### ISSUE TITLE
genes associated to nerve growth factor binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#10]
nerve growth factor receptor binding
Accession:GO:0005163
Synonyms:
nerve growth factor receptor ligand
neurotrophin
NGF receptor binding 

Genes: fgf2 and fgf5

How comes fibroblast growth factors are associated to
that term?

I suggest:

for the receptor side:

low affinity nerve growth factor receptor
Ensembl Gene: ENSG00000064300

tropomyosine related kinase A
ENSG00000117029 

tropomyosine related kinase B
ENSG00000148053 

tropomyosine related kinase C
ENSG00000140538 

for the ligand side:

nerve growth factor 
ENSG00000134259

brain derived neurotrophic factor
ENSG00000176697

neurotrophin 3
ENSG00000185652  

neurotrophin 4
ENSG00000167744

Reported by: lenov

Original Ticket: "geneontology/annotation-issues/10":https://sourceforge.net/p/geneontology/annotation-issues/10

**Comment by linuxlovell** [comment]
thanks www.movied.org
