### ISSUE TITLE
SPKW: amino acid metabolic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1004]
http://www.yeastgenome.org/cgi-bin/GO/goAnnotation.pl?dbid=S000000288\#computational

is involved in
folic acid biosynthetic process
not amino acid

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1005](https://sourceforge.net/p/geneontology/annotation-issues/1005)

**Comment by mcourtot** [comment]
@Val: can you confirm status?

**Comment by ValWood** [comment]
still there

**Comment by mcourtot** [comment]
Do you have a link to the uniprot entry? the above is dead for me.

**Comment by ValWood** [comment]
I couldn't track the UniProt ID for the SGD entry, here's the l entry for the pombe ortholog. Same issue.
http://www.uniprot.org/uniprot/O43007

**Comment by mcourtot** [comment]
Action: remove KW-0028 from O43007

**Comment by penso** [comment]
@mcourtot You dont want to bother @Val using his nickname but should use @ValWood instead.

**Comment by penso** [comment]
Every time you used @Val in this thread, he got a notification about it.

**Comment by ValWood** [comment]
This might be out of date! I will check in  a minute

**Comment by ValWood** [comment]
MIS1
https://www.yeastgenome.org/locus/S000000288/go#comp
still has

involved in | cellular amino acid biosynthetic process |   | IEA with KW-0028 | UniProt | 2020-11-28 | UniProt-GOA (2012)
involved in | methionine biosynthetic process |   | IEA with KW-0486
involved in | histidine biosynthetic process |   | IEA with KW-0368

**Comment by sylvainpoux** [comment]
Hi Val,
I removed the KWs in MIS1 and ade9 entries
Thanks
Sylvain

**Comment by suzialeksander** [comment]
resolved.
