### ISSUE TITLE
P41250 GARS

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1014]
This gene product does not  have
Diadenosine tetraphosphate synthetase activity
but it does have the process term
diadenosine tetraphosphate biosynthetic process

should it have both \(or neither\)?
\(I'm trying to figure out if I should allow this in an intersect but I need to know if the process term would be valid first\)

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1015](https://sourceforge.net/p/geneontology/annotation-issues/1015)

**Comment by mcourtot** [comment]
@ValWood: can you please submit on the ontology tracker if you still wish to request this term?
Thanks,
Melanie
