### ISSUE TITLE
	P49373 not DNA binding (SP-KW)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1024]
transcription elongation factor TFIIS 
is mapping to 
GO:0003677  DNA binding IEA KW-0238
but it doesn't apper to be a DNA binding TF (although does bind RNA, in mRNA cleavage?)

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1025](https://sourceforge.net/p/geneontology/annotation-issues/1025)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
Still there
http://www.uniprot.org/uniprot/P49373

**Comment by mcourtot** [comment]
Action: remove KW-0238 from P49373

**Comment by ValWood** [comment]
Note that  when these fixes are implemented they do not ONLY affect the proteins with the reported problem, but all of the orthologs which the KW is transferred to.

**Comment by ValWood** [comment]
transferred to 
https://github.com/geneontology/go-annotation/issues/1503
