### ISSUE TITLE
SPKW repair DNA  repair false positives/matrix

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1032]
RPL40A UniProt:P0CH09 (and RPL40B) have SPKW mappings to "DNA repair" which looks wrong for the ribosome-ubiquitin fusion protein?

also RPS31 (UniProtKB:P05759)

and DNA-directed RNA polymerase II subunit RPB4 (P20433)

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1033](https://sourceforge.net/p/geneontology/annotation-issues/1033)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
still there

**Comment by mcourtot** [comment]
Action: remove KW-0234 from P20433, Q8VC56, Q80XJ2

**Comment by ValWood** [comment]
Transferred to "off target" KW mappign ticket
https://github.com/geneontology/go-annotation/issues/1503
