### ISSUE TITLE
DNA replication	IEA	UniProtKB:KW-0235

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1048]
This particular ligase (lig4) has an IEA to 
DNA replication, but it is a  repair specific ligase

O74833

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1049](https://sourceforge.net/p/geneontology/annotation-issues/1049)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
Still there.
Also recombination...

**Comment by mcourtot** [comment]
Action: remove KW-0235, KW-0233 from O74833

**Comment by ValWood** [comment]
Closing, out of date, will add to filtered mappings for Matrix project paper.
