### ISSUE TITLE
SPKW mapping to DNA repair

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1052]
- [x] I don't think that set1 (pombe) Q9Y7R4
is involved in DNA repair (it is involved in detection of checkpoint, which is upstream)

thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1053](https://sourceforge.net/p/geneontology/annotation-issues/1053)

**Comment by mcourtot** [comment]
Still there.Tagging.

Action: Remove KW-0234 from P04910

**Comment by ValWood** [comment]
fixed , closing
