### ISSUE TITLE
O74991 not  GO:0006355 regulation of transcription, DNA-dependent	

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1058]
O74991  pof3
has IEA
GO:0006355  regulation of transcription, DNA-dependent  IEA UniProtKB:KW-0805
but we don't see any evidence for this in fission yeast?

VAl

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1060](https://sourceforge.net/p/geneontology/annotation-issues/1060)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
still there. I can see where this comes from, but its weak  for  a mapping (really only warrants a phenotype).

**Comment by mcourtot** [comment]
Action: remove KW-0805 from O74991

**Comment by sylvainpoux** [comment]
Done (KW removed)
