### ISSUE TITLE
O74737 (rid1) mapping to nucleus  	SL-0191

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1059]
I can't find any evidence that rid1 is nuclear and it doesn't seem likely
Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1061](https://sourceforge.net/p/geneontology/annotation-issues/1061)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
still there
http://www.uniprot.org/uniprot/O74737

This is derived from a genome-wide localization study. We think its a false positive and removed it from this dataset. It has quite a few FP's and its probably not a good source of mapping data

**Comment by mcourtot** [comment]
Action: remove SL-0191 from O74737

**Comment by Antonialock** [comment]
fixed

**Comment by Antonialock** [comment]
(it will take a while before these fixes filter through)
