### ISSUE TITLE
	SL-0455 mappings to septum for fission yeast

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1060]
SL-0455 is used to map a number of fission yeast gene products to the septum, but these are not really septum proteins (they are medial cortex, so they are close to the septum, but they aren't septum components)

Includes
blt1    O74338

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1062](https://sourceforge.net/p/geneontology/annotation-issues/1062)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
still there for tea3, presume for the others too
http://www.ebi.ac.uk/QuickGO/GProtein?ac=O14248

**Comment by Antonialock** [comment]
fixed, not sure how long it ill take before it filters through.
