### ISSUE TITLE
Pombe Gua2	not GO:0006541 glutamine metabolic process UniProtKB:KW-0315 (is GMP biosynthesis?)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1063]
https://www.pombase.org/gene/SPAP7G5.02c
http://www.uniprot.org/uniprot/Q9P772

UniProtKB:KW-0315
mapping looks incorrect
it is GO:0006177    GMP biosynthetic process?
v

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1065](https://sourceforge.net/p/geneontology/annotation-issues/1065)

**Comment by mcourtot** [comment]
Still there. http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q9P772 Tagging.

Action: Remove UniProtKB:KW-0315 from Q9P772.

**Comment by sylvainpoux** [comment]
I'm not sure to understand here: Q9P772 is a Glutamine amidotransferase and the KW 'Glutamine amidotransferase' looks correct.

Should the mapping to GO be changed into GO:0003922; F:GMP synthase (glutamine-hydrolyzing) activity;?

If it is the case, please forward the request to George

Thanks

Sylvain

**Comment by ggeorghiou** [comment]
I'm on agreement with Sylvain. The keyword is correct, and the mapping can use a bit of refinement. I think @sylvainpoux suggestion is correct to change the mapping from GO:0006541 to GO:0003922. I've gone ahead and done this.

**Comment by ValWood** [comment]
Sorry got it, glutamine is the N-donor...
