### ISSUE TITLE
UniProtKB:G2TRT3  mapping to protein transport UniProtKB:KW-0653

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1072]
There does not appear to be any evidence for this (it was only recently discovered, there is no functional info and no similarity)
    UniProtKB:KW-0653
val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1074](https://sourceforge.net/p/geneontology/annotation-issues/1074)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
still there
http://www.uniprot.org/uniprot/G2TRT3

transport unlikely, its this family:
http://pfam.xfam.org/family/PF06624

**Comment by Antonialock** [comment]
pmid:10601334 

Together these results suggest that the stabilization of membrane proteins during and after ER stress involves the concerted action of a rescue unit in the ER membrane comprised of SERP1/RAMP4, components of the translocon such as Sec61α and Sec61β, and ER chaperons, such as calnexin.
