### ISSUE TITLE
mapping to UniProtKB:KW-0236 negative regulation of DNA replication for 	P87074

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1076]
P87074 crb2 SPBC342.05

I don't think that this negatively regulates DNA replication?
 
It is involved in mitotic G2 DNA damage checkpoint which 
negatively regulates progression through the G2/M transition of the cell cycle in response to DNA damage

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1078](https://sourceforge.net/p/geneontology/annotation-issues/1078)

**Comment by mcourtot** [comment]
@ValWood: can you please check status?

**Comment by ValWood** [comment]
Actually, this one is OK
