### ISSUE TITLE
mapping of UniProtKB:KW-0234 to repair

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1077]
Q10325 histone acetyltransferase Mst2 
(Is mapped to DNA repair but this doesn't appear to be the casein fission yeast is involved in maintenance of centrometic heterochromatin, and in DNA damage chackpoint activation)

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1079](https://sourceforge.net/p/geneontology/annotation-issues/1079)

**Comment by mcourtot** [comment]
@ValWood : seems to be fixed: http://www.uniprot.org/uniprot/Q10325
