### ISSUE TITLE
plasma membrane	IEA	SL-0039 source

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1084]
Fission yeast ypt1 is mapped to "plasma membrane"
Do you have a source for this (it doesn't seem correct for pombe or cerevisiae from current data?)

Many thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1086](https://sourceforge.net/p/geneontology/annotation-issues/1086)

**Comment by mcourtot** [comment]
Seems fixed, http://www.ebi.ac.uk/QuickGO/GProtein?ac=P11620
