### ISSUE TITLE
GO:0005635	nuclear envelope	IEA	SL-0178 uniprot mappign rng2

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1087]
O14188 has a mapping to nuclear envelope but it isn't a nuclear envelope protein

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1089](https://sourceforge.net/p/geneontology/annotation-issues/1089)

**Comment by mcourtot** [comment]
Still there, tagging. http://www.uniprot.org/uniprot/O14188

Action: remove KW-0717 from O14188
