### ISSUE TITLE
SPKW mapping to DNA replication for dre4 Q09685

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1093]
Has a KW mapping to "DNA replication"
this is indirect, its actually a splicosomal protein

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1095](https://sourceforge.net/p/geneontology/annotation-issues/1095)

**Comment by mcourtot** [comment]
Still there, tagging. http://www.uniprot.org/uniprot/Q09685

Action: remove KW-0235 from Q09685

**Comment by pgaudet** [comment]
@sylvainpoux removed the KW
