### ISSUE TITLE
is antibody x-reaction an ISS?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#11]
I'd like to discuss the issue of whether or not people
think antibody cross-reactivity is good enough for ISS.
For example, I have been reading many papers that use
mouse, human and rat tissue or cell lines to assay  the
function, location and process of a gene product that
is assayed for by cross-reactivity of an antibody. How
far should we carry the cross-species annotations based
on this kind of evidence?

David

Reported by: ukemi

Original Ticket: "geneontology/annotation-issues/11":https://sourceforge.net/p/geneontology/annotation-issues/11

**Comment by linuxlovell** [comment]
thanks www.movied.org
