### ISSUE TITLE
InterPro glycolysis

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1100]
I think this one needs removing?
Val

PomBase    SPAC186.08c    SPAC186.08c        GO:0006096    GO_REF:0000002    IEA    InterPro:IPR011304    P    L-lactate dehydrogenase (predicted)        protein    taxon:4896    20130720    InterPro

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1104](https://sourceforge.net/p/geneontology/annotation-issues/1104)

**Comment by mcourtot** [comment]
Seems fixed: http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q9P7P7
