### ISSUE TITLE
P36627 mapping to DNA binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1103]
Is a CCHC-type zinc finger, but is mRNA binding not DNA binding 
thanks

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1107](https://sourceforge.net/p/geneontology/annotation-issues/1107)

**Comment by mcourtot** [comment]
Still there, tagging. http://www.ebi.ac.uk/QuickGO/GProtein?ac=P36627

Action: remove KW-0238 from P36627

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-annotation/issues/1503
