### ISSUE TITLE
	O94640 DNA repair/ indirect UniProtKB-KW:KW-0234

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1108]
note that this EXP  annotation has been removed from SGD SIR2

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1115](https://sourceforge.net/p/geneontology/annotation-issues/1115)

**Comment by mcourtot** [comment]
Still there, tagging. http://www.ebi.ac.uk/QuickGO/GProtein?ac=O94640

Action: remove KW-0234 from O94640
