### ISSUE TITLE
complete and ref in sync for GOA human?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1113]
complete has annotations to post-synaptic density for the MYD88 gene. One annotation is to the ref (J3KQJ6)

$ grep MYD88 14-Oct-2013/gene_association.goa_human | grep GO:0014069
UniProtKB       H0Y4G9  MYD88           GO:0014069      GO_REF:0000019  IEA     Ensembl:ENSRNOP00000018341      C       Myeloid differentiation primary response protein MyD88  H0Y4G9_HUMAN|MYD88      protein   taxon:9606      20131012        Ensembl 
UniProtKB       J3KQJ6  MYD88           GO:0014069      GO_REF:0000019  IEA     Ensembl:ENSRNOP00000018341      C       Myeloid differentiation primary response protein MyD88  J3KQJ6_HUMAN|MYD88      protein   taxon:9606      20131012        Ensembl 

However this annotation is not present in the ref file

Reported by: cmungall

Original Ticket: [geneontology/annotation-issues/1120](https://sourceforge.net/p/geneontology/annotation-issues/1120)

**Comment by mcourtot** [comment]
@cmungall , @ValWood : should this be closed as we're overhauling the ensemble pipeline?

**Comment by ValWood** [comment]
I guess it could be.  But in these cases I would prefer to keep the ticket and flag as needing checking after the new orthology pipeline is in place so we can be sure that any existing problems were properly addressed.

**Comment by cmungall** [comment]
Yes, the problem is still outstanding. We would like to switch to ref, but we would like our annotations to be complete. When will the new pipeline be in place?

**Comment by cmungall** [comment]
Hopefully this can be discussed at the GO meeting.

Note we have 20 different identifiers for human BRCA1 right now, in goa_human

**Comment by cmungall** [comment]
Here is my understanding, based on cursory analysis, not sure if this is documented:

 * ensembl predictions spread across multiple proteins, not just the GCRP
 * HPA IDAs spread across multiple proteins, not just the GCRP
 * experimental annotations from other sources get duplicated across multiple members, not just the GCRP. E.g.:

```
UniProtKB       E7ENE1  IL12A           GO:0032946      PMID:11023671   IMP             P       Interleukin-12 subunit alpha    E7ENE1_HUMAN|IL12A      protein taxon:9606      20140513        AgBase      
UniProtKB       E9PGR3  IL12A           GO:0032946      PMID:11023671   IMP             P       Interleukin-12 subunit alpha    E9PGR3_HUMAN|IL12A      protein taxon:9606      20140513        AgBase      
UniProtKB       P29459  IL12A           GO:0032946      PMID:11023671   IMP             P       Interleukin-12 subunit alpha    IL12A_HUMAN|IL12A|NKSF1 protein taxon:9606      20140513        AgBase      
```

**Comment by pgaudet** [comment]
@cmungall 
@tonysawfordebi 
@ggeorghiou 
What is the status on this one ? 

Thanks, Pascale

**Comment by ValWood** [comment]
@cmungall Spotted this old one while trying to find my duplicate "GAF" tickets

This is no longer an issue as far as I'm aware...can close?

**Comment by suzialeksander** [comment]
@cmungall it sounds like this was resolved 8 years ago, can you confirm?
