### ISSUE TITLE
	UniProtKB-KW:KW-0415 karyogamy

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1116]
pombe   P40383 is mapped by IEA to karyogamy.
This seems to be indirect?

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1123](https://sourceforge.net/p/geneontology/annotation-issues/1123)

**Comment by mcourtot** [comment]
Still there. http://www.ebi.ac.uk/QuickGO/GProtein?ac=P40383

Action: remove KW-0415 for P40383
