### ISSUE TITLE
	P40383 microtubule UniProtKB-KW:KW-0493

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1119]
S. pombe exo2 (exonuclease) has a mapping to microtubule. I can't find any evidence for this, could you take a look and remove if appropriate.

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1126](https://sourceforge.net/p/geneontology/annotation-issues/1126)

**Comment by mcourtot** [comment]
Still there. http://www.ebi.ac.uk/QuickGO/GProtein?ac=P40383

Action: remove KW-0493 from P40383

**Comment by ValWood** [comment]
appears to be fixed

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-annotation/issues/1503
