### ISSUE TITLE
P32747 NOT integral  to membrane

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1144]
I  can't find anything to indicate
P32747 is integral  to membrane

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1156](https://sourceforge.net/p/geneontology/annotation-issues/1156)

**Comment by mcourtot** [comment]
@ValWood  Still there. http://www.ebi.ac.uk/QuickGO/GProtein?ac=P32747

Action: remove KW-0812 from P32747

**Comment by ValWood** [comment]
Fixed because the term was obsoleted
