### ISSUE TITLE
SP_KW:KW-0804 mapping to recombination (Matrix QG project)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1145]
E. coli ArgR has a mapping to recombination, (is this correct , it looks quite indirect?)

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1157](https://sourceforge.net/p/geneontology/annotation-issues/1157)

**Comment by mcourtot** [comment]
@ValWood still there, http://www.ebi.ac.uk/QuickGO/GProtein?ac=P0A6D0

Action: remove KW-0804 from P0A6D0
