### ISSUE TITLE
Q9USU1, Q9UTN4, P40847, Q9P7C8  O13927 KW mapping to  chromsome segregation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1177]
Hi @pedruzzi 

The KW assignment for these entries seems to be based on phenotypes and be rather indirect. Can you please check if the KW is appropriate ? 

Original Ticket: [geneontology/annotation-issues/1194](https://sourceforge.net/p/geneontology/annotation-issues/1194)

**Comment by ValWood** [comment]
moved to
https://github.com/geneontology/go-annotation/issues/1503

**Comment by ValWood** [comment]
These were don in the other ticket.
v
