### ISSUE TITLE
UniProtKB-KW:KW-0238 poz1 not DNA binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1178]
Hi ,

I don't think that poz1 binds to DNA directly...if not could this mapping be removed?

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1195](https://sourceforge.net/p/geneontology/annotation-issues/1195)

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-annotation/issues/1503
