### ISSUE TITLE
transferase KW mappings

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1194]
UniProtKB-KW:KW-0808

The following pombe proteins do not appear to be transferases, could you take a look?
Thanks

cys11 O59701 (is a lyase)
cys12

aim22 (isa ligase)
SPAC6G10.03c (is a hydroalse)
ykt6 (is a ANAP receptor, not catalytic?)
naa15 (acetyltransferase activator- (regulatory subunit)

trp1 (lyase and isomerase)
rib4 (isomerase)

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1212](https://sourceforge.net/p/geneontology/annotation-issues/1212)

**Comment by ValWood** [comment]
transferred to 
https://github.com/geneontology/go-annotation/issues/1503
