### ISSUE TITLE
query about hyperacetylation vs acetylation & genomic locati

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#12]
Is it possible to capture annotations using go for a
gene which is involved in

acetylation of 'histone H3 in the whole of the genome'

AND

M26-specific hyperacetylation.

(PMID:14988732)

I can't think of a way to capture this information with
existing terms

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/12":https://sourceforge.net/p/geneontology/annotation-issues/12

**Comment by linuxlovell** [comment]
thanks www.movied.org
