### ISSUE TITLE
GO:0016874	ligase activity	IEA	UniProtKB-KW:KW-0436

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1209]
Hi

Some ubiquitin conjugating enzymes, and ubiquitin ligases have the annotation
mapping to ligase,

but despite the name they are actually 'transferases" not ligases....
e.g P46595
but I suspect there will be lots....

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1228](https://sourceforge.net/p/geneontology/annotation-issues/1228)

**Comment by ValWood** [comment]
I think these are fixed
