### ISSUE TITLE
	O13858 mapping to cell wall and extracellular region

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1213]
Is eisosome component , could   UniProtKB-KW:KW-0134 and    UniProtKB-KW:KW-0964
be removed

Thanks

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1232](https://sourceforge.net/p/geneontology/annotation-issues/1232)

**Comment by ValWood** [comment]
seem to be fixed.
