### ISSUE TITLE
large number of mappings to "meiotic nuclear division" from UniProtKB-KW:KW-0469

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1216]
UniProtKB-KW:KW-0469
is mapping a large number of gene products to

meiotic nuclear division
One of the two nuclear divisions that occur as part of the meiotic cell cycle."

including
ght6    SPCC1235.13 hexose transporter Ght6
mug58   SPAC630.09c GLYK family kinase of unknown specificity (predicted)
atg2    SPBC31E1.01c    autophagy associated protein Atg2
mug65   SPAC1296.04 spore wall assembly protein (predicted)
smc6    SPCC5E4.06  Smc5-6 complex SMC subunit Smc6
kms2    SPBC947.12  spindle pole body protein Kms2
mug103  SPAC22A12.02c   Schizosaccharomyces specific protein Mug103
SPAC10F6.15 SPAC10F6.15 UPF0300 family protein 1
psf2    SPBC725.13c GINS complex subunit Psf2
mug24   SPCC74.09   RNA-binding protein, rrm type
mug133  SPAC4G9.07  S. pombe specific UPF0300 family protein 2
meu26   SPAC6B12.16 conserved fungal protein
rfp1    SPAC19A8.10 SUMO-targeted ubiquitin-protein ligase subunit Rfp1

possibly a few 100 in total. Consider "meiotic cell cycle"
but some of these are based on expression levels only and should probably be deleted.

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1235](https://sourceforge.net/p/geneontology/annotation-issues/1235)

**Comment by ValWood** [comment]
this was done
