### ISSUE TITLE
UniPathway:UPA00378 not protein glycosylation (Matrix)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1218]
Q9P7C3  has   a mapping to protein glycosylation, but is involved in protein deglycosylation

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1237](https://sourceforge.net/p/geneontology/annotation-issues/1237)

**Comment by pgaudet** [comment]
@ValWood OK to close?

**Comment by ValWood** [comment]
Can we keep this one open? its an annotation conundrum that I would like to think about!
I'll take the ticket  from Ivo and try to figure it  out.

**Comment by ValWood** [comment]
@pgaudet  I will close this ticket. It should be resolved by separating MF's from BPs  this arose because of the confusion between specific activities and broader pathways.
