### ISSUE TITLE
DNA polymerase zeta catalytic NOT DNA replication, multiple mappings

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1219]
A.F.I.K DNA polymerase zeta  is a repair polymerase only?
val

UniProtKB   Q9P6L6  rev3        GO:0006261  GO_REF:0000003  IEA EC:2.7.7.7  P   DNA polymerase zeta catalytic subunit   DPOZ_SCHPO|rev3|SPAC688.10  protein taxon:284812    20140920    GOC     

UniProtKB   Q9P6L6  rev3        GO:0006261  GO_REF:0000037  IEA UniProtKB-KW:KW-0239    P   DNA polymerase zeta catalytic subunit   DPOZ_SCHPO|rev3|SPAC688.10  protein taxon:284812    20140920    GOC     

UniProtKB   Q9P6L6  rev3        GO:0006260  GO_REF:0000037  IEA UniProtKB-KW:KW-0235    P   DNA polymerase zeta catalytic subunit   DPOZ_SCHPO|rev3|SPAC688.10  protein taxon:284812    20140920    UniProt 

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1238](https://sourceforge.net/p/geneontology/annotation-issues/1238)

**Comment by ValWood** [comment]
SP KW mappings remain, this KW is already on my blacklist for other errors
https://github.com/geneontology/go-annotation/issues/1503

**Comment by ValWood** [comment]
rev3 stil;l has replication:

UniProtKB:Q9P6L6 | rev3 | involved_in | GO:0006260    DNA replication | ECO:0000322   IEA | GO_REF:0000043 | UniProtKB-KW:KW-0235 | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | UniProt

**Comment by ValWood** [comment]
2019 paper
https://academic.oup.com/nar/article/47/16/8348/5549710

We also highlight recent evidence that uncovers various roles of pol ζ that extend beyond translesion synthesis. For instance, pol ζ is also employed when the replisome operates sub-optimally or at difficult-to-replicate DNA sequences.

so closing
