### ISSUE TITLE
SPKW mapping 	Q9UT52 UniProtKB-KW:KW-0717 barrier septum assembly

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1222]
Isn't barrier septum assembly?
Val

Will send to UniProt.

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1241](https://sourceforge.net/p/geneontology/annotation-issues/1241)

**Comment by pgaudet** [comment]
@sylvainpoux suggests moving to 'regulation' 
@ValWood will ask the community
@pgaudet suggests that this is an issue with regulation versus causality

**Comment by pgaudet** [comment]
Hi @ggeorghiou - 

based on the suggestions in the previous comment, can you make a suggestion as to how to move forward with this ? 

It seems like the question is really how Uniprot assigns this KW. The usage seems broader that what GO does.

**Comment by Antonialock** [comment]
I've fixed these

mod21 - removed
Tea3 -  removed
rng2 - changed to cell division
nsp1 - removed and changed function comment to phenotype, Also removed cell cycle from cerevisiae ortholog
cam2 - removed
alp4 - removed
myo1 - it doesn't look like this protein has this kw any longer.
rng3 - changed to cell division
