### ISSUE TITLE
Remove extracellular annotations where cell was experimentally lysed

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1226]
See http://jira.geneontology.org/browse/GO-613

These annotations are (unless I am mistaken) wrong

Reported by: cmungall

Original Ticket: [geneontology/annotation-issues/1245](https://sourceforge.net/p/geneontology/annotation-issues/1245)

**Comment by pgaudet** [comment]
@cmungall How would you identify annotations made from specific experiments ? 
I don't see the action here. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I spot checked a few annotations, and it would be useful but tricky work. Some example of proteins annotated to both extracellular and intracellular: 


dictyBase:DDB_G0276821 | both HDA
-- | --
SGD:S000006044 | both localizations seem correct
UniProtKB:P9WIE5 | fixed PAINT - original data HTTP
PomBase:SPBP4G3.02 | I dont understand why this shows up - all annot look extracellular to me
UniProtKB:P9WIH3 | inconsistent extracellular HDA
PomBase:SPAC14C4.09 | looks like it's a 'temporary' location

**Comment by mah11** [comment]
> PomBase:SPBP4G3.02 I don't understand why this shows up - all annot look extracellular to me

Where are you looking? On the [PomBase gene page](https://www.pombase.org/gene/SPBP4G3.02) and in AmiGO, this gene has experimentally-supported annotations to 'extracellular region' and several intracellular CCs.

> PomBase:SPAC14C4.09 looks like it's a 'temporary' location

Which location looks temporary? The two IDA intracellular annotations come from some of our best community curators, and reflect localizations where [agn1](https://www.pombase.org/gene/SPAC14C4.09) likely acts. The 'extracellular region' annotation is from a slightly older paper but I double-checked it and it doesn't look like an error (figure 2 in [PMID:15194814](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC491845/) ).

**Comment by pgaudet** [comment]
Out of date
