### ISSUE TITLE
PAINT:Ionotropic Glutamate Receptors. PTN001056595 & PTN001056621

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1228]
Hi,

The PAINT annotations for Ionotropic Glutamate Receptors (iGluR) & Ionotrpic Receptors (IR) in D.mel have a mixture of problems - inappropriate NOT annotations, highly specific molecular functions, IRs with iGluR terms and vice versa.

Drosophila have the typical iGluRs that fall into the kainate, AMPA, NMDA subclasses and Ionotropic Receptors (IR). IRs are a variant subfamily of ionotropic glutamate receptors which lack conserved glutamate-interacting residues found throughout the protostome lineage. They can been dived into two subgroups: (1) antennal - olfactory receptors expressed in the antenna and, (2) divergent - largely species-specific, with low amino acid sequence identity. Expressed in gustatory organs, they are believed to be taste receptors.

PMID:21220098 has a good evolutionary tree.

Issues:

A. Ionotropic Receptors being given NOT annotations for iGluR attributes. 

As these receptors are known to not bind glutamate, it's misleading to give this annotation - they are a distinct class in their own right. NOTs are perhaps not appropriate for PAINT - we would only use them when it is surprising that X does not do Y using IKR or experimental evidence codes and to point to conflicting evidence. 

e.g. Ir100 from PANTHER:PTN001056595
NOT     GO:0004970  ionotropic glutamate receptor activity  
NOT     GO:0005234  extracellular-glutamate-gated ion channel
NOT  GO:0008328 ionotropic glutamate receptor complex
NOT  GO:0035235 ionotropic glutamate receptor signaling pathway
NOT  GO:0035249 synaptic transmission, glutamatergic
NOT  GO:0045211 postsynaptic membrane

(D.mel genes: Ir100a, Ir10a, Ir21a, Ir40a, Ir41a, Ir52c, Ir60a, Ir60e, Ir64a, Ir67b, Ir67c, Ir68a, Ir75d, Ir76a, Ir76b, Ir7c, Ir7e, Ir7g, Ir87a, Ir92a, Ir93a)

B. Ionotropic Receptors being given iGluR annotations.
PANTHER:PTN001056621
e.g. Ir94d

GO:0005234   extracellular-glutamate-gated ion channel
GO:0035235   ionotropic glutamate receptor signaling pathway
GO:0035249   synaptic transmission, glutamatergic
GO:0045211   postsynaptic membrane

(D.mel genes: Ir11a, Ir25a, Ir31a, Ir54a, Ir75a, Ir75b, Ir75c, Ir7a, Ir7b, Ir7d, Ir7f, Ir8a, Ir94d)

C. Annotation with "extracellular ammonia-gated ion channel activity" GO:0036081

This is based on one D.mel IR - Ir92a. As far as I know, this is the only ammonia-gated IR. But all annotations for PANTHER:PTN001056595 have this.
(D.mel genes: Ir100a, Ir10a, Ir21a, Ir40a, Ir41a, Ir52c, Ir60a, Ir60e, Ir64a, Ir67b, Ir67c, Ir68a, Ir75d, Ir76a, Ir76b, Ir7c, Ir7e, Ir7g, Ir87a, Ir92a, Ir93a).

Not really happy with any IBA annotation made from just one source - I would regard a 1:1 relationship such as this as an ISS, with all the associated background work to confirm its orthology/homology. But this one is really very specific, so shouldn't happen.

D. iGluRs annotated with NOT annotations for iGluR attributes and extracellular ammonia-gated ion channel activity. Again from PANTHER:PTN001056595.

CG11155 - Kainate iGluR family
CG9935 - kainate iGluR family

NOT  GO:0004970 ionotropic glutamate receptor activity  
NOT  GO:0005234 extracellular-glutamate-gated ion channel
NOT  GO:0008328 ionotropic glutamate receptor complex
NOT  GO:0035235 ionotropic glutamate receptor signaling pathway
NOT  GO:0035249 synaptic transmission, glutamatergic
NOT  GO:0045211 postsynaptic membrane

Regards,

Helen

p.s. I've just cleaned-up the D.mel IRs annotation, removing a few old incorrect ISS/NAS and up-dated the experimental-based annotations.

Reported by: hattrill

Original Ticket: [geneontology/annotation-issues/1247](https://sourceforge.net/p/geneontology/annotation-issues/1247)

**Comment by selewis** [comment]
Not sure where this stands right now. Neither PTN1056595 nor PTN1056621 currently remain in the PANTHER tree files. 

When I search the PANTHER db for Ir11a the family is PTHR11866, which has been annotated. But, within PTHR11866, the node for PTN001056193 disappeared between v10 and v11 of PANTHER and annotations to NMDA selective glutamate receptor complex and NMDA glutamate receptor were consequently lost. Those others must have disappeared between earlier PANTHER releases. 

The only real solution is for someone to review the annotations of this family (and it is a largish family with 1734 nodes).

**Comment by pgaudet** [comment]
I noted in the google spreadsheet that this one needs to be reannoated.

**Comment by thomaspd** [comment]
Drosophila ir11a is now in PTHR42643, which has not been painted yet. The original family was subdivided because it was too diverse for an accurate alignment, but the annotations were (correctly) removed.

**Comment by hattrill** [comment]
Glutamate receptor terms have returned for these:
PANTHER:PTN000438080
FBgn0261401	Ir75c	
FBgn0052704	Ir8a	
FBgn0037501	Ir84a	
FBgn0035604	Ir64a	
FBgn0051718	Ir31a	
FBgn0036757	Ir75a	
FBgn0031634	Ir25a	
FBgn0036937	Ir76b	
FBgn0036829	Ir75d	
FBgn0031209	Ir21a
PANTHER:PTN001826301
FBgn0259215	Ir93a

Attaching a list of all our ionotrophic receptors for blocking such terms.
[IR_fly.txt](https://github.com/geneontology/go-annotation/files/3265583/IR_fly.txt)

**Comment by marcfeuermann** [comment]
PTHR18966 has been reviewed and propagation of glutamate receptor terms excluded from nodes containing many duplications.  The above-mentioned genes are no more associated with glutamate receptor terms. FBgn0051718 Ir31a is no more part of a PANTHER family in the new PANTHER version. PTHR18966 is a huge and complicated family that needs to be checked at every PANTHER update.

**Comment by hattrill** [comment]
Thanks, Marc!
