### ISSUE TITLE
query about F-P links

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1230]
GO:0004129 - cytochrome-c oxidase activity has an FP link to hydrogen ion transmembrane transport. I have 11 gene products annoyed to GO:0004129
but only 4 are pricking up this mapping. cox1,2,3,5 Why is that?

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1249](https://sourceforge.net/p/geneontology/annotation-issues/1249)

**Comment by ValWood** [comment]
Is this because mappings d not propagate across non-experimental evidence codes?

If so, shouldn't they?

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14674
