### ISSUE TITLE
F-P link GO:0019888	protein phosphatase regulator activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1232]
Could it go to

part_of
GO:0043666  regulation of phosphoprotein phosphatase activity

and
GO:0004864 - protein phosphatase inhibitor activity
to
negative regulation of phosphoprotein phosphatase activity

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1251](https://sourceforge.net/p/geneontology/annotation-issues/1251)

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14673
