### ISSUE TITLE
UniProt KW mapping to mRNA processing

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1234]
The following PomABse genes are annotated to mRNA processing
via KW:KW-0507
but 
decapping is part of  mRNA catabolism which isn't processing.

Processing is defined
"Any process involved in the conversion of a primary mRNA transcript into one or more mature mRNA(s) **_prior**_\* to translation into polypeptide." 

PomBase SPAC19A8.12 dcp2        GO:0006397  GO_REF:0000037  IEA UniProtKB-KW:KW-0507    P   mRNA decapping complex catalytic subunit Dcp2       protein taxon:4896  20141025    UniProt  
PomBase SPBC19G7.10c    ppo1        GO:0006397  GO_REF:0000037  IEA UniProtKB-KW:KW-0507    P   topoisomerase II-associated deadenylation-dependent mRNA-decapping factor (predicted)       protein taxon:4896  20141025    UniProt  
PomBase SPBC3D6.08c lsm1        GO:0006397  GO_REF:0000037  IEA UniProtKB-KW:KW-0507    P   mRNA decapping complex subunit (predicted)      protein taxon:4896  20141025    UniProt  
PomBase SPBC3B9.21  dcp1        GO:0006397  GO_REF:0000037  IEA UniProtKB-KW:KW-0507    P   mRNA decapping complex regulatory subunit Dcp1      protein taxon:4896  20141025    UniProt     

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1253](https://sourceforge.net/p/geneontology/annotation-issues/1253)

**Comment by ValWood** [comment]
transferred to
https://github.com/geneontology/go-annotation/issues/1503
