### ISSUE TITLE
mapping to chromatin modification UniProtKB-KW:KW-0156

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1246]
A number of pombe proteins annotated to "chromatin modification" don't appear to be chromatin modifiers (some are involved in assembly, but not modifcation).

here is the list

rbx1
elp3
hip4
slm9
mis16
hip1
SPAC15E1.10

thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1266](https://sourceforge.net/p/geneontology/annotation-issues/1266)

**Comment by ValWood** [comment]
see https://github.com/geneontology/go-annotation/issues/1503
