### ISSUE TITLE
HAMAP mapping O13814 Ermes complex "protein complex assembly" 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1249]
There is a mapping HAMAP:MF_03102 to map mdm10 O13814 Ermes complex sununit to "protein complex assembly". Is there a ref for this?

thanks
Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1269](https://sourceforge.net/p/geneontology/annotation-issues/1269)

**Comment by pedruzzi** [comment]
Guess that is based on this: PubMed:15239954, and should be refined to the child GO:0070096; P:mitochondrial outer membrane translocase complex assembly

**Comment by pedruzzi** [comment]
fix:
updated the term in MF_03102 to GO:0070096; P:mitochondrial outer membrane translocase complex assembly
