### ISSUE TITLE
UniProtKB-KW:KW-0324 not pyruvate dehydrogenase (acetyl-transferring) activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1254]
Hi,

UniProtKB-KW:KW-0324 is a mapping to a  pyruvate dehydrogenase (acetyl-transferring) activity

(glycolytic process ends at pyruvate)

thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1274](https://sourceforge.net/p/geneontology/annotation-issues/1274)

**Comment by ValWood** [comment]
This mapping is still present.  This doesn't seem as though it should be mapped to glycolytic process.  @Antonialock Do you agree?

**Comment by Antonialock** [comment]
Yes I agree and will remove this keyword for any protein annotated to EC 1.2.4.1, EC 2.3.1.12 and EC 1.8.1.4

these correspond to the E1 E2 and E3 subunits of the PDC complex. It will probably take a while to filter through.

**Comment by Antonialock** [comment]
a few protens also had TCA cycle which I removed
