### ISSUE TITLE
EC mapping  RNA polymerase II carboxy-terminal domain kinase activity to	EC:2.7.11.23

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1258]
A couple of us at PomBase  have been curious about  this mapping. I checked with an expert and as far as we know  pombe cdc2 (cdk1)  P04551 is not known to phosphorylate RNA polymerase CTD.

We think that this mapping is derived from another cdk,  (mcs6 in pombe) which is an RNA pol kinase. So, this mapping doesn't appear to hold for all mapped entries. (this migh be because all cyclin dependent kinases are mapped to this term, but not all cylin dept kinases are rnA pol II kinases).

Antonia (PomBase) pointed out that RNA pol2 kinases as not phosphorylating histones (which is not true for cdc2). I don't know if this  correct but it does indicate a substrate specificity difference.

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1279](https://sourceforge.net/p/geneontology/annotation-issues/1279)

**Comment by pgaudet** [comment]
I am not sure what's going on here - Human cdc2 seems to phosphorylates CTD of RNA pol2 (PMC118035), but yeast cdc2 does not seem to be an ortholog. Could the annotation have been on the name rather than on the sequence?

**Comment by pgaudet** [comment]
@kaxelsen

**Comment by pgaudet** [comment]
P04551 is now mapped to EC:2.7.11.22, which is assigned to cyclin-dependent protein serine/threonine kinase activity. I think this is OK ?
