### ISSUE TITLE
mapping to IPR027523intracellular distribution of mitochondria

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1259]
Hi

 IPR027523
is mapping to
intracellular distribution of mitochondria

but this is really just a phenotype. We think that this protein is  more likely involved in
cytoplasmic translation.

I confirmed this with SGD who are removing the GO annotation to
"mitochondrion organization"

thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1280](https://sourceforge.net/p/geneontology/annotation-issues/1280)

**Comment by ValWood** [comment]
Hi @srengel  based on this I am removing pombe ISS to translation.
What do you think? It looks really weak (doesn't even appear to have any translation phenotypes according to SGD description?)

**Comment by srengel** [comment]
hi @ValWood which gene are we talking about?

**Comment by ValWood** [comment]
That would help, its clu1

**Comment by srengel** [comment]
i have removed the translation annotation from CLU1.

**Comment by ValWood** [comment]
and pombe SPBC530.06c ISS done
