### ISSUE TITLE
	UniProtKB-KW:KW-0560 not oxidoreductase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1260]
Thsi is part of respiratory complex I in human (a large multi member complex with around 50 subunits which possesses oxidoreductase activity). There is no evidence that this subunit has (or contributes to) the oxidoreductase activity. Could this mapping ber removed from pomb (and other organisms).

I can find lots more background about this in older SF tickets if required.

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1281](https://sourceforge.net/p/geneontology/annotation-issues/1281)

**Comment by sylvainpoux** [comment]
Swiss-Prot annotation was corrected (the KW removed)
