### ISSUE TITLE
mappings for mitotchondrial chaperone HAMAP:MF_03120

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1261]
HAMAP:MF_03120
mappings to
GO:0034599  cellular response to oxidative stress
GO:0070407  oxidation-dependent protein catabolic process
and
GO:0090296  regulation of mitochondrial DNA replication

seem quite indirect?

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1282](https://sourceforge.net/p/geneontology/annotation-issues/1282)

**Comment by pedruzzi** [comment]
GO:0034599 cellular response to oxidative stress
GO:0070407 oxidation-dependent protein catabolic process
are sourced from the human Lon entry, based on PubMed:12198491 "Lon protease preferentially degrades oxidized mitochondrial aconitase..." 
Lon is the protease and preferentially degrades oxidized substrates, so I to me it can't be a more direct assignment to this term. The only question is how hard we are on the "-dependent" GO term. LON does degrade native aconitase, but has a much higher preference for oxidized aconitase.
This process has been confirmed and corroborated in yeast on multiple oxidized substrates in PubMed:20150421 "Identification of Novel Oxidized Protein Substrates and Physiological Partners of the Mitochondrial ATP-dependent Lon-like Protease Pim1", so I deemed it valid to propagate these terms with a rule.

**Comment by pedruzzi** [comment]
GO:0090296 regulation of mitochondrial DNA replication
is also based on human (PubMed:9485316, PubMed:17420247) and yeast (PubMed:8276800, PubMed:28377575), though the mechanism here is indeed not clear yet and it might be indirect. Still, LON does bind mtDNA and is suggested to regulate mitochondrial DNA replication and/or gene expression using site-specific, single-stranded DNA binding to target the degradation of regulatory proteins binding to adjacent sites in mitochondrial promoters.
This is very vague and I'm ok there's not enough direct proof for the term less for its propagation to orthologs.
I'll remove GO:0090296 from the rule, but keep the 2 others (above), unless further objection.
Thanks
-ivo
