### ISSUE TITLE
Q9KRW5, P32177 and Q9KRW5 should not be annotated to GO:0008863 or GO:0009326

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1275]
FdhD is not part of any formate dehydrogenase complex (PMID 2170340) and does not have formate dehydrogenase activity.  It plays a role in activating formate dehydrogenases by acting as a sulfur carrier (PMID 22194618).

Thanks,
Ingrid

Reported by: imk07

Original Ticket: [geneontology/annotation-issues/1298](https://sourceforge.net/p/geneontology/annotation-issues/1298)

**Comment by pgaudet** [comment]
@ggeorghiou 

Can you please review these? 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi Pascale,
I had a look at those entries and there are no UniProt GOA annotations for these entries to the terms above. What Amaia meant was that these entities have that function mentioned in their profile in UniProt (for example https://www.uniprot.org/uniprot/P32177).
This is not a GOA revision task but rather a user request for the UniProt helpdesk.
Thanks,
Penelope

**Comment by pgaudet** [comment]
@pgarmiri yAre you saying that we should move this to http://www.uniprot.org/contact? 

Or is this a known issue and we can close the ticket here?

**Comment by pgarmiri** [comment]
@pgaudet ,  I don't think the issue is a known, so I would suggest moving the ticket to the link above. It might take some time until it will disappear from the pages, but it will eventually.

**Comment by pgarmiri** [comment]
@pgaudet ,Actually the request should go here http://www.uniprot.org/update

**Comment by pgaudet** [comment]
ok thanks
