### ISSUE TITLE
SPKW mapping gluconeogenesis UniProtKB-KW:KW-0312

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1277]
I noticed that pombe sdh7  Q9P7Y2

mitochondrial respiratory chain complex II assembly ACN9 family protein Sdh7 

is assigned to gluconeogenesis, that doesn't look right ?

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1300](https://sourceforge.net/p/geneontology/annotation-issues/1300)

**Comment by pgaudet** [comment]
KW removed from entry.
