### ISSUE TITLE
HAMAP:MF_03012 mapping to "regulation of translational initiation"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1280]
A lot of the eukaryotic transcription factors which have this mapping are involved directly in translation, rather than in the regulation of translation. Could this be made less specific?

If the  mappings are specific for eif3 or the 46 or 48 preiniitation complex, they could also be made more specifically to "cytoplasmic translation initiation"

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1303](https://sourceforge.net/p/geneontology/annotation-issues/1303)

**Comment by pedruzzi** [comment]
In fact updated the mappings for all rules concerning translation initiation factors, removing the 'regulation of translational initiation' term and updating to the more specific cytoplasmic process terms.
