### ISSUE TITLE
HFE annotations incorrect

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1281]
Dear Sir/Madam,

Many of the annotations for human HFE (Q30201) are not correct. Experts are agreed that HFE is not involved in antigen binding and I have had discussions with Dr Ann Walker about this (ann.walker@ucl.ac.uk). However, there are many electronic pipelines that have incorrectly created annotations to hfe about antigen binding/immune response, which need to be deleted.

Thanks, 

Klaus

Reported by: klausotto

Original Ticket: [geneontology/annotation-issues/1304](https://sourceforge.net/p/geneontology/annotation-issues/1304)

**Comment by pgaudet** [comment]
@RLovering 
I suppose this can be closed ? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@RLovering - can this ticket be closed now?

Thx.

**Comment by RLovering** [comment]
yes please close

**Comment by vanaukenk** [comment]
Thanks @RLovering
