### ISSUE TITLE
Review annotations to mRNA cleavage

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1293]
mRNA cleavage (GO:0006379) was, until recently, under mRNA processing. But this is incorrect, as mRNA processing only covers processes leading to production of mature mRNA, whereas only some mRNA cleavage processes do.

Reviewing direct annotations to this term (see below) shows they are a mixed bag - some processing some not.  So, I've generalised the meaning and classification of mRNA cleavage.

The new structure is.

mRNA cleavage (GO:0006379)
.    % mRNA cleavage involved in gene silencing
.    % mRNA cleavage involved in mRNA processing
.    .    % pre-mRNA cleavage required for polyadenylation

Ref for cleavage prior to polyadenylation: http://www.ncbi.nlm.nih.gov/books/NBK21563/#_A2878_

A review of annotations shows As the definition is now more general, current annotations are correct, but could be made more specific.
### mRNA cleavage involved in mRNA processing:

UniProtKB PMID:10523662  =  pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:10619842  =  pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:10899131  =  pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:11344258  =  pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:11713271  =  pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:12504017  =  pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:18971324 = pre-mRNA cleavage required for polyadenylation + involvement in snoRNA processing
UniProtKB PMID:7590244 = pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:9342333 = pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:21102410 = pre-mRNA cleavage required for polyadenylation
UniProtKB PMID:12704082  =  pre-mRNA cleavage required for polyadenylation

UniProtKB PMID:21317875 = ribonuclease activity in regulated splicing (splices Xbp1 mRNA generating an active Xbp1s transcriptional activator) - fits under processing

UniProtKB PMID:9712888 =  Earlier cleavage event - during transcription (involved in read through past block to elongation).  Fits under processing?
PMID:12692127  =  Earlier cleavage event - during transcription ((involved in read through past block to elongation). Fits under processing?
### Leading to mRNA degredation / gene silencing / negative reg of translation

UniProtKB PMID:14729943  = novel method of mRNA degradation: RNase MRP specifically cleaves the CLB2 mRNA in its 5'-UTR to allow rapid 5' to 3' degradation by the Xrn1 nuclease
UniProtKB PMID:15009896 = inhibition of translation in bacteria via mRNA cleavage
UniProtKB PMID:17158880 = 3' end cleavage -> degradation (controlling mRNA in cell cycle
UniProtKB PMID:18007599 = siRNA targeted mRNA cleavage
UniProtKB PMID:18454937 = siRNA pathway
### Annotation error?

UniProtKB PMID:20424607 = Refers to miRNA processing, possibly 3'-5'-exoribonuclease activity involved in mature miRNA 3'-end processing

Reported by: dosumis

Original Ticket: [geneontology/annotation-issues/1317](https://sourceforge.net/p/geneontology/annotation-issues/1317)

**Comment by vanaukenk** [comment]
It looks like there are still a few outstanding direct annotations to mRNA cleavage (GO:0006379) that could be reviewed and possibly annotated to a more specific term:

@hdrabkin (these are miRNAs - does Dmitry have a github handle?)
@rachhuntley (this looks to be an annotation from Rebecca)
@sylvainpoux (an annotation from Kati)
@hattrill 
@srengel @suzialeksander 

https://docs.google.com/spreadsheets/d/1C2w0kEl_yzWJ0-I50Tc9p0oyOprpHo28_mJ6PGpjGEc/edit#gid=0

Thx.

**Comment by srengel** [comment]
there was only a single SGD annotation left, i moved it down to 98787.  the other 9 yeast annotations are IEA's from InterPro.

removing myself and Suzi A from assignees.

**Comment by hattrill** [comment]
Done.

**Comment by RLovering** [comment]
UCL - done, can't edit the spreadsheet if you need to record action please add: Changed to more granular child term.

**Comment by bmeldal** [comment]
3 complexes fixed to more granular children.

**Comment by hdrabkin** [comment]
MGI done

**Comment by pgaudet** [comment]
@vanaukenk 
Are you handling this ticket ? There is a single annotation left to Q7A225 (HigB), an endoribonuclease, which seems OK. 

Can you close this tickjt and mark the Google spreadsheet DONE  (if it is). 

Thanks ! 

Pascale

**Comment by vanaukenk** [comment]
@pgaudet - done.  Thx.
