### ISSUE TITLE
non specific annotations to mitochondrial with KW-0496 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1296]
There are a number of fission yeast annotations using KW:KW-0496 which are studied, but not  detected in mitochondria, or I can't find any evidence from budding yeast ortholog.

These include:

SPBC27B12.02 GO:0005739 IEA UniProtKB-KW:KW-0496 centromere protein Mis19/Eic1
SPCC970.07c GO:0005739 IEA UniProtKB-KW:KW-0496 Rik1-associated factor Raf2
SPCC338.16 GO:0005739 IEA UniProtKB-KW:KW-0496 F-box protein Pof3
SPAPB1A10.16 GO:0005739 IEA UniProtKB-KW:KW-0496 conserved fungal protein
SPCC4G3.13c GO:0005739 IEA UniProtKB-KW:KW-0496 CUE domain protein Cue1/4 family involved in ER associated protein catabolism (predicted)
SPCC548.06c GO:0005739 IEA UniProtKB-KW:KW-0496 hexose transmembrane transporter Ght8 (predicted)

I have blocked this mapping at PomBAse as everything we know /infer to be mitochondrial with good evidence is manually annotated.

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1321](https://sourceforge.net/p/geneontology/annotation-issues/1321)

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-annotation/issues/1503
