### ISSUE TITLE
indirect for histidine biosynthesis? KW:KW-0368

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1297]
These annotations look indirect for histidine biosynthesis for these gene products

PomBase SPBC2G2.08  ade9        GO:0000105  GO_REF:0000037  IEA UniProtKB-KW:KW-0368    P   C-1-tetrahydrofolatesynthase/methylenetetrahydrof olatedehydrogenase/methylenetetrahydrofolatecyclohydrolase/ formyltetrahydrofolatesynthetase (predicted)      protein taxon:4896  20150328    UniProt  

PomBase SPBC839.16  thf1        GO:0000105  GO_REF:0000037  IEA UniProtKB-KW:KW-0368    P   C1-5,6,7,8-tetrahydrofolate (THF) synthase, trifunctional enzyme Thf1       protein taxon:4896  20150328    UniProt 

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/1322](https://sourceforge.net/p/geneontology/annotation-issues/1322)

**Comment by Antonialock** [comment]
will be fixed for cerevisiae and pombase, in addition to histidine biosynthesis I removed methionine bio, purine bios.
I kept the KW to One-carbon metabolism & added folate biosynthesis

let me know if that doesn't look right.

**Comment by Antonialock** [comment]
actually not adding folate biosynthesis, it's metabolism I suppose.

**Comment by Antonialock** [comment]
Also should it be removed for all these enzymes?
https://www.uniprot.org/uniprotkb?query=%28ec%3A1.5.1.5%29+AND+%28keyword%3AKW-0368%29&facets=reviewed%3Atrue
