### ISSUE TITLE
Three Annotation Issues for GO Camp from WormBase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#13]
Here are three annotation issues that I've encountered
while doing GO curation for the C. elegans UNC-31 protein.

Some Background:
When compared to yeast and mammals, the C. elegans
field still does relatively little biochemistry-type
experiments.  The upshot of this is that many of our
molecular function, and to a lesser extent cellular
component, annotations are ISS annotations drawn from
direct assays performed in other species.  The
following annotation issues come from reading a paper
(PMID: 11927595)  about what I believe is the rat
UNC-31 ortholog, CAPS, in which the authors describe
results of direct assays regarding CAPS function and
subcellular localization.  The rat protein has not yet
been annotated to any GO terms.

#1-CAPS is described as a cytosolic protein that also
associates with the plasma membrane, dense core
(secretory granule) membranes, and Golgi membranes.  It
does not appear to be an integral component of these
membranes, but likely transiently associates with
distinct phospholipid components.  What are the
appropriate annotations for this type of localization
which although transient, is critical to CAPS function?
Does annotating to plasma membrane, Golgi membrane,
and secretory granule membrane imply integral membrane
association?  Would this be an example of when to use
the associates_with qualifier?  Is an associates_with
qualifier going to be added to the accepted list of
qualifiers?  

#2-CAPS is shown to exhibit nonspecific acidic
phospholipid binding and stereoselective PtdIns(4,5)P2
binding.  In order to capture both functions, would
people assign both MF:phospholipid binding and
MF:phosphoinositide (4,5) bisphosphate binding even
though there would be redundancy in these annotations
since the latter term is a child of the former?  

#3-When using the ISS evidence code, what is the
appropriate way to reference the annotation?  Should I
list the original paper (in this case the rat paper) as
well as the C. elegans paper that describes the
sequence similarity?  Just the rat paper?  Just the C.
elegans paper?  

Thanks,
Kimberly    

Reported by: vanaukenk

Original Ticket: "geneontology/annotation-issues/13":https://sourceforge.net/p/geneontology/annotation-issues/13

**Comment by linuxlovell** [comment]
thanks www.movied.org
