### ISSUE TITLE
Annotating protein complexes

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#1303]
Hi,

We are now annotating to protein complexes using the IntAct complex portal identifiers.

A few issue have come up that are being discussed in a working group. Please record any new issues here.

Minutes from the first call are here:
http://wiki.geneontology.org/index.php/Protein_Complex_Conference_Call_June19,_2015

We are having another call next week and will post a link to the minutes to the GO list and here.

Please feel free to add discussion points to an annotation call agenda whenever it suits.

Birgit

Reported by: bmeldal

Original Ticket: [geneontology/annotation-issues/1328](https://sourceforge.net/p/geneontology/annotation-issues/1328)

**Comment by pgaudet** [comment]
@bmeldal 
Is this ticket superseded by the new WG ? If so please close this one. 

Thanks, Pascale
