### ISSUE TITLE
IPR004545 proliferation mapping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1307]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008283

Note the annotation comment:

This term was moved out from being a child of 'cellular process' because it is a cell population-level process, and cellular processes are restricted to those processes that involve individual cells. Also note that this term is intended to be used for the proliferation of cells within a multicellular organism, not for the expansion of a population of single-celled organisms.

(this term is  not a process in GO to represent viability in a single celled organism)

I'm also not sure that cell cycle or transcription are appropriate mappings at present. There is no evidence for a cell cycle  role as yet in fission yeast and there doesn't seem to be any good functional data in other organisms...

**Comment by asangrador** [comment]
I have removed 'cell proliferation' as it can not be applied, as you've  point out, to the fungal proteins in this entry. There is not evidence for cell cycle or transcription activity in pombe, the annotation is based in higher eukaryotes, where it is involved in proliferation [PMID:24275324], cell cycle transition [PMID15689342] and transcription [PMID:23242156]. We will consider removing the annotation.

**Comment by ValWood** [comment]
Yeah I would remove them. They seem to be more 'phenotypes' observations then real characterized processes. They all seem a bit weak...Having no GO annotation might be better....
