### ISSUE TITLE
PTHR12377 - Query PAINT annotation UniProtKB:Q9UTL0|PTN000272201|SPAC144.16

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1312]
This one is strange
PomBase	SPAC144.16	cia2		GO:0007059	PAINT_REF:12377	IBA	PANTHER:PTN000272126	P	iron-sulfur cluster assembly protein Cia2 (predicted)	UniProtKB:Q9UTL0|PTN000272201|SPAC144.16	protein	taxon:284812	20140919	GO_Central		

it seems that some of the evidence is from SPAC144.16 itself, but this is unstudied in pombe. As far as we know from SGD this is involved in ron-sulfur cluster assembly  (and PAINT also generates these annotations). Can you point me to the source of the chromosome segregation primary annotation ?

**Comment by pgaudet** [comment]
Hi Val, The evidence is in fact from SGD - CIA2 gene. Do you want to dispute that ? 

The paper seemed convincing enough for the PAINT curator to propagate it (Paper: PMID:22678362) 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi Val, 

The chromosome segregation data is based on Drosophila galla-1 (PMID25065591) and human FAM96B (PMID:20797633). Probably due to the evolutionary span of these annotations, the curator decided to propagate the annotation. 

If that seems incorrect I can remove the annotation. 


Thanks, Pascale

**Comment by ValWood** [comment]
This would quite possible have a chromosome segregation phenotype, but  so do 100's of  other proteins upstream of chromosome segregation (DNA replication, splicing etc).

- The effect on  "chromosome segregation" is proposed to be inserting iron sulfur cluster into 
ERCC2 of the MMXD complex
- Pombe does not appear to have this complex. Pombe has some complex members including ERCC2 (they are also part of TFIIH).
- We don't annotate TFIIH to chromosome segregation, because its known roles (recombination,  repair transcription) are upstream.

In human, this complex is "required" for normal chromosome segregation
http://www.uniprot.org/citations/20797633
(this is maybe likely to be "affects" rather than "involved in", although it does seem to localize to the SPB in mitosis)

 @Antonialock is working on iron sulphur cluster biogenesis- do you have any further info?
I think pombe cia2 is also part of a silencing complex which operates on centromeric heterochromatin?

I'm a bit precious about  mitotic chromosome segregation
http://tinyurl.com/zzz98um
So I'm inclined to say remove, but if you want to keep I can filter until we know more.

**Comment by pgaudet** [comment]
Hi Val, 

We removed chromosomal segregation and restricted the propagation of the complex to animals. 

Thanks for the feedback, 

Pascale & Marc

**Comment by ValWood** [comment]
OK I wanted to follow up on this one.
A search on "MMXD" the complex only brings up  2 papers, 
https://www.ncbi.nlm.nih.gov/pubmed/20797633
Mol Cell. 2010 Aug 27;39(4):632-40. doi: 10.1016/j.molcel.2010.07.029.
MMXD, a TFIIH-independent XPD-MMS19 protein complex involved in chromosome segregation.

and the later
https://www.ncbi.nlm.nih.gov/pubmed/23150669
J Biol Chem. 2012 Dec 21;287(52):43351-8. doi: 10.1074/jbc.M112.431270. Epub 2012 Nov 13.
The mammalian proteins MMS19, MIP18, and ANT2 are involved in cytoplasmic iron-sulfur cluster protein assembly.


I don't think the evidence for chromosome segregation is strong 
but it has a well characterised role in cytoplasmic iron-sulfur cluster assembly  
https://www.ncbi.nlm.nih.gov/pubmed/?term=MMS19
https://www.ncbi.nlm.nih.gov/pubmed/?term=MIP18

I

**Comment by pgaudet** [comment]
Hi Val, 

I had closed this issue; does something else need to be done ? Are you disputing the primary annotations ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Close, I'll follow up with Antonia. If it is a problem it should drop pout of here analysis.
It does look a bit indirect for chromsome segregation to me, particularly considering the later paper.
