### ISSUE TITLE
PTHR24356 (1300 members) PANTHER:PTN001220075)	problem annotation for fission yeast 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1313]
I just spotted this

mug27           positive regulation of septation initiation signaling       GO Central  Schizosaccharomyces pombe   IBA PANTHER:PTN001220075            PAINT_REF:0024356   20150429

```
mug27           regulation of meiotic nuclear division      GO Central  Schizosaccharomyces pombe   IBA PANTHER:PTN000683505            PAINT_REF:0024356   20150429
```

This kinase hasn't been studied in detail in pombe but it seems to be involved in prospore membrane assembly rather than "nuclear division".

I can't see an ortholog which could generate the  "positive regulation of septation initiation signaling"
annotation, and  it seems  very unlikely (impossible) as "septation iniitation signalling" is a mitotic signalling pathway and this kinase is meiosis specific.

**Comment by pgaudet** [comment]
PTHR24356 - 1400 members.  Fix postponed.

**Comment by pgaudet** [comment]
Hi Val, 

We removed the annotation to positive regulation of septation initiation, but it was citing a pombe gene. I am not sure why the primary annotation is gone. 

I dont see an annotation to 'regulation of meiotic nuclear division' in the GAF. Is this a PAINT annotation ? 

Thanks, Pascale

**Comment by ValWood** [comment]
no, there is no evidence that it is regulating meiotic nuclear division, just that it functions during the meiotic cell cycle.

More recent publication implicates it in regulating autophagy, which is a "sporulation-related" process in pombe, and we have annotations for that in our pending submission file.


I suspect the septation iniitiation signalling annotation could have originated from sid2 the mitotic specific  pombe paralog which *is* part of SIN. 

SIN is a fairly well characterised pathway:
![sin](https://cloud.githubusercontent.com/assets/7359272/19525961/ad8e8348-961a-11e6-90b5-8c028b1dcc02.jpg)

so I hope we would have it covered. Any additional annotations would be suspect...

I hope this helps....

**Comment by ValWood** [comment]
remember https://github.com/geneontology/go-ontology/issues/11709 ;)

**Comment by ValWood** [comment]
This looks like PAINT:
 
  regulation of meiotic nuclear division      GO Central  Schizosaccharomyces pombe   IBA PANTHER:PTN000683505            PAINT_REF:0024356   20150429

**Comment by ValWood** [comment]
This one turns out to be a bit more complicated. Apparently the same pathway operates in meiosis, and is still called "septation initiation network" although in this instance it is regulating sporulation, not septation.

This is a problem with the way we try to build signalling pathway names into GO generally....
This  particular term is built into GO as a pathway specifically regulating  mitotic septation and cytokinesis.

This is a good example for some of the problems with signalling pathway terms generally.

But safest for now not to propagate. 
It might be better to remove  the "SIN signalling" terms (which are a bit pombe specific) and have 
signalling involved in activation of septation
signalling involved in activation of cytokinesis
etc.

**Comment by selewis** [comment]
Hi @ValWood 

Do you know whether the ontology issues for this have been added to the ontology tracker? @cmungall @ukemi it would be useful to have the two of you look at this.

It's a classic of one pathway (SIN) being used for different biological objectives (both meiosis and sporulation).

On the PAINT side, perhaps there might be a way to detect this pattern and at least make the curator aware of this.

**Comment by ukemi** [comment]
Yes. As Val point out, this is an issue in defining where signaling pathways begin and end. It needs some focused ontology development work. Recently we teased out these things in apoptosis and autophagy. In fact I just made some edits yesterday in the autophagy branch where we had several processes listed a types of autophagy, but in fact they represented processes where there were upstream processes added on to autophagy and regulated it. The fasted we get to LEGO, the better these things will be sorted out.

**Comment by ValWood** [comment]
I'm in favour of a massive simplification.

Something like:
 signalling involved_in "+/-ve regulation of x process" (can be post composed with extensions, LEGO style)
for everything.

Trying to use established names of for pathways isn't scalable. They are so nebulous. Sometimes they refer to entire networks, not pathways at all. 

Most pathways encompass many modules (which are covered by the function term anyways)
Map kinase activity -> MAP kinase cascade
GTPase activity -> GTPase mediated signalling 
etc....

I don't think LEGO will necessarily resolve these issues from an  annotation or ontology perspective, although it will be helpful to think about the problems and what the annotations 
should look like.

**Comment by ValWood** [comment]
see annotations here
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC417.06c

**Comment by ValWood** [comment]
can close, all existing annotations from PAINT are redundant with EXO, but correct
