### ISSUE TITLE
PAINT_REF:10571 IEA     PANTHER:PTN000060284

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1314]
gpt2            GO:0019348      PAINT_REF:10571 IEA     PANTHER:PTN000060284    P       UDP-N-acetylglucosamine--dolichyl-phosphate N-acetylglucosaminephosphotransferase       alg7|gpt        protein taxon:4896      20140919        GO_Central

we have this annotated to 
GO:0006489	dolichyl diphosphate biosynthetic process

which seems more correct. Its not really metabolising dolichol?

val

**Comment by pgaudet** [comment]
Fixed, thanks ! 

Pascale
