### ISSUE TITLE
PTHR23500 (was:PAINT_REF:24063 IBA     PANTHER:PTN000756124) (MFS family glucose transporters)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1315]
PomBase SPAC20G8.03     itr2            GO:0046323      PAINT_REF:24063 IEA     PANTHER:PTN000756124    P       MFS myo-inositol transmembrane transporter              protein taxon:4896      20150313        GO_Central

I don't think we probably want to transfer specificities of some of these transporters. In pombe itr2 isn't transporting "glucose".
This is a member of a "sugar" transporter family and but substrates of transporters can evolve pretty rapidly ...especially in the larger families.

**Comment by ValWood** [comment]
similarly 

PomBase	SPAC4F8.15	itr1		GO:0046323	PAINT_REF:24063	IEA	PANTHER:PTN000756124	P	myo-inositol transmembrane transporter Itr1	SPAC7D4.01	protein	taxon:4896	20150313	GO_Central	

we have an IMP to carbohydrate but didn't feel we could be more specific
v

**Comment by ValWood** [comment]
We have a whole family of these, and the specificities are not always known. I think 'glucose' has been added to all of them, but it is known they they have different specificities. Also GO:0005351 sugar:proton symporter activity and I can't find any evidence for this mechanism (they are MSF family?). Can you point me to the original annotation for this for a family member? 

For process I don't think that you can be any more specific than "carbohydrate transport" from a related species to pombe .... (this inlcudes ght3,4,6,7,8)

**Comment by pgaudet** [comment]
Pombe itr2 is part of PTHR23500 in Panther11.

**Comment by ValWood** [comment]
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC20G8.03
has incorrect

glucose transmembrane transporter activity
hexose transmembrane transport

**Comment by pgaudet** [comment]
Fixed.
