### ISSUE TITLE
PAINT_REF:14094	IEA	PANTHER:PTN000363482 (signal recognition particle)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1316]
srp72 is picking up an annotation to 
GO:0005047	signal recognition particle binding

But IT IS part of the SRP ?

PomBase	SPCC320.10	srp72		GO:0005047	PAINT_REF:14094	IEA	PANTHER:PTN000363482	F	signal recognition particle subunit Srp72 (predicted)		protein	taxon:4896	20140929	GO_Central

**Comment by pgaudet** [comment]
Annotation to GO:0005047 signal recognition particle binding was removed. Thanks!
