### ISSUE TITLE
PTHR10438 - PAINT annotation, thioredoxin and "protein folding"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1321]
All thioredoxins in pombe are getting annotations to "protein folding".I can't see any evidence for this for trx1 or trx2...they are involved in protein repair via  peptide-methionine (S)-S-oxide reductase activity

**Comment by ValWood** [comment]
@pgaudet  @gocentral  Do we need a PAINT label

**Comment by pgaudet** [comment]
Hi Val, 

We reannotated this family and removed the protein folding annotation. 

Thanks, Pascale and Marc

**Comment by ValWood** [comment]
Did you agree with that one...I didn't think that all thioredoxins were involved in protein folding, but some are...it  didn't seem correct for these?

**Comment by ValWood** [comment]
You don't need to answer this. The other ticket answers
https://github.com/geneontology/go-annotation/issues/1400
