### ISSUE TITLE
IPR001434 mapping

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-annotation#1323]
From Ingrid @keseler

The issue I have run across is a GO mapping for Domain of unknown function DUF11 (IPR001434) to GO:0005727 extrachromosomal circular DNA, which I really don't understand at all. Is it really correct?

Thanks,
Ingrid

**Comment by paolaroncaglia** [comment]
Val @ValWood , 
I don't have permission to add (or even edit) labels on this tracker. If you do, could you please add 'InterPro' to this ticket?

Thanks,
Paola

**Comment by asangrador** [comment]
Hi,

This is a very old entry. I don't understand how it came to have this annotation. I have removed it!

**Comment by keseler** [comment]
Thanks, everyone!
