### ISSUE TITLE
gamma glutamyl transferase and glutathione hydrolase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1324]
Does anybody know  anything about  gamma-glutamyltranspeptidases ?

In pombe we have 2
ggt1 http://www.pombase.org/spombe/result/SPAC664.09
and 
ggt2 http://www.pombase.org/spombe/result/SPAC56E4.06c

we have annotated to 
gamma-glutamyltransferase activity
and so has SGD
http://www.yeastgenome.org/locus/YLR299W/overview#go

but EC mapping is to GO:0036374 glutathione hydrolase activity

**Comment by ValWood** [comment]
I want to ping Peter D' for this one but I can't see his github profile? Anyone know?

**Comment by deustp01** [comment]
I don't, but but here is a reference from Alton Meister (who I think was the preeminent authority on this) and a recent one from another person who looks like an authority:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC283344/
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4388159/
From a description of the cycle that I just skimmed, it looks like the cycle works to preserve the energy in the bond connecting the glutamate residue to the rest of glutathione by means for a transpeptidation reaction, while hydrolysis of the bond (GO:0036374) would lose that energy.

**Comment by ValWood** [comment]
Thanks Peter, I took the easiest option and contacted Marie Hannigan for advice/confirmation

**Comment by ValWood** [comment]
A really useful summary from Marie:

Thanks for reaching out to me. The link to my review that was included in the earlier post will provide a fairly compressive overview of the enzyme -  http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4388159/

The answer answer to your questions: Gamma-glutamyl transferase and gamma-glutamyl transpeptidase  are alternative names for the same protein. There is actually a family of GGT enzymes and in vertebrates GGT1 is the enzyme that is referred to when people talk about GGT. There is also a GGT5 enzyme that is expressed and active, in humans there is a GGT2 gene that is expressed but inactive. (we have publications on both these enzymes). With regard to the activity of GGT it is a cell surface enzyme that hydrolyzes the gamma-glutamyl bond of extracellular gamma-glutamyl compounds. Glutathione is the most abundant substrate physiologically. In a test tube one can set up conditions in which the enzyme will transfer the gamma-glutamyl portion of the substrate to an acceptor molecule, but this requires non-physiologic conditions, including millmolar concentrations of an acceptor such as glygly. This reaction is used in assays to detect the presence of the enzyme, but is not a physiological function of GGT.    

==
@pgaudet  this is a really useful summary and references  for PAINTING these proteins

I'm going to open a ticket on the ontology tracker to include this ref and add comments to the 2 terms about the physiological direction.

**Comment by ValWood** [comment]
suggested a comment on the  gamma-glutamyltransferase activity term
https://github.com/geneontology/go-ontology/issues/12114

(In yeast this part of the pathway appears to occur in the vacuole)

**Comment by ValWood** [comment]
I wonder if this applies in yeast?
https://github.com/pombase/curation/issues/728

**Comment by srengel** [comment]
thanks Val.  i updated the annotation in SGD (from PMID:11672438) from GO:0003840 gamma-glutamyltransferase activity to GO:0036374 glutathione hydrolase activity.  the experiment was done in vacuoles.

**Comment by vanaukenk** [comment]
@ValWood - is there anything left to do here or can we close this ticket?  Thx.

**Comment by pgaudet** [comment]
gamma-glutamyltransferase activity now obsoleted 
with CONSIDER: 'GO:003637 glutathione hydrolase activity' 
https://github.com/geneontology/go-ontology/issues/13571
