### ISSUE TITLE
Annotating yeast autophagy regulators in PMID:25660547 ?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-annotation#1326]
I have annotated human proteins in experiments described in  "Rph1/KDM4 Mediates Nutrient-Limitation Signaling that Leads to the Transcriptional Induction of Autophagy" - PMID:25660547 but there are a large number of experiments done with yeast (S. cerevisiae )that might be better handled by others - anyone interested?

**Comment by suzialeksander** [comment]
There are 20 annotations to two proteins from this paper in SGD, done 11/2015.  (Although I'd love to say it was me I can't).  I'm considering this to be done, unless there's something specific that might have been missed/is still needed.

Thanks
Suzi
