### ISSUE TITLE
Query about IGI evidence code guidelines

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#1327]
Hi 

I do not agree with the changes that have recently been made to the IGI evidence code guidelines, and I do not think that these reflect the decision made about these guidelines in annotation calls.

One of the established guideline is:
Examples where the IGI evidence code should be used:
mutation in gene B provides information about gene A being annotated. For this type of experiment, use the IGI code.

The NEW guideline is:
Examples where the IGI evidence code should not be used:
In situations where a mutation in gene A provides information about the function, process, or component of gene B do not use IGI. Use IMP evidence code and use column-16 or the Annotation Extension column to provide additional data. For example, if a mutation in gene A causes a mislocalization of gene B, gene A is annotated to protein localization using IMP and the gene B identifier is added to the Annotation Extension column with the appropriate relationship.
1. If I change the gene A and B assignments in this new guideline isn't this the same as the example of when IGI should be used, but now is a do not use IGI?
   In situations where a mutation in gene B provides information about the function, process, or component of gene A do not use IGI. 
2. We have to make sure that there is consistent use of Column 16 and the WITH field. Column 16 is not the place to add information about which proteins interact with the annotated protein to create a functional protein complex (i.e. subunit information) because this is effectively a 'reverse' annotation. The WITH field should include 'subunit' information.

Note that I do agree with the example provided with this new guideline. This is an appropriate use of C16, but I would suggest that it would be very helpful to include the appropriate relationship: transports_or_maintains_localization_of for this example.

I would suggest the NEW guideline is revised as follows:
Examples where the IGI evidence code should not be used:
In situations where a mutation in gene A transports gene B to a new location in the cell do not use IGI. Use IMP evidence code and use column-16/Annotation Extension to provide additional data. For example, if a mutation in gene A causes a mislocalization of gene B, gene A is annotated to protein localization using IMP with the Annotation Extension transports_or_maintains_localization_of gene B.

In addition, I would suggest that any modifications to the GO evidence code documentation are actually presented in an annotation call so that people can agree with the wording before they are added. This might just be a boring formality but I think it is one to consider adopting.

Ruth

**Comment by monicacecilia** [comment]
Review is undergoing - see the Annotation Call notes for details http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-02-09
