### ISSUE TITLE
PTN000349745 annotation to GO:0005794, Golgi apparatus

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#1333]
...may be slightly too eukaryotic for E.coli.  I get this annotation for the E. coli RfaJ and RfaI proteins.

http://www.ebi.ac.uk/QuickGO/GProtein?ac=P27129
http://www.ebi.ac.uk/QuickGO/GProtein?ac=P27128

Cheers,
Ingrid

**Comment by pgaudet** [comment]
Fixed.
