### ISSUE TITLE
EC:2.7.1.137 mapping

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1334]
pombe tor1 and tor2 have an IEA mapping to 1-phosphatidylinositol-3-kinase activity
EC:2.7.1.137
but I think these proteins are ser/thr kinases, they are part of the PIKK family of kinases (kinases that look like PI3 kinases but are not, as far as I understand it). This should probably be removed?

cheers

**Comment by mcourtot** [comment]
Forwarded to Michele for investigation.

**Comment by mcourtot** [comment]
Ivo Pedruzzi (SIB) says: "Antonia is right on the issue and I have seen it can easily be solved by updating/correcting the UniProt annotation of these proteins."
He will do the fix.

**Comment by ipedruzz** [comment]
I have updated both UniProtKB entries for tor1 and and tor2 from S.pombe, most importantly replacing the erroneous EC:2.7.1.137 by EC:2.7.11.1
The updated entries will be public in UniProt release 2016_04. I'm unsure however of how much time it takes for the correction of the GO term assignment, as these are all automatic procedures, but eventually the IEA mapping to GO:0016303; F:1-phosphatidylinositol-3-kinase activity will be replaced by GO:0004674; F:protein serine/threonine kinase activity
Best
-ivo

**Comment by Antonialock** [comment]
Super, thank you Ivo!

**Comment by mcourtot** [comment]
Was trying to assign ipedruzz but didn't work as Ivo is not member of the project yet. Ivo: let me know if you would like to be added to this tracker.
