### ISSUE TITLE
obsoletetion or merge of APC-complex activity terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1335]
Hi Tanya,

I thought we were going to get rid of these in favour of  using the  corresponding
x ubiquitin ligase  MF terms ......

Val

GO:0051488 activation of anaphase-promoting complex activity
GO:0051487 activation of anaphase-promoting complex activity involved in meiotic cell cycle
GO:0090302	APC-Cdc20 complex activity
GO:0007092	activation of APC-Cdc20 complex activity
GO:0060564	negative regulation of APC-Cdc20 complex activity
GO:0061636	mitotic anaphase-promoting complex activator activity	
GO:0061637	mitotic anaphase-promoting complex inhibitor activity
GO:0090622	APC-fizzy related complex activity	
GO:0090623	activation of APC-fizzy related complex activity	
GO:1903834	regulation of APC-fizzy related complex activity	
GO:1903835	positive regulation of APC-fizzy related complex activity
GO:1904190	negative regulation of APC-fizzy related complex activity

GO:0060565 is already obsolete
obsolete inhibition of APC-Cdc20 complex activity

**Comment by tberardini** [comment]
Still on my plate, see open Ontology GH issue. Unfortunately, no bandwidth to do it yet.

https://github.com/geneontology/go-ontology/issues/11757

**Comment by ValWood** [comment]
ok, I couldn't remember where we were up to.
val
