### ISSUE TITLE
Importing annotations from ExoCarta and Vesiclepedia in GO

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-annotation#1337]
Stemming from the soon-to-be-submitted paper (for publication in the JBMS ontology issue)
"Extending Gene Ontology in the Context of ExRNA Communication".

1) The short-term plan is as follows - 
"The Protein Function Content team at EMBL-EBI are currently working on importing annotations from ExoCarta and Vesiclepedia into the GOC."
Aleksandra Shypitsyna started looking at a small subset of ExoCarta annotations. We're hoping to import them by the end of January 2016, but this plan will have to be reviewed after the holidays based on available resources.

2) Then a longer-term plan is to include all of the annotations from ExoCarta and Vesiclepedia in GO. Resources for this will also need to be discussed and defined.

**Comment by paolaroncaglia** [comment]
Note - while revising the manuscript, Paul Thomas commented on the following section:
"In collaboration with the GOC editorial team, we have mapped the ExoCarta and Vesiclepedia gene products (coding and non-coding RNAs and proteins) onto their corresponding RNAcentral (http://www.rnacentral.org) and UniProt (http://www.uniprot.org/) identifiers using the newly extended GO Cellular Component terms." 
Paul notes:
"Please add a sentence about the evidence code that you used and what it means.  Did you use ECO?"

**Comment by paolaroncaglia** [comment]
Update: paper was accepted. Working with Shiva's team to incorporate small subset of ExoCarta + Vesiclepedia annotations. This involves Aleks too as she drafted guidelines for the external curators - thanks @zebrafishembryo

**Comment by paolaroncaglia** [comment]
Update: this is now a priority for GOA; the point curator is likely going to be George. George, Alice, Michele and Claire have a copy of the latest version of external annotations from ExoCarta/Vesiclepedia (as well as a copy of the curation guidelines that Alice developed). I put them in touch with Shivakumar Keerthikumar who was leading the external curation effort.

**Comment by pgaudet** [comment]
@ggeorghiou 
Can you please update us on the status of this ticket ? 
Thanks, Pascale

**Comment by ggeorghiou** [comment]
Hi, so with regards to Vesiclepedia/EcoCarta, we are still reviewing some of their annotations. Those which are ok have been incorporated into the GOA database but are not available publically. Since many of their annotations are based on high-throughput annotations, I will be informing them of the changes we made so that they can make sure the ECO code they've used is appropriate.
