### ISSUE TITLE
taxon restraints  for 'programmed cell death' - excluding Dicty?

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-annotation#1338]
Hello,
I was notified by GOA report that we had 4 (older) ISS annotations to GO:0006915 'apoptotic process' which is taxon restricted for Opisthokonta. Dicty doesn't have any caspases, so I decided to use the parent GO:0012501 'programmed cell death' 
Def.: "PCD, caspase-independent apoptosis, regulated cell death, caspase-independent cell death, non-apoptotic programmed cell death, nonapoptotic programmed cell death. A process which begins when a cell receives an internal or external signal and activates a series of biochemical events (signaling pathway). The process ends with the death of the cell."

When I updated the term in Protein2GO however,  it got still flagged as violating a taxon restraint. It cannot be that this parent is taxon restricted for Dicty. Dicty has 'autophagic cell death', which is a child of programmed cell death (PMID: 19133302).

Thanks!
Petra

**Comment by paolaroncaglia** [comment]
Hi Petra,

I confirm that GO:0012501 'programmed cell death' doesn't have any taxon constraint at all. So you shouldn't get an error. I will look into this. Thanks for reporting!

Paola

**Comment by pfey03** [comment]
Thanks Paola! 
I just checked in P2GO today and still flagged for taxon constraint reasons. Maybe this is then more a question for Tony that the flag doesn't disappear when you update the GO term? The annotations are for
- Q86IX1
- Q55FS2
- Q54EY4
- Q54JG7

Thanks again, Petra

**Comment by paolaroncaglia** [comment]
Hi again,

Unfortunately Tony is away this week. In the meantime, @mcourtot , @cmungall would you have any tip on fixing this, please? 

Cheers,
Paola

**Comment by paolaroncaglia** [comment]
Mentioning @tonysawfordebi anyway, for the records

**Comment by cmungall** [comment]
I don't see any restriction on PCD in the ontology, so perhaps a P2GO 
issue? cc @TonySawford

**Comment by tonysawfordebi** [comment]
I haven't looked into this yet, but I can clarify that the flag doesn't get reset in P2G until the next time the taxon constraint pipeline is run (which happens every weekend). So if an annotation is flagged and you update the GO term, then it will remain flagged until the next constraint validation run.

**Comment by pfey03** [comment]
Alright - thanks Tony, good to know! Just checked and the flags are indeed gone:-)
