### ISSUE TITLE
Tor[X] proteins annotated to wrong function? (GO:0009033 trimethylamine-N-oxide reductase activity vs GO:0050626 trimethylamine-N-oxide reductase (cytochrome c) activity)

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-annotation#1340]
Moved from ontology tracker https://github.com/geneontology/go-ontology/issues/12192

The IntEnz xrefs for proteins annotated to the above terms don't match up between GO and UniProt.

GO:0009033 trimethylamine-N-oxide reductase activity has xref EC 1.6.6.9
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009033

GO:0050626 trimethylamine-N-oxide reductase (cytochrome c) activity has xref EC 1.7.2.3
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0050626

There are 4 proteins manually annotated to GO:0009033 trimethylamine-N-oxide reductase activity. One is a SwissProt entry (http://www.uniprot.org/uniprot/Q9KRF0) and has EC 1.7.2.3 annotation in Uniprot. The other 3 are TrEMBL entries only. All GO annotations are by sequence alignment/similarity.

Similarly, the 2 manually annotated proteins to GO:0050626 trimethylamine-N-oxide reductase (cytochrome c) activity are SwissProt and also annotated to EC 1.7.2.3.

All these proteins are from the same protein family.

This leads me to believe that at least the SwissProt protein annotated to GO:0009033, and possible all 4 manually annotated protein here, should be annotated to GO:0050626. Then the 100s of inferred annotations will follow...

Hope this makes sense,
Birgit

**Comment by mcourtot** [comment]
Forwarded to Michele for investigation.

**Comment by mcourtot** [comment]
Emailed UniProt curator who said:
The TORA_VIBCH (Q9KRF0) entry has a correct Swiss-Prot annotation (correct EC number) but should be annotated to GO:0050626 by similarity to TORA_ECOLI (P33225) and not to GO:0009033 as it is currently annotated with the ISS code.
The characterized entry is TORA_ECOLI, which has a trimethylamine-N-oxide reductase (cytochrome c) activity, and whose adjacent gene in the genome is the cytochrome c-type protein TorC (TORC_ECOLI).
I have cheked the adjacent genes of torA from VIBCH, and the adjacent gene is indeed the cytochrome c-type protein TorC (Q9KRE9_VIBCH). Therefore,  the sequence similarity and the genetic colocalization support the assignation to EC 1.7.2.3 and GO:0050626 for TORA_VIBCH (Q9KRF0). 

Subsequently sent email to sdurkin who is the contact point we have for TIGR (source of those annotations) - cc @bmeldal

**Comment by mcourtot** [comment]
Tony S. and I checked, and there seem to be 2 issues:
1. wrong ISS annotations from TIGR (and we'll see whether that can be solved if we can reach a maintainer)
2. possibly wrong InterPro2GO mapping which generates the IEAs you see. I am tagging this issue with "InterPro" so their curators can see it. **InterPro team**: we are seeing IEAs from your source for example to http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q9KRF0, where GO:0009033 is assigned to torA with InterPro:IPR011887, and it seems this is wrong (torA should instead be assigned with GO:0050626)

**Comment by EBI-Hsinyu** [comment]
Hello,

Thank you for letting us know. I have had a look at the entry 'IPR011887' and found it was assigned the wrong GO term 'GO:0009033'. I have replaced it with 'GO:0050626'. 

Hsin-Yu
InterPro curator

**Comment by mcourtot** [comment]
cc @tonysawfordebi - reminder to check when we get news from TIGR

**Comment by ValWood** [comment]
@pgaudet  if the only outstanding  issue on this ticket is to remove the TIGR mapping you can do that and this one can close

**Comment by ValWood** [comment]
@bmeldal  can you confirm if there is still  an issue here

**Comment by bmeldal** [comment]
No, none of the misleading UniProt and GO annotations have been touched yet. Q9KRF0 is still annotated to 2 different GO MF terms but only one matching EC number. It will still couse the incorrect IEA mappings.

Obviously, I can't change any of these annotations myself.

**Comment by ValWood** [comment]
Can you raise a dispute directly in protein2GO?
If not paste the disputed annotations in here and either me or PAscale can do it. If they are TIGR annotations @pgaudet can fix.
v

**Comment by bmeldal** [comment]
I haven't used P2GO yet. The dispute is above. One annotation is by TIGR (by ISS, but no with/from field either) to one MF, the other is by IEA to another, sibling MF, but the two MFs are linked to diff EC numbers. UniProt matches the GO mapping to EC. I guess the TIGR ISS annotation causes the wrong inferences downstream.

If the TIGR annotation is fixed I guess everything else will fall into place, too. @pgaudet 

I tried to visualise it here:

[Q9KRF0.pptx](https://github.com/geneontology/go-annotation/files/3324280/Q9KRF0.pptx)

Birgit

**Comment by bmeldal** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/10517124/60082690-295fa500-972c-11e9-8c4e-a3bdb95f5d45.png)

**Comment by pgaudet** [comment]
Removed TIGR annotations.
