### ISSUE TITLE
P50750 - MF annotation taken from introduction of paper

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-annotation#1341]
GO:0008353 RNA polymerase II carboxy-terminal domain kinase activity 

is a correct annotation but using IDA from PMID:12721286 comes only from the introduction which seems wrong...

Better papers are: PMID:10866664 & PMID:9499409 if you want to have evidence!

Thanks,
Birgit

**Comment by pedruzzi** [comment]
was not wrong, recombinant human P-TEFb has been used to phosphorylate the CTD of recombinant RNAP IIO to produce the substrate for the phosphatases to be tested (Mat&Meth, Fig 3A)
has been used to annotate the other kinases (cdk1, cdk7, mapk1) as well, and RGD did the same for rat (ISO).
Of course, PMID:9499409 is better evidence, and I added this to corroborate the annotation, as that paper has already been curated for this protein.

**Comment by bmeldal** [comment]
But doesn't F3 only show the phosphatase activity of SCP1? I can't see any measurements for kinase activities of RNAPII - RNAPIIO only acts as substrate for SCP2. What am I missing here?

**Comment by pedruzzi** [comment]
This is correct. F3 shows phosphatase activity of SCP1, using phosphorylated RNAPIIO as substrate. The measurement here is that to produce phosphorylated RNAPIIO, it was treated with either CDK1 (Cdc2), CDK7 (TFIIH), CDK9 (PTEF-b) or MAPK1 (MAPK2/ERK2) and the fact that you actually have, see and measure phosphorylated substrate to act on proves the substrate was phosphorylated by the different kinases. Seemed good enough to me.

**Comment by pedruzzi** [comment]
But if you insist I have no problem removing all of these

**Comment by bmeldal** [comment]
I just looked at the def of the term again and see my error. The term **name** says to me that it's the kinase is the RNAPolII (specifically its CTD) but the **def** defines it as substrate. I appear to read these names in reverse logic.

So it's all good :)

**Comment by pedruzzi** [comment]
oh, I see. No it's always the substrate preceding the kinase in the name, protein kinase, ser/thr kinase, CTD kinase, sugar kinase etc.

thanks for the update :-)
