### ISSUE TITLE
Annotations to ion channels 

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-annotation#1342]
Some time ago, we discussed the issue of selective- versus non-selective ion channels and their representation in GO - this was unsatisfactory to some researchers; Huaiyu reported it and we started to look into this, as described in these annotation call minutes

http://wiki.geneontology.org/index.php/Annotation_Conf._Call,_June_9,_2015#ion_channels

Changes in the ontology are now in place. We may want to look into a re-annotation effort. Probably not a high priority, but we should not let this fall through the cracks - not sure how much work would be needed.

**Comment by pgaudet** [comment]
>2,600 EXP annotations. No strategy to approach this. We cannot do as stated here.
