### ISSUE TITLE
methyltransferase mapping incorrect  for IPR001555

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1343]
IPR001555 has methyltransferase activity

It is present in pombe ade5 (S. cerevisiae ade8, human GART)

It is trifunctional (in human) and these are the activities
this is the
phosphoribosylglycinamide formyltransferase activity 

is the methyltransferase correct?

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

You are right. I have deleted this GO term. 

Hsin-Yu

**Comment by mcourtot** [comment]
Closing as this is done. Please re open if outstanding action to be taken.
