### ISSUE TITLE
Ensembl pipeline propagation issues

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1344]
I just spotted that
human Trifunctional purine biosynthetic protein adenosine-3 GART

has the following mappings from the Ensembl pipeline. A good example of annotations which should probably a) not be transferred and b) sound more like indirect phenotype annotations (GART is involved in nucleotide biosynthesis, and causes problems in DNA replication, so pretty upstream of development???).

brainstem development Source: Ensembl
cerebellum development Source: Ensembl
cerebral cortex development Source: Ensembl

These seem a bit crazy too. Maybe no 'response to annotations' should be transferred....?

response to inorganic substance Source: Ensembl
response to organic substance Source: Ensembl

Will assign to @mcourtot  for consideration in the new Ensembl mapping pipline

**Comment by mcourtot** [comment]
Thanks Val - just seeing this now. Ccc'ing @tonysawfordebi as he is working on the new files.

**Comment by pgaudet** [comment]
Hi @ValWood 
I dont think this is GO-related, but rather is how the ensembl does propagation. I suggest you contact Ensembl directly.

**Comment by ValWood** [comment]
I thought the plan was that GOA was going to take on the  annotation projection from Compara It would be good to know when this happens (and that all things like taxon relations are being observed) as part of the QC. I agree that it no longer needs to be on this tracker.

**Comment by ValWood** [comment]
Most of the issues could be fixed by having certain terms and annotation as "not suitable for propagation via orthology"...could be a longer term low priority task for QA group.

**Comment by pgaudet** [comment]
Hi Val, 

You can add to this ticket for now: 
https://github.com/geneontology/go-annotation/issues/1707

We'll look for a place to store this information (maybe a new subset_property?) what do you think @cmungall ? 

Thanks, Pascale
