### ISSUE TITLE
IPR002975	  incorrect IEA mapping to adenylate cyclase-activating G-protein coupled receptor signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1345]
For pombe gpa1. The effector is not known, but it isn't adenylate cyclase.

adenylate cyclase-activating G-protein coupled receptor signaling pathway	
IEA	IPR002975	GO_REF:0000002

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

You are right. I have deleted this term. 

Hsinyu
