### ISSUE TITLE
GO:0006098	pentose-phosphate shunt	IEA	UniProtKB-KW:KW-0570

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1348]
triosephosphate isomerase   P07669
is mapping to  pentose-phosphate shunt

Is that correct? I cant see it in the pathway

**Comment by deustp01** [comment]
Conventional pathway boundaries have some reactions that generate glyceraldehyde-3-phosphate inside the pentose phosphate shunt, but its conversion to dihydroxyacetone phosphate (glycerone phosphate) by triosephosphate isomerase counts as part of glycolysis.and gluconeogenesis.

**Comment by ValWood** [comment]
tranfferred to list https://github.com/geneontology/go-annotation/issues/1348
