### ISSUE TITLE
IEA	IPR004226 	unfolded protein binding	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1349]
Is this correct? its Tubulin binding cofactor A but this is involved in heterodimer assembly. I don't know if it binds beta-tubulin until it is folded?

**Comment by ValWood** [comment]
to clarify these are the post chaperonin co-factors.
va

**Comment by ValWood** [comment]
ignore, well, the tubulin is 'partially' folded at this stage...I thought the post chaperonin part was assembly of the alpha beta dimers, but it could be a bit of both.
I'm not sure that I would call it 'unfolded' though....

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

I have had a look at this entry yesterday. I agree with you about this GO term. It is not really wrong, but it does not really add huge value in term of functional annotation. I have deleted this term and updated the abstract to reflect the fact this entry also includes yeast Rbl2, which only shares 32% sequence identity with human TBCA and may use different mechanisms to bind beta-tubulin. 

So this entry now has GO term: GO:0007021 tubulin complex assembly and GO:0048487 beta-tubulin binding. Please let me know if this makes sense. 

Regards,
Hsin-Yu

**Comment by ValWood** [comment]
Agreed!
you could add "post-chaperonin tubulin folding pathway" for BP
val

**Comment by EBI-Hsinyu** [comment]
Thanks! I have also added GO:0007023 post-chaperonin tubulin folding pathway.

Hsinyu
