### ISSUE TITLE
IEA check for 	IPR003043 precorrin-2 dehydrogenase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1352]
This domain is described as 

Uroporphiryn-III C-methyltransferase, conserved site

but mapped to
precorrin-2 dehydrogenase activity
which has the synonym
1,3-dimethyluroporphyrinogen III dehydrogenase activity

should it be
GO:0004851	uroporphyrin-III C-methyltransferase activity
(I used this ISO to the SGD entry
http://www.yeastgenome.org/locus/S000001777/overview#go
which had IDA)

**Comment by ValWood** [comment]
GOt it:
precorrin-2 dehydrogenase activity
is probably one or both of these:
PF14823	Pfam	IPR028162	Siroheme biosynthesis protein Met8, C-terminal	163	225	
PF14824	Pfam	IPR028281	Siroheme synthase, central domain	132	158	


The confusion arises because they have a shared N-terminal domain
PF13241	Pfam	IPR006367	Sirohaem synthase, N-terminal

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

Our database is frozen for the InterPro 56.0 release the moment. So, we will update these GO terms a bit later. 

Cheers, 
Hsin-Yu

**Comment by ValWood** [comment]
Thanks, no hurry.

**Comment by EBI-Hsinyu** [comment]
Hello,

Sorry for the late reply. I have had a look at this entry and found that it hits a few multifunctional proteins and some related proteins, such as siroheme synthase cysG protein and cobalamin biosynthesis protein CobIJ. Therefore, the GO term "precorrin-2 dehydrogenase activity"  is too specific. I have deleted this term. Thank you for spotting this. 

Regards, 

Hsin-Yu
