### ISSUE TITLE
IPR01180 cysteine metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1353]
This is in a pathway upstream of cysteine metabolism (although it is required for some sulpher containing amino acids)
http://www.genome.jp/dbget-bin/www_bget?spo:SPAC13G7.06

cysteine metabolism is indirect.

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

Thank you for this. I have deleted this GO term. I kept GO:0019379 and GO:0004604 for this entry. 

Regards, 

Hsin-Yu
