### ISSUE TITLE
	IPR016652 mapping to omega peptidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1355]
Is this correct for ubiquitin hydrolases? it doesn't seem to fit this def.

Val

**Comment by ValWood** [comment]
same question	IPR017390

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

Thank you for spotting this. You are right. I have deleted this GO term and added more appropriate terms, such as  'GO:0016579 protein deubiquitination' and 'GO:0004843 ubiquitin-specific protease activity'. The same applies to IPR017390. 

Regards, 
Hsin-Yu

**Comment by mcourtot** [comment]
Closing as this is done. Please re open if outstanding action to be taken.
