### ISSUE TITLE
PTHR11848 PANTHER:PTN000218063 odd PAINT 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#1357]
Hi

I find it odd that dpp (TGF-beta ortholog, P07713, Drosophila) is annotated to TGF-beta receptor binding based on homology with BMP4 (at least this is how it is listed at flybase). At QuickGO it is listed with  
PANTHER:PTN000218063. But then P12644 (BMP4_HUMAN) is part of this Panther family and is annotated to  TGF-beta receptor binding although there is experimental evidence to support this protein as bind the BMP receptor which is correct GO:0070700 BMP receptor binding PMID:7811286. I don't think it is appropriate for BMPs to be annotated to TGF-beta receptor binding. 
Please could someone review the annotations associated with this family and consider PAINTing to the parent term receptor binding, or to the more specific terms if the sub-families are available which group the proteins into TGF-beta orthologs v BMP orthologs.

BTW I am unable to view the 'trees' at PANTHER due to safari blocking access and my attempts to unblock access have been unsuccessful so advice on the URL to use for this this would be helpful.
Thanks

Ruth

**Comment by dosumis** [comment]
I used to work on this pathway.  I'm pretty sure there is direct biochemical evidence for binding to Drosophila BMP receptors (sax, tkv, bab).

**Comment by RLovering** [comment]
yes but is there evidence for BMPs binding to TGFbeta receptors?

**Comment by pgaudet** [comment]
PTHR11848: 600 member family

**Comment by huaiyumi** [comment]
The annotation is based on a mouse experimental evidence: https://www.ncbi.nlm.nih.gov/pubmed/?term=17878231
This is probably a weak evidence because it's an IPI one.

**Comment by thomaspd** [comment]
We discussed this, and we think the annotation is OK, as BMP and TGF beta receptors are in the same family.
