### ISSUE TITLE
IPR024222 capping not lengthening?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1359]
Not sure about this one, but I think ten1 should be "telomere capping" not "telomere maintenance via telomere lengthening" (its cap complex)

Val

**Comment by Pauldenny** [comment]
Is this of interest to @RLovering @rachhuntley @NancyCampbell ?

**Comment by RLovering** [comment]
Hi 

Jess has sent me this: I agree capping more accurate - if this is pombe ten1 then I see it already has an annotation to "telomere capping"  - as well as "telomere maintenance via telomere lengthening".

Best

Ruth

**Comment by EBI-Hsinyu** [comment]
Hello, 

Than you for this. I have change the term into 'telomere capping'.

Hsin-Yu

**Comment by mcourtot** [comment]
Closing as this is done. Please re open if outstanding action to be taken.
