### ISSUE TITLE
IPR015519 to replicative senesence

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1360]
This seems wrong for ATM checkpoint kinase. Is there a reference? it sounds like a phenotype.

val

**Comment by mcourtot** [comment]
Hi Val, I looked at the other ticket, https://github.com/geneontology/go-ontology/issues/12305, and was wondering whether this should be a taxon constraint? If this term is not applicable to Pombe we can maybe just state that and have those annotations be removed after the InterPro mapping step?

**Comment by ValWood** [comment]
That could be  a solution but it isn't a way they have been dealt with previously (mappings should be true across kingdoms....with some exceptions like active site mutations, which get flagged). This means that the mappings  can be used for protein families independently of knowledge about GO taxon restrictions.

I would describe cellular ageing in yeast as a phenotype, not a process, but SGD do have  some annotations to the replicative senesence term (DPB3 and 4) so they might  be able to justify it's  use for yeast as a normal process. Once we have heard back from SGD about whether these should be treated as a normal process for fungi we can decide about the taxon restriction.

I can easily work around it for pombe by adding a local filter, but I prefer that any problems are fixed at source if possible.

**Comment by ValWood** [comment]
I don't think
GO:0090399 replicative senescence 
is a good mapping for ATM kinase

The term isn't quite right for starters (I'll address that elsewhere), but this won't really work for yeast.

**Comment by ValWood** [comment]
Hi @asangrador  this is a very old one so I assigned to you as I don't know if you would pick this up otherwise.

Best

Val

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/14881

**Comment by asangrador** [comment]
Yes, this ticket was out of radar. The good thing is that if this entry (contributing signature PTHR11139:SF96) matched fungi in the past, it does not anymore. Now it only matches Metazoa, so the 'replicative senesence' mapping won't create any problem [PMID:15149599]. Adding a taxonomic constrain for the future would definitely help, as GOA post-processing of InterPro annotations would deal with the problem.

**Comment by ValWood** [comment]
OK!
