### ISSUE TITLE
	IPR030847 heme biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1363]
This is indirect, it's a glycine transmembrane transporter acting upstream of this process.

Va

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

This GO term is added because of this reference: PMID:19412178

'......SLC25A38 is important for the biosynthesis of heme in eukaryotes."

Hsin-Yu

**Comment by ValWood** [comment]
It is, but its  upstream of the biosynthesis pathway.... We wouldn't  make a GO annotation to the process in this case. 

See here, although the role in heme biosysnthesis is recognised, the GO annotation isn't made:
http://www.yeastgenome.org/locus/YDL119C/overview

although the phenotype
heme accumulation: decreased
is recorded.

Val

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

After discussing with other curators, we decide to delete this term. Thank you for bringing this to our attention. 

Regards, 

Hsin-Yu

**Comment by mcourtot** [comment]
Closing as this is done. Please re open if outstanding action to be taken.
