### ISSUE TITLE
	IPR028419 actin filament organization 	(and IPR001837 actin binding)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1364]
This doesn't seem to fit for  cap1 (adenylate cyclase)

**Comment by ValWood** [comment]
also cell morphogenesis	IEA	IPR016098

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

I think these GO terms are from:

1. 	Hubberstey AV, Mottillo EP.
Cyclase-associated proteins: CAPacity for linking signal transduction and actin polymerization.
FASEB J. 16 487-99 2002 [PubMed: 11919151]
http://www.fasebj.org/cgi/content/abstract/16/6/487
2. 	Deeks MJ, Rodrigues C, Dimmock S, Ketelaar T, Maciver SK, Malho R, Hussey PJ.
Arabidopsis CAP1 - a key regulator of actin organisation and development.
J. Cell. Sci. 120 2609-18 2007 [PubMed: 17635992]
http://dx.doi.org/10.1242/jcs.007302
3. 	Freeman NL, Field J.
Mammalian homolog of the yeast cyclase associated protein, CAP/Srv2p, regulates actin filament assembly.
Cell Motil. Cytoskeleton 45 106-20 2000 [PubMed: 10658207]
http://dx.doi.org/10.1002/(SICI)1097-0169(200002)45:2<106::AID-CM3>3.0.CO;2-3

Hsin-Yu

**Comment by ValWood** [comment]
I would need to look into this one further.

I'm not sure the actin role is broadly conserved:
CAP is conserved over a wide range of organisms. Cross-species complementation experiments have shown that heterologous CAP can consistently complement S. cerevisiae CAP-dependent cytoskeletal functions but not AC activation. The N-terminus of S. cerevisiae CAP is required to expose AC binding sites to Ras (Shima et al., 2000). S. pombe also requires CAP for AC activity (Kawamukai et al., 1992), but S. pombe AC is not activated by the Ras pathway. CAP in S. pombe must facilitate AC activation in a novel fashion and, consequently, the N-terminus of S. pombe CAP cannot complement S. cerevisiae cap mutants or vice-versa (Kawamukai et al., 1992). CAP isoforms from other species are also unable to complement S. cerevisiae AC activation (Matviw et al., 1992; Vojtek and Cooper, 1993; Yu et al., 1994; Zelicof et al., 1993) and have been argued to operate in their own species-specific signalling pathways (Hubberstey and Mottillo, 2002). The cross-species association of apparently independent signalling and cytoskeletal activities might reflect an as yet unidentified functional integration of the two roles (Vojtek and Cooper, 1993).

On the whole its probably safer  not to annotate the downstream processes regulated by signalling molecules, unless they are known to be broadly conserved. I'll ask an adenylate cyclease expert about this one though....

**Comment by ValWood** [comment]
Actually this one is fine. 
I fund a paper that isn't curated yet!
http://www.ncbi.nlm.nih.gov/pubmed/26542710
