### ISSUE TITLE
IPR032259 	hydro-lyase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1365]
is mapping to	hydro-lyase activity
but is a 
3-hydroxyisobutyryl-CoA hydrolase activity

(I don't know if this is also a hydro-lyase, but it isn't in the ancestry)

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

You are right. I have replace this go term with '3-hydroxyisobutyryl-CoA hydrolase activity'. Thank you for all the feedback. :)

Regards, 

Hsin-Yu

**Comment by mcourtot** [comment]
Closing as this is done. Please re open if outstanding action to be taken.
