### ISSUE TITLE
IPR032465, GO:0046874 quinolinate metabolic process 

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-annotation#1366]
For IPR032465 I think the mapping to 'GO:0046874 quinolinate metabolic process' should be replaced by  'regulation of quinolinate biosynthetic process ; GO:1904984' or 'negative regulation of quinolinate biosynthetic process ; GO:1904985'.

There are two main pathways in ACMS metabolism: 

i) tryptophan ->  ACMS -> QA -> NAD
ii) tryptophan -> ACMS -> AMS -> PA 

QA = quinolinic acid/quinolinate

ACMS is non-enzymatically converted to QA (pathway i). The enzyme ACMSD competes with this pathway to convert ACMS to AMS (pathway ii). Therefore ACMSD levels are inversely correlated with the amount of QA produced.

See Figure 1 in PMID 19843166 for an overview.

Thanks,
Rebecca

**Comment by EBI-Hsinyu** [comment]
Hello Rebecca, 

Thank you for the information. I have deleted the term 'GO:0046874 quinolinate metabolic process'. However, I can't find the terms 'GO:1904984' or 'GO:1904985' in QuickGO or the database. Are these new terms? 

Regards,

Hsin-Yu

**Comment by EBI-Hsinyu** [comment]
The terms seem to be in the database now. I have added 'GO:1904984' in this entry. It will be visible in our next release. 

Regards, 

Hsin-Yu
