### ISSUE TITLE
IPR001094 mappings FMN binding and iron ion binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1368]
I think the other subunit of sulfite reductase (NADPH) activity might be the one which binds FMN (at least this is called the flavoprotein subunit?

Also that should be iron-sulpher cluster or heme binding (I'm not sure which , UniProti entries have both)

val

**Comment by asangrador** [comment]
Hi Val,
This entry matches both the sulfite reductase subunit alpha from bacteria (and not the beta) and the sulfite reductase subunit beta from yeast (but not the alpha). It is describing a flavodoxin-like domain that is supposed to have a flavin mononucleotide (FMN)-binding site. In bacteria, the alpha subunit  binds FAD or FMN, and the beta chain binds one iron-sulfur (Fe4S4) cluster [PMID:7657631]. 
Is this known to be the case for yeast too?  It is just that this entry -and also IPR008254-
seem to agree that it has a flavodoxin-like domain.

I have removed the iron binding term. It already gets iron-sulpher cluster and heme binding from more appropriate domain entries.

Amaia

**Comment by ValWood** [comment]
Hi Amaia,

I think its probably OK. I had a look but I couldn't see a structure of the 2 subunits with FMN so I can't be sure, but it is possible that both subunits bind....

In Uniprot, its the other subunit which  is annotated to bind FMN
http://www.uniprot.org/uniprot/Q09878

not this one
http://www.uniprot.org/uniprot/Q1K9C2

I was basing on this, but I can't see the source of the annotation....

val
