### ISSUE TITLE
IPR028867/IPR028868 mappings to glutamate receptor complex (GO:0032983)

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-annotation#1369]
Neto1 and Neto2 are auxiliary subunits that associate with kainate receptors (KARs) to modulate their function. IPR028867 and IPR028868 are generating IEA annotations for NETO1 and NETO2 to the receptor complex itself (GO:0032983)

In GO the definition of GO:0032983 doesn't include the auxiliary subunits:

kainate selective glutamate receptor complex ; GO:0032983
An assembly of four or five subunits which form a structure with an extracellular N-terminus and a large loop that together form the ligand binding domain. The C-terminus is intracellular. The ionotropic glutamate receptor complex itself acts as a ligand gated ion channel; on binding glutamate, charged ions pass through a channel in the center of the receptor complex. Kainate receptors are multimeric assemblies of GluR5-7 and KA-1/2 subunits.

Therefore these mappings should be revised. Ideally we'd want to annotate to 'colocalizes_with:  GO:0032983': can mappings include qualifiers?

Thank you!

**Comment by asangrador** [comment]
Hi Rebecca,

You are right, the definition for the the receptor complex does not include the accessory subunits, so I have removed this annotation. Unfortunately we don't have the possibility of using qualifiers with our GO annotations, so the only thing I can do is remove them.
Cheers,
Amaia
