### ISSUE TITLE
PTHR10071 PAINT issue: c.elegans heart development GO:0007507 PANTHER:PTN001600558 P28515 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1370]
from GOHelp desk 15th March 2016
http://jira.geneontology.org/browse/GO-1132
[Protein2GO] Notification of annotation dispute concerning protein P28515 (Dispute ID: 4233)

A dispute has been raised over a GO annotation coming from your group. The details are given below.

If you agree with the dispute, please amend or delete the annotation accordingly. If, however, you disagree or need to respond to the disputer, you may contact the disputing curator by replying to this email.

SOURCE ENTITY TYPE ENTITY ID GO ID EVIDENCE ECO ID REFERENCE WITH EXTENSION
REFG protein P28515 GO:0007507 IBA ECO:0000318 GO_REF:0000033 PANTHER:PTN001600558

Dispute ID: 4233
Nature of dispute: This dispute concerns the GO term used
Details:
Alas, C. elegans does not have a heart, so this PAINT annotation will need to be corrected.
Thanks,
--Kimberly

Sent by Protein2GO on behalf of Kimberly Van Auken (vanauken@caltech.edu)

**Comment by pgaudet** [comment]
PTHR10071 > 500 members. Fix postponed.

**Comment by selewis** [comment]
FWIW, in the latest updates there are no IBA annotations (to any organism) for heart development in PTHR10071 so perhaps we're good.

@pgaudet, can you load this family now?
