### ISSUE TITLE
 conflicting SP:KW UniProtKB-KW:KW-0336 & KW:KW-0812

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1371]
O13960 Cell wall protein ecm33

Has conflicting SP:KW annotations
UniProtKB-KW:KW-0336
GO:0031225 - anchored component of membrane (cellular_component)
Definition: "The component of a membrane consisting of the gene products that are tethered to the membrane only by a covalently attached anchor, such as a lipid group that is embedded in the membrane. Gene products with peptide sequences that are embedded in the membrane are excluded from this grouping." [GOC:dos, GOC:mah]

and 
UniProtKB-KW:KW-0812
GO:0016021 - integral component of membrane (cellular_component) [QuickGO, AmiGO, BioPortal]
Definition: "The component of a membrane consisting of the gene products and protein complexes having at least some part of their peptide sequence embedded in the hydrophobic region of the membrane." [GOC:dos, GOC:go_curators]

**Comment by pgaudet** [comment]
We need guidelines for annotating TM proteines; for eg if there are different isoforms or if different parts of the proteins are not attached in the same manner... etc . 
To be discussed. 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Val,

a complex case: it contains a transmembrane, which is predicted cleaved in the mature form. But the presence of the transmembrane triggers the GO GO:0016021. Is the GPI-anchor prediction appropriate, I don't know

In any case, this protein needs complete reannotation. Maybe contact Ivo (@pedruzzi) or send an update request to UniProt?

Thanks

Sylvain

**Comment by ValWood** [comment]
This is probably OK. I opened a ticket, but I see the signal peptide is considered as a TMM.
I think we can close this as it would be difficult to fix at present.

**Comment by sylvainpoux** [comment]
Hi Val,
thanks for sending a ticket. Actually, the transmembrane is at the C-terminus. It is a predicted Type I transmembrane protein. Ivo will have a detailed look
Thanks
Sylvain

**Comment by pedruzzi** [comment]
Hi,
it's an annotation error in UniProt indeed. For GPI-anchored proteins with a cleaved C-ter, we don't annotate a transmembrane at this position. It must have been carried over from our prediction tools. I'll remove the transmembrane annotation.
