### ISSUE TITLE
Please stop spamming me by adding @Val in your comments

### ISSUE THREAD

**Issue by Val** [geneontology/go-annotation#1372]
* https://github.com/geneontology/go-annotation/issues/1004#issuecomment-203917536
* https://github.com/geneontology/go-annotation/issues/1004#issuecomment-203937742
* https://github.com/geneontology/go-annotation/issues/1004#issuecomment-203941244
* https://github.com/geneontology/go-annotation/issues/1004#issuecomment-203945956
* https://github.com/geneontology/go-annotation/issues/1004#issuecomment-203951506

...

**Comment by mcourtot** [comment]
Sorry Val, my mistake - will be more careful with autocomplete in future.

**Comment by Val** [comment]
Thx
