### ISSUE TITLE
ASPGD annotation of splicing components to cell cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1374]
ASPGD has annotations of many splicing components to "cell cycle"

The first one I checked  Aspve1_0039699 is from InterPRO
http://tomodachi.berkeleybop.org/amigo/gene_product/AspGD:Aspfo1_0042686
but this Interpro family does not have this mapping

**Comment by ValWood** [comment]
same for
	Aspfo1_0042686	
	Asptu1_0041558
        Aspgl1_0552764	
        Aspgl1_0552764	

I don't know who is now maintaining ASPGD annotations...

**Comment by pgaudet** [comment]
@marekskrzypek can you please have a look ? 

Thanks, Pascale

**Comment by marekskrzypek** [comment]
Not sure I understand this. The genes listed above only have GO:0000398 and GO:0005681 (splicing and spliceosomal complex) in AspGD's current gaf. No cell cycle annotations. It must have been some error that has been fixed since then..

**Comment by ValWood** [comment]
OK it's an Interpro mapping but it does not exist, so I guess it will disappear when your IEA's are updated, can close.
