### ISSUE TITLE
IPR007150 mapping to "DNA repair"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1376]
hus1 is a checkpoint protein so it isn't involved  in "DNA repair"

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

Sorry for the late reply. InterPro was locked for 57.0 release. I have deleted this term now. This will be visible in InterPro 58.0. Thank you!

Regards, 

Hsin-Yu

**Comment by ValWood** [comment]
now getting the DNA repair mapping from 	IPR016580

**Comment by asangrador** [comment]
DNA repair has been removed from IPR016580 too. It should be fine now.
