### ISSUE TITLE
IPR006195 annotations to GO:0006418 and 4812 problematic

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#1378]
It turns out that AsnA, the ammonia-utilizing asparagine synthetase of E. coli, gets these two GO annotations via IPR006195.  There is indeed an evolutionary relationship between asparagine synthetases and aminoacyl-tRNA synthetases; see, e.g. PMID 12874385.  However, the AsnA enzyme does not charge tRNAs.

Thanks,
Ingrid

**Comment by EBI-Hsinyu** [comment]
Hello Ingrid, 

Thank you for this. You are right. I have deleted these two terms in IPR006195. 

Regards, 

Hsin-Yu

**Comment by almitchell** [comment]
Hi Hsin-Yu,
Was there no higher level term that we could map to this entry?

Alex

**Comment by EBI-Hsinyu** [comment]
In theory, this is a domain entry, no GO term should be given. And there 
are many family entries that have GO terms in them. I think it's safer 
not to give any GO terms.

Hsinyu

**Comment by almitchell** [comment]
Ok - just checking! ;)

**Comment by ValWood** [comment]
>In theory, this is a domain entry, no GO term should be given. 

Is that a general rule?

-pombe has 16 members, all tRNA ligases. If the E.coli member is a ligase, maybe this MF is still appropriate? Val

**Comment by almitchell** [comment]
No, that’s not a general rule. It is just that domain entries are often more difficult to GO map,
since they often occur in proteins with diverse functions (and often the function of the protein is not
the function of the domain).
