### ISSUE TITLE
Annotations to GO:0044179 hemolysis in other organism and its child terms

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-annotation#1379]
We were looking at hemolysis terms and stumbled across some odd annotations in QuickGO. 

The host albumin is being annotated to hymolysis by symbiont of host terms. This doesn't make sense to us.

**Comment by vanaukenk** [comment]
Annotations to vertebrate proteins that need review are now in a Google spreadsheet:

https://docs.google.com/spreadsheets/d/1HWYtqMqjuP9pw3jvcMuwK0ogJcg_iGeAFJsi-vpIW9U/edit#gid=0

@ggeorghiou - can you or someone at GOA please take a look?  Thx.

**Comment by pgarmiri** [comment]
Hi,

Most of those annotations were for peptides produced by frogs/fish that have hemolytic activity against human/rabbit red blood cells. I have updated those annotations to GO:0044179    'hemolysis in other organism' as humans/rabbits and frogs/fish are not really symbionts. For each case, I added the interacting taxon in the relevant box.

The most problematic annotation is for P02768   ( Serum albumin) based on PMID:16394536 as the initial message suggested. 
- Firstly, I have added the annotation to the Vibrio protein that actually has the hemolytic activity. 
- They show though that human serum albumin stabilizes VvhA and delay VvhA inactivation by oligomerization, and thus enhance VvhA (Hemolytic) activity. I had a look and I couldn't find a suitable term for this. I though of protein stabilization in other organism perhaps (?) but it's not available and just 'protein stabilization' is not accepted. 
Any ideas of how to capture this?

Thanks,

Penelope

**Comment by pgaudet** [comment]
Possible solution propose by @pmasson55 

Annotate HSA to 
- MF GO:0140272 exogenous protein binding
- BP  GO:0032460 negative regulation of protein oligomerization

(and remove annotation to GO:0044179 hemolysis in other organism) 

@pgarmiri Can you please do that ? (otherwise  @milarolo) 

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
My reaction to reading this paper is that I wouldn't make this annotation. It's not at all clear to me that this is a biologically relevant activity; BSA is used as a nonspecific additive to lots of biochemical reactions to help keep proteins from sticking to other things like the sides of test tubes. The paper alludes to this.

I'm also not sure whether hemolysis is the actual pathogenic process for many bacterial pathogens or if it's an assay for related processes (cell lysis)

**Comment by ggeorghiou** [comment]
Hi all, I've followed @pgaudet and @jimhu-tamu suggestions for this particular issue. I've deleted the annotation regarding hemolysis and added in the two annotations Pascale had suggested.

**Comment by pgaudet** [comment]
Thanks !
