### ISSUE TITLE
UniProtKB - A6NFY7 (SDHF1_HUMAN)

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1381]
Hi,
A6NFY7 has a NAS to GO:0016226 iron-sulfur cluster assembly
based on PMID:19465911

I looked at this paper, and it looks like the authors are just speculating that this protein might be involved in this process (right at the end in the discussion bit)? Could you please review?

**Comment by mcourtot** [comment]
Hi Antonia,

It seems that the NAS evidence code can be used in this case: http://geneontology.org/page/nas-non-traceable-author-statement

If you could provide a little bit more information as to why you think this annotation is wrong I will raise a dispute in P2GO, which will notify the original curator for review.

Cheers,
Melanie

**Comment by ValWood** [comment]
So presumably if they are speculating there is some experimental evidence in the paper to support this?

**Comment by Antonialock** [comment]
SDHAF1 is a mitochondrial respiratory chain complex II assembly factor.

The authors say:
"SDHAF1 contains a LYR tripeptide motif, which is present in the N-terminal region of several protein sequences in different species"

Interpro:
Family: LYR motif-containing protein 2 (IPR026868)
Proteins in this family contain a LYR motif. Their function is not clear.

The authors say that human contains 8 LYR motif proteins. One of these is involved in iron-sulfur cluster assembly, another one is part of the NADH:ubiquinone oxidoreductase complex, and another one is an "iron- responsive protein".

They then say that "These data suggest that the LYR motif is a signature for proteins involved in Fe-S metabolism" and "In particular, NDUFA6, NDUFB9 and possibly SDHAF1 as well could be important
for the insertion or retention of the Fe-S centers within the protein backbones of cI and cII, respectively" 

It looks like the curator used this information to annotate SDHAF1 to iron sulfur cluster assembly
To me, it seems really speculative, I just wanted to flag it up.

**Comment by mcourtot** [comment]
I would suspect, as per the annotation guidelines, that the original curator thought this was a valid statement. I don't think the paper needs to contain experimental evidence supporting this, as the guidelines I linked to above state "As this paper provided no reference to support the author's ascertion that CELF3 is located to the nucleus (nor presentation of sequence analyses related to this statement), and the absence of better published data at the time of curation, CELF3 has been annotated to the GO term nucleus with the NAS evidence code."

This annotation Antonia referenced is quite old (2009) so if you can provide information/evidence as to why this is probably wrong we can raise a dispute. Such information could be disagreeing with the annotation on the basis that you don't think there is enough evidence for a NAS annotation, or could be your scientific knowledge that this is probably wrong based on subsequent publications.

I'm happy raising the dispute in P2GO, but just want to make sure I am providing as much information as possible in the ticket for the original curator to review. @Antonialock: just saw your comment, I will copy this in the ticket and forward to the original curator, thanks!

**Comment by mcourtot** [comment]
Original curator agreed and deleted the annotation.
