### ISSUE TITLE
Deprecate JCVI set

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-annotation#1387]
AI from Geneva meeting

Do we have a protocol for updating annotations from groups that have become inactive? @paolaroncaglia mentions @RLovering & her group can update HGNC annotations, but this is on a case by case basis.

@thomaspd will mention this to Jim Hu

**Comment by pgaudet** [comment]
We now have a mechanism to handle these annotations. So it's all good, this can be closed.
