### ISSUE TITLE
	IPR013882 DNA replication checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1389]
Based on pombe papers, we should not map this to "DNA repliciation checkpoint".

it causes defects, which are detected by the replication checkpoint, but as far as we are aware it is upstream of the sensor. For more information see 
https://github.com/pombase/curation/issues/587#issuecomment-214698773

Thanks

Val

**Comment by asangrador** [comment]
Thanks for letting us know. I have removed the annotation.

Amaia

**Comment by ValWood** [comment]
Yeah, we, and even our  checkpoint experts would have made that annotation until recently. 
Lots of gene  when mutated cause problems which are sensed by the checkpoint signalling. If you knock out a gene and the checkpoint is still active it's  not directly involved in the signalling pathway.
Val
