### ISSUE TITLE
IPR033031 gene expression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1391]
Cohesin has a role in gene expression, but this is the loading factor for cohesin, so its  effects on gene expression are quite indirect.

**Comment by EBI-Hsinyu** [comment]
Hi Val, 

Thank you for the e-mail. We have had a discussion among the InterPro curators to decide if we want to keep this term. 

This entry includes proteins from fungi, plants and animals. The fungi protein Scc2 is known to be part of the loader for the cohesion to be loaded onto the chromosome  [PMID:19797771]. More recently, budding yeast Scc2 has been shown to regulate gene expression independent of cohesin [25715109].

The zebrafish Scc2 homologue, Nipbl, has been shown to regulate transcription. Nipbl has the ability to interact with other molecules such as histone deacetylases, HP-1gamma, and chromatin remodelling factors. Therefore, the author of this paper [PMID:22039349] suggests that Nipbl is a cohesin-asociated scaffold protein that have functions other than loading cohesin. The Drosophila Nipped-B has also been shown to regulate gene expression [PMID:17965872]. 

Therefore, we think it is likely that the Scc2/Nipped-B family members are involved in regulation of gene expression. 

Regards, 

Hsin-Yu

**Comment by ValWood** [comment]
Hi  Hsin_yu,

You are correct. The cohesin loader also appears to have a  probably role outside of cohesin.

I  asked a chromatin expert about this (Frank Uhlmann at Crick).  He is happy for me to share the thread with you so I will forward. The cohesin subunits themselves should  likely not have a  "gene expression" annotation (at least this is the case for yeast), but currently they don't so this is all fine.
