### ISSUE TITLE
hydrolase activity for checkpoint protein	UniProtKB-KW:KW-0378

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1392]
As far as I know there isn't any evidence that Rad1 checkpoint clamp complex protein has this activity?

P22193 DNA damage checkpoint control protein rad1

**Comment by ValWood** [comment]
Actually this is odd. I'm picking up "hydrolase" but the UniProt  entry has "nuclease activity"
(I'm not aware of evidence for either?)

Also, the annotation to "DNA repair" isn't completely correct   here. This  is part of the checkpoint which slows the cell cycle *whilst* repair takes place.

**Comment by ValWood** [comment]
The repair is InterPRro, will open a new ticket for that one...

**Comment by ValWood** [comment]
PomBase	SPAC1952.07	rad1		GO:0016787	GO_REF:0000037	IEA	UniProtKB-KW:KW-0378	F	checkpoint clamp complex protein Rad1	rad19	protein	taxon:4896	20160312	UniProt

**Comment by ValWood** [comment]
Note that in the UniProt entry "nuclease" is visible for KW mapping, not hydrolase.  It seems to be hydrolase in our most recent Gaf, as far as I know, neither is correct.

**Comment by pgaudet** [comment]
Fixed according to @sylvainpoux
