### ISSUE TITLE
	IPR003011 DNA repair /cohesin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1393]

**Comment by ValWood** [comment]
the annotation to "DNA repair" isn't completely correct here. This is part of the checkpoint which slows the cell cycle whilst repair takes place.

**Comment by almitchell** [comment]
Hi Val,
We would keep the DNA repair term for the Rad1 proteins, as there seems to be evidence that they (or rather the complexes they form) may be involved not just in the checkpoint, but in DNA repair itself. This is quite an old paper (2004), but seems relevant:

http://www.sciencedirect.com/science/article/pii/S1568786404001041

> The prevailing view is that checkpoint activation indirectly participates in DNA repair by slowing cell 
> cycle progression and allowing time for repair. The 9–1–1 complex appears to have a more direct role 
> in DNA repair, however. Studies in S. cerevisiae and S. pombe have implicated the 9–1–1 complex in 
> the regulation of mutagenic translesion synthesis [46] and [47], a repair pathway that requires a 
> specialized family of DNA polymerases known as the mutagenic, error-prone, or translesion 
> polymerases (reviewed in  [48], [49], [50] and [51]). 
...
> Studies in yeast demonstrate that the 9–1–1 complex also plays a role in the repair of double-strand 
> breaks. In S. cerevisiae, deletion of the Rad17 (scRad24) clamp loader and the Rad1 (scRad17) clamp 
> subunit lead to decreased survival following the introduction of enzymatically produced double-strand 
> breaks  [52]. 

We would also argue that Rad1 proteins would still contribute to the overall process of DNA repair, even if they were just involved in slowing the cell cycle, since presumably this is crucial to the overall process. There seems to be a question about how involved in a process a protein has to be to get the GO term and this seems to be a bit inconsistent across databases at the moment. Might it be worth meeting to discuss this with the InterPro and GOA teams next time you are at EBI?

Alex

**Comment by ValWood** [comment]
If the repair signalling is indirect, as in:

"The prevailing view is that checkpoint activation indirectly 
participates in DNA repair by slowing cell
cycle progression and allowing time for repair"

We would not annotate the signalling pathway to repair, the cell cycle 
checkpoint genes aren't regulation the repair process per. se.
For regulation it needs to be  modulating the process, not just giving 
it time to happen.

However,  if this is true:
The 9–1–1 complex appears to have a more direct role
in DNA repair, however. Studies in S. cerevisiae and S. pombe have 
implicated the 9–1–1 complex in
the regulation of mutagenic translesion synthesis [46] and [47], a 
repair pathway that requires a
specialized family of DNA polymerases known as the mutagenic, 
error-prone, or translesion
polymerases (reviewed in [48], [49], [50] and [51]).

we would make the annotation. We will check now for good evidence for a 
direct repair role for rad1, especially as you have highlighted some 
pombe papers.

Re > We would also argue that Rad1 proteins would still contribute to 
the overall process of DNA repair, even if they were just involved in 
slowing the cell cycle, since presumably this is crucial to the overall 
process.

We wouldn't. Many processes are required upstream of another process. If 
you followed this to its logical conclusion, GO would no longer be 
useful. We would ask the question "would our users expect this gene 
product to be annotated to DNA repair, and for the  checkpoints". They 
wouldn't (I already asked some people who have worked in this field 
since the beginning).

A more obvious example might be the spindle checkpoint. This halts the 
cell cycle until chromosome attachment is correct, but you would not 
expect to see all of the spindle checkpoint genes annotated to 
"chromosome attachment". It wouldn't make sense.

We can discuss this further.  We have some good guidelines at PomBase 
but they are a bit anecdotal, I need to document them more precisely.

Val


On 04/05/2016 13:44, almitchell wrote:
>
> Hi Val,
> We would keep the DNA repair term for the Rad1 proteins, as there 
> seems to be evidence that they (or rather the complexes they form) may 
> be involved not just in the checkpoint, but in DNA repair itself. This 
> is quite an old paper (2004), but seems relevant:
>
> http://www.sciencedirect.com/science/article/pii/S1568786404001041
>
>     The prevailing view is that checkpoint activation indirectly
>     participates in DNA repair by slowing cell
>     cycle progression and allowing time for repair. The 9–1–1 complex
>     appears to have a more direct role
>     in DNA repair, however. Studies in S. cerevisiae and S. pombe have
>     implicated the 9–1–1 complex in
>     the regulation of mutagenic translesion synthesis [46] and [47], a
>     repair pathway that requires a
>     specialized family of DNA polymerases known as the mutagenic,
>     error-prone, or translesion
>     polymerases (reviewed in [48], [49], [50] and [51]).
>     ...
>     Studies in yeast demonstrate that the 9–1–1 complex also plays a
>     role in the repair of double-strand
>     breaks. In S. cerevisiae, deletion of the Rad17 (scRad24) clamp
>     loader and the Rad1 (scRad17) clamp
>     subunit lead to decreased survival following the introduction of
>     enzymatically produced double-strand
>     breaks [52].
>
> We would also argue that Rad1 proteins would still contribute to the 
> overall process of DNA repair, even if they were just involved in 
> slowing the cell cycle, since presumably this is crucial to the 
> overall process. There seems to be a question about how involved in a 
> process a protein has to be to get the GO term and this seems to be a 
> bit inconsistent across databases at the moment. Might it be worth 
> meeting to discuss this with the InterPro and GOA teams next time you 
> are at EBI?
>
> Alex
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/go-annotation/issues/1393#issuecomment-216851741>
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by ValWood** [comment]
Hi Alex,

This is what Paul Russell has to say http://www.scripps.edu/russell/publications.html. 
Paul is a leading authority, he has been working in this area since the early 80’s

==
It is good to hear from you. Here’s my take on 9-1-1 and repair:

1- Evidence for 9-1-1 being required for activation of Chk1 and Cds1 is clear and convincing and universally accepted in the field. 

2- The inability to activate Chk1 and Cds1 is sufficient to explain all the DNA damage sensitivities of 9-1-1 mutants. Therefore there is no “need” to propose that 9-1–1 also has DNA repair functions. 

3- There have been several reports of 9-1-1 being involved in DNA repair or interacting with DNA repair proteins, although I would say they reports exist in isolation, have not been confirmed by independent investigators, and may not be generally accepted by the field (or me). So yes they are tentative. 

4- Notable for fission yeast, Kai et al (PMID: 17515930) reported that phosphorylation of Rad9 on Thr225 regulates repair pathway choice without affecting sensitivity to DNA damaging agents. No evidence for mechanism.  

5- On the other hand, Furuya et al (PMID: 21095590) reported that a T225C mutation causes sensitivity to camptothecin, perhaps by inhibiting 9-1-1 disassociation from chromatin and thereby interfering with DNA repair. In this sense 9-1-1 has an “anti-repair” activity. 

So in summary I would say the evidence for 9-1-1 being involved in DNA repair is quite tentative, although it remains a reasonable possibility. 

I hope this helps a bit. Feel free to contact me if you need anything else. 

All the best! 

-Paul

==

Paul was happy for me to share his thoughts.

So, although it is possible, the evidence is tentative, or even absent. I think it is an OK annotation for the publications which hint at this possibility , if other MODs think it appropriate.

In the   publication  cited in the review, we did not find that the evidence was conclusive for a role in repair:
see https://curation.pombase.org/pombe/curs/25c44b9071bd33a2/ro/

The reviews use quite selective language like  "appears to have" and "suggests that"  or “implicates” which is often a clue that there is no clear evidence ;)
In the light of this I would say an IEA mapping was premature... but if you want to keep it we will filter for PomBase. We are a bit fussy. 

Val

**Comment by almitchell** [comment]
Hi Val,
Thanks for looking into this in detail. Based on your feedback, I think we will delete the term from InterPro for this entry and its parent, and replace it wih 'DNA damage checkpoint'. 

BTW, it might be worth expanding this discussion to include the other databases (not quite sure how to do this via GitHub). Looking at the family members in other organisms, the human protein (O60671) has the term 'DNA repair' sourced from Reactome. Meanwhile, the pombe (P22193), mouse (Q9QWZ1) and other family members are getting 'DNA repair' sourced from UniProt keywords, as well as InterPro, so this will need fixing in the other dbs or the annotation will persist.

Alex

**Comment by ValWood** [comment]
Yep. There is a plan for me to talk about this on an annotation call (not yet scheduled). It might help me to plan to go through with you guys and some local curators first using these examples.
If there are errors in other species I do try to report them, but it is a bit ad hoc unfortunately because there are lots. Ideally we would have time/resources to work through every process intersection systematically.

For example, It is most likely for example that I have already reported the SPKW issues. Once I report them, I filter them for PomBase so if they don't actually get fixed they don't come onto  my radar again.

It might help me to work out how to present  the procedures we use on the call if we meet up earlier with you Melanie and others. The methods are  often used to identify ontology issues so it might help if some of the editorial office participated too.

This particular one might be part of a separate issue, where they evidence to make a mapping should maybe be a bit more 'solid', and this is  a bit more difficult to address...although existing annotations  guidelines can be used to address to a certain extent. 

I'm away next week, but I'll make a plan once I return.

Val

**Comment by ValWood** [comment]
As an aside, the Matrix
http://tomodachi.berkeleybop.org/matrix
showed only 2 EXP annotation where cohesin subunits intersected with transcription (Zfin and MGI). I raised disputes for these through protein2GO.
