### ISSUE TITLE
mappings to protein sumoylation from Reactome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1394]
Hi Peter,

I think there are some problems with some of theReacome mappings to "protein sumoylation"

I would usually do these via the protein2GO annotation dispute system, but there are quite a lot of these
231 annotations for 108 proteins
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016925#term=annotation
I think I have reported some already.

Some of are clearly  involved in sumoylation, but the majority it seems as though they are perhaps sumoylated, rather than involved in sumoylation ? (for example the nuclear pore proteins, DNA topoisomerase I, PCNA etc), if this is the case it might be best to suppress the export of this mapping?

Val

@deustp01

**Comment by deustp01** [comment]
Fixed. Changes should become visible with the next release of Reactome in mid-June.

**Comment by ValWood** [comment]
Although some are gone. The following are still annotated to "sumoylation" in quickGO

TOP1
TOP2A
PCNA
NUP214
NUP62
RNAGAP1 ? not sure about this
RNBP2 ?  not sure about this
NUP98
NUP107
NUP188
NUP54
NUP93
NUP107
NUP85
INCENP
NUP58
NUP85
NUP88
NUP205
NUP160
NUP43
NUP37
NUP35
NUP210

possibly others.
Because  of the small number of true positives for Sumoylation this is probably going to obscure any enrichment to this term.

**Comment by deustp01** [comment]
These are happening because the Reactome script for parsing reactions to assign GO biological process terms to proteins takes all the proteins associated with the reaction, including ones that are involved as substrates, and assigns the reaction's BP term to them. While this is really obvious, I didn't see the issue correctly until the GO meeting in November when someone (Ruth Lovering, I think) framed the actor versus acted-upon distinction so that I got it. We will need to fix this script.

**Comment by pgaudet** [comment]
Hi @deustp01 
Has this been addressed ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@deustp01 emailed that they will try to get this fixed in Reactome release 64 due in March 2018. 

We'll check again then. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@deustp01 Any update on this ? 
For example at least NUP155 (O75694) is still annotated to protein sumoylation. 

Thanks, Pascale

**Comment by deustp01** [comment]
The release is scheduled for later this month.

**Comment by pgaudet** [comment]
Thanks, I'll check again possibly in the April 2019 GO release.

**Comment by ValWood** [comment]
There was another ticket about sumoylation/Reactome which aI already closed, so this must be a duplicate
