### ISSUE TITLE
Remove constraint on IEP only applying to BP

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1395]
Consider an IEP annotation to 'cellular response to glucose stimulus'

This will yield an inference to locatization to 'cell'. We can argue about the utility of this, but it's logically and biologically correct, and we don't have 'cell' in our antislims.

There may be other cases where an IEP leads to inference of a subcellular location - currently prohibited.

@tberardini and I propose removing the constraint that IEP only applies to BPs.

**Comment by mcourtot** [comment]
Hi @cmungall and @tberardini,

With the changes in evidence codes (see http://www.ebi.ac.uk/GOA and copied below), the inferred annotation would not have an IEP code, but rather an IEA (mentioned by @rachhuntley) 
So do you here actually mean removing the constraint that we don't infer from IEPs annotations on BPs, independently of the evidence code the inferred annotation would have?

Cheers,
Melanie





Changes to annotations created by logical inference 
=================================================== 

With effect from this release, we have made a change to the format of annotations that are created by logical inference based on inter-ontology links between molecular function and biological process terms, or between biological process and cellular component terms. These annotations can be identified easily, as they have "GOC" in the assigned_by column of the GAF and GPAD files. 

In previous releases, these logically inferred annotations retained the reference, with/from, and evidence code of the annotation to the asserted GO term from which they were derived. Now, however, inferred annotations will have GO_REF:0000108 (http://www.geneontology.org/cgi-bin/references.cgi#GO_REF:0000108) as their reference, and one of the two evidence codes ECO:0000364 (evidence based on logical inference from manual annotation used in automatic assertion) or ECO:0000366 (evidence based on logical inference from automatic annotation used in automatic assertion), depending on whether the annotation to the asserted term is manual or electronic, respectively; the with/from column is also populated with the identifier of the GO term in the original asserted annotation.

**Comment by cmungall** [comment]
I'm not following. Where does this text come from? Do we have two pipelines for this with different rules?

**Comment by tberardini** [comment]
I, too, am confused.  I thought that GOC was creating the annotations based on MF-BP links and that the member MODs were consuming these annotations.  Does GOA have a separate pipeline to generate MF-BP annotations?

**Comment by mcourtot** [comment]
The text above (coming from the hyperlink above) describes behaviour in the GOA pipeline. At the moment, we do not infer from IEP annotations, but we could lift that constraint if this is desired. However, the current constraint in the inter-ontology link pipeline is not "IEP can't be used with CC" but "we don't project from IEP". 

The changes to evidence codes for inferred annotations has been discussed on the go-managers list, and more recently at the Geneva meeting. I was unable to find how to access the archives for the go-managers list, but messages are:
Evidence code and tracing inferred annotations (18/06/15)
proposal for new evidence code(s) to use in inferred annotations (19/06/15)

**Comment by tberardini** [comment]
Reviving this thread.  This is related to the recent discussion in the GO eds call about unifying the annotation inference practices of the Jenkins and GOA pipelines.  For the purposes of the annotations in this issue, the suggestion to remove the rule that IEP can only be used with BP (GO_AR:0000006).

http://geneontology.org/page/annotation-quality-control-checks#0000006

**Comment by ValWood** [comment]
I'm leary of this change. For starters we only use the IEP evidence code judiciously. I'd hope that anything annotated to these terms already had a 'cell' annotation descendent  at PomBase so it would be filtered in most  cases. However in the few cases (10) where we have no component annotation, but we have a response to some stimulus annotation,  I'd rather keep these as "CC ND" because we don't know *whereabouts* in the cell they are located. I'd say that for single celled organisms it isn't really useful to annotate to 'cell' directly.

in fact, we already have "cell" in the list of terms we don't use for annotation:

https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/GO_terms_excluded_from_pombase.txt

This list is  only a soft check. Mainly its for terms which we know we should always be able to make a more specific annotation. For  cell its because for yeast it isn't really informative (it wouldn't help our users to make this annotation)

**Comment by ValWood** [comment]
Hang on, does  "occurs_in"  generate  CC annotations by inference  right now?

I'm looking at one example where we have a response to annotation but no CC annotation
http://www.pombase.org/spombe/result/SPBC4C3.04c

This term has ancestry to cell via 'occurs_in"
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007264#term=ancchart
but we don't get a "cell' annotation here?

I still worry about transferring evidence across ontology aspect like this. For example here if you had an annotation by IDA or IMP to GTPase mediated signal transduction it would seem odd to have a corresponding annotation to "intracellular"  from the same paper with this evidence if it wasn't actually assayed. This isn't a great example but there are cases where it could become very confusing in a way that it isn't for MF->BP

**Comment by hattrill** [comment]
Hi Val,

The occurs_in inference to CC  is made in the Jenkins pipeline. I am not a fan as there are examples like this:

FBgn0000482	dor	GO:0005622 intracellular
FBgn0000482	dor	GO:0005623 cell

inferred from GO:0008333 endosome to lysosome transport IMP

(GO:0005622	intracellular	AnnotationPropagation	C	GO:0008333	endosome to lysosome transport	IMP
GO:0005623	cell	AnnotationPropagation	C	GO:0008333	endosome to lysosome transport	IMP)


Even having >1 cell, I would not use these terms in annotation as they are not informative.

I would rather restrict to MF > BP inference.

Helen

**Comment by ValWood** [comment]
We import the inference pipeline data, but I forgot we also have  hard-check which excludes some  term annotations from external sources (this helps our users to find unannotated things).

So, in addition to the 1123 terms in the soft check file above,
we  have 125 terms in a hard check file for external data
https://curation.pombase.org/dumps/latest_build/pombe-embl/goa-load-fixes/filtered_GO_IDs
"Cell" is in here which is why I don't see them. 

This filter is mainly for "bad mappings" which have not been fixed (lots) https://github.com/geneontology/go-annotation/issues
(but we ensure first that we have made any appropriate or more specific manual annotations  for true positives).

There are 2 issues:
We have had the discussion before about whether it is appropriate to make these annotations with the original evidence code. I remember Rama was strongly opposed, and I think most curators would be uncomfortable with this. It does catch us out when we see them. The shouldn't really have the original experimental code as the cellular location has not been assayed. Really they are "inferred from MF or BP annotation"

Secondly the usefulness of making annotations to these high level terms in an automated way if a curator has chosen not to infer them. I would prefer not to, but can continue to filter...

**Comment by srengel** [comment]
i agree with Val on this. 
1. it is not appropriate to make these mapped annotations using the original evidence code.  
2. i do not see the utility of making these high level annotations automatically if the curator who made the original annotation (from which the high-level annotation is to be automatically generated) chose not to make that annotation.  there is a reason why we have humans with brains making curation decisions (as opposed to automated scripts without curation judgment).

**Comment by hdrabkin** [comment]
So today during my weekly QC, three IEP annotations to a cellular component were found that were attributed to GOC.  It used a specific literature reference.
The same reference was used to make IDA process annotation by GOA_CACAO (coming in from our GOA mouse load).  So if the GOC was made based on the GOA_CACAO IDA, why did it get a different evidence code, especially if the use of that evidence code with a cellular process breaks rules of use for that code? This came in for two different gene annotations from the same group.
The other onee were one where UniProt (from our GOA mouse load) used a paper for a cellular component, and the GOC annotation came in for a cellular component annotation using IEP

**Comment by cmungall** [comment]
This thread has too may things going on to make sense of.

These problems all go away if we add inter-ontology links (MF-part-of-BP, BP-occurs-in-CC) to go-basic and cease materializing inter-ontology inferences.

I added a ticket for this: #1427

If we agree on this, then this ticket (#1395) becomes irrelevant, and we don't need to worry about the fact that GOC and GOA pipelines have diverged etc.

**Comment by ValWood** [comment]
This  ticket did go off on a tangent, sorry. 

However, I think this ticket revealed a larger problem, in that the biologists making the annotations, at least at PomBase, Flybase and SGD  are uncomfortable with 
a) some of the annotations which are generated by the inference pipeline
and
b) The preservation of the evidence code.
I don't know how much of this would apply if the annotations were not "materialised" but I think that its important  at least that curators understand the consequences of not making the explicit annotations if they want to see  annotations to these terms appear on their gene pages. I don't think this is clear so far.....

Could this be discussed on a future annotation call to make sure we all understand ?
 @ukemi I want to tag Kimberley  too  but her user ID doesn't pop up
)

**Comment by ukemi** [comment]
Kimberly and I have been discussing this wrt LEGO models too. I definitely think it needs to be brought up on a call or at the GOC meeting.

**Comment by tberardini** [comment]
@cmungall, @ValWood, @ukemi , @vanaukenk: Can this still be added to the GO meeting agenda?

**Comment by ukemi** [comment]
Hi Tanya,

It's already here. 

http://wiki.geneontology.org/index.php/2016_Los_Angeles_GOC_Meeting_Agenda#Annotation_Issues_-_LEGO_Annotations

I need it because it is throwing errors in out annotation checker that looks at Noctua models.

-D

**Comment by tberardini** [comment]
Thank you, David.

**Comment by ValWood** [comment]
I pulled out the parts of this discussion that are related to
i) the evidence code used for inter ontology annotation
ii) the usefulness of instantiating these high level terms if they were not made by the curator

They are now in  the newer ticket created by @rachhuntley 
https://github.com/geneontology/go-annotation/issues/1487

So this ticket is now only about the constraint on IEP applying only to BP (which I believe we should retain, it's a "weak" evidence code, and we generally try not to use it).

**Comment by tberardini** [comment]
Wow, it's exactly one year after the last comment.

I've had one violation pop up in this month's jenkins report.  Where are we with keeping/getting rid of the 'IEP only used for BP annotations' rule?


The violation: (from a BP occurs in CC inference by GOC)

209274	**GO_AR:0000006	Warning	IEP usage is restricted to terms from the Biological Process ontology**	TAIR	locus:2092221	STP10		GO:0005623	TAIR:Publication:501768255|PMID:26893494	**IEP**		**C**	AT3G19940	AT3G19940|STP10|SUGAR TRANSPORT PROTEIN 10|MPN9.18	protein	taxon:3702	20160301	**GOC**		TAIR:locus:2092221

**Comment by suzialeksander** [comment]
Closing, as this particular topic (about IEP) seems like the constraint has been removed- there are plenty C and P annotations:
<img width="542" alt="Screenshot 2024-03-09 at 12 16 45" src="https://github.com/geneontology/go-annotation/assets/13735608/98562b91-8ca8-425c-aeec-3db1a88c7f8d">

Also noting some of these arguments are still coming up for GO-CAMS: https://github.com/geneontology/noctua/issues/822 https://github.com/geneontology/noctua/issues/277 https://github.com/geneontology/noctua/issues/584 etc.

**Comment by pgaudet** [comment]
These are allowed for PAINT. OK to close.

**Comment by ValWood** [comment]
I see  61 IEP annotations to MF terms. I can't see how that is possible? Should these be blocked?

**Comment by pgaudet** [comment]
They should appear in error reports
