### ISSUE TITLE
Matrix example, cohesin complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1396]
This ticket is in preparation for the discussion on using  the "Matrix" tool to identify (and fix) annotation errors that will  present on a curation call at some point in the weeks ahead.

Usually for this  I look across all cellular process intersections, but for  demonstration purposes I have restricted to a single  CC term (cohesin complex), intersected with cellular processes.

The green ticks in the figure represent the process intersections that I know to be correct. The others I am unsure about. Some are  very clearly  outliers. 

![matrix example cohesin complex](https://cloud.githubusercontent.com/assets/7359272/15478193/f48c92a0-2110-11e6-9604-7ac73949bf2b.jpg)

All of the disputed annotation have been queried either with you directly or via protein2GO. I will update the figure as I get feedback that the original annotations are correct, or  corrections.

@doughowe
@hdrabkin
@pfey03
@ukemi
@gantonazzo
@hattrill

also tagging Interpro curators and Melanie as they have been asking about the process and asked for a briefing:
@almitchell 
@mcourtot 
@asangrador

@pgaudet  (for PAINT)
and @RLovering  (none of your  groups annotations Ruth, the human ones appear to be legacy uniprot annotations).

@bmeldal  for Intact  annotations for cohesin

The idea is that long term, we make annotation rules
like 
GO:0006520,GO:0006310, NO OVERLAP 
which  will be used  in the Jenkins checks. Obviously  the rules will be updated if new biology violates them.

This is a powerful way to dig out "indirect" annotations   (biologists use of 'indirect' here), which are really phenotypes of processes which have pleiotropic effects. For example, it is known that mutated cohesin can affect  protein levels probably indirectly via transcription-> RNA biogenesis -> translation. However, cohesin does not appear to  'regulate' or 'affect' translation directly in a normal cell.
The transcription intersections are  a little less clear, but the annotated papers don't appear to provide good evidence of this. I will check with a cohesin expert to see what  the consensus on this is.

This method can also identify  errors in the ontology,  but I hope most of these are now reported (at least at the GO slim level for cellular processes).

The working version of the matrix tool is here if any of you want to try it out
http://tomodachi.berkeleybop.org/matrix
you can filter on species in this version, which is much better.
 (it is also useful  to generate a GO slim view of your organism)
I'll prepare one more example for the discussion from mitotic chromosome segregation  over the next few weeks.

**Comment by ValWood** [comment]
cytoskeleton organization  will be fixed by
https://github.com/geneontology/go-ontology/issues/12308

**Comment by pfey03** [comment]
The Dicty vesicle transport annotations (to child 'macropinocytosis' ) from PMID 22120990 are RCA annotations from large-scale analysis. We do not do these kinds of large scale annotations anymore since 2013. Those could be deleted if in violation of anything.

**Comment by ValWood** [comment]
![condensin](https://cloud.githubusercontent.com/assets/7359272/15498563/08cf4d84-2198-11e6-8458-f6856bc9ce71.jpg)

Not bad for day one,  10 experimental/TAS fixed. All of the IEAs derived from them will also get fixed (eventually). This will be A LOT in Ensembl (only the ones in AmiGO get included in these totals).

**Comment by ValWood** [comment]
@pdthomas

**Comment by ValWood** [comment]
Hi Petra, OK, could you delete your RCA to vesicle mediated transport (highly unlikely that condensin has a role in this). It might be worth checking other annotations from this paper...you have 2186 annotations to micropinotosis, mostly RCA from this paper...transmembrane transporters, ribosomal proteins, nucleopoins etc, etc.
v

**Comment by pfey03** [comment]
Deleted 32 RCA macropinocytosis annotations that also have a chromosome annotation (no cohesin manual annotations); there is one other centrosomal protein cepF which is PAINT IBA annotated to ER to Golgi vesicle-mediated transport. Will dig for others or delete all RCA from this paper.

**Comment by pfey03** [comment]
also deleted all ribosomal proteins that were RCA / macropinocytosis from PMID 22120990

**Comment by ValWood** [comment]
outstanding issues (and  more violations) in the new ticket:
https://github.com/geneontology/go-annotation/issues/1490
