### ISSUE TITLE
query about matrix tool

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1399]

**Comment by ValWood** [comment]
I am using this link:
http://tomodachi.berkeleybop.org/matrix
which version of the GO database does this use.

I am preparing a lab presentation about the MAtrix tool for tomorrow.

I notice that the current version of the data PomBase reports 
Query: ( GO_ID(GO:0000003 - reproduction) ) AND ( GO_ID(GO:0044281 - small molecule metabolic process) )
This query matches 8 genes.

SPCC550.10	atd3	aldehyde dehydrogenase Atd3 (predicted)
SPCC306.09c	cap1	adenylyl cyclase-associated protein Cap1
SPCC285.09c	cgs2	cAMP-specific phosphodiesterase Cgs2	
SPBC19C7.03	cyr1	adenylate cyclase	
SPBC32H8.07	git5	heterotrimeric G protein beta subunit Git5	
SPAC23C4.12	hhp2	serine/threonine protein kinase Hhp2
SPAC6F12.02	rst2	transcription factor Rst2	
SPAC17C9.10	stm1	G-protein coupled receptor Stm1	

whereas Matrix reports only one?
I'll check which one shortly.
I want to check whether its due to different versions of the data (seems unlikely because these annotations aren't new?). So, now i'm wondering if not all annotation is included?

**Comment by cmungall** [comment]
Quick answer as everyone is off today

At the bottom of the screen it says:
Last file loaded on 2016-05-22, see full details
http://tomodachi.berkeleybop.org/amigo/load_details
The PomBase one is 2016-05-29 (which is after 2016-05-22...)

I'm not sure how you're translating your set-logic expression to the 
matrix interface. Do you calculate the ID lists yourself?

**Comment by ValWood** [comment]
On 30/05/2016 18:46, Chris Mungall wrote:
> Quick answer as everyone is off today
Yep me too...


>
> At the bottom of the screen it says:
> Last file loaded on 2016-05-22, see full details
> http://tomodachi.berkeleybop.org/amigo/load_details
> The PomBase one is 2016-05-29 (which is after 2016-05-22...)
>
OK our live data is from the 12th April. It would have been submitted to 
GO around  10 MAy so the data should be the same.


> I'm not sure how you're translating your set-logic expression to the
> matrix interface. Do you calculate the ID lists yourself?

I was double checking using PomBase query builder because I wanted to 
fix any violations...

If I intersect "small molecule metabolic process"
and reproduction here
http://www.pombase.org/spombe/query/builder

I get the 8 annotations below:

This seems correct? These are annotated to both terms in current 
dataset....unless something changed in the ontology.....but I could not 
account for the difference this way when I checked current parentage of 
some anotations in QuickGO


>
> On 30 May 2016, at 9:57, Val Wood wrote:
>
> > I am using this link:
> > http://tomodachi.berkeleybop.org/matrix
> > which version of the GO database does this use.
> >
> > I am preparing a lab presentation about the MAtrix tool for tomorrow.
> >
> > I notice that the current version of the data PomBase reports
> > Query: ( GO_ID(GO:0000003 - reproduction) ) AND ( GO_ID(GO:0044281 -
> > small molecule metabolic process) )
> > This query matches 8 genes.
> >
> > SPCC550.10 atd3 aldehyde dehydrogenase Atd3 (predicted)
> > SPCC306.09c cap1 adenylyl cyclase-associated protein Cap1
> > SPCC285.09c cgs2 cAMP-specific phosphodiesterase Cgs2
> > SPBC19C7.03 cyr1 adenylate cyclase
> > SPBC32H8.07 git5 heterotrimeric G protein beta subunit Git5
> > SPAC23C4.12 hhp2 serine/threonine protein kinase Hhp2
> > SPAC6F12.02 rst2 transcription factor Rst2
> > SPAC17C9.10 stm1 G-protein coupled receptor Stm1
> >
> > whereas Matrix reports only one?
> > I'll check which one shortly.
> > I want to check whether its due to different versions of the data
> > (seems unlikely because these annotations aren't new?). So, now i'm
> > wondering if not all annotation is included?
> >
> > ---
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > 
> https://github.com/geneontology/go-annotation/issues/1399#issuecomment-222527884
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/geneontology/go-annotation/issues/1399#issuecomment-222533392>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AHBLKFGc4aL4yNi2xe6_6lBWjmRxRnP_ks5qGyJagaJpZM4Ip7jQ>.
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by ValWood** [comment]
In matrix only atd3 is included in the intersection GO:0044281/GO:0000003

http://tomodachi.berkeleybop.org/amigo/search/bioentity?q=*:*&fq=taxon_subset_closure_label:%22Schizosaccharomyces%20pombe%22&fq=isa_partof_closure:%22GO:0044281%22&fq=isa_partof_closure:%22GO:0000003%22

I'll confirm one of the missing ones in AmiGO...

**Comment by ValWood** [comment]
cap1 has

negative regulation of conjugation with cellular fusion which has 'reproduction' parent
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0031138#term=ancchart

regulation of adenylate cyclase activity has "small molecule metabolic process' parent
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0045761#term=ancchart

both annotations are here:
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC306.09c

**Comment by ValWood** [comment]
Something else is odd. Our slim has been relatively stable over the last few releases, but the slim totals differ a little between PomBase and GO. (matrix)

protein folding PomBase  103 Matrix 101
carbohydrate metabolic process PomBase  211 Matrix 97
generation of precursor met and energy PomBase  82 Matrix 76
cell wall organisation and bio. PomBase  108 Matrix 85
tRNA metabolic process PomBase  161 Matrix 160
lipid metabolic process PomBase 227 Matrix 214
signalling  PomBase  364 Matrix 294

**Comment by ValWood** [comment]
Ok its 'regulates' relationship......
That's no problem (would be good to be able to toggle on and off).

It just menas that this pass, I won't locate all of the  issues. Its probably enough to be going on with. Nothing will be wrong.
