### ISSUE TITLE
Go camp annotation issues from FlyBase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#14]
Here's some topics FB curators would like discussed at
the GO annotation camp:

1. Process Assays In Non-Drosophila Cells:

In FBrf0105796 (PMID:9857177), the authors expressed
Drosophila grim in mouse 3T3 fibroblasts, and showed
that grim induces death in these cells.
Because the assay is not performed in Drosophila cells,
is it ok to annotate to 'apoptosis ; GO:0006915' and
its children?

2. Cellular component Assays in Non-Drosophila Cells:

In FBrf0105796 (PMID:9857177), the authors go on to
examine the subcellular localization of Grim in the
mammalian fibroblasts. They find the Grim protein in
the cytoplasm and the mitochondria. Because the cells
are not Drosophila cells, is this assay adequate to
assign cytoplasm ; GO:0005737 and mitochondrion ;
GO:0005739 component terms?

Similarly, in FBrf0087337 (PMID:8524796) in an antibody
cellular localization assay, the authors show that
Drosophila Tra and Tra2 are found in speckles in
mammalian cells.

3. For immuno-localization experiments, when a
GFP-fusion protein is made, is this an adequate assay
to assign GO cellular component information, since it
is not always known whether the GFP tag affects the
subcellular localization of the gene product?

Eg in FBrf0132409 (PMID:11158320) and FBrf0167463
(PMID:14651932)

4. What evidence code do MODs use when curating
conference abstracts?

Do other MODs use just NAS for curating abstracts, or
is using IMP, ISS, IGI, IPI etc ok even though the
primary data is not shown.

E.g:
http://fbserver.gen.cam.ac.uk:7081/.bin/fbidq.html?FBrf0145796&resultlist=fbrf21903.data
Loss-of-function studies of amnesiac indicate that the
encoded peptide participates in the innate immune
response. Because the mutant data itself is not
presented, can the evidence code IMP be used?

http://fbserver.gen.cam.ac.uk:7081/.bin/fbidq.html?FBrf0133865&resultlist=fbrf22533.data
Similarly, mutations in Unc-76, disrupt axon cargo
transport. Though the primary data is not presented in
an abstract, can IMP be used?

The authors of this abstract also say that Unc-76 binds
kinesin in pull-down assays. Can we annotate to
'kinesin binding ; GO:0019894 | IDA' ?

http://fbserver.gen.cam.ac.uk:7081/.bin/fbidq.html?FBrf0106385&resultlist=fbrf22754.data
*E FBrf0106385 == hb000218.e == Danos et al., 1999, A.
Dros. Res. Conf. 40: 362A

The authors say 'The protein is similar to vertebrate
TAK1s throughout, with a well conserved kinase domain
showing 56% identity and 73% similarity in amino acid
sequence to the mouse TAK1. Can we annotate to 'MAP
kinase kinase kinase activity ; GO:0004709 ; EC:2.7.1.-
| ISS' ?

5. Do other MODs differentiate between the
function/process/location of an RNA and that of a
protein gene product?

For example, in flies a number of mRNAs are localized
during oogenesis (eg oskar and nanos mRNAs are
localized to the pole plasm). In our GO annotations we
have cellular component information relating to the
mRNA, and process information relating to the protein.
All are just attributed to the gene at the moment.

6. Similar to one of the WB issues: how to annotate
proteins that are on the surface of/associated-with a
cellular component.

In  FBrf0110050 (PMID:10466937), mt:srRNA RNA iis
found"enriched on the *surface* of polar granules".
Does this count as being localized to a 'polar granule
; GO:0018994'?

7. How do other MODs deal with conflicting GO data from
different sources?

Eg in FBrf0109981 (PMID:10385622) the authors claim
Acf1 gene product did not purify with components of
CHRAC. In FBrf0138380 (PMID11447119), the authors claim
that Acf1 is a component of CHRAC.

And the following 2 papers disagree on whether MBD-like
has methyl-CpG binding function or not: FBrf0130046
(PMID:10982856) and FBrf0123223 (10581020).

I'll forward pdfs of the references here to Midori/Mike
as requested.

Thanks,
Becky

Reported by: beckyfoulger

Original Ticket: "geneontology/annotation-issues/14":https://sourceforge.net/p/geneontology/annotation-issues/14

**Comment by linuxlovell** [comment]
thanks www.movied.org
