### ISSUE TITLE
PAINT annotation TRX1/2/3 (SGD) (via Matrix)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1400]
These all have "protein folding" annotation via IBA.

I'm not sure that this is valid for these thioredoxins.  Which orthologs is it derived from? Could you take a look?

Thanks

Val

**Comment by pgaudet** [comment]
Hi Val, 

You can see the information here: 
http://pantree.org/node/annotationNode.jsp?id=PTN000047070
There seem to be quite a bit of support. 
EcoGene(EcoGene:EG13261), TAIR:locus:2200141, TAIR:locus:2064854, TAIR:locus:2159971, WB:WBGene00015062, MGI:MGI:2389312, FB:FBgn0029752

Do you think the primary annotations may be wrong ? 

PTHR10438 -

**Comment by ValWood** [comment]
I thought it was a co-chaperone for a chaperone of 'misfolded proteins' (which are degraded). I did't think it has a role in directly in folding or refolding. I notice people often use 'protein folding' for the misfolded  protein-> degradation  pathways which doesn't seem to be correct unless they are refolded.

I'll double check though, I could be wrong. I'll begin by asking SGD why TRX1 isn't annotated to protein folding and work from there.

VAl

**Comment by ValWood** [comment]
One role is to maintain proteins in a reduced state for import into mitochondria (and possibly ER?). This seems to precede folding, which occurs after import.

protein folding
The process of assisting in the covalent and noncovalent assembly of single chain polypeptides or multisubunit complexes into the correct tertiary structure.

I guess it depends where folding begins and ends.

**Comment by ValWood** [comment]
I'm probably being a bit dim here. Maybe any thioredoxin which maintains a protein in an unfolded state for any reason has a role in  protein folding? I'm asking a  pombe tpx1 expert.....

**Comment by vanaukenk** [comment]
Hi @ValWood,

I was just trying to trace the source of the C. elegans annotations and it looks like it might have come from an MF-BP link?

I can't find the link anymore, though, and am not sure of the best way to trace the history.

**Comment by ValWood** [comment]
What MF do you have?

I have
protein disulfide oxidoreductase activity
but this never had a link to protein folding
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0015035#term=history

**Comment by vanaukenk** [comment]
Ah, I just checked QuickGO.
We also have an MF to protein disulfide isomerase activity for which the MF-BP link to protein folding appears to have been deleted on 2016-05-01.
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003756#term=history

**Comment by vanaukenk** [comment]
But...in looking at the paper again, I think the original annotation to protein disulfide isomerase activity is a mistake, so I'm going to remove that annotation.

Thx.
--K.

**Comment by ValWood** [comment]
Now we are getting there.......
https://github.com/geneontology/go-ontology/issues/12385

So Pascale,  if all of the annotations are via the old F-P link to  'protein folding' this will disappear?

If not let me know and I'll follow up.

**Comment by ValWood** [comment]
.>So Pascale, if all of the annotations are via the old F-P link to 'protein folding' this will disappear?

I just realised that's unlikely if WB annotation was incorrect...

**Comment by ValWood** [comment]
My source
"no point to say that Trx1 is involved in protein folding"
(this is on pombe)
https://www.upf.edu/osccg/leaders/hidalgo.html

**Comment by ValWood** [comment]
Rob says this about S. cereviisae TRX1/2
I agree that a protein aggregation phenotype is not enough for a protein folding annotation....
Val

Hi,

From this classical paper (Jang et al., 2004 PMID: 15163410), if was demonstrate that both TSA1 (cTPxI) and TSA2 (cTPxII) have chaperone activity via a direct assay. This is based on a structural shift from a form that acts as a peroxidase to one that acts as a chaperone, where the structural transition is mediated by oxidative stress or heat shock. I have added annotations to both TSA1 and 2 in protein2go, using IDA and added part_of: cellular response to heat. Also was able to add the same annotation for TSA1 using part of: cellular response to oxidative stress. I believe this was one of the first demonstrations of this in yeast. Also added an annotation to unfold proteins binding for TSA1 with IDA and part of: cellular response to heat, as this is considered as part of how this occurs, by binding to the denatured substrate. In this paper they also show that TSA1 provides cells with some heat shock resistance.

However, other than increased levels of aggregated ribosomal proteins observed in trx1 trx2 null mutants and trr1 nulls in Rand and Grant 1006 (PMID: 16251355) I cannot yet find direct evidence that its annotatable to protein folding. I am just not sure this evidence is enough, so I will leave this one for now.

Cheers,
Rob

**Comment by ValWood** [comment]
Hi Pascale,

I'll close this one. I don't think there is evidence that this has a role in protein folding for yeast. I don't feel confident that is wrong, it could be just an absence of information.  It is unlikely we know all of the roles of this protein (although the studies in pombe and cerevisiae don't indicate any protein floding role, as you say there is good evidence).

Val
