### ISSUE TITLE
FP mapping to "sister chromatid cohesion" for SMC subunit  IPR027131

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1401]
is SMC-complexsubunit, not cohesin
http://www.pombase.org/spombe/related/GO:0030915
(the complexes are related)

**Comment by ValWood** [comment]
O13710/ smc5/ SPAC14C4.02c has this in our next update

**Comment by asangrador** [comment]
Hi Val,
I will remove the term 'sister chromatid cohesion', as this role is questionable. However, there are  references that indicate that SMC5 is involved in sister chromatid cohesion in humans (PMID: 19502785, 'SMC5 and MMS21 are required for chromosome cohesion and mitotic progression' ) and plants (PMID:19737979, ' the SMC5/6 complex promotes sister chromatid cohesion after DNA breakage and facilitates homologous recombination between sister chromatids'). Furthermore, as mentioned in PMID: 25329383,  'Smc5/6 possibly contributes to some of the many functions assigned to cohesin. However, while cohesin impairment leads to cohesion loss, inhibition of Smc5/6 only creates minor cohesion defects'. So it is very possible that this complex has a role in chromosome cohesion after all, but I'll remove the term to be on the safe side.

**Comment by ValWood** [comment]
For PMID: 19502785 the phenotype "premature sister chromatid separation prior to anaphase" could also be caused by, for example, not being able to maintain the spindle assembly checkpoint appropriately, rather than faulty cohesion....(this would also explain the single subunit effect). There are probably other explanations too.

PMID:19737979 seems to be describing an 'upstream' problem which affects cohesion rather than direct involvement.

 They're very speculative conclusions.  I don't think these are strong enough for a mapping data. 

Again, the words 'suggest' and 'possibly' leap out. Always a red flag...

**Comment by ValWood** [comment]
There are quite a few papers for SMC5 /cohesion, so this one is probably OK, sorry!
