### ISSUE TITLE
IPR001831 (Tat protein) GO mappings

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-annotation#1403]
The InterPro mappings for IPR001831 (viral Tat protein) could be updated:
https://www.ebi.ac.uk/interpro/entry/IPR001831

The text suggests it's an RNA-binding transcription factor (GO:0001070), and the following process could added: positive regulation of viral transcription ; GO:0050434

Thanks!
Becky

**Comment by asangrador** [comment]
I have removed the previous terms we had and added the ones you suggested that certainly are much better. Thanks,
Amaia
