### ISSUE TITLE
Addressing curation effort redundancy

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1404]
This has been tranferred from the GO Help desk tracker GO-1131.
See http://jira.geneontology.org/browse/GO-1131 for rest of thread.

Help mail submitted by @ValWood 

"We need to take steps to ensure we are not duplicating effort.
Historically sometimes PomBase and UniProt would curate the same papers. This doesn't happen anymore because a) we can see all existing annotation in our curation tool and b) UniProt tend not to annotate pombe papers for GO, since we need to do them anyway for other datatypes.
However, now Intact are curating and exporting interactions. This seems to happen whether we have already go curated these interactions or not and results in duplicated annotation From the same paper
I'm illustrating this with a screenshot which shows that skp1 has each interaction curated 2 time.

In this case first by UniProt
Then by PomBase (predating our ability to see existing interactions), and now very recently by Intact.

We need to move towards a single annotation from a single source.

Soon, we will begin to filter redundant annotations before we submit the PomBase data to GO, so this will be an additional difference between GO and GOA.

<img width="1105" alt="dulication" src="https://cloud.githubusercontent.com/assets/11865746/15819879/afafa104-2bdd-11e6-96b6-dce3b9e5b358.png">

To be discussed at a future GO-wide call?

**Comment by pgaudet** [comment]
@tonysawfordebi Is it possible for you to find out how many papers are annotated by more than one source ? (ie a % -wise) 

@ValWood do you know the fraction of papers this affects for Pombase ? 

If this doesn't happen very much we probably don't need to take any action about this. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think it is very low,but mainly because intact have not done so many pombe papers. 

We can manage this internally by filtering duplicate annotation but it seems that there should be coordination to reduce redundancy in the longer term, because it will presumably happen more and more...

**Comment by pfey03** [comment]
I brought this up a while back with someone at a meeting (forgot who) who told me that it's good if interaction annotations are in IntAct. But in our new database I will also check how many are redundant there are and if it's worth filtering.

**Comment by ValWood** [comment]
Maybe this is one for  MODS to handle locally depending how fussy they are....can close...

**Comment by pgaudet** [comment]
Action point would be to develop a separate tool to track: 

- [ ] annotated papers
- [ ] partially annotated papers
- [ ] rejected papers
