### ISSUE TITLE
GO terms for PTN000558065 too specific (PTHR23091 PTHR10 / PTHR42191 PTHR11)

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#1406]
The E. coli PhnO protein, P16691, has inherited three GO annotations related to protein/peptide acetyltransfer via PTN000558065.  The protein is actually an aminoalkylphosphonate N-acetyltransferase and not a peptide/protein acetyltransferase (see PMID 23056305).  So the acetyltransferase part is correct, but the more specific terms are not.

Cheers,
Ingrid

**Comment by pgaudet** [comment]
PTHR42919 - not in the Google spreadsheet for PAINT tracking: https://docs.google.com/spreadsheets/d/1uHgcaXO7t9__9GuXgBibT0H-YlnU252IsRGWIyhCWN8/edit, PAINT cannot find it.

**Comment by pgaudet** [comment]
Hello, 
In Panther11 phnO is removed from  PTHR23091 and moved to PTHR42191, so all annotations have been removed. Marc and I have annotated PTHR42191. 

Thanks, Pascale
