### ISSUE TITLE
ECO for siRNA expt?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-annotation#1407]
We have experimental evidence for the MF of a gene product from siRNA treatment. Which ECO are you using for this now? It's not really direct and it's not a mutant phenotype as the construct or native genome is not altered. 

We use it for the GO annotations on complexes (in which case the MF of the complex disappears after siRNA treatment).

@rebeccafoulger ?

Thanks,
Birgit & Mila

**Comment by ValWood** [comment]
Hi Birgit,

Historically we use IMP for  knockdowns and phenotypes  based on alterations to expression level
http://geneontology.org/page/imp-inferred-mutant-phenotype

any procedure that disturbs the expression or function of the gene, including RNAi, anti-sense RNAs, antibody depletion, or the use of any molecule or experimental condition that may disturb or affect the normal functioning of the gene, including: inhibitors, blockers, modifiers, any type of antagonists, temperature jumps, changes in pH or ionic strength.

(I don't know if there is a more specific ECO code)

Val

**Comment by mah11** [comment]
I agree that this is a phenotype because the effective expression level of the gene product is altered.

Would siRNA fit ECO:0000019?

[Term]
id: ECO:0000019
name: RNAi evidence
def: "Inference based on a phenotype observed when expressing an RNAi construct that includes a fragment of the gene product in a wild-type (for that gene product) background. A double-stranded RNA specifically suppresses the expression of the gene bearing its complementary sequence." [TAIR:TED]
synonym: "IMP: RNAi experiment" RELATED []
is_a: ECO:0000059 ! experimental phenotypic evidence

**Comment by bmeldal** [comment]
Thanks. We can use any ECO codes so happy to go with ECO:0000019 or carry on using IMP [ECO:0000015], they are siblings... 

I need some sort of consensus on what others are using, please :)

**Comment by mah11** [comment]
Well, at PomBase we would use IMP right now because we haven't switched to using ECO IDs for GO annotations yet. If we were up-and-running with ECO I would use ECO:0000019 (yep, we'll have lots to upgrade but I suppose it'll happen incrementally).

**Comment by ValWood** [comment]
Why isn't  ECO:0000019 a descendant of ECO:0000015, if it is defined "Inference based on a phenotype ....."
?

**Comment by bmeldal** [comment]
Good question, Val...

**Comment by rachhuntley** [comment]
We also use IMP at the moment for silenced genes, as we can't use ECO codes yet.
I'm wondering whether there should be a distinction between naturally occurring RNAi and artificial RNAi? You can make any RNAi construct to silence a gene, but there are also naturally occurring siRNA/miRNA/piRNA etc. What if the authors are studying these? Would you want to distinguish between them?
It looks like the term RNAi has been used for both artificial and naturally occurring silencing. 
Just to note, the IMP/ECO:19 code would be used for annotating the entity that is silenced, if you were to annotate the function of the miRNA/siRNA the evidence would be IDA.

**Comment by bmeldal** [comment]
Thanks, Rachel.

The entity we are annotating is the complex where one subunit has been silenced and that leads to a impairment of the normal function. 

So with regards of being consistent I guess we should use IMP as otherwise filters would not result in consistent results.

Thanks everyone for you help!

**Comment by bmeldal** [comment]
I don't know how to close this ticket :(

**Comment by pgaudet** [comment]
I have added the Documentation label. We'll make sure this goes in the new version of the evidence documentation. 

Thanks, Pascale

**Comment by ValWood** [comment]
Is this still relevant and in the evidence code docs?
Can probably close?
