### ISSUE TITLE
IEA with UniProtKB-KW:KW-0812

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1408]
S. pombe mak2 and mak3 are annotated to
GO:0016021integral component of membrane
IEA with UniProtKB-KW:KW-0812

This looks odd as I don't think they have TM domains? 

I have sent an email to help@uniprot.org also

**Comment by pedruzzi** [comment]
I agree with you. Seems to be some (very old) TMHMM predictions in Swiss-Prot. I have them removed now. Will be visible in UniProtKB public release 2016_09.
thanks

**Comment by Antonialock** [comment]
Super, thanks Ivo!
