### ISSUE TITLE
PTHR18945 [Protein2GO] Notification of annotation dispute concerning protein G5EG88  (Dispute ID: 4593)

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-annotation#1409]
Dear @pgaudet, this comes from JIRA at http://jira.geneontology.org/browse/GO-1265
# 

A dispute has been raised over a GO annotation coming from your group. The details are given below. If you agree with the dispute, please amend or delete the annotation accordingly. If, however, you disagree or need to respond to the disputer, you may contact the disputing curator by replying to this email.

```
SOURCE ENTITY TYPE  ENTITY ID   GO ID   EVIDENCE    ECO ID  REFERENCE   WITH    EXTENSION
REFG    protein G5EG88  GO:0004889  IBA ECO:0000318 GO_REF:0000033  PANTHER:PTN001450552    
```

**Dispute ID:** 4593
**Nature of dispute:** This dispute concerns the GO term used
**Details:** Hi, There is a paper from 2013 that characterized the activity of ACR-23 and shows that it is specifically activated by glycine betaine and not be acetylcholine.  Please see: http://www.ncbi.nlm.nih.gov/pubmed/24212673  

**The relevant text is:**

> To  test  whether  betaine  acts  directly  on  the  ACR-23  receptor,  we  expressed  ACR-23  in Xenopus oocytes  and  examined  its  response to various ligands. ACR-23 forms an ion channel that is activated by betaine, but not by acetylcholine, choline, glycine, or GABA (Fig. 4a).  

I've just requested the appropriate new MF term, but in the meantime, could all of the acetylcholine-related annotations for ACR-23 be removed?  
Many thanks, --Kimberly
Sent by Protein2GO on behalf of Kimberly Van Auken

**Comment by pgaudet** [comment]
NOTE: concerns  	PTHR18945 - 1500 members. Postpone fix.

**Comment by thomaspd** [comment]
acetylcholine receptor activity annotation has been removed.  As of now, betaine receptor activity is not a GO term, so we can't add this function.
