### ISSUE TITLE
mapping EC 1.4.1.13	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1412]
According to 
    PMID:7773104
pombe glt1  Q9C102 is GOGAT: EC 1.4.1.14--gluta- mine-oxoglutarate aminotransferase

This is in agreement with  SGD GLT1 http://www.yeastgenome.org/locus/S000002330/overview#go

Thanks

val

**Comment by ValWood** [comment]
Probably not enough info here.

Currently it has EC 1.4.1.13 EC to GO mapping

**Comment by pgaudet** [comment]
Who does the EC2GO mappings ?

**Comment by ValWood** [comment]
I  think @hdrabkin knows...

**Comment by hdrabkin** [comment]
Know I do not know for sure
I believe it gets gernated  now from the ontology file (which is why we had to get rid of the EC:x.x.x.- as xrefs as it was generating but annotations. 
Maybe check with @cmungall ?

**Comment by ValWood** [comment]
So did we find out who does the EC mappings?

**Comment by cmungall** [comment]
> So did we find out who does the EC mappings?

The GOC currently maintains mappings between GO terms and EC. Once we have finished mapping to Rhea we can obtain EC mappings for leaf activities from Rhea.

Assignment of proteins to EC IDs was done by SwissProt, though they are switching to Rhea.

Hopefully this is all clear to everyone now, though we still need to do a better job of explaining mappings to our users!

**Comment by cmungall** [comment]
Is there anything to be done for this specific ticket? 

Is this one of these cases where we have two distinct reactions that we want to deliberately conflate?

Current ontology

NAD(P)H PARENT:

id: GO:0045181
name: glutamate synthase activity, NAD(P)H as acceptor
namespace: molecular_function
def: "Catalysis of the reaction: 2 L-glutamate + NAD(P)+ = L-glutamine + 2-oxoglutarate + NAD(P)H + H+." [EC:1.4.1.13, EC:1.4.1.14]
synonym: "glutamate synthase activity, NADH or NADPH as acceptor" RELATED []
is_a: GO:0015930 ! glutamate synthase activity
is_a: GO:0016639 ! oxidoreductase activity, acting on the CH-NH2 group of donors, NAD or NADP as acceptor

TWO CHILD TERMS:

id: GO:0004355
name: glutamate synthase (NADPH) activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 L-glutamate + NADP(+) = 2-oxoglutarate + L-glutamine + H(+) + NADPH. This is a two-step reaction: (a) L-glutamate + NH3 = L-glutamine + H2O, (b) L-glutamate + NADP+ + H2O = NH3 + 2-oxoglutarate + NADPH + H+." [EC:1.4.1.13, RHEA:15501]
comment: Note that this term has a MetaCyc pathway reference as the pathway only has a single step.
synonym: "glutamate (reduced nicotinamide adenine dinucleotide phosphate) synthase activity" RELATED [EC:1.4.1.13]
synonym: "glutamate synthetase (NADP) activity" RELATED [EC:1.4.1.13]
synonym: "glutamine amide-2-oxoglutarate aminotransferase (oxidoreductase, NADP) activity" RELATED [EC:1.4.1.13]
synonym: "glutamine-ketoglutaric aminotransferase activity" RELATED [EC:1.4.1.13]
synonym: "GOGAT activity" BROAD [EC:1.4.1.13]
synonym: "L-glutamate synthase activity" BROAD [EC:1.4.1.13]
synonym: "L-glutamate synthetase activity" BROAD [EC:1.4.1.13]
synonym: "L-glutamate:NADP+ oxidoreductase (transaminating)" RELATED [EC:1.4.1.13]
synonym: "L-glutamine:2-oxoglutarate aminotransferase, NADPH oxidizing activity" RELATED [EC:1.4.1.13]
synonym: "NADPH GOGAT" EXACT []
synonym: "NADPH-dependent glutamate synthase activity" RELATED [EC:1.4.1.13]
synonym: "NADPH-glutamate synthase activity" RELATED [EC:1.4.1.13]
synonym: "NADPH-linked glutamate synthase" RELATED [EC:1.4.1.13]
xref: EC:1.4.1.13
xref: KEGG_REACTION:R00114
xref: MetaCyc:GLUGLNSYN-PWY
xref: MetaCyc:GLUTAMATESYN-RXN
xref: MetaCyc:GLUTSYN-PWY
xref: RHEA:15501
is_a: GO:0045181 ! glutamate synthase activity, NAD(P)H as acceptor

id: GO:0016040
name: glutamate synthase (NADH) activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 L-glutamate + NAD(+) = 2-oxoglutarate + L-glutamine + H(+) + NADH." [EC:1.4.1.14, RHEA:13753]
synonym: "glutamate (reduced nicotinamide adenine dinucleotide) synthase" RELATED [EC:1.4.1.14]
synonym: "GOGAT activity" BROAD []
synonym: "L-glutamate synthase (NADH)" RELATED [EC:1.4.1.14]
synonym: "L-glutamate synthase activity" BROAD [EC:1.4.1.14]
synonym: "L-glutamate synthetase activity" BROAD [EC:1.4.1.14]
synonym: "L-glutamate:NAD+ oxidoreductase (transaminating)" RELATED [EC:1.4.1.14]
synonym: "NADH-dependent glutamate synthase activity" RELATED [EC:1.4.1.14]
synonym: "NADH-glutamate synthase activity" RELATED [EC:1.4.1.14]
synonym: "NADH: GOGAT" RELATED [EC:1.4.1.14]
xref: EC:1.4.1.14
xref: KEGG_REACTION:R00093
xref: MetaCyc:GLUTAMATE-SYNTHASE-NADH-RXN
xref: RHEA:13753
is_a: GO:0045181 ! glutamate synthase activity, NAD(P)H as acceptor

**Comment by ValWood** [comment]
I think this is OK now. My issue was that pombe was picking up GO:0004355 mapping, but this is no longer the case. The only annotation to this term now in GOC are bacterial, so this can probably close.

I'll request a taxon restriction for GO:0004355 'never in yeast' as this seems to be a safe assumption based on current knowledge.

for the question
>Hopefully this is all clear to everyone now, though we still need to do a better job of explaining mappings to our users!

We know GOC maintains the EC2GO mappings, my question is more specifically which *individual* should I assign EC2GP mapping tickets to? These get left because they don't get assigned to a person. Nobody seems to know which person does them (or even where  they are kept ?)

**Comment by pgaudet** [comment]
> We know GOC maintains the EC2GO mappings, my question is more specifically which individual should I assign EC2GP mapping tickets to? These get left because they don't get assigned to a person. Nobody seems to know which person does them (or even where they are kept ?)


Hi @ValWood The EC2GO is maintained by GO editors. 
Any term with a xref to an EC term is exported to the EC2GO file here: http://current.geneontology.org/ontology/external2go/index.html

GOA (and other groups ?) take this file and apply the GO terms to any entry with the appropriate EC mapping. @alexsign please correct me if this is not accurate. 

Corrections to EC mappings should be created in the go-ontology tracker. 

Thanks, Pascale

**Comment by ValWood** [comment]
AH right. I have always put them on the annotation tracker. I will check later and  flag any others for migration.

**Comment by hdrabkin** [comment]
If something wrong with EC mappings I usually handle it. As Pascale says, the ec2go file gets generated by GO based on the xrefs in the ontology.

**Comment by ValWood** [comment]
OK this one can close anyway as out of date by the obsoletion

**Comment by cmungall** [comment]
Hold on

@ValWood asks

> We know GOC maintains the EC2GO mappings, my question is more specifically which individual should I assign EC2GP

I don't know the individual, but if there is a question about an EC2**GP** mapping, this is not a go-ontology issue. It is an annotation of a GP to an EC. The go-annotation tracker is most appropriate

If there is an EC2**GO** question this is go-ontology and Harold typically answers

(we should set up issue templates and have the relevant person auto-assigned)

**Comment by hdrabkin** [comment]
I see Chris's point because it could be an issue with the assignment of the EC to the gene product (we take ours (MGI) from whatever UniProt has it the UniProt entry record.

**Comment by pgaudet** [comment]
@marcfeuermann Can you edit the SP entry for  Q9C102 from  EC 1.4.1.13 to  EC 1.4.1.14? 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
Hello,
I've updated the UniProt entry  for Q9C102, adding data from PMID:7773104 and changing EC 1.4.1.13 to EC 1.4.1.14. 
Best regards,
Marc.
