### ISSUE TITLE
UniProtKB-KW:KW-0254 endocytosis mappings

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1414]
imt1 SPAC2F3.01	O14084
imt2 SPCC4F11.04c Q9UT67
imt3 SPAC17G8.11c Q10323

are annotated via KW mapping to endocytosis. I can't see any evidence for this?
They appear to be Golgi/ER proteins involved in
	mannosyl-inositol phosphorylceramide biosynthetic process

**Comment by pedruzzi** [comment]
You are correct. imt mutants have an endocytosis defect, but it is an indirect, pleiotropic effect of the loss of the phosphorylceramide, and not an involvement of the enzyme in the process.

I removed the KW from the 3 entries

**Comment by ValWood** [comment]
thanks!
