### ISSUE TITLE
GO_REF for ISO (GOA syntax checks)

### ISSUE THREAD

**Issue by mah11** [geneontology/go-annotation#1417]
The July 2016 syntax check file we have from GOA has flagged many of our ISO annotations as using an inappropriate reference, GO_REF:0000024. Reading the the title and description, though, GO_REF:0000024 seems like it should be allowed for ISO (the text could be updated to recommend ISO instead of ISS).

Could someone please clarify -- should the syntax check be adjusted? If not, what should we use for our ISOs instead? Thanks!

http://www.geneontology.org/cgi-bin/references.cgi#GO_REF:0000024

**Comment by pgaudet** [comment]
@mah11 Is this still a problem ?

**Comment by mah11** [comment]
Probably fixed - at least, the last two sets of syntax checks haven't flagged ISO/GO_REF:0000024 any more.
