### ISSUE TITLE
allowable references for IC (GOA syntax checks)

### ISSUE THREAD

**Issue by mah11** [geneontology/go-annotation#1418]
The July 2016 syntax check file from GOA has flagged many of our IC annotations as using various inappropriate references. The documentation for IC suggests that two of them, GO_REF:0000024 and GO_REF:0000050, should actually be allowed, because they are cited for the annotations from which the ICs were made. Ideally the check should be adjusted; otherwise, we will have to ignore these warnings.

http://geneontology.org/page/ic-inferred-curator

**Comment by pgaudet** [comment]
@mah11 Is this still a problem ?

**Comment by mah11** [comment]
I think it has been addressed by the introduction of GO_REF:0000111 (although there's still room for snark about how poorly its addition was communicated to annotators).
