### ISSUE TITLE
ND code should only be used for root terms

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1419]
noticed by @selewis 

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=evidence_type_closure:%22no%20biological%20data%20found%22&fq=-annotation_class_label:%22molecular_function%22&fq=-annotation_class_label:%22biological_process%22&fq=-annotation_class_label:%22cellular_component%22&sfq=document_category:%22annotation%22

6 violations

<img width="1352" alt="screen shot 2016-07-18 at 11 13 40 am" src="https://cloud.githubusercontent.com/assets/50745/16925371/bceddba8-4cd8-11e6-8461-49f3d4e08fe2.png">

**Comment by pgaudet** [comment]
@dougli1sqrd Is this implemented ?

**Comment by ValWood** [comment]
@pgaudet  is this in the rules yet?
There are non right now...

**Comment by ValWood** [comment]
Who deals with annotation rules? Assigning to Seth for now to assign to the correct person.

**Comment by kltm** [comment]
@ValWood , currently, trying to get the "easy" GORULES implemented is a project with @pgaudet . I'm not sure if this falls into that category or not, but @pgaudet look at this with Anushya and make a determination.

**Comment by pgaudet** [comment]
implemented https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000011.md
