### ISSUE TITLE
InterPro mapping to "regulation of cell migration" for fission yeast 	IPR016555

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1421]
http://www.pombase.org/spombe/result/SPAC2F7.16c (	Q09706)

Can this one be removed?
I'll ask for a taxon restriction for this term.

Thanks

Val

**Comment by ValWood** [comment]
also 
"regulation of phagocytosis" same  ID

**Comment by almitchell** [comment]
Deleted in April this year, and so should have been removed from InterPro release 58.0 (Junes 2016) onwards. It may be that the updated annotations are taking time to percolate through the various pipelines.

**Comment by ValWood** [comment]
ah we haven't had a  PomBase update for a while either.... I should check the  current InterPRO first at the moment.
