### ISSUE TITLE
uniprot KW-0342	

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1422]
Pombe SPCC1620.08 has this mapping
GO:0005525  GTP binding IEA UniProtKB-KW:KW-0342    GO_REF:0000037

however, it looks like this might be incorrect based on PMID:9874242 
(cerevisiae paper) where the abstract states
The yeast succinyl-CoA ligase was shown to utilize ATP but not GTP for succinyl-CoA synthesis.

so this mapping should probably be removed?

**Comment by Antonialock** [comment]
I also emailed help@uniprot.org

**Comment by pedruzzi** [comment]
working on it...

I agree with you that this enzyme most probably uses ATP for succinyl-CoA synthesis. I have to review the entire protein family though, as it has been shown that some enzymes are specific for the one or the other nucleotide (mostly in vertebrates that have 2 copies), while others can use both (some bacteria), and it is as of yet not entirely clear as to what residues/structure confer nucleotide specificity.

I'll post when done

**Comment by Antonialock** [comment]
cheers Ivo :-)

**Comment by ValWood** [comment]
You could cheat and move the mapping up to NTP binding :)
Val

**Comment by pedruzzi** [comment]
Finally finished the fix for the entire family, e.g. for S.pombe, GTP-binding will be replaced by ATP-binding for UniProt release 2016_11
best
-ivo
