### ISSUE TITLE
GO_REF:0000003 evidence + succinate-CoA ligase (GDP-forming) activity	

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1423]
Pombe SPCC1620.08 is annotated to 
GO:0004776  succinate-CoA ligase (GDP-forming) activity IEA EC:6.2.1.4

but it appears that this might be incorrect based on this cerevisiae paper:
PMID:9874242 
"The yeast succinyl-CoA ligase was shown to utilize ATP but not GTP for succinyl-CoA synthesis."

**Comment by ValWood** [comment]
@Antonialock  did you send this one?

**Comment by Antonialock** [comment]
Probably? How can I check that?

**Comment by Antonialock** [comment]
I would assume I emailed them because I did for #1422 which I submitted at the same time.

**Comment by pedruzzi** [comment]
working on an update to the entire protein family in UniProt, yes. This will fix both issues. I'll comment when done
cheers
-ivo

**Comment by pgaudet** [comment]
Hi @pedruzzi 

Any update on this one ? 


Thanks, Pascale

**Comment by pedruzzi** [comment]
This has been fixed together with #1422 , yes. Just forgot to report here as well.
