### ISSUE TITLE
New deglycation GO mappings for IPR006287

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-annotation#1425]
I've created some new GO terms (see https://github.com/geneontology/go-ontology/issues/12550) that can be used to update the GO:InterPro mappings for:

Family: Protein deglycase DJ-1 (IPR006287)
https://www.ebi.ac.uk/interpro/entry/IPR006287

Including:
protein degylcase activity ; GO:0036524
protein deglycation ; GO:0036525

These new terms are children of 'protein repair' so can replace the existing GO terms assigned to IPR006287.

Thanks, and please let me know if you have any questions.

**Comment by asangrador** [comment]
Thanks Rebecca,

We will add those terms as soon as they are available to us (at the 
moment our curation tool does not recognize them).


Amaia

**Comment by asangrador** [comment]
Terms have been added now.
Cheers,

Amaia
