### ISSUE TITLE
	C6Y4C8 not GO:0030127 COPII vesicle coat (IEA from HAMAP:MF_03058)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1428]
This is "vacuolar H+-ATPase assembly protein" I don't think  it should have vesicle coat annotation?

vma21 GO:0030127 COPII vesicle coat IEA HAMAP:MF_03058 GO_REF:0000020

GO:0030127
Definition	One of two multimeric complexes that forms a membrane vesicle coat. COPII is best characterized in S. cerevisiae, where the subunits are called Sar1p, Sec13p, Sec31p, Sec23p, and Sec24p. Vesicles with COPII coats are found associated with endoplasmic reticulum (ER) membranes at steady state. 
PMID:11252894

**Comment by pedruzzi** [comment]
Vma21 is an essential assembly chaperone of the vacuolar ATPase (V-ATPase), which is organized into a transmembrane (V0) and a cytoplasmic (V1) sector. V0 assembly occurs in the endoplasmic reticulum (ER), coordinated by the Vma21 chaperone. Once V0 is formed, Vma21 accompanies it on COPII vesicles to the Golgi apparatus, where V1 subunits are added to complete the V-ATPase. This has been shown in yeast (PubMed:15356264) and has been confirmed in human (PubMed:23315026).
So Vma21 is found in COPII-coated vesicles embedded in their membrane, which prompted us to annotate the subcellular location of this protein to COPII-coated vesicles.
I have now changed the GO term in HAMAP-rule MF_03058 to GO:0012507; ER to Golgi transport vesicle membrane, which is the "official" subcell2GO mapping for this UniProt subcellular location.
According to the definition, GO:0030127 should only be used for the proteins building up the coat, you are right.

**Comment by ValWood** [comment]
Sounds good
