### ISSUE TITLE
PTHR11920 [Protein2GO] Notification of annotation dispute concerning protein P20594 (Dispute ID: 4533)

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-annotation#1429]
NOTE: Concerns PTHR11920

Dear @pgaudet, this comes from JIRA at http://jira.geneontology.org/browse/GO-1255
If this issue has already been addressed, please update and close.
# 

17/Jun/16 7:44 AM

A dispute has been raised over a GO annotation coming from your group. The details are given below. If you agree with the dispute, please amend or delete the annotation accordingly. If, however, you disagree or need to respond to the disputer, you may contact the disputing curator by replying to this email.

```
SOURCE  ENTITY TYPE ENTITY ID   GO ID   EVIDENCE    ECO ID  REFERENCE   WITH    EXTENSION
REFG    protein P20594  GO:0008074  IBA ECO:0000318 GO_REF:0000033  PANTHER:PTN000229249    
```

**Dispute ID:** 4533
**Nature of dispute:** This dispute concerns the GO term used
**Details:** I do not understand this annotation for a transmembrane receptor.

Sent by Protein2GO on behalf of Lionel Breuza

**Comment by pgaudet** [comment]
The is a 900-member family, cannot be loaded in PAINT right now, will revisit when we can load big families. 

- Pascale

**Comment by selewis** [comment]
Would people Please provide the name of the family in these requests. It's cumbersome to keep grepping to find the family that needs to be reviewed. (It's PTHR11920 btw)

In any case, the annotation is no longer present, nor are any experimental annotations found to transmembrane receptor. The one IBA annotation for this human protein is to quanylate cyclase complex, soluble (GO:00080741)

**Comment by thomaspd** [comment]
This annotation no longer appears in AmiGO, so this issue is resolved
