### ISSUE TITLE
Interpro mapping IPR004640, protein folding

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1436]
Pombe Jac1 has an IEA IPR004640 GO_REF:0000002

I think this should be removed, I think jac1 is upstream of incorporation of the iron-sulfur cluster into apo proteins
eg 
https://www.ncbi.nlm.nih.gov/pubmed/26545917

or it is the hsc20 ortholog in this diagram
![screen shot 2016-09-02 at 16 48 39](https://cloud.githubusercontent.com/assets/12727506/18209779/26ba2320-712d-11e6-854b-1ac31b94cc2f.png)

**Comment by asangrador** [comment]
The mapping to 'protein folding' from IPR004640 has been removed, and 'protein maturation by iron-sulfur cluster transfer' has been added instead.

**Comment by Antonialock** [comment]
super thank you
