### ISSUE TITLE
	SL-0081 to Cvt vesicle membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1437]
Pombe doesn't have CVT pathway.
I'll link more tickets with explanation shortly.....

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/12636

**Comment by ValWood** [comment]
submitted to UniProt

**Comment by pedruzzi** [comment]
Removed all mention of Cvt (function/pathway/subcell) in all proteins of this family except S.cerevisiae.
