### ISSUE TITLE
	HAMAP:MF_03045 mapping  applied to SPAC2C4.07c O14040

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1438]
No miRNA in fungi.
Could this mapping be removed? I have requested a taxon check https://github.com/geneontology/go-ontology/issues/12634.

Thanks

Val

**Comment by pedruzzi** [comment]
There was a taxon case missing on that GO term in HAMAP-rule MF_03045. I've added it now so the mapping should disappear.
taxon constraint on this GO term is a good idea, as we check these in HAMAP as well and it would have helped to identify this omission.
Thanks for reporting
-ivo

**Comment by ValWood** [comment]
Not sure if the taxon constriant can be applied across fungi, but  that's all for  this one!
