### ISSUE TITLE
Query mapping IPR000043

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1439]
adenosylhomocysteinase

S-adenosyl-L-homocysteine + H2O = adenosine + L-homocysteine.

has a mapping to
IEA IPR000043   GO_REF:0000002
    one-carbon metabolic process

looks incorrect?

**Comment by asangrador** [comment]
I have removed this mapping. It seems to have been added a long time ago, probably the entry changed, but the term was not deleted. Thanks.
