### ISSUE TITLE
query mappings for 	IPR005294 and	IPR000793

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1440]
IPR005294 and   IPR000793

have mappings to
proton-transporting ATPase activity, rotational mechanism
and
ATP hydrolysis coupled proton transport

This is not the physiological direction for the mitochondrial F1/F0 ATPase
(its acting as an ATP synthase)

(there have been quite a few similar tickets to this when  the ATP synthesis mappings have been applied to the vacuolar ATPAses)

Val

**Comment by almitchell** [comment]
Hi Val,
Can you give us more detail?
Thanks,
Alex

**Comment by ValWood** [comment]
I added a few more words ;)
 I'll link to some older tickets

**Comment by ValWood** [comment]
The older tickets are all about the V-type ATPase
https://github.com/geneontology/go-annotation/issues/479
https://github.com/geneontology/go-annotation/issues/515
https://github.com/geneontology/go-annotation/issues/581
https://github.com/geneontology/go-annotation/issues/745
https://github.com/geneontology/go-annotation/issues/581
https://github.com/geneontology/go-annotation/issues/744

It seems F1-Fo can function physiologically  in  reverse in some bacteria and protazoa...I haven't seen this for yeast....this might make the mappings tricky....


Like other enzymes, the activity of F1FO ATP synthase is reversible. Large-enough quantities of ATP cause it to create a transmembrane proton gradient, this is used by fermenting bacteria that do not have an electron transport chain, but rather hydrolyze ATP to make a proton gradient, which they use to drive flagella and the transport of nutrients into the cell.

**Comment by almitchell** [comment]
Thanks Val, 
We will start digging into these - I suspect that a lot of our annotations will need updating.
Alex

**Comment by asangrador** [comment]
Hi Val,

The 'proton-transporting ATPase activity, rotational mechanism'
and 'ATP hydrolysis coupled proton transport' terms have now been deleted from these entries (changes will not be visible till our next release, release 60.0) . We will also review other ATP synthases (F1/F0 ATPases) to make sure they have the right annotation.

Cheers,
Amaia
