### ISSUE TITLE
PTHR11135 - PTN000123981 annotation transfer to bacterial proteins

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#1441]
I'm not sure whether it was a "not" that wasn't working, but several eukaryotic-specific GO terms got added to an E. coli protein, YhcC (P0ADW6) via Panther. Could this be fixed?
Thanks,
Ingrid

**Comment by pgaudet** [comment]
Hi Ingrid, 

Thanks for the feedback, we reviewed the annotation of this family. 

Pascale
