### ISSUE TITLE
PTHR10643 - Q10198 (ndc80)  problem PAINT annotations 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1444]
Challenge	
PANTHER:PTN000837476
GO:0005200
structural constituent of cytoskeleton

Ndc80 is a kinetochore component , not a spindle component 

PANTHER:PTN000837476
GO:0007052 mitotic spindle organization also looks suspect
	
and
	
PANTHER:PTN000837476
GO:0000132 establishment of mitotic spindle orientation

(there is a spindle orientation  checkpoint in budding yeast but this is not known to exist in fission yeast. This  *could* be the source of these annotations/)

**Comment by pgaudet** [comment]
Fixed ! Removed 
PANTHER:PTN000837476
GO:0007052 mitotic spindle organization also looks suspect

and

PANTHER:PTN000837476
GO:0000132 establishment of mitotic spindle orientation

The annotation to spindle as a component was already removed. 

Thanks, 

Pascale & Marc
