### ISSUE TITLE
PTHR12585 - PANTHER:PTN000286904	 rad21 is mitotic cohesin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1445]
Hi Pascale

rad21 is mitotic cohesin not meiotic
	
GO:0034991 nuclear meiotic cohesin complex
PANTHER:PTN000286904	

AND 
GO:0051754 meiotic sister chromatid cohesion, centromeric
P
IBA
GO_REF:0000033
PANTHER:PTN000286904

@pgaudet

**Comment by ValWood** [comment]
I want to check that the mitotic cohesin isn't used for the sister chromatid segregation of meiotic division. I don't think that is  but I'll double check. It think thar these come from mouse annotations?  I had previously spotted that  mouse  had meiotic annotations for mitotic cohesin @ukemi remember I mentioned them to you in an e-mail when we were discussing Frank's paper?

**Comment by ValWood** [comment]
non issue, rad21 has a role in meiosis too.....

**Comment by ValWood** [comment]
well what I was actually told was":

"some people will argue that rad21 is specific to mitosis and is not present in meiosis, others would keep an open mind" 
so it isn't really conclusive. Which organism has the EXP evidence for  rad21?

**Comment by ukemi** [comment]
Hi Val. I looked at the two papers that we had annotated to the meiotic term and it looks like in the first one the antibody could detect Rad21 and Rad21l and in the second one they were really talking about Rad21l. I removed the meiotic component annotations to Rad21.

**Comment by pgaudet** [comment]
Pascale: This is PTHR12585 - Marc and I are looking into it.

**Comment by ValWood** [comment]
I think this one is OK, see feedback above...but the other tickets about cohesin are still valid.
For Rad21 it is still not certain.

**Comment by pgaudet** [comment]
We moved the annotation to the parents (nuclear cohesin complex and sister chromatid cohesion). 

Thanks ! 
Pascale & Marc

**Comment by ValWood** [comment]
mitotic  cohesin complex is  definitely fine, its only the meiotic which is tentative
