### ISSUE TITLE
	IPR017923	Transcription factor IIS, N-terminal

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1447]
Is also present in proteins which are not directly involved in transcription.

SPCC74.02c	ppn1		mRNA cleavage and polyadenylation specificity factor complex associated protein 	O74535

cheers

val

**Comment by happy-lorna** [comment]
Thanks for pointing this out. I have removed the affected GO terms and have updated the annotation. This will be visible in the next release.
cheers, Lorna.
