### ISSUE TITLE
sperm mobilization or fertilization?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1450]
Might be a good topic for an annotation call

Discussion from
https://github.com/geneontology/go-ontology/issues/12695#issuecomment-250817982

Term matrix shows 74 annotations to both "sperm motility" and "fertilization"

![sperm motility matrix](https://cloud.githubusercontent.com/assets/7359272/19086418/f94cd2d2-8a65-11e6-9eea-5766312d99b7.jpg)

sperm motility should presumably not be annotated directly to "fertilization" althoguh sperm motility is required for (causally upstream of) fertilization

**Comment by ValWood** [comment]
@cmungall 
@ukemi

**Comment by vanaukenk** [comment]
@ValWood - it looks like there are now 82 gene products annotated to both :-)
I can understand, though, why curators are doing that, given that there is not an explicit relationship in the ontology between fertilization and the sperm motility terms, and I'm not sure there should be.
This is a good example, though, of one process that is causally upstream of another.

**Comment by ValWood** [comment]
I'm not fussed if this is closed ;)

**Comment by vanaukenk** [comment]
Okay, I will close this ticket, but have made note of this as a potentially good example of use of a causally_upstream_of relation.
Thx.
