### ISSUE TITLE
Obsolete IDs in Slims - filter annotations

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-annotation#1452]
In https://github.com/geneontology/go-ontology/issues/12731, @tonysawfordebi reported that a number of GO slims refer to obsolete terms.

This was discussed at a recent ontology call, http://wiki.geneontology.org/index.php/Ontology_meeting_2016-03-10. As per the minutes, editors didn't consider that having obsolete terms in slim was an issue per se, however annotations should be filtered out - therefore moving this ticket to the annotation tracker. @cmungall, assigning to you as I think you are the one who could filter annotations on the GOC side? Feel free to re assign if this is wrong.

**Comment by cmungall** [comment]
```
obo-sed.pl -r is_obsolete 's/subset:.*\n//' gene_ontology_write.obo > 
filtered.obo
diff -u gene_ontology_write.obo filtered.obo | less
mv filtered.obo gene_ontology_write.obo
```

https://github.com/cmungall/obo-scripts

You may want to file a ticket on the Protege obsoletion plugin tracker 
https://github.com/balhoff/obo-actions/

For a removal script, either robot or sparql may be best

**Comment by pgaudet** [comment]
@cmungall 
Do we want to filter annotations or fix the slim ?

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14677
