### ISSUE TITLE
Mapping IPR008220

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1453]
Pombe cys2 has two annotations from IPR008220
GO:0009086 methionine biosynthetic process IEA IPR008220
GO:0004414 homoserine O-acetyltransferase activity IEA IPR008220

However, the activity of cys2 is serine O-acetyltransferase activity (PMID:27558664)
and it is involved in cysteine biosynthetic process from serine 

![screen shot 2016-10-17 at 11 24 35](https://cloud.githubusercontent.com/assets/12727506/19435263/998812de-9461-11e6-904c-27c38c61707d.png)

can these two mappings be removed? 

"Cys2 has greatest sequence homology to homoserine O-acetyltransferases, predicting that it should be involved with methionine biosynthesis. However, as noted previously, Met6 is also predicted to be a homoserine O-acetyltransferase...
.....Thus our data support the notion that Cys2 is actually a serine O-acetyltransferase that is specifically essential for cysteine biosynthesis"

**Comment by ValWood** [comment]
Also supported by PMID: 17622533

" We also showed that in Schizosaccharomyces pombe there are two apparent homologues of Saccharomyces cerevisiae MET2: the previously known met6 (+), and SPBC106.17c (named cys2 (+)). The cys2 mutation required cysteine rather than methionine."

**Comment by ValWood** [comment]
Note that the cys2 and met6 are not "in paralogs" wrt S. cerevisiae...... S. cerevisiae does not  appear to have a cys2 ortholog, these are separate branches of this family.

**Comment by asangrador** [comment]
Yes, these annotations are wrong and will be removed from the entry. (I think we can create a more specific entry that does not match the pombe proteins to avoid loosing annotations).
Amaia
