### ISSUE TITLE
No IBAs in the source FB or PomBase files

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1455]
No IBAs in the release files

```
curl --compressed -L http://geneontology.org/gene-associations/gene_association.fb.gz | gunzip | egrep '\tIBA\t'
curl --compressed -L http://geneontology.org/gene-associations/gene_association.pombase.gz | gunzip | egrep '\tIBA\t'
```

no results

not in the submission file either:

```
curl --compressed -L http://geneontology.org/gene-associations/submission/gene_association.fb.gz | gunzip | egrep '\tIBA\t'
curl --compressed -L http://geneontology.org/gene-associations/submission/gene_association.pombase.gz | gunzip | egrep '\tIBA\t'
```

Either they don't get them from PAINT, or they don't incorporate them into their DB.

**Comment by cmungall** [comment]
OK, touchup is doing the right thing. GAFs with IBAs are present here:

http://www.geneontology.org/gene-associations/submission/paint/pre-submission/

so PomBase and FB are not slurping these...

**Comment by ValWood** [comment]
nope, not yet...we are waiting for fixes:

https://github.com/geneontology/go-annotation/issues/1321
https://github.com/geneontology/go-annotation/issues/1322
https://github.com/geneontology/go-annotation/issues/1316
https://github.com/geneontology/go-annotation/issues/1315
https://github.com/geneontology/go-annotation/issues/1314
https://github.com/geneontology/go-annotation/issues/1313
https://github.com/geneontology/go-annotation/issues/1312

from  a small amount of spot checking....

I have now (eventually) got every slim category to match the expectations of those working on these processes, 
http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms
and these would reek havoc...

Will try again when the outstanding issues are fixed ...please don't include...most valid annotations will be covered.

**Comment by hattrill** [comment]
Hi Chris,

We are in the right in the middle of making a lovely new pipeline to incorporate external annotations including IBAs from PAINT - I am nearly there, but I "flushed" the old PAINT set we held as they were very stale.  (In the past, external annotations were updated in an ad hoc manner, but soon FlyBase will be the model of good practice "slurping and regurgitating").

**Comment by pgaudet** [comment]
Hi Val,

Marc and I have been working on disputes, we'll look at these this week. 

Thanks for the reminder ! 

Pascale

**Comment by ValWood** [comment]
Not in a hurry, it will be a while before we have another update, so PomBase won't be able to reload for a few months (but we can evaluate again once the tickets are closed).
VAl

**Comment by cmungall** [comment]
Thanks for your responses, makes sense. cc @thomaspd

**Comment by selewis** [comment]
@ValWood Are any of these still open? I checked a handful and they all seem to be closed.

**Comment by ValWood** [comment]
Not sure, but still some open:

https://github.com/geneontology/go-annotation/issues?q=is%3Aissue+is%3Aopen+label%3A%22PANTHER+annotation%22

This isn't an issue because I can filter these during loading when I get to it.

**Comment by hattrill** [comment]
As of the FB2017_02 April release of FlyBase, the PAINT annotations are in FlyBase and are incorporated the FB GAF. Going forward, they will be updated in FB every release.

**Comment by ValWood** [comment]
out of date.
