### ISSUE TITLE
PTHR10000 has lost ancestral nodes

### ISSUE THREAD

**Issue by selewis** [geneontology/go-annotation#1456]
PTN000000001 and PTN000000002 aren't in the PTHR10000 family any longer.

They were used to annotate to:
small molecule biosynthetic process (GO:0044283) 
cytoplasm (GO:0005737) 
phosphatase activity 
phosphoserine phosphatase activity (GO:0004647) 
L-serine biosynthetic process (GO:0006564) 
magnesium ion binding (GO:0000287) 
and
chloroplast (GO:0009507) supported by [TAIR:locus:2027433]

Most of the supporting information came from  SGD:S000003440, HGNC:9577, TAIR:locus:2027433, EcoGene:EG10945, ENSEMBL:PF10_0325, EcoGene:EG13327, EcoGene:EG13678, EcoGene:EG13216, EcoGene:EG11470, EcoGene:EG11239, EcoGene:EG11195
I think these are still in the family, but haven't checked yet.

**Comment by marcfeuermann** [comment]
Many previous terms are any longer in the family. Only "phosphatase activity",  "magnesium ion binding" and "cytosol/cytoplasm" could be kept, all coming from E Coli ybhA and yldA.
