### ISSUE TITLE
	IPR003111 mapping to GO:0004176	ATP-dependent peptidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1460]
This is the substrate binding domain, and it seems to be present in non-peptidases:

http://www.pombase.org/spombe/result/SPBC14F5.10c#translation

Do you think?

**Comment by ndrawlings** [comment]
Hi Val,

 

Thank you for your E-mail.  You are absolutely correct: the S. pombe sequence is lacking the peptidase domain, and this domain is substrate-binding.  I have removed the GO terms relating to proteolysis from the InterPro entry and changed the annotation to explain that this is a substrate-binding domain only and that it can occur in proteins missing the peptidase domain.

**Comment by ValWood** [comment]
Thanks Neil!
