### ISSUE TITLE
GO:0001948 glycoprotein binding annotations - QC problem

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#1462]
Hi

as GO:0001948 glycoprotein binding is a child of GO:0097367 carbohydrate derivative binding and is no longer a child of protein binding we get error messages when we create an IPI annotation. Because the GO:0001948 glycoprotein binding (and the child terms) does not meet the reciprocal binding requirement.

Would it be possible to either add protein binding as a parent to this term, or change the QC so that this annotation is recognised as an acceptable reciprocal annotation associated with a protein binding annotation.

Thanks

Ruth
@tonysawfordebi

**Comment by ValWood** [comment]
Glycoprotein is_a protein so glycoprotein binding should be is_a protein binding.....(and is in CHEBI)

**Comment by mcourtot** [comment]
Hi @RLovering, this is an issue linked to the use of PRO and ChEBI protein, see https://github.com/geneontology/go-ontology/issues/12580

**Comment by mcourtot** [comment]
Hi @RLovering  - @paolaroncaglia has added the missing link and things should go back to normal for annotations to glycoprotein.
