### ISSUE TITLE
Devise SOP for using annotation matrix for QC

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1467]
Explore ways of using Val's matrix (now on AmiGO) to spot possibly problematic areas of annotation or ontology.

**Comment by suzialeksander** [comment]
@ValWood have there been any updates in this area?

**Comment by ValWood** [comment]
not yet but it is on my radar....

**Comment by suzialeksander** [comment]
This is in place at https://github.com/geneontology/go-site/tree/master/metadata/rules#gorule0000009 

Closing, any improvement requests should be a new ticket
