### ISSUE TITLE
Documentation: explain that AmiGO displays annotation to subclasses by default

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-annotation#1471]
We have had a similar question coming up a few times on the GO helpdesk, about users saying 'AmiGO displays annotations to term X but I don't see them in the GAF file'. The reason is that AmiGO displays annotations to subclasses by default, while the GAF only contains direct annotations.

It may be worthwhile adding a new FAQ?

**Comment by cmungall** [comment]
Yes, but not just to subclasses

**Comment by mcourtot** [comment]
See, I thought it was just subclasses :) What other annotations are displayed?

**Comment by dosumis** [comment]
QuickGO and AmiGO both use closure over multiple edge types to group annotations.  QuickGO defaults = part_of, is_a, occurs_in.  You can optionally switch to use regulates relations too.  I believe AmiGO uses regulates by default.

**Comment by mcourtot** [comment]
So by default AmiGO = part_of, is_a, occurs_in, regulates?
I know in QuickGO you can visualize/modify the behaviour using "Filter" and 'Go Identifier tab", but I don't know how to do this with AmiGO - it may be worth adding the explanation to the FAQ?

**Comment by pgaudet** [comment]
This issue was moved to geneontology/amigo#459
