### ISSUE TITLE
Nuclear cap-binding protein subunit 1 (IPR027159)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1473]
I wasn't sure about
GO:0045292 mRNA cis splicing, via spliceosome 

(an mRNA catabolic process mapping would be better?)

**Comment by asangrador** [comment]
I don't think the term is wrong;  cbc1/spo1, as a component of the CBC, has been shown to play an important role in pre-mRNA splicing in eukaryotes. Yeast results  also point towards this role (PMID:15989964, A yeast cap binding protein complex (yCBC) acts at an early step in pre-mRNA splicing). It seems to be involved in spliceosome assembly/U1 snRNP recruitment  and removal the U1 snRNP (PMID: 15989964 ). 

A higher term would be' mRNA splicing, via spliceosome' or 'mRNA processing'.

**Comment by ValWood** [comment]
yep!
