### ISSUE TITLE
suggestion for annotation of human protein

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-annotation#1475]
Transferred from GO helpdesk:
-------------
https://www.ncbi.nlm.nih.gov/pubmed/?term=17984056

Hello,

I don't know what annotation team to pass this on to. PMID:17984056 seems to
have quite a bit of useful information on DUX4 (this gene currently only has
IEAs http://www.ebi.ac.uk/QuickGO/GProtein?ac=C3U3A0 ).

E.g.
DNA binding transcription factor activity involved in positive regulation of
transcription (target = pitx1)
RNA polymerase II core promoter proximal region sequence-specific DNA binding
(binds TAAT core motif - I don't know if there is a SO term for this)

Thanks...Antonia

**Comment by tberardini** [comment]
@Antonialock : annotation issues can be tracked on this GH tracker
@RLovering : is this paper one that your group can take on?

**Comment by ValWood** [comment]
@Antonialock  I often hit the feedback button from the UniProt entry for missing human annotation they usually do them pretty quickly.

**Comment by Antonialock** [comment]
The gene is implicated in FSHD, a skeletal muscular dystrophy so maybe it is important for heart too :-) I can send it to UniProt unless you take it @RLovering

**Comment by RLovering** [comment]
Ok will do, I had started looking at it and got distracted by phosphorylation. who asked for it to be annotated?

**Comment by ValWood** [comment]
Antonia is trained not to let any IEA hang around if there is a possible EXP, so she thinks its a universal rule :).....the luxury of 5000 genes eh ?

**Comment by RLovering** [comment]
but why is she looking at human proteins and not annotating them?

**Comment by hdrabkin** [comment]
In mouse, DUX4 appears coded by Dux. However, the FSHD diseases appear to be associated with Frg1 (at least there is a mouse model).  Currently we don't have anything for Dux, even IEA (because we won't process  interpro from trembl records  (historic)). But do have IEA or ISO for Frg1. I've got three papers associated with Dux, 2 of which may have GO (at least one does have localization data that I can use). Additional problem: In mouse,  Dux is a Complex/Cluster/Region (NOT marker type "gene").  So even if I annotate it in MGI, cannot do so in Noctua (not a marker type gene), and it won't get into our gaf (we annotate only marker type =gene; no pseudogenes, clusters, etc.).  8-(

**Comment by Antonialock** [comment]
I started another job 50% Ruth, curating gene expression datasets for rare diseases (not GO related). I came across this gene and thought it was a shame to leave it at an IEA when there is experimental evidence for some function. I assumed I could just send it on to GO for generic GO annotation (hence why I sent it to their helpdesk)

**Comment by hdrabkin** [comment]
Well, I put annotation to it (our system triggers nagged about it); at least it's there now 8-)

**Comment by Antonialock** [comment]
Thanks!

**Comment by RLovering** [comment]
Perhaps we should set up a google doc as I am sure you will find plenty more? But it is great that Harold has address the mouse gene, I must admit it will be after xmas before I have time to do the paper you mentioned as it looks like I will need to pay attention when reading it.

**Comment by Antonialock** [comment]
I'll just pass them on to uniprot in the future! No worries about this one anyway, I managed to miss that I had landed on a trembl entry http://www.ebi.ac.uk/QuickGO/GProtein?ac=C3U3A0 
I should have looked at http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q9UBX2
instead....the gene is annotated - fridays eh!
Thanks all... :-)
