### ISSUE TITLE
Secondary ID in Interpro2go mapping file

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1476]
Hi,

It looks like the secondary ID GO:0004889 is still being used in two mappings in the InterPro2GO mapping file:

InterPro:IPR032932 Neuronal acetylcholine receptor subunit beta-2 > GO:acetylcholine-activated cation-selective channel activity ; GO:0004889

InterPro:IPR002394 Nicotinic acetylcholine receptor > GO:acetylcholine-activated cation-selective channel activity ; GO:0004889

The new primary ID is: GO:0022848 and the new term name is: acetylcholine-gated cation-selective channel activity

Thanks,
--Kimberly Van Auken

**Comment by asangrador** [comment]
Thanks for letting us know. We have removed the secondary term and substitute with the new primary ID. This change will be visible in our next release,

Amaia

**Comment by vanaukenk** [comment]
Thanks very much, @asangrador!
