### ISSUE TITLE
lncRNAs are incorrectly classified as miRNAs in GOA GPI and GAF

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1477]
From http://jira.geneontology.org/browse/GO-1430

We have some lncRNAs in GO, e.g.

http://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS000053D37B_9606

However, these are classified incorrectly as miRNAs:

```
$ curl -L  http://www.geneontology.org/gene-associations/goa_human_rna.gaf.gz | gzip -dc | grep URS000053D37B
 RNAcentral      URS000053D37B_9606      URS000053D37B_9606              GO:1903955      PMID:24270810   IMP             P       Homo sapiens long intergenic non-protein coding RNA 1104 (LINC01104), long non-coding RNA.            miRNA   taxon:9606      20150302        ParkinsonsUK-UCL        has_regulation_target(UniProtKB:O60260)       
```

It's actually a lncRNA:

http://www.noncode.org/show_gene.php?id=NONHSAG028706.2

Seem to be at least 22 of these:

```
$ curl -L  http://www.geneontology.org/gene-associations/goa_human_rna.gaf.gz | gzip -dc | grep 'long non-coding RNA' | egrep -c '\tmiRNA\t'
22
```

**Comment by cmungall** [comment]
Sorry, should have demonstrated on source file:

```
$ curl -L ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_rna.gaf.gz | gzip -dc | grep 'long non-coding RNA'  | egrep -c '\tmiRNA\t'
100 31590  100 31590    0     0  12875      0  0:00:02  0:00:02 --:--:-- 12888
22
```

**Comment by rachhuntley** [comment]
There are other entity types in this file as well, e.g. small nucleolar RNA (URS00000DE3E2_9606) and telomerase RNA (URS00004A7003_9606). I don't know if Tony has classified everything in this file as miRNA, as that was it's original purpose, but now other curators are using RNAcentral IDs for other types of RNA. 

We could look into using RNAcentral's classification - I think it has improved recently, it used to be that miRNAs were classified as other types of RNAs, e.g. lncRNA. However, there are still some miRNAs classified as "miscellaneous RNA", e.g. URS0000190DC2_9606, which I have annotated (as a miRNA) based on sequence identity reported in the paper. Also in the case of this small nucleolar RNA: URS00000DE3E2_9606, it is classified as snRNA and snoRNA in RNAcentral (http://rnacentral.org/search?q=URS00000DE3E2_9606), whereas this one: URS00006C68F5_9606 is classified only as snRNA.

**Comment by pgaudet** [comment]
I think we now use RNA Central classifications ? 
Anyhow I dont find the example ID in AmiGO. I'll close this, it can be reopened if this is still an issue. 

@RLovering have you encountered this?

**Comment by RLovering** [comment]
sorry I haven't been following this issue
Ruth
