### ISSUE TITLE
Corrections to annotations to ' 'signal transducer, downstream of receptor, with protein tyrosine kinase activity'

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-annotation#1478]
@hattrill  - incorrect annotation of Alk to  'signal transducer, downstream of receptor, with protein tyrosine kinase activity' 

![image](https://cloud.githubusercontent.com/assets/112839/21313634/e5a540aa-c5ea-11e6-9732-c09eaba7d338.png)

Move to "transmembrane receptor tyrosine kinase activity" 

@rachhuntley - incorrect annotation of INSR to  'signal transducer, downstream of receptor, with protein tyrosine kinase activity' 

![image](https://cloud.githubusercontent.com/assets/112839/21313808/df4053e8-c5eb-11e6-9702-57cd5a12744a.png)

Move to "transmembrane receptor tyrosine kinase activity"

**Comment by hattrill** [comment]
Thanks for spotting - replaced. Will be visible after next release in Jan.

**Comment by pgaudet** [comment]
OK those are gone.
