### ISSUE TITLE
QC check for annotations to retracted publications

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1479]
Hi,
Following on from a help desk ticket:
http://jira.geneontology.org/browse/GO-1431

Can we explore adding a QC check for annotations to retracted publications?

A possible approach might be:

PubMed indexes retracted publications in the PublicationTypeList tag. Here's an example (XML formatting not coming through):

PublicationTypeList

PublicationType UI="D016428" Journal Article PublicationType

PublicationType UI="D013485" Research Support, Non-U.S. Gov't PublicationType

PublicationType UI="D013486" Research Support, U.S. Gov't, Non-P.H.S.  PublicationType

PublicationType UI="D016441" Retracted Publication PublicationType 

PublicationTypeList

Perhaps implementing a periodic query to PubMed for articles with Type "Retracted Publication" and then checking those PMIDs against the PMIDs in the GO database would work.

Thx.

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-site#676
