### ISSUE TITLE
Q: Does anyone know the identity of  "Atg12 ligase activity"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1481]
Name	Atg12 ligase activity
Ontology	Molecular Function
Definition	Catalysis of the transfer of Atg12 to a substrate protein via the reaction X-Atg12 + S --> X + S-Atg12, where X is either an E2 or E3 enzyme, the X-Atg12 linkage is a thioester bond, and the S-Atg12 linkage is an isopeptide bond between the C-terminal amino acid of Atg12 and the epsilon-amino group of lysine residues in the substrate.

the GP which ligates Atg12  to a substrate?

Thanks!
https://github.com/pombase/curation/issues/1171

Val

**Comment by ukemi** [comment]
In some cases, there is none, but I'm not sure that is always the case.

PMID:22682742

**Comment by ValWood** [comment]
OK that would make sense ...there are no annotations to this term now I have corrected our ISS.

**Comment by srengel** [comment]
is ATG10 an example?  it's annotated one parent up.  Atg12-transferase activity.

**Comment by ukemi** [comment]
I think it is the conjugating enzyme (E2).

**Comment by ValWood** [comment]
so maybe ATG10 is one of those e.g.s which do both the E2 and the E3.....
