### ISSUE TITLE
	IPR028343 -> GO:0006001

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1482]
Hi,

I think this mapping may not be correct here.
Explanation is in this ticket.
https://github.com/pombase/curation/issues/1226#issuecomment-268526810
v

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

Thank you for this. I have replaced this term with GO:0006094 gluconeogenesis . Does this term look right for you?

Regards, 
Hsin-Yu

**Comment by ValWood** [comment]
based on what Peter says in our ticket, not all are gluconeogenesis either for human....
v

**Comment by EBI-Hsinyu** [comment]
Thanks! I will remove this term. 
Hsin-Yu
