### ISSUE TITLE
IPR007834 proteasome assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1483]
I don't think this should par to "proteasome assembly"

The complex may not assemble when this subunit is mutated, but this is a phenotype and not the role  of this proteasome subunit in a normal cell.

Also the mapping to "mRNA export" seem indirect. What  is the source of this one?

**Comment by asangrador** [comment]
Hi Val,

The proteasome assembly annotation derives from this paper where Dss1 in budding yeast was shown to function in proteasome assembly :The intrinsically disordered Sem1 protein functions as a molecular tether during proteasome lid biogenesis (Tomko and Hochstrasser, 2014). Paper PMID:25306921 from pombe states: In agreement with data from budding yeast loss of Dss1 caused a modest reduction in 26S proteasome integrity. Also there is this recent review paper: PMID:26944332

Regarding the role of 'mRNA export' it seems to be some reasonable evidence  in yeast and humans. For budding yeast: PMID:19289793, Sem1 is a functional component of the nuclear pore complex-associated messenger RNA export machinery. Also PMID:19061648. In humans PMID:24896180. 

I would prefer not to remove these terms. Have a look at the references and let me know what you think.

Amaia

**Comment by ValWood** [comment]
Yep, OK is multifunctional.
Val
