### ISSUE TITLE
IPR033008 mapping to "COP9 signalosome assembly"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1485]
This is just a phenotype, it  is required for assembly, because its a component of the complex
 but it isn't "involved in assembly"

for more info see David Hill's comment on this ticket:
https://github.com/geneontology/go-ontology/issues/12846

**Comment by asangrador** [comment]
Yes, its C-terminal PCI domain interacts with the PCI domain of other subunits to form the complex, but it is not involved in complex formation per se.

I have removed the term.

Amaia
