### ISSUE TITLE
GO annotations being "projected" by Ensembl back onto same species?

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-annotation#1488]
Moved from the ontology tracker. https://github.com/geneontology/go-ontology/issues/12870
Created by @Pauldenny 

Should IEA GO annotations be "projected" by Ensembl back onto same species? e.g. Q4VAE3
Tmem65 (mouse) GO:0003231
cardiac ventricle development IEA
GO_REF:0000107
with/from field: UniProtKB:Q4VAE3|ensembl:ENSMUSP00000071984
Which appears to be the same gene in the same species, apparently inferred from an IMP annotation of the same gene?
Shouldn't these projections only be inferred for homologs in a different species? Or am I missing something?

**Comment by mcourtot** [comment]
Mentioned this to @tonysawfordebi yesterday who is following up with Ensembl (projections of orthologs are done against self in the file they provide)

**Comment by pgaudet** [comment]
@tonysawfordebi Are you taking care of this ? Seems like it should not be on this tracker. Please move if possible. 

Thanks, Pascale

**Comment by tonysawfordebi** [comment]
I fixed this ages ago. If there are still any self-projections in the Ensembl annotation sets, then that's a different bug.
