### ISSUE TITLE
cohesin complex update, matrix project

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1490]
Update on the original ticket: https://github.com/geneontology/go-annotation/issues/1396

This is how the cohesin intersections look currently:

![cohesin_complex_update](https://cloud.githubusercontent.com/assets/7359272/21824918/5b43d6e2-d779-11e6-8cee-095e90956fb3.jpg)

**Comment by ukemi** [comment]
Can you cross-reference the ontology issue for the cytoskeleton here?

**Comment by ValWood** [comment]
Actions
I think bit I think that  might be fixed already 9that is part of the reduction from 30 to 16)
I didn't want to check everything until the ontology was fixed. Just about to list the things outstanding...

**Comment by ValWood** [comment]
outstanding issues
- [ ]  Zfin translation, I think this was reported as fixed @doughowe
- [ ] Reactome small protein conjugation or removal (becasue sumoylated)
Issues not previously reported

- [ ]  DNA replication via SGD (plus IEA's)
http://amigo.geneontology.org/amigo/reference/PMID:24062159
I would call this "sister chromatid decatenation"
inter-molecular strand passage  of DNA   to removes catenanes persisting between sister chromatids following DNA replication.
This term  "DNA unwinding involved in DNA replication" is describing the geometric change  which occurs *during replication* not the topological change which occurs afterwards.

- [ ]  cytokinesis, reported to SGD CDC5 helpdesk

chromatin organization
- [ ]  TAIR SYN1
- [ ]   FlyBase Nipped B and Sce
These are both "Cohesin complex" and co-localizes with. I didn't think we used "colocalizes" in this way. I thought it was when you used  colocalization with a tagged protein to infer a localization (like centromere or chromatin here), rather than a complex term
Maybe we should discuss
Suggest rule, do not use "colocalizes_with" with complex terms?
(If it's binding, use a protein complex binterm term/extension?)

Cytoskeleton annotations remaining now the ontology issue is fixed
- [ ]  RGD have ISO to human, but human does not have this annotation
- [ ] TAIR WAPL1 and 2 (IGI to each other) (mitotic spindle organization, this looks a bit odd for cohsin)
- [ ] PomBase moa1 cohesin associated NAS (FIXED)
- [ ]  SGD CDC5 (already reported via e-mail for the cytokinesis intersection, this is also a "colocalizes_with cohesin" This one has been used to generate  cohesin iEAs for other species which highlight a danger.
- [ ]  SMC3 human  (plus ISO's and IEA's), reported to UniPROT  via RT
 
Regulation of cell cycle phase transition
- [ ] MGI mta3  query "cohesin"
- [ ] CDC5A reported to UniPROT  via RT 
The rest are IEAs from these 2 gene products

**Comment by hattrill** [comment]
with regard to colocalizes_with complexes the documentation states "Gene products that are transiently or peripherally associated with an organelle or complex may be annotated to the relevant cellular component term, using the colocalizes_with qualifier."

A couple of years ago I queried the use of "colocalizes_with" for instances where a gene product is not part of a complex: See snippets below:
Q: "While we're on the subject, could I ask about the "colocalizes_with" qualifier? The documentation says "Gene products that are transiently or peripherally associated with an organelle or complex may be annotated to the relevant cellular component term, using the colocalizes_with qualifier".  
 I take this to mean: if protein X is shown associate with complex Y and this is pertinent to the biology described in the paper but it is unclear whether it is a bona fide subunit, annotate to the specific complex with the colocalizes_with qualifier."
Answer 1 "I think this is a very good usage of the qualifier.  The stability of interactions is an important factor in whether GO or Intact makes a complex term (which can then be used as the subject of GO annotation).  But that doesn't preclude capturing weaker relationships in annotation."
Answer 2 "The best example that comes to my mind is ribosome. We all know what the subunits of the ribosome are. But often there are proteins that bind to it for various reasons and they will all get annotated to a subunit of the ribosome with this colocalizes qualifier. hope that helps."
--------------------------------------------
So this is the rule we've applied, although not with great gusto as we have other means of capturing protein-protein interactions.

Personally, I'm not so in-favour of coloc_with for complexes - it's ambiguous and if they get stripped out by downstream tools it's a pain (but not as bad as a NOT qualifier being lost!). The last time we discussed this on a call, there was a general feeling that we should get new complex binding terms but I this hasn't trickled down to a hard rule or into the documentation. So, perhaps an official decision is needed and we need to think about those cases where we are not completely sure whether the a component is binding to or part of the complex.

**Comment by ValWood** [comment]
I'm going to migrate the colocalizes with "complex" for proteins which are clearly not part of the complex to another ticket. I think its important to address and I don't want it to get lost.
v

**Comment by tberardini** [comment]
@ValWood : Sorry, but I missed the context.  Am I supposed to be reviewing the annotations to chromatin organization and cytoskeleton?  Or specific kids?

**Comment by hattrill** [comment]
Have removed co-loc with cohesin complex for Sce as paper actually does not shown this. 
For 2008 paper for Nipped-B removed co-loc with cohesin complex (and added some cohesin loading/unloading terms for genes in this paper as more appropriate), but for 2010 paper they show co-loc staining with cohesin complex subunits but in an IP "none of the cohesin subunit precipitations brought down detectable amounts of Nipped-B". So, I will keep this one for now for and add it to #1500 as an example.

**Comment by ValWood** [comment]
The queried annotation is "mitotic spindle organization"  WAPL1 and 2.
WAPL is a cohesin binding protein and cohesin release factor.
I read a lot of papers on this and I'm not aware of any other role. At TAIR it has "mitotic spindle organization", the evidence is IGI to each other?

I don't think that there is a direct role in spindle organization.
Phenotypes show "mitotic spindle attachment defects", this is  a downstream effect because of  the defect in kinetochore assembly.
Historically, spindle organization was (incorrectly) a parent of "mitotic spindle attachment".
This might explain the annotation.

I would  not even annotate this to "mitotic spindle attachment" its too far downstream....

Of course there may be entirely another reason for this annotation that I'n unaware of!

**Comment by hattrill** [comment]
Removed the co-locs for Nipped-B and pds5. Should be public beginning of Feb.

**Comment by tberardini** [comment]
I fixed the annotation for SYN1.  @lreiser will look into the WAPL1/2 annotations.

**Comment by lreiser** [comment]
Val, yes, it was based on the figure showing the mutant phenotype (a downstream effect) and I have obsoleted the annotations for WAPL1/2.

#MakingGOGreatAgain
#irony

**Comment by ValWood** [comment]
Hello,

This is how the cohesin complex  annotation intersections look today:

![cohesin complex update figure](https://cloud.githubusercontent.com/assets/7359272/23752337/dace6d34-04cc-11e7-8acc-31aa3e06b282.jpg)

I'm using this intersection as an example in a paper, along with some larger studies.
Also Seth Carbon will be talking about the Matrix project as ISB later this month and will use this example. This is a final call for any annotation fixes... I can remove any "pending"  annotation violations from the figure. Or, if you believe them to be correct  I can extend the annotation rules.

I'll summarize the outstanding issues today below.

Thanks!

Val

**Comment by ValWood** [comment]
- [ ]  Zfin, intersection with translation. This was supposedly removed but it didn't disappear along with the other ones? @doughowe  @zebrafishembryo 

 - [ ]  SGD CDC5 (this is because CDC5 is annotated as "colocalizes_with" cohesin complex. I wonder if an IPI would be better here (or a MF-> substrate annotation of this is possible)
There are problems associated with this type of annotation in that this is picked up and propagated without the "co localizes" qualifier. See
https://github.com/geneontology/go-annotation/issues/1500 
@srengel 

- [ ]  Human SMC1A "mitotic spindle organization" (I missed this one before so I did not query this until today raised dispute with protein to GO Dispute ID: 5913) @sylvainpoux

And today I did the final intersection, signalling which raised the following

- [ ] MGI:Mta3 Dispute ID: 5914 queried cohesin complex annotation @ukemi 

- [ ] UniProt human SMC3 not  signal transduction, its a target of a signalling pathway Dispute ID: 5933 @sylvainpoux

- [ ]  SMC1A Cohesin isn't part of checkpoint signalling (here it is described as an effector)
Dispute ID: 5934/5  @sylvainpoux 

- [x] FB:SMC3  Dispute ID: 5935 "lateral inhibition (Helen fixed this one before I finished typing the Git Hub ticket, Thanks!)

**Comment by ukemi** [comment]
I looked at this paper again and changed the annotations from being a part of the cohesin and NuRD complexes to 'protein complex binding' with those complexes as inputs. Although it is a fine line about when something is part of a complex and when it binds the complex, in this case, I think the authors intent is to say that the protein interacts with the core complexes.

**Comment by ValWood** [comment]
>Although it is a fine line about when something is part of a complex and when it binds the complex, in this case, I think the authors intent is to say that the protein interacts with the core complexes.

I agree, its sometimes tricky. In this case cohesin is a well defined complex but it has some transient interactors. Complex binding with extension works better (especially  since these have been picked up by PAINt and Ensembl piplines and propagated)

**Comment by ValWood** [comment]
More outstanding
- [ ]  FB:san Q9NHD5 via UniPRot Outstanding dispute Dispute ID: 4458)

**Comment by ValWood** [comment]
- [ ]  DNA replication via SGD (plus IEA's) @srengel
http://amigo.geneontology.org/amigo/reference/PMID:24062159
I would call this "sister chromatid decatenation"
inter-molecular strand passage of DNA to removes catenanes persisting between sister chromatids following DNA replication.
This term "DNA unwinding involved in DNA replication" is describing the geometric change which occurs during replication not the topological change which occurs afterwards.

Actually this one still has the "DNA unwinding during DNA replication in Protein2GO" too.
I think I resolved this dispute previously

**Comment by hattrill** [comment]
Hi Val, this has to be resolved by a UniProt curator - like MC Hammer I "can't touch this"

**Comment by srengel** [comment]
reading David's comment above, i can change this colocalizes_with to 'protein complex binding' with a col-16 entry.  it seems that would be better.  the deal with Cdc5 associating with Scc1 is significant and should be captured.

**Comment by ValWood** [comment]
Thanks @hattrill   I did a new P2GO dispute yesterday.

Thanks @srengel  I think the complex binding works better. Since polo phosphorylates condensin "kinase activity has_target "condensin subunit (3)" would also  provide the additional detail.

**Comment by ValWood** [comment]
forgot this one 
- [ ] UniProt human SMC3 not mitotic spindle organization Dispute ID: XXXX @sylvainpoux

**Comment by ValWood** [comment]
I think these are all done, but I noticed a new one

cohesion complex
FB:FBgn0024188 san (N-acetyltransferase)
	cohesin complex	
(it acetylates a cohesion subunit but isn’t part of the complex per se (binding maybe)
@hattrill  could you take a look

Then I'll close this.

**Comment by hattrill** [comment]
Hi @ValWood FBgn0024188 Q9NHD5 is a UniProt annotation. I've raised a dispute via Protein2GO.

**Comment by pgarmiri** [comment]
Hi @ValWood, I have now deleted the misleading annotation for Q9NHD5. Thanks @hattrill  for the notification.
Thanks,
 Penelope

**Comment by ValWood** [comment]
closing. Cohesin complex now looks  cleaned up. I opened tickets for a couple of remaining issues
