### ISSUE TITLE
InterPro:IPR006034 cellular amino acid metabolic process	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1491]
Looks incorrect?
See:
http://amigo.geneontology.org/amigo/gene_product/SGD:S000001181

V

**Comment by asangrador** [comment]
The 'NOT' qualifier for asparaginase activity for this protein comes from panTree (PANTHER:PTN000917459), inferred from the ancestor, but is there any publication or  evidence for this?

**Comment by ValWood** [comment]
@pgaudet  do you know where this comes from?

The superfamily does appear to be specific for amino acid catabolism?
Is there conflicting evidence.

Note that SRS100 evidence for spore wall maturation looks quite weak....(phenotype)
Is that the source?

**Comment by asangrador** [comment]
@pgaudet 
It would help us to know where this annotation comes from, and if there is some evidence. Because it could be involved in spore formation and still have some sort of role in amino acid catabolism.

**Comment by ValWood** [comment]
The spore wall assembly annotation comes from a single phenotype annotation from a 1988 paper:
http://www.yeastgenome.org/reference/S000045684/overview

However,  it *also* only has a prosite motif (no pfam) could easily be a false positive?
http://www.yeastgenome.org/locus/S000001181/protein

I don't see a PANTHER family reported at SGD?

**Comment by ValWood** [comment]
Tha asparagine assignment is probably OK.
Paralog YGP1 is in this superfamily:
http://www.yeastgenome.org/domain/SM00870/overview

**Comment by pgaudet** [comment]
The annotation to cellular amino acid metabolic process is gone.
