### ISSUE TITLE
mitochondrial polG/ glycyl tRNA  aminoacylation  PANTHER:PTN000078674 (PTHR10745)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1492]
Is this real? Its an annotation outlier and I didn't come across this role for PolG before

Val

http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1354947

@hdrabkin  will probably know

**Comment by hdrabkin** [comment]
Annotations to glycine tRNA aminoacylation are coming in fro PAINT (IBA) I think because of the panther family designation.  goref-0000033;

**Comment by pgaudet** [comment]
I reannotated the tree - polG seems to have been inserted in the tree in one of the Panther updates. 
The tree has polG in the middle, so I had to make NOT annotations for 
- glycine-tRNA ligase activity (GO:0004820) and 
- mitochondrial glycyl-tRNA aminoacylation (GO:0070150) 
It may take a little while to trickle to the various databases; let me know if I can already close this one. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
The gaf import file was just changed on 1/15/2017. I think it gets released monthly? So unfortunately, this will still keep showing up for a month unless the file changes.

**Comment by ValWood** [comment]
I think the panther tree is correct. The family is called
	glycyl-trna synthetase/dna polymerase subunit gamma-2 pthr10745

The mitochondrial PolG designation comes from these 2 oldish publications from the same authors:

https://www.ncbi.nlm.nih.gov/pubmed/10330144
Mol Cell Biol. 1999 Jun;19(6):4039-46.
The accessory subunit of Xenopus laevis mitochondrial DNA polymerase gamma increases processivity of the catalytic subunit of human DNA polymerase gamma and is related to class II aminoacyl-tRNA synthetases.
Carrodeguas JA1, Kobayashi R, Lim SE, Copeland WC, Bogenhagen DF.

Peptide sequences obtained from the accessory subunit of Xenopus laevis mitochondrial DNA (mtDNA) polymerase gamma (pol gamma) were used to clone the cDNA encoding this protein. Amino-terminal sequencing of the mitochondrial protein indicated the presence of a 44-amino-acid mitochondrial targeting sequence, leaving a predicted mature protein with 419 amino acids and a molecular mass of 47.3 kDa. This protein is associated with the larger, catalytic subunit in preparations of active mtDNA polymerase. The small subunit exhibits homology to its human, mouse, and Drosophila counterparts. Interestingly, significant homology to glycyl-tRNA synthetases from prokaryotic organisms reveals a likely evolutionary relationship. Since attempts to produce an enzymatically active recombinant catalytic subunit of Xenopus DNA pol gamma have not been successful, we tested the effects of adding the small subunit of the Xenopus enzyme to the catalytic subunit of human DNA pol gamma purified from baculovirus-infected insect cells. These experiments provide the first functional evidence that the small subunit of DNA pol gamma stimulates processive DNA synthesis by the human catalytic subunit under physiological salt conditions.


AND,
Nucleic Acids Res. 2000 Mar 1;28(5):1237-44.
Protein sequences conserved in prokaryotic aminoacyl-tRNA synthetases are important for the activity of the processivity factor of human mitochondrial DNA polymerase.
Carrodeguas JA1, Bogenhagen DF.

https://www.ncbi.nlm.nih.gov/pubmed/10666468

Previous studies have shown that the small subunit of Xenopus DNA polymerase gamma (pol gammaB) acts as a processivity factor to stimulate the 140 kDa catalytic subunit of human DNA polymerase gamma. A putative human pol gammaB initially identified by analysis of DNA sequence had not been shown to be functional, and appeared to be an incomplete clone. In this paper, we report the cloning of full-length human and mouse pol gammaB. Both human and mouse pol gammaB proteins were expressed in their mature forms, without their apparent mitochondrial localization signals, and shown to stimulate processivity of the recombinant catalytic subunit of human pol gammaA. Deletion analysis of human pol gammaB indicated that blocks of sequence conserved with prokaryotic class II aminoacyl-tRNA synthetases are necessary for activity and inter-action with human pol gammaA. Purification of DNA pol gamma from HeLa cells indicated that both proteins are associated in vivo.

PMID: 10666468


Maybe this is a questionable?  

This is certainly the mitochondrial tRNA ligase. Some organisms have 2 members of this family
one cytoplasmic and one mitochondrial (e.g. cerevisiae). Some have one member which covers both locations (S. pombe).

So, almost certainly, this is the mitochondrial tRNA ligase in mouse and human.  Whether it is also a polG subunit  hinges on the above 2 papers (unless  there is more evidence that I missed).

**Comment by ValWood** [comment]
I think this is an issue with these 2 old papers...

I think the solution is to not propagate this annotation via PAINT

Polg2 | polymerase (DNA directed), gamma 2, accessory subunit |   | glycine-tRNA ligase activity |   | GO_Central | Mus musculus | IBA | PANTHER:PTN000078673 | glycyl-trna synthetase/dna polymerase subunit gamma-2 pthr10745 |   | MGI:MGI:4459044GO_REF:0000033

**Comment by hdrabkin** [comment]
The Paint annotation needs to be removed and new files generated. Otherwise this continues to show up when we import the mouse PAINT gaf.

**Comment by huaiyumi** [comment]
There is a IRD loss of function annotation in the polg2 clade, so the issue was resolved.

**Comment by ValWood** [comment]
I don't think it's necessarily a loss of function. IIRC this  one is just a couple of dodgy experiments.
