### ISSUE TITLE
InterPro:IPR003732 D-amino acid catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1493]
Not sure about this one, it seems to be involved in tRNA editing, not amino-acid catabolism?
Val

http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1913294

**Comment by asangrador** [comment]
The enzyme cleaves D-aminoacyl-tRNA molecules into free tRNAs and D-amino acids, so amino-acid catabolism may not be the most correct BP term, as it does not break down the D-aa. You suggest tRNA editing, this has been merged into GO:0006400 tRNA modification, but its description does not seem to match this particular case. Perhaps tRNA metabolic process, described as 'The chemical reactions and pathways involving tRNA' could be the best option. There is no tRNA deacylation term.

For MF I can use GO:0002161 aminoacyl-tRNA editing activity.

**Comment by ValWood** [comment]
@hdrabkin  do you know?
I only suggested editing because of the MF term, but  what type of "editing" is this?

@ukemi  if you can see Harold can you tap him, My e-mails go into a spam folder ;)

(If we don't hear, tRNA modification is safe, and thats what PANTHER used)

Val

**Comment by deustp01** [comment]
From the description the process leaves the D-amino acid intact and ready for action. It could possibly qualify for D-amino acid salvage and tRNA salvage in the sense that it starts with an unwanted metabolic product and derives useful ones from it, but it's certainly not catabolism, conversion of a metabolic intermediate to yield energy (maybe) and end-products for disposal as waste.

**Comment by hdrabkin** [comment]
I would not think de-acylation  is a tRNA modification; certainly aminoacylation is not. 
The "editing" is not tRNA editing (post transcriptional changes of the sequence), it's a term used for the check by the synthetase for the correct amino acid. Some synthetases check at the first step (aa + ATP -> aa-AMP+ PPi) . Some check at the second step, aa-AMP +tRNA -> aa-tRNA + AMP.
It is a type of translational fidelity assurance.

**Comment by ValWood** [comment]
I figured that from
http://www.uniprot.org/uniprot/P0A6M4

so really its a "tRNA metabolism involved in translational fidelity"?

**Comment by hdrabkin** [comment]
Or an " aminoacyl-tRNA metabolism involved in translational fidelity”
I like to think of uses for a aa-TRNA
Translation (etc; elongation or iniation)
Cell wall biosynthesis (certain species)
Amino acid transfer (by  Aminoacyl tRNA-Protein Transferases)
This type of metabolism is not use per se  like 1-3.

Regular editing of what aa gets put on what tRNA is usually a property of the synthetases themselves.  So I guess if a D-amino acid gets by the synthetase (during aminoacylation), there is a second level of surveillance in some organisms.

**Comment by asangrador** [comment]
Therefore there seems not to be an existing GO term that we can apply for this biological process at the moment.  Something to look into.

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/12917

**Comment by ValWood** [comment]
Harold can you check that this ticket looks OK?

**Comment by hdrabkin** [comment]
I don't see an mgi annotation to  amino-acid catabolism; 

Please supply
1. PMID to use as reference
2. Suggested Definitgion
3. Suggested parentage

So I have something to work with

**Comment by ValWood** [comment]
Hi Harold,

I don't think this thread is about an MGI annotation, but I think we need your input. It seems that
https://github.com/geneontology/go-ontology/issues/12917
ticket being finalised might help if I re skim read correctly?

I probably put the comment
"Harold can you check that this ticket looks OK?" in the wrong ticket...

Val

**Comment by hdrabkin** [comment]
again; lost among github emails; I'll try to get to it today (12917) although I swore today I would devote to another project that I owe time to.

**Comment by hdrabkin** [comment]
done

**Comment by ValWood** [comment]
Harold, we  love you and we do not want to change you immediate priorities that would be unfair.   It could be  on your  "important" list for next week though ;)

....But, do all of my e-mails to you still go to spam?  This important (for me) to address  because  not very effective for me to  e-mail @ukemi  to tell you that I need to speak to you ;)

I   now wonder if  a lot of the "Git Hub communication between people problem"  might be due to institutional spam filters.  If  so GO should look into that...

Github should be whitelisted everywhere.... that might help communication

**Comment by ValWood** [comment]
@pgaudet

**Comment by cmungall** [comment]
It sounds like @hdrabkin was saying he gets so many github emails it's sometimes hard to find the ones that need his attention.

Everyone: github offers good controls as to what you get notified of and what you don't. You can subscribe at the level of ticket, or at the level of repo. If you choose "Not watching" you will still be notified if either you personally are `@`-mentioned, or a team you are part of is `@` mentioned: 

![image](https://user-images.githubusercontent.com/50745/33406369-62c65f88-d521-11e7-932a-72b45ea2ecf8.png)

**Comment by ValWood** [comment]
@cmungall Maybe this post should go on the GO discuss list ;)

**Comment by ValWood** [comment]
I get confused by the watching/ not watching thing...I find it ambiguous....

Even if I select  "Not watching" I *still* receive e-mails, even if I have *no* connection to the ticket (i.e not assignee, submitter or tagged) .

Maybe I need to tag "never be notified"  instead, but I do want to be notified if I am mentioned 
and I am not sure if I would.

( I could look up the difference but at present it's easier for me to delete irrelevant e-mails...but probably others do not feel this way...)

**Comment by happy-lorna** [comment]
I'm replying here as I don't think I can see the GO discuss list.
I agree there is a danger of messages being lost in a deluge of notifications. @cmungall you said it is possible to get notifications at the level of a team you are part of. Does such a team exist for InterPro? If not, how do I go about creating it? It would be super-useful for us (InterPro curators) to just pick up those messages that are tagged as InterPro.

**Comment by hdrabkin** [comment]
No you don't go into spam
So yesterday I dealt with geneontology/go-ontology#12917
SO please clarify what THIS ticket needs ?

**Comment by hdrabkin** [comment]
I already have it set to only send me assigned or mentioned. One of the confusing this on my end is that the email alert does not always identify who the message came from. So for example, 
the "happy-lorna' comment came to me as coming Val Wood. 
Then there are the notifications if comment only has one word (like 'thanks', etc.). Those I usually delete,

**Comment by ValWood** [comment]
so, the point here was to get a term to annotate
InterPro:IPR003732 D-amino acid catabolic process
and we were not sure what was suitable.

i.e the process for this MF
https://www.ebi.ac.uk/QuickGO/term/GO:0051499

can close for now as the problem mapping was removed. Once somebody is annotating one of these from a paper it might be easier to do...
