### ISSUE TITLE
EC:2.3.1.48 misapplication to  HPA3 | D-Amino acid N-acetyltransferase that detoxifies D-amino acids

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1494]
Is this involved in amino acid metabolism?
	Tetrameric histone acetyltransferase		D-amino acid metabolic process		GO_Central	Saccharomyces cerevisiae S288c	IBA	PANTHER:PTN001632122

	Tetrameric histone acetyltransferase		D-amino-acid N-acetyltransferase activity		GO_Central	Saccharomyces cerevisiae S288c	IBA	PANTHER:PTN001632122

http://amigo.geneontology.org/amigo/gene_product/SGD:S000006397

seems unlikely to be acetylating free amino acids?

**Comment by ValWood** [comment]
Comes from here so instead will query the original SGD annotation
http://amigo.geneontology.org/amigo/gene_product/SGD:S000000792

I would say this isn't a
	D-amino acid metabolic process (the amino acid is  modified before removal, not metabolised)
but it is detoxification of D-amino acids

**Comment by ValWood** [comment]
It is  acetylating free amino acids. The problem seems to be the histone acetyltransferase
EC number,I don't see any evidence for this? How do we get EC removed?

HPA3 | D-Amino acid N-acetyltransferase that detoxifies D-amino acids |   | histone acetyltransferase activity |   | UniProt | Saccharomyces cerevisiae S288C | IEA | EC:2.3.1.48

**Comment by pgaudet** [comment]
Hi @ValWood 
Which annotation are you disputing, histone acetyltransferase activity?

**Comment by ValWood** [comment]
yep, not physiologically relevant:
https://www.yeastgenome.org/reference/S000079786

**Comment by pgaudet** [comment]
OK thanks. Then SGD should also correct the ISS @srengel

**Comment by pgaudet** [comment]
Who maintains EC2GO?

**Comment by ValWood** [comment]
I don't see an ISS at SGD, 
https://www.yeastgenome.org/locus/S000000792/go#comp
only an IEA from PAINT?

**Comment by srengel** [comment]
HPA3 and HPA2 in Sc can both acetylate a range of substrates, not just histones.  http://www.jbc.org/content/288/30/21506.full.pdf

i have cleaned up the acetylation-related annotations for both proteins.  closing.
