### ISSUE TITLE
PANTHER and InterPro InterPro:IPR005121 PANTHER:PTN000711660 (PTHR11538)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1496]
Fdxacb1	ferredoxin-fold anticodon binding domain containing 1
http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:3584513

has annotations to
phenylalanyl-tRNA aminoacylation		UniProtKB	Mus musculus	IEA	InterPro:IPR005121
tRNA processing		UniProtKB	Mus musculus	IEA	InterPro:IPR005121
rRNA base methylation		GO_Central	Mus musculus	IBA	PANTHER:PTN000711660

It seems unlikely that all are correct. I'm not sure how to trouble-shoot this one.

(I think I submitted a related ticket earlier, but  none seems to match these family IDs)

Val

**Comment by pgaudet** [comment]
In the original annotation there is a NOT to 
phenylalanine-tRNA ligase activity(NOT) 	PANTHER:PTN001355900
phenylalanyl-tRNA aminoacylation(NOT) 	PANTHER:PTN001355900

There is a problem with how the data gets exported. 

- Pascale

**Comment by asangrador** [comment]
On the InterPro side, I will remove these annotations from IPR005121. They are wrong; this entry represents a domain found not only in phenylalanine-tRNA ligases, but also in other proteins.

Amaia

**Comment by pgaudet** [comment]
For Chris: 
The original data is here: 
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/paint/PTHR11538/PTHR11538.gaf?sortby=date&view=log

The species-specific file for mouse is here: 
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/paint/pre-submission/gene_association.paint_mgi.conf?sortby=date&view=log

Chris, is that what you needed ? 

Thanks, Pascale

**Comment by selewis** [comment]
Actually this looks like the NOT annotation was placed at too low a point in the tree. That mouse gene (MGI:3584513) is in a separate branch. The direct negation is to PTN000711660 and this mouse gene isn't a descendant.

**Comment by selewis** [comment]
Or perhaps it needs to be added to two different branches, though that would be less likely.

**Comment by ValWood** [comment]
There are still PAINT annotations,
I can't see any evidince that this is a phenylalanine-tRNA ligase activity or tRNA ligase...
http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:3584513


yeast ortholog
https://www.yeastgenome.org/locus/YIL096C
appears to be 
rRNA (uridine-N3-)-methyltransferase activity

**Comment by marcfeuermann** [comment]
This seems to have been corrected a while ago. The NOT annotation is now on PTN000711660.
