### ISSUE TITLE
InterPro:IPR000043	S-adenosylhomocysteine catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1497]
for ahcyl1 
S-adenosylhomocysteine catabolic process
does not seem to be correct?

http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:2385184

**Comment by asangrador** [comment]
You are right; the annotation will be deleted for this protein.

**Comment by ValWood** [comment]
Just to check, Was this deleted for the family?

**Comment by asangrador** [comment]
It  hasn't been deleted yet as our database is frozen for our next release (61.0) due at the end of this week. As soon as its done we will delete this annotation.

**Comment by ValWood** [comment]
OK, I wasn't sure if it was deleted for the family of the family suppressed for specific proteins. Got it.

val

**Comment by asangrador** [comment]
Just to clarify, it will be deleted for the whole family. And a new entry more specific for adenosylhomocysteinases that does not match ahcyl1 will be created (to avoid loosing annotations for  adenosylhomocysteinases)

Amaia

**Comment by asangrador** [comment]
The annotations have now been deleted from IPR000043.
