### ISSUE TITLE
GO camp annotation issues from ZFIN

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#15]
-ZFIN-

Areas for discussion at Cambridge GO camp:

PDFs of the 4 pubs cited in the following have been
sent to Mike Cherry.

1) How do we delimit a process?  Which gene products
are involved in the processwhich are not?  A general
discussion of this issue would be great.

Specific example (ZDB-PUB-040216-17 ; PMID:14757644)
Phillips BT et al. 2004. Development 131, 923-931.

Wnt8&lt;--&gt;fgf3/8 -&gt;otic placode/vesicle development

An epistatic relationship exists between wnt8 and
fgf3/8.   wnt8 regulates expression of fgf3 and fgf8
and vice versa.  Expression of fgf3/8 is necessary and
sufficient to induce formation of otic placodes and
vesicles.  Loss of fgf 3/8 expression blocks otic
vesicle formation.  Loss of wnt8 delays expression of
fgf3/8 and delays expression of preotic markers, but
otic vesicles form eventually.

a.  Should wnt8, fgf3 and fgf8 all be annotated with
otic vesicle formation?
b.  wnt8 increases expression of fgf3/8Is this positive
regulation of FGFR signaling pathway?
c.  What if a new pub comes along and shows that fgf3/8
are inducing expression of some other gene that is
required for otic visicle formation?

The decision to include a gene in a process seems
loosely defined and somewhat arbitrarily based on what
a paper publishes, how involvement in the process is
demonstrated, when it is published, and what else we
know about the process at the time.  

2) How are others handling the overlap between
phenotype annotation and biological process GO
annotation?  For example mutation of nic1
(muscle-specific Nicotinic AchR) results in abnormal
muscle fiber organization and motor axon extension. 
Phenotype annotations involve abnormal muscle and
axons, but should GO for nic1 only be regarding muscle
development/morphogenesis, since nic1 is not expressed
in the axon?  Involvement of nic1 in axon extension is
likely to be indirect, but users may reasonably expect
to find nic1 in a list of genes involved in axon
extension because of their familiarity with that
phenotype...

Similar to #1how do we delimit the process?  
Specific Example (ZDB-PUB-040510-5 ; PMID 15128655)
Lefebvre et al. 2004 Development 131(11): 2605-2618.

3) How do we annotate when a gene product has an
activity by itself (a homomeric ion channel complex for
example), but has altered activity or characteristics
in the presence of other subunits (heteromeric ion
channel complex for example)?  Does a protein that
forms a homomeric complex have a molecular function
itself or is it contributing to the function of a
complex?  
Specific Example (ZDB-PUB-040225-4 ; PMID 14970195)  
Paukert et al. 2004 JBC 279(18):18783-18791)
page 18788

4) How do we annotate when a process is compromised by
alteration of gene A (IMP), but the severity or
penetrance of the phenotype is modified by alteration
of gene A and gene B (IGI)?  This could be pairs of
morpholinos or mutants at multiple loci.  
Specific Example (ZDB-PUB-030304-12 ; PMID 12591239)
Lekven et al. 2003. Dev. Biol. 254(2):172-187.
Page: 182

What if we were dealing with multiple alleles of a
single gene (IMP?).

5) New GO term creation:  Should we create new terms
when a concept can be represented by several existing
terms?  Creating new terms vs. waiting for slots
approach?  Granularity of new terms?  General
discussion of what would make a new term desirable or
undesirable in the big picture would be good.

6) If authors claim a protein is a transmembrane
protein based on a hydrophobicity plot, is that ISS, NAS?

Reported by: doughowe

Original Ticket: "geneontology/annotation-issues/15":https://sourceforge.net/p/geneontology/annotation-issues/15

**Comment by linuxlovell** [comment]
thanks www.movied.org
