### ISSUE TITLE
review annotations to GO:0045251 electron transfer flavoprotein complex (or children)

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-annotation#1501]
From related ontology ticket: https://github.com/geneontology/go-ontology/issues/12895

http://amigo.geneontology.org/amigo/term/GO:0045251

@pgaudet : Birgit has found that this term is not appropriate for the annotation of acyl-CoA dehydrogenases.  There are over 200 PAINT based annotations to this term.   If any of those were based on experimental annotations of ETF-ubiquinone oxidoreductases or acyl-CoA dehydrogenases, such annotations should be removed. I'm not sure where the IBA annotations would have originated as the non-IEA annotations for this term and its children in other organisms are of the TAS/ISS/IC variety.  Maybe all of these annotations should just be removed.

@ukemi : There is one mouse TAS annotation to this term for Etfdh that might need (re)moving.  Can you check please?

**Comment by bmeldal** [comment]
In the original ontology ticket, please focus on my comments in my second comment (from 6th January) as it overrides the original suggestions (from 5th January). I did more digging!
