### ISSUE TITLE
rogue SPKW application

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1503]
Will collect old outstanding issues here:

~- [ ]  P20433 DNA-directed RNA polymerase II subunit RPB4
has  UniProtKB-KW-0234 (DNA repair)
outstanding from
https://sourceforge.net/p/geneontology/annotation-issues/1033/~

see
https://github.com/geneontology/go-annotation/issues/1803

**Comment by ValWood** [comment]
- [ ] AIMP1 Homo sapiens Q12904 to glucose metabolic process UniProtKB-KW:KW-0313
https://sourceforge.net/p/geneontology/annotation-issues/1159/

**Comment by ValWood** [comment]
- [ ] KW-0414 At least 5 False positives for pombe

**Comment by ValWood** [comment]
The following mappings to amino acid biosynthetic process seem too indirect. This sulphite assimilation. required for amino acid metabolism  but upstream.

O14172 SPAC4D7.06c  met8    GO:0008652  UniProtKB-KW:KW-0028
P78937 SPBC27.08c   sua1    GO:0008652  UniProtKB-KW:KW-0028
Q09878 SPCC584.01c  SPCC584.01c GO:0008652  UniProtKB-KW:KW-0028
Q1K9C2 SPAC10F6.01c sir1    GO:0008652  UniProtKB-KW:KW-0028
Q9USP8 SPBC902.05c  idh2    GO:0008652  UniProtKB-KW:KW-0028

**Comment by ValWood** [comment]
UniProtKB-KW:KW-0131		S. cerevisae	P25337	BUD31	cell cycle			indirect, splicing
UniProtKB-KW:KW-0131		S. cerevisae	Q06819	DIB1	cell cycle			indirect, splicing
UniProtKB-KW:KW-0132		S. cerevisae	Q06819	DIB1	cell division			indirect, splicing
UniProtKB-KW:KW-0498		S. cerevisae	Q06819	DIB1	mitotic nuclear division			indirect, splicing

**Comment by ValWood** [comment]
from
https://github.com/geneontology/go-annotation/issues/1348

triosephosphate isomerase P07669 GO:0006098	pentose-phosphate shunt	IEA UniProtKB-KW:KW-0570

**Comment by ValWood** [comment]
SPBC27B12.02 GO:0005739 IEA UniProtKB-KW:KW-0496 centromere protein Mis19/Eic1
SPCC970.07c GO:0005739 IEA UniProtKB-KW:KW-0496 Rik1-associated factor Raf2
SPCC338.16 GO:0005739 IEA UniProtKB-KW:KW-0496 F-box protein Pof3
SPAPB1A10.16 GO:0005739 IEA UniProtKB-KW:KW-0496 conserved fungal protein
SPCC4G3.13c GO:0005739 IEA UniProtKB-KW:KW-0496 CUE domain protein Cue1/4 family involved in ER associated protein catabolism (predicted)
SPCC548.06c GO:0005739 IEA UniProtKB-KW:KW-0496 hexose transmembrane transporter Ght8 (predicted)

from
https://github.com/geneontology/go-annotation/issues/1296

**Comment by ValWood** [comment]
KW:KW-0156 chromatin modification
rbx1
elp3
hip4
slm9
mis16
hip1
SPAC15E1.10

**Comment by ValWood** [comment]
UniProtKB-KW:KW-0560		oxidoreductase				P36596
(is a transferase)

**Comment by ValWood** [comment]
UniProtKB-KW:KW-0540		nuclease activity				P22193

**Comment by ValWood** [comment]
UniProtKB-KW:KW-0808		transferase		S.pombe	cys11	O59701
UniProtKB-KW:KW-0808		transferase		S.pombe	cys12	P87131
UniProtKB-KW:KW-0808		transferase		S.pombe	SPAC6G10.03c	O14249
UniProtKB-KW:KW-0808		transferase		S.pombe	ykt6	O60073
UniProtKB-KW:KW-0808		transferase		S.pombe	nat1	O74985
UniProtKB-KW:KW-0808		transferase		S.pombe	trp1	Q92370
UniProtKB-KW:KW-0808		transferase		S.pombe	rib4	Q9UUB1

**Comment by ValWood** [comment]
All indirect, upstream , phenotypes

UniProtKB-KW:KW-0159		S.pombe	Q9UTN4		chromosome segregation	
UniProtKB-KW:KW-0159		S.pombe	P40847		chromosome segregation	
UniProtKB-KW:KW-0159		S.pombe	Q9P7C8		chromosome segregation	
UniProtKB-KW:KW-0159		S.pombe	Q9USU1		chromosome segregation	

from 
https://github.com/geneontology/go-annotation/issues/1177

**Comment by ValWood** [comment]
UniProtKB-KW:KW-0415		S.pombe	P40383		karyogamy		and s cerevisiae	indirect phenotype	

see
https://github.com/geneontology/go-annotation/issues/1116

**Comment by ValWood** [comment]
KW-0238  no evidence for DNA binding

DNA binding		S.pombe		O13852
DNA binding		S.pombe		O14362
DNA binding		S.pombe		O94530
DNA binding		S.pombe		Q09769
DNA binding		S.pombe		O14362
DNA binding		S.pombe		O42934
DNA binding		S.pombe		Q9P6R8
DNA binding		S.pombe		O60158
DNA binding		S.pombe		O94530
DNA binding		S.pombe		P79011
DNA binding		S.pombe		O94416
DNA binding		S.pombe		O94704
DNA binding		S.pombe		O14210
DNA binding		S.pombe		P36627
DNA binding		S.pombe		Q9P7S9
DNA binding		S.pombe		O13852
DNA binding		S.pombe		Q9Y7I8

from
https://github.com/geneontology/go-annotation/issues/1103
https://github.com/geneontology/go-annotation/issues/1397

**Comment by ValWood** [comment]
KW-0493		microtubule		S.pombe		P40383	 also S. cerevisiae, presumably others	


from
https://github.com/geneontology/go-annotation/issues/1119

**Comment by ValWood** [comment]
Q09915 GO:0003746	 translation elongation factor activity IEA with KW-0251

**Comment by ValWood** [comment]
UniProtKB-KW:KW-0931 for
PomBase	SPCC1672.12c	get4		
PomBase	SPBC3D6.05	ptp4

**Comment by ValWood** [comment]
KW:KW-0507 has a lot of "off target" GO mappings see
https://github.com/geneontology/go-annotation/issues/1234

**Comment by ValWood** [comment]
cut8 P38937 has keyword mappings to transport and protein transport
(both incorrect)
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P38937
transferred from
https://github.com/geneontology/go-annotation/issues/916
(transport will be dealt with anyway if we disallow for direct annotation)

**Comment by ValWood** [comment]
KW-0046 examples P41878, P30821, P05219, Q09146

**Comment by ValWood** [comment]
Mapping to KW DNA replication appears to be incorrect for human Dtd1
UniProtKB-KW:KW-0235
(there are papers supporting this, but if I remember correctly  people who worked on DNA replication do not believe them, I asked around).

**Comment by ValWood** [comment]
KW:KW-0762
This UniProt Keyword is sometimes applied to gene products which are involved in carbohydrate derivative metabolism, rather than carbohydrate metabolism.

yea4 O74750 NST UDP-N-acetylglucosamine transporter (predicted)
rft1 O94302 Man5GlcNac2-PP-Dol translocation protein Rft1 (predicted)
pet3 Q10354 phosphoenolpyruvate transporter Pet3
vrg4 Q9UTK8 Golgi GDP-mannose transporter Vrg4 (predicted)

**Comment by pgaudet** [comment]
Hi @ValWood 
We were going to discuss this now, if you can join... 

Pascale

**Comment by ValWood** [comment]
Will close. If I find any that are not fixed I will open a new ticket
