### ISSUE TITLE
InterPro:IPR002616 InterPro:IPR004803 not biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1508]
delete 
biosynthetic process	
https://github.com/geneontology/go-ontology/issues/12920

add
tRNA-guanine transglycosylation
see
https://github.com/geneontology/go-ontology/issues/11905

**Comment by asangrador** [comment]
Thanks Val. Queuosine biosynthetic process was deleted from theses entries in November, but the changes have just became public today with release 61.0.  I have added tRNA-guanine transglycosylation to IPR004803.
