### ISSUE TITLE
PANTHER:PTN000205059  (PTHR11760) DNA repair and nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1509]
Is mapping a clearly cytoplasmic ribosome protein to nucleus and DNA repair.

seems to come from one source:
https://www.ncbi.nlm.nih.gov/pubmed/8641296

Is this likely to be physiological role? I can't see any further follow up since 1996......

**Comment by pgaudet** [comment]
Hi Val, 

I see several sources for the double activity: 
http://www.yeastgenome.org/locus/S000005122/overview
http://www.uniprot.org/uniprot/P62908
http://flybase.org/reports/FBgn0002622.html

PMID:7775413
PMID:8641296
PMID:11561734 
PMID:15707971
PMID:14706345
PMID:16737853
PMID:17560175
PMID:18610840

Are we talking about the same family ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Something a bit strange here:
Then I look in AmiGO, it is this family associated with RPS3
http://amigo.geneontology.org/amigo/gene_product/SGD:S000005122

But if I go back a page to here

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=isa_partof_closure:%22GO:0002181%22&fq=isa_partof_closure:%22GO:0006281%22

it's
30s/40s ribosomal protein s3 pthr11760
which makes much more sense?
?

**Comment by ValWood** [comment]
Maybe because there are 2 families. Anyway I see what you mean. This appears to have a repair role. I wonder why SGD did not make this annotation- will check. There could be evidence that this is not the physiological role if its an in vitro assay.....

**Comment by ValWood** [comment]
This one is OK.
SGD will add repair role BP annotation.
