### ISSUE TITLE
Large set of human  ribosomal proteins annotated to 	SRP-dependent cotranslational protein targeting to membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1511]
SRP-dependent cotranslational protein targeting to membrane
from 	Reactome:R-HSA-1799339
I don't think this is correct?  This is just about targeting part (SRP business)
Val

@deustp01 

UniProtKB:Q07020	RPL18
UniProtKB:P08708	RPS17
UniProtKB:P62081	RPS7
UniProtKB:Q9UNX3	RPL26L1
UniProtKB:P05388	RPLP0
UniProtKB:P84098	RPL19
UniProtKB:P15880	RPS2
UniProtKB:P36578	RPL4
UniProtKB:P46782	RPS5
UniProtKB:P46779	RPL28
UniProtKB:P46778	RPL21
UniProtKB:P46777	RPL5
UniProtKB:P46776	RPL27A
UniProtKB:P42677	RPS27
UniProtKB:P62851	RPS25
UniProtKB:P47914	RPL29
UniProtKB:P62424	RPL7A
UniProtKB:P05387	RPLP2
UniProtKB:P05386	RPLP1
UniProtKB:P50914	RPL14
UniProtKB:Q02543	RPL18A
UniProtKB:P61927	RPL37
UniProtKB:P83881	RPL36A
UniProtKB:P83731	RPL24
UniProtKB:Q02878	RPL6
UniProtKB:P40429	RPL13A
UniProtKB:P23396	RPS3
UniProtKB:P46781	RPS9
UniProtKB:P46783	RPS10
UniProtKB:P18621	RPL17
UniProtKB:P18077	RPL35A
UniProtKB:P48730	CSNK1D
UniProtKB:Q92901	RPL3L
UniProtKB:P63220	RPS21
UniProtKB:P63173	RPL38
UniProtKB:Q99567	NUP88
UniProtKB:P26373	RPL13
UniProtKB:P61353	RPL27
UniProtKB:P61313	RPL15
UniProtKB:P08865	RPSA
UniProtKB:P61254	RPL26
UniProtKB:P61247	RPS3A
UniProtKB:P60866	RPS20
UniProtKB:P25398	RPS12
UniProtKB:P30050	RPL12
UniProtKB:P18124	RPL7
UniProtKB:P61513	RPL37A
UniProtKB:P35268	RPL22
UniProtKB:P62987	UBA52
UniProtKB:P62979	RPS27A
UniProtKB:P62945	RPL41
UniProtKB:P62917	RPL8
UniProtKB:P62910	RPL32
UniProtKB:P62906	RPL10A
UniProtKB:P62753	RPS6
UniProtKB:P62750	RPL23A
UniProtKB:P62701	RPS4X
UniProtKB:P62899	RPL31
UniProtKB:P62891	RPL39
UniProtKB:P62888	RPL30
UniProtKB:P62857	RPS28
UniProtKB:P62854	RPS26
UniProtKB:P62847	RPS24
UniProtKB:P62841	RPS15
UniProtKB:P62829	RPL23
UniProtKB:P62273	RPS29
UniProtKB:P32969	RPL9
UniProtKB:Q9Y3U8	RPL36
UniProtKB:P39023	RPL3
UniProtKB:P27635	RPL10
UniProtKB:P39019	RPS19
UniProtKB:P62913	RPL11
UniProtKB:P22090	RPS4Y1
UniProtKB:P49207	RPL34
UniProtKB:P42766	RPL35
UniProtKB:P62280	RPS11
UniProtKB:P62277	RPS13
UniProtKB:P62269	RPS18
UniProtKB:P62266	RPS23
UniProtKB:P62263	RPS14
UniProtKB:P62249	RPS16
UniProtKB:P62244	RPS15A
UniProtKB:P62241	RPS8

**Comment by deustp01** [comment]
The problem here is that a complex consisting of a mRNA associated with a ribosome and with the first few residues of the encoded polypeptide interacts with the signal recognition machinery. As far as I know, while it's indeed the polypeptide that directly binds, the interaction only happens in the context of the whole complex. We couldn't figure out a way to both annotate the participation of the whole complex and exclude the ribosomal proteins from tagging with the GO bp term. We probably have to do something with a skip list. This will need some more thought.

**Comment by ValWood** [comment]
Mapping from Reactome still exists, but based on @deustp01  final comment it does not seem totally incorrect to make this annotation.

will close

**Comment by deustp01** [comment]
"... it does not seem totally incorrect to make this annotation." Channeling your inner David Botstein. OK - works for me.

**Comment by ValWood** [comment]
: ) now that's a scary thought!
