### ISSUE TITLE
When to annotate a 'target' to a process?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#1513]
Hi 
I never annotate what I consider a target of a process to the process term. However, it has occurred to me that there may be occasions when this should be done, or at least for participants. That is if we want GO to be used for HTP analysis.

For example when the extracellular matrix is being 'assembled' the proteins regulating the assembly process, eg transcription factors will be upregulated. But so to will the collagens. If someone does an analysis and has collagens upregulated then it is not unreasonable to expect the term 'extracellular matrix organisation' to be enriched. To be honest the majority of human collagens are associated with the GO term 'extracellular matrix organisation', only 12 are not, and I haven't checked to see if these are collagens which are not in the extracellular matrix. However, there may be other organization terms where we should consider associating the target with the term. 

In addition, I wonder whether the GO term record should include advice to annotate to the 'participants' in cases like this.  

Or do people think that annotation to the cellular component term: extracellular matrix is sufficient? Certainly the collagens interactions with other extracellular components are essential for extracellular matrix organisation.

Ruth

**Comment by pgaudet** [comment]
I think this should be limited to LEGO annotations.

**Comment by vanaukenk** [comment]
I agree that it would be a good exercise to model some of these processes in LEGO, but am also wondering if additional annotations to biological processes related to say, adhesion or tissue organization/development, would be helpful in capturing the role of molecules like collagens.  Basically, what is the end goal of the organization?

**Comment by pgaudet** [comment]
biological process ;)

**Comment by ValWood** [comment]
Hi Ruth,
Do you have an example of the experiments when you want to do this. I think we do this already,  if we can't get the target gene onto a function term (I thought everyone did as I see annotations of this type). Maybe I misunderstood what you mean?
Val
