### ISSUE TITLE
please check your GGT GO:0003840 gamma-glutamyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1514]
against this comment:
The gene family commonly referred to as gamma-glutamyl transferases (GGT) catalyze hydrolysis of gamma-glutamyl bonds in gamma-glutamyl compounds such as glutathione. In a test tube one can set up conditions in which the enzyme will transfer the gamma-glutamyl portion of the substrate to an acceptor molecule, but this requires non-physiologic conditions, including millmolar concentrations of an acceptor such as glygly. This reaction is used in assays to detect the presence of the enzyme, but is not a physiological function of members of the GGT family (PMC4388159), which should be annotated to a suitable hydrolysis term instead (e.g. glutathione hydrolase activity).

Affects
- [ ] CACAO @jimhu-tamu
- [x] RGD @slaulederkind 
- [ ] ECOwiki @jimhu-tamu
- [ ] Reactome @deustp01 
- [ ] UniProt @mcourtot 
- [x] SGD @srengel 
- [x] MTBBASE @rwst
- [x] TAIR @tberardini 
- [x] FlyBase @hattrill 
- [x] MGI @ukemi 

(too many for Protein2GO!)

This isn't physiological reaction,
Should use glutathione hydrolase activity= gamma-glutamyltranspeptidase activity

**Comment by ValWood** [comment]
Also please check you process annotations  are not in the "amino acid metabolic process" lineage, which is what alerted me.
Thanks!

**Comment by tberardini** [comment]
I updated the 1 TAIR IMP annotation.  While doing that, I noticed that there was a UniProtKB annotation to this GO term based on EC mapping.  

EC:2.3.2.2 > GO:gamma-glutamyltransferase activity ; GO:0003840
http://www.chem.qmul.ac.uk/iubmb/enzyme/EC2/3/2/2.html

As well as one based on INTERPRO to GO mapping:

https://www.ebi.ac.uk/interpro/entry/IPR000101
InterPro:IPR000101 Gamma-glutamyltranspeptidase > GO:gamma-glutamyltransferase activity ; GO:0003840

Should these mappings be revisited or has that been done and all is ok?

**Comment by hdrabkin** [comment]
Most of our annotations to these are IEA based; EC2GO or intepro2go. Either the mappings need to change OR UniProt needs to remove the EC number from their protein records.
But I found IDA, IMP, and one ISO; the ISO is from RGD, so they should fix their manual so we can lose it.
I'll fix the two manuals in a minute

**Comment by slaulederkind** [comment]
We've reannotated the only manual annotation to the term at RGD.

**Comment by hdrabkin** [comment]
ok, we'll pick that up next week!

**Comment by srengel** [comment]
our two genes DUG2 and DUG3 are annotated for BP to 'glutathione catabolic process', which is_a 'cellular modified amino acid catabolic process'.  

is this a no-no? or is that ok since it's not under "amino acid metabolic process"? 

please clarify.  thanks.

**Comment by ValWood** [comment]
reported mapping issues
https://github.com/geneontology/go-annotation/issues/1519 (and via uniprot helpdesk)
https://github.com/geneontology/go-annotation/issues/1518

@srengel glutathione catabolic process  is fine, 
(I think DUG1 is your catalytic subunit here? it does not have  GO:0036374 but it has a correct, though less specific annotation to omegapeptidase activity)

in fact
		glutathione hydrolase activity -> glutathione catabolic process 

could be an F-P link I think?

**Comment by almitchell** [comment]
Updated in InterPro. The replacement terms will be visible from release 62 onwards (mid-March)

**Comment by ValWood** [comment]
Thanks all!

I can't locate Jim's Github ID, or remember where the list is if anyone can help here?

Also I don't know who MTBBAse are?

**Comment by hattrill** [comment]
FB has one manual annotation that will be replaced in the next release.

**Comment by slaulederkind** [comment]
MTTBBASE: http://www.ark.in-berlin.de/Site/MTBbase.html

**Comment by ValWood** [comment]
Wow,  that's amazing!

**Comment by ValWood** [comment]
Hi all,

This term still has 4,711 for 4,685 proteins.
Most are IEA.

These are the remaining experimental annotations:
![remain](https://cloud.githubusercontent.com/assets/7359272/26492268/228336c0-420b-11e7-997b-9109fc831781.jpg)

Penelope Garmiri at uniprot has today fixed  P71828 asked if anyone is looking at the others.

I'm not sure if Melanie is still working on GOA? if not Penelope has offered to  look at these but does not want to duplicate effort.

The EC number will remain, as it is correct but we do not wnat the annotations for GO as they are non-physiological. How do we get an EC mapping removed.
The other IESa should gradually become replaced as the pipelines to generate annotations are re-run.


Although, if this reaction is *never* observed physiologically maybe the best  solution would be just to obsolete the GO term, then they will all go away.

Thoughts?
@pgaudet

**Comment by ValWood** [comment]
GO:0003840 was obsoleted in the end so all done here.
