### ISSUE TITLE
IPR016092 GO association update

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1515]
IPR016092 is associated with the GO term  iron-sulfur cluster assembly, however, it seems like the proteins listed in this entry (HesB, IscA, SufA and ErpA) are involved in the (directly) downstream process of GO:0097428	protein maturation by iron-sulfur cluster transfer.

Could this be updated? The pombe homolog of ISCA is currently getting an IEA to  iron-sulfur cluster assembly.

ISCA (red protein right hand side of diagram)
![screen shot 2017-01-18 at 16 54 47](https://cloud.githubusercontent.com/assets/12727506/22152246/eaf0f482-deef-11e6-9187-0de46c4c6288.png)

SufA / ISCA
![screen shot 2017-01-20 at 09 05 30](https://cloud.githubusercontent.com/assets/12727506/22152239/decac3d6-deef-11e6-8ed3-8d7da6618e8b.png)

ErpA
![screen shot 2017-01-20 at 09 07 08](https://cloud.githubusercontent.com/assets/12727506/22152238/dd0dc782-deef-11e6-8a25-6b970366e9ef.png)

**Comment by EBI-Hsinyu** [comment]
Hello, 

Thank you for the information. I have updated this entry and its children entries. This will be visible in InterPro 62.0. 

Hsin-Yu 
InterPro curator

**Comment by Antonialock** [comment]
thanks!
