### ISSUE TITLE
PTN001093729 regulation of mitochondrial translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1516]
The "Pan5" branch of the 2-dehydropantoate 2-reductase family 
is annotated to "regulation of mitochondrial translation" which seems incorrect for pan5 family. It seems to be coming from a  protein CBS2, which is not so closely related to the PAN5 branch (pombe does not have this protein). It might be an example of "duplication and divergence"

It seems unlikely that pan5 has any role in mitochondrial translation (pombe or cerevisiae).  In fact,  there is a very strong morphology phenotype associated with  fission yeast mitochondrial translation and the pan5 deletion does not have this phenotype.

**Comment by marcfeuermann** [comment]
It is indeed an example of "duplication and divergence". All annotation propagations from CBS2 have been removed.
