### ISSUE TITLE
EC:2.3.2.2 > GO:gamma-glutamyltransferase activity mapping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1519]
Hi,

Could you check this mapping against this ticket?

geneontology/go-annotation#1514 (comment)

thanks

val

**Comment by ValWood** [comment]
Note that the EC number-> mapping is OK.

But the EC number appears to be incorrectly applied to  glutathione hydrolases.

Sent this to Uniprot helpdesk.

**Comment by ValWood** [comment]
For record:
If I understood correctly, I think you are correct that  the EC number can still be applied.

I think I got my comment in this ticket the wrong way around
https://github.com/geneontology/go-annotation/issues/1519
I think I should have said, the EC number is OK but the mapping should be removed for GO.


If this is true:

The gene family commonly referred to as gamma-glutamyl transferases (GGT) catalyze hydrolysis of gamma-glutamyl bonds in gamma-glutamyl compounds such as glutathione. In a test tube one can set up conditions in which the enzyme will transfer the gamma-glutamyl portion of the substrate to an acceptor molecule, but this requires non-physiologic conditions, including millmolar concentrations of an acceptor such as glygly. This reaction is used in assays to detect the presence of the enzyme, but is not a physiological function of members of the GGT family (PMC4388159), which should be annotated to a suitable hydrolysis term instead (e.g. glutathione hydrolase activity).(Annotation comment on
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003840
gamma-glutamyltransferase activity
Catalysis of the reaction: (5-L-glutamyl)-peptide + an amino acid = peptide + 5-L-glutamyl-amino acid.
2.3.2.2
isn't a physiological reaction,  we should not use it because for GO annotation we are only concerned with physiologically relevant reactions and processes.

So what we want to do is remove the GO mapping between these entries and the EC number
2.3.2.2, not remove the EC number from the entry.

Let me know what you think,

**Comment by ValWood** [comment]
Hi David,

In the older ticket you commented
This mapping looks ok based on the definition.

This is true. The EC number is correct, and the mapping is correct.
These gene products can do this activity which means they get this EC number, but this only happens in vitro  under specific conditions and is not physiologically relevant.

I don't  know what we do in these cases,  other than delete the mapping to the  GO term,  because I can't remember an analogous situation......

If this activity *never* occurs physiologically, maybe we should delete the GO term instead? Then all of the confusion goes away?

**Comment by cmungall** [comment]
It looks like this term was obsoleted in https://github.com/geneontology/go-ontology/commit/521be1bff3352b3c53c818d7a0ed5b4f34d8ad2b

Is there anything remaining to be done?

We closed the linked annotation ticket, even though ecocyc, reactome, uniprot hadn't migrated
https://github.com/geneontology/go-annotation/issues/1514

We have also retained the following

id: GO:0102953
name: hypoglycin A gamma-glutamyl transpeptidase activity
namespace: molecular_function
def: "Catalysis of the reaction: glutathionate + hypoglycin A = L-cysteinylglycine + hypoglycin B." [EC:2.3.2.2, GOC:pz]
xref: EC:2.3.2.2
xref: MetaCyc:RXN-9157
is_a: GO:0016755 ! transferase activity, transferring amino-acyl groups

id: GO:0103068
name: leukotriene C4 gamma-glutamyl transferase activity
namespace: molecular_function
def: "Catalysis of the reaction: leukotriene C4 + a standard alpha amino acid = leukotriene D4 + an (gamma-L-glutamyl)-L-amino acid." [GOC:pz, PMID:1676842, PMID:9139674]
xref: EC:2.3.2.2
xref: MetaCyc:RXN66-336
is_a: GO:0016755 ! transferase activity, transferring amino-acyl groups

These are used by ecocyc for annotation of ggt:
https://biocyc.org/gene?orgid=META&id=EG10374#tab=GO

And uniprot (which  lists the EC:2.3.2.2 annotation first for the corresponding protein):

https://www.uniprot.org/uniprot/P18956

**Comment by pgaudet** [comment]
Hi @cmungall 

My understanding was that errors related to obsoleted terms would be in reports and people should fix that instead, so the tickets were redundant. isn't it ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Can close if obsoleted because any annotations or mappings will be fixed via that route
