### ISSUE TITLE
	transcription factor TFIIIB complex subunit  mapping to regulation 	IPR000812

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1522]
is involved in 
RNA polymerase III transcriptional preinitiation complex assembly 

currently maps to
GO:0006355	regulation of transcription, DNA-templated

and is directly involved rather than 'regulatory', it is required for this process to occur.

Could you change the mapping to reflect this (I am reviewing annotations to 'regulation of' with essentiality). If for some reason you can't use the mpore specific mapping could you make the mapping directly to the process rather than to the regulation term?

Thanks,

Val

**Comment by ValWood** [comment]
actually the problem might not be the InterPRO mapping, It might be the F-P link
Will check and feedback....

**Comment by ValWood** [comment]
I think probably both problems exist. You have a mapping, and there is an ontology link ;)

**Comment by asangrador** [comment]
I have removed the regulation of transcription, DNA-templated term and added GO:0070897 (DNA-templated transcriptional preinitiation complex assembly). I had to use a more general term that the one you suggested because this entry matches also proteins involved in PolII (and probably PolI in plants) transcription.

**Comment by ValWood** [comment]
Actually, I think regulation  was ok for this one ...
https://github.com/geneontology/go-ontology/issues/12985

**Comment by asangrador** [comment]
Thanks for then link to the discussion. I have added regulation of transcription, DNA-templated  and I'll leave the other term too, as it seems to be involved in both.

**Comment by ValWood** [comment]
yep!
