### ISSUE TITLE
InterPro:IPR024661 NOT GO:0006359 regulation of transcription from RNA polymerase III promoter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1524]
This one is required for (directly involved in)   "transcription from RNA polymerase III promoter"

Could this move up from the regulation term?
(These might seem unimportant, but you would lost this annotation of you filter the "regulates" relation)

**Comment by asangrador** [comment]
It has been changed now to "transcription from RNA polymerase III promoter".
