### ISSUE TITLE
	IPR018791 regulation of autophagy

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1527]
Hi,

although atg14 is involved in autophagy, I don't think other members (vps38) are...?

Val

**Comment by asangrador** [comment]
Hi Val,
This one is a bit tricky. The entry matches Atg14  from cerevisiae, Atg14L/Bakor and UVRAG  from metazoa, and Atg4 and Vsp38 from pombe. Vsp28 from pombe seems to be the quivalent of metazoan UVRAG and budding yeast Vps38 [PMID: 23950735]. In cerevisiae Vps38, resides in a PI3K complex distinct from the Atg14-containing complex and is dispensable for autophagy [PMID:11157979]. But this entry does not match Vps38 from cerevisiae, and the metazoan equivalent, UVRAG  , is involved in autophagy [PMID:16799551]. So is pombe Vps38 functionally equivalent to the budding yeast or metazoa? I think I am going to leave the annotation, and if it is wrong for pombe Vps38  we can filter it out?

**Comment by ValWood** [comment]
shouldn't the family be extended to include S. cerevisiae Vps38?

**Comment by asangrador** [comment]
I'll pass this one to Pfam so they can have a look at it.

**Comment by asangrador** [comment]
Hi Val,

Sara from Pfam has been looking into this and it was not possible to include S. cerevisiae Vps38 in the same family; it was not similar enough. Instead, a new family for cerevisiae VPS38 (based on the uniprot ID : Q05919) has been created  (PF17649) and it is now in a clan with ATG14 (PF10186, IPR018791). 
If you want any further details you can contact Sara.
Regarding the GO annotation, as far as mammalian UVRAG is involved in autophagy (PMID:20643123) , I will leave the annotation at the moment.

**Comment by pgaudet** [comment]
@ValWood 
Is there something else you'd like to do here?

**Comment by ValWood** [comment]
I need to check. I don't think vps38 is autophagy in pombe....

**Comment by ValWood** [comment]
I think the mapping should be removed, effects most likely indirect:

"In our published work (https://www.ncbi.nlm.nih.gov/pubmed/23950735), we showed that SPBC18H10.19/vps38 is dispensable for autophagy (Figure 2A, see main text at the beginning of page 5). Based on our unpublished observations, vps38 deletion may affect autophagy slightly but it is probably an indirect effect through a perturbation of the endosomal trafficking."

**Comment by asangrador** [comment]
Ok, I will remove the term. I found another protein matched by this entry that is probably not involved in autophagy neither (Q9VK07 from Drosophila), so better to remove it.
Thanks,
Amaia
