### ISSUE TITLE
IPR006694 	fatty acid biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1530]
includes C-4 methylsterol oxidase activity

which is ergosterol biosynthesis.

(lipid biosynthetic process might work...)

v

**Comment by ValWood** [comment]
actually i think lipid biosynthetic process might  be an incorrect parent for ergosterol so probably not...

**Comment by ValWood** [comment]
IPR014430 is similar.
sphingosine hydroxylase gets this mapping too.

**Comment by asangrador** [comment]
Done
