### ISSUE TITLE
Incorrect annotations to Human calmodulin coming from reactome

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-annotation#1533]
This aint right!

![image](https://cloud.githubusercontent.com/assets/112839/23024829/b712597a-f453-11e6-83fe-f31f03312ee0.png)

I can believe that calmodulin regulates these activities under some circumstance, but not that it has them!

**Comment by dosumis** [comment]
Another one:

![image](https://cloud.githubusercontent.com/assets/112839/23025222/11fb36d0-f455-11e6-8801-3263aab7f344.png)

Are these being propagated from the whole model to individual genes?

**Comment by dosumis** [comment]
Here's a link to the reactome model that the last annotation apparently comes from:

http://www.reactome.org/cgi-bin/instancebrowser?ID=5672965

**Comment by ValWood** [comment]
There are quite a few like this coming through in term matrix. I think @deustp01  is looking into the export rules for these....

**Comment by deustp01** [comment]
Haven't looked at these latest examples, but a general problem is that we make the regulation_of process X a part_of that process. That makes sense given our view of biology. We can avoid the collision with GO practice (X and its regulation are separate) by finer-grained assignment of GO biological_process terms to our events, assigning regulation BP terms to the ones we all agree are regulatory and straight process terms to events that we all agree are parts of the process.

The practical difficulty is that this requires manual re-annotation, so it happens as we notice (or, more likely, as you notice) and as time permits.

Action item - keep generating the comments, and we will follow up and fix.

**Comment by dosumis** [comment]
>  but a general problem is that we make the regulation_of process X a part_of that process

These are MFs.  Would you make a regulator of an MF a part of that MF?

**Comment by dosumis** [comment]
These are still an issue:

http://www.ebi.ac.uk/QuickGO-Beta/annotations?geneProductId=P62158&assignedBy=REACTOME&aspect=molecular_function

**Comment by dosumis** [comment]
More suspicious examples:

![image](https://cloud.githubusercontent.com/assets/112839/26704555/af1dd184-46e4-11e7-86a4-845ee98fc936.png)

**Comment by dosumis** [comment]
Not clear to me where in Reactome these are coming from:

![image](https://cloud.githubusercontent.com/assets/112839/23025222/11fb36d0-f455-11e6-8801-3263aab7f344.png)
I see no mention of CALM1 here:
http://www.reactome.org/content/detail/R-HSA-5672965

**Comment by pgaudet** [comment]
P62158 has no more Reactome annotations in AmiGO. Looks like this is fixed. 

Thanks, Pascale
