### ISSUE TITLE
InterPro:IPR033539 (Osteopontin) to GO:0001503 ossification not correct for dicty

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1536]
IPR033539 found in dicty, dicty doesn't have bones.

**Comment by almitchell** [comment]
Thanks - fixed.  

I think this is a side effect of the update to PANTHER 11.1 in InterPro - the PANTHER entry has expanded in taxonomic range in terms of sequences matched, but we didnt spot all of the conflicting GO terms. If you find any more, please let us know.
