### ISSUE TITLE
small GTPase mediated signal transduction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1537]
Not all GTPases are involved in signal transduction (for example membrane scission GTPases)

I think this (ERMES complex subunit) might also be one that is not...

GO:0007264	
small GTPase mediated signal transduction
IEA with IPR001806

**Comment by almitchell** [comment]
Thanks for picking this up, small GTPase mediated signal transduction deleted and replaced with GTPase activity. This will go live in our next release (mid-March).
