### ISSUE TITLE
Move annotations to 'meiotic cell cycle process' and 'meiotic cell cycle process'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1538]
Hello, 

There are 5 manual annotations and a few InterPro mappings to GO:1903047 'mitotic cell cycle process'; this term should not be used for annotation. Please replace by 'GO:0000278 mitotic cell cycle' or a child. 

There are some InterPro and PAINT annotations to GO:1903046 'meiotic cell cycle process'; this term should not be used for annotation. Please replace by GO:0051321 meiotic cell cycle or a child.

See https://github.com/geneontology/go-ontology/issues/13113 
Thanks, Pascale

**Comment by almitchell** [comment]
Hi Pascale,
Can you let me know the InterPro accessions that map to GO:1903047? I cant see any of these in the database, or in the audit tables, but I might be missing something.
We had 1 entry mapped to GO:1903046. I've changed this and it will be visible in our next release in about 2 weeks time.
Alex

**Comment by pgaudet** [comment]
Right, I misspoke, there are no InterPro2GO annotations.

Thanks, Pascale

**Comment by almitchell** [comment]
No worries
