### ISSUE TITLE
IPR000751 mapping to GO:mitotic M phase; GO:0000087

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1539]
Hi,

It looks like the following mapping to a cell cycle phase is in the InterPro2GO file:

InterPro:IPR000751 M-phase inducer phosphatase > GO:mitotic M phase ; GO:0000087

The cell cycle phase terms are in the gocheck_do_not_annotate subset, so perhaps a replacement mapping could be made using GO:1902751 positive regulation of cell cycle G2/M phase transition?

In C. elegans we have multiple cdc-25 genes, some of which are required for meiosis, so that is why I'm suggesting the more general regulation term rather than one specific to mitotic G2/M phase transition.

Many thanks,
--Kimberly VA

**Comment by asangrador** [comment]
Thanks for pointing out this. Our database is frozen for the next release, but terms will be changed as suggested and visible in the following release (63.0).

Amaia
