### ISSUE TITLE
redundant annotation from F-P links in Jenkins pipeline

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1544]
http://pombase2.aska.gen.nz/gene/SPCC1235.13
ght6

![f-pipeline](https://cloud.githubusercontent.com/assets/7359272/24514984/051ebee8-156e-11e7-83e4-875054ecec71.jpg)

(check "show details" to see the redundant annotation)

Here:

GO:1904659	glucose transmembrane transport IGI  with S000001136	Heiland S et al. (2000)

is created by the F-P pipeline, but is redundant with more specific annotation we already made from this paper (	glucose import across plasma membrane	)

Up until now I was convinced that we only got redundant annotation  if the annotation we had made had not reached GO, but in this case, our annotation is in AmiGO

http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC1235.13

Is the filtering not working (I'm sure that it did in the past? or am I mistaken?)

Val

**Comment by selewis** [comment]
Is part of this related to the issue of single step processes (
https://github.com/geneontology/go-ontology/issues/12859) ?because this
looks very like the problem that precipitated that request.

**Comment by kltm** [comment]
I believe that redundant annotation filtering is ongoing: https://github.com/geneontology/amigo/issues/43

**Comment by kltm** [comment]
If so, probably fine to close here with the above pointer.

**Comment by selewis** [comment]
Not if this only applies to Amigo. Where it also cause problems is in
PAINT.

Really need to remove the single-step processes because these are
inherently redundant (with the corresponding function class), and are
unhealthy as far as the ontology goes.

**Comment by kltm** [comment]
If PAINT is getting them from AmiGO/GOlr, the core ticket is still over there. You'd want to label this as an upstream issue if you keep it open.

**Comment by cmungall** [comment]
I prematurely closed as I thought this was an amigo ticket.

In fact it's about the F-P inference pipeline. I think we have this tracked elsewhere but am keeping open

**Comment by ValWood** [comment]
Yes its a separate issue from the single -step processes, and the redundency in AmiGO.

So here you are creating new (redundant) higher level experimental annotations. These are difficult for us to filter locally, because we only filter redundant IEA,IC, and TAS. We never "filter"  experimental annotations.
IIRC the pipeline did not used to create annotations  where a more specific Experimental annotation already exists from the same paper?

**Comment by ValWood** [comment]
Hi Suzi,

Although I largely agree about the single step processes (we hide them in PomBase when they don't add any value), sometimes they are useful, for annotation or grouping.

I wouldn't consider "x transmembrane transport" of a substrate to be a single step process in quite the same way. Take glucose transport for example.

The process of glucose  import is a collection of transporters that function together (high affinity, low affinity, different transporters are used in different environments). The process is the sum total of myriad transporters doing the same task in a different way. The transport process is the sum of these different single steps.

Therefore, these transport processes, even though they appear to be single-step at first glance, are actually a really useful biological process grouping term.
http://pombase2.aska.gen.nz/term/GO%3A0098708

**Comment by cmungall** [comment]
As discussed on the annotation call, we will first document the rules used to materialize the cross-branch links, and then discuss any specific filtering rules

**Comment by selewis** [comment]
Assuming that the rules for materializing these cross-branch links are
biologically valid (which I assume is safe to do, with the exception of the
redundant single-step processes that are a related, but different problem)
then I see no problem with always materializing them.

As I tried to explain on the call in most cases having a pile-up of
consistent evidence for a given role/function is of course useful. The
place where the multiple, (duplicative) annotations is not useful, in fact
annoying, is in the simple presentations like Amigo. In these cases all the
user wants to know is what functions a given GP has. If they want to see
all of the evidence then they could click to expand it. This also might be
the case in other situations where only a summary is desired. The fact that
we record separate annotations for the same function, but revealed in
separate papers is somewhat an historical artifact of our old friend the
GAF file.

**Comment by ValWood** [comment]
I missed the call when this was discussed but sensible filtering might be the way to go.
You can shield the user from a huge amount of annotation redundancy in this way.

We incorporate quite a lot of different types of annotation redundancy  filtering for gene page display.

1. NAS,TAS,IEA,IC experimental annotation code annotations are never presented (they do not add any value). 

2. We hide the evidence and source as Suzi suggests above, so if users want to see all of the sources they click to expand. On our current site we do this on a term by term basis.
On the new pages we also hide redundant parents
So, for cdc2 here MF
http://pombase2.aska.gen.nz/gene/SPBC11B10.09
you only see experimental data for less specific terms

e.g. GO:0097472	cyclin-dependent protein kinase activity
and GO:0004672	protein kinase activity
(historical but important papers) in the "full view"

3. We don't annotate directly to "phosphorylation" and other single-step process type terms *unless*  there is not enough information to make a molecular function term (for example, you don't know if a gene products is a kinase or phosphatase regulator). 

4.In addition and if there is no direct annotation we don't display the term from the function process link on the gene page. Behind the scenes for querying and enrichment the annotation still exists but it isn't necessary on the gene page if we have a "protein kinase" annotation. 

This means that we present the most biology relevant information in a non-redundant way...Maybe some of these filtering steps would be useful in AmiGO too.

cdc2 above is a complicated example because it has ~200 targets and is involved in many many processes during different cell cycle phases, so even the "non-redundant" version of the annotation will be pretty complicated.

A more "average" gene like a  mitochondrial ribosomal protein:
Filtering redundant annotation provides 3 simple annotations (4 if expanded to show evidence):
http://pombase2.aska.gen.nz/gene/SPBC211.01

These 3/4 annotations provide the same experimentally supported annotation as the 14  non-filtered:
http://www.ebi.ac.uk/QuickGO/GProtein?ac=O60186

Much easier for users to consume the information. This is all independent of Noctua/LEGO because at the end of the day, we still need to present gene specific information on gene pages...

**Comment by ValWood** [comment]
The additional redundant annotations created by the F-P pipeline are particularly annoying because they are redundant experimental annotations. We hide these in the summary view but they  are present in the full view even though we made a more specific annotation  to describe the same experiment. I have seen a few examples like this today.

Here 
![redundancy](https://cloud.githubusercontent.com/assets/7359272/25151460/9bea6ec6-247d-11e7-8d7b-620fcd19b2ea.jpg)

PomBase made
"calcium ion import across plasma membrane" for the "Ma et al" paper. The F-P links pipeline generates the redundant 
"calcium ion transmembrane transport" from the "stretch-activated calcium channel activity" from the same paper.  
 Here it would not be possible for the F-P link in the ontology to be more specific, but the  pipeline should be sophisticated enough to recognise the existing, more specific (or equivalent) experimental annotation from the SAME SOURCE/PUBLICATION.

It would remove quite  a lot of redundancy if this pipeline did not generate  an additional EXP annotations. This was the specific issue this ticket was about, but this is only one small aspect of redundancy. This is  generation of  excess existing annotations rather than possible options for filtering and display...

(Note that it is difficult for us to filter these locally because  they are experimental, and  they have the "PomBase" source)

**Comment by ValWood** [comment]
> (Note that it is difficult for us to filter these locally because they are experimental, and they have the "PomBase" source)


This might be the problem...I thought these were not present historically. This might be wrong. It could be that we used to be able to filter them because they had GOC as the source, but now they seem to have PomBase as the source?

**Comment by ValWood** [comment]
I'm confused by this...
we pull in more annotations from the F-P links
http://pombase2.aska.gen.nz/gene/SPCC548.07c
than I see in AmiGO
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC548.07c

I wonder if we are getting them from the wrong place?

**Comment by ValWood** [comment]
Here:

GO:0005353	fructose transmembrane transporter activity IGI  with S000002750	Heiland S et al. (2000)

is generating
GO:0015755	fructose transport IGI  with S000002750	Heiland S et al. (2000)

GO:0005355	glucose transmembrane transporter activity
is generating
GO:0035428	hexose transmembrane transport IGI  with S000002750	Heiland S et al. (2000)

from F-P links,

even though we already made the more specific
	GO:1990539	fructose import across plasma membrane IGI  with S000002750	Heiland S et al. (2000)

and
	GO:0098708	glucose import across plasma membrane IGI  with S000002750	Heiland S et al. (2000)

We update these annotations nightly, and they aren't new, but they aren't in AmiGO?

**Comment by ValWood** [comment]
I haven't been able to track down the  inference file via the GO website 
where does it live?

**Comment by ValWood** [comment]
Kim has pointed me to the location
http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/
so we are using the correct file.

The one above  which is not in AMiGO must be new F-P links, it isn't there because we are the authority and it wont be submitted until out next update.

The inferred annotations all have GOC as source, so we could potentially filter them locally, but not creating the redundant  EXP annotation  from the same publication would be better.  Am I correct that this used to happen?
Maybe it never did?

**Comment by ValWood** [comment]
to convince (myself mainly!)

From the current GAF
PomBase	SPCC1235.13	ght6		GO:1904659	PMID:10735857	IGI	SGD:S000001136	P	hexose transmembrane transporter Ght6	meu12	protein	taxon:4896	20121128	GOC		
PomBase	SPCC1235.14	ght5		GO:0015755	PMID:10735857	IGI	SGD:S000001136|SGD:S000004613|SGD:S000002753|SGD:S000001134|SGD:S000001138|SGD:S000002751|SGD:S000002750	P	hexose transmembrane transporter Ght5		protein	taxon:4896	20121128	GOC		
PomBase	SPCC1235.14	ght5		GO:0015992	PMID:10735857	IGI	SGD:S000001136|SGD:S000004613|SGD:S000002753|SGD:S000001134|SGD:S000001138|SGD:S000002751|SGD:S000002750	P	hexose transmembrane transporter Ght5		protein	taxon:4896	20121128	GOC		
PomBase	SPCC1235.14	ght5		GO:0035428	PMID:10735857	IGI	SGD:S000001136|SGD:S000004613|SGD:S000002753|SGD:S000001134|SGD:S000001138|SGD:S000002751|SGD:S000002750	P	hexose transmembrane transporter Ght5		protein	taxon:4896	20121128	GOC		
PomBase	SPCC1235.14	ght5		GO:0098655	PMID:10735857	IGI	SGD:S000001136|SGD:S000004613|SGD:S000002753|SGD:S000001134|SGD:S000001138|SGD:S000002751|SGD:S000002750	P	hexose transmembrane transporter Ght5		protein	taxon:4896	20121128	GOC	

but the more specific process annotations are the GO database, 
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC1235.13
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC1235.14

So the redundant annotations are created, this isn't a synching issue.

**Comment by cmungall** [comment]
@ValWood apologies, we're in mid-transition.

This is where they have been historically
https://build.berkeleybop.org/view/GAF/

As we change the pipeline as I outlined at the USC meeting, we have set up some new jenkins jobs. This one runs nightly and provides a snapshot of the release process:

https://build.berkeleybop.org/job/go-gaf-release-snapshot

All of your files are collected in one place:
https://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/pombase/

The F->P predications are:
pombase-gafcheck-prediction.gaf

**Comment by ValWood** [comment]
My issues here are resolved.The broader dicussion about hiding redundant TAS,NAS etc  is adressed elsewhere.

**Comment by ValWood** [comment]
I don't know if this was fixed. Still in the in gaf in the Jenkins location

**Comment by ValWood** [comment]
I'll close this ticket. The reason that I opened it is covered by
https://github.com/geneontology/go-site/issues/576
(there is a side issue mentioned by Susie which is to do with  annotations to single step processes). we should probably discuss these separately as there  is another issue about this.
