### ISSUE TITLE
[Protein2GO] Notification of annotation dispute concerning protein Q24574 (Dispute ID: 5833)  (PTHR24006)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1545]
external	5833	Helen Attrill	hla28@cam.ac.uk	This dispute concerns the GO term used	27-FEB-2017 19:20	38	REFG	GO Reference Genomes	Pascale.Gaudet@sib.swiss	protein	Q24574	*GO:0006284*	ECO:0000318	IBA	GO_REF:0000033	PANTHER:PTN000607280

external	5834	Helen Attrill	hla28@cam.ac.uk	This dispute concerns the GO term used	27-FEB-2017 19:20	38	REFG	GO Reference Genomes	Pascale.Gaudet@sib.swiss	protein	Q24574	*GO:0042981*	ECO:0000318	IBA	GO_REF:0000033	PANTHER:PTN000607280

Dispute ID: 5833
Nature of dispute: This dispute concerns the GO term used
Details:
Both of these terms appear to be propagated from downstream processes regulated by the activity of the deubiuitinase, rather than specific to the family. Could you review them?

**Comment by marcfeuermann** [comment]
The whole family (PTHR24006) has been updated, GO:0006284 and GO:0042981 do not appear anymore in the new version (PANTHER13).
