### ISSUE TITLE
Notification of annotation dispute concerning protein Q96GC9 (Dispute ID: 5876) (PTHR10281)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1546]
SOURCE	ENTITY TYPE	ENTITY ID	GO ID	EVIDENCE	ECO ID	REFERENCE	WITH	EXTENSION
REFG	protein	Q96GC9	GO:0010506	IBA	ECO:0000318	GO_REF:0000033	PANTHER:PTN000031590	

Dispute ID: 5876
Nature of dispute: This dispute concerns the GO term used
Details:
Hi Marc
please can you edit the source of this annotation and change to autophagy term and then propagate again
Thanks
Ruth

**Comment by marcfeuermann** [comment]
This has been done a while ago :-)
