### ISSUE TITLE
[Protein2GO] Notification of annotation dispute concerning protein P18858 (PANTHER:PTN000048794) PTHR10459

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#1547]
Dear Ruth Caroline Lovering,

A dispute that you initiated concerning an external annotation to protein P18858 on 22 Dec 2015 has been automatically resolved,
as it has been open for 450 days.

If you are happy that the issue raised in your dispute has been addressed, then you need take no further action. If, however, the issue still stands,
then you should contact the group responsible for the annotation (GO Reference Genomes) directly at Pascale.Gaudet@sib.swiss.

Details of the disputed annotation and your reason for raising the dispute, together with a link to the Protein2GO page for the protein affected, are given below.

If you have any concerns regarding the contents of this email, please contact goa@ebi.ac.uk; DO NOT REPLY to this email - it is sent from an unmonitored account.

Source Entity ID   GO ID      Evidence          Reference      With_string                                       Date
REFG   P18858      GO:0051103 ECO:0000318 (IBA) GO_REF:0000033 PANTHER:PTN000048794                              20150204

http://www.ebi.ac.uk/internal-tools/protein2go/dynamic.html?database=production#ac=P18858

Dispute reason:

Hi
please could you explain why this annotation is NOT, PMID:25879709 seem to be working on the assumption that LIG1 is able to repair DNA a statement from this paper: an alternative mechanism of repair occurs called long patch base excision repair (LP-BER), which involves the coordinated activities of Pol polymerase activity and 5 flap incision by flap endonuclease 1 (FEN1) for multiple nucleotide incorporation [22], [23] and [24]. The action of FEN1 results in a nick that is ligated by DNA ligase 1 (LIG1).
Thanks
Ruth

Dispute ID: 3861

**Comment by RLovering** [comment]
Hi Pascale 

I don't think this issue was addressed

Thanks

Ruth
@pgaudet

**Comment by RLovering** [comment]
Hi 
I don't think this has been addressed and it looks like this NOT annotation was the one listed as a BP NOT annotation included in the PAINT presentation today. Please could you look at this. The problem I have now is that I don't know what term this was associated with because these GitHub tickets do not link to a specific annotation, whereas the original Protein2GO disputes linked to a specific annotation.

I think the dispute is with GO:0051103 DNA ligation involved in DNA repair

Thanks

Ruth

**Comment by huaiyumi** [comment]
We checked AmiGO, P18858 has no IBA annotation to GO:0051103. The issue seems to be resolved already.
