### ISSUE TITLE
Gene associated with GO class (direct): 55180

### ISSUE THREAD

**Issue by rserrat** [geneontology/go-annotation#1548]
The following gene: Cnr1 can be associated with the GO class (direct): 55180 “mitochondrion”
The following Pubmed IDs validate the localization:
-	27828947 : Hebert-Chatelain et al., Nature 539(7630):555-559, 2016
-	22388959: Benard et al. Nature Neuroscience 15(4):558-64, 2012
-	27826249: Mendizabal-Zubiaga Front. Physiol. 7:476, 2016
-	24944910: Hebert-Chatelain et al Mol. Metab. 3(4):495-504, 2014)

**Comment by vanaukenk** [comment]
Hi @hdrabkin and @ukemi 

This looks to be a user request for annotation.  I took a quick look at some of the abstracts/titles and they mention mice, so have at least temporarily triaged this to MGI curators.  Let me know if it needs annotations from another group, as well.  Thx.

**Comment by hdrabkin** [comment]
PMID:27828947  not in mgi
PMID:22388959 in MGI J:181260 selected for GO not used, indexed to Cnr1
PMID:27826249 not in mgi
PMID:24944910 not in MGI
Will get the three missing PMIDS into our system.

**Comment by rserrat** [comment]
Thanks, a really fast response indeed.

If possible, I would be interested to know how the procedure will go for this annotation. How much time usually take to be actualized?

**Comment by hdrabkin** [comment]
We have a triage process; in this case, if the papers came in normally, it all depends on whether the gene in question would fall under one of our priority qc reports; in this case it would not, as the gene already had some manual annotation to all three GO branches. I have the papers now, and will be looking at them ahead of anything else. 
If I had all of them annotated today they would appear in a gaf or gpad maybe by Friday; if you are looking at the MGI web pages, next Tuesday would be a best guess

**Comment by ValWood** [comment]
human and mouse now have, closing
http://www.uniprot.org/uniprot/P21554#subcellular_location
