### ISSUE TITLE
IPR007690 Incorrect mapping to extracelular transport ?

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1550]
Hello, 

Based on the description I would suggest annotating IPR007690 to 
GO:0009306 	protein secretion
rather than to 
GO:0006858 extracellular transport

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, 
IPR005705 should perhaps be annotated to GO:0015774 polysaccharide transport, rather than 'extracellular carbohydrate transport'

**Comment by happy-lorna** [comment]
I have corrected these mappings as suggested. They will be visible in the next release.
Thanks Pascale!

**Comment by pgaudet** [comment]
Thanks Lorna :)
