### ISSUE TITLE
PAINT:   PTHR24373 (PTN001224703/PTN002392833)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1551]
Annotations from PANTHER:PTN001224703
to
extracellular space
proteinaceous extracellular matrix
for kek4/FBgn0032484

This references "SLIT RELATED LEUCINE-RICH REPEAT NEURONAL PROTEIN (PTHR24373)"
which is secreted, but seems to be hitting members of the Kekkon family in D.mel which are plasma membrane transmembrane proteins containing leucine rich repeats and Ig-domains.

Similarly for PANTHER:PTN002392833
kek5/FBgn0031016
axonogenesis

**Comment by marcfeuermann** [comment]
Kek4 is in PTHR24373 which contains many nodes. No more terms are propagated from one node to another. Only for few of them, the CC 'extracellular matrix' or 'plasma membrane' terms were kept. The annotation should disappear from kek4. 

Kek5 is in PTHR45842 in which 'axonogenesis' is no more present.
