### ISSUE TITLE
IPR016263 mapping to GO:0030435

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#1552]
Two E. coli sigma factors, FliA and RpoH, get the GO term GO:0030435, sporulation resulting in formation of a cellular spore, via its mapping to IPR016263.  However, E. coli does not sporulate.  I don't know whether the mapping to the GO term itself should be removed because it is too specific, or whether the IPR016263 family should be changed to somehow exclude sigma factors that come from non-sporulating organisms.  Clearly, based on the name of the family (RNA polymerase sporulation-specific sigma factor), the latter was intended, but I don't know if it turns out to be possible.  In any case, the current situation leads to a misannotation for E. coli sigma factors.

Thanks for looking into this,
Ingrid

**Comment by EBI-Hsinyu** [comment]
Hello Ingrid, 
Thank you for letting us know. After looking into this entry, we found this entry over-hits non specific Sigma factors, so we decided to delete this entry. Therefore, this GO term will be gone in our next release, which will happen in the next few weeks' time. 

Best regards, 
Hsin-Yu
