### ISSUE TITLE
in the inferred gaf, process annotations have "C" as aspect

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1553]
see for eg first line of pombe file

PomBase	SPAC1002.04c	taf11		GO:0006357	GO_REF:0000024	ISO	SGD:S000004477	C	transcription factor TFIID complex subunit Taf11 (predicted)		protein	taxon:4896	20050510	GOC	

from
https://github.com/pombase/website/issues/263#issuecomment-296146562

**Comment by cmungall** [comment]
My first hypothesis was that the pombase GAF already includes materialized F->Ps, thus non-presence in the file, but I have not had opportunity to check.

The various pombase files are here:

https://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/pombase/

If it's helpful, there is both a GAF format set of predictions and a report based on that:

 * [pombase-gafcheck-prediction-report.txt](https://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/pombase/pombase-gafcheck-prediction-report.txt/*view*/)
 * [pombase-gafcheck-prediction.gaf](https://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/pombase/pombase-gafcheck-prediction.gaf/*view*/)

The report is not as informative as it could be.

It looks like we have very few P predictions across all the contributing groups, needs investigating further...

**Comment by cmungall** [comment]
On cursory inspection I'm stumped. There is a junit test with a F->P test that explicitly checks aspect, and it passes. Nothing in the code has changed here, so unless this has always been an issue there must be some external factor. I suspected something to do with the switch from using oboedit and propagation of the namespace tag... yet that doesn't seem to be the case.

Will investigate more later

**Comment by ValWood** [comment]
Yep there are  processes in the file but they  have aspect "C". They appear to be loading for us. I presume that we don't get the aspect information form the gaf so it isn't breaking anything, but I guess it might for others....

**Comment by ValWood** [comment]
This might be related too....
Some  inferred links do not appear to be generated at all?
see
https://github.com/pombase/pombase-chado/issues/633


From
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051920#term=ancchart

http://preview.pombase.org/gene/SPBC17D11.03c
should get an annotation to
GO:0098869 cellular oxidant detoxification
and slim to cellular detoxification but it doesn't?

**Comment by ValWood** [comment]
Or even this one!
https://github.com/geneontology/go-annotation/issues/1336

**Comment by ValWood** [comment]
These processes now have aspect P instead of C.
Thanks!

**Comment by ValWood** [comment]
I'll close this but the other reported problem (some expected annotations not generated) is still present. I'll open a fresh  ticket for this....
