### ISSUE TITLE
IPR000971 oxygen binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1558]
for nitric oxide dioxygenase activity.

is technically correct but seems a little odd. We don't usually do this for reaction participants (hmm, except there is a precedent to do it for NTP). In fact this is the only oxygen binding annotation for pombe...

**Comment by EBI-Hsinyu** [comment]
Hello Val, 
Thanks for this. I have removed this term. 
Hsin-Yu
