### ISSUE TITLE
IPR006061: Incorrect mapping  to GO:0005215 transporter activity ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1562]
Hello, 

By the description in the InterPro record, and from PMID:23013274 (ugpB), this family appears to participate in transport by binding the ligand, but does not have transporter activity. I suggest this mapping be removed.

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hello Pascale, 
Thank you for this. I have deleted this term. 
Hsin-Yu

**Comment by pgaudet** [comment]
Great, thanks !
