### ISSUE TITLE
Establish an overall data flow for curators to correct/challenge/remove annotations as traceable issues

### ISSUE THREAD

**Issue by selewis** [geneontology/go-annotation#1563]
Proposal/requirements needs to be made.

**Comment by ValWood** [comment]
We have a reasonable system.  MAybe it could improve, but we can probably close this?

**Comment by pgaudet** [comment]
Sure. This is probably a ticket in some of the Noctua trackers.

**Comment by deustp01** [comment]
> This is probably a ticket in some of the Noctua trackers.

So the issue doesn't get lost again, could you find the Noctua tickets and link them to this one?

**Comment by ValWood** [comment]
I thought this tracker *was* the place to document annotation issues in a traceable way?

**Comment by pgaudet** [comment]
@deustp01 
https://github.com/geneontology/noctua/issues/361

**Comment by ValWood** [comment]
This ticket was originally about annotation issues, but the comment above seems to be about ontology structure?

From a personal perspective, implementing such a system might even be a bigger drain on already severely limited resources and result in even more tickets in people's inboxes. Active ontology developers apart from @pgaudet are only working ~1 day per week. That isn't very much time to make a dent in >700  open tracker tickets.  Although a large number of the tickets are closed quickly, the ones which remain are usually more difficult to address. However, they are grouped into projects so redundant tickets are usually spotted and closed.

I remember the days when there  more than 4+ full time ontology developers and probably fewer new tickets. Now that would be an interesting graph......

**Comment by ValWood** [comment]
For the annotation tracker it's a bit different. Most of the new ticket *are* resolved in a timely manner by the assignee. there is a good system in pace for this.

The legacy tickets are the problem, I guess we could just close them all but many seem to be in progress or forgotten, or unassigned, hence me prompting  people last week. This resulted in the closure of >100 tickets  (i.e. over 25% of the tracker).

Another round of prompting in a month or so, we might be able to close most of the legacy tickets. However, that depends entirely on the assignees answering the questions or making the  required fixes.....

These are the annotation tracker tickets which have a designated pathway to fix them:
is:issue -label:"annotation review" is:open -label:"InterPro mapping" -label:"PAINT annotation" -label:"UniProt KW2GO mapping" -label:ARBA -label:UniRule -label:"EC2GO mapping" -label:GO-CAM -label:UniProt -label:GPAD/GPI -assignee:pgaudet 

There are  now only 108 tickets  which still need  follow up
https://github.com/geneontology/go-annotation/issues?q=is%3Aissue+-label%3A%22annotation+review%22+is%3Aopen+-label%3A%22InterPro+mapping%22+-label%3A%22PAINT+annotation%22+-label%3A%22UniProt+KW2GO+mapping%22+-label%3AARBA+-label%3AUniRule+-label%3A%22EC2GO+mapping%22+-label%3AGO-CAM+-label%3AUniProt+-label%3AGPAD%2FGPI+-assignee%3Apgaudet+

either to be assigned to someone, or reassigned , or closed.
These are mainly for individual annotation fixes by various databases , and they seem to sometimes get forgotten about, or the person has left, of forgotten to close. 
Once I have another free evening I will go through the remainder, and after that we should be good going forward if GO assigns somebody to keep an eye on the tracker, and maybe as you suggest some sort of periodic automated reminder.
(but this will only work if the ticket is assigned to an active person).
