### ISSUE TITLE
check annotations to 'intermembrane transport' GO:0046909

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#1564]
As discussed in more detail here: https://github.com/geneontology/go-ontology/issues/12329 
please check your annotations to the term **'intermembrane transport'** GO:0046909, grouped below by what they look like they should probably be annotated to.

**'intermembrane lipid transfer'**
These are all to TTPA from some species and belong in 'intermembrane lipid transfer' as per this diagram: http://www.nature.com/nrm/journal/v11/n10/fig_tab/nrm2971_F1.html
- UniProt (1 IDA) - already changed within Protein2GO challenge system
-- UniProt (2 ISS) - should be fixed when IDA above propagates through
-- RGD (1 ISO) - should be fixed when IDA above propagates through
-- Ensembl (3 IEA) - should be fixed when IDA above propagates through

These EcoCyce ones might also be 'intermembrane lipid transfer'. The paper the figure above is from (PMID:20823909) mentions that lipid transfer proteins (LTPs) have been identified in bacteria, but I'm not sure if these are bacterial LTPs.
- EcoCyc (6 IGI + 6 NR) @jimhu-tamu 

**'vesicular transport'** - These annotations look like they should be moved to something related to 'vesicular transport'
- TAIR (1 TAS) @tberardini - suspect this belongs somewhere under 'vesicular transport' since the abstract mentions SNAREs

- PomBase (1 IMP) @ValWood  - already removed see: https://github.com/pombase/curation/issues/1215
-- AspGD (4 IEA) - should be fixed soon since based on PomBase annotation
-- CGD (4 IEA) - should be fixed soon since based on PomBase annotation

**Comment by tberardini** [comment]
TAIR annotation removed.

**Comment by krchristie** [comment]
Thanks @tberardini

**Comment by krchristie** [comment]
obsoletion done:
https://github.com/geneontology/go-ontology/commit/4295a13c9ab09825ae574a99b3c6c931f1e7c57f
