### ISSUE TITLE
panther annotation - PTHR10383

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1565]
http://www.yeastgenome.org/locus/S000002512/go
has

L-serine transmembrane transporter activity		IBA	GO_Central	2015-03-03		Gaudet P, et al (2010)

but I don't see any evidence for this being a tm transporter, could you check?

see also:
http://pfam.xfam.org/family/PF03348

**Comment by pgaudet** [comment]
Hi Val, 

Thanks for this, I removed the incorrect annotations. Perhaps 'transporter' would do, since it's sometimes described as a carrier. Primary annotations should be reviewed.

**Comment by ValWood** [comment]
Hi Pascale,

Not sure,
The paper which describes this as a carrier is this one:
http://www.jbc.org/content/280/42/35776.long

"Serine Palmitoyltransferase Activity—The reaction mixture contained 0.1 M HEPES, pH 8.3, 5 mM dithiothreitol, 2.5 mM EDTA, 50 μM pyridoxal 5′-phosphate, 0.2 mM palmitoyl-CoA, 1 mM [3H]serine (60 μCi), and the indicated amount of membrane proteins or cell lysates in a total volume of 0.3 ml. After incubation at 37 °C for 10 min, the reaction was terminated by the addition of 1.5 ml of chloroform/methanol (1/2). After 25 μg of sphinganine was added as carrier, the lipid products were extracted by the method described previously (22)."

so this doesn't appear to be referring to a "transporter type" carrier but something more like
this type of carrier
GO:0008897 - holo-[acyl-carrier-protein] synthase activity
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008897#term=ancchart
which isn't a transporter, its a transferase?

v

**Comment by pgaudet** [comment]
Hi Val, 

For me the transport branch is very non-intuitive. Most of that branch is duplicated in some way to allow both transmembrane transport and transport within the cell (I think this is what @thomaspd describes as 'carrier'). 

Right now the standard definition of 'transport' is "The directed movement of x, from one side of a membrane to the other into, out of or *within* a [cellular compartment]."

Biologically I would prefer to have 'carrier activity' limited to molecular function. The transmembrane transport seems to me a relevant biological process. I have another issue open with several questions about transport  #13356

What do you think ? 

Tagging @dosumis because he has done a lot of work on this already. 

Thanks, 

Pascale

**Comment by ValWood** [comment]
There are a class of mitochondrial transmembrane transporters that are referred to as "mitochondrial carriers"
https://en.wikipedia.org/wiki/Mitochondrial_carrier
although I use these names in the product as this is how the community refer to them, I use
mitochondrial x transmembrane transporter for GO annotation.

Another class of proteins (acyl carrier proteins) are referred to as carriers, but they are unrelated, and they are NOT transporters. These are the proteins which have a phosphopantethine group which acts as an attachment site for a substrate and  stops it from diffusing away from the active site. They are not directed because they are not involved in directed movement and I usually only annotate these to the catalytic activity of the enzyme. In theory they could be annotated to localization of the substrate but that isn't a very useful...

actually there is some history here about using "protein binding involved process...." 

 https://github.com/geneontology/go-ontology/issues/9416

I think the  L-serine transmembrane transporter activity above is probably one of this type of non-transporter/ non-transport carrier.

I think carrier should ONLY be used as synonyms for various in GO. I agree there is no need for anything referring to carrier in process.

**Comment by deustp01** [comment]
Serine Palmitoyltransferase is a transferase enzyme that catalyzes an early step in the process of sphingosine biosynthesis, so I don't think it qualifies as either a carrier (think of steroid binding protein associating with a hydrophobic steroid molecule and thereby enabling it to travel in aqueous environments in the body) or a transporter (think of a protein that forms a selective channel in a lipid membrane, enabling a hydrophilic small molecule to traverse that membrane).

I guess the protein in question could also have one of these two roles, but I don't think the paper cited gives any evidence for that.

**Comment by ValWood** [comment]
> a carrier (think of steroid binding protein associating with a hydrophobic steroid molecule and thereby enabling it to travel in aqueous environments in the body) 

Ah so that is another (3rd) use of the word "carrier".

**Comment by pgaudet** [comment]
Hi @deustp01 @ValWood 

Thanks for all the input. I disputed the annotation, it's an HGNC annotation, I am not sure who the contact person is at HGNC now.

Pascale

**Comment by pgaudet** [comment]
Hi @RLovering 
I see you have made these annotations (back in 2005) (Q7TNK0); can you remove them ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

thanks for spotting this. I have removed the annotation and replaced it with protein binding, bridging term. Are you also going to alert InterPro to this?

Best

Ruth

**Comment by ValWood** [comment]
hi Ruth
There is no InterPro mapping for this. I was only using the Pfam entry to try to explain that it wasn't a TM transporter.
http://www.ebi.ac.uk/interpro/entry/IPR005016

Val

**Comment by RLovering** [comment]
Hi Val

yeah there are 
Serinc1 http://www.ebi.ac.uk/interpro/entry/IPR029552 
Serinc2 InterPro:IPR029554
Serinc3 InterPro:IPR029557
Serinc5 http://www.ebi.ac.uk/interpro/entry/IPR029555

plus the serine transport annotations with this records

see http://www.ebi.ac.uk/QuickGO/GAnnotation?tax=9606&a=&goid=GO%3A0015194&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&protein=&qualifier=&ref=&evidence=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal 

Ruth

**Comment by ValWood** [comment]
Ah ok I missed those, they proably aren't in yeast...

**Comment by ValWood** [comment]
tagging Hsin-Yu @EBI-Hsinyu & Amaia @asangrador

**Comment by dosumis** [comment]
> For me the transport branch is very non-intuitive. Most of that branch is duplicated in some way to allow both transmembrane transport and transport within the cell (I think this is what @thomaspd describes as 'carrier').

This ticket is about a transporter (MF), rather than transport (BP).  Transport just  covers any process by which some entity moves.   Transmembrane transport could be passive (via a channel) or active (via an active transporter). Within a cell it could be via vesicular transport.  It could be along a microtubule, it could involved some carrier protein....

> Right now the standard definition of 'transport' is "The directed movement of x, from one side of a membrane to the other into, out of or within a [cellular compartment]."

Here's the parent class definition:  "The directed movement of substances (such as macromolecules, small molecules, ions) or cellular components (such as complexes and organelles) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter, pore or motor protein."

Part of the aim of patternising this branch would be to make this consistent.

> Biologically I would prefer to have 'carrier activity' limited to molecular function.

That would be a *very* radical change to the whole branch.

**Comment by ValWood** [comment]
I know the problem  Pascale is referring to very well. 

![image](https://user-images.githubusercontent.com/7359272/27260323-fe38084a-5420-11e7-9b6f-7b34dae6f8d6.png)

So, there are multiple "types" of transport.  These include
i) transmembrane
ii) intermembrane
iii) vesicle mediated (aka trafficking)
iv) targeting(to membrane)
vi) microtubule mediated
vi) the one Peter mentioned "a carrier (think of steroid binding protein associating with a hydrophobic steroid molecule and thereby enabling it to travel in aqueous environments in the body)" ..........NOTE we do not have BP transport term for this type of transprt in GO. 

So I think the problem Pascale is referring to an be illustrated by the  pic above.

Many  substrate transport terms exist,  with a non-transport type specific term, and a transmembrane transport term, even if transmembrane transport is the only known mechanism of transport.

So, for example here we have
"caroxylic acid transport" and
"tricarboxylic acid transport" even though these are transported  only by tansmembrane transport as far as we know?
This occurs right through the transport branch.
Many curators annotate to these none-specific terms like "cation transport" "glucose transport"
and not to the appropriate "transmembrane transport" term.

One solution would be to review and,  merge  these "redundant terms"
A better way to handle this might be to make all of the non-mechanism specific terms "not for direct annotation". This would force curators to ensure they are selecting the correct and most specific terms, which would improve annotation. In a while a merge could be considered if no problems were encountered (i.e non-transmembrane type transport of such a molecule exists)

We  have an internal rule that for transport  it should always specify the transport type, and we have a few "sterol transport" annotations which break this rule. To fix this we would require 
 a BP  term  for "carrier-type transport in aqueous environments"

**Comment by dosumis** [comment]
> A better way to handle this might be to make all of the non-mechanism specific terms "not for direct annotation". This would force curators to ensure they are selecting the correct and most specific terms, which would improve annotation. In a while a merge could be considered if no problems were encountered (i.e non-transmembrane type transport of such a molecule exists)

That sounds sensible to me.   The issue you describe is really an annotation issue - rather than any  inconsistency in the way the ontology is built.  The general import/export terms that don't specify a location have a similar issue.

> We have an internal rule that for transport it should always specify the transport type, and we have a few "sterol transport" annotations which break this rule. To fix this we would require
a BP term for "carrier-type transport in aqueous environments"

Seems reasonable to request, as long as you can make a case for other proteins being involved besides the carrier (pretty sure you can in this case).

**Comment by pgaudet** [comment]
Created new ticket to address the ontology issue:
https://github.com/geneontology/go-ontology/issues/13679
