### ISSUE TITLE
amino acid transporters

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1568]
I noticed   when checking the PAINT file that  a few pombe amino acid transporters now have specificity annotated from PAINT. 

These have a many:many and the S. cerevisiae proteins that they are related to, they have likely suplicated and diverged many times  since the species split. So for example pombe
SPBC460.01 and paralogs  have many to many S. cerevisiea orthologs with different specificities (the S. cerevisie  proteins are more similar to each other than to any of the pombe ones.

The problem is that the specificity  is determined by a very small number of residues (possibly even a couple), so specificity can change rapidly and in a convergent manner.

![f4430f1e-7dd5-11e6-8622-0df9e89bee56](https://user-images.githubusercontent.com/7359272/27185334-e7b6ac70-51dc-11e7-8c19-20b26ec064de.jpg)

I think "amino acid transporter/transport" which is all that can be reasonably  inferred.

Could these annotation be revised/reviewed?

**Comment by ValWood** [comment]
I just transferred this from the PomBase tracker, but now I check the gaf, I think ti was already adressed

**Comment by pgaudet** [comment]
Hi Val, 

When you submit these queries, if you can please have a PTHR or a PTN ID that would be really useful. In this case it looks like you're talking about 
http://pantherdb.org/panther/family.do?clsAccession=PTHR43341
which is not yet curated ! 

Thanks, Pascale

**Comment by ValWood** [comment]
I closed this because I  could not track  the problem in the current GAF. But often I see these  in SGD with IBA  an the paint paper reference but I don't see the actual family ID, and I don't know how to track it down from the presented information....

**Comment by pgaudet** [comment]
I see. SGD doesn't display the 'with' for the IBAs. AmiGO and QuickGO do, but I can look for them, no worries. 

Pascale

**Comment by ValWood** [comment]
Oh yes, I can do it that way.
Anyway I downloaded the PAINT gaf yesterday for more info and SPBC460.01 was not in it so I closed.
