### ISSUE TITLE
IPR034586 mitotic spindle orientation checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1569]
This checkpoint is not present in fission yeast. It is required in budding yeast because the spindle has to be orientated to get though the bud neck. I'm not sure if it is present in any medially dividing cells?

**Comment by EBI-Hsinyu** [comment]
Hello Val,

Thank you for this. I have deleted this GO term. 

Regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
Val, I am closing this. 

- Pascale
