### ISSUE TITLE
Query  GO:0032066 nucleolus to nucleoplasm transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1571]
This issue arises form 
https://github.com/geneontology/go-ontology/issues/13686

Val writes: 
The nucleolus is not a separate compartment as such

nucleolus
Ontology Cellular Component
Definition A small, dense body one or more of which are present in the nucleus of eukaryotic cells. It is rich in RNA and protein, is not bounded by a limiting membrane, and is not seen during mitosis. Its prime function is the transcription of the nucleolar DNA into 45S ribosomal-precursor RNA, the processing of this RNA into 5.8S, 18S, and 28S components of ribosomal RNA, and the association of these components with 5S RNA and proteins synthesized outside the nucleolus. This association results in the formation of ribonucleoprotein precursors; these pass into the cytoplasm and mature into the 40S and 60S subunits of the ribosome.

...and I'm not aware of a transport mechanism between the two ... This has only 3 EXP annotations
UniProtKB Q14191 WRN IDA PMID:11420665 MGI
UniProtKB Q3YBR2 TBRG1 IDA PMID:17110379 HGNC
UniProtKB Q9Y3T9 NOC2L IDA PMID:20123734 UniProt

@ukemi 
@RLovering 
@sylvainpoux

would you please check your annotations and see if this term is required? 

Thanks, Pascale

**Comment by ValWood** [comment]
to clarify, should say 
of a transport mechanism between the  nucleolus and  nucleoplasm 
(context in other ticket)
v

**Comment by pgaudet** [comment]
Hi @RLovering 
@hdrabkin 

I think the term 'GO:1902570 protein localization to nucleolus' would be more appropriate; is that OK for you ? I could do a merge. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Yes, the authors refer to  'nucleolar localization' , so I think that will be safe.

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14690

**Comment by pgaudet** [comment]
I closed this but I realized that the BHF and MGI annotations are still there. 

Pascale
