### ISSUE TITLE
 IPR002130 protein folding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1574]
peptidyl-prolyl cis-trans isomerase activity
is not always  "protein folding"

see also
https://github.com/geneontology/go-annotation/issues/545
https://github.com/geneontology/go-annotation/issues/1559

v

**Comment by asangrador** [comment]
Yes, this entry matches a variety of PPIases, and not all are involved in protein folding, so I will remove this term.
Cheers,
Amaia
