### ISSUE TITLE
GCV3 SGD:S000000042 protein lipoylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1575]
http://amigo.geneontology.org/amigo/gene_product/SGD:S000000042

Is lipoylated, rather than involved in? @srengel 

also 	
- [ ] RGD:1600115 via ISS @slaulederkind 
- [ ] human via ISS http://www.uniprot.org/uniprot/P23434 
- [x] http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBP19A11.01 (fixed)

**Comment by ValWood** [comment]
I could not tag goa for Uniprot as there are no contact details in this list:
https://github.com/geneontology/go-ontology/blob/master/curator_group_contacts.tsv

**Comment by srengel** [comment]
Hi Val,
The authors do find that Gcv3p is lipoylated, but also that it is required for the lipoylation of the other two targets. I'm inclined to leave the annotation for GCV3.

Look at pages 23239-40 for a lot of statements and explanation.

in a nutshell:
"We conclude that Gcv3, a target of lipoylation, is absolutely required for lipoylation of Lat1 and Kgd2. That a target of lipoylation is required for lipoylation is a novel result that suggests a level of regulation in yeast not previously recognized in the well studied prokaryotic system."

**Comment by srengel** [comment]
oh here's the paper: http://www.jbc.org/content/284/35/23234.full.pdf

**Comment by ValWood** [comment]
OK I'll add that back!
It sounds like the lipolated  Gvc3  is some sort of lipoate donor....

Thanks,

Val
