### ISSUE TITLE
Some expected  inferred links do not appear to be generated ?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1576]
From
pombase/pombase-chado#633

From
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051920#term=ancchart

http://preview.pombase.org/gene/SPBC17D11.03c
http://pombase2.aska.gen.nz/gene/SPBC17D11.03c (last nights build)

should get an annotation to
GO:0098869 cellular oxidant detoxification
and slim to "cellular detoxification" but it doesn't?

**Comment by ValWood** [comment]
Is it because the 	"peroxiredoxin activity" is linked to the process term through "antioxidant activity"?

**Comment by ValWood** [comment]
Hi @cmungall  you probably don't see tickets on the annotation tracker if not assigned to you.
Probably I should move this  to website thracker?

So I'm still not getting expected inferences....

**Comment by cmungall** [comment]
The code is configured to skip IEAs by default:

```
PomBase SPBC17D11.03c   SPBC17D11.03c           GO:0051920      GO_REF:0000002  IEA     InterPro:IPR003779      F       conserved fungal protein                protein taxon:4896      20170114        InterPro  
```

I'm not sure when this decision was made or who made it, it does not seem the right one, but someone probably told Heiko to do this at some point and he did it.

Moving forward, we need to document everything within its own gorule, then we will have a full audit trail of any changes of decision:

https://github.com/geneontology/go-site/tree/master/metadata/rules

We don't have a rule for F->P at all...

**Comment by ValWood** [comment]
Closing, this was because F-P links skip IEAS, (although these would be useful, why is that?)
