### ISSUE TITLE
Merge response to low-density lipoprotein particle stimulus and its cellular equivalent ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1578]
Hello @BarbaraCzub @RLovering 

The term 'cellular response to low-density lipoprotein particle stimulus' has a parent term 'response to'. However other terms in the neighborhood don't have a 'response' equivalent. 

Can I merge the 'response to' into 'cellular response to'? 

There are 4 annotations by UCL-BHF: 

P41233	Abca1	NOT	GO:0055099	response to high density lipoprotein particle	Process	IMP	PMID:15210959	-	10090	20091209	BHF-UCL
P78536	ADAM17	-	GO:0055099	response to high density lipoprotein particle	Process	IDA	PMID:17786981	-	9606	20081121	BHF-UCL
Q64343	Abcg1	-	GO:0055099	response to high density lipoprotein particle	Process	IDA	PMID:15210959	-	10090	20091209	BHF-UCL
Q8K4E1	Abcg4	-	GO:0055099	response to high density lipoprotein particle	Process	IDA	PMID:15210959	-	10090	20091209	BHF-UCL

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
the only response is cellar response, I think. If organ response is considered cellular response, 
Ruth

**Comment by BarbaraCzub** [comment]
Hi @pgaudet I have also just had a look at these annotations and it appears that they had been made before the 'cellular response...' terms were created. And from the abstracts of the reference papers it appears that the annotated studies involved cellular responses indeed.

**Comment by pgaudet** [comment]
OK, so I will merge. 

Thanks, Pascale

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14675
