### ISSUE TITLE
IPR020605 octanoyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1579]
Hi,

could you check this?
I think it should be
lipoyl(octanoyl) transferase activity?

see:
https://github.com/geneontology/go-ontology/issues/13722#issuecomment-311075142

thanks

val

**Comment by asangrador** [comment]
I  have removed the annotation from this entry (it is a conserved site). Proteins will get the annotation from the family entry IPR000544, which has the correct annotation: lipoyl(octanoyl) transferase activity.
Cheers,
Amaia
