### ISSUE TITLE
redundant annotations created by F-P  inferred link pipline

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1580]
I reported this before but I think it is has got a bit buried. Here is a clear example:

I annotated to
	DNA-directed 5'-3' RNA polymerase activity
and
        transcription from RNA polymerase I promoter

inference  pipeline creates less specific  "RNA biosynthetic process"

(	GO:0006360	
transcription from RNA polymerase I promoter is a descendant of 	
RNA biosynthetic process, and more accurate for the gene product)

so we get this:
![annoying](https://user-images.githubusercontent.com/7359272/27551532-b8bb5bba-5a9b-11e7-9a97-de69fcbdaecb.jpg)

We try to annotate non-redundantly and but we are pulling getting lots of redundant annotations.
In addition, these are often also often  to terms we would not annotate too because we can always be more specific. I can filter these out and I'd like to do this, but then I lose the ability  to check if it's fixed.

Let me know if anyone is looking at it..if not I'll probably go ahead and filter the annotations on loading.
cheers,

val

**Comment by ValWood** [comment]
I don't see this now

**Comment by ValWood** [comment]
I wasn't looking at the right file.... Will re-check when I know where the file lives

**Comment by pgaudet** [comment]
@ValWood any update ?

**Comment by ValWood** [comment]
Can be closed but note that thisa a good example
https://github.com/geneontology/go-annotation/issues/1674
