### ISSUE TITLE
IPR005686 protein channel

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1582]
Hi,

I'm not sure that it is correct to describe
mitochondrial outer membrane translocase complex
as a "protein channel activity"
because it is defined
"Enables the energy-independent facilitated diffusion, mediated by passage of proteins through a transmembrane aqueous pore or channel." [GOC:rb]

the usual activity for these is
P-P-bond-hydrolysis-driven protein transmembrane transporter activity
(energy dependent).

That said, I'm not sure what would use "protein channel activity"

PomBase only other annotation is this one
http://preview.pombase.org/gene/SPCC16A11.09c
which I am deleting now.....

I'm not sure what we would use this for...

**Comment by ValWood** [comment]
All EXP annotations are from SGD Tim and Tom complex @srengel

**Comment by ValWood** [comment]
I forgot about this ticket
https://github.com/geneontology/go-ontology/issues/13251

**Comment by asangrador** [comment]
Hi Val,
If I have not misunderstood, and looking at geneontology/go-ontology#13251 (which mentions that the The TOM complex seems to only have channel activity,) it seems that "protein channel activity" would be OK for this entry as it represents TOM40.
Amaia

**Comment by srengel** [comment]
hi Val,
yeah i'm not sure what you are asking us to do here.  are you saying the protein channel annotations at SGD need to be changed to GO:0015450 - P-P-bond-hydrolysis-driven protein transmembrane transporter activity?

**Comment by ValWood** [comment]
Hi Stacia,

I think its probably primarily an ontology issue:
https://github.com/geneontology/go-ontology/issues/13251

TOM complex are sometimes annotated to channel, and sometimes to 
P-P-bond-hydrolysis-driven protein transmembrane transporter activity

These are in different branches and are describing the same activity (for TOM).

I wouldn't worry about this ticket until any relationship issues in the ontology are fixed.
Will ping this ticket when the "upstream one" closes.

**Comment by ValWood** [comment]
This should be automatically fixed by clarification here:
https://github.com/geneontology/go-ontology/issues/13251

**Comment by happy-lorna** [comment]
Thanks Val.
Yes, looking at the GO term and description as it stands now, I think the annotation is fine.
