### ISSUE TITLE
PTN000271860: PAINT ADA2-related issues 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1583]
For the nodes populated for PTN000271860, I am wondering whether the transcription factor terms are appropriate. This is a subunit of HAT complexes, rather than a transcription factor per se.
Term: transcription factor activity, sequence-specific DNA binding
There is some early evidence for interactions with transcription factors, so perhaps co-activator is ok, but it doesn't seem to feature much in current thinking.

**Comment by pgaudet** [comment]
Hi @hattrill 
It seems clear in the literature that SAGA is considered a co-factor: 
http://genesdev.cshlp.org/content/28/18/1999.long

There are several primary annotations; I suggest that you dispute the primary annotations; what do you think ? 
@Tanya AT4G16420
@srengel S000002856 (+Candida: CAL0000192402)

Thanks, Pascale

**Comment by ValWood** [comment]
The problem is that although SAG is considered a cofactor, it completely fits the GO def of TF in that it both 1) binds DNA  (ada subunit has a DNA binding domain)  and 2) Regulates transcription.

This  implies that the  def of trancription factor needs refining. Not all types  of transctiptional regulation + DNA binding = "transcription factor"

**Comment by ValWood** [comment]
I'm basing this on the fact that  ADa2 has a homeobox. Maybe it does not bind DNA, but for sure some  chromatin remodelling type co-factors do. I always felt that  something else was required in the def

**Comment by krchristie** [comment]
With respect to definition of "transcription factor", also remember that not all transcription factors bind DNA.

**Comment by hattrill** [comment]
Well, I guess it is ok - looking at enhanceosomes, etc. seems that many have HAT activity.

**Comment by ValWood** [comment]
I checked last night and SAGA binds to TBP and RNA pol II, so co-factor fits for this.

We still have an issue that other non co-factor chromatin remodellers also fit the DNA binding TF def .....

**Comment by hattrill** [comment]
And, some domains e.g. SANT-MYB, MADF-BESS and ARID domains pop up in cofactors, DNA binding TFs and remodellers.

**Comment by pgaudet** [comment]
@hattrill @ValWood 
So, can this issue be closed ? It doesnt seem to be a problem with the annotations of the family. 

Thanks, Pascale

**Comment by hattrill** [comment]
I am ok with closing this.

**Comment by srengel** [comment]
seems like nothing here to do for Sc ADA2.  please let me know if i have misunderstood.

**Comment by pgaudet** [comment]
Right, I dont think so, the annotations were right.
