### ISSUE TITLE
IPR034735 Change mapping ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1584]
Hello, 

I came across this while working on the ontology issue: https://github.com/geneontology/go-ontology/issues/12787

In PMID: 19763089, it sounds like the best term for this mapping would be 
'K63-polyubiquitin modification-dependent protein binding' (GO:0070530; I just renamed, the former name is : K63-linked polyubiquitin binding )

What do you think ? 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Thank you for this. I have added 'GO:0070530' to this entry. IPR034735 represents the C-terminal Zinc Finger (ZF) domain of NEMO. Together with the NOA/UBAN domain, the ZF domain  is contributing  to  K63-specific ubiquitin binding (PubMed:19763089). 

Regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
Great, thanks !
