### ISSUE TITLE
InterPro:IPR016710 mapping to glycoprotein binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1585]
Hello, 

In the ontology issue https://github.com/geneontology/go-ontology/issues/12787
we have decided that modified protein-binding should actually be differential binding that occurs only when the modification is present in the target protein. I am not sure this is the case for IPR016710; can you please have a look ? 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 

I am not sure this entry (IPR016710) is the best example for this. The 'glycoprotein binding' term was given due to a paper describing that Emp46 can bind porcine thyroglobulin (contains high mannose-type sugar chains) in vitro. No other glycoprotein binding data is available the moment. 

Regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
Dear @EBI-Hsinyu 

I am not sure my request was clear. Based on what you replied it sound like IPR016710 binds glycoprotein but it's not clear that the binding is dependent on the modification. I have merged glycoprotein with glycoprotein, which sounds consistent with your reply. 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi, I'm now still confused by this (I wasn't at the meeting).
So when you say "dependent on the modification" do you mean that the modification needs to be present (in which case all  existing glycoprotein binding annotations would be OK), or the sugar moiety is the part of the glycoprotein that is bound?

**Comment by pgaudet** [comment]
@ValWood : I mean that the binding must *only* occur when the modification is present, ie that the modification is required for the interaction. 

In the case of the glycosylation-moiety binding we might want to capture the binding site (ie the glycosylated part). 

Is that clearer ?

**Comment by ValWood** [comment]
OK, I think so. But  for all of these type of terms you would only use them if the modification is present. So would you need to know that the binding would not occur unless the modification if  present? I don't think you would have data to exclude, the dependency can only be assumed if direct binding to the moiety is not demonstrated?

**Comment by pgaudet** [comment]
>So would you need to know that the binding would not occur unless the modification if present?
Yes. We put a comment regarding this: "This term should only be used when the binding is shown to require a post-translational modification: the interaction needs to be tested with and without the PTM. The binding does not need to be at the site of the modification. It may be that the PTM causes a conformational change that allows binding of the protein to another region; this type of modification-dependent protein binding is valid for annotation to this term."

>  I don't think you would have data to exclude, the dependency can only be assumed if direct binding to the moiety is not demonstrated?
I am not following, can you please rephrase ?

**Comment by ValWood** [comment]
So, what I'm trying to say is,
For glycoproteins it is unlkely that we would ever be able to make an annotation. I can't think of a case where an experiment would  show that
i) a glycoprotein is bound
ii) the same protein is not bound if the  glycosylated residue was absent.

**Comment by pgaudet** [comment]
Hi Val, 

Right - unlike phosphorylation and ubiquitination, I think glycosylation is pretty much constitutive, so we probably need to deal with this differently. There are two questions: 
1. Do we want to express the binding to the sugar modification itself ? Some of the annotations seem to capture that.
2. Otherwise, we are only capturing something about the interactor, ie that it is glycosylated. Is there something more relevant biologically, for example interacting with secreted protein or ...? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't know. Maybe others can comment in the other ticket (which one was that, I can't find it?). I removed our annotations as they weren't absolutely necessary. I don't really have any other example experiments....but it might be worth clarifying to avoid future problems.

**Comment by ValWood** [comment]
see https://github.com/geneontology/go-annotation/issues/1586

**Comment by srengel** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/?term=16439369

This paper shows what Val was asking about: glycoprotein bound, then not bound if glycosylation absent.

**Comment by ValWood** [comment]
closing because "glycoprotein binding" appears to no longer exist

**Comment by pgaudet** [comment]
Right, this was merged into 'protein binding'.
