### ISSUE TITLE
Glycoprotein binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1586]
Dear all, 

I am implementing the proposal agreed up on at the last GOC meeting to rename terms like '(post-translationally-modified-protein binding' to 'modification-**dependent** protein binding'. If a protein binds a modified protein but the dependency on that modification is not known, then the guidelines are to simply use 'protein binding. 

For 'glycoprotein binding', there are about 100 annotations, which as far as I can tell, the dependency on the modification was not assayed. Therefore I am merging 'glycoprotein binding' with 'protein binding'. If you would like, you can move your annotations to the new term 'GO:0140032 glycosylation-dependent protein binding'. 

Affected groups: 

BHF-UCL ParkinsonsUK-UCL @RLovering  
PomBase @ValWood @mah11 
UniProt @sylvainpoux
MGI @ukemi 
SGD @srengel 
FlyBase @hattrill 
AgBase 
RGD 
EcoCyc 
CAFA

Here's the list of EXP annotations: 
UniProtKB	D6PZR1	-	-	GO:0001948	glycoprotein binding	Function	IMP	PMID:7679512	-	9031	20150515	AgBase
UniProtKB	F1NBL0	MUC6	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:5119791	UniProtKB:Q98UI9	9031	20170210	AgBase
UniProtKB	F1NQ19	-	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:24488493	UniProtKB:B3VMQ8,UniProtKB:E1C600,UniProtKB:Q6PW00|UniProtKB:B3VMQ8,UniProtKB:E1C600,UniProtKB:Q90768|UniProtKB:E1C600,UniProtKB:P70069,UniProtKB:Q6PW00|UniProtKB:E1C600,UniProtKB:P70069,UniProtKB:Q90768	9031	20150916	AgBase
UniProtKB	G3V6K6	Egfr	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:21349584	RGD:2307	10116	20110428	RGD
UniProtKB	G3V8U0	Cd6	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:12525577	RGD:2309	10116	20100819	RGD
UniProtKB	O00238	BMPR1B	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:24904118	UniProtKB:Q30201	9606	20150424	BHF-UCL
UniProtKB	O35824	Dnaja2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:16774738	RGD:3410	10116	20110113	RGD
UniProtKB	O74739	png1	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:18279662	-	284812	20111116	PomBase
UniProtKB	P01009	SERPINA1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:20477988	UniProtKB:Q12907	9606	20140519	UniProt
UniProtKB	P01130	LDLR	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:10571240	UniProtKB:Q60841	9606	20111118	BHF-UCL
UniProtKB	P01137	TGFB1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:15247411	UniProtKB:Q6EMK4	9606	20140519	UniProt
UniProtKB	P01730	CD4	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:10922058	UniProtKB:P03375	9606	20060116	UniProt
UniProtKB	P02676	FGB	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:7642629	UniProtKB:P23142	9913	20150501	UniProt
UniProtKB	P02749	APOH	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:9269765	UniProtKB:P08519	9606	20080402	BHF-UCL
UniProtKB	P02786	TFRC	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:9465039	UniProtKB:Q30201	9606	20150424	BHF-UCL
UniProtKB	P02786	TFRC	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:9546397	UniProtKB:Q30201	9606	20150604	BHF-UCL
UniProtKB	P02786	TFRC	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:9990067	UniProtKB:Q30201	9606	20150710	BHF-UCL
UniProtKB	P03995	Gfap	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:20797626	UniProtKB:P13473-1	10090	20151020	ParkinsonsUK-UCL
UniProtKB	P04275	VWF	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:16409464	-	9606	20070327	UniProt
UniProtKB	P05107	ITGB2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:16831868	UniProtKB:Q15762	9606	20081127	BHF-UCL
UniProtKB	P05852	tsaD	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:20824107	-	83333	20100921	EcoCyc
UniProtKB	P06239	LCK	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:14625311	UniProtKB:P08575	9606	20060116	UniProt
UniProtKB	P06239	LCK	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:15554700	UniProtKB:P10747	9606	20060116	UniProt
UniProtKB	P06239	LCK	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:7513706	UniProtKB:P04216	9606	20060116	UniProt
UniProtKB	P06239	LCK	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:8650207	UniProtKB:P37198	9606	20090511	UniProt
UniProtKB	P06241	FYN	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:16831868	UniProtKB:Q15762	9606	20081127	BHF-UCL
UniProtKB	P06494	Erbb2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:15499570	RGD:621331	10116	20061101	RGD
UniProtKB	P08670	VIM	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:19420356	UniProtKB:Q9BX97	9606	20140107	UniProt
UniProtKB	P08709	F7	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:3455766	UniProtKB:P13726	9606	20090416	BHF-UCL
UniProtKB	P08921	Cd2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:11981840	RGD:2309	10116	20050217	RGD
UniProtKB	P11021	HSPA5	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:20477988	UniProtKB:Q12907	9606	20140519	UniProt
UniProtKB	P11215	ITGAM	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:15004192	UniProtKB:P04216	9606	20060103	UniProt
UniProtKB	P11717	IGF2R	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:10900005	-	9606	20091210	UniProt
UniProtKB	P11762	Lgals1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:10814697	RGD:3451	10116	20071127	RGD
UniProtKB	P11762	Lgals1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:10814697	RGD:3860	10116	20071127	RGD
UniProtKB	P12273	PIP	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18930737	UniProtKB:P25311	9606	20131205	UniProt
UniProtKB	P12830	CDH1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:23086448	UniProtKB:P15529	9606	20140218	UniProt
UniProtKB	P12960	Cntn1	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:19458237	-	10090	20101217	MGI
UniProtKB	P14735	IDE	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:17055432	UniProtKB:Q9J3M8	9606	20120606	UniProt
UniProtKB	P18418	Calr	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:12401114	RGD:3848	10116	20130111	RGD
UniProtKB	P18828	Sdc1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:8769660	UniProtKB:P24821	10090	20100315	MGI
UniProtKB	P20936	RASA1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:8618896	UniProtKB:Q13501	9606	20120131	UniProt
UniProtKB	P21333	FLNA	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:1833070	-	9606	20080914	BHF-UCL
UniProtKB	P21333	FLNA	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:3138234	-	9606	20090714	BHF-UCL
UniProtKB	P25311	AZGP1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18930737	UniProtKB:P12273	9606	20131205	UniProt
UniProtKB	P26006	ITGA3	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:24220332	UniProtKB:P48509	9606	20140812	UniProt
UniProtKB	P27177	PRNP	-	GO:0001948	glycoprotein binding	Function	IMP	PMID:7679512	-	9031	20150515	AgBase
UniProtKB	P27797	CALR	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:15056662	UniProtKB:P30460	9606	20140516	UniProt
UniProtKB	P32851	Stx1a	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:7553862	-	10116	20090324	MGI
UniProtKB	P34058	Hsp90ab1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18644871	UniProtKB:P17046	10116	20160615	ParkinsonsUK-UCL
UniProtKB	P35565	Canx	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:12401114	RGD:3848	10116	20130111	RGD
UniProtKB	P36894	BMPR1A	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:24904118	UniProtKB:Q30201	9606	20150424	BHF-UCL
UniProtKB	P47515	pdhB	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:12787366	-	243273	20160629	CAFA
UniProtKB	P47516	pdhA	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:12787366	-	243273	20160629	CAFA
UniProtKB	P47543	gapA	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:12787366	-	243273	20160629	CAFA
UniProtKB	P47819	Gfap	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:20797626	UniProtKB:P13473-1	10116	20151020	ParkinsonsUK-UCL
UniProtKB	P48030	Tgfa	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:15572151	-	10090	20050322	MGI
UniProtKB	P49134	Itgb1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18658130	RGD:3886	10116	20100607	RGD
UniProtKB	P51882	Cd5	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:11981840	RGD:2297	10116	20050830	RGD
UniProtKB	P51882	Cd5	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:12525577	RGD:2312	10116	20050217	RGD
UniProtKB	P60905	Dnajc5	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:16774738	RGD:3410	10116	20110113	RGD
UniProtKB	P61107	Rab14	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:18429929	-	10116	20090406	RGD
UniProtKB	P61769	B2M	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:9465039	UniProtKB:Q30201	9606	20150424	BHF-UCL
UniProtKB	P61769	B2M	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:9546397	UniProtKB:Q30201	9606	20150604	BHF-UCL
UniProtKB	P61769	B2M	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:9990067	UniProtKB:Q30201	9606	20150710	BHF-UCL
UniProtKB	P82995	Hsp90aa1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18644871	UniProtKB:P17046	10116	20151019	ParkinsonsUK-UCL
UniProtKB	P97633	Csnk1a1	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:8973207	-	10116	20080919	RGD
UniProtKB	P98155	VLDLR	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:10571240	UniProtKB:Q60841	9606	20111118	BHF-UCL
UniProtKB	Q01102	Selp	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:8562500	-	10090	20071025	MGI
UniProtKB	Q04589	Fgfr1	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:19952283	-	10116	20100521	RGD
UniProtKB	Q06486	Csnk1d	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:8454611	-	10116	20080919	RGD
UniProtKB	Q07113	Igf2r	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:2963825	UniProtKB:P04095	10090	20080131	MGI
UniProtKB	Q12396	EMP46	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:16439369	-	559292	20060210	SGD
UniProtKB	Q12907	LMAN2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:20477988	UniProtKB:P01009	9606	20140519	UniProt
UniProtKB	Q13438	OS9	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:18264092	-	9606	20090903	UniProt
UniProtKB	Q13438	OS9	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:19346256	-	9606	20090907	UniProt
UniProtKB	Q5FVU4	Cd6	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:12525577	RGD:2309	10116	20100819	RGD
UniProtKB	Q5S007	LRRK2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:21307259	UniProtKB:Q9JIS5	9606	20140513	ParkinsonsUK-UCL
UniProtKB	Q61330	Cntn2	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:19458237	-	10090	20101217	MGI
UniProtKB	Q62226	Shh	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:11476578	-	10090	20091123	MGI
UniProtKB	Q62351	Tfrc	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:16893896	UniProtKB:P70387	10090	20150424	BHF-UCL
UniProtKB	Q62761	Csnk1g1	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:7759525	-	10116	20080919	RGD
UniProtKB	Q62762	Csnk1g2	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:7759525	-	10116	20080919	RGD
UniProtKB	Q62763	Csnk1g3	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:7759525	-	10116	20080919	RGD
UniProtKB	Q62844	Fyn	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:8103744	RGD:2307	10116	20100517	RGD
UniProtKB	Q62844	Fyn	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:8870703	RGD:3860	10116	20100513	RGD
UniProtKB	Q6AYS3	Ctsa	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:12505983	UniProtKB:P17046	10116	20151014	ParkinsonsUK-UCL
UniProtKB	Q6PD21	Shb	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:8302579	-	10090	20100430	MGI
UniProtKB	Q6ZVN8	HFE2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:22728873	UniProtKB:Q30201	9606	20150424	BHF-UCL
UniProtKB	Q77Q67	UL1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:11448035	UniProtKB:Q8JLV0	10390	20150602	AgBase
UniProtKB	Q80UW2	Fbxo2	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:15723043	-	10090	20050901	MGI
UniProtKB	Q80UW2	Fbxo2	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:15809437	-	10090	20080812	MGI
UniProtKB	Q812A4	Cd6	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:12525577	RGD:2309	10116	20100819	RGD
UniProtKB	Q8BJT9	Edem2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:24200403	UniProtKB:P02879	10090	20150609	ParkinsonsUK-UCL
UniProtKB	Q8IWF2	FOXRED2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:21359175	UniProtKB:Q9P2K2	9606	20140530	UniProt
UniProtKB	Q8JLV0	gH	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:11448035	UniProtKB:Q77Q67	10390	20150602	AgBase
UniProtKB	Q8NI29	FBXO27	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:18203720	-	9606	20100625	UniProt
UniProtKB	Q924X6	Lrp8	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:10571240	UniProtKB:Q60841	10090	20111118	BHF-UCL
UniProtKB	Q925U4	Edem1	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:24200403	UniProtKB:P02879	10090	20150609	ParkinsonsUK-UCL
UniProtKB	Q96B86	RGMA	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:22728873	UniProtKB:Q30201	9606	20150424	BHF-UCL
UniProtKB	Q96DZ1	ERLEC1	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:16531414	-	9606	20090903	UniProt
UniProtKB	Q96EF6	FBXO17	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:18203720	-	9606	20100625	UniProt
UniProtKB	Q96PG8	BBC3	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:26212789	UniProtKB:P13473	9606	20151008	ParkinsonsUK-UCL
UniProtKB	Q98UI9	MUC5B	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:5119791	UniProtKB:F1NBL0	9031	20170210	AgBase
UniProtKB	Q9BYF1	ACE2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18343844	UniProtKB:P59594	9606	20080519	BHF-UCL
UniProtKB	Q9BYF1	ACE2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18343844	UniProtKB:Q6Q1S2	9606	20080519	BHF-UCL
UniProtKB	Q9GZZ8	LACRT	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:11419941	-	9606	20081013	UniProt
UniProtKB	Q9JI92	Sdcbp	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:11152476	UniProtKB:P20241	10116	20100908	RGD
UniProtKB	Q9JKX3	Tfr2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:16893896	UniProtKB:P70387	10090	20150424	BHF-UCL
UniProtKB	Q9PSP5	-	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:8063820	-	9031	20150623	AgBase
UniProtKB	Q9QX70	Egfr	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:21349584	RGD:2307	10116	20110428	RGD
UniProtKB	Q9QZN4	Fbxo6	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:12939278	-	10090	20090903	UniProt
UniProtKB	Q9QZN4	Fbxo6	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:21062743	-	10090	20150602	ParkinsonsUK-UCL
UniProtKB	Q9UP52	TFR2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:18353247	UniProtKB:Q30201	9606	20150707	BHF-UCL
UniProtKB	Q9UP52	TFR2	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:22728873	UniProtKB:Q30201	9606	20150424	BHF-UCL
UniProtKB	Q9VTJ4	Fuca	-	GO:0001948	glycoprotein binding	Function	IDA	PMID:26101846	-	7227	20170607	FlyBase
UniProtKB	Q9WTS1	Egfr	-	GO:0001948	glycoprotein binding	Function	IPI	PMID:21349584	RGD:2307	10116	20110428	RGD

**Comment by ValWood** [comment]
OK for us. So just to be sure, to use glycoprotein binding we need to  be sure that the glycosyl moity is bound. There is no way to say that a GP binds a glycoprotein if you don't know exactly which one? I'm OK with that. We only have 2  and it is clear from the GPs that they must bind a glycoprotein, they are sensors for misfolded glycoproteins. I don't  think this is a big loss...

**Comment by ValWood** [comment]
...Or the  fact that they bind a glycoprotein could be inferred if required from the  reaction substrate
like this:
http://www.pombase.org/spombe/related/GO:0000224
4-N-(N-acetyl-D-glucosaminyl)-protein + H2O

**Comment by hattrill** [comment]
What is happening to the children of glycoprotein binding?

**Comment by pgaudet** [comment]
Hi @hattrill 
The children are now direct children of 'protein binding'. 

@ValWood: The proposal for the 'modification-dependent protein binding' terms specified that we did not want to capture whether the protein bound the modified bit or not. That seemed OK for myriostylation-dependent and phosphorylation-dependent, etc, but for  ubiquitin for example perhaps we need more granularity. Same for glycosylation perhaps ? 

Do you think we need terms such as 'protein binding to ubiquitin/polyubiquitin/glycosylation modification? 

Thanks, Pascale

**Comment by ValWood** [comment]
I'm not sure. If you are saying that something binds a glycoprotein, then the sugar molecule must be present (otherwise it isn't a glycoprotein), so maybe all of the existing annotations are OK with the change (so I can add ours back)?

**Comment by pgaudet** [comment]
@ValWood 
Some of these annotations really capture something about the class of protein being bound. To me this is more evident when we look at terms like myriostylation and phosphorylation, it's not useful to say 'this protein binds a protein that is capable of being myriostylated/phosphorylated'. However most glycoproteins are constitutively glycosylated, so we could keep this term as-is, making glycoproteins a class like 'growth factor binding' and 'Wnt-protein binding'. 

Pascale

**Comment by srengel** [comment]
wait, so does this mean that the GO:0001948 glycoprotein binding is ok to use again?

the one SGD annotation was for EMP46, which recognizes the sugar parts of the proteins.  so i changed it just now from 5515 protein binding to GO:0030246 carbohydrate binding.  maybe that wasn't the right thing to do? 

actually now i think i should change this one back to GO:0001948 glycoprotein binding...

**Comment by ValWood** [comment]
possibly....
Other part of discussion is here:
https://github.com/geneontology/go-annotation/issues/1585

**Comment by pgaudet** [comment]
Hello again, 

This seems a relevant term to keep, in a different form to make it clear that we are talking abozt the binding to the carbohydrate part of the modified protein: 
'glycosylated region binding' (similar to 'proline-rich region binding), 
Proposed def: Interacting selectively and non-covalently with a glycosylated region of a protein. 
Proposed parents: 
- protein binding + carbohydrate-derivative protein binding.

Would that resolve the issue ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hello @ValWood @srengel @hattrill 
Since you have commented on this issue, what do you think of my proposal above ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Sounds OK to me.

Val

**Comment by srengel** [comment]
Hi Pascale,
i read this yesterday but paused because of the 'protein binding + carbohydrate-derivative protein binding'.  specifically the 'carbohydrate-derivative protein binding'.  after looking around a bit, i think you meant for that 2nd parent to be just 'carbohydrate-derivative binding'?

that sounds better, but is a glycoprotein really a carbohydrate derivative?  i don't think it is.

**Comment by pgaudet** [comment]
Hi @srengel 

glycoprotein (CHEBI:17089) is a carbohydrate derivative (CHEBI:63299)
according to CHEBI 

Pascale

**Comment by srengel** [comment]
Ok cool, thanks!

**Comment by pgaudet** [comment]
Resolved.
