### ISSUE TITLE
IPR000237 change BP: protein targeting to Golgi to CC Golgi apparatus

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1587]
Hello,

Based on the description of the GRIP domain (IPR000237), the protein that bears the domain is itself targeted to the Golgi. Using GO 'GO:0000042 protein targeting to Golgi' means that the proteins targets *other* proteins to the Golgi. 

I suggest you change the mapping to Cellular component Golgi apparatus GO:0005794 	Golgi apparatus. 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Thank you for this. I have removed this term. Because this entry also matches some proteins that have not been shown to localise to Golgi, so we will not give the Golgi apparatus GO term. 
Regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks !
