### ISSUE TITLE
IPR033922  	 glutamate dehydrogenase (NAD+) activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1588]
The pombe member is
glutamate dehydrogenase (NADP+) activity

v

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you. I have replace the GO term with "GO:0016639 oxidoreductase activity, acting on the CH-NH2 group of donors, NAD or NADP as acceptor". This will be visible in InterPro 65.0. 

Regards, 
Hsin-Yu

**Comment by ValWood** [comment]
Hmm, it seems a shame to lose  so much specificity. Maybe a grouping term is useful if the same family encodes both?

**Comment by EBI-Hsinyu** [comment]
Hi Val, 

I have discussed this with other curators in the team. In this entry, we can only put the parent term GO:0016639 to cover the both GO:0004354 and GO:0004352. Unfortunately, this means to lose the specificity. It might be nice to have a term like 'glutamate dehydrogenase activity' from GO.

Hsin-Yu

**Comment by ValWood** [comment]
Hi,

You can request a new term here
https://github.com/geneontology/go-ontology/issues
and link to this ticket for rationale.

Val

**Comment by ValWood** [comment]
I think this is done?
