### ISSUE TITLE
Annotation query MGI	P70278 Stra8

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1593]
from
https://github.com/geneontology/go-ontology/issues/13798#issuecomment-314530281

query 
Abstract

The transition from mitosis to meiosis is a defining juncture in the life cycle of sexually reproducing organisms. In yeast, the decision to enter meiosis is made before the single round of DNA replication that precedes the two meiotic divisions. We present genetic evidence of an analogous decision point in the germ line of a multicellular organism. The mouse Stra8 gene is expressed in germ cells of embryonic ovaries, where meiosis is initiated, but not in those of embryonic testes, where meiosis does not begin until after birth. Here we report that in female embryos lacking Stra8 gene function, the early, mitotic development of germ cells is normal, but these cells then fail to undergo premeiotic DNA replication, meiotic chromosome condensation, cohesion, synapsis and recombination. Combined with previous findings, these genetic data suggest that active differentiation of ovarian germ cells commences at a regulatory point upstream of premeiotic DNA replication.

I don't think the mouse one is about the DNA replication checkpoint. Its about preventing DNA replication. The DNA replication checkpoint is about preventing the next transition if there are problems with replication? * fail to undergo premeiotic DNA replication*

**Comment by hdrabkin** [comment]
I need more information here.
WHAT is the annotation (GO ID, PMID, evidence code, etc. ). It is the only way I can route an existing annotation for review.

**Comment by ValWood** [comment]
I got this from QuickGO
UniProt ID P70278 
Gene name Stra8

PMID is 17115059

**Comment by hdrabkin** [comment]
ok, now I see many annotations in our system using that PMID.
What GO are the ones you challenge, and what would you suggest what terms they be annotated to. 
I need all of this information to present to the curator who made the annotations.

**Comment by ukemi** [comment]
I think it is the checkpoint one. I think this paper is consistent with a checkpoint (although not conclusive). PMID:18799790 (J:139646) argues that it is not involved in a novel checkpoint.

**Comment by ValWood** [comment]
Ah sorry it's in the linked ticket this part:

GO:0033315 meiotic G2/M1 DNA replication checkpoint
(There is only one pomBase and one mouse annotation to the existing term. I don't think the mouse one is about the DNA replication checkpoint. Its about preventing DNA replication. The DNA replication checkpoint is about preventing the next transition if there are problems with replication- I will open an annotation tracker ticket for this).

but not the "mieotic DNA replication checkpoint" ?

**Comment by ValWood** [comment]
This is a DNA replication checkpoint:
A cell cycle checkpoint that prevents the initiation of nuclear division until DNA replication is complete, thereby ensuring that progeny inherit a full complement of the genome.

**Comment by ukemi** [comment]
I don't see this annotation any more. Must have been changed or removed by someone.
