### ISSUE TITLE
Deploy gorule system

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1594]

**Comment by pgaudet** [comment]
Where are the rules ?

**Comment by pgaudet** [comment]
This should get deployed with the new pipeline -> Jan 15, 2018

**Comment by pgaudet** [comment]
Tasks: 
1. Make SPARQL queries 
2. Somehow make then run periodically 
3. Somehow generate report (probably for each group) 

and maybe some other tasks

**Comment by kltm** [comment]
Too stale to use.
