### ISSUE TITLE
general question about localization/transport within a signalling pathway - MAPK import into nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1596]
From
https://github.com/geneontology/go-annotation/issues/1592

re:
check term and annotations to GO:0000189 'MAPK import into nucleus'. It is currently part of the MAPK cascade.

**Comment by ValWood** [comment]
We have a few things like this (in other pathways), and this is one of my outstanding questions.

In the cell cycle, for example, cdc25 phosphatase dephosphorylates and activates cdc2 (Cdk1)
as part of the signalling pathway that controls the G2/M transition.
Cdc25 itself is a target of a number of signalling pathways including replication checkpoint pathway, cell size pathway, MAPK pathway etc
When cdc25 is inhibited by these pathways it is sequestered in the cytoplasm (by a 14-3-3) protein.

So transfer into the nucleus appears to be part of the process at first glance.
However, I have been wondering if these should really be represented as part of the process.
We know that certain karyopherins are required for the pathway, but does this mean they are involved in the signalling ? Or is it just the case that this is constitutive- just a "conduit" (what do you call them in CamModels?), and they are not part of the process per se, or regulatory. We only know they are required because the transition does not occur when the nucleocytoplasmic transporters are mutated.

If there is no evidence for regulation of the transport system itself, would these be annotated along the lines:

karyopherin (has_substrate cdc25) involved in "protein import into nucleus" happens_during(positive regulation of G2/M transition of mitotic cell cycle).

My feeling is that the "regulation of the transition" here has nothing to do with the transport system per se but rather controlled by whatever releases cdc25 from the inhibitory sequestering by the 14-3-3 protein (although I am not sure that this is fully known).

I have a similar problem with localization of participants in spindle checkpoint pathway.

I hope we can resolve this in Sept. I hope to discuss this with Jacky H too, as she has co-authored and curated a number of papers which generated "localization within a signalling pathway data" (mainly the pathway above), and she has done a some work on the role of the nuclear transport system in cell cycle control. I'm hoping she will also be able to attend the signalling meeting too.

**Comment by pgaudet** [comment]
@ukemi I think this can be closed ?

**Comment by ValWood** [comment]
It still isn't clear to me exactly how to capture localization  in these cases, will this be covered by the signalling guidelines? It isn't part of the signalling (presumably) but it seems that we need to handle differently if the localization  occurs during the signalling (if the localization occurs "autonomously"  once a signal is passed), or if a specific localization is required for the signalling to occur (recruitment).
