### ISSUE TITLE
Is a MAPK activated kinase part of the MAPK cascade?

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#1598]
Is a "MAPK activated kinase" part of the MAPK cascade?
http://pombase2.aska.gen.nz/gene/SPAC23A1.06c

**Comment by ukemi** [comment]
According to the definition of the cascade and its children, it is.

MAPK cascade: An intracellular protein kinase cascade containing at least a MAPK, a MAPKK and a MAP3K. The cascade can also contain two additional tiers: the upstream MAP4K and the downstream MAP Kinase-activated kinase (MAPKAPK). The kinases in each tier phosphorylate and activate the kinases in the downstream tier to transmit a signal within a cell. Source: PMID:9561267, GOC:bf, GOC:mtg_signaling_feb11, PMID:20811974

comment: MAPK cascades lie downstream of many cell surface receptors and cooperate in transmitting various extracellular signals to the nucleus. One way by which the specificity of each cascade is regulated is through the existence of several distinct components in each tier of the different cascades. The cascades are typically named according to the component in the MAPK tier.

**Comment by ValWood** [comment]
So is that only the kinases one tier below the MAPK?

So for sty1

MAPK-activated protein kinase Srk1
P-TEFb-associated cyclin-dependent protein kinase Lsk1
MAPK-activated protein kinase Cmk2


(so Lsk1 is not usually described as a MAPK-activated kinase, but it is a kinase, and a MAPK target, so this should get MAPK cascade too?)

**Comment by ukemi** [comment]
From the above definition, yes. But I need to go back and read the papers that were used in defining these terms. There is no molecular function in GO for  MAPK activated kinase activity that I can find.

**Comment by ValWood** [comment]
I don't think we would need such a term,  its function is still a protein kinase. The fact that it is annotated by MAPK should not need to be in the MF ontology. This connection would be evident from the fact that the gene was a substrate/target of a MAPK. 
Also we would end up with multiple MF terms to describe the  exact same activity because these kinases are likely to be phospho-targets of multiple kinases. It's activity is still a " serine-threonine protien kinase", regardless what phosphorlates it.

What we would need to do is make the MAPK cascade annotations for these, if they are bona fida pathway components,  "MAPK activated kinase"  is just a gene product label, that is sometimes used for these kinases....

**Comment by ukemi** [comment]
This makes sense to me, but we do have MAPK, MAPKK, MAPKKK.

**Comment by ValWood** [comment]
They could easily be protein kinase part_of MAPK cascade!
But these are  more acceptable because  it's substrate specificity. The MAPK activated kinase is info about the upstream kinase, not it's specificity.

**Comment by ukemi** [comment]
Good argument for not having MAPKAKs as named molecular functions.

**Comment by ukemi** [comment]
But then in annotation guidelines and to be consistent with the current cascade definition, ANY kinase that is directly activated by a MAPK would be annotated to the cascade. Have a look at my straw-man generic model in the project ticket.

**Comment by ValWood** [comment]
Yes that's fine. The will can still be annotated to the cascade.

You would just connect that specific  kinase in the same way that you connected the MAPK's (I still don't find GO cam models easy to read, but essentially we have the same thing as you have in the model in standard GO annotations).

**Comment by ukemi** [comment]
I just realized that I forgot the MAPKAKs activity in the model. It is there now, represented as the generic kinase activity that is directly activated by MAPK. 

So I think this ticket is complete. The function of MAPKAKs are to be considered part of the MAPK cascade and they are any protein kinase that is directly activated by a MAPK.

**Comment by ValWood** [comment]
yep!
