### ISSUE TITLE
PTN000107351 annotation to  - where is this coming from?

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1601]
Where is this coming from:
UniProtKB | Q9VVE0 | Dmel\CG14057 |   | GO:0009249 | protein lipoylation | P | IBA | GO_REF:0000033 | PANTHER:PTN000107351 | 7227 | 20141112 | GO_Central

From http://www.pantree.org/node/annotationNode.jsp?id=PTN000107351
"No annotations inherited by this node"
So, where is this originating from?

Is this a PAINT or GOA issue? 
NB I can't see a id mapping issue at the UniProtKB end. But as this node is marked "has no annotations". I assume it's on the PAINT side of things.

**Comment by marcfeuermann** [comment]
There is a duplication event with function divergence in PTHR10993. I've blocked the propagation of "GO:0009249 protein lipoylation" for node PTN001404517 which contains POP5 component of ribonuclease P. Annotation has been corrected and updated for this node.
