### ISSUE TITLE
Fix GPI file format spec

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-annotation#1604]
The GPI spec on geneontology.org is correct, but unmaintainable, not being in github: http://geneontology.org/page/gene-product-information-gpi-format.

The GPI spec on github: https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-1_2.md

is not correct. Let's update the github GPI spec to reflect what is in geneontology.org.

**Comment by suzialeksander** [comment]
Closing, as the new spec is almost completely official.
