### ISSUE TITLE
hdac10 is an  acetylpolyamine deacetylase 

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-annotation#1608]
I wasn't sure which tracker to put this on so feel free to move it if there is a better place for the discussion and work.

PMID:  28516954 Characterizes Hdac10 from human and zebrafish and concludes that Hdac10 has   acetylpolyamine deacetylase activity.  "though the PDAC activity of zHDAC10 and hHDAC10 was highest with N^8-acetylspermidine, substantial catalytic activity was also observed with acetylcadaverine and acetylputrescine, as well as N^-(8-aminooctyl)acetamide."

This paper may help with Paint annotations

We have a lot of electronic annotations that say Hdac10 has histone deacetylase activity based on EC:3.5.1.98 and UniProt annotations and these appear to be incorrect.   The enzyme reaction appears to occur in the cytoplasm not in the nucleus, though that isn't demonstrated directly in the paper.

Support for the assertion that Hdac 10 targets a different substrate is provided by PMID: 20139990  Characterizes the response of various human Hdacs to inhibitors showing that Hdac6 and Hdac10 are inhibited by different molecules then  Hdac1,-3 &8 or Hdac 4-7&9. 

related term request is 
https://github.com/geneontology/go-ontology/issues/13997

**Comment by hdrabkin** [comment]
closed per issue 13997
