### ISSUE TITLE
ran GTPase signal transduction 	GO:0007165	 signal transduction IEA  with IPR002041

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1609]
GO:0007165 | signal transduction | IEA with IPR002041
-- | -- | --

I'm not sure that this mapping would be correct to describe Ran GTPase when acting i the context of a  regulator of nucleocytoplasmic transport?

val

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
You are right. RanGTPase is different from other GTPases involved in signal-transduction. I will remove this term. 

Regards, 
Hsin-Yu
