### ISSUE TITLE
IPR033896  MAPK cascade |

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1610]
should  transcription factors be annotated to this module?
It doesn't seem so... @ukemi ?

http://www.yeastgenome.org/locus/S000000386/go#comp
http://www.yeastgenome.org/locus/S000006010/go#comp

MAPK cascade |   | IEA with IPR033896

**Comment by EBI-Hsinyu** [comment]
Hello Val, 

We have deleted this term 'GO:0000165 MAPK cascade' a while ago (07/04/2017).  Please do let us know if there are any other problems. 

Regards, 
Hsin-Yu
