### ISSUE TITLE
PANTHER:PTHR11524:PTN000897517	 cytoplasmic translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1612]
This is a tricky one. Some ribosomal protein like proteins are not actually involved in translation, only in ribosome biogenesis (they are nucleolar, they never go to teh cytoplasm)

RPL7 is one:
http://www.yeastgenome.org/locus/S000004947/overview#protein

**Comment by marcfeuermann** [comment]
Lets say that they are required for, but not directly involved in translation :-)
I understand the point, and I've removed the annotation.
