### ISSUE TITLE
Accession number for GO_molecular function

### ISSUE THREAD

**Issue by guptapa** [geneontology/go-annotation#1622]
Hi,
I'm looking for the accession number for 4-aminobutyrate-pyruvate transaminase enzyme (EC: 2.6.1.96). I did not find it on GO live site. Following link is for more information about enzyme:
http://www.brenda-enzymes.org/enzyme.php?ecno=2.6.1.96&Suchword=&reference=&UniProtAcc=&organism%5B%5D=Oryza+sativa&show_tm=0 
Thanks.

**Comment by krchristie** [comment]
It looks like we do NOT have this EC number, though we do have a term with nearly that name, but a different EC#:

4-aminobutyrate:pyruvate transaminase activity (GO:0034387)
Def: Catalysis of the reaction: 4-aminobutanoate + pyruvate = succinate semialdehyde + alanine.
  EC:2.6.1.19
  GOC:mah

This looks like a mistake as the definition for this GO term looks like it matches the definition for EC:2.6.1.96, and not for EC:2.6.1.19, which is supposed to be "4-aminobutyrate—2-oxoglutarate transaminase".  @hdrabkin Do you agree?

The only annotation to that term is a plant gene (http://amigo.geneontology.org/amigo/term/GO:0034387), so probably worth checking which EC number this gene actually has.

Here is info from the EC pages for these two EC numbers:

**EC 2.6.1.19** (http://www.chem.qmul.ac.uk/iubmb/enzyme/EC2/6/1/19.html)
**Accepted name**: **4-aminobutyrate—2-oxoglutarate transaminase**
**Reaction**: 4-aminobutanoate + 2-oxoglutarate = succinate semialdehyde + L-glutamate
**Glossary**: 4-aminobutanoate = γ-aminobutyrate = GABA

**EC 2.6.1.96** (http://www.chem.qmul.ac.uk/iubmb/enzyme/EC2/6/1/96.html)
**Accepted name**: **4-aminobutyrate—pyruvate transaminase**
**Reaction**: (1) 4-aminobutanoate + pyruvate = succinate semialdehyde + L-alanine
  (2) 4-aminobutanoate + glyoxylate = succinate semialdehyde + glycine
**Systematic name**: 4-aminobutanoate:pyruvate aminotransferase

This ticket should probably be transferred to the ontology tracker, but I don't know how to do that. Maybe @ukemi or @vanaukenk can move it.

**Comment by hdrabkin** [comment]
Yep, this is not right.
These are two different critters.
H

**Comment by krchristie** [comment]
This issue was moved to geneontology/go-ontology#14118

**Comment by jaiswalp** [comment]
So we need a new GO term for EC: 2.6.1.96

**Comment by krchristie** [comment]
**PLEASE DO NOT COMMENT IN THIS TICKET** 

Please put all future comments to the ontology ticket that I moved this issue to: geneontology/go-ontology#14118
