### ISSUE TITLE
IPR029523 & UniProtKB-KWs 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1625]
migrated from
https://github.com/geneontology/go-ontology/issues/14141
@Antonialock 

pombe ino80 complex subunits have IEAs to regulation of transcription from RNA polymerase II promoter & regulation of transcription, DNA-templated
e.g. IPR029523 & UniProtKB-KW:KW-0805 & UniProtKB-KW:KW-0804

the ino80 complex moves nucleosomes around thereby regulating nucleosome density.

It seems to me like ino80 function is upstream of regulation of transcription? Unless ino80 is directly involved in the recruitment of factors (which I don't think it is?) it "just" makes the chromatin accessible to other factors (which could be involved in repair, transcription, replication....anything where proteins need access?)

**Comment by EBI-Hsinyu** [comment]
Hi,

Thank you for this. I have removed this term. 

Hsin-Yu

**Comment by Antonialock** [comment]
cheers+
