### ISSUE TITLE
annotations to mature ribosome assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1626]
I noticed when following up on
https://github.com/geneontology/go-ontology/issues/11517

that this term now has many more manual (and hence electronic annotations).

Many are to arabodopsis annotations of ribosomal proteins to ribsome assembly via the CAFA project. This is a proteomics experiment to   quantify ribosome, it can not be inferred by IC that these are involved in ribosome assembly.

@tberardini 
(not sure who to tag for CAFA)

**Comment by tberardini** [comment]
@ValWood "Many are to arabodopsis annotations...via the CAFA project."

Which ones are you referring to?  There are 51 A. thaliana annotations to 'ribosome assembly' and children terms.

42 IBA (PAINT, right?)
 6  IEA
  2 IMP
  1 IDA

I don't see any IC annotations.

**Comment by ValWood** [comment]
2nd to 7th, and more in this list:
Used QuickGO

http://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0042256&evidenceCode=ECO:0000352&evidenceCodeUsage=descendants

**Comment by tberardini** [comment]
Aha.  Yes, agree that IC is not appropriate.  Don't know who to contact at CAFA either.

**Comment by ValWood** [comment]
tagging Jim to assign to the appropriate person @jimhu-tamu

**Comment by ValWood** [comment]
@jimhu-tamu 
note that these should not be annotated to any ribosome assembly term, not just the mature ribosome assembly term used.

val

**Comment by ValWood** [comment]
Oh yes I was, sorry Jim. I don't know what CAFA is....

**Comment by ValWood** [comment]
@pgaudet  do you know what CAFA is?

**Comment by ValWood** [comment]
I remembered. No, we can't include predictions as IC's
http://biofunctionprediction.org/cafa/
If these were made for CAFA validation......very worrying.....

**Comment by jimhu-tamu** [comment]
I think CAFA is @idoerg

**Comment by idoerg** [comment]
Whoops, thanks for tagging me. This indeed creates an issue, but not too late for us to fix.  @ashleyzhou972 @yuxjiang

**Comment by pgaudet** [comment]
I am assigning myself (because I cannot assign someone outside the project right now); please @idoerg @ashleyzhou972 @yuxjiang do let me know when this is ready to close. 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Iddo, 

Are these annotations validated by  the MODs? I had a look  at the small number of pombe ones yesterday and spotted a few annotations we would not make. I was just looking at the Drosphila ones and saw quite a few in just a few minutes. 

I noted a few examples but I won't have time to look in any detail for a while. 

Val

**Comment by ValWood** [comment]
note for  this one, I think it is all  "ribosome assembly" which have a problem (305), not only 
mature ribosome assembly

http://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0008150&assignedBy=CAFA&evidenceCode=ECO:0000305&evidenceCodeUsage=descendants

**Comment by idoerg** [comment]
I don’t know what am MOD is. The annotations were not provided by me or my
team. We are only consumers of these annotations, so we are grateful that
someone alerted us to this issue.

If you want the actual annotators, you should talk with Maria Martin
(cc'd).

--

**Comment by ValWood** [comment]
George at UniProt is on the case.
I'd odd that these have CAFA as a source rather then UniPRot-KB. The assigned_by field is for who made the annotation. Hence the confusion.

**Comment by ggeorghiou** [comment]
Hi all, 

I'm responsible for managing the annotations for the CAFA challenge. I'm removing the IC annotations that @ValWood has highlighted.

To answer your question Val, CAFA is a seperate grant from UniProt and we felt it would be good to reflect that with the annotations by having the source as CAFA.

**Comment by idoerg** [comment]
Question: on the CAFA assessment side of things, we used the term GO:0003735 "structural constituent of ribosome" http://amigo.geneontology.org/amigo/term/GO:0003735 for our benchmark. This is in the Molecular Function aspect. Is that term still valid?

**Comment by ValWood** [comment]
It is a valid term, but probably not  a great term to use for bench marking.  It was created in the early days  to enable ribosomal components to be assigned to a MF term if they did not have a catalytic assignment. I think it is now used in rather an 'ad hoc' way.  It's not really possible at this point to really  determine  whether a ribosomal component is structural or not, but in many cases this term has been applied wholesale to all ribosomal subunits, and some resources avoid using it.

**Comment by hdrabkin** [comment]
It might be better to use ribosomal subunit assembly so as not to imply something that is the entire ribosome

**Comment by ValWood** [comment]
Closing because there are no CAFA annotations to this term
