### ISSUE TITLE
P87058 (LAH1_SCHPO) annotation dispute

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1627]
sla1 P87058
tRNA export from nucleus Source: CAFA

isn't involved in tRNA export, this is a mutation in an export signal.

Could this one be deleted?

Thanks

Val

**Comment by ValWood** [comment]
@ggeorghiou  do you deal with CAFA?

**Comment by ggeorghiou** [comment]
I do. I'll have to review it but won't be able to change it till the CAFA results are posted.

**Comment by ggeorghiou** [comment]
Deleted the annotation. Closing the ticket
