### ISSUE TITLE
JAK/STAT pathway - Signaling Project

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#1628]
GO:0007259 receptor signaling pathway via JAK-STAT 

Main tasks:

- [x] Create GO-CAM model (http://noctua.berkeleybop.org/editor/graph/gomodel:59c8885900000374)

- [x] Create google spreadsheet (https://docs.google.com/spreadsheets/d/1H6ZCHAxd5YSpj-UaUzkJ6ssF2FXj9hT8kkT5qGaS1lY/edit#gid=683337807)

- [ ] define members of the JAK/STAT pathway for flies, worms, and a subset of vertebrates

 - [ ] collate all JAK/STAT-related annotations for those members

- [ ] Flag annotations that are annotated to the pathway but do not have MF support as being part of the process

 - [ ] flag annotation issues that need review, e.g. annotation to the pathway and regulation of the pathway

- [x]  identify ontology terms that need review/clarification. Also see https://github.com/geneontology/go-ontology/issues/13038. Please comment on this ticket as well.

 - [ ] where possible, note what experiments are used to support annotation to specific terms

Additional tasks:

- [ ]  Review annotations of other gene products to JAK/STAT pathway - How do the activities of these gene products actually relate to JAK/STAT signaling?

- [ ]  Collate all 'JAK/STAT' terms in the ontology (maybe other terms as well)

- [ ]  Look at annotations to all JAK/STAT-related terms

@RLovering @gantonazzo

**Comment by RLovering** [comment]
New term requests:
https://github.com/geneontology/go-ontology/issues/14164

**Comment by RLovering** [comment]
Hi Giulia
how are you progressing on this long list of tasks?
Ruth

**Comment by gantonazzo** [comment]
Hi Ruth,
For fly, we have definitely defined the members, and collated (and reviewed) all the annotations. We have also kept track of the experiments used to support annotations to the pathway. At least for the core members of the pathway, we should be good with MF support as part of the process, but we still have some regulators that lack a MF annotation. We don't have annotations in the grey area between regulation of the pathway and the pathway itself, but I don't know how the situation is for worms and other vertebrates. Regarding the ontology, I've seen the new discussion on [#14167](https://github.com/geneontology/go-ontology/issues/14167), so I guess we may still have to sort some details out!:)
