### ISSUE TITLE
Non-english publication used in annotations

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#1632]
During our normal GOA-mouse annotation loads,  we have come across IPI annotations made using PMID:14619418, an article completely in Japanese.
1. Tanpakushitsu Kakusan Koso. 2003 Nov;48(14):1920-7.
[Complex between nidogen and laminin fragments reveals a paradigmatic  beta-propeller interface].
[Article in Japanese]   <<<<<<<<<<<<<<<<<< not even an English abstract
Takagi J(1).
Author information: 
(1)takagi@protein.osaka-u.ac.jp
PMID: 14619418  [Indexed for MEDLINE]
The annotations are from IntAct.

How was this annotated? Figure legend, translated?, etc.  Before we load this I have to get the pdf into our db.

UniProtKB	P10493	Nid1		GO:0005515	PMID:14619418	IPI	UniProtKB:P02468	F	Nidogen-1	NID1_MOUSE|Nid1|Ent	protein	taxon:10090	20170829	IntAct

**Comment by deustp01** [comment]
I can probably get the reference. If I succeed, who wants a copy? (I probably can't just post it to this ticket - copyright.)

**Comment by hdrabkin** [comment]
Certainly send it to me. If there is some figure that makes it obvious then I'll have it load I guess.

**Comment by hdrabkin** [comment]
Peter found it by entering the title; there are TWO papers with same title and authors in pubmed
Takagi J, Yang Y, Liu JH, Wang JH, Springer TA. Complex between nidogen and
laminin fragments reveals a paradigmatic beta-propeller interface. Nature. 2003
Aug 21;424(6951):969-74. PubMed PMID: 12931195.
THIS looks more like it. The annotation reference needs to be changed? Then we could load it.

**Comment by hdrabkin** [comment]
Peter found it by entering the title; there are TWO papers with same title and authors in pubmed
Takagi J, Yang Y, Liu JH, Wang JH, Springer TA. Complex between nidogen and
laminin fragments reveals a paradigmatic beta-propeller interface. Nature. 2003
Aug 21;424(6951):969-74. PubMed PMID: 12931195.
THIS looks more like it. The annotation reference needs to be changed? Then we could load it.

**Comment by bmeldal** [comment]
You are absolutely spot on! I just used the same IntAct evidence for the complex which is due out with our next release.

My notes:

PMID:12931195 - Takagi et al 2003
Title: Complex between nidogen and laminin fragments reveals a paradigmatic beta-propeller interface
1npe: nidogen 941-1207aa (IPR011042) - laminin-gamma-1 769-932aa (IPR000742 - 3 of 6 of these domains in this region, there are also 3 more further to N-terminus)

PMID:14619418 - Takagi 2003 [Japanese]
Seems to be same as 12931195 above but in a Japanese journal
EBI-7059826 - MINT curation with link to 1npe

I think the PMID of this IntAct entry is mis-assigned. Unless MINT had a Japanese visitor or student etc who annotated it. I will discuss with Pablo and Sandra as we can fix it at our end and then the fix will trickle through to GO. Bear with me til UK morning time!

**Comment by bmeldal** [comment]
Sandra fixed the PMID, it will be out with the next release.

**Comment by hdrabkin** [comment]
Thanks Birgit (and Sandra); !
I will close now.
