### ISSUE TITLE
Query: receptor activator activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1634]
Following up on https://github.com/geneontology/go-ontology/issues/14220- @thomaspd mentioned that 'receptor activator activity' should be synonymous to receptor ligand activity, but the term is not clearly defined and the usage has been quite varied. The good news is that there are only 5 direct EXP annotations: 

**MGI:MGI:96434**	insulin-like growth factor 2		GO:0030546	BHF-UCL	NCBITaxon:10090	IMP		MGI:MGI:4438697|PMID:20032056	20110420
-> I think this was used a 'receptor ligand activity' 

**UniProtKB:Q86YN6**	Peroxisome proliferator-activated receptor gamma coactivator 1-beta		GO:0030546	UniProt	NCBITaxon:9606	IDA		PMID:11854298	20061127
-> nuclear factor coactivator

**UniProtKB:P07355**	Annexin A2	contributes_to	GO:0030546	BHF-UCL	NCBITaxon:9606	IDA		PMID:22848640	20150302
-> not a receptor activator (it inhibits receptor degrdation)

**IntAct:EBI-10814663**	ANXA2-PCSK9 complex		GO:0030546	BHF-UCL	NCBITaxon:9606	IDA		PMID:22848640	20161019
-> not a receptor activator (it inhibits receptor degrdation)

**MGI:MGI:97599**	protein kinase C, epsilon		GO:0030546	MGI	NCBITaxon:10090	IDA		MGI:MGI:3762436|PMID:17875639	20110325
-> in this paper they describe a modulation in receptor sensitivity by Prkce

@ukemi 
@bmeldal 
@RLovering 
is 'receptor activator activity' really what you want to capture in these annotations? If we forget existing GO classes, what function would you like to capture ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
> IntAct:EBI-10814663	ANXA2-PCSK9 complex GO:0030546 BHF-UCL NCBITaxon:9606 IDA PMID:22848640 20161019

@NancyCampbell 's complex (and I reviewed it...). I agree, probably not the right term. Could you please suggest an alternative, Nancy? You can make the edits directly in the editor.

**Comment by RLovering** [comment]
MGI:MGI:96434	changed to receptor ligand activity
UniProtKB:P07355	changed to molecular function regulator

I would suggest EBI-10814663 revised to molecular function regulator

Ruth

**Comment by bmeldal** [comment]
> EBI-10814663

A little top-level (doesn't really say much...), what about grandchild term GO:0030546 receptor activator activity?

**Comment by ukemi** [comment]
I think originally this term was meant to cover the things that can activate a receptor other than just ligands. That would make sense for the Prkce. But I can remove that annotation if the term changes.

**Comment by pgaudet** [comment]
Hi @ukemi  
The problem is that it seems some people interpret this to also include ligands. We should clarify the term and the definition if we want to capture  things that can activate a receptor other than just ligands.

Generally - do we want to have 'gene product class x' regulator activity and regulation? (this is really parallel to the binding question).

**Comment by NancyCampbell** [comment]
@bmeldal 

>  I would suggest EBI-10814663 revised to molecular function regulator

> A little top-level (doesn't really say much...), what about grandchild term GO:0030546 receptor activator activity?

EBI-10814663 complex is currently annotated to receptor activator activity and it seems this is where the problem is - at least as I understand it from Pascal's @pgaudet original comment

> Following up on geneontology/go-ontology#14220 @thomaspd mentioned that **'receptor activator activity' should be synonymous to receptor ligand activity**,

The complex inhibits LDL receptor degradation which is definitely not synonymous to receptor ligand activity defined as:"**Binding to a signaling receptor** as part of signaling and modulating the effector activity of that receptor to initiate a change in cell activity .....". i.e. my complex does not bind to the receptor.

I agree with David @ukemi. Yes the term's definition: ''The function of interacting (directly or indirectly) with receptors such that the proportion of receptors in the active form is increased" seems to
> cover the things that can activate a receptor other than just ligands.

However, i admit that when I did the annotation I seem to have concentrated on second half of the definition i.e. "such that the proportion of receptors in the active form is increased" as my complex inhibits LDL receptor degradation, and took the 'very' wide meaning of "indirectly" in the first half. Now, even though I can justify the former, I really can't justify the latter.

@pgaudet I am happy to change the annotation.

So for the time being I went with Ruth's suggestion and changed to molecular function regulator - or better suggestion if anyone disagrees. 

Hope that is ok.

Thanks.

**Comment by bmeldal** [comment]
Thanks @NancyCampbell - I seemed to have gone round in a circle there and made the same assumption as you did when you first annotated it! So yes, I agree we have to lift the annotation up a couple of levels.

Will you make the change in the Editor, Nancy?

**Comment by NancyCampbell** [comment]
@bmeldal 
Thank Birgit. Done for both mouse and human.

**Comment by pgaudet** [comment]
Hi @bmeldal 
what this points out is GO is really missing a concept that described 'downregulation of signaling by receptor degradation" (it is also possible that the concept exists but I don't know what it's called).  Any suggestions @ukemi @vanaukenk @RLovering @bmeldal ? 

Thanks, 
Pascale

**Comment by NancyCampbell** [comment]
@bmeldal @ukemi @vanaukenk @RLovering

Hi @pgaudet 

Thank you for the suggestion that 'downregulation of signaling by receptor degradation' might be missing.

However, in this particular case i.e. the PCSK9-ANX2 complex and the LDL receptor, this is not a signalling pathway. So 'negative regulation of receptor degradation' is appropriate though I can't find this in QuickGO. So maybe I should request this term? (or better suggestion).

Thanks
Nancy

**Comment by ValWood** [comment]
Isn't this a little bit similar to the existing term:

"regulation of transcription by transcription factor catabolism"

there is talk of obsoleting this term. So, it seems odd to add new similar ones in another context. We should probably decide how to represent this type of process regulation  more generally before the  new terms are created.

**Comment by bmeldal** [comment]
@ValWood are we just comparing principle here, now? Nancy's complex is a regulator of a receptor, not a TF. (although receptors can become TFs...) At it acts on the synthesised protein, not at the transcription or translation level.

**Comment by ValWood** [comment]
Ontology principle. Regulation of some process by protein catabolism.

**Comment by bmeldal** [comment]
Ok, I see what you mean, Val.

Does that mean it needs an editors' discussion?

**Comment by pgaudet** [comment]
Hi @ValWood @bmeldal 
I don't yet know what the best solution is; @ValWood I think the terms of type 'x involved in y' were being discussed for obsoletion (in #14138 but there are probably other issues). Examples of these terms are 'cyclin-dependent protein serine/threonine kinase activity involved in negative regulation of conjugation with cellular fusion' where we don't know how the MF fits in the BP. 

This case here is a mechanism of regulation: perhaps it would be useful to have: 
- regulation of MF by degradation of the target 
- regulation of MF by sequestration of the target 
- regulation of MF by post translational modification of the target 
- regulation of MF by oligomerization/complex dissociation 
(we have this in the GPCRs and @pmasson55 showed me an example yesterday where the activate form of a receptor was a dimer that produced after ligand binding).
... etc 

This seems to come up again and again as somthing we are unable to express, and even in GO-CAM models we cannot really do it. 

Thoughts ? 
@thomaspd @ukemi and others I'd like your input as well :) 


Thanks, Pascale

**Comment by bmeldal** [comment]
> regulation of MF by oligomerization/complex dissociation
> (we have this in the GPCRs and @pmasson55 showed me an example yesterday where the activate form of a receptor was a dimer that produced after ligand binding).

It is really common for receptors to not oligomerise until the ligand binds. Lots of examples in the CP now, e.g. PDGFs (and more to come). But I would annotate directly with the MF of the receptor activity and the BP of the signaling pathway.

**Comment by pgaudet** [comment]
@sylvainpoux dealt with the Uniprot annotation 

@hdrabkin can you please have a look at MGI:MGI:97599	protein kinase C, epsilon? 

Thanks, Pascale

**Comment by suzialeksander** [comment]
ontology was refactored, UniProt and MGI annotations were reviewed.  Further action should be a new ticket
