### ISSUE TITLE
update annotation guidelines for Molecular Function

### ISSUE THREAD

**Issue by thomaspd** [geneontology/go-annotation#1635]
From @ValWood comment on the ontology [https://github.com/geneontology/go-ontology/issues/14161](url).

We need to update the MF guidelines, especially with respect to the notion of separate functions. Guidelines are at http://www.geneontology.org/page/molecular-function-ontology-guidelines 

Sentences like these are not correct:
'A gene product may have many different functions, but it would be wrong to create a function term that represents multiple functions.'
and
' Do not confuse the following:

    Two things that happen at the same time or that are done by the same molecule.
    Two things that are dependent on each other and cannot occur independently.

For example, the proposed term actin binding with sliding actually includes the two functions binding and motor activity, so it is not appropriate as a function term. However, calcium-transporting ATPase activity represents two activities that are dependent on each other and cannot occur independently; thus calcium-transporting ATPase activity is appropriate as a GO molecular function. '

In fact the example given for the former statement is nuclear receptor activity, which is currently in MF and indeed has multiple parentage.  We WANT to have molecular functions that are compound functions, if this is how the gene product acts at the molecular level.

**Comment by suzialeksander** [comment]
this looks like it's been removed, can't find this on the wiki or on the revised website.
