### ISSUE TITLE
add UniProt people to contacts list

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1638]
https://github.com/geneontology/go-ontology/blob/master/curator_group_contacts.tsv

**Comment by ValWood** [comment]
"yo" sounded nice but I edited to "to"

Anyone who describes themselves as a  "GO curator" should be on GitHub.

GitHub is our means of communication, for terms, genes, people, problems, solutions.

Sandra would sort it for UniProt  but I can't find her GitHub ID !

**Comment by ValWood** [comment]
Would be good to add Sandra for EBI UniProt then can close this

**Comment by pgaudet** [comment]
Done
