### ISSUE TITLE
Documentation - Need feedback on wiki usage

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1640]
Hello,

Following on from the Cambridge meeting, please add to this ticket the curation documentation you typically consult on the GO wiki.

We plan to reorganize the documentation on the website and wiki and want to prioritize according to what pages are most used by GO curators.

Thx.

**Comment by vanaukenk** [comment]
From Midori @mah11 (PomBase):

As requested, a few notes on GO documentation we use at PomBase ...

We link some of our user documentation to the wiki page on annotation extensions (e.g. http://preview.pombase.org/documentation/gene-page-gene-ontology). I'm not sure it's optimized for biologist end users, but we don't know of anything better at present.

I use the annotation extension docs at GitHub frequently, and I think the other PB curators do too (perhaps a bit less frequently).

**Comment by suzialeksander** [comment]
Closing due to underwhelming response.  Can open new ticket if needed
