### ISSUE TITLE
Annotation challenge: RBGA5 (AT4G13850) and transcription antitermination factor activity, RNA binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1642]
Hello, 

I think anti-termination is a prokaryotic-specific process. Interestingly, the assay for anti-termination activity of RBGA5 was done in E. coli. The authors conclude that "These results demonstrate that GRP2 has an activity that is capable of melting the RNA secondary structure in vivo, which further confirms that GRP2 exhibits RNA chaperone activity."

So it seems 'transcription antitermination factor activity, RNA binding' (and the process transcription anti-termination) is a bit strong. How about annotating to 'misfolded RNA binding', and perhaps the closest BP is 'GO:0060567 negative regulation of DNA-templated transcription, termination'? 

See also #1641 for additional background and references. 

Thanks, Pascale

**Comment by tberardini** [comment]
@pgaudet :The 'transcription antitermination' annotations were made by UniProtKB.  I cannot edit them.

http://amigo.geneontology.org/amigo/reference/PMID:17376161

Please reassign to the appropriate UniprotKB contact.  Thanks.

**Comment by pgaudet** [comment]
thanks @tberardini 
I disputed via Protein2GO. 

Pascale

**Comment by pgaudet** [comment]
Repoenting to make sure I dont forget.

**Comment by pgaudet** [comment]
Annotation replaced  by 'misfolded RNA binding'.
