### ISSUE TITLE
B2RXF0 (TMEM229A) hit to IPR036963: false positive? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1643]
Hello, 

Is it possible that B2RXF0 (TMEM229A) hit to IPR036963 is a false positive? 
It seems weird that human would have an endogenous gene to transcribe the HIV virus. 

Thanks, Pascale

**Comment by asangrador** [comment]
Yes, it looks like a false positive. We have other signatures for Tat that do no hit TMEM229A. I will remove the annotation for this entry, as we have another entry (IPR001831) that will provide annotation to the proteins that should get it.
Cheers,
Amaia
