### ISSUE TITLE
GO:0000015 annotation for RNase E

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#1644]
I just ran across an annotation for E. coli RNase E (P21513) as "part_of" the phosphopyruvate hydratase complex. It is true that both enolase (aka phosphopyruvate hydratase) and RNase E are part of the degradosome; however, no other component of the degradosome other than enolase is actually part of the homomultimeric enolase complex.  Is this a case of a transitive annotation of membership in a complex, or simply an annotation error?  (There doesn't seem to be a "degradosome" CC term in the GO.)  The source of the annotation is shown as CAFA.

**Comment by ggeorghiou** [comment]
Hi @keseler 

I've reviewed the annotation for you. RNase E was found to bind enolase and I assumed at the time that it was part of the same complex as enolase. Given a second reading of the paper, plus your input, I have removed the annotation since it is incorrect.

Best,

George

**Comment by pgaudet** [comment]
@keseler is this is OK please close the issue. 

Thanks, Pascale

**Comment by keseler** [comment]
Yes, totally ok with me.  Didn't realize that I should be the one closing the issue. :-)
