### ISSUE TITLE
Review annotations to BP high affinity transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1645]
Hello, 

For the ticket https://github.com/geneontology/go-ontology/issues/14354
These are the merges that will be done, and the number of affected EXP annotations per group. 
@ValWood @tberardini @srengel 
If your group does not automatically transfer annotations after a merge, please go ahead and do so. 

At the same time: Ideally we would git rid of just 'transport' in BP; to be a proper process it'd be nice to know if this is import into cell (or where it's being moved from). So if you know whether the annotations here are transmembrane import into cell, please let me know, it might accelerate the next merge. 

Thanks, 
Pascale

GO ID | term label | term to be merged with | EXP annotation per group 
-- | -- | -- | --
GO:1990821 | high affinity glucose import | Merge into  GO:0098708 glucose import across plasma   membrane | (1) pombase
GO_0015678 | high-affinity copper ion   transport | Merge into GO:0098705 copper ion import across plasma membrane  | (1) TAIR
GO_0015683 | high-affinity ferric iron   transmembrane transport | Merge into  GO:0034755 iron ion transmembrane transport | (2) PseudoCAP
GO_0061839 | high-affinity ferrous ion   transmembrane transport | Merge into  GO:0034755 iron ion transmembrane transport | 0 annotations
GO_0008646 | high-affinity hexose   transport | Merge into GO:0035428 hexose transmembrane   transport | (4) CGD   (2) GeneDB   (1) TAIR
GO_0006827 | high-affinity iron ion   transmembrane transport | Merge into  GO:0034755 iron ion transmembrane transport | (12) CGD   (8) SGD   (1) TIGR
GO_0010163 | high-affinity potassium ion   import | Merge into GO:0071805 potassium   ion transmembrane transport | (4) TAIR
GO_0044749 | high-affinity zinc II ion   transmembrane import | Merge into GO:0071578  zinc II ion transmembrane import | (1) EcoCyc   (1) PomBase
GO_0006830 | high-affinity zinc II ion   transport | Merge into GO:0071578  zinc II ion transmembrane import | (1) SGD
GO:0008647 | low-affinity hexose   transport | Merge into GO:0035428 hexose transmembrane   transport | 0 annotations
GO:0080055 | low-affinity nitrate transport | Merge into GO:0015706 nitrate   transport? GO:1902025 nitrate import? Rename one of these 'nitrate import   into cell'? | (7) TAIR
GO:0006831 | low-affinity zinc II ion   transport | Merge into GO:0071578  zinc II ion transmembrane import | (1) SGD
GO:0015090  | low-affinity iron ion transmembrane transporter activity | Merge into GO:0034755 iron ion transmembrane transport  | (1) SGD (SGD should add the activity 'GO:0015090 low-affinity iron ion transmembrane transporter activity' to FET4/S000004938)

**Comment by pgaudet** [comment]
PS Please remove your name from assignees once you are done.

**Comment by RLovering** [comment]
There seems to be another ticket for this https://github.com/geneontology/go-ontology/issues/14354 so I am confused about where to put my comments ;(

Please could high-affinity ferric iron transmembrane transport be renamed ferric iron transmembrane transport

And high-affinity ferrous iron transmembrane transport be merged into GO:1903874 ferrous iron transmembrane transport

Note we currently have the terms
ferric iron transport and ferrous iron transport although unfortunately GO:0061839 high-affinity ferrous ion transmembrane transport did not have ferrous iron transmembrane transport as a parent.

The transport of the ferric and ferrous ions is by different systems and it would be good to keep this distinction.

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

The other ticket is for the ontology changes; I wanted to keep that separate from the annotation review; is that OK ? 

Thanks, Pascale

**Comment by RLovering** [comment]
great, sorry not to appreciate the difference, it does make sense now

**Comment by pgaudet** [comment]
:)

**Comment by ValWood** [comment]
PomBAse annotations OK for merge (high affinity captured by MF)

**Comment by tberardini** [comment]
I took care of the TAIR annotations.  For the GO:0080055 | low-affinity nitrate transport annotations, I transferred them to 'nitrate transport'.

**Comment by pgaudet** [comment]
@brinkmanlab
Can you please review  the PseudoCAP annotations? 

Thanks, Pascale

**Comment by srengel** [comment]
just now getting to this, but i don't see any SGD annotations to this term.  unassigning myself.  please let me know if i missed something.

**Comment by pgaudet** [comment]
Hi Stacia, 

I should have included which genes were impacted. The merge is already done; but I suspect that the affected genes are for eg: S000004120 (GO:0006831 | low-affinity zinc II ion transport), now annotated to the BP GO:0071578  zinc II ion transmembrane import. 

So it looked like the merge was correctly handled by SGD; unless you disagree with the merges in the table above then there is no action needed from you. 

Thanks ! 

Pascale
