### ISSUE TITLE
IPR007310 not GO:0015343 siderophore transmembrane transporter activity ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1646]
Hello, 

If IPR007310 catalyzes the synthesis of the siderophore, I would say it's NOT involved in 
GO:00015343 siderophore transmembrane transporter activity ? 

Thanks, Pascale

**Comment by Antonialock** [comment]
If it is of any help...we haven't made any NOT annotations, but we have annotated different genes biosynthesis/transport

e.g. 
ferrichrome biosynthetic process
http://preview.pombase.org/term/GO:0031169
![screen shot 2017-10-13 at 10 13 50](https://user-images.githubusercontent.com/12727506/31539055-4dd1d1d0-afff-11e7-84fd-c2afbee8c131.png)

siderophore transport
http://preview.pombase.org/term/GO:0015891
![screen shot 2017-10-13 at 10 15 09](https://user-images.githubusercontent.com/12727506/31539099-76a26d90-afff-11e7-8224-e43631657f5c.png)

**Comment by pgaudet** [comment]
Thanks !
