### ISSUE TITLE
IPR029755 not GO:0006826 iron ion transport ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1647]
Hello, 

IPR029755 seems to be a transcriptional regulatory factor; ie it should NOT be directly mediating GO:0006826 iron ion transport .Homeostatis (already mapped) is probably enough. 

Thanks, Pascale

**Comment by asangrador** [comment]
I have removed the GO term for iron ion transport.
Thanks,
Amaia

**Comment by pgaudet** [comment]
Thanks !
