### ISSUE TITLE
InterPro2GO pipeline

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1653]
Tasks identified at the Oct 2017 GOC meeting: 

* Collect uber ‘black list’ and post it somewhere that everyone can access it
* Come up with some rule for filtering ahead of time - new GO rule for filtering InterPro2GO for GO pipeline - https://github.com/geneontology/go-site/issues/436 
* Put together working group of interested individuals, have a couple meetings, come up with guidelines by May 2018 GOC mtg
* Each of the database should provide their QC pipeline to make sure nothing falls through the cracks

**Comment by suzialeksander** [comment]
unclear what a "uber black list" is. @pgaudet  is this still planned? the corresponding go-site ticket is still open.

**Comment by pgaudet** [comment]
This should be covered by the do_not_annotate check. 

Thanks.
