### ISSUE TITLE
Update PAINT documentation: tool instructions + guidelines

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1656]
Action item from Oct 2017 GOC meeting

**Comment by pgaudet** [comment]
Note that Paul updated the documentation on the wiki, needs to be reviewed

**Comment by pgaudet** [comment]
From Paul

Hi all,

I edited the wiki pages on the PAINT user manual and SOP (curation guidelines), to update them before we give them to EBI.  Can you please review the pages at:
http://wiki.geneontology.org/index.php/PAINT_SOP
http://wiki.geneontology.org/index.php/PAINT_User_Guide

I didn’t have time to upload the new images from the new PAINT interface for opening families from the database (from Huaiyu’s manual), but maybe Huaiyu can do that.

Thanks,
Paul.

**Comment by pgaudet** [comment]
Feedback from Marc 

Hi all,

Sorry for this late reply. Busy times before holidays ;-)

I've looked at the documents and I'm fine with both. It's simple and clear. However, as we are familiar with PAINT, it would be good to ask also potential curators not familiar with the tool to be sure that it is also clear for them.


Few little comments:


Curation guidelines:

I would wait for the PAINT tool updates subsequent to our discussion with Huaiyu in Geneva. May be some additional functions will be available (depending on what is possible to improve).


User manual:

I love it. May be I would develop a little bit the "Avoiding over-propagation and uncertain statements" section, by adding at least the "classical" examples of mitochondria and chloroplasts. I would also show a more complicated example such as "neurons" and "brain", and highlight where to propagate such terms in the frame of evolution (any other animal or plant organ could be fine).

In the "DO NOT propagate" section, I would mention the very general phenotypes, one extreme being "growth" (and even "cell proliferation" if the protein is not a cell-cycle protein).

It would also be important to mention somewhere that, in the case of families containing a lot of duplication events (especially when we have big patches of duplications for some organisms, i.e. plants),  propagation might be dangerous since MFs can be lost or diverge and CCs might be totally different.

Finally, the case of HTP does not appear anywhere, but I think this is a work in progress.

I hope this is helpful.

I wish you a great day.

Best regards.

**Comment by suzialeksander** [comment]
this ticket is 6+ years old and was last reviewed in 2021 so closing
