### ISSUE TITLE
Generate reports to replace the Google docs to track progress /lock families, etc

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1657]
Action item form Oct 2017 GOC meeting

Anushya/Huaiyu

**Comment by vanaukenk** [comment]
@pgaudet - do you want to have this issue in the PAINT tracker?

**Comment by pgaudet** [comment]
Hi @vanaukenk 
Similar to Noctua, this is really an annotation issue (PAINT annotation, but annotation). Is it OK to keep it here? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Moreover I'd like to assign this to @huaiyumi (I cannot assign an issue to a person not in the project; does anyone know how to do that?)

**Comment by vanaukenk** [comment]
@pgaudet - sure, fine to keep it here if it's really more of an annotation issue than a PAINT feature request; I couldn't quite tell from the title.

Do we just need to add @huaiyumi to the go-annotation project?

**Comment by pgaudet** [comment]
I think this is covered by http://pantree.org/tree/allTrees.jsp
