### ISSUE TITLE
Implement a check for terms for which curators should always use a more specific child term. (“Do not manually annotate”) 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1659]
Action item from Oct 2017 GOC meeting

First example is here: 
https://github.com/geneontology/go-annotation/issues/1648

This needs to be done stepwise to allow people to make corrections. We'll add other terms regularly.

**Comment by cmungall** [comment]
Remember and update the documentation for the rule with any changes made. This is what we have so far:
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000008.md

The contact is still Emily, this should be changed

@dougli1sqrd will implement the SPARQL for this, and point at reports

**Comment by ValWood** [comment]
- needs to be a soft check initially, report in Jenkins? is this where these go already.

**Comment by pgaudet** [comment]
Done https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000008.md

**Comment by ValWood** [comment]
Looks good. I see them in the file. All PomBase ones from PAINT
