### ISSUE TITLE
Odorant binding or odorant transport? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1660]
Hello, 
I have discovered a GO term, 'GO:0043563 odorant transporter activity', which has never been used, but that was evidently made for 'odorant binding proteins' such as those described in PMID:2010751

These proteins bind to hydrophobic odorant molecules and bring them in closer contact with receptors. However this family has been annotated to 'GO:0005549	odorant binding' . 

My question is, do people consider this transport ? 

Here are the annotations that we should consider moving. 

GENE PRODUCT DB	GENE PRODUCT ID	SYMBOL	QUALIFIER	GO TERM	GO NAME	ECO_ID	GO EVIDENCE CODE	REFERENCE	WITH/FROM	TAXON ID	ASSIGNED BY	ANNOTATION EXTENSION
UniProtKB	A2AEP0	Obp1b	enables	GO:0005549	odorant binding	ECO:0000314	IDA	PMID:9661663		10090	MGI	
UniProtKB	P08937	Obp1f	enables	GO:0005549	odorant binding	ECO:0000314	IDA	PMID:3388043		10116	RGD	
UniProtKB	Q78E14	Obp3	enables	GO:0005549	odorant binding	ECO:0000314	IDA	PMID:11473933		10116	RGD	
UniProtKB	Q9D3H2	Obp1a	enables	GO:0005549	odorant binding	ECO:0000314	IDA	PMID:9661663		10090	MGI	
UniProtKB:A0A0R4IM31 | ora1 | enables | GO:0005550                pheromone binding | ECO:0000314                 (IDA) | PMID:24831010 |   | 7955 | ZFIN
UniProtKB:B3DJV6 | ora1 | enables | GO:0005550                pheromone binding | ECO:0000314                 (IDA) | PMID:24831010 |   | 7955 | ZFIN

Thanks, Pascale

**Comment by hdrabkin** [comment]
I guess this wouldn't come to mind for me as a transport;

**Comment by deustp01** [comment]
What about SERPINA6, also known as corticosteroid-binding globulin? It's a serum protein that binds corticosteroids, enabling their efficient delivery to target tissue. The mouse homolog has GO annotations steroid binding (function), extracellular part of serum (component) and transport (process) - http://www.informatics.jax.org/go/marker/MGI:88278. (The name comes from its sequence similarity to serpins - I don't think there's any evidence that this one binds and inhibits serine proteases.)

**Comment by ValWood** [comment]
A carrier?

carriers are non-transporter MF involved in transport
https://www.ebi.ac.uk/QuickGO/term/GO:0140104

**Comment by ValWood** [comment]
actually this does not fit any of the available  carrier "types"
https://www.ebi.ac.uk/QuickGO/term/GO:0140104

but we have steroid and hormone type "carriers" to place under here

Also, not all carriers are involved in transport (acyl carrier for example).

Will open a ticket later for the 
I think these are probably "carriers"?
https://www.ebi.ac.uk/QuickGO/term/GO:0017127

I have a few things annotated to "sterol transport" and I have never been able to figure the mechanism/function that involves them in this process
http://preview.pombase.org/term/GO:0015918

**Comment by ValWood** [comment]
Yes some do appear to be just "diffusion"....really hard to figure out for some, for instance the metallochaperones. Whenever I have looked I haven't found good reviews for how these things work.....

**Comment by pgaudet** [comment]
Isn't it similar to what karyopherins do, for example? 
 
![image](https://user-images.githubusercontent.com/4782928/31788400-d911d218-b50e-11e7-9ba2-9c792372d850.png)

**Comment by hdrabkin** [comment]
The final "ligand" here is KaryoA or b bound to thing that actually gets transported across a membrane here.
In the cases of odorants, pheromones, itsn't it that they bind a receptor and then the receptor does something, not necessarily transporting the ligand across a membrane. 
But in the case above:
So do you say in the case above that karyopherin as transporter activity? I don't think so; The TM protein and appears to have the activity as it is moving the ligand complex across the membrane.
Is KaryoA involved in the transport if it is actually part of the ligand?

**Comment by ValWood** [comment]
@hdrabkin  agreed Karyopherins are currently housed under transporter, 
https://www.ebi.ac.uk/QuickGO/term/GO:0061608
but we have previously discussed their move under carrier
https://github.com/geneontology/go-ontology/issues/14336
(it's not TM transport though the membrane is not traversed, its part of "nucleocytoplasmic transport")

**Comment by sabrinatoro** [comment]
I looked at the annotations and the publication where these annotations are from. 
These gene products are receptors which binds to pheromone. Pheromone binding triggers a signal. There is no evidence at all of transport occurring. 
Based on the evidence available, I would not move these ZFIN annotations to  'GO:0043563 odorant transporter activity',

@pgaudet : I am removing my name from the "Assignees". Feel free to add me back if necessary (and sorry it took so long, I didn't see I was assigned until you mentioned it in the call

**Comment by hdrabkin** [comment]
The mgi annotation to odorant binding is a paper just studying that has no experimental evidence for the statement, and thus will be removed now

**Comment by pgaudet** [comment]
OK, then it sound like nobody needs this term 'GO:0043563 odorant transporter activity'; I'll put a ticket to obsolete it. 

Thanks, Pascale
