### ISSUE TITLE
Proposal for Protein complexes representation in Noctua 

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#1663]
_From @pgaudet on October 17, 2017 11:7_

At the Oct 2017  GOC meeting, we decided to form a working group to provide guidance for protein complex representation in Noctua: Formulate the issue; make a proposal 

_Copied from original issue: geneontology/noctua#517_

**Comment by bmeldal** [comment]
duplicate of https://github.com/geneontology/go-annotation/issues/1661 ?

I guess we added tickets before we saw what each other did!

**Comment by vanaukenk** [comment]
Yes, this is a duplicate of #1661 and since there is more information in that ticket, I am going to close this one.
