### ISSUE TITLE
ntr: cellular detoxification of flouride

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1665]
standard def

Any process carried out at the cellular level that reduces or removes the toxicity of a flouride. These may include transport of flouride away from sensitive areas and to compartments or complexes whose purpose is sequestration of the toxic substance.

does this also include "export"? this isn't clear from the standard def?

"Therefore, fluoride is toxic for S. pombe even at low concentrations, and specific channels that export fluoride ions are required for normal growth."

**Comment by ValWood** [comment]
PMID:27327046

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14391
