### ISSUE TITLE
ntr: fluoride transmembrane export across plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1666]
- [ ] ntr: fluoride transmembrane export across plasma membrane
standard def 
ref PMID:27327046

don't seem to have 

- [ ] ntr : export across plasma membrane  either?

- [ ] although we do have
GO:1903764    regulation of potassium ion export across plasma membrane
???
add parents

**Comment by mah11** [comment]
wrong tracker
