### ISSUE TITLE
ntr:  fluoride transmembrane export across plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1667]
- [ ] ntr: fluoride transmembrane export across plasma membrane
standard def 
ref PMID:27327046

don't seem to have 

- [ ] ntr : export across plasma membrane  either?

- [ ] although we do have
GO:1903764    regulation of potassium ion export across plasma membrane
???
add parents

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14390

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14396
