### ISSUE TITLE
Transcription factor branch refactoring: overview of annotations of TFIIIC and TFIIB complexes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1668]
Hello, 

The term 'transcription factor activity, protein binding', as well as its children, will be renamed (and possibly reorganized), since as they are it is very difficult for users to understand what function is being described. 

Before doing this, I wanted to understand how the terms had been used, so I started by looking at the MF annotations for proteins belonging to families annotated to the CC     GO:0000127 transcription factor TFIIIC complex. 

There are 6 subunits, corresponding to 6 PTHR families. I looked at the primary EXP MF annotations for all 6 families, and this is what I retrieved: 

**PTHR15180 Yeast TFC3,  Human GTF3C1**
•	contributes to DNA binding, bending (IDA) SGD
•	contributes to RNA polymerase III type 1 promoter sequence-specific DNA binding (IDA) SGD
•	contributes to RNA polymerase III type 2 promoter sequence-specific DNA binding (IDA) SGD
•	contributes to transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting (IDA) SGD
•	contributes to transcription factor activity, RNA polymerase III type 2 promoter sequence-specific binding, TFIIIB recruiting (IDA) SGD
•	**transcription factor activity, core RNA polymerase III binding** Pombase

 

**PTHR15052 Yeast TFC6, human GTF3C2** 
EXP: 
•	RNA polymerase III type 1 promoter sequence-specific DNA binding SGD
•	RNA polymerase III type 2 promoter sequence-specific DNA binding SGD
•	transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting SGD
•	transcription factor activity, RNA polymerase III type 2 promoter sequence-specific binding, TFIIIB recruiting SGD
•	chromatin insulator sequence binding	 Pombase
•	tDNA binding	Pombase
•	**transcription factor activity, core RNA polymerase III binding** Pombase

**PTHR23082 Yeast TFC4, human GTF3C3**
•	contributes to DNA binding, bending (IDA) SGD
•	contributes to RNA polymerase III type 1 promoter sequence-specific DNA binding (IDA) SGD
•	contributes to RNA polymerase III type 2 promoter sequence-specific DNA binding (IDA) SGD
•	contributes to transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting (IDA) SGD
•	contributes to transcription factor activity, RNA polymerase III type 2 promoter sequence-specific binding, TFIIIB recruiting (IDA) SGD
•	**transcription factor activity, core RNA polymerase III binding** Pombase

**PTHR15496  human GTF3C4**
No relevant annotations
GENERAL TRANSCRIPTION FACTOR 3C POLYPEPTIDE 4 FAMILY

**PTHR13230 human GTF3C5**

•	contributes to DNA binding, bending (IDA) SGD
•	contributes to RNA polymerase III type 1 promoter sequence-specific DNA binding (IDA) SGD
•	contributes to RNA polymerase III type 2 promoter sequence-specific DNA binding (IDA) SGD
•	contributes to transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting (IDA) SGD
•	**transcription factor activity, core RNA polymerase III binding** Pombase
•	chromatin insulator sequence binding	 Pombase
•	

**PTHR21860  human GTF3C6**
No relevant annotations

=====
transcription factor TFIIIB complex families & annotations

**PTHR10126 TBP, yeast SPT15**
tbpA (dicty, flybase, human, etc) 
Metazoa: TBP, TBPL1, TBPL2

•	chromatin binding (IDA) SGD
•	DNA binding, bending (IDA) SGD
•	RNA polymerase I transcription factor binding (IDA, IPI) SGD
•	RNA polymerase II activating transcription factor binding (IDA, IPI) SGD
•	RNA polymerase II core promoter sequence-specific DNA binding (IDA) SGD
•	RNA polymerase III regulatory region DNA binding (IDA) SGD
•	**TFIIIB-type transcription factor activity** (IC) SGD
•	**transcription factor activity, RNA polymerase I transcription factor recruiting** (IDA, IPI) SGD
•	**transcription factor activity, RNA polymerase II core promoter sequence-specific binding involved in preinitiation complex assembly** (IC) SGD
•	**RNA polymerase III transcription factor activity, sequence-specific DNA binding** Source: UniProtKB
•	**RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly** Source: CAFA
•	TFIIB-class transcription factor binding Source: CAFA
•	transcription factor binding Source: UniProtKB
•	transcription regulatory region DNA binding Source: UniProtKB
•	RNA polymerase II core promoter sequence-specific DNA binding	Pombase
•	**transcription factor activity, RNA polymerase I CORE element sequence-specific binding** Pombase
•	**transcription factor activity, RNA polymerase II core promoter sequence-specific** Pombase

**PTHR11618  Yeast BRF1**
Brf Flybase

•	RNA polymerase III type 3 promoter sequence-specific DNA binding Source: FlyBase
•	**RNA polymerase III type 3 promoter TFIIIB-type transcription factor activity** Source: FlyBase
•	transcription factor binding Source: FlyBase 
•	TBP-class protein binding Source: InterPro
•	DNA binding (IDA) SGD
•	RNA polymerase III core binding (IDA, IPI) SGD
•	**TFIIIB-type transcription factor activity** (IC) SGD
•	TFIIIC-class transcription factor binding (IDA, IPI) SGD

Human BRF2 
•	RNA polymerase III type 3 promoter DNA binding Source: UniProtKB
•	transcription factor activity, RNA polymerase III transcription factor binding Source: UniProtKB

Human GTF2B
•	TBP-class protein binding Source: CAFA
•	thyroid hormone receptor binding Source: UniProtKB
•	transcription factor binding Source: UniProtKB
Mouse GTF2
•	core promoter binding
Yeast SUA7

•	RNA polymerase II core binding (IDA, IPI) SGD
•	**RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly** (IDA, IMP) SGD
•	TBP-class protein binding (IDA, IPI) SGD
•	transcription factor activity, core RNA polymerase II recruiting (IDA, IMP) SGD
Pombe Sua7 
•	**RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly**

**PTHR22929 Yeast BDP1 (only annotated protein for MF)**
•	**TFIIIB-type transcription factor activity** (IC) SGD
•	TFIIIC-class transcription factor binding (IDA, IPI) SGD

**Comment by pgaudet** [comment]
Remarks for TFIIIB: 

There seem to be no difference in usage between 'GO:0001026 TFIIIB-type transcription factor activity' and its children: 
- GO:0001040 RNA polymerase III hybrid type promoter TFIIIB-type transcription factor activity
- GO:0001027 RNA polymerase III type 1 promoter TFIIIB-type transcription factor activity
- GO:0001028 RNA polymerase III type 2 promoter TFIIIB-type transcription factor activity
- GO:0001029 RNA polymerase III type 3 promoter TFIIIB-type transcription factor activity

**Comment by suzialeksander** [comment]
GO:0001026 was obsoleted 2021, assuming the rest of this cycle of TF revision is complete
