### ISSUE TITLE
Query: FBgn0037852 annotation to thiamine pyrophosphate-transporting ATPase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1671]
Hi @hattrill 
FBgn0037852 is annotated to 'thiamine pyrophosphate-transporting ATPase activity', which is the term for ABC-transporter. Looking at the paper I think the authors found that ATP is a transport substrate, but not that this is ATP-dependent. 

If you agree then the gene should be annotated to 'GO: thiamine transmembrane transporter activity' instead (and possibly to GO:0005347 ATP transmembrane transporter activity). 

Thanks, Pascale

**Comment by hattrill** [comment]
Most def. agree.
GO:0015234 thiamine transmembrane transporter activity
I think that "GO:0015297 antiporter activity" is also appropriate with the exchanged substrates as a has_input relationship.

**Comment by pgaudet** [comment]
Sounds good ! You can close the issue if it's resolved. 

Thanks, Pascale
