### ISSUE TITLE
odd and redundant inferences from  pipeline

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1682]
We are getting inference to "nucleus" via IMP.
this is a bit weird anyway, but 

PomBase	SPAC17G8.03c	bur6		GO:0005634	PMID:15388803	IMP	DNA polymerase epsilon interactor Dpb3-like	dpb3	protein	taxon:4896	20120829	GOC	

but we already have correctly

- | GO:0043596 | nuclear replication fork | IC from epsilon DNA polymerase complex | Spiga MG et al. (2004) | 61
- | GO:0005634 | nucleus | IMP | Spiga MG et al. (2004) | 2698
  | IDA | Spiga MG et al. (2004)

the additional IMP is very confusing and unecessary?

**Comment by ValWood** [comment]
Also

PomBase	SPBC25H2.13c	cdc20		GO:0005634	PMID:10888871	IMP	DNA polymerase epsilon catalytic subunit Pol2	pol2	protein	taxon:4896	20140903	GOC

is covered by the more specific 

GO:0000784 | nuclear chromosome, telomeric region | 53
-- | -- | --
during mitotic S phase | IDA

**Comment by ValWood** [comment]
and here
PomBase	SPCC736.12c	mmi1		GO:0005634	PMID:26670050	IMP	nucleus specific RNA binding exosome specificity factor Mmi1		proteintaxon:4896	20161130

is inferred from the nuclear surveillance terms

It seems very odd to have IMP to nucleus for this paper. They did not so any experiments to 
detect localization:
http://pombase-dev.bioinformatics.nz/reference/PMID:26670050

and the annotation is covered by other sources

**Comment by pgaudet** [comment]
@cmungall is this in the right tracker ?

**Comment by ValWood** [comment]
duplicate of 
https://github.com/geneontology/go-site/issues/576

But even if we did not have this annotation, we wouldn't make an IMP for this annotation (as curators), so I don;t think this should be made as an inference with this evidence code.

I'm not sure if it still is , or not...
