### ISSUE TITLE
Rbp4 and 	retinol transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1684]
Hello, 

Rbp4 binds retinol, and is annotated to 'retinol transporter activity' by RGD (RGD:3546), UniProt (P04916) and MGI (MGI:97879). However in the papers I cannot find the evidence of the transporter activity. Can people who made these annotations please check ? 

(I suspect the correct annotation is just 'retinol binding') 

Thanks, Pascale

(for https://github.com/geneontology/go-ontology/issues/14492)

**Comment by hdrabkin** [comment]
Hi Pascale; I'm locked out of our EI today so will have to look at this tomorrow if a fix is needed

**Comment by ggeorghiou** [comment]
Hi Pascale, the annotations in question are from PIR so I cannot edit them. I can email them to ask if they can review it unless we have a contact for PIR on GitHub that we can tag.

**Comment by pgaudet** [comment]
Hi @ggeorghiou, yes please contact PIR (you can also ask them if they want to be contacted directly next time; they can add their GitHub handle here: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

Thanks, Pascale

**Comment by slaulederkind** [comment]
I have removed the questionable annotations at RGD.

**Comment by ggeorghiou** [comment]
@pgaudet I heard back from PIR and they have removed the annotation.

**Comment by pgaudet** [comment]
great, thanks !

**Comment by hdrabkin** [comment]
Annotation to be removed; should be reflected in Friday's GAF and GPAD
