### ISSUE TITLE
RGD Cubn annotation to cobalamin transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1685]
Hi Stan, 

Cubn (RGD:68355) is annotated to cobalamin transporter activity; however it is rather an endocytic receptor. I suggest you move the annotation to 'GO:0038024 cargo receptor activity'. If you want a specific term for cobalamin please request it in the ontology tracker. 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Sorry, Pascale.  That annotation was imported from UniProt.

**Comment by pgaudet** [comment]
Sorry Stan ! 

@ggeorghiou can you please have a look ? 

Thanks, Pascale

**Comment by ggeorghiou** [comment]
@pgaudet I'll have a look at it today.

**Comment by ggeorghiou** [comment]
@pgaudet I reviewed the paper and agree. I will change the annotation to cargo receptor activity. Closing the issue

**Comment by pgaudet** [comment]
thanks  !
