### ISSUE TITLE
Folr1 RGD:71032 annotation to 'folic acid transporter activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1686]
Hi Stan, 

Folr1 RGD:71032 is annotated to 'folic acid transporter activity'; it should rather be ' folic acid receptor activity' since this protein mediates folic acid internalization by endocytosis. 

Can you please fix the annotation? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
The annotation has been removed.

**Comment by pgaudet** [comment]
thanks !
