### ISSUE TITLE
Relation to use for regulation terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1687]
_From @pgaudet on October 17, 2017 10:50_

At the Cambridge 2017 GOC meeting, it was decided that for assertions of type “Gene product involved_in X regulation”, we will use default ‘involved in’. 

This needs to be documented. 

(Question: Is the relation 'regulates to be obsoleted?) 

_Copied from original issue: geneontology/noctua#516_

**Comment by pgaudet** [comment]
_From @kltm on October 17, 2017 18:8_

@pgaudet What is the action here? If this for documentation within this repo, or more general documentation?

**Comment by pgaudet** [comment]
_From @kltm on October 17, 2017 18:28_

@pgaudet I see that there is also now a "Documentation" project. While a `documentation` label could be useful for marking non-code requests withing the repo, I'm not sure how you envision that interacting with a GH project?

**Comment by pgaudet** [comment]
_From @vanaukenk on October 17, 2017 19:7_

Hi,
I actually created the Documentation project in the Noctua repo yesterday to keep track of the status of overhauling the documentation for using Noctua.
There is some blurring on the Noctua repo of issues related to the mechanics/functionality/features of the tool with modeling decisions that might better be housed in the go-annotation repo.  
I also created a Documentation project in go-annotation, and am okay if we prefer to track Noctua/GO-CAM documentation there instead of in the Noctua repo.
--K.

**Comment by pgaudet** [comment]
_From @kltm on October 17, 2017 19:17_

@vanaukenk Great--thank you for the clarification. I'm still processing how this all hangs together (and trying to model what went wrong with the `go-site` repo).
As the "overhaul" part definitely maps to a concrete and bounded push (as I believe they should be) would you mind terrible if I added "overhaul" to the ticket and description? Also, do you have and feel for what columns you'll be using for that? We have a set that we're using for other noctua projects, but they might not be applicable for this use.

**Comment by pgaudet** [comment]
_From @vanaukenk on October 17, 2017 21:55_

@kltm  - Sure, feel free to add 'overhaul' to the ticket and description.
For columns, @ukemi started a Documentation project at geneontology and I think we would want to roughly mirror the columns there:
https://github.com/orgs/geneontology/projects/3
New Documentation Required
Documentation Updates Required
Documentation in Progress
Documentation Completed
I'd like to clarify on the managers call tomorrow, though, about exactly how we want to track documentation projects.  It makes sense to me to have them in specific repos, but I don't know if everyone feels that way,

**Comment by pgaudet** [comment]
_From @kltm on October 17, 2017 22:14_

@vanaukenk I've added "overhaul" to the project.
Would there be a good venue to discuss the columns that would be used (as we are already rather off-topic here)?

**Comment by pgaudet** [comment]
_From @vanaukenk on October 17, 2017 22:24_

@kltm - maybe a Skype with you, me @pgaudet @ukemi and anyone else interested to flesh out good practices in github project column use?  
I can see that the column names originally made for Documentation projects don't align with what exists for other projects, but maybe conceptually are not that far off.

**Comment by pgaudet** [comment]
_From @kltm on October 17, 2017 22:36_

@vanaukenk That would be fine with me.

**Comment by pgaudet** [comment]
_From @ukemi on October 18, 2017 11:8_

Me too.

**Comment by pgaudet** [comment]
Me too.

**Comment by RLovering** [comment]
This ticket seems to just discuss where to discuss this issue. It is not clear to me what you will be discussing here. 
Would it be possible to delete all the comments if they are not related to the original point as we have just spent ages reading comments that are not relevant to the actual initial ticket. 

Plus please explain what the initial ticket is addressing.

Thanks

Ruth
@rachhuntley @BarbaraCzub

**Comment by RLovering** [comment]
Hi

Can we clarify, that the statement:  'for assertions of type “Gene product involved_in X regulation”, we will use default ‘involved in’' means that for annotations in the format:
Gene product A: 'regulation of BP/MF' 
Then these annotations will continue to use the default relation 'involved_in':
Gene product A: involved_in 'regulation of BP/MF' 

But this seems to contradict the current practice of avoiding creating new regulation terms. 

Are new GO terms going to be post-composed? In which case won't there be new regulation terms created?

Also please keep in mind that the 'regulates' relations are commonly used in the Annotation extension field. We note that there are 2 places where 'relations' are being included, in the qualifier field and on the edge (which then becomes the annotation extension relation).

Plus we are concerned that there is a move to only use 'regulates' for gene products that 'directly regulate' and that all other 'regulation' processes will be considered causally_upstream_of. This implies that only 'activators' or 'inhibitors' can be associated with 'regulation' terms. Please confirm.

Thanks

UCL team
@rachhuntley @BarbaraCzub

**Comment by pgaudet** [comment]
We use 'involved in' GO: regulation of xx, see 
https://wiki.geneontology.org/Involved_in
