### ISSUE TITLE
IPR001640 annotation to GO:0009249 protein lipoylation 

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#1689]
It sounds almost right, but it is not.  A lipoate group is a specially modified octanoyl group that is attached to certain subunits in special multienzyme complexes like pyruvate dehdrogenase; lipoproteins are not modified with lipoate.

**Comment by asangrador** [comment]
Thanks for alerting us to this, I have removed 'protein lipoylation' term.

Amaia
