### ISSUE TITLE
Review annotations to 'allantoin uptake transmembrane transporter activity ' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1692]
Hello, 

There are 5 EXP annotations to 4 proteins to the term 'allantoin uptake transmembrane transporter activity (GO:0005274)' 

Yeast DAL4
TAIR UPS1, UPS2, UPS4, UPS15

The definition and the subclasses imply that it's a symporter ('Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: allantoin(out) + H+(out) = allantoin(in) + H+(in) by secondary active transport.'), also, it has a parent 'nucleobase:cation symporter activity'; but I am not completely sure that this has been showed in the paper. 

Another suspicious observation is that GO:0005274 has x ref 
http://www.tcdb.org/search/result.php?tc=2.A.39.3.1

but at least one of the children has a different one: 
http://www.tcdb.org/search/result.php?tc=2.A.7.19.3

Can you please confirm that all the annotated proteins are symporters ? 

Thanks, Pascale

**Comment by tberardini** [comment]
There are four annotations to GO:0005274 for three genes in _A. thaliana_, UPS1, UPS2, and UPS5 (two splice variants).  

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/4998871/33090780-0c216e16-ceaa-11e7-9f1c-620a951f7fdd.png">

Looking at this paper:

http://amigo.geneontology.org/amigo/reference/PMID:16738859

> Together these  data  indicate  that  AtUPS5l,  like  AtUPS1  and
AtUPS2,  mediates  H+-coupled  transport  of  its  substrates.

So, yes, these are symporters.  It looks like you went ahead and changed the primary term name already.

**Comment by pgaudet** [comment]
Thanks for confirming  @tberardini
