### ISSUE TITLE
IPR031824 mapping to GO:0090263

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1694]
IPR031824 has mapping to GO:0090263 positive regulation of canonical Wnt signaling pathway
Can't see extensive evidence that this is a conserved process interaction for this domain.

**Comment by EBI-Hsinyu** [comment]
Hi! 

RNF220 has been shown to enhance canonical Wnt signaling through USP7-mediated deubiquitination of beta-catenin.  Knockdown of RNF220 impairs Wnt signaling [PMID: 25266658]. 

Regards, 
Hsin-Yu

**Comment by hattrill** [comment]
Yes - but is this true of all proteins with this domain?

**Comment by EBI-Hsinyu** [comment]
Hi Helen, 
I have another look at this entry. It does hit fungal proteins. Therefore, this term is not applicable. I will delete this term. Thank you for letting us know. This will be visible in InterPro67.0.

Regards, 
Hsin-Yu

**Comment by hattrill** [comment]
Thanks!
