### ISSUE TITLE
PTHR11309 PANTHER:PTN000139394: remove wnt binding annotation to smoothened receptors

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1696]
Smoothened receptors don't bind wnt.

Please remove:
"Wnt-protein binding" GO:0017147 IBA - PANTHER:PTN000139394 for smoothened proteins
e.g. 
P91682 
Q99835

**Comment by hattrill** [comment]
Could I request another fix for this node?

GPCR activity to frizzled receptors as this is atypical of this class of receptor - exception rather than rule, evidence sporadic. 
Can you block the propagation of GO:0004930  "G-protein coupled receptor activity" from this node to frizzleds? ("NOT" not appropriate as a handful have been shown to have GPCR-like capabilities under certain circumstances)

**Comment by vanaukenk** [comment]
Note that fixing the propagation of GO:0004930 'G-protein coupled receptor activity' should also fix the annotations to GO:0007186 'G-protein coupled receptor signaling pathway' that are coming from F-P links between these two terms.

**Comment by hattrill** [comment]
Note: Issue also raised as part of #1229

**Comment by pgaudet** [comment]
> GO:0004930 "G-protein coupled receptor activity"


Gone
