### ISSUE TITLE
Please review annotations: 'synaptic vesicle endocytosis GO:0048488' and child terms

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-annotation#1697]
Dear Curators,

### Background
It has been brought to GO editors' attention that although 'synaptic vesicle endocytosis GO:0048488' is defined as a clathrin-dependent and is a child term of 'clathrin-dependent endocytosis GO:0072583' (QuickGO screenshots below), not all processes of synaptic vesicle endocytosis depend on clathrin. https://github.com/geneontology/go-ontology/issues/14540

![screen shot 2017-11-21 at 11 13 27](https://user-images.githubusercontent.com/16541096/33069634-0e4fd102-cead-11e7-83aa-1305c05118c5.png)
![screen shot 2017-11-21 at 11 11 41](https://user-images.githubusercontent.com/16541096/33069639-13779318-cead-11e7-8dde-48ee5feef3b3.png)

### Possible solutions
Two proposals have been made on how to address the above issue:
1. Change the GO term definition (and parent relations) of 'synaptic vesicle endocytosis GO:0048488' to include both clathrin-dependent and clathrin-independent mechanisms. Then create more specific child term(s).
2. Modify the GO term name of 'synaptic vesicle endocytosis GO:0048488' to 'clathrin-dependent synaptic vesicle endocytosis', and create a **_new_** parent term, which will be called 'synaptic vesicle endocytosis' and encompass both clathrin-dependent and clathrin-independent mechanisms.

### Required action
There are currently 97 experimentally-evidenced annotations to 'synaptic vesicle endocytosis GO:0048488' and its child terms, including '(positive/negative) regulation of synaptic vesicle endocytosis' terms [based on: AmiGO, accessed: 20 Nov 2017]:

- [x] BHF-UCL | 5 | @RLovering
- [x] CAFA | 7 | @ggeorghiou
- [x] FlyBase | 43 | @hattrill @gantonazzo
- [x] MGI | 9 | @krchristie @hdrabkin
- [x] ParkinsonsUK-UCL | 3 | @BarbaraCzub
- [ ] RGD | 2 | @slaulederkind
- [x] SynGO | 12 | @Pimmelorus @ftwkoopmans
- [x] SynGO-annotation-tool | 30 | @Pimmelorus @ftwkoopmans
- [x] UniProt | 10 | @ggeorghiou @pgarmiri @sylvainpoux
- [x] WB | 6 | @vanaukenk

1. Could members of each group please review their annotations to 'synaptic vesicle endocytosis GO:0048488' and its child terms, including regulation terms?
The aim is to check whether the experiments demonstrating the role of the annotated gene products in 'synaptic vesicle endocytosis' did indeed describe a clathrin-dependent process.
--> If you find annotations to this term (or children, incl. reg.) were not based on evidence demonstrating clathrin involvement, please flag and _**keep track**_ of these _within your groups_. 
2.  Then in this ticket, please indicate how many of your groups' annotations to this term, or its children, were indeed based on experiments that showed 'synaptic vesicle endocytosis' was clathrin-dependent.

### What next?
1. If the majority of the above annotations happen to **not** have been based on evidence demonstrating the involvement of clathrin, then the term definition will be changed (solution 1) to include clathrin-dependent and clathrin-independent mechanisms, and more specific child terms will be created for specific mechanisms. 
--> Then the _**new**_ more specific child terms, including 'clathrin-dependent synaptic vesicle endocytosis', can be used by curators to update their existing annotations, for which clathrin involvement was demonstrated.
2. If the majority of the above annotations happen to have been based on evidence demonstrating the involvement of clathrin, then the term name will be changed (solution 2) to 'clathrin-dependent synaptic vesicle endocytosis', and a _**new**_ more general parent term 'synaptic vesicle endocytosis', encompassing clathrin-dependent and clathrin-independent mechanisms, will be created. 
--> Then curators will be requested to use the _**new**_ more general parent term to update their existing annotations, for which there was **_no_** evidence for clathrin involvement.

### Timeframe

Could you please aim to get these reviewed by the **_12th of December_**?

Thank you,
Barbara

cc:
@RLovering 
@paolaroncaglia 
@thomaspd 
@dosumis 
@jblake
@ukemi 
@pgaudet

**Comment by vanaukenk** [comment]
@BarbaraCzub 
I've looked at all of the C. elegans annotations at WB and all of the gene products annotated to GO:0048488 participate in clathrin-dependent synaptic vesicle endocytosis.  Thx.

**Comment by pgarmiri** [comment]
Hi @BarbaraCzub ,
I checked the UniProt and CAFA annotations and all seem to be involved in clathrin-dependent synaptic vesicle endocytosis. 
Thanks,
 Penelope

**Comment by BarbaraCzub** [comment]
<img width="682" alt="screen shot 2017-11-22 at 11 01 15" src="https://user-images.githubusercontent.com/16541096/33124343-81d5c72c-cf74-11e7-85be-e99d450624ba.png">

**Comment by BarbaraCzub** [comment]
Thank you @vanaukenk @pgarmiri and @RLovering for checking these.

**Comment by BarbaraCzub** [comment]
I checked the ParkinsonsUK-UCL annotations and all seem to be involved in clathrin-dependent synaptic vesicle endocytosis (based on TAS + author intent).

**Comment by krchristie** [comment]
I've checked all of the mouse ones. For half of them, there was nothing in the paper that allowed me to say that the process was clathrin-dependent.

There was also one where I thought that the paper actually talked more about "synaptic vesicle recyling", which leads me to ask what is the difference between these two terms, and if they aren't identical, why isn't there a relationship between the two?

`Term`: synaptic vesicle endocytosis (GO:0048488)
`Def`: Clathrin-mediated endocytosis of presynaptic membrane that **recycles** synaptic vesicle membrane and its components following synaptic vesicle exocytosis. This process starts with coating of the membrane with adaptor proteins and clathrin prior to invagination and ends when uncoating has finished.

`Term`: synaptic vesicle recycling via endosome (GO:0036466)
`Def`: Synaptic vesicle **recycling** where vesicles endocytose via clathrin-coated pits, re-acidify, and refill with neurotransmitters after passing through an endosomal intermediate.

**Comment by Pimmelorus** [comment]
@krchristie 
>There was also one where I thought that the paper actually talked more about "synaptic vesicle recycling", which leads me to ask what is the difference between these two terms, and if they aren't identical, why isn't there a relationship between the two?

Different papers use this to relate to different aspect of the reuse of SVs after exocytosis. However, in the seminal paper __Synaptic vesicle recycling: steps and principles__ ([PMID:24596248](https://www.ncbi.nlm.nih.gov/pubmed/24596248/) of Rizolli (key opinion leader in this field) SV recycling is:

> The SV components are subsequently retrieved from the plasma membrane of the presynaptic neuron (endocytosis) and are turned into a new fusion-competent SV. The best name for this process has been proposed by Heuser and Reese (1973): synaptic vesicle recycling.

So, in the context of this discussion, it includes kiss-an-run exocytosis, and bulk and clathrin-mediated forms of endocytosis modes of SV retrieval from the plasma membrane, the (optional) processing and sorting of SV proteins in the endosomal compartment and acidification followed by refilling with neurotransmitter.

I several paper I have seen the _recycling_ term used in a more restricted scope to represent the endocytocis process, however. So, the term is used inconsistently in literature.

>Term: synaptic vesicle recycling via endosome (GO:0036466)
Def: Synaptic vesicle recycling where vesicles endocytose via clathrin-coated pits, re-acidify, and refill with neurotransmitters after passing through an endosomal intermediate.

I annotate for SynGO (synapse gene ontology) and this term is NOT part of our implementation of processes. It seems to be implemented by the Parkinson project. This term is in agreement with the definition by Rizolli, but is limited in use (problematic in my view) because it couples the _recycling_ concept to certain events that may or may not occur during the _recycling_ of SV's.

1. Not all SVs are endocytised after exocytosis (_kiss-and-run_ excytosis)
2. Not all SVs endocytised via endocytosis pass the endosome (immediate refilling).
3. Not all SV endocytosis via the endosome involves clathrin-mediated endocytosis (_bulk endocytosis_)

One may make use of this term, but uniformed use of it may cause undesired misassignments when uninformed users will use this term.

**Comment by BarbaraCzub** [comment]
Thanks @krchristie for confirming that it is a 50:50 ratio for mouse.

@pgaudet perviously asked the same question re: synaptic vesicle recycling via endosome (GO:0036466). I have made a note to revise this term.

Thanks @Pimmelorus for your comments on this and for the PMID reference.

**Comment by hattrill** [comment]
Hi @BarbaraCzub I've had a look at the FlyBase experimental evidence annotations.

About half refer specifically to clathrin-dependent processes, the rest either make no distinction or others include clathrin-independent mechanisms.

PMID:19640479	Clathrin-dependent
PMID:20111007	Clathrin-dependent
PMID:14634669	Clathrin-dependent
PMID:14627659	Clathrin-dependent
PMID:15824135	Clathrin-dependent
PMID:21029287	Clathrin-dependent
PMID:9118220	Clathrin-dependent
PMID:21606364	Clathrin-dependent
PMID:16269341	Clathrin-dependent
PMID:11927550	Clathrin-dependent
PMID:11955450	Clathrin-dependent
PMID:19737521	Clathrin-dependent
PMID:9883738	Clathrin-dependent
PMID:16600855	Clathrin-dependent
PMID:20704589	Clathrin-dependent and independent
PMID:15260956	Clathrin-dependent and independent
PMID:14622578	Clathrin-dependent and independent
PMID:28414717	Clathrin-dependent and independent
PMID:19066280	Clathrin-independent
PMID:19571145	Clathrin-independent
PMID:17620409	Not distinguished
PMID:15260957	Not distinguished
PMID:15014125	Not distinguished
PMID:19379781	Not distinguished
PMID:22998870	Not distinguished
PMID:15998804	Not distinguished
PMID:20410372	Not distinguished
PMID:25228693	Not distinguished
PMID:9822725	Not distinguished

**Comment by BarbaraCzub** [comment]
Thanks @hattrill

**Comment by ftwkoopmans** [comment]
Hi,

As Pim mentioned, we use 'synaptic vesicle endocytosis (GO:0048488)' as the
umbrella term and we think its definition should not restrict to 'clathrin
mediated' endocytotic mechanisms. For quite some annotations we made
against this term, the experimental evidence cannot discriminate between
clathrin dependent/independent.

Within the SynGO consortium we decided last year to postphone the
development of a more detailed ontology model for synaptic endocytosis. We
prioritized getting respective experts onboard, collect evidence for all
(known) proteins involved in synaptic endocytosis and make annotations to
the more generic terms so we establish a foundation for future work.

Synaptic endocytosis is an active field of research with lots of new
insights and perspectives beyond the classic clathrin mediated endocytosis.
To me, a major challenge would be adding terms that appreciate the time
scales at which different modes of endocytosis take place, their
distinct(?) molecular mechanisms and the circumstances that dictate which
mode of endocytosis is used. Further, many proteins involved in endocytosis
play a role in multiple modes of endocytosis (so we probably need to review
experimental assays, which endocytosis sub-processes / mechanisms can we
actually observe/discriminate?). Very interesting and timely given all the
new papers that came out in the last year, but bringing all this together
is not trivial in my opinion. We intend to work on this in the future and
engage with experts in our field, some already joined SynGO over the last
year, but unfortunately not at this point in time. So if we can now broaden
the inclusion criteria in the definition for SV endocytosis (GO:0048488),
we are happy to keep the endocytosis terms in the SynGO goslim as they are
for the time being.

Cheers,
Frank

**Comment by BarbaraCzub** [comment]
Thank you for taking the time to review your annotations.

During [yesterday's ontology call](http://wiki.geneontology.org/index.php/Ontology_meeting_2017-11-27) it was agreed that solution 1 will be more suitable based on the comments, which you provided regarding your existing annotations. 
I.e. I will change the GO term definition (and parent relations) of 'synaptic vesicle endocytosis GO:0048488' to include both clathrin-dependent and clathrin-independent mechanisms. I will then create more specific child term(s).

If you wish to update some of your GO annotations to the more specific child terms afterwards, the ontology development aspects can be tracked in the following ticket: geneontology/go-ontology#14540 

Thanks again,
Barbara

**Comment by BarbaraCzub** [comment]
The GO IDs for the new child terms are:

+id: GO:0150007
+name: clathrin-dependent synaptic vesicle endocytosis

and

+id: GO:0150008
+name: bulk synaptic vesicle endocytosis
