### ISSUE TITLE
PANTHER:PTN000236067: "valine-tRNA ligase activity" being wrongly associated with leucine tRNA ligases

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#1698]
Please review this PAINT inference.
At least human LARS (UniProtKB:Q9P2J5) and fly LeuRS (UniProtKB:Q9VQR8) are wrongly getting a "GO:0004832	valine-tRNA ligase activity" annotation at the moment.  (I'm sure other species are affected too.)
@hattrill

**Comment by marcfeuermann** [comment]
In PANTHER 13, the original tree containing several amino acyl-tRNA synthetases has been split. Now all the LARS are in PTHR45794 and are correctly annotated.
