### ISSUE TITLE
PANTHER:PTN000078673: "glycine-tRNA ligase activity" being wrongly associated with DNApol-gamma

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#1699]
Please review this PAINT inference.
At least human POLG2 (UniProtKB:Q9UHN1) and fly DNApol-gamma35 (UniProtKB:Q9VJV8) are wrongly getting a "GO:0004820	glycine-tRNA ligase activity" annotation at the moment.  (I'm sure other species are affected too.)

@hattrill

**Comment by marcfeuermann** [comment]
Annotation propagations of "glycine-tRNA ligase activity" and "glycyl-tRNA aminoacylation" have been blocked for PTN002473373 containing the DNA polymerase subunit POLG2 of many species. This node has been annotated to DNA polymerase-related terms.

**Comment by sjm41** [comment]
Thanks Marc!
