### ISSUE TITLE
GO annotation camp issues from Alex/MGI.

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#17]
This is just a short list of annotation issues of interest to me, 
not necessarily to other curators at MGI, which I would like 
discussed at the GO annotation camp.

1)  Use of response to virus, bacteria, fungus terms for 
immune responses, and detection of etc.

2)  "extracellular space" for PM proteins versus 
"extracellular" versus "external side of plasma membrane" 
versus "extrinsic to plasma membrane" versus "cell surface"

3)  IGI annotations and double knockout papers. PMID: 
15066262 Neuron. 2004 Apr 8;42(1):23-36. PMID: 14738763 
Immunity. 2004 Jan;20(1):37-46.

4)  Proper annotation of signaling pathways.

-\- Alex

Reported by: addiehl

Original Ticket: "geneontology/annotation-issues/17":https://sourceforge.net/p/geneontology/annotation-issues/17

**Comment by linuxlovell** [comment]
thanks www.movied.org
