### ISSUE TITLE
Annotation review : protein import into the nucleus

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1700]
| EXP | BHF-UCL | UniProt+CAFA | MGI | ZFIN | RGD | SGD | Flybase | AgBase | dictyBase | HGNC | Pombase | Wormbase | TAIR
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
GO:0000189 MAPK import into nucleus | 2 |   | 1 |   |   |   |   | 1 |   |   |   |   |   |  
GO:0000201 MAPK import into nucleus   involved in cell wall organization or biogenesis | 0 |   |   |   |   |   |   |   |   |   |   |   |   |  
GO:0000208 MAPK import into nucleus   involved in osmosensory signaling pathway | 1 |   |   |   |   |   | 1 |   |   |   |   |   |   |  
GO:0002146 steroid hormone receptor   import into nucleus | 0 |   |   |   |   |   |   |   |   |   |   |   |   |  
GO:0002147 glucocorticoid receptor import   into nucleus | 1 |   |   |   |   | 1 |   |   |   |   |   |   |   |  
GO:0006608 snRNP protein import into   nucleus | 1 |   |   |   |   |   |   | 1 |   |   |   |   |   |  
GO:0006609 mRNA-binding (hnRNP) protein   import into nucleus | 7 |   |   |   |   |   | 7 |   |   |   |   |   |   |  
GO:0006610 ribosomal protein import into   nucleus | 6 |   | 3 | 2 |   |   | 1 |   |   |   |   |   |   |  
GO:0007184 SMAD protein import into   nucleus + GO:0060390, GO:0060391, GO:0060392 regulation | 42 | 13 | 11 | 3 |   | 1 |   | 13 | 1 |   |   |   |   |  
GO:0007262 STAT protein import into   nucleus + regulation | 17 | 1 | 5 | 2 |   |   |   |   | 6 | 3 |   |   |   |  
GO:0035048 splicing factor protein import   into nucleus | 7 |   | 1 |   |   |   |   | 6 |   |   |   |   |   |  
GO:0035105 sterol regulatory element   binding protein import into nucleus | 2 |   | 1 | 1 |   |   |   |   |   |   |   |   |   |  
GO:0035411 catenin import into nucleus   +    GO:0035412, GO:0035413, GO:0035412   regulation | 38 | 17 | 10 | 5 | 5 | 1 |   |   |   |   |   |   |   |  
GO:0035424 MAPK import into nucleus   involved in innate immune response | 0 |   |   |   |   |   |   |   |   |   |   |   |   |  
GO:0036283 positive regulation of   transcription factor import into nucleus in response to oxidative stress | 2 |   |   |   |   |   |   |   |   |   |   | 2 |   |  
GO:0042348 NF-kappaB import into nucleus   + GO:0042345, GO:0042346, GO:0042347 regulation | 42 | 11 | 16 | 9 |   | 2 |   | 1 | 2 |   | 1 |   |   |  
GO:0042991 transcription factor import   into nucleus + GO:0042990 GO:0042992 GO:0042993 regulation | 65 | 11 | 14 | 3 |   | 2 | 12 | 3 | 8 |   |   | 1 | 5 | 6
GO:0044376 RNA polymerase II complex   import to nucleus | 8 |   |   |   |   |   | 8 |   |   |   |   |   |   |  
GO:0051531 NFAT protein import into   nucleus + GO:0051532 GO:0051533 GO:0051534 regulation | 22 |   | 8 | 11 |   | 2 |   | 1 |   |   |   |   |   |  
GO:0071167  ribonucleoprotein complex import into   nucleus | 1 IC | 1 |   |   |   |   |   |   |   |   |   |   |   |  
GO:0071512 MAPK import into nucleus   involved in conjugation with cellular fusion | 0 |   |   |   |   |   |   |   |   |   |   |   |   |  
GO:1990236 proteasome core complex import   into nucleus | 1 |   |   |   |   |   |   | 1 |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |

**Comment by ValWood** [comment]
Hi Pascale,
It's difficult to read in this format (you cant see rows and columns at the same time)
I fixed moved up ours to 
GO:0036283 
GO:0042993
(was redundant with info in extensions)
were there any others for PomBase?
v

**Comment by pgaudet** [comment]
Here's the original document

[import_into_nucleus.xlsx](https://github.com/geneontology/go-annotation/files/1495767/import_into_nucleus.xlsx)

**Comment by pfey03** [comment]
I took care of the 3 Dicty annotations (Q54I36, P18161). Extensions were already there, just updated the terms from GO:2000366 positive regulation of STAT protein import into nucleus
to
GO:0042307 positive regulation of protein import into nucleus

**Comment by sabrinatoro** [comment]
I have reviewed the ZFIN annotations and moved the annotation to "protein import into nucleus" or "negative regulation of protein import into nucleus".
However, we are currently unable to capture annotation extensions, and therefore the protein imported.

**Comment by vanaukenk** [comment]
@ValWood and @pfey03  - What annotation extension relations are you using?
Looking at the list, it seems that several may be applicable (although some only for regulation terms):
has_input
has_regulation_target
regulates_transport_of
transports_or_maintains_localization_of

**Comment by pfey03** [comment]
@vanaukenk
Since my terms have been 'positive regulation of STAT protein import into nucleus' and the two annotated proteins are kinases, it has been used and I left as is: is_regulation_target.

**Comment by tberardini** [comment]
@pgaudet I'm not clear on why I am supposed to be reviewing annotations.

TAIR has 6 direct annotations to 'transcription factor import into nucleus'.  What's the goal of the review?

**Comment by pgaudet** [comment]
Hi @tberardini 
The goal is to obsolete all terms that refer to import of specific proteins (or specific classes of proteins, such as transcription factors). All nuclear proteins are imported by the same nuclear import mechanism; if there are exceptions we should create terms that describe the different mechanism. 

Does this answer your question? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@sabrinatoro 
Would it be possible to use Noctua to make these annotations, as a temporary solution until ZFIN can make annotation extensions ? 

Thanks, Pascale

**Comment by ValWood** [comment]
We used has_regulation_target too as regulation terms....I guess we could be more specific and use 
regulates_transport_of . we haven't included that relationship but it could be inferred from the combination of "has_regulation_target" and "regulation of transport" term.

We need to look at this one again anyway..the abstract says
On imposition of oxidative stress, the Pap1 protein relocalizes from the cytoplasm to the nucleus in a process that is dependent on the Sty1 kinase. This relocalization is the result of regulated protein export, rather than import, and involves the Crm1 (exportin) nuclear export factor and the dcd1+/pim1+ gene that encodes an Ran nucleotide exchange factor.

So it seems to be regulating export, not import!

**Comment by hattrill** [comment]
I have moved the FlyBase annotations.

**Comment by sabrinatoro** [comment]
@pgaudet 
I could use Noctua to make the annotation extensions, but it won't be available for some times. I think it is ok though, there aren't many.

**Comment by vanaukenk** [comment]
The WB annotations are moved.  I used 'regulates transport of' in the annotation extensions to capture the target of the regulation.

**Comment by slaulederkind** [comment]
RGD has moved all of the annotations from protein-specific terms to more generic terms.

**Comment by tberardini** [comment]
I've reviewed and cleaned up the TAIR annotations.  Updates will be visible in the GAF that will be released at the end of December 2016/beginning of January 2018.

**Comment by pgaudet** [comment]
As far as I can tell only BHF  @RLovering and MGI @hdrabkin have not yet responded - can you please have a look ? 
Thanks, Pascale

**Comment by RLovering** [comment]
Hi
for the signaling proteins that are regulating the transcription factor import into the nucleus what is the alternative. I appreciate that only proteins actually importing proteins into the nucleus should be annotated to the 'process' term. But I haven't got my head around how we are going to capture the downstream impact of signaling proteins.

For example I could annotate the ligands as 'positive regulation of DNA binding transcription factor activity' and then list the DbTFs regulated, but SMADs act as complexes and it is the complex formation that is required before their import into the nucleus. What is the plan for terms such as SMAD protein signal transduction?

The term transforming growth factor beta receptor signaling pathway does include regulation of transcription but I don't think we could use AE to state which SMAD proteins are involved in the increase in transcription following stimulation of this pathway. If this is constructed in GO-CAM what GPAD exported AE relationships would be created to capture this?

**Comment by hdrabkin** [comment]
FWIW:
We have noticed that we are getting some of these through IBA annotations (PAINT). 
The family that is the source of the IBA annotations for 5 mouse genes is this one: 
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR10527 
You can see the 6 mouse genes in the family here:
http://www.pantherdb.org/genes/geneList.do?searchType=basic&loggedPrivilege=false&fieldName=all&fieldValue=PTHR10527*&listType=1&organism=Mus%20musculus 
One of them, Kpnb1, has an IDA annotation to this term, while the other 5 have annotations to this term by IBA.

The IBA annotations need to be addressed in the PAINT annotation stream.

**Comment by pgaudet** [comment]
Ignore IBAs. Normally the stats I gave were for EXP. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
So it turns out that not all import into nucleus uses the same pathways; Specifically, 
"L12 (rpL12) is distinguished from the bulk of ribosomal proteins because it accesses the importin 11 pathway as a major route into the nucleus (PMID:11809816 for Ipo11.  So I guess even "ribosomal protein import into nucleus" might even have 'flavors', not just 'protein import into nucleus'

**Comment by ValWood** [comment]
Different proteins use  specific importins and exportins, but do we require  process terms for every "carrier"

instead:

"importin a"  "protein import into nucleus"  has_imput cargo protein x
"importin b"  "protein import into nucleus"  has_input cargo protein y

etc...
(its the same mechanism, with a different carrier)

**Comment by deustp01** [comment]
I'm way out of date on this but my recollection is that the processes mediated by different importins and exportins can differ at the level of molecular function details, so the answer may be "sometimes, yes" but an up-to-date expert is needed to figure out which those times are.

**Comment by ValWood** [comment]
That is true (certain importins are required for specific cell cycle regulators, for example) but in those cases you can do

"importin a" "protein import into nucleus" has_input "cargo protein x", part_of "process z"

**Comment by bmeldal** [comment]
In the CP we have importin complexes from 4 species and consistently used:

GO:0000060 protein import into nucleus, translocation - which is part_of GO:0006606 protein import into nucleus

I guess no change required?

**Comment by pgaudet** [comment]
Hi @bmeldal 
Right, the term 'GO:0000060 protein import into nucleus, translocation ' was not being discussed here - but I wonder if it's useful in this case ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
The def 

> A protein transport process that contributes to protein import into the nucleus, and that results in the vectorial transfer of a cargo-carrier protein complex through the nuclear pore complex from the cytoplasmic side to the nucleoplasmic side of the nuclear envelope.

is exactly what importins do. What would be the objections to using it?

**Comment by pgaudet** [comment]
Hi @bmeldal 

If it corresponds to what importin does, then we are talking about a function, and not a process. Perhaps that process is not necessary ? 

Thanks, Pascale

**Comment by deustp01** [comment]
Getting a cargo into the nucleus includes steps of assembly in the cytosol, traversal of the nuclear pore, disassembly within the nucleus and (possibly, depending on how one defines the boundaries for the process) return of proteins other than the cargo to the cytosol, and each of these steps is associated with distinct acts of binding, movement, and GTP hydrolysis, so it looks like a process.

**Comment by pgaudet** [comment]
Hi @deustp01 

just to make sure we are talking about the same thing: the definition above is for 
"protein import into nucleus, translocation" (A protein transport process that contributes to protein import into the nucleus, and that results in the vectorial transfer of a cargo-carrier protein complex through the nuclear pore complex from the cytoplasmic side to the nucleoplasmic side of the nuclear envelope.) which is a sub-step of nuclear import. 

I was saying that this part sounds like the *function* of importin.

Apologies if I misunderstood your message. 

Thanks, Pascale

**Comment by deustp01** [comment]
No, you're right.

**Comment by bmeldal** [comment]
It wasn't my def, it's the GO def :) And it's currently a process.

**Comment by bmeldal** [comment]
Ok, combining all the comments made on 3 tickets about nucleocytoplasmic transport/import/carriers and the new terms @pgaudet added in https://github.com/geneontology/go-ontology/issues/14336 I conclude that our importins should be annotated to the new term **GO:0061608 nuclear import signal receptor activity**. 

But I'm struggling to work out what larger process it's involved in: As transporters have been defined as static and importins are carriers it's not transport. Likewise, the translocation terms are all children of transport. Surely, we must be able to put this into the broader context of a process?

**Comment by pgaudet** [comment]
Hi @bmeldal 
It seems to me both carriers and transports *could* act in the BP transport. Perhaps the exception is the acyl carrier-types of carriers, but importins and hemoglobin are certainly involved in transport. 

Does that seem OK ? Or do you see an inconsistency here ? 

Thanks, Pascale

**Comment by ValWood** [comment]
The process you need for importins and exportins is
nucleocytoplasmic transport!
https://www.ebi.ac.uk/QuickGO/term/GO:0006913

v

**Comment by bmeldal** [comment]
Thanks, Val. 
So, for importins it would be the child GO:0051170 nuclear import?

The discussion about transport and who does which movement got me a little confused :)

**Comment by ValWood** [comment]
Yes that's correct (nuclear import).

So, the main "types" of transport are
GO:0055085    transmembrane transport
GO:0006913    nucleocytoplasmic transport
GO:0016192    vesicle-mediated transport
GO:0099111    microtubule-based transport
and then there is the "flip flopping" between membrane leaflets (translocases), which we have no process grouping for. There are probably a couple of other types mediated by carriers, but I get a bit confused by these. Some appear to only be chaperones and not part of a transport process.
These general types of transport get a bit hidden under "transport" because of all of the substrate specific terms.

**Comment by srengel** [comment]
what is the preferred replacement for GO:0000208 MAPK import into nucleus involved in osmosensory signaling pathway?

**Comment by bmeldal** [comment]
Along these lines, should GO:0042564 NLS-dependent protein nuclear import complex have importin as a narrow synonym?

>A dimer consisting of an alpha and a beta-subunit that imports proteins with an NLS into the nucleus through a nuclear pore. 

If yes, I'll make a separate ticket but wanted to keep the train of thought in the same place!

**Comment by bmeldal** [comment]
All CP importins updated with MF and BP acc to above discussion.

**Comment by ValWood** [comment]
Personally I don't think it's a different process....Some things might not have NLS but they are imported with something that has.... I don't think "NLS-dependent" needs to be a term....Isn't all nucleocytoplasmic transport NLS dependent, its just that only sometimes is the NLS identified....

**Comment by srengel** [comment]
i've fixed the SGD ones that were to GO:0044376 RNA polymerase II complex import to nucleus.
still working on the others.

**Comment by pgaudet** [comment]
Hi @srengel 

> what is the preferred replacement for GO:0000208 MAPK import into nucleus involved in osmosensory signaling pathway?

There is no preferred replacement, it depends on what protein you are annotating. It does sound like the end point of some 'osmotic signaling', so a suggestion might be MAPK signaling or regulation of MAPK signaling ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I'm still a bit confused about how we handle import as part of a signalling pathway. The advice seems to be conflicting because at the signalling meeting there was advice that it is not part of the signalling. I'm not sure we have this quite figured out and it's probably one of the points that needs revisiting. What do the guidelines from the signalling meeting say  about this the moment (are there any?)

Also, we never achieved a consensus on how to name the  individual MAPK pathways. The  consensus 3-way split presented at the signalling meeting was very human centric.
I tried to fit the yeast to this 3-way split (it does fit), but if we use it the names of the pathways would need some work.
https://github.com/geneontology/go-ontology/issues/14676
https://github.com/geneontology/go-annotation/issues/1597

**Comment by ValWood** [comment]
@srengel what did you use for 
GO:0044376 RNA polymerase II complex import to nucleus
as we had ISS'd to it. I remember querying when I made the ISS's and I thought it was a specific pathway.

**Comment by srengel** [comment]
@ValWood to replace GO:0044376 RNA polymerase II complex import to nucleus i used 6606 protein import into nucleus then put the subjects in col16.

**Comment by srengel** [comment]
changed GO:0000208 MAPK import into nucleus involved in osmosensory signaling pathway to to 6606 has direct input HOG1 part of 161

changed GO:0006610 ribosomal protein import into nucleus to 6606 has direct input RPL25

still have to do 6609 and 42991.

**Comment by srengel** [comment]
changed the 6609's to 6606 with transportee in col16.

**Comment by srengel** [comment]
42990 changed to 42306 regulates transport of SWI6

**Comment by srengel** [comment]
42992 changed to 42308 transportee in col16

**Comment by srengel** [comment]
done.  changed all the 42990 to 6606 with col16 entries.

**Comment by pgaudet** [comment]
Dear all, 

To monitor progress on this ticket I have created a Google doc with remaining annotations: 
https://docs.google.com/spreadsheets/d/1JbDRDBqkxr1rHU-7j8bPfw0GABq_Z1qPwIjDwFaoe2E/edit#gid=0

I apologize if you have already reviewed the annotations and that this is not yet visible in Amigo, but there are still annotations to these terms from the following groups: 

AgBase  @jinhuiz
FlyBase @hattrill  
SGD @srengel 
MGI @hdrabkin 
UniProt @ggeorghiou 

These terms will be obsoleted next week, see 
https://github.com/geneontology/go-ontology/issues/13686

Thanks, Pascale

**Comment by srengel** [comment]
SGD has changed all relevant annotations.  not sure why the updates are not yet visible in AmiGO.  we can see the updates in P2GO and on our own website.

**Comment by hdrabkin** [comment]
Hi @srengel stacia
I suspect there is a pipeline issue: note that at the GO web page, the most recent SGD GAF is listed as "9/13/2017"! We have the same problem with the MGI gaf file date.

**Comment by hdrabkin** [comment]
OK I think I got them all

**Comment by hattrill** [comment]
These were changed. AmiGO out of sync.

**Comment by ValWood** [comment]
Hi @srengel stacia
I suspect there is a pipeline issue: note that at the GO web page, the most recent SGD GAF is listed as "9/13/2017"! We have the same problem with the MGI gaf file date.

Is there a ticket about this that we can follow to know when the data is current again?
we are using the current GO database for an analysis for a paper. We'd like to be able to report a 2018 data not 2017...

@cmungall 

@Antonialock  - please note

**Comment by ValWood** [comment]
I am opening one now!

**Comment by ValWood** [comment]
https://github.com/geneontology/amigo/issues/472

**Comment by hdrabkin** [comment]
I already put a ticket in at on the GO-sites. #542 
I put it there because "A collection of metadata, tools, and files associated with the Gene Ontology public web presence. "
