### ISSUE TITLE
GO:0008282 list of dubious co-occurring terms

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-annotation#1701]
I made a comment in https://github.com/geneontology/go-ontology/issues/11989 on 29/7/2015 about dodgy looking co-annotation to  GO:0008282 ATP-sensitive potassium channel complex (about to be renamed to "inward rectifying potassium channel"):

> I'm dubious if these co-annotations are correct:

GO:0005244 voltage-gated ion channel activity
GO:0005249 voltage-gated potassium channel activity
GO:0015272 ATP-activated inward rectifier potassium channel activity
GO:0015467 G-protein activated inward rectifier potassium channel activity [can't find this as co-annotation any more so must have been fixed]
and
GO:0008076 voltage-gated potassium channel complex
and even
GO:0005242 inward rectifier potassium channel activity

>because:
>A) ATP inhibits the channel, and
>B) activation is either by mechanical means (in cardiac cells) or by changing the intracellular ATP or MgADP or extracellular glucose concentration (in pancreatic beta-cells) rather than voltage change (see def of GO:0005242 inward rectifier potassium channel activity, last annotation above). >In fact, Kir6 channel activity results in voltage change and at least in pancreatic beta-cells this activates the Ca2+ channels which results in insulin release.

>The names of the above terms are in parts misleading but the defs clearly refer to either ATP-dep or voltage-gated activation.

The annotations were to the following proteins:
Q14654 BHF @RLovering 
Q09428 Reactome @deustp01 
[O60706-1]
[O60706-2]
O60706
Q61743
B2RUS7
[P70170-1]
[P70170-2]
P70170
P70673
Q09429
[Q63563-1]
[Q63563-2]
Q63563

Annotations were only to canonical forms. I've made the corrections according to Ruth's comment below. Birgit

**Comment by RLovering** [comment]
Hi Birgit

I have changed the complexes associated with the following, to GO:0008282 inward rectifying potassium channel
O60706 
Q09428
Q14654
The annotations to these proteins have been ISO'd to rat and mouse. RGD needs to update P70673, Q09429, Q63563 and MGI needs to update Q61743, B2RUS7, P70170 @hdrabkin  (unless these ISO's are updated automatically) and painted so there are REFG errors too for P70170, B2RUS7, Q09429, Q63563 (I think these will need repainting?) @pgaudet 

I am confused by 
O60706-1, O60706-2 P70170-1 P70170-2 Q63563-1 Q63563-2 as these don't seem to be present in Protein2GO, although the non-isoform IDs are. Maybe this is a mapping issue? 

As you point out a few of the annotations also need to be revised by Reactome.

does anyone know an RGD @?

Thank you for identifying my errors here

Ruth

**Comment by pgaudet** [comment]
The contact for RGD is Stan @slaulederkind

**Comment by bmeldal** [comment]
Thank you, Ruth.

>O60706-1, O60706-2 P70170-1 P70170-2 Q63563-1 Q63563-2

Sorry, yes, we use the isoform in the complexes but GOA used the canonical forms so please check the annotations to the canonical entries.

**Comment by hdrabkin** [comment]
MGI ISO annotations will be updated automatically when the target "With" has been reannotated.

**Comment by hdrabkin** [comment]
"MGI needs to update Q61743, B2RUS7, P70170 @hdrabkin (unless these ISO's are updated automatically)"
Yes, these will be updated automatically when the ISO target annotation is changed

**Comment by slaulederkind** [comment]
RGD ISO annotations will disappear after the pipelines pick up the corrections from elsewhere.

**Comment by pgaudet** [comment]
Looks like this one can be closed - can you confirm @bmeldal ?

**Comment by bmeldal** [comment]
Ruth mentioned above that Reactome need to fix some annotations, too. Should @deustp01 take a look before I close?

**Comment by pgaudet** [comment]
Pinging @deustp01 
When you see this can you please let us know ?

**Comment by deustp01** [comment]
The two Reactome annotations involving Q09428 are errors. We will fix them.

(Took a while to notice this and get to it - had to dig through hundreds of GitHub messages whose total content was things like "yes you're right", "closed X", "reopened X", "re-closed X" etc. The signal is getting lost in a tremendous amount of noise.)

**Comment by ValWood** [comment]
closing, assuming all done here.
