### ISSUE TITLE
IPR001796 glycine biosynthetic process /	 nucleotide biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1702]
Picking this up for 

dihydrofolate reductase activity
glycine hydroxymethyltransferase activity

not sure these are  correct?

**Comment by ValWood** [comment]
glycine hydroxymethyltransferase activity is IPR001085

**Comment by asangrador** [comment]
I have removed the  'glycine biosynthetic process'  and 'nucleotide biosynthetic process' from IPR001796 (changed it for tetrahydrofolate biosynthetic process, which makes more sense).

Regarding IPR001085 (Serine hydroxymethyltransferase), this enzyme catalyzes the reversible conversion of serine and tetrahydrofolate to glycine and methylenetetrahydrofolate. The term glycine biosynthetic process term seems ok here.  In fact, the child of this term, glycine biosynthetic process from serine, is better.
Amaia

**Comment by asangrador** [comment]
And serine hydroxymethyltransferase has 'glycine hydroxymethyltransferase activity' (EC 2.1.2.1)

**Comment by ValWood** [comment]
Yes sorry I was just pointing out that  glycine hydroxymethyltransferase activity is IPR001085
not  IPR001796...all good...
