### ISSUE TITLE
IPR005676 isoleucine biosynthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1703]
I that correct (EC not in KEGG pathway)

v

**Comment by ValWood** [comment]
SGD
Aspartic beta semi-aldehyde dehydrogenase; catalyzes the second step in the common pathway for methionine and threonine biosynthesis

**Comment by asangrador** [comment]
Hi Val,
The annotation in this entry was given after aspartate-semialdehyde dehydrogenase,  as it seems to the second enzyme in the aspartate pathway that converts aspartyl phosphate to aspartate-semialdehyde, the branch point intermediate between the lysine and threonine/methionine pathways. 
But the entry also matches Malonyl-CoA reductases, so I will remove the annotation.
Amaia

**Comment by ValWood** [comment]
ah OK, I should make the annotation then.
