### ISSUE TITLE
Annotation review: P15993 & proton motive force dependent protein transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1704]
Hello, 

EcoCyc has an annotation of P15993 to proton motive force dependent **protein** transmembrane transporter activity. 
P15993 seems to be an amino acid transporter, not a protein transporter. Can you please have a look ? 

Thanks, Pascale

**Comment by amandamackie** [comment]
This was assigned incorrectly and has now been removed. 

Amanda

**Comment by keseler** [comment]
Thanks, Amanda!
A quick FYI to GO folks, though: it does take quite a bit of time for any changes we make in EcoCyc to trickle out to the E. coli GAF.  Usually after an EcoCyc release, Jim Hu will generate and submit a new E. coli GAF.  We are just about to publicly release our latest version; however, the data for that was frozen more than a month ago.  Our next release (with Amanda's change) won't be public until ~April 2018.

**Comment by pgaudet** [comment]
Thanks for the corrections and information @amandamackie @keseler
