### ISSUE TITLE
Move annotations from 'GO:0043492 ATPase activity, coupled to movement of substances ' to the equivalent transmembrane term

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1706]
* GO:0043492 ATPase activity, coupled to movement of substances 
** 19 Flybase EXP annotations @hattrill 
** 1 EcoCyc EXP annotation @keseler 

Annotations can be rehoused under 'ATPase activity, coupled to transmembrane movement of ions, phosphorylative mechanism' - or a more specific child of you can ! 

Thanks, Pascale

**Comment by hattrill** [comment]
Moved FB ones.

**Comment by amandamackie** [comment]
EcoCyc ones now moved as well
