### ISSUE TITLE
Review annotations to 'core promoter binding' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1708]
Hello,

The core promoter is the region where 'basal/general' transcription factors bind; usually the 'motif' DNA binding transcription factors (PAX, HOX, SMAD, etc) do no bind the core promoter, but they bind the 'proximal' promoter. 
https://docs.google.com/spreadsheets/d/1k-ony7IhQL7yP9JvcJ27tF8Pmt3-5GbNDT6VIsztnEg/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
Hello, 

I downloaded all EXP annotations to 'GO:0001047 core promoter binding' and children. 

Most of them are actually incorrect: The core promoter is the region that contains the transcription start site and the binding site for the RNA polymerase. 'Normal' DNA binding transcription factors bind the 'proximal promoter'. 

Please review your annotations. Most of the time the correct term should be 
'GO:0000978 RNA polymerase II proximal promoter sequence-specific DNA binding' (unless it's another type of promoter). 

Annotations are here, grouped by assigned_by and grouped by term: 
https://docs.google.com/spreadsheets/d/1k-ony7IhQL7yP9JvcJ27tF8Pmt3-5GbNDT6VIsztnEg/edit#gid=0


Thanks, Pascale

**Comment by pgaudet** [comment]
AgBase  @jinhuiz

**Comment by vanaukenk** [comment]
The WB annotations are fixed.
This paper might be a nice addition to the list of references associated with this term:
https://www.ncbi.nlm.nih.gov/pubmed/12381658

**Comment by slaulederkind** [comment]
Manual RGD annotations have been corrected.

**Comment by tberardini** [comment]
@pgaudet  Can you look at this one: http://science.sciencemag.org/content/336/6084/1045?
Figure 1E and 1F could be interpreted to represent CDF1 core promoter binding to FT.  Amplicon 13 looks like it overlaps the UTR.  What do you think?  Let me know if you can't access the paper.

**Comment by hattrill** [comment]
FlyBase annotations fixed.

**Comment by pgaudet** [comment]
Hi @tberardini I agree, my understanding of region 13 would be the core promoter as well. 
@krchristie Is this how that's defined? 
Thanks, Pascale

**Comment by RLovering** [comment]
2 UCL ones updated to GO:0000978, TAF1 is a large subunit of TFIID therefore this annotation correct. UCL all done
Ruth

**Comment by krchristie** [comment]
@tberardini & @RLovering - I checked the Science paper Tanya had questions about and while I agree that Amplicon 13 could contain the core promoter, I would think it also contains quite a bit of the proximal promoter region, probably more proximal promoter than core promoter as the core promoter is quite small. 

Considering that the main things that bind the core promoter for RNAP II are General Transcription Factors, and it doesn't look to me like the factors described in the Science paper are GTFs, I personally think that it is more likely that CDF1 is binding the proximal promoter. With respect to the annotation, I would be OK with calling it the proximal promoter due to knowing that CDF1 is not a GTF. Alternatively, if you feel that the ambiguity of Amplicon 13 makes it difficult to make the call, you could go up a level and just indicate binding to a RNAP II regulatory region. I don't think Amplicon 13 is unambiguous evidence of binding the core promoter.

This review by Thomas & Chiang (https://www.ncbi.nlm.nih.gov/pubmed/16858867) was one of our main sources in defining the core promoter versus the proximal promoter for RNAP II. Figure 2 is quite useful at illustrating some of the main elements of the RNAP II core promoter and what proteins bind to each element.

![thomaschiang-fig2](https://user-images.githubusercontent.com/10533218/33491574-8872051c-d66f-11e7-9326-3c5730363e1c.jpg)

**Comment by tberardini** [comment]
Thanks, @krchristie.  Annotation updated.

**Comment by sabrinatoro** [comment]
ZFIN annotations have been updated.

**Comment by hdrabkin** [comment]
I am seeing that many of our IDA annotations are coming from our GOA_mouse load; 
These include several from UniProt; needs to be changed at that end..

**Comment by bmeldal** [comment]
Complex annotations reviewed, most looked correct.

**Comment by hdrabkin** [comment]
MGI: All  GO:0000979  changed to GO:0000978 (46 genes, over 50 annotations)

**Comment by pgaudet** [comment]
Hi @hdrabkin 
How about the annotations to  GO:0001047 | core promoter binding? 
Could they be moved to 'RNA polymerase II core promoter sequence-specific DNA binding'?

If you could please write 'OK' or 'Fixed' that would be really helpful.  

Thanks, Pascale

**Comment by hdrabkin** [comment]
@pgaudet 
Still waiting on the assigned curators; should be any time now.

**Comment by hdrabkin** [comment]
I have been informed that all MGI annotations are now accounted for!

**Comment by pgaudet** [comment]
There are still annotations to be reviewed by 
UniProt + CAFA @ggeorghiou 
SGD @krchristie you might want to first scan the list ? 
EcoCyc @keseler 
RGD @slaulederkind 

Thank you in advance for having a look at these ! 

Pascale

**Comment by srengel** [comment]
fixed the SGD annotations that needed fixing.  left some as as.  

pasting the list here in case @krchristie wants to be 2nd pair of eyes:
ok | P13393 | SPT15
fixed | P14164 | ABF1
fixed | P22035 | BAS1
fixed | P22035 | BAS1
ok | P29547 | CAM1
ok | P32569 | SRB4
ok | P32585 | SRB5
ok | P35817 | BDF1
ok | P35817 | BDF1
fixed | P36167 | SRL3
fixed | P39521 | FHL1
ok | P40096 | BUR6
ok | P40356 | PGD1
fixed | P40473 | POG1
ok | P40992 | RRN7
ok | P47821 | SSN8
ok | Q04712 | RRN11
ok | Q07442 | BDF2
ok | Q12343 | MED4
ok | Q92317 | NCB2

**Comment by krchristie** [comment]
@srengel - I don't have time to look at these individually, but from the list you've posted, I recognize most of the ones you've said are OK for annotations to "core promoter binding" and they make sense to me.

**Comment by srengel** [comment]
ok cool, thanks @krchristie.  i'm considering SGD done for this ticket.  removed myself from assignees.

**Comment by keseler** [comment]
I just reviewed the three EcoCyc annotations, and IMO they are correct.  In bacteria at least, transcription factors (maybe only repressors, but I'm not sure of that) do in fact bind in the core promoter region and essentially compete with RNA polymerase, which is how they act as repressors. If the term is only intended for RNA pol and positively acting factors, please let me know!

**Comment by pgarmiri** [comment]
All EBI UniProt annotations have been revised and the excel sheet has been updated.

For SIB UniProt annotations, all the curators have been notified with appropriated actions but not all have been changed as yet. The suggested action have been reported in the excel page.

**Comment by pgaudet** [comment]
Only 2 annotations remain (PseudoCAP). I will contact them.

**Comment by glwinsor** [comment]
Changed for G3XCV0. Could not find any other annotations (such as Q51460) that were annotated with GO:0000985.

**Comment by pgaudet** [comment]
Hi @glwinsor 
I still see the annotation of Q51460 to GO:0000985 in Protein2GO (I am assuming that this is where you make annotations?) 

<img width="966" alt="image" src="https://user-images.githubusercontent.com/4782928/44254538-5f2a2800-a203-11e8-96ed-d23ba0c95588.png">


Thanks, Pascale

**Comment by pgaudet** [comment]
Q51460 is now fixed
