### ISSUE TITLE
GO:0000733	DNA strand renaturation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1709]
I was working with a collaborator yesterday  to refine some phenotypes based on GO and we think this term looks odd.

Should it be called "annealing" (renaturation isn't a process,  it will occur in a test tube with any complementary DNA?)

It also has the child
GO:0061306    DNA strand renaturation involved in double-strand break repair
(one experimental annotation)
This  gene also has

GO:0010709    
heteroduplex formation involved in double-strand break repair via synthesis-dependent strand annealing

which is probably describing the same process?
@hattrill  http://www.uniprot.org/uniprot/Q9VMX6

the children of
https://www.ebi.ac.uk/QuickGO/term/GO:0000733
imply it is describing the activity of a helicase

PomBase have used for  2 condensin units, which seems *completely* wrong?
https://www.pombase.org/term/GO:0000733

**Comment by ValWood** [comment]
hmm may be it's OK, I'm not sure....
I'm still confused by the differences between annealing, renaturation and rewinding....

**Comment by hattrill** [comment]
Seems like one is recombination driven and one isn't. I don't understand why renaturation is used instead of annealing. 
I guess the rewinding can be separable from annealing.....this could probably do with an expert eye, as it is not immediately obvious if these terms would mean the same to them.

**Comment by mah11** [comment]
I didn't have answers then and I don't now, but this stuff came up a while back on the ontology tracker - 

https://github.com/geneontology/go-ontology/issues/12539

and the older ticket linked there.

**Comment by ValWood** [comment]
This isn't urgent as not many annotations would be affected. It seems like an issue that might be addressed during  some later stage MF refactoring .....

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14671
