### ISSUE TITLE
PAINT annotation:PTN001663160

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1710]
Annotations transferred from this node http://www.pantree.org/node/annotationNode.jsp?id=PTN001663160 are multicellular organism reproduction, circadian rhythm and extracellular space.
The common domain is a IPR010562 Haemolymph juvenile hormone binding. 
I think the extracellular space is ok to transfer, but multicellular organism reproduction & circadian rhythm do not seem suitable for transfer.

**Comment by marcfeuermann** [comment]
I totally agree. Many duplications and not very relevant BP terms. I've remove propagation of both 'multicellular organism reproduction' & 'circadian rhythm'.
