### ISSUE TITLE
PAINT:Remove annotations to Sdic genes: PANTHER:PTN000277823, PANTHER:PTN000277824  

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1711]
Could you remove the dynien-related terms derived from:
PANTHER:PTN000277823 
PANTHER:PTN000277824 
Annotations to
FBgn0067861 Sperm-specific dynein   intermediate chain 1, Sdic1
FBgn0053497 Sperm-specific dynein intermediate chain   2, Sdic2
FBgn0053499 Sperm-specific dynein intermediate chain   4, Sdic4

These from a gene cluster of derived from the cytoplasmic dynein intermediate chain. They lack the N-terminal region essential for intermediate chain function.

**Comment by marcfeuermann** [comment]
It is indeed risky to propagate annotations into duplicated clusters like that. Annotations have been removed for Sdic 1, 2 and 4.

**Comment by hattrill** [comment]
Ace! (again)
