### ISSUE TITLE
Review annotation to 'receptor ligand activity' (GO:0048018)

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1713]
@BarbaraCzub @RLovering 

Please can you review the annotation of MAPT (UniProtKB:P10636) to 'receptor ligand activity' to see if you think this reflects the normal biological role of MAPT or a role it has acquired in a disease state.

In Protein2GO, I can see two annotations, one TAS and another that is IDA but still marked PRIV.

Thx.

**Comment by RLovering** [comment]
Thanks Kimberley 
we are discussing the normal action with our experts. We will get back to you soon
Ruth and Barbara

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 
Although PMID:24534188 suggests that Tau can be extracellular in physiological conditions, the IDA annotation is from PMID:18272392, which investigates the toxicity of extracellular tau, so I removed this annotation.
Thanks,
Barbara

**Comment by RLovering** [comment]
removed Barbara and my assignment from this ticket
