### ISSUE TITLE
Review annotations to beta catenin

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1714]
Hi @RLovering, @slaulederkind, @ukemi, @pgarmiri

I have some annotation issues for beta catenin that I would like you to review as part of the signaling project.

1. Could you please review some annotations to beta catenin. Beta catenin does not directly bind DNA, but interacts with regulatory regions via other transcription factors, TCF/LEF being the major factor. 
Could you review your annotations to:
DNA binding transcription factor activity and DNA binding terms and their children? 
Suggested replacements:RNA polymerase II transcription coactivator activity GO:0001105 and/or RNA polymerase II transcription factor binding GO:0001085

2. As beta catenin acting as a coactivator in the nucleus is a hallmark of the canonical wnt signaling pathway that distinguishes it from non-canonical pathways, it would seem appropriate to upgrade all annotations made to "Wnt signaling pathway" GO:0016055 to the more specific term "canonical Wnt signaling pathway GO:0060070

The annotations can be found in this spreadsheet:
https://docs.google.com/spreadsheets/d/1WJHkgtXLvPizEJt5Sce8mFeH9AI_JUAtQa0pVOmAH_w/edit#gid=0

Grand totals for manual annotations:
BHF-UCL	1 -done
ParkinsonsUK-UCL	2 - done
MGI	11
RGD	13 - pending MGI updates
UniProt	9 - done

Please reassign if you wish,
Thanks, Helen

**Comment by pgarmiri** [comment]
The UniProt annotations are also fixed. 
Thanks,
Penelope

**Comment by slaulederkind** [comment]
All of the RGD annotations are ISO or ISS, assigned by import pipelines.  When MGI changes their annotations, the RGD annotations will be corrected by the import pipeline.

**Comment by hattrill** [comment]
Thanks @pgarmiri. Can I get you to do one more fix? P18824-1, PMID:9635189 (it's a Dmel one that I missed off)  to upgrade from Wnt signaling pathway GO:0016055 to canonical Wnt signaling pathway GO:0060070.
Here's the link to the P2GO page:https://www.ebi.ac.uk/internal-tools/protein2go/dynamic.html?database=production#ac=9635189

**Comment by pgarmiri** [comment]
Hi @hattrill , update is done.  If you find any more, just let me know.

**Comment by ukemi** [comment]
I'm pretty sure I caught all the MGI ones.

**Comment by hattrill** [comment]
Brill, thanks @ukemi

**Comment by ukemi** [comment]
Note, I will also change our annotations from ChIP experiments from 'chromatin binding' to 'chromatin' as was recently decided.

**Comment by pgaudet** [comment]
@hattrill 
Is this resolved ?

**Comment by hattrill** [comment]
Hi @vanaukenk - must have missed this before, there is one WormBase one:
WB:WBGene00000238   Bar-1 Wnt signaling pathway IMP PMID:11560894
that you might be able to upgrade to canonical.

**Comment by pgaudet** [comment]
@vanaukenk Can you have a look at that annotation ? 
> WB:WBGene00000238 Bar-1 Wnt signaling pathway IMP PMID:11560894
that you might be able to upgrade to canonical.

After that is fixed this ticket can be closed. 

Thanks, Pascale
