### ISSUE TITLE
PTHR45674 PANTHER:PTN000048695: DNA ligase terms being associated with PARP proteins

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#1716]
Please review PANTHER:PTN000048695.
Current implementation is resulting in "DNA ligase (ATP) activity" (MF) and "DNA ligation involved in DNA repair" (BP) being annotated to Poly [ADP-ribose] polymerase (PARP) proteins, which I believe is incorrect.  I've observed this for Drosophila, human and mouse, though the issue probably extends further.

**Comment by pgaudet** [comment]
@sjm41 next time can you give us the protein Accession of the protein you are looking at ? 
Drosophila Parp  (P35875) is in PTHR10459
(which does not contain PTN000048695 anymore)

So, "DNA ligase (ATP) activity" (MF) and "DNA ligation involved in DNA repair" (BP) are not propagated to P35875 anymore. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks Pascale.
(Yes, will try to remember to add the accessions!)
