### ISSUE TITLE
Annotation review: nucleocytoplasmic carrier activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1717]
Hello, 

While working on https://github.com/geneontology/go-ontology/issues/14336
I noticed a few annotations that need to be reviewed and possibly updated: 

https://docs.google.com/spreadsheets/d/1xsoJzSX37cSIVrFedI5dBHHMOluFkakGBlSMlCU7ztE/edit#gid=0

Groups that have annotations to review

GeneDB @pgarmiri ? 
ParkinsonsUK-UCL @RLovering 
UniProt @pgarmiri 
TAIR @tberardini 
MGI @hdrabkin 

Thanks, Pascale

**Comment by hdrabkin** [comment]
MGI annotation removed as paper has no evidence to support current definition clarification.

**Comment by tberardini** [comment]
Moved the annotation for PSD to 'nuclear export signal receptor activity'.

**Comment by BarbaraCzub** [comment]
Based on the ontology ticket I am assuming the definition of 'nucleocytoplasmic transporter activity' currently is:
'Carries substances between the nucleus and the cytoplasm of a cell by moving along with the target protein.'
?

Accordingly, I updated the original PARL annotation to two new annotations:

### Original:

PARL - XPO1 - IMP - GO:0005487 nucleocytoplasmic transporter activity - has_input Q96D46 60S ribosomal export protein NMD3 - PMID:12773398

### New:

PARL - XPO1 - IMP - GO:0005487 nucleocytoplasmic transporter activity - has_input GO:0015935 small ribosomal subunit, part_of GO:0000056 ribosomal small subunit export from nucleus - PMID:12773398 Figure 6

PARL - XPO1 - IMP - GO:0005049 nuclear export signal receptor activity - has_direct_input Q96D46 60S ribosomal export protein NMD3, has_input GO:0015934 large ribosomal subunit, part_of GO:0000055 ribosomal large subunit export from nucleus - PMID:12773398 Figures 6-9

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
I had a look at the annotations. I am afraid, I can't change annotations made by GEneDB but we do have an email address of them. I ask them to take a look.
The UniProt annotations have been all created at SIB, so I have no access to them.  @sylvainpoux could you please take a look and pass it to the relevant curator?
Thanks,
Penelope

**Comment by pgaudet** [comment]
Hello @fatimasilva
Can you please have a look at the GeneDB annotation? 
http://amigo.geneontology.org/amigo/gene_product/GeneDB:PF3D7_0309000
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:O77334
Annotations are from this paper: PMID: 18793411

It looks like the proteins are *transported* to th enucleus, ie they not do themselves mediate transport. 
Thanks, Pascale

**Comment by uliboehme** [comment]
Hello @pgaudet,
GeneDB annotation removed as paper has no evidence to support current GO terms.
Thanks, Uli

**Comment by bmeldal** [comment]
Updated all CP importins with GO:0061608 nuclear import signal receptor activity

**Comment by pgaudet** [comment]
All done. Thanks everyone !
