### ISSUE TITLE
Annotation review Cav1 rat

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1718]
RGD:2280 is annotated to 'RNA polymerase I transcription factor binding' but I see no mentino of PolI or rRNA in the paper, Can you please check? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Hi Pascale, Cavin1 is a Pol1 transcription factor that directly or indirectly binds Cav1 (RGD:2280).

**Comment by pgaudet** [comment]
Hi @slaulederkind 
Do you have a reference supporting that role as a trabscription factor ? This is not mentioned in UniProt: http://www.uniprot.org/uniprot/P41350

Nor in the paper cited by RGD, PMID:23941874

Thanks, Pascale

**Comment by slaulederkind** [comment]
PMID: 9582279

**Comment by pgaudet** [comment]
Hi Stan, 

You are talking about 'Cloning and functional characterization of PTRF, a novel protein which induces dissociation of paused ternary transcription complexes.'? 

I dont see Cav1 mentioned there; is there a synonym being used ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Hi Pascale, The original annotation for which you raised an issue came from PMID:23941874.  The annotation was deleted because the evidence was immunoprecipitation from a tissue sample, not purified proteins.  PMID: 9582279 was given as evidence that Cavin1 (Ptrf) was a Pol1 transcription factor.
