### ISSUE TITLE
Annotation review PMID: 23867755

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1719]
HDAC4 and HDAC5 are annotated to 'RNA polymerase III transcription factor binding'

but the paper seems to talk about polII (2)-regulated genes. 

Can you please have a look ? There are annotations from RGD and UniProt for the same paper.

**Comment by slaulederkind** [comment]
Those RGD annotations were imported from UniProt.

**Comment by pgarmiri** [comment]
Thanks for pointing those out @pgaudet .

Both annotations have been changed to 'RNA polymerase II transcription factor binding'.
