### ISSUE TITLE
IPR006534 NOT ATP biosynthetic process 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1722]
IPR006534 maps
https://www.pombase.org/gene/SPAC1071.10c  (P09627)

a

GO:0008553 | hydrogen-exporting ATPase activity, phosphorylative mechanism
GO:0120029 | hydrogen ion export across plasma membrane

to
ATP biosynthetic process | IEA with IPR006534

**Comment by asangrador** [comment]
'ATP biosynthetic process' is a very old annotation and definitely wrong. 
I have changed the terms as suggested . Thanks!

**Comment by ValWood** [comment]
still has ATP biosynthetic process
http://www.ebi.ac.uk/interpro/entry/IPR006534

**Comment by happy-lorna** [comment]
We have not made a new release since the change was made, so it is not visible on the public site yet.
Last release 23 Nov 2017
Next release due 1 March 2018

**Comment by ValWood** [comment]
Ah OK
