### ISSUE TITLE
PAINT:PANTHER:PTN000093831, P51140 dsh

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1726]
Hi,
Could you please block propagation of GO:0060071 | Wnt signaling pathway, planar cell polarity pathway to D.mel P51140 dsh from PANTHER:PTN000093831.

In flies, Wnt ligands are generally not thought to be invloved in PCP.

Thanks.

**Comment by marcfeuermann** [comment]
Propagation of  GO:0060071 | Wnt signaling pathway, planar cell polarity pathway has been restricted to Deuterostomia - PTN000853715 (excluding flies and close species).

**Comment by hattrill** [comment]
Ace!
