### ISSUE TITLE
MGI annotation to 'GO:0007037 vacuolar phosphate transport'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1731]
Hello,

MGI has two proteins annotated to 'GO:0007037 vacuolar phosphate transport' from PMID:  24259513

The paper talks about renal phosphate transport but I dont see a mention of the vacuole. Can you please check ? 

I am trying to see if that term can be merged with     GO:1905011 transmembrane phosphate ion transport from cytosol to vacuole

Thanks, Pascale

**Comment by hdrabkin** [comment]
fixed
