### ISSUE TITLE
Report on taxon constraint violations in annotations by DFLAT

### ISSUE THREAD

**Issue by hwick** [geneontology/go-annotation#1732]
Hello,
I am posting here because no one is responding from goa@ebi.ac.uk. Can this annotation be corrected as outlined?

Hello,
My former supervisor, Donna Slonim, received an email recently about a taxon constraint in one of DFLAT's annotations to GO. After reviewing it, I believe the annotation was made in error, and should be changed from the taxon-constrained GO:0060446 to the unconstrained GO:0060438. I have not logged into Protein2GO in years, and am unable to make this change directly myself. Is it possible this could be done on your end? Thanks,
~ Heather

Hello,

We have identified one or more annotation(s) by the DFLAT group that have failed taxon constraint checks.
The offending annotations are listed at the end of this email, along with details of the violated constraint(s).

You can find more details of the violation(s) by viewing the annotations in Protein2GO and clicking on the amber flag icon
that is displayed at the beginning of the annotation line.

If you have any concerns regarding the contents of this email, please contact goa@ebi.ac.uk; please DO NOT REPLY to this email - it is sent from an unmonitored account.

Thanks,
The GOA team.

Curator                  Constraint                                        Entity Type              Entity ID   GO ID      Name                                    Evidence          Reference      Taxon ID Taxon Name
Heather Wick             GO:0007424 only_in_taxon Arthropoda               protein     Q12946                   GO:0060446 branching involved in open tracheal s...ECO:0000315 (IMP) PMID:19500772  9606     Homo sapiens

**Comment by pgarmiri** [comment]
Correct by @sylvainpoux on 19-Feb-2018

Fixed
