### ISSUE TITLE
Use of CL:0014548 in annotation to Cdk5

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#1733]
An imported annotation has invalid CL id 
The id 'CL:0014548' in the c16 annotation extension is a dangling reference	
MGI	MGI:101765	Cdk5		GO:0051966	MGI:MGI:6094501|PMID:24607229	IMP		P	cyclin-dependent kinase 5	Crk6	protein	taxon:10090	20171031	ARUK-UCL	occurs_in(EMAPA:35196),regulates_o_occurs_in(CL:0002608),regulates_o_occurs_in(CL:0014548)	

MGI imports this from GOA/ARUK-UCL; 
I cannot find CL:0014548 in the cell ontology

**Comment by RLovering** [comment]
Thanks Harold, error deleted, the ID was from Uberon and got duplicated when the editing was done.
