### ISSUE TITLE
PAINT:PTN000226268 Wnt signaling pathway to positive regulation of...

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1736]
PTN000226268 node
http://www.pantree.org/node/annotationNode.jsp?id=PTN000226268
is annotated with "Wnt signaling pathway".

We have changed our annotations to "positive regulation of canonical Wnt signaling pathway" and the human and mouse sources are similarly annotated with regulation terms. Could you review this node, please.

Thanks

**Comment by ukemi** [comment]
The mouse annotation of MGI:1351660 is coming from a SPKW mapping.

**Comment by hattrill** [comment]
Just to note to avoid confusion: MGI:1351660  has "positive regulation of canonical Wnt signaling pathway" based on IGI
http://www.informatics.jax.org/go/marker/MGI:1351660?header=signaling
So our "source" genes now have the same annotation as this.

**Comment by pgaudet** [comment]
Thanks @hattrill 
The correct annotations are now available in PAINT, we have made the corrections. 

Thanks, Pascale

**Comment by hattrill** [comment]
Ace! Thanks!

Seeing of exciting fixes - thanks for all!
