### ISSUE TITLE
KW-0251 spt6 nucleosome remodelling protein is not a "translation elongation factor"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1737]
missapplied KW

https://www.pombase.org/gene/SPAC1F7.01c
http://www.uniprot.org/uniprot/S6BMF4

This seems to be a rule base issue...

**Comment by pgaudet** [comment]
Hi, 

As part of the transcription refactoring we plan to restore transcription elongation factor activity; sounds like this is the term needed here, right ? 

Thanks, 

Pascale

**Comment by ValWood** [comment]
I'm still not sure about this. A lot of things called "elongation factors" are just "required for elongation, many turn out to be very indirect.

Spt6 as far as I can tell has a role in nucleosome positioning  probably by recruiting something to chromatin) and seems to affect transcription  generally, and therefore "affects" elongation.

To me "transcription elongation factor" means "BP  transcription elongation" and nothing else.

Problems:
When we know the activity of an "elongation factor" it will have annotations to both its "real activity" and "elongation factor" to describe the same function? 

Do you envisage that *everything* involved in "transcription elongation" would be annotated to this term?  Or just a subset? If so, how do you decide?

I think it could lead to more annotation inconsistency, not less.....

**Comment by ValWood** [comment]
Closing. 
The annotation is correct to 
H3-H4 histone complex chaperone activity

There is an incorrect InterPro mapping, I will deal with that later
