### ISSUE TITLE
members of Cdc73/Paf1 complex  -> histone modification

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1738]
All  Cdc73/Paf1 complex subunits are annotated to histone modification:
SPBC13E7.08c  IPR007149
SPBC17G9.02c IPR007852
SPAC664.03 IPR007133
SPBC651.09c IPR031102
SPAC27D7.14c  IPR031101

Appears to derive from
http://europepmc.org/abstract/MED/20178742
facilitate activator (p53)- and histone acetyltransferase (p300)-dependent transcription elongation from a recombinant chromatin template in a biochemically defined RNA polymerase II transcription system. This represents a PAF1C function distinct from its established role in histone ubiquitylation and methylation. 

which is based on
and, potentially related, is required for H2B ubiquitylation and downstream H3K4 and H3K79 methylation both in yeast (Ng et al., 2003; Krogan et al., 2003; Wood et al., 2003) and in human (Zhu et al., 2005; Kim et al., 2009).

and seems to be indirect:
Wood A, Schneider J, Dover J, Johnston M, Shilatifard A. The Paf1 complex is essential for histone monoubiquitination by the Rad6-Bre1 complex, which signals for histone methylation by COMPASS and Dot1p. J. Biol. Chem 2003;278:34739–34742. [PubMed: 12876294]

**Comment by asangrador** [comment]
Looking into this, an annotation to  'regulation of histone modification' seems more correct. The complex definitely interacts with RNF20/RNF40 (that catalyzes histone H2B monoubiquitination), and  MLL1 (that methylates histone H3 at K4). As stated in [PMID: 29311159] 'As an integral part of its transcription-regulatory function, PD2/PAF1 plays a role in posttranslational histone covalent modifications '.
