### ISSUE TITLE
Sec62/Sec63 complex IPR004728 IPR027137

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1740]
This is the complex that brings the protein to the channel (translocon),
So I think this one should be annotated as a 

MF carrier rather than a  
https://www.ebi.ac.uk/QuickGO/term/GO:0140104

MF transporter
https://www.ebi.ac.uk/QuickGO/term/GO:0005215
(process is still transport)

**Comment by happy-lorna** [comment]
Both entries are currently annotated as MF = GO:0008565 (protein transporter activity) which has an exact synonym of protein carrier activity. Also the GO term you suggest (GO:0140104) says it should not be used for direct annotation. So its seems like we should leave the annotations as they are.

**Comment by ValWood** [comment]
I think the exact synonym was changed today to related  @pgaudet (if not it should be)

We need a more specific term, a child of  carrier for this activity.
I'll open a ticket for that.

**Comment by ValWood** [comment]
Ignore, this , I was thinking to the SRP.
I'm not sure that this is a "transporter" though. It appears to only be "signal sequence binding". It seems to function analogously to the SRP.
http://europepmc.org/abstract/MED/12518317

**Comment by happy-lorna** [comment]
Having investigated this I agree that we cannot define a MF of "protein transport" for either Sec62 or Sec63. According to this, PMID:29263911 I  don't think we can assign any specific MF to these subparts of the complex that would be correct accross all InterPro hits. As such I have removed the MF terms from these entries. 
Thanks!
Lorna.

**Comment by ValWood** [comment]
I agree it's  role is unclear.
