### ISSUE TITLE
IPR000403 some members are pseudokinase not kinase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1741]
For example
tra1	SPBP16F5.03c	SAGA complex phosphatidylinositol pseudokinase Tra1
https://www.pombase.org/gene/SPBP16F5.03c

tra2	SPAC1F5.11c	NuA4 complex phosphatidylinositol pseudokinase complex subunit Tra2
https://www.pombase.org/gene/SPAC1F5.11c

**Comment by happy-lorna** [comment]
Thanks for pointing this out, I have removed the kinase activity annotation.
