### ISSUE TITLE
IPR026872 Mapping to "regulation of cell proliferation"  

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1742]
https://github.com/geneontology/go-annotation/issues/1307
Comments on parent also appliaes to "regulation" terms.

This term was moved out from being a child of 'cellular process' because it is a cell population-level process, and cellular processes are restricted to those processes that involve individual cells. Also note that this term is intended to be used for the proliferation of cells within a multicellular organism, not for the expansion of a population of single-celled organisms.

(I'll request a restriction)

**Comment by happy-lorna** [comment]
Thanks for highlighting this. We will await the restriction before removing this annotation, as currently it is not incorrect.

**Comment by ValWood** [comment]
The taxon restriction will be applied, see
https://github.com/geneontology/go-ontology/issues/14846

I'll assign to you for now and you can close when the taxon violations come through (or I can close now if the fix will happen automatically).

**Comment by happy-lorna** [comment]
it wont happen automatically - so leave it assigned to me - I will check for the restriction and will close the issue when it has been updated.

**Comment by happy-lorna** [comment]
I have removed the term now the taxon restriction is in place.
