### ISSUE TITLE
IPR022783 is splicing factor not transcription factor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1745]
yeast family member is a splicing factor

Has been fixed before:
https://github.com/geneontology/go-annotation/issues/879

now has
GO:0006355 regulation of transcription, DNA-templated 
GO:0003677 DNA binding

**Comment by happy-lorna** [comment]
Sorry about that. The annotations have been removed now, and the abstract altered.
Cheers, Lorna.
