### ISSUE TITLE
Review annotations to palate development

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#1746]
In https://github.com/geneontology/go-ontology/issues/11680 it was noted that the logical definition of palate development refers to the secondary palate in UBERON. This ticket requests a name change to reflect that this term refers to the secondary palate. I have reviewed some of the mouse annotations and all of the annotations I reviewed can either be assigned to the secondary palate term (phenotype cleft palate), or can be reassigned to primary palate development based on annotation extensions. Note the development of the palatal shelves should be considered as secondary palate development and the term primary palate development will be removed as an asserted child of secondary palate development.

If the annotations should be to secondary palate, then they can remain and we will rename the term. If the annotations cannot be refined to primary or secondary palate, please comment on the ontology ticket referenced above.

The annotation review spreadsheet is here:
https://docs.google.com/spreadsheets/d/1m9OHL9hPumoeRaNEpk9wKYh0oevYh5GgTrIYLrVtack/edit#gid=0

**Comment by slaulederkind** [comment]
The RGD annotation involves the secondary palate.

**Comment by ukemi** [comment]
MGI annotations have been checked.

**Comment by sabrinatoro** [comment]
We would need to have a separate “palate development” term, which does not refer to primary or secondary palate. 
The adult palate in zebrafish is different enough in bone composition and structure I would be concerned about using the mammalian palate terms. 
Zebrafish embryonic cartilage (which is a good model of palate development) changes locations entirely in the adult. Most of GO annotations are based on phenotypes observed in the embryos, and therefore we do not know for sure which palate development is affected: the primary, secondary, or both. 
[I will also add this comment to the original case]

**Comment by sabrinatoro** [comment]
After discussion with David H, and discussion with Ceri, here is the ZFIN suggestion: 
- It is not possible to distinguish in zebrafish which part correspond to the primary palate and the secondary palate, and especially at the developmental stages at which the experiments (and the GO annotations based on these experiments) are done. Therefore we need a more general term.
- The Uberon term “roof of mouth” (UBERON:0007375) would be appropriate to refer to the zebrafish palate. 
- From a usage point of view, it would be better to have the term “palate” instead of “roof of mouth”. 

Suggestion: 
New term called “palate development”
This term has “roof of mouth” (UBERON:0007375) in the logical definition. 
Synonym: roof of mouth development
Notes: this term should be used when the distinction between the primary and secondary palate cannot be made, for example in zebrafish larvae.

**Comment by pgarmiri** [comment]
Hi, 
I didn't have edit access to the excel file but all the UniProt  annotations are referring to secondary palate and for the CAFA one a more more descriptive term was there, so I deleted them.

**Comment by pgaudet** [comment]
Hi @pgarmiri 
I updated the permissions of the spreadsheet - can you please edit ? 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Done!

**Comment by ukemi** [comment]
It seems that some comments on this thread have gone missing. From this discussion I think the best way to go is to rename the exisitng term 'secondary palate development' and to create a new term for the fish called palate development. We have two suggestions for the logical definition of that term, the firs one using UBERON 'roof of mouth' and the second using 'primitive palate'. @sabrinatoro , @cmungall, it seems like the latter may be more appropriate although it will create sibling terms due to the structure of UBERON. Whaic do you suggest?

**Comment by cmungall** [comment]
I think the comments are over here on the ontology tracker: https://github.com/geneontology/go-ontology/issues/11680

I'd like to keep the terminology consistent, and keep taxa out of the name. But I acknowledge that the 'primitive' in Uberon's 'primitive palate' is not perfect...

**Comment by ukemi** [comment]
Yup, the comments are on the ontology tracker. It seems to me that the 'primitive palate' would be the best fit, but I will wait to hear from @sabrinatoro .
See the ontology tracker for a summary of the proposal.

**Comment by ukemi** [comment]
OK. New plan. It seems like we will need to move existing annotations to a new term 'secondary palate development'  based on what was previously done in the ontology. See the ontology ticket associated with this annotation ticket.

**Comment by RLovering** [comment]
Hi 
sorry didn't appreciate I was listed here, 
All checked and all cleft palate papers
Ruth

**Comment by ukemi** [comment]
Awesome. These should all be moved to 'secondary palate development' to make the annotations more specific.

**Comment by RLovering** [comment]
Ok all done ;)
