### ISSUE TITLE
Annotation review rxrbb zfin

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1747]
Hello, 
zfin rxrbb is annotated to 'RNA polymerase III transcription factor activity, sequence-specific DNA binding' - but I think what is meant is polII (2), not 3. 

https://docs.google.com/spreadsheets/d/1z_ek0w6JvPrcAkTlpIhrQJfh9CpyYkXovrCZsjIocm4/edit#gid=0

Thanks, Pascale

**Comment by sabrinatoro** [comment]
@pgaudet 
I think it was indeed a mistake (I cannot find any information suggesting the annotation to pol3). 
I have updated the annotation. 
Thank you !
