### ISSUE TITLE
IPR002652 carrier not transporter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1748]
Hi,

Should be
GO:0061608 - nuclear import signal receptor activity
(
which is now "carrier" not transporter)

or
GO:0140142 - nucleocytoplasmic carrier activity
if more general.

v

**Comment by pgaudet** [comment]
GO:0061608 - nuclear import signal receptor activity
seems approrpiate. 

Right now GO:0140142 - nucleocytoplasmic carrier activity is flagged 'do not annotate' - since it's a parent of import and export. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think for some karyopherins we don't know the direction...will check...

**Comment by ValWood** [comment]
Maybe it's OK, all PomBase are specified as either import or export... can wait to see if  others cannot specify.

Some are both, but I guess maybe  you can always say at least one direction.....I have a feeling we might need to relax this one but let's see ;)

**Comment by happy-lorna** [comment]
Thanks for this - the fixes will be in the next release.

**Comment by ValWood** [comment]
When is your next release date? I'll see how many of my list I can process.

val

**Comment by happy-lorna** [comment]
our next release is scheduled for 1st March.

**Comment by happy-lorna** [comment]
As an aside (I'm not sure where this should be reported), while looking at the GO definition for this term, I notice the phrase "nuclear import signal (NIS)" is used rather than "nuclear localisation signal (NLS)". I am assuming these refer to the same thing, but have only seen it called NLS elsewhere. It might be good to clarify this in the definition.

**Comment by pgaudet** [comment]
Hi @happy-lorna 
I discussed this with Lionel at Swiss-Prot and I'd like to remove that, to accommodate the Nuft2 that transports the Ran-GDP  into the nucleus (see http://www.uniprot.org/uniprot/P61970). What do you think ?

**Comment by happy-lorna** [comment]
I'm not sure - what would the new definition be?

**Comment by pgaudet** [comment]
"Combining with a protein to mediate its transport through the nuclear pore, from the cytoplasm to the nucleus." 
(ie just removing the NIS bit)

**Comment by happy-lorna** [comment]
yeah that seems fine to me. certainly wouldn't affect the validity of the annotations talked about here.

**Comment by ValWood** [comment]
@pgaudet  I'm assuming this can close and that you did the def part?
