### ISSUE TITLE
IPR030847	Solute carrier family 25 member 38 NOT GO:1904983 transmembrane glycine transport from cytosol to mitochondrion 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1750]
based on the description, this seems that it can't be correct, 
GO:1904983 transmembrane glycine transport from cytosol to mitochondrion 
(glycine import into mitochondrion)

because the transporter is located in the inner membrane? (presumably transports from the inner membrane space to the matrix or vice versa?)

v

**Comment by ValWood** [comment]
hmm, maybe the inner membrane location is incorrect?
https://www.yeastgenome.org/locus/S000002277#go
the description at SGD says
Mitochondrial glycine transporter; required for the transport of glycine into mitochondria.....

@srengel

**Comment by ValWood** [comment]
the paper supporting inner membrane is this one,
https://www.yeastgenome.org/reference/S000049213
(I don't see anything in the with column?)

**Comment by ValWood** [comment]
mitochondrial carriers all appear to be in the inner membrane, but some definitely seem to support import across the outer membrane. ....not sure...

**Comment by srengel** [comment]
can't find experimental evidence for MIM annotation, so removed that one, but the import annotations seem supported by the papers, so i'm not inclined to remove those.

**Comment by ValWood** [comment]
It's confusing. I had a trawl around and so far as I can tell, all of these mitochondrial carriers are  definitely MIM...

**Comment by asangrador** [comment]
According to PMID: 28404662:
"Mitochondria possess both outer and inner membranes with differential permeabilities. The outer mitochondrial membrane is permeable to solutes up to ∼5 kDa, while the inner membrane is comparatively impermeable to enable efficient oxidative phosphorylation. Various transporters reside within the inner mitochondrial membrane to overcome its permeability barrier, including transporters required to facilitate the synthesis of heme."

And SLC25 is supposed to be a family of inner mitochondrial membrane transporters. The SLC25A38 member from S. cerevisiae Hem25/YDL119C was detected among these [10930523]. I think that paper is where our annotation came from for MIM.

**Comment by ValWood** [comment]
Thanks @asangrador ...that makes sense.
It seems that papers talk loosely about "import into the mitochondria" but what they mean really is "import into the mitochondrial matrix"

So if we said "cytoplasm into mitochondria" it would be correct (although a little misleading), but "cytosol into  mitochondria" is incorrect.

Anyway this is more of a GO issue.
