### ISSUE TITLE
 IPR006367	uroporphyrin methyltransferase mapping to 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1752]
https://www.pombase.org/gene/SPCC1739.06c

is that correct? 
I'm not sure what  
precorrin-2 dehydrogenase activity is

is it a False+ for met1?

**Comment by happy-lorna** [comment]
Having investigated this it turned out that one of the signatures was overhitting and so I have removed that signature. This means IPR006367 no longer hits SPCC1739.06c anyway.
