### ISSUE TITLE
IPR004123	Dim1 family

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1753]
member

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0046540
U4/U6 x U5 tri-snRNP complex

isn't a spiceosomal complex
(although it is a GO:0097525	spliceosomal snRNP complex)

I know it's confusing!
https://github.com/geneontology/go-ontology/issues/14460

**Comment by happy-lorna** [comment]
Hi Val,
I'm not clear what the problem with this one is. We don't currently annotate to GO:0046540.
Lorna.

**Comment by happy-lorna** [comment]
This has now been fixed - thats for the info.
