### ISSUE TITLE
PF12855	Pfam	Ecl1	IPR024368	Life-span regulatory factor	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1754]
1 GO annotation
zinc binding  PMID:28160081

2 rename as "Ecl1 zinc binding domain"

Life-span regulatory factor is a bit odd, its a phenotype (decreased viability in stationary phase)

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
The name is from Pfam. I will forward this to Sara. 
Hsin-Yu

**Comment by selgebali** [comment]
Hi Val, 
The ID line I left as it is currently, but I did change the description to ECL1/2/3 zinc binding proteins. The HMM model is not restricted to the zinc binding region (domain). The model rather captures the full length of the family members, which include a N-temrinal region with the conserved cysteines involved in zinc binding. I updated the annotation accordingly and included the reference you supplied. Thank you! 
Sara
