### ISSUE TITLE
Human and Yeast DNA polymerase alpha does NOT have 3'->5' exonuclease activity

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1755]
I am curating a Panther book, PTHR10322.  There is a subfamily named POLA1, which is DNA polymerase alpha, which is known to NOT have 3'->5' exonuclease activity, but this is not included in GO.  
If this could be added for the human protein, then we can fix the IEA (Inferred Electronic Annotations) for the rest of the subfamily.
http://www.uniprot.org/uniprot/P09884
PMID: 12531027 -- Human deficient activity in title of this paper.  I don't have full journal access yet, so I can't track down the ideal PMID (sorry).
PMID: 23245696 -- Yeast deficient activity in abstract of this paper.  See last part of 3rd sentence.  Yeast protein has UniProt ID P13382.

**Comment by asangrador** [comment]
I have removed the term 3'-5' exonuclease activity  from  IPR006133, as it matches DNA polymerase alpha. Thanks for letting us know.

**Comment by pgaudet** [comment]
Hi @keslingmj 
Just checking - if this is an InterPro annotation, you shouldn't have seen it in PAINT, is this right ? 

Also, if the issue has been addressed, please close the ticket. 

Thanks, Pascale

**Comment by asangrador** [comment]
We don't have PTHR10322 integrated in InterPro, our annotation was not related to panther, but to other member database. I was just checking if there was any entries in InterPro with the wrong annotation, to avoid spreading it.
