### ISSUE TITLE
Annotation review: Q96RS0 ribonucleoprotein complex import into nucleus 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1758]
http://www.uniprot.org/uniprot/Q96RS0

ribonucleoprotein complex import into nucleus
: BHF-UCL IC PMID:16687569

Seems indirect, capping doesn't have a role in transport?
@RLovering

**Comment by pgaudet** [comment]
@RLovering 
ping

**Comment by RLovering** [comment]
annotation deleted
