### ISSUE TITLE
SPBC19F8.02/	O60166 FP for 	IPR008978	HSP20-like chaperone (Gene3D)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1762]
This looks like a false positive?

https://www.pombase.org/spombe/result/SPBC19F8.02

**Comment by EBI-Hsinyu** [comment]
Hi, 

This might be a true hit. As IPR008978 is a "Homologous superfamily" entry, it hits proteins that have similar structures. Both SSF49764 and G3DSA:2.60.40.790 hit this protein, O60166. Also, from the NudC family abstract in InterPro: all members of the NudC family share a conserved p23 domain, which possesses chaperone activity both in conjunction with and independently of heat shock protein 90 (Hsp90) [PMID:21777812]. Hope this explains. 

Hsin-Yu

**Comment by ValWood** [comment]
Yes, I agree, is Heatshock clan
