### ISSUE TITLE
glyoxylate reductase/ transcription co-repressor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1763]
glyoxylate reductase/ is picking up mappings to

Glyoxylate reductase |   | transcription corepressor activity |   | GO_Central | Saccharomyces cerevisiae S288C | IBA | PANTHER:PTN000107684

and then

GOR1 | Glyoxylate reductase |   | negative regulation of nucleic acid-templated transcription |   | GOC | Saccharomyces cerevisiae S288C | IEA | GO:0003714 |   |   | SGD_REF:S000185202 | 20170902

which seems to be an IEA based on the PANTHER annotation

I can't find  anything in PuBmed describing a moonlighting activity.

@pgaudet  not sure who to assign this to?

**Comment by pgaudet** [comment]
You can assign PAINT reviews to me. We are waiting for the PAINT pipeline to be up and running before addressing these (since changes cannot be seen, its too hard to keep track). Hopefully soon ! 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @ValWood 
I don't see this. Can you please check again? 
Thanks, Pascale

**Comment by ValWood** [comment]
Me neither...
