### ISSUE TITLE
InterPro:IPR007145 NOT cytokinesis in fission yeast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1764]
In fission yeast ase1  does not appear to habe a role in cytokinesis, but it detects problems with cytokinesis and prevents nuclear division (i.e it acts post-cytokinesis)

cytokinesis checkpoint
-- | --
A mitotic cell cycle checkpoint that detects a defect in cytokinesis and prevents further rounds of nuclear division until cytokinesis is completed.

**Comment by asangrador** [comment]
Hi Val,
The cytokinesis term have been removed.
