### ISSUE TITLE
FP Gene3D	G3DSA:3.30.1610.10	IPR007230	Peptidase S59, nucleoporin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1765]
for
https://www.pombase.org/gene/SPAC2C4.09  

O14042
--

**Comment by EBI-Hsinyu** [comment]
HI, 
We just had a G3D update recently. This entry no longer hits O14042. This result should be visible in our next release. 
Hsin-Yu

**Comment by ValWood** [comment]
OK...
when you add the comment that you fixed can you close the ticket too...saves me going back to them ;)

cheers

Val
