### ISSUE TITLE
Nucleotide-sugar transporter (IPR007271)  NOT  sugar transporter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1766]
should be
UDP-galactose transmembrane import into Golgi lumen
UDP-galactose transmembrane transporter activity

(carbohydrate derivative parentage, rather than sugar/carbohydrate)

**Comment by happy-lorna** [comment]
I have removed the sugar-transport terms and replaced them with nucleotide-sugar transport terms.
Thanks, L.

**Comment by ValWood** [comment]
OK...
when you add the comment that you fixed can you close the ticket too...saves me going back to them ;)

cheers

Val

**Comment by happy-lorna** [comment]
will do
