### ISSUE TITLE
AIMP1 Homo sapiens Q12904 , keyword removal  KW:KW-0313

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1767]
AIMP1 Homo sapiens Q12904 
http://www.uniprot.org/uniprot/Q12904
Aminoacyl tRNA synthase complex-interacting multifunctional protein 1

to glucose metabolic process UniProtKB-KW:KW-0313
https://sourceforge.net/p/geneontology/annotation-issues/1159/

probaly derived from
"Involved in glucose homeostasis through induction of glucagon secretion at low glucose levels"
seems very indirect for a KW application of "glocose metabolism".
I can't work out which paper this is (from the 6 cited in the function section).

**Comment by sylvainpoux** [comment]
Hi Val,

it comes from this paper in MOUSE 

RP   FUNCTION, SUBCELLULAR LOCATION, AND TISSUE SPECIFICITY.
RX   PubMed=17001013; DOI=10.1073/pnas.0602045103;
RA   Park S.G., Kang Y.S., Kim J.Y., Lee C.S., Ko Y.G., Lee W.J.,
RA   Lee K.-U., Yeom Y.I., Kim S.;
RT   "Hormonal activity of AIMP1/p43 for glucose homeostasis.";
RL   Proc. Natl. Acad. Sci. U.S.A. 103:14913-14918(2006).

Could you assign the ticket to Michele Magrane who will look more in detail and see whether the KW is relevant?

Thanks

Sylvain

**Comment by magrane** [comment]
Hi Val, 

I agree that a role in glucose metabolism is indirect. PMID:17001013 shows that Aimp1 is secreted from the pancreas in response to low glucose levels and induces secretion of glucagon. I have removed the keyword. Thanks for pointing this out.

Michele
