### ISSUE TITLE
pombe Mis19, centromere protein not mitochondrial KW:KW-0496 & UniProtKB-SubCell:SL-0173 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1768]
misapplied mapping

Mis19  centromere protein Mis19/Eic1
https://www.pombase.org/gene/SPBC27B12.02

Uncharacterized protein SPBC27B12.02 in Uniprot

lots of papers:
https://www.ncbi.nlm.nih.gov/pubmed?cmd=Search&term=(SPBC27B12.02+OR+mis19+OR+eic1+OR+SPBC30B4.10+OR+kis1)+AND+(pombe+OR+fission+yeast)

UniProtKB:O42995 | SPBC27B12.02 | part_of | GO:0005739  mitochondrion | ECO:0000322 (IEA) | GO_REF:0000037 | UniProtKB-KW:KW-0496 | 284812 | UniProt |  

UniProtKB:O42995 | SPBC27B12.02 | part_of | GO:0005739  mitochondrion | ECO:0000322 (IEA) | GO_REF:0000039 | UniProtKB-SubCell:SL-0173 | 284812 | UniProt

**Comment by sylvainpoux** [comment]
This one will take more time. May I ask you to send a real user request. Marc or Ivo will take care of the update

Thanks

Sylvain

**Comment by pgaudet** [comment]
@ValWood when you send the real user request the ticket here should be closed I suppose ?

**Comment by ValWood** [comment]
Sent to UniProt helpdesk

**Comment by ValWood** [comment]
I think we  should keep them open until they are fixed maybe?
I can keep tabs on them this way. Lots have gone to the helpdesk but not fixed historically and then its difficult to know which have been addressed. Maybe best if  the fixer  closes?

**Comment by pedruzzi** [comment]
Yes I agree. I'll close it once it's fixed. Thanks for this one.

**Comment by marcfeuermann** [comment]
Hi Val,
This entry has not been updated since June 2004 ! I've made the updates, with the correct function and cellular component. I've updated also the data for mis20. The modifications will be public after the next release cycle.
Thanks
Marc.

**Comment by ValWood** [comment]
cheers
