### ISSUE TITLE
checkpoint clamp complex protein Rad1, not a nuclease, remove KW-0378

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1771]
misapplied KW

checkpoint clamp complex protein Rad1
https://www.pombase.org/gene/SPAC1952.07

http://www.uniprot.org/uniprot/P22193
has
Hydrolase KW-0378
nuclease KW-0540

**Comment by sylvainpoux** [comment]
Hi Val,

done

Sylvain

**Comment by ValWood** [comment]
Hi Sylvain,

Did you address for all species?
 I just spotted that the annotation comes from  human
3'-5' exonuclease activity Source: UniProtKB IDA PMID: 9660799

and
Source: UniProtKB-EC

This is from a paper
http://www.uniprot.org/citations/9660799

which is refuted https://www.ncbi.nlm.nih.gov/pmc/articles/PMC317084/

(I asked a pombe expert who works on Rad1, and it isn't a nuclease at all...
it's a DNA clamp)

So, who would we assign this one to?

And is there a way to add this paper to a "blacklist" to make sure it is not used again? I think we talked about this as part of our QC procedure?

@pgaudet

**Comment by pgaudet** [comment]
Thanks @ValWood I added this to our QC ideas notes. 

Pascale

**Comment by ValWood** [comment]
I raised a dispute for human
https://www.uniprot.org/uniprotkb/O60671/entry
for the single 1999 annotation

It still has  old nuclease annotation (and an EC SPKW and a PAINT mapping)

**Comment by sylvainpoux** [comment]
Hi @ValWood 
I removed this annotation. 
Many thanks for pointing this out
Sylvain
