### ISSUE TITLE
Should HTP annotations be allowed sequence-based transfer methods

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1775]
The question for this ticket relates to whether HTP should be allowed as a source for ISS, ISA, ISO and IBA transtitive annotations.

Previously, the working group decided that the value of marking an annotation as HTP was clearly indicating that it was part of a larger set and from an experiment likely to be non-hypothesis driven.
Since then some curators have wanted to transfer these annotations as they are the only source that they can find. 

Issues?
Should this be allowed?
What about IEA pipelines?
If allowed: 
should we have different evidence codes,
different rules

IBA transfer needs to be clarified or documented.
#1654 
 #1469

**Comment by hattrill** [comment]
Decision: to allow propagation of HTP annotations via ISS/ISA/ISO/IBA. No new codes needed. Need to be clear in guideline for transitive annotation codes that each gene should be reviewed on a case-by-case basis such that the curator has a good evidence base for propagation. No automated pipelines.
Action point: Ask Tony to allow transfer from HTP codes
Action point: Update ISS/ISO/ISA guidelines to be explict about expected standards

**Comment by hattrill** [comment]
Update: Asked for P2GO to allow transfer
Added: Reviewed ISS guidance on wiki:
Doc already states that " If the annotation has not been reviewed manually, the correct evidence code is IEA, even if the evidence supporting the annotation is all sequence based." and "An ISS annotation is often based on more than just one type of sequence-based evidence", which covers some of what was discussed.
Added:
"It is advised that curators carefully review other supporting evidence for terms transferred using ISS, particularly when transferring from annotations originating from high throughput experiments (evidence codes HTP, HDA, HMP, HGI, HEP)." to wiki for ISS - but I think  that this could be beefed up.

**Comment by tonysawfordebi** [comment]
I've updated P2G to remove the restriction on ISS-ing from HTP-evidenced annotations.
