### ISSUE TITLE
Review annotations to  'regulation of transcription during mitotic cell cycle' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1780]
Hello, 

We need to review annotations to 'regulation of transcription during mitotic cell cycle' and children to address the ontology ticket here: 
https://github.com/geneontology/go-ontology/issues/14896

**DONE GO:0007070 negative regulation of transcription from RNA polymerase II promoter during mitotic cell cycle**
https://docs.google.com/spreadsheets/d/1TD4XlLMu15n1B09AzSpghlL5i9QMia_83HsnF7l3mHw/edit#gid=0
* 2 BHF
* 6 SGD (changed to GO:000122)
* 2 UniProt 

**DONE GO:0007069 negative regulation of transcription from RNA polymerase I promoter during mitotic cell cycle** 
* 1 annotation by SGD, changed to GO:0016479 
https://docs.google.com/spreadsheets/d/16-zCVKXS5CrJryuQN0Q4rK6haRTyQ519izo7xIWFIiw/edit#gid=0

**DONE GO:0046022 positive regulation of transcription from RNA polymerase II promoter during mitotic cell cycle** 
https://docs.google.com/spreadsheets/d/1JrN6gcT7Y3hGOLqqSlSh2C9Bu2BKI08OZcufD_bGuY4/edit#gid=0
* 2 annotations by MGI and UniProt

**Comment by pgaudet** [comment]
@srengel https://github.com/geneontology/go-ontology/issues/14896
>i fixed the SGD annotations.
changed 7070 to 122 happens_during 278 mitotic cell cycle.
changed 7069 to 16479, and it already had happens_during 90 mitotic anaphase.

**Comment by hdrabkin** [comment]
Changed MGIs'

**Comment by RLovering** [comment]
BHF all changed

**Comment by ggeorghiou** [comment]
UniProt is all done.

**Comment by pgaudet** [comment]
Thanks everyone !
