### ISSUE TITLE
IPR031824 "E3 ubiquitin-protein ligase RNF220, middle domain" - Wnt signaling

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1781]
IPR031824 "E3 ubiquitin-protein ligase RNF220, middle domain"  is associated with GO:0090263 "positive regulation of canonical Wnt signaling pathway".

I can only find one paper that shows this: "The ubiquitin ligase RNF220 enhances canonical Wnt signaling through USP7-mediated deubiquitination of β-catenin. (PMID:25266658, PMCID:PMC4248747). 

Not sure if that is strong enough evidence for a domain-procecss link.

**Comment by happy-lorna** [comment]
Hi Helen, You are correct, and looking at our internal version or the DB I can see that these terms have already been removed from this entry. These changes will be visible in our next release (1st March).
Thanks, Lorna.

**Comment by hattrill** [comment]
Thank you!
