### ISSUE TITLE
rename GO:0005297 'hydrogen:proline symporter activity'

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-annotation#1782]
A small issue but the could GO:0005297 be renamed 'proline:proton symporter activity' - it is a child of GO:0015295 solute:proton symporter activity and the other child terms all use the 'xxx:proton symport' syntax. Just noticed that GO:0005280 is 'hydrogen:amino acid symporter actvity' which should also be corrected. Thank you

Amanda

**Comment by ukemi** [comment]
Moved to:
https://github.com/geneontology/go-ontology/issues/14918
