### ISSUE TITLE
TPV: ammonium transmembrane transport children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1783]
These look odd?
V

GO:1902616    acyl carnitine transmembrane transport | is_a
GO:1903091    pyridoxamine transmembrane transport | is_a
GO:1903711    spermidine transmembrane transport | is_a
GO:1903710    spermine transmembrane transport | is_a
GO:0072489    methylammonium transmembrane transport | is_a
GO:1902603    carnitine transmembrane transport

**Comment by ValWood** [comment]
Or all they all ammonia compounds, I think I asked this before, but I could not see the parentage for spermidine in chebi.

**Comment by ValWood** [comment]
Also "spermine" has the parent "drug transmembrane transport"

**Comment by ValWood** [comment]
Seems odd since we define 
ammonium transmembrane
Ammonium is the cation NH4+

**Comment by deustp01** [comment]
The pK of ammonia is about 9, so at pH 7 about 99% of ammonia molecules are protonated - NH4+ - and as pH falls the protonated fraction increases more, so what's actually getting transported is probably that charged entity. I think most of those other molecules that can be described as derivatives of ammonia also have alkaline pKs so they too will be mostly protonated at neutral pH (Not sure whether this helps or not.)

**Comment by pgaudet** [comment]
I dont think GO should reason over this.  In ChEBI spermidine is a **derivative** of NH4. However a spermidine transporter is not necessarily an ammonium transporter. The reasoner says that spemidine is a subclass of ammonium, not a derivative. 

I'll add this to the editors call to get more information. 

Thanks, Pascale

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#14928

**Comment by ValWood** [comment]
OK, I thought it looked odd to see spermidine annotated as an "ammonium transporter", (I would just expect it to be a "polyamine" transport.

 but it might be OK...I think I questioned it before.

**Comment by ValWood** [comment]
agree...ammonium derivative...

**Comment by ValWood** [comment]
whoops, sorry!
