### ISSUE TITLE
Review annotations to GO:0015992 'proton transport'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1784]
Dear all, 

While working on https://github.com/geneontology/go-ontology/issues/14918, I noticed that 'proton transport' should really be 'transmembrane proton transport'. I have pulled out the direct EXP annotations to GO:0015992 'proton transport' and rapidly scanned all of them.

The annotations are here: 
https://docs.google.com/spreadsheets/d/1iTHdYoKrBW2z9foCAI7d2Kw0_ll1roAVBB3ad3fqw2o/edit#gid=0

I have marked REVIEW in the left-most column those that seemed suspicious to me. The ones marked OK seemed fine but feel free to review them! 

I'm assigning only the people whom I think need to review. I emailed Geoff from PseudoCAP.

Thanks, Pascale

**Comment by RLovering** [comment]
thanks for this information, I found some papers which contradicted the paper this annotation was based on. 
Ruth

**Comment by bmeldal** [comment]
I think the CP complexes annotated to children of GO:0015992 are all transmembrane (mainly mitochondrial respiratory chain complexes).

**Comment by pgaudet** [comment]
Hello,

Some groups have not answered this one yet: 

SGD @srengel 
RGD @slaulederkind 
UniProt @ggeorghiou 
PseudoCAP @brinkmanlab

**Comment by hattrill** [comment]
Yes - transmembrane, merge away.

**Comment by slaulederkind** [comment]
Checked and/or changed.

**Comment by pgarmiri** [comment]
All UniProt annotations have been checked by @ggeorghiou for EBI and another curator at SIB.

**Comment by pgaudet** [comment]
Great! thanks everyone
