### ISSUE TITLE
Human ESCO1 and ESCO2 are required for "sister chromatid cohesion"

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1786]
PMID: 15958495 shows by RNA-interference experiments that both ESCO1 and ESCO2 of Human are required for "sister chromatid cohesion"

See 4th sentence of abstract:
RNA interference depletion experiment revealed that EFO1/ESCO1 and EFO2/ESCO2 were not redundant and that both were required for proper sister-chromatid cohesion.

**Comment by ValWood** [comment]
I forwarded this one to the UniProt helpdesk. 
Val

**Comment by magrane** [comment]
The paper was already in the UniProt ESCO1 entry (Q5FWF5) but has been added to the ESCO2 entry (Q56NI9) and GO terms have been added for both entries.
