### ISSUE TITLE
UniProtKB-KW:KW-0046 KW:KW-0196 mappings to "response to antibiotic" and "response to cyclohexamide"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1788]
The keywords in these cases appear to be used to capture drug sensitivity phenotypes.

examples include
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P41878
26S proteasome regulatory subunit rpn11

response to antibiotic from UniProtKB-KW:KW-0046
response to cyclohexamide UniProtKB-KW:KW-0196

also
P02406 | RL28_YEAST |   | 60S ribosomal protein L28

**Comment by ValWood** [comment]
i.e not normal processes...

**Comment by sylvainpoux** [comment]
Hi Val,
I am not familiar with this process. Marc will be much more accurate than me. May I ask you to assign him the ticket or create a user request for Swiss-Prot?
Thanks
Sylvain

**Comment by ValWood** [comment]
sure!
@marcfeuermann

**Comment by marcfeuermann** [comment]
Hi Val,
I totally agree with you, these KWs are not appropriate. This was the "old fashioned" way to annotate (2003). They will be removed for the next UniProt public release. 
Do not hesitate to assign such tickets directly to me, I will deal with them as soon as I can (even if sometimes it might take some time).
Best regards
Marc.
