### ISSUE TITLE
indirect upstream mappings to "cell cycle" and "cell division"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1789]
http://www.uniprot.org/uniprot/Q06819
Is a splicing component
cell division | ECO:0000322   (IEA) | GO_REF:0000037 | UniProtKB-KW:KW-0132
cell cycle | ECO:0000322   (IEA) | GO_REF:0000037 | UniProtKB-KW:KW-0131

This occurs quite a lot for splicing compement because they have a cell cycle phenotype

**Comment by ValWood** [comment]
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P25337

possibly others

**Comment by ValWood** [comment]
I had a check and I don't think there are many more

**Comment by sylvainpoux** [comment]
Done (keyword removed in both entries)
