### ISSUE TITLE
Move annotations to rubidium transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1792]
Hello, 

Terms referring to rubidium transport will be obsoleted since this is an assay for potassium transport (see https://github.com/geneontology/go-ontology/issues/11416)

Annotations should be moved to potassium transport and children. Annnotations are here:

**Comment by pgaudet** [comment]
*DONE GO:2000682 positive regulation of rubidium ion transport*
https://docs.google.com/spreadsheets/d/1XjdHWEV8oILWXcv3fPXqngYvctA6tHithI5JTRr5WDU/edit#gid=0 

*DONE GO:2000688 positive regulation of rubidium ion transmembrane transporter activity
https://docs.google.com/spreadsheets/d/1QjIPjgERlRgIwDAtjR_41LsFATnW05sG_EFtxV4y5eo/edit#gid=0

**Comment by RLovering** [comment]
DONE GO:2000681 negative regulation of rubidium ion transport 
DONE GO:2000687 negative regulation of rubidium ion transmembrane transporter activity

**Comment by hdrabkin** [comment]
Done

**Comment by slaulederkind** [comment]
Done

**Comment by slaulederkind** [comment]
Actually the second RGD annotation is also a UniProt import.

**Comment by pgaudet** [comment]
@slaulederkind can you please the google spreadsheet to write what you did ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Both "RGD" annotations were made by UniProt, so there is nothing I can do.

**Comment by pgaudet** [comment]
Thanks everyone !
