### ISSUE TITLE
Review annotations to phorbol ester terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1793]
Hello, 

It has been proposed to obsolete (https://github.com/geneontology/go-ontology/issues/12037)
* GO:1904627 response to phorbol 13-acetate 12-myristate and 
https://docs.google.com/spreadsheets/d/1r1I6o45zGYYOdtGVpb7LSidkCJ2IUAN_GnKfyrQ_SiE/edit#gid=0
2 annotation Uniprot

* GO:1904628 cellular response to phorbol 13-acetate 12-myristate
https://docs.google.com/spreadsheets/d/18Qyjphf2psAsfYRvLUHWHxPB0RK7Z62GI81Ve7aCa4k/edit#gid=0
16 annotations 
AgBase @jinhuiz
MGI
RGD
UniProt

There are 18 EXP annotations to these 2 terms. It looks like in all cases they are testing some kind of signaling pathway, that is also often annotated. Can people check they annotations and move them as appropriate ? 

Thanks, 

Pascale

**Comment by hdrabkin** [comment]
Annotation to 
MGI:2385891Zc3h12a  is ISO to human protein UniProtKB:Q5D1E8 via ISO load; this needs to be changed at UniProt or will keep reloading.

**Comment by pgaudet** [comment]
We decided to keep the terms for now. While the compound is not physiological in the organism being annotated, it does respond to it. 
Thanks, 
Pascale

**Comment by pgarmiri** [comment]
Hi Pascale,
Does that mean that from these type of experiments we add two annotations? "response to phorbol ester" and the pathway it is suppose to trigger? Shall we add back the annotations to this term?
Thanks,
Penelope

**Comment by pgaudet** [comment]
I will turn to @vanaukenk - should we make this a 'request for guidelines' ticket ?

**Comment by pgarmiri** [comment]
Hi,
Any further thoughts on this?
Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi @pgarmiri 
We have decided to keep these terms. 

The wider questions of annotation guidelines for 'response to' terms and when to create these terms will be discussed later when we do a revision of all the 'response' term (planned for Fall 2018). 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Thank you @pgaudet for the update.
Penelope

**Comment by hdrabkin** [comment]
sorry; accidentally deleted people when trying to assign to @dms321(Dmitry); reassigned
@pgaudet can you add @dms321 to the git-annotation lists? Thanks
