### ISSUE TITLE
Review annotations to GO:1990858 cellular response to lectin

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1794]
GO:1990858 cellular response to lectin, has sometimes been used for experiments looking at toxic effects of lectins. There are 2 EXP annotations: 
by RGD and AgBase (@jinhuiz); can you please review to check that this is not the case?  

https://docs.google.com/spreadsheets/d/1hr3Q1PzZpSPuhJ0u0wr1NOXDTJ6GCa5Idh2bZW1avJ0/edit#gid=0

Thanks, Pascale

**Comment by slaulederkind** [comment]
Changed term.
