### ISSUE TITLE
MGI GAFs have some lines with an "O" for aspect

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#1797]
`$ curl -L http://www.informatics.jax.org/downloads/reports/gene_association.mgi.gz | gzip -dc | egrep '\tO\t'`

```
MGI     MGI:1917378     Oxsr1           GO:2000687      MGI:MGI:5574433|PMID:24393035   IGI     UniProtKB:Q9Z1W9        O       oxidative-stress responsive 1   2210022N24Rik|2810422B09Rik|Osr1
        protein taxon:10090     20141006        ParkinsonsUK-UCL
MGI     MGI:103150      Slc12a1         GO:0035827      MGI:MGI:4417868|GO_REF:0000096  ISO     RGD:3685        O       solute carrier family 12, member 1      D630042G03Rik|mBSC1|Nkcc2|urehr3
        protein taxon:10090     20110510        RGD     
MGI     MGI:103150      Slc12a1         GO:0035829      MGI:MGI:4417868|GO_REF:0000096  ISO     RGD:3685        O       solute carrier family 12, member 1      D630042G03Rik|mBSC1|Nkcc2|urehr3
        protein taxon:10090     20110510        RGD     
MGI     MGI:2135960     Slc12a6         GO:0035826      MGI:MGI:4834177|GO_REF:0000096  ISO     UniProtKB:Q9UHW9        O       solute carrier family 12, member 6      gaxp|KCC3       proteintaxon:10090      20141006        MGI     
MGI     MGI:2135960     Slc12a6         GO:0035827      MGI:MGI:4834177|GO_REF:0000096  ISO     UniProtKB:Q9UHW9        O       solute carrier family 12, member 6      gaxp|KCC3       proteintaxon:10090      20141006        MGI     
MGI     MGI:1858416     Stk39           GO:2000681      MGI:MGI:5574433|PMID:24393035   IGI     UniProtKB:Q6P9R2        O       serine/threonine kinase 39      DCHT|RF005|Rnl5|SPAK    proteintaxon:10090      20141006        ParkinsonsUK-UCL
MGI     MGI:1858416     Stk39           GO:2000681      MGI:MGI:4834177|GO_REF:0000096  ISO     UniProtKB:Q9UEW8        O       serine/threonine kinase 39      DCHT|RF005|Rnl5|SPAK    proteintaxon:10090      20151125        MGI     
MGI     MGI:1858416     Stk39           GO:2000687      MGI:MGI:5574433|PMID:24393035   IGI     UniProtKB:Q6P9R2        O       serine/threonine kinase 39      DCHT|RF005|Rnl5|SPAK    proteintaxon:10090      20141006        ParkinsonsUK-UCL
MGI     MGI:1858416     Stk39           GO:2000687      MGI:MGI:4834177|GO_REF:0000096  ISO     UniProtKB:Q9UEW8        O       serine/threonine kinase 39      DCHT|RF005|Rnl5|SPAK    proteintaxon:10090      20151125        MGI     
MGI     MGI:2652875     Wnk3            GO:2000682      MGI:MGI:4834177|GO_REF:0000096  ISO     UniProtKB:Q9BYP7        O       WNK lysine deficient protein kinase 3   Prkwnk3|Wnk3|Wnk3-ps   protein  taxon:10090     20110518        MGI     
MGI     MGI:2652875     Wnk3            GO:2000688      MGI:MGI:4834177|GO_REF:0000096  ISO     UniProtKB:Q9BYP7        O       WNK lysine deficient protein kinase 3   Prkwnk3|Wnk3|Wnk3-ps   protein  taxon:10090     20110518        MGI     
```

**Comment by hdrabkin** [comment]
That would be O for obsolete; these should NOT get into the gaf ever; let me look in the db

**Comment by hdrabkin** [comment]
I'm not even allowed to enter "O" in our interface to search

**Comment by hdrabkin** [comment]
These are no longer in our db, as we reran loads on the weekend (which prevent obsoletes from loading). However, if I term became Obsolete during the week, since we load GO every day, those will have "O" as aspect. But they should not have loaded into the Friday  gaf. 
I can submit a new gaf and gpad today.

**Comment by hdrabkin** [comment]
Just looked at Friday's gaf for GO:2000687

I see P as aspect, not O
Our gaf script did NOT output O

MGI	MGI:1917378	Oxsr1		GO:2000687	MGI:MGI:5574433|PMID:24393035	IGI	UniProtKB:Q9Z1W9	P	oxidative-stress responsive 1	2210022N24Rik|2810422B09Rik|Osr1	protein	taxon:10090	20141006	ParkinsonsUK-UCL		
MGI	MGI:1858416	Stk39		GO:2000687	MGI:MGI:5574433|PMID:24393035	IGI	UniProtKB:Q6P9R2	P	serine/threonine kinase 39	DCHT|RF005|Rnl5|SPAK	protein	taxon:10090	20141006	ParkinsonsUK-UCL
MGI	MGI:1858416	Stk39		GO:2000687	MGI:MGI:4834177|GO_REF:0000096	ISO	UniProtKB:Q9U

**Comment by hdrabkin** [comment]
They are obsolete today, but not Friday. Thus were ok for Friday's file.

Term is NOT in  today's GAF.
Since I only upload Friday, where did the file with "O" aspect come from???

**Comment by cmungall** [comment]
Yup, it was on your end, this is where we grab from:

https://github.com/geneontology/go-site/blob/master/metadata/datasets/mgi.yaml#L19

**Comment by cmungall** [comment]
But is fixed now in any case, thanks

**Comment by hdrabkin** [comment]
So when did you fetch from 
 http://www.informatics.jax.org/downloads/reports/gene_association.mgi.gz
Because today it has none of those annotations. It didn't Friday. 
I seriously need to find our how this is happening, but I don't have any evidence in our own files that it happened. 
So if you are now getting these files directly, I can stop commiting to SVN?

**Comment by hdrabkin** [comment]
Although I get reports for obsolete annotations, they should NOT have ended up in a gaf; I requested that when GAF is generated, only F, P, and C aspect get output. I thought this was always in place.

**Comment by hdrabkin** [comment]
So I'll close this for now and we will keep an eye on it.

**Comment by cmungall** [comment]
From now on you will get an explicit report if this happens again, @dougli1sqrd can show you

**Comment by hdrabkin** [comment]
Thanks; So I can stop with the SVN right? And these would merely be kicked out? It would not be fatal for the entire gaf?

**Comment by dougli1sqrd** [comment]
No, but we'll throw out lines that have 'O' as an aspect

**Comment by hdrabkin** [comment]
Good, that's just like what used to happen.
