### ISSUE TITLE
Flybase annotations to GO:0044745 amino acid transmembrane import

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1798]
Hi @hattrill 

Flybase has 11 annotations to  GO:0044745  amino acid transmembrane import all from PMID:16916974. Can you move those to ' GO:0003333 amino acid transmembrane transport'? (since it doesnt seem to be clear on which membrane some of the proteins are located, we cannot tell where it imports). 

Other option if the information is available is to move to  GO:0089718 amino acid import across plasma membrane (I am in the process of merging that with the parent GO:0044745  amino acid transmembrane import )

Thanks, Pascale

**Comment by hattrill** [comment]
Hi Pascale,
As these are based on an ISM for the SLC6 transporters which are generally defined for uptale across the plasma membrane, but I will move them to the more general GO:0003333, as it's only an ISM!

**Comment by hattrill** [comment]
Done

**Comment by pgaudet** [comment]
thanks !
