### ISSUE TITLE
GO annotation camp issues from RGD

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#18]
GO Camp annotation issues from RGD. 

The  PDFs  for the articles have been sent to Midori. 
.
Topics address  issues such as:
Delineating  a cellular component  and
once a component term is assigned 
how to best  describe it?
Delineating scaffold activity
How to best handle and represent glutamate 
receptor(s) 
Gow to deal with splice variants
One process, various directions
Using GFP (green fluorescent protein) and 
evidence code

Delineating a cellular component  what are the 
boundaries, can they always be defined?
Generally a cellular component is a complex, an 
organelle, a vesicle or a compartment. However, 
sometimes there are just specialized structures located 
at, near or associated with a cellular component. For 
instance:

A  characteristic feature of the glutamatergic synapse is 
its asymmetry. Presynaptically, there is an electron-
dense specialization termed the active zone (AZ) where 
synaptic vesicles are docked and fused with the plasma 
membrane; postsynaptically  there is an electron-dense 
thickening of the membrane juxtaposed against AZ and  
termed  the postsynaptic density (PSD). Either is 
constituted by specific proteins that aid in the 
docking/fusion of synaptic vesicles and enable 
glutamate release (AZ) or aid in the glutamate response 
processes (PSD).  A number of proteins are  known to 
be part of either specialization and PSD has been 
estimated to contain over 300 proteins. 

A notable feature of the proteins associated with either 
specialization is their multi-domain structure and the 
range of interactions they are involved in. The Shank 
family  of proteins  they contain Src homology 3 
domain and ankyrrin repeat-containing, also known as 
proline-rich synapse-associated protein/somatostin 
receptor-interacting protein  whose range of direct and 
indirect interactions is too long to cite here  have been 
dubbed master scaffolding proteins of the PSD, PSD 
assembly is essential  for the recruitment of AMPA, 
NMDA receptors to the nascent synapse. Studies aiming 
at monitoring the assembly characteristics of AZ and  
PSD  have used GFP (green fluorescent protein) fusion 
constructs.
PMID: 14960624
PMID: 11509555

(1) Active zone (AZ) and postsynaptic density (PSD)  
should deserve  to be thought of valid cellular 
components.
(2) Maybe scaffold activity term, PSD-related, should be 
revisited.  GKAP/Homer scaffold activity is the only term 
in GO  studies have shown that members of Shank 
family contact members of the metabotropic glutamate 
receptors via Homer/Ves1. What  do others think about. 
We can talk about both Shanks and Homer members - 
the latter represented by three genes with multiple 
splice variants.
(3) How to look upon results using GFP tagged 
molecules, evidence codewise.  I think IMP is more 
suitable than IDA; the fusion construct may have 
properties/behavior different than either constituent 
protein.

Two of the four subunits of the AMPA receptor have 
two splice variants (I have a rat paper on the two splice 
variants  the flip variant is preferentially expressed 
during pre-natal development, the flop is postnatally). 
AMPA is one type of ionotropic glutamate receptor. 
Splice variants are also known for the GABA receptors (I 
have a rat paper on GABA splice variants as well).  GABA 
is the major inhibitory neurotransmitter. Yet GABA 
receptors, along with some olfactory receptors  and 
metabotropic glutamate receptors  constitute one family 
of the GPCR receptors. 
PMID: 12379442
PMID: 14657159

(4) How do people handle splice variants? I know this 
issue has been brought up before, but I think it is worth 
talking about. Splice variants usually have a distinct 
symbol  example subunit 1 has two splice variants, 1A 
and 1B;  they tend  to have similar functions but differ 
in detail  example different desensitization 
susceptibilities and/or current potentials; finally as the 
rat example suggests they may vary with respect to the 
process they support. 
(5) I also think we should revisit the glutamate receptor 
term, which may also impact on the GPCR term(s). Ill 
have a diagram (hopefully) and we could discuss it. 

Clathrin-mediated endocytosis is believed to be the 
major route for synaptic vesicle recycling. Studies have 
recently shown that the metabotropic glutamate 
receptor mGlur5 - a member of Group I metabotropic 
glutamate receptors  is endocytosed via a clathrin-
independent route. 
PMID: 14985443
PMID: 12529370

(6) How could we reconcile the two routes within GO? 
There is no term for clathrin-mediated endocytosis in GO 
and Ill  submit a request for it in SourceForge, since is 
the major endocytic route. But how about the other,  
maybe non-clathrin endocytosis? What do others think?

SNAREs are membrane proteins that catalyze membrane 
fusion  one the best known systems is involved in the 
membrane fusion at the synapse (synaptic SNARE). The 
proteins are defined by a characteristic ~70 residue 
motif that includes eight heptad repeats  and known as 
the SNARE motif. Four SNARE motifs  one each from 
synaptobrevin and syntaxin, and two from SNAP-25  
form a tight complex  that initiates membrane fusion.
PMID: 14529716

(7) The SNARE complex and how it may impart on the 
SNARE activity terms.

Reported by: vpetri

Original Ticket: "geneontology/annotation-issues/18":https://sourceforge.net/p/geneontology/annotation-issues/18

**Comment by linuxlovell** [comment]
thanks www.movied.org
