### ISSUE TITLE
Annotation review for L-glutamate transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1800]
Hello, 

I am not sure these two paper show direct involvement of the proteins in transport: 

* gb | genderblind |   | L-glutamate transport |   | FlyBase | Drosophila melanogaster | IMP |   | amino acid transporter pthr11785 |   | FB:FBrf0202691PMID:18193891
* Psen1 | presenilin 1 |   | L-glutamate transport |   | MGI | Mus musculus | IMP | MGI:MGI:1857974 | presenilin pthr10202 |   | MGI:MGI:3622834PMID:15009636

@hdrabkin 
@hattrill 
Can you please have a look ? 
https://docs.google.com/spreadsheets/d/1lCgM_gm8uguaVNcOfNOgfEC1G5SSFUnpiTqzNf6WY_0/edit#gid=0

Thanks, Pascale

**Comment by hattrill** [comment]
With you there. Pow - gone!

**Comment by hdrabkin** [comment]
Curator will look into it later today; I'll close it when they get back to me; suspect GO id typo

**Comment by hdrabkin** [comment]
done.
