### ISSUE TITLE
IPR033481 mapping to GO:0000753

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1802]
Hello,

we have an IEA mapping from IPR033481 to GO:0000753 cell morphogenesis involved in conjugation with cellular fusion

Could this please be reviewed? This protein is involved in GO:0032220 plasma membrane fusion involved in cytogamy (this is downstream from cell morphogenesis)

Cheers

**Comment by EBI-Hsinyu** [comment]
Hi, 
You are right. GO:0032220 is a better term for this entry. The result will be visible in our next release. Thank you for letting us know. 
Cheers, 
Hsin-Yu
