### ISSUE TITLE
mapping to DNA repair for RNA polymerase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1803]
http://www.uniprot.org/uniprot/P20433
from
https://github.com/geneontology/go-annotation/issues/1503

**Comment by sylvainpoux** [comment]
Hi Val,
not sure for this one. Information on DNA repair comes from PubMed=12411509

Why would you remove this? Do you have eivdnece that this information is incorrect? Thanks Sylvain

**Comment by ValWood** [comment]
It's probably a bit indirect for a mapping, as it is probaly just a requirement of this subcomplex  for the transcription of specific subsets of genes.
 https://www.yeastgenome.org/reference/S000086303
It's not really strong enough evidence for a  mapping that would be transferred to other species. We see the same thing that certain polymerase subunits have phenotypes. There are differences anyway because rpb4 is an essential RNA polymerase subunit in pombe and it's non essential for vegetative growth in S. cerevisiae

**Comment by sylvainpoux** [comment]
OK, removed the KW
