### ISSUE TITLE
amino acid metabolic process indirect for some

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1804]
siroheme biosynthetic process/sulfate assimilation etc

O14172 SPAC4D7.06c met8 GO:0008652 UniProtKB-KW:KW-0028
P78937 SPBC27.08c sua1 GO:0008652 UniProtKB-KW:KW-0028
Q09878 SPCC584.01c SPCC584.01c GO:0008652 UniProtKB-KW:KW-0028
Q1K9C2 SPAC10F6.01c sir1 GO:0008652 UniProtKB-KW:KW-0028
Q9USP8 SPBC902.05c idh2 GO:0008652 UniProtKB-KW:KW-0028

and orthologs...

**Comment by sylvainpoux** [comment]
@marcfeuermann  Marc, could you have a look when you have a moment? I suspect these KW should be removed from entries?

**Comment by ValWood** [comment]
Hi @marcfeuermann  did you have time to look at these. I checked met8 and it still has the KW.

Cheers
Val

**Comment by marcfeuermann** [comment]
Oups, this is an old story. Sorry for the delay, I've totally missed this one. I've removed the KW-0028 manually when it was possible. I've also contacted my colleagues propagating stuff via HAMAP annotation rules to update rule MF_03106 (https://hamap.expasy.org/rule/MF_03106) to remove the propagation of this KW.
