### ISSUE TITLE
PAINT, elongator is not a histone acetyltransferase  	PTHR11135

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1806]
it is involved in
tRNA wobble base 5-methoxycarbonylmethyl-2-thiouridinylation

please delete
http://www.uniprot.org/uniprot/O14023

histone acetyltransferase activity
and
regulation of transcription from RNA polymerase II promoter

(can't check the family as QuickGO is broken)

**Comment by ValWood** [comment]
see 
https://github.com/geneontology/go-annotation/issues?q=is%3Aissue+elongator+is%3Aclosed

for some history.

**Comment by ValWood** [comment]
The current def of elongator
Definition
A heterohexameric protein complex that is involved in modification of wobble nucleosides in tRNA. The complex can associate physically with hyperphosphorylated RNA polymerase II; it contains two discrete heterotrimeric subcomplexes. Source: PMID:23165209, PMID:17018299, GOC:vw, PMID:15769872, GOC:bhm, PMID:11689709, PMID:18755837, GOC:jh, PMID:11435442, GOC:mah
Comment
Despite its name, this complex is no longer thought to be directly involved in transcriptional elongation (PMID:23165209).

see this paper and other recent ones
https://www.ncbi.nlm.nih.gov/pubmed/23165209

**Comment by ValWood** [comment]
Extensive work in budding yeast and fission yeast strongly support that Elongator is primarily implicated in tRNA modifications in these two species, which underlies a new mechanism that fundamentally contributes to gene expression regulation.

(all the transcription phenotypes are suppressed by tRNA overexpression)

**Comment by ValWood** [comment]
It doesn't have any domains related to acetyltransferases....

**Comment by ValWood** [comment]
histone acetyltransferase activity |   | IDA | SGD | 2007-01-08 |   | Wittschieben BO, et al. (1999)PMID:10445034


This annotation was removed from SGD back in 2006  by  Maria when the  tRNA modification info came to light as is not now considered to be physiologically relevant (all phenotypes are suppressed by over-expression of tRNA...there are lots of more recent papers)

@srengel  could you get soeone take a look ?

**Comment by ValWood** [comment]
I'm a bit confused because I don't see the SGD annotation in the UniprotKB entry, but http://www.uniprot.org/uniprot/O14023
I do see a GOC mapping....
Seems very strange...

**Comment by ValWood** [comment]
In quickGo its just IBA and IDA, maybe you already removed it?
![in quickgo](https://user-images.githubusercontent.com/7359272/36155164-84beb88e-10cb-11e8-884b-a805b319036b.jpg)

**Comment by srengel** [comment]
if the annotation was removed in 2006, it must have been added back in 2007.  

to make sure i understand, you are asking that we re-remove the histone acetyltransferase MF annot for ELP3?

**Comment by ValWood** [comment]
yes the consensus is that it isn't a histone acetyltransferase according to papers post 2005

"This domain is not involved in histone acetyltransferase activity, but it could have a role in 5carboxymethyluridine modification through an unprecedented chemistry performed on acetyl-CoA [according to PMID:25151136]. It seems that the function of the domains of Elp3 is not exactly known."

see also
https://github.com/geneontology/go-annotation/issues/1805
and linked tickets.

**Comment by pgaudet** [comment]
@srengel @ValWood 
Is this a case where NOT should be used, to make sure we don't repeat the mistake again? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood are you saying that the UniProt summary is incorrect ? 
http://www.uniprot.org/uniprot/Q9H9T3

**Comment by ValWood** [comment]
> are you saying that the UniProt summary is incorrect ?

yes it's very out of date...

**Comment by pgaudet** [comment]
One problem is that UniProt has a mapping of Elongator complex protein 3  to EC:2.3.1.48, Histone acetyltransferase (this corresponds to the IEAs)

Same problem with InterPro. I will create separate tickets for those.

**Comment by pgaudet** [comment]
We also need to request groups with primary EXP annotations to add 'NOT' annotations to avoid confusion in the future. 

@srengel  SGD ELP3
@RLovering Human ELP3

**Comment by ValWood** [comment]
I'm pretty sure I reported these previously....

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/1806#issuecomment-385909608

**Comment by ValWood** [comment]
corrected 
https://github.com/geneontology/go-annotation/issues?q=is%3Aissue+elongator+is%3Aclosed
