### ISSUE TITLE
Ensembl Plants annotation transfer to S. cerevisiae???

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1807]
Cerevisiae elongator complex
http://www.uniprot.org/uniprot/Q02908

has
regulation of auxin mediated signaling pathway Source: EnsemblPlants
regulation of leaf formation Source: EnsemblPlants

**Comment by ValWood** [comment]
This raises a number of questions.

First, why are Ensembl plants transferring data to fungi
Second, why don't these get flagged by taxon restrictions?

**Comment by pgaudet** [comment]
@tonysawfordebi  any idea what's happening ?

**Comment by ValWood** [comment]
for instance SOD1 annotaed to 
response to ozone, respond to cold, response to UV-B, reps one to light intensity
 cellular response to sucrose stimulus

annotations to 
gene silencing by miRNA (cerevisiae does not have this pathway)

 symmetric cell division???

that’s on the first page…..

**Comment by ValWood** [comment]
I think we should ban "response to x" from annotation transfer anyways.

**Comment by tonysawfordebi** [comment]
@ValWood I've had a look into the original annotations that you mentioned, and discovered two things:

- Ensembl  are indeed saying that Q93ZR1 and Q02908 are orthologs
- GO:0010928 and GO:2000025 appear not to be subject to any taxon constraints

I'll contact Ensembl about the first point, and direct them towards this thread so that they can comment directly.
With regard to the taxon constraint thing, that sounds like something for the GO editors to address.

Finally, some time ago I proposed (although I can't remember where or to whom) the introduction of a third subset to complement gocheck_do_not_annotate and gocheck_do_not_manually_annotate, called gocheck_do_not_propagate to indicate that annotations to a term thus flagged should not be transferred to another gene product, even if the target gp is an ortholog (or claimed to be one). Maybe the time has come to introduce that...?

**Comment by ValWood** [comment]
Yes they are orthologs. This does not mean that plant-specific annotations should be transferred to fungi.

In the previous pipeline NO annotations were transferred to any of the models (this makes sense  for an automated pipeline).

Annotations should not be transferred  from non fungal species to fungi. It will cause way to many problems.

**Comment by ValWood** [comment]
Experimental annotation from cerevisiae and pombe should propagate to other fungal species (but not to each other). This would be fairly safe (although often inaccurate, would provide a reasonable first pass annotation for  unannotated species). 

Under no circumstances should  annotations from plant be transferred to cerevisiae or pombe. 
If these annotations are valid they will almost certainly already be present.  A large percentage will be incorrect.......

**Comment by tonysawfordebi** [comment]
So we need taxon constraints and some kind of do_not_propagate mechanism (that obviously isn't specific to plants and fungi).

**Comment by ValWood** [comment]
I would say do not propagate between kingdoms.
Use the model organisms for the respective  kingdoms to propagate from. Anything else will create a big mess. Of course, the orthologs are largely functionally conserved but the functions occur in many different  contexts (processes)  in different species.

Even the correct annotation will be redundant in which case its  totally superflous...

**Comment by RLovering** [comment]
Hi Val

Please confirm which species you are including in your statement 'we should ban "response to x" from annotation transfer'.

I think this is a valid annotation to transfer across mammalian orthologs

Best

Ruth

**Comment by ValWood** [comment]
Well most are used very badly. They aren't really representing processes, just phenotypes.
There are a subset that really are valid processes, but we have "response to every chemical".

cellular response to topoisomerase inhibitor?
cellular response to gold(3+)? 
cellular response to alkane?
 cellular response to boron-containing substance levels? 


It would be better if these were made to represent process annotations to make them meaningful

"signalling pathway x" occurs_during "response to y"

or "cellular detoxification" in response to y.

I can't see how these are meaningful in isolation, if you can't link them to an actual biological process.....otherwise they are just phenotypes...

**Comment by ValWood** [comment]
You can throw any chemical at an organism and most times there will be some "response"...what does it mean?

**Comment by ValWood** [comment]
we also have
GO:0072757    cellular response to camptothecin
(camptothecin is A topoisomerase inhibitor)

These aren't normal processes.....

**Comment by ValWood** [comment]
GO:1901593   response to GW 7647
it's crazy! (although this one isn't used)

**Comment by ValWood** [comment]
GO:1904842    response to nitroglycerin?
(from a microarray expression profile) do you really want to transfer these?

GO:0070301   cellular response to hydrogen peroxide??
isn't that just the oxidative stress response? It's a condition  used to produce oxidative stress (that's a useful one).

**Comment by mah11** [comment]
Re "response to" terms: quite a few of the strange-looking ones are there to allow other ontologies (including FYPO) to use them in logical definitions or other cross-references. Any such terms should be flagged as not for gene product annotation (I thought they were, but it's certainly possible that some were missed).

https://mailman.stanford.edu/pipermail/go-ontology/2016-April/007432.html

**Comment by RLovering** [comment]
yes I agree GO:0070301 cellular response to hydrogen peroxide should probably not be a term, we have used this 9 times. The problem is now look at the ontology! Also people have used this because it is there

Ruth

**Comment by ValWood** [comment]
I know....I talked about this at the GO meeting in the "slimming talk". It is difficult to assess what is "unknown" when 
we have ~50% of a species proteome annotated to "response to" terms...

**Comment by ValWood** [comment]
Discussion about "response to" is now here:
https://github.com/geneontology/go-ontology/issues/15103

**Comment by ValWood** [comment]
@srengel  (for SGD)

**Comment by srengel** [comment]
yeah 'regulation of leaf formation' is not a good annotation to transfer to yeast. i agree with Val that plant-specific annotations should never be transferred to fungi.  for a broader rule, seems reasonable to not do automatic transfer between kingdoms.  most especially when a curated model organism set is available for transfer within the kingdom.

**Comment by ValWood** [comment]
@pgaudet 
here are some suggestions for IEA pipeline consolidation

**Comment by ValWood** [comment]
This pipeline Ensembl plant annotation tranfer pipeline no longer seems to be no active

**Comment by pgaudet** [comment]
And this should be picked up by TC...
