### ISSUE TITLE
Annotation review: glucose transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1810]
Hello, 

I noticed a few suspicious annotations to 'glucose tranport's - some seem quite indirect. 

Please have a look and correct as appropriate: 
https://docs.google.com/spreadsheets/d/1qBtFV09FVrPnuVqNYSLqC3JsAWPK9P8pbJMd05GHxKU/edit#gid=0

(This is not the whole list; I only extracted those that seemed odd). 

Pascale

**Comment by hdrabkin** [comment]
Li Ni  will investigate for MGI

**Comment by hdrabkin** [comment]
because I accidentally removed everyone.

**Comment by RLovering** [comment]
BHFL annotation revised

**Comment by pgarmiri** [comment]
UniProt annotations have been updated.

**Comment by LiNiMGI** [comment]
MGI annotations have been checked and updated, please see excel sheet for details.

**Comment by suzialeksander** [comment]
SGD annotations have been changed.  I also emailed @jimhu-tamu in case they can edit the CACAO one.

**Comment by pgaudet** [comment]
Thanks everyone !
