### ISSUE TITLE
Annotation review to GO:0005110 frizzled-2 binding

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1812]
From the signaling workshop:

A proposal was made to merge GO:0005110 frizzled-2 binding into GO:0005109 frizzled binding since GO:0005110 frizzled-2 binding is a gene product-specific term.

https://github.com/geneontology/go-ontology/issues/14183

There are eight experimental annotations to this term, five from FlyBase and three from MGI.  

@hattrill - from the ontology ticket, it looks like it was okay to move the FB annotations, but I didn't see the updated annotations in AmiGO, so wanted to double-check before doing the merge.

@ukemi @hdrabkin - can one of the MGI curators check the three MGI annotations?

Spreadsheet is here:
https://docs.google.com/spreadsheets/d/1Yqan9pHEvWxY0bdrklXPV53rD0WuOevxqyXWaDI9awQ/edit#gid=0

Thx.

**Comment by ukemi** [comment]
MGI annotations changed.

**Comment by hattrill** [comment]
Hi Kimberly, 
wingless ones have been done, but I I had one other that I'd missed in the purge! Gone now!

**Comment by vanaukenk** [comment]
Great; thank you @hattrill   
I will go ahead with the merge.
