### ISSUE TITLE
C3AR1 UniProtKB:Q16581 Annotation

### ISSUE THREAD

**Issue by simondharding** [geneontology/go-annotation#1813]
As part of our curation of the Guide to IMMUNOPHARMACOLOGY (www.guidetoimmunopharmacology.org), one of our expert contributors as pointed out some possible alternation to the annotation of C3AR1.
There is a suggestion to remove ‘positive regulation of neutrophil chemotaxis’ (or change to eosinophil – see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2192052/). Also, to remove neutrophil degranulation. Also 'negative regulation of neutrophil mobilization' should be added (eg. https://www.ncbi.nlm.nih.gov/pubmed/23696668).
Many thanks, 
Simon Harding, Database Developer, Guide to IMMUNOPHARMACOLOGY.

**Comment by deustp01** [comment]
The relevant Reactome annotations assert that C3AR1 protein is a component of the azurophil granule membrane that becomes associated with the plasma membrane when degranulation occurs. I may be missing something but I don't see how either of these annotations asserts that C3AR1 has a function in the degranulation process or its regulation, so I'm not sure why this annotation is a concern here.

**Comment by ggeorghiou** [comment]
Reviewing this after a substantial amount of time now. I don't see an issue and agree with Peter's assessment. Closing this ticket.
