### ISSUE TITLE
Uniprot annotation of pombe gcn1

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#1815]
Hello,

pombe gcn1 (UniProtKB:Q10105) has an annotation assigned by Uniprot

![screen shot 2018-02-14 at 14 48 51](https://user-images.githubusercontent.com/12727506/36210431-4e0d6152-1196-11e8-9201-ed3e36ece700.png)

Could this please be removed? gcn1 negatively regulates translation
see PMID:28771613

**Comment by ValWood** [comment]
seems to be done!
