### ISSUE TITLE
request for annotation review of usage of the tRNA 3' end nucletotidyl transferases

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#1817]
This was discovered while tending to #11721 in the ontology tracker. 
There are 3 types of enzymes involved here
   1.  CCA tRNA nucleotidyltransferase. adds CCA consecutively, but can also add A to a 3' CC.
    THIS is the activity that should be annotated to for most organisms.
    This is EC:2.7.7.72, CCA tRNA nucleotidyltransferase.
    Even if all that is measured is "A" addition, this is the enzyme that does in

   2.  in SOME organisms, the CC gets added by one enzyme and the A gets added by a second enzyme. In Aquifex aeolicus, Deinococcus radiodurans, Bacillus halodurans, and Synechocystis sp., CCA synthesis is catalyzed by two nucleotidyltransferases (CC-adding and A-adding enzyme)
    in a stepwise addition of two C and one A residues.

This also means that the reaction in GO indicating addition of a single A to the 3'end of a tRNA-CC should only be used for cases like #2.

In summary
GO:005292 ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity; should be used only for case 2

GO:0052928 CTP:3'-cytidine-tRNA cytidylyltransferase activity; should not be used; should be obsoleted

GO:0052927: CTP:tRNA cytidylyltransferase activity; case 2 only, different gene product
It's def Catalysis of the reaction: a tRNA precursor + CTP = a tRNA with a 3' cytidine end + diphosphate., should be changed to Catalysis of the reaction: a tRNA precursor + 2CTP = a tRNA with a 3' CC end

GO:0001680 tRNA 3'-terminal CCA addition This is EC 2.7.7.72 ; this can added either the C's or the As as needed. This is what all other organisms should be annotated to. I think any annotation existing that is to anything else should be changed to this term (unless you are dealing with the two ogranisms listed above).

**Comment by hdrabkin** [comment]
OR, since I don't see any annotations properly attributed to 927 and 292, I could merge those into 1680 and then all current annotations would be correct.
 CTP:tRNA cytidylyltransferase activity: GO:0052927; iea only; no problem making it go away

also found "GO:0004810, which should be merged into GO:0001680 (tRNA adenylyltransferase activity) ; both have same ec number even, so this was NEVER meant to be an enzyme that only adds A (also represents an deprecated EC number and is scheduled to be obsoleted.

**Comment by ValWood** [comment]
This is an old request to review but it was never assigned to anyone. I have a feeling that this has been addressed subsequently  by 
@sjm41 . Do you think we can close this, or do we still need to doe anything?

**Comment by pgaudet** [comment]
Looks like this was done here: https://github.com/geneontology/go-ontology/issues/19854
