### ISSUE TITLE
Annotation review to regulation of transcription by glucose

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#1818]
Currently the terms and children of 'negative regulation of transcription by glucose' (GO:0045414)  are children of carbon catabolite repression of transcription. The references support this placement even though the definitions are more generic. For the most part I think that these terms have been used in annotation with respect to the carbon catabolite repression pathway, but there are a few annotations to them from organisms that do not have these pathways (human and mouse). 

I have renamed these terms 'carbon catabolite repression of transcription by glucose ' and 'carbon catabolite repression of transcription from RNA polymerase II promoter by galactose'. I created new generic terms for simply 'negative regulation of transcription by glucose' (GO:0061986) and 'negative regulation of transcription from RNA polymerase II promoter by glucose' (GO:0061987)

Curators from databases that have annotated to these terms should check their annotations and make sure they are using the correct term.

The spreadsheet is here:

https://docs.google.com/spreadsheets/d/1_8fqztTF0GRTLkaA0MdVaVUMQNYWVdxPqEZu4zoA3n0/edit#gid=0

**Comment by ValWood** [comment]
@Antonialock  this is your area, could you do this one for PomBase?
(remove yourself as assignee when done)
v

**Comment by RLovering** [comment]
BHF-UCL annotation updated, no access to edit the spreadsheet
Ruth

**Comment by pgaudet** [comment]
I fixed the sharing properties of the file. 

Pascale

**Comment by pgarmiri** [comment]
Both UniProt annotations checked. One changed to a (different) more appropriate term and the other is a valid one.

**Comment by suzialeksander** [comment]
I've checked all the SGD ones.

**Comment by pgaudet** [comment]
@ukemi Looks like all annotations have been checked. (I can close the ticket and edit the spreadsheet to mark it DONE but I though it would be better if you checked.) 

Thanks, Pascale

**Comment by ukemi** [comment]
You are right. It looks like they have all been addressed.
