### ISSUE TITLE
Review PAINT annotations to GO:0071790 establishment of spindle pole body localization to nuclear envelope

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1819]
Hi,

I was looking at the annotations to GO:0071790 'establishment of spindle pole body localization to nuclear envelope' in AmiGO and there are a number of annotations, both NOT and positive, to metazoan gene products even though the term definition states that spindle pole bodies are found in fungi:

A process in which a spindle pole body is transported to a specific location in the nuclear envelope. A spindle pole body is a type of microtubule organizing center found in fungal cells.

http://amigo.geneontology.org/amigo/term/GO:0071790

The positive annotations need to be checked, but I even find the NOT annotations unsatisfactory.  Our annotation documentation states that the NOT qualifier "is used when a GO term might otherwise be expected to apply to a gene product, but an experiment, sequence analysis, etc. proves otherwise."  In the case of these metazoan gene products, it seems that even the NOT annotations don't really make sense.

Is there a way, in PAINT, to block propagation of an annotation without also specifically making the NOT annotation?

**Comment by pgaudet** [comment]
Hi @vanaukenk 
Thanks for pointing that out. In PAINT I don't see the annotations; my guess is that they come from the 'touchup' script that  check PAINT annotations after they have been made. 


However the specs were that we get in IRD annotation - ie 'do not propagate' for those; I have no idea why those get in the GAF as NOT IBA. 

@selewis  @huaiyumi Where is this script run now ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Updated annotations according to @vanaukenk 's comment.

**Comment by pgaudet** [comment]
@ValWood why did you close this ? 

The annotations are inconsistent between PAINT and AmiGO - it's important to understand why. 
@selewis @huaiyumi  any thoughts ?

**Comment by ValWood** [comment]
sorry, my mistake, I thought it was something else.
