### ISSUE TITLE
IPR020082 one-carbon metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1820]
is 

adenosylhomocysteinase (predicted)

https://www.pombase.org/gene/SPBC8D2.18c

do you think that's correct, it doesn't seem so?

**Comment by asangrador** [comment]
I have removed the one-carbon metabolic process, I am not sure why it was added in the first place. Regarding the other term, all the predictions from InterPro seem to indicate it is an adenosylhomocysteinase.
