### ISSUE TITLE
Yeast RAD3 phosphorylation activity should be (CONTRIBUTES TO)

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1822]
The RAD3 gene (also known as "General transcription and DNA repair factor IIH helicase subunit XPD") of YEAST
http://amigo.geneontology.org/amigo/gene_product/SGD:S000000973
It has the function "phosphorylation of RNA polymerase II C-terminal domain"
but I believe it should be CONTRIBUTES TO this activity if the following page is correct:
http://www.uniprot.org/uniprot/P06839
where it says: "Phosphorylation of the C-terminal tail (CTD) of the largest subunit of RNA polymerase II by the kinase module TFIIK controls the initiation of transcription. XPD/RAD3 acts by forming a bridge between TFIIK and the core-TFIIH complex."  As RAD3 is TFIIH and not TFIIK, it should be CONTRIBUTES TO.

**Comment by ValWood** [comment]
Hi,
contributes_to is only used with molecular function.
val
