### ISSUE TITLE
definition typos

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-annotation#1823]
The definitions for “regulation of sarcomere organization” (GO:0060297), “positive regulation of sarcomere organization” (GO:0060298), and “negative regulation of sarcomere organization (GO:0060299) need “of” added between “extent” and “myofibril assembly”.

**Comment by vanaukenk** [comment]
Same here - closing this ticket as it is a duplicate of a term in the ontology tracker.
https://github.com/geneontology/go-ontology/issues/15216
