### ISSUE TITLE
Review annotations to receptor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1827]
The definition of 'receptor activity' "Combining with an extracellular or intracellular messenger to initiate a change in cell activity. " is almost the same as 'signaling receptor activity' "Receiving a signal and transmitting the signal in the cell to initiate a change in cell activity. A signal is a physical entity or change in state that is used to transfer information in order to trigger a response."

These two terms will be merged, see 
https://github.com/geneontology/go-ontology/issues/15234

Please review your annotations to make sure that the annotation was indeed for 'signaling receptor activity' , NOT a 'cargo receptor activity'. 

https://docs.google.com/spreadsheets/d/18zaDTpRQzAgy6rvNqHDMS4ZxlcmoUGKZA18CuciwExM/edit#gid=0

Affected groups
--
AgBase @jinhuiz
ARUK-UCL
BHF-UCL
CGD @marekskrzypek
FlyBase
GO_Noctua 
HGNC @RLovering
MGI
RGD
SGD
SGN ??
TIGR ??
UniProt
WB
ZFIN
InterPro

**Comment by slaulederkind** [comment]
RGD has no manual annotations for 'signaling receptor activity'.

**Comment by srengel** [comment]
addressed these 4 annotations for the 3 genes in Sc.  for 2 of the genes i changed it to 38024.  for the other gene, i removed it.

**Comment by hattrill** [comment]
I have a quite a few to go through (~30 genes) - some easy, some not so easy (as they are adhesion receptors that can signal). Should have reviewed them by the start of next week, I hope!

**Comment by RLovering** [comment]
Hi
I have checked the 2 annotations for UCL
1. Slc40a1 (mouse and ISS'd to human) looks right, have updated to GO:0038023. Although, it is weird to be a cargo receptor and signaling receptor: Paper title Hepcidin Regulates Cellular Iron Efflux by Binding to Ferroportin and Inducing Its Internalization. hepcidin ( a peptide hormone) bound to ferroportin (Slc40a1) leading to internalisation of this transporter.
2. I have asked Barbara to revise the second annotation
Ruth

**Comment by RLovering** [comment]
Hi All

I am interested to hear that Helen has adhesion molecules annotated to receptor activity. I have a feeling that many adhesion molecules signal and I was wondering how this was going to be captured. I would like people to consider reinstating the term: GO:0004895 cell adhesion receptor activity which was removed when people decided adhesion wasn't a function ;(

Another option might be to create the term: 
GO:0098631  cell adhesion mediator activity
GO:0004888 transmembrane signaling receptor activity
>is_a Child new term: cell adhesion mediator receptor activity

If this seems reasonable let me know and I will submit a request

Thanks

Ruth

**Comment by hattrill** [comment]
It doesn't seem too unreasonable!
The majority of annotations are ISS/NAS/TAS, so probably ancient and will go straight to bin. 
Integrins, planar cell polarity are a classic example of signaling/adhesion cross-overs. I'll let you know when I've poked them with my large stick 

(Only ~6 genes have exp annotations.)

**Comment by pgaudet** [comment]
I had forgotten to add the link to the spreadsheet, here it is: 
https://docs.google.com/spreadsheets/d/18zaDTpRQzAgy6rvNqHDMS4ZxlcmoUGKZA18CuciwExM/edit#gid=0

If you already fixed the annotations, would you please anyway go in and mark them in the spreadsheet ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
Scanned through complexes (260!): all look like classic signalling receptors. Including all the integrins!

**Comment by vanaukenk** [comment]
I updated our one WB annotation to GO:0004888 transmembrane signaling receptor activity.

**Comment by pgaudet** [comment]
Thanks to all ! 

@bmeldal you are OK with integrin being a signalling receptor, or do you prefer the adhesion signaling term ?

**Comment by bmeldal** [comment]
It's fine, they are annotated with "transmembrane signaling receptor activity" and "cell-matrix adhesion". That should do.

**Comment by RLovering** [comment]
But they should also be annotated to GO:0098631   cell adhesion mediator activity to ensure consistant annotation

**Comment by bmeldal** [comment]
>But they should also be annotated to GO:0098631 cell adhesion mediator activity to ensure consistent annotation

Do you mean the integrins, Ruth? Yes, I can add it. (They were done before my time...)

>also see NTR cell adhesion receptor activity #15237

If we end up with a new/reinstated term cell adhesion signaling receptor activity I'll wait with doing edits.

**Comment by slaulederkind** [comment]
All RGD annotations for "receptor activity" have been checked, changed, or deleted.

**Comment by pgaudet** [comment]
Thanks for describing the potential confusion here @RLovering 
I'd like to discuss with @vanaukenk @ukemi @thomaspd to provide guidelines - and we should later discuss this on an annotation call.

**Comment by ukemi** [comment]
I had the same question as @RLovering . In many cases, the receptors that bind to molecules that activate signaling pathways also endocytose to recycle the receptors and sometimes to regulate the pathway.

**Comment by asangrador** [comment]
Hi,
InterPro annotations are reviewed and  done. We had 44 annotations to  'receptor activity', and most of them are fine (they correspond to 'signaling receptor activity') ; I only had to change or delete 7. I found that nomenclature is confusing  in some cases, for example the' Catecholate siderophore receptor Fiu' (P75780) is involved in siderophore transport, so apparently is not a receptor despite its name.

**Comment by sabrinatoro** [comment]
ZFIN annotations were reviewed.

**Comment by pgarmiri** [comment]
UniProt annotations have been reviewed. Only one is pending but the PIR curator has been contacted and hopefully that will be updated soon. Changes have been report on the excel sheet.

**Comment by ukemi** [comment]
MGI annotation checks completed.
