### ISSUE TITLE
Some EXP annotations incorrectly have RGD as source? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1828]
Hi @slaulederkind 

Many times I incorrectly ask you to review annotations - latest example is in #1827 

However in AmiGO RGD is listed as the contributor of these annotations; is there some mix up in the pipeline somewhere?  

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/4782928/36511884-78ae6564-1736-11e8-8b7e-60b964c5a5fe.png">

**Comment by cmungall** [comment]
@pgaudet, I understood @slaulederkind to say no manual for SRA. Your screenshot is manual for RA. This is RGD SRA; all are electronic. They are a mixture of manual and automatic. Perhaps @slaulederkind intended to say no experimental SRA?

![image](https://user-images.githubusercontent.com/50745/36519132-a1814440-173e-11e8-8423-7d5b8e3fb307.png)

In any case, the results in amigo are the same as RGD, e.g. https://rgd.mcw.edu/rgdweb/report/gene/main.html?id=619837

So I think pipeline is fine here

**Comment by pgaudet** [comment]
Oups, ok thanks.

**Comment by hdrabkin** [comment]
Hi @slaulederkind  we just recently found an error in our GAF/GPAD pipline that atrributed  OUR ISO from Rat exp to RGD,when in fact they should be marked MGI since WE declared the ortholgy.  This has been fixed so the next time our GAF and GPADs are picked up,these will have changed

**Comment by slaulederkind** [comment]
All sounds good.  I'll check the RGD manual "receptor activity" annotations.
