### ISSUE TITLE
Rat PRPP Associated Proteins should be modified as (CONTRIBUTES TO)

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1829]
Rat proteins:
http://amigo.geneontology.org/amigo/gene_product/RGD:620207
http://amigo.geneontology.org/amigo/gene_product/RGD:620206
are PRPP synthase *associated protein*.  It is homologous to PRPP synthase, and is associated in the same complex as PRPP synthase, but is known to have altered active site and binding site residues.  It also shares non-homologous [to PRPP synthase] insert(s) which are themselves conserved amongst PRPP synthase associated proteins. Rat purified proteins has been shown to lack PRPP synthase activity (ribose phosphate diphosphokinase activity).  
So the molecular function should be "ribose phosphate diphosphokinase (CONTRIBUTES TO)" as it is part of the complex that has that molecular function.  The 2 yeast equivalents are already categorized under the (CONTRIBUTES TO) category.
A 2017 review (PMCID: PMC5312242) details this information.
See section entitled "(ii) PAP." where PAP-39 and PAP-41 are discussed.  Farther down in the article is where the rat proteins are discussed.

**Comment by slaulederkind** [comment]
The source of those annotations are Interpro, not RGD.

**Comment by ValWood** [comment]
I no longer see these annotations . If I missed them, reopen and assign to InterPro.
Thanks!
