### ISSUE TITLE
 IPR004574  NOT DNA repair

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1830]
http://pombase-dev.bioinformatics.nz/gene/SPBC13G1.04c

O60066

IEA with IPR004574
but this is a tRNA demethylase

(I think the problem is that another family member is a histone H2A dioxygenase)
Val

**Comment by asangrador** [comment]
Thanks Val,
It is the same for mammals, ABH1 is involved in tRNA modification. I have removed the DNA repair term.
