### ISSUE TITLE
PTN000229249 guanylate cyclase activity vs adenylate cyclase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1831]
FBgn0003301/rut/P32870 It is an adenylate cyclase and is annotated as such in FlyBase 

Have a problem with:
http://www.pantree.org/node/annotationNode.jsp?id=PTN000229249

UniProtKB:P32870 is labelled with:
 cGMP biosynthetic process
guanylate cyclase activity
guanylate cyclase complex, soluble

The curator note says:
Curator note:This family contains both adenylate and guanylate cyclase. The tree is a bit auckward. The two devides well, except for the bacterial sequences at the bottom. Thus, it is possible that AC evolved earlier, and GC came later.

Perhaps the distinction isn't so clear. Could you review this node.

**Comment by pgaudet** [comment]
FBgn0003301 is not under PTN000229249 anymore. It's now in PTHR45627
