### ISSUE TITLE
Human CDKN1B does not have protein kinase activity

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1833]
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P46527
This human gene is a ser/thr protein kinase INHIBITOR, and it does not hit any PFAM kinase domain, etc.  It should not have "cyclin-dependent ser/thr protein kinase activity"

**Comment by pgaudet** [comment]
This annotation is coming from Reactome @deustp01

**Comment by deustp01** [comment]
This is another instance of our long-time GAF mistake of attributing the molecular_function associated witha  reaction and propagating it onto protein substrates of the reaction. That error has now been fixed and GO annotations like this should disappear from our next release, planned for later this month.

**Comment by pgaudet** [comment]
thanks @deustp01 !
