### ISSUE TITLE
InterPro: InterPro2GO mapping - IDs with a large number of term mappings

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1834]
Hi InterPro,

We noticed that we had a large number of MF annotations coming from an InterPro mapping from IPR023102 - it looks like many of the potential activities of this superfamily had been mapped to this ID rather than using a higher-level grouping term such as "fatty acid synthase activity GO:0004312"

I did a count of InterPro IDs with a large number of mapped terms from the InterPro2GO file and found some more with a lot of term mappings  - many are from a proliferation of biological processes that are probably too specific to be blanket-assigned to a family or domain, rather than the MF problem with IPR023102.

I am attaching a spreadsheet of InterPro IDs with 7 or more terms associated with them (fairly arbitrary cutoff). Could you review some of the worst cases, please.

Thanks, Helen

[InterPro_greaterthan6.xlsx](https://github.com/geneontology/go-annotation/files/1784425/InterPro_greaterthan6.xlsx)

**Comment by almitchell** [comment]
Hi Helen,
Thanks for letting us know. It looks like something has gone wrong with the mapping of GO terms to that entry. We think this is a historical problem. We are now reviewing all of the entries in your list and other domain-based annotations to check them and remove / remap problematic terms.
Alex

**Comment by hattrill** [comment]
Thanks!
