### ISSUE TITLE
nucleoside deoxyribosyltransferase activity InterPro:IPR007710

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1835]
is
nucleoside deoxyribosyltransferase activity
correct for
http://www.uniprot.org/uniprot/O43598
it is annoted to
deoxyribonucleoside 5'-monophosphate N-glycosidase activity

and there is no mention of multi functionality.

(I'm looking at the ortholog)

**Comment by asangrador** [comment]
You are right, it is not correct. This entry matches two related families with different functions, and both functions were added by mistake. I have removed the terms.
