### ISSUE TITLE
odd annotations for human GPI (glucose-6-phosphate isomerase)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1838]
1 -[ ]  uniprot KW mapping to cytokine? @sylvainpoux  is that correct?
can function as a tumor-secreted cytokine (not normal role?)

2 - [ ] angiogenesis  @sylvainpoux  is that correct?
UniProtKB-KW:KW-0037  (not normal role?)

3. Ensemlb transfer from mouse
@ukemi  GPI is an essential gene?
in utero embryonic development?
mesoderm formation? 

4. learning or memory???? Ensembl transfer from RGD @slaulederkind  (the rats might be a bit tired if they can't do glycolysis so they probably can't learn so well ;)

5. "methylglyoxal biosynthetic process" (isn't methylglyoxal a toxic byproduct?)
this seems to be an alternative role of GPI in aldehyde detoxification? 

6. Lots of 'response to' by IEP
response to muscle stretch?

7. There are 5 (otherwise) identical annotations to extracellular exosome by ISO to a rat gene
from 6 different papers?

UniProtKB:Q6P6V0 | Gpi | part_of | GO:0070062    extracellular exosome | ECO:0000266   (ISO) | PMID:19056867 | RGD:1344852 | 10116 | RGD |  
( a large scale proteomics paper)

UniProtKB:Q6P6V0 | Gpi | part_of | GO:0070062    extracellular exosome | ECO:0000266   (ISO) | PMID:19199708 | RGD:1344852 | 10116 | RGD |  
(A proteomics paper)

UniProtKB:Q6P6V0 | Gpi | part_of | GO:0070062    extracellular exosome | ECO:0000266   (ISO) | PMID:20458337 | RGD:1344852 | 10116 | RGD |  
(A proteomics paper)

UniProtKB:Q6P6V0 | Gpi | part_of | GO:0070062    extracellular exosome | ECO:0000266   (ISO) | PMID:23376485 | RGD:1344852 | 10116 | RGD |  
(this appear to be a human proteomics paper, of urine, but  rat is in the "with" field)

UniProtKB:Q6P6V0 | Gpi | part_of | GO:0070062    extracellular exosome | ECO:0000266   (ISO) | PMID:23533145 | RGD:1344852 | 10116 | RGD

I don't think these HTP should be transferred to orthologs should they?
Note also that GPI is a common contaminant in protomics experiments

8. 

ciliary membrane | ECO:0000266   (ISO) | PMID:22179047 | RGD:10680
similar story to 7. The authors don't mention GPI in the abstract...

**Comment by sylvainpoux** [comment]
Removed the KW. This is kind of borderline case, but I agree it is safer to delete it. Sylvain

**Comment by pgaudet** [comment]
@hattrill @vanaukenk 
ISO should probably not propagate HTP annotations - what do you think ? 

Pascale

**Comment by ValWood** [comment]
>ISO should probably not propagate HTP annotations - what do you think ?


I think judicious transfer should be OK. However I think annotations are exchanged between rat/mouse and human via a pipeline. If this is the case it might resolve a lot of problems when the underlying datasets are changed to HTP evidence codes. Maybe @ukemi  or @slaulederkind 
can elaborate on how these are created?

**Comment by hattrill** [comment]
I think we decided that ISS transfer and it's children were ok for HTP and, as the guidelines stand, need to be manually reviewed. We should make this clear.
Automatic propagation needs an IEA.

**Comment by pgaudet** [comment]
Right - but the MGI/RDG ISO pipeline is automatic, as far as I know 
@ukemi @hdrabkin @slaulederkind - Can you comment ? 

Thanks, Pascale

**Comment by ValWood** [comment]
This has always bothered me, it should be IEA....

**Comment by slaulederkind** [comment]
Gene_association files of Gene Ontology (GO) annotations for non-rat species such as mouse, human and dog are downloaded from the GO Consortium website (http://www.geneontology.org/). Chinchilla manual GO annotations are retrieved from the RGD database. Annotations with experimental evidence codes (IDA, IMP IPI, IGI, IEP or EXP) in the originating species are automatically assigned to the orthologous rat genes with an evidence code of ISO (Inferred from Sequence Orthology; for more information about GO evidence codes, their meaning and how they are used, go to the GO Consortium evidence code documentation at http://www.geneontology.org/GO.evidence.shtml). The original reference ID for the paper from which the annotation was made in the original species is assigned as the "XREF_SOURCE" and appears in the "Original reference" column of the website display. In addition, the PMID of the original reference is included in the reference column of the GO annotation files available on RGD's ftp site (ftp://ftp.rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/ and ftp://ftp.rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/with_terms/).

**Comment by ukemi** [comment]
We are going to keep our annotations.

**Comment by ukemi** [comment]
This is actually an interesting issue with respect to complex organisms. It turns out the activity of the gene is not required until gastrulation when glycolysis is necessary for embryogenesis to proceed. I think we need to capture this kind of information.

**Comment by ValWood** [comment]
Ah OK,  but  there is no growth up to this point, just division? Then every cell will need glycolysis for growth prior to division... I wouldn't have considered this to be development, you could say the same for every housekeeping gene required for growth and division, I imagine? anyway closing.....
