### ISSUE TITLE
autophagy annotations over-inflated/ U2AF2 etc

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1839]
Hi @RLovering 

is this one correct?
https://www.uniprot.org/uniprot/P26368
PMID:24912190
This paper does not seem to be about the splicing factor U2AF2.
The abstract talks about SREBF1?

**Comment by ValWood** [comment]
Ah I see it's a screen
http://amigo.geneontology.org/amigo/reference/PMID:24912190

I wouldn't make GO annotations for all of an RNI screen, maybe just the ones the authors followed up on don't  you think. The rest is just a discovery exercise to find potential candidates?

Lots of FP's  splicing factors, ribosomal proteins, DNA polymerase etc....

**Comment by ValWood** [comment]
@deustp01 

This might be a cargo issue too?

  | U2AF2 | Splicing factor U2AF 65 kDa subunit |   | RNA export from nucleus |   | Reactome | Homo sapiens | TAS |   | rna-binding protein pthr23139 |   | Reactome:R-HSA-159101 | 20171118

  | U2AF2 | Splicing factor U2AF 65 kDa subunit |   | mRNA export from nucleus |   | Reactome | Homo sapiens | TAS

**Comment by deustp01** [comment]
Indeed, it looks like a function annotation that belongs to the transporter has propagated onto the cargo. I will check to find out whether the fix already made to keep enzyme function terms from propagating onto substrates, will also prevent propagation here. If the fix extends goes this far, then this error will go away with our next release later this month. If the fix does not extend, we will figure out how to extend it to transporters, and the error will go away after the following release in June,

**Comment by RLovering** [comment]
I have reviewed these annotations, all annotations confirmed by low throughput data have kept as IMP, annotations which are to proteins that do appear to have a relevant process/function annotation but do not have low throughput data in paper have HMP evidence, rest of annotations have been deleted. Thanks Ruth

**Comment by pgaudet** [comment]
@ValWood can this be closed ?

**Comment by ValWood** [comment]
I think so since @deustp01  is following up on the TAS ones...
