### ISSUE TITLE
Reactome, nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1841]
@deustp01 
are these correct?

Val

EIF4E | Eukaryotic translation initiation factor 4E |   | RNA export from nucleus |   | Reactome | Homo sapiens | TAS |   | eukaryotic translation initiation factor 4e related pthr11960 |   | Reactome:R-HSA-158447 | 20170406
  | EIF4E | Eukaryotic translation initiation factor 4E |   | mRNA export from nucleus |   | Reactome | Homo sapiens | TAS |   | eukaryotic translation initiation factor 4e related pthr11960 |   | Reactome:R-HSA-158484 | 20170405
  | EIF4E | Eukaryotic translation initiation factor 4E |   | mRNA export from nucleus |   | Reactome | Homo sapiens | TAS |   | eukaryotic translation initiation factor 4e related pthr11960 |   | Reactome:R-HSA-159050 | 20170406

**Comment by ValWood** [comment]
| SRSF11 | Serine/arginine-rich splicing factor 11 |   | RNA export from nucleus |   | Reactome | Homo sapiens | TAS |   | family not named pthr32343 |   | Reactome:R-HSA-159101 | 20171118
  | SRSF11 | Serine/arginine-rich splicing factor 11 |   | mRNA export from nucleus |   | Reactome | Homo sapiens | TAS

**Comment by ValWood** [comment]
U2AF1L4 | Splicing factor U2AF 26 kDa subunit |   | RNA export from nucleus |   | Reactome | Homo sapiens | TAS |   | u2 snrnp auxiliary factor, small subunit pthr12620 |   | Reactome:R-HSA-159101 | 20171118
  | U2AF1L4 | Splicing factor U2AF 26 kDa subunit |   | mRNA export from nucleus |   | Reactome | Homo sapiens | TAS

**Comment by deustp01** [comment]
Indeed, it looks like a function annotation that belongs to the transporter has propagated onto the cargo. I will check to find out whether the fix already made to keep enzyme function terms from propagating onto substrates, will also prevent propagation here. If the fix extends goes this far, then this error will go away with our next release later this month. If the fix does not extend, we will figure out how to extend it to transporters, and the error will go away after the following release in June,

**Comment by ValWood** [comment]
fixed
