### ISSUE TITLE
human TCF7L2 positive regulation of protein export from nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1842]
@RLovering 

in the abstract, says
Loss of TCF7L2 resulted in decreased GLP-1 and GIP-stimulated AKT phosphorylation, and AKT-mediated Foxo-1 phosphorylation and nuclear exclusion.
Q9NQB0 PMID:19386626

(I don't think that's necessarily regulating nucleocytoplasmic transport?)

**Comment by RLovering** [comment]
Ok this is a challenging paper PMID:19386626 

GLP-1 and GIP exert their functions through pathways involving phosphorylation of serine 473 and activation of AKT
Basal and GLP-1/GIP-stimulated levels of p-AKT were reduced in TCF7L2-depleted islets
Nuclear FOXO1 acts as a transcription factor when localized in the nucleus but it translocates to the cytoplasm when phosphorylated by AKT. 
41% decrease in p-FOXO1 by siTCF7L2
Triple-staining for Foxo1, insulin and DAPI in control islets revealed that both GLP-1- and GIP-stimulated FOXO1 nuclear exclusion (Fig. 3K, upper panel). In contrast, in TCF7L2-depleted islets FOXO1 was mainly localized in the nucleus and neither GIP nor GLP-1 had any effect on this distribution
GIP or GLP-1 treatment resulted in a 1.6- and 1.4-fold induction of the cytosolic FOXO1 portion, respectively, in the control cells but not in the TCF7L-depleted cells.

Looking at the annotations associated with TCF7L2 it has been shown to bind several transcription factors and beta-catenin as well as DNA binding. 

So I think this annotation might be ok, I can't annotate it to negative regulation of nuclear localisation, that seems weird? 

I'd appreciate your thoughts on this

Best

Ruth

**Comment by ValWood** [comment]
hmm its tricky without knowing the mechanism.
https://en.wikipedia.org/wiki/FOXO1

 It is most likely that the phosphorylation event results in FOX1 nuclear exclusion because it can't bind to something that it usually binds to when phosphorylated.

When this binding event is prevented  (or FOX1 is not phosphorylated), the protein moves out to the cytoplasm. This would be a common mechanism for regulating transcription (both positively and negatively). It seems that  most phosphorylation events (other than activation during signalling), are regulating their  target genes by regulating  their localization in some way.

 TCF7LS is more likely involved in *nuclear retention* of phosphorylated FOXO1 (which would naturally move out to the cytoplasm as many nuclear proteins do when they are not chromatin bound). So, it is only making the cargo available to be transported not regulating nucleocytoplasmic transport. That's why the  choose their words carefully and say "nuclear exclusion", rather than transport, I guess.

So if it is clear that this is upstream of the kinase   I would annotate this to 
negative regulation of "GO:0034504   protein localization to nucleus" has_input FOXO1

if it isn't totally clear that it is upstream of the kinase (if for example it could be  part of the anchoring complex),  I would use GO:0034504  directly.

v

**Comment by ValWood** [comment]
This is very similar to the MAP kinase etc example entering the nucleus. I'm increasingly convinced these should not be annotated to the regulation of nucleocytoplasmic transport...the transport is constitutive and the modification status of the protein makes it available for nucleocytoplamic shuttling if it isn't  sequestered to some organelle.

**Comment by ValWood** [comment]
Don't do anything with this one yet. We should discuss ....
@pgaudet

**Comment by pgaudet** [comment]
yes

**Comment by RLovering** [comment]
Thanks This has been changed to positive regulation of protein localization to nucleus
Ruth
