### ISSUE TITLE
SGD-> PAINT TMEM33 not  structural constituent of nuclear pore

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1843]
Is assoicated with the nuclear pore, but I don't think it is part of it, or a structural constituent.
Which ref is this?

  | TMEM33 | Transmembrane protein 33 |   | structural constituent of nuclear pore |   | GO_Central | Homo sapiens | IBA | PANTHER:PTN001398562

**Comment by ValWood** [comment]
Its from this
https://www.yeastgenome.org/reference/S000134225

The abstract says
https://www.yeastgenome.org/reference/S000134225

Here, we describe the identification and functional characterization of Pom33, a novel transmembrane protein dynamically associated with budding yeast NPCs. Pom33 becomes critical for yeast viability in the absence of a functional Nup84 complex or Ndc1 interaction network, which are two core NPC subcomplexes, and associates with the reticulon Rtn1. Moreover, POM33 loss of function impairs NPC distribution, a readout for a subset of genes required for pore biogenesis, including members of the Nup84 complex and RTN1

Its not really a part of the nuclear pore, not a structural part for sure

**Comment by ValWood** [comment]
@srengel

**Comment by ValWood** [comment]
and pom121

**Comment by suzialeksander** [comment]
Hi Val, 
I went over several papers that gloss over Pom33 as being possibly structural, but absolutely nothing to substantiate the annotation to structural constituent.  I've removed the annotation to GO:0017056 | structural constituent of nuclear pore. I think our annotation to GO:0005643 nuclear pore might even be updated with a colocalises_with, I'll have to look into it a bit.

Thanks
Suzi

**Comment by ValWood** [comment]
this is the paralog, this has "colocalizes_with"
https://www.yeastgenome.org/locus/YLR064W#go

**Comment by pgaudet** [comment]
Hi @ValWood @suzialeksander  

I removed the IBA annotation to 'structural constituent of nuclear pore' 
This is what's left; does it seem OK ? 

<img width="519" alt="image" src="https://user-images.githubusercontent.com/4782928/37137823-d51fa44e-22a7-11e8-843f-1fa3e10d15a0.png">

Thanks, Pascale

**Comment by ValWood** [comment]
My feeling is that it isn't really involved in "nuclear pore assembly" It seems to be involved in anchoring components into the nuclear membrane,  (pores, SPB's), and the ER membrane.

I  would go with a much more general 

membrane organization (the slim term)
in case  the functions are partitioned between family members in other species)
https://www.pombase.org/gene/SPBC1539.04
(pombe only has one, cerevisiae has 3)

**Comment by pgaudet** [comment]
I removed "nuclear pore assembly" and added "membrane organization". 

What about "cellular protein localization"? Isn't that odd as well?

**Comment by ValWood** [comment]
It's not incorrect but I would say that it isn't particularly useful.....

**Comment by pgaudet** [comment]
It's coming from pombase :) 
If it's not incorrect I'll leave it. 

Can this be closed? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes but in PomBase it has a target gene....localizes rtn1
without that  detail it doesn't mean so much...

In fact I am going to change that annotation to capture where rtn is localized to....
...or it might be better as a phenotype right now, I'm not sure if it is really involved in localization, or if for some indirect reason rtn1 cannot localize correctly in the mutant....

**Comment by ValWood** [comment]
This is very old, pre Canto annotation

Based on this,
Thus, our data suggest that Rtn1p, Yop1p, and Tts1p colocal- ize in a subcompartment of the ER and physically associate.
We wondered whether Rtn1p, Yop1p, and Tts1p function together in shaping ER membranes. We examined ER mor- phology with fluorescent markers for different ER compart- ments in wild-type and mutant genetic backgrounds. In rtn1D cells, both Yop1p-GFP- and Tts1p-GFP-marked mem- branes were significantly depleted from the lateral cortex (Figures 2A and 2B), suggesting diminishment of peripheral tubules. Tts1p and Yop1p in rtn1D cells were still clearly excluded from the cisternal compartment marked by Ost1p (Figure S2A). Consistent with a conversion to more cisternal ER, Ost1p in rtn1D cells localized extensively along the lateral cortex, unlike its typical intermittent pattern in wild-type cells (Figure S1A).
Similarly, Rtn1p-GFP showed decreased occupancy at the cell cortex in both yop1D and tts1D cells, and its occupancy was further diminished in the double yop1Dtts1D mutant (Figure 2C).

We would only annotate these localization dependencies as phenotypes. It is likely that loss of interactions results in de-localization. It shouldn't be a GO annotation.....

**Comment by pgaudet** [comment]
I removed the nuclear pore annotation - are you saying that *all* annotations should be removed ?

**Comment by ValWood** [comment]
nuclear pore is OK, but should probably have "contributes to"

"cellular protein localization" will disappear from PomBase.

I think "nuclear pore assembly"  will also probably disappear @suzialeksander  is that correct?

"membrane organization" is possible (from current PomBase annotation)

**Comment by pgaudet** [comment]
> nuclear pore is OK, but should probably have "contributes to"

I added back the annotation with colocalizes with. 

Anything else ?

**Comment by ValWood** [comment]
nope...not for now ;)

**Comment by pgaudet** [comment]
thanks :)

**Comment by ValWood** [comment]
For the record I re-curated this.
It now has "modern" curation , and no mention of protein localization
http://curation.pombase.org/pombe/curs/c166fc9a9dd60e8d
The localization of some proteins is affected in the mutants, but this is a consequence of 
either a) not binding normal binding partners or b) abnormal reticular ER formation.
So, in conclusion,  "tetra spanning  protein" possibly the best thing that could be transferred  is "membrane organization".
