### ISSUE TITLE
	InterPro:IPR034978 not nucleocytoplamic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1848]
will double check

**Comment by deustp01** [comment]
Indeed, it looks like a function annotation that belongs to the transporter has propagated onto the cargo. I will check to find out whether the fix already made to keep enzyme function terms from propagating onto substrates, will also prevent propagation here. If the fix extends goes this far, then this error will go away with our next release later this month. If the fix does not extend, we will figure out how to extend it to transporters, and the error will go away after the following release in June,

**Comment by ValWood** [comment]
yep, It is a nucleocytoplasmic shuttling protein  according to the description
https://www.ebi.ac.uk/interpro/entry/IPR034978
That's just describing the location, not an involvement in transport.

**Comment by asangrador** [comment]
Thanks for pointing out this mistake, I have removed the term.
