### ISSUE TITLE
human SET not nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1851]
https://www.ncbi.nlm.nih.gov/pubmed/11555662

It is  *in* the nucleus?

SET | Protein SET |   | nucleocytoplasmic transport |   | UniProt | Homo sapiens | NAS

very old ...2004

**Comment by ggeorghiou** [comment]
Indeed, a very old annotation and a NAS statement. Could have been a man down at the pub who told the author this information! Consider it deleted.

**Comment by ValWood** [comment]
;) Lot's of good science happens in the pub too though!
