### ISSUE TITLE
human PARP10 	negative regulation of protein import into nucleus, translocation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1855]
This doesn't seem correct?

PMID:23575687

tagging @vanaukenk  as it seems  likely to be a LEGO model?

can you assign to the correct person?

**Comment by pgaudet** [comment]
No, it's not a GO-CAM model. 

The annotation is redundant with 'negative regulation of NF-kappaB transcription factor activity' from the same paper. @ggeorghiou can you please have a look and delete if you agree? 

Thanks, Pascale

**Comment by ggeorghiou** [comment]
After reading the paper, I believe the annotation was meant to show that this was more to the mechanism of how it negatively regulates NF-kappB transciption activity. It is redundant, so I will delete it.
