### ISSUE TITLE
human /cerevisiae BUD13 not nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1857]
@srengel 
BUD13
SGD 
However, they are required for efficient splicing in vitro and in vivo. Furthermore, inactivation of this complex causes pre-mRNA leakage from the nucleus. The corresponding complex was named pre-mRNA REtention and Splicing (RES). 

and
human
@RLovering 
BUD13 | BUD13 homolog |   | mRNA export from nucleus |   | BHF-UCL | Homo sapiens | ISS | UniProtKB:P46947 | family not named pthr31809 |   | PMID:15565172

**Comment by suzialeksander** [comment]
I agree.  SGD annotation has been removed for GO:0006406 mRNA export from nucleus.  
Thanks!
Suzi

**Comment by ValWood** [comment]
thanks Suzi!

**Comment by RLovering** [comment]
BHFL annotation removed too :)
