### ISSUE TITLE
human PINC annotation to delete, not nucleocytoplamsic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1859]
I'm not looking into these, but they look incorrect

O60318 MCM3AP | Germinal-center associated nuclear protein |   | protein import into nucleus |   | PINC | Homo sapiens | TAS |   | 80 kda mcm3-associated protein pthr12436 |   | PMID:9712829

PDIA3 | Protein disulfide-isomerase A3 |   | protein import into nucleus |   | PINC | Homo sapiens | TAS |   | protein disulfide isomerase pthr18929 |   | PMID:7487104 | 20030904

**Comment by ValWood** [comment]
@pgaudet  can you delete these?

**Comment by pgaudet** [comment]
> MCM3AP
The paper states that " Map80 may not participate in the import of MCM3 but stabilize the nuclear localization of MCM3 by interacting with other karyopheric materials, such as chromatin or other karyopheric protein" 
-> How about if I move the annotation to 'regulation of protein localization to nucleus'? 
It definitely seem to have some role in nucleocytoplasmic transport: https://europepmc.org/articles/PMC3378895

**Comment by pgaudet** [comment]
PDIA3
Deleted 
- protein import into nucleus 
- protein retention in ER lumen
- signal transduction

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood please next time include the AC or ID.

**Comment by ValWood** [comment]
Ah right MCM3AP is TREX, that does have a role in nucleocytoplasmic transport (it might be indirect but it is traditionally annotated to this term). However it isn't import, it's export.

re
@ValWood please next time include the AC or ID.
Will do I cut and pasted the annotation from AmiGO, I thought the ID was in the annotation!

**Comment by pgaudet** [comment]
Did you look at the paper ? https://www.ncbi.nlm.nih.gov/pubmed/?term=9712829
MCM3AP seems to be required for the nuclear localization of a NLS-containing protein; could it have multiple roles ?

**Comment by ValWood** [comment]
DNA binding from this paper probably needs deleting too?

**Comment by ValWood** [comment]
A more recent paper (not used for GO)
https://www.ncbi.nlm.nih.gov/pubmed/22307388

**Comment by pgaudet** [comment]
Nucleic acid binding comes from InterPro @asangrador 

Thanks, Pascale

**Comment by asangrador** [comment]
Are you referring to a match to IPR035979? This entry is annotated to nucleic acid binding, but I don't think it is wrong. It represents a RRM domain in the  multidomain protein GANP, not present  in the shorter isoform GANP/MCM3AP or in pombe SAC3. And GANP associates with cromatin according to PMID:23652018.

**Comment by ValWood** [comment]
1. The DNA binding is from Prot inc (TAS), that should go. At least from this paper.

2. It most likely does bind RNA (TREX associates with RNA polymerase, and RNAs).

3. The proposed "acetyl transferase domain" appears to be not functionally relevant. Lots of authors refer to it, but I can't see anything which confirms this activity,  and the origianl authors 
see also this ticket.
https://github.com/geneontology/go-annotation/issues/1861

Later the authors say in another paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3037533/
more recent work from the same lab downplays the acetyase activity inthe MCM3AP fragment
Furthermore, because GANP also contains a region identical to MCM3AP (MCM3 acetylating protein), that interacts with and weakly acetylates MCM3,31,32 these proteins have often been confused in databases and the literature.

The original alignment with GNAT looks spurious

**Comment by ValWood** [comment]
related
https://github.com/geneontology/go-annotation/issues/1861

**Comment by pgaudet** [comment]
Hi @ValWood 
I deleted the DNA binding annotation. 

Thanks,Pascale

**Comment by pgaudet** [comment]
and the nuclear import.
