### ISSUE TITLE
Something has lopped the !gaf-version header off a bunch of GAFs

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-annotation#1860]
Our import pipeline failed this morning when it tried to process the following GAFs, with the error "unsupported or unrecognised file format". When I took a closer look, I saw that they had all lost their "!gaf-version: 2.1" header line.

ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.gramene_oryza.gz
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Pfalciparum.gz
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Lmajor.gz
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.jcvi.gz
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.PAMGO_Mgrisea.gz
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Tbrucei.gz
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.zfin.gz
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.rgd.gz

**Comment by cmungall** [comment]
spec for @dougli1sqrd 

```
!gaf-version: 2.1
!
!Generated from [ORIG] by GO Central on YYYY-MM-DD
!
![other metadata from source yaml here]
!
!original header below:
[copy original]
```

**Comment by kltm** [comment]
Same issue, these upstreams do not seem to have  headers in he GAF and would need repair:
     gene_association.GeneDB_Lmajor.gz
      gene_association.GeneDB_Pfalciparum.gz
      gene_association.GeneDB_Tbrucei.gz
      gene_association.PAMGO_Atumefaciens.gz
      gene_association.PAMGO_Ddadantii.gz
      gene_association.PAMGO_Mgrisea.gz
      gene_association.PAMGO_Oomycetes.gz
      gene_association.sgn.gz

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/153

**Comment by kltm** [comment]
Files coming in on skyhook now look good.

**Comment by kltm** [comment]
Superset of missing (proper) version info:
gene_association.PAMGO_Atumefaciens.gz
gene_association.GeneDB_Pfalciparum.gz
gene_association.GeneDB_Lmajor.gz
gene_association.GeneDB_Tbrucei.gz
gene_association.PAMGO_Ddadantii.gz
gene_association.PAMGO_Mgrisea.gz
gene_association.PAMGO_Oomycetes.gz
gene_association.gramene_oryza.gz
gene_association.jcvi.gz
gene_association.rgd.gz
gene_association.sgn.gz
gene_association.zfin.gz

**Comment by kltm** [comment]
All checks look good. Re-running release pipeline.

**Comment by kltm** [comment]
@tonysawfordebi Given a little time to percolate through the internets and internal systems, I believe that the files have been fixed. Please let us know if there are still issues.
