### ISSUE TITLE
human MCM3AP SPKW check

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1861]
These look strange:
~immune system process
for something which just supports cell type specific proliferation (possibly through replication? interacts with mcm3?)~

~I still think this looks strange, its likely an indirect of TREX function.~

**Comment by ValWood** [comment]
Also 
http://www.uniprot.org/keywords/KW-0012
transferase activity, transferring acyl groups

doesn't appear to be a catalytic activity of any sort?
http://pfam.xfam.org/protein/O60318

**Comment by sylvainpoux** [comment]
There are papers on acetyltransferase activity: PubMed=11258703, PubMed=22307388;

And the protein is involved in immunoglobulin V-region diversification  (PubMed=21388430)

For me the annotation is correct

**Comment by ValWood** [comment]
now there is the useful GO annotation for MCM3AP!
https://www.ncbi.nlm.nih.gov/pubmed/11258703

I don't see any acetyltransferase EXP in this paper
PubMed=22307388

**Comment by ValWood** [comment]
I'll see if Pfam can build this into acetyltransferase clan

**Comment by ValWood** [comment]
Recent reviews do not mention this activity at all
Germinal Center B-Cell-Associated Nuclear Protein (GANP) Involved in RNA Metabolism for B Cell Maturation.

Sakaguchi N, Maeda K.

Adv Immunol. 2016;131:135-86. doi: 10.1016/bs.ai.2016.02.003. Epub 2016 Mar 29. Review.

PMID: 27235683

**Comment by sylvainpoux** [comment]
Val, 

we are happy to correct clear errors, but we don't have enough resources to look of these cases in detail: the question was whether the annotation is correct, and it is based on these publications. 

If this/these protein(s) are of specific importance for your research we can assign a curator to it, otherwise, it will not be possible

**Comment by ValWood** [comment]
OK, this is pretty confusing, but I'm pretty convinced that this is not a GNAt family acetyltransferase. The similarity is spurious. I would also question whether it has acetyl transferase activity physiologically...

It is the clear ortholog of  cerevisiae/pombe  Trex subunit 
 Sac3
http://pfam.xfam.org/family/PF03399

it has a paralog in human SACD1 (this is not annotated as an acetyltransferase)

**Comment by ValWood** [comment]
It would be really helpful if GO annotations were made to the primary papers rather than Keywords assigned in these cases.

**Comment by ValWood** [comment]
Yes it is important for my research that human annotation is correct.

**Comment by ValWood** [comment]
As part of QC there needs to be a robust mechanism for purging outdated incorrect annotation.

**Comment by sylvainpoux** [comment]
I perfectly agree, but we also have to prioritize things. You send many requests, but in some cases, you don't look into enough detail before sending them.

I have found different papers reporting this acetyltransferase activity (PMID:12226073, PMID:11258703). I cannot tell if it is really true, because I would need to go into more detail, but I notice that the human protein is much longer than the yeast ones. It also contains an InterPro domain not present in yeast. I don't know if this can explain the difference.

Regarding the role of the protein in immune system, it is required for antibody maturation, so I would not say that this annotation is incorrect.

Again, if it is priority for you, send an official request to UniProt, we will of course handle this.

**Comment by ValWood** [comment]
PMID:12226073 uses the mutant that PMID:11258703 previously reported as an acetyltransferase. There is no assay in this paper, only genetics.

There is only one paper with an  'assay'
https://www.ncbi.nlm.nih.gov/pubmed/11258703

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3037533/
more recent work from the same lab downplays the acetyase activity inthe MCM3AP fragment

Furthermore, because GANP also contains a region identical to MCM3AP (MCM3 acetylating protein), that interacts with and weakly acetylates MCM3,31,32 these proteins have often been confused in databases and the literature. The nucleotide sequence for MCM3AP is completely contained in the 3′ region of GANP, suggesting that MCM3AP is a splice variant33 and, furthermore, MCM3AP can be transcribed independently of GANP. Consequently, they should be referred to as independent, overlapping genes and not described interchangeably as at present in databases.

Recent work has identified GANP as an integral component of the mammalian bulk mRNA export machinery.34 Separate domains of GANP show local homology to FG-nucleoporins, the yeast mRNA export factor Sac3p and the mammalian MCM3 acetyltransferase. GANP therefore combines features from different components of the mRNA export machinery and NPCs, and so has the potential to coordinate key steps in the gene expression pathway. In support of this hypothesis, GANP is localized predominantly to the nuclear face of the nuclear envelope, albeit combined with weaker staining of the nuclear interior.3

**Comment by ValWood** [comment]
will close when fixed

**Comment by sylvainpoux** [comment]
Could you please send an official UniProt request mentioning the PMID:21326821 paper? We need to follow the user request procedure for a question of tracking
Thanks

**Comment by ValWood** [comment]
I sen't the link to this ticket to the helpdesk?

**Comment by sylvainpoux** [comment]
I'm not sure it works, and not all UniProt curators are familiar with GitHub. 
A quick summary of 2-3 sentences with the text of the paper saying that acetyltransferase activity is dubious (PMID:21326821) would be great
Thanks

**Comment by ValWood** [comment]
That is what this ticket says. They will need to look at the ticket  anyway.

**Comment by sylvainpoux** [comment]
thanks

**Comment by ValWood** [comment]
I'll pass to HGNC
@sartweedie
but it probably needs to be fixed at Havana and the GO annotation can be addressed after that.

**Comment by ValWood** [comment]
@sar
