### ISSUE TITLE
human glycosylation annotations over-inflated

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1865]
A lot of these appear to be "glycosylated" not involved in glycosylation

first one I looked at: a cholesterol transporter
 https://www.uniprot.org/uniprot/O15118 IDA
https://www.uniprot.org/citations/10821832

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprot/P07306 TAS via reactome (receptor for exocytosed glycoprotein)

**Comment by deustp01** [comment]
Those TAS from us should go away with our next release at the end of the month.

**Comment by ValWood** [comment]
Brilliant. I'll close this one. I noticed some others  which might be  slightly different reasons. so I will open tickets for these later......But  am I OK to assume that any resulting in "target of process annotated to process" are fixed for all processes?

v

**Comment by deustp01** [comment]
"OK to assume that any resulting in "target of process annotated to process" are fixed for all processes?"

The discrepancy arises at the level of individual reactions (molecular functions) and propagates to the pathways (processes) that those reactions are parts of. Where the reaction involves catalytic activity (GO:0003824) and its children or transporter activity (GO:0005215) and its children, the discrepancies should be fixed. In the cases of proteins and complexes traversing the nuclear pore or proteins associated with intraqcellular vesicles moving to the cell membrane and extracellular space, the fixes will take longer.

**Comment by ValWood** [comment]
reopening as there are non -reatcome ones above.

**Comment by ValWood** [comment]
From MGI
@ukemi @hdrabkin  please assign appropriate person

MGI

Q9BQQ3	GORS1_HUMAN	Golgi reassembly-stacking protein 1
These findings substantiate the role of GRASP65 in continuity of the cis Golgi network required for proper glycosylation, while showing that neither this continuity nor GRASP65 itself are essential for the viability of a complex organism.

ISS from mouse
http://www.uniprot.org/citations/24795147
Seems to be a phenotype due to Golsi disruption rather than an effect on glycosylation

Q15643	TRIPB_HUMAN	Thyroid receptor-interacting protei..
also seems to be from Golgi abnormalities
via UniProtKB:E9Q512  (mouse)
https://www.ncbi.nlm.nih.gov/pubmed/20089971?dopt=Abstract

Q86UW2	OSTB_HUMAN	Organic solute transporter subunit ...
via mouse
UniProtKB:Q80WK2 http://europepmc.org/articles/PMC3375545

Formation of the transporter complex is also coupled to post-translational modifications of Ostα; i.e. stable interaction between the subunits is required for progression through the biosynthetic-secretory pathway and to generate a glycosylated form of Ostα (5, 9, 10). Thus, the glycosylation status of Ostα can be utilized as an index of interaction between the two subunits.

**Comment by ValWood** [comment]
UniProt @ggeorghiou 

- [ ]  *glycosylated*
P60604	UB2G2_HUMAN	Ubiquitin-conjugating enzyme E2 G2
P55072	TERA_HUMAN	Transitional endoplasmic reticulum ... 
Q86TM6	SYVN1_HUMAN	E3 ubiquitin-protein ligase synovio...  
protein N-linked glycosylation via asparagine IMP, PMID:22607976 appears to be *glycosylated*

- [ ]  *glycosylated*
Q12893	TM115_HUMAN	Transmembrane protein 115    

protein glycosylation  PMID:24806965 appears to be *glycosylated* (uniprot function line also needs updating)

**Comment by ukemi** [comment]
@vanaukenk and @pgaudet   This is a nice edge case for the new qualifiers and might be worth discussing on a call. You need a good Golgi apparatus to get proper glycosylation, but if we make the cut off of the glycosylation being the enzymatic steps, then the organization of the Golgi would be upstream of it. In my opinion it is still very important to capture this kind of information in some way. The last case is even more interesting. The complex between the beta subunit and the alpha subunit is required for the alpha subunit to be glycosylated. The beta is annotated to positive regulation, but if we make the cut off being the enzymatic steps, it would act upstream as well.

**Comment by ggeorghiou** [comment]
All of these annotations have been deleted or updated accordingly. Closing this ticket.
