### ISSUE TITLE
human "cofactor metabolism" annotation over-inflated

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1868]
A lot of these appear to come from  annotations of lots of "nucleoporins" to "regulation of glycolytic process"

e.g.

http://www.uniprot.org/uniprot/O75694
A8CG34
O15504
Q8NFH3
Q8NFH4
Q8NFH5
etc

I'm not sure if this one is covered by the pending fixes?

v

@deustp01

**Comment by ValWood** [comment]
At the same time, these all appear to have
mitotic nuclear envelope disassembly: : Reactome
protein sumoylation Source: Reactome
regulation of cellular response to heat Source: Reactome
regulation of gene silencing by miRNA Source: Reactome

**Comment by deustp01** [comment]
Val's first comment - this looks like a valid annotation to me. An important part of regulating glucose metabolism in mammals is moving a glucokinase from the cytosol where it is active to the nucleus where it is not, and this movement is mediated by the nuclear pore complex, each component of which plays its normal role, whateer than is (so we are missing some distinctions between contributes-to and directly-involved).

Val's second comment - to the extent I can track those down, it looks like they are all results of the now-fixed failure to distinguish cargo from transported so those annotations should go away.

**Comment by ValWood** [comment]
But are the nuclear pore proteins really "regulating glycolysis" ?
The thing which regulates the moving, is the regulator of glycolysis, if anything, not the nuclear pore components?

**Comment by deustp01** [comment]
Two practical choices here.
1) Spend half a day digging through all the details of our "Regulation of Glucokinase by Glucokinase Regulatory Protein" (https://reactome.org/PathwayBrowser/#/R-HSA-70326&SEL=R-HSA-170822&) to find the exact sub-detail within it that fits the narrow GO view of "regulation", time that neither I or any of my colleagues have right now given our own production, maintenance, and grant-writing benchmarks that need to be satisfied, or
2) Just delete the "regulation" GO term from the pathway. That hides some good biological annotation but preserves the integrity of the slim.
Preferences?

**Comment by ValWood** [comment]
@pgaudet ? @ukemi ?
Are the nuclear pore proteins are really regulating "glycolytic process"
If not, is deletion the best option (there are quite a lot).

**Comment by ValWood** [comment]
closing since "cofactor metabolism/metabolic process" is obsolete
