### ISSUE TITLE
how ontology issues over-inflation of annotation affects GO analyses

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1869]
This table  (for a paper on unknowns) shows changes in pombe slim over time:

the orange fluctuations are due to stricter annotation criteria, the peach ones due to ontology changes. There are lots of ontology fixes that are not picked up by this snapshot, because they are  added and fixed  between the snapshots.  Slim totals  have been quite stable for the past 6-12 months apart from an occasional ontology glitch.

![pombe sheet1](https://user-images.githubusercontent.com/7359272/37303630-f448893a-2626-11e8-9bd6-d5a5c12f38a7.jpg)

This figure shows  the "cellular process slim" totals for pombe, cerevisiae and human. This isn't part of the unknowns paper, I did it out of interest.  The green shading are cellular processes where the gene products are (largely) conserved 1:1:1. The blue are where I expected the human numbers to be higher (lots of on to many). Some  term totals  are a  lot higher for human than expected. I have had a glance through some  of the lists and identified some obvious errors. There are a lot more.

Personally I think it is critical that the annotation errors are addressed because their presence will obscure true enrichments and make GO unusable for human analysis.

![comparison sheet1](https://user-images.githubusercontent.com/7359272/37304663-2443a9aa-262a-11e8-9aba-e827fe1c0adf.jpg)

Overinflated numbers appear to be largely due to 2 recurring  annotations error types 
i) annotations of target genes to a process and 
ii) experimental readouts.

**Comment by vanaukenk** [comment]
@ValWood 
This is really interesting.  In terms of actionable items, I see there are already tickets to review some of the human annotations, but it would be nice to generate the second table for more species and have it available as an ongoing report that curators could systematically check.

**Comment by ValWood** [comment]
I was thinking that @vanaukenk . I was going to tag you  because I remembered you asking about evidence for ontology changes affecting analysis.

It's very easy to do....with GO term mapper  you can import legacy gafs to look at  historical changes...
I waited  until now to share because the  pombe slim should not  have so many large fluctuations from now on (there will be increases over time, but the ontology is much more stable for slim totals, at least for cellular processes). 

It's really nice  also to have a slim constantly available on our web site
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms
it's one of our most highly accessed pages.
I makes sanity checking specific process lists very easy.....

**Comment by ValWood** [comment]
I can add other species  if I get the protein coding  gene lists. That is the trickiest part!

**Comment by pgaudet** [comment]
ACTION ITEM NYC 2018 GOC: Create report based on species slims

**Comment by ValWood** [comment]
Should this be closed? The tool accompanying Marcs paper will help a lot to interrogate  slim set differences.
