### ISSUE TITLE
human- overinflation of numbers to DNA replication, lots of experimental readout

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1870]
I took advice on this from a replication researcher and he agrees:

"I agree completely - these all look like they effect proliferation, with replication just being used as a readout for this."

http://www.uniprot.org/uniprot/O15520 from http://www.uniprot.org/citations/17471512 readout?
http://www.uniprot.org/uniprot/P01127 from http://www.uniprot.org/citations/2836953 readout?
http://www.uniprot.org/citations/9482941 9482941 readout?

~http://www.uniprot.org/uniprot/P08069 positive regulation of DNA replication Source: BHF-UCL readout?~ fixed
~http://www.uniprot.org/uniprot/P22003 http://www.uniprot.org/citations/15516325 BHF-UCL readout?~ fixed

**Comment by ValWood** [comment]
IGF1 http://www.uniprot.org/uniprot/P05019
http://www.uniprot.org/citations/9722506 IDA BHF

http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P01133
https://www.uniprot.org/citations/9482941 TAS protInc

I'm sure there are lots more of these so the list of "DNA replication" annotation should be reviewed.

**Comment by vanaukenk** [comment]
@ValWood 

It's really important that we keep track of curatorial efforts put into annotation review.  Can you follow the SOP we've been trying to use by creating corresponding spreadsheets in the Annotation Review folder on GO's Google drive:
https://drive.google.com/drive/folders/1FDfp4yXlLZjrcB0NIbsAgUukDWDwhJe_

There is also an Annotation Review Guidelines doc in that folder.

Let me know if you have any questions.  Thx.

**Comment by RLovering** [comment]
Hi Val

BHF ones and PINC updated/deleted. I have also looked at all the UCL annotations to these terms and updated/deleted the majority of them

Ruth

**Comment by ValWood** [comment]
Brillliant, thanks!

**Comment by ValWood** [comment]
A couple more (these were from Matrix intersection of "replication" with "proliferation"

- [ ] mouse NASP http://www.uniprot.org/citations/16728391 should be nucleosome assembly?
- [ ] mouse E4F1 http://www.uniprot.org/uniprot/Q8CCE9 DNA replication IMP 
- http://www.uniprot.org/citations/15226446
- [ ] human ACHE DNA  GO:0006260http://www.uniprot.org/uniprot/P22303 TAS from http://www.uniprot.org/citations/11283752

**Comment by ValWood** [comment]
@ukemi

**Comment by ValWood** [comment]
I just checked the ones that were not crossed out and these were no longer annotated to DNA replication, so closing
