### ISSUE TITLE
Associate more specific MF GO term to InterPro IPR000297?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#1872]
Hi,

The InterPro domain "Peptidyl-prolyl cis-trans isomerase, PpiC-type" (IPR000297) is currently only associated to a very high level GO MF term - "isomerase activity" (GO:0016853).

From the InterPro definition, and specifically the reference to EC:5.2.1.8, it seems a more specific GO term could be associated?
E.g. peptidyl-prolyl cis-trans isomerase activity (GO:0003755)

**Comment by sjm41** [comment]
Tagging @hattrill

**Comment by asangrador** [comment]
You are right; I have changed the annotation to peptidyl-prolyl cis-trans isomerase activity (GO:0003755).

**Comment by sjm41** [comment]
Great, thanks!
