### ISSUE TITLE
pre-import PAINT checks, PAINT IGNORING TAXON RESTRICTIONS

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1873]
this batch should be taxonomically restricted:

~fhl1	forkhead transcription factor Fhl1		cell differentiation		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN001371846			PAINT_REF:11829	20170427~
see https://github.com/geneontology/go-annotation/issues/1873
~fhl1	forkhead transcription factor Fhl1		anatomical structure morphogenesis		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN001371846~
see https://github.com/geneontology/go-annotation/issues/1873

- [ ]  map1	MADS-box transcription factor Map1		multicellular organism development		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000235373			PAINT_REF:11945	20170427

MULTICELLULAR ORGANISM DEVELOPMENT  IS TAXONOMICALLY RESTRICTED FOR YEAST

- [ ] 	nup61	nucleoporin Nup61		positive regulation of mitotic centrosome separation		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000566604	
(I would question this annotation more generally anyway)

THIS TERM *SHOULD* BE TAXONOMICALLY RESTICTED ITS PARENTS ARE
https://github.com/geneontology/go-ontology/issues/15685

- [ ] 	rho4	Rho family GTPase Rho4		regulation of cell migration		GO_Central	Schizosaccharomyces pombe

THIS TERM *SHOULD* BE TAXONOMICALLY RESTICTED ITS PARENTS ARE

- [ ] 	shk2	PAK-related kinase Shk2		cell migration		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000686326	

CELL MIGRATION IS ALREADY TAXONOMICALLY RESTRICTED, IGNORED BY PAINT???
GO:0040011 | locomotion | Never in Taxon | 451864

- [ ] spn1	mitotic septin Spn1		cilium assembly		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000430231			PAINT_REF:18884	20170427

CILLIUM ASSEMBLY IS ALREADY TAXONOMICALLY RESTRICTED, IGNORED BY PAINT???
GO:0060271 | cilium assembly | Never in Taxon | 4890 | Ascomycota

**Comment by ValWood** [comment]
- [ ] 	tra2	NuA4 complex phosphatidylinositol pseudokinase complex subunit Tra2		kinase activity		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000124197

(Tra2 in NuA4 is a pseudo-kinase, I think this is a general across species thing but I'm not sure)

**Comment by ValWood** [comment]
we wouldn't make these:

- [ ] 	nup211	nucleoporin nup211		mitotic spindle assembly checkpoint		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN001052033

this one is only about translocation of a checkpiutn protein, it isn't really part of the checkpoint

**Comment by ValWood** [comment]
These look incorrect:

	tos4	transcription factor, FHA domain protein Tos4 (predicted)		translation		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000559990	

(Is a DNA binding transcription factor)

**Comment by ValWood** [comment]
not enough information to make these inferences (transport inferences are dangerous across species, but to the best of our knowledge this is a sulfate transporter)

	SPCC320.05	sulfate transmembrane transporter (predicted)		regulation of intracellular pH		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
	SPCC320.05	sulfate transmembrane transporter (predicted)		bicarbonate transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
	SPCC320.05	sulfate transmembrane transporter (predicted)		chloride transmembrane transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
	SPCC320.05	sulfate transmembrane transporter (predicted)		oxalate transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047

**Comment by ValWood** [comment]
- [ ] 
	rmt3	type I ribosomal protein arginine N-methyltransferase Rmt3		histone arginine methylation		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000109455			PAINT_REF:11006	20170427
	rmt3	type I ribosomal protein arginine N-methyltransferase Rmt3		histone-arginine N-methyltransferase activity		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000109455

I don't think that histone is the physiological substrate here?
This is characterised in pombe as colocalizing with and methylating ribosomes
see
https://www.pombase.org/gene/SPBC8D2.10c

**Comment by ValWood** [comment]
not enough information to make these inferences (transport inferences are dangerous across species, but to the best of our knowledge this is a sulfate transporter)

SPCC320.05	sulfate transmembrane transporter (predicted)		regulation of intracellular pH		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
SPCC320.05	sulfate transmembrane transporter (predicted)		bicarbonate transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
SPCC320.05	sulfate transmembrane transporter (predicted)		chloride transmembrane transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
SPCC320.05	sulfate transmembrane transporter (predicted)		oxalate transport

**Comment by cmungall** [comment]
@ValWood - are all of these for the attention of the PAINT team (assigning @huaiyumi for now)? Are some for new TCs in GO?

**Comment by selewis** [comment]
Does this mean that the taxon checking code was removed from PAINT? It use to be built-in.

**Comment by ValWood** [comment]
I guess  some will be for  checking the PAINT annotation.

I think ssn6 is a panther family issue?

The taxon checks don't appear to be working. I think this might be a general GO issue now I think about it. Let me know if you want these 2 split out into different tickets.

**Comment by ValWood** [comment]
- [ ]     tra2 NuA4 complex phosphatidylinositol pseudokinase complex subunit Tra2 kinase activity GO_Central Schizosaccharomyces pombe IBA PANTHER:PTN000124197

(Tra2 in NuA4 is a pseudo-kinase, I think this is a general across species thing but I'm not sure)

**Comment by ValWood** [comment]
we wouldn't make these:

- [ ]     nup211 nucleoporin nup211 mitotic spindle assembly checkpoint GO_Central Schizosaccharomyces pombe IBA PANTHER:PTN001052033

this one is only about translocation of a checkpoint protein, it isn't really part of the checkpoint

- [ ] 	nup61	nucleoporin Nup61		spindle organization		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000566604	
see above

- [ ] 	npp106	nucleoporin Npp106		nuclear pore complex assembly		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000131983			PAINT_REF:11225

not assembly, just a phenotype

**Comment by ValWood** [comment]
-  [ ] sec21	coatomer gamma subunit Sec21 (predicted)		organelle transport along microtubule		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000029440

Golgi positioning isn't microtubule dependent in fission yeast (possibly not in yeast, not sure)

**Comment by ValWood** [comment]
positive and negitive annotation from the sme family

- [ ] 	arg6	acetylglutamate synthase Arg6		acetylglutamate kinase activity		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000597373			PAINT_REF:23342	20170427
- [ ] 	arg6	acetylglutamate synthase Arg6	NOT	acetylglutamate kinase activity		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000597386			PAINT_REF:23342	20170427

it isn't acetylglutamate kinase activity, it's acetyl-CoA:L-glutamate N-acetyltransferase activity
(this might be becaue its a multi domain protein in  higher eukaryotes?)

**Comment by ValWood** [comment]
incorrect annotations
See
https://github.com/geneontology/go-annotation/issues/31
for some history

- [ ] SPAC11E3.12	mitochondrial thioredoxin family protein		mitochondrial electron transport, NADH to ubiquinone		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000042666			PAINT_REF:10371

- [ ] SPAC11E3.12	mitochondrial thioredoxin family protein		respiratory electron transport chain		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000042665			PAINT_REF:10371	20170427

- [ ] SPAC11E3.12	mitochondrial thioredoxin family protein		NADH dehydrogenase (ubiquinone) activity		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000042665			PAINT_REF:10371	20170427

**Comment by ValWood** [comment]
- [ ] sil1	nucleotide exchange factor for the ER lumenal Hsp70 chaperone, Sil1 (predicted)		cytoplasmic translation		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN001062524			PAINT_REF:19316	20170427

is involved in 

SRP-dependent cotranslational protein targeting to membrane, translocation

**Comment by ValWood** [comment]
- [ ] 	snd302	SRP-independent ER targeting protein Snd3b (predicted)		phosphate ion transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN001999322			PAINT_REF:28112	20170427

see InterPRo summary
http://www.ebi.ac.uk/interpro/entry/IPR012098

the phosphate transport is from some old 1996 genetics, indirect
https://www.yeastgenome.org/reference/S000051002

**Comment by ValWood** [comment]
I scanned the first 1000  they look pretty good!)
Once these are fixed I'll try a real import against our filtering (most will hopefully be duplicates so they  will be filtered from PomBase as redundant).

It would be really helpful to suppress redundant annotation more generally .....

**Comment by ValWood** [comment]
some of these will need to be addressed by PAINT curators.

**Comment by ValWood** [comment]
We can't import the PAINT annotations into PomBase until these are fixed. However, the pombe annotations are now in AMiGO. Because they  have the incorrect gene ID in the db object symbol column they are also causing problems for downstream softwares (see helpdesk ticket).

**Comment by selewis** [comment]
Right, I forwarded your message to Anushya and Huaiyu to draw their
attention to this.

**Comment by mah11** [comment]
> Taxon constraints should go in the go-ontology tracker.

Is that applicable to these reports? As I understand it, the taxon constraints are already present in the ontology, but annotations that should be flagged or blocked are getting through. Is that still an ontology issue?

**Comment by ValWood** [comment]
yes I think in many cases the taxon restrictions are present but the taxon restrictions are not in place. I  have asked about this in multiple tickets.
@cmungall ?

anyway I'll start by separating this list out.

**Comment by ValWood** [comment]
ticket about taxon checks (and other QC checks)
https://github.com/geneontology/go-annotation/issues/1928

**Comment by ValWood** [comment]
There are 2 issues really......

1 . Why aren't the taxon restrictions being included more generally (i.e when a gene products is  annotated to a taxonomically restricted term, why isn't it flagged in the logs.

but 
2. Why is PAINT ignoring the taxon restrictions and making annotations to them
For example, pombe and cerevisiae should not get any annotation via  PAINT to 
"multicellular organism development"

Both of these problems need  resolving.  The taxon checks not working issue is already reported to @cmungall 

The entries in this ticket related to taxon checks is about PAINT  ignoring them....

**Comment by ValWood** [comment]
It seems to be a mixture.
I renamed this ticket
pre-import PAINT checks, PAINT IGNORING TAXON RESTRICTIONS

I'll move any queries that do not appear to be  this particular problem to  separate tickets

**Comment by ValWood** [comment]
If it helps, taxon restrictions are being ignored for everything, and have been for a while. Not just for PAINT  (although I had assumed that there would be an extra upstream step to prevent PAINT annotations being created if a taxon restriction exists?)

**Comment by ValWood** [comment]
GO:0060271 | cilium assembly | Never in Taxon | 4890 | Ascomycota
we get 8 pombe genes annotated to this term

**Comment by selewis** [comment]
There ought  to be (and indeed use to be) at least two built-in checks for passing the taxon constraints.
1. Built-in to PAINT itself so that the annotations aren't created in the first place. 3 possible things could happen at this stage. 1.a code-rot resulting in this functionality being lost. -- @huaiyumi would you please check that. -- 1.b older PAINT annotations prior to current checks, but these could be caught when the PAINT gafs are generated by @huaiyumi,  again @huaiyumi to check-- and last 1.c the taxon checker service that PAINT uses is down -- @kltm or @dougli1sqrd can determine that.
2. The pipeline should be checking all submissions to ensure they obey the taxon constraints. This would deal with any failures in the above. Really though these should ideally be caught at inception

**Comment by kltm** [comment]
Moved to implementation ticket here: https://github.com/geneontology/go-site/issues/758

**Comment by pgaudet** [comment]
We should leave this ticket open as it provides nice examples to do QC.

**Comment by kltm** [comment]
@pgaudet If they are to be implemented, they should go with the ticket; if they are documentation, the wiki may be a more appropriate place.

**Comment by pgaudet** [comment]
I think this is all done. Please reopen if not.
