### ISSUE TITLE
Guidelines for ISS protein binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1876]
ISS to 'protein binding' should NOT be allowed, since we cannot capture the 'with' (only the 'from'). 

There are 91 existing annotations: 
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=exact&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0005515&evidenceCode=ECO:0000250&evidenceCodeUsage=descendants

Similarly, ISS to 'protein-containing complex binding' should  NOT be allowed for the same reason. 

@vanaukenk 
@bmeldal 
@ValWood 
@RLovering 

Does that seem OK to you ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Sometimes we might need to infer a binding relationship to fill a gap in a model? @vanaukenk ?

**Comment by bmeldal** [comment]
@ValWood how do you capture the protein you inferred from in species A as well as the inferred binding partner in species B (where the annotation object is from species B)?

I.e.
<GP1 spA> protein binding <GP2 spA> by IPI
<GP1 spB> protein binding <GP2 spB> by ISS --> Where to you capture that you inferred this annotation from <GP2 spA>?

**Comment by ValWood** [comment]
Good point. we haven't ever actually done it so I don't have an example, but  we would probably need to to fill  annotation gaps ....

**Comment by pgaudet** [comment]
- In GO_CAM models, you can leave the evidence black, hence 'filling the gaps' but the data would not be exported until someone can come in and add the correct information. 
- For ISS, how would one handle the 'with' anyway? Say you have
GP-1(human) | protein binding | IPI | with GP-2(human) | 
GP-1(mouse) | protein binding | ISS | with GP-2(human or mouse????) | 
Would putting the mouse ortholog there be correct ? 

Thanks, Pascale

**Comment by ukemi** [comment]
The way I had been doing this was to annotate the mouse protein in the model with ISS and the with field filled in for the human protein. Then I would make a separate model for the human protein and the experimental evidence.

**Comment by pgaudet** [comment]
But the mouse-human interaction is not 'normal', so it seems inconsistent with that basic principle of GO annotations ? 

Pascale

**Comment by deustp01** [comment]
We divide the capture process in two. First, we annotate a multispecies reaction perhaps with multispecies physical entities in it to capture the actual experimental data. That reaction is labeled "chimeric". (We asked NCBI taxonomy for a species instance "chimeric" and they refused.) That reaction is also accompanied by citations to the relevant primary literature. Then, we annotate the inferred human reaction, populated entirely by human entities and tag it as inferred_from (manually, by curator) the chimeric one. If the second reaction has any literature references, they should be ones in which experts spell out their reasons for believing that the chimeric (or other non-human model system) accurately reflects the behavior of the human one.

Maybe an analogy in GO would be likewise to create two models, one that corresponds exactly to the evidence, one that represents the curator's inference to the species of interest. Easy to say; probably a lot of work to implement.

**Comment by bmeldal** [comment]
My example has evidence for one species (e.g. human-human) that is being inferred to another species (e.g. mouse-mouse). So BOTH GPs that are binding are being inferred.

**Comment by vanaukenk** [comment]
We have had, for some time now, an annotation rule that disallows ISS to 'protein binding' for exactly the reason that what could be captured in the With/From field was limited:

https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000005.md

http://wiki.geneontology.org/index.php/Inferred_from_Sequence_or_structural_Similarity_(ISS)

I think this is another good argument for capturing the inputs of protein binding with an annotation extension of has_input.  That way, the 'input' would be species-specific and physiologically relevant while the With/From value would, as always, reflect the source of the sequence-based similarity inference.

**Comment by RLovering** [comment]
Yes 
I was under the impression that the in vivo predicted bound protein could be added to the AE field
ie GP-1(human) | protein binding | IPI | with GP-2(mouse) | AE has_input GP-2(human) 
I guess in theory if the AE field is being used then the protein binding term is informative because of this extension. ie
GP-1(mouse) | protein binding | ISS | with GP-1(human) | AE has_input GP-2(mouse) 

FYI If I do an ISS for:
GP-1(human) | a GO term not binding | IDA | AE has_some_sort_of_target GP-2(human) | to 
GP-1(mouse) |  a GO term not binding | ISS | WITH GP-1(human) AE has_some_sort_of_target GP-2(mouse) |
because the AE field should include in vivo data

Ruth

**Comment by bmeldal** [comment]
Why would someone want to infer a human-mouse (or yeast-pombe etc) binding when the experimental data is species-specific for one species already? I would only use mixed-species evidence if that's what the authors used in the lab and then I see the point at inferring to the 2 species-specific interactions by ISS.

I.e.:
1.
GP-1(human) | protein binding | IPI | with GP-2(human)
infer
GP-1(human) | protein binding | ISS | with GP-2(mouse) - makes no sense, with or without AE

You'd want to get to
GP-1(mouse) | protein binding | ISS | with GP-2(mouse) - which I guess one can capture that correctly with 2 lots of AEs, one for each GP?

2.
GP-1(human) | protein binding | IPI | with GP-2(mouse)
infer to
GP-1(human) | protein binding | ISS | with GP-2(human) | AE has_input GP-2(mouse) 
[infer GP-2(human) from GP-2(mouse)]
and
GP-2(mouse) | protein binding | ISS | with GP-1(mouse) | AE has_input GP-1(human) 
[infer GP-1(mouse) from GP-1(human)]

Or what did I miss conceptually?

**Comment by RLovering** [comment]
Hi Birgit

I'm afraid you do not appreciate that the 'with' field is used for multiple purposes. So we would not create 
GP-1(human) | protein binding | ISS | with GP-2(mouse) - makes no sense, with or without AE
we would potentially create:
GP-1(human) | protein binding | ISS | with GP-1(mouse) - makes no sense, with or without AE
This means that we think that GP-1 in human is able to bind another protein because GP-1 in mouse is able to bind another protein. so in this case the With field provides information about what protein has experimental evidence to support why the GO term has been associated with protein annotated. 
Whereas, when the evidence code is IPI the 'with' field captures the protein bound by the protein annotated.
Because of the lack of information associated with the term 'protein binding' the GOC has suggested that there is no reason to ISS annotation to orthologs.
If this doesn't make sense please discuss with George when you have your P2G training.
Ruth

**Comment by bmeldal** [comment]
Ok, and AE has_input GP-x is the actual binding partner in the same species? But who's actually using this data and how? Unless you go through the pain of parsing out the annotated GP and the GP in the AE **if ECO is ISS** all you get is "protein binding" - and I'd challenge anyone to find a protein that will never ever bind another protein ;-)

Just playing devil's advocate here as so far I've been more of a user of GO annotations than a hard-core contributor.

**Comment by RLovering** [comment]
yes you have got it. this is why the GOC has said don't create ISS protein binding annotations.

But if it was possible to provide information about the predicted binding partner in the AE field and this data could be extracted by uses then this might be useful

**Comment by bmeldal** [comment]
Summary from call on 23/4/18:
Attendees: @hdrabkin , Ben Good, @krchristie , Edith, @deustp01 , Sandra, @vanaukenk , @pgaudet , @hattrill

**Options:**

1. put EXP species ID in "with/from" and inferred species in AE has_input
2. change backend model to allow separate "with" and "from" usage in same line?
3. ask IntAct to curate the experimental data! We capture everything (but wouldn't infer to another species)
4. put inferred species in "with" but use one of the new ECO codes we designed for the complex annotations that allow modelling based on homology inferences (ECO:0005610 "biological system reconstruction evidence based on homology evidence used in manual assertion" or children https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0005610) 
5. ISO for species-specific annotation

**Next step:**

Discuss on next Noctua call (today, Wed, 25/4/18?) as they have more use cases and this is not complex-annotation-specific.

**Comment by bmeldal** [comment]
@vanaukenk & @pgaudet : were we meant to create some guidelines and stick them on the Wiki? Did the Noctua group ever discuss this?

**Comment by vanaukenk** [comment]
@bmeldal - I'll review with @pgaudet and we'll update documentation where needed.  Thx.

**Comment by bmeldal** [comment]
Thanks. Let me know if and where/when I can help. Memory is fading ;-(

**Comment by bmeldal** [comment]
Added Cambridge GOC meeting as milestone. 

Further discussions in https://github.com/geneontology/go-ontology/issues/16833

**Comment by bmeldal** [comment]
Presented at Cambridge GOC mtg on 11/4/19:

Agreed to no longer use pre-composed "x complex binding" terms but with/from field (and AE where required).

- [Rule implementations](https://github.com/geneontology/go-site/issues/1056) - ticket in progress
- Obsoletion tickets: to be created (will be linked to *rule* ticket)
- Annotation review ticket: to be created

Closing as new ticket will capture remaining tasks.
