### ISSUE TITLE
S. pombe sgf29 UniProt annotation from PMID:26401015

### ISSUE THREAD

**Issue by mah11** [geneontology/go-annotation#1877]
We have received a community curation session for PMID:26401015, and upon reviewing it I hereby query one of the annotations UniProt has made from the paper:

    PomBase	SPBC1921.07c	sgf29		GO:0006357	PMID:26401015	IDA		P	SAGA complex subunit Sgf29	SPBC21D10.13	protein	taxon:4896	20170725	UniProt		

As a member of the SAGA complex, Sgf29 probably does play a role in transcriptional regulation, but this paper does not show any experiments assaying transcription, and therefore does not support annotation to GO:0006357 at all, let alone with IDA evidence. Could this annotation therefore please be removed?

I also suggest removing the GO:0016573 annotation, as the paper shows that Sgf29 regulates the HAT module's substrate specificity, and accordingly I am adding an annotation to GO:2000615. But this is less important than deleting the GO:0006357 annotation.

Thank you.

p.s. @marcfeuermann , I don't know which curator is best to flag; please reassign if I've guessed badly.

**Comment by ValWood** [comment]
Tagging @pedruzzi  too. I will also raise a protein2GO dispute pointing to this ticket.

**Comment by pgaudet** [comment]
This annotation has been deleted by Sylvain
