### ISSUE TITLE
duplicate nucleotide kinase molecular function terms?

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-annotation#1878]
GO:0019201 nucleotide kinase activity "Catalysis of the reaction: ATP + nucleoside monophosphate = ADP + nucleoside diphosphate. "
and
GO:0050145 nucleoside phosphate kinase activity "Catalysis of the reaction: ATP + nucleoside phosphate = ADP + nucleoside diphosphate."

Despite the differences in parentage (looking quickly, GO:0019201 looks like its parents are a subset of those of GO:0050145), I can't find a difference between these two terms. Note that while the definition for GO:0050145 sounds more general when it lists substrates, the list of products removes any ambiguity / generality that would distinguish it from GO:0019201. What am I missing? If a merger is in order, no preference from here about which term survives. @ukemi ? @hdrabkin ?

**Comment by ukemi** [comment]
Are all nucleoside phosphates nucleotides? If I recall there are some that are phosphorylated on different residues and didn't fall into the nucleotide category.

**Comment by ukemi** [comment]
transferred to go-ontology#15471
