### ISSUE TITLE
Redundant annotations accumulating

### ISSUE THREAD

**Issue by selewis** [geneontology/go-annotation#1879]
For example --- noticed that the human gene LFNG has been annotated twice in subsequent years by UniProt via ISS. First in 20131212 to GO:0008593  (regulation of notch signaling pathway) and then again in 20150928 to GO:1902367 (negative regulation of notch signaling pathway [blocking JAG]). In addition there is an IEA from Ensembl to GO:0045747 (positive regulation of notch signaling pathway). The positive and negative are fine (though it would be nice to also have an ISS for the positive aspect with DLL1). But why wasn't the original redundant ISS annotation from 2013 removed in 2015?

**Comment by ValWood** [comment]
Removing annotation redundancy has been an action item from  the last few meetings :)
It would be  a huge benefit to users of GO to remove the redundancy.

**Comment by ValWood** [comment]
There are quite a few tickets about implementing redundancy filtering. I looked for the main one last night but I couldn't find it. I know I updated it with the PomBase filtering  procedure.

I'll carry on looking but @cmungall  might know where it is...

**Comment by robnash** [comment]
In my humble opinion, although I agree that redundant annotations based on ISS may make some sense (although not if the with columns entry is different), accumulation of experimental evidence from multiple papers increases the level of confidence that the annotations are concrete. In addition it, is often required if we want to capture things like substrates in column 16. It can (and is used in some knowledge bases) to computationally infer the level of confidence in the function or process.

**Comment by ValWood** [comment]
We should not filter any experimental annotation.

At PomBase we filter IC, NAS,TAS, IEA, ISM,ISS, ISO if nn-HTP experimental annotation exists.

I can see a case for keeping ISS as additional support if your experimental data is a bit weak,  and we used to do this, but on the whole   we decided it added very little (most of our experiments are good).

It makes it much easier for  users (and curators), to evaluate annotations and spot annotation and ontology issues.

For example we filter
37,231 annotations down to 3294...our users  like this. It does not add any value...

Annotations  with different annotation extensions are not redundant (but would not apply as at present are all experimental).

**Comment by ValWood** [comment]
The PAINT pipeline is also producing redundant annotations:
Here there is an IGI from a complementation experiment, plus  IBA

![redundant](https://user-images.githubusercontent.com/7359272/38295209-27f0c2dc-37e5-11e8-9b3d-25d7a7e0dd59.jpg)

**Comment by pgaudet** [comment]
We will develop guidelines for this - see https://github.com/geneontology/go-annotation/issues/2060
