### ISSUE TITLE
IPR032752 ubiquitin binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1880]
Is this correct? it is  a ubiquitin-like domain, but  ubiquitin binding is not necessarily a feature of this family ?

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
Thank you for this. This domain seems to weakly bind to ubiquitin  [PMID: 20440844].  The evidence is not strong, so I will remove this GO term and rename the entry. 
Regards, 
Hsin-Yu
