### ISSUE TITLE
What constitutes a new complex version?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-annotation#1881]
Hi all,

We are trying to define what constitute a new version of a complex in the Complex Portal and so far we have defined:

- change in composition of protein participants

- drastic change in function, i.e. change to GO MF annotation and complex description (I know, a bit vague, we'll have to define it as and when we have a case)

- change in stoichiometry??? We are not sure about this one. Would you consider a change from say a dimer to a tetramer to be a new version of a complex? Often we are not really sure if we are deriving the "real" *in vivo* assembly from an experiment.

Let the discussion begin :)

Birgit

PS: The entry on the CP website and annotation object for GO will always be the canonical AC with the versioning available "under the hood".

**Comment by ValWood** [comment]
Can  we close this? We don't add lots of new complexes and we have quite extensive guidelines
https://wiki.geneontology.org/Protein_complexes
