### ISSUE TITLE
query UniProt KW mapping DUF89

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1884]
has methyltransferase
https://www.pombase.org/gene/SPAC806.04c
from a kw mapping inferred from human

but 
https://www.pombase.org/reference/PMID:27322068
implies
this family are  metal-dependent phosphatases

any input?

**Comment by asangrador** [comment]
Sorry for the delay in answering. This DUF domain seems to match pantothenate kinases and methyltranferases, so I would be wary to associated to any function at the moment. Regarding SPAC806.04c, homology seems to indicate that it is a methyltranferase, I don't know how reliable PMID:27322068 is.

**Comment by ValWood** [comment]
Thanks,
Probably the KW mapping should be removed.

**Comment by ValWood** [comment]
Actually I'll close this one...
