### ISSUE TITLE
Review reference guidelines for GAF, GPAD

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#1885]
Our documentation states that if a database has an independent identifier for a reference that also has a PMID, then both are required in the GAF:

http://geneontology.org/page/go-annotation-file-gaf-format-21

I'd like to review this rule and, if possible, propose that we simplify the reference field by not including redundant identifiers.  

This might then make it possible to use both a published paper and a GO_REF together to indicate when a combination of a published paper and subsequent curatorial analysis was used together to assign an annotation.   See #1796 for an example of how this might be used.

**Comment by suzialeksander** [comment]
Closing as this was specifically included on the latest GPAD specs. Please open a new ticket if this is still a wishlist item
