### ISSUE TITLE
Review direct annotations to 'biological regulation'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1887]
As requested in https://github.com/geneontology/go-ontology/issues/15490
we will make 
'biological regulation' 
'regulation of biological process'
'negative regulation of biological process'
'positive regulation of biological process

-> 'not for direct annotation'. Please remove/move the following annotations: 

https://docs.google.com/spreadsheets/d/1wgIi0LLG8JjwMsnwbafTFNEgxuMU1N6ZvG6gavf0saE/edit#gid=0
(EcoCyc, Flybase, MGI, RGD)

https://docs.google.com/spreadsheets/d/1tx6uSA3dCQc8fXWySu58It5WhmU-gXpEwpUnjsjJylc/edit#gid=0
(EcoCyc and PseudoCap)

This also affects

InterPro:IPR028625 @asangrador 
UniRule:UR000106266 @pedruzzi 

**Instructions:**
1. Please note what you did (removed, changed) in the spreadsheet
2. Remove your name from the assignees when done. 

Thanks, Pascale

**Comment by slaulederkind** [comment]
The two RGD annotations are inferred from the mouse ortholog annotations at MGI.  The RGD annotations will change automatically after the MGI annotations are changed.

**Comment by ukemi** [comment]
The MGI ones are coming from GO-CAM models in which we used the generic regulation term and specified it with class being regulated. We will need to instantiate the regulation of blah terms in the ontology and then change the models.

**Comment by pgaudet** [comment]
@ukemi  OK - so the 'do not annotate' flag shouldn't be a problem; it will just be an error in the report.

**Comment by keseler** [comment]
I removed/changed the annotations in EcoCyc, but I don't know when the changes will make it into the E. coli GAF due to our indirect process via EcoliWiki.

**Comment by pedruzzi** [comment]
Since @keseler removed GO:0065007 from UniProt:P0AFW4, I removed the term from corresponding UniRule:UR000106266 as well

**Comment by asangrador** [comment]
InterPro:IPR028625  has been removed.

**Comment by pgaudet** [comment]
Thanks everyone.
