### ISSUE TITLE
annotation review request, YGL185C

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1888]
I can't see where this comes from?

It's IEA from GO:0003714 but this gene product is not GO:0003714?
I'm not sure which GOC pipeline this comes from?

	YGL185C	Putative protein with sequence similar to hydroxyacid dehydrogenases		negative regulation of nucleic acid-templated transcription		GOC	Saccharomyces cerevisiae S288C	IEA	GO:0003714			SGD_REF:S000204515	20180303

**Comment by ValWood** [comment]
similar situation with

https://www.yeastgenome.org/locus/YGR196c#go
negative regulation of nucleic acid-templated transcription |   | IEA with transcription corepressor activity | GOC | 2017-09-23 |   | GOA curators (2016)

which pipeline is this?

there are possibly more.... I only found the ones which are annotation "unknowns"

**Comment by ValWood** [comment]
@srengel  do you know where they come from?

**Comment by ValWood** [comment]
@ggeorghiou  any idea? I haven't seen these before

 GOA curators (2016)

**Comment by ggeorghiou** [comment]
I'm wondering if this is from annotation inferences between function and process GO terms that GOC fills in sometimes when a curator makes an annotation to the function term but not the process. Protein2GO suggests additional GO terms to use sometimes based on how frequently they appear together, but there are additional annotations suggested that it makes that says GOC will make them if you don't add them (i.e., protein is annotated to 'kinase activity', the suggestion is to automatically make an annotation to the process 'phosphorylation')

**Comment by ValWood** [comment]
so these 2 genes don't have
"transcription corepressor activity" so could you delete?

v

**Comment by ggeorghiou** [comment]
If they are IEA annotations, I am not able to.

**Comment by ValWood** [comment]
Ah OK, could you assign to the person who creates the pipeline?

**Comment by ggeorghiou** [comment]
Not sure I can do that either since I am not sure about it myself. Tony has always said it was from GOC. Unfortunately he's away for the next 2 weeks. @cmungall any ideas?

**Comment by ggeorghiou** [comment]
So, just had a look in Protein2GO for this entry. It's a PAINT annotation from REFG to transcriptional co-repressor activity that is linked to the process term. https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P53100

REFG made the original annotation but I can't see who the curator was since we import these into GOA.

**Comment by ValWood** [comment]
OK no hurry, I can filter for my purposes, on the assumption these will go.

**Comment by ValWood** [comment]
I don't see any annotation to
transcriptional co-repressor activity
https://www.yeastgenome.org/locus/S000003153#sequence

for either of these at SGD (EXP or inferred?)

**Comment by ggeorghiou** [comment]
These the transcriptional corepressor activity is an IBA annotation from PAINT. That's interesting that it is not showing up at SGD. If they filtered the function term, how did they not filter out the process term?

**Comment by ValWood** [comment]
OK, got it.
In the Uniprot entry
http://www.uniprot.org/uniprot/P53100
has the following  PAINT annotations

glyoxylate reductase (NADP) activity Source: GO_Central
hydroxypyruvate reductase activity Source: GO_Central
protein homodimerization activity Source: GO_Central
transcription corepressor activity Source: GO_Central

transcription co-repressor come from
http://www.pantree.org/node/annotationNode.jsp?id=PTN000107684
if I follow the link.
That looks  like a bug? @selewis

**Comment by srengel** [comment]
not sure if there is anything i need to do here?  i'm a little confused in that i don't even see the FYV8/YGR196C annotation that Val is referring to?  for YGR196C, the annotation is linked to this GO ref:
https://www.yeastgenome.org/reference/S000204515

**Comment by ValWood** [comment]
Very confusing.

I see it in SGD 

![detail](https://user-images.githubusercontent.com/7359272/38040048-909d76de-32a6-11e8-93b4-d7b6782f7f32.jpg)

but not in AmiGO?

Although I am using GO term finder and that is using the current GO database....

**Comment by srengel** [comment]
right, that's the YGL185C annotation, but i don't see the FYV8/YGR196C (i now realize i made an ORF name typo in my comment a few minutes ago).

**Comment by ValWood** [comment]
OK I got mixed up. I had another example with the transcription repressor, but I lost it.

This one is a different reason.

YGR196C
https://www.yeastgenome.org/locus/YGR196c#go

DNA demethylation		IBA with PTN000559411	GO_Central	2016-09-15		Gaudet P, et al (2010)

this is odd,  because cerevisiea don’t have DNA methylation?

**Comment by ValWood** [comment]
This ticket got a bit confusing. I'll open new separate tickets for each with what we know...
