### ISSUE TITLE
YLR419W PAINT to RNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1889]
https://www.yeastgenome.org/locus/S000004411/go

Has
RNA processing |   | IBA with PTN000433338 | GO_Central | 2014-07-30 |   | Gaudet P, et al (2010)

from
http://pantree.org/node/annotationNode.jsp?id=PTN000433338

I'm not sure this is appropriate. The processing term comes from helicases which are involved in splicing. This is most likely mitochondrial  where there is no splicing (at least  not the same type)

**Comment by pgaudet** [comment]
Should be fixed. Can you close or do you want to wait to see the changes? 

Pascale

**Comment by ValWood** [comment]
thanks.
