### ISSUE TITLE
Query annotations 'signal transducer' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1890]
Hello @dougli1sqrd 

I would like to have the annotations in the main database (ie NOT Noctua): 
For all proteins annotated to 'signal transducer' - what other MF is each one of them annotated to? 

It would be nice to have a template query like this in GOOSE. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think you can already do this,
use all genes annotated to "molecular function activity" but not"signal tranducer activity"

**Comment by ValWood** [comment]
that wont work will it?

You will need
all genes annotated to "signal transducer activity" and but not where "molecular function activity" is NOT  "signal tranducer activity"
(you might need to exclude "protein binding" too)

**Comment by pgaudet** [comment]
Right - I need to take all "signal transducer activity" , then take all MF annotations (even without the protein binding, that's 80K annotations), and do a diff. 

AmiGO seems to be unable to return the 80K annotations but I may not be patient enough). 

Pascale

**Comment by dougli1sqrd** [comment]
And just to be clear, you want back annotations?

**Comment by pgaudet** [comment]
Hi @dougli1sqrd 
Yes I would like 
Protein accession | GO + Evidence | GO + evidence (if there is more than one annotation). 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
As a preliminary set of results, take at look at the attached file: 
[ducers.log](https://github.com/geneontology/go-annotation/files/1921829/ducers.log)

**Comment by dougli1sqrd** [comment]
```
?Term	?GP	?code
<http://purl.obolibrary.org/obo/GO_0004871>	<http://www.wormbase.org/db/gene/gene?name=WBGene00003099>	"IBA"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.obolibrary.org/obo/GO_0004871>	<http://www.wormbase.org/db/gene/gene?name=WBGene00008930>	"IBA"^^<http://www.w3.org/2001/XMLSchema#string>
```

**Comment by suzialeksander** [comment]
@pgaudet this ticket isn't assigned to anyone, if you still need it can you please re-assign

**Comment by pgaudet** [comment]
Out of date.
