### ISSUE TITLE
annotation challenge "social behavior" ->Putative protein MSS51 homolog, mitochondrial

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1892]
Is annotated to "social behaviour"  by IEP?

**Comment by ValWood** [comment]
and  Q8WXX5

(but these are the only 2 annotations to social behaviour , so not so bad....)

**Comment by ValWood** [comment]
Yes there are 18 genes. I menaa there are only 2 annotated by IEP. But this  seems to be an association study (candiate region), and then some genes int  this region are down-regulated, ( in Epstein-Barr virus-transformed lymphoblastic cells) hmm....

revised above

**Comment by ggeorghiou** [comment]
Hi Val,

Looking at this right now. I've got more than 2 annotations to 'social behavior' with evidence IEP: https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0035176&evidenceCode=ECO:0000270&evidenceCodeUsage=descendants

I'll have a look at the annotation you are challenging and the associated genes from the same paper (PMID;21531385) annotated to social behavior.

**Comment by pgaudet** [comment]
Annotations from PMID;21531385 have been removed
