### ISSUE TITLE
P84039 cell comunication

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1893]
human unknown protein  is getting an annotation to "cell communication" by IEA from ensembl pipeline.

The annotation comes from
http://www.uniprot.org/uniprot/P84039
(IDA)

but there is no experiment described in the abstract:

Membrane glycoproteins of neural cells play crucial roles in axon guidance, synaptogenesis, and neuronal transmission. We have here characterized membrane glycoproteins containing terminal alpha-mannose residues in rat brain membranes. Affinity purification using Galanthus nivalis agglutinin, that is highly specific for terminal alpha-mannose residues, revealed a 50-kDa protein as well as 80-kDa SHPS-1 and 45-kDa beta2 subunit of Na,K-ATPase in rat brain membranes. Combination of N-terminal peptide sequencing and mass spectrometry indicated that the 50-kDa protein was rat nucleotide pyrophosphatase-5 (NPP-5). In contrast to other NPPs, NPP-5 was a type-I transmembrane protein. Northern blot analysis showed that NPP-5 was highly expressed in brain, but also expressed in other peripheral tissues. However, we could not detect either the NPP activity or the lysophospholipase D activity in the immunoprecipitates with antibodies to NPP-5 from rat brain membranes. These data, therefore, suggest that NPP-5 is a neural oligomannosidic glycoprotein that may participate in neural cell communications.

seems to be just a northern blot showing expression in the brain?

@slaulederkind  could you take a look?

**Comment by slaulederkind** [comment]
I would annotate "membrane" to rat Enpp5 from this paper, nothing else.

**Comment by ValWood** [comment]
;) cheers... sorry I didn't look at the paper in detail, but it looked unlikely from the abstract...
