### ISSUE TITLE
Q9HB07 locomotory exploration behavior  (UPF0160 protein MYG1, mitochondrial)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1894]
unknown human protein,

~annotated to locomotory exploration behavior
via a mouse annotation from this paper?
Myg1-deficient mice display alterations in stress-induced responses and reduction of sex-dependent behavioural differences.
The main finding of the present study was that Myg1 invalidation decreases several behavioural differences between male and female animals that were obvious in wild-type mice, indicating that Myg1 contributes to the expression of sex-dependent behavioural differences in mice.~

I misunderstood this one. the "locomotory  behaviour" it seems is some "anxiety induced phenomena (not to be confused with actual locomotion!)

**Comment by ValWood** [comment]
remaining annotation looks dodgy too
UniProtKB:Q9HB07 | C12orf10 | involved_in | GO:0043473    pigmentation | ECO:0000303   NAS | PMID:16996721 |   | 9606 | UniProt
MYG1, novel melanocyte related gene, has elevated expression in vitiligo.
(PMID:16996721)

@ggeorghiou

**Comment by hdrabkin** [comment]
WHAT paper @ValWood ? PMID:16996721? We have no annotations using this at all.
If you mean the IMP using PMID:19818808?  We see nothing wrong with this annotation. 
Fig. 3. Locomotor activity test and habituation in mice lacking Myg1

**Comment by pgarmiri** [comment]
Hi @ValWood ,
I had a look at this annotation and the publication. The authors observed an increase in MYG1 expression in vitiligo patients and they concluded that there is a possible involvement of MYG1 in the pathogenesis of vitiligo. That would have been a disease related function and should have not been captured. I am deleting the annotation and closing the issue.
Thanks,
Penelope
