### ISSUE TITLE
"unknown" human gene "neuron death"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1895]
This study doesn't seem appropriate to make an annotation to
"neurone death"

PMID: 22166940

(in fact "neuron death" is not for direct annotation, are these rules being applied?)

@pgaudet 
@cmungall

**Comment by pgaudet** [comment]
@ggeorghiou can you please review ?

**Comment by ggeorghiou** [comment]
I've had a look and yes, these annotations are not appropriate. I've gone ahead and deleted them.
