### ISSUE TITLE
query annotation human Q5FVC7 "protein localization to endosome"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1897]
It seems from the abstract that the appropriate annotation here would be
GO:0032456    endocytic recycling ?
could you take a look?

v

**Comment by ggeorghiou** [comment]
@sylvainpoux I am currently trying to clear up some of the UniProt tickets on the annotation tracker and this particular annotation belongs to SIB. Can you have a look? I'm in agreement with Val that it should be endocytic recycling.

**Comment by sylvainpoux** [comment]
Done
S.
