### ISSUE TITLE
Review annotations to GO:0008517 folic acid transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1900]
* InterPro:IPR032935	Folate receptor alpha -> Incorrect, should be  GO:0061714  folic acid receptor activity
* InterPro:IPR032937	Folate receptor beta ->Incorrect, should be  GO:0061714  folic acid receptor activity
* InterPro:IPR028339	SLC19A1	-> imprecise; can use the new GO term  GO:0140211 folate symporter activity

~* MGI:MGI:95569	folate receptor 2 (fetal) -> Incorrect, should be  GO:0061714  folic acid receptor activity~
~* MGI:MGI:95568	folate receptor 1 (adult) -> Incorrect, should be  GO:0061714  folic acid receptor activity~

(More explanation here: https://github.com/geneontology/go-ontology/issues/15461) 

Thanks, Pascale

**Comment by hdrabkin** [comment]
done

**Comment by asangrador** [comment]
I have changed IPR032935 (Folate receptor alpha) and IPR032937 (Folate receptor beta) as suggested, both for folic acid receptor activity and folic acid import across plasma membrane.
Regarding InterPro:IPR028339 SLC19A1, I have changed it to the more specific GO:0008518 'folate:anion antiporter activity' (I think GO:0140211 'folic acid:proton symporter activity' is meant  for SLC46A1).

**Comment by pgaudet** [comment]
@rachhuntley 'folic acid transport' does not imply that its transmembrane. The folate recptors receptors transport folate by endocytosis. 

Thanks to all for the fixes. 

Pascale
