### ISSUE TITLE
Review Annotation to non-specific MAPK cascades

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#1901]
As part of the MAPK project, we have decide to obsolete or merge the 'MAPK cascade involved in X' terms because they do not differentiate the MAPK cascades themselves in a standard way. See ontology ticket https://github.com/geneontology/go-ontology/issues/14676. 

The annotation spreadsheet can be found here:
https://docs.google.com/spreadsheets/d/1wo7CkDWA9hD9C2Q-a3taA3xq-YvPR5VuJDOaOgS66mQ/edit#gid=0

**Comment by vanaukenk** [comment]
Changed the WB annotations to 'p38 MAPK cascade' with an annotation extension for the axon regeneration process.

**Comment by ukemi** [comment]
Perfect!

**Comment by pgaudet** [comment]
@ggeorghiou or @milarolo Can you please look at the UniProt annotations for this ? There are 15 annotations (but fewer genes). 

Thanks, Pascale

**Comment by milarolo** [comment]
Done. The UniProt annotations had already been changed a year ago for "activation of MAPK activity" (GO:0000187). There was only one left.  I changed it to "positive regulation of MAPK cascade" (GO:0043410)

**Comment by ggeorghiou** [comment]
Seeing as this is done, I am closing this ticket.
