### ISSUE TITLE
PAINT PANTHER:PTN001087171	 not electron transfer (via Matrix)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1904]
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC8F11.02c
dph3 | diphthamide biosynthesis protein Dph3 (predicted)

has

electron transfer activity?

it's involved intRNA wobble uridine modification 
but now mapping to GO:0006091    generation of precursor metabolites and energy
via F-P link toGO:0022900    electron transport chain

**Comment by marcfeuermann** [comment]
PAINT annotation of PTHR21454 has been updated. I've removed the propagation of  'electron transport chain' and added 'tRNA wobble uridine modification' .
