### ISSUE TITLE
PAINT 	PANTHER:PTN000132051	 not endoplasmic reticulum unfolded protein response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1905]
I need to look into this one, but I don't think the

UDP-glucose-glycoprotein glucosyltransferase Gpt1
 is unfolded protein response (a signalling pathway)

but is
ER-associated misfolded protein catabolic process

This one might be an  mis-annotation somewhere... but I need to check first. I tidieed the pombe ones recently to get rid of the problem annotations...

**Comment by pgaudet** [comment]
Annotation removed

Thanks, Pascale
