### ISSUE TITLE
PAINT wrong family for inferences  (via Matrix)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1906]
Mis6 is a well defined kinetochore component involved in CENP-A assembly
https://www.pombase.org/gene/SPAC1687.20c

it is the ortholog of s. cerevisiae CTF3
https://www.yeastgenome.org/locus/YLR381W
is PTHR23139 family

However, in AmiGO, it is getting  mappings to

mRNA export from nucleus
and
mRNA splicing, via spliceosome

from

PANTHER:PTN000567094
which appears to be a different cerevisiae protein?

**Comment by ValWood** [comment]
Another example
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC19B12.11c
is involved in ribosome biogenesis

but is mapping to 

lipid A biosynthetic process
from 
PANTHER:PTN000466551

http://www.pantree.org/node/annotationNode.jsp?id=PTN000466551
it isn't in this family?

**Comment by marcfeuermann** [comment]
SPAC1687.20c nor  S. cerevisiae CTF3 (YLR381W) are found in any family anymore. Should one be created ?
@huaiyumi 
SPAC19B12.11c has been moved in PTHR46095 where it is not annotated to 'lipid A biosynthetic process' anymore, only ribosomal terms.

**Comment by ValWood** [comment]
@huaiyumi fyi
human cenp-I should be in this family too,
I submitted a Pfam family for this a long while back
http://pfam.xfam.org/family/PF07778#tabview=tab6

**Comment by huaiyumi** [comment]
These annotations were fixed in panther families and paint, but AmiGO was not reflecting the updates due to the implementation of the pipeline at the time. They are now all correct in AmiGO.
