### ISSUE TITLE
	PANTHER:PTN002321897 to ribosomal subunit export from nucleus (via Matrix)	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1907]
This is a heat shock protein,
I don't think it has a direct role in "nucleocytoplasmic transport?
(ribosome subunit export from the nucleus)
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC1709.05

(the family linked to does not exist, so maybe this annotation will disappear?)

**Comment by marcfeuermann** [comment]
The annotation does not exist anymore, so yes, it should disappear.
