### ISSUE TITLE
PAINT Spo4 to various off target processes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1908]
Pombe spo4 is a sporulation specific kinase

It is annotated erroneously to

DNA replication initiation via PANTHER:PTN000747050
phagocytosis via PANTHER:PTN000747050
double-strand break repair via break-induced replication  via PANTHER:PTN000747050
regulation of cell shape via PANTHER:PTN000225966

oddly some of the evidence for the transfer comes from fission yeast? SPBC776.12c
(a kinase that is involved in replication)
http://www.pantree.org/node/annotationNode.jsp?id=PTN000747050
presumably an aincient paralog.

transfer of annotation to paralogs is  a bit unsafe often....

**Comment by marcfeuermann** [comment]
Spo4 and SPBC776.12c (hsk1) are neighbors in the tree, meaning that they probably originate from a "recent" duplication event with loss of function for spo4. So I've removed the terms  'DNA replication initiation' and 'double-strand break repair via break-induced replication', specifically for spo4. 'Regulation of cell shape' and 'phagocytosis' have already been removed previously.
