### ISSUE TITLE
YGL185C annotation query (source unclear)  -PTHR10996 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1909]
from
https://github.com/geneontology/go-annotation/issues/1888

SGD annotated this 
to biological process ND

However there is an IEA annotation to

negative regulation of nucleic acid-templated transcription |   | GOC | Saccharomyces cerevisiae S288C | IEA | GO:0003714

http://amigo.geneontology.org/amigo/gene_product/SGD:S000003153

I can't trace the source of this annotation.....
YGL185C  is not annotated to GO:0003714 (which is in the 'with' field)

we think it comes from F-P mappings but are not sure...

**Comment by pgaudet** [comment]
@ValWood See curator notes here: 
http://www.pantree.org/tree/familyCuratorNotes.jsp?accession=PTHR10996
"PTN000107684 clade is a group of eukaryotic CTBPs (C-terminal binding protein) - that are transcriptional co-repressors with enzymatic activity with unclear substrate (pmid:17336131 and 12419229)." 
This seems to be supported by more recent papers as well, see PMID 28576945. 

I cannot open the tree right now but I'll check if the current tree topology is consistent with these notes. 

Thanks, Pascale

**Comment by ValWood** [comment]
OK it does some from PANTHER, that wasn't clear.

But this protein  is in this panther family 
https://www.yeastgenome.org/domain/PTHR10996

and this Pfam family?
http://pfam.xfam.org/family/PF02826

I can't see any link to transcription here?

**Comment by ValWood** [comment]
This is a very big family of 
 2-hydroxyacid dehydrogenase, NAD binding domain
http://pfam.xfam.org/family/PF02826

I don't think this can be transferred to fungi.
Other yeast members are
https://www.yeastgenome.org/locus/S000005915
https://www.yeastgenome.org/locus/S000005218
https://www.yeastgenome.org/locus/S000000883

and CTBP does not seem to be a direct ortholog....

**Comment by ValWood** [comment]
Ah I just read the notes, but PTHR10996 isn't covered by these. I don't think this can be inferred for these anyway.

**Comment by ValWood** [comment]
plus 
Putative protein with sequence similar to hydroxyacid dehydrogenases; green fluorescent protein (GFP)-fusion protein localizes to the cytoplasm 1 2

**Comment by huaiyumi** [comment]
Just checked AmiGO and PANTHER, SGD:S000003153 is not annotated to GO:0003714. It seems that the issue was resolved.
