### ISSUE TITLE
	PANTHER:PTN001997363 mitotic cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1911]
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC13G7.04c
I can't find the annotation for this here:
http://www.pantree.org/node/annotationNode.jsp?id=PTN001997363

**Comment by marcfeuermann** [comment]
Has been remove by PAINT, but still present in AmiGO. The discrepancy will be fixed when the pipeline is restored.
