### ISSUE TITLE
PTN000144283 chaperonin containing T-complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1913]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000144283

This isn't chaperonin containing T-complex ?
which is well characterised:
https://www.pombase.org/gene/SPBC9B6.03
I don't even see a connection here?

Its an "unknown" member of this family?
https://www.pombase.org/gene_subset/interpro:IPR000306

**Comment by ValWood** [comment]
yeast ortholog
https://www.yeastgenome.org/locus/YGL023C

human orthologs
http://www.uniprot.org/uniprot/Q7Z3T8
http://www.uniprot.org/uniprot/O95405

looks like some aspect of vesicle-mediated transport?

**Comment by ValWood** [comment]
for e.g., one of the annotations transferred from is
https://www.pombase.org/gene/SPAC1420.02c (which is chaperonin containing T complex)

but the annotation is for
https://www.pombase.org/gene/SPBC9B6.03
which is unrelated. Possibly a pipeline issue?

**Comment by pgaudet** [comment]
@ValWood 

Again this is a problem regarding the lack up update of the annotations: SPBC9B6.03 isn't a child of PTN000144283 anymore. 

Thanks, Pascale
