### ISSUE TITLE
PANTHER:PTN000749808 etc off target recombination/repair	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1914]
I'm not sure that these are correct for
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC694.02

PANTHER:PTN000344873
four-way junction helicase activity

PANTHER:PTN000749808
nucleus

PANTHER:PTN000344873
chromosome
recombination

PANTHER:PTN000344874
double-strand break repair via homologous recombination

evidence so far points to this being a cytoplasmic helicase:

1. HDA to cytosol pombe
2. human orthologs
http://www.uniprot.org/uniprot/Q8IY21
cytosolic based on
https://www.ncbi.nlm.nih.gov/pubmed/21791617
and its paralog:
http://www.uniprot.org/uniprot/Q5H9U9
is RNA binding

3. pombe HTP physical interactions indicate  connnections to RNA degradation

**Comment by pgaudet** [comment]
@keslingmj You have looked this book - can you have a look ?

**Comment by marcfeuermann** [comment]
SPAC694.02 is not in any family anymore and should loose all annotations.

**Comment by ValWood** [comment]
It should be in a family...it has clear  human orthologs DDX60 and DDX60L
Hieranoid, Inparanoid, OMA, OrthoDB, OrthoFinder, OrthoInspector, orthoMCL, Phylome, RoundUp, TreeFam
(no cerevisiae ortholog though)

**Comment by pgaudet** [comment]
emailed @huaiyumi

**Comment by huaiyumi** [comment]
In the next release, SPAC694.02 is clustered in the same family with human DDX60 and DDX60L.
