### ISSUE TITLE
	PANTHER:PTN000684825	 likely pseudokinase, unknown role

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1916]
We don't know what tea5 does:

All of these annotations are off target:

regulation of apoptotic process
protein serine/threonine kinase activity
signal transduction by protein phosphorylation
stress-activated protein kinase signaling cascade
regulation of mitotic cell cycle

Mostof the mappings come from pombe annotation, so the transfer for this family should be closely inspected generally:
http://www.pantree.org/node/annotationNode.jsp?id=PTN000684825

(it isn't a canonical kinase, we have the product as pseudokinase, but I can't remember where that came from.....)

**Comment by pgaudet** [comment]
hi @ValWood 

tea5 is in a pombe-specific duplication together with cdc7. I can add NOT annotations to tea5 for all these terms; do you think these should not be applied to cdc7 either? 

Thanks, Pascale

**Comment by ValWood** [comment]
cdc7 is a kinase, but should not have:

regulation of apoptotic process
stress-activated protein kinase signaling cascade

its part of the septation initiation network.....

**Comment by ValWood** [comment]
was that pombe cdc7 or human/cerevisiae cdc7 (which is pombe hsk1)

**Comment by pgaudet** [comment]
- I removed 'regulation of apoptotic process'

- 'stress-activated protein kinase signaling cascade' is somehow removed by PAINT (message: "PTNnnnn annotated to GO:0031098 with evidence code IBA for annotation id 425105294 has paint evidence code but not PAINT evidence type GO_REF ). 

Hopefully that takes care of this one. 

Thanks, Pascale

**Comment by ValWood** [comment]
OK it is cdc7 http://www.uniprot.org/uniprot/P41892

I won't pretend to know everything that these kinases  regulate, but we aren't even sure that apoptosis actually occurs in fission yeast (and I suspect that some of the other annotations are from readouts). This is a central kinase regulating cytokinesis and septation,  and would cause cell cycle and apoptosis-like phenotypes (cell cycle arrest)  if mutated....

fy researchers would find an annotation to "apoptosis" very odd...

so yes, all good.
