### ISSUE TITLE
PANTHER:PTN000207233	 yeast have no 	mitochondrial respiratory chain complex I

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1917]
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC18E5.10

http://www.pantree.org/node/annotationNode.jsp?id=PTN000207233

so not
mitochondrial electron transport, NADH to ubiquinone

or
mitochondrial respiratory chain complex I

(I really really thought I got a taxon constraint on this one...)

So, mitochondrial respiratory chain complex I
is a huge multifunctional supra-complex...pombe has 2/~44 subunits....

for more detail see
https://github.com/geneontology/go-annotation/issues/1207
and linked tickets...

**Comment by ValWood** [comment]
Also applies to
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC11E3.12
from
http://www.pantree.org/node/annotationNode.jsp?id=PTN000042665

**Comment by ValWood** [comment]
plasma membrane respiratory chain complex I
--

**Comment by ValWood** [comment]
note to self, taxon constraints

**Comment by ValWood** [comment]
plasma membrane respiratory chain complex I
has taxon constraints only in bacteria, never in fungi
https://www.ebi.ac.uk/QuickGO/term/GO:0045272

requested the other one:
https://github.com/geneontology/go-ontology/issues/15521

**Comment by pgaudet** [comment]
@huaiyumi @thomaspd This could be a test family to check whether touchup works ?

**Comment by pgaudet** [comment]
@ValWood 
According to  PMID:21115482 the respiratory complex I is present in all species, even in bacteria. So the complex annotation should be OK; or what is the evidence otherwise ? 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
Plasma membrane respiratory chain complex I is indeed a bacterial term. This will be removed from non-bacterial species. I could remove respiratory chain complex I from fungi if you agree.

**Comment by ValWood** [comment]
I know that pombe and cerevisiae do not have mitochondrial  complex I.  (they have an alternative NADH dehydrogenase), I'm not sure but I think I discussed this recently with @Antonialock  and it was present in some other fungi.

**Comment by ValWood** [comment]
The evidence that it not present in pombe is well known, but it only has 2/44 subunits out of the in the complex. I suspect that the complex has other activities too.

**Comment by Antonialock** [comment]
Complex 1 is present in most fungi but not all (eg. absent in saccharomyces cerevisiae and Shizosaccharomyces pombe but  present in Yarrowia, Aspergillis and Neurospora). I think all (?) eukaryotes have alternatives to complex 1 (at least 1 or 2 other systems - alternative dehydrogenase and AOX, and there might be an unknown mechanism?)

There was something about if the organism is "roterod sensitive" then it has complex 1.

**Comment by marcfeuermann** [comment]
Very interesting paper, thanks Pascale. Figure 2 is really clear. So it seems that yeasts do not have complex I contrary to filamentous fungi. I've removed the propagation of complex I to all fungi, but I could restrict this to yeasts (Saccharomyces/Kluyveromyces clade and pombe clade). Would you agree with that ?

**Comment by marcfeuermann** [comment]
Okay, Done !

**Comment by ValWood** [comment]
This  one should not have come up, already has taxon constraints!

GO:0045271 | respiratory chain complex I | Never in Taxon | 4896 | Schizosaccharomyces pombe |  

GO:0045271 | respiratory chain complex I | Never in Taxon | 4932 | Saccharomyces cerevisiae
