### ISSUE TITLE
cell wall organization and biogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1920]
We are picking up PAINT annotations to cell wall organization and biogenesis 

SPAC19B12.01 TPR repeat protein, human TTC27 ortholog
from

https://www.yeastgenome.org/locus/YNL313C
(clearly has a more general role, since it is conserved to human...lots of processes can affect cell wall integrity).....this is likely to be something really "core" since it is essential in both yeast.

@srengel  do you think this annotation seems OK?

**Comment by srengel** [comment]
this paper https://mic.microbiologyresearch.org/content/journal/micro/10.1099/mic.0.045971-0 indicates a direct role, so i'm inclined to leave as is.  

"Loss of Emw1p function is not associated with abrogation of the cell wall integrity (CWI) MAP kinase cascade. Instead, emw1(ts) mutants activate this cascade even at permissive temperature, indicating that loss of Emw1p function does not cause a defect in sensors and effectors of cell wall signalling, but leads to a cell wall defect directly."

**Comment by ValWood** [comment]
....but it's upstream of the MAPK cascade according to the statement above "i.e activate this cascade" ? so it would be "regulation of " in this case?

**Comment by ValWood** [comment]
OK I misread it.  But a phenotype with a loss of cell wall integrity could  even be a cytokinesis defect, or other things...... the phenotype isn't necessarily through MAPK?

**Comment by ValWood** [comment]
The "directly" could be just semantics because the abstract concludes:

Consequently, the defect associated with emw1ts mutants may be associated with compromise in one of the remaining processes that depend on UDP-GlcNAc, namely N-glycosylation or glycosylphosphatidylinositol (GPI)-anchor synthesis.

**Comment by ValWood** [comment]
The PAINT mapping is gone so this is fine,
