### ISSUE TITLE
PTHR10584 PTN000061853 ribokinase-like family 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1921]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000061853

https://www.pombase.org/gene/SPAC16C9.01c

Not all ribokinase-like  family members are carbohydrate metabolism:
https://www.pombase.org/gene_subset/interpro:IPR029056
(some are nucleotide)

**Comment by marcfeuermann** [comment]
SPAC16C9.01c and related homologues have been split form PTHR10584 into a small family PTHR47098, which does not contain any relevant annotation to propagate.
