### ISSUE TITLE
PTN000248248 NADH dehydrogenase complex assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1922]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000248248

is mapping
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC25A8.03c
to 
NADH dehydrogenase complex assembly

(pombe has an NADH dehydrogenase complex, but it is only 2 subunits, not the 44 subunits of the metazoan complex, AND it is not evolutionarily related),

so this is probably not a good annotation for yeast. Maybe it has a more general role in complex assembly?

the concurrent annotation to "ATP metabolic process" seems odd?  too

**Comment by pgaudet** [comment]
hi @ValWood 
I reannotated the tree:
 -moved GO:0032981 mitochondrial respiratory chain complex I assembly deeper in the branch, now excluding fungi
- added MF  GO:0035243  protein-arginine omega-N symmetric methyltransferase activity to the root

OK for you ? 

Thanks, Pascale
