### ISSUE TITLE
	PANTHER:PTN000815317	 photorespiration (has taxon constraint only in plants?)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1923]
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC630.09c

from http://www.pantree.org/node/annotationNode.jsp?id=PTN000815317

**Comment by ValWood** [comment]
from this family
glycerate kinase activity


but from this family http://www.pantree.org/node/annotationNode.jsp?id=PTN000032154
uridine kinase
and
pyrimidine nucleobase metabolic process


(uridine most likely)

**Comment by ValWood** [comment]
@cmungall  could you assign to somebody to look into the absence of taxon constraints?
This seems to be cropping up  in a few tickets?

**Comment by pgaudet** [comment]
@ValWood Can you please create one ticket per family/PTN node?

**Comment by pgaudet** [comment]
from http://www.pantree.org/node/annotationNode.jsp?id=PTN000815317
-> removed by PAINT processing because primary annotation has been removed.

**Comment by pgaudet** [comment]
Hi @ValWood 

Can you please explain what you are asking for  http://www.pantree.org/node/annotationNode.jsp?id=PTN000032154? 

Thanks, Pascale

**Comment by ValWood** [comment]
Hmm, it looks like the second comment went into the wrong ticket! I will investigate...

**Comment by pgaudet** [comment]
I'm closing. Please open a new ticket if needed.

**Comment by ValWood** [comment]
Oh I get it, its all about the same gene product

http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC630.09c

I was pointing out that it had two completely different families, but it is a multi domain protein.
I'll move the part about 
glycerate kinase activity to a new ticket
