### ISSUE TITLE
annotation query: "intracellular transport" for human HID1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1924]
the annotations to "intracellular transport" for human HID1
 http://www.uniprot.org/uniprot/Q8IV36
is from
http://www.uniprot.org/citations/21337012
although a trafficking role is likely, there is no assay for this process in this paper...

The Golgi has other functions, glycosylation, catabolic processes, transmembrane transport so it isn't really safe to assume trafficking with no experiments...

note once this is checked
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBP19A11.07c
http://www.pantree.org/node/annotationNode.jsp?id=PTN000491103

**Comment by vanaukenk** [comment]
Please also check the annotation to

GO:0031001 response to Brefeldin A

as I think the BFA experiments in the paper are meant to address the subcellular localization of HID1.

**Comment by ValWood** [comment]
ah right in that case the original annotation might be OK (with IMP not IDA). Brefeldin A is a commonly used trafficking inhibitor.  I could not find any explicit reference to transport in the paper.

**Comment by ValWood** [comment]
Allthough I don't know how specific it is for use as an assay....

**Comment by pgaudet** [comment]
Fixed
