### ISSUE TITLE
Review annotations to GO:0000989 'transcription factor activity, transcription factor binding'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1926]
Dear all, 

For the transcription factor overhaul, we are proposing to obsolete GO:0000989 'transcription factor activity, transcription factor binding'. There are not very many annotations, and most proteins are annotated to other MF terms. Please review your annotations: 

https://docs.google.com/spreadsheets/d/1XaVzCW-NO9dgPzdnaNvXz5l1VXyVngAgTp5XZRb7Oms/edit#gid=0

Impacted groups: 

BHF-UCL @RLovering 
MGI @ukemi 
SGD @suzialeksander 
UniProt @ggeorghiou 

tagging @krchristie

Please fill the Google doc and remove your name from the assignees when done. 
-----

Also, there are some IPR mappings: 

IPR | consider | GO term
-- | -- | --
InterPro:IPR030006 | consider | GO:0001104    RNA polymerase II transcription cofactor activity
InterPro:IPR030008 | consider | GO:0001104  RNA polymerase II   transcription cofactor activity
InterPro:IPR032648 | consider | GO:0000981  RNA polymerase II   transcription factor activity, sequence-specific DNA binding
InterPro:IPR030174 | consider | GO:0000981  RNA polymerase II   transcription factor activity, sequence-specific DNA binding
InterPro:IPR030167 | consider | GO:0000981  RNA polymerase II   transcription factor activity, sequence-specific DNA binding

Thanks, Pascale

**Comment by bmeldal** [comment]
I have 20 complexes to review (see comment on obsoletion ticket.), https://github.com/geneontology/go-ontology/issues/15538

**Comment by asangrador** [comment]
InterPro annotations are done.

**Comment by ukemi** [comment]
Assigning to @krchristie for MGI.

**Comment by RLovering** [comment]
BHF done

**Comment by suzialeksander** [comment]
@pgaudet, are the child terms of  GO:0000989 transcription factor activity, transcription factor binding also being removed? I saw a closed ticket mentioning the Pol II child would likely be removed, and I don't want to annotate that if it's going away soon.  Thanks!

**Comment by pgaudet** [comment]
@suzialeksander 

Some terms will get removed, yes. For me it's OK if you want for these other changes before re-annotating.

Thanks, Pascale

**Comment by pgarmiri** [comment]
The EBI UniProt annotation have been reviewed and changed. The SIB curator have been contacted. The ISS annotations will be updated automatically when all the master annotations are fixed.

**Comment by pgaudet** [comment]
Term has been obsoleted - annotation will show up in reports.
