### ISSUE TITLE
Which annotation validation rules are currently implemented? (e.g Taxon checks are not running)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1928]
We are a bit confused about which checks are currently running/not running.
I have reported the absence of taxon checks in a few ticketes (related to PAINT and other annotation outliers)

midori just inserted some errors into our files and reported back that
" It also reported using 14 rules for annotation validation ... of 23 documented. The taxon check, rule 13, appears to be one of the ones that's not used."

 v

**Comment by ValWood** [comment]
added "bug" for taxon checks....

**Comment by pgaudet** [comment]
@cmungall @dougli1sqrd 
Can we clean up the rules documentation for the GOC meeting ? I'm happy to help of needed. 

Thanks, Pascale

**Comment by ValWood** [comment]
Are taxon constraints back
https://github.com/geneontology/go-ontology/issues/15701

**Comment by ValWood** [comment]
Taxon constraints don't appear to be implemented...

There are lots of annotations to "multicellular organismal process" for fungi  in GO/AmiGO (1511)

**Comment by ValWood** [comment]
and locomotion (92)

**Comment by pgaudet** [comment]
It is a known issue that taxon checks are not running, see https://github.com/geneontology/go-site/issues/660

Hopefully this can be fixed soon, I agree this is critical.

**Comment by ValWood** [comment]
It's driving me crazy :)

**Comment by selewis** [comment]
Me too. The taxon checks are needed in three places #1 in PAINT, #2 in Huaiyu's code when he is staging the PAINT releases, and #3 in the primary pipeline.

The first two can't happen until @mugitty (Anushya) and @huaiyumi move their code into github. Help us motivate them please!

**Comment by selewis** [comment]
Everything - taxon checks need to be resuscitated.

**Comment by pgaudet** [comment]
This ticket should be subsumed by https://github.com/geneontology/go-site/issues/670

But first, taxon checks are high priority. @dougli1sqrd @cmungall how soon can the be re-instated?

**Comment by ValWood** [comment]
What is the current status of taxon checks? Are they all running now? Is this ticket still required?

**Comment by ValWood** [comment]
duplicate of  geneontology/go-site#670
but  if taxon check not implemented, ho long will they take?

**Comment by pgaudet** [comment]
There are reports for taxon rules violations in the 'reports' files but I am not sure they are correctly implemented, see https://github.com/geneontology/go-site/issues/734

Pascale

**Comment by pgaudet** [comment]
I think this can be closed.
