### ISSUE TITLE
Review annotations to cytolysis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1929]
Hello, 

For https://github.com/geneontology/go-ontology/issues/13041
We will obsolete 

**Cytolysis in other organism** 

 https://docs.google.com/spreadsheets/d/1Zmiv_PBpYUob4_Lnr3DVIU8KOT7x-rfL1aBYdpqgDaI/edit#gid=0

1. GO:0051715 cytolysis in other organism: 43 EXP

CACAO @sandyl27
CAFA @ggeorghiou 
CGD  @marekskrzypek
EcoCyc @keseler 
FlyBase @hattrill 
UniProt @ggeorghiou 

2.  GO:0051710 regulation regulation of cytolysis in other organism : 0 annotations

3. GO:0051713 negative regulation of cytolysis in other organism: 2 annotations
PseudoCap @brinkmanlab

4.  GO:0051714 positive regulation of cytolysis in other organism: 3 annotations 
Uniprot @ggeorghiou 

----
**GO:0051801   cytolysis in other organism involved in symbiotic interaction**
2 manual annotations
https://docs.google.com/spreadsheets/d/1YxmtN_VyLYAeBD0ulBfTR03kelZTvoDSMq3-s_ji3RA/edit#gid=0
UniProt @ggeorghiou 

(no annotations to regulation children)

----
**Obsolete regulation of cytolysis** 
https://docs.google.com/spreadsheets/d/1HTN9ABIw2YhFzs5O31JsQa3mtUJKzThIYx62dX_K5ts/edit#gid=0

1. GO:0042268 regulation of cytolysis : 6 manual annotations

CGD @marekskrzypek
UniProt @ggeorghiou 

2. GO:0045919 positive regulation of cytolysis : 53 manual annotations

AgBase @jinhuiz
BHF-UCL @RLovering 
UniProt @ggeorghiou 

3.  GO:0045918 negative regulation of cytolysis: 19 manual annotations

AgBase @jinhuiz
BHF-UCL @RLovering 
CACAO @sandyl27
MGI @hdrabkin 
UniProt @ggeorghiou 

----
**Add DO NOT ANNOTATE flag on the parent cytolysis.** 
88 manual annotations 
https://docs.google.com/spreadsheets/d/1HTN9ABIw2YhFzs5O31JsQa3mtUJKzThIYx62dX_K5ts/edit#gid=0

AgBase  	@jinhuiz
BHF-UCL @RLovering 
CACAO  @sandyl27
CAFA @ggeorghiou 
EcoCyc @keseler 
MGI @hdrabkin 
PseudoCAP
RGD @slaulederkind 
UniProt @ggeorghiou 
JCVI & TIGR

Please review your annotations:

**Comment by slaulederkind** [comment]
RGD annotations have been removed.

**Comment by sandyl27** [comment]
CACAO annotations have been done.

**Comment by hdrabkin** [comment]
MGI done

**Comment by ggeorghiou** [comment]
UniProt mostly done. @sylvainpoux when you have a chance can you have a look at the ones that I have not marked? They are SIB specific annotations that I do not have access to.

**Comment by sylvainpoux** [comment]
Done
Sylvain
PS: these tables are really not convenient and we lose a lot of time to retrieve entries: depending on the organism, I have to search for the UniProt entry from the MGI or RGD accession and then load annotations etc. It takes time

**Comment by RLovering** [comment]
FYI I tend to extract the PMID from the table and use that to search for the annotations to revise, the PMID is a bit hidden in ref column but it is there eg MGI:MGI:5897756|PMID:16931762
Hope that helps
Ruth

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
Out of date, I'll open a new ticket for remaining annotations
