### ISSUE TITLE
 IPR014752 signalling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1930]
I'm not super-confident about this, but I'm not convinced that all "arrestin" family members have a role in "signalling".
although wikepedia supports such a role
https://en.wikipedia.org/wiki/Arrestin
It might not always be true.

If they are "endocytic adaptors". It follows that if they  may have a more general role in endocytosis, they are only involved in signalling when they are endocytosing "receptors" or other signalling pathway components...

So we would need to be sure about the target molecules to make this annotation?

**Comment by ValWood** [comment]
I found this member
https://www.pombase.org/gene/SPAC4G9.13c
vps26 is a retromer complex subunit involved in retrograde transport, endosome to Golgi

so here "signalling" isn't right...

**Comment by asangrador** [comment]
You are right, this entry matches vps26 proteins and should not have the "signalling" annotation. It has been removed  now.
