### ISSUE TITLE
GPI1 gene  of S cerevisiae should be CONTRIBUTES TO pentose phosphate shunt

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#1931]
From the GO page of glucose-6-phosphate isomerase:
http://amigo.geneontology.org/amigo/gene_product/SGD:S000000400
We see this gene involved in glycolysis and gluconeogenesis, which is true in both cases.
There is genetic data showing that a GPI1 gene can affect the pentose-phosphate shunt as well https://www.ncbi.nlm.nih.gov/pubmed/7901008
However, this is because some metabolites are shared between the pathways, and not because GPI1 is part of the well-characterized pentose-phosphate shunt.  We should therefore change it to CONTRIBUTES TO pentose phosphate shunt.

**Comment by ValWood** [comment]
Contributes_to is only for use with molecular function.

It seems that the annotation maybe should be removed.

@srengel ? 
val

**Comment by srengel** [comment]
wait, @ValWood , i'm confused.  seems like the suggestion is to add 'contributes_to pentose-phosphate shunt'. which annotation are you suggesting that i remove?

**Comment by ValWood** [comment]
I'm saying you can't add contributes_to to this annotation  'pentose-phosphate shunt'
because contributes_to is only valid with MF annotation.

but it seems that "Glucose-6-phosphate isomerase" isn't really part of the "pentose-phosphate shunt", so I wouldn't make this annotation?
https://en.wikipedia.org/wiki/Pentose_phosphate_pathway

.....although I have by ISS, I'm deleting it now;)

**Comment by srengel** [comment]
yeah i saw this ticket when it first came through and was not planning to take any action on it.  meaning, i'm not planning to add that p-p shunt annot.

**Comment by ValWood** [comment]
It already has it in SGD (and I made a ISS) , but it needs removing?
v

**Comment by srengel** [comment]
wait, i thought this ticket was about GPI1?

**Comment by srengel** [comment]
ugh.  PGI1.  sure i can remove this annotation.  seems like PGI1 is too upstream of p-p shunt.

**Comment by ValWood** [comment]
http://amigo.geneontology.org/amigo/gene_product/SGD:S000000400

GPI is a general abbreviation for  
glucose-6-phosphate isomerase
(sorry, this got  very confusing!)

**Comment by ValWood** [comment]
OK you got it ;)
