### ISSUE TITLE
PANTHER:PTN001999424 not DNA replication  checkpoint

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1933]
PANTHER:PTN001999424 has DNA replication  checkpoint
from P34252 SGD=S000001591|UniProtKB=P34252

for pombe  Drc1
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=O14216
via

(this is an IMP annotation from an old paper, but it shows the problem with making process annotation only from phenotypes and genetic interaction).

Paul Russell (DNA damage checkpoint expert:)
Drc1 is essential for DNA replication and thus when it is deleted or otherwise completely inactivated cells will divide with a cut phenotype. The phenotype is very similar to deletion of cdc18. The cut phenotype is often associated with a checkpoint defect but in this case it can be misleading, as the checkpoint can be activated only when cells are in the process of replicating their DNA. We hedged our bets to say that Drc1 might be involved in the replication checkpoint, but most likely it has no role in checkpoint detection or signaling per se. 

So at PomBase because we  most likely it does not have a role, we made a conscious decision not to make this particular annotation.

If SGD want to keep this particular annotation I suggest that we just don't transfer the annotation to other species in the short term without additional data.

**Comment by ValWood** [comment]
The SGD description looks good
Description
Single-stranded DNA origin-binding and annealing protein; required for initiation of DNA replication; phosphorylated in S phase by cyclin-dependent kinases (Cdks), promoting origin binding, DNA replication and Dpb11p complex formation; component of the preloading complex; binds the Mcm2-7p complex to prevent inappropriate Mcm2-7p interaction with the GINS complex in G1; required for S phase checkpoint; relative distribution to the nucleus increases upon DNA replication stress

So I would say :
DNA replication initiation 
mitotic DNA replication preinitiation complex assembly S
DNA strand renaturation 

this also fits with PomBase annotation. 

double-strand break repair via break-induced replication
also seems OK (Sld2)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2878651/
e conclude that the Dpb11–Sld3–Sld2 complex is required for the initiation of new BIR synthesis, most likely by recruiting Cdc45 and the GINS complex to the assembling replication machinery at the BIR template.

**Comment by ValWood** [comment]
so just not  to transfer the checkpoint annotation.

**Comment by pgaudet** [comment]
OK done, thanks
