### ISSUE TITLE
Review annotations to GO:0006987 activation of signaling protein activity involved in unfolded protein response & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1934]
Dear all, 

We have proposed to obsolete GO:0006987 activation of signaling protein activity involved in unfolded protein response & children, see https://github.com/geneontology/go-ontology/issues/11656

Please review your annotations to the following terms: 

- GO:0006987 | activation of signaling protein activity involved in unfolded protein response
https://docs.google.com/spreadsheets/d/13lAqPfk12q2ZJPsNVY_bCR-k_IUGevREBmtKnNypHP4/edit#gid=0
** TAIR @tberardini 
** BHF-UCL @RLovering 
** UniProt @ggeorghiou 

* GO:0030969 | mRNA splicing via endonucleolytic cleavage and ligation involved in unfolded protein response
https://docs.google.com/spreadsheets/d/1Zmt5TYR0UMuFYTzMiG6QmZR7l7p5GtaL1apec_fuTjs/edit#gid=0
** ParkinsonsUK-UCL @RLovering 
** SGD @suzialeksander 
** WB @vanaukenk 

* GO:0070055 | mRNA endonucleolytic cleavage involved in unfolded protein response
https://docs.google.com/spreadsheets/d/1xvLrcJc39n9-5EVleibvbgYDOKAGdS1qGrXjzo2aZdc/edit#gid=0
** AspGD
** FlyBase @hattrill 
** ParkinsonsUK-UCL @RLovering 
** UniProt @ggeorghiou 
** WormBase @vanaukenk 

* GO:1904721 | negative regulation of mRNA endonucleolytic cleavage involved in unfolded protein response
https://docs.google.com/spreadsheets/d/1CXzoDGmDj_UV6x5a0H8ZSmWybmqnj9D8CCjv67UM6Dk/edit#gid=0
** ParkinsonsUK-UCL @RLovering 

* GO:1904722 | positive regulation of mRNA endonucleolytic cleavage involved in unfolded protein response
https://docs.google.com/spreadsheets/d/1YDDII0cYnjHq-WSAVjVCU5XCwyPLqubN5URiNuugxCU/edit#gid=0 
** ParkinsonsUK-UCL @RLovering 

* GO:1904720 | regulation of mRNA endonucleolytic cleavage involved in unfolded protein response
No annotations.

**Comment by tberardini** [comment]
TAIR annotation reviewed and removed.

**Comment by pgaudet** [comment]
Hi, 

We still need UniProt, BHF and Wormbase to look at their annotations
 @ggeorghiou @RLovering @vanaukenk

**Comment by pgaudet** [comment]
(note that the terms are already obsoleted !)

**Comment by RLovering** [comment]
all done

**Comment by vanaukenk** [comment]
Marie-Claire (@mcharrison345) and I fixed all of the WormBase annotations.

**Comment by pgarmiri** [comment]
All UniProt experimental annotations have been updated apart from one that is pending as I just email the SIB curator. The spreadsheets have been updated accordingly. ISS annotations will be updated automatically to mirror the changes of the experimental annotations.
