### ISSUE TITLE
PTHR 12302 PANTHER:PTN000266556

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1936]
for
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC19F8.04c

has 

RNA catabolic process
from a TUDOr domain protein
http://www.uniprot.org/uniprot/Q9FLT0#family_and_domains
http://www.uniprot.org/uniprot/Q8VZG7#ptm_processing

via PANTHER:PTN000266556

but  SPBC19F8.04c does not have a TUDOr domain

**Comment by pgaudet** [comment]
We don't see that annotation in PAINT anymore, so I will close this but ask @huaiyumi why there is a discrepancy. 

Thanks, Pascale

**Comment by ValWood** [comment]
I think nuclease is OK
http://pfam.xfam.org/family/PF00565#tabview=tab2
but from phenotypes this is most likely a DNA nuclease in vivo

**Comment by ValWood** [comment]
(...but will probably degrade both in vitro... I'd usually want to see some physiological context to transfer a process).

**Comment by thomaspd** [comment]
That makes sense to me.  @marcfeuermann could you please decide on the best way to annotate evolution of RNA vs DNA specificity in this family?

**Comment by ValWood** [comment]
For yeast I would not transfer any process info, not all of the ortholog predictors agree with Panther here:

https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPBC19F8.04c

**Comment by marcfeuermann** [comment]
The family contains an ancient duplication at the origin of the eukaryotes, leading to 2 nodes, PTN000266557 and PTN001265932. I propose to keep "RNA catabolic process" for PTN000266557. I would believe that PTN001265932 is rather involved in DNA degradation (as suggested by Val) but as the evidences are weak, I would not annotate this part of the tree to DNA catabolism. Nuclease activity stays at the root.
Again, if you agree with my correction (or not), let me know to close this issue.

**Comment by ValWood** [comment]
I agree, I would leave the unknown branch with no annotation, it's purely speculation by me ;)
