### ISSUE TITLE
PTN002001475 	PANTHER:PTN000000084	 mappings to "function in process" terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1937]
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC31H12.02c

maps one of PomBase "process unknown" to

negative regulation of ATPase activity

....this isn't really describing any particular process.

Could we avoid inferences to "regulation of activity?"

It comes from a single annotation 
P25619
which looks very indirect (as a result of expression)
 Plasma membrane H(+)-ATPase activities of heat shocked and weak acid-adapted, hsp30 mutant and wild-type cells, revealed that Hsp30 induction leads to a downregulation of the stress-stimulation of this H(+)-ATPase.

**Comment by ValWood** [comment]
Similarly PANTHER:PTN000000084

annotates an  "unkown process" phosphatase to 
"dephosphorylation"

**Comment by pgaudet** [comment]
PTN000000084
-> annotated by PAINT to MF: phosphatase activity. This is also supported by 3 papers as well as by domains. 
The process dephosphorylation is a MF-> BP link. So, this is outside the scope of PAINT. 

----

**Comment by ValWood** [comment]
OK, this will be dealt with by us internally, can close this.

**Comment by pgaudet** [comment]
PTN002001475
-> PTHR28286
Removed propagation of negative regulation of ATPase activity

Thanks, Pascale

Thanks, Pascale

**Comment by ValWood** [comment]
reopened for 
negative regulation of ATPase activity
(slightly different issue)

**Comment by pgaudet** [comment]
what's the issue ??

**Comment by ValWood** [comment]
ignoe you did it!
