### ISSUE TITLE
PANTHER:PTN000659780 Rhodopsin does not bind neuropeptides

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#1941]
Rhodopsin with neuropeptide GPCR annotations:please block propagation

FBgn0036260 Rh7
PANTHER:PTN000659780
-neuropeptide signaling pathway
-neuropeptide binding

**Comment by pgaudet** [comment]
Thanks @hattrill 
With @marcfeuermann we added a NOT on the node PTN002796263

Thanks, Pascale

**Comment by pgaudet** [comment]
To help us: If the primary annotation had had a NOT, we would have be alerted to the loss of function in this node. 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes I think the PAINT NOTs are different from the NOTs we make during manual curation. We would not want to import the NOTs....
v

**Comment by pgaudet** [comment]
@hattrill @ValWood 
What I was trying to say is that Flybase could have annotated a NOT 'neuropeptide signaling pathway' to FBgn0036260 Rh7 (if that data was available), this way we would have more easily seen it in the family. It's a relatively large family where most other members *do* have this function. 

It was just a suggestions for primary annotations to help us PAINT. 

That being said, we used IRD, which should not results in a visible NOT annotation (according to the specs, I don't know how this is implemented anymore).

Thanks, Pascale

**Comment by hattrill** [comment]
As long as it is an IRD and it won't be visible that is exactly what we want. We need to make sure that the specs match the output.

Although a class A GPCR, Rhodopsin 7 is part of a sub-family rhodopsins/opsins well-known to be light-activated GPCRs, so we couldn't add a NOT as there's nothing to suggest it would have a neeuropeptide binding activity (Panther calls excluded).

**Comment by pgaudet** [comment]
OK, thanks !
