### ISSUE TITLE
Review Annotation to GO:0031012, extracellular matrix

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#1943]
Please review your annotations to extracellular matrix. We have created a new term collagen-containing extracellular matrix. Most, if not all, metazoan annotations to the parent term should be reannotated to this term. 

The spreadsheet for re-annotation can be found here:

https://docs.google.com/spreadsheets/d/1K2gWfmAKVu5v6xV-jcdAcYjHZUuQVV4sOMBOusvJXH0/edit#gid=0

**Comment by rachhuntley** [comment]
Can you please share the spreadsheet?

**Comment by ukemi** [comment]
Hi @rachhuntley. I just moved it to the appropriate folder. You should be able to get to it now. Sorry!

**Comment by rachhuntley** [comment]
Hi @ukemi, I think the spreadsheet is a little messed up. I can't find any BHF-UCL annotations and I know we have around 300. It also looks odd as MGI have lots in the spreadsheet but in AmiGO I'm only seeing 3. I think maybe the assigned by column is actually the DB column?

**Comment by ukemi** [comment]
OK. I will have another try at making the spreadsheet.

**Comment by ukemi** [comment]
Should be fixed now! Thanks @rachhuntley!

**Comment by rachhuntley** [comment]
Great, thanks. Also AgBase have some annotations, but I can't see Fiona McCarthy on GitHub.

**Comment by rachhuntley** [comment]
All BHF-UCL annotations are now updated.

**Comment by tberardini** [comment]
Do the plant ECM annotations need reviewing, @rachhuntley ?  It sounds like the metazoan ones do as they would most likely move to collagen-containing ECM.  Can I leave the _A. thaliana_ ones where they are or did you envision them moving to a more specific term as well?  If so, which one?  Neither 'biofilm matrix' nor 'organomineral ECM' is quite right.

**Comment by hattrill** [comment]
Most of the FlyBase ones are done. I have a few things to chase down: dendritic cap, cuticle composition. Will do these later.

**Comment by pfey03** [comment]
@ukemi Since Dicty is not a metazoan but a protozoan, but has an extracellular matrix and even a family of genes named for it, can I just leave the annotations? There are 5 EXP and they seem ok. Thanks!

**Comment by ukemi** [comment]
Hi @pfey03,
Yes. This seems reasonable. Thanks for checking. Do you think we need an additional subclass for the type of ECM found in dicty?

**Comment by pfey03** [comment]
I would need to look more in detail but am grant writing and other urgent things. But I keep it in mind. If we would need new terms we request when more into the matter through newer papers or such.

Thanks @ukemi !
Petra

**Comment by vanaukenk** [comment]
The two WB annotations have been reviewed; one removed and one changed.

**Comment by rachhuntley** [comment]
Hello all,
We would like to try to finish up the extracellular matrix project soon, and there are still quite a number of annotations that need to be reviewed.
This review should be quick to do: we have created a new term collagen-containing extracellular matrix (GO:0062023) and most, if not all, metazoan annotations to 'extracellular matrix' should be reannotated to this term. It should, therefore, be simple to update your annotations automatically by looking for the combination of taxon ID and GO ID. Those using Protein2GO - Tony has already done this with the BHF-UCL annotations.

As a summary, these are the counts of annotations for each group:
UniProt/CAFA/DFLAT - 114
RGD - 35
AgBase - 27
ZFIN - 2
IntAct/Complex Portal - 1

Thank you!
Rachael and David.

**Comment by rachhuntley** [comment]
AgBase review done by Fiona McCarthy.

**Comment by slaulederkind** [comment]
RGD review is finished.  No write access to Google spreadsheet disallowed recording of changes on appropriate lines.

**Comment by bmeldal** [comment]
complexes done (there were more than one!)

**Comment by pgarmiri** [comment]
Hi, 
All the UniProt EBI annotations have been reviewed and the spreadsheet undated. I have labeled the SIB annotations that I can't change, with a tag at the end of the relevant lines.  @sylvainpoux could you look into them?
Thanks,
Penelope

**Comment by sylvainpoux** [comment]
Done for UniProt SIB

**Comment by ukemi** [comment]
@sabrinatoro  Can you have a look at the ZFIN annotations?

**Comment by sabrinatoro** [comment]
@ukemi 
I have reviewed the ZFIN annotations.
