### ISSUE TITLE
InterPro mappings to GO:0031012 extracellular matrix

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-annotation#1944]
We have created a new term GO:0062023 collagen-containing extracellular matrix. Most, if not all, metazoan annotations to GO:0031012 extracellular matrix should be reannotated to this term.

Could you please check your mappings to see whether any can be moved to this more specific term?
e.g. http://www.ebi.ac.uk/interpro/entry/IPR033078/taxonomy looks like it can be re-mapped.

Thanks,
Rachael.

Part of ontology project https://github.com/geneontology/go-ontology/projects/9

**Comment by EBI-Hsinyu** [comment]
Hi Rachael, 

I have replaced the GO:0031012 term with the new term GO:0062023 in several InterPro entries. This will be visible in InterPro 69.0. 

Regards,
Hsin-Yu

Terms replaced in:
IPR032973
IPR033079
IPR037286
IPR037641
IPR013275
IPR013276
IPR013277
IPR030705
IPR030751
IPR030763
IPR027118
IPR033081
IPR033078
IPR001863
IPR027216
IPR037640
IPR027215
IPR027219
IPR003979
IPR004116
IPR033026
IPR016359
IPR011398
IPR030743

**Comment by rachhuntley** [comment]
Hi Hsin-Yu,
That's great, thanks for doing this so quickly!

Regards,
Rachael.
