### ISSUE TITLE
transcription annotation breakdown

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1947]
Following  on from the annotation call, I did a quick review of  fission yeast transcription annotation:

Total , in our slim 468 today
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

breakdown:
![txn](https://user-images.githubusercontent.com/7359272/39386450-954c943e-4a6c-11e8-97e6-27a4e96c8b70.jpg)

This is pretty trivial to do (for us, but you need a Kim  @kimrutherford ) to make you one of these:
https://www.pombase.org/query

Without a Kim, maybe somebody can make the GOOSE SQL queries? if this is a useful exercise?
(PS. all of our website code is generic/freely available)

**Comment by ValWood** [comment]
![txn](https://user-images.githubusercontent.com/7359272/39386450-954c943e-4a6c-11e8-97e6-27a4e96c8b70.jpg)

**Comment by ValWood** [comment]
Interestingly only 36 of the 86 we had annotated to 
https://www.ebi.ac.uk/QuickGO/term/GO:0003712

**Comment by ValWood** [comment]
currently

![txn](https://user-images.githubusercontent.com/7359272/39831678-1f5423dc-53bd-11e8-97f1-c05350ffeb91.jpg)

**Comment by RLovering** [comment]
nice !

**Comment by ValWood** [comment]
@RLovering @pgaudet  what did we say that CCR4-NOT was? co-regulator?

**Comment by ValWood** [comment]
This is a matix view of most of the major activities intersected with conserved transcription complexes. The annotation errors stand out. Unfortunately, I can't access them right now

![transcription overview](https://user-images.githubusercontent.com/7359272/75373711-b9a94780-58c2-11ea-81d1-8e51e5397774.jpg)

**Comment by ValWood** [comment]
@Antonialock  this transcription overview would be a nice example for your Matrix talk at UniProt. it's one everyone should be able to understand.  and instead of process/process it's mainly MF/CC

it will help to pick out  DNA binding TFs annotated as general transcription factors and the like.

**Comment by pgaudet** [comment]
I think CCR4-NOT is a co-regulator. 

@colinlog is this right ??

**Comment by Antonialock** [comment]
> 
> 
> I think CCR4-NOT is a co-regulator.
> 

I saw this comment while looking at a 2017 paper. In it they say:

Ccr4-Not is a conserved complex involved in RNA surveillance, transcription elongation,RNA export, and DNA repair (Collart and Panasenko 2012; Millerand Reese 2012; Wahle and Winkler 2013; Inada and Makino2014). The Ccr4-Not complex is the primary deadenylase and isessential for downstream decapping and mRNA decay by Xrn1(Schizosaccharomyces pombe: Exo2), a conserved 5′-3′exoribonu-clease (Collart and Panasenko 2012; Miller and Reese 2012). Caf1and Ccr4 build the deadenylase module of Ccr4-Not, whileNot1, Not2, Not4 (S. pombe: Mot2), and Not5 belong to the Notgroup of the complex. Caf1 bridges Ccr4 to Not1 and is essentialfor the deadenylation activity (Basquin et al. 2012)

**Comment by ValWood** [comment]
@colinlog  is the involvement in elongation direct?

the annotation I have so far

caf1 and caf4 poly(A)-specific ribonuclease activity
mot2 E3 ubiquitin ligase
rcd1 RNA binding

but it's role seems downstream of elongation?

**Comment by colinlog** [comment]
This complex has most definitely mRNA metabolism MFs.
For transcription itself it is lnt as obvious. Martine Collart http://www.ige3.unige.ch/collart.php worked a lot on this complex and claims RNA polymerase II regulation. Hence, the co-TF annotation of CCR4-NOT could rely on her published work. This complex may consist of multiple variants?
Shall we ask Martine what she would recommend GO do in terms of annotating s.p and other eukaryotes, such as H.s???

**Comment by ValWood** [comment]
Yes it would be good to know if the elongation part is now considered to be indirect.

**Comment by ValWood** [comment]
The page suggests some sort of chaperone role.

**Comment by pgaudet** [comment]
@ValWood 
What do we need to do here ?

**Comment by ValWood** [comment]
We can close. I think I thought this was on the PomBAse tracker. I tried to transfer it but it isn't possible to move between GO-> PomBase repositories.
 But  we can do some annotation rules  at some point. We can maybe look at the matrix intersections on a transcription call at the end of the transcription review?

**Comment by colinlog** [comment]
Yes Val, Pascale has just initiated this type of 'sanity checks' for the human dbTFs as we have now frozen the dbTF list. Of course that list will still evolve over time, but it is hopefully very poor in false positives. The matrixintersection could be one of the starting points for the upcoming coTF/coregulator annotation/refactoring review, which may take several years and will involve the complex portal, hopefully.
