### ISSUE TITLE
IPR000182 not histone acetyltransferase

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1949]
At least ELP3 (Q9H9T3) is not a histone acetyltransferase

See discussion in https://github.com/geneontology/go-annotation/issues/1806

Thanks, Pascale

**Comment by happy-lorna** [comment]
This GO term has already been removed, and ELP3 is not mentioned specifically in the description. Is there still a problem with this?

**Comment by pgaudet** [comment]
No - perhaps we were looking at out-of-date data. 

Thanks !
