### ISSUE TITLE
PANTHER:PTN000361179 various

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1951]
from 
https://github.com/geneontology/go-annotation/issues/1873

for pombe
https://www.pombase.org/gene/SPBC23E6.09
SSn6 is a co repressor, it  does nto bind to DNA directly (it only has TPR domains)
It does not have histone demethylase activity (most likely involved in recruitment)
It is *associated* with active promoters, but does not bind to them directly

PANTHER:PTN000361179   need removing (I suspect this is an issue with the primary annotation rather than the PAINT process?

sequence-specific DNA binding
chromatin DNA binding
histone demethylase activity (H3-K27 specific)
RNA polymerase II proximal promoter sequence-specific DNA binding
transcriptional activator activity, RNA polymerase II transcription factor binding

**Comment by thomaspd** [comment]
These have been fixed, and only "transcription repressor complex" annotations remain for this pombe gene and its yeast ortholog, CYC8.  The family has two distinct subfamilies, separated by a gene duplication at the root of the tree.  One subfamily contains this pombe gene and its yeast ortholog (and orthologs in other organisms), and seems to have proteins with just TPR repeats.  The other subfamily includes human KDM6A, and other genes that also have a Jumanji domain that has the catalytic activity.  Only the latter subfamily is annotated with the terms listed above.
