### ISSUE TITLE
PTN000029440 coatomer gamma subunit sec21

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1960]
from
https://github.com/geneontology/go-annotation/issues/1873

http://www.pantree.org/node/annotationNode.jsp?id=PTN000029440

coatomer gamma subunit Sec21

is annotated to 
"organelle transport along microtubule"
primary annotation may need to be addressed?

**Comment by ValWood** [comment]
sec21 isn't involved in the transport although maybe in some species the vesicles are moved along microtubules? (not in fission yeast)

**Comment by ValWood** [comment]
Annotation id from RAT|RGD=1565292|UniProtKB=Q4AEF8

@slaulederkind  could you check, if this looks OK, @pgaudet  can restrict the annotation to the correct clade.
Thanks
Val

**Comment by slaulederkind** [comment]
Based on PMID:20525016, it looks like "organelle transport along microtubule" is appropriate for rat Copg1.

**Comment by ValWood** [comment]
Yep, OK. @pgaudet  can you block transfer  to yeast (at least I think this is the case), @srengel ?

If not, just for pombe. 

(in pombe the Golgi are not connected to the centrosome/SPB)

**Comment by ValWood** [comment]
thanks.
@pgaudet  can you restrict the  propagation?
thanks
val

**Comment by srengel** [comment]
sorry guys, i'm not sure exactly what is being requested.  our SEC21 is annotated to

- ER to Golgi vesicle-mediated transport (IMP)
- retrograde vesicle-mediated transport, Golgi to ER (IMP)

i can't get that pantree URL to load, it just hangs as an empty page.

**Comment by ValWood** [comment]
Sorry I wasn't clear!

Do you agree that  the term 
"organelle transport along microtubule" should not be transferred from metazoa for fungi for sec21?  
https://www.ncbi.nlm.nih.gov/pubmed/20525016

I want to block the transfer to fission yeast.

Thanks
Val

**Comment by srengel** [comment]
Ok thank you.  I looked at this more, and yes I agree that the term
"organelle transport along microtubule" should not be transferred from metazoa to fungi for sec21.

**Comment by thomaspd** [comment]
@marcfeuermann can you please consider how this PAINT annotation should change?  One possibility would be to change the ancestral node where "organelle transport along microtubule" is gained, to be in the metazoa (or metazoa-choanoflagellida), so this term is not inferred for fungi.

**Comment by marcfeuermann** [comment]
If I understand well you would like to remove "organelle transport along microtubule"  from fungi, but keep "ER to Golgi vesicle-mediated transport" and "retrograde vesicle-mediated transport, Golgi to ER" ? If it's not transport, don't you think all have to be removed ? Or do fungi not use microtubles for the transport but another way ? I can go through the literature, but if you aleady have the answer, let me know to gain time.

**Comment by ValWood** [comment]
So in fungi organelles may transport along microtubules but we have no data about this, I have sometimes asked people and it isn't really clear if the proteins transported along microtubules are in vesicles or are direct cargo.

But even if they are in vesicles I don't think we can infer sec21 in this process.

This coat, as far as I'm aware in fission yeast only occurs as part of vesicle-mediated transport (trafficking)

In fact the general role of COPi is in the transport(trafficking) of vesicles from the ER to the GOllgi
https://en.wikipedia.org/wiki/COPI

(this  process isn't microtubule-mediated)

**Comment by marcfeuermann** [comment]
Thanks Val for this precision. I was first tempted to remove the annotation from the tree, but there is PMID:20525016 which, in my opinion, shows quite clearly that microtubule-dependent Golgi positioning requires  the coatomer. So I would follow Paul's suggestion to  change the ancestral node where "organelle transport along microtubule" is gained, to be in the metazoa-choanoflagellida.
@ValWood if you agree, let me know to close this issue.

**Comment by ValWood** [comment]
I think tat makes sense
