### ISSUE TITLE
PTN000212047 sulphate transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1962]
https://github.com/geneontology/go-annotation/issues/1873

not enough information to make these inferences (transport inferences are dangerous across species, because substrates change but to the best of our knowledge this is a sulfate transporter)

- [x] SPCC320.05	sulfate transmembrane transporter (predicted)		regulation of intracellular pH		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
- [x]  SPCC320.05	sulfate transmembrane transporter (predicted)		bicarbonate transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
- [x]  SPCC320.05	sulfate transmembrane transporter (predicted)		chloride transmembrane transport		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000212047			PAINT_REF:11814	20170427
- [x]  SPCC320.05	sulfate transmembrane transporter (predicted)		oxalate transport

**Comment by pgaudet** [comment]
But sulfate transmembrane transporter is OK for this entire family ?

**Comment by ValWood** [comment]
I don't know....
It's a big family ....I don't think I would transfer across to fungi because specificities change. I'm not even suer the pombe one should be annotated to sulphate. That comes from

http://pfam.xfam.org/family/PF00916
and
http://www.ebi.ac.uk/interpro/entry/IPR001902
the interPro family maps to sulphate and most characterized members are sulphate transporters

**Comment by ValWood** [comment]
IPR001902 maps to 
GO:0008271 secondary active sulfate transmembrane transporter activity 

so presumably they believe this to be true for all members

**Comment by thomaspd** [comment]
I just checked and none of the original questionable annotations appear in AmiGO.  Sulfate transport remains as a PAINT annotation, and I think, based on the agreement with InterPro annotation, that we can keep it.
