### ISSUE TITLE
Functional information about UniProtKB - Q72P16 (Q72P16_LEPIC) and UniProtKB - Q72PB3 (Q72PB3_LEPIC)

### ISSUE THREAD

**Issue by APYLopes** [geneontology/go-annotation#1963]
I would like to request you to include new experimental data about the function of the proteins below, 
first annotated in 2004. This new informations were published on PLOS one under the title: “VapC from the leptospiral VapBC toxin-antitoxin module displays ribonuclease activity on the initiator tRNA.” PLoS One. 2014 Jul 21;9(7):e101678. doi: 10.1371/journal.pone.0101678. PMID: 25461800.
Please let me know if I'm running this query correctly. Thank you very much. 
Best regards,
Alexandre Paulo Yague Lopes, PhD 
Scientific Researcher – Instituto Butantan – SP-Brazil
Email: alexandre.lopes@butantan.gov.br

Q72P16 (Q72P16_LEPIC)
Protein: Toxin VapC
Gene: vapC
Organism: Leptospira interrogans serogroup Icterohaemorrhagiae serovar copenhageni (strain Fiocruz L1-130)
Function: It is the toxic component of VapBC module, a type II toxin-antitoxin (TA) system. It cleaves tRNA-(fMet) in the same way that the tRNA(fMet)-specific endonuclease VapC from Salmonella typhimurium (UniProtKB - Q8ZM86 (VAPC_SALTY)) does. It does not present any non-specific activity in relation to E. coli rRNA. The expression of the leptospiral VapC in E. coli promotes a strong bacterial growth arrestment, which is reversed by the expression of the antitoxin VapB.

Q72PB3 (Q72PB3_LEPIC)
Protein: Antitoxin VapB
Gene: vapC
Organism: Leptospira interrogans serogroup Icterohaemorrhagiae serovar copenhageni (strain Fiocruz L1-130)

**Comment by pgaudet** [comment]
@pgarmiri Can you have a look at that ? 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi @pgaudet ,

That somehow got lost in my inbox.

I have now taken a look and curated the paper. The correct PMID is 25047537. It was straight forward apart for one little thing that might be an issue. 

The activity of this toxin is a GO:0004549 ' tRNA-specific ribonuclease activity' toward _E. coli_. However, this term is not under the  GO:0044419 'biological process involved in interspecies interaction between organisms'. 

1. I can't enter Interacting Taxon (I have put it in the 'toxin activity' annotation though)
2.  Could it be misleading, i.e. the activity being toward it's own tRNA? If yes, a new relation could be added to allow this?

Thanks,

Penelope

**Comment by APYLopes** [comment]
Hi Penelope.
I'm not sure I understand the question related to "new relation" well.
Anyway, the activity of the studied VapC toxin (LIC_12559) is towards its
own tRNA, which is a mandatory characteristic of the toxins of the
bacterial "toxin-antitoxin" systems (TA systems). It has exactly the same
activity described for  Shigella VapC UnoProtKB - O06662 (VAPC_SHIFL).
I hope it helps.
Thanks
Alexandre

*Alexandre Paulo Yague Lopes, Ph.D. – Pesquisador Científico*

*Laboratório **de Desenv. de Vacinas - Centro de Biotecnologia - Instituto
Butantan*


*Avenida Vital Brasil, 1500, 05503-000 – São Paulo, SP, Brasil Fone: 55 11
2627 9475 - ***@***.***
***@***.***>*


Em qui., 27 de mai. de 2021 às 09:59, pgarmiri ***@***.***>
escreveu:

**Comment by APYLopes** [comment]
Hi Penelope
Yes, I do agree with it.
Thank you for your work.
Kind regards.
Alexandre


*Alexandre Paulo Yague Lopes, Ph.D. – Pesquisador Científico*

*Laboratório **de Desenv. de Vacinas - Centro de Biotecnologia - Instituto
Butantan*


*Avenida Vital Brasil, 1500, 05503-000 – São Paulo, SP, Brasil Fone: 55 11
2627 9475 - ***@***.***
***@***.***>*


Em qui., 27 de mai. de 2021 às 17:48, pgarmiri ***@***.***>
escreveu:

**Comment by pgaudet** [comment]
Hi @pgarmiri 

Can this be closed?

**Comment by APYLopes** [comment]
Hi.
Yes, this can be closed.
thank you.
Alexandre

*Alexandre Paulo Yague Lopes, Ph.D. – Pesquisador Científico*

*Laboratório **de Desenv. de Vacinas - Centro de Biotecnologia - Instituto
Butantan*


*Avenida Vital Brasil, 1500, 05503-000 – São Paulo, SP, Brasil Fone: 55 11
2627 9475 - ***@***.***
***@***.***>*


Em seg., 31 de mai. de 2021 às 09:37, pgaudet ***@***.***>
escreveu:

**Comment by pgaudet** [comment]
Thank both!
