### ISSUE TITLE
new function for UNKNOWN protein (conserved yeast  to human)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1969]
Structural and biochemical characterization of the yeast HD domain containing protein YGK1 reveals a metal-dependent nucleoside 5'-monophosphatase.

 YGK1 (YGL101W) and YB92 (YBR242W) from Saccharomyces cerevisiae as nucleoside 5'-monophosphatases

PMID: 29752939

@suzialeksander   for primary annotation
@pgaudet for PAINT
@asangrador for InterPro mapping

**Comment by asangrador** [comment]
Thanks, I have create a new entry with this annotation.

**Comment by suzialeksander** [comment]
Done, thanks!

**Comment by suzialeksander** [comment]
Wow, thanks, updated.

**Comment by pgaudet** [comment]
thanks !
