### ISSUE TITLE
Review annotations to GO:0030820, GO:0030821, GO:0030822 regulation of cAMP catabolic process and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1971]
2 BHF annotations
GO:0030820 regulation of cAMP catabolic process will get obsoleted. 

https://docs.google.com/spreadsheets/d/1xv5oqSbWFDmTK5EKwFis7v2iWjoHjf_4f6KmnL-hTrk/edit#gid=0

@RLovering I admit I have not looked at the annotations, if you need help please let me know. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Annotations can be moved to 'GO:0051342 regulation of cyclic-nucleotide phosphodiesterase activity' or a child, if this is not already there. 

Thanks, Pascale

**Comment by RLovering** [comment]
All regulation annotations updated, and updated spreadsheet.
I look forward to hearing about the process term
Thanks
Ruth

**Comment by pgaudet** [comment]
> Please confirm whether the process term GO:0030822 CAMP catabolic process is also going to be obsoleted, and if so please stall this until we have reviewed the annotations

This is what I understood from the GOC meeting. @ValWood @vanaukenk @deustp01 @jimhu-tamu (anyone else) - can you please confirm ? 

To me this also applies to 'GO:0009187 cyclic nucleotide metabolic process' and direct children (cAMP, cGMP, metabolism, catabolism, biosynthesis). I don't see why we'd keep some and not the others.



Thanks, Pascale

**Comment by ValWood** [comment]
that's ok then.
