### ISSUE TITLE
IPR000151 Ciliary neurotrophic factor + growth ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1972]
Hi, 

It is possible to make a more precise mapping for the BP for IPR000151 Ciliary neurotrophic factor? 

We'd like to make 'growth' a 'do not annotate' term (see https://github.com/geneontology/go-ontology/issues/15742) 

Thanks, Pascale

**Comment by asangrador** [comment]
Hi Pascale,
I have removed 'growth' that is far too general and added more relevant terms.
