### ISSUE TITLE
Review annotations to 'growth'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1973]
Hello, 

We'd like to make 'growth' a 'do not annotate' term. Please review your annotations to make a more precise annotations: 
https://docs.google.com/spreadsheets/d/1olP2l-TJVaCXB4FDh-stCW5RepSjXiKxSpU37s8Z0lY/edit#gid=0

Contributor   (Assigned by) | Number of annotations | Curator
-- | -- | --
BHF-UCL | 1 | @RLovering 
FlyBase | 12  |  @hattrill 
GeneDB | 44  | @Achchuthan 
MGI | 15  |  @hdrabkin 
MTBBASE | 659  |  @ggeorghiou (what should we do about those?)  'growth' + IMP seems a little suspicious 
RGD | 10  |  @slaulederkind 
TAIR | 21  |  @tberardini 
TIGR | 4  | @ggeorghiou 
UniProt | 6  |  @ggeorghiou 
WB | 9  | @vanaukenk 
ZFIN | 1  |  @sabrinatoro

**Comment by selewis** [comment]
Perhaps a new child term under growth for those geneDB annotations?
Assuming these are largely microbial perhaps something like colony growth?
(one of you practicing biologists can arrive at the best class for these)

-S

**Comment by pgaudet** [comment]
GeneDB and MTBBASE are IMP. Really They should probably go, as they are likely to be phenotypes. 

Pascale

**Comment by hdrabkin** [comment]
So I'm just wondering what term would fit
'"the expansion of a population of single-celled organisms."?

**Comment by pgarmiri** [comment]
The 6 UniProt annotations are dealt with.

The  44 'GeneDB' (TBRU) are not ours. I do have a contact email address that Tony managed to dig out.(@pgaudet  I will pass it to you be email.)

For the MTBBASE annotations, I had a look to some of the papers and most of them are screenings for essential genes. Gene is missing- no growth.. The actual function of the genes could be in any essential metabolic process. If all of them are like that, I think they could go..

**Comment by tberardini** [comment]
20+ annotations from TAIR reviewed.

**Comment by hdrabkin** [comment]
MGI Done;

**Comment by hattrill** [comment]
FlyBase - done

**Comment by vanaukenk** [comment]
WB annotation are reviewed and removed.

@pgaudet and @pgarmiri - GeneDB is starting to make GO annotations again and submit new annotation files.
I don't know how the previous GeneDB file pipeline worked, but it might be worth getting in touch with @Achchuthan about these.  I'm adding his contact to the groups csv.

**Comment by sabrinatoro** [comment]
ZFIN annotation was reviewed and removed

**Comment by pgarmiri** [comment]
Just to confirm that  the MTBBASE annotations have been taken care of. 
612 / 659 are all coming from one paper. It is a screening for essential genes, so not informative at all. I asked Tony to delete them and they are all gone.

The remaining ones I went through the papers and removed or replaced the annotations accordingly. The spreadsheet is updated as well.

**Comment by pgaudet** [comment]
Great, thanks everyone !
