### ISSUE TITLE
Review annotations to GO:0006198 cAMP catabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1974]
Hello, 

For the GPCR work we propose to obsolete cAMP catabolic process - annotations are here: 
https://docs.google.com/spreadsheets/d/1WFXwop5Meyo_vb0kYZNAT1CJaHpepLeMpk_GMEPYOPc/edit#gid=0

and impacted groups. As shown in the matrix analysis below , cAMP catabolic process  phosphodiesterase activity are always co-annotated (if I got this right, @ValWood )

Contributor   (Assigned by) | Curator
-- | --
BHF-UCL | 12 | @RLovering 
dictyBase | 6 |  @pfey03 
FlyBase | 1 |   @hattrill 
MGI | 1 |  @ukemi 
MTBBASE | 3 |  @ggeorghiou 
PomBase | 2 |  @ValWood 
RGD | 27 |  @slaulederkind 
UniProtKB | 15 |  @ggeorghiou 

<img width="862" alt="image" src="https://user-images.githubusercontent.com/4782928/40068142-eb76a9f4-5835-11e8-9949-eb6cd937846b.png">

**Comment by RLovering** [comment]
Should we make sure all of these proteins are annotated to a signaling pathway? so that they still have a BP annotation?

**Comment by pgaudet** [comment]
Right ! Interestingly most are *not* annotated to the pathway. This may mean that the activity was  tested, outside the context of a pathway. We do need to review annotations before just moving annotations to the pathway (or its regulation). 

For example the first annotation in the spreadsheet: 


MGI:MGI:99555 | phosphodiesterase 4D, cAMP specific |   | GO:0006198 |  BHF-UCL | NCBITaxon:10090 | IDA |  PMID:21670503

is a nice example of  'GO:0071878 negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway' (or even 'GO:0140199 negative regulation of adenylate cyclase-activating adrenergic receptor signaling pathway involved in heart process :) 

OK ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Hey, Pascale.  The spreadsheet is read only.

**Comment by pgaudet** [comment]
Should be fixed. 

Thanks, 
Pascale

**Comment by slaulederkind** [comment]
RGD annotations fixed or deleted.

**Comment by RLovering** [comment]
Thanks for the annotation advice. I think the suggested term can only be applied to Pde4b, rather than Pde4d, but very helpful. 
The majority of the BHF-UCL annotations were based on enzyme assays and therefore no expt evidence for role in signaling.

All BP terms removed as requested

Ruth

**Comment by hattrill** [comment]
FlyBase - done

**Comment by pgarmiri** [comment]
The UniProt annotations have been checked.

**Comment by hdrabkin** [comment]
I believe the one annotation in the spreadsheet for MGI has already been removed

**Comment by pfey03** [comment]
Sorry it took me so long - 2 grants this year.. but now took care of all Dicty, mostly removed on changed

**Comment by ValWood** [comment]
PomBase fixed, sorry I missed this one.

There are still 7 annotations tho' (dictybase, MTBBASE, BH-UCL)

**Comment by ValWood** [comment]
ignore dictybase. (MTBBASE, BH-UCL)

**Comment by Antonialock** [comment]
MTBBASE done

**Comment by RLovering** [comment]
added the missing annotation to the spreadsheet and BHF-UCL now completely done

**Comment by pgaudet** [comment]
Out of date
