### ISSUE TITLE
Interpro FAD-binding, type 2 (IPR016166) with enzyme activity

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#1975]
FAD-binding, type 2 (IPR016166)
from the description and name it appears to have binding function but the GO terms associated to this domain also include "GO:0016614 oxidoreductase activity, acting on CH-OH group of donors" activity. Is it appropriate to assign enzyme activity to this domain?

**Comment by asangrador** [comment]
Same for this one. I will remove the activity term.

**Comment by phanivg** [comment]
Thank you Amaia. Can you please do the same for the corresponding homologous superfamily IPR036318.

**Comment by asangrador** [comment]
Done!
