### ISSUE TITLE
InterPro NADP-binding domain IPR006115 with enzyme activity

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#1976]
6-phosphogluconate dehydrogenase, NADP-binding (IPR006115)
looking at the description of this domain it seems to be involved in binding. Just wondering how an activity term is assigned to this domain instead of a binding term?

**Comment by asangrador** [comment]
Probably this annotation was added based on the proteins matched rather than the domain. I will remove the activity term.
Thanks,

**Comment by phanivg** [comment]
Thank you Amaia.
Phani
