### ISSUE TITLE
Review annotations to GO:0009187 cyclic nucleotide metabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1978]
https://docs.google.com/spreadsheets/d/1KzY5aabgNgFuUQJr8nmL6LIyPYS--YxPqbnpXKW5Ot0/edit#gid=0

1 MGI
1 SGD
1 UniProt

**Comment by suzialeksander** [comment]
We've looked at our annotation and are not sure why it's up for review.  CPD1 is a cyclic nucleotide phosphodiesterase; it hydrolyses a byproduct of splicing (ADP-ribose 1'', 2''-cyclic phosphate) to ADP-ribose 1''-phosphate.  Nothing to do with GPCR.  We can probably annotate this to the catabolic child term, but this term is the best fit as far as BP goes for CDP1.

**Comment by pgarmiri** [comment]
The UniProt annotations have been removed.
