### ISSUE TITLE
Review annotations to GO:0030803 negative regulation of cyclic nucleotide biosynthetic process 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1983]
Context:

To be consistent with obsoletion of regulation of cAMP biosynthetic process (geneontology/go-ontology#14718), I plan to obsolete the parent: GO:0030803 negative regulation of cyclic nucleotide biosynthetic process

https://docs.google.com/spreadsheets/d/1N4sPsWB-zuGa54T0tD7ayLSpUmsFhsBLxCxCHn6U0r8/edit#gid=0

Group | Annotation count
-- | --
PseudoCAP | 2

**Comment by glwinsor** [comment]
Removed obsolete GO:0030803 entry for PA3385 (armZ).

**Comment by pgaudet** [comment]
Thanks !
