### ISSUE TITLE
Review annotations to GO:0052653 3',5'-cyclic diguanylic acid metabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1984]
This term corresponds to a single-step process and has been proposed to be obsoleted. Please replace by MF GO:0052621  diguanylate cyclase activity if appropriate. 

Annotation review spreadsheet is here: 

https://docs.google.com/spreadsheets/d/16ieEh2kHIOg7a-g7SFLaBuS7fVt3lveJo0HUO_VTc40/edit#gid=0

Group | Annotations
-- | --
CACAO | 1
EcoCyc  | 1
PseudoCAP  | 1

Thanks, Pascale

**Comment by keseler** [comment]
Removed in EcoCyc; it will take a while to trickle down to the GAF, though.

**Comment by sandyl27** [comment]
CACAO is changed

**Comment by glwinsor** [comment]
Marked to be removed from pseudomonas.com database for our next release in a few weeks. We'll update the GAF around then.

**Comment by pgaudet** [comment]
Thanks everyone
