### ISSUE TITLE
Review annotations to  'regulation of cGMP metabolic/catabolic/biosynthetic process',  and + and - children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1985]
This issue was brought up in the GPCR work. Similar to cAMP biosynthesis/catabolism, cGMP biosynthesis/catabolism corresponds to the reaction catalyzed by guanylate cyclase. Regulation of cGMP metabolic/catabolic/biosynthetic process probably corresponds to a pathway, as indicated in the attached figures (but not limited to those). 

![image](https://user-images.githubusercontent.com/4782928/40374368-32ea84dc-5de9-11e8-8fbd-4c0c7be91b5a.png)

Therefore, we plan to obsolete the following terms. Please review your annotations to make sure that they are housed elsewhere. 

 - [x]  GO:0030823 | regulation of cGMP metabolic process: 
** **9 MG**I @hdrabkin 
https://docs.google.com/spreadsheets/d/1wcwEJS9ykxip2U9U5IX8wKUXhpMyUZNKOMgl2-vX1xQ/edit#gid=0

 - [x]  GO:0030824 | negative regulation of cGMP metabolic process
** **1 RGD** @slaulederkind 
https://docs.google.com/spreadsheets/d/1foE9kV1XkTqsU3Q0XON1dorLIiyn69Kkrv_aDn6MsA8/edit#gid=0

 - [x]   GO:0030826 | regulation of cGMP biosynthetic process
** **2 dictybase** @pfey03 
** **1 UniProt** removed @pgaudet
https://docs.google.com/spreadsheets/d/1G6_HHY4-Un211XHJCHeOkxHVVCp-1AfU6r4ELsqaPWY/edit#gid=0

 - [x]   GO:0030825 | positive regulation of cGMP metabolic process
** **2 BHF** @RLovering
** **2 nonEXP UniProt** @ggeorghiou 
https://docs.google.com/spreadsheets/d/1tef9JmVBCdJaM8fQ3SNdfEMN3XW9R8itCTmZYTgV_TU/edit#gid=0

 - [x]   GO:0030827 | negative regulation of cGMP biosynthetic process
** **1 dictybase** @pfey03 
** **5 UniProt-EBI** @pgarmiri 
https://docs.google.com/spreadsheets/d/1XlsVrj62efXgz_EUrwdvi8B2XogqTqaQxGzIVlHzMHU/edit#gid=0

 - [x]   GO:0030828 | positive regulation of cGMP biosynthetic process
** **2BHF-UCL** @RLovering 
** **1 dictybase** @pfey03 
** **4 MG**I @hdrabkin 
** **6 RGD** @slaulederkind 
** **1 UniProt-EBI** @pgarmiri
https://docs.google.com/spreadsheets/d/1zay-kk_3F4KNelMH_AycmxID-kVMoKhO2XD7e1CLEeA/edit#gid=0

Thanks, Pascale

**Comment by hdrabkin** [comment]
@pgaudet , what specifically are the recommendations?  There are none in the spreadsheets. None of the spreadsheets have the "Suggested action (by annotation review requester) " filled in.  The link to the main project is not helpful as it is not clear where the topic covered in THIS ticket is ...?

**Comment by slaulederkind** [comment]
RGD annotation fixed.

**Comment by bmeldal** [comment]
GO:0030828 positive regulation of cGMP biosynthetic process removed from 3 complexes.

Was co-annotated with 
GO:0004383 guanylate cyclase activity
GO:0007168 receptor guanylyl cyclase signaling pathway
GO:0035556 intracellular signal transduction
which all remain.

Birgit

**Comment by pgarmiri** [comment]
UniProt annotations has been checked and changed. Only the 2 ISS are remaining that are based on the EXP of BHF. When those are fixed, these will be updated automatically.

**Comment by RLovering** [comment]
annotations used for ISS updated
All on this ticket done.

**Comment by slaulederkind** [comment]
RGD annotations fixed.

**Comment by pgaudet** [comment]
Thanks everyone !
