### ISSUE TITLE
Review annotations to GO:0030814 regulation of cAMP metabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1986]
Context: 

To be consistent with obsoletion of regulation of cAMP biosynthetic process (https://github.com/geneontology/go-ontology/issues/14718), I plan to obsolete the parent: GO:0030814 regulation of cAMP metabolic process

Annotations could perhaps be moved to 
GO:0007189 adenylate cyclase-activating G-protein coupled receptor signaling pathway 
GO:0007193 adenylate cyclase-inhibiting G-protein coupled receptor signaling pathway

or regulation of one of those terms. 

https://docs.google.com/spreadsheets/d/17vmJ-_n36uMmtiDHDDD762TzzX3O4fwe1f4gqZ7S1gY/edit#gid=0

1 AgBase 
2 BHF-UCL
1 CACAO
6 MGI

**Comment by sandyl27** [comment]
CACAO's was removed.

**Comment by RLovering** [comment]
done

**Comment by pgaudet** [comment]
Annotations could perhaps be moved to 
GO:0007189 adenylate cyclase-activating G-protein coupled receptor signaling pathway 
GO:0007193 adenylate cyclase-inhibiting G-protein coupled receptor signaling pathway

or regulation of one of those terms. 

@hdrabkin does that help ?

**Comment by hdrabkin** [comment]
sorry this was done a while ago
