### ISSUE TITLE
Assess IEA, or annotation transfer pipelines, more generally, to make sure we’re transferring annotations reasonably. 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1989]
Action point from NYC 2018 meeting:

Assess IEA, or annotation transfer pipelines, more generally, to make sure we’re transferring annotations reasonably. 

----
Discussion: 
Val: we need to look at annotation specificity, filtering, display to address annotation explosion.
David: doesn’t think we should remove information just for the purposes of simplification; if annotations are correct, we should keep them but digest and present the information better
Jim H.: wants to be able to get all annotations to show his students what annotations have been made
The BioLink API will address Jim’s concern. Code is here: https://github.com/biolink/biolink-api and demo page here: https://api.monarchinitiative.org/api/ where you can play with the interface to see the JSON output.

**Comment by pgaudet** [comment]
This is a big task. We need to define the priority of this ticket.

**Comment by ValWood** [comment]
Yes, we can implement some simple things first and build on it.....

**Comment by ValWood** [comment]
@pgaudet  is this ticket still required?

**Comment by suzialeksander** [comment]
@pgaudet is this needed? Is this something addressed in whole/part with the treegrafter annotations?

**Comment by pgaudet** [comment]
This is out-of-date. thanks !
