### ISSUE TITLE
IPR019404 mapped to a merged term

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#1993]
Hello InterPro, 

IPR019404 is mapped to 
GO:0001104 RNA polymerase II transcription cofactor activity 
which now has as a primary ID: GO:0003712

Do you automatically migrate merge terms ? If not we'll make sure to notify you ahead of time. 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 

Thank you for this. We do have a system (script) to migrate these terms. We usually do so as soon as we receive the report from GO. However, as you may be aware, these results are only visible after our release.  In this case, we changed these terms in May, so the new ID 'GO:0003712' will be visible in our next release (v.69) in June. Therefore, it's always good to get your report as early as possible to synchronise the InterPro and GO websites. :)

Thank you, 
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks @EBI-Hsinyu 
Can you specify which report you are talking about ? Some email with errors ?

**Comment by EBI-Hsinyu** [comment]
Hi Pascale,

Sorry for the delayed reply. I just double checked with Amaia. We usually pick up the data from GOA and run a sanity check in InterPro. We then migrate the terms using SQL. 
Regards, 
Hsin-Yu
