### ISSUE TITLE
PAINT pipeline probem

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1994]
Something is very wrong here.

Pombe  Lto1
https://www.pombase.org/gene/SPCC191.08
is
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR28532

protein maturation by [4Fe-4S] cluster transfer
ribosomal large subunit biogenesis

has human ortholog LTO1
http://www.uniprot.org/uniprot/Q8WV07
this is getting IBA annotations to
double-strand break repair via homologous recombination Source: GO_Central
intra-S DNA damage checkpoint Source: GO_Central
meiotic DNA integrity checkpoint Source: GO_Central
mitotic DNA replication checkpoint Source: GO_Central
nucleotide-excision repair Source: GO_Central
(all incorrect)

from a *totally* different family  PANTHER:PTN000307391
which includes annotations transferred from pome
SPAC20G4.04c|UniProtKB=P78955 hus1 (which is a checkpoint protein)

hus1 and lto1 are unrelated?

@pgaudet @selewis @huaiyumi

**Comment by ValWood** [comment]
@pgaudet  maybe you could check if this one is reolved. The pipline might be ironed out by now.

**Comment by ValWood** [comment]
human LTO1 still seems to be picking up mappings from the wrong tree. I can't figure it out...
http://www.pantree.org/node/annotationNode.jsp?id=PTN000307391

**Comment by ValWood** [comment]
This is pom be LTO1
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC191.08
it does not have the PANTHER family.

human LTO1 is missign from AMigo?

This is mouse LTO1
http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1919534

It is in a family which maps it to pombe
https://www.pombase.org/spombe/result/SPAC20G4.04c
but this is not related to LTO1

**Comment by ValWood** [comment]
See the LTO1 orthologs
https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPCC191.08

Note, that DIOPT reports ORAOV1 but this is not called LTO1 in human rat and mouse

**Comment by ValWood** [comment]
This is the human entry in AmiGO.
It still has the old name
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q8WV07
but it does have the incorrect mappings  that come from a seemingly unrelated family

**Comment by pgaudet** [comment]
@ValWood 

pombe lto1 has a single IBA 

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/4782928/44942601-57719400-ad6a-11e8-9093-3865303b3b8e.png">


Are you describing multiple problems ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
I removed all annotations to the ORAOV1 branch, if that works for you please close. 

Pascale

**Comment by ValWood** [comment]
I think there is a problem with the family though.

pombe  LTO1
https://www.pombase.org/gene/SPCC191.08
ORAOV1 ortholog

is not related  (at all) to pombe hus1
https://www.pombase.org/gene/SPAC20G4.04c
HIUS1 ortholog

Lto1 is a
http://pfam.xfam.org/family/PF09811#tabview=tab2
Hus1 is a ATPase checkpoint protein 
http://pfam.xfam.org/family/PF04005#tabview=tab2
They are not even in the same clan.

Maybe there is another domain below threshold in one of them. But to me they seem to be totally unrelated. 

I think this one panther need to look at.

**Comment by pgaudet** [comment]
I sent an email to @huaiyumi , he'll look into this for the next Panther release.
