### ISSUE TITLE
Links from PanTree to AmiGO broken

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1996]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000042666

gives

Not Found
The requested URL /cgi-bin/amigo/term_details was not found on this server.

**Comment by pgaudet** [comment]
@kltm or @cmungall Did the links change ? If that's the case, PanTree is probably not the only site with bad links (dictybase seems to have the same problem). 
 
 @mugitty can you please have a look? 

Thanks, Pascale

**Comment by kltm** [comment]
This issue was moved to geneontology/go-site#664
