### ISSUE TITLE
Attribution of annotations in ZFIN GAF

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-annotation#1997]
I've just returned to the fray after a week's holiday and discovered that we appear to no longer be importing any ZFIN annotations.

When I looked at http://www.geneontology.org/gene-associations/gene_association.zfin.gz I discovered the reason, and that is that all of the annotations it contains are attributed to GO_Central, and none to ZFIN.

I assume that this is some kind of error?
@doughowe @sabrinatoro

**Comment by cmungall** [comment]
Correct, https://zfin.org/downloads/gene_association.zfin.gz has 18 columns when it should be 17. How quickly can the ZFIN developers fix this @sabrinatoro?

**Comment by cmungall** [comment]
Also, just showing our working:

This is the report for the most recent release, 2018-05-20:

http://release.geneontology.org/2018-05-20/reports/zfin.report.md

 * Associations: 0
 * Lines in file (incl headers): 202604
 * Lines skipped: 202604

This is pretty drastic! I thought we had a dead man's switch that would kill the entire pipeline and force and investigation, but this seemed to slip by.

We also run a daily snapshot report that can be checked by contributing groups:

http://snapshot.geneontology.org/reports/zfin.report.md

**Comment by sabrinatoro** [comment]
@cmungall 
Thank you for the link! I now know where to check that our GAF is ok. 

The ZFIN developers have fixed the problem*, and the current GAF should be fixed. Please let me know if there is more issues. Thanks. 

(*the timing was just perfect, and they were able to work on it immediately. And it wasn't a big problem. This rapid answer should not set expectations high for future issues :-) :-) )

**Comment by cmungall** [comment]
Thanks!

I can confirm that the fix is deployed"

```
$ curl -s -L https://zfin.org/downloads/gene_association.zfin.gz  | gzip -dc  | grep ^ZFIN | head -1  | awk -F"\t" '{print NF;exit}'
17
```

**Comment by tonysawfordebi** [comment]
Thanks everybody - now just waiting for the changes to percolate through the system...

**Comment by pgaudet** [comment]
Hello, 

Where was the GO_Central inserted ? At UniProt ?

**Comment by tonysawfordebi** [comment]
No - the GO_Central annotations are those from PAINT.

**Comment by pgaudet** [comment]
Ah ! Get it - those were the only valid annotations for zebra fish from all sources, is this right ?

**Comment by tonysawfordebi** [comment]
Not from **all** sources, just PAINT.

**Comment by cmungall** [comment]
@sabrinatoro - the problem seems to have reverted

we now have 18 columns again

```
$ curl -s -L https://zfin.org/downloads/gene_association.zfin.gz  | gzip -dc  | grep ^ZFIN | head -1  | awk -F"\t" '{print NF;exit}'
18
```

**Comment by sabrinatoro** [comment]
@cmungall : We are in the process of migrating database systems, and it appears that some things (like our downloads) are not stable. Something must have happened yesterday or today, and our downloads reverted to old data (i.e. before the column number issue was fixed). 
We looked into it and fixed the current downloads, and now, the current available file should have the correct number of columns. 
We will monitor this issue until we are done with the database migration.

**Comment by cmungall** [comment]
Thanks for the quick fix! We're also making some changes at this end to be more robust in the face of things like this

**Comment by sabrinatoro** [comment]
I think the issue is now fixed. Is that right? Can this ticket be closed? 
@cmungall @tonysawfordebi

**Comment by tonysawfordebi** [comment]
Yep, all seems good now.
