### ISSUE TITLE
Review annotation to GO:0030816	positive regulation of cAMP metabolic process and GO:0030815 negative 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2000]
Hello, 

For the G-protein coupled receptor signaling work, I will obsolete 
GO:0030816	positive regulation of cAMP metabolic process. Please review your annotation: 
https://docs.google.com/spreadsheets/d/14w1MbDnbvtJgP1U6E6LxpkS_RhyJUs9MfUOylLkkbl0/edit#gid=0

Group | # annotations
 -- | -- 
AgBase | 1
ARUK-UCL | 32
BHF-UCL | 1
RGD | 5
UniProt | 17

Annotated proteins are receptor or ligands, I propose to move annotation to either

GO:0007189 adenylate cyclase-activating G-protein coupled receptor signaling pathway
or
GO:0007193 adenylate cyclase-inhibiting G-protein coupled receptor signaling pathway
as appropriate. 

Thanks, Pascale

**Comment by slaulederkind** [comment]
All RGD annotations fixed.

**Comment by pgarmiri** [comment]
I checked and removed the one IDA EBI annotation. Contacted the SIB curator to update their 4 IDA annotations. The rest are by ISS and they will be updated automatically when the parent term has changed.

**Comment by BarbaraCzub** [comment]
I reviewed all the ARUK-UCL annotations.
