### ISSUE TITLE
PANTHER:PTN001173581 boss is not glutamate receptor

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2002]
PANTHER:PTN001173581 
FBgn0000206 boss has been classified as metabotropic glutamate receptor pthr24060, which it is not. 
Terms:
glutamate receptor activity
G-protein coupled glutamate receptor signaling pathway
regulation of synaptic transmission, glutamatergic

Could you block the propagation from this node to boss?

Thanks

**Comment by thomaspd** [comment]
I looked at this, on the possibility that boss doesn't belong in this family, but I think it is just a very diverged member of the family.  I agree with Helen's suggestion that we should block propagation to the clade containing boss (loss of these functions), along with potential gains of other functions.  @marcfeuermann can you please look at this (PTHR24060) and change as you see fit.

**Comment by hattrill** [comment]
Yes, it is weird one amongst the class C GPCRs - it acts as a ligand for sevenless tyrosine kinase (and there is a pinch of tenuous evidence implicating it as a glucose receptor)

**Comment by marcfeuermann** [comment]
I've blocked propagation to boss of the following terms: 
glutamate receptor activity
G-protein coupled glutamate receptor signaling pathway
regulation of synaptic transmission, glutamatergic

**Comment by hattrill** [comment]
I am seeing 
glutamate receptor activity for boss from this node again

**Comment by marcfeuermann** [comment]
Really strange ! Something messy happened during migration to new PANTHER version. I've reviewed the whole tree and made a lot of corrections.
