### ISSUE TITLE
IPR033308 	ER to Golgi vesicle-mediated transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2003]
ER to Golgi vesicle-mediated transport

is a bit indirect as ted1 is 

GPI anchor biosynthetic process

https://www.yeastgenome.org/locus/S000002590
mannose-ethanolamine phosphate phosphodiesterase; involved in GPI-anchor remodeling prior to the attachment of cell wall proteins to beta 1,3-glucan, removing ethanolamine phosphate from the first mannose of GPI anchors

**Comment by asangrador** [comment]
Thanks for this, I have changed the term for this entry and its child (IPR033307) as suggested.
