### ISSUE TITLE
TFIIF helicase keywords

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2004]
TFIIF subunit 

tfg2 / SPBC1198.13c  UniProtKB:O94424
http://pombase-dev.bioinformatics.nz/gene/SPBC1198.13c

has SPKW "helicase activity"

I don't see any evidence for that in domains, or  complex description
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005674

Is there a source for this?

**Comment by sylvainpoux** [comment]
Hi Val,

information was propagated from HUMAN entry UniProt P13984 (PubMed=2477704). If you think we should not propagate this, I can remove the EC number, CATALYTIC ACTIVITY and keyword

Sylvain

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Transcription_factor_II_F

I don't see anything in the literature except for this 1989 paper saying that TFIIF is a helicase...

and there is no helicase domain in O94424 or P13984

  O94424 / P13984 have a DNA binding domain and  a domain for interaction with the other subunits of TFIIF
but neither of those appears to be a helicase either....

So I'm not sure....
