### ISSUE TITLE
conficting mapping on IPR007015(fixed) SPKW and PAINT

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2007]
http://www.ebi.ac.uk/interpro/entry/IPR007015

Is 
Proteins of this family are predominantly nucleolar. The majority are described as transcription factor transactivators. The family also includes the fifth essential DNA polymerase (Pol5p) of Schizosaccharomyces pombe (Fission yeast) and Saccharomyces cerevisiae (Baker's yeast) (EC:2.7.7.7). Pol5p is localized exclusively to the nucleolus and binds near or at the enhancer region of rRNA-encoding DNA repeating units.

so the MF is polymerase and the BP is transcription?

(I'm not sure from a brief check that it  is a DNA polymerase, this might be a red-herring)?

**Comment by asangrador** [comment]
Yes,you are right, Pol5p is thought to act, like the animal members of the family, as a regulator of transcription (PMID:12695662), and not being a polymerase. I have updated the abstract and changed the GO annotation (removing 'polymerase activity', and adding 'regulation of transcription, DNA-templated')

**Comment by ValWood** [comment]
OK, @pgaudet  the PAINT also need revising

IBA with PTN000996206 , S000000781

and the SPKW  KW-0239 @sylvainpoux

**Comment by sylvainpoux** [comment]
Thanks for pointing this. Ivo, could you have a look and update these entries? O60094, P39985 @pedruzzi
