### ISSUE TITLE
Q99501 uniprot annotation

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#2010]
Q99501 is annotated to
thyroid hormone receptor binding IPI from PMID:19375645
-I don't think this paper shows a physical interaction between these two proteins.

It is also annotated to
negative regulation of erythrocyte differentiation 
- In this paper they show that Q99501 overexpression lengthens the cell cycle and causes growth inhibition. Other papers show that this protein interacts with microtubules. It doesn't seem unlikely that the observed "negative regulation of erythrocyte differentiation" could just be an indirect effect of messing with the microtubule cytoskeleton.

**Comment by ValWood** [comment]
Shouldn't go and work for UniProt should ya!

**Comment by Antonialock** [comment]
lol
