### ISSUE TITLE
Review two ISS annotations for protein complexes

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2013]
Following on from the protein complexes working group discussion on use of protein complexes in the With/From field, there are two CC annotations that look to perhaps just be mappings between a complex as captured in the complex portal and the complex as represented by a GO term.  

https://github.com/geneontology/go-ontology/issues/15421

@RLovering - can you take a look at these two annotations and see if that is indeed the case?  If so, we would recommend they be removed.  Thanks.

https://docs.google.com/spreadsheets/d/1B7srG8pz2ZxbjUnqlagjy6aQRDE8hxXuNvaW0oe2iP4/edit#gid=0

@bmeldal

**Comment by RLovering** [comment]
ok done
Ruth

**Comment by pgaudet** [comment]
@vanaukenk These are done. Close ?
