### ISSUE TITLE
InterPro2GO "3-hydroxyacyl-CoA dehydrogenase activity" issue.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2016]
The following 4 InterPro signatures all map to 3-hydroxyacyl-CoA dehydrogenase activity (GO:0003857, =EC:1.1.1.35):
IPR006108 	3-hydroxyacyl-CoA dehydrogenase, C-terminal
IPR006176 	3-hydroxyacyl-CoA dehydrogenase, NAD binding
IPR006180 	3-hydroxyacyl-CoA dehydrogenase, conserved site
IPR022694 	3-hydroxyacyl-CoA dehydrogenase

I have come across 3 gene/proteins where this appears untrue/inaccurate.

1. Human CRYL1 (Q9Y2S2) - annotated with "L-gulonate 3-dehydrogenase activity" (GO:0050104, =EC:1.1.1.45) IDA from PMID:15809331
2. Rabbit CRYL1 (P14755) - also annotated with "L-gulonate 3-dehydrogenase activity" (GO:0050104, =EC:1.1.1.45) IDA from PMID:15809331
3. D. melanogaster CG9914 (Q9VXI1) - this corresponds to the 'Had' locus that is characterised as having "L-gulonate 3-dehydrogenase activity" (GO:0050104, =EC:1.1.1.45) in PMIDs 4328697 & 28119. (Note this annotation has not yet been made in FlyBase/Protein2GO.)

So I think the InterPro2GO associations for the 4 signatures above may need to go up one level to "oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor" (GO:0016616)??
(Or maybe some edits to the GO are required?)

![screen shot 2018-06-27 at 09 50 21](https://user-images.githubusercontent.com/16306861/41963445-8a2687c4-79ef-11e8-9d08-36fc11d8152f.png)

**Comment by sjm41** [comment]
Tagging @hattrill

**Comment by sjm41** [comment]
@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I had a look a these entries and changed the term for the one you mentioned, except for IPR006176 which is a NAD binding domain (thus, I added the term NAD+ binding (GO:0070403)). The changes will be visible in the next InterPro release (83.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
