### ISSUE TITLE
human  genes, annotated to GO, missing from  AmiGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2018]
uniprot look up service for  HGNC:30005 filtering on "reviewed" to get the  'swiss-prot' entry
that would presumably be in reference genomes and hence in GO sometimes does not find the expected entry

 
For example  HGNC:30005  gets U3KPV4 (A3GALT2)

https://www.uniprot.org/uniprot/U3KPV4
has GO annotation , 

~but  U3KPV4 is not in quickgo~
~https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=U3KPV4~

not in   AmiGO
http://amigo.geneontology.org/amigo/medial_search?q=U3KPV4

but presumably, once was since it has annotation from GOC PAINT pipeline.

Where d'it go???

**Comment by ValWood** [comment]
@Antonialock  care,  quite a few of the "unannotated" when searching GO seem to be this type.

**Comment by ValWood** [comment]
eg 2
HGNC:268   P0DMS8 ADORA3
https://www.uniprot.org/uniprot/P0DMS8
not in QuickGO  or AmiGO

**Comment by ValWood** [comment]
Actually  QuickGO is broken which may be why I can't find them there (some problem with the Solr indexing, I can't find anything)

@Antonialock  we probably need to switch back to the UniProt ID set you used previously. This may work now ...we can't use the HGNC set because it is likely that a couple of hundred entries are affected (at least that's about the number I see that I would expect to be slimmed).

**Comment by pgaudet** [comment]
Seems fixed ? 
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P0DMS8
= 27 annotations

**Comment by ValWood** [comment]
OK QuickGO is back.

But these should be the entries supplied from UnoPROT to GO
if they are the unique Swiss prot ID that the HGNC entry maps to.

**Comment by ValWood** [comment]
I altered the issue above to indicate that these entries are in QuickGO,  and UniPRot, but are not in AmiGO

@tonysawfordebi  any idea why. We are  trying to figure out the best way to analyse some data but we keep finding duplications and omissions.

I'm happy to report this on somewhere if some other group needs to look into it.

Val

**Comment by tonysawfordebi** [comment]
I've kind of lost the plot here - can you summarise what the problem is?

I've checked our database, and the files that we publish, and everything seems to be in order on our side, including the GPI file that gives HGNC:30005 as a cross-reference for UniProtKB:U3KPV4.

**Comment by ValWood** [comment]
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:U3KPV4

was giving a "not found" error  last week.... now it's OK. 
More weirdness.

**Comment by ValWood** [comment]
Actually

http://amigo.geneontology.org/amigo/medial_search?q=U3KPV4

Nothing found for U3KPV4. Please try again.

http://amigo.geneontology.org/amigo/gene_product/UniProtKB:U3KPV4

Will move to Amigo tracker @kltm @cmungall

**Comment by Antonialock** [comment]
@ValWood I have had this before

notice the difference in the URLs
http://amigo.geneontology.org/amigo/**medial_search**?q=U3KPV4

the "medial search" address is the problem, it comes when you enter a gene name in the search box, and instead of selecting the result from the dropdown list you hit enter

to get to the correct page you need to select the result from the dropdown.

**Comment by ValWood** [comment]
https://github.com/geneontology/amigo/issues/514

yes but you only see this if you add a space, and why would you with an ID.  You should be able to locate the entry with the ID.
