### ISSUE TITLE
Review annotations to GO:0097722 "sperm motility"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#2022]
In https://github.com/geneontology/go-ontology/issues/15945 it was suggested that the term 'sperm motility' should be marked in the "do NOT annotate" set as it is the grouping term for two terms which are clearly separated by the taxon of the organism being annotated:
-- sperm motility
--- amoeboid sperm motility (present in nematodes)
--- flagellated sperm motility

As the curator should know if they are annotating a nematode or some other type of organism, it makes sense to force annotation to one of the specific terms, rather than allowing annotation to the grouping term.

Thus correction of direct annotations to the term 'sperm motility' is needed. Rereading of the papers seems unlikely to be needed, as all of these annotations appear to be for vertebrates with flagellated sperm:
- Zfin, MGI, and UniProt have experimental annotations to move from 'sperm motility' to 'flagellated sperm motility'. 
- RGD and UniProt have ISO or ISS annotations that appear to all be based on experimental annotations of mouse genes and which may need to be manually moved to the 'flagellated sperm motility' term:

Annotating   group | IMP | ISO | ISS
-- | -- | -- | --
UniProt | 4 |   | 4
MGI | 1 |   |  
ZFIN | 1 |   |  
RGD |   | 4 |  
UniProtKB |   |   | 1

**Comment by krchristie** [comment]
Here is the spreadsheet with annotations to 'sperm motility' to correct (rereading paper should not be required)

https://drive.google.com/file/d/1t8fXpV-7Utrg-mDc4ZtU3h-r6HZGvO_k/view?usp=sharing

**Comment by slaulederkind** [comment]
Since all of the RGD ISO annotations are imported, they will automatically be corrected after MGI and UniProt correct the original annotations.

**Comment by pgarmiri** [comment]
All UniProt annotations were created at SIB. I have contacted the relevant curators with the change required.

**Comment by pgaudet** [comment]
@sabrinatoro 
@ukemi 
There are still some annotations to change. 

Can you please have a look ? 
https://docs.google.com/spreadsheets/d/1oNydnJavcA_8oGE5U8eR32Tne8N8kZEaa6rQAeYuuuc/edit#gid=2066403410

Thanks, Pascale

**Comment by sabrinatoro** [comment]
Thank you for bringing this to my attention. 
The ZFIN annotations have been changed.

**Comment by pgaudet** [comment]
@hdrabkin 
There is still 

MGI:MGI:1277238
MGI:MGI:1918349
 to look at.

**Comment by hdrabkin** [comment]
These two cannot be changed as they are imported from GOA (UniProt); they will change when that change in GOA gets into the load pipleline

**Comment by pgaudet** [comment]
Great ! Thanks everyone.
