### ISSUE TITLE
Review annotations to 'GO:0000988  transcription factor activity, protein binding' and similar children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2024]
Hello, 

From the annotation call of July 10, 2018, I propose to obsolete 'transcription factor activity, protein binding' and similar children. The list of terms is in the ontology ticket 
https://github.com/geneontology/go-ontology/issues/16053

Annotations and potential replacements for many of them are here: https://docs.google.com/spreadsheets/d/1jwgpZF3paxNOHvEHQ4v_uxOFb3FjQUOnxSJpswIzyMI/edit#gid=0

Annotation guidelines are here: https://goo.gl/dsvB18

**Groups impacted | Number of annotations** 
BHF-UCL | 28 @RLovering - done
CACAO | 1 @sandyl27 
CAFA | 11 @ggeorghiou 
ComplexPortal | 3 @bmeldal 
FlyBase | 21 @hattrill 
MGI | 19 @hdrabkin 
ParkinsonsUK-UCL | 1 @RLovering - done
PomBase | 2 @ValWood 
SGD | 77 @srengel @krchristie 
TAIR | 1 @tberardini 
UniProt | 3 @ggeorghiou 
WB | 7 @vanaukenk  
ZFIN | 4 @sabrinatoro 

Thanks, Pascale

**Comment by sabrinatoro** [comment]
What should I do with the following annotation?
Kctd10 was shown to bind to Tbx5a (which was shown to be a transcription factor), and this binding repress the transcriptional activity of Tbx5a. 
There is no report of Kctd10 binding to DNA, and no report that it is binding to RNA polymerase II basal transcription machinery.
How should Kctd10 be annotated? 
Thank you!

**Comment by pgaudet** [comment]
Hi @sabrinatoro 
I would annotate to     GO:0003714  transcription corepressor activity. (Note that this term needs to be reviewed too, but I am pretty sure that Kctd10 would be correctly annotated there.) 

Thanks, Pascale

**Comment by pgaudet** [comment]
NOTE: I restored  GO:0003711 transcription elongation regulator activity
which should allow to annotate some proteins in that list (See https://github.com/geneontology/go-ontology/issues/14398)

**Comment by pgarmiri** [comment]
The UniProt annotations have been reviewed and updated.

**Comment by bmeldal** [comment]
All complexes changed. All TFs with to-be-obsoleted terms now have annotations to GO:0140110 transcription regulator activity or children. However, as the term is new I doubt all TFs in the Complex Portal are annotated with this branch... I'd have to do some archaeology to fix that!

**Comment by sandyl27** [comment]
CACAOs annotation has been updated.

**Comment by sabrinatoro** [comment]
Thank you @pgaudet.
The ZFIN annotations have been reviewed and updated.

**Comment by ValWood** [comment]
I have no annotations to GO:0000988 so I must have done them in a previous round.

**Comment by pgaudet** [comment]
@ValWood It's very possible that you already deleted the annotations, but in the spreadsheet you still have two proteins (PomBase:SPBC2D10.06; PomBase:SPBC2F12.11c)
Can you go in the google spreadsheet and mark those proteins as fixed ? 
https://docs.google.com/spreadsheets/d/1jwgpZF3paxNOHvEHQ4v_uxOFb3FjQUOnxSJpswIzyMI/edit#gid=0

**Comment by tberardini** [comment]
TAIR done.

**Comment by ValWood** [comment]
done ;)

**Comment by vanaukenk** [comment]
WB annotations reviewed and updated.

**Comment by pgaudet** [comment]
@srengel @suzialeksander 
Would it be OK if I went ahead with the obsoletion tomorrow, so that it appears in the next release ? (Otherwise further changes are more difficult). 

That might mean you have annotations to obsolete terms but that should be for a short period until you get to fixing them. 

Thanks, Pascale

**Comment by srengel** [comment]
That’s ok.  I won’t be able to get to these until next week, but will get it done then.

**Comment by hdrabkin** [comment]
By the spreadsheet, any annotations left to mouse genes have been done by BHF-UCL or ParkinsonsUK-UCL; MGI can't do anything to those as they are dropped and re-loaded weekly.  So I'll take my name off of the assigned.

**Comment by RLovering** [comment]
Ok BHF annotations done - Ruth

**Comment by pgaudet** [comment]
@RLovering 
There were filters applied. There is 1 Parkinson's annotation to UniProtKB:P18848

Thanks, Pascale

**Comment by RLovering** [comment]
thanks sorted out that last one. I did try to select all in the filter option, maybe I just had slow internet
Ruth

**Comment by pgaudet** [comment]
Closing this. Some groups have not responded 
@hdrabkin @hattrill @pgarmiri 

but the term has already been obsoleted.

**Comment by pgarmiri** [comment]
> 
> 
> The UniProt annotations have been reviewed and updated.

@pgaudet I had another look at the spreadsheet. There is only one annotation from UniProt left but is ISS, so this should have been fixed automatically after the parent was corrected.  
Thanks

**Comment by RLovering** [comment]
Hi Pascale

in ticket https://docs.google.com/spreadsheets/d/1uHMSFAuxsOL54F0CLiB2lbrYyvjHTbyA0O2n8rsgKEI/edit#gid=0 you list BHF annotations as not done for this ticket, but they are done it is just I hadn't marked them as done. I have highlighted them on the ticket.

Ruth
