### ISSUE TITLE
P07199 Human cenpb has no BP annotation

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#2027]
human cenpb has no biological process annotation which is a bit surprising

Could someone annotating human add e.g. from https://www.cell.com/developmental-cell/abstract/S1534-5807(15)00216-6

**Comment by ValWood** [comment]
P07199

**Comment by ValWood** [comment]
@Antonialock  could you transfer to this ticket so they are all in one place?
https://github.com/geneontology/go-annotation/issues/2026

**Comment by Antonialock** [comment]
transferred #2026
