### ISSUE TITLE
human NUDT6, not a growth factor, remove TAS, reannotate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2028]
Hydrolytic activity of human Nudt16 enzyme on dinucleotide cap analogs and short capped oligonucleotides.

Abstract
Human Nudt16 (hNudt16) is a member of the Nudix family of hydrolases, comprising enzymes catabolizing various substrates including canonical (d)NTPs, oxidized (d)NTPs, nonnucleoside polyphosphates, and capped mRNAs. Decapping activity of the Xenopus laevis (X29) Nudt16 homolog was observed in the nucleolus, with a high specificity toward U8 snoRNA. Subsequent studies have reported cytoplasmic localization of mammalian Nudt16 with cap hydrolysis activity initiating RNA turnover, similar to Dcp2. The present study focuses on hNudt16 and its hydrolytic activity toward dinucleotide cap analogs and short capped oligonucleotides. We performed a screening assay for potential dinucleotide and oligonucleotide substrates for hNudt16. Our data indicate that dinucleotide cap analogs and capped oligonucleotides containing guanine base in the first transcribed nucleotide are more susceptible to enzymatic digestion by hNudt16 than their counterparts containing adenine. Furthermore, unmethylated dinucleotides (GpppG and ApppG) and respective oligonucleotides (GpppG-16nt and GpppA-16nt) were hydrolyzed by hNudt16 with greater efficiency than were m7GpppG and m7GpppG-16nt. In conclusion, we found that hNudt16 hydrolysis of dinucleotide cap analogs and short capped oligonucleotides displayed a broader spectrum specificity than is currently known.

https://www.ncbi.nlm.nih.gov/pubmed/29483298

**Comment by ValWood** [comment]
There are loads of papers about this role.....

hNUDT16: a universal decapping enzyme for small nucleolar RNA and cytoplasmic mRNA.

Lu G, Zhang J, Li Y, Li Z, Zhang N, Xu X, Wang T, Guan Z, Gao GF, Yan J.

Protein Cell. 2011 Jan;2(1):64-73. doi: 10.1007/s13238-011-1009-2. Epub 2011 Feb 20.

PMID: 21337011

**Comment by pgarmiri** [comment]
Hi Val, I had a look at this. There are two different entities Q96DE0 (NUD16_HUMAN) and P53370 (NUDT6_HUMAN). The papers you suggested are for NUD16 and not NUDT6. I am trying to find some more to populate NUDT6 that does seem to have an effect on cell proliferation.

**Comment by ValWood** [comment]
Oh whoops!

**Comment by ValWood** [comment]
I wouldn't bother witha "cell proliferation " annotation, it is really only a phenotype  (i.e required for growth or division ) unless it's saying something about the expansion os a particular population of cells. I thought  we had already blocked this  for direct annotation ages ago  but apparently not @pgaudet  should we do that?

**Comment by krchristie** [comment]
@ValWood - When I was an SGD curator, I agreed that 'cell proliferation' annotations were not useful for curating for S. cerevisiae. However, as a curator for mouse, this is a term we use, sometimes in conjunction with a specific cell type. I think more input form mammalian curators might be warranted before marking this term not for direct annotation.

**Comment by ValWood** [comment]
Ah OK, I thought that you always used the child terms but that might be why. 

Penelope, if this was the paper:

A potential proliferative gene, NUDT6, is down-regulated by green tea catechins at the posttranscriptional level.

Sukhthankar M, Choi CK, English A, Kim JS, Baek SJ.
J Nutr Biochem. 2010 Feb;21(2):98-106. doi: 10.1016/j.jnutbio.2008.11.002. Epub 2009 Jan 20.
PMID: 19157820

I would not curate it. I don't think I would curate anything from this journal ;)

Summary: Cells grow when overexpressed...

**Comment by krchristie** [comment]
@ValWood - If there is a more specific term, then I will use that. However, there isn't always a more specific term, and lately we have been inclined towards using the annotation extension to provide specificity rather than asking for so many more new terms for all the specific cell types.

**Comment by ValWood** [comment]
Yes that makes sense for cell types, that must be why it isn't blocked.

In this case there should always be a cell-type specific extension.

Maybe the comment could be clearer to this effect.

Currently
"Also note that this term is intended to be used for the proliferation of cells within a multicellular organism, not for the expansion of a population of single-celled organisms."

Should be  something like:

"Also note that this term is intended to be used for the proliferation of  a ***specific population of *** cells within a multicellular organism, ***not for genes  required for the  growth and division of any cell type or ***~not~ for the expansion of a population of single-celled organisms."

i. e. it isn't for genes that are just essential for growth and division in every cell type.

**Comment by pgarmiri** [comment]
Hi Val, 
The paper I based the annotation of 'negative regulation of cell proliferation' was 
' The endogenous fibroblast growth factor-2 antisense gene product regulates pituitary cell growth and hormone production.'
 Asa SL , Ramyar L , Murphy PR , Li AW , Ezzat S  
Molecular Endocrinology (Baltimore, Md.) [01 Apr 2001, 15(4):589-599] 
(PMID:11266510)

 In the abstract the authors state: ' GFG expression inhibited cell proliferation as shown by [(3)H]thymidine incorporation, proliferating cell nuclear antigen (PCNA) nuclear staining, and cell cycle analysis.' (GFG  is an alternative name)

I have also added the specific cell type mentioned about plus  'negative regulation of cell cycle'.

**Comment by ValWood** [comment]
OK!
