### ISSUE TITLE
 TF related

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#203]
I am working wih Tony Wright at the Karolinska to try
to refine and
extend the list of S. pombe regulatory   transcription
factors in pombe,
ie ones that we expect to bind to specific DNA sequences.

So in Go we have:

GO:0003700
transcription factor activity
Any activity required to initiate or regulate
transcription; includes
the actions of both gene regulatory proteins as well as
the general
transcription factors.

Many Interpro mappings have been made to this term,
which seems
perfectly reasonable based on its current def.

However, by this term, do we mean the transcription
'factors' which are
part of the general RNA pol I/II and III machinery, I
didn't think we
did becasue 
a) these have their own terms, and 
b) these are not 'real' function terms but function
grouping terms for
'factors' known to be members of RNA polymerase I II
and III complexes
and subcomplexes. 
i.e. they are process terms in function which will each
have specific
functions 

This may be completely wrong, if so please correct me!

In light of the above (if it is correct), here are some
suggested
updated mapping to remove the 'transcription factor
activity' from
things which are not 'transcription factors which bind
specific DNA
sequences'  (if this is what it means)

IPR000812
is present in TFIIB &TFIIC so this probably needs to go
to the parent
transcription regulator activity GO:0030528 ?

IPR001222
not sure abut this as it isn't specific for
'transcription factor
activity' is also in RNA polymerase subunits
rpa12/O94703 rpb9/O74635
and rpc11/O13896and in tfs1/P49373

IPR007309
GO:0003709 : RNA polymerase III transcription factor
activity `

IPR007198
GO:0003702 : RNA polymerase II transcription factor
activity

IPR003923
GO:0003702 : RNA polymerase II transcription factor
activity 

IPR006809
GO:0003702 : RNA polymerase II transcription factor
activity 

IPR011442 
wasn't sure here/ both?
GO:0016986 transcription initiation factor activity
GO:0003702 : RNA polymerase II transcription factor
activity 

IPR004598
Transcription factor Tfb2 would probably be better
renamed Transcription
factor TFIIH subunit Tfb2
GO:0003702 : RNA polymerase II transcription factor
activity 

IPR004600  
Transcription factor Tfb4 would probably be better
renamed Transcription
factor TFIIH subunit Tfb4
GO:0003702 : RNA polymerase II transcription factor
activity 

IPR006289
GO:0003702 : RNA polymerase II transcription factor
activity 
and/or
GO:0003746 translation elongation factor activity

I think these are correct, but Sandra you'll probably
spot if I have
made them too specific...some could probably be more
specific like
'general RNA polymerase II transcription factor activity'

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/203":https://sourceforge.net/p/geneontology/annotation-issues/203

**Comment by linuxjackto1** [comment]
thanks www.movied.org
