### ISSUE TITLE
adding Molecular function terms to IPR018108 and IPR002067

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#2030]
The domains Mitochondrial substrate/solute carrier 'IPR018108' and Mitochondrial carrier protein 'IPR002067' are seen in many carrier proteins. All the SLC25 family members in Fly as well as many human and mouse proteins have at-least one of this domain. 
It will be nice if you can check and add a molecular function term like "transmembrane transporter activity" ; GO:0022857 to these domains.

**Comment by ValWood** [comment]
For IPR018108 ugo1
https://www.yeastgenome.org/locus/YDR470C
is a carrier but apparently not a transporter as far as we know. It has a role in membrane fusion.

I think it can be added for the IPR002067 subset.

**Comment by phanivg** [comment]
Got it. Make sense not to add GO:0022857 for IPR018108.

**Comment by asangrador** [comment]
I have added the term to IPR002067. Thanks.
