### ISSUE TITLE
A question about the sources of GO_Central annotations

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#2032]
Just a question, concerning some exploration around the fix for https://github.com/biolink/ontobio/issues/201

We noticed that the vast majority of GO_Central annotations are IBAs, but very infrequently, for some resources, there are like one or two that are not. As a concrete example in wormbase:

```
sjcarbon@moiraine:/tmp$:) zcat wb.gpad.gz | grep -v "^!" | grep GO_Central | grep -v ECO:0000318
WB	WBGene00004317	involved_in	GO:1990000	PMID:25495476|WB_REF:WBPaper00046187	ECO:0000315			20150626	GO_Central	
WB	WBGene00004317	involved_in	GO:2000786	PMID:25495476|WB_REF:WBPaper00046187	ECO:0000315			20150626	GO_Central	
```

Assuming this is okay, in general, are there any rules we should think about for the structure of GO_Central annotation?

@vanaukenk @dougli1sqrd

**Comment by tonysawfordebi** [comment]
GO_Central is primarily used as the attribution for annotations from PAINT (which is where all of the IBAs come from), but it is also used as the attribution for annotations created by GOC curators via Protein2GO (usually curators from groups who don't routinely use P2G as their primary annotation tool).

**Comment by pgaudet** [comment]
Right - these two were curated by @marcfeuermann 

My annotations show up the same way. 

Pascale

**Comment by ValWood** [comment]
I wonder why we have GO:1990000 positive regulation of amyloid fibril formation?
Amyloid fibrils are abnormal. I can see you would have terms for clearance but not for regulation of formation?

**Comment by pgaudet** [comment]
@ValWood This question should go in the ontology tracker. It has come up often, we should at least have a comment. 

@kltm Can we close ?

**Comment by ValWood** [comment]
moved query about 
GO:1990000 positive regulation of amyloid fibril formation?
to
https://github.com/geneontology/go-annotation/issues/2038
