### ISSUE TITLE
 PTN000081399 not 3'-phospho-5'-adenylyl sulfate transmembrane transport/er

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2033]
Our  ER
UDP-N-acetylglucosamine transmembrane transporter 

is picking up this mapping:
https://www.pombase.org/gene/SPBC1734.09

**Comment by thomaspd** [comment]
This annotation no longer appears in AmiGO, and is not in the current PAINT annotations that would be propagated to SPBC1734.09.

However, in addition to the substrate in the gene name, there are several other predicted substrates based on a very clear orthologous group with  few duplications in the Unikonts, suggesting these other substrates could be conserved.  Are you OK with these being propagated as well? http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC1734.09

**Comment by ValWood** [comment]
I'm not aware of any xylose or fucose in yeast glycans, in which case there probably isn't a ER transporter for this UDP-sugar (although it is known to be present in mammalian glycans). I would need to ask about this though I'm not sure..... but I would have expected it would have been assayed/known/annotated in SGD if it were the case.....

**Comment by ValWood** [comment]
Sometimes,  especially for transporter substrates it isn't wise to transfer from mammalian for yeast. Many budding yeast transporters are well-studied  and this would most likely be known. Specificity changes a lot over time (even between close paralogs).
Unless there is a very clear 1:1 relationship with a very defined substrate and lots of evidence, I would not transfer specificity  at all. It would be best to stick with a useful general annotation (UDP-sugar), than to try to infer specifity. I see too many examples where these are not conserved as would be expected based on taxonomic pattern. 

I guess we could have rules for different transporter types and compartments. For example for all mitochondrial carriers annotations transfer is pretty safe. For those transferring substrates of glycans in the ER, often not.....

**Comment by thomaspd** [comment]
The UDP-N-acetylglucosamine activity seems to be broadly conserved, based on the experimental annotations.  As for the other substrates, @marcfeuermann , can you please take a look at PTHR10778 and see how you think we should handle these?

**Comment by marcfeuermann** [comment]
3'-phospho-5'-adenylyl sulfate transmembrane transport/er was propagated over an ancient duplication event, so yes this was indeed a mistake. I propose to restrict this term to PTN000845564 (which does not contain any fungi).  PTN000081451 (including SPBC1734.09) will no more have this term and will get UDP-N-acetylglucosamine as a substrate as experimentally shown for Human, Drodophila and yeast (YEA4). I would also restrict UDP-xylose to animals for this node.
Let me know if you agree with this solution to close this issue.

**Comment by ValWood** [comment]
I think so,
