### ISSUE TITLE
Two GONUTS annotations appear to have faulty PMIDs

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#2037]
In the current GONUTS source GAF, http://geneontology.org/gene-associations/submission/gene_association.gonuts.gz (2018-07-25), the following incorrected PMIDs appear:

* PMID:16166540[2]
* PMID:PMC207867

What is the proper procedure for pushing this upstream?

**Comment by pgaudet** [comment]
@sandyl27 Can you please have a look ?

**Comment by sandyl27** [comment]
We have a new GPAD that needs to be submitted but we just did a server migration and are trying to figure out the to put it so it is public. 

@jimhu-tamu

**Comment by pgaudet** [comment]
OK thanks !

**Comment by ValWood** [comment]
@kltm, I am assuming a fix for this came through. I can't check because it doesn't seem to be possible to search aioGO with PMIDs but please reopen if not.
