### ISSUE TITLE
Review annotations to GO:2000677 regulation of transcription regulatory region DNA binding & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2039]
Looks like most of them could be moved to a function, either 'DNA-binding transcription factor activity' or 'transcription coregulator activity', or one of their children. These terms are: 

- 'regulation of transcription regulatory region DNA binding'

- 'negative regulation of transcription regulatory region DNA binding'
- 'negative regulation of core promoter binding'
- 'negative regulation of RNA polymerase I regulatory region sequence-specific DNA binding'
- 'negative regulation of RNA polymerase II regulatory region sequence-specific DNA binding'

- 'positive regulation of transcription regulatory region DNA binding'
- 'positive regulation of core promoter binding'
- 'positive regulation of RNA polymerase II regulatory region sequence-specific DNA binding'

- 'regulation of core promoter binding'
- 'negative regulation of core promoter binding'
- 'positive regulation of core promoter binding'

- 'regulation of RNA polymerase I regulatory region sequence-specific DNA binding'
- 'negative regulation of RNA polymerase I regulatory region sequence-specific DNA binding'

- 'regulation of RNA polymerase II regulatory region sequence-specific DNA binding'
- 'negative regulation of RNA polymerase II regulatory region sequence-specific DNA binding'
- 'positive regulation of RNA polymerase II regulatory region sequence-specific DNA binding'

Annotations are here: 

https://docs.google.com/spreadsheets/d/1mpoIskoYNs4mOOtXelBuBmPLe4Hbuzu5ZKiO89zoi8k/edit#gid=0

Group | Manual annotations
-- | --
AgBase | 41
BHF-UCL | 22
CAFA | 11
EcoCyc | 2
FlyBase | 4
GO_Central | 1
MGI | 10
ParkinsonsUK-UCL | 4
PomBase | 4
PseudoCAP | 2
RGD | 4
SGD | 5
UniProt | 37
UniProtKB | 8
WB | 5

Thanks, Pascale

**Comment by ValWood** [comment]
I haven't fixed this yet and  I want @alock to do these ones, but happy for you to obsolete and they can sit in our logs until fixed, so removing my name. We can easily rehouse.

**Comment by slaulederkind** [comment]
RGD annotations are fixed.

**Comment by pgaudet** [comment]
@slaulederkind just curious- what did you change the annotation to ? It would be useful if you could add this to column A. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Annotations to GO:0000991 are here: https://docs.google.com/spreadsheets/d/16CWA5XBcBHVTaKutTcKtWLmqTeaU9x4Pt-TNBNxpxqQ/edit#gid=0

**Comment by ValWood** [comment]
I'm a bit confused
the spreadsheet is for 
GO:0000991 transcription factor activity, core RNA polymerase II binding 
which doesn't appear to be this ticket.
Which ticket is the spreadsheet for since I don't remember seeing these.

**Comment by pgaudet** [comment]
Thanks - I moved the comment to the correct ticket https://github.com/geneontology/go-ontology/issues/16053
