### ISSUE TITLE
TF related interpro False Positives

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#204]
IPR002197 O42917 / Q10275/ P87124 / O60155 / O59676
IPR000005 P40376 / O13758

so all of the False positives to transcription factor
are generated by htese 2 families 

cheers

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/204":https://sourceforge.net/p/geneontology/annotation-issues/204

**Comment by linuxjackto1** [comment]
thanks www.movied.org
