### ISSUE TITLE
Doubled up IBA+EXP annotations (from Karen Christie)

### ISSUE THREAD

**Issue by selewis** [geneontology/go-annotation#2042]
As pointed out in https://agr-jira.atlassian.net/browse/AGR-1069, the GO ribbon displays PAINT annotations that are self-referential, i.e. there is an IBA annotation for genes which have direct experimental annotations to the same term, and thus were all/part of the source info for the IBA. These are supposed to be blocked from propagation. 

![image](https://user-images.githubusercontent.com/1519120/43477041-065e4230-94af-11e8-8d8d-0d60a9e99887.png)

(would add Dustin and Anushya but couldn't find their user names)

**Comment by pgaudet** [comment]
@dustine32 
@mugitty

**Comment by pgaudet** [comment]
In this case the IBA is self-referential, so it's not useful (and may be confusing). No IBA should have the same sequence in column 2 (object) and in column 8 (with). 

@selewis @thomaspd @huaiyumi Is this correct?

**Comment by selewis** [comment]
Yep there was a discussion, but we resolved it.

And the upshot is that this change should be backed out. The 'review'
status can be determined best be determined by their usage in the "with"
field of the IBAs. No self-referential annotations should exist.

**Comment by selewis** [comment]
Yes, correct.

**Comment by hattrill** [comment]
Today's discussion on the call has left me confused. It seems like these redundant annotations are intentional and here to stay. 
Is this the plan?

**Comment by selewis** [comment]
That's what @thomaspd is arguing for, the rationale being that the additional annotation from PAINT provides an added level of confidence. I can understand that. But given that rationale, then we really should be considering this more broadly. If more generally the idea is to indicate whenever, however the ascribing of a given function/process/location to a given gene product has been reviewed and confirmed, then it is time to consider the best way to designate confidence and how it was gained. Is it by creating a new "annotation"? (i.e. simply by amassing annotations there is greater confidence?) Or should we consider the collection of evidence for any given assertion as a whole? (with some evidence being experimental, some phylo review, some expert review, etc.) What are the implications for enrichment for example? 

I am in favor of a more general discussion first rather than jumping right in without thinking it through fully.

**Comment by pgaudet** [comment]
I've added this to the Montreal meeting agenda
http://wiki.geneontology.org/index.php/2018_Montreal_GOC_Meeting_Agenda

It could be a great topic for a break group.

**Comment by srengel** [comment]
i don't support this idea that the circular annotations provide more info.  they are circular!

**Comment by thomaspd** [comment]
They're never completely circular.  There is always additional curation that was done to produce any IBA annotation: 1) the experimental annotation was reviewed again, 2) the evolution of related sequences was reviewed and the annotated function was deemed to have been conserved, and 3) other annotations for related sequences were found to have been consistent with the annotated function.  The with field of an IBA always includes more evidence, namely the stable identifier of the ancestral gene in which that function was first inferred to have appeared.  So I think these are valid as additional annotations and are not completely redundant, as the evidence is different from the EXP.

However, I do agree that from the perspective of most uses of GO annotations, they are redundant, but this is true of all annotations of a given gene to the same term, that differ only in using a different evidence code and/or reference.  There is a fair amount of this redundancy in the GO database, at least for some organisms.  We should handle this type of redundancy in a consistent way, but I don't think we have Consortium-wide guidelines for this yet, and there is no collapsing/filtering done in AmiGO.  For example, I know PomBase filters out any IEA's that are to the same term as an EXP, and we could develop GOC standards for collapsing/filtering of annotations.

**Comment by hattrill** [comment]
We also filter out redundant IEAs. We feel the same way about IEAs as we do IBAs -for us they are useful gap-fillers. We haven't added a filter for IBAs though as dev time is somewhat limited and it can't just be bolted on to the IEA filter.

I do feel like this could be a good method of validating/building evidence. Many of the model organisms are mature experimental systems - it would be nice to be able to display demonstrated conservation of function in some manner (to some extent, the stacked ribbons in the Alliance gene pages did this while they existed, but were not purely experimental - which was a bit of a shame), but adding redundant non-experimental annotations is not what we want - we are trying to get rid of these to ease the burden on the eyes!
Anyway, I agree, it would be timely to have a discussion about redundancy with regard to non-experimental evidence codes.

**Comment by selewis** [comment]
@hattrill - as regards ribbon specifically, it would be quite easy to incorporate a prioritized display of the "annotations" for a given term, that is, EXP (with backing IBA) first, if none then EXP (no IBA), if none then ... and so forth. If we implemented this as a generalized service then any display could present support for a GP association to a given term in a ranked manner. Our perspective needs a subtle shift in that the "annotation" is solely a given GP to a given term (i.e. each paper or compute is not itself an annotation, but a another piece of evidence for the GP<->term association). For that association/annotation there is more of less evidence in support that can indicate our 'confidence'.

**Comment by pgaudet** [comment]
I just think we need to distinguish the **data** from the **display**. In AmiGO it makes a lot of sense to filter and collapse evidences like pombase does (I am naming pombase because I've looked at it, not necessarily because it's the only one). 

However the full data could be available somewhere for download and analysis. 

Pascale

**Comment by hattrill** [comment]
Adding an example of a circular annotation (with no extra evidence) - Tsc1, FBgn0026317
![screen shot 2018-08-22 at 08 43 52](https://user-images.githubusercontent.com/11865746/44450041-d38c0f00-a5e7-11e8-803d-120bcf6863ce.png)

**Comment by huaiyumi** [comment]
This seems to be the same as #2049 . I believe it has been addressed.
