### ISSUE TITLE
PAINT:circular transfer of annotations 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2049]
D.mel grh, FBgn0259211
(P13002/grainy head)
http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0259211

Has IBA-evidenced annotations derived from itself (FB:FBgn0259211)

P13002/grainy head/FBgn0259211

As does Grhl1, MGI:2182540
http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:2182540

PANTHER:PTN000867451
PANTHER:PTN000112980

Although the date stamp is: 20170228, this seems recent as I can't see it in my files over the past couple of months. Has a sanity check failed or is this a one-off example?

**Comment by hattrill** [comment]
Tagging @ukemi as MGI gene in example.

**Comment by hattrill** [comment]
Can I ask how long it has been there?

 I think that perhaps we haven't seen this before as Protein2GO may have been screening this out of the files that we pick up....or I could be barking up the wrong tree!

**Comment by huaiyumi** [comment]
This has been discussed at the consortium level. The decision is that IBAs are allowed to leaf sequences that have experimental annotation to the same term and are used as evidence for the IBD annotation.
