### ISSUE TITLE
    	  IPR002129 Pyridoxal-dependent decarboxylase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#205]
IPR002129 Pyridoxal-dependent decarboxylase is picked
up by dicty sphingosine-1-phosphate lyase (DDB0214888),
which is involved in lipid metabolism. Could we change
the mapping "GO:0006520 amino acid metabolism" to its
parent " GO:0019752 : carboxylic acid metabolism"?

Thanks, Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/205":https://sourceforge.net/p/geneontology/annotation-issues/205

**Comment by linuxjackto1** [comment]
thanks www.movied.org
