### ISSUE TITLE
IPR003538 and GO:0031992 energy transducer activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2050]
Is it correct that IPR003538 is annotated to GO:0031992 energy transducer activity? Seems odd to me. 

Thanks, Pascale

**Comment by asangrador** [comment]
I think it is based in the fact that it couples cytoplasmic membrane electrochemical potential to  transport, see paper : 'TonB protein appears to transduce energy by shuttling between the cytoplasmic membrane and the outer membrane in Escherichia coli' (PMID:9159515).  May be this is not the meaning it is supposed to have in GO? Description in GO: The biological transducer activity that accepts energy and converts it to another form, often by transfer to another molecule within the cell.

**Comment by pgaudet** [comment]
Right, I do't think this is much used like this - This is the first time I see a transporter annotated like this. Can you check if there are other cases?

**Comment by asangrador** [comment]
I have removed the term for IPR003538. I have checked and we do not have more cases of this term in InterPro. For IPR003538, probably we used the term after Uniprot annotation for E. coli protein P02929 (https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P02929).

**Comment by pgaudet** [comment]
Thanks. A created another ticket to ask the EcoCyc annotations to be reviewed.

**Comment by pgaudet** [comment]
Hi @asangrador 
I am sorry, in fact the annotation was correct, see https://github.com/geneontology/go-annotation/issues/2054

Please restore!

Best regards, Pascale

**Comment by asangrador** [comment]
Yes, I followed #2054 and I have restored the annotation.
Cheers,
