### ISSUE TITLE
Review annotations to 'GO:0045026 plasma membrane fusion'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2051]
While working on this ontology ticket: 
https://github.com/geneontology/go-ontology/issues/15939

We noticed that annotations to this term could be more precise, and in some cases seem incorrect: 

https://docs.google.com/spreadsheets/d/1YabtRE8xGp-mqpXItOYZNjT6M6WiS_GnL95gs_rre3Q/edit#gid=0

Groups | Number annotations
-- | --
CAFA | 1
MGI | 4
UniProt | 19
WB | 8

**Comment by vanaukenk** [comment]
I've reviewed the C. elegans annotations:
The annotations to eff-1 could be changed to cell-cell fusion when that term becomes available.  
The annotation to acn-1 was kept but given a new gp2term relation of 'acts upstream of or within, positive effect'.  C. elegans ACN-1 lacks some of the key residues required for ACE activity and has some additional structural features that leave open the possibility that is has a more direct role in cell-cell fusion.
Four annotations were removed, but noted as they would make good GO-CAM models.
I'll leave myself assigned to this ticket to update the eff-1 annotations when possible.

**Comment by ggeorghiou** [comment]
UniProt and CAFA are done.

**Comment by LiNiMGI** [comment]
MGI done. Waiting for the new term to update our GO EI.

**Comment by pgaudet** [comment]
The new term is now in the ontology - it should be available for annotation soon. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@bmeldal - is there anything else you need to address for this ticket?  If not, then I think it's okay to close.

**Comment by bmeldal** [comment]
I updated it but didn't comment.
