### ISSUE TITLE
Review annotations to regulation of glucose import in response to insulin stimulus	

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2052]
Most of them can be moved to either

    GO:0008286 insulin receptor signaling pathway
    GO:0046626 regulation of insulin receptor signaling pathway
    GO:0042593 glucose homeostasis
    GO:0001678 cellular glucose homeostasis

Contributor   (Assigned by) | Number annotations
-- | --
AgBase | 4
MGI | 8
RGD | 5
UniProt | 9

https://docs.google.com/spreadsheets/d/1C7Y1KucIrPzVRm_L44_mQ-6sp0EM6WjHSpoSnJDIn1Q/edit#gid=0

**Comment by slaulederkind** [comment]
Is the whole "glucose import" branch being cut?

**Comment by pgaudet** [comment]
No, not at all. Although generally I would like to remove the terms that are just 'x import', in favor of terms that say where the substance is being imported (it doesn't add that much information to group 'glucose import into cell' and 'glucose import into mitochondrion'.

And the present ticket is concerned with 'regulation of glucose import' (or transport), which in most cases could be replaced by a more interesting sigalling annotation. 

I admit I could have given a little bit of an explanation ! 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi,
The UniProt EBI annotations have been reviewed and the spreadsheet undated. I have labeled the SIB annotations that I can't change, with a tag at the end of the relevant lines. @sylvainpoux could you look into them (there are 6 left)?
Thanks,
Penelope

**Comment by slaulederkind** [comment]
RGD annotations have all been changed.

**Comment by pgaudet** [comment]
Term is now obsoleted. Remaining annotations will be flagged by annotation QC checks.
