### ISSUE TITLE
Review annotations to GO:0000920 cell separation after cytokinesis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2053]
Hello, 

'cell separation after cytokinesis' only occurs in organisms with cell walls (see https://github.com/geneontology/go-ontology/issues/16238). 

For other organisms, the term to use is 'GO:0061952  midbody abscission' 
(suggestions for synonyms are welcome! since this term was never found) 

Group | Number of annotations
-- | --
AgBase | 1
ComplexPortal | 2
dictyBase | 8
FlyBase | 2
UniProt | 19

https://docs.google.com/spreadsheets/d/16CP3DOELoEYayToW41SWg_dK2iHuT2wXIRkxPEfl4WQ/edit#gid=0

Thanks, Pascale

**Comment by hattrill** [comment]
Done.

**Comment by ggeorghiou** [comment]
UniProt (EBI) has changed their annotations. @sylvainpoux can you have a look at the ones from SIB?

**Comment by bmeldal** [comment]
Done (there were a few more).

**Comment by pfey03** [comment]
Maybe 
synonym: daughter cell separation ?

I search Dictyostelium AND midbody and found 2, but e.g 90 papers for Dicty + cleavage furrow. So a synonym like the above would help. Thanks!

**Comment by pgaudet** [comment]
@pfey03 Did you fix the dictybase annotations ? If you did please write it on the spreadsheet. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Adding synonym here: https://github.com/geneontology/go-ontology/issues/16279
Thanks, Pascale

**Comment by pfey03** [comment]
@pgaudet I was at Dicty meeting and traveling until this WE. Will look into soon now.

Also got from EBI this weekend a new taxon restriction to GO:0000920 septum digestion after cytokinesis. Is this related? Couldn't find a separate ticket.

**Comment by pfey03** [comment]
Oh, I just saw the email we got is really weired as it has "GO:0000920 septum digestion after cytokinesis". GO:0000920 is this ticket here. I will take care of them soon catching up on a lot.

**Comment by pfey03** [comment]
I took care of all Dicty annotations. But I still do not see the synonym . When will it appear?

Thanks!

**Comment by pgaudet** [comment]
Yes @pfey03 the synonym is added, it should be visible soon.
