### ISSUE TITLE
PTN002356460 - RTK - cytoplasm and negative regulation of signaling transduction

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2057]
Please, could this node be reviewed?
http://www.pantree.org/node/annotationNode.jsp?id=PTN002356460
TYROSINE-PROTEIN KINASE RECEPTOR (PTHR24416)

'cytoplasm' and 'negative regulation of signaling transduction' are not typically what I would expect for RTKs . The former probably arises from non-signaling competent pools and the latter from very specific settings.

**Comment by vanaukenk** [comment]
We are also seeing incorrect annotations to 'negative regulation of signal transduction' for a number of C. elegans receptor tyrosine kinases.
The original single supporting experimental annotation to human ERBB3 (UniProtKB:P21860) seems to be from a paper that describes a secreted isoform of the receptor that acts as a competitive inhibitor by binding the ligand.
https://www.ncbi.nlm.nih.gov/pubmed/11389077

**Comment by thomaspd** [comment]
@marcfeuermann , can you please review the annotation of 'cytoplasm' and 'negative regulation of signaling transduction' to PTN002356460?

**Comment by huaiyumi** [comment]
I don't see 'cytoplasm' as a problem, as the protein kinase activity happens there.

**Comment by hattrill** [comment]
I do. Ask a user downloading everything under "cytoplasm" what they expect to see - how can we expect people to trust GO when we make non-intuitive rules. 
This type of annotation is ok in an extension (occurs in), but we need to ask how much harm we do when we make annotations based on opaque curator reasoning.

**Comment by marcfeuermann** [comment]
Family locked by Pascale. @pgaudet are you reviewing this one or should I do it ?

**Comment by pgaudet** [comment]
I reannotated the family. There might be other issues as this is a very large family, quite hard to annotate. 

Pascale
