### ISSUE TITLE
Rab and protein transport

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#206]
Hello, 

I am not sure all Rabs are involved in protein
transport. I would suggest removing the following
mappings: 

IPR003579 Ras small GTPase, Rab type -&gt;GO:0015031
protein transport

Thanks, Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/206":https://sourceforge.net/p/geneontology/annotation-issues/206

**Comment by linuxjackto1** [comment]
thanks www.movied.org
