### ISSUE TITLE
Develop guidelines/rules for dealing with annotation redundancy

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2060]
- [ ] Redundant annotations from pipeline predictions (F-> P or CC-> MF)

- [ ] Redundant annotations from PAINT

- [ ] Redundant annotations from IEAs

- [ ] Redundant experimental annotations from different curation groups 

- [ ] Redundant annotations to parent and child terms

**Comment by ValWood** [comment]
- [ ] redundant non experimental annotation (ISS/NAS/TAS/IC)

**Comment by pgaudet** [comment]
Duplicate of https://github.com/geneontology/go-site/issues/943
