### ISSUE TITLE
Review annotations to GO:0008137	 NADH dehydrogenase (ubiquinone) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2066]
@ValWood we need to find the proteins that need to be reviewed

**Comment by ValWood** [comment]
there ate 67 EXP annotations

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0008137&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

I'm not sure why the y need to be reviewed. clsosing
@pgaudet reopen if you remember

**Comment by pgaudet** [comment]
No idea, I thought it may have an ontology update but I cannot find anything at that time. 

Annotations look OK based on protein families.
