### ISSUE TITLE
InterPro:IPR032967 - Retinal homeobox protein Rx

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2069]
The gene products associated with InterPro:IPR032967 (Retinal homeobox protein Rx) include a number of nematode proteins for which these GO BP mappings do not apply:

GO:0043010 camera-type eye development
 
and 

GO:0007601 visual perception

A mapping to GO:0048513 'animal organ development' would probably be okay, although it is quite general.

Thanks.

**Comment by asangrador** [comment]
Thanks for letting know about this. I have removed the terms.
Cheers
