### ISSUE TITLE
spkw -> chaperone

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#207]
Hi Ev,

Swiss-port attatches the keyword chaperone to (amongst
other things) histone chaperones.

these are mapped to 'protein folding' and 'unfolded
protein binding', however the term 'histone chaperone'
does not mean that the gene product is involved in
histone folding, ;or binds unfolded histones , they are
involved in 'nucleosome assembly'

so either the usage needs changing, or the keyword
mapping need removing

cheers

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/207":https://sourceforge.net/p/geneontology/annotation-issues/207

**Comment by linuxjackto1** [comment]
thanks www.movied.org
