### ISSUE TITLE
InterPro:IPR017287 mapping to GO:0007601 visual perception 

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2070]
Hi,

Here is another InterPro domain that is present in various nematode species but also mapped to GO:0007061 visual perception.

https://www.ebi.ac.uk/interpro/entry/IPR017287
Retinal rod rhodopsin-sensitive cGMP 3', 5'-cyclic phosphodiesterase, delta subunit (IPR017287)

Thanks.

**Comment by asangrador** [comment]
I have changed the term to the parent 'sensory perception of light stimulus', whicht could also be applied to nematodes (https://www.ncbi.nlm.nih.gov/pubmed/18604203).
Cheers.
