### ISSUE TITLE
Possible sources to fix,  and GO contacts list housekeeping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2071]
based on
https://github.com/geneontology/go-site/issues/807

I will update
https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

but some of these  sources need to be tracked down and fixed:
- [ ]  286 WormBase -> WB @vanaukenk 
- [x] 2 FLYBASE -> FlyBase @hattrill 
- [ ] 3 AGBASE -> AgBase @jinhuiz
- [ ]   3 GO_CENTRAL ->@pgaudet @cmungall 
- [ ]  271 COLLECTF -> 5320 CollecTF?    NO CONTACT PERSON , SEE BELOW

Updates to contacts file required
- [x] AspGD update the group-contacts file, currently ASPGD
- [x] update HGNC to Susan @sartweedie
- [ ] Roslin_Institute no annotation, remove from contacts file (currently assigned to Pascale) ?
- [x] change all @tonysawfordebi production to @alexsign

No contact listed  in contact file,  find and add
- [x] 10764686 RNAcentral   @AntonPetrov 
- [x]  325395 EnsemblMetazoa ADD for completion  @alexsign
- [x]  11007 EnsemblProtists       "    @alexsign
- [x]  126 PAMGO_VMD     "    @pgaudet 
- [x]  140 SynGO-UCL   "  @RLovering 
- [x]  963 ComplexPortal @bmeldal
- [ ]  1150 GONUTS   (is this the correct source?) @jimhu-tamu ?
- [ ]  1456 SGN ?  (Solanum lycopersicum )  note many of these should be High throughput, if valid at all PMID:22903030 (def NOT IDA)
- [x]  7555 CAFA @ggeorghiou 
- [ ]   CollecTF  erill (NEED GH ID)
- [ ]  47 GO_Noctua   @pgaudet ?  @cmungall  ?
- [ ]  309 ASAP ?
- [ ]  6 Eurofung ?
- [ ]  YuBioLab pengy (NEED GH ID)

Any others known?

Other updates required to contacts file:

Move the following entries to "Domain experts" section (not submitters)
- [ ] Buffallo University ?
- [ ] Chembl  @PruMM Prudence can you give us a replacement contact GitHub ID for Chembl?
- [ ] Protein Ontology ?

TBRU,   this group is  probably intending to submit, but we have no GitHub contact
- [ ] Wikidata  no annotation

**Comment by ValWood** [comment]
I also thought    54873 UniProtKB seemed very low for manual UniProtKB annotation, is something wrong there? @tonysawfordebi  @sylvainpoux

**Comment by tonysawfordebi** [comment]
What are these numbers?

**Comment by bmeldal** [comment]
I looked at the contact list and can't find Complexportal at all. I do know I added myself on *a* GO GH contact list a long time ago but that doesn't seems to have propagated. Should I change the file myself?

**Comment by tonysawfordebi** [comment]
@ValWood We're back on old ground again... there shouldn't be *any* annotations with UniProtKB in the assigned_by - the correct attribution is UniProt.

**Comment by ValWood** [comment]
Hi @bmeldal  I'm trying to ensure that each submitter has at least one contact in the contacts file, we only need one contact, but more than one is also OK.

You can edit the lines above with the correct details. Once all the info is collected I'll update the file so only one pull request is required. Just tick the line so I know your edits are done/approved.

**Comment by ValWood** [comment]
> @ValWood We're back on old ground again... there shouldn't be any annotations with UniProtKB in the assigned_by - the correct attribution is UniProt.

Sigh. That's what I thought but  I was so sure this was already addressed that  I had misremembered what was supposed to happen.
So where do the  UniProtKB come from ?

**Comment by tonysawfordebi** [comment]
That's the $64000 question...

**Comment by ValWood** [comment]
I moved the  UniProtKB to its own ticket ;)
https://github.com/geneontology/go-annotation/issues/2072

**Comment by tonysawfordebi** [comment]
I saw :)

With regard to contact addresses, you can use goa@ebi.ac.uk for all the Ensembl sources and rnacentral@gmail.com for RNAcentral. Or are you looking for GH handles?

**Comment by ValWood** [comment]
GH handles are required  for this file, so we can TAG you in tickets!

**Comment by tonysawfordebi** [comment]
OK - in that case, don't use me, as I'm going to be outta here in 85 days...

**Comment by ValWood** [comment]
So, when you go, or before we need a replacement GH handle for  ALL of your entries in this file  https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
Please nominate the appropriate people ;)

**Comment by tonysawfordebi** [comment]
Well, I'd suggest that for any kind of production-related issue tag @alexsign, and for anything that requires curator input either @ggeorghiou or @pgarmiri 

Anton Petrov is probably the best contact for RNAcentral, but I can't find his GH handle...

**Comment by ValWood** [comment]
>Anton Petrov
I have it

**Comment by bmeldal** [comment]
Ok, I ticked myself in your original ticket and taken out the question mark.
I hope that's all you need for now.

**Comment by ggeorghiou** [comment]
CollecTF is Ivan Erril - erill@umbc.edu
YuBioLab is Peng Yu - pengy@tamu.edu
Roslin Institute is managed by GOA at the moment.

**Comment by pgarmiri** [comment]
Hi @bmeldal , Hema's GH account should be @hbye. I think her funding for the complex portal is finished but I am sure she would be okay to look after existing annotations.

**Comment by bmeldal** [comment]
Ok, keep me as CP contact and if there are questions regarding Hema's annotations I'll pass them on to her.

**Comment by kltm** [comment]
People may want to refrain from putting peoples' email addresses in the clear in this thread. Possible use an internal Google Doc?

**Comment by kltm** [comment]
Please also see related:
https://github.com/geneontology/go-site/issues/512
https://github.com/geneontology/go-site/issues/685

**Comment by pgaudet** [comment]
RE @kltm 's comment about emails- at least use -AT-

**Comment by ValWood** [comment]
closing, out of date
