### ISSUE TITLE
UniProtKB as assignee

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2072]
From
https://github.com/geneontology/go-annotation/issues/2071

Where do these come from in GO?
54873 UniProtKB 

@cmungall 
@tonysawfordebi 
@kltm

**Comment by kltm** [comment]
```shell
bbop@wok:/home/skyhook/release/annotations$ zgrep -P '\d{8}\tUniProtKB' *.gaf.gz | cut -d ':' -f 1 | uniq -c
```
```
    936 ecocyc.gaf.gz
  53949 rgd.gaf.gz
      3 zfin.gaf.gz
```

**Comment by ValWood** [comment]
936 ecocyc.gaf.gz
  53949 rgd.gaf.gz
      3 zfin.gaf.gz

I  don't really understand this. If the annotations are created *by* uniprot how come they have the worn assigned by? IS this dues to a local conversion? If so, does this result in duplicate annotations ?

**Comment by ValWood** [comment]
Ah I remember.....  Everyone was fixing this s presumably the change did not filter through yet. The annotations should be unique because the submitting authority should 'trump' and be the submitter for all annotations.

If a rule was enforced the submitter could fix the files presubmission easily with a "search and replace".....

**Comment by sabrinatoro** [comment]
from ticket #1772 : 
I checked the latest ZFIN GAF (date 2018/09/13), and I cannot find any annotations with "UniProtKB" in col15. Could these annotations be coming from somewhere else but the ZFIN GAF (?? how would that be??)
Could you tell me more about these particular annotations, please? (there are only 3) I'll see if I can find them at all.
(@pgaudet @ValWood )

**Comment by tutajm** [comment]
I have checked the spec for GAF2.0 format (http://geneontology.org/page/go-annotation-file-format-20) and UniProtKB is listed there **everywhere**
