### ISSUE TITLE
Incorrect gene assignment for mouse annotation

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#2073]
We have an annotation from CACAO that has an incorrect gene assignment.

The paper is PMID:21474562 and it has GO:0016567 annotated to the Taz (MGI:109626) gene. This annotation should be modified to be the Wwtr1 (MGI:1917649) gene. Taz is a synonym for Wwtr1.

**Comment by sandyl27** [comment]
Fixed!
