### ISSUE TITLE
Question pipeline

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2075]
Hi @tonysawfordebi @kltm 

This annotation was changed on Aug 8 in Protein2GO: 

PTPN11	 [Q06124] Tyrosine-protein phosphatase non-receptor type 11		positive regulation of glucose import in response to insulin stimulus		BHF-UCL	Homo sapiens	IDA			protein		PMID:7493946	20120815

But it's still present in AmiGO today. Is this expected ? 

Thanks, Pascale

**Comment by tonysawfordebi** [comment]
As you say, this annotation was updated in our database on 8 August, and the modified version is what is now visible in QuickGO:
https://www.ebi.ac.uk/QuickGO/annotations?reference=PMID:7493946&assignedBy=BHF-UCL&geneProductId=UniProtKB:Q06124

It's also in the files published as part of last week's GOA release.

It looks like AmiGO is still showing the annotations from the previous GOA release, which was on 16 July. There was no GOA release in August.

**Comment by pgaudet** [comment]
OK that explains, thanks.
