### ISSUE TITLE
Annotation review - check use of has_input for MF annotations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2076]
On the GO-CAM calls, we have been discussing the use of has_input vs has_direct_input for Molecular Function annotations.

For conventional annotation, has_direct_input has typically been used to capture targets of an activity where there is a direct physical association between an entity and that target.  See:
http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:has_direct_input  

GO-CAM models, however, use has_input for 'direct' targets of MFs, e.g. substrates of enzymatic activities or targets of DNA binding activity.

The result is that the meaning of has_input is different depending on the source of the annotation.

We need to be consistent in our use of has_input vs has_direct_input so as a first step towards this we are asking curators to review their use of has_input in MF annotation extensions to see what the reason was for choosing has_input.  

In some cases, it may be that curators only ever used has_input (even for direct interactions) or that they began using has_input to be consistent with GO-CAM models.  For other cases, we need to know what the rationale was.

All MF annotations that used has_input as of 20180731 can be found in this spreadsheet:

https://docs.google.com/spreadsheets/d/1jKeiGVLgmR9JMerS4Is2bvfEw1WL0ZugCZpcbr3Evzk/edit#gid=0

If you used has_input to capture a direct input, you don't need to change anything in your annotations right now and you can select 'Checked (and unchanged)'.

If you used has_input to capture something that you didn't believe was direct but for which you'd like to keep the information, please just highlight those rows so we can discuss those annotations.

If you no longer wish to keep the has_input extension, feel free to remove it and mark the spreadsheet with 'Removed'.

There are some comment columns on the far-right side of the spreadsheet that note some examples of when has_input may have been used over has_direct_input; feel free to mark an 'x' in the column if you think the situation applies or add other comments or columns as needed.

We can discuss specific annotation cases as needed on future calls.  

@pfey03 
@hdrabkin 
@ukemi 
@hattrill 
@RLovering 
@suzialeksander 
@BarbaraCzub 
@ggeorghiou 
@pgarmiri

**Comment by hattrill** [comment]
@vanaukenk I have added then FlyBase annotations that currently lie in the GOA DB and do not go out via GOC to the spreadsheet.

**Comment by vanaukenk** [comment]
@hattrill - thank you!

**Comment by BarbaraCzub** [comment]
ARUK-UCL - done.

**Comment by RLovering** [comment]
Hi Kimberley there are far too many for me to tackle right now, and I am not sure why the more specfic relation is needed. Is there documentation available for all of the relation to use for MF terms eg DNA binding terms v transcription regulator activity terms?
Sorry just very busy
Ruth

**Comment by pfey03** [comment]
@vanaukenk The rows are now frozen to 103 and I cannot get to dictyBase annotations anymore as I don't seem to be able to unfreeze the rows. Would you be able to make the rows < 103 available again?
Thanks!!

**Comment by pgaudet** [comment]
hi @pfey03 I removed the filters and the hidden columns. 

Pascale

**Comment by vanaukenk** [comment]
> I am not sure why the more specfic relation is needed.

@RLovering - do you mean that you are not sure why we need 'has direct input' for MF annotation extensions?

**Comment by vanaukenk** [comment]
For GO-CAM models, though, we are only using 'has input' for capturing the targets of MFs and so we're trying to understand what curators were intending to capture with 'has input' in conventional annotations that might cause inconsistencies in interpretation if we only use 'has input' for GO MFs.

One thing I _think_ I'm seeing in conventional annotations is use of 'has input' for enzyme-substrate annotations where there wasn't additionally a demonstration of physical interaction, e.g. a pulldown or co-IP, in the paper.

Another thing I'm seeing is annotation to 'x chemical binding' with an extension of 'has input' CHEBI:x chemical identifier.

In theory, these annotations are consistent with GO-CAM and would be okay to keep as is (although I'm not sure we need the 'has input' extension for the latter).

But we need to know if there are other uses of 'has input' that won't be consistent with how we use it in GO-CAMs and thus, should be discussed further to understand if, and how, we could model that information. 

I've just added a new tab to the review spreadsheet that shows a unique list of all the MF GO terms that used 'has input' for extensions; it is mostly a mix of binding and catalytic activity terms.

**Comment by pfey03** [comment]
Also, the definition for has_input:
"p has input c iff: p is a process, c is a material entity, c is a participant in p, c is present at the start of p, and the state of c is modified during p"

Should be updated if also MF are annotated now for functions with direct binding once the whole process gets final. Just came to mind...

**Comment by ukemi** [comment]
But the process in the definition above is not restricted to GO biological processes. It would include GO molecular functions. We need to keep in mind that the relations are not restricted only to GO use, which in some cases can be confusing for GO annotators.

**Comment by pfey03** [comment]
Ah ok, thanks for that David! Process for them does not mean strictly BP, good to know.

**Comment by vanaukenk** [comment]
@pfey, are you concerned about function vs process (as used in GO) or whether binding actually qualifies as modifying the state of 'c'?

**Comment by ukemi** [comment]
Good point. Is bound-C a different state than C?

**Comment by pfey03** [comment]
If the MF modifies the entity and in oder to do has to bind, yes. I thought this is the reason now to use has_input for MF and GO CAM?

**Comment by pfey03** [comment]
Done now with reviewing Dicty

**Comment by pgarmiri** [comment]
I have just finished with reviewing the UniProt-EBI and CAFA annotations. I have added comments to the designated column.

**Comment by hdrabkin** [comment]
Will/are all of these converted to 'has_input' when imported into Noctua?

**Comment by ukemi** [comment]
https://github.com/geneontology/gocamgen/issues/49

**Comment by pgaudet** [comment]
@vanaukenk I think this can be closed ?

**Comment by RLovering** [comment]
I have checked some of the BHF annotations and Parkinson's UK annotations and I am happy that these has_input annotations are good

**Comment by srengel** [comment]
SGD done
