### ISSUE TITLE
R2TP complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#2079]
human ECD is annotated to R2TP complex, assigned by uniprot

I don't think this protein is part of this complex (it has qualifier colozalizes with) so the annotation should probably be removed? e.g. def for the coplex doesn't mention ECD

A highly conserved protein complex comprised of two ATP-dependent DNA helicases (Rvb1p and Rvb2p in yeast, Pontin52 and Reptin52 in humans), Pih1p in yeast or PIH1D1 in humans, and Tah1 in yeast or RPAP3 in humans.

**Comment by pgaudet** [comment]
Next time please provide AC numbers - so much easier!

**Comment by pgaudet** [comment]
Removed.
