### ISSUE TITLE
IPR006688 ADP-ribosylation factor: add mapping

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#208]
Hello, 

Can we add GO: 7264 "small GTPase mediated signal
transduction" to IPR006688 ADP-ribosylation factor? 

Thanks, Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/208":https://sourceforge.net/p/geneontology/annotation-issues/208

**Comment by linuxjackto1** [comment]
thanks www.movied.org
