### ISSUE TITLE
Review annotations to GO:0033216 - ferric iron import

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2084]
GO:0033216 - ferric iron import ~will be obsoleted~ will be merged into the parent GO:0006826 iron ion transport for now. , see https://github.com/geneontology/go-ontology/issues/16408

Please review your annotations (1-2 annotations per group): 

https://docs.google.com/spreadsheets/d/1R7q8p7s4m_PF5dhkW09o1ghgpyYRxdyGF7jr5Kb6ezo/edit#gid=0

It'd still be good to review anotations. 

MTBBASE @ggeorghiou
GR @jaiswalp
MGI @hdrabkin 
BHF-UCL @RLovering

**Comment by RLovering** [comment]
Hi

you have suggested I use the term endocytic iron import into cell, but as this term doesn't exist it is hard to revise the annotation.

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering I am creating the new term: 
https://github.com/geneontology/go-ontology/issues/16778

**Comment by RLovering** [comment]
thanks I have used the new term

**Comment by ggeorghiou** [comment]
Should we close this ticket seeing as all the corrections are done?

**Comment by pgaudet** [comment]
I fixed the MTBBASE annotations. 

Some Gramene annotations are left 

GR_protein:Q6L8G2
GR_protein:Q0JAT2
