### ISSUE TITLE
annotation review human Cep57

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2086]
human Cep57
https://www.uniprot.org/uniprot/Q86XR8

Centrosomal protein which may be required for microtubule attachment to centrosomes. May act by forming ring-like structures around microtubules. Mediates nuclear translocation and mitogenic activity of the internalized growth factor FGF2, but that of FGF1.1 Publication

these descriptions are conflicting because  being involved in centrosome/microtubule attachment  doesn't really coincide with  nuclear transport.

the 
protein import into nucleus, translocation
seems to come from
https://www.uniprot.org/citations/12717444
a TAS annotation, but this papers seems to be about FGF-1 and FGF-2  which are not listed as synonyms for Cep57

(note that Cep57 is also called FGF2-interacting protein. This would not be contradictory with a centrosomal role, but does not necessarily imply a role in nucleocytoplasmic transport.

**Comment by deustp01** [comment]
A two-part thought here. The first is that some proteins are good at sticking to diverse stuff. Here the authors are claiming that, unlike the case of actin, the stickiness is physiologically relevant and specific. (No clue whether the experiments really show that.) The second is a recollection from 10 years ago that, somewhere in the vicinity of the RAN small GTPase and its associated proteins there really are proteins that both play a role in transport through the nuclear pore in interphase and in mitotic spindle assembly and function during mitosis, so this pair of functions isn't a priori impossible. All our annotations for the protein are of functions involving centrosomes.

**Comment by ValWood** [comment]
It's not impossible. However there is no evidence. The paper providing the TAS for Cep57 does not mention Cep57, or its synonyms TSP57?

**Comment by ValWood** [comment]
Oh it's "translokin" in the title!
OK so this paper *Is* about cep57

**Comment by ValWood** [comment]
HA–FGF-2, which were concentrated in the centrosome area.
To determine whether the intracellular transport of exogenous
FGF-2 was dependent on microtubules, we carried out experiments
with depolymerizing drugs. Cytochalasin B, which targets actin
microfilaments (Fig. 4b, compare the actin filament distribution in
rows 4 and 5), did not alter the distribution of FGF-2 in the nuclear
region. By contrast, treatment with nocodazole, which causes
depolymerization of microtubules (Fig. 4b, compare the microtubule
organization in rows 2 and 5), prevented the appearance of
FGF-2 in the juxtanuclear region (Fig. 4b, row 3). In these cells,
punctuated FGF-2 staining was found in the cytoplasm, especially
in the vicinity of the plasma membrane. These results indicate that
the intracellular trafficking of exogenous 18K FGF-2 may be mediated
by microtubules in ABAE cells and that it correlates with the
microtubule-associated pattern of Translokin observed by
immunocytochemistry (Supplementary Information Fig. S1c).
We considered that if nuclear translocation is important for the
mitogenic activity of FGF-2, then it might be possible to restore the
mitogenic activity of Nb1a2 by fusing an NLS derived from the
SV40 T antigen (PKKKRKKV) to its N terminus. We therefore produced
and purified recombinant NLS–Nb1a2 and NLS–FGF-2 (as
a control). Both proteins showed the same affinity as wild-type
FGF-2 for immobilized heparin (data not shown). The mitogenic
activities of FGF-2 and NLS-FGF-2 were comparable (Fig. 5a);
however, fusion of the NLS to Nb1a2 strongly enhanced its mitogenic
activity, which reached roughly 60% of the value obtained
with wild-type FGF-2. The fractionation of NIH-3T3 cells that had
been stimulated or not with NLS–FGF-2 or NLS–Nb1a2 confirmed
the ability of these growth factors to be translocated to the nuclear
region (Fig. 5b). These results show that the nuclear association of
FGF-2 is essential for its mitogenic activity.
To investigate further whether Translokin is the mediator of this
translocation, we transfected NIH-3T3 cells with small interfering
RNA (siRNA) duplexes21 to reduce the expression of endogenous
Translokin. After 55 h of transfection with an siRNA targeting
Translokin or a scramble, control siRNA, cells were stimulated by
HA–FGF-2, collected and fractionated. The Translokin-specific
siRNA led to a decrease in Translokin of about 78%, whereas
β-actin remained unaffected (Fig. 5c). Immunofluorescence studies
showed that siRNA treatment di....



so I don't think
"protein import into nucleus, translocation"
(which is nucleocytoplasmic transport through the nuclear pore is exactly  the correct term for this experiment, but I don't know what is? maybe just localization? or no annotation at all....).

**Comment by ValWood** [comment]
This process *could* occur during centrosome insertion into the nuclear envelope, although I'm not sure how this happens in a closed mitosis. This would make sense for these proteins and from these results. This would rule out the nucleocytoplasmic transport term.

It would er on the side of caution and use an appropriate  "localization" term

**Comment by pgaudet** [comment]
"protein import into nucleus, translocation" was removed.
