### ISSUE TITLE
InterPro:IPR000272 mapping to GO:0006811 ion transport

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#2087]
Hi,

While doing QC review for new qualifiers I am seeing mouse genes like _Fxyd3_ annotated via this mapping. I think it might be better if this domain were mapped to the regulation terms or removed if inconsistent. Can you please check?

Thanks.

**Comment by asangrador** [comment]
I agree; I have changed the terms to regulation terms.
Cheers,
