### ISSUE TITLE
InterPro:IPR000296 mapping to GO:0005537 mannose binding, GO:0015578 mannose transmembrane transporter activity, GO:0005537 mannose binding, and GO:

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#2088]
Hi,

While doing QC review for new qualifiers I am seeing mouse genes like _M6pr_ annotated via this mapping. This gene is a mannose-6-P receptor. I'm not sure it is involved in mannose transport or binding. Can you please check?

Thanks.

**Comment by asangrador** [comment]
Thanks for letting us know. This annotation is wrong, the receptor binds mannose-6-phosphate motifs in proteins for transport from the golgi to the lysosome. I have removed the wrong annotation.
