### ISSUE TITLE
InterPro:IPR000356 mapping to GO:0007200 phospholipase C-activating G protein-coupled receptor signaling pathway

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#2089]
Hi,

While doing QC review for new qualifiers I am seeing mouse genes like P2ry2 annotated via this mapping. Are the purinergic receptors always coupled to PLC or can they be coupled to other downstream effectors?

Thanks.

**Comment by asangrador** [comment]
I think they mainly act though PLC, so the annotation does not seem wrong, but P2Y2 can also act through G12—Rho activation (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4358762/).
