### ISSUE TITLE
IPR002078 Sigma-54 factor, interaction regio

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#209]
Hello, 

"IPR002078 Sigma-54 factor, interaction region" has
mapping to "GO:0043565 sequence-specific DNA binding"
and "GO:0006355 regulation of transcription,
DNA-dependent". 

However from the description, it seems like this reigon
is involved in ATP binding, has ATPase activity, and
binds the sigma 4 factor (protein factor). It seems
like the DNA regulatory fonctions belongs to another
domain of the protein. 

Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/209":https://sourceforge.net/p/geneontology/annotation-issues/209

**Comment by linuxjackto1** [comment]
thanks www.movied.org
