### ISSUE TITLE
TAIR KT1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2095]
potassium ion transmembrane transporter activity |   | TIGR | Arabidopsis thaliana | IGI | SGD:CY162 |   | protein |   | PMID:9477572TAIR:Publication:2681 | 20030512

This is a TAIR @tberardini annotation created by TIGR.
We don't know how these get fixed as are not in protein2GO.

.

**Comment by ValWood** [comment]
we wanted to fix SGD:CY162 which is not an SGD ID. @pgaudet  will open a ticket to create a rule for this.

**Comment by tberardini** [comment]
> This is a TAIR @tberardini annotation created by TIGR.
We don't know how these get fixed as are not in protein2GO.

@ValWood : We (TAIR) can fix those types of annotations.

I replaced with SGD:CY162 with SGD:S000003665,SGD:S000001758 today.
