### ISSUE TITLE
Annotation review  cellular potassium ion transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2096]
We just merged 
Accession GO:0071804
Name cellular potassium ion transport
into
potassium ion transport

https://github.com/geneontology/go-ontology/issues/16455

These annotations  were direct to cellular potassium ion transport
 and will still be correct, but would be better migrated donw (most likely to 
potassium import across plasma membrane"?

- [ ] shw-3 |   |   | cellular potassium ion transport |   | WB | Caenorhabditis elegans | IDA |   |   | gene |   | PMID:19387491WB_REF:WBPaper00033073 | 20110923

- [x] kcnh3 | potassium voltage-gated channel, subfamily H (eag-related), member 3 |   | cellular potassium ion transport |   | ZFIN | Danio rerio | IDA |   |   | protein |   | PMID:28443815ZFIN:ZDB-PUB-180214-21 | 20180627

- [ ]  Kcnj16 | potassium voltage-gated channel subfamily J member 16 |   | cellular potassium ion transport |   | RGD | Rattus norvegicus | IDA |   | inward rectifier potassium channel pthr11767 | gene |   | PMID:19665991RGD:7247320 | 20130705

- [ ]   Kcnk9 | potassium channel, subfamily K, member 9 |   | cellular potassium ion transport |   | MGI | Mus musculus | IDA |   | potassium channel, subfamily k pthr11003 | protein |   | MGI:MGI:4830078PMID:20351106 | 20141015
 
- [ ]  Kcnk5 | potassium channel, subfamily K, member 5 |   | cellular potassium ion transport |   | MGI | Mus musculus | IDA |   | potassium channel, subfamily k pthr11003 | protein |   | MGI:MGI:4830078PMID:20351106 | 20141015

**Comment by ValWood** [comment]
pinging @slaulederkind @ukemi @suzialeksander @sabrinatoro

**Comment by sabrinatoro** [comment]
added the "potassium import across plasma membrane" annotation

**Comment by pgaudet** [comment]
I create a spreadsheet to track this review: 

https://docs.google.com/spreadsheets/d/150_k619pbncUoJPJA2CWnFSIrXRTEOufZuPFlSg1h0c/edit#gid=0

(and added ZFIN's info)

Thanks, Pascale

**Comment by pgaudet** [comment]
One WB annotation can be deepened bit it is correct.
