### ISSUE TITLE
add zinc ion binding to IPR002893 Zinc finger, MYND-t

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#210]
Add zinc ion binding (GO:0008270) to 

\- IPR002893 Zinc finger, MYND-type
- IPR000197 Zinc finger, TAZ-type
- IPR000571 Zinc finger, CCCH-type
- IPR000679 Zinc finger, GATA-type
- IPR000690 Zinc finger, C2H2-type matrin
- IPR000962 Znf_DskA_TraR
- IPR000967 Znf_NFX1
- IPR001510; Znf_PARP
- IPR001594; Znf_DHHC currently mapped to metal ion
binding)
- IPR001607; (Znf_UBP)
- IPR001876; (Znf_RanBP2)
- IPR001878; (Znf_CCHC) 
- IPR002515; (Znf_C2HC)
- IPR002694; (Znf_CHC2)
- IPR002867; (Znf_C6HC)
- IPR002926; (Znf_CONSTANS) 
- IPR003126; (Znf_Nrecognin) 
- IPR003224; (Znf_P11)
- IPR003851; (Znf_Dof) 
- IPR006564; (Znf_PMZ)
- IPR006895; (Znf_Sec23_Sec24)
- IPR007527; (Znf_SWIM) 
- IPR009349; (Znf_C2HC5) 
- IPR011011; (Znf_FYVE_PHD) 
- IPR012934; (Znf_AD)
- IPR012935; (Znf_C3HC)
- IPR013010; (Znf_SIAH)
- IPR013085; (Znf_U1-C) 
- IPR013137; (Znf_TFIIB)
- IPR013138; (Znf_TFIIS_2) 

\- IPR000058 Znf_AN1? currently : molecular_function
unknown! 

I did not include the domains that have "putative" or
"predicted" zinc binding in the description. 

Thanks, Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/210":https://sourceforge.net/p/geneontology/annotation-issues/210

**Comment by linuxjackto1** [comment]
thanks www.movied.org
