### ISSUE TITLE
	IPR036259 add mapping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2108]
Could this one be mapped to 
transmembrane transporter activity
and
transmembrane transport

(or do you know of  FP?)

**Comment by asangrador** [comment]
IPR036259 matches more than one million proteins. It is very risky to give GO annotation to this huge entries, as they always match some outliers. For example this entry matches Atg22, and  BTN1 from S. cerevisiae, involved in vacuolar transport. It is difficult to say if they are FP or more distantly related.

**Comment by ValWood** [comment]
BTN1 is a transmembrane transporter. This will be published soon (I'm going to delete this conmment though ;)


Atg22 is a presumed amino acid tranmembrane transporter. https://www.pombase.org/reference/PMID:21307582

I'm happy that the 76 fission yeast entries are all TM transporters
https://www.pombase.org/gene_subset/interpro:IPR036259

It was actually Btn1 I was trying to include, but I will  manually annotate this if you think the mapping might be dangerous.

**Comment by asangrador** [comment]
Yes, you are right about Atg22, I was thinking of plasma membrane transmembrane transport. But looking at the entry I see it matches a few 'Polyamine aminopropyltransferases' and some peptidases, so to be in the safer side I think its better to leave out the annotation for this entry. You'll have to give Btn1 manual annotation at the moment. We have other smaller entries that match Btn1, but we'll have to wait till more is known in yeast ;) and mammals to give it annotation.

**Comment by ValWood** [comment]
OK I'll update you when I have this.
v
