### ISSUE TITLE
PTN000021568 CalpC NOT calcium-dependent cysteine-type endopeptidase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2109]
Could you block calcium-dependent cysteine-type endopeptidase activity from PTN000021568 to FBgn0260450.

CalpC, FBgn0260450 lacks the catalytic residues for activity:
Q9VXH6	CalpC	NOT|involved_in	GO:0006508	proteolysis	ECO:0000320	IKR	PMID:12646209	20121101

**Comment by thomaspd** [comment]
@marcfeuermann , can you please see where these catalytic residues were lost in the tree for PTHR10183, and make the corresponding IKR loss for whichever functions were lost there?

**Comment by pgaudet** [comment]
@thomaspd @muggity

We used to take into account the NOT annotations and not propagate contradictory positive annotations. Perhaps we should also take into account IRK annotations (some of these are made manually, not by PAINT). 

What do you think ? 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
Family locked by Pascale. @pgaudet are you reviewing this one or should I do it ?

**Comment by marcfeuermann** [comment]
Very good point. I think we indeed should take into account IRK annotations (I thought it was already the case). For PTHR10183, I've checked the alignment for the presence of the 3 active sites and blocked propagation when at least one of them was absent.  @pgaudet , do you want us to keep this issue open for further discussion or should we close it ?

**Comment by pgaudet** [comment]
I dont have PTHR10183  locked !! Very strange... Can you check again ?

**Comment by pgaudet** [comment]
Never mind ! That was a while ago. 

@marcfeuermann If you blocked the annotations that's OK. In these cases I would use IRK, not just 'block' propagation (IRD).

**Comment by marcfeuermann** [comment]
It was not locked anymore when I made the corrections. I indeed used IRK, not IRD :-)
