### ISSUE TITLE
Review annotations to GO:0000983 'transcription factor activity, RNA polymerase II core promoter sequence-specific DNA binding' and GO:0001075 'transcription factor activity, RNA polymerase II core promoter sequence-specific binding involved in preinitiation complex assembly'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2111]
These terms are being merged into 

https://github.com/geneontology/go-ontology/issues/16490
GO:0016251 RNA polymerase II general transcription initiation factor activity' -

Some annotations were questionable - would people please review these: 

Contributor   (Assigned by) | COUNT
-- | --
FlyBase | 4
MGI | 2
~BHF-UCL~ fixed | 4
CAFA | 1
NTNU_SB | 2
~PomBase~ fixed | 1
SGD | 1
UniProt | 28
WB | 2

Thanks, Pascale

**Comment by hattrill** [comment]
FB fine with merge.

**Comment by hdrabkin** [comment]
Merge is fine.

**Comment by pgarmiri** [comment]
UniProt and CAFA annotations have been checked ( I only found 9 annotations though..The rest must be ISS)

**Comment by pgaudet** [comment]
Hello, 

The genes listed should really be reviewed. The term merge means that the gene products are now annotated to general transcription factor activity, which by looking at the gene names, seems incorrect. 


I think UniProt annotations were fixed by @pgarmiri , but not the others. 
 @vanaukenk, @ValWood, @hdrabkin, @hattrill, @RLovering, @srengel can you please have a look ? 
https://docs.google.com/spreadsheets/d/1aLehwUY6ixqWJF4j8uxlbH6kgKj8oALV4Sg5BGvmDKY/edit#gid=0

Thanks, Pascale

**Comment by hattrill** [comment]
Fixed ours now.

**Comment by RLovering** [comment]
done and spreadsheet updated

**Comment by pgaudet** [comment]
There are only a few annotation left: 


MGI @hdrabkin 
NTNU_SB @mlacencio
SGD @suzialeksander 
WB @vanaukenk 


Can you please check your annotations ? I think they are not GTF, they should be moved to GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific

Thanks, Pascale

**Comment by mlacencio** [comment]
done and spreadsheet updated!

**Comment by hdrabkin** [comment]
All MGI marked "contributed by UniProt" are from the GOA mouse load or goa human to mouse laod;  they will change when GOA changes; 
Done

**Comment by srengel** [comment]
SGD annotation removed.

**Comment by vanaukenk** [comment]
WormBase annotations are done; both removed.

**Comment by pgaudet** [comment]
Thanks everyone !
