### ISSUE TITLE
PTN000919759 (PTHR11728) -FBgn0003598  'Suppressor of variegation 3-7' is not a glycerol-3-phosphate dehydrogenase

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2112]
FBgn0003598 'Suppressor of variegation 3-7' is not a glycerol-3-phosphate dehydrogenase, it is a DNA binding protein involved in epigenetic silencing. 
PANTHER is practically the only algorithm that would make this call.

**Comment by pgaudet** [comment]
Thanks for reporting this. This was a tricky one, there is a duplication in flies that is easy to miss: 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/4782928/46813246-5f96f900-cd44-11e8-8da9-f55dcbae817e.png">


I cleaned up the family. 

Thanks, 

Pascale

**Comment by hattrill** [comment]
Thanks!

**Comment by sjm41** [comment]
Looks like this is still a problem, at least for Dmel.
PTHR11728 includes 5 proteins, three of which are GLYCEROL-3-PHOSPHATE DEHYDROGENASES (Gpdh1, Gpdh2, Gpdh3), but two of which are transcriptional regulators (Su(var)3-7 and CG34149):

DROME|FlyBase=FBgn0001128|UniProtKB=P13706	Glycerol-3-phosphate dehydrogenase [NAD(+)], cytoplasmic
Gpdh
ortholog	GLYCEROL-3-PHOSPHATE DEHYDROGENASE [NAD(+)]-RELATED (PTHR11728:SF8)	dehydrogenase	Drosophila melanogaster

DROME|FlyBase=FBgn0034825|UniProtKB=Q9W1U3	Glycerol-3-phosphate dehydrogenase [NAD(+)]
Gpdh2
ortholog	GLYCEROL-3-PHOSPHATE DEHYDROGENASE [NAD(+)]-RELATED (PTHR11728:SF8)	dehydrogenase	Drosophila melanogaster 

DROME|FlyBase=FBgn0263048|UniProtKB=Q8IN06	Glycerol-3-phosphate dehydrogenase [NAD(+)]
Gpdh3
ortholog	GLYCEROL-3-PHOSPHATE DEHYDROGENASE [NAD(+)]-RELATED (PTHR11728:SF8)	dehydrogenase	Drosophila melanogaster


DROME|FlyBase=FBgn0003598|UniProtKB=P20193	Protein suppressor of variegation 3-7
Su(var)3-7
ortholog	BESS DOMAIN-CONTAINING PROTEIN-RELATED (PTHR11728:SF1)	dehydrogenase	Drosophila melanogaster

DROME|FlyBase=FBgn0083985|UniProtKB=Q0KI27	BESS domain-containing protein
DmelCG34149
ortholog	BESS DOMAIN-CONTAINING PROTEIN-RELATED (PTHR11728:SF1)	dehydrogenase	Drosophila melanogaster


@pgaudet - can you have another look at this please?

**Comment by pgaudet** [comment]
Fixed

**Comment by sjm41** [comment]
Thanks @pgaudet
