### ISSUE TITLE
InterPro:IPR005775 mapping to GO:0006814 sodium ion transport 

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#2113]
Mouse gene Atp4a is getting an annotation to sodium ion transport from this interpro mapping. I do not see any evidence that this protein transports sodium. It is classified as a potassium-proton exchanger. Can you double-check the mapping?

Thanks!

**Comment by EBI-Hsinyu** [comment]
Hi! You are right. As we described in the abstract "These P-ATPases include both H+/K+-ATPases and Na+/K+-ATPases... ". Some proteins are not sodium transporters, and the GO term (GO:0006814) should not be there. Deleted now. 
Hsin-Yu
