### ISSUE TITLE
InterPro:InterPro:IPR002059 mapping to GO:0006355 regulation of transcription, DNA-templated 

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#2115]
Some proteins like CSDE1 in mouse contain this domain, but I find no evidence that this protein regulates transcription. Instead, it is thought that it regulates gene expression post-transcriptionally by interacting with RNA.  Perhaps it would be appropriate to move this mapping to regulation of gene expression?

**Comment by EBI-Hsinyu** [comment]
Hi! Thanks! I have deleted this term. 

Regards, 
Hsin-Yu
