### ISSUE TITLE
Annotation review  human Q8N1F7 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2116]
PMID:26878725

phenotypes
glomerular visceral epithelial cell development
glomerular visceral epithelial cell migration
negative regulation of hydrogen peroxide-induced cell death

background in 
https://github.com/geneontology/go-annotation/issues/1957#issuecomment-429340639

also mouse and rat annotations from the same paper.

nuclear pore is required for these processes but is not part of them (it's very indirect).

I'm also not sure that the signalling pathway shoud be annotated to the nucleoporins but for this you should refer to the signalling pathway meeting outcomes. I may have misremembered but I thinnk he decision was that the nuclear translocation step was not part of the signalling pathway.

**Comment by ValWood** [comment]
@ggeorghiou  Could you assign to appropriate UniProt person, thanks

**Comment by ggeorghiou** [comment]
Done. Sent an email to the curator responsible.

**Comment by pgaudet** [comment]
Fixed
