### ISSUE TITLE
	PANTHER:PTN000428096 (PTHR18763) replication annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2118]
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC13G7.08c

both need removing:

crb3 | Rix1 complex WD repeat sunbunit Crb3 |   | regulation of DNA-dependent DNA replication initiation |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000428096SGD:S000005126 | wd-repeat protein 18 pthr18763 | protein |   | PMID:21873635 | 20170602

  | crb3 | Rix1 complex WD repeat sunbunit Crb3 |   | pre-replicative complex assembly involved in nuclear cell cycle DNA replication |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000428096SGD:S000005126 | wd-repeat protein 18 pthr18763 | protein |   | PMID:21873635 | 20170602

**Comment by ValWood** [comment]
this one seems OK
https://www.yeastgenome.org/reference/S000148858

**Comment by pgaudet** [comment]
@ValWood Do you think only the pombe annotation should be removed, or that this annotation should not be propagated at all ? This paper seems to show a role in DNA replication: 
https://www.ncbi.nlm.nih.gov/pubmed/22421151

(I removed complex assembly from the entire tree). 

Thanks, Pascale

**Comment by ValWood** [comment]
Oh, I did not know that.  I will check with replication people.
@mah11  may know....

**Comment by mah11** [comment]
I'm just learning of this too, and I've only skimmed the paper linked above. But it does look pretty reasonable, given the origin binding and interactions with well-known replication initiation proteins. https://www.ncbi.nlm.nih.gov/pubmed/27057756 also describes similar stuff in human.

**Comment by pgaudet** [comment]
So I would lean towards keeping the annotation. Close ?

**Comment by ValWood** [comment]
yep, I mailed and expert. he didn't get back to me yet. I'll reopen if there is an issue.
