### ISSUE TITLE
IPR006762 Gtr1/RagA G protein

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#212]
On IPR006762 Gtr1/RagA G protein, I thnik we can add: 

Function = GO: 5525 GTP binding
Process = GO: 7264 small GTPase mediated signal
transduction

Thanks, Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/212":https://sourceforge.net/p/geneontology/annotation-issues/212

**Comment by linuxjackto1** [comment]
thanks www.movied.org
