### ISSUE TITLE
NACA  UniPROT description inconsistent with GO annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2120]
https://www.uniprot.org/uniprot/Q13765#family_and_domains

THis is an odd case I wondered if somehow the incorrect entry was annotated?

Uniprot describes as NACA.

The evidence I'm currently looking at seems stronger for the transcription factor role.  So far I can only see a TAS for translation

What is the  EXP EVIDENCE FOR
Nascent polypeptide-associated complex subunit alpha?

**Comment by ValWood** [comment]
This does seem to be 
Nascent polypeptide-associated complex subunit alpha
there is a NAture paper that could be used for GO. MAybe it is multifunctional. I'll take a closer look at this one.

**Comment by pgarmiri** [comment]
There are also 4 structural papers in the Interaction/Subunit Structure section of the UniProt entry.

**"The alpha and beta subunit of the nascent polypeptide-associated complex have distinct functions."**
Beatrix B., Sakai H., Wiedmann M.
J. Biol. Chem. 275:37838-37845(2000) [PubMed] [Europe PMC] [Abstract]
Cited for: FUNCTION, INTERACTION WITH BTF3, ASSOCIATION WITH RIBOSOMES, SUBCELLULAR LOCATION.
**"The alpha-chain of the nascent polypeptide-associated complex binds to and regulates FADD function."**
Stilo R., Liguoro D., di Jeso B., Leonardi A., Vito P.
Biochem. Biophys. Res. Commun. 303:1034-1041(2003) [PubMed] [Europe PMC] [Abstract]
Cited for: INTERACTION WITH FADD.
**"The crystal structure of the human nascent polypeptide-associated complex domain reveals a nucleic acid-binding region on the NACA subunit."**
Liu Y., Hu Y., Li X., Niu L., Teng M.
Biochemistry 49:2890-2896(2010) [PubMed] [Europe PMC] [Abstract]
Cited for: X-RAY CRYSTALLOGRAPHY (2.5 ANGSTROMS) OF 84-136, SUBUNIT, DNA/RNA-BINDING REGION, SUBCELLULAR LOCATION.
**"Crystal structures of NAC domains of human nascent polypeptide-associated complex (NAC) and its alphaNAC subunit."**
Wang L., Zhang W., Wang L., Zhang X.C., Li X., Rao Z.
Protein Cell 1:406-416(2010) [PubMed] [Europe PMC] [Abstract]
Cited for: X-RAY CRYSTALLOGRAPHY (1.9 ANGSTROMS) OF 79-132, SUBUNIT.

**Comment by ValWood** [comment]
transcription factor annotations are purged.
