### ISSUE TITLE
IPR001282 glucose-6-phosphate dehydrogenase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2121]
EA  with IPR001282
In pombe
https://www.pombase.org/gene/SPCC794.01c
is glucose dehydrogenaase

v

**Comment by EBI-Hsinyu** [comment]
Hi. You are right. Gcd1 differs from traditional Glc-6-P dehydrogenases in that it contains nonconsensus amino acids in its putative Glc-6-P binding pocket [PMID:28667014]. I will delete this GO term. 
Hsin-Yu
