### ISSUE TITLE
PAINT annotation review for Q15361

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2124]
https://www.uniprot.org/uniprot/Q15361

this seems to be a nucleolar, RNA polymerase I termination factor, in which case the PAINT annotation looks odd...

**Comment by marcfeuermann** [comment]
In the new PANTHER version, Q15361 is part of a small family of 23 leafs, PTHR46760, with no PAINT propagation. Any reference to polymerase II transcription has disappeared and I've updated annotation to nucleolar location and RNA polymerase I termination factor.
