### ISSUE TITLE
revised CREBB annotation 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2127]
Hi Pascale

following discussion with ENCODE I have revised dbTF CREBB Q92793 annotation to GO:0003714 transcription corepressor activity.

I guess it should be possible to pull out all annotations to enzyme activity and dbTF activity and mark these for review? Dread to think what we will get but probably needs to be done?

Ruth

**Comment by pgaudet** [comment]
We can do that with the matrix ?

**Comment by RLovering** [comment]
That was what I thought but it might be a big number
