### ISSUE TITLE
Review annotations to GO:0001199 transcription factor activity, metal ion regulated sequence-specific DNA binding & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2128]
Hello, 

A few annotations to 'GO:0001199 transcription factor activity, metal ion regulated sequence-specific DNA binding & children' seem to represent zinc finger transcription factors, not necessarily metal-ion **regulated** transcription factors. Can you please have a look ? 
https://docs.google.com/spreadsheets/d/1l1BrmgBh0vT7dbfCFfbbdNCceVw-ARXqEkvGQjeLujk/edit#gid=0

~1 pombase @ValWood~ agreed and fixed. Requirement for zinc is for DNA binding by zinc finger. No evidence that this is Zn regulated. @Antonialock  
2 TAIR @tberardini 
1 CAFA @ggeorghiou 

Thanks, Pascale

**Comment by tberardini** [comment]
Done.
Moved to GO:0001227, DNA-binding transcription repressor activity, RNA polymerase II-specific

**Comment by pgaudet** [comment]
The CAFA annotation has been disputed in P2GO. I'm closing this.
