### ISSUE TITLE
Check InterPro2GO annotations for IPR023318 and IPR014929

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2129]
**E2 binding (IPR014929)**
GO:0016881 acid-amino acid ligase activity 

**Ubiquitin activating enzyme, alpha domain superfamily (IPR023318)**
GO:0016881 acid-amino acid ligase activity 

I don't think either of these is correct.
Maybe meant to be  NEDD8 activating enzyme activity (GO:0019781) or its parent  ubiquitin-like modifier activating enzyme activity (GO:0008641)?

**Comment by sjm41** [comment]
Tagging @hattrill

**Comment by ValWood** [comment]
That's odd. I don't see this mapping  for IPR014929  in PomBase and it was removed back in 2014
https://github.com/geneontology/go-annotation/issues/1231

**Comment by asangrador** [comment]
I have removed the 'acid-amino acid ligase activity' terms for these entries. It was  just wrong, so thanks for letting us know. The annotation is from 2008 so I suspect the entry changed but somehow the GO annotation was never removed or updated. @ValWood  I don't think this is a case of wrong annotation coming back,  and we have measures to tag and avoid this now.

**Comment by sjm41** [comment]
Thanks @asangrador !

**Comment by ValWood** [comment]
That's great that the mechanism is in place to stop recurrence.   I couldn't not find any existing GO amnnotations to cause this mapping but let us know if  mappings are derived from erroneus GO annotations.
