### ISSUE TITLE
Guanine nucleotide exchange factors

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#213]
A few suggestions for mappings of Guanine nucleotide
exchange factors:  

\- IPR000651 Guanine nucleotide exchange factor for
Ras-like GTPases, N-terminal, and 
IPR001331 (CDC24), IPR001895  (CDC25) add: 
- GO: 51057 positive regulation of small GTPase
mediated signal transduction and 
- GO: 5622 intracellular

\- IPR000219 DH has no mappings. Can add: 
-GO:0005089 Rho guanyl-nucleotide exchange factor
activity 
- GO: 35025 positive regulation of Rho protein
signal transduction 
- GO: 5622 intracellular

\- IPR008937 Ras guanine nucleotide exchange factor, can
add: 
- GO: 46579 positive regulation of Ras protein
signal transduction
- GO: 5088 Ras guanyl-nucleotide exchange factor
activity
- GO: 5622 intracellular

\- IPR000904 Sec7 like: see also PMID: 10652516 
- GO: 5086 ARF guanyl-nucleotide exchange factor
activity
- GO: 5622 intracellular
- GO: new positive regulation of ARF protein signal
transduction

\- IPR006762 Gtr1/RagA G protein: 
- GO: 5087 Ran guanyl-nucleotide exchange factor activity
- GO: 5622 intracellular
- GO: new positive regulation of Ran protein signal
transduction

(see
https://sourceforge.net/tracker/?func=add&group\_id=36855&atid=440764
for new terms requests) 

thanks, Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/213":https://sourceforge.net/p/geneontology/annotation-issues/213

**Comment by linuxjackto1** [comment]
thanks www.movied.org
