### ISSUE TITLE
Question about proposed GO rule: IPI should not be used with catalytic activity molecular function terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2131]
Gorule-0000007: IPI should not be used with catalytic activity molecular function terms
We have 71 annotations failing that rule. Should we implement that ? Or is the evidence code valid for these annotations? 

https://docs.google.com/spreadsheets/d/16CRMSe5J_Hws5sMXIpLsTiFt5tSXgFkoUFfGuKx4JUw/edit#gid=0

A large fraction of these annotations are from SGD @srengel 

Should we implement this rule or not ? Thanks in advance for your input. 

Pascale

**Comment by srengel** [comment]
i'll take a quick look.  maybe we can delete some of the SGD ones.

**Comment by ValWood** [comment]
will check ours. Poss not this week.

**Comment by hdrabkin** [comment]
I assume that this rule would be IPI to the substrates of the reaction right? 
So NO ATP binding  or target binding for a kinase BUt there could be another IPI for a binding partner that is not part of the catalytic reaction..

**Comment by sabrinatoro** [comment]
ZFIN annotations have been reviewed

**Comment by srengel** [comment]
SGD annotation have all been addressed (either removed or changed).

**Comment by pgaudet** [comment]
Looks like everyone is ok with implementing this rule. 

@vanaukenk @ValWood OK with you ?

**Comment by ValWood** [comment]
GO for it. I didn't check ours yet but since there are only 3 I'm sure I can find another way.

**Comment by hdrabkin** [comment]
MGI has changed theirs

**Comment by tberardini** [comment]
Thanks, @ValWood.  I suggest applying the 'no IPI' rule to only the _is_a_ children of 'catalytic activity'.

**Comment by pgaudet** [comment]
OK I requested that we implemented that.

**Comment by pgaudet** [comment]
FlyBase @hattrill 
CACAO @sandyl27 
AspGD  	@marekskrzypek

Still have annotations to catalytic activity or children by IPI. Do you want to have a look ?

**Comment by ValWood** [comment]
I changed the 3 pombe ones to EXP because really they combine 2 pieces of data with different evidence codes...

**Comment by hattrill** [comment]
We do not have any - these are enzyme regulator terms: protein phosphatase inhibitor activity & GTPase activator activity

**Comment by pgaudet** [comment]
Thanks for checking @hattrill

**Comment by pgaudet** [comment]
So, we have 2 left: 
CACAO: 5'-3' exonuclease activity @sandyl27 
one SGN annotation. We don't have any contact for SGN - @ggeorghiou @vanaukenk Do you ?

**Comment by tberardini** [comment]
Re: SGN contact, try Lukas Mueller: @lukasmueller.

**Comment by lukasmueller** [comment]
Hello, what is this about?

cheers
Lukas

**Comment by pgaudet** [comment]
Hello @lukasmueller! How are you doing ? 

We would like to implement a rule that forbids annotating GO:catalytic activity or children using the IPI evidence code. SGN has one annotation failing that rule: see in this document
https://docs.google.com/spreadsheets/d/16CRMSe5J_Hws5sMXIpLsTiFt5tSXgFkoUFfGuKx4JUw/edit#gid=0

Can you check whether a difference evidence can be used ? 

Thanks, Pascale

**Comment by sandyl27** [comment]
CACAO is done

**Comment by pgaudet** [comment]
Hello @lukasmueller 
I am closing this ticket. We will implement this rule, so if the evidence code is not changed at SGN, this annotation will be filtered from AmiGO and not exported. 

Thanks, Pascale
