### ISSUE TITLE
Curation Doubt on GO:0008656

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2133]
_From @liviap on November 7, 2018 16:11_

Hi,
I have a curation doubt on GO:0008656 cysteine-type endopeptidase activator activity involved in apoptotic process: 
Definition: "Increases the rate of proteolysis catalyzed by a cysteine-type endopeptidase involved in the apoptotic process." 
Comments: "Examples of this are 1) granzymes that may bind to initiator caspases and cleave them, and 2) already active caspases, e.g. caspase 9, that cleave effector caspases."

I have a complex, called PIDDosome whose components are 7xCASP2:7xCRADD:5xPIDD1 and whose functions is to allow pairs of CASP2 subunits to self-cleave to release a processed and functional Caspase-2. I was wondering whether I can annotate this complex with the GO:0008656 function.
Thanks in advance
Kindest regards
Livia
@bmeldal 

_Copied from original issue: geneontology/go-ontology#16587_

**Comment by pgaudet** [comment]
_From @ukemi on November 7, 2018 18:48_

Seems reasonable to me.

**Comment by pgaudet** [comment]
_From @bmeldal on November 8, 2018 7:48_

Thanks, David. It was actually I who had doubts. Should we add a further comment that self-activation is also applicable for this term?

Would you still co-annotate with the direct term 
GO:0097153 cysteine-type endopeptidase activity involved in apoptotic process?
I guess so.

**Comment by pgaudet** [comment]
Hi @bmeldal 

GO terms don't specify the substrate, only the gene product that mediates the activity. So acting on itself is fine. I can add something to the definition, but we cannot be exhaustive relative to possible substrates. I a little reluctant to add just because then, do we want to add this to all known cases ? (protein kinases seem a good example of this) 

What do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
_From @bmeldal on November 8, 2018 9:52_

I was doubting if we did the right thing as the term has comments with examples that didn't quite fit the selfactivation situation; it mentions caspases that activate other caspases rather than themselves. Maybe I'm just too cautious. The PIDDosome is a bit of a nightmare to de-tangle, tbh.

**Comment by pgaudet** [comment]
_From @ukemi on November 8, 2018 13:5_

I think self activation doesn't just hang on this term. I think it is generally applicable as legitimate MF. @vanaukenk, @thomaspd  and @pgaudet do you agree in light of the MF refactoring? Should this be moved to the annotation tracker? It seems like more an annotation practice question than an ontology question.

**Comment by pgaudet** [comment]
_From @bmeldal on November 8, 2018 13:8_

I think it's in this paper: PMID:15073321

Yes, should be in Annotation tracker.

**Comment by thomaspd** [comment]
I think a GO-CAM might help to clarify how we should annotate these.  We want to describe the individual gene product functions to the extent possible.  At first glance (though I haven't had a chance to look closely, so those who've looked closely please correct me) it looks like maybe we can think of PIDD1 and CRADD each acting as a scaffold or adaptor (not unlike a MAP kinase cascade scaffold) to bring together the CASP2 subunits so they can cleave each other's pro-peptide.  So the PIDD1 and CRADD adaptor activities activate the CASP2 (protease) activity on CASP2, while the CASP2 activity on CASP2 activates the CASP2 activity on effector caspases.

**Comment by bmeldal** [comment]
Paul, what you describe is correct but we are annotating to the PIDDosome itself where the PIDD1 and CRADD act as a scaffold and the CASP2 selfactivates. Subsequently, CASP2 appears to dissemble from PIDD1 and CRADD and then acts as an endopeptidase on downstream targets (but apparently not on other caspases).

CASP2 is always an endopeptidase, there's no doubt.
The PIDDosome is the complex within which CASP2 selfcleaves and that selfcleavage activates it for it's downstream function. 

Therefore, the PIDDosome itself is the activator (as CASP2 doesn't selfactivate away from the complex) and its activating function is as an endopeptidase. So far, we have annotated with both terms.

You can't see the annotations yet as it's a new CP entry and still in our system.

**Comment by ValWood** [comment]
Closing as out of date. Reopen if required
