### ISSUE TITLE
Review annotations to 'GO:0033212 iron import into cell' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2134]
Hello, 

There are some errors in the annotations of 'GO:0033212 iron import into cell' and children. Possibly this is because the term used to be labeled 'iron assimilation', and several mechanisms of iron import were missing. 

I've added suggestions for all the annotations that need to be reviewed.   
https://docs.google.com/spreadsheets/d/1bwOqVnt0QUxx1TwbdzQL22ylvOXS5xJBVLGkiuel0zA/edit#gid=0

Contributor   (Assigned by)
--
Alzheimers_University_of_Toronto | 1
AspGD | 12
CACAO | 1
CGD | 7
EcoCyc | 5
MGI | 1
MTBBASE | 1
PomBase | 2
SGD | 1
UniProt | 2

Thanks, Pascale

**Comment by ukemi** [comment]
MGI annotation changed to homeostasis.

**Comment by ValWood** [comment]
I deleted ours, but then I added them back.
@Antonialock  you did the original, but at first glance this seems correct to me. The oxidase reduced the iron for transport by the transmembrane transporter?

The term used to be called 
"iron assimilation by reduction and transport" and I think it was for this process, at least originally. 


seems to fit the def
A process in which iron is solubilized by reduction from Fe3+ to Fe2+ via a cell surface reductase and subsequent transport of the iron across the membrane by iron uptake proteins.

**Comment by ValWood** [comment]
The reference for the term is this one, doesn't look right?
http://europepmc.org/abstract/MED/16963626
It's a pombe paper about iron homeostasis, but not about this process?

**Comment by ValWood** [comment]
Sorry that's  a different process
involving the 
plasma membrane ferric-chelate reductase Frp1
https://www.pombase.org/gene/SPBC1683.09c

this is 
oxidase-permease-based iron transport
(standard ferrous iron transport system?)

I'll just delete.
Val

**Comment by srengel** [comment]
just now removed the one SGD annotation.

**Comment by pgaudet** [comment]
@keseler 

> Can the reductive removal of iron from a siderophore still be considered part of the siderophore-dependent iron import process?

Yes, I think so. @marcfeuermann @Antonialock What does that seem right ?

**Comment by sandyl27** [comment]
CACAO changes made.

**Comment by pgaudet** [comment]
Hi  	@marekskrzypek
Can you look at the CDG and AspGD annotations ? https://docs.google.com/spreadsheets/d/1bwOqVnt0QUxx1TwbdzQL22ylvOXS5xJBVLGkiuel0zA/edit#gid=0


Thanks, Pascale

**Comment by marekskrzypek** [comment]
Done.

Thanks,
Marek




On Nov 26, 2018, at 8:58 AM, pgaudet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @marekskrzypek<https://github.com/marekskrzypek>
Can you look at the CDG and AspGD annotations ? https://docs.google.com/spreadsheets/d/1bwOqVnt0QUxx1TwbdzQL22ylvOXS5xJBVLGkiuel0zA/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
Thanks !
