### ISSUE TITLE
IBA	PANTHER:PTN000917495 (PTHR43828)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2136]
SPAC977.12 | L-asparaginase (predicted) |   | positive regulation of transcription involved in G1/S transition of mitotic cell cycle |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000917495PomBase:SPAC22F3.09c more... | family not named pthr43828 | protein

 plus 2 others

The annotate protein is asparaginase 
https://www.pombase.org/gene/SPAC977.12

but the protein in the "with" field is not an asparaginase, it is 

https://www.pombase.org/gene/SPAC22F3.09c

MBF transcription factor complex subunit Res2

**Comment by ValWood** [comment]
This one is tricky.
res1(SWI4)

It does bind to DNA  directly. It is part of a Transcription factor complex.


RNA polymerase II proximal promoter sequence-specific DNA binding
is OK

maybe 
DNA-binding transcription activator activity, RNA polymerase II-specific 
is wrong.
cdc10/SWI6 is the complex member conferring specificity (or so I thought)...

but maybe they both do simultaneously.

@Antonialock  is res1 a cofactor or a _bona fida_ DNA-binding transcription factor

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3019803/
it's probably contributes to with cdc10....

In Schizosaccharomyces pombe, the heterodimers Cdc10/Res1 (homolog of Swi6/Mbp1) and Cdc10/Res2 (homolog of Swi6/Swi4) play essential roles in the G1/S transition (4, 10, 36, 39, 40, 42, 51, 54, 60). It is proposed that Cdc10/Res1 and Cdc10/Res2 constitute the core MBF complex and coordinately bind to the MCB-like motif (55). Cdc10 has been shown to bind the promoter of cdc18 constitutively (58). Given that Cdc10 forms complexes with Res1 and Res2 throughout the cell cycle (55), it is conceivable that the core MBF complex Res1-Cdc10-Res2 is bound at the promoter of the target genes throughout the cell cycle. However, activation of MBF at the G1 phase is complex. It has been shown that MBF is activated by Cdc2 in the G1 phase (17, 18, 46). On the other hand, the MBF activity is also regulated by the CDK Pef1-Pas1 (52). It is therefore likely that MBF activity is regulated by multiple signaling pathways in S. pombe.

**Comment by ValWood** [comment]
Also we have a couple of weird ones which have a DNA binding function and a none DNA binding function.

Could you ask Jurg  of someone in the group about this one @Antonialock  next time you see them

**Comment by pgaudet** [comment]
@ValWood I am re-assigning this to you - let us know if you want further changes to this tree. 

Thanks, Pascale

**Comment by ValWood** [comment]
looks OK in amigo
