### ISSUE TITLE
IBA PANTHER:PTN000019791 (PTHR10177) Cyclin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2139]
rem1 is a meiosis specific cyclin

We don't annotate proliferation (it should be blocked  for direct annotation, or taxon restricted. Can't check because QuickGO isn't working)

Please remove the following

rem1 | meiosis-specific cyclin Rem1 |   | positive regulation of cell proliferation |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000019791RGD:2293 more... | cycline pthr10177 | protein |   | PMID:21873635 | 20171130

  | rem1 | meiosis-specific cyclin Rem1 |   | regulation of mitotic nuclear division |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0000404PANTHER:PTN000019791WB:WBGene00000871 | cycline pthr10177 | protein |   | PMID:21873635 | 20171130

meiosis-specific cyclin Rem1 |   | mitotic cell cycle |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0000404FB:FBgn0010317 more... | cycline pthr10177 | protein |   | PMID:21873635 | 20171130

**Comment by pgaudet** [comment]
1. Removed ' positive regulation of cell proliferation' from the tree

2. Question: Is Cyclin E a meiotic cyclin in all organisms ? 
https://en.wikipedia.org/wiki/Cyclin_E

3. Should I remove 'regulation of mitotic nuclear division' only from  Rem1 ? The cerevisiae paralogs are annotated to G2/M transition of the mitotic cell cycle': 

<img width="669" alt="image" src="https://user-images.githubusercontent.com/4782928/54594072-3172bf00-4a30-11e9-8db1-98316a69a40e.png">


Thanks, Pascale

**Comment by ValWood** [comment]
I would need to check. All I know is that i) role of cyclins is not conserved, there is repurposing and sub functionalization  ii) some cyclins can substitute when ectopically expressed but it isn't their normal role so experiments can be confusing.

I think I would err on the side of caution and  not specify the transition by PAINTING

**Comment by pgaudet** [comment]
Removed problematic annotations for rem1. 

Pascale
