### ISSUE TITLE
spkw glycosidase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#214]
Hi Ev,

I'd like to query the Swiss-prot kw mapping of

glycosidase to carbohydrate metabolism.

For instance 
pyrimidine-specific oxidized base lesion DNA
N-glycosylase activity is a glycosidae but you
wouldn't expect this to map to carbohydrate metabolism.

Perhaps this could move up to metabolism?

cheers

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/214":https://sourceforge.net/p/geneontology/annotation-issues/214

**Comment by linuxjackto1** [comment]
thanks www.movied.org
