### ISSUE TITLE
IPR010102 ->3-chloroallyl aldehyde dehydrogenase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#215]
Hi Sandra,

I'm not sure about this mapping.

I have it on 

succinate-semialdehyde dehydrogenase [NAD(P)+] activity

could you take a look,

cheers

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/215":https://sourceforge.net/p/geneontology/annotation-issues/215

**Comment by linuxjackto1** [comment]
thanks www.movied.org
