### ISSUE TITLE
 IPR003606 Nuclear protein Zn2+-binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#216]
Hello, 

IPR003606 Nuclear protein Zn2+-binding has several
mappings but according to the description the function
of this domain is not well characterized. 

Maybe these mappings should be removed? (except zinc
ion binding)

Also, related entries (IPR001214, IPR003616 and
IPR007728) do not have amy mappings. Perhaps  IPR001214
Nuclear protein SET could have "GO:0018024
histone-lysine N-methyltransferase activity "

Thanks, Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/216":https://sourceforge.net/p/geneontology/annotation-issues/216

**Comment by linuxjackto1** [comment]
thanks www.movied.org
