### ISSUE TITLE
IPR000379 Esterase/lipase/thioesterase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#217]
IPR000379 Esterase/lipase/thioesterase: 

change function to "hydrolase activity" (GO:16787) 

add process: catabolism (GO:9056)? 

Thanks, 
Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/217":https://sourceforge.net/p/geneontology/annotation-issues/217

**Comment by linuxjackto1** [comment]
thanks www.movied.org
