### ISSUE TITLE
PANTHER:PTN000559727 (PTHR46156) CCCH Zn finger

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2179]
NURS complex/Red5 isn't export as far as I'm aware, are these phenotypes?
(in pombe red5 is  involved in the degradation of meiosis specific transcripts)

red5 | NURS complex subunit Red5 |   | poly(A)+ mRNA export from nucleus |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0035900PANTHER:PTN000559727UniProtKB:Q8IXZ2 | family not named pthr46156 | protein |   | PMID:21873635 | 20170228

**Comment by pgaudet** [comment]
Removed. Little primary data. 

The original paper mentions **regulation** of mRNA nuclear adenylation, which I think is required for export. But it's annotated to mRNA nuclear adenylation

PMID: 19364924 @hattrill Do you want to have a look ? 
(I'll check the human annotations with @sylvainpoux ) 

Thanks, Pascale

**Comment by hattrill** [comment]
There is evidence that it interacts with polyA and export factors. From mutants - decreased export of polyA RNA and increased tail length. As not much characterization beyond this paper, I think better to go with "regulation of mRNA polyadenylation" and "regulation of mRNA export from nucleus". 
I've remove the FB annotation to polyadenylation - there are some "SWIE" annotations to the fly protein, so no point in making more redundant annotations.

There is no evidence that it is functionally equivalent red5 or a component of the NURS complex, so prob not a good idea to cross-pollinate our annotations.

**Comment by pgaudet** [comment]
Disputed human annotation (Q8IXZ2) in Protein2GO.
