### ISSUE TITLE
DEAD/DEAH box helicase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#218]
Hello,

Please modify these two InterPro mappings so they are
consistent:

IPR001410 DEAD/DEAH box helicase
IPR011545 DEAD/DEAH box helicase, N-terminal

They should both have:

GO:0003676 nucleic acid binding
GO:0005524 ATP binding
GO:0008026 ATP-dependent helicase activity

Thanks,

Karen

Reported by: kpilcher

Original Ticket: "geneontology/annotation-issues/218":https://sourceforge.net/p/geneontology/annotation-issues/218

**Comment by linuxjackto1** [comment]
thanks www.movied.org
