### ISSUE TITLE
PANTHER:PTN000275634 (PTHR12412 - CAP binding protein)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2180]
not suitable for fission yeast

cbc1	nuclear cap-binding complex large subunit (predicted)		primary miRNA processing		GO_Central	Schizosaccharomyces pombe	IBA	FB:FBgn0022942
PANTHER:PTN000275634
TAIR:locus:2054137	cap binding protein pthr12412	protein		PMID:21873635	20170228

isn't involved directly in transport

cbc1 | nuclear cap-binding complex large subunit (predicted) |   | mRNA export from nucleus |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000275634UniProtKB:Q09161 | cap binding protein pthr12412 | protein |   | PMID:21873635 | 20170228

or  splicing

cbc1 | nuclear cap-binding complex large subunit (predicted) |   | mRNA splicing, via spliceosome |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000275634SGD:S000004732 | cap binding protein pthr12412 | protein |   | PMID:21873635 | 20170228

**Comment by pgaudet** [comment]
In human there is quite a bit of evidence for a role in mRNA export, so I moved the annotation up to animals.
