### ISSUE TITLE
IPR001163 Like-Sm ribonucleoprotein

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#219]
Mappings for this record are to:

GO:0006397 mRNA processing
GO:0005634 nucleus
GO:0005732 small nucleolar ribonucleoprotein complex

This is true for LSM2-8 and for snRNPs, however, LSM1
maps to this domain as well and is believed to be
cytoplasmic and involved in mRNA degradation.  I think
the mappings can stay, however, it would be useful to
include a note regarding LSM1.  I noticed a few LSM1
gene products annotated to these GO terms so a note
would help prevent aberrant annotations for LSM1.

Thanks,

Karen

Reported by: kpilcher

Original Ticket: "geneontology/annotation-issues/219":https://sourceforge.net/p/geneontology/annotation-issues/219

**Comment by linuxjackto1** [comment]
thanks www.movied.org
