### ISSUE TITLE
PAINT annotations for spindle pole body (GO:0005816)

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-annotation#2195]
spindle pole body (GO:0005816) : The microtubule organizing center in fungi; functionally homologous to the animal cell centrosome.
This term should be restricted to fungi

It looks like there are some IBA annotations to this term for zebrafish (and human, rat, mouse, fly... according to amigo). 
These annotations should be removed. 

Thanks

**Comment by ValWood** [comment]
Or go to GO:0005815  microtubule organizing center

It's a shame we have 2 term, increasingly researchers refer to yeast spindle pole bodies as "centrosomes"

Key phosphorylation events in Spc29 and Spc42 guide multiple steps of yeast centrosome duplication.

Jones MH, O'Toole ET, Fabritius AS, Muller EG, Meehl JB, Jaspersen SL, Winey M.

Mol Biol Cell. 2018 Sep 15;29(19):2280-2291. doi: 10.1091/mbc.E18-05-0296. Epub 2018 Jul 25.
PMID: 30044722

Big Lessons from Little Yeast: Budding and Fission Yeast Centrosome Structure, Duplication, and Function.

Cavanaugh AM, Jaspersen SL.

Annu Rev Genet. 2017 Nov 27;51:361-383. doi: 10.1146/annurev-genet-120116-024733. Epub 2017 Sep 15. Review.
PMID: 28934593

Molecular model of fission yeast centrosome assembly determined by superresolution imaging.

Bestul AJ, Yu Z, Unruh JR, Jaspersen SL.
J Cell Biol. 2017 Aug 7;216(8):2409-2424. doi: 10.1083/jcb.201701041. Epub 2017 Jun 15.
PMID: 28619713 


10.
Structured illumination with particle averaging reveals novel roles for yeast centrosome components during duplication.

Burns S, Avena JS, Unruh JR, Yu Z, Smith SE, Slaughter BD, Winey M, Jaspersen SL.
Elife. 2015 Sep 15;4. doi: 10.7554/eLife.08586.
PMID: 26371506 

I have been meaning to pole the Spindle community in fission yeast to see if they would object to a label change, but never got round to it.

It would be a shame to lose mammalian inferences from yeast totally though....

**Comment by ValWood** [comment]
105/145 fission yeast spindle pole body components are already identified in metazoa...(c.f. 125/145 cerevisiae). I suspect most of the remainder (except DASH complex) are also conserved I just haven't been able to detect yet. SPB components are difficult because they are often coiled-coil.

**Comment by pgaudet** [comment]
> It's a shame we have 2 term, increasingly researchers refer to yeast spindle pole bodies as "centrosomes"

Can we merge ?? 

@sabrinatoro 
I reviewed PTHR23050 and PTHR28520. I don't know which protein you were looking at; if that doesn't solve the issue please open a new ticket, citing the protein ID that had incorrect annotations. 

(I don't find any annotations to GO:0005816 in the ZFIN report: http://snapshot.geneontology.org/reports/paint_zfin-report.html - do you guys filter out annotations that fail taxon checks ? ) 

Thanks, Pascale

**Comment by ValWood** [comment]
> Can we merge ??

I think eventually, but  I need to check. There are odd things like in yeast the meiotic SPB  seeds the forespore membrane.  They are at least connected properly via microtubule organizing centre parent. I think we should wait a while to decide whether to merge. I will ask people at the next pombe meeting.

**Comment by mah11** [comment]
>> Can we merge ??
> 
> I think eventually, but I need to check. 

When you do, bear in mind that the structures are very different. Similarities are functional, not structural. That's probably why there have been separate terms all along.

**Comment by ValWood** [comment]
yep on balance good to keep separate. We might add related "centrosome" synonyms but for now the terms work well as they are.

**Comment by sabrinatoro** [comment]
Thank you @pgaudet 
I will check after our next load. 

> (I don't find any annotations to GO:0005816 in the ZFIN report: http://snapshot.geneontology.org/reports/paint_zfin-report.html - do you guys filter out annotations that fail taxon checks ? )
> 
For some reason, these went through the taxon checks... which is very weird...
