### ISSUE TITLE
Missing NOT annotation PTHR10003

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2196]
CCS human should have NOT  superoxide dismutase activity

@dustine32 can you tell where that went??? 

We probably should write a full history of annotations added and removed in the 'curators notes' file.

**Comment by pgaudet** [comment]
@dustine32 can you please have a look ?

**Comment by huaiyumi** [comment]
@dustine32 I didn't see a NOT qualifier for that node (PTN000000116). Actually I searched and didn't find a NOT qualifier to any paint annotation,  including the obsoleted annotations, until @pgaudet added on two days ago. I also searched and found other NOT annotations were loaded at the time the initial data was loaded (creation_date = 2017-02-28). I could be wrong. Please double check. If what I saw is true, the NOT annotation to this family somehow was not loaded.

**Comment by dustine32** [comment]
@huaiyumi Yeah, I guess I didn't provide any details of what I was looking at. This is looking in the GO release GAFs between 2018-04-02 and 2018-05-20:
```
$ curl -L http://release.geneontology.org/2018-04-02/annotations/goa_human.gaf.gz | gunzip | grep O14618 | grep GO:0004784
UniProtKB	O14618	CCS		GO:0004784	GO_REF:0000002	IEA	InterPro:IPR018152	F	Copper chaperone for superoxide dismutase	CCS_HUMAN|CCS	protein	taxon:9606	20180324	InterPro
UniProtKB	O14618	CCS		GO:0019430	GO_REF:0000108	IEA	GO:0004784	P	Copper chaperone for superoxide dismutase	CCS_HUMAN|CCS	protein	taxon:9606	20180324	GOC
UniProtKB	O14618	CCS	NOT	GO:0004784	PAINT_REF:10003	IBA	PANTHER:PTN000000116	F	Copper chaperone for superoxide dismutase	UniProtKB:O14618|PTN002467124	protein	taxon:9606	20170427	GO_Central
UniProtKB	O14618	CCS		GO:0004784	PAINT_REF:10003	IBA	PANTHER:PTN000000113	F	Copper chaperone for superoxide dismutase	UniProtKB:O14618|PTN002467124	protein	taxon:9606	20170427	GO_Central

$ curl -L http://release.geneontology.org/2018-05-20/annotations/goa_human.gaf.gz | gunzip | grep O14618 | grep GO:0004784
UniProtKB	O14618	CCS		GO:0004784	GO_REF:0000002	IEA	InterPro:IPR018152	F	Copper chaperone for superoxide dismutase	CCS_HUMAN|CCS	protein	taxon:9606	20180421	InterPro
UniProtKB	O14618	CCS		GO:0019430	GO_REF:0000108	IEA	GO:0004784	P	Copper chaperone for superoxide dismutase	CCS_HUMAN|CCS	protein	taxon:9606	20180421	GOC
UniProtKB	O14618	CCS		GO:0004784	PMID:21873635	IBA	EcoGene:EG13419|FB:FBgn0003462|MGI:MGI:103181|MGI:MGI:98351|PANTHER:PTN000000113|PomBase:SPAC821.10c|RGD:3731|RGD:3733|SGD:S000003865|TAIR:locus:2025595|TAIR:locus:2046168|UniProtKB:P00441|UniProtKB:P00442|UniProtKB:P9WGE9|WB:WBGene00004930|WB:WBGene00004933|ZFIN:ZDB-GENE-990415-258|dictyBase:DDB_G0267420|dictyBase:DDB_G0282993	F	Copper chaperone for superoxide dismutase	CCS_HUMAN|CCS	protein	taxon:9606	20170228	GO_Central
```

And then checking the DB for a paint annotation to PTN000000116 and GO:0004784, I saw that this record was obsoleted. Though, 2018-03-01 and 2018-05-20 is a pretty long time for this obsoletion to be reflected in the GO release GAFs so I guess a lot of things could've happened in that time. Maybe we were cleaning out dup annotations?

**Comment by pgaudet** [comment]
AFAIK someone reannotated and forgot to add the NOT back.
