### ISSUE TITLE
Review annotations to GO:0006607 - NLS-bearing protein import into nucleus

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2197]
Hello, 

Can you please review these annotations to GO:0006607 - NLS-bearing protein import into nucleus

Group | Annotations
-- | --
FlyBase | 5
SGD | 3
UniProt | 2

https://docs.google.com/spreadsheets/d/1AYSL_Lzy-BgmYKwaXyjEIOuSK2gankC1EOtSlCW_Vfo/edit?usp=sharing

(Note that this time I also listed the annotations that seemed correct to me, so we can use that in the starts in the future). 

Thanks, Pascale

**Comment by ggeorghiou** [comment]
UniProt is fixed but I don't have write access to the spreadsheet.

**Comment by suzialeksander** [comment]
Nup145 is a nuclear pore component, so this looks ok- the other protein's annotation was deleted in Protein2GO in Feb of this year, so probably shouldn't still be showing up on these sheets (Cmd1 )? 
Let me know if there's a specific reason the Nup145 annotations from SGD are flagged.

**Comment by pgaudet** [comment]
Hello, 

Thanks @hattrill @suzialeksander 
I am not sure about SGD - I asked Flybase because the spreadsheet wasn't filled, I wan't sure you had checked. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I see one annotation by MGI: MGI:MGI:103223
@hdrabkin Can you have a look ?

**Comment by hdrabkin** [comment]
what exactly is the issue here?

**Comment by dms321** [comment]
Removed

**Comment by dms321** [comment]
?Removed

________________________________

**Comment by hdrabkin** [comment]
Wish you had at second emal; if you thought it was good we could change qualilfier to ‘acts upstream or within’ ; we shouldn’t remove it just because it’s not directly involved if the data is good (assume they knocked down von-hipple and saw an effect?
