### ISSUE TITLE
 UR000106107  mappings for Ermes complex subunits

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2199]
Ermes complex

- | GO:0070096 | mitochondrial outer membrane translocase complex assembly | IEA with UR000106107

not sure who handles these?

**Comment by pedruzzi** [comment]
That's coming from HAMAP, so yes I will

**Comment by ValWood** [comment]
@pedruzzi is this still current?

Cheers

Val

**Comment by ValWood** [comment]
closing as this seems to be a partial duplicate of
https://github.com/geneontology/go-annotation/issues/2226
