### ISSUE TITLE
GO ID for UDP-D-glucuronic acid pyrophosphorylase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#220]
Could you please provide us with a GO ID regarding 
the molecular function of UDP-D-glucuronic acid 
pyrophosphorylase (for desciption see below).
Thank you very much in advance!

IUBMB Enzyme Nomenclature

EC 2.7.7.44
Common name: glucuronate-1-phosphate 
uridylyltransferase
Reaction: UTP + 1-phospho-a-D-glucuronate = 
diphosphate + UDP-glucuronate

Other names: UDP-glucuronate pyrophosphorylase; UDP-D-
glucuronic acid pyrophosphorylase; UDP-glucuronic 
acid pyrophosphorylase; uridine diphosphoglucuronic 
pyrophosphorylase

Systematic name: UTP:1-phospho-a-D-glucuronate 
uridylyltransferase

Comments: Also acts slowly with CTP.

References:

1. Roberts, R.M. The formation of uridine diphosphate-
glucuronic acid in plants. Uridine diphosphate-
glucuronic acid pyrophosphorylase from barley 
seedlings. J. Biol. Chem. 246 (1971) 4995-5002. 
[Medline UI: 71288579] 

Reported by: tsesmetz

Original Ticket: "geneontology/annotation-issues/220":https://sourceforge.net/p/geneontology/annotation-issues/220

**Comment by linuxjackto1** [comment]
thanks www.movied.org
