### ISSUE TITLE
Review annotations to GO:0000060 - protein import into nucleus, translocation, and regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2203]
Hello, 

As explained in https://github.com/geneontology/go-ontology/issues/16698, we plan to obsolete 

- GO:0000061  protein import into nucleus, substrate release: 0 annotations

- GO:0000060  protein import into nucleus, translocation: 39 EXP
- GO:0033158 regulation of protein import into nucleus, translocation: 5 EXP
- GO:0033159 negative regulation of protein import into nucleus, translocation: 5 EXP
- GO:0033160 positive regulation of protein import into nucleus, translocation: 25 EXP

The reason is that most annotations seem to be readouts; proteins annotated to this term do not mediate nuclear import. 

**A few annotations seem correct and could be moved to the parent** (see notes in the 'comments'), one by Parkinsons project @RLovering and 3 by GOA @pgarmiri 

All annotations are here: https://docs.google.com/spreadsheets/d/18NFH_K1BKBVB5Dguhz075Hj40ps-gwuqWlbG_3DHnLM/edit#gid=0

Number of annotations for each group: 

Group | Number of annotations
-- | --
AgBase | 5
BHF-UCL | 4
CAFA | 3
FlyBase | 3
MGI | 14
ParkinsonsUK-UCL | 1
PINC | 2
RGD | 10
SGD | 2
TAIR | 2
UniProt | 28

Thanks, Pascale

**Comment by srengel** [comment]
the 2 SGD annotations have been moved up to parent 6606.

**Comment by lreiser** [comment]
Of the 4 annotations to Arabidopsis genes I only saw one that was made by 
TAIR and I updated that to the parent term.
The remaining 3 Arabidopsis annotations were made by UniProt.
I can't seem to find the 'second' TAIR annotation.

**Comment by pgaudet** [comment]
@lreiser 
The second TAIR annotation is a TAS: - sorry the spreadsheet only included EXP: (now added to the spreadsheet)

RANBP1 | RAN binding protein 1 |   | protein import into nucleus, translocation |   | TAIR | Arabidopsis thaliana | TAS |   |   | protein | TAIR:locus:2178798 | PMID:9025305


This one should probably be moved up to the parent GO:0006606 protein import into nucleus. 


Thanks, Pascale

**Comment by bmeldal** [comment]
Fixed complexes. There was one that didn't get picked up by your search.

**Comment by pgaudet** [comment]
Sorry about that ! I never find them :( thanks for checking.

**Comment by bmeldal** [comment]
No, don't worry, it's because not all are exported to GO yet. I always have to check manually in our DB.
This time, I also updated the correct annotations to the appropriate protein or RNA import child terms. They may have been added after I did the curation...

**Comment by lreiser** [comment]
@pgaudet , I fixed the second one in our curation database.
