### ISSUE TITLE
Review direct annotations to 'cell population proliferation' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2204]
It has been proposed to make 'cell proliferation' a do_not_annotate term. Please review your annotations to make them more precise (or remove them if they represent a read out and the molecular mechanism by which the cell is involved in proliferation is not known).

**Comment by pgaudet** [comment]
So, how about making a rule that the extension is mandatory?

**Comment by pgaudet** [comment]
@ValWood OK for you ?

**Comment by ValWood** [comment]
yep. I suggested here that extended terms would also be OK
https://github.com/geneontology/go-ontology/issues/16659

**Comment by hattrill** [comment]
Probably take me a couple of weeks to get round to reviewing these.

**Comment by pgaudet** [comment]
yes there is no emergency for these.

**Comment by hdrabkin** [comment]
As David points out we can use extensions with these terms, so this should not be made do not annotate. A rule could be made to require an extension if the term is used.

**Comment by pfey03** [comment]
I'm done, cemented on the wrong issue yesterday.

The Dicty EXP were legacy and have been updated to term we use currently. These Dicty 'growth' IMP went years ago to 'cell proliferation' and then to 'asexual reproduction', which those were updated to.

I also deleted the legacy dictyBase ISS annotations

**Comment by vanaukenk** [comment]
The WB annotations are done.  I removed one and changed the other two to variations on mitotic cell cycle.

**Comment by tberardini** [comment]
@ebakker2 :  Still working on getting you on the list for 'Assignees'.  This is the ticket we were talking about earlier today.

**Comment by sabrinatoro** [comment]
I am working on adding the annotation extensions (I have to do it through Noctua) to the annotations. Should the required annotation extensions refer to the cell type/anatomy term? 
OR could it also be a BP, for example "cell population proliferation" -part of- "fin regeneration" ?

**Comment by hdrabkin** [comment]
MGI done

**Comment by pgarmiri** [comment]
The UniProt-EBI annotations have been checked and the actions reported in the spreadsheet.

There are 66 SWIS annotation left. I added a purple colored tag in end of each relevant row. (@sylvainpoux )
Thanks,
Penelope

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
@Achchuthan Can you please review the GeneDB genes ? The task is to either add an annotation extension or remove the annotation.

**Comment by Achchuthan** [comment]
Thanks @pgaudet. I have removed all Trypanosoma brucei and Leishmania major annotations from GeneDB. I have also emailed Uli to review Plasmodium annotations.

**Comment by uliboehme** [comment]
Thanks @Achchuthan. I have now removed the Plasmodium annotations from GeneDB. @pgaudet It would be really great if you could let me know in the future if there are any obsolete Plasmodium GO terms. Thanks!

**Comment by pgaudet** [comment]
Dear @uliboehme 

This is the error report for Plasmodium falciparum : 

http://current.geneontology.org/reports/genedb_pfalciparum-report.html

These get updated about once a month, so you can check periodically if new errors have been detected. 

Thanks, Pascale

**Comment by uliboehme** [comment]
Dear @pgaudet, 

Thanks for your reply. I was not aware of this link. 

Could you also please add me as contact for GeneDB (in addition to @Achchuthan). 

Thanks very much. 
Uli

**Comment by dsiegele** [comment]
I removed the annotation in CACAO. The [paper (Figure 1A](https://pubmed.ncbi.nlm.nih.gov/17353269/) may have evidence for regulation of cell population proliferation, but the experiment tested overexpression of MOUSE:BOP1 in cell lines so I am not sure about it.

**Comment by pgaudet** [comment]
@dsiegele In this case I think the authors are testing the viability of the cells with and without the proper factors to process the ribosomal RNA. I dont think these genes are directly involved in cell proliferation. 

Pascale
