### ISSUE TITLE
GO ID for glucuronokinase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#221]
Could you please provide us with a GO ID regarding 
the molecular function of glucuronokinase? (See below)
Thank you very much in advance! 

IUBMB Enzyme Nomenclature

EC 2.7.1.43
Common name: glucuronokinase 
Reaction: ATP + D-glucuronate = ADP + 1-phospho-a-D-
glucuronate 

Other name(s): glucuronokinase (phosphorylating); 
glucurono-glucuronokinase 

Systematic name: ATP:D-glucuronate 1-
phosphotransferase 

References: 

1. Neufeld, E.F., Feingold, D.S. and Hassid, W.Z. 
Enzymic phosphorylation of D-glucuronic acid by 
extracts from seedlings of Phaseolus aureus. Arch. 
Biochem. Biophys. 83 (1959) 96-100. 

Reported by: tsesmetz

Original Ticket: "geneontology/annotation-issues/221":https://sourceforge.net/p/geneontology/annotation-issues/221

**Comment by linuxjackto1** [comment]
thanks www.movied.org
