### ISSUE TITLE
IPR019503 family

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2211]
Hello, 

IPR019503 hits some transcription factors - at least FBgn0011656     Mef2  Myocyte enhancer factor 2

Perhaps that mapping should be removed ? 

Thanks, Pascale

**Comment by asangrador** [comment]
Hi,
I only see one match to Myocyte enhancer factor 2, isoform G  ([A0A0B4KEP4](https://www.uniprot.org/uniprot/A0A0B4KEP4)) a trembl predicted protein, but it does not match any of the others.  The rest seem to be metallopeptidases. Is there any other hit that I am missing?

**Comment by pgaudet** [comment]
I dont know, maybe not, this is the protein that was causing problems.

Pascale

**Comment by asangrador** [comment]
I have removed one of the signatures in the InterPro entry that was matching this protein, so it should not be getting this annotation anymore (after our next release).
Cheers,

**Comment by pgaudet** [comment]
great, thanks !
