### ISSUE TITLE
Review annotations to 'protein-containing complex assembly' by IMP

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2213]
Coming from https://github.com/geneontology/go-annotation/issues/2142
(and others) - many times when a part of a complex is knocked-out, the complex doesn't form. It doesn't mean that that subunit assembles it. This is a place holder to look for suspicious annotations. 

Pascale

**Comment by ValWood** [comment]
Another example of "protein complex assembly" for complex members

**Comment by ValWood** [comment]
I don't think this is done. There are still many complex members annotated to assembly of the complexes they are members of when they autonomously assembly.
