### ISSUE TITLE
InterPro annotations to biofilm matrix

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-annotation#2215]
Hello,

A few months ago we created two child terms of biofilm matrix; fungal biofilm matrix and bacterial biofilm matrix. All of the manual annotations were reviewed and moved (https://github.com/geneontology/go-annotation/issues/1964), but we missed the IEA annotations.

All of the IEAs are from InterPro and appear to be from bacterial species, therefore it should be possible to re-map the domains to GO:0097311 bacterial biofilm matrix.

Could you please take a look and see if this can be done?

Thanks,
Rachael.

**Comment by asangrador** [comment]
Hi,
We only had one annotation to biofilm matrix, and I have changed  it to bacterial biofilm matrix, as suggested.
Thanks for updating us on this.

**Comment by rachhuntley** [comment]
Thanks Amaia!
