### ISSUE TITLE
PANTHER:PTN000456925 Septate junction

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2219]
Node: PANTHER:PTN000456925 Septate junction

Several Ig-conatining domain proteins have been annotated with septate junction assembly ; GO:0019991/septate junction ; GO:0005918 from PTN000456925.

They seem to originate from one FlyBase gene - FBgn0010238 - which has IBAs evidenced by itself alone - so that circular annotation needs to be removed.

The other examples are not septate junction proteins: Ig-domains can be quite tricky to classify, so I would class everything annotated to this node as suspect.
I would also caution against using one source to propagate annotations. I wish that this was a formal rule, as it seems to come up a lot and these exact circular annotations would be prevented.

These genes:
FBgn0259714
FBgn0039617
FBgn0051646
FBgn0052791
FBgn0031725
FBgn0259245
FBgn0051708
FBgn0031837
FBgn0267428
FBgn0051814
are neuronal proteins involved in neuronal identity.
Could you remove these, please.

We have a further two annotatated from this node:
FBgn0053543
FBgn0031627
I can't really see much support for this based on orthology, although they aren't well characterised.

**Comment by selewis** [comment]
The circular IBAs have had a long-running debate. They were introduced when PAINT annotations started being exported out of the panther database by @huaiyumi and @dustine32. The resolution (regrettably IMHO) is that they are allowed (and I don't actually recall this being fully discussed at a consortium meeting). See #2049 

However the issue of requiring >1 piece of experimental evidence is something to consider. It's both a curation policy for within PAINT, but it is also something that could be determined in software and perhaps issue a warning when an annotation hinges on a single piece of evidence, whether it's IBA, ISS, etc.

**Comment by hattrill** [comment]
The problem is that is exactly circular - the gene is providing evidence for itself FBgn0010238 IBA from FBgn0010238. There are no other supporting genes. We have seen this quite a bit of late.
If we had the must have >1 annotation rule, then this would be prevented from happening - there would always have to be evidence from another entity.

**Comment by pgaudet** [comment]
I removed all annotations to that tree. It must be recurated - annotation were odd. 

Thanks, Pascale
