### ISSUE TITLE
 IPR007062 Protein phosphatase inhibitor 2 (IPP-2)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#222]
Hello, 

Could we add some process mapping to " IPR007062
Protein phosphatase inhibitor 2 (IPP-2)", like
"regulation of enzyme activity, GO: 50790" (or maybe
something mor precise? I was thinking along the lines
of "regulation of phosphatase activity, but I can't
find that term. Should I request it?)

Thanks, 

Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/222":https://sourceforge.net/p/geneontology/annotation-issues/222

**Comment by linuxjackto1** [comment]
thanks www.movied.org
