### ISSUE TITLE
annotation review  Q13127 Gene REST,

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2221]
A zinc finger protein
RE1-silencing transcription factor

outward rectifier potassium channel activity Source: UniProtKB
not so sur about some of the others either, but this is a major outlier

**Comment by RLovering** [comment]
Hi Val

if you look on my spreadsheet there is a list of emails I have sent to people about these 'outliers' Reactome is going to be addressing this

https://docs.google.com/spreadsheets/d/17mISqgr4JtlHO2ggpibcQ5pbOkes1d8v1Hh81nudpVg/edit?usp=sharing 

Ruth

**Comment by pgaudet** [comment]
Removed by @milarolo 

@RLovering  Q13127 is not in the spreadsheet - or am I missing something ?

**Comment by pgaudet** [comment]
OK thanks, I've added that the enzymatic activity has been reviewed. 

We still need to review the transcription part. 

Pascale

**Comment by ValWood** [comment]
OK  I wasn’t really looking at this from the transcription overhaul perspective. I  was looking because one of our “conserved unknowns” , the ortholog of ZNF277 was published this week:
https://www.ncbi.nlm.nih.gov/pubmed/30530495
https://www.pombase.org/gene/SPAC19B12.07c

In human, this (ZNF277) is annotated to many transcription terms, but I hadn’t made this inference in pombe since the evidence did not seem strong
lots if IEA one ISA to  https://www.uniprot.org/uniprot/Q8VIG1
which is how I ended up looking at this again. 

It’s all very odd because “REST”   does not appear to be the ortholog of ZNF277
https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPAC19B12.07c

Although they both have multiple zinc fingers.
(mouse has a ZNF277)

I hope to know more about  SPAC19B12.07c/ZNF277 one Francois has curated PMID:30530495

Cheers
Val

**Comment by ValWood** [comment]
i.e ZNF277  needs looking at...

**Comment by pgaudet** [comment]
Disputed in Protein2GO.
