### ISSUE TITLE
IPR002515 / InterPro:IPR036060

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2223]
https://www.uniprot.org/uniprot/Q7ZW29

Histone acetyltransferase Genekat7b

Zinc finger, C2HC-type (IPR002515)
Zinc finger, C2HC-type superfamily (IPR036060)

not all C2HC-type zn finger are DNA-binding transcription factors

background:
https://github.com/geneontology/go-annotation/issues/2207

**Comment by asangrador** [comment]
Following an older issue I have just changed the annotation for these entries from 'DNA-binding transcription factor activity ' to 'transcription regulator activity'. I think that would apply to all/most cases.

**Comment by ValWood** [comment]
based on this description
http://www.ebi.ac.uk/interpro/entry/IPR002515

C2HC superfamily is found outside transcription regulators.

also, there are C2Hc domains that are definitely not transcription regulators, but are not in the superfamily

https://www.pombase.org/gene_subset/interpro:IPR001878

so it might be safest not to include?

**Comment by asangrador** [comment]
Actually IPR002515 should be called C2H2C-type, which is different from IPR001878 (C2HC-type). I will correct this. In the description for IPR00251 , the first paragraph, seems to refer to zinc fingers in general.  As far as I can see all the SWPs matches for IPR002515  correspond to enzymes involved in chromatin modification or transcription factors, but to be on the safe side I will remove the transcription regulator annotation.
Cheers,

**Comment by ValWood** [comment]
OK in this case your original might be correct. This family does seems to be a) restricted to higher eukaryotes and b) more functionally related to transcription

**Comment by asangrador** [comment]
I will leave the annotation at the moment then.
