### ISSUE TITLE
Annotate cell-cell adhesion complex with GO:0005887 integral component of plasma membrane?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-annotation#2224]
Neuroligin and neurexins bind to pre-and post-synaptic plasma membranes and both have well described intracellular, transmembrane and extracellular domains. Therefore, I annotated the complex to GO:0005887 integral component of plasma membrane but Livia raised the question if the annotation holds true even though the individual proteins bind different membranes.

PMID:18084303 & 28641112 (see also F4 binding schema) (crystal structures)
PMID:16846852 & 16242404 (see also F1 domain schema) (binding to either membrane)

**Comment by RLovering** [comment]
I don't think I would describe these as membrane binding. They are located in the membrane, and neuroligin bind to neurexins (and vice versa) in adjacent cells.

I think this is a good point, both neuroligin and neurexin need to be integral to two different plasma membranes in order for the complex to be an adhesion complex.  But will annotation to GO:0005887 be misleading?

I would imagine that this will come up as a problem for other complexes? Should a receptor complex that includes an exracellular ligand be annotated with GO:0005887? Probably but it could potentially suggest all components are integral to the plasma membrane.

Ruth

**Comment by ValWood** [comment]
I came across this issue a lot when I was  re-assessing our mitochondrial annotations. 

I didn't like the fact that a complex could be "integral to membrane" and that would place all components as integral to membrane  although some clearly aren't.

**Comment by deustp01** [comment]
This looks like a variant on the standard complex annotation problem: a whole complex does something; roles for individual subunits are not clear; how should the subunits be annotated? The one solution we don't have would it this case too and it seems unlikely that the case described here can be definitively sorted out without an agreement on handling the standard problem.

**Comment by bmeldal** [comment]
Thank you for sharing our frustration! We may just need a new term for these (I'm sure it applies to several ECM complexes, too, but I can't recall an example now). 

I'm happy to discuss this in an annotation call. I can do most Tuesdays but need a heads up for the week you add it to the agenda.

**Comment by ValWood** [comment]
This is no longer an issue  because "integral component of memb rane" terms no longer exist
