### ISSUE TITLE
Review PAINT annotations to cilium and protein localization to cilium

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-annotation#2225]
This is related to the go-ontology issue #16767.
I noticed that some plant genes from Arabidopsis were being annotated to cilium (GO:0005929) and protein localization to cilium(GO:0061512).
The seem to be coming from PAINT annotations and this extends to other species that are outside of the species constraint for that term
For example, if I filter the set of annotations to protein localization to cilium
http://amigo.geneontology.org/amigo/term/GO:0061512
for Magnoliophyta there are 83 annotations that should not be there.

Can someone from PAINT remove these? Is there  a way to check on taxon constraints before propagating terms in PAINT?
Leonore

**Comment by pgaudet** [comment]
- [] PANTHER:PTHR16517
- [] PANTHER:PTHR31978
- [] PANTHER:PTHR12764
- [] PANTHER:PTHR14699
- [] PANTHER:PTHR11711
- [] PANTHER:PTHR20870

**Comment by pgaudet** [comment]
- [x] PTHR12458
- [x] PTHR16517
- [] PTHR16275
- [] PTHR33906
- [] PTHR16011
- [] PTHR12509
- [] PTHR10676
- [] PTHR12442
- [] PTHR31691
- [] PTHR14920
- [] PTHR32465
- [] PTHR21351
- [] PTHR14699
- [] PTHR10779
- [x] PTHR11711
- [] PTHR14605
- [] PTHR18962
- [] PTHR34639
- [] PTHR33958
- [] PTHR21547
- [] PTHR20931
- [] PTHR20991
- [] PTHR15722
- [] PTHR44177
- [] PTHR20870
- [] PTHR18849
- [] PTHR12764
- [] PTHR44117
- [] PTHR21625
- [] PTHR24078
- [] PTHR13376
- [] PTHR12969
- [] PTHR31432
- [] PTHR33487
- [] PTHR24098
- [] PTHR46492
- [] PTHR33865
- [] PTHR14781
- [] PTHR31363
- [] PTHR21963
- [] PTHR16074
- [] PTHR14871
- [] PTHR31978
- [] PTHR13183
- [] PTHR13236
- [] PTHR15614

**Comment by marcfeuermann** [comment]
Cilia are not present in higher plants and fungi. Chlamydomonas reinhardtii, a green algae, is a model to study cilia and is found at the "origin" of  plants in the PANTHER trees. So we set the limit for propagation of cilia-related terms at Chlamydomonas reinhardtii (CHLORE) and blocked them downstream. These families have also been updated for other terms when necessary.
