### ISSUE TITLE
PANTHER:PTN001208729  -PTHR24276  sphe does not have serine-type endopeptidase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2228]
serine-type endopeptidase activity GO:0004252 
PANTHER:PTN001208729 

Q9VXC8 - sphe - FBgn0030774 - does not have serine protease activity as there is a S to G mutation in the catalytic triad.

Note- it already has a "NOT" qualified annotation for this term.

**Comment by hattrill** [comment]
Adding to this: and sphe is not cytoplasmic either.

**Comment by pgaudet** [comment]
Removed annotations.
