### ISSUE TITLE
PTN000105428 (PTHR10985) Notch Signaling

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2229]
Panther node PTN000105428 - Hes-related bHLH transcription factors should not be annotated with 'Notch signaling pathway'. Such TF genes tend to be transcriptionally actived by Notch signaling.

We have removed the experimentally evidenced annotations for FBgn0010109 dpn.

'Notch signaling pathway' from PTN000105428 is associated with these d.mel genes:
FBgn0002609	E(spl)m3-HLH
FBgn0002631	E(spl)m5-HLH
FBgn0002633	E(spl)m7-HLH
FBgn0000591	E(spl)m8-HLH
FBgn0002733	E(spl)mbeta-HLH
FBgn0002734	E(spl)mdelta-HLH
FBgn0002735	E(spl)mgamma-HLH
FBgn0027788	Hey
FBgn0032741	Sidpn
FBgn0259938	cwo
FBgn0010109	dpn
FBgn0001168	h

**Comment by RLovering** [comment]
Hi Helen

Sorry are you saying that Notch signaling leads to an increase in the transcription of Hes. Then Hes regulates the transcription of lots of other genes? Therefore Hes is not part of the Notch signaling pathway? If so I agree.

But do you agree that RBPJ would be part of the Notch signaling pathway as it is activated by NICD and regulates the expression of the first genes transcribed following Notch signaling?

Thanks

Ruth

**Comment by hattrill** [comment]
Yes - Hes (and in the case of D.mel, these E(spl)XXX-HLH) are targets of the notch transcription complex and then these regulate the expression of other genes.

RBPJ (Su(H) to us) is definitely very much part of Notch signaling.

**Comment by pgaudet** [comment]
Removed annotations.
