### ISSUE TITLE
IPR002049 EGF-like, laminin

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#223]
Hello, 

IPR002049 EGF-like, laminin is mapped to " GO:0005198
structural molecule activity"; unfortunately many
(most) hits also hit " IPR000742 EGF-like, type 3",
"IPR006210 EGF" and/or "IPR013032 EGF-like region",
which are not structural molecules. 

Also, a protein need more than these EGF-like domains
to be a laminin. From PMID: 15979864: 

"Laminin-like domains are found in many proteins, but
for such a protein to be considered a laminin chain,
sequence data must show an unequivocal classification
as an α, β or γ chain. In particular, the presence of
an α-helical coiled-coil domain is essential in the
definition of the laminin family"

I suggest to remove that mapping,

Thanks, 
Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/223":https://sourceforge.net/p/geneontology/annotation-issues/223

**Comment by linuxjackto1** [comment]
thanks www.movied.org
