### ISSUE TITLE
PANTHER:PTN000819906 NOT CCR4-NOT complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2233]
At least 

	btf3	nascent polypeptide-associated complex beta subunit		CCR4-NOT core complex		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000819906
SGD:S000002660	transcription factor btf3 pthr10351	protein		PMID:21873635	20180521

is not CCR4-NOT in fission yeast....

the annotation comes from a reported interaction between 
nascent polypeptide-associated complex  and
 interacts with Caf130p of the CCR4-NOT complex; inbudding yeast but I haven't been able to find any other support for this , does not appear to be a bona fida member in fission yeast.

**Comment by marcfeuermann** [comment]
Sorry, I deleted my previous comment since I put it in the wrong ticket.
Marc.

**Comment by marcfeuermann** [comment]
Hi Val,
I've updated the annotation for PTHR10351. I agree with you, btf3 is indeed not part of the CCR4-NOT complex. In fact, CCR4-NOT complex interacts with NAC complex (I've worked on this subject during my 3rd post-doc !). So I've removed the PAINT propagation of "CCR4-NOT core complex".
Regards
Marc.

**Comment by ValWood** [comment]
I now know where to direct my CCR4-NOT queries :)
