### ISSUE TITLE
FCP inference annotations

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#2234]
We have three annotations that are coming in from the FXP/FXC load that have IEP to non-process terms that are generating warnings.

My understanding is that these are made if there exists an F annotation.
Like if F = transcription factor activity, a C would be generated with same evidence code and reference to "nucleus" 
These three in question have NO F annotations using IEP (which would also generate an error also. 

GO_AR:0000006 IEP usage is restricted to terms from the Biological Process ontology Warning count: 3
127142 GO_AR:0000006 Warning IEP usage is restricted to terms from the Biological Process ontology MGI MGI:109602 Gphn GO:0045211 MGI:MGI:5819334|PMID:24894704 IEP C gephyrin 5730552E08Rik|geph protein taxon:10090 20160620 GOC 
127165 GO_AR:0000006 Warning IEP usage is restricted to terms from the Biological Process ontology MGI MGI:109602 Gphn GO:0099634 MGI:MGI:5819334|PMID:24894704 IEP C gephyrin 5730552E08Rik|geph protein taxon:10090 20160620 GOC 
206334 GO_AR:0000006 Warning IEP usage is restricted to terms from the Biological Process ontology MGI MGI:1354184 Nox4 GO:0005623 MGI:MGI:3795840|PMID:18431508 IEP C NADPH oxidase 4 protein taxon:10090 20110310 GOC.

This is a weekly drop/reload run, so I can't figure why these persist
I notice that the gaf we load is dated Date: 2018/04/13
I suspect the file has been moved; used to be 
http://build.berkeleybop.org/job/gaf-check-mgi/lastBuild/artifact/gene_association.mgi.inf.gaf;
where is this now?

**Comment by ValWood** [comment]
Assigning to @cmungall  to assign to the correct GOC person

**Comment by cmungall** [comment]
you should get them from snapshot, @ukemi is with @kltm today they will explain

**Comment by hdrabkin** [comment]
We found the file in snapshot directory;  it was also renamed. I can close this

**Comment by ukemi** [comment]
@hdrabkin I don't see these in our gaf any more. Can this ticket be closed or are you still seeing these warnings?

**Comment by hdrabkin** [comment]
yes; we are good now; we were pointing to the incorrect file.
