### ISSUE TITLE
clarify docs on NOT

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-annotation#2237]
Current documentation states: 
> NOT is also used when a cited reference explicitly says (e.g. “our favorite protein is not found in the nucleus”)... (It is not generally used for negative or inconclusive experimental results.)

http://wiki.geneontology.org/index.php/Qualifiers

http://geneontology.org/page/go-annotation-conventions#qual 

Am I correct that currently, no group would annotate NOT to "our favorite protein is not found in the nucleus", and can I delete this from both sources?  This popped up way back on #3, but the documentation is still contradicting itself.

(note to self, part of https://github.com/geneontology/go-site/issues/789 on go-annotations.md)

**Comment by suzialeksander** [comment]
After GO-CAM call today, docs need to be clarified: a negative use is permitted especially in PAINT

**Comment by vanaukenk** [comment]
I've now added documentation on use of NOT in PAINT annotation and linked that to the corresponding IKR evidence code page.

**Comment by pgaudet** [comment]
@vanaukenk Ready to close ?
