### ISSUE TITLE
PTN000799655 - PTHR10048 - platelet activation

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2238]
Hi,

Can you please take a look at the propagation of GO:0030168 'platelet activation' in PTN000799655.

We are getting an annotation to 'platelet activation' for C. elegans age-1 but C. elegans does not have platelets.

Thx.

**Comment by vanaukenk** [comment]
We may also need to re-evaluate the annotation to GO:006468 'phosphorylation'.

@hdrabkin @ukemi - do you still think the original annotations to PI3Ks from PMID:15192701 are okay?  They are quite old.

**Comment by hdrabkin** [comment]
As far as I can tell they seem to be coming in from PAINT in 2017

**Comment by vanaukenk** [comment]
@hdrabkin 
I am looking at this page, for example, at MGI:

http://www.informatics.jax.org/go/marker/MGI:1206581

where I see an IDA annotation to protein phosphorylation from PMID:15192701

**Comment by hdrabkin** [comment]
Ok, did not notice; and because of that the other Pi3Ks are getting the IBA from Panther?

**Comment by vanaukenk** [comment]
Yes, it looks that way.  Thx.

**Comment by ukemi** [comment]
I see the ones from MGI in our interface. I will check it out. They look suspicious.

**Comment by hdrabkin** [comment]
So it appears the paper shows  "inhibition  of  either  PI3K  or  Akt  prevents
the  PS1-dependent  Akt  phosphorylation' ; not that PI3K is doing the Akt phosphorylation.

**Comment by ukemi** [comment]
Agreed. It is a downstream effect.

**Comment by ukemi** [comment]
causally-upstream, but important to capture the take-home message of the paper.

**Comment by hdrabkin** [comment]
I can fix now or you?

**Comment by ukemi** [comment]
Go ahead and fix. You're right, the authors argue that it is regulatory.

**Comment by ukemi** [comment]
Would be a nice one to model (hint hint).

**Comment by hdrabkin** [comment]
Done; other fish to fry for model (PRO)
