### ISSUE TITLE
Nct PANTHER:PTN000473192 only evidenced by itself

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2239]
FBgn0039234, Nct 

D.mel Nct annotated to 'Notch receptor processing' with/from FB:FBgn0039234, PANTHER:PTN000473192	

The with/from field only has one supporting gene id, but this is the gene itself.

**Comment by pgaudet** [comment]
This is to do with the redundant annotation display in AmiGO - nothing to do with PAINT annotations.

**Comment by vanaukenk** [comment]
@pgaudet 
I thought this had to do with the issue of 'self-referential' GO annotations.
@hattrill - is that right?

**Comment by pgaudet** [comment]
Yes it does - but that issue has been reported many times - there is nothing special about this instance of a self-referential annotation, it's in the PAINT model. 

We needed to decide whether to include these in AmiGO or not. The main issue is here: 
https://github.com/geneontology/go-site/issues/943

Pascale

**Comment by hattrill** [comment]
No, it is not to do with redundancy.

The Nct is the entity annotated and the ONLY entity in the 'with' - it is the evidence for itself, there is no other gene in the with. It is entirely circular, a clone of itself. Nct is not an ancestor of itself.
If there were other genes supporting the evidence, it would then be a redundant annotation.

We have seen this before and we would like to see a solution at the level of the PAINT output not at AmiGO.

**Comment by ValWood** [comment]
Isn't this just a filtering problem. You just don't want to display these annotations at FlyBase?

**Comment by hattrill** [comment]
@ValWood This is going back a bit. Might as well close this as I've argued that IBAs with totally circular evidence - no other supporting genes but itself should be stopped at source, but others don't see the issue.

**Comment by ValWood** [comment]
I kind of agree with you (and would extend the sentiment more generally to all inferences when you have good experimental data) will close since we have the ticket about redundant information≥
https://github.com/geneontology/go-site/issues/943
