### ISSUE TITLE
 IPR010921 Trp repressor/replication initiator

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#224]
Sandra, 

Did we say that the domains with high chances of false
positives should not have ay mappings? 

IPR010921 Trp repressor/replication initiator
is mapped to 'DNA binding'. 

Thanks, 
Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/224":https://sourceforge.net/p/geneontology/annotation-issues/224

**Comment by linuxjackto1** [comment]
thanks www.movied.org
