### ISSUE TITLE
PANTHER:PTN000473190 endopeptidase activity		

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2240]
Nicastrin PANTHER:PTN000473190 endopeptidase activity is a subunit of the gamma secretase complex that cleaves Notch receptor and APP, but it is the presenilin subunit that has the activity.

**Comment by ukemi** [comment]
Changed to contributes_to.

**Comment by ValWood** [comment]
Out of curiosity, will the PAINT annotation then automagically update?

**Comment by hattrill** [comment]
I am not sure that it will get updated automatically. I am re-opening until we have a confirmation from PAINT. 
I will note now, that I don't think that PAINT should propagate "contributes_to" as this qualifier has acknowledged issues with consistency of use. Ditto of coloc_with. Propagating them just amplifies the issue.

**Comment by pgaudet** [comment]
Removed annotation. (we can do 'contributes_to in PAINT but I prefer not to).

**Comment by ValWood** [comment]
I wouldn't annotate this with contribute_to anyway, since the endonuclease subunit is clearly identifiable We only use this qualifier for "emergent function of a complex"

**Comment by pgaudet** [comment]
Right
