### ISSUE TITLE
glucose-6-phosphate dehydrogenase activity IEA  with IPR022674

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2241]
Hi

O59812

https://www.pombase.org/reference/PMID:28667014

is a 

GO:0047935 | glucose 1-dehydrogenase (NADP+) activity
not

GO:0004345 | glucose-6-phosphate dehydrogenase activity

cheers

va

**Comment by asangrador** [comment]
We missed this. I have removed GO:0004345 and changed it to GO:0016614  | oxidoreductase activity, acting on CH-OH group of donors.
Thanks

**Comment by ValWood** [comment]
OK thanks, closing!
