### ISSUE TITLE
PTN000288287 Q9V3V9 EndoGI is not Ku autoantigen DNA helicase

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2242]
Please block annotations from PTN000288287 to FBgn0028515 Q9V3V9 EndoGI.

It is an endonuclease inhibitor not a helicase. https://academic.oup.com/nar/article/37/21/7312/1422223

**Comment by marcfeuermann** [comment]
PTHR12604: Annotations from PTN000288287 to FBgn0028515 Q9V3V9 EndoGI have been blocked.
Marc.

**Comment by hattrill** [comment]
Thanks
