### ISSUE TITLE
cell wall - PTN000114490 and PTN000905869 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2245]
Propagation of cell wall from PTN000114490 and PTN000905869 (both supported by only one annotation!) to organisms without cell walls.

I've requested taxon restriction on cell wall https://github.com/geneontology/go-ontology/issues/16859

**Comment by marcfeuermann** [comment]
PTHR11051 and PTHR11605 have been updated. Indeed "cell wall" is now restricted to fungi in PTHR11051 and totally removed in PTHR11605.
