### ISSUE TITLE
PAINT PIPELINE: Duplicate annotations

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2247]
We are seeing quite a lot of duplicate annotations coming from the PAINT pipeline where the only difference is a gene/protein id in the with field and the date stamp- not sure if some flush has been missed in the reload/release or it is some other issue.

For FBgn0030778
http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0030778
extracellular space:
with/from:
MGI:MGI:1934569
PANTHER:PTN000163972
RGD:2394
RGD:70931
&
extracellular space:
with/from:
MGI:MGI:1926006
MGI:MGI:1934569
PANTHER:PTN000163972
RGD:2394
RGD:70931
The only difference is "MGI:MGI:1926006" and the date stamps are 20170228 and 20181130

Same for FBgn0004432 
http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0004432
peptidyl-prolyl cis-trans isomerase activity
where there are 34 and 35 ids in with/from, the only difference being UniProtKB:Q8IXY8. The date stamp is also different here: 20181002 and 20180405

Looking back at my numbers, this problem seemed to have been increasing since September 2018 - but can't really pin it down as bit of a moving target. For us, the number prob ranges in the 100s, but difficult to estimate current numbers because of synchronicity issues. I can give some more spot-check examples, if that helps.

**Comment by pgaudet** [comment]
@kltm Any idea what's happening here ? 
Looks like the 20170228 should have been deleted when 20181130 was loaded. Thanks, Pascale

**Comment by huaiyumi** [comment]
I looked at this. This error is on the PAINT side. There are duplicated records in the gaf generated by PAINT. We will investigate and fix it.

**Comment by pgaudet** [comment]
Hi @huaiyumi Any update on this ?

**Comment by huaiyumi** [comment]
This problem will be fixed in the montly April GO release.
