### ISSUE TITLE
human SGT1 annotation review

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2248]
Probably all the TAS from ProtINc should be removed.
transcription coactivator activity
transcription by RNA polymerase II
regulation of glycolytic process

Anything from 
https://www.uniprot.org/citations/9928932
should be removed. This is a cross-species screen and there is no real evidence here for a role in transcription.

Even though there is an interaction between human hSgt1p and the DNA-binding domain of Gal4p  budding yeast does not have a Sgt1 ortholog and human does not have a GAL4 ortholog so this is all extremely tenuous.

PubMed:19919181 also looks tenuous. There might be better evidence for a role in transcription from elsewhere, but  the SPKW to  mRNA processing and  RNA splicing seem more likely. This gene product is conserved between pombe and human but absent from budding yeast, this often indicates a role in splicing  with pleiotropic effects.

**Comment by ValWood** [comment]
I  also had a transcription annotation to pombe SGt1 from the same authors. I just deleted this:

Check out FlyBase for more recent info
Ecdysoneless (Ecd) physically interacts with several components of the U5 snRPN pre-mRNA splicing complex. Its loss result in intron retention within spok, accounting for ecdysone deficiency of ecd[1] mutants. [Date last reviewed: 2016-08-18]

**Comment by ggeorghiou** [comment]
Hi @ValWood I've gone ahead and deleted the suspect annotations. Closing this ticket.
