### ISSUE TITLE
human Dr1-associated corepressor / annotation review

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2249]
DNA-binding transcription factor activity, RNA polymerase II-specific
seems incorrect?

@pgaudet   how do I tag NTNU_SB

**Comment by ValWood** [comment]
Hi Marcio, @mlacencio
could  you look at the 

DNA-binding transcription factor activity, RNA polymerase II-specific
for 
https://www.uniprot.org/uniprot/Q14919

Does this seem correct?

Cheers
Val

**Comment by mlacencio** [comment]
Hi Val,

I will discuss this issue with the other NTNU curators here and then reply you as soon as possible.

Best regards,

Marcio

**Comment by mlacencio** [comment]
Hi Val,

We have created this annotation taking into consideration Vaquerizas 2009 TF classification. At that time, Vaquerizas et al classified DRAP1 as a probable DbTF.

Although DRAP1 is classified as “Likely to be sequence specific TF” in the most recent human DbTF consensus generated by Lambert et al (2018) (humantfs.ccbr.utoronto.ca/), I think they provide weak evidence for that. Colin Logie has reviewed the list of these likely DbTFs and ended up concluding that DRAP1 should not be considered as a DbTF.

After considering all these aspects, I have deleted this annotation!

Best,

Marcio

**Comment by ValWood** [comment]
Thanks, I removed  the pombe annotation too.

**Comment by RLovering** [comment]
Hi Marcio

please could you also remove the dbTF annotation associated with the other subunit of this complex DR1

NTNU | Q01658 | DR1 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR003958

The InterPro record does not support this annotation as it this is just: This domain is found in archaebacterial histones and histone-like transcription factors from eukaryotes. This is not mapped to any GO terms.

Thanks
Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotation!

Best,

Marcio
