### ISSUE TITLE
    	  IPR001577 Peptidase M8, leishmanolysin

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#225]
IPR001577 Peptidase M8, leishmanolysin: based on the
definition, is should probably also be mapped to Zinc
ion binding? (GO: 8270)

Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/225":https://sourceforge.net/p/geneontology/annotation-issues/225

**Comment by linuxjackto1** [comment]
thanks www.movied.org
