### ISSUE TITLE
 IPR017964 	 DNA-directed DNA polymerase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2252]
https://www.uniprot.org/uniprot/O60094 is
rDNA transcriptional regulator pol5

not a polymerase.

see "caution" in Uniprot entry
Caution
Was originally thought to belong to the DNA polymerase type-B family based on conserved motifs (PubMed:12093911). Has later been shown to be unrelated to B class DNA polymerases (PubMed:12695662).2 Publications

(SGD annotation was removed today)

**Comment by asangrador** [comment]
Thanks for alerting us to this. I have removed the annotation.
