### ISSUE TITLE
RNA-binding protein with multiple splicing, RBPMS Q93062

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2253]
https://www.uniprot.org/uniprot/Q93062

Has a mixture of annotation.
It is an RNA binding protein.

transcription coactivator activity looks suspect (old paper)
or
mRNA splicing, via spliceosome Source: GO_Central PAINT

as its very unlikely to be both splicing AND transcription

**Comment by ValWood** [comment]
Actually, my concern is in the annotation of 
mde7 (pombe ortholog of RBPMS) to "splicing.

This comes from

mde7 | RNA-binding protein Mde7 |   | mRNA splicing, via spliceosome |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000827569SGD:S000000323 more... | u1 small nuclear ribonucleoprotein a/u2 small nuclear ribonucleoprotein b pthr10501 | protein |   | PMID:21873635 | 20170228


However,  YBR119W/MUD1 is not so closely related to  pombe Mde1 (they have the same RNA binding domains but are not orthologous). I suspect the annotation transfer in  PANTHER:PTN000827569 family is not conservative enough.

**Comment by marcfeuermann** [comment]
I agree, the PAINT annotation for PTHR10501 was a little bit weird. I've updated it and restricted mRNA splicing to PTN000052389.
