### ISSUE TITLE
Zinc finger FYVE domain-containing protein 9 NOT serine-type peptidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2256]
I don't see any evidence that  ZFYVE9 is a 
serine-type peptidase activity
https://www.uniprot.org/uniprot/O95405

**Comment by ValWood** [comment]
The paralog
https://www.uniprot.org/uniprot/Q7Z3T8 ZFYVE16
has
protein transporter activity Source: UniProtKB

which also looks wrong (although it does appear to be involved in endosomal transport in some way)

**Comment by pgaudet** [comment]
@sylvainpoux This is an annotation from 2001; can you please have a look maybe ?

**Comment by sylvainpoux** [comment]
Deleted
Thanks for pointing this out
S.

**Comment by pgaudet** [comment]
thanks
