### ISSUE TITLE
hdd1 what's the correct process term?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2257]
I had hdd1 as an unknown until recently, but it has been annotated in SGD as 

term=deoxyribonucleoside monophosphate catabolic process; GOid=GO:0009159; evidence=ISO; with=SGD:S000003069

so I ISS'd to it.

Then I noticed that  I had a note to update because it has been PAINTED to

	hdd1		dUMP biosynthetic process	IBA	EcoGene:EG14102
PANTHER:PTN000217770	
ASN
	hdd1			pyrimidine deoxyribonucleotide salvage		IBA	EcoGene:EG14102
PANTHER:PTN000217770

deoxyribonucleoside monophosphate catabolic process
and
dUMP biosynthetic process
seem as though they are process terms describing the reaction outputs rather than the overall process?

Is "pyrimidine deoxyribonucleotide salvage" the correct term to use here?

@suzialeksander 
@deustp01 
@pgaudet

**Comment by deustp01** [comment]
The textbook view (Wikipedia) has UMP as an end product both of de novo synthesis and of pyrimidine salvage but they arrive at that shared endpoint by different reactions so it's hard to see how one enzyme function could be part of both processes. The UniProt entries for the human (Q7Z4H3 - HDDC2) and pombe (P87242 - SPCC4G3.17) proteins both have both annotations, all as inferences from biological aspect of ancestor. No obvious experimental data here and PomBase says the pombe knockout strain is viable. Maybe both terms are too specific, and something like pyrimidine metabolic process is safer? Out of ignorance, I'm assuming that there is a fully worked out standard pathway for de novo pyrimidine synthesis in pombe and this gene product is not part of it, nor of any established salvage pathways?

**Comment by ValWood** [comment]
> I'm assuming that there is a fully worked out standard pathway for de novo pyrimidine synthesis in pombe and this gene product is not part of it, nor of any established salvage pathways?

No, its all old genetics and functional complementation! Nobody looked at it since I worked on fission yeast. We don't do metabolism very well....

**Comment by ValWood** [comment]
This particular gene  product was in my unknowns. I was going to annotate based on the PAINT inference and the SGD annotation.
I think you are correct that "pyrimidine metabolic process".

I'll ask @marcfeuermann  to remove the PAINT inference.

**Comment by pgaudet** [comment]
Fixed
