### ISSUE TITLE
IPR001474 GTP cyclohydrolase I

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#226]
Hello, 
Could we add a more specific process mapping to 
"IPR001474 GTP cyclohydrolase I"? "aromatic compound
biosynthesis" (GO: 19438) would cover both 
tetrahydrofolate and pteridine-related compounds
biosynthesis. 

Also, I suppose this is all intracellular. 

Thanks, 
Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/226":https://sourceforge.net/p/geneontology/annotation-issues/226

**Comment by linuxjackto1** [comment]
thanks www.movied.org
