### ISSUE TITLE
 KW-0269 for 	Q9USG9 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2260]
Q9USG9  has a mapping to KW-0269 

GO:0004527 | exonuclease activity

but is a 	
GO:0017005 | 3'-tyrosyl-DNA phosphodiesterase activity

v

**Comment by ValWood** [comment]
OK, I can move to the ontology tracker if necessary.

in GO nuclease is
Catalysis of the hydrolysis of ester linkages within nucleic acids.

and 3'-tyrosyl-DNA phosphodiesterase activity does not have this parentage which is suspect.
In fact I am not seeing the difference between some of the parents!

![ster phos](https://user-images.githubusercontent.com/7359272/52043767-74d4a500-2538-11e9-9e6f-40cc8bdc53c8.jpg)

**Comment by sylvainpoux** [comment]
It is why I prefer to pass to to @kaxelsen because he knows every intricacies for enzyme nomenclature. GO ontology is currently incomplete/imprecise for enzyme categories. By the way, it is perfectly possible that the case you report is incorrect in Swiss-Prot. Kristian will know

**Comment by kaxelsen** [comment]
Hi @ValWood
A priori, the two GO terms are not linked. But when you read the CC function topic of the Swiss-Prot entry you find:
CC       May have low 3'exonuclease
CC       activity and may be able to remove a single nucleoside from the
CC       3'end of DNA and RNA molecules with 3'hydroxyl groups. Has no
CC       exonuclease activity towards DNA or RNA with a 3'phosphate (By
CC       similarity)

So in this entry they are parallel.
There is no experimental evidence provided for this protein entry, so I don't know how trustworthy these annotations are.

**Comment by ValWood** [comment]
OK got it. Will close.
