### ISSUE TITLE
Thioredoxin IPR004502 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#227]
Hello, 

Thioredoxin is mapped to 'GO: electron transporter
activity ; GO:0005489' (which is being obsoleted). I
think you can change the mapping to 'thiol-disulfide
exchange intermediate activity GO: 30508'.

Thanks, 

Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/227":https://sourceforge.net/p/geneontology/annotation-issues/227

**Comment by linuxjackto1** [comment]
thanks www.movied.org
