### ISSUE TITLE
IPR020189 translational frameshifting

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2273]
for  translation elongation and termination factor eIF5A

GO:0006452 | t ranslational frameshifting | IEA with IPR020189

Is this correct?
Might be my ignorance but I thought this was a "programmed" phenomena?

**Comment by asangrador** [comment]
We got this annotation from Uniprot/SGD,  associated with cerevisiae IF5A (P19211 and P23301) and based on a paper (PMID:19424157).  Looking at the paper it seems to me that they were trying to prove that IF5A is involved in elongation (which it is) by using mutants that impaired programmed ribosomal frameshifting, but that does not mean that eIF5A is directly involved in it. As you say, if it is a programmed phenomena and depends mainly on structures in the RNA, why is there even a GO term for it? Then, I don't know anything about frameshifting, may be there is somebody that knows more about it?

**Comment by ValWood** [comment]
That's a good question. There are only 6 annotations. Two are to eIF5, and the others look suspect.

My knowledge is based on annotating this single paper many years ago
https://www.pombase.org/reference/PMID:9769097

I guess that the RNA structures could  correctly be annotated with this activity though?

@srengel  what do you think about the annotations?
Maybe they are OK,  but any GP required for normal translation will be required for translating a  "programmed frameshift" . There is something slightly odd about this as a process, but I can't put my finger on the problem.....

**Comment by srengel** [comment]
Hi @ValWood sorry we let this lag..curators discussed today and it seems that gene products can regulate translational frameshifting.  but none of us is an expert.  are there user experts that we can ask?

**Comment by ValWood** [comment]
I'm not sue but I think @asangrador  was correct for his particular exp/annotation in that

ooking at the paper it seems to me that they were trying to prove that IF5A is involved in elongation (which it is) by using mutants that impaired programmed ribosomal frameshifting, but that does not mean that eIF5A is directly involved in it. 

For programmed ribosomal frame-shifting  I think it is regulated by polyamine levels directly.

there is regulation of polyamine synthesis downstream of antizyme production
https://en.wikipedia.org/wiki/AZIN1

Ornithine decarboxylase (ODC) catalyzes the conversion of ornithine to putrescine in the first and apparently rate-limiting step in polyamine biosynthesis. Ornithine decarboxylase antizymes play a role in the regulation of polyamine synthesis by binding to and inhibiting ornithine decarboxylase. The protein encoded by this gene is highly similar to ODC. It binds to ODC antizyme and stabilizes ODC, thus inhibiting antizyme-mediated ODC degradation. Two alternatively spliced transcript variants have been found for this gene.[7]

antizyme is the single gene produced by the  programmed ribosomal frameshift in budding yeast and fission yeast I think?

This is regulated by polyamines binding directly to the riboswitch.

**Comment by dsiegele** [comment]
I found two examples in viruses where mRNA binding-proteins rather than mRNA structure are needed for programmed ribosomal frameshifting to occur.

Transactivation of programmed ribosomal frameshifting by a viral protein
Yanhua Li,a,b,1 Emmely E. Treffers,c,d Sawsan Napthine,e Ali Tas,c Longchao Zhu,a,b,1 Zhi Sun,a Susanne Bell,e Brian L. Mark,f Peter A. van Veelen,d Martijn J. van Hemert,c Andrew E. Firth,e Ian Brierley,e,2 Eric J. Snijder,c,2 and Ying Fanga,b,1,2
Proc Natl Acad Sci U S A. 2014 May 27; 111(21): E2172–E2181.
PMCID: PMC4040542

A novel role for poly(C) binding proteins in programmed ribosomal frameshifting
Sawsan Napthine,1 Emmely E. Treffers,2 Susanne Bell,1 Ian Goodfellow,1 Ying Fang,3 Andrew E. Firth,1,* Eric J. Snijder,2,* and Ian Brierley1,*
Nucleic Acids Res. 2016 Jul 8; 44(12): 5491–5503.
PMCID: PMC4937337

**Comment by ValWood** [comment]
So the term is OK, just the mapping problem.
Val

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by typhainepl** [comment]
I've updated the InterPro entry and removed the GO term.
