### ISSUE TITLE
Headers on gpad/gpi 2.0 files

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2274]
Final proposal at the bottom of the ticket
----

In preparation for releasing the GPAD/GPI 2.0 specs for comment, we need to agree on what and how metadata will be included in the headers of the files.

For tags, we may want to use terms from the Dublin Core Metadata Initiative wherever possible:
http://dublincore.org/documents/dcmi-terms/

Here is a proposal to start:

Required metadata:
!gpa-version: 2.0
!go_version: PURL
!license: text? (URL CC or CC0)
!creator_url: generic URLs from dbxefs.yaml
!creator_release_version: text 
!created: YYYY-MM-DD

Optional metadata:
!creator_email: help @ project.org
!creator_funding: text

!! free text about the file format, the resource, annotation practice, etc.

**Comment by kltm** [comment]
@vanaukenk For composite GPADs, which we will be creating from both upstream and pipeline sources, how would a GO version work as a required field when multiple versions of the GO may have been used?

**Comment by kltm** [comment]
@vanaukenk @cmungall 
I had another thought on this recently. Currently, one of the things that we do for the GAFs is create some rather more complicated headers; e.g.:
```text
!gaf-version: 2.1
!
!Generated by GO Central
!
!Date Generated by GOC: 2019-03-10
!
!Header from fb source gaf:
!=================================
!date: 02/13/2019 $
!from: FlyBase
!saved-by: FlyBase GOcur gocur@morgan.harvard.edu
!Data from FlyBase version fb_2019_01
!=================================
!
!PAINT Header copied from paint_fb_valid.gaf
!=================================
!Created on Mon Dec 31 16:32:03 2018.
!PANTHER version: v.13.1.
!GO version: 2018-12-01.
!=================================
!
!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md
!
```
While this can be written, it's not really machine usable (and only marginally human usable). What might be nice is either a frontmatter/yamldown-type header (e.g. https://raw.githubusercontent.com/geneontology/go-site/master/metadata/rules/gorule-0000001.md) or to have something more structure like YAML embedded in the header. This would allow for a lot of flexibility in for structured creations, parsing ,and additional metadata (even recursive), allowing for traceability chains to be essentially embedded. As well, this would allow more standard libraries to make use of the headers.

Naturally, this is a bit of a departure from what we have done to date. However, this is likely the last chance we would have to do something like this--once we have the final format for the GO interchange milestone, I suspect that we'll have a hard time doing much after it's out.

**Comment by vanaukenk** [comment]
From discussion with @kltm and @dougli1sqrd at USC hackathon, we agreed on these fields for each source file, as well as the file produced by GO:

!gpa-version: 2.0 (required)

!go-version: URI (optional, but will be included in GO release files).  This field indicates the GO version used for QC checks, not the GO version(s) used at the time of annotation.

!go-release: Y or N (optional) Y = indicates whether the go-version used for QC checking was from a versioned release; N = indicates that the go-version used for QC checking was not from a versioned release.

!creator-URL: generic source URL from dbxefs.yaml file (optional)

!creator-release-version: text (optional)

!created: YYYY-MM-DD (required)

!creator-email: help@mod.org (optional)

!creator-funding: U41, etc. (optional)

Fields may be repeated in the header for each source file that contributes to the file either submitted to, or released by, GO.

**Comment by pgaudet** [comment]
Example: (to be reviewed/confirmed)

!gpa-version: 2.0
!go-version: http://release.geneontology.org/2019-05-10/ontology/go-basic.owl
!provider-url: http://wormbase.org
!creator-url: http://wormbase.org
!creator-release-version: V22
!created: 2019-06-11
!creator-email: wormbase@wormbase.org
!creator-funding: U41, etc.
!
!creator-url: http://interpro.org
!creator-release-version: version 142
!created: 2019-03-02
!creator-email: help@interpro.org
!creator-funding: U41, etc.
!
!creator-url: http://mgi.org
!creator-release-version: mgi-data-2019-01-02
!created: 2019-01-02
!creator-email: help@interro.org
!creator-funding: U41, etc.
!
!File specification can be found at 
! coll1 col2 col3 ...
foo bar bibble

|
V

!gpa-version: 2.0
!go-version: http://release.geneontology.org/2019-06-09/ontology/go-basic.owl
!provider-url: http://geneontology.org
!creator-url: http://geneontology.org
!creator-release-version: http://release.geneontology.org/2019-06-09/annotations/index.html
!created: 2019-07-07
!creator-email: help@geneontology.org
!creator-funding: U41, etc.
!
!go-version: http://release.geneontology.org/2019-05-10/ontology/go-basic.owl
!creator-url: http://wormbase.org
!creator-release-version: V22
!created: 2019-06-11
!creator-email: wormbase@wormbase.org
!creator-funding: U41, etc.
!
!go-version: http://release.geneontology.org/2018-03-10/ontology/go-basic.owl
!creator-url: http://interpro.org
!creator-release-version: version 142
!created: 2019-03-02
!creator-email: help@interpro.org
!creator-funding: U41, etc.
!
!creator-url: http://mgi.org
!creator-release-version: mgi-data-2019-01-02
!created: 2019-01-02
!creator-email: help@interro.org
!creator-funding: U41, etc.
!
!File specification can be found at http://geneontology.org/docs/gene-product-association-data-gpad-format
! coll1 col2 col3 ...
foo bar bibble

**Comment by kltm** [comment]
Closing: I believe this is covered in the current spec.
