### ISSUE TITLE
annotation of E. coli dUTPase with GO:0002134?

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#2278]
There's an annotation for the E. coli dUTPase (P06968) to "UTP binding" using the 2001 Nord et al. paper by CAFA.  There is no mention of UTP at all in that paper that I can find.  I wonder if the intended annotation was dUTP binding (such a term does not exist, and in any case, dUTP is the substrate of this enzyme).

Thanks for checking/getting it removed.  Cheers,
Ingrid

**Comment by pgaudet** [comment]
@ggeorghiou you curated this; can you please have a look ?

**Comment by ggeorghiou** [comment]
Hi @pgaudet this is indeed of of my annotations and from the time I started doing GO annotation! I deleted the annotation since you are correct, dUTP is a substrate.

**Comment by pgaudet** [comment]
Thanks !
