### ISSUE TITLE
InterPro: please review mappings to 'do not annotate' terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2279]
Hello, 

I have compiled a list of all mappings of InterPro domains to 'do not annotate' terms, see
https://docs.google.com/spreadsheets/d/1Dk9ESmFX32u0gLH-IlSJRb0OJqrOQt26LJpmw1n9ryo/edit#gid=1290029287

@asangrador @happy-lorna 
Can you please have a look and let us know if you can change (or in some cases remove) the mapping? 

I tried to suggest replacements but I wasn't always able to. 

I would like help for 

- InterPro:IPR021906 | SWI/SNF-like complex subunit BAF250/Osa > GO:SWI/SNF superfamily-type complex -> @bmeldal  any suggestions? 
- InterPro:IPR026676 | Synaptonemal complex central element protein 1 > GO:meiotic prophase I
-> @ValWood any suggestions ? 

Thanks, Pascale

**Comment by ValWood** [comment]
pombe famously does not have this complex, but 
GO:0007129    synapsis  (which occurs *during* prophase I)
@asangrador  we have "phase terms" in the BP  for historical reasons. We only use them in annotation extensions to say when something occurs.
I can't find any docs related to this though.  There is a comment with a bit of explanation on the terms.

v

**Comment by asangrador** [comment]
Hi,
I have removed all the terms in the list (not for direct manual annotation) except for one:
InterPro:IPR021906 | SWI/SNF-like complex subunit BAF250/Osa > GO:SWI/SNF superfamily-type complex | GO_0070603.
The problem with this entry is that corresponds in part to SWI/SNF complex/GO:0016514  and in part to the brahma complex/GO:0035060 (Drosophila), so the most logical would be to use the common ancestor of both.
Thanks for providing us with alternative terms,

Amaia

**Comment by pgaudet** [comment]
Thanks @asangrador 
If the subunit belongs to both complexes it would be correct to annotate to both children, wouldn't it ? 

@bmeldal

**Comment by bmeldal** [comment]
I'm not familiar with InterPro mapping and therefore don't understand this ticket (which way to we remove the do-not-annotate?). 

However, BAF250 (A and B version) is a core SWI/SNF subunit that is found in almost all types of SWI/SNF complexes.

**Comment by pgaudet** [comment]
Thanks @bmeldal 
my point was it would then be OK to have the InterPro mapping for this family to both complexes, since that protein is a member of both.

**Comment by bmeldal** [comment]
Yes.

**Comment by asangrador** [comment]
Ok. I will add both SWI/SNF complex/GO:0016514 and brahma complex/GO:0035060, and remove SWI/SNF superfamily-type complex/GO:0070603 . Nevertheless,  most papers only refer to the brahma complex in the case of Drosophila, but not in the case of mammals. May be the terminology is a bit confusing.

**Comment by pgaudet** [comment]
Thta's possible. I dont think these annotations make an incorrect statement, though.

**Comment by bmeldal** [comment]
>Nevertheless, most papers only refer to the brahma complex in the case of Drosophila, but not in the case of mammals. May be the terminology is a bit confusing.

@asangrador yes, "brahma" one was first discovered in drosophila and then they realised it was more widely present...! The other one use to the 'the yeast one"... Happens all the time ;-)
(And now we know there are lots and lots more SWI/SNF type complexes!)

**Comment by pgaudet** [comment]
Hi @asangrador Just following up: I can still see 'intracellular' mapped in http://www.ebi.ac.uk/interpro/entry/IPR027500
When can we expect the changed to be visible in InterPro ? 

Thanks, Pascale

**Comment by happy-lorna** [comment]
Hi @pgaudet 
Amaia has recently left InterPro (just on Friday actually) so I am replying on her behalf.
The changes will be visible in the next release, which should be public this week. We had a major network outage at the EBI earlier in the month which had a severe knock-on effect to our production schedule, hence our release is a little late. However as I say, it should be out this week.
Lorna.
