### ISSUE TITLE
GO:0008022  protein C-terminus binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#228]
Dear all,
i have problems to understand the definition of this GO
term GO: 0008022  protein C-terminus binding

Def:Interacting selectively with a protein C-terminus,
the end of any peptide chain at which the 1-carboxy
function of a constituent amino acid is not attached in
peptide linkage to another amino-acid residue.

I am annotating P19491 and P19492 (uniprot entries) ans
they are glutamate receptor that bind several protein
(ABP, PICK1 and GRIP).

If i read something like this:
ABP binds to the C termini of  the GLUR2 and GLUR3 
AMPA receptor subunits via PDZ domain (Srivastava et
al. 1998) may I use GO:0008022 for the annotation.
I am not sure because I am not able to understand the
definition.
Thanks
Erika

Reported by: arike

Original Ticket: "geneontology/annotation-issues/228":https://sourceforge.net/p/geneontology/annotation-issues/228

**Comment by linuxjackto1** [comment]
thanks www.movied.org
