### ISSUE TITLE
Location of Transmembrane Protein 9 in Human mis-assigned

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2281]
_From @keslingmj on March 1, 2019 20:33_

Location of Transmembrane Protein 9 in Human mis-assigned
There are 2 closely related proteins: TMEM9B (Q9NQ34) and TMEM9 (Q9P0T7) in Humans.  A research paper "The lysosomal transmembrane protein 9B regulates the activity of inflammatory signaling pathways". PMID: 18541524. looked at TMEM9B but not TMEM9.  They showed that it was localized in the lysosome and late endosome.  GO annotation ascribed these locations to TMEM9 rather than TMEM9B, though they used the correct PMID.  They got the BP annotation correct, though.

_Copied from original issue: geneontology/go-ontology#16979_

**Comment by pgaudet** [comment]
@keslingmj These types of requests (dealing with annotations rather than GO terms) need to be opened in the Annotation Tracker - https://github.com/geneontology/go-annotation/issues

I will move your ticket there. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@keslingmj I dont see either  TMEM9B (Q9NQ34) nor TMEM9 (Q9P0T7) annotated with the paper PMID: 18541524. What is the problem exactly ?

Thanks, Pascale

**Comment by keslingmj** [comment]
Hi Pascale.  The paper deals with TMEM9B, which should be annotated as " lysosome" and "early endosomes" for cellular location.  TMEM9, on the other hand, should not be annotated with these locations.
Thanks,
Michael

**Comment by ValWood** [comment]
@Antonialock 
PMID:18541524 has not yet been used for GO annotation.
It could be used  to provide EXP annotations for the lysosome membrane and endosome annotations which are currently IEA only.

**Comment by Antonialock** [comment]
TMEM9 is annotated to lysosome membrane and endosome membrane from
PMID:12359240
Characterization of the novel human transmembrane protein 9 (TMEM9) that localizes to lysosomes and late endosomes.

TMEM9B is annotated correctly in uniprot from PMID:18541524 - it already had KW mappings from the paper...I added the two components manually for good measure

**Comment by Antonialock** [comment]
think this can close? reopen if any objections.
