### ISSUE TITLE
Human MISP involved in mitotic spindle positioning 

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#2283]
HUMAN_Q8IVT2 ,also known as MISP, Mitotic Interactor and substrate of PLK1, is involved in "mitotic spindle positioning" PMID: 23574715.
Also it's involved in "proper spindle orientation" and "mitotic progression" PMID: 23509069
This information is captured on the UniProt page https://www.uniprot.org/uniprot/Q8IVT2
but it lacking from GO annotations: https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q8IVT2
Thanks, Michael

**Comment by pgaudet** [comment]
@sylvainpoux Can someone from SP look into this ?

**Comment by sylvainpoux** [comment]
Sure, I created a ticket in our user request queue

**Comment by pgaudet** [comment]
Thanks @sylvainpoux

**Comment by ValWood** [comment]
Note that "mitotic progression" is a phenotype not a GO process,  (almost 1/3 of pombe proteins could be annotated to such a term).

This gene  affecting the metaphase/anaphase transition"  when depleted. This means that lack of this protein  results in "mitotic metaphase /anaphase progression (via spindle checkpoint activation) ". It isn't involved in "normal regulation" of the transition, it's depletion is causing a problem that is detected by the checkpoint. 

Unfortunately, there is no good "cell level phenotype" ontology for human, but there will be soon, via Monarch, at this point this can be captured (as "increased activation of the mitotic spindle checkpoint"), but until then not unfortuntely.

The GO terms will  likely be around the roles in  "microtubule attachments" involved in "spindle orientation"

It might be worth passing this to the curator as it's not very obvious if you are just looking  for phrases mapping to GO terms.

I'm going to find the yeast ortholog of this, there must be one!

**Comment by ValWood** [comment]
There is a 2018 paper from the same lab, might be a better starting point for curation
https://www.ncbi.nlm.nih.gov/pubmed/29679050
