### ISSUE TITLE
Annotations  from SynGO in Noctua not following GO rule gorule-0000018

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#2284]
MGI noticed this in our qc checks. We are loading mouse annotations made by SynGO in Noctua. 

http://snapshot.geneontology.org/reports/mgi-report.html#gorule-0000018 (IPI annotations require a With/From entry)

There are 175 annotations using IPI with no entry in the With/Inferred from field (column 10 Gpad, column 15 gaf.). The majority are CC annotations, but there are others also.
Looking at other gafs reports in snapshot do not show this; either not picking up SynGO annotations from Noctua or, since SynGO annotations made with p2go do not have this problem as the interface will not allow.
None of the 175 annotations to mouse genes  appear in Amigo since this error is fatal (annotation skipped).

Assigning to PT as directed.

**Comment by pgaudet** [comment]
Email Frank

**Comment by pgaudet** [comment]
Fixed by Frank
