### ISSUE TITLE
Review annotations to 'GO:0042954 lipoprotein transporter activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2285]
Hello, 

I have proposed to obsolete 'GO:0042954 	lipoprotein transporter activity'  (see ticket: https://github.com/geneontology/go-ontology/issues/17004

These are the manual annotations that need review: https://docs.google.com/spreadsheets/d/13YY6cRqfcXngf3y5Aetw3zlt20qDMfpilnWX6jf6sH4/edit#gid=0

Group | Number of   annotations | contact person
-- | --   | -- 
JCVI | 4 | @mgiglio99
TIGR | 5 | @mgiglio99
EcoCyc | 1 | @keseler 
Reactome | 1 | @deustp01  (done)
UniProt | 3 |  @lbreuza (done)

Please let me know if this is OK. 

Thanks, Pascale

**Comment by amandamackie** [comment]
Hello Pascale,
@keseler from EcoCyc passed this issue to me for comment.

The LolCDE complex **releases** lipoproteins from the periplasmic side of the inner membrane to the LolA chaperone, it does not transport them from one side of a membrane to the other which is what the current def of transmembrane transporter activity specifies ('Enables the transfer of a substance, usually a specific substance or a group of related substances, from one side of a membrane to the other'). 

PMID 10783239 is the initial characterization of LolCDE and they state 'The LolCDE complex differs mechanistically from all other ABC transporters as it is not involved in the transmembrane transport of substrates'. This is an important distinction and for this reason I chose to annotate lolC, lolD and lolE in EcoCyc to the more general term 'lipoprotein transporter activity ('the directed movement of any conjugated, water soluble protein...into, out of or within a cell'). 

Amanda

**Comment by pgaudet** [comment]
Thanks for the comment Amanda! 

Tu put this query in context: I came across this while doing the refactoring of the Molecular Function branch, and for transporters, we are trying to group functions based on transport mechanism. 

Right now we have 'transmembrane transporter activity' and 'cargo receptor activity' as types of mechanisms by which substances can be transported. The transport of proteins is more tricky because it can occur by several different ways (and as far as I can tell, transmembrane transport is not very common). The way you used 'lipoprotein transporter activity' is essentially a BP annotation - you know the end result but you don't describe how. 

I found a more recent review (PMID:21670534) also with a nice diagram (pasted below), where the **function** of  the LolCDE complex seems to be in selecting which protein to 'hand' to LolA

![image](https://user-images.githubusercontent.com/4782928/54268266-21b03200-457b-11e9-9682-9b736ffd81af.png)

It would be nice to find a way to describe this function - any suggestions ? 

Thanks, Pascale

**Comment by amandamackie** [comment]
What about 'lipoprotein releasing activity': the process by which lipoproteins are released from the inner membrane of diderm bacteria and transferred to a chaperone protein for subsequent transport across the periplasmic space.

In EcoCyc we call LolCDE the 'lipoprotein release complex'

Amanda

**Comment by pgaudet** [comment]
Sounds good. Would it be OK to be under 'molecular carrier activity' ? It doesn't seem to fit the definition of transporter activity. 
The BP transport (protein transport) would capture the role in that process. 

Would that work ? 

Thanks, Pascale

**Comment by amandamackie** [comment]
That works for me

Amanda
