### ISSUE TITLE
Review annotations to protein transport by the Tat complex

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2286]
There are 2 annotations by PseudoCAP that seem to capture target of the transport process rather than being involved in the process itself. 

see https://docs.google.com/spreadsheets/d/1SrlrBtxERj69-2DxE8AATSo9mOtlOw1pRxE1umNz4NA/edit#gid=0

Thanks, Pascale

**Comment by glwinsor** [comment]
Thanks Pascale. I agree they should be at least removed. Are you aware of a term that captures their role as a target of the transport process?

**Comment by pgaudet** [comment]
Thanks @glwinsor 
We never annotate targets in GO, only the active protein. For example the target of a protein kinase is never annotated to phosphorylation, even though it is phosphorylated. 

In this case what you can capture about the target protein is its **final** location- we don't capture either the observation that a protein localises to a location during its maturation/transport to active location. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@glwinsor Has this been addressed ?
