### ISSUE TITLE
Review annotations to GO:0060090 molecular adaptor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2288]
Hello, 

While working on https://github.com/geneontology/go-ontology/issues/15509
I came across some annotations that should be reviewed: 
(incorrectly using the term OR could have a more specific annotation - see my suggestions in the spreadsheet): 
https://docs.google.com/spreadsheets/d/1_XtkQ-1ysDcvv5uFVnLrv1gh3VJEurVEPiv89zAVBtA/edit#gid=0

Group | Number of annotations 
-- | --
BHF-UCL | 1
FlyBase | 7
PomBase | 3
UniProt | 6

Thanks, Pascale

**Comment by ValWood** [comment]
based on the annotation cdc48 could move down to protein binding bridging, but I'm surprised we have cdc48 as an adaptor

For isu1, iron chaperone activity  descendant of molecular carrier, seems correct
and @Antonialock  mentions carrier for here. So need to check why she went with adaptor finally.

**Comment by pgaudet** [comment]
The carrier activity is rather a delivery: 
"Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location."

**Comment by milarolo** [comment]
With respect to Annexin A5 (P81287) in PMID:21501828 with GO:0060090 | molecular adaptor activity:
In this paper they show that Annexin A5 binds PtdSer (viral envelope protein), and they use it  to show that Gas6 also binds to PtdSer. (fig. 5C and 6)
They want to show that Gas6 is a protein bridge for viral infection but they don't show that for Annexin A5.
I would replace molecular adaptor activity for protein binding

**Comment by milarolo** [comment]
I agree about the Growth arrest-specific protein 6 (Q14393). I've changed GO:0060090 (molecular adaptor activity) for GO:0030674 (protein binding, bridging).

**Comment by ValWood** [comment]
Hi @Antonialock can you check why you used adaptor here?

**Comment by Antonialock** [comment]
> * [ ]  Hi @Antonialock can you check why you used adaptor here?

not sure, I just picked the wrong one. 

I moved isu1 to 

GO:0140132 | iron-sulfur cluster carrier activity

**Comment by ValWood** [comment]
ok pombase done

**Comment by pgaudet** [comment]
@ValWood @Antonialock 
Can you please fill the google spreadsheet ? 
https://docs.google.com/spreadsheets/d/1_XtkQ-1ysDcvv5uFVnLrv1gh3VJEurVEPiv89zAVBtA/edit#gid=0

Thanks, Pascale

**Comment by ValWood** [comment]
oops done

**Comment by pgaudet** [comment]
There are some annotations left by 
- SWIS @sylvainpoux 
- SWIE @milarolo 
- TAIR @tberardini 

Please have a look and comment on the spreadsheet.  Once done, please remove your name from the assignees. 
Thanks, Pascale

**Comment by milarolo** [comment]
> With respect to Annexin A5 (P81287) in PMID:21501828 with GO:0060090 | molecular adaptor activity:
> In this paper they show that Annexin A5 binds PtdSer (viral envelope protein), and they use it to show that Gas6 also binds to PtdSer. (fig. 5C and 6)
> They want to show that Gas6 is a protein bridge for viral infection but they don't show that for Annexin A5.
> I would replace molecular adaptor activity for protein binding

**Comment by milarolo** [comment]
SWIE  all done
I changed "molecular adaptor activity" in Annexin A5 (P81287) in PMID:21501828  to  "phosphatidylserine binding" (GO:0001786)

**Comment by pgaudet** [comment]
There are 3 UniProt annotations left: @sylvainpoux 

Q9UBV8 
O75340 
Q8W234

**Comment by tberardini** [comment]
@pgaudet I checked the annotation and it's from UniProt.  I can't change it but I agree with the change.  We have a TAIR-made annotation to transcription coregulator activity for the same gene product from another paper. Looks like you unassigned me already.

**Comment by pgaudet** [comment]
@tberardini Apologies, sometimes my eyes cross and I read the wrong column ! 

Cheers, Pascale

**Comment by pgaudet** [comment]
Fixed remaining annotations.
