### ISSUE TITLE
Need checks and constraints for bract development.  

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-annotation#2289]
I found a improper zebrafish annotation to bract development GO:0010432 (that I made by accident)  which is showing up on the current data release of amigo.  It looks like there should be error reports  to let us know if there are data issues but I don't think they are running.  Annotation has been in place for at least a couple of years.  
Usage of term should be restricted to phyllome.  If this ticket needs to be moved to a different tracker please do.  

Annotation has been updated so the bad data should go away but we still need a report if we violate the constraint.

![image](https://user-images.githubusercontent.com/2602957/54164250-2eb51000-4419-11e9-8661-37c9b743d948.png)

**Comment by pgaudet** [comment]
@cerivs We put these requests in the ontology tracker. I'll move this one. 

Thanks, Pascale

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#17025
