### ISSUE TITLE
IPR000812 -> Zinc binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#229]
This does not appear to be the zinc binding domain of
TFIIB subunit

(or at least the Pfam domain which picks up the mapping
"Brf1-like TBP-binding domain" isn't

cheers

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/229":https://sourceforge.net/p/geneontology/annotation-issues/229

**Comment by linuxjackto1** [comment]
thanks www.movied.org
