### ISSUE TITLE
Review annotations to GO:0008565 protein transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2293]
https://docs.google.com/spreadsheets/d/1wOfGUMUcckFPeD1Gr_HG5s6b0zXmOH7M5RBgotRpjlc/edit#gid=0

**Comment by RLovering** [comment]
Hi Pascale

The first 2 I think are correct based on the statement: LIMP-2 is the trafficking receptor for beta-glucocerebrosidase.

The third one I could change but I would appreciate a second opinion. Another paper PMID: 26903377 has the statement: These data for the first time revealed a novel role that MOG1, a nucleocytoplasmic transport protein, plays in cardiac physiology and development. But I think if Mog1 in yeast is not considered to be a transporter then I will revise: Note the yeast paper PMID:11509570, seems to support the transporter role or maybe this is not sufficient evidence to do more than just confirm MOG1 involved in the process of transport only?

Thanks

Ruth

**Comment by pgaudet** [comment]
LIMP-2 could be annotated to cargo receptor activity.

**Comment by RLovering** [comment]
Thanks Pascale for your help with these, 3 UCL annotations updated

**Comment by pgaudet** [comment]
Thanks !

**Comment by pgaudet** [comment]
The proposal has been made to obsolete GO:0008565 protein transporter activity - see Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/17071. The reason for obsoletion is that the term has been inconsistently used: it’s been used mostly as the ‘protein transport’ process, but annotations represent various mechanisms to transport proteins. 

There are 116 EXP annotations as shown below. **The annotation review spreadsheet is here: 
https://docs.google.com/spreadsheets/d/1wOfGUMUcckFPeD1Gr_HG5s6b0zXmOH7M5RBgotRpjlc/edit#gid=0**

Contributor   (Assigned by) | Number of annotations
-- | --
CACAO | 1 @sandyl27 
dictyBase | 1 @pfey03 
EcoCyc | 1 @keseler  
EcoliWiki | 3
FlyBase | 9  @hattrill 
GeneDB | 2 @ggeorghiou 
MGI | 13 @hdrabkin 
SGD | 47 @srengel 
TAIR | 6 @tberardini 
UniProt | 30 @milarolo 

There are also 8 InterPro families with mappings @happy-lorna  (also in the annotation review spreadsheet https://docs.google.com/spreadsheets/d/1wOfGUMUcckFPeD1Gr_HG5s6b0zXmOH7M5RBgotRpjlc/edit#gid=0) 

I need to create 2 new terms to rehouse some annotations - I will do that now and add comments to the spreadsheet. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I have added a second spreadsheet with the non-IEAs annotations 


AgBase | 1
-- | --
ARUK-UCL | 1
ComplexPortal | 3
dictyBase | 10
FlyBase | 32
GeneDB | 14
JCVI | 12
MGI | 18
PINC | 3
PomBase | 6
RGD | 1
SGD | 1
TAIR | 4
TIGR | 12
UniProt | 66

**Comment by RLovering** [comment]
Hi 
Please could you advise on O95817, BAG3, annotated with protein transporter activity based on PMID: 21681022 see the abstract statement: In this novel pathway, BAG3 mediates the targeting and transport of degradation-prone substrates into aggresomes via the microtubule-motor dynein. 
What molecular function should I use if not protein transporter activity ?

Thanks
Ruth

**Comment by pgaudet** [comment]
PMID 21681022 is a review; I suppose you want to annotate the papers that this paper cites ? 
For example PMID:21252941 ? The conclusion states "The main factor of this pathway is the stress-induced co-chaperone BAG3 that couples the release of Hsp70-bound substrates to the dynein motor complex, thereby mediating aggresome-targeting and autophagic degradation of chaperoned substrates. " 

This is what I intended to cover with the proposed 'protein transport chaperone' term; would that work ? 

Thanks, Pascale

**Comment by RLovering** [comment]
yes that would be great, you are right I should annotate the paper rather than the review. So I can't update this annotation until the new term is available, is that right?

Thanks

Ruth

**Comment by pfey03** [comment]
I took care of all directly annotated to GO:0008565. What about children?
I have still two ISS to GO:0008320 protein transmembrane transporter activity

ISS once everyone have cleaned them will anyway be flagged and then deleted

**Comment by pgaudet** [comment]
> I can't update this annotation until the new term is available, is that right?

Right

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Just to let you know that we have deleted all the "GO:0008565" in InterPro. 
Hsin-Yu

**Comment by milarolo** [comment]
All SWIE ones are changed/removed now
Mila

**Comment by pgaudet** [comment]
@pfey03 GO:0008320 protein transmembrane transporter activity
will remain. 

I just want to figure out mechanisms for the MF branch: either transmembrane transport or endocytic transport. 
If the experiment doesn't allow to tell, then you only annotate to the BP 'protein transport'.

**Comment by LiNiMGI** [comment]
all MGI annotations updated. Li

**Comment by milarolo** [comment]
All SWIE annotations are changed or removed

**Comment by tberardini** [comment]
TAIR is done.

**Comment by pgaudet** [comment]
@milarolo Can you have a look at Q86H98 (DDB_G0275573)? It's a Swiss-EBI annotation.

Thanks, Pascale

**Comment by pgaudet** [comment]
@Achchuthan Can you please have a look at GeneDB:PF3D7_1105600 (see comment in the spreadsheet for details: https://docs.google.com/spreadsheets/d/1wOfGUMUcckFPeD1Gr_HG5s6b0zXmOH7M5RBgotRpjlc/edit#gid=0)

**Comment by Achchuthan** [comment]
Hi @pgaudet,

Thanks for this. I have forwarded this to Uli Boehme, plasmodium curator at GeneDB.

Best wishes,
Achchuthan

**Comment by uliboehme** [comment]
Hi @pgaudet,
Thanks for this. I've now deleted "GO:0008565" in P. falciparum (PF3D7_1105600) on GeneDB. 
Best, 
Uli

**Comment by pgaudet** [comment]
Thanks @uliboehme @Achchuthan

**Comment by pgaudet** [comment]
@milarolo In fact there are 3-4 SWIE annotations that were missed - I highlighted them in cyan in the spreadsheet; can you please fix ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@sandyl27 Can you fix the 1 CACAO and 3 EcoWiki annotations? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@srengel I created the terms required for re-annotation - your annotations can be reviewed as soon as the term is available in P2GO. 

@hattrill FlyBase genes can also be reanntoated. 

Thanks ! Pascale

**Comment by milarolo** [comment]
> @milarolo Can you have a look at Q86H98 (DDB_G0275573)? It's a Swiss-EBI annotation.
> 
> Thanks, Pascale

Changed to "transporter activity"

**Comment by pgaudet** [comment]
>>     @milarolo Can you have a look at Q86H98 (DDB_G0275573)? It's a Swiss-EBI annotation.

> Changed to "transporter activity"

Oh ! I was planning to make this a 'do not annotate'. Vps32 seems to be involved in vesicular transport, but I cannot see any evidence for its function; what is the data you are using to make this annotation? 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi @pgaudet - just got back from a meeting, will prob take me a few days before I get round to this.

**Comment by milarolo** [comment]
> @milarolo In fact there are 3-4 SWIE annotations that were missed - I highlighted them in cyan in the spreadsheet; can you please fix ?
> 
> Thanks, Pascale

All done
Mila

**Comment by pgaudet** [comment]
Thanks !!!

**Comment by milarolo** [comment]
> > > ```
> > > @milarolo Can you have a look at Q86H98 (DDB_G0275573)? It's a Swiss-EBI annotation.
> > > ```
> 
> > Changed to "transporter activity"
> 
> Oh ! I was planning to make this a 'do not annotate'. Vps32 seems to be involved in vesicular transport, but I cannot see any evidence for its function; what is the data you are using to make this annotation?
> 
> Thanks, Pascale

Yes, you are right, they don't present any evidence. I've just removed it
Mila

**Comment by sandyl27** [comment]
I changed the CACAO one but I dont have access to the Ecoliwiki ones. 

@jimhu-tamu

**Comment by srengel** [comment]
SGD done except for the ones that are supposed to be changed to these new terms:

Change to GONEW: GO:0140318 protein carrier activity 
Change to GO:GO:0140312 cargo adaptor activity (NEW)

because these terms don't appear to be available in P2GO yet.

**Comment by gthayman** [comment]
RGD done.

**Comment by hattrill** [comment]
FlyBase done.

**Comment by srengel** [comment]
SGD done.

**Comment by ValWood** [comment]
PomBase ones all IBA (Paint)

**Comment by bmeldal** [comment]
16 complexes changed as well.

**Comment by RLovering** [comment]
Hi

is there going to be a new term protein transport chaperone?

Thanks

Ruth

**Comment by dsiegele** [comment]
changed annotations on EcoliWiki from GO:0008565 to GO:0008320 'protein transmembrane transporter activity '

**Comment by pgaudet** [comment]
Term has been obsoleted, any remaining annotations will be flagged by QC checks. 

Pascale
