### ISSUE TITLE
Review annotation to SGD:S000004573 SRP-dependent cotranslational protein targeting to membrane, translocation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2294]
Hello, 

Reviewing the Panther family (https://github.com/geneontology/go-annotation/issues/2162)
I think SGD:S000004573 (SRP65) is involved in signal sequence recognition, and the annotation to 'SRP-dependent cotranslational protein targeting to membrane, translocation' is probably just a downstream effect from knocking out the first step of the reaction. 

Thanks, Pascale

**Comment by suzialeksander** [comment]
Thanks @pgaudet, I've removed that one as we had the right annotation already.

**Comment by pgaudet** [comment]
Thanks !

**Comment by ValWood** [comment]
edited to SEC65
