### ISSUE TITLE
Review annotations to GO:0052033 and GO:0052169 pathogen-associated molecular pattern dependent modulation/induction by symbiont of host innate immune response

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2296]
Hello, 

The terms 
GO:0052033 pathogen-associated molecular pattern dependent induction by symbiont of host innate immune response and 
GO:0052169 pathogen-associated molecular pattern dependent modulation by symbiont of host innate immune response

should have been annotated to symbiont genes/gene products, but they are annotated to host gene products .

Annotations should be moved to 'GO:0002221 pattern recognition receptor signaling pathway' or GO:0002752 cell surface pattern recognition receptor signaling pathway

https://docs.google.com/spreadsheets/d/1EwF_QPEXzfMxkxUuRCipwzmpaGeTb2VfcDacoKkOPGA/edit#gid=0

@tberardini @sabrinatoro @milarolo 

See also https://github.com/geneontology/go-ontology/issues/17040 for more details. 

Thanks, Pascale

**Comment by sabrinatoro** [comment]
ZFIN annotations have been updated.

**Comment by lreiser** [comment]
@tberardini  the TAIR annotations have been updated.

**Comment by tberardini** [comment]
Thanks very much, @lreiser.

**Comment by milarolo** [comment]
The UniProt annotations were done by SWIP so I can't change them. (A9T142, A9S9Q8/GO:0052169)
