### ISSUE TITLE
Review annotation to protoporphyrinogen IX biosynthetic process from glutamate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2297]
E. coli hemF is annotated to 'protoporphyrinogen IX biosynthetic process from glutamate' 
from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC205104/pdf/jbacter00021-0135.pdf

but I dont see a mention of glutamate. @keseler can you check that this is correct? 

(see also https://github.com/geneontology/go-ontology/issues/17053). 

Thanks, Pascale

**Comment by suzialeksander** [comment]
I see no manual annotations only treegrafter, uniprot, paint.  If this is incorrect it's not EcoCyc.

**Comment by pgaudet** [comment]
No action needed, thanks!
