### ISSUE TITLE
Review annotations to AU-rich element binding (GO:0017091)

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2299]
The MF terms

GO:0017091 AU-rich element binding

and 

GO:0035925 mRNA 3'-UTR AU-rich region binding

currently seem to overlap in meaning, as exact synonyms for 'AU-rich element binding' include 'ARE binding' and 'Adenylate/uridylate-rich element binding' which refer to AU-rich motifs in the 3'-UTR of messages that control mRNA stability.

I checked the existing annotations to 'AU-rich element binding' and with a very few exceptions, annotations can be moved down to the more specific term, 'mRNA 3'-UTR AU-rich region binding'.

Could people please check and move their annotations down where appropriate, and for those annotations that don't fit 'mRNA 3'-UTR AU-rich region binding', check to see if the other suggested term is okay, a new term is warranted, or if we need to keep the parent term but update the term name.

https://docs.google.com/spreadsheets/d/1E77ms-ae2cEb5ajBeDZNtX-JOJT5z5_s_aRsY8zSUX4/edit#gid=0

See:
https://github.com/geneontology/go-ontology/issues/16842

@tberardini (2)
~@ValWood (1 - maybe already moved)~ done now
@hdrabkin (5)
@slaulederkind (1)
@RLovering (1) done
@suzialeksander (2)
@milarolo (2)
@sylvainpoux (22)

Thank you!

**Comment by hdrabkin** [comment]
According to the spreadsheet, the MGI annotations are coming in through our GOA load from UniProt. I can't fix these.

**Comment by hdrabkin** [comment]
oops wait; I see them earlier in the sheet than what I was looking at. I fix

**Comment by milarolo** [comment]
I've made the changes for the SWIE annotations (Q8IYX4, P26651). For some reason the spreadsheet document didn't allow me to update it with the changes.

**Comment by gthayman** [comment]
RGD annotation moved down.

**Comment by vanaukenk** [comment]
@milarolo - I re-set the permissions for the spreadsheet.  It seemed to be okay last week, so I'm not sure why/how it changed.
Let me know if you have any trouble again.  Thx.

**Comment by milarolo** [comment]
It works now. I updated the changes.
Mila

**Comment by vanaukenk** [comment]
@sylvainpoux - there are 20 annotations to review here from Swiss-Prot curators.  
@milarolo reviewed the annotations from EBI.
Thx.

**Comment by pgaudet** [comment]
Swiss-Prot now done

**Comment by tberardini** [comment]
TAIR done

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
All fixed.
