### ISSUE TITLE
    	  IPR000048 IQ calmodulin-binding region

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#230]
Hi Sandra, 
Is 'IPR000048 IQ calmodulin-binding region' an
indicatio of 'calmodulin binding'? (GO: 5516)?

Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/230":https://sourceforge.net/p/geneontology/annotation-issues/230

**Comment by linuxjackto1** [comment]
thanks www.movied.org
