### ISSUE TITLE
Review annotations to 'positive regulation of drug transmembrane export'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2303]
Hello, 

RGD has one annotation to 'positive regulation of drug transmembrane export'  (RGD:3112); since this is a transporter, it should be annotated to 'export across plasma membrane' 

Please respond here: https://docs.google.com/spreadsheets/d/1wi7f_qyjh8Z6hvcMbpDZUCZET-zh2wGM1aOsY2ytfSs/edit#gid=0

Thanks, Pascale

**Comment by gthayman** [comment]
Hi Pascale,
Changed to suggested term and noted on Google spreadsheet.
Tom

**Comment by pgaudet** [comment]
thanks!
