### ISSUE TITLE
Review annotations to 'GO:0042891 antibiotic transport'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2304]
Antibiotic transport will be obsoleted, see https://github.com/geneontology/go-ontology/issues/17082

https://docs.google.com/spreadsheets/d/1Iex3RzncnY10hexEpz4kNSREBJTbZI3L7MNJ_wqlPS0/edit#gid=0

Please move your annotations: 

Group | Number of annotations
-- | --
EcoCyc | 9
MTBBASE | 3
PseudoCAP | 1
RGD | 2

Thanks, Pascale

**Comment by gthayman** [comment]
Both RGD annotations moved.

**Comment by pgaudet** [comment]
Term was obsoleted. Remaining annotations will be flagged by QC checks.

**Comment by glwinsor** [comment]
Thanks for bringing this to our attention. Terms have been updated.

**Comment by pgaudet** [comment]
@keseler FYI it doesn't look like EcoCyc have been updated.

**Comment by glwinsor** [comment]
@pgaudet And thanks to you guys for doing this valuable work!

**Comment by keseler** [comment]
@pgaudet the terms have been updated/removed in EcoCyc; I don't know when our GAF was last updated, though.  That's still done via EcoliWiki.
