### ISSUE TITLE
Review annotations to GO:0042895 antibiotic transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2305]
Antibiotic transmembrane transporter activity will be obsoleted, see geneontology/go-ontology#17082

Please move your annotations: https://docs.google.com/spreadsheets/d/1UaATMC_ch16EPYXSnaPI7QOJHUQJgbFyM198tK4nqDY/edit#gid=0

Group | Number of annotations
-- | --
EcoCyc | 9
PseudoCAP | 1
RGD | 2
ZFIN | 2

Thanks, Pascale

**Comment by gthayman** [comment]
The two RGD annotations have been deleted.

**Comment by sabrinatoro** [comment]
ZFIN annotations have been reviewed and updated

**Comment by bmeldal** [comment]
4 complexes updated

**Comment by pgaudet** [comment]
pinging @glwinsor 
@keseler or @amandamackie
@jimhu-tamu

**Comment by pgaudet** [comment]
Term was obsoleted. Any remaining annotations will be flagged by QC checks.
