### ISSUE TITLE
Review annotations to GO:0015238 drug transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2306]
We are planning to ~obsolete~ merge GO:0015238 drug transmembrane transporter activity into     GO:0042910  xenobiotic transmembrane transporter activity, see https://github.com/geneontology/go-ontology/issues/16962

Please move your annotations: 
https://docs.google.com/spreadsheets/d/1gOWADbidJzGgulsD-vxr8DudNq00Xr-pD-Huw0p_42k/edit#gid=0

Group | Number of annotations
-- | --
CGD | 22
EcoCyc | 7
EcoliWiki | 2  	@jimhu-tamu
GeneDB | 9
PseudoCAP | 23
RGD | 5
SGD | 8
TAIR | 1
UniProt | 4
UniProtKB | 1

**Comment by tberardini** [comment]
TAIR done.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by milarolo** [comment]
SWIE done

**Comment by pgaudet** [comment]
Thanks !

**Comment by gthayman** [comment]
RGD done.

**Comment by srengel** [comment]
@marekskrzypek there are 11 CGD annotations to review on this one

**Comment by srengel** [comment]
SGD done.

**Comment by marekskrzypek** [comment]
CGD done

**Comment by pgaudet** [comment]
@Achchuthan Can you please look at the GeneDB annotations? 
@glwinsor Can you please look at the PseudoCAP annotations? 
@slaulederkind RGD ? 

Thanks, Pascale

**Comment by happy-lorna** [comment]
FYI - I have fixed the few of these we had in InterPro.

**Comment by pgaudet** [comment]
Thanks Lorna! Sorry for not mentioning InterPro.

**Comment by gthayman** [comment]
Hi Pascale,
I handled RGD's (noted above) for Stan.
Tom

**Comment by pgaudet** [comment]
Thanks Tom !

**Comment by Achchuthan** [comment]
GeneDB done

**Comment by dsiegele** [comment]
Ecoliwiki done

**Comment by pgaudet** [comment]
Merge done for this term.
