### ISSUE TITLE
InterPro:IPR033508 too specific

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2307]
Hi,

http://www.ebi.ac.uk/interpro/entry/IPR033508

is mapped to the GO BP angiotensin maturation (GO:0002003) which is too specific for some of the proteins matched.

For example, C. elegans VB0395L.1: https://wormbase.org/species/c_elegans/gene/WBGene00044150

gets this annotation, but C. elegans does not have an angiotensin.

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have removed this GO term. 
Hsin-Yu

**Comment by EBI-Hsinyu** [comment]
Hi, 
Just to let you know that Amaia has left our group after 9 years. Please assign tickets to me or Lorna. Thank you!
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks for the information @EBI-Hsinyu ! And all the best to @asangrador
