### ISSUE TITLE
Add GO:0003755 to IPR001179?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2308]
Can we associate "peptidyl-prolyl cis-trans isomerase activity" (GO:0003755) to this InterPro domain?:
FKBP-type peptidyl-prolyl cis-trans isomerase domain (IPR001179)

@hattrill

**Comment by happy-lorna** [comment]
I have added this. change will be visible in next release. thanks!

**Comment by sjm41** [comment]
Thanks
