### ISSUE TITLE
PAINT:PANTHER:PTN000000448 and PTN000000481 yellow proteins

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2309]
The function of the insect yellow proteins is not clear - some may have enzymatic functions, other may be hormone-like. For most it is not clear. PMID:20656794

yellow-f and yellow-f2 have been shown to have dopachrome isomerase activity, but yellow-y, yellow-b and yellow-c have been tested and do not show this activity. We've just added a ’NOT dopachrome isomerase activity (GO:0004167)’ to these 3 genes.

Given the rather uncertain function of this group, it would be better not to propagate annotations between them, as most probably aren't isomerases.

These are the fly genes with IBAs:
FBgn0004034	y	yellow	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0032601	yellow-b	yellow-b	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0041713	yellow-c	yellow-c	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0041712	yellow-d	yellow-d	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0034856	yellow-d2	yellow-d2	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0041711	yellow-e	yellow-e	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0038151	yellow-e2	yellow-e2	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0038150	yellow-e3	yellow-e3	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0041710	yellow-f	yellow-f	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0041710	yellow-f	yellow-f	dopachrome isomerase activity ; GO:0004167 | IBA with PANTHER:PTN000000481
FBgn0038105	yellow-f2	yellow-f2	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0038105	yellow-f2	yellow-f2	dopachrome isomerase activity ; GO:0004167 | IBA with PANTHER:PTN000000481
FBgn0041709	yellow-g	yellow-g	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0035328	yellow-g2	yellow-g2	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0039896	yellow-h	yellow-h	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448
FBgn0036504	yellow-k	yellow-k	isomerase activity ; GO:0016853 | IBA with PANTHER:PTN000000448

**Comment by marcfeuermann** [comment]
Propagation of MF and BP to PTN000000448 and PTN000000481 have been removed.

**Comment by hattrill** [comment]
Thanks @marcfeuermann 
@sjm41 - yellow protein issue should be resolved now.

**Comment by sjm41** [comment]
Great, thanks both.
