### ISSUE TITLE
various INTERPRO domains: 'electron transporter activity'

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#231]
Just making sure that the new mapping is updated to
point from 'electron transporter activity' to 'electron
carrier activity ; GO:0009055' as the former term is
now obsolete.

Thanks,

Tanya

Reported by: tberardini

Original Ticket: "geneontology/annotation-issues/231":https://sourceforge.net/p/geneontology/annotation-issues/231

**Comment by linuxjackto1** [comment]
thanks www.movied.org
