### ISSUE TITLE
Review annotations to GO:0005215 transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2311]
Hello, 

I will make 'GO:0005215 transporter activity' a 'do not annotate' term, see 
https://github.com/geneontology/go-ontology/issues/17097

Annotations can be reviewed here: 
https://docs.google.com/spreadsheets/d/15mSlj-phRM-tzFfz6PapOi1dS_jzHXGsTFXVexotWgI/edit#gid=472725260

Note that there are 2 spreadsheets, one for EXP and one for manual, non-EXP. 

**Experimental**

Contributor   (Assigned by) | Number of EXP annotations
-- | --
BHF-UCL | 2
EcoCyc | 2
EcoliWiki | 3
GeneDB | 3 @uliboehme
GR | 1
MGI | 1
RGD | 4
SGD | 5
TAIR | 3
UniProt | 17
WB | 1

**Non experimental**

Contributor   (Assigned by) | Number of non-EXP annotations
-- | --
AspGD | 14
CGD | 7
dictyBase | 16
EcoCyc | 3
FlyBase | 12
GeneDB | 30
GR | 85
JCVI | 248
MGI | 3
PAMGO_GAT | 3
PAMGO_MGG | 2
PINC | 62
Reactome | 2
RGD | 1
SGD | 12
TAIR | 174
TIGR | 628
UniProt | 42

**Comment by hdrabkin** [comment]
MGI done

**Comment by milarolo** [comment]
All SWIE are done

**Comment by gthayman** [comment]
RGD done.

**Comment by pgaudet** [comment]
@hdrabkin you didn't write anything in th espreadsheet next to MGI:MGI:1860508; is that one done too ?

**Comment by hdrabkin** [comment]
Yes; must have just forgot to mark that cell; it's gone

**Comment by pfey03** [comment]
dictyBase done

**Comment by marekskrzypek** [comment]
CGD done

**Comment by tberardini** [comment]
TAIR done

**Comment by hattrill** [comment]
FlyBase done.

**Comment by suzialeksander** [comment]
SGD done.

**Comment by RLovering** [comment]
UCL done

**Comment by vanaukenk** [comment]
WB done.

**Comment by vanaukenk** [comment]
WB done

**Comment by pgaudet** [comment]
Do not annotate tag added. Any remaining annotations will be flagged by QC checks.
