### ISSUE TITLE
MGI review annotation to GO:0042892 chloramphenicol transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2313]
Hi @hdrabkin 

MGI:1346060 is annotated to GO:0042892  chloramphenicol transport
but I dont see mention of chloramphenicol in the paper; can you please check ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Should be gone by now; was typo

**Comment by pgaudet** [comment]
https://docs.google.com/spreadsheets/d/1SV2hUSl3WwlWYDFdC4cJ2HOj22EnmQwAHuSuP8ItXh0/edit#gid=0

**Comment by hdrabkin** [comment]
can't spell my own git handle!
