### ISSUE TITLE
Review annotations to GO:0034437 - glycoprotein transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2316]
Hello, 

For the MF refactoring, would everyone please review their annotations to 
GO:0034437 - glycoprotein transporter activity
https://docs.google.com/spreadsheets/d/1cu0Nll7dFiBQkts7C2Ug0G7a3RCxKhnsmLCKGw94Nqg/edit#gid=0

2 BHF @RLovering - done
2 UniProt @milarolo

**Comment by milarolo** [comment]
SWIE @milarolo- done
