### ISSUE TITLE
Human PIMREG protein controls cell cycle at Metaphase-to-Anaphase Transition

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#2319]
Human PIMREG protein Q9BSJ6
(https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q9BSJ6) was studied at PMID: PMID:18757745 (https://europepmc.org/abstract/MED/18757745).  This protein is also called RCS1.
Via knockout, they showed that the cell cycle sped up because of Metaphase-to-anaphase acceleration.  The PIMREG knockout also caused accelerated break down on SECURIN and CYCLIN B, proteins known to act that this transition point.
They also showed that "RCS1 is efficiently ubiquitinated by APC/C in vitro and degraded during mitotic exit in a Cdh1-dependent manner in vivo. APC/C recognizes a unique D-box at the N terminus of RCS1, as mutations of this D-box abolished ubiquitination in vitro and stabilized the mutant protein in vivo"
APC = Anaphase Promoting Complex.
PIMREG's expression level also fluctuates through the cell cycle.
Based on these independent lines of evidence (some stronger than others), GO should consider adding this protein to "Mitotic cell cycle regulator" and "Meta-phase to Anaphase transition"
Thanks,
Michael Kesling

**Comment by Antonialock** [comment]
I don't think I can make this annotation. A later (2017) paper states:

The function of Fam64a in fCMs is currently unknown. We found that Fam64a knockdown inhibits and its overexpression promotes fCM proliferation (Fig. [5](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5493652/figure/Fig5/)), whereas expression of a non-degradable Fam64a mutant does not promote proliferation (Fig. [7](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5493652/figure/Fig7/)). These data indicate that Fam64a serves as a cell cycle promoter, but its mechanism of action is not simple. These findings contrast to those reported for HeLa cells, in which none of the expression modifications, such as knockdown, overexpression, or expression of a non-degradable mutant, appear to change the cell proliferation or the cell cycle gene expressions, and mitosis proceeds normally[11](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5493652/#CR11). The only change observed is a faster progression from metaphase to anaphase following Fam64a knockdown. These results strongly suggest that Fam64a has an indispensable role in CMs, whereas its role is not essential in HeLa cells.
https://pubmed.ncbi.nlm.nih.gov/28667270/
