### ISSUE TITLE
IPR001509 ->nucleotide-sugar metabolism 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#232]
I'm not sure about this one.

Certainly some like

dihydroflavonol 4-reductase family P53111

are these OK?

Val   

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/232":https://sourceforge.net/p/geneontology/annotation-issues/232

**Comment by linuxjackto1** [comment]
thanks www.movied.org
