### ISSUE TITLE
Incorrect PMID (and Functions) for Human CLIP1 Protein

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#2320]
Human CLIP1 protein (P50238)
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P50238
has 2 molecular functions ("DNA binding, bending" and "AT DNA binding").  Both of these MFs refer to a published paper at PMID: 20108983
However, when reading the paper, it becomes clear that it refers to a different protein: High Mobility Group Protein AT Hook 2 (HMGA2).  HMGA2 does not appear to be a synonym of CLIP1 from what the Uniprot page has.  I cannot find "CLIP1" anywhere in the full manuscript.  I therefore think that the PMID is not correct.  Furthermore, I did a few PubMed searches and couldn't find (from the titles) anything linking CLIP1 to these 2 activities.

**Comment by ValWood** [comment]
I will dispute these in Protein2GO and point to this ticket

**Comment by ValWood** [comment]
Before I do this,  @keslingmj   the protein you point to here
 https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P50238
is CRIP1 not CLIP1. This doesn't invalidate the query but I'd like to check first that we are looking at the correct proteins.

**Comment by ValWood** [comment]
Dear  @keslingmj  
closing as out-of-date
If there is still an issue with the annotation you can  use the feedback form in
https://www.uniprot.org/uniprotkb/P50238/entry
to report to UniProt the annotation provider.

Thanks
Val
