### ISSUE TITLE
NTR: Repression of monocyte activation

### ISSUE THREAD

**Issue by milarolo** [geneontology/go-annotation#2321]
Could you please create this term: "Repression of monocyte activation"

It would be a child of "monocyte activation" (GO:0042117)

The request is for this paper: PMID:15597323 (Fig.3, also  1 and 2)

Thank you,

Mila

**Comment by pgaudet** [comment]
@milarolo Can you put this in the go-ontology tracker ? https://github.com/geneontology/go-ontology/issues

Thanks, Pascale
