### ISSUE TITLE
review reverse cholesterol transport painting 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2322]
Hi

I spent considerable time a long time ago annotating reverse cholesterol transport. I may have missed some of the proteins that should be associated with this term. However, I do not think that all paralogs of APOE should be associated with the reverse chiolesterol transport

eg PANTHER:PTN000439006|UniProtKB:P02647|UniProtKB:P02649|UniProtKB:P06727 should not be propagated to paralogs. 

If you find evidence that APOA5 is involved in this process please point me to the paper.

Thanks

Ruth

**Comment by marcfeuermann** [comment]
I've blocked the propagation to the APOA5 branch (PTN000439061).

**Comment by RLovering** [comment]
Thanks Ruth
