### ISSUE TITLE
PAINT species coverage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2323]
Is it possible to get a list (species/taxon ID) of all of the species that are covered by PAINT annotation currently. We are specifically interested in fungal and parasitic protazoa/kinetoplastids.

**Comment by ValWood** [comment]
@Achchuthan
@vanaukenk

**Comment by pgaudet** [comment]
http://www.pantherdb.org/panther/summaryStats.jsp

**Comment by ValWood** [comment]
Is there a text version of this list anywhere? @Achchuthan would like to do a diff with his list to see the difference.

**Comment by pgaudet** [comment]
@huaiyumi Is it possible to get the Panther species list in a txt file ?

**Comment by Achchuthan** [comment]
Thanks @ValWood. I have looked at the list in the summary stats page and compared to EuPathDB genomes list.
Here is the list. There are only 17 species.
[EuPathDB_genomes_in_PANTHER.xlsx](https://github.com/geneontology/go-annotation/files/3181864/EuPathDB_genomes_in_PANTHER.xlsx)

**Comment by ValWood** [comment]
and only 12 Fungi.

So the next question is how are the species decided. Are there plans to scale up to include other important Fungi? Clearly this is the best way to  high-quality get inferred annotations but we are limited  by the small number of species...

**Comment by ValWood** [comment]
closing....
