### ISSUE TITLE
Annotations to "cell"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2325]
It think we decided that direct annotations to cell were not really useful.  Should we add a 'direct annotation" block?

There are 2467 direct annotations, many are IEA (895)  mainly from GOC inferences. 

Only 582 are Experimental, mainly AgBAse. It isn't clear to me why cell was used because I assume most could be more specific?

![agbase](https://user-images.githubusercontent.com/7359272/56229677-5fb8de00-6072-11e9-8acb-862fc2b21a06.jpg)

**Comment by pfey03** [comment]
I deleted the 1 dictybase EXP annotation. was very old and plenty of better components annotated

**Comment by ValWood** [comment]
@pfey -OK will tag some of the others with small numbers will strengthen the case to make  "not for direct annotation"

@vanaukenk 
@ukemi 
@RLovering

**Comment by bmeldal** [comment]
Does this include those with "colocolizes_with" qualifiers? See preceeding [ticket](https://github.com/geneontology/go-annotation/issues/1940#issuecomment-483762020).

**Comment by ValWood** [comment]
All annotations.... so "colocolizes_with"  would be included...

**Comment by pgaudet** [comment]
I thought the GOC F->C annotations received the same Evidence as the original?

**Comment by pgaudet** [comment]
I tried to address part of this here: https://github.com/geneontology/go-ontology/issues/14235

**Comment by ValWood** [comment]
>I thought the GOC F->C annotations received the same Evidence as the original?

They did at one point but this did not make sense.
For example, if function A was know to occur in mitochondria and had IDA, mitochondria got IDA even though location has not been assayed. It was very confusing.

**Comment by pgaudet** [comment]
OK, that's good !!

**Comment by ValWood** [comment]
Out of date. "cell" no longer exists.
