### ISSUE TITLE
Zebrafish pregnancy a GO/Paint problem

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-annotation#2327]
There is a PAINT provided annotation for female pregnancy for the zebrafish crhbp.  Female zebrafish don't get pregnant so this annotation should not be made.  It looks like there is a taxon constraint for only in mammalia so I'm not sure why the annotation propagated.
http://amigo.geneontology.org/amigo/gene_product/ZFIN:ZDB-GENE-040801-196

crhbp | corticotropin releasing hormone binding protein |   | female pregnancy |   | GO_Central | Danio rerio | IBA | PANTHER:PTN000031419RGD:2403UniProtKB:P24387 | corticotropin-releasing factor-binding protein pthr10278 | protein |   | PMID:21873635 | 20171

**Comment by pgaudet** [comment]
Removed, thanks for the feedback.
