### ISSUE TITLE
Representation of protein complexes in GPI 2.0

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2328]
We need to add 2.0 specifications for representing protein-containing complexes and their members in GPI file format.

Right now, it looks like GOA is the only group submitting a specific gpi file for protein-containing complexes (I'm not sure if other groups are including complexes in their group-specific files).

Currently for articulating the complex members, it looks like there is a colon-separated list of names in the synonyms field:

ComplexPortal  CPX-9  atf1-atf4_human  ATF1-ATF4 transcription factor complex  ATF1:ATF4  protein_complex  taxon:9606

@bmeldal @alexsign - is that the correct interpretation of the above line in the human complex gpi file?

For the 2.0 specs, I'm thinking that we will want to have a new, distinct field for complex members and populate that with IDs, e.g. UniProtKB:P18846

I'm agnostic on the punctuation in between complex members, but @kltm @cmungall may have input here on the best approach or if there is punctuation we definitely shouldn't use.

**Comment by cmungall** [comment]
That example looks wrong, these are not names

ComplexPortal
protein_complex
taxon:9606

**Comment by bmeldal** [comment]
What should the structure of the GPI be? We did this with Tony and he gave us the specifications.

The current file is:
source | stable_ID | internal_shortlabel | recommended_name | synonyms[pipe_separated] | annotation_object_type | species_ID

e.g.
ComplexPortal	CPX-9	atf1-atf4_human	ATF1-ATF4 transcription factor complex	ATF1:ATF4	protein_complex	taxon:9606
ComplexPortal	CPX-58	mat_i_rat	Methionine adenosyltransferase complex variant 1	MAT I complex|Mat1a tetramer|AdoMet synthetase 1 complex|Methionine adenosyltransferase I/III|MAT-I/III|Mat1a complex	protein_complex	taxon:10116

**Comment by bmeldal** [comment]
ftp://ftp.ebi.ac.uk/pub/databases/intact/current/various/complex_portal.gpi

**Comment by vanaukenk** [comment]
@bmeldal 

I was actually just wondering if the current ComplexPortal gpi file routinely lists the members of the complex as synonyms, e.g. ATF1:ATF4, but from the rat example above, CPX-58, it looks like the answer is no.

I was thinking that we might want to have the ids of complex members listed in a new field of the gpi file, but is that overkill and could that information, if needed, be obtained from IntAct?

I can see that it might be useful to have this information for Noctua curation in order to visualize exactly what members are in a complex if that was the entity chosen for curation.  It might also be useful for outputting annotations to the individual gene/gene product members in the GPAD file.

@cmungall - I think the format of what I pasted in the initial ticket was confusing because there were pipes where tabs actually exist in the original file.  I fixed that above.

**Comment by bmeldal** [comment]
>I was actually just wondering if the current ComplexPortal gpi file routinely lists the members of the complex as synonyms, e.g. ATF1:ATF4, but from the rat example above, CPX-58, it looks like the answer is no.

No, "ATF1:ATF4" is the systematic name, a concatenation of gene symbols, but that's not unambiguous, of course.

>I was thinking that we might want to have the ids of complex members listed in a new field of the gpi file, but is that overkill and could that information, if needed, be obtained from IntAct?

We can supply a list of UniProt IDs for GPI2.0, that's not a problem. Or you can always grab them from the WS.

**Comment by cmungall** [comment]
> I think the format of what I pasted in the initial ticket was confusing because there were pipes where tabs actually exist in the original file. I fixed that above

Yes you are correct this was my misunderstanding. Thanks!

**Comment by suzialeksander** [comment]
Done, column 9
