### ISSUE TITLE
PANTHER:PTN000859004 phospholipid-translocating not transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2329]
see
https://github.com/geneontology/go-ontology/issues/17186
https://github.com/geneontology/go-annotation/issues/2330
for background

  | ivn1 | plasma membrane phospholipid-translocating ATPase complex Lem3 family subunit Ivn1 (predicted) |   | aminophospholipid transmembrane transporter activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000859004UniProtKB:Q3MIR4UniProtKB:Q9NV96 | cell cycle control protein 50 pthr10926 | protein |   | PMID:21873635 | 20180308

**Comment by marcfeuermann** [comment]
Good point. Family updated and wrong annotation removed !
Marc.
