### ISSUE TITLE
"lipid translocation" isn't transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2330]
From
https://github.com/geneontology/go-ontology/issues/17186

I used the matrix to identify violations

GO:0045332
should not probably overlap with
GO:0022857
or
GO:0055085 

![violations](https://user-images.githubusercontent.com/7359272/56730081-d62e9d80-674e-11e9-978c-4b0075658cc5.jpg)

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=isa_partof_closure:%22GO:0055085%22&fq=isa_partof_closure:%22GO:0045332%22

unfortunately, you cant switch this to an annotation view to see the evidence

but these are the sources:
![sources](https://user-images.githubusercontent.com/7359272/56730194-31609000-674f-11e9-9f95-013dc1ff55f1.jpg)

both of the PomBase ones will be fixed by
https://github.com/geneontology/go-annotation/issues/2329

**Comment by gthayman** [comment]
Hi Val,
I don't find any manual annotations in RGD to phospholipid translocation (GO:0045332) or its children that are co-annotated to either GO:0022857 or GO:0055085.
Tom

**Comment by ValWood** [comment]
Hi Tom, its possible this were coused by the PAINT annotations. I suggest  we don't review these until the PAINT updates filter through then I will update the numbers.

**Comment by ValWood** [comment]
Looking much better:


+ | − | (95) | UniProtKB
-- | -- | -- | --
+ | − | (51) | CGD
+ | − | (19) | MGI
+ | − | (19) | RGD
+ | − | (2) | ZFIN
+ | − | (1) | AGI_LocusCode
+ | − | (1) | FB
+ | − | (1) | dictyBase


<img width="903" alt="Screenshot 2023-09-01 at 16 34 03" src="https://github.com/geneontology/go-annotation/assets/7359272/b1983878-a1b0-420c-b395-e8424b22cd75">


This isn't super urgent but nice to keep it open as an example of error identification using the matrix tool

@Antonialock  you might want to look at the uniprot ones. It could be caused by a mapping issue (I can't tell easily without looking at the annotations in detail).

**Comment by Antonialock** [comment]
@ValWood If we want to use the matrix more in QC perhaps we could ask for more efficient tool-output?

**Comment by ValWood** [comment]
Agreed, this isn't efficient which is why I'm not pushing to close these, 
I just wondered if there was a mapping here that could be fixed. I will have a look later.

I planned to look for any obvious problems where we could maybe improve the terms defs or names, or add comments to prevent new violations.
it's a shame because we fixed up all the errors in these intersections for the paper, but  the rules were never implemented in a way that people can easily use them (there error reports, but they are somewhat buried).

**Comment by Antonialock** [comment]
It would be cool to have a tool that at least soft-checked you "you have made this annotation, but the gp is co-annotated to X violating rule Y", and to be able to pull out any annotations that violate any rules, be able to mark annotations as exceptions to the rule.

**Comment by ValWood** [comment]
That would be really nice.
Actually since the Matrix paper, the intersections have stayed pretty clean .
Here are the violations for the current rules - not bad!
http://snapshot.geneontology.org/reports/shared-annotation-check.html

But as you say tracking down to the violating annotation can be quite a pain, especially if a gene has a lot of annotations.
It would also be nice to  know immediately which species have errors.
It's not high on the priority list though in the grand scheme of things....

**Comment by ValWood** [comment]
We can close this one. I think most of the annotation inconsistencies  come from a single PANTHeR family

https://www.pantherdb.org/genes/gene.do?acc=SCHPO%7CPomBase%3DSPBC691.05c%7CUniProtKB%3DO13621

I looked at it a  while ago, and I couldn't figure it out:
https://www.pombase.org/gene/SPBC691.05c

It's either 2 families, or its multifunctional, or there are annotation errors, but it isn't a well charcterized family as far as I can see.
