### ISSUE TITLE
PANTHER:PTN002547992: BMP and cell cycle IBAs too specific

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2331]
Hi,

The annotations:
positive regulation of BMP signaling pathway 
G2/M transition of mitotic cell cycle 
propagated from PANTHER:PTN002547992 

are derived from one paper/gene evidence - http://amigo.geneontology.org/amigo/search/annotation?q=FBXL15

These are too process-specific for propagation using PAINT

**Comment by marcfeuermann** [comment]
I think that these processes can be PAINTed in some cases, but I have to admit that some nodes of PTHR13318 have some weird annotations. I've removed the propagation of both processes from PTN002547992, as well as few others in other places within the tree.
Marc.

**Comment by hattrill** [comment]
Ace - thanks!
