### ISSUE TITLE
Review annotations to GO:0015893 'drug transport' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2332]
**GO:0015893  drug transport** 
https://docs.google.com/spreadsheets/d/1bbLQuCNdbgNde_HiENICDwyyE-lIzs9pBE65zRLs5sg/edit#gid=0

Note that there are 2 worksheets: one for EXP and one for non-EXP annotations.

The suggestion is to move annotations to 'xenobiotic detoxification by transmembrane export across the plasma membrane'. Let me know if that is not appropriate. 

Group | Number of manual annotations 
-- | -- 
CGD | 4 @marekskrzypek
GeneDB | 4  @Achchuthan
MGI | 1 |
RGD | 5 @gthayman
SGD | 13 |
UniProt | 3 |
InterPro | IPR004734

Group | Number of non-manual annotations
-- | --
BHF-UCL | 1 | 
CGD | 33  @marekskrzypek
SGD | 1 |
UniProt | 2 |

**Comment by happy-lorna** [comment]
D'oh! we just missed getting this in the next release by 5 minutes! I will fix this when we are able to edit the data again, and it will be in the following release.

**Comment by hdrabkin** [comment]
mgi done did

**Comment by marekskrzypek** [comment]
CGD done

**Comment by bmeldal** [comment]
As for https://github.com/geneontology/go-annotation/issues/2333:

Some children include import processes, e.g.:
GO:0015889 cobalamin transport
Def: The directed movement of cobalamin (vitamin B12), a water-soluble vitamin characterized by possession of a corrin nucleus containing a cobalt atom, into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore.

or
GO:0015670 carbon dioxide transport
GO:0015671 oxygen transport
GO:0030185 nitric oxide transport

My complexes: 
[Vitamin B12 outer membrane transporter complex](https://www.ebi.ac.uk/complexportal/complex/CPX-1083)
[Cobalamin transport complex](https://www.ebi.ac.uk/complexportal/complex/CPX-2105)
Hemaglobins

**Comment by milarolo** [comment]
SWIE done

**Comment by pgaudet** [comment]
@bmeldal The children will just move under a more appropriate parent (as inferred by ChEBI).

**Comment by bmeldal** [comment]
Ok, so no action required if annotated to children.

**Comment by Achchuthan** [comment]
GeneDB done

**Comment by gthayman** [comment]
RGD done.

**Comment by suzialeksander** [comment]
SGD done.

**Comment by happy-lorna** [comment]
InterPro done

**Comment by pgaudet** [comment]
@mgiglio99 
There are 3 TIGR annotations remaining to drug transport (ISS). I tried to replace the annotations but there are no homology to any sequences in UniProt (BLAST). What do you recommend we do ? 


UniProtKB:A0A0F7RN55
UniProtKB:A0A0J1HRK2
UniProtKB:Q81VC8

Thanks, Pascale

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
HI @Achchuthan 
There are 4 GeneDB annotations to 'drug transport' all from PMID:20851719, which is a HTP assay that is not directly testing transport, as far as I can tell. 

Can you please have another look ? 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet,
I have already removed these annotations in our database and updated the spreadsheet. When we update our records with GO next time, they should be removed.
Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Ah ok thanks !
