### ISSUE TITLE
Review annotations to GO:0046618 drug export

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2334]
Please review annotations to GO:0046618 drug export

https://docs.google.com/spreadsheets/d/1UHEa8r_nU6I2SAw_8HWwNzHsj5518CLy3sUPqnK2I9g/edit#gid=0

The suggestion is to move annotations to 'xenobiotic detoxification by transmembrane export across the plasma membrane'. Let me know if that is not appropriate.

Group | Number of manual annotations 
-- | --
CGD | 21 @marekskrzypek
EcoCyc | 7
RGD | 6
TAIR | 1
UniProt | 3

InterPro:IPR005285

**Comment by marekskrzypek** [comment]
CGD done

**Comment by milarolo** [comment]
All the UniProt ones are SWIS so I can't change them

**Comment by amandamackie** [comment]
Several of the EcoCyc terms are for transporters that capture the compound in the periplasm and pump it back out across the outer membrane (the plasma membrane is the inner membrane in diderm bacteria). I require the term 'xenobiotic detoxification by transmembrane export across the outer membrane'. I know this was discussed as part of an earlier post but I'm not clear on what the outcome was.

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
@amandamackie I created the term you requested https://github.com/geneontology/go-ontology/issues/17234

**Comment by bmeldal** [comment]
3 complexes changed

**Comment by happy-lorna** [comment]
InterPro done
