### ISSUE TITLE
Lost MF annotation from PTHR24031:SF594

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2335]
We've lost an MF annotation to C. elegans ddx-52 (WBGene00011032) that was coming from PAINT.

The annotation was to 'ATP-dependent RNA helicase activity' GO:0004004 which seemed like a reasonable annotation to make.

Looking at the members of the sub-family listed in Panther
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR24031:SF594

it looks like there are experimental annotations at least from S. cerevisiae Rok1 to support this PAINT annotation and more experimental support from the larger family..

What's the best way to figure out why an annotation was removed?

Thx.

**Comment by pgaudet** [comment]
@huaiyumi @dustine32 @thomaspd 
@marcfeuermann and I just looked at the tree, and ALL annotations are gone. This is a family of around 3000 members. Looks like the annotations were lost during Panther migration 12-> 13. 

@huaiyumi @dustine32 Can you have a look ? In cases where all annotations are lost during an update we should get some notification (The tree status was 'partially curated'). 

Thanks, Pascale

**Comment by huaiyumi** [comment]
The GO term GO:0004004 ATP-dependent RNA helicase activity was annotated to PTN000618218 in PTHR24031 before PANther13. The family was labeled as partially curated. When PANTHER 13 was built, the PTN was not able to be tracked forwardly (i.e., PTN000618218 was gone in 13). As a result, the IBD annotation was lost and the family was labeled as "Require paint review".

**Comment by pgaudet** [comment]
Are there other families that have lost ALL their annotations?

**Comment by marcfeuermann** [comment]
PTHR24031 is a huge family which contains 3085 leafs, with 98 MF, 105 CC and 294 BP primary GO annotations. It seems really weird that all the PAINT annotations have been lost since many are specific to some nodes. Anyway, I've re-annotated the family and the terms should be back in the next release.
Regards,
Marc.
