### ISSUE TITLE
PAINT annotations to obsolete terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2336]
According to the error reports in snapshot, these families have annotations to obsolete terms: 

GO:0008565 protein transporter activity
--
family not   named pthr28188
family not   named pthr34597
mitochondrial   import inner membrane translocase subunit tim-17 pthr10485
mitochondrial   import inner membrane translocase subunit tim22 pthr14110
mitochondrial   import receptor subunit tom20 pthr12430
mitochondrial   import receptor subunit tom40 pthr10802
secy/sec61-alpha   family member pthr10906
succinate   dehydrogenase pthr13337
tim23   pthr15371

GO:0042891   antibiotic transport
--
family not   named pthr23501
family not   named pthr24220
family not   named pthr24221

We need to wait for PAINT to load the new version of GO to be able to correct these.

**Comment by marcfeuermann** [comment]
**PTHR28188:** Now annotated to GO:0008320 "protein transmembrane tranporter activity" - Okay
**PTHR34597:** Now annotated to GO:0008320 "protein transmembrane tranporter activity" - Okay
**PTHR10485:** Now annotated to GO:0008320 "protein transmembrane tranporter activity" - Okay
**PTHR14110:** Now annotated to GO:0008320 "protein transmembrane tranporter activity" - Okay
**PTHR12430:** Not a transporter, assembles the transporter complex, annotated as CONTRIBUTES_TO GO:0008320- Reviewed.
**PTHR10802:** Now annotated to GO:0008320 "protein transmembrane tranporter activity" - Okay
**PTHR10906:** Now annotated to GO:0008320 "protein transmembrane tranporter activity" - Reviewed.
**PTHR13337:** A tiny node (2 proteins) annotated now to GO:0008320 "protein transmembrane tranporter activity" - Okay
**PTHR15371:** Now annotated to GO:0008320 "protein transmembrane tranporter activity", and GO:0015171 "amino acid transmembrane transporter activity" - Okay
**PTHR23501:** various compounds transported, annotated at the root to GO:0055085 "transmembrane transport" - Reviewed
**PTHR24220:**  Various compounds transported, annotated at the root to GO:0055085 "transmembrane transport" - Okay
**PTHR24221:** Various compounds transported, annotated at the root to GO:0055085 "transmembrane transport" - Okay
