### ISSUE TITLE
Does yeast YBT1  really transport bile ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2337]
YBT1 is annotated to 'bile acid-exporting ATPase activity' and 'bile acid and bile salt transport'. Looking at the paper this does not seem to be physiologically relevant - they have assayed this looking for a human gene. 

Can you please review ? 

Thanks, Pascale

**Comment by srengel** [comment]
hi @pgaudet the annotation seems valid, but we will discuss here to be sure..will get back to you...

**Comment by srengel** [comment]
Hi Pascale, we discussed as a group, and have changed the F and P annotations to each go one step up to 
F: ATPase-coupled monocarboxylic acid transmembrane transporter activity
and 
P: monocarboxylic acid transport
