### ISSUE TITLE
Annotation review  - lipopolysaccharide transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2338]
Hi @amandamackie

I am looking at LPS transport. There are 2 similar function terms annotated by EcoCyc: 
- GO:0015221 lipopolysaccharide transmembrane transporter activity
- GO:0015437 lipopolysaccharide-transporting ATPase activity 

GO:0015221 lipopolysaccharide transmembrane transporter activity
--

https://docs.google.com/spreadsheets/d/1YBI0sCECGx20VPa92th4awrXf6oZZGJDICzLV2XDCjE/edit#gid=0

yhjD (P37642)
The evidence is weak (mutant phenotype) to show the function; the role in transport seems convincing. I would propose to remove that MF annotation. 

GO:0015437 lipopolysaccharide-transporting ATPase activity 
--

https://docs.google.com/spreadsheets/d/1DkjObyBL2SYoO0FKzFF43w_By0xmqt57jT0bNzIqi-Q/edit#gid=0

LPT system: contains msbA, and lptA-G. 
* msbA seems to be a flippase/floppase (translocation of LPS within the inner membrane)
* lptB/C/F/G could be annotated to 'lipopolysaccharide releasing activity'  (like we did for the lol system) (not ethat this term does not yet exist)
* lptA is a carrier that brings LPS from the inner membrane to the outer membrane
* lptD/E are flippases/floppases that translocate LPS within the outer membrane. 

We propose to move 'GO:0015437 lipopolysaccharide-transporting ATPase activity ' under 'intermembrane lipid transporter activity
So: 
1. msbA would be OK
2. lptB/F should be re-annotated to 'lipopolysaccharide releasing activity'  (need to create the term, if you think this is OK). 

It also looks like the other members of the complex could be annotated. 
Let me know if you want me to create 'lipopolysaccharide releasing activity' and 'lipopolysaccharide carrier activity' . 

Let me know what you think. 

Thanks, Pascale

**Comment by amandamackie** [comment]
There's a few issues here; I'll address them in point form
1. _yhjD (P37642)
The evidence is weak (mutant phenotype) to show the function; the role in transport seems convincing. I would propose to remove that MF annotation._ 

I agree and will remove that MF annotation

2. _We propose to move 'GO:0015437 lipopolysaccharide-transporting ATPase activity ' under 'intermembrane lipid transporter activity
So: msbA would be OK_

But 'intermembrane lipid transporter activity' is defined as movement from a donor membrane to a separate acceptor membrane so MsbA would not be OK because it mediates translocation within a membrane. Perhaps I have misunderstood what you are proposing?

3. _lptB/F should be re-annotated to 'lipopolysaccharide releasing activity' (need to create the term, if you think this is OK)._

I'm not comfortable with the term 'LPS releasing activity' for this system (unlike the Lol system where LolCDE has been shown to mediate the actual release of lipoprotein from proteoliposomes in vitro). I believe current thinking on the Lpt system is that LptBFGAC forms a continuous bridge from the IM to the OM and ATP hydrolysis (by the LptB ATPase) 'pushes' LPS across the periplasm. At some stage LPS will be released (extracted is probably a better word) from the inner membrane but I would be hesitant to assign this function to specific gene products. 

So I would suggest that 'intermembrane lipopolysaccharide transporter activity' is an appropriate term for LptBFGAC. 
MsbA and LptB are both ATPases; I would describe them as having 'ATPase activity, coupled to movement of LPS'.

Hope this helps - if I can contribute anything further let me know

Amanda

**Comment by pgaudet** [comment]
Hi @amandamackie 

Thanks a lot for your feedback. 

> We propose to move 'GO:0015437 lipopolysaccharide-transporting ATPase activity ' under 'intermembrane lipid transporter activity

Right ! My mistake. The label was changed to 'ATPase-coupled intramembrane lipopolysaccharide transporter activity'.

Can you also annotate lptD and E to this term? 

I will create 'ATPase-coupled intermembrane lipopolysaccharide transporter activity' for you to annotate lptB; does that work ? Or do you also want 'intermembrane lipopolysaccharide transporter activity'? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi again, 

I just came across that paper: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6164715/figure/ijms-19-02680-f001/

Looks like A (and perhaps C and D) are carriers, rather than transporters (according to the GO definition, a carrier is 'Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location.' ) 

The paper also mention that 'LptD and LptE (yellow) sort LPS to the outer leaflet of the outer membrane', which sounds similar to the 'releasing activity' of the lol 

This also sounds similar to the term you have requested in #15917. 

Thanks again, 

Pascale

**Comment by bmeldal** [comment]
Watching as we have 2 complexes annotated to GO:0015437. Let me know when the new structure is in place and I will make any required updates accordingly.

**Comment by amandamackie** [comment]
Yes that's a good depiction of the current model. The LptA and C proteins form the bridge across the periplasm for movement of LPS. Its a bit semantic as to whether they are carriers or transporters; I see that GO defines transporters as forming a pore which allows passing of molecules. The LptA and C proteins aren't pore forming but they are thought to form a continuous chamber across the periplasm that protects the lipid moiety of LPS as it passes through the periplasm (see Fig 2 of that same paper). For this reason I would prefer to call them transporters. I've really never seen them referred to as 'carriers'.

The LptD and E proteins form a complex that (as part of the larger seven protein LPt complex) inserts/assembles the LPS into the OM and I think any GO term should reflect this eg 'lipopolysaccharide insertion into outer membrane' as a child of 'outer membrane organization'. Neither of them have ATPase activity.

**Comment by pgaudet** [comment]
Hi again @amandamackie 

I have changed the term label of 'GO:0015437 lipopolysaccharide-transporting ATPase activity' to 'lipopolysaccharide floppase activity', which is an ATPase the transfers a lipopolysaccharide from the cytosolic to the exoplasmic leaftlet of a membrane. 

There are annotations to msbA, lptB and ltpF; is this right?

**Comment by jimhu-tamu** [comment]
floppase? Where does "floppase" come from? Did you mean flippase?

**Comment by amandamackie** [comment]
I would only annotate MsbA to LPS flippase activity.
LptB is not a flippase; the specific molecular function of LptF as part of the Lpt complex is not clear (although it could be assigned a BP term for intermolecular LPS transport)

Amanda

**Comment by pgaudet** [comment]
@jimhu-tamu There are both flippases and floppases, depending on the direction in which they transfer the lipid within the membrane, see https://www.ncbi.nlm.nih.gov/pubmed/20043909

**Comment by pgaudet** [comment]
@amandamackie So you need to remove the annotation to lptB and then this can be closed; is this right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Sorry - I need to create 'intermembrane lipopolysaccharide transporter activity' for you to be able to annotate lptB; right ?

**Comment by jimhu-tamu** [comment]
@pgaudet : OK, so there are citations to floppases and the distinction is based on the directionality. Unfortunately, the convention described in the paper you linked is not consistent with usage in other contexts. 

> Flippases and floppases are ATP‐dependent transbilayer lipid translocators. According to an extensively used, though not universal, nomenclature they catalyze lipid transfer towards the inward monolayer (flippase) or towards the outward monolayer (floppases). Some authors however use the name floppase to denote any enzyme catalyzing transbilayer lipid motion, in some cases even in the absence of ATP requirements.

In the bacterial literature related to peptidoglycan biosynthesis, enzymes that move Lipid II from the inner leaflet to the outer leaflet are called flippases. There also seems to be disagreement about directionality in the multidrug resistance pump literature.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC178438/pdf/1785853.pdf

> Interestingly, the product of the mouse mdr2 gene, a homolog of multidrug efflux protein gene mdr1, is a phospholipid flippase, which translo- cates phospholipid from the inner to the outer leaflet of the bilayer (44).

**Comment by amandamackie** [comment]
> 
> 
> Sorry - I need to create 'intermembrane lipopolysaccharide transporter activity' for you to be able to annotate lptB; right ?

For LptB I require the molecular function term: ATPase activity coupled to movement of LPS 
and for both LptB and LptF I require a biological process term: intermembrane LPS transport

I would suggest PMID 24639492 for the LptB function term and perhaps one of the recent prokaryotic LPS transport review refs for the BP term eg 28878019
Thanks,
Amanda

**Comment by pgaudet** [comment]
Hi @jimhu-tamu 

I just looked over the literature and there seems to be no mention of floppases in bacteria, regardless of the direction in which an enzyme moves lipids in a membrane - ie the same name is used in both cases. Therefore I propose we keep the flip/floppase nomenclature, unless you have other suggestions. 

In cases where the directionality is unknown, please use the parent 'intramembrane lipid transporter activity'. 

I hope that works for you. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi again @amandamackie 
> LptB I require the molecular function term: ATPase activity coupled to movement of LPS

With the Molecular Function refactoring, we don't have this specific term in the ontology anymore (MF coupled to a BP). I suggest you annotate it to 'ATPase activity' and 'contributes to' 'intermembrane lipopolysaccharide transporter activity' (created new term here: https://github.com/geneontology/go-ontology/issues/17276) 


For the BP,  would 'LPS localization to cell outer membrane' work ? 

Thanks, Pascale

**Comment by amandamackie** [comment]
Done: removed the 'floppase' term from LptB and LptF and reannotated.
LPS localization to cell outer membrane would work

Amanda

**Comment by pgaudet** [comment]
Great ! So this is all taken care of. The new term (LPS localization to cell outer membrane would work) was created yesterday. 

Thanks so much for your help ! 

Pascale

**Comment by pgaudet** [comment]
I assume this is OK ? Please reopen if there are unresolved issues.
