### ISSUE TITLE
PANTHER:PTN000218063 TGF-beta superfamily ligands

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2339]
Looking at propagation from PANTHER:PTN000218063, I can see a number of problems:

1. D.mel has 7 TGF-beta superfamily members, but they are either BMP or activin receptor ligands (I am currently culling any TGF terms in FlyBase). I curator notes refer to the issues with the TGF superfamily and Ruth noted this issue back in 2016).
FBgn0026199	myoglianin	myo
FBgn0031461	dawdle	daw
FBgn0024913	Activin-beta	Actbeta
FBgn0039914	maverick	mav
FBgn0005590	screw	scw
FBgn0024234	glass bottom boat	gbb
FBgn0000490	decapentaplegic	dpp

Could you block: transforming growth factor beta receptor binding for those listed above.

2. I would also sugest that:
regulation of MAPK cascade 
regulation of apoptotic process
which are only supported by one annotation, and are not direct regulation are removed.

3. For MGI:MGI:103302 (Bmp7) - cell development - is getting the IBA from itself (only). I would suggest that this term is a bit too high-level to be worth propagating any way.

**Comment by marcfeuermann** [comment]
I've reviewed family PTHR11848. It is a quite complicated family and needs perhaps input from an expert.  The best was to clean all and annotate it again from zero. I have restricted "transforming growth factor beta receptor binding" (point1) and removed the 3 annotations mentioned in points 2 and 3.

**Comment by hattrill** [comment]
Thanks, Marc! I've done a bit of background into the conservation/diversification for these pathways and yes, it is very complicated :-)
