### ISSUE TITLE
Annotation review: lplT 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2340]
Hello @amandamackie

 lplT is annotated to 'lysophospholipid transporter activity'
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P39196

but is a flippase according to the reference: PMID:15661733

Can you please have a look ? 

Thanks, Pascale

**Comment by amandamackie** [comment]
Thanks, I've removed the incorrect term. Can I request a new term for 'lysophospholipid translocation' please? in the meantime I've reannotated to GO:0045332 phospholipid translocation. 

Amanda

**Comment by pgaudet** [comment]
https://docs.google.com/spreadsheets/d/1ezdmt4CQqfMvIevd3RnPBMiUVQGJ72AySj5rZQAO1ZU/edit#gid=0

**Comment by pgaudet** [comment]
Hi @amandamackie I created the term you requested: 
https://github.com/geneontology/go-ontology/issues/17232

Thanks, Pascale

**Comment by pgaudet** [comment]
Note to @pgaudet 
Check 2 BHF annotations in the google spreadsheet.

**Comment by pgaudet** [comment]
OK, all good.
