### ISSUE TITLE
Annotation review:  GO:0004012 phospholipid-translocating ATPase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2342]
~@marcfeuermann and I still need to add suggestions~

Suggestions now added - see spreadsheet

https://docs.google.com/spreadsheets/d/1Pzr5O9-9ZTsbG75IfDH1pho1GqQ708hN_UNrAAofTx8/edit#gid=0

**Comment by pgaudet** [comment]
Hello, 

GO:0004012 phospholipid-translocating ATPase activity will be merged into its parent (see https://github.com/geneontology/go-ontology/issues/17281), since it is not a useful grouping class (a more specific annotation can always be made). 

Would you please review your annotations to 'GO:0004012 phospholipid-translocating ATPase activity' 


Group | Number of EXP 
-- | --
CGD | 2
MGI | 2
SGD | 21
TAIR | 1
WB | 2

Thanks, Pascale

**Comment by pgaudet** [comment]
To check: do we still need the term GO:0004012 ATPase-coupled phospholipid transporter activity? All genes can be annotated to more specific terms.

**Comment by tberardini** [comment]
TAIR done

**Comment by marekskrzypek** [comment]
CGD done

**Comment by suzialeksander** [comment]
SGD done

**Comment by pgaudet** [comment]
GO:0004012 phospholipid-translocating ATPase activity  is merged into     GO:0140326
    ATPase-coupled intramembrane lipid transporter activity

2 wormbase annotations left to review, that could be made more specific (but annotations are correct).
