### ISSUE TITLE
Annotation review SGD:OXA1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2343]
I am updating ISS's based on  the transmembrane transport/translocation revisions and I have this
https://www.yeastgenome.org/locus/S000000956#go

ISS's to both 
ion channel activity (IDA)
membrane insertase activity (IMP)
which seems to be mutually incompatible?

Also the process annotation are confusing me

mitochondrial genome maintenance (IMP, IGI)
mitochondrial proton-transporting ATP synthase complex assembly (IMP)
look like indirect  phenotypes from incorrect insertion of membrane proteins?

(I'm keeping the insertase ISS's since  these fit the description)

**Comment by srengel** [comment]
Hi @ValWood i deleted the ion channel and genome maintenance annotations.
