### ISSUE TITLE
Human Arglu1 protein Q9NWB6 involved in Estrogen-dependent Gene expression

### ISSUE THREAD

**Issue by keslingmj** [geneontology/go-annotation#2345]
Human Arglu1 protein Q9NWB6 has been shown to interact with the Mediator 1 protein (MED1) and with it affect the expression of estrogen-dependent genes.  PMID: 21454576

**Comment by RLovering** [comment]
sorry what is this ticket about? Do you want someone to annotate this paper for you?

**Comment by keslingmj** [comment]
Hi.
Thank you for your response.
I am working with Panther and am not trained to perform literature curation with GO.
I’m hoping that someone else can annotate this paper.
Thank you

**Comment by pgaudet** [comment]
Hi @keslingmj 
It's unlikely anyone here will deal with these requests. For annotation of human genes I suggest you contact: https://www.uniprot.org/contact

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
If it can wait we can suggest papers for CACAO students too.
