### ISSUE TITLE
PAINT for Set7 histone H3-K37

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2346]
https://github.com/pombase/website/issues/1217
https://www.pombase.org/reference/PMID:30773398

**Comment by ValWood** [comment]
except it doesn't appear to have a panther family, which is strange?

http://www.pantherdb.org/genes/gene.do?acc=SCHPO|PomBase%3DSPCC297.04c|UniProtKB%3DQ9Y7Q6

**Comment by marcfeuermann** [comment]
Yes indeed, it is not in a PANTHER family. The protein seems quite short and is not well conserved when compared to what is found in the other reference organisms used to create the PANTHER families. @huaiyumi do you have an idea about this ?

**Comment by ValWood** [comment]
yes it is short, it has a full SET though :
http://pfam.xfam.org/protein/Q9Y7Q6

**Comment by ValWood** [comment]
short version is quite common 
http://pfam.xfam.org/family/PF00856#tabview=tab1

(in fact some of the longer  SETS seem like they may have other  domains embedded..)

**Comment by marcfeuermann** [comment]
I was just trying to guess why it does not appear in any PANTHER family. The presence of the SET domain should indeed be sufficient to get into a family. I remember that we had similar problems with some _S. pombe_ ATG proteins and it was resolved.  @huaiyumi has probably a better idea about this problem and how to solve it.

**Comment by pgaudet** [comment]
I created a ticket in the Pantherdb tracker: https://github.com/pantherdb/Helpdesk/issues/5
