### ISSUE TITLE
 IPR011012 Longin-like

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#235]
"IPR011012 Longin-like" is mapped to transport, but
there is a note saying that the signature is under
review. Do you leave these mappings? 

Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/235":https://sourceforge.net/p/geneontology/annotation-issues/235

**Comment by linuxjackto1** [comment]
thanks www.movied.org
