### ISSUE TITLE
Review annotations to GO:0010175 sphingolipid transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2352]
See 
https://docs.google.com/spreadsheets/d/16t8QD2nbjKxRluepNXLdbdFqQjYcai4x7jEoUohnipI/edit#gid=0

single annotation by TAIR

**Comment by pgaudet** [comment]
The paper seems to describe an intermembrane spingosine transfer activity 
PMID:11850411 "we tested the ability of heterologously expressed ACD11 protein to catalyze the transfer of three different sphingolipids between vesicles in vitro"; "ACD11 had a small, but reproducible catalytic effect on the transfer of Sph, whereas Sph transfer in the presence of GLTP was equal to the background level"

**Comment by pgaudet** [comment]
I will change the term label. No action needed. Please let me know if you disagree @tberardini

**Comment by tberardini** [comment]
Not much time to review and respond but looks ok.
