### ISSUE TITLE
IPR005897 move mapping down ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2353]
Hi, 

I think IPR005897 could have the more specific MF annotation 

GO:0043214 ATPase-coupled bacteriocin transmembrane transporter activity

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Thank you for this. I have replaced the GO term with GO:0043214. This will be visible in InterPro75.0.
Regards, 
Hsin-Yu
