### ISSUE TITLE
Review annotations to GO:0005548 phospholipid transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2357]
https://docs.google.com/spreadsheets/d/1Fugsh079Mtrl_ltsoCATWqzt9AEEZMaPzatHzzgycdo/edit#gid=0

(suggestions still being added)

**Comment by pgaudet** [comment]
Hello, 

Please review your annotations to GO:0005548 phospholipid transporter activity . 

Note that some new terms are required for some of the new annotations;I created these terms today. 



Contributor   (Assigned by)
--
ARUK-UCL | 1
BHF-UCL | 4
CGD | 6
GR | 1
MGI | 4
RGD | 1
TAIR | 1
UniProt | 8

**Comment by pgaudet** [comment]
@milarolo There is a single SWIE - I added the information in Column A. 

Thanks, Pascale

**Comment by gthayman** [comment]
RGD done (deleted).

**Comment by milarolo** [comment]
> @milarolo There is a single SWIE - I added the information in Column A.
> 
> Thanks, Pascale

Almost done. Waiting for the new term to become available in QuickGo

**Comment by pgaudet** [comment]
Hi all,


The new terms are now in Protein2GO, you can go ahead and change the annotations. 

Thanks, Pascale

**Comment by tberardini** [comment]
TAIR done

**Comment by milarolo** [comment]
SWIE done. New term added ("GO:NEW phosphatidylcholine flippase activity")

**Comment by ValWood** [comment]
pombase has none to
phospholipid transporter activity
but we do have

phosphatidylcholine transporter activity

should these be addressed too?

**Comment by marekskrzypek** [comment]
CGD done

**Comment by pgaudet** [comment]
EcoCyc and BHF + ARUK annotations not yet done.

**Comment by amandamackie** [comment]
EcoCyc done - reannotated to phospholipid transfer activity

**Comment by RLovering** [comment]
UCL done
