### ISSUE TITLE
Incorrect contributor FLYBASE

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2358]
Hi @hattrill 
There are 2 annotations that have FLYBASE rather than FlyBase: 

- hyi | hydroxypyruvate isomerase |   | glyoxylate metabolic process |   | FLYBASE | Escherichia coli K-12 | IDA |   | family not named pthr43489 | protein | PR:P30147 | PMID:10561547 | 20120612
- hyi | hydroxypyruvate isomerase |   | hydroxypyruvate isomerase activity |   | FLYBASE | Escherichia coli K-12 | IDA |   | family not named pthr43489 | protein | PR:P30147 | PMID:10561547 | 20120612

Can these be fixed ? 

Thanks, Pascale

**Comment by hattrill** [comment]
We fixed them a while back at P2GO, but then discovered that the source is actually from the EcoCyc GAF - not sure where they are with this. Perhaps GO_central could block them?

Below is the email from Ingrid Keseler about getting this sorted:

--------
Hi Helen,

Yes, these annotations definitely came to EcoCyc via our GOA import.  I have changed the attributions in beta EcoCyc to FlyBase, but our next released version (which will presumably be used to generate an updated annotation file) is already long frozen.  I'm cc'ing Jim and Debby (EcoliWiki), who should be able to make the change to the submitted file on their end.

Cheers,
Ingrid

P.S. I actually see a third annotation for that protein from FlyBase, to GO:0042803.

On 3/27/19 7:38 AM, Helen Attrill wrote:
Hi,

In the ecocyc GAF (the current one available from GO), there are two annotations attributed to FLYBASE:

UniProtKB	P30147	hyi		GO:0046487	PMID:10561547	IDA		P	hydroxypyruvate isomerase	hyi|ybbG|gip|b0508|ECK0501	protein	taxon:83333	20120612	FLYBASE		PR:P30147
UniProtKB	P30147	hyi		GO:0008903	PMID:10561547	IDA		F	hydroxypyruvate isomerase	hyi|ybbG|gip|b0508|ECK0501	protein	taxon:83333	20120612	FLYBASE		PR:P30147

Could you change this to FlyBase (it is causing some confusion when users chose FLYBASE as a source and only get two annotations). This may stem from the GOA pipeline - I’ve updated the attribution using Protein2GO, so if that is the underlying cause it should get fixed on the next import, but if not - could you fix it at your end?
-------------------------------

**Comment by pgaudet** [comment]
Ah! And maybe this is also the source for "UniProtKB" ? @keseler @alexsign

**Comment by keseler** [comment]
Sorry for the late reply.  For reasons only known to Microsoft, git emails often - not always! - get sorted into my spam folder, and I have no control whatsoever over it.  
Anyway, I feel like I should know this or once knew it, but is UniProtKB no longer being used?  Is it now "UniProt", or something else?  Is there documentation for this?  Obviously we have been using "UniProtKB" in very many places; I'll see what I can do to get this changed...

**Comment by hattrill** [comment]
Hi Keseler, 
We had it fix the same problem a while ago.
UniProt should be used for the GO contributor, but still use UniProtKB for protein identifiers.....it is to do with the distinction between the curators and the knowledgebase.

**Comment by pgaudet** [comment]
The documentation is here: 

https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

For example for the Database UniProt, the ID prefix is UniProtKB

**- database: UniProtKB**
  name: Universal Protein Knowledgebase
  description: A central repository of protein sequence and function created by joining the information contained in Swiss-Prot, TrEMBL, and PIR database
  rdf_uri_prefix: http://identifiers.org/uniprot/
  generic_urls:
    - http://www.uniprot.org
  entity_types:
    - type_name: protein
      type_id: PR:000000001
      id_syntax: ([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z]([0-9][A-Z][A-Z0-9]{2}){1,2}[0-9])((-[0-9]+)|:PRO_[0-9]{10}|:VAR_[0-9]{6}){0,1}
      url_syntax: http://www.uniprot.org/uniprot/[example_id]
      **example_id: UniProtKB:P51587**
example_url: http://www.uniprot.org/uniprot/P51587

Thanks, Pascale

**Comment by hattrill** [comment]
FLYBASE > FlyBase, so will close.
