### ISSUE TITLE
IPR004827 Basic-leucine zipper (bZIP) transcription factor

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#236]
Hello, 

For "IPR004827 Basic-leucine zipper (bZIP)
transcription factor", should we add function =
"GO:3700 transcription factor activity"?

Thanks, 
Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/236":https://sourceforge.net/p/geneontology/annotation-issues/236

**Comment by linuxjackto1** [comment]
thanks www.movied.org
