### ISSUE TITLE
sperm ejaculation looks like a readout for 'sexual behaviour'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2360]
Seems quite indirect:
https://www.ncbi.nlm.nih.gov/pubmed/20704641

RGD annotation transferred to human too.
Not sure who to tag for RGD?

**Comment by pgaudet** [comment]
@gthayman

**Comment by gthayman** [comment]
Hi Val,
I don't have immediate access to this paper and have requested it, which may take a few days. From the abstract, Slc6a4 knockouts affect the frequency of this process - seems like a reasonable annotation to me.
Tom

**Comment by ValWood** [comment]
I have the paper, this seems to be testing the effects of serotonin sexual disfunction? they are using ejaculation frequency to measure. The results don't look very significant anyway?

the study size is *tiny*  2 out of 8 animals never showed sexual activity during training. Because it is im- possible to calculate the sexual parameters for these rats, it was decided to exclude them for statistical comparison. Also when rats didn't reach a second ejaculation, these rats were excluded for the statistical comparisons for the secondary ejaculation series.

so these results could be random anyway?

Also, these experiments are performed in "flinder sensitive line" which appears to be a strain bred as a model for depression. Can this model rat be linked only to a single gene product (Slc6a4)?

**Comment by ValWood** [comment]
I was looking at the annotation to slca4 because 
 of this, which could be another can of worms

https://www.theatlantic.com/science/archive/2019/05/waste-1000-studies/589684/

but I can't find SLC6A4 mentioned in this rat paper?

**Comment by ValWood** [comment]
http://amigo.geneontology.org/amigo/gene_product/RGD:3714

**Comment by ValWood** [comment]
@pgaudet  
I'm not sure this annotation is correct for this gene from this paper/experiment (maybe some insider information), but if it is, for this gene do you think this is an example of a readout?

http://wiki.geneontology.org/index.php/Annotating_from_phenotypes

was "annotating phenotypes" ever covered in an annotation call?

**Comment by pgaudet** [comment]
"Annotating phenotypes" was discussed at least once. In any case, all annotations to that process are fairly old (most recent in 2010); it would be worth it to revisit, perhaps in a broader view, for example looking at behavior and readouts for behavior ?

**Comment by suzialeksander** [comment]
@gthayman were you able to review this annotation yet?

**Comment by gthayman** [comment]
Annotation changed.
