### ISSUE TITLE
Enhancer of rudimentary (IPR000781)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2361]
I don't think there is any evidence for nucleotide metabolism for enhancer of rudimentary.

the paper list refers to
http://europepmc.org/abstract/MED/9074495

function has been implicated in pyrimidine biosynthesis and the cell cycle (Wojcik et al. (1994) Genetics 138, 1163-1170).

I would remove this, and cell cycle and te notch signalling (which is not relevent for yeast)
More recent work implicates in mRNA metabolism (degradation).
https://www.pombase.org/reference/PMID:26942678

YTH-RNA-binding protein prevents deleterious expression of meiotic proteins by tethering their mRNAs to nuclear foci.
Shichino Y, Otsubo Y, Kimori Y, Yamamoto M, Yamashita A.
Elife. 2018 Feb 9;7. pii: e32155. doi: 10.7554/eLife.32155.

PMID: 29424342 Free PMC Article
Similar articles
Select item 28627136
3.
Enhancer of rudimentary homologue interacts with scaffold attachment factor B at the nuclear matrix to regulate SR protein phosphorylation.
Drakouli S, Lyberopoulou A, Papathanassiou M, Mylonis I, Georgatsou E.

FEBS J. 2017 Aug;284(15):2482-2500. doi: 10.1111/febs.14141. Epub 2017 Jul 8.
PMID: 28627136 Free Article

4.
Drosophila Enhancer of Rudimentary Homolog, ERH, Is a Binding Partner of RPS3, RPL19, and DDIT4, Suggesting a Mechanism for the Nuclear Localization of ERH.
Tsubota SI, Phillips AC.
Mol Biol Int. 2016;2016:8371819. Epub 2016 Oct 18.
PMID: 27830090 Free PMC Article
Similar articles

5.
Enhancer of Rudimentary Cooperates with Conserved RNA-Processing Factors to Promote Meiotic mRNA Decay and Facultative Heterochromatin Assembly.
Sugiyama T, Thillainadesan G, Chalamcharla VR, Meng Z, Balachandran V, Dhakshnamoorthy J, Zhou M, Grewal SIS.

Mol Cell. 2016 Mar 3;61(5):747-759. doi: 10.1016/j.molcel.2016.01.029.

PMID: 26942678 Free PMC Article
Similar articles

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
Thank you for the information you provided. This is a quite old entry that has not been reviewed for a while. You are right. I will remove the GO term and update the abstract. This will be visible in InterPro75.0.
Regards, 
Hsin-Yu
