### ISSUE TITLE
Review annotations to GO:0017127 cholesterol transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2364]
https://docs.google.com/spreadsheets/d/16NmWzd0cUufZKLqMGAs_yCZ2xx3zYm8lM8H5a0gZ7JE/edit#gid=0

Many apolipoproteins are annotated to this term; but they are not transoirters oer se. More accurately, they bind the lipids are form the apoplipoprotein particle. A more appropriate term might be 'apoplipoprotein structural activity'
See https://en.wikipedia.org/wiki/Apolipoprotein

@RLovering @gthayman @hdrabkin Would tha be OK for you ? If yes, I'll create the new term. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

this term does not describe all of the activities of these proteins, but I agree this would be a good term to use. 

However, some of these proteins bind to lipid particle receptors which then leads to endocytosis of the whole receptor-particle. How could this 'activity' be captured?

I guess it feels like not all structural molecules are required to enable the molecules bound in the complex to be transported to a different location

Thanks

Ruth

**Comment by pgaudet** [comment]
>  some of these proteins bind to lipid particle receptors which then leads to endocytosis 

Good point ! We don't have an activity for this, AFAIK. 
Cargo receptor binding ? or Cargo receptor ligand ? 

What do you think ?

**Comment by hdrabkin** [comment]
What about 'carrier activity', or more specifically lipid carrier activity?

**Comment by pgaudet** [comment]
For lipids, carriers are called 'lipid transfer activity' (this is the term we found most often in the literature with @marcfeuermann ) . Right now we have 

'lipid transfer activity'
'diacylglyceride transfer activity'
'glycolipid transfer activity'
'lipopolysaccharide transfer activity'
'phospholipid transfer activity'
'sphingolipid transfer activity'
'sterol transfer activity'
'triglyceride transfer activity'

(plus a few children). 

Pascale

**Comment by RLovering** [comment]
Looking at the definition of the tranfer activity terms I think that the lipid particle proteins should be annotated to this term. I am not sure how useful the term 'apoplipoprotein structural activity' will be, although it would potentially enable the lipid transfer proteins that are not in lipoprotein particles to be separated from those that are in lipoprotein particles.

The next question is how specific we should be when annotating the lipoprotein particle proteins?

For example from wikipedia:
Each native LDL particle contains a single Apo B-100 along with 80 to 100 additional ancillary proteins. Each LDL has a highly hydrophobic core consisting of linoleate and esterified and unesterified cholesterol molecules, as well as triglycerides (other fats) and is surrounded by a shell of phospholipids and unesterified cholesterol. 

So do we want to only specify the type of lipid transfer activity based on the lipid that is bound by the lipoprotein, or all the lipids in the lipoprotein particle (ie 'cholesterol transfer activity' and 'triglyceride transfer activity') or just apply the general lipid transfer activity term? 

Also should all proteins that are in the lipoprotein particle be associated with a lipid transfer activity term, even if lipid binding has not been shown (although maybe lipid binding data for all will be available). With caution for any enzymes in the lipoprotein particle!

Thanks

Ruth

**Comment by marcfeuermann** [comment]
Thanks Ruth for your feedback. 
Here are some comments/suggestions :

1 - I would say that, yes, lipid particle proteins should also be annotated to the "transfer" term. Apolipiproteins play a crucial structural role in the formation of such particles, so 'apoplipoprotein structural activity' refers to this function, which does not rule out to annotate them also to the transfer activity. 

2 - Most papers I've seen so far mentioned the transport of specific lipids (cholesterol, sphingosine-1-phosphate, ...) and I think, depending on the experimental evidence, we should annotate to the type of lipid transfer activity studied in the paper (especially when those terms already exist). When several/many different lipids or "rare" lipidic compounds are mentioned, we could use a more general term.  

3 - I see a lipoprotein particle as a complex whose role is to transport lipids, so I would annotate all the proteins that are in the lipoprotein particle to "CONTRIBUTES TO lipid transfer activity". 

Regards,
Marc.

**Comment by RLovering** [comment]
Great

what about the proteins that actually bind the receptors to facilate the endocytosis, would you use enables qualifier?

Ruth

**Comment by pgaudet** [comment]
Can you give examples? Aren't these cargo receptors ?

**Comment by marcfeuermann** [comment]
Good question ! :-) 
As the whole particle/complex plays the role of transporter, I would keep the qualifier for all and just complete with a receptor binding function. Endocytosis can then be annotated as BP.
This is my view and it can/should be discussed and modified.
Marc.

**Comment by RLovering** [comment]
I guess I am thinking of APOB see https://en.wikipedia.org/wiki/Apolipoprotein_B

- ApoB on the LDL particle acts as a ligand for LDL receptors

- Apolipoprotein B is the primary apolipoprotein of chylomicrons, VLDL, IDL, and LDL particles

- ApoB within the LDL (and all larger) particles remains somewhat unclear, it is the primary organizing protein (of the entire complex shell enclosing/carrying fat molecules within) component of the particles and is absolutely required for the formation of these particles. 

So I would expect ApoB to be annotated to enables transfer activity whereas the other Apos would be annotated to contributes_to

Ruth

**Comment by pgaudet** [comment]
Looking at this with @RLovering - all annotations are OK if we merge 
GO:0017127 cholesterol transporter activity
and GO:0120020 cholesterol transfer activity 

Thanks, Pascale

**Comment by gthayman** [comment]
RGD done.
