### ISSUE TITLE
Q6E213 NOT retinol O-fatty-acyltransferase activity from PMID:15220349

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2366]
Hi @deustp01 

A Swiss-Prot curator just reported that Q6E213 has not been shown to have retinol O-fatty-acyltransferase activity in the paper cited by Reactome (PMID:15220349). Can you please have a look ? 

Thanks, Pascale

**Comment by deustp01** [comment]
The assertion is correct but we should have cited PMID: 28096191 for the experimental evidence. We will fix that in Reactome. Can the UniProt curator make the fix to the UniProt record (that will get it out in public faster)?
Thanks

**Comment by pgaudet** [comment]
Thanks for the quick response. 

All we wanted was for the Reactome record to be fixed - do you see anything that needs fixing in UniProt ?

**Comment by deustp01** [comment]
I'm not an expert, but for what it's worth don't see any problem with the UniProt record. Reactome fix will propagate to our public site (and from there to UniProt) in September.

**Comment by pgaudet** [comment]
Great, that's perfect.
