### ISSUE TITLE
Review annotations to GO:0034204 lipid translocation and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2367]
For a possible merge and change of label - see 
https://github.com/geneontology/go-ontology/issues/14987

Annotations are here: 
https://docs.google.com/spreadsheets/d/1jY3X1uM-ywpnPs_gnneUpM_0g17vJDywqNs8KrJFbpE/edit#gid=158126030

**Comment by suzialeksander** [comment]
It looks like some of these were reviewed.  Due to the age of this ticket, if any more action were to happen on https://github.com/geneontology/go-ontology/issues/14987 a new spreadsheet would be needed anyway.
