### ISSUE TITLE
PAINT annotations to "intracellular"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2368]
cheers,
val

We have quite a few violations from PAINT in our checks
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPBC31F10.10c SPBC31F10.10c GO:0005622 PMID:21873635 IBA PANTHER:PTN002486649|UniProtKB:O42631 C Armadillo-type fold protein, zf-MYND type zinc finger protein UniProtKB:P87311|PTN000326637 protein taxon:284812 20180419 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPCC1020.06c tal1 GO:0005622 PMID:21873635 IBA PANTHER:PTN002242159|UniProtKB:Q5BGU0|UniProtKB:Q4WUP8 C Transaldolase UniProtKB:O42700|PTN000074387 protein taxon:284812 20180308 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC521.03 SPAC521.03 GO:0005622 PMID:21873635 IBA PANTHER:PTN002451405|UniProtKB:C8VUY4 C short chain dehydrogenase, human DHRS7 family(predicted) UniProtKB:Q9P7B4|PTN000673512 protein taxon:284812 20170228 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC3G9.11c pdc201 GO:0005622 PMID:21873635 IBA PANTHER:PTN000438887|UniProtKB:P87208 C pyruvate decarboxylase (predicted) UniProtKB:O42873|PTN000438935 protein taxon:284812 20170228 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC23C11.05 ipp1 GO:0005622 PMID:21873635 IBA PANTHER:PTN000815492|UniProtKB:Q5B912 C inorganic pyrophosphatase Ipp1 (predicted) UniProtKB:P19117|PTN002232111 protein taxon:284812 20180306 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC3A12.02 SPAC3A12.02 GO:0005622 PMID:21873635 IBA PANTHER:PTN000815492|UniProtKB:Q5B912 C mitochondrial inorganic diphosphatase (predicted) UniProtKB:P87118|PTN000032514 protein taxon:284812 20180306 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC186.09 pdc102 GO:0005622 PMID:21873635 IBA PANTHER:PTN000438887|UniProtKB:P87208 C pyruvate decarboxylase (predicted) UniProtKB:Q9P7P6|PTN000438895 protein taxon:284812 20170228 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC13A11.06 pdc202 GO:0005622 PMID:21873635 IBA PANTHER:PTN000438887|UniProtKB:P87208 C pyruvate decarboxylase (predicted) UniProtKB:Q09737|PTN001451544 protein taxon:284812 20170228 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPBC409.13 rib4 GO:0005622 PMID:21873635 IBA PANTHER:PTN000471873|UniProtKB:C8VFD4 C 6,7-dimethyl-8-ribityllumazine synthase UniProtKB:Q9UUB1|PTN000471882 protein taxon:284812 20170228 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPBC216.03 SPBC216.03 GO:0005622 PMID:21873635 IBA PANTHER:PTN000385404|UniProtKB:C8V3A5|UniProtKB:Q4X1F3 C NADP binding superfamily conserved fungal protein UniProtKB:Q9Y7K0|PTN000385453 protein taxon:284812 20170228 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPBC30D10.05c SPBC30D10.05c GO:0005622 PMID:21873635 IBA PANTHER:PTN002453021|UniProtKB:Q5AVU0 C sepiapterin reductase (predicted) UniProtKB:O14351|PTN000673797 protein taxon:284812 20170601 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC1F8.07c pdc101 GO:0005622 PMID:21873635 IBA PANTHER:PTN000438887|UniProtKB:P87208 C pyruvate decarboxylase (predicted) UniProtKB:Q92345|PTN000438894 protein taxon:284812 20170228 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPBC23G7.10c SPBC23G7.10c GO:0005622 PMID:21873635 IBA PANTHER:PTN000527805|UniProtKB:Q4WHS9|UniProtKB:Q5AY77 C NADH-dependent flavin oxidoreductase, implicated in cellular detoxification from family members (predicted) UniProtKB:O94467|PTN000527817 protein taxon:284812 20171117 GO_Central
WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms (GO:0005622) -- PomBase SPAC869.02c yhb1 GO:0005622 PMID:21873635 IBA PANTHER:PTN001116481|UniProtKB:Q5AX11 C nitric oxide dioxygenase Yhb1 UniProtKB:Q9URY5|PTN000531896 protein taxon:284812 20170228 GO_Central

**Comment by marcfeuermann** [comment]
This must have been corrected at the primary annotation level since the term is no more present in any of the PANTHER families mentioned above, nor in Protein2GO.
