### ISSUE TITLE
PTN002858589 extracellular space to FBgn0040074 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2369]
PTN002858589 annotation to extracellular space FBgn0040074 is only supported by itself, FBgn0040074 i.e. is completely circular. No other genes support this.

**Comment by pgaudet** [comment]
This is reported many other places. It's a display issue.

**Comment by hattrill** [comment]
What is the display issue? 
retinin = FBgn0040074
Is retinin supported by more evidence from other genes than just that from itself? If the annotation comes only from itself, it's a data issue. It's a display issue if more genes should be displayed in the with field.
![Screen Shot 2019-05-24 at 08 14 48](https://user-images.githubusercontent.com/11865746/58309409-0de73e80-7dfc-11e9-96f1-6d57aeb7a64e.png)

**Comment by marcfeuermann** [comment]
PAINT propagation has been deleted.
