### ISSUE TITLE
IPR000648 Oxysterol-binding protein

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#237]
IPR000648 Oxysterol-binding protein: add mapping 
"GO: 8142 oxysterol binding"

Thanks
Pascale

Reported by: pgaudet

Original Ticket: "geneontology/annotation-issues/237":https://sourceforge.net/p/geneontology/annotation-issues/237

**Comment by linuxjackto1** [comment]
thanks www.movied.org
