### ISSUE TITLE
GOC-OWL errors - how to remove?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2370]
Hi
There does not seem to be a GitHub section for GOC-OWL, so I am hoping someone will move this issue to the appropriate section if required.

Harold has spotted some odd errors in the MGI files that have the source GOC-OWL. I have looked at these in Protein2GO and these 2 seem very odd. 

Firstly PMID: 26627310, the GOC-OWL annotation is the only one associated with this PMID.  Possibly a group (MGI?) created an annotation, the pipeline ran and created the IC annotation, and then the group deleted the annotation, leaving the IC orphaned. How can we delete this annotation?

Secondly PMID: 18804103, (creation date 23 Aug 2017) the IC annotation 'locomotion' is derived from the annotation semaphorin-plexin signaling pathway involved in axon guidance (see blue bar automatically generated by Protein2GO to show the way these 2 annotations are 'linked'). But 'locomotion' is a parent to the semaphorin-plexin signaling pathway involved in axon guidance term so the creation of the IC is redundant.
In addition, the annotation below to Sema3a using the same GO term, but with 2 AE cell types in separate AE rows rather than 1 cell type (which is what Sema3f has) did not get the GOC-OWL IC annotation. How can we delete this annotation?

Thanks

Ruth
@hdrabkin

**Comment by RLovering** [comment]
![Screenshot 2019-05-23 at 09 20 03](https://user-images.githubusercontent.com/12080010/58238417-247b9000-7d3f-11e9-8547-3cd0f6d062ee.png)
![Screenshot 2019-05-23 at 09 16 29](https://user-images.githubusercontent.com/12080010/58238418-247b9000-7d3f-11e9-8a4d-3f8fb0319a6d.png)

**Comment by hdrabkin** [comment]
Usually an IC is a manual annotation. These are coming in our GOA load, attributed go GOA-OWL. I don't know of any pipeline that would use that (like GOC for the inference annotations). I was hoping someone with access to p2go could go in and get rid of them.

**Comment by pgaudet** [comment]
Neither PMID:18804103 nor PMID:26627310 are in the mgi-prediction file: 
http://release.geneontology.org/2019-05-09/products/annotations/mgi-prediction.gaf


@hdrabkin , is it possible that MGI never wipes them out ? They should be deleted and reloaded with every release. 

Pascale

**Comment by hdrabkin** [comment]
The load drops then reloads.
Again, GOC-OWL
Where is this coming from?
Can you see this in p2GO
Inference annotations get “GOC” ;
We do NOT take inferences from GOA load because we fetch the mgi-predicton.gaf.

I’ll bet you will see GOC-OWL somewhere in p2GO and that’s how it gets into the GOA mouse download?
I’ll delete them now in MGI but I’ll bet they come back over the weekend (I'm going away so will have someone else check on Monday).

H

**Comment by hdrabkin** [comment]
If I see them back, I’ll request a fix on our load end to ignore GOC-OWL (again, not until I get back from my vacation)

I did not think IC annotations were made any other way than manually
In our mgi-inferred file, the inferred annotations have the same evidence code as whatever annotation they were inferred from.
When we make an IC they are strictly manual (curator attribution)

H

**Comment by pgaudet** [comment]
In P2GO the source is GOOI, not GOC-OWL - or is this the same ? I had never seen GOOI before.

**Comment by RLovering** [comment]
yes GOOI is GOC-OWL

I could ask Alex to remove them? at least some have been in Protein2GO since 2017.

Ruth
