### ISSUE TITLE
GO:0044689 maps to deprecated EC

### ISSUE THREAD

**Issue by Artoria2e5** [geneontology/go-annotation#2372]
GO:0044689 currently maps to EC 2.5.1.77, a deprecated entry now split into EC 2.5.1.147 and EC 4.3.1.32, entries representing the two steps of reactions catalyzed by CofG and CofH subunits of the heterodimeric FO synthetase complex [PMID 25781338]. 

There does not seem to be examples of any of these subunits working in the absence of the other in vivo, so a new GO term is not urgently necessary. However, the lack of mappings for the new EC numbers is clearly breaking GO results for proteins annotated using these numbers (e.g. UniProt:P9WP76). It's probably a good idea to add these new EC mappings somehow.

* * *

There should probably be a hunt for all the deprecated EC numbers in the entire set of GO terms some day.

**Comment by pgaudet** [comment]
This is in the wrong tracker. I moved here: https://github.com/geneontology/go-ontology/issues/17408
