### ISSUE TITLE
annotation of non-helicase subunits of chromatin remodeller  to helicase  PANTHER:PTN000233752/ PANTHER:PTN000234048

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2374]
There are a few of these

	arp5	Ino80 complex actin-like protein Arp5	contributes_to	ATP-dependent 3'-5' DNA helicase activity		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000233752
SGD:S000005004	actin pthr11937	protein		PMID:21873635	20190301

arp10 | dynactin complex actin-like protein Arp10 (predicted) | contributes_to | ATP-dependent 3'-5' DNA helicase activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000233752SGD:S000005004 | actin pthr11937 | protein |   | PMID:21873635 | 20190301

arp8 | Ino80 complex actin-like protein Arp8 | contributes_to | ATP-dependent 3'-5' DNA helicase activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000234048SGD:S000005667 | actin pthr11937 | protein |   | PMID:21873635 | 20190301

I don't think the actin subunit contributes to helicase activity?

**Comment by marcfeuermann** [comment]
There are no (or maybe no more) PAINT annotations with this term in PTHR11937. The only annotations to helicase activity are primary annotations from SGD. 
@srengel , could someone from your group have a look at this ?
Thanks a lot,
Marc.

**Comment by srengel** [comment]
Hi @marcfeuermann i can only find three helicase annotations in this set of 11 yeast proteins in the family PTHR11937.  ARP4, 5, and 8 to GO:0043138 but with 'contributes_to'.  shouldn't contributes_to annotations be ignored for PAINT propagation?

**Comment by marcfeuermann** [comment]
Hi Stacia,
When it makes sens, we propagate "contributes_to" annotations with PAINT. In this case I think Val was right to ask not to make the propagation. If you think the annotation is appropriate for ARP4, 5, and 8, then it's OK for me. As far as PAINT goes this is resolved. 
Thanks for having looked at this.
Best regards,
Marc

**Comment by ValWood** [comment]
I would not annotate Arp4 and 5 to contributes to helicase activity, because I'm not sure there is evidence that they do. This paper, the complex was assayed, and the complex has "helicase activity" which does not necessarily indicate that these subunit are required for the catalytic activity. However, guidelines on this have always been hazy....


For the roles of the arp submodule:
https://www.cell.com/fulltext/S0092-8674%2813%2901010-6
Actin, Arp8, and Arp4 form a structural module with the central helicase SANT-associated (HSA) domain of Ino80 and function in histone or nucleosome interactions (Gerhold et al., 2012, Harata et al., 1999, Saravanan et al., 2012, Schubert et al., 2013, Shen et al., 2003, Szerlong et al., 2008).

**Comment by srengel** [comment]
but the qualifier is contributes_to, not required_for.

**Comment by ValWood** [comment]
Ah OK
I just checked the guidlines.

The contributes to qualifier
Contributes to appears in a GO annotation when a function of a protein complex is facilitated, but not directly carried out by one of its subunits on its own. Annotating individual gene products according to attributes of a complex is especially useful for molecular function annotations in cases where a complex has an activity, but not all of the individual subunits do. (For example, there may be a known catalytic subunit and one or more additional subunits, or the activity may only be present when the complex is assembled.) Molecular function annotations of individual subunits working as complexes in which no individual subunit has the activity must include contributes to in the annotation. The contributes to qualifier should not be used in biological process annotations. All gene products annotated using contributes to must also be annotated to a cellular component term representing the complex that possesses the activity. Note that contributes to is not needed to annotate a catalytic subunit. Furthermore, contributes to may be used for any non-catalytic subunit, whether the subunit is essential for the activity of the complex or not.

I see a sentance has been added
"Furthermore, contributes to may be used for any non-catalytic subunit, whether the subunit is essential for the activity of the complex or not."

This seems to be a recent addition? because it implies that any subunit can now be annotated with contributes_to.

If this is the case there is no point to say:

"Annotating individual gene products according to attributes of a complex is especially useful for molecular function annotations in cases where a complex has an activity, but not all of the individual subunits do. (For example, there may be a known catalytic subunit and one or more additional subunits, or the activity may only be present when the complex is assembled.) Molecular function annotations of individual subunits working as complexes in which no individual subunit has the activity must include contributes to in the annotation. "

If we can use it for any complex subunit regardless?
To me, this makes no sense?
@pgaudet @vanaukenk

**Comment by mah11** [comment]
re

>  Furthermore, contributes to may be used for any non-catalytic subunit, whether the subunit is essential for the activity of the complex or not.

My guess is that this sentence is meant to indicate that a subunit that isn't absolutely essential for, but does make some difference to, a complex's activity can be annotated to the function term using contributes_to. It's up to curator discretion not to annotate a function to a subunit that's just in the complex but appears not to affect the activity at all (I agree it would be stupid and pointless to do so). Perhaps different wording could make it clearer, but I don't think the goal of saying contributes_to isn't restricted to essential subunits is inherently bad.

IOW, there's middle ground between "only annotate essential subunits" and "annotate all subunits regardless".

**Comment by pgaudet** [comment]
I think the guidelines need to be re-written. From discussion with @thomaspd and @vanaukenk , I think what we'd like is to annotate 'emerging' functions - ie those that cannot be accomplished by any one subunit, such as RNA polymerase, with contributes_to. 

For protein complexes with a catalytic subunit and accessory subunits, I think we were proposing to only annotate the catalytic subunit. 

@vanaukenk is this right ? 
What do people think about this suggestion ? 

Perhaps we should discuss this at an annotation call and change the guidelines. 

Thanks, Pascale

**Comment by ValWood** [comment]
> I think what we'd like is to annotate 'emerging' functions - ie those that cannot be accomplished by any one subunit, such as RNA polymerase, with contributes_to.

I *love* this suggestion, because it is what we do already. This makes total sense to me...

**Comment by sjm41** [comment]
Contributes_to guidelines have now been clarified and match the last 2 comments in this post (from Aug 2019).
Can we now remove "3'-5' DNA helicase activity(CONTRIBUTES_TO)" from PTN000234048 and PTN000233752 please?

**Comment by marcfeuermann** [comment]
Done.

**Comment by sjm41** [comment]
Thanks Marc!
