### ISSUE TITLE
symbiont/pathogen effector activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2376]
The decision is to create this term, since it will be a useful grouping term to link together heterogeneous activities and there is a precedent for other activities  (toxin, antioxidant, etc)

See 
https://github.com/geneontology/go-ontology/issues/17243#issuecomment-497749459

@CuzickA -  I think you and  Kim H_K worked on a definition for such a term a while back? Could you supply here as a starting point.

Also we need to identify existing pathogen effector functions to add as desecndents.
We can make a list on Monday....

CC @mgiglio99  @pgaudet

**Comment by pgaudet** [comment]
Moved to right tracker.
