### ISSUE TITLE
use of qualifier with BP annotations

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2377]
Hi All

I have taken notes on the qualifier issue in GOC meetings but I am concerned I may have missed something and it would be very helpful to have clarification. Hopefully you can just point me to a guidelines doc rather than answer these queries.

In Protein2GO we have the following qualifier options for BP annotations (ignoring the NOT options):
involved_in
acts_upstream_of
acts_upstream_of_positive_effect
acts_upstream_of_negative_effect
acts_upstream_of_or_within
acts_upstream_of_or_within_positive_effect
acts_upstream_of_or_within_negative_effect

please clarify:
1. if we use the acts_upstream_of qualifier this annotation will be included in the GPAD/GAF files and therefore available for enrichments.
2. Is the idea that 'involved_in' is only used with BP terms if the BP is the first process the gp is involved in. eg for insulin: use involved_in insulin signaling pathway; use acts_upstream_of for regulation of transcription, use acts_upstream_of for regulation of glucose transport?
3. So if using the AE field we would create:
insulin: involved_in insulin signaling pathway AE causually_upstream_of regulation of transcription
Then based on the AE information the GOC pipeline would also create the annotation
insulin: acts_upstream_of regulation of transcription
4. Why do we have the qualifiers:
acts_upstream_of_positive_effect
acts_upstream_of_negative_effect
acts_upstream_of_or_within_positive_effect
acts_upstream_of_or_within_negative_effect
Are we supposed to use them with the regulation terms-please say no!
Hopefully we are not going to be using these.

Thanks

Ruth

@pgaudet @vanaukenk

**Comment by ValWood** [comment]
Great questions Ruth! I'm still confused by this, it isn't clear to me. Even the fundamentals of how to call "upstream of" are unclear to me.  

Form the above  selection, it appears that "upstream direct regulation" will be "upstream of". This means that the "further upstream of" direct regulation annotations that are only "affecting" a process we are not possible to distinguish from regulation. This puts us right back at square one.....

**Comment by RLovering** [comment]
I guess another point: is acts_upstream_of in the qualifier field equivalent to 'causally_upstream_of' in the AE field? If so can we use the same name?

**Comment by vanaukenk** [comment]
@ValWood and @RLovering 
Good points.  @pgaudet and I are planning to work more on the documentation for the relations with specific examples of 'upstream' vs 'regulation'.

@RLovering  -  since we need to describe relations between gene products (material entities) and GO processes as well as between GO processes, we need to have two different relations.

**Comment by ValWood** [comment]
But here we aren't talking about relations between GO processes in either case are we? 
Or are we  and I am really confused?

**Comment by vanaukenk** [comment]
In AEs we would be talking about relations between GO processes.

**Comment by ValWood** [comment]
ah OK.  but not for substrates right?

**Comment by RLovering** [comment]
Is a GOC pipeline that if we create something like
Gene Product involved_in 'insulin signaling' AE causally upstream of 'regulation of glucose transport'
Then the GOC pipeline automatically creates the annotation
Gene product acts_upstream_of 'regulation of glucose transport'

Or does the GOC pipeline only do this for MF as part_of BP
eg: 
Gene Product enables kinase activity AE part_of 'insulin signaling'
GOC pipeline automatically creates the annotation
Gene product involved in 'insulin signaling'

So the reason you are saying it is good to have different relation term in the AE v Qualifier is because the relations are between GO terms v GP to GO term. And that having the same relation term will be confusing.

If this is the case then we have a problem with 'part_of'. 

I am still not convinced that there is a problem of using the same relation for GP to GO term qualifier, and the GO term to GO term relation for the AE field. in a way by stating 
Gene Product involved_in 'insulin signaling' AE causally upstream of 'regulation of glucose transport' you are stating
Gene product acts_upstream_of 'regulation of glucose transport'

I guess the main point is to make it clear how the AE relations will be mapped by GOC pipelines to simple GO annotations

Thanks

Ruth

**Comment by ValWood** [comment]
I'm also unclear why different relationship types are required if the meaning is the same. Part_of is a good example, that is used in both.
Perhaps it will be clearer if we can see how the  relations differ in meaning?

**Comment by hattrill** [comment]
I'll just chime in here with some of my concerns :) 
What I would really like and I think what we really need to d,o before we all start pumping out GPADs, is a good discussion on how we implement these in the first instance - for example are there certain processes that we simply cannot use 'involved in" with? For multicellular organisms this is a particular problem - where do we draw the line wrt things like differentiation or organogenesis - should we only allow "causally upstream of...." for  such broad processes and leave "involved in" for the more tangible small processes such as pathways, etc that make up these broader processes?
I am also worried about the consistency of use:
upstream could mean anything from the process directly upstream to one that is separated by many, many events. As we take in annotations from other sources, it will get  complicated if we have divergence in use - for us and the users.

**Comment by ValWood** [comment]
similar concerns noted in
https://github.com/geneontology/noctua-models/issues/50

**Comment by RLovering** [comment]
Please see http://noctua.berkeleybop.org/editor/graph/gomodel:5a7e68a100000427 where the noctua model uses causally upstream of for an edge but the output shows acts_upstream of see http://noctua.berkeleybop.org/workbench/annpreview/?model_id=gomodel:5a7e68a100000427&barista_token=
