### ISSUE TITLE
PANTHER:PTN000156123 Serpins without activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2378]
These do not have serpin activity and are annotated accordingly:
serine-type endopeptidase inhibitor activity ; GO:0004867 | NOT inferred from key residues

FBgn0053121 | Serpin 28Db | Spn28Db
FBgn0032178 | Serpin 31A | Spn31A
FBgn0024293 | Serpin 43Ab | Spn43Ab
FBgn0044011 | Serpin 43Ad | Spn43Ad
FBgn0033574 | Serpin 47C | Spn47C
FBgn0034195 | Serpin 53F | Spn53F
FBgn0052203 | Serpin 75F | Spn75F
FBgn0015586 | Accessory gland protein 76A | Acp76A
FBgn0036969 | Serpin 77Bb | Spn77Bb
FBgn0036970 | Serpin 77Bc | Spn77Bc
FBgn0037772 | Serpin 85F | Spn85F
FBgn0039795 | Serpin 100A | Spn100A
FBgn0263109 |   | CG43366 

This was also an issue that was fixed a long while back. #1238

**Comment by pgaudet** [comment]
Looks like the problem is caused by PAINT ignoring IKR annotations. I opened a ticket  in the PAINT tracker.

**Comment by hattrill** [comment]
Thanks!

**Comment by pgaudet** [comment]
@hattrill I just discussed this with @huaiyumi and @thomaspd 
One thing I have been wondering is that IKR is a child of 'phylogenetic evidence', but in this case, do you consider your annotation derived from a phylogenetic method ?

I think @sylvainpoux has also used IKR for experimentals. 

One possibility is to create new ECO terms to represent those different types of analyses; what do you think ? (I am asking because this solution would change how we handle this in PAINT; right now the assumption is that only PAINT is using IKR). 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,
I don't remember having used the IKR evidence code (maybe some old annotation). We rarely use such codes and try to limit to IDA, IMP or IPI codes
Thanks,
Sylvain

**Comment by hattrill** [comment]
IKR was traditionally to be used with a NOT where there is sequence info indicating that it diverges from an activity expected of its family e.g. pseudokinases. 

When it was mapped to ECO it went under "phylogenetic evidence". Looking at the definition, this would fit with divergence from the phylogentically conserved motif, so it is correctly used i.e. from analysis of gene families.

The point is, that if you see a NOT and an IKR, someone has already looked at the sequence and determined that it is probably inactive and transferring positive annotations to this via IBA should be blocked. (BTW: The person who did this analysis on the serpins showed that these are probably recent events, so it would not be a good idea to propagate these NOTs and years back, he was very insistent that we got this right.)

If we see a conflict between an experimental and an IKR, we remove the IKR (as, for example, not all predicted pseudokinases are actually pseudokinases).

**Comment by hattrill** [comment]
The fix https://github.com/pantherdb/fullgo_paint_update/issues/39 only seems to apply to exp annotations. Could you apply to all evidence codes (see examples above)? We have many sequence-based NOTs.

**Comment by hattrill** [comment]
This is still an issue - can you block this or get PAINT to include non-exp evidence for blocking propagation

**Comment by marcfeuermann** [comment]
Huge and very complex family. Updated.

**Comment by hattrill** [comment]
Thanks, @marcfeuermann. The problem with this family is that there is no good way to predict which ones drop activity. 

From what I can see, NOT is only seen by PAINT if it is with an EXP evidence code  - I requested it for IKR, but I can't see that it was acted on. In fact, NOT should be a propagation blocker for all evidence codes, as curators don't use NOT unless there is a very sound reason.

**Comment by pgaudet** [comment]
> From what I can see, NOT is only seen by PAINT if it is with an EXP evidence code - I requested it for IKR, but I can't see that it was acted on. In fact, NOT should be a propagation blocker for all evidence codes, as curators don't use NOT unless there is a very sound reason.

What do you mean? If PAINT curators use IKR, that will generate a 'real' NOT that you see in annotations. IRD does not produce any annotations. 

On the other hand, if FlyBase has IRK annotations, we should see then as NOT in PAINT, and positive annotations should not be propagated.

Is this what you meant ?

**Comment by hattrill** [comment]
"On the other hand, if FlyBase has IRK annotations, we should see then as NOT in PAINT, and positive annotations should not be propagated."

Yes. Then that should be ok.

**Comment by thomaspd** [comment]
Yes, I also thought we'd agreed to treat manual IKR 'NOT' annotations the same way we treat EXP 'NOT' annotations in PAINT, i.e. they can be used as evidence for inferred IBD annotations, or as automatic stops on propagation of positive annotations. If we haven't done that yet, we should prioritize it.
