### ISSUE TITLE
Methylthiotransferase, N-terminal domain superfamily (IPR038135) without Mol.fun

### ISSUE THREAD

**Issue by gphanivijay** [geneontology/go-annotation#2379]
From the IPR038135 description the GO mol. fun term GO:0035596 seems appropriate. Can you please add this.

**Comment by happy-lorna** [comment]
Hi @gphanivijay 
When it comes to assigning GO terms in InterPro we have to focus on accuracy over coverage as the GO terms are applied to all proteins matching our member database models. As such, we typically do not assign GO terms to Homologous Superfamily models as these match very large diverse groups of proteins which will often represent a variety of different functions. 
However, the proteins matched by IPR038135 are also matched by IPR013848 (a type Domain entry). I have added GO:0035596 to this domain entry. This change will be visible in our next release.
Lorna.

**Comment by gphanivijay** [comment]
Got it. Thanks a lot for the prompt reply.
