### ISSUE TITLE
PTN000150874  ADENOSINE DEAMINASE (PTHR11409) Not growth factor

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2380]
I've removed "growth factor activity" from FBgn0043025 as this is indirect (adenosine inhibits cell proliferation, and FBgn0043025 converts it to inosine).
Could you remove "growth factor activity" from PTN000150874, as this was the only annotation supporting this.

**Comment by marcfeuermann** [comment]
Done !
