### ISSUE TITLE
PTN002335023 transmembrane signaling receptor activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2381]
PTN002335023 transmembrane signaling receptor activity

The lectin-28C FBgn0040099 looks like a secreted protein. 

This is only based on one annotation = MOUSE|MGI=MGI=97142|UniProtKB=Q61830, so probably safer to remove this as many classes of C-type lectins are secreted and some are TM and some are TM then cleaved.

**Comment by marcfeuermann** [comment]
This annotation is indeed weird since most of the proteins of family PTHR22803 are localized outside of the cell (secreted). I've removed the propagation of this term.
