### ISSUE TITLE
IPR001320 ionotropic glutamate receptor activity 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2383]
IPR001320 is associated with ionotropic glutamate receptor activity 
but this domain is also found in a large class of non-glutamate binding ionotropic Receptors in Drosophila and they probably diverge in other species.
Could you go up the tree to 'ligand-gated ion channel activity' GO:0015276?

**Comment by happy-lorna** [comment]
I have updated this as you suggest. 
Thanks!
Lorna.
