### ISSUE TITLE
PANTHER:PTN000583675, etc. 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2384]
Could you block annotations from PANTHER:PTN000583675 to D.mel FBgn0011300 babo and FBgn0003317 sax as these are activin and BMP pathway specific receptors.

and from PANTHER:PTN001147434 to babo

and PANTHER:PTN002356032 to sax

Thanks

**Comment by marcfeuermann** [comment]
PTHR23255 contains a huge amount of primary annotations leading to some confusion and was probably over-painted. I've deleted all and re-painted the family in a more restrictive manner.  FBgn0011300 babo and FBgn0003317 sax have now their specific functions.

**Comment by hattrill** [comment]
Cheers! The different TNF-related pathways make it all a bit tricky!
