### ISSUE TITLE
IPR031424 Protein quiver

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2391]
The GO terms associated with the quiver family do not seem accurate:
GO:1903818 positive regulation of voltage-gated potassium channel activity
GO:0032222 regulation of synaptic transmission, cholinergic
GO:0030431 sleep 
GO:0034235 GPI anchor binding 

GO:0034235 GPI anchor binding - it has a gpi anchor rather than binds one

Some quiver family members have been shown to be involved in modulate the trafficking of membrane proteins. Think that the sleep and channel regulation/synaptic transmission processes are more limited towards the quiver protein rather than quiver family proteins.

**Comment by happy-lorna** [comment]
I agree that the GPI anchor binding annotation was wrong, I have removed this - thanks for highlighting it for us.
However, the other 3 terms seem fine (based on PMID:24613312 and PMID:18635795) given that the InterPro entry really only hits quiver protein.

**Comment by hattrill** [comment]
It's hitting 3 other genes in D.mel besides quiver:
FBgn0261277 retroactive (rtv) - which is chitin organising protein
FBgn0032421 crooked (crok) - septate junction component transport
FBgn0033872 CG6329 - ?

The Pfam quiver protein designation seems problematic - hitting members of the ly6 family. 
The ones listed above don't get picked up as quiver paralogs in our integrated tool.

**Comment by happy-lorna** [comment]
Hi Helen,
I was having another look at this, but as far as I can see everything that this entry matches from D.mel is designated as quiver by UniProt. 
(A0A0B4LEU0, B4F5Y8, B4F5Z0, B4F5Z3, B4F5Z5, B4F5Z6, B5A5T4, M9PJI2, Q7K188, Q9VKA0, Q9VZ21)

**Comment by hattrill** [comment]
Oh....I see what you mean....

Entry | Protein names | Gene names (UniProtKB) | FBgn | FlyBase Name
-- | -- | -- | -- | --
B5A5T4 | Protein quiver (Protein sleepless) | qvr sss CG33472 | FBgn0260499 | quiver
M9PJI2 | Protein quiver (Protein sleepless) | rtv 1 Dmel\CG1397 l(1)10Ag l(1)G13 l(1)L1 L1 Rtv CG1397 Dmel_CG1397 | FBgn0261277 | retroactive
Q9VZ21 | Protein quiver (Protein sleepless) | rtv 1 Dmel\CG1397 l(1)10Ag l(1)G13 l(1)L1 L1 Rtv CG1397 Dmel_CG1397 | FBgn0261277 | retroactive
Q9VKA0 | Protein quiver (Protein sleepless) | crok BcDNA:RE65321 CG17218-RA Dmel\CG17218 CG17218 Dmel_CG17218 | FBgn0032421 | crooked
A0A0B4LEU0 | Protein quiver (Protein sleepless) | qvr anon-WO02059370.1 BcDNA:GH06755 CG30032 Dmel\CG33472 mdcds_22455 sss   CG33472 Dmel_CG33472 | FBgn0260499 | quiver
B4F5Z5 | Protein quiver (Protein sleepless) | CG1397 | FBgn0261277 | retroactive
B4F5Z3 | Protein quiver (Protein sleepless) | CG1397 | FBgn0261277 | retroactive
Q7K188 | Protein quiver (Protein sleepless) | Dmel\CG6329 CG6329 Dmel_CG6329 | FBgn0033872 | Unnamed gene (CG6329)
B4F5Y8 | Protein quiver (Protein sleepless) | CG1397 | FBgn0261277 | retroactive
B4F5Z0 | Protein quiver (Protein sleepless) | CG1397 | FBgn0261277 | retroactive
B4F5Z6 | Protein quiver (Protein sleepless) | CG1397 | FBgn0261277 | retroactive

.....that's not good. I will have a dig and get on to UniProt!

**Comment by Kawatebi** [comment]
Hello, It looks like this protein name was incorrectly propagated to some unreviewed entries based upon a rule from our automatic annotation pipeline UniRule. Alistair, one of our AA curators is currently looking into this and will either delete or modify the rule so that it only apples to the Quiver protein and it's orthologues in other Drosophila species. Kate from UniProt

**Comment by pgaudet** [comment]
Hi @Kawatebi 

Any update on this one?

**Comment by Kawatebi** [comment]
Hi @pgaudet 

Alistair has now retired so I'll pass this on to our new AA curator Pedro Raposo and ask if he can look into it.

**Comment by ValWood** [comment]
Any update @PedroRaposo @esperetta  can this close??

**Comment by PedroRaposo** [comment]
Hello,
Removed from GO:0034235 (GPI anchor binding) from UR001628775, as suggested before.
Regarding FBgn0261277 (Q9VZ21), FBgn0032421 (Q9VKA0) and FBgn0033872 (Q7K188), these are all TrEMBL entries, which means its annotations can be changed in 2 ways:

1. By changing the rules it touches (in this case UR001628775), and we base the rules on what we see in Swiss-Prot
2. Ask a curator to review FBgn0261277, FBgn0032421 and FBgn0033872, turning them into Swiss-Prot, so then UR001628775 would be changed accordingly.

Looking to the 12 Swiss-Prot we have at the moment, they seem very similar, and I can confirm they have the same InterPro integrated signatures. FBgn0261277, FBgn0032421 and FBgn0033872 have the same length as the 12 Swiss-Prot and some of them belong to the same genus. Putting everything together, this means that we cannot differentiate between these 12 Swiss-Prot and FBgn0261277, FBgn0032421 and FBgn0033872.

I am going to ask for a curator to curate FBgn0261277, FBgn0032421 and FBgn0033872, if you agree, and add these to Swiss-Prot.
From the UniRule perspective, the only thing we can do is if we have a name that would encompass the 12 Swiss-Prot proteins + FBgn0261277, FBgn0032421 and FBgn0033872. Would "Quiver family u-PAR/Ly-6-like domain protein" fit our needs?
Do you have a better suggestions?

**Comment by hattrill** [comment]
Thanks @PedroRaposo No better suggestion from me.

**Comment by PedroRaposo** [comment]
In UR001628775:

1. I removed GO:0034235 (GPI anchor binding)
2. Changed recommended name from "Protein quiver" to "Quiver family u-PAR/Ly-6-like domain protein". Should I also remove "Protein sleepless" as a secondary name? If so, I'll remove GO:0030431 (sleep), as well. If there's any suggested changes to the rule, please tell me.

Also, I asked curators from UniProt EBI to review FBgn0261277, FBgn0032421 and FBgn0033872.
