### ISSUE TITLE
Review annotations to GO:0072001 renal system development

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#2392]
Following on from a discussion in go-ontology/issues/16143, the proposal has been made to make GO:0072001 'renal system development' a do-not-manually-annotate term. This procedure will ensure that curators will attach their annotations to to terms with more specificity. There are currently 15 annotations with experimental evidence summarized with suggested re-annotation.

https://docs.google.com/spreadsheets/d/1TPDoADiQS3hhMnYt2-XxEa00AsTphTjGIgYw4LMmiEY/edit#gid=0

Group | # of annotations

UniProt | 12
DFLAT | 1
BHF-UCL | 1
ZFIN | 1

**Comment by RLovering** [comment]
UCL annotation revised and new GO term added - thanks Ruth

**Comment by sabrinatoro** [comment]
The ZFIN annotation was created by UniProt (ZFIN got it from GOA), and therefore I cannot update it. 
@ukemi

**Comment by sabrinatoro** [comment]
ZFIN annotation was revised and deleted. Thanks

**Comment by pgaudet** [comment]
Remaining annotations are disputed in P2GO. 
@milarolo if you want to you update the spreadsheet (I did for the ones closed this morning). 
Thanks, Pascale

**Comment by pgarmiri** [comment]
SWIE annotations havw been reviewed and either removed or changed to the suggested one. Changes reported in the spreadsheet. Thanks
