### ISSUE TITLE
MSH4 AND MSH5 PAINT and IEA annotations incorrect

### ISSUE THREAD

**Issue by robnash** [geneontology/go-annotation#2393]
Hi,

The process and component annotations for _S. cerevisiae_ MSH4 (P40965) and MSH5 (Q12175) to mismatch repair (GO:0006298) and mismatch repair complex (GO:0032300) are incorrect. These two proteins form a complex called the MutSgamma complex (GO:0062128; see PMID:9374523), and both proteins are involved in reciprocal meiotic recombination (GO:0007131) but NOT mismatch repair. For details on the processes for MSH4 see for example PMID: 8001134 and PMID: 9374523, and for MSH5 see PMID: 7622037 and PMID: 9374523.

Cheeers,
Rob

**Comment by ValWood** [comment]
@happy-lorna   are you covering InterPRo now @asangrador  has left?

**Comment by happy-lorna** [comment]
This one is going to take a bit of time for us to sort out at InterPro as both proteins hit multiple "mismatch repair" entries. We have a plan but it wont make it into the next release as we need to freeze curation today. I will come back to it however!

**Comment by marcfeuermann** [comment]
At the PAINT level, I've blocked all mismatch repair-related terms for MSH4 and MSH5 nodes in PTHR11361. Meiotic recombination terms were kept. The annotation to the MutSgamma complex is too recent to be present in the PAINT matrix, but will be propagated when available.

**Comment by pgaudet** [comment]
Done for PAINT. Removing the label.

**Comment by happy-lorna** [comment]
Apologies, I didn't get round to looking at this again the last curation cycle. Am now tagging @typhainepl  so it actually gets picked up after this freeze!

**Comment by typhainepl** [comment]
The two protein accessions have been added to the GO blacklist.
