### ISSUE TITLE
Matrix project  amino acid metabolism/DNA recombination

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2394]
This annotation from an older paper seems to have been added in since the last round. Any idea why it was added later (it seems to be a phenotype?)
 

IRC7 | Beta-lyase involved in the production of thiols |   | replication-born double-strand break repair via sister chromatid exchange |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr43500 | gene |   | PMID:23357952 | 20170109

**Comment by srengel** [comment]
hi Val, i have removed the annotation.  thanks for the heads up.
