### ISSUE TITLE
Matrix project : amino acid metabolism/ DNA replication

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2395]
Is seems that for MET30  is regulation for  amino acid metabolism and DNA replication

The replication annotation was fixed to "regulation" at some point, but the direct annotation to "DNA replication initiation" from the same paper still exists

- [x] MET30 | F-box protein containing five copies of the WD40 motif |   | DNA replication initiation |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | wd40 repeat protein pthr22847 | gene |   | PMID:15870262 | 20131010

- [x]   | MET30 | F-box protein containing five copies of the WD40 motif |   | regulation of DNA-dependent DNA replication initiation |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | wd40 repeat protein pthr22847 | gene |   | PMID:15870262 | 20070815

(note to self, deal with keyword mappings)

**Comment by ValWood** [comment]
MCM1 is a transcription factor. 
This is a very old paper. I remember following up on this with a couple of replication experts and it isn't supported other than by this paper (nobody believes it). Do you thik this annotation should stay?


MCM1 | Transcription factor |   | DNA replication initiation |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | mads box protein pthr11945 | gene |   | PMID:12473677 | 20100421

These 2 annotations (MET30 and MCM1) are the only  annotation outliers in this intersection (except for the IEAs derived from them)

**Comment by srengel** [comment]
i have deleted the MCM1 annotation just now.

**Comment by srengel** [comment]
i deleted also the 2 MET30 annotations just now.

**Comment by ValWood** [comment]
Thanks!
