### ISSUE TITLE
Matrix project : PAINT annotation  - pantoate-beta-alanine ligase activity pthr21299

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2397]
pombe pan6
pantoate-beta-alanine ligase activity (GO:0004592)

has been painted to

pan6 | pantoate-beta-alanine ligase |   | pantothenate biosynthetic process from valine |   | GO_Central | Schizosaccharomyces pombe | IBA | EcoGene:EG11746PANTHER:PTN000480612 | cytidylate kinase/pantoate-beta-alanine ligase pthr21299 | protein |   | PMID:21873635 | 20170228

I haven't come across this before and I'm not sure that it happens in higher Eukaryotes?

@deustp01  do you know anything about this pathway?

**Comment by ValWood** [comment]
The activity I have is
Catalysis of the reaction: ATP + (R)-pantoate + beta-alanine = AMP + diphosphate + (R)-pantothenate. Source: EC:6.3.2.1

**Comment by marcfeuermann** [comment]
From  PMID:11154694 (http://www.jbc.org/content/276/14/10794.long) the biosynthesis pathways of the beta-alanine precursor seem to differ in _S. cerevisae_ and bactera, but the biosynthesis pathways of the pantoate precursor look similar. 
Valine is a a far upstream precursor of pantoate and I propose to replace "pantothenate biosynthetic process from valine" by "pantothenate biosynthetic process".

Another issue with PTHR21299 is the weird location of _S. pombe_ pan6 within the Prokaryotic node.  @huaiyumi could someone have a look at this ? Thank you.

**Comment by marcfeuermann** [comment]
The horizontal transfer to S.pombe seems to be real and is not a mistake in the PANTHRE tree. I've only kept the the  "pantothenate biosynthetic process" for PAINT propagation.
