### ISSUE TITLE
Matrix: CLN3  (amino acid metabolism/ cytoskeleton organization 1)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2398]
CLN3  has a number of annotations to various metabolism but is a transmembrane transporter (not metboliizing)

MGI

- [x]  Cln3 | ceroid lipofuscinosis, neuronal 3, juvenile (Batten, Spielmeyer-Vogt disease) |   | cellular amino acid metabolic process |   | MGI | Mus musculus | IMP | MGI:MGI:1933976 | battenin pthr10981 | protein |   | MGI:MGI:3616748PMID:12763292 | 20060913

Clin Chim Acta. 2003 Jun;332(1-2):145-8.
Altered amino acid levels in sera of a mouse model for juvenile neuronal ceroid lipofuscinoses.

Altered amino acid levels shouldn't be used to make "metabolism" annotations

**Comment by ValWood** [comment]
Out of data unsupported annotations on CLN3 (human)

All of these look incorrect:

-- | -- | -- | -- | -- | -- | -- | -- | -- | -- |-- | -- | -- | --
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- |-- | -- | -- | --
 UniProtKB:Q13286 | CLN3 | involved_in | GO:0016236    macroautophagy | ECO:0000303   NAS | PMID:9949212 |   | 9606 Homo sapiens | UniProt

**Comment by ValWood** [comment]
- [ ]  This  paper is about 
UniProtKB:Q13286 | CLN3 | involved_in | GO:0006684    sphingomyelin metabolic process | ECO:0000315   IMP | PMID:15240864 |   | 9606 Homo sapiens | UniProt
-- | -- | -- | -- | -- | -- | -- | -- | --

This paper isn't about sphingomyelin metabolic process

McNamara JO 2nd , 0000-0003-4091-618X
--
Vandongen A , 0000-0002-9923-3407 , University of Leiden

**Comment by ukemi** [comment]
@hdrabkin parses out the MGI annotation tickets.

**Comment by ukemi** [comment]
This was probably made when there was debate about whether transport was part of metabolism. I will change to homeostasis.

**Comment by ValWood** [comment]
Do you think amino acid level in a mutant is enough for homeostasis?

**Comment by ValWood** [comment]
Not all transport is homeostasis (as one of our community  working on zinc homeostasis only ascribes a subset of this transport system to homeostasis). I don't think you can get "homeostasis from a transport mutant becase it's an artificial perturbation?

**Comment by ValWood** [comment]
In this paper, although multiple transporters were studied
https://www.pombase.org/reference/PMID:29529046
only some are involved in "homostasis" in a normal cell (via an assay)
Some will transport but don't  keep the zinc levels on an even keel.

**Comment by ukemi** [comment]
OK. Deleted.

**Comment by ValWood** [comment]
The disputed ones were Rachels, so maybe we can delete those @pgaudet  if you agree?

**Comment by ValWood** [comment]
The human ones  disputed in Protein2GO are done
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8717)
 Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8716)
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8715)
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8714)
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8713)

**Comment by ValWood** [comment]
I tried to delete the PinC ones but I can't so I raised disputes for thse too

**Comment by ValWood** [comment]
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8717)

**Comment by ValWood** [comment]
resolved
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8755)
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8754)
Comment added to annotation dispute concerning protein Q13286 (Dispute ID: 8753)
