### ISSUE TITLE
Matrix: FB:FBgn0286784 (amino acid metabolism/ cytoskeleton organization 2)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2399]
http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0286784

Hi @hattrill 
these seem odd?

The only mention of TER94 I could find was here:
However, expression of a dominant-negative form of valosin-containing protein (VCP; TER94) (Rumpf et al., 2011), which interferes with proteasomal degradation (Meyer et al., 2012; Rumpf et al., 2011, 2014; Wójcik et al., 2006), could stabilize Asn-GFP in SPGs (Fig. S7A,B).

which doesn't seem to generate these annotations?

TER94 |   |   | asparagine catabolic process |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0239793PMID:30002129 | 20180920
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 TER94 |   |   | negative regulation of cell cycle |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0239793PMID:30002129 | 20180920

**Comment by hattrill** [comment]
Yes - does seem a bit odd. I've come across this protein as involved in facilitating protein degradation in the nucleus. I'll have a look, I seem to remember that it has some strange history and was classified as a V-ATPase at some point in the past.

**Comment by ValWood** [comment]
I'm getting another violation from the same publication:

Ntan1 | N-terminal amidohydrolase 1 |   | asparagine catabolic process |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein

This seems to be an aginyltransferase involved in protein arginylation preceding degradation via the N-end rule pathway. Does this one look OK?

**Comment by ValWood** [comment]
Oh its the same annotation causing violations in 2 places!

**Comment by ValWood** [comment]
and

Ate1 | Arginyltransferase 1 |   | asparagine catabolic process |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0239793PMID:30002129 | 20180920

**Comment by hattrill** [comment]
This one is a bit of a dog's dinner!

Looks like Ate1 and Ntan1 are both involved in "ubiquitin-dependent protein catabolic process via the N-end rule pathway" - looks like someone got confused and chose a amino acid metabolism term.
TER94 was a 'red herring', in that they just used it as a tool to do the opposite.

Basic conclusion from paper was: endoreplication/ploidy is enhanced by down by Ntan1 via N-end rule pathway which switches glial cells away from proliferation.

**Comment by hattrill** [comment]
So cell cycle and asparagine catabolic process are both wrong and removed for all three.

**Comment by hattrill** [comment]
I've still got to address the amino acid metabolism/ cytoskeleton organization question - was diverted by the dog's dinner!

**Comment by ValWood** [comment]
OK closing, I got the fixes
