### ISSUE TITLE
Matrix: Auh Amino acid metabolism/ mRNA metabolism 1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2400]
https://www.uniprot.org/uniprot/Q13825
Methylglutaconyl-CoA hydratase, mitochondrial

UniProt description says
Was originally identified as RNA-binding protein that binds in vitro to clustered 5'-AUUUA-3' motifs (PubMed:7892223).

is this thought to be physiologically relevant?
It seems unlikely if this is really in the mitochondria?

Knock-on effect of this is the mouse protein:

http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1338011
called
AU RNA binding protein/enoyl-coenzyme A hydratase
if the human annotation is removed the mouse product probably needs updating?

and the TAS to:
nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay
via
http://amigo.geneontology.org/amigo/reference/PMID:10072761
and the RNA binding annotation?

**Comment by ValWood** [comment]
MAybe this one is OK, there is some connection between the mitochondria and  deadnylation decay. However, I don't think I would make a TAS to the process right now? The only experiemnt shows the binding but there is no process coneection yet as far as I can see, so this could be an artifact?

**Comment by hdrabkin** [comment]
removed.

**Comment by ValWood** [comment]
thanks HArold
