### ISSUE TITLE
Matrix: ATF4 Amino acid metabolism/ mRNA metabolism 3

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2402]
I don't think this annotation should be made from this review, delete?

ATF4 | Cyclic AMP-dependent transcription factor ATF-4 |   | cellular amino acid metabolic process |   | UniProt | Homo sapiens | TAS |   | activating transcription factor atf 4/5 pthr13044 | protein |   | PMID:12689582 | 20050906

**Comment by pgaudet** [comment]
This is an EBI annotation @milarolo

**Comment by milarolo** [comment]
I have deleted the annotation "cellular amino acid metabolic process" (GO:0006520)

**Comment by ValWood** [comment]
thanks!
