### ISSUE TITLE
Matrix: AARS2/CBS2 | amino acid metabolism/ mitochondrial organization 1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2403]
This is a phenotype (of most mitochondrial gene expression and transport mutants): 

- [x] UniProtKB:Q5JTZ9 | AARS2 | involved_in | GO:0033108    mitochondrial respiratory chain complex assembly | ECO:0000315   IMP | PMID:21549344 |   | 9606 Homo sapiens | BHF-UCL

**Comment by ValWood** [comment]
CBS2 | Mitochondrial translational activator of the COB mRNA |   | mitochondrial respiratory chain complex III assembly |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr43765 | gene |   | PMID:3329045 | 20180816

**Comment by srengel** [comment]
i removed the SGD annotation to CBS2 just now.

**Comment by RLovering** [comment]
Hi Val

BHF annotation deleted

Best

Ruth

**Comment by ValWood** [comment]
Thanks. Taking the authors word for it this annotation looks reasonable but it doesn't really add anything to the picture process wise....

@pgaudet  does it make sense why I would not add "acts upstream of " here although it isn't incorrect?

**Comment by ValWood** [comment]
@pgaudet  ignore comment. I thought this was a different ticket. Getting so bogged under!
