### ISSUE TITLE
Matrix: PAINT annotations  methyltransferases to S-adenosylhomocysteine metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2405]
We have  PAINT ammpings of methyltransferases to 
 S-adenosylhomocysteine metabolic process 

but these are n't really involved in  S-adenosylhomocysteine metabolic process, it's jus the donor... (this makes methytransferases slim  to "nucleobase-containing small molecule metabolic process" which seems odd)

rmt2 | N-methyltransferase (predicted) |   | S-adenosylhomocysteine metabolic process |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001282244RGD:2659 | family not named pthr32379 | protein |   | PMID:21873635 | 20170228

  | rmt2 | N-methyltransferase (predicted) |   | S-adenosylmethionine metabolic process |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001282244RGD:2659

**Comment by marcfeuermann** [comment]
Propagation of the over-annotations to these processes have been removed from family PTHR32379.
