### ISSUE TITLE
Matrix: amino acid metabolic process/ protein catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2408]
I don't think this should be 

- [ ] PCYOX1 | Prenylcysteine oxidase 1 |   | prenylcysteine metabolic process |   | UniProt | Homo sapiens | NAS |   | family not named pthr15944 | protein |   | PMID:9287348 | 20011009

the  correct annotation is 

PCYOX1 | Prenylcysteine oxidase 1 |   | prenylated protein catabolic process |   | BHF-UCL | Homo sapiens | IDA |   | family not named pthr15944 | protein |   | PMID:10585463 | 20090403

it's acting on the protein not the amino acid
![protein](https://user-images.githubusercontent.com/7359272/59722376-6c48e680-921b-11e9-816d-b8eb366c156b.jpg)

**Comment by ValWood** [comment]
Also PAINT annotations

PCYOX1 | Prenylcysteine oxidase 1 |   | prenylcysteine catabolic process |   | GO_Central | Homo sapiens | IBA | MGI:MGI:1914131PANTHER:PTN000409219 | family not named pthr15944 | protein |   | PMID:21873635 | 20170228
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | PCYOX1 | Prenylcysteine oxidase 1 |   | prenylated protein catabolic process |   | GO_Central | Homo sapiens | IBA | PANTHER:PTN000409219TAIR:locus:2163966UniProtKB:Q9UHG3 | family not named pthr15944 | protein |   | PMID:21873635 | 20170228

**Comment by marcfeuermann** [comment]
In PMID:9287348, the authors used prenylated cysteins to determine the catalytic activity of the enzyme. Moreover, in the latest version of pthr15944, "prenylcysteine catabolic process" comes from an IMP Mouse annotation by MGI based on PMID:12151402 showing that : "prenylcysteine lyase deficiency in mice results in the accumulation of farnesylcysteine and geranylgeranylcysteine in brain and liver". 
This is why I'm not sure what to do with the primary GO annotations, as they do not seem wrong in the context of the articles (keep them or delete them ?).
Anyway, for PAINT propagation I've only kept the propagation of the process at the protein level.

**Comment by ValWood** [comment]
Hmm, I guess keep the original annotations for now until it is clearer if this is physiologically relevent or just some unwanted metabolic byproduct accumulation.

The rule of thumb is to remove things if they are  not considered to be physiologically relevant

**Comment by marcfeuermann** [comment]
Yes, I agree that we should restrict annotation to physiologically relevant stuff. Anyway, sometimes we do not have enough information to decide whether it is physiological or not. If we think it is not relevant, we should also obsolete the corresponding GO terms. Anyway, this kind of stuff will not be painted anymore..

**Comment by ValWood** [comment]
reopening for 

- [ ] PCYOX1 | Prenylcysteine oxidase 1 |   | prenylcysteine metabolic process |   | UniProt | Homo sapiens | NAS |   | family not named pthr15944 | protein |   | PMID:9287348 | 20011009

**Comment by pgaudet** [comment]
Disputed in P2GO.

**Comment by pgaudet** [comment]
Fixed in P2GO.
