### ISSUE TITLE
Matrix: Amino acid metabolism/peroxisome biogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2409]
@deustp01 
- [ ] This is targetted to the peroxisome rather than  involved in targeting to the peroxisome
UniProtKB:P21549 | AGXT | involved_in | GO:0006625    protein targeting to peroxisome | ECO:0000304 TAS | Reactome:R-HSA-9033241 |   | 9606 Homo sapiens | Reactome

@sabrinatoro 
- [x] Annotation also used in Zfin ISS annotation
agxtb | alanine--glyoxylate and serine--pyruvate aminotransferase b |   | protein targeting to peroxisome |   | ZFIN | Danio rerio | ISS | UniProtKB:P21549 | aminotransferase class v pthr21152 | protein |   | ZFIN:ZDB-PUB-040216-1 | 20071010

**Comment by sabrinatoro** [comment]
ZFIN annotation has been changed.

**Comment by ValWood** [comment]
Will this be fixed by
https://github.com/geneontology/go-annotation/issues/2425
?

If so I 'll close this one too

**Comment by deustp01** [comment]
It should be, yes.

**Comment by ValWood** [comment]
Yes it lists AGXT so closing...
