### ISSUE TITLE
Matrix: Gfpt1  amino acid metabolism/glycosylation (1)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2410]
UDP-N-acetylglucosamine metabolic process

This doesn't seem right here:

Gfpt1 | glutamine fructose-6-phosphate transaminase 1 |   | fructose 6-phosphate metabolic process |   | RGD | Rattus norvegicus | IDA |   | glucosamine--fructose-6-phosphate aminotransferase, isomerizing pthr10937 | gene |   | PMID:10898949RGD:1625426 | 20070613

(it's  glutamine-fructose-6-phosphate transaminase (isomerizing) activity)

**Comment by ValWood** [comment]
also PAINTED
Gfpt2 | glutamine-fructose-6-phosphate transaminase 2 |   | fructose 6-phosphate metabolic process |   | GO_Central | Rattus norvegicus | IBA | PANTHER:PTN000101302RGD:1549703 | glucosamine--fructose-6-phosphate aminotransferase, isomerizing pthr10937 | gene |   | PMID:21873635
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
actually this one may be OK, will check tomorrow

**Comment by gthayman** [comment]
UDP-GlcNac inhibits the activity of Gfpt1, so I would think that would qualify as involvement in the hexosamine biosynthetic pathway - I should add that to our diagram.

**Comment by ValWood** [comment]
yep this one is fine,  I see its an early step.  and  glutamine  is the input will add an exception
