### ISSUE TITLE
Matrix: amino acid biosynthesis/histidine regulation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2411]
Should PHO2 be 
"regulation of histidine biosynthesis"?

PHO2 | Homeobox transcription factor |   | histidine biosynthetic process |   | SGD | Saccharomyces cerevisiae S288C | IMP |   |   | gene |   | PMID:3303332 | 20100125

  | PHO2 | Homeobox transcription factor |   | histidine biosynthetic process |   | SGD | Saccharomyces cerevisiae S288C | IGI | SGD:S000000735 |   | gene |   | PMID:3303332 | 20100125

  | PHO2 | Homeobox transcription factor |   | histidine biosynthetic process |   | SGD | Saccharomyces cerevisiae S288C | IGI | SGD:S000001807 |   | gene |   | PMID:3303332 | 20100125

**Comment by ValWood** [comment]
also


PHO2 | Homeobox transcription factor |   | purine nucleobase biosynthetic process |   | SGD | Saccharomyces cerevisiae S288C | IDA |   |   | gene |   | PMID:1495962 | 20011106
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by srengel** [comment]
there are no 'regulation of' terms for histidine biosynthesis

**Comment by srengel** [comment]
fixed the purine one to regulation.  requested regulation terms for the histidine biosynthesis.  https://github.com/geneontology/go-ontology/issues/17537

**Comment by srengel** [comment]
have updated the histidine biosynthesis annotations to 'regulation of' now that the new terms are available.  closing.
