### ISSUE TITLE
Matrix: EC assignment histone acetyltransferase (amino acid metabolism/chromatin remodelling 5)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2412]
HPA3
physiological role D-Amino acid N-acetyltransferase that detoxifies D-amino acids

Although it is named after  histone,  this doesn't appear to be the physiological substrate otherwise it would . be annotated as a histone acetyl transferase at SGD )

HPA3 | D-Amino acid N-acetyltransferase that detoxifies D-amino acids |   | histone acetylation |   | GOC | Saccharomyces cerevisiae S288C | IEA | GO:0004402 | diamine n-acetyltransferase pthr10545 | gene |   | GO_REF:0000108 | 20190601

 this is an F-P inference from

HPA3 | D-Amino acid N-acetyltransferase that detoxifies D-amino acids |   | histone acetyltransferase activity |   | UniProt | Saccharomyces cerevisiae S288C | IEA | EC:2.3.1.48 | diamine n-acetyltransferase pthr10545 | gene |   | GO_REF:0000003 | 20190601

http://amigo.geneontology.org/amigo/reference/PMID:16362288
So I guess the EC mapping needs to be removed?

**Comment by Antonialock** [comment]
removing the EC mapping to this one.
