### ISSUE TITLE
Matrix: amino acid metabolism/chromatin remodelling 1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2413]
I don't fully understand whet this particular Sirtuin is, but it's clearly non-canonical. Seems to be mitochondrial

Suggest delete unsupported:

SIRT4 | NAD-dependent protein lipoamidase sirtuin-4, mitochondrial |   | chromatin silencing |   | PINC | Homo sapiens | TAS |   | family not named pthr43688 | protein |   | PMID:10381378 | 20030904

**Comment by pgaudet** [comment]
Done
