### ISSUE TITLE
Matrix: amino acid metabolism & translation/meiosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2418]
These seem indirect  (useful for phenotypes?), because, GatA will be required for *everything*?

GatA | Glutamyl-tRNA amidotransferase, subunit A |   | oogenesis |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0162144PMID:12930750 | 20060803
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | GatA | Glutamyl-tRNA amidotransferase, subunit A |   | oocyte karyosome formation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0162144PMID:12930750 | 20060803

**Comment by hattrill** [comment]
Phenotype. Removed.

**Comment by ValWood** [comment]
great,
