### ISSUE TITLE
Matrix: Plod3  amino acid metabolism/ glycosylation 2 (MGI + PAINT)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2419]
As far as I can see collogen is the only known substrate of Plod3. or at least, it seems to modify proteins and not free amino-acids

Plod3	procollagen-lysine, 2-oxoglutarate 5-dioxygenase 3		hydroxylysine biosynthetic process		UniProt	Mus musculus	IDA		procollagen-lysine,2-oxoglutarate 5-dioxygenase/glycosyltransferase 25 family member pthr10730	protein		MGI:MGI:6202004
PMID:16447251	20180903

Plod3	procollagen-lysine, 2-oxoglutarate 5-dioxygenase 3		hydroxylysine biosynthetic process		MGI	Mus musculus	ISO	UniProtKB:O60568	procollagen-lysine,2-oxoglutarate 5-dioxygenase/glycosyltransferase 25 family member pthr10730	protein		GO_REF:0000096

Plod3 | procollagen-lysine, 2-oxoglutarate 5-dioxygenase 3 |   | hydroxylysine biosynthetic process |   | MGI | Mus musculus | ISO | UniProtKB:O60568 | procollagen-lysine,2-oxoglutarate 5-dioxygenase/glycosyltransferase 25 family member pthr10730 | protein |   | GO_REF:0000096MGI:MGI:4834177 | 20160603

**Comment by ValWood** [comment]
Also PAINTED from this

Plod3 | procollagen-lysine, 2-oxoglutarate 5-dioxygenase 3 |   | hydroxylysine biosynthetic process |   | GO_Central | Mus musculus | IBA | PANTHER:PTN000842962UniProtKB:O00469 more... | procollagen-lysine,2-oxoglutarate 5-dioxygenase/glycosyltransferase 25 family member pthr10730 | protein |   | PMID:21873635 | 20180308
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ukemi** [comment]
@hdrabkin handles the distribution of annotation review requests for MGI.

**Comment by ukemi** [comment]
I'm going to give this one back to @hdrabkin because I think it is more a question of the ontology. Is hydroxylysine always synthesized as a postranslational modification or is it ever made as a free amino-acid derivative. Maybe we need to request the 5-hydroxylysinate residue from ChEBI? This would then have a 'is subsequent group from' relation to the free 5-hydroxylysinate. It looks like we do not chain over this relation to the non-residue classes. See GO:0008612. Also, if this is the only context in which this is made, we may want to change the term name to be more similar to GO:0008612.

**Comment by ukemi** [comment]
Reactome only has them on collagens.

**Comment by ukemi** [comment]
Actually, I take that back, they have the metabolism of the free compound represented. So it definitely gets metabolized. But is it only synthesized on collagen?

https://reactome.org/PathwayBrowser/#/R-HSA-71064&SEL=R-HSA-6788611&PATH=R-HSA-1430728,R-HSA-71291&FLG=60175

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/issues/17518

**Comment by hdrabkin** [comment]
There appears to be a case for lysine hydroxylation of non-peptide lysine in E.coli
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC214457/

**Comment by ukemi** [comment]
Then we should retain the term, but create a new one for the collagen modification and move the annotation.

**Comment by hdrabkin** [comment]
I removed link; it doesn't seem to be hydroxylated at the same position
https://en.wikipedia.org/wiki/Hydroxylysine

**Comment by hdrabkin** [comment]
The bacterial one appears to be N-hydroxy vs the 5-Hydroxy-L-lysine

**Comment by ukemi** [comment]
What do you mean by 'I removed the link'? Isn't the AA hierarchy inferred by the reasoner?

**Comment by ukemi** [comment]
Or the AA derivative?

**Comment by hdrabkin** [comment]
The link to the paper about the bacterial enzyme; it's still on the wiki page above. NOT a link in the ontology.

**Comment by deustp01** [comment]
> Actually, I take that back, they have the metabolism of the free compound represented. So it definitely gets metabolized. But is it only synthesized on collagen? https://reactome.org/PathwayBrowser/#/R-HSA-71064&SEL=R-HSA-6788611&PATH=R-HSA-1430728,R-HSA-71291&FLG=60175

"Only on collagen" is one of those negative results. The collagen post-translational modification is a major function for the enzyme and the only function we've annotated.

**Comment by pgaudet** [comment]
@marcfeuermann and I removed 'hydroxylysine biosynthetic process' 

The protein catalyses a PTM on protein (as stated in the original comment). Disputed human annotations in P2GO.

**Comment by ValWood** [comment]
Hi PAscale,

Which annotations were disputed? I would like to add them to the Matrix spreadsheet.
Actually I only add if resolved so if you get a resolution soon could you forward I will add. Not to worry if not. It doesn't matter so much....

**Comment by pgaudet** [comment]
I disputed 


* CAFA | O60568 | GO:0046947 | ECO:0000315 (IMP) | PMID:10934207
* CAFA | O60568 | GO:0046947 | ECO:0000314 (IDA) | PMID:9724729
* CAFA | O60568 | GO:0046947 | ECO:0000314 (IDA) | PMID:9582318
*  CAFA | Q02809 | GO:0046947 | ECO:0000250 (ISS) | PMID:9582318 | UniProtKB:O60568
Thanks, Pascale

**Comment by ValWood** [comment]
Hi @pgaudet  did these get removed yet? If so I can add to my spreadsheet.

val

**Comment by pgaudet** [comment]
No - @ggeorghiou is getting back from vacation this week, hopefully he can fix them.

**Comment by ggeorghiou** [comment]
Hi all, back from vacation now. Will work on these when I have a chance. It appears I've been tagged in a great many tickets....

**Comment by pgaudet** [comment]
All resolved, thanks @ggeorghiou !!
