### ISSUE TITLE
Matrix: let-268  PAINT amino acid biosynthesis/ protein glycosylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2422]
let-268 |   |   | hydroxylysine biosynthetic process |   | GO_Central | Caenorhabditis elegans | IBA | PANTHER:PTN000842962UniProtKB:O00469

(this is 
UDP-glucose:glycoprotein glucosyltransferase activity
)

**Comment by pgaudet** [comment]
Same tree as https://github.com/geneontology/go-annotation/issues/2419
Fixed.
