### ISSUE TITLE
Matrix: ero1b prdx4 amino acid metabolism/protein folding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2423]
4-hydroxyproline metabolic process
--
I think this is protein folding or isomerization upstream of collagen modification, but isn't part of the amino-acid derivative biosyntheis

~Ero1b | endoplasmic reticulum oxidoreductase 1 beta |   | 4-hydroxyproline metabolic process |   | RGD | Rattus norvegicus | ISO | RGD:1557809 | ero1-related pthr12613 | gene |   | MGI:MGI:5461404PMID:22981861RGD:1624291 | 20160512~

~Prdx4 | peroxiredoxin 4 |   | 4-hydroxyproline metabolic process |   | RGD | Rattus norvegicus | ISO | RGD:731498 | thioredoxin peroxidase pthr10681 | gene |   | MGI:MGI:5461404PMID:22981861RGD:1624291 | 20160512~

~Ero1a | endoplasmic reticulum oxidoreductase 1 alpha |   | 4-hydroxyproline metabolic process |   | RGD | Rattus norvegicus | ISO | RGD:732479 | ero1-related pthr12613 | gene |   | MGI:MGI:5461404PMID:22981861RGD:1624291 | 20160512~

above should be fixed by pipeline

Prdx4	peroxiredoxin 4		4-hydroxyproline metabolic process		MGI	Mus musculus	IGI	MGI:MGI:1354385 MGI:MGI:1914725	thioredoxin peroxidase pthr10681	protein		MGI:MGI:5461404 PMID:22981861	20140120

**Comment by ValWood** [comment]
If  the modification is the term you ned, then its:

peptidyl-proline hydroxylation to 4-hydroxy-L-proline

which will still create a violation right now  but will be fixed by:
https://github.com/geneontology/go-ontology/issues/17518

**Comment by ValWood** [comment]
Same issue with

Prdx4 | peroxiredoxin 4 |   | 4-hydroxyproline metabolic process |   | RGD | Rattus norvegicus | ISO | RGD:731498 | thioredoxin peroxidase pthr10681 | gene |   | MGI:MGI:5461404PMID:22981861RGD:1624291 | 20160512

Prdx4 | peroxiredoxin 4 |   | 4-hydroxyproline metabolic process |   | MGI | Mus musculus | IGI | MGI:MGI:1354385MGI:MGI:1914725 | thioredoxin peroxidase pthr10681 | protein

**Comment by ValWood** [comment]
pdi-2 |   |   | peptidyl-proline hydroxylation to 4-hydroxy-L-proline |   | WB | Caenorhabditis elegans | IDA |   |   | gene |   | PMID:18276589WB_REF:WBPaper00031524 | 20120112


or am I wrong here?

**Comment by ValWood** [comment]
This does seem to act directly on collagens so maybe these terms should . be merged or this one obsoleted? The seem to mean the same thing?

**Comment by gthayman** [comment]
The first 3 are from MGD.

**Comment by ValWood** [comment]
yup:
https://en.wikipedia.org/wiki/Hydroxyproline
Hydroxyproline is produced by hydroxylation of the amino acid proline by the enzyme prolyl hydroxylase following protein synthesis (as a post-translational modification). T

**Comment by hdrabkin** [comment]
@ValWood , Looking the close this; I see the MGI lines crossed out. What does this mean? Are we good?

**Comment by hdrabkin** [comment]
looking at the paper for the one not crossed out, (the IGI), I see it is actually that ascorbic acid biosynthesis is getting hit; Ascorbic acid is a required co-factor for any collagen proline hydroxylase. So it's a bit further along 'Compromised ER disulfide relay thus exposes protein thiols to competing for oxidation to sulfenic acid, resulting in depletion of ascorbic acid, impaired procollagen proline 4-hydroxylation,"

**Comment by ValWood** [comment]
HI HArold,

I think the issue will be fixed by changing the parentage of 
https://github.com/geneontology/go-ontology/issues/17518
so it is not an amino acid metabolic process (its a modification)

17518 is assigned to you too, you could close this one....

**Comment by ValWood** [comment]
I was referring to prdx4 in my comment. I will edit to make this clear

**Comment by ValWood** [comment]
you could also  fix the pedx4 issue for this annotation by moving to 
peptidyl-proline hydroxylation to 4-hydroxy-L-proline (I think?)

**Comment by ValWood** [comment]
...I'm a  bit confused...

**Comment by hdrabkin** [comment]
So to fix this annotation, it should be to the peptidyl term. not the term that could be interpreted as acting on free proline 
(however, I am not aware of hydroxylation of free proline anyway.)

**Comment by ValWood** [comment]
Yes, I agree.  I think the other term should probably not exist...that is what the ontology tracker  ticket is about.

I got confused by the ascorbic acid part....

**Comment by hdrabkin** [comment]
| GO:0018401
peptidyl-proline hydroxylation to 4-hydroxy-L-proline
Done; THIS ticket can be closed now; looking at the ontology ticket now

**Comment by vanaukenk** [comment]
@ValWood - Is there anything I need to do for the WB annotation here?  Is it that the annotation okay, but the ontology parentage needs to be updated?

**Comment by hdrabkin** [comment]
quickly looking at the wb paper; I think it's fine. The paper talks about the activity on peptides.

**Comment by ValWood** [comment]
@vanaukenk  yes, the ontology fix will fix yours.

**Comment by hdrabkin** [comment]
And also found 2 more mis-annotations (same paper; IGI will always include at least two genes).
