### ISSUE TITLE
Matrix: LARS  amino acid metabolism/protein targeting 1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2424]
LARS is a Leucyl-tRNA synthetase is an intracellular leucine sensor for the mTORC1-signaling pathway.

so it could be annotated to positive regulation of TOR signalling

but not to 

UniProtKB:Q9P2J5 | LARS | involved_in | GO:0006622    protein targeting to lysosome | ECO:0000315 IMP | PMID:22424946 |   | 9606 Homo sapiens | CAFA

this seems to be only a phenotype, this isn't really about targeting,  positive regulation of TOR signalling causes TOR to move to the vacuole/lysosome but that's just part of the p[athway. If this must be captured, it would be localization not targeting, but it's just part of the signaling process.

The author intent is summarized nicely here:

These results suggest that endogenous LRS is involved in an
amino acid- and leucine-induced mTORC1 activation pathway.
Withdrawal of amino acids, particularly the branched chain
amino acids leucine and isoleucine, is known to inhibit mTORC1
signaling. We monitored whether LRS also mediates isoleucineinduced mTORC1 activation. Depletion of isoleucine did not
completely suppress S6K phosphorylation, but supplementation
of isoleucine increased S6K phosphorylation. Interestingly,
isoleucine-induced S6K phosphorylation was inhibited by LRS
knockdown but not by IRS knockdown (Figure 2D), suggesting
that LRS mediates amino acid-induced mTORC1 signaling.

There are 112 annotations from this paper. Were ALL of the experiments done on human and rat cells? (unlikely)_ I can't figure out which organism it is because I didn't find anything with a search on human or rat, but presumably some of these annotations are ISS?

A useful annotation to demonstrate the multifunctionality of LARS would be to annotate as an "amino acid sensor"

**Comment by ValWood** [comment]
Is this a readout?

LARS | Leucine--tRNA ligase, cytoplasmic |   | negative regulation of autophagy |   | CAFA | Homo sapiens | IMP |   | family not named pthr45794 | protein |   | PMID:22424946 | 20170

**Comment by ggeorghiou** [comment]
@ValWood I've gone ahead and made the suggested change where it is now annotated to positive regulation of TOR signaling. I also deleted the negative regulation of autophagy annotation. Closing this ticket.
