### ISSUE TITLE
Matrix: amino acid metabolism/transmembrane transport 1 (legacy TAS from PINC)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2427]
this is a transporter, delete ancient TAS

SLC7A2 | Cationic amino acid transporter 2 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | family not named pthr43243 | protein |   | PMID:8954799 | 20030904

**Comment by ValWood** [comment]
and

SLC7A8 | Large neutral amino acids transporter small subunit 2 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | amino acid transporter pthr11785 | protein |   | PMID:10391915 | 20030904

**Comment by ValWood** [comment]
and

SLC6A14 | Sodium- and chloride-dependent neutral and basic amino acid transporter B(0+) |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | sodium/chloride dependent transporter pthr11616 | protein |   | PMID:10446133 | 20030904

SLC6A6 | Sodium- and chloride-dependent taurine transporter |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | sodium/chloride dependent transporter pthr11616 | protein |   | PMID:8010975 | 20030904


SLC7A6 | Y+L amino acid transporter 2 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | amino acid transporter pthr11785 | protein |   | PMID:9829974 | 20030904

**Comment by ValWood** [comment]
need to trace to original annotations

SLC1A3 | Excitatory amino acid transporter 1 |   | glutamate biosynthetic process |   | Ensembl | Homo sapiens | IEA | UniProtKB:P56564ensembl:ENSMUSP00000005493 | sodium/dicarboxylate symporter-related pthr11958 | protein |   | GO_REF:0000107 | 20190601



SLC1A3 | Excitatory amino acid transporter 1 |   | gamma-aminobutyric acid biosynthetic process |   | Ensembl | Homo sapiens | IEA | UniProtKB:P56564ensembl:ENSMUSP00000005493 | sodium/dicarboxylate symporter-related pthr11958 | protein |   | GO_REF:0000107 | 20190601
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
SLC7A7 | Y+L amino acid transporter 1 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | amino acid transporter pthr11785 | protein |   | PMID:9829974 | 20030904

**Comment by ValWood** [comment]
SLC3A1 | Neutral and basic amino acid transport protein rBAT |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | alpha-amylase pthr10357 | protein |   | PMID:8054986 | 20030904

**Comment by pgaudet** [comment]
Deleted 
- [x] SLC7A2 | Cationic amino acid transporter 2 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | family not named pthr43243 | protein |   | PMID:8954799 | 20030904
- [ ] SLC7A8 | Large neutral amino acids transporter small subunit 2 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | amino acid transporter pthr11785 | protein |   | PMID:10391915 | 20030904
- [ ] SLC7A4 | Cationic amino acid transporter 4 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | family not named pthr43243 | protein |   | PMID:9598310 | 20030904
SLC6A14 | Sodium- and chloride-dependent neutral and basic amino acid transporter B(0+) |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | sodium/chloride dependent transporter pthr11616 | protein |   | PMID:10446133 | 20030904
- [ ] SLC6A6 | Sodium- and chloride-dependent taurine transporter |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | sodium/chloride dependent transporter pthr11616 | protein |   | PMID:8010975 | 20030904
- [ ] SLC7A7 | Y+L amino acid transporter 1 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | amino acid transporter pthr11785 | protein |   | PMID:9829974 | 20030904
- [ ] SLC3A1 | Neutral and basic amino acid transport protein rBAT |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | alpha-amylase pthr10357 | protein |   | PMID:8054986 | 20030904
- [ ] SLC7A6 | Y+L amino acid transporter 2 |   | cellular amino acid metabolic process |   | PINC | Homo sapiens | TAS |   | amino acid transporter pthr11785 | protein |   | PMID:9829974 | 20030904

**Comment by pgaudet** [comment]
MGI:99917 should not be annotated to 'x metabolic process' 

@hdrabkin

**Comment by ValWood** [comment]
Hi Harold, can you close this one when you do the mouse annotation, thanks
Val

**Comment by hdrabkin** [comment]
I assigned Dmitry to do this.

**Comment by hdrabkin** [comment]
Done closed

**Comment by ValWood** [comment]
was that
glutamate metabolic process
and
glutamate biosynthetic process
?
(for the spreadsheet)

**Comment by hdrabkin** [comment]
Yes both; do not see a spreadsheet in this ticket.

**Comment by ValWood** [comment]
No don't worry. It's so many individual annotations I am compiling them into the spreadsheet as I go. I just wasn't sure what the terms were here as Pascale identified the MGI ones.
