### ISSUE TITLE
Matrix: amino acid metabolism/transmembrane transport 4

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2431]
Is a transporter. Paper (abstravct) appears to describe a lysine requirement due to transport defect?

SLC25A32 | Mitochondrial folate transporter/carrier |   | glycine metabolic process |   | BHF-UCL | Homo sapiens | ISS | UniProtKB:Q6IZB5 | family not named pthr45683 | protein |   | GO_REF:0000024 | 20150702

  | SLC25A32 | Mitochondrial folate transporter/carrier |   | glycine metabolic process |   | BHF-UCL | Homo sapiens | IGI | UniProtKB:Q6IZB5 | family not named pthr45683 | protein |   | PMID:15140890 | 20150702

**Comment by pgaudet** [comment]
Disputed in P2GO.

**Comment by RLovering** [comment]
Hi Both

I have deleted this annotation, please remove the dispute comment from the deleted section of PMID:15140890 

Thanks

Ruth

**Comment by ValWood** [comment]
I'm never sure if these should be "acts upstream of". Folate is known to be required  upstream of DNA metabolism, lipid metabolism and amino acid metabolism.

I keep asking about this- but it isn't clear if we would  aim to annotate, for example, ALL folate pathway as upstream of all of these processes? Where would we stop? Nobody has answered the question yet, so I am still unsure/. It would be really great if we could have clear information as to whether we annotate "acts upstream of" in situations where a process is *known* to be upstream of another.

 The useful information in this paper is that it identifies a critical residue and an auxotrophy phenotype but this would be better as a phenotype/genotype connection (I know . this isn't possible for human).

It is still an unanswered question as to whether we should annotate ALL upstream dependencies. 
I get different answers depending who I ask....

**Comment by deustp01** [comment]
Folate derivatives (folate with a donatable carbon in various states of reduction) are required participants in DNA metabolism (nucleotide biosynthesis), amino acid metabolism. Processes that generate these molecules by mediating their de novo synthesis, or regeneration / interconversion among reduction states, or uptake by cells are thus causally upstream of DNA metabolism etc. and would qualify for a "provides required input for" annotation. One could get a more fine-grained "provides required input for" annotation by pointing to the specific activity that mediates generation of the exact folate derivative consumed in the DNA / lipid / amino acid metabolic process of interest.

At least in mammals, as far as I know, these processes are constitutive - blockage by toxins, drugs, vitamin deficiencies, and mutations in genes of folate metabolism are pathologies - so they wouldn't qualify for a regulation term.
