### ISSUE TITLE
Matrix:  (TH) amino acid metabolism/vesicle-mediated transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2432]
Th | tyrosine hydroxylase |   | aminergic neurotransmitter loading into synaptic vesicle |   | RGD | Rattus norvegicus | IDA |   | aromatic amino acid tyrosine/tryptophan/phenylalanine hydroxylase pthr11473 | gene |   | PMID:19903816RGD:5128868 | 20110322

this appears to be describing the production of dopamine by TH and the loading by 
associated VMAT(1)?

http://amigo.geneontology.org/amigo/reference/PMID:19903816

**Comment by gthayman** [comment]
They provide evidence that TH, AADC and VMAT2 are in a synaptic vesicle-associated complex, and that DA synthesis and vesicle DA loading are linked in this complex.

**Comment by ValWood** [comment]
Ah OK, I can create an exception to the rule for this complex. What is it called?

**Comment by gthayman** [comment]
Sorry for the delay. They call it a VMAT2-AADC-TH complex (2 is subscripted).

**Comment by ValWood** [comment]
Thanks Tom,  is there a GO term for the complex (I could not find one).  Otherwise, I can create an exception using panther family ID, or another specific GO term...

**Comment by gthayman** [comment]
I couldn't find one either, sorry.

**Comment by ValWood** [comment]
PTHR11473 will provide an exception for this member of the complex.
