### ISSUE TITLE
MAtrix (ILV5) amino acid metabolism/mitochondrial organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2433]
ILV5 is described as 
Acetohydroxyacid reductoisomerase and mtDNA binding protein; 

so do you think theser are OK< or are they just downstream effects

ILV5 | Acetohydroxyacid reductoisomerase and mtDNA binding protein |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IGI | SGD:S000000956 | family not named pthr21371 | gene |   | PMID:18826960 | 20120501
  | ILV5 | Acetohydroxyacid reductoisomerase and mtDNA binding protein |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IGI | SGD:S000003679 | family not named pthr21371 | gene |   | PMID:18826960 | 20120501
  | ILV5 | Acetohydroxyacid reductoisomerase and mtDNA binding protein |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr21371 | gene |   | PMID:7621838

From what I can see these are mainly GIs (supressors) 
https://www.yeastgenome.org/reference/S000127907
which would not be surprising  that this was a long range phenotype. They don't appear to 
suggest a mechanism. 

If you think it is OK, I can add an exception for this.

**Comment by ValWood** [comment]
also
(this does seem to be indirect)
KGD2 | Dihydrolipoyl transsuccinylase |   | mitochondrial genome maintenance |   | SGD | Saccharomyces cerevisiae S288C | IGI | SGD:S000004676 | family not named pthr43416 | gene |   | PMID:10869431 | 20100603
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by srengel** [comment]
for ILV5, looks that that one may be bifunctional.  different mutants cause loss of either the branched chain amino acid biosynthetic function or the mtDNA stability function.  so i think we could leave those as is.

will look at KGD2...

**Comment by ValWood** [comment]
exception added for ILV5

**Comment by srengel** [comment]
i have removed the KGD2 annotation.
