### ISSUE TITLE
Matrix: GCL (both subunits) amino acid/mitochondion organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2436]
GCLC | Glutamate--cysteine ligase catalytic subunit |   | apoptotic mitochondrial changes |   | Ensembl | Homo sapiens | IEA | UniProtKB:P97494ensembl:ENSMUSP00000034905 | glutamate cysteine ligase pthr11164 | protein |   | GO_REF:0000107

- GCL is upstream of glutathione synthesis (rate limiting step)
- glutathine is free radical scavanger (protection agains apoptosis)
- Overexpressing GCL -( GCLC and GCLM) subunits gives protection against apoptosis

https://www.ncbi.nlm.nih.gov/pubmed/15288121

P97494 is the mouse protein.
So because apotosis is mitochondrial organization, this gets mitochondrial organization. Does that seem OK?
The affect on organization seems way downstream ?

**Comment by ukemi** [comment]
I'm not convinced on your reasoning for this one, but I think I can make the annotation better. This enzyme is involved in making glutathione, which has a role in responding to oxidative stress. Oxidative stress directly effects mitochondria so I think this the mechanism by which this gene product interacts with the apoptotic program. It is one of the targets of apoptotic caspases, so during apoptosis it is inactivated (see the reference for the annotation). So I don't think it's way downstream. Instead, I think when it is functional, it negatively regulates the mitochondrial changes that are triggered during the apoptotic program, which are sensitized by oxidative stress. That said, I'm going to change these annotations to GO:1901029 negative regulation of mitochondrial outer membrane permeabilization involved in apoptotic signaling pathway, which in turn would negatively regulate apoptosis. This is going on the assumption that the activity of this enzyme is kind of like a rheostat: when it is active it protects against apoptosis, but when apoptosis is triggered the enzyme gets cleaved.

**Comment by ValWood** [comment]
OK I'll add an exception for
pthr11164 @ pthr13295
