### ISSUE TITLE
Matrix:  Htt amino acid metabolism/ mitochondrial membrane organization 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2437]
"regulation of mitochondrial membrane permeability"

this isn't a programmed effect, it's a 

"suggesting mitochondria undergo compensatory changes in calcium sensitivity in response to the many cellular changes wrought by polyglutamine expansion. "

i.e. it's a disease symptom/phenotype

Htt | huntingtin |   | regulation of mitochondrial membrane permeability | regulates → occurs inEMAPA:17549 | MGI | Mus musculus | IMP | MGI:MGI:1861934 | huntington disease protein pthr10170 | protein

(this is likely the case for most annotations to this term ? I might look at this later)

**Comment by ValWood** [comment]
This one is weird.

bb8 is described as a testis specific protein with a role in mitochondrial organization:

http://amigo.geneontology.org/amigo/reference/PMID:27529784

BUT it is a  the conserved 

mnitochondrial glutamate dehydrogenase [NAD(P)+] activity

**Comment by ValWood** [comment]
Actually you also have gdh, so maybe some subfunctionalization going on. If you think bb8, or any of these are OK let me know and I'll add an exception for this.

**Comment by ValWood** [comment]
based on this, I am going to allow "glutamine metabolism" to overlap with mitochonrdal organization http://amigo.geneontology.org/amigo/reference/PMID:19742324

**Comment by gthayman** [comment]
This is from MGD.

**Comment by ValWood** [comment]
yep!

**Comment by ukemi** [comment]
I agree @ValWood , these annotations need to be reviewed. The polyglutamine repeat expansions are dominant gain of function alleles that need to be interpreted with extreme caution.

**Comment by ukemi** [comment]
I removed this annotation ( I thought). Why did you reassign this to me?

**Comment by ValWood** [comment]
It wasn't clear that you removed it. 

I thought you were just saying "these annotations need to be reviewed"

now closing ;)

**Comment by ukemi** [comment]
Ah OK. Sorry for the confusion. Have put this gene on the agenda at our lab meeting for a full review, but I did remove the annotations you questioned.
