### ISSUE TITLE
Matrix:  amino acid metabolism/mitochondrial organisation 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2438]
The 3 mitochondrial organisation from  this  paper  seem to be phenotypes (would cause pleiotropic effects?)

http://amigo.geneontology.org/amigo/reference/PMID:19755423

dmGlut | Dietary and metabolic glutamate transporter |   | mitochondrion organization |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0209321PMID:19755423 | 20110324

SelD | Selenide,water dikinase |   | mitochondrion organization |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0209321PMID:19755423 | 20110324

Gs1 | Glutamine synthetase 1 |   | mitochondrion organization |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0209321PMID:19755423 | 20110324

phenotype only? abnormal mitochondria?

**Comment by ValWood** [comment]
maybe this is OK....; 

expression and that elevated levels of glutamine lead to a nutritional stress that provides a signal for megamitochondrial formation

If this is a nutritional response it's OK,  but I might in this case annotate to the regulation of mitochondrial fusion maybe?

**Comment by ValWood** [comment]
This one looks like a disease phenotype though:
Delta-1-pyrroline-5-carboxylate dehydrogenase (P5CDh) is a nuclear-encoded mitochondrial enzyme that catalyzes the second step in proline degradation. Mutations in human P5CDh cause type II hyperprolinemia, a complex syndrome displaying increased serum proline and mental disabilities. Conceptual gene CG7145 in Drosophila melanogaster encodes the orthologous DmP5CDh1. The mutant allele CG7145(f04633) contains a piggyBac transposon that truncates the enzyme by 83 residues. Heterozygous (CG7145(f04633)/TM3) individuals developed normally, while homozygous (CG7145(f04633)/CG7145(f04633)) individuals displayed proline levels twice that of normal, swollen mitochondria, and ultimately larval and pupal lethality. We believe this is the first correlation between the loss of P5CDh and morphological defects in mitochondria


P5CDh1 | delta-1-Pyrroline-5-carboxylate dehydrogenase 1 |   | mitochondrion organization |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0213855PMID:21168532 | 20110616

I wonder if these are different phenotypes. "Swollen" (defect) or "fused" possibly a programmed response...

**Comment by ValWood** [comment]
This one is weird.

bb8 is described as a testis specific protein with a role in mitochondrial organization:

http://amigo.geneontology.org/amigo/reference/PMID:27529784

BUT it is a  the conserved 

mnitochondrial glutamate dehydrogenase [NAD(P)+] activity

**Comment by ValWood** [comment]
based on this, http://amigo.geneontology.org/amigo/reference/PMID:19742324
I am going to allow "glutamine metabolism" to overlap with mitochondrial organization 

This is quite a nice little set. It might be worth figuring if it is regulation of  mitochondrial  fusion , which would link these togther  more clearly...

**Comment by ValWood** [comment]
Slimp | Seryl-tRNA synthetase-like insect mitochondrial protein |   | mitochondrion morphogenesis |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0212542PMID:20870726 | 20110127

The way this one is described would make it a phenotype:
 capacity and an increase in mitochondrial mass in the form of aberrant mitochondria.


and this
Slimp | Seryl-tRNA synthetase-like insect mitochondrial protein |   | cellular respiration |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0212542PMID:20870726 | 20110127

is usually a phenotype of abolished mitochondrial gene expression. Although in the abstract they say that the essentiallity  of Slipm is not related to the translation function....I did not dig deeper than that...

**Comment by hattrill** [comment]
dmGlut
SelD
Gs1
bb8
Basically, looks like elevated glutamine (and things that effect glutamate pool) causes mitochondrial fusion.
Have updated these to regulation terms for mitochondrial fusion.

P5CDh1 & Slimp - removed mito org/morphology annotation. Looks phenotypic side-effect rather than a genuine cellular response.

**Comment by ValWood** [comment]
added exceptions for glutamine and glutamate metabolism.
