### ISSUE TITLE
Matrix: tRNA metabolism/DNA replication 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2439]
Is this keyword  mapping out of date?

DTD1 | D-aminoacyl-tRNA deacylase 1 |   | DNA replication |   | UniProt | Homo sapiens | IEA | UniProtKB-KW:KW-0235 | d-tyrosyl-trna tyr deacylase pthr10472 | protein

**Comment by sylvainpoux** [comment]
Hi Val,
there are at least 2 papers describing this activity. I would therefore be tempted to keep the keyword

Sylvain

RN   [6]
RP   FUNCTION, PHOSPHORYLATION, SUBUNIT, AND SUBCELLULAR LOCATION.
RX   PubMed=15653697; DOI=10.1074/jbc.M404754200;
RA   Casper J.M., Kemp M.G., Ghosh M., Randall G.M., Vaillant A.,
RA   Leffak M.;
RT   "The c-myc DNA-unwinding element-binding protein modulates the
RT   assembly of DNA replication complexes in vitro.";
RL   J. Biol. Chem. 280:13071-13083(2005).
RN   [11]
RP   FUNCTION, SUBCELLULAR LOCATION, PHOSPHORYLATION, AND INTERACTION WITH
RP   CDC45 AND TOPBP1.
RX   PubMed=20065034; DOI=10.1128/MCB.00710-09;
RA   Chowdhury A., Liu G., Kemp M., Chen X., Katrangi N., Myers S.,
RA   Ghosh M., Yao J., Gao Y., Bubulya P., Leffak M.;
RT   "The DNA unwinding element binding protein DUE-B interacts with Cdc45
RT   in preinitiation complex formation.";
RL   Mol. Cell. Biol. 30:1495-1507(2010).
...
CC   -!- FUNCTION: Possible ATPase (PubMed:15653697) involved in DNA
CC       replication, may facilitate loading of CDC45 onto pre-replication
CC       complexes (PubMed:20065034). {ECO:0000269|PubMed:15653697,
CC       ECO:0000269|PubMed:20065034}.

**Comment by ValWood** [comment]
OK assigned to me to create an exception

**Comment by ValWood** [comment]
Hi @hdrabkin  do you know anythink about this. It seems really strange. I now think the  D-aminoacyl-tRNA deacylase is probably incorrect and the DNA replication associatd activity is fine.

I can't find any support for the aminoacyl-tRNA deacylase and this isn't annotated at MGI except by PAINT. I wondered if you  knew anything about it?  The mouse description says


[Summary is not available for the mouse gene. This summary is for the human ortholog.] The protein encoded by this gene is similar in sequence to histidyl-tRNA synthetase, which hydrolyzes D-tyrosyl-tRNA(Tyr) into D-tyrosine and free tRNA(Tyr). The encoded protein binds the DNA unwinding element and plays a role in the initiation of DNA replication. Alternative splicing results in multiple transcript variants encoding different isoforms. [provided by RefSeq, Dec 2015]

so it acknowledges the similarity to D-aminoacyl-tRNA deacylase, but only confirms the replication associated role.

**Comment by ValWood** [comment]
There is a paper used to annotate SGD  ddt1
https://www.yeastgenome.org/locus/S000002378#go

arggh this one is confusing!

**Comment by ValWood** [comment]
Annotation sources used by PAINT:

DTD1 | D-aminoacyl-tRNA deacylase 1 |   | D-tyrosyl-tRNA(Tyr) deacylase activity |   | GO_Central | Homo sapiens | IBA | EcoGene:EG11852MGI:MGI:1923485 more... | d-tyrosyl-trna tyr deacylase pthr10472 | protein |   | PMID:21873635 | 20170228

  | DTD1 | D-aminoacyl-tRNA deacylase 1 |   | aminoacyl-tRNA editing activity |   | GO_Central | Homo sapiens | IBA | EcoGene:EG11852PANTHER:PTN000049487 | d-tyrosyl-trna tyr deacylase pthr10472 | protein |   | PMID:21873635 | 20170228

**Comment by ValWood** [comment]
D-aminoacyl-tRNA deacylase 1
https://www.ncbi.nlm.nih.gov/pubmed/29410408?dopt=Abstract
is very well established.

replication role not so clear
https://www.uniprot.org/citations/15653697
The presence of DNA-unwinding elements (DUEs) at eukaryotic replicators has raised the question of whether these elements contribute to origin activity by their intrinsic helical instability, as protein-binding sites, or both. We used the human c-myc DUE as bait in a yeast one-hybrid screen and identified a DUE-binding protein, designated DUE-B, with a predicted mass of 23.4 kDa. Based on homology to yeast proteins, DUE-B was previously classified as an aminoacyl-tRNA synthetase; however, the human protein is approximately 60 amino acids longer than its orthologs in yeast and worms and is primarily nuclear. In vivo, chromatin-bound DUE-B localized to the c-myc DUE region. DUE-B levels were constant during the cell cycle, although the protein was preferentially phosphorylated in cells arrested early in S phase. Inhibition of DUE-B protein expression slowed HeLa cell cycle progression from G1 to S phase and induced cell death. DUE-B extracted from HeLa cells or expressed from baculovirus migrated as a dimer during gel filtration and co-purified with ATPase activity. In contrast to endogenous DUE-B, baculovirus-expressed DUE-B efficiently formed high molecular mass complexes in Xenopus egg and HeLa extracts. In Xenopus extracts, baculovirus-expressed DUE-B inhibited chromatin replication and replication protein A loading in the presence of endogenous DUE-B, suggesting that differential covalent modification of these proteins can alter their effect on replication. Recombinant DUE-B expressed in HeLa cells restored replication activity to egg extracts immunodepleted with anti-DUE-B antibody, suggesting that DUE-B plays an important role in replication in vivo.

https://www.uniprot.org/citations/20065034
Template unwinding during DNA replication initiation requires the loading of the MCM helicase activator Cdc45 at replication origins. We show that Cdc45 interacts with the DNA unwinding element (DUE) binding protein DUE-B and that these proteins localize to the DUEs of active replication origins. DUE-B and Cdc45 are not bound at the inactive c-myc replicator in the absence of a functional DUE or at the recently identified ataxin 10 (ATX10) origin, which is silent before disease-related (ATTCT)(n) repeat length expansion of its DUE sequence, despite the presence of the origin recognition complex (ORC) and MCM proteins at these origins. Addition of a heterologous DUE to the ectopic c-myc origin, or expansion of the ATX10 DUE, leads to origin activation, DUE-B binding, and Cdc45 binding. DUE-B, Cdc45, and topoisomerase IIbeta binding protein 1 (TopBP1) form complexes in cell extracts and when expressed from baculovirus vectors. During replication in Xenopus egg extracts, DUE-B and Cdc45 bind to chromatin with similar kinetics, and DUE-B immunodepletion blocks replication and the loading of Cdc45 and a fraction of TopBP1. The coordinated binding of DUE-B and Cdc45 to origins and the physical interactions of DUE-B, Cdc45, and TopBP1 suggest that complexes of these proteins are necessary for replication initiation.

from the same lab, nothing since 2010
seems to be a combination of pleiotropic phenotypes and binding assays.

**Comment by ValWood** [comment]
Pubmed search gives one more paper
https://www.ncbi.nlm.nih.gov/pubmed/25258324
also same lab. No other people in the replciation community have publisehd on this connection.

Although:
https://www.ncbi.nlm.nih.gov/pubmed/22380713
so maybe this is a "metazoan specific" role for this protein.

For now I added an exception but I'll add this to my "questionable" and follow up with tRNA metabolism/DNA replication experts.

**Comment by hdrabkin** [comment]
The mouse nomenclature seems very specific, most likely based on orthology to DTD1. MGI has no literature for functional annotation, but not surprising for a mouse protein for anything involved in translation. Let me do a little more digging.

**Comment by ValWood** [comment]
I already added an exception, but it wasn't very clear to me if there was strong support for replication. Everything is from the same lab...
