### ISSUE TITLE
Matrix: TAIR trna metabolism/ carbohydrate metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2441]
This looks weird but I can't figure it out.
It has annotations for

http://amigo.geneontology.org/amigo/gene_product/TAIR:locus:2024377

tRNA pseudouridine synthase activity
but also to 
cell wall stuff.

Are some of the domain hits false positives?

**Comment by tberardini** [comment]
Seems to me that it's the InterPro and UniProt annotations that possibly need review, the TAIR-made ones are all CC related [plasma] membrane ones.  Who checks the INTERPRO2GO mappings?

**Comment by ValWood** [comment]
> Who checks the INTERPRO2GO mappings?


Anyone, but I am including them in this project.

However, I think this problem is fixed. At least it's strange because these annotations don't show up in UniProt
https://www.uniprot.org/uniprot/O04500
or QuickGO
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=O04500

I'll close this  one and assume that it will get sorted in AmiGO?

**Comment by ValWood** [comment]
Although the reference for this IEA is
TAIR:AnalysisReference:501756966

Do you run InterPro locally yourselves? In this case it might not resolve...

**Comment by tberardini** [comment]
We do not run it locally but incorporate the Uniprot annots.

**Comment by ValWood** [comment]
OK I was  bit confused because it has "TAIR:AnalysisReference:501756966" rather than a reference to say they come from the standard GOA/UniProt pipeline.

In that case I guess it is already fixed upstream...

**Comment by ValWood** [comment]
There is something else weird here. This entry has


COBL6 | AT1G09790 |   | tRNA pseudouridine synthase activity |   | UniProt | Arabidopsis thaliana | IEA | EC:5.4.99.12 |   | protein | TAIR:locus:2024377 | TAIR:AnalysisReference:501756967 | 20181205


too, which isn't from the Interpro pipeline, and has a different date.

**Comment by tberardini** [comment]
The spurious annotations were removed by our Interpro updating pipeline on 7/3/19.  They should not come back in our next release at the end of September.
