### ISSUE TITLE
Matrix: tRNA metabolism/ cell adhesion UniProtKB-KW:KW-0130 mapping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2442]
Seems to be FP for cell adhesion (or at lease I can't see any annotations to adhesion , unless this is one of those wacky functions of tRNA synthase)

AIMP1 | Aminoacyl tRNA synthase complex-interacting multifunctional protein 1 |   | cell adhesion |   | UniProt | Homo sapiens | IEA | UniProtKB-KW:KW-0130 | family not named pthr11586 | protein |   | GO_REF:0000037 | 20190601

**Comment by ValWood** [comment]
This is the paper mentioning AIMP1 and adhesion
https://www.ncbi.nlm.nih.gov/pubmed/21416500

but maybe not strong enough evidence for a mapping?

**Comment by ValWood** [comment]
...and has not been used to make a GO annotation...

**Comment by sylvainpoux** [comment]
Hi Val,
I agree this is quite indirect. I removed the KW
Thanks
Sylvain
