### ISSUE TITLE
Matrix: TAIR:sen1  tRNA metabolism/cytokinesis 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2443]
These  are annotated to 
 zygote asymmetric cytokinesis in embryo sac
representing that they are embryonic lethal. I only ready the abstract but this doesn' seem like quite the right term...clearly they don't do the first division, but this is due to problems upstream of division?

SEN1 | AT3G45590 |   | zygote asymmetric cytokinesis in embryo sac |   | TAIR | Arabidopsis thaliana | IGI | AGI_LocusCode:AT5G60230 |   | protein | TAIR:locus:2085687 | PMID:28631407TAIR:Publication:501775989 | 20170715

  | SEN2 | AT5G60230 |   | zygote asymmetric cytokinesis in embryo sac |   | TAIR | Arabidopsis thaliana | IGI | AGI_LocusCode:AT3G45590 |   | protein | TAIR:locus:2144060 | PMID:28631407TAIR:Publication:501775989 | 20170715
 
  | RNL | AT1G07910 |   | zygote asymmetric cytokinesis in embryo sac |   | TAIR | Arabidopsis thaliana | IMP |   |   | protein | TAIR:locus:2205085 | PMID:28631407TAIR:Publication:501775989 | 20170715

**Comment by tberardini** [comment]
You're suggesting removing the 'zygote asymmetric cytokinesis in embryo sac' annotations for SEN1, SEN2, and RNL and replacing with something like 'tRNA splicing' instead?  Capturing the mutant phenotype directly as a phenotype?

**Comment by tberardini** [comment]
Internal links for my reference only: (won't work for outside TAIR)
https://pubsearch.arabidopsis.org/pdfs/86264.pdf
https://pubsearch.arabidopsis.org/Display?acc=term:112765

**Comment by ValWood** [comment]
Yep, 
 Sen1 is involved in  RNA 3' end processing
Sen2 is a tRNA splicing endonuclease
RNL is a tRNA ligase

 'zygote asymmetric cytokinesis in embryo sac'  would be quite indirect since these are all required generally for normal proliferation in all cells.

TAIR:AnalysisReference:501756966
--

**Comment by lreiser** [comment]
@tberardini 
annotations to 'zygote asymmetric cytokinesis in embryo sac' have been obsoleted for these three loci. All have linked phenotypes.
AT1G07910 (RNL)  
AT3G45590 (SEN1)   
AT5G60230 (SEN2)
