### ISSUE TITLE
MAtrix Suv3 tRNA metabolism/energy generation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2445]
This is a common phenotype resulting from defects in mitochondrial gene expression:

Suv3 | Suv3 helicase |   | respiratory electron transport chain |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0229444PMID:26152302 | 20160218

**Comment by hattrill** [comment]
Exactly - comes from one paper. Removed.
