### ISSUE TITLE
Matrix:  tRNA metabolism/protein catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2447]
Only one in this intersection:

USP14 | Ubiquitin carboxyl-terminal hydrolase 14 |   | tRNA guanylyltransferase activity |   | PINC | Homo sapiens | TAS |   | family not named pthr43982 | protein |   | PMID:8579355 | 20030904

**Comment by pgaudet** [comment]
Removed annotations


GO:0004843 | thiol-dependent ubiquitin-specific protease activity |  (TAS) |   | PMID:8579355 

GO:0008193 | tRNA guanylyltransferase activity|  (TAS) |   | PMID:8579355
