### ISSUE TITLE
Review annotations to GO:0044140 negative regulation of growth of symbiont on or near host surface

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2448]

**Comment by pgaudet** [comment]
The proposal has been made to obsolete GO:0044140 negative regulation of growth of symbiont on or near host surface, see https://github.com/geneontology/go-ontology/issues/17521

There are 3 manual annotations to this term: 
2 MGI
1 UniProt-EBI

https://docs.google.com/spreadsheets/d/1NMs4nmV_kcQ_gCeE1tBHyQ4iHMXsFQjpy3isE4ymNYE/edit#gid=0

Please review and remove or rehouse your annotations as appropriate. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
@addiehl can you comment (also see #17521

**Comment by hdrabkin** [comment]
Annotations removed a while ago; cleaning up tickets

**Comment by pgaudet** [comment]
@hdrabkin can you also write what you did in the spreadsheets next time ? Otherwise I cannot compile stats (ie I can only count what people mark as reviewed). 

Thanks, Pascale

**Comment by pgaudet** [comment]
Term has been obsoleted.

**Comment by hdrabkin** [comment]
actually, you obsoleted the term before I got a chance to do spreadsheet because I was waiting for alex to respond. So the annotations were removed during a separate cleanup obsolete term qc in MGI.  That is why they never went into the spreadsheet.

**Comment by addiehl** [comment]
Wow, removed a couple of valid annotations for a term that actually made sense for the gene product in question.  Guess we aren't going to bother annotating anti-microbial peptides with what they actually do.  Whatever...

**Comment by pgaudet** [comment]
Hi @addiehl 

Sorry we didn't get your input before the term was obsoleted. I still think the terms obsoleted were redundant. 
Specifically: Out of the 3 annotations we had 2 papers annotated: 

1. **PMID:16177355**
In addition to the term that was removed ("negative regulation of growth of symbiont on or near host surface"), the gene is also annotated to 
- killing by host of symbiont cells and
- defense response to Gram-positive bacterium
Moreover, the paper mentions 'innate immune defense' as the process in which this antimicrobial peptide is involved, which is not annotated. 
We do have a term 'antifungal innate immune response'; Perhaps a better term for this activity would be 'antibacterial innate immune response'? 


2. **PMID:23006328**
also mention 'antibacterial innate immune response'

If this seems appropriate I can create that term under 'innate immune response'. 
That seems more useful to me than just a symbiotic relation-type term (which is was "negative regulation of growth of symbiont on or near host surface"). 

What do you think ? 

Thanks, Pascale

**Comment by addiehl** [comment]
PMID:16177355 does show assays that demonstrate an effect on bacterial growth, hence the annotation.  However, clearly either nobody else ever thought of annotating anti-microbial peptides with this term, or nobody has actually been annotating anti-microbial peptides, despite their biological importance.  So I don't care if the term is gone, and as you point out, we can still capture other aspects of anti-microbial peptide functionality.

And of course 'antibacterial innate immune response' seems like a good addition in analogy with 'anti fungal innate immune response'.

Thanks,
Alex
