### ISSUE TITLE
Review annotations to GO:0044130 negative regulation of growth of symbiont in host  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2449]
The proposal has been made to obsolete GO:0044130 negative regulation of growth of symbiont in host, see geneontology/go-ontology#17521

There are  manual annotations to this term:

Contributor   (Assigned by)
--
AgBase | 3
BHF-UCL | 1 -deleted
CACAO | 1
FlyBase | 8
MGI | 24

Please review and remove or rehouse your annotations as appropriate.

Thanks, Pascale

**Comment by pgaudet** [comment]
Suggested action (by annotation review requester)

**Comment by pgaudet** [comment]
https://docs.google.com/spreadsheets/d/13T9LhdmHmW7c6TYeyRJvFP6AFHT5aTQfBlFo80Ac7M4/edit#gid=0

**Comment by hattrill** [comment]
done

**Comment by pgaudet** [comment]
Term was obsoleted. Remaining annotations will be flagged by QC checks.
