### ISSUE TITLE
Matrix: HRR25 tRNA metabolism/ vesicle-mediated transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2451]
should these be "regulation of"? (upstream signalling)

HRR25 | Conserved casein kinase |   | autophagosome assembly |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | casein kinase-related pthr11909 | gene |   | PMID:26195667 | 20170623
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HRR25 | Conserved casein kinase |   | vesicle fusion with Golgi apparatus |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | casein kinase-related pthr11909 | gene |   | PMID:26195667 | 20170623

-

**Comment by srengel** [comment]
Hi @ValWood i moved the autophagosome one down to regulation.

the vesicle fusion one - there aren't regulation terms.  i have requested them:
https://github.com/geneontology/go-ontology/issues/17539

**Comment by srengel** [comment]
moved the vesicle fusion one down to regulation now that the new terms are available.  closing.
