### ISSUE TITLE
Matrix: UniProtKB-KW:KW-0819 tRNA processing /vesicle-mediated transport (-> SGD & POMBASE  primary annotations)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2452]
RTT10 | WD40 domain-containing protein involved in endosomal recycling |   | tRNA processing |   | UniProt | Saccharomyces cerevisiae S288C | IEA | UniProtKB-KW:KW-0819 | wd repeat protein pthr14344 | gene |   | GO_REF:0000037 | 20190601

RTT10 appears to be http://amigo.geneontology.org/amigo/reference/PMID:21880895

is "tRNA processing " legacy?

**Comment by sylvainpoux** [comment]
Hi Val,
I would leave the KW tRNA processing: RTT10  is "Required together with TRM7 for the methylation of the 2'-O-ribose of nucleotides at position 34 of the tRNA anticodon loop of tRNA(Phe) and tRNA(Leu(UAA))."     Source: PMID:22912484

**Comment by ValWood** [comment]
Ok that's a strange one. I will  create an exception for now but I also asked a tRNA modification expert.

v

**Comment by ValWood** [comment]
Yes, my source says "tRNA modification for sure"

Doesn't know about the endosomal transport role.

I will keep this as an exception , but keep an eye out for  confirming information for the endosome recycling role.

In the meantime I'm going to hedge my bets and convert the pombe annotation from "endosomal recycling" to the more definite "tRNA metabolism" annotation

@srengel  you might want to include the tRNA metabolism  in the SGD GO annotations?

**Comment by ValWood** [comment]
I'm using 

ISO to SGD
GO:0002130    wobble position ribose methylation
(based on teh UniProt and SGD descriptions)

**Comment by ValWood** [comment]
I also updated Trm7 to 
if you could make those more specific
/GO="aspect=F; term=tRNA 2'-O-methyltransferase activity; GOid=GO:0106050; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000000265; date=20190624"
/GO="aspect=P; term=wobble position ribose methylation; GOid=GO:0002130; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000000265; date=20190624"
(currently tRNA methyltransferase/,ethylation)

**Comment by srengel** [comment]
i've added the P GO:0002130 to RTT10, but i haven't yet found a paper that i can use for the F without a contributes_to...but i've only just started...

**Comment by ValWood** [comment]
I didn't get an F for RTT10, and I didn't see any. The person I spoke to said it was 

" a helper protein for a tRNA methylase for sure"

**Comment by srengel** [comment]
oh thanks, oops i was reading TRM7 as RTT10 in the comment about making the annotations more specific.  i'll take a look at TRM7...

**Comment by srengel** [comment]
ok added F 106050 and P 2130 to TRM7.

**Comment by ValWood** [comment]
OK I think we are done here until more info on the endosomal role...

**Comment by ValWood** [comment]
exception added for RTT10 ( & orthologs)  in the intersection with vesicle-mediated transport
