### ISSUE TITLE
Matrix: tRNA metabolism/transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2453]
This seems odd, I will come back to it

MSK1 | Mitochondrial lysine-tRNA synthetase |   | tRNA import into mitochondrion |   | SGD | Saccharomyces cerevisiae S288C | IDA |   | family not named pthr42918 | gene

This is sort of correct but I suspect the problem is because this is really "targetting" not import

**Comment by srengel** [comment]
i don't think i fully appreciate the difference between targeting and import, especially when the authors use the terms interchangeably, as in the paper whence this annotation is derived.

i changed it to GO:0008033    tRNA processing

**Comment by ValWood** [comment]
I don't think we represent this properly in GO. But  officially 'targeting' is the  movement of something to a membrane.  Karyopherins do targeting. And the SRP  targets translation to the endoplasmic membrane and to the mitochondrial membrane. Targeting is  dependent on a signal sequence (usually in the  targeted protein, but sometimes in a binding partner). 
Targeting could be part of import.
However,  "transmembrane import" is strictly defined in GO to refer to  the import across the membrane. Here the barrier must be traversed. It's a sub process of import.

I now think
GO:0016031   tRNA import into mitochondrion
is incorrectly positioned under "transmembrane transport" because strictly 
as defined
The process in which a tRNA is transported from the cytosol, into the mitochondrial matrix.

this does not  restrict  usage to crossing the membrane, it could also include targeting.
(usually the transmembrane import terms have the clause "from one side of a membrane to the other", it is the transport step after targeting).

This would make this annotation non-violating  and it does sound correct-  it is targeting the tRNA to the mitochondria.

I'll request an ontology fix, so this can be added back.

**Comment by ValWood** [comment]
was fixed.
