### ISSUE TITLE
MAtrix: tRNA metabolism /nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2455]
Ssb | small RNA binding exonuclease protection factor La |   | tRNA export from nucleus |   | RGD | Rattus norvegicus | ISO | RGD:1348902 | lupus la protein-related pthr22792 | gene |   | PMID:17308035RGD:1624291 | 20170318

This is an ISO but It seems to be from another rat protein (although I can only find one AAb?)

Anyway, from the abstract, this paper appears to be about a nuclear retention signal in Ssb,  rather than a role for Ssb itslef in export. There are other annotations too, but I didn't look at the evidence for these.

**Comment by pgaudet** [comment]
I also saw this before - @slaulederkind Shouldn't the ISO pipeline assign orthogos from other species ? These are paralogs. 

Thanks, Pascale

**Comment by ValWood** [comment]
ACtually, now I get it. This is a human annotation but RGD put a rat ID in the with field?

The human annotations are from CAFA
see
http://amigo.geneontology.org/amigo/reference/PMID:17308035


SSB | Lupus La protein |   | nucleus |   | CAFA | Homo sapiens | IDA |   | lupus la protein-related pthr22792 | protein |   | PMID:17308035 | 20161026
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | SSB | Lupus La protein |   | cytoplasm |   | CAFA | Homo sapiens | IDA |   | lupus la protein-related pthr22792 | protein |   | PMID:17308035 | 20161026
  | SSB | Lupus La protein |   | tRNA export from nucleus |   | CAFA | Homo sapiens | IMP |   | lupus la protein-related pthr22792 | protein |   | PMID:17308035 | 20161026
  | SSB | Lupus La protein |   | tRNA processing |   | CAFA | Homo sapiens | IMP |   | lupus la protein-related pthr22792 | protein |   | PMID:17308035 | 20161026

**Comment by ValWood** [comment]
RGD have their own entries for human proteins
https://rgd.mcw.edu/rgdweb/report/gene/main.html?id=1348902
That's confiusing!

**Comment by ValWood** [comment]
Actually though. I had a closer look at this paper and I think the annotation is OK. This does have a cryptic  role as a tRNA export chaperone .....
