### ISSUE TITLE
Matrix: tRNA metabolism/ nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2456]
This  paper
http://amigo.geneontology.org/amigo/reference/PMID:27385342

identifies a few exosome components and annotates to "nucleocytoplasmic transport" but  defects in processing lead to retention, so I am not sure this is correct ?

There are already quite a lot of the processing pathway that have  " nuclear accumulation" as a phenotype.

I don't thinkthe exosome has a specific role in transport though?

**Comment by ValWood** [comment]
and this one, same paper. 
MTR4 | ATP-dependent 3'-5' RNA helicase of the DExD/H family |   | poly(A)+ mRNA export from nucleus |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | atp-dependent rna and dna helicase pthr12131 | gene |   | PMID:27385342 | 20161114

**Comment by srengel** [comment]
defects in processing lead to retention at specific locations, and the mutants are annotated to 'poly(A)+ mRNA export from nucleus'.  are you wanting these to be changed to some sort of 'processing' term?

**Comment by ValWood** [comment]
Yep.
MTR4 is Tramp complex.
It has a role in processing but not in transport (although it results in transport defects)

SGD desciption is perfect:
Description
ATP-dependent 3'-5' RNA helicase of the DExD/H family; involved in nuclear RNA processing and degradation both as a component of TRAMP complex and in TRAMP-independent processes; TRAMP unwinds RNA duplexes, with Mtr4p unwinding activity stimulated by Pap2p/Air2p but not dependent on ongoing polyadenylation; contains an arch domain, with two coiled-coil arms/stalks and a globular fist/KOW domain, which has RNA binding activity and is required for 5.8S rRNA processing 2 4 5 6 7 8 9 10 11 12

(and does not mention transport)
Transport is a mis-inference from the fact that mutations result in nuclear retention. Historically nuclear retention phenotypes were often used to infer transport defects, but this predated the detailed knowledge about processing.
Hence the gene description "MTR" for mRNA transport

Unfortunately, my first comment does not mention the genes I was looking at.  I'll track this down....

**Comment by ValWood** [comment]
OK its all of the processing ones from this paper:


  | CSL4 | Exosome non-catalytic core component | Saccharomyces cerevisiae S288C | 3'-5' exoribonuclease csl4-related pthr12686 | gene | SGD | YNL232WSKI4exosome non-catalytic core subunit CSL4
  | RRP43 | Exosome non-catalytic core component | Saccharomyces cerevisiae S288C | exosome complex exonuclease ribosomal rna processing protein pthr11097 | gene | SGD | YCR035Cexosome non-catalytic core subunit RRP43
  | LOS1 | Nuclear pore protein | Saccharomyces cerevisiae S288C | exportin-t/los1 pthr15952 | gene | SGD | YKL205WRan GTPase-binding protein LOS1
  | MTR4 | ATP-dependent 3'-5' RNA helicase of the DExD/H family | Saccharomyces cerevisiae S288C | atp-dependent rna and dna helicase pthr12131 | gene | SGD | YJL050WDOB1ATP-dependent RNA helicase MTR4
  | DIS3 | Exosome core complex catalytic subunit | Saccharomyces cerevisiae S288C | ribonuclease pthr23355 | gene | SGD | YOL021CMTR17RRP44exosome catalytic subunit DIS3

**Comment by ValWood** [comment]
not LOS1

**Comment by srengel** [comment]
ok all changed to mRNA processing 6397.  CSL4 RRP43 MTR4 DIS3
