### ISSUE TITLE
Matrix: nucleocytoplasmic transport/ tRNA metabolsim UniProtKB-KW:KW-0819

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2457]
LOS1 | Nuclear pore protein |   | tRNA processing |   | UniProt | Saccharomyces cerevisiae S288C | IEA | UniProtKB-KW:KW-0819 | exportin-t/los1 pthr15952 | gene |   | GO_REF:0000037

Should tRNA processing be removed? This is a nuclear pore protein

**Comment by ValWood** [comment]
Description
Nuclear pore protein; involved in nuclear export of pre-tRNA and in re-export of mature tRNAs after their retrograde import from the cytoplasm; deletion mutation extends replicative lifespan, as does exclusion of Los1p from the nucleus in response to caloric restriction 2 3 4 5 6``

**Comment by sylvainpoux** [comment]
Hi Val,
something that would be worth checking with @marcfeuermann 
There is one sentence in the function "Involved in pre-tRNA splicing, probably by affecting the interaction of pre-tRNA with splicing endonuclease." This can be considered as kind of tRNA processing
Could you check with Marc?
Thanks
Sylvain

**Comment by ValWood** [comment]
Hi Marc,
This is a 1987 paper
https://www.ncbi.nlm.nih.gov/pubmed/3031485

but later papers just refer to it as an exporter
https://www.pnas.org/content/110/52/21042

since tRNA splicing occurs in the cytoplasm.

Early papers all it an effector of splicing, but in  ~1996 this  appears to change to "exportin" as the upstream pathway is dissected.

**Comment by marcfeuermann** [comment]
The annotation to splicing originates from 4 papers - PMID:7363329 (1980), PMID:3031485 (1987), PMID:8366091 (1993) and PMID:8725220 (1996). The only relevant experimental evidence is the accumulation of pre-tRNAs when LOS1 is deleted. But this phenotype can also be explained by the impairing of pre-tRNA nuclear export. Moreover, at least 2 of these papers "admit" that it is hard to explain how LOS1 could be involved in pre-tRNA splicing. As you said, later papers just refer to it as an exporter, so, YES, I will remove this function and the corresponding KW, and move the accumulation of pre-tRNAs data to the "dispruption phenotype" section.
