### ISSUE TITLE
Matrix: cytoplasmic translation/DNA replication

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2458]
https://www.ncbi.nlm.nih.gov/pubmed/20080954

- [x] TICRR | Treslin |   | formation of translation preinitiation complex |   | UniProt | Homo sapiens | ISS | UniProtKB:Q6DRL4 | uncharacterized pthr21556 | protein |   | GO_REF:0000024 | 20100125

- [x] ticrr | TopBP1-interacting, checkpoint, and replication regulator |   | formation of translation preinitiation complex |   | UniProt | Danio rerio | IMP |   | uncharacterized pthr21556 | protein

These should be "replication initiation complex formation" not translation initiation 

(raise disputes)

**Comment by sabrinatoro** [comment]
@ValWood 
I agree with you that the zebrafish gene should be annotated to the "replication initiation" term.
This annotation was not made at ZFIN though, so I cannot update it. I think it was made by Uniprot (we got it via our GOA load), so UniProt will have to update it.

**Comment by ValWood** [comment]
Disputes raised in protein2Go referencing this ticket
Notification of annotation dispute concerning protein Q6DRL4 (Dispute ID: 8813)
Notification of annotation dispute concerning protein Q6DRL4 (Dispute ID: 8814)
