### ISSUE TITLE
cytoplasmic translation/cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2459]
All of these seem a bit odd for eiF4e1?
The violation  that picked this up was translation/cytokinesis. This is the only single protein in that space, but the other annotatiosn look as though they will cause violations with other intersections:

eIF4E1 | eukaryotic translation initiation factor 4E1 |   | chromatin organization |   | FlyBase | Drosophila melanogaster | HMP |   |   | protein |   | FB:FBrf0135802PMID:11290718 | 20060803

  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | female meiosis chromosome segregation |   | FlyBase | Drosophila melanogaster | HMP |   |   | protein |   | FB:FBrf0135802PMID:11290718 | 20060803
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | mitotic chromosome condensation |   | FlyBase | Drosophila melanogaster | HMP |   |   | protein |   | FB:FBrf0135802PMID:11290718 | 20060803
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | mitotic cell cycle |   | FlyBase | Drosophila melanogaster | HMP |   |   | protein |   | FB:FBrf0135802PMID:11290718 | 20060803
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | regulation of cell growth |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0145121PMID:11865045 | 20060803
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | positive regulation of cell growth |   | FlyBase | Drosophila melanogaster | TAS |   |   | protein

eIF4E1 | eukaryotic translation initiation factor 4E1 |   | male germ-line cyst formation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423

  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | meiotic chromosome condensation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | spermatid differentiation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | spermatocyte division |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | male meiosis chromosome segregation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | male meiosis cytokinesis |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423

eIF4E1 | eukaryotic translation initiation factor 4E1 |   | male germ-line cyst formation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | meiotic chromosome condensation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | spermatid differentiation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | spermatocyte division |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | male meiosis chromosome segregation |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423
  | eIF4E1 | eukaryotic translation initiation factor 4E1 |   | male meiosis cytokinesis |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228090PMID:25849588 | 20150423

**Comment by ValWood** [comment]
yup.  Also causing the single violation with  cytoplasmic translation/chromatin remodelling

**Comment by hattrill** [comment]
Removed the non-translation related processses - they all were phenotype detail (mainly because it's testes-specific) that has been captured in pheno annotation .

**Comment by ValWood** [comment]
great, tks
