### ISSUE TITLE
Matrix: DNA recombination / cytoplasmic translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2462]
There are 2 annotations in this intersection. Both are from screens and look quite indirect:

- [ ] BUD27 | Unconventional prefoldin protein involved in translation initiation |   | replication-born double-strand break repair via sister chromatid exchange |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | nut2 and uxt pthr13345 | gene |   | PMID:23357952 | 20170109

- [ ] RPS16B | Protein component of the small (40S) ribosomal subunit |   | DNA recombination |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | ribosomal protein s9 pthr21569 | gene |   | PMID:23390378 | 20140609

**Comment by ValWood** [comment]
BUD27  seems to be a chaperone involved in the assembly of a number of complexes so  all of the other processes might be indirect. It also has an annotation to mediator complex from PAINT,  which is incorrect. It isn't a Mediator subunit....

**Comment by srengel** [comment]
i removed the annotation from BUD27.

**Comment by srengel** [comment]
i removed the RPS16B annotation as well.
