### ISSUE TITLE
Matrix:  BUD27 isn't a Mediator complex subunit

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2463]
BUD27	Unconventional prefoldin protein involved in translation initiation	
mediator complex		GO_Central	Saccharomyces cerevisiae S288C	IBA	
FB:FBgn0036581
MGI:MGI:106331 	
nut2 and uxt pthr13345	gene		PMID:21873635	20180412

At least in yeast this is incorrect and I'm pretty sure Mediator is universally conserved.
BUD27 is a prefoldin like chaperone..

**Comment by ukemi** [comment]
@ValWood PMID:15340084 makes a very strong case for Med10 (human synonym NUT2) being in the TRAP mediator complex. In fact it is a core component. Ping @bmeldal

**Comment by ValWood** [comment]
That isn't BUD27 ortholog though?

BUD27 is https://www.uniprot.org/uniprot/O94763 (human URI1)

Med10/Nut2 *is* core mediator...

**Comment by hattrill** [comment]
FBgn0036581 is MED10

The HCOP orthos tab at HGNC for MED10 (https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/28760) gives a good over-view of orthology calls MED10:

nut2 is the the ortholog

uri1/Bud27 only supported by PANTHER orthology call.

**Comment by ValWood** [comment]
OK so this is a Panther famly issue. Assigning to @huaiyumi 

@marcfeuermann  is it possible to block propagation to fungi in the meantime?

**Comment by ukemi** [comment]
@ValWood why the new assignment? I don't think this annotation is wrong on our end.

**Comment by ValWood** [comment]
The annotation at MGI is fine.

BUT Bud27 is not the fungal ortholog of human Med10.
yeast Med10 is the ortholog of  human Med10.

PAINT family assignment false positive , so PAINT transfer should be removed

**Comment by ukemi** [comment]
OK. Standard practice for annotation review is for us to remove our tag, once we have done the work on the ticket.

**Comment by marcfeuermann** [comment]
In the PTHR13345 family tree, node PTN004417795 including _S. cerevisiae_ BUD17, as well as a _Candida albicans_ and an _Ashbya gossypii_ protein is close to _S. cerevisiae_  NUT2 and orthologs. This node has probably to be moved. I've blocked all the annotation propagations to it.

**Comment by ValWood** [comment]
Ah sorry. I thought I did remove you. Sorry about that.

**Comment by ValWood** [comment]
removing @marcfeuermann

**Comment by pgaudet** [comment]
I'd like to check this one on PAINT14.

**Comment by ValWood** [comment]
There are still mappings to transcription terms in AmiGO.
It's very weird.

pumbe uri1 is 1:1 across species  human is URI1  cerevisiae is BUD27.

There are quite a few mappings from MED

uri1 | unconventional prefoldin chaperone involved protein complex assembly Uri1 (predicted) |   | regulation of transcription by RNA polymerase II |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:106331PANTHER:PTN000331216 more... | nut2 and uxt pthr13345 | protein |   | PMID:21873635 | 20170228

  | uri1 | unconventional prefoldin chaperone involved protein complex assembly Uri1 (predicted) |   | positive regulation of transcription by RNA polymerase II |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:106331PANTHER:PTN000331217SGD:S000006372 | nut2 and uxt pthr13345 | protein |   | PMID:21873635 | 20180412

	uri1	unconventional prefoldin chaperone involved protein complex assembly Uri1 (predicted)		mediator complex		GO_Central	Schizosaccharomyces pombe	IBA	FB:FBgn0036581
MGI:MGI:106331 	nut2 and uxt pthr13345	protein		PMID:21873635	20180412

**Comment by ValWood** [comment]
S. cerevisiae BUD27  has a similar issue:
http://amigo.geneontology.org/amigo/gene_product/SGD:S000001871

**Comment by ValWood** [comment]
@marcfeuermann  above you say "I've blocked all the annotation propagations to it." but I still see them in AMiGO?

**Comment by pgaudet** [comment]
Fixed
