### ISSUE TITLE
Matrix: cytoplasmic translation /adhesion Unirule Mapping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2465]
this is the only annotation in this intersection, so it looks odd, but I don't know how to trace the provenence

RPSA | 40S ribosomal protein SA |   | cell adhesion |   | UniProt | Homo sapiens | IEA | UniRule:UR000107182 | 40s ribosomal protein sa pthr11489 | protein |   | GO_REF:0000104 | 20190601

**Comment by ValWood** [comment]
Actually, there is one more, for 
http://amigo.geneontology.org/amigo/reference/PMID:11259264

this is the bit about adhesion in the abstract

Mouse blastocysts attached, but did not outgrow, on surfaces coated with recombinant murine HIP/RPL29. Surprisingly, soluble glycosaminoglycans including heparin, low molecular weight heparin, or chondroitin sulfate were not able to inhibit embryo attachment to HIP/RPL29-coated surfaces. These latter observations indicate that embryonic cell surface components other than HS proteoglycans can promote binding to HIP/RPL29 expressed by uterine cells.

This probably shouldn't be annotated?

**Comment by ValWood** [comment]
But much improved from last time
https://github.com/geneontology/go-annotation/issues/1510

**Comment by sylvainpoux** [comment]
Hi Val,

This case is interesting. There are several papers describing its role in other processes, such as laminin receptor in rat (PubMed=16453457 or cell adhesion (PubMed=8076763 or PubMed=11553521, paper not in Swiss-Prot but annotated by RGD)

There are also 2 papers in X.laevis: PubMed=15780176 and PubMed=16059908

I therefore think it is fine to keep this function and KW in vertebrate entries

It looks like proteins such as ribosomal subunits and histones can play a role in extracellular compartments, possibly as cleavage products

Regarding RPL29, I would not have annotated this paper. As you say, there is no real biological relevance. The case of RPSA is different as different papers confirm this possible role in cell-cell adhesion

Thanks

Sylvain

**Comment by ValWood** [comment]
Hi Sylvain,

I'm questioning the ribosomal proteins 
RPSA and RPL29.

is there any evidence for these having a functional role in adhesion (the papers I looked at above refer to the lamin receptor not to ribosomal proteins?)

**Comment by sylvainpoux** [comment]
Hi Val,
for RPL29, I would ask MGI to delete the GO annotation

For RPSA, I would keep it given the different papers, including the RGD paper mentionned. These papers talk aboute RPSA, which is also named 'laminin receptor' and they describe a role in cell adhesion

DE   RecName: Full=40S ribosomal protein SA {ECO:0000255|HAMAP-Rule:MF_03016};
DE   AltName: Full=37 kDa laminin receptor precursor {ECO:0000255|HAMAP-Rule:MF_03016};
DE            Short=37LRP {ECO:0000255|HAMAP-Rule:MF_03016};
DE   AltName: Full=37/67 kDa laminin receptor {ECO:0000255|HAMAP-Rule:MF_03016};
DE            Short=LRP/LR {ECO:0000255|HAMAP-Rule:MF_03016};
DE   AltName: Full=67 kDa laminin receptor {ECO:0000255|HAMAP-Rule:MF_03016};
DE            Short=67LR {ECO:0000255|HAMAP-Rule:MF_03016};
DE   AltName: Full=Colon carcinoma laminin-binding protein;
DE   AltName: Full=Laminin receptor 1 {ECO:0000255|HAMAP-Rule:MF_03016};
DE            Short=LamR {ECO:0000255|HAMAP-Rule:MF_03016};

Thanks

Sylvain

**Comment by ValWood** [comment]
Thanks!

**Comment by ValWood** [comment]
Assigning to @ukemi  for the mouse annotation

**Comment by ValWood** [comment]
for RPSA I found this fairly recent review
https://www.ncbi.nlm.nih.gov/pubmed/26146125

The abtract seems to suggest that  the extracellular role is pathogenic and associated with metastatases"

They say
"further thought to contribute to cellular migration and invasion"

RPSA is also increasingly found to be important in other pathologies, including microbial infection, neurodegenerative disease and developmental malformations. I

I am not convinced that these are evolved functions but I will make an exception and put it in my "revisit this later" folder

**Comment by ukemi** [comment]
It looks like RPL29 really might bind heparin during pregnancy based on the in vitro study above and by expression data. Some of the papers are old, but I'm old too.
See the section on HIP/RPL29 in     PMID:17766150.
Also see PMID:25735597. This paper suggests that the matrix rules may not hold well for ribosomal proteins.

**Comment by hdrabkin** [comment]
Just looking at Rpsa in mouse; multiple cc annotations to synapse  from SynGO based on a 
 Using these methods (HTP) , we determined the relative expression of 2159 proteins and 1564 phosphorylation sites in PSD preparations from murine cortex, midbrain, cerebellum, and hippocampus; Cell fractionation; maybe contamination with ribosomes in brain membrane fractions? (could be membrane bound polysomes ).

**Comment by ValWood** [comment]
The matrix rules can be whatever we want them to be. Valid exceptions are added to the rules, and many intersections have some specific exceptions. 

For example  there is already a ribosomal protein  exception for
https://www.ncbi.nlm.nih.gov/pubmed/25735597
"more than a dozen of ribosomal proteins have been found to activate the tumor suppressor p53 pathway in response to ribosomal stress"

 The issue with this particular conjecture one is that, despite multiple papers I don't see any evidence that these interactions are functionally relevant....It is well established that  ribosomal proteins and histones proteins are often found outside the cell.  We find them in all the extracellular HTP screens. At >~200,000 proteins   per cell this isn't surprising. 
In fact they are  major contaminant in every mass spec preparation, so any role  that is not based on a really thorough investigation is really difficult to establish. Just binding to anything is going to need a lot of additional support.

Considering the constraints on their evolution ( yeast and human ribosomal histone and ribosomal proteins   highly similar or even identical). It is more difficult to envisage that  their binding to cell surface molecules is a _bona fida_ adhesion process.

This abstract continues:
In addition, these ribosomal proteins are involved in various physiological and pathological processes. This review is composed to overview the current understanding of how ribosomal stress provokes the accumulation of ribosome-free ribosomal proteins, as well as the ribosome-independent functions of ribosomal proteins in tumorigenesis, immune signaling, and development. 

SO I'll look into this review to see if I can find any  papers  which are  functionally relevant for ribosome/adhesion.

Note that clearly ribosomes *affect* growth. TOR signalling regulates translation. However I wouldn't annotate the ribosomes themselves to "regulation of growth",  unless they are shown independently to have some way of controlling growth (as in the p53 example) because ribosomes  are just translating according to the input from the signalling pathway and this happens through the initiation and or elongation factors not the ribosomes themselves.

**Comment by ValWood** [comment]
This review 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4481666/

doesn't mention adhesion, even though tit is trying to make a case for the extra-ribsomal functions. It's interesting that they list disease mutants and tumourigenesis as extra-ribosomal functions (remove these and there is very little left), and that most of these observations they list,  apart from the obviously correct ones,  are from single publications.....

**Comment by ukemi** [comment]
No I know it doesn't mention adhesion. It was there to support that I think we need to be cautious with the rules regarding ribosomal proteins.

**Comment by ValWood** [comment]
I know, as I said all rules can have exceptions if there is supporting evidence. The high-level rules are only a starting point to reduce the amount of work to create the rules. Then you move down the intersections to add scientifically robust (but very specific) exceptions.

I already have exceptions for translation, but for ribosomal proteins the evidence doesn't look good, particularly for adhesion.

**Comment by ValWood** [comment]
I raised a  dispute for 


PINC | P08865 | RPSA | involved_in | GO:0007155 | cell adhesion | ECO:0000303(NAS) | ECO:0000303 | (NAS) |   | PMID:2970671
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ECO:0000303 | (NAS)

which removes one issue.

**Comment by ValWood** [comment]
Still dubious about 
https://europepmc.org/article/MED/11259264#impact
and adhesion since it was published in 2001 and there are no "supporting" citations reported so far, and considerin g the expression levels of ribosomal proteins, but I'll close this for now.
