### ISSUE TITLE
Matrix: mitotic chromosome segregation /cytoplasmic translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2466]
eIF4E1 | eukaryotic translation initiation factor 4E1 | Drosophila melanogaster |   | protein | FB | 0260/090587/11

This is a . screen and it identifies quite a few  upstream things (others will probably pop out in other intersections).

They don't study these any further and they say:

A simple explanation for the high representation of these factors is that the observed mitotic defects are indirectly caused by a lack of transcription, splicing, or translation of mitotic regulators. However, it is also possible that at least some of these genes might directly regulate mitosis in a manner independent of their functions in transcription, mRNA splicing, or translation.

Since  most are likely indirect effects  I wouldn't make these annotations from this screen.

**Comment by hattrill** [comment]
Removed: phenotype

**Comment by ValWood** [comment]
Ah this is the same gene /paper. I thouhg it would pop up again!

**Comment by hattrill** [comment]
There were two papers - equally nuked!
