### ISSUE TITLE
Matrix: cytoplasmic translation /protein maturation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2467]
this mitochondrial inner membrane protease is annotated to cytoplasmic translation?

AFG3 | Mitochondrial inner membrane m-AAA protease component |   | cytoplasmic translation |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr43655 | gene |   | PMID:15328540 | 20121218

**Comment by srengel** [comment]
removed. 
good catch @ValWood i think that one must have been a typo - AFG3 is not even mentioned in the paper attached to that annotation.
