### ISSUE TITLE
Matrix: Eif4c mitochondrion organization / cytoplasmic translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2469]
This is causing the violation:

- [x] EIF4G1 | Eukaryotic translation initiation factor 4 gamma 1 |   | mitochondrion organization |   | ParkinsonsUK-UCL | Homo sapiens | IMP |   | eukaryotic translation initiation factor 4 gamma pthr23253 | protein |   | PMID:18426977

I think this annotation comes from the mitochondrial membrane depolarization assay. I'm not sure that this isn't a readout to detect reduced mitochondrial activity. ...but in a normal cell 
EIF4G1 doesn't really seem to regulate "mitochondrial organization" even if it does regulate some of the metabolic pathways?
also

- [x] EIF4G1 | Eukaryotic translation initiation factor 4 gamma 1 |   | positive regulation of cell population proliferation |   | ParkinsonsUK-UCL | Homo sapiens | IMP |   | eukaryotic translation initiation factor 4 gamma pthr23253 | protein |   | PMID:18426977 | 20161006

This one is not for direct annotation (only children should be used to indicate  growth of a specific cell-type population).

**Comment by RLovering** [comment]
annotations removed and asked @BarbaraCzub to review the annotations associated with this paper

**Comment by ValWood** [comment]
tks!
