### ISSUE TITLE
Matrix:  cytoplasmic translation/ protein targeting . (PAINT)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2471]
PAINT annotation looks odd based on description. Will . do more digging

LHS1 | Molecular chaperone of the endoplasmic reticulum lumen |   | cytoplasmic translation |   | GO_Central | Saccharomyces cerevisiae S288C | IBA | PANTHER:PTN002500129SGD:S000001106 | heat shock protein 70kda pthr19375

**Comment by ValWood** [comment]
OK, I don't think annotations can be transferred between 

LHS1 and  SSZ1 becasue they are in different locations

**Comment by marcfeuermann** [comment]
Fixed. Only the ribosome-bound chaperones have now the term "cytoplasmic translation".
