### ISSUE TITLE
Tagging InterPro in issues

### ISSUE THREAD

**Issue by happy-lorna** [geneontology/go-annotation#2472]
To minimise email traffic we are changing our "watch" settings here at InterPro. For anything that requires InterPro attention, please now tag the curators to ensure it gets picked up.

@EBI-Hsinyu 
@typhainepl 
@lsw26
@sarach06 
@alexbateman1

Thanks!

**Comment by ValWood** [comment]
Sorry ;)

**Comment by ValWood** [comment]
Tagging the people who submit the most Interpro mapping tickets so that they know

@bmeldal 
@hattrill 
@vanaukenk 
@pgaudet 
@Antonialock 
@ukemi 

Do we just pick one of you randomly? or tag all 3 of you?

**Comment by Antonialock** [comment]
is it possible to have these tags as an option in the 'labels' section? I'm never going to remember this!

**Comment by ValWood** [comment]
you can bookmark this page for contacts
https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
(I'm assuming the file is up to date)

**Comment by bmeldal** [comment]
How am I submitting Interpro mapping tickets? I don't remember doing it consciously so must be through a pipeline. I always ignore all Interpro tickets as I have no access to their DB. 

NB: we manually map certain sequence features to Interpro but they only go into our xml and tab-del files but not in the GPAD.

**Comment by ValWood** [comment]
No worries @bmeldal  I  thought I saw your name on one of the recent submissions?

**Comment by ValWood** [comment]
ha it was this ticket, it is in the "open list" withthe interpro mapping filter, but it has been there since 2106.
https://github.com/geneontology/go-annotation/issues/1340
anything to do here?

**Comment by happy-lorna** [comment]
@ValWood  probably safest to tag all of us so that somebody picks it up even across holidays etc.
@Antonialock I'm sorry, I know it is an overhead to have to tag us, but so little of the traffic is relevant to us that actually things get lost in it.
I had hoped there was a way to automatically assign tags based on labels, but it seems not :(
I will keep the list in the original message at the top up-to-date by editing it so you just have to copy and paste from there for an InterPro relevant things.
On that topic, can somebody please invite @typhainepl to gene ontology organisation so I can add her to the list too (I don't seem to be able to invite her).

**Comment by ValWood** [comment]
don't worry @Antonialock  if you forget  who to tag just assign to InterPro and somebody will pick it up and assign fairly quickly
