### ISSUE TITLE
Matrix: Rpl17 cell cycle transition/ cytoplasmic translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2474]
Rpl17 | ribosomal protein L17 |   | nucleus |   | MGI | Mus musculus | ISO | RGD:1303019 | 60s ribosomal protein l17 pthr11593 | protein
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Using the mouse annotation because the rat one did not come up in the intersection for some reason (possibly a synching issue), but the primary annotation is rat.

This doesn't appear to demonstrate a role in the  G1 or Go/S-phase transition, it just refers to an increased number of cells in 
G0/G1. Indicating some sort of block.
Knockdown of ribosomal proteins often causes a cell cycle block because  they cause problems (reduced translation) with knock-on effects  (reduced levels of critical proteins) to activate cell cycle checkpoints resulting in a block. But this is an abnormal (pathological situation) for the cell, not a normal process.

They use this to infer a role in inhibiting proliferation, but it is just a readout. Proliferation is growth+ division. I think they are trying to get a the growth aspect here? 
It's odd though that a ribosomal protein is implicated in the inhibition of growth since  
translation is required for growth, but I won't adress that issue here.

BACKGROUND: Carotid intima-media thickening is associated with increased cardiovascular risk in humans. We discovered that intima formation and cell proliferation in response to carotid injury is greater in SJL/J (SJL) in comparison with C3HeB/FeJ (C3H/F) mice. The purpose of this study was to identify candidate genes contributing to intima formation. METHODS AND RESULTS: We performed microarray and bioinformatic analyses of carotid arteries from C3H/F and SJL mice. Kyoto Encyclopedia of Genes and Genomes analysis showed that the ribosome pathway was significantly up-regulated in C3H/F in comparison with SJL mice. Expression of a ribosomal protein, RpL17, was >40-fold higher in C3H/F carotids in comparison with SJL. Aortic vascular smooth muscle cells from C3H/F grew slower in comparison to SJL. To determine the role of RpL17 in vascular smooth muscle cell growth regulation, we analyzed the relationship between RpL17 expression and cell cycle progression. Cultured vascular smooth muscle cells from mice, rats, and humans showed that RpL17 expression inversely correlated with growth as shown by decreased cells in S phase and increased cells in G(0)/G(1). To prove that RpL17 acted as a growth inhibitor in vivo, we used pluronic gel delivery of RpL17 small interfering RNA to C3H/F carotid arteries. This resulted in an 8-fold increase in the number of proliferating cells. Furthermore, following partial carotid ligation in SJL mice, RpL17 expression in the intima and media decreased, but the number of proliferating cells increased. CONCLUSIONS: RpL17 acts as a vascular smooth muscle cell growth inhibitor (akin to a tumor suppressor) and represents a potential therapeutic target to limit carotid intima-media thickening.

**Comment by slaulederkind** [comment]
Most of the data we pull out of the literature is a "a readout".  Why am I seeing a lot of "just a readout" for the reason to eliminate annotations people don't like?

**Comment by ValWood** [comment]
Apologies, I pasted the wrong annotation.

Also, rat appears to have no annotations in this intersection except 


	Rpl24	ribosomal protein L24		biological_process		RGD	Rattus norvegicus	ND		60s ribosomal protein l24 pthr10792	gene		RGD:1598407	20160225

so the problem the annotations  here aren't originating from rat.
I will follow up on the problems separately.

The concept of an "experimental readout" is described very nicely in:

Best Practices in Manual Annotation with the Gene Ontology.https://www.ncbi.nlm.nih.gov/pubmed/27812934
by @sylvainpoux and @pgaudet 

cheers, and apologies for the confusion.
val
