### ISSUE TITLE
matrix: DNA replication/ribosome biogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2475]
I have some things allowed in this intersection, but this evidence sounds weak (or non-existant), and it's quite old. The abstract only says "no cells were in S phease, but thats becasue arrest is either in G1 or G2?

NOP7 | Component of several different pre-ribosomal particles |   | cell cycle DNA replication |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | pescadillo - related pthr12221 | gene |   | PMID:12110181 | 20131010

@mah11  thoughts?

**Comment by srengel** [comment]
i have removed the NOP7/YPH1 annotation.

**Comment by ValWood** [comment]
OK I wasn't so confident about this not being somehow related to replication because there is a precedent (Rix 1 complex), although I don't know how direct this is I made an exception.

However this particular paper didn't really seem to imply a direct role

**Comment by ValWood** [comment]
OK I can't find any mention other than this 2002 paper.

LAter papers don't mentin this role. A  2005 paper 
says

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1291219/
Nop7 and Pescadillo are implicated in DNA replication or cell proliferation

referring only to this paper. I can't find anything else- so based on this  I would be inclined not to annotate to DNA replication. I think that will be OK.
