### ISSUE TITLE
Matrix: Cdt1 DNA replication & chromosome segregation/cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2476]
Actually the chromosome segregation ones seem to be OK. I will make an exception for pthr28637. I didn't know Cdt1 had a role at the kinetochore. I'm not sure that this is true for yeast, will check this one out further....

However, this paper doesn't appear to mention mediator?

- [x] CDT1 | DNA replication factor Cdt1 |   | positive regulation of mediator complex assembly |   | CAFA | Homo sapiens | IDA |   | family not named pthr28637 | protein |   | PMID:11125146 | 20160725

[Protein2GO] Notification of annotation dispute concerning protein Q9H211 (Dispute ID: 8833)

**Comment by ValWood** [comment]
note to self
PMID: 22581055 
PMID: 30154187

**Comment by ValWood** [comment]
Drosophila CDT1 is annotated to cytokinesis from this paper
http://flybase.org/reports/FBrf0184073.html
but this paper doesn't seem to mention CDT1 (aka double parked)

**Comment by ValWood** [comment]
also if FB is removed there are some PAINT annotations to deal with.  Tagging MArc.

**Comment by hattrill** [comment]
Removed doubled parked (dup) as it was used as a genetic tool to halt progression through replication.

**Comment by hattrill** [comment]
So now no support for PAINT:PTN002008627 mitotic cytokinesis, so please can you remove this @marcfeuermann ?

**Comment by marcfeuermann** [comment]
I've cleaned the annotation and only kept the propagation of DNA replication-related terms.
