### ISSUE TITLE
Matrix: ribosome biogenesis/  carbohydrate metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2478]
this seems to be  indirect 
SNF6 | Subunit of the SWI/SNF chromatin remodeling complex |   | maturation of LSU-rRNA |   | SGD | Saccharomyces cerevisiae S288C | IMP |   |   | gene |   | PMID:23437238 | 20160224this doesn't seem right from this paper, but I only read the abstract.

 at least from reading the abstract

SNF6 | Subunit of the SWI/SNF chromatin remodeling complex |   | positive regulation of transcription by RNA polymerase I |   | SGD | Saccharomyces cerevisiae S288C | IMP |   |   | gene |   | PMID:23437238 | 20160224

would seem to cover it?

**Comment by ValWood** [comment]
"sucrose catabolic process" for SNF2,5,6 also seems a bit indirect.
PMID:6392017

**Comment by ValWood** [comment]
could 

GLC7 | Type 1 S/T protein phosphatase (PP1) catalytic subunit |   | glycogen metabolic process |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | serine/threonine protein phosphatase pthr11668 | gene |   | PMID:1660885 | 20010118

and

GLC7 | Type 1 S/T protein phosphatase (PP1) catalytic subunit |   | rRNA processing |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | serine/threonine protein phosphatase pthr11668 | gene |   | PMID:12837249 | 20030805

be moved to "regulation of ..." 

this would make the]m non-violating

**Comment by ValWood** [comment]
Mofre sucrose catabolic process

SWI1 | Subunit of the SWI/SNF chromatin remodeling complex |   | sucrose catabolic process |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | rbp-related pthr13964 | gene |   | PMID:1339306 | 20120301

**Comment by srengel** [comment]
moved this one down to regulation: GLC7 | glycogen metabolic process 

deleted this one : GLC7 | rRNA processing

**Comment by srengel** [comment]
i removed the SWI1 and SNF2 annotations to sucrose catabolic process.

**Comment by ValWood** [comment]
Hi Stacia,  were SNF2,5,6 included?
cheers
val

**Comment by srengel** [comment]
oops @ValWood i had missed those, but got them now and think i have deleted all sucrose catabolism from SWI/SNF subunits.
