### ISSUE TITLE
Matrix: ribosome biogenesis/cell adhesion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2480]
Following up on the "everything is involved in adhesion" hypothesis

Aatf | apoptosis antagonizing transcription factor |   | cell adhesion |   | MGI | Mus musculus | IMP | MGI:MGI:2176283 | aatf protein apoptosis antagonizing transcription factor pthr15565 | protein |   | MGI:MGI:1927250PMID:11071758 | 20020726

I only read the abstract, it's an early paper on this transcription factor (the first)

Little is known about the genetic control of preimplantation development. We have isolated, characterized, and mutated a previously undescribed mouse gene, Traube (Trb), essential for preimplantation development. Similar protein coding sequences are found in rats, humans, and yeast. The TRB protein contained two amino-terminal acidic domains, a leucine zipper, and three putative nuclear localization signals. The Trb gene was expressed at low levels ubiquitously early in development and became restricted to the liver and the central nervous system from E11.5 onward. Myc-tagged TRB protein was localized to the nucleus, and in a large proportion of the cells to the nucleoli. The Trb mutant embryos halted in development at the compacted morula stage at E2.5. At E3.5 they started to decompact and a day later they disintegrated and died. The observed defect was cell autonomous, as mutant cells failed to participate in the formation of chimeric embryos. The Trb mutant embryos showed a 50% reduction of the total cell number. The mutant embryos exhibited a paucity of ribosomes, polyribosomes, and rough endoplasmic reticulum. This paucity of ribosomes together with the localization of TRB to the nucleoli, the site of ribosome synthesis, suggests that TRB is involved in the synthesis of ribosomes. 

I searched this paper and I couldn't find any mention of adhesion
?

**Comment by ukemi** [comment]
I'll have a look. Morula compaction is cell adhesion.

**Comment by ValWood** [comment]
OK, in that case this would be regulating cell adhesion. I can add an exception for this (but regulation of...) might be better.

Currently I am only assessing  if both annotations to the process are direct (more likely to be OK together  if one or both annotations are regulation because this usually indicates signalling)
..I doubt that I will ever attempt to do signalling...

**Comment by ukemi** [comment]
From the annotated paper, it looks like there is no problem with protein levels of cell adhesion complex components, but the complexes fail to function correctly. I'm going to leave these as they will get a causally_upstream_of_or_within qualifier when we import these as GO-CAMs. I'm also going to look at the other papers we have for this gene to see if I can get a better handle on exactly how this gene functions.

**Comment by ValWood** [comment]
exception added. Please let me know if you find out any more...
