### ISSUE TITLE
Matrix: ribosome biogenesis/cell adhesion .

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2481]
C. elegans

byn-1 |   |   | cell adhesion |   | UniProt | Caenorhabditis elegans | IEA | UniProtKB-KW:KW-0130 |   | gene |   | GO_REF:0000037 | 20190105

human
BYSL | Bystin |   | cell adhesion |   | PINC | Homo sapiens | TAS |   | bystin pthr12821 | protein |   | PMID:9560222 | 20030904

  | BYSL | Bystin |   | female pregnancy |   | PINC | Homo sapiens | TAS |   | bystin pthr12821 | protein |   | PMID:9560222 | 20030904

There is also a mouse ISS, but I can't trace any experimental evidence for this SPKW or PINC annotation (this one looks very familiar, but I can;t find an exitng ticket)

**Comment by sylvainpoux** [comment]
Hi Val,
could you assign this to @magrane? Curators in her team are in charge of C.elagans curation.
Thanks
Sylvain

**Comment by ValWood** [comment]
done

**Comment by magrane** [comment]
Hi Val, 

For C.elegans byn-1, I've removed the "Cell adhesion" keyword from the UniProt record as there's no evidence for involvement of this protein in cell adhesion. This will allow for removal of the associated IEA GO term "cell adhesion" which is based on the keyword.

For human BYSL, I've removed the PINC annotations for "cell adhesion" and "female pregnancy". These were based on data in PMID:9560222 which shows that bysin binds the cell adhesion protein trophinin but bystin does not seem to have any direct involvement in cell adhesion.

For mouse, there are still 2 ISS annotations of "cell adhesion" from MGI.

Michele

**Comment by pgaudet** [comment]
@hdrabkin Can you please file the mouse ISS annotations ?

**Comment by hdrabkin** [comment]
I can only find one mouse ISS
The paper is a comparison of syntenic regions between orthologous genes in yeast and mouse .
"he product of the BYSL gene was identified as a part of a cell adhesion molecule complex (Pack et al. 1998)"  THAT reference is Assignment of the bystin gene BYSL to human chromosome band 6p21.1 by in  situ hybridization. No functional data.   I have removed the annotation

**Comment by ValWood** [comment]
Great. Thanks

NOte, There is no synteny between yeast and mouse (there  is not even any synteny between pombe and S. cerevisiae)

**Comment by hdrabkin** [comment]
Yes I said that a little bass-ackward
