### ISSUE TITLE
Matrix: ribosome metabolic process/ cofactor metabolic process (Question?)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2482]
Hi @pgaudet  wasn't there a decision at some point that we didn't annotate methyltransferases to " S-adenosylmethionine biosynthetic process" because this is just the  interconverting methyl donor ?
(this is actually the only one I came across so far)

METTL16 | RNA N6-adenosine-methyltransferase METTL16 |   | S-adenosylmethionine biosynthetic process |   | UniProt | Homo sapiens | IDA |   | sam-dependent methyltransferase pthr13393 | protein |   | PMID:28525753 | 20181030

  | METTL16 | RNA N6-adenosine-methyltransferase METTL16 |   | S-adenosylmethionine biosynthetic process |   | UniProt | Homo sapiens | IDA |   | sam-dependent methyltransferase pthr13393 | protein |   | PMID:30197297 | 20181030

**Comment by ValWood** [comment]
There is also PAINT nmapping
rmt2 | N-methyltransferase (predicted) |   | S-adenosylhomocysteine metabolic process |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001282244RGD:2659 | family not named pthr32379 | protein |   | PMID:21873635

**Comment by pgaudet** [comment]
@sylvainpoux Can you look at the 'S-adenosylmethionine biosynthetic process' annotations for Q86W50?

**Comment by sylvainpoux** [comment]
Hi Pascale,

I would say that the S-adenosylmethionine biosynthetic process is correct as this methyltransferase directly regulates expression of MAT2A. 

As it represents the main role of this enzyme and as there is no term for regulation of S-adenosylmethionine biosynthetic process, it is the only way to capture this. Removing this annotation would remove the most important process regulated by this protein

Sylvain

**Comment by ValWood** [comment]
OK got it  rmt2 is *directly* regulating SAM biosynthesis via the regulation of MAT2A splicing.

 ![mettl16](https://user-images.githubusercontent.com/7359272/60172365-6eefa100-9804-11e9-946b-146f76d89212.jpg)


To capture the contribution of METTL16 in the methylation cycle I would probably do:

METTL16 
rRNA (adenine-N6-)-methyltransferase activity has_input MAT2A *
part_of "GO:1905869   "negative regulation of 3'-UTR-mediated mRNA stabilization"
PMID:28525753 

(i.e methylates the MAT2A mRNA and  destabilizes it for breakdown)

AND
METTL16 
GO:0003729   mRNA binding has_input MAT2A*
part_of "GO:0070935    3'-UTR-mediated mRNA stabilization",
part_of "NTR positive regulation of S-adenosylmethionine biosynthetic process"
PMID:28525753 

(i.e binds the MAT2A mRNA and  allows it to translate SAM synthetase )


This makes it clear that METTL16  is performing 2 separate activities, and one is  regulates S-adenosylmethionine biosynthetic process
via the control of MAT2A expression.

I thought the annotation was from the reaction
adenosine in U6 snRNA + S-adenosyl-L-methionine = H+ + N6-methyladenosine in U6 snRNA + S-adenosyl-L-homocysteine
(which would be incorrect anyway because its consuming  S-adenosyl-L-methionine)


(* or could use the Ensembl transcript ID. At Pombase we just use the gene ID which isn't ideal, but the substrate type can be inferred from the term)

**Comment by sylvainpoux** [comment]
Thanks I will use GO:1905869 term as well,
regarding GO:0006556, I used the qualifier acts_upstream to indicate that it is not directly part of the biosynthesis

**Comment by ValWood** [comment]
This sounds like a good use of "acts_upstream_of"

I wonder instead of 
part_of "GO:0070935 3'-UTR-mediated mRNA stabilization",
if the process  for this one should be
GO:0048026    positive regulation of mRNA splicing, via spliceosome

(the stabilization terms bother me a bit because they are  just an output of the enhanced splicing, so it lead to inconsistent annotation   a similar issue was identified with "protein stabilization, and  the proposal was obsoletion https://github.com/geneontology/go-ontology/issues/16360)

The "positive regulation of mRNA splicing, via spliceosome" 
give the more correct parent to 
"positive regulation of gene expression"
