### ISSUE TITLE
Matrix: ribosome biogenesis/ conjugation with cellular fusion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2483]
very old indirect

SSF2 | Protein required for ribosomal large subunit maturation |   | conjugation with cellular fusion |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | peter pan-related pthr12661 | gene |   | PMID:7748491 | 20190409

LSG1 | Putative GTPase involved in 60S ribosomal subunit biogenesis |   | conjugation with cellular fusion |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr45709 | gene |   | PMID:10669874 | 20021011

LSG1 | Putative GTPase involved in 60S ribosomal subunit biogenesis |   | conjugation with cellular fusion |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr45709 | gene |   | PMID:10669874 | 20021011

  | LSG1 | Putative GTPase involved in 60S ribosomal subunit biogenesis |   | ascospore formation |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr45709 | gene |   | PMID:10669874 | 20021011

**Comment by srengel** [comment]
i have removed these old, indirect annotations from SSF2 and LSG1.  closing.
