### ISSUE TITLE
Matrix: ribosome biogenesis /cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2484]
indirect downstream  phenotype?

 - [ ] BUD23 | Methyltransferase that methylates residue G1575 of 18S rRNA |   | cellular bud site selection |   | SGD | Saccharomyces cerevisiae S288C | HMP |   | methyltransferase-related pthr12734 | gene |   | PMID:11452010 | 20021010

- [ ]  NOP15 | Constituent of 66S pre-ribosomal particles |   | actomyosin contractile ring assembly |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr46754 | gene |   | PMID:14657029 | 20040521

- [ ]  BUD20 | C2H2-type zinc finger protein required for ribosome assembly |   | cellular bud site selection |   | SGD | Saccharomyces cerevisiae S288C | HMP |   | family not named pthr46095 | gene |   | PMID:11452010 | 20021010
- [ ] GLC7 will be fixed by moving down to "regulation of cell budding"

**Comment by srengel** [comment]
i have removed the BUD23 and BUD20 annotations to cellular bud site selection.

**Comment by srengel** [comment]
i have removed the NOP15 annotation to actomyosin contractile ring assembly.

**Comment by srengel** [comment]
the GLC7 one i fixed by moving down to "regulation of cell budding"
