### ISSUE TITLE
Matrix: ribosome biogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2485]
This annotation is being transferred from a cytoplasmic ribosomal protein (which has a role in ribosome biogenesis) over to the mitochondrial ribosomal protein in the same family

MRPS9 |   |   | maturation of SSU-rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA) |   | GO_Central | Candida albicans | IBA | PANTHER:PTN000490829SGD:S000002241SGD:S000004751 | ribosomal protein s9 pthr21569 | gene_product |   | PMID:21873635 | 20170228

**Comment by ValWood** [comment]
[Protein2GO] Notification of annotation dispute concerning protein Q14CZ7 (Dispute ID: 8853)

**Comment by marcfeuermann** [comment]
I've restricted the propagation to the cytoplasmic ribosomal protein.
