### ISSUE TITLE
Matrix: ribosome biogenesis /  energy generation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2486]
- [x] FASTKD2 | FAST kinase domain-containing protein 2, mitochondrial |   | cellular respiration |   | UniProt | Homo sapiens | ISS | UniProtKB:Q14CZ7 | fast leu-rich domain-containing pthr21228 | protein |   | PMID:20869947 | 20101208

This is upstream of respiration. It's involved in mitochondrial ribosome assembly. Cellular respiration is a phenotype.

(The object in the ISS is  to itself)

**Comment by ValWood** [comment]
I disputed the one above. Also spotted 

HPA | Q9NYY8 | FASTKD2 |   | GO:0045171 | intercellular bridge | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | GO_REF:0000052 |   |   |   |   |   |   |   |  
ECO:0000314 | (IDA)

which seems wrong since this is a mitochondrial protein and intracellular bridge is a  cytokinesis structure. However the system will not let me dispute this one ? @pgaudet

**Comment by ValWood** [comment]
[Protein2GO] Notification of annotation dispute concerning protein Q9NYY8 (Dispute ID: 8893)
for the first one

**Comment by pgaudet** [comment]
Deleted. You can close the dispute. 

Thanks, Pascale

**Comment by ValWood** [comment]
did you do FASTKD2 too?

**Comment by ValWood** [comment]
intercellular bridge
I can't appear to disput that

**Comment by ValWood** [comment]
@pgaudet  I can't dispute the "intercellular bridge" annotation for some reason. 
DO you have the authority to delete this?

**Comment by pgaudet** [comment]
I'll contact HPA.

**Comment by pgaudet** [comment]
Emailed Emma Lundberg

**Comment by ValWood** [comment]
Closing, the annotation is gone
