### ISSUE TITLE
Matrix: ribosome biogenesis/ lipid metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2488]
TOR2 has

TOR2 | PIK-related protein kinase and rapamycin target |   | 1-phosphatidylinositol 4-kinase activity |   | UniProt | Saccharomyces cerevisiae S288C | IEA | EC:2.7.1.67 | ataxia telangiectasia mutated atm -related pthr11139 | gene |   | GO_REF:0000003 | 20190601

 and so gets annotated to inbositol and lipid metabolism. ALthough tor2 is related, it doesn't act on myo-inositol physiologically AFAIK, it's just a serine/threonine protein kinase

**Comment by ValWood** [comment]
This cropped up again on ATM kinase, gets "fatty acid metabolism" which seems weird
ATM | Serine-protein kinase ATM |   | phosphatidylinositol-3-phosphate biosynthetic process |   | GOC | Homo sapiens | IEA | GO:0016303 | ataxia telangiectasia mutated atm -related pthr11139 | protein |   | GO_REF:0000108 | 20190601

**Comment by sylvainpoux** [comment]
Hi Val,

regarding TOR2, there is a paper (PMID:8846782) describing the 1-phosphatidylinositol 4-kinase activity. If you think that it is erroneous, may I ask you to contact Ivo (@pedruzzi )?

For ATM, automatic annotation to phosphatidylinositol-3-phosphate biosynthetic process is not surprising as ATM is part of the PI3/PI4-kinase family.

Thanks

Sylvain

**Comment by ValWood** [comment]
@pedruzzi  what do you think?

These are all members of the same superfamily with different specificities?
https://www.pombase.org/gene_subset/interpro:IPR036940

I don't  know  that phosphatidylinositol is physiologically relevant for  ATM or TOR in vivo (this would be other family members (pik1,3 and stt4 in pombe)

@Antonialock may know.

**Comment by ValWood** [comment]
Annotations appear to have been removed, closing
