### ISSUE TITLE
Matrix: lipid metabolism/ ribosome biogenesis . UniProtKB-KW:KW-0698

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2489]
I'm going to have a [poke around to find any evidence

SIRT1 | NAD-dependent protein deacetylase sirtuin-1 |   | rRNA processing |   | UniProt | Homo sapiens | IEA | UniProtKB-KW:KW-0698 | chromatin regulatory protein sir2 pthr11085 | protein |   | GO_REF:0000037 | 20190601

Sirt1 | sirtuin 1 |   | rRNA processing |   | UniProt | Mus musculus | IEA | UniProtKB-KW:KW-0698 | chromatin regulatory protein sir2 pthr11085 | protein |   | GO_REF:0000004MGI:MGI:1354194 | 20190602

Sirt1 | sirtuin 1 |   | rRNA processing |   | UniProt | Rattus norvegicus | IEA | UniProtKB-KW:KW-0698 | chromatin regulatory protein sir2 pthr11085 | gene |   | GO_REF:0000037RGD:1600115 | 20190110

**Comment by ValWood** [comment]
ribosome biogenesis/ mirochondrion organization

Also

Cdkn2a | cyclin-dependent kinase inhibitor 2A |   | rRNA processing |   | UniProt | Rattus norvegicus | IEA | UniProtKB-KW:KW-0698 |   | gene |   | GO_REF:0000037RGD:1600115 | 20190110


seems to regulate rDNA transcription but I can't find regulation of processing

**Comment by ValWood** [comment]
I haven't been able to locate the source of this in human, rat or mouse

**Comment by sylvainpoux** [comment]
Hi Val,
I removed the KW from SIRT1 (and orthologs)
Regarding Cdkn2a, as it is a MGI and RGD annotation, I cannot do anything
Thanks
Sylvain

**Comment by ValWood** [comment]
This is the only annotation I can find on mouse

Cdkn2a | cyclin dependent kinase inhibitor 2A |   | rRNA processing |   | UniProt | Mus musculus | IEA | UniProtKB-KW:KW-0698 |   | protein |   | GO_REF:0000004MGI:MGI:1354194 | 20190602

**Comment by sylvainpoux** [comment]
Ok, I see now, this function is related to the ARF isoform of Cdkn2a  (they are in separate Swiss-Prot entries, it is why I didn't found this annotation). 

There are at least 2 papers describing its role in rRNA processing and I would keep the KW for the moment (PMID:15361825, PMID:14636574)

Thanks

Sylvain

**Comment by ValWood** [comment]
OK got it. This is something  inhibiting growth and driving cells into apoptosis. Yeast don't have this so I was a bit confused by the CDK connection.

Ideally this would be "negative regulation of rRNA processing" and then my problem would go away.
I can make an exception for now, but is there a plan to deal with KW mappings when they are direct but GO annotation requires "regulation of"? I think @pgaudet  raised this a while ago, but I don't know what was decided.

**Comment by ValWood** [comment]
added exception pthr24148 to lipid metabolism/ribosome biogenesis for now and will revisit in future

**Comment by pgaudet** [comment]
Do you leave that open then ? Do you want to reassign to yourself ?

**Comment by ValWood** [comment]
closing, I have a list of weird ones that cannot currently be ruled out but the evidence is weak. It will be interesting to see how many stand the test of time.
