### ISSUE TITLE
Matrix: mitochondrion organisation / ribosome biogenesis (PAINT)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2492]
ribosomal large subunit biogenesis looks incorrect, this is a mitochondrial outer membrane protein (cytosolic side)

MDV1 | Peripheral protein of cytosolic face of mitochondrial outer membrane |   | ribosomal large subunit biogenesis |   | GO_Central | Saccharomyces cerevisiae S288C | IBA | PANTHER:PTN000458182SGD:S000001451 | family not named pthr19857 | gene

**Comment by marcfeuermann** [comment]
The annotations propagated come all from node PTN002716161 (a triplicate from YEAST). It seems that the 3 proteins have different functions, so it is not possible to propagate any of those annotations. I've removed all propagations.
