### ISSUE TITLE
Matrix: ribosome biogenesis /vesicle-mediated transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2494]
This is a flippase  so this one looks odd:

DRS2 | Trans-golgi network aminophospholipid translocase (flippase) |   | ribosomal small subunit assembly |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr24092 | gene |   | PMID:8247005 | 20070523

**Comment by ValWood** [comment]
The paper is
DRS1 to DRS7, novel genes required for ribosome assembly and function in Saccharomyces cerevisiae.
Date


but you only have CAM1 & DRS2 annotated from this and neither seems right?

**Comment by srengel** [comment]
hi Val, i have removed both of the annotations from that paper.
