### ISSUE TITLE
Matrix:  DNA replication/carbohydrate metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2496]
BMH2 is a 14-3-3 protein (signalling molecule sequestering)

BMH2 | 14-3-3 protein, minor isoform |   | glycogen metabolic process |   | SGD | Saccharomyces cerevisiae S288C | IGI |   | 14-3-3 protein pthr18860 | gene |   | PMID:9215628 | 20010829

looks indirect. If it's kept at all it should be "regulation of..."

**Comment by srengel** [comment]
i moved this one down to 'regulation'.  did the same for paralog BMH1.
