### ISSUE TITLE
MAtrix: RNR4 DNA replication vs nucleotifde metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2497]
I don't see co-factor metabolic process here. Which Co-factor?

RNR4 | Ribonucleotide-diphosphate reductase (RNR) small subunit |   | cofactor biosynthetic process |   | SGD | Saccharomyces cerevisiae S288C | IPI | SGD:S000003563 | ribonucleoside-diphosphate reductase small chain pthr23409 | gene |   | PMID:15196016 | 20080730

  | RNR4 | Ribonucleotide-diphosphate reductase (RNR) small subunit |   | cofactor biosynthetic process |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | ribonucleoside-diphosphate reductase small chain pthr23409 | gene

We have "nucleobase containing small molecule...yada children (probably too many!)

**Comment by srengel** [comment]
the diferric-tyrosyl radical (Y*) cofactor cofactor in Rnr2p.  they're old annotations and no longer seem appropriate.  i removed them.
