### ISSUE TITLE
Matrix: DNA replication/adhesion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2499]
- [ ] ACHE | Acetylcholinesterase |   | DNA replication |   | UniProt | Homo sapiens | TAS |   | carboxylesterase pthr11559 | protein |   | PMID:11283752 | 20031128

**Comment by ValWood** [comment]
also in the lipid intersecgtion

**Comment by ValWood** [comment]
Hi @pgaudet  I don't think this annotation is correct. If you agree can you delete?

**Comment by pgaudet** [comment]
This in an EBI annotation. DNA replication should go.

**Comment by ValWood** [comment]
I thought protein2GO would not allow me to dispute this one, but it has
Notification of annotation dispute concerning protein P22303 (Dispute ID: 8993)

I think the dispute came back to us and I don't think i have permission to delete?

**Comment by ValWood** [comment]
done

**Comment by pgaudet** [comment]
And I see the dispute is resolved,
