### ISSUE TITLE
virion/viral envelope terms on zebrafish genes via uniprotkb_kw2go translations

### ISSUE THREAD

**Issue by doughowe** [geneontology/go-annotation#2501]
The zebrafish genes zp2.1 and zp2.2 are getting annotated to the terms viral envelope (GO:0019031) and virion (GO:0019012).  These are coming to ZFIN via application of the following uniprotkb_kw2go  translations.

UniProtKB-KW:KW-0946 Virion > GO:virion ; GO:0019012
UniProtKB-KW:KW-0261 Viral envelope protein > GO:viral envelope ; GO:0019031

Those UniProt KW are in turn coming from:
https://www.uniprot.org/uniprot/Q9PWC8  on zp2.1

https://www.uniprot.org/uniprot/Q98SS1 on zp2.2
https://www.uniprot.org/uniprot/Q98SS2 on zp2.2
https://www.uniprot.org/uniprot/Q98SS0 on zp2.2
https://www.uniprot.org/uniprot/Q98SS3 on zp2.2

So, I'm not sure where the issue is....maybe the keywords shouldn't be associated with those proteins?

**Comment by ValWood** [comment]
Hi @doughowe  these entries seem to be obsolete. Please open a new issue if there is still a problem.
