### ISSUE TITLE
PTN000029003 selenide, water dikinase activity and process terms (PTHR10256)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2502]
PTN000029003 selenide, water dikinase activity
selenocysteine biosynthetic process
tRNA seleno-modification
selenium compound metabolic process

Just reviewing: SelD, FBgn0261270. And appears that it does not have selenide, water dikinase activity. 

From PMID:19755423
"The sequences of SPS1/SelD and SPS2 are highly conserved. For example, the amino acid sequence homology between human SPS1/SelD and SPS2 is 72% and that between Drosophila SPS1/SelD and SPS2 is 45%. One of the major differences between SPS1/SelD and SPS2 is that SPS1/ SelD has an arginine at the position corresponding to Sec in SPS2. Initially, both SPS1/SelD and SPS2 were thought to be involved in selenophosphate synthesis. However, it was subsequently shown that only SPS2 catalyzes selenophosphate synthesis. In in vitro experiments, SPS2 synthesized selenophosphate from selenide and ATP, but SPS1/SelD did not have this activity. Knockdown of SPS2 in NIH3T3 cells led to the loss of selenoprotein biosynthesis, whereas the inhibition of SPS1/ SelD expression did not affect the biosynthesis of selenoproteins, and only SPS2 was capable of restoring selenoprotein synthesis"
It seems that only the SPS2 has the activity and SPS1 does not and that this may be conserved.

**Comment by marcfeuermann** [comment]
PAINT bug has been fixed and the node including SelD is now accessible. The primary annotations of SelD to "selenocysteine biosynthetic process" and related terms are still present in the PAINT matrix and prevent to block IBA annotation to SelD. I will block the terms as soon as they disappear.

**Comment by hattrill** [comment]
Hi @marcfeuermann could you block the "selenocysteine biosynthetic process" term for SelD, FBgn0261270. Thanks.

**Comment by pgaudet** [comment]
Fixed.
