### ISSUE TITLE
Matrix: DNA replication cytokinesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2506]
GO:0006260  DNA replication
GO:0000910  cytokinesis

from
http://amigo.geneontology.org/amigo/reference/PMID:17286961

This paper is about nuclear division (mitosis) not cytoplasmic division(cytokinesis)

BRCA2 | Breast cancer type 2 susceptibility protein |   | mitotic cytokinesis |   | UniProt | Homo sapiens | IDA |   | breast cancer type 2 susceptibility protein brca2 pthr11289 | protein |   | PMID:17286961 | 20180125

and

Brca2 | BRCA2, DNA repair associated |   | mitotic cytokinesis |   | RGD | Rattus norvegicus | ISO | RGD:736254 | breast cancer type 2 susceptibility protein brca2 pthr11289 | gene |   | PMID:17286961RGD:1624291 | 20180203

Will raise dispute

**Comment by ValWood** [comment]
I don't believe the "centrosome duplication" either. This is an old and vague  paper,  GFP seems to interfere somewhat. I wonder if this has been repeated?

**Comment by ValWood** [comment]
dispute
Notification of annotation dispute concerning protein P51587 (Dispute ID: 8933)

Seems to be involved in cohesion between centrosomes
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4993541/

**Comment by ValWood** [comment]
This will also fix the BRCA2 cytoskeleton/DNA replication intersection

**Comment by gthayman** [comment]
These are imported from GOC.

**Comment by ValWood** [comment]
I reported the human one in protein2GO

**Comment by ValWood** [comment]
These are fixed. ~However there are new annotations in this intersection which appear to be  incorrect. WIll address later.
