### ISSUE TITLE
Matrix: DNA replication/ cytoskeleton organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2507]
All the NAS/TAS from this paper should be deleted
http://amigo.geneontology.org/amigo/reference/PMID:11443112
It's largely speculation form a cloning experiment.

NCOA6 | Nuclear receptor coactivator 6 |   | DNA replication |   | UniProt | Homo sapiens | NAS |   | nuclear receptor coactivator 6 pthr15690 | protein |   | PMID:11443112 | 20031216

  | NCOA6 | Nuclear receptor coactivator 6 |   | DNA repair |   | UniProt | Homo sapiens | NAS |   | nuclear receptor coactivator 6 pthr15690 | protein |   | PMID:11443112 | 20031216

  | NCOA6 | Nuclear receptor coactivator 6 |   | DNA recombination |   | UniProt | Homo sapiens | NAS |   | nuclear receptor coactivator 6 pthr15690 | protein |   | PMID:11443112 | 20031216

  | NCOA6 | Nuclear receptor coactivator 6 |   | intracellular estrogen receptor signaling pathway |   | UniProt | Homo sapiens | NAS |   | nuclear receptor coactivator 6 pthr15690 | protein |   | PMID:11443112 | 20031216

  | NCOA6 | Nuclear receptor coactivator 6 |   | glucocorticoid receptor signaling pathway |   | UniProt | Homo sapiens | NAS |   | nuclear receptor coactivator 6 pthr15690 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | transcription coregulator activity |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | RNA binding |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | DNA replication |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | DNA repair |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | DNA recombination |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | mediator complex |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20090825

  | RBM14 | RNA-binding protein 14 |   | intracellular estrogen receptor signaling pathway |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | protein binding, bridging |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

  | RBM14 | RNA-binding protein 14 |   | glucocorticoid receptor signaling pathway |   | UniProt | Homo sapiens | NAS |   | serine/arginine rich splicing factor pthr23147 | protein |   | PMID:11443112 | 20031216

**Comment by pgaudet** [comment]
These are from EBI @milarolo can you please have a look ?

**Comment by milarolo** [comment]
all deleted now

**Comment by ValWood** [comment]
thanks!
