### ISSUE TITLE
Matrix: DNA replication/ cytoskeleton organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2508]
I don't think this has a role in replication, I didn't check the paper, but replication is pretty eukaryotically conserved. Mainly I don' think you can indicate replication via IEP

Pdgfb | platelet derived growth factor subunit B |   | DNA replication |   | RGD | Rattus norvegicus | IEP |   | platelet-derived growth factor pthr11633 | gene |   | PMID:12084843RGD:1581760 | 20061024

I can dig deeper  if you think the annotation is OK

**Comment by ValWood** [comment]
I checked the abstract, this is a clear example of an experimental readout.  It seems that DNA synthesis is being used as a readout for " a growth/proliferation phenotype".

**Comment by ValWood** [comment]
Another example:
(these seem to be from Uniprot, will raise a Protein2GO dispute)

Tnfaip1 | TNF alpha induced protein 1 |   | positive regulation of DNA replication |   | RGD | Rattus norvegicus | IDA |   | tumor necrosis factor-related pthr11145 | gene |   | PMID:15726626RGD:1357162 | 20050629


Tnfaip1 | TNF alpha induced protein 1 |   | DNA replication |   | UniProt | Rattus norvegicus | IDA |   | tumor necrosis factor-related pthr11145 | gene |   | PMID:15726626RGD:1357162 | 20051214
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


Tnfaip1 | TNF alpha induced protein 1 |   | DNA repair |   | UniProt | Rattus norvegicus | TAS |   | tumor necrosis factor-related pthr11145 | gene |   | PMID:15726626RGD:1357162 | 20051214

There are many TAS from this paper, should probably be deleted:

Tnfaip1 | TNF alpha induced protein 1 |   | actin cytoskeleton organization |   | UniProt | Rattus norvegicus | TAS |   | tumor necrosis factor-related pthr11145 | gene |   | PMID:15726626RGD:1357162 | 20051214
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Tnfaip1 | TNF alpha induced protein 1 |   | protein homooligomerization |   | UniProt | Rattus norvegicus | TAS |   | tumor necrosis factor-related pthr11145 | gene |   | PMID:15726626RGD:1357162 | 20051214
  | Tnfaip1 | TNF alpha induced protein 1 |   | protein heterooligomerization |   | UniProt | Rattus norvegicus | TAS |   | tumor necrosis factor-related pthr11145 | gene |   | PMID:15726626RGD:1357162 | 20051214

**Comment by ValWood** [comment]
I can't raise a dispute for these annotations.
I'm pretty sure this isn't curatabe. The papers shows the authors cloned 2 genes than that they  supposedly both interact with PCNA. Then they do an assay and   supposedly show an invitro increase in polymerase activity. However this activity is only increased in the presence of PCNA and there is no control experiment. It's in a journal I haven't heard of and I don't think it has been confirmed since 2005.
@pgaudet  what do you think?

**Comment by pgaudet** [comment]
@gthayman

**Comment by pgaudet** [comment]
@gthayman Can you please look at those annotations ?

**Comment by gthayman** [comment]
The RGD Pdgfb annotation is gone. I think the controls and our annotation for Tnfaip1 are appropriate. I'm afraid we can't do anything about the UniProt annotations.

**Comment by pgaudet** [comment]
Thanks @gthayman 
I removed the UniProt TAS annotations and those that were redundant with RGD (they dated from 2005).
