### ISSUE TITLE
Matrix: DNA replication/cytoskeleton organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2510]
CCDC88A

Ccdc88a | coiled coil domain containing 88A |   | regulation of DNA replication |   | UniProt | Mus musculus | IMP |   | hook proteins pthr18947 | protein |   | MGI:MGI:3581096PMID:15753085 | 20070418

from

Knockdown of APE Reduces DNA Synthesis—To explore the effect of APE depletion on proliferation, DNA synthesis in HepG2 cells were measured by BrdUrd incorporation. It was shown that suppressed expression of endogenous APE by siRNA led to decreased DNA synthesis in an APE siRNA titer-dependent manner (Fig. 7).

I don't think you can use this phenotype to infer involvement in regulation (many cell cycle blocks would give this phenotype).

Although it has been cited quite a bit so I'll check some more recnt papers  for the role of CCDC88A in replication

**Comment by ValWood** [comment]
I found only a review searching on CCDC88A and replication in PubMed.

This says

"Small interfering RNA (siRNA)‐mediated knockdown of Girdin resulted in a reduction of DNA synthesis, suggesting a role of Girdin in promoting cell proliferation. However, though Girdin increases the kinase activity of Akt, the association of Girdin and Akt was inhibited by insulin stimulation in HEK293 cells. Further data suggest that the relationship between Girdin and Akt might be far more complex. That is, exogenously induced expression of both Akt and Girdin induced apoptosis and inhibited cell proliferation, survival, and cytokinesis (the DNA content increased to more than 4n in the S phase) by COS7 cells and HeLa cells.3 Because previous studies have shown that Akt promotes cellular proliferation and inhibits apoptosis in many cell types,8, 9 these complex findings obscure the mechanism by which Girdin regulates the function of Akt in various cellular processes. It will be important to address how alterations in Akt signaling by Girdin affect the control of cell proliferation. We speculate that Girdin may be needed for the integrity of growth factor‐induced Akt signaling; that is, modulation of Akt signaling via spatially and temporally regulated distribution of Girdin protein."

**Comment by ValWood** [comment]
I'll close this one. There are only 71 proteins in this intersection, most look as though they should be annotated to "regulation" of both processes, not directly to both processes, but we can address these more systematically later.

**Comment by ValWood** [comment]
Annotation to "DNA replication" looks dodgy though from the above .

**Comment by pgaudet** [comment]
In this case DNA replication is a read-out for cell proliferation. The abstract is pretty clear: 

> In cells in which APE was suppressed by small interfering RNA, DNA synthesis was significantly reduced with suppression of PKB phosphorylation, suggesting a synergistic role of APE in PKB-induced proliferation.


We need to be careful to distinguish readouts when annotating, in this case this falls in a different branch of GO.

**Comment by ValWood** [comment]
I agree.

**Comment by LiNiMGI** [comment]
Are we talking about the annotation:
Ccdc88a | coiled coil domain containing 88A |   | regulation of DNA replication |   | UniProt | Mus musculus | IMP |   | hook proteins pthr18947 | protein |   | MGI:MGI:3581096PMID:15753085 | 20070418

That particular annotation was made by GOA_UniProt @ValWood

**Comment by ValWood** [comment]
OK I raised a protein2GO dispute.
This is an expired account so it will probably go to @pgaudet  or @Antonialock 
There is also a SPKW to DNA replication on this entry which should be deleted (and orthologs if they have them too).
I will change the assignee.

**Comment by pgaudet** [comment]
I deleted the DNA replication annotation, and updated the others. 

Can you please close the dispute? 

Thanks, Pascale

**Comment by ValWood** [comment]
Done but reopening for the KW mapping

**Comment by Antonialock** [comment]
fixed kw mapping
