### ISSUE TITLE
Matrix: DNA replication /cytoskeleton organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2511]
check?
is endoreduplication normal process for mouse?

Zpr1 | ZPR1 zinc finger |   | DNA endoreduplication |   | UniProt | Mus musculus | IMP |   | zinc finger protein zpr1 pthr10876 | protein

**Comment by ValWood** [comment]
@ukemi 
I didn't look into this one in detail yet, but is endoreduplication enen a valid process for mouse?

Endoreduplication (also referred to as endoreplication or endocycling) is replication of the nuclear genome in the absence of mitosis, which leads to elevated nuclear gene content and polyploidy

(this sounds like a phenotype?"

**Comment by ValWood** [comment]
If not maybe we could add some taxon restrictions?

**Comment by vanaukenk** [comment]
I don't know about mouse, but endoreduplication in certain nematode tissues is a normal part of development and can regulate body size:

https://www.ncbi.nlm.nih.gov/pubmed/10805788
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4845952/

**Comment by ukemi** [comment]
PMID:24154524

**Comment by ValWood** [comment]
Ah "syntactium" was the word I was trying to remember, but could not get close enough to find it by Google.

But isn't 
https://www.ebi.ac.uk/QuickGO/term/GO:0006949 endoreduplication (increase in ploidy without division)  subtly different from syntactium formation (where the the nuclei divide). 

Drosophila polytene chromosomes are a product of endoreduplication.

**Comment by ValWood** [comment]
OK ignore my comment both these examples are endoreduplication. so is Zpr1 could be a valid example of this because zpr1 involved in mRNA processing but it seems to be closely coupled to  cell growth/size and development.

Zpr1 is a highly conserved zinc finger protein at the interface between mRNA catabolism and translation. It is essential in both yeasts and its deletion has pleiotropic effects.

So more likely here the the problem annotation is microtubule organization. This is likely an indirect pathological phenotype. The suppression of zpr1 causes microtubule disruption in neurons (no mechanistic connection suggested). It is likely that in dividing cells another phenotype would predominate....

**Comment by mah11** [comment]
> Ah "syntactium" was the word I was trying to remember,

The word is *syncytium*.

**Comment by ValWood** [comment]
I'll close this one. There are only 71 proteins in this intersection, most look as though they should be annotated to "regulation" of both processes, not directly to both processes, but we can address these more systemtically later.

**Comment by pgaudet** [comment]
Really I think these are cell proliferation. It may be worth reviewing on an annotation call. Up to you.

**Comment by ValWood** [comment]
I agree. I kind of gave up with this.....

**Comment by pgaudet** [comment]
Let's close for now... As Val says, it's not so many annotations.
