### ISSUE TITLE
Matrix: DNA replication/ energy generation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2512]
look into this, the interacting gene does not have  DNA replication:

BMH2

DNA replication initiation |   | IGI with BMH1 | SGD | 2009-11-30 | Yahyaoui W and Zannis-Hadjopoulos M (2009)PMID:19934224

or, the problem could be this one
glycogen metabolic process |   | IGI with P29311 | SGD | 2001-08-29 | Roberts RL, et al. (1997)

either way, 14-3-3 is usually sequestering signalling molecules so one or both if correct are likely to be "regulation"

**Comment by ValWood** [comment]
Let me know if this doesn't make sense.

Essentially these will be OK if one or both is "regulation of" BUT I wasn't sure they were correct.

**Comment by srengel** [comment]
oh i already switched the glycogen metabolism to 'regulation' last week from a different ticket i thought.

**Comment by ValWood** [comment]
yep, sorry! https://github.com/geneontology/go-annotation/issues/2496
