### ISSUE TITLE
Matrix: DNA replication/ mRNA metabolism (UPF1) & nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2515]
UPF1 | Regulator of nonsense transcripts 1 |   | DNA replication |   | HGNC | Homo sapiens | IMP |   | dna2/nam7 helicase family pthr10887 | protein |   | PMID:16488880 | 20060317

From
https://www.ncbi.nlm.nih.gov/pubmed/16488880

Personally, I don't think this supports a role in DNA replication (just S-phase progression)

The eukaryotic nonsense-mediated mRNA decay (NMD) pathway degrades mRNAs carrying premature stop codons (PTC). In humans, NMD depends on the RNA- and DNA-dependent 5'-3' helicase UPF1 and six other gene products referred to as SMG1, UPF2, UPF3, EST1A/SMG6, EST1B/SMG5, and EST1C/SMG7. The NMD machinery is also thought to coordinate mRNA nuclear export and translation and to regulate the levels of several physiologic transcripts. Furthermore, in a process named SMD, UPF1 promotes degradation of mRNAs that are bound by Staufen 1. Intriguingly, SMG1 and EST1A/SMG6 function also in DNA repair and telomere maintenance, respectively. Here, we show that UPF1 is also required for genome stability. shRNA-mediated depletion of UPF1 causes human cells to arrest early in S phase, inducing an ATR-dependent DNA-damage response. A fraction of hyperphosphorylated UPF1 associates with chromatin of unperturbed cells, and chromatin association increases in S phase and upon gamma irradiation. ATR phosphorylates UPF1 both in vitro and in vivo, and shRNA-mediated downregulation of ATR diminished the association of UPF1 with chromatin, although it did not affect NMD. Physical interaction of UPF1 with DNA polymerase delta suggests a role for human UPF1 in DNA synthesis during replication or repair.

**Comment by ValWood** [comment]
dispute raised

**Comment by RLovering** [comment]
HI Val
sorry I didn't read your github ticket before responding to the dispute. But I am still confused about why you don't think a DNA helicase isn't involved in DNA replication? Especially with the end of the abstract you include above stating: Physical interaction of UPF1 with DNA polymerase delta suggests a role for human UPF1 in DNA synthesis during replication or repair.

Please could you explain what the problem is in more detail
Thanks
Ruth

**Comment by ValWood** [comment]
I wasn't convinced that it was a DNA helicase....
 in yeast
ATP-dependent RNA helicase of the SFI superfamily; involved in nonsense mediated mRNA decay; required for efficient translation termination at nonsense codons and targeting of NMD substrates to P-bodies; binds to the small ribosomal subunit via an interaction with Rps26; forms cytoplasmic foci upon DNA replication stress 2 3 4 5 6

 we only have RNA helicase.

The human description says "DNA helicase" but I don't see an annotated assay for this.

**Comment by ValWood** [comment]
I think its due to the same reasons as the slowing in replication progression with THO complex.

See the rationale in this ticket:
https://github.com/geneontology/go-annotation/issues/2517

**Comment by RLovering** [comment]
Hi Val there is a BHF annotation which suggests UPF1 does have a role in DNA replication and perhaps also repair, see PMID:21829167 and also more recent: PMID:28541562 which states in the abstract: UPF1 is a conserved helicase required for nonsense-mediated decay (NMD) regulating mRNA stability in the cytoplasm. Human UPF1 (hUPF1) is also needed for nuclear DNA replication.

**Comment by ValWood** [comment]
Yup, this looks like it needs an exception. I'm at a meeting with lots of telomere biologists and DNA repair experts so will ask tomorrow what the known connections are between these processes and add the necessary exceptions. Assume that you don't need to do anything here... I'll take this ticket and close it when we are sorted for the rules.

**Comment by ValWood** [comment]
I  didn't ask anyone about this because there is lots of evidence, it looks solid- I'm adding pthr10887  as an exception for now.  This will only cover UPF1 ......Most likely later I will change this to the sub-process  if other families turn out to be involved too.
