### ISSUE TITLE
Matrix: DNA replication/ nucleocytoplasmic transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2520]
I made an exception earlier to allow rRix complex to be both "DNA replication" and "RNA processing" but export seems downstream

RIX1 | Component of the Rix1 complex and possibly pre-replicative complexes |   | ribosomal subunit export from nucleus |   | SGD | Saccharomyces cerevisiae S288C | IMP |   |   | gene |   | PMID:11313466 | 2003062

**Comment by srengel** [comment]
agree.  have removed export from RIX1.
