### ISSUE TITLE
Matrix: ribosome biogenesis/DNA replication

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2524]
Hi @hattrill 

This one is a red flag but I didn't look into the details.  It's the only remaining issue in replication/ribosome biogenesis. Seems likely to be a phenotype but I don't want to role out some quirky role in endoredulication...

LTV1 | LTV1 ribosome biogenesis factor |   | DNA endoreduplication |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0228511PMID:25858587 | 20160218

**Comment by hattrill** [comment]
Yup! Endoreduplication pheno is downstream effect. Removed.
