### ISSUE TITLE
LTV1  PANTHER:PTN000488416 EGO complex/late endosome membrane 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2525]
PANTHER:PTN000488416 propagation to EGO complex and  late endosome membrane looks a bit odd. LTV1 is a well-conserved factor in ribosome biogenesis.

As far as I can see, the annotations come from one paper (PMID:16732272) for scLTV1 https://www.yeastgenome.org/locus/S000001626
Perhaps someone in SGD could revisit this original annotation (@suzialeksander)?

I seem to find more errors with IBAs supported by only one annotation - perhaps you could review the practice at some point?

**Comment by srengel** [comment]
Hi @hattrill the paper shows Ltv1p is part of EGO/GSE.  do you just not believe the paper?  please advise.

**Comment by hattrill** [comment]
Mainly, I do not think that this annotation should be propagated via PAINT as:
1. Not sure if this complex is conserved,
2. LTV1 is most certainly involved in 40s biogenesis - this is being masked by the assertion that it's an endosomal transport complex protein.

I am not sure how you want to handle the yeast annotations - if you think it is ok, then don't change it - it reflects author intent. I just feel a bit suspicious about this paper - Ltv1p is shown to come down in a pull down with Gtr1 - but I am not convinced by that gel and it displays diffferent behaviour to the other subunits in terms of the effect of depletion on the other subunits and its subcellular localization. However, there is some evidence that it is involved in Fig 2 (controls are unsatisfactory). And, I have not seen this subunit backed up in any other papers. 
Complex Portal has the EGO and GSE complexes as separate complexes (although the difference is just Ltv1p). Perhaps this is more "EGO complex binding" than part of the EGO complex - they don't look for Ltv1p in the gel filtration experiment.

**Comment by pgaudet** [comment]
Note to PAINT curators: Labeled as required review in PAINT13

**Comment by marcfeuermann** [comment]
Propagation to EGO complex and late endosome membrane was removed.
