### ISSUE TITLE
Matrix: cohesion case study (tim-1)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2528]
tim-1 |   | colocalizes_with | mitotic cohesin complex |   | WB | Caenorhabditis elegans | IPI | WB:WBGene00001860 |   | gene |   | PMID:12827206WB_REF:WBPaper00005919 | 2008033

comes up in the cohesin intersection,  should this removed? (I think we are obsoleting contributes to?) t

**Comment by ValWood** [comment]
Although wiht the above fix, the matrix issue is resolved I would question all of the following from the same paper


tim-1 |   |   | regulation of sister chromatid cohesion |   | WB | Caenorhabditis elegans | IGI | WB:WBGene00001860 |   | gene |   | PMID:12827206WB_REF:WBPaper00005919 | 20080331

  | tim-1 |   |   | regulation of sister chromatid cohesion |   | WB | Caenorhabditis elegans | IMP | WB:WBVar00249136 |   | gene |   | PMID:12827206WB_REF:WBPaper00005919 | 20080331

  | tim-1 |   |   | mitotic sister chromatid cohesion |   | WB | Caenorhabditis elegans | IGI | WB:WBGene00001860 |   | gene |   | PMID:12827206WB_REF:WBPaper00005919 | 20080331

  | tim-1 |   |   | mitotic sister chromatid cohesion |   | WB | Caenorhabditis elegans | IMP |   |   | gene |   | PMID:12827206WB_REF:WBPaper00005919 | 20080331

tim-1 |   |   | meiotic sister chromatid cohesion |   | WB | Caenorhabditis elegans | IMP | WB:WBVar00249136 |   | gene |   | PMID:12827206WB_REF:WBPaper00005919 | 20080331

Because this is  a  well studied replication fork protection complex subunit. I'll have a quick glance  at this paper

**Comment by ValWood** [comment]
These are OK, there is a connection between a DNA checkpoint complex and cohesin. It might be quite indirect, but it is  related to cohesin establishment.

So it's just the "complex" term here.

**Comment by vanaukenk** [comment]
@ValWood - the 'complex' annotation was deleted a while back, but it hasn't yet trickled down to our latest production GAF.
I'll go ahead and close this ticket.
