### ISSUE TITLE
Matrix: cohesin case study (TAIR-  TITAN8 )

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2529]
cohesin complex and transmembrane transporter are mutually exclusive. This one looks really familiar, but I can't find an existing ticket (open or closed)?

@tberardini 

TTN8 | TITAN8 |   | transmembrane transporter activity |   | TAIR | Arabidopsis thaliana | ISS | InterPro:IPR003439 |   | protein | TAIR:locus:2102420 | PMID:11346655TAIR:Publication:501680567 | 20190419

  | TTN8 | TITAN8 |   | cohesin complex |   | TAIR | Arabidopsis thaliana | ISS |   |   | protein | TAIR:locus:2102420 | PMID:11846874TAIR:Publication:1547295 | 20040512
 
 | TTN8 | TITAN8 |   | sister chromatid cohesion |   | TAIR | Arabidopsis thaliana | IMP |   |   | protein | TAIR:locus:2102420 | PMID:19533160TAIR:Publication:501733318 | 20100203

**Comment by tberardini** [comment]
I removed the 'transmembrane transporter activity' annotation.
