### ISSUE TITLE
Matirx: Cohesin case study (SMC3)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2530]
Looks indirect for cohesin (phenotype from meiotic chromosome segregation functions)

SMC3 | Subunit of the multiprotein cohesin complex |   | ascospore formation |   | SGD | Saccharomyces cerevisiae S288C | IMP |   | family not named pthr43977 | gene |   | PMID:10412984 | 20010118

**Comment by srengel** [comment]
removed.
