### ISSUE TITLE
QC: IEA mapping updates

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2531]
This InterPro mapping  was deleted in 2014

~ACLA_070070 |   |   | mitotic chromosome condensation |   | AspGD | Aspergillus clavatus NRRL 1 | IEA | InterPro:IPR027120 |   | gene_product |   | AspGD_REF:ASPL0000166200 | 20190701~

This implies that AspGD source is just updating the timestamp on their InterPro mappings but not acutually rerunning the pipeline?

We should make sure that everyone knows what this data stamp means,  and suggest that ASPGD let GOA supply the InterPro mapping annotations to the GO database if they don't have the resources to update the mappings....

**Comment by ValWood** [comment]
correction, this was the deleted mapping

ACLA_070070 |   |   | DNA recombination |   | AspGD | Aspergillus clavatus NRRL 1 | IEA | InterPro:IPR024704 |   | gene_product |   | AspGD_REF:ASPL0000166200 | 20190701

**Comment by vanaukenk** [comment]
@ValWood 
FungiDB is supposed to become the authority for Aspergillus annotations, so presumably this will be addressed when they assume that responsibility.
I can check in with Ach and co. to see where things stand wrt their annotation files.

**Comment by pgaudet** [comment]
If this is the case we need to update the files
https://github.com/geneontology/go-site/tree/master/metadata/datasets
and
https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

AFAIK right now AsgDB is the authority for Aspergillus - and whatever their procedure is, it would be the same for CGD. 

Pascale

**Comment by pgaudet** [comment]
@marekskrzypek Can you please check why AspGD ACLA_070070 has an InterPro mapping that has been removed for months now ? The data assigned is 20200323, which is not possible - this cannot have been run on 20200323. 

Thanks ! 

Pascale

**Comment by marekskrzypek** [comment]
This must be due to some long forgotten cron job that is still active for AspGD on our side, even though the AspGD GO annotations have not been actively maintained by us for years. We will find and deactivate it, and there won't be any ghosts like this anymore. 
Thanks, 
Marek

**Comment by pgaudet** [comment]
Great !! thanks

**Comment by pgaudet** [comment]
'Resolved' - ie this is not causing problems anymore, now that the AspGD data is coming from GOA; however this is not a species GO central fully loads, so we dont have IEAs. These will get restored when we do the work in this project: 

https://github.com/geneontology/project-management/issues/48
