### ISSUE TITLE
Matrix: amino acid metabolism/carbohydrate matabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2533]
succinate-semialdehyde dehydrogenase

I wondered if this were a littl indirect for

ALDH5A1 | Succinate-semialdehyde dehydrogenase, mitochondrial |   | glutamate metabolic process |   | UniProt | Homo sapiens | ISS | UniProtKB:Q8BWF0 | family not named pthr43353 | protein |   | GO_REF:0000024 | 20080415

  | ALDH5A1 | Succinate-semialdehyde dehydrogenase, mitochondrial |   | glutamine metabolic process |   | UniProt | Homo sapiens | ISS | UniProtKB:Q8BWF0 | family not named pthr43353 | protein |   | GO_REF:0000024 | 20080415

I have added exceptions for some TCA feedin points so let me know if you want to keep this and I will extend.

these  were not violating this intersection but seem incorrect for TCA cycle:

ALDH5A1 | Succinate-semialdehyde dehydrogenase, mitochondrial |   | glycerophospholipid metabolic process |   | UniProt | Homo sapiens | ISS | UniProtKB:Q8BWF0 | family not named pthr43353 | protein |   | GO_REF:0000024 | 20080415

ALDH5A1 | Succinate-semialdehyde dehydrogenase, mitochondrial |   | glucosylceramide metabolic process |   | Ensembl | Homo sapiens | IEA | UniProtKB:Q8BWF0ensembl:ENSMUSP00000040591 | family not named pthr43353 | protein |   | GO_REF:0000107 | 20190601

  | ALDH5A1 | Succinate-semialdehyde dehydrogenase, mitochondrial |   | galactosylceramide metabolic process |   | UniProt | Homo sapiens | ISS | UniProtKB:Q8BWF0 | family not named pthr43353 | protein |   | GO_REF:0000024 | 20080415

  | ALDH5A1 | Succinate-semialdehyde dehydrogenase, mitochondrial |   | glutathione metabolic process |   | UniProt | Homo sapiens | ISS | UniProtKB:Q8BWF0 | family not named pthr43353 | protein |   | GO_REF:0000024 | 20080415

ALDH5A1	Succinate-semialdehyde dehydrogenase, mitochondrial		central nervous system development		UniProt	Homo sapiens	IMP		family not named pthr43353	protein		PMID:9683595	20060428

Assigning to @ukemi  because although these are human the  primary annotations are mouse

**Comment by ukemi** [comment]
This is fascinating interconnected biochemistry, but I think these will end up being deleted because the reactions are being forced in the opposite directions in the mutant. I need to read a bit more on exactly how we might want to model this. PMID:23750153, PMID:17854388 (and discuss it more with @deustp01).

**Comment by ukemi** [comment]
Looking at the Reactome pathway description makes sense to me: R-HSA-916853.1. This enzyme should be in the GABA catabolism pathway.

**Comment by ukemi** [comment]
Related, but not integral metabolism annotations have been removed.

**Comment by ukemi** [comment]
That said, it would be really cool to try to model some of these pathways that impinge upon each other. It brings up the age-old boundary issues we always have. Would it make sense to create many models with different boundaries, each with specific participants and enzymatic activities?

**Comment by ukemi** [comment]
So the other large question wrt this issue is that the GABA degradation does have an output of L-glutamate. So should we have an annotation to glutamate metabolic process?

**Comment by ukemi** [comment]
OK. Mulling this over I'm adding back the glutamate metabolism terms.

**Comment by ValWood** [comment]
I can add an exception instead?

**Comment by ValWood** [comment]
OK I see you added them back. I will add an exception for 

 glutamate metabolic process in this intersection.
Any more of these need exceptions?

**Comment by ukemi** [comment]
I think so. Some of the meatabolism terms don't fit, but based on the Reactome diagram, it fits our def of succinate and glutamate.

**Comment by ukemi** [comment]
I don't think so, but as I said above it all depends on how you slice and dice the pathways.

**Comment by ValWood** [comment]
I added 
GO:0006536
will see what falls out next time
