### ISSUE TITLE
Matrix: Amino acid metabolism/ carbohydrate metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2534]
GOT2 | Aspartate aminotransferase, mitochondrial |   | gluconeogenesis |   | Reactome | Homo sapiens | TAS |   | aspartate aminotransferase pthr11879 | protein |   | Reactome:R-HSA-70263 | 20181127

glucomeogenesis seems odd for aspartate aminotransferase?

**Comment by deustp01** [comment]
In healthy humans where gluconeogenesis is a key part of the body's response to fasting, carbon skeletons derived from protein breakdown are a major source of carbon skeletons used for gluconeogenesis and the asparate aminotransferase reaction is a major proximate source of oxaloacetate , a key gluconeogenic intermediate. So this is another pathway boundary issue - Reactome (following some standard textbooks) treats this reaction as a part of gluconeogenesis. @ukemi?

**Comment by ukemi** [comment]
Correct, this is a boundary issue. For glycolysis, we opted for the textbook view thinking that their viewpoint was valid (at least more than mine). To account for this, we created different flavors of glycolysis with the various types of carbohydrate inputs. It would make sense to do this with gluconeogenesis as well to represent the overall view of the process.

**Comment by ValWood** [comment]
OK I will add an exception for this. I wasn't sure where it was wrt glycolysis and I didn't have an exception for it.
