### ISSUE TITLE
Matrix: amino acid metabolism/carbohydrate metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2535]
"gluconeogenesis" seems incorrect for tyrosine aminotransferase?

Tat | tyrosine aminotransferase |   | gluconeogenesis |   | RGD | Rattus norvegicus | TAS |   | family not named pthr45744 | gene |   | PMID:2863382RGD:1299072 | 20050217

**Comment by gthayman** [comment]
Annotation deleted.
