### ISSUE TITLE
Matrix: does thiosulfate sulfurtransferase, involved in tRNA wobble position thiolation act on free amino acids

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2536]
I can add an exception for this, but I don't know if these are all correct:

tum1 | thiosulfate sulfurtransferase, involved in tRNA wobble position thiolation Tum1 (predicted) |   | thiosulfate sulfurtransferase activity |   | PomBase | Schizosaccharomyces pombe | ISO | SGD:S000005777 | thiosulfate sulfertansferase pthr11364 | protein |   | GO_REF:0000024 | 20060206

I wasn't aware of these activities on free amino acids:

tum1 | thiosulfate sulfurtransferase, involved in tRNA wobble position thiolation Tum1 (predicted) |   | 3-mercaptopyruvate sulfurtransferase activity |   | UniProt | Schizosaccharomyces pombe | IEA | EC:2.8.1.2 | thiosulfate sulfertansferase pthr11364 | protein |   | GO_REF:0000003 | 20190601

tum1 | thiosulfate sulfurtransferase, involved in tRNA wobble position thiolation Tum1 (predicted) |   | transsulfuration |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN002604081RGD:620065 | thiosulfate sulfertansferase pthr11364 | protein |   | PMID:21873635 | 20190524

**Comment by ValWood** [comment]
Need advice from @hdrabkin ?
Will also ask tRNA metabolism expert

**Comment by ValWood** [comment]
Is this an in virto assay system,
3-mercaptopyruvate sulfurtransferase activity
Catalysis of the reaction: 3-mercaptopyruvate + cyanide = pyruvate + thiocyanate.

**Comment by ValWood** [comment]
I think this one is multifunctional. It appears to be involved in tRNA wobble position thiolation
and also  detoxify cyanide?

**Comment by hdrabkin** [comment]
Questions:
The evidence for these are ISO, IEA, and IBA
What literature is the PAINT derived from.
What experimental is the ISO based on.

Assume EC:2.8.1.2  is coming from a UniProt record. If so why did they assign this EC?

**Comment by ValWood** [comment]
Wikipedia page implicates this enzyme in cyanide detoxification.

A different cyanide-metabolizing pathway, 3-mercaptopyruvate sulfurtransferase (3-MPST, EC 2.8.1.2), which is more widely distributed in mammalian tissues than rhodanese, is being explored. 3-MPST converts cyanide to thiocyanate, using the cysteine catabolite, 3-mercaptopyruvate (3-MP). However, 3-MP is extremely unstable chemically. Therefore, a prodrug, sulfanegen sodium (2, 5-dihydroxy-1,4-dithiane-2,5-dicarboxylic acid disodium salt), which hydrolyzes into 2 molecules of 3-MP after being administered orally or parenterally, is being evaluated in animal models.[32][33]

 Crankshaw DL, Goon DJ, Briggs JE, et al. (December 2007). "A novel paradigm for assessing efficacies of potential antidotes against neurotoxins in mice". Toxicol. Lett. 175 (1–3): 111–7. doi:10.1016/j.toxlet.2007.10.001. PMC 2171362. PMID 18024011.
 Nagasawa HT, Goon DJ, Crankshaw DL, Vince R, Patterson SE (December 2007). "Novel, orally effective cyanide antidotes". J. Med. Chem. 50 (26): 6462–4. doi:10.1021/jm7011497. PMC 2274902. PMID 18038966.

**Comment by hdrabkin** [comment]
this page: https://en.wikipedia.org/wiki/3-mercaptopyruvate_sulfurtransferase
But they don't mention any involvement in tRNA base modification. Links to EC:2.8.1.2;

**Comment by hdrabkin** [comment]
BUT if it IS the same protein as tum1, then I guess it DOES have two catalytic activites.

**Comment by ValWood** [comment]
hmm,

there are 2 copies in human
MPST https://www.uniprot.org/uniprot/P25325
and TST https://www.uniprot.org/uniprot/Q16762
maybe there is some sub-functionalization (although this isn't clear, there is a mixture of processes)

yeast has one copy which is tRNA metabolism.
https://www.yeastgenome.org/locus/S000005777#go

I made the exception, but i'll keep an eye on it.
