### ISSUE TITLE
Remove "ferroxidase activity" from PANTHER:PTN000153092 (PTHR11431)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2537]
PANTHER:PTN000153092 currently results in "ferroxidase activity (GO:0004322)" being annotated to both light chain and heavy chain ferritin subunits.
This is incorrect and that GO term should be removed - only the heavy chain subunits (equivalent to the ancestral/bacterial single ferritin?) have this activity (see PMID:28349628 or PMID:16551544 for a couple of relevant reviews).

@hattrill

**Comment by marcfeuermann** [comment]
Annotation propagation within family PTHR11431 was indeed weird. I've reviewed the whole PAINT annotation for this family, blocking activity for several nodes including the light chain subunits. I've also removed several other annotations.

**Comment by sjm41** [comment]
thanks Marc!

**Comment by sjm41** [comment]
Hi @marcfeuermann 
Looks like this is still a problem or it's resurfaced: "ferroxidase activity" is still on this node and being inappropriately applied to fly and human ferritin light chain members (Fer2LCH / UniProtKB=A0A0B4KHF0) (FTL / UniProtKB=P02792)

http://www.pantree.org/node/annotationNode.jsp?id=PTN000153092

**Comment by marcfeuermann** [comment]
Strange. I've updated the family once again. Hope this time I made it right.

**Comment by sjm41** [comment]
Thanks Marc.
