### ISSUE TITLE
Remove "ferroxidase activity" from PANTHER:PTN000194708

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2538]
PANTHER: PTN000194708 (associated with family MULTI-COPPER OXIDASE (PTHR11709)) is currently annotated with "ferroxidase activity (GO:0004322)".

But not all multi-copper oxidases are ferroxidases - see PMID:20219675.
From the Introduction of that review: "Multicopper oxidases (MCOs) are a large family of enzymes that include, but are not limited to, laccases (p-diphenol:dioxygen oxidoreductase, E.C.1.10.3.2), ascorbate oxidases (l-ascorbate:dioxygen oxidoreductase, E.C.1.10.3.3), and ferroxidases (iron(II):dioxygen oxidoreductase, E.C.1.16.3.1)."

An example from Drosophila is the gene stw (FBgn0286203). This is an MCO that encodes a 'laccase'.  Currently, that gene gets an inappropriate "ferroxidase activity" annotation via this PAINT rule.

**Comment by sjm41** [comment]
tag @hattrill

**Comment by marcfeuermann** [comment]
Updated
