### ISSUE TITLE
Matrix: tRNA metabolism /cytoskeleton  ABP140

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2541]
this is the only record of actin filament bundle assembly for ABP40 (quite old)

ABP140	AdoMet-dependent tRNA methyltransferase and actin binding protein		actin filament bundle assembly		SGD	Saccharomyces cerevisiae S288C	IDA		methyltransferase-related pthr22809	gene		PMID:9467951	20110113

https://www.ncbi.nlm.nih.gov/pubmed/21792172 Cotranslational transport of ABP140 mRNA to the distal pole of S. cerevisiae. might account for early observations
?

**Comment by srengel** [comment]
i agree and have removed the actin filament bundle assembly for ABP140.
