### ISSUE TITLE
Matrix: tRNA metabolism/cytoskeleton organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2542]
elongator subunit:

SGD:S000000018	ATS1
microtubule cytoskeleton organization		IMP	SGD	2004-01-15	Shields CM, et al. (2003) PMID:13680156

and 
budding cell bud growth		IMP	SGD	2004-01-15	Shields CM, et al. (2003) PMID:13680156

**Comment by ValWood** [comment]
these are likely legacy annotation indirect effects of   the tNRNA modification (has pleiotrpoic phenotypes). All elongator phenotypes in fission yeast are suppressed by over expression of the modified RNAs

see
#1965
and tickets within for more background

**Comment by ValWood** [comment]
should this be regulation?
SGD:S000002205	SIT4 actin cytoskeleton organization		IMP	SGD	2002-12-11	Angeles de la Torre-Ruiz M, et al. (2002) PMID:12080055

(might be done already?)

**Comment by srengel** [comment]
Hi @ValWood i agree and have removed these annotations:
SGD:S000000018	ATS1
microtubule cytoskeleton organization	IMP	SGD	2004-01-15	Shields CM, et al. (2003) PMID:13680156

and
budding cell bud growth	IMP	SGD	2004-01-15	Shields CM, et al. (2003) PMID:13680156

**Comment by srengel** [comment]
also moved the SIT4 one down to regulation.
