### ISSUE TITLE
water dikinase PAINT propagation  (PTHR10256)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2543]
This looked odd. It seems not to have this activity in fly, but the annotation is transferred.
Also, oddly it is called  "selenide, water dikinase" in fly ?

![incorrect propagation](https://user-images.githubusercontent.com/7359272/60820893-597e5d80-a19a-11e9-87ee-9cc26a06490f.jpg)

@hattrill 
@marcfeuermann

**Comment by ValWood** [comment]
Another  example
![positive and negative](https://user-images.githubusercontent.com/7359272/60992052-a487a480-a343-11e9-90b8-50d9f7aadd69.jpg)

@pgaudet  I don't know who would deal with this, or even if it is on the correct tracker?

**Comment by pgaudet** [comment]
There is a bug with PAINT - @marcfeuermann emailed Anushya.

**Comment by hattrill** [comment]
#2502 just linking to reported issue regarding SelD

**Comment by hattrill** [comment]
(ps @ValWood Steven is doing a spot of renaming)

**Comment by ValWood** [comment]
;)

**Comment by pgaudet** [comment]
Asked Anushya again about this one.

**Comment by marcfeuermann** [comment]
Duplicated ticket. See https://github.com/geneontology/go-annotation/issues/2502#issuecomment-526073261
