### ISSUE TITLE
MAtrix : tRNA metabolism /cofactor metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2545]
Scully.

I haven't been able to figure the problem, but it seems to be

scu | scully | contributes_to | ribonuclease P activity |   | FlyBase | Drosophila melanogaster | IC | GO:0030678GO:0090646 |   | protein |   | FB:FBrf0232995PMID:27131785 | 20170604

scu | scully |   | mitochondrial tRNA processing |   | FlyBase | Drosophila melanogaster | IMP |   |   | protein |   | FB:FBrf0232995PMID:27131785 | 20160818

because scully appears to be a sterol dehydrogenase.

Although these annotations are older so I'm not sure...

**Comment by ValWood** [comment]
Yep there is a lot of data about the sterol DH role
https://www.uniprot.org/uniprot/O18404
so the tRNA processing seems to be the outlier.

I didn't check if it was a tandem fusion or something...

**Comment by hattrill** [comment]
Looks like some dual function magic:

The papers that describe the steriod dehydrogenase and mitochondrial ribonuclease P complex subunit look solid.

HSD17B10 human - paper identifies HSD17B10 as a component of RNase P:
https://europepmc.org/abstract/MED/18984158
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6102140/
HSD17B10 also has been known as 'mitochondrial RNase P subunit 2' https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/4800

**Comment by ValWood** [comment]
OK, for now, I will restrict the exception to
FB:FBrf0232995 because I think I saw Scully lurking in another intersection. This is a double red flag. 
If one of these is not ove turned I will refine to a specific activity, or family.
