### ISSUE TITLE
Matrix: amino acid biosynthesis /membrane organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2547]
SKL1 | shikimate kinase-like 1 |   | aromatic amino acid family biosynthetic process |   | TIGR | Arabidopsis thaliana | TAS |   |   | protein | TAIR:locus:2088469 | PMID:1338949TAIR:Publication:501683147 | 20070807

Hi Tanya, this is an old TAS from TAIR. Should we delete it?

**Comment by ValWood** [comment]
The abstract does not mention any involvement in  amino acid metabolism. it seems to be just a cloning.

Note that alos this has "NOTs" for shikimat kinase...

**Comment by tberardini** [comment]
Agreed.  I've removed the annotation.  Thanks.
