### ISSUE TITLE
Matrix: DNA replication /transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2548]
SMC3 | AT5G48600 |   | transmembrane transporter activity |   | TAIR | Arabidopsis thaliana | ISS | InterPro:IPR003439 |   | protein | TAIR:locus:2152526 | PMID:11346655TAIR:Publication:501680567 | 20190419

(this is smc3, condensin subunit)

**Comment by tberardini** [comment]
I removed the 'transmembrane transporter activity' annotation.
