### ISSUE TITLE
Atg8 ligase activity (GO:0019776)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2549]
"Atg8 ligase activity" (GO:0019776; Def: "Catalysis of the covalent attachment of the ubiquitin-like protein Atg8 to substrate molecules; phosphatidylethanolamine is a known substrate.") is currently a child of the high-level term "transferase activity" (GO:0016740).

From the synonyms, seems this single term is meant to encompass both E2 conjugating and E3 ligase (transferase) activities acting on Atg8?  May be a case for splitting these into 2 terms - e.g. see PMID: 18704115.

If it stays as a single term, then it seems it should be a child of "ubiquitin-like protein transferase activity" (GO:0019787; Def: Catalysis of the transfer of a ubiquitin-like from one protein to another via the reaction X-ULP + Y --> Y-ULP + X, where both X-ULP and Y-ULP are covalent linkages. ULP represents a ubiquitin-like protein.)

If the term is split, then the E2 and E3 terms can go under these more specific terms:
ubiquitin-like protein conjugating enzyme activity (GO:0061650)
ubiquitin-like protein ligase activity (GO:0061659)

@hattrill

**Comment by sjm41** [comment]
Hi @kaxelsen - any thoughts/insights on this one?

**Comment by kaxelsen** [comment]
I think you should ask @marcfeuermann about this. He has worked on the autophagy system.

What I noticed during my brief attempt to understand the system is that the equivalent to E1 is Atg7, so I assume Atg8 is equivalent to E2. A target for Atg8 is Atg19 (an E3?).

What I also noticed was that in UniProtKB/Swiss-Prot the term is not found in one single Atg8 entry, but in Atg12, Atg3, Atg16, a few Atg5 entries and in TIPD_DICDI. Most of the annotations had the ECO codes: IBA:GO_Central and IEA:EnsemblFungi

**Comment by sjm41** [comment]
Ah, I think I see the issue now.  Atg8 ligases transfer Atg8 to phosphatidylethanolamine (which isn't a protein...) at the membrane, so we can't have this term being a child of terms defined as acting on a protein.

That said, we do need a new term 'Atg8 conjugating enzyme activity' for the E2 enzyme (which is known to be ATG3) - that does act on proteins, so can slot in as a sister to the other E2s in GO.  Then, we could consider  a new parent term 'Atg8 transferase activity' directly under the 'transferase activity' term, having both there existing 'Atg8 ligase activity' and the new 'Atg8 conjugating enzyme activity' terms as children.

I will close this ticket, and make a new one for this suggestion in the gene ontology tracker.

**Comment by sjm41** [comment]
New ticket is: https://github.com/geneontology/go-ontology/issues/17675
