### ISSUE TITLE
Review annotations to 'has_agent' AE relation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2551]
Aften looking at the snapshot error report I have identified that the UCL team has used the 'obsolete' has_agent relation in 112 annotations. Need to look at these and consider if this was the right relation to use. If there are no other relation that could be used to capture this information raise a query with Kimberly.

BHF-UCL 10
ARUK-UCL 98
Parkinson's-UCL 4
AgBase 50
UniProt 31
MGI 13
CAFA 1

I have not notified groups as I am not convinced that this is a priority at the moment. I think UCL should look at our annotations and with Kimberly and others try to provide guidance about the AE relation to use instead of has_agent

If the AE relation has_agent definately is obsoleted then need to ask Alex to include this in a Protein2GO error report and also to remove this option from the list of AE relations available in Protein2GO
Note useful QuickGO URL for this query https://www.ebi.ac.uk/QuickGO/annotations?extension=has_agent

**Comment by pgaudet** [comment]
Hi @RLovering 

I created a spreadsheet here: 
https://docs.google.com/spreadsheets/d/1500SKVGbpMiufAT_3ehuqRc1gqaO_PIzIr9w89FBzM4/edit?usp=sharing

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

you also created the spreadsheet from the MF relations table 
https://docs.google.com/spreadsheets/d/1TEdjaIz4gBW6oCjcMabrFEOHyXSLwAOen7T9bE0EpoE/edit#gid=0 which has 4 MF annotations rather than the 2 on the table above. I think you should delete the other table so that there is only one available

**Comment by pgaudet** [comment]
Deleted the table with 2 annotations. Thanks for pointing that out !

**Comment by RLovering** [comment]
as this is mentioned in another ticket I am closing this ticket although the issue about how to capture the information currently captured using has_agent is still not resolved.
