### ISSUE TITLE
Matrix: sororin (cdca5) isn't a cohesin subunit PTHR31092

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2552]
primary annotation was removed a while ago:
PAINT mapping still present:

![iba panther cohesin](https://user-images.githubusercontent.com/7359272/61039790-55835300-a3c7-11e9-9218-d3db28acd5c0.jpg)

**Comment by pgaudet** [comment]
There is still on MGI annotation that needs to be removed: 
Q9CPY3 colocalizes_with cohesin complex - 
' colocalizes_with' are not allowed with protein-containing complexes @hdrabkin 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
This term isn't propagated anymore in family PTHR31092. The IBAs should disappear in the next release. 
Human and Mouse have still had primary annotation. I've removed the annotations by Swiss-prot and we contacted MGI to do so.

**Comment by hdrabkin** [comment]
Hi @pgaudet 
There are two in mgi but are from and IDA from GOA_UniProt (PMID:21111234) and an ISO from our UniProt load (coming from PMID:17349791 for human)
If I remove them they will come back unless UniProt does something.

**Comment by pgaudet** [comment]
I removed the UniProt annotation. All done then :)

**Comment by hdrabkin** [comment]
So whenever a new goa gaf appears they will disappear from MGI.
