### ISSUE TITLE
PAINT: PTN002154029 interferon terms propagated to invertebrates

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2553]
-positive regulation of type I interferon production
-interferon-beta production 
Interferons are a vertebrate thing, so could you block propagation to us inverts?

I will look into the GO and see if some taxon constraints can be added.

Another thing:

As you can see, this is also an example of a regulation and direct annotation to a process

(As is:
positive regulation of defense response to virus by host 
defense response to virus)

This should probably be folded into a sanity check.

**Comment by hattrill** [comment]
Note to say that interferon-related terms such as production and receptor signlaing don't seem to be grouped under common parent - makes it difficult to make a global taxon fix.

**Comment by marcfeuermann** [comment]
I've reviewed the annotation for PTHR34339 by restricting interferon-related stuff to vertebrates.
As these proteins are "facilitators of innate immune signaling that act as a sensors of cytosolic DNA from bacteria and viruses and promote the production of type I interferon". I've propagated only regulation terms.
I've added also the role in autophagy for these proteins.
