### ISSUE TITLE
IPR006655 NOT electron transfer activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2557]
The definition of GO:0009055 electron transfer activity is 'Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient.' 

Most oxidoreductases are not part of the electron transport chain; I dont think IPR006655 is. Please remove mapping. 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Thank you for this. I have deleted this Go term. 
Regards, 
Hsin-Yu
