### ISSUE TITLE
Suspected error in gaf file

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#2560]
MGI's  weekly GOA load ran into a problem last night because our loader didn't know what to do with three entries.
These were found in the "gene product"/isoform field
UniProtKB:Q3TMQ6:PRO_0000415440

The loader is not expecting two colons
Should there not be a pipe? UniProtKB:Q3TMQ6|PRO_0000415440
Can't seem to find the documentation about this.
The annotations are old (2017) but the ids above must have been added recently because we had no error before. 
These are coming from UniProt (as part of the GOA load) so I'm pinging 
@ggeorghiou (first on the list of UniProt contacts).

**Comment by alexsign** [comment]
@hdrabkin Hi Herald,
no, the ":" syntax in the identifier is correct one.
here, from db-xrefs.yaml (https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml) for UniProtKB:

id_syntax: ([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z]([0-9][A-Z][A-Z0-9]{2}){1,2}[0-9])((-[0-9]+)|:PRO_[0-9]{10}|:VAR_[0-9]{6}){0,1}

which basically means UniProtKB:Q3TMQ6 can be referenced by itself, or with :PRO_XXXXXXXX, or :VAR_XXXXXXX at the end. 

yes, these are old annotations. The data was in GPAD file, but not in GAF before last release. There was a bug related to col 17 in GAF file which is fixed now. 

Alex

**Comment by hdrabkin** [comment]
Thanks for your comment. 
We are concerned about generating GPAD and GAF after importing (we got them in, but getting them into the GPAD might be a parser problem. Any hints or shortcuts you might have would be appreciated
(parser does not expect > 1 colon in any entry).

**Comment by alexsign** [comment]
Hi Harold,
I don't think I know any easy way around it. You can always relax you constrain in the parser, which is checking for ":" sign, or ignore data which doesn't fit your rules. However, the proper way to deal with input and output GO annotation data is to use the GO consortium metadata, go_rules and constrains. It will require time to implement, but it is the best way to make sure consistence between the consortium groups.
Alex

**Comment by hdrabkin** [comment]
HI @alexsign 
I was wondering if you could easily give me a human annotation that has similar ids
 ie UniProtKB:something:PRO_something
We'd like to check it out in Amigo 
Thanks
Harold

**Comment by alexsign** [comment]
here is couple of examples

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q14790&reference=PMID:10508785
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P12838&reference=PMID:15616305

I'm not sure if you can find them in AmiGO though

**Comment by hdrabkin** [comment]
I see quickgo does not link out properly using these in the inferred from field. 
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q14790&reference=PMID:10508785 (you get page not found if you click on it). Is this an error on how Quickgo links out or is it that it is not a format that UniProt itself does not parse properly?

as for the PMID:10508785 , you list these as annotation objects but they do not appear to link out to UniProt 
UniProtKB:P12838:PRO_0000006782; 
How do you put these in gaf or gpad.

**Comment by alexsign** [comment]
if it's GPAD 1.x col2 will have Q14790:PRO_0000004629
if it's GAF 2.x col17 will have UniProtKB:Q14790:PRO_0000004629 
as it is outlined in the file format specs. you can download both formats from QuickGO to have examples handy

**Comment by hdrabkin** [comment]
So you don't worry that a user of QuickGO cannot link out to UniProt to see what exactly the id is?

**Comment by alexsign** [comment]
Yes, I do. This is the bug in QuickGO, and I've repotted it to our web development team. Hopefully, it will be fixed soon.

**Comment by ValWood** [comment]
@alexsign can this one be closed?

**Comment by alexsign** [comment]
@ValWood yes, the link out to UniProt works fine now
