### ISSUE TITLE
PAINT annotations disregarded the 'NOT...' qualifier

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-annotation#2561]
Hi @huaiyumi 

@RLovering and were looking at annotations for ABCB4. 

BHF-UCL previously annotated this protein in human as 'NOT|enables' 'ceramide floppase activity' and 'NOT|involved_in' 'ceramide translocation' (IDA evidence).

Today we noticed that a few GO_Central annotations for orthologues of the human ABCB4 have the annotations 'enables/involved_in' 'ceramide floppase activity/translocation'. These have the IBA evidence, so we thought these were probably propagated by PAINT.

Please see the QuickGO screenshots below for examples.

Could you please check these IBA annotations? If they are based on the BHF-UCL IDA annotations, then it looks like there is a bug, as they should have been propagated with the 'NOT' qualifiers.

Thanks,
Barbara

<img width="1148" alt="Screenshot 2019-07-17 at 11 26 27" src="https://user-images.githubusercontent.com/16541096/61380429-07cc8600-a8b2-11e9-822b-22f797af8b96.png">
<img width="1239" alt="Screenshot 2019-07-17 at 11 26 00" src="https://user-images.githubusercontent.com/16541096/61380430-08651c80-a8b2-11e9-8671-0a261a4ab460.png">

**Comment by BarbaraCzub** [comment]
Hi @huaiyumi 

I was wondering whether you have had a chance to look into this yet? At UCL we feel this is quite an important point that should be addressed asap to ensure users do not get erroneous annotations in analysis results.

Atm, ABCB4 experimentally-evidenced 'NOT' annotations get propagated without the 'NOT' qualifier. All annotations for human, mouse and rat ABCB4 to either ceramide floppase activity or translocation can be viewed here: https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=UniProtKB:Q08201,UniProtKB:P21439,UniProtKB:P21440&goId=GO:0099038,GO:0099040&goUsageRelationships=is_a,part_of,occurs_in&goUsage=descendants and the 'NOT' annotations are the only ones with experimental IDA evidence.

In terms of the other annotations for for _human_ ABCB4, one of the evidence codes is IBA, which is why @RLovering and I thought this propagation would have been done by PAINT (is this right?). However, there are also two IEA annotations (from GOC) that should not have been propagated without the 'NOT'. There are no experimentally-evidenced annotations to these terms for the mouse and rat orthologues, so perhaps the IEA propagation was done from another source. Or maybe they were propagated from another ABCx family member? Anyhow, if experimental IDA evidence resulted in the 'NOT' annotations, then surely the IBA and IEA annotations should be consistent with this?

I'm copying in @pgaudet @vanaukenk @ValWood and @thomaspd in case they may be able to explain the origin of the IEA annotations and/or comment on the IBA annotation.

Thanks,
Barbara

**Comment by ValWood** [comment]
Actually- this does seem to be a type of  transmembrane transport, so  instead it seem that the ontology will need to be rearranged, and the  appropriate parents will need to be added.

https://github.com/geneontology/go-ontology/issues/1767

**Comment by ValWood** [comment]
Ah -but you are saying this is NOT a  ceramide floppase?

This just seems like transfer from a close relative via PAINT, so this is a PAINT curation issue more likely than a pipeline issue?

TAgging @marcfeuermann

**Comment by BarbaraCzub** [comment]
Thanks!

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 

If you look at the 'with' information, the annotations for ABCB4 orthologs (like F7ED09) are based on ABCB1 (P08183), not on ABCB4 (P21439)

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/4782928/62614332-79c14980-b90b-11e9-88a4-8e4e7ad2e299.png">

So we are not ignoring the NOT evidence. 

Pascale

**Comment by pgaudet** [comment]
There IS a PAINT update issue, however: 
the family nodes moved around. The ABCB4 node didn't used to be annotated for ceramide floppase activity, and it now is (see screenshots) 

Panther13: 


<img width="965" alt="image" src="https://user-images.githubusercontent.com/4782928/62614626-1683e700-b90c-11e9-9831-98a391100191.png">

Panther 14: 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/4782928/62614572-fd7b3600-b90b-11e9-85bb-d0cca22082eb.png">


We are trying to figure out ways to pick up these cases, but it's very tricky. Thanks for reporting any odd looking family. 

I'll remove the propagation of the 'ceramide floppase activity' from the ABCB4 node.

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Thank you!
