### ISSUE TITLE
matrix mRNA splicing via spliceosome / Group II intron splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2562]
I will create a rule for this 
Group II intron splicing is a different mechanism of splicing than  mRNA splicing via spliceosome

Pombe has one too but it hasn't made it through top the GO database yet.

OTP51 | AT2G15820 |   | Group II intron splicing |   | TAIR | Arabidopsis thaliana | IMP

This has also been painted

**Comment by tberardini** [comment]
updated annotations 
   http://doi.org/10.1111/j.1365-313X.2008.03581.x
