### ISSUE TITLE
IPR000447 FAD-dependent glycerol-3-phosphate dehydrogenase

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2563]
Family IPR000447
FAD-dependent glycerol-3-phosphate dehydrogenase
is associated with the terms:
GO:0006072 glycerol-3-phosphate metabolic process
GO:0055114 oxidation-reduction process 
GO:0004368 glycerol-3-phosphate dehydrogenase (quinone) activity
GO:0009331 glycerol-3-phosphate dehydrogenase complex

In FlyBase, this is present in 5 proteins:
FBgn0013810	Dynein heavy chain at 36C	Dhc36C
FBgn0033190	Glycerophosphate oxidase 2	Gpo2
FBgn0033388	-	CG8046
FBgn0028848	Glycerophosphate oxidase 3	Gpo3
FBgn0022160	Glycerophosphate oxidase 1	Gpo1

3/5 ok:
The Glycerophosphate oxidases are fine, but it's hitting these others:
Dhc36C (dynein heavy chain) and CG8046 (solute carrier family)

So, I am wondering if this signiture not specific/dinctinct enough to propagate terms from?

**Comment by hattrill** [comment]
Tagging @happy-lorna for InterPro

**Comment by EBI-Hsinyu** [comment]
Hi Helen, 
This entry overhit these proteins due to an signature (PS00978) we integrated in. I have removed this signature from this entry. So, the GO terms won't be given to these proteins you mentioned in your e-mail. 

Hsin-Yu
