### ISSUE TITLE
GO:1990112: RQC complex

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-annotation#2565]
One of our prokaryote specialists at UniProt mentioned that there seems to be an RQC complex in bacteria, but the large ribosomal subunit is 50S not 60S. We should change the definition from:
"A multiprotein complex that forms a stable complex with 60S ribosomal subunits containing stalled polypeptides...."
to:
"A multiprotein complex that forms a stable complex with **large** ribosomal subunits containing stalled polypeptides..."
Regards,
Marc.

**Comment by pgaudet** [comment]
Moved to correct tracker: 
https://github.com/geneontology/go-ontology/issues/17644
