### ISSUE TITLE
transporter activities transmembrane/intermembrane/intramembrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2567]
I thought these 3 types of transporter were mutually exclusive
GO:0022857	transmembrane transporter activity 
GO:0140303    intramembrane lipid transporter activity (flippase/floppase)
GO:0120013 lipid transfer activity  (this is the term defined as intermembrane transport)

but we have quite a few annotations in the intersections:

![matrix](https://user-images.githubusercontent.com/7359272/61966903-dcd9e480-afcb-11e9-9154-fc480b07b69b.jpg)

**Comment by ValWood** [comment]
This would deal with the fungal annotations in the 
GO:0022857	transmembrane transporter activity
GO:0140303 intramembrane lipid transporter activity (flippase/floppase)
intersection

Many come from the same gene having both
	ATET_09726			ATPase-coupled intramembrane lipid transporter activity		AspGD	Aspergillus terreus NIH2624	IEA	InterPro:IPR006539		gene_product		AspGD_REF:ASPL0000166200	20190701
I will look into this one

and
	ATET_09726			ATPase-coupled cation transmembrane transporter activity		AspGD	Aspergillus terreus NIH2624	IEA	InterPro:IPR001757		gene_product		AspGD_REF:ASPL0000166200	20190701


SGD

DNF1	Aminophospholipid translocase (flippase)	Saccharomyces cerevisiae S288C	family not named pthr24092	gene	SGD	YER166W
aminophospholipid-translocating P4-type ATPase DNF1


should not have
	DNF1	Aminophospholipid translocase (flippase)		ion transmembrane transporter activity, phosphorylative mechanism		SGD	Saccharomyces cerevisiae S288C	IMP		family not named pthr24092	gene		PMID:11932440	20141205
	DNF1	Aminophospholipid translocase (flippase)		ion transmembrane transporter activity, phosphorylative mechanism		SGD	Saccharomyces cerevisiae S288C	ISS	UniProtKB:P13586	family not named pthr24092	gene		PMID:9224683	20141205
	DNF1	Aminophospholipid translocase (flippase)		ion transmembrane transporter activity, phosphorylative mechanism		SGD	Saccharomyces cerevisiae S288C	ISS	UniProtKB:P13587	family not named pthr24092	gene		PMID:9224683	20141205
	DNF1	Aminophospholipid translocase (flippase)		ATPase-coupled intramembrane lipid transporter activity		UniProt	Saccharomyces cerevisiae S288C	IEA	EC:7.6.2.1	family not named pthr24092	gene		GO_REF:0000003	20190622

	NEO1	Phospholipid translocase (flippase), role in phospholipid asymmetry o	Saccharomyces cerevisiae S288C	family not named pthr24092	gene	SGD	YIL048W
putative aminophospholipid-translocating P4-type ATPase NEO1


should not have 
	NEO1	Phospholipid translocase (flippase), role in phospholipid asymmetry o		ion transmembrane transporter activity, phosphorylative mechanism		SGD	Saccharomyces cerevisiae S288C	ISS	UniProtKB:P13586	family not named pthr24092	gene		PMID:9224683	20070301
	NEO1	Phospholipid translocase (flippase), role in phospholipid asymmetry o		ion transmembrane transporter activity, phosphorylative mechanism		SGD	Saccharomyces cerevisiae S288C	ISS	UniProtKB:P13587	family not named pthr24092	gene		PMID:9224683	20070301

**Comment by ValWood** [comment]
The remaining annotations are to these panther families, need to check these 

+ | − | (19) | atp-binding cassette transporter subfamily a abca pthr19229
-- | -- | -- | --
+ | − | (12) | family not named pthr24221
+ | − | (12) | ngep-related pthr12308
+ | − | (4) | major facilitator superfamily domain-containing protein pthr11328
+ | − | (2) | family not named pthr24092
+ | − | (1) | family not named pthr24223

**Comment by ValWood** [comment]
easy, we can delete this one: @pgaudet 

ATP11B | Probable phospholipid-transporting ATPase IF |   | ion transmembrane transporter activity |   | UniProt | Homo sapiens | NAS |   | family not named pthr24092 | protein |   | PMID:11790799 | 20040315


ATP8A1 | Phospholipid-transporting ATPase IA |   | ATPase-coupled cation transmembrane transporter activity |   | UniProt | Homo sapiens | NAS |   | family not named pthr24092 | protein |   | PMID:10198212 | 20030403
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
pthr24223

Abcc1 | ATP binding cassette subfamily C member 1 |   | ATPase-coupled intramembrane lipid transporter activity |   | RGD | Rattus norvegicus | ISO | RGD:1344624 | family not named pthr24223 | gene |   | PMID:17050692RGD:1624291 | 20170831

**Comment by ValWood** [comment]
pthr11328
all are derived from:

Mfsd2a | major facilitator superfamily domain containing 2A |   | lysophosphatidylcholine flippase activity |   | GO_Central | Mus musculus | IDA |   | major facilitator superfamily domain-containing protein pthr11328 | protein |   | PMID:26945070 | 20190529

Major facilitator superfamily domain containing 2A (MFSD2A) was recently characterized as a sodium-dependent lysophosphatidylcholine transporter expressed at the blood-brain barrier endothelium. It is the primary route for importation of docosohexaenoic acid and other long-chain fatty acids into fetal and adult brain and is essential for mouse and human brain growth and function. Remarkably, MFSD2A is the first identified major facilitator superfamily member that uniquely transports lipids, implying that MFSD2A harbors unique structural features and transport mechanism. Here, we present three three-dimensional structural models of human MFSD2A derived by homology modeling using MelB- and LacY-based crystal structures and refined by biochemical analysis. All models revealed 12 transmembrane helices and connecting loops and represented the partially outward-open, outward-partially occluded, and inward-open states of the transport cycle. In addition to a conserved sodium-binding site, three unique structural features were identified as follows: a phosphate headgroup binding site, a hydrophobic cleft to accommodate a hydrophobic hydrocarbon tail, and three sets of ionic locks that stabilize the outward-open conformation. Ligand docking studies and biochemical assays identified Lys-436 as a key residue for transport. It is seen forming a salt bridge with the negative charge on the phosphate headgroup. Importantly, MFSD2A transported structurally related acylcarnitines but not a lysolipid without a negative charge, demonstrating the necessity of a negatively charged headgroup interaction with Lys-436 for transport. These findings support a novel transport mechanism by which lysophosphatidylcholines are "flipped" within the transporter cavity by pivoting about Lys-436 leading to net transport from the outer to the inner leaflet of the plasma membrane.

This implies that  the transmembrane transport annotations to Mfsd2 and orthologs needs to be reviewed.

Although now, I am unsure whether this mechanism (flipping) is the only mechanism to move lipids from one membrane to another. ie. this raises the question as to whether this mechanism is also used to get lipids from outside to inside a cell (i.e dietary lipids). This could be a 2-step process (embed in outer leaflet, transfer from outer to inner leaflet, extrude into cell), or, even if they remain in the inner membrane.

This is important to find out because  if it remains in the membrane it isn't "transmembrane transport" which is explicity defined 
"Transmembrane transport is the transport of a solute across a lipid bilayer."

**Comment by ValWood** [comment]
atp-binding cassette transporter subfamily a abca pthr19229
--

Possibly this is a flippase.
But it does seem to bring the lipids "through" the membrane, which is transmembrane transport.

In yeast the genes  families annotated as  "intra" and "intermembrane" transfer proteins only move  lipids between membranes , and not into compartments.

If possible we should keep to this more restricted terminology, but this might not be possible.

**Comment by ValWood** [comment]
ngep-related pthr12308

There are also NOT annotations to this term, and positive annotations to "scramblase"

ANO9 | Anoctamin-9 |   | intracellular calcium activated chloride channel activity |   | UniProt | Homo sapiens | IMP |   | ngep-related pthr12308 | protein |   | PMID:22946059 | 20140424

**Comment by ValWood** [comment]
SGD ones and NAS/TAS easy to fix so assigning to @pgaudet  and @srengel 

Others  need a little bit more knowledge about the transport processes @pgaudet  and @ValWood  can look into this in the future (may need an expert input)

**Comment by ValWood** [comment]
@RLovering  pthr19229
are floppases, so for this one we will need to review the transmembrane transport annotations

Although previous cell-based studies have implicated ABCA1 and ABCA7 in the efflux of phospholipids and cholesterol from cells as a critical step in the reverse cholesterol transport pathway, it has been unclear if these proteins directly transport these lipids across the membrane or simply mediate lipid transfer to apo-A1 through an indirect “regulatory” mechanism (45). In this study, we provide the first direct biochemical evidence that ABCA1 and ABCA7 transport or flip specific phospholipids from the cytoplasmic leaflet to the exocytoplasmic leaflet of the lipid bilayer, and we determine the phospholipid specificity for these ABCA transporters. This was achieved through analysis of ATP-dependent transport of Fl-PL by these transporters and supported by the stimulation of their ATPase activity by the same phospholipids.

**Comment by srengel** [comment]
i have deleted these 3 from DNF1 and 2 from NEO1:
	DNF1	Aminophospholipid translocase (flippase)
ion transmembrane transporter activity, phosphorylative mechanism	SGD	Saccharomyces cerevisiae S288C	IMP	family not named pthr24092	gene	PMID:11932440	20141205

 	DNF1	Aminophospholipid translocase (flippase)
ion transmembrane transporter activity, phosphorylative mechanism	SGD	Saccharomyces cerevisiae S288C	ISS	UniProtKB:P13586	family not named pthr24092	gene	PMID:9224683 20141205

 	DNF1	Aminophospholipid translocase (flippase)
ion transmembrane transporter activity, phosphorylative mechanism	SGD	Saccharomyces cerevisiae S288C	ISS	UniProtKB:P13587	family not named pthr24092	gene	PMID:9224683 20141205

NEO1	Phospholipid translocase (flippase), role in phospholipid asymmetry ion transmembrane transporter activity, phosphorylative mechanism	SGD	Saccharomyces cerevisiae S288C	ISS UniProtKB:P13586	family not named pthr24092	gene	PMID:9224683	20070301
 
	NEO1	Phospholipid translocase (flippase), role in phospholipid asymmetry
ion transmembrane transporter activity, phosphorylative mechanism	SGD	Saccharomyces cerevisiae S288C	ISS	UniProtKB:P13587	family not named pthr24092	gene	PMID:9224683 20070301

but this one needs to be removed by UniProt:
DNF1	Aminophospholipid translocase (flippase)	ATPase-coupled intramembrane lipid transporter activity	UniProt	Saccharomyces cerevisiae S288C	IEA	EC:7.6.2.1	family not named pthr24092	gene	GO_REF:0000003	20190622

**Comment by ValWood** [comment]
thanks @srengel !

**Comment by RLovering** [comment]
Thank you so much with your help on these. I have deleted the ABCA1 annotation, but other PAINT has contributed ATPase-coupled transmembrane transporter activity. The ABCA7 annotations we have made are to the floppase term, the ATPase-coupled transmembrane transporter activity term is from PAINT from mouse Abca8 O94911 and various others.

I am going to leave you to decide about the cholesterol transfer activity term, it looks OK to me.

But I do not find the definition of ATPase-coupled transmembrane transporter activity specific enough, couldn't there be some sort of statement that the transported molecule will not be embedded in the membrane across which it was transported? if that is the difference between these activities

Thanks

Ruth

**Comment by ValWood** [comment]
It seems that flippases/floppases  *should* be classified as transmembrane transporters. I opened a ticket  for this.
https://github.com/geneontology/go-ontology/issues/17672

I think it was still correct to remove the "ion transmembrane transporter terms" above because the flippase/floppase is specific for lipids.

**Comment by suzialeksander** [comment]
This looks like everything has been deleted/changed as needed.
