### ISSUE TITLE
family not named pthr24221 PAINT

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2568]
This family is painted as a transmembrane transporter  probably from the family root, but this sub-family  branch appears to be floppases?

**Comment by marcfeuermann** [comment]
Hi Val,
Not sure which sub-family branch you are talking about. Annotation to node PTN002516971 that contains ABCB1 and ABCB4 has been modified to floppases after we have created the new terms (transmembrane transporter has been removed). was it this one ?
Thanks,
Marc.

**Comment by ValWood** [comment]
It's OK.
I  made a mistake with this one actually.

Floppases are considered to be transmembrane transporters anyway. The ontology needs to be fixed to reflect this:
https://github.com/geneontology/go-ontology/issues/17672
