### ISSUE TITLE
Matrix GO:0120013/ GO:0140303

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2569]
- [ ] UniProtKB:O95477 | ABCA1 | enables | GO:0120020    cholesterol transfer activity | ECO:0000314   IDA | PMID:12084722 |   | 9606 Homo sapiens | BHF-UCL

this term refers to intermembrane transfer and I think here Ruth is annotating "intermembrane transfer" or "flipping

I was also confused by this, I think the term needs to be more explicit, I mentioned this to @pgaudet  a few days ago:
https://github.com/geneontology/go-ontology/issues/17648

**Comment by RLovering** [comment]
Hi Val

in PMID: 12084722 Abstract they state: These results suggest that apoA-I-stimulated cholesterol efflux cannot occur without a direct interaction between the apoprotein and critical residues in two extracellular loops of ABCA1. The apoprotein is within the extracellular located HDL particle. statement from the intro: ABCA1 activity is associated with the transfer of cellular phospholipid and cholesterol  to  acceptor  apolipoproteins,  such  as  apoA-I .

See also this review: PMID:29305383. 

I therefore think that ABCA1 has both a floppase and cholesterol transfer activities.

Ruth

Therefore ABCA1 does not only transfer cholesterol as a floppase it also

**Comment by RLovering** [comment]
I thought flippase activity was from external to internal and floppase was internal to external, both are child terms of intramembrane lipid transporter activity.

HDL does not have a membrane

**Comment by ValWood** [comment]
OK where does ABCA1 transport from/to I'm confused and I could not figure it out from the paper.

These are the 3 classes of transporter that might be relevant:

![IMG_0447](https://user-images.githubusercontent.com/7359272/62052541-970c5e80-b20d-11e9-85a4-65c2d2705977.jpg)

I see- I had missed the fact this this can  transfer to a lipid particle and does not need to transfer to a membrane.

I was thinking of intermembrane transfer  like the sec14 cytosolic factor family and the osh family which do seem to switch lipids between membranes (intermembrane)

Anyway at least in PomBase we have no transmembrane transport of lipids, it is all described as "translocation", so it is possible that  lipid transport across a membrane is always translocation, and when transporter families which are normally doing "transmembrane transport"  are transporting lipids they must be  using a translocation mechanism, even when the  lipid does not remain in the membrane.

@pgaudet  I think we need to revisit some of these MF terms. I think we still need a way to describe the "intermembrane transfer". We don't  have this and we can't change the term as I suggested here: geneontology/go-ontology#17648
because this also includes the transfer to the HDL particle.

**Comment by ValWood** [comment]
I will create an exception for this sub-family, it does appear to be both

**Comment by RLovering** [comment]
good point, I am not sure where the lipid is to start, other than it is inside the cell, I have seen these described as lipid pools or lipid droplets https://www.ebi.ac.uk/QuickGO/term/GO:0005811. But it depends how much cholesterol is in the cell as to whether the cell has lipid droplets.

**Comment by ValWood** [comment]
OK, this makes sense. If it's lipid droplet to lipid droplet it fits the "intermembrane transfer" thing well...

I need to find out more about  membrane biology, it seems to be taking off in fission yeast...

**Comment by ValWood** [comment]
Anyway this is all good so I'll close this one.
