### ISSUE TITLE
Problem with PAINT PTN002514495 annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2572]
PTN002514495 is being used to propagate the GO term "ubiquitin conjugating enzyme activity" (GO:0061631) to Ubiquitin E2 Enzyme Variants (UEVs) that don't have this activity (they lack the catalytic cysteine).
Examples include:
Drosophila Uev1A (Q9VRL1) and morgue (Q9Y165)
Human UBE2V1 (Q13404) and UBE2V2 (Q15819)

**Comment by sjm41** [comment]
tagging @hattrill

**Comment by pgaudet** [comment]
Interesting. This node should have 'contributes_to', because it works as a ubi ligase as a dimer (although it's not the active subunit). 

I removed the annotation for now, will bring this up to the PAINT group. 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
This is a huge and complex family. I've removed the activity everytime the catalytic cysteine was missing. The 'contributes_to' issue has still to be fixed.

**Comment by pgaudet** [comment]
Thanks !

**Comment by sjm41** [comment]
OK, thanks Marc.

**Comment by pgaudet** [comment]
Adding contributes_to to the specific child node needs some new developments in PAINT.

**Comment by sjm41** [comment]
Hi @pgaudet 
Earlier in this ticket you said "I removed the annotation for now", but I think something must have gone awry.

Looking at QuickGO today, I now see these 3 annotations to morgue (Q9Y165) and Uev1A (Q9VRL1), all associated with PTN002514495 - two positive, and one negative:
enables	ubiquitin conjugating enzyme activity (GO:0061631)	IBA	PANTHER:PTN002514495
enables	ubiquitin conjugating enzyme activity (GO:0061631)	IBA	PANTHER:PTN002514495
NOT|enables	ubiquitin conjugating enzyme activity (GO:0061631)	IBA	PANTHER:PTN002514495

Can you take another look at this?

**Comment by sjm41** [comment]
Hi @pgaudet, Can I give you a nudge to look at this please? Thanks!

**Comment by sjm41** [comment]
Also: I see in Protein2GO that fly UbcE2M (Q9VSF3) has recently acquired "ubiquitin conjugating enzyme activity" from PANTHER:PTN002514495. But this is a NEDD8 conjugating enzyme, so this propagation is wrong.

**Comment by sjm41** [comment]
@marcfeuermann @pgaudet - can you have another look at this one please?

Looking at protein2GO just now, I still see these incorrect IBA propagations of "ubiquitin conjugating enzyme activity" from PTN002514495:
Q9Y165 (fly morgue) - lack the catalytic cysteine needed for activity
Q9VSF3 (fly UbcE2M) = Nedd8 (not ubiquitin) conjugating enzyme
Q13404 (human UBE2V1) - ubiquitin conjugating enzyme activity (only works as dimer with UBE2N)
Q15819 (human UBE2V2) - ubiquitin conjugating enzyme activity (only works as dimer with UBE2N)

Does this (large) PANTHER family for this need splitting some more to account for different activities associated with members, or do more edits on the PAINT node need to be put in place?

**Comment by RLovering** [comment]
Q9D2M8 and Q9D2M8 are the source of the UBE2V1 and 2 annotations, I have emailed them, and requested these are removed
Ruth

**Comment by hdrabkin** [comment]
Q9D2M8 annotation: PMID used can't possible be correct in our db; must be typo but no way I can trace what it should have been
Its an IGI along with P61089 (Ube2n), Name  reference
Will need to remove

**Comment by marcfeuermann** [comment]
I've made the requested corrections. Indeed the family is huge and complicated and splitting would be a good idea.

**Comment by sjm41** [comment]
Thanks Marc - sounds promising!  I'll keep a look out for the improvements once your work filters through to the annotations in P2GO etc. Steven.
