### ISSUE TITLE
PANTHER:PTN000399371 problem

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2573]
Looks like this propagation of "ubiquitin protein ligase activity" (GO:0061630) is based on a single annotation to the mouse Gene Pdzrn3 (PDZ domain containing RING finger 3) (Q69ZS0).

It's resulted in that GO term being annotated to Drosophila Slip1 (Q8MR31).
But the fly gene lacks the RING finger domains - it's just got the PDZ bits - so is very unlikely to act as a E3 ligase.

Since the RING domains of Pdzrn3 aren't present in all PANTHER orthologs of Pdzrn3, I think this PAINT inference should either be tightened up or removed.

**Comment by sjm41** [comment]
@hattrill

**Comment by marcfeuermann** [comment]
Propagation of  "ubiquitin protein ligase activity" (GO:0061630) has been restricted to node PTN002694419 (one of the 3 vertebrate nodes, after the duplication event.).
Regards,
Marc.

**Comment by sjm41** [comment]
thanks Marc.
