### ISSUE TITLE
Somatomedin B domain (IPR001212)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2574]
Somatomedin B domain (IPR001212) is associated with GO terms:
GO:0030247 polysaccharide binding
GO:0005044 scavenger receptor activity 
GO:0006955 immune response 

This domain seems to be present in quite a few non-scavager/immune proteins e.g.
vitronectin - ECM proteins
tubulointerstitial nephritis antigen like 1 - ECM/adhesion
D.mel Swim FBgn0034709 -  wnt binding

Could you have a look at this? Thanks

@happy-lorna

**Comment by happy-lorna** [comment]
Hi Helen,
Yes you are correct, I have removed that GO terms from the domain entry. The changes will be visible in the next release.
cheers, Lorna.
