### ISSUE TITLE
Problem with PANTHER:PTN001188366 (PTHR24014)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2575]
PANTHER:PTN001188366 is resulting in these ubiquitination-related terms being added to the Drosophila genes brat (Q8MQJ9 ) and wech (Q9V4M2):
ubiquitin protein ligase activity (GO:0061630)
protein polyubiquitination (GO:0000209)

This is based on GO annotations to four different mouse TRIM genes, which are bona fide E3 ligases.

Problem is that brat and tech lack the RING domain that is necessary for E3 ligase activity.
For this reason, both these genes are classed as 'TRIM-like' - see PMID:23185523.  (quote from that pub: "detect several genes that are clearly related in sequence to canonical TRIM proteins, but lack part of the basic RBCC signature, normally either the RING finger or both B boxes. The genes encoding these “TRIM-like” proteins (between parentheses in Table 1) can be hypothesized to derive from typical TRIM genes, again by duplications followed by protein domain losses. "

So I think this PAINT rule needs tightening up if possible to avoid propagation of the ubiquitination terms to these TRIM-like proteins.

**Comment by pgaudet** [comment]
Hi @sjm41 

I removed the ubiquitin annotations from brat and wech; however according to UniProt they both have 2 B-boxes. Just wanted to point this out, as it seemed inconsistent with what you report from the paper. 

Thanks, Pascale
