### ISSUE TITLE
ECO and with/from inheritance for DNA binding proteins

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-annotation#2576]
As we transition from the old GO evidence to ECO for CACAO and GO annotation more generally, we may need to examine how we set up the rules for with/from. Example: We got this check on several of our CACAO gpad submissions 

> ERROR	With/from is mandatory for this evidence code	[[ECO:0007129 (IPI)] []]

The term is: ECO:0007129  chromatin immunoprecipitation-qPCR evidence used in manual assertion

It inherits the with/from requirement from a parent ECO:0000353  physical interaction evidence used in manual assertion, which is a synonym for the old IPI code. It's also a child of ECO:0000314  direct assay evidence used in manual assertion, which is the exact synonym for IDA.

Before switching to ECO we would have used IDA. Using ECO:0007129 is more informative, but in a ChIP assay, there are two physical interactions, and the more relevant one is a protein-DNA interaction. Which means there would need to be a DNA identifier in the with/from. Worse, this kind of evidence is for interaction with a region of DNA, where the interaction is somewhere between the genome coordinates defined by PCR primers in the case of qPRC. 

This will be an issue with other forms of DNA binding annotations ranging from ChIP-seq variants to ancient EMSA and filter binding assays. I suspect there are other kinds of IDA annotations that will have similar issues that don't involve DNA but have problems with a lack of accessions for the binding partner.

How should this be handled?

cc: @mgiglio99 and @nsuvarnaiari

**Comment by bmeldal** [comment]
IntAct is currently working on this issue. Please get in touch with @pporrasebi who is working with Ensembl and leads the effort of defining genomic coordinates for interaction partners. It's anything but trival!

**Comment by jimhu-tamu** [comment]
My initial thoughts on the IntAct approach: the nontrivial issues suggest that a better alternative might be to adjust the structure of ECO and the placement of the inherited with/from requirement. 

Note also that there are related issues for annotation extensions and GO-CAM models. IMO, what we want for extensions vs evidence are different where the the inference from authors might be captured without coordinates using SO and OBO-REL and gene identifiers.

Any solution involving genome coordinates will create the "lift-over" problem when genome releases change and coordinates change. Even in E. coli, version 2 and version 3 of NC_000913 have shifted coordinates due to adding an IS element near the start of the record.

**Comment by pgaudet** [comment]
@jimhu-tamu Did you contact ECO to see if the ontology can be reorganized ? CHIP as IDA makes sense to me. 

Pascale

**Comment by nsuvarnaiari** [comment]
Adding other ECO members ... @jbmunro  @beckyjackson @mchibucos.

**Comment by mgiglio99** [comment]
I actually have concerns with many of the terms under 'physical interaction evidence'.  This has come up before with other issues and leads to a can of worms. I think the IPI term in ECO leads to problems because  many kinds of evidence involve some kind of physical interaction. It becomes difficult to draw the line of what should be a child of 'physical interaction' and what shouldn't.  

It seems there are two ways to solve this:

1. change the structure of ECO
  a. move ChIP out from under 'physical interaction'
  b. get rid of 'physical interaction' term - but we can't really do this since it's needed for GO mappings.   Unless perhaps we can make more specific terms for the exact types of interactions that GO needs and not have the corresponding parent term in ECO? Haven't thought that idea through at all yet.

2. change the way the with/from rules are attached to ECO terms that are children of the GO code ECO terms.

**Comment by jimhu-tamu** [comment]
One possible approach would be to create a branch at the IPI synonym or its parent that is agnostic about manual vs automated assertion. 

Make the differentia based on whether the IPI partner requires a with from and attach some ECO classes like ChIP to the child where an accessionable partner is optional.

But this is not something where I’ve thought through the possible unintended consequences

**Comment by mgiglio99** [comment]
We solved these issues via the ability to provide ECO term-level mappings to GO evidence codes. In this new system, ECO terms do not map to GO codes solely based on the ECO structure, then can be manually mapped at the time of creation and will be moving forward with new terms. Old terms, as reviewed, will have their mappings updated to the correct GO evidence code mapping, even if they are a child of an upper level ECO term that has a direct mapping to a different GO evidence code.

**Comment by mgiglio99** [comment]
Oops - I thought I was closing an issue in ECO - but I was in GO - and I didn't want to take the liberty to close this GO issue.
