### ISSUE TITLE
InterPro: Ufmylation terms to associate with InterPro IPR014806 & IPR018611?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2579]
Hi InterPro,

What do you think about adding these GO terms in the InterPro2GO pipeline:

Ubiquitin-fold modifier-conjugating enzyme 1 (IPR014806)
- UFM1 conjugating enzyme activity (GO:0061657)
- protein ufmylation (GO:0071569)

E3 UFM1-protein ligase 1 (IPR018611)
- UFM1 ligase activity (GO:0061666)
- protein ufmylation (GO:0071569)

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by sjm41** [comment]
Hi @typhainepl  - can you take a look at this old ticket? Thanks.

**Comment by typhainepl** [comment]
Hi,
Thank you for the reminder. I have added the GO terms to the corresponding entries. The changes will be visible in InterPro 83.0.

**Comment by sjm41** [comment]
Thanks!
