### ISSUE TITLE
PTN000869255 contributes_to histone acetyltransferase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2580]
PTN000869255 contributes_to histone acetyltransferase activity is only supported by FBgn0043002 and we have removed this annotation (this will not appear until the FB gaf is released later in August).

Can I check, as I am not sure: if we remove a supporting annotation will this automatically be reflected in the subsequent PAINT release?

**Comment by pgaudet** [comment]
Fixed.

**Comment by pgaudet** [comment]
Maybe not. The family wouldn't save. I need to check this one again.

**Comment by pgaudet** [comment]
BTW @hattrill if the original annotation is removed, the IDBs/IBAs will go away (although there may be a little delay with GO releases and PAINT updates). So, if you report these it's great. 

Thanks, Pascale
