### ISSUE TITLE
Review annotations using extensions 'not_exists_during' and 'not_occurs_in'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2581]
Hello, 

We'd like to remove 'negative' relations from GO_REL (see https://github.com/geneontology/go-ontology/issues/17712). 

Can people please review their annotations and let us know if they can capture the data differently ? 
https://docs.google.com/spreadsheets/d/1irr4bikf43mj8pEXeYOAGJWtA6Bm4oTEfPg26eQw2yg/edit#gid=0

MGI: 2 annotations
pombase: 17 annotations

Thanks, Pascale

**Comment by ukemi** [comment]
MGI done

**Comment by pgaudet** [comment]
OK Pombase done, see https://github.com/geneontology/go-ontology/issues/17712
