### ISSUE TITLE
Review annotations using extension 'has_regulation_target'  for MF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2587]
Hello, 

To simplify the relations used for annotation extensions, we propose to use 'has_input' instead of 'has_regulation_target'. 

Annotations are here: 
https://docs.google.com/spreadsheets/d/1MwJaCUrPwrhgINBWRtA4XDODaOINN8aerFI_LwozT_g/edit#gid=0

If you agree, and if your annotations are in Protein2GO, no action is needed: we will ask for an automatic mapping. 

Assigned   by |  
-- | --
AgBase | 2
ARUK-UCL | 9
BHF-UCL | 28
CAFA | 7
dictyBase | 6
HGNC | 1
MGI | 153
NTNU_SB | 150
ParkinsonsUK-UCL | 10
PomBase | 198
SGD | 67
UniProt | 65
WB | 2

Thanks, Pascale

**Comment by ValWood** [comment]
Are these all MF or BP+MF?

Anyway, we decided on our group call this morning that we will keep these  relations locally (we have many more display labels that are even more specific).

Instead we will fix our GO submission file and map up to the has_input term.

There are multiple reasons for this decision, but mainly:

1. We like the more natural language these relationships present when we provide these annotations on our gene pages are much more human readable.
We don't these all to be has_input
https://www.pombase.org/gene/SPAC6G10.12c
https://www.pombase.org/gene/SPBC29B5.01
https://www.pombase.org/gene/SPBC216.05

2. Originally I thought we could  have a display label "has_direct_input" for "has_input". However, if we simultaneously map has_regulation_target to has_input we can no longer do this without configuring at multiple ontology subsets to  disentangle the different meanings.
 
3. A gene is not really a "direct input" for a transcription factor (the transcription factor regulates the RNA polymerase which regulates expression of the gene through specific promoters).  For this we would eventually like to display "regulates the expression of".

Although this might not be critical information for GO,  apart from looking better on the gene page, and being more precise, we believe we will make use of this information when we are constructing networks, so we don't want to lose what we have arduously captured to date.

Anyway, we can easily make sure GO has the requested info by mapping our submission up to the less informative relations.

**Comment by ukemi** [comment]
What about coactivator and corepressors? To distinguish between the partner and the regulated gene, we will have to use a different relation for the partner. I suspect this would work as an independent activity that would be regulated and also have the same input.

**Comment by ValWood** [comment]
Exactly. The direct_input of the coactivator/repressor is the transcription factor.
The genes are regulated_by, they aren't "direct input".
We want to keep this specificity at PomBase. Of course, you can figure it out based on the term but since we want to display the more specific labels anyway, for us it  would be more work to remove them, and then add them back in another way.

**Comment by ukemi** [comment]
For coactivators and corepressors it was decided we should use has_input.

**Comment by ValWood** [comment]
@mah11  will map Pombase ones to has_input for GO

**Comment by ukemi** [comment]
MGI done.

**Comment by pfey03** [comment]
dictyBase done

**Comment by BarbaraCzub** [comment]
The UCL annotations are in Protein2GO, so I'll remove my assignment here. Thanks!

**Comment by RLovering** [comment]
I agree with Barbara, The UCL annotations are in Protein2GO, so I'll remove my assignment here. and I have added Alex to this ticket

**Comment by pgaudet** [comment]
@alexsign Please change any remaining annotations in P2GO using 'has_regulation_target' to 'has input', and remove 'has_regulation_target' from the options in P2GO. 

Thanks, Pascale

**Comment by alexsign** [comment]
@pgaudet just a bit of stats before I start making changes. In case of external sources I cannot do much. Ones 'has_regulation_target' removed from go-plus.json it should disappear from the P2GO automatically.

UniProt (EBI Curators)	internal	1349
MGI	external	1095
AgBase	internal	600
AlzheimersResearchUK-UCL	internal	586
BHF-UCL	internal	575
NTNU	internal	539
ParkinsonsUK-UCL	internal	504
DictyBase	internal	172
SGD	internal	122
Automated Function Prediction SIG CAFA Experiment (UniProt Curators)	internal	107
FlyBase	internal	43
GO_Central	internal	10
WormBase	internal	6
GOC OWL Inferences	external	3
HGNC	internal	3
Withheld Manual Annotation	internal	2
Alzheimers Project at University of Toronto 	internal	2
UniProt (SIB Curators)	internal	1

**Comment by pgaudet** [comment]
Thanks @alexsign 
So, only MGI needs to update their annotations. @ukemi Is this under way ? 

Thanks, Pascale

**Comment by ukemi** [comment]
I'm massively confused. I thought @dustine32 was doing this as part of the import.

**Comment by vanaukenk** [comment]
I propose we re-visit this issue after the meeting.  

We need to make sure we're all on the same page about what is supposed to happen when and where.

**Comment by RLovering** [comment]
Hi Alex
please change all the UCL annotation relations 'has_regulation_target' to 'has_input'
Thanks
Ruth
@alexsign

**Comment by pgaudet** [comment]
@alexsign We'll want to do this for every source (this also applies to the other relations)

**Comment by pfey03** [comment]
HI Alex,
For us they have creeped in again. Please change dictyBase annotation extension relations also from 'has_regulation_target' to 'has_input'
Many thanks!
@alexsign

**Comment by alexsign** [comment]
@pfey03 @RLovering @pgaudet 
Updated in Protein2GO, available from QuickGO next week.

**Comment by RLovering** [comment]
Brilliant thanks
Ruth

**Comment by pfey03** [comment]
Thanks so much Alex!

**Comment by ValWood** [comment]
@pgaudet Oh shoot. I just went to remove myself from this ticket and removed all assignees.
IS there a  way to add back the people who still need to do?

**Comment by pfey03** [comment]
@ValWood this happened to me as well on another ticket a while back. Something strange with the git settings here.

**Comment by pgaudet** [comment]
@vanaukenk Can we go ahead and close this - and remove the 'has regulation target' from GOREL?

**Comment by pgaudet** [comment]
Not yet completed - there are still 40 annotations using 'has_regulation_target'; both MF and BP. I will ask Alex to do an automatic replacement to 'has input' 

Note that the target needs to be a gene product. 

Annotations are here: https://docs.google.com/spreadsheets/d/1jw635dKG2g7D71SftEOAR1HyKi7-gYZaA8dPBIMj_p4/edit#gid=0


ASSIGNED   BY
--
dictyBase | 19
FlyBase | 3
UniProt | 18

**Comment by pfey03** [comment]
@pgaudet for MF as well? P2Go has fixed all but not for MF when it's regulator protein? Not sure if I should change that?

**Comment by pgaudet** [comment]
Yes, we used 'has input' for these as well.

**Comment by pfey03** [comment]
@pgaudet 
I'm done with changing all Dicty remaining extension annotations
