### ISSUE TITLE
Review MF annotations using extension 'has_participant' (MF only)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2588]
Hello, 

To simplify the relations used for annotation extensions, we propose to use 'has_input' instead of 'has_participant'. 

Annotations should be reviewed as this mapping is probably not exact.
https://docs.google.com/spreadsheets/d/1pUyADYGA9Qo1WG_5p364ZEi4s7Iu9JtLfarHkOqxXQA/edit#gid=0

Assigned   by |  
-- | --
MGI | 290
UniProt | 10
AgBase | 8

Thanks, Pascale

**Comment by ukemi** [comment]
MGI done. Not all were has_input, but I made notes.

**Comment by pgaudet** [comment]
Hi @pgarmiri Can you look at those for UniProt ?

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
The UniProt ones have been checked.
Thanks,
Penelope

**Comment by vanaukenk** [comment]
I've updated the AgBase annotations in Protein2GO, so the reviews here are now all done.
