### ISSUE TITLE
Review annotations to GO:1900392 regulation of transport by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2589]
Hello, 

To finish work in this ontology ticket: https://github.com/geneontology/go-ontology/issues/12739

Please review/move this annotation: 

https://docs.google.com/spreadsheets/d/1uUO_Dm8zF15wRfO094oTMTNK1920a1frd3vL_Ha5bjk/edit#gid=0

Thanks, Pascale

**Comment by ValWood** [comment]
deleted
