### ISSUE TITLE
Review annotations to GO:0097235 positive regulation of fatty acid beta-oxidation by positive regulation of transcription from RNA polymerase II promoter	

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2590]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move those annotations:
https://docs.google.com/spreadsheets/d/1ZxNBmiqPII9JYpDvbEtskXYeNoveMZmPUcGMkVyCdEs/edit#gid=0

~1 WormBase~
1 SGD

Thanks, Pascale

**Comment by vanaukenk** [comment]
I've updated the C. elegans annotations, but noting that I can't revise the annotation extensions in Protein2GO as expected, so will have to explore why further with Alex.

**Comment by srengel** [comment]
changed the SGD one from 97235 to 45944 col16 part_of 32000.  please let me know if that's not correct.

**Comment by pgaudet** [comment]
@srengel Looks good, thanks.
