### ISSUE TITLE
Review annotations to GO:0036083 positive regulation of unsaturated fatty acid biosynthetic process by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2591]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review annotations so we can obsolete this term: 
https://docs.google.com/spreadsheets/d/1Q7oDQ1fab966ttP9OT2TZgwpexgZZwedj1OxnL2dANc/edit#gid=0

2 SGD
1 PomBase

Thanks, Pascale

**Comment by ValWood** [comment]
done

**Comment by srengel** [comment]
done. changed the 2 SGD annotations to 45944 col16 part_of 2001280.

**Comment by pgaudet** [comment]
Thanks !
