### ISSUE TITLE
GO:2000531 regulation of fatty acid biosynthetic process by regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2592]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 2 annotations: (SGD)

https://docs.google.com/spreadsheets/d/18tUjVSamREmpo9mfC2mlb2BBD56Vvsl15Esw_ajx4GM/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
done.
