### ISSUE TITLE
Review annotations to GO:1904741 positive regulation of filamentous growth of a population of unicellular organisms in response to starvation by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2593]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review annotations so we can obsolete this term:
https://docs.google.com/spreadsheets/d/1wXWnAjdUnodqzyE0BUGfehbJToPwfzBrnliMZrcPm6I/edit#gid=0

4 SGD

Thanks, Pascale

**Comment by srengel** [comment]
done.
