### ISSUE TITLE
Review annotations to GO:0061424 positive regulation of peroxisome organization by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2594]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review annotations so we can obsolete this term:
https://docs.google.com/spreadsheets/d/1f9GYyhiqNIylfNP9pAMw74z-EvB3RYv6vCq_a76uXz8/edit#gid=0

1 SGD

Thanks, Pascale

**Comment by srengel** [comment]
done

**Comment by srengel** [comment]
done
