### ISSUE TITLE
Review annotations to GO:1900478 positive regulation of sulfate assimilation by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2595]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review annotations so we can obsolete this term:
https://docs.google.com/spreadsheets/d/1uu1GRHVBNYejQaDJchqeNcUWt0A_tlzqXpaVqNmUJKE/edit#gid=0

2 SGD

Thanks, Pascale

**Comment by srengel** [comment]
done
