### ISSUE TITLE
Review annotations to GO:0100057 regulation of phenotypic switching by transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2596]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review annotations so we can obsolete this term:
https://docs.google.com/spreadsheets/d/17yEjUJDUt4Ar_VCfXGFncFCkkZ0skmSr7BQKkGUdJIo/edit#gid=0

1 BHF

Thanks, Pascale

**Comment by RLovering** [comment]
done, sorry about that one, I think there was a pasting error
