### ISSUE TITLE
Review annotations to GO:1900545 regulation of phenotypic switching by regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2597]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review annotations so we can obsolete this term:
https://docs.google.com/spreadsheets/d/1z5wm7A9yx6SK2ZLEmc_0xS4pAqtG-CZZYBY685qL6iA/edit#gid=0

1 CGD

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @marekskrzypek 
Can you please have a look at this one ?

**Comment by pgaudet** [comment]
Note that I am obsoleting the term, since it's a single annotation.

**Comment by marekskrzypek** [comment]
Good! It's a bizarre term anyway! I changed it to regulation of phenotypic switching (GO:1900239)

**Comment by pgaudet** [comment]
Thanks !
