### ISSUE TITLE
Matrix cohesin complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2599]
Hi @vanaukenk 

This oone has appeared int eh cohesin /DNA replication intersect.

tim-1 |   | colocalizes_with | mitotic cohesin complex |   | WB | Caenorhabditis elegans | IPI | WB:WBGene00001860 |   | gene |   | PMID:12827206WB_REF:WBPaper00005919 | 20080331

All the annotation looks OK, but I think we decided not to do "colocalizes_with"  complex.
This  causes a violation since this isn't really cohesin (but binds to cohesin)

cheers

val

**Comment by vanaukenk** [comment]
@ValWood 
This has already been deleted and will be in our next WB production file that should be out at the end of this month (August).
