### ISSUE TITLE
Matrix: Incorrect Ensembl annotation transfer

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2602]
slc25a16 solute carrier family 25 member 16 has annotations transferred to it from human DNA2 helicase. (Ensembl pipeline)
 
I don't know who to assign this to?

  | Slc25a16 | solute carrier family 25 member 16 |   | DNA replication checkpoint |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110

  | Slc25a16 | solute carrier family 25 member 16 |   | DNA double-strand break processing |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | mitochondrial DNA replication |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | base-excision repair |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | DNA replication, removal of RNA primer |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | mitochondrial DNA repair |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | positive regulation of DNA replication |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | DNA replication, Okazaki fragment processing |   | Ensembl | Rattus norvegicus | IEA | UniProtKB:P51530ensembl:ENSP00000351185 | family not named pthr24089 | gene |   | GO_REF:0000107RGD:1600115 | 20190110
  | Slc25a16 | solute carrier family 25 member 16 |   | nucleic acid phosphodiester bond hydrolysis |   | GOC | Rattus norvegicus | IEA | GO:0004518 | family not named pthr24089 | gene |   | GO_REF:0000108RGD:1600115 | 20190110

**Comment by vanaukenk** [comment]
In the current [group contacts file](https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv), Ensembl-related inquiries have Tony S as the point of contact.  I think we can safely assume Tony no longer wants to be contacted about this :-)

Let's assign someone from UniProt for now and see if we can get an updated contact for future inquiries.

**Comment by pgaudet** [comment]
I usually assign Alex when it was Tony.

**Comment by magrane** [comment]
Sorry for the late reply - have been on holiday. You can assign this one to Alex. I tried to do it myself but I can't find his name in the list of the assignees.

**Comment by pgaudet** [comment]
@magrane I fixed Alex's team's membership - we can now assign him annotation and ontology tickets.

**Comment by ValWood** [comment]
These annotations have disappeared, closing
