### ISSUE TITLE
Matrix: cohesin study, endoreduplication from review untraceable

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2603]
This is a review, no EXP annotatiosn here:
https://www.ncbi.nlm.nih.gov/pubmed/15917200

used to make the following annotation?

SMC1A | Structural maintenance of chromosomes protein 1A |   | negative regulation of DNA endoreduplication |   | BHF-UCL | Homo sapiens | IMP |   | structural maintenance of chromosomes smc family member pthr18937 | protein |   | PMID:15917200 | 20100127

(I  tried to trace the origin don't see any reference to endoreplication in the review?)

**Comment by ValWood** [comment]
Also


STAG2 | Cohesin subunit SA-2 |   | negative regulation of DNA endoreduplication |   | BHF-UCL | Homo sapiens | IMP |   | stromal antigen pthr11199 | protein |   | PMID:15917200 | 20100127

**Comment by ValWood** [comment]
and

SMC3 | Structural maintenance of chromosomes protein 3 |   | negative regulation of DNA endoreduplication |   | BHF-UCL | Homo sapiens | IMP |   | family not named pthr43977 | protein |   | PMID:15917200 | 20100127
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
I tried to raise a dispute in Portein2GO but  I can't see these so maybe they were fixed by some other dispute. Odd that they are still in AmiGO though....

**Comment by RLovering** [comment]
There were several odd annotations to this paper so when you disputed one, I deleted them all, on 18 July 2019

**Comment by ValWood** [comment]
OK, that makes sense but usually there is a GO db update every month ? @pgaudet

**Comment by pgaudet** [comment]
Right - unfortunately we've had some issues with the release, the current data is from July 2nd (you can see the date of the release in AmiGO, in the bottom right corner of the page). 


Pascale

**Comment by ValWood** [comment]
OK, thanks
