### ISSUE TITLE
Matrix: cohesin study, wapl is a cohesin loader not cohesin complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2604]
Wapl is cohesin loader, not a cohesin subunit

	WAPL	Wings apart-like protein homolog		cohesin complex		UniProt	Homo sapiens	IDA		family not named pthr22100	protein		PMID:17113138	20100921
	WAPL	Wings apart-like protein homolog		cohesin complex		UniProt	Homo sapiens	IDA		family not named pthr22100	protein		PMID:19696148	20110106

**Comment by pgaudet** [comment]
Any way you can give more informative titles to the tickets ? That would be much appreciated :)

**Comment by ValWood** [comment]
raised dispute in p2GO

**Comment by ValWood** [comment]
@lbreuza  fixed
