### ISSUE TITLE
Review annotation using extension 'regulates_o_results_in_maturation_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2605]
Hello, 

We would like to stop relying on GO_REL, and start by removing relations that are not much used. There is a single (quite complicated) annotation using 'regulates_o_results_in_maturation_of' by MGI: 

https://docs.google.com/spreadsheets/d/1m91m6Hs_y3uZYBSUbSA_jfWGKHxRZ9KrjEvKI7CRy_A/edit#gid=0

@ukemi Can this data be captured differently ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
We'll remove all chained relations.

**Comment by vanaukenk** [comment]
Reviewed existing relation use.  Consistent with ShEx shape; will be modeled in GO-CAM upon import.

MGI:MGI:88138

**Comment by pgaudet** [comment]
These have all been dealt with
