### ISSUE TITLE
Matrix: cohesin study/ translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2606]
rad21a | RAD21 cohesin complex component a |   | translation |   | ZFIN | Danio rerio | IMP | ZFIN:ZDB-MRPHLNO-070904-2 | scc1 / rad21 family member pthr12585 | protein |   | PMID:25378554ZFIN:ZDB-PUB-141108-5 | 20160217

Translation impairment appears to be  quite indirect and seems to be only one of the many pleiotropic phenotypes when cohesion is disrupted?  (translation is affected because ribosome synthesis is affected because rNDA synthesis is affected when cohesin is disrupted.

At the very end the authors point out that a direct rile in translation is "speculative"

We speculate that an evolutionarily conserved function of the cohesin complex is to tie the chromosome structure to the translational output of cells. The mechanisms by which this is accomplished are likely related to the binding of cohesin at the rDNA and nucleolar function, but additional roles are possible and merit further investigation.

**Comment by sabrinatoro** [comment]
Thank you Val. 
I agree, this annotation should be a phenotype, and not GO annotation. I have removed it. 
Thanks
