### ISSUE TITLE
Review annotation using extension 'during'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2607]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications. 

Please review annotations to 'during': 

https://docs.google.com/spreadsheets/d/1ZpGb4DD-hKq6PVrzxmlZCojCNe4fQGc370jt41POZO0/edit#gid=0

11 BHF
16 MGI

Thanks, Pascale

**Comment by ukemi** [comment]
In several places, exists_during is suggested as a replacement, but I don't see that relation in RO. I only see it in GO_REL as a child of during. Reviewing the MGI annotations shows that when a curator used this relation in an annotation they wanted to express that a gene product was located in a CC under certain conditions. For example gene X is in the plasma membrane when cells are normoxic, but in the cytosol when cells are hypoxic. So they chose the relation during coupled to  'response to increased/decreased oxygen levels' as the extension. Even if we keep exists_during I don't think it quite captures the intent.

**Comment by ukemi** [comment]
There are also several suggestions to change relations to happens_during when the object is a biological process. I thought based on the discussion from the annotation call this week, we were going to reserve that relation for phases or life stages.

**Comment by pgaudet** [comment]
I thought I only suggested happens_during when the extension was a phase. 
Are we talking about the same thing ?

**Comment by ukemi** [comment]
OK. I was looking at the wrong line.

**Comment by pgaudet** [comment]
yer, sorry, my mistake ! 
This is a little confusing ;)

**Comment by RLovering** [comment]
These are Toronto annotations not UCL annotations and I do not have permission to edit these

**Comment by RLovering** [comment]
Toronto annotations - revisions complete

**Comment by pgaudet** [comment]
Brilliant !

**Comment by pgaudet** [comment]
@ukemi Can you review the remaining annotations and close the ticket ?
