### ISSUE TITLE
Matrix: ELP1 elongator not transcription

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2609]
raised disputes for

HGNC | O95163 | ELP1 |   | GO:0006357 | regulation of transcription by RNA polymerase II | ECO:0000304(TAS) | ECO:0000304 | (TAS) |   | PMID:11714725 |   |   |   | 

ECO:0000304 | (TAS)
  |   | BHFL | O95163 | ELP1 |   | GO:0006368 | transcription elongation from RNA polymerase II promoter | ECO:0000304(TAS) | ECO:0000304 | (TAS) |   | PMID:11714725
ECO:0000304 | (TAS)

BHFL | O95163 | ELP1 | contributes_to | GO:0000993 | RNA polymerase II complex binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:11714725

**Comment by ValWood** [comment]
SWIE | O95163 | ELP1 |   | GO:0008023 | transcription elongation factor complex | ECO:0000314(IDA) | ECO:0000314 | (IDA) | 5 | PMID:11714725

**Comment by ValWood** [comment]
See https://github.com/geneontology/go-annotation/issues/1965
for background information, lots of papers overturning role in transcription

**Comment by ValWood** [comment]
@pgaudet 

could you delete these TAS?
I can't raise disputes on these or delete them:



PINC
O95163
ELP1
GO:0006468
protein phosphorylation
ECO:0000304
(TAS)
PMID:9751059



PINC
O95163
ELP1
GO:0006955
immune response
ECO:0000304
(TAS)
PMID:9751059


SWIE	O95163	
ELP1
GO:0008607	
phosphorylase kinase regulator activity
ECO:0000314	(IDA)
5	PMID:11818576	
			
PINC	O95163	
ELP1
GO:0008607	
phosphorylase kinase regulator activity
ECO:0000304	(TAS)
PMID:9751059

**Comment by ValWood** [comment]
and
@pgaudet 
ELP1 | Elongator complex protein 1 |   | protein-containing complex assembly |   | PINC | Homo sapiens | TAS |   | ikappab kinase complex-associated protein pthr12747 | protein |   | PMID:975105

needs to be removed

**Comment by pgaudet** [comment]
PINC annotation removed.

**Comment by RLovering** [comment]
BHF and HGNC annotations removed
