### ISSUE TITLE
Matrix: elp2 / transcription zfin/FB/RGD

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2610]
Hi @sabrinatoro  I don't think the thing ISS'd to here is the ortholog of elp2?

elp2 | elongator acetyltransferase complex subunit 2 |   | transcription elongation from RNA polymerase II promoter |   | UniProt | Danio rerio | ISS | UniProtKB:Q16186 | family not named pthr44111 | protein |   | ZFIN:ZDB-PUB-110105-1 | 20070420

  | elp2 | elongator acetyltransferase complex subunit 2 |   | proteasome assembly |   | UniProt | Danio rerio | ISS | UniProtKB:Q16186 | family not named pthr44111 | protein |   | ZFIN:ZDB-PUB-110105-1 | 20070420

but anyway, elongator complex is no longer considered to be a histone acetyltransferase, it is involved in tRNA wobble modification.

See  https://github.com/geneontology/go-annotation/issues/1965
for lots of background papers

**Comment by ValWood** [comment]
Oddly RGD has the same 2 ISS inferences


Elp2 | elongator acetyltransferase complex subunit 2 |   | transcription elongation from RNA polymerase II promoter |   | UniProt | Rattus norvegicus | ISS | UniProtKB:Q16186 | family not named pthr44111 | gene |   | GO_REF:0000024RGD:1600115 | 20180127

  | Elp2 | elongator acetyltransferase complex subunit 2 |   | proteasome assembly |   | UniProt | Rattus norvegicus | ISS | UniProtKB:Q16186 | family not named pthr44111 | gene |   | GO_REF:0000024RGD:1600115 | 20180127


which seems really odd?

**Comment by ValWood** [comment]
elp2 is this WD family protein:
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR44111


UniProtKB:Q16186 is not a WD repeat
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR12225

**Comment by gthayman** [comment]
These are imported from GOA.

**Comment by ValWood** [comment]
Ah OK.

@pgaudet  do we know who creates these. ISS are manual - so not a pipeline... and the dates range from 2007 to 2018?

**Comment by ValWood** [comment]
OK, I could query these in Protein2GO. Disputes raised.

**Comment by gthayman** [comment]
Hi Val,
We get them from here, if this helps:

ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/RAT

**Comment by ValWood** [comment]
I think these are all fixed again. `At least  https://www.uniprot.org/uniprotkb/Q05AM5/entry
is OK and  the UniProt enrty hads a useful cautionary note:
I presume this is applied to all others and so reannotation will hopefully be prevented.


Caution
The elongator complex was originally thought to play a role in transcription elongation. However, it is no longer thought to play a direct role in this process and its primary function is thought to be in tRNA modification.
