### ISSUE TITLE
Review annotations using extension 'regulates_activity_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2613]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet the GO-CAM specifications.

Annotations are here: https://docs.google.com/spreadsheets/d/1iSh0fxwSGWnglUgOfWuYaCiMOprLDQTypO8s2CXYETc/edit#gid=0

Some these could be replaced by 'has input'. 

Impact on each group: 

Assigned   by |  
-- | --
AgBase | 2
ARUK-UCL | 30
BHF-UCL | 13
CAFA | 3
dictyBase | 1
ParkinsonsUK-UCL | 2
PomBase | 20
SGD | 8
SynGO | 1
SynGO-UCL | 4
UniProt | 23
WB | 9

Thanks, Pascale

**Comment by pfey03** [comment]
changed to has_input, done

**Comment by milarolo** [comment]
SWIE all done

**Comment by mah11** [comment]
PomBase done

**Comment by pgaudet** [comment]
@RLovering @vanaukenk @ValWood you still have a few annotations to review (according to the spreadsheet); can you please have a look ? 

https://docs.google.com/spreadsheets/d/1iSh0fxwSGWnglUgOfWuYaCiMOprLDQTypO8s2CXYETc/edit#gid=0

Thanks, Pascale

**Comment by mah11** [comment]
For PomBase please see my [comment](https://github.com/geneontology/go-annotation/issues/2613#issuecomment-578144389) above, and the comments in column W of the spreadsheet.

**Comment by pgaudet** [comment]
Thanks @mah11 I hadn't seen this. I marked as 'changed'

**Comment by vanaukenk** [comment]
Sorry @pgaudet - these were all changed a few months ago, but I forgot to add it to the spreadsheet.  All done now.

**Comment by pgaudet** [comment]
Great, thanks everyone !

**Comment by pgaudet** [comment]
@RLovering when you have a minute - please replace the relation 'regulates_activity_of' by 'has input'. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Alex
would you be able to change the UCL relations in Protein2GO for us from regulates_activity_of' to 'has input'. There are almost 50 UCL annotations.
If this is not possible please let me know and I will do these manually
Thanks
Ruth
@alexsign

**Comment by alexsign** [comment]
@RLovering 
Hi Ruth,
Yes, it's on my todo list. I'll update the ticket when it's done. Sorry for delay.

**Comment by RLovering** [comment]
great sorry, was trying to organise my to do list. I will not bother you again about this. Thanks for your help and hope you are well

**Comment by alexsign** [comment]
@RLovering @pgaudet 
Hi Ruth,
The annotation extensions are updated in Protein2GO, and should be updated in the QuickGO next week.

**Comment by RLovering** [comment]
brilliant many thanks
Ruth

**Comment by RLovering** [comment]
Hi Pascale 
I have closed this ticket, as UCL ones have all been done by Alex
Ruth
