### ISSUE TITLE
Review annotations using extension 'results_in_maturation_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2614]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

https://docs.google.com/spreadsheets/d/1yEhsiLyPqTSXZi_2DjL3Qs9i045qmkiUaeNFXNtvttg/edit#gid=0

MF annotations using this relation should be removed/replaced: 
3 UniProt @milarolo 
1 GOC @pgaudet (removed)

**no decision on BP yet -** 

BP annotations |
--|--
AgBase | 1
ARUK-UCL | 2
MGI | 72
UniProt | 19
ZFIN | 16

Thanks, Pascale

**Comment by milarolo** [comment]
I've removed the extension (results in maturation of)  from the  3 SWIE  MF ones
I haven't done anything with the BP ones

**Comment by pgaudet** [comment]
OK thanks Mila !

**Comment by vanaukenk** [comment]
'results in maturation of' is in RO:  RO:0002299

Relevant ShEx shape:

\<DevelopmentalMaturation> @\<BiologicalProcess> AND EXTRA a {
  a @\<DevelopmentalMaturationClass> {1};
  results_in_maturation_of: @\<AnatomicalEntity> {0,1};
} // rdfs:comment "a developmental maturation GO biological process or child"

**Comment by pgaudet** [comment]
This one is OK
