### ISSUE TITLE
Review annotation using extension 'regulates_o_has_participant'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2615]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.
Please review annotations to 'regulates_o_has_participant'
https://docs.google.com/spreadsheets/d/1mdP8gS9ulrxcjcdRb4niNTSH2RDxFTZ-wIickKO0FPg/edit#gid=0

All annotations are by MGI (>500 annotations). 

Thanks, Pascale

**Comment by ukemi** [comment]
I believe this is out of date. We decided that these would be modified on import.
