### ISSUE TITLE
Review annotation using extension 'regulates level of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2617]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation 'regulates level of' in extensions: 
https://docs.google.com/spreadsheets/d/1PxfotVlHqCLYIWtA6lrwT3mv9vCAwT_yf02fcyU0wzI/edit#gid=0

5 MGI annotations impacted. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Do we want this ? @thomaspd 
I thought we were implying that 'activity regulating processes' such as transcription were regulating the next activity. 

Or do we want to keep this for extensions and have a special way of translating it to GO-CAM ?

**Comment by pgaudet** [comment]
In any case - if it's useful for the ontology we can leave it in RO; i'll just take it out from RO (and we should not allow annotations using it). OK ?

**Comment by ukemi** [comment]
MGI annotations changed or removed.
