### ISSUE TITLE
 Review annotations using extension 'stabilizes' in extensions

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2619]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation 'stabilizes' in extensions:
https://docs.google.com/spreadsheets/d/13olYxgZwbnoP1fhOeQiCzZr5cB3-Rtz9Kd1XIbIR0oM/edit#gid=0

Suggestion is to change to 'has_input'. 

Here are the annotations, by group: 

Assigned   by |  
-- | --
AgBase | 2
BHF-UCL | 10
ParkinsonsUK-UCL | 19
UniProt | 21

Thanks, Pascale

**Comment by milarolo** [comment]
all SWIE annotations reviewed and changed

**Comment by RLovering** [comment]
Alex updated these for us - Thank you Alex

**Comment by pgaudet** [comment]
All done, thanks everyone.
