### ISSUE TITLE
Review annotations using extension 'regulates_o_results_in_division_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2620]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation 'regulates_o_results_in_division_of' in extensions: 
https://docs.google.com/spreadsheets/d/1M7LdskuSzh4yh7vHsSGe4v4oPulag2nEfZ3FXYJNrJ8/edit#gid=0

4 MGI
2 BHF

Thanks, Pascale

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by RLovering** [comment]
great, I'll remove my name then

**Comment by RLovering** [comment]
I have removed all the annotations listed in the spreadsheet and there are now no obvious annotations from any group with this extension
