### ISSUE TITLE
Review annotations using extension  regulates_o_results_in_specification_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2621]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation regulates_o_results_in_specification_of' in extensions:
https://docs.google.com/spreadsheets/d/1M7LdskuSzh4yh7vHsSGe4v4oPulag2nEfZ3FXYJNrJ8/edit#gid=0

5 MGI
2 BHF
6 UniProt

Thanks, Pascale

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by RLovering** [comment]
this is the wrong spreadsheet for this relation. I have removed the 4 AEs with the extension regulates_o_results_in_specification_of

it looks like there are still 18 to be removed https://www.ebi.ac.uk/QuickGO/annotations?extension=regulates_o_results_in_specification_of

UniProt | 40.91 | 9
-- | -- | --
RGD | 22.73 | 5
BHF-UCL | 18.18 | 4 (removed)
MGI | 18.18 | 4

**Comment by pgaudet** [comment]
All removed.
