### ISSUE TITLE
Review annotations using extension 'regulates_o_has_input'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2622]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation ''regulates_o_has_input' in extensions:
https://docs.google.com/spreadsheetshttps://docs.google.com/spreadsheets/d/1YjOSi-DOMhf2yX79DLvtQEr_-Vq4QvgD42IfDiu6NmI/edit#gid=0

121 MGI
Thanks, Pascale

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by pgaudet** [comment]
Add done
