### ISSUE TITLE
Review annotations using extension 'regulates_o_results_in_mophogenesis_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2623]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation regulates_o_results_in_specification_of' in extensions:
https://docs.google.com/spreadsheets/d/1ePOKT1OSuriD4Zd1u0JqKA2Ajywp0WEfR3pwEUCe8nE/edit#gid=0

9 MGI

Thanks, Pascale

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by pgaudet** [comment]
All done
