### ISSUE TITLE
Review annotations using extension 'regulates_o_results_in_commitment_to'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2624]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation regulates_o_results_in_specification_of' in extensions:
https://docs.google.com/spreadsheets/d/1VXhvMD9rRvgGvEZjABgGhqfn4ybDCHnObkuk8GyFKz8/edit#gid=0

10 MGI

Thanks, Pascale

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by pgaudet** [comment]
All annotations removed
