### ISSUE TITLE
Review annotations using extension 'regulates_expression_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2625]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation ' 'regulates_expression_of' in extensions:
https://docs.google.com/spreadsheets/d/1-LGI7kD8h4g2jirdEOnKeXiQkIqCyNLZiTztuyDKPNg/edit#gid=0

It may be possible to use 'has input'? 

Impacted groups: 

Assigned   by |  
-- | --
AgBase | 4
ARUK-UCL | 425
BHF-UCL | 1143
dictyBase | 2
ParkinsonsUK-UCL | 27
SGD | 28
WB | 13

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Hi @pgaudet, we have >1500 of these, so when Alex is available (I think some time next week), I will ask whether he could change them all computationally. I'll keep you updated.
cc @RLovering

**Comment by pfey03** [comment]
dictyBase done

**Comment by vanaukenk** [comment]
WB done

**Comment by BarbaraCzub** [comment]
Hi @pgaudet 
@alexsign agreed to do this computationally for the annotations in P2GO (email conversation with subject 'Extension relations' on 12-13 September), so I'll remove my assignment.
Thanks,
Barbara

**Comment by RLovering** [comment]
Thanks Barbara for discussing with Alex. I agree there are too many annotations for us to change these manually and we are happy for the AE relation to be changed to has_input
Ruth

**Comment by RLovering** [comment]
Hi Alex
please change all the UCL annotation relations 'regulates_expression_of' to 'has_input'
Thanks
Ruth

**Comment by pgaudet** [comment]
See newer ticket: https://github.com/geneontology/go-ontology/issues/27038
