### ISSUE TITLE
Review annotations to ENSG00000069482

### ISSUE THREAD

**Issue by hedi-ee** [geneontology/go-annotation#2627]
Hello!

One of g:Profiler users noticed that a human gene has relations to plant specific biological processes (e.g. root hair cell development, GO:0080147). See https://biit.cs.ut.ee/gplink/l/cf4ZyEA_Tq (choose detailed results tab). Looking into our archives it seems that the issue goes back to 2015 and might originate from inferring annotations from this paper http://amigo.geneontology.org/amigo/reference/PMID:22329353

**Comment by pgaudet** [comment]
Annotation has been removed. 

Thanks for reporting the problem ! 

Pascale

**Comment by milarolo** [comment]
P22466  GO:1902891 	ECO:0000314 (IDA) 	PMID:22329353  has been removed

Mila
