### ISSUE TITLE
Reference given is in russian

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#2628]
We have an annotation from our GOA mouse import that uses a reference in Russian. Was this paper actually read or is the annotation taken from the abstract?

UniProtKB	Q6PDM1	Msl1		GO:0005634	PMID:16119455	IDA		C	Male-specific lethal 1 homolog	Msl1|Msl1l1	protein	taxon:10090	20190715	UniProt.

**Comment by pgaudet** [comment]
Disputed in P2GO with a reference to this ticket. 

Pascale

**Comment by pgaudet** [comment]
I asked to change the evidence code. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
We don't annotate to abstracts; this has always been the policy. We should remove the annotation

**Comment by pgaudet** [comment]
OK - I wrote to the curator again.
