### ISSUE TITLE
Review extension 'regulates_o_transports_or_maintains_localization_of'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2631]
Hello,

We would like to stop relying on GO_REL, and start by removing relations that don't meet GO-CAM specifications.

Please review annotations using the relation 'regulates_o_transports_or_maintains_localization_of' in extensions:
https://docs.google.com/spreadsheets/d/1UBXKfpg-3Hj64sMulDKPAyjDnct3QF5DkiHakC6A0Wg/edit#gid=0

29 MGI

Thanks, Pascale

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by ukemi** [comment]
I believe this is out of date. We have a method for importing chain relations into GO-CAM models. These annotations can stay for now.

**Comment by pgaudet** [comment]
All done
