### ISSUE TITLE
Review annotations to 'x part' terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2632]
Dear all, 

The proposal has been made to obsolete 'x part' terms (such as 'nuclear part). 
Although most terms have the 'do_not_annotate' flag, there are some annotations to some of the terms.

Please review your annotations; the suggestion is to move annotations up to the component (rather than 'component part). 

https://docs.google.com/spreadsheets/d/10udUjxkZqWGHF2BjNZUjQHSd_lRh1ujfk4Y3TTkpJlY/edit#gid=0

Contributor   (Assigned by)
--
AspGD | 1 @marekskrzypek
CGD | 2 @marekskrzypek
GeneDB | 1
GR | 2 
JCVI | 1
MGI | 13
SGN | 7 @lukasmueller

Note that we will add 'replace_by' the parent term for each of those, except for 'neuron part' (since its parent would not be a GO term), so it is possible that your annotation tool will map these automatically. 

Thanks, Pascale

**Comment by pgaudet** [comment]
For more information, the obsoletion ticket is here: 
https://github.com/geneontology/go-ontology/issues/17778

**Comment by ukemi** [comment]
MGI done. Some could be replaced by bonafide cellular components, one was changed to the parent and some were removed because they were to neuron part, but the papers only indicated that the genes were expressed in a neuron with no real CC information.

**Comment by pgaudet** [comment]
Term has been obsoleted. Remaining annotations will be flagged by QC checks.
