### ISSUE TITLE
Review annotations to GO:1900460 negative regulation of invasive growth in response to glucose limitation by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2633]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 7 annotations: (SGD)
https://docs.google.com/spreadsheets/d/1OTPssy3Ys2PlE8cXOwEh4NVBIW5f4FhTxnHI0O4h_1k/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed. done.
