### ISSUE TITLE
Review annotations to GO:0036095 positive regulation of invasive growth in response to glucose limitation by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2634]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 11 annotations: (SGD)
https://docs.google.com/spreadsheets/d/1i9VOl0XgxKm3vswYjxqE5QP0AVFfJfNVSFCYZFrCAik/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed. done.
