### ISSUE TITLE
Review annotations to GO:1900474 negative regulation of mating type switching by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2635]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 2 annotations: (SGD)
https://docs.google.com/spreadsheets/d/1liF46_3fnep5EX6ZL2anO3jF0vu1S6mweHbIWmK-RVM/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed. done.
