### ISSUE TITLE
GO:1900423 positive regulation of mating type switching by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2636]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 2 annotations: (SGD)
https://docs.google.com/spreadsheets/d/1j2TFUY9Bjl7IGXOe-zIyF50pm3_OGYWSR4i5jf3YosE/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed. done.
