### ISSUE TITLE
Review annotations to GO:0035959 positive regulation of glyoxylate cycle by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2637]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 2 annotations: (SGD)
https://docs.google.com/spreadsheets/d/18QIZfAYmDfk2-Bh3QoOJF0dEeH7JGQIrEnwlPnKcops/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed. done.
