### ISSUE TITLE
Review annotations to GO:1900471 negative regulation of inositol biosynthetic process by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2638]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 2 annotations: (SGD)

https://docs.google.com/spreadsheets/d/1bwVAhRqKHG2wgZ4x4QSfzd7kJ9tWv4QsxTiqIpj6ApY/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed. done.
