### ISSUE TITLE
Review annotations to GO:1900375 positive regulation of inositol biosynthetic process by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2639]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 2 annotations: (SGD)

https://docs.google.com/spreadsheets/d/1XOwF705XTaB5N96YeaVGGQH2yIsgvZ7N9NghPpO5ZyE/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed. done.
