### ISSUE TITLE
Review annotations to GO:0035957 positive regulation of starch catabolic process by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2642]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these 5 annotations: (SGD)

https://docs.google.com/spreadsheets/d/13UV7HA9xYO-ZqDq4ZtGd3zszzBLq3GbgoEtxg1eqF7s/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
Hi @pgaudet the spreadsheet link seems to be to the wrong one.  do you have a link to the correct spreadsheet?

**Comment by pgaudet** [comment]
Looks OK to me - can you check again ? 

https://docs.google.com/spreadsheets/d/13UV7HA9xYO-ZqDq4ZtGd3zszzBLq3GbgoEtxg1eqF7s/edit#gid=0

**Comment by srengel** [comment]
oh yes it is ok, i must have been looking at the wrong window before.  i had too many open at the same time :(

ok i'll take a look at these.

**Comment by srengel** [comment]
ok all done.
