### ISSUE TITLE
Review annotations to GO:0072362 regulation of glycolytic process by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2643]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move this annotation (BHF)

https://docs.google.com/spreadsheets/d/1w0IuMs3E-E1971p9YadQ9JEWwKvpfs1MhvlvFX9vcuY/edit#gid=0

Thanks, Pascale

**Comment by RLovering** [comment]
UCL done
