### ISSUE TITLE
Review annotations to GO:0072363 regulation of glycolytic process by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2644]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move those annotations: 
https://docs.google.com/spreadsheets/d/1zfbk8e0GhtcjyvfDkdmGfln1KzTRk2eD5AmJ-O1HHxY/edit#gid=0

1 BHF-UCL
1 MGI
7 SGD

Thanks, Pascale

**Comment by srengel** [comment]
SGD fixed.  done.

**Comment by RLovering** [comment]
UCL done

**Comment by ukemi** [comment]
I don't see this annoation.

**Comment by pgaudet** [comment]
The term is already obsolete.
