### ISSUE TITLE
Review annotations to GO:0061434 regulation of replicative cell aging by regulation of transcription from RNA polymerase II promoter in response to caloric restriction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2645]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move those annotations (2 SGD)

https://docs.google.com/spreadsheets/d/1BTsz4qX3LPeXxKOhwSBcGQPQsGDRed_apdZ50CwGCGc/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed.  done.
