### ISSUE TITLE
Review annotations to GO:0061432 regulation of transcription from RNA polymerase II promoter in response to methionine

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2646]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move those annotations (1 SGD)
https://docs.google.com/spreadsheets/d/14qxl57i8R_riSqdQtqKzPuJtMuwrwQALUdx2_mpxZUw/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed.  done.
