### ISSUE TITLE
Review annotations to  GO:1900622 positive regulation of transcription from RNA polymerase II promoter by calcium-mediated signaling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2647]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move those annotations (3 SGD)

https://docs.google.com/spreadsheets/d/1WgzWfT2qC7syM7pnBOObp-N-oKzdetROYXsBGEF8GnA/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
fixed.  done.
