### ISSUE TITLE
Review annotations to  GO:0061396 regulation of transcription from RNA polymerase II promoter in response to copper ion

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2648]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move those annotations (2 MGI)

https://docs.google.com/spreadsheets/d/1q2cIDml8RgPeXbZHyBZNMTSeBQ98vD441ZLu6hBC3DQ/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
Did you fix the 2 MGI annotations ?

**Comment by ukemi** [comment]
Yes. It should be indicated on the spreadsheet.
