### ISSUE TITLE
Conotoxin I-superfamily (IPR012624)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2649]
Could you take a look at this:

Conotoxin I-superfamily (IPR012624) has:
GO:0009405 pathogenesis 
GO:0005576 extracellular region 

It's hitting: D.mel CG43061 (http://flybase.org/reports/FBgn0262363)

Looking at the pfam
http://pfam.xfam.org/family/PF08088
this only seems to hit D.mel (perhaps they don't rate cone snails?)
(27 hits for InterPro family - 2 D.mel)

**Comment by hattrill** [comment]
Tagging @happy-lorna

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by typhainepl** [comment]
The GO terms have been removed from the InterPro entry, the changes will be visible at the next InterPro release.
