### ISSUE TITLE
smc3 and IPI/has_input

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2653]
Hi @doughowe 

You might want to review the 'DNA-binding transcription factor activity, RNA polymerase II-specific' annotation for smc3 - it has ZFIN:ZDB-GENE-991105-4 (cx43) as both the IPI with and has_input DBxref

From the paper, seems that smc3 binds promoter region and regulates transcription of the cx43 gene

**Comment by ValWood** [comment]
Assigned @doughowe please close if no longer current
