### ISSUE TITLE
Dissociate "DNA-directed DNA polymerase activity" from IPR007185 

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2654]
DNA polymerase alpha/delta/epsilon, subunit B (IPR007185) refers to the non-catalytic, accessory/regulatory subunit of these DNApols.

However, there's currently an InterPro2GO for IPR007185 to "DNA-directed DNA polymerase activity" (GO:0003887).  I think this should be removed.

**Comment by sjm41** [comment]
@hattrill

**Comment by typhainepl** [comment]
Hi,
Thanks for highlighting this, I've removed the GO term from the InterPro entry.
