### ISSUE TITLE
Remove "DNA-directed DNA polymerase activity" from IPR019038

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2655]
DNA polymerase delta subunit 3 (IPR019038) refers to the non-catalytic, accessory/regulatory subunit.

However, there's currently an InterPro2GO making an  "enables DNA-directed DNA polymerase activity (GO:0003887)" annotation. I think this should be removed.

**Comment by sjm41** [comment]
@hattrill

**Comment by typhainepl** [comment]
@sjm41 This GO term has been assigned by UniProt based on this publication [http://europepmc.org/abstract/MED/10219083]

**Comment by sjm41** [comment]
That NAS annotation is wrong.  I've just disputed it in Protein2GO with this comment:
"This paper is about the mouse polymerase delta complex, in which they show that a new protein (p66, mouse POLD3) is part of the delta complex. There are no data to show mouse POLD3 has polymerase activity itself (it's known to be an "accessory subunit" - POLD1 is the catalytic subunit), and I don't see human POLD3 (Q15054) used at all.  Sp I think this NAS annotation needs to be removed, especially as it's apparently the sole source for an InterPro2GO annotation for IPR019038."

**Comment by sjm41** [comment]
Response from UniProt:
Hi Steven, Thank you for your comments. I had a look at this and I agree with you that as it is not the catalytic subunit, it should not be annotated to the function. I have removed the annotation, so could you please resolve the dispute? They did sequence the human N- terminal of the protein (KIAA0039 cDNA (GeneBank accession number D26018) but there are better papers that characterised the complex. Kind regards, Penelope

So please dissociate that GO term from the InterPro entry.

(I'm curious - are there many InterPro2GO mappings based on single NAS GO annotations??)

**Comment by typhainepl** [comment]
I've removed the GO term from IPR019038.

**Comment by sjm41** [comment]
Great, thanks!
