### ISSUE TITLE
Remove MF GO terms from IPR007238 & IPR016558

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2656]
DNA primase large subunit, eukaryotic/archaeal (IPR007238) and DNA primase, large subunit, eukaryotic (IPR016558) refer to the the non-catalytic, accessory/regulatory subunit.

However, there's currently an InterPro2GO for IPR007238 making an "enables DNA primase activity (GO:0003896)" annotation, and for IPR016558 making an "enables Nucleotidyltransferase activity (GO:0016779)" annotation.
I think these should both be removed.

**Comment by hattrill** [comment]
Tagging @happy-lorna

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by typhainepl** [comment]
The GO terms have been removed from those entries, the changes will be visible at the next InterPro release.

**Comment by sjm41** [comment]
Great, thanks!
