### ISSUE TITLE
InterPro2GO associations to "DNA-directed 5'-3' RNA polymerase activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2657]
The following 7 InterPro entries all refer to RNA polymerase subunits that are not part of the 'catalytic core' (see Table 1 of PMID:22365827).
However, in each case, an InterPro2GO annotation of "enables DNA-directed 5'-3' RNA polymerase activity (GO:0003899)" is being made.
Minimally, I think the qualifier should be changed to "contributes to" (though I don't know if that's an option for InterPro2GO??).
But there's an argument to remove this GO term association from all these InterPro accessions, given they are outside the polymerase core?
(Aside: all PAINT-derived IBA annotations for RNAP activities appear to use the 'contributes' to qualifier.)

**RNA polymerase I associated factor, A49-like (IPR009668)**
"Saccharomyces cerevisiae A49 is a specific subunit associated with RNA polymerase I (Pol I) in eukaryotes. Pol I maintains transcription activities in A49 deletion mutants. However, such mutants are deficient in transcription activity at low temperatures."

**RNA polymerase Rpb7-like, N-terminal domain superfamily (IPR036898}**
"The eukaryotic RNA polymerase subunits RPB4 and RPB7 form a heterodimer that reversibly associates with the RNA polymerase II core."

**RNA polymerase Rpb7-like , N-terminal (IPR005576)**
"Rpb7 binds to Rpb4 to form a heterodimer. This complex is thought to interact with the nascent RNA strand during RNA polymerase II elongation"

**DNA-directed RNA polymerase III subunit RPC4 (IPR007811)**
"This entry represents a component of the RNA polymerase III (Pol III) complex"

**DNA-directed RNA polymerase III subunit Rpc5 (IPR006886)**
"Subunit c5 is a specific peripheric component of RNA polymerase III complex."

**DNA-directed RNA polymerase III, subunit Rpc31 (IPR024661)**
"Rpc31, Rpc34 and Rpc82 form a cluster of enzyme-specific subunits that contribute to transcription initiation in Saccharomyces cerevisiae and Homo sapiens"

**RNA polymerase III Rpc82, C -terminal (IPR008806)**
"This entry describes the C-terminal region of several DNA-directed RNA polymerase III polypeptides which are related to the Saccharomyces cerevisiae RPC82 protein"

**Comment by sjm41** [comment]
@hattrill @happy-lorna

**Comment by hattrill** [comment]
wrt 'contributes_to' - as the catalytic subunits can still function w/o these other subunits, would not be appropriate.
I would steer well-clear of adding 'contributes_to' to any InterPro associations - this qualifier is problematic.

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by typhainepl** [comment]
I've deleted the GO:0003899 from the InterPro entries except IPR005576 as it matches lots of proteins and has 4 publications associated with the GO term.

**Comment by sjm41** [comment]
Sorry for delay in responding to this! Thanks for removing that GO term from most of the InterPro entries I listed.
I'm not sure about IPR005576...I did find this relevant (albeit slightly dated) review though: PMID:15544954

**Comment by typhainepl** [comment]
@sjm41 thanks for mentioning the publication, I've now removed the GO term from IPR005576.
