### ISSUE TITLE
PTN002473373 - should not have "DNA-directed DNA polymerase activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2658]
http://www.pantree.org/node/annotationNode.jsp?id=PTN002473373

Currently propagates "DNA-directed DNA polymerase activity (GO:0003887)" to the non-catalytic/accessory subunits of DNApolG, such as D. melanogaster DNApol-gamma35 (Q9VJV8) and human POLG2 (Q9UHN1).

This is based on a single IDA annotation to the mouse ortholog Q9QZM2 from PMID:10666468 (which is wrong, and I've raised a dispute about).

@hattrill

**Comment by pgaudet** [comment]
Fixed, thanks for reporting.

**Comment by sjm41** [comment]
Thanks Pascale.
