### ISSUE TITLE
DB_Name has 2 entries (not 0 or 1, as defined): gramene_oryza, pamgo_mgrisea, tair

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/go-annotation#2659]
GAF Format is "illegal" for these files for the **DB_Name** field:
* gramene_oryza.gaf
* pamgo_mgrisea.gaf
* tair.gaf

**DB_Name** is defined as having 0 or 1 items, but it has two items.

The date generated is the same for all three files.
**!Date Generated by GOC: 2019-07-01**

I reference the lines using these fields. Please let me know if you need more information to identify the lines in the gaf files:    
* DB_ID
* GO_ID
* Evidence_Code

[log.txt](https://github.com/geneontology/go-annotation/files/3639245/log.txt)

**Comment by vanaukenk** [comment]
@dvklopfenstein - yes, could you include the exact lines in the GAFs that violate this specification?
Thank you!

**Comment by dvklopfenstein** [comment]
The filename and line numbers with **DB_Name** having more than 0 or 1 entry is in the attached log file.

### pamgo_mgrisea.gaf and tair.gaf
The entries producing the bad DB_Name look like this:

`Similar to sp|P15992 Saccharomyces cerevisiae`

which when split looks like this:

    [
        "Similar to sp",    
        "P15992 Saccharomyces cerevisiae"    
    ]

### gramene_oryza.gaf
In gramene_oryza.gaf, on line 24982, the DB_Name is:

`Putative phosphatidylinositol transfer-like protein II|`

The "|" in the DB_Name causes the split to produce:

    [
        "Putative phosphatidylinositol transfer-like protein II",    
        ""    
    ]

[i2659.log](https://github.com/geneontology/go-annotation/files/3644796/i2659.log)

**Comment by ValWood** [comment]
Dear @dvklopfenstein  apologies for the delayed response. Is this still an issue? Presumably  QC checks have resolved or reported.
If not I will  I will feed back tot he appropriate groups.

**Comment by pgaudet** [comment]
@balhoff Did we decide that pipes we not an allowed character? it makes parsing of the files very challenging.

**Comment by balhoff** [comment]
> @balhoff Did we decide that pipes we not an allowed character? it makes parsing of the files very challenging.

Yep, pipes are not allowed within any values in the new GPAD spec, only as separators defined by the format.

**Comment by pgaudet** [comment]
OK, so if these are still present in the files mentioned above, we should be getting errors. I'll make sure this is in the parsing rules.
