### ISSUE TITLE
PAINT: PANTHER PTN000185192 (should not get through, have NOT label)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2660]
Can the following PAINT annotations for fission yeast SPAC1B3.15c

  | Term ID | Term name | Evidence | Qualifiers | Reference | Count
-- | -- | -- | -- | -- | -- | --
- | GO:0015878 | biotin transport | IBA with PTN000185192 , vht1 |   | Gaudet P et al. (2011) | 2
- | GO:1905039 | carboxylic acid transmembrane transport | IBA with vht1 , PTN000185192 |   | Gaudet P et al. (2011) | 66
- | GO:0035461 | vitamin transmembrane transport | IBA with PTN000185192 , vht1 |   | Gaudet P et al. (2011) | 8

be removed. SPAC1B3.15 has been tested and appears to have no role in biotin transport
see:

- | GO:1905135 | NOT biotin import across plasma membrane | IGI with S000003297 | heterologous_system | Stolz J (2003) | 1

second biotin transporter in Sz. pombe, I investigated whether SPAC1B3.15p can complement a disruption in the S. cerevisiae vht1 gene. As shown in Figure 4C, expression of SPAC1B3.15c does not rescue the growth defect of the JSYΔvht1 on low concentrations of biotin. As this assay is extremely sensitive, I propose that SPAC1B3.15c has no function in biotin uptake. It is possible that SPAC1B3.15c is functionally related to the S. cerevisiae VHT1 homologue SEO1. seo1 mutants are resistant against the toxic methionine analogue ethionine sulphoxide (Isnard et al., 1996), implying that Seo1p mediates the plasma membrane transport of the drug. However, the natural substrate of Seo1p has yet to be identified.

Taken together these results demonstrate that SpVht1p mediates biotin and desthiobiotin uptake and that no other biotin transporter is encoded in the Sz. pombe genome.

**Comment by ValWood** [comment]
Also


SPAC1B3.15c | transmembrane transporter (predicted) |   | biotin transmembrane transporter activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000185192PomBase:SPAC1B3.15cPomBase:SPAC1B3.16c | family not named pthr43791 | protein |   | PMID:21873635 | 20170228

  | SPAC1B3.15c | transmembrane transporter (predicted) |   | dethiobiotin transmembrane transporter activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000185192PomBase:SPAC1B3.16c | family not named pthr43791 | protein |   | PMID:21873635 | 20181004

**Comment by pgaudet** [comment]
I don't understand - again we have both positive and negative annotations. This should not be the case - @dustine32 can you check what is going on ? 

Also, the same annotation is duplicated, with 2 different dates: 

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/4782928/65430589-2be2a100-dde6-11e9-8f39-8f36344def4d.png">

Any idea what is happening ? 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet I believe the conflicting qualifier is an example of the issue here https://github.com/pantherdb/fullgo_paint_update/issues/30. At first glance, we may need to add some additional structure to our DB schema to handle this. I'll do some testing with this and try to get it fixed soon. More detail will be added in that ticket.

For the duplicated annotations I'll add some code to the IBA creation script to collapse these together. Separate ticket coming soon!

**Comment by dustine32** [comment]
@pgaudet And https://github.com/pantherdb/fullgo_paint_update/issues/35 is the duplicated annotation ticket.

**Comment by pgaudet** [comment]
Great, thanks !

**Comment by dustine32** [comment]
@pgaudet I'm close to fixing the larger conflicting qualifier issue in our DB but, for this specific case, I think some curator intervention may be necessary. Can you see how this `GO:0015225` (biotin transmembrane transporter activity) to `PTN000185192` annotation looks in the PAINT tool (PTHR43791)? In the DB, I see three of these duplicate annotations and none of them have a NOT qualifier.

So in order for the positive `GO:0015225` to `SPAC1B3.15c` IBA(s) to go away, either these PAINT annotations will need to be obsoleted or an IKR/IRD NOT could be annotated on or above the `SPAC1B3.15c` leaf. Does this sound sane?

**Comment by pgaudet** [comment]
Hi @dustine32 

I see the same in PAINT: 

<img width="925" alt="image" src="https://user-images.githubusercontent.com/4782928/65688216-b6bada00-e038-11e9-9729-bdc9d39d3fd3.png">


I removed 2 of the 3 annotations. Let me know what it now looks like in the database. 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
I've reviewed this family. Was still a correction to do, but should be okay now.
