### ISSUE TITLE
Review annotations to GO:0044415   evasion or tolerance of host defenses

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2661]
GO:0044415   evasion or tolerance of host defenses
Definition (GO:0044415 GONUTS page)
Any process, either active or passive, by which an organism avoids or tolerates the effects of its host organism's defense(s). Host defenses may be induced by the presence of the organism or may be preformed (e.g. physical barriers). The host is defined as the larger of the organisms involved in a symbiotic interaction.

This term has been used for many, many annotations  of host species,  but it seems to be a term which can only be used to  annotate a pathogen or symbiont?

There are 146 annotations mainly by IEA from the Ensembl pipeline or ISS form AgBAse

There are only 3 EXP annotations

UniProtKB:O35345 | Kpna6 | acts_upstream_of_or_within | GO:0030683    evasion or tolerance by virus of host immune response | ECO:0000315 IMP | PMID:28189564 | MGI:MGI:3856636 | 10090 Mus musculus | MGI |  

UniProtKB:P01137 | TGFB1 | involved_in | GO:0019049    evasion or tolerance of host defenses by virus | ECO:0000314 IDA | PMID:15334054 |   | 9606 Homo sapiens | BHF-UCL |
  
UniProtKB:P84022 | SMAD3 | involved_in | GO:0019049    evasion or tolerance of host defenses by virus | ECO:0000314 IDA | PMID:15334054 |   | 9606 Homo sapiens | BHF-UCL

Which probably need to be addressed?

What taxon restrictions should I suggest?
Never in mammalia 
Never in plant?
would  probably cover?

**Comment by pgaudet** [comment]
Right - I have been trying to separate 'symbiont processes' and 'host processes' (and ideally put the taxon constraint at that level), but we need to address the annotation issues.

**Comment by ValWood** [comment]
I guess they will all get fixed once the taxon constraints are working... Do we know when this will be yet?

**Comment by pgaudet** [comment]
Annotations are here: 
https://docs.google.com/spreadsheets/d/10BujYHKP44LJFWQBRWP5iBjn2RTRtnmkox_c2t89lWI/edit#gid=0

2 BHF
1 MGI 
1 Reactome

Thanks, Pascale

**Comment by LiNiMGI** [comment]
MGI done, thanks!

**Comment by LiNiMGI** [comment]
Done, would you mind remove my name? Thanks!  Li

**Comment by RLovering** [comment]
UCL done
