### ISSUE TITLE
contributes_to DNA-directed DNA polymerase activity PTN000295225 (PTHR12708), PTN000045935 (PTHR10416)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2664]
There are two contributes_to DNA-directed DNA polymerase activity  PAINT annotations to DNA polymerase subunits which are not required for DNA synthesis and this has been experimentally shown in flies:

1. FBgn0035644 (DNApol-epsilon58): remove  
contributes_to DNA-directed DNA polymerase activity (GO:0003887) |  IBA with PANTHER:PTN000295225

This subunit is not catalytic and the catalytic subunit (DNApol-epsilon255) has the full activity in the absence of this other subunit. (PMID:15135399)

2. FBgn0027903 (Pol31): contributes_to DNA-directed DNA polymerase activity (GO:0003887) |  IBA with PANTHER:PTN000045935

Could you block this as this subunit is not catalytic and the catalytic subunit has been shown to be fully active in the absence of this subunit in both delta and zeta DNA polymerase complexes (PMID:8415662, PMID:15175013)

wrt #1650
@sjm41

**Comment by pgaudet** [comment]
This corresponds to PTHR14016
Primary annotations should also be reviewed: 
- Rat Pold2 RGD:1304954 @gthayman 
- Pombe cdc1 SPAC27E2.05  @ValWood 
- Yeast Pol31 S000003766 @srengel 

Thanks, Pascale

**Comment by ValWood** [comment]
@mah11

**Comment by pgaudet** [comment]
@gthayman There is one EXP annotation based on PMID:10541966, assigned by RGD. Can you please have a look ?

**Comment by mah11** [comment]
PomBase annotation deleted; will percolate to our next GAF on Monday.

**Comment by pgaudet** [comment]
Thanks @mah11

**Comment by gthayman** [comment]
RGD annotation deleted.

**Comment by pgaudet** [comment]
Thanks !

**Comment by srengel** [comment]
wait, just because a protein is 'not required' doesn't mean it doesn't 'contribute'.  are we now saying that complex members can't have a 'contributes_to' annotation?

it feels very wrong to not allow yeast Pol31p (a subunit of DNA polymerase delta) to be annotated to 'contributes_to polymerase activity' just because fly delta can be purified and exhibits polymerase activity on its own in vitro.

**Comment by hattrill** [comment]
This is in-keeping with the current guidelines. In this case, we know that there is one subunit responsible for the catalytic activity. For DNA polymerases, this pretty much seems to be true. For RNA polymerases, where there is no one subunit that can be entirely assigned this activity, then contributes_to is appropriate.

**Comment by vanaukenk** [comment]
Yes, the current guidelines state that when there is a known catalytic subunit for a protein-containing complex, then only the catalytic subunit is annotated to the catalytic activity.

The MFs of the other subunits can be annotated to their respective functions, e.g. regulator activity or molecular adaptor activity or molecular_function (if not known).

@srengel - the polymerase delta subunits sound like they might be a good example to explore further for our documentation.  Perhaps there is new experimental evidence to support a structural role for Pol31p?

This paper is very new, but might be a good jumping off point:

https://www.ncbi.nlm.nih.gov/pubmed/31582849

**Comment by deustp01** [comment]
A tangent here is that the EBI Complex Portal, I think, supports much richer vocabulary of things that components of a complex can do besides catalyze a reaction. So, continuing the discussion on the ontology call earlier today, we need to get a better process for moving annotations from Reactome and MGI (but also other annotators) into the Complex Portal in order to make those annotations available via the PRO ontology for use in GO-CAM models. Could that eventually do something to prevent the information loss @srengel describes?

**Comment by sjm41** [comment]
Probably an obvious point, but just to state that we do have GO-CC complex terms for these complexes, and all components will/should be annotated with those terms (regardless of whether they are catalytic or not).
E.g. delta DNA polymerase complex (GO:0043625)

**Comment by pgaudet** [comment]
@sjm41 A little clarification: Do you mean to say 'all complex members would be annotated to the complex' or to the function?

**Comment by sjm41** [comment]
I meant "'all complex members would be annotated to the (GO-CC) complex term", regardless of the GO-MF annotations each member may or may not have.

**Comment by pgaudet** [comment]
OK, right, this is correct. This is why it is useful to annotate the MF precisely to individual roles - otherwise the MF annotations become synonymous with the CC annotations. 

Pascale

**Comment by sjm41** [comment]
Hi @srengel, Did you decide that SGD would keep the contributes_to annotation for the delta subunit?
Regardless, @pgaudet - can the PAINT propagations Helen identified in the original ticket be blocked as it's clear (I think) that the propagation of terms to other species is not appropriate here.
Thanks.

**Comment by pgaudet** [comment]
Fixed in PAINT - thanks for the reminder !

**Comment by srengel** [comment]
Hi @sjm41 yes SGD curators discussed and decided to leave the yeast annotation as is.

**Comment by sjm41** [comment]
@pgaudet / @hattrill - I think this can be closed?

**Comment by pgaudet** [comment]
I think ? This family is annotated to 'DNA primase activity' and 'alpha DNA polymerase:primase complex' 

If this is right, please close. 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet 
Some confusion here - I think your last comment is about ticket #2725 (PTN000830013), which still needs addressing??

This ticket (#2664) is for issues relating to PTN000295225 & PTN000045935, which I believe is now resolved.  Agree @hattrill ?

**Comment by hattrill** [comment]
In terms of the original subject, contributes_to DNA-directed DNA polymerase activity PTN000295225 (PTHR12708), PTN000045935 (PTHR10416) seem to have been removed. So I will close this ticket.
