### ISSUE TITLE
IPR015088 nucleoside binding (GO:0001882)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2667]
IPR015088 has nucleoside binding (GO:0001882) associated. 
The GOC guidelines (http://wiki.geneontology.org/index.php/Annotating_binding) advise that substrate binding terms and catalytic activities should not be redundantly annotated. As this has:
DNA-directed DNA polymerase activity (GO:0003887), 
    nucleoside binding (GO:0001882) is not required.

Tagging @happy-lorna and @sjm41

**Comment by happy-lorna** [comment]
You are correct. I have removed the redundant annotation.
Thanks!
