### ISSUE TITLE
PAINT: PANTHER:PTN001173193 & FBgn0046332 gskt

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2669]
Could you block propagation of terms from PANTHER:PTN001173193 to FBgn0046332 gskt.

It's a bit of an odd case - a retro-transposed GSK-3 gene with testes-specific expression.
PMID:17179138

**Comment by pgaudet** [comment]
@hattrill I cannot find gskt in PMID:17179138 - is the paper using a synonym for that gene name ?

**Comment by pgaudet** [comment]
Thanks ! I removed the annotations. 

(I couldn't find the synonyms in FB or UniProt - I might have looked too quickly). 

Pascale

**Comment by hattrill** [comment]
No problem. 
We have a synonyms section on gene pages but there is also a lot of other stuff to hide it!

e.g. http://flybase.org/reports/FBgn0046332#synonyms
