### ISSUE TITLE
PANTHER:PTN001089332 (PTHR21533) negative regulation of Wnt signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2670]
Could you block propagation of 
negative regulation of Wnt signaling pathway
from PANTHER:PTN001089332 
to
FBgn0067317 Cby

As:
PMID:22508513
"The function of CBY in WNT signaling in vertebrates has either been acquired during vertebrate evolution or lost in Drosophila."

**Comment by pgaudet** [comment]
Fixed. Thanks for reporting.

**Comment by hattrill** [comment]
Thanks!
