### ISSUE TITLE
Review annotations to 'GO:0034225 regulation of transcription from RNA polymerase II promoter in response to zinc ion starvation' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2672]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move those annotations (6 SGD, 1 pombase)

https://docs.google.com/spreadsheets/d/1WxlzEuKuj_Yvervda8idQll1sEAflBKV7O66_MkMwg8/edit

Thanks, Pascale

**Comment by ValWood** [comment]
Fixed for PomBase

**Comment by srengel** [comment]
SGD done.
