### ISSUE TITLE
IPR001767 proteolysis

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2676]
Hi @happy-lorna 

IPR001767 Hedgehog protein, Hint domain

has peptidase activity (GO:0008233)
and proteolysis (GO:0006508)

which looks a bit strange for users looking at the annotations for hedgehog.

It looks like this is a protein splicing activity (PMC2614485)
so perhap the BP would be better as
 'protein autoprocessing' GO:0016540 
or 'protein splicing' GO:0030908

I *think* that 'peptidase activity' is probably wrong here as the catalytic event here is a transesterification.....I am way out of my comfort zone here, so perhaps @hdrabkin or @ukemi could help out here before I make a fool of myself!

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by typhainepl** [comment]
I didn't find any reference to peptidase activity either. I've removed the GO terms and added GO:0016540 to IPR001767.

**Comment by hattrill** [comment]
Thanks!

**Comment by sjm41** [comment]
FYI, I think this explains the original association of hh with peptidase activity:
https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=C46
"_Peptidase family C46 contains the C-terminal, intein-like domains of the hedgehog proteins, which mediate autolytic cleavage of the proteins._"
"_The autolytic cleavage occurs at a conserved -GlyCys- bond, and is mediated by the C-terminal domain of the hedgehog protein. This is the only peptidase activity expressed by the protein._"

I'm not sure whether or not it's correct/desirable/useful to annotate proteins that mediate cleavage of themselves (autolytic) with "peptidase activity"?
Anyone have thoughts on that general point?
