### ISSUE TITLE
APOPT1/COA8- not apoptosis? (PTN001579212/InterPro:IPR018796/CG14806/MGI) (PTHR31107)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2678]
FBgn0029594 CG14806/Coa8

I have just added  NOT apoptotic process to PMID: 31555154 for this gene. This particular function does not happen in flies.

In fact, it looks like it the function of APOPT1/COA8 might be COX complex biogenesis and the apoptosis link is a bit of a red herring - PMID:30552096. 

Mouse has the only experimentally supported annotations MGI:1915270, so perhaps @ukemi could check this out.
IEA annotations:@happy-lorna: InterPro:IPR018796 
IBAs @pgaudet PANTHER:PTN001579212

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by typhainepl** [comment]
Thanks for the highlight. I've updated the InterPro description.

**Comment by pgaudet** [comment]
Removed.
