### ISSUE TITLE
Review annotation to P57760

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2680]
hello, 

RGD | P57760 | Stk16 |   
Is a kinase, regulating a transcription factor, Please remove annotation to GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding (PMID:10947953)

Thanks, Pascale

**Comment by RLovering** [comment]
Hi 
This review PMID:30974739 also confirms the dual activity of this protein, possibly via alternative transcripts
Ruth
