### ISSUE TITLE
review annotations to GO:0052106 - "quorum sensing involved in interaction with host"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#2681]
As outlined in **OTR: meaning of "quorum sensing involved in interaction with host" #17757**, we think that this term doesn't have a clear meaning and has been used inconsistently. 

Here's the summary of the experimental and ISO annotations:
> 33 experimental & 10 ISO annotations: 
> --	BHF-UCL (1 IDA, 1 IMP – both annotations are challenged)
> --	GeneDB (31 IMP, 8 ISO – all could be moved to “quorum sensing”)
> --	MGI (1 ISO – depends on challenged annotation)
> --	RGD (1 ISO – depends on challenged annotation, **will it update automatically if human annotation changes?**)

All of the experimental ones come from two papers, one annotated by BHF-UCL and a second by GeneDB. The ISO ones by GeneDB all depend on IMP ones from the experimental paper. I've made recommendations shown both here and in the [annotation review spreadsheet](https://docs.google.com/spreadsheets/d/1CbN6MnMsubieRw5sPjCIZHn5It7YnRkTajj-NFS--i8/edit#gid=0) to track annotation review.

**Comment by krchristie** [comment]
@pgaudet - Do you know who to tag for GeneDB annotations?

**Comment by RLovering** [comment]
Hi Karen

please could you point me to where you have advised the change that should be implemented on the BHF annotation as this is not clear in the spreadsheet

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi @krchristie 
@Achchuthan takes care of GeneDB. 

All people are listed here for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

Thanks, Pascale

**Comment by pgaudet** [comment]
BTW Mouse and rat ISOs are assigned automatically.

**Comment by krchristie** [comment]
> Hi Karen
> 
> please could you point me to where you have advised the change that should be implemented on the BHF annotation as this is not clear in the spreadsheet
> 
> Thanks
> 
> Ruth

Hi @RLovering - I had put challenges into Protein2GO a few weeks ago when I first looked at the paper on both of the BHF-UCL annotations, so if you go to P2GO, you can see what I suggested.

Thanks,

-Karen

**Comment by Achchuthan** [comment]
Hi @krchristie 
I have changed annotations for all genes with GeneDB/ EuPathDB gene IDs in our database and updated the google sheet. However, there are two annotations with UniProt IDs, which are duplicates that trace back to the already updated GeneDB IDs. I left these two gene IDs in the google sheet. I hope these annotations will be updated once the UniProt records are updated next time from GeneDB.

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Actually @Achchuthan this is from GeneBD T. brucei 
We have an email contact f.silva-franco at liverpool.ac.uk

How does this work, do you work direct with your sources? 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet, Fatima has left her position in Liverpool and started a position in Spain. I have taken over T. brucei and other Kinetoplastida genomes in GeneDB/ EuPathDB. 

Both those UnIProt IDs map to Tb927.11.4610 in GeneDB. This gene ID also appears in the spreadsheet and I have corrected the annotation for it in our database. We only have Trypanosoma brucei brucei strain 927 genome in GeneDB. It appears to me that UnIprot have mapped gene IDs from Tb927 genome to other records from them. Two Uniprot IDs from this spreadsheet (Q95PL2 & Q9GU80) do not have any strain information in the organism, while another UniProt gene mapped from Tb927.11.4610 (Q385V6) is from the exact strain that we curate.

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Thanks @Achchuthan

**Comment by alexsign** [comment]
@Achchuthan hi, can you please send your email to goa@ebi.ac.uk . I'll update it as contact instead of Fatima in our database.

**Comment by alexsign** [comment]
@pgaudet we've trace the origin of this issue, and it's coming from GeneDB.
ftp://ftp.sanger.ac.uk/pub/project/pathogens/gff3/xrefs/uniprot-xrefs.txt
has
Q9GU80	Tb927.11.4610:pep
Q9GPG5	Tb927.11.4610:pep
Q385V6	Tb927.11.4610:pep

**Comment by pgaudet** [comment]
@Achchuthan Can you please check what @alexsign reported ?

**Comment by Achchuthan** [comment]
Thanks @alexsign and @pgaudet, I have sent an email to the above address from Alex. Thanks for tracing the origin of these UniProt mappings. I have anyway updated the annotations for Tb927.11.4610:pep in our database. So, it should be updated in UniProt once the GeneDB annotations are updated in UniProt next time.

**Comment by RLovering** [comment]
Thanks all UCL revisons done Ruth

**Comment by pgaudet** [comment]
@RLovering Are the BHF annotations done ?

**Comment by RLovering** [comment]
yes all BHF-UCL done

**Comment by RLovering** [comment]
done thanks
