### ISSUE TITLE
 Review annotations to protein homodimerization activity (GO:0042803)

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2682]
To continue the work on revising annotations made to GO terms that reflect stoichiometry of interactions, we would like curators to review a subset of manual annotations to 'protein homodimerization activity' (GO:0042803).

A few things for curators to note:

In the spreadsheet, I've listed only those annotations that need to be manually reviewed. Other annotations should be able to be changed en masse programmatically (depending on how groups handle the bulk changes).  

Spreadsheet:  https://docs.google.com/spreadsheets/d/1Kan24lkChsdq1bPgaWyAyDteEQxPCq2E73vNDJB29OQ

See this Google doc for more information on the proposed ontology changes:  https://docs.google.com/document/d/1JxzNwl1fr5Fj-IJy_Fo1lLfAlAQB8IxPDwwYKxIXBZo/edit#heading=h.oxlxrmsdkphr

As the suggested changes to existing annotations depends on the evidence code used, I've put annotations for each evidence code in a separate comment to hopefully make it easier for curators to hone in on the ones they need to review.

Any questions, please add a comment to the ticket. 

Thank you!

**Comment by vanaukenk** [comment]
**IMP**

Annotation to Annotations to **GO:0042803** (protein homodimerization activity) and evidence code ECO:0000315 (IMP)

Issue:  Need manual review to see if they refer to the wild-type function and if a corresponding experimental annotation to the wild-type protein exists
			**AgBase - 6
                         **BHF-UCL - 2
                         **CAFA - 38
                         **FlyBase - 4
			**MGI - 1 
                         **RGD - 3 (maybe done already?)
                         **UniProt - 27
                         **Zfin -1

**Comment by vanaukenk** [comment]
**IC**

Annotation to Annotations to **GO:0042803** (protein homodimerization activity) and evidence code ECO:0000305 (IC)

Action: remove
                         **RGD** - 3 
                         **UniProt** - 1

**Comment by vanaukenk** [comment]
**TAS**

Annotation to Annotations to **GO:0042803** (protein homodimerization activity) and evidence code ECO:0000304 (TAS)

Action: remove; if possible, check for or add corresponding experimental annotation
                         **AgBase** - 5   
                         **ARUK-UCL** - 1
                         **BHF-UCL** - 3
                         **dictyBase** - 4
                         **FlyBase** - 1
                         **ParkinsonsUK-UCL** - 5
                         **RGD** - 3 
                         **UniProt** - 28

**Comment by vanaukenk** [comment]
**NAS**

Annotation to Annotations to **GO:0042803** (protein homodimerization activity) and evidence code ECO:0000303 (NAS)

Action: remove; if possible, check for or add corresponding experimental annotation
                         **AgBase** - 1   
                         **BHF-UCL** - 5
                         **ParkinsonsUK-UCL** - 1
                         **UniProt** - 22

**Comment by vanaukenk** [comment]
**ISM**

Annotation to Annotations to **GO:0042803** (protein homodimerization activity) and evidence code ECO:0000255 (ISM)

Action: remove; if possible, check for or add corresponding experimental annotation
                         **FlyBase** - 4   (note separate tab in spreadsheet)

**Comment by hdrabkin** [comment]
Our people have yet to work on my work order to convert the ones to be changed en masse programmatically. It is a high priority annotation.

**Comment by vanaukenk** [comment]
Thanks for the update @hdrabkin 
There will be one or two more review tickets before we've covered all of the annotations and after that, I'll make the changes in the ontology.

**Comment by sabrinatoro** [comment]
I cannot find the ZFIN annotation to update, and I don't see it in our latest GAF file.

**Comment by vanaukenk** [comment]
Thanks @sabrinatoro - perhaps you had already made the change.  I don't see the annotation now in AmiGO, either.

**Comment by sabrinatoro** [comment]
@vanaukenk : yes, I took care of all the homo/hetero dimerization annotations when reviewing the previous case. :-)

**Comment by pfey03** [comment]
I"m done with Dicty TAS, thanks!

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 
I am not able to update my info in the spreadsheet (it's in the 'view only' mode even when I'm logged into google). I have just sent an edit access request. 
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
ARUK-UCL TAS removed.

**Comment by BarbaraCzub** [comment]
ParkinsonsUK-UCL all done.
cc @RLovering

**Comment by BarbaraCzub** [comment]
BHF-UCL NAS and TAS done.
cc @RLovering

**Comment by BarbaraCzub** [comment]
BHF-UCL IMP done.
cc @RLovering

**Comment by gthayman** [comment]
RGD done.

**Comment by hdrabkin** [comment]
removed MGI annotation as changing would lead to duplication from same reference. Done

**Comment by hattrill** [comment]
FB done

**Comment by pgarmiri** [comment]
UniProt- EBI and CAFA annotations have been checked and the actions were recorded in the excel form.

There are 6 annotations left that I can't alter as they have been created by SIB. I have put a comment at the end of the relevant rows and colored the box (purple).  @sylvainpoux , could you please take a look at those?

**Comment by gthayman** [comment]
Previously, the spreadsheet linked above was just our 9 RGD annotations. Now it's everyone's and I can't edit. Access request sent.

**Comment by suzialeksander** [comment]
Remaining spreadsheet entries are all "no need to review"
