### ISSUE TITLE
Question on annotation to GO:0006285

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#2685]
I am annotating pombe uracil DNA N-glycosylase Ung1 to 
Base Excision Repair, AP site formation

This protein removes uracil in DNA
Uracil can either occur via deamination of cytosine, or by misincorporation of dUMP during DNA synthesis

GO:0006285 has the two children
- GO:0097510 base-excision repair, AP site formation via deaminated base removal 
- GO:0045008 depyrimidination (The disruption of the bond between the sugar in the backbone and the C or T base, causing the base to be removed and leaving a depyrimidinated sugar)

1. The def of GO:0045008 could be extended to also include uracil? 
2. Should I annotate to both these terms?

Thanks!

**Comment by pgaudet** [comment]
Interestingly, GO:0045008 depyrimidination is a child of GO:0006285 base-excision repair, AP site formation. Maybe we should merge ?

**Comment by ukemi** [comment]
Be careful with this merge. PMID:22048164

**Comment by Antonialock** [comment]
do we need them since - they seem like one step reactions? Then we can annotate to MF + BER/chromatin organization, adaptive immunity, or whatever the MF is used for?

**Comment by Antonialock** [comment]
(i.e. depyrimidination, depurination, base-excision repair, base-free sugar-phosphate removal)

**Comment by pgaudet** [comment]
For sure depyrimidination, depurination are the single-step processes we have proposed to obsolete. I would say base-excision repair is an important repair mechanism and I would keep it in. 

Pascale

**Comment by Antonialock** [comment]
Yes of course, BER needs to stay.
I was referring to go:0006286 base-excision repair, base-free sugar-phosphate removal !

**Comment by pgaudet** [comment]
Ah OK. As far as I am concerned all those terms can go.

**Comment by Antonialock** [comment]
Thanks, I'll just annotate to BER directly
