### ISSUE TITLE
Review annotations for GO:0004584 	dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#2686]
The EC for this term has been split into 4 other EC ids; 
From the Comments field
The comments field:This term represents EC 2.4.1.130 and was too unspecific and covered several different enzymes with non-overlapping catalytic activities. 
Consider one of the following: GO:0052925, GO:0052926, GO:0052917 or GO:0052918. GO:0004584 is scheduled for obsoletion.
There are at least 77 manual annotations to this term. Please review and re-house to one of the other 4 terms.

refer to ontology  #18081

**Comment by pgaudet** [comment]
I created an annotation review spreadsheet: 
https://docs.google.com/spreadsheets/d/1lhBpUjWQMNe6gY9oCYZxajwTTlr1L9cE1h7ZiGEBzi8/edit#gid=0

I only find 11 manual annotations to GO:0004584: 

FlyBase: 1 
GeneDB: 3
PomBase: 1
SGD: 5 

@hdrabkin Can you check whether this is correct ? 

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.  rehoused under more general terms than those suggested because we need more guidance about how to use those specific terms.  would take a lot of reading/time to choose because would need to do some learning.

**Comment by hattrill** [comment]
SGD's done our one (by proxy ISS changes automated in P2GO)

**Comment by hdrabkin** [comment]
@pgaudet that number seems correct. 
BTW, I got a response from RHEA about this term, which I'll post pere and in the original ontology request.
This was concerning perhaps saving the term:
'Such a reaction does not exist. The problem would be how to define 'a membrane
    lipid-linked oligosaccharide. As the definition of the compound is indeed very
    vague, it would be impossible to create a structure of the substrate and the
    product which is a prerequisite to create a Rhea reaction. We cannot even
    create the oligosaccharide as a polymer as the mannose units can be added to
    several positions.'

**Comment by pgaudet** [comment]
Obsolete ?

**Comment by hdrabkin** [comment]
@pgaudet , I think yes.
