### ISSUE TITLE
IPR000308 protein domain specific binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2687]
IPR000308 14-3-3 protein is associated with 'protein domain specific binding' GO:0019904 - this is pretty vague and probably only appropriate for manual annotation with something specified in the 'with' field.

@happy-lorna

**Comment by typhainepl** [comment]
Thank for reporting this, I've updated the entry, the changes will be visible in the next InterPro release.

**Comment by hattrill** [comment]
Thanks
