### ISSUE TITLE
Check PAINT PTN001733184 annotation please.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2688]
PTN001733184 propagates "isomerase activity" based on a single annotation to E.coli paaG (P77467) to several potential orthologs, including fly Echs1 (Q7JR58) and human ECHS1 (P30084).

I'm not convinced this propagation is justified.

The fly protein hasn't really been studied, but the human protein was characterized biochemically in PMID: 26251176 as a hydratase - no mention of isomerase activity.

Do you mind checking on this?

@hattrill

**Comment by pgaudet** [comment]
Removed isomerase annotation.

**Comment by sjm41** [comment]
Thanks Pascale.
