### ISSUE TITLE
IPR003882 described as a plant domain but picks up animal proteins

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2689]
Hello, 

Can you remove or change 'structural constituent of cell wall (GO:0005199)' - this domain picks up animal proteins (for eg http://amigo.geneontology.org/amigo/gene_product/WB:WBGene00044011, http://amigo.geneontology.org/amigo/gene_product/UniProtKB:A0A3Q1MM77). 

Thanks, Pascale

**Comment by typhainepl** [comment]
Hi, Thank you for pointing this out. I've now removed the GO term. The changes will be visible in the next InterPro release (77.0)
