### ISSUE TITLE
'cell-substrate adherens junctions' annotation review

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-annotation#2690]
There is no such structure in biology as ‘cell-substrate adherens junctions’, because ‘adherens junctions’ are always ‘cell-cell junctions’. Consequently, we propose to obsolete the term: ‘cell-substrate adherens junctions’. (https://github.com/geneontology/go-ontology/issues/18119)

There are currently 3 experimental manual annotations for the exact term ‘cell-substrate adherens junctions’ and 4 ISS/ISO annotations and the affected groups include:

UniProt – 4 annotations 
RGD – 2 annotations @slaulederkind
MGI – 1 annotation @ukemi
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=exact&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0005924

![cell-substrate adherens junction annotations](https://user-images.githubusercontent.com/16541096/68221965-50dc4d80-fffb-11e9-89a5-8bfac638cd73.png)

Could you please track your changes in this spreadsheet: https://docs.google.com/spreadsheets/d/17G-3RrrUNB83uwyQ6LHHEvxayNfslqns71DriqqE1eo/edit 

Could you please review your annotations and:

1.	Re-annotate to ‘cell-substrate junction’ if there is the evidence for this in the annotated paper (or the paper that the annotation was transferred from by ISS/ISO).
2.	Re-annotate to ‘adherens junction’ if there is the evidence in the annotated paper (or the paper that the annotation was transferred from by ISS/ISO) that this is a ‘cell-cell adherens junction’.
3.	Re-annotate to another more specific appropriate term – perhaps ‘focal adhesion’ will be correct for some of these.

We propose the deadline of 15 Nov for completing this review.

Thank you,
Barbara, Mila and Ruth

cc @milarolo  @RLovering

**Comment by slaulederkind** [comment]
The single manual RGD rat annotation has been corrected.

**Comment by BarbaraCzub** [comment]
> @BarbaraCzub I created an 'Annotation Review' spreadsheet:
> 
> https://docs.google.com/spreadsheets/d/17G-3RrrUNB83uwyQ6LHHEvxayNfslqns71DriqqE1eo/edit
> 
> Please remove electronic and ISO annotations and paste the annotations to be reviewed there.
> 
> This allows us to track changes that are made.
> 
> Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Thanks @pgaudet, I'll add the annotations and a record of the RGD correction - thanks @slaulederkind

**Comment by milarolo** [comment]
UniProt/SWIE done

**Comment by BarbaraCzub** [comment]
> UniProt/SWIE done

Thanks, Mila! However, I see there is one annotation here that no one has claimed: UniProt is the contributor, but the gene product has the MGI gene ID...

**Comment by ukemi** [comment]
What's the paper? I'll have a look. If it doesn't need to be changed we are all set.

**Comment by BarbaraCzub** [comment]
Oh, I see now. The MGI gene ID is the same as Q62417, which you have added to the table. And the PMID is the same.

**Comment by BarbaraCzub** [comment]
So, Mila changed it, but in the row below.

**Comment by BarbaraCzub** [comment]
All experimental annotations have been reviewed and changed. Thank you!
