### ISSUE TITLE
PANTHER:PTN000389240 -> ubiquitin protein ligase activity (PTHR15160)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2692]
PANTHER:PTN000389240 adds "ubiquitin protein ligase activity" (GO:0061630) to fly Vhl (Q9V3C1) and Human VHL (P40337) amongst others.
But this is based on a single annotation to human P40337 from PMID:24899725  that is wrong (I'm currently disrupting that via protein2GO).  The assay in that paper used the Vhl complex (CUL2, Elongin C, Elongin B + VHL) in which VHL acts a regulatory or substrate-specificity component - it doesn't have catalytic activity itself.  Also see PMID:11006129 about fly Vhl. (seems Rbx1 is the actual E3 ligase here).

So I think "ubiquitin protein ligase activity" should be dropped from the PANTHER:PTN000389240 node.

@hattrill

**Comment by pgaudet** [comment]
Actually I had made a note that I wanted to use 'contributes_to'. I removed the MF annotation, but kept the 'protein ubiquitination'; does that seem OK to you ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Sounds good to me, thanks.
