### ISSUE TITLE
PANTHER:PTN000444160 - yeast don't have chloroplasts (PTHR19271)

### ISSUE THREAD

**Issue by srengel** [geneontology/go-annotation#2694]
Yeast BI3 Q9ZZW7 has a PAINT annotation to chloroplast thylakoid membrane.  yeast don't have chloroplasts.  can we please 1) remove this, and 2) not propagate any chloroplast annotations to yeast?

**Comment by ValWood** [comment]
I thought taxon constraints were working now?

**Comment by hattrill** [comment]
A full range of taxon constrains available for this one: https://www.ebi.ac.uk/QuickGO/term/GO:0009535 - seems to have failed as this has been propagated to the yeast COB (cytochrome B) and the yeast mitochondrial mRNA maturation factors B12, B13 and B14 and for the mitochondrial cytochrome Bs for other invert & vertebrates.

This node should be reviewed - a strange choice to propagate from a single evidence:
PANTHER:PTN000444160, TAIR:locus:504954695
for what should be a fairly well-characterised family (CYTOCHROME B (PTHR19271))

**Comment by pgaudet** [comment]
Fixed, thanks for reporting this.
