### ISSUE TITLE
Add GO:0003755 to IPR005788

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2696]
Hi,

Would you consider replacing "Isomerase activity (GO:0016853)" with the more specific "protein disulfide isomerase activity (GO:0003756)" on IPR005788 (Disulphide isomerase)?

IPR005788 already has an EC xref of 5.3.4.1 = Protein disulfide-isomerase

Thanks.

@hattrill

**Comment by sjm41** [comment]
Also for IPR041865 (Protein disulfide-isomerase A5, N-terminal TRX-like b domain), which also has the same EC xref?

**Comment by hattrill** [comment]
tagging @typhainepl

**Comment by typhainepl** [comment]
I've update the GO term for IPR05788. For IPR041865, only the human protein matches this term, which isn't enough evidence for InterPro to add the GO term.

**Comment by sjm41** [comment]
_I've update the GO term for IPR05788._ 
Great, thanks!

_For IPR041865, only the human protein matches this term, which isn't enough evidence for InterPro to add the GO term._
OK, understood.
But for the record, I also see 1 mouse protein, 2 fish proteins and 2 fly proteins with this domain (in addition to the single human protein).

**Comment by typhainepl** [comment]
@sjm41 _But for the record, I also see 1 mouse protein, 2 fish proteins and 2 fly proteins with this domain (in addition to the single human protein)._
That is correct, but only the human protein has literature evidence for this GO term.

**Comment by sjm41** [comment]
OK, thanks for clarifying. I'll close this now. Cheers, Steven.

**Comment by sjm41** [comment]
Hi,

I don't see the new GO term on http://www.ebi.ac.uk/interpro/entry/InterPro/IPR005788/
Is this in the pipeline and I just need to wait for a new InterPro release?

**Comment by typhainepl** [comment]
Hi, I forgot to mention it will be visible in the next InterPro release (78.0) which will happen at the end of February.

**Comment by sjm41** [comment]
Ah, OK.  Thanks!
