### ISSUE TITLE
PANTHER:PTN000287547 annotation (PTHR12592)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2698]
The "NADHX epimerase activity" and "NADPHX epimerase activity" terms associated with PANTHER:PTN000287547 should be removed (or at least restricted to bacteria).

Currently, these epimerase terms are being incorrectly added to fly Naxd and human NAXD (amongst others) - should only be applied to fly Naxe/human NAXE.

The sources for both these terms is given as:
- TAIR=AT5G19150|UniProtKB=Q94AF2 (this is wrong and I've disputed in protein2GO)
- EcoGene=EG11758|UniProtKB=P31806 (this correct because bacteria have a fused hydratase/epimerase gene)

The gene fusion and subsequent separation into two genes is nicely shown in fig 1B of PMID:24599492. To quote from that paper:
"The E. coli dehydratase and its counterparts in almost all other prokaryotes were shown to be fused to an N-terminal domain (Fig. 1B) that was predicted, and then demonstrated, to have NAD(P)HX epimerase activity (Marbaix et al., 2011). This epimerase domain has stand-alone homologs in yeast and mammals that were likewise shown to have NAD(P)HX epimerase activity (Marbaix et al., 2011)."

@hattrill

**Comment by sjm41** [comment]
FYI: the incorrect TAIR annotations have now been removed.
From Tanya: _Agreed. I've removed the annotations. This changes will be visible on TAIR by next Monday and in the next public GO GAF file which will be released at the end of December 2019/beginning of January 2020._

**Comment by pgaudet** [comment]
Fixed, thanks

**Comment by sjm41** [comment]
Thanks!
