### ISSUE TITLE
'cell-substrate adherens junction assembly' annotation review

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-annotation#2701]
Dear All,

Thank you very much for your reviews of the adherens junction-related cellular component terms https://github.com/geneontology/go-annotation/issues/2690 https://github.com/geneontology/go-annotation/issues/2691

Following on from this we also need to review the related biological process annotations prior to making  the required ontology changes
https://github.com/geneontology/go-ontology/issues/18129

### Re: point 4 in the ontology [issue](https://github.com/geneontology/go-ontology/issues/18129) 
I have prepared a review spreadsheet for 'cell-substrate adherens junction assembly'.

Based on the same principle as for the cellular components, could you please confirm whether the junction being assembled is (a) cell-cell adherens junction, or (b) cell-substrate junction?
If (a) is true, then please change your annotation to either 'cell-cell junction assembly', or its child term 'adherens junction assembly'.
If (b) is true, then please change your annotation to 'cell-substrate junction assembly'.

The experimental annotations requiring review are listed below. Could you please review your annotations and track your review actions in the Google spreadsheet hyperlinked below?

Thank you,
Barbara, Mila and Ruth

### cell-substrate adherens junction assembly

  | Count |  
-- | -- | --
ZFIN | 1 | @sabrinatoro

https://docs.google.com/spreadsheets/d/1pYEImdAeZEpA5mp04q9qotNdLKUrEtRn4IhaWwUKqVM/edit#gid=0

cc
@RLovering 
@milarolo

**Comment by sabrinatoro** [comment]
ZFIN annotation reviewed.
@BarbaraCzub, I guess this ticket can be closed?

**Comment by BarbaraCzub** [comment]
> ZFIN annotation reviewed.
> @BarbaraCzub, I guess this ticket can be closed?

Yes , thank you!
