### ISSUE TITLE
'adherens junction maintenance' annotation review

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-annotation#2702]
Dear All,

Thank you very much for your reviews of the adherens junction-related cellular component terms https://github.com/geneontology/go-annotation/issues/2690 https://github.com/geneontology/go-annotation/issues/2691

Following on from this we also need to review the related biological process annotations prior to making  the required ontology changes
https://github.com/geneontology/go-ontology/issues/18129

### Re: point 2 in the ontology [issue](https://github.com/geneontology/go-ontology/issues/18129) 
I have prepared a review spreadsheet for 'adherens junction maintenance'.

Based on the same principle as for the cellular components, could you please confirm whether the junction being maintained is (a) cell-cell adherens junction, or (b) cell-substrate junction?
If (a) is true, then please leave your annotations unchanged.
If (b) is true, then please request a new term: 'cell-substrate junction maintenance' and assign @BarbaraCzub and cross-reference this annotation review ticket.

The experimental annotations requiring review are listed below. Could you please review your annotations and track your review actions in the Google spreadsheet hyperlinked below?

Thank you,
Barbara, Mila and Ruth

### adherens junction maintenance

  | Count |  
-- | -- | --
FlyBase | 10 | @hattrill 
UniProt | 2 | @pgarmiri @sylvainpoux 
MGI | 2 | @ukemi
WB | 1 | @vanaukenk
ZFIN | 6 | @sabrinatoro
ARUK-UCL | 1 | @BarbaraCzub @milarolo 
RGD | 1 | @slaulederkind

https://docs.google.com/spreadsheets/d/19AXGQ3AygACY1HwY472aMGwwlpOktsrrmB-SiEmc4Oo/edit#gid=0

cc
@RLovering 
@milarolo

**Comment by milarolo** [comment]
The two UniProt annotations are SWIS. 
I don't see any ARUK one in the spreadsheet

**Comment by BarbaraCzub** [comment]
> The two UniProt annotations are SWIS.

Am I correct in assigning @sylvainpoux to review these?


> I don't see any ARUK one in the spreadsheet

Thanks, Mila, I will look into this.

**Comment by sylvainpoux** [comment]
Hi,
I checked the annotations and they are correct in my opinion
Thanks
Sylvain

**Comment by BarbaraCzub** [comment]
> Hi,
> I checked the annotations and they are correct in my opinion
> Thanks
> Sylvain

Thanks, Sylvain! Ok, I marked this in the [spreadsheet](https://docs.google.com/spreadsheets/d/19AXGQ3AygACY1HwY472aMGwwlpOktsrrmB-SiEmc4Oo/edit#gid=0): Comment: checked (and unchanged); Respondent: sylvainpoux 
Thanks,
Barbara

**Comment by slaulederkind** [comment]
RGD annotation checked.  It is okay to keep.

**Comment by sabrinatoro** [comment]
ZFIN annotations checked

**Comment by vanaukenk** [comment]
The WB annotation is also fine as is.  Thanks @BarbaraCzub !

**Comment by BarbaraCzub** [comment]
> RGD annotation checked. It is okay to keep.

Thank you!

**Comment by BarbaraCzub** [comment]
> ZFIN annotations checked

Thank you!

**Comment by BarbaraCzub** [comment]
> The WB annotation is also fine as is. Thanks @BarbaraCzub !

Thank you!

**Comment by hattrill** [comment]
FB done

**Comment by ukemi** [comment]
MGI done

**Comment by BarbaraCzub** [comment]
> FB done

Thank you!

**Comment by BarbaraCzub** [comment]
> MGI done

Thank you!
