### ISSUE TITLE
'protein localization to adherens junction' annotation review

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-annotation#2703]
Dear All,

Thank you very much for your reviews of the adherens junction-related cellular component terms https://github.com/geneontology/go-annotation/issues/2690 https://github.com/geneontology/go-annotation/issues/2691

Following on from this we also need to review the related biological process annotations prior to making  the required ontology changes
https://github.com/geneontology/go-ontology/issues/18129

### Re: points 7 and 8 in the ontology [issue](https://github.com/geneontology/go-ontology/issues/18129) 
I have prepared a review spreadsheet for 'cell-substrate adherens junction assembly'.

Based on the same principle as for the cellular components, could you please confirm whether the junction to which a protein localises is (a) cell-cell adherens junction, or (b) cell-substrate junction?
If (a) is true, then please leave your annotation unchanged (the GO term 'protein localization to adherens junction' will be repositioned to become a child of 'protein localization to cell-cell junction').
If (b) is true, then please request a new term: 'protein localization to cell-substrate junction' and assign @BarbaraCzub and cross-reference this annotation review ticket.

The experimental annotations requiring review are listed below. Could you please review your annotations and track your review actions in the Google spreadsheets hyperlinked below?

Thank you,
Barbara, Mila and Ruth

### protein localization to adherens junction

  | Count |  
-- | -- | --
FlyBase | 4 | @hattrill
MGI | 1 | @ukemi
ZFIN | 3 | @sabrinatoro
BHF-UCL | 3 | @RLovering @BarbaraCzub

https://docs.google.com/spreadsheets/d/1lJ6juV97mVVXYJarG82YW3m0cB-P3nrLcm1Ssv1OSNQ/edit#gid=0

cc
@RLovering 
@milarolo

**Comment by BarbaraCzub** [comment]
BHF-UCL done.

**Comment by sabrinatoro** [comment]
ZFIN done

**Comment by BarbaraCzub** [comment]
> ZFIN done

Thank you!

**Comment by ukemi** [comment]
MGI done

**Comment by BarbaraCzub** [comment]
> MGI done

Thank you!

**Comment by hattrill** [comment]
FB done

**Comment by BarbaraCzub** [comment]
> FB done

Thank you!
