### ISSUE TITLE
 IPR027084 not 	 protein serine/threonine/tyrosine kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2704]
fission yeast mph1 (	O94235) is a 	protein serine/threonine kinase activity
(i think this also applies to other family memebers)

**Comment by typhainepl** [comment]
@ValWood this annotation comes from the SGD database, should I replace it by the less specific GO term GO:0004674?

**Comment by ValWood** [comment]
Ignore me. This is dual specificity.
Sorry about that.
v
