### ISSUE TITLE
Review annotations to GO:0060154 cellular process regulating host cell cycle in response to virus

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2705]
Hi @hdrabkin 

There are 3 mouse annotations to 
GO:0060154 cellular process regulating host cell cycle in response to virus

It seems to me that the annotation to 'positive regulation of apoptotic process by virus' covers the data shown in the paper. I dont see where host cell cycle is being tested. 

**Spreadsheet is here: https://docs.google.com/spreadsheets/d/1MbQyxVFyXf-lPra5t5TlXv_C0-npaipLV2bo17dmIPQ/edit#gid=0**

Can you please check ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+ 1 UniProt annotation (also disputed in P2GO @milarolo)

**Comment by pgaudet** [comment]
@milarolo fixed the annotation

**Comment by LiNiMGI** [comment]
MGI annotations to 'positive regulation of apoptotic process by virus' removed. Thanks,
Li
