### ISSUE TITLE
PANTHER:PTN002375404 DNA dealkylation involved in DNA repair (PTHR24075)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2706]
PTN002375404 DNA dealkylation involved in DNA repair is based on one annotation. Looking cross-species, I can't see if that function is conserved. In yeast, a role in translation and in D.mel splicing.

However, that it has helicase activity could be propagated safely....(but not safe to make the call RNA or DNA specific)

**Comment by pgaudet** [comment]
@dustine32 Can we look at why some annotations were unobsoleted here ?

**Comment by pgaudet** [comment]
BTW I fixed what @hattrill requested.

**Comment by dustine32** [comment]
@pgaudet Sure! Are you referring to these recent unobsoletions in PTHR24075?
```
2019-10-28: PAINT annotation to PTN001940172 with GO:0004386 was unobsoleted because it now has valid experimental evidence.
2019-10-28: PAINT annotation to PTN002375404 with GO:0043138 was unobsoleted because it now has valid experimental evidence.
2019-10-28: PAINT annotation to PTN002375518 with GO:0003724 was unobsoleted because it now has valid experimental evidence.
```

**Comment by pgaudet** [comment]
yes

**Comment by dustine32** [comment]
Cool! So, in the PAINT update pipeline, we recently (in response to https://github.com/pantherdb/fullgo_paint_update/issues/36) got the evidence search to look if a PAINT IBD annotation can be supported by any experimental GO annotation to the same term _or a more specific term_. In one case here, we consider an exp GO annotation of 'RNA helicase activity' on yeast and human genes able to support the 'helicase activity' IBD on an ancestor node.

Here are the supporting GO annotations in the PAINT DB for those three unobsoleted IBDs:
`PTN001940172 with GO:0004386`:

| ibd_term   | ibd_name          | exp_term   | exp_name              | exp_gene       | eco |
|------------|-------------------|------------|-----------------------|----------------|-----------------|
| GO:0004386 | helicase activity | GO:0003724 | RNA helicase activity | UniProtKB:O75643     | IDA             |
| GO:0004386 | helicase activity | GO:0003724 | RNA helicase activity | SGD:S000000974 | IDA             |
| GO:0004386 | helicase activity | GO:0003724 | RNA helicase activity | SGD:S000000974 | IMP             |
| GO:0004386 | helicase activity | GO:0004386 | helicase activity     | UniProtKB:O75643     | IDA             |

`PTN002375404 with GO:0043138`:

| ibd_term   | ibd_name                    | exp_term   | exp_name                    | exp_gene         | eco |
|------------|-----------------------------|------------|-----------------------------|------------------|-----|
| GO:0043138 | 3'-5' DNA helicase activity | GO:0043138 | 3'-5' DNA helicase activity | UniProtKB:Q8N3C0 | IDA |

`PTN002375518 with GO:0003724`:

| ibd_term   | ibd_name              | exp_term   | exp_name              | exp_gene         | eco |
|------------|-----------------------|------------|-----------------------|------------------|-----|
| GO:0003724 | RNA helicase activity | GO:0003724 | RNA helicase activity | UniProtKB:O75643 | IDA |
| GO:0003724 | RNA helicase activity | GO:0003724 | RNA helicase activity | SGD:S000000974   | IDA |
| GO:0003724 | RNA helicase activity | GO:0003724 | RNA helicase activity | SGD:S000000974   | IMP |

**Comment by dustine32** [comment]
@pgaudet So the other reason these IBDs were only recently unobsoleted involves some internal DB nerdery. When a previously obsoleted GO annotation reappears in our DB, we make a new record rather than unobsoleting the existing GO annotation record. This way we have a history. Unfortunately, when asking if a PAINT annotation could be unobsoleted due to reappearing evidence, we were then only checking the links to those old GO evidence records, which of course were never going to be unobsoleted.

Anyhow, that screwup was also fixed as part of the https://github.com/pantherdb/fullgo_paint_update/issues/36 changes. Let me know if you have any other questions about these.

**Comment by pgaudet** [comment]
OK - let's assume it's OK - but I am really surprised how many time we see previously obsoleted GO annotation reappearing. This is more likely due to how the annotations are recognized as valid/obsolete than by actual obsoletion and reannotation to the same term. 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet Agreed that it is odd!

Looking at the dates on these annotations, which I think are just set by the upstream MOD, they've been around for years. I did notice that all of these GO annotations were obsoleted during the 2019-07-23 PAINT DB update. It would be wonderful to figure out why they were obsoleted, either missing in a data file or dropped by a update query that's likely already changed. I'll take a quick look.

**Comment by pgaudet** [comment]
Thanks !
