### ISSUE TITLE
PANTHER:PTN001477696 transmembrane receptor protein tyrosine phosphatase signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2708]
PANTHER:PTN001477696 transmembrane receptor protein tyrosine phosphatase signaling pathway
This is only supported by FBgn0033668 (exp) and it is incorrect. I have removed the annotation but it will be > 2 months before you see that as we've just finished this release cycle, so you might want to remove it from PAINT rather than waiting.

**Comment by pgaudet** [comment]
Replaced by 'signal transduction', according to PMID:25849395. let me know if this is not correct. 

Thanks, Pascale

**Comment by hattrill** [comment]
There's not much evidence for that - doesn't work in TGF-beta signaling, like other SMADs. Interacts with RTK signaling (in one paper), but looks like it is acting downstream - all phenotypes and nothing to distinguish where it is acting.

It also has an annotation to chitin biosynthetic process which has been propagated via PANTHER:PTN001100555 from a secretion phenotype (but that's just a readout, not a functional assay). I am going to remove this as well (and also that for the other supporting gene - so you might want to remove this as well). I will probably just end up with 'trachea morphogenesis' as that seems ok (but probably not ok to propagate to other species).

**Comment by pgaudet** [comment]
I removed all annotations (I wasn't sure of the strength of the evidence for cytoplasm and membrane).

**Comment by hattrill** [comment]
Thanks (I removed membrane as well)....trashed this gene's annotations!
