### ISSUE TITLE
IPR011701 add MF: transmembrane transporter activity ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2710]
Hello, 

Can you add MF: transmembrane transporter activity to IPR011701 ? 
and maybe to IPR020846 and IPR036259? 

Thanks, Pascale

**Comment by typhainepl** [comment]
Hi,
Thanks for highlighting this. I've added the GO term to IPR011701 and IPR020846.
Regarding IPR036259, we generally do not assign GO terms to Homologous superfamily entries.

**Comment by pgaudet** [comment]
OK thanks !
