### ISSUE TITLE
Review human annotations for ALB UniProtKB:P02768

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#2711]
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P02768

Albumin has many annotations, but do these truly reflect the actual function? And it seems that we have no annotations to its actual function which is regulation of oncotic pressure (GO:0030104), and as a carrier protein for specific substances?

I'll review some annotations on a paper by paper basis. This is not comprehensive, and my reading of some papers may be too cursory.

- [x] ## Shotgun proteomics reveals specific modulated protein patterns in tears of patients with primary open angle glaucoma naïve to therapy.

http://amigo.geneontology.org/amigo/reference/PMID:23580065

All annotations are high-throughput. Either to 'retina homeostasis' or 'extracellular space of lacrimal gland'. I think the first is dubious and the second is not meaningful.

There are other high-throughput papers annotated, and these also produce not very meaningful annotations

- [x] ## Albumin prevents mitochondrial depolarization and apoptosis elicited by endoplasmic reticulum calcium depletion of neuroblastoma cells

http://amigo.geneontology.org/amigo/reference/PMID:16153637

yields annotations to negative regulation of apoptotic process + maintenance of mitochondrion location

From the abstract _These results suggest that albumin protects cells from entering into apoptosis by preventing mitochondrial depolarization_

Why not annotate to the more proximal and direct function (preventing mt depolarization, i.e. GO:0051902)?

(arguably the ontology could have the causal relation between GO:0051902 and apoptosis)

- [x] ## Human serum albumin and its N-terminal tetrapeptide (DAHK) block oxidant-induced neuronal death.

http://amigo.geneontology.org/amigo/reference/PMID:14726550

yields annotations to copper ion binding, antioxidant activity, and negative regulation of programmed cell death

The antioxidant activity seems justified, and copper ion binding is not wrong, but IMO unsatisfying as these two annotations should be combined together, is AFAIK the N-terminus of ALB has a function binding of free transition metals controlling their reactivity and limit their availability for the Fenton reaction. 

see e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3577569/

 But I question the neg reg of PCD. It's certainly causally upstream of neuronal death, in the experimental system chosen. But regulation of a program is too strong.

If we really believe this annotation then why don't we just add a *negatively regulates* link in the ontology between *antioxidant activity* and *apoptosis*?

- [ ] ## all those binding annotations

We have lots of binding annotations. If the binding reflects a meaningful function, what is it? GO doesn't say. This is a well studied protein so this doesn't reflect a knowledge gap, just excessive annotation to the experiment. 

- [ ] ## From reactome

Lots of annotations to 'extracellular' from Reactome, but not to the actual function which is transport, e.g. http://www.reactome.org/content/detail/R-HSA-264679 -- maybe we can look at next week @ukemi

**Comment by deustp01** [comment]
> Lots of annotations to 'extracellular' from Reactome, but not to the actual function which is transport, e.g. http://www.reactome.org/content/detail/R-HSA-264679

Good point. Albumin is a ubiquitous low specificity binder of all sorts of hydrophobic stuff under physiological conditions, but it would be appropriate, in the spirit of the "all those binding annotations" comment, to restrain ourselves and annotate only those cases i) where the binding has the effect of _sequestering_ something that could do damage or be damaged or lost if it were left to circulate on its own; and / or ii) where the binding enables the _transport_ of a cargo too water-insoluble to get to where it needs to be on its own. And in those cases, we could use more specific MF terms rather that generic "binding". We are starting to look for and fix cases like this as part of the project to get more complete GO-CAM models out of Reactome pathways (plain binding reactions yield incomplete GO-CAMs by definition), so if someone sees a way to detect these improve-able binding annotations systematically, that would be great. Otherwise, we will stumble on them as we traverse our incomplete GO-CAMs and fix them as we find them. @ukemi anything to add?

**Comment by pgaudet** [comment]
> ## Shotgun proteomics reveals specific modulated protein patterns in tears of patients with primary open angle glaucoma naïve to therapy.
http://amigo.geneontology.org/amigo/reference/PMID:23580065

Delete BP annotations to  GO:0001895 | retina homeostasis

**Comment by pgaudet** [comment]
>  ## Albumin prevents mitochondrial depolarization and apoptosis elicited by endoplasmic reticulum calcium depletion of neuroblastoma cells

http://amigo.geneontology.org/amigo/reference/PMID:16153637


Changed annotation to GO:0051902 as suggested

**Comment by pgaudet** [comment]
## Albumin prevents mitochondrial depolarization and apoptosis elicited by endoplasmic reticulum calcium depletion of neuroblastoma cells

http://amigo.geneontology.org/amigo/reference/PMID:16153637


Removed annotation to neg reg of PCD

I dont think we can add a *negatively regulates* link in the ontology between *antioxidant activity* and *apoptosis*; I think there are responses to oxidative stress that are not apoptosis

**Comment by pgaudet** [comment]
I fixed the UniProt annotations, except for binding - this protein is not any worse than others in that respect. We need a more global discussion for binding. 

I leave this open in case @deustp01 wants to do more reviews for Reactome (otherwise, @deustp01 , please close).
