### ISSUE TITLE
InterPro - mappings to GO:0140142 nucleocytoplasmic carrier activity

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#2712]
There are three InterPro2GO mappings to GO:0140142 nucleocytoplasmic carrier activity, but this term is in the 'gocheck_do_not_annotate' subset.

Perhaps more specific MF terms can be mapped to these three domains?

InterPro:IPR027140 Importin subunit beta-1, plants > GO:nucleocytoplasmic carrier activity ; GO:0140142

InterPro:IPR036975 Importin-alpha, importin-beta-binding domain superfamily > GO:nucleocytoplasmic carrier activity ; GO:0140142

InterPro:IPR040016 Exportin-6 > GO:nucleocytoplasmic carrier activity ; GO:0140142

Thanks!

**Comment by happy-lorna** [comment]
@typhainepl

**Comment by typhainepl** [comment]
Hi @vanaukenk, thanks for highlighting this. I've updated the InterPro entries. The changes will be visible in InterPro 78.0

**Comment by vanaukenk** [comment]
Thanks @typhainepl and @happy-lorna !
