### ISSUE TITLE
Review annotation to GliA AspGD, ASPL0000109327

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2713]
Hi @marekskrzypek 

1. GliA (transporter) is annotated to 'mycotoxin biosynthetic process' and gliotoxin biosynthetic process; this is incorrect. 
Can you remove the 3 annotations (IGC, IEP, ISS) and replace with 'toxin transmembrane transporter activity', using 'has input ' CHEBI:5385 (gliotoxin). 
(PMID:24847038)

2. laeA (protein methyltransferase-like): please remove 'gliotoxin biosynthetic process' ('positive regulation' is OK)

3. cclA (histone methytransferase) : please remove 'gliotoxin biosynthetic process' ('positive regulation' may be OK, but probably quite indirect)

4. gliZ (Zn2Cys6 binuclear transcription factor): please remove 'gliotoxin biosynthetic process' and  'mycotoxin biosynthetic process'  ('positive regulation' may be OK, but probably quite indirect)

5. hdaA (histone deacetylase) : please remove 'gliotoxin biosynthetic process' ('positive regulation' may be OK, but probably quite indirect)

6. rsmA1 (transcription factor):  please remove 'gliotoxin biosynthetic process' and  'mycotoxin biosynthetic process'  ('positive regulation' may be OK, but probably quite indirect)

7. gpgA (G protein-coupled receptor gamma subunit): please remove 'gliotoxin biosynthetic process' ('positive regulation' is OK)

8. sfaD (G protein-coupled receptor beta subunit) : please remove 'gliotoxin biosynthetic process' ('positive regulation' is OK)

Thanks, Pascale

**Comment by marekskrzypek** [comment]
Hi Pascale,
I thought it was FungiDB folks who were going to take over the maintenance of AspGD GO annotations. As I understand, Achchu is their contact person, (A.Shanmugasundram2@liverpool.ac.uk). But I am not sure what the current status is, so please, let me know if it is still not entirely up and running and I need to keep doing the GO errors. BTW, AspGD has never implemented Column 16, so the No 1 request will be hard to do.
Cheers,
Marek

**Comment by pgaudet** [comment]
@Achchuthan

**Comment by Achchuthan** [comment]
Hi @pgaudet & @marekskrzypek, 
The plan was for FungiDB to take over the maintenance of of AspGD GO annotations. As we are currently working on the merger of EuPathDB databases with VectorBase and moving towards new annotation platform for next year, its not entirely up and running and we have not loaded the AspGD annotations into our curation database. It would be great if you could do the maintenance of annotations for the time being. 
Thanks & best wishes,
Achchuthan

**Comment by marekskrzypek** [comment]
OK, these ones are now done.
Marek

**Comment by pgaudet** [comment]
Thanks !
