### ISSUE TITLE
taxon violations for pombe

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2714]
All "multicellular" terms

cdc2 | cyclin-dependent protein kinase Cdk1/Cdc2 |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000623979TAIR:locus:2099478 | cell division protein kinase pthr24056 | protein |   | PMID:21873635 | 20170228

  | mss1 | mitochondrial tRNA wobble uridine modification GTPase Mss1 (predicted) |   | embryonic organ development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000746268ZFIN:ZDB-GENE-050522-335 | family not named pthr42714 | protein |   | PMID:21873635 | 20170828

  | mbx1 | MADS-box transcription factor Mbx1 |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000235373UniProtKB:Q9FIS1UniProtKB:Q9XJ66 | mads box protein pthr11945 | protein |   | PMID:21873635 | 20170829

  | mbx2 | MADS-box transcription factor Pvg4 |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000235373UniProtKB:Q9FIS1UniProtKB:Q9XJ66 | mads box protein pthr11945 | protein |   | PMID:21873635 | 20170829

  | ldb1 | LIM domain binding protein, transcription co-repressor |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001623859TAIR:locus:2029137 | lim domain-binding protein pthr10378 | protein |   | PMID:21873635 | 2017082

**Comment by marcfeuermann** [comment]
I'm amazed that there are still such kind of propagations. All of them have been removed.
