### ISSUE TITLE
suspect mapping for wdr55 IPR037628

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2716]
wdr55 is a conserved protein involved in ribosome biogenesis
but the pombe member
https://www.pombase.org/gene/SPAC1A6.02 	O13856
is mapped to panther
PTHR22652	PANTHER	PTHR22652	IPR037628	Nucleoporin Nup43
this is mapped to 	
nuclear pore outer ring
and is false positive for O13856

**Comment by typhainepl** [comment]
Thanks for highlighting this, I've unintegrated the InterPro entry.
