### ISSUE TITLE
Exclude fly protein from PAINT PTN001842290 - PTHR21008 annotation please

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#2717]
PANTHER:PTN001842290 propagates "rRNA (adenine) methyltransferase activity" activity based on single annotation to S.cerevisiae (P38278) to several potential orthologs, including fly Samtor (Q9W138) and Human BMT2 (Q1RMZ1).

We are not convinced with this propagation. Fly protein and even human protein have no orthology with the yeast protein.
The fly protein was studied and showed to be a regulator of mTORC1 signaling via interaction with the GATOR1 and KICSTOR complexes in PMID:29123071. 
Though it has the methyltransferase domain there is no mention about "rRNA (adenine) methyltransferase activity".

Can you please check this?

@hattrill
@sjm41

**Comment by hattrill** [comment]
So, probably the best action is to remove propagation by PAINT from this node and wait until there is more experimental data.

**Comment by sjm41** [comment]
HI @pgaudet @marcfeuermann  - Any thoughts on this one from Dec 2019? Thanks.

**Comment by pgaudet** [comment]
Fixed

**Comment by sjm41** [comment]
Great, thanks @pgaudet !
