### ISSUE TITLE
Review annotations using extension 'inhibited_by'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2719]
We'd like to remove the relation 'inhibited_by'. Please review your annotations here:

https://docs.google.com/spreadsheets/d/17SV7E7MUlJzyfc5c8DKss2yqPAIgXIXN1xMXNioWc-U/edit#gid=0

Assigned   by | Number of annotations
-- | --
AgBase | 20
BHF-UCL | 10
PomBase | 63
SGD | 12
UniProt | 3

Thanks, Pascale

**Comment by RLovering** [comment]
so does all this informaton just get deleted? there are no suggestions for how to capture this in other ways?

**Comment by ValWood** [comment]
We wanted to keep the info in PomBase but I guess it is outside the scope of GO. We  are migrating it to "miscellaneous" curation... (I don't think there is an different way to vcapture it in GO)

**Comment by pgaudet** [comment]
@ValWood @RLovering Can you give an example of what you were trying to capture ? These annotations don't seem to fit the 'causal' model, but perhaps we can capture this another way ? 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi, the UniProt annotations have been reviewed and updated.
Thanks,
Penelope

**Comment by srengel** [comment]
SGD annotations done.  i removed all the inhibited_by.

**Comment by RLovering** [comment]
BHF-UCL done

**Comment by ValWood** [comment]
PomBase done

**Comment by pgaudet** [comment]
Not used anymore
