### ISSUE TITLE
Review annotations to response to host defenses

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2721]
Those should only be annotated to symbiont proteins: 

3 MGI annotations: 

https://docs.google.com/spreadsheets/d/1xbA1coHL_zyoux_Bv-35LkKG8NDn9T9CQ9xvW8La8mA/edit#gid=0

Please change or remove. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Can I see the ticket number for the reasoning behind this?

**Comment by pgaudet** [comment]
The reasoning is in the definition: 

* **GO:0052063    induction by symbiont of defense-related host nitric oxide production**
Def: The activation by a symbiont of the production of nitric oxide as part of the defense response of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction. 

* **GO:0052565   response to defense-related host nitric oxide production**
Def: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of nitric oxide produced as part of the defense response of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

* **GO:0052567  response to defense-related host reactive oxygen species production**
Def: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of reactive oxygen species produced as part of the defense response of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction

Mouse is always the host, so these terms cannot be used to annotate mouse genes. 

OK ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
This was done; could have SWORN I updated spreadsheet. Might have been for a different one. You can close this one .

**Comment by pgaudet** [comment]
Thanks !
