### ISSUE TITLE
Incorrect annotations for the E. coli outer membrane vitamin B12 transporter, BtuB (PTHR30069)

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-annotation#2723]
I have attached a spreadsheet detailing a dozen wrong annotations that have been imported into EcoCyc for BtuB. The source of the incorrect terms relating to siderophore and enterobactin transport is Panther and the source of the incorrect ion channel terms is CAFA. 

BtuB does not mediate enterobactin transport; it is a TonB dependent OM transporter that is specific for cobalamin. It has been extensively studied; a few recentish references are PMIDs 27693114, 24243114, and 14499604. It is also not an ion channel; the literature reference provided for the CAFA annotation is PMID 15465872 Zakharov04 which actually reports that BtuB does not function as an ion channel. 

Are you able to remove these annotations? or can you advise me who I should I contact for assistance
Thank you 
Amanda Mackie
EcoCyc curator

[BtuB GO annotations.xlsx](https://github.com/geneontology/go-annotation/files/3924543/BtuB.GO.annotations.xlsx)

**Comment by pgaudet** [comment]
Thanks @amandamackie 
* PMID 15465872 should be used to annotate  ompF and tonB to 'colicin transmembrane transporter activity', right ?

**Comment by pgaudet** [comment]
Fixed PAINT annotations.

**Comment by amandamackie** [comment]
Thanks for the prompt action on those annotations.

Regarding OmpF:  it's a non specifc outer membrane porin so its biological function is to mediate diffusion of small solutes; the colicins 'parasitize' it to gain entry into the cell. If you wish to annotate the colicin function then yes, PMID 15465872 could be used, although I think PMID 21098297 (Housden et al 2010) is more definitive. 

Similar deal for **TolC** which is the OM efflux channel for toxic stuff in E. coli but is used by colicins to get into the cell - I haven't got a good reference for it but 15465872 would suffice. PMID 23176499 is a good review for colicin import in general.

PS: I think you've used 'TonB' by mistake in your question; TonB is a different protein - it energizes the import of B12 through BtuB. TolC is the OM channel parasitized by colicins and it is the protein referred to in PMID15465872 (along with OmpF).
