### ISSUE TITLE
Review annotation to DNA binding transcription factors

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2726]
Hello, 

Some proteins annotated to GO:0003700 DNA-binding transcription factor activity do not look like DNA-binding transcription factors. Please review
https://docs.google.com/spreadsheets/d/1hGvuM9KJepT_HQMxNPI1CCRtUFvZIfh0l_xOsd8UIfA/edit#gid=0

BHF @RLovering 
PINC @pgaudet / @RLovering 
UniProt @pgaudet 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, there are a number of InterPro families that sound probably not be mapped to GO:0003700: 


InterPro families
--
InterPro:IPR003894
InterPro:IPR002515
InterPro:IPR003106
InterPro:IPR012890
InterPro:IPR000232
InterPro:IPR029138
InterPro:IPR016659
InterPro:IPR037249
InterPro:IPR036060

@typhainepl @happy-lorna Can you please review them ? 


Thanks, Pascale

**Comment by typhainepl** [comment]
Hi, thanks for highlighting this, I've deleted the term from the InterPro entries, however I am not so sure for the following one:
InterPro:IPR000232, it represents the DNA-binding domain of the Heat shock factor, which is a transcriptional activator of heat shock genes

**Comment by pgaudet** [comment]
@RLovering Does IPR000232 seem like it can stay to you ? (the InterPro description is convincing)

**Comment by pgaudet** [comment]
Done
