### ISSUE TITLE
Review PAINT families that should not be annotated to GO:0003700 DNA-binding transcription factor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2727]
- [x] PANTHER:PTN000829442, PTN000829417 -> PTHR10528 AF4
 - [x] PANTHER:PTN000919548 -> PTHR11723: redo see https://github.com/geneontology/go-annotation/issues/2727#issuecomment-571659302
 - [x] PANTHER:PTN000088533 -> PTHR45893
 - [x] PANTHER:PTN000383895 -> PTHR14955
 - [x] PANTHER:PTN001818762 -> PTHR16515
 - [x] PANTHER:PTN002802863 -> removed in Panther 17
 - [x] PANTHER:PTN000001154 -> PTHR10015 -> I think this one is OK

**Comment by pgaudet** [comment]
@hattrill 
For PTHR10528: FBgn0041111 annotation to 'GO:0003700 DNA-binding transcription factor activity' should be moved up to  GO:0140110 transcription regulator activity. 

Alternatively - I haven't looked at the paper, just the abstract, but it does look like it's a co-regulator, so if the evidence is there, perhaps annotate to 'GO:0003712 transcription coregulator activity' 

Thanks, Pascale

**Comment by hattrill** [comment]
The experimental annotation (IMP) is a UniProt one, so tagging @pgarmiri to look at this. We've got a couple of ISS to human genes. I'll have a look at those.

**Comment by pgaudet** [comment]
PTHR11723: Disputed the following in P2GO

-- | -- | -- | -- | -- | -- | -- | -- | --
SWIE | P20067 | Id1 | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) | PMID:17681138 |   |  
SWIE | P41133 | Id3 | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) | PMID:17681138 |   |  
SWIE | Q14469 | HES1 | GO:0003700 | DNA-binding transcription factor activity | ECO:0000

**Comment by pgarmiri** [comment]
> 
> 
> The experimental annotation (IMP) is a UniProt one, so tagging @pgarmiri to look at this. We've got a couple of ISS to human genes. I'll have a look at those.

Hi, I looked at that and changed the annotation to GO:0003712  'transcription coregulator activity' as the suggested term is nor suitable for manual annotation.
Thanks,
Penelope

**Comment by pgaudet** [comment]
PTHR11723 -> I think ID1 (P41134), ID2 (Q02363), ID3 (Q02535) and ID4 (P47928) are co-repressors - is this right @colinlog ?

**Comment by colinlog** [comment]
I would rather call them inhibitors or repressors of dbTFs.
A bona fide co-repressor would be recruited to a chromosomal site by DNA
binding competent dbTF to inhibit transcription. Examples are histone
deacetylases or H3K9methylases.
The concept in the literature is that ID proteins can form dimers with
other bHLH proteins but they lack theDNA binding domain. Hence, they bind
to a dbTF monomer and thus stop it from binding to chromosomal DNA. So they
do not co-repress [on-DNA], they just repress before DNA is bound. They are
not co-factors, rather they are repressors of a dbTF's DNA binding activity.
