### ISSUE TITLE
PTN002747256 cytoskeleton

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2728]
cytoskeleton is being propagated from PTN002747256 from a single source.

Although some of the F-BAR domain proteins can bind cytoskeletal proteins, I don't think that propagating that CC is correct. The orthology for the source is fairly limited as well:
https://www.alliancegenome.org/gene/HGNC:9581#orthology

For FB this node hits:
FBgn0037702 CG8176
FBgn0053094 Synd

(In general, I think that the propagation of terms from BAR domain proteins could do with a review - there is a lot of nesting/overlap and some ours are ending up with 8-14 IBAs.)

**Comment by marcfeuermann** [comment]
Updated
