### ISSUE TITLE
PTN000129806 associated with lots of Cul-RING ubiquitin ligase complex terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2731]
PTN000129806 is associated with a lot of CulX-RING ubiquitin ligase complex terms. As the cullin-E3 partners are quite specific, rather than propagating lots of the specific complexes which is resulting in incorrect annotations, propagating the parent complex term 'cullin-RING ubiquitin ligase complex' would be more accurate.
Also, the process term 'SCF-dependent proteasomal ubiquitin-dependent protein catabolic process' is specific to a specific subset of complexes, so just keeping 'ubiquitin-dependent protein catabolic process' would be more correct.

**Comment by marcfeuermann** [comment]
Annotation has been cleaned following your suggestions.
