### ISSUE TITLE
	 vesicle docking IEA  with IPR009976

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2732]
seems to be incorrect for the F-box protein 

O74854

(at least seems indirect)

**Comment by ValWood** [comment]
I think its because it's  related to the exocyst complex F-box subunit sec10

**Comment by typhainepl** [comment]
Hi,
Thank you for highlighting this, I've removed the GO term from the InterPro entry, as it wasn't matching any protein in the entry anymore.
