### ISSUE TITLE
Incorrect Paint annotation for E. coli flagellar rod proteins FlgG, FlgF, FlgC and FlgB

### ISSUE THREAD

**Issue by amandamackie** [geneontology/go-annotation#2733]
These 4 proteins are flagellar rod proteins in Salmonella and E. coli (Table 1 in Berg 2003 PMID 12500982; or a more recent review is Minamino15 PMID 25613993). They are incorrectly annotated with the CC term GO:0009424 'bacterial-type flagellum hook' (21873635:EV-COMP-IBA:3697257600:GO_CENTRAL::PANTHER\:PTN000764839). 

The correct term should be GO:0030694 'bacterial-type flagellum basal body, rod' 

Thanks
Amanda (EcoCyc)

**Comment by marcfeuermann** [comment]
Propagation removed, but still no primary annotation to GO:0030694 'bacterial-type flagellum basal body, rod'
