### ISSUE TITLE
PTN002356460 CG10702 not an RTK

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2737]
PTN002356460  	TYROSINE-PROTEIN KINASE RECEPTOR (PTHR24416)

D.mel CG10702 does not have a RTK domain (has homology with Insulin-related receptor which is why it gets hit). Could you block propagation from this node?

**Comment by hattrill** [comment]
tagging @phanivg

**Comment by pgaudet** [comment]
Fixed.

**Comment by hattrill** [comment]
That was quick. Thanks!
