### ISSUE TITLE
Definition for secretion term

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2738]
Hi
please could the definition for secretion be improved to provide a beginning and end to this process. Currently it is not clear that this term does not include the loading of a vesicle etc.

GO:0046903 secretion
current definition: The controlled release of a substance by a cell or a tissue. 

Suggested definition: The controlled release of a substance by a cell or a tissue. The process starts when the substance to be released is localised at the release site and ends when the substance leaves the cell or tissue.

Possibly add the note: loading of the substance within a secretory vesicle is not included in the secretory process as this is covered by the process of  GO:0035459 vesicle cargo loading.

Also possibly add this clarification to some of the child terms.
eg:
 GO:0032940 secretion by cell
Suggested definition: The controlled release of a substance by a cell. The process starts when the substance to be released is localised at the release site and ends when the substance leaves the cell.

If people feel that the definition of secretion should include earlier processes then it would be helpful to have some new child GO terms associated with this term to clarify this, as well as changes to the definition.

Thanks

Ruth

**Comment by pgaudet** [comment]
HI @RLovering 

I like your suggestion. Many signaling proteins are annotated to 'secretion', while I think it would be more accurate to annotate them to 'regulation of secretion'. Specifying the beginning would be very useful here. 

Thanks, Pascale

**Comment by ukemi** [comment]
I don't think this was moved over to the ontology tracker. Do we really want to restrict to this view? When I learned about this in the dark ages, protein secretion was always described from the ER onwards and ended with the fusion of the secretory granule with the plasma membrane.  If I recall correctly there was constitutive secretion and regulated secretion. You should look to see how this has been handled in the synaptic transmission part of the graph. There is also secretion of molecules other than proteins that I think should be considered another class, for example hisamines by mast cells.

**Comment by RLovering** [comment]
Hi David

I completely agree with you, however, when I looked at the child terms for cell secretion it seemed that there were no child terms describing the earlier phases of secretion and the vesicle transport domain of GO seems to cover most of the intracellular processes that occur before exocytosis. Although this doesn't cover intracellular secretion pathways that occur without vesicles.

I have put the comments from this ticket in an old ticket https://github.com/geneontology/go-ontology/issues/16471 

I'm not sure what aspect of synaptic transmission you are referring to the secretion terms still seem to be very exocytosis focused, but the term  GO:0099504 synaptic vesicle cycle does have many more steps included. Please do point me in the right direction

Thanks

Ruth

**Comment by ukemi** [comment]
I think the issue is some of those same steps occur but branch into other non-secretory pathways, so they couldn't be made rigid part_of children. This is just my guess.

I thought that perhaps you guys had done neurotransmitter secretion as part of the SynGO project.

**Comment by ukemi** [comment]
But the other aspect we need to consider is secretion at the organismal level where an organ or tissue stores something in a lumen and then pumps it out at the appropriate times.

**Comment by RLovering** [comment]
yes there was a discussion about the neurotransmitter secretion in SynGO, so David has worked on that aspect but the secretion again seems to be focused on exocytosis

**Comment by pgaudet** [comment]
@RLovering Should this issue be moved to the ontology tracker ?
