### ISSUE TITLE
PANTHER:PTN000205060 (translation/repair)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2744]
rps3 | 40S ribosomal protein S3 (predicted) |   | DNA repair |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0002622PANTHER:PTN000205060 | 30s/40s ribosomal protein s3 pthr11760 | protein |   | PMID:21873635 | 20190819

evidence for this ribosomal protein in repair seems to be based on a single 1996  fly publication.

I think I queried this before, so I will see if I can locate the outcome.

http://flybase.org/reports/FBrf0087792.html

(I'd expect to see at least some subsequent  follow-up papers or confirmation in another species in 20 years if this is correct)

**Comment by ValWood** [comment]
There are a few in vitro publications

There are quite a few papers

https://www.uniprot.org/citations/7775413

https://www.uniprot.org/citations/15707971

http://amigo.geneontology.org/amigo/reference/PMID:18973764

To me these don't seem to provide any evidence for a physiological role in repair.
I can see that the annotations should stay, but maybe should not be transferred without better evidence?

**Comment by marcfeuermann** [comment]
Based on the evidences I do not think that this term is wrongly propagated. Anyway, as the physiological relevance can be discussed I can remove the propagation.
