### ISSUE TITLE
rna binding protein pthr24012  and PANTHER:PTN002769004 (spo5) membrane org/mRNA met

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2745]
In fission yeast this  protein (spo5)  is a meiosis-specific RNA binding protein, and probably involved in meiosis-specific regulation. However, it isn't part of the spliceosome and alternative splicing is not detected in fission yeast.

spo5 | meiotic RNA-binding protein 1 |   | mRNA splice site selection |   | GO_Central | Schizosaccharomyces pombe | IBA | MGI:MGI:1338822MGI:MGI:1342295 more... | rna binding protein pthr24012 | protein |   | PMID:21873635 | 20180411

  | spo5 | meiotic RNA-binding protein 1 |   | regulation of alternative mRNA splicing, via spliceosome |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0000114PANTHER:PTN002769004 more... | rna binding protein pthr24012 | protein |   | PMID:21873635 | 20180411

**Comment by pgaudet** [comment]
Fixed
