### ISSUE TITLE
PANTHER:PTN000296326  (Sda1) ribosome biogenesis/cytoskeleton organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2748]
sda1 is shown to . be involved in ribosome biogenesis
https://www.yeastgenome.org/reference/S000076463 PMID: 15107621

this is an earlier paper by the same group.

sda1 | SDA1 family protein (predicted) |   | actin cytoskeleton organization |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000296326SGD:S000003477 | hsda/sda1-related pthr12730 | protein |   | PMID:21873635 | 20170228

from
Buscemi G, et al. (2000) PMID:10704371

The later paper PMID: 15107621 does not refer to this "actin cytoskeleton phenotype" at all (or even refer to this paper)

I don't think this annotation should be transferred by PAINT.  @srengel  it should possibly be deleted, or moved to phenotype annotation?

**Comment by srengel** [comment]
Hi @ValWood yes i think this paper needs a redo on curation.  will try to get to it in the next week or so...

**Comment by pgaudet** [comment]
I removed all PAINT annotations for now.

**Comment by srengel** [comment]
@ValWood i removed the actin cytoskeleton GO annotation from SDA1.

**Comment by ValWood** [comment]
thanks, closing!
