### ISSUE TITLE
PANTHER:PTN000996416 glycophagy in yeast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2751]
atg11 | autophagy associated protein Atg11 |   | glycophagy |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0037363 PANTHER:PTN000996416 | cgthba protein -14 gene protein pthr13222 | protein |   | PMID:21873635 | 20170228

I can't find any evidence for the process of glycophagy in yeast. It seems to be an adaptation in animal muscle cells

**Comment by marcfeuermann** [comment]
Glycophagy term restricted to PTN000996418
