### ISSUE TITLE
PANTHER:PTN002776372 .  (mitochondrion organization/mRNA metabolic process)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2752]
pombe irc3 is a mitochondrial DNA helicase, not involved in splicing.

The ortholog is  SGD:S000002740 irc3 so this may be a family problem,  or just transferring annotation too widely

  | irc3 | mitochondrial DNA branch migration helicase Irc3 (predicted) |   | mRNA splicing, via spliceosome |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN002776372 SGD:S000002242 more... | rna helicase pthr24031 | protein |   | PMID:21873635 | 20190430

**Comment by pgaudet** [comment]
Moved the annotation to a different ancestral node to exclude this node.
