### ISSUE TITLE
PTHR19375 - PANTHER:PTN002500132  PANTHER:PTN002321897 (vmt/translation)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2754]
This particular  heat shock family molecular chaperone appears to be  ribosome associated and involved in de novo protein folding

See yeast SSB1 & 2
https://www.yeastgenome.org/locus/YDL229W
and
https://www.yeastgenome.org/locus/YNL209W

I don't think the following look right for yeast?

1 vesicle-mediated transport

sks2	heat shock protein, ribosome associated molecular chaperone Sks2		**vesicle-mediated transport**		GO_Central	Schizosaccharomyces pombe	IBA	FB:FBgn0266599
PANTHER:PTN002500132	heat shock protein 70kda pthr19375	protein		PMID:21873635	20170831

2. I probably would not transfer any "response to" annotations

	sks2	heat shock protein, ribosome associated molecular chaperone Sks2		**cellular response to unfolded protein**		GO_Central	Schizosaccharomyces pombe	IBA	MGI:MGI:95835
PANTHER:PTN002321897 	heat shock protein 70kda pthr19375	protein		PMID:21873635	20170831

	sks2	heat shock protein, ribosome associated molecular chaperone Sks2		response to unfolded protein		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN002321897
RGD:1593284 	heat shock protein 70kda pthr19375	protein		PMID:21873635	20170831

**Comment by ValWood** [comment]
I'm not quite sure about the family assignment.
I think that pombe sks2 is
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR19375:SF410

It's  difficvult to assign families to the hsps

**Comment by ValWood** [comment]
ssa1 | heat shock protein Ssa1 (predicted) |   | vesicle-mediated transport |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0266599PANTHER:PTN002500132 | heat shock protein 70kda pthr19375 | protein |   | PMID:21873635 | 20170831
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by marcfeuermann** [comment]
This is a huge and complex family. Annotation has been reviewed. I've restricted the vesicle-mediated transport term and removed propagation of "response to" terms. I've also extended annotation to the new prokaryotic branch that appeared in the latest PANTHER version.
