### ISSUE TITLE
PTHR28533- PANTHER:PTN002003922 (intersect protein/ lipid catabolism)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2757]
pbn1 ([SPCC1919.02](https://www.pombase.org/gene/SPCC1919.02) is
pig-X, glycosylphosphatidylinositol-mannosyltransferase I complex subunit 
so this is an readout, I believe:

these are 
pbn1 | pig-X, glycosylphosphatidylinositol-mannosyltransferase I complex subunit (predicted) |   | ubiquitin-dependent ERAD pathway |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN002003922SGD:S000000557 | family not named pthr28533 | protein |   | PMID:21873635 | 2017022

pbn1 | pig-X, glycosylphosphatidylinositol-mannosyltransferase I complex subunit (predicted) |   | protein processing |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN002003922 SGD:S000000557 | family not named pthr28533 | protein |   | PMID:21873635 | 20170228

**Comment by ValWood** [comment]
PMID: 16418276
Depletion of Pbn1p does not affect exit of proprotease A or procarboxypeptidase Y from the ER, indicating that Pbn1p is not required for global exit from the ER. Depleting Pbn1p leads to a significant increase in the unfolded protein response pathway

but isn't this just a phenotype of defects in correct GPI anchor biosynthesis?

@srengel

**Comment by srengel** [comment]
Hi @ValWood i will look at this (and one from last week?) after the SGD grant is turned in in 2 weeks.  i hope this can sit till then.  please advise if not.

**Comment by ValWood** [comment]
no hurry!

**Comment by pgaudet** [comment]
@ValWood Which annotation are you disputing ?

**Comment by ValWood** [comment]
I would just say
[GPI anchor biosynthetic process](http://amigo.geneontology.org/amigo/term/GO:0006506)

**Comment by pgaudet** [comment]
Fixed, thanks
