### ISSUE TITLE
cobalamin biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2761]
UniProtKB:Q9Y4U1 | MMACHC | involved_in | GO:0009236    cobalamin biosynthetic process | ECO:0000318   IBA | PMID:21873635 | PANTHER:PTN001585018 more... | 9606 Homo sapiens | GO_Central

(this  annotation was in QuickGO, but I do not see it in AmiGO?)

Eukaryotes don't make vitamin B12 as far as I'm aware?

**Comment by marcfeuermann** [comment]
Good point. Indeed most eukaryotes do not produce cobalamin. I've removed propagation of GO:0009236. The enzyme seems however to be involved in tailoring of alkylcobalamins entering from the circulation to produce the active cofactor forms. So I've kept the term "cobalamin metabolic process"
