### ISSUE TITLE
PANTHER:PTN000327451 .  BCP1 family

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2762]
I believe the following annotation are indirect (if they apply to yeast at all)

SPCC613.08	CDK regulator, involved in ribosome export (predicted)		
**cellular response to DNA damage stimulus**		GO_Central	Schizosaccharomyces pombe	IBA	**MGI:MGI:1913415**
PANTHER:PTN000327451	brca2 and cdkn1a interacting protein pthr13261	protein		PMID:21873635	20180425

SPCC613.08	CDK regulator, involved in ribosome export (predicted)		
**regulation of cyclin-dependent protein serine/threonine kinase activity**		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000327451
**UniProtKB:Q9P287**	brca2 and cdkn1a interacting protein pthr13261	protein		PMID:21873635	20180425

SPCC613.08	CDK regulator, involved in ribosome export (predicted)		
**establishment of mitotic spindle orientation**		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000327451
**UniProtKB:Q9P287**	brca2 and cdkn1a interacting protein pthr13261	protein		PMID:21873635	20180425

SPCC613.08	CDK regulator, involved in ribosome export (predicted)		
**microtubule anchoring**		GO_Central	Schizosaccharomyces pombe	IBA	**MGI:MGI:1913415**
PANTHER:PTN000327451
**UniProtKB:Q9P287**	brca2 and cdkn1a interacting protein pthr13261	protein		PMID:21873635	20180425

SPCC613.08	CDK regulator, involved in ribosome export (predicted)		
**mitotic spindle organization**		GO_Central	Schizosaccharomyces pombe	IBA	**MGI:MGI:1913415**
PANTHER:PTN000327451
**UniProtKB:Q9P287**	brca2 and cdkn1a interacting protein pthr13261	protein		PMID:21873635	20180425

SPCC613.08	CDK regulator, involved in ribosome export (predicted)		
**mitotic spindle assembly**		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000327451
**UniProtKB:Q9P287**	brca2 and cdkn1a interacting protein pthr13261	protein		PMID:21873635	20180425

**Comment by ValWood** [comment]
There is  very little published on  Bcp1 family but here is a fairy recent (uncurated) paper from yeast (cerevisiae)

J Biol Chem. 2017 Jan 13;292(2):585-596. doi: 10.1074/jbc.M116.747634. Epub 2016 Dec 2.
Bcp1 Is the Nuclear Chaperone of Rpl23 in Saccharomyces cerevisiae.
Ting YH1, Lu TJ1, Johnson AW2, Shie JT1, Chen BR1, Kumar S S1,3, Lo KY4.
Author information
Abstract
Eukaryotic ribosomes are composed of rRNAs and ribosomal proteins. Ribosomal proteins are translated in the cytoplasm and imported into the nucleus for assembly with the rRNAs. It has been shown that chaperones or karyopherins responsible for import can maintain the stability of ribosomal proteins by neutralizing unfavorable positive charges and thus facilitate their transports. Among 79 ribosomal proteins in yeast, only a few are identified with specific chaperones. Besides the classic role in maintaining protein stability, chaperones have additional roles in transport, chaperoning the assembly site, and dissociation of ribosomal proteins from karyopherins. Bcp1 has been shown to be necessary for the export of Mss4, a phosphatidylinositol 4-phosphate 5-kinase, and required for ribosome biogenesis. However, its specific function in ribosome biogenesis has not been described. Here, we show that Bcp1 dissociates Rpl23 from the karyopherins and associates with Rpl23 afterward. Loss of Bcp1 causes instability of Rpl23 and deficiency of 60S subunits. In summary, Bcp1 is a novel 60S biogenesis factor via chaperoning Rpl23 in the nucleus.


So it seems to be a nuclear export chaperone.

(note that I am updating the fission yeast product today)

**Comment by ValWood** [comment]
This is also a fairly recent paper,
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5561484/pdf/onc201792a.pdf
I'm going to ask an expert about this.

**Comment by ValWood** [comment]
Feedback from spindle assembly expert who has published over 50 papers on this, is that this is likely to be indirect due to the role in nuclear export.
It  would probably better not to transfer this to yeast for now.

**Comment by marcfeuermann** [comment]
This one has been corrected a while ago. I've forgot to close it.
