### ISSUE TITLE
PANTHER:PTN000952612 / protein import into peroxisome matrix

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2763]
afg1 | AFG1 family mitochondrial ATPase/chaperone Afg1 (predicted) |   | protein import into peroxisome matrix |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000952612SGD:S000000778 | atpase n2b pthr12169 | protein |   | PMID:21873635 | 20170616

protein import into peroxisome matrix 
is now removed from SGD 

Do the  IBA annotations get removed automagically?

**Comment by marcfeuermann** [comment]
The annotations should indeed get removed automatically, but as this process seems to take a while, I've removed the propagation manually.

**Comment by pgaudet** [comment]
@marcfeuermann it's safer to remove manually, so they will not come back should another error be introduced in the primary annotations. 

Thanks, Pascale
