### ISSUE TITLE
PANTHER:PTN001272048 septin ring assembly 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2764]
ice2 | ER membrane protein involved triglyceride mobilization ICE2 family |   | septin ring assembly |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001272048 SGD:S000001352 | family not named pthr31726 | protein |   | PMID:21873635 | 20170228

septin ring assembly appears to be indirect.

Publication title is
Reference: Loewen CJ, et al. (2007) Inheritance of cortical ER in yeast is required for normal septin organization. J Cell Biol 179(3):467-83

so  endoplasmic reticulum inheritance is upstream of septin assembly

(endoplasmic reticulum inheritance my be indirect too, as this seems to be involved in triglyceride mobilization, but IO won't address that here)

**Comment by ValWood** [comment]
affects only yeast

**Comment by pgaudet** [comment]
Fixed
