### ISSUE TITLE
PTHR23003 - PANTHER:PTN001493199 PANTHER:PTN001124003 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2765]
I don't think these are correct. The annotations are not transferred from the  orthologs oif hrb1 and some are from  other pombe RNA binding proteins.
I will try to dig out some evidence but I carefully annotated all of the mRNA and nuclear surveillance relatively recently so I doubt that this is right.

- [ ] hrb1 | RNA-binding protein involved in export of mRNAs Hrb1 (predicted) |   | **regulation of mRNA stability involved in response to oxidative stress** |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001493199 PomBase:SPAC12G12.03PomBase:SPBC16A3.18 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828

(this one is definitely wrong. These pombe proteins are associated with  the post release spliceosome). Note that there are a bunch of closely related RNAs in fission yeast with different roles including splicing, export and telomere binding)

- [ ]   | hrb1 | RNA-binding protein involved in export of mRNAs Hrb1 (predicted) |   | **nuclear mRNA surveillance** |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001124003 SGD:S000000517 SGD:S000004949 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828

- [x]    | hrb1 | RNA-binding protein involved in export of mRNAs Hrb1 (predicted) |   | **poly(A)+ mRNA export from nucleus** |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001124003 SGD:S000000517 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828

This one is OK

**Comment by ValWood** [comment]
At SGD Hrb1 is  described as
Poly(A+) RNA-binding protein; key surveillance factor for the selective export of spliced mRNAs from the nucleus to the cytoplasm;

but it is annotated to
nuclear mRNA surveillance GO:0071028
The set of processes involved in identifying and degrading defective or aberrant mRNAs within the nucleus.

I'm not totally sure but I think these are different things?

**Comment by ValWood** [comment]
Here is a n ice summary
https://www.researchgate.net/publication/255789061_MRNA_quality_control_pathways_in_Saccharomyces_cerevisiae

<img width="993" alt="Screenshot 2020-01-14 at 13 55 33" src="https://user-images.githubusercontent.com/7359272/72350120-b1f85f80-36d5-11ea-876a-0970bc0e64d3.png">


so it seems like  surveillance->degradation OR export

**Comment by ValWood** [comment]
If I understood this correctly:

Nature. 2016 Dec 22;540(7634):593-596. doi: 10.1038/nature20572. Epub 2016 Dec 12.
mRNA quality control is bypassed for immediate export of stress-responsive transcripts.
Zander G1, Hackmann A1, Bender L1, Becker D1, Lingner T2, Salinas G2, Krebber H1.
Author information
Abstract
Cells grow well only in a narrow range of physiological conditions. Surviving extreme conditions requires the instantaneous expression of chaperones that help to overcome stressful situations. To ensure the preferential synthesis of these heat-shock proteins, cells inhibit transcription, pre-mRNA processing and nuclear export of non-heat-shock transcripts, while stress-specific mRNAs are exclusively exported and translated. How cells manage the selective retention of regular transcripts and the simultaneous rapid export of heat-shock mRNAs is largely unknown. In Saccharomyces cerevisiae, the shuttling RNA adaptor proteins Npl3, Gbp2, Hrb1 and Nab2 are loaded co-transcriptionally onto growing pre-mRNAs. For nuclear export, they recruit the export-receptor heterodimer Mex67-Mtr2 (TAP-p15 in humans). Here we show that cellular stress induces the dissociation of Mex67 and its adaptor proteins from regular mRNAs to prevent general mRNA export. At the same time, heat-shock mRNAs are rapidly exported in association with Mex67, without the need for adapters. The immediate co-transcriptional loading of Mex67 onto heat-shock mRNAs involves Hsf1, a heat-shock transcription factor that binds to heat-shock-promoter elements in stress-responsive genes. An important difference between the export modes is that adaptor-protein-bound mRNAs undergo quality control, whereas stress-specific transcripts do not. In fact, regular mRNAs are converted into uncontrolled stress-responsive transcripts if expressed under the control of a heat-shock promoter, suggesting that whether an mRNA undergoes quality control is encrypted therein. Under normal conditions, Mex67 adaptor proteins are recruited for RNA surveillance, with only quality-controlled mRNAs allowed to associate with Mex67 and leave the nucleus. Thus, at the cost of error-free mRNA formation, heat-shock mRNAs are exported and translated without delay, allowing cells to survive extreme situations.

then hrb1 and the paralog  bypass surveillance and  are involved in the export of stress responsive genes?

**Comment by ValWood** [comment]
Similarly these should be removed from cip1 and cip2 (these are cytoplasmic)


- [ ] 
cip1 | RNA-binding protein Cip1 |   | nuclear mRNA surveillance |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001124003SGD:S000000517SGD:S000004949 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828

- [ ] 
cip1 | RNA-binding protein Cip1 |   | poly(A)+ mRNA export from nucleus |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001124003SGD:S000000517 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --





cip1 | RNA-binding protein Cip1 |   | nuclear mRNA surveillance |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001124003SGD:S000000517SGD:S000004949 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
- [ ] cip2 | RNA-binding protein Cip2 |   | nuclear mRNA surveillance |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001124003SGD:S000000517SGD:S000004949 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828

- [ ]   | cip2 | RNA-binding protein Cip2 |   | poly(A)+ mRNA export from nucleus |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001124003SGD:S000000517 | rna recognition motif rrm domain containing protein pthr23003 | protein |   | PMID:21873635 | 20170828

**Comment by pgaudet** [comment]
hrb1 has no more annotations in PAINT 

However they are still in AmiGO, see http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC328.05


@dustine32 we had this issue before, of annotations from 2017 always coming back, or never getting removed, even after we remove them. Can you please check?

**Comment by pgaudet** [comment]
Annotations are gone - this is a pipeline issue
