### ISSUE TITLE
PTN000306732 is not catalytic SU of gamma secretase - PTHR12889

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2766]
GAMMA-SECRETASE SUBUNIT APH-1 (PTHR12889) does not have endopeptidase activity.

I have disputed the annotations to FBgn0031458|UniProtKB:Q9VQG2 via P2GO.

@hdrabkin could you look at these mouse ones that are being used in propagation from PAINT?

PTN000306751
(MOUSE|MGI=MGI=1915568|UniProtKB=Q9DCZ9)
PTN000306752
(MOUSE|MGI=MGI=3522097|UniProtKB=Q8C7N7)
PTN000306775
(MOUSE|MGI=MGI=2385110|UniProtKB=Q8BVF7)

**Comment by hattrill** [comment]
tagging @phanivg as might be relevant in review of hydrolases.

**Comment by sjm41** [comment]
I just ran into this issue myself....
@hattrill  - I didn't see any dispute on the fly annotation (Q9VQG2), so I just added one myself in protein2GO.
@hdrabkin - looking at the source papers for the mouse annotations (PMID:15634781, PMID:17913918), I don't see evidence for the specific annotations to the Aph1 isoforms so I think they should be removed. (Presenilin is the catalytic subunit of the gamma secretase complex - see GO:0070765.)

**Comment by hdrabkin** [comment]
I could add contributes_to to these; They are IGI; the complex annotation is present for the genes.

**Comment by sjm41** [comment]
Current rules say not to annotate non-catalytic subunits of a complex with catalytic activity terms, even with 'contributes to', so I think these annotations should either be removed or changed to an 'enzyme regulator activity' MF term (if there's evidence for that). Right @hattrill ?

**Comment by hattrill** [comment]
Yes, that's correct.

**Comment by ukemi** [comment]
OK. I removed them all including the contributes_to.

**Comment by sjm41** [comment]
Thank @ukemi .  @pgaudet - happy to leave this one closed, or do you want to edit the PAINT node directly now?

**Comment by pgaudet** [comment]
yes I'd like to fix the family, this way if the annotation re-appears one way or another, it won't be automatically restored.

**Comment by pgaudet** [comment]
I changed the annotation to GO:0030674 | protein-macromolecule adaptor activity.
