### ISSUE TITLE
IPR025799 GO terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2769]
Protein arginine N-methyltransferase (IPR025799)

This currently has the GO terms:
- BP: Protein methylation (GO:0006479)
- MF: Methyltransferase activity (GO:0008168)

Minimally, would be good to change the MF term to this (to match the BP):
- protein methyltransferase activity (GO:0008276)

But from the InterPro term name and description, consider changing both to more specific:
- BP: peptidyl-arginine methylation (GO:0018216)
- MF: protein-arginine N-methyltransferase activity (GO:0016274)

**Comment by typhainepl** [comment]
I have updated the GO terms in the InterPro entry. The changes will be visible in InterPro 78.0

**Comment by sjm41** [comment]
Thanks!
