### ISSUE TITLE
SPT16 not cohesin complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2770]
from
https://www.yeastgenome.org/reference/S000249183
Cohesin is a regulator of genome architecture with roles in sister chromatid cohesion and chromosome compaction. The recruitment and mobility of cohesin complexes on DNA is restricted by nucleosomes. Here, we show that the role of cohesin in chromosome organization requires the histone chaperone FACT ('facilitates chromatin transcription') in Saccharomyces cerevisiae. We find that **FACT interacts directly with cohesin,**

But the FACT complex subunit  SPT16 has been annotated to "cohesin complex'

part of | cohesin complex |   | IDA | SGD | 2019-10-18 | Garcia-Luis J, et al. (2019) PMID:31582854

**Comment by ValWood** [comment]
Hi @srengel  I raised a dispute for this one so the originating curator should get this.
cheers
v

**Comment by srengel** [comment]
thanks @ValWood i'm passing this to @jpa29  this morning

**Comment by jpa29** [comment]
Hi Val, Thanks for pointing this out. Spt16 was shown to physically bind  to the Cohesin complex.  Is there a better term to describe this? Like Cohesin complex binding?  I agree it looks confusing with the GO term cohesin complex. I can remove this. 
"We found that some chromatin remodelers were highly enriched in our pulldowns (Table 1). The most abundant was the Spt16 subunit of the FACT complex (Table 1). "

**Comment by srengel** [comment]
protein-complex binding has_input cohesin complex.

**Comment by jpa29** [comment]
Thank you! I did this change in Noctua :Yeast SPT16 gomodel:5df932e000000652. I deleted the Protein2 GO annotation. I was using Safari and the browser did not display the has_input row.

**Comment by ValWood** [comment]
fixed
