### ISSUE TITLE
 protein polymerization annotations for proteins that polymerize

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2772]
Mucin is_a polymer but it isn't involved in polymerization?

~UniProtKB:F1NBL0 | MUC6 | involved_in | GO:0051258    protein polymerization | ECO:0000314   IDA | PMID:2327958 |   | 9031 Gallus gallus | AgBase~

This has gone

**Comment by ValWood** [comment]
Lots of annotations to  'priotein polymerization" for bacterial tubulin ftsz from unirule

e.g.


UniProtKB:A0A009FST0 | ftsZ | involved_in | GO:0051258    protein polymerization | ECO:0000256   IEA | GO_REF:0000104 | UniRule:UR000100343 | 1310605 Acinetobacter baumannii 348935 | UniProt


but if this is like eukaryotic tubulin it  'self-organizes' into polymers. I think this term is for use only to describe processes like actin and tubulin nucleation machinery?

**Comment by pgaudet** [comment]
Deleted the AgBase annotation

I am tagging @pedruzzi for the UniRule annotations. 

Thanks, Pascale

**Comment by ValWood** [comment]
CLosing this. It isn't terrible for tubulin etc to be annotate to polymerization.  These can be tackled when this area of GO is better.
