### ISSUE TITLE
Review annotations to GO:0001134 transcription regulator recruiting activity and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2774]
Hello, 

We plan to obsolete GO:0001134 transcription regulator recruiting activity and children and children (see https://github.com/geneontology/go-ontology/issues/18561

Please review your annotations. In most cases the annotations to another 'transcription regulator term' should be sufficient to capture the information, but people may want to also annotate to '    GO:0030674  protein binding, bridging'. 

Googe doc: 
https://docs.google.com/spreadsheets/d/12wRHYEut8yihcVEJG6ag_1FrZxbxz0VDO6BiLwM5xPk/edit#gid=0

Impacted groups: 

Group | Number of annotations
--|--
CAFA | 2
dictyBase | 2
MGI | 1
PomBase | 1
SGD | 37
UniProt | 1

Thanks, Pascale

**Comment by pfey03** [comment]
I've taken care of the two Dicty ISS annotations

**Comment by hdrabkin** [comment]
done

**Comment by pgarmiri** [comment]
Hi, The 2 CAFA annotations have been revised. The UniProt one is SWIS and I have marked it as such in the google doc.
Thanks,
Penelope

**Comment by pgaudet** [comment]
@suzialeksander @ValWood 
Will you be able to look into this before next week ? 

Thanks, Pascale

**Comment by suzialeksander** [comment]
yes, that should work @pgaudet

**Comment by ValWood** [comment]
I used this to annotate fission yeast teb1.
So everything else has something more specific than "transcription regulator" describing the type of regulator. So it seems a bit sub-optimal not to be able to describe "recruitment" generally. (I think "protein binding, bridging " is not as specific as "recruitment"). 

I can change it , but longer term I still think we need a way to describe this.

Here is my issue:
All of the other transcription regulator activities are described by a single term. To describe 
tel1 recruiting ams2 I need to use 2 terms (one of which is only under protein binding)  i) transcription regulator activity and ii) protein binding bridging.

I would prefer something more specific than "transcription regulator activity"

**Comment by ValWood** [comment]
Hang on, I can use

GO:0001134    transcription regulator recruiting activity

that will stay right?

**Comment by pgaudet** [comment]
No, that's the one we were planning to delete. 

How would you define "recruitment" ? Right now it describes the order of binding of the different subunits - is that really a function ? 

"The function of binding to an RNA polymerase (RNAP) transcription regulator and recruiting it to the general transcription machinery complex in order to modulate transcription initiation. "

Thanks, Pascale

**Comment by ValWood** [comment]
Possibly this example is not recruitment, so I would be happy for now to remove this MF.
 
I think "molecular adaptor"  would work OK for recruitment.
I did not realise "protein binding, bridging" was a child of this term.

I think   "protein binding, bridging" would be better called an adaptor?  It is odd  right now because its parents and children are described as adaptors. I would rather the term name recognised its adaptor ancestry than it's protein binding ancestry.

I'll fix the annotation and open a ticket for the "protein binding, bridging" term name.

**Comment by pgaudet** [comment]
I cannot exactly remember why the label of this term is still "protein binding, bridging". 

The only relevant comment I find is #16721 
that states that 'protein binding, bridging' is not limited to protein-protein interactions (it also includes protein-lipid, for example). It may be worth it to have more specific terms, such as 'protein-protein adaptor activity' (which is now a narrow synonym of  'protein binding, bridging' ), and protin-lipid adaptor activity, for example. What do you think ?

**Comment by ValWood** [comment]
We already have a number of more specific terms (see above).
That's partially why the current name seems odd?

**Comment by ValWood** [comment]
wrong ticket ;)

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/18655
for discussion about  "protein binding, bridging"

**Comment by ValWood** [comment]
Note that pombe teb1 also annotate to

positive regulation of transcription by transcription factor localization
which was describing the same "recruitment" activity. Presumably this "BP" should go too?

**Comment by pgaudet** [comment]
Yes, I think so

**Comment by suzialeksander** [comment]
sgd done.
