### ISSUE TITLE
Review annotations to GO:0020012 mitigation of host immune response (term label was: evasion or tolerance of host immune response) -> now merged into GO:0042783 evasion of host immune response  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2777]
Hello, 

Can you please review annotations to GO:0020012 mitigation of host immune response (term label was: evasion or tolerance of host immune response)

https://docs.google.com/spreadsheets/d/1gm9FqEo0bobjHAKiQ7wcChYXdAbbSZT3chMAO_cQTts/edit#gid=0

Group | Annotations to review
CGD | 11 
GeneDB | 2 @Achchuthan 

Annotations from other groups have already been fixed or were OK. 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Sorry for the delayed response due to my holidays. I have changed the annotation from Trypanosoma brucei gene. Uli Boehme will be able to review and update the changes from Plasmodium falciparum genes. I'll let her know.

**Comment by uliboehme** [comment]
Hi @pgaudet, the two Plasmodium genes have now been changed.

**Comment by pgaudet** [comment]
Thanks !

**Comment by pgaudet** [comment]
@marekskrzypek Can you please look at the CGD annotations ?

**Comment by marekskrzypek** [comment]
These are OK
