### ISSUE TITLE
histone modification | IEA with IPR031101

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2778]
RNA polymerase II associated Paf1 complex subunit Tpr1
Cdc73/Paf1 complex

has an Interpro mapping to 

histone modification | IEA with IPR031101

Do you have a source for that? It seems odd.

Cheers

Val

**Comment by typhainepl** [comment]
Paf1 complex plays a role in histone modification has suggested here: [http://europepmc.org/article/MED/20178742]

**Comment by ValWood** [comment]
OK thanks!
