### ISSUE TITLE
PAINT annotations to PTHR11214 (inc. PTN000130250)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2779]
**PANTHER:PTN002257246**
http://www.pantree.org/node/annotationNode.jsp?id=PTN002257246
Family: BETA-1,3-N-ACETYLGLUCOSAMINYLTRANSFERASE (PTHR11214)

In contrast to the family name, the GO-MF term annotated to this node is:
UDP-galactose:beta-N-acetylglucosamine beta-1,3-galactosyltransferase activity (GO:0008499)
which is a type of "beta-1,3-**GALACTOSYL**transferase activity".

Is the problem here simply that the PANTHER family name is misleading, or is there an issue with the Panther tree, or the associated GO terms?

Also, I don't understand why both these two distinct MF terms are both 'inherited by this node'?:
acetylgalactosaminyltransferase activity IBA
acetylglucosaminyltransferase activity IBA

(Maybe the reason is associated with my 2nd question below...)

===

**PANTHER:PTN000130250**
http://www.pantree.org/node/annotationNode.jsp?id=PTN000130250
Family:	BETA-1,3-N-ACETYLGLUCOSAMINYLTRANSFERASE (PTHR11214)

This has the same PANTHER family association as above.

Here, the 2 direct annotations to the node are:
acetylgalactosaminyltransferase activity (GO:0008376)
acetylglucosaminyltransferase activity (GO:0008375)

I understand these two activities are related, but are they both ever found in the same protein?
As things stand, both terms are getting applied to every gene in the panther family, and I'm not sure that's right.

For example, these human acetylglucosaminyltransferases are getting the 
acetylgalactosaminyltransferase activity term via PTN000130250:
B3GNT2, B3GNT3, B3GNT4, B3GNT5, B3GNT6, B3GNT7, B3GNT8, B3GNT9

And conversely, these human galactosaminyltransferases are getting the 
acetylglucosaminyltransferase activity term via PTN000130250:
B3GALT1, B3GALT2, B3GALT4, B3GALT6

**Comment by sjm41** [comment]
tagging @hattrill

**Comment by sjm41** [comment]
I've looked at this one again, trying to get my head around it.  The issue is probably best viewed from the perspective of the PTHR11214 family, like this:


The "BETA-1,3-N-ACETYLGLUCOSAMINYLTRANSFERASE (PTHR11214)" family is very large (1,766 members), including 16 human genes and 9 fly genes.

This family appears to be associated with nine different PAINT nodes:
http://www.pantree.org/tree/family.jsp?accession=PTHR11214
Together, these nodes have nine distinct glycosyltransferase (MF) terms, which appear to be being propagated in combination to some/all members of the family.

For example, 7 of the fly genes in the family are getting annotated with these 3 different activity terms:
- "UDP-galactose:beta-N-acetylglucosamine beta-1,3-galactosyltransferase activity" (from PTN002257246) 
- "acetylgalactosaminyltransferase activity" (from PTN000130250)
- "acetylglucosaminyltransferase activity" (also from PTN000130250)

Another example, fly beta3GalTII (A1Z7G9) gets annotated with these five different activity terms:
- UDP-galactosyltransferase activity (from PTN000880300)
- galactosyltransferase activity (also from PTN000880300)
- acetylgalactosaminyltransferase activity (from PTN000130250)
- acetylglucosaminyltransferase activity (also from PTN000130250)
- transferase activity, transferring hexosyl groups (from PTN000879966)

So, this over-propagation either results in multiple distinct activity terms being added to the same proteins, and/or results in redundant (parent-child type) annotation.

Not sure what needs to happen here?  Ideally, split the Panther family further and have distinct PAINT nodes for the subfamilies? Or if that's not feasible, just propagate higher level glycosyltransferase terms to all of PTHR11214?

**Comment by sjm41** [comment]
tagging @pgaudet @marcfeuermann

**Comment by sjm41** [comment]
Update (28th Oct 2020):
- PTN002257246 appears to have been deleted, which solves some of the original reported problem
- PTN000130250 is still an issue (has two different activities associated with it) - I'll take another look at this.
- PTN000880300 is fixed - now just has 'UDP-galactosyltransferase activity'
- the PTHR11214 family is now associated with (only!) seven PAINT nodes rather than the nine when first made this ticket.

The fly beta3GalTII (A1Z7G9) example (cited above) is now only annotated with one (not five) activity term via PAINT:
UDP-galactosyltransferase activity (from PTN000880300)

**Comment by sjm41** [comment]
_PTN000130250 is still an issue (has two different activities associated with it) - I'll take another look at this._

"acetylglucosaminyltransferase activity" on this node is supported by 6 independent annotations, and looks accurate.
"acetylgalactosaminyltransferase activity" on this node is supported by a single annotation, which looks like curator error (should be same term as the other 6 annotations - I've just disputed this in P2GO)

Good example of danger of propagating terms supported by single annotation perhaps?

**Comment by pgaudet** [comment]
Hi @sjm41 
This is indeed a tough one! I removed all annotations and started over. 
- Annotated   GO:0016757  transferase activity, transferring glycosyl groups  and GO:0000139 Golgi membrane to the root. 

Other annotations are to more restricted nodes. Hopefully this addresses the issues you report here. 

Thanks, Pascale
