### ISSUE TITLE
PEPTIDYL-PROLYL CIS-TRANS ISOMERASE (PTHR11071) - over-propagation to this family

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2780]
Looking at PEPTIDYL-PROLYL CIS-TRANS ISOMERASE (PTHR11071) (e.g. annotations for D.mel CG17266), there is a pretty mixed bag of annotations.

Supported by >1 annotation:
cyclosporin A binding 	PANTHER:PTN002594282
peptidyl-prolyl cis-trans isomerase activity	PANTHER:PTN002594282
unfolded protein binding	PANTHER:PTN002594282
protein refolding	PANTHER:PTN002594282

But:
ribonucleoprotein complex binding	PANTHER:PTN000870406
positive regulation of viral genome replication	PANTHER:PTN000870406
angiogenesis	PANTHER:PTN000116703

are only supported by one source and are a bit dubious (& angiogenesis is not really appropriate for flies)

Cyclophilins are associated with a variety of processes, but not all-in-one. Perhaps just stick to the core attributes.

**Comment by marcfeuermann** [comment]
This is a huge family (1185 members) and, some PAINT propagations were weird. I've totally cleaned and reannotated this family, indeed sticking to the core attributes.
