### ISSUE TITLE
IPR034997 & IPR038887 angiogenesis (GO:0001525)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2781]
IPR034997 Inner nuclear membrane protein Man1
IPR038887 Dehydrodolichyl diphosphate synthase complex subunit Nus1

are associated with the term angiogenesis (GO:0001525), which is a bit indirect and this term is really applicable for insects.

tagging @happy-lorna

**Comment by typhainepl** [comment]
Thanks for pointing this out. I've updated the InterPro entries.
