### ISSUE TITLE
IPR039016 Reversion-inducing cysteine-rich protein with Kazal motifs

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2782]
IPR039016	Reversion-inducing cysteine-rich protein with Kazal motifs

is associated with

vasculature development (GO:0001944)
regulation of canonical Wnt signaling pathway (GO:0060828)

But this is probably not conserved or appropriate to propagate to all species as Wnt signaling can be quite divergent.

**Comment by hattrill** [comment]
tagging @happy-lorna

**Comment by typhainepl** [comment]
Thanks for pointing this out. I've updated the InterPro entry.
