### ISSUE TITLE
IPR039183 Coiled-coil domain-containing protein 66

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2783]
IPR039183 Coiled-coil domain-containing protein 66

is associated with retinal rod cell development GO:0046548

but this term is under camera-type eye photoreceptor cell differentiation GO:0060219

so shouldn't be propagated to all species - and also, as it is a development term, it's not really good to propagate as direct link to process may not be conserved. 

tagging @happy-lorna

**Comment by typhainepl** [comment]
Hi,
Thanks for highlighting this. I've updated the InterPro entry, the changes will be visible in the next InterPro release (78.0).
