### ISSUE TITLE
Remove Galactosyltransferase activity (GO:0008378) from IPR002659

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2784]
Description of InterPro "Glycosyl transferase, family 31 (IPR00265)" includes:

_Glycosyltransferase family 31 (GH31) comprises enzymes with a number of known activities; N-acetyllactosaminide beta-1,3-N-acetylglucosaminyltransferase (2.4.1.149); beta-1,3-galactosyltransferase (2.4.1); fucose-specific beta-1,3-N-acetylglucosaminyltransferase (2.4.1); globotriosylceramide beta-1,3-GalNAc transferase (2.4.1.79) [2, 3]._

Which is consistent with the activities listed here: http://www.cazy.org/GT31.html

But the associated InterPro2GO term is given as "Galactosyltransferase activity (GO:0008378)", which is only true of certain members of this family. E.g. Drosophila brn (FBgn0000221, Q24157) belongs to this family but has been characterized as an acetylglucosaminyltransferase.

So please remove "Galactosyltransferase activity" from IPR002659.
Probably safe to add the higher term "transferase activity, transferring hexosyl groups" (GO:0016758), but that may be too generic to be useful?

**Comment by sjm41** [comment]
@hattrill

**Comment by hattrill** [comment]
tagging @happy-lorna

**Comment by typhainepl** [comment]
Thanks for pointing this out. I've updated the InterPro entry.

**Comment by sjm41** [comment]
Hi @typhainepl, Based on revision of #2788, IPR002659 should probably get a higher level (rather than no) MF term - 
"transferase activity, transferring hexosyl groups" (GO:0016758)

**Comment by typhainepl** [comment]
Hi @sjm41,
I have updated the InterPro entry. The changes will be visible in InterPro 83.0.

**Comment by sjm41** [comment]
Great, thanks.
