### ISSUE TITLE
Remove GO:0004579 from IPR007676

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2785]
The description of Ribophorin I (IPR007676) includes:
_Ribophorin I and OST48 are thought to be responsible for OST catalytic activity [PMID: 11443278]._

That 'thought' has proved to be incorrect, and it's now known that the STT subunit(s) have the catalytic activity within the OST complex (e.g. see Table 1 of PMID: 31810196.)

So can you remove "Dolichyl-diphosphooligosaccharide-protein glycotransferase activity (GO:0004579)" from IPR007676 please?

Thanks.

@hattrill 
@happy-lorna

**Comment by typhainepl** [comment]
Thanks for highlighting this, I've updated the InterPro entry.
