### ISSUE TITLE
Remove GO:0004579 from IPR003038

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2786]
It's now known that the STT subunit(s) have the catalytic activity within the OST complex - DAD1/Ost2 has a stabilization role (e.g. see Table 1 of PMID: 31810196.)

So can you remove "Dolichyl-diphosphooligosaccharide-protein glycotransferase activity (GO:0004579)" from IPR003038 please?

Thanks.

@hattrill
@happy-lorna

**Comment by typhainepl** [comment]
Hi,
Thanks for highlighting this, I've removed the GO term from the InterPro entry.
