### ISSUE TITLE
PANTHER:PTN001170207 propagation to non-delta-like proteins

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2787]
PANTHER:PTN001170207 is associated with negative regulation of Notch signaling pathway

but this is only valid for DLK1 (delta like non-canonical Notch ligand 1) orthologs. It's being propagted to other families like scavenger receptors and for us, NimA, FBgn0261514. Which is an immune-type receptor.

The Alliance page https://www.alliancegenome.org/gene/FB:FBgn0261514 is quite good for looking at the other families hit, using the low stringency setting for orthology.

**Comment by marcfeuermann** [comment]
The term has indeed been propagated over a duplication event. I've restricted it to the DLK1 node.
