### ISSUE TITLE
Remove GO:0008375 from Glycosyl transferase, family 14 (IPR003406)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2788]
Glycosyl transferase, family 14 (IPR003406) corresponds to CAZT GT14 family, which includes several different functional activities, not all of which are acetylglucosaminyltransferases:
http://www.cazy.org/GT14.html

E.g. some GT14 members are xylosyltransferases, as noted in the 'family relationships' section of the InterPro report.

It's therefore incorrect to associate "acetylglucosaminyltransferase activity (GO:0008375)" with 
IPR003406 - please remove.

Thanks.
@hattrill 
@happy-lorna

**Comment by typhainepl** [comment]
Thanks for highlighting this. I have removed the GO term from the InterPro entry. The changes will be visible in the next InterPro release (78.0).

**Comment by sjm41** [comment]
Thanks!

**Comment by cmungall** [comment]
I'm curious why the decision was made to remove this altogether than to go up a level to 

```
id: GO:0016757
name: transferase activity, transferring glycosyl groups
namespace: molecular_function
alt_id: GO:0016932
def: "Catalysis of the transfer of a glycosyl group from one compound (donor) to another (acceptor)." [GOC:jl, ISBN:0198506732]
subset: goslim_chembl
subset: goslim_drosophila
subset: goslim_generic
subset: goslim_yeast
synonym: "glycosyltransferase activity" EXACT []
synonym: "transferase activity, transferring other glycosyl groups" NARROW []
synonym: "transglycosidase activity" EXACT []
synonym: "transglycosylase activity" EXACT []
xref: EC:2.4
is_a: GO:0016740 ! transferase activity
```

this seems consistent with http://www.cazy.org/GT14.html

**Comment by pgaudet** [comment]
@typhainepl

**Comment by sjm41** [comment]
I agree with @cmungall - sorry, I should have suggested this at the time.
Please add GO:0016757 to IPR003406.

**Comment by typhainepl** [comment]
I have updated the InterPro entry. The changes will be visible in InterPro 83.0.

**Comment by sjm41** [comment]
Thanks.
