### ISSUE TITLE
Documentation for annotation relations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2789]
One of our collaborators was asking about GO annotation extension relations. Docs here seem very out of date:
http://wiki.geneontology.org/index.php/Annotation_Extension_Relation_Subsets

**Comment by pgaudet** [comment]
You should at least be using this page: 
http://wiki.geneontology.org/index.php/Annotation_Relations

**Comment by pgaudet** [comment]
I assume this is OK. Let us know if some parts of the documentation need work (or which part is most urgent). 

Thanks, Pascale

**Comment by ValWood** [comment]
yes, I forwarded the more recent docs.
