### ISSUE TITLE
dispute GO:0010204    defense response signaling pathway, resistance gene-independent Biological Process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2790]
EDITED: Annotation review spreadsheet is here: 
https://docs.google.com/spreadsheets/d/1fv8c9WDOxFJ0CILQNjpyCfgjy1yAj09eMCEYgqP4Zy0/edit#gid=0

----

from

https://github.com/geneontology/go-ontology/issues/18587

FMO1 is 
FMO1  PMID:16856982
we showed that the enhanced basal resistance phenotype was dependent on the accumulation of salicylic acid. FMO1-3D plants showed wild-type resistant reactions after inoculation with avirulent bacteria, indicating that the R-gene-mediated defence physiology was not compromised by FMO1 over-expression. 
We discuss the possibility that the FMO may participate in the detoxification of virulence factors produced by pathogens.

Moreover, while CDR1 and ADR1 are believed to be involved in pathogen defence signalling, FMO1 encodes an FMO. Flavin‐containing mono‐oxygenases probably occur in all life forms, as they have been detected in bacteria, fungi, plants and animals (Schlenk, 1998). Mostly studied in animal systems, they have been shown to be important for the detoxification of xenobiotica, i.e. molecules that are foreign to the organism

Q9LMA1	
FMO1
GO:0009870	 defense response signaling pathway, resistance gene-dependent
PMID:16531493	
		
and
GO:0010204	 defense response signaling pathway, resistance gene-independent
PMID:16856982	

This one is strange because it is 
FMO1 encodes an FMO. Flavin‐containing mono‐oxygenases probably occur in all life forms, as they have been detected in bacteria, fungi, plants and animals (Schlenk, 1998). Mostly studied in animal systems, they have been shown to be important for the detoxification of xenobiotica, i.e. molecules that are foreign to the organism

It does not appear to be signalling at all?

**Comment by ValWood** [comment]
These are 3 splicing complex components conserved across eukaryotes.
The evidence seems to be largely genetic suppression experiments and the conclusions also don't appear to implement in this pathway signalling.

MOS4  PMID:17575050
CDC5  PMID:17575050
PRL1  PMID:17575050
MOS4 (Modifier Of snc1, 4), AtCDC5, and PRL1 (Pleiotropic Regulatory Locus 1)--that are all essential for plant innate immunity.
Since the complex components along with their interactions are highly conserved from fission yeast to Arabidopsis and human, they may also have a yet-to-be-identified function in mammalian innate immunity.
In fission yeast, cerevisiae human and arabidopsis   these are all spicing factors, so this seems to be indirect?

This is not signalling, from the conclusion
It is reasonable to propose that the Arabidopsis MAC is orthologous to the NTC, which has been indicated to be essential for splicing (Ajuh et al. 2001), based on studies in human and yeast. Since the majority of plant genes are interrupted by noncoding introns, a defect in general splicing of mRNA would likely result in catastrophic phenotypes or death. For example, several general splicing mutants are embryo lethal, based on data in the SeedGenes database (Tzafrir et al. 2003). Since mutations in MOS4, PRL1, or AtCDC5 alone only have minor effects on the plants’ normal growth and development, it is unlikely that the protein products of these genes are essential components of splicing. However, since mos4-1 Atcdc5-1 and mos4-1 prl1-1 double-homozygous mutants seem to be lethal, MAC as a whole could be required for an essential process, such as spliceosome assembly, as suggested from studies in yeast and humans (Tarn et al. 1993; Grillari et al. 2005)
and 
……Although the functional relevance of alternative splicing in innate immunity is unknown, the association of the NTC with the spliceosome led us to hypothesize that MOS4, AtCDC5, and PRL1 may be involved in alternative splicing. We tested several alternatively spliced genes, including RPS4, AtSRp30, AtSRp34, U1snRNP, ANP1, and POT1, for relative levels of transcript variants of each in the mos4-1, Atcdc5-1, and prl1-1 mutants by real-time RT–PCR. In all cases, there were no significant differences in transcript variant levels between wild type and the mos4-1, Atcdc5, and prl1 mutants (Fig. 7). Our data suggest that MOS4, AtCDC5, and PRL1, while possibly associated with a spliceosome complex, are individually not involved in general or alternative RNA splicing. We cannot discount the possibility that the intact MAC complex is required for spliceosome assembly as the NTC is in yeast, or that the individual members regulate the splicing of an unknown RNA species.

https://www.uniprot.org/uniprot/Q42384
cwf15
cdc5

For this one, if you approve the changes, this date seems to be transferred into keywords. There are a few other spurious mappings on these proteins. I can look at these afterwards.
(not to self, also an Interpro DNA binding, possibly from Myb)

**Comment by ValWood** [comment]
GLO5  PMID:22286136 
GLO3	PMID:22286136
Peroxisomal (S)-2-hydroxy-acid oxidase GLO5
this seems way downstream of the signalling pathway? HO from the retain activates:
“Here we show that GOX is an alternative source for the production of H(2)O(2) during both gene-for-gene and nonhost resistance responses”

AFFECTS 
Glycolate oxidase modulates reactive oxygen species-mediated signal transduction during nonhost resistance in Nicotiana benthamiana and Arabidopsis.

**Comment by ValWood** [comment]
ERD2B PMID:19717464
UGGT  PMID:19717464
CRT3 PMID:19717464
To gain insights into the molecular mechanisms underlying PTI, we investigated EFR-mediated PTI using genetics. 
A forward-genetic screen for Arabidopsis elf18-insensitive (elfin) mutants revealed multiple alleles of calreticulin3 (CRT3), UDP-glucose glycoprotein glucosyl transferase (UGGT), and an HDEL receptor family member (ERD2b), potentially involved in endoplasmic reticulum quality control (ER-QC). 

This is about PTI but it’s  very indirect as it is about ER to Golgi transport of the receptor

**Comment by pgaudet** [comment]
@ValWood @tberardini 
I have created a spreadsheet: 
https://docs.google.com/spreadsheets/d/1fv8c9WDOxFJ0CILQNjpyCfgjy1yAj09eMCEYgqP4Zy0/edit#gid=0

@ValWood For  PMID:22286136 do you suggest we create 'reactive oxygen species-mediated signaling pathway'? 

Thanks, Pascale

**Comment by ValWood** [comment]
http://amigo.geneontology.org/amigo/reference/PMID:9670562

I don't see any experiments in this paper, it's just a correlation between  PCR products and previously known markers.

Between markersDFR and ve027/nga129, eight disease resistance loci have been located; theHRTgene which is required for resistance to turnip crinkle virus (Dempseyet al., 1997), RPS4whichis involved in the specific recognition of aP. syringaeisolate (Kunkel, 1996),TTR1which confers tolerance to infection by tobacco ringspot virus (TRSV) (Kunkel, 1996),andRPP8, RPP21, RPP22, RPP23, and RPP24which areinvolved in the specific recognition ofP. parasiticaisolatesEmoy2andEmco5, Madi1, Aswa1, Gowa1 and Edco1,respectively (Holubet al., 1994; Holub, 1997). pNd2 also showed homology with CIC clones that have been mapped to positions on chromosome 4 and 5, which are so far not correlated to resistance gene loci.

Should not be used for
defense response to fungus, incompatible interaction
OR
response to fungus

**Comment by ValWood** [comment]
> @ValWood For PMID:22286136 do you suggest we create 'reactive oxygen species-mediated signaling pathway'?

 The  MF is known here so
GO:0003973   (S)-2-hydroxy-acid oxidase activity
Catalysis of the reaction: (S)-2-hydroxy-acid + O2 = 2-oxo acid + hydrogen peroxide.

part of
GO:0002758    innate immune response-activating signal transduction

 might do until the connections are known?

**Comment by pgaudet** [comment]
Looks like ROS signaling could be a BP (although there seem to be several types): 
https://www.sciencedirect.com/science/article/pii/S235240731930006X

**Comment by ValWood** [comment]
Yup. In this context they are signalling molecules so that might be the best way...

**Comment by tberardini** [comment]
@ebakker2 Can you please review the TAIR annotations in the linked spreadsheet?  @ValWood has done some review already and her notes are in the Suggested action field.

**Comment by ValWood** [comment]
@ebakker2  I didn't read the papers in detail, just skimmed for the relevant pathways data so new terms or refinements might be required.

**Comment by ValWood** [comment]
Another term used  to describe the HO production is

GO:0002679    JSON
respiratory burst involved in defense response
Biological Process

Definition (GO:0002679 GONUTS page)
A phase of elevated metabolic activity, during which oxygen consumption increases made as part of a defense response ; this leads to the production, by an NADH dependent system, of hydrogen peroxide (H2O2), superoxide anions and hydroxyl radicals. PMID:12789499

**Comment by ValWood** [comment]
Hello,
You should wait until
https://github.com/geneontology/go-ontology/issues/18588
is done before reannotating the PRR signalling terms
This will give you a term under "immune signalling"

**Comment by pgaudet** [comment]
BTW geneontology/go-ontology#18588 is done

**Comment by pgaudet** [comment]
Thanks!
