### ISSUE TITLE
Review annotations based on similarity to RNA binding/transport

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#2791]
eg human SIDT1 has phylogenetic-based annotation to 
double-stranded RNA binding
RNA transport

and interpro mapping
RNA transmembrane transporter activity
dsRNA transport

but according to a recent nature scientific report
https://www.nature.com/articles/s41598-017-07077-z

In the present study, we have cloned human SIDT1 and SIDT2 and produced fusion proteins to the green fluorescent protein (GFP). Using a wide variety of methods, we show evidence strongly suggesting that SIDT1 and SIDT2 are involved in cellular cholesterol transport in mammalian cells....

...All the evidence gathered in the present study indicates that SIDT1 and SIDT2 are members of a novel family of proteins involved in the uptake and intracellular cholesterol transport in mammals.

...Previous studies have identified SIDT1 and SIDT2 as homologues of the C. elegans SID1 protein, which is involved in the transport of double-stranded RNA (dsRNA) in the nematode32, 33. One of such studies showed the transport of dsRNA in PANC-1 cells overexpressing SIDT1. Databases have both genes annotated as dsRNA transporters (NCBI, SIDT1 Gene ID:54847 and SIDT2 Gene ID: 51092). We have shown previously that both SIDT1 and SIDT2 shared a higher identity with ChUP-1 than with SID1 (31) (Supplementary Fig. 1). We have reported previously that ChUP-1 is a novel protein involved in dietary cholesterol uptake in the nematode C. elegans. We conducted experiments with radioactive dsRNA using C. elegans SID1 as positive control. Transport experiments show that neither SIDT1 nor SIDT2 transport dsRNA or microRNAs in HEK293, PANC-1 or S2 Drosophila melanogaster cells (Fig. 1A–C). Most interestingly, mixing dsRNA with cholesterol resulted in increased uptake of dsRNA (Fig. 1D). The transport of the dsRNA was dose-dependent on the amount of cholesterol used (Fig. 1E). The expression of SID-1, SIDT1and SIDT2 was corroborated with RT-PCR (Fig. 1F).

**Comment by Antonialock** [comment]
tagging works now..

**Comment by Antonialock** [comment]
Maybe it is ok, not sure?
...Even though a couple of studies have shown dsRNA transport by SIDT132, 33. A recent study suggested that dsRNA transport by SIDT1 was attained only when the dsRNA was covalently bound to cholesterol38.

**Comment by Antonialock** [comment]
hmm...looking at https://febs.onlinelibrary.wiley.com/doi/epdf/10.1002/1873-3468.12541

maybe it's not certain what it does yet...

**Comment by pgaudet** [comment]
There is more evidence for a role in RNA transport, so I left that : 

https://www.ncbi.nlm.nih.gov/pubmed/?term=SIDT1+function

Thanks, Pascale
