### ISSUE TITLE
Reactome: pathway annotations to proteasome subunits

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2792]
@deustp01 tagging you on this - not sure whether Reactome would like to assign this to a different tracker.

For the D.mel proteasome subunits have been annotated as TASs to:
GO:0007623 circadian rhythm
GO:0008063	Toll signaling pathway

Can these be removed as the process of proteasome-mediated degradation should not be directly annotated as in involved in the pathway? (prob. made by Mark W many moons ago).

Attaching file with proteins.
[proteasome_pathway.txt](https://github.com/geneontology/go-annotation/files/4148498/proteasome_pathway.txt)

**Comment by deustp01** [comment]
We assign GO biological process terms to reactions and pathways and the terms then propagate onto the proteins involved in those events. I've removed the offending GO terms from the pathways in our internal database. The changes will propagate to the public database and our GAF with our next release in late March.

**Comment by hattrill** [comment]
Thanks!
