### ISSUE TITLE
EIF5 is annotated to be a GTPase, should be GTPase activator

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#2793]
See this TAS from PINC:

http://amigo.geneontology.org/amigo/reference/PMID:8663286

Do we believe this? The TAS seems to be based on sequence similarity. Not been demonstrated experimentally?

Should the annotation not be to GTPase **activator** activity? AFAIK EIF5 is a GAP, many papers (not yet annotated) show this. E.g https://www.google.com/search?q=eif5+gtpase

**Comment by pgaudet** [comment]
Thanks @cmungall 
I deleted the PINC annotations and disputed the UniProt ones.
