### ISSUE TITLE
IPR002557  and IPR036508 NOT chitin metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2794]
Chitin binding (GO:0008061)
is OK, but "chitin metabolic process" isn't

Often, these molecules in pathogens bind chitin to sequester it and prevent  activation of host immune system.

Cheers

Val

**Comment by typhainepl** [comment]
I've updated the InterPro entries, the changes will be visible in the next InterPro release (78.0).
