### ISSUE TITLE
IPR016900 - query GO:0004583 association

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2799]
Alpha-2-glucosyltransferase Alg10 (IPR016900)
is for the conserved ALG10 protein, and is linked (correctly) to EC: 2.4.1.256

EC: 2.4.1.256 is an xref to this GO term (also correct):
id: GO:0106073
name: dolichyl pyrophosphate Glc2Man9GlcNAc2 alpha-1,2-glucosyltransferase activity

But IPR016900 is associated with this different GO term:
Dolichyl-phosphate-glucose-glycolipid alpha-glucosyltransferase activity (GO:0004583)

Please check, but I think IPR016900 should be associated with GO:0106073 instead.

**Comment by sjm41** [comment]
@hattrill

**Comment by hattrill** [comment]
Tagging @happy-lorna

**Comment by happy-lorna** [comment]
I have corrected the mapping here
Thanks!

**Comment by sjm41** [comment]
Thanks Lorna!

I had thought/assumed that the EC numbers associated with InterPro entries were simply pulled in from the EC xref on the associated GO term, but this example shows that can't be true - so I guess you add the EC associations manually in-house?
If so, there might be a useful QC process to implement here: for all the GO MF terms used on InterPro entries, compare the EC-to-GO associations present in InterPro to the EC xrefs on the terms within the GO itself.
This should flag up any inconsistencies like this one (which could then be fixed at InterPro or GO, as appropriate) as well as show up any missing EC associations at either end.
What do you think?
