### ISSUE TITLE
PAINT PTN000275691 (PTHR12413)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2800]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000275691

This appears to be adding "dolichyl pyrophosphate Man9GlcNAc2 alpha-1,3-glucosyltransferase activity" (GO:0042281) to both ALG6 orthologs (correct) and ALG8 orthologs (incorrect).
Looking at fly (Q9W3V8) and human ALG8 (Q9BVK2).

Can you look at restricting the propagation of this term to ALG6 orthologs?

(FYI, ALG8 orthologs "ought" to be getting this term:
dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase activity (GO:0042283))

Useful review: https://link.springer.com/chapter/10.1007/978-4-431-67877-9_82

**Comment by sjm41** [comment]
@hattrill

**Comment by pgaudet** [comment]
@sjm41 Human ALG8 protein is annotated as 'Probable dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase' - is this not correct ? 

https://www.uniprot.org/uniprot/Q9BVK2? 


In any case, I propagated the yeast annotation to the ALG8 clade, 
dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase activity

Is this right ? 

Thanks, Pascale

**Comment by sjm41** [comment]
_@sjm41 Human ALG8 protein is annotated as 'Probable dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase' - is this not correct ?
https://www.uniprot.org/uniprot/Q9BVK2?_

Yes, that's correct.  The problem is that PTN000275691 is currently giving a (slightly) different GO annotation to ALG8, ie. "dolichyl pyrophosphate Man9GlcNAc2 alpha-1,3-glucosyltransferase activity" (so using the substrate lacking a terminal Glc residue)

_In any case, I propagated the yeast annotation to the ALG8 clade,
dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase activity
Is this right ?_
Yes, that's right, thanks. But can you confirm you also blocked the incorrect annotation (dolichyl pyrophosphate Man9GlcNAc2 alpha-1,3-glucosyltransferase activity) on ALG8?


In case helpful, here are my notes on the ALG6/ALG8/ALG10 system:

ALG6:
- Adds the first glucose residue to the lipid-linked oligosaccharide precursor for N-linked glycosylation.
- Transfers glucose from dolichyl phosphate glucose (Dol-P-Glc) onto the lipid-linked oligosaccharide Man9GlcNAc2-PP-Dol.
- EC:2.4.1.267 => Dol-P-Glc:Man(9)GlcNAc(2)-PP-Dol alpha-1->3-glucosyltransferase.
- GO:0042281 => dolichyl pyrophosphate Man9GlcNAc2 alpha-1,3-glucosyltransferase activity

ALG8:
- Adds the second glucose residue to the lipid-linked oligosaccharide precursor for N-linked glycosylation.
- Transfers glucose from dolichyl phosphate glucose (Dol-P-Glc) onto the lipid-linked oligosaccharide Glc1Man9GlcNAc2-PP-Dol.
- EC:2.4.1.265 => Dol-P-Glc:Glc(1)Man(9)GlcNAc(2)-PP-Dol alpha-1->3-glucosyltransferase.
- GO:0042283 => dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase activity

ALG10:
- Adds the third glucose residue to the lipid-linked oligosaccharide precursor for N-linked glycosylation.
- Transfers glucose from dolichyl phosphate glucose (Dol-P-Glc) onto the lipid-linked oligosaccharide Glc2Man9GlcNAc2-PP-Dol. 
- EC:2.4.1.256 => Dolichyl-P-Glc:Glc(2)Man(9)GlcNAc(2)-PP-dolichol alpha-1,2- glucosyltransferase.
- GO:0106073 => dolichyl pyrophosphate Glc2Man9GlcNAc2 alpha-1,2-glucosyltransferase activity

**Comment by pgaudet** [comment]
Hi @sjm41 

Thanks for the notes, this is very helpful. 

This is what I have now: 
* ALG8:  GO:0042283 dolichyl pyrophosphate Glc1Man9GlcNAc2 alpha-1,3-glucosyltransferase activity (no other MF)
* ALG6: GO:0042281 dolichyl pyrophosphate Man9GlcNAc2 alpha-1,3-glucosyltransferase activity 

I'll look at the family containing ALG10 to make sure it's correctly annotated. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Please reopen if this was not right.

**Comment by sjm41** [comment]
Looks good, thanks Pascale!

**Comment by pgaudet** [comment]
ALG10 = PTHR12989
I've annotated to     GO:0106073 dolichyl pyrophosphate Glc2Man9GlcNAc2 alpha-1,2-glucosyltransferase activity
