### ISSUE TITLE
Review annotations to GO:1900524 positive regulation of flocculation via cell wall protein-carbohydrate interaction by positive regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2801]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:
https://docs.google.com/spreadsheets/d/1QO7qstxpN88jV1WU92H0nr50dKNiuMYVbM9FZEagzzc/edit#gid=0

4 SGD @srengel 

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.  i also cleaned up some other similar annotations for these 2 genes since i was in there.
