### ISSUE TITLE
PTN000180782 cAMP PK reg subunit with cGMP activities  - PTHR11635

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2802]
PTN000180782  	CAMP-DEPENDENT PROTEIN KINASE REGULATORY CHAIN (PTHR11635)

is propagating 3',5'-cyclic-GMP phosphodiesterase activity
cGMP-mediated signaling

 from Dicty cGMP-dependent 3',5'-cGMP phosphodiesterase A to cAMP protein kinase A regulatory subunits.

**Comment by pgaudet** [comment]
Fixed, thanks for reporting this.
