### ISSUE TITLE
follow on query  from transcription refactoring https://github.com/geneontology/go-ontology/issues/18561

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2803]
https://github.com/geneontology/go-ontology/issues/18561

From this I could find nothing more specific than 

"transcription regulator activity"
to use as an MF (the recommendations were for BP terms)

However "transcription regulator activity" is not for direct annotation. I think that was why we had "recruitment" terms?

**Comment by pgaudet** [comment]
What are you trying to capture ? 

Maybe @colinlog has some suggestions ?

**Comment by colinlog** [comment]
We are trying to capture three 'children' of RNA polymerase II regulation which exists as [GO:0003899 DNA-directed 5'-3' RNA polymerase activity (MF)], [GO:0006366 transcription by RNA polymerase II (BP)] and [GO:0005665 DNA-directed RNA polymerase II, core complex (CC)] namely;

- sequence-specific DNA binding factors (dbTF) [MF]
- the co-factors for the dbTFs - these include recruited enzyme (complexes), recruited allosteric interactions and 'bridging' activities [MF].
- General transcription factors (GTFs), these include TFIIA-B-D-E-H etc...)

The biologicasl processes that may be regulated in this context are:

- Trancription initiation [BP]
- Transcription elongation [BP] 
- Transcriptoin termination [BP]

The cellular components for these processes are CC's harbouring MF's for BP's

- protein dimers up to very large protein complexes [CC], that may bear structural RNAs [CC] and that may be bound to specific genomic coordinates [CC]
- Liquid phase partitions [CC]. This term may be found in a physics ontology? It is currently a very hot topic in gene regulation and nuclear structure (regulation) in general.

**Comment by pgaudet** [comment]
@ValWood 

We have since created 
GO:0140537 'transcription regulator activator activity' 
GO:0140416 'transcription regulator inhibitor activity'

I'll close this as out of date. 

Thanks, Pascale
