### ISSUE TITLE
Review annotations to GO:0072364 regulation of cellular ketone metabolic process by regulation of transcription from RNA polymerase II promoter and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2804]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations: 
https://docs.google.com/spreadsheets/d/12fUyZUJZSEtYTTsYyI1WADZAbv0rGGB0wyw-UajPftU/edit#gid=0

4 SGD 

Thanks, Pascale

**Comment by srengel** [comment]
done.
