### ISSUE TITLE
Review annotations to GO:0035960 regulation of ergosterol biosynthetic process by regulation of transcription from RNA polymerase II promoter and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2805]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations: 

https://docs.google.com/spreadsheets/d/1V7N_Kdc1u01QL6bezsbwQp0dh8Cu3RuWtj4T4UyCFYw/edit#gid=0

4 SGD
1 Pombase

Thanks, Pascale

**Comment by ValWood** [comment]
PomBase done
