### ISSUE TITLE
Review annotations to GO:0072367 regulation of lipid transport by regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2806]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:

https://docs.google.com/spreadsheets/d/1c9SBmbjIJXGhKmW6W_mnatUPCljnntsscAftooKVOeE/edit#gid=0

2 BHF
5 SGD

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by RLovering** [comment]
UCL done
