### ISSUE TITLE
Review annotations to GO:1900406 regulation of conjugation with cellular fusion by regulation of transcription from RNA polymerase II promoter and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2807]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:

https://docs.google.com/spreadsheets/d/1goh_Nxp9Hw88bi7oi2OtJH4hViyijAYexgYOIVEnsbY/edit#gid=0

5 SGD
15 Pombase

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by ValWood** [comment]
PomBase done
