### ISSUE TITLE
Review annotations to ' GO:1902352 negative regulation of filamentous growth of a population of unicellular organisms in response to starvation by negative regulation of transcription from RNA polymerase II promoter'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2808]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:

https://docs.google.com/spreadsheets/d/1xA8rk2y9mn8W1bg-ZOpcNglgrUp5RMT29Aw7DhucEKY/edit#gid=0

2 SGD 

Thanks, Pascale

**Comment by srengel** [comment]
done
