### ISSUE TITLE
Review annotations to 'GO:0035950 regulation of oligopeptide transport by regulation of transcription from RNA polymerase II promoter'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2809]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations: https://docs.google.com/spreadsheets/d/1wBUECCSBoigIQxrmD1uh1r4PT7uvE8Vfk-Bu_ujeJAE/edit#gid=0

7 SGD

Thanks, Pascale

**Comment by srengel** [comment]
done
