### ISSUE TITLE
Review annotations to GO:1900473 negative regulation of phosphatidylcholine biosynthetic process by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2810]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations: https://docs.google.com/spreadsheets/d/1Hxpa1wwv7e6WqDYDcjL5z07tnBoUHXfnHvbq9-u_JgI/edit#gid=0

1 SGD

Thanks, Pascale

**Comment by srengel** [comment]
done.
