### ISSUE TITLE
Review annotations to GO:0100056 negative regulation of phosphatidylserine biosynthetic process by transcription from RNA polymerase II promoter and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2811]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations: 
https://docs.google.com/spreadsheets/d/1HufAt3Iy_2VhhxLwILuIrHpxGQfT2Qfd6Kf0KpnJ6pI/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
done.
