### ISSUE TITLE
Review annotations to GO:1900462 negative regulation of pseudohyphal growth by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2812]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations: 
https://docs.google.com/spreadsheets/d/1ZgfggNH25nYc_XhDOjpQXskVndTDAaCu2fV-QWYQP2k/edit#gid=0

3 SGD

Thanks, Pascale

**Comment by srengel** [comment]
done.
