### ISSUE TITLE
PANTHER:PTN000098822 (PTHR10910) needs splitting?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2813]
This node includes these related MF and BP terms:
- adenosine to inosine editing
- RNA processing
- double-stranded RNA adenosine deaminase activity
- tRNA-specific adenosine deaminase activity
- double-stranded RNA binding IBD
http://www.pantree.org/node/annotationNode.jsp?id=PTN000098822

For flies, the PANTHER family PTHR10910 includes these 5 proteins (domains shown):
- Adat1 (has **Adenosine deaminase/editase** domain)
- Adar (has **Adenosine deaminase/editase** & **Double-stranded RNA-binding domain**)
- DIP1 (has **Double-stranded RNA-binding domain**)
- CG12493 (has **Double-stranded RNA-binding domain**)
- blanks (no annotated domains, but has "siRNA binding" IDA annotation)

From sequence/orthology predictions, Adat1 and Adar form a subgroup (PTHR10910:SF140 & PTHR10910:SF142), and the other three form another subgroup (PTHR10910:SF62). (see [here](http://www.pantherdb.org/genes/geneList.do?searchType=basic&loggedPrivilege=false&fieldName=all&fieldValue=PTHR10910*&listType=1&organism=Drosophila%20melanogaster))
Certainly the latter three genes are very unlikely to have any "adenosine deaminase" activity.

So, I think PTHR10910 needs to be split further, with appropriate GO terms being distributed between branches?

**Comment by sjm41** [comment]
@hattrill 
@phanivg

**Comment by pgaudet** [comment]
Hi @sjm41 
The requests regarding the Panther trees should be made in this tracker: 

https://github.com/pantherdb/Helpdesk/issues

Thanks, Pascale

**Comment by sjm41** [comment]
OK, good to know. New ticket here: https://github.com/pantherdb/Helpdesk/issues/12

I guess there may be some PAINT work to do once the tree is split, so I'll leave this ticket open for now?

**Comment by pgaudet** [comment]
OK yes

**Comment by sjm41** [comment]
Hi @pgaudet 
Just checking how this one can be moved forward? (Is the Panther tracker actively monitored? - haven't seen any activity there since Feb). Steven.

**Comment by marcfeuermann** [comment]
I've blocked the propagation of the 2 terms to the node containing DIP1, CG12493 and blanks.

**Comment by sjm41** [comment]
Thanks Marc!

**Comment by sjm41** [comment]
Hi @marcfeuermann 
Looks like the "double-stranded RNA adenosine deaminase activity" term is still on the node containing DIP1, CG12493 and blanks.  Can you block propagation of this term on that node too please?

**Comment by sjm41** [comment]
Hi @marcfeuermann Can I give you a nudge on this one?  Just need to also remove the "double-stranded RNA adenosine deaminase activity" term on the node containing DIP1, CG12493 and blanks.
Thanks.

**Comment by pgaudet** [comment]
Removed annotation. I also removed dsRNA binding, but I kept RNA processing, since thre is EXP evidence that it binds siRNA. 

Let me know if that's OK. 

Thanks, Pascale

**Comment by sjm41** [comment]
Part of this issue appears to have resurfaced: CG12493 (which has no deaminase domain) is getting "double-stranded RNA adenosine deaminase activity" & " tRNA-specific adenosine deaminase activity" via PTN000098822 again.

Not sure why these previously fixed issues are coming back to haunt us?

**Comment by marcfeuermann** [comment]
So, I've blocked all the activity terms as well as the related BPs for CG12493. I've put this family in my blacklist (to investigate what happened). I'm trying to close this ticket once again.... fingers crossed.
