### ISSUE TITLE
Review annotations to GO:1900387 negative regulation of cell-cell adhesion by negative regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2814]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:
https://docs.google.com/spreadsheets/d/1YteZNqkVFeqw0FOpGDvYAU7b9CYXDtariIVqvcJEvt8/edit#gid=0

2 pombase
3 BHF

Thanks, Pascale

**Comment by ValWood** [comment]
PomBase done

**Comment by RLovering** [comment]
UCL done
