### ISSUE TITLE
Reviewed annotations to GO:0035950 regulation of oligopeptide transport by regulation of transcription from RNA polymerase II promoter and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2815]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:
https://docs.google.com/spreadsheets/d/1wUQ-nQPJ4jlMdxLWcHbbvntgFNwXS9O3-gHnprYwlUQ/edit#gid=0

7 SGD

**Comment by srengel** [comment]
done.
