### ISSUE TITLE
Paint annotation to Q54DE4/DDB_G0292312/fbxD

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-annotation#2816]
@pgaudet I found the following PAINT annotation

REFG | Q54DE4 | DDB0184321 | part_of | GO:0070545 | PeBoW complex | ECO:0000318(IBA) | ECO:0000318 | (IBA) |   | PMID:21873635 |   | PANTHER:PTN000458000\|SGD:S0... 

FbxD has been found as the F-box protein binding to Skp1 (fpaA, fpaB) and to cullin E (CulE) and forming the Dicty cytoplasmic SCF complex. 

I cannot exclude that FbxD is involved in another complex but since there is a family of F-box proteins in Dicty, I doubt it. I leave it up to you if reconsidering the PAINT annotation in this context.

Thanks!

**Comment by pgaudet** [comment]
Fixed, thanks for reporting.
