### ISSUE TITLE
Review last 'regulation of biosynthetic process by regulation of transcription' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2817]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations: https://docs.google.com/spreadsheets/d/1PP_zR5Oe-_W2My2XljHUtdW8lCu_unCcadvTQauLNMA/edit#gid=0

* 10 CGD
* 1 PomBase
* 10 SGD 

    GO:1900435 negative regulation of filamentous growth of a population of unicellular organisms in response to starvation
    GO:1900526 negative regulation of phosphatidylserine biosynthetic process by negative regulation of transcription from RNA polymerase II promoter
    GO:1900525 positive regulation of phosphatidylserine biosynthetic process by positive regulation of transcription from RNA polymerase II promoter
    GO:0061427 negative regulation of ceramide biosynthetic process by negative regulation of transcription from RNA Polymerase II promoter
    GO:1900413 positive regulation of phospholipid biosynthetic process by positive regulation of transcription from RNA polymerase II promoter
    GO:1900472 positive regulation of phosphatidylcholine biosynthetic process by positive regulation of transcription from RNA polymerase II promoter
    GO:1900525 positive regulation of phosphatidylserine biosynthetic process by positive regulation of transcription from RNA polymerase II promoter
    GO:0100036 positive regulation of purine nucleotide biosynthetic process by transcription from RNA polymerase II promoter
    GO:1900418 positive regulation of purine nucleotide biosynthetic process by positive regulation of transcription from RNA polymerase II promoter

Thanks, Pascale

**Comment by ValWood** [comment]
PomBAse fixed

**Comment by marekskrzypek** [comment]
CGD fixed, except GO:1900435 negative regulation of filamentous growth of a population of unicellular organisms in response to starvation. What is wrong with this term? Did you mean GO:1902352 negative regulation of filamentous growth of a population of unicellular organisms in response to starvation by negative regulation of transcription from RNA polymerase II promoter? These are fixed in CGD.

**Comment by ValWood** [comment]
Hi Marek,

I believe the issue with these terms is that they are  (usually) describing  population level phenotypes.
which is out of scope for GO.

Does the parent 
GO:0060258    negative regulation of filamentous growth
work?

if so
@pgaudet  maybe rename 
GO:1900435 negative regulation of filamentous growth of a population of unicellular
to
GO:1900435 negative regulation of filamentous growth in response to starvation 

(@pgaudet quite a few of the parents in this. branch will need the "or a population of unicellular organisms" removing)

**Comment by srengel** [comment]
SGD done.

**Comment by marekskrzypek** [comment]
Hi Val,
GO:0060258 negative regulation of filamentous growth should work but it is less specific. @pgaudet renaming as Val suggests will work better: 

negative regulation of filamentous growth of a population of unicellular 
to
negative regulation of filamentous growth in response to starvation

**Comment by marekskrzypek** [comment]
CGD done.
