### ISSUE TITLE
InterPro2GO for DPM1-like (IPR039528)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2818]
DPM1-like (IPR039528) has a very general GO MF term (transferase activity (GO:0016740)) but a very specific EC xref (2.4.1.83).
One of these should probably be adjusted accordingly?
The GO term for 2.4.1.83 is "dolichyl-phosphate beta-D-mannosyltransferase activity" (GO:0004582).

@hattrill 
@happy-lorna

**Comment by typhainepl** [comment]
Thank you for highlighting this. I've updated the InterPro entry.
