### ISSUE TITLE
 PINC  TAS and NAS for Aminoacyl tRNA synthase complex-interacting multifunctional protein 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2823]
@pgaudet  could you delete these when you get chance (possibly others)

UniProtKB:Q12904 | AIMP1 | involved_in | GO:0006935    chemotaxis | ECO:0000304   TAS | PMID:7545917 |   | 9606 Homo sapiens | PINC |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB:Q12904 | AIMP1 | involved_in | GO:0006954    inflammatory response | ECO:0000304   TAS | PMID:7545917 |   | 9606 Homo sapiens | PINC |  
UniProtKB:Q12904 | AIMP1 | involved_in | GO:0007165    signal transduction | ECO:0000303   NAS | PMID:9405472 |   | 9606 Homo sapiens | PINC |  
UniProtKB:Q12904 | AIMP1 | involved_in | GO:0009611    response to wounding | ECO:0000304   TAS | PMID:7545917 |   | 9606 Homo sapiens | PINC

**Comment by pgaudet** [comment]
Removed.
