### ISSUE TITLE
UniProtKB-KW:KW-0698 RSC9 NOT rRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2824]
UniProtKB-KW:KW-0698 | S. cerevisiae | Q03124 | RSC9 | rRNA processing
This is part of a chromatin remodelling complex, required for (most?) transcription. I don't see any evidence for RNA processing though?

**Comment by ValWood** [comment]
Should  the RNA processing mapping be removed here
https://www.uniprot.org/uniprotkb/Q03124/entry

**Comment by ValWood** [comment]
I have assigned @Antonialock , but I have assigned a HUGE number of tickets to her, so I tried not to reassign any of the existing ones.

**Comment by Antonialock** [comment]
yes it's a downstream effect


Shifting wild-type cells to 37°C causes a temporary decrease in ribosome biogenesis but the cells recover and increase rRNA synthesis after a 3 hr shift. In contrast, rRNA synthesis in rsc9-1 is reduced at this time point. ...These results further indicate that RSC plays a role in ribosome biogenesis, a principal target of the stress response.

**Comment by Antonialock** [comment]
done
