### ISSUE TITLE
UniProtKB-KW:KW-0665 RSC9 NOT pyrimidine nucleotide biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2825]
UniProtKB-KW:KW-0665 | S. pombe | Q9HDU6 | pan5 | pyrimidine nucleotide biosynthetic process |   | incorrect annotation, correct- pantothoate biosynthesis |  

tks
v

**Comment by sylvainpoux** [comment]
Done. Thanks for pointing this out
S.
