### ISSUE TITLE
UniProtKB-KW:KW-0415 P40383 not karyogamy

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2826]
This seems indirect

UniProtKB-KW:KW-0415 | S. pombe | P40383 | exo2 | karyogamy |   | indirect phenotype

phenotype only?

Also this part of the function summary may be out of date?

Acts as a microtubule-associated protein which interacts with cytoplasmic microtubules through beta-tubulin and promotes in vitro assembly of tubulin into microtubules. Associates with microtubule functions such as chromosome transmission, nuclear migration, and SPB duplication. Has also a role in G1 to S transition and is involved in nuclear fusion during karyogamy (By similarity).

as in fission yeast I dopn't think there is any evidence that exo1 is a MAP

**Comment by ValWood** [comment]
I think the karyogamy comes from S. cerevisiae anyway

and in pombe mating is normal

FYPO:0000760 | normal mating | exol-1::ura4 (disruption) | Microscopy |   | Szankasi P et al. (1995)

**Comment by mah11** [comment]
hang on, is this about exo1 or exo2? The UniProt annotation says exo2 (which doesn't have a mating phenotype annotated, normal or abnormal).

**Comment by sylvainpoux** [comment]
Corrected. Note that I also simplified/modified function and added experimental evidence tags to the exonuclease activity.
Thanks
Sylvain

**Comment by ValWood** [comment]
Ah sorry was exo2, but the role in karyogamy is unreported and exo2 is required for vegetative growth so likely to have pleiotropic phenotypes. 

karyogamy  is from an S. cerevisiae phenotype (probably used to be a GO annotation,? ) now only has
nuclear fusion during mating: absent
