### ISSUE TITLE
Remove "DNA-directed DNA polymerase activity" from IPR016266

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2830]
DNA polymerase epsilon, subunit B (IPR016266)
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR016266/

As the InterPro description says, "The largest subunit of DNA polymerase epsilon is responsible for polymerase activity." -  subunit B (this entry) is non-catalytic, so should not be associated with "DNA-directed DNA polymerase activity (GO:0003887)".

Can you remove it please?

@happy-lorna 
@hattrill

**Comment by typhainepl** [comment]
Hi,
I have updated the InterPro entry. The changes will be visible in InterPro 79.0.
