### ISSUE TITLE
Review annotations to GO:0000726 non-recombinational repair

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2831]
Hello, 

There are 2 EXP annotations to GO:0000726 non-recombinational repair

REXO4 RNA exonuclease 4 non-recombinational repair has input ENSEMBL:ENSG00000181019
occurs at SO:0000167 ARUK-UCL Homo sapiens IDA exonuclease pthr12801 protein PMID:21602889 20181201
@RLovering 
Use GO:0006302 double-strand break repair ? 
(BTW I am not sure the 'input' is correct; is the repair really specific to that gene, or is this the gene that has been tested ? ) 

nfo endonuclease IV non-recombinational repair EcoCyc Escherichia coli K-12 IDA endonuclease iv endodeoxyribonuclease iv pthr21445 protein PR:P0A6C1 PMID:2453510 20110603
@keseler 
-> Pathway not specified - use parent 'DNA repair ? 

Can you annotate to a 'positive' term ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
I don't this this is a straight-forward situation. It looks like the enzyme (which is also a transcription regulatory) is involved in double and single stranded DNA exonuclease activity, but 10x more for single stranded DNA. I think that it is gene specific, but this really isn't my area of expertise.

What do you think?

Ruth

**Comment by keseler** [comment]
Hi Pascale,
I've removed the annotation from EcoCyc for the moment and used DNA repair, as you suggested.  Hopefully I'll find time to update (or delegate...) this enzyme further; it's really not well annotated.
Cheers,
Ingrid

**Comment by RLovering** [comment]
removed
