### ISSUE TITLE
PANTHER:PTN000087518 protein O-linked fucosylation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2832]
FRINGE-RELATED (PTHR10811) proteins are 
are GlcNAc transferases for O-linked fucose modified peptides, with the activity:
O-fucosylpeptide 3-beta-N-acetylglucosaminyltransferase activity

PANTHER:PTN000087518 is annotated with:
protein O-linked fucosylation 

I will dispute the underlying annotations in P2GO

**Comment by hattrill** [comment]
Looking at this again, I wonder if the problem might be with the term definition rather than the term itself.

protein O-linked fucosylation GO:0036066:
"The process of transferring a fucosyl group to a serine or threonine residues in a protein acceptor molecule, to form an O-linked protein-sugar linkage. PMID:19948734"

Seems to suggest a single-step process

...As do the definitions for a lot of the protein glycosylation terms - many have the pattern "A protein glycosylation process in which a carbohydrate or carbohydrate derivative unit is added to a protein via..."

I wonder if the definitions encompassed the multi-step process, it would be better i.e. modification of the protein or proteoglycan (including modifications, trimming?).  {something like:
"The process of transferring a fucosyl group to a serine or threonine residues in a protein acceptor molecule, to form an O-linked protein-sugar linkage and subsequent glycosylation and modification to form the mature proteoglycan."

If you agree, perhaps I can move this to the ontology tracker.

**Comment by pgaudet** [comment]
Sure - what would be the other steps ?

**Comment by hattrill** [comment]
From what I know, O-linked fucosylation is restricted to EGF-type and thrombospondin type 1 repeats, fucose is linked to a Ser/Thr. The fucose can either remain unmodified or be modified: In EGF-repeats, by the addition of GlcNAc and, depending on situation and species, this can be extended by galactose and sialic acid. In TSR repeats, by glucose.

So, the structures resulting from O-fucosylation:

Fuc-O-Ser/Thr
Glcβ1,3Fuc-O-Ser/Thr
GlcNAcβ1,3Fuc-O-Ser/Thr
Galβ1-4GlcNAcβ1-3Fuc-O-Ser/Thr
Siaα2–3/6Galβ1-4GlcNAcβ1-3Fuc-O-Ser/Thr

PMID:30690220 Protein O-fucosylation: structure and function.
PMID:16464858 Two distinct pathways for O-fucosylation of epidermal growth factor-like or thrombospondin type 1 repeats.
PMID:28876865 Other Classes of Eukaryotic Glycans.

**Comment by marcfeuermann** [comment]
The primary annotation is no more present, so PAINT annotation also disappeared.
