### ISSUE TITLE
IPR014839 mapping to transcription

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2833]
I don't think this should be annotated to transcription at present. The evidence is quite weak. It could be any aspect of gene expression (or not)

The SGD annotation is based on a single 2006 paper
https://www.yeastgenome.org/reference/S000114801

It is just genetic interaction data.

**Comment by typhainepl** [comment]
thanks for highlighting this, I have removed the GO term from the InterPro entry.
