### ISSUE TITLE
NF-kappa-B-activating protein IPR040466

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2834]
NF-kappa-B-activating protein IPR040466

The role of NFAH in Notch signaling pathway and transcriptional regulation may not be conserved across species, and there are certainly other suggestions for functional roles (such as splicing regulation, RNA binding), so don't think that attaching terms to this domain are advisable at the moment.

PMID:27997579
PMID:27694884

**Comment by hattrill** [comment]
tagging @happy-lorna

**Comment by typhainepl** [comment]
thanks, I have updated the InterPro entry. The changes will be visible in InterPro 79.0.
