### ISSUE TITLE
review annotation of P13009 to GO:0008276 and the inferred GO:0006479

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#2837]
There currently is an IDA annotation for P13009 to GO:0008276, coming from BHF-UCL.  However, methionine synthase is not a protein methyltransferase.  The cobalamin cofactor of the enzyme acts as a methyl carrier and needs to be methylated for the enzyme to be active.  Maybe that caused the confusion?  

Thanks for looking into this,
Ingrid

**Comment by RLovering** [comment]
Thanks Ingrid
annotation deleted, 
Best
Ruth

**Comment by keseler** [comment]
Hi Ruth,
Sorry, I should have checked sooner, but the same annotation was also made for the second methionine synthase in E. coli, MetE, P25665.
Thanks,
Ingrid

**Comment by RLovering** [comment]
OK P25665 GO:0008276 annotation deleted, thanks for letting me know
Ruth
