### ISSUE TITLE
RNA polymerase III complex (Transcription Matrix)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2844]
Tbp | TATA binding protein |   | RNA polymerase III complex |   | FlyBase | Drosophila melanogaster | IC | GO:0006359GO:0042796GO:0042797 | tata-box binding protein pthr10126 | protein |   | FB:FBrf0090837PMID:8943346 | 20060803

I don't think Tbp is RNA polymerase III complex?

@hattrill

**Comment by hattrill** [comment]
D.mel pol III does:  "U6 TATA sequences are bound by TFIIIB that in Drosophila contains the three subunits TBP, Brf1, and Bdp". I don't know how/if this is conserved.

(I think that there is some overlap between subunits between pol II and I and III - we have them on a list to review at some point, so if you are looking in any detail at them now, give us a shout and we can co-ordinate).

**Comment by ValWood** [comment]
But is TATA part of polymerase complex?

I never annotate it to polymerase? I only have the polymerase subunits?
https://www.pombase.org/term_genes/GO:0005666

Maybe it should include TATA (@pgaudet can we put this on agenda today)

**Comment by ValWood** [comment]
Ah but should be 
transcription factor TFIIIB complex (GO:0000126), not the polymerase?
https://www.pombase.org/term/GO:0000126

**Comment by ValWood** [comment]
For info 5 shared subunits for pol I,II,III


SPAC1B3.12c | rpb10 | DNA-directed RNA polymerase I, II, and III subunit Rpb10
SPAC23C4.15 | rpb5 | DNA-directed RNA polymerase I, II and III subunit Rpb5
SPCC1020.04c | rpb6 | DNA-directed RNA polymerase I, II and III subunit Rpb6
SPBC14C8.12 | rpb8 | DNA-directed RNA polymerase I, II and III subunit Rpb8
SPBC19C2.03 | rpc10 | DNA-directed RNA polymerase I, II and III subunit Rpc10

I have a list (in progress) of which transcription complexes should be annotated to which of the new function terms.

In total there are 32 subunits of pol1,11, and III in pombe/cerevisiae. 31 appear to be conserved. I haven't found RPA14 in metazoa but I will look for that now.

I am such a nerd :)

**Comment by hattrill** [comment]
Sorry - misunderstood. Up to speed now. Yes, that seems correct.....in fact, this annotation was removed back in early Dec and is not in FlyBase.

The GO in AmiGO hasn't been updated since 2020-01-02. The Feb updated was skipped.

**Comment by ValWood** [comment]
I think metazoa mustn't have RPA14, or it isn't a _bona fida_ subunit. Human rat mouse all have 13 annotated subunits for pol I complex  but pombe and cerevisiae have 14

**Comment by ValWood** [comment]
Overall core  transcription  looks pretty good
see matrix snapshot here : https://github.com/geneontology/go-annotation/issues/1947

**Comment by hattrill** [comment]
Having a deeper look - @sjm41 has already done the RNA pol Gene Groups for FlyBase - that explains our GO clean-up in Dec :)....you can also get orthologs from these pages. 
pol III http://flybase.org/reports/FBgg0001255.html
pol II http://flybase.org/reports/FBgg0000351.html
pol I http://flybase.org/reports/FBgg0001253.html

Feel free to indulge your inner nerd.

**Comment by sjm41** [comment]
My review in Dec was focussed on cleaning up the catalytic activity terms (wrt our ongoing enzyme review project). I removed a number of inappropriate annotations then, as well making several InterPro2GO and PAINT tickets (I can look them up if you like - I don't think they have all been resolved yet.)
So, the 'Gene Group' pages Helen alludes to are (mainly) for the 'catalytic core subunits' of Dmel RNAPs - they are all grouped under: http://flybase.org/reports/FBgg0001250.html

The only complete RNAP complex we have a public group for is RNAPII:
http://flybase.org/reports/FBgg0000351.html

But I have spreadsheets ready-to-go for the complete Dmel RNAPI and RNAPIII complexes - these are based on a review of the available literature and my own orthology/GO analyses - I just haven't had chance to build them into 'Gene Groups' yet.  Can also share these if helpful.

**Comment by ValWood** [comment]
It's OK, I was only looking at annotation intersections for txn call this p.m. 
It  seems that I should wait for the next GO update before reporting any oddities though!

**Comment by hattrill** [comment]
....and got more than you bargained for :)

**Comment by ValWood** [comment]
I think this one  can close...
