### ISSUE TITLE
pku70 PAINT propagation PANTHER:PTN000288287

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2846]
Can we remove these? They are just phenotypes (but I don't think we propagate response to annotations generally.
(we know quite a lot about ku so these will look strange)

pku70 | Ku domain protein Pku70 |   | cellular response to X-ray |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000288287RGD:2643RGD:3976 | ku autoantigen dna helicase pthr12604 | protein |   | PMID:21873635 | 20170228

  | pku70 | Ku domain protein Pku70 |   | cellular response to gamma radiation |   | GO_Central | Schizosaccharomyces pombe | IBA | FB:FBgn0041627PANTHER:PTN000288287 more... | ku autoantigen dna helicase pthr12604 | protein |   | PMID:21873635 | 20170228

**Comment by ValWood** [comment]
Also from pku80

**Comment by marcfeuermann** [comment]
Cleaned.
