### ISSUE TITLE
IPR010684 not regulation (pof4 elongin complex)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2849]
Hi,

GO:0006357 | regulation of transcription by RNA polymerase II | IEA with IPR010684

this isn't regulating elongation/initiation it's part of the core transcription machinery.

could have both

GO:0006368 | transcription elongation from RNA polymerase II promoter 

GO:0006367 | transcription initiation from RNA polymerase II promoter

**Comment by ValWood** [comment]
@colinlog  correct? @pgaudet

**Comment by typhainepl** [comment]
Thanks for highlighting this, I have removed GO:0006357 and added GO:0006368 instead.
