### ISSUE TITLE
 IPR000812	not regulation  (Transcription factor TFIIB)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2850]
is core transcription machinery so  should be directly to the term not to regulation

GO:0006355 | regulation of transcription, DNA-templated | IEA with IPR000812 | GO_REF:0000002 | 367

can use
 general transcription initiation factor activity
(if allowed for direct mappings)

and only
transcription, DNA-templated (GO:0006351)

(because family contains polII and polIII GTFs)

**Comment by typhainepl** [comment]
I have removed GO:0006355 from the entry.
However, GO:0006352 looks more appropriate than GO:0006351, what do you think @ValWood ?

**Comment by ValWood** [comment]
Yes, good catch!

**Comment by typhainepl** [comment]
I have updated the entry with GO:0006352.
