### ISSUE TITLE
IPR037796	GO:0006357	 SAGA complex/transcription factor TFIID complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2851]
regulation of transcription by RNA polymerase II IEA  with 

should be directly to the term, not to regulation term (core transcription machinery)

this family is specific for a gene product, so can use

RNA polymerase II general transcription initiation factor activity
and
transcription initiation from RNA polymerase II promoter

**Comment by typhainepl** [comment]
I have updated the InterPro entry.
