### ISSUE TITLE
IPR009400 transcription factor TFIIH complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2852]
This is core transcription machinery, should not be to "regulation"
GO:0006355 | regulation of transcription, DNA-templated

better (more specific)  would be 

RNA polymerase II general transcription initiation factor activity
and
GO:0006367 | transcription initiation from RNA polymerase II promoter

**Comment by typhainepl** [comment]
@ValWood it looks like 'GO:0006366: transcription by RNA polymerase II' will suit better, what do you think?

**Comment by ValWood** [comment]
GO:0006366: transcription by RNA polymerase II
is true, but the inititation specific descendant
transcription initiation from RNA polymerase II promoter
is more precise and also true, so this would be better here.

The rule of thumb is to be as specific as possible , but only as long as the annotation is true for all members and in this case it seems to be a TFIIH specific domain.

**Comment by typhainepl** [comment]
I agree we should use the most specific term possible, but in this case GO:0006367 only matches 2 proteins in the InterPro entry (Q6ZYL4, Q9HDW3) and isn't supported by literature; while GO:0006366 matches 79 proteins and is supported by 2 publications (19008953, 19818408).

**Comment by ValWood** [comment]
Hmm, I don't know why it isn't  supported, 
TFIIH is a highly conserved transcription initiation factor...many many papers
https://www.ncbi.nlm.nih.gov/pubmed/?term=TFIIH+initiation


@srengel  could this IDA be added at SGD?
I have this ISS @PomBase
UniProtKB:Q9HDW3 | tfb5 | involved_in | GO:0006367    transcription initiation from RNA polymerase II promoter | ECO:0000266  ISO | GO_REF:0000024 | SGD:S000007603

This paper would do it
https://www.ncbi.nlm.nih.gov/pubmed/30905750


In fact, 
MF RNA polymerase II general transcription initiation factor activity
should be is_a
BP GO:0006367 | transcription initiation from RNA polymerase II promoter
@pgaudet

**Comment by srengel** [comment]
@ValWood i added just now TFB5 GO:0006367 IDA PMID: 30905750

**Comment by typhainepl** [comment]
I have updated the InterPro entry.
