### ISSUE TITLE
general transcription initiation factor activity (GO:0140223)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2853]
Transcription group  discussed that this term should have a comment to the effect that the genes  which are  GTFs are core transcription machinery and should be annotated directly to terms transcription and not to their regulation.

There are a couple of cases to discuss.
1) TFIIH components  which are kinases/cyclins , aren't these regulators?
1) GTFs which are also members of other complexes like
tfg3 which is TFIID, TFIIF, Ino80, SWI/SNF, and NuA3 complex subunit
so although a GTF, could also be corepressor/coactivator.  So some multifunctional GTFs might also be "regulators"*

* this depends on the decision about the decision on corepressor/coactivator

@RLovering 
@pgaudet 
@colinlog

**Comment by ValWood** [comment]
I think this one can close? out of date?

**Comment by pgaudet** [comment]
This was done - Comment: Usage guidance: The distinction between general transcription factors and DNA-binding transcription factors is that the latter modulate the selection of which genes are expressed under specific conditions, while general transcription factors are the constitutive machinery required for transcription initiation.
