### ISSUE TITLE
PANTHER:PTN000137292 ATP-dependent peptidase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2856]
PANTHER:PTN000137292 ATP-dependent peptidase activity

The ClpX subunit ClpXP of does not actually possess the peptidase activity, which belongs to the ClpP subunit.

ClpX is an ATPase - the activity of which probably relates to its role as a chaperone in loading/unloading the peptide substrate for ClpXP and in other chaperone/protein QC processes.

https://en.wikipedia.org/wiki/ClpX

Could PAINT block this propagation.

These have been propaged from a single source: UniProKB:P0A6H1
Could CACAO (@jrr-cpt) add this to their fix list?

(tagging @sjm41, in case in comes up in your review)

**Comment by marcfeuermann** [comment]
Indeed, this family should not have the peptidase activity. I've removed the propagation.
