### ISSUE TITLE
IPR023960 NOT ubiquinol-cytochrome-c reductase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2857]
https://www.uniprot.org/uniprot/Q7X9A6

remove
IPR023960 Cyt_b6_f_Rieske
GO:0008121    ubiquinol-cytochrome-c reductase activity
(this is a mitochondrial complex, b6-f is chloroplast

IPR014909 Cyt_b6-f_cplx_Fe-S_su
GO:0009496    plastoquinol--plastocyanin reductase activity | ECO:0000256 IEA | GO_REF:0000002 | InterPro:IPR014909
is OK

still looking into 
GO:0045158    electron transporter, transferring electrons within cytochrome b6/f complex of photosystem II activity

IPR017941 Rieske_2Fe-2S
IPR036922 Rieske_2Fe-2S_sf
IPR014349 Rieske_Fe-S_prot
IPR005805 Rieske_Fe-S_prot_C

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
Thank you for this. I had a look into these InterPro entries. They have not been updated for a while, and some GO terms aren't accurate. I have updated the abstracts and GO terms of these entries. This will be visible in our next release. 
Regards, 
Hsin-Yu
