### ISSUE TITLE
Review annotations to GO:0005072 transforming growth factor beta receptor, cytoplasmic mediator activity and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2858]
The following terms will be obsoleted, see details in https://github.com/geneontology/go-ontology/issues/16202

GO:0005072 transforming growth factor beta receptor, cytoplasmic mediator activity
and children: GO:0030618 transforming growth factor beta receptor, pathway-specific cytoplasmic mediator activity
GO:0030616 transforming growth factor beta receptor, common-partner cytoplasmic mediator activity
GO:0030617 transforming growth factor beta receptor, inhibitory cytoplasmic mediator activity

Please review annotations

https://docs.google.com/spreadsheets/d/17D_vv-mC_G2dUHL1-m4lGfUlaGWNcBrlq8oikYZnD1w/edit#gid=0&fvid=1090703531

Group | Number of annotations
-- | --
BHF-UCL | 11
ComplexPortal | 1
FlyBase | 2
WB | 1
PINC | 1

Thanks, Pascale

**Comment by hattrill** [comment]
FB done.

**Comment by bmeldal** [comment]
CP done

**Comment by pgaudet** [comment]
PINC done

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
@vanaukenk Can you check the WB annotation ? I said I'd obsolete this week, let me know if you need more time. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
WB is done. Thx and apologies for the delay.

**Comment by pgaudet** [comment]
Thanks everyone !
