### ISSUE TITLE
PTN000034466 (PTHR10314) - cysteine synthase vs cystathionine beta-synthase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2862]
PTN000034466 propagates "cysteine synthase activity" (a transferase term, EC:2.5.1.47) and "cysteine biosynthetic process from serine" to the "SER/THR DEHYDRATASE AND TRP SYNTHASE FAMILY MEMBER (PTHR10314)" family.

http://www.pantree.org/node/annotationNode.jsp?id=PTN000034466

There are many source annotations for these 2 terms, from worms, plants, yeast and bacteria.

But (at least) the human member of this family (CBS, P35520) is characterised and annotated with a different GO term: cystathionine beta-synthase activity (a lyase term, 4.2.1.22).

The situation appears to be explained in the associated InterPro entry:
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR005857/
Cystathionine beta-synthase IPR005857
_Members of this family closely resemble cysteine synthase but contain an additional C-terminal CBS domain. Cysteine synthase (O-acetylserine (thiol)-lyase) is the enzyme responsible for the formation of cysteine from O-acetyl-serine and hydrogen sulphide with the concomitant release of acetic acid - the function of many of these enzymes is unproven.
This entry includes human CBS protein, which is a hydro-lyase catalyzing the first step of the transsulfuration pathway, where the hydroxyl group of L-serine is displaced by L-homocysteine in a beta-replacement reaction to form L-cystathionine, the precursor of L-cysteine._ 

So...probably needs some more research, but I don't think it's correct to add "cysteine synthase activity" to all PTHR10314 members.  Probably need to add different GO terms to different subfamilies within it?

**Comment by pgaudet** [comment]
Fixed, annotated clade by clade.

**Comment by sjm41** [comment]
This issue has resurfaced - "cysteine synthase activity" (GO:0004124/EC:2.5.1.47) is again being added to genes (e.g. fly Cbs, Human CBS) that are characterized as Cystathionine beta-synthases (GO:0004122/EC:4.2.1.22)

**Comment by marcfeuermann** [comment]
No idea why this is back. I've blocked the cysteine synthase activity for the CBS node which is annotated to cystathionine beta-synthase.
