### ISSUE TITLE
Remove 'protein kinase activity' from IPR010622

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2863]
Can you remove Remove 'protein kinase activity' from IPR010622?
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR010622/

The domain was originally described in a putative protein kinase, but does not seem to have this activity. From PMID:29036396: " FASTK was initially proposed to act as a protein kinase activated upon Fas ligation (1), but critical active site residues are not conserved within the family and this activity has been questioned since (2)."

@happy-lorna 
@typhainepl 
@hattrill

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have removed this term. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Great, thanks. I'll close the ticket.
