### ISSUE TITLE
Annotation object types

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2866]
Hello, 

@vanaukenk is working on the specs for GPAD/GPI files, and in that work we are looking at the types of genes and products annotated, and trying to stardardize more if possible. 

For type *transcript*, there are 
* 25609 GeneDB annotations
* 3 UniProt
* 2 BHF

For type *primary_transcript* 58 BHF transcripts

@Achchuthan 
@pgarmiri 
@RLovering 

Can those be moved to a more precise gene product type ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi 
please could you create a file of the annotations you are talking about? I don't know what these are
Thanks
Ruth

**Comment by pgaudet** [comment]
Here are the annotations:

* Entity = transcript: https://docs.google.com/spreadsheets/d/1N1BALGsQL4HWFbRDSDIGMQhCwVMz8WurRc-fwdnllWA/edit#gid=0

* Entity = primary transcript: https://docs.google.com/spreadsheets/d/1oIfo2CtBf-gVWYTATgqDOq78Tx-7xtjgQe1bfNgZdxE/edit#gid=0

Thanks, Pascale

**Comment by RLovering** [comment]
We can change all the primary transcript annotations to the 3p and 5p IDs and use IGI and WITH for these. This would be a better interpretation of the data

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Do you have a list of recommended annotation object types from which I can choose that fits GeneDB annotations?

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Hi @Achchuthan 
protein | protein | PR:000000001
ncRNA-coding gene | ncRNA_gene  | SO:0001263 
ncRNA | ncRNA | SO:0000655  (and children)
protein-containing complex | protein-containing complex | GO:0032991
marker or uncloned locus | genetic_marker | SO:0001645

Do any of those work ? What do the GeneBD IDs actually correspond to ? 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet, 
GeneDB IDs in the list should correspond to protein-coding genes. So, we can use Protein (PR:000000001).

Thanks,
Achchuthan

**Comment by BarbaraCzub** [comment]
BHF-UCL done

**Comment by pgaudet** [comment]
Hi @Achchuthan 
'protein-coding gene' is OK as an entity, please use that instead, since it more accurately represents the data. 

While you're at it - GeneDB provides the following number of entities: 


25609 transcript
6541  protein
6199 gene


If all entities are 'protein-coding gene' , can you please use that ? 
("gene" is especially ambiguous - we'd minimally like to know if it's protein-coding or ncRNA)

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Sure, we can fix it when we submit to GO next time. 
Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Great, thanks !

**Comment by RLovering** [comment]
It will take us a while to go through the rest of the transcript annotations. I have discussed this with Barbara and we have agreed on the approach we are going to take. I hope to have these done by mid April, if you need them done earlier let me know.

**Comment by pgarmiri** [comment]
Hi, I am trying to find the relevant entities curated by UniProt but I can't find them in the excel file.
Could I have a list please? 
Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi @pgarmiri 
Here you go: https://docs.google.com/spreadsheets/d/1N1BALGsQL4HWFbRDSDIGMQhCwVMz8WurRc-fwdnllWA/edit#gid=0

**Comment by pgarmiri** [comment]
Hi @pgaudet 

Thank you for sharing the spreadsheet again. I had a look at our annotations and although they are ncRNA | ncRNA | SO:0000655,  I could not find any other suitable ID to replace the RNAcentral ID. I saw that Ruth has used the ENSEMBL ID, but for our species (Takifugu rubripes (torafugu) and Oryzias latipes (Japanese medaka) ) there isn't one. 
If you have any other ideas let me know, otherwise we will keep the current one.

Thanks,
Penelope

**Comment by pgaudet** [comment]
Thanks for looking into this @pgarmiri 
The object type ncRNA would be better than transcript. Who assigns object types in those cases, Ensembl ? It's be great if we could make them more accurate. 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi Pascale,
I am afraid I don't have a clear answer on this. Sandra suggested to contact Anton Petrov who runs Rfam/RNAcentral for help. You can either contact him directly or if you tell me exactly what it's needed I can do that. But just to make sure it should be an ID that is supported for annotations.
Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi @AntonPetrov - can you please have a look at this ? 
The GPI2.0 specs require that we use one of the following objects for annotation 

### GPI Entity Types 
#### Entity types may be one of the following, or a more granular child term.

Entity Type | Ontology Label | Ontology ID 
---------------------------|----------------|------------ | 
protein-coding gene | protein_coding_gene | SO:0001217 
ncRNA-coding gene | ncRNA_gene  | SO:0001263 
mRNA | mRNA | SO:0000234
ncRNA | ncRNA | SO:0000655 
protein | protein | PR:000000001
protein-containing complex | protein-containing complex | GO:0032991
marker or uncloned locus | genetic_marker | SO:0001645


https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#gp-entities

Can the 'transcript' objects be changed to something more specific ? 

Thanks, Pascale

**Comment by AntonPetrov** [comment]
Thanks @pgaudet - @blakesweeney and I can look into adding more granular terms. When do you need this?

**Comment by pgaudet** [comment]
This is not urgent, right now those are still allowed. It will probably be several weeks until we implement checks for this (but we'll keep sending reminders).

**Comment by RLovering** [comment]
UCL Primary transcription annotations reviewed and updated

**Comment by suzialeksander** [comment]
ticket is 4 years old and specs have not been enforced yet.  Will make new ticket if there are still violations when GPAD/GPI 2.0 is required.
