### ISSUE TITLE
Review annotations to GO:0005070 SH3/SH2 adaptor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2871]
GO:0005070 SH3/SH2 adaptor activity will be obsoleted, see https://github.com/geneontology/go-ontology/issues/18409

Please review your annotations: 
https://docs.google.com/spreadsheets/d/1uYH63seQfDmgtzQ2wsqtOQ1iF7jxA04OYgfTkKUcvbw/edit#gid=0

Group |Number of annotations
-- | --
BHF-UCL | 7
HGNC-UCL | 1
FlyBase | 5
MGI | 5
UniProt - SWIE | 9
CAFA | 2

Thanks, Pascale

**Comment by pgaudet** [comment]
There are also 12 InterPro domains with this mapping: 

InterPro:IPR017304
--
InterPro:IPR030219
InterPro:IPR035036
InterPro:IPR035035
InterPro:IPR035848
InterPro:IPR035054
InterPro:IPR035032
InterPro:IPR035040
InterPro:IPR035055
InterPro:IPR017289

**Comment by hattrill** [comment]
FB done.

**Comment by typhainepl** [comment]
InterPro done

**Comment by hdrabkin** [comment]
MGI done; two on the list actually come from GOA or other loads and will disappear once term is obsoleted OR original source changes

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
@pgarmiri Can you please review those annotations ?

**Comment by pgarmiri** [comment]
Hi,
The UniProt and CAFA annotations have been reviewed.
Thanks,
Penelope

**Comment by pgaudet** [comment]
Thanks !
