### ISSUE TITLE
Review annotations to GO:0004584 dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2872]
GO:0004584 dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity
is mapped to EC:2.4.1.130, which has been replaced by: 
Transferred entry: 2.4.1.258: Dolichyl-P-Man:Man(5)GlcNAc(2)-PP-dolichol alpha-1,3-mannosyltransferase. 
Transferred entry: 2.4.1.259: Dolichyl-P-Man:Man(6)GlcNAc(2)-PP-dolichol alpha-1,2-mannosyltransferase. 
Transferred entry: 2.4.1.260: Dolichyl-P-Man:Man(7)GlcNAc(2)-PP-dolichol alpha-1,6-mannosyltransferase. 
Transferred entry: 2.4.1.261: Dolichyl-P-Man:Man(8)GlcNAc(2)-PP-dolichol alpha-1,2-mannosyltransferase. 

There are 3 EXP annotations left by GeneDB 
and 1 InterPro mapping to InterPro:IPR007315 

https://docs.google.com/spreadsheets/d/1MNrfYhqCimhrM9Xsxr2GiCk5DhmoDCQGUunmGBvXWyE/edit#gid=0

This term will be obsoleted. 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Thanks a lot for letting me know. I have updated the annotation for the gene from _Trypanosoma brucei_ with GO:0052925 (2.4.1.258) in our Chado database. @uliboehme will be able to update the Plasmodium annotations.

**Comment by typhainepl** [comment]
Hi,
I have replaced the GO term in the InterPro entry by GO:0000030: mannosyltransferase activity.

**Comment by uliboehme** [comment]
Hi @pgaudet, 
Thanks for letting me know. The GO term in Plasmodium (PF3D7_1341600) has been changed last year in the annotation database as indicated in the google spread sheet. https://docs.google.com/spreadsheets/d/1lhBpUjWQMNe6gY9oCYZxajwTTlr1L9cE1h7ZiGEBzi8/edit#gid=0
I'm not able to change GO terms in UniProt (Q8IDS3, PF3D7_1341600).

**Comment by pgaudet** [comment]
@alexsign 
Are GeneDB:PF3D7_1341600 and and UniProtKB:Q8IDS3 the same ? It looks the same in Protein2GO; do you know why we would get this listed twice in AmiGO ? Its as if the IDs are not reconciled... ?

**Comment by pgaudet** [comment]
also there is one pombase annotation @ValWood please fix: https://docs.google.com/spreadsheets/d/1lhBpUjWQMNe6gY9oCYZxajwTTlr1L9cE1h7ZiGEBzi8/edit#gid=0

**Comment by alexsign** [comment]
@pgaudet I can see 3 records in the P2GO database from GeneDB:

Q8IDS3		GO:0004584	ECO:0000316	PMID	24489949
Q8IDS3		GO:0005783	ECO:0000314	PMID	12117963
Q8IDS3		GO:0006506	ECO:0000316	PMID	24489949

looks like 3 different annotations to PF3D7_1341600 = Q8IDS3

**Comment by ValWood** [comment]
Does anyone know the actual activities for 



gpi10 | pig-B (predicted)
gpi18 | pig-V, dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase (predicted)

**Comment by ValWood** [comment]
pigB according to UniProt
https://www.uniprot.org/uniprot/Q92521
Mannosyltransferase involved in glycosylphosphatidylinositol-anchor biosynthesis. Transfers the third alpha-1,2-mannose to Man2-GlcN-acyl-PI during GPI precursor assembly.1 Publication
but has GO
glycolipid mannosyltransferase activity

SGD has
alpha-1,2-mannosyltransferase activity

**Comment by ValWood** [comment]
pigV human
https://www.uniprot.org/uniprot/Q9NUD9
glycolipid mannosyltransferase activity

SGD
enables alpha-1,6-mannosyltransferase activity

**Comment by deustp01** [comment]
A useful review, with material on budding yeast - human homology: PMID: 29679465

**Comment by ValWood** [comment]
MT-III (Gpi10),

MT-II (Gpi18)
A second Man is added to the GPI intermediate by MT-II which consists of two subunits, Gpi18 and Pga1 in S. cerevisiae (100,101). Based on homology to Pmt2 family of O- mannosyltransferases, Gpi18 is predicted to be the catalytic sub- unit and Pga1 an accessory subunit (101). Metabolic labeling experiments suggest that (EtnP)Mana1–4GlcNa1–6(2-acyl)inositol- phospholipid is the major intermediate that accumulates in gpi18 mutants and could be its major substrate (100). However, a GPI precursor without EtnP may also be a substrate.

So now I only need to find out what MTII and MTIII refer to!

**Comment by ValWood** [comment]
I can't figure this out but go ahead with the obsoletion anyway - if we can't work it out we'll just go up to mannosyltransferase.

**Comment by pgaudet** [comment]
@uliboehme You should be able to remove 

PFAL | Q8IDS3 | PF3D7_1341600 |   | GO:0004584 | dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity | ECO:0000316(IGI) | ECO:0000316 | (IGI) |   | PMID:24489949 ECO:0000316 | (IGI)

I will remove the IBA annotation. 

Thanks, Pascale

**Comment by hattrill** [comment]
@sjm41 and @phanivg you may want to review PIG-V based on this obsoletion proposal

**Comment by pgaudet** [comment]
I dont see any annotations by FlyBase to this term - did I miss some ?

**Comment by hattrill** [comment]
No - no issue here. It's an ISS with a yeast protein - when Stacia updated the SGD annotation, ours automatically updated in P2GO. But Steven & Phani have an enzyme project on the go (I have a feeling that they've looked over this, but I wanted to double check with them)

**Comment by uliboehme** [comment]
@pgaudet 
Thanks for your message. I've already removed GO:0004584 from PF3D7_1341600 in our annotation database (chado Artemis). I'm not able to remove the GO term from UniProtKB:Q8IDS3.

**Comment by pgaudet** [comment]
Got it. I assume that will be done in the next load 
Is this right @alexsign ?

**Comment by uliboehme** [comment]
Thanks @pgaudet

**Comment by alexsign** [comment]
@pgaudet should be removed after this weekend load.

**Comment by pgaudet** [comment]
Great - this looks like it's all done.

**Comment by sjm41** [comment]
@ValWood  You probably realise this, but note that the 'GPI mannosyltransferases' should not be annotated with any of the 4 activities mentioned at the top of this ticket - those activities describe the actions of the 'dolichyl pyrophosphate mannosyltransferases' (i.e. Alg3, Alg9, Alg12) that act earlier in glycan synthesis.  The two sets of enzymes are distinguished by substrate: dolichol pyrophosphate (PP-Dol) vs dolichol phosphate (P-Dol).

This distinction may be the reason we have the GO:0004584 term, as it's specific for dolichyl-phosphate, and may be a reason for not obsoleting it - I'll mention this on the related ticket.

Synthesizing data from UniProt/EC/SGD/GO, I believe the following summarizes the situation:

**Dolichyl pyrophosphate mannosyltransferases:**

- ALG3/alg3 => GO:0052925	dol-P-Man:Man(5)GlcNAc(2)-PP-Dol alpha-1,3-mannosyltransferase activity (2.4.1.258)
- ALG9/alg9 => GO:0052926	dol-P-Man:Man(6)GlcNAc(2)-PP-Dol alpha-1,2-mannosyltransferase activity (2.4.1.259) & GO:0052918	dol-P-Man:Man(8)GlcNAc(2)-PP-Dol alpha-1,2-mannosyltransferase activity (2.4.1.261)
- ALG12/alg12 => GO:0052917	dol-P-Man:Man(7)GlcNAc(2)-PP-Dol alpha-1,6-mannosyltransferase activity (2.4.1.260)


**GPI mannosyltransferases:**

- PIGM (gpi14/MT-I/GPI mannosyltransferase 1/IPR007704) => alpha-1,4-mannosyltransferase activity / glycolipid mannosyltransferase activity (UniProt: "Transfers the first alpha-1,4-mannose to GlcN-acyl-PI during GPI precursor assembly." (Note - PIG-X/pbn1 is an accessory subunit to PIG-M)
- PIGV (gpi18/MT-II/GPI mannosyltransferase 2/IPR007315) => alpha-1,6-mannosyltransferase activity / glycolipid mannosyltransferase activity (UniProt: "Transfers the second mannose to the glycosylphosphatidylinositol during GPI precursor assembly.")
- PIGB (gpi10/MT-III/GPI mannosyltransferase 3/IPR039521) => alpha-1,2-mannosyltransferase activity / glycolipid mannosyltransferase activity (UniProt: "Transfers the third alpha-1,2-mannose to Man2-GlcN-acyl-PI during GPI precursor assembly.")
- PIGZ (smp3/MT-IV/GPI mannosyltransferase 4) => alpha-1,2-mannosyltransferase activity (UniProt: "Transfers a fourth mannose to some trimannosyl-GPIs during GPI precursor assembly.")
