### ISSUE TITLE
PTN000122012 (PTHR11117) - remove "kinase activity" term?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2873]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000122012

PTHR11117 is for the conserved "SUCCINYL-COA LIGASE SUBUNIT ALPHA".

PTN000122012 includes the expected/canonical MF of "succinate-CoA ligase (ADP-forming) activity" (supported by 3 source annotations) and related BP terms.

But it also includes a unexpected MF of "nucleoside diphosphate kinase activity", supported by a single annotation to the Pseudomonas aeruginosa sucD protein (with the related BP term) from PMID:10671455.

I'm not aware that this second enzymatic activity has been established in any other species, or that it is reasonable to expect it's conserved from Pseudomonas to humans?

Unless others know different, it may be best to remove the "nucleoside diphosphate kinase activity" and "nucleoside triphosphate biosynthetic process" terms from this PAINT node and restrict the GO terms to the established functions?

(I don't see this propagation on the PANTHER family for the beta subunit - PTHR11815)
 

@hattrill

**Comment by pgaudet** [comment]
Removed.

**Comment by sjm41** [comment]
Thanks!
