### ISSUE TITLE
 IPR039278   red1 not RNA binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2876]
I don't see any evidence that red1 binds RNA directly.
Do you have a reference?

**Comment by EBI-Hsinyu** [comment]
Hi, 
I think this term might be from Uniprot (http://sp.isb-sib.ch/uniprot/O60293). However, there is no evidence of direct RNA binding. I will remove this term. 
Hsin-Yu

**Comment by ValWood** [comment]
OK I alerted UniProt too.
