### ISSUE TITLE
InterPro2GO for GPI mannosyltransferases

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2877]
Related to #2872:

Should wait for final resolution of that ticket (and related geneontology/go-ontology#16022), but we may be able to add some more specific InterPro2GO terms for the GPI mannosyltransferases:

**GPI mannosyltransferase 1 (IPR007704)**
PIG-M has a DXD motif. The DXD motif is found in many glycosyltransferases that utilise nucleotide sugars. It is thought that the motif is involved in the binding of a manganese ion that is required for association of the enzymes with nucleotide sugar substrates 

- current MF: transferase activity, transferring hexosyl groups (GO:0016758)
- consider changing to: alpha-1,4-mannosyltransferase activity (GO:0051751) & glycolipid mannosyltransferase activity (GO:0004376)

==

**GPI mannosyltransferase 2 (IPR007315)**
This entry represents GPI mannosyltransferase 2, also known as PIG-V in humans or Gpi18 in fungi. PIG-V is a mannosyltransferase that transfers the second mannose in glycosylphosphatidylinositol (GPI) biosynthesis [1, 2, 3]. GPI is a glycolipid that anchors many proteins to the eukaryotic cell surface [1].

- current MF: dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity (GO:0004584)
- changed in #2872 to: mannosyltransferase activity (GO:0000030)
- consider changing to: alpha-1,6-mannosyltransferase activity (GO:0000009) & glycolipid mannosyltransferase activity  (GO:0004376)

==

**GPI mannosyltransferase 3 (IPR039521)**
Many eukaryotic cell surface proteins are bound to the membrane via the glycosylphosphatidylinositol (GPI) anchor. The GPI anchor precursor is synthesized in the endoplasmic reticulum (ER) by sequential enzymatic reactions. PIG-B is a mannosyltransferase that transfers the third alpha-1,2-mannose to Man2-GlcN-acyl-PI during GPI precursor assembly [1]. Gpi10 is the functional homologue in yeast [2].

- current MF: mannosyltransferase activity (GO:0000030)
- consider changing to: alpha-1,2-mannosyltransferase activity (GO:0000026) & glycolipid mannosyltransferase activity (GO:0004376)

==

@happy-lorna 
@hattrill 
@typhainepl

**Comment by sjm41** [comment]
FYI: The dependent tickets have now been resolved/closed, so it's now 'safe' to review the InterPro2GO annotations mentioned above.

**Comment by typhainepl** [comment]
@sjm41, are those newly created GO terms?
Could you provide the GO identifier?

**Comment by sjm41** [comment]
Oops, sorry I omitted the IDs - I've just edited the original post to include them.

**Comment by typhainepl** [comment]
Thank you, I have updated the InterPro entries. The changes will be visible in the next InterPro release (79.0).
