### ISSUE TITLE
PTN000847539 Check patch annotations

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2879]
patch is a negative regulator of the smoothened signaling and should be annotated to "negative regulation of smoothened signaling pathway GO:0045879" rather than directly to the pathway itself.

Could you check the source annotations

PTN000083918	(MOUSE|MGI=MGI=105373|UniProtKB=Q61115) @ukemi 
PTN002473801	(HUMAN|HGNC=9585|UniProtKB=Q13635) (disputed in P2GO)
PTN000083955	(DANRE|ZFIN=ZDB-GENE-980526-44|UniProtKB=Q98864) @sabrinatoro

and update the term where poss. Thanks.

**Comment by marcfeuermann** [comment]
Done with issue #4196
