### ISSUE TITLE
PAINT annotations for "mitochondrion inheritance"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2881]
Pombe should not have annotations to this term. This isn't an active process in fission yeast.
The mitochondria are tethered to the membrane which results in equal segregation, but not an active process. There is a process to get mitochondria into the bud in budding yeast, but I think most of these annotations are really phenotypes

I used

GO:0051659 | maintenance of mitochondrion location

phb1 | prohibitin Phb1 (predicted) |   | mitochondrion inheritance |   | PomBase | Schizosaccharomyces pombe | ISO | SGD:S000003364 | prohibitin pthr23222 | protein |   | GO_REF:0000024 | 20080204
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | num1 | cortical anchoring factor for dynein Mcp5/Num1 |   | mitochondrion inheritance |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000833803SGD:S000002557 | family not named pthr28190 | protein |   | PMID:21873635 | 20170228
  | mdm12 | ERMES complex subunit Mdm12 |   | mitochondrion inheritance |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN002000262SGD:S000005369 | family not named pthr28204 | protein |   | PMID:21873635 | 20170228
  | mdm31 | mitochondrial inner membrane protein Mdm31 |   | mitochondrion inheritance |   | InterPro | Schizosaccharomyces pombe | IEA | InterPro:IPR012571 | family not named pthr31068 | protein |   | GO_REF:0000002 | 20191214
  | mdm31 | mitochondrial inner membrane protein Mdm31 |   | mitochondrion inheritance |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000776322SGD:S000001237SGD:S000005673 | family not named pthr31068 | protein |   | PMID:21873635 | 20170228
  | dnm1 | mitochondrial dynamin family scission GTPase Dnm1 |   | mitochondrion inheritance |   | PomBase | Schizosaccharomyces pombe | IMP |   | dynamin pthr11566 | protein |   | PMID:19373772 | 20140911
  | dnm1 | mitochondrial dynamin family scission GTPase Dnm1 |   | mitochondrion inheritance |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN002480318PomBase:SPBC12C2.08SGD:S000003924 | dynamin pthr11566 | protein |   | PMID:21873635 | 20170928

**Comment by ValWood** [comment]
duplicate of 
https://github.com/geneontology/go-annotation/issues/2749

**Comment by marcfeuermann** [comment]
IBAs have all been corrected.
