### ISSUE TITLE
PTN000784925 (PTHR24419)  - inclusion of fly 'tube' protein.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2889]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000784925

PTN000784925 adds 'protein serine/threonine kinase activity' to members of the INTERLEUKIN-1 RECEPTOR-ASSOCIATED KINASE (PTHR24419) family.

The fly members of this famiily are:
1. DROME|FlyBase=FBgn0010441|UniProtKB=Q05652	SERINE/THREONINE-PROTEIN KINASE PELLE (PTHR24419:SF33)
=> This is 'pelle', a known S-T kinase => OK

2. DROME|FlyBase=FBgn0046706|UniProtKB=P83103	SERINE/THREONINE-PROTEIN KINASE HASPIN (PTHR24419:SF18)
=> This is 'Haspin', has kinase domains, orthologs known to be kinases => OK

3. DROME|FlyBase=FBgn0003882|UniProtKB=P22812	SERINE/THREONINE-PROTEIN KINASE HASPIN (PTHR24419:SF18)
=> this is 'tube', an adaptor protein with no kinase domains (e.g. PMID:11731453) => not OK

Can the kinase term be blocked for fly 'tube' (P22812)?  Or should this be a ticket for the separate PANTHER tree tracker?

@hattrill

**Comment by sjm41** [comment]
@pgaudet @marcfeuermann  - any thoughts on this one?  Is it on the right tracker?

**Comment by sjm41** [comment]
Looks like the kinase term on this node has changed from 'protein serine/threonine kinase activity' to 'histone kinase activity (H3-T3 specific)', but the problem with adding the annotation to Drosophila 'tube' (P22812) remains. Can this be blocked?

**Comment by marcfeuermann** [comment]
It is indeed the right tracker.This family needed a big update. I've cleaned the annotation and blocked kinase-related annotation for Drosophila 'tube' (P22812).

**Comment by sjm41** [comment]
Many thanks Marc!

**Comment by sjm41** [comment]
Hi @marcfeuermann I see this node still has (or has newly acquired) a "histone kinase activity (H3-T3 specific)" annotation that is now getting propagated to Drosophila 'tube' (P22812).  Can you block that propagation too please?

**Comment by pgaudet** [comment]
Annotations have been blocked, see screenshot. I think we suffer from a long lag since the last release!

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/4782928/114870128-18e45700-9df8-11eb-9f5e-3dbd6434148a.png">

**Comment by sjm41** [comment]
OK, thanks.

**Comment by sjm41** [comment]
The erroneous "protein serine/threonine kinase activity" annotation to fly 'tube' via PTN000784925 (PTHR24419) has returned....

Same problem with PTN002401141 (associated with same family, PTHR24419)

**Comment by marcfeuermann** [comment]
OMG I'm turning nuts...
I've removed it once again. Another "unstable" family to follow more closely.
