### ISSUE TITLE
PTN000021458 (PTHR10182) - remove 'kinase activity' term.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2890]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000021458

PTN000021458 adds 'contributes_to protein serine/threonine kinase activity' to members of the CALCIUM-BINDING PROTEIN 39-RELATED (PTHR10182) family.

This is based on two source annotations:
PTN002468781 (HUMAN|HGNC=20292|UniProtKB=Q9Y376) PMID:24393035 (PARL)
PTN002229625 (RAT|RGD=1306390|UniProtKB=A0A0G2JZH0) PMID:14511394 (RGD)

I think both those source annotations should be changed to "protein serine/threonine kinase activator activity".
The MO25 (aka CAB39) subunit is defined as an accessory/scaffold subunit with no kinase activity itself, though these papers show it stimulates the activity of kinases with which it forms a complex.

I've disputed the human annotation in protein2GO.
@slaulederkind  - can you review the rat annotation?

Thanks.

tagging @hattrill

**Comment by pgaudet** [comment]
Fixed PAINT 
@slaulederkind @gthayman Can someone from RGD look at this annotation ? 

Thanks, Pascale

**Comment by sjm41** [comment]
For the record - Ruth has fixed the human annotation.

**Comment by slaulederkind** [comment]
The rat annotation has been removed.

**Comment by sjm41** [comment]
Thanks Stan, Pascale - closing.
