### ISSUE TITLE
PTN000038857 (PTHR10343) - remove 'kinase activity'

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2891]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000038857

PTN000038857 adds 'contributes_to AMP-activated protein kinase activity' to members of the "5'-AMP-ACTIVATED PROTEIN KINASE , BETA SUBUNIT (PTHR10343)" family, which are non-catalytic subunits.

This is based on a single source:
PTN000038878 (RAT|RGD=71057|UniProtKB=P80386)
with the same GO annotation being made to 2 refs: PMID:14511394 & PMID:15695819.

In both cases, I think the GO term should probably be changed to "protein serine/threonine kinase activator activity".

@slaulederkind  - can you review please?

Thanks

@hattrill

**Comment by slaulederkind** [comment]
Rat annotation has been removed.

**Comment by sjm41** [comment]
Thanks Stan - closing.

**Comment by pgaudet** [comment]
I'd like to review the family anyway.

**Comment by sjm41** [comment]
The 'kinase activity' term has now disappeared from the PAINT node.
@pgaudet - do you still want to keep this ticket open?

**Comment by sjm41** [comment]
Hi @pgaudet - just checking if we can close this one?

**Comment by pgaudet** [comment]
Yes, this is fixed, thanks.

**Comment by sjm41** [comment]
This issue has also re-appeared....

PTN000038857 now adds "AMP-activated protein kinase activity(CONTRIBUTES_TO)" to 5'-AMP-ACTIVATED PROTEIN KINASE , BETA SUBUNIT (PTHR10343) members, which are non-catalytic subunits.  Please remove.

**Comment by marcfeuermann** [comment]
Removed !
