### ISSUE TITLE
PTN001464650 (PTHR21064) edit

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2893]
http://www.pantree.org/node/annotationNode.jsp?id=PTN001464650

PTN001464650 adds both 'amino acid kinase activity' and 'kinase activity' to members of the UNCHARACTERIZED (PTHR21064) family.

This is based on single "homoserine kinase activity (GO:0004413)" (which is a child of 'amino acid kinase activity') annotation to a Pseudomonas aeruginosa protein:
PTN002326068 (PSEAE|EnsemblGenome=PA5495|UniProtKB=P29364)

Most species (including fly and all mammals) have a single member in the PTHR21064 family - for humans, it's HYKK (UniProt A2RU49) = Hydroxylysine kinase

As the name suggests, this human protein is annotated with "hydroxylysine kinase activity" (GO:0047992) (from PMID:22241472)

"hydroxylysine kinase activity" is not a child of "amino acid kinase activity" in the GO.
Assuming that's correct, then the GO term on the PAINT node should be changed to just be 'kinase activity'.

Alternatively, you might be able to add "homoserine kinase activity" to a new node for 	PTHR21064:SF4, and add "hydroxylysine kinase activity" to new node for PTHR21064:SF1.

@hattrill

**Comment by marcfeuermann** [comment]
What can I say. Hydroxylysine is an amino acid (hydroxylated lysine), so  "hydroxylysine kinase activity" should be a child of "amino acid kinase activity" in GO.  And this is why we have propagated this term. The human annotation is not available yet for PAINT propagation. I propose to keep the annotation and complete it when more data will be available.

**Comment by sjm41** [comment]
_Hydroxylysine is an amino acid (hydroxylated lysine), so "hydroxylysine kinase activity" should be a child of "amino acid kinase activity" in GO._

Yes, I was also wondering about that - that was my "assuming that's correct" caveat above...
Wikipedia agrees with you: https://en.wikipedia.org/wiki/Hydroxylysine

I shall make a new ticket on the other tracker to ask for the new parent child relationship and then close this ticket.

**Comment by marcfeuermann** [comment]
Okay, thank you :-)

**Comment by sjm41** [comment]
Here's the new ticket:
https://github.com/geneontology/go-ontology/issues/19121

**Comment by sjm41** [comment]
Sorry Marc, one other thing on this one:
Why does PTN001464650 adds both 'amino acid kinase activity' and 'kinase activity'? Why not just need the former?

**Comment by marcfeuermann** [comment]
Hi Steven,
No worry. Usually, when we propagate a child term, the parent is automatically removed, which seems not to be the case here. I've removed it manually. @pgaudet, @huaiyumi, a comment ?
