### ISSUE TITLE
Proposal to retrofit annotations with contributes_to qualifier to align with use guidelines

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2897]
New guidelines #1650 have been available for the use of contributes_to since summer 2019.

Existing annotations should be updated to reflect this (in many cases the qualifier is used incorrectly when annotating enzyme complex subunits). These should be updated to be adhere to the guidelines #1650. 

The mis-match between guidelines and annotations is causing many issues e.g. #2894

A retrofit would help bring groups up-to-speed on the new rules and help work out any issues.

Before a retrofit can be actioned, we need to:
1. Define the scope of the retrofit (e.g. all MFs or just enzymatic)
2. Assess the extent of the use and misuse,
3. See if a computational approach could be used to identify/exclude candidates or even semi-automate a retrofit
4. Make a clear retrofit protocol/decision chart to help curators with the retrofit

We shall have to make a clear time-line for completing this task - it is quite a large task. Let's aim to have some of these points addressed by the virtual GOC meeting in May so we can see if there is any consensus from the wide consortium.

tagging @sjm41 @bmeldal @RLovering @ValWood @pgaudet @vanaukenk @sylvainpoux

**Comment by bmeldal** [comment]
@hattrill do you want to organise slot for a TC?

Next week is our virtual PSI consortium mtg, Mon-Thu, 3-10 pm UK time. I only have to dip in and out though.

**Comment by hattrill** [comment]
Yes, that would be good. I will confer with Kimberly et al and see when we could slot it in. Perhaps start around the week of the 6th April, to give everyone time to adjust to their new working routines! (And alllow a settling in period for those whom will be enjoying the extensive company of their kids!)

**Comment by bmeldal** [comment]
Yup, today is the last day my kids are at school. I'm dreading next week. I'll not be working in the mornings apart from our 9 am team skype calls so I can get us into some routine. But our TCs would be PM anyway when I let the kids play/get "plugged in". 

My husband is in recruitment, wall-to-wall phone and video calls... (they still recruit as they are in software dev!)

**Comment by hattrill** [comment]
Yes, we will be having a 'family meeting' at the weekend to make a weekday timetable so that everyone is happy(ish) :)

**Comment by RLovering** [comment]
I think you should point people to this page http://wiki.geneontology.org/index.php/Contributes_to and if this is not accurate get this page improved.

Good to hear that men and women are sharing the child care responsiblities where possible ;) and thus their employers are sharing the financial implications

**Comment by bmeldal** [comment]
> Good to hear that men and women are sharing the child care responsibilities where possible ;) and thus their employers are sharing the financial implications

In our case it's the nature of the work rather than the gender :( As I will be working more in the afternoon/evening (assuming the kids concentrate better in the mornings) he'll be doing the cooking! (He's the better cook anyway!) - Although, my home office is now the kitchen table! x

**Comment by suzialeksander** [comment]
@pgaudet what is the status of this? Is the contributes_to documentation something we can address on an upcoming call or is there more that needs to be done first?

**Comment by pgaudet** [comment]
@hattrill (and maybe @sjm41 ) 

is this now 'good enough' for closing? I assume we never expect 100% perfect/right.

**Comment by hattrill** [comment]
Yes, let's close it.
