### ISSUE TITLE
IPR015727 - remove 'protein kinase C activity'?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2898]
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR015727/

Protein kinase C mu-related (IPR015727) is associated with "protein kinase C activity (GO:0004697)" and relates to "The protein kinase D family of enzymes consists of three isoforms: PKD1 (PKCmu), PKD2, and PKD3 (PKCnu)."

"protein kinase C activity" is defined as "Catalysis of the reaction: ATP + a protein = ADP + a phosphoprotein. This reaction requires diacylglycerol."

But the reference given in the InterPro description (PMID: 12829240) seems to say that the PKD proteins are no longer classed as PKC family members and that their kinase activity does not directly require diacylglycerol (they get activated directly by PKC enzymes) - see extracts copied below.

I think the GO term should be replaced with a more general term, probably "protein serine/threonine kinase activity (GO:0004674)"

@hattrill @happy-lorna @typhainepl 

==
From PMID: 12829240:

Initially, PKCmu and PKCnu were labeled as members of the PKC family [2], creating a new subgroup of the PKCs. However, their only similarity to other PKCs resides in a C1 domain that is homologous to the DAG binding domain of other PKC enzymes, and they lack the C2 domain responsible for Ca2+ sensitivity of the conventional PKC subgroup [1,2]. Additionally, in contrast to PKC family members, the catalytic domain of PKD shows a very low homology to the conserved kinase domain of the PKCs and displays a distinct inhibitor and substrate specificity [5^7]. The NH2-terminal part of PKD contains a pleckstrin homology (PH) domain and lacks the typical autoinhibitory pseudosubstrate motif present in PKCs [1]. These differences made it difficult to classify PKD1, 2 and 3 in the PKC family and recently they were classified as a novel subgroup of the calcium/calmodulin-dependent protein kinase (CAMK) family, based on sequence similarities of the kinase domain [8].

Several agents are known to activate PKD1 through the activation of phospholipase C (PLC),

Although the second cysteine-rich domain of PKD binds directly to DAG, this is not the main activation mechanism following stimulation of PLC. In case of classical and novel PKCs, a pseudo-substrate sequence is replaced from the substrate binding site during DAG binding, creating an active enzyme. However, this PKC activation is not retained during immunoprecipitation, because DAG is released. Since PKD preserves its activity after being immunoprecipitated, and because of the absence of such a pseudosubstrate domain, it seems that DAG binding in PKD mainly serves to localize the enzyme to specific cellular targets. The activation itself is predominantly mediated by phosphorylation events.

**Comment by typhainepl** [comment]
I agree, GO:0004674 is more appropriate. I've updated the InterPro entry.

**Comment by sjm41** [comment]
Great, thanks.  I'll close.
