### ISSUE TITLE
Exclude Fly Imaginal disc growth factor genes from PANTHER:PTN000126545 node #16

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#2899]
Fly Imaginal disc growth factor genes (Idgf1-Idgf6) are Chitinase-like family members. These proteins were given chitinase activity (GO:0004568) based on PANTHER:PTN000126545 node, but PMID:18342251 suggests that fly Idgf6 (FBgn0013763 / Q23997) lacks the critical residue required for chitinase activity.
Human orthologs CHI3L1 and CHI3L2 are also suggested to lack chitinase activity.
Can you please exclude propogation by PAINT from this node to these following FlyBase members.

FLYBASE_ID SYMBOL UUNIPROT_ID
FBgn0020416 Idgf1 Q8MM24
FBgn0020415 Idgf2 Q9V3D4
FBgn0020414 Idgf3 Q8MLZ7
FBgn0026415 Idgf4 Q9W303
FBgn0064237 Idgf5 Q8T0R7
FBgn0013763 Idgf6 Q23997

@hattrill

**Comment by pgaudet** [comment]
@phanivg Do you want to exclude only chinase activity, or also imaginal disc growth/development and other annotations ?

**Comment by hattrill** [comment]
Not chitinase activity - have plenty of that. It's just this subset of the glycosylhydrolase family 18 that have lost the activtiy. 
http://flybase.org/reports/FBgg0000514

**Comment by hattrill** [comment]
Can you do that for all Idgf orthologs in other Drosophila species?

**Comment by pgaudet** [comment]
What other Drosophila species do we have ? We have other flies, but I am not sure I see other drosophilas: 

<img width="395" alt="image" src="https://user-images.githubusercontent.com/4782928/77323908-43a7cd00-6d16-11ea-9407-3da49ce5a7ee.png">

**Comment by hattrill** [comment]
I assumed that you would cover them - do you not include them in the propagation?

**Comment by pgaudet** [comment]
Those are the species covered: 
http://www.pantherdb.org/panther/summaryStats.jsp

**Comment by pgaudet** [comment]
Fixed.
