### ISSUE TITLE
interpro2go IPR000685->RuBisCo GO terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#29]
I think the following interpro2go mappings may need to
be adjusted since they result in translations to
'ribulose-bisphosphate carboxlyase' related GO terms in
Zebrafish genes as well as several other vertebrate
species.  It is my understanding that none of these
species have a 'RuBisCo' complex or activity as this is
related to photosynthesis in some way...

InterPro:IPR000685 Ribulose bisphosphate carboxylase,
large chain &gt; GO:ribulose-bisphosphate carboxylase
activity ; GO:0016984
InterPro:IPR000685 Ribulose bisphosphate carboxylase,
large chain &gt; GO:carbon utilization by fixation of
carbon dioxide ; GO:0015977
InterPro:IPR000685 Ribulose bisphosphate carboxylase,
large chain &gt; GO:ribulose bisphosphate carboxylase
complex ; GO:0009573 

-Doug 

Reported by: doughowe

Original Ticket: "geneontology/annotation-issues/29":https://sourceforge.net/p/geneontology/annotation-issues/29

**Comment by cmungall** [comment]
[I'm reopening this though not sure if I should make a new ticket]

Perhaps something got miscommunicated in this ticket, but it looks like IPR000685 has *lost* the link to the rubisco function:

http://www.ebi.ac.uk/interpro/entry/InterPro/IPR000685

It looks like the original request from @doughowe was driven my mistaken zebrafish annotation with this domain, but this seems resolved

![image](https://user-images.githubusercontent.com/50745/118200919-1f6fe980-b40b-11eb-8bae-025c4bddd0ca.png)

**Comment by cmungall** [comment]
opened a new ticket: 3815
