### ISSUE TITLE
Review annotations to GO:0007016 cytoskeletal anchoring at plasma membrane

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2902]
Hello, 

The proposal has been made to obsolete GO:0007016 cytoskeletal anchoring at plasma membrane, because it represents a function, see https://github.com/geneontology/go-ontology/issues/19119. Please review annotations: 

https://docs.google.com/spreadsheets/d/1ZYh2nKh0XGJrXx7221iZoIELlEOdeyjfCLqIp9x4_dY/edit#gid=0

Contributor | Number of annotations
-- | --
BHF-UCL | 3
dictyBase | 1
FlyBase | 11
MGI | 2
PINC | 2
UniProt | 7
WB | 2

Thanks, Pascale

**Comment by pgaudet** [comment]
Please review InterPro annotations

3 InterPro mappings
InterPro:IPR015224
InterPro:IPR030691
InterPro:IPR008465

**Comment by ValWood** [comment]
Most would use
"GO:0106006   cytoskeletal protein-membrane adaptor activity

some do not appear to be involved in anchoring, at least from the cited paper  (see https://github.com/geneontology/go-ontology/issues/19119)

**Comment by pgaudet** [comment]
UCL done, see https://github.com/geneontology/go-ontology/issues/19119#issuecomment-603490168

**Comment by hattrill** [comment]
FB done

**Comment by typhainepl** [comment]
InterPro done

**Comment by pfey03** [comment]
done dictyBase

**Comment by vanaukenk** [comment]
WB annotations updated.

By definition, the suggested MF didn't apply to the gps annotated, but I changed the BP annotation to:

cortical actin cytoskeleton organization (GO:0030866)

**Comment by pgaudet** [comment]
MGI @hdrabkin 
UniPror @pgarmiri 
Can you please review your annotations? 

Thanks, Pascale

**Comment by ValWood** [comment]
Nice overview in 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6829894/

<img width="1040" alt="Screenshot 2020-03-30 at 17 57 54" src="https://user-images.githubusercontent.com/7359272/77940131-22178a00-72b0-11ea-8279-41b63b136728.png">

**Comment by pgarmiri** [comment]
Hi,
 The UniProt annotations have been revised. 
Thanks,
 Penelope

**Comment by pgaudet** [comment]
Thanks everyone !
