### ISSUE TITLE
 IPR041752 isn't mitochondrial respiratory chain complex IV 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2907]
coa3 | GO:0005751 | mitochondrial respiratory chain complex IV | IEA with IPR041752

coa3 is 
cytochrome c oxidase assembly protein
but not part of IV

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
You are right. It is involved in mitochondrial respiratory chain complex IV assembly (GO:0033617) rather being part of the complex. I have replaced the GO term. 
Regards, 
Hsin-Yu
