### ISSUE TITLE
TIM22 mitochondrial import inner membrane insertion complex | IEA with IPR039094 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2908]
Tim9| GO:0042721 | TIM22 mitochondrial import inner membrane insertion complex | IEA with IPR039094 

Tim9 isn't TIM22 mitochondrial import inner membrane insertion complex

it's
Tim9-Tim10 complex
which in GO is
oddly named as
GO:0042719    mitochondrial intermembrane space protein transporter complex

Soluble complex of the mitochondrial intermembrane space composed of various combinations of small Tim proteins; acts as a protein transporter to guide proteins to the Tim22 complex for insertion into the mitochondrial inner membrane. PMID:12581629

**Comment by typhainepl** [comment]
Hi, thanks for highlighting this. I have updated the InterPro entry.
