### ISSUE TITLE
List of SARS-CoV-2 target proteins

### ISSUE THREAD

**Issue by typhainepl** [geneontology/go-annotation#2909]
Hi, 

At InterPro, we've come across this nice page of human proteins targeted by SARS-CoV-2 http://www.geneontology.xyz/covid-19.html.

Could you provide the list of corresponding UniProt accessions?

**Comment by ValWood** [comment]
@cmungall ?
@kltm

**Comment by ValWood** [comment]
Hi @typhainepl typhaine NOt sure who created the page but Chris or Seth will know...

**Comment by lpalbou** [comment]
I did but I am unsure how you came across that page as this is on a development site (geneontology.xyz and not geneontology.org). @typhainepl was it through google search ?

The list of human proteins targeted by the virus is available as a [supplementary material](https://www.biorxiv.org/content/biorxiv/early/2020/03/23/2020.03.22.002386/DC4/embed/media-4.xlsx?download=true) of [that article](https://www.biorxiv.org/content/10.1101/2020.03.22.002386v2.supplementary-material).

If you need a json format of that list (human targets clustered by virus gene), you can access it through a temporary link: http://geneontology.xyz/data/sars-cov-2_targets.json

Note: while the page gets validated by our PIs / managers, I have temporarily restricted the access

**Comment by cmungall** [comment]
@lpalbou created this. It's a demo/mockup, it wasn't intended for general release.

It looks like someone has made this password protected. IMO this is too much. We are an open group and things should be done transparently. It's sufficient to put a banner at the top.

Regarding the original question, we plan to include the viral protein IDs from the GPI pre-release, see https://github.com/Knowledge-Graph-Hub/kg-covid-19/issues/31#issuecomment-606080346

**Comment by pgaudet** [comment]
In any case we should be ready to release it soon (in a few days??) so a password may be OK for now?

**Comment by typhainepl** [comment]
Thanks, the Excel document does the job, as we just need the list of UniProt accessions. 

We are currently reviewing the InterPro entries matching the viral proteins.
