### ISSUE TITLE
Exclude Fly 'rgn' from PAINT node PANTHER:PTN000542974 - PTHR22993

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#2911]
The fly 'rgn' (regeneration/FBgn0261258) protein is more likely a C-type lectin member based on the available evidence (PMID:16475980) and its domain architecture while based on DIOPT orthology search shows very weak or no orthology with the evidence annotations of this PAINT node PANTHER:PTN000542974. 
Please exclude Fly rgn/regeneration/FBgn0261258/Q9Y102,M9PFV8 from this propagation.

@hattrill 
@sjm41

**Comment by pgaudet** [comment]
Fixed. This sequence does not seem to belong in the tree, I'll report it in the Panther tracker. 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet 
Can I check on the status of this one - above you said it was fixed, but you also made a ticket in the Panther tracker.  Do we have to wait for that Panther ticket to be resolved before 'rgn' is not annotated via PTN000542974?

**Comment by pgaudet** [comment]
Thanks for the reminder 
https://github.com/pantherdb/Helpdesk/issues/31
