### ISSUE TITLE
Atg15 NOT GOlgi KW-0333

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2913]
https://www.uniprot.org/uniprot/O13934
GO:0005794 | Golgi apparatus | IEA with KW-0333 | GO_REF:0000043

**Comment by sylvainpoux** [comment]
Hi Val,

Marc (@marcfeuermann) will know more about this.. Marc could you have a look and correct this annotation if necessary?

Thanks

Sylvain

**Comment by marcfeuermann** [comment]
Atg15 reaches the vacuolar lumen after transit through the ER and Golgi apparatus in a way similar to that of the MVB pathway. As ER and Golgi are not the compartments where atg15 is active but only "transitory" compartments, I propose to remove  both ER and Golgi from all atg15 orthologs.
