### ISSUE TITLE
InterPro:IPR017194 TGFbeta signaling

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2914]
InterPro:IPR017194 is associated with:

GO:0007179  transforming growth factor beta receptor signaling pathway

Could you change this to the more general term (which is true for all Transforming growth factor-beta receptor, type II receptors):

GO:0007178 transmembrane receptor protein serine/threonine kinase signaling pathway

as GO:0007179 is specific for the TGFbeta branch of signaling rather than the superfamily (which encompasses BMP, activin and other TGFbeta superfamily receptors - which are not present in all metazoans).

**Comment by hattrill** [comment]
tagging @happy-lorna

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have replaced this GO term as you suggested. 
Regards,
Hsin-Yu
