### ISSUE TITLE
InterPro2GO - IPR006116 & IPR006117

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2915]
2-5-oligoadenylate synthetase, N-terminal (IPR006116)
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR006116/

This has a current catalytic GO term of "transferase activity (GO:0016740)".
But associated ECs are much more specific: 2.7.7.-, 2.7.7.72, 2.7.7.84

(i) From a quick check (please confirm), looks like the EC xrefs should/could be slimmed down to just 2.7.7.84 (https://enzyme.expasy.org/EC/2.7.7.84)

(ii) The "transferase activity" GO term should be replaced either with "GO:0016779 nucleotidyltransferase activity" (to match ECs are: 2.7.7.-) or "GO:0001730 2'-5'-oligoadenylate synthetase activity" if you decide the more specific EC:2.7.7.84 xref is correct.

Also compare http://www.ebi.ac.uk/interpro/entry/InterPro/IPR006117/

**Comment by sjm41** [comment]
@hattrill

**Comment by hattrill** [comment]
@happy-lorna

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. Unfortunately, these entries need to be revised as more information are available now. I have created/separated some of these entries and added the GO terms you recommended accordingly. I suggest that it is better to have a look again after our release (InterPro 79.0). Moreover, there are some inactive enzyme in these entries. Perhaps Uniprot could block the GO term accordingly. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu
Could you list the new/separated entries on this ticket so we know which ones to check after your next release? (and when is the release due?)
Cheers,
Steven.

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 
The next public release (79) is scheduled for April 23rd. I will send you the entries when our release is out. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Sounds good, thanks.

**Comment by sjm41** [comment]
Hi Hsin-Yu,
I see r79 came out last week - do you have a list of the new entries mentioned earlier in the ticket please?
Thanks,
Steven.

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 

The GO term for IPR006116 has been changed to GO:0016779. The signature for this entry is now cd05400. The previous signature, PS00832, has been used to create a new entry, IPR043518. Hope this helps. 

Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu. Looks good.
