### ISSUE TITLE
Review annotations to GO:0033662 modulation by symbiont of host defense-related protein level and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2916]
Hello, 

GO:0033662 modulation by symbiont of host defense-related protein level and children
will be obsoleted. 

Review annotations here: 
https://docs.google.com/spreadsheets/d/1K2d59ievsZPoWqspYhAyhDTWIeS4SIBULZCbn1fo0e4/edit#gid=0

Impacts 
AgBase @pgaudet - remove
JCVI @pgaudet 
CACAO @sandyl27 

Thanks, Pascale

**Comment by pgaudet** [comment]
@sandyl27 Can you please review the CACAO annaotions ?

**Comment by sandyl27** [comment]
I'm not working on any CACAO stuff anymore. I am a grad student now in a
different lab.

On Wed, Apr 15, 2020 at 10:31 AM pgaudet <notifications@github.com> wrote:

> @sandyl27
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandyl27&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=704vRw1OWAOj5VlcFf4paxbepRfolP7FsDIkvmjxKi0&m=CutNWuOmJy7Fr6ZmHsHt3xvo9c5EZ-Z3X-Fb0Bi1YNM&s=I1Pc15DkK7ukfWuMWlXclwlVzQX0sG4gNBvZYfzNM_s&e=>
> Can you please review the CACAO annaotions ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geneontology_go-2Dannotation_issues_2916-23issuecomment-2D614109950&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=704vRw1OWAOj5VlcFf4paxbepRfolP7FsDIkvmjxKi0&m=CutNWuOmJy7Fr6ZmHsHt3xvo9c5EZ-Z3X-Fb0Bi1YNM&s=WvYgTRi6IR-ZGuCBor3tyG9BFrLmInQM_d4EfOmG848&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AC37YJM3NMY2IWRLBNP56SDRMXHMFANCNFSM4L4G2ZIQ&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=704vRw1OWAOj5VlcFf4paxbepRfolP7FsDIkvmjxKi0&m=CutNWuOmJy7Fr6ZmHsHt3xvo9c5EZ-Z3X-Fb0Bi1YNM&s=h7VwuBnImKXi6KxR8H_5rwKoq-1RlFDj7546nl_Wm4o&e=>
> .
>


-- 
Sandy LaBonte
Graduate Teaching Assistant
Texas A&M University
