### ISSUE TITLE
bir1 (survivin) NOT apoptotic (PAINT), and nor spindle assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2918]
For bir1 I think the apoptotic annotations are  neo-functionalization in the metazoan lineage.
Should not be transferred to yeast which do not enter apoptotic pathway from spindle defects.
Thanks
Val

	bir1	survivin, Bir1		negative regulation of cysteine-type endopeptidase activity involved in apoptotic process		GO_Central	Schizosaccharomyces pombe	IBA	FB:FBgn0015247
FB:FBgn0260635 	inhibitor of apoptosis pthr10044	protein		PMID:21873635	20190327

**Comment by ValWood** [comment]
\
ing  annotations to  mitotic spindle assembly from


bir1 | survivin, Bir1 |   | mitotic spindle assembly |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000005168ZFIN:ZDB-GENE-030826-2 | inhibitor of apoptosis pthr10044 | protein |   | PMID:21873635 | 20170228

we think this is OK, but should be "regulation"?

**Comment by ValWood** [comment]
In fact deleting comment above. We think  survivin is not involved in assembly. It is  involved in 

GO:0061805   mitotic spindle elongation (spindle phase three)


this isn't part of "assembly", the spindle assembly  includes spindle elongation in pro metaphase, but not  phase 3 spindle elongation  which occurs during chromosome segregation.

Mitotic bipolar spindle assembly begins with spindle microtubule nucleation from the separated spindle pole body, includes spindle elongation during prometaphase, and is complete when all kinetochores are stably attached the spindle, and the spindle assembly checkpoint is satisfied.

So this annotation should not be transferred either. The annotation is probably too specific for the assay (I  didn't check)

**Comment by ValWood** [comment]
(I discussed this with Takashi Toda, spindle expert)

**Comment by marcfeuermann** [comment]
Family reviewed.
