### ISSUE TITLE
InterPro2GO for "ATPase, V1 complex, subunit S1" (IPR008388)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2919]
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR008388/

From the InterPro def:
This entry represents the S1 subunit (or subunit AC45) found in the V1 complex of V-ATPases... This subunit may assist the V-ATPase in the acidification of neuroendocrine granules [9].

This is characterised as an "accessory subunit" (i.e. no inherent catalytic activity itself), so I think the two associated MF terms should be removed:
proton-transporting ATP synthase activity, rotational mechanism (GO:0046933)
proton-transporting ATPase activity, rotational mechanism (GO:0046961)

Also, the EC number mentioned earlier in the InterPro definition is obsolete - transferred to  7.1.2.2.

For reference, here's the UniProt summary for the human protein:
https://www.uniprot.org/uniprot/Q15904
Accessory subunit of the proton-transporting vacuolar (V)-ATPase protein pump, which is required for luminal acidification of secretory vesicles. Guides the V-type ATPase into specialized subcellular compartments, such as neuroendocrine regulated secretory vesicles or the ruffled border of the osteoclast, thereby regulating its activity. Involved in membrane trafficking and Ca2+-dependent membrane fusion. May play a role in the assembly of the V-type ATPase complex. 

@hattrill @happy-lorna

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have removed the GO terms and the EC number you mentioned. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks!
