### ISSUE TITLE
InterPro2GO for Carbohydrate kinase PfkB (IPR011611)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2921]
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR011611/

Hi,
This entry lacks any InterPro2GO annotations, but from definition and slew of EC xrefs, it looks like you could add "kinase activity (GO:001630)" (and maybe related terms).
Could you take a look?

Thanks

@hattrill @happy-lorna

**Comment by EBI-Hsinyu** [comment]
Hi, 
This entry includes 199k proteins. Some of them uncharacterised. Therefore, we are cautious and decide not to add the kinase activity GO term to it. We usually add the term to the subfamily entries which have more references. This way, it's more likely that we won't give the terms to inactive enzymes. Hope this explains. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
OK, understood.
But the absence of a GO term seems inconsistent with the listing of specific EC numbers as xrefs on this InterPro record. Should they be removed too? Or should users interpret the EC xrefs differently from an associated GO term?  (BTW Where do the EC xrefs come from on InterPro entries - are they automatically imported from UniProt entries or ?)
I couldn't find answers to these questions in any InterPro documentation, but maybe I missed it.

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 

Yes, we take EC numbers associated with Swiss-Prot entries, and applying them to InterPro entries mapping these proteins. Therefore, these EC numbers are references for family members that are annotated by UniProt, not everything. 

Regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
@sjm41 Do you think some UnoiProt curator should review this ?

**Comment by sjm41** [comment]
Thanks for that extra info Hsin-Yu - that clears up some of the confusion!
It would be great to add that information to the InterPro FAQs (or similar) - can you do that? (I see there's already a FAQ for "How are InterPro entries mapped to GO terms?")

I (at least) had been interpreting the EC xrefs on InterPro entries in a similar way as the associated GO term - i.e. they were basically equivalent, and both the GO term and EC applied to all proteins with that InterPro signature. (similar to how EC xrefs work on GO terms)

But I now understand that the GO term is added manually and has to apply to all proteins with that InterPro signature, whereas the EC xrefs mean some different - they are pulled in from the linked Swiss-Prot entries and thus represent functions of the specific annotated proteins (that may not apply to all proteins with that signature). This difference can lead to mismatches between the GO term and EC on a given InterPro entry, especially for entires with lots of members.

Q) Do the EC xrefs on InterPro entries get added manually or automatically from Swiss-Prot, and in either case, how often do they get reviewed/updated?


@pgaudet - if there are 199k proteins with the InterPro entry listed at the top of this ticket, then no, I don't think a UniProt curator should try to review.  My broader interest/query issue here is the relationship between a GO term and EC xref(s) present on InterPro entries, and how this interfaces/compares with (i) EC xrefs present on GO terms themselves and (ii) the EC2GO pipeline run at UniProt.  Any wider discussion on those points should occur outside of this specific ticket!
