### ISSUE TITLE
Associate GO activity term for IPR013818 Lipase/vitellogenin domain

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#2923]
The InterPro signature IPR013818 appear to have no associated GO term. From its description it belongs to EC:3.1.1.3 and, so I'd suggest to add the GO term "triglyceride lipase activity" (GO:0004806).
and for IPR000734 (Triacylglycerol lipase family) the associated GO term "carboxylic ester hydrolase activity" (GO:0052689) should be replaced with "triglyceride lipase activity" (GO:0004806).

@hattrill @sjm41

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have added/changed the GO terms you mentioned. 
Regards, 
Hsin-Yu

**Comment by phanivg** [comment]
Thank you Hsin-Yu!!
