### ISSUE TITLE
IPR037867 Q9UT39 not GO:0048188 | Set1C/COMPASS c

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2924]
Q9UT39 swd22
GO:0048188 | Set1C/COMPASS complex | IEA with IPR037867

isn't Set1C/COMPASS complex in pombe

there is a duplication and swd22 is 
mRNA cleavage and polyadenylation specificity factor complex
the paralog is SET/CoMPASS

**Comment by EBI-Hsinyu** [comment]
Hi, 
It looks like most of the proteins in this entry are Swd2 homologues that are part of the Set1/COMPASS complex. It would be a shame to lose this term. Is it possible to block it from UniProt for this protein (Q9UT39)? Thank you. 
Hsin-Yu

**Comment by ValWood** [comment]
OK, I can filter in  PomBase  but I can't  do anything about UniProt. If UniProt import their GO inference data  for fission yeast via PomBase (as the database authority for fission yeast) it will disappear, but if they generate the mappings internally it won't.

I'm happy  to close though if you want to retain the mapping (makes sense). I have filtered locally at PomBase.
