### ISSUE TITLE
Review annotations to GO:0061392 regulation of transcription from RNA polymerase II promoter in response to osmotic stress and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2925]
Hello,

More work for this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:

https://docs.google.com/spreadsheets/d/18nDedHe18cjIpRu0vq6ERxDSvw0HWyxj3B8BBxupwJc/edit#gid=0

**Comment by pgaudet** [comment]
Contributor   (Assigned by)
--
PomBase | 1
SGD | 43
TAIR | 1
UniProt | 4
WB | 1

**Comment by tberardini** [comment]
@ebakker2 Can you please review the 1 TAIR annotation?  Thanks.

**Comment by ValWood** [comment]
PomBase done

**Comment by vanaukenk** [comment]
WB done

**Comment by ebakker2** [comment]
TAIR done

**Comment by pgaudet** [comment]
@srengel Also if you have time to finish this one, it'd be great !

**Comment by srengel** [comment]
ok SGD all fixed.
