### ISSUE TITLE
Review annotations to "coenzyme" grouping terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#2927]
We are planning to obsolete all of the `cofactor` grouping terms, see https://github.com/geneontology/go-ontology/issues/19243 for explanation.

I've included sequence based annotations to make sure the manual sequence annotations are reviewed, though I know some are from loads based on orthology with other sequences. If it will be fixed once the original annotation is fixed, you can just put a comment in the first column.

https://docs.google.com/spreadsheets/d/12A4Xlg907tiz3LApJ3NT9BcLWF5BOjg0wYwER4P_AO8/edit?usp=sharing

**Direct annotations to coenzyme terms - Evidence by Contributor**

Contributor | IDA | IGI | IMP | IPI | TAS | RCA | ISM | ISO | ISS | Grand Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProt | 4 |   | 1 | 2 |   |   |   |   | 12 | 19
RGD | 2 |   |   | 2 |   |   |   | 6 |   | 10
MGI | 1 |   |   |   |   |   |   | 8 |   | 9
AspGD | 1 |   |   |   |   | 6 |   |   |   | 7
Reactome |   |   |   |   | 6 |   |   |   |   | 6
JCVI |   |   |   |   |   |   |   |   | 4 | 4
MTBBASE | 1 |   | 3 |   |   |   |   |   |   | 4
PseudoCAP |   |   | 4 |   |   |   |   |   |   | 4
CAFA | 2 |   |   |   |   |   |   |   |   | 2
EcoCyc | 1 | 1 |   |   |   |   |   |   |   | 2
GeneDB |   |   |   |   |   |   | 1 |   |   | 1
TIGR |   |   |   |   |   |   |   |   | 1 | 1
Grand Total | 12 | 1 | 8 | 4 | 6 | 6 | 1 | 14 | 17 | 69

**Comment by krchristie** [comment]
@pgarmiri - Could you please look at the JCVI ones as well as the UniProt ones. Many thanks!

**Comment by krchristie** [comment]
@brinkmanlab - Please review your annotations to any of the coenzyme terms and update to a more specific term if possible. Thanks very much.

**Comment by hdrabkin** [comment]
MGI done

**Comment by Achchuthan** [comment]
GeneDB done.

**Comment by deustp01** [comment]
Reactome done - changes will become visible with June 2020 release.

A nomenclature issue: our pathway "Coenzyme A biosynthesis" was previously tagged with GO "coenzyme biosynthetic process" and that correctly tripped the alarm here. The fix is to re-tag the pathway with the GO term for Coenzyme A biosynthetic process, and to assert as a matter of nomenclature that "Coenzyme A" is a proper name that does not logically imply the role "coenzyme" or "cofactor". Elsewhere the same patch with the same nomenclatural wriggle was applied to our molybdenum cofactor metabolism pathway.

The fix is that where we used high-level "cofactor" and "coenzyme" terms to tag our high-level grouping pathways, those have been removed (we don't need them internally) and I've ensured that every child pathway that describes the metabolism of a specific molecule or family of them now has a metabolism process term that that points to the chemical type of the molecules, not to any alleged role they may have. (Even if those chemical names sometimes include a word like coenzyme)

**Comment by pgarmiri** [comment]
Hello,
Is it possible to have a term 'Coenzyme A binding'?  There is  GO:1905502
'acetyl-CoA binding' but it's not suitable for the case I am checking.

Thanks,
Penelope

**Comment by ValWood** [comment]
This term is in many slims so maybe a broader announcement is needed.
v

**Comment by deustp01** [comment]
This request seems OK because it's for a term to annotate the binding of a chemical whose (unfortunate) name is Coenzyme A - it's not annotating the coenzyme role.

**Comment by krchristie** [comment]
> Hello,
> Is it possible to have a term 'Coenzyme A binding'? There is GO:1905502
> 'acetyl-CoA binding' but it's not suitable for the case I am checking.
> 
> Thanks,
> Penelope

I agree with @deustp01 that a term for 'coenzyme A binding' is fine since that is binding to a specific compound.

**Comment by pgarmiri** [comment]
Hi, 

All the relevant experimental annotations of UniProt-EBI and MTB have been checked by me. There were a couple more annotations (highlighted in orange background) that are referring to particular derivative compounds of Coenzyme A ( (3S)-3-hydroxy-3-methylglutaryl-CoA and succinyl-CoA) . Shall I request new binding terms for those?

@pgaudet checked most UniProt-SWIS annotations (there is one more left to be checked) and the JCVI ones. 

The ISS annotations will be updated automatically when the parent annotations are all updated.

Thanks,

Penelope

**Comment by krchristie** [comment]
> Hi,
> 
> All the relevant experimental annotations of UniProt-EBI and MTB have been checked by me. There were a couple more annotations (highlighted in orange background) that are referring to particular derivative compounds of Coenzyme A ( (3S)-3-hydroxy-3-methylglutaryl-CoA and succinyl-CoA) . Shall I request new binding terms for those?

Requesting new terms seems like a good option to me, but I'll check with the ontology editor's group at our next Monday meeting (4/20/20) to confirm. 

 
> @pgaudet checked most UniProt-SWIS annotations (there is one more left to be checked) and the JCVI ones.
> 
> The ISS annotations will be updated automatically when the parent annotations are all updated.
> 
> Thanks,
> 
> Penelope

Thanks to you both.

**Comment by pgaudet** [comment]
I am closing this because the term was obsoleted already, so the remaining errors will appear in error reports. 

For information  
AspGD @marekskrzypek 
RGD @gthayman 
PseudoCAP @glwinsor 

Still need to be fixed. 

Thanks, Pascale
