### ISSUE TITLE
CAFA annotations for P60723

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#2934]
There are two annotations for the E. coli ribosomal protein L4 to terms involving DNA binding, specifically GO:0032993 and GO:0001217.  I think these are incorrect; RplD binds to the mRNA for its regulatory function.

Thanks for checking,
Ingrid

**Comment by pgarmiri** [comment]
Hello,

Thank you for pointing this out. I had a look at the paper and I don't think that are evidence for DNA binding, so I reviewed the annotations accordingly. I have updated the MF annotation to GO:0030371 'translation repressor activity' and removed the CC annotation to GO:0032993 'protein-DNA complex'.

Let me know if there are any further issues.

Kind regards,

Penelope

**Comment by pgaudet** [comment]
I think this is fine ? @keseler please reopen if there are still issues.
