### ISSUE TITLE
Review MGI:107157 annotation to GO:0003700 DNA-binding transcription factor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2935]
MGI:107157

GO:0003700 DNA-binding transcription factor activity   (inconsistent with information in PMID:15998811

This is a co-factor, as stated in the paper: "mSin3A is a core component of a large multiprotein corepressor complex with associated histone deacetylase (HDAC) enzymatic activity. Physical interactions of mSin3A with many sequence-specific transcription factors " 

Should be annotated to GO.0003714 transcription corepressor activity

Thanks, Pascale

**Comment by pgaudet** [comment]
@hdrabkin who should do this ? Or was it done?

**Comment by hdrabkin** [comment]
If this was from Ruth I may have taken care of it through MGI help-desk (a p2go challenge).
Not sure.

**Comment by hdrabkin** [comment]
Hi @pgaudet Was able to check this morning (can't get into our EI during certain times on weekends because that's when loads occur). This was taken care of already in a p2go challenge coming into our help desk. I'll remove myself and close this.
