### ISSUE TITLE
NADH dehydrogenase (ubiquinone) activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2938]
does not seem to be:

NDUFAB1 | Acyl carrier protein, mitochondrial |   | NADH dehydrogenase (ubiquinone) activity |   | UniProt | Homo sapiens | NAS |   | acyl carrier protein/zinc finger protein 593-related pthr20863 | protein |   | PMID:9878551 | 20070221

**Comment by ValWood** [comment]
can this TAS just be deleted? is clearly incorrect.

**Comment by pgaudet** [comment]
Removed
