### ISSUE TITLE
regulation of DNA-binding transcription factor /PAINT PTHR24006

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2939]
these seem quite  indirect?

ubp5 | ubiquitin C-terminal hydrolase Ubp5 |   | regulation of DNA-binding transcription factor activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001922594 UniProtKB:Q93009WB:WBGene00010406 | family not named pthr24006 | protein |   | PMID:21873635 | 20170928

  | ubp15 | ubiquitin C-terminal hydrolase Ubp15 |   | regulation of DNA-binding transcription factor activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001922594UniProtKB:Q93009WB:WBGene00010406 | family not named pthr24006 | pr

or at least pombe does not have the specific targets so it seems a bit of a stretch to transfer...
...this would be a bit like transferring annotations specific for the target of a TF

**Comment by pgaudet** [comment]
These annotations are now removed (not sure when that happened).
