### ISSUE TITLE
MMS19 is not  indirectly upstream of  transcription, and isn't regulatory

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2942]
iron-sulfur protein assembly (CIA) complex, a multiprotein complex that mediates the incorporation of iron-sulfur cluster into apoproteins

ERCC2/XPD is a target protein.

Challenge MF

receptor signaling complex adaptor activity 

transcription coactivator activity 
(note that this paper PMID: 11279242  describes as "The human homologue of the yeast DNA repair and TFIIH regulator MMS19 is an AF-1-specific coactivator of estrogen receptor."
suggesting that hMMS19 may be an AF-1-specific transcriptional coactivator of estrogen receptor. (weasel words)

Challenge BP
response to hormone
DNA metabolic process
DNA repair
phosphorelay signal transduction system
positive regulation of double-strand break repair via homologous recombination
positive regulation of transcription, DNA-templated
transcription, DNA-templated
nucleotide-excision repair
chromosome segregation

all seem to be indirect.
 iron-sulfur protein assembly (CIA) complex, a multiprotein complex that mediates the incorporation of iron-sulfur cluster into apoproteins 

To me it doesn't make sense to annotate to 
"regulation of transcription" when this is required for the integrity of the participating proteins. 

This isn't regulatory.

Do you agree ?

@colinlog  @RLovering @pgaudet 

If so I will reises disputes. If not, can we add to tomorrows discussion?

**Comment by ValWood** [comment]
Ideally ERCC2/ would be added as a target protein, but I don't know how to describe the actual MF

**Comment by ValWood** [comment]
(note that this paper PMID: 11279242 describes as "The human homologue of the yeast DNA repair and TFIIH regulator MMS19 is an AF-1-specific coactivator of estrogen receptor."

suggesting that hMMS19 may be an AF-1-specific transcriptional coactivator of estrogen receptor. (weasel words)

**Comment by ValWood** [comment]
I  disputed some of the indirect phenotypes in protein2GO

**Comment by sylvainpoux** [comment]
Hi @ValWood I removed some annotations but not all. MMS19 role in DNA repair is well documented and should not be deleted.
Sylvain

**Comment by ValWood** [comment]
Doesn't MMS19 have a repair defect because which transfers critical FeS clusters to several key enzymes with functions in DNA repair and replication?
https://pubmed.ncbi.nlm.nih.gov/27558664/
"A requirement for Mms19 is explained by its role in directing iron-sulfur cluster assembly into sulfite reductase as opposed to promoting DNA repair, as DNA damage response genes were not enriched among those required for cadmium or arsenic tolerance."
Obviusly it is reqyired for replication, repain and genome integrity generally
https://pubmed.ncbi.nlm.nih.gov/22678362/
https://pubmed.ncbi.nlm.nih.gov/22678361/
but it seems to be indirect?

As far as I know we don't normally annotate proteins required for the maturation of proteins involved in a process  to that process.

@pgaudet  thoughts?

**Comment by ValWood** [comment]
i.e this would have only a phenotype annotation

**Comment by sylvainpoux** [comment]
I see your point, I read the UniProt function. I think it is too preliminary to remove it. As most papers describe its role in DNA repair I would prefer to keep it for the moment.

**Comment by ValWood** [comment]
OK!
