### ISSUE TITLE
TFIIA is a GTF not co-repressor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2945]
TFIIA should be annotated to 
MF RNA polymerase II general transcription initiation factor activity
and
BP transcription initiation from RNA polymerase II promoter / RNA polymerase II preinitiation complex assembly

**Comment by pgaudet** [comment]
@ValWood We need to know who shoudl fix this. 

From context I think this is human - next time please provide the accession number for the protein and assign someone to look at it if you can.

**Comment by pgaudet** [comment]
P52655 PINC annotation

**Comment by pgaudet** [comment]
Fixed
