### ISSUE TITLE
TAF7 KW mapping to translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2946]
Hi Sylvain.
Delete?

TAF7 | TAFII55_N domain-containing protein |   | translation initiation factor activity |   | UniProt | Dictyostelium discoideum | IEA | UniProtKB-KW:KW-0396 | transcription initiation factor tfiid 55 kd subunit-related pthr12228 | protein |   | GO_REF:0000043 | 20200418

v

**Comment by ValWood** [comment]
and


TAF5 | Transcription initiation factor TFIID subunit |   | translation initiation factor activity |   | UniProt | Dictyostelium discoideum | IEA | UniProtKB-KW:KW-0396 | transcription initiation factor tfiid pthr19879 | protein |   | GO_REF:0000043 | 20200418


odd that these are only a couple of weeks old. Are things like this still being added?

**Comment by ValWood** [comment]
TAF5 is OK. Also part of SAGA

**Comment by sylvainpoux** [comment]
Hi Val,
I cannot do anything for these. The error is coming from the submitter. You should either contact someone at ebi or someone from dictybase

KW   Initiation factor {ECO:0000313|EMBL:EAL71799.1};
KW   Protein biosynthesis {ECO:0000313|EMBL:EAL71799.1};

Thanks

Sylvain

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

dictyBase doesn't assign keywords; what can they do here? 
Thanks, Pascale

**Comment by sylvainpoux** [comment]
Then the problem comes from EMBL automatic annotation pipeline and/or TrEMBL.

Maybe contact someone at EBI and see how to clear such case? As already said, as these are TrEMBL entries and annotation derived from the submitter, I cannot do anything for these entries

Thanks

Sylvain

**Comment by ValWood** [comment]
and maybe not assign SPKW from EMBL entries (this is a genomic sequence entry- I don't see any KW assignment so it's odd that a pipeline is adding this?).

**Comment by pgaudet** [comment]
@pgarmiri @alexsign Do you know what is the process to address those issues ?

**Comment by ValWood** [comment]
TAF5 is gone
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q15542&aspect=molecular_function

**Comment by ValWood** [comment]
ignore, still there
https://www.uniprot.org/uniprot/Q54KH7

**Comment by pgarmiri** [comment]
Hi, 

This will be fixed in the 2021.02 release. 

For issues like this, it would be better to contact help@uniprot.org as me and Alex can't do much about TrEMBL entries. They can be directed to Jie Luo that can fix them.

Thanks,

Penelope

**Comment by pgaudet** [comment]
@pgarmiri 

Would it be possible to tag Jie in the GO GH tickets ?

**Comment by pgarmiri** [comment]
Hello @pgaudet ,

His github account is jieluo321.

All the best,

Penelope
