### ISSUE TITLE
Review annotations to GO:0035391 maintenance of chromatin silencing at silent mating-type cassette

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2947]
Hello, 

GO:0035391 maintenance of chromatin silencing at silent mating-type cassette will be obsoleted. 
There are 5 SGD annotations to review: 

https://docs.google.com/spreadsheets/d/1wqFkhWmVDX8pWGcYtCZPuumutUi2lEb5JfBW5NJMHJ0/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
@srengel This term was obsoleted, but the annotations dont seem to have been fixed yet. I'm closing this, you'll see the errors in the error reports.

**Comment by srengel** [comment]
oops sorry Pascale, just got piled up with work, will try to address these today...
