### ISSUE TITLE
InterPro2GO for "proton-transporting ATP synthase activity, rotational mechanism (GO:0046933)"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2949]
"proton-transporting ATP synthase activity, rotational mechanism" (GO:0046933) is associated with the following InterPro terms:

IPR000711:ATPase, OSCP/delta subunit
IPR005294:ATP synthase, F1 complex, alpha subunit
IPR005722:ATP synthase, F1 complex, beta subunit
IPR000131:ATP synthase, F1 complex, gamma subunit
IPR035968:ATP synthase, F1 complex, gamma subunit superfamily
IPR001469:ATP synthase, F1 complex, delta/epsilon subunit
IPR006721:ATP synthase, F1 complex, epsilon subunit, mitochondrial
IPR036742:ATP synthase, F1 complex, epsilon subunit superfamily, mitochondrial

But, as stated in the IPR005294 & IPR005722 definitions, the catalytic activity specifically resides in the beta subunit.
So I think all the above associations should be removed, except IPR005722 (beta subunit).

Useful recent refs: PMID: 31418131, PMID: 30888962

@hattrill

**Comment by hattrill** [comment]
Hi @sjm41 

I think that because this is essentially a compound term:
Enables the transfer of protons from one side of a membrane to the other according to the reaction: ADP + H2O + phosphate + H+(in) = ATP + H+(out), by a rotational mechanism

is_a phosphotransferase activity, phosphate group as acceptor
is_a proton channel activity
and definition includes the requirement for the rotational mechanism, that it's ok to have these for all subunits.

**Comment by sjm41** [comment]
Hi @hattrill 

Do you mean for all subunits of just the F1 sector? (OSCP/delta subunit is part of the F0).

**Comment by hattrill** [comment]
For F1 and F0 -  ATPsyn and channel. 
From InterPro description, OSCP/delta subunit is part of generation of torque. I think that a contributes_to might be good to add here. 

I wonder if putting contributes_to on the other subunits might be appropriate and then adding individual H+ channel activity and ATP syn term (that doesn't exist) on the appropriate domains/SUs w/o qualifier would be appropriate. 

@bmeldal what do you think? Good example of a complex molecular machine! These compound terms are a good example of where the contributes_to qualifier could be useful and get round some of the issues with compound terms (inaccurate inferrences of activity multiple activities, multiple inheritance).

**Comment by sjm41** [comment]
Hmmm, yes, maybe the primary issue here is the "compound"-ness of the GO term itself.  Not sure what to do about that....  The term as defined can only really apply to the whole complex.

From my reading (see PMIDs in original post) I don't think it would be correct to add the current "proton-transporting ATP synthase activity, rotational mechanism" term (which necessarily includes the ATP synthase bit) to all the individual F0 subunits - the literature seems clear that F1 is the catalytic sector, and the beta subunits specifically have the catalytic interface (also see GO:0005754 on this).  And apart from the OSCP subunit, InterPro seems to agree with that view: https://www.ebi.ac.uk/interpro/search/text/GO:0046933/?page=1#table (InterPro seems to give the F0 subunits the "proton transmembrane transporter activity (GO:0015078)" term.)

As for the F1 subunits, using 'contributes_to' for the alpha/gamma/delta/epsilon subunits might work.
But I seem to remember a previous discussion saying the InterPro2GO doesn't/shouldn't use that qualifier?? Have I got that wrong?

**Comment by hattrill** [comment]
InterPro doesn't use contributes_to....thankfully :)

Perhaps InterPro should not really add to OSCP. But, for general annotation, no one subunit can both be defined as a proton transporter and an ATP syn - so we either use or don't use this term for all SUs or for none. It's not perfect, but think for the MF itself, the term is synonymous with the complex as a whole unit. 

(I think this is where the gene groups help..they don't have to mirror the GO - just put the beta subunits in a catalytic branch)

**Comment by sjm41** [comment]
I think this ticket can probably be closed now, with no action taken.
Annotating all subunits with the compound term "proton-transporting ATP synthase activity, rotational mechanism (GO:0046933)" seems to be consistent with the agreements from the 'contributes to' discussion at the recent GO meeting - InterPro2GO can't use that qualifier, but any manual annotations should.

My main concern in starting this ticket was that any subunit getting GO:0046933 was automatically being classed as a 'transferase' via its parent term "phosphotransferase activity, phosphate group as acceptor". But that parent isn't accurate and should be removed (see https://github.com/geneontology/go-ontology/issues/19380), which will fix that particular issue.
