### ISSUE TITLE
MRPS36 (human and other, not mitochondrial ribosome)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#2951]
The structure of the human mitochondrial ribosome
Alexey Amunts,# Alan Brown,# Jaan Toots, Sjors H. W. Scheres, and V. Ramakrishnan†

P82909 MRPS36 (HGNC:16631)
from
For the mt-SSU, we are able to locate all reported constituent proteins (30, with 14 specific to mitochondria) with the exception of MRPS36, confirming the recent observation that it is not a mitoribosomal protein (5)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4501431/

in yeast it is 
https://www.yeastgenome.org/locus/YFR049W
Subunit of the mitochondrial alpha-ketoglutarate dehydrogenase; recruits E3 subunit (Lpd1p) to the E1-E2 (Kgd1p, Kgd2p) core; exists in two forms derived from a single mRNA translated from two alternative start sites; has similarity to human mitochondrial ribosomal protein MRP-S36

**Comment by ValWood** [comment]
mitochondrial translational elongation Source: Reactome
mitochondrial translational termination Source: Reactome
@deustp01

**Comment by ValWood** [comment]
I will raise disputes in p2GO for the others shortly. RIght now I'm on a different goose chase...

**Comment by ValWood** [comment]
@sylvainpoux there is also a SP-KW mapping

**Comment by ValWood** [comment]
Challenged other annotations in P2GO

**Comment by deustp01** [comment]
Bruce May, who annotated this process for Reactome, replies:

I based the inclusion of MRPS36 in the small subunit of the mitochondrial ribosome on work from Linda Spremulli's lab on the bovine mitochondrial ribosome:
Haque et al. 2011 (https://www.ncbi.nlm.nih.gov/pubmed/22015679)
Linda Spremulli also reviewed the pathway.
I think the inference from cow to human is OK for the mitochondrial ribosome.

**Comment by ValWood** [comment]
I think I would be more inclined to believe the 2 most recent papers.
The one I cite above is 
Venki Ramakrishnan 2015  Science paper.
(note that that was a direct quite from the paper, and had been reported by others)

 I would expect this to be very rigorous and 2011 is a long time ago. Maybe check with Linda if she still believes this is a bona fida subunit?

So in addition to multiple lines of evidence, this is 
mitochondrial alpha-ketoglutarate dehydrogenase in yeast...

**Comment by sylvainpoux** [comment]
Hi Val,
I created a ticket for this. I will assign this to a curator who will handle this interesting case
Cheers
Sylvain

**Comment by ValWood** [comment]
Maybe it's a membrane anchor or something similar?

**Comment by sartweedie** [comment]
HGNC are also interested to know if the research community still believe this is a mitochondrial ribosomal protein (as well as a mitochondrial alpha-ketoglutarate dehydrogenase adaptor) - if not, we feel the current nomenclature is misleading and we would consider updating it. As Sylvain has assigned this to a curator to look at this, we will wait to see what they think (we don't want multiple curators contacting the same researchers).

**Comment by deustp01** [comment]
If it's useful, you can contact Bruce May, who made the Reactome annotations, directly - broose dot reactome at gmail dot com.

**Comment by ValWood** [comment]
Hi @deustp01 could you point Bruce to this ticket, and then he can add any support for the old annotation?

@sartweedie  do you have any insight from HGNC?

I'm basing my opinion at the moment solely  on
1.  Conflicting information from the original bovine derived  annotation from human and yeast
2. Mass specs  weren't very good in 2011

But  if this is the *only* piece of evidence I would  remove based on the  more recent data (and add a NOT annotation)

**Comment by ValWood** [comment]
Any update on this? Did it turn out to be likely a ribosomal subunit?

**Comment by sartweedie** [comment]
Assuming nobody else has written to Linda Spremulli yet, I'll email her today.

**Comment by sartweedie** [comment]
Antonia let us know that she had updated the protein name at UniProt which prompted me to trying contacting Linda Spremulli again and this time she got back to me.  I said, 'If it is now agreed that this gene does not encode a mitochondrial small subunit ribosomal protein then we would propose renaming it.' - she said 'I agree with the proposed revisions.'.  The only issue is that we don't have any human genes approved with the KGD root - we have the name oxoglutarate dehydrogenase rather alpha-ketoglutarate dehyrdogenase; the kgd1/KGD1 genes in S. pombe and S. cerevisiae have the human ortholog OGDH (and OGDHL). Unlike yeast, all subunits of the complex in human have unrelated symbols (OGDH. DLD, DLST, MRPS36). We don't want to invent a new symbol for MRPS36 but we would be happier to switch to KGD4 if the orthologs in either or S. pombe or S. cerevisiae (ideally both) were also changed to from YMR31 to KGD4 so there is some continuity. Is that something you'd consider? We still need to write to authors using the MRPS36 before we update it but given the current symbol is misleading this should be a formality.

**Comment by pgaudet** [comment]
@srengel @ValWood see comment above please

**Comment by ValWood** [comment]
Since this gene is not published in S. pombe, I would be happy,  in principle,  to implement the alternative name suggestion  "KGD1" to align with human and move the SGD inferred name to beasynonym (there are no clashes for us). However, this may be more difficult for SGD if the name is published... and there are many (the majority) of genes that do not align with human. However, of course it is always nice when they do.

One other thing, there is a new pombe manuscript accepted which might include work on this protein. I will double-check with the author (Nathalie Bonnefoy), because I know that number of pombe proteins are assigned names in this manuscript. I think it might have even  been discussions with Nathalie which initiated this question.

**Comment by srengel** [comment]
the KGD4 name is already an alias of YMR1/YFR049W, so i'm not sure there is anything SGD needs to do here.

**Comment by sartweedie** [comment]
Val - thanks for agreeing in principle to change the pombe gene symbol from ymr31 to kgd4. We wouldn’t normally be that bothered about trying to align the symbols but in this case we’d be adopting a symbol with the KGD root which comes from yeast symbols but isn’t actually being used for this gene (other than as an alias). Anyway, good if at least one yeast can match. Let me know what Nathalie Bonnefoy says and then we’ll go ahead and alert researchers that we intend to change to KGD4. You may want to hold off till we have done this – I can keep you posted.

Stacia - I appreciate that SGD already have KGD4 as an alias for YMR31 but given the current consensus is that this does not encode a ribosomal protein in humans or yeast (PMID: 25838379, PMID: 25165143) and ‘YMR’ is derived from ‘yeast mitochondrial ribosomal protein’ I thought you may want KGD4 to become the standard name. I don’t know what your policy is for changing S. cerevisiae nomenclature and descriptions. We don’t like to change published human symbols but make an exception if it could be misleading. In this case the researcher that previously published the human gene as a mitochondrial ribosomal protein agrees it should be changed but I guess the yeast researchers that originally published it may agree.
