### ISSUE TITLE
InterPro entries incorrectly mapped to transctiption or regulation of transcription

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2952]
* remove regulation of transcription, DNA-templated (GO:0006355)
 - [ ] IPR011177 Transcription initiation factor TFIID subunit 1, animal

* change from remove regulation of transcription, DNA-templated (GO:0006355) to transcription, DNA-templated (GO:0006351) 

- [x] IPR003894  TAFH/NHR1
- [x] IPR037249  TAFH/NHR1

* change MF to DNA-binding transcription factor activity (GO:0003700) or DNA-binding transcription factor activity, RNA polymerase II-specific if eukaryotic-specific (GO:0000981 )
- [x] IPR017970 Homeobox, conserved site
- [x] IPR015660   MASH1/Ascl1a-like

**Comment by typhainepl** [comment]
Hi @pgaudet,
I've updated the mentioned entries. The changes will be visible in the next InterPro release.
