### ISSUE TITLE
Review annotation to MGI:104633

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2954]
Hello, 

MGI:104633 is annotated to DNA-binding transcription factor activity, RNA polymerase II-specific, but it seems to be a co-repressor. 

@hdrabkin can you pleaae check ? 

Thanks, Pascale

**Comment by ukemi** [comment]
Fixed.

**Comment by pgaudet** [comment]
Thanks @ukemi 
Can you just tell me if you removed or changed the annotation (and how?) 

Thanks, Pascale

**Comment by ukemi** [comment]
changed to corepressor

**Comment by pgaudet** [comment]
Thanks !

**Comment by hdrabkin** [comment]
I am getting these from two pipelines: Ruth/p2go, and now github. Yesterday I changed one that Ruth had (an ISO to human).
