### ISSUE TITLE
UniProt IDs should be of type 'protein-coding gene' in the GPI file(s) 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2955]
Hi @alexsign 

To be consistent with the GO-Shapes/ShEx, we need to have the UniProt IDs that represent gene-centric reference protein (GCRP) accession of type  'protein-coding gene' , SO:0001217, and not protein. 

Thanks, Pascale

**Comment by alexsign** [comment]
@ not sure what is issue about? 
ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_gcrp.gpi.gz
should have GCRP accessions of type 'protein-coding gene', unless something went wrong on during the assignment.

**Comment by pgaudet** [comment]
OK thanks @alexsign 
@vanaukenk I think we're all good ? The ShEx should not create incorrect inferences anymore if this is taken into account, right ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@RLovering in case you want to follow the discussion

**Comment by pgaudet** [comment]
Thanks @alexsign ! I should have checked before opening a ticket.
