### ISSUE TITLE
Hes6  Q9JHE6 MGI:1859852 revision required

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2961]
Hi Harold 

please could you forward this request to the relevant curator. We discussed the annotation of Hes6 today and the paper (PMID:10851137) with Colin, Pascale, Val, Antonia Giulia and it was agreed that this is a DNA binding protein but although it is not binding DNA on it's own this probably reflects that the appropriate DNA sequence was not included for this protein. It does appear to bind DNA as a heterodimer. Whilst you could argue that then this should be annotated to 'contributes to' dbTF activity or as MGI has curated, to co-repressor activity, the group felt that as there is other evidence to support this protein being a dbTF that it should either be annotated as a dbTF with this paper, or that the DNA binding activity should not be captured with this papers evidence.

If you let me know when this is done I will add your name to the human annotation review spreadsheet so that this annotation revision is included in the next batch of stats

Best

Ruth

**Comment by ukemi** [comment]
Sorry Ruth. Do you want us to delete this annotation?

**Comment by pgaudet** [comment]
>  Do you want us to delete this annotation? the coregulator one?

yes (if you agree)

**Comment by ukemi** [comment]
deleted.

**Comment by RLovering** [comment]
thanks sorry for not being clearer. thank you so much, I have added your name to the human dbTF review spreadsheet
Thanks
Ruth
