### ISSUE TITLE
IPR034968 BP mapping needs revision

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-annotation#2962]
IPR034968 Maps to the BPs
neuron migration (GO:0001764)
central nervous system development (GO:0007417)

Not good for Dicty which has the domains in two proteins
https://dictycr.org/gene/DDB_G0285297/goannotations
https://dictycr.org/gene/DDB_G0285271/goannotations

Please remove these mappings

**Comment by typhainepl** [comment]
Hi @pfey03, could you let us know which protein accessions are missannotated?

**Comment by pfey03** [comment]
@typhainepl 
https://www.uniprot.org/uniprot/Q54NG6
https://www.uniprot.org/uniprot/Q54NG5

**Comment by typhainepl** [comment]
I have informed the GO team, they will add the proteins to the GO black list.
