### ISSUE TITLE
IPR002038 problematic BP mapping

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-annotation#2963]
IPR002038 the Osteopontin domain, as the name already says has the mapping to
ossification (GO:0001503)

Sadly, Dicty has a protein in this family and got the IEA
https://dictycr.org/gene/DDB_G0280137/goannotations

Thanks!!

**Comment by typhainepl** [comment]
@pfey03 do you know which protein accession is causing this missannotation?

**Comment by pfey03** [comment]
@typhainepl sure
https://www.uniprot.org/uniprot/Q54VU2
Thanks!

**Comment by typhainepl** [comment]
Are you saying that Q54VU2 shouldn't have GO:0001503 mapping to it?

**Comment by pfey03** [comment]
Dictyostelium is an amoeba and doesn't have any bones. Yes, Q54VU2 should not have this annotation. Thanks!

**Comment by typhainepl** [comment]
I have informed the GO team, they will add the proteins to the GO black list.
