### ISSUE TITLE
Membrane dipeptidase, active site (IPR000180)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2965]
Should remove dipeptidyl-peptidase activity (GO:0008239) association.

@hattrill

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have removed this term. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu - closing.

**Comment by sjm41** [comment]
Hi @EBI-Hsinyu 
Sorry I didn't notice this first time round, but I've just realised that the remaining two MF terms on this entry can be replaced with a single term.
That is:
metalloexopeptidase activity (GO:0008235)
dipeptidase activity (GO:0016805)
>
metallodipeptidase activity (GO:0070573)

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 
We have started the release procedure for Interpro80. This means that we can't add/delete GO terms until certain step of the release. This might takes a few days. I will changes these terms when that happens.  
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
No problem - thanks for the update.
Steven

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 
Thank you for this. I have replaced the terms with GO:0070573 now. 
Hsin-Yu

**Comment by sjm41** [comment]
Great, thanks!
