### ISSUE TITLE
Peptidase M14B, caboxypeptidase D (IPR015567)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2966]
Can you check the association of "serine-type carboxypeptidase activity (GO:0004185)" to this term?  I can't see any evidence for it, including looking at the M14 MEROPS page (https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=M14)

@hattrill

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have removed the term. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu - closing.
