### ISSUE TITLE
Cdx2 and Pou5f1 revise annotations for transcription project

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2972]
Hi

Please could you review the annotation of Cdx2 P43241; and Pou5f1 P20263 both of which are likely to be dbTFs but based on PMID:16325584 have been annotated as coTFs

Thanks
Ruth

**Comment by pgaudet** [comment]
@hdrabkin Can you please have a look at this one ?

**Comment by hdrabkin** [comment]
It is clear from papers that Cdx2 binds DNA. 
However, it is also clear that Cdx2 binds protein (Oct3/4, aka Pou5f1); 
Oct3/4 binds DNA
What is not clear is whether when Cdx2 is bound to Pou5f1, it is also binding to DNA ?
That is when Cdx2 is negatively regulating Pou5f1-dependent promoters, is it doing so via just it's binding to Pou5f1, and not to it's DNA binding.

**Comment by RLovering** [comment]
Hi Harold
I have just had an email froma colleague at UCL, Vishwanie Mahadeo, who works on  Brn-3b/Q63934/Pou4f2. She has stated that Brn-3b appears to very often form dimers with other dbTFs, even when these are not closely related. In the cases where this has been closely examined it appears that there are binding motifs for both proteins in the region bound. But as you have noted, she has pointed out that it is very difficult to demonstrate both proteins are actually bound. As both proteins have DNA binding domains it is your decision whether you want to delete these annotations or assume that these proteins are acting as dbTFs. 
Both proteins have existing experimental evidence that they bind DNA; their DNA binding domain is well characterised. I would apply the dbTF term. 

It confirm if you are not comfortable with this suggestion it is very important not to annotate these to coTF activity. The evidence you have described is not good enough to give these the 'novel' function of acting as coregulators. To apply that term you would need evidence that the activity does NOT involve DNA binding. 

Obviously, if the protein did not have a DNA binding domain then you would not need evidence that it did not bind DNA in order to apply the coTF activity term.

Best

Ruth

**Comment by hdrabkin** [comment]
Or, Cdx2 could have two separate modes of action: one utilizing it's protein-binding activity to inhibit Oct3/4, (thus regulator)  and one when it binds DNA and acts as a transcription factor? 
IF the paper where Oct3/4 also demonstrated DNA binding of both during the inhibition,  I would be fine. I'll think on it a bit more.

**Comment by RLovering** [comment]
HI Harold

are you able to make a decision on removing the coTF term

Thanks

Ruth

**Comment by hdrabkin** [comment]
Changed both to dbTF

**Comment by RLovering** [comment]
Great thanks
Ruth
