### ISSUE TITLE
IPR028314 NOT transcription coregulator activity (GO:0003712)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2973]
Hello, 
IPR028314 should not be associated with "transcription coregulator activity (GO:0003712)"; it is a  'GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific' . 

See PMID:7784053 (cited in the entry).

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Thank you for this. I have replace the GO term. 
Hsin-Yu
