### ISSUE TITLE
Review RGD:67398 annotation to DNA-binding transcription factor activity PMID:7980586

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2974]
Hello @gthayman 

Can you please review annotation of RGD:67398 from PMID:7980586 to DNA-binding transcription factor activity? 
It should be annotated to GO:0016251 RNA polymerase II general transcription initiation factor activity. 

Thanks, Pascale

**Comment by gthayman** [comment]
Done.

**Comment by pgaudet** [comment]
Thanks
