### ISSUE TITLE
IPR030453 NOT transcription coactivator activity (GO:0003713)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2975]
Hello, 

IPR030453 is annotated to both 

* DNA-binding transcription factor activity (GO:0003700)
* transcription coactivator activity (GO:0003713)

The latter annotation should be removed. Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale,
Thank you! I have removed this term. 
Hsin-Yu
