### ISSUE TITLE
Review MGI:107543 annotation from PMID:8636240

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2976]
Hello @hdrabkin 

MGI:107543 in  PMID:8636240 should be annotated to GO:0001228 DNA-binding transcription activator activity, RNA polymerase II-specific, and not GO:0003713 transcription coactivator activity. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
done

**Comment by pgaudet** [comment]
thanks
