### ISSUE TITLE
IPR003309 NOT DNA-binding transcription factor activity (GO:0003700)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2977]
Hello, 

IPR003309 has annotations to 
*  regulation of transcription, DNA-templated (GO:0006355)
*  DNA-binding transcription factor activity (GO:0003700)

from older papers, probably when zinc fingers were all assumed to be transcription factors. I couldn't find any evidence that this is right for the SCAN domain. 

I suggest those annotations get removed. 

Maybe @colinlog knows more about those ? 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
You are right. Some proteins with this domain don't even have the zinc finger motifs. I have removed these terms. 
Regards, 
Hsin-Yu
