### ISSUE TITLE
MGI:1343132 (Q2M4I6) NOT GO:0003713	 transcription coactivator activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2978]
Hi @hdrabkin 

PMID:10393183 does not have evidence for the MF GO:0003713 transcription coactivator activity to MGI:1343132. 

An experimental BP annotation would be OK though, to 
GO:0045893 positive regulation of transcription, DNA-templated

Thanks, Pascale

**Comment by hdrabkin** [comment]
done
