### ISSUE TITLE
FBgn0010825 does not directly bind DNA ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2979]
Hi @hattrill 
FBgn0010825 is annotated to DNA binding from PMID:16481466, but it's also annotated to coregulator activity from other papers. I dont think PMID:16481466 shows direct DNA binding, but only that it's found *at* the DNA with the dbTF it regulates. 

Can you please have a look ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Yep...corepressor that interacts with a nuclear receptor. I've removed the annotation and added some corepressor terms.

**Comment by pgaudet** [comment]
Thanks !
