### ISSUE TITLE
Q02248	 MGI:88276  Ctnnb1 not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2980]
Hi 

please could you review/revise the annotation, of Q02248 | Ctnnb1 as a dbTF based on PMID:12235125 

please let me know if you change or remove the annotation so I can record this on the sheet
Thanks
Ruth

**Comment by RLovering** [comment]
@hdrabkin

**Comment by hdrabkin** [comment]
I see this is annotated to co-activator activity by this and several other papers. 
Please clarify
Ctnnb1 not dbTF:  do you mean you see an annotation based on this paper that says it IS a dbTF and it should NOT be, OR that you are expecting to be one and it is not.

It IS annotated to RNA polymerase II transcription factor binding; that is, it binds a transcription factor;

**Comment by RLovering** [comment]
HI Harold

I am so sorry for not being specific enough.

In Protein2GO there is the annotation:

MGI | Q02248 | Ctnnb1 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:12235125

please either delete or change to 

GO:0003713 | transcription coactivator activity

Thanks

Ruth

**Comment by hdrabkin** [comment]
AH; ok; found it; difficult to find as Ctnnb1 has over 400 annotations and 1122 papers tagged for GO for the gene  but not yet used: So it was taking forever to load through our VPN (my internet is giving me grief this AM. 
Changed.

**Comment by RLovering** [comment]
Wonderful
thank you so much
Ruth
