### ISSUE TITLE
InterPro:IPR001723 - NR0B1 annotation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2981]
Hi 
please would you review the GO annotations in this record. There is only 1 paper PMID:9384387 that demonstrates P51843 | NR0B1/DAX1 binds DNA and in this paper it is binding single stranded hairpin loop. All other articles about this gene suggest this is a corepressor. Colin Logie has stated: Well, if the DNA binding is to single strand DNA, that is not evidence for DAX1 being a dbTF. The literature definitely points at a corepressor MF. Unless there is a convincing double strand DNA binding (not single stranded) experiment. 
Note DAX1 also shown to bind RNA. 

There is also not strong evidence that this is a steroid hormone receptor

Many thanks
Ruth

@colinlog 
@pgaudet

**Comment by EBI-Hsinyu** [comment]
HI Ruth, 
Thank you for this. This InterPro entry includes a large group of nuclear hormone receptors (NRs). NR0B1 and NR0B2 (NR0B2 does not have a conventional DNA binding domain) are both included in this entry. It is likely that some members of this family don't have the typical NR functions. I have removed these GO terms. 
Regards, 
Hsin-Yu
