### ISSUE TITLE
Conflict of GO annotations between IPR032925 and IPR000418

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2982]
Hi

IPR032925 and IPR000418 are both associated with  P50548 | ERF, leading to GO annotations

GO:0003700 | DNA-binding transcription factor activity
GO:0003714 | transcription corepressor activity
As IPR000418 provides the GO:0043565 | sequence-specific DNA binding annotation as well, and based on paper https://pubmed.ncbi.nlm.nih.gov/7588608/ which does identify ERF as DNA binding could the GO term mapped from IPR032925 be changed to  GO:0001227
DNA-binding transcription repressor activity, RNA polymerase II-specific 
or to  GO:0001217 DNA-binding transcription repressor activity if the family associated with IPR032925 is not only associated with regulation of RNA pol II transcription

Thanks

Ruth

**Comment by EBI-Hsinyu** [comment]
Hi Ruth, 
Thank you for this. I have changed the GO term GO:0003714  in IPR032925 to GO:0001217.
Regards, 
Hsin-Yu
