### ISSUE TITLE
NTNU SKOR2 dispute Q2VWA4	GO:0000981	ECO:0000255 (ISM)	PMID:19274049

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2983]
Hi Marcio (NTNU)

Q2VWA4 | GO:0000981 | ECO:0000255 (ISM) | PMID:19274049

Discussion so far

Ruth Lovering | 07-MAY-2020 | I  don't think there is sufficient evidence to suggest this protein binds  DNA. InterPro does not associated the GO term DNA binding with the  InterPro record IPR009061 nor with IPR010919   IPR010919 record discusses how SKI (related to this gene) disrupts  Tx:Ski is able to disrupt the formation of a functional complex between  the Co- and R-SMADs, leading to the repression of TGF-beta, Activin and  BMP responses, resulting in the repression of TGF-signalling  Please remove the dbTF annotation Thanks Ruth
-- | -- | --
 
Marcio Luis Acencio | 11-MAY-2020 | Lambert  et 2018 suggest that this protein is a DbTF due to direct evidence for  its DNA binding in a HT-SELEX paper (PMID: 28473536). Maybe we can  remove or modify this annotation to accommodate this experimental  evidence.
 
Ruth Lovering | 19-MAY-2020 | Hi  Marcio, I have looked at this paper and checked the supplemental files  https://science.sciencemag.org/content/sci/suppl/2017/05/03/356.6337.eaaj2239.DC1/aaj2239_Yin_SM.pdf  you can search in the file for SKI etc but it is not listed, at least  none of the synonyms for SKOR1 and SKI are in this list. To demonstrate  try looking for ONECUT and if you increase the text size you will see  ONECUT in that circular graph. Consequently I do not believe this paper  provides any evidence that this family binds DNA. Please remove the  annotation Thanks Ruth
 
Marcio Luis Acencio | 19-MAY-2020 | Hi!  This protein is SKOR2  and it is possible to find its PMW in the Table  S2  (https://science.sciencemag.org/highwire/filestream/693922/field_highwire_adjunct_files/1/aaj2239_Yin_SM_tables_S1-S6.xlsx)  of the paper. So I believe that we should either keep this annotation  or change it to IDA supported by the Science paper.

**Comment by RLovering** [comment]
@colinlog

**Comment by colinlog** [comment]
It looks quite ok to me at first sight, although TAATTAA may also represent a favoured minor groove binding mode without much specificity. If Arttu Jolma sees a problem with this motif for SKOR2, he will tell me. Meanwhile, yes, annotation of the 544 human proteins for which this high throughput SELEX table of the Yin Science Paper provides a DNA-binding domain - target DNA motif relation in its S2 data sheet is something good to do. Even though there are no unique protein identifiers, there are geneIDs in the S1 file...   ;-)     I note that the Supplementary file does not contain the ARID factors that have the AT-hooks, and nor TBP, so quite clean with respect to GTFs and coregulators.

**Comment by RLovering** [comment]
Arttu Jolma confirms: SKOR2 seems to have a semi-decent SAND domain in it and although the binding site looks quite different from the other SANDs I would still give it a pretty decent chance for being a real TF. Yin et al paper also used E. Coli derived protein, so it can’t be a carryover of some specific TF from the lysates as with the Jolma 2013 things where we were using mammalian cell lysates.

So we will keep the dbTF annotations

Thanks for your patience

Ruth

**Comment by RLovering** [comment]
Hi Marcio
Please could you remove this ISM annotation which references InterPro IPR010919. The InterPro record IPR010919 does not provide a mapping to DNA binding. Therefore this annotation is not following GOC guidelines.
  | UniProtKB | Q2VWA4 | SKOR2 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255 | ISM | PMID:19274049 | InterPro:IPR009061\|InterPro:IPR010919 | 9606 | NTNU |

UniProtKB | P84550 | SKOR1 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255 | ISM | PMID:19274049 | InterPro:IPR009061\|InterPro:IPR010919 | 9606 | NTNU |  

Thanks

Ruth

**Comment by mlacencio** [comment]
Hi @RLovering!

I have deleted ISM-based annotations for SKOR1 and SKOR2. I will create soon new annotations based on HT-SELEX papers. 

Thanks

Best,

Marcio

**Comment by RLovering** [comment]
Hi Marcio

Thank you for confirming. Although I have already added SKOR1 and 2 DNA binding annotations based on that paper. I was also wondering if we should annotate all proteins listed in that paper to DNA binding. Colin has already identified all the UniProt IDs so these don't need to be found again. 

Colin and Pascale are you happy to have all proteins identified by this HT-SELEX paper annotated to sequence-specific double-stranded DNA binding. Due to the way these experiments are performed and the necessity to clone each gene and express them individually in e.coli I think this should be IDA evidence.

Colin has already identified all the UniProt IDs in the supplemental table so this would be straightforward. 

Best

Ruth

**Comment by colinlog** [comment]
Yes Ruth, the SELEX experiment can certainly demonstrate sequence specific-DNA binding (GO:0043565), and it is a direct assay, albeit high-throughput and performed at the hand of a robot, by all means.

**Comment by pgaudet** [comment]
All annotations from this paper have been removed. Thanks @mlacencio
