### ISSUE TITLE
InterPro2GO peptidase annotations for proteasome subunits

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#2984]
It seems established that the catalytic (threonine-type endopeptidase) activity of the proteasome resides specifically in 3 of the beta subunits: beta1, beta2 and beta5 (see PMID:28583440 for recent review).

Most of the descriptions for the InterPro entries for proteasome subunits also mention this specificity, e.g:
Proteasome, subunit alpha/beta (IPR001353)
"The proteasome consists of four stacked rings composed of alpha/beta/beta/alpha subunits. There are seven different alpha subunits and seven different beta subunits [6]. Three of the seven beta subunits are peptidases, each with a different specificity.
The proteasome subunits are related to N-terminal nucleophile hydrolases, and the catalytic subunits have an N-terminal threonine nucleophile.
This entry contains threonine peptidases and non-peptidase homologues belong to MEROPS peptidase family T1 (proteasome family, clan PB(T)). The family consists of the protease components of the archaeal and bacterial proteasomes and the alpha and beta subunits of the eukaryotic proteasome."

But several InterPro2GO associations aren't consistent with just beta1, beta2 and beta5 being the peptidases.  I think some edits are required - suggestions below.
(Note these suggestions are based on reviewing GO annotations for fly (D. melanogaster) proteasome subunits, so there may well be additional InterPro entries worth reviewing.)

==

Proteasome, subunit alpha/beta (IPR001353)
- threonine-type endopeptidase activity (GO:0004298)
=> remove this GO term  (this entry is for all the alpha and beta subunits (and includes "non-peptidase homologues")

==

Proteasome B-type subunit (IPR023333)
- threonine-type endopeptidase activity (GO:0004298)
=> remove this GO term (this entry is for all beta subunits)

==

Proteasome subunit beta 4 (IPR016295)
- threonine-type endopeptidase activity (GO:0004298)
=> remove this term (this isn't a catalytic subunit, as the description says: "...This group represents the beta type-4 subunit (MEROPS identifier T01.987) from the proteasome endopeptidase complex, which is one of the non-peptidase subunits.")

==

Proteasome alpha-subunit, N-terminal domain (IPR000426)
- endopeptidase activity (GO:0004175)
=> remove this GO term (non-cataltyic subunit)

==

Peptidase T1A, proteasome beta-subunit (IPR000243)
- endopeptidase activity (GO:0004175)
=> replace with more specific "threonine-type endopeptidase activity (GO:0004298)"

==

Proteasome beta-type subunit, conserved site (IPR016050)
- endopeptidase activity (GO:0004175)
=> replace with more specific "threonine-type endopeptidase activity (GO:0004298)"

==

Proteasome subunit beta 1 (IPR035202)
- [no GO-MF term]
=> add "threonine-type endopeptidase activity (GO:0004298)"

==

Proteasome subunit beta 2 (IPR035206)
- [no GO-MF term]
=> add "threonine-type endopeptidase activity (GO:0004298)"

==

Proteasome subunit beta Pre3 (IPR037559)
- threonine-type endopeptidase activity (GO:0004298)
=> This one is good!

==

Tagging: @happy-lorna, @typhainepl, @EBI-Hsinyu, @hattrill @bmeldal

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 
This is very helpful. Thank you. I have updated all the entries. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu!

**Comment by sjm41** [comment]
Hi @EBI-Hsinyu 

I just had cause to review these entries again, and realised I was thoroughly confused by the dichotomy in nomenclature between yeast/flies and vertebrates (where the same numbers are used to refer to different subunits....)

The following changes should be made:

Proteasome subunit beta 1 (IPR035202)
=> remove threonine-type endopeptidase activity (GO:0004298)
(This refers to vertebrate PSMB1 or fly Prosβ6, a non-peptidase subunit)

Proteasome subunit beta 2 (IPR035206)
=> remove threonine-type endopeptidase activity (GO:0004298)
(This refers to vertebrate PSMB2 or fly Prosβ4, a non-peptidase subunit)

Proteasome subunit beta 7 (IPR035216)
=> add threonine-type endopeptidase activity (GO:0004298)
(This refers to vertebrate PSMB7 or fly Prosβ2, a peptidase subunit)

Proteasome beta-type subunit, conserved site (IPR016050)
=> remove threonine-type endopeptidase activity (GO:0004298)
(This site is found in both peptidase and non-peptidase subunits)

**Comment by sjm41** [comment]
also tagging @sarach06 and @blazaropinto

**Comment by ValWood** [comment]
@ValWood  tagging myself to check PomBase

**Comment by blazaropinto** [comment]
Hello,

Thank you so much for checking that, I made the following changes, please let me know if you agree with them:

IPR035202:
GO:0004298 removed, 
GO:0010498 added

IPR035206:
GO:0004298 removed, 
GO:0010498 added

IPR035216:
GO:0004298, GO:0010498 added

IPR016050:
GO:0004298 removed

Best regards,
Beatriz

**Comment by sjm41** [comment]
Those changes look good to me, thanks @blazaropinto !
