### ISSUE TITLE
NTNU P12755 SKI is this a dbTF or a coTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2985]
Hi Marcio

Disputed | NTNU | P12755 | GO:0000981 | ECO:0000255 (ISM) | PMID:19274049 | InterPro:IPR009061\|InterPro:IPR010919

Ruth Lovering | 07-MAY-2020 | I  don't think there is sufficient evidence to suggest this protein binds  DNA. InterPro does not associated the GO term DNA binding with the  InterPro record IPR009061 nor with IPR010919  IPR010919 record discusses how SKI (related to this gene) disrupts  Tx:Ski is able to disrupt the formation of a functional complex between  the Co- and R-SMADs, leading to the repression of TGF-beta, Activin and  BMP responses, resulting in the repression of TGF-signalling
-- | -- | --
 
Marcio Luis Acencio | 11-MAY-2020 | Lambert  et al 2018 classifies this protein in DbTF and provide the following  comment: Binds specifically to GTCTAGAC via EMSA in one study (PMID:  9452486). But, needs to form complexes with other proteins, such as NFI,  to bind to DNA in another (PMID: 9380514). Related to SKIL, which also  has evidence for DNA binding (PMID: 9824161)

Ruth response to above 20/5/2020
Thanks for the papers, ideally these papers should be annotated.
However, the annotation based on InterPro are incorrect because these record do not provide evidence for DNA binding. Please remove these ISM annotations.

I need more time to check these papers, but thank you so much for providing them.

Thanks

Ruth

**Comment by pgaudet** [comment]
@mlacencio

**Comment by RLovering** [comment]
The EMSA in PMID: 9452486 uses nuclear extract. It seems to me that there is no evidence that this protein binds DNA on its own. However, following discussions with Arttu and Colin that SKOR1-2 do bind DNA based on HT-SELEX data the decision to annotate these proteins as dbTFs has been made. I do not think we should remove the coTF annotations as it looks like SKIL binds to TAF110 and therefore the requirement for another

**Comment by RLovering** [comment]
Sorry I forgot this issue was also about the use of InterPro IDs that do NOT support the annotation they are associated with. I have asked Pascale to create a dbTf annotation based on PMID:17469184.
Your dbTf annotation based on interpro domains still needs to be removed as it is not inline with GOC guidelines
Thanks
Ruth

**Comment by mlacencio** [comment]
Hi @RLovering,

Annotations removed! I will take a look again at SKI and SKIL to try to find out why they are classified as DbTF by Lambert et al 2018.

Thanks!

Marcio

**Comment by RLovering** [comment]
Hi Marcio

Thanks for helping so much with this. 
FYI Following Colin's advice we have decided to curate these as dbTFs by PAINT based on the fact that the SKOR DNA binding domain is present in SKI and SKIL. 

If you can find evidence to support SKI and SKIL as dbTFs that would be great, but if there is no literature to support this, at least a decision has been made at the moment for these. Please do add your findings to this ticket so that we can close it which ever way the decision goes

Best

Ruth

**Comment by mlacencio** [comment]
Hi @RLovering !

Although SKI and SKIL have been considered DbTF and are/will be annotated via PAINT, me, Astrid and Martin think that both proteins could be well annotated as DbTF supported by IDA taking into consideration, respectively, PMID:9452486 and PMID: 9824161. Why?

According to the new guidelines under preparation, sequence-specific DNA binding activity can now be demonstrated by ChIP as long as other requirements are met, namely, presence of DBD and experimentally validated transcriptional activity. We think that EMSA with nuclear extract and ChIP are equivalent in their ability to show DNA binding activity. In both types of experiment we can't guarantee that the protein of interest is directly binding DNA and then we need extra evidence such as the presence of DBD and demonstration of transcription activity. Therefore, as SKI and SKIL have DBDs and in both PMID:9452486 and PMID: 9824161 papers the DNA binding activity is shown via EMSA supershift with nuclear extract and transcription activity is shown via promoter reporter gene assay, then we think these papers could be used for IDA annotation of SKI and SKIL.

Best,

Marcio

**Comment by colinlog** [comment]
very good, we all agree that these are dbTFs indeed.

**Comment by pgaudet** [comment]
Thanks everyone !
