### ISSUE TITLE
IPR001628 not always host cell nucleus (GO:0042025)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2986]
Hello, 

IPR001628 is mapped to host cell nucleus (GO:0042025) - This cannot be right ? I dont think viruses or symbionts have nuclear receptor genes? 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale,
You are right. I have removed this term. 
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks !
