### ISSUE TITLE
Review annotation of RGD:3370 to GO:0003713 transcription coactivator activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2987]
Hello @gthayman 

RGD:3370 Ppard is annotated to GO:0003713 | transcription coactivator activity from PMID:19965574. However it is a DNA binding transcription factor. It should be annotated to 'DNA-binding transcription activator activity, RNA polymerase II-specific'. Acting synergistically with other transcription factors do not justify annotating it as a cofactor (assuming this is the reason it was annotated as a coTF). 

Thanks, Pascale.

**Comment by gthayman** [comment]
Fixed.
