### ISSUE TITLE
MGI annotations to PMID:2017177

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2988]
Hi

please review the following annotations associated with this paper PMID:2017177
There is good evidence of GATA3 binding DNA and regulating transcription in figure 6, so please use the GO term 

GO:0001228 DNA-binding transcription activator activity, RNA polymerase II-specific
in this annotation
  | P23772 | Gata3 | enables | GO:0003713 | transcription coactivator activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:2017177

Also please delete the annotation:

  | P04234 | CD3D | enables | GO:0003713 | transcription coactivator activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:2017177

Thanks

Ruth

**Comment by hdrabkin** [comment]
H @RLovering 
I assume you mean to delete the coactivator activity term for Gata3, not Cd3d? Currently Cd3d has no such annotation (in fact, the PMID is only used for Gata3.

**Comment by hdrabkin** [comment]
done

**Comment by RLovering** [comment]
Hi Harold
Thank you so much 

unfortunately CD3D P04234 does have this annotation see
https://www.ebi.ac.uk/QuickGO/annotations?reference=2017177&aspect=molecular_function&assignedBy=MGI 
If you could remove this that would be great

Best

Ruth

**Comment by hdrabkin** [comment]
@RLovering 
I am not seeing it in our DB. I have attached screenshots of the only MF annotations for Cd3d in MGI; the only MF annotations are all load-related. The only ISOs to P04234 are for protein binding terms.
![Screen Shot 2020-05-20 at 10 09 07 AM](https://user-images.githubusercontent.com/10440080/82456417-3131e180-9a82-11ea-8665-9ba8e0df8a71.jpg)
![Screen Shot 2020-05-20 at 10 13 04 AM](https://user-images.githubusercontent.com/10440080/82456715-97b6ff80-9a82-11ea-832d-afc4c38efdae.jpg)

**Comment by hdrabkin** [comment]
The only use of PMID:2017177 in our DB is for Gata3

**Comment by RLovering** [comment]
ok this is so weird. 
I will leave this open, maybe someone has deleted it in the last couple of weeks and so the change hasn't yet appeared in Protein2GO
Thanks again
Ruth

**Comment by hdrabkin** [comment]
Very weird because all of these annotation change requests come to me and I have no record of anything having to do with Cd3d.

**Comment by ukemi** [comment]
I see it to the human gene, originating at MGI, in AmiGO. I suspect the primary annotation is an ISO with J:73065.

**Comment by hdrabkin** [comment]
But it isn't here in our DB; there is no such annotation to Cd3d via 73065.

**Comment by ukemi** [comment]
You're right. That's just weird. I see it in AmiGO2 as well. Can we check the file we provide to Alex for the human annotations that come from MGI?

**Comment by hdrabkin** [comment]
I've lost the link to the file (most likely when the servers were changed?)

**Comment by hdrabkin** [comment]
Found it; under 'custom'

**Comment by hdrabkin** [comment]
Yes; in that file there are multiple annotations using the PMID to CD3D; But none of them are in our db!!! argh.
File date is 2020-05-18 08:00; double-argh!   TR to Lori time!

**Comment by hdrabkin** [comment]
The paper is indexed to two genes, Gata3  (SynonymsGata-3, jal)and Tcrd,(complex cluster region, synonyms Tcrdelta, Tcr delta ); T3d is a synonym for Cd3d so it might have been miss-indexed at one time.

**Comment by RLovering** [comment]
Pascale has just noticed this is the CD3D human gene. How do you edit these?
Thanks
Ruth

**Comment by hdrabkin** [comment]
So in MGI, we have a 'special' J# 
We make an ISO annotation to the human protein, and then we supply a file to GOA where we convert the ISO to an IDA with the evidence code.  PMID used (which we store as a string in db

Example:
For mouse Cd3d, the annotation would read in ourdb
GO:123456 J:73065 ISO human uniprot in the inferred from; 
In our db, the annotation gets a property: external refence: PMID:234567 | IDA

Property is used to make an annotation in our gene_association.non_mouse file (gaf)
Human_UniProt id GO:123456 IDA PMID:234567
We noticed today that the file appears to not be undated properly (because we found the annotations in the file although they are not in the db

**Comment by hdrabkin** [comment]
We set up this file so that GOA gets from us as we take from GOA!

**Comment by hdrabkin** [comment]
In Noctua, we can't do it as described above. We make an ISO with the J#, but need to then make an annotation to the human protein in the same model. Don't know if this is ever picked up into Amigo yet

**Comment by pgaudet** [comment]
So... can you fix this ? It seems complicated!

**Comment by hdrabkin** [comment]
As soon as we fix our file on our end it will stop.

**Comment by hdrabkin** [comment]
OK; this is now fixed; non_mouse gaf we give to GOA should now not have it. it should disappear at Amigo/Quickgo, etc.

**Comment by pgaudet** [comment]
OK thanks !

**Comment by RLovering** [comment]
Note that this annotation is still in QuickGO 

UniProtKB:P23771 | GATA3 | enables | GO:0003713 | ECO:0000314 | PMID:2017177 |   | 9606   Homo sapiens | MGI
transcription coactivator   activity | IDA

Should it have gone by now?

Thanks

Ruth

**Comment by hdrabkin** [comment]
I have no idea; I thought I fixed this. I'll check again.

**Comment by pgaudet** [comment]
Annotation is still in P2GO 
UniProtKB:P23771 | GATA3 | enables | GO:0003713 | ECO:0000314 | PMID:2017177 |   | 9606 Homo sapiens | MGI
transcription coactivator activity | IDA

**Comment by hdrabkin** [comment]
Have no annotation for GATA3 for  GO:0003713 here. This must be coming from a different gene where UniProtKB:P23771 has been incorrectly put into the with field. 
Trying to pin.

**Comment by hdrabkin** [comment]
Have checked this AM, and as of 10/7, annotation of mouse Gata 3 via ISO to P23771 to transcription coactivator activity GO:0003713 is gone in our public, and in the non-mouse file we generate. So depending on when GOA picks it up and reloads this into p2go, it should disappear.

**Comment by pgaudet** [comment]
Thanks @hdrabkin 
It's still there today, we'll check again later.

**Comment by hdrabkin** [comment]
Unfortunately, I don't know how frequently GOA picks up the non-mouse file.

**Comment by alexsign** [comment]
@hdrabkin @pgaudet The GOA updates all external sources every Saturday. Last update was on 11th of October. The file which is available now
http://www.informatics.jax.org/downloads/custom/gene_association.mgi_nonmouse
is from Sunday 12th of October. We have one day miss here, but this coming Saturday it should be fixed in P2GO. Please let me know in case you needed earlier.

**Comment by pgaudet** [comment]
No rush, thanks for checking !

**Comment by hdrabkin** [comment]
Thanks Alex. No rush;

**Comment by pgaudet** [comment]
All good now :)
