### ISSUE TITLE
 IPR024830 change mapped GO term

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2989]
Hi 

this record is mapping Glucocorticoid modulatory element-binding (GMEB) proteins 1 and 2 to transcription coactivator activity (GO:0003713)
However the record states that these proteins: bind to glucocorticoid modulatory elements and increases sensitivity to low concentrations of glucocorticoids[1, 2].
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR024830/
Please change the GO terms mapped to:
GO:0000978 RNA polymerase II cis-regulatory region sequence-specific DNA binding
and
GO:0001228 DNA-binding transcription activator activity, RNA polymerase II-specific
and
GO:0045944positive regulation of transcription by RNA polymerase II

if you think these are appropriate

Thanks
Ruth

**Comment by EBI-Hsinyu** [comment]
Hi Ruth, 
Thank you for this. I have updated this entry as you suggested. 
Regards, 
Hsin-Yu
