### ISSUE TITLE
NTNU GON4L not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2990]
Hi Marcio
I don't think this protein binds DNA. PMID: 29615614 states in discussion:Because Gon4l does not bind DNA directly, we predict that Gon4l-enriched genomic loci are direct targets of chromatin modifying protein complexes with which Gon4l associates[36]. Ref 36 is https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3093903/ which also does not suggest DNA binding capacity of GON4L.
In addiiton both Lambert and Tripathi lists both state that this is not a dbTF.
Thanks
Ruth

**Comment by pgaudet** [comment]
@mlacencio

**Comment by mlacencio** [comment]
@pgaudet and @RLovering, Q3T8J9/GON4L removed!  HT-SELEX also shows no binding of GON4L to any DNA specific sequence.

**Comment by RLovering** [comment]
This is great, thank you so much Ruth
