### ISSUE TITLE
revision to InterPro:IPR009057

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2991]
Hi

please would you look at the mappings or the proteins associated with the InterPro:IPR009057 record. 
Q3T8J9 | GON4L I am concerned about the annotation of DNA binding that is associated with this protein based on InterPro:IPR009057.
I don't think this protein binds DNA. PMID: 29615614 states in discussion:Because Gon4l does not bind DNA directly, we predict that Gon4l-enriched genomic loci are direct targets of chromatin modifying protein complexes with which Gon4l associates[36]. Ref 36 is https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3093903/ which also does not suggest DNA binding capacity of GON4L. In addiiton both Lambert, 2018 and Tripathi, 2016 state that this is not a dbTF. 

In addition, in IPR033277 states that GON-4-like has transcriptional repressor activity, probably as part of a complex with the DNA-binding protein YY1, the co-repressor Sin3a, and the histone-modifying enzyme histone deacetylase 1 (HDAC1). 
Thus IPR033277 and IPR009057 almost contradict each other. Not completely but usually DNA binding and regulation of transcription would suggest the GO term DNA-binding transcription factor would be associated with the protein and usually corepressors do not bind DNA. This rule is not always true though!

Thanks Ruth 

see also request for NTNU to remove their annotation to this protein https://github.com/geneontology/go-annotation/issues/2990

**Comment by EBI-Hsinyu** [comment]
Hi Ruth, 
It is always a bit risky to give a GO term to a big domain entry such as IPR009057. When InterPro just started the curators at the time believe these GO terms can help the community to predict functions of these proteins. With the aid of more publications and specific models, now we can provide more accurate information (for instance by creating IPR033277 entry). However, this means that the GO terms the past curators gave may not always consistent with the GO terms we give now. Moreover, sometimes we have to balance the function prediction/specific  function description of InterPro entries, so it would be difficult to lose certain GO terms. It is great that you send us these feedbacks, so we can improve our annotations. Thank you for this. I have removed the term in IPR009057.  
Best regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks !
