### ISSUE TITLE
IPR017287-Retinal rod rhodopsin-sensitive cGMP 3', 5'-cyclic phosphodiesterase, delta subunit activity term

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#2992]
Hi,
This entry represents the phosphodiesterase (PDE) delta subunit. Its description suggests that it acts as a prenyl-binding protein and participates in the transport of PDE6 catalytic alpha/beta subunits. Similar suggestion from fly paper as well (PMID:18503409)
so I'd suggest to disassociate the GO activity term 3',5'-cyclic-nucleotide phosphodiesterase activity (GO:0004114) for this entry.

@hattrill 
@sjm41

**Comment by hattrill** [comment]
tagging @happy-lorna

**Comment by typhainepl** [comment]
Hi,
Thank you for highlighting this. I have removed the Go annotation from the InterPro entry and added the reference to the description.
Typhaine

**Comment by phanivg** [comment]
Thank you Typhaine!
