### ISSUE TITLE
Review anotation of MGI:97712 to GO:0003713 transcription coactivator activity PMID:23447615

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2993]
Hi @hdrabkin 

In PMID:23447615, MGI:97712  is annotated to GO:0003713 transcription coactivator activity, but see Fig 1E - they tested a reporter gene driven Prx1 binding sites:  
>to more closely examine the relationship between Sox2 and Prx1 in regulating transcription in adult NSCs, we prepared luciferase reporter constructs that contained a minimal tk promoter with multimerized Prx1 binding sites

We suggest you change the annotation to 'DNA-binding transcription activator activity, RNA polymerase II-specific' 

Thanks, Pascale

**Comment by hdrabkin** [comment]
done
