### ISSUE TITLE
Is a CTCFL dbTF or a coTF ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#2996]
Hi @colinlog 

CTCFL (https://www.uniprot.org/uniprot/Q8NI51) seems to bind DNA, suggesting it is a dbTF; however the UniProt entry seems to describe roles that seem like coTF roles: "Directly binds the unmethylated H19 ICR and recruits the PRMT7 methyltransferase". 

PMID:16140944 seems to indicate it is a dbTF. 

Is a CTCFL dbTF or a coTF ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Note that this is to annotate PTHR24406.

**Comment by colinlog** [comment]
Short asnwer: yes, like CTCF, CTCFL should be annotated to dbTF. That is how the transcription field currently considers it!

Long answer:
Yes, however, it It is one of two DNA binding proteins known to bind to an isotropic DNA motif that defines the basis of chromatin loops that underlie the emergence of topologically associating domains (TADs). CTCFL, aka BORIS, is important for male meiosis, I believe.
Let's for sure put it down as a dbTF, as the GO:00xxxxx for loop anchor protein has not yet been generated... that term should tie-in with terms already used to annotate the cohesin complex and the molecular functions 'chromatin extrusion', 'chromatin looping' and the chromatin term TAD.

**Comment by pgaudet** [comment]
Thanks.
