### ISSUE TITLE
SKOR1 and SKOR2 dbTFs not corepressors

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#2998]
Hi 

WRT InterPro:IPR028762

sorry to bother you but in the transcription review it has been agreed that SKOR1 and SKOR2 and probably SKI and SKIL are dbTFs. If you have evidence that these do not bind DNA at all then please let me know. SKOR1 and SKOR2 have been shown by Yin et al by HT-SELEX to bind DNA although SKI and SKIL do not appear to bind DNA alone. 
But if you agree with this decision please could you remove the mapping to the GO term transcription corepressor activity (GO:0003714) from InterPro:IPR028762

https://github.com/geneontology/go-annotation/issues/2983

P84550 | SKOR1
Q2VWA4 | SKOR2

many thanks
Ruth

**Comment by mlacencio** [comment]
@RLovering!

Nice that we have reached an agreement about these DbTFs. Regarding the deletion of the mapping mention by you, I am afraid to say that I have no idea how to do it. I have no access to the GO:0003714 annotation in Protein2GO that is assigned to REFG.

Best,

Marcio

**Comment by RLovering** [comment]
Hi Marcio
sorry I meant this to be directed to InterPro. I have edited the request to make this clearer. I will remove you from this ticket
Best
Ruth

**Comment by pgaudet** [comment]
@EBI-Hsinyu @typhainepl @happy-lorna 

Please do the same for IPR028376 (SKOR2).  IPR028762 mentioned in the first comment corresponds to SKOR1. 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Ruth, 
Thank you for this. Could you send me the reference (from Yin et al), please? So, I can update these entries. 
Regards, 
Hsin-Yu

**Comment by RLovering** [comment]
Hi 
So sorry to have missed this information. Please see https://europepmc.org/article/MED/28473536
Table S2 (https://science.sciencemag.org/highwire/filestream/693922/field_highwire_adjunct_files/1/aaj2239_Yin_SM_tables_S1-S6.xlsx) of the paper. 
Thanks
Ruth

**Comment by EBI-Hsinyu** [comment]
Thank you! 
Hsin-Yu

**Comment by EBI-Hsinyu** [comment]
I have deleted this term GO:0003714 in both entries. 
Hsin-Yu

**Comment by RLovering** [comment]
wonderful thank you so much
Ruth
