### ISSUE TITLE
Duplicate IBA annotation with different withs

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#2999]
Hi, have a bit of an oddity going on with D.mel Mef2 (P40791; FBgn0011656).

Has IBA annotation:

GO:0000976 | transcription regulatory region sequence-specific DNA binding

from PANTHER:PTN000235373

but the other IDs in the with differ:
FB:FBgn0011656|MGI:MGI:99458|PANTHER:PTN000235373|UniProtKB:Q02078|UniProtKB:Q06413|UniProtKB:Q14814|ZFIN:ZDB-GENE-980526-253|ZFIN:ZDB-GENE-990415-163|ZFIN:ZDB-GENE-990415-164

and

UniProtKB	P40791	enables	GO:0000976	PMID:21873635	ECO:0000318	MGI:MGI:99458|PANTHER:PTN000235373|TAIR:locus:2043600|TAIR:locus:2052420|TAIR:locus:2137070|TAIR:locus:2146774|TAIR:locus:2152511|UniProtKB:F4KGH9|UniProtKB:P29381|UniProtKB:Q38876|UniProtKB:Q9S7Q7|UniProtKB:Q9S9U2|ZFIN:ZDB-GENE-980526-253|ZFIN:ZDB-GENE-990415-163|ZFIN:ZDB-GENE-990415-164		
 

can see it in AmiGO, so not a GOA thing.

**Comment by hattrill** [comment]
One more to add:

NFAT FBgn0030505
GO:0005667:PMID:21873635:ECO:0000318 with PANTHER:PTN000969601
UniProtKB:A8JUV3
UniProtKB:E1JJP5
UniProtKB:E1JJP6
UniProtKB:M9PH25
UniProtKB:Q86NT0
UniProtKB:Q9GU53
UniProtKB:Q9VYA6

with MGI:MGI:102463|PANTHER:PTN000969601
or 
MGI:MGI:102463|MGI:MGI:102469|MGI:MGI:1920431|PANTHER:PTN000969601

**Comment by pgaudet** [comment]
@dustine32 Can you please look into this ?

**Comment by pgaudet** [comment]
@hattrill 
Do you remember this one? 

Just checking that I understand what you meant - you were seeing different 'with' in AmiGO versus QuickGO, is this right ? 

Now this looks OK to me: 

**Mef2 (P40791; FBgn0011656).**

QuickGO: 
MGI:MGI:104526
OR
MGI:MGI:99458
OR
MGI:MGI:99532
OR
MGI:MGI:99533
OR
PANTHER:PTN000235373
OR
PomBase:SPBC19G7.06
OR
UniProtKB:Q02078
OR
UniProtKB:Q02080
OR
WB:WBGene00003182 

AmiGO:
PANTHER:PTN000235373
UniProtKB:Q02078
MGI:MGI:104526
MGI:MGI:99532
WB:WBGene00003182
UniProtKB:Q02080
PomBase:SPBC19G7.06
MGI:MGI:99458
MGI:MGI:99533




-----
NFAT FBgn0030505 UniProt:M9PH25 

QuickGO: 
 MGI:MGI:102463
OR
MGI:MGI:102469
OR
MGI:MGI:1920431
OR
PANTHER:PTN000969601
OR
UniProtKB:O94916
OR
UniProtKB:Q12968 

AmiGO: 
 PANTHER:PTN000969601
MGI:MGI:1920431
UniProtKB:Q12968
UniProtKB:O94916
MGI:MGI:102463
MGI:MGI:102469



These now look identical. 

Close ?

**Comment by hattrill** [comment]
Yes.
