### ISSUE TITLE
use of NOT

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#3]
I just started using NOT and reilised I have used it
incorrectly.

I annotated a gene to
NOT Golgi to vacuole transport
based on the evidence of no mis-sorting of
carboxypeptidase Y in PMID: 14575697 suggesting that
the Pep12 homolog is not required for vacuolar protein
transport

I reilised it was incorrect to annotate somthing to NOT 
based on this kind of negative evidence.
i.e. not required for but may be involved in
and
not required for this particular product (assay)

This may be an example where the annotation guidelines
could be extended to make the use of NOT expicit for
first time users.
with examples.

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/3":https://sourceforge.net/p/geneontology/annotation-issues/3

**Comment by deustp01** [comment]
reopened by accident (text was misread as a GitHub cross-reference), so this can be closed again by someone with the right powers @ValWood ?
