### ISSUE TITLE
Remove transcription corepressor annotation MGI:2443473 Skor1 from PMID:15528197

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3000]
Hi @hdrabkin 
MGI:2443473 Skor1 is annotated to transcription corepressor  from PMID:15528197. 

However there is no evidence of DNA binding, there is GAL fusion data, so the reg transcription can stay. Please remove MF annotation. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
done

**Comment by pgaudet** [comment]
Thanks
