### ISSUE TITLE
TAF annotations to GO:0051123 'RNA polymerase II preinitiation complex assembly'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#3002]
@RLovering @pgaudet 

I'm reviewing the C. elegans TAF annotations and we have at least one ISS annotation to GO:0051123 'RNA polymerase II preinitiation complex assembly' based on the original IMP annotations to yeast TAFs from this paper (Figure 3, I think):

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC165660/

What are your thoughts on annotations to this term, for TAFs or any other transcriptional regulator?  

Note past discussion on annotating to 'complex assembly' terms with IMP:  #2213

**Comment by pgaudet** [comment]
Thanks for sending this @vanaukenk 

I'll pass this along to @colinlog. While I agree that assembly is required for the activity, and I am aware there was a lot of work to determine the order of assembly of the various subunits, I am not sure this is much relevant for the activity. 

Moreover those subunits are probably the target of the assembly, not the mediators (although you can argue that if subunit 1 is not present, then subunit 2 cannot assemble). 

What do you think ? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
Thanks @pgaudet 

I think in the past when we've talked about this issue, the key distinction has been between gps that function as complex assembly chaperones, say, versus gps that are actually being assembled into a complex.  The former could perhaps reasonably be annotated to a complex assembly BP, but the latter not.

Let's see what @colinlog says.

**Comment by pgaudet** [comment]
@colinlog Can you please let us know what you think about that one?

**Comment by pgaudet** [comment]
Hi @vanaukenk 

After discussion with @colinlog , we believe these annotations are OK. We have improved the definitions of this term (and parents/siblings) to match what the papers are describing, see 

https://github.com/geneontology/go-ontology/issues/25954

Thanks, Pascale
