### ISSUE TITLE
Review NTNU annotations to RCOR1, RCOR2, and RCOR3

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3007]
Hi @mlacencio 

MIDEAS,  RCOR1, RCOR2, and RCOR3 (Q6PJG2, Q9UKL0, Q8IZ40, Q9P2K3) are annotated to 
GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific
by ISM based on domains : InterPro:IPR001005|InterPro:IPR009057

but they are believed to be cofactors. Please remove annotations. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Marcio

pleaes note that resolved tickets have been raised with InterPro to remove the DNA binding mapping associated with IPR009057 and IPR001005

https://github.com/geneontology/go-annotation/issues/2991 InterPro confirmed removal of DNA binding from IPR009057

https://github.com/geneontology/go-annotation/issues/988 InterPro confirmed removal of DNA binding from IPR001005

It is therefore not appropriate to use these InterPro records to support dbTF annotations. In addition RCORs are considered to be coTFs not dbTFs by the community.

Thanks

Ruth

**Comment by mlacencio** [comment]
@RLovering and @pgaudet: removed after discussion with Astrid and Martin. We have agreed that these annotations should be removed and this has been done. We think these proteins could be used for improving the curation guidelines: If experimental evidence for coTF is strong enough for a candidate DbTF, then we should remove annotations with computational evidence supporting its role as DbTF.

**Comment by pgaudet** [comment]
Hi @mlacencio 

Thanks for looking into this. 

A few comments: 
* 
>  If experimental evidence for coTF is strong enough for a candidate DbTF, then we should remove annotations with computational evidence supporting its role as DbTF.

This is a general rule. If computational evidences are inconsistent with annotations, we dispute them to InterPro, who remove mappings. 

However in this case, as we pointed out many times, neither IPR001005 nor IPR009057 have any GO term mappings, so it is not appropriate anyway for you to assign one. 

* Based on the explanation above, this annotation should also be deleted : 

  | NTNU | Q6PJG2 | MIDEAS |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR001005\|InterPro:IPR009057| ECO:0000255 | (ISM)


Thanks, Pascale

**Comment by mlacencio** [comment]
Hi @pgaudet,

Thank you for the observations.

Annotation removed due to the lack of GO term mappings to the Interpro domains. 

Regarding the biological function of this protein, me and Astrid will take a look at the literature and pertinent databases to check if there is strong evidence for DbTF or coTF activity for this protein.

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks @mlacencio 

The queries we had about those 4 genes have been addressed, I'm closing this ticket.
