### ISSUE TITLE
RFT1 not a floppase/translocase/lipid transporter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3009]
S. cerevisiae Isn't a floppase (or even a translocase) according to most S. c publications (I have confimred this via communication with SGD. I originally suggested the annotation be added but  @edwong57  pointed out this would be incorrect)

All of the existing annotations to this term stem from a single publication:
Translocation of lipid-linked oligosaccharides across the ER membrane requires Rft1 protein. Nature 415(6870):447-50 PMID: 11807558

To remove: 
 - [ ] UniProtKB:P38206 | RFT1 | enables | GO:0034202  glycolipid floppase activity | ECO:0000304 TAS | Reactome:R-SCE-449765 |   | 559292 Saccharomyces cerevisiae (strain ATCC 204508 / S288c) | Reactome

- [x] InterPro IPR007594 remove "lipid transporter activity"

-  [ ] PAINT annotation

This T. brucei paper is the most informative article
http://europepmc.org/article/MED/23720757
"These results suggest that rather than facilitating M5-DLO flipping, Rft1 facilitates conversion of M5-DLO to mDLO by another mechanism, possibly by acting as an M5-DLO chaperone."

I think all you can say right now is that it is involved in 

GO:0006488 dolichol-linked oligosaccharide biosynthetic process
 This can be  inferred from
https://www.uniprot.org/uniprot/Q383B3

**Comment by deustp01** [comment]
@ValWood could you say more about what's needed here and how it's different from the issue in ticket phospholipid scramblase activity, odd comment #19470? Thanks

**Comment by ValWood** [comment]
This is a separate annotation issue. As far as we know, RTF1 isn't a transporter at all. 

The ontology tracker issue is  that the comment is slightly  confusing when you see it out of context of the knowledge of the other terms . It  has some unnecessary information, and some missing information. But that ticket isn't really related to this ticket, other than I  opened both  when looking at RFT1. The  odd comment #19470 first when I *thought* that RTF1 was a transporter. Once  @edwong57  convinced me that it wasn't I opened this one for the corrections.

Very early yeast papers described RFT1 as a transporter/translocase, but none of the later papers agreed with this interpretation.

**Comment by typhainepl** [comment]
Hi @ValWood, thanks for highlighting this. I have updated the InterPro entry.

**Comment by ValWood** [comment]
seems to be fixed.
