### ISSUE TITLE
Invalid GO id for IC

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#3011]
We get this annotation during our GOA mouse load; It was made by'UniProt"

GI:1347481	Foxc2	GO:0005634	IC GO:0044212	PMID:9169153
Id was merged into GO:0000976 

@pgarmiri could you get this changed please, or reassign to whoever can fix p2go annotations
Thanks much.

**Comment by pgarmiri** [comment]
Hi,
I had a look at the paper and there were evidence to change to the supporting GO ID for the IC annotation ( GO:0001216 'DNA-binding transcription activator activity').
Hope this is okay with you,
Penelope

**Comment by hdrabkin** [comment]
That's good; just had to have a valid id to pass the checks during our GOA mouse load. Thanks much!
