### ISSUE TITLE
PAINT annotation of yeast genes to non-yeast term: GO:0005813 centrosome

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-annotation#3012]
There are 12 yeast IBA annotations to GO:0005813 centrosome even though there's a constraint: "GO:0005813 | centrosome | Never in Taxon | 4751 | Fungi"
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005813#term=history

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0005813%22&sfq=document_category:%22bioentity%22

This is a recurrence of https://github.com/geneontology/go-annotation/issues/1424
>yeast do not have a centrosome rather a functional equivalent called the spindle pole body (GO:0005816)

**Comment by ValWood** [comment]
Note that I plan in the future to survey the SPB/centrosome community about merging these terms. They are not only "functional equivalents' they are the same component with a different name (most subunits are conserved). Furthermore, many many yeast researchers now refer to the SPB as the centrosome in their papers.

So, for now, it is best to remove, but I think a merge of these is probably imminent. This would allow the metazoan userbase to take advantage of all of the very cool pombe and cerevisiae research.

The common parent "microtubule organizing center (GO:0005815)" is OK for now, but this distinction is really just semantics, which shouldn't be baked into GO.

e.g
https://pubmed.ncbi.nlm.nih.gov/29722648/
Opposing Bqt4-dependent Lem2 mobility are factors that stabilize Lem2 beneath the centrosome, where Lem2 plays a crucial role in kinetochore maintenance. Our data prompt a model in which Bqt4-rich nuclear subdomains are 'safe zones' in which collisions between transcription and replication are averted and heterochromatin is reassembled faithfully.

and
https://www.pombase.org/reference/PMID:28619713
Molecular model of fission yeast centrosome assembly determined by superresolution imaging.

**Comment by marcfeuermann** [comment]
Addressed with https://github.com/geneontology/go-annotation/issues/3653
