### ISSUE TITLE
InterPro2GO: tRNA N6-adenosine threonylcarbamoyltransferase, TsaD (IPR022450)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3013]
Hi,

This entry is currently associated with this GO-MF term:
metalloendopeptidase activity (GO:0004222)

Can you check this is accurate across species?

The description does say:
"A member of Kae1 family has been characterised as a DNA-binding protein with apurinic endopeptidase activity. In contrast, the rare characterised members of the TsaD family show O-sialoglycoprotein endopeptidase (3.4.24.57) activity after export."
which does support that at least some proteins with this domain have endopeptidase activity.

But the InterPro name suggests it's a transferase (instead of/as well as a hydrolase).
Morever, the single yeast (P43122) and human (Q9H4B0) proteins with this domain appear to be characterized as transferases rather than hydrolases (peptidases).
https://www.uniprot.org/uniprot/P43122
https://www.uniprot.org/uniprot/Q9H4B0

@hattrill @EBI-Hsinyu

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 

Thank you for this. You are right.  I have removed this GO term and updated the abstract. 

Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Great, thanks,
