### ISSUE TITLE
InterPro2GO: PLAC (IPR010909)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3016]
Hi,

This entry is for a domain "present at or near the C-terminal of various enzymes and matrix proteins".  Some of these are peptidases, but not all.

E.g. four of the human proteins with this domain (Q8N6G6/ADAMTSL1, Q86TH1/ADAMTSL2, P82987/ADAMTSL3, Q6UY14/ADAMTSL4) all have this comment in UniProt:
"Although strongly similar to members of the ADAMTS family it lacks the metalloprotease and disintegrin-like domains which are typical of that family."

So I think the associated "peptidase activity" term should probably be removed.

@hattrill @EBI-Hsinyu

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have removed this term.
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks!
