### ISSUE TITLE
NCOA1, NCOA2 and NCOA3 are coTFs, not TFs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3017]
Hi @mlacencio 

NCOA1 (Q15788), NCOA2 (Q15596) and NCOA3 (Q9Y6Q9) and annotated by NUTU as dbTF by ISM and ISA from PMID:19274049, GO_REF:0000113

Please change/remove. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Marcio
please note Colin's comments on this issue: For the NCOAs, there is very much literature supporting a coregulator (coactivator) MF annotation, and until there is good experimental proof that their HLH domain actually does bind DNA we should indeed refrain from giving them dbTF status.  I went back and forth on these a few times this year  ;-)  

Best

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
@mlacencio Annotations are not removed from Q9Y6Q9 NCOA3

**Comment by mlacencio** [comment]
@pgaudet ,

Done!

Best,

Marcio
