### ISSUE TITLE
InterPro2GO: Signal peptidase complex subunit 3 (IPR007653)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3018]
This is one of two subunits of the 'signal peptidase complex' characterized as having catalytic activity.
I think the current MF term of 'peptidase activity' could be changed to the more specific "serine-type peptidase activity (GO:0008236)" to match the InterPro2GO entries for the other catalytic subunit (IPR019756, IPR019758).

That said, I think the even more specific "serine-type endopeptidase activity (GO:0004252)" would be accurate for both entries.

@hattrill @EBI-Hsinyu

**Comment by sjm41** [comment]
May also want to use that more specific GO term on: InterPro:IPR019756, InterPro:IPR019758

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 
Thank you for this. I have changed the GO term. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu.
Just to confirm, did you change the GO term to "serine-type endopeptidase activity (GO:0004252)"?

**Comment by typhainepl** [comment]
Hi @sjm41, yes she did.

**Comment by sjm41** [comment]
Great, thanks for confirming!

**Comment by sjm41** [comment]
Hi Hsin-Yu,

Looking into this deeper, I've discovered that IPR007653 shouldn't have any peptidase activity term at all.  The only catalytic subunit of the SPC is Sec11 (yeast), which is orthologous to two genes (SEC11A (aka SPC18) and SEC11C (aka SPC21)) in vertebrates.  See #3112.

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you. I have removed this term. 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu.
