### ISSUE TITLE
MIER1 and MIER3 are coTFs, not TFs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3020]
Q8N108 MIER1
Q7Z3K6 MIER3

**Comment by RLovering** [comment]
Actually, Colins email stated:
>MIER1: Corepressors (CDYL association is the give-away. For the rest the proteomics are still quite confusing  PMID:28514442 and 21258344 are for MIER1-CDYL interaction. 21258344 and 18451879 are for EHMT2 H3K27 trimethylase interactions in the what is the same complex as with CDYL.

>MIER2: Corepressor (CDYL) cite PMID:28596423.   28514442 and  26186194  are cited by Biogrid for MIER2 interactions with dbTFs.  26871637 and 24722188 are cited for interaction with NDN, a (MAGE) transcription factor (?) I did not know about.

>MIER3: The PhD thesis of Derwish, Roya (https://research.library.mun.ca/13816/) supports an association with REST, the complex that inhibits neuronal genes in non-neuronal cell types this supports the GO:0003714 corepressor annotation. She also states, but did not yet publish that where there is MIER3 there is often also a FOXA1 motif.  I would park MIER3 under G:0003700 as it is not clear that MIER3 is truly a co-repressor from the proteomics, contrary to MIER1 and 2 that associate with HDAC and CDYL.

However, currently there is no published data to support MIER3 binding DNA, and the other family members having corepressor functions (note Q8N344 MIER2 not annotated as dbTF but as coTF). Plus the InterPro records InterPro:IPR001005|InterPro:IPR009057 supporting the NTNU annotations are no longer mapping to DNA binding. 

In conclusion for consistency all three MIER3 should not be annotated as dbTFs unless there is published evidence to support this.

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks
