### ISSUE TITLE
Aminopeptidase P, N-terminal (IPR007865)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3021]
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR007865/

From the description, the given reference and the associated MF term of "manganese ion binding", I think the other MF term of "aminopeptidase activity (GO:0004177)" can be improved to the more specific "metalloaminopeptidase activity" (GO:0070006).

**Comment by sjm41** [comment]
@hattrill @EBI-Hsinyu

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 
Thank you for this. I have changed the GO term. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
thanks
