### ISSUE TITLE
Mouse Taf4 is not a regulator of transcription 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3023]
Hello, 

Mouse Taf4 ( MGI:2152346) is anotated to 'regulation of transcription' from PMID:11570813 and PMID:11557891. Please annotate to 'transcription, DNA templated (and not regulation), since this gene encodes a general transcription factor. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
done

**Comment by RLovering** [comment]
great, thank you, our spreadsheet is updated
