### ISSUE TITLE
TAFs are general transcription factors - IPR003894 and IPR037249

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3024]
Hello,

IPR003894 and IPR037249 contains members that are either transcription coregulators  (Q06455/ CBFA2T1) OR general transcription factors (Q92750/TAF4B), so I dont think we can make any mappings. 

Can you please check/remove is appropriate ? 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Thank you for this. I have removed the term. 
Regards, 
Hsin-Yu

**Comment by RLovering** [comment]
Thank you so much, I have updated our spreadsheet
