### ISSUE TITLE
InterPro2GO: Carboxypeptidase, activation peptide (IPR003146)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3025]
This entry is associated with the GO terms "carboxypeptidase activity (GO:0004180)" and "proteolysis (GO:0006508)".

But it looks like this entry is specifically for the "propeptide associated with peptidases belonging to MEROPS peptidase family M14A".  That is, it's for the propeptide sequence rather than the catalytic domain (which I think is covered by "Peptidase M14, carboxypeptidase A, IPR000834").  In which case, I don't think those GO terms should be applied directly to the propeptide domain.

(E.g. there's a fly protein (FBgn0262880 / UniProt:C1C3H6) that appears to have the propeptide but lacks the catalytic domains, so is presumably inactive.)

Can you check and, if you agree, remove those two GO term associations?

@hattrill @EBI-Hsinyu

**Comment by EBI-Hsinyu** [comment]
Hi,
Thank you for this. I have removed this term. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks!
