### ISSUE TITLE
IPR011177 is involved in transcription, not regulation of transcription

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3026]
Hello, 

IPR011177 is mapped to both 'regulation of transcription, DNA-templated (GO:0006355)' and 'DNA-templated transcription, initiation (GO:0006352)'. As a general transcription factor, it should only be annotated to transcription. 

You can also probably map to the more specific term GO:0006367 transcription initiation from RNA polymerase II promoter. 

Thanks, Pascale

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you. I have removed the term. 
Regards, 
Hsin-Yu

**Comment by RLovering** [comment]
Thanks, I have updated our spreadsheet
