### ISSUE TITLE
PTN000491515 (D-ALANYL-D-ALANINE CARBOXYPEPTIDASE (PTHR21581))

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3027]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000491515

This node is annotated with "endopeptidase activity IBD" based on a single annotation to E. coli pbpG (P0AFI5).

That GO term is being inherited by orthologs of the "TRAPPC12" component of the TRAPPIII protein complex, including human (Q8WVT3) and fly (Q9VPB6).
I don't see any evidence for the endopeptidase activity of the E. coli gene being conserved through to eukaryotes/metazoa in terms of domains or other GO annotations, or of peptidase activity being associated with the TRAPPIII complex.

If you agree, can you remove/restrict propagation of this annotation?

@hattrill

**Comment by marcfeuermann** [comment]
I totally agree. I've removed the annotation and renamed the family.

**Comment by sjm41** [comment]
Thanks!
