### ISSUE TITLE
InterPro2GO: Peptidase S8/S53 domain (IPR000209)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3028]
As the description says "The vast majority of the family are endopeptidases, although there is an exopeptidase, tripeptidyl peptidase"

so the current associated GO term "serine-type endopeptidase activity (GO:0004252)" should be changed to "serine-type peptidase activity (GO:0008236)"

@hattrill @EBI-Hsinyu

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have replaced the term. 
Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
And thanks again!
