### ISSUE TITLE
UBTF P17480

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3029]
Hi Marcio

please would you remove this annotation
UBTF (alias UBF1) P17480
 GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR009071

The InterPro record you have used to support this annotation, IPR009071, states nucleolar transcription factors UBF 1/2 (upstream binding factor) involved in transcription by RNA polymerase I

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotation!

Best,

Marcio
