### ISSUE TITLE
Tagging InterPro in issues update

### ISSUE THREAD

**Issue by typhainepl** [geneontology/go-annotation#3030]
To minimise email traffic we are changing our "watch" settings here at InterPro. For anything that requires InterPro attention, please now tag the curators to ensure it gets picked up.

@EBI-Hsinyu 
@lsw26
@sarach06
@Alexbateman1
 @typhainepl

Thanks!

**Comment by typhainepl** [comment]
@bmeldal
@hattrill
@vanaukenk
@pgaudet
@Antonialock
@ukemi

**Comment by hattrill** [comment]
Hi @typhainepl should we just pick one curator or tag you all?

**Comment by typhainepl** [comment]
would be nice to tag at least 3 of us

**Comment by hattrill** [comment]
FYI @sjm41 and @phanivg

**Comment by sjm41** [comment]
Hi @typhainepl
Just checking - how does adding the 'InterPro mapping' label work in this context? Is not that effective to alert all relevant InterPro curators?

Steven.

**Comment by typhainepl** [comment]
Hi @sjm41,
Yes the InterPro mapping is useful, but we don't receive an alert when a ticket has the label assigned (if there is a way to do send an email to Interpro that would be even better) and we don't check the list of GO tickets everyday.

**Comment by sjm41** [comment]
OK, understood. I'm don't know either if the labels can be made to work in that way or not....
Just about to make you a(nother) ticket - will tag all 5 of you and see how that goes!

**Comment by pgaudet** [comment]
@suzialeksander It would be nice to make templates with this information

**Comment by suzialeksander** [comment]
@pascale, I think I can make a template auto-assign specific users. The catch is it would then be up to the user opening the ticket to identify it as an InterPro issue before anything else, and then selecting the correct template.  https://github.community/t/apply-labels-automatically-at-issue-creation/1218/14

I also looked into somehow getting the action of assigning the `InterPro mapping` tag to notify or assign specific users, but I can't find anything that would indicate that's possible.  GH does use email notifications very cleanly, and we could ask InterPro to monitor all emails from notifications@github.com and CC'd to team_mention@noreply.github.com, BUT: that depends on GO changing a bit how Teams are set up and then InterPro curators filtering emails for `team_mention`.  I'm not sure this process saves any effort over just remembering to tag 3+ InterPro curators. 

Do you want me to go ahead and make the template?

**Comment by Antonialock** [comment]
Personally I would much rather have to identify an issue as an interpro issue at the point of opening the ticket (I think I manage to do this 100% of the time anyway) than having to do what  currently do; finding an archived email in my vast stash of emails and copying'n'pasting relevant people EVERY TIME

**Comment by Antonialock** [comment]
:) I hope that did not sound harsh. I'm in support, I'll find the right template 👍

**Comment by Antonialock** [comment]
(or assign a tag:I just hate having to search my archived emails for the list of people to @ mention)

**Comment by pgaudet** [comment]
@suzialeksander 

I saw in another tracker that when you click new issue you have a menu: 
- type of ticket A
- type of ticket B
- other type (for stuff that doesn't fit) 

I suggest:

1) Annotation review request
- ask to specific which group , protein ID is affected
-if possible add 'annotation review' label

2) Report an issue with PAINT annotations
- add 'PAINT' label 
- 'assign or tag myself  (@pgaudet) and @marcfeuermann 

3) Report an issue with InterPro annotations 
- add 'InterPro' label 
- 'assign or tag 
@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

4) Report an issue with UniProt KW mappings or assignments 
 - add 'UniProt KW2GO mapping' label 
- 'assign or tag @sylvainpoux @pgarmiri 

5) Any other issue


I think those are the main ones. Let me know if this is doable and if you want a bit more explanatory text  for each of those.

Thanks, Pascale

**Comment by typhainepl** [comment]
Hi,
I think it is safe to say that you can tag only @EBI-Hsinyu and @sarach06 for future InterPro-related GO tickets as they are currently the main InterPro curators.
Typhaine
