### ISSUE TITLE
inferences for adducins.  PTN000072560

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3032]
Adducins are likely to have some cytoskeletal role, but a lot of these processes infered from nmetazoans are likely to be a little indirect.

For fission yeast adducins these annotations are unlikely to be correct:
(I kept the annotation on these sparse, because their role is really unclear, these are likely readouts)

Q9HE08 &  Q9P5M9

GO:0005198 | structural molecule activity | IBA with MGI:87918 , MGI:87919 , MGI:1351615 , PTN000072560

GO:0051017 | actin filament bundle assembly | IBA with P35612 , PTN000072560 , P35611

GO:0051016 | barbed-end actin filament capping | IBA with PTN000072560 , P35611 , P35612

GO:0044853 | plasma membrane raft | IBA with P35612 , PTN000072560 | Gaudet P et al. (2011)

**Comment by marcfeuermann** [comment]
Family annotation has been updated.
