### ISSUE TITLE
	Q09743 Rictor homolog, Ste20.  PTN000329282

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3033]
For fission yeast please remove:

GO:0008047 | enzyme activator activity | IBA with DDB_G0277399 , PTN000329282 | Gaudet P et al. (2011)

GO:0030010 | establishment of cell polarity | IBA with PTN000329282 , DDB_G0277399 | Gaudet P et al. (2011) | 25
- | GO:0030950 | establishment or maintenance of actin cytoskeleton polarity | IBA with PTN000329282 , S000000895 | Gaudet P et al. (2011) | 11
- | GO:0051897 | positive regulation of protein kinase B signaling | IBA with 1307224 , PTN000329282 , DDB_G0277399 | Gaudet P et al. (2011) | 1
- | GO:0042325 | regulation of phosphorylation | IBA with MGI:1926007 , PTN000329282 , 1307224 | Gaudet P et al. (2011) | 69
GO:0031532 | actin cytoskeleton reorganization | IBA with PTN000329282 , Q6R327 | Gaudet P et al. (2011) | 3

Althopugh probably regulating some aspects of cytoskeleton organization  is unlikely that the polarity annotations are correct for fission yeast.

Transferring annotations for signalling pathways  makes me feel a little uncomfortable.....

**Comment by ValWood** [comment]
and also

Q9P7Y9

GO:0030950 | establishment or maintenance of actin cytoskeleton polarity | IBA with S000005438 , PTN001410677

(this might be a "budding" specific thing for budding, but TORC signalling does not seem to be directly connected to polarity in fission yeast)

**Comment by marcfeuermann** [comment]
The family has been completely reannotated according to your comments.
