### ISSUE TITLE
Mis4 cohesin loading factor PTN000496017

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3037]
remove  from Q09725

GO:0007076 | mitotic chromosome condensation | IBA with PTN000496017 , S000002588
GO:0070550 | rDNA condensation | IBA with S000002588 , PTN000496017 | Gaudet P et al. (2011) | 1
- | GO:1990414 | replication-born double-strand break repair via sister chromatid exchange | IBA with S000002588 , PTN000496017 | Gaudet P et al. (2011) | 2
- | GO:0071733 | transcriptional activation by promoter-enhancer looping | IBA with FBgn0026401 , PTN000496017 , ZDB-GENE-060526-121 , ZDB-GENE-030131-6070 | Gaudet P et al. (2011) | 2

(Mis 4 is a cohesin loading factor, but I believe it loads some transcription factors in higher eukaryotes, possibly, anyway not enough data to  infer for fission yeast)

**Comment by marcfeuermann** [comment]
Already done. Duplicate from #3309.
