### ISSUE TITLE
PTN001160522 drug transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3047]
Has a large number of mappings to "drug transport"
(21 for fission yeast).
Could these be removed ?
(I think this term is going anyway?)

**Comment by ValWood** [comment]
Actually I think the term  will stay but not the descendants classified as drugs.
ANyway these annotations   should go, and I still see 23 annotations to drug transport from PAINT in AmiGO

**Comment by marcfeuermann** [comment]
After checking the corresponding PAINT families, I did not find these annotations anymore. @pgaudet, has the term been removed recently ?

**Comment by pgaudet** [comment]
Hi @marcfeuermann, 

maybe some were removed in other tickets/work. In AmiGO I see two families that still have IBAs to drug transport: 

PANTHER:PTHR23502
PANTHER:PTHR42718

Thanks, Pascale

**Comment by marcfeuermann** [comment]
Hi, yes I've checked these 2 families. So I guess I can close this ticket. Have a nice week-end. Take care and stay safe.
Regards,
Marc.
