### ISSUE TITLE
hexose transporters PTN000756124

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3048]
↑is_a GO:0046323 | glucose import
ght3 | | IBA with ght1 , PTN000756124 , ght5 , ght6 , ght2 |   | Gaudet P et al. (2011) | 8
ght4 |   | IBA with ght2 , ght6 , ght5 , PTN000756124 , ght1 |   | Gaudet P et al. (2011)
ght7 |   | IBA withPTN000756124 , ght2 , ght1 , ght6 , ght5 |   | Gaudet P et al. (2011)
ght8 |   | IBA with ght1 , ght6 , PTN000756124 , ght5 , ght2

please remove (in fission yeast these transport  other sugars, not glucose)

**Comment by marcfeuermann** [comment]
As there are many duplications in the family, I've completely removed the propagation of glucose transporter terms to keep only the more general carbohydrate transport terms.
