### ISSUE TITLE
InterPro2GO for IPR039785 (Ubiquitin carboxyl-terminal hydrolase MINDY-3/4)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3056]
1. I think you can usefully add these GO-MF terms (based on the given reference, PMID:27292798):
- thiol-dependent ubiquitin-specific protease activity (GO:0004843)
- Lys48-specific deubiquitinase activity (GO:1990380)
(and probably a related BP term)

2. I'm not sure why the term name includes "carboxyl-terminal" - I don't think that's accurate?  Maybe remove?

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 

Thank you for this. I have added the GO terms you suggested. The name of the entry is from UniProt. I have changed it into "Deubiquitinating enzyme MINDY-3/4". 

Regards, 
Hsin-YU

**Comment by sjm41** [comment]
Great, thanks!
