### ISSUE TITLE
Peptidase C69, dipeptidase A (IPR005322)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3058]
Can you add "cysteine-type exopeptidase activity (GO:0070004)" to this entry please?

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by EBI-Hsinyu** [comment]
Thanks! I have added the GO term in this entry. 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu.
