### ISSUE TITLE
InterPro2GO - ArgE/DapE/ACY1/CPG2/YscS, conserved site (IPR001261)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3077]
This entry is associated with the GO terms "proteolysis (GO:0006508)" and "metallopeptidase activity (GO:0008237)".

But, as the description says, I don't think all proteins with this domain necessarily have those functions:
"This group contains metallopeptidases belonging to MEROPS peptidase family M20 (clan MH), subfamilies M20A and M20B; many are classified as unassigned peptidases or **non-peptidase homologues**.
**In addition to the metallopeptidases this group of sequences contain a variety of other protein families** from the archaea, bacteria and eukaryota that hydrolyse substrates"

Maybe remove both terms?

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by typhainepl** [comment]
Hi,
Thanks for highlighting this. I have updated the InterPro entry.
Typhaine

**Comment by sjm41** [comment]
Thanks!
