### ISSUE TITLE
InterPro2GO: Cytosolic nonspecific dipeptidase/DUG1 (IPR017153)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3078]
From the description and the fact the quoted proteins with this domain are metallopeptidases, I think the current GO-MF term of "dipeptidase activity (GO:0016805)" could be replaced with the more specific "metallodipeptidase activity (GO:0070573)"

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by typhainepl** [comment]
Hi,
It looks to me that only DUG1 is a metallopeptidase in this entry (not CNDP1 and CNDP2), so I don't think GO:0070573 can be applied here.
Typhaine

**Comment by sjm41** [comment]
CNDP1 and CNDP2 from human (at least) are annotated as metallopeptidases at UniProt:
https://www.uniprot.org/uniprot/Q96KN2
https://www.uniprot.org/uniprot/Q96KP4

And peptidase M20 subfamily are all defined as metallopeptidases at MEROPS:
https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=M20

Where do you see CNDP1 and CNDP2 are not metallo-type peptidases?

**Comment by typhainepl** [comment]
Hi,
Sorry I got confused by the InterPro description which was saying that DUG1 is a metallopeptidase, but it wasn't clear for CNDP1 and CNDP2. I found a nice paper https://europepmc.org/article/MED/12473676 classifying them as metallopeptidases.
I have updated the InterPro description and changed the GO term.

**Comment by sjm41** [comment]
Great, thanks Typhaine!
