### ISSUE TITLE
Q7Z7C8 TAF8 should be annotated to transcription, not regulation of transcription

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3079]
@hdrabkin 

Another human gene annotated by MGI: 
Q7Z7C8 TAF8 -> should be annotated to transcription, not regulation of transcription

Can you please update ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Fixed in our system; don't know when it will be updated by GOA since we are still having issues with the generation of the file they pick up.

**Comment by pgaudet** [comment]
thanks!
