### ISSUE TITLE
Q96PN7 TRERF1

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3081]
Hi Marcio

We have discussed the experimental data available for TRERF1 and Colin, Pascale and I agree that this protein has not been shown to bind DNA. It has been shown to bind other DNA binding proteins and the data available suggests it is a coactivator rather than a dbTF.

I have annotated it with nuclear receptor transcription coactivator activity based on PMID:17015480

Please delete annotation 

NTNU | Q96PN7 | TRERF1 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR001005\|InterPro:IPR009057.

Note IPR009057 DNA binding annotation removed  https://github.com/geneontology/go-annotation/issues/2991

and IPR001005 DNA binding annotation removed https://github.com/geneontology/go-annotation/issues/988

Thanks

Ruth

@pgaudet

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotation!

Best,

Marcio
