### ISSUE TITLE
InterPro2GO - Peptidase M19 (IPR008257)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3082]
Can you change the current "dipeptidase activity (GO:0016805)" term on this to "metallodipeptidase activity (GO:0070573)"?

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by typhainepl** [comment]
Hi,
I have updated the GO term for InterPro IPR008257 as well as IPR028536.

**Comment by sjm41** [comment]
Excellent, thanks!
