### ISSUE TITLE
InterPro2GO - JAB1/MPN/MOV34 metalloenzyme domain (IPR000555)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3083]
From the description and quoted proteins, I think we can add these GO-MF terms to this entry:

isopeptidase activity (GO:0070122)
metallopeptidase activity (GO:0008237)

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Thank you, I've added those terms to the entry.
Regards,
Sara

**Comment by sjm41** [comment]
Thanks!
