### ISSUE TITLE
InterPro2GO - Dipeptidyl-peptidase 3 (IPR005317)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3084]
I think we can add this GO term to this entry:
metalloaminopeptidase activity (GO:0070006)

Dipeptidyl peptidase 3 isn't described as a metallo-type in the IPR005317 description, but it is in the parent term description (IPR039461).

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Thank you, I added the term and updated the entry.
Regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
