### ISSUE TITLE
change coTF annotation for Q94FL9	MYB3R4

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3085]
Hi Tanya

please would you change the annotation associated with this protein

TAIR | Q94FL9 | MYB3R4 |   | GO:0003713 | transcription coactivator activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:17287251

I think this is more likely to be a DNA binding transcription factor, rather than a coactivator. The authors state:
>By phylogenetic analysis of the conserved DNA-binding domains, Arabidopsis MYB3R1 and MYB3R4 form a clade together with NtmybA1, NtmybA2 and two rice proteins
>A group of Myb transcription factors in tobacco, NtmybA1, NtmybA2 and NtmybB, bind to the MSA motif in vitro and in yeast
>Expression of the KN::LUC reporter construct was stimulated approximately twofold by co-transfection of 35S::MYB3R4, and this activation was further increased by the additional transfection of a 35S::CYCB1 expression plasmid (Fig. 6A). In comparison, KN::LUC reporter activity was unchanged when 35S::MYB3R1 was transfected, but was activated approximately twofold when 35S::CYCB1 was additionally co-transfected (Fig. 6A). Thus, MYB3R1 and MYB3R4 act as transcriptional activators of the KN gene promoter, with MYB3R4 being more effective than MYB3R1. Activation of the KN promoter by MYB3R4 is dependent on the presence of MSA elements, because a mutant KN promoter that lacks all three MSA elements (KNΔMSA) was no longer activated by 35S::MYB3R4 alone or in combination with 35S::CYCB1

I think the intent of the authors here is to use a promoter region which contains a motif commonly bound by MYB family proteins to see if these proteins (which are members of the MYB family) bind the DNA and regulate transcription. I would therefore consider this as sufficient evidence, to change the annotation to:

GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific

Please note that 

F4JV48 | PC-MYB1 |  is also annotated based on this paper so perhaps this annotation needs to change too.

Many thanks and hope you have a good weekend

Ruth

**Comment by tberardini** [comment]
@ebakker2  Can you please take care of the review and re-annotation, if necessary, of AT4G32730 and AT4G32730 based on this paper:

https://pubsearch.arabidopsis.org/DisplayArticle?article_id=39601

Thanks.

**Comment by EricaBakker** [comment]
Done!

**Comment by pgaudet** [comment]
Thanks !
