### ISSUE TITLE
Change 	MGI:99918  Mecp2 dbTF annotation to coTF annotation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3086]
Hi

Mecp2 does bind DNA but it is not considered to be a DNA-binding transcription factor because the binding is not specific enough for this to 'provide a genomic address' which ensures specific gene regulation, although it may acheive this by interacting with dbTFs that are providing the specific address.

Please could you review these annotations and consider changing these to a  GO:0003712 transcription coregulator activity or child term.

I'm afraid I have not checked these papers so if these do demonstrate that this protein binds DNA in a way that would support annotation of this gene to GO:0003700 please let me know.

MGI | Q9Z2D6 | Mecp2 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000315 (IMP) |   | PMID:15608638
MGI | Q9Z2D6 | Mecp2 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000315 (IMP) |   | PMID:17108082
MGI | Q9Z2D6 | Mecp2 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) |   | PMID:16782889
MGI | Q9Z2D6 | Mecp2 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) |   | PMID:18511691

Many thanks

Ruth

**Comment by krchristie** [comment]
Hi @RLovering 

While I agree that Mecp2 does not bind DNA in a sequence-specific manner and thus does not meet the criteria for annotation to GO:0003700, I do not agree that it is appropriate to call it a co-repressor.

Mecp2 binds methyl-CpG in DNA and recruits the NCoR1/2 co-repressor complex to repress DNA. Thus the role of Mecp2 is like that of a DNA-specific TF in that it's role is to bind a specific DNA location and recruit a repressor. The difference here is that the location is not specified by the DNA sequence, but by the methylation pattern. I think we need a new term for this.


There's a nice compact summary in the Intro of this paper:

> Pelka et al 2006. **Mecp2 deficiency is associated with learning and cognitive deficits and altered gene activity in the hippocampal region of mice.** Brain. 129(Pt 4):887-898. https://pubmed-ncbi-nlm-nih-gov.ezproxy.jax.org/16467389/ 

> Rett syndrome, RTT (MIM 312750), is a neurodevelopmental disorder associated with onset of cognitive and motor deterioration at 6–18 months of life (Hagberg et al., 1983). Up to 80% of classical RTT patients harbour mutations in the X-linked MECP2 gene encoding the methyl-CpG-binding protein 2 (MeCP2) (Amiret al., 1999).  MeCP2 binds selectively to methylated CpG dinucleotides in mammalian genomic DNA (Lewis et al., 1992) via a methyl-CpG-binding domain (MBD) (Nanet al., 1993) and represses transcription of target genes by transcriptional repression domain (TRD) initiated  interactions with histone deacetylases (HDAC1 and HDAC2) and the transcriptional co-repressor SIN3A (Nanet al., 1998).

This recent review also supports this view.
> Tillotson R, Bird A. **The Molecular Basis of MeCP2 Function in the Brain** [published online ahead of print, 2019 Oct 17]. J Mol Biol. 2019;S0022-2836(19)30595-9. doi:10.1016/j.jmb.2019.10.004
PMID:31629770

Thanks,

-Karen

**Comment by colinlog** [comment]
@krchristie @hdrabkin 

We agree with you for the GO:0008327 methyl-CpG binding, but no new term is needed as MECP2 is already annotated to this term. 

I believe we then agree that you can remove sequence-specific DNA binding annotation term GO:0003700 in https://github.com/geneontology/go-annotation/issues/3086#issue-631647471

**Comment by krchristie** [comment]
> @krchristie @hdrabkin
> 
> We agree with you for the GO:0008327 methyl-CpG binding, but no new term is needed as MECP2 is already annotated to this term.

I understand that the term `methyl-CpG binding` already exists, but to say that this is sufficient is like saying that it would be sufficient to annotate a sequence specific DNA binding transcription factor to the term `sequence-specific DNA binding`. You all have spent quite a lot of time trying to correctly represent that the function of a `sequence specific DNA binding transcription factor` is that it **BOTH**
- binds DNA of a specific sequence **AND**
- interacts with the transcription machinery to activate or repress transcription

Similarly, with Mecp2, it's function is to **BOTH**
- binds DNA with a specific modification (Me-CpG) **AND**
- interacts with the transcription machinery to activate or repress transcription

[Hsu et al. 2020. Restoring Wnt6 signaling ameliorates behavioral deficits in MeCP2 T158A mouse model of Rett syndrome. Sci Rep. 10(1):1074.](https://pubmed-ncbi-nlm-nih-gov.ezproxy.jax.org/31974426/)

> Methyl-CpG-binding protein 2 (MECP2) is an X chromosome-linked gene that encodes the MeCP2 protein. MeCP2 contains two major domains, the methyl-DNA binding domain and the transcriptional repression domain, which are both structurally conserved. MeCP2 was first found to function as a transcriptional repressor. **It binds to the CpG island of methylated DNA and recruits co-repressors**, such as the histone deacetylase (HDAC) complex, for transcriptional repression. But a later study has indicated that MeCP2 could also function as a transcriptional activator.

Thus, I feel that a new term is needed for something like `DNA-modification binding transcription factor`

> I believe we then agree that you can remove sequence-specific DNA binding annotation term GO:0003700 in [#3086 (comment)](https://github.com/geneontology/go-annotation/issues/3086#issue-631647471)

I agree with you that GO:0003700 is not appropriate for Mec2p, but I don't want to spend any more time on this gene until an appropriate term is available so that I can read the papers once to remove GO:0003700 and add any new terms as appropriate.

**Comment by pgaudet** [comment]
Hi @krchristie 
We have created a term for this function, epigenetic reader, see https://github.com/geneontology/go-ontology/issues/20551


Hopefully that will be suitable for annotation of Mecp2.  

Thanks, Pascale

**Comment by RLovering** [comment]
Hi @krchristie

Our list of DNA-binding transcription factors is about to be published. The reviewers have asked us to comment on whether a specific filter in AmiGO or QucikGO will download this list. Currently there are a few MGI annotations that mean that applying the GO:0003700 filter will lead to several non-dbTF proteins being downloaded. One of these is Mecp2. The reviewers have also asked us to provide examples of proteins which have been wrongly assigned as a dbTF. The lack of appropriate GO term to describe the epigenetic reader facilty seems to be a good reason.

Please would you change the following annotations using the GO term  GO:0140566 epigenetic reader

  | MGI | Q9Z2D6 | Mecp2 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000315(IMP) | ECO:0000315 | (IMP) |   | PMID:17108082 |   | MGI:MGI:2183727 |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ECO:0000315 | (IMP)
  |   | MGI | Q9Z2D6 | Mecp2 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:18511691 |  
ECO:0000314 | (IDA)

Thanks

Ruth

**Comment by RLovering** [comment]
David confirmed this is completed
