### ISSUE TITLE
Change Notch1 dbTF annotation to coTF 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3087]
Hi Harold

Notch1 does not bind DNA.

Please could you review these annotations and consider changing these to a GO:0003712 transcription coregulator activity or child term.

MGI | Q01705 | Notch1 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) |   | PMID:9111338
MGI | Q01705 | Notch1 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) |   | PMID:17658278
MGI | Q01705 | Notch1 | enables | GO:0043565 | sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:17658278

I'm afraid I have not checked these papers so if these do demonstrate that this protein binds DNA in a way that would support annotation of this gene to GO:0003700 please let me know.

Many thanks

Ruth

**Comment by hdrabkin** [comment]
PMID:17658278 does have data to suggest sequence-specific DNA binding. (Fig3F). Other data in 3 is from Chip experiments, where3F uses direct binding to labeled DNA.
However, PMID:17658278 is more to do with Rbpjl  and not with Notch at all.

**Comment by hdrabkin** [comment]
Looking at PMID:17658278  fig 3 more, and some reviews, I believe the 'chromatin binding" (Fig 3 B-E, but not sure about F).  I will change to co-activator and remove DNA binding annotation.

**Comment by RLovering** [comment]
Thanks Harold. In figure 3F they only ever use the Notch polypeptide ICN1 with CSL, it is never investigated on its own. I haven't checked the other figures in that paper but at least this one with purified Notch does not support DNA binding

I have updated our spreadsheet confirming these annotations have been removed

Thanks

Ruth

**Comment by RLovering** [comment]
Sorry Harold, please confirm that you have removed the DNA binding annotation so that I can update that row on our table

Thanks

Ruth

**Comment by hdrabkin** [comment]
Yes; you can close

**Comment by RLovering** [comment]
thanks
