### ISSUE TITLE
P67778 | Phb is not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3089]
Hi Harold

MGI | P67778 | Phb | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:18480465

Please could you review this annotation, I would recommend deleting it. 
In the paper cited they state: 
>PHB modulates transcription of many genes directly through interactions with corepressors and HDACs, as well as transcription factors, including steroid receptors [38–40]. In this study, PHB overexpression reduced promoter activity of all three gonadotropin genes, and also the transcript levels of Cga and Lhb. It is quite possible that PHB acts as a corepressor or scaffold factor to assemble such repressive complexes at the promoter. 
certainly there is no evidence of DNA binding being responsible for the data presented.

I have removed the UCL DNA binding annotation from the orthologous human record

Many thanks

Ruth

**Comment by hdrabkin** [comment]
The experiment does seem consistent with GO:0003714 transcription corepressor activity and is consistent with other annotations to the negative regulation of transcription. So changed to that.

**Comment by RLovering** [comment]
excellent thanks. I have updated our spreadsheet too
Ruth
