### ISSUE TITLE
IPR005033 does not support P42568	MLLT3

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3090]
Hi Marcio

please would you remove the 

Q03111 | MLLT1 Protein ENL
P42568 | MLLT3 super elongation complex subunit annotation 

* UniProtKB | Q03111 | MLLT1 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255 | ISM | PMID:19274049 | InterPro:IPR005033 | 9606 | NTNU_SB
* UniProtKB | P42568 | MLLT3 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR005033

InterPro:IPR005033 does not support this annotation in addition the UniProt description suggests that:
>Chromatin reader component of the super elongation complex (SEC), a complex required to increase the catalytic rate of RNA polymerase II transcription by suppressing transient pausing by the polymerase at multiple sites along the DNA 

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
