### ISSUE TITLE
Delete Bmpr1a dbTF annotation, and edit Zcchc12 annotation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3092]
Hi 

Bmpr1a does not bind DNA. In addition, I don't think there is evidence to support the annotation of Zcchc12 to GO:0030374 | nuclear receptor transcription coactivator activity

Please could you review the annotations associated with PMID:19416967. I have had a quick look at the paper and I think these annotations have been based to some extent on the luciferase assay in figure 9. Obviously luciferase assays can be used to examine signaling pathways not just dbTFs and coTFs.

Delete: MGI | P36895 | Bmpr1a | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19416967

Change: MGI | Q9CZA5 | Zcchc12 | enables | GO:0030374 | nuclear receptor transcription coactivator activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19416967
Based on this statement: Sizn1 (Zcchc12) is a recently identified, novel transcription co-activator that positively modulates BMP signaling through its interaction with Smad family members and recruitment of CREB-binding protein (CBP)3 to the transcription complex (4). could change to  GO:0003713 transcription coactivator activity

Change: MGI | Q9CZA5 | Zcchc12 | acts_upstream_of_or_within | GO:2000327 | positive regulation of nuclear receptor transcription coactivator activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19416967
change to GO:0045944 positive regulation of transcription by RNA polymerase II

Not essential but change: MGI | P36895 | Bmpr1a | acts_upstream_of_or_within | GO:0045893 | positive regulation of transcription, DNA-templated | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19416967 
to be consistent change to  GO:0045944 positive regulation of transcription by RNA polymerase II

Thanks

Ruth

**Comment by LiNiMGI** [comment]
Thanks Ruth, sounds good to me, will make all the suggested changes.  Li

**Comment by RLovering** [comment]
wonderful
thanks 
I have updated the spreadsheet we are keeping track of this on
Ruth
