### ISSUE TITLE
ZFP36L1 and 2 not DNA binding

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3093]
Hi Marcio

Please remove these annotations:

NTNU | P47974 | ZFP36L2 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000571

NTNU | Q07352 | ZFP36L1 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000571

The InterPro record does not support the annotation and several papers state the protein:
>destabilizes several cytoplasmic AU-rich element (ARE)-containing mRNA transcripts by promoting their poly(A) tail removal or deadenylation, and hence provide a mechanism for attenuating protein synthesis (PubMed:25106868, PubMed:14981510).
see UniProt record for more information https://www.uniprot.org/uniprot/P47974

Thanks

Ruth

**Comment by RLovering** [comment]
closed p2g dispute so that we just discuss this in GitHub
Thanks
Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio
