### ISSUE TITLE
Change MGI:109360  LMO4 annotation to coTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3094]
Hi

as described in https://pubmed.ncbi.nlm.nih.gov/19323994/
> Unlike LIM-HD proteins, LMO proteins have LIM domains but lack any functional DNA-binding motif.

based on the paper above this annotation was created:
MGI | P61969 | Lmo4 | enables | GO:0000987 | cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19323994

Please would you change this annotation to a coTF term, eg  GO:0003713 transcription coactivator activity

Figure 3 confirms dbTFs bound by LMO4 and Fig 5B confirms activation function. Fig 6 ChiP is not sufficent evidence for DNA binding

Thanks

Ruth

**Comment by krchristie** [comment]
Hi @RLovering 

While I agree with you that "Fig 6 ChiP is not sufficent evidence for DNA binding", I don't agree that this paper shows that Lmo4 is a coactivator.

What they showed in this paper is that Lmo4 and Ldb1 (aka NLI) assemble Gata2 and Tal1 (aka SCL) into the V2b complex, a higher-order LIM complex that is a dimer of two Ldb1:Gata2:Lmo4:Tal1 units. It is the V2b complex which binds the Intronic enhancers of the Gata2 and Gata3 genes. Then, the V2b complex recruits the coactivator Ssbp3 (aka SSDP1).

Thus, I have deleted the `cis-regulatory region sequence-specific DNA binding` as you requested.

However, I do not feel that `transcription coactivator activity` is an appropriate annotation for Lmo4. Instead, I have annotated all 4 genes: Lmo4, Ldb1, Gata2, and Tal1 to the CC term `transcription regulator complex`.

I have added an annotation for Ssbp3 to `transcription coactivator activity`

Thanks,

-Karen









> as described in https://pubmed.ncbi.nlm.nih.gov/19323994/
> 
> > Unlike LIM-HD proteins, LMO proteins have LIM domains but lack any functional DNA-binding motif.
> 
> based on the paper above this annotation was created:
> MGI | P61969 | Lmo4 | enables | GO:0000987 | cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19323994
> 
> Please would you change this annotation to a coTF term, eg GO:0003713 transcription coactivator activity
> 
> Figure 3 confirms dbTFs bound by LMO4 and Fig 5B confirms activation function. Fig 6 ChiP is not sufficent evidence for DNA binding
> 
> Thanks
> 
> Ruth

**Comment by pgaudet** [comment]
Thanks !
