### ISSUE TITLE
change Btg2 (rat) annotation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3095]
Hi

this is a MGI annotation to the rat protein. However there is no evidence that this binds DNA and the authors in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2791842/ state 
>Given that PC3/Tis21 has been shown to bind histone deacetylases (HDACs) and to act as an inhibitory transcriptional co-factor [13], we can speculate that PC3/Tis21 may impair the transcriptional activity of Id3 by recruiting these inhibitory molecules to the Id3 promoter, thereby facilitating the terminal differentiation of dentate gyrus neuron. 

The annotation of "DNA binding" appears to rely on ChIP data in fig 7

MGI | P27049 | Btg2 | enables | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314 (IDA) |   | PMID:20020054 |  

I guess the intent of the authors is to investigate Btg2 as a corepressor ( GO:0003714 
transcription corepressor activity), so perhaps that term could be applied. The paper referenced as [13] above is https://pubmed.ncbi.nlm.nih.gov/17371797/ which does show PC3 binds HDAC, some of this data is mouse.

Best

Ruth

**Comment by ukemi** [comment]
Changed to corepressor as suggested.
