### ISSUE TITLE
PANTHER:PTN000188065, cellular response to tetrahydrofolate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3097]
I'm going to question the existance of this term:

shm1 | serine hydroxymethyltransferase Shm1 (predicted) |   | cellular response to tetrahydrofolate |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000188065UniProtKB:P34896

(has more informative  tetrahydrofolate interconversion)

**Comment by marcfeuermann** [comment]
Term removed. Should indeed never have been propagated.
