### ISSUE TITLE
PANTHER:PTN000214662 not branched-chain amino acid biosynthetic process 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3098]
I'm not sure that this inference from E.coli is correct. Presumbly it is the best hit, but I think this  is a larger family in eukaryotes.
Anyway
abz2 is involved in folic acid biosynthetic process

abz2 | 4-amino-4-deoxychorismate lyase Abz2 (predicted) |   | branched-chain amino acid biosynthetic process |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000214662 UniProtKB:P0AB80 | amino-acid aminotransferase pthr42743 | protein |   | PMID:21873635

**Comment by marcfeuermann** [comment]
The family has been re-annotated.
