### ISSUE TITLE
 IPR012080 	 isoleucine biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3099]
This seems too specific for this family.

See SGD HOM2
Aspartic beta semi-aldehyde dehydrogenase; catalyzes the second step in the common pathway for methionine and threonine biosynthesis; 

https://www.yeastgenome.org/locus/YDR158W

**Comment by marcfeuermann** [comment]
This term does not appear anymore in the annotation of the family. I've restricted annotation to methionine and threonine biosynthesis.
