### ISSUE TITLE
PANTHER:PTN000295178 - PTHR12707 - not cell junction or adhesion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3101]
pnn1 | splicing factor, pinin ortholog Pnn1 |   | cell adhesion |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000295178 UniProtKB:P79149 | pinn pthr12707 | protein

and

pnn1	splicing factor, pinin ortholog Pnn1		cell-cell junction		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000295178
UniProtKB:P79149	pinn pthr12707	protein		PMID:21873635	20170228

I think this is highly likey to be a splicing factor, and that the other annotation on human UniProtKB:P79149	 are very indirect readouts. It is also listed at UniProt as a transcription regulator with a DNA binding domain. I believe this is also incorrect.

**Comment by pgaudet** [comment]
Removed.
