### ISSUE TITLE
PANTHER:PTN000403280 not telomere maintenance  - PTHR15696

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3102]
ebs1 | EST1 family nonsense-mediated mRNA decay (NMD) pathway protein Ebs1 |   | telomere maintenance via telomerase |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000403280 SGD:S000004223UniProtKB:A0A1D8PP89 | smg-7 suppressor with morphological effect on genitalia protein 7 pthr15696

ebs1 pombe is the ortholog of S. cerevisaie SGD:S000002614
which is involved in NMD pathway.

**Comment by ValWood** [comment]
Actually EST1  is a paralog. But I think these 2 are both likely to be readouts. Many  gene products have a telomere maintenance phenotype...

**Comment by pgaudet** [comment]
@ValWood If you have a clear action we can do the fix.

**Comment by ValWood** [comment]
I think est1 is a bona fida telomerase regulator, but ebs1 not:

Can you see a split between ebs1 (NMD factor)  and est1 (telomerase regulator)
https://www.pombase.org/gene_subset/interpro:IPR019458

**Comment by pgaudet** [comment]
> Can you see a split between ebs1 (NMD factor) and est1 (telomerase regulator)


No - they look like two independent duplications. I can just remove the annotations to yeast EBS1 and pombe SPBC2F12.03c. OK ? 

Thanks, Pascale

<img width="599" alt="image" src="https://user-images.githubusercontent.com/4782928/84635672-cf835c80-aef3-11ea-80b7-68bb96608011.png">

**Comment by pgaudet** [comment]
Done, please reopen if it was not correct.

**Comment by ValWood** [comment]
OK, I will ask some experts about this and get back to you. It might not be this week.

**Comment by ValWood** [comment]
...i.e. if there is anything to change.
