### ISSUE TITLE
MGI:1915033  AHCTF1 not a dbTF - please remove annotation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3106]
Hi Marcio

please remove the annotation

NTNU | Q8WYP5 | AHCTF1 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000637 | 

The interpro domain does not support this annotation, it does not have any DNA binding annotations or dbTF annotations.

InterPro states: High mobility group (HMG) proteins are a family of relatively low molecular weight non-histone components in chromatin
[1]. HMG-I and HMG-Y (HMGA) are proteins of about 100 amino acid residues which are produced by the alternative splicing of a single gene. HMG-I/Y proteins bind preferentially to the minor groove of AT-rich regions in double-stranded DNA in a non-sequence specific manner[2, 3]. 

It is suggested that these proteins could function in nucleosome phasing and in the 3' end processing of mRNA transcripts. They are also involved in the transcription regulation of genes containing, or in close proximity to, AT-rich regions. DNA-binding of these, and several related, proteins is effected by an 11-residue domain known as an AT-hook.

UniProt states: Required for the assembly of a functional nuclear pore complex (NPC) on the surface of chromosomes as nuclei form at the end of mitosis. May initiate NPC assembly by binding to chromatin and recruiting the Nup107-160 subcomplex of the NPC. Also required for the localization of the Nup107-160 subcomplex of the NPC to the kinetochore during mitosis and for the completion of cytokinesis.

Please remove the annotation
Thanks
Ruth

**Comment by RLovering** [comment]
Hi Harold

please remove the annotation (see notes above about this protein). While it binds AT sequence this is not considered to be specific enough to classify this as a dbTF.
In addition, PMID:11952839 does not support these annotations.
 MGI | Q8CJF7 | Ahctf1 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000315(IMP) | ECO:0000315 | (IMP) |   | PMID:11952839
ECO:0000315 | (IMP)

MGI | Q8CJF7 | Ahctf1 | acts_upstream_of_or_within | GO:0006355 | regulation of transcription, DNA-templated | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:11952839

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet 

I have removed the annotation!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks, only MGI annotation left @krchristie

**Comment by krchristie** [comment]
MGI annotations removed.

**Comment by pgaudet** [comment]
Thanks!
