### ISSUE TITLE
Q9NR48 | ASH1L is not a dbTF please remove annotation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3107]
Hi Marcio

the InterPro domain does not support this annotation. In addition, this protein is a 
histone methyltransferase activity (H3-K9 specific) so more likely to be a coTF.

Please remove this annotation

NTNU | Q9NR48 | ASH1L |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000637

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotation!

Best,

Marcio
