### ISSUE TITLE
InterPro2GO on IPR002467 & IPR002468

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3108]
Hi

When you get chance, these two MF terms on the two InterPro entries mentioned above could be replaced with a single MF term:

aminopeptidase activity (GO:0004177)
metalloexopeptidase activity (GO:0008235)
->
metalloaminopeptidase activity (GO:0070006)

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Thank you very much! I have done the changes pointed out.
Best regards,
Sara

**Comment by sjm41** [comment]
Great, thanks Sara!
