### ISSUE TITLE
Arid proteins not dbTFs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3110]
Hi All

As part of the dbTF discussions it was agreed that AT hook proteins are not dbTFs. These bind a short sequence of DNA that is not long enough to provide a genomic address, instead they often act as coTFs. ie they bind with a dbTF regulating the transcription at that specific locus but not being responsible for identifying the gene to regulate.

There are several mouse Arid3a annotations that need to be revised. 

Q99856 | ARID3A |   |   |   | NTNU | Q62431 | Arid3a |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314 (IDA) |   | PMID:15456761
Q99856 | ARID3A |   |   |   | NTNU | Q62431 | Arid3a |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000315 (IMP) |   | PMID:15456761

Q99856 | ARID3A |   |   |   | MGI | Q62431 | Arid3a | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) |   | PMID:21955986
Q99856 | ARID3A |   |   |   | MGI | Q62431 | Arid3a | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314 (IDA) |   | PMID:15456761

Consider using  GO:0003713 transcription coactivator activity if this is appropriate

I haven't checked the papers in detail, but if the EMSA uses nuclear extracts this will not be sufficient to demonstrate specific promoter binding, as a dbTF in the nuclei could be involved.

Also another mouse annotation for another ARID

NTNU | Q9Z1N7 | Arid3b |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:8543152

Thanks

Ruth @colinlog

**Comment by RLovering** [comment]
After discussion with Colin and Pascale we recommend that you apply the 

GO:0003680 AT DNA binding term, the definition is being revised to describe this as AT rich DNA binding.
And 
GO:0003712 transcription coregulator activity term (or child term)

PMID:10545119 ; PMID:15802641 ; PMID: 26223912 all describe DNA binding but also state that the binding is not specific. The AT hook binds the minor groove and is not DNA sequence specific binding.

Many thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet 

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Only the MGI annotation left @krchristie 

MGI:1328360 Arid3a

**Comment by pgaudet** [comment]
Hi @krchristie 
**Mouse ARID proteins** still have annotations to transcription factor activity and sequence-specific binding: 

MGI:1328360 | Arid3A
MGI:1930768 | Arid3b
MGI:3650624 | Arid3c


Also @tberardini **AT1G20910 (ARID3)** is also annotated to  

*  DNA-binding transcription activator activity, RNA polymerase II-specific
* DNA-binding transcription factor activity
* RNA polymerase II transcription regulatory region sequence-specific DNA binding


**Suggestions for changes:** 
ARID proteins are considered co-regulators. 
The binding function (if demonstrated, of course), is AT-rich sequence binding ("minor groove of adenine-thymine-rich DNA binding"; GO:0003680), which is not a child of 'sequence -specific binding', but a child of 'DNA secondary structure binding'

Thanks, Pascale

**Comment by hdrabkin** [comment]
MGI:1930768 | Arid3b not annotated to these functions except through PAINT.

**Comment by hdrabkin** [comment]
Aldo Arid3c not annotated to these except through Paint and GOA_NTNU_SB

**Comment by pgaudet** [comment]
Thanks @hdrabkin 

Did you removed annotations for Arid3a ? 

<img width="733" alt="image" src="https://user-images.githubusercontent.com/4782928/90533211-785e6a00-e178-11ea-9bbc-17043e2e1b3d.png">

**Comment by pgaudet** [comment]
Sorry about the confusion for Arid3b and Arid3c  - PAINT always lags behind a little (or a lot). 

Thanks, Pascale

**Comment by tberardini** [comment]
@ebakker2 Can you please review and take care of the Arabidopsis annotations mentioned above?  Thanks.

**Comment by hdrabkin** [comment]
I am surprised the  GOA_NTNU_SB annotation for Arid3b is still there; they just had a new release so it will stay around for a  month I guess.

**Comment by hdrabkin** [comment]
Done.

**Comment by EricaBakker** [comment]
Done.
