### ISSUE TITLE
CAMTA1 and CAMTA2 not dbTFs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3111]
Hi

There is conflicting evidence for the human and mouse CAMTA2 proteins. Eric Olson's group clearly show that human CAMTA2 does not bind DNA when acting as a coactivator for NKX2.5 in  PMID: 16678093 (also reasserted in PMID: 17046230, see below for more details). 

However, PMID: 25049392 provides good evidence, using invitro translated proteins and E.coli recombinant proteins, that mouse Camta1 and Camta2 bind DNA (with additional evidence that these regulate transcription using luciferase assays in Fig S4). However, a few aspects to this paper are of concern 1. Fig 4E confirms the requirement of an AT rich sequence adjacent to the 'core' sequence they have identified and the use of mutated sequences in Fig 4C does not exclude the possiblity that these proteins are binding AT sequences. Note that the ratio of DNA binding in the supershift and nonshifted bands in Fig 4B appears to be more like 1:1 than this ratio in  Fig 5B, where the amount of DNA in the supershift is considerably more than that in the non-shifted band, but I couldn't find any information to explain this. Note that MGI did not associated a MF term other than DNA binding based on this paper.

I have included more details below. I suggest that the mouse and human proteins are annotated differently and that the electronic annotations be kept. ie I think these proteins should be associated with both coTF and dbTF annotations. Future data might enable this decision to be resolved to one or the other activity. 

Please could the following annotations be removed

NTNU | O94983 | CAMTA2 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR002909\|InterPro...

NTNU | Q9Y6Y1 | CAMTA1 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR002909\|InterPro...

The annotation to dbTF is not supported by either of the InterPro IDs included in this record  InterPro:IPR002909
OR InterPro:IPR005559 
IPR002909
>The IPT (Ig-like, plexins, transcription factors) domain has an immunoglobulin like fold
[1]. These domains are found in cell surface receptors such as Met and Ron as well as in intracellular transcription factors where it is involved in DNA binding. The Ron tyrosine kinase receptor shares with the members of its subfamily (Met and Sea) a unique functional feature: the control of cell dissociation, motility, and invasion of extracellular matrices (scattering) 

IPR005559
>CG-1 domains are highly conserved domains of about 130 amino-acid residues containing a predicted bipartite nuclear localisation signal. They are named after a partial cDNA clone isolated from parsley encoding a sequence-specific DNA-binding protein
[1]. CG-1 domains are found in CAMTA proteins (for CAlModulin -binding Transcription Activator), which are transcription factors containing a calmodulin-binding domain and ankyrin repeats
[2]
mapped to GO term: DNA binding (GO:0003677)
I have asked InterPro to revise the GO terms mapped to the CG-I domain IPR039033 in ticket #3114

Thanks

Ruth

____________________________________________________________________________________________

More details about the articles mentioned above: 
>PMID: 17046230 provides compelling evidence that these are coactivators rather than dbTFs it states:
>>Several lines of evidence support the conclusion that CAMTA2 acts as a coactivator of Nkx2.5 [36••]. First, the Nkx2.5-response element (NKE) in the ANF promoter is necessary for transcriptional activation by CAMTA2, and one copy of the NKE is sufficient to confer CAMTA2 responsiveness to a basal promoter. Second, CAMTA2 synergizes with Nkx2.5 to activate NKE-dependent promoters. Third, CAMTA2 associates with NKE in the ANF promoter in native chromatin, as detected by chromatin immunoprecipitation (ChIP) assay, and this association is enhanced by Nkx2.5. Since CAMTA does not bind the ANF promoter in gel mobility-shift assays, it is likely that it forms a ternary complex on the NKE by associating with Nkx2.5. Fourth, CAMTA2 interacts with Nkx2.5 directly, and mutations in CAMTA2 that disrupt this interaction also eliminate the ability of CAMTA2 to stimulate Nkx2.5 activity.
>>In addition they suggest that:
Given the high homology between CAMTA1 and -2 and their different expression patterns during embryogenesis, it is not unreasonable to speculate that CAMTA1 also plays a major role in regulating Nkx2.5-dependent gene expression in developing heart. 

>PMID: 25049392 suggests Camta1 and Camta2 binds DNA, with good evidence, using invitro translated proteins and E.coli recombinant proteins

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio
