### ISSUE TITLE
PTN000301433 (PTHR12804) - peptidase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3112]
PTN000301433 adds 'peptidase activity' to members of the "MICROSOMAL SIGNAL PEPTIDASE 23 KD SUBUNIT SPC22/23 (PTHR12804)" family.

Can this be removed please?

It is based on 3 source annotations to S. cerevisie and Candida SPC3 (orthologs of vertebrate SPC22/23 (aka SPCS3)) from SGD.
While SPC3 was originally found to "be essential for signal peptidase activity" of the signal peptidase complex (which comprises 4 subunits in yeast and 5 in vertebrates), subsequent/current understanding is that the only catalytic subunit of the complex is Sec11 (yeast), which is orthologous to two genes (SEC11A (aka SPC18) and SEC11C (aka SPC21)) in vertebrates.

See:
PMID:10206957 (VanValkenburgh et al 1999)
Intro to PMID:14559916 (Liang et al 2003)
Intro to PMID:15300682 (De La Rosa 2004)
Intro to PMID:29265467 (Guan et al 2018)
(Also, SPC3 (or its orthologs) are not listed in the MEROPS database of peptidases.)

Here's the info on the SGD annotations if @srengel  wants to review?

===

S.cerevisiae SPC3 (Q12133)

peptidase activity IMP	PMID:9148931 (Meyer & Hartmann 1997)
peptidase activity IMP	PMID:9148930 (Fang et al 1997)

Both papers find that SPC3 is "essential for signal peptidase activity" of the 4-unit signal peptidase complex, and both suggest that Spc3p may participate directly in the signal peptide cleavage reaction, but neither paper shows that SPC3 itself is a peptidase.
Subsequent papers (especially PMID:10206957) showed that the catalytic activity is restricted to Sec11p.

====

Candida SPC3 (Q5AL47)

peptidase activity IGI with SGD:S000004056 (= SPC3) PMID:15300682 (De la Rosa et al, 2004)

This paper shows that Candida SPC3 complements the thermosensitive growth of a S. cerevisiae spc3 mutant, but that it doesn't rescue the ts phenotype of a S. cerevisiae sec11 mutant.

(Also, the intro of PMID:15300682 says "Sec11p has been shown to be the only catalytic subunit of the Saccharomyces cerevisiae SPC (YaDeau et al. , 1991; VanValkenburgh et al. , 1999)... The essential character of Spc3p (the yeast homologue of the mammalian SPC subunit SPC22/23) seems to be that it is required to stabilize Sec11p (Meyer and Hartmann, 1997; VanValkenburgh et al. , 1999).)"

====

@hattrill

**Comment by srengel** [comment]
Thanks @sjm41 i will take a look. this information you have provided is helpful.

**Comment by pgaudet** [comment]
Removed. 
I'll leave open for @srengel and @marekskrzypek to fix the primary annotations. 

Thanks, Pascale

**Comment by srengel** [comment]
removed the peptidase MF annotations from SPC3 in P2GO.  changed to root because i can't find any other information.

**Comment by sjm41** [comment]
Thanks Pascale, Stacia.

Sorry I misread the database contributing the candida annotation! - thanks for tagging Marek.

**Comment by marekskrzypek** [comment]
I removed the annotation from CGD since it was based on functional complementation with S. cerevisiae SPC3 and I don't see an alternative reference

**Comment by sjm41** [comment]
Thanks @marekskrzypek
