### ISSUE TITLE
IPR040155 - please check the proteins associated with this record

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3115]
Hi

One of the genes associated with this record is CEBPZ. But I do not think this is correct because https://www.jbc.org/content/276/28/26332.long states: 
>ii) Mak21p, the yeast homolog of HSP-CBF, was isolated in a screening to complement mutations in genes allowing propagation of M1 double-stranded RNA and was shown to be essential for cell growth, apparently being required for 60 S ribosomal biogenesis. The lack of complementation of the Mak21–1 phenotype by the human gene, suggesting notable interspecies differences and the absence of yeast conditional mutants limit inferences from the yeast studies. 

Which is based on a statement in https://www.jbc.org/content/273/44/28912.full (which is listed in the InterPro record as PMID: 9786894):
> hCBF Does Not Complement a mak21 Deletion

please would you remove CEBPZ Q03701 M37197 from this record, unless it is associated with this record based on additional data. 

Thanks

Ruth

**Comment by sarach06** [comment]
Hi Ruth,
Thank you for that information. I have removed the term from the entry and added a sentence in the abstract about the different function of the human homolog. 
Best regards,
Sara

**Comment by RLovering** [comment]
Hi Sara
that is great, thank you so much
Best
Ruth
