### ISSUE TITLE
CEBPZ not dbTF please remove annotations

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3116]
Hi Marcio

I have spent some time looking at publications associated with this gene, which led to me curating PMID:11306579, and annotating CEBPZ to coTF activity and NOT DNA binding. This paper mentions PMID:2247079 and actually gets the cDNA clone they have used in expts from these authors. In summary they point to a conflict of their data and that in PMID:2247079. But as this protein does not have a well characterised DNA binding domain therefore please could you delete these annotations:

NTNU | Q03701 | CEBPZ |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:2247079 | 
ECO:0000314 | (IDA)
NTNU | Q03701 | CEBPZ |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:2247079 |   |   | occurs_at(SO:0001952)

Also this InterPro ID does not support DNA binding (also see Intact ticket I raised #3115) 
NTNU | Q03701 | CEBPZ |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR005612
ECO:0000255 | (ISM)

Thanks

Ruth

**Comment by RLovering** [comment]
comment from Marcio: PMID:11306579-Fig 1F is coTF (EMSA supershift) and PMID:2247079-Fig 4 is DbTF (EMSA with purified recombinant CEBPZ; specific binding to dsoligo with wt CAAT motif: "CTCGGTATTGGCTCACAAGG" (and not to mutated oligo). AAccording to Lambert and Co, both Hocomocco and Transfac cite a TFBS motif for this protein.

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio
