### ISSUE TITLE
P42681TXK is not a dbTF please remove these annotation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3117]
Hi Marcio

please would you remove these annotations

NTNU | P42681 | TXK |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:11859127 | 

  NTNU | P42681 | TXK |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:11859127 |   |   | occurs_at(SO:0001952)

Pascale, Colin and I have discussed this and Colin has confirmed that there is no strong evidence that this binds DNA due to the type of assay they are using

You could change one GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific to nuclear chromatin which will keep the SO information in the AE field.

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio
