### ISSUE TITLE
InterPro2GO: Peptidase C1B, bleomycin hydrolase InterPro entry (IPR004134)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3119]
Current GO-MF is "cysteine-type endopeptidase activity (GO:0004197)"
but, as per the description, this should be changed to "cysteine-type aminopeptidase activity" or maybe just "cysteine-type peptidase activity"

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
I changed the GO term, it will be seen in the next release (InterPro 81.0).

Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara.  Which of the 2 GO terms I suggested did you plump for in the end?

**Comment by sarach06** [comment]
You are welcome. Finally, "cysteine-type peptidase activity" as I think it included better all the members. 
Thank you!
Sara

**Comment by sjm41** [comment]
OK, sounds good. Cheers.
