### ISSUE TITLE
IPR022150 AKNA not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3120]
Hi 

please would you revise IPR022150 record. The paper referenced PMID: 30787442 in this record does not confirm that this protein should be associated with the terms
    RNA polymerase II cis-regulatory region sequence-specific DNA binding (GO:0000978)
    DNA-binding transcription activator activity, RNA polymerase II-specific (GO:0001228)

The paper describes AKNA as  
> necessary and sufficient to organize centrosomal microtubules, and promote their nucleation and growth. 

The role of AKNA as a centrosomal protein, is also described in several other papers. 

Please remove the GO mappings listed above, and replace with
 GO:0005813 centrosome 
 GO:0003677 DNA binding

Other GO annotations have been requested to be removed #3121

Thanks

Ruth

**Comment by RLovering** [comment]
BTW Q5T1N1 | AKNAD1 can be included in this InterPro record as it is currently but with the revised GO annotations

**Comment by EBI-Hsinyu** [comment]
Hi Ruth, 
Thank you for this. I have removed the terms (GO:0000978 and GO:0001228). As you mentioned this entry also includes AKNAD1, whose function is unclear. So I won't add any GO term to this entry. 
Regards, 
Hsin-Yu

**Comment by RLovering** [comment]
Thank you so much

Ruth
