### ISSUE TITLE
Q7Z591	AKNA not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3121]
Hi Marcio

this is a centrosomal protein, as described in several papers (see #2848 Thanks. In the Nature paper from 2013 PMID:11268217 they demonstrate correlation of gene expression but they do not demonstrate that AKNA regulates gene expression. In addition the sequence bound confirms this as an AT hook protein, which suggests the sequence bound it not specific enough to confirm DNA binding.

Please remove the following annotations

NTNU | Q7Z591 | AKNA |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:11268217 | 

NTNU | Q7Z591 | AKNA |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:11268217 |   |   | occurs_at(SO:0001952)

Also it is not appropriate to use the IPR000637 record to support this annotation as it states:
>High mobility group (HMG) proteins are a family of relatively low molecular weight non-histone components in chromatin [1]. HMG-I and HMG-Y (HMGA) are proteins of about 100 amino acid residues which are produced by the alternative splicing of a single gene. HMG-I/Y proteins bind preferentially to the minor groove of AT-rich regions in double-stranded DNA in a non-sequence specific manner 

ie this will not provide a genomic address and InterPro have not associated a dbTF activity with this record. Please remove the following annotation
NTNU | Q7Z591 | AKNA |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000637

Thanks

Ruth, Pascale, Colin

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet 

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
