### ISSUE TITLE
P62633	CNBP not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3122]
Hi

Pascale, Colin and I discussed this and it was decided that the role of G-Quadruplex Isomers in the regulation of gene expression in a genomic address context was still being debated. These structures do not provide a sequence specific 'motif' and therefore at this time proteins that bind to G-Quadruplex DNA should not be annotated to dbTF terms

https://pubmed.ncbi.nlm.nih.gov/30920805/ discusses G-Quadruplex Isomers and role in regulation of transcription, this isn't sequence specific because this is a structural aspect. In future the Tx field might resolve how these are acting but too early to make a call about how to capture the activity associated with these proteins using GO terms.

Please delete these annotations:

NTNU | P62633 | CNBP |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:23774591 |   |   | has_input(NCBI_Gene:4609) |   

  |   | NTNU | P62633 | CNBP |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:23774591 |   |   | has_input(NCBI_Gene:4609) 

  |   | NTNU | P62633 | CNBP |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:23774591 |   |   | has_input(NCBI_Gene:4609)

 Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
thanks !
