### ISSUE TITLE
Remove all dbTF annotations associated with IPR000637

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3123]
Hi Marcio

as mentioned in #3121 it is not appropriate to use the IPR000637 record to support GO annotations with  GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific.

 the IPR000637 record states:
> High mobility group (HMG) proteins are a family of relatively low molecular weight non-histone components in chromatin [1]. HMG-I and HMG-Y (HMGA) are proteins of about 100 amino acid residues which are produced by the alternative splicing of a single gene. HMG-I/Y proteins bind preferentially to the minor groove of AT-rich regions in double-stranded DNA in a non-sequence specific manner

ie this will not provide a genomic address and InterPro have not associated a dbTF activity with this record. 

11 of these annotations currently exist in QuickGO: https://www.ebi.ac.uk/QuickGO/annotations?withFrom=InterPro:IPR000637&assignedBy=NTNU_SB 
Please remove the following annotations:

UniProtKB:O43167 | ZBTB24 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB:Q03164 | KMT2A | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q7Z591 | AKNA | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q8WYP5 | AHCTF1 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q96C55 | ZNF524 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q96CK0 | ZNF653 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q9BVI0 | PHF20 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q9H4Z2 | ZNF335 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q9HBE1 | PATZ1 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  
UniProtKB:Q9NR48 | ASH1L | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000637 | 9606 Homo sapiens | NTNU_SB |  

In addition, please remove the InterPro ID IPR000637 from this record:
UniProtKB:P78545 | ELF3 | enables | GO:0000981                DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255              ISM | PMID:19274049 | InterPro:IPR000418 more... | 9606 Homo sapiens | NTNU_SB |  

Thanks

Ruth, Pascale, Colin

**Comment by RLovering** [comment]
@pgaudet @colinlog

**Comment by RLovering** [comment]
Hi
Also, Pascale and Colin reviewed this paper PMID:12920234 and agreed that this confirms that Q96CK0 | ZNF653 is a coreppressor and not a dbTF. As listed above this confirms that this annotation should be removed

NTNU | Q96CK0 | ZNF653 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000637

Thanks
Ruth

**Comment by RLovering** [comment]
Annotations we have noticed have been removed
ZNF524
ZNF335

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
