### ISSUE TITLE
PCBP family not dbTFs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3124]
Hi

Colin, Pascale and I have looked at this family and we have agreed these proteins are not DNA binding transcription factors.

These have KH domains which are associated with RNA binding. Some papers suggest that these proteins bind CCCCCC sequences however, Colin confirms that repeat G content suggests it is not specific DNA binding. 

The paper annotated (PMID:22521865) for Pcbp3 suggests ds DNA binding but then their later paper https://pubmed.ncbi.nlm.nih.gov/24026233/ seems to highlight only ss DNA binding, in line with other papers.  Note the annotations associated with these family members.

It is not clear what function can be associated with these proteins at this point

Please remove the following annotations:

MGI | P57722 | Pcbp3 | enables | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:22521865 |  

 MGI | P57722 | Pcbp3 | enables | GO:0003690 | double-stranded DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:22521865
ECO:0000314 | (IDA)

MGI | P60335 | Pcbp1 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15836633

Thanks

Ruth

**Comment by RLovering** [comment]
Hi Marcio

as discussed above please remove the annotations:

NTNU | Q96I24 | FUBP3 |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:8940189 

NTNU | Q96I24 | FUBP3 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:8940189 |   |   | occurs_at(SO:0001952)

In addition, PMID:32203166 confirms this protein binds LNCRNA which guides the gene to promoter of MYC. This is sufficent evidence to remove the dbTF annotation, althought this PMID:8940189 mentions DNA binding the protein only have KH domains which bind RNA, it may in theory bind ss DNA but ssDNA binding proteins are not dbTFs

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks Marcio 

Annotations to PMID:15836633 and PMID:22521865 in original comment are from MGI 
@krchristie Can you please remove/change? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Karen or Harold

Please could you check and consider revising these annotations

Thanks

Ruth

**Comment by RLovering** [comment]
Hi Karen

we have only about 20 human proteins still annotated as dbTFs which shouldn't be. 7 are due to Ensembl annotations from the mouse ortholog. It would be great if these could get fixed soon. Apologies if you have already done these, and they just haven't shown up in Protein2GO yet. I will add this text to all of the outstanding tickets if I can find them.

Hope all is well with you
Ruth

**Comment by RLovering** [comment]
Hi @krchristie

Our list of DNA-binding transcription factors is about to be published. The reviewers have asked us to comment on whether a specific filter in AmiGO or QucikGO will download this list. Currently there are a few MGI annotations that mean that applying the GO:0003700 filter will lead to several non-dbTF proteins being downloaded. One of these is PCBP1. 

Please revise the annotations associated with PMID: 15836633
MGI | P60335 | Pcbp1 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15836633 
see comments above

Thanks

Ruth

**Comment by pgaudet** [comment]
@krchristie Can you please have a look at this? 
paper says it's a ss DNA binding protein

Thanks, Pascale

**Comment by RLovering** [comment]
David confirmed this has been completed
