### ISSUE TITLE
THAP family remove annotations

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3125]
Hi

I have looked in PubMed and some THAP reviews for confirmation that these proteins bind DNA and there is very little evidence of this. The best is for THAP1 and THAP11. But even though a few papers comment on THAP7 and THAP5 binding DNA the evidence just isn't there. For THAP5 they rely on identification of DNA motif and based on nuclear extracts PMID:21110952. The THAP7 papers don't have DNA binding evidence either. 

THAP4 is involved in heme binding.

THAP9 does bind DNA but is shown to be an active DNA transposase PMID: 23349291 with DNA binding discussed in PMID: 20010837 (THAP Proteins Target Specific DNA Sites Through Bipartite Recognition of Adjacent Major and Minor Grooves).

Summary:

THAP1 | dbTF
-- | --
THAP2 | no data
THAP3 | reg Tx but no DNA binding confirmed
THAP4 | heme binding
THAP5 | PMID 21110952: DNA motif identified using MeWo nuclear extract and the THAP5/dsDNA complex Ippt, then EMSA with nuclear extract
THAP6 | only 1 paper with THAP6 and no mention of DNA binding
THAP7 | THAP7 (2 above) PMID:15561719 paper does not show DNA binding, but does show Tx regulation, annotated this as shows histone tail binding associated with C-terminal 77 amino acids of THAP7. HDAC3 bound specifically to a GST fusion of the THAP domain (amino acids 1–100), but not the central region of the protein (101–231). Some residual binding was also observed with the HID domain (232–309). Subsequent paper PMIDF:16195249 still not showing DNA binding although other papers claim this does
THAP8 | no papers
THAP9 | PMID:23349291 an active P-element DNA transposase. PMID:20010837 DNA binding
THAP10 | no papers
THAP11/Ronin | several papers confirm this is a dbTF PMID: 20581084 PMID:20581084 PMID:19008924 PMID:18585351 THAP11 ChIP data localises this protein to the promoter
THAP12/THAP0/DAP4 | PMID:  7828849 THAP12 but no DNA binding data, proposed as serine/threonine kinase

**Comment by RLovering** [comment]
Because of the information above this family should not be annotated as dbTF unless expt evidence is available. 
Please remove the following annotations:

GENE   PRODUCT ID | SYMBOL | QUALIFIER | GO TERM | GO NAME | ECO ID | GO EVIDENCE CODE | REFERENCE | WITH/FROM | TAXON ID | ASSIGNED BY | ANNOTATION EXTENSION | GO ASPECT
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Q7Z6K1 | THAP5 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase   II-specific | ECO:0000255 | ISM | PMID:19274049 | InterPro:IPR006612 | 9606 | NTNU_SB |   | F
Q7Z6K1 | THAP5 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase   II-specific | ECO:0005556 | ISA | GO_REF:0000113 | tfclass:2.9.1 | 9606 | NTNU_SB |   | F
Q8WTV1 | THAP3 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase   II-specific | ECO:0000255 | ISM | PMID:19274049 | InterPro:IPR006612 | 9606 | NTNU_SB |   | F
Q8WTV1 | THAP3 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase   II-specific | ECO:0005556 | ISA | GO_REF:0000113 | tfclass:2.9.1 | 9606 | NTNU_SB |   | F
Q9BT49 | THAP7 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase   II-specific | ECO:0000255 | ISM | PMID:19274049 | InterPro:IPR006612 | 9606 | NTNU_SB |   | F
Q9BT49 | THAP7 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase   II-specific | ECO:0005556 | ISA | GO_REF:0000113 | tfclass:2.9.1 | 9606 | NTNU_SB |   | F

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
