### ISSUE TITLE
Q5SXM2	SNAPC4 is a GTF not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3126]
Hi Marcio

please could you delete this annotation as this protein is a GTF

UniProtKB | Q5SXM2 | SNAPC4 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255 | ISM | PMID:19274049 | InterPro:IPR001005\|InterPro:IPR009057 | 9606 | NTNU_SB

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio
