### ISSUE TITLE
IPR033375 Please remove DNA-binding transcription repressor activity, RNA polymerase II-specific (GO:0001227)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3127]
IPR033375 Please remove DNA-binding transcription repressor activity, RNA polymerase II-specific (GO:0001227)

The role as dbTF has not been shown. It rather seems to be involved in DNA looping, see PMID:31547883 "CGGBP1 Regulates CTCF Occupancy at Repeats" 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale, 
Thanks for highlighting this. I have removed the term.
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks !
