### ISSUE TITLE
Q9UFW8 CGGBP1	NOT	GO:0001227	DNA-binding transcription repressor activity, RNA polymerase II-specific

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3128]
Hi @mlacencio 

Q9UFW8 CGGBP1	should not be annotated to GO:0001227	DNA-binding transcription repressor activity, RNA polymerase II-specific from PMID:10692448. 

The paper does not provide direct evidence for a molecular function annotation. (BP annotation to transcription already exists).

Please remove the annotation. 

Thanks, Pascale

**Comment by RLovering** [comment]
the evidence in PMID:10692448 suggests this is a looping factor, also likely to be non-specific DNA binding, as 70% of promoters are CG rich

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotation!

Best,

Marcio

**Comment by pgaudet** [comment]
@mlacencio Can you please also remove the annotation to 

GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000315(IMP) | ECO:0000315 | (IMP) |   | PMID:10692448

as mentioned above the authors mention the binding is non-specific. You might want to use a parent GO:0003690 double-stranded DNA binding

**Comment by mlacencio** [comment]
@pgaudet ,

Done!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks
