### ISSUE TITLE
Q9BYE7	PCGF6	NOT	GO:0003700	DNA-binding transcription factor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3129]
Hi Marcio, 

Q9BYE7	PCGF6	should not be annotated to	GO:0003700	DNA-binding transcription factor activity	from PMID:8521824.	

While the paper seems to show DNA binding, there are a large number of newer papers that show that PCGF6 is a co-factor. It seems like the data from this paper are an artifact. 

Please remove. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Marcio
this is one of yours:

NTNU | Q99NA9 | Pcgf6 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:8521824 
NTNU | Q99NA9 | Pcgf6 |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:8521824
ECO:0000314 | (IDA)

Pascale has removed the UniProt annotation associated with this paper, based on her comments above

Please remove

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Hi @mlacencio ,

The second annotation 

NTNU | Q99NA9 | Pcgf6 |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:8521824
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ECO:0000314 | (IDA)



has not yet been removed. 

Also I am not sure the sequence-specific DNA binding is right. 

Thanks, Pascale

**Comment by mlacencio** [comment]
Hi @pgaudet !

I could not find this annotation via Protein2GO.

Best,

Marcio

**Comment by pgaudet** [comment]
Looks like it was from MGI. Thanks, Pascale
