### ISSUE TITLE
Q8IWS0	PHF6	not GO:0001227	DNA-binding transcription repressor activity, RNA polymerase II-specific

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3130]
Hi Marcio, 

Q8IWS0	PHF6	sould not be annotated to 
* GO:0001227	DNA-binding transcription repressor activity, RNA polymerase II-specific
and 
* GO:0043565 | sequence-specific DNA binding |   | IDA | PMID:24554700

The DNA binding is non-specific (see Section entitled 'PHF6-ePHD2 Domain Basic Surface Nonspecifically Binds toDNA' pm page 10076). Since the interaction is non-specific, we cannot annotate a MF, but you can annotate Cellular component chromatin if that is useful. 

PHF6 is a coTF, but I dont see any transcriptional assay in this paper on which that annotation could be based. 

Please remove those annotations. 

Thanks, Pascale

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio
