### ISSUE TITLE
Sarnp MGI:1913368 not a transcription factor

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3131]
Hi @hdrabkin 

MGI:1913368 not a transcription factor. There are 2 annotations to GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific (IMP and IDA) from PMID:18480465, 

No evidence for dbTF; see discussion: "Based on our current findings, we **propose** that this protein acts as a sequence-specific DNA binding factor through its N-terminal SAP domain". SAP domain believed to be a SUMO E3 ligase, see PMID:32317623

The DNA binding annotation should also be removed. 

Thanks, Pascale

**Comment by LiNiMGI** [comment]
I would like to keep all the annotations based on the evidences I copied from the paper (1110005A23RIK is MGI:1913368):

reporter gene assay and real-time quantitative PCR analysis, in which the activity of the Fshb, but not the Cga nor Lhb promoter, was reduced following 1110005A23RIK overexpression...

ransfection of an siRNA construct that reduces 1110005A23Rik expression, increased activity of the Fshb gene promoter...

a LGALS4-1110005A23RIK fusion protein was created, enabling assessment of the effect of this protein or its truncated mutants on the activity of a LGALS4-responsive reporter gene...

In order to verify whether 1110005A23RIK exerts a direct effect at the level of the Fshb gene promoter, 1110005A23RIK fused to an HA tag was overexpressed. The tagged protein was detected at the Fshb gene proximal promoter by **ChIP** using antisera to HA, which did not precipitate any endogenous proteins associated with the promoter in these cells...

Also, information about SAP domain: 
http://smart.embl.de/smart/do_annotation.pl?DOMAIN=SM00513

Thanks,
Li

**Comment by ValWood** [comment]
There evidence in yeast that this protein does bind to DNA
https://www.yeastgenome.org/locus/YER063W#go
but is it not thought to be a transcription factor, and I never trust the old experiments anymore...

It isn't very well characterised in yeast, but it appears to be involved in RNA export.
Evidence in plant also points to a role in mRNA export.

Basically it isn't very well characterised but  the 1:1 conservation across eukaryotic species makes the likelihood of this  being a DNA-binding TF 

I don't think SAP is an E3 ligase, although it is present in some E3 ligases. I thought it was RNA binding....

**Comment by ValWood** [comment]
here is a nice summary (and structure)  of yeast THO1  in 2016
https://pubmed.ncbi.nlm.nih.gov/27303905/

**Comment by ValWood** [comment]
Tho1 was identified as a multicopy suppressor of hpr1Δ (Jimeno et al., 2002 ▸; Piruat & Aguilera, 1998 ▸) and was thought to function in a similar manner to the yeast protein Sub2. Studies revealed that Tho1, like Sub2, can assemble onto the nascent mRNA during transcription and that Tho1 and Sub2 can provide alternative pathways for mRNP biogenesis in the absence of a functional THO complex (Jimeno et al., 2006 ▸). Null mutants of THO1 did not result in a distinct phenotype and thus the function of Tho1 in vivo remains unclear. However, the ability of Tho1 to suppress hpr1Δ was shown to be located in the RNA-binding C-terminal region. Our study has determined the solution structures of both the N-terminal SAP domain, which in other proteins has been shown to bind to DNA (Göhring et al., 1997 ▸), and the C-terminal domain thought to be responsible for RNA binding. The SAP domain contains a helix–extended-loop–helix motif similar to those found in other members of this family and binds to DNA. The C-terminal region adopts a helical fold similar to that of the WHEP RNA-binding domains of metazoan aminoacyl-tRNA synthetases (Cahuzac et al., 2000 ▸).

I think its role  alongside the THO complex is fairly well accepted. I doubt that anyone would say it was  a DNA-binding TF today.

**Comment by pgaudet** [comment]
Thanks for looking into this @LiNiMGI 

The SMART SAP domain description doesn't support this domain being a DNA binding transcription factor. Maybe it can bind DNA but that doesn't make it a dbTF. For it to be a dbTF, the DNA motif it binds would need to be characterized, or the DNA binding motif should be similar to other DNA binding motifs known to be part of dbTFs.

Moreoever, on its own, ChIP data is not sufficient to show a dbTF function (or even a direct DNA binding function). According to the available evidence, Sarnp should not be annotated to the MF dbTF. We are not disputing the role in the MF regulation of transcription. 

UniProt has a good description of what the role of Sarnp is believed to be: https://www.uniprot.org/uniprot/Q9D1J3.

Thanks, Pascale

**Comment by LiNiMGI** [comment]
Thanks Pascale!
The reason I put the SMART SAP domain information in the response was for you to know that it’s not only believed to be “a SUMO E3 ligase”, it could be a DNA-binding motif.

If we think the ChIP evidence is too weak to say it’s DNA binding, then I propose to change the annotations as below:

chromatin binding
GO:0003682 IDA 
Occurs at: transcriptional_cis_regulatory_region ; SO:0001055
Has input: Fshb ; MGI:95582 
Occurs in: gonadtroph ; CL:0000437

negative regulation of transcription by RNA polymerase II
GO:0000122  IDA
Has input: Fshb ; MGI:95582
Occurs in: gonadtroph ; CL:0000437

negative regulation of transcription by RNA polymerase II
GO:0000122  IMP
Has input: Fshb ; MGI:95582
Occurs in: gonadtroph ; CL:0000437

I deleted the two TF function annotations from MGI.
Please let me know if you have any other suggestions.
Thanks,
Li

**Comment by pgaudet** [comment]
Looks good! Thanks @LiNiMGI
