### ISSUE TITLE
EAF2 is not a dbTF - NTNU to delete

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3132]
Hi Marcio

@colinlog, @pgaudet and I have reviewed the paper PMID:16114057 which you annotated to provide the annotations:

NTNU | Q96CJ1 | EAF2 |   | GO:0045944 | positive regulation of transcription by RNA polymerase II | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:16114057
NTNU | Q96CJ1 | EAF2 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:16114057 
NTNU | Q96CJ1 | EAF2 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:16114057
ECO:0000314 | (IDA)

We spent a long time examining this paper as well as other papers that have been published since this paper. In addition, we aligned this protein (Q96CJ1) with its paralog EAF1 (Q96JC9) https://www.uniprot.org/align/A20200618216DA2B77BFBD2E6699CA9B6D1C41EB209346CG.

While we agree that this paper does provide evidence that the protein binds DNA and regulates transcription the subsequent literature does not discuss the DNA binding ability of this protein. Instead it is described clearly as contributing to elongation. 

We did identify that this protein does appear to multiple roles, for example in https://pubmed.ncbi.nlm.nih.gov/28887217/ this figure https://www.sciencedirect.com/science/article/pii/S1874939917300482?via%3Dihub#f0040 (Figure 8) clearly shows EAF1 and 2 binding to TP53 and SMAD2/3 to in suppressing TGF-βsignaling. Whereas https://pubmed.ncbi.nlm.nih.gov/32087315/ confirms the role of this protein in regulating elongation.

However EAF1 and 2 are highly homologous and there is no clear region in these proteins that can be identified as likely to bind a specific DNA sequence. The paper you annotated does purify the recombinant protein, but the author did not (and have not since) tried to identify the DNA binding domain in the protein. Some false positives do occur in these types of studies and therefore we would like to be more cautious and not include this as a dbTF.

We would be very grateful if you would remove the following annotations:
 
NTNU | Q96CJ1 | EAF2 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:16114057 
NTNU | Q96CJ1 | EAF2 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:16114057
ECO:0000314 | (IDA)

Kind regards

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet

I have removed the annotations!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
