### ISSUE TITLE
 KW-0747 incorrect mappings

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3134]
UniProtKB/SwissProt | O13792 SPAC17G6.14c
This is TREX complex, can the KW-0747 be deleted?
Thanks

**Comment by ValWood** [comment]
UniProtKB/SwissProt | O14352 SPBC30D10.06
This is U6 snRNP, can the KW-0747 be deleted?

**Comment by ValWood** [comment]
spliceosomal snRNP complex subunits

- [ ] SPBC119.13c	prp31	U4/U6 x U5 tri-snRNP complex subunit Prp31. O42904
- [ ] SPAC29E6.02	prp3	U4/U6 x U5 tri-snRNP complex subunit Prp3 Q09856
- [ ] SPBC19C2.08	prp38	U4/U6 x U5 tri-snRNP complex subunit Prp38 Q9UUD2

**Comment by sylvainpoux** [comment]
Done
Thanks
Sylvain

**Comment by pgaudet** [comment]
thanks !
