### ISSUE TITLE
Catalytic GO terms on IPR001431 & IPR011249

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3136]
Peptidase M16, zinc-binding site
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR001431/

- description mentions several examples of proteins with this domain that lack activity
=> suggest remove "metalloendopeptidase activity (GO:0004222)"

==

Metalloenzyme, LuxS/M16 peptidase-like
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR011249/

- description also mentions "non-peptidase homologues belonging to MEROPS peptidase family M16"
=> suggest remove "catalytic activity (GO:0003824)"

The specific issue I came across is that these two InterPro terms add catalytic GO terms to the alpha subunit of the mitochondrial processing peptidase (MPP), which is recognised as a non-catalytic subunit (e.g. see PMID: 12191769). (The beta subunit has the catalytic activity).

E.g. https://www.uniprot.org/uniprot/Q10713

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Thank you for this. I have removed the terms from those entries. The changes will be seen in the next release.
Best,
Sara

**Comment by sjm41** [comment]
Great, thanks Sara.
