### ISSUE TITLE
PTN000220169 (PTHR11851 )- "endopeptidase activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3137]
PTN000220169 adds "endopeptidase activity(CONTRIBUTES_TO)" to members of the METALLOPROTEASE (PTHR11851) family.
PTHR11851 comprises both subunits from two homologous complexes - using humans
as the example, those subunits are:

- HUMAN|HGNC=18667|UniProtKB=Q10713	Mitochondrial-processing peptidase subunit alpha   MITOCHONDRIAL-PROCESSING PEPTIDASE SUBUNIT ALPHA (PTHR11851:SF192)

- HUMAN|HGNC=9119|UniProtKB=O75439	Mitochondrial-processing peptidase subunit beta    MITOCHONDRIAL-PROCESSING PEPTIDASE SUBUNIT BETA (PTHR11851:SF103)

- HUMAN|HGNC=12585|UniProtKB=P31930	Cytochrome b-c1 complex subunit 1, mitochondrial    CYTOCHROME B-C1 COMPLEX SUBUNIT 1, MITOCHONDRIAL (PTHR11851:SF116)

- HUMAN|HGNC=12586|UniProtKB=P22695	Cytochrome b-c1 complex subunit 2, mitochondrial    CYTOCHROME B-C1 COMPLEX SUBUNIT 2, MITOCHONDRIAL (PTHR11851:SF216)

The source annotation for the ""endopeptidase activity" term comes from two C. elegans proteins:

- Q95XN2	(mppa-1)	contributes_to	metalloendopeptidase activity	IDA	PMID:16788047

- Q23295	(mppb-1)	contributes_to	metalloendopeptidase activity	IDA	PMID:16788047

Those annotations do represent the data from that 2006 paper, which says "Although neither the ZC410.2 (=mppb-1) nor the Y71G12B.24 (= mppa-1) protein showed any proteolytic activity independently (Fig. 5, A and B), a mixture of the two proteins was found to cleave a substrate peptide...Therefore, the metallopeptidase activity of MPP is suggested to depend on the association of the ZC410.2 and Y71G12B.24 proteins."

However, the wider/deeper understanding (as stated in the introduction to that worm paper) is that:
i) peptidase activity of the MITOCHONDRIAL-PROCESSING PEPTIDASE complex is restricted to the beta subunit (= human O75439/PMPCB)
ii) peptidase activity of the CYTOCHROME B-C1 COMPLEX is either restricted to the homologous subunit (= human P31930/UQCRC1) or is absent from this complex.
(see PMID:12191769 for a review, and the intro to PMID:16788047; also see UniProt webpages for Q10713 & O75439, and P31930 & P22695)

So...I think the propagation of "endopeptidase activity(CONTRIBUTES_TO)" should either be blocked on this node, or else the PANTHER family needs splitting out and GO terms assigned appropriately.

@hattrill

**Comment by pgaudet** [comment]
Thanks for pointing this out @sjm41 
I removed the MF for the alpha subunit genes, but kept the BP protein processing involved in protein targeting to mitochondrion. 

Is that OK ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Sounds good, thanks @pgaudet
