### ISSUE TITLE
Rat Gtf2f2 (RGD:620772) should not be annotated to 'regulation of transcription'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3138]
Hi @gthayman 

Gtf2f2 (RGD:620772) is a GTF. It should be annotated to ' GO:0006366 transcription by RNA polymerase II', not 'positive regulation of transcription by RNA polymerase II'  

Also, the same paper PMID:1429731 can be used to annotate the MF 'GO:0016251  RNA polymerase II general transcription initiation factor activity' and the root MF (ND) annotation can be removed. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Similarly for PMID:7929273
Annotations should not be to the 'regulation' terms: 

* positive regulation of RNA polymerase II transcription preinitiation complex assembly -> 
 RNA polymerase II transcription preinitiation complex assembly
* positive regulation of transcription elongation from RNA polymerase II promoter -> transcription elongation from RNA polymerase II promoter

Thanks, Pascale

**Comment by gthayman** [comment]
Done.

**Comment by pgaudet** [comment]
Thanks !
