### ISSUE TITLE
contributes_to used with BP terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3139]
Hi @slaulederkind came across these annotations with contributes_to used for process aspect that you may want to check out.

Slco1a4	contributes_to	GO:0010468	PMID:27090119|RGD:15090804	IEP	P	20200103
Abcc2	contributes_to	GO:0010468	PMID:27090119|RGD:15090804	IEP	P	20200103
Nr1h4	contributes_to	GO:0015721	PMID:19136377|RGD:15042882	IMP	P	20191213
Nr1h4	contributes_to	GO:0015721	PMID:29138817|RGD:15042871	IEP	P	20191213
Nr1h4	contributes_to	GO:0015721	PMID:29235094|RGD:15042872	IDA	P	20191213
Nr1h4	contributes_to	GO:0015721	PMID:30068870|RGD:15042870	IMP	P	20191213
Nr1h4	contributes_to	GO:0035690	PMID:29235094|RGD:15042872	IDA	P	20191213
Nr1h4	contributes_to	GO:0038183	PMID:19136377|RGD:15042882	IMP	P	20191213
Nr1h4	contributes_to	GO:0038183	PMID:29138817|RGD:15042871	IEP	P	20191213
Nr1h4	contributes_to	GO:0038183	PMID:29235094|RGD:15042872	IDA	P	20191213
Nr1h4	contributes_to	GO:0038183	PMID:30068870|RGD:15042870	IMP	P	20191213
Nr1h4	contributes_to	GO:0042632	PMID:19136377|RGD:15042882	IMP	P	20191213
Nr1h4	contributes_to	GO:0070328	PMID:19136377|RGD:15042882	IMP	P	20191213
Nr1h4	contributes_to	GO:0072574	PMID:29138817|RGD:15042871	IEP	P	20191213
Nr1h4	contributes_to	GO:0097421	PMID:29138817|RGD:15042871	IEP	P	20191213
Abcb11	contributes_to	GO:0010468	PMID:27090119|RGD:15090804	IEP	P	20200103

**Comment by slaulederkind** [comment]
Thanks for the info, Helen.  The annotations have been fixed.
