### ISSUE TITLE
IPR028128 remove annotation to DNA-binding transcription factor activity (GO:0003700)? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3140]
Hello, 

IPR028128 (Vasculin family) seems to bind DNA and regulate transcription, based on the paper cited in the entry (PMID: 14612417). 

However: 
1. In PMID: 14612417, they show that Vasculin binds an GC-rich region, which may be more structural rather than binding a 'true' motif

2. A more recent paper, PMID:26156556, shows that Vasculin binds RNA with even higher affinity than DNA. 

As far as we can tell the role of this protein is not clear, I would remove the MF annotations (or if you want to keep RNA/DNA binding, those are probably correct). 

Thanks, Pascale and @RLovering

**Comment by sarach06** [comment]
Hi!
I have changed the MF annotation and added GO:0003677 and GO:0003723 (DNA and RNA binding) instead. I also added a sentence in the abstract along with the reference you provided. Let me know if you agree with that. 
Many thanks,
Sara

**Comment by pgaudet** [comment]
Thanks !
