### ISSUE TITLE
MGI:1920524  Q6NXH3  Gpbp1 not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3141]
Hi

This gene is described as a dbTF based on this paper PMID:14612417. Unfortunately the EMSA analysis does not use a specific sequence to demonstrate that the protein binds a specific sequence, just uses unlabled probe.

Subsequent papers suggest that this is protein preferentially binds RNA (PMID: 26156556)

Please delete this annotation
  |   | MGI | Q6NXH3 | Gpbp1 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:14612417
ECO:0000314 | (IDA)

We have also disputed the InterPro annotation https://github.com/geneontology/go-annotation/issues/3140

Many thanks

Ruth

**Comment by krchristie** [comment]
Hi @RLovering - @LiNiMGI and I have read this paper and we felt the EMSA was fine for what they were talking about, i.e. binding to G-C rich sequences, similar to Sp1, which is also annotated to GO:0003700.

Regarding the subsequent paper (PMID: 26156556), while it does show RNA binding, it also confirms that Gpbp1 binds DNA.

Thus, we do not agree that these annotations should be removed.
