### ISSUE TITLE
Q6PCN7	Hltf - is there sufficient evidence for this to be dbTF?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3142]
Hi Marcio

I am not convinced that PMID:9427542 provides sufficient evidence that Hltf is a dbTF
NTNU | Q6PCN7 | Hltf |   | GO:0045944 | positive regulation of transcription by RNA polymerase II | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:9427542 | 
  |   | NTNU | Q6PCN7 | Hltf |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:9427542 |   |   |   |   |   |   |   |  
ECO:0000314 | (IDA)
  |   | NTNU | Q6PCN7 | Hltf |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:9427542 |   |   | occurs_at(SO:0001952)
ECO:0000314 | (IDA)

My query is based on the fact that newer papers e.g. https://pubmed.ncbi.nlm.nih.gov/28954549/ have demonstrated that  "SMARCAL1, ZRANB3, and HLTF are three related members of this family with specialized functions that maintain genome stability during DNA replication. These proteins are recruited to replication forks through protein-protein interactions and bind DNA using both their motor and substrate recognition domains (SRDs)". 

I think that the data in PMID:9427542 is compatible with the function of this proteins role in DNA replication. 

Please would you review the literature published since PMID:9427542 and consider deleting the annotations listed above

Many thanks

Ruth

@colinlog

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet ,

Annotations removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks
