### ISSUE TITLE
PANTHER:PTN000552063 PTN000552063 FBgn0026144 not a troponin

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3144]
Could you block propagation from PANTHER:PTN000552063 PTN000552063  to FBgn0026144 (CBP) as it is not a troponin - has an EF-hand which I think is where the PANTHER call is arising from - other orthology predictions do not make this link.

**Comment by ValWood** [comment]
EF-hands can be really conserved in non-orthologous proteins...

**Comment by marcfeuermann** [comment]
An old ticket still open. Has been probably solved a while ago. An opportunity to further clean the annotation.
