### ISSUE TITLE
Changing IDs in Protein2GO AE field

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3146]
Hi @alexsign 
I'm not sure this is the right tracker to use, or if you would prefer this request by email.

However, as the GOC has agreed that UniProt IDs will be used to represent genes and transcripts would you be able to change all of the ENSG and ENST IDs in the AE field to UniProt IDs? 

If so do you need help to do this?
Or do you need all groups that have ENSG/T IDs to agree to this before you apply this?

Thanks

Ruth

**Comment by alexsign** [comment]
Hi @RLovering, conformations from the groups would be nice. I can start fixing them for UCL sources if it's ok. 

Here is the counts for P2GO editable sources:

AgBase	52
UniProt (EBI Curators)	17
HGNC	1
ParkinsonsUK-UCL	114
BHF-UCL	3164
FlyBase	2
Automated Function Prediction SIG CAFA Experiment (UniProt Curators)	1
SynGO	2
AlzheimersResearchUK-UCL	1310
DiBest-Unical	21

**Comment by RLovering** [comment]
Hi Alex
so it looks like UCL is the main contributor!  It would be great if you could as I have 3 students creating microRNA annotations and to complete their project they will do a Cytoscape analysis. This will be a lot easier to do if all targets of microRNAs are UniProt IDs.

I am a bit worried about the mapping from Ensembl to UniProt IDs. Will you be able to make sure these all map to the 'reviewed' entry if there is one for the gene/protein?

Thank you so much

Best

Ruth

**Comment by RLovering** [comment]
Hi Alex
Also will you need us to stop editing when you change the IDs?

Thanks
Ruth
