### ISSUE TITLE
PTN000162487 - PTHR 11521 - Troponin-T not ATPase or Ca2+ binding 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3148]
PTN000162487 Troponin-T
has Ca2+ binding, but this is from the D.mel version and I think that this is not seen outside of insects - so best not to propagate.

Also
I have just disputed, via Protein2GO, the annotation to the human protein that underlies 
'contributes_to calcium-dependent ATPase activity' as the troponin complex is not an ATPase.

**Comment by sjm41** [comment]
@hattrill I was just about to make this ticket myself...when I spotted you made it 23 hours ago :-)

**Comment by hattrill** [comment]
Great minds....@sjm41. I had an accidental run in with the troponin complex yesterday when doing ncRNAs!

**Comment by pgaudet** [comment]
Fixed, thanks for reporting the issue.

**Comment by hattrill** [comment]
Thanks
