### ISSUE TITLE
Mouse Kdm3a (MGI:98847) is NOT a dbTF 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3152]
Hi @hdrabkin 

This annotation should be changed to co-factor: 

* MGI | MGI:98847 (Q6PCM1) | Kdm3a | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) |  | PMID:17991879 |   ECO:0000314 | (IDA)

also, it does not directly bind DNA, so please change these:

* MGI:98847  GO:0000976 | transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) |  PMID:17991879 

* MGI:98847 | Q6PCM1 | Kdm3a | enables | GO:0000979 | RNA polymerase II core promoter sequence-specific DNA binding | ECO:0000314(IDA) |PMID:17943087

Thanks, Pascale & Ruth

**Comment by hdrabkin** [comment]
Done
