### ISSUE TITLE
InterPro2GO - adding 'ATP-dependent peptidase activity' to some entries

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3153]
Hi

From the descriptions/members, I think the following InterPro signatures could usefully and accurately have the 'ATP-dependent peptidase activity (GO:0004176)' term added:

IPR000642:Peptidase M41 (also see https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=m41)
IPR037219:Peptidase M41-like
IPR005936:Peptidase, FtsH
IPR011546:Peptidase M41, FtsH extracellular

IPR001907:ATP-dependent Clp protease proteolytic subunit                               

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Thank you for highlighting this. I have added the term to those entries. The changes will be seen in the next InterPro release (81.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Great, thanks Sara.
