### ISSUE TITLE
IPR034632 NOT DNA-binding transcription factor activity, RNA polymerase II-specific (GO:0000981)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3154]
Hello, 

IPR034632 corresponds to a domain present in a single-stranded DNA binding or a RNA binding paper. In any case, the function 'DNA-binding transcription factor activity, RNA polymerase II-specific (GO:0000981)'  is incorrect. It doesn't seem we know very much about the function of this protein, see more recent paper: PMID:22801375, which shows transcription factor binding but isn't clear about its DNA binding function.

I suggest you remove  DNA-binding transcription factor activity, RNA polymerase II-specific (GO:0000981). You can replace by the BP 'GO:0006357 regulation of transcription by RNA polymerase II' . 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I have changed the term and added this reference. 
Best regards,
Sara.

**Comment by pgaudet** [comment]
Thanks !
