### ISSUE TITLE
IPR036051 should not include nucleic acid binding (GO:0003676)

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3155]
Hi

the KRAB domain superfamily record IPR036051 https://www.ebi.ac.uk/interpro/entry/InterPro/IPR036051/ and the record IPR001909 should not include the GO term nucleic acid binding (GO:0003676)
The record actually states: The KRAB domain is a protein-protein interaction module which represses transcription through recruiting corepressors.

A KRAB domain may consist of an A-box, or of an A-box plus either a B-box, a divergent B-box (b), or a C-box. Only the A-box is included in this model. 

The KRAB domain functions as a transcriptional repressor when tethered to the template DNA by a DNA-binding domain. A sequence of 45 amino acids in the KRAB A subdomain has been shown to be necessary and sufficient for transcriptional repression. 

Best 

Ruth

**Comment by sarach06** [comment]
Hi Ruth,
Thank you very much. I have removed the term from those entries. The changes will be seen in the next release (InterPro 81.0).
Best regards, 
Sara

**Comment by pgaudet** [comment]
Thanks!
