### ISSUE TITLE
MGI:1934811 Nucks1 NOT a dbTF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3156]
Hi @hdrabkin 

MGI:1934811 Nucks1 is annotated as a dbTF from PMID:24931609, but there is no assay testing the function. I suggest you remove the MF annotation to GO:0001228 DNA-binding transcription activator activity, RNA polymerase II-specific. 

Maybe the protein binds DNA but the paper does not show sequence-specific binding. Also, it has no domain supporting this annotation, and I cannot find other papers that helps. For this paper, then I suggest you remove 'GO:0001228 DNA-binding transcription activator activity, RNA polymerase II-specific. '

Thanks, Pascale

**Comment by hdrabkin** [comment]
Figure 5 B and supplemental procedures:
Mobiity shift done with specific DNA fragments and Nucks (as supplied by lysates).  As described below.

Electromobility shift assayNuclear,  cytosolic  or  whole  cell  protein  extracts  were  collected  by  NE-PER  Nuclear  and Cytoplasmic Extraction  Reagent  Kit  (Thermo  Scientific).The  probes  were  predicted NUCKS bindingsequence(5'-TCCAGACCTTTAAATTGGAACCTCGGTGTTACTTGTGTTT-3')from mouseIR promoteror from literature (Foti et al., 2003). Procedure of EMSA has been described previously (Ghosh et al., 2012; Teo et al., 2010).

Also: Supplemental figure S1 and S2 describes a DNA binding domain.

**Comment by pgaudet** [comment]
Hi @hdrabkin 

Thanks for looking into this. Since the EMSA was done on cell/nuclear extracts, the binding may be indirect. In these cases, we also require that the protein contains a known DNA binding motif or that it has been otherwise shown to bind DNA (more directly), but there is no other data that we could find. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
How about I change to co-activator?

**Comment by pgaudet** [comment]
This is the only paper that implicates this gene in transcription. The MF is not clear; I dont think there is any more evidence for coTF than TF. I would stick only to the BP annotation.

**Comment by RLovering** [comment]
Hi Harold

I have just added the coactivator annotation to human protein based on PMID:25116364

so mouse will get this annotation via Ensembl

Best

Ruth

**Comment by hdrabkin** [comment]
Actually, we will get it when we convert human experimental annotation from  GOA to ISO

**Comment by RLovering** [comment]
excellent, let us know when the dbTF annotation is removed
then we can update the spreadsheet and close this
Thanks
Ruth

**Comment by hdrabkin** [comment]
Removed

**Comment by RLovering** [comment]
thanks Ruth
