### ISSUE TITLE
Conflicting evidence for IER2 Q9BTL4 - probably not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3159]
Hi Marcio and Pascale

while I agree that PMID:19584537 supports the dbTF annotations that NTNU have associated with this protein. The protein has no obvious DNA binding domain and recent data suggests it has other very different roles.

PMID: 30599213 IER Family Proteins Are Regulators of Protein Phosphatase PP2A and Modulate the Phosphorylation Status of CDC25A. This paper states that: IER2 and IER5L activate transcriptional activity of HSF1

It is therefore possible that the results of the experiments annotated in PMID:19584537 actually were due to IER2 binding to an e.coli dbTF which had some affinity for the promoter region in the reporter assay. 

Please remove the annotations:

NTNU | Q9BTL4 | IER2 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19584537 

NTNU | Q9BTL4 | IER2 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19584537 

SWIS | Q9BTL4 | IER2 |   | GO:0003677 | DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) | 2 | PMID:19584537

Thanks

Ruth

@colinlog

**Comment by colinlog** [comment]
Hi Ruht, Pascale, Marcio,
I have looked at PMID:19584537 figure 5 and agree with Ruth, this is not sufficient evidence for sequence-specific DNA binding activity, also in light of the fact that in yeast the human INO1 promoter appears to be subject to yeast INO2/4 dbTF heterodimer regulation and thus IER2/ETR101 may well exert effect 'indirectly'.  The paper is quite interesting, but Figure 5 is shaky as all the parts of the hINO1 promoter are shifted.  Best, Colin

**Comment by pgaudet** [comment]
Disputed in P2GO to Cristina. I also asked to change the entry description ("DNA-binding protein that seems to act as a transcription factor (PubMed:19584537)."

Thanks, Pascale

**Comment by pgaudet** [comment]
Only NTNU annotations remain to be fixed.

**Comment by mlacencio** [comment]
Hi @pgaudet  and @RLovering ,

Annotations removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
