### ISSUE TITLE
Jarid2 not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3160]
Hi Marcio

The article you have curated PMID: 12890668 states: Among 38 oligonucleotides we sequenced (data not shown), 25 (66%) contain A/T-rich sequences, suggesting that JMJ prefers to bind to A/T-rich sequences, which contain a 5′-(T)4-6, or -TATT-, or -TAAT-motif.

while PMID: 20075857 confirms that mouse Jarid2 (alias jmj) binds DNA, the specificity of this binding is not demonstrated and in fact the discussion hightlights that it has a 'broader specificity for DNA' and that it is likely that JARID2 recruits PRC2 in combination with other dbTFs"

>Our data, together with the reported ability of the JARID2 ARID domain to bind different DNA sequences17, demonstrate that JARID2 is a critical regulator of PRC2 binding to target genes. This is further supported by the ability of JARID2 to directly recruit PRC2 activity to an artificial promoter (Fig. 2d). Previous studies have identified several DNA sequences binding to the ARID domain of JARID2 (ref. 17). The diversity of these sequences suggests that JARID2 might have a broader specificity for DNA, and they could indicate that the association of PRC2 with specific target genes is not only determined by JARID2, but also in combination with other transcription factors and by the affinity of PRC2 for H3K27me2/3 (refs 26, 27). 

Paper 17 referenced above is https://www.jbc.org/content/278/43/42247.long Fig 5B in this paper confirms "Purified GST-JMJ aa 529-798 was incubated with 20 fm (about 40,000 cpm/lane) of an A/T-rich oligonucleotide, TX2, labeled with 32P." This article does demonstrate gene regulation by JMJ and a target sequence. However in the discussion they point out that : "due to the loose consensus DNA binding sites of JMJ, it is difficult to identify the JMJ target gene by searching the JMJ binding motif in the promoter region." Although this article does discuss Therefore while  

Furthermore, JARID2 is related to JARID1 alias KDM5A/B/C which have been discussed in https://github.com/geneontology/go-annotation/issues/3008 where Colin confirms the likely role of this family as coregulators and not dbTFs.

Please remove/replace the following annotations

NTNU | Q62315 | Jarid2 |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:12890668
Replace with  GO:0003714 transcription corepressor activity

NTNU | Q62315 | Jarid2 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:12890668
Replace with  GO:0003680 AT DNA binding (as mentioned before GO:0003680 AT DNA binding term, the definition is being revised to describe this as AT rich DNA binding and the name is changing to GO:0003680 minor groove of adenine-thymine-rich DNA binding)

Thanks 

Ruth

@colinlog

**Comment by mlacencio** [comment]
Dear @pgaudet and @RLovering ,

Annotations removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
