### ISSUE TITLE
KMT2A is a histone methyltransferase not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3161]
Hi Marcio

this protein Q03164 | KMT2A is a histone methyltransferase

Please remove the annotation you have created based on InterPro:IPR000637. This domain does not support the dbTF annotation

NTNU | Q03164 | KMT2A |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000637

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet ,

Removed!

Best,

Marcio
