### ISSUE TITLE
LCOR (alias Pali1) and LCORL (alias PALI2) these are not dbTFs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3162]
Hi Marcio

The presence of a DNA binding domain is not sufficient to confirm the role of a protein as a dbTF. 

Please remove these annotations as the InterPro:IPR007889 just states this domain can be mapped to DNA binding:
NTNU | Q96JN0 | LCOR |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR007889

NTNU | Q8N3X6 | LCORL |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR007889

PMID: 29628311 states: 
>PALI1/2 potentially link polycombs with transcriptional co-repressors...PALI1 and PALI2 are defined by their CTBP binding domains and a PALI interaction with PRC2 (PIP) domain.... LCOR, a widely expressed transcriptional co-repressor, is known to associate with CTBP proteins and nuclear receptors via conserved N-terminal domains. ...... PALI2 and LCORL do not share the nuclear receptor binding box present in PALI1 and LCOR, whereas PALI2 has three predicted adenine-thymidine rich (AT) hooks in its C terminus, which could confer the ability to bind to DNA (Figure 3E).

In PMID:12535528 the authors were unable to demonstrate DNA binding of LCOR to a promoter which it regulated the expression of: 
Moreover, GAL4-LCoR fusion repressed the activity of the 5 × 17-mer-tk promoter in a dose-dependent manner by 4-fold (Figure 5J), whereas free LCoR had no effect on the 5 × 17-mer-tk promoter (data not shown)

Best

Ruth

@colinlog

**Comment by mlacencio** [comment]
@RLovering and @pgaudet ,

Removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
