### ISSUE TITLE
InterPro2GO: Dynein 1 light intermediate chain (IPR008467)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3165]
Dynein 1 light intermediate chain (IPR008467)

This isn’t a (catalytic) heavy chain, so I think the current “microtubule motor activity (GO:0003777)” term should be removed.

@hattrill

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for highlighting this. I have removed the term.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
