### ISSUE TITLE
Q6ZN28 | MACC1 Not dbTF change to coTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3168]
Dear Marcio

we have spent over 50 min looking at the literature describing MACC1. The paper you curated does have EMSA evidence of DNA binding however this was performed with nuclear extracts. The problem with nuclear extracts is that these will be identifying transcription complexes. Thus nuclear extract EMSAs and ChIP data both cannot be used to confirm DNA binding unless the protein does have a well recognised DNA binding domain.

We looked at a lot of papers and none that we looked at confirmed DNA binding although many show it in the nucleus, associated with promoters and regulating transcription.

We would therefore like you to remove the DNA binding annotation below and change the dbTF annotation to  GO:0003713 transcription coactivator activity.

DELETE: NTNU | Q6ZN28 | MACC1 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19098908 |   |   | has_input(NCBI_Gene:4233) 

Change to GO:0003713 NTNU | Q6ZN28 | MACC1 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:19098908 |   |   | has_input(NCBI_Gene:4233) 

Thanks

Ruth

@colinlog @pgaudet

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet ,

Annotations removed.

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
