### ISSUE TITLE
O96028 NSD2 NOT DNA binding transcription factor

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3169]
Hi @mlacencio 

O96028 NSD2 is NOT a DNA binding transcription factor, its a histone-lysine N-methyltransferase NSD2 (could be annotated as a cofactor. 

Moreover, this NTNU ISM annotation is supported by IPR009071, HMG box, which is NOT found in the entry, and NOT associated with any GO terms. Please remove the annotation to  GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific. 

Thanks, Pascale

**Comment by mlacencio** [comment]
@pgaudet and @RLovering ,

Removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
