### ISSUE TITLE
host cell nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3170]
InterPro is suddenly mapping many terms to "host cell nucleus" which is incorrect for anything which isn't a pathogen.

IPR004367
IPR007218
IPR001138
IPR001083
IPR024931
IPR019809
IPR000232
 IPR043198

**Comment by mah11** [comment]
> incorrect for anything which isn't a ~pathogen~ symbiont.

FIFY

i.e. "host" not restricted to pathogens

**Comment by pgaudet** [comment]
thanks for the precision @mah11

**Comment by sarach06** [comment]
Hi!
Thank you very much for highlighting this. I have checked and removed the term from the entries. The changes will be available in the next InterPro release (81.0).
Best regards,
Sara
