### ISSUE TITLE
Q9UQ80 | PA2G4  not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3173]
Hi

please would you change the annotation:

MGI | Q9UQ80 | PA2G4 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15073182

to  GO:0003714 transcription corepressor activity

Also remove this annotation:
MGI | Q9UQ80 | PA2G4 | enables | GO:0003677 | DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15073182

There is no evidence of sequence specific DNA binding in the experiments shown in this paper, the DNA cellulose expt is just demonstrates that it binds nucleic acids. The promoter binding is only shown with nuclear extracts, not with the recombinant proteins. There is a putative DNA binding domain however this is not a domain that is 'always' associated with dbTFs. The evidence here that the recombinant protein does not bind the promoter suggests that this protein is acting as a coTF at this locus.

Thanks

Ruth

**Comment by hdrabkin** [comment]
done

**Comment by RLovering** [comment]
thanks Ruth
