### ISSUE TITLE
Q9BVI0 | PHF20 not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3174]
Hi Marcio

Please remove this annotation. InterPro:IPR000637 is not a domain present in PHF20, and furthermore InterPro:IPR000637
does not support the association of dbTF activity with any protein.

NTNU | Q9BVI0 | PHF20 |   | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000255(ISM) | ECO:0000255 | (ISM) |   | PMID:19274049 |   | InterPro:IPR000637

I will create another ticket explaining how the NTNU ISM annotations need to all be reviewed and revised due to the high number of errors that are associated with these annotations.

Thanks

Ruth

**Comment by mlacencio** [comment]
@RLovering and @pgaudet ,

This annotation has been removed as well as all annotations derived from Vaquerizas.

Best,

Marcio

**Comment by pgaudet** [comment]
Great !
