### ISSUE TITLE
Review NTNU annotation to TOX2

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3176]
Hi @mlacencio 
PMID:25352127 uses nuclear extracts, hence does not show direct DNA binding. 

Fig 4C shows GO:0045944 positive regulation of transcription by RNA polymerase II and 4D shows GO:0003713
    transcription coactivator activity. Please edit annotations accordingly. 

ALSO, please remove the ISM from InterPro:IPR009071 - this domain does not have any MF (or any GO mappings).

Thanks, Pascale and @colinlog

**Comment by mlacencio** [comment]
Dear @pgaudet  and @RLovering ,

DbTF activity annotation removed and new coTF annotation created.

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
