### ISSUE TITLE
Remove ISM annotation to Q8IYH5 ZZZ3

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3177]
Hi @mlacencio 

Q8IYH5 ZZZ3 is annotated to GO:0003700 | DNA-binding transcription factor activity based on InterPro:IPR001005|InterPro:IPR009057

Neither domain has GO mappings. Please remove. 

Thanks, Pascale

**Comment by mlacencio** [comment]
Dear @pgaudet ,

Removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks!
