### ISSUE TITLE
MGI:2684058 Q6SJ95 | Tbpl2 not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3178]
Hi

this is not a dbTF. There is good review of the role of this protein which provides good evidence that this is a general transcription factor PMID: 21711503.

The paper annotated overexpresses (5-10 fold over) the protein and this can cause problems in the formation of a complex which is then unable to undertake its normal activities. In the introduction the authors discuss the role of the the protein as a GTF supported by references 23-27. Consequently, we would like you to remove these 2 annotations. Pascale has painted this family and so these will soon have the GTF MF and Trancription BP annotations

MGI | Q6SJ95 | Tbpl2 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:17109819

MGI | Q6SJ95 | Tbpl2 | acts_upstream_of_or_within | GO:0045892 | negative regulation of transcription, DNA-templated | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:17109819

Thanks

Ruth

**Comment by hdrabkin** [comment]
done

**Comment by RLovering** [comment]
great thanks Ruth
