### ISSUE TITLE
Nucleoside-triphosphatase, THEP1 type (IPR004948)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3179]
Description says "This entry represents a family of nucleoside-triphosphatases..."
and has EC xref to 3.6.1.5 (Nucleoside-triphosphate phosphatase)

But associated GO term is "nucleotide phosphatase activity, acting on free nucleotides (GO:0098519)"

This should be changed to "nucleoside-triphosphatase activity (GO:0017111)" (that also has xref of EC:3.6.1.15)

@hattrill 

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by sarach06** [comment]
Hi!
Thank you for this, I have changed the term. The changes will be available in the next InterPro release (81.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
