### ISSUE TITLE
Add GPAD and GPI example lines to documentation

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#3180]
@cmungall suggested that it may be useful to have a dozen or so example lines of GPAD and GPI in the spec.

A little chicken-and-egg at the moment, but maybe we could use WB or MGI import files for the first part? I'm not sure there is any *real* GPI 2.0 anywhere...

Tagging @vanaukenk @ukemi

**Comment by ukemi** [comment]
Here are some fake ones that are in a requirements doc that I made for @loricorbani. We should have real files available for testing in a short while. 


**GPAD 1.1**
MGI	MGI:1918911	enables	GO:0003674	MGI:MGI:2156816|GO_REF:0000015	ECO:0000307			20100209	MGI		
**GPAD 2.0**
MGI:MGI:1918911		enables	GO:0003674	MGI:MGI:2156816|GO_REF:0000015	ECO:0000307			2010-02-09	MGI		

**GPAD 1.1**
MGI	MGI:99607	NOT|acts_upstream_of_or_within	GO:0071403	MGI:MGI:3047008|PMID:15210959	ECO:0000315			20091209	BHF-UCL		
**GPAD 2.0**
MGI:MGI:99607	NOT	acts_upstream_of_or_within	GO:0071403	MGI:MGI:3047008|PMID:15210959	ECO:0000315			2009-12-09	BHF-UCL		

**GPI 1.2**
MGI	MGI:87871	Acat2	acetyl-Coenzyme A acetyltransferase 2	Tcp-1x|Tcp1-rs1	gene	taxon:10090		UniProtKB:Q8CAY6	
**GPI 2.0**
MGI:MGI:87871	Acat2	acetyl-Coenzyme A acetyltransferase 2	Tcp-1x|Tcp1-rs1	gene	NCBITaxon:10090				UniProtKB:Q8CAY6	

**GPI 1.2:**
MGI	MGI:87885	Chrna1	cholinergic receptor, nicotinic, alpha polypeptide 1 (muscle)	Achr-1|Acra	gene	taxon:10090		UniProtKB:P04756	
**GPI2.0:**
MGI:MGI:87885	Chrna1	cholinergic receptor, nicotinic, alpha polypeptide 1 (muscle)	Achr-1|Acra	SO:0000704	NCBITaxon:10090				UniProtKB:P04756

**Comment by vanaukenk** [comment]
Here is a spreadsheet in the GO's Google drive with some real world examples from WB (and coming soon from MGI, too).
I'd encourage other groups to add examples, as well:

https://docs.google.com/spreadsheets/d/1Dyd0k3jWIwM2LRMAxAT-WV8q1Pz5BU--IgH4EUPTMUg

**Comment by pgaudet** [comment]
Is this part of a project ?

**Comment by ValWood** [comment]
assigning to @kltm  please reassign or close as appropriate

**Comment by kltm** [comment]
A good place to start with documentation would be @suzialeksander and @pgaudet .

**Comment by suzialeksander** [comment]
we don't have a dozen, but we have a few in the docs and more can be added when we have real lines. closing as this is mostly done.
