### ISSUE TITLE
New ATPase GO terms for InterPro entries?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3181]
Hi,

From looking at the descriptions and doing a thorough review of the relevant Drosophila proteins (a rather narrow view, I realise), I think adding the following InterPro2GO associations would be accurate and helpful. (Would certainly fill a few gaps in the Drosophila annotations, at least).

But you may know of reasons why they can't be added....   Could you take a look when you have chance?

**IPR002464:DNA/RNA helicase, ATP-dependent, DEAH-box type, conserved site**
Add GO:0004386 helicase activity

**IPR041677:DNA2/NAM7 helicase, AAA domain**
Add GO:0004386 helicase activity

**IPR014014:RNA helicase, DEAD-box type, Q motif**
Add GO:0004386 helicase activity or maybe GO:0003724 RNA helicase activity

**IPR003959:ATPase, AAA-type, core**
Add GO:0016887 ATPase activity

**IPR003960:ATPase, AAA-type, conserved site**
Add GO:0016887 ATPase activity

@hattrill 

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by EBI-Hsinyu** [comment]
Hi, 
I have added the following GO terms as you suggested. 

IPR041677:DNA2/NAM7 helicase, AAA domain
Add GO:0004386 helicase activity

IPR014014:RNA helicase, DEAD-box type, Q motif
Add GO:0004386 helicase activity

IPR003959:ATPase, AAA-type, core
Add GO:0016887 ATPase activity

IPR003960:ATPase, AAA-type, conserved site
Add GO:0016887 ATPase activity

However, I couldn't add the GO term to IPR002464 as it hits proteins that are not included in the helicase superfamily. 

Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
Thanks Hsin-Yu - this looks good.
