### ISSUE TITLE
IPR006612 THAP-type zinc finger - MF unknown

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3182]
Hello, 

For most THAP-type zinc fingers, the MF is unknown (although some are transcription factors). Can you please remove the mapping to nucleic acid binding (GO:0003676) ? 

Thanks, Pascale & @RLovering

**Comment by EBI-Hsinyu** [comment]
Hi Pascale, 
Thank you for this. I have removed this term. 
Hsin-Yu

**Comment by RLovering** [comment]
thank you so much
Ruth
