### ISSUE TITLE
review propagations for PTHR46769:SF4

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#3183]
Hi,

Today, I discovered that the annotations to Pkhd1l1 from **Follit et al. 2014. Arf4 is required for Mammalian   development but dispensable for ciliary assembly. (PMID:24586199)** should have been made for Pkhd1. I have corrected this, but this means I have deleted what looks like it may have been the source for the annotation to "cilium" in the SF4 subfamily of PTHR46769 containing Pkhd1l1.

The paper (**Wu et al. 2019 | PKHD1L1 is a coat protein of hair-cell stereocilia and is required for normal hearing. (PMID:31444330)**  I have just annotated that Pkhd1l1 is located in the stereocilium tip. A new term is needed for the stereocilium coat.

The annotations of the SF4 subfamily will need to be corrected since Pkhd1l1 does not appear to be a cilium protein.

Thanks,

-Karen

**Comment by krchristie** [comment]
Here's the term request for the term needed to complete annotation of Pkhd1l1

[NTR: glycocalyx term for stereocilium](https://github.com/geneontology/go-ontology/issues/19780)

**Comment by pgaudet** [comment]
Thanks @krchristie I removed the annotation.
