### ISSUE TITLE
Dissociate GO term with InterPro Structure-specific endonuclease subunit Slx4

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#3184]
The IPR018574 signature is associated with GO term 5'-flap endonuclease activity (GO:0017108). Its description suggests that it is the regulatory subunit of the SLX1-SLX4 structure-specific endonuclease.
Can you please disassociate the molecular function term for this signature as the catalytic activity term seems misleading for these structural components. 

Similar isuue with IPR004579 ERCC1/RAD10/SWI10 family, as the members of this family are also non-catalytic components of a structure-specific DNA endonuclease complex.

@hattrill
@sjm41

**Comment by hattrill** [comment]
tagging InterPro group:
@EBI-Hsinyu 
@lsw26
 @sarach06 
@Alexbateman1 
@typhainepl

**Comment by sarach06** [comment]
Hi!
Thank you very much, I have removed the terms for those entries. The changes will be seen in the next InterPro release (81.0).
Best regards,
Sara

**Comment by sjm41** [comment]
This looks done - please reopen if I'm wrong!
