### ISSUE TITLE
InterPro2GO: Kinesin light chain (IPR002151)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3185]
Kinesin light chain (IPR002151)

This isn’t a (catalytic) heavy chain, so I think the current “microtubule motor activity (GO:0003777)” term should be removed.

@hattrill

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by sarach06** [comment]
Hi!
Thank you very much. I have removed the term.
Best
Sara

**Comment by sjm41** [comment]
Great, thanks!
