### ISSUE TITLE
Disassociate GO term for the protein components of the RNase P complex members

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#3186]
The following InterPro signatures correspond to the protein subunits of RNase P and/or RNase MRP Ribonucleoprotein complex. The RNA subunit is the catalytic unit but requires the protein subunits for its activity (PMID:11241345). These protein subunits contributes to the activity of the RNA subunit but have no catalytic ability on their own.

Can you please disassociate the catalytic molecular function terms for these signatures.

IPR002730:Ribonuclease P/MRP, subunit p29
IPR016848:Ribonuclease P/MRP, p29 subunit
IPR036980:Ribonuclease P/MRP, subunit p29 superfamily
IPR002759:Ribonuclease P/MRP protein subunit
IPR016819:Ribonuclease P/MRP protein subunit Pop5
IPR014612:Ribonucleases P/MRP protein subunit Rpp20                               
IPR002738:RNase P subunit p30

@hattrill
@sjm41

**Comment by sarach06** [comment]
Hi!
Thank you very much. I have removed the catalytic term from these entries and the changes will be available in the next InterPro release (84.0).
Best,
Sara

**Comment by phanivg** [comment]
Thank you Sara.
