### ISSUE TITLE
InterPro2GO: BRK domain (IPR006576)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3187]
The description for this is: "The function of this domain is unknown [1]. It is often found associated with helicases and transcription factors."

Yet it has an associated MF GO term of "hydrolase activity, acting on acid anhydrides (GO:0016817)".

I came across this because the domain is in D. melanogaster 'pps' (A0A0B4K6G3), and I can't see any evidence that this is a hydrolase.

Maybe remove that hydrolase term?

@hattrill

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by sarach06** [comment]
Hi,
Many thanks. I have removed the term.
Best,
Sara

**Comment by sjm41** [comment]
thanks Sara
