### ISSUE TITLE
Disassociate GO activity term for G-protein, gamma subunit

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#3188]
The InterPro signature IPR001770 represents the G protein gamma subunit and is associated with catalytic term GTPase activity (GO:0003924). From the description it is clear that it is the alpha subunit that binds with GTP/GDP and has the GTPase activity, while gamma subunit pairs with beta and regulates the signal.
Please remove the catalytic term on this gamma subunit.

similarly IPR039227 as well.

thanks

@hattrill
@sjm41

**Comment by hattrill** [comment]
Tagging InterPro:
@EBI-Hsinyu 
@lsw26 
@sarach06
 @Alexbateman1 
@typhainepl

**Comment by sarach06** [comment]
Hi!
Thank you very much for this. I have removed that term from the entries and added this MF one GO:0031681 (G-protein beta-subunit binding). Let me know if you agree.
Best,
Sara

**Comment by phanivg** [comment]
Hi Saara,
Happy wit the fix.
Thank you,
Phani
