### ISSUE TITLE
InterPro2GO: Ku, C-terminal (IPR014893)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3190]
The description for this is suggests the domain is specific to Ku proteins, and that it represents a binding domain.

If it is a binding domain, I don't think the MF term "hydrolase activity, acting on acid anhydrides (GO:0016817)" is appropriate.

Moreover, I also see the domain in non-Ku proteins, including D. melanogaster EndoGI (Q9V3V9).

Maybe remove that hydrolase term?

@hattrill

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by sarach06** [comment]
Hi, 
Thank you very much. I have removed the term.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
