### ISSUE TITLE
CoA pyrophosphatase activity (GO:0010945) annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3192]
I think the following annotations should change to use:
CoA pyrophosphatase activity (GO:0010945)
(also see [#19787](https://github.com/geneontology/go-ontology/issues/19787))

**Human NUDT19:	
acyl-CoA hydrolase activity	TAS	Reactome:R-HSA-6810474**
- already changed by Bijay at Reactome

**Human NUDT7:		
CoA hydrolase activity	TAS	Reactome:R-HSA-6809354**
- already changed by Bijay at Reactome

**Mouse Nudt7 (Q99P30):
acetyl-CoA hydrolase activity	IDA	PMID:11415433**
- @hdrabkin , can you take a look?

**Worm ndx-8(Q9NA25):
acetyl-CoA hydrolase activity	IDA	PMID:11943069
CoA hydrolase activity	IDA	PMID:11943069**
- @vanaukenk , can you take a look?

**Yeast PCD1 (Q12524):
pyrophosphatase activity	IDA	PMID:10922370**
- @srengel , can you take a look?

**Comment by sjm41** [comment]
@hdrabkin @vanaukenk @srengel 
Would you mind taking a look at the annotations above and see if you agree with my suggested edit? Thanks.

**Comment by hdrabkin** [comment]
Based on the reaction products in paper vs def of GO:0010945 vs def of acetyl-CoA hydrolase activity (which is  EC 3.1.2.1), I agree; done

**Comment by srengel** [comment]
did the yeast one just now in P2GO.  thanks @sjm41 .

**Comment by vanaukenk** [comment]
Now done.  @sjm41 - sorry for the delay.
