### ISSUE TITLE
InterPro2GO: Nucleoside diphosphate-linked moiety X motif 19 (IPR039121)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3193]
Hi

I think you can add the MF "CoA pyrophosphatase activity (GO:0010945)" to this entry.

Also see:
https://github.com/geneontology/go-ontology/issues/19787
https://github.com/geneontology/go-annotation/issues/3192

@hattrill

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 
Thank you for the suggestion. This entry contains 1538 eukaryotic NUDT19-like proteins and 8603 uncharacterised bacterial proteins. Most of them have the NUDIX hydrolase domain. To be on the safe side, I will give this entry the more general GO term "GO:0016787 — hydrolase activity'. 

Regards, 
Hsin-Yu

**Comment by sjm41** [comment]
OK, understood!

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you so much for you suggestion. I agree in this intermediate solution. I updated the GO term. The changes will be available in InterPro 94.0.

Best,

Beatriz

**Comment by sjm41** [comment]
Great, thanks Beatriz!
