### ISSUE TITLE
	O94235 NOTGO:0004708 | MAP kinase kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3195]
from  EC assignment/mapping
GO:0004708 | MAP kinase kinase activity | IEA with 2.7.12.2 | GO_REF:0000003

**Comment by sylvainpoux** [comment]
Hi Val,

corrected. The EC number was incorrect EC 2.7.12.2 -> 2.7.12.1

Thanks

Sylvain

**Comment by cmungall** [comment]
Thanks @sylvainpoux!
