### ISSUE TITLE
InterPro2GO: ATP-dependent RNA helicase YTHDC2-related (IPR031083)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3196]
Add "GO:0003724 | RNA helicase activity" to "ATP-dependent RNA helicase YTHDC2-related" (IPR031083)?

@hattrill 

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by sarach06** [comment]
Hi Steven,
I have added that term to the entry. Thank you very much!
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
