### ISSUE TITLE
PANTHER:PTN000805648 propagation to Traf4

### ISSUE THREAD

**Issue by gantonazzo** [geneontology/go-annotation#3198]
Could you block the propagation of PANTHER:PTN000805648 to FBgn0026319 (Traf4)?
While in other models Traf4 orthologs have a role in the TNF signalling pathway, in Dmel it has been shown that the gene is not involved (only Traf6 seems to be involved).

**Comment by sjm41** [comment]
PTN000805648 also adds 'ubiquitin-protein transferase activity' to fly Traf4, Traf-like and all human TRAFs (including TRAF4) (as part of TNF RECEPTOR ASSOCIATED FACTOR (PTHR10131)), but these do not have this activity (e.g. https://www.uniprot.org/uniprot/Q9BUZ4)

- Source annotations for this are:
(HUMAN|HGNC=12032|UniProtKB=Q12933) = TRAF2
(HUMAN|HGNC=12036|UniProtKB=Q9Y4K3) = TRAF6
(MOUSE|MGI=MGI=108072|UniProtKB=P70196) = Traf6
=> these annotations look good, so maybe PANTHER family needs splitting to represent functions of different TRAFs?

**Comment by marcfeuermann** [comment]
Family has been updated.

**Comment by hattrill** [comment]
Looks like the annotation to D.mel Traf-like is back: http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0030748

Could you block this please.

**Comment by marcfeuermann** [comment]
This family is a nightmare ! In fact it has been corrected for other drosophila members but this one escaped to my attention. Also blocked.
