### ISSUE TITLE
IPR031267 please change coTF to dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3201]
Hi

please would you change the GO ID associated with IPR031267 from transcription coactivator activity (GO:0003713) to DNA-binding transcription factor activity, the record for IPR031267 states that the domain binds DNA

either use  GO:0003700 DNA-binding transcription factor activity or preferably  GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific - if you think this is appropriate

Thanks

Ruth

**Comment by sarach06** [comment]
Hi Ruth,
Thank you very much. I have changed the term and added GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific.
Best regards,
Sara

**Comment by RLovering** [comment]
thanks this is very helpful
Ruth
