### ISSUE TITLE
InterPro2GO: PPM-type phosphatase domain (IPR001932)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3202]
Hi,

From the description and proteins with the domain (that I've looked at), it seems the current GO term of "catalytic activity" could be changed to the more specific "phosphatase activity (GO:0016791)".
Do you mind checking?

@EBI-Hsinyu
@lsw26
@sarach06
 @Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much, I have changed the term to 'Phosphatase activity'.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
