### ISSUE TITLE
InterPro2GO - Thiolase-like (IPR016039)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3203]
Hi,

From the description and EC xrefs, it seems the current GO term of "catalytic activity" could be changed to the more specific "transferase activity, transferring acyl groups (GO:0016746)".
Do you mind checking?

@EBI-Hsinyu
@lsw26
@sarach06
 @Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi!
Thank you very much, I have changed the term for the more specific one.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
