### ISSUE TITLE
InterPro2GO - HRDC-like superfamily (IPR010997)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3204]
Hi,

I think the associated GO term of "catalytic activity" should be removed here.
As the description says, the signature is found in RNA polymerase subunit RBP4, but that subunit is not part of the catalytic core (and the specific domain entries for RBP4 lack a catalytic GO term association - see IPR006590,  IPR005574, IPR038846, IPR038324). It's not mentioned in the description, but the same is true of RNApol subunit RPC17.

@EBI-Hsinyu
@lsw26
@sarach06
 @Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi!
Yes, you are right. I have removed the term. Thank you very much.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
