### ISSUE TITLE
InterPro2GO: AMP-dependent synthetase/ligase (IPR000873)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3205]
Hi,

I think the associated GO term of "catalytic activity" should be removed here.
One of it's children is "Dip2-like domain (IPR037337)", which lacks any catalytic GO term and whose description says "Dip2 proteins show sequence similarity to other members of the adenylate forming enzyme family...however, its function may have diverged from other members of the superfamily. " And I don't see any evidence for catatlytic activity amongst DIP2 orthologs.

@EBI-Hsinyu
@lsw26
@sarach06
 @Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi!
Thank you very much, I have removed the term from the entry.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
