### ISSUE TITLE
InterPro2GO: Alpha amylase (IPR006046)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3206]
Hi,

From the description and proteins with the domain (that I've looked at), it seems the current GO term of "catalytic activity" could be changed to the more specific "alpha-amylase activity (GO:0004556)".
Do you mind checking?

@EBI-Hsinyu
@lsw26
@sarach06
 @Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have changed the term for alpha-amylase activity.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks again!
