### ISSUE TITLE
PROTEIN KINTOUN (PTHR22997:SF3) 

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#3210]
Mouse Dnaaf2 (MGI:1923566, UniProtKB:Q8BPI1) is in the Panther family PROTEIN KINTOUN (PTHR22997:SF3).

It has an IBA to the term `cilium-dependent cell motility` (with PTN001123556). This is too narrow. Dnaaf2 is also required for `epithelial cilium movement involved in extracellular fluid movement (GO:0003351)`. Seems that the appropriate term would be the mutual parent term for `cilium movement (GO:0003341)`.

Thanks,

-Karen

**Comment by pgaudet** [comment]
I can only propagate GO:0001539     cilium or flagellum-dependent cell motility from available terms; is this OK ?

**Comment by pgaudet** [comment]
Please reopen if this is not correct.

**Comment by krchristie** [comment]
I should have been clearer. I have just added the annotation to `epithelial cilium movement involved in extracellular fluid movement (GO:0003351)` for Dnaaf2. So, I have reopened this so that once the new annotation propagates through to PAINT, you can look at this again.

**Comment by marcfeuermann** [comment]
Term is now in PAINT.
