### ISSUE TITLE
gpi spec: consider allowing specific subtypes for proteins to distinguish polyproteins from functional products

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#3212]
For proteins there is a single type allowed:
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#gpi-entity-types

Do we also need to distinguish

 1. Reference from isoform?
 2. different stages of post-processing

I think for 1 it's sufficient to use the parent/encoded by field

One of the drivers for 2 is viral genomes, e.g sars-cov-2. Do we want to distinguish between the polyprotein and the cleavage products (what uniprot calls mat_peptide)? Do we even want to allow the polyprotein in annotation (we definitely want to include it as a referenceable entity, e.g. the input for the protease)?

polyproteins are an issue in human too, what are we currently doing for POMC?

**Comment by ValWood** [comment]
@cmungall Please reassign as appropriate

**Comment by pgaudet** [comment]
Outdated
