### ISSUE TITLE
PTN001191880  SH3 AND MULTIPLE ANKYRIN REPEAT DOMAINS PROTEIN (PTHR24135)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3213]
PTN001191880 has a lot of process terms associated with it.
I think that this should be reviewed as some seem somewhat redundant and some are just supported by one annotation.
![Screenshot 2020-08-05 at 16 56 55](https://user-images.githubusercontent.com/11865746/89435402-b69d6780-d73c-11ea-9989-d8d1d072d4a9.png)

**Comment by ValWood** [comment]
Definitely remove all. This family is in yeast!

**Comment by marcfeuermann** [comment]
Annotation has been cleaned.
