### ISSUE TITLE
carboxypeptidase Y and phytochelatin biosynthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3214]
cpy1	vacuolar carboxypeptidase Y		phytochelatin biosynthetic process		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000928060
SGD:S000000343
SGD:S000004912	serine protease family s10 serine carboxypeptidase pthr11802	protein		PMID:21873635	20170228

I have not come across this, it looked odd.

At SGD  the annotations come from a single publication:
Reference: Wünschmann J, et al. (2007) Phytochelatins are synthesized by two vacuolar serine carboxypeptidases in Saccharomyces cerevisiae. FEBS Lett 581(8):1681-7

Phytochelatins (PCs) are cysteine-rich peptides that chelate heavy metal ions, thereby mediating heavy metal tolerance in plants, fission yeast, and Caenorhabditis elegans. They are synthesized from glutathione by PC synthase, a specific dipeptidyltransferase. While Saccharomyces cerevisiae synthesizes PCs upon exposure to heavy metal ions, the S. cerevisiae genome does not encode a PC synthase homologue. How PCs are synthesized in yeast is unclear. This study shows that the vacuolar serine carboxypeptidases CPY and CPC are responsible for PC synthesis in yeast. The finding of a PCS-like activity of these enzymes in vivo discloses another route for PC biosynthesis in eukaryotes.
PMID: 17408619

I don't think this ap[plies in species that have phytochelatin synthase?
So probably it should not be transferred beyond budding yeast. I did not dig any deeper.....

**Comment by marcfeuermann** [comment]
This is a huge family with surprisingly only few primary annotations. I've removed the propagation.
