### ISSUE TITLE
Create biolink modeling language definition for GPI 2.0

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#3215]
Create biolink modeling language definition for GPI 2.0. This would server two initial purposes: 1) as a supporting definition for the format, helping with documentation, etc., and 2) as a roadmap for alignment and future conversation with BGI or other future files.

A start has been made here for a biolinkml definition of GPI here: https://github.com/geneontology/go-annotation/pull/3209

Also see: <small><strike>https://github.com/biolink/biolink-model</strike></small> https://github.com/biolink/biolinkml (thanks @deepakunni3)

Tagging @cmungall @deepakunni3 @sierramoxon @vanaukenk @ukemi @sabrinatoro @goodb 
Please feel free to tag on others for this conversation.

**Comment by deepakunni3** [comment]
And the repo for biolink modeling language: https://github.com/biolink/biolinkml

**Comment by ValWood** [comment]
Should this migrate top the BioLink tracker?

**Comment by kltm** [comment]
@ValWood Probably not, I'm guessing. I believe this has rather moved on and I'm not sure this is worth keeping. @sierra-moxon , do you have any thoughts here?

**Comment by kltm** [comment]
I think we can open this up again if it comes up.
