### ISSUE TITLE
PANTHER:PTN000352745 - human TAB1 actually a pseudophosphatase?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#3216]
Hi @marcfeuermann 

In working on a GO-CAM model for the NF-kB signaling module, I'm trying to describe the MF of human TAB1.

Although there are IBA annotations to protein phosphatase MF terms, it looks like human TAB1 may actually be a pseudophosphatase:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1615897/

Can you take a look at this paper to see if you agree and if so, revise the IBA annotations?

Thanks.

**Comment by marcfeuermann** [comment]
Hi Kimberley,
You are right, TAB1 is indeed a pseudophosphatase and annotated as such in UniProt. The PAINT annotation was propagated over several duplication events. I've blocked any phosphatase-related terms for the TAB1 node, PTN002675954.
Thank you for pointing this out.
Stay safe.
Best regards,
Marc.

**Comment by vanaukenk** [comment]
Thanks very much @marcfeuermann !
