### ISSUE TITLE
Remove mapping to dbTF from tfclass 0.4.1

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3217]
Hi @mlacencio 

We are reviewing the last proteins with discrepancies and we would like to remove tfclass 0.4.1 from the list of dbTFs  (https://docs.google.com/spreadsheets/d/1lIvPoAtHPWuDDlhGqidEngWDQPhNbitFT-8K6dEOo_0/edit#gid=0)

This tf class contains 3 proteins: 

ZNFX1 | Q9P2E3
NFX1 | Q12986
NFXL1 | Q6ZNB6

However ZNFX1 is clearly not a dbTF, so this creates a false positive. Also, ZNFX1 falls in a different Panther family (PTHR10887) compared to NFX1 and NFXL1 (PTHR12360). Can you please remove it ? 

Thanks, Pascale

**Comment by mlacencio** [comment]
Hi @pgaudet !

Done!

Best,

Marcio

**Comment by pgaudet** [comment]
Q12986
Q6ZNB6

are not deleted in P2GO - disputed there as well. 

Thanks, Pascale

**Comment by mlacencio** [comment]
Hi @pgaudet !

Removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Thanks !
