### ISSUE TITLE
ARBA:ARBA00002004 annotation incorrect

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3218]
Hello @sylvainpoux @pedruzzi 

I just came accross ARBA:ARBA00002004 in the F1M8G0 entry 
It says 
> If a protein meets these conditions... i
Common conditions
       Matches InterPro signature IPR021980
        Matches InterPro signature IPR039775
        taxon = Eukaryota
... then these annotations are applied i
Function:     May play a role in transcription regulation.

1. I think the evidence for the transcription factor role based on those domains is weak. 
2. More importantly, this applies a KW 'DNA binding', which I think should be removed. 

Please let me know if I should contact someone else for those ARBA annotations. 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,

ARBA generates automatic annotation, and here the problem doesn't come from the rule but from the original paper that defines this domain as atypical homeodomain. There are few papers for this family but found this one:

RX PubMed=12604659; DOI=10.1095/biolreprod.102.009787
RA Oyhenart J., Le Goffic R., Samson M., Jegou B., Raich N.
RT Phtf1 is an integral membrane protein localized in an endoplasmic reticulum domain in maturing male germ cells.
RL journal article: Biol. Reprod. 68:1044-1053 (2003)

As these proteins contain transmembrane domains, I think they are right. I will recurate this family.

Thanks for pointing this out

Sylvain

**Comment by pgaudet** [comment]
Thanks !
