### ISSUE TITLE
Drosophila shn is a dbTF not a coTF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3220]
Hi @hattrill 

Fly shn is annotated to 
-  GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific

as well as 
-  GO:0003714 transcription corepressor activity
and 
- GO:0003713 transcription coactivator activity

However it seems to bind DNA directly, so I think the co-factor annotations should be replaced by GO:0000981

Thanks, Pascale

**Comment by hattrill** [comment]
shn in BMP signaling is a bit of a question mark. It joins the Mad/Med transcription factor complex and acts as a modifier - it may or may not act to bind the DNA specifically in this complex. I am inclined to keep this.

**Comment by pgaudet** [comment]
ok, thanks !
