### ISSUE TITLE
IPR033056 please change associated Transcription term

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3222]
Hi

please would you change the GO term: transcription by RNA polymerase II (GO:0006366) currently associated with the IPR033056 record to  GO:0006357 regulation of transcription by RNA polymerase II as the POU6F2 family are DNA-binding transcription factors and should be annotated as regulating transcription rather than being part of the transcription process.

as this record includes the RNA pol II specific process already, it would also (not not essential) to also change the MF term from DNA-binding transcription factor activity (GO:0003700) to  GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific

Thanks

Ruth

@EBI-Hsinyu @sarach06 @pgaudet

**Comment by EBI-Hsinyu** [comment]
Hi Ruth, 
Thank you for this. I have changed the terms you recommanded. 

Regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks ! 
@RLovering I marked as DONE in the spreadsheet.
