### ISSUE TITLE
Lysine--tRNA ligase human

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3224]
This has many annotations to

https://www.uniprot.org/uniprot/Q15046#function
"Human lysyl-tRNA synthetase is secreted to trigger proinflammatory response."

activation of MAPK activity Source: CAFA
looks like a readout for the immune response but is transferred by PAINT
(the paper looks ver over annotated)

**Comment by pgaudet** [comment]
https://europepmc.org/article/MED/15851690

**Comment by ValWood** [comment]
I'm not sure who to assign this one to?

**Comment by pgaudet** [comment]
@pgarmiri

**Comment by pgarmiri** [comment]
Hi @ValWood ,

I had a look at the paper and at the annotations for KARS1. This is a moonlighting  protein.
From the UniProt function comment : 'When secreted, acts as a signaling molecule that induces immune response through the activation of monocyte/macrophages '

The authors found that KARS1 secretion was induced by TNF-alpha. The secreted KRS bound to macrophages and peripheral blood mononuclear cells to enhance the TNF-alpha production and their migration.( Figures 1 and 3)

 It is signaling molecule that activates immune cells and through specific signal mediators (ERK, p38 MAPK, and Gαi).  This was validated in figure 5 by detection of their phosphorylation with their phosphospecific antibodies. They also used inhibitors to the above (and more) mediators and determined the KRS-dependent TNF production (D) and MMP-9 production (E) and cell migration (F).

To me, this doesn't seem to be a readout but rather the mechanism/pathway that the signalling occurs and we see the activation of the immune cells.

I have done some changes though.

-   I changed the annotation below:

GO:1905050 | 'positive regulation of metallopeptidase activity' that was a readout for 

 GO:1905523 | 'positive regulation of macrophage migration'

- I also deleted the annotation to 'negative regulation of cell population proliferation' as this was part of the experiments to investigate the involvement of the KARS1 in activating macrophages.

How do these changes look to you?

Thanks,

Penelope

**Comment by ValWood** [comment]
Well this is a bit outside of my area of expertise. However,

To identify secretable ARSs, we cloned the cDNAs encoding 17 different human ARSs in a mammalian expression vector and transfected them into HEK293 cells. Among them, 11 ARSs that were well expressed have been used for the secretion tests. The cells transfected with each ARS were cultivated, and the culture media were collected without disrupting the cell membranes. Among the tested ARSs, full-size KRS and AlaRS were observed in the culture media, whereas no tubulin was leaked to the culture media (Fig. 1A). Because the secretion of KRS was apparent, we further investigated its secretion in more detail. We then expressed Myc-KRS in HEK293 cells and collected the culture medium at time intervals.

raises red flags. These tRNA synthases have a mitochondrial signal sequence. The is cleaved to activate the cytosolic version. One could imagine that over-expressing a tRNA synthase could result in these some being secreted. It seems possible that this is an autoimmune response, which could be potentially induced by a virus (many viris's use host tRNAsynthases , and package them)  ...and there is evidence for the involvement of tRNA synthases   in auto-immune conditions). Pathogen tRNA synthases also seem to induce an immune response.

There  is good evidence that tRNA's act otherwise as signalling molecules:
It was recently reported that cLysRS is released form MARS after MAPK-dependent phosphorylation in activated mast cells and is translocated into the nucleus
where it activates transcription factor MITF in an Ap4Adependent
manner.

However 'moonlighting activity' reported here is picked up and reported by reviews so I guess it is reasonable to annotate it. but probably shouldn't be PAINTED unless there is more support from different experiments and papers.

This still seems to be an over-annotation from this paper. Most of these experiments are just different assays to demonstrate:

GO:0002863    positive regulation of inflammatory response to antigenic stimulus occurs_in macrophage (although this seems to overlap with "macrophage activation" so maybe that is also needed).

The existing annotations are mainly the components of this response,  (the readouts commonly used to indicate immune response activation). So I would not annotate directly to the MAP kinase pathway components,  the activities which comprise the downstream signalling  (although it would be helpful if there was better guidance for this).


CAFA | Q15046 | KARS1 |   | GO:0000187 | activation of MAPK activity

CAFA | Q15046 | KARS1 |   | GO:0002720 | positive regulation of cytokine production involved in immune response

CAFA | Q15046 | KARS1 |   | GO:0010759 | positive regulation of macrophage chemotaxis | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15851690

CAFA | Q15046 | KARS1 |   | GO:0033209 | tumor necrosis factor-mediated signaling pathway | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15851690 |   |   |   |   |   |   |   |  

 CAFA | Q15046 | KARS1 |   | GO:0043032 | positive regulation of macrophage activation | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15851690 |   |   |   |   |   |   |   |  
ECO:0000314 | (IDA)

 CAFA | Q15046 | KARS1 |   | GO:0070374 | positive regulation of ERK1 and ERK2 cascade | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15851690 |   |   |   |   |   |   |   |  
ECO:0000314 | (IDA)

 CAFA | Q15046 | KARS1 |   | GO:1900017 | positive regulation of cytokine production involved in inflammatory response | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15851690 |   |   |   |   |   |   |   |  

 CAFA | Q15046 | KARS1 |   | GO:1900745 | positive regulation of p38MAPK cascade | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15851690 |   |   |   |   |   |   |   |  

CAFA | Q15046 | KARS1 |   | GO:1905523 | positive regulation of macrophage migration


We need to move away from curating " all supporting assays" and  instead curate the  biological processes the gene product is directly involved in, and the activity it performs in this process.

A good tip is  what is the take-home message of the paper. Here
"Human lysyl-tRNA synthetase is secreted to trigger proinflammatory response."
**proinflammatory response** is the process that should be captured, plus any mechanistic detail or connections to the pathway (which are not available from this paper).

@pgaudet any thoughts on this? This kind of mirrors what we are seeing in the pathogen host branch for annotation of readouts (assays commonly used to indicate a particular process is activated) which seems to be proinflammatory response in this case?

**Comment by pgaudet** [comment]
While I agree the inflammatory role may be an artifact, the authors present this as one of the true roles. Of course we can always think of ways that experiments have been misinterpreted. 

That being said, we can remove from PAINT, especially if it's an unexpected function based on a single paper. 

A agree about removing annotations to all assays/readouts. 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi Both, 

I see the point of the argument, so I have used the term you suggested Val with the extension (GO:0002863 positive regulation of inflammatory response to antigenic stimulus occurs_in macrophage) and kept the| GO:0043032 | positive regulation of macrophage activation as well.

As the paper is about KARS1, I also deleted all annotations to 

   P47811 | Mapk14
  Q63844 | Mapk3
   P41245 | Mmp9

Would you agree with this approach? Or did I take it too far with the deletions?

Thanks,

Penelope

PS. Some guidelines would be useful as each curator has different expertise. Perhaps a table with assays commonly used to indicate a particular process is activated linked to the particular process that should be annotated. People can add to it as they come across them.  Just an idea :)

**Comment by ValWood** [comment]
This looks much better.
We definitely need better guidelines!

**Comment by pgaudet** [comment]
@marcfeuermann will have another look at the family.

**Comment by ValWood** [comment]
Should we close this one?
