### ISSUE TITLE
InterPro2GO for Furin-like cysteine-rich domain (IPR006211)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3226]
This entry has "transmembrane receptor protein tyrosine kinase activity (GO:0004714)".
I don't easily see the evidence for this - the description suggests the domain acts by "receptor aggregation" rather than having kinase activity itself.

Can you check that GO association is accurate? 

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi! 
Thank you very much for this. I have checked and agree with you that there is no evidence for this GO term association, so I removed it from this entry. I also removed the other terms from this domain. Let me know if you agree.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara. I only checked the two MF terms, which look like they both should be removed.  The BP terms might be OK from just reading the InterPro description, but I haven't checked the references or done any further research on those.

**Comment by sarach06** [comment]
The entry matches Furin-like domain-containing proteins that are not all protein kinases, so we prefer to delete these terms and try to add specific ones in case of domains. Anyway, those terms are included in family entries to cover the proteins matched and we don't lose them. Let me know if that's OK.

Best regards,
Sara

**Comment by sjm41** [comment]
Sounds fine. Thanks again!
