### ISSUE TITLE
Review annotations to GO:0008626 granzyme-mediated apoptotic signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3227]
Hello, 

"granzyme-mediated apoptotic signaling pathway (GO:0008626) -> @sylvainpoux suggested that it would be safe to change **apoptotic** to **cell death**, since we now know that many cell-death pathways are not related to apoptosis. In this paper, they at least show that granzyme A mediates pyroptosis and not apoptosis. As we don't know for other Granzymes, I think that best is to stay high level with cell death instead of pyroptosis. 

Most annotations should be replaced by GO:0140507 granzyme-mediated programmed cell death signaling pathway (just created, in https://github.com/geneontology/go-ontology/issues/19901)

Please fix annotations here:

https://docs.google.com/spreadsheets/d/1-NTDaHYXe_6cpLeNmOsrB3ebBHqWZYZQFJcewSXQoVk/edit#gid=0

2 MGI @hdrabkin 
2 UniProt @pgaudet 

Thanks, Pascale

**Comment by hdrabkin** [comment]
GO:0140507 not available yet (at least for us)

**Comment by hdrabkin** [comment]
MGI Done

**Comment by pgaudet** [comment]
Thanks, I fixed the UniProt annotations.
