### ISSUE TITLE
Review annotations to GO:0032800	receptor biosynthetic process and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3228]
Hello, 

The term GO:0032800 receptor biosynthetic process and its children will be obsoleted, see https://github.com/geneontology/go-ontology/issues/19900. 

There are 33 EXP annotations. Please review annotations: 
https://docs.google.com/spreadsheets/d/1M3i6xVL5yU_kc-AO8sX_4GY2V_PhqnbU96EUQ5jj6sg/edit#gid=0

Contributor   (Assigned by) | Number of annotations
-- | --
AgBase | 3
BHF projects | 26
MGI | 3
UniProt | 1

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi,

The UniProt  annotation has been revised. 

Thanks,

Penelope

**Comment by RLovering** [comment]
UCL annotations revised
thanks
Ruth

**Comment by pgaudet** [comment]
@hdrabkin Only the 3 MGI annotations remain - can you have a look ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
done but forgot to mark spreadsheet; sorry

**Comment by pgaudet** [comment]
Thanks everyone.
