### ISSUE TITLE
TSC22D1-D3 are these dbTFs?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3230]
Hi Colin

please could you comment on this family.

Q99576                TSC22D3 interpro still has this as dbTF although NTNU annotations have been removed https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000580/

Thanks

Ruth

**Comment by RLovering** [comment]
Email response from Colin Logie
TSC22D3 D1 and D2 are difficult.

I have now waited for more than 6 years for someone to publish the sequence-specificity of TSC22D3 (aka GILZ). This has not been forthcoming. Rather, it has been argued that it is a regulator of other transcription factors as well as of the RAF1 kinase and Ras together.


Ayroldi E, Zollo O, Bastianelli A, Marchetti C, Agostini M, Di Virgilio R, et al. GILZ mediates the antiproliferative activity of glucocorticoids by negative regulation of Ras signaling. J Clin Invest. (2007) 117:1605–15. doi: 10.1172/JCI30724

Furthermore, in 1997 the porcine protein was charcterized by NMR (PMID: 9388238) and the authors state: "DNA-binding capability, however, is not obvious from its sequence, because it lacks the basic region found in the original basic region/leucine zipper (bZIP) DNA-binding domains. "

I would like to move thhem to inhibitor of dbTF if anything, as there is literature for AP1 and NFKb inhibition. But dbTF is probably far-fetched, despite 100ds of glucocorticoid receptor reviews repeating that TSC22D3 is a transcription factor.... So are JNK, ERK and p38 kinases and those are also found on gene promoters! However, they are not dbTFs. I am afraid that TSC22D1-2-3-4 do not have the data with them.

Shall me make a github ticket for the TSC22D family, as we are going against much repeated (weak) knowledge by removing them from the list?

**Comment by RLovering** [comment]
Hi

our transcription factor review suggests that there is not strong evidence that this protein family are DNA binding transcription factors. We will not be including these on our dbTF list. Currently the InterPro record IPR000580 provides a mapping for this family to DNA-binding transcription factor activity (GO:0003700) and  Regulation of transcription, DNA-templated (GO:0006355).

so you may want to remove the GO:0003700 mapping, although there does seems to be support for the Regulation of transcription, DNA-templated (possibly this could be changed to a more specific term  GO:0006357 
regulation of transcription by RNA polymerase II - depending on whether the species with these proteins have RNA pol II.

There are actually 4 members of this family. TSC22D1-2-3-4. These are all in different PANTHER families and looking just at the protein sequence alignments there does not seem to be much conservation between them outside of the TSC-22 domain. 
There are currently no other Molecular function dbTF annotations associated with these 4 proteins other than the InterPro annotations.
TSC22D1 | TSC22 domain family member 1 |   | Q15714
TSC22D2 | TSC22 domain family member 2 |   | O75157
TSC22D3 | TSC22 domain family member 3 |   | Q99576
TSC22D4 | TSC22 domain family member 4 |   | Q9Y3Q8

Please confirm whether or not you will remove the MF annotation so that we can close this ticket

Best

Ruth

**Comment by sarach06** [comment]
Dear Ruth,
Thank you for highlighting this. I have removed the MF term and replaced the BP one by the more specific term you suggested. 

Best,
Sara

**Comment by RLovering** [comment]
That is great news,
thanks for all your help
Ruth
