### ISSUE TITLE
ZNF609 and ZNF608

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3231]
Hi Colin
based on the annotation of Drosophila orthologs function as a coTF and that these proteins only have 1 zinc finger we have curated these as coTFs not dbTFs 
O15014	ZNF609
Q9ULD9	ZNF608
Droso sbb A0A0B4KEU2 FBgn0285917
PTHR21564

thanks
Ruth and Pascale

**Comment by RLovering** [comment]
Email from Colin:
I believeI agree. Still, what is the basis for the criterion that one Zn Finger is not enough to bind DNA in a sequence-specific fashion?  Shall we put that reasoning/pice of literature in this ticket?

**Comment by pgaudet** [comment]
We will not classify those as dbTFs for now, since the experimental evidence for DNA binding is weak, AND there is a single zinc finger.
