### ISSUE TITLE
Remove the node FB:FBgn0017550|FB:FBgn0033029|PANTHER:PTN000595684 - PTHR23326

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#3236]
This PANTHER node FB:FBgn0017550|FB:FBgn0033029|PANTHER:PTN000595684 is based on the evidence coming from two fly genes FBgn0017550 and FBgn0033029 whose IDA annotations have been removed recently, so please remove this node.

@hattrill @sjm41

**Comment by pgaudet** [comment]
Do you mean the annotation to 'negative regulation of translation' ? (just want to make sure)

Thanks, Pascale

**Comment by phanivg** [comment]
Sorry Pascale, I did not understand what you asked. I was referring to the "poly(A)-specific ribonuclease activity GO:0004535" annotation to this node. I want to update you that the source annotations for that enzyme activity coming from FBgn0017550, FBgn0033029 have been removed in FlyBase.

**Comment by sjm41** [comment]
Looks like things have worked through the system and GO:0004535 is no longer on this node.  I'm closing.
