### ISSUE TITLE
PTHR13119 and tfclass:2.8.1 zinc finger CCCH-type family Not dbTFs?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3238]
Hi Colin and Pascale

I think probably these are not dbTFs

P61129 | ZC3H6 | zinc finger CCCH-type containing 6
Q8N5P1 | ZC3H8 | zinc finger CCCH-type containing 8
Q9UPT8 | ZC3H4 | zinc finger CCCH-type containing 4

Lambert and Vaquerizas suggests several of these are not dbTFs

P61129 | ZC3H6 | zinc finger CCCH-type containing 6
> only NTNU annotation based on tfclass:2.8.1 
> no suitable publications

Q8N5P1 | ZC3H8 | zinc finger CCCH-type containing 8, alias Fliz1
> GO:0003723 | RNA binding annotations
> NTNU annotation based on tfclass:2.8.1 
> dbTF annotation based on PMID:12153508 - this paper does not support this annotation
> research into other functions: PMID: 28254838 and PMID: 30041613 state this is in little elongation complex
> PMID: 12077251 shows recombinant protein binds GATA1 intron and regulates transcription - suggesting dbTF 

Q9UPT8 | ZC3H4 | zinc finger CCCH-type containing 4
> GO:0003723 | RNA binding annotations
> NTNU annotation based on tfclass:2.8.1
> no obvious confirmation of dbTF activity

I think we should remove this family from the QuickGO dbTF list but leave the dbTF annotation associated with the three ZC3Hs. Or should we remove all ISA NTNU annotations and just leave the dbTF annotation based on PMID:12077251?

Best

Ruth

**Comment by RLovering** [comment]
Colin email: Indeed, unless positive evidence for DNA binding is shown, this CCCH family appears to be RNA binding.

**Comment by RLovering** [comment]
Dear Marcio

PANTHER puts these 5 proteins into the same family:
P61129 | ZC3H6 | zinc finger CCCH-type containing 6
Q8N5P1 | ZC3H8 | zinc finger CCCH-type containing 8
Q9UPT8 | ZC3H4 | zinc finger CCCH-type containing 4
Q5TC82 | RC3H1 | ring finger and CCCH-type domains 1
Q9HBD1 | RC3H2 | ring finger and CCCH-type domains 2

Only 3 of them are in the tfclass:2.8.1. Obviously these sorts of differences will arise from time to time. However, all  proteins in tfclass:2.8.1 appear to be annotated as RNA binding and only ZC3H8 has evidence that would support this being a dbTF. Although some papers have demonstrated it is an elongation factors (see notes above).

We will not be including this family in the dbTF list. 

Ideally we would like NTNU to remove the annotations supported by tfclass:2.8.1  and consider removing the  PMID:12077251 dbTF annotations.

Thanks
Ruth

**Comment by RLovering** [comment]
Hi Marcio
could you look at these too please
Thanks

Ruth

**Comment by mlacencio** [comment]
Hi @RLovering ,

Thanks for the nice observations!

We will look these proteins and then give you our position about them.

Best regards,

Marcio

**Comment by RLovering** [comment]
Hi Marcio
we have only about 20 human proteins still annotated as dbTFs which shouldn't be. 

It would be great if these could get fixed soon. 
ZC3H4
ZC3H6
ZC3H8

I will add this text to all of the outstanding tickets if I can find them.
Hope all is well with you
Ruth

**Comment by mlacencio** [comment]
@RLovering and @pgaudet ,

Annotations removed!

Best,

Marcio

**Comment by RLovering** [comment]
great thanks
Ruth

**Comment by RLovering** [comment]
Hi Marcio

**Comment by mlacencio** [comment]
Hi Ruth,

Now I believe that this entry has been properly removed

 Best regards,

Marcio
