### ISSUE TITLE
TIM subunits  IPR005678, IPR005681

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3241]
PMID: 29270408 TIM23 complex does not appear to hydrolyse ATP for translocation of polypeptides (ATP is used by a Hsp on other side of membrane)

Could you remove:
P-P-bond-hydrolysis-driven protein transmembrane transporter activity (GO:0015450)
intracellular protein transport (GO:0006886)
From:
IPR005678 Mitochondrial inner membrane translocase complex, subunit Tim17
IPR005681 Mitochondrial inner membrane translocase complex, subunit Tim23

Thanks

@EBI-Hsinyu  @lsw26  @sarach06  @Alexbateman1  @typhainepl 

FYI @sjm41

**Comment by ValWood** [comment]
I also used this term (ISS'd to things which have now disappeared)
Which terms did you use for MF?
v

**Comment by hattrill** [comment]
I think that wrt transporter function:
protein transporter activity or protein transmembrane transporter activity

**Comment by ValWood** [comment]
This is very weird because the term  when I annotated to it was called
mitochondrial protein translocase activity
and refers to 
TC:3.A.8.1.1
so it seems that the meaning of this term has changed over time???

**Comment by hattrill** [comment]
I can't see a specific term that describes that activity. 
There is a term 'mitochondrial protein-transporting ATPase activity' with the definition:
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O = ADP + phosphate; drives the transport of proteins into the mitochondrion via the mitochondrial inner membrane translocase complex. 
And has the comment:See also the cellular component term 'mitochondrial inner membrane presequence translocase complex ; GO:0005744', which is now known as 'TIM23 mitochondrial import inner membrane translocase complex'
In the definition, of this complex term, they associate the ATPase activity of the Hsp as being an intergral part of the translocase. But Hsp70 is not part of the complex. There are different proposals for how Hsp70 acts: Fig 2 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5725982/
But I would suggest that although it is part of the process, Hsp70 is not part of the Tim23 complex and hence the ATPase activity shouldn't be associated with Tim23 subunits. 

'TIM23 mitochondrial import inner membrane translocase complex' 
Def: The protein transport machinery of the mitochondrial inner membrane that typically transports proteins that possess a matrix-targeting N-terminal presequence. The TIM23 complex contains three essential Tim proteins: Tim17 and Tim23 are thought to build a preprotein translocation channel while Tim44 interacts transiently with the matrix heat-shock protein Hsp70 to form an ATP-driven import motor.

**Comment by ValWood** [comment]
should 'GO:0008566 mitochondrial protein-transporting ATPase activity
be obsoleted. I sounds like you are saying there is no transporter with ATP ase activity. That the ATPase  is separate to the transport?

( GO:0008566 has no annotations)

**Comment by hattrill** [comment]
That would be my feeling.

**Comment by sarach06** [comment]
Hi,
Thank you very much for clarifying this. I have removed the terms you mentioned. The changes will be available in the next InterPro release (82.0).

Best regards,
Sara
