### ISSUE TITLE
Q9Z248 Aebp2 and AEBP2 Q6ZN18

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3243]
Hi MGI and NTNU

AEBP2 has been annotated as a dbTF and as having sequence specific DNA binding based on PMID: 10329662 (see below). However the abstract for this paper states: These results suggest that a portion of the zinc finger structure may play a direct role in transcriptional repression function, but not in DNA binding. They claim that this protein has three Gli-Krüppel (Cys2-His2)-type zinc fingers. But if part of this domain is binding to other proteins and not binding DNA it seems unlikely that the remaining part of the zinc finger domain binds DNA and certainly this paper does not demonstrate DNA binding.

In addition, this review argues that the putative DNA binding domain of AEBP2 is a protein-protein interaction domain (PMID: 30451485). 

Please would you delete the following annotations

Thanks

Ruth

NTNU | Q9Z248 | Aebp2 |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:10329662 |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MGI | Q9Z248 | Aebp2 | enables | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:10329662 |   |   |   |   |   |   |   |  
MGI | Q9Z248 | Aebp2 | enables | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-
NTNU | Q9Z248 | Aebp2 |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:10329662 |   |   | occurs_at(SO:0001952) |   |   |   |   |  
NTNU | Q9Z248 | Aebp2 |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000315(IMP) | ECO:0000315 | (IMP) |   | PMID:10329662 |   |   | occurs_at(SO:0001952)
MGI | Q9Z248 | Aebp2 | enables | GO:0003677 | DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:10329662

@colinlog @pgaudet

**Comment by pgaudet** [comment]
Hi, 

We're finishing off the dbTF catalog paper and those have not yet been fixed. @hdrabkin @mlacencio Can you please fix those annotations ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Harold
we have only about 20 human proteins still annotated as dbTFs which shouldn't be. 7 are due to Ensembl annotations from the mouse ortholog. It would be great if these could get fixed soon. Apologies if you have already done these, and they just haven't shown up in Protein2GO yet. I will add this text to all of the outstanding tickets if I can find them.
Hope all is well with you
Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet ,

Annotations removed!

Best,

Marcio

**Comment by RLovering** [comment]
wonderful
thanks for sorting out all these tickets, only one more to go ;)

**Comment by hdrabkin** [comment]
Done
