### ISSUE TITLE
TF class 2.3.2 remove MF mappings

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3244]
Hi @mlacencio 

TF class is defined as 'Other factors with up to three adjacent zinc fingers' and includes at least one protein that is not a dbTF, AEBP2 (Q6ZN18), but a coTF. The MF mappings should be removed: 

GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific | 
GO:0043565 sequence-specific DNA binding

Thanks, Pascale

**Comment by pgaudet** [comment]
@pgaudet

**Comment by mlacencio** [comment]
Hi @pgaudet ,

Removed!

Best,

Marcio

**Comment by pgaudet** [comment]
Great !
