### ISSUE TITLE
SMAD6 and SMAD7 not dbTFs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3248]
Hi Colin

I have reviewed some of the data and I stick with the statement that SMAD6 and SMAD7 are not dbTFs. A summary of why I have made this decision is below. There is just one paper to support SMAD7 binding DNA but this suggests that MH2 region is binding the DNA where other papers and InterPro state the MH2 region is for protein interactions and not for DNA binding.

 It seems that everyone agrees these are inhibitory SMADs however there is some data confirming DNA-binding by them. This review seems useful https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5334261/ Below are some key points from this review
1.	it states that SMAD6 and 7 do not have MH1 domain whereas UniProt lists these as having MH1 domain. 
2.	They state that The MH2 domains are required for interactions with activated type I receptors and R-Smads.
3.	I-Smads have a PY (Pro-Tyr) motif in their middle regions, which is required for recognition by the WW (Trp-Trp) domains of Smurf (Smad ubiquitin regulatory factor) E3 ubiquitin ligases. 
a.	Smad6, but not Smad7, has a PLDLS (Pro-Leu-Asp-Leu-Ser) motif, which recruits the corepressor carboxy-terminal binding protein (CtBP) to Smad6 (Lin et al. 2003). 
b.	The N domain of Smad7 also has a Leu-rich motif (LRM), which is required for recruitment of the E2 ubiquitin-conjugating enzyme UbcH7 (Ogunjimi et al. 2005). 
4.	Figure 2 describes 4 ways of I-SMAD action, none of which include DNA binding
5.	DNA binding summary
a.	Smad7 has been reported to interfere with the formation of functional Smad–DNA complex, with Smad7 interacting with the Smad-binding DNA element through its MH2 domain (Zhang et al. 2007). Smad7 fused to the DNA-binding domain of GAL4 represses Gal4 luciferase reporter genes (Pulaski et al. 2001; Yan et al. 2014), and this activity is enhanced in cooperation with YY1 and histone deacetylase 1 (HDAC-1) (Yan et al. 2014), suggesting that Smad7 acts as a transcriptional corepressor.
b.	The 2007 paper is the only paper that seems to be referenced for SMAD7 binding DNA (I have done a summary of this data below)
c.	Smad6 possibly associates with the Id1 promoter DNA through interactions with Smad1 and represses BMP-induced transcription of Id1 in the nucleus. (not sure what reference supports this statement probably https://www.ncbi.nlm.nih.gov/pmc/articles/PMC309600/ which is the only ref in this paragraph
d.	In addition, Smad6 has been reported to bind to DNA through its N domain and recruit HDACs to DNA (Bai and Cao 2002). 
e.	In another section: When Smad7 interacts with interferon regulatory factor 1 (IRF1), it increases the affinity of this transcription factor for the interferon-stimulated response element (ISRE) DNA sequence (Hong et al. 2013).

**Summary of specific papers:**

Paper 1 SMAD7
For SMAD7 there seems to be just one quite convincing paper for DNA-binding: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1900056/ https://pubmed.ncbi.nlm.nih.gov/17438144/  Fig 7 D and E: (D) The Smad7 MH2 domain specifically binds to the ARE, but not to its mutant (mut) sequence. GST fused to N-terminal Smad7 MH2 was expressed and purified from Escherichia coli. The oligonucleotide precipitation assay was carried out as described for panel A. (E) The binding of GST-Smad7 protein to DNA is specific. GST-Smad7 protein was purified from E. coli. EMSA was carried out using ARE, PAI-1 sequence, and their mutants. 
The other expts in this paper could be interpreted that SMAD7 is not directly binding as these are nuclear extracts, chromatin ppts.
The reason I think we should not accept this data is because the MH2 domain is not expected to bind DNA (from review above) and also from InterPro record: https://www.ebi.ac.uk/interpro/entry/InterPro/IPR001132/. As this is the only paper to describe this domain binding DNA I do not think this is sufficient evidence.

Paper 2 SMAD7
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3561575/
These results suggest that Smad7 does not directly interact with the ISRE sequence but enhances the binding activity of IRF1 through protein-protein interaction with IRF1 protein. Also states that Smad7 MH1 domain binds IRF1.

Paper 3 SMAD6
For SMAD6 https://pubmed.ncbi.nlm.nih.gov/11711531/ in the 2002 paper: Smad6 also binds to DNA through its MH1 domain, and the MH2 domain of Smad6 masks this binding activity, indicating that Smad6 MH1 and MH2 domains associate reciprocally and inhibit each other's function. Hoxc-8 induces Smad6 binding to DNA as a transcriptional complex. Our findings revealed that I-Smads act as antagonists in the nucleus by recruiting HDACs. The figure looks convincing to me: https://www.jbc.org/content/277/6/4176/F4.large.jpg . However they also state:
To determine the binding site of Smad6, we mutated several bases on the probe at the flanking regions of the Hoxc-8 binding site. The gel-shift results showed that the MH1 domain of Smad6 bound to all of the mutated probes (data not shown), suggesting that specificity of binding of the heterodimer is mainly determined by Hoxc-8. 
Thus the data would support coTF not dbTF activity

Paper 4 SMAD6
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC309600/ this article does not support Smad6 binding DNA: In transfected BMP-responsive 293T cells, Smad6 bound to the DNA only in the presence of Smad1 (Fig. (Fig.7A,7A, lanes 4 and 8) and BMP treatment increased the association of Smad6 with the Id1 promoter DNA. This suggests that Smad6 binding to DNA may be through Smad1. CtBP was also present in this nucleoprotein complex, which seemed to be independent of BMP treatment. Interestingly, the presence of Smad6 (lane 7) or the combination of Smad6 and Smad1 (lanes 4 and 8) enhanced the binding of CtBP to DNA.

Paper 5 SMAD6
https://pubmed.ncbi.nlm.nih.gov/16491121/ used to support Smad6 DNA binding by SWIS and NTNU, but I think the data is just ChIP.

Best

Ruth

@colinlog @pgaudet

**Comment by RLovering** [comment]
SMAD6 O43541 possibly dispute DNA binding and dbTF annotations associated with PMID:16491121
SMAD7 O15105 possibly dispute DNA binding and dbTF annotations associated with PMID: 17438144 and tfclass:7.1.1

**Comment by RLovering** [comment]
NTNU | O15105 | SMAD7 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0005556 (ISA) |   |   |   | GO_REF:0000113 |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NTNU | O43541 | SMAD6 |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314 (IDA) |   | PMID:16491121 |   |   |  
NTNU | O43541 | SMAD6 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0005556 (ISA) |   | GO_REF:0000113 |   | tfclass:7.1.1 |  
IPRO | O15105 | SMAD7 |   | GO:0003700 | DNA-binding transcription factor activity | ECO:0000256(IEA) | GO_REF:0000002 |   | InterPro:IPR013019
SPKW | O15105 | SMAD7 |   | GO:0003677 | DNA binding | ECO:0000322(IEA) | ECO:0000322 | (IEA) |   | GO_REF:0000043 |   | UniProtKB-KW:KW-0238
SPKW | O43541 | SMAD6 |   | GO:0003677 | DNA binding | ECO:0000322 (IEA) |   | GO_REF:0000043
IPRO | O43541 | SMAD6 |   | GO:0003700 | DNA-binding transcription factor activity | ECO:0000256 (IEA) |   |

**Comment by sarach06** [comment]
Hi Ruth,
Thank you very much for this detailed analysis. I have checked the entries including these proteins and deleted the term in the ones which had it. The changes will be seen in the next InterPro release (82.0).

Best regards,
Sara

**Comment by mlacencio** [comment]
Hi @RLovering !

Annotations removed, but please note that there are still IBA annotations by REFG supporting their roles as DbTFs.

Best,

Marcio

**Comment by RLovering** [comment]
Hi Sylvain
have you had a chance to look at this ticket?

Thanks

Ruth

**Comment by RLovering** [comment]
Please could the DNA binding SPKW annotations be removed from O15105 and  O43541 
Thanks
Ruth

**Comment by sylvainpoux** [comment]
Hi Ruth,
sure we can. 
For consistency, would it be possible to delete your experimental annotations (RNA polymerase II cis-regulatory region sequence-specific DNA binding; PMID:28369590) in protein2GO? There are still present
Thanks
Sylvain

**Comment by sylvainpoux** [comment]
Hi Ruth,
My mistake sorry!I was lost with the different SMAD proteins. By the way, I deleted the DNA-binding KW.
Thanks for pointing this out and sorry for the inconvenience
Sylvain

**Comment by RLovering** [comment]
no worries I can close this ticket which is great, thanks for sorting this out
Best
Ruth
