### ISSUE TITLE
which relationships can be used with what

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3249]
I'm trying to figure out which set of RO relations can be used with which entities and terms.

1. Which relations can be used when describing the relationship between a MF activity and another MF activity
2. Which  relations can be used when describing the relationship between an MF activity and a BP (i.e extension or GO cam)
3. Which relations can be used when describing the relationship between an  MF and target entity (i.e extension or GO cam)
4. Which relations can be used when describing the relationship between an  annotated entity and a GO term (i.e  'qualifier'), and which part of the curation does this relate to in GO-CAM ( I just tried to make a model but I couldn't  get noctua to work in  graph or tabular mode).

I presume there are documentation pages for these  but I can only find old pages like this one

http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:has_input
which seem out of date (still refers to has_direct _input).

I can't find the page about the relationships between entities and terms.

 I am examining which includes mappings to  GO Cam and I see  potential inconsistencieds between relationships in use in existing  extensions and in GO-Cam, but it is difficult to know...

@cmungall
@vanaukenk
@pgaudet

**Comment by pgaudet** [comment]
@ValWood The documentation is here: 
http://wiki.geneontology.org/index.php/Annotation_Relations
and http://wiki.geneontology.org/index.php/Annotation_Extension

@vanaukenk and I will be reviewing this in the upcoming weeks before the GO-CAM jamboree. I'll leave this open, you can give feedback and ask for clarification on any page here. 

Thanks, Pascale

**Comment by ValWood** [comment]
Thanks. You can close this ticket. I got what I needed immediately.
v

**Comment by ValWood** [comment]
When is the GO-CAm jamboree?

**Comment by pgaudet** [comment]
Week of November 16th.

**Comment by ValWood** [comment]
Is that for everyone? Is it advertised?

**Comment by pgaudet** [comment]
yes, everyone interested in doing GO-CAM annotation is welcome. It was announced on Tuesday's annotation call: 
http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2020-09-15#GO-CAM_Jamboree

**Comment by ValWood** [comment]
I must have missed the beginning  of the call as usual. 
I still think it is better to send announcements to the GO list so those who can't make the calls are aware too...
