### ISSUE TITLE
TFDP3 Q5H9I0 - remove GO:0000981	 DNA-binding transcription factor activity, RNA polymerase II-specific

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3250]
Hi @mlacencio 

TFDP3 Q5H9I0 is an inhibitor, not a GO:0000981 DNA-binding transcription factor activity, RNA polymerase II-specific. 

Please remove the annotation. 

Otherwise this class is good, I don't like to have an exception but perhaps in this case it deserves an exception. 

Thanks, Pascale

**Comment by mlacencio** [comment]
Hi @pgaudet ,

I have removed the TFDP3 annotation.  I got surprise to know the DP3 can't bind DNA.

Based on your comment, I was wondering if we should really delete a whole TFClass family or subfamily if we find that only one member of it is not or is not likely to be a DbTF. Wouldn't this be a little bit unfair for the remaining members of the category? For example, TFDP1 and all E2Fs are classical DbTFs and if we had followed the rules, they would have been also removed as they are all members of the family 3.3.2.

Maybe should we rethink this rule?

Best,

Marcio

**Comment by pgaudet** [comment]
There are several InterPro domains that have mappings to GO:0003700 DNA binding transcription factor activity and that hit TFDP3: 
- IPR015648 Transcription factor TFDP3 
- IPR028315 Transcription factor TFDP3
- IPR003316  Winged helix DNA-binding domain superfamily
- IPR028315 Transcription factor TFDP3 

The MF mapping to those proteins should be removed. 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I have removed the term from the entries matching TFDP3. The changes will be visible in the next InterPro release (83.0).
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks !
