### ISSUE TITLE
TAIR annotations to PMID:31806676

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3252]
Hi @tberardini 

TAIR annotated a yeast 1 hybrid assay from PMID:31806676 to 
GO:0000976	 transcription regulatory region sequence-specific DNA binding by IPI

I think it should be annotated to HPI (high throughput). 

Thanks, Pascale

**Comment by tberardini** [comment]
@pgaudet Is here an HPI? I don't see it listed here:

http://geneontology.org/docs/guide-go-evidence-codes/

The experiments actually test pairwise interaction and the partners for each annotated gene product are specified so I think IPI is good.

**Comment by pgaudet** [comment]
Oh ! I think I just assumed there was ! Sorry.
