### ISSUE TITLE
P41777 Nolc1 RGD 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3253]
Hi

during the dbTF review we have identified that Nolc1 (alias Nopp140) has been wrongly annotated as DNA binding and as a dbTF. The evidence curated suggests this is a

Note that the curated paper PMID:8972203 states:There is no obviousRNA- or DNA-binding domain in Nopp140 (27). We haveperformed DNase I footprinting experiments using a DNAprobe derived from theagpgene promoter region (2180 to110) and recombinant wild-type Nopp140 but failed to un-cover any sequence-specific recognition by Nopp140. Further-more, we performed an electrophoretic mobility shift assayusing an AGP/EBP-binding oligonucleotide as a probe andrNopp140 and failed to detect any complex formation. Thesefacts suggest that at least in theagppromoter, there is unlikelyto be any DNA binding by Nopp140. 

Please remove these annotations

RGD | P41777 | Nolc1 | contributes_to | GO:0003677 | DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:9553145 
RGD | P41777 | Nolc1 |   | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:8972203

Thanks

Ruth

**Comment by gthayman** [comment]
Done.

**Comment by pgaudet** [comment]
Human annotations: 
Fixed human annotation  Q14978 | NOLC1 |   | GO:0001042 | RNA polymerase I core binding -> protein-macromolecule activity. 

Q14978 | NOLC1 | enables | GO:0003700 | DNA-binding transcription factor activity -> will be automatically updated (Ensembl)

Pascale
