### ISSUE TITLE
LIN54 is not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3254]
Hi

during the dbTF review we identified LIN54 as annotated as a dbTF. The crystal structure paper https://pubmed.ncbi.nlm.nih.gov/27465258/ suggests this binds the minor groove of the DNA. While this is specific binding this does not mean it is a dbTF. Instead LIN54 plays a role in remodeling the DNA.

The paper curated by Wormbase demonstrates DNA binding but the protein is recruited to the promoter regions, by E2F/DP rather than being the initial protein directing specific gene expression. ie it is E2F that is determining which genes are expressed and lin-54 just makes this possible.

We will not include LIN54 on our dbTF list, so you may wish to remove this annotation
WB | Q95QD7 | lin-54 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:21589891

Best

Ruth

**Comment by vanaukenk** [comment]
@RLovering 
Would you still annotate to DNA binding, but rather, a parent of GO:0000977?

**Comment by pgaudet** [comment]
@vanaukenk You can annotate to 'GO:0003680 minor groove of adenine-thymine-rich DNA binding' 


Thanks, Pascale

**Comment by vanaukenk** [comment]
@RLovering @pgaudet @colinlog 

I would like some more guidance on this annotation.

Based on the definition of GO:0000977:

 "Interacting selectively and non-covalently with a specific sequence of DNA that is part of a regulatory region that controls the transcription of a gene or cistron by RNA polymerase II." 

the original annotation seems correct.

I could also make an ISS annotation to the minor groove binding term, but I think it would be unfortunate to lose the MF annotation that LIN-54 binds to transcription regulatory regions.

Have you also looked at this paper for human?  How would you annotate it?

https://febs.onlinelibrary.wiley.com/doi/full/10.1111/j.1742-4658.2009.07261.x

**Comment by vanaukenk** [comment]
@pgaudet @RLovering @colinlog 
Would it be possible to take a look at this together some time?  Thx.

**Comment by colinlog** [comment]
I am not sure how controversial this result is when extrapolating to fly or worm, but to me it looks like very thorough study for a dbTF activity for the human version of LIN54. 

The paper is  convincing as to the 'sequence specific DNA binding activity' (band shifts on Figure 8 in particular -- and this is not just AT richness as a GGG insertion promoted DNA binding). This is an example of a DNA binding protein being part of a large complex that modulates transcription (SYN-MUV also known as the DREAM complex -- I know of Alexander Brehm's work from > 10 years ago, published in Cell).

What was throwing us off was the lack of a DNA binding domain? This is solved as a CXC domain? Or is that controversial/unlikely?

That productive binding is also E2F4 dependent, is not really a problem. It is well known that E2F and DREAM and RB/p130 etc work together.

Still, let's look as a group to check for the 'provides a genomic address' part of dbTF activity. I would say that the crux is whether there is evidence for a DNA sequence that must be present to repress/induce the target gene and that this is directly bound by LIN54 to regulate the promoter.

**Comment by vanaukenk** [comment]
@colinlog 
Thank you very much for your feedback. I'll look to see if there are other papers that might inform LIN54 function.
