### ISSUE TITLE
Review annotations to 'GO:0001300 chronological cell aging' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3255]
Dear all, 

The proposal has been made to obsolete 'GO:0001300 chronological cell aging' and its children: 
* GO:0001323 age-dependent general metabolic decline involved in chronological cell aging
* GO:0010978 gene silencing involved in chronological cell aging
* GO:0001305 progressive alteration of chromatin involved in chronological cell aging 
*  GO:0001324 age-dependent response to oxidative stress involved in chronological cell aging
* GO:0001320 age-dependent response to reactive oxygen species involved in chronological cell aging 

See #18632 

Annotations to be reviewed are here: 
https://docs.google.com/spreadsheets/d/16xynCABJWISWKDrM4mRCCq46pHdBQrXJ5EbvirsmDsc/edit#gid=0

* 2 BHF
* 2 MGI
* 22 SGD

Higher eukaryotes can probably replace the annotation by 'GO:0090398 cellular senescence'. For yeast 'GO:0044838
cell quiescence' may work. 

Thanks, Pascale

**Comment by srengel** [comment]
cleared all the SGD ones.  done.

**Comment by pgaudet** [comment]
Great ! Thanks @srengel !

**Comment by pgaudet** [comment]
Obsoletion is done. According to the spreadsheet there are some annotations left: 
- 1  MGI  - @hdrabkin 
- 2 BHF @RLovering 

Thanks, Pascale

**Comment by hdrabkin** [comment]
done
