### ISSUE TITLE
Ighmbp2 rat and mouse annotations

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3257]
Hi

we do not think this is a dbTF. The zinc finger is a ubiquitin like fold and therefore unlikely to bind dsDNA, and instead protein interaction domain.

Please delete these rat annotations
MGI | Q9EQN5 | Ighmbp2 | enables | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15358184
RGD | Q9EQN5 | Ighmbp2 |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15358184 |   |  
ECO:0000314 | (IDA)

You might also want to consider removing these

rat 
RGD | Q9EQN5 | Ighmbp2 |   | GO:0000122 | negative regulation of transcription by RNA polymerase II | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15358184

mouse
MGI | P40694 | Ighmbp2 | acts_upstream_of_or_within | GO:0000122 | negative regulation of transcription by RNA polymerase II | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15358184

Thanks

Ruth

@pgaudet @colinlog

**Comment by gthayman** [comment]
Hi Ruth,
I'm going to respectfully disagree with you. This protein has seven helicase motifs and an R3H motif, which I believe mediate DNA binding, and five references, 27 through 31, cited in PMID:15358184 all indicate that orthologs of this protein bind DNA.
Tom

**Comment by RLovering** [comment]
Hi Tom

thanks. In our review of human dbTFs none of the 7 groups that provided lists of dbTFs included this protein in their lists. Obviously none of the lists were complete, however it is unusual for none of them to have picked this up. Colin suggested that the AN1-type zinc finger is ubiquitin-ike protein fold. The protein has also been identified as a 5' to 3' helicase that unwinds RNA and DNA duplices in an ATP-dependent reaction. According to UniProt the human protein: Preferentially binds to the 5'-GGGCT-3' motif. Whereas PMID:15358184 suggests recombinant Smubp-2 protein binds to region II (containing the ACTG-motif) in the 50-bp element in the MMTV promoter. I believe that helicases can influence the transcription rate but this does not mean that the protein is specifically binding to the regulator region of DNA in order to determine the expression of a gene. It is possible that this protein is localised to the region when a dbTF that regulates the specific tissue etc expression of the gene.

It would be nice if you would remove these annotations. Either way I do not think we will be adding this gene to our list of human dbTFs

Best

Ruth

**Comment by gthayman** [comment]
The RGD repressor activity annotation has been removed.

**Comment by pgaudet** [comment]
Hi @hdrabkin 

This one is still not fixed; can you please remove? 

MGI | Q9EQN5 | Ighmbp2 | enables | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:15358184

Thanks, Pascale

**Comment by hdrabkin** [comment]
Done
