### ISSUE TITLE
TCF20 not a dbTF mouse 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3258]
Hi

although there are 2 papers that have been curated to support the role of Tcf20 as a dbTF. We believe that the DNA binding is via the AT hook domain and the binding has been confirmed to be to TTTAAA https://www.jbc.org/content/275/51/40288.long PMID:10995766 ie AT hook

PMID:7760812 DNA binding is shown using nuclear extract so does not confirm sequence specific  ds DNA binding please remove these annotations:

MGI | Q9EPQ8 | Tcf20 | enables | GO:0000976 | transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:7760812
NTNU | Q9EPQ8 | Tcf20 | enables | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:7760812
MGI | Q9EPQ8 | Tcf20 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:7760812

PMID:10995766 confirms that it is a coTF as it regulates the expression of dbTFs please change this annotation to  GO:0003680 minor groove of adenine-thymine-rich DNA binding:
NTNU | Q9EPQ8 | Tcf20 |   | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:10995766

I have added transcription coactivator activity term based on this paper

Best

Ruth

@pgaudet @colinlog

**Comment by mlacencio** [comment]
@RLovering ,

Annotations removed!

Best,

Marcio

**Comment by RLovering** [comment]
Thanks
Ruth

**Comment by LiNiMGI** [comment]
Annotations removed!
