### ISSUE TITLE
atx1 not a transport chaperone 	O74735

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3259]
GO:0006825 | copper ion transport | IEA with KW-0187 | GO_REF:0000043

I have
protein maturation by copper ion transfer
which is not related to transport in GO

**Comment by ValWood** [comment]
Also applies to Interpro mappings
IPR017276
IPR007745

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
Thank you for this. I agree that this term "GO:0006825 copper ion transport" shouldn't be in these entries. I have removed them. 
Regards, 
Hsin-Yu
