### ISSUE TITLE
GPER1 not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3260]
Hi

please would you consider removing the following annotations as the protein does not have a DNA binding domain.

PMID:20445128 does not support this annotation.
PMID:23283935 This paper shows that the G-protein coupled transmembrane receptor does bind to estrogens, and anti-estrogens and that this influences trancription through MAPK activation. However, there is no evidence for a DNA binding (nuclear) transcription factor activity for GPER1 in the paper. The nuclear receptor ESR1 and ESR2 do activate transcription and are antagonized by anti-estrogens. GPER1 is not a dbTF.

SWIS | O08878 | Gper1 |   | GO:0003707 | steroid hormone receptor activity | ECO:0000314 (IDA) | 3 | PMID:23283935
RGD | O08878 | Gper1 |   | GO:0003707 | steroid hormone receptor activity | ECO:0000314 (IDA) |   | PMID:20445128
SWIS | O08878 | Gper1 |   | GO:0030284 | estrogen receptor activity | ECO:0000314 (IDA) | 2 | PMID:23283935

Thanks

Ruth and Colin

@colinlog

**Comment by gthayman** [comment]
RGD annotation deleted.

**Comment by RLovering** [comment]
thanks

**Comment by pgaudet** [comment]
Fixed.

**Comment by RLovering** [comment]
Hi both

don't kill me but I just checked the ontology and actually these annotation were correct as this term is not associated with DNA binding 

really sorry, I should have checked the term instead of just assuming I had remembered this correctly

Ruth
