### ISSUE TITLE
Review annotations to Ncor2 : it is a co-repressor, not a dbTF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3261]
Hi @gthayman 

Ncor2 *is* a co-repressor, not a dbTF, so this annotation is incorrect: 

RGD | A0A0G2JU91 | Ncor2 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:20137375 |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ECO:0000314 | (IDA)
  |   | RGD | D3ZXN9 | Ncor2 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:20137375
ECO:0000314 | (IDA)

Thanks, Pascale
Please remove or change to  GO:0003714 transcription corepressor activity

**Comment by gthayman** [comment]
Annotation removed.

**Comment by vanaukenk** [comment]
@pgaudet - maybe this one can be closed, too?
