### ISSUE TITLE
P09874	 PARP1 not dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3262]
Hi Marcio

We have checked this protein again and Colin has reviewed the paper PMID:11112786 which you curated. Although this paper shows DNA binding this is using a crude fraction. This is an old paper as this is so unexpected that Colin feels that someone would have followed this up, as it is very unexpected that a poly(ADP-ribose) polymerase would also have the dbTF function.

Please remove this annotation

P09874 | PARP1 | enables | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | ECO:0000314 | IDA | PMID:11112786 | 9606 | NTNU_SB | has_input(NCBI_Gene:2919)

Thanks

Ruth

@pgaudet @colinlog

**Comment by mlacencio** [comment]
Dear @RLovering ,

Agree and removed!


Best,

Marcio

**Comment by pgaudet** [comment]
Thanks Marcio - added to our spreadsheet.
