### ISSUE TITLE
Review annotations to GO:0060850  regulation of transcription involved in cell fate commitment & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3263]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:
https://docs.google.com/spreadsheets/d/18pfebO6j8apSONxXWAoBLNVQeuA-8Kv4OD6-mfXUfO0/edit#gid=0

Contributor   (Assigned by)
--
BHF-UCL | 3
MGI | 12
UniProt | 8 (done)
WB | 1
ZFIN | 1

 
Thanks, Pascale

**Comment by vanaukenk** [comment]
WB annotation updated.

**Comment by sabrinatoro** [comment]
ZFIN annotation has been updated

**Comment by pgaudet** [comment]
@hdrabkin Did you do the MGI ones ?

**Comment by hdrabkin** [comment]
I thought I had passed it one to another MGI; but will do now

**Comment by LiNiMGI** [comment]
MGI annotations have been updated.

**Comment by pgaudet** [comment]
Hi @RLovering 
Can you look at the 3 BHF annotations ? 

Thanks, Pascale

**Comment by RLovering** [comment]
done thanks for the reminder
Ruth
