### ISSUE TITLE
Review annotations to regulation of transcription involved in anterior/posterior axis specification 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3264]
Hello,

To finish work in this ontology ticket: geneontology/go-ontology#12739

Please review/move these annotations:
https://docs.google.com/spreadsheets/d/1U5ctXXa3Te5UOJIrt4bxcWg_dH63dkqhGTKfbhANiBs/edit#gid=0

Contributor   (Assigned by)
--
BHF-UCL | 2
Flybase | 2
UniProt | 1 (done)

**Comment by hattrill** [comment]
done

**Comment by vanaukenk** [comment]
@pgaudet - do you think we can close this annotation review ticket?  It looks like the annotations have been changed.

**Comment by pgarmiri** [comment]
What a coincidence! I used this term yesterday! Thanks to the email summary I noticed that something was going on with term and I revised my annotations according to the guidelines in the ticket :)
