### ISSUE TITLE
IBA/interpro nuclease activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#3265]
There seems to be a number of proteins annotated to 
GO:0004518  nuclease activity  (Interpro)
or child 5'-flap endonuclease activity &  flap endonuclease activity (IBA)

eg. J9VT48, Q587E3, P40850, Q9UTN2, Q38C92

but the metal binding site isn't conserved
CAUTION: Although it belongs to the XPG/RAD2 endonuclease family, only one of the seven Asp residues involved in Mg(2+) binding is conserved suggesting that it has no nuclease activity. 
@pgaudet 
@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

**Comment by Antonialock** [comment]
(also papers don't support endonuclease activity)

**Comment by sarach06** [comment]
Hi!
The term has been removed from the family entry IPR006084 and it is mentioned in the abstract to make it clear, which will be seen in the next InterPro release.

Best,
Sara

**Comment by EBI-Hsinyu** [comment]
Hi! 
This is the same problem with the delay between InterPro and Uniprot. 
Regards, 
Hsin-Yu
