### ISSUE TITLE
Review GO assignment for GO:0005634. Bacterial gene product incorrectly assigned a nucleus GO id as a cellular component.

### ISSUE THREAD

**Issue by waikitong** [geneontology/go-annotation#3268]
Looks like an E. coli gene product [UniProtKB:P0A8J2](https://www.uniprot.org/uniprot/P0A8J2) has been incorrectly assigned a cellular component of GO:0005634 (nucleus). [QuickGO link](https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P0A8J2). Reference: GO_REF:0000108. Assigned By GOC. 

Nucleus is for eukaryotic cells and E. coli is a prokaryote, so UniProtKB:P0A8J2 should not have been assigned GO:0005634.

**Comment by pgaudet** [comment]
Thanks for reporting this @waikitong 

----
@keseler 

This comes from the IPI annotation to a term that is clearly meant for eukaryotes: 

UniProtKB:P0A8J2 | dnaT | involved_in | GO:0006267                pre-replicative complex assembly involved in nuclear cell cycle DNA replication

Can you please edit ? 

----
@alexsign 

Are those not filtered from QuickGO and the files you produce ? Our taxon rule (https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000013.md) filters out non-EXP annotations that fail the taxon constraints. 

Thanks, Pascale

**Comment by alexsign** [comment]
@pgaudet pretty strange, I'll take a look

**Comment by pgaudet** [comment]
Thanks !
