### ISSUE TITLE
IPR005629 not 	 (1->6)-beta-D-glucan biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3269]
It affects 

(1->6)-beta-D-glucan biosynthetic process
  it's actually a bit upstream. Its a plasma membrane anchor, so I think this annotation should be removed.

So the name probably needs updating too!

Here are 2 more recent papers:
PMID: 27749909
PMID: 27898700 

The  (1->6)-beta-D-glucan biosynthetic process also won't travel well to oomycetes which are also in this family.

Thanks
Val

**Comment by sarach06** [comment]
Hi Val,
Many thanks for this. I have updated the name and abstract and removed the term. This will be available in the next InterPro release (83.0).
Kind regards,
Sara
