### ISSUE TITLE
taxon violation for fungal protein

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3270]
UniPRot:A7WPF7
https://www.uniprot.org/uniprot/A7WPF7
has SPKW mapping to "viral envelope protein" in QuickGO

**Comment by sylvainpoux** [comment]
Hi Val,
unfortunately, we cannot do anything as erroneous annotation is coming from the submitter.
You should contact EMBL and ask them to remove this erroneous annotation
Thanks
Sylvain

**Comment by ValWood** [comment]
Hi, Sylvain,

I don't understand, I thought the KW were assigned by UniProt?

I don't see any reference to "viral envelope" in this entry?
https://www.ebi.ac.uk/ena/browser/api/embl/CAO98811.1?lineLimit=1000

Val

**Comment by sylvainpoux** [comment]
Hi Val,

my mistake, sorry. You are right, it is assigned by UniProt based on EMBL content. 

I however have no control on automatic annotation. May I ask you to contact Penelope (@pgarmiri ) from GOA? She will be able to correct this

Sorry

Sylvain

**Comment by ValWood** [comment]
Thanks, assigned to @pgarmiri

**Comment by pgarmiri** [comment]
Hi @ValWood ,

This is on our side. I got a reply below from Jie that is responsible for those mappings.

"In our embl protein import, we have following rule
EMBL					UniProt keyword
envelope glycoprotein	Viral envelope protein
envelope polyprotein	Viral envelope protein
envelope protein	Viral envelope protein

According to above rules, if production contains “envelope protein”, we add the “Viral envelope protein” keyword to uniprot entry. I noticed for this entry
The product is "nuclear envelope protein”, we will add the keyword. Maybe we should have for more strict rule for this keyword. "

Could you please let us know how strict should the rule be on this?

Thanks,

Penelope

**Comment by ValWood** [comment]
probably "envelope protein" can't map to anything? but only
"nuclear envelope protein" could map to "nuclear envelope" and
"viral  envelope protein" can map to "viral envelope protein"
Can taxonomic information be incorporated into the KW rules? that would work, but I don;t think you can make a rule from substring matching.

**Comment by pgarmiri** [comment]
Hi @Val, 
I just heard back for Jie that he has fixed the issue. The fixed entry will be in 2021.01 release.
Thanks,
Penelope
