### ISSUE TITLE
mouse Zfpm1 O35615 and Human ZFPM1 Q8IX07 Not dbTFs

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3272]
Hi Harold and Marcio

please change or remove these annotations. ZFPM1 is a coTF not a dbTF

Thanks

Ruth

NTNU | Q8IX07 | ZFPM1 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0005556 (ISA) |   | GO_REF:0000113 |   | tfclass:2.7.2 |  
MGI | O35615 | Zfpm1 | enables | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314 (IDA) |   | PMID:21245044

**Comment by RLovering** [comment]
Hi Marcio
we have only about 20 human proteins still annotated as dbTFs which shouldn't be. It would be great if these could get fixed soon. I will add this text to all of the outstanding tickets if I can find them.
Hope all is well with you
Ruth

**Comment by RLovering** [comment]
Hi Harold

we have only about 20 human proteins still annotated as dbTFs which shouldn't be. this was a request to remove the sequence specific binding annotation, which is not as much of an issue as the dbTF activity terms. 

Note that you also have ISO dbTF activity and DNA binding annotations still associated with this protein, eg 

DNA-binding transcription repressor activity, RNA polymerase II-specific and RNA polymerase II cis-regulatory region sequence-specific DNA binding.

It would be great if these could get fixed soon. I will add this text to all of the outstanding tickets if I can find them.

Hope all is well with you
Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet ,

Annotation removed!

Best,

Marcio

**Comment by hdrabkin** [comment]
MGI removed

**Comment by RLovering** [comment]
great thanks
Ruth
