### ISSUE TITLE
mouse Bcl3 Q9Z2F6

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3274]
Hi 

Bcl3 is not a dbTF it is a coTF. The curated paper states: we found that coexpression of Bcl-3 and p50 significantly transactivated the promoter (Fig. 7⇓, B and C), strongly suggesting that Bcl-3, along with its DNA-binding partner, p50, participates in the transactivation of gata-3.

The EMSA's are nuclear extracts and are looking at Bcl-3 and p50 complexes.

Please delete these annotations or revise to coTF annotation

Thanks

Ruth

MGI | Q9Z2F6 | Bcl3 | enables | GO:0000978 | RNA polymerase II cis-regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:16081776 |   |   | has_input(MGI:MGI:95663) |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ECO:0000314 | (IDA)
  |   | MGI | Q9Z2F6 | Bcl3 | enables | GO:0003700 | DNA-binding transcription factor activity | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:16081776
ECO:0000314 | (IDA)

**Comment by RLovering** [comment]
Hi Harold
we have only about 20 human proteins still annotated as dbTFs which shouldn't be. 7 are due to Ensembl annotations from the mouse ortholog. It would be great if these could get fixed soon. Apologies if you have already done these, and they just haven't shown up in Protein2GO yet. I will add this text to all of the outstanding tickets if I can find them.
Hope all is well with you
Ruth

**Comment by hdrabkin** [comment]
Fixed
