### ISSUE TITLE
SGD:S000004599/PANTHER:PTN000289179 protein disulfide isomerase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3276]
SGD:S000004599 has been annotated with protein disulfide isomerase activity GO:0003756, but it should most probably be just thiol oxidase activity GO:0016972. It is Pdi1p that does the isomerase bit, and Ero1p acts on Pdi1p as a thiol oxidase.

I've replaced the FlyBase annotation for protein disulfide isomerase activity with thiol oxidase activity. This just leaves SGD:S000004599 supporting GO:0003756 for PANTHER:PTN000289179.

**Comment by hattrill** [comment]
tagging @srengel

**Comment by hattrill** [comment]
FYI @phanivg

**Comment by sjm41** [comment]
BTW, the fly annotation is still showing up on the PAINT node: http://www.pantree.org/node/annotationNode.jsp?id=PTN000289179
Shouldn't it have disappeared by now?

**Comment by sjm41** [comment]
Fly annotation has now disappeared from the PAINT node, but problematic annotation (from yeast persists).
Adding high priority flag to fix please!

**Comment by srengel** [comment]
i have deleted the offending protein disulfide isomerase activity GO:0003756 annotation to yeast ERO1 SGD:S000004599 just now in P2GO.  apologies for the delay.

**Comment by ValWood** [comment]
Hi @hattrill  while you are looking at this, is 

IPR007266
+ | protein-disulfide reductase activity
+ | thiol oxidase activity

are these describing the same reaction? they aren't closely related in the ontology...

**Comment by hattrill** [comment]
Hi @ValWood - the acceptor is the main difference

protein-disulfide reductase activity GO:0015035
Def:Catalysis of the reaction: a protein with reduced sulfide groups = a protein with oxidized disulfide bonds.
is_a 
disulfide oxidoreductase activity GO:0015036
Catalysis of the reaction: substrate with reduced sulfide groups = substrate with oxidized disulfide bonds. 
&
catalytic activity, acting on a protein GO:0140096
Catalytic activity that acts to modify a protein. 

thiol oxidase activity GO:0016972
Catalysis of the reaction: 4 R'C(R)SH + O2 = 2 R'C(R)S-S(R)CR' + 2 H2O2. 

is_a
oxidoreductase activity, acting on a sulfur group of donors, oxygen as acceptor
Catalysis of an oxidation-reduction (redox) reaction in which a sulfur-containing group acts as a hydrogen or electron donor and reduces oxygen. 

So, for **protein-disulfide reductase activity GO:0015036** - in this case something like NAD(P)+ is the acceptor and the substrate is a protein

and for **thiol oxidase activity GO:0016972** - oxygen is the acceptor

The branches intersect at 

oxidoreductase activity, acting on a sulfur group of donors GO:0016667
Catalysis of an oxidation-reduction (redox) reaction in which a sulfur-containing group acts as a hydrogen or electron donor and reduces a hydrogen or electron acceptor.

**Comment by ValWood** [comment]
OK thanks.
