### ISSUE TITLE
human FAM50B/A role. role previously obscure

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3277]
Has a role in splicing 
https://pubmed.ncbi.nlm.nih.gov/32703943/

So UniPROT can remove
"May be a DNA-binding protein or transcriptional factor."

I am ISSing to splicing.

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprot/Q9Y247
https://www.uniprot.org/uniprot/Q14320

**Comment by ValWood** [comment]
@Antonialock

**Comment by pgaudet** [comment]
@sylvainpoux

**Comment by ValWood** [comment]
I can e-mail the helpdesk for this one...

**Comment by ValWood** [comment]
I mailed the helpdesk. The DB-TF annotation was removed, presumably part of transcription  review.
