### ISSUE TITLE
SGD RCR1 not "ubiquitin ligase substrate adaptor"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3278]
I was about to update the pombe ortholog of RCR1  because I notice it is recently described as a 
"ubiquitin ligase substrate adaptor"

However on closer inspection I dont' think it is a 
"ubiquitin ligase substrate adaptor" 

Description
The binding activity of a molecule that brings together a ubiquitin ligase and its substrate. Usually mediated by F-box BTB/POZ domain proteins.

This is the activity of adapting a ligase and its substrate. I thin k that the term you need is

GO:0043495   protein-membrane adaptor activity (with occurs at "plasma membrane")

I will use this in the ISS so let me know if you agree.

**Comment by edwong57** [comment]
Hi Val, I took a look at the paper and I think the term you suggest works. I've made the change in Noctua. It should show up next week.
