### ISSUE TITLE
SGD SCS3 / YGL126W 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3279]
SCS3 / YGL126W 
was annotated in 2019 to

involved in | postreplication repair |   | IGI with DUN1 | SGD | 2019-07-26 | Hammet A, et al. (2002) PMID:11953437

from an old paper. This looks incorrect, because this is an ER membrane protein involved in lipid metabolism (lipid droplet assembly) and ERAD.

I quickly searched PMID:11953437 and I could not find any reference to SCS3 / YGL126W  

Could you take a look?

Thanks
v

**Comment by edwong57** [comment]
Thanks, Val. I checked it out. I think there was a typo when the annotation was made. I corrected it in Protein2GO -- it might take a week to show up in production. Closing.
