### ISSUE TITLE
InterPro2GO: Phospholipid phosphatase (IPR043216)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3281]
Phospholipid phosphatase (IPR043216) is currently associated with the MF "phosphatidate phosphatase activity (GO:0008195)", which has the def "Catalysis of the reaction: a 1,2-diacylglycerol 3-phosphate + H2O = a 1,2-diacyl-sn-glycerol + phosphate."  and EC xref EC:3.1.3.4.

This seems too specific for the InterPro entry given its description ("Type 2 lipid phosphate phosphohydrolases (LPPs), formerly known as phosphatidic acid phosphatases (PAPs), are enzymes that catalyse the hydrolysis of a variety of lipid phosphate mono-esters, including lysophosphatidic acid (LPA), PA, diacylglycerolpyrophosphate, S1P and ceramide 1-phosphate (C-1-P)....") and associated EC numbers of annotated proteins (3.1.3.4, 3.1.3.-, 3.1.3.81, 3.1.3.106).

Would "lipid phosphatase activity (GO:0042577)" be better?

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by alanbridge** [comment]
Hi Steven, 

yes it probably would, the range of substrates for IPR043216 seems much broader than 1,2-diacyl-sn-glycero-3-phosphate 

https://www.uniprot.org/uniprot/?query=ipr043216+AND+reviewed%3Ayes+AND+rhea%3A*&sort=score

All the best, Alan

**Comment by sarach06** [comment]
Hi Steven,
I looked at this entry and I changed the term for GO:0042577. This change will be available in the next InterPro release (83.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Great, thanks Sara (and Alan).
