### ISSUE TITLE
PTN001853063 - PTHR21541

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3284]
http://www.pantree.org/node/annotationNode.jsp?id=PTN001853063

PTN001853063 propagates the following annotations to SLX4/him-18 orthologs:
contributes_to 3'-flap endonuclease activity
contributes_to 5'-flap endonuclease activity
contributes_to crossover junction endodeoxyribonuclease activity

Sources for these annotations are:
(CAEEL|WormBase=WBGene00011415|UniProtKB=Q22145) - PMID:22927825
(HUMAN|HGNC=23845|UniProtKB=Q8IY92) - PMID:19595721, PMID:19596235, PMID:19596236

From looking at those references and the UniProt pages, it looks like SLX4/him-18 is a structural/regulatory subunit, so (following current 'contribute to' guidelines) I think those terms should be removed from this node and the source annotations be edited/deleted.

@vanaukenk @pgarmiri @sylvainpoux

**Comment by pgaudet** [comment]
Fixed PAINT family, thanks @sjm41

**Comment by pgaudet** [comment]
- Disputed Human annotations
- Removed C. elegans annotations. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet!
