### ISSUE TITLE
NDUFAF2 is not an enzyme: IPR007763 & MGI:1922847

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3287]
tagging InterPro:
@EBI-Hsinyu 
@lsw26 
@sarach06
 @Alexbateman1 
@typhainepl
and MGI/enzyme fan: @hdrabkin 

NDUFAF2 is a paralog of NDUFA12. NDUFA12 has enzyme activity, but NDUFAF2 does not, it is classed as a Complex-I assembly factor.

Annotations from IPR007763  NADH dehydrogenase [ubiquinone] 1 alpha subcomplex subunit 12 are being applied to both NDUFAF2 and NDUFA12:
NADH dehydrogenase (ubiquinone) activity (GO:0008137)
electron transfer activity (GO:0009055)

So should be removed.

For mice:
MGI:1922847 (NDUFAF2)
PMID:23702311
has been annotated with:
Biological Process			cellular respiration			IMP	MGI:5521199 	J:201547 	
Molecular Function	oxidoreductase		NADH dehydrogenase (ubiquinone) activity			IMP	MGI:5521199 	J:201547 	
Biological Process			reactive oxygen species metabolic process			IMP	MGI:5521199 	J:201547 	
Biological Process			respiratory electron transport chain			IMP	MGI:5521199 	J:201547 

This paper states that "Ndufaf2, unlike other Complex-1 assembly factors, may be more accurately described as a chaperone involved in proper folding during Complex-1 assembly, since it is dispensable for Complex-1 maturation but not its proper function."

Perhaps GO:0032981 'mitochondrial respiratory chain complex I assembly' is more appropriate? 

From PMID:23648483 "Neurospora crassa NDUFAF2 homologue, the 13.4 L protein, is a late assembly factor that associates with complex I assembly intermediates containing the membrane arm and the connecting part but lacking the N module of the enzyme. Furthermore, we provide evidence that dissociation of the assembly factor is dependent on the incorporation of the putative regulatory module composed of the subunits of 13.4 (NDUFA12), 18.4 (NDUFS6), and 21 (NDUFS4) kDa. Our results demonstrate that the 13.4 L protein is a complex I assembly factor functionally conserved from fungi to mammals."

Reactome has a model for complex I assembly: https://www.reactome.org/content/detail/R-HSA-6799198

(FYI @sjm41 @phanivg Gene Groups fix needed here)

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have removed those terms and added GO:0032981 to the entry. The changes will be available in the next InterPro release (83.0).
Best,
Sara

**Comment by hattrill** [comment]
Thanks, Sara

**Comment by hdrabkin** [comment]
Activity term removed and GO:0032981 added as suggested

**Comment by hattrill** [comment]
Ace. Thanks.
