### ISSUE TITLE
Q9NZJ7 MTCH1 outie not innie

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3288]
Q9NZJ7 MTCH1 is an outer mitochondrial membrane protein https://pubmed.ncbi.nlm.nih.gov/18375015/ but is getting  GO:0005743 mitochondrial inner membrane from 2 electronic pipelines:

UniProtKB-SubCell and KW

**Comment by hattrill** [comment]
Hi @pgarmiri - I am tagging you, but not sure if that's correct for this pipeline :-)

**Comment by pgaudet** [comment]
I think this is @sylvainpoux ?

**Comment by pgarmiri** [comment]
Hi, 
I had a quick look and the mapping is correct. So, it does need to be changed on the UniProt side.
Penelope

**Comment by pgarmiri** [comment]
Hi @sylvainpoux ,
Could you please change the keyword in this entry? 
Thanks,
Penelope

**Comment by sylvainpoux** [comment]
done, I changed the SUBCELLULAR LOCATION as well
Thanks
Sylvain

**Comment by hattrill** [comment]
Thanks
