### ISSUE TITLE
IPR023635 - Peptide deformylase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3295]
Hi, 

I think you can add 'peptide deformylase activity' (GO:0042586) to IPR023635

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven,
Many thanks. I added the term to this entry. The changes will be seen in the next release (InterPro 83.0).

Best regards,
Sara

**Comment by sjm41** [comment]
thanks
