### ISSUE TITLE
InterPro2GO: Thioesterase (IPR001031)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3299]
This entry is currently associated with the GO term "hydrolase activity, acting on ester bonds (GO:0016788)"
Do you mind checking whether you think this is accurate?

Two source references are given. I don't see any evidence for hydrolase/esterase activity in the first one (PMID: 9560421) and it concludes with "Nevertheless, further studies are needed to clarify the definite catalytic functions of these thioesterase-like proteins."

The introduction of the second ref (PMID: 23822773) includes "Most TEs [thioesterase domains] from fungal iPKSs catalyze product release by intramolecular C—C bond formation through Claisen/Dieckmann cyclization (TE/CLC domains), in some cases coupled to product truncation by deacylation. Nevertheless, a smaller number of fungal iPKSs, including those involved in RAL or DAL biosynthesis, feature TE domains that catalyze O—C bond formation through macrolactone closure, hydrolysis, and ester or pyrone formation."

Seems like the TE domain may be involved in hydrolysis, but not always, so I think the current GO MF term on IPR001031 should probably be removed?

(Reason I ask is that three fatty acid synthases in Drosophila (FASN1, FASN2, FASN3) are being annotated as hydrolases via this InterPro2GO, and I don't see the evidence for that.)

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. I had a look and I agree with you that the term is not correct for all the members, so I have removed it. The changes will be available in the next InterPro release (83.0).
Best regards,
Sara

**Comment by sjm41** [comment]
That's great, thanks for checking!
