### ISSUE TITLE
InterPro2GO - Myosin tail (IPR002928)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3303]
This domain is associated with the GO MF term "motor activity (GO:0003774)"

However, it is found in invertebrate 'paramyosin' protein, which is a structural protein with no known motor activity itself.

Further, the current InterPro description for this entry also suggests that the tail region only has a structural role.

If you agree, can you dissociate "motor activity" from this entry?

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven,
Many thanks. Yes, I agree with you. I have removed the term from this entry and the changes will be seen in the next InterPro release (83.0).

Best regards,
Sara

**Comment by sjm41** [comment]
thanks!
