### ISSUE TITLE
missing GO annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3305]
These 29 identifiers were found to be unannotated: Systematic ID SPBC32H8.03 SPCC622.21 SPBC27.04 SPCC663.02 SPCC736.05 SPBC21C3.07c SPCC285.07c SPCC1906.04 SPCC1183.10 SPCC1281.08 SPCC663.17 SPCC970.11c SPCC1450.08c SPCC794.02 SPAC12G12.16c SPAC1F7.06 SPCC1620.02 SPCC1739.15 SPBC354.08c SPAC11D3.13 SPCC162.04c SPBC649.05 SPAC144.19 SPCC548.03c SPBC3H7.11 SPCC1919.06c SPCC1906.03 SPBC947.09

**Comment by pgaudet** [comment]
Who is this addressed to ???

**Comment by ValWood** [comment]
Wrong tracker!
