### ISSUE TITLE
cyclins not	G2/M transition of mitotic cell cycle	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3306]
These 3 fission yeast cyclins are not involved in G2/M transition
I don't think cyclin phases should be transferred in general.....

cig1	
IBA with S000006323 , S000003340 , S000006324 , PTN000808787 , P30284	
Gaudet P et al. (2011)
cig2	
IBA with P30284 , S000006323 , PTN000808787 , S000003340 , S000006324	
Gaudet P et al. (2011)
rem1	
IBA with S000006323 , PTN000808787 , S000006324 , S000003340 , P30284

**Comment by ValWood** [comment]
(the cyclins are too similar, so paralogs  and orthologs are difficult to distinguish, plus there are lots of differences between pombe and cerevisiae)

**Comment by marcfeuermann** [comment]
As it is too difficult to distinguish paralogs and orthologs (and as those seem to me mixed in the family tree), I decided to remove propagation of specific phase transitions and keep only the more general parent term.
