### ISSUE TITLE
PTN000027265/PTN000249331/PTN000313913 not 'regulation of"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3311]
positive regulation of RNA polymerase II transcription preinitiation complex assembly

these should be
RNA polymerase II transcription preinitiation complex assembly
(not regulation, they are directly involved in initiation)

taf6	
IBA with FBgn0031281 , P49848 , PTN000027265	
Gaudet P et al. (2011)
taf9	
IBA with WBGene00006391 , MGI:1888697 , Q16594 , PTN000249331 , 727861	
Gaudet P et al. (2011)
tfg1	
IBA with MGI:1923848 , PTN000313913 , 1359646 , P35269	
Gaudet P et al. (2011)

**Comment by marcfeuermann** [comment]
Fixed for all 3 families.
