### ISSUE TITLE
elongator transcription  annotations back PTN001011041/PTN000307203

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3313]
I'm absolutely sure that all of these annotations were purged for the matrix paper, but:

elp2 | elongator complex WD repeat protein Elp2 (predicted) |   | regulation of transcription by RNA polymerase II |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001011041 SGD:S000003432 | elongator complex protein 2 pthr44111 | protein |   | PMID:21873635 | 20170228

**Comment by ValWood** [comment]
and elp4	
IBA with PTN000307203 , Q96EB1 , S000006022

**Comment by marcfeuermann** [comment]
Propagation removed in both families.
