### ISSUE TITLE
interspecies protein binding - exported from IntAct

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-annotation#3314]
This came up in the annotation call today.

IntAct exports all binary interactions as simple lines of syntax:

ProtA `protein binding` with/from:ProtB

irrespective of taxon. The binary interactions can be between proteins from different species as we only capture what was done in the experiment, not author intent. And there are MANY inter-species experiments (e.g. human protein tested against mouse library or in non-human cell line, e.g. COS).

We can't map the species of ProtB to the species of ProtA in our data model and it's pretty hard to implement automatic ortholog mapping for all the combination we are annotating. 

Also: in many cases these are true interactions (host-pathogens, symbionts etc...). We cannot flag if the interaction is physiological or not.

Tagging @noedelta (IntAct developer)

**Comment by pgaudet** [comment]
In GO this is not allowed, only physiological interspecies interactions are allowed. 
What IntAct can do is to use the ID of the interacting partner in the 'with' column, since this is about the experiment. 

@sandraorchard I am closing this, please reopen if needed.
