### ISSUE TITLE
PANTHER:PTN000332517 NOT mediator

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3315]
Mediator complex is well described, uri1 isn't a component of mediator

uri1 | unconventional prefoldin chaperone involved protein complex assembly Uri1 (predicted) |   | mediator complex |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000331217 TAIR:locus:2165680 more... | mediator of rna polymerase ii transcription subunit 10 pthr13345 | protein |   | PMID:21873635 | 20200808

**Comment by tberardini** [comment]
Not sure what I need to do here.  Please clarify.

**Comment by ValWood** [comment]
I don't think TAIR:locus:216568 is a mediator subunit?

**Comment by tberardini** [comment]
https://www.arabidopsis.org/servlets/TairObject?accession=locus:2165680

Still confused. It definitely looks like this is a mediator subunit. From http://doi.org/10.1105/tpc.109.066910:

> "...med10a(At5g41910, SALK_115673)..."

Also in UniProt

https://www.uniprot.org/uniprot/Q9FHZ2

**Comment by ValWood** [comment]
OK, then this seems to be a panther issue.

Yeast uri1 and TAIR:locus:2165680 are in different families

**Comment by marcfeuermann** [comment]
Fungal node PTN002491435 contains many recent duplication events with gain/loss of function ( (including S. pombe uri1 and nut2). I've blocked any propagation within this node.
