### ISSUE TITLE
PANTHER:PTN000255549   PTN000429848 nbs1/ rad50 telomere capping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3316]
nbs1 | Mre11 complex subunit Nbs1 |   | telomere capping |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000255549 UniProtKB:O60934 FB:FBgn0261530 | nibrin-related pthr12162 | protein |   | PMID:21873635 | 20170228

I'm *pretty sure* MRe11 complex isn't involved in telomere capping.

@hattrill 
telomere capping
A process in which telomeres are protected from degradation and fusion, thereby ensuring chromosome stability by protecting the ends from both degradation and from being recognized as damaged DNA. May be mediated by specific single- or double-stranded telomeric DNA binding proteins.

(it does have a role in telomere integrity/maintenence, but not in actual cappng AFAIK)

**Comment by ValWood** [comment]
also rad50
rad50	
IBA with locus:2045437 , FBgn0034728 , Q92878 , PTN000429848

has a role in telomere maintenance (via recombination, not capping)

**Comment by hattrill** [comment]
changed both rad50 and nb1s annotations to telomere maintenance
Aren't due a release until Dec, so Paint may want to block this.

**Comment by marcfeuermann** [comment]
Both families reviewed.
