### ISSUE TITLE
PTN000072560  mug14 spectrin binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3317]
Please remove

mug14	↑is_a GO:0030507	
spectrin binding
IBA with PTN000072560, P35612 , P35611

There isn't really a spectin ortholog in yeast, although ere are spectrin repeats. I'm not really sure what this annotation means

 ideally binding terms would not generally be transferred.

**Comment by marcfeuermann** [comment]
Propagation of term removed.
