### ISSUE TITLE
PTN000328844 NOT DNA repair

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3319]
SPAC2G11.04
IBA with FBgn0086683 , PTN000328844 , locus:2028130

This one might be a panther problem.
The fly ortholog of SPAC2G11.04 isn't  FBgn0086683 it's FBgn0051550

SPAC2G11.04 is a splicing factor based on human annotation, I believe this because  of the species distribtion

**Comment by ValWood** [comment]
and the family name!

SPAC2G11.04 | RNA-binding protein, G-patch type, splicing factor 45 ortholog (predicted) |   | DNA repair |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000328844 FB:FBgn0086683TAIR:locus:2028130 | splicing factor 45 spf45 pthr13288 | protein |   | PMID:21873635 | 20180410
There could be a fly annotation problem here, worth checking @hattrill

**Comment by hattrill** [comment]
PMID:17154718 characterizes it as a "the Drosophila melanogaster protein is bifunctional, with independent functions in DNA repair and splicing." and says that "The sequence of the SPF45 protein is significantly conserved, yet functional studies have identified it as a splicing factor in animal cells and as a DNA-repair protein in plants." Looks like there is some evolutionary shenanigans goiung on here, so buyer beware!

**Comment by hattrill** [comment]
(and Panther gives the only ortholog prediction for SPAC2G11.04 out of the 15 other ortholog algorithms used in DIOPT.)

**Comment by ValWood** [comment]
what is the reference for the plant involvement of SPF45 in DNA repair - I don't believe it ;)

**Comment by hattrill** [comment]
here's one with an annotation ......PMID:8479917
and a Toxoplasma gondii PMID:12135477 one.

haven't looked at them btw

**Comment by ValWood** [comment]
Well the toxoplasema  one has this statemttn int he abstract
When an Escherichia coli mutant lacking ruvC endonuclease and recG helicase was transformed with TgDRE cDNA, a significant increase in resistance to DNA-damaging agents, such as UV light and mitomycin C, was observed.

which is the only nod to repair!

and the other one is a complementation experiment. So I think both of. these can be ignored....

**Comment by marcfeuermann** [comment]
Lets remove the propagation of this term.
