### ISSUE TITLE
PANTHER:PTN000464223 elc1 transcription elongation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3320]
elongin is involved directly in elongation, not regulation

elc1 | elongin C Elc1 (predicted) |   | positive regulation of transcription elongation from RNA polymerase II promoter |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000464223 RGD:620658 | elongin-c pthr20648 | protein |   | PMID:21873635 | 20170228

**Comment by marcfeuermann** [comment]
Regulation term removed.
