### ISSUE TITLE
PANTHER:PTN000464223 elc1 NOT ubiquitin-protein transferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3321]
elc1 | elongin C Elc1 (predicted) | contributes_to | ubiquitin-protein transferase activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000464223 SGD:S000005967 | elongin-c pthr20648 | protein |   | PMID:21873635 | 20170228

This one is a substrate adaptor

**Comment by marcfeuermann** [comment]
Corrected.
