### ISSUE TITLE
PANTHER:PTN001582398    EKC/KEOPS complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3322]
This is a tRNA modifiying enzyme.  These are indirect, and/or out of data science

pcc1 | EKC/KEOPS complex subunit Pcc1 (predicted) |   | positive regulation of transcription from RNA polymerase II promoter by pheromones |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001582398 SGD:S000028512 | ekc/keops complex subunit pcc1 family member pthr31283 | protein |   | PMID:21873635 | 20190410

  | pcc1 | EKC/KEOPS complex subunit Pcc1 (predicted) |   | positive regulation of transcription by RNA polymerase II |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001582375 SGD:S000028512 | ekc/keops complex subunit pcc1 family member pthr31283 | protein |   | PMID:21873635 | 20190410

**Comment by marcfeuermann** [comment]
Done.
