### ISSUE TITLE
PANTHER:PTN000548991 not DNA catabolic process, exonucleolytic

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3329]
At least for

eri1 | double-strand siRNA ribonuclease Eri1 |   | DNA catabolic process, exonucleolytic |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000548991 WB:WBGene00000797 | 3'-5' exonuclease eri1-related pthr23044 | protein |   | PMID:21873635 | 20170228

which is involved in RNAi and is a ribonuclease

**Comment by marcfeuermann** [comment]
Family has been updated.
