### ISSUE TITLE
new mapping: Glycosyl transferase, family 1 InterPro  IPR001296 -> GO:0016757 glycosyltransferase

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#3330]
I propose mapping http://www.ebi.ac.uk/interpro/entry/InterPro/IPR001296/ to

```
id: GO:0016757
name: transferase activity, transferring glycosyl groups
namespace: molecular_function
alt_id: GO:0016932
def: "Catalysis of the transfer of a glycosyl group from one compound (donor) to another (acceptor)." [GOC:jl, ISBN:0198506732]
subset: goslim_chembl
subset: goslim_drosophila
subset: goslim_generic
subset: goslim_yeast
synonym: "glycosyltransferase activity" EXACT []
synonym: "transferase activity, transferring other glycosyl groups" NARROW []
synonym: "transglycosidase activity" EXACT []
synonym: "transglycosylase activity" EXACT []
xref: EC:2.4
is_a: GO:0016740 ! transferase activity
```

based on:
http://www.cazy.org/GT1.html

(most are to 2.4.1.- but some to 2.4.2.-)

Also propose the same mapping for 

http://www.ebi.ac.uk/interpro/entry/pfam/PF00534/

I'm not an expert, I may miss some nuance. Not sure why mappings were removed for other GTs, e.g.
#2788

**Comment by sjm41** [comment]
@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

**Comment by typhainepl** [comment]
Hi, 
The annotation of IPR001296 with this GO term looks sensible to me. I've updated the entry, the changes will be visible in the next InterPro release.

**Comment by cmungall** [comment]
Thank you!
