### ISSUE TITLE
InterPro2GO: Adenylate kinase isoenzyme 6 (IPR020618)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3332]
From the description and given refs, I think you can add 'ATPase activity' (GO:0016887) to this entry.

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi!
Thank you very much. I added the term to this entry.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!
