### ISSUE TITLE
InterPro2GO: Add 'ATPase activity' to TRiC/CCT complex subunit entries?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3333]
I think 'ATPase activity (GO:0016887)' can be added to all of the following entries (related to subunits of the TRiC/CCT complex). ATPase/ATP hydrolysis is already mentioned in most of the entry descriptions, and 'ATP binding' is associated with all but one entry.  (see PMC5441784 for a recent account of the ATPase activity of these subunits)

IPR002194:Chaperonin TCP-1, conserved site
IPR002423:Chaperonin Cpn60/TCP-1 family
IPR012715:T-complex protein 1, alpha subunit
IPR012716:T-complex protein 1, beta subunit
IPR012719:T-complex protein 1, gamma subunit
IPR012717:T-complex protein 1, delta subunit
IPR012722:T-complex protein 1, zeta subunit
IPR012720:T-complex protein 1, eta subunit
IPR012721:T-complex protein 1, theta subunit

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. You are right, I have added the term to those entries. The changes will be seen in the next InterPro release (83.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
