### ISSUE TITLE
InterPro2Go - GroES chaperonin (IPR020818)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3334]
I think you can add "ATP binding (GO:0005524)" and ''ATPase activity (GO:0016887)" to this entry.

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Thank you very much. I added the terms to this entry.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!
