### ISSUE TITLE
InterPro2GO: Heat shock protein 70 family (IPR013126)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3335]
I think you can add "ATP binding (GO:0005524)" and ''ATPase activity (GO:0016887)" to this entry.

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have added those terms, which will be visible in the next InterPro release (83.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks!

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have changed the term for the new one. It will be available in Interpro 88.0.
Best,
Sara
