### ISSUE TITLE
InterPro2GO: Heat shock protein Hsp90 family (IPR001404)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3336]
I think you can add "ATP binding (GO:0005524)" and ''ATPase activity (GO:0016887)" to this entry.
See PMID: 28429788 for recent review.

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven, 
Thank you very much. I added ATPase activity to this entry, ATP binding was already included. The changes will be seen in the next release.
Best regards,
Sara

**Comment by sjm41** [comment]
Great, thanks!
