### ISSUE TITLE
InterPro2GO: Add 'ATPase activity' to SMC subunit entries?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3337]
I think 'ATPase activity (GO:0016887)' and 'ATP binding (GO:0005524)' can be added to all of the following entries (related to subunits of the SMC complexes). 

IPR024704:Structural maintenance of chromosomes protein                               
IPR028468:Smc1, ATP-binding cassette domain	
IPR027120:Smc2, ATP-binding cassette domain
IPR041741:Structural maintenance of chromosomes 3, ABC domain, eukaryotic                               	
IPR041738:Structural maintenance of chromosomes 4, ABC domain, eukaryotic                  
IPR027131:Structural maintenance of chromosomes protein 5                               	
IPR027132:Structural maintenance of chromosomes protein 6      

Structural maintenance of chromosomes (SMC) proteins, a family of conserved ATPases. Harvey SH, Krien MJ, O'Connell MJ. Genome Biol. 3, REVIEWS3003, (2002). (PMID: 11864377)
Carter, S.D., Sjögren, C. (2012). The SMC complexes, DNA and chromosome topology: right or knot?  Crit. Rev. Biochem. Molec. Biol. 47(1): 1--16. (PMID: 21923481)

@EBI-Hsinyu
@lsw26
@sarach06 
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven,
Many thanks for this. I added those terms to the entries, and the changes will be visible in the next InterPro release (83.0).

Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
