### ISSUE TITLE
PTN000204884 /  PTN000337444/ PTN000428162 mixed up cytosolic and mitochondrial ribosomal proteins

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3339]
This is  a mitochondrial ribosomal protein?

GO:0000462 | maturation of SSU-rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)

mrps18 |   | IBA with PTN000204884 , S000003727 , S000000627 |   | Gaudet P et al. (2011)

**Comment by ValWood** [comment]
Also

mrps18 | ↑part_of GO:0000028 | ribosomal small subunit assembly | IBA with S000000627 , PTN000204884 , S000003727 , 62025 , P62263

**Comment by ValWood** [comment]
mrpl22 |   | IBA with PTN000337444 , P61175 |   | Gaudet P et al. (2011)

not 
GO:0042255 | ribosome assembly

**Comment by ValWood** [comment]
SPBC83.06c |   | IBA with PTN000428162 , S000007224 |  
I believe this to be a ribosomal protein.

**Comment by pgaudet** [comment]
- [ ] PTN000204884 
- [ ] PTN000337444
- [ ] PTN000428162

**Comment by pgaudet** [comment]
PAINT offline

**Comment by marcfeuermann** [comment]
I've reviewed all 3 families. Indeed, some cleaning was necessary.
