### ISSUE TITLE
PTN000184007/ PTN000391312 /PTN000242048 mitochondrial ribosomal proteins

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3340]
Please remove ribosome large subunit  complex assembly term. These are part of the complex- because these are mitochondrial, I don't think they have a role in their own assembly (some cytosolic ribosomal proteins are involved in assembly, but these are a bit of a mess, I will follow up pon that later)

mrpl19 |   | IBA with S000002826 , S000000780 , P0A7J7 , PTN000184007 |   | Gaudet P et al. (2011)
mrpl39 |   | IBA with P0A7N9 , PTN000391312 |   | Gaudet P et al. (2011)
mrpl7 |   | IBA with P62399 , S000006306 , P62913 , PTN000242048 , S000003317

**Comment by ValWood** [comment]
It seems that PAnther is not distinguishing ribosomal and cytosolic ribosomes in the same family

**Comment by marcfeuermann** [comment]
All 3 families have been corrected.
