### ISSUE TITLE
ribosome biogenesis and ribosomal subunits

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3341]
I don't think these can be easily transferred.

I have seen quite a few papers where one of the paralogs is involved in assembly, and the other one in translation, they areswitched over at some point during assemblyIIRC.

I will try to locate some  papers. Anyway the paralogs in question are more similar to each other than to the orthologs in other species (possibly only the expression is different).

**Comment by pgaudet** [comment]
@ValWood what genes are you talking about ? Or are you talking about the GO terms themselves ?

**Comment by ValWood** [comment]
Of ten with the ribosomal proteins there are 2 paralogs. I have seen papers describing where only one of the paralogs is involved in  ribosome biogenesis, so  did not feel immediately comfortable with these annotations. 
  I would need to check this though and I don't know where to start so I'll close this and  keep the inferences until we have time to do this pathway (It isn't high priority for PomBAse because hardly anyone works on it)

**Comment by ValWood** [comment]
i.e both of a pair of paralogs would be  implicated in biogenesis. It's not a big deal though at the moment.
