### ISSUE TITLE
PTN001114632/PTN000131749 not "regulation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3342]
These should not be 'regulation' these are the  "carriers"

	iws1	↑regulates GO:0010793	
regulation of mRNA export from nucleus
IBA with Q96ST2 , PTN001114632

	crm1	↑regulates GO:0046825	
regulation of protein export from nucleus
IBA with PTN001114632 , MGI:2144013

**Comment by ValWood** [comment]
and

msn5 | karyopherin/importin beta family nuclear import/export signal receptor (predicted) |   | regulation of protein export from nucleus |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000131749MGI:MGI:2144013 | exportin 1/5 pthr11223 | protein

**Comment by marcfeuermann** [comment]
Regulation terms have been removed.
