### ISSUE TITLE
PTN000373411 rmn1, not nucleocytoplasmic export

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3343]
I suspect this one is pANTHER mapping the incorrect ribosomal protein.

	rmn1	↑regulates,positively_regulates GO:0046833	
positive regulation of RNA export from nucleus
IBA with FBgn0002044 , PTN000373411

In fission yeast rmn1 is a member of the NURS complex, involved in meiotic chromosome pairing and heterochromatin assembly, not related to nucleocytoplasmic transport

**Comment by ValWood** [comment]
Hmm, it is the correct ortholog, 
http://flybase.org/reports/FBrf0212671.html

There is. agenetic link to export factors in F.Y too, but  these are more recent interpretations
https://pubmed.ncbi.nlm.nih.gov/24713849/

**Comment by marcfeuermann** [comment]
Anyway, there are very few primary annotations, so I've cleaned the family with minimal propagation.
