### ISSUE TITLE
PTN000012880 / PTN000030137 NOT mitochondrial ATP synthesis coupled proton transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3346]
mitochondrial ATP synthesis coupled proton transport

cox4 |   | IBA with PTN000012880 , WBGene00000371 |   | Gaudet P et al. (2011)

cyt1 |   | IBA with PTN000030137 , WBGene00000869

@vanaukenk  could you take a look at the primary annotations?

**Comment by marcfeuermann** [comment]
PAINT propagation removed.
