### ISSUE TITLE
PTN000150497 positive regulation of oxidative phosphorylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3349]
pgk1 | ↑positively_regulates,regulates GO:1903862 | positive regulation of oxidative phosphorylation | IBA with ZDB-GENE-040426-2711 , PTN000150497

seems an odd annotation for glycolysis pathway (causally upstream?)

**Comment by marcfeuermann** [comment]
Indeed. Propagation removed.
