### ISSUE TITLE
PTN000835262 not respiratory electron transport chain

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3350]
SPAC20G8.04c |   | IBA with PTN000835262 , ZDB-GENE-040912-168 |  

this is
mitochondrial electron transfer flavoprotein-ubiquinone oxidoreductase 
it's not respiratory electron transport chain

@sabrinatoro  could you check this one out?

**Comment by marcfeuermann** [comment]
Corrected.
