### ISSUE TITLE
PTN000549861 pls remove from SPAC29A4.05 (calmodulin paralogs)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3355]
This is an actin associated  (Myosin light chain) paralog of cam1 (calmodulin)

GO:0000226 | microtubule cytoskeleton organization | IBA with cam1 , FBgn0000253 , PTN000549861 , S000000313 , WBGene00000552

and

GO:0019722 | calcium-mediated signaling | IBA with 2259 , 2257 , 2258 , PTN000549861

**Comment by marcfeuermann** [comment]
Updated.
