### ISSUE TITLE
PTN000447085 SOME NOT microtubule nucleation by interphase microtubule organizing center

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3357]
remove from
microtubule nucleation by interphase microtubule organizing center

alp4	
IBA with alp16 , gfh1 , PTN000447085
alp6	
IBA with gfh1 , PTN000447085 , alp16

These are MTOC speciifc.
In general if pombe has paralogs  in a family and they are not annotated to the same process, that is intentional

**Comment by marcfeuermann** [comment]
Corrected.
