### ISSUE TITLE
PTN000195421  positive regulation of microtubule polymerization?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3358]
alp41	↑regulates,positively_regulates GO:0031116	
positive regulation of microtubule polymerization
IBA with PTN000195421 , P36404 , Q2TA37	

I don't think this necessarily regulates polymerization (it will affect polymerization if mutated  because it affects tubulin availability)

**Comment by marcfeuermann** [comment]
Fixed.
