### ISSUE TITLE
PTN001997934  regulation of /attachment of spindle microtubules to kinetochore

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3359]
dad2/SPAC1805.07c

GO:0051987 | positive regulation of attachment of spindle microtubules to kinetochore | IBA with PTN001997934 , S000001791 | Gaudet P et al. (2011) | 8

dad2 should be "attachment of spindle microtubules to kinetochore"  not 'regulates',
DASH complex is directly involved in this process?

- | GO:0031116 | positive regulation of microtubule polymerization | IBA with S000001791 , PTN001997934 | Gaudet P et al. (2011)

also Is this one correct?
Should it be depolymerization, if anything?

**Comment by ValWood** [comment]
tagging @edwong57

**Comment by marcfeuermann** [comment]
I totally agree. Corrected.
