### ISSUE TITLE
PTN002166039 not spindle assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3360]
Please remove
SPAC17G8.15/wip1
GO:0051225 | spindle assembly | IBA with ZDB-GENE-100922-200 , PTN002166039

@sabrinatoro  can you look into this one, perhaps it is just a phenotype?
wip1 is CENP-W and is involved in CENP-A containing nucleosome assembly, so it will indirectly affect spindle assembly

**Comment by sabrinatoro** [comment]
@ValWood 
I did review this annotation, and indeed, this annotation was done based on a phenotype. 
I removed it (so it will take a little bit of time before the change makes its way through the whole pipeline).

**Comment by marcfeuermann** [comment]
Annotation propagation removed.
