### ISSUE TITLE
PTN000902162, PTN000326738 not All  mitochondrial fission

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3361]
msp1	

GO:0000266 | mitochondrial fission | IBA with A0A1D8PKC9 , O00429 , locus:2006777 , WBGene00001093 , Q8S944 , S000003924 , dnm1 , MGI:1921256 , FBgn0026479 , PTN000902162 , Q8LFT2 | Gaudet P et al. (2011)

is involved in fusion not fission

ditto

vps1	
GO:0000266 | mitochondrial fission | IBA with A0A1D8PKC9 , Q8S944 , dnm1 , O00429 , S000003924 , FBgn0026479 , Q8LFT2 , MGI:1921256 , WBGene00001093 , locus:2006777 , PTN000902162

I think these derive from the similarity between these  dynamics, some are fission, some are fusion

In general if pombe has paralogs  in a family and they are not annotated to the same process, that is intentional

this one is just odd, I would not propagate this:

fis1	↑is_a GO:0043653	
mitochondrial fragmentation involved in apoptotic process
IBA with Q9Y3D6 , 1306668 , PTN000326738

**Comment by marcfeuermann** [comment]
Both families have been re.annotated.
