### ISSUE TITLE
PTN000170085  / dynamin family protein polymerization involved in mitochondrial fission

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3362]
I don't know which tracker to put this one on!

1) Some are not true for fission yeast, some are fusion.

2) This term should not exist
(this polymerization  is just the 'mechanism' for dynamin in fission  history https://github.com/geneontology/go-ontology/issues/12639)
https://en.wikipedia.org/wiki/Dynamin

dnm1 | GO:0003374 | dynamin family protein polymerization involved in mitochondrial fission | IBA with O00429 , PTN000170085 | Gaudet P et al. (2011) | 3
msp1 |   | IBA with O00429 , PTN000170085 | Gaudet P et al. (2011)
vps1 |   | IBA with PTN000170085 , O00429 | Gaudet P et al. (2011)

**Comment by marcfeuermann** [comment]
This term (and related ones) still exist but there is no PAINTing to it anymore.
