### ISSUE TITLE
PTN000395816 mitochondrion morphogenesis (challenge: does not exist)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3363]
mic60 is involved in cristae formation
obviously if you interfere with cristae formation you affect shape of mitochondria, but this isn't an evolved process to regulate shape- it's phenotype.  The shape 'is what it is'...(autonomously based on the physical constraints, it isn't 'programmed' like cell-shape)

GO:0070584 | mitochondrion morphogenesis |IBA with WBGene00020511 , WBGene00012315 , PTN000395816 , FBgn0019960

In fact, I don't know of nay 'real' mitochondrial morphogenesis, so I challenge the existence of this term.
_S. cerevisiae_ has 4 annotations  2  proteins (all phenotypes)
_S. pombe_ has no annotations

**Comment by marcfeuermann** [comment]
This term is indeed vague and does not bring much, so yes, I removed the PAINT annotation.

**Comment by pgaudet** [comment]
You requested this term here: https://github.com/geneontology/go-ontology/issues/6031

It seems to me mitochondrion morphogenesis is a phenotype of mitochondrial organization .. ?
