### ISSUE TITLE
PTN000277108  NOT mitochondrial outer membrane translocase complex assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3365]
I don't think this is correct for Tom20, because T0m20 is itself a member of 
mitochondrial outer membrane translocase complex

GO:0070096 | mitochondrial outer membrane translocase complex assembly | IBA with PTN000277108 , S000003314 | Gaudet P et al. (2011) | 6

@srengel 
@edwong57

**Comment by edwong57** [comment]
I'll take a look.

**Comment by edwong57** [comment]
I cleaned up an annotation that SGD made to this term for TOM20

**Comment by marcfeuermann** [comment]
Same as ticket #3366. Annotation removed.
