### ISSUE TITLE
PTN000246311  not mitochondrial respiratory chain complex III assembly/ PTN000312316

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3366]
qcr7 (ubiquinol-cytochrome-c reductase complex subunit 6)

because Qcr7 is itself a member of
mitochondrial respiratory chain complex III assembly
(although we refer to them inconsistently in GO, I think I opened a ticket about this somewhere............)

GO:0034551 | mitochondrial respiratory chain complex III assembly | IBA with PTN000246311 , FBgn0039576 , S000002937

**Comment by ValWood** [comment]
also
GO:0034551 | mitochondrial respiratory chain complex III assembly | IBA with PTN000312316 , S000003415 | Gaudet P et al. (2011) | 6

**Comment by marcfeuermann** [comment]
Two more examples of complex members annotated to "complex assembly". PAINT propagation removed in both families.
