### ISSUE TITLE
PTN000423706 not mitochondrion organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3367]
This seems an odd inference for  frataxin
http://paint.pombase.kmr.nz/gene/SPCC1183.03c

GO:0007005 | mitochondrion organization | IBA with MGI:1096879 , PTN000423706

frataxin is involved in iron-sulfur cluster assembly, not really in mitochondrion organization (although it indirectly affects it)

**Comment by marcfeuermann** [comment]
This is indeed very indirect. Annotation propagation has been removed.
