### ISSUE TITLE
PTN000129548, PTN000567445, PTN000567445, PTN000566947, PTN000397856, PTN000567445, PTN000328844, PTN000298794

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3370]
There is little, if any alternative splicing in fission yeast and some of these gene products are known to be involved in canonical splicing. Others seem to be sporadic hist to RNA binding proteins. I would be inclined to remove all of these inferences.

GO:0000381 | regulation of alternative mRNA splicing, via spliceosome | 

bpb1 | 
IBA with FBgn0022984 , 620921 , 621459 , WBGene00006423 , PTN000129548 , FBgn0264491 , Q07666 | Gaudet P et al. (2011) | 10

mrd1 | IBA with Q13247 , FBgn0260944 , FBgn0030479 , FBgn0028554 , Q9BWF3 , FBgn0265298 , MGI:98284 , FBgn0004587 , PTN000567445 , MGI:1100865 , Q8WXF0 , P0DJD3 , FBgn0011305 , FBgn0283477 | Gaudet P et al. (2011)

prp24 |   | IBA with FBgn0260944 , FBgn0004587 , Q8WXF0 , Q9BWF3 , FBgn0030479 , P0DJD3 , PTN000567445 , MGI:98284 , MGI:1100865 , FBgn0011305 , FBgn0283477 , Q13247 , FBgn0265298 , FBgn0028554 | Gaudet P et al. (2011)

rbm8 |   | IBA with Q9Y5S9 , PTN000566947 | Gaudet P et al. (2011)

rns1 |   | IBA with Q15287 , locus:2017948 , PTN000397856 | Gaudet P et al. (2011)

tcg1 |   | IBA with P0DJD3 , Q9BWF3 , FBgn0260944 , Q13247 , FBgn0011305 , FBgn0283477 , FBgn0030479 , Q8WXF0 , MGI:1100865 , FBgn0265298 , PTN000567445 , FBgn0028554 , FBgn0004587 , MGI:98284 | Gaudet P et al. (2011)

usp107 |   | IBA with P49756 , PTN000428218 | Gaudet P et al. (2011)

SPAC222.18 |   | IBA with MGI:98284 , FBgn0004587 , FBgn0030479 , FBgn0265298 , P0DJD3 , MGI:1100865 , Q8WXF0 , Q9BWF3 , FBgn0028554 , FBgn0260944 , PTN000567445 , Q13247 , FBgn0283477 , FBgn0011305 | Gaudet P et al. (2011)

SPAC2G11.04 |   | IBA with PTN000328844 , FBgn0086683 | Gaudet P et al. (2011)

SPBC1539.02 |   | IBA with PTN000298794 , WBGene00004896 | Gaudet P et al. (2011)

**Comment by marcfeuermann** [comment]
Many weird annotations and all these families have been cleaned.
