### ISSUE TITLE
PTN002768818 NOT regulation of mRNA splicing, via spliceosome (at least for csx1)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3371]
S. pombe csx1 doesn't appear to have a role in splicing

GO:0048024 | regulation of mRNA splicing, via spliceosome | IBA with MGI:1915285 , PTN002768818

It has a role in mRNA stability (localization nucleocytoplasmic stress granule), but that is post-splicing.

This could be an inference problem becuse there are very close  related splicing components

**Comment by marcfeuermann** [comment]
Correction done.
