### ISSUE TITLE
PTN000275634  not mRNA cis splicing, via spliceosome |

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3372]
cbc1

GO:0045292 | mRNA cis splicing, via spliceosome | IBA with S000004732 , Q09161 , PTN000275634 | Gaudet P et al. (2011) | 140

@srengel @edwong57  this is 
nuclear cap binding complex subunit.
The splicing annotation is really, really old (1999) based on IPI. I think  it should likely be removed?

**Comment by marcfeuermann** [comment]
Removed from PAINT annotation.
