### ISSUE TITLE
PTN001295889 SDF2 and SDF2L1 are not mannosyltransferases

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3375]
Can you review PTN001295889? (and block propagation in the meantime) 

DOLICHYL-PHOSPHATE-MANNOSE--PROTEIN MANNOSYLTRANSFERASE (PTHR10050)

The tree is stucking in  co-chaperone/unfolded protein binders  SDF2 and SD
F2L1 and their orthologs (FBgn0037312) and is propagating:
GO:0004169 dolichyl-phosphate-mannose-protein mannosyltransferase activity
GO:0035269 protein O-linked mannosylation
to them. 
https://www.alliancegenome.org/gene/HGNC:9202#orthology
https://www.alliancegenome.org/gene/HGNC:10675#orthology
are useful to help separate them.

![Screenshot 2020-10-22 at 14 41 37](https://user-images.githubusercontent.com/11865746/96880850-8f218580-1475-11eb-8c31-9d281c51c40b.png)

**Comment by hattrill** [comment]
REF: PMID: 28597544

**Comment by pgaudet** [comment]
No action needed in PAINT ?

**Comment by hattrill** [comment]
Sorry, closed by mistake. Fix still needed by the looks of it.

**Comment by hattrill** [comment]
Can this be fixed by March release? Thanks

**Comment by hattrill** [comment]
Hi @marcfeuermann @pgaudet can I put in a plug for this? Thanks

**Comment by marcfeuermann** [comment]
I've got a look at this one. The family is full of duplications with loss of function and neo-functionalization. There are no nodes specific to each function, pomt and sdf2 are mixed up and it is impossible to discriminate which protein is doing what. So, even if we have a lot of evidences, I decided to remove all PAINT annotations (except the RE CC). This is probably a non-PAINTable case.  @pgaudet @huaiyumi ?

**Comment by hattrill** [comment]
Hi @pgaudet Reopened this and added high priority - see I somehow didn't reopen it at the time.

**Comment by pgaudet** [comment]
I fixed this again. The tree looks odd, I dont understand why the SDF2 sequences are inserted a bit randomly everywhere (see attached screenshot). I added the Panther16 label to review it again when we get the new trees. 

<img width="773" alt="image" src="https://user-images.githubusercontent.com/4782928/114863772-7aa0c300-9df0-11eb-9013-253a08dee9ca.png">

**Comment by hattrill** [comment]
Thanks!

**Comment by pgaudet** [comment]
For info: I actually added GO:0004169 dolichyl-phosphate-mannose-protein mannosyltransferase activity and 
GO:0035269 protein O-linked mannosylation back at the root. I blocked the node I shown above and removed a few more.

**Comment by ValWood** [comment]
Close?

**Comment by ValWood** [comment]
Closing @hattrill  reopen, or open new for outstanding.

**Comment by pgaudet** [comment]
Note than in Panther19 the chaperones SDF2 and SD, F2L1 and their orthologs (FBgn0037312) are gone. Re-annotaed the tree.
