### ISSUE TITLE
InterPro2GO: 26S proteasome regulatory subunit P45-like (IPR005937)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3376]
Description of this entry says "This family includes the six paralogous AAA-ATPases, termed Rpt1-Rpt6, of the 19S component base".
But the current GO MF term is only "hydrolase activity (GO:0016787)"

If this domain is specific to the Rpt subunits (true for Drosophila, haven't checked other species), then the MF term could be improved to "proteasome-activating ATPase activity (GO:0036402)".

Do you mind checking?

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I have checked and improved the term as you mentioned. 
Best regards,
Sara

**Comment by sjm41** [comment]
Wonderful - thanks!
