### ISSUE TITLE
UniProtKW/SUB-CELL and InterPro for SDF2-like proteins

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3377]
Q99470
Q9HCN8
Q9VNA3
are getting incorrect annotations from UniProtKB-KW, UniProtKB-SubCell and InterPro.

PMID:28597544: 'SDF2 and SDF2L1 associate with ERdj3 and act as components in the BiP chaperone cycle to prevent the aggregation of misfolded proteins.' 
They are not enzymes and are ER resident proteins, not membrane or extracellular proteins. 
Additional detail here: https://github.com/geneontology/go-annotation/issues/3375

Q99470
UniProtKB-KW:UniProtKB-SubCell: extracellular region
InterPro: membrane (IPR016093|IPR036300)

Q9HCN8
InterPro: membrane (IPR016093|IPR036300)

Q9VNA3
UniProtKB-KW: transferase activity
UniProtKB-KW: transferase activity, transferring glycosyl groups
InterPro: membrane (IPR016093|IPR036300)

InterPro issue associated with MIR motif/Mir domain superfamily association with membrane.

@EBI-Hsinyu
 @lsw26
 @sarach06 
@Alexbateman1 
@typhainepl

@sylvainpoux 

Thanks

**Comment by sylvainpoux** [comment]
Hi Helen,

we (unfortunately) cannot do anything on the Uniprot side:

Q99470: the signal sequence is both predicted and proven experimentally (PubMed=25944712) and there are good chances that this protein is secreted

Q9HCN8: we cannot do anything for this InterPro prediction

Q9VNA3: the erroneous annotation is coming from submitters, not from an UniProt curator

Thanks

Sylvain

**Comment by hattrill** [comment]
> Hi Helen,
> 
> we (unfortunately) cannot do anything on the Uniprot side:
> 
> Q99470: the signal sequence is both predicted and proven experimentally (PubMed=25944712) and there are good chances that this protein is secreted

-I am a bit confused: PubMed=25944712 is a paper titled 'N-terminome analysis of the human mitochondrial proteome"

https://pubmed.ncbi.nlm.nih.gov/28597544/ "Both human SDF2 and SDF2L1 are ER‐resident proteins Human SDF2 and SDF2L1 contain three MIR domains and share 67% amino acid identity (Fig. 1A). SDF2L1 is an ER‐resident protein with an ER retrieval signal (HDEL) at its C‐terminus, whereas murine SDF2 was initially believed to be a secretory protein because the HAEL tetrapeptide at its C‐terminus does not match the typical ER localization signal (Hamada et al. 1996). To analyze the intracellular location of human SDF2 and SDF2L1, an HA‐tag was introduced upstream of the C‐terminal tetrapeptides of SDF2 and SDF2L1. Pulse‐chase analysis showed that both SDF2 and SDF2L1 were not secreted into the culture medium during a chase period of 2 h (Fig. 1B, lanes 7–10). Immunostaining of SDF2‐HA and SDF2L1‐HA showed that they colocalized with the ER marker PDI but did not colocalize with the cis‐Golgi marker GM130 (Fig. 1C). Therefore, we conclude that both SDF2 and SDF2L1 are retained in the ER."


> 
> Q9HCN8: we cannot do anything for this InterPro prediction

(InterPro is tagged here too)


> 
> Q9VNA3: the erroneous annotation is coming from submitters, not from an UniProt curator

These are from the KW pipeline - who is responsible for them then?

![Screenshot 2020-10-23 at 10 31 33](https://user-images.githubusercontent.com/11865746/96987535-0e1cc980-151b-11eb-96a7-ceb6079df92f.png)



> 
> Thanks
> 
> Sylvain

**Comment by sylvainpoux** [comment]
Hi Helen,

Q99470:  sorry, I skipped that there is some experimental information (https://pubmed.ncbi.nlm.nih.gov/28597544/). May I ask you to submit an user request for this entry (https://www.uniprot.org/update?entry=Q99470)? We will curate this paper.

Q9VNA3: you should contact EMBL and see if they can modify annotation. We have no control on this.

Thanks

Sylvain

**Comment by hattrill** [comment]
Thanks @sylvainpoux - I will submit  the request (I've done the GO, a I wanted it for an ISS ti D.mel, but there is other info there for UnIProt, so will do)

Is EMBL the contact for all KWs? We should probably add a point to contact to the contact yaml.

**Comment by sylvainpoux** [comment]
For KW derived from automatic annotation, maybe ask Alex (@alexsign) from GOA, he probably knows more regarding automatic annotation pipelines from EMBL submissions
Thanks
Sylvain

**Comment by alexsign** [comment]
The GOA supports mapping between GO terms and UniProt KW. The requests to add, remove or change it, comes from the UniProt curators and @pgarmiri can update them. There is an automatic annotations pipeline that runs on this data and creates GO annotations in GOA. It is subject usual checks and taxon constrains.

**Comment by hattrill** [comment]
Thanks, @alexsign and @sylvainpoux.
@pgarmiri could you have a look at this for me? Thanks

**Comment by pgarmiri** [comment]
Hi Helen,

I have blacklisted the following annotations based on the InterPro entries:

Q99470
UniProtKB-KW:UniProtKB-SubCell: extracellular region
InterPro: membrane (IPR016093|IPR036300)

Q9VNA3
UniProtKB-KW: transferase activity
UniProtKB-KW: transferase activity, transferring glycosyl groups
InterPro: membrane (IPR016093|IPR036300)

All the best,
Penelope

**Comment by hattrill** [comment]
Thank you.

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have changed the term in the InterPro entries for 'endoplasmic reticulum membrane' (GO:0005789) and added the reference you cited here. Let me know if you agree. The changes will be visible in the next InterPro release (83.0).
Best regards,
Sara
