### ISSUE TITLE
Q9BPY8	HOPX NOT dbTF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3380]
Hi @mlacencio 

Q9BPY8 | HOPX is annotated to GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific based on its belonging to TFclass3.1.3; however the UniProt entry states "Atypical homeodomain protein which does not bind DNA ", so the annotation should be removed. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @hdrabkin 

PMID:12297045 shows that HOPX is NOT a DNA binding protein, despite its HOX domain. Would you please remove the annotation  GO:0003677 | DNA binding | ECO:0000314(IDA) ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Marcio
we have only about 20 human proteins still annotated as dbTFs which shouldn't be. It would be great if these could get fixed soon. I will add this text to all of the outstanding tickets if I can find them.
Hope all is well with you
Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet ,

Annotation removed!

Best,

Marcio

**Comment by RLovering** [comment]
brilliant thanks
