### ISSUE TITLE
rat TFAM Q91ZW1 RGD 620682 - change annotation to mitochondrial TF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3384]
Hi

Tfam (transcription factor A, mitochondrial) is a mitochondrial TF. Changes to the MF ontology means that mitochondrial TFs need to be annotated to the more specific GO term: 

GO:0034246 | mitochondrial transcription factor activity Not to the GO:0003700 dbTF term

please change these 2 annotations:  

RGD | Q91ZW1 | Tfam |   | GO:0003700 | DNA-binding transcription factor activity | ECO:0000266(ISO) | ECO:0000266 | (ISO) |   | GO_REF:0000096 |   | RGD:1605718 
  |   | RGD | Q91ZW1 | Tfam |   | GO:0003700 | DNA-binding transcription factor activity | ECO:0000315(IMP) | ECO:0000315 | (IMP) |   | PMID:15126286

Thanks

Ruth

**Comment by gthayman** [comment]
Deleted one, made to a retracted paper and deleted the other and a couple more inappropriate annotations to a sloppy, crappy paper. Thanks for pointing these out.

**Comment by RLovering** [comment]
wonderful, thank you so much
Ruth
