### ISSUE TITLE
InterPro2GO: SNF2-related, N-terminal domain (IPR000330)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3385]
This entry already has 'ATP binding (GO:0005524)' associated, and I think you can add 'ATPase activity (GO:0016887)' or perhaps the more specific ''nucleosome-dependent ATPase activity (GO:0070615)'.

The entry description includes "SNF2 functions as the ATPase component of the SNF2/SWI multisubunit complex, which utilises energy derived from ATP hydrolysis to disrupt histone-DNA interactions"

And the introduction of Reference #2 on the entry (PMID: 14729263) includes "The second class of enzymes comprises proteins that utilize the energy derived from ATP-hydrolysis to modulate the contacts between histones and DNA, resulting in an increased DNA accessibility within the nucleosomal array, a process commonly referred to as “chromatin remodeling” (Varga-Weisz and Becker, 1998). Chromatin remodeling is mediated by protein complexes, which typically consist of several subunits. The core subunit of these remodeling complexes is an ATPase subunit, which belongs to the SWI/SNF2-subfamily of the DEAD/H superfamily of nucleic acid-stimulated ATPases (Boyer et al., 2000). The first remodeling complex was identified in yeast and contained SNF2 as the catalytic subunit (Cairns et al., 1994)."

Also, looking at figure 1 of PMID: 14729263, it doesn't look as though this domain is always 'N-terminal', so an edit to the InterPro entry name might be in order?

 @EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Many thanks for this. I have updated the name and added the more specific term 'nucleosome-dependent ATPase activity (GO:0070615)' to this entry. 
Best regards,
Sara

**Comment by sjm41** [comment]
Great, thanks!
