### ISSUE TITLE
mouse Tle4 Q62441 not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3386]
Hi

Please could you change this annotation to a corepressor activity term

MGI | Q62441 | Tle4 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0000316(IGI) | ECO:0000316 | (IGI) |   | PMID:15729346

This paper investigates several transcription proteins but does not demonstrate Tle4 (Grg4) binds DNA

Thanks

Ruth

**Comment by hdrabkin** [comment]
Done

**Comment by pgaudet** [comment]
Thanks!
