### ISSUE TITLE
Ybx3 is NOT a dbTF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3387]
Hi @mlacencio 

Mouse Ybx3 is annotated to dbTF activity, but it isn't. Please review or remove the following annotations: 

NTNU | Q9JKB3 | Ybx3 |   | GO:0000977 | RNA polymerase II transcription regulatory region sequence-specific DNA binding | ECO:0000314(IDA) | ECO:0000314 | (IDA) |   | PMID:17934523 |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ECO:0000314 | (IDA)
  |   | NTNU | Q9JKB3 | Ybx3 |   | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific

Thanks, Pascale

**Comment by mlacencio** [comment]
Hi @pgaudet !

PMID:17934523 seems to provide convincing experimental evidence for DbTF activity for this protein (although the EMSA seems to be performed with nuclear extracts). However, according to TFClass, CSD factors bind single-stranded nucleic acids (http://www.edgar wingender.de/Class%209.1.html). I would like to know if this single-stranded nucleic acid binding activity is the reason for not considering YBX3 as a DbTF. 

Thanks!

Marcio

**Comment by pgaudet** [comment]
Hi @mlacencio 

- Indeed we rejected EMSA with nuclear extracts as evidence, unless there was other evidence
- In my note I wrote (quite succinctly) "Evidence for transcription factor activity is weak for all members. InterPro domains point to nucleic acid binding and regulation of RNA processing"
- Also, we have exchanged about this by email in August, subject line "FYI re YBX proteins" - where you replied "We agree with you and, accordingly, we have removed its annotations.", so I am not sure why the annotations have not been removed?
- We also suggested to remove the tf class  9.1 Cold-shock domain factors on the basis of weak evidence for them to be specific transcription factors; involved in mRNA processing.

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Marcio

we have only about 20 human proteins still annotated as dbTFs which shouldn't be. 7 are due to Ensembl annotations from the mouse ortholog. It would be great if these could get fixed soon. I will add this text to all of the outstanding tickets if I can find them.

Hope all is well with you
Ruth

**Comment by mlacencio** [comment]
Hi @pgaudet,

Finally removed!

**Comment by RLovering** [comment]
Thanks
Ruth
