### ISSUE TITLE
InterPro: ZNFX1 likely to be an RNA binding protein

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3388]
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000967/ 

Please review this record as it looks like ZNFX1 is an RNA binding protein not a dbTF. 

Also in the description in the entry does not contain evidence for dbTF.

Thanks

Ruth

**Comment by EBI-Hsinyu** [comment]
Hi Ruth, 
You are right. I have removed these terms in this entry (IPR000967). This will be visible in InterPro83.0.

Regards, 
Hsin-Yu

**Comment by RLovering** [comment]
Wonderful
thank you so much
Ruth
