### ISSUE TITLE
InterPro2GO: IPR001752:Kinesin motor domain & IPR027640:Kinesin-like protein

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3389]
Both these entries currently have "microtubule motor activity (GO:0003777)" associated.

I think this can be replaced with the more specific "ATP-dependent microtubule motor activity (GO:1990939)".

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill

**Comment by sarach06** [comment]
Hi,
Many thanks. I have replaced the term for the more specific one.

Best,
Sara

**Comment by sjm41** [comment]
Thanks very much!
