### ISSUE TITLE
PTN000174701 (PTHR11599)

### ISSUE THREAD

**Issue by phanivg** [geneontology/go-annotation#3390]
PANTHER:PTN000174701 node adds endopeptidase activity to members of the "PROTEASOME SUBUNIT ALPHA/BETA (PTHR11599)".

This is too broad for grouping and needs splitting as the alpha-subunits of the proteasome have a different function than the beta subunits, and also different beta subunits have distinct functions.
see PMID:19145068 for review

For now it might be good to remove the endopeptidase activity term from the node.

@hattrill  @sjm41

**Comment by hattrill** [comment]
@marcfeuermann, @pgaudet Could you look at this? Only the eukaryotic beta subunits: beta1, beta2 and beta5 are catalytic.

**Comment by pgaudet** [comment]
Fixed.

**Comment by pfey03** [comment]
@pgaudet sorry I fell off this with so many projects on my back. I will look at our proteasome annotations with the limited data we have and also how the naming all came and how it corresponds to our ortholog data. It's quite a project but I will start now in earnest tackling this.
