### ISSUE TITLE
Review annotations to 'regulation of x gene expression'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3391]
Hello, 

The proposal has been made to obsolete 'regulation of x gene expression', see https://github.com/geneontology/go-ontology/issues/20209

Annotations are here: https://docs.google.com/spreadsheets/d/1Kuzcs8eB3yrdv2nrap3pIzeuUNC_rdmPqZnrlSP_4no/edit#gid=0

There are 17 manual annotations to those terms: 

Contributor | Number of annotations
-- | --
ARUK-UCL | 2
FlyBase | 6
MGI | 5
PomBase | 1
UniProt | 3

Thanks, Pascale

**Comment by pgaudet** [comment]
Fixed UniProt annotations.

**Comment by ValWood** [comment]
Fixed.
The annotator comment from @Antonialock  says 
"bet this is a term Val hates :p"

**Comment by hattrill** [comment]
Fixed FB's - dans la poubelle

**Comment by Antonialock** [comment]
Turns out the whole Go hates it! :) Do you put the histones in extensions instead?

**Comment by ValWood** [comment]
Already there ;)
![Uploading Screenshot 2020-10-27 at 09.44.30.png…]()

**Comment by RLovering** [comment]
thanks, removed
Ruth

**Comment by pgaudet** [comment]
Obsoletion as done; remaining annotations (MGI) will show up in reports.
