### ISSUE TITLE
mlh1 NOT GO:0005712 | chiasma

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3392]
mlh1 | ↑part_of GO:0005712 | chiasma | IBA with PTN000008164 , MGI:101938

**Comment by ValWood** [comment]
at least for fission yeast, but seems odd based on the fact that these are the interchange for recombintion, and mlh1 binds mismatches. This might be OK but I wouldn't transfer it based on the avaiable evidence.

**Comment by marcfeuermann** [comment]
I would not have propagated this term. Corrected.
