### ISSUE TITLE
PTN000867953 a question

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3394]
Is it correct to annotate these translation factors to "ribosome"?

gcn2 |   | IBA with S000002691 , PTN000867953 | Gaudet P et al. (2011)
hri1 |   | IBA with S000002691 , PTN000867953 | Gaudet P et al. (2011)
hri2 |   | IBA with S000002691 , PTN000867953

**Comment by ValWood** [comment]
same question
eif21 |   | IBA with S000003286 , PTN000325517

**Comment by marcfeuermann** [comment]
This comes from S. cerevisiae GCN2. However, from the associated paper (PMID: 2038314): "GCN2 could be dissociated from 60S subunits by 0.5 M KCl, suggesting that it is loosely associated with ribosomes rather than being an integral ribosomal protein". 

I've removed the propagation.
