### ISSUE TITLE
PTN000205057  not cytosolic ribosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3397]
get1 |   | IBA with locus:2169518 , PTN000205057 , P23396 , 619888 , S000005122 , locus:2084490 , P0A7V3 , Q8IKH8 , Q0Z8U2 , locus:2065863

(it's GET complex, associates with ribosomes)

**Comment by ValWood** [comment]
also remove "structural constituent of ribosome"

**Comment by marcfeuermann** [comment]
Done.
