### ISSUE TITLE
PTN002811836 sfc2 not DNA-binding transcription factor activity (GO:0003700) -  	PTHR24393 (MECOM)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3416]
sfc2 |   | IBA with prz1 , PTN002811836 , MGI:95457 , MGI:1917923

this is TFIIA

**Comment by ValWood** [comment]
I was not sure if to tag MGI or if this is an inference problem

**Comment by ValWood** [comment]
also not

sfc2 | transcription factor TFIIIA |   | regulation of transcription by RNA polymerase II |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN002811836MGI:MGI:95457


adding 'high priority, as this will help the transcription clean up

**Comment by marcfeuermann** [comment]
PAINT annotation updated.
