### ISSUE TITLE
PTN005301173 not DNA-binding transcription factor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3419]
eta2 | GO:0003700 | DNA-binding transcription factor activity | IBA with MGI:1344415 , PTN005301173 , reb1

eta2 is a termination factor

**Comment by ValWood** [comment]
also rtf1

**Comment by pgaudet** [comment]
Not annotations (IRD) were already present for eta2 - annotations are not in AmiGO 
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC31G5.10

where do you see that ? 

(fixed rtf1)

**Comment by ValWood** [comment]
I saw it in PomBase, we get  PAINT from GOA, anyway I checked, no longer in QuickGO either so all good.

val
