### ISSUE TITLE
PTN001963821 not DNA-binding transcription factor activity, RNA polymerase II-specific

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3420]
DNA-binding transcription factor activity, RNA polymerase II-specific

yox1 |   | IBA with S000002264 , MGI:96086 , PTN001963821 , Q03014

yox1 is part of a DNA-binding TF complex (MBS), but this particular subunit is a corepressor

**Comment by ValWood** [comment]
Still annotated as DNA binding TF in AmiGO

**Comment by marcfeuermann** [comment]
Fixed.
