### ISSUE TITLE
PTN000032154 not kinase?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3425]
These are uracil phosphoribosyltransferases, so if kinase is true, this should. be an ancestor of

uracil phosphoribosyltransferase

uck2 |   | IBA with P0A8F4 , P0A6I3 , PTN000032154 , S000005295 , locus:2034260 , P9WPA7 , locus:2164516 , Q9NPI5 , S000005073 , Q9NWW6 , locus:2086523 |   | Gaudet P et al. (2011)

urg2 |   | IBA with Q9NWW6 , P0A6I3 , PTN000032154 , locus:2164516 , S000005295 , locus:2034260 , P0A8F4 , P9WPA7 , S000005073 , locus:2086523 , Q9NPI5

**Comment by ValWood** [comment]
I don't think these are kinases.

the parent of uracil phosphoribosyltransferase is

 transferase activity, transferring pentosyl groups

**Comment by ValWood** [comment]
uck2 is the ortholog of
https://www.yeastgenome.org/locus/YHR128W
SGD:S000001170
not  S000005295

**Comment by marcfeuermann** [comment]
this is a very complex tree. Kinase activity has been removed from the root and the right activities have been propagated where possible.
