### ISSUE TITLE
 PTN000622075 dsk1 mde3, or pit1 aren't MAP kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3426]
dsk1 | ↑is_a GO:0004707 | MAP kinase activity | IBA with locus:2012808 , Q16539 , FBgn0267339 , S000006258 , O15264 , 621505 , PTN000622075 , FBgn0003256 , WBGene00002187 , FBgn0015765 , 1309340 , A0A1D8PT38 , DDB_G0283903 , DDB_G0286353 , MGI:1346861 , 628847 , MGI:1346863 , P27361 , MGI:1346865 , A0A1D8PFT5 , ZDB-GENE-010202-2 , MGI:1354946 , locus:2043904 , MGI:1346859 , locus:2124943 , WBGene00004056 , MGI:1346858 , Q8ILF0 , MGI:1201387 , FBgn0024846 , Q8TD08 , spk1 , 70500 , 3045 , S000004103 , WBGene00002178 , 70496 , S000003272 , S000000112 , P45984 , Q15759 , CAL0000183747 , sty1 , pmk1 , 3046 , 3663 , 621506 , WBGene00003401 , locus:2080457 , P45983 , FBgn0000229 , 70975 , WBGene00004055

**Comment by ValWood** [comment]
or mde3, or pit1

**Comment by marcfeuermann** [comment]
This is a huge kinase family. The term MAP kinase activity has been removed from the root and only associated with the right nodes.

**Comment by sjm41** [comment]
Ha! Just came across this issue myself for fly annotations - thanks for fixing already!
