### ISSUE TITLE
PTN002450928 not a kinase?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3427]
mcs4 |   | IBA with P52101 , PTN002450928

I don't think mcs4 
response regulator  is a kinase? @Antonialock ?

**Comment by Antonialock** [comment]
hmmmm....

for mcs4 activation I'm really not sure
mak2/3/1 are activated by autophosphorylation, and the actiavtion signal 'flows' to mcs4 with the help of mpr1 -  I'm not sure if the chemistry of this is known (it must be?) i.e. mcs4 could have an active role taking the phosphate from upstream players

I don't think it is believed to phosphorylate downstream targets (eg morigasaki 2013),

**Comment by Antonialock** [comment]
Ah this is weird
 IBA with Sensor histidine kinase GlrK

but mcs4 is a response regulator, not a histidine kinase?

in pombe the sensor histidine kinases are mak1/2/3 (autophosphorylates on histidine, internal transfer to asp residue), the phosphate is then transferred to a histidine in mpr1, which is then transferred to an Asp residue in mcs4

I'm not sure what the underlying chemistry of the phosphotransfer is (do the receiving proteins catalyze any steps? I'm not sure)

**Comment by ValWood** [comment]
Oh I think I know why this might have kinase activity. In some species, there is also a histidine kinase domain ?
This  is from E. coli,
http://pfam.xfam.org/protein/P52101
so this needs to not be propagated.

Phew, a flipping lot of detective work today!

**Comment by Antonialock** [comment]
I think different response regulators function very differently, and can contain different domains.

**Comment by marcfeuermann** [comment]
Reviewed.
