### ISSUE TITLE
PTN000599579 uridylate kinase/UMP kinase ?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3429]
ura6 is uridylate kinase.

Is that the same thing as UMP kinase activity?

ura6 | ↑is_a GO:0033862 | UMP kinase activity | IBA with PTN000599579 , DDB_G0287495 , WBGene00007812 , WBGene00009575

uridylate kinase activity (GO:0009041)
Catalysis of the reaction: ATP + (d)UMP = ADP + (d)UDP.

has descendant
UMP kinase activity (GO:0033862)
Catalysis of the reaction: ATP + UMP = ADP + UDP.

what is the (d) here?

**Comment by ValWood** [comment]
asking @hdrabkin

**Comment by hdrabkin** [comment]
The (d)UMP denotes a reaction with either dUMP or UMP. 
See other child with dUMP + ATP  vs UMP + ATP

**Comment by hdrabkin** [comment]
Just noticed that the 'parent' has an incorrect EC. 
It has "GOC:curators"  as defref, which makes me suspicious if it exists at all (that is, not sure if there would be a gene product that would use EITHER dUMP or UMP as substrate. Let me investigate further.
@deustp01 do you know of any enzyme that does that?

**Comment by hdrabkin** [comment]
649 annotations, 17 experimental.

**Comment by hdrabkin** [comment]
@krchristie , I notice you made one of the children to GO:0009041. Do you remember if there was any kinase that used either/or dUMP/UMP?  I think the term needs to be obsoleted.

**Comment by ukemi** [comment]
PMID:13901467?

**Comment by ValWood** [comment]
So either way, the terms and the definitions don't match...

**Comment by hdrabkin** [comment]
PMID:13901467 has enzyme that uses dUMP only as far as I can see.

**Comment by ValWood** [comment]
So what is the action here

I can use  GO:0033862 | UMP kinase 
https://en.wikipedia.org/wiki/UMP_kinase
but uridylate kinase should be an exact synonym.

The name of  uridylate kinase activity  should change?

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprot/P15700 says
Catalyzes the phosphorylation of pyrimidine nucleoside monophosphates at the expense of ATP. Plays an important role in de novo pyrimidine nucleotide biosynthesis. Has preference for UMP and dUMP as phosphate acceptors, but can also use CMP, dCMP, AMP, GMP, dGMP and dTMP. ATP and dATP are the best phosphate donors, but can also use GTP, dGTP, dCTP, and dTTP to some degree.

hmpph

**Comment by krchristie** [comment]
> @krchristie , I notice you made one of the children to GO:0009041. Do you remember if there was any kinase that used either/or dUMP/UMP? I think the term needs to be obsoleted.

All I know is what is in the ticket: **dUMP kinase activity** #15447 which cited PMID:3010881

**Comment by hdrabkin** [comment]
With such a loose specificity, I don't think a name change will help. I notice that many of the annotations to the term are to proteins whose name suggests that they really should be annotated to EC:2.7.4.14. (see below).

 The UniProt record  for the Saccharomyces cerevisiae protein just assigns  the UMP reaction and not the others.  But they map the  record to  EC:2.7.4.14, which is to UMP/CMP kinase. which is 
    ATP + (d)CMP <=> ADP + (d)CDP
    ATP + UMP <=> ADP + UDP
which GO has mapped to GO:0004127, but GO defines it only as cytidylate kinase,   ATP + (d)CMP = ADP + (d)CDP. only, but ignores the UMP reaction EC lists. 
Cytidylate kinase  has two children, CMP kinase (GO:0036430, RHEA:11600)   and dCMP kinase (GO:0036431, RHEA 25094)

NOT
(EC 2.7.4.22: UMP kinase activity (GO:0033862)
Catalysis of the reaction: ATP + UMP = ADP + UDP.

I would have to ask UniProt why they did not map EC:2.7.4.22 to the entry.
A search on EC:2.7.4.22 
https://www.uniprot.org/uniprot/?query=EC%3A2.7.4.22&sort=score
shows assignments to multiple proteins but the pombe protein is not one of them 8-(

Sorry this is such a mess.

**Comment by hdrabkin** [comment]
I think if one were annotating  P15700 you might actually need to annotate it to all of the activities (ducking).

**Comment by hdrabkin** [comment]
Oops, I see Q97ZE2 Saccharolobus solfataricus is assigned EC:2.7.4.22 at UniProt. pyrH.  But not cerevisiae.

**Comment by ValWood** [comment]
I wonder if all of these different activities/substrates are really physiologically relevant?

**Comment by hdrabkin** [comment]
Hard to tell unless compare km to see how much they need to be 'forced'

**Comment by pgaudet** [comment]
Not a PAINT issue - opened an ontology ticket.
