### ISSUE TITLE
PTN002309613 - PTHR15175 /PTN001038805 - PTHR15706 -   not   superoxide-generating NADPH oxidase activator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3431]
bbc1 | ↑is_a GO:0016176 | superoxide-generating NADPH oxidase activator activity | IBA with MGI:2449980 , Q86UR1 , PTN002309613 |   | Gaudet P et al. (2011) | 2

I don't think bbc1 has an easily identifiable mouse ortholog (only the SH3 domain)

same term, definitely incorrect for scd2
scd2 |   | IBA with MGI:1919143 , Q15080 , PTN001038805 |

**Comment by pgaudet** [comment]
Fixed both families.
