### ISSUE TITLE
PTN000269659/PTN001095090/ PTN001095090 not deacetylase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3434]
these aren't deacetylases, although they are subunits of a deacetylase complexes

pst1 |   | IBA with PTN000269659 , WBGene00004117 | Gaudet P et al. (2011)
pst2 |   | IBA with WBGene00004117 , PTN000269659 | Gaudet P et al. (2011)
pst3 |   | IBA with PTN000269659 , WBGene00004117

@vanaukenk

**Comment by ValWood** [comment]
also
dep1 |   | IBA with PTN001095090 , S000001346 , Q9H7L9

**Comment by ValWood** [comment]
also

rxt2 |   | IBA with S000000299 , PTN002000565

**Comment by ValWood** [comment]
also

sds3 |   | IBA with S000001346 , Q9H7L9 , PTN001095090

**Comment by ValWood** [comment]
@suzialeksander

**Comment by marcfeuermann** [comment]
All annotated as "contributes-to". PAINT propagations have been removed in all families.
