### ISSUE TITLE
 PTN000418221 not tRNA (guanine-N7-)-methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3435]
not
GO:0008176 | tRNA (guanine-N7-)-methyltransferase activity

SPCC18.13 |   | IBA with PTN000418221 , S000002572 , P57081

**Comment by ValWood** [comment]
has contributes_to

**Comment by marcfeuermann** [comment]
Removed from PAINT.
@srengel SGD:S000002572, another example of a CONTRIBUTES_TO annotation to delete.

**Comment by srengel** [comment]
done.
