### ISSUE TITLE
PTN000458398 not a methyltransferase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3440]
not a histone methyltransferase activity (H3-K4 specific) (GO:0042800)
swd2 |   | IBA with S000001501 , PTN000458398 , Q6UXN9 |   | Gaudet P et al. (2011)
swd22 |   | IBA with S000001501 , Q6UXN9 , PTN000458398

**Comment by marcfeuermann** [comment]
Another Contributes_to propagation removed.
