### ISSUE TITLE
 PTN002631076 PTN000464223 PTN000255799 PTN002595486 PTN002631076 PTN000836056 PTN002595486

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3444]
these seem to be a mixture of cullins and adaptors

ckn1 | ↑is_a GO:0004842 | ubiquitin-protein transferase activity | IBA with PTN000523156 , Q13216 |   | Gaudet P et al. (2011) | 94
cul1 |   | IBA with S000003583 , S000002290 , PTN002631076 , Q13618 |   | Gaudet P et al. (2011)
cul3 |   | IBA with PTN002631076 , S000002290 , Q13618 , S000003583 |   | Gaudet P et al. (2011)
elc1 |   | IBA with PTN000464223 , S000005967 |   | Gaudet P et al. (2011)
hrd3 |   | IBA with PTN002595486 , S000004197 |   | Gaudet P et al. (2011)
pcu4 |   | IBA with Q13618 , S000003583 , PTN002631076 , S000002290 |   | Gaudet P et al. (2011)
pop1 |   | IBA with PTN002541357 , CAL0000200882 |   | Gaudet P et al. (2011)
snt2 |   | IBA with S000003099 , PTN000836056 |   | Gaudet P et al. (2011)
SPAC1B3.10c |   | IBA with S000004197 , PTN002595486

**Comment by ValWood** [comment]
I'm filtering all of these unless I am given a convincing reason to keep them...I don't think they are
ubiquitin-protein transferase activity

**Comment by sjm41** [comment]
FlyBase has a similar problem with some of these - I think 'ubiquitin-protein transferase activity' needs to be removed from the node of the following (at least).

(@pgaudet  @marcfeuermann  - do you want this ticket splitting up?):

==

PTN002631076
- adds 'ubiquitin-protein transferase activity' to CULLIN (PTHR11932), including fly Cul1, Cul2, Cul3, Cul4, Cul5, Cul6
- Source annotations are:
(HUMAN|HGNC=2553|UniProtKB=Q13618) = CUL3
(YEAST|SGD=S000002290|UniProtKB=Q12018) = CDC53
(YEAST|SGD=S000003583|UniProtKB=P47050) = RTT101
=> these are non-catalytic adaptor/scaffold subunits (source annotations look wrong)

==

PTN000805648
- adds 'ubiquitin-protein transferase activity' to TNF RECEPTOR ASSOCIATED FACTOR (PTHR10131), including fly Traf4, Traf-like
- Source annotations are:
(HUMAN|HGNC=12032|UniProtKB=Q12933) = TRAF2
(HUMAN|HGNC=12036|UniProtKB=Q9Y4K3) = TRAF6
(MOUSE|MGI=MGI=108072|UniProtKB=P70196) = Traf6
=> these annotations look good, PANTHER family needs splitting to represent functions of different TRAFs?

==

PTN002595486
- adds 'ubiquitin-protein transferase activity(CONTRIBUTES_TO)' to SEL-1-LIKE PROTEIN (PTHR11102), including fly Hrd3
- Source annotation is: (YEAST|SGD=S000004197|UniProtKB=Q05787) = HRD3
=> this is non-catalytic adaptor/scaffold subunit (source annotation looks wrong)

==

PTN000464223
- adds 'ubiquitin-protein transferase activity(CONTRIBUTES_TO)' to ELONGIN-C (PTHR20648) 
- source annotation is (YEAST|SGD=S000005967|UniProtKB=Q03071) = ELC1
=> this is non-catalytic adaptor/scaffold subunit (source annotation looks wrong)

==

**Comment by sjm41** [comment]
@ValWood I think PTN000255799 is OK.
See PMID:22044534 on FYV10/GID9 and PMID:18508925 on RMD5/GID2

**Comment by ValWood** [comment]
yep I  remember did not check all of these ones thoroughly. 
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR044063/
I deleted that one from the list.

**Comment by sjm41** [comment]
@pgaudet - should we split this ticket up?

**Comment by sjm41** [comment]
Hi @pgaudet - I just remembered this unresolved PAINT ticket and added 'high priority'.

**Comment by pgaudet** [comment]
ok thanks! I'll have a look soon.

**Comment by sjm41** [comment]
@marcfeuermann @pgaudet Can I give you a nudge on this one?

**Comment by pgaudet** [comment]
@sjm41 For these 3 families,  would it be appropriate to propagate     GO:0030674    protein-macromolecule adaptor activity? 

Thanks, Pascale

**Comment by sjm41** [comment]
Yes, I believe that would be accurate.  Thanks.

**Comment by pgaudet** [comment]
PTHR20648 done in https://github.com/geneontology/go-annotation/issues/3321

**Comment by pgaudet** [comment]
OK, all done (I hope)

**Comment by sjm41** [comment]
Thanks @pgaudet !
