### ISSUE TITLE
PTN000262858 not calcium:sodium antiporter activity involved in regulation of cardiac muscle cell membrane potential  in yeast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3445]
SPAC3A12.06c | ↑is_a GO:0086038 | calcium:sodium antiporter activity involved in regulation of cardiac muscle cell membrane potential | IBA with PTN000262858 , WBGene00003574 , MGI:2180781

I will request a taxon restriction for this one!

**Comment by marcfeuermann** [comment]
Taxon restriction has been implemented, however I've updated the family and corrected this weird annotation.
