### ISSUE TITLE
Review annotations to GO:0009405 pathogenesis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3452]
Hello, 

The proposal has been made to obsolete GO:0009405 pathogenesis, see https://github.com/geneontology/go-ontology/issues/11057

The reason for obsoletion is that the term is out of scope for GO, since pathogenesis is a disease process. There are many annotations to this term, mostly genes that contribute pathogens grow, but are not specifically relevant for pathogenesis or even interspecies interaction. 

We suggest the annotations be either removed, or replaced by 'GO:0044419 biological process involved in interspecies interaction between organisms' or a child. 

Annotations to review are here: https://docs.google.com/spreadsheets/d/1v5W2rmYkYriY8U23XC7IdI1wRRfUdlNqIXMDZCfnvCY/edit#gid=0

Contributor  |  (Assigned by)
--|--
AgBase | 5
ASAP | 50
AspGD | 39
CACAO | 60
CAFA | 8
CGD | 400
EcoliWiki | 1
GeneDB | 11
MGI | 1
MTBBASE | 92
PAMGO_MGG | 4
PAMGO_VMD | 3
ParkinsonsUK-UCL | 1
PseudoCAP | 56
TAIR | 1
TIGR | 3
UniProt | 184
WB | 2

**Comment by RLovering** [comment]
UCL done

**Comment by hdrabkin** [comment]
MGI done

**Comment by genegodbold** [comment]
UniProt has nearly a quarter million accessions tagged with "Pathogenesis" and nobody can say what it means. Good riddance! FWIW, the JHU APL folks have a much better approach to documenting what is happening in pathogenic symbiosis. It should make it's public debut sometime next year. This is just a guess, though.

**Comment by tberardini** [comment]
TAIR done

**Comment by vanaukenk** [comment]
WB done.

**Comment by pgarmiri** [comment]
Hello,

I am just starting looking at this. It seems that the suggested term to be used has a restriction.

 GO:0044419 JSON
biological process involved in interspecies interaction between organisms

**Restrictions**

**This term should not be used for direct annotation.**

Is this going to change when the GO:0009405 'pathogenesis' will be obsoleted? 

We have a few annotations to check and it wouldn't be fun to have to go back to them again for a second time.

Thanks,

Penelope

**Comment by pgarmiri** [comment]
Hi,
CAFA and UniProt-EBI annotations have been reviewed. Actions reported in the spreadsheet.

Annotations by SWIS and SWIP have been tagged in the spreadsheet with a purple and orange label, respectively.

Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi @pgarmiri 

'GO:0044419 biological process involved in interspecies interaction between organisms' should not change. 
Thanks for your understanding and for fixing all those annotations !! 


Pascale

**Comment by Achchuthan** [comment]
GeneDB done.

**Comment by marekskrzypek** [comment]
CGD done
