### ISSUE TITLE
PTN000380877 / PTN000315300 / PTN000331371 / PTN001404517 / PTN000393206

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3457]
not a ribonuclease
rpp21 |   | IBA with Q9H633 , PTN000380877 , S000001454 |

**Comment by sjm41** [comment]
Same issue for these:
PTN000315300 -  contributes_to ribonuclease P activity
PTN000331371 - contributes_to ribonuclease MRP activity / contributes_to ribonuclease P activity
PTN001404517 - contributes_to ribonuclease P activity
PTN000393206 - contributes_to ribonuclease P activity

The underlying annotations here are all for protein components of the RNase P/RNaseMRP complexes where the RNA molecule provides the catalytic activity.

**Comment by marcfeuermann** [comment]
All the five families have been corrected. I realize that the "CONTRIBUTES_TO" stuff is far from being cleaned.
