### ISSUE TITLE
PTN000124327  TORC1 & TORC2 complexes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3466]
pombe naming is bonkers. Tor1 is TORC2 signalling and trr2 is TORC1 signalling.

GO:0038202 | TORC1 signaling
tor1 |   | IBA with FBgn0021796 , PTN000124327 , P42345 , tor2

**Comment by marcfeuermann** [comment]
As both signaling pathways are mixed within the tree, I've only propagated the parent TOR signaling term.

**Comment by ValWood** [comment]
Hi @marcfeuermann The complex mapping is back

[GO:0031931](https://www.pombase.org/term/GO:0031931)	
[TORC1 complex](https://www.pombase.org/term/GO:0031931)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [MGI:1928394](http://www.informatics.jax.org/accession/MGI:1928394) , [WBGene00002583](http://www.wormbase.org/get?name=WBGene00002583) , [68371](https://rgd.mcw.edu/rgdweb/search/search.html?term=68371) , [P42345](https://www.uniprot.org/uniprot/P42345) , [S000001686](https://www.yeastgenome.org/search?q=S000001686&is_quick=true) , [FBgn0021796](http://flybase.org/reports/FBgn0021796.html) , [tor2](https://www.pombase.org/gene/SPBC216.07c) , [PTN000124327](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000124327) , [S000003827](https://www.yeastgenome.org/search?q=S000003827&is_quick=true)

It's odd because  SGD tor1 and  tor2 are both mapping to TORC1 complex

SGD tor2  https://www.yeastgenome.org/locus/S000001686 ToRs = TORC2 
PomBase tor1  https://www.pombase.org/gene/SPBC30D10.10c = TORC2

SGD tor1 https://www.yeastgenome.org/locus/S000003827 = TORC1
PomBase  tor2 https://www.pombase.org/gene/SPBC216.07c = TORC1

https://github.com/pombase/curation/issues/3693

**Comment by marcfeuermann** [comment]
This is weird... I corrected it again.
