### ISSUE TITLE
intra complex gene product specific binding terms - PTHR10676

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3469]
can we remove

dhc1

GO:0045505 | dynein intermediate chain binding | IBA with DDB_G0276355 , PTN000743491 | Gaudet P et al. (2011) | 2
&
GO:0051959 | dynein light intermediate chain binding | IBA with MGI:103147 , 71042 , PTN000743491 , Q14204

These are intra-complex interactions for 

cytoplasmic dynein complex

**Comment by ValWood** [comment]
not true for fission yeast

GO:0051293 | establishment of spindle localization | IBA with Q14204 , S000001762 , PTN000072732 , WBGene00000962


GO:0072382 | minus-end-directed vesicle transport along microtubule | IBA with DDB_G0276355 , PTN000072732 | Gaudet P et al. (2011)

**Comment by pgaudet** [comment]
Hi @ValWood 

We removed minus-end-directed vesicle transport along microtubule

However for 'establishment of spindle localization', there is evidence in both human (PMID:23027904) and Dicty (PMID:18430243) for a role in spindle localization, and in pombe it's annotated to attachment of mitotic spindle microtubules to kinetochore  - could the papers be looking at the same process with different assays? Would there be a common term that we could use? 

Thanks, Pascale

**Comment by ValWood** [comment]
Actually looking at 
https://www.pombase.org/reference/PMID:17409356
I am going to remove
[mitotic sister chromatid biorientation](https://www.pombase.org/term/GO:1990758)
is likely indirect.
It does seem to be involved in microtubule attachment to the MTOC 
(this paper needs annotating properly)

based on this "establishment of spindle localization" seems to be OK.
Although I would like to check this with @manu

From the terms it isn't really clear which aspects of spindle localization these terms refer to. Is it  just spindle orientation? or something else?

There are 2 children
GO:0060069    Wnt signaling pathway, regulating spindle positioning | regulates
GO:0000132    establishment of mitotic spindle orientation
but BOTH of these terms seem to be referring to "mitotic spindle orientation"
so I wonder if "establishment of spindle localization"  is really required.

I am a bit confused about how spindle orientation works in pombe, it seemed to be controversial.

I will open an ontology tracker ticket based on Manu's feedback here.

**Comment by ValWood** [comment]
Also spindle positioning is probably different in organisms which undergo closed mitosis ( fission yeast) vs those which do open mitotis (human and dicty).

We could keep 
"establishment of spindle localization" but call it "spindle positioning" and figure out what types of positioning occur in additional to "orientation"

I think the annotations are probably OK.

**Comment by pgaudet** [comment]
The binding annotations were remvoed. Please reopen if you want other changes (note that the binding annotations still show in AmiGO and probably in QuickGO, as the last build of the PAINT annotations at least for PomBase is from October 2022, see http://release.geneontology.org/2023-01-01/products/annotations/paint_pombase-src.gaf.gz
