### ISSUE TITLE
Reactome neutrophil degranulation R-HSA-6798695 - possibly error in mapping to GO

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3470]
Hi 

I am concerned that the Reactome mapping of R-HSA-6798695 to  GO:0043312 neutrophil degranulation needs to be modified.

This has been drawn to my attention due to a review of https://pubmed.ncbi.nlm.nih.gov/32805023/

In this paper the authors identify GO:0043312 neutrophil degranulation as an enriched GO term. 
Definition: The regulated exocytosis of secretory granules containing preformed mediators such as proteases, lipases, and inflammatory mediators by a neutrophil. 

However, this term has been associated with almost 500 human proteins due to the mapping from R-HSA-6798695.

Looking at R-HSA-6798695 I am concerned that many of the proteins associated with this term are associated due to a proteomic study rather than evidence that all 500 proteins have a role in neutrophil degranulation. I do not know how to work out which references support the annotations in Reactome, but one of the 5 papers listed is: Proteome profiling of human neutrophil granule subsets, secretory vesicles, and cell membrane: correlation with transcriptome profiling of neutrophil precursors.

If these proteins are associated with this term due to proteomic data then possibly a better mapping 

For example the Reactome child term of R-HSA-6798695: exocytosis of azurophil granule lumen proteins has 88 proteins, that doesn's seem so bad but this includes P20333 TNFRSF1B Tumor necrosis factor receptor superfamily member 1B
The GO term GO:0043312 neutrophil degranulation has the parent term:
exocytosis
neutrophil activation
'other' immune process terms

I don't think TNFRSF1B is involved in exocytosis, although it maybe involved in regulation of this process, although I haven't tried to check this.
But looking at the Reactome pathway it looks like the Reactome term exocytosis of azurophil granule lumen proteins might include a list of proteins in the granule lumen rather than actively participating in exocytosis. ie they are targets of exocytosis that GO would not normally capture the targets of a process in this way.

Although I don't think the proteomic study I mentioned above is one of the ones listed in this entry. 

I therefore think the mapping for this term should be to a cellular component term such as GO:0042582 azurophil granule or GO:0035578 azurophil granule lumen rather than to a GO process term.

Ideally each R-HSA-6798695 child term would be mapped to the more specific cellular component GO term, or alternatively it would be good to change the mapping of the parent term R-HSA-6798695 to GO:0030141 secretory granule.

Looking at the published paper I list above shows how having large gene groups like this associated with GO process term in a way that is not consistent with the way the GO curators are annotating is causing an over-interpretation of data and might mis-direct future research projects.

I have no idea how these associations can be identified easily, although possibly it would be useful if all BP GO terms that have large numbers (>100, or maybe >400? depending on the specificity of the term) of genes associated with them based on a single Reactome ID should be investigated to make sure that the Reactome ID is describing a complex pathway that justifies such high numbers of associated gene products.

Best

Ruth

@cmungall @pgaudet @deustp01 @vanaukenk

**Comment by deustp01** [comment]
Looking quickly at the neutrophil degranulation pathway R-HSA-6798695, it appears that we have catalogued the protein content of each type and asserted that each of those proteins is thereby a participant in the process. That clearly violates the GO rule against annotating substrates, as I understand it from previous discussions - the vesicle contents do not enable the release process - so we will fix our GAF, with luck in time for our next release next month.
