### ISSUE TITLE
InterPro2GO: Gid-type RING finger domain (IPR044063)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3478]
Currently has "ubiquitin-protein transferase activity (GO:0004842)".
From the description, references, and annotated proteins, I think this can be improved to "ubiquitin protein ligase activity (GO:0061630)"

@EBI-Hsinyu
@lsw26
@sarach06
@Alexbateman1
@typhainepl

@hattrill
@ValWood

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I have replaced the term as you suggested. The changes will be visible in the next InterPro release (83.0).
Best,
Sara

**Comment by sjm41** [comment]
thanks
