### ISSUE TITLE
PTN001003176 / PTN001095998 / PTN000992949 / PTN000325907

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3489]
All these are associated with these three terms:

histone acetyltransferase activity (H4-K16 specific) ; GO:0046972 (contributes_to)
histone acetyltransferase activity (H4-K5 specific) ; GO:0043995  (contributes_to)
histone acetyltransferase activity (H4-K8 specific) ; GO:0043996  (contributes_to)

Source annotations are all from non-catalytic human subunits curated from PMID:20018852, which I notice were all deleted in P2GO last week.
So, these terms should disappear from the PAINT nodes in time, but making this ticket for the record and in case you can remove them directly sooner.

@hattrill

**Comment by marcfeuermann** [comment]
PAINT annotation has been removed in all 4 families.

**Comment by sjm41** [comment]
thanks
