### ISSUE TITLE
ARMT1/ YMR027W PTN000262496  - PTHR12260

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3502]
- [ ] Can the PANTHER mapping change from

GO:2001020 | regulation of response to DNA damage stimulus | IBA with PTN000262496 , Q9H993

to "response to DNA damage stimulus"
(@pgaudet I don' think we should have 'regulation of response to " terms. If you know it "regulates, you must know the process?)

 - [ ] SGD @edwong57  and PomBAse, remove phosphatase annotation?
You might want to keep it but the human work looks more robust?

https://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC4350021&blobtype=pdf

Here, we provide the original description of Armt1, a first-in-class eukaryotic
methyltransferase encoded by the uncharacterized gene C6orf211. Structurally, Armt1
belongs to the ‘DUF89’ family, and of the four DUF89 structures that have been determined to date, all possess conserved and strong structural similarities to key active site residues of the SAM-MT fold (Martin and McMillan, 2002). Based on these structural observations,
activities for the DUF89 family of proteins have been previously proposed, but these studies lacked biochemical and cellular analyses. For example, in 2010 the structure of the S.cerevisiae Armt1 homolog was deposited into the protein data bank by a structural genomics group (PDB code: 3PT1). After soaking the crystals with 6-fructophosphate, the depositors found the molecule in the central pocket leading them to postulate it as novel carbohydrate phosphatase. Instead, we observe that the yeast structure belongs to the SAM-MT domain family, readily docks the cofactor SAM (data not shown), and our in-depth characterization
of carboxyl methyltransferase activity with the human homolog supports this domain as a SAM-MT fold. In these studies we not only detected methyltransferase activity in the
presence of PCNA, but also in its absence. Self-methylation of Armt1 appears to generate negative feedback that limits its activity.

**Comment by edwong57** [comment]
@ValWood, thanks. Some later papers show phosphatase activity for yeast and human proteins. 27322068(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7001580/) shows YMR027W has metal ion-dependent phosphatase activity. A 2020 paper https://pubmed.ncbi.nlm.nih.gov/32682077/ also shows human DUF89 has phosphatase activity. Looks like same author in the 2016 and 2020 papers.

**Comment by ValWood** [comment]
OK! - the balance tips in favour of phosphatase (and the methyltransferase paper was  5 years ago)
@EBI-Hsinyu   could you update
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR039763/

I will keep phosphatases and remove methyltransferase pending supporting data (I doubt it is both, we have no instances of any other protein being both phosphatase and a methyltransferase simultaneously , and it has only a single domain as far as I can tell.

**Comment by ValWood** [comment]
In fact UniProt human entry has this caution:

Caution
Has been reportedly associated with a protein carboxyl methyltransferase activity, but whether this protein indeed has such an activity remains to be determined (PubMed:25732820). It has been later shown to belong to a family of metal-dependent phosphatases implicated in metabolite damage-control (PubMed:27322068).

**Comment by ValWood** [comment]
Note that ARMT1 stands for 

ARMT1
Approved name 
acidic residue methyltransferase 1

@sartweedie (HGNC)

**Comment by ValWood** [comment]
Although methyltransferase domains, and phosphatase domains are often only 150-200 AA and this is 
~400 aa , and does not fall into any Clan so perhaps the family represents 2 domains and this is multifunctional? I will ask Pfam about this.

**Comment by ValWood** [comment]
the most recent paper taken together, these features separate DUF89 subfamily III proteins from more remote structural neighbors that include methyltransferases (Perry et al., 2015). Catalytic activity is also conserved between the human and yeast DUF89 proteins, with a broad selection of phospho-sugars being substrates, whichbelong to pathways that include the pentose phosphate pathway andglycolysis. Highest activity was also noted on F-1-P for hDUF89, and inhumans, liver aldolase B is known to act on F-1-P, but hDUF89 isstructurally dissimilar to this enzyme and it lacks the aldolase’s activityon fructose 1,6‐diphosphate (Dalby et al., 2001), indicating distinctcellular roles.A damage pre-emption function in metabolite control for DUF89subfamily III proteins has been suggested (Huang et al., 2016) due to the DNA damage response phenotypes in human (Perry et al., 2015)and budding yeast cells (Gasch et al., 2001), and because F-1-P is a non-canonical yeast metabolite that is toxic at high levels. It may be of interest to further define hDUF89 in cellular roles that could additionally include directed overflow and/or preventing the trapping of phosphate sugar substrates (Galperin et al., 2006; Linster et al., 2013; Sun et al.,2017; Beaudoin and Hanson, 2016; Bommer et al., 2019; Reaves et al.,2013), and thereby allow for high-flux through key metabolic pathways such as through the glycolytic pathway (Bommer et al., 2019; Collardet al., 2016). hDUF89 and yeast DUF89 activities on phospho-fructose species and on erythrose 4-phosphate and ribose-5-phoshpate, may also pre-empt of unwanted glycation events. Notably, fructose and fructose phosphates are relatively potent glycating agents, as compared to glu-cose and glucose phosphates (Levi and Werman, 2003). Also, glycation is the first step in generating an advanced glycation product (AGE) (Fuet al., 1994; Bucala and Cerami, 1992), where AGEs have been strongly
implicated in aging pathophysiology and many age-related diseases(Ajith and Vinodkumar, 2016; Singh et al., 2001; Yan et al., 2008).Thus, molecular-based definitions of DUF proteins are likely to provideunique biochemical insights to greatly impact our understanding of cellular metabolism and potentially of human health.


I  won't ask Pfam to look for additional domains as the structure /catalytic site is quite clear.
I'm going to annotate conservatively as a phosphatase involved in
GO:1990748 | cellular detoxification

**Comment by pgaudet** [comment]
The original annotation was to 'regulation', so we cannot propagate the non-regulatory version of the term. 

I changed the annotation, we need to wait for the various release cycles to go through to update this one.

**Comment by sartweedie** [comment]
Thanks for the heads-up Val - we'll take at look at the recent papers as it sounds like the human gene name (which was agreed with the author of the 2015 prior to publication) could now be misleading.

**Comment by pgaudet** [comment]
There is no annotation to the 'response' term that we can use to propagate, so I will leave this annotation. The regulation of terms will be obsoleted, see https://github.com/geneontology/go-ontology/issues/24632

If we use 'replace by' GO:0006974 cellular response to DNA damage stimulus these will be updated, otherwise the annotations will go away.

Thanks, Pascale
