### ISSUE TITLE
PTN000224401  enolase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3506]
GO:0032889 | regulation of vacuole fusion, non-autophagic | IBA with PTN000224401 , S000001217 , S000003486

OK this one might be controversial.
enolase probably doest have all of these moonlighting roles:
https://pubmed.ncbi.nlm.nih.gov/31106201/#&gid=article-figures&pid=figure-5-uid-4

the paper proposing a role in homotypic fusion is a 2006 paper and I can't find any confirmation.

Also vacuolar fragmentation is quite a   pleiotropic phenotype:

It seems no coincidence that the "moonlighting proteins" always seem to be the ones in the "crapome" too (i.e they are the most highly expressed genes).

Based on the available info I'd be unlikely to make this call even if it wasn't enolase.

I would restrict to S. cerevisiae until more data at least.

**Comment by ValWood** [comment]
even if it is multifunctional, this could be a readout.

**Comment by marcfeuermann** [comment]
Fixed.
