### ISSUE TITLE
GTF with "regulation" inference

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3508]
I have

RNA polymerase II general transcription initiation factor activity

with both

GO:0006355 | regulation of transcription, DNA-templated | IBA with PTN007678118 , FBgn0039067 , MGI:1919039 | Gaudet P et al. (2011) | 382

- | GO:0006367 | transcription initiation from RNA polymerase II promoter | IBA with PTN007678118 , FBgn0010356 , Q15542

is that correct?
@RLovering 
@colinlog 
@pgaudet

**Comment by colinlog** [comment]
I think we (Pascale actually ;-) are in the process of refactoring the GTF MF branch so as to park it under transcription rather than regulation of transcription. Basically along with RNA polymerase II. THe question is how long it will take for this to be visible in QuickGO and Amigo...

**Comment by pgaudet** [comment]
Yes, changes have been made to the ontology to remove that assertion. I'll check the family to make sure this is not annotated directly. 

Thanks for reporting this, 

Pascale

**Comment by pgaudet** [comment]
Re-annotated.
