### ISSUE TITLE
Review annotations to 'GO:0018307 enzyme active site formation’ and its children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3511]
Dear all, 

The proposal has been made to obsolete 'GO:0018307 enzyme active site formation’ and its children. Annotations should be removed - this is outside the scope of GO. See https://github.com/geneontology/go-ontology/issues/15594

Annotations are here: https://docs.google.com/spreadsheets/d/1KzYrO8Ca1YHX-fqVBGQgU4wRb_cCyRNvsAQyXhH8vro/edit#gid=0

1 EcoCyc
1 ParkinsonsUK-UCL
9 UniProt

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, there is 1 InterPro mapping IPR012406, already mapped to protein folding, so it probably just needs to be removed. 

Thanks, Pascale

**Comment by keseler** [comment]
Hi Pascale,

Could you explain why this is considered outside the scope of GO?  In the case of the EcoCyc annotation, P0A9N4 is the pyruvate-formate lyase activating enzyme, which generates an essential glycyl radical within the active site of pyruvate-formate lyase.  I can't think of a better way of describing this than "enzyme active site formation".

Thanks,
Ingrid

**Comment by ukemi** [comment]
I seem to recall that there are other examples of this as well, sometimes in order to recycle the active state of an enzyme?

**Comment by pgaudet** [comment]
EC calls it [Formate-C-acetyltransferase]-activating enzyme - ie it is described as a function, not a process. Would that work @keseler  ?

**Comment by pgaudet** [comment]
In fact that term already exists, GO:0043365 [formate-C-acetyltransferase]-activating enzyme activity

**Comment by pgaudet** [comment]
Note to self: [formate-C-acetyltransferase]-activating enzyme activity and its parent should be children of 'enzyme activating activity'.

**Comment by sarach06** [comment]
Hi Pascale,
Many thanks. I have removed the term from IPR012406. The changes will be available in the next InterPro release (83.0).
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks @sarach06

**Comment by pgaudet** [comment]
@keseler Does my reply address your concern ? Or do you think those terms should be kept ?

**Comment by keseler** [comment]
Hi Pascale,
Sorry for the delay.  Yes, in the case of the E. coli PFL activating enzyme, it is a single activity of an enzyme, so this case can be described by the enzymatic activity.  Are all/some/any of the others single-step enzymatic activities with corresponding MF terms as well? Is there a different BP that would collect each of those activities? Maybe (well, probably) I'm behind the times in keeping up with GO standards, but if possible, I usually look for both a MF and a larger/more general BP term for annotation.
Thanks,
Ingrid

**Comment by pgaudet** [comment]
Hi @keseler 

Thanks for your reply. 
Out of the 22 terms I proposed to obsolete, only 3 have annotations: 


1.   GO:0018307 enzyme active site formation > 1 EXP
This is the EcoCyc annotation you have looked at

2.  GO:0018323 enzyme active site formation via L-cysteine sulfinic acid  > 1 EXP
- Mouse Park7
annotated by BHF @RLovering 
- I dont see any mention of L-cysteine sulfinic acid or active site formation in the paper cited (PMID:17766438)- however PMID:15181200 's title is "The Parkinson's disease protein DJ-1 is neuroprotective due to cysteine-sulfinic acid-driven mitochondrial localization " 
The paper mentions in the intro: 
> If the pI shift of DJ-1 represents a formation of cysteine-sulfinic acid, then mutating these cysteine residues will block oxidation. C106 is a prime candidate for modification, because it is highly conserved and may be part of an active site in a deep crevice on the DJ-1 dimer 

> Mitsumoto et al. (10) have suggested that DJ-1 may be directly oxidized by free radicals, because the pI shift after oxidation is consistent with formation of cysteine-sulfinic acid (10), an idea recently tested using mass spectrometry where cysteine-sulfonic acids were identified in oxidized DJ-1 (12). Formation of cysteine-sulfinic acid has been recognized as an important reversible posttranslational modification of proteins, such as the peroxiredoxins (13-15).


3. GO:0018192 enzyme active site formation via cysteine modification to L-cysteine persulfide > 9 EXP to 2 proteins, 
- L-cysteine S-thiosulfotransferase subunit SoxA : https://www.uniprot.org/uniprot/O33434 (and orthologs)
> The SoxAX complex catalyzes the formation of a heterodisulfide bond between the conserved cysteine residue on a sulfur carrier SoxYZ complex subunit SoxY and thiosulfate or other inorganic sulfur substrates. This leads to the liberation of two electrons, which may be transferred from the SoxAX complex to another cytochrome c that then channels them into the respiratory electron transport chain.


-  Adenylyltransferase and sulfurtransferase MOCS3
https://www.uniprot.org/uniprot/O95396
> Its N-terminus first activates URM1 and MOCS2A as acyl-adenylates (-COAMP), then the persulfide sulfur on the catalytic cysteine is transferred (...) 


As described here, all those look like molecular functions. If we encounter a case where the active site generation requires more than one activity, we can revisit this and create the functions again (or revert the obsoletion). 

Does that seem OK to you ? 

Thanks, Pascale

**Comment by keseler** [comment]
Hi @pgaudet

Wow, that's a lot of info.  So it's fine with me to obsolete all of those terms.  My personal preference would have been to keep the GO:0018307 parent term, but if that doesn't jibe with the GO philosophy, I'm not one to object.

For future consideration, when thinking about enzyme active site formation, the process that came to my mind is the formation/insertion of iron-sulfur clusters.  I think those BP terms are currently under protein maturation/modification, but could also be considered enzyme active site formation.  There are also a bunch of very detailed BP terms such as "iron incorporation into iron-sulfur cluster via tris-L-cysteinyl L-arginyl diiron disulfide"...  Oh no, did I just open a can of worms?

Cheers,
Ingrid

**Comment by pgaudet** [comment]
I am well aware of the can of worms.... I'm trying to break it up into more reasonable tasks. 

Thanks for the feedback !
