### ISSUE TITLE
Review annotations to GO:0097755 and GO:0097756 positive/negative regulation of blood vessel diameter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3512]
Dear all, 

The proposal has been made to obsolete GO:0097755 and GO:0097756 positive/negative regulation of blood vessel diameter
see https://github.com/geneontology/go-ontology/issues/12253 for details.

There are 61 annotations to those 2 terms: 
Contributor   (Assigned by)
--
AgBase | 7
MGI | 2
RGD | 43
UniProt | 9

 https://docs.google.com/spreadsheets/d/1vR65vSzZDdAYbsXcuhqa_nrdw_aI-Bl3qH7sekKJXRM/edit#gid=0

Please review your annotations.

Thanks, Pascale

**Comment by pgaudet** [comment]
@hdrabkin @gthayman According to the spreadsheet, MGI and RGD annotations have not been fixed, but since the terms are already obsoleted, you should go to your group's error report to fix them. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
We must have done this and forgot; these are gone
