### ISSUE TITLE
PTN000801132 - PTHR10071

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#3518]
In pombe fil1 only appears to acts as an activator of gene expression, not as a repressor (PMID:29432178) 

  | GO:0000122 | negative regulation of transcription by RNA polymerase II | IBA                        with                                            Q5AP95          ,                                     fep1            ,                                             S000000842          ,                                             S000001742          ,                                             PTN000801132          ,                                             S000003646 | Gaudet P et al. (2011) | 52
-- | -- | -- | -- | -- | --

**Comment by pgaudet** [comment]
Fixed
