### ISSUE TITLE
Review annotations to 'GO:0030375 thyroid hormone receptor coactivator activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3520]
This term will be obsoleted, see: 

Annotations are here: https://docs.google.com/spreadsheets/d/11e3aThHaGv6k3tytSyw3M9YLaKTckuZzoYXWnDWL5wI/edit#gid=0

1 RGD, 3 MGI annotations. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
mgi done

**Comment by gthayman** [comment]
RGD done.

**Comment by pgaudet** [comment]
Thanks everyone !
