### ISSUE TITLE
PTN004500658 - PTHR18902

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3521]
Can you block propagation to FBgn0037979 GCC185 from PTN004500658. 

Perhaps this is not a great node to propagate from - proteins that are used for 'nucleoplasm' exp are all from HPA and they are a fairly unrelated bunch. Think it's just a sequence quirk.
 
FBgn0037979 GCC185 is a golgin and already has a lot of annotations from this node PTN004500662 that seems more consistent with golgin function. 

There is definitely a sharp dropoff in ortholog calls.

![Screenshot 2020-11-19 at 13 13 52](https://user-images.githubusercontent.com/11865746/99673032-26292f80-2a6c-11eb-81dc-1bbee504eb44.png)

**Comment by pgaudet** [comment]
Sorry @hattrill - what do you want us to remove ? All annotations ? or the CC ? 

Thanks, Pascale

**Comment by hattrill** [comment]
PANTHER:PTN004500658 only has a CC, but block all please.

**Comment by pgaudet** [comment]
What about FBgn0037979﻿, GCC185, isn't that Golgi ?

**Comment by pgaudet** [comment]
Fixed.

**Comment by hattrill** [comment]
Yes, it is, the issue is nucleoplasm from PTN004500658 

Annotations coming from PTN004500662 are golgi and fine 
but the nucleoplasm one inherrited from PTN004500658 isn't.
![Screenshot 2020-12-16 at 10 11 07](https://user-images.githubusercontent.com/11865746/102335113-63a7ac80-3f87-11eb-9a8e-6613ab0eedfb.png)

**Comment by pgaudet** [comment]
OK good, that's gone. This family is weird, I opened a ticket for the Panther group to review it.

**Comment by hattrill** [comment]
Thanks!
