### ISSUE TITLE
Obsolete GO terms, GO:2000327 and GO:2000325, in gaf files: chicken, cow, human, pig, mgi, rgd, and zfin

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/go-annotation#3523]
Hello,

Thank you for the terrific annotations.

Our tests are reporting an obsolete GO terms, **GO:2000327** and **GO:2000325**, in the files listed below downloaded 2020/11/22 from http://current.geneontology.org/annotations.

GO:2000327 is annotated to the proteins: 

|DB Symbol | DB Symbol | With/From
|-------------|-------------|--------------
| CNOT6 | Cnot6 | UniProtKB:Q9ULM6|ensembl:ENSP00000481893
| CNOT9 | Cnot9 |UniProtKB:Q92600|ensembl:ENSP00000486540
| TACC1 |  Tacc1 | UniProtKB:O75410|ensembl:ENSP00000321703

It is also seen in Saccharomyces cerevisiae rgd.gaf for: **Zcchc12** and **Zfp335**.

## File's downloaded Nov 21, 2020:
go-basic.obo
goa_cow.gaf
goa_dog.gaf
goa_human.gaf
goa_pig.gaf
goa_pig_isoform.gaf
mgi.gaf
rgd.gaf
zfin.gaf

**Comment by dvklopfenstein** [comment]
Here is the grep of GO:2000327...

[i3523_obsolete_GO.txt](https://github.com/geneontology/go-annotation/files/5580418/i3523_obsolete_GO.txt)

**Comment by dvklopfenstein** [comment]
And here is the grep of GO:2000325:

[i3523_obsolete_GO2.txt](https://github.com/geneontology/go-annotation/files/5580432/i3523_obsolete_GO2.txt)

**Comment by ValWood** [comment]
@suzialeksander  I think this should be on the helpdesk, but I can't transfer tickets.

GO PI's @cmungall @thomaspd Who is monitoring this tracker? I have been making sure people are assigned to  the unassigned tickets for this past month or so, mainly because most of the submissions are mine, reassigning and answering helpdesk, but it isn't really my job to deal with all of the other tickets!

**Comment by suzialeksander** [comment]
Hi @dvklopfenstein, 

Thanks for letting us know about this.  I've looked at the two GO terms reported, and it looks like this is simply a timing issue.  Both terms were marked as obsolete on 24 November.  You can follow major obsoletions at https://github.com/geneontology/go-announcements/issues, or QuickGO's change log at the bottom of a term page (https://www.ebi.ac.uk/QuickGO/term/GO:2000327).  

We expect the December release to be out around mid-month, and if this issue persists please let us know.

If you need any more assistance, please let us know in a new ticket.

**Comment by dvklopfenstein** [comment]
Thank you for taking a look at this issue. 

Just a note, that it was causing our parser to crash until we added a workaround.  We can work around it with no problem. But I wonder of the effect for other parsers that did not notice this new event.
