### ISSUE TITLE
PTN000623092 not  (all) mediator

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3524]
Hi,

GO:0016592 | mediator complex | IBA with PTN000623092 , MGI:1196224 , P49336 , FBgn0015618 , S000005963 , srb10

Although pombe srb10 is mediator, csk1 isn't (it  has an independent S. cerevisiae ortholog CAK1, so I suspect this is a PANTHER family problem.

Val

**Comment by pgaudet** [comment]
2500 family member - will do later

**Comment by marcfeuermann** [comment]
Addressed a few months ago.
