### ISSUE TITLE
PTN000418654  - PTHR16301

### ISSUE THREAD

**Issue by keseler** [geneontology/go-annotation#3525]
The B. subtilis protein YvyE (P32437) has an IBA annotation to GO:0060733 with PTN000418654 and MGI:1098233.  However, GO:0060733 is a eukaryote-specific term.  I don't know whether the annotation needs to be moved to a more general term and/or whether there needs to be a taxon constraint on GO:0060733.

Cheers,
Ingrid

**Comment by pgaudet** [comment]
Fixed, thanks for reporting this.
