### ISSUE TITLE
PTN000138598 PTN001020335  PTN000158239 mappings to 'response to' terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3528]
Please remove:

ptr8 | GO:0009411 | response to UV | IBA with DDB_G0278729 , PTN000138598 , P19447 , FBgn0001179 , locus:2177891 , MGI:95414 , locus:2177901 | Gaudet P et al. (2011) | 25
rad15 |   | IBA with PTN000158239 , P18074 , MGI:95413 , FBgn0261850 , locus:2014525 | Gaudet P et al. (2011)
rhp18 |   | IBA with MGI:1890476 , PTN001020335 | Gaudet P et al. (2011)

At pombase we don't annotate "response to terms" because they don't really mean anything unless they relate to a specific stress signalling pathway.
For example we have all of these  184 genes annotated to "sensitive to UV" which is essentially what this GO term means:
https://www.pombase.org/term/FYPO:0002550
Sensitivities span all. processes
https://www.pombase.org/slim:bp_goslim_pombe/from/id/e3e43839-0fb1-4b83-9a41-cd92b29fb59f

so this term is very meaningless.
We would use "DNA damage response" if this was narrowed down further, like:

DNA synthesis involved in UV-damage excision repair
or
 regulation of translation involved in cellular response to UV (or as an extension in the absence of a precomposed term).

In general, I don' think cross-species "response to " inferences are safe, but  even more I don't think they are  useful as GO terms, they are just phenotypes.

**Comment by marcfeuermann** [comment]
Done for ptr8 and rhp18. Will do the 3rd when PAINT will be available again.
