### ISSUE TITLE
endoplasmic reticulum unfolded protein response/ ubiquitin-dependent ERAD pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3532]
calnexin is annotated to

GO:0030968 | endoplasmic reticulum unfolded protein response | IBA with WBGene00000567 , PTN000117401 , WBGene00000802

This is a signalling pathway:

Definition 
The series of molecular signals generated as a consequence of the presence of unfolded proteins in the endoplasmic reticulum (ER) or other ER-related stress; results in changes in the regulation of transcription and translation.

but as far as I am aware  calnexin is involved in a different pathway

GO:0030433 | ubiquitin-dependent ERAD pathway | ISO with S000000054

The series of steps necessary to target endoplasmic reticulum (ER)-resident proteins for degradation by the cytoplasmic proteasome. Begins with recognition of the ER-resident protein, includes retrotranslocation (dislocation) of the protein from the ER to the cytosol, protein ubiquitination necessary for correct substrate transfer, transport of the protein to the proteasome, and ends with degradation of the protein by the cytoplasmic proteasome.

It might be useful to identify the beginning and end of 
GO:0030968 | endoplasmic reticulum unfolded protein response
or something to make it clearer the distinction between these 2 terms

@vanaukenk  to check WB annotation
@pgaudet for ontology. Do we know anyone who knows about these processes (Or perhaps there is a Noctua model of the signalling pathway? its a broader parent of IRE1-mediated unfolded protein response)

**Comment by ValWood** [comment]
also

GO:0030968 | endoplasmic reticulum unfolded protein response | IBA with Q9BUN8 , S000002819 , PTN000109990 , Q96Q80 , Q9GZP9

**Comment by ValWood** [comment]
Maybe I'm wrong and there is some intersection, but  there is no relationship between these terms in GO, and one is a signalling pathway, one isn't:

![Uploading Screenshot 2020-11-25 at 14.30.01.png…]()

**Comment by ValWood** [comment]
![Uploading Screenshot 2020-11-25 at 14.30.18.png…]()

**Comment by marcfeuermann** [comment]
Family has been updated.
