### ISSUE TITLE
PTN000270391 & PTN000270390  - PTHR12357

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3533]
This is suspect because  mmi1 is a nuclear gene involved in  RNA surveillance (it does regulate transcription but not translation so these could be annotation errors?). I did not look further....

GO:0045948 | positive regulation of translational initiation | IBA with Q9BYJ9 , Q7Z739 , Q9Y5A9 , PTN000270391

**Comment by ValWood** [comment]
I had an further look, I think these are bad orthology calls

also

GO:0061157 | mRNA destabilization | IBA with PTN000270390 , Q9Y5A9 , MGI:2444233 , Q7Z739 , ZDB-GENE-040426-948

**Comment by pgaudet** [comment]
Fixed, this looks like a downstream effect of mRNA stability.
