### ISSUE TITLE
MGI:1276116﻿ Mouse EP300 NOT RNA polymerase II cis-regulatory region sequence-specific DNA binding 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3537]
Hi, 

MGI:1276116﻿ EP300 is NOT RNA polymerase II cis-regulatory region sequence-specific DNA binding. 

It localizes with the DNA in a non-sequence-specific manner. Please change to 'chromatin' or remove the annotation. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Paper used appears to be indexed to a different gene. Investigating

**Comment by hdrabkin** [comment]
done (data buried in supplemental).
