### ISSUE TITLE
PTHR28189 remove  pheromone-dependent signal transduction involved in conjugation with cellular fusion

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#3538]
pheromone-dependent signal transduction involved in conjugation with cellular fusion

git11 pombe has an IBA to this, but git11 is heterotrimeric G protein gamma subunit for the Glucose receptor in pombase (not pheromone pathway)

**Comment by pgaudet** [comment]
Please @Antonialock next time if you can provide the PTN or PTHR that would be appreciated ! 

Thanks, Pascale

**Comment by pgaudet** [comment]
Thanks, I changed to  GO:0007189  adenylate cyclase-activating G protein-coupled receptor signaling pathway

Pascale

**Comment by Antonialock** [comment]
note that cerevisiae has two gamma subunits - one for the glucose pathway and one for the pheromone pathway.

In pombe, only one gamma subunit has been identified (git11) that functions in glucose signaling.
(there is one proposed gamma for the pheromone pathway - gnr1 - but I think it is not confirmed / controversial)

I see that aside from pombe, PTHR28189 contains cerevisiae STE18, which according to SGD is the pheromone one.
I see they have annotated GPG1 to BP "invasive growth in response to glucose limitation" - this is probably their glucose signaling beta subunit? 

 It doesn't looks like we can infer which one functions in which pathway? Since git11/STE18 is glucose sensing in pombe but pheromone sensing in cerevisiae

maybe a more general "G protein coupled signaling pathway" would be safest here?

**Comment by pgaudet** [comment]
You mean it's not an ACA-activating GPCR pathway ?

**Comment by Antonialock** [comment]
if by ACA you mean adenylate cyclase (yeast CYR1) then no, cerevisiae STE18 is not in an ACA pathway

![image](https://user-images.githubusercontent.com/12727506/102494912-5107a300-406d-11eb-8321-6837bc13fbf6.png)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1083946/

**Comment by Antonialock** [comment]
here is an image comparing pombe and cerevisiae

![image](https://user-images.githubusercontent.com/12727506/102495064-8b714000-406d-11eb-8c08-94c7e0e8c74e.png)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1087802/

**Comment by pgaudet** [comment]
Yes, that's what I meant, I'll change the annotation. 

Thanks, Pascale

**Comment by Antonialock** [comment]
thanks sorry for the confusion, but it looks like the two yeasts have mixed things up a bit wrt to these two GPCR pathways

**Comment by pgaudet** [comment]
OK fixed, thanks for the precision.
