### ISSUE TITLE
human annotations  to receptor-mediated endocytosis overinflated

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3539]
human has 695 (1300 annotations)  genes annotated to endocytosis. This seems like a massive over-inflation. Endocytosis is well studied in yeast and has around 70 gene products. Since this is a relatively conserved process it seems unlikely that all of the annotations are correct.

A quicker recky reveals lots of annotations to gene products that are 'endocytosed'

here are just a few:

<img width="975" alt="Screenshot 2020-12-07 at 17 40 09" src="https://user-images.githubusercontent.com/7359272/101385159-4d2c9180-38b3-11eb-964c-cd831dbb0dc7.png">
<img width="957" alt="Screenshot 2020-12-07 at 17 39 56" src="https://user-images.githubusercontent.com/7359272/101385174-5158af00-38b3-11eb-8e3e-7b6c03db539b.png">
<img width="1069" alt="Screenshot 2020-12-07 at 17 39 41" src="https://user-images.githubusercontent.com/7359272/101385186-5584cc80-38b3-11eb-8bcb-b845746750f2.png">

<img width="20" alt="Screenshot 2020-12-07 at 17 39 30" src="https://user-images.githubusercontent.com/7359272/101385202-5cabda80-38b3-11eb-9da8-12676a5e735e.png">

<img width="983" alt="Screenshot 2020-12-07 at 17 39 17" src="https://user-images.githubusercontent.com/7359272/101385213-62092500-38b3-11eb-8e2a-c0f65348f59b.png">

<img width="1000" alt="Screenshot 2020-12-07 at 17 39 05" src="https://user-images.githubusercontent.com/7359272/101385230-66354280-38b3-11eb-8c8d-2ec3debda155.png">

**Comment by ukemi** [comment]
Hmmmm. The IGs functioning in the receptor-mediated endocytosis process does not seem odd to me since IIRC they serve as either the receptors or the ligands that trigger the process after they bind antigen or interact in some way. And there are lots of them. But let's ask an expert. @addiehl ?

**Comment by ValWood** [comment]
Ah right if they are the endocytic receptors that seems ok- but not if they are the cargo, is that right?

**Comment by deustp01** [comment]
Some of this is a curation mistake: an incompletely characterized process in which alpha-1-microglobulin binds heme and somehow mediates its degradation got included with "Scavenging of heme from plasma", in turn a child of "Binding and uptake of ligands by scavenger receptors". That specific process fits better as a variant process within  GO:0042167
heme catabolic process. We'll fix that.

**Comment by pgaudet** [comment]
> Ah right if they are the endocytic receptors that seems ok- but not if they are the cargo, is that right?

Yes,  that's right.

**Comment by ValWood** [comment]
these seem to be fixed.
