### ISSUE TITLE
Review annotations to invadopodium terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#3540]
Dear all, 

The proposal has been made to obsolete all of the invadopodium terms. The reason for obsoletion is that an invadopodium is an abnormal structure found in cancerous or transformed cells that is out of scope of GO. Only the starred terms have been used in annotations.

- GO:0071437 - invadopodium *
- GO:0071438 - invadopodium membrane *
- GO:1905863 - invadopodium organization *
- GO:1905877 - invadopodium assembly
- GO:1905878 - invadopodium disassembly
- GO:1905924 - regulation of invadopodium assembly
- GO:1905925 - negative regulation of invadopodium assembly
- GO:1905926 - positive regulation of invadopodium assembly *
- GO:1905927 - regulation of invadopodium disassembly
- GO:1905928 - negative regulation of invadopodium disassembly
- GO:1905929 - positive regulation of invadopodium disassembly *

There are 17 experimental and 63 sequence-based annotations to these term by MGD, RGD, and UniProt:
- MGI: 17 ISO
- RGD: 3 EXP, 14 ISO
- UniProt: 14 EXP, 32 ISS

There are 2 UniProt vocabulary terms for subcellular localizations:
- invadopodium = UniProtKB-SubCell:SL-0148
- invadopodium membrane = UniProtKB-SubCell:SL-0290

The experimental annotations by RGD and UniProt have already been removed; please review the sequence based annotations:

https://docs.google.com/spreadsheets/d/1KKx_w9mhnYe3sJuqNHp95du7SQJfC3reHFdyb4UgBoQ/edit#gid=0

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on December 20, 2020. Unless objections are received by 12/20/20, we will assume that you agree to this change.

Any comments can be  added to the issue:  obsolete? invadopodium terms #20475 https://github.com/geneontology/go-ontology/issues/20475

Thanks,

Karen

**Comment by pgaudet** [comment]
@krchristie Just checking why you assigned me (and Sylvain) - if UniProt annotations have been removed, there is no action for us, right ?

**Comment by krchristie** [comment]
> @krchristie Just checking why you assigned me (and Sylvain) - if UniProt annotations have been removed, there is no action for us, right ?

The experimental annotations have been removed, but UniProt also has 32 ISS annotations. I'm under the impression that UniProt's ISS annotations are manual and would need to be reviewed. 

I added all of the sequence based annotations to the spreadsheet you created for the experimental annotations. In addition to the UniProt ISS annotations, MGI and RGD also have ISO annotations. For MGI, these are all from an orthology annotation pipeline, so these will be removed once source annotations are removed.

**Comment by pgaudet** [comment]
ISS get automatically updated when EXP are changed.

**Comment by pgaudet** [comment]
I mean, for annotations done in P2GO this is automated.

**Comment by krchristie** [comment]
> ISS get automatically updated when EXP are changed.

Great, they can be marked in the spreadsheet as automatically updating

**Comment by gthayman** [comment]
RGD's GO ISO annotations are also imported by pipeline - marked in spreadsheet.

**Comment by pgaudet** [comment]
Everything is done, closing the ticket.

**Comment by pgaudet** [comment]
@pgarmiri 

Can you please update the KW mappings ? 


    invadopodium = UniProtKB-SubCell:SL-0148
    invadopodium membrane = UniProtKB-SubCell:SL-0290


Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
just checking to be sure, you are asking for the mapping to be removed, right?
Thanks,
Penelope

**Comment by pgaudet** [comment]
or changed, yes; the ontology ticket mentions 'podosome' as the normal structure; but I dont suppose this is a safe mapping
(see #20475)

**Comment by pgaudet** [comment]
Actually UniProt defines invadopodia very different from GO: 

> The invadopodium is a localized and persitent cell protrusion similar to the highly dynamic podosome, but larger. These structures protrudes into the extracellular matrix. Invadopodial protrusions are enriched in integrins, tyrosine kinase signaling machinery, soluble and membrane proteases including matrix metalloproteases, actin and actin-associated proteins. Essential for physiological and pathological cell invasion and metastasis these structures are involved in focalized degradation of the extracellular matrix. Invadopodia form underneath the cell body, often close to the nucleus and proximal to the Golgi complex, and are rarely found at the cell periphery. Their half-life is quite extended. As invadopodia and podosomes are similar in appearance, location and composition, it is likely that a thin line separates these two entities in time and function.


, although wikipedia clearly states that invadopodium is a disease structure and podosome is the normal structure: 

https://en.wikipedia.org/wiki/Invadopodia

**Comment by pgarmiri** [comment]
..and also a few papers
 https://www.sciencedirect.com/science/article/pii/S0171933514000909
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2171731/

I think is quite clear that the invadopodium is related to cancel and metastasis.

 I will just leave it as it is and we can see into changing the definition in UniProt to remove the part that is essential for physiological functions? Not sure who to tag for this.

**Comment by AndreaAuchincloss** [comment]
I can look into this - next week or next year! The definition does need changing.
I started all this with a request for a podosome membrane term however which @krchristie was looking into, ticket #20443

**Comment by krchristie** [comment]
> I can look into this - next week or next year! The definition does need changing.
> I started all this with a request for a podosome membrane term however which @krchristie was looking into, ticket #20443

@Achchuthan - I put a bunch of info about the similarities and differences of podosomes and invadopodia into the ontology ticket for obsoleting the invadopodium terms from GO: https://github.com/geneontology/go-ontology/issues/20475

In addition to the references already used as definition references in GO, I found several other useful papers that I quoted and cited in the ticket. Some of these might be helpful to you.
