### ISSUE TITLE
AKIRIN1 and AKIRIN2 not dbTFs?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3542]
Hi Pascale

AKIRIN1 and AKIRIN2 are not on our dbTF list but are now annotated as dbTFs based on PANTHER:PTN000329080.

The structure described in UniProt does not point to this function

please could you check these annotations, maybe we could discuss with Colin whether these need to be added to the dbTF list?

Thanks

Ruth

**Comment by pgaudet** [comment]
Fixed, this is a coTF. Thanks, 

Pascale

**Comment by RLovering** [comment]
wonderful, thank you so much
Ruth
