### ISSUE TITLE
DMRTC1 Q5HYR2 not a dbTF

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3544]
Hi Marcio

please see ticket https://github.com/geneontology/go-annotation/issues/3379 which describes why this protein is not a dbTF. InterPro have removed their annotations and PAINT has created a NOT dbTF annotation (see evidence code IBA).

Please remove this annotation:

NTNU | Q5HYR2 | DMRTC1 | enables | GO:0000981 | DNA-binding transcription factor activity, RNA polymerase II-specific | ECO:0005556(ISA) | GO_REF:0000113 |   | tfclass:2.5.1

Thanks

Ruth

**Comment by mlacencio** [comment]
Dear @RLovering and @pgaudet ,

Annotation removed!

Best,

Marcio

**Comment by RLovering** [comment]
thanks
Ruth
