### ISSUE TITLE
Issues with NOT annotations in Panther 15

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3546]
Reported by @dustine32 

https://docs.google.com/spreadsheets/d/16L4TDDldeogYVlXEbrDuul3CRxBaG9PnmNPOysuRa60/edit#gid=0

**PAINT annotations that were forward-tracked to new PTNs**
classification_id | new_pthr | prev_pthrs | prev_node_ptns | new_node_ptns | go_term | Fix
-- | -- | -- | -- | -- | -- | --
930191248 | PTHR10003 | PTHR10003 | PTN004118896 | PTN004118900 | GO:0004784 (NOT, IKR), GO:0005737 (IBD), GO:0016532 (IBD) | Fixed
930110507 | PTHR10183 | PTHR10183 | PTN002564895,PTN002564902 | PTN000809773,PTN002564886,PTN002564896 | GO:0004198 (NOT, IKR), GO:0006508 (NOT, IKR) | Fixed
930206404 | PTHR10846 | PTHR10846 | PTN002586308 | PTN002474463 | GO:0005802 (IBD), GO:0005887 (NOT, IRD) | Annotation OK
930092527 | PTHR11461 | PTHR11461 | PTN000156152 | PTN002606970,PTN002606973 | GO:0005615 (NOT, IRD) | Fixed
930185449 | PTHR11932 | PTHR11932 | PTN004322134 | PTN004322136 | GO:0004842 (NOT, IRD), GO:0016567 (NOT, IRD), GO:0031461 (NOT, IRD), GO:0031625 (NOT, IRD) | Fixed - removed NOTs
930175004 | PTHR12697 | PTHR12697 | PTN000976400 | PTN000976423 | GO:0008612 (NOT, IRD), GO:0019135 (NOT, IRD) | Fixed - removed NOTs from PTN002652975
930103329 | PTHR13345 | PTHR13345 | PTN000331274,PTN004417795 | PTN000331275,PTN001410867 | GO:0000785 (IBD), GO:0000930 (COLOCALIZES_WITH, IBD), GO:0003712 (NOT, IRD), GO:0003714 (IBD), GO:0005634 (NOT, IRD), GO:0016592 (NOT, IRD), GO:0045944 (NOT, IRD), GO:0048487 (IBD) | Fixed - was already disputed #3315
930135393 | PTHR15151 | PTHR15151 | PTN001032096 | PTN001032109,PTN002689129 | GO:0005123 (IBD), GO:0005615 (NOT, IRD), GO:0038177 (IBD), GO:0042475 (IBD), GO:0051092 (IBD), GO:1901224 (IBD) | Fixed
930103196 | PTHR15592 | PTHR15592 | PTN000400581 | PTN000400582 | GO:0003729 (NOT, IRD), GO:0006417 (NOT, IRD) | Fixed
930107382 | PTHR21087 | PTHR21087 | PTN000472459,PTN001464780 | PTN000472467,PTN000472496 | GO:0000287 (NOT, IKR), GO:0004765 (NOT, IKR), GO:0005829 (NOT, IRD), GO:0009073 (NOT, IKR), GO:0009507 (IBD), GO:0019632 (NOT, IKR) | Fixed
930128756 | PTHR23076 | PTHR23076 | PTN001130167 | PTN002348150 | GO:0005739 (NOT, IRD) | Fixed
930134942 | PTHR23251 | PTHR23251 | PTN001509613 | PTN000583314 | GO:0005789 (NOT, IRD) | Fixed
930110974 | PTHR23359 | PTHR23359 | PTN002764135,PTN004635205 | PTN002764136,PTN002764144,PTN002764156 | GO:0004017 (NOT, IRD), GO:0004550 (IBD), GO:0006186 (IBD), GO:0006756 (IBD), GO:0006757 (IBD) | Annotation OK
930104828 | PTHR24060 | PTHR24060 | PTN004658124 | PTN002780858,PTN004658125 | GO:0007216 (NOT, IRD), GO:0051966 (NOT, IRD) | Annotation OK ?
930165059 | PTHR24104 | PTHR24104 | PTN004670351 | PTN002540971 | GO:0000209 (NOT, IRD), GO:0043161 (NOT, IRD), GO:0061630 (NOT, IRD) | Annotation OK ?
930111650 | PTHR24416 | PTHR24416 | PTN001975022,PTN002356460,PTN002814447,PTN004704213,PTN004704288 | PTN000699229,PTN001230349,PTN002521409,PTN004704214,PTN004704289 | GO:0004714 (IBD), GO:0004714 (NOT, IRD), GO:0005887 (IBD), GO:0005887 (NOT, IRD), GO:0007169 (IBD), GO:0007169 (NOT, IRD), GO:0007275 (IBD), GO:0007275 (NOT, IRD), GO:0009925 (IBD), GO:0016477 (IBD), GO:0033674 (IBD), GO:0033674 (NOT, IRD), GO:0043235 (IBD), GO:0043235 (NOT, IRD), GO:0045766 (IBD), GO:0051897 (IBD), GO:0070374 (IBD), GO:0070857 (IBD) | Annotation OK ?
930174292 | PTHR24418 | PTHR24418 | PTN002521550 | PTN000764966 | GO:0050853 (NOT, IRD) | Cannot load tree 1700 sequences
930148069 | PTHR31088 | PTHR31088 | PTN002029275 | PTN004762099 | GO:0005829 (NOT, IRD) | Fixed - tree has multiple suspicious HGT
930172619 | PTHR42938 | PTHR42938 | PTN001335230 | PTN000107798 | GO:0004617 (NOT, IRD), GO:0005829 (IBD), GO:0006520 (NOT, IRD), GO:0008615 (IBD), GO:0033711 (IBD), GO:0036001 (IBD) | Reannotated
930129197 | PTHR43527 | PTHR43527 | PTN001840039 | PTN002882405 | GO:0009236 (IBD), GO:0050515 (NOT, IRD) | Reannotated
930118704 | PTHR45858 | PTHR45858 | PTN002912442 | PTN000975189 | GO:0030676 (NOT, IKR) | Had lost all annotations - recurated
930163751 | PTHR47961 | PTHR24031 | PTN002772474 | PTN002772475,PTN004651425 | GO:0000712 (IBD), GO:0003723 (NOT, IRD), GO:0003724 (NOT, IRD) | Reannotated

**Comment by pgaudet** [comment]
**NOT annotations not forwardly tracked**


accession | public_id | accession | qualifier | Evidence | Fix
-- | -- | -- | -- | -- | --
PTHR10134:AN328 | PTN004127831 | GO:0006122 | NOT | IRD |  
PTHR10134:AN328 | PTN004127831 | GO:0008121 | NOT | IRD |  
PTHR10134:AN329 | PTN004127832 | GO:0006122 | NOT | IRD |  
PTHR10134:AN329 | PTN004127832 | GO:0008121 | NOT | IRD |  
PTHR11932:AN1135 | PTN004322566 | GO:0004842 | NOT | IRD |  
PTHR11932:AN1135 | PTN004322566 | GO:0016567 | NOT | IRD |  
PTHR11932:AN1135 | PTN004322566 | GO:0031461 | NOT | IRD |  
PTHR11932:AN1135 | PTN004322566 | GO:0031625 | NOT | IRD |  
PTHR11932:AN1138 | PTN004322568 | GO:0004842 | NOT | IRD |  
PTHR11932:AN1138 | PTN004322568 | GO:0016567 | NOT | IRD |  
PTHR11932:AN1138 | PTN004322568 | GO:0031461 | NOT | IRD |  
PTHR11932:AN1138 | PTN004322568 | GO:0031625 | NOT | IRD |  
PTHR12143:AN258 | PTN002486431 | GO:0005634 | NOT | IRD |  
PTHR22993:AN127 | PTN000891721 | GO:0003906 | NOT | IRD |  
PTHR22993:AN127 | PTN000891721 | GO:0005634 | NOT | IRD |  
PTHR22993:AN127 | PTN000891721 | GO:0006284 | NOT | IRD |  
PTHR22993:AN127 | PTN000891721 | GO:0019104 | NOT | IRD |  
PTHR23105:AN1488 | PTN001895997 | GO:0000470 | NOT | IRD |  
PTHR23105:AN1488 | PTN001895997 | GO:0003723 | NOT | IRD |  
PTHR23105:AN1488 | PTN001895997 | GO:0022625 | NOT | IRD |  
PTHR23105:AN1648 | PTN000560514 | GO:0000469 | NOT | IRD |  
PTHR23105:AN1648 | PTN000560514 | GO:0000470 | NOT | IRD |  
PTHR23105:AN1648 | PTN000560514 | GO:0003723 | NOT | IRD |  
PTHR23105:AN1648 | PTN000560514 | GO:0031118 | NOT | IRD |  
PTHR23105:AN1648 | PTN000560514 | GO:0031120 | NOT | IRD |  
PTHR23105:AN1648 | PTN000560514 | GO:0031429 | NOT | IRD |  
PTHR23105:AN1648 | PTN000560514 | GO:0034513 | NOT | IRD |  
PTHR23105:AN1653 | PTN001134795 | GO:0022625 | NOT | IRD |  
PTHR23147:AN2548 | PTN001899513 | GO:0000381 | NOT | IRD |  
PTHR23147:AN2548 | PTN001899513 | GO:0003723 | NOT | IRD |  
PTHR23147:AN2548 | PTN001899513 | GO:0005737 | NOT | IRD |  
PTHR23147:AN2548 | PTN001899513 | GO:0016607 | NOT | IRD |  
PTHR23147:AN2548 | PTN001899513 | GO:0045292 | NOT | IRD |  
PTHR24031:AN4005 | PTN002772468 | GO:0003723 | NOT | IRD |  
PTHR24031:AN4005 | PTN002772468 | GO:0003724 | NOT | IRD |  
PTHR24031:AN5961 | PTN002772399 | GO:0003723 | NOT | IRD |  
PTHR24031:AN5961 | PTN002772399 | GO:0003724 | NOT | IRD |  
PTHR24057:AN649 | PTN004657530 | GO:0004674 | NOT | IRD |  
PTHR24057:AN649 | PTN004657530 | GO:0005737 | NOT | IRD |  
PTHR24057:AN649 | PTN004657530 | GO:0005829 | NOT | IRD |  
PTHR24057:AN649 | PTN004657530 | GO:0007165 | NOT | IRD |  
PTHR24057:AN781 | PTN004657633 | GO:0004674 | NOT | IRD |  
PTHR24057:AN781 | PTN004657633 | GO:0005737 | NOT | IRD |  
PTHR24057:AN781 | PTN004657633 | GO:0005829 | NOT | IRD |  
PTHR24057:AN781 | PTN004657633 | GO:0007165 | NOT | IRD |  
PTHR24060:AN674 | PTN004658124 | GO:0001641 | NOT | IRD |  
PTHR24068:AN1194 | PTN004660199 | GO:0006301 | NOT | IKR | Marc done for #3442
PTHR24068:AN1194 | PTN004660199 | GO:0070534 | NOT | IKR | Marc done for #3442
PTHR24068:AN3392 | PTN004661023 | GO:0006511 | NOT | IKR | Marc done for #3442
PTHR24068:AN3698 | PTN004661277 | GO:0006511 | NOT | IKR | Marc done for #3442
PTHR24068:AN3721 | PTN004661296 | GO:0006511 | NOT | IKR | Marc done for #3442
PTHR24068:AN4160 | PTN002784245 | GO:0031145 | NOT | IKR | Marc done for #3442
PTHR24115:AN6410 | PTN002380231 | GO:0005634 | NOT | IRD |  
PTHR24115:AN6410 | PTN002380231 | GO:0005815 | NOT | IRD |  
PTHR24115:AN6410 | PTN002380231 | GO:0072686 | NOT | IRD |  
PTHR24189:AN15 | PTN002793830 | GO:0005634 | NOT | IRD |  
PTHR24189:AN15 | PTN002793830 | GO:0005737 | NOT | IRD |  
PTHR24189:AN15 | PTN002793830 | GO:2000812 | NOT | IRD |  
PTHR24253:AN407 | PTN001207272 | GO:0005615 | NOT | IRD |  
PTHR24379:AN182 | PTN002394381 | GO:0000977 | NOT | IRD |  
PTHR24379:AN182 | PTN002394381 | GO:0005634 | NOT | IRD |  
PTHR24379:AN183 | PTN002520529 | GO:0000977 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0004714 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0005030 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0005887 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0007169 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0007275 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0007399 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0010976 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0014068 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0030424 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0033674 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0043121 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0043235 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0043408 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0043410 | NOT | IRD |  
PTHR24416:AN1017 | PTN002815021 | GO:0051896 | NOT | IRD |  
PTHR24416:AN1110 | PTN000700771 | GO:0004714 | NOT | IRD |  
PTHR24416:AN1110 | PTN000700771 | GO:0005887 | NOT | IRD |  
PTHR24416:AN1110 | PTN000700771 | GO:0007169 | NOT | IRD |  
PTHR31356:AN289 | PTN002044505 | GO:0009507 | NOT | IRD |  
PTHR42823:AN3 | PTN001686127 | GO:0042777 | NOT | IRD |  
PTHR42823:AN3 | PTN001686127 | GO:0045263 | NOT | IRD |  
PTHR42823:AN3 | PTN001686127 | GO:0046933 | NOT | IRD |  
PTHR43427:AN2 | PTN002459532 | GO:0005886 | NOT | IRD |  
PTHR45752:AN1164 | PTN002907941 | GO:0046579 | NOT | IRD |  
PTHR45752:AN320 | PTN002547862 | GO:0005225 | NOT | IRD |  
PTHR45752:AN320 | PTN002547862 | GO:0034702 | NOT | IRD |  
PTHR45752:AN320 | PTN002547862 | GO:0098656 | NOT | IRD |

**Comment by pgaudet** [comment]
@dustine32 @huaiyumi will you release a PAINT/Panther16? just to avoid fixing issues twice.

**Comment by sjm41** [comment]
Not sure if you want/need more examples of NOT conflicts, but I found another one for fly CG18853 (A1Z758) and PTN000025285  (PTHR10211) which doesn't seem to be on the above list:
![Screenshot 2021-04-19 at 14 31 06](https://user-images.githubusercontent.com/16306861/115244542-eef2a380-a11b-11eb-8090-35822055e40c.png)

**Comment by sjm41** [comment]
Also fly CG32318 (Q7KVC2) and PTN000648413 (PTHR24115):
![Screenshot 2021-04-19 at 15 29 06](https://user-images.githubusercontent.com/16306861/115253211-1188ba80-a124-11eb-8f64-6ca588844c5d.png)

**Comment by sjm41** [comment]
@dustine32 @huaiyumi  @pgaudet
Is there any update on fixing this general issue of PAINT annotations being applied where a NOT annotation exists?
Thanks.

**Comment by dustine32** [comment]
Hi @sjm41! Is this the same thing that's happening in #3701? If yes, it should be getting fixed once we finish some internal coding (via https://github.com/pantherdb/fullgo_paint_update/issues/52) to correctly generate the IBAs from PAINT. Sorry, I thought we could get this done and released a couple months ago but then priorities shifted. This is very close to finished so I'll dig out some time for this very soon.

**Comment by sjm41** [comment]
Thanks for the update @dustine32 ! I'm not sure if the two tickets are describing exactly the same issue, but there's overlap. My two examples from 19th April concern IKR annotations apparently being ignored in the PAINT pipeline, and that's definitely part of #3701.  Not sure whether some lines in the big table at the top of this ticket cover different issues...maybe I should have posted those examples in #3701??
Anyway, sounds like you're on the case, thanks!  (This is high priority issue IMO!!)

**Comment by marcfeuermann** [comment]
I would close this one. We adressed quite a lot of those cases if not all. If you still have issues, just open it again or create a more specific ticket.
