### ISSUE TITLE
Review annotations to transporters

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3547]
Hello,

I am working on simplifying the transporter labels, see #17164 

Specifically I am renaming terms that describe ABC transporters -> ABC-type transporter activity (currently mostly named 'ATPase-coupled transmembrane transporter activity) and P-type -> P-type transporter activity (currently mostly named 'x transmembrane transporter activity, phosphorylative mechanism). Looking at annotations there are a few inconsistencies. I'll be adding them to this ticket. 

Thanks, Pascale

**Comment by pgaudet** [comment]
- [ ] GO:0015434 ATPase-coupled cadmium transmembrane transporter activity => 1 EXP annotation, TAIR HMA1 (AT4G37270), a P-type -> please change to GO:0008551 P-type cadmium transporter activity

@tberardini 

Thanks, Pascale

**Comment by pgaudet** [comment]
- [ ] GO:0015633  ATPase-coupled zinc transmembrane transporter activity corresponds to ABC-type according to the RHEA mapping; => 1 EXP annotation, TAIR HMA1 (AT4G37270), a P-type -> please change to GO:0008551 P-type cadmium transporter activity (same protein as above) 

@tberardini

**Comment by pgaudet** [comment]
Merge  
GO:0048474 D-methionine transmembrane transporter activity
GO:0033232 ATPase-coupled D-methionine transporter activity 

All D-met transporters are ABC transporters
(and probably bacterial)

**Comment by tberardini** [comment]
Did both. I changed the second one (zinc...) to  GO:0016463,     zinc transmembrane transporter activity, phosphorylative mechanism instead of the cadmium term.

**Comment by pgaudet** [comment]
Thanks !
