### ISSUE TITLE
PTN000317312 BLOC-1 COMPLEX SUBUNIT 1 (PTHR13073) 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3548]
http://www.pantree.org/node/annotationNode.jsp?id=PTN000317312

Gives mitochondrion to the BLOC-1 subunit. The more appropriate CC to propagate cross-species is BLOC-1 complex. The mito observation is from one paper PMID:22309213 and a HDA.

**Comment by pgaudet** [comment]
Fixed, thanks
