### ISSUE TITLE
PTN001006717 PTN000270240 development

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3553]
no evidence for developmental process in yeast:

nud3
GO:0032502 | developmental process | IBA with WBGene00003829 , PTN000270240 , locus:2178431 , ZDB-GENE-040426-899 , FBgn0021768 | Gaudet P et al. (2011)

rav2
GO:0032502 | developmental process | IBA with Q9GZN7 , c, MGI:1913299. PTN001006717 
(this is a weird annotation anyway for the  RAVE complex?)

also for rav2
GO:0007035 | vacuolar acidification | IBA with S000002610 , PTN001006717
is a phenotype, consequence of complex misassembly

nud3
- | GO:0032502 | developmental process | IBA with WBGene00003829 , PTN000270240 , locus:2178431 , ZDB-GENE-040426-899 , FBgn0021768

**Comment by pgaudet** [comment]
PTN000270240 = PTHR12356
PTN001006717 =

**Comment by pgaudet** [comment]
fixed
