### ISSUE TITLE
PTN001350062 - LIPOCALIN (PTHR11430) 

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#3562]
I've just annotated a paper for Obp2a (odorant binding protein 2A, Chr 2). The paper is:

Cho KW, Zhou Y, Sheng L, Rui L. **Lipocalin-13 regulates glucose metabolism by both insulin-dependent and insulin-independent mechanisms.** Mol Cell Biol. 2011 Feb;31(3):450-7. PMID:21135134

In MGI, I see that mouse Obp2a is annotated with the term **odorant binding (GO:0005549)** by IBA with PTN001350062. However, the paper shows a role for Obp2a in regulation of glucose metabolism and is found in blood plasma.

It looks like the lipocalin family is broader than just binding odorant molecules - https://en.wikipedia.org/wiki/Lipocalin 

I think it might be good to see if it is possible to be more selective in which branches should receive this term, or possibly to not propagate the term `odorant binding` to members of the lipocalin family.

Thanks,

-Karen

**Comment by pgaudet** [comment]
Thanks for reporting this. I propagated to a narrower clade.
