### ISSUE TITLE
missing parent "GO:0032220 | plasma membrane fusion involved in cytogamy"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3573]
-  deleted original comment as it is misleading -

plasma membrane fusion involved in cytogamy
 should  NOT be related to 
cell morphogenesis involved in conjugation with cellular fusion
the annotation to dni1 should not be transferred, dni1 is involved in a step after  shmooing.

**Comment by pgaudet** [comment]
For both families: PTHR15706 (PTN000838580) and PTHR28092 (PTN001999077 ) 

I removed the propagation of 'plasma membrane fusion involved in cytogamy'
and 'cell morphogenesis involved in conjugation with cellular fusion'

 and replaced by  GO:0000747  conjugation with cellular fusion, which is annotated in both pombe and cerevisiae. 


I hope that's OK? 

Those all look like various aspects of the same process, it's very hard to decide what to annotate to, especially given that the MF is not clear. 

Thanks, Pascale

**Comment by ValWood** [comment]
yes thats fine.
