### ISSUE TITLE
not vacuolar PTN001920909 - PTHR23502

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3577]
In fission yeast these aren't vacuolar transporters (vacuole is probably only the catabolism location for these in cerevisiea)

mfc1	
IBA  with PTN001920909 , S000005799 , S000003951	Gaudet P et al. (2011)
mfs2	
IBA  with S000003951 , S000005799 , PTN001920909	Gaudet P et al. (2011)
mfs3	
IBA  with S000005799 , S000003951 , PTN001920909

**Comment by pgaudet** [comment]
Fixed.
