### ISSUE TITLE
Mouse Annotation of Nudt1 to dGTP  need to be reviewed

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3582]
The manual annotation of the mouse Nudt1 gene to GO:0006203 “dGTP catabolic process” based on experimental evidence, are wrong. The term definition is “The chemical reactions and pathways resulting in the breakdown of dGTP, guanosine triphosphate.” NUDT1, however, is a 7,8-dihydro-8-oxoguanine triphosphatase, with measurable but 17-fold weaker activity on dGTP than on 8-hydroxy-dGTP (kinetic data are not shown for the mouse protein). (The UniProt assignment of MF GTPase activity seems similarly wrong.)
PMID:7592783

**Comment by hdrabkin** [comment]
removed; ISOs wil go away when UniProt fixes.
