### ISSUE TITLE
Review Paint annotations to AOX family - PTHR11908

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3583]
In reviewing purine catabolism, we noted that members of the AOX family of proteins (Aox1,Aox2,Aox3,Aox4 mouse) are annotated to xanthine dehydrogenase activity (GO:0004031 )based on Paint propagation. We cannot find any evidence that these proteins have this catalytic activity.
A relevant publication that discusses the evolution of this protein family is here: PMID:17301077.

**Comment by pgaudet** [comment]
Please next time can you give some ID ? Protein ID / PTHR / PTN would be appreciated ! 

Thanks, Pascale

**Comment by deustp01** [comment]
Aox1 O54754
Aox2 Q5SGK3
Aox3 G3X982
Aox4 Q3TYQ9

**Comment by ukemi** [comment]
No worries:
PANTHER:PTN000935735
Mouse proteins are O54754, Q5SGK3, Q6V957, Q3TYQ9.

**Comment by pgaudet** [comment]
Fixed, thanks for reporting.
