### ISSUE TITLE
InterPro2GO for IPR007266 IPR037192

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3587]
ERO1-like superfamily (IPR037192)
Endoplasmic reticulum oxidoreductin 1 (IPR007266)

Please remove "protein disulfide isomerase activity (GO:0003756)" from both.

Both descriptions state "The activity of Ero1 is regulated by Pdi1, which is a protein disulfide isomerase." - i.e. Ero1 doesn't have disulfide isomerase activity itself. Also see #3276

@EBI-Hsinyu
@sarach06 

@hattrill

**Comment by sarach06** [comment]
Hi!
Yes, you're right. Thank you very much. I have removed the term from both entries. The changes will be available in the next InterPro release 84.0.

Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
