### ISSUE TITLE
Review annotations to 'P-type divalent copper transporter activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3589]
Hello, 
I created the term 'GO:0140581 P-type **monovalent** copper transporter activity' for https://github.com/geneontology/go-ontology/issues/20699 and it looks like existing annotations to 'GO:0043682 P-type **divalent** copper transporter activity' are incorrect. 

I created a spreadsheet to review the annotations: https://docs.google.com/spreadsheets/d/1EKIvjzUPQwgCTk3F4LJdjK06hEGNYIp_4a_BtO9T0XU/edit#gid=0

There are 4 MGI and 1 CGD annotations to review. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1EKIvjzUPQwgCTk3F4LJdjK06hEGNYIp_4a_BtO9T0XU/edit#gid=0

Please note that I just created the term a few minutes ago; the term will be available with some delay, depending on release cycles.

**Comment by hdrabkin** [comment]
Why are they wrong? Are you implying that they should be monovalent Cu? the genes annotated are named 'Cu++ transporting' ; I haven't looked at the refs yet because until I get the replacement term if needed, I won't actually do anything.

**Comment by pgaudet** [comment]
@hdrabkin this is what I wrote in the comment inthe spreadsheet: "Described in Uniprot as an Cu1 transporter; also change gene product in MGI ? "

**Comment by hdrabkin** [comment]
This make take a while if this means a nomen event.

**Comment by pgaudet** [comment]
is 'nomen' = nomenclature ? I dont see how that affects the GO annotations.

**Comment by hdrabkin** [comment]
The suggestion above was that the gene is mis-named , because the official gene name for the first one is 
  | Atp7a | ATPase, Cu++ transporting, alpha polypeptide
implying divalent copper
So, our nomen group needs to be advised if this is really not a divalent copper transporter.

**Comment by hdrabkin** [comment]
Same for Atp7b

**Comment by hdrabkin** [comment]
THe papers used for assays in these annotations are using CuCl2 (which is Cu++, NOT Cu+_
We will also check with HGNC, who we co-ordinate with

**Comment by hdrabkin** [comment]
From nomen:
. HGNC have renamed their ATPases with the word copper replacing Cu++. I will be happy to update ours to agree. It should be public in about two weeks.
This still does not explain the papers using CuCl2 for their assays. I wonder if actually it can do both.

**Comment by suzialeksander** [comment]
@hdrabkin did you ever resolve this? looks like the annotations still exist.

**Comment by deustp01** [comment]
@LiNiMGI Do you know the answer to this, or can you check in the appropriate place in MGI? (Or have I misunderstood and someone else inherited this problem from Harold?)

**Comment by LiNiMGI** [comment]
@deustp01 Thanks, i will take a look.  Li

**Comment by LiNiMGI** [comment]
Assays used in both papers for these MGI annotations are using CuCl2. 
Also a review article PMID:32333855 says Atp7a is a Cu2 transporter, so it might actually can do both. 
I will keep the MGI annotation and close this ticket for now. 
Thanks, Li
