### ISSUE TITLE
UniProtKB:O43181 NADH dehydrogenase [ubiquinone] iron-sulfur protein 4, mitochondrial not  "cAMP-mediated signalling"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3592]
UniProtKB:O43181	NADH dehydrogenase [ubiquinone] iron-sulfur protein 4, mitochondrial		GO:0019933		UniProt	NCBITaxon:9606	IMP		PANTHER:PTHR12219	protein		PMID:11165261	20070302
UniProtKB:O43181	NADH dehydrogenase [ubiquinone] iron-sulfur protein 4, mitochondrial		GO:0019933		UniProt	NCBITaxon:9606	IMP		PANTHER:PTHR12219	protein		PMID:11181577	20070302

This appears to be downstream of cAMP-signalling pathway.

(phosphorylated by cAMP-dependent protein kinase)

**Comment by sylvainpoux** [comment]
Hi Val,
I agree. I deleted these annotations
Cheers
Sylvain

**Comment by ValWood** [comment]
Wow speedy!
