### ISSUE TITLE
Mouse MGI:2140950 (Q91YI6) Tent2 is active in the cytoplasm

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3595]
Hello 

Mouse Tent2 MGI:2140950 is active in cytoplasm - the paper cited for nucleus localization PMID:17927953 does not show data supporting this annotation. 

Came across while fixing https://github.com/geneontology/go-annotation/issues/3585

Thanks, Pascale

**Comment by ukemi** [comment]
Figure 2a?

**Comment by hdrabkin** [comment]
@ukemi yep;

**Comment by pgaudet** [comment]
OK - still this looks weak WRT to the localization of the activity of the enzyme, we wont propagate. 

Thanks for checking.

**Comment by deustp01** [comment]
Interesting - the [UniProt entry for human TENT2](https://www.uniprot.org/uniprot/Q6PIY7) starts with text describing "Cytoplasmic poly(A) RNA polymerase ...", which makes sense given its function, but then in its [subcellular location](https://www.uniprot.org/uniprot/Q6PIY7#subcellular_location) section assigns it to the nucleus by similarity to mouse.

**Comment by hdrabkin** [comment]
because the mouse annotation shows both nuclear and cytoplasmic localization via fractionation.

**Comment by pgaudet** [comment]
Right - we could specific this with 'located in' rather than 'is active in'.

**Comment by hdrabkin** [comment]
My understanding is that the CC annotations qualifier will be 'located in'

**Comment by pgaudet** [comment]
Depends if the gene is found in a place or if it's where it's active. Ideally we would end up annotating 'is active in' for gene products for which we know the function.
