### ISSUE TITLE
IPR029404 CDAN1-interacting nuclease 1

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3596]
IPR029404 CDAN1-interacting nuclease 1 is associated with  differentiation (GO:0030218)

But this family is found in organisms without erythrocytes. Could you remove this association?

@EBI-Hsinyu
@sarach06

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have removed the term from this entry, the changes will be visible in the next InterPro release (84.0).

Best regards,
Sara

**Comment by hattrill** [comment]
That was quick! Thanks.
