### ISSUE TITLE
PANTHER:PTN001998674 - PTHR28069 Mss51 not mitochondrial translation in fission yeast (likely other orgs)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3597]
PMID:22349564
Title | Schizosaccharomyces pombe homologs of the Saccharomyces cerevisiae mitochondrial proteins Cbp6 and Mss51 function at a post-translational step of respiratory complex biogenesis.

In this study we have investigated the function of Mss51, Cbp3 and Cbp6 in S. pombe, and found that they only act at post-translational steps in mitochondrial biogenesis. Since the functions of Mss51, Cbp3 and Cbp6 conserved in these two widely divergent species are post-translational, our findings suggest that their role in respiratory complex assembly may be their ancestral role, while their role in controlling budding yeast translation may be a specialized adaptation for facultative anaerobiosis.

mss51 | mitochondrial Cox1 translation regulator Mss51 (predicted) |   | translation regulator activity |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001998674SGD:S000004193 | gh20023p pthr28069 | protein |   | PMID:21873635 | 20170228

  | mss51 | mitochondrial Cox1 translation regulator Mss51 (predicted) |   | positive regulation of mitochondrial translation |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001998674SGD:S000004193 | gh20023p pthr28069 | protein |   | PMID:21873635 | 20170228

**Comment by pgaudet** [comment]
Removed annotations.
