### ISSUE TITLE
PTN000256836 - PTHR12184 cbp3 not mitochondrial translation in f.y. (possibly not ancestral role)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3598]
pombe cbp3
GO:0070131 | positive regulation of mitochondrial translation | IBA with S000006136 , Q9NVA1 , PTN000256836

PMID:22349564
Title | Schizosaccharomyces pombe homologs of the Saccharomyces cerevisiae mitochondrial proteins Cbp6 and Mss51 function at a post-translational step of respiratory complex biogenesis.

In this study we have investigated the function of Mss51, Cbp3 and Cbp6 in S. pombe, and found that they only act at post-translational steps in mitochondrial biogenesis. Since the functions of Mss51, Cbp3 and Cbp6 conserved in these two widely divergent species are post-translational, our findings suggest that their role in respiratory complex assembly may be their ancestral role, while their role in controlling budding yeast translation may be a specialized adaptation for facultative anaerobiosis.

**Comment by pgaudet** [comment]
Fixed
