### ISSUE TITLE
SAC domain (IPR002013) InterPro2GO

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3603]
This currently has the GO MF "phosphoric ester hydrolase activity (GO:0042578)" but from the description, I think this can be improved to use the child term "phosphatase activity (GO:0016791)".
Can you check please?

@EBI-Hsinyu 
@sarach06

**Comment by sarach06** [comment]
Hi!
I've checked and I agree with you, so I changed the term for GO:0016791.

Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
