### ISSUE TITLE
DNA double-strand break repair protein Mre11 (IPR003701)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3605]
Current MF are:
- endonuclease activity (GO:0004519)
- 3'-5' exonuclease activity (GO:0008408)

Since DNA is the substrate for both activities, I think these can be improved to:
-  endodeoxyribonuclease activity (GO:0004520)
- 3'-5'-exodeoxyribonuclease activity (GO:0008296)

@EBI-Hsinyu 
@sarach06

**Comment by sarach06** [comment]
Hi Steven,
Yes, thank you very much for this. I've improved those terms for the entry, which will be visible in the next InterPro release (84.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks again!
