### ISSUE TITLE
Pombase GPI column 10 DB-XRefs should be a CURIE

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-annotation#3607]
Looking at the latest Pombase GPI file at https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi it looks like entries in column 10, the db-xrefs column, are all the identifier part of what should maybe be UniProtKB CURIEs.

For example, on the second GPI entry:
```
PomBase:SPAC1002.02     pom34   pom34   mug31   SO:0001217      NCBITaxon:4896                          Q9US56  go-annotation-summary=nucleoporin Pom34
```
we have `Q9US56`.

I believe this is referring to `UniProtKB:Q9US56` at https://www.uniprot.org/uniprot/Q9US56.

Tagging @vanaukenk and @ValWood

**Comment by mah11** [comment]
@kimrutherford is the one to tag for file issues. I've also alerted him on our active GPAD/GPI ticket.

**Comment by kimrutherford** [comment]
Thanks for the feedback.

We've added a "UniProtKB:" to all the UniProt IDs in column 10.  Is that what's needed or should we use URLs for the UniProt IDs?

**Comment by dougli1sqrd** [comment]
No, everything seems great now! I was able to parse the file as GPI 2.0 just fine and it seemed to load just fine on my end! Thanks!
