### ISSUE TITLE
Yeast RSC3 NOT DNA translocase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3609]
Hello, 
RSC3 is annotated to contributes_to DNA translocase activity; however this is part of a complex that has translocase activity, but itself is not a translocase. sth1 is the translocase

Can you review and consider removing the annotation ? 

Thanks, Pascale

@colinlog

**Comment by pgaudet** [comment]
Same for all RSC's ; can you please have a look ?

**Comment by srengel** [comment]
will do.

**Comment by srengel** [comment]
tagging @suzialeksander to please help because i didn't get to this last week.

**Comment by suzialeksander** [comment]
I *think* this is done.  There were several RSCs and other proteins all annotated to contributes_to DNA translocase activity, I think I got them all

**Comment by pgaudet** [comment]
thanks !
