### ISSUE TITLE
InterPro2GO - IPR006689

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3612]
Small GTPase superfamily, ARF/SAR type
IPR006689

From title and description, seems we could add "GTPase activity GO:0003924" to this term.
Could you check please?

@sarach06  @EBI-Hsinyu

**Comment by sarach06** [comment]
Hi,
Many thanks! I've checked and yes, the term could be added. It will be visible in the next release (InterPro 85.0).

Best,
Sara

**Comment by sjm41** [comment]
Great, thanks!
