### ISSUE TITLE
V-ATPase subunit ATPase annotations in PAINT - should be 'contributes to'

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3616]
The following PAINT nodes add compound ATPase/transporter MF terms to subunits of the V-ATPase - the terms are appropriate, but they all lack the 'contributes to' relation, which should be added.
Source annotations are from dictyBase, SGD, MGI, RGD, ZFIN, TAIR and EnsemblGenome - @pfey03 @srengel @hdrabkin @slaulederkind @sabrinatoro @tberardini 

**PTN000813763 / V-TYPE PROTON ATPASE PROTEOLIPID SUBUNIT (PTHR10263)**
proton-transporting ATPase activity, rotational mechanism IBD	PTN000029688 (DICDI|dictyBase=DDB_G0274381|UniProtKB=P54642)

**PTN000179505 / VACUOLAR PROTON ATPASES (PTHR11629)**
proton-transporting ATPase activity, rotational mechanism IBD	PTN000179664 (YEAST|SGD=S000005796|UniProtKB=P32563)
proton-transporting ATPase activity, rotational mechanism IBD	PTN000179661 (YEAST|SGD=S000004658|UniProtKB=P37296)

**PTN000111953 / VACUOLAR ATP SYNTHASE SUBUNIT AC39 (PTHR11028)**
proton-transporting ATPase activity, rotational mechanism IBD	PTN000111993 (MOUSE|MGI=MGI=1201778|UniProtKB=P51863)
proton-transporting ATPase activity, rotational mechanism IBD	PTN000112022  (YEAST|SGD=S000004439|UniProtKB=P32366)

**PTN001015339 / VACUOLAR ATP SYNTHASE SUBUNIT F (PTHR13861)**
ATPase-coupled ion transmembrane transporter activity IBD	PTN000355409 (RAT|RGD=621552|UniProtKB=P50408)

**PTN005238491 / ATPASE H+-TRANSPORTING V1 SUBUNIT E1A-RELATED (PTHR45715)**
proton-exporting ATPase activity, phosphorylative mechanism IBD	PTN000172047 (MOUSE|MGI=MGI=1922165|UniProtKB=Q9D593)
proton-exporting ATPase activity, phosphorylative mechanism IBD	PTN000172060 (MOUSE|MGI=MGI=894326|UniProtKB=P50518)
proton-exporting ATPase activity, phosphorylative mechanism IBD	PTN000172080 (DANRE|ZFIN=ZDB-GENE-020419-11|UniProtKB=Q6NWK4)

**PTN002268884 / V-TYPE ATP SYNTHASE SUBUNIT D (PTHR11671)**
proton-transporting ATPase activity, rotational mechanism IBD	PTN000186882 (NEUCR|EnsemblGenome=NCU08035|UniProtKB=O59941)

**PTN000015490 / V-TYPE PROTON ATPASE SUBUNIT C (PTHR10137)**
proton-transporting ATPase activity, rotational mechanism IBD	PTN000015531 (MOUSE|MGI=MGI=1913585|UniProtKB=Q9Z1G3)
proton-transporting ATPase activity, rotational mechanism IBD	PTN001299415 (ARATH|TAIR=locus=2010386|UniProtKB=Q9SDS7)
proton-transporting ATPase activity, rotational mechanism IBD	PTN000015510 (MOUSE|MGI=MGI=1916025|UniProtKB=Q99L60)

**Comment by ValWood** [comment]
Also for this family

GO:0005765 | lysosomal membrane | IBA with PTN000111953 , DDB_G0273071

yeast should not be lysosomal membrane. Taxon restriction applied for.

**Comment by pfey03** [comment]
GO:0005765 | lysosomal membrane should then be 'not in yeast'

**Comment by srengel** [comment]
sorry guys, i'm confused by this ticket.  i thought we were not supposed to be adding contributes_to to complex members?  i was expecting my task here would be to remove the direct 'enables' annotations, but instead i'm being asked to change 'enables' to 'contributes_to'?

please advise.

**Comment by sjm41** [comment]
Hi @srengel 
The difference here is that "proton-transporting ATPase activity, rotational mechanism" is a 'compound term' that effectively combines two molecular functions to represent the function of the V-ATPase complex.  No single subunit of the complex does "proton-transporting ATPase activity, rotational mechanism". This is the exceptional case where all subunits still have to get annotated with 'contributes to' (unless there are known to be 'accessory' in some way - in which case they wouldn't get any annotation to that term).
At least, that's my understanding.  @hattrill or @pgaudet can probably point us to the current doc on this.

**Comment by hattrill** [comment]
Hi @srengel

Here is a link to the presentation from the GOC meeting:
https://docs.google.com/presentation/d/1g-2M8XQuINGN6eKVT0Sqm1OsudF_kM2D4jemv-izTks/edit#slide=id.g77554c6e7f_0_76 and the guide on the wiki:http://wiki.geneontology.org/index.php/Contributes_to

The H+ transporting ATPase example falls into the class of 'irreducible molecular machines', where the MF 'proton-transporting ATPase activity, rotational mechanism' cannot be ascribed to an individual subunit or a descrete few subunits. In these cases, 'contributes_to' should be used.

**Comment by srengel** [comment]
thanks @sjm41 and @hattrill that's helpful info.  i'll fix these...

**Comment by srengel** [comment]
ok all done.  added contributes_to to the 3 YEAST annotations listed above.  in P2GO, just now.

**Comment by sjm41** [comment]
Thanks @srengel. I just assigned this ticket to reps from the other relevant MODs.

**Comment by slaulederkind** [comment]
RGD has no manual annotation to this term.  The only annotations to this term at RGD are imports from PAINT.

**Comment by tberardini** [comment]
I updated the single TAIR IGI annotation.

**Comment by sjm41** [comment]
Hi @slaulederkind - the PTN001015339 PAINT page and the protein2GO tool say that RGD has this IDA annotation:

RAT\|RGD=621552\|UniProtKB=P50408 (Atp6v1f)
ATPase-coupled ion transmembrane transporter activity (GO:0042625) IDA from PMID:8621738

Can you add a 'contributes_to' relation to that annotation?
Thanks.

**Comment by hdrabkin** [comment]
mgi done

**Comment by pfey03** [comment]
added contributes_to to our GO:0046961 proton-transporting ATPase activity, rotational mechanism IDA

**Comment by ValWood** [comment]
The docs here seem to be out of date:
http://geneontology.org/docs/go-annotations/
this says" Furthermore, contributes_to may be used for any non-catalytic subunit, whether the subunit is essential for the activity of the complex or not."

**Comment by hattrill** [comment]
Can you update this  to match the wiki http://wiki.geneontology.org/index.php/Contributes_to @vanaukenk @pgaudet

**Comment by hdrabkin** [comment]
@ValWood That DOES seem odd because then why would you say it contributes to an activity?

**Comment by ValWood** [comment]
Who knows ;) 

It seems that all of this should be in the main docs:
So that people don't assume it is used for non-catalytic subunits that contribute to the activity in some way but are not part of the "catalytic site".

All subunits of the complex should be assigned the activity using the 'contributes_to' qualifier if the complex can be described as an irreducible molecular machine.
For example, if a gene product is part of a complex but only has the function as part of that complex, e.g. forms a composite catalytic site that is required for the function, annotate to the molecular function using the qualifier 'contributes_to'.

**Comment by sabrinatoro** [comment]
ZFIN annotation has been updated

**Comment by sjm41** [comment]
Looks like this is all done except for the RGD annotation.

@slaulederkind - you said above that "RGD has no manual annotation to this term. The only annotations to this term at RGD are imports from PAINT."
But I still see this IDA annotation from RGD in the P2GO tool:
**RAT|RGD=621552|UniProtKB=P50408 (Atp6v1f)
ATPase-coupled ion transmembrane transporter activity (GO:0042625) IDA from PMID:8621738**

Can you add a 'contributes_to' relation to that annotation?

Or are you saying that annotation has already been deleted/modified in the RGD files?

**Comment by slaulederkind** [comment]
Hi Steven,  I don’t know where you are looking at the errant QC data, but look at the following screenshot from the public RGD website.  Your favorite annotation is Source: GO_Central with evidence code of IBA.  You can email me 10 more times asking me to fix the annotation, but the answer will remain the same:  RGD did not create that annotation.


***@***.***D71BDB.7B154BE0]

**Comment by sjm41** [comment]
And yet this is what I see in the P2GO tool and on the PAINT site:
![Screenshot 2021-03-18 at 14 50 10](https://user-images.githubusercontent.com/16306861/111646506-9e74e700-87f9-11eb-9a85-0890eba8c508.png)
![Screenshot 2021-03-18 at 14 53 05](https://user-images.githubusercontent.com/16306861/111646586-b0568a00-87f9-11eb-8692-657a745bca4f.png)

Can anyone tell what the disconnect is here?

Regardless, sounds like this will now need to be fixed directly on the PAINT side, so I'll reassign this to Marc/Pascale.

**Comment by sjm41** [comment]
Hi @marcfeuermann, @pgaudet 
I just checked again, and the P50408 source annotation that lacked the 'contributes to' relation (that was somehow attributed to RGD) has now disappeared from the P2G interface.  So, that annotation will be discounted as a source for the PTN001015339 node in the fullness of time, though it's still shown there currently (http://www.pantree.org/node/annotationNode.jsp?id=PTN001015339).

Do you want to keep this ticket open or shall we close now?
