### ISSUE TITLE
Review annotations to S000003135 and WBGene00004063

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3617]
Hello, 

S000003135 and WBGene00004063 are annotated to 'GO:0015410 manganese transmembrane transporter activity, phosphorylative mechanism'; but this term was actually describing an ABC transporter. I have now changed the term label but the annotations should be move, I think to  GO:0005388 P-type calcium transporter activity, which corresponds to the EC assigned to those entries EC:7.2.2.10. From what I understand the main substrate is calcium but the proteins also transport manganese. 

Thanks, Pascale

**Comment by srengel** [comment]
Hi @pgaudet this one doesn't make sense to me.  S000003135 is characterized as having "selectivity profile of Mn(2+) > Ca(2+)".  the two GO terms are siblings, and the gene is annotated to both.  looking at GO:0015410 and GO:0005388 side-by-side (names, placement, and definitions), how is a curator or user supposed to know that one is valid and one isn't?  you're asking that i remove the manganese annotation but keep the calcium annotation?  please advise.

**Comment by pgaudet** [comment]
Hi @srengel 
I now created GO:0140613 P-type manganese transporter activity, you can annotate to this term instead. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@srengel The issue was the type of transporter, not the substance transported. Can you use the new term GO:0140613 P-type manganese transporter activity instead? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
WB annotations have been updated.

**Comment by srengel** [comment]
SGD annotation has been updated some time ago.  closing.
