### ISSUE TITLE
InterPro2GO: Tubulin/FtsZ, GTPase domain (IPR003008)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3619]
This domain is associated with all tubulins (alpha, beta and gamma), at least in Drosophila.

It is associated with the GO MF "GTPase activity (GO:0003924)" and has this def:
This entry represents a GTPase domain found in all tubulin chains, such as tubulin alpha, beta and gamma chains, and some bacterial FtsZ proteins [1]. These proteins are involved in polymer formation. Tubulin is the major component of microtubules, while FtsZ is the polymer-forming protein of bacterial cell division, it is part of a ring in the middle of the dividing cell that is required for constriction of cell membrane and cell envelope to yield two daughter cells [2, 3]. FtsZ and tubulin are GTPases, this entry is the GTPase domain. FtsZ can polymerise into tubes, sheets, and rings invitro and isubiquitous in bacteria and archaea.

alpha-beta tubulin dimers do have GTPase activity, though I can't work out whether it's just the beta subunit or the alpha-beta interface that is implicated in GTPase activity.  (good review: https://www.frontiersin.org/articles/10.3389/fpls.2014.00511/full)

But Reference 1 in the def and the review given above don't mention gamma tubulin - it's not a GTPase as far as I can tell - any one else know?

So I'm wondering if 'GTPase activity' should be removed from this InterPro entry.  Perhaps replace with 'GTP binding'?  Thoughts?

@sarach06 @EBI-Hsinyu

**Comment by sarach06** [comment]
Hi,
Thank you for this. I agree with you that 'GTPase activity' should be removed. I agree with you, that gamma tubulin binds GTP and doesn't have GTPase activity (https://www.nature.com/articles/ncb2863, https://www.nature.com/articles/s42003-018-0037-3, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6214090/). I will replace the term for GTP binding.

Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara!

**Comment by sjm41** [comment]
Hi @sarach06 
I notice that  'GTPase activity' is still associated with IPR003008 as of InterPro release 87.  Did this removal get missed?

**Comment by sarach06** [comment]
Hi Steven,
Thank you for pointing this and my apologies (I probably forgot to remove the term when adding the other one, my bad). It is now removed.
Best regards,
Sara

**Comment by sjm41** [comment]
OK, thanks @sarach06 !
