### ISSUE TITLE
Review annotations to  GO:0000733 DNA strand renaturation and  GO:0061306 DNA strand renaturation involved in double-strand break repair

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3621]
Dear all, 

The proposal has been made to obsolete GO:0000733 DNA strand renaturation and  GO:0061306 DNA strand renaturation involved in double-strand break repair, and consider replacing by 'GO:0036310 annealing helicase activity'. 
See https://github.com/geneontology/go-ontology/issues/14671

Please review your annotations: 

Contributor   (Assigned by)
--
CGD | 1
FlyBase | 3
RGD | 1
SGD | 9
UniProt | 14

Thanks, Pascale

**Comment by hattrill** [comment]
Fixed ours. Only had 2 annotations that I could see.

**Comment by pgaudet** [comment]
@hattrill Right, the interontology links are confusing. Thanks !

**Comment by srengel** [comment]
removed the 9 for SGD just now in P2GO.

**Comment by gthayman** [comment]
RGD has no manual GO annotations to either term.

**Comment by marekskrzypek** [comment]
CGD done

**Comment by pgaudet** [comment]
Thanks !
