### ISSUE TITLE
InterPro:IPR014314 & InterPro:IPR018495 & IPR000701

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3624]
**Succinate dehydrogenase, cytochrome b556 subunit (InterPro:IPR014314)**
succinate dehydrogenase activity (GO:0000104)

**Succinate dehydrogenase, cytochrome b subunit, conserved site (InterPro:IPR018495)**
succinate dehydrogenase activity (GO:0000104)
electron transfer activity (GO:0009055)

Both these entries are for the SdhC subunit of Succinate dehydrogenase, but that subunit is not involved in the Succinate dehydrogenase reaction (SdhA does that), though they do participate in electron transfer (https://en.wikipedia.org/wiki/Succinate_dehydrogenase_complex_subunit_C#Function)

So, I think GO:0000104 needs removing from both entries, and GO:0009055 could be added to 
IPR014314.

@sarach06 @EBI-Hsinyu

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have done the changes you mentioned, which will be visible in the next InterPro release (85.0).

Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!

**Comment by sjm41** [comment]
Hi @sarach06 
I just noticed that "oxidoreductase activity, acting on the CH-CH group of donors (GO:0016627)" should be removed from the parent InterPro term "Succinate dehydrogenase/fumarate reductase type B, transmembrane subunit" (IPR000701) for the same reason as stated above.

**Comment by sarach06** [comment]
Hi!
Thanks! I've removed it. The changes will be available in the next InterPro release (85.0).

Best,
Sara

**Comment by sjm41** [comment]
Hi @sarach06 

I just had cause to look at these annotations again and realised I'd made an oversight in what I wrote above.
While it is just the SdhA subunit that oxidises succinate to fumarate, the other three subunits (SdhB, C, D) are all needed to concomitantly reduce ubiquinone to ubiquinol (via electron transfer).  And GO:0008177 is defined as including both these aspects: "Catalysis of the reaction: succinate + ubiquinone = fumarate + ubiquinol".

So, it is correct to have GO:0000104 on IPR014314 and IPR018495 after all, and fine to have GO:0016627 on the parent IPR000701.

Very sorry about this....

**Comment by sarach06** [comment]
Hi,
No worries. I've re-added the terms to the entries. They will be visible in the next InterPro release (86.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara! 👍

**Comment by sjm41** [comment]
....Deep breath...

Hi @sarach06 
The InterPro annotations mentioned above came up in another cross-check I was running, so I had yet another (deeper) look at them and the current view of the functions of the 4-subunit SDH complex. Here's what I see:

UniProt descriptions and manually curated GO/EC/RHEA annotations for the human proteins (at least) say that subunits A and B are 'catalytic' (GO:0008177/EC:1.3.5.1/Rhea 40523], while subunits C and D are 'Membrane-anchoring subunits'. (Though all subunits function in 'electron transfer'.)

Consistent with that view, I now see that the SDHC wikipedia page mentioned above says that "The encoded protein (SDHC) is one of two integral membrane proteins that anchor other subunits of the complex, which form the catalytic core, to the inner mitochondrial membrane."
That is, SDHA and SDHB form the "catalytic core".

Furthermore, a very recent and comprehensive review on the SDH complex (PMID: 37490987) says:
"**SDHA and SDHB are covalently bound by FAD and three Fe–S clusters to jointly form the soluble subunits, which form a catalytic heterodimer**[18]. In addition, the C-terminal domain of SDHB has been reported to play an important role in linking the SDHB-SDHA subunit to the SDHC-SDHD subunit [12]. The hydrophobic domain is composed of the SDHC-SDHD dimer, which anchors the whole complex to the IMM."

So...it now seems clear that there shouldn't be any catalytic annotations for the two inner membrane subunits, SDHC/D, which means the following InterPro2GO associations should be removed after all:

- IPR014314 Succinate dehydrogenase, cytochrome b556 subunit -> succinate dehydrogenase activity (GO:0000104))
- IPR018495 Succinate dehydrogenase, cytochrome b subunit, conserved site -> succinate dehydrogenase activity (GO:0000104))
- IPR000701 Succinate dehydrogenase/fumarate reductase type B, transmembrane subunit -> oxidoreductase activity, acting on the CH-CH group of donors (GO:0016627)
- IPR014312 Succinate dehydrogenase, hydrophobic membrane anchor -> succinate dehydrogenase activity (GO:0000104)

I think/hope this is my final word on these entries!

**Comment by sarach06** [comment]
Hi @sjm41 
Thank you very much for the update and deep analysis, plus the new reference. I have removed the terms from the entries you listed and added the reference. These changes will be visible in InterPro 97.0.
Best regards,
Sara

**Comment by sjm41** [comment]
Hi @sarach06

I still see this annotation in InterPro 97.0:
IPR000701 Succinate dehydrogenase/fumarate reductase type B, transmembrane subunit -> oxidoreductase activity, acting on the CH-CH group of donors (GO:0016627)

Can that be removed?
