### ISSUE TITLE
InterPro2GO for Cytochrome b-c1 complex subunits

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3633]
Hi @sarach06, @EBI-Hsinyu 

Several InterPro entries for non-catalytic (non-redox) subunits of the Cytochrome b-c1 complex (complex III) appear to have incorrect MF terms and missing CC/BP terms.  Haven't done an exhaustive check, but I came across these:

**Cytochrome b-c1 complex, subunit 6 (IPR003422)**
- remove MF "ubiquinol-cytochrome-c reductase activity (GO:0008121)"
- add CC "mitochondrial respiratory chain complex III (GO:0005750)"

**Cytochrome b-c1 complex subunit 8 superfamily (IPR036642)**
- remove MF "ubiquinol-cytochrome-c reductase activity (GO:0008121)"
- add CC "mitochondrial respiratory chain complex III (GO:0005750)"
- add BP "mitochondrial electron transport, ubiquinol to cytochrome c (GO:0006122)"

**Cytochrome b-c1 complex subunit 8 (IPR004205)**
- remove MF "ubiquinol-cytochrome-c reductase activity (GO:0008121)"
- add CC "mitochondrial respiratory chain complex III (GO:0005750)"
- add BP "mitochondrial electron transport, ubiquinol to cytochrome c (GO:0006122)"

**Cytochrome b-c1 complex subunit 9 (IPR008027)**
- remove "mitochondrial inner membrane (GO:0005743)" (that's a parent of the other CC term on the entry)

**Cytochrome b-c1 complex subunit 9 superfamily (IPR036656)**
- remove "mitochondrial inner membrane (GO:0005743)" (that's a parent of the other CC term on the entry)

**Cytochrome b-c1 complex subunit 10 (IPR015089)**
- remove MF "ubiquinol-cytochrome-c reductase activity (GO:0008121)"
- remove MF "electron transfer activity (GO:0009055)"
- add CC "mitochondrial respiratory chain complex III (GO:0005750)"
- add BP "mitochondrial electron transport, ubiquinol to cytochrome c (GO:0006122)"

(Description on several of these entries correctly lists the 3 redox subunits of the complex:
The ubiquinol-cytochrome C reductase complex (cytochrome bc1 complex) is a respiratory multienzyme complex [1]. The bc1 complex contains 11 subunits; 3 respiratory subunits (cytochrome B, cytochrome C1, Rieske protein), 2 core proteins and 6 low molecular weight proteins.)

**Comment by sarach06** [comment]
Hi!
Thank you very much. I have done the changes you mentioned and I had a look at other subunits, adding/deleting the terms when necessary. The changes will be seen in the next InterPro release (85.0).

Best,
Sara

**Comment by sjm41** [comment]
Quick work - thanks!
