### ISSUE TITLE
InterPro2GO for Cytochrome c oxidase subunits

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3637]
Hi @sarach06, @EBI-Hsinyu

I'm now looking at InterPro entries for non-catalytic subunits of the cytochrome-c oxidase complex (complex IV).
The following refer to proteins that are characterised as 'supernumerary (non-catalytic) subunits' (e.g. PMID: 28870773 - Timón-Gómez et al 2018) so I think "cytochrome-c oxidase activity (GO:0004129)" should be removed from these entries:

Cytochrome c oxidase subunit IV family InterPro:IPR004203
Cytochrome c oxidase subunit IV superfamily InterPro:IPR036639
Cytochrome c oxidase, subunit Va/VI InterPro:IPR003204
Cytochrome c oxidase, subunit Va/VI superfamily InterPro:IPR036545
Cytochrome c oxidase, subunit Vb InterPro:IPR002124
Cytochrome c oxidase, subunit Vb superfamily InterPro:IPR036972
Cytochrome c oxidase subunit 6C InterPro:IPR004204
Cytochrome c oxidase subunit VIIa, metazoa InterPro:IPR003177
Cytochrome c oxidase, subunit VIIa superfamily InterPro:IPR036539
Cytochrome c oxidase subunit VIIc InterPro:IPR004202
Cytochrome c oxidase subunit VIIc superfamily InterPro:IPR036636
Cytochrome c oxidase, subunit 8 InterPro:IPR003205

(Consistent with this proposal, most of these entry descriptions say "In eukaryotes, in addition to the three large subunits, I, II and III, that form the catalytic centre of the enzyme complex are encoded within the mitochondrial genome, there are a variable number of small polypeptidic subunits encoded within the nuclear genome.")

(You might be able to add "mitochondrial respiratory chain complex IV (GO:0005751)" and "mitochondrial electron transport, cytochrome c to oxygen (GO:0006123)" CC and BP terms to some of these, but I guess that depends on whether the interpro terms also cover prokaryotic/bacterial proteins.)

**Comment by sarach06** [comment]
Hi!
Thank you very much! I have removed GO:0004129 from these entries and added the two you mentioned when suitable. The changes will be available in the next InterPro release (85.0).
Best,
Sara

**Comment by sjm41** [comment]
Hi

We missed this one in the previous review:
Cytochrome c oxidase, subunit VIa (IPR001349)
Can you remove GO:0004129 from that entry too please?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I have removed the term, this will be visible in the InterPro release 88.0.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!

**Comment by sjm41** [comment]
HI @sarach06 
We should also remove the MF "electron transfer activity (GO:0009055)" from 'Cytochrome c oxidase subunit VIIa, metazoa IPR003177'.  None of the other supernumerary (non-catalytic) subunits mentioned above have this MF term.

**Comment by sarach06** [comment]
Hi!
Thank you very much for this. I have removed the term. This will be visible in the next InterPro release.
Best,
Sara
