### ISSUE TITLE
PTN000129454  mitochondrial ribosomal protein not pre-miRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3641]
These mappings are to a fission yeast mitochondrial ribosomal protein O43042
mitochondrial ribosomal protein L44
(happens to have a "Ribonuclease III domain" )

GO:0031054 | pre-miRNA processing | IBA with locus:2024407 , DDB_G0268410 , MGI:1261425 , PTN000129454 | Gaudet P et al. (2011) | 2
- | GO:0031053 | primary miRNA processing | IBA with Q9NRR4 , WBGene00009163 , FBgn0026722 , PTN000129454 | Gaudet P et al. (2011) | 3
- | GO:0030422 | production of siRNA involved in RNA interference | IBA with DDB_G0268410 , A0A1D8PM62 , PTN000129454 , locus:2024407

**Comment by marcfeuermann** [comment]
Fixed.
