### ISSUE TITLE
InterPro2GO for non-catalytic subunits of mito. Complex I

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3642]
Hi @sarach06 , @EBI-Hsinyu 

The following InterPro entries are associated with "NADH dehydrogenase (ubiquinone) activity" and/or "NADH dehydrogenase activity", but correspond to proteins characterised as accessory/supernumerary (non-catalytic) subunits of complex I. (e.g.  PMID: 23527692, PMID: 31485716).

IPR009947
IPR009866
IPR008698
IPR008699
IPR016551
IPR009423
IPR012575

Can you removed these MF terms please?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much! I have removed the term/terms from these entries, updated the descriptions, names when required and added references. The changes will be available in the next InterPro release (85.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara - that sounds like a thorough revision!
