### ISSUE TITLE
make sure GPI 2.0 spec allows Property_Symbol to contain hyphens and underscores

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-annotation#3648]
Given the following definitions, it doesn't seem like a header line like `!generated-by: MGI` will be considered valid. `generated-by` isn't an ID because it doesn't have a colon (although it precedes the colon which is part of the header line). It isn't Alphanumeric because it contains a hyphen. The spec explicitly adds hyphens and colons to the Prefix part of an ID, but not to a non-ID Property_Symbol.

```
GPI_Header_Line ::=
   '!' Property_Symbol ':' Space* Value nl |
   '!!' (Char - nl)* nl
```

```
Property_Symbol ::= ID | Alphanumeric
```

```
Alpha_Char ::= a |b |c |d |e |f |g |h |i |j |k |l |m |n |o |p |q |r |s |t |u |v |w |x |y |z
   | A |B |C |D |E |F |G |H |I |J |K |L |M |N |O |P |Q |R |S |T |U |V |W |X |Y |Z
Digit ::= 0 |1 |2 |3 |4 |5 |6 |7 |8 |9
Alphanumeric_Char ::= Alpha_Char | Digit
Alphanumeric ::= Alphanumeric_Char+
```

```
ID ::= Prefix ':' Local_ID
```

```
Prefix ::= Alphanumeric | '_' | '-'
```

**Comment by balhoff** [comment]
Is `Value` meant to be the same as `Property_Value`?

Could we redefine Property_Symbol like so?

```
Property_Symbol ::= ID | Prefix
```

I think we may want to enforce at least one space after the header line colon (rather than zero or more). Otherwise how do you know whether this property symbol is key `NS:text1` with value `text2` or key `NS:` with value `text1:text2`?

```
NS:text1:text2
```

**Comment by ValWood** [comment]
Hi @balhoff is this still current?

**Comment by balhoff** [comment]
No longer relevant, thanks.
