### ISSUE TITLE
COA6_HUMAN not plasma membrane ATP synthesis coupled electron transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3649]
Cytochrome c oxidase assembly factor 6 homolog
Gene
COA6
has

plasma membrane ATP synthesis coupled electron transport Source: UniProtKB

**Comment by sylvainpoux** [comment]
Hi Val,

a clear curation error. Corrected to  GO:0042775 mitochondrial ATP synthesis coupled electron transport.

Thanks

Sylvain
