### ISSUE TITLE
P56134 (ATPK_HUMAN) not nuclear membrane?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3651]
ATP synthase subunit f, mitochondrial
Gene
ATP5MF

https://www.uniprot.org/uniprot/P56134#subcellular_location

ATP5MF | located_in | GO:0031965    nuclear membrane | ECO:0000314   IDA | GO_REF:0000052

**Comment by sylvainpoux** [comment]
This annotation is coming from a large scale paper. Please contact Penelope (@pgarmiri )
Again, a dispute would be more appropriate
Thanks
Sylvain

**Comment by pgarmiri** [comment]
Hi @ValWood ,
I just had a look in Protein2GO and I can't edit this annotation as it is coming from HPA (Human Protein Atlas tissue profile). 

The high-throuput annotation that Sylvain mentioned was to 'Nucleus' and I have removed it.

Thanks,
Penelope

**Comment by ValWood** [comment]
so who can edit HPA (Human Protein Atlas tissue profile).?

**Comment by Antonialock** [comment]
@pgaudet  ?

**Comment by Antonialock** [comment]
I contacted the relevant group.

**Comment by ValWood** [comment]
@Antonialock  did this get resolved? If not let me know.
Maybe we need  some way to block external errors  (Like we do at PomBase)

**Comment by pgaudet** [comment]
I dont know if this can be 'fixed'. The HPA method detected this protein in the nuclear membrane for whatever reason. The annotation relation is 'located in', indicating that we dont know whether this is where the protein is active. 

I suggest we close.

**Comment by ValWood** [comment]
OK!

**Comment by ValWood** [comment]
We should be able to over-ride these though...

**Comment by Antonialock** [comment]
We thought at the minimum the evidence should change to HDA, the contact I had was Emma Lundgren emma.lundberg@scilifelab.se
