### ISSUE TITLE
P49406 not nuclear membrane?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3652]
9S ribosomal protein L19, mitochondrial
Gene
MRPL19

https://www.uniprot.org/uniprot/P49406#subcellular_location
nuclear membrane Source: UniProtKB
nucleus Source: UniProtKB

also

UniProtKB:O60783 | MRPS14 | located_in | GO:0031965    nuclear membrane | ECO:0000314   IDA | GO_REF:0000052 |   | 9606 Homo sapiens | HPA

and

UniProtKB:Q9Y3D9 | MRPS23 | located_in | GO:0031965    nuclear membrane | ECO:0000314   IDA | GO_REF:0000052 |   | 9606 Homo sapiens | HPA

**Comment by sylvainpoux** [comment]
deleted the annotation. Please note that it would be easier to Dispute annotations, since the dispute directly arrives to the curator
Thanks
Sylvain
