### ISSUE TITLE
remove centrosome annotations from yeast (lots)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3653]
I don't totally object to calling the SPB the centrosome (we could solicit community input on this). However at present we use SPB for these:

alp14 | GO:0005813 | centrosome | IBA with Q14008 , DDB_G0268616 , PTN000288762 , WBGene00006994 | Gaudet P et al. (2011) | 15
cdc13 |   | IBA with PTN002468700 , O95067 , 2294 , P14635 | Gaudet P et al. (2011)
cig1 |   | IBA with PTN002468700 , P14635 , O95067 , 2294 | Gaudet P et al. (2011)
cig2 |   | IBA with P14635 , PTN002468700 , O95067 , 2294 | Gaudet P et al. (2011)
clp1 |   | IBA with Q9UNH5 , ZDB-GENE-040426-1214 , PTN000596949 , WBGene00000383 | Gaudet P et al. (2011)
cut1 |   | IBA with WBGene00004775 , PTN000300670 , Q14674 | Gaudet P et al. (2011)
dis1 |   | IBA with DDB_G0268616 , PTN000288762 , WBGene00006994 , Q14008 | Gaudet P et al. (2011)
dli1 |   | IBA with PTN000293992 , FBgn0030276 | Gaudet P et al. (2011)
fin1 |   | IBA with DDB_G0270814 , PTN000686715 , P51955 , FBgn0029970 | Gaudet P et al. (2011)
gtb1 |   | IBA with P23258 , MGI:101834 , DDB_G0271738 , FBgn0260639 , MGI:2144208 , WBGene00006540 , FBgn0010097 , PTN000172659 | Gaudet P et al. (2011)
mzt1 |   | IBA with PTN002003414 , Q08AG7 | Gaudet P et al. (2011)
plo1 |   | IBA with WBGene00004042 , Q9H4B4 , FBgn0003124 , O00444 , PTN000679869 , P53350 , DDB_G0274503 , Q9NYY3 , MGI:97621 | Gaudet P et al. (2011)
rem1 |   | IBA with 2294 , P14635 , PTN002468700 , O95067 | Gaudet P et al. (2011)
tti2 |   | IBA with Q6NXR4 , PTN002084802

**Comment by ValWood** [comment]
and
GO:0031616 | spindle pole centrosome | IBA with O14965 , WBGene00000098 , PTN000681967

**Comment by alanbridge** [comment]
Not sure Val, I would run it by Iain Hagan and Keith Gull ;-)

**Comment by ValWood** [comment]
Yeah, OK I think I'll drop that.....Although increasingly people use interchangeably in manuscripts.
I get fed up of reading "the fission yeast centrosome, or spindle pole body"

**Comment by ValWood** [comment]
Like the one I just read:


PMID:32084401
--
Title | The Hydrophobic Patch Directs Cyclin B to Centrosomes to Promote Global CDK Phosphorylation at Mitosis.
Authors | Basu S, Roberts EL, Jones AW, Swaffer MP, Snijders AP, Nurse P
Publication date | 12 Feb 2020

**Comment by ValWood** [comment]
In fact:
 
Centrosomal MPF triggers the mitotic and morphogenetic switches of fission yeast.
Grallert A, Patel A, Tallada VA, Chan KY, Bagley S, Krapp A, Simanis V, Hagan IM.
Nat Cell Biol. 2013 Jan;15(1):88-95. doi: 10.1038/ncb2633. Epub 2012 Dec 9.

**Comment by ValWood** [comment]
We could go with "centrosome/spindle pole body" for GO.

I can deal with a hybrid, just not annotations to both....

**Comment by alanbridge** [comment]
OK I guess if Paul and Iain both use it you are probably safe from Keith :-)

**Comment by ValWood** [comment]
I'm more frightened of Keith :)

Anyway for now they are separate, I think the merge will be further in the future, and I worry that some of the processes might cause problems. There are a lot  of  process terms referring to the  SPB, so not worth considering until those are cleaned up.

**Comment by marcfeuermann** [comment]
We had this discussion many time. I think that we once decided to use "GO:0005815-Microtubule organizing center" for both SPB and centrosome. At least in PAINT, we could only propagate the parent term whenever we have primary annotations to one or the other.

**Comment by marcfeuermann** [comment]
Thanks to the latest (very fast loading and saving) version of our great tool, I could now go through all these families relatively quickly. All are reviewed now. Please, just do not tell me that the terms will be merged in a close future ;-)
