### ISSUE TITLE
human NUDT16 annotated to XDP catabolic process GO:1901639

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3655]
While reviewing nucleotide catabolism for the Pathways2GO project, we looked into this term as a possible extension of a Reactome import. This annotation is made as an IDA from PMID:20385596. In this paper, they assay for the enzyme using many different substrates and show that it is active on XDP catalyzing nucleotide phosphatase activity, acting on free nucleotides. Although this activity is real, I don't find any evidence that the enzyme catalyzes the reaction with XDP in a physiological setting. (Leads to an interesting discussion about annotation in and of itself). The enzyme probably works on IDP/dIDP (R-HSA-2509793, Id: R-HSA-2509816).
I have searched the literature using both PubMed and Google scholar and have looked at Kegg, Reactome and metacyc for evidence of the catabolism of XDP. Physiologically XTP is catabolized directly to XMP by ITPA (eg R-HSA-2509831) but I find no evidence for XTP catabolism going through XDP or XDP itself being catabolized. Could we please have this annotation reviewed and removed if you agree? If there is agreement, we will also make requests to have the process term obsoleted.
@deustp01 please feel free to comment.

**Comment by pgaudet** [comment]
The curator who made this annotation is not with Swiss-Prot anymore. 

Maybe the confusion comes from the statement "NUDT16 hydrolyzes purine nucleoside diphosphates to the corresponding nucleoside monophosphates" , and this was interpreted as XDP catabolic process, when it's just a conversion ? 

If this seems reasonable I'm happy to remove the annotation.

**Comment by pgaudet** [comment]
I think 'IDP catabolic process' can also be removed?

**Comment by ukemi** [comment]
https://reactome.org/PathwayBrowser/#/R-HSA-2509816
Don't think so.

**Comment by deustp01** [comment]
> this was interpreted as XDP catabolic process, when it's just a conversion

Conversion looks like a much better fit than catabolism, yes.

**Comment by deustp01** [comment]
> https://reactome.org/PathwayBrowser/#/R-HSA-2509816
> Don't think so.

This one is trickier. The Reactome reaction that @ukemi cites is part_of purine catabolism, and its intra-nuclear UMP output has no provides_input link to anything. However, that's probably a limitation of Reactome curation. Cytosolic UMP is an intermediate in purine biosynthesis ([this reaction](https://reactome.org/PathwayBrowser/#/R-HSA-8956320&SEL=R-HSA-73794&PATH=R-HSA-1430728,R-HSA-15869) and [this one](https://reactome.org/PathwayBrowser/#/R-HSA-8956320&SEL=R-HSA-111524&PATH=R-HSA-1430728,R-HSA-15869), and the UMP generated within the nucleus should be able to diffuse freely through the nuclear pore into the cytosol. So it is a real reaction exactly as @ukemi says and its output could be catabolized once it gets to the cytosol, but it can also be re-converted to AMP or GMP.

**Comment by ukemi** [comment]
I can't find any evidence that this is done physiologically. It looks like the aUthors just tried it as a substrate in an assay.

**Comment by ukemi** [comment]
For the tricky one, you are spot on @deustp01. This reaction and it's sibling convert IDP or dIDP (I think you mistyped) to IMP or dIMP. These are both in the nucleus and are part of the pathway Phosphate bond hydrolysis by NUDT proteins, which is part of Purine catabolism. So these are at least candidates for the first step in (d)IDP catabolism. I don't know the fate of the IMP output. But I'd hate to obsolete the term without actually looking more closely at the biology (with you).

**Comment by pgaudet** [comment]
As far as the annotation goes, should I also remove  'IDP catabolic process' ?

**Comment by ValWood** [comment]
Assigned to @pgaudet , with waiting for feedback from @ukemi or @deustp01

**Comment by deustp01** [comment]
> So these are at least candidates for the first step in (d)IDP catabolism. I don't know the fate of the IMP output. But I'd hate to obsolete the term without actually looking more closely at the biology (with you).

@ukemi while we continue to meditate on the deep problem of making specific causal connections between biological processes without going off the deep end and connecting everything to everything (because it is all interconnected in some sense, but we can't handle the resulting combinatorial explosion) would it be OK in the interest of tidiness and consistency to allow the removal Pascale proposed above on Feb 26, 2021?

**Comment by ukemi** [comment]
I guess so. Should I remove the annotation to Nudt9 for mouse? If we don't believe that IDP gets catabolized through IMP, I guess the answer is yes?

**Comment by ukemi** [comment]
Since the authors say the IDP is a non-physiological substrate of Nudt9, I removed the annotation.
