### ISSUE TITLE
PANTHER:PTN000504318 regulation of axon guidance  - PTHR22619

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3657]
For PANTHER:PTN000504318 

regulation of axon guidance  GO:1902667 

is not really a process that is appropriate to propagate for this family as it is an rather indirect process. 

This recent paper PMID:33184237 has been curated by UniProt for UniProtKB:A7E2V4 and other orthologs and shows a role in miRNA degradation and as a ubiquitin ligase-substrate adaptor, so there are now a better set of annotations to propagate from.

**Comment by pgaudet** [comment]
Fixed
