### ISSUE TITLE
InterPro2GO for IPR018152 (Superoxide dismutase, copper/zinc, binding site)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3662]
Hi @sarach06 @EBI-Hsinyu 

This binding-site entry has the GO MF "superoxide dismutase activity (GO:0004784)".

But the signature is found in non-catalytic CCS (Copper chaperone for superoxide dismutase) proteins, e.g.:
https://www.uniprot.org/uniprot/O14618
https://flybase.org/reports/FBgn0010531

So I think the term should be removed from the entry?

(also note that the description currently includes "These patterns will not detect proteins related to SODC, but which have lost their catalytic activity", which may not be quite true?)

**Comment by sarach06** [comment]
Hi, 
Thank you very much. I have removed the term from this entry and updated the abstract. The changes will be seen in the next release (InterPro 85.0).

Best,
Sara
