### ISSUE TITLE
Review annotations to GO:0007050 cell cycle arrest & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3664]
Dear all,

The following terms will be merged into 'GO:0051726 regulation of cell cycle'.

GO:0007050 cell cycle arrest
GO:0071850 mitotic cell cycle arrest
GO:0071156 regulation of cell cycle arrest
GO:0071157 negative regulation of cell cycle arrest
GO:0071158 positive regulation of cell cycle arrest

The reason for this change is that 'cell cycle arrest' is a measure of the cell cycle status, not a process in itself. In several instances, the genes annotated to cell cycle arrest are causing a pathological situation in the cell resulting activation of a cell cycle checkpoint; this does not mean that the genes are involved in cell cycle signaling in a normal situation. We have noticed several examples where cell cycle arrest is a phenotype, and the paper lack evidence that the gene is involved in cell cycle regulation.

There are 186 EXP annotations to the 5 terms mentioned above.
When reviewing annotations, if there is sufficient evidence for a role in cell cycle progression or exit from the cell cycle (G0), these terms can be considered for replacement:

GO:0000075 cell cycle checkpoint signaling or a descendant
GO:0070314 G1 to G0 transition
GO:0070315 G1 to G0 transition involved in cell differentiation

An 'easier' option would be to use the relation 'causally upstream of or within'.

Annotations are here: 
https://docs.google.com/spreadsheets/d/1vdei_8YbKKbgHHlPF-9LNQw10CKHwjbdE-09__-RasY/edit#gid=0

Contributor (Assigned by)| Number EXP 
--|--
BHF-all | 46
CACAO | 7
CAFA | 4
ComplexPortal | 1
FlyBase | 3
MGI | 26
ParkinsonsUK-UCL | 3
RGD | 6
SGD | 2
TAIR | 2
UniProt | 72
WB | 12
ZFIN | 1

Thanks, Pascale & Val

**Comment by pgaudet** [comment]
Note that this refers to the ontology ticket https://github.com/geneontology/go-ontology/issues/20935

**Comment by srengel** [comment]
removed the 2 SGD annotations just now from P2GO.

**Comment by hattrill** [comment]
FB done

**Comment by RLovering** [comment]
Hi 
sorry as usual I am slightly confused about the suggestions that have been made. In the statement:
>There are 186 EXP annotations to the 5 terms mentioned above.
>When reviewing annotations, if there is sufficient evidence for a role in cell cycle progression or exit from the cell cycle (G0), these terms can be considered for replacement:

>GO:0000075 cell cycle checkpoint signaling or a descendant
>GO:0070314 G1 to G0 transition
>GO:0070315 G1 to G0 transition involved in cell differentiation

>An 'easier' option would be to use the relation 'causally upstream of or within'.

Are you saying 'just change the current annotation to have the qualifier  'causally upstream of or within''? If so wouldn't it be more appropriate to say just change the current annotation to have the qualifier  'causally upstream of'?' as the 'within' implies 'involved in', but maybe I have mis-interpreted this.

The first paper I have checked PMID: 18421303 is describing differentiation of a neuron which obviously leaves the cell cycle. here transcription regulation is determining the progress eg, differentiation v apoptosis. The term pos reg of cell cycle arrest was applied because these are transcription factors regulating the proteins involved in the process rather than actually directly involved in the process. 

So I am tempted to look at the applying the term positive regulation of G1 to G0 transition involved in cell differentiation, this term however does not exist. I need to check that paper again, but am I interpreting the approach you are wanting people to take? If so will the regulation term be created or should I just say 'acts upstream of' GO:0070315 G1 to G0 transition involved in cell differentiation

Thanks

Ruth

**Comment by hattrill** [comment]
What I am doing with things that act to influence transcription of things that are regulating a discrete process is to use 'acts upstream of' +ve or -ve regulation of that process. Would be good to hear if others are doing the same or different.

**Comment by RLovering** [comment]
good point, What I am doing with things that act to influence transcription or translation of proteins that are **involved** in a discrete process is to use '**involved in**' +ve or -ve regulation of that process.

**Comment by bmeldal** [comment]
Complexes done.

**Comment by pgaudet** [comment]
@RLovering 

> Are you saying 'just change the current annotation to have the qualifier 'causally upstream of or within''?

My point was this could be done if you didn't have time to review the annotations. I think annotations can be moved or removed, but I realize there are a lot.

* Regarding PMID:18421303 : I see the mechanism for regulation of apoptosis: 
Pouf [negatively regulates] dbTF activity enabled by P73 [has input] BAX -> BAX [part of] apoptotic process
So in GO-CAM we would say 'Pouf acts upstream of, negative effect BAX activity

* However for the G1/G0 transition, I dont see via which gene Pouf acts, but in any case it should be a similar mechanism, so I think adding 'Pouf acts upstream of, positive effect G1 to G0 transition involved in cell differentiation is OK. 

What do you think? 

We can bring this up on a GO-CAM office hours call 

@thomaspd @vanaukenk

**Comment by RLovering** [comment]
Hi Pascale
I guess my first point was that it doesn't make sense to change the qualifier from 'involved in' to 'causally upstream of or within' as effectively these are still potentially 'involved in' and if we are not allowed to use 'involved in' then we shouldn't use  'causally upstream of or within'.

I am struggling with the db transcription factor decisions that are being made with GO-CAMs, I have added my concerns/queries to GO-CAM agenda. I assume there will be a meeting next week
Ruth

**Comment by tberardini** [comment]
TAIR done

**Comment by LiNiMGI** [comment]
MGI done

**Comment by vanaukenk** [comment]
WB is done

**Comment by sabrinatoro** [comment]
Now that ZFIN models are in Noctua-prod, I was able to review the ZFIN annotation. 
ZFIN annotation is done.

**Comment by pgarmiri** [comment]
Hi, the CAFA and UniProt-EBI (SWIE) annotations have been reviewed. The SWIS annotation have been tagged as such with a lilac label at the end of each line.
Thanks,
Penelope

**Comment by RLovering** [comment]
done

**Comment by suzialeksander** [comment]
corresponding ontology change has been completed.  CACAO, RGD, UniProt were the only groups that did not sign off on the spreadsheet
