### ISSUE TITLE
InterPro2GO - COX15/CtaA family (IPR003780)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3665]
Hi @sarach06 @EBI-Hsinyu 

Can I check the evidence for having "oxidoreductase activity, acting on the CH-CH group of donors (GO:0016627)" on this entry?
SGD have 3 independent annotations for the yeast COX15 gene, and they are all for "oxidoreductase activity, acting on NAD(P)H, heme protein as acceptor" (which is a different branch of oxidoreductase classification).  And those SGD annotations are used as the source for PAINT propagation of that latter GO term via [PTN000590786](http://www.pantree.org/node/annotationNode.jsp?id=PTN000590786).

All of which means COX15 proteins are currently getting somewhat conflicting annotations via InterPro vs PAINT.

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for highlighting this. I couldn't find evidence to support GO:0016627. I have updated the entry adding new references and changed the term for "GO:0016653 — oxidoreductase activity, acting on NAD(P)H, heme protein as acceptor" as you stated. This will be visible in the next InterPro release (85.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
