### ISSUE TITLE
InterPro2GO: Prolyl 4-hydroxylase alpha-subunit, N-terminal (IPR013547) & Prolyl 4-hydroxylase, alpha subunit (IPR006620)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3667]
Hi @sarach06 @EBI-Hsinyu 

The IPR013547 entry says "The members found in this entry are eukaryotic proteins, and include all three isoforms of the prolyl 4-hydroxylase alpha subunit. This enzyme (1.14.11.2) is important in the post-translational modification of collagen, as it catalyses the formation of 4-hydroxyproline."

Consistent with that, it's associated with this GO MF term:
procollagen-proline 4-dioxygenase activity (GO:0004656) (which has xref of 1.14.11.2)
(Note that this is a child of "oxidoreductase activity, acting on **paired donors**, with incorporation or reduction of molecular oxygen (GO:0016705)", with EC xref 1.14.-.-)

But IPR013547 also has this second GO MF term, which is from a different branch of oxidoreductases (EC:1.13.11.-)
oxidoreductase activity, acting on **single donors** with incorporation of molecular oxygen, incorporation of two atoms of oxygen (GO:0016702)

Is there evidence for this second activity, or is that just a mistake?

**Comment by sjm41** [comment]
Also need to check association of "oxidoreductase activity, acting on single donors with incorporation of molecular oxygen, incorporation of two atoms of oxygen (GO:0016702)" on the related entry "Prolyl 4-hydroxylase, alpha subunit IPR006620"

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. I have checked and GO:0016702 is not correct, I removed it from this entry. I also checked the terms in IPR006620 and GO:0016702 is not suitable. The changes will be visible in the next InterPro release (85.0). Let me know if it's Ok for you.
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara - quick work!  Just to confirm - you're removing GO:0016702 from both these InterPro entries, right?

**Comment by sarach06** [comment]
Thanks! Yes, sorry that I haven't mentioned that.
Cheers,
Sara

**Comment by sjm41** [comment]
Great, thanks again!
