### ISSUE TITLE
Review annotations to GO:0004447  iodide peroxidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3670]
Hello, 

Synonyms for GO:0004447  iodide peroxidase activity were confusing, see https://github.com/geneontology/go-ontology/issues/21027

Some annotations to this term probably need to be moved to the new term I just created, GO:0140616  iodotyrosine deiodinase activity

Please review your annotations: 

dictyBase - 1 - @pfey03 
GeneDB - 2  @Achchuthan 
MGI - 2 @hdrabkin 

Annotations are here: https://docs.google.com/spreadsheets/d/138NYNqDJzsdqXMhnsSWqal3yWtxy7DkJAAvcR-kU1Fs/edit#gid=0

Thanks, Pascale

**Comment by sjm41** [comment]
@pgarmiri / @sylvainpoux  - you may also wish to use the new GO term for the human protein:
https://www.uniprot.org/uniprot/Q6PHW0

**Comment by pfey03** [comment]
@pgaudet gave it to @rjdodson as he made the original annotation.

**Comment by hdrabkin** [comment]
GO:0140616 not in go-basic yet (currenet snapshot is /2021-03-06

**Comment by rjdodson** [comment]
dicty entry reviewed with no changes. dicty poxA is a heme peroxidase with at least two substrates: iodide and thiocyanate. (PMID:29242189). poxA currently has GO terms: GO:0004447 iodide peroxidase activity and GO:0036393 thiocyanate peroxidase activity, and I think these are correct as is.

**Comment by Achchuthan** [comment]
Hi @pgaudet,
Thanks for the suggestion to change these annotations to GO:0016688. I reviewed the annotations and left it unchanged. This is because the gene was already annotated to GO:0016688 in addition to annotation to GO:0004447 from the two listed publications. I have checked them and they appear correct from the enzyme assays.
Best wishes,
Achchuthan

**Comment by pgarmiri** [comment]
> 
> 
> @pgarmiri / @sylvainpoux - you may also wish to use the new GO term (GO:0140616
> iodotyrosine deiodinase activity - see #21027) for the human protein:
> https://www.uniprot.org/uniprot/Q6PHW0

Hi, I had a look at this and I am afraid I can't edit this annotation as it of REFG.

Thanks,

Penelope

**Comment by sjm41** [comment]
Hi @pgarmiri - I was wondering if you wanted to *add* it as a new GO annotation to human IYD (Q6PHW0) (PubMed:15289438, PubMed:25395621, PubMed:18434651).  The correct EC number is on that protein, but not the new GO term.

**Comment by pgarmiri** [comment]
oh @sjm41 , now I see what you meant!

 I have added the annotation to two of the papers that was missing and and disputed the two higher level annotations present in the third one as I don't have editing rights on them. I added the details in the comment, so I am sure they will updated shortly.

**Comment by pgarmiri** [comment]
All done from UniProt side.

**Comment by hdrabkin** [comment]
mgi done

**Comment by pgaudet** [comment]
Thanks everyone
