### ISSUE TITLE
Review annotations to GO:0033955 mitochondrial DNA inheritance

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3674]
Hello, 

The proposal has been made to obsolete GO:0033955 mitochondrial DNA inheritance, see https://github.com/geneontology/go-ontology/issues/18417

There are 12 annotations: 

10 GeneDB
1 MGI
1 TAIR

Please consider replacing by GO:0000002 mitochondrial genome maintenance or 
 GO:0000266 mitochondrial fission

Thanks, Pascale

**Comment by pgaudet** [comment]
Annotations are here:
https://docs.google.com/spreadsheets/d/1D7ji3-3fBh_Y2RsR9OYYEB15rYiege-guBRxoHAlTuI/edit#gid=0

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
@Achchuthan Just checking if you had a chance to fix your annotations. Note that the term is obsoleted, so I am closing this ticket. Annotations to obsolete terms appear in the GeneDB error report: http://snapshot.geneontology.org/reports/genedb_tbrucei-report.html#gorule-0000020

Thanks, Pascale
