### ISSUE TITLE
mappings to GO:0016709 and GO:0016712 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3675]
These 2 mappings are applied to coq6,

GO:0016709 | oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen | IEA with IPR010971 | GO_REF:0000002 

GO:0016712 | oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen | IEA with UR000376533 | GO_REF:0000104 

 which is a
GO:0008681 | 2-octaprenyl-6-methoxyphenol hydroxylase activity
2-octaprenyl-6-methoxyphenol + O2 + 4 H+ = 2-octaprenyl-6-methoxy-1,4-benzoquinol + H2O

@pgaudet I don't know who to tag for UR000376533

**Comment by EBI-Hsinyu** [comment]
Hi! 
Thank you for this. I have added this term to IPR000689. This will be visible in InterPro85.0.
Hsin-Yu
