### ISSUE TITLE
Latest PomBase GAF has extra field - breaks GO pipeline

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-annotation#3676]
Noticed this when the pipeline crashed on gaferencer processing pombase. From the [upstream PomBase GAF](https://github.com/geneontology/go-site/blob/b3fbfb813a8755351ec5bd041bd3378ad90564d8/metadata/datasets/pombase.yaml#L19) available at ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/gene_association.pombase.gz:
```
!URL: http://www.pombase.org/
!generated-by: PomBase
!date-generated: 2021-03-08
!gaf-version: 2.2
!contact: helpdesk@pombase.org
!
PomBase SPAC212.08c     SPAC212.08c     is_active_in    NOT|is_active_in        GO:0031362
      PMID:12845604   TAS             C       S. pombe specific GPI anchored protein family 1         protein taxon:4896      20131025        PomBase
```
Note the double qualifier fields, one having a `NOT|`. From the [GAF 2.2 spec](http://geneontology.org/docs/go-annotation-file-gaf-format-2.2/), there should only be one qualifier field. From looking at the rest of the file, this seems to only happen on the NOT annotations.

This needs to be fixed upstream at PomBase

Tagging @pgaudet @vanaukenk @kltm @ValWood

**Comment by ValWood** [comment]
These seem to be fixed in our local files now? @mah11 @kimrutherford

**Comment by mah11** [comment]
Will be fixed (at the location GO picks up) on Monday.

(Treating as not weekend-work urgent since it's taken 5 days to even be reported.)

**Comment by mah11** [comment]
Corrected GAF committed in PomBase pipeline. I'll let @dustine32 (or whoever else at GO) close this when it's picked up by GOC.

**Comment by pgaudet** [comment]
Fixed ? @dustine32

**Comment by dustine32** [comment]
Oh yes, it is fixed. Thanks for catching this unclosed ticket @pgaudet!
