### ISSUE TITLE
InterPro2GO for "Cytochrome P450" entries

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3677]
Hi @sarach06 @EBI-Hsinyu 

Looking at InterPro entries relevant to Drosophila cytochrome P450 proteins, their catalytic MF terms are a mixture of "oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen (GO:0016705)" and/or "monooxygenase activity (GO:0004497)".
These are implemented as orthogonal classifications in GO, and I believe both are accurate and both should be applied to all InterPro cytochrome P450 entries (as already done for IPR002403, at least).
Indeed, all the InterPro descriptions I looked at begin with "Cytochrome P450 enzymes are a superfamily of haem-containing mono-oxygenases", but "monooxygenase activity (GO:0004497)" is absent from most.

I've listed the 6 fly-relevant InterPro terms below together with their current catalytic GO term associations to illustrate my point, but you may want to review all 28 listed as 'overlapping terms' on "Cytochrome P450 superfamily (IPR036396)".

**Cytochrome P450 superfamily (IPR036396)**
- oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen (GO:0016705)

**Cytochrome P450 (IPR001128)**
- oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen (GO:0016705)

**Cytochrome P450, conserved site (IPR017972)**
- oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen (GO:0016705)

**Cytochrome P450, E-class, group I (IPR002401)**
- oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen (GO:0016705)

**Cytochrome P450, E-class, group II (IPR002402)**
- monooxygenase activity (GO:0004497)

**Cytochrome P450, E-class, group IV (IPR002403)**
- monooxygenase activity (GO:0004497)
- oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen (GO:0016705)

**Comment by sarach06** [comment]
Hi,
Thank you very much. Sorry for the late reply. I have checked and added the terms as necessary. The changes will be available in InterPro 85.0.

Best,
Sara
