### ISSUE TITLE
InterPro2GO for Endoplasmic reticulum oxidoreductin 1 (IPR007266)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3681]
Hi @sarach06, @EBI-Hsinyu 

Endoplasmic reticulum oxidoreductin 1 (IPR007266) has GO MF "oxidoreductase activity, acting on a sulfur group of donors, disulfide as acceptor (GO:0016671)"

But the yeast, fly and human orthologs have independent experimental GO annotations to "thiol oxidase activity" (GO:0016972), which is a child of "oxidoreductase activity, acting on a sulfur group of donors, oxygen as acceptor" (GO:0016670)

So maybe change the GO MF here to GO:0016972 or GO:0016670?

**Comment by sjm41** [comment]
Same for parent term, ERO1-like superfamily (IPR037192)

**Comment by EBI-Hsinyu** [comment]
Hi Steven, 

Thank you for this. I have added the term you suggested and updated the abstract. This will be visible in InterPro85.0.

Hsin-Yu

**Comment by sjm41** [comment]
Thanks @EBI-Hsinyu .  Just to confirm, did you update IPR007266 and IPR037192?

**Comment by EBI-Hsinyu** [comment]
Hi, 

IPR037192 is a superfamily entry. We try not to assign GO terms to superfamily entries if there are equivalent entries with the GO terms. As superfamily (H type) entries tend to overhit and more unstable with each update. 

Hsin-Yu

**Comment by sjm41** [comment]
Sorry, I meant will you also remove "oxidoreductase activity, acting on a sulfur group of donors, disulfide as acceptor (GO:0016671)" from IPR037192, for exactly the reasons you state :-)

**Comment by EBI-Hsinyu** [comment]
No worries. I have removed it. Thank you! :)
