### ISSUE TITLE
InterPro2GO - Glutaredoxin (IPR002109)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3684]
@sarach06  @EBI-Hsinyu

GO MF for this is currently "protein disulfide oxidoreductase activity (GO:0015035)"

I think that could be replaced with the first or maybe both of these two more specific terms:
glutathione oxidoreductase activity (GO:0097573)
protein-disulfide reductase (glutathione) activity (GO:0019153)

From Fig 3 and accompanying text of PMID:23397885, GRXs can operate via two distinct enzymatic reactions:
1. Reversible (de-)glutathionylation of proteins that depends only on the N-terminal active site cysteinyl residue, using the 'monothiol mechanism'. = GO:0097573
2. Reduction of protein disulfides using the so-called 'dithiol mechanism' similar to thioredoxins (but dependent on glutathione) = GO:0019153

There's a note on the GO:0097573 entry saying "See PMID:18992757: "Grxs [glutaredoxins] can also reduce mixed disulfides between proteins or low molecular weight thiols and GSH in reactions that require only their N-terminal active- site cysteine. It is important to note that the reduction of glutathionylated substrates through the monothiol mechanism seems to be the major activity of Grxs; all dithiol Grxs described so far catalyze these reactions, but not all dithiol Grxs catalyze the reduction of protein disulfides by the dithiol mechanism".

So maybe best just to have GO:0097573 on this entry? What do you think?

**Comment by EBI-Hsinyu** [comment]
Hi! 
Sorry for the late reply. We are very busy with a member database update recently. This entry (IPR002109) overhits non-Glutaredoxin proteins due to the PS51354 signature. I have removed this signature and replaced GO:0015035 with GO:0097573. This will be visible in InterPro 85.0.

Hsin-Yu

**Comment by sjm41** [comment]
Sounds good, thanks Hsin-Yu.

**Comment by sjm41** [comment]
Hi @sarach06 

Following on from #4092:
I think having GO:0097573 (glutathione oxidoreductase activity) associated with Glutaredoxin (IPR002109) must be wrong too.  Would you agree @kaxelsen?

(I see GO:0097573 (glutathione oxidoreductase activity) has no EC/RHEA xref, and is only associated with a single EXP GO annotation to Arabidopsis GRXC5.  Not sure if this reaction really exists as defined....)

**Comment by kaxelsen** [comment]
I agree. In the GRXC5_ARATH entry, the function comment reads: "Has a glutathione-disulfide oxidoreductase activity in the presence of NADPH and **glutathione reductase**." So this comments nicely demonstrates that glutathione is not the enzyme, glutathione reductase is.

**Comment by sarach06** [comment]
Hi,
Thank you very much for clarifying this. I have removed GO:0097573 from this entry. The changes will be visible in InterPro 90.0.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks both.

**Comment by sarach06** [comment]
Thank you very much! I have removed the term from this entry too.
Best,
Sara
