### ISSUE TITLE
Add functionality to support examining input and output annotation differences (GPAD 2.0 diffs?)

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/go-annotation#3687]
see: https://github.com/biolink/ontobio/issues/540

@kltm @pgaudet

**Comment by kltm** [comment]
Noting, as a first step, we want to add functionality to ontobio to support gpad2.0 diffs to get a handle on this.

@vanaukenk @ukemi

**Comment by kltm** [comment]
Ah, the minerva repo has a lot of this stuff: 
https://github.com/geneontology/minerva/issues?q=is%3Aissue+is%3Aopen+gpad
Should this actually be a separate sub-project? It looks like there might be a lot to do.

**Comment by kltm** [comment]
@ukemi @vanaukenk Would it be good to give a little more time to examining the current state of affairs with the output, and then you could iterate on the tools that are needed for automated probing of annotations w/@sierra-moxon?

**Comment by sierra-moxon** [comment]
After talking with Chris:
- [ ] calculate how many genes in each file, with how many unique terms per gene.
- [ ] report if one file has significantly genes or unique terms.
- [ ] use ontobio tools to see if missing terms are replaced with more general or more specific terms (for example, not needed in the first step).

Next steps will fall out as we progress.

**Comment by kltm** [comment]
After discussions with @cmungall and @sierra-moxon , @sierra-moxon will be prioritized to make a rough first pass on this.

**Comment by sierra-moxon** [comment]
PR is open for review here: https://github.com/biolink/ontobio/pull/594
good for GAF 2.0 and GPAD 1.2 comparisons (but have to compare two of the same type/version).

**Comment by ValWood** [comment]
Hi @sierra-moxon  is this ticket still required?

**Comment by sierra-moxon** [comment]
I think we can close; we have the differ in ontobio now.
