### ISSUE TITLE
Change InterPro annotation to GO:0004985 opioid receptor activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3689]
InterPro IPR039574 is mapped to GO:0004985 opioid receptor activity 
but should be mapped to the new GO term GO:0140625 opioid growth factor receptor activity, see https://github.com/geneontology/go-ontology/issues/21110

@sarach06 @EBI-Hsinyu can you please change the mapping to GO:0140625 (when the term is available, of course)

Thanks, Pascale

**Comment by sarach06** [comment]
Hi,
Thank you very much. Sure, I'll make the changes when it is possible. 
Best,
Sara
