### ISSUE TITLE
InterPro2GO Gamma interferon inducible lysosomal thiol reductase GILT (IPR004911)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3691]
Hi @sarach06, @EBI-Hsinyu 

I think it would be appropriate to add
oxidoreductase activity, acting on a sulfur group of donors, disulfide as acceptor (GO:0016671)
and/or
protein disulfide oxidoreductase activity (GO:0015035) 
to IPR004911.

What do you think?

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you. I have added GO:0016671 to this entry. This will be visible in InterPro 85.0.
Hsin-Yu

**Comment by sjm41** [comment]
Thanks!
