### ISSUE TITLE
InterPro2GO - Phosphatidylinositol N-acetylglucosaminyltransferase subunit C (IPR009450)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3694]
Hi @sarach06 @EBI-Hsinyu 

Phosphatidylinositol N-acetylglucosaminyltransferase subunit C (IPR009450) is not the catalytic subunit of the complex - can you remove "phosphatidylinositol N-acetylglucosaminyltransferase activity (GO:0017176)" please?

E.g. from PMID: 12655644: "It appears that the majormolecular function of PIG-C/GPI2 is scaffolding, anchoring thetransferase complex to the ER membrane and allowing inter-action with other protein components of the complex (Fig. 5)."

Thanks.

@gantonazzo

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you. I have removed the term. 

Hsin-Yu

**Comment by sjm41** [comment]
Thanks!
