### ISSUE TITLE
InterPro2GO - 2Fe-2S ferredoxin-type iron-sulfur binding domain (IPR001041)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3696]
Hi @sarach06 @EBI-Hsinyu 

IPR001041 currently has the GO MF "electron transfer activity (GO:0009055)" (GO def: _Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient_.)

But this domain is found in several proteins not characterised to have that activity, including Aldehyde oxidases and ferredoxins.

Please check, but I think the term should be removed.

**Comment by sjm41** [comment]
If you agree, then "electron transfer activity (GO:0009055)" should also be removed from the higher level "2Fe-2S ferredoxin-like superfamily (IPR036010)" entry.

**Comment by sjm41** [comment]
Should also check these related entries with "electron transfer activity (GO:0009055)":
Adrenodoxin (IPR001055)
Adrenodoxin, iron-sulphur binding site (IPR018298)

Basic question in all 4 cases is whether these 'electron carriers' fit the GO definition of 'electron transfer activity'

**Comment by sarach06** [comment]
Hi!
Thank you for this. I agree with you and removed the term from IPR036010 and IPR001041. In the case of Adrenodoxin, I wouldn't remove it as seems to me that the term fits well (PMID:1863359, PMID:12069587, PMID:22556163). Let me know if you agree, please.
Best,
Sara

**Comment by sjm41** [comment]
Hi Sara

Both Adrenodoxin (IPR001055) & Adrenodoxin, iron-sulphur binding site (IPR018298) are in fly Ferredoxins Fdx1 and Fdx2 (I haven't checked other species), which also have the other two domains mentioned above.

Ferredoxins (including Adrenodoxin as a specific example) certainly act as an electron carriers, transferring electrons within the "mitochondrial cytochrome P450 system". 
The question is whether this function fulfils the GO definition of 'electron transfer' - that is, is it acting within "an electron transport chain" involving "a series of electron carrriers" to "generate a transmembrane electrochemical gradient"?

From glancing through PMID: 22556163, it looks ferredoxins do work within a "chain", but I don't think they act to "generate a transmembrane electrochemical gradient", do they?

But I'm no expert on this stuff - maybe @pgaudet or @ValWood can help us?

**Comment by ValWood** [comment]
hmm, not sure. Maybe the definition needs relaxing  (we have used for the ferridoxins)
https://www.pombase.org/reference/PMID:11841224
IIRC the restriction was to prevent its use for any dehydrogenase (which it had been), but maybe we went a bit far!

**Comment by sjm41** [comment]
Alternative would be to keep the current "electron transfer activity (GO:0009055)" for the respiratory (OXPHOS) electron transport chain (which is how it seems to be defined right now) and make an additional term for the "mitochondrial cytochrome P450 system" (which I don't really understand right now - need to do more reading......). Or maybe there's a new parent-child relationship here??  Do we have any other MF/BP terms that specifically describe the "mitochondrial cytochrome P450 system" right now?

**Comment by ValWood** [comment]
> IIRC the restriction was to prevent its use for any dehydrogenase (which it had been), but maybe we went a bit far!

like here for example:
https://www.uniprot.org/uniprot/Q9UQ10
 I came across this yesterday while reviewing our unknowns.

**Comment by sjm41** [comment]
Hi @ValWood @pgaudet - Any further thoughts on this?

Seems the options are:
i) relax the current definition of 'electron transfer activity' (by removing "to generate a transmembrane electrochemical gradient"?) and therefore make that term applicable to components of the mitochondrial cytochrome P450 system (ferredoxins)
or
ii) keep the current def (which I think effectively restricts it to the OXPHOS system) and make a new term for the P450 electron transfer components

**Comment by ValWood** [comment]
If you remove  "to generate a transmembrane electrochemical gradient"  we would open. up again to using for any dehydrogenase  like https://www.uniprot.org/uniprot/Q9UQ10 (this clause was added for that reason). 

Could we add something to include  OXPHOS system
(are they related enough, I don't know much about this?).

**Comment by sjm41** [comment]
You mean "add something to include the **mitochondrial cytochrome P450** system"?

I don't know much about it either - https://pubmed.ncbi.nlm.nih.gov/22556163/ is useful.

**Comment by sjm41** [comment]
I was thinking the "_ ...in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors_" bit would stop the term being used for any dehydrogenase?

**Comment by ValWood** [comment]
Yes that sounds correct.

We have used this  term for the fission yeast ortholog of  Fdx1 ortholog etp1!

**Comment by sjm41** [comment]
Hi @ValWood 
Just to be clear, would you be happy if the def changed from:
_Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient._
to
_Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors._

If so, I will make a separate ticket to request that.

**Comment by ValWood** [comment]
yes that seems more accurate.

**Comment by sjm41** [comment]
Hi @sarach06 As we're proposing to tweak the GO def of 'electron transfer activity', that term will be fine to stay on those 2 Adrenodoxin InterPro entries mentioned above.  I'll close this ticket now.

**Comment by sjm41** [comment]
Re-opened based on new comments/thoughts in geneontology/go-ontology#21334

**Comment by sjm41** [comment]
Proposal now is:
i) 'electron transfer activity' def does not change, and we clarify that term is meant only as a grouping term for OXPHOS enzymes/reactions
ii) Thismeans that 'electron transfer activity' should not be used to annotate ferredoxins (or adrenodoxin as a specific example) as they don't "a transmembrane electrochemical gradient" as far as we know (please point to a ref that says otherwise!) -> these proteins (and InterPro entries) should use the top-level 'oxidoreductase activity' term instead.

**Comment by sjm41** [comment]
Hi @sarach06

We've now clarified the def of 'electron transfer activity' (#21334) and added a new BP term for "P450-containing electron transport chain" (GO:0140647) (https://github.com/geneontology/go-ontology/issues/21455).

So, I think Adrenodoxin (IPR001055) and Adrenodoxin, iron-sulphur binding site (IPR018298) should now have:
- 'electron transfer activity' removed
-  'P450-containing electron transport chain (GO:0140647)' added.

**Comment by sarach06** [comment]
Hi!
Many thanks. For now I'll leave 'electron transfer activity' as the new term is not available yet, but I'll record it to make the changes then.
Cheers,
Sara

**Comment by sarach06** [comment]
Hi,
Just to let you know that the new term has been added to the entries and 'electron transfer activity' has been removed. This will be visible in the next InterPro release (87.0)

**Comment by pgaudet** [comment]
Thanks!
