### ISSUE TITLE
PTN000145640, PTN002260779, PTN000145560, PTN000145643, PTN000145563 and PTN000145505 (all PTHR11361)

### ISSUE THREAD

**Issue by gantonazzo** [geneontology/go-annotation#3697]
I am opening this ticket to address some issues related to the MutS ATPases family.

PTN000145640 is propagating "contributes_to dinucleotide repeat insertion binding" (GO:0032181) to Drosophila spel1 (FBgn0015546).

The source of propagation is PMID:8942985, where they describe this function as performed by an heterodimer formed by MSH2, human ortholog of fly spel1, and MSH3, which doesn't have a known direct ortholog in Dmel.

This heterodimer therefore doesn't seem to exist in drosophila, and I'd suggest to stop the propagation of this annotation to spel1.

Furthermore, spel1 has been assigned a lot of different terms via PAINT.

From PTN000145640:
contributes_to dinucleotide repeat insertion binding
enables double-strand/single-strand DNA junction binding
contributes_to four-way junction DNA binding
contributes_to guanine/thymine mispair binding
contributes_to MutLalpha complex binding
contributes_to oxidized purine DNA binding
contributes_to single guanine insertion binding
contributes_to single thymine insertion binding
involved_in DNA recombination
involved_in maintenance of DNA repeat elements
involved_in negative regulation of DNA recombination
involved_in postreplication repair
part_of MutSalpha complex
part_of MutSbeta complex

From PTN002260779:
enables DNA-dependent ATPase activity
contributes_to mismatched DNA binding
part_of mismatch repair complex

From PTN000145643:
involved_in intrinsic apoptotic signaling pathway in response to DNA damage by p53 class mediator

From PTN000145505:
involved_in mismatch repair

Likewise, the same is happening for Msh6 (FBgn0036486), spel1 paralog, which has also been assigned a lot of different terms.

From PTN002260779:
enables DNA-dependent ATPase activity
contributes_to mismatched DNA binding
part_of mismatch repair complex

From PTN000145560:
enables four-way junction DNA binding
contributes_to MutLalpha complex binding
contributes_to oxidized purine DNA binding
contributes_to single thymine insertion binding
involved_in interstrand cross-link repair
involved_in maintenance of DNA repeat elements
involved_in meiotic mismatch repair
involved_in negative regulation of DNA recombination
involved_in pyrimidine dimer repair
part_of MutSalpha complex

From PTN000145563:
involved_in intrinsic apoptotic signaling pathway in response to DNA damage

From PTN000145505:
involved_in mismatch repair

So, in addition to blocking the propagation of "contributes_to dinucleotide repeat insertion binding" (GO:0032181) to spel1 via PTN000145640, I would suggest to review all the PTHR11361-linked propagations, and possibly just propagate more generic terms, since some of these specific annotations may originate from the study of complexes that may not be present in all organisms (as per the example of the MSH2-MSH3 heterodimer).

**Comment by ValWood** [comment]
aso

GO:0045910 | negative regulation of DNA recombination | IBA with PTN000145560 , P52701 , MGI:1343961
-- | -- | --

(not sure that is a direct role anyway)

**Comment by marcfeuermann** [comment]
The annotation was indeed weird, a nightmare to correct. I've deleted all and re-annotated the family, propagating only more generic terms.
