### ISSUE TITLE
InterPro2GO - Pyridoxal phosphate-dependent decarboxylase (IPR002129)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3700]
@sarach06 @EBI-Hsinyu 

IPR002129 has GO MF carboxy-lyase activity (GO:0016831), which is EC:4.1.1.-, but this signature is also found in aldehyde-lyases (EC:4.1.2.-), as indicated by the EC xrefs at the bottom of the IPR002129 page.

So can you change the MF to the parent term GO:0016830 carbon-carbon lyase activity (= EC: 4.1.-.-.)?

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have changed the term as you stated. It will be visible in the next InterPro release (85.0).

Best, 
Sara

**Comment by sjm41** [comment]
Great, thanks!
