### ISSUE TITLE
EC mapping to remove

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3704]
not enough info to assign this EC number to 
  | O94279

(not likely to be a protein phosphatase)

GO:0004725 | protein tyrosine phosphatase activity | IEA                        with                                            3.1.3.48

**Comment by ValWood** [comment]
and for 
  | Q9UUF3 (inositol phosphatase)

**Comment by ValWood** [comment]
@marcfeuermann  are yu the correct eperson for EC2GO mappings, let me know if not I will remove you

**Comment by marcfeuermann** [comment]
Hi Val, no I'm not involved in EC2GO mappings. I think you should contact our experts from the Rhea team:
Anne Morgat: Anne.Morgat@sib.swiss
Kristian Axelsen: Kristian.Axelsen@sib.swiss
Best regards,
Marc.

**Comment by ValWood** [comment]
but do they update the GO EC mappings? I'm not sure who does that?

Its a misplaced mapping on one UniProt entry

**Comment by ValWood** [comment]
@pgaudet

**Comment by marcfeuermann** [comment]
I was wondering if Anne was no involved in this. But I'm not sure. If I'm not directly involved in the EC2GO mapping itself, however, I can of course act upstream and update UniProtKB entries. For O94279 I can modify the EC number (make it incomplete). Would this be okay for you ?

**Comment by ValWood** [comment]
Oh yes please. Then we can close this.

@pgaudet  I'd sill like to know the "offical" person for EC2GO mappings. Did @hdrabkin  used to do it?

**Comment by marcfeuermann** [comment]
Okay, done ;-)

**Comment by ValWood** [comment]
Yay!

**Comment by marcfeuermann** [comment]
Of course also done for Q9UUF3...

**Comment by ValWood** [comment]
Thank you!
