### ISSUE TITLE
 PTN001128880 F-bar family

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3707]
we shouldn't transfer annotation between F-bar family members.  imp2 and cdc15 have different roles in cytokinesis. I think it's likely that cdc15 is assembly and imp2 is dissassembly (i.e partitioning between paralogs)

  | GO:1903476 | protein localization to cell division site involved in mitotic actomyosin contractile ring assembly | IBA                        with                                            PTN001128880          ,                                     cdc15

**Comment by ValWood** [comment]
Probably only affects pombe branch and I have filtered

**Comment by marcfeuermann** [comment]
cdc15 and imp2 result from a duplication in pombe. The term seems not to exist anymore (obsoleted ?).
