### ISSUE TITLE
 PBLD 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3710]
these annotations seem to represent very general phenotypes in cancer cell lines(I came across these as I was reviewing my unknowns list).
@pgaudet  do you agree? If so I will raise a dispute in. p2GO

UniProtKB:P30039 | PBLD | involved_in | GO:0010719    negative regulation of epithelial to mesenchymal transition | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt |  
UniProtKB:P30039 | PBLD | involved_in | GO:0010633    negative regulation of epithelial cell migration | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt |  
UniProtKB:P30039 | PBLD | involved_in | GO:0030512    negative regulation of transforming growth factor beta receptor signaling pathway | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt |  
UniProtKB:P30039 | PBLD | involved_in | GO:0030277    maintenance of gastrointestinal epithelium | ECO:0000315   IMP | PMID:17929853 |   | 9606 Homo sapiens | UniProt |  
UniProtKB:P30039 | PBLD | involved_in | GO:0060394    negative regulation of pathway-restricted SMAD protein phosphorylation | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt | has_input (UniProtKB:P84022)
UniProtKB:P30039 | PBLD | involved_in | GO:0060392    negative regulation of SMAD protein signal transduction | ECO:0000316   IGI | PMID:23687415 | UniProtKB:Q9Y3F4 | 9606 Homo sapiens | UniProt | has_input (UniProtKB:P84022)
UniProtKB:P30039 | PBLD | involved_in | GO:0050680    negative regulation of epithelial cell proliferation | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt

**Comment by pgaudet** [comment]
Hi @ValWood 
This was done by a curator not at EBI anymore. 

I removed the regulation of migration and epithelial to mesenchymal transition, as well as phosphorylation, but I think the signaling annotations are OK ? 

Can you check and close disputes?

**Comment by ValWood** [comment]
> but I think the signaling annotations are OK ?
OK, but I don' think they should be transferred, could be very indirect if it is not clear where in the pathway? This is an ancestral conserved protein (from bacteria to metazoa). In plants, the paralog   is described as an "amino acid racemase".

It's probably OK to keep the annotation, but I don't think it should be PAINTED at present. IO will assign to Marc now to fix the PAINT.

> Can you check and close disputes?
I didn't open he disputes for this one yet. Do you mean others? (I usually close them when I get pinged by Protein2GO that they have been fixed?)

**Comment by ValWood** [comment]
Will be fixed  automatically as annotations have  been removed?

**Comment by marcfeuermann** [comment]
This looks clean now.
