### ISSUE TITLE
PMID: 23687415   PBLD (reviewing unknowns)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3713]
Thus publication does not seem to be appropriate  for GO  process annotation, these observations are just migration/proliferation assays/ phenotypes in cancer cell lines from knockdown/overexpression.

UniProtKB:P30039 | PBLD | involved_in | GO:0010719    negative regulation of epithelial to mesenchymal transition | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt |  
UniProtKB:P30039 | PBLD | involved_in | GO:0010633    negative regulation of epithelial cell migration | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt |  
UniProtKB:P30039 | PBLD | involved_in | GO:0030512    negative regulation of transforming growth factor beta receptor signaling pathway | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt |  
UniProtKB:P30039 | PBLD | involved_in | GO:0060394    negative regulation of pathway-restricted SMAD protein phosphorylation | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt | has_input (UniProtKB:P84022)
UniProtKB:P30039 | PBLD | involved_in | GO:0060392    negative regulation of SMAD protein signal transduction | ECO:0000316   IGI | PMID:23687415 | UniProtKB:Q9Y3F4 | 9606 Homo sapiens | UniProt | has_input (UniProtKB:P84022)
UniProtKB:P30039 | PBLD | involved_in | GO:0050680    negative regulation of epithelial cell proliferation | ECO:0000315   IMP | PMID:23687415 |   | 9606 Homo sapiens | UniProt

I'll raise a Protein2GO dispute for the annotation

( I am checking our priority unknowns list which includes the yeast ortholog of this gene)

**Comment by ValWood** [comment]
Assigning @pgarmiri  expired EBI account

**Comment by pgaudet** [comment]
Duplicate of #3710 ?

**Comment by ValWood** [comment]
yes, closing...

**Comment by ValWood** [comment]
Ah OK and the disputes are now closed...
