### ISSUE TITLE
Q9UQ10 NAD(P)+ transhydrogenase activity unsupported

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3714]
https://www.uniprot.org/uniprot/Q9UQ10

remove TAS
NAD(P)+ transhydrogenase activity Source: ProtInc
from

trans-1,2-dihydrobenzene-1,2-diol dehydrogenase activity Source: UniProtKB-EC
is a better annotation

**Comment by pgaudet** [comment]
Done, thanks
