### ISSUE TITLE
PTN001258896 not a protein phosphatase - PTHR31126

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3715]
PTN001258896

GO:0004725 | protein tyrosine phosphatase activity | IBA with PTN001258896 , Q9HXC7 | Gaudet P et al. (2011)

is an inostiol phosphatase, does not appear to a protein phosphatase physiologically?

**Comment by ValWood** [comment]
from a single 2009 paper in vitro assay
https://www.uniprot.org/citations/19543378

https://www.yeastgenome.org/locus/S000004977/go
info from S. cerevisiae points to inositol phosphorylation, many papers. so I would not transfer this single annotation from pseudomonas although it may be correct in this species, I guess.

**Comment by pgaudet** [comment]
Q9HXC7 is annotated as a protein tyrosine phosphatase activity though..

**Comment by ValWood** [comment]
Se above

"so I would not transfer this single annotation from pseudomonas although it may be correct in this species, I guess"

There have been lots of experiements in yeast, and a single exp in pseudomonas.... I think if it dephosphorylated protein in yeast we would know by  now...

**Comment by pgaudet** [comment]
OK got it ! thanks

**Comment by pgaudet** [comment]
Fixed.
