### ISSUE TITLE
incorrect IDA annotation of 'plasmalogen synthase activity' to the Arabidopsis LPEAT1 and LPEAT2 genes

### ISSUE THREAD

**Issue by peifenz** [geneontology/go-annotation#3717]
The GO term 'plasmalogen synthase activity' describes the attachment of an acyl-CoA to 1-O-alk-1-enyl-glycero-3-phosphocholine. 

There is no experiment evidence suggests that the Arabidopsis genes LPEAT1 and LPEAT2 have such enzyme activity. The cited paper (PMID:19445718) does not support it. The substrates tested in the paper (in Methods section) included  1-palmitoyl-2-hydroxy-sn-glycero-3-phosphocholine, 1-oleoyl-2-hydroxy-sn-glycero-3-phosphocholine, and other lipids. None of them are 1-O-alk-1-enyl-glycero-3-phosphocholines.

Here is a screen shot of the incorrect GO annotation to LPEAT1:
<img width="1612" alt="Screen Shot 2021-03-30 at 9 34 16 PM" src="https://user-images.githubusercontent.com/36932254/113092196-5f07ac80-91a2-11eb-8895-1e2b05966496.png">

**Comment by pgaudet** [comment]
Hi @alanbridge 
Should we close this ticket? Or will you come back to close it when it's done locally?

**Comment by alanbridge** [comment]
Hi Pascale, Emmanuel Boutet and Damien Lieberherr are going to take care of the fixes - Emmanuel will close the ticket when done.

**Comment by dlieberherr** [comment]
Hi Peifen, Alan and Pascale,
We have updated GO annotation for LEAPT1 and LEAPT2 and added the correct reactions in the corresponding UniProt entries.
Best, Damien

**Comment by dlieberherr** [comment]
The UniProtKB/Swiss-Prot updates of LEAPT1 and LEAPT2 should be freezed on May 12 (Freeze 2021_04) and publicly released on July 28 (Release 2021_04). For GOA, I do not have the release calendar.
Damien

**Comment by pgaudet** [comment]
Thanks !!
