### ISSUE TITLE
endoplasmic reticulum membrane (Ermes Mdm12 and Mdm34)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3721]
GO:0005789 | endoplasmic reticulum membrane | IEA with UR000106136
GO:0031307 | integral component of mitochondrial outer membrane | IEA with UR000106401

please remove.

The ERMES complex comprises four core components (Mmm1,
Mdm10, Mdm12, and Mdm34). The maintenance of mitochondrial
morphology protein 1 (Mmm1) and the mitochondrial distribution
and morphology protein 10 (Mdm10) are
transmembrane proteins residing on the ER membrane and the
mitochondrial outer membrane, respectively. Mdm12 and Mdm34
are cytosolic, functioning to bridge Mmm1 and Mdm105–10.

**Comment by ValWood** [comment]
Although 
"Indeed, Mmm1, Mdm12, and Mdm34
are SMP (synaptotagmin-like mitochondrial-lipid binding protein)"
I will look into this further.

**Comment by pgaudet** [comment]
@pedruzzi 
I think you manage the UniRules?

**Comment by pedruzzi** [comment]
Yes these are all HAMAP rules. I'll have a look at it.

**Comment by ValWood** [comment]
This was fine, since ERMES is both:
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0032865
