### ISSUE TITLE
PTN000179713, PTN000179968 , PTN000180161, PTN000180096, PTN000180038, PTN000297471

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3724]
It isn't clear that the MCM complex

mcm2 |   | IBA with S000000119 , PTN000179907 | Gaudet P et al. (2011)
-- | -- | -- | --
mcm3 |   | IBA with S000000758 , PTN000179713 | Gaudet P et al. (2011)
mcm4 |   | IBA with PTN000179968 , S000006223 | Gaudet P et al. (2011)
mcm5 |   | IBA with S000004264 , PTN000180161 | Gaudet P et al. (2011)
mcm6 |   | IBA with S000003169 , PTN000180096 | Gaudet P et al. (2011)
mcm7 |   | IBA with PTN000180038 , S000000406 | Gaudet P et al. (2011)
orc3 |   | IBA with PTN000297471 , S000003927 | Gaudet P et al. (2011)

is involved in pre-replicative complex assembly.
(note that mcm is itself  part_of the pre-replicative complex), and it seems to self assemble in vitro?

Seems to be from:
https://www.yeastgenome.org/reference/S000117043
I am filtering fro PomBase

CC @mah11

**Comment by marcfeuermann** [comment]
Some more complex assembly annotations fixed.
