### ISSUE TITLE
InterPro2GO: SecE/SEC61gamma subunit (IPR005807 & IPR008158)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3725]
SecE subunit of protein translocation complex, bacterial-like (IPR005807)
Protein translocase SEC61 complex, gamma subunit (IPR008158)

These two entries both have "P-P-bond-hydrolysis-driven protein transmembrane transporter activity (GO:0015450)", that is, they drive protein translocation using energy derived from diphosphate (aka pyrophosphate) hydrolysis.

But the entry description and the literature I've briefly read say that the energy is derived from ATP hydrolysis, suggesting "ATPase-coupled transmembrane transporter activity GO:0042626" is the accurate term to use.

That said, the InterPro entries also say that bacterial SecA (not SecE) and eukaryotic BiP (not Sec61gamma) are the ATPases, suggesting the MF should just be removed altogether?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I had a look and I agree that they are not ATPases. I added 'GO:0008320 — protein transmembrane transporter activity' to these entries. The changes will be visible in the next InterPro release (86.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
