### ISSUE TITLE
PTN005238491 (PTHR45715) & source annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3727]
PTN005238491 adds GO:0008553 "proton-exporting ATPase activity, phosphorylative mechanism" (recently renamed to "P-type proton-exporting transporter activity") to members of the ATPASE H+-TRANSPORTING V1 SUBUNIT E1A-RELATED (PTHR45715) family.

This is based on these source annotations:

(MOUSE|MGI=MGI=894326|UniProtKB=P50518) "GO:0008553 P-type proton-exporting transporter activity" IGI with SGD:S000005859 (PMID:11872743)
(MOUSE|MGI=MGI=1922165|UniProtKB=Q9D593) IGI with SGD:S000005859 (PMID:11872743)

(DANRE|ZFIN=ZDB-GENE-020419-11|UniProtKB=Q6NWK4) "GO:0008900 P-type potassium:proton transporter activity" IDA (PMID:24671205)

This is odd because the V-ATPase is characterised to act via a rotational and not phosphorylative mechanism.

@hdrabkin the two mouse annotations are based on the ability of the two genes/proteins "to Complement the Yeast Δvma4 Mutant".  Looks like the yeast gene doesn't have any EXP annotations, but the TAS and IEA annotations say it uses a phosphorylative mechanism (https://www.alliancegenome.org/gene/SGD:S000005859#function---go-annotations), so I think these should be changed to "proton-transporting ATPase activity, rotational mechanism GO:0046961".

@sabrinatoro - I don't easily see the evidence for "P-type potassium:proton transporter activity" from PMID:24671205 - please check, but maybe change to "proton transmembrane transporter activity | GO:0015078"?

**Comment by hdrabkin** [comment]
fixed for mgi

**Comment by sjm41** [comment]
Hi @sabrinatoro Can you take a look at the ZFIN annotation mentioned above? Thanks.

**Comment by sabrinatoro** [comment]
@sjm41 
Our annotations are "frozen" for now, until we have completed the migration to Noctua. 
So I need to wait for Noctua migration before I can take a look at these, but I will definitely take care of these as soon as migration is completed (which hopefully will happen very soon).

**Comment by sjm41** [comment]
Ah yes, of course!  You said so at the GO mtg.....
@marcfeuermann @pgaudet  - in the meantime, can you remove GO:0008553 directly from the PAINT node?

**Comment by marcfeuermann** [comment]
Changes have been done at the PAINT level. This ticket can be closed once the ZFIN annotation will be corrected.

**Comment by sabrinatoro** [comment]
@sjm41 @marcfeuermann @pgaudet 
All the ZFIN annotations are now in Noctua, and I was able to update the ZFIN annotation.
Thank you for your patience! 
This issue can now be closed.
