### ISSUE TITLE
PTN000833803 not mitochondrial fission

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3728]
I don't see any direct role for this in fission yeast
GO:0000266 | mitochondrial fission | IBA with S000002557 , PTN000833803

In fission yeast it functions as an adaptor for dynein in 
dynein-driven meiotic oscillatory nuclear movement

In fact in fission yeast it seems to be meiosis-specific which fits it's known role and rules out a role in  mitochondrial fission which occurs during vegetative growth.

**Comment by marcfeuermann** [comment]
Fixed.
