### ISSUE TITLE
direct annotations to cell death terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3729]
direct annotations to 
http://amigo.geneontology.org/amigo/term/GO:0008219
http://amigo.geneontology.org/amigo/term/GO:0060548

should be reviewed at some point,. The mainly appear to be pro-survival......there are not so many...

SRSF6 | Serine/arginine-rich splicing factor 6
DUS2 | tRNA-dihydrouridine(20) synthase [NAD(P)+]-like
escrt-iii_human | ESCRT-III complex
RAD18 | E3 ubiquitin-protein ligase RAD18

Maybe the  terms need better comments about not annotating prosurvival, or blocking altogether unless the mechanism can be specified (apoptosis, autophagy)

_Originally posted by @ValWood in https://github.com/geneontology/go-annotation/issues/3712#issuecomment-818515341_

**Comment by pgaudet** [comment]
Contributor  |  (Assigned by)
--|--
AgBase | 5
ARUK-UCL | 18
BHF-UCL | 12
CACAO | 3
CAFA | 2
ComplexPortal | 1
dictyBase | 3
EcoCyc | 5
FlyBase | 88
GeneDB | 1
MGI | 24
ParkinsonsUK-UCL | 12
PseudoCAP | 1
RGD | 92
TAIR | 36
UniProt | 102
WB | 1
ZFIN | 2

**Comment by vanaukenk** [comment]
WB is done.
