### ISSUE TITLE
PTN000088828 mitochondrial translation - PTHR10826

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3730]
GO:0070131 | positive regulation of mitochondrial translation | IBA with S000001332 , MGI:1194505 , PTN000088828

mam33 is involved in mitochondrial ribosome assemlby, so not 'regulation of translation'
but is 'causally upstream'

**Comment by pgaudet** [comment]
PAINT does not do causally upstream

**Comment by ValWood** [comment]
This is a 2019 yeast paper (uncurated)
http://europepmc.org/article/MED/31053642
it describes a specific role as a chaperone for ribosome assembly, which would impact translation. It isn't a translational regulator, but affects translation.

Based on the more recent paper maybe SGD should remove the old phenotypes to be phenotype annotations  and reannotate to ribosome assembly?

"Together with the
cosedimentation experiments, these protein interactions suggest that Mam33 associates with individual mtLSU proteins,
but not the fully assembled large subunit."

The authors speculate why only cox1 translation is affected in the discussion and don't rule out a role as a translational regulator too, but at present there are numerous explanations.


@suzialeksander

**Comment by pgaudet** [comment]
Removed annotation in PAINT.

**Comment by suzialeksander** [comment]
Removed SGD.
