### ISSUE TITLE
PTN001821752 and PTN000429500 (both PTHR18866)

### ISSUE THREAD

**Issue by gantonazzo** [geneontology/go-annotation#3733]
Mccc1 (FBgn0039877) has been assigned two different carboxylase activity terms by PAINT: "enables CoA carboxylase activity", propagated via PTN001821752, and "enables methylcrotonoyl-CoA carboxylase activity", propagated via PTN000429500.

MCCC1 in human is known to form a heterododecamer (6α6β - a complex called 3-methylcrotonyl CoA carboxylase) with MCCC2, where MCCC2 has the catalytic domain (for carboxyltransferase activity) and MCCC1 has a covalently bound biotin that is necessary for the 3-methylcrotonyl CoA carboxylase complex to work (since it’s a biotin-requiring enzyme).

In flies Mccc2 (FBgn0042083) has an Acetyl-CoA carboxylase domain, while Mccc1 (FBgn0039877) has a Biotin carboxylase-like, N-terminal domain, so they seem to have the same "task division” as in human.

This 3-methylcrotonyl CoA carboxylase is part of a special class of biotin-dependent enzymes, which you can read more about in this review: https://www.sciencedirect.com/science/article/abs/pii/S0003986113003263.
We are planning to add this enzyme example to the "contributes_to" GO guidelines, since it’s a special situation.

Since biotin is covalently attached to Mccc1, and it is essential for the enzyme function, we think Mccc1 should have a “contributes_to” annotation (together with Mccc2). Mccc2 has already been assigned a "contributes_to methylcrotonoyl-CoA carboxylase activity" annotation by PTN000523406, so I propose here that Mccc1 receive the same "contributes_to" annotation (which could be propagated from human MCCC1, based on PMID:17360195), instead of the current functions assigned by PAINT.

@hattrill 
@sjm41

**Comment by marcfeuermann** [comment]
Thanks for this nice explanation. I've switched to the CONTRIBUTES_TO annotation.
