### ISSUE TITLE
Review annotations to GO:0000188 inactivation of MAPK activity and related

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3736]
Dear all, 

The proposal has been made to obsolete

GO:0000188 | inactivation of MAPK activity'
GO:0051389 | inactivation of MAPKK activity'
GO:0051390 | inactivation of MAPKKK activity'

since those represent molecular functions.

There are about 300 EXP annotations:

Contributor   (Assigned by)
--
ARUK-UCL | 1 done
CGD | 2
~FlyBase~ | ~1~
GOC | 1
HGNC-UCL | 1 done
MGI | 8
SGD | 34
UniProt | 8
WB | 6
ZFIN | 1

Annotations are here: https://docs.google.com/spreadsheets/d/1RIWnSg1tVUocr9TVLdtUasqUkRvHwjNva3DKSIZOG1E/edit#gid=0

Since this is a lot to review we will leave 1 month until the obsoletion. Please let me know if you need more time.

Thanks, Pascale

**Comment by pgaudet** [comment]
Suggestions for replacement: 
* GO:0043409 negative regulation of MAPK cascade
* GO:0043408 regulation of MAPK cascade 
* GO:0033550 MAP kinase tyrosine phosphatase activity

**Comment by pgaudet** [comment]
Sorry @hattrill The FlyBase annotation was to GO:0033550 MAP kinase tyrosine phosphatase activity. You're off the hook! have a great weekend :)

**Comment by hattrill** [comment]
That's great news @pgaudet ! Case closed and not a finger lifted on my part! You have a good weekend too :-)

**Comment by hdrabkin** [comment]
MGIdone

**Comment by pgaudet** [comment]
Hi everyone, This is a reminder that these terms are scheduled to be obsoleted on Monday. Please let me know if you need more time to review. 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi, 
The UniProt EBI annotations have been checked. There are 4 annotation from SIB that have been marked with a lilac tag at the end of the row.( for the attention of @sylvainpoux )
Thanks,
Penelope

**Comment by vanaukenk** [comment]
WB is done.

**Comment by pgaudet** [comment]
PAINT annotations

 - [ ]  dual specificity protein phosphatase PTHR10159
 - [ ]  protein-tyrosine-phosphatase ibr5 PTHR47244
 - [ ]  sprouty-related, evh1 domain-containing protein family member PTHR11202
 - [ ]  agap008228-pa PTHR45682

**Comment by pgaudet** [comment]
The terms have been obsoleted; and remaining annotation will appear in the error reports: http://snapshot.geneontology.org/reports/gorule-report.html

**Comment by sabrinatoro** [comment]
ZFIN done after annotations were migrated into Noctua
