### ISSUE TITLE
InterPro2GO - Oxoglutarate/iron-dependent dioxygenase (IPR005123)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3737]
Hi

This has the MF 'oxidoreductase activity (GO:0016491)' but as the EC xrefs at the bottom of the InterPro entry indicate, this domain is also found in transferases, hydrolases and lyases.
Please check, but I think it should be removed.

**Comment by EBI-Hsinyu** [comment]
HI, 
Thank you for this. I have removed this term. This will be visible in InterPro86.0.
Hsin-Yu

**Comment by sjm41** [comment]
Thanks!
