### ISSUE TITLE
PTN000846433 not a ribosomal  protein - PTHR10792

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3738]
although

rlp24
ribosomal L24-like protein involved in ribosome biogenesis Rlp24 (predicted)
looks like a ribosomal protein, it is only involved in ribosome assembly. It is released from the ribosomes and isn't part of the final ribosomal.

see  https://www.yeastgenome.org/locus/S000003999

GO:0003735 | structural constituent of ribosome | IBA with PTN000846433 , 621191

GO:0022625 | cytosolic large ribosomal subunit | IBA with locus:2054982 , 621191 , locus:2040555 , S000002999 , S000003380 , locus:2085246 , PTN000846433 , P83731

Rlp24 is very similar to the ribosomal protein rpl24, I don't  know if you will be able to distinguish these easily in PANTHER tress but they should from a separate orthologous group (yeast to human)

**Comment by pgaudet** [comment]
I suppose you are talking about SPAC22E12.13c?

**Comment by pgaudet** [comment]
OK got it. Fixed the family, annotated the 2 separate nodes. 

However I could only pick  GO:0042273  ribosomal large subunit biogenesis  and not GO:0000027 ribosomal large subunit assembly @suzialeksander Can you maybe make the yeast annotation to the more specific child term for S000003999? 

Thanks, Pascale
