### ISSUE TITLE
PTN000375324 do not transfer for yeast  - PTHR12829

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3739]
GO:0032775 | DNA methylation on adenine | IBA with MGI:1924031 , PTN000375324 , Q8N3J2 , WBGene00015939

Pombe does not have DNA methylation (Nor S. cerevisiae, as far as I know @srengel ?)

In pombe theis is an mRNA methylase

I am filtering the term, will also request a taxon restriction

**Comment by srengel** [comment]
true, prevailing thought is that DNA methylation doesn't happen in budding yeasts.  there was some murmuring about 10 years ago about it happening on cytosine in yeasts, but other studies came out saying that no it doesn't really happen, not even on cytosine.

**Comment by ValWood** [comment]
Yes- people tried to find it a lot, but without success!

**Comment by pgaudet** [comment]
Hi, 

Moved the annotations to narrower clades.
