### ISSUE TITLE
IPR001655 - NOT superoxide-generating NAD(P)H oxidase activity (GO:0016175)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3741]
Hello, 

I think IPR001655 should be mapped to     GO:0016176  superoxide-generating NADPH oxidase activator activity (and not 
GO:0016175 superoxide-generating NAD(P)H oxidase activity).

Thanks, Pascale

**Comment by pgaudet** [comment]
Same applies to MGI:97283 and RGD:61307. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
If this is an interpo 2 go mapping, MGI has nothing to do with the mapping file.  If the mapping changes the annotaton will change.  There is nothing for me to do.

**Comment by sarach06** [comment]
Hi Pascale,
Many thanks. I have changed the term for GO:0016176, which will be visible in the next InterPro release (86.0).
Best,
Sara

**Comment by pgaudet** [comment]
@hdrabkin 

There are 2 EXP in MGI: 
- one IMP from  MGI:MGI:1889180 | PMID:10987289
- one IDA from  MGI:MGI:65356 | PMID:8119734

Not sure why we see different things?

**Comment by hdrabkin** [comment]
Ah; I didn't check because the ticket title was indicating IPR001655, so I thought any annotations we had were coming in via ip2go. I'll look at these now. 
Ok Done.

**Comment by gthayman** [comment]
The one annotation (IEA) is imported from GOA, originally from Interpro.

**Comment by pgaudet** [comment]
@gthayman There is also an IDA annotation based on PMID:16040349/ RGD:1600567; can you please have a look at that?

**Comment by gthayman** [comment]
Changed.

**Comment by pgaudet** [comment]
Thanks @gthayman
