### ISSUE TITLE
PTN000959239  family problem

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3742]
There is a problem with this Panther family. The  metazoan members the 'nuclear is transferred from are TUDOR domain protein kinases. The yeast proteins are much shorter and have a single tm domain nd nuclease domain.
There is no space for TUDOR or protein kinase.

see
pombe http://pfam.xfam.org/protein/O60168
human STK31 http://pfam.xfam.org/protein/Q9BXU1

GO:0005634 | nucleus | IBA with MGI:1929266 , locus:2159218 , WBGene00006626 , locus:2183359 , Q8II01 , PTN000959239 , FBgn0035121

**Comment by ValWood** [comment]
I think this might be a family problem so probably needs to be reported back to Panther

**Comment by marcfeuermann** [comment]
The family contains 2 big subfamilies. Propagation was indeed weird and has been restricted.
