### ISSUE TITLE
GO Annotation File (GAF) 2.2, error in the page

### ISSUE THREAD

**Issue by ANiknejad** [geneontology/go-annotation#3743]
Hello GO team,

http://geneontology.org/docs/go-annotation-file-gaf-format-2.2/#annotation-extension-column-16

'mitochondrion ; GO:0005439'

should be

mitochondrion ; **GO:0005739**

Best regards,

Anne Niknejad

**Comment by pgaudet** [comment]
Fixed, thanks for reporting this!
