### ISSUE TITLE
PTN004333583- Mice don't catabolize allantoin

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3744]
Although the Allc gene (MGI:2136971) is present in mice, it is likely that under physiological conditions it does not break down allantoate. In mice allantoin is secreted in the urine and there is no evidence that it is catabolized.
See PMID:14745534 and PMID:11852104.
ping @deustp01

**Comment by ukemi** [comment]
You should probably also remove the MF annotation for this gene to allantoicase activity (GO:0004037). As above, although the enzyme can be forced to work, it is unlikely that his has physiological significance.

**Comment by deustp01** [comment]
Here's a tabulation of validated and candidate gene products for pathways from urate / uric acid to ammonia. I have not checked the assertions about possible enzyme activity or lack of it against existing GO annotations.
[urate_catab_notes.docx](https://github.com/geneontology/go-annotation/files/6359494/urate_catab_notes.docx)

**Comment by ukemi** [comment]
Perfect timing! I was just trying to make a 'NOT' model for mice for allantoin catabolism. Not as easy as it appears on the surface. Lots of room for discussion.

**Comment by ukemi** [comment]
ureidoglycolate lyase activity has been assayed in marine fish----PMID: 3741398. But genes are hard to come by.
