### ISSUE TITLE
PTN000477446 / PTN000272437

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3750]
fission yeast bos1/cerevisiae bos1 are ER to Golgi SNARE

These annotations are transferred to pombe Bos1 from non-orthologous SNARES

- | GO:0006896 | Golgi to vacuole transport | IBA with S000004810 , locus:2175733 , PTN000477446 | Gaudet P et al. (2011) | 22
- | GO:0006891 | intra-Golgi vesicle-mediated transport | IBA with O14653 , S000004810 , PTN000477446 | Gaudet P et al. (2011) | 33
- | GO:0006623 | protein targeting to vacuole | IBA with PTN000477446 , locus:2175733 , locus:2200595 | Gaudet P et al. (2011) | 28
- | GO:0042147 | retrograde transport, endosome to Golgi | IBA with PTN000477446 , Q96AJ9 | Gaudet P et al. (2011) | 37
- | GO:0048280 | vesicle fusion with Golgi apparatus | IBA with S000004068 , PTN000477446 , 621490

**Comment by ValWood** [comment]
human ortholog is GOSR2

**Comment by ValWood** [comment]
This looks incorrect for Vsl1 (ortholog is STX8 not   STX6 or 10)
Vsl1 is  Golgi to vacuole

GO:0042147 | retrograde transport, endosome to Golgi | IBA with PTN000272437 , O43752 , O60499

**Comment by marcfeuermann** [comment]
Both families have been fixed.
