### ISSUE TITLE
Q15526 PinC annotation for cytochrome oxidase assembly factor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3753]
Hi @pgaudet 

can you delete
cytochrome-c oxidase activity Source: ProtInc
aerobic respiration Source: ProtInc
respiratory chain complex IV assembly (I think this one is wrong, but I'm not totally sure)

oxidative phosphorylation Source: BHF-UCL looks indirect (phenotype)? (I  would annotate cytochrome oxidase to this term, not the assembly factors)
@RLovering 

cheers

Vall

**Comment by pgaudet** [comment]
Done

**Comment by RLovering** [comment]
deleted

**Comment by pgaudet** [comment]
Thanks!
