### ISSUE TITLE
InterPro2GO for [GO:0051997] 2-oxo-4-hydroxy-4-carboxy-5-ureidoimidazoline decarboxylase activity (IPR017580)

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3757]
The mapping of this domain to 'allantoin biosynthetic process' (GO:0019428) should be re-examined. In mice the output of urate catabolism is allantoin, which is a waste product. This domain is in the last enzyme of the catabolic pathway. Therefore I think it would be misleading to say it is 'biosynthesized' in mice. I think it would be better to change this mapping to allantoin metabolic process (GO:0000255). 
ping @deustp01

**Comment by ukemi** [comment]
Please hold off on this ticket for now. @deustp01 will discuss this further next week.

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have changed the term to 'GO:0000255'. It will be visible in the next InterPro release (86.0).
Best,
Sara
