### ISSUE TITLE
InterPro2GO: P-type ATPase (IPR001757)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3764]
I think you can replace "ATPase (GO:0016887)" currently on this entry with the child term "GO:0140358 P-type transmembrane transporter activity"

**Comment by sjm41** [comment]
Thanks!

**Comment by pgaudet** [comment]
Right for example this family has at least one flippase: 
https://www.ebi.ac.uk/interpro/protein/reviewed/D4AA47/

GO:0005215 transporter activity
and GO:0140603 ATP hydrolysis activity 
would avoid incorrect propagations. 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi,
Thank you very much for clarifying this. I have replaced the term and added those Pascale mentioned.

Best,
Sara

**Comment by sjm41** [comment]
Thanks all.  Apologies for my initial oversight!
