### ISSUE TITLE
InterPro2GO: Spo11/DNA topoisomerase VI subunit A (IPR002815)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3765]
Current MF on this is "endodeoxyribonuclease activity, producing 3'-phosphomonoesters (GO:0016889)"

I think this should be updated to "DNA topoisomerase type II (double strand cut, ATP-hydrolyzing) activity (GO:0003918)" to match the description and the EC number listed at the foot of the page.

Also, the references to 5.99.1.2 and 5.99.1.3 in the description should be updated to 5.6.2.1 and 5.6.2.2, respectively.

**Comment by sarach06** [comment]
Hi,
Many thanks. I have updates the term in this entry and the references you mentioned. The changes will be visible in the next InterPro release (86.0).

Best,
Sara

**Comment by sjm41** [comment]
Great, thanks Sara!
