### ISSUE TITLE
InterPro2GO: DNA fragmentation factor 40 (IPR039729)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3767]
Current GO MF is deoxyribonuclease activity (GO:0004536)

I think that can be improved to the child term: endodeoxyribonuclease activity (GO:0004520).
E.g. the abstract of the given reference on the entry says "...two major apoptotic nucleases, termed DNA fragmentation factor (DFF) or caspase‐activated DNase (CAD) and endonuclease G (Endo G). Both endonucleases attack chromatin to yield 3′‐hydroxyl groups and 5′‐phosphate residues..."

**Comment by EBI-Hsinyu** [comment]
Hi, 
Thank you for this. I have replaced the term. 

Hsin-Yu
