### ISSUE TITLE
Checking IPR000734 & IPR002334

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3769]
Hi,

Triacylglycerol lipase family (IPR000734) has GO MF "triglyceride lipase activity (GO:0004806)".

Vespid venom allergen phospholipase A1 (IPR002334), which is a 'child' of IPR000734, has GO MF "phospholipase A1 activity (GO:0008970)".

But "phospholipase A1 activity (GO:0008970)" is not a child/subtype of "triglyceride lipase activity (GO:0004806)" in the GO/EC.  Is that OK, or should the InterPro2GO associations or InterPro term relations be changed here?

One consequence of the current annotation is that 7 D. melanogaster proteins (products of CG6295, CG6296, CG17192, CG6271, CG6277, CG6283, CG17191) that have both InterPro signatures are getting InterPro2GO annotations to both terms.
The literature says that there is a single phospholipase A1 in D. melanogaster (e.g. PMIDs 28422159 & 25002678), so maybe the issue here is the GO annotation on IPR002334?  Maybe that should be changed to 'lipase activity'??

What do you think?

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have changed the term in IPR002334 and added lipase activity. The changes will be available in the next InterPro release (86.0). 
Best,
Sara

**Comment by sjm41** [comment]
Sounds good, thanks!
