### ISSUE TITLE
HPRT1 (UniProtKB:P00492) should not be annotated to guanine salvage and hypoxanthine salvage

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3770]
HPRT1 encodes the enzyme that is capable of two GO molecular functions, hypoxanthine phosphoribosyltransferase and guanine phosphoribosyltransferase. This enzyme converts the guanine and hypoxanthine substrates to GMP and IMP respectively. The guanine and hypoxanthine salvage pathways in GO are defined as generating guanine and hypoxanthine making this enzymatic activity one step downstream of the salvage. Could the annotations to guanine salvage (GO:0006178) and hypoxanthine salvage (GO:0043103) be removed?
ping @deustp01

**Comment by ukemi** [comment]
Right, it allows them to start with the bases, but the definition of the GO term ends with the base. 
hypoxanthine salvage: Any process that generates hypoxanthine, 6-hydroxy purine, from derivatives of it without de novo synthesis.
guanine salvage: Any process that generates guanine, 2-amino-6-hydroxypurine, from derivatives of it without de novo synthesis.
I'm assuming that the hypoxanthine and guanine in these two processes are an end point and don't go on to form the downstream nucleotides (but we will want to use them as sub-processes at some point continuing along the path via the action of HPRT1)

The other pathways that would start with or go through the bases would end with something else; IMP salvage, GMP salvage etc. So I think this challenge still stands unless the phosphoribosyltransferase reactions can run in the opposite direction. I don't see any evidence for that. Do you agree? If not, let's take a closer look on Thursday and then amend this ticket.

**Comment by pgaudet** [comment]
Hi @ukemi 

If this is the case we should also ask the UniProt curators to edit the gene description, 
https://www.uniprot.org/uniprot/P00492, which now says "Plays a central role in the generation of purine nucleotides through the purine salvage pathway." . Also, many papers refer to this enzyme as being part of the salvage pathway, see for eg:  PMID:19527031 "The purine salvage enzyme hypoxanthine-guanine-xanthine phosphoribosyltransferase", and PMID:33887682 "Parasites of the Plasmodium genus are unable to produce purine nucleotides de novo and depend completely on the salvage pathway. This fact makes plasmodial hypoxanthine-guanine-(xanthine) phosphoribosyltransferase [HG(X)PRT] a valuable target for development of antimalarial agents. "


Is the GO def correct? 

Thanks, Pascale

**Comment by pgaudet** [comment]
So can this close and an ontology ticket be opened if needed? 

Thanks,

**Comment by ukemi** [comment]
Talking with @deustp01 we decided that this is an ontology issue and we will correct these errors by modifying the ontology. We will open a ticket in that tracker.  Bottom line is we don't think these molecules are the end points of any salvage pathways.
