### ISSUE TITLE
Botrytis cinerea and GO annotation

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-annotation#3771]
Hello, 
We've recently got the following request from a UniProtKB user about GO annotation:

> Dear team of Uniprot,
> 
> The GO annotation of fungal species (e.g. Botrytis cinerea) outside of
> 20 model organisms is outdated and a lot of genes miss GO annotation 
> comparing to ensemble. It seems that it has been a long time the GO 
> and Ontology are not updated in this unpopular organism. Could you 
> please update the annotation of the organism-Botrytis cinerea at your 
> earliest convenience?
> Thank you very much for this!
> Sincerely,
> Bettina

This fungus plays indeed an important role in In viticulture and  horticulture, and I think including Botrytis cinerea into PANTHER families could be a good idea. 

In UniProtKB  we have several strains:
Botryotinia fuckeliana (strain B05.10) with TaxID:332648
Botryotinia fuckeliana (strain T4)  with TaxID:999810
Botryotinia fuckeliana (strain BcDW1) with TaxID:1290391

We have also a more general TaxID:40559 for all other strains for which no complete proteomes exist yet.

The most common and annotated strain being strain B05.10 (with TaxID:332648), I would propose to integrate at least this one in PANTHER families. 

Best regards,
Marc.

**Comment by ValWood** [comment]
@huaiyumi  should this close, or move over to the panther tracker?

**Comment by pgaudet** [comment]
right, this should be moved to the PAINT tracker. The upcoming TreeGrafter annotations will likely deal with this.
