### ISSUE TITLE
Add interpro mappings for BMCs

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#3774]
* **InterPro ID / label**

http://www.ebi.ac.uk/interpro/entry/InterPro/IPR004992/

and it's two children

* Ethanolamine utilization protein EutN/carboxysome shell vertex protein CcmL (IPR004992)
    * Carboxysome shell vertex protein CsoS4A (IPR014076)
    * Carboxysome shell vertex protein CsoS4B (IPR014077)

Also http://pfam.xfam.org/family/PF03319

* **Example sequences with problematic annotation (ID + gene/protein name):**

This is a request to add a mapping, not report a problem one

* **Description of issue**

Mappings should be added to

id: GO:0031469
name: polyhedral organelle
namespace: cellular_component
def: "An organelle found in bacteria consisting of a proteinaceous coat containing metabolic enzymes whose purpose is the sequestration or concentration of metabolites and which has the appearance of a polygonal granule by electron microscopy." [GOC:js, PMID:10498708, PMID:11844753, PMID:12923081]
subset: goslim_pir
synonym: "BAC" BROAD []
synonym: "bacterial microcompartment" EXACT []
is_a: GO:0043232 ! intracellular non-membrane-bounded organelle
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/16852 xsd:anyURI

See also #29

This paper from scientists at my institute includes a survey of previous work that used PF03319
https://www.biorxiv.org/content/10.1101/2021.01.25.427685v2

Note this group also came up with some new HMMs, I am not sure of the process of adding these to PFAM/IPR

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have added the term to those entries. The changes will be available in the next InterPro release (86.0).  I will have a look at that paper and the Pfam family. Regarding submission of annotations to Pfam (or any other related questions, information, etc) you can contact us through our helpdesk: http://pfam.xfam.org/help#tabview=tab17. Hope this helps.
Best regards,
Sara
