### ISSUE TITLE
InterPro2GO: HAD hydrolase, subfamily IA IPR006439

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3776]
* **InterPro ID / label**
HAD hydrolase, subfamily IA IPR006439

* **Description of issue**
This is associated with the GO MF "hydrolase activity (GO:0016787)" but one of the subfamilies (Beta phosphoglucomutase IPR010972) is for an isomerase (and is associated with an isomerase GO term).  So I think "hydrolase activity" should be removed from IPR006439?

**Comment by sarach06** [comment]
Hi,
Thank you very much. Yes, you're right. I removed the term.
Cheers,
Sara

**Comment by sjm41** [comment]
Thanks again!
