### ISSUE TITLE
InterPro2GO: Peptidase M16, middle/third domain (IPR032632)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3778]
* **InterPro ID / label**
Peptidase M16, middle/third domain (IPR032632)

* **Description of issue**
I think you can add "metalloendopeptidase activity (GO:0004222)" (corresponds to EC:3.4.24.-) to this entry.

**Comment by sarach06** [comment]
Hi,
Thank you very much. In this case, I wouldn't add the term to this entry because it is not the catalytic domain.

Best,
Sara

**Comment by sjm41** [comment]
Ah, understood.
In that case, would you be able to add that GO term to the "Peptidase M16, N-terminal IPR011765" entry?  Or is that not appropriate because the domain is found in peptidases and non-peptidase homologues?  (I'm not sure what the InterPro policy is for adding catalytic activity GO terms to peptidase domains that may be found both in peptidases and non-peptidase homologues....)

**Comment by sarach06** [comment]
Yes, I also thought to add it to the N-terminal domain but, as you said, it also includes non-peptidase homologues, it is not appropriate. 
Cheers,
Sara

**Comment by sjm41** [comment]
Ok, one last attempt then (!) - how about adding "metalloendopeptidase activity (GO:0004222)" to "Peptidase M16, zinc-binding site IPR001431".  That entry includes the promising comment "This signature pattern only detects active members of the M16 peptidase family."

**Comment by sarach06** [comment]
Haha yes! Forgot to say that. Term added, it will be visible in the next release.

Cheers,
Sara

**Comment by sjm41** [comment]
Excellent, thanks!  Adding that will tidy up the annotations for the fly M16 peptidases (and should help other species annotations too!)
Steven.
