### ISSUE TITLE
 PTN000497525 cactin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3779]
* **PTHR ID & PTN node:**

GO:0010468 | regulation of gene expression | IBA with WBGene00012230 , PTN000497525 , Q8WUQ7

* **Sequences with problematic annotation (ID + gene/protein name):**
SPBC2F12.12c 
O14342

cactin, spliceosome complex subunit

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source. Cactin is a splicing factor.  Splicing has plieotrophic phenotypes so a lot of the annotation ios probably indirect.Although some splicing factors are regulatory,  for splice variants, this could not be transferred.

It definitely seems to be a splicing factor according to this recent Science paper (uncurated)
A human postcatalytic spliceosome structure reveals essential roles of metazoan factors for exon ligation.
Fica SM, Oubridge C, Wilkinson ME, Newman AJ, Nagai K.
Science. 2019 Feb 15;363(6428):710-714. doi: 10.1126/science.aaw5569. Epub 2019 Jan 31.
PMID: 30705154

**Comment by ValWood** [comment]
PMID:20829348 is possibly over-annotated.

**Comment by marcfeuermann** [comment]
Fixed.
