### ISSUE TITLE
	 COPII vesicle coating PTN000333928

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3781]
* **PTHR ID & PTN node:**

sec16 | GO:0048208 | COPII vesicle coating | IBA&nbsp;with&nbsp;S000006006&nbsp;,&nbsp;PTN000333928

* **Sequences with problematic annotation (ID + gene/protein name):**

sec16/O14029

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

sec16 IS a vesicle coat component, so I would class this as erroneous source.

I'm not even sure what this term means. Surely the coat is  the same as  budding? Is it really a different process to

Ontology term: COPII-coated vesicle budding (GO:0090114)
The evagination of an endoplasmic reticulum membrane, resulting in formation of a COPII-coated vesicle.

the coat causes the evagination doesn't it?
?

**Comment by ValWood** [comment]
revised...

**Comment by marcfeuermann** [comment]
I agree the 2 terms are dealing with the same process. May be they could be merged. @pgaudet  ? For now, I've blocked the propagation of this term.

**Comment by pgaudet** [comment]
Hi both, 

You propose merging GO:0048208 | COPII vesicle coating and GO:0090114 COPII-coated vesicle budding , is this right?

**Comment by lbreuza** [comment]
Hi,
what did you do finally? Maybe you should then reconsider merging terms for clathrin-coated pits like clathrin-mediated membrane bending and clathrin coat assembly?

**Comment by ValWood** [comment]
> You propose merging GO:0048208 | COPII vesicle coating and GO:0090114 COPII-coated vesicle budding , is this right?

I'm not sure but that sounds correct. Did we also diascuss this before somewhere? it seems familiar?

**Comment by pgaudet** [comment]
COPII issues come up regularly: https://github.com/geneontology/go-ontology/issues?q=is%3Aissue+COPII
