### ISSUE TITLE
ATPase-coupled transmembrane transporter activity IEA with IPR017871 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3784]
* **InterPro ID / label**
 IPR017871 

* **Example sequences with problematic annotation (ID + gene/protein name):**

Incorrect for 	O14134, O59672, P24488, 	O60102 etc

* **Description of issue**

This family is called "ABC transporter, conserved site" but it is present in many, many non transporters (translation factors for example).
It's just the ATPase domain....

I never understand why this family does not get renamed because this happens every few years...

**Comment by ValWood** [comment]
see for example
**https://github.com/geneontology/go-annotation/issues/48**

**Comment by sjm41** [comment]
This might be my fault - #3763  #3601 

Yes, would be good to change the name & description if this site is not specific to ABC transporters.

**Comment by EBI-Hsinyu** [comment]
Hi, 
I believe this name was from ProSite (they named it "ABC transporters family signature"). According to ProSite, this is "a conserved region which is located between the 'A' and the 'B' motifs of the ATP-binding site.". I agree the name is a bit misleading. I will rename it as "ABC transporter-like, conserved site", as almost all the SwissProt proteins belong to the "ABC transporter superfamily". I hope this name is a bit better.

Regards, 
Hsin-Yu

**Comment by EBI-Hsinyu** [comment]
Hi, 
Forgot to mention that I have removed this GO term. 
Hsin-Yu

**Comment by sjm41** [comment]
Hi @ValWood @EBI-Hsinyu 
Having agreed that "ATPase-coupled transmembrane transporter activity" should not be associated with IPR017871, I think we should have reinstated its original GO term - "ATP hydrolysis activity (GO:0016887)" (see https://github.com/geneontology/go-annotation/issues/3601). Can we add that GO term back to IPR017871?

**Comment by sjm41** [comment]
Hi @EBI-Hsinyu @sarach06 Just checking if you saw the last comment?

**Comment by sarach06** [comment]
Hi Steven, thanks for tagging me in your comment as I missed the previous one.
Yes, I added the term back to this entry, which will be visible in the next release (InterPro 91.0). Just a reminder, Hsin-yu doesn't work at the EBI anymore, so remember not to tag her ;). Thanks!
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara, and thanks for the reminder about Hsin-Yu moving on!
