### ISSUE TITLE
PTN000333928 / organization?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3785]
* **PTHR ID & PTN node:**
PTHR13402 
GO:0007029	endoplasmic reticulum organization IBA with MGI:2139207 , FBgn0052654 , Q96JE7 , PTN000333928 , O15027

* **Sequences with problematic annotation (ID + gene/protein name):**

pombe sec16 / O14029

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

The primary annotation look like phenotypes as a result of transport defects?

**Comment by ValWood** [comment]
GO:0070863	 positive regulation of protein exit from endoplasmic reticulum IBA with PTN000333928 , FBgn0052654 , Q96JE7

Also seems to be , part_of not regulation?

**Comment by pgaudet** [comment]
Fixed.
