### ISSUE TITLE
PTN000420501 not all cyclin-dependent protein serine/threonine kinase regulator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3788]
* **PTHR ID & PTN node:**

GO:0016538 | cyclin-dependent protein serine/threonine kinase regulator activity | IBA&nbsp;with&nbsp;PTN000420501&nbsp;,&nbsp;FBgn0032378&nbsp;,&nbsp;Q8ND76

* **Sequences with problematic annotation (ID + gene/protein name):**

POMBE O13818 (SPAC19A8.02 Ltc2)
This looks like a family problem because the Fly and human protein in the with filedare cyclins.

pombe Ltc2 is an ER membrane tether.

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

**Comment by marcfeuermann** [comment]
Fixed. I've restricted few terms to Metazoa.
