### ISSUE TITLE
GO:0008284 | positive regulation of cell population proliferation/   PTN000623979

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3789]
* **PTHR ID & PTN node:**

GO:0008284 | positive regulation of cell population proliferation | IBA&nbsp;with&nbsp;locus:2099478&nbsp;,&nbsp;P24941&nbsp;,&nbsp;MGI:104772&nbsp;,&nbsp;PTN000623979 | Gaudet P et al. (2011) | 1

* **Sequences with problematic annotation (ID + gene/protein name):**

SPBC11B10.09 / 

P04551

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

 population terms should not. bre used for single species (should be taxon restricted)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
This term is taxon resticted. I thought these were blocked?

**Comment by marcfeuermann** [comment]
It is restricted now. I further updated this annotation.
