### ISSUE TITLE
PTN000073599 proteasome subunit, not assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3791]
* **PTHR ID & PTN node:**

GO:0043248 | proteasome assembly | IBA&nbsp;with&nbsp;PTN000073599&nbsp;,&nbsp;WBGene00004462&nbsp;,&nbsp;O00231&nbsp;,&nbsp;S000002255

* **Sequences with problematic annotation (ID + gene/protein name):**

any proteasome subunit, this one is rpn6/Q9P7S2

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source

**Comment by ValWood** [comment]
Also

GO:0043248 | proteasome assembly | IBA&nbsp;with&nbsp;PTN000027362&nbsp;,&nbsp;locus:2121269&nbsp;,&nbsp;S000001243

rpn9
GO:0043248 | proteasome assembly | IBA&nbsp;with&nbsp;PTN000056911&nbsp;,&nbsp;S000002835

**Comment by marcfeuermann** [comment]
We are aware about this annotations of complex subunits with complex assembly terms. We have decided to check all families with such terms... once we will find time !! Anyway, fixed in these 3 cases.
