### ISSUE TITLE
PTN000027362 not all proteasome regulatory particle, base subcomplex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3792]
* **PTHR ID & PTN node:**

GO:0008540 | proteasome regulatory particle, base subcomplex | IBA&nbsp;with&nbsp;S000001243&nbsp;,&nbsp;rpn10&nbsp;,&nbsp;locus:2121269&nbsp;,&nbsp;O82143&nbsp;,&nbsp;PTN000027362

* **Sequences with problematic annotation (ID + gene/protein name):**

This one is a bit weird. It seems to be inferred from rpn10. However, this is Pof10/

Q9P7W4

It is a WD repeat and F-box protein. Nothing like rpn10?

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
Yup, Panther puts them in the same family,
https://www.pombase.org/gene_subset/interpro:PANTHER:PTHR10223
no idea why????

**Comment by marcfeuermann** [comment]
Due to the presence of many duplications, I've retsricted the propagation and blocked everything for pof10 which is indeed linked to rpn10 in the tree.
