### ISSUE TITLE
Invalid PMID used in annotations from UniProt

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#3793]
Hello
PMID:33410407 is used for 11 annotations to mouse genes (Mttp, 4) and Prap1 in the GOA mouse annotation file MGI loads.
The source of the annotations is "UniProt"

This is an invalid PMID

**Comment by pgaudet** [comment]
@alexsign Can you please look into this?

**Comment by alexsign** [comment]
@hdrabkin @pgaudet This looks like an entry error and timing issue.
On 08-MAR-21 curator added annotation with PMID:33410407
On 08-APR-21 unload for release happened
On 15-APR-21 curator changed annotation to PMID:33168624
I'm not sure what to do with this, but it is correct in Protein2GO and will be corrected in the next release in GOA
