### ISSUE TITLE
PTN000195421  IPR044612 not microtubule polymerization (phenotype)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3795]
* **PTHR ID & PTN node:**

UniProtKB:P36404	ARL2	involved_in	GO:0031116    positive regulation of microtubule polymerization	ECO:0000318   IBA	PMID:21873635	
PANTHER:PTN000195421 more...

positive regulation of microtubule polymerization
IEA with IPR044612
GO_REF:0000002

* **Sequences with problematic annotation (ID + gene/protein name):**

alp41
tubulin complex assembly

& other family members

* **Type of Issue: Erroneous source or erroneous propagation, or other issue*

Most of the annotations seem to come from human eg
http://europepmc.org/article/MED/10831612
http://europepmc.org/article/MED/20740604
etc

 has  some IDA annotations but these are all phenotypes (overexpression/depletion) . If alp41/ARP2 is overexpressed, mutated or depleted  it affects microtubule dynamics (actually more extreme, microtubule integrity), but  this is a phenotype. I don't see any evidence here that the tubulin folding step is  regulating the rate of polymerisation in a normal cell. Regulation of polymerization is by downstream processes through microtubule-associated proteins.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by EBI-Hsinyu** [comment]
Hi, 
You are right. This term is from the animal ARL2 and ARL3 proteins. They regulate TBCD, a tubulin chaperone that affects tubulin folding and microtubule dynamics. We will have to wait for more evidence to see if this is the case for other homologues. I have removed the term for now. This will be visible in InterPro87.0.

Hsin-Yu

**Comment by ValWood** [comment]
Yes, microtubule dynamics (i.e polymerization) are _affected_ if the function is compromised, but this appears to be a phenotype. I don't see evidence that it is regulatory in a normal cell.

**Comment by ValWood** [comment]
IPR044612
[positive regulation of microtubule polymerization](https://www.ebi.ac.uk/QuickGO/term/GO:0031116)
is still present
@sarach06 
@blazaropinto

**Comment by sarach06** [comment]
Dear Val,
I had a look and we don't have the term in IPR044612, probably the propagation comes from other source? 
Best regards,
Sara

**Comment by ValWood** [comment]
Right you are, it is visible in UniProt, but it has gone in QuickGO.
