### ISSUE TITLE
trans sulfuration PTN000146159

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3796]
* **PTHR ID & PTN node:**

GO:0019346 | transsulfuration | IBA&nbsp;with&nbsp;620065&nbsp;,&nbsp;PTN000146159

* **Sequences with problematic annotation (ID + gene/protein name):**

this mapping maps

tum1
thiosulfate sulfurtransferase, involved in tRNA wobble position thiolation Tum1 (predicted)

to "amino acid metabolic process"
through parentage.

I guess it could be considered an ontology is (MF inBP)?

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This term corresponds indeed more an MF than a BP... Anyway the definition does not match the function of these proteins (or some of them). Propagation removed.
