### ISSUE TITLE
PTN000012556 not all glutamine-tRNA ligase activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3801]
* **PTHR ID & PTN node:**

GO:0004819 | glutamine-tRNA ligase activity | IBA&nbsp;with&nbsp;PTN000012556&nbsp;,&nbsp;P00962&nbsp;,&nbsp;S000005694&nbsp;,&nbsp;P47897

and

GO:0006425 | glutaminyl-tRNA aminoacylation | IBA&nbsp;with&nbsp;P00962&nbsp;,&nbsp;S000005694&nbsp;,&nbsp;PTN000012556&nbsp;,&nbsp;P47897

* **Sequences with problematic annotation (ID + gene/protein name):**

O13775
is 
glutamate-tRNA ligase activity

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

.....and is not orthologous to 
S000005694 
(its  ortholog is SGD:S000003214)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Nodes corresponding to glutamine-tRNA ligase activity and glutamate-tRNA ligase activity have been distinguished.
