### ISSUE TITLE
PTN000896085 tfs1 not negative regulation of transcription by RNA polymerase II 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3802]
* **PTHR ID & PTN node:**

GO:0000122 | negative regulation of transcription by RNA polymerase II | IBA&nbsp;with&nbsp;S000001488&nbsp;,&nbsp;PTN000896085

* **Sequences with problematic annotation (ID + gene/protein name):**

P49373
Gene standard name
tfs1
general transcription elongation factor TFIIS
SPAC20H4.03c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

looks like a propagation issue.
S000001488 is not the ortholog of tfs1

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
Also

GO:0045899 | positive regulation of RNA polymerase II transcription preinitiation complex assembly | IBA&nbsp;with&nbsp;PTN000896085&nbsp;,&nbsp;S000003011


is a general transcription factor so should  it be
RNA polymerase II transcription preinitiation complex assembly ?

**Comment by marcfeuermann** [comment]
This complex family has been completely reannotated.
