### ISSUE TITLE
PTN000129453 not regulation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3804]
* **PTHR ID & PTN node:**

GO:0010468 | regulation of gene expression | IBA&nbsp;with&nbsp;MGI:1261425&nbsp;,&nbsp;DDB_G0269426&nbsp;,&nbsp;DDB_G0268410&nbsp;,&nbsp;locus:2024407&nbsp;,&nbsp;S000004852&nbsp;,&nbsp;Q9NRR4&nbsp;,&nbsp;PTN000129453&nbsp;,&nbsp;FBgn0026722&nbsp;,&nbsp;ZDB-GENE-070209-23&nbsp;,&nbsp;A0A1D8PM62&nbsp;,&nbsp;WBGene00009163

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC3B9.14c

mitochondrial ribosomal protein subunit L44
O43042 

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous propagation, this isn't  S000004852 ortholog

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed for the whole mitochondrial ribosomal protein subunit L44 node.
