### ISSUE TITLE
PTN002934191 rsv1 not carbon catabolite repression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3805]
* **PTHR ID & PTN node:**

GO:0000433 | carbon catabolite repression of transcription from RNA polymerase II promoter by glucose | IBA&nbsp;with&nbsp;S000003177&nbsp;,&nbsp;S000003003&nbsp;,&nbsp;PTN002934191&nbsp;,&nbsp;scr1

* **Sequences with problematic annotation (ID + gene/protein name):**

rsv1 (scr1 paralog) does not seem to be involved in carbon catabolite repressions (negative regulation of transcription in high glucose), it appears to be involved in the starvation response.

**Comment by marcfeuermann** [comment]
Another case of  a pombe duplication. Term blocked for rsv1.
