### ISSUE TITLE
PTN002644105 not all lipid kinase/sphingolipid metabolic process (tim54)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3806]
* **PTHR ID & PTN node:**

Tim54 	O94624
GO:0006665	sphingolipid metabolic process
IBA with FBgn0030300 , MGI:3037816 , locus:2119642 , FBgn0260750 , Q8TCT0 , locus:2063004 , FBgn0052484 , C0LT23 , MGI:1917173 , ZDB-GENE-100922-225 , locus:2176202 , Q9LRB0 , locus:6530298214 , S000005697 , S000004250 , Q9NRA0 , PTN002644105 , FBgn0037315 , Q9NYA1 , MGI:1861380

GO:0001727 | lipid kinase activity | IBA&nbsp;with&nbsp;MGI:1316649&nbsp;,&nbsp;locus:2176202&nbsp;,&nbsp;Q9NRA0&nbsp;,&nbsp;Q9NYA1&nbsp;,&nbsp;PTN002644105&nbsp;,&nbsp;FBgn0260750&nbsp;,&nbsp;C0LT23&nbsp;,&nbsp;FBgn0037315&nbsp;,&nbsp;locus:6530298214&nbsp;,&nbsp;MGI:2386052&nbsp;,&nbsp;MGI:1917173&nbsp;,&nbsp;Q8TCT0&nbsp;,&nbsp;locus:2119642
-- | -- | --

* **Sequences with problematic annotation (ID + gene/protein name):**

tim54 O94624

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This seems to be erroneous propagation as tim54 isn't a lipid kinase? and the 

S000005697 , S000004250 are not the pombe orthologs of Tim54

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed.
