### ISSUE TITLE
PTN000339531 not all mitochondrial

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3807]
* **PTHR ID & PTN node:**

	GO:0090646	
mitochondrial tRNA processing
IBA with Q7L0Y3 , FBgn0034351 , PTN000339531

	

* **Sequences with problematic annotation (ID + gene/protein name):**

Trm10 O14214

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

TRMT10C not orthologous, TRM10A is ortholog. 

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed.
