### ISSUE TITLE
PTN001064960  not all cytoplasmic translation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3808]
* **PTHR ID & PTN node:**

GO:0002181	cytoplasmic translation IBA with S000002388 , PTN001064960 , S000005153
GO:0006450	regulation of translational fidelity IBA with S000002388 , S000005153 , PTN001064960	Gaudet P et al. (2011)	13
GO:0000054	ribosomal subunit export from nucleusIBA with PTN001064960 , S000005153 , S000002388	Gaudet P et al. (2011)	28
GO:0005844	polysome IBA with S000002388 , PTN001064960 , S000005153

* **Sequences with problematic annotation (ID + gene/protein name):**
Lsh1 	Q10061

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation
SGD:S000001556 is the ortholog, is ER an chaperone

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed.
