### ISSUE TITLE
PTN001834223 not ER/endoplasmic reticulum unfolded protein response

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3809]
* **PTHR ID & PTN node:**

GO:0030968	endoplasmic reticulum unfolded protein response IBA with MGI:95835 , WBGene00002008 , bip1 , WBGene00002007 , PTN001834223
GO:0030433	 ubiquitin-dependent ERAD pathway IBA with PTN001834223 , locus:2182783 , S000003571
GO:0034663	 endoplasmic reticulum chaperone complex IBA with FBgn0001218 , P11021 , PTN001834223 , MGI:95835	Gaudet P et al. (2011)	2
GO:0005788	endoplasmic reticulum lumenIBA with S000003571 , PTN001834223 , Q6Z7B0 , MGI:95835 , bip1 , P11021	Gaudet P et al. (2011)	10
GO:0016020	membraneIBA with locus:2165715 , Q6Z7B0 , PTN001834223 , MGI:95835 , locus:2182783 , P11021 , bip1

* **Sequences with problematic annotation (ID + gene/protein name):**

ssz1 P87142

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

 erroneous propagation
SGD:S000001106 SSZ1 is ortholog

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
indeed this node is involved in nascent protein folding during translation. Fixed.
