### ISSUE TITLE
PTN001999186 cytogamy

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3810]
* **PTHR ID & PTN node:**

GO:0000755 | cytogamy | IBA&nbsp;with&nbsp;S000001661&nbsp;,&nbsp;PTN001999186

* **Sequences with problematic annotation (ID + gene/protein name):**

Map3  	P31397 SPAC3F10.10c pheromone receptor

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

it seems odd to annotate this to "cytogamy", positive regulation of  conjugation with cellular fusion' seems more accurate. cytogamy is a part of the regulated process...

**Comment by marcfeuermann** [comment]
Fixed
