### ISSUE TITLE
ctp1 isn't an endonuclease

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3813]
* **PTHR ID & PTN node:**

ctp1 | CtIP-related endonuclease | &nbsp; | single-stranded DNA endodeoxyribonuclease activity | &nbsp; | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000387514UniProtKB:Q99708

* **Sequences with problematic annotation (ID + gene/protein name):**

SPCC338.08 O74986
but probably everything

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous source (was thought to be an endonuclease, but is actually an endonuclease activator)

See
PMID:33836577
The Mre11-Rad50-Nbs1 complex (MRN) is important for repairing
DNA double-strand breaks (DSBs) by homologous recombination
(HR). The endonuclease activity of MRN is critical for resecting 5′-
ended DNA strands at DSB ends, producing 3′-ended single-strand
DNA, a prerequisite for HR. This endonuclease activity is stimulated
by Ctp1, the Schizosaccharomyces pombe homolog of human CtIP.
Here, with purified proteins, we show that Ctp1 phosphorylation
stimulatesMRN endonuclease activity by inducing the association of
Ctp1 with Nbs1. The highly conserved extreme C terminus of Ctp1 is
indispensable for MRN activation. Importantly, a polypeptide composed
of the conserved 15 amino acids at the C terminus of Ctp1
(CT15) is sufficient to stimulate Mre11 endonuclease activity. Furthermore,
the CT15 equivalent from CtIP can stimulate human
MRE11 endonuclease activity, arguing for the generality of this stimulatory
mechanism. Thus, we propose that Nbs1-mediated recruitment
of CT15 plays a pivotal role in the activation of the Mre11
endonuclease by Ctp1/CtIP.

I will also remove PomBase ISO and make an explicit  NOT annotation.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
The panther family name would need updating too. It seems that the original annotations are  from mutant phenotypes.

**Comment by ValWood** [comment]
Actually one is an assay (S. cerevisiae). The authors of the paper above inform me that in fission yeast this is not an endonuclease.

**Comment by marcfeuermann** [comment]
Family name and annotations have been updated.
