### ISSUE TITLE
IPR000685->RuBisCo is lacking a meaningful GO association

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#3815]
* **InterPro ID / label**

http://www.ebi.ac.uk/interpro/entry/InterPro/IPR000685/  Ribulose bisphosphate carboxylase, large subunit, C-terminal

which corresponds to Ribulose bisphosphate carboxylase large chain, catalytic domain
http://pfam.xfam.org/family/PF00016

* **Example sequences with problematic annotation (ID + gene/protein name):**

This is an interpro->go mapping issue, not a interpro annotation issue

* **Description of issue**

See #29 for history

this interpro should be mapped to:

[Term]
id: GO:0016984
name: ribulose-bisphosphate carboxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: D-ribulose 1,5-bisphosphate + CO2 + H2O = 2 3-phospho-D-glycerate." [EC:4.1.1.39]
synonym: "3-phospho-D-glycerate carboxy-lyase (dimerizing)" RELATED [EC:4.1.1.39]
synonym: "3-phospho-D-glycerate carboxy-lyase (dimerizing; D-ribulose-1,5-bisphosphate-forming)" RELATED [EC:4.1.1.39]
synonym: "carboxydismutase activity" RELATED [EC:4.1.1.39]
synonym: "D-ribulose 1,5-diphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "D-ribulose-1,5-bisphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "diphosphoribulose carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose 1,5-bisphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose 1,5-bisphosphate carboxylase/oxygenase activity" EXACT []
synonym: "ribulose 1,5-diphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose 1,5-diphosphate carboxylase/oxygenase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose bisphosphate carboxylase/oxygenase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose diphosphate carboxylase activity" RELATED [EC:4.1.1.39]
synonym: "ribulose diphosphate carboxylase/oxygenase activity" RELATED [EC:4.1.1.39]
synonym: "RuBisCO activity" RELATED [EC:4.1.1.39]
synonym: "rubisco activity" EXACT []
synonym: "RuBP carboxylase activity" RELATED [EC:4.1.1.39]
xref: EC:4.1.1.39
xref: MetaCyc:RIBULOSE-BISPHOSPHATE-CARBOXYLASE-RXN
xref: RHEA:23124
is_a: GO:0016831 ! carboxy-lyase activity

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I added the term to this entry, which will be visible in the next InterPro release (87.0).
Best regards,
Sara
