### ISSUE TITLE
Review annotations to GO:0070615 nucleosome-dependent ATPase

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3817]
The definition of GO:0070615 nucleosome-dependent ATPase is rather vague (Catalysis of the reaction: ATP + H2O = ADP + phosphate. This reaction requires the presence of one or more nucleosomes), and could potentially represent many different functions. 

During the ATPase jamboree we are discussing obsoleting the term. We are reviewing the annotations to make a final decision: 

https://docs.google.com/spreadsheets/d/1dJJhbeNnsEzCAIunaYnXVFTTNKqyO-071TmIsqsraJE/edit#gid=0

Thanks, Pascale

**Comment by bmeldal** [comment]
Note to self: we have a total of 7 complexes annotated to GO:0070615 (3x human [on spreadsheet] 3 mouse orthologs, 1 yeast)

**Comment by hdrabkin** [comment]
So the suggestion is to remove the annotation? No replacement?

**Comment by pgaudet** [comment]
@hdrabkin No, we dont suggest to remove, we haven't had time to make suggestions yet. Some seems 'easy', like helicases, but maybe that 's not the case for all.

**Comment by ValWood** [comment]
Note, most are not helicases, even though they have helicase  domains, most are ATP-dependent chromatin remodellers.

**Comment by pgaudet** [comment]
For today's annotation call: all proteins annotated to 'GO:0070615 nucleosome-dependent ATPase' can be re-annotated to GO:0140658 ATP-dependent chromatin remodeler activity. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Complexes done.

**Comment by hdrabkin** [comment]
MGI done

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
Only 2 SGD annotations left. Thanks everyone!

**Comment by srengel** [comment]
SGD done.

**Comment by ValWood** [comment]
All gone
https://www.pombase.org/results/from/id/d8b601a9-8d3d-47e4-87a5-657680ee0810
