### ISSUE TITLE
PTN002462320 not enzyme activator

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3818]
* **PTHR ID & PTN node:**

GO:0008047 | enzyme activator activity | IBA&nbsp;with&nbsp;S000000898&nbsp;,&nbsp;PTN002462320 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

SPBC23G7.04c/ P87159

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

possibly a propagation error because S000000898 is not ortholog.

**Comment by marcfeuermann** [comment]
Removed all propagations from this unPAINTable family.
