### ISSUE TITLE
Carboxysome assembly protein IPR020990 should be mapped to structural constituent of carboxysome

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#3820]
* **InterPro ID / label**

http://www.ebi.ac.uk/interpro/entry/InterPro/IPR020990/

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

Should this be mapped to:

id: GO:0043886
name: structural constituent of carboxysome
namespace: molecular_function
def: "The action of a molecule that contributes to the structural integrity of a carboxysome, an organelle found in all cyanobacteria and some chemoautotrophs, consisting of a proteinaceous coat and enzymes for the fixation of CO(2)." [GOC:jl, PMID:28934381]
is_a: GO:0005198 ! structural molecule activity
intersection_of: GO:0005198 ! structural molecule activity
intersection_of: occurs_in GO:0031470 ! carboxysome
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19743 xsd:anyURI

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have added the term to this entry, it will be available in the next InterPro release (87.0).

Best regards,
Sara
