### ISSUE TITLE
PTN000643689 (PTHR42861) & source annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3821]
* **PTHR ID & PTN node:**
PTN000643689 (PTHR42861)

* **Sequences with problematic annotation (ID + gene/protein name):**
(YEAST\|SGD=S000003135\|UniProtKB=P13586) PMID:10801856
(CAEEL\|WormBase=WBGene00004063\|UniProtKB=G5EDU1) PMID:11134055
(HUMAN\|HGNC=13211\|UniProtKB=P98194) PMID:12707275

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
The above 3 sources annotate to "GO:0015410 ABC-type manganese transporter activity", but the proteins are P-type transporters, so I think the terms should probably be changed to "GO:0140613 P-type manganese transporter activity"?

@pgarmiri 
@vanaukenk 
@srengel

**Comment by vanaukenk** [comment]
Thanks @sjm41 
I've updated the C. elegans annotations.  It will take a bit for these to trickle through the WB system, but they should be in our production GAF files for the WS282 WB release (~October 1st, 2021).

**Comment by pgaudet** [comment]
Fixed the PAINT annotations.

**Comment by pgaudet** [comment]
@suzialeksander Would you please look at the yeast annotation (YEAST|SGD=S000003135|UniProtKB=P13586) PMID:10801856?

**Comment by sjm41** [comment]
Thanks @pgaudet

**Comment by pgaudet** [comment]
Fixed human annotation

**Comment by srengel** [comment]
fixed the yeast annotation in P2GO just now.
