### ISSUE TITLE
PTN000226268, wnt signalling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3822]
GO:0016055 Wnt signaling pathway

Definition	
The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell and ending with a change in cell state. 

GO:0016055 Wnt signaling pathway
IBA with PTN000226268 , P49674

Should  be blocked for yeast as they don't have "Wnt protein"

Affects
cki1	GO:0016055	
Wnt signaling pathway
IBA with P49674 , PTN000226268	Gaudet P et al. (2011)	5
cki2	
IBA with PTN000226268 , P49674	Gaudet P et al. (2011)
cki3	
IBA with PTN000226268 , P49674	Gaudet P et al. (2011)
hhp1	
IBA with PTN000226268 , P49674	Gaudet P et al. (2011)
hhp2	
IBA with P49674 , PTN000226268	Gaudet P et al. (2011)

Block should be at:
cell-cell signaling by wnt (GO:0198738)

**Comment by marcfeuermann** [comment]
I wouldn't have propagated this term. Fixed.
