### ISSUE TITLE
PTN002000498 not directly amino acid transport (causally upstream)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3826]
* **PTHR ID & PTN node:**

GO:0006865 | amino acid transport | IBA with PTN002000498 , A0A1D8PLU5

* **Sequences with problematic annotation (ID + gene/protein name):**

Q9Y876
https://www.pombase.org/gene/SPBC409.20c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation,
This is an ER packaging chaperone for packaging amino acid transporters into ER COPI vesicles.
I would not annotate to amino acid transport. It seems causally upstream?

Although I would like to know what the rules would be here.
@vanaukenk @pgaudet  ?

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
I agree. Propagation removed.
