### ISSUE TITLE
IPR012879 not GO:0036503 ERAD pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3827]
* **InterPro ID / label**
* 
PAT complex subunit CCDC47
GO:0036503 | ERAD pathway | IEA with IPR012879 | GO_REF:0000002

* **Example sequences with problematic annotation (ID + gene/protein name):**

this seems indirect (causally upstream), as a consequence of incorrect transport from ER to Golgi (possibly due to incorrect membrane insertion in the ER compartment immediately post-translocation.

I would not make this annotation for GO it seems to be a phenotype, unless you have evidence for a more direct involvement in ERAD.

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. Yes, I agree with you. I have removed the term from this entry. The changes will be visible in the next InterPro release (87.0).
Best regards,
Sara
