### ISSUE TITLE
PTN001161029, likely not borate transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3828]
* **PTHR ID & PTN node:**

 GO:0035445 | borate                     transmembrane transport | IBA                with    S000004892                                                                                                     PTN001161029

* **Sequences with problematic annotation (ID + gene/protein name):**

SPBC1683.03c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

 erroneous propagation
 ortholog  AMF1 / YOR378W at SGD has

Low affinity NH4+ transporter; member of the DHA2 family of drug:H+ anti porters; putative paralog of ATR1; but not required for boron tolerance;

**Comment by pgaudet** [comment]
Removed.
