### ISSUE TITLE
PTN000562490  not all translation elongation factor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3829]
* **PTHR ID & PTN node:**

GO:0003746	
translation elongation factor activity
IBA with DDB_G0269134 , DDB_G0269136 , PTN000562490 , S000000322 , MGI:1096317

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC25B2.01

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation S000000322 is not the ortholog

**Comment by marcfeuermann** [comment]
Within a node of 4 duplicated S. pombe leaves, one has a divergent function. Fixed.

**Comment by ValWood** [comment]
I'm not sure this is a divergent paralog, its a separate orthologous group... onserved to human:



Homo sapiens | HBS1L (HGNC:4834) | HBS1 like translational GTPase
Saccharomyces cerevisiae | HBS1 (YKR084C) | GTPase with similarity to translation release factors more ...

so this one might be a PAINT issue  (they are quite closely relate to the EF-1 alpha)

**Comment by marcfeuermann** [comment]
I was thinking that it might be a tree issue. My comments usually just try to explain why we did the propagation error. I will submit the issue to the Panther friends.
