### ISSUE TITLE
 PYURF  has PIGY annotations but is not PIGY PANTHER:PTN002127271 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3831]
* **PTHR ID & PTN node:**

UniProtKB:Q96I23 | PYURF | involved_in | GO:0006506    GPI anchor biosynthetic process | ECO:0000318   IBA | PMID:21873635 | PANTHER:PTN002127271 more... | 9606 Homo sapiens | GO_Central |  

UniProtKB:Q96I23 | PYURF | part_of | GO:0000506    glycosylphosphatidylinositol-N-acetylglucosaminyltransferase (GPI-GnT) complex | ECO:0000318   IBA | PMID:21873635 | PANTHER:PTN002127271 more... | 9606 Homo sapiens | GO_Central

* **Sequences with problematic annotation (ID + gene/protein name):**

UniProtKB:Q96I23 and any sequence transferred to

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source
see
PREY and PIGY, 2 apparently unrelated proteins, are respectively the product of an upstream and a downstream ORF contained in a single bicistronic transcript.

all of the annotations on PREY should  be on PIGY

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by pgaudet** [comment]
I removed the annotations. The data was from a single paper.
