### ISSUE TITLE
PTN002005445  not TFIIH

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3832]
* **PTHR ID & PTN node:**

GO:0005669 | transcription factor TFIID complex | IBA with Q6ZYL4 , PTN002005445 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC32F12.15

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

is TFIIH. Looks like erroneous annotation on
https://www.uniprot.org/uniprot/Q6ZYL4

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
I guess you wanted to say not TFIID complex. Fixed.

**Comment by ValWood** [comment]
yep!
