### ISSUE TITLE
Review annotations to GO:0043044  ATP-dependent chromatin remodeling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3833]
Discussing with @colinlog and as part of the work on ATPases

GO:0043044  ATP-dependent chromatin remodeling  will be merged into GO:0006338 chromatin remodeling, see 
https://github.com/geneontology/go-ontology/issues/21732

We suggest people consider using the new term, GO:0140658 ATP-dependent chromatin remodeler activity, to capture ATP-dependent chromatin remodelers. 

Annotations are here: 
https://docs.google.com/spreadsheets/d/1dlmmkswk6CU6cvIL5eTDDj7fEO9Gn3PFQbMbCLbAH9Q/edit#gid=0
@colinlog and I tried to mark ATP-dependent remodelers that we could easily spot, this may not be exhaustive.

Special note for yeast: 
These are the ATP-dependent chromatin remodelers in yeast: 
ISW1, ISW2, STH1, SNF2, FUN30, INO80, SWR1, yfr038w, CHD1  (note that not all of them are annotated to GO:0043044  ATP-dependent chromatin remodeling, but you may want to annotate the MF for all of them). 

Thanks, Pascale

**Comment by hdrabkin** [comment]
MGI done using suggested term.

**Comment by ValWood** [comment]
Will annotate the pombe MFs today. Very happy for the others to merge into chromatin remodeling

**Comment by ValWood** [comment]
A question, I got a bit lost in the  series of changes here. 

Some of our GO:0140658 ATP-dependent chromatin remodeler activity are now annotated to

GO:0070615 | nucleosome-dependent ATPase activity

will this term merge into 
GO:0140658 ATP-dependent chromatin remodeler activity
and are/will there be  there more specific terms to represent the histone/nucleosome loaders?

**Comment by ValWood** [comment]
> A question, I got a bit lost in the series of changes here.

ignore, I found the ticket about 
GO:0070615 | nucleosome-dependent ATPase activity

I agree it should be obsoleted. It has name mappings to divergent ATPases acting on DNA (helicases), and nucleosomes (loaders)

**Comment by bmeldal** [comment]
@pgaudet I picked this up from the Jenkins report. No-one is yet assigned to this ticket.

**Comment by RLovering** [comment]
ucl done

**Comment by pgaudet** [comment]
For today's ontology call - what remains: 
- SGD and ZFIN annotations
- clarification on MGI corrections

**Comment by bmeldal** [comment]
I'm on it, 36 complexes remaining! (The GO search doesn't find them all so I always do my internal one.)

**Comment by bmeldal** [comment]
> I'm on it, 36 complexes remaining! (The GO search doesn't find them all so I always do my internal one.)

CP done :)

**Comment by srengel** [comment]
i can work on this towards the end of next week.

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
Merge has been done
@srengel do you still want to review these?

**Comment by srengel** [comment]
oops, sorry for the delay, i think the change has already been made on the GO side.  i went through our list and added the suggested annotations to GO:0140658 ATP-dependent chromatin remodeler activity

**Comment by pgaudet** [comment]
Thanks!
