### ISSUE TITLE
PTN002000061  not  regulation of transcription, DNA-templated

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3835]
* **PTHR ID & PTN node:**

GO:0006355 | regulation of transcription, DNA-templated | IBA with PTN002000061 , S000002704 | Gaudet P et al. (2011)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous annotation, seems to be pouit of date. I would not transfer this:

MHR1
Mitochondrial ribosomal protein of the large subunit; also involved in homologous recombination in mitochondria; required for recombination-dependent mtDNA partitioning; involved in stimulation of mitochondrial DNA replication in response to oxidative stress 2 3 4 5 6

regulation of transcription, DNA-templated		IPI with GAL4	SGD	2008-01-03	Emili A, et al. (1998) PMID:9736700

**Comment by marcfeuermann** [comment]
Fixed.
