### ISSUE TITLE
Review annotations to GO:0046695 SLIK (SAGA-like) complex

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#3837]
See geneontology/go-ontology#21727. RTG2 is no longer considered part of the SLIK complex thus annotations associating SLIK with RTG2 and its homologues should be reviewed and probably deleted.

https://docs.google.com/spreadsheets/d/1WFBZGeXm_Jeydbka0tSpq0dxBAEpi9tEf9ztlX4n0Ys/edit?usp=sharing

**Comment by pgaudet** [comment]
Fixed PAINT annotations to PTHR30005.

Thanks, Pascale

**Comment by suzialeksander** [comment]
SGD done
