### ISSUE TITLE
IPR002219 "Protein kinase C-like, phorbol ester/diacylglycerol-binding domain": 5 not all signal transduction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3838]
* **InterPro ID / label**

IPR002219 

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene_subset/interpro:IPR002219
SPBC12C2.05c | bzz1 | F-BAR domain protein Bzz1
SPAC3H1.12c | snt2 | Lid2 complex PHD finger subunit Snt2

* **Description of issue**

This domain is present in non signal transducers:

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. I have removed the term from this entry. The changes will be visible in the next InterPro release (87.0)
Best,
Sara
