### ISSUE TITLE
Hopanoid biosynthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3839]
* **InterPro ID / label**

IPR006400

* **Example sequences with problematic annotation (ID + gene/protein name):**

B6K412
http://japonicusdb.kmr.nz/gene/SJAG_03360

* **Description of issue**

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6087623/
Hopanoids are found in diverse bacteria and in a handful of lichens and plants. Similar to eukaryotic sterols, hopanoids are planar, polycyclic hydrocarbons containing five rings compared with the four rings in sterols, and they have a variety of polar and nonpolar side chains2.19 Feb 2018

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. I have updated this entry and added the reference you provided, which will be available in the next InterPro release (87.0).
Best,
Sara
