### ISSUE TITLE
topoisomerase and chromatin remodelling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3841]
* **PTHR ID & PTN node:**

GO:0006338 | chromatin remodeling | IBA with P11387 , S000005366 , PTN000033230

The SGD one looks like a phenotype. Could be with indirect. I would not transfer.

Stil need to look at the human one.

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This is redundant to #3843 and has been fixed by Pascale.
