### ISSUE TITLE
Topoisomerase , not chromatin remodelling - PTHR10290

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3843]
* **PTHR ID & PTN node:**

GO:0006338 | chromatin remodeling | IBA with P11387 , S000005366 , PTN000033230

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC1703.14c
but any topoisomerase

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous annotation.

Discussed today on chromatin remodelling call with @colinlog  & @pgaudet

**Comment by pgaudet** [comment]
Fixed
