### ISSUE TITLE
IPR006274 is not specific for GO:0004088

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#3844]
* **InterPro ID / label**
IPR006274 Carbamoyl-phosphate synthase, small subunit
* **Example sequences with problematic annotation (ID + gene/protein name):**
mouse Cps1 (MGI:891996)--UniProtKB:Q8C196
* **Description of issue**
This gene product is being assigned GO:0004088 carbamoyl-phosphate synthase (glutamine-hydrolyzing) activity, defined as 'Catalysis of the reaction: 2 ATP + L-glutamine + CO2 + H2O = 2 ADP + phosphate + glutamate + carbamoyl phosphate.'
As near as I can tell, this enzyme actually enables GO:0004087 carbamoyl-phosphate synthase (ammonia) activity, defined as Catalysis of the reaction: 2 ATP + CO(2) + H(2)O + NH(4)(+) = 2 ADP + carbamoyl phosphate + 5 H(+) + phosphate.

@hdrabkin @deustp01

**Comment by sarach06** [comment]
Hi,
I think the GO:0004088 term is correct as it is supported by other databases and represents the majority of the members in this entry, apart that the abstract mentions the substrates and pathways they are involved in (also see https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=6.3.5.5). Hope this helps.
Best regards,
Sara

**Comment by suzialeksander** [comment]
sounds like a wontfix
