### ISSUE TITLE
PomBase histone demethylases

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3845]
From @ValWood in the ontology tracker, https://github.com/geneontology/go-ontology/issues/21089

I would like to be able to annotate to
"histone demethylase activity" for family members with no experimental data. If these are like set domain we can't assume that all members have the same specificity.

The methyltransferase specificities:
Systematic ID | Gene name | Product description
SPAC29B12.02c | set2 | histone lysine H3-K36 methyltransferase Set2
SPCC297.04c | set7 | histone lysine H3-K37 methyltransferase Set7
SPCC306.04c | set1 | histone lysine H3-K4 methyltransferase Set1
SPBC428.08c | clr4 | histone lysine H3-K9 methyltransferase Clr4
SPCC4B3.12 | set9 | histone lysine H4-K20 methyltransferase Set9
SPAC22E12.11c | set3 | histone lysine methyltransferase Set3
SPCC1739.05 | set5 | histone lysine methyltransferase Set5 (predicted)
SPBP8B7.07c | set6 | histone lysine methyltransferase Set6 (predicted)

**Comment by pgaudet** [comment]
Are these methylases or demethylases?

**Comment by ValWood** [comment]
These are methylases, but I was using to explain that the situation is similar for the demethylases. We don't know the specificity of all of the family members so we need to be able to annotate to the parent. We cant assume that all the family members have the same specificity.
v

**Comment by pgaudet** [comment]
OK but I have not seen examples yet. We can edit once we find examples?

**Comment by ValWood** [comment]
jmj1 & 4 are the examples?

**Comment by ValWood** [comment]
I only want to annotate to
"histone demethylase activity"
I was using the methylases  for comparison to show that they are usually modification specific.
If the demethylases are the same, then we cannot be more specific than histone demethylase activity right now.
