### ISSUE TITLE
iml1 not  GO:0034198 | cellular response to amino acid starvation 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3846]
* **PTHR ID & PTN node:**

GO:0034198 | cellular response to amino acid starvation | IBA with PTN000323637, O75140 , FBgn0035227

* **Sequences with problematic annotation (ID + gene/protein name):**

iml1
https://www.pombase.org/gene/SPBC26H8.04c
O74788

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

In addition, unlike in mammals, the GATOR complex is dispensable for TORC1 regulation in
fission yeast under amino acid starvation.

(this branch of pathway is nitrogen starvation which is different from amino acid starvation).

PMID:33534698
Title | Tripartite suppression of fission yeast TORC1 signaling by the GATOR1-Sea3 complex, the TSC complex, and Gcn2 kinase.
Authors | Fukuda T, Sofyantoro F, Tai YT, Chia KH, Matsuda T, Murase T, Morozumi Y, Tatebe H, Kanki T, Shiozaki K

**Comment by ValWood** [comment]
Also



iml1 |   | IBA with PTN000323637 , O75140 , FBgn0035227 | Gaudet P et al. (2011)
npr2 |   | IBA with PTN000988255 , FBgn0030800 , Q8WTW4 | Gaudet P et al. (2011)
sea4 |   | IBA with FBgn0031399 , PTN000419916 , Q9NXC5

**Comment by marcfeuermann** [comment]
All 3 families have been updated accordingly.

**Comment by ValWood** [comment]
I should add that I am not sure how conserved response this is. 
"cellular response to starvation" would be OK for everything...
