### ISSUE TITLE
V-ATPase subunit annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3850]
* **InterPro ID / label**
E.g.
ATPase, V0 complex, subunit (IPR008389)
ATPase, V0 complex, subunit e1/e2 (IPR008389)
ATPase, V1 complex, subunit C (IPR004907)

* **Description of issue**
Most of the InterPro entries for V-ATPases I've looked at map to "proton transmembrane transporter activity (GO:0015078)" - 3 examples above. I think these could all use the more specific child term "proton-transporting ATPase activity, rotational mechanism" (GO:0046961), as some other V-ATPase subunit entries already do (e.g. IPR014272 ).

What do you think?

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have reviewed the entries related to V-ATPases (V1/V0 complex) and added the child term "proton-transporting ATPase activity, rotational mechanism" (GO:0046961) when suitable. The changes will be visible in the next InterPro release (87.0). Let me know if you find entries in which should be added or if I miss something.
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
Do you mind listing the relevant V-ATPase InterPro entries here? Then I can have a quick check. Thanks, Steven.

**Comment by sarach06** [comment]
Yes, sure. Apart from the ones you listed, IPR002843 (and its child IPR016727), IPR002842, IPR002490, IPR005124, IPR022878, IPR008218, IPR000245 (and its child entry IPR011555), IPR005723 and IPR002699. There were some not listed here because they had already the term. 
Thanks, 
Sara

**Comment by sjm41** [comment]
Looks good to me, thanks again!
