### ISSUE TITLE
NADP-dependent oxidoreductase domain (IPR023210)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3851]
* **InterPro ID / label**
NADP-dependent oxidoreductase domain (IPR023210)

* **Description of issue**
This entry describes a "NADP-dependent oxidoreductase domain" though the GO-MF term is the rather specific "D-threo-aldose 1-dehydrogenase activity (GO:0047834)", which corresponds to EC:1.1.1.122.

Maybe change to the parent term?:
oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616)
which corresponds to EC:1.1.1.-

That said, I see that this domain is found in the glutamate-cysteine ligase modifier subunit (GCLM = P48507), which is a regulatory subunit of the glutamate-cysteine ligase complex.  I'm not aware that this protein is known to have an oxidoreductase activity??

**Comment by sarach06** [comment]
Hi,
I think in this case, to avoid wrong transferences, is better to delete this term and don't add GO:0016616. Do you agree?
Best,
Sara

**Comment by sjm41** [comment]
That's fine with me!  There's just one source (https://www.ebi.ac.uk/interpro/entry/pfam/PF00248/), and the evidence there doesn't seem overwhelming....

**Comment by sarach06** [comment]
Yes, I know. It is a domain entry and include many members, some of them may not have oxidoreductase activity. Let's keep it safe :-)
Cheers,
Sara
