### ISSUE TITLE
Aldehyde dehydrogenase, C-terminal (IPR016163)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3852]
* **InterPro ID / label**
Aldehyde dehydrogenase, C-terminal (IPR016163)

* **Description of issue**
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR016163/ has an redundant 'oxidoreductase activity' GO-MF term.

**Comment by sarach06** [comment]
Many thanks. I deleted the more general term. The changes will be visible in the next InterPro release (87.0).

Sara
