### ISSUE TITLE
Noctua annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3853]
HI @ukemi 
I notice in Noctua model that  TORC signalling is annotated as negatively regulating autophagy, but in all species  studied doesnt TORC signalling negatively regulate autophagy and promote growth? (i.e positively regulate translation etc)?

**Comment by ukemi** [comment]
Which model? Is there evidence on it?

**Comment by ValWood** [comment]
A bit more information.

There are lots or negative regulator of TOR signalling which  turn off TORC1 signalling promote autophagy.
at least 3 parallel pathways  converge  inhibit TOC1 signalling (GATOR1,  which inhibits the RagGTPase and RHEB GAP which inhibits the Rheb GTPase. Both of these GTPases are positive regulators of TORC1 signalling.

**Comment by ValWood** [comment]
Sorry, I thought I included the model)
Noctua model for TORC1 signalling
http://noctua.berkeleybop.org/editor/graph/gomodel:60e7989d00000085?model_id=gomodel:60e7989d00000085&barista_token=awnuqh4qaomi9szqaptv#

**Comment by ValWood** [comment]
wrong model link, I will find it.

**Comment by ukemi** [comment]
Don't include the token in the link.

**Comment by ValWood** [comment]
It's this one
http://noctua.berkeleybop.org/editor/graph/gomodel:567b544200000138?

This part

<img width="673" alt="Screenshot 2021-07-12 at 13 54 56" src="https://user-images.githubusercontent.com/7359272/125291148-fd1a1f80-e318-11eb-9257-6d0380b9b3c8.png">

**Comment by ValWood** [comment]
I don't know how to access the evidence.

**Comment by ukemi** [comment]
This is only a development model. I wouldn't put any faith in it.

**Comment by ValWood** [comment]
<img width="227" alt="Screenshot 2021-07-12 at 13 58 27" src="https://user-images.githubusercontent.com/7359272/125291381-3eaaca80-e319-11eb-816d-b90d27870f04.png">

**Comment by ukemi** [comment]
If I don't make them production, a lot of time I'm just playing around.

**Comment by ValWood** [comment]
Ah right, I was just looking for models of TOR. will ignore

**Comment by ukemi** [comment]
No worries. I'm glad you are looking at models.  :)

**Comment by ValWood** [comment]
I'm trying to figure out how to convert our causal models annotation into CO-CAM compliant format so they can be imported :)
I tried to model a bit of this pathway to export but came across some bugs  which prevented me proceeding  (on Noctua tracker) so I was looking for similar models.

**Comment by ukemi** [comment]
I saw your bug reports, but almost always just find it easier to look over someone's shoulder as they work to try to figure things out. Let me know if you want to try that. Wednesday morning I am completely open (for the moment).

**Comment by ukemi** [comment]
Sounds good. @vanaukenk is out today, but just in case she wants to join us, I have included her here.
