### ISSUE TITLE
NADH dehydrogenase ubiquinone Fe-S protein 4, mitochondrial (IPR006885)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3854]
* **InterPro ID / label**
NADH dehydrogenase ubiquinone Fe-S protein 4, mitochondrial (IPR006885)

* **Description of issue**
This family is for/includes Complex I *accessory* subunits, not involved in catalysis, eg. NDUFS4 (O43181).
So I think the GO-MF "oxidoreductase activity, acting on NAD(P)H (GO:0016651)" should be removed.

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have removed this term and updated the description.
Cheers,
Sara

**Comment by sjm41** [comment]
Thanks!
