### ISSUE TITLE
Squalene/phytoene synthase (IPR002060)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3856]
* **InterPro ID / label**
Squalene/phytoene synthase (IPR002060)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Q330K2 (NDUF6_HUMAN)
Q9VYS5 (NDUF6_DROME)

* **Description of issue**
This entry is associated with the GO-MF "transferase activity (GO:0016740)" buts also hits well-known oxidoreductases like the NDUF6 orthologs mentioned above.  Also, many of the EC numbers associated with the entry are not transferases.  So, remove this MF term from the entry?

**Comment by sarach06** [comment]
Hi Steven,
Yes, I removed the term from this entry.
Thank you very much,
Sara

**Comment by sjm41** [comment]
Thanks.
