### ISSUE TITLE
Phosphatidylinositol N-acetylglucosaminyltransferase subunit H (IPR044215)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3857]
* **InterPro ID / label**
Phosphatidylinositol N-acetylglucosaminyltransferase subunit H (IPR044215)

* **Description of issue**
PIG-H isn't the catalytic subunit of the glycosylphosphatidylinositol-N-acetylglucosaminyltransferase (GPI-GnT) complex, so I think the GO-MF (phosphatidylinositol N-acetylglucosaminyltransferase activity (GO:0017176)) on IPR044215 should be removed.

E.g. from PMID: 19883648:
 GPI-GlcNAc transferase (GPI-GnT), a multi-subunit enzyme consisting of seven components (PIG-A, PIG-C, PIG-H, PIG-P, PIG-Q, PIG-Y, and DPM2), catalyzes this reaction. The PIG-A gene encoding the catalytic subunit of GPI-GnT is

**Comment by sarach06** [comment]
Hi,
Many thanks. I have removed the term from this entry and aldo from IPR019328 (GPI-GlcNAc transferase complex, PIG-H component, conserved domain).
Cheers,
Sara

**Comment by sjm41** [comment]
Thanks again!
