### ISSUE TITLE
Triacylglycerol lipase family (IPR000734) & Lipase/vitellogenin (IPR013818)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3859]
* **InterPro ID / label**
Triacylglycerol lipase family (IPR000734) & Lipase/vitellogenin (IPR013818)

* **Description of issue**
Both these terms are associated with GO-MF "triglyceride lipase activity (GO:0004806)" but I think that term might be too specific.

_Triacylglycerol lipase family (IPR000734)_
- InterPro 'child terms' are Vespid venom allergen phospholipase A1 (IPR002334) and Lipase, LIPH-type (IPR016272), which are not specific to 'triglyceride lipase activity'
- associated EC xrefs include several other specific lipase terms in addition to 'triglyceride lipase activity' (which is EC: 3.1.1.3)
- contributing entries include PTHR11610 'LIPASE', which seems to be a more general lipase grouping.

=> change MF to 'lipase activity' and remove 'Triacylglycerol' from term name?
(relates to previous tickets #3769 &  #2923)

_Lipase/vitellogenin (IPR013818)_
- associated EC xrefs include several other specific lipase terms in addition to 'triglyceride lipase activity' (which is EC: 3.1.1.3)
- single contributing entry is PF00151, which is just described as 'Lipase'
- entry also mentions "Lipoprotein lipases also exhibit homology with a region of Drosophila vitellogenins. That region, represented by this entry, is entirely within the N-terminal domain of lipoprotein lipase..."  The Drosophila vitellogenins (Yp1/Vit1Dm, Yp2/Vit2Dm, Yp3/Vit3Dm2) are described in PMID: 19540341 as catalytically inactive, though vitellogenins of other insects are described as functional.  IPR013818 hits many more Drosophila proteins than the 'vitellogenins' anyway.

=> change MF to 'lipase activity' and remove 'vitellogenin' from term name and description?
(relates to previous ticket #2923)

What do you think?

**Comment by sjm41** [comment]
@phanivg I see that you originally suggested adding "triglyceride lipase activity (GO:0004806)" to these InterPro entries in  #2923 - do you still think that justified, or do you agree with my comments above?

**Comment by phanivg** [comment]
I agree with your comments @sjm41 to change the MF to 'lipase activity'.

**Comment by sarach06** [comment]
Hi,
Sorry for the late reply. Thank you very much for clarifying this. I have updated the GO terms in this entries as you stated and updated the name and description in IPR013818. The changes will be available in the next InterPro release (87.0).
Best,
Sara

**Comment by sjm41** [comment]
Great, thanks Sara.
