### ISSUE TITLE
Humans cells do not have a cell wall

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3860]
* **InterPro ID / label** IPR002152 Glycoside hydrolase, family 23

* **Example sequences with problematic annotation (ID + gene/protein name):**
* 
UniProtKB:C9J4J0 | LYG2 | involved_in | GO:0016998                cell wall macromolecule catabolic process | ECO:0000256              IEA | GO_REF:0000002 | InterPro:IPR002152 | 9606 Homo sapiens | InterPro |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB:C9JBA4 | LYG2 | involved_in | GO:0016998                cell wall macromolecule catabolic process | ECO:0000256              IEA | GO_REF:0000002 | InterPro:IPR002152 | 9606 Homo sapiens | InterPro |  
UniProtKB:Q86SG7 | LYG2 | involved_in | GO:0016998                cell wall macromolecule catabolic process | ECO:0000256              IEA | GO_REF:0000002 | InterPro:IPR002152 | 9606 Homo sapiens | InterPro |  
UniProtKB:Q8N1E2 | LYG1 | involved_in | GO:0016998                cell wall macromolecule catabolic process | ECO:0000256              IEA | GO_REF:0000002 | InterPro:IPR002152 | 9606 Homo sapiens | InterPro |  

* **Description of issue**
* Humans and other animal cells do not have a cell wall therefore these proteins should not be annotated to this term

Thanks

Ruth

**Comment by sarach06** [comment]
Hi Ryth,
Many thanks. I have removed the term. The changes will be visible in the next InterPro release (87.0).

Best,
Sara

**Comment by EBI-Hsinyu** [comment]
Hi! 
Sorry to re-open this ticket. I am not sure who to ask to. We have a new curator joining InterPro, her name is Beatriz (blp@ebi.ac.uk). Do you know anyone who can add her as a new member to The Gene Ontology Consortium in Github? Thank you for your help. 

Best Regards, 
Hsin-Yu

**Comment by pgaudet** [comment]
Thanks @EBI-Hsinyu 

I emailed Beatriz about the procedure to follow.
