### ISSUE TITLE
tRNA endonuclease-like domain superfamily (IPR011856)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3861]
* **InterPro ID / label**
tRNA endonuclease-like domain superfamily (IPR011856)

* **Description of issue**
This superfamily includes structural (non-catalytic) subunits (e.g. see the description of the child entry IPR018593) so I think the current MF of "nuclease activity (GO:0004518)" should be removed.

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have removed the term from this entry.
Best,
Sara

**Comment by sjm41** [comment]
many thanks.
