### ISSUE TITLE
JAB1/MPN/MOV34 metalloenzyme domain (IPR000555)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3862]
* **InterPro ID / label**
JAB1/MPN/MOV34 metalloenzyme domain (IPR000555)

* **Description of issue**
Current GO-MF of "metallopeptidase activity (GO:0008237)" can be improved to the child term "metal-dependent deubiquitinase activity (GO:0140492)"

**Comment by sarach06** [comment]
Hi,
Many thanks. I have changed the term for GO:0140492. It will be visible in the next InterPro release (87.0).
Best,
Sara

**Comment by sjm41** [comment]
Wonderful, thanks!

**Comment by sjm41** [comment]
Hi @sarach06 

Sorry, I was wrong about this one.  IPR000555 is also found in CSN5 (aka COPS5 / JAB1 / MOV-34), which is a metal-dependent deneddylase, rather than deubiquitinase (e.g. PMID: 31195722). So the GO MF on this entry should be reverted to the parent metallopeptidase activity (GO:0008237).

**Comment by sarach06** [comment]
Hi!
No worries, thank you very much for letting me know. I have reverted the term in this entry, which will be visible in the next InterPro release (89.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!
I think it would be correct to add the specific "metal-dependent deubiquitinase activity (GO:0140492)" term to the child InterPro entry "STAMBP/STALP-like, MPN domain (IPR044098)". What do you think?

**Comment by sjm41** [comment]
Great, thanks again.
