### ISSUE TITLE
Ribosome-binding ATPase YchF/Obg-like ATPase 1 (IPR004396)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3863]
* **InterPro ID / label**
Ribosome-binding ATPase YchF/Obg-like ATPase 1 (IPR004396)

* **Description of issue**
Would you consider adding 'GO:0016887 ATP hydrolysis activity' to this entry?  Description is "Ribosome-binding ATPase YchF is a yeast ATPase that binds to both the 70S ribosome and the 50S ribosomal subunit in a nucleotide-independent manner [1]. The mammalian homologue of YchF has been termed OLA1, for Obg-like ATPase 1 [2]. These proteins bind and hydrolyse ATP more efficiently than GTP, therefore their name. ATPase activity is a general feature of the YchF subfamily of Obg-like GTPases [2]."

**Comment by sarach06** [comment]
Hi,
Thank you very much. Yes, I have added the term to this entry and also GO:0005524 (ATP binding). Let me know if you agree.

Cheers,
Sara

**Comment by sjm41** [comment]
Looks good, thanks!
