### ISSUE TITLE
ATPase, AFG1-like (IPR005654)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3864]
* **InterPro ID / label**
ATPase, AFG1-like (IPR005654)

* **Description of issue**
Would you consider adding 'GO:0016887 ATP hydrolysis activity' to this entry?

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have added the term to this entry.

Best,
Sara

**Comment by sjm41** [comment]
Thanks!
