### ISSUE TITLE
Torsin (IPR010448)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3865]
* **InterPro ID / label**
Torsin (IPR010448)

* **Description of issue**
Would you consider adding ' GO:0016887 ATP hydrolysis activity' to this entry?
Description says "Torsins are membrane-associated ATPases. They belong to the AAA+ (ATPase associated with a variety of cellular activities) superfamily of ATPases, but they lack conserved catalytic residues typically found in related ATPases. Accordingly, Torsins do not display ATPase activity unless they are engaged by their regulatory cofactors lamina-associated polypeptide 1 (LAP1) or luminal domain-like LAP1 (LULL1)"

So maybe the GO term shouldn't be added because "Torsins do not display ATPase activity unless they are engaged by their regulatory cofactors"??  Any thoughts on this @hattrill @bmeldal ?

Couple of recent reviews:
https://www.frontiersin.org/articles/10.3389/fmolb.2017.00029/full
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4887320/

The second review explains things like this:
_Notably, however, Torsins lack the catalytic arginine residue that is otherwise conserved among AAA+ proteins, drawing into question whether Torsins are indeed active ATPases. In fact, when the first comprehensive in vitro analysis of purified Torsins and its previously identified [16] binding partners was conducted, Torsins were found to be completely inactive in isolation [4]. Addition of the LDs of LAP1 or LULL1, which are necessary and sufficient for Torsin binding, strongly induced ATP hydrolysis, with LULL1 being the more potent activator [4]. This stimulatory effect was attributable to a substantial stimulation of the ATP hydrolysis step that was reminiscent of the action of small GTPases by GAPs [21], suggesting that LAP1 and LULL1 serve similarly to regulate ATP hydrolysis [4]._

**Comment by sarach06** [comment]
Hi,
Thank you for these two articles, I added them to the abstract. From a first thought, I wouldn't add the term as Torsins need the cofactors to activate the ATPAse activity (as they complement the arginine finger required for it and absent in these proteins), but once activated they act like that. If these cases are considered in the term and wouldn't be a mapping issue just let me know and I'll add it.
Cheers,
Sara

**Comment by bmeldal** [comment]
We decided that we can annotate GP that need another GP to carry out their composite function with _contributes_to_. But I don't know how this works for InterPro annotations.

See https://github.com/geneontology/go-annotation/issues/1650

**Comment by hattrill** [comment]
By analogy to GAPs and small GTPases, I would say to annotate the cofactors with GO:0001671 'ATPase activator activity' and the torsin with GO:0016887 'ATP hydrolysis activity' as it can still do it, just very slowly (like the small GTPases).

**Comment by sarach06** [comment]
Many thanks!
Term added then. It will be visible in the next InterPro release (87.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks all!
The regular contributes_to guidelines don't quite apply here as Torsin _is_ the catalytic subunit, but it seems the cofactors effectively complement its active site with a missing arginine residue.
