### ISSUE TITLE
IPR005669 NOT ABC transporter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3866]
* **InterPro ID / label**
IPR005669 Thiosulphate/Sulfate-binding protein

* **Example sequences with problematic annotation (ID + gene/protein name):**
UniProtKB:P02906 

* **Description of issue**
IPR005669 represents sulfate/thiosulfate carriers that deliver the sulfate or thiosulfate to an ABC transporter, but they are not transporters. 
GO has a term, 'sulfur carrier activity (GO:0097163) - but that wouldn't cover thiosulfate. 

Maybe the best MF is GO:0140104 molecular carrier activity for this? 

Also, the BP could be changed to the child term  GO:1902358 sulfate transmembrane transport. 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I have deleted the term and added GO:0140104 to cover sulfate and thiosulfate. Also, I've changed the BP to the child term. These changes will be available in the next InterPro release (87.0).
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks @sarach06
