### ISSUE TITLE
Review annotations to GO:0003845 11-beta-hydroxysteroid dehydrogenase [NAD(P)] activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3869]
Genes annotated to GO:0003845 11-beta-hydroxysteroid dehydrogenase [NAD(P)] activity can be annotated to a more specific child, 
- GO:0070523 11-beta-hydroxysteroid dehydrogenase (NAD+) activity or 
-  GO:0070524 11-beta-hydroxysteroid dehydrogenase (NADP+) activity 
Please review annotations: 

https://docs.google.com/spreadsheets/d/13QQi79cO0vA8yCEj8uVsf85Dslp5ct9TkXIA0bp4RoE/edit#gid=0
- 1 UniProt DONE 
- 2 MGI
- 2 RGD
Thanks, Pascale

**Comment by pgaudet** [comment]
Also, Reactome R-HSA-194023 should be moved to GO:0070524 11-beta-hydroxysteroid dehydrogenase (NADP+) activity

@deustp01

**Comment by gthayman** [comment]
RGD done.

**Comment by hdrabkin** [comment]
MGI Done
