### ISSUE TITLE
 PTN000077911  not all  intrinsic component of mitochondrial inner membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3870]
* **PTHR ID & PTN node:**

GO:0031304 | intrinsic component of mitochondrial inner membrane | IBA with 1310543 , PTN000077911 , MGI:104968 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC146.09c  lsd1
histone demethylase SWIRM1
Q9Y802
&
https://www.pombase.org/gene/SPAC23E2.02
Lsd2

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation, MGI:104968 isn't the ortholog of  pombe Lsd1

**Comment by pgaudet** [comment]
Removed propagation.
