### ISSUE TITLE
Q15904 Not plasma membrane proton-transporting V-type ATPase complex - PTHR12471

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3875]
* **PTHR ID & PTN node:**

UniProtKB:Q15904 | ATP6AP1 | part_of | GO:0033181    plasma membrane proton-transporting V-type ATPase complex | ECO:0000318   IBA | PMID:21873635 | FB:FBgn0262515 more...

* **Sequences with problematic annotation (ID + gene/protein name):**
example
https://www.uniprot.org/uniprot/Q15904
V-type proton ATPase subunit S1
ATP6AP1

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This could be both.  There is a lot of confusing annotation for this protein, but it is an ER chaperone for the vacuolar ATPase, not part of the final complex.  

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
@sjm41 @hattrill  you might want to check this:

FlyBase
involved_in vacuolar proton-transporting V-type ATPase complex assembly	
inferred from genetic interaction with UniProtKB:Q9VHG4

**Comment by ValWood** [comment]
I mean
@sjm41 @hattrill you might want to check this:
plasma membrane proton-transporting V-type ATPase complex

**Comment by ValWood** [comment]
Actually what doe this term mean? It's only used by FlyBase, all IMP?
I don't think there are any 2 sector ATPases complexes in the plasma membrane in eukaryotes are there???

**Comment by pgaudet** [comment]
V-type ATPases are eukaryotic enzymes present in a variety of cellular membranes, including the **plasma membrane,** vacuoles, late endosomes, and trans-Golgi cisternae, see PMID:33705299

**Comment by ValWood** [comment]
For yeast, I would prefer this isn't transferred. This review cites 1 human paper. I just checked all 14 subunits at SGD, and they don't have a single annotation to plasma membrane despite decades of experiments.
There is however a Golgi variant of the complex that appears to have fewer subunits
https://www.yeastgenome.org/complex/CPX-1192

**Comment by hattrill** [comment]
Hi Val,
I've  reviewed this and removed 'plasma membrane proton-transporting V-type ATPase complex' from Q7JR49.
This was from a descrete malpighian tubule-specific PM V-ATPase complex based on a combination of expression and common phenotype. But cannot be used to say that this is part of the PM complex.

**Comment by ValWood** [comment]
In this case,  this term will have no EXP annotations. Should we obsolete this term unless there is good evidence that such a complex exists?

**Comment by hattrill** [comment]
The specific PM V-ATPase complex is thought to exist in the basal PM of tubules in D.mel and other PM-specific V-ATPase complexes  have been shown in mammal, so I would be inclined to keep it. There are many different assemblies of V-ATPase alternative subunits, so when we are able to label a descrete complex it is useful as the name "V-ATPase" is somewhat misleading.
I have only removed the annotation from the accessory subunit as the correlation between phenotype and expression is probably because of its assembly/ER role.

**Comment by ValWood** [comment]
OK so the rule is for now do not transfer to fungi, where this location has not been observed.

**Comment by hattrill** [comment]
I would say that the specific sub-type of V-ATPase might be hard to infer from sequence conservation alone as there are multiple SU isoforms and there is no way to tell what is the thing that makes one a PM V-ATPase vs other locations - so I would say don't propgate to beyond "proton-transporting V-type ATPase complex". 

Alternatively, we could just specify the subcellular location using an extension and dump the types as we only have PM and vacuolar 'types' in the GO (we could also merge V1 and VO sectors into "proton-transporting V-type ATPase complex" as this is more of a 'domain' thing?

<img width="622" alt="Screenshot 2021-09-09 at 11 01 48" src="https://user-images.githubusercontent.com/11865746/132666134-91c9e36f-fece-494f-b836-eab868c52688.png">

**Comment by hattrill** [comment]
> Note that if slightly overexpressed V-type ATPase subunits, which get to the vacuole through the ER, will end up at the plasma membrane...we see this for some subunits in our HTP localization studies where the proteins were not at endogenous levels.

These are specific PM complexes, for sure. Not obver-expression, but have physiological roles.

**Comment by ValWood** [comment]
>These are specific PM complexes, for sure. Not obver-expression, but have physiological roles.

OK,maybe they do exist in yeast, but I would like to see some evidence first.
Good plan to get rid of the V0-V1 sector...

**Comment by hattrill** [comment]
I am pretty sure I read somewhere that there are no PM V-ATPase complexes in single-celled organisms.

Happy to merge V0-V1 sector up and I think that @bmeldal suggested this before.

**Comment by bmeldal** [comment]
Re: PM location: 

Human: Review http://europepmc.org/article/MED/32001091 lists the ATP6V0A4 variant as resident in the PM. The article currently doesn't open at Elsevier but it was towards the end in the "isoform" section. -> so yes, keep the PM term if we do keep location-specific terms.

We already released the 2 S. cerevisiae complexes and they are "Golgi" and "vacuole" -types. We are currently updating their compositions, new versions will go out in our next release. -> so yes, we also didn't find PM-types in yeast.

Re: V0-V1 domains: these are indeed legacy terms and we wouldn't create new domain-type children these days. 

In fact, if we created this term now, we'd stop at "GO:0033176 proton-transporting V-type ATPase complex" as they all have the same function regardless of where in the cell they reside. 

Also, as Helen said, there are tonnes of isoforms for several SUs making location assignments potentially tricky. A separate annotation to subcellular location or an AE would work better as you can do that by experiment.

The 4 major human variants will be released in our next release.

**Comment by pgaudet** [comment]
Removed the plasma membrane annotation, I left 'V-type ATPase complex'. 

Thanks, Pascale
