### ISSUE TITLE
InterPro:IPR008388 not proton-transporting V-type ATPase, V1 domain

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3876]
* **InterPro ID / label**
InterPro:IPR008388 

* **Example sequences with problematic annotation (ID + gene/protein name):**
Q15904 |

* **Description of issue**

This is an ER/Golgi  ~resident~ protein/chaperone, it isn't part of the  V-type ATPase

UniProtKB:Q15904 | ATP6AP1 | part_of | GO:0033180    proton-transporting V-type ATPase, V1 domain | ECO:0000256   IEA | GO_REF:0000002 | InterPro:IPR008388 | 9606 Homo sapiens | InterPro |  

UniProtKB:Q15904 | ATP6AP1 | involved_in | GO:1902600    proton transmembrane transport | ECO:0000256   IEA | GO_REF:0000002 | InterPro:IPR008388 | 9606 Homo sapiens | InterPro

**Comment by sarach06** [comment]
Dear Val,
Thank you very much. I have removed the terms from this entry. The changes will be visible in the next InterPro release (87.0).

Best regards,
Sara

**Comment by sjm41** [comment]
Hi @sarach06
Will you also be changing the name ("ATPase, V1 complex, subunit S1") and definition (which talks a lot about V-ATPases) of IPR008388?

**Comment by sarach06** [comment]
Hi,
Yes, I changed the name to "V0 complex accessory subunit Ac45" (based on this recent article PMID: 33065002) and I left a brief description of V-ATPases apart from the specific description for this subunit. Do you think this is clear enough? Let me know if you have any suggestions.
Best
Sara

**Comment by ValWood** [comment]
Note, I edited above. I think  I read this is ER and Golgi (but not late Golgi).
@sarach06 I also sent an update to Pfam (for description and family), so you might want to coordinate here.
v

**Comment by sarach06** [comment]
Hi Val, 
Yes, thank you very much. I'm working on that too, I'll let you know the changes I'm doing when finished.
Best,
Sara

**Comment by sjm41** [comment]
Hi @sarach06 - the new name and changed description look good to me, thanks.

**Comment by ValWood** [comment]
@Antonialock pointed out that this  isn't correct.

There is some cleavage event and the N-term part remains in the membrane but the (C terminal does end up in the final V-type ATPase 

https://pubmed.ncbi.nlm.nih.gov/29526695/
Maybe these domains could be separated?

**Comment by ValWood** [comment]
It seems that a new family was created as this member is now IPR037654
