### ISSUE TITLE
PTN001999053, query fungal-type cell wall biogenesis and protein N-linked glycosylation , protein O-linked mannosylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3877]
* **PTHR ID & PTN node:**

GO:0009272 | fungal-type cell wall biogenesis | IBA with PTN001999053 , S000004813 | Gaudet P et al. (2011) | 57
- | GO:0006487 | protein N-linked glycosylation | IBA with PTN001999053 , S000004813 | Gaudet P et al. (2011) | 57
- | GO:0035269 | protein O-linked mannosylation | IBA with PTN001999053 , S000004813

* **Sequences with problematic annotation (ID + gene/protein name):**

For example:
pombase.org/gene/SPAC31G5.02  
O14103

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Depends partly on the outcome of 
https://github.com/geneontology/go-ontology/issues/22008

but I would not annotated ER chaperones to glycosylation, or cell wall biogenesis?

**Comment by marcfeuermann** [comment]
Fixed.
