### ISSUE TITLE
Review annotations to GO:0070827 chromatin maintenance & GO:0070829 heterochromatin maintenance.

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3878]
Dear all, 

The proposal has been made to obsolete GO:0070827 chromatin maintenance & GO:0070829 heterochromatin maintenance, see https://github.com/geneontology/go-ontology/issues/22013

Annotations are here: https://docs.google.com/spreadsheets/d/1Iz2cNS7lBIT9XLv5r7k6Cq3DfmVt5Jwi7BjQ8_9RmNE/edit#gid=0

Contributor | (Assigned by) |  Status
--| --|--
BHF-UCL | 3 | Fixed
FlyBase | 2 | Fixed
GeneDB | 5 | Fixed
MGI | 3 | Fixed
PomBase | 2 | Fixed
SGD | 6 | Fixed
UniProt | 5 | Fixed

Suggestions have been made for reannotation. 

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by hattrill** [comment]
FB done
