### ISSUE TITLE
Is prefoldin really a transcription regulator, or is this indirect?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3880]
* **PTHR ID & PTN node:**

GO:0006355 | regulation of transcription, DNA-templated | IBA with Q99471 , S000004559 , PTN000975547

@colinlog 
@Antonialock 
@RLovering 
@pgaudet

**Comment by ValWood** [comment]
OK, 
https://www.yeastgenome.org/reference/S000155330
I just want to check if this is current thinking. The human stuff seems to be quite different

https://www.uniprot.org/uniprot/Q99471
it is annotated as 
a) transcription corepressor activity Source: ProtInc
and 
b) negative regulation of transcription, DNA-templated

**Comment by Antonialock** [comment]
Is this helpful?

2020 paper PMID: 32396196 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7293050/

Although there is no indication about the DNA binding ability of PFDs, they participate in the regulation of gene targets in the context of the chromatin. For instance, chromatin immunoprecipitation assays showed that human prefoldin 1 (PFDN1) binds to the transcription start site of the Cyclin A gene to repress its expression (3). 

We have a better understanding about the mechanism of PFDN5/MM-1 in transcriptional regulation. This PFD regulates c-Myc activity, acting as a bridge protein that recruits a transcriptional co-repressor, TIF1β/KAP1, and the HDAC1 histone deacetylase complex directly to the c-Myc-bound genomic targets to repress their expression (4,5).

**Comment by ValWood** [comment]
This is the cyclin paper (2017)
https://pubmed.ncbi.nlm.nih.gov/27694898/
and the c-Myc paper (1998)
https://pubmed.ncbi.nlm.nih.gov/11585818/

**Comment by ValWood** [comment]
@colinlog  is the data strong enough for co-repressor?
And/or for annotations transfer by PAINT?

**Comment by pgaudet** [comment]
See also #3880

**Comment by pgaudet** [comment]
After discussion with @colinlog we annotated to RNA pol I, II and III complex assembly.

**Comment by ValWood** [comment]
sounds good.
Note to self, remove filter on PTHR12674
