### ISSUE TITLE
Review annotations to GO:0031938 regulation of chromatin silencing at telomere & GO:1905547 regulation of subtelomeric heterochromatin assembly & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3882]
Hello, 

The proposal has been made to obsolete 
* GO:0031938 regulation of chromatin silencing at telomere
* GO:0031939 negative regulation of chromatin silencing at telomere
*  GO:0031940 positive regulation of chromatin silencing at telomere
* GO:1905547 regulation of subtelomeric heterochromatin assembly
* GO:1905548 negative regulation of subtelomeric heterochromatin assembly
* GO:1905549 positive regulation of subtelomeric heterochromatin assembly
see https://github.com/geneontology/go-ontology/issues/22027

Annotations are here: https://docs.google.com/spreadsheets/d/16NWloMDnpze_fWfjUzTyDKfxdwGdhVdwtnUxA-OvgsY/edit#gid=569711590

* 2 FB
* 45 SGD to review. 
Suggestions for reannotation have been made on the spreadsheet. 

Thanks, Pascale

**Comment by hattrill** [comment]
FB done
