### ISSUE TITLE
Review annotations to 'GO:0034401 chromatin organization involved in regulation of transcription' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3883]
Hello, 

 'GO:0034401 chromatin organization involved in regulation of transcription'  will be obsoleted, see https://github.com/geneontology/go-ontology/issues/22041

There are 3 EXP annotations, by BHF and EcoCyc. Suggestions for corrections have been made here: https://docs.google.com/spreadsheets/d/1ae52ndE9nBKm9ReF-wVTMlefwzVT-unr_TXG8XjCqd0/edit#gid=0

Thanks, Pascale

**Comment by RLovering** [comment]
done
