### ISSUE TITLE
Review annotations to GO:0070868 heterochromatin organization involved in chromatin silencing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3884]
Hello, 

The proposal has been made to obsolete GO:0070868 heterochromatin organization involved in chromatin silencing, see https://github.com/geneontology/go-ontology/issues/22046

There are 42 EXP annotations - by FlyBase and SGD (+ 1 UniProt, disputed in P2GO). Suggestions for reannotation are here: 

https://docs.google.com/spreadsheets/d/1kpdxYHpC8taX_ZlbKaTCzZa73YmHXYRDoFQn84qwYXw/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
Thanks!
