### ISSUE TITLE
Review annotations to GO:0016569 covalent chromatin modification

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3886]
Hi, 

The proposal has been made to obsolete GO:0016569 covalent chromatin modification, see
https://github.com/geneontology/go-ontology/issues/22062

There are 7 annotations - 
https://docs.google.com/spreadsheets/d/1KHk5kwgKN1un2FIWKOCvhSwNQGGDHgb8IWG5lsoc7u0/edit#gid=0

ComplexPortal	2	
MGI	1
SGD	2	
UniProt	2

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by bmeldal** [comment]
CP done (there were 12 entries ;-) )

**Comment by pgaudet** [comment]
One remaining annotation to correct, that I wanted to check with @colinlog 
<google-sheets-html-origin><style type="text/css"></style>

UniProtKB:O14646 | Chromodomain-helicase-DNA-binding protein 1 |   PMID:28866611

Can we replace the annotation from this paper by heterochromatin assembly? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Was changed to chromatin remodeling
