### ISSUE TITLE
PTN000468320 not | chromatin-mediated  maintenance of transcription (Transcription elongation factor 1 )  - PTHR20934

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3888]
* **PTHR ID & PTN node:**
PTN000468320

* **Sequences with problematic annotation (ID + gene/protein name):**

  | GO:0048096 | chromatin-mediated  maintenance of transcription | IBA                with    S000001643       PTN000468320

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Looks like it should be
co-transcriptional chromatin reassembly (GO:0140673) 

~although I'm confused because GO:0140673 has the parent
" transcription elongation from RNA polymerase II promoter"
I thought this term was for the maintenence of promoter configuration?~

Scub this part . Here I am querying the elongation factor annotated to the 'promoter configuration term

@pgaudet 
@colinlog

**Comment by pgaudet** [comment]
Hi @ValWood 
I removed the annotation to 'chromatin-mediated maintenance of transcription' - however in the paper cited by SGD to make this annotation (to ELF1, S000001643), PMID:16260625, the authors state, "Analysis of elf1Delta mutants suggests a role for this factor in maintaining proper chromatin structure in regions of active transcription.", and mention a role in "chromatin-mediated transcription elongation" 

Does this fit better 
- 'chromatin-mediated maintenance of transcription': Maintenance of transcription by remodelling of chromatin into an 'open configuration'. Once established, this regulation is mitotically stable and is maintained over many cell divisions. It is also heritable.
- or
- 'co-transcriptional chromatin reassembly': The reestablishment of chromatin structure that was disrupted upon passage of RNA polymerase II during transcription elongation. This process prevents cryptic intragenic transcription initiation.

I am not which which evidence we would need to justify an annotation to one or the other term. 

Also should we add the synonym 'chromatin-mediated transcription elongation' to one of these? 

@colinlog 

Thanks, Pascale

**Comment by ValWood** [comment]
Doesn't 
'chromatin-mediated maintenance of transcription': Maintenance of transcription by remodelling of chromatin into an 'open configuration'. Once established, this regulation is mitotically stable and is maintained over many cell divisions. It is also heritable.

refer to maintaining an open configuration at the promoter?
Should the def say this? This isn't elongation associated is it @colinlog 

I thought
'co-transcriptional chromatin reassembly':
was the term to use for the  chromatin process associated with elongation.

**Comment by pgaudet** [comment]
Dealt with the def in https://github.com/geneontology/go-ontology/issues/22012
