### ISSUE TITLE
GO:0034622	 cellular protein-containing complex assembly IBA with PTN002933666 , S000000285

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3889]
* **PTHR ID & PTN node:**
 PTN002933666
* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC25H2.11c
(I'm guessing  here that the complex referred to is SAGA and spt7 is a SGAS complex member)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source  
* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed.
