### ISSUE TITLE
Pbxip1 is not a DNA binding transcription factor

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#3891]
Hi

Our list of DNA-binding transcription factors is about to be published. The reviewers have asked us to comment on whether a specific filter in AmiGO or QucikGO will download this list. Currently there are a few MGI annotations that mean that applying the GO:0003700 filter will lead to several non-dbTF proteins being downloaded. One of these is Pbxip1. 

I have just looked at the article supporting the dbTF annotation associated with Pbxip1 PMID: 30659184 https://pubmed.ncbi.nlm.nih.gov/30659184/ and the evidence does not support this annotation.

In the results section the authors state:
1. The findings above have shown that H3K56ac was involved in gene expression and there were enhanced H3K56ac around HPIP DNA-binding regions. 
2. Taken together, these data demonstrate that HPIP directly activates expression of key Wnt signaling pathway targets by acetylating H3K56ac in their promoters.

In the discussion the authors state: 
1. In this study, we found that HPIP deficiency in OA chondrocytes impaired Wnt signaling. Subsequent analysis demonstrates that HPIP exerts its biological function mainly through interactions with transcriptional factors (LEF1) to activate Wnt signaling. LEF1 is a sequence-specific DNA-binding protein which is expressed in adult mice pre-B and T lymphocytes and in the mesencephalon, neural crest, whisker follicles, tooth germs, and other sites during the progression of embryogenesis.
2. Mechanistically, we showed that HPIP physically interacts with LEF1 to promote transcription of Wnt target genes. HPIP potentiates LEF1 transcriptional activity and acetylates H3K56ac around Wnt signaling target gene promoters.

Thus the paper does not demonstrate DNA binding but the results text does imply DNA binding. 

Please revise these annotations to reflect the author intent, ie change the dbTF annotations to coTF annotations. In addition I do not think they demonstrate that this coTF has acetylase activity either. Potentially you could use a dbTF binding term instead of some of the protein binding terms used.

Thanks

Ruth

**Comment by LiNiMGI** [comment]
Changed to GO:0003713 transcription coactivator activity in MGI.  Thanks, Li

**Comment by RLovering** [comment]
Thanks ;)
