### ISSUE TITLE
InterPro:IPR000836    (not all nucleoside)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3892]
* **InterPro ID / label**
InterPro:IPR000836

* **Example sequences with problematic annotation (ID + gene/protein name):**
see below

* **Description of issue**

nucleoside metabolic process (GO:0009116)

Some are nucleotide metabolism

For example
https://www.pombase.org/gene/SPAC1399.04c uracil phosphoribosyltransferase Uck2

https://www.pombase.org/gene/SPBC3D6.06c ribose-phosphate pyrophosphokinase Prs5 (predicted)

And nucleobase
For example
https://www.pombase.org/gene/SPBC3D6.06c uracil phosphoribosyltransferase (predicted)

**Comment by EBI-Hsinyu** [comment]
Hi Val, 
Thank you for this. I have removed the term. This will be visible in InterPro87.0.
Hsin-Yu
