### ISSUE TITLE
PTN000048698 GO:0006266 | DNA ligation | 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3894]
* **PTHR ID & PTN node:**

GO:0006266 | DNA ligation | IBA with PTN000048698 , 1304639 , MGI:1335098 , P49917 , S000005531 , locus:2175544

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I just wanted to report that I am filtering this mapping for PomBase  because it is a MF  not a BP
@pgaudet  do we want a GO ticket for this?

**Comment by pgaudet** [comment]
Not sure - we know we need to do these, but I dont think we can tackle this right now?

**Comment by ValWood** [comment]
OK I can just filter the mapping, I just wanted to report as once it is gone from PomBase I won't pick it up again.

**Comment by marcfeuermann** [comment]
To close the ticket I've removed the propagation.
