### ISSUE TITLE
IPR023210 query about D-threo-aldose 1-dehydrogenase activity (GO:0047834)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3902]
https://www.pombase.org/results/from/id/aa776c7b-4648-42bf-93ba-188370b8815b

I am picking up 14 mappings to this term
https://www.pombase.org/results/from/id/aa776c7b-4648-42bf-93ba-188370b8815b

<img width="930" alt="Screenshot 2021-09-03 at 08 46 43" src="https://user-images.githubusercontent.com/7359272/131969813-a170edc9-dc9e-4912-8eb7-80c6b07c5425.png">

https://www.pombase.org/term_genes/GO:0047834

but many have other annotation like 

alditol:NADP+ 1-oxidoreductase activity
pyridoxine:NADP 4-dehydrogenase activity

are these all 
D-threo-aldose 1-dehydrogenase activities?
This term has no children, no Add EC or Rhea,

**Comment by ValWood** [comment]
Thanks @hdrabkin I transferred to the annotation tracker. Just wanted to check first that I wasn't missing something obvious. I will remove you.
v

**Comment by hdrabkin** [comment]
Also forgot 'lso, aldose is a sugar, alditol is sugar alcohol, pyridoxine is an aromatic compound - should they really be related?"
The relationship is that they are all types of enzymes EC:1.1.1 that are oxidoreductase using NAD(P).
