### ISSUE TITLE
IPR000330 NOT nucleosome-dependent ATPase activity (GO:0070615)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3920]
* **InterPro ID / label**
IPR000330
* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**
Hi, 

The description of this family implicates many different MF; I dont think a MF can be assigned (and certainly not 'nucleosome-dependent ATPase activity (GO:0070615)', which is very specific. 

Thanks , Pascale

**Comment by ValWood** [comment]
All of these  do seem to be 
ATP-dependent chromatin remodeler
at least for pombe?

To me all 
ATP-dependent chromatin remodeler are 'nuclease dependent' 
do we even need this term they seem to be equivalent to me?
@colinlog

**Comment by ValWood** [comment]
i.e.
20 ATP-dependent chromatin remodeler activity (GO:0140658)
plus
subset: IPR000330
<img width="981" alt="Screenshot 2021-09-11 at 07 34 22" src="https://user-images.githubusercontent.com/7359272/132938936-f4b27bfd-dd46-474b-bd03-bb0d4b36f16a.png">

20 ATP-dependent chromatin remodeler activity (GO:0140658)
https://www.pombase.org/results/from/id/932bc8e0-f8c0-4172-a26b-57f3bb92f260

subset: IPR000330 (20)
https://www.pombase.org/results/from/id/3c4b2abb-2e4f-48fa-8ab6-5d0a1c325d28


 
 
  

https://www.pombase.org/results/from/id/77d3c80c-b796-4446-8092-917bd1b4594d

**Comment by pgaudet** [comment]
The description states "This domain is found in proteins involved in a variety of processes including transcription regulation (e.g., SNF2, STH1, brahma, MOT1), DNA repair (e.g., ERCC6, RAD16, RAD5), DNA recombination (e.g., RAD54), and chromatin unwinding (e.g., ISWI) as well as a variety of other proteins with little functional information (e.g., lodestar, ETL1)" 


Are all these chromatin remodelers? I didn't think so, but I may be mistaken.

**Comment by ValWood** [comment]
I think they are all in the list we were looking at with @colinlog  when discussing the sub-types:
![Uploading Screenshot 2021-09-10 at 16.00.12.png…]()

certainly SNF2, ERCC6, RAD16, RAD54, ISWI

I am assuming that STH1, brahma, MOT1  lodestar, ETL1 are related

**Comment by pgaudet** [comment]
OK - no action needed then. Thanks for the feedback.

**Comment by ValWood** [comment]
@pgaudet  is there a ticket to do something with 
nucleosome-dependent ATPase activity (GO:0070615)
?
