### ISSUE TITLE
Review annotations to methotrexate terms 

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-annotation#3922]
Obsolete: methotrexate terms #21998 

Dear all,

The proposal has been made to obsolete all of the methotrexate terms, see geneontology/go-ontology#21998

Please review your annotations:
https://docs.google.com/spreadsheets/d/1jnr6pFzq9r5UADhZyZOM-1DCRQ-7ziQ3bdfGE--r4lo/edit#gid=0

Group | # 
-- | --
ARUK-UCL | 6
BHF-UCL | 8
CAFA | 1
GeneDB | 1
RGD | 13
UniProt | 10

Thanks, Karen

**Comment by slaulederkind** [comment]
All RGD annotations fixed or removed.

**Comment by RLovering** [comment]
UCL fixed

**Comment by Antonialock** [comment]
I think all the Uniprot ones are SWIS, I don't have permission for those - I take it I only update SWIE? @pgaudet
