### ISSUE TITLE
Isocitrate dehydrogenase NAD-dependent (IPR004434)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3928]
* **InterPro ID / label**
Isocitrate dehydrogenase NAD-dependent (IPR004434)

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly Idh3b (Q9VD58) / human IDH3B (O43837)
fly CG5028 (Q8MT18) / human IDH3G (P51553)

* **Description of issue**
IPR004434 is associated with "isocitrate dehydrogenase (NAD+) activity (GO:0004449)"
Problem is that this domain is found in non-catalytic subunits (in addition to the catalytic subunit) of the multisubunit isocitrate dehydrogenase complex - see example sequences above.

So I think "isocitrate dehydrogenase (NAD+) activity (GO:0004449)" should be removed.

**Comment by sjm41** [comment]
Similar issue for "Isopropylmalate dehydrogenase-like domain IPR024084", which is associated with "oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616)".

This domain is also found in non-catalytic subunits of the multisubunit isocitrate dehydrogenase complex (e.g. human IDH3G (P51553)) , and so I think the GO term should also be removed from this one.

**Comment by sarach06** [comment]
Hi Steven,
Yes, I agree. The terms were removed from the entries you mentioned. The changes will be available in release InterPro 88.0.
Cheers,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
