### ISSUE TITLE
Su(var)3-7 (P20193) & Glycerol-3-phosphate dehydrogenase, NAD-dependent (IPR006168)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3930]
* **InterPro ID / label**
Glycerol-3-phosphate dehydrogenase, NAD-dependent (IPR006168)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Su(var)3-7 (P20193) 

* **Description of issue**
I'm trying to figure out how/why P20193 is associated with IPR006168 (which comes from PTHR11728) and has the InterPro2GO of "glycerol-3-phosphate dehydrogenase [NAD+] activity (GO:0004367)"
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR006168/
https://www.ebi.ac.uk/interpro/protein/reviewed/P20193/

As documented in #2112, Su(var)3-7 (P20193) is not a glycerol-3-phosphate dehydrogenase, and @pgaudet fixed the related PTN000919759 issue in that ticket.  Do we just need to wait for that fix to filter through to IPR006168, or maybe something still needs fixing at the PANTHER side?:
http://www.pantherdb.org/genes/geneList.do?searchType=basic&loggedPrivilege=false&fieldName=all&fieldValue=PTHR11728*&listType=1&organism=Drosophila%20melanogaster

Any insights?

@pgaudet 
@hattrill

**Comment by sarach06** [comment]
Hi!
In this case, to fix this from InterPro, I unintegrated the Panther signature from this entry as this match is an overhit and then, this will stop the association. It will need then to be fixed at the Panther side.
Best,
Sara

**Comment by pgaudet** [comment]
@sjm41 I dont think this was a Panther issue; looked like this was an incorrect assignment from InterPro, which is now corrected. Please reopen if you still see issues. 

Thanks, Pascale

**Comment by sjm41** [comment]
OK, thanks both.
