### ISSUE TITLE
Upstream EcoCyc GAF contains unsupported qualifiers

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#3934]
The EcoCyc GAF currently contains lines like: 

`UniProtKB       P0AFD6  nuoI    Contributes_to  GO:0003954      PMID:3122832    IDA             F                       gene    taxon:83333     20080722        EcoliWiki`

"Contributes_to" is not an allowed qualifier.

**Comment by kltm** [comment]
Tagging @vanaukenk @pgaudet

**Comment by kltm** [comment]
Upstream: https://ecoliwiki.org/gaf/gene_association.ecocyc.gz

**Comment by kltm** [comment]
Noting that this currently causes a crash in the pipeline, so we are trying to fix at that end as well.
Tagging @dustine32

**Comment by kltm** [comment]
Noting https://github.com/biolink/ontobio/issues/591

**Comment by vanaukenk** [comment]
@dsiegele Would it be possible to change the upper case 'C' in 'Contributes_to' to a lower case c, i.e. 'contributes_to', in the EcoCyc GAF?  

Thank you!

**Comment by dsiegele** [comment]
I fixed the EcoCyc GAF and replaced 'Contributes_to' with 'contributes_to' with a lower case 'c.'

**Comment by kltm** [comment]
@dsiegele Great, thank you!
