### ISSUE TITLE
Review RHB1 S000000622 annotations to 'transport'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3941]
These seem indirect: 
GO:0015809	arginine transport	IMP	PMID:10753927	20011023
GO:0015809	arginine transport	IGI	PMID:10753927	20011023
GO:0015819	lysine transport	IMP	PMID:10753927	20011023

Maybe add 'acts upstream of'? or 'acts upstream of or within'
? 

Thanks, Pascale

**Comment by srengel** [comment]
this ticket escaped me.  looking now i think these should probably be 'regulation of'...

**Comment by pgaudet** [comment]
The authors write in the discussion, "The mechanism for Can1p regulation by ScRheb needs to be investigated further. One possible mechanism is through the regulation of CAN1 gene expression." so, the evidence seems rather weak to call this regulation?

**Comment by srengel** [comment]
deleted the annotations.  closing.
