### ISSUE TITLE
UniProtKB:P38935 not translation (unsupported annotation)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3944]
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P38935

has conflicting annnotations to DNA replication and  translation (NAS)

@Antonialock  do you have permission to update?
@pgaudet  noticed in 'new slim' matrix [1 annotation in intersection]

**Comment by Antonialock** [comment]
try this one:
https://academic.oup.com/hmg/article/18/7/1288/674737
IGHMBP2 is a ribosome-associated helicase inactive in the neuromuscular disorder distal SMA type 1 (DSMA1)

**Comment by Antonialock** [comment]
will be annotated to BPs  RNA secondary structure unwinding and DNA duplex unwinding, removed other bps,
19158098, 30218034

**Comment by ValWood** [comment]
Those terms sound like MF terms in the BP ontology and so will be obsoleted in the medium term. What is the actual process?  e.g. RNA processing?

**Comment by Antonialock** [comment]
Well they will slim to chromosome organization and RNA metabolic process? They can move up once / if they get obsoleted?

**Comment by ValWood** [comment]
@pgaudet a good case for prioritising the obsoletions sooner.
Or at least block these terms for further annotation.

Antonia, the problem is  that  these cannot usually be merged as 
i) often the annotations are very heterogeneous and need checking for more specific annotation options. Pascale is reviewing most of them which makes this very time consuming. 
ii) Merges are not  favoured, because the terms are often used by other ontologies for logical definitions and the meaning is not *exact*. 
Another round of work is required  to fix things later (usually involving looking at the papers again).

**Comment by Antonialock** [comment]
hmm....I'll believe you, it just seemed to make sense that if something is involved in unwinding a duplex, then it is involved in the metabolism of said duplex
