### ISSUE TITLE
Fly examples of PAINT/NOT annotation conflicts

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3947]
Hi @pgaudet, @marcfeuermann, @thomaspd, @huaiyumi, (also tagging @hattrill)

As suggested during the GO mtg earlier this week, I'm listing below the examples I have of Drosophila enzymes with a NOT annotation (using IKR) that are currently also getting a positive annotation via PAINT.  As mentioned, I'm not sure if these are 'fly oddballs' or represent changes that could/should be made on the PAINT/Panther nodes.  You'll probably want separate tickets if they are fixable, but I'll list them all here for now.

Also see #3546, #3701, #3304.

**Yp1 (FBgn0004045), Yp2 (FBgn0005391), Yp3 (FBgn0004047), CG10116 (FBgn0036367), CG14034 (FBgn0250847)**
PTN000176726 (PTHR11610) adds "lipase activity" despite NOT (IKR) annotation to same term

**CG18853 (FBgn0042173/A1Z758)**
PTN000025285 (PTHR10211) adds "deoxyribodipyrimidine photo-lyase activity" despite NOT (IKR) annotation to same term

**CG32318 (FBgn0052318/Q7KVC2)**
PTN000648413 (PTHR24115) adds "microtubule motor activity" and PTN001189922 (PTHR24115) adds "plus-end-directed microtubule motor activity" despite NOT (IKR) annotation to "microtubule motor activity"

**LBR (FBgn0034657/Q8MLV1)**
PTN000479179 (PTHR21257) adds "oxidoreductase activity, acting on the CH-CH group of donors" but there's a NOT (IGI) annotation to child term (delta14-sterol reductase activity)
-> different terms, so maybe nothing to be done here?

**CG1271 (FBgn0035392/Q9VZV9), CG8298 (FBgn0033673/Q7JY99)**
PTN000023394 (PTHR10196) adds "glycerol kinase activity" despite NOT (IKR) annotation to same term

**Argp (FBgn0051469/Q8ING6)**
PTN000197212 (PTHR11717) adds "protein tyrosine phosphatase activity" despite NOT (IKR) annotation to the same term

**CG7573 (FBgn0036153)**
PTN000012712 (PTHR10120) adds "metalloendopeptidase activity" despite NOT (IKR) to same term 

**Ance-2 (FBgn0032535), Ance-3 (FBgn0032536), Ance-4 (FBgn0033366), Ance-5 (FBgn0035076)**
PTN000828236 (PTHR10514) add "metallopeptidase activity" despite NOT (IKR) to same term

**frma (FBgn0029769), goe (FBgn0027528), Nepl10 (FBgn0033742), Nepl11 (FBgn0037230), Nepl12 (FBgn0037727), Nepl13 (FBgn0039022), Nepl14 (FBgn0039023), Nepl15 (FBgn0039024), Nepl16 (FBgn0039277), Nepl17 (FBgn0039609), Nepl18 (FBgn0039611), Nepl19 (FBgn0039612), Nepl20 (FBgn0039613), Nepl21 (FBgn0027578), Nepl4 (FBgn0031805), Nepl5 (FBgn0031808), Nepl6 (FBgn0259716), Nepl7 (FBgn0032442), Nepl8 (FBgn0032585), Nepl9 (FBgn0032613)**
PTN000199753 (PTHR11733) adds "metalloendopeptidase activity" despite NOT (IKR) to same term 

**aqrs (FBgn0039598), CG14990 (FBgn0035496), CG18557 (FBgn0031470), CG18563 (FBgn0032639), CG3117 (FBgn0031471), CG31266 (FBgn0051266), CG33127 (FBgn0053127), CG33225 (FBgn0053225), CG40160 (FBgn0058160), CG4477 (FBgn0035971), CG4793 (FBgn0028514), CG5390 (FBgn0032213), CG8586 (FBgn0033320), CG8738 (FBgn0033321), CG9673 (FBgn0030775), SPH93 (FBgn0032638)**
PTN001207268 (PTHR24256) adds "serine-type endopeptidase activity" despite NOT (IKR) to same term

**CG17242 (FBgn0250841), CG31267 (FBgn0051267), CG32833 (FBgn0052833), CG32834 (FBgn0052834), CG34129 (FBgn0083965), CG34130 (FBgn0083966), CG34295 (FBgn0085324), CG4271 (FBgn0031409), CG4653 (FBgn0030776), CG9897 (FBgn0034807), intr (FBgn0039599), kappaTry (FBgn0043471), sphe (FBgn0030774)**
PTN001208729 (PTHR24276) adds "serine-type endopeptidase activity" despite NOT (IKR) to same term

**Comment by hattrill** [comment]
Can we bump this up the priority list? Been open for a while.

**Comment by pgaudet** [comment]
Thanks @hattrill 

I've put this on the agenda for our next PAINT call, scheduled for next Tuesday. 

Thanks, Pascale

**Comment by huaiyumi** [comment]
All of them have been reviewed and corrected in PAINT back in November. A few positive IBAs were allowed if the IKR evidence was weak. The Amigo should have the correct data now.

**Comment by hattrill** [comment]
@marcfeuermann Do you have a list of the positive IBAs you've allowed?
I opened a ticket for LBR PTN000479179 #4034 ticket yesterday which is on the list above, as it conflicts with our enzyme resource.

**Comment by sjm41** [comment]
Thanks @huaiyumi!
I just checked through all the examples in the Protein2GO tool from my original post - all appear to be fixed except for these four:

**Yp1 (FBgn0004045), Yp2 (FBgn0005391), Yp3 (FBgn0004047), CG10116 (FBgn0036367), CG14034 (FBgn0250847)
PTN000176726 (PTHR11610) adds "lipase activity" despite NOT (IKR) annotation to same term**
=> fixed for all except Yp1 (FBgn0004045/P02843)
=> do we need to manually exclude propagation to Yp1?

**CG32318 (FBgn0052318/Q7KVC2)
PTN000648413 (PTHR24115) adds "microtubule motor activity" and PTN001189922 (PTHR24115) adds "plus-end-directed microtubule motor activity" despite NOT (IKR) annotation to "microtubule motor activity"**
=> not fixed

**LBR (FBgn0034657/Q8MLV1)
PTN000479179 (PTHR21257) adds "oxidoreductase activity, acting on the CH-CH group of donors" but there's a NOT (IGI) annotation to child term (delta14-sterol reductase activity)**
=> not fixed

**CG1271 (FBgn0035392/Q9VZV9), CG8298 (FBgn0033673/Q7JY99)
PTN000023394 (PTHR10196) adds "glycerol kinase activity" despite NOT (IKR) annotation to same term**
=> fixed, but I see that PTN000023213 adds "phosphotransferase activity, alcohol group as acceptor" (which is a parent of "glycerol kinase activity") to these two cases, which is also wrong.

**Comment by huaiyumi** [comment]
They were missed in our initial review for various reasons. The are fixed in PAINT, and should be in GO database in the next release.

**Comment by marcfeuermann** [comment]
It seems that the 4 remaining have been done. I've checked LBR to address issue 4049. There were still some additional terms to modify. I will go through the others and close the ticket once done.

**Comment by sjm41** [comment]
Hi @marc @huaiyumi 
I just checked the 4 outstanding cases I mentioned above in the P2GO tool, and all the reported issues do now seem to be resolved.  Thanks a lot!  Shall we close this ticket now?

Whilst checking, I did notice two new issues with a couple of the mentioned genes - I'll list them below, but I suggest I make separate tickets for the two cases below - sound OK? :

**1. CG1271 (FBgn0035392/Q9VZV9)**
PTN007425640 (PTHR10196) adds "phosphotransferase activity, alcohol group as acceptor" despite NOT (IKR) annotation to parent term "transferase activity" (though this NOT annotation was only recently changed to this top-level term)

**2. CG32318 (FBgn0052318/Q7KVC2)**
PTN000648413 (PTHR24115) adds "ATP hydrolysis activity" despite NOT (IKR) annotation to same term

**Comment by marcfeuermann** [comment]
Hi @sjm41,
Thanks for your message. My bad, I should have handled this already, Yes I think it would be nice to follow your suggestion. I'm closing this one now and you can create 2 new tickets. It will be easier to handle them one by one.
Again, thank you very much or your great efforts in helping us to improve our annotation.
All the best.
Marc.

**Comment by sjm41** [comment]
@marcfeuermann 
Some of the problematic nodes mentioned (and previously fixed) in this ticket appear to have resurfaced:

These have "serine-type endopeptidase activity PTN001207268" despite "NOT enables peptidase activity IKR":
- CG8586 (FBgn0033320/A1Z7H7)
- CG8738 (FBgn0033321/A1Z7H8)

These have "metalloendopeptidase activity PTN000199753" despite "NOT enables peptidase activity IKR":
- Nepl3 (FBgn0031678/Q9VMU6)
- goe (FBgn0027528/Q9XZ14)
- Nepl9 (FBgn0032613/Q9VJH0)

These have "serine-type endopeptidase activity PTN001208729" despite  "NOT enables peptidase activity	IKR":
- CG9672 (FBgn0030777/Q9VXC5)
- CG4271 (FBgn0031409/Q9VQA4)
- CG9997 (FBgn0039597/Q9VAT8)
- aqrs (FBgn0039598/Q9VAT7)
- intr (FBgn0039599/Q9VAT6)
- CG34295 (FBgn0085324/A8JRF1)

**Comment by sjm41** [comment]
Hi @marcfeuermann Thanks for fixing all my recent PAINT tickets.  Just letting you know this is the final one that is open, in case you missed it. Steven.

**Comment by sjm41** [comment]
_All corrected._ 
Great, thanks a lot Marc! Much appreciated.

 _I hope all this remains stable from now on. We will see at the next yearly PANTHER release if it is the case._
Yep. Ideally, we'd check this (and similar test cases where previously fixed cases have returned) prior to making the public PAINT updates next time!!

**Comment by sjm41** [comment]
Hi @marcfeuermann, sorry to re-open this one again...but I noticed that two of the genes/proteins I listed in https://github.com/geneontology/go-annotation/issues/3947#issuecomment-1442993379 are still getting "serine-type endopeptidase activity" via PTN001208729 despite having "NOT enables peptidase activity IKR":
intr (FBgn0039599/Q9VAT6)
CG34295 (FBgn0085324/A8JRF1)

Can you check those two instances again please?

**Comment by marcfeuermann** [comment]
I made the corrections. Let me close it again... let's see how long it will stay closed... ;-)
