### ISSUE TITLE
Toll/interleukin-1 receptor homology (TIR) domain (IPR000157)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3951]
* **InterPro ID / label**
Toll/interleukin-1 receptor homology (TIR) domain (IPR000157)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Dmel Toll (FBgn0262473/P08953)
Human TLR1 (Q15399)

* **Description of issue**
IPR000157 is currently associated with NAD+ nucleosidase activity (GO:0003953), I think based on PMID: 29395922.  But looks like that paper only shows that activity for prokaryotic enzymes (reflecting the 'primordial function' of this domain).  I don't think there's evidence for the eukaryotic proteins with this domain having that enzymatic activity, is there?

**Comment by sjm41** [comment]
Hi Sara

The reference you give for human SARM1 references another paper for showing the NAD+ nucleosidase activity - PMID: 28334607.  From the abstract of that paper: "Here, in a series of experiments using purified proteins from mammalian cells, bacteria, and a cell-free protein translation system, we show that the SARM1-TIR domain itself has intrinsic NADase activity – cleaving NAD+ into ADP Ribose (ADPR), cyclic ADPR, and Nicotinamide".  So, it's clear that SARM1 does have this activity.

But that same paper also contains this paragraph:
_We next asked if this enzymatic activity was unique to complexes associated with the SARM1-TIR domain or whether TIR domains from other proteins could also assemble complexes that exhibit NADase activity. We expressed and purified the TIR domains of TLR4, a Toll-like receptor, and MyD88, another member of the TIR adaptor family, from NRK1-HEK293T cells and tested them in the in vitro NAD+ depletion assay. Both TLR4 and MyD88 TIR containing complexes showed no NADase activity (Figure S1B and S1C). These results support the previously reported unique roles of SARM1 among TIR adaptor proteins (Gerdts et al., 2015; O’Neill et al., 2013, Summers et al., 2016) in promoting axonal degeneration and neuronal NAD+ depletion._

Also from the introduction of PMID:31439793 that you mention:
_The noncanonical animal TIR protein SARM1 (sterile alpha and TIR motif containing 1) is required for Wallerian degeneration in axons after nerve injury (4, 5). Although other animal TIRs function as oligomeric signaling scaffolds, SARM1 has a distinct mechanism: SARM1’s TIR domain is the founding member of a class of enzymes that cleave nicotinamide adenine dinucleotide (oxidized form; NAD+)_

And from the 'outlook' section of PMID:31439792 you mention:
_We describe the structural basis of self-association–dependent NAD+ cleavage by TIR domains from animal SARM1 and plant NLRs. TIR domains have a flavodoxin fold common to many proteins with diverse functions, and our bioinformatic analyses reveal that they are related to a number of proteins with enzymatic activities such as nucleotide and carbohydrate hydrolysis, consistent with the NAD+ cleavage activity observed for TIR domains. Some branches may have lost enzymatic activity but retained scaffolding protein interaction functions. TLR and adaptor proteins show no NADase activities [fig. S7E; (13)]; although TLRs have glutamate residues in the analogous region of the protein, these are not found in the same spatial locations (Fig. 1)._ 

So...it looks like the nucleosidase activity is present in some metazoan proteins with a TIR domain (e.g. SARM1, plants NLRs) but not others (fly Toll mammalian TLR proteins).  Maybe we need some subtypes of this InterPro entry?

**Comment by sarach06** [comment]
Hi Steven,
Yes, that's true. What we can do is remove the term from this entry and add it to the specific entries (e.g. IPR039184 or IPR044974). What do you think?
Thanks,
Sara
