### ISSUE TITLE
PTN000537561 not intracellular transport in yeast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3952]
* **PTHR ID & PTN node:**

GO:0006886 | intracellular protein transport | IBA with PTN000537561 , MGI:2385326 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

cdc16 https://www.pombase.org/gene/SPAC6F6.08c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation.
In yeast this is the SIN signalling GTPase.  It doesn't have a mammalian counterpart.

I think this must be a domain hit to the vesicle-mediated transport GTPases

**Comment by marcfeuermann** [comment]
Fixed.
