### ISSUE TITLE
 PTN001115716 , biosynthesis not organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3954]
* **PTHR ID & PTN node:**

GO:0031505 | fungal-type cell wall organization | IBA with PTN001115716 , P30583

* **Sequences with problematic annotation (ID + gene/protein name):**

chs1,
I have this annotated to
GO:0034217 | ascospore wall chitin biosynthetic process

biosynthesis  is separate from organization

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous source

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed.
