### ISSUE TITLE
PTN001266432 biosynthesis , not organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3955]
* **PTHR ID & PTN node:**

GO:0031505 | fungal-type cell wall organization | IBA with CAL0000186924 , CAL0000181783 , P43076 , S000004335 , S000004924 , S000005492 , PTN001266432

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

According to this ticket, this is biosynthesis, not organization
https://github.com/geneontology/go-ontology/issues/21244

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed.
