### ISSUE TITLE
Mrp/NBP35 ATP-binding protein (IPR019591)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3956]
* **InterPro ID / label**
Mrp/NBP35 ATP-binding protein (IPR019591)
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR019591/

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly proteins Q8SZU4, Q9VJI9, Q9VPD2

* **Description of issue**
I think it's appropriate to replace "ATPase (GO:0016887)" currently on this entry with the recently created "ATP-dependent FeS chaperone activity (GO:0140663)" term.

@pgaudet agree?

**Comment by sarach06** [comment]
Hi,
Many thanks for this. I replaced the term as you suggested. It will be available in the next Interpro release.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
