### ISSUE TITLE
DNA mismatch repair MutS family IPR045076

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3957]
* **InterPro ID / label**
DNA mismatch repair MutS family (IPR045076)
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR045076/

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly Q9VUM0, P43248

* **Description of issue**
I think you can add the recently added term "ATP-dependent DNA damage sensor activity (GO:0140664)" to this entry.

@pgaudet

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I added this term to the entry. It will be visible in InterPro 88.0.
Best,
Sara
