### ISSUE TITLE
Rad50/SbcC-type AAA domain  IPR038729

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3958]
* **InterPro ID / label**
Rad50/SbcC-type AAA domain  IPR038729

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly Q9W252

* **Description of issue**
I think you can add the recently added term "ATP-dependent DNA damage sensor activity (GO:0140664)" to this entry.

@pgaudet

**Comment by sarach06** [comment]
Hi,
Yes, that's right. Thank you very much. I added the term, which will be available in Interpro 88.0.
Best,
Sara
