### ISSUE TITLE
DNA mismatch repair protein MutL/Mlh/Pms IPR038973

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3959]
* **InterPro ID / label**
DNA mismatch repair protein MutL/Mlh/Pms IPR038973
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR038973/

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly O61917, O76417

* **Description of issue**
I think you can add the recently added term "ATP-dependent DNA damage sensor activity (GO:0140664)" to this entry.

@pgaudet

**Comment by sarach06** [comment]
Hi,
Thank you very much, I have added the term to this entry. 
Best, 
Sara
