### ISSUE TITLE
DNA recombination and repair protein RecA-like, ATP-binding domain IPR020588

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3960]
* **InterPro ID / label**
DNA recombination and repair protein RecA-like, ATP-binding domain IPR020588
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR020588/

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly Q27297, O77135, Q8SZ30

* **Description of issue**
I think you can replace "ATPase, acting on DNA (GO:0008094)" on this entry with the recently added term "ATP-dependent DNA damage sensor activity (GO:0140664)".

@pgaudet

**Comment by sarach06** [comment]
Hi,
Many thanks. I replaced the term as you suggested. It will visible in InterPro 88.0.
Cheers,
Sara
