### ISSUE TITLE
GroES chaperonin family IPR020818

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3961]
* **InterPro ID / label**
GroES chaperonin family IPR020818
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR020818/

* **Description of issue**
I think you can change "ATPase (GO:0016887)" on this term to "ATP-dependent protein folding chaperone (GO:0140662)"

@pgaudet

**Comment by sarach06** [comment]
Hi,
Thanks a lot. I have replaced GO:0016887 with GO:0140662. The changes will be seen in InterPro 88.0.
Best,
Sara
