### ISSUE TITLE
Clp protease, ATP-binding subunit ClpX IPR004487

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3962]
* **InterPro ID / label**
Clp protease, ATP-binding subunit ClpX IPR004487
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR004487/

* **Description of issue**
I think you can add "ATP-dependent protein folding chaperone (GO:0140662)" to this entry

(There's also a typo in the second sentence of the description - "depedent")

@pgaudet

**Comment by sarach06** [comment]
Hi,
Thanks you very much. I fixed the typo and adde the term to this entry. The changes will be available in Interpro 88.0.
Best,
Sara

**Comment by sjm41** [comment]
Thanks for fixing all these related tickets Sara!
