### ISSUE TITLE
Heat shock protein Hsp90 family (IPR001404)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3963]
* **InterPro ID / label**
Heat shock protein Hsp90 family (IPR001404)

* **Description of issue**
I think you can change "ATP hydrolysis activity (GO:0016887)" on this entry to "ATP-dependent protein folding chaperone (GO:0140662)".

@pgaudet

**Comment by raymond91125** [comment]
I agree that we have two issues here,
1. Display. Neither AmiGO nor QuickGO shows the relation
- 'GO:0140657 ATP-dependent activity' has part some GO:0016887 ATP hydrolysis activity
2. Reasoning. Annotations to GO:0140657 ATP-dependent activity are not automatically propagated to GO:0016887 ATP hydrolysis activity. e.g. Ce helq-1 is directly annotated to single-stranded DNA helicase activity. This annotation is propagated to ATP-dependent activity but not propagated to ATP hydrolysis activity.

**Comment by sjm41** [comment]
Hi @pgaudet - You said above that the issue above would be discussed with ontology editors (again!).  Has that happened yet? Any resolution?  Should InterPro hold off making the InterProGO suggested at the top of this ticket?

**Comment by sjm41** [comment]
Hi @sarach06. While the general issue (raised by Val and Raymond above) still needs more discussion, can you still add "ATP-dependent protein folding chaperone (GO:0140662)" to IPR001404 please?  (You can keep the "ATP hydrolysis activity" term as well, at least for now.)
Thanks.

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have added the term to this entry. It will be visible in the next InterPro release.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara

@pgaudet I'll close this specific ticket and let the wider discussion occur elsewhere.
