### ISSUE TITLE
Review annotations to  GO:0070734 histone H3-K27 methylation & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3966]
Dear all, 

The proposal has been made to obsolete GO:0070734 histone H3-K27 methylation & children
*  GO:0061086 negative regulation of histone H3-K27 methylation
*  GO:0061087 positive regulation of histone H3-K27 methylation
*  GO:0061085 regulation of histone H3-K27 methylation 

Annotations are here: https://docs.google.com/spreadsheets/d/1w9zvcfSqUHS8p54Jf4-FjY4r-7QAHwJuCP7SMlUMbeM/edit#gid=0

Contributor | (Assigned by)   
-- | --
ARUK-UCL  |   1
FlyBase | 14
MGI | 17
RGD 2
TAIR    | 7
UniProt | 44
WB |  4
ZFIN |    2

**Comment by suzialeksander** [comment]
errors are now in reports. closing.
