### ISSUE TITLE
Fix annotations to GO:0051816	acquisition of nutrients from other organism during symbiotic interaction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3970]
Hi @marekskrzypek 

CGD CYB2 (CAL0134171) is annotated to GO:0051816	acquisition of nutrients from other organism during symbiotic interaction, which will be obsoleted, see https://github.com/geneontology/go-ontology/issues/22343

Maybe this can simply be removed, as the annotation to 'lactate metabolic process' sort of covers it? Or maybe the more precise term works, 'acquisition of nutrients from host' ? 

Thanks, Pascale

**Comment by marekskrzypek** [comment]
Changed to GO:0051816

**Comment by pgaudet** [comment]
Thanks!
