### ISSUE TITLE
InterPro mapping InterPro:IPR009104

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#3972]
* **InterPro ID / label**
* InterPro:IPR009104

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**
InterPro:IPR009104 is mapped to GO:0052331 | hemolysis in other organism involved in   symbiotic interaction
This term will be obsoleted, see https://github.com/geneontology/go-ontology/issues/22343

Perhaps you could annotate to ' [is_a relation] GO:0044179 hemolysis in other organism' or 'GO:0051715 cytolysis in other organism'? 

(BTW The entry describes a sea anemone toxin, but also hits zebrafish and other entries; maybe this is right, but it could help to widen the description). 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much for this. I changed GO:0052331 for GO:0051715 'cytolysis in other organism' as they not only cause hemolysis, they affect other cells as well. Also, I mentioned in the abstract the fish matches. These changes will be visible in InterPro 88.0.
Best,
Sara

**Comment by sarach06** [comment]
Hi Pascale,
I forgot to mention it before, sorry about that, Hsin-yu is not working at the EBI anymore, could you remove her from the InterPro curators list when tagging us, please? Keeping Beatriz (blazaropinto) and me is ok.
Many thanks!
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks for the info @sarach06 !
