### ISSUE TITLE
METHYLOSOME PROTEIN 50 PTN005323416

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#3973]
* **
METHYLOSOME PROTEIN 50 PTHR46853 & PTN005323416 node:**
http://www.pantree.org/node/annotationNode.jsp?id=PTN005323416

* **Sequences with problematic annotation (ID + gene/protein name):**
FBgn0003978 etc

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Annotations seem not to involve the major role of the methylosome https://www.ebi.ac.uk/QuickGO/term/GO:0034709 and most are single source. Suggest that this is reviewed.
'negative regulation of epithelial cell proliferation involved in prostate gland development' being a particularly horrible example.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Indeed, the PAINT propagation here was quite weird. I've reviewed this family, removing most annotations.
Greetings to the Drosophila's prostate ;-)
Marc.
