### ISSUE TITLE
UniRule: UR000780754 / ARBA: ARBA00000928

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3981]
UniRule: UR000780754 says: if protein "Matches PIR Superfamily signature PIRSF027081" then apply "Endonucleolytic cleavage of RNA, removing 5'-extranucleotides from tRNA precursor. EC:3.1.26.5".

But PIRSF027081 corresponds to POP4/Rpp29, a non-catalytic subunit of the RNase P/MRP complex (the RNA component is catalytic). PMID: 27187488

==

Similarly ARBA: ARBA00000928 includes "if Matches InterPro signature IPR016848 (Ribonuclease P/MRP subunit Rpp29)" then add "Endonucleolytic cleavage of RNA, removing 5'-extranucleotides from tRNA precursor. EC:3.1.26.5"

Adding EC:3.1.26.5 to UP entries via these rules then propagates an inaccurate EC2GO annotation of "ribonuclease P activity".

**Comment by PedroRaposo** [comment]
From the Flybase entries (https://www.uniprot.org/uniprotkb?query=POP4+AND+%28taxonomy_id%3A7227%29&fields=acc[…]sts%2Clineage%2Corganism_name%2Cec%2Cxref_interpro&view=table), none of these entries (different mRNA or fragments of the same protein) now display any EC number.

The ARBA rule (https://www.uniprot.org/arba/ARBA00000928) seems to use InterPro signatures not anymore in the Drosophila POP4/Rpp29 entry.

For the PIR rule and UniRule, it seems the content of the rule has also been updated:
https://www.ebi.ac.uk/uniprot/unirule/rule/view?id=780754 & https://www.uniprot.org/unirule/UR000780754
