### ISSUE TITLE
InterPro2GO: N-acetylglucosaminyl transferase component (IPR007720)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3982]
* **InterPro ID / label**
N-acetylglucosaminyl transferase component (IPR007720)

* **Example sequences with problematic annotation (ID + gene/protein name):**
D. melanogaster PIG-Q (Q8IR17)
Human PIGQ (Q9BRB3)

* **Description of issue**
PIG-Q is a non-catalytic subunit of the GPI-GnT) complex, so the 'phosphatidylinositol N-acetylglucosaminyltransferase activity (GO:0017176)' GO MF term should be removed.

Also see #3693

**Comment by blazaropinto** [comment]
Thank you for that. This GO term is removed and the description of the entry updated. These changes will be available
in InterPro 88.
Best regards,
Beatriz

**Comment by sjm41** [comment]
Thanks!
