### ISSUE TITLE
Soluble quinoprotein glucose/sorbosone dehydrogenase (IPR011041)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3983]
* **InterPro ID / label**
Soluble quinoprotein glucose/sorbosone dehydrogenase (IPR011041)

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly Q9VYN8
human Q9Y2X0, Q96QV1, Q96JK4, Q8N145, Q6UX06, Q6UWX4, Q05BV3

* **Description of issue**
None of the fly or human proteins matching this superfamily (listed above) are characterized to be enzymes, so I think the 'catalytic activity (GO:0003824)' GO term should be removed from this entry.

**Comment by blazaropinto** [comment]
Thank you so much for pointing this out. The GO term is removed. The changes will be available in InterPro 88.
Best regards,
Beatriz

**Comment by sjm41** [comment]
Thanks!
