### ISSUE TITLE
Polymerase/histidinol phosphatase-like (IPR016195)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3984]
* **InterPro ID / label**
Polymerase/histidinol phosphatase-like (IPR016195)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Human P78346
Fly Q9VPM0

* **Description of issue**
This term is currently annotated with 'catalytic activity (GO:0003824)'.  But this superfamily entry hits Ribonuclease P protein subunit p30, which is a non-catalytic component of RNase P/MRP. In addition, several of the listed 'overlapping InterPro entries' lack any catalytic activity GO term. So I think 'catalytic activity (GO:0003824)' should be removed.

**Comment by blazaropinto** [comment]
Thank you for that. The term is removed now. These changes will be available in InterPro 88.
Best regards,
Beatriz

**Comment by sjm41** [comment]
Great, thanks!
