### ISSUE TITLE
Alkaline-phosphatase-like, core domain superfamily (IPR017850)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3985]
* **InterPro ID / label**
Alkaline-phosphatase-like, core domain superfamily (IPR017850)

* **Description of issue**
The description for this entry starts with "This superfamily represents a structural domain with a core 3-layer alpha/beta/alpha structure, which can sometimes contain additional subdomains (also covered by this entry). These domains form the core domain of alkaline phosphatases."
This suggests that IPR017850 is a 'structural domain' and that the subdomains (which are not always present) 'form the core domain of alkaline phosphatases'.  That is, not all proteins with IPR017850 are enzymes.
Consistent with that, some of the 'overlapping entries' are not annotated with a catalytic activity GO term.

So I think 'catalytic activity (GO:0003824)' should be removed from this entry.

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. Actually, I think the description of this entry should be updated to represent the catalytic domain of these structural related enzymes (PMID: 12657638,  11746679), as evidenced when comparing with other entries such as IPR000917 (it doesn't have GO:0003824 but has GO:0008484). I suggest updating this description and keep the term unless you have specific examples for which it would be an incorrect propagation. Also I can check the overlapping entries to add/update GO terms on it. Let me know if you agree.

Many thanks,
Sara

**Comment by sjm41** [comment]
Hi Sara

Thanks for looking into this.
I don't have any specific examples that prove the propagation is incorrect, but I have ~15 fly proteins (listed below) that have _only_ these 2 signatures:
IPR017850:Alkaline-phosphatase-like, core domain superfamily (catalytic activity GO:0003824)
IPR004245:Protein of unknown function DUF229  (no GO terms)

I was trying to decide if the presence of IPR017850 (superfamily) was sufficient evidence to classify these proteins as enzymes.  My conclusion was probably not given (i) the entry's current description and (ii) the fact these proteins don't have any of the more specific overlapping entries.

FBgn0032843 | CG10730 (Q9VIP6)
FBgn0032964 | CG11630 (Q9V9Q1)
FBgn0032967 | CG1428 (Q9V9P7)
FBgn0037964 | CG14731 (Q9VGG4)
FBgn0038832 | CG15695 (Q8SY05)
FBgn0032338 | CG16854 (M9ND65)
FBgn0032082 | CG18088 (Q9VLG3)
FBgn0031465 | CG3123 (Q9VQH3)
FBgn0051933 | CG31933 (Q9VQ50)
FBgn0052984 | CG32984 (Q86BL8)
FBgn0052985 | CG32985 (Q86BL9)
FBgn0038318 | CG6236 (Q9VF91)
FBgn0035888 | CG7120 (M9PEJ0)
FBgn0035216 | CG9168 (Q9W0F7)
FBgn0032080 | CG9525 (Q9VLG5)
FBgn0039591 | CG9988 (Q9VAU4)

**Comment by sarach06** [comment]
Hi,
I see. I tried to find some evidence but haven't either. I'll remove the term, then.

Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara.  (I think any bona fide enzyme will have one of the more specific 'child' InterPro entries, so will get an InterPro2GO annotation that way if applicable.)
