### ISSUE TITLE
RNA polymerase subunit Rpb7-like (IPR045113)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3986]
* **InterPro ID / label**
RNA polymerase subunit Rpb7-like (IPR045113)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly Q9VM72 (Polr1F)
Fly Q9VFB5 (Polr2G)
Fly Q9VTL6 (Polr3H)

* **Description of issue**
Rpb7-like subunits are not part of the 'catalytic core' of RNA polymerases (e.g. see PMID:22365827,), so I think "DNA-directed 5'-3' RNA polymerase activity (GO:0003899)" should be removed from this entry (consistent with other RNAP subunit entries in InterPro).

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have removed the term from this entry. The changes will be available in the next InterPro release (88.0).
Best,
Sara
