### ISSUE TITLE
ER-bound oxygenase mpaB/mpaB'/Rubber oxygenase, catalytic domain (IPR018713)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3987]
* **InterPro ID / label**
ER-bound oxygenase mpaB/mpaB'/Rubber oxygenase, catalytic domain (IPR018713)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly Q95U32 (CG31344)

* **Description of issue**
Description says the domain is found in three oxygenases from Penicillium/Streptomyces and in "uncharacterised proteins from Mycobacterium sp. and hypothetical proteins, mainly from bacteria and fungi".  Given that last bit, I'm not sure having "oxidoreductase activity (GO:0016491)" on the entry is warranted. What do you think?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. Although I can see the key active site residues in the alignment, probably we can't assure all members have "oxidoreductase activity (GO:0016491)", so I removed the term from this entry. The changes will be visible in the next InterPro release (88.0).
Best,
Sara

**Comment by sjm41** [comment]
OK, thanks Sara!
