### ISSUE TITLE
STAGA complex 65 subunit gamma (IPR039460)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3988]
* **InterPro ID / label**
STAGA complex 65 subunit gamma (IPR039460)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly Q9VX12 (Spt7)

* **Description of issue**
This is not a catalytic subunit of the STAGA complex (e.g. PMID: 17375202, 22426530) so "histone acetyltransferase activity (GO:0004402)" should be removed from the InterPro entry.

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have removed the term from this entry and added the references. The changes will be visible in the next InterPro release (88.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
