### ISSUE TITLE
Pre-mRNA-splicing factor SLU7 InterPro (IPR039974)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3998]
* **InterPro ID / label**
Pre-mRNA-splicing factor SLU7 InterPro (IPR039974)

* **Example sequences with problematic annotation (ID + gene/protein name):**
human SLU7 (O95391)
cerevisiae SLU7 (Q02775)
fly Slu7 (Q9VAQ7)

* **Description of issue**
I'm not convinced this entry should have "second spliceosomal transesterification activity (GO:0000386)".  SLU7 is definitely involved in mRNA splicing, but its function in the referenced paper (PMID: 10197984) is described as being "required for a structural alteration of the spliceosome prior to the establishment of the catalytically active spliceosome for step II."  UP entry for human SLU7 (O95391) says "Required for holding exon 1 properly in the spliceosome and for correct AG identification when more than one possible AG exists in 3'-splicing site region. May be involved in the activation of proximal AG. Probably also involved in alternative splicing regulation."  Also this 2019 paper (PMID: 30705154) describes a structural role for SLU7.
So, I don't think SLU7 has, or contributes to, catalytic activity itself. What do you think?

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I agree with you. The term has been removed from this entry. 
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
