### ISSUE TITLE
Diphthamide synthesis DPH1/DPH2 (IPR016435)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#3999]
* **InterPro ID / label**
Diphthamide synthesis DPH1/DPH2 (IPR016435)

* **Description of issue**
I think you can add "2-(3-amino-3-carboxypropyl)histidine synthase activity (GO:0090560)" to this entry (and its children). Matches EC 2.5.1.108.

**Comment by blazaropinto** [comment]
Good morning,
Thank you so much for this suggestion. I added this GO term to the entry. The change will be available in InterPro 88.
Best regards,
Beatriz

**Comment by sjm41** [comment]
Thanks Beatriz.

**Comment by sjm41** [comment]
You mean, you can add also add GO:0017183 to the entry (in addition to GO:0090560)?  That sounds right to me.

**Comment by blazaropinto** [comment]
I mean there aresome "Diphthamide biosynthesis proteins" in this entry (in Swiss Prot: A0A1D8PL26 and Q59SJ9) that are described as being involved in this process but not as catalysing this specific reaction (I think this paper might help here PMID: 24739148)

**Comment by sjm41** [comment]
A0A1D8PL26 (DPH22_CANAL) and Q59SJ9 (DPH21_CANAL) have UP function statements based on similarity to P32461 (DPH2_YEAST), which is annotated to EC 2.5.1.108/GO:0090560.
Looks like these entries are the Candida orthologs of cerevisiae DPH1/DPH2?

So I think both GO terms discussed above are correct for these UP accessions, and both can still be added to IPR016435 (unless you have other examples?)

Cheers
Steven

**Comment by sjm41** [comment]
Excellent, thanks again!
