### ISSUE TITLE
Inosine/uridine-preferring nucleoside hydrolase domain (IPR001910)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4001]
* **InterPro ID / label**
Inosine/uridine-preferring nucleoside hydrolase domain (IPR001910)
Ribonucleoside hydrolase-like (IPR036452)

* **Description of issue**
Based on the description, linked EC numbers, and matching proteins in fly (at least) I think this GO term could be added to both those entries:
GO:0016799 hydrolase activity, hydrolyzing N-glycosyl compounds (EC xref = 3.2.2.-)

What do you think?

**Comment by deustp01** [comment]
This looks like a really fine-grained term request, at odds with the recent push to capture such detail at the level of annotations and confine terms to ones that describe broader classes of chemistry (e.g. the recent reluctance to allow distinct terms for kinases acting on different modified forms of a nucleotide. Is there a level of generality here that I'm missing?
@ukemi @pgaudet

**Comment by sjm41** [comment]
@deustp01 This isn't a new term request.  Just asking for an existing GO term to be associated with an existing InterPro entry(ies).

**Comment by deustp01** [comment]
Sorry - it's early Monday morning. But I will probably still wonder about the granularity after I'm fully awake.

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I added the term as you suggested, in both entries. It will be visible in InterPro 88.0.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
