### ISSUE TITLE
PTN000553037  not regulation of process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4002]
* **PTHR ID & PTN node:**

rpt1 | ↑regulates,positively_regulates GO:1901800 | positive regulation of proteasomal protein catabolic process | 

rpt1 | IBA with P35998 , S000002165 , PTN000553037 | Gaudet P et al. (2011) | 16

rpt6 |   | IBA with S000002165 , PTN000553037 , P35998

* **Sequences with problematic annotation (ID + gene/protein name):**

See above

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I would not annotate these to "regulation of proteasomal protein catabolic process"
I'd say that they were **part_of** the process? (they could be annotated possibly to 'protease regulator activity' (with the protease subunits as inputs) part_of "proteasomal protein catabolic process"

**Comment by marcfeuermann** [comment]
Does not seem to be annotated to regulation anymore.
