### ISSUE TITLE
are pentose shunt enzymes "pentose catabolic process"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4003]
* **PTHR ID & PTN node:**

GO:0019323	pentose catabolic process  IBA with P0AG07 , PTN00020266

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
 https://www.pombase.org/gene/SPAC31G5.05c (transferred to)
and P0AG07 (transferred from)

This doean't seem correct. This is the only pentose shunt pathway component annotated to this term (also if it were correct , shouldn't 
GO:0019323	pentose catabolic process be a superclass of 
GO:0006098    pentose-phosphate shunt

https://en.wikipedia.org/wiki/Pentose_phosphate_pathway
While the pentose phosphate pathway does involve oxidation of glucose, its primary role is anabolic rather than catabolic.

**Comment by marcfeuermann** [comment]
This looks okay now.
