### ISSUE TITLE
Review annotations to GO:0031493 nucleosomal histone binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4008]
Dear all, 

The proposal has been made to obsolete  GO:0031493 nucleosomal histone binding, see https://github.com/geneontology/go-ontology/issues/22467

There are 39 manual annotations 

Contributor   (Assigned by) | Number of annotations
-- | --
ARUK-UCL | 2
BHF-UCL | 1
ComplexPortal | 1
PomBase  (fixed) | 24
RGD | 1
SGD | 3
TAIR | 2
UniProt | 3

There is one InterPro mapping: IPR021162 @sarach06 @blazaropinto 

One PTHR family: PTHR22880 

Annotations are here: 
https://docs.google.com/spreadsheets/d/19MgrkVHpofzkfmW1HuY9vWimEXF97TiTfsEZ621pWbs/edit#gid=0

Thanks, Pascale

**Comment by blazaropinto** [comment]
Hi Pascale,

Thank you so much for letting us know. This is updated in InterPro, the changes will be available in the next release.

Best,
Beatriz

**Comment by srengel** [comment]
SGD done.

**Comment by gthayman** [comment]
RGD done.

**Comment by RLovering** [comment]
UCL done

**Comment by ValWood** [comment]
Pombase appear to be done.

**Comment by tberardini** [comment]
TAIR appears to be done.

**Comment by tberardini** [comment]
@pgaudet Close?
