### ISSUE TITLE
InterPro histone families annotation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4009]
Hello, 

There is a MF for histones, GO:0030527 structural constituent of chromatin; however there are no InterPro annotations to this. @blazaropinto @sarach06 would you consider adding this function to histone InterPro families? 

Thanks, Pascale

**Comment by blazaropinto** [comment]
Hi Pascale,

Thank you for that. We are adding the term to the pertinent entries. The changes will be available in the next InterPro release.

Best regards,
Beatriz

**Comment by pgaudet** [comment]
Great! Thanks, Pascale
