### ISSUE TITLE
Block annotations to FBgn0001206 from PTN000496516

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4014]
* **NASCENT POLYPEPTIDE ASSOCIATED COMPLEX ALPHA SUBUNIT-RELATED (PTHR21713) & PTN000496516 node**

* **Sequences with problematic annotation (FBgn0001206 + Hmr)**

* **Type of Issue: Although Hmr has domain similarity, this is a chromatin binding protein - please block all annotations from this node (unfolded protein binding, protein targeting to membrane, cytoplasm)**

**Comment by marcfeuermann** [comment]
Done
