### ISSUE TITLE
BGL2  Endo-beta-1,3-glucanase not PTN001047358 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4015]
* **PTHR ID & PTN node:**

PTN001047358 

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC26H5.08c
and others

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Seems to be both. Erroneous source for

GO:0042124 | 1,3-beta-glucanosyltransferase activity | IBA with CAL0000186956 , PTN001047358 , S000003514

it's a 
GO:0042973 | glucan endo-1,3-beta-D-glucosidase activity

**Comment by ValWood** [comment]
tagging @suzialeksander to check

**Comment by suzialeksander** [comment]
Agreed, changed SGD source.

**Comment by marcfeuermann** [comment]
Done.
