### ISSUE TITLE
pentose -phosphate shunt not GO:0044262	cellular carbohydrate metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4017]
* **PTHR ID & PTN node:**

GO:0044262	cellular carbohydrate metabolic process IBA with PTN000202667 , P32719

* **Sequences with problematic annotation (ID + gene/protein name):**
https://www.pombase.org/gene/SPAC31G5.05c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

The parentage of 
pentose-phosphate shunt
is 'carbohydate derivative metabolic process', not 'carbohydrate metabolic process'.

**Comment by pgaudet** [comment]
PAINT issue resolved

**Comment by pgaudet** [comment]
Ontology issue opened: https://github.com/geneontology/go-ontology/issues/24641
