### ISSUE TITLE
IPR037520  GAP not GEF

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4018]
* **InterPro ID / label**

I'm not 100% sure about this one:

GO:0005085 | guanyl-nucleotide exchange factor activity | IEA with IPR037520 |   | GO_REF:0000002

but most info seems to point to it being a GAP not a GEF

1. SGD annotation https://www.yeastgenome.org/locus/S000001659
Seems to be a GAP for Gtr2 (is annotated as a GAP)

2. the Interpro definitions says
This is the N-terminal domain of folliculin, the longin domain [1, 2, 3]. An arginine residue located in this domain (Arg164) is catalytic residue for GAP activity
and
3. Folliculin (FLCN) is a tumor suppressor that enables nutrient-dependent activation of the mechanistic target of rapamycin complex 1 (mTORC1) protein kinase via its guanosine triphosphatase (GTPase) Activating Protein (GAP) activity. 

(although it also says  This domain can also be found in SMCR8, a component of the C9orf72-SMCR8 complex, a complex that has guanine nucleotide exchange factor (GEF) activity and regulates autophagy) , but being a member of a complex with GEF activity doesn't not rule out it being a GAP since the GAF and GAP are frequently in the same complex.

On balance the evdence is much stronger for GAP activity.

**Comment by blazaropinto** [comment]
Hi Val,
I agree. I added GO:0005096 and removed GO:0005085. The changes will be available in the next InterPro release.
Best regards,
Beatriz
