### ISSUE TITLE
PTN000349879 direct role in DNA replication and repair 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4019]
* **PTHR ID & PTN node:**

GO:0006282 | regulation of DNA repair | IBA with PTN000349879 , S000005162

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC26H5.02c
O13984

This has a direct role in DNA replication and repair rather than "regulation of..."

**Comment by marcfeuermann** [comment]
Done.
