### ISSUE TITLE
PTN001126135 - PTHR48100 - not intramolecular transferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4020]
* **PTHR ID & PTN node:**

GO:0016868 | intramolecular transferase activity, phosphotransferases | IBA with Q79FW5 , PTN001126135

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1687.21
O94461

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation.

This is transferred from microbacterium, but this annotation should not be transferred to all members of the family.

See
https://www.pombase.org/gene_subset/interpro:IPR001345
(only some members are phosphoglycerate mutateses)

**Comment by pgaudet** [comment]
Changed to phosphatase activity.
