### ISSUE TITLE
protein serine/threonine/tyrosine kinase activity (GO:0004712) mappings from RHEA

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4021]
Nearly all of the pombe protein kinases are being mapped to 
the term
protein serine/threonine/tyrosine kinase activity (GO:0004712)
by RHEA (most of them are definitely not considered to be dual specificity, although a few could be, definitely the ones below are not considered to be- so it might be best to make this mapping more conservative.

the mappings are from 
IEA with 46608 GO_REF:0000116
and
IEA with 17989 GO_REF:0000116

SPCC24B10.07 | gad8 | serine/threonine protein kinase (AGC family) Gad8
SPBC1347.06c | cki1 | serine/threonine protein kinase (CK1 family) Cki1
SPBP35G2.05c | cki2 | serine/threonine protein kinase (CK1 family) Cki2
SPAC1805.05 | cki3 | serine/threonine protein kinase (CK1 family) Cki3
SPBC3H7.15 | hhp1 | serine/threonine protein kinase (CK1 family) Hhp1
SPAC23C4.12 | hhp2 | serine/threonine protein kinase (CK1 family) Hhp2
SPBC21C3.18 | spo4 | serine/threonine protein kinase (DDK family) Spo4
SPAC24B11.11c | sid2 | serine/threonine protein kinase (NDR family) Sid2
SPCC74.03c | ssp2 | serine/threonine protein kinase AMPK catalytic (alpha) subunit Ssp2
SPBC18H10.15 | cdk11 | serine/threonine protein kinase Cdk11
SPAC57A10.02 | cdr2 | serine/threonine protein kinase Cdr2
SPCC1450.11c | cek1 | serine/threonine protein kinase Cek1
SPAC23C11.11 | cka1 | serine/threonine protein kinase Cka1
SPBC8D2.01 | gsk31 | serine/threonine protein kinase Gsk31
SPAC29A4.16 | hal4 | serine/threonine protein kinase Hal4
SPCC576.15c | ksg1 | serine/threonine protein kinase Ksg1
SPBC16E9.13 | ksp1 | serine/threonine protein kinase Ksp1
SPCC70.05c | nnk1 | serine/threonine protein kinase Nnk1
SPCC1020.10 | oca2 | serine/threonine protein kinase Oca2
SPAC821.12 | orb6 | serine/threonine protein kinase Orb6
SPAC110.01 | ppk1 | serine/threonine protein kinase Ppk1
SPAC3H1.13 | ppk13 | serine/threonine protein kinase Ppk13
SPAC4G8.05 | ppk14 | serine/threonine protein kinase Ppk14
SPAC823.03 | ppk15 | serine/threonine protein kinase Ppk15
SPAC890.03 | ppk16 | serine/threonine protein kinase Ppk16
SPBC1778.10c | ppk21 | serine/threonine protein kinase Ppk21
SPBC1861.09 | ppk22 | serine/threonine protein kinase Ppk22
SPBC21.07c | ppk24 | serine/threonine protein kinase Ppk24
SPBC32C12.03c | ppk25 | serine/threonine protein kinase Ppk25
SPBC725.06c | ppk31 | serine/threonine protein kinase Ppk31
SPCC162.10 | ppk33 | serine/threonine protein kinase Ppk33
SPAC1805.01c | ppk6 | serine/threonine protein kinase Ppk6
SPAC22G7.08 | ppk8 | serine/threonine protein kinase Ppk8
SPCC777.14 | prp4 | serine/threonine protein kinase Prp4
SPBC19C2.05 | pat1 | serine/threonine protein kinase Ran1/Pat1
SPCC4G3.08 | psk1 | serine/threonine protein kinase S6K family Psk1
SPAC1B9.02c | sck1 | serine/threonine protein kinase S6K family Sck1
SPAC22E12.14c | sck2 | serine/threonine protein kinase S6K family Sck2
SPBC21.06c | cdc7 | serine/threonine protein kinase SIN pathway Cdc7
SPBC119.07 | vps15 | serine/threonine protein kinase Vps15
SPBC8D2.19 | mde3 | serine/threonine protein kinase, meiotic, STKc MAK-like Mde3
SPAC3C7.06c | pit1 | serine/threonine protein kinase, meiotic, STKc MAK-like Pit1
SPAC167.01 | ire1 | serine/threonine protein kinase, sensor for unfolded proteins in the ER Ire1

**Comment by ValWood** [comment]
@pgaudet  there is no label for Rhea and I don't know who to assign to.

**Comment by pgaudet** [comment]
This may get fixed by changes in https://github.com/geneontology/go-ontology/issues/20882

**Comment by pgaudet** [comment]
@ValWood is this still a problem?

**Comment by ValWood** [comment]
I think it's OK. I filter the problems from PomBAse as I report them, but these also seem to be OK in UNiPRot, so I assume the problem is fixed.
