### ISSUE TITLE
TAIR misannotation to 'conjugation'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4022]
GH3.7 GRETCHEN HAGEN 3.7 (TAIR, locus:2201170) is annotated to  GO:0000746 conjugation, but in the 'ligase' sense. 

IN PAINT we have annotated to GO:0016881 acid-amino acid ligase activity; maybe there is a better, more specific term, but that would already be an improvement. 

Thanks, Pascale

**Comment by tberardini** [comment]
Fixed. Will be in April 1 release.
