### ISSUE TITLE
PTN000111103 guanine deglycation, glyoxal removal

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4023]
* **PTHR ID & PTN node:**

sdj1 | GO:0106046 | guanine deglycation, glyoxal removal | IBA with Q99497 , PTN000111103 | Gaudet P et al. (2011) | 1

Probably best not to transfer this annotation. There is only a single EXP  annotation (PARJ7) and according to the UnoPRot entry this is disputed.
It is not clear that it removes glyoxal from free guanine residues.

**Comment by marcfeuermann** [comment]
In PAINT we have now a NOT annotation for human and another one for Fly. Moreover the term does not seem to be propagated anymore. No action required.
