### ISSUE TITLE
Review GO:1903231 mRNA binding involved in posttranscriptional gene silencing annotations

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#4024]
Hi 

Following the recognition that miRs need to have a MF term to describe their activity the GO term GO:1903231 mRNA binding involved in posttranscriptional gene silencing has been changed to: GO:1903231 mRNA base-pairing posttranscriptional repressor activity.

However, there are a few proteins that are associated with this term. 
FlyBase 3 annotations @hattrill 
EcoCyc 1 annotation @dsiegele 
ZFIN 1 annotation @sierra-moxon 

Please review the following annotations:

GENE PRODUCT ID | SYMBOL | QUALIFIER | GO TERM | GO NAME | ECO ID | GO EVIDENCE CODE | REFERENCE | WITH/FROM | TAXON ID | ASSIGNED BY
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
P0ADZ4 | rpsO | enables | GO:1903231 | mRNA binding involved in posttranscriptional gene silencing | ECO:0000314 | IDA | PMID:2407855 | 83333 | EcoCyc
Q01085 | TIAL1 | enables | GO:1903231 | mRNA binding involved in posttranscriptional gene silencing | ECO:0000314 | IDA | PMID:33203680 | 9606 | FlyBase
Q7KWG9 | Marf1 | enables | GO:1903231 | mRNA binding involved in posttranscriptional gene silencing | ECO:0000314 | IDA | PMID:30279526 | 7227 | FlyBase
Q7T3T8 | zar1 | enables | GO:1903231 | mRNA binding involved in posttranscriptional gene silencing | ECO:0000314 | IDA | PMID:27913641 | 7955 | ZFIN
Q8IMX4 | Rox8 | enables | GO:1903231 | mRNA binding involved in posttranscriptional gene silencing | ECO:0000314 | IDA | PMID:33203680 | 7227 | FlyBase

Possible terms to apply instead include:
EcoCyc: PMID:2407855 suggests rpsO negatively regulates ribosome initiation via mRNA binding, so potentially might be able to use GO:0045947  negative regulation of translational initiation and  GO:0000900 translation repressor activity, mRNA regulatory element binding - although this term needs to have mRNA binding parent. - ticket created here: https://github.com/geneontology/go-ontology/issues/22747

ZFIN: PMID:27913641  zar1 could also be associated with the term GO:0000900 translation repressor activity, mRNA regulatory element binding OR GO:0090079 translation regulator activity, nucleic acid binding, or just  GO:0045182 translation regulator activity depending on whether you are happy with the evidence for mRNA binding etc

Thanks

Ruth

**Comment by sramachand** [comment]
ZFIN done

**Comment by RLovering** [comment]
Hi InterPro

the GO term GO:1903231 mRNA base-pairing posttranscriptional repressor activity should only be associated with RNAs not proteins (see GO term description and notes) but InterPro has associated it with 6000 proteins. Please could InterPro:IPR024768  be revised to remove this term
Thanks
Ruth

**Comment by sarach06** [comment]
Hi Ruth,
Thank you very much for this. I removed the term from this entry, which will be visible in the next InterPro release (93.0).
Best regards,
Sara

**Comment by RLovering** [comment]
Hi Sara
thanks for sorting this out, much appreciated.
Best
Ruth
