### ISSUE TITLE
GO:0004128	 cytochrome-b5 reductase activity, acting on NAD(P)H IBA with S000001633 , PTN000452207

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4027]
* **PTHR ID & PTN node:**

GO:0004128 | cytochrome-b5 reductase activity, acting on NAD(P)H | IBA with S000001633 , PTN000452207

- | GO:0006696 | ergosterol biosynthetic process | IBA with PTN001064729 , S000001633

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC17H9.12c (cyc2)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous transfer

SGD:S000001633 is MCR1, not CYC2
https://www.yeastgenome.org/locus/YOR037W is pombe cyc2 orthlog

**Comment by ValWood** [comment]
Actually looking closer I'm not sure what Cyc2 is. 

This is the best most recent description of the activity: (2005)
https://pubmed.ncbi.nlm.nih.gov/16207709/
A redox function for Cyc2p in the heme lyase reaction is suggested from 1) the presence of a noncovalently bound FAD molecule in the C-terminal domain of Cyc2p, 2) the localization of Cyc2p in the inner membrane with the FAD binding domain exposed to the intermembrane space, and 3) the ability of recombinant Cyc2p to carry the NADPH-dependent reduction of ferricyanide. We postulate that, in vivo, Cyc2p interacts with CCHL and is involved in the reduction of heme prior to its ligation to apocytochrome c by CCHL.

**Comment by ValWood** [comment]
...I'm out of my comfort zone!

**Comment by pgaudet** [comment]
It looks like Cyc2 is a heme reductase that contributes to cytochome c assembly? 
https://pubmed.ncbi.nlm.nih.gov/22257001/

**Comment by ValWood** [comment]
I think this can close, appears to be multifunctional. I don't think any of the annotation is incorrect
https://www.google.com/search?q=cytochrome-b5

**Comment by ValWood** [comment]
Actually, I think the annotatio transfer needs checking.

The pombe entry I refer to is  CYC2, but the annotation transfer is from  MCR1. I can't find an ortholog of MCR1 in pombe (it has 2 domains, and the only proteins with these two domains have independent orthologs)
https://www.pombase.org/results/from/id/cb476c10-8c83-4f7b-9793-16c6cf55508c
butt neither is cyc2

**Comment by marcfeuermann** [comment]
Annotation was done over an ancestral duplication event leading to the MCR1 and the CYC2 nodes. I've restricted annotations to respectively each node which solves the problem.
