### ISSUE TITLE
 PTN000129455 , 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4028]
* **PTHR ID & PTN node:**

primary miRNA processing | IBA with WBGene00009163 , Q9NRR4 , ZDB-GENE-070209-23 , PTN000129455 , FBgn0026722 , DDB_G0268410

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC119.11c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

https://www.pombase.org/gene/SPBC119.11c
fission yeast does not have
GO:0035195    gene silencing by miRNA

**Comment by marcfeuermann** [comment]
PAINT annotation has been restricted.
