### ISSUE TITLE
PTN000336449 not always post-transcriptional gene silencing by RNA

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4030]
* **PTHR ID & PTN node:**

GO:0035194 | post-transcriptional gene silencing by RNA | IBA with WBGene00011333 , PTN000336449

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC20F10.05

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous propagation

**Comment by pgaudet** [comment]
PAINT annotation is fixed.
