### ISSUE TITLE
PTN000560919 not always mRNA binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4031]
* **PTHR ID & PTN node:**

GO:0003729	mRNA binding
IBA with locus:2198095 , locus:2175921 , PTN000560919 , locus:2093317 , locus:2179479

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC17H9.04c

Fission yeast dri1 binds to centromeric transcripts (siRNA) is convolved in heterochromatin assembly. Fission yeast foes not have an RNAidependent post transcriptional silencing and so it does not bind to mRNAs

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous propagation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Fixed
