### ISSUE TITLE
	GO:0030174	 regulation of DNA-templated DNA replication initiation 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4032]
The fission yeast mcm complex subunits are annotated to 
GO:0030174 | regulation of DNA-templated DNA replication initiation | IDA | 

from . PMID:10770926  Lee JK et al. (2000)

However mcm is involved  directly in DNA replication, not in regulation.
I think this annotation is coming from Intact. Do we have a way to tag intact?

**Comment by ValWood** [comment]
Affects fission yeast 
mcm2 P40377
mcm3 P30666
mcm4 P29458
mcm5 P41389
mcm6 P49731
mcm7 O75001

**Comment by ValWood** [comment]
Hi @pgaudet  who is Birgits replacent as a contact? Do you know?

**Comment by pgaudet** [comment]
It's @Kalpanapanneerselvam

**Comment by sandraorchard** [comment]
Done

**Comment by pgaudet** [comment]
Thanks @sandraorchard
