### ISSUE TITLE
Review annotations to precomposed terms under GO:0046019 regulation of transcription from RNA polymerase II + development

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4035]
Dear all, 

The proposal has been made to obsolete the precomposed terms under GO:0046019 regulation of transcription from RNA polymerase II]). Few terms are left ; this next list focuses on term precomposed with a developmental term: 

Precomposed with heart development: 
* GO:1901213 regulation of transcription from RNA polymerase II promoter involved in heart development: 0 EXP
* [GO:1901227 negative regulation of transcription from RNA polymerase II promoter involved in heart development](http://amigo.geneontology.org/amigo/term/GO:1901227#display-lineage-tab): 1 EXP
* [GO:1901228 positive regulation of transcription from RNA polymerase II promoter involved in heart development](http://amigo.geneontology.org/amigo/term/GO:1901228#display-lineage-tab): 3 EXP
* [GO:0003258 regulation of transcription from RNA polymerase II promoter involved in endocardial precursor cell differentiation](http://amigo.geneontology.org/amigo/term/GO:0003258#display-lineage-tab): 0 annot
* [GO:0003256 regulation of transcription from RNA polymerase II promoter involved in myocardial precursor cell differentiation](http://amigo.geneontology.org/amigo/term/GO:0003256#display-lineage-tab): 3 EXP
* GO:0003257 positive regulation of transcription from RNA polymerase II promoter involved in myocardial precursor cell differentiation: 6 EXP
* 13 BHF @RLovering 

Precomposed with kidney development: 
* GO:0060994 regulation of transcription from RNA polymerase II promoter involved in kidney development: 1 EXP
* [GO:0061216 regulation of transcription from RNA polymerase II promoter involved in mesonephros development](http://amigo.geneontology.org/amigo/term/GO:0061216#display-lineage-tab): 0 
* [GO:0072212 regulation of transcription from RNA polymerase II promoter involved in metanephros development](http://amigo.geneontology.org/amigo/term/GO:0072212#display-lineage-tab): 0 
* 1 MGI @hdrabkin 

Precomposed with spermatogenesis
* GO:1902064 regulation of transcription from RNA polymerase II promoter involved in spermatogenesis
4 EXP 
* 1 UniProt (changed)
* 1 WB @vanaukenk 
* 2 FB @hattrill 
These should be annotated with extensions or as GO-CAM models. 

Annotations are here: https://docs.google.com/spreadsheets/d/1v4Vs1zHiySAMqEUEmiF2uuRfTDRZmET52mokg8Qp3oA/edit#gid=0

You can comment here: https://github.com/geneontology/go-ontology/issues/12739#issuecomment-1029217618

We'd like to obsolete these terms by February 10th. 

Thanks, Pascale

**Comment by hattrill** [comment]
FB done

**Comment by hdrabkin** [comment]
MGI fixed

**Comment by RLovering** [comment]
UCL done

**Comment by vanaukenk** [comment]
WB done - I think this is it for this ticket.
