### ISSUE TITLE
Review annotations to GO:0007569 cell aging & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4037]
Hello, 

The proposal has been made to obsolete GO:0007569 cell aging & its regulation children, see  https://github.com/geneontology
/go-ontology/issues/22788

There are 120 EXP annotations:  - see https://docs.google.com/spreadsheets/d/1FdIe-cpZms1Qsw7wBTF5N8ep59N3wUwoOrXnZaWLLRs/edit#gid=0

Suggestions have been made for reannotation, whenever possible.

Contributor  |  (Assigned by)
--|--
BHF-UCL | 5
CAFA | 1
FlyBase | 2 - fixed
MGI | 73
RGD | 10
SGD | 7
TAIR | 4
UniProt | 15 - fixed
ZFIN | 3

Thanks, Pascale

**Comment by srengel** [comment]
SGD done

**Comment by sramachand** [comment]
ZFIN done.

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
Pinging @RLovering and @hdrabkin , some of your annotations are still need to be fixed. 

Thanks, Pascale

**Comment by RLovering** [comment]
done for UCL

**Comment by pgaudet** [comment]
Thanks!

**Comment by hdrabkin** [comment]
done for mgi

**Comment by pgaudet** [comment]
Thanks everyone!
