### ISSUE TITLE
changing GO BP associated with IPR018737

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-annotation#4038]
IPR018737

Q10120 
(Caenorhabditis elegans)Protein lin-52

* **Description of issue**
Looking at https://www.ebi.ac.uk/interpro/entry/InterPro/IPR018737/
I think the associated GO BP term should be changed to
GO:0006355 regulation of transcription, DNA-templated
Because Protein lin-52 is a component of the DRM / DREAM complex which behaves as a co-TF
and so based on the most recent TF guidelines:
https://docs.google.com/document/d/1bqCxx7QUblrc9q4PIynbJzoCXv248UWBxJa7fguJyXs/edit?pli=1#

**Comment by blazaropinto** [comment]
Hi Paul,

Thank you so much for this information. This GO term is now updated. The changes will be available in the next InterPro release.

Best regards,
Beatriz
