### ISSUE TITLE
protein phosphorylation annotations - review single step BP

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-annotation#4042]
review GO:0006468 protein phosphorylation annotations.

DDB done except autophosprylation. These need to be checked, if biologically relevant.

**Comment by pgaudet** [comment]
For GO:0032147 | activation of protein kinase activity, you could use 'GO:0030295 protein kinase activator activity', if the evidence supports it.

**Comment by pfey03** [comment]
I also have more specific terms like
GO:0043406 | positive regulation of MAP kinase activity
GO:2000481 | positive regulation of cAMP-dependent protein kinase activity

So I have to go into each paper and find details and put everything into extensions. Can I use the regulation extensions? Hardly used so far.

**Comment by pfey03** [comment]
@pgaudet What about GO:0006470 protein dephosphorylation

This seems usually phosphatase activity but if not known we probably used this term. Just 10 DDB annotations, not a big deal for us but lots of IEAs

**Comment by pfey03** [comment]
We also still need to discuss 'protein autophosphorylation' as I have not changed these, we have 22 annotations to autophosphorylation or any children thereof.

**Comment by ValWood** [comment]
I agree with Petra. We will continue to annotate these phenotypes because the community require them. But here we are not describing the normal role of a gene product, we are describing the consequences of mutants (decreased/increased/abolished phosphorylation etc, attached to alleles, not to genes), it's a completely different data type. This isn't in the scope of GO annotation, but it is still necessary curation for MODs (mainly for researchers actively working on the detailed characterization of a gene who need a record of the consequences of loss of/gain of function consequences of different variants). e.g. https://www.pombase.org/term/FYPO:0002494

I like @vanaukenk suggestion that these phenotypes can probably be defined logically by uPHENO using PRO terms, I had wondered about this but had not been able to figure out what would be missing from the design pattern.

**Comment by pfey03** [comment]
I wonder if UPHENO is willing to dive into this just because GO obsoletes terms. But I will suggest it on the next UPHENO call and see what the resonance is

**Comment by pfey03** [comment]
At the UPHENO call today we discussed that I open a ticket and add examples. @ValWood  I can paste the link to ticket here and maybe you can also add some examples. Will do that later today or tomorrow.

Then we'll have a look if patterns can be added to cover them. 

Also @pgaudet the pheno people would love to have a list, even if preliminary of single step processes that are obsoleted. If you have others in mind please let me know. I have a ton of projects right now.

**Comment by ValWood** [comment]
For fission yeast it will  eventually affect be  every term under 
abnormal protein modification (FYPO:0002494)
https://bioportal.bioontology.org/ontologies/FYPO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFYPO_0002494

and every term under 
normal protein modification (FYPO:0002495)
https://bioportal.bioontology.org/ontologies/FYPO?p=classes&conceptid=FYPO:0002495#details

**Comment by pfey03** [comment]
@ValWood But not all under protein modification in GO is single step processes. So it won't affect all, especially metabolic terms are often no single step.

**Comment by ValWood** [comment]
There are a few GO terms under modification that aren't single step and will remain. I think all of the FYPO phenotypes under FYPO:0002494 and FYPO:0002494 will probably be removed though.  I think it should be possible to create logical defs using a combination of MOD/PRO.

**Comment by pgaudet** [comment]
Hi @pfey03 

I made a list of the children of 'GO:0036211 protein modification process' that are likely obsoleted, and those that may be kept: 
https://docs.google.com/spreadsheets/d/1x69ACAZmGJA7vK_UKJp5aFrF41AvHeSL7deSwc3rex0/edit#gid=0

Can you tell how many of these terms are used in FYPO? ie how many children of GO:0036211  are used in logical definitons? We could proceed with the other terms first. 

Thanks, Pascale

**Comment by ValWood** [comment]
Don't worry about FYPO. I can just remove the logical defs until there is another way to construct them.  It's difficult to know how many (there will be lots, but we will figure it out). Obsoletions are less of a problem than merges which can change the meaning.

**Comment by pfey03** [comment]
Many thanks @pgaudet I'll have detailed look and the UPHENO world will really appreciate this!

**Comment by ValWood** [comment]
I agree with most, but I wasn't sure about  sumoylation, neddylation and the ubiquitin ligases as these represent multistep  pathways:

"https://en.wikipedia.org/wiki/SUMO_enzymes#:~:text=SUMO%20pathway%20modifies%20hundreds%20of,than%20ten%20large%2Dscale%20studies.

**Comment by deustp01** [comment]
> sumoylation, neddylation and the ubiquitin ligases

All three and a related ISGylation are represented as multistep processes, one key step of which the the actual transfer of an Ub, SUMO, NEDD, or ISG moiety onto a side chain of the target protein. Removal of all of these modifications is often (generally?) seen as involving one step.

**Comment by pgaudet** [comment]
Thanks for the feedback, I've updated the spreadsheet.

**Comment by pfey03** [comment]
I created a new issue for the obsoletion Table and discussions there instead of here in the phosphorylation ticket: https://github.com/geneontology/go-ontology/issues/23037

**Comment by pfey03** [comment]
@pgaudet any news about GO:0046777 protein autophosphorylation?

Do these need to be replaced by kinase function with itself in the extension? Or what's the plan? 
On the non regulation terms these are the only ones I haven't touched.

**Comment by ValWood** [comment]
>Do these need to be replaced by kinase function with itself in the extension? 
That is what PomBase use.  To me, it would be more confusing to have this single BP term.

**Comment by pgaudet** [comment]
> Update to kinase function with has_input self in extension?

Does that work for you ? @ValWood If the auto-catalysis is important we could also have a separate MF term, I know some people have wanted to express this @ccasalsc @RLovering

**Comment by ValWood** [comment]
I just used the self-substrate but if other want them i have no objection

**Comment by pfey03** [comment]
@pgaudet 
A child of 'regulation of protein phosphorylation' is
GO:0006110 regulation of glycolytic process
However, glycolytic process is not a single step - will this stay with parent 'glycolytic process' and just loose the 'regulation of protein phosphorylation' parent which seems odd anyway?

**Comment by pfey03** [comment]
Except 'protein autophosphorylation' I'm done with all Dicty , also regulation terms and dephosphorylation (the latter all had function terms)

@pgaudet When do we decide what to do with autophosphorylation? New MF? Maybe 'self kinase activity' or is 'auto kinase activity" possible?

**Comment by ValWood** [comment]
Closing in favour of https://github.com/geneontology/go-ontology/issues/26255
