### ISSUE TITLE
Review annotation to GO:0010848 regulation of chromatin disassembly

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4045]
Hi, 

The proposal has been made to obsolete 
GO:0031498 chromatin disassembly and GO:0010848 regulation of chromatin disassembly

There is one annotation left: 

UniProtKB:Q66K74	Microtubule-associated protein 1S		GO:0010848		BHF-UCL	NCBITaxon:9606	IDA		PANTHER:PTHR13843		PMID:12762840	20150226

Maybe move to 'chromosome condensation'? Although the evidence doesn't seem very direct. 

Thanks, Pascale

**Comment by RLovering** [comment]
Annotation deleted
Thanks
Ruth

**Comment by pgaudet** [comment]
Thanks!
