### ISSUE TITLE
IPR023034 mapping too specific? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4051]
* **InterPro ID / label**

IPR023034

* **Example sequences with problematic annotation (ID + gene/protein name):**
surA [P0ABZ6](https://www.uniprot.org/uniprot/P0ABZ6)

* **Description of issue**
* [maintenance of stationary phase (GO:0060274)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0060274) seems too specific for (any) InterPro mapping. I suggest removing it.
* 
Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much for this. I have removed the term as you suggested. The changes will be available in the next InterPro release (88.0).
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks!
