### ISSUE TITLE
regulation of clathrin-dependent endocytosis IEA with IPR045192

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4053]
* **InterPro ID / label**
IPR045192

* **Example sequences with problematic annotation (ID + gene/protein name):**
https://www.pombase.org/gene/SPBC19F8.03c

* **Description of issue**
I think this mapping should be  "clathrin-dependent endocytosis" rather than regulation iof (it is part of the process)

**Comment by blazaropinto** [comment]
Hi Val,

Thank you so much for this. This GO term is now updated. The changes will be available in the next InterPro release.

Best regards,
Beatriz
