### ISSUE TITLE
PTN000550449 regulation of peptide transport 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4054]
* **PTHR ID & PTN node:**

GO:0090087 | regulation of peptide transport | IBA with PTN000550449 , WBGene00015009

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC405.03c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source
I don't think any annotations should be transferred from this publication, it is a screen referring to an intestinal absorption pathway

http://amigo.geneontology.org/amigo/reference/PMID:21980510

The annotation looks odd  applied to a transmembrane transporter most closely related to ER and Golgi nucleotide sugar transporters

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation removed. was probably chosen because was the only term linked to transport.
