### ISSUE TITLE
PTN000168538 Neuroligin

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#4058]
* **PTHR ID & PTN node:**
PTN000168538

P19835
* **Sequences with problematic annotation (ID + gene/protein name):**
P19835 CEL

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Erroneous propagation
CEL should probably not be in this panther family? 
http://www.pantherdb.org/genes/geneList.do?searchType=basic&loggedPrivilege=false&fieldName=all&fieldValue=PTHR43903*&listType=1&organism=Homo%20sapiens

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
I agree. The "CEL node" seems to be in the wrong family. At the PAINT level, I've blocked all neuroligin-related terms. I've also contacted Panther to see if it would be possible to remove it from this family.
