### ISSUE TITLE
Review annotations to DNA repair, DNA incision

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4059]
Dear all,

The proposal has been made to obsolete the following terms:

* GO:0033683 nucleotide-excision repair, DNA incision
* GO:0006295 nucleotide-excision repair, DNA incision, 3'-to lesion
* GO:0006296 nucleotide-excision repair, DNA incision, 5'-to lesion
*  GO:1990731 UV-damage excision repair, DNA incision

see https://github.com/geneontology/go-ontology/issues/22883

Please review your annotations: https://docs.google.com/spreadsheets/d/15co8t7ShRzSzfsP1YfL3kBzTfwgAGR8WqmAKkBSStyU/edit#gid=0

Contributor   (Assigned by) | Annotations
--|--
CACAO | 1
ComplexPortal | 2
EcoCyc | 1
FlyBase | 2
MGI | 2
PomBase | 1 (changed)
SGD | 6
TAIR | 1
UniProt | 18

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

@tberardini i used this as parent: GO:0006289 ! nucleotide-excision repair

**Comment by hdrabkin** [comment]
MGI done; one of the 2 annotations is actually from UniProt via GOA load; cannot change.

**Comment by sandraorchard** [comment]
Complex Portal done.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by Antonialock** [comment]
uniprot done
