### ISSUE TITLE
Reiew annotations to GO:1905616 regulation of miRNA-mediated gene silencing by inhibition of translation 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4060]
Dear all, 

The proposal has been made to obsolete GO:1905616 regulation of miRNA-mediated gene silencing by inhibition of translation , see https://github.com/geneontology/go-ontology/issues/22887

There are 13 annotations, only 1 ZFIN remains to be corrected: https://docs.google.com/spreadsheets/d/1OHc4crHElZ6XEKYnLc-HJU4bIRUOFxDMba5St64E1Ho/edit#gid=0

Thanks, Pascale

**Comment by sramachand** [comment]
ZFIN done
