### ISSUE TITLE
GO class (direct) annotation of VNN1

### ISSUE THREAD

**Issue by Amirhosseinnr** [geneontology/go-annotation#4061]
VNN1 in Homo sapiens annotated wrongly as "negative regulation of oxidative stress-induced intrinsic apoptotic signaling pathway". According to the PMID reference provided, "negative" has to be changed to "positive".

**Comment by pgaudet** [comment]
@RLovering This is a BHF annotation; would you please have a look? There is a mouse EXP and a human IDA from PMID:15282320

Thanks, Pascale
