### ISSUE TITLE
Review annotations to GO:0046999 regulation of conjugation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4062]
Hello @pfey03 

GO:0046999 regulation of conjugation will be obsoleted, see https://github.com/geneontology/go-ontology/issues/22916

There are 2 dicty annotations from  PMID:15817229 that could be moved to GO:0140084 sexual macrocyst formation. 

Thanks, Pascale

**Comment by pfey03** [comment]
@pgaudet these are very old annotations (pre P2GO) and I will have to go to paper. Might be able to use the macrocyst term, will see. Will do it soon.

**Comment by pfey03** [comment]
@pgaudet I changed the annotations and made use of extensions, later in GO-CAM it should come out fine. These annotations were from 2005 by Karen;-)

**Comment by pgaudet** [comment]
Wow !! Thanks @pfey03
