### ISSUE TITLE
IPR011330 - very high-level terms associated with superfamily

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4063]
IPR011330 Glycoside hydrolase/deacetylase, beta/alpha-barrel

This superfamily is associated with the very high-level term: catalytic activity (GO:0003824)

I think that this term is too high-level and, the protein family is too broad to be informative - other proteins in this class map to more informative terms via the subclasses. For inactive members e.g verm E1JI40, causes issues as cannot use NOT annotations to block propagation when at a higher level.

**Comment by sarach06** [comment]
Hi,
Thank you very much. I agree, I have removed the term from this entry; the changes will be available in the next InterPro release (88.0).
Best regards,
Sara

**Comment by hattrill** [comment]
Thanks!
