### ISSUE TITLE
IPR011060 & IPR013785 - high level term associated with superfamilies

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4064]
* **InterPro ID / label**
IPR011060 | Ribulose-phosphate binding barrel
IPR013785 | Aldolase-type TIM barrel

* **Description of issue**
Similar to #4063, both these superfamilies are associated with the high-level GO term "catalytic activity ; GO:0003824", which seems too broad to be useful/accurate for these structural motifs that cover many subclasses.  Better to remove the GO from these terms and rely on more informative terms on subclasses?

**Comment by sarach06** [comment]
Hi,
Yes, I agree, I've removed the term from these entries. The subclases have their respective specific terms associated (when appropriate). Changes will be visible in the next InterPro release (88.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
