### ISSUE TITLE
IPR001509	NAD-dependent epimerase/dehydratase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4065]
* **InterPro ID / label**
IPR001509 | NAD-dependent epimerase/dehydratase

* **Example sequences with problematic annotation (ID + gene/protein name):**
- Fly ND-39 (Q9VPE2)
- Human NDUFA9 (Q16795)

* **Description of issue**
This is associated with the high level GO term 'catalytic activity GO:0003824', which isn't very informative.  Moreover, the motif is found in at least one protein (NDUFA9) that is an accessory subunit of OXPHOS complex I and which is not involved in catalysis.  Maybe remove this GO term?

**Comment by sarach06** [comment]
Hi Steven
Thank you very much. Yes, better to remove the term and avoid this wrong propagation. The changes will be seen in InterPro 88.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!
