### ISSUE TITLE
IPR006047	Glycosyl hydrolase, family 13, catalytic domain

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4066]
* **InterPro ID / label**
IPR006047 | Glycosyl hydrolase, family 13, catalytic domain

* **Example sequences with problematic annotation (ID + gene/protein name):**
- Fly CD98hc (A0A0B4KGE4)
- human SLC3A2 (P08195)

* **Description of issue**
This entry is only associated with the high-level GO term 'catalytic activity', which isn't very informative. Moreover, the two proteins mentioned above are characterized as transmembrane transporters rather than enzymes. So maybe remove this GO term?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. Similar to the previous ticket, I agree and removed the term from this entry. This will be visible in the next release.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks again!
