### ISSUE TITLE
Annotation conundrum GTPase activator or GEF

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4068]
pombe spo14 (A WD repeat protein)
has
<img width="1082" alt="Screenshot 2022-02-25 at 12 41 58" src="https://user-images.githubusercontent.com/7359272/155716935-ea289efd-e125-4cc6-92b4-b7643ca8ffc1.png">

spo14 appear to have 2  orthologs at SGD
1. SEC12 (YNR026C) | Guanine nucleotide exchange factor (GEF)
2. SED4  (YCR067C) | Integral ER membrane protein that stimulates Sar1p GTPase activity; 
( used for the PAINT inference) SGD:S000000663 

This seems like a red flag, (but WD repeat proteins without additional domains  do not usually act as GEFs or GTPase activators, and it would be unlikely for these close paralogs to have different activities).

 First will tag @srengel  to see if both SGD annotations are valid.

**Comment by ValWood** [comment]
I might be wrong, AmiGO has 222 annotations to both GEF and GAP according to matrix.
 5 at SGD

**Comment by ValWood** [comment]
For instance, SGD have BEM2 annotated as a GAP from lots of sources, but InterPro (and PomBase) have annotated the orthologs as GEFs.

**Comment by marcfeuermann** [comment]
I've completely reviewed the annotation for this family and removed the annotation to GEF. We have only an annotation for SEC12 (YNR026C)  which is in a duplication node... not enough evidence to use it for PAINTing.
