### ISSUE TITLE
review annotation to  GO:0000767 cell morphogenesis involved in conjugation 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4070]
MLT1 is annotated to GO:0000767 cell morphogenesis involved in conjugation from PMID:10330137

Please consider the child term: GO:0000753   cell morphogenesis involved in conjugation with cellular fusion)

**Comment by ValWood** [comment]
Or even  most annotation could move down to down to "mating projection formation"  I have a feeling that when sorted out this branch is single inheritance so 
"GO:0000753 cell morphogenesis involved in conjugation with cellular fusion" is probably also an unnecessary grouping term.

**Comment by srengel** [comment]
this annotation no longer exists, and the term has been obsoleted.  closing.
