### ISSUE TITLE
Review annotations to steroid and estrogen receptor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4073]
Hi, 

Some annotations to GO:0030284 estrogen receptor activity and GO:0003707 steroid hormone receptor activity
should actually be to GO:0038054 G protein-coupled estrogen receptor activity

https://docs.google.com/spreadsheets/d/1P5mlOTE2EvrztOfn5AB9R6nyEo4FX3PbDI99dkZ6mHY/edit#gid=0

5 UniProt @Antonialock 
1 ZFIN @sramachand 

Please move the annotations to the correct term. 

Thanks, Pascale

**Comment by sramachand** [comment]
ZFIN done

**Comment by Antonialock** [comment]
fixed

**Comment by pgaudet** [comment]
Thanks!
