### ISSUE TITLE
IPR000182. -> GO:0008080

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4075]
* **InterPro ID / label**
[IPR000182](http://www.ebi.ac.uk/interpro/entry/IPR000182)

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.uniprot.org/uniprot/D5VRB9
https://www.pombase.org/gene/SPAC29A4.20

* **Description of issue**
Does not show protein lysine acetyltransferase activity (PubMed:[30733442](https://www.uniprot.org/citations/30733442)).

At least one member elp3 is not know to have any N-substrates, It is a carboxy acyltransferase according to the Rhea reaction here: https://www.uniprot.org/citations/30733442

I suggest to move up to acetyltransferase activity

**Comment by sjm41** [comment]
Hi
I think this GO annotation needs to go up one more level to GO:0016747 "acyltransferase activity, transferring groups other than amino-acyl groups". IPR000182 is also found in GLYAT enzymes, which are glycine N-acyltransferases (note 'acyl' rather than 'acetyl').  E.g see PMID:28701716

**Comment by sarach06** [comment]
Hi Steven, 
Thank you very much. I have changed the GO term as you suggested. It will be visible in the next release (InterPro 91.0).
Best,
Sara
