### ISSUE TITLE
GO:0003991 | NOT acetylglutamate kinase activity | IBA with PTN000597373 , PTN000597386

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4076]
* **PTHR ID & PTN node:**

pombe ARg11 has

GO:0003991 | NOT acetylglutamate kinase activity | IBA with PTN000597373 , PTN000597386

I made
GO:0003991 | acetylglutamate kinase activity | ISO with S000000871

based on the SGD ortholog.

PAINT makes 

GO:0004042 | acetyl-CoA:L-glutamate N-acetyltransferase activity | IBA with MGI:2387600 , Q8N159 , PTN000597386 , ZDB-GENE-121219-2 , S000003607

S000003607 (ARG2)  is not the  ortholog of pombe arg11 (arg56 is)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC4G9.09c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Looks like erroneous transfer?

**Comment by marcfeuermann** [comment]
Th` shape of he ree made difficult the propagation of the terms and the NOT qualifier. I've fixed it.`
