### ISSUE TITLE
Remove DNA-templated transcription, initiation (GO:0006352) from IPR004823

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4077]
* IPR004823 / TATA box binding protein associated factor (TAF), histone-like fold domain

* Histone-fold IPR009072 is listed as an overlapping family here and so DNA-templated transcription, initiation (GO:0006352) is being propagated to histone family members such as  P84040 His4 in flies.

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have removed the term from IPR004823, which will resolve the erroneous propagation. This will be visible in the next InterPro release (89.0).
Best regards,
Sara

**Comment by hattrill** [comment]
Thank you!
