### ISSUE TITLE
PANTHER:PTN000286904 not 	GO:0007064	 mitotic sister chromatid cohesion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4078]
* **PTHR ID & PTN node:**

GO:0007064 | mitotic sister chromatid cohesion | IBA | Gaudet P et al. (2011)
[FB:FBgn0260987]()
OR
[PANTHER:PTN000286904]()
OR
[PomBase:SPCC338.17c]()
OR
[SGD:S000002161]()
OR
[ZFIN:ZDB-GENE-030131-994]()

[GO:0007064](https://www.pombase.org/term/GO:0007064)	

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC29A10.14
rec8 is meiosis specific cohesin

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
There was such a mess with mitotic vs. meiotic specific cohesins. I've cleaned the family by annotating the parents "cohesin complex" and "sister chromatin cohesion" to the root and restricted the more specific terms to nodes for which we have clear evidence.
