### ISSUE TITLE
IPR001902 not always sulphate transporter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4079]
* **InterPro ID / label**

* **Example sequences with problematic annotation (ID + gene/protein name):**

[IPR001902]does not always seem to be a sulphate transporter

* **Description of issue**

see
S. cerevisiae https://www.yeastgenome.org/locus/YGR125W

and 
  | Ohnishi S, Kawano-Kawada M, Yamamoto Y, Akiyama K, Sekito T. | Related Articles
-- | -- | --
  | A vacuolar membrane protein Vsb1p  contributes to the vacuolar compartmentalization of basic amino acids in  Schizosaccharomyces pombe.
  | Biosci Biotechnol Biochem. 2022 Mar 15;. [Epub ahead of print]
  | PMID: 35289847

for  fission yeast

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. I have removed this term from the entry. This will be visible in the next InterPro release (89.0).
Best,
Sara
