### ISSUE TITLE
PTN000197844 not all mitochondrial

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4083]
* **PTHR ID & PTN node:**

* **Sequences with problematic annotation (ID + gene/protein name):**

pombe cdh1
https://www.pombase.org/gene/SPBC336.02
isn't

GO:0005759 | mitochondrial matrix | IBA with Q9H5Q4 , PTN000197844 , Q8WVM0 , S000004841

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source
https://www.pombase.org/gene_subset/interpro:IPR001737

S000004841 is the ortholog of the other family member mtf1

SPBC336.02 is nucleolar not mitochondrial

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Mitochondrial and nucleolar branches had indeed to be distinguished in animals, fungi and plants. Fixed.
