### ISSUE TITLE
Does IPR001463 have alanine:sodium symporter activity (GO:0015655) ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4086]
* **InterPro ID / label**
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR001463/

* **Example sequences with problematic annotation (ID + gene/protein name):**
[P30143](https://www.uniprot.org/uniprot/P30143), [Aspzo1_0143382](http://www.aspergillusgenome.org/cgi-bin/locus.pl?dbid=Aspzo1_0143382)

* **Description of issue**
I dont have access to the paper cited in the IPR001463 entry, but by the abstract it doesnt seem to be a symporter? 

Actually these are the only annotations to this term if there is no evidence that this activity exists we'll obsolete. 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
I found this reference PMID:30659158 where the sodium/alanine symporter AgcS (Q6LX42) is described and demonstrated that has this activity. Having a look at this entry, it also includes O31464 (Probable sodium/glutamine symporter GlnT) PMID:15995196, so probably change the term to GO:0005283 (amino acid:sodium symporter activity)?
Let me know if you agree.
Thanks,
Sara

**Comment by pgaudet** [comment]
Yes thank you !
