### ISSUE TITLE
PTN000227259  cell motility terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4090]
* **PTHR ID & PTN node:**

GO:0048870 | cell motility | IBA with DDB_G0277833 , PTN000227259 , MGI:101757 , FBgn0011726

* **Sequences with problematic annotation (ID + gene/protein name):**

3 pombe annotations
https://www.pombase.org/term/GO:0048870

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation, but it os odd because this term has taxon restriction 'never in Dikarya'

**Comment by ValWood** [comment]
pld1 |   | IBA with DDB_G0279483 , PTN000431025 | Gaudet P et al. (2011)
- | cdc42 | ↑is_a GO:0016477 | cell migration | IBA with PTN000632904 , MGI:106211 , FBgn0010341 , ZDB-GENE-030131-8783

**Comment by ValWood** [comment]
adf1 | GO:0048870 | cell motility | IBA with DDB_G0277833 , PTN000227259 , MGI:101757 , FBgn0011726 | Gaudet P et al. (2011) | 3

pld1 |   | IBA with DDB_G0279483 , PTN000431025 | Gaudet P et al. (2011)
- | cdc42 | ↑is_a GO:0016477 | cell migration | IBA with PTN000632904 , MGI:106211 , FBgn0010341 , ZDB-GENE-030131-8783

[adf1](https://www.pombase.org/gene/SPAC20G4.06c)	[GO:0048870](https://www.pombase.org/term/GO:0048870)	
[cell motility](https://www.pombase.org/term/GO:0048870)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [DDB_G0277833](http://dictybase.org/gene/DDB_G0277833) , [PTN000227259](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000227259) , [MGI:101757](http://www.informatics.jax.org/accession/MGI:101757) , [FBgn0011726](http://flybase.org/reports/FBgn0011726.html)	[Gaudet P et al. (2011)](https://www.pombase.org/reference/PMID:21873635)	[3](https://www.pombase.org/term/GO:0048870)
[pld1](https://www.pombase.org/gene/SPAC2F7.16c)	
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [DDB_G0279483](http://dictybase.org/gene/DDB_G0279483) , [PTN000431025](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000431025)	[Gaudet P et al. (2011)](https://www.pombase.org/reference/PMID:21873635)
[-]()	[cdc42](https://www.pombase.org/gene/SPAC110.03)	↑is_a [GO:0016477](https://www.pombase.org/term/GO:0016477)	
[cell migration](https://www.pombase.org/term/GO:0016477)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [PTN000632904](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000632904) , [MGI:106211](http://www.informatics.jax.org/accession/MGI:106211) , [FBgn0010341](http://flybase.org/reports/FBgn0010341.html) , [ZDB-GENE-030131-8783](http://zfin.org/ZDB-GENE-030131-8783)

**Comment by marcfeuermann** [comment]
All 3 families have been updated.
