### ISSUE TITLE
Glutaredoxin active site (IPR011767)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4092]
* **InterPro ID / label**
Glutaredoxin active site (IPR011767)

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly [Q9V420]

* **Description of issue**
Current associated GO term is "glutathione-disulfide reductase (NADPH) activity (GO:0004362)"
I think this should be "protein-disulfide reductase (glutathione) activity (GO:0019153)"

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I've replaced the term with GO:0019153. This will be available in the next release.
Best regards,
Sara

**Comment by sjm41** [comment]
Hi Sara
I've been talking with @kaxelsen about Glutaredoxins, and my suggestion above is incorrect.  GO:0019153 (= EC:1.8.4.2) is not appropriate for Glutaredoxins - that GO/EC term is only relevant to a small subset of non-Glutaredoxin proteins, as demonstrated by the facts the GO term has been used with EXP evidence to only 9 proteins in UniProt, and the EC is only on 5 proteins (vertebrate TXNDC12).
Actually, @kaxelsen tells me that Glutaredoxins should be classed as reactants (electron carriers in reactions catalysed by other proteins) and not as enzymes themselves.  (The second paragraph of the IPR011767 entry description basically says the same)

So, please remove GO:0019153 from this entry.

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this information. I removed the term from this entry (this will be visible in InterPro 90.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
