### ISSUE TITLE
Putative nuclease HARBI1-like (IPR045249)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4095]
* **InterPro ID / label**
Putative nuclease HARBI1-like (IPR045249)

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly CG12253 (Q9VKM0), CG7492 (Q9VS98), CG32095 (Q95U65), CG32187 (Q9VVK9), CG43088 (M9NGE9)

* **Description of issue**
Currently associated with GO term "nuclease activity (GO:0004518)"

But as far as I can tell from the InterPro entry and associated refs, there is no experimental evidence for proteins with this domain having nuclease activity - it's just hypothesised.  So it seems a bit premature to put "nuclease activity" on the entry.

Moreover, the child entry "Harbinger transposase-derived nuclease, animal (IPR026103)" does not have the GO term, and one of the associated papers there (PMID: [26642436](https://europepmc.org/abstract/MED/26642436)) says "ALP1 is unlikely to retain nuclease activity"

So I'd suggest removing the 'nuclease activity' term from IPR045249.

**Comment by sarach06** [comment]
Hi,
Thank you very much. I agree, I've removed the term from this entry. The changes will be visible in the next InterPro release (89.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks again.
