### ISSUE TITLE
PTN000458000 not all  preribosome, large subunit precursor 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4097]
* **PTHR ID & PTN node:**

GO:0030687 | preribosome, large subunit precursor | IBA with Q9GZL7 , PTN000458000 , S000005798

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC664.15

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation.
This isn't the S. cerevisiae 
Standard Name
YTM[1](https://www.yeastgenome.org/locus/S000005798#reference) 1
Systematic Name
YOR272W
SGD ID
SGD:S000005798

ortholog  in pombe (that is  https://www.pombase.org/gene/SPAC890.04c)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
The family tree contains a mixture of several unrelated functions and the problematic term has been erroneously propagated to the root. I've reviewed the whole annotation.
