### ISSUE TITLE
PTN000146039 - ribosomal large subunit assembly seems to be a phenotype for ribosomal subunit

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4098]
* **PTHR ID & PTN node:**

GO:0000027	
ribosomal large subunit assembly
IBA with PTN000146039 , S000005589	Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC17A5.03

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source:
from 
Reference: Nam HG and Fried HM (1986) Effects of progressive depletion of TCM1 or CYH2 mRNA on Saccharomyces cerevisiae ribosomal protein accumulation. Mol Cell Biol 6(5):1535-44

 Without L3, apparent synthesis of several 60S subunit proteins diminished, and 60S subunits did not assemble. A similar phenomenon occurred when, in a second strain, synthesis of ribosomal protein L29 was prevented. Loss of 60S subunit assembly was accompanied by a destabilization of some 60S ribosomal protein mRNAs. These data suggest that synthesis of some S. cerevisiae ribosomal proteins may be regulated posttranscriptionally as a function of the extent to which they are assembled.

**Comment by marcfeuermann** [comment]
Fixed. We expect to review all the families with complex assembly terms. However, as we have a lot of higher priority stuff at the moment, this will be done later on.
Thanks,
Marc.
