### ISSUE TITLE
Review annotations to histone phosphorylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4099]
The proposal has been made to obsolete histone phosphorylation & children:
https://github.com/geneontology/go-ontology/issues/23140

_**Edited numbers**_
There are 98 annotations to these terms: 

<body link="#0563C1" vlink="#954F72">

Contributor   (Assigned by)
--
AgBase | 1
AspGD | 1
BHF-UCL | 4 Done
CACAO | 3
CAFA | 5
ComplexPortal | 7
FlyBase | 8
GeneDB | 6
GOC | 2 DONE
MGI | 8
RGD | 6
TAIR | 15
UniProt | 31 DONE
ZFIN | 1

</body>

</html>

Annotations are here: 
https://docs.google.com/spreadsheets/d/1bH8YkoyWklAUEtbYZtxhQLWexFasCmejp4s__K5B4RA/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
@tberardini I could not assign you directly (too many assignees)

**Comment by pgaudet** [comment]
Suggestions for reannotations: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  |   |   |   | Consider: |  
-- | -- | -- | -- | -- | --
GO:0016572 | histone phosphorylation |   |   | GO:0035173 | histone kinase activity
GO:0035404 | histone-serine phosphorylation |   |   | GO:0035174 | histone serine kinase activity
GO:0035405 | histone-threonine phosphorylation |   |   | GO:0035184 | histone threonine kinase activity
GO:0035406 | histone-tyrosine phosphorylation |   |   | GO:0035400 | histone tyrosine kinase activity
  |   |   |   |   |  
GO:1990164 | histone H2A phosphorylation |   |   |   |  
GO:1990853 | histone H2A SQE motif   phosphorylation |   |   |  
GO:0043990 | histone H2A-S1 phosphorylation |   |   | GO:0044024 | histone kinase activity (H2A-S1 specific)
GO:0072370 | histone H2A-S121 phosphorylation |   |   | GO:0072371 | histone kinase activity (H2A-S121 specific)
GO:0035978 | histone H2A-S139 phosphorylation |   |   | GO:0035979 | histone kinase activity (H2A-S139 specific)
GO:1990245 | histone H2A-T120 phosphorylation |   |   | GO:1990244 | histone kinase activity (H2A-T120 specific)
GO:0043991 | histone H2B-S14 phosphorylation |   |   | GO:0044025 | histone kinase activity (H2B-S14 specific)
GO:0043987 | histone H3-S10 phosphorylation |   |   | GO:0035175 | histone kinase activity (H3-S10 specific)
GO:0043988 | histone H3-S28 phosphorylation |   |   | GO:0044022 | histone kinase activity (H3-S28 specific)
GO:0035407 | histone H3-T11 phosphorylation |   |   | GO:0035402 | histone kinase activity (H3-T11 specific)
GO:0072355 | histone H3-T3 phosphorylation |   |   | GO:0072354 | histone kinase activity (H3-T3 specific)
GO:0035408 | histone H3-T6 phosphorylation |   |   | GO:0035403 | histone kinase activity (H3-T6 specific)
GO:0035409 histone H3-Y41   phosphorylation | histone H3-Y41 phosphorylation |   |   | GO:0035401 | histone kinase activity (H3-Y41 specific)
GO:0043989 | histone H4-S1 phosphorylation |   |   | GO:0044023 | histone kinase activity (H4-S1 specific)



</body>

</html>

**Comment by ValWood** [comment]
Note curators should check that histones are shown to be physiological substrates, and not just a generic kinase assay using histones (in which case a less specific annotation is required).

**Comment by pgaudet** [comment]
There are 2 InterPro mappings:  
InterPro:IPR015519  > remove? histone is one of many substrates
InterPro:IPR028772 > remove? histone is one of many substrates

**Comment by blazaropinto** [comment]
Hello,

Thanks a lot for that.

I've been having a look at those two and I'm not sure the histone phosphorylation terms should be removed:

for IPR015519, PMID: 24509855 says "ATM phosphorylates histone H2AX at mitotic kinetochores, and this phosphorylation is required for ... the maintenance of the mitotic checkpoint complex integrity"

for IPR028772 there are several papers that specifically mention the relevance of H3 phosphorylation by proteins in this entry (PMID: 34736137 , PMID: 11352945, PMID: 11856369 , PMID: 11784863 )

Please let me know your thoughts.

Kind regards,

Beatriz

**Comment by Achchuthan** [comment]
GeneDB done!

**Comment by Antonialock** [comment]
uniprot done

**Comment by ValWood** [comment]
hi @blazaropinto - the reason for the removal is that the term "histone phosphorylation" and children will be removed from GO because they represent a  molecular Function in the biological process  ontology.
You should either use  a molecular function term "histone kinase activity" or one of its children, or a term representing the process that the phosphorylation even is controlling.
Please let us know if this is unclear and we can explain better.

(Side Note that we do not usually have 'gene product' specific terms in GO, but because of the histone code we made an exception for histones so that we could capture  residue-specific activities).

**Comment by LiNiMGI** [comment]
mgi done.

**Comment by pgaudet** [comment]
Hi everyone, 

There are still annotations to histone phosphorylation by the following groups: 


Contributor   (Assigned by)
--
AgBase | 1
AspGD | 1
BHF-UCL | 4
CACAO | 3
CAFA | 5
ComplexPortal | 7
FlyBase | 8
GOC | 2
MGI | 8
RGD | 6
TAIR | 15



Thanks, Pascale

**Comment by pgaudet** [comment]
@Antonialock Can you please deal with the CAFA annotations?

**Comment by pgaudet** [comment]
thanks @gthayman

**Comment by tberardini** [comment]
Took a while but done now.

**Comment by Antonialock** [comment]
CAFA fixed

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
