### ISSUE TITLE
Review annotations to GO:0018101 protein citrullination & children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4102]
Dear all,

As part of the project of removing single step BPs from the ontology (and moving them to MFs as appropriate), the proposal has been made to obsolete GO:0018101 protein citrullination & children:
GO:0036414 histone citrullination
GO:0036413 histone H3-R26 citrullination
see https://github.com/geneontology/go-ontology/issues/23154

Annotations are here: https://docs.google.com/spreadsheets/d/1gT-Vn0B3D1KnExWxTaA-PSdD1iC1BI427M7VdfzNL6k/edit#gid=0
Most have been reviewed. Annotations left by group: 

* MGI: 1
* UniProt: 6
* ZFIN: 2
I created a ticket for creating new terms for histone deiminase activity, see #23152  
I suggest people wait for the new MF terms to be available in the annotation tools (sometime next week?) 

Thanks, Pascale

**Comment by Antonialock** [comment]
@pgaudet I thought Id quickly update the rest but I see the comment eg PMID: 16567635 suggested term histone H3-R26 citrullination
but paper says  (H3/Arg-8, H3/Arg-17, and H4/Arg-3)

similarly 
PMID:15339660
suggested term: histone H3-R26 citrullination
but paper:  We show that peptidyl arginine deiminase 4 (PADI4) specifically deiminates, arginine residues R2, R8, R17, and R26 in the H3 tail.

**Comment by Antonialock** [comment]
(so I'm not sure if I am missing something?)

**Comment by pgaudet** [comment]
Hi @sramachand 

The ZFIN annotations can now be edited, the new term has been created  GO:0140794
https://docs.google.com/spreadsheets/d/1gT-Vn0B3D1KnExWxTaA-PSdD1iC1BI427M7VdfzNL6k/edit#gid=0

Thanks, Pascale

**Comment by sramachand** [comment]
I have edited the ZFIN annotations. Thanks
