### ISSUE TITLE
Review annotations to protein glycosylation in cellular component

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4104]
Dear all, 

The following BP terms will be obsoleted, because they conflate BP and CC: 

* GO:0033578 protein glycosylation in Golgi
* GO:0090283 regulation of protein glycosylation in Golgi 
* GO:0090285 negative regulation of protein glycosylation in Golgi
* GO:0090284 positive regulation of protein glycosylation in Golgi
* GO:0033581 protein galactosylation in Golgi
* GO:0033575 protein glycosylation at cell surface
* GO:0033580 protein galactosylation at cell surface 
* GO:0033576 protein glycosylation in cytosol
* GO:0033582 protein galactosylation in cytosol 
* GO:0033577 protein glycosylation in endoplasmic reticulum
* GO:0033579 protein galactosylation in endoplasmic reticulum 

There are 2 MGI annotations left to fix, see https://docs.google.com/spreadsheets/d/1ffkNQagHxNKYASyYheus_jr490bQrs6Rdybii8zQhwQ/edit#gid=0 

(I fixed the UniProt annotations). 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Could not find either annotation in MGI; done
