### ISSUE TITLE
Some PRO entries in the MGI GPI file refer to genes that do not have primary entries

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#4105]
```
✗ curl -L -s http://www.informatics.jax.org/downloads/reports/mgi.gpi.gz | gzip -dc | grep mLy76
PR:000002981    mLy76   lymphocyte antigen 76 (mouse)   mLy76|ter-119|ter119    PR:000000001    NCBITaxon:10090 MGI:MGI:106910  
```

however, this gene isn't in the MGI GPI file

```
✗ curl -L -s http://www.informatics.jax.org/downloads/reports/mgi.gpi.gz | gzip -dc | grep 106910
PR:000002981    mLy76   lymphocyte antigen 76 (mouse)   mLy76|ter-119|ter119    PR:000000001    NCBITaxon:10090 MGI:MGI:106910  
```

I don't think this is a major issue, we don't currently check for dangling parent IDs but it's odd that the gene isn't in the file

I suspect this is because this is a marker gene not tied to a sequence:
http://www.informatics.jax.org/marker/MGI:106910

I do think we might want to exclude this PRO ID and ones like this, if a curator does annotate to it there is no way to trace it to a uniprot or a homolog...

**Comment by nataled** [comment]
The PRO term in question is based on what used to be an entry in UniProtKB. The entry was deprecated by late 2012, prompted by a change in status of the MGI gene from protein coding to non-protein-coding (though by August of 2013 the status had again changed, possibly to its current status as 'other genome feature'). For this reason there's no UniProtKB cross-reference. As I recall, the sequence had no homologs in other species. The PRO term is active because it is(?) in use by CL.

**Comment by ukemi** [comment]
Thanks @nataled. Interesting biology and history of this aside, I think the bottom line here is that we don't want to have entities in our MGI GPI file that don't map up to 'gene' entities to which we can annotate. We should be able to fix this on our end in our GPI file. We are working on it.

**Comment by kltm** [comment]
From managers' call, this is noted elsewhere and can be safely removed from this project.

**Comment by ukemi** [comment]
@hdrabkin pinging you to be sure this gets done on our end. I think you opened a ticket in the MGI tracker.

**Comment by ukemi** [comment]
MGI ticket 854.

**Comment by hdrabkin** [comment]
yes, it was created last week (4/14/22) and is set to high priority, and is in top 10.

**Comment by pgaudet** [comment]
Is this now handled by PRO ? should the GO ticket here be closed?

**Comment by hdrabkin** [comment]
It's MGI's GPI file;  the work ticket is still open (requirements are still pending).

**Comment by ValWood** [comment]
@ukemi  is this ticket still required?

**Comment by ukemi** [comment]
Nope

**Comment by ValWood** [comment]
yay!
