### ISSUE TITLE
Incorrect Unirule mapping:  ribonucleotide reductase (matrix)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4106]
**UniProt UniRule (ID and label):**

GO:0006260 | DNA replication | IEA with UPA00326 | GO_REF:0000041

**Sequences with problematic annotation (ID + gene/protein name):**

**Description of issue**

suc22 P36603  and cdc22 P36602
are causally. upstream of DNA synthesis  (provide precursors), but  I would not annotate to "DNA replication"

**Comment by esperetta** [comment]
Thanks Val. I am looking into this.

**Comment by ValWood** [comment]
This  annotation is because because historically people would say  "regulation of DNA replication"  but this really more "affects" rather than regulates. If you mutate ribonucleotide reductase, the effects are detected/sensed by the DNA damage and/or DNA replication checkpoint machinery and DNA synthesis is halted/slowed, but this isn't really direct regulation of replication. The regulation begins with the checkpoint and ribonucleotide reductase is really only creating the problem that the checkpoint detects.

**Comment by esperetta** [comment]
Thank you Val for explaining this. I showed the issue to Michele as well and I am going to remove the keyword (DNA replication) that it is triggering the identical GO term for these entries but also for others entries in Swiss-Prot so to clean-up all annotations.  I will also add the KW Deoxyribonucleotide synthesis which is mapped to the Go term GO:0009263; deoxyribonucleotide biosynthetic process as it better describes the biological process. Would this be OK?

**Comment by ValWood** [comment]
GO:0009263; deoxyribonucleotide biosynthetic process is much  better!

DNA replication  is defined as beginning with origin recognition, not nucelotide synthesis.

**Comment by esperetta** [comment]
Thanks. I will make the changes and I hope they will already visible in UniProt release 2022_03.

**Comment by esperetta** [comment]
1.
