### ISSUE TITLE
Review annotations to GO:0018298 protein-chromophore linkage and descandants

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4109]
As part of the project of removing single step BPs from the ontology (and moving them to MFs as appropriate), the proposal has been made to obsolete GO:0018298 protein-chromophore linkage and descendants.

Of the 12 terms, 2 have direct annotations.
GO:0018298 protein-chromophore linkage
GO:0019922 protein-chromophore linkage via peptidyl-cysteine

There are 12 EXP annotations to these terms:
Contributor (Assigned by)
AgBase 9
UniProt 3 (1 WormBase)

https://docs.google.com/spreadsheets/d/1Rx3Yj1EfbvJDSE6_lkoT52VXvQh-ZfcrRj3029zM-aY

**Comment by AndreaAuchincloss** [comment]
Hi, Is there a term you want me to replace these 3 UniProtKB annotations with? Or just remove them?

**Comment by pgaudet** [comment]
Hi @raymond91125 I removed all annotations. These were wrong according to GO annotation guidelines, because the proteins annotated were linked to a chromophore, but did not mediate the linkage. 

You can go ahead with the obsoletion. 

Thanks, Pascale

**Comment by raymond91125** [comment]
Thanks.
