### ISSUE TITLE
ARBA:00026354 and ARBA00028243 and ARBA00028932 (uninformative high level processes, also incorrect)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4115]
I would not make either of these annotations for ksg1  a
3-phosphoinositide-dependent protein kinase 

GO:1901564 | organonitrogen compound metabolic process | IEA with ARBA00026354 | GO_REF:0000117 | 1624
GO:0044238 | primary metabolic process | IEA with ARBA00028243 | GO_REF:0000117

They are too high level and it isn't really clear where they come from.

They. seem to be generated from some machine learning method that is applied to uncurated entries but this type of  annotation doesn't  appear to be useful for poorly studied or well-studied prototeomes.

These are the first ones I came across so I  will check some others but these should be removed.

@pgaudet 
@Antonialock 
do you know anything about these?
It would be useful if everyone was informed about new methods so they could review.

**Comment by ValWood** [comment]
@pgaudet  can we block 
GO:1901564 and GO:0044238 for direct annotation?

**Comment by ValWood** [comment]
Personally, I don't think we should include machine learning in GO at present until we know they conform to all GO annotation rules and don't generate false positives. I've spent the last 15 years weeding them out. ;)

**Comment by ValWood** [comment]
All of these:


ksg1 | GO:0044238 | primary metabolic process | IEA with ARBA00028243 | GO_REF:0000117 | 2963
-- | -- | -- | -- | -- | --
pyp1 |   | IEA with ARBA00028243 | GO_REF:0000117
pyp2 |   | IEA with ARBA00028243 | GO_REF:0000117
pyp3 |   | IEA with ARBA00028243 | GO_REF:0000117
swd2 |   | IEA with ARBA00028243 | GO_REF:0000117
wwm1 |   | IEA with ARBA00028243 | GO_REF:0000117
wwm2 |   | IEA with ARBA00028243 | GO_REF:0000117
wwm3 |   | IEA with ARBA00028243 | GO_REF:0000117
SPAC2C4.08 |   | IEA with ARBA00028243 | GO_REF:0000117
SPBC17A3.03c

**Comment by ValWood** [comment]
Also block
for
GO:0043170 | macromolecule metabolic process | IEA with ARBA00026955

gene_association.pombase (11):PomBase	SPBC11B10.08	wwm1	involved_in	GO:0043170	GO_REF:0000117	IEA	ARBA:ARBA00026955	P	WW domain containing conserved fungal protein Wwm1	wwm3	protein	taxon:4896	20220314	UniProt		
gene_association.pombase (11):PomBase	SPBC660.05	wwm3	involved_in	GO:0043170	GO_REF:0000117	IEA	ARBA:ARBA00026955	P	WW domain containing conserved fungal protein Wwm3	wwm1	protein	taxon:4896	20220314	UniProt		
gene_association.pombase (11):PomBase	SPBC660.06	wwm2	involved_in	GO:0043170	GO_REF:0000117	IEA	ARBA:ARBA00026955	P	WW domain containing conserved fungal protein Wwm2		protein	taxon:4896	20220314	UniProt	

It might be true (over 50% of pom be proteins are)  but I would rather keep as "unknown"

**Comment by ValWood** [comment]
I don't appear to be able to 'filter the ARBA: in quickGO, it isn't available  the with/from field filter I wanted to check how many annotations they have pre-PomBase filtering (that would gi ve me an idea about  the overall accuracy). it's difficult though there are no prizes for AI predicting an existing annotation!

**Comment by ValWood** [comment]
More terms that will be flagged as "do not annotate/not for direct annotation"

GO:0043231 	intracellular membrane-bounded organelle (is also not clear that this was correct for ucp12)

GO:0110165  cellular anatomical entity (is also not clear that this was correct for dpp2 which is a protease, this would usually be acting on an anatomical entity rather than part of it). Note that the definition is of "anatomical entity" is 
"with granularity above the level of a protein complex"

**Comment by PedroRaposo** [comment]
Hello,
Protein ksg1 (https://www.pombase.org/gene/SPCC576.15c), or Q12701 (https://www.uniprot.org/uniprotkb/Q12701/entry) does no longer have the 2 GO terms GO:1901564 (organonitrogen compound metabolic process) nor GO:0044238 (primary metabolic process). You can verify in QuickGO (https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q12701).

Using the same resources, I can see that ucp12 does no longer have the GO term GO:0043231 (https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=O94536).

And dpp2 does not have GO:0110165 (https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=O14073).
