### ISSUE TITLE
ARBA:00028984 "mRNA metabolic process" not enough information to make this inference

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4116]
Please remove 

IEA with ARBA00028984
SPCC1739.01
SPAC458.02c

Seems to be based on protein family membership but  members of this family are involved in other processes. There is not enough information to annotate to "mRNA metabolic process"

@pgaudet

**Comment by ValWood** [comment]
Annotations still present.

**Comment by esperetta** [comment]
Hello Val,  thanks for flagging this. I had a look at those 2 entries but I don't see the annotation from ARBA. This is what I see: 

SPCC1739.01 (O74463): the annotation seems to have been removed? 
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=O74463


SPAC458.02c (Q9P3W6) there is an annotation with the GO term GO:0016071 (mRNA metabolic process) that you are questioning, but it is coming from SGD:S000005724 now.
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q9P3W6

I have also checked the Pombe database and I don't think the annotations are there. Maybe something was updated recently?
If you have more example, please let me know. 

In the meantime, I will have a look at the conditions of that ARBA rules.

Many thanks!

**Comment by ValWood** [comment]
That's strancge.

I see an IEA here
https://www.uniprot.org/uniprotkb/O74463/entry with Uniprto source, I assumed it was ARBA. But it isn't in AmiGO, so probably it has been dealt with and this is just a time-lag issue.
Will close.

**Comment by ValWood** [comment]
and for SPAC458.02c it would bo OK anyway...

**Comment by esperetta** [comment]
Regarding the GO still visible in Uniprot, I believe it is a time lag, but I will double check with Alex. Thanks for flagging this!
