### ISSUE TITLE
 ARBA:00028796 remaking out of data removed annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4117]
I *removed* all of these annpotations recently, because  the proteasome isn't really doing the regulation of the transition  here, the  upstream signalling is doing the regulating. So I'm likely pulling back my own out of date annotations that have been previously propagated to other fungi !

pre1 |   | IEA with ARBA00028796 | GO_REF:0000117
-- | -- | -- | --
pre10 |   | IEA with ARBA00028796 | GO_REF:0000117
pre3 |   | IEA with ARBA00028796 | GO_REF:0000117
pre4 |   | IEA with ARBA00028796 | GO_REF:0000117
pre5 |   | IEA with ARBA00028796 | GO_REF:0000117
pre6 |   | IEA with ARBA00028796 | GO_REF:0000117
pre8 |   | IEA with ARBA00028796 | GO_REF:0000117
pre9 |   | IEA with ARBA00028796 | GO_REF:0000117
pts1 |   | IEA with ARBA00028796 | GO_REF:0000117
pup1 |   | IEA with ARBA00028796 | GO_REF:0000117
pup2 |   | IEA with ARBA00028796 | GO_REF:0000117
pup3 |   | IEA with ARBA00028796 | GO_REF:0000117
rpt1 |   | IEA with ARBA00028796 | GO_REF:0000117
rpt2 |   | IEA with ARBA00028796 | GO_REF:0000117
rpt3 |   | IEA with ARBA00028796 | GO_REF:0000117
rpt4 |   | IEA with ARBA00028796 | GO_REF:0000117
rpt5 |   | IEA with ARBA00028796 | GO_REF:0000117
rpt6 |   | IEA with ARBA00028796 | GO_REF:0000117
scl1 |   | IEA with ARBA00028796 | GO_REF:0000117

[pre1](https://www.pombase.org/gene/SPAC31A2.04c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pre10](https://www.pombase.org/gene/SPCC1795.04c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pre3](https://www.pombase.org/gene/SPBC4C3.10c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pre4](https://www.pombase.org/gene/SPBC577.10)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pre5](https://www.pombase.org/gene/SPAC6G10.04c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pre6](https://www.pombase.org/gene/SPBC106.16)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pre8](https://www.pombase.org/gene/SPCC1442.06)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pre9](https://www.pombase.org/gene/SPAC13C5.01c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pts1](https://www.pombase.org/gene/SPAC4A8.13c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pup1](https://www.pombase.org/gene/SPAC23D3.07)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pup2](https://www.pombase.org/gene/SPAC323.02c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[pup3](https://www.pombase.org/gene/SPCC63.12c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[rpt1](https://www.pombase.org/gene/SPBC16C6.07c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[rpt2](https://www.pombase.org/gene/SPBC4.07c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[rpt3](https://www.pombase.org/gene/SPCC576.10c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[rpt4](https://www.pombase.org/gene/SPCC1682.16)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[rpt5](https://www.pombase.org/gene/SPAC3A11.12c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[rpt6](https://www.pombase.org/gene/SPBC23G7.12c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)
[scl1](https://www.pombase.org/gene/SPBC646.16)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with ARBA00028796	[GO_REF:0000117](https://www.pombase.org/reference/GO_REF:0000117)

**Comment by PedroRaposo** [comment]
This rule is going to be removed in the next release (2022_3).
