### ISSUE TITLE
GO:0043414	 macromolecule methylation IEA with ARBA00027232

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4121]
I guess this one isn't such an issue as the term will be obsoleted soon, but I will record everything I filter:
GO:0043414 | macromolecule methylation | IEA with ARBA00027232

**Comment by ValWood** [comment]
This might be out of date.

**Comment by PedroRaposo** [comment]
Hello,
The term has not become obsolete since. When is this going to happen?
If GO is certain this will be obsolete, we can simple delete ARBA00027232 altogether.

**Comment by PedroRaposo** [comment]
I requested this ARBA rule to be deleted.

**Comment by pgaudet** [comment]
Yes this term can be obsoleted.
