### ISSUE TITLE
ARBA: ARBA00026771  nucleic acid metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4125]
SPCC31H12.03c
GO:0090304 | nucleic acid metabolic process | IEA with ARBA00026771

this is too general.  I didn't make an annotation to "transcription elongation" because the role of THO is unclear. It seems to be post-transcription .

**Comment by ValWood** [comment]
This might be out of date.

**Comment by PedroRaposo** [comment]
Hello Val,
I am not sure I follow your query. Do you want the ARBA rule to not propagate to this specific protein? Or to all proteins?
Would you like this ARBA rule to propagate a different GO term, instead?

**Comment by ValWood** [comment]
I think this is OK. The term is a little general to be useful, this does seem to be
[transcription elongation by RNA polymerase II](https://www.yeastgenome.org/go/GO:0006368)
so it isn't incorrect.

Will close.
I notice 

GO:0034641 | cellular nitrogen compound metabolic process
but I will probably propose we block this term for annotation (more likely it will be removed as an unnecessary grouping term -most organic compounds contain nitrogen so it provides no resolution)




[GO:0034641](https://www.pombase.org/term/GO:0034641)	
[cellular nitrogen compound metabolic process](https://www.pombase.org/term/GO:0034641)
