### ISSUE TITLE
ARBA00027653 NOT protein serine/threonine phosphatase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4126]
https://www.pombase.org/gene/SPAC10F6.17c
GO:0004722 | protein serine/threonine phosphatase activity | IEA with ARBA00027653
is actually a
GO:0004741 | [pyruvate dehydrogenase (lipoamide)] phosphatase activity

Most of the annotations I am reporting appear to be annotations that existed relatively recently via other pipelines. So it would be interesting to know what this pipeline is doing that PAINT isn't doing (PAint is a lot more robust and isn't a black-box)

**Comment by PedroRaposo** [comment]
Hello,
What ARBA does is to look for at least 5 Swiss-Prot entries that have one annotation in common and propagate that annotation, to TrEMBL entries with:
1 - Taxonomy that correspond to the common ancestor of all those Swiss-Prot
2 - InterPro signatures in common

In this case, ARBA00027653 is propagating GO:0004722 (protein serine/threonine phosphatase activity) to proteins with 3 sets of characteristics (https://www.uniprot.org/arba/ARBA00027653). The relevant in this situation is the first, where the GO term is going to be propagated into TrEMBL proteins that belong to Fungi, and that have both IPR001932 and IPR015655. This corresponds to 11 Swiss-Prot entries (https://www.uniprot.org/uniprotkb?query=%28xref%3Ainterpro-IPR001932%29+AND+%28xref%3Ainterpro-IPR015655%29+AND+%28taxonomy_id%3A4751%29&facets=reviewed%3Atrue).

For S. cerevisiae entries (P25646, for example) this GO term was added manually from SGD (backed up by a paper), and even for S. pombe (Q09173) the term was added by PomBase (and it also has a paper). So we cannot exclude the GO term from this ARBA rule based on taxonomy. I am going to ask the team if we can stop the propagation of annotation for specific entries. If so, we can stop the propagation of GO:0004722 to O14189 (or whatever else protein you would like us to remove).

**Comment by PedroRaposo** [comment]
Ok. Let's not touch Q09173.
I will send an email to SGD to change O14189's GO term GO:0004741 ([pyruvate dehydrogenase (acetyl-transferring)]-phosphatase activity) to GO:0004721 (phosphoprotein phosphatase activity).
Are there any additional actionable points?

**Comment by ValWood** [comment]
Hang on for this. I already mailed SGD and they say it is serine/threonine, so I opened a ticket to fix the parentage
see
https://github.com/geneontology/go-ontology/issues/26242

**Comment by ValWood** [comment]
Ignore this one. I made a mistake, you are correct and this parentage already exists in GO.
There is absolutely no issue with this prediction, closing.
Sorry about that!

**Comment by ValWood** [comment]
Sorry if this wasn't clear, you can reinstate this rule.
v

**Comment by Antonialock** [comment]
the ARBA is gone but a heads up this still has Rhea (I can review this) + interpro

**Comment by Antonialock** [comment]
Ive updated the rhea and ec for this protein.
