### ISSUE TITLE
Add 'GTPase activity' to 'Beta tubulin' (IPR002453)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4128]
* **InterPro ID / label**
Beta tubulin (IPR002453)

* **Description of issue**
Related to #3619, I think you can add 'GTPase activity' (GO:0003924) to this entry, e.g.  https://www.nature.com/articles/ncb2863#ref-CR5

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I added GO:0003924 to this entry, which will be visible in the next InterPro release (89.0).
Best regrads,
Sara

**Comment by sjm41** [comment]
Thanks Sara.
