### ISSUE TITLE
IPR004045 not  glutathione metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4130]
* **InterPro ID / label**

GO:0006749	glutathione metabolic process IEA with IPR004045
Involved in the conjugation of glutathione to proteins, not in glutathione metabolism

* **Example sequences with problematic annotation (ID + gene/protein name):**

multiple PomBase
https://www.pombase.org/gene_subset/interpro:IPR004045

* **Description of issue**

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. I have removed the term from this entry. The changes will be visible in the next InterPro release (89.0).
Best,
Sara
