### ISSUE TITLE
Remove annotations to GO:0018660 (reaction does not exist).

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#4133]
GO:0018660 Obsolete Rhea ID used in xref: RHEA:16681 (RHEA:16681 has been replaced by RHEA:30595);
But, GO:0052881 already assigned RHEA:30595 using FADH;
Since GO:0018660 was assigned to RHEA 16681 with NAD vs FAD; 3 IEA; suggest obsoletion of GO:0018660
Zfin should remove the three IEA annotations using GO:0018660.

**Comment by sramachand** [comment]
Thanks. These IEA annotations should be "removed" after our next data exchange with UniProt.

**Comment by hdrabkin** [comment]
Ok, I can close this then as 'done'.
