### ISSUE TITLE
Formyl transferase entires IPR002376 & IPR005793

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4135]
* **InterPro ID / label**
Formyl transferase, N-terminal (IPR002376)
Formyl transferase, C-terminal (IPR005793)

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly FBgn0032945/Q9VIC9
human ALDH1L1/O75891

* **Description of issue**
Both these related entries are associated with "hydroxymethyl-, formyl- and related transferase activity (GO:0016742)".
But the description of IPR005793 includes the statement "This family also includes formyltetrahydrofolate dehydrogenases", while IPR002376 has a 'child entry' of "Formyltetrahydrofolate deformylase, C-terminal hydrolase domain"

Since these domains are also found in dehydrogenases (oxidoreductases), I think the transferase GO term should be removed from both entries.

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this, you are right. I've removed the term from these entries and also from the homologous superfamily one (IPR036477), as it includes dehydrogenases as well. I added GO:0008864 "formyltetrahydrofolate deformylase activity" to the child entry Formyltetrahydrofolate deformylase, C-terminal hydrolase domain (IPR041729) and GO:0004479 "methionyl-tRNA formyltransferase activity" to the other child IPR041711 (Methionyl-tRNA formyltransferase, N-terminal domain) (BTW, family entries for members in these entries have the specific GO terms associated). Let me know if you agree.
Many thanks,
Sara

**Comment by sjm41** [comment]
Thanks Sara.  Your edits look good to me.

**Comment by sjm41** [comment]
Hi @sarach06 
I just noticed that the "hydroxymethyl-, formyl- and related transferase activity (GO:0016742)" term needs removing from this superfamily entry:
Formyl transferase, C-terminal domain superfamily (IPR037022)

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much, my apologies that I missed this one. I have removed the term from this entry. This change will be visible in InterPro 94.0.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
