### ISSUE TITLE
 Review annotations to GO:0004744 retinal isomerase activity

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-annotation#4136]
The term  GO:0004744, retinal isomerase activity needs to be obsoleted. The reasons are as follows
1. RHEA has obsoleted the mapped RHEA:24124 : not enough experimental evidence
2. EC: 5.2.1.3  retinal isomerase is a deleted entry.
 'Now known to be catalyzed by a pathway involving multiple steps"

EC 1.1.1.300, NADP-retinol dehydrogenase;   **GO:0052650** NADP-retinol dehydrogenase activity
EC 2.3.1.135, phosphatidylcholine—retinol O-acyltransferase; **GO:0047173** phosphatidylcholine-retinol O-acyltransferase activity and **GO:0102279** lecithin:11-cis retinol acyltransferase activity
EC 3.1.1.64, retinoid isomerohydrolase (two RHEAs)  and 3 GO terms
    **GO:0052885** all-trans-retinyl-ester hydrolase, 11-cis retinol forming activity RHEA:31771
    **GO:0052884** all-trans-retinyl-palmitate hydrolase, 11-cis retinol forming activity RHEA:31775
    **GO:0047376** all-trans-retinyl-palmitate hydrolase, all-trans-retinol forming activity RHEA:13933
  and 
  EC 1.1.1.315, 11-cis-retinol dehydrogenase. no rhea; no go term; will make if requested

GO:0004744 is used in 4 experiment annotations. indicated below. These need to be reannotated to one of the proposed activities

If your paper does not have enough evidence to reannotate, it is suggested that you remove the annotation. 
I have removed both the RHEA as well as the EC already from GO:0004744. Once reannotated, I will put out the obsoletion notice and obsolete. 

FB:0002937  ninaB	neither inactivation nor afterpotential B   GO:0004744	PMID:19020100 FlyBase	

UniProtKB	Q28175	RPE65		GO:0004744	PMID:16096063	IDA		F	Retinoid isomerohydrolase		protein	NCBITaxon:9913	20120412	CACAO		

UniProtKB	Q4R1I4	OPN4		GO:0004744	PMID:15936279	IDA		F	Melanopsin	MOP	protein	NCBITaxon:7741	20061123	UniProt	

MGI	MGI:98001	Rpe65		GO:0004744	MGI:MGI:3790914|PMID:18195010	IMP		F	retinal pigment epithelium 65	A930029L06Rik|Mord1|rd12	protein	NCBITaxon:10090	20081118	MGI

**Comment by hattrill** [comment]
Hi @hdrabkin  - the labels don't automatically flag this up as an issue for groups. Could you tag me and @sjm41 on FlyBase/Dmel enzyme issues?

**Comment by hdrabkin** [comment]
Hi @hattrill ; I did put you as an assignee last night; the labels were made earlier as I made the ticket to remind me who to look up to assign. I see steve assigned himself. But I don't see that you were removed; it's as if I never assigned you. Same thing for one other person I did assign. weird.

**Comment by hattrill** [comment]
Thanks for replying @hdrabkin  Strange indeed. Steven can have this one ;-)

**Comment by sjm41** [comment]
Just added the new GO term (GO:0106422 carotenoid isomerooxygenase activity) to the 4 papers characterising ninaB.

**Comment by Antonialock** [comment]
The uniprot annotation was removed,

**Comment by hdrabkin** [comment]
Done
