### ISSUE TITLE
C. elegans WBGene00004790 annotated to GO:0060047 'heart contraction'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#4137]
PTHR ID & PTN node:[Panther:PTN000986439](http://pantree.org/node/annotationNode.jsp?id=PTN000986439)

Sequences with problematic annotation (ID + gene/protein name):WBGene00004790

Type of Issue: Erroneous propagation

From the subsets workshop at the GOC meeting.

**Comment by marcfeuermann** [comment]
OMG, worms are heartless !! :-)   Thanks for pointing this over-propagation out. All the heart-related terms have been restricted.

**Comment by vanaukenk** [comment]
Thank you @marcfeuermann 
Worms are very nice, but indeed, they lack a heart :-)
