### ISSUE TITLE
C. elegans WBGene00016619 annotated to GO:0050728 'negative regulation of inflammatory response'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#4138]
PTHR ID & PTN node:[Panther:PTN002930557](http://pantree.org/node/annotationNode.jsp?id=PTN002930557)

Sequences with problematic annotation (ID + gene/protein name):WBGene00016619

Type of Issue: Erroneous propagation

Note that there is a taxon constraint of 'only in vertebrate' on the parent term 'GO:0006954' inflammatory response but I don't know if that holds for the regulation children as non-vertebrate gene products might regulate the vertebrate inflammatory response?  Either way, the 'negative regulation of inflammatory response' doesn't make sense for C. elegans.

**Comment by marcfeuermann** [comment]
You are totally right. This is an old annotation done well before we implemented taxon constraints. I've restricted the propagation to vertebrates.

**Comment by vanaukenk** [comment]
Thank you @marcfeuermann !
