### ISSUE TITLE
Dipeptidyl-peptidase 3 (IPR005317)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4139]
* **InterPro ID / label**
Dipeptidyl-peptidase 3 (IPR005317)

* **Description of issue**
Description of entry includes "The dipeptidyl peptidase III aminopeptidases are zinc-dependent enzymes that cleave dipeptides from the N-terminal of peptides"
and it is associated with these two GO MF terms:
[dipeptidyl-peptidase activity (GO:0008239)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008239)
[metalloaminopeptidase activity (GO:0070006)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0070006)

But "metalloaminopeptidase activity" is defined as "Catalysis of the hydrolysis of a **single** N-terminal amino acid residue from a polypeptide chain"
So I think this term should be replaced with "GO:0008235 metalloexopeptidase activity"?

The same issue may exist for similar InterPro entries - I haven't checked.

**Comment by blazaropinto** [comment]
Hi,

Thank you so much for reporting that. I replaced this term. The changes will be available in the next InterPro release.

Kind regards,

Beatriz

**Comment by sjm41** [comment]
Thanks!
