### ISSUE TITLE
PTN000648413 (PTHR24115) - NOT issue

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4141]
* **PTHR ID & PTN node:**
PTN000648413 (PTHR24115) 

* **Sequences with problematic annotation (ID + gene/protein name):**
CG32318 (FBgn0052318/Q7KVC2)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
PTN000648413 (PTHR24115) adds "ATP hydrolysis activity" to CG32318 despite a NOT (IKR) annotation to same term

**Comment by ValWood** [comment]
@marcfeuermann

**Comment by marcfeuermann** [comment]
Corrected. With the changes implemented for the NOT annotations in PAINT, we have some families to re-check.

**Comment by sjm41** [comment]
Thanks marc.
