### ISSUE TITLE
Review annotations to GO:0007571 age-dependent general metabolic decline & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4142]
Dear all, 

The proposal has been made to obsolete: 

GO:0007571 age-dependent general metabolic decline
GO:0001306 age-dependent response to oxidative stress
GO:0001315 age-dependent response to reactive oxygen species
GO:0034614 cellular response to reactive oxygen species
GO:0072353 cellular age-dependent response to reactive oxygen species 
see https://github.com/geneontology/go-ontology/issues/23252

There are 29 manual annotations: 
https://docs.google.com/spreadsheets/d/12MXBnT649PST6sBaX_UKoenDkphHABKrMdkIkvQtrZA/edit#gid=0

* 4 FlyBase
* 3 MGI
* 2 SGD
* 15 UniProt
* 5 WB
* ZFIN

Please remove or rehouse your annotations. 

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by hdrabkin** [comment]
MGI done

**Comment by vanaukenk** [comment]
WB done

**Comment by sramachand** [comment]
ZFIN done.

**Comment by pgaudet** [comment]
UniProt done.

**Comment by pgaudet** [comment]
Hi @hattrill 
Only Fly annotations need to be fixed. I made some suggestions. I will go ahead with the obsoletion, I dont think this term brings a lot to the role of these genes.
