### ISSUE TITLE
mappings to pombe adl1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4144]
* **PTHR ID & PTN node:**

GO:0097681 | double-strand break repair via alternative nonhomologous end joining | IBA with ZDB-GENE-030131-8453 , PTN000048765 , P49916 , MGI:109152

GO:0006273 | lagging strand elongation | IBA with PTN000048696 , cdc17 , S000002323

GO:0043504 | mitochondrial DNA repair | IBA with PTN000048765 , MGI:109152 , P49916

GO:0005737 | cytoplasm | IBA with locus:2199953 , cdc17 , FBgn0262619 , S000002323 , P49916 , PTN005231428

GO:0070421 | DNA ligase III-XRCC1 complex | IBA with PTN000048765 , P49916

[GO:0070421](https://www.pombase.org/term/GO:0070421)	
[DNA ligase III-XRCC1 complex](https://www.pombase.org/term/GO:0070421)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [PTN000048765](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000048765) , [P49916](https://www.uniprot.org/uniprot/P49916)

[GO:0005737](https://www.pombase.org/term/GO:0005737)	
[cytoplasm](https://www.pombase.org/term/GO:0005737)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [locus:2199953](http://arabidopsis.org/servlets/TairObject?accession=locus:2199953) , [cdc17](https://www.pombase.org/gene/SPAC20G8.01) , [FBgn0262619](http://flybase.org/reports/FBgn0262619.html) , [S000002323](https://www.yeastgenome.org/locus/S000002323) , [P49916](https://www.uniprot.org/uniprot/P49916) , [PTN005231428](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN005231428)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC713.06

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I think it would be useful to suppress all mappings to this term. Adl hasn't yet been published, but I know  people have tested it and been unable to get any positive results.
BAsed on its position as a divergent paralog, and an unlikely requirement for DNA application, I think it would be useful to suppress all of the mappings  to this protein until we know more. They are probably more misleading than useful. It is likely to be a specific sub-functionalization.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by pgaudet** [comment]
> I think it would be useful to suppress all mappings to this term

Do you mean you'd like to get rid of IBAs to this gene? 


I fixed the node according to your suggestions. 

Thanks, Pascale
