### ISSUE TITLE
Epoxide hydrolase (IPR016292)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4145]
* **InterPro ID / label**
Epoxide hydrolase (IPR016292)

* **Description of issue**
InterPro description says "This entry includes epoxide hydrolase 1 (EPHX1) from mammals and juvenile hormone epoxide hydrolase (JHEH) from insects."  but then associates the specific GO term "cis-stilbene-oxide hydrolase activity (GO:0033961)" which has only been demonstrated in mammals.  The JHEH GO term is "juvenile hormone epoxide hydrolase activity (GO:0008096)" , and the shared parent term of GO:0033961 and GO:0008096 is "ether hydrolase activity GO:0016803" - so change the GO term on IPR016292 to that?

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have changed the term as you suggested. This will be visible in the next InterPro release (89.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
