### ISSUE TITLE
 glycosylceramide catabolic process  seems incorrrect

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4149]
* **PTHR ID & PTN node:**

GO:0046477 | glycosylceramide catabolic process | IBA with PTN000155295 , MGI:1347344

mel1
maltase.

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by pgaudet** [comment]
Removed.
