### ISSUE TITLE
GO:0010266    response to vitamin B1	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4150]
Please remove (this is just a promoter used in an  expression system). Thiamine  promoter is used for shut -off the experiment has nothing to do with thiamine:

UniProtKB:A1XJ43	14-3-3L	involved_in	GO:0010266    response to vitamin B1	ECO:0000314   IDA	PMID:20519337	
3635 Gossypium hirsutum	AgBase	
UniProtKB:B6REZ8	B6REZ8	involved_in	GO:0010266    response to vitamin B1	ECO:0000314   IDA	PMID:20519337	
3635 Gossypium hirsutum	AgBase

**Comment by pgaudet** [comment]
removed
