### ISSUE TITLE
IPR036556 remove MF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4153]
* **InterPro ID / label**
IPR036556 is mapped to [protein-arginine deiminase activity (GO:0004668)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004668) but the entry states that this is the non-catalytic domain. Please remove the mapping. 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much for this, I have removed the term. The changes will be visible in the next InterPro release (89.0).
bets regards,
Sara

**Comment by pgaudet** [comment]
Thanks @sarach06 !
