### ISSUE TITLE
Acetyl-CoA hydrolase/transferase IPR003702

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4154]
* **InterPro ID / label**
Acetyl-CoA hydrolase/transferase IPR003702

* **Description of issue**
Entry description says family includes several different enzymes:
"This family contains several enzymes which take part in pathways involving acetyl-CoA. Acetyl-CoA hydrolase [3.1.2.1] from yeast catalyses the formation of acetate from acetyl-CoA, CoA transferase (CAT1) [2.8.3] produces succinyl-CoA, and acetate-CoA transferase [2.8.3.8] utilises acyl-CoA and acetate to form acetyl-CoA."

So I don't think it's appropriate to annotate the entry (and thus any proteins with the signature) to both:
acetyl-CoA hydrolase activity (GO:0003986)
acetate CoA-transferase activity (GO:0008775)

(Note the child terms of IPR003702 either have the top-level 'transferase activity' or no GO terms associated)

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have removed the term from this entry and updated/added references to the abstracts. The changes will be available in the next release (InterPro 89.0).
Best regards,
Sara

**Comment by sjm41** [comment]
thanks!
