### ISSUE TITLE
ATP-dependent (S)-NAD(P)H-hydrate dehydratase (IPR000631)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4156]
* **InterPro ID / label**
ATP-dependent (S)-NAD(P)H-hydrate dehydratase (IPR000631)

* **Description of issue**
Description says signature is found in ATP-dependent and ADP-dependent enzymes, but associated GO term is just for the ADP-dependent form.  Change to the shared parent term "GO:0016836 hydro-lyase activity"?

Might also want to change InterPro entry name?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much, I agree with this. I replaced the term for GO:0016836 in this entry and changed the name as you suggested. The changes will be visible in the next release.
Best regards,
Sara
