### ISSUE TITLE
Dihydroorotate dehydrogenase, conserved site (IPR001295)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4160]
* **InterPro ID / label**
Dihydroorotate dehydrogenase, conserved site (IPR001295)

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly su(r) (FBgn0086450/Q9W374)

* **Description of issue**
IPR001295  has the associated GO term dihydroorotate dehydrogenase activity (GO:0004152), but it looks like this site is also found in (at least some) Dihydropyrimidine dehydrogenase enzymes, such as fly su(r).

So I think that GO term needs replacing with the shared parent term "oxidoreductase activity, acting on the CH-CH group of donors (GO:0016627)"

Looks like a similar situation exists for the related entry "Dihydroorotate dehydrogenase domain IPR005720", where the description says "_This entry represents a domain found in the type I dihydroorotate dehydrogenases and dihydropyrimidine dehydrogenase_." and as a result the GO term is (correctly) "oxidoreductase activity, acting on the CH-CH group of donors (GO:0016627)"

**Comment by sarach06** [comment]
Hi,
Thank you very much. You're right, I changed the term as you mentioned.
Best,
Sara
