### ISSUE TITLE
Review annotations to GO:0004448 isocitrate dehydrogenase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4163]
Dear all, 

GO:0004448  isocitrate dehydrogenase activity has 2 children, 
GO:0004449 isocitrate dehydrogenase (NAD+) activity' & GO:0004450 isocitrate dehydrogenase (NADP+) activity'

There are 4 direct EXP annotations to GO:0004448 isocitrate dehydrogenase activity. We have put a 'do not annotate' tag on this term, since the cofactor is (so far) always known. Please reannotate to the more specific term: 

https://docs.google.com/spreadsheets/d/16fXJlkojxilSRtsonhSDQPgbrlB7ijt40S6EaMWga6M/edit#gid=0

* 2 MGI (done)
* 1 FB
* 1 UniProt (done)

Thanks, Pascale

**Comment by hdrabkin** [comment]
mgi done

**Comment by sjm41** [comment]
FB done.

**Comment by pgaudet** [comment]
Thanks!
