### ISSUE TITLE
Betaine-homocysteine S-methyltransferase, BHMT (IPR017226)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4164]
* **InterPro ID / label**
Betaine-homocysteine S-methyltransferase, BHMT (IPR017226)

* **Description of issue**
Entry description concludes with "This entry also includes homocysteine S-methyltransferase (2.1.1.10), which converts S-adenosylmethionine to methionine [5]; selenocysteine methyltransferase (2.1.1.280), which methylates DL- and L-selenocysteine, DL-homocysteine, and DL- and L-cysteine [6]; and S-methylmethionine--homocysteine S-methyltransferase BHMT2 (also 2.1.1.10), which converts converts homocysteine to methionine [4]."

But the associated GO term is the specific "betaine-homocysteine S-methyltransferase activity (GO:0047150)" (=2.1.1.5).

Change to the shared parent term, which I think is GO:0008168 methyltransferase activity?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this, I agree. I have changed the term for GO:0008168. This will be visible in the next release (InterPro 89.0).
Best 
Sara
