### ISSUE TITLE
Nicotinate phosphoribosyltransferase-like, C-terminal (IPR036068)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4167]
* **InterPro ID / label**
Nicotinate phosphoribosyltransferase-like, C-terminal (IPR036068)

* **Description of issue**
This superfamily includes both phosphoribosyltransferases and pyrophosphorylases, but it has the specific GO term "nicotinate-nucleotide diphosphorylase (carboxylating) activity (GO:0004514)" applied to it.   Remove?

**Comment by sarach06** [comment]
Hi,
Many thanks. I have removed the term from this entry and added to the family entry instead (IPR007229). Let me know if you agree. The changes will be available in the next release.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara.

I don't think adding "nicotinate-nucleotide diphosphorylase (carboxylating) activity (GO:0004514)" to IPR007229 is correct.  Looks like that family (from the name, children, associated EC xref and the fly protein matching it (https://flybase.org/reports/FBgn0031589) should get the other GO term involved here, namely nicotinate phosphoribosyltransferase activity (GO:0004516) = EC:6.3.4.21
Maybe the description (that specifically mentions EC:2.4.2.11 needs tweaking?

I'm no expert in the enzymology here.....

**Comment by sarach06** [comment]
I see, I have changed the EC reference to 6.3.4.21 that's why I added the term (not visible right now). Is that ok?
Thanks,
Sara

**Comment by sjm41** [comment]
I think so....
Will you also add nicotinate phosphoribosyltransferase activity (GO:0004516) to IPR007229?

**Comment by sarach06** [comment]
Hi,
Sorry my late reply. Actually, what I meant was that I added GO:0004516 to IPR007229, sorry I didn't explain it clearly (my bad). I didn't add GO:0004514 to this entry. The changes will be visible in InterPro 89.0. Let me know if I miss anything.
Best regards,
Sara

**Comment by sjm41** [comment]
Ah, sounds good, thanks.
