### ISSUE TITLE
mRNA capping enzyme, bifunctional IPR017074

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4169]
* **InterPro ID / label**
mRNA capping enzyme, bifunctional IPR017074

* **Example sequences with problematic annotation (ID + gene/protein name):**
human RNGTT (O60942)
fly mRNA-cap (FBgn0030556/Q9VY44)

* **Description of issue**
I think "polynucleotide 5'-phosphatase activity (GO:0004651)" should be changed to "GO:0140818 mRNA 5'-phosphatase activity" (= EC 3.6.1.74) - this term was just recently created in [#23319](https://github.com/geneontology/go-ontology/issues/23319)

Similarly, I think reference to "RNA 5'-triphosphatase activity ([3.1.3.33])" in the entry description should be changed to "mRNA 5'-phosphatase activity ([3.6.1.74])"

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have updated the EC reference but couldn't add the new GO term as it's not yet available. I left the current one and will change to GO:0140818 when possible.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara
The new term is in QuickGO (https://www.ebi.ac.uk/QuickGO/term/GO:0140818) but I guess InterPro may not access the most up-to-date GO?

**Comment by sarach06** [comment]
Hi Steven,
Just to let you know that I have changed GO:0004651 to GO:0140818 in this entry. It will be available in InterPro 90.0.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!
