### ISSUE TITLE
BMP signaling related annotations

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4186]
Please block these annotations to these nodes, they arise because there a many subtypes of the TGF-beta superfamily pathways and the components are closely related, but exclusive in many cases, to a particulat subtype.

Dad FBgn0020493 - PTN000344419 - is an inhibitory SMAD -  	SMAD (PTHR13703) - so is not part of BMP signaling, but a negative regulator.

daw FBgn0031461 - PTN000932183  -  	TGF-BETA FAMILY (PTHR11848) - is not part of BMP signaling in Dmel, it is part of the activin pathway

Smox FBgn0025800 - PTN000344419; SMAD (PTHR13703) 
it is not part of BMP signaling in Dmel, it is part of the activin pathway

---------------------
And for 
PTN005316910 CROSSVEINLESS 2 (PTHR46698)
Don't think that this gene should be used to propagate these specific terms as I do not think that this can be said to be conserved - is propagated to orthologs that don't have a great deal of sequence conservation except for the VWFC domain (http://www.ebi.ac.uk/interpro/entry/InterPro/IPR001007/).

BMP binding
BMP receptor binding
positive regulation of BMP signaling pathway

In Dmel:
FBgn0051869 CG18499
FBgn0039257 tnc
FBgn0051869 CG31869
FBgn0032414 CG17211

**Comment by marcfeuermann** [comment]
Hi Helen,
I've updated all 3 families. These "signaling families" are huge and complex, and primary annotation goes to all directions, which does not help. Thanks to your expertise, we can improve their PAINTing. As mentioned during the GO meeting, we will focus our next efforts on these families... I think the best would be to propagate less specific terms. 
Thanks again.
Marc.

**Comment by hattrill** [comment]
Thanks!
