### ISSUE TITLE
Incorrect UniProt KW mapping:  KW-0333 Golgi

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4188]
* **UniProt KeyWord (ID and label):**

GO:0005794 | Golgi apparatus | IEA with KW-0333 | GO_REF:0000043

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC28F2.11

Q9USU7

* **Description of issue**

Is upstream binding transcription factor, RNA polymerase I specific, Hmo1 (nucleolarr)?

**Comment by sylvainpoux** [comment]
Hi Val,

sorry for the late reply, I was absent last week. The Golgi apparatus annotation comes from PMID:16823372. However, while looking more in detail in their table, it looks like authors are unsure about this. I will therefore remove this annotation

Thanks for pointing this out

Sylvain

**Comment by ValWood** [comment]
thanks!
