### ISSUE TITLE
Incorrect UniProt KW mapping: KW-0012 acetyltransferase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4189]
* **UniProt KeyWord (ID and label):**

ggt1 | GO:0016746 | acyltransferase activity | IEA with KW-0012 | 93
ggt2 |   | IEA with KW-0012

* **Sequences with problematic annotation (ID + gene/protein name):**

[ggt1](https://www.pombase.org/gene/SPAC664.09)	[GO:0016746](https://www.pombase.org/term/GO:0016746)	
[acyltransferase activity](https://www.pombase.org/term/GO:0016746)
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with [KW-0012](https://www.uniprot.org/keywords/KW-0012)	[93](https://www.pombase.org/term/GO:0016746)
[ggt2](https://www.pombase.org/gene/SPAC56E4.06c)	
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with [KW-0012](https://www.uniprot.org/keywords/KW-0012)

* **Description of issue**

These are gamma-glutamyltranspeptidases

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprot/Q9US04
https://www.uniprot.org/uniprot/O14194

**Comment by Antonialock** [comment]
hmmm I don't know

 according to https://enzyme.expasy.org/EC/3.4.19.13
This is a bifunctional protein that also has the activity of EC [2.3.2.2](https://enzyme.expasy.org/EC/2.3.2.2).
The enzyme binds its substrate by forming an initial gamma-glutamyl- enzyme intermediate, releasing the L-cysteinylglycine part of the molecule.
The enzyme then reacts with either a water molecule or a different acceptor substrate (usually an L-amino acid or a dipeptide) to form L-glutamate or a product containing a new gamma-glutamyl isopeptide bond, respectively.


and  https://enzyme.expasy.org/EC/2.3.2.2
The mammlian enzyme is part of the cell antioxidant defense mechanism.
    It initiates extracellular glutathione (GSH) breakdown, provides cells with a local cysteine supply and contributes to maintain intracelular GSH levels.
    The protein also has EC [3.4.19.13](https://enzyme.expasy.org/EC/3.4.19.13) activity.
    The enzyme consists of two chains that are created by the proteolytic cleavage of a single precursor polypeptide.
    The N-terminal L-threonine of the C-terminal subunit functions as the active site for both the cleavage and the hydrolysis reactions.
