### ISSUE TITLE
ARBA: ARBA00026310 (annotations to BP modification terms are being removed)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4190]
We don't use these terms (All mappings to biological process (BP) for modification should be removed)

filtering
clr4 | ↑is_a GO:0051567 | histone H3-K9 methylation | IEA with ARBA00026310

**Comment by PedroRaposo** [comment]
By BP do you mean PomBase database?

**Comment by ValWood** [comment]
edited above.

We are in the process of removing a large number of terms from GO because they represent Molecular function terms in the Biological Process ontology. The first stage in this process is to remove the annotations before the terms are obsoleted.

This applies to most (but not all) terms in this branch of the Biological Process ontology.
https://www.ebi.ac.uk/QuickGO/term/GO:0036211

**Comment by PedroRaposo** [comment]
So, do you suggest the suppression of propagation (from ARBA) of all GO terms related to biological processes (BP) for modification? Or only specifically this rule ARBA00026310?

**Comment by PedroRaposo** [comment]
In our ARBA rules, we can restrict our propagation by taxonomy, or remove the rule altogether, but we cannot remove the propagation on a protein by protein basis, if that is what you were mentioning.
Maybe we could exclude rules containing BP GO terms from being propagated into S. pombe.

**Comment by ValWood** [comment]
The tickets I'm opening aren't  PomBase specific, they will apply across that annotation corpus. But there could be many reasons for errors/problems. For example annotations based on out of data annotation, out of date science, more stringent GO practices etc. etc.

**Comment by PedroRaposo** [comment]
We expect the removal of this ARBA rule in the next release (2022_3).
