### ISSUE TITLE
ARBA:ARBA00027284 GO:0032784 | regulation of DNA-templated transcription, elongation (old annotation)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4191]
https://www.pombase.org/gene/SPBC21C3.16c
GO:0032784 | regulation of DNA-templated transcription, elongation | IEA with ARBA00027284

this is now annotated to 

co-transcriptional chromatin reassembly
--

[co-transcriptional chromatin reassembly](https://www.pombase.org/term/GO:0140673)
not to regulation of elongation

**Comment by ValWood** [comment]
There will be a lot of problems with "regulation of" ....terms generally because biologists use the phrase "regulation" often to mean "affects". In GO we use it in the strictest sense to mean "control"

From the GO perspective this gene  is part_of the transcription elongation process (specifically "co-transriptional chromatin reassembly"), yes it 'affects' this process, but it isn't controlling it.

So the information in the paper is still correct, but we are looking through a slightly more refined lens with more  detailed mecchanistic information.

**Comment by ValWood** [comment]
Actually I do not see the paper state that these are involved in regulation of elongation. The state that they  are
"Spt4, Spt5, and Spt6 have characteristics of general transcription-elongation factors"

**Comment by PedroRaposo** [comment]
Thank you for the explanation. In the paper I could see that it stated: "These new studies, taken together with earlier work, portray Spt4, Spt5, and Spt6 as general transcription-elongation factors, controlling transcription both positively and negatively in important regulatory and developmental roles".

**Comment by pgaudet** [comment]
Yes you have - how authors use 'regulates' or 'regulation' is often quite different from the GO definition, which is a lot narrower - a regulator should act directly on a protein in a way that is rate-limiting on the pathway. 

Thanks, Pascale

**Comment by PedroRaposo** [comment]
Hello,
This ARBA rule stopped existing, probably due to updates on Swiss-Prot entries.
But the GO term GO:0032786 (positive regulation of DNA-templated transcription, elongation) is still being propagated through InterPro family IPR009287 (https://www.ebi.ac.uk/interpro/entry/InterPro/IPR009287/), so I will send an email to InterPro for them to stop associating this GO term to that family.

**Comment by ValWood** [comment]
Removing ARBA, tagging InterPro

**Comment by ValWood** [comment]
Here the. same applies to 
GO:0006355 | regulation of DNA-templated transcription | IEA with ARBA00028138
Spt4 https://www.pombase.org/gene/SPBC21C3.16c

**Comment by PedroRaposo** [comment]
I cannot see this GO term GO:0006355 in this protein (https://rest.uniprot.org/uniprotkb/Q9P7K8.txt). Am I missing something?
Also, it would be easier to determine which InterPro signature this term should be removed. This is because ARBA (https://www.uniprot.org/arba/ARBA00028138) is touching multiple signatures.

**Comment by ValWood** [comment]
I could see it here https://www.pombase.org/gene/SPBC21C3.16c yesterday, but I filtered it so it has gone today.
There was a new GO release a couple of days ago so maybe this was already cleaned up. There has been quite  a bit of effort to remove the "regulation" terms when things are "part_of"

Oddly there is a PAINT annotation in AmiGO
https://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC21C3.16c
from [PANTHER:PTN000306261](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000306261)
I will check that that is removed.

**Comment by ValWood** [comment]
I see it in QuickGO
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q9P7K8&aspect=biological_process
I don't know why it isn't in the Swiss-Prot entry?

**Comment by PedroRaposo** [comment]
Sorry Val, my mistake - Q9P7K8 in fact has the GO term GO:0006355.
Yes, UniProt does not have the same data as QuickGO, as we filter out the less relevant GO terms and only keep the most important ones. But the complete list of GO terms are always present in QuickGO.
For this protein, the GO term was also added by the InterPro signature IPR009287 (which we already reported to InterPro).

**Comment by pgaudet** [comment]
@sarach06 @blazaropinto 
Can you please have a look at IPR009287?

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I had a look at this family last week, when Pedro sent and email. Ther GO term has been removed, and this will be visible in InterPro 97.0.
Best wishes,
Sara

**Comment by pgaudet** [comment]
Thanks @sarach06 !

**Comment by pgaudet** [comment]
Looks like everything is addressed and annotations will be fixed when the updates trickle through the various pipelines.
