### ISSUE TITLE
PTN000329686 box H/ACA telomerase RNP complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4193]
* **PTHR ID & PTN node:**

I have a single mapping of a box H/ACA telomerase RNP complex component to
GO:0090661 | box H/ACA telomerase RNP complex | IBA with PTN000329686 , Q9NPE3

But is this a functional complex(I though it was an assembly intermediate, so I wouldn't annotate to a complex term)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAP27G11.13c

**Comment by ValWood** [comment]
Based on this term, human telomerase becomes annotated to the parent  term " box H/ACA telomerase RNP complex" which looks very odd...

**Comment by ValWood** [comment]
I looked at a couple of papers and temomerase RNA is described as a substrate?

**Comment by RLovering** [comment]
The telomerase RNA is an essential template which is required/essential for telomere replication see  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4993324/ 

assuming this is the RNA you are referring too, it is confusing as you also do not seem to want telomerase to be annotated to the box H/ACA telomerase RNP complex term, which I don't understand as telomerase is in the complex name so shouldn't it be in the complex?

**Comment by ValWood** [comment]
Ignore sorry. I was reading this as 
box H/ACA snoRNP complex
not
box H/ACA RNP complex

[box H/ACA telomerase RNP complex
 does have a parentage to 
is_a [sno(s)RNA-containing ribonucleoprotein complex]

which is why I was confused. It doesn't contain sno's does it?



[box H/ACA snoRNP complex](https://www.pombase.org/term/GO:0031429)

**Comment by pgaudet** [comment]
Hi, I removed GO:0090661 | box H/ACA telomerase RNP complex, as this dont seem to be always the case. 
I kept GO:0031429  box H/ACA snoRNP complex. 

Thanks, Pascale
