### ISSUE TITLE
Review annotations to GO:0070816 phosphorylation of RNA polymerase II C-terminal domain & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4194]
Dear all, 

To remove single step processes from the ontology, the proposal has been made to obsolete GO:0070816 phosphorylation of RNA polymerase II C-terminal domain & children. Since this is a highly regulated 'RNA polymerase II large subunit CTD code' , we will move these as MF (details in https://github.com/geneontology/go-ontology/issues/23389) 

BP annotations need to be fixed: 
https://docs.google.com/spreadsheets/d/1yDggiAuZ50WS9rFy75pwSjisVMB3MWNb3iaxA9tuYiE/edit#gid=0

Thanks, Pascale

**Comment by ValWood** [comment]
Long gone
