### ISSUE TITLE
Rfam2GO issues for RF03419 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4195]
Hi @AntonPetrov,

Some issues with IEA annotations to these ncRNA gene products:
URS000078D33A_7227	microRNA dme-mir-998 precursor
URS00007C56B7_7227  mir-998	
URS0000EFBF03_7227  Dme-Mir-29-P1d stem-loop	
URS000230EC89_7227	Dme-Mir-29-P2h_pre stem-loop

All are annotated with "GO:0045742 positive regulation of epidermal growth factor receptor signaling pathway IEA with Rfam:RF03419

These are all precursors/processed precursors. We have associated GO:0045742 positive regulation of epidermal growth factor receptor signaling pathway with the precise miRNA : URS00002A1726_7227 - I assume this is where the annotation for the Rfam2GO annotation was originally taken from.

However, I don't think that this sort of IEA propagation is appropriate as our annotation guidelines are to annotate to the mature miRNA (5p or 3p) where we can rather than the immature precursors. Also, this is quite a specific annotation which is probably not a good idea to propagate via IEA.

[Oddly, for one, on the RNAcentral site, this entry is given IGI evidence code for the annotation:
https://rnacentral.org/rna/URS000078D33A/7227
which is strange (cf https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=URS000078D33A_7227)]

**Comment by pgaudet** [comment]
Thanks @AntonPetrov , I'll note this. All the best for your new project!

**Comment by hattrill** [comment]
Hi @AntonPetrov - I thought that we had said "goodbye" to you at the last RNAcentral but couldn't remember what your leaving date was. Hope all is going well and don't get haunted by too many RNA ghosts!

**Comment by AntonPetrov** [comment]
Thanks Helen and Pascale! I don't mind ghosts 👻 

Good luck with your work as well!

**Comment by blakesweeney** [comment]
Hi Helen, thanks for pointing out these issues. We will work on fixing them on the Rfam and RNAcentral side now.

**Comment by blakesweeney** [comment]
We've removed GO:0045742 from RF03419 and from RNAcentral, so it should be fixed in the next Rfam and RNAcentral releases.

**Comment by pgaudet** [comment]
Thanks!
