### ISSUE TITLE
GMP synthetase ATP pyrophosphatase domain (IPR025777)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4197]
* **InterPro ID / label**
GMP synthetase ATP pyrophosphatase domain (IPR025777)

* **Description of issue**
Entry says "GMPS consists of two catalytic units, glutamine amidotransferase (GATase) and ATP pyrophosphatase (ATP-PPase). GATase hydrolyzes glutamine to yield glutamate and ammonia, **while ATP-PPase utilises ammonia to convert adenyl xanthosine 5'-monophosphate (adenyl-XMP) into GMP**. The two catalytic units are either encoded by a single gene (two-domain type) in eucaryotes, bacteria, and some archaea, or encoded by two separate genes (two-subunit type) in other archaea."

One the references (PMID: [19900465](https://europepmc.org/abstract/MED/19900465)) explains the overall reaction like this:
_GMPS belongs to the class I glutamine amidotransferase (GATase) family and consists of two catalytic units, GATase and ATP pyrophosphatase (ATPPase):
(1) GATase: L-glutamine + H2O → L-glutamate + NH3
(2) ATPPase: XMP + Mg-ATP → adenyl-XMP intermediate + pyrophosphate + Mg2+
(3) adenyl-XMP intermediate + NH3 → GMP + AMP_

IPR025777 (which is specifically for the ATP-PPase unit) currently has a GO association of "pyrophosphatase activity (GO:0016462)".  I think this should be removed.  Instead, I think you could add "GMP synthase activity (GO:0003921)", which has definition "Catalysis of the reaction: ATP + XMP + NH4(+) = AMP + diphosphate + GMP + 2H(+)."

Consistent with that suggestion, GO:0003921 maps to RHEA:18301 (https://www.rhea-db.org/rhea/18301), and RHEA indicates that RHEA:18301 and RHEA:15889 together comprise the overall GMPS reaction described in RHEA:11680.

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. I have updated the term as you suggested; the changes will be visible in the next release (InterPro 90.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!
