### ISSUE TITLE
Load the non-mouse annotations made by MGI curators

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-annotation#4198]
Note this is independent of the mouse curation stream, but will be needed if these annotations need to be modified. I suspect this will be the best place for this ticket as one blocker will be identifers that are present in this file that are missing in Noctua.

These are available as a gaf file here:
http://www.informatics.jax.org/downloads/custom/gene_association.mgi_nonmouse

**Comment by pgaudet** [comment]
ping @krchristie @alexsig - where does this stand? 
My understanding is that Alex is ready to do this; or has it been done already?

**Comment by krchristie** [comment]
> ping @krchristie @alexsign - where does this stand? My understanding is that Alex is ready to do this; or has it been done already?

I have not heard anything further about this since my previous comment on this ticket.

**Comment by alexsign** [comment]
@krchristie @pgaudet MGI non-mouse data is added to Prortein2GO. Karen now has an access to MGI internal source as well. I'm gonna post relevant syntax check bellow in case data can be fixed and send to me for an additional upload.

**Comment by alexsign** [comment]
-- Report on the use of unknown, deleted and secondary UniProt accessions
ENTITY_ID    B4DVB8    SECONDARY Q15717
ENTITY_ID    B7ZLX0    SECONDARY P06756
ENTITY_ID    C9JQA1    SECONDARY O60828
ENTITY_ID    D3ZGS8    DELETED	 n/a
ENTITY_ID    D3ZS17    DELETED	 n/a
ENTITY_ID    D3ZYA3    DELETED	 n/a
ENTITY_ID    D4A0I3    DELETED	 n/a
ENTITY_ID    D4A0I6    DELETED	 n/a
ENTITY_ID    D4A9H4    DELETED	 n/a
ENTITY_ID    E1BQZ5    DELETED	 n/a
ENTITY_ID    E1BXZ0    DELETED	 n/a
ENTITY_ID    E2RJ37    DELETED	 n/a
ENTITY_ID    E2RJ63    DELETED	 n/a
ENTITY_ID    F1LXE1    DELETED	 n/a
ENTITY_ID    F1M9T0    DELETED	 n/a
ENTITY_ID    F1MA67    DELETED	 n/a
ENTITY_ID    F1NF99    DELETED	 n/a
ENTITY_ID    F1NYG0    DELETED	 n/a
ENTITY_ID    F1R219    DELETED	 n/a
ENTITY_ID    F6U9N7    SECONDARY F6VVA5
ENTITY_ID    F7F983    SECONDARY B1WC73
ENTITY_ID    H9YXW8    SECONDARY F7FKH9
ENTITY_ID    O70485    SECONDARY Q9R283
ENTITY_ID    O88860    SECONDARY Q9QX15
ENTITY_ID    O95095    SECONDARY Q92624
ENTITY_ID    O95742    SECONDARY Q4U2R8
ENTITY_ID    P01343    SECONDARY P05019
ENTITY_ID    P08107    SECONDARY P0DMV8, P0DMV9
ENTITY_ID    P19245    SECONDARY P0A6G7, P0A6G8, P0A6G9, P0A6H0
ENTITY_ID    P26442    SECONDARY Q9UKV5
ENTITY_ID    P62158    SECONDARY P0DP23, P0DP24, P0DP25
ENTITY_ID    Q13161    SECONDARY Q13873
ENTITY_ID    Q17RQ6    SECONDARY Q9NQ66
ENTITY_ID    Q5I0H1    SECONDARY G3V928
ENTITY_ID    Q5JUN8    DELETED	 n/a
ENTITY_ID    Q5TAM4    SECONDARY O75829
ENTITY_ID    Q641I8    SECONDARY P70005
ENTITY_ID    Q6ICR7    SECONDARY O00585
ENTITY_ID    Q80ZH4    SECONDARY A2A259
ENTITY_ID    Q8N133    SECONDARY Q96RA2
ENTITY_ID    Q91VU9    SECONDARY O88630
ENTITY_ID    Q96AA4    SECONDARY Q9BV10
ENTITY_ID    Q9H9U1    SECONDARY Q9BW27
ENTITY_ID    Q9HC28    SECONDARY Q9BZC7
ENTITY_ID    Q9Y307    SECONDARY Q8N9N2
ENTITY_ID    R9WAE9    SECONDARY Q5VYJ5
WITH_STRING  D3ZYA3    DELETED	 n/a
WITH_STRING  F1NYG0    DELETED	 n/a
WITH_STRING  P22445    SECONDARY B0BCM3, P0CE16


-- Report on the use of retracted publications as references
PMID:23862016				      2
PMID:15087446				      2
PMID:15687497				      2

**Comment by alexsign** [comment]
SUMMARY
=======

Number of lines processed: 7086
Total number of annotations: 7083
Number of annotations assigned by MGI: 7083
Total number of problems detected: 311
Number of annotations with error "Obsolete GO ID": 2
Number of annotations with error "Restricted GO term: gocheck_do_not_annotate": 34
Number of annotations with error "Restricted GO term: gocheck_do_not_manually_annotate": 2
Number of annotations with error "Secondary GO ID": 9
Number of annotations with error "Unsupported / missing reference": 80
Number of annotations with error "Unsupported / unmapped identifier": 2
Number of annotations with error "Unsupported evidence code": 74
Number of annotations with error "With/from contains one or more invalid components": 107
Number of annotations with error "With/from is mandatory for this evidence code": 1
Number of annotations excluded with evidence <unset>: 74
Total number of warnings: 74
Number of annotations with warning "No usage constraint found for this evidence code": 74
Number of annotations with no errors: 6843
[MGI_P2GO_syntax_check.log](https://github.com/geneontology/go-annotation/files/9167006/MGI_P2GO_syntax_check.log)

**Comment by ukemi** [comment]
I believe that these have been loaded and @krchristie is working on the QC. I am closing this ticket.
