### ISSUE TITLE
1-Cys peroxiredoxin (IPR045020)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4203]
* **InterPro ID / label**
1-Cys peroxiredoxin (IPR045020)

* **Description of issue**
Current GO-MF term on this entry is thioredoxin peroxidase activity (GO:0008379), but from the term name and EC xrefs, I think this should be changed to GO:0051920 peroxiredoxin activity

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have updated the term in this entry, which will be visible in the next InterPro release (90.0).
Best,
Sara

**Comment by sjm41** [comment]
thanks!
