### ISSUE TITLE
PTN000885245 smo mixed regulation and part of annotations to pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4204]
* **PTN000885245 &  PTN000885245 node:**

* **Has positive regulation of smoothened signaling pathway and smoothened signaling pathway annotations.
Should just be smoothened signaling pathway.**

This has been propagated from:
MGI=MGI=108075|UniProtKB=P56726 @ukemi 
DANRE|ZFIN=ZDB-GENE-980526-89|UniProtKB=Q5RH73 @doughowe 

Which should probably be up dated to 'smoothened signaling pathway'

**Comment by marcfeuermann** [comment]
Indeed... and we have the same concern with the wnt signaling pathway within the same family. I've updated the PAINTing and so could remove the PAINT label. Feel free to close this ticket (or not) when you consider everything is solved.

**Comment by doughowe** [comment]
I've updated the corresponding annotation for DANRE|ZFIN=ZDB-GENE-980526-89|UniProtKB=Q5RH73
in Noctua.

**Comment by marcfeuermann** [comment]
Still many regulation terms (sometimes both BP and regulation of BP), but none is propagated anymore by PAINT.
