### ISSUE TITLE
PTN002449977  THIOREDOXIN-DEPENDENT PEROXIDE REDUCTASE (PTHR42801)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4206]
* **PTHR ID & PTN node:**
PTN002449977  THIOREDOXIN-DEPENDENT PEROXIDE REDUCTASE (PTHR42801)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Erroneous source

This node is annotated with "thioredoxin peroxidase activity" (GO:0008379).
But I think it should use the new term thioredoxin-dependent peroxiredoxin activity (GO:0140824) = EC:1.11.1.24

Source annotations are:
PTN000841000 (ECOLI|EcoGene=EG10108|UniProtKB=P0AE52)
PTN000074145 (YEAST|SGD=S000001272|UniProtKB=P40553) @srengel 
PTN000074148 (SCHPO|PomBase=SPBC1773.02c|UniProtKB=O94561) @ValWood 
PTN000074033 (DROME|FlyBase=FBgn0038519|UniProtKB=Q9VEJ0) **<- I've changed this one**
PTN002533774 (HUMAN|HGNC=9354|UniProtKB=P30048) **<- disputed in P2GO**

**Comment by sjm41** [comment]
related to #4205

**Comment by ValWood** [comment]
Does the same apply to pombe tpx1 from the same paper? or is it just bcp1/SPBC1773.02c

**Comment by sjm41** [comment]
@ValWood I only mentioned the one on the PAINT node I encountered, but yes, from reading the abstract of PMID: 20356456 and checking the EC number on the UniProt entry, the same applies to tpx1. The abstract suggests the same is also true of gpx1 (though you have annotated a "NOT thioredoxin peroxidase activity" for that one?)

**Comment by ValWood** [comment]
OK thanks done.

**Comment by sjm41** [comment]
Closing this.
Turned out the real issue here is a relationship issue in the GO, compounded by ambiguous names - ticket to fix this is https://github.com/geneontology/go-ontology/issues/23121#issuecomment-1161798387

Basically, "thioredoxin peroxidase activity" (GO:0008379) is a more specific term than "thioredoxin-dependent peroxiredoxin activity (GO:0140824) = EC:1.11.1.24", so the former should be a child of the latter.

Should use "thioredoxin peroxidase activity" when substrate is specifically H2O2
and use "thioredoxin-dependent peroxiredoxin activity" when there is broader substrate specificity for any hydroperoxide (e.g. cumene hydroperoxide. text-butyl hydroperoxide, H2O2)

@ValWood The changes you made are still correct - PMID: 20356456 tested all three hydroperoxides I mentioned above.
