### ISSUE TITLE
Persulfide dioxygenase-like, MBL-fold metallo-hydrolase domain (IPR044528)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4219]
* **InterPro ID / label**
Persulfide dioxygenase-like, MBL-fold metallo-hydrolase domain (IPR044528)

* **Description of issue**
This has two GO-MF terms associated (for hydrolase and oxidoreductase activity):
hydrolase activity, acting on ester bonds (GO:0016788)
sulfur dioxygenase activity (GO:0050313)

The second one looks fine, but I don't see the evidence for the first one.  Can you check please?

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for that. You are right, I removed the GO term as I didn't find evidence saying the whole entry should be associated with this term.  The changes will be available in the next InterPro release.

Best regards,
Beatriz

**Comment by sjm41** [comment]
Thanks Beatriz.
