### ISSUE TITLE
 protein serine/threonine phosphatase activity (annotation to adenylate cyclase)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4221]
* **InterPro ID / label**

GO:0004722 | protein serine/threonine phosphatase activity | IEA with IPR001932

* **Example sequences with problematic annotation (ID + gene/protein name):**

pombe adenylate cyclase:
https://www.pombase.org/gene/SPBC19C7.03

* **Description of issue**
I'm not aware of this?

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. Yes, I agree. I removed the term from this entry to avoid this wrong propagation to adenylate cyclases. This will be visible in the next InterPro release (90.0).
Best regards,
Sara
