### ISSUE TITLE
Incorrect UniProt KW mapping: Q9Y812 kinetochore

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4230]
* **UniProt KeyWord (ID and label):**

Cnp1 (CENP-A)
GO:0000776 | kinetochore | IEA with KW-0995 | GO_REF:0000043

* **Sequences with problematic annotation (ID + gene/protein name):**
Q9Y812 (possibly others)

Cnp1 is part of the CENP-A containing nucleosome (centromeric chromatin)
It isn't part of the kinetochore  (although the kinetochore is assembled over it)

**Comment by ValWood** [comment]
also 
GO:0000776 | kinetochore | IEA with KW-0995 | GO_REF:0000043

**Comment by Antonialock** [comment]
I am going to try and get the "kinetochore" keyword removed from cenp-a proteins (it's not a mapping issue, it's an annotation issue).

In Uniprot the function statement for CENP-A proteins states:
"Replaces conventional H3 in the nucleosome core of centromeric chromatin at the inner plate of the kinetochore", perhaps this could be interpreted as that it is part of the kinetochore, but current papers definitely state that the kinetochore forms ON CENP-A nucleosomes, and both are then then part of a large subunit complex that connects to MTs (" The CENP-A:CHIKMLN complex binds directly to the KMN network, resulting in a 21-subunit complex that forms a minimal high-affinity linkage between CENP-A nucleosomes and microtubules in vitro. " - 2016 paper)


2016 Nature  27580032: Kinetochores...enrich nucleosomes containing the histone H3 variant centromeric protein A (CENP-A). **A group of several additional CENPs, collectively known as constitutive centromere associated network (CCAN), establish the inner kinetochore**, whereas a ten-subunit assembly known as the KMN network creates a microtubule-binding site in the outer kinetochore. **Interactions between CENP-A and two CCAN subunits, CENP-C and CENP-N, have been previously described,**

2022 Science 35420891: Kinetochores assemble onto specialized centromeric CENP-A (centromere protein A) nucleosomes (CENP-ANuc) to mediate attachments between chromosomes and the mitotic spindle

2019 Nature 31578520: Here we describe the cryo-electron microscopy structure of the Saccharomyces cerevisiae inner kinetochore module, the constitutive centromere associated network (CCAN) complex, assembled **onto a Cenp-A nucleosome**

2021 EMBO J  33463726:  Once the CENP-A nucleosome is established in the centromere, additional proteins recognize the CENP-A nucleosome to form a kinetochore, and that kinetochore+cenp-A


2020 NAR  32976599: The inner kinetochore constitutive centromere associated network (CCAN) complex assembles onto the centromere-specific Cenp-A nucleosome (Cenp-ANuc)

**Comment by Antonialock** [comment]
Changing
"Histone H3-like nucleosomal protein that is specifically found in centromeric nucleosomes. Replaces conventional H3 in the nucleosome core of centromeric chromatin at the inner plate of the kinetochore"

For
"Histone H3-like nucleosomal protein that is specifically found in centromeric nucleosomes. Replaces conventional H3 in the nucleosome core of centromeric chromatin and serves as an assembly site for the inner kinetochore."

**Comment by Antonialock** [comment]
should the def of GO:0000939 "inner kinetochore" be updated to exclude CENP-A or it looks a bit confusing?
The region of a kinetochore closest to centromeric DNA; in mammals the CREST antigens (CENP proteins) are found in this layer; this layer may help define underlying centromeric chromatin structure and position of the kinetochore on the chromosome.

**Comment by Antonialock** [comment]
The uniprot annotations saying it is part of the kinetochore come from this 2003 paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2173538/

**Comment by Antonialock** [comment]
although 2010 nat cell bio paper 16715078
"The centromeric histone Cse4p is a core component of the kinetochore. "

**Comment by Antonialock** [comment]
Hmm, current papers seem to think it associates with kinetochores, not that it is part of it, and they then for a  part of a large subunit complex that connects to MTs (" The CENP-A:CHIKMLN complex binds directly to the KMN network, resulting in a 21-subunit complex that forms a minimal high-affinity linkage between CENP-A nucleosomes and microtubules in vitro. " - 2016 paper)

eg

2016 Nature 27580032: Kinetochores...enrich nucleosomes containing the histone H3 variant centromeric protein A (CENP-A). A group of several additional CENPs, collectively known as constitutive centromere associated network (CCAN), establish the inner kinetochore, whereas a ten-subunit assembly known as the KMN network creates a microtubule-binding site in the outer kinetochore. Interactions between CENP-A and two CCAN subunits, CENP-C and CENP-N, have been previously described,

2022 Science 35420891: Kinetochores assemble onto specialized centromeric CENP-A (centromere protein A) nucleosomes (CENP-ANuc) to mediate attachments between chromosomes and the mitotic spindle

2019 Nature 31578520: Here we describe the cryo-electron microscopy structure of the Saccharomyces cerevisiae inner kinetochore module, the constitutive centromere associated network (CCAN) complex, assembled onto a Cenp-A nucleosome

2021 EMBO J 33463726: Once the CENP-A nucleosome is established in the centromere, additional proteins recognize the CENP-A nucleosome to form a kinetochore, and that kinetochore+cenp-A

2020 NAR 32976599: The inner kinetochore constitutive centromere associated network (CCAN) complex assembles onto the centromere-specific Cenp-A nucleosome (Cenp-ANuc)

**Comment by Antonialock** [comment]
but older papers suggest it is part of the kinetochore 

even as recent as 2010
pmid:16715078
"The centromeric histone Cse4p is a core component of the kinetochore. "

or this 2003 paper
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2173538/

**Comment by Antonialock** [comment]
the GO def does not exclude CENP-A from the def of inner kinetochore

GO:0000939 "inner kinetochore:
The region of a kinetochore closest to centromeric DNA; in mammals the CREST antigens (CENP proteins) are found in this layer; this layer may help define underlying centromeric chromatin structure and position of the kinetochore on the chromosome.

**Comment by ValWood** [comment]
The difference might be between S. cerevisiae. (point centromeres, single nucleosome) and S. pombe and higher eukaryotes (regional centromeres).

Most schematics show it like this:

<img width="408" alt="Screenshot 2022-08-26 at 14 59 39" src="https://user-images.githubusercontent.com/7359272/186920737-ad1acd1a-4d14-4d24-b12c-db0982db0d79.png">
<img width="389" alt="Screenshot 2022-08-26 at 14 59 15" src="https://user-images.githubusercontent.com/7359272/186920746-d55d3e9f-2543-4390-83c1-cd416f6b0b1a.png">

and it fits the GO.
Comments
Note that the kinetochore overlaps the centromeric DNA, but centromeric DNA is not part of the kinetochore.

This comment should probably  be part of the definition. @pgaudet

**Comment by Antonialock** [comment]
SGD have annotated to kinetochore
![image](https://user-images.githubusercontent.com/12727506/186920235-ceda5c67-c864-476c-aa21-02ad19c12931.png)


so has MGI
![image](https://user-images.githubusercontent.com/12727506/186920436-b8a1f9fd-ec41-483f-a10c-7de5b91bccc7.png)


and BHFL
![image](https://user-images.githubusercontent.com/12727506/186920665-aaf7a7b7-0751-46d7-8cc5-4928eabe6152.png)


and RGD
![image](https://user-images.githubusercontent.com/12727506/186920962-5bca0c93-6fb5-4cf8-a7bf-fff8ea0e2c11.png)


it would be strange to remove the IEA and let all these manual annotations exist?

**Comment by ValWood** [comment]
I think it is a resolution issue.

The mouse paper PMID:14519686

Most eukaryotic centromeres, including those of fission yeast, Drosophila and mammals, contain regions of heterochromatin; that is, chromatin packaged in a condensed state throughout the cell cycle ([7](javascript:;)). On a cytological scale, this heterochromatin may appear to overlap with the kinetochore ([8](javascript:;)–[10](javascript:;)), and in some organisms flank the kinetochore along the chromosome axis ([11](javascript:;),[12](javascript:;)). Pericentric heterochromatin contains few transcribed genes and can form domains that are involved in gene silencing in trans within the interphase nucleus ([13](javascript:;),[14](javascript:;)).

**Comment by ValWood** [comment]
I think the centromeric chromatin cannot be part of the kinetochore. The kinetochore assembles during mitosis. But the CENP-A containing chromatin is assembled during S-phase.

**Comment by ValWood** [comment]
Wikepedia calls CENP-A kinetochore.
Uses a 2004 paper

**Comment by ValWood** [comment]
maybe it's OK...but  it seems odd to include the DNA and centromeric heterochromatin   as part of the complex (which this would do as CENP-A is nucleosomal). Perhapos all of t inner kinetochore is also present throughout the cell cycle.

**Comment by ValWood** [comment]
But the CENP_A Wikipeida page doe not class CENP-A as kinetochore
https://en.wikipedia.org/wiki/CENPA
It says 
CENPA interacts directly with the [inner kinetochore](https://en.wikipedia.org/wiki/Kinetochore) through proteins including [CENPC](https://en.wikipedia.org/wiki/CENPC1) and [CENPN](https://en.wikipedia.org/wiki/CENPN).[[18]](https://en.wikipedia.org/wiki/CENPA#cite_note-18)[[19]](https://en.wikipedia.org/wiki/CENPA#cite_note-19)

citing a 2019 and a 2020 paper
Kixmoeller K, Allu PK, Black BE (June 2020). ["The centromere comes into focus: from CENP-A nucleosomes to kinetochore connections with the spindle"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7333888). Open Biology. 10 (6): 200051. [doi](https://en.wikipedia.org/wiki/Doi_(identifier)):[10.1098/rsob.200051](https://doi.org/10.1098%2Frsob.200051). [PMC](https://en.wikipedia.org/wiki/PMC_(identifier)) [7333888](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7333888). [PMID](https://en.wikipedia.org/wiki/PMID_(identifier)) [32516549](https://pubmed.ncbi.nlm.nih.gov/32516549).
 Yan K, Yang J, Zhang Z, McLaughlin SH, Chang L, Fasci D, et al. (October 2019). ["Structure of the inner kinetochore CCAN complex assembled onto a centromeric nucleosome"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6859074). Nature. 574 (7777): 278–282. [Bibcode](https://en.wikipedia.org/wiki/Bibcode_(identifier)):[2019Natur.574..278Y](https://ui.adsabs.harvard.edu/abs/2019Natur.574..278Y). [doi](https://en.wikipedia.org/wiki/Doi_(identifier)):[10.1038/s41586-019-1609-1](https://doi.org/10.1038%2Fs41586-019-1609-1). [PMC](https://en.wikipedia.org/wiki/PMC_(identifier)) [6859074](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6859074). [PMID](https://en.wikipedia.org/wiki/PMID_(identifier)) [31578520](https://pubmed.ncbi.nlm.nih.gov/31578520).

**Comment by ValWood** [comment]
From reference 18
<img width="711" alt="Screenshot 2022-08-26 at 15 20 56" src="https://user-images.githubusercontent.com/7359272/186925372-10533180-caa4-4eb2-ac2c-941ea8606ab5.png">

so I am sticking with out (which is what I have been reading fro pombe kinetochore annotations)

**Comment by ValWood** [comment]
The kinetochore annotations are legacy before the kinetochore structure was fully resolved, and can be disputed pointing to this ticket.

**Comment by Antonialock** [comment]
Ok yes I agree that seems to be the current thinking. 

I have disputed the ones I saw.....it would be good to see there is consensus before I remove it from the UniProt entries.

**Comment by Antonialock** [comment]
ok I will close and remove the kinetochore association with CENPA at the uniprot end.
