### ISSUE TITLE
positive regulation of transforming growth factor beta receptor signaling pathway

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-annotation#4231]
following on from
https://github.com/geneontology/go-ontology/issues/23449

I noticed that the "positive regulation of transforming growth factor beta receptor signaling pathway" term was not restricted for protostomes e.g. Q5WRN1

should they not be flagged too?

**Comment by Pauldenny** [comment]
same constraint for these?

Child Term	Relationship to
GO:0007179
[GO:1901048](https://www.ebi.ac.uk/QuickGO/term/GO:1901048)    transforming growth factor beta receptor signaling pathway involved in regulation of multicellular organism growth	is_a
[GO:1905313](https://www.ebi.ac.uk/QuickGO/term/GO:1905313)    transforming growth factor beta receptor signaling pathway involved in heart development	is_a
[GO:0017015](https://www.ebi.ac.uk/QuickGO/term/GO:0017015)    regulation of transforming growth factor beta receptor signaling pathway	regulates
[GO:0030512](https://www.ebi.ac.uk/QuickGO/term/GO:0030512)    negative regulation of transforming growth factor beta receptor signaling pathway	negatively_regulates
[GO:0060826](https://www.ebi.ac.uk/QuickGO/term/GO:0060826)    transforming growth factor beta receptor signaling pathway involved in neural plate anterior/posterior pattern formation	is_a
[GO:0035463](https://www.ebi.ac.uk/QuickGO/term/GO:0035463)    transforming growth factor beta receptor signaling pathway involved in determination of left/right asymmetry	is_a
[GO:0099126](https://www.ebi.ac.uk/QuickGO/term/GO:0099126)    transforming growth factor beta complex	capable_of_part_of
[GO:0007181](https://www.ebi.ac.uk/QuickGO/term/GO:0007181)    transforming growth factor beta receptor complex assembly	part_of
[GO:0060835](https://www.ebi.ac.uk/QuickGO/term/GO:0060835)    transforming growth factor receptor beta signaling pathway involved in oral/aboral axis specification	is_a
[GO:0060797](https://www.ebi.ac.uk/QuickGO/term/GO:0060797)    transforming growth factor beta receptor signaling pathway involved in primary germ layer cell fate commitment	is_a
[GO:0030511](https://www.ebi.ac.uk/QuickGO/term/GO:0030511)    positive regulation of transforming growth factor beta receptor signaling pathway	positively_regulates
[GO:0090010](https://www.ebi.ac.uk/QuickGO/term/GO:0090010)

**Comment by ValWood** [comment]
@Antonialock are you requesting taxon constrints?
If so can you list  the restrictions and I will transfer to the ontology tracker.

**Comment by pgaudet** [comment]
Will be done in #23449 please comment there
