### ISSUE TITLE
Review annotations to GO:0039612 modulation by virus of host protein phosphorylation & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4233]
Dear all, 

The proposal has been made to obsolete GO:0039612 modulation by virus of host protein phosphorylation & children. 

There are 3 annotations to this term, see https://docs.google.com/spreadsheets/d/1x888E7jsMjJ3oUvkTLhf7AaKfjU03ggRR_fsZlxI6tY/edit#gid=0

* 2 AgBase (fixed
* 1 CACAO (fixed 2022-07-15)

Please fix annotations.

**Comment by pgaudet** [comment]
There is also one UniRule - UR000613387
GO:0039586 modulation by virus of host PP1 activity can be replaced by GO:0039606 suppression by virus of host translation initiation

@esperetta 
@PedroRaposo 

Thanks, Pascale

**Comment by pedruzzi** [comment]
fixed rule MF_04079 aka UR000613387, removed obsolete GO term
