### ISSUE TITLE
Remove InterPro annotations to GO:0043486 histone exchange 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4235]
* **InterPro ID / label**
* InterPro:IPR008895 
* InterPro:IPR037651
* InterPro:IPR039723 
* 
* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**
For all 3, you can  remove; chromatin remodeling sufficient as BP, add MF: GO:0140849 ATP-dependent H2AZ histone chaperone activity

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much for this. I have done the changes you mentioned. These will be available in the next InterPro release (90.0).
Best regards,
Sara
