### ISSUE TITLE
Review annotations to GO:0043486 histone exchange and regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4236]
Dear all, 

The proposal has been made to obsolete GO:0043486 histone exchange and regulation children: 
* GO:1900049 regulation of histone exchange
* GO:1900050 negative regulation of histone exchange
* GO:1900051 positive regulation of histone exchange

Suggestions have been made for reannotation: 
* 1 TAIR
* 20 SGD SGD
* 2 MGI

Annotations are here: 
https://docs.google.com/spreadsheets/d/13Sys5a4tYDCtXJKzwZ29K-0VCCN_IMl9SGMchl_QLGM/edit#gid=0

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by tberardini** [comment]
TAIR done.

**Comment by ValWood** [comment]
These are long gone
