### ISSUE TITLE
PTN000574151  not all GO:0035267 | NuA4 histone acetyltransferase complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4237]
* **PTHR ID & PTN node:**

GO:0035267 | NuA4 histone acetyltransferase complex | IBA with FBgn0031873 , S000005051 , yaf9 , O95619 , PTN000574151 , CAL0000173992 ,

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC22H12.02

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

probablyly propagation

**Comment by marcfeuermann** [comment]
Ancient duplication with gain/loss of function within fungi. A whole clade had to be reviewed.
Done.
