### ISSUE TITLE
SMAD signaling needs consistent annotation 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#4239]
Hi

I think that the term GO:0060395 SMAD protein signal transduction should describe the 'intracellular cassette signaling pathway' rather than a receptor mediated pathway.

I realise that all SMAD signaling occurs via a receptor mediated pathway but I had assumed that, for example, BMP2 would be annotated as:
1. Involved_in GO:0030509 BMP signaling pathway
2. Involved_in (acts upstream of - not sure what the correct option is here) GO:0060391 positive regulation of SMAD protein signal transduction with the annotation extension: part_of GO:0030509 BMP signaling pathway

And that only the SMADs and the directly involved dbTF would be annotated as:
1. Involved_in GO:0030509 BMP signaling pathway
2. Involved_in GO:0060395 SMAD protein signal transduction with the annotation extension: part_of GO:0030509 BMP signaling pathway

But the current definition (my bad?) includes the ligand and receptor.

The advantage of including the ligand and receptor is that this means the annotations are also associated with the transmembrane receptor protein serine/threonine kinase signaling pathway GO term - which is correct.

The disadvantage is that this is inconsistent with other intracellular signaling cassettes eg GO:0048017 inositol lipid-mediated signaling. Also this does not allow a distinction between the proteins that are part of the SMAD pathway and those that are at the cell membrane (eg Ligands BMPs, TGFs and their receptors)

Maybe I have just misinterpreted the signaling annotation plan?

The problem is that some curators are annotating the ligands and receptors with positive regulation of SMAD protein signal transduction while others are annotating ligands and receptors with SMAD protein signal transduction - thus creating inconsistent annotations. 

Could we either make GO:0060395 SMAD protein signal transduction a child of GO:0035556 intracellular signal transduction or change the term name to receptor signaling pathway via SMAD (similar to GO:0007259 receptor signaling pathway via JAK-STAT) to clarify this.

Either way the annotations to GO:0060395 SMAD protein signal transduction and the regulation of SMAD protein signal transduction terms need to be reviewed so that a BMP is annotated to either the process or regulation of the process

Best

Ruth

**Comment by pgaudet** [comment]
Is this an annotation or an ontology ticket?

**Comment by hattrill** [comment]
I think that the suggestion that makling GO:0060395 SMAD protein signal transduction a child of GO:0035556 intracellular signal transduction is the best option - make it into an intracellular casette.


I guess it would be mainly restricted to SMADs and co-SMADs. IMO It's good to have these terms, as a lot of regulation happens at this juncture.

I think as the receptor directly activated SMAD signaling, then "GO:0060391 positive regulation of SMAD protein signal transduction ;  part_of GO:0030509 BMP signaling pathway would make sense for the receptor and ligand.

**Comment by RLovering** [comment]
Thanks Helen
I have downloaded all manual expt and TAS annotations and marked up some of them. I have hightlighted the regulation annotations as it makes it easier for me to see what is going on.
But before I go any further do you think that dbTFs, and maybe coTFs, should be associated with the pathway if they are the dbTF that works with SMAD4 (usually) to regulate transcription or should dbTFs, and coTFs just be associated with the ligand signaling pathway?

Thanks

Rut
[SMAD signaling review.xlsx](https://github.com/geneontology/go-annotation/files/9112429/SMAD.signaling.review.xlsx)
h

**Comment by RLovering** [comment]
Ruth to sort out the annotation review sheet with Pascale help 
https://github.com/geneontology/go-ontology/issues/23773
Also need to decide about dbTF and coTFs to include, should we just stop at SMADs or include more TFs
Ruth

**Comment by pgaudet** [comment]
There is a newer ticket for this: 

https://github.com/geneontology/go-annotation/issues/4611
