### ISSUE TITLE
INtact complex portal (physical interaction between different species)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4241]
Could this annotation be deleted, it records  a physical interaction between  a pombe protein and human protein (these shouldn't get through to GO should they)?

INTA | P04910 | hta2 | enables | GO:0005515 | protein binding | ECO:0000353(IPI) | ECO:0000353 | (IPI) |   | PMID:21633354 |   | UniProtKB:Q15003

ECO:0000353 | (IPI)

**Comment by ValWood** [comment]
Assigning to @Antonialock  to assign the right person, and check  if this should be an annotation check

**Comment by sandraorchard** [comment]
The process is automatic so the only way of getting rid of this interaction at the IntAct end would be to add a filter so all cross-species interactions are removed from the IntAct2GO (and UniProt) exports. This has been discussed in the past, but would mean (a) all host-pathogen interactions and (b) all interactions designed to show sequence conservation are lost so it was always agreed the loss outweighed the gain.  A data import filter at your end would be the other alternative.

**Comment by ValWood** [comment]
Hmm it would be a shame to use pathogen-host interactions from GO, as these are real interactions.

 Is it possible to make a way to distinguish these ?  It seems a shame that the pathogen-host interactions and the sequence conservation examples are not distinguishable. MAybe they could have a specific "qualifier" to distinguish them.

This would also enable the pathogen-host interaction pairs to be accessed as a set. I suspect PHI-base will be interested in this set as they are likely to be represent  proteins that  should be included in  include . Is it possible to do a query to retrieve all interspecies physical interactions? 

We can filter them locally from PomBase.

**Comment by sandraorchard** [comment]
Can this be closed now?

**Comment by ValWood** [comment]
Yes I guess (note to self add filter to PomBase)
