### ISSUE TITLE
Review annotations to GO:0010108 detection of glutamine

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4242]
Dear all,

The proposal has been made to obsolete

 GO:0010108 detection of glutamine

Obsoletion ticket: https://github.com/geneontology/go-ontology/issues/23123

since it represents a molecular function GO:0140786 glutamine sensor activity

There are 2 EXP annotations:
Contributor (Assigned by) SGD

Please review your annotations.
https://docs.google.com/spreadsheets/d/1nRrhTtkW9W87C4biN5MGlSR4WdSCwU-kZcfjVBudKz0/edit#gid=0

Thanks. Raymond

**Comment by srengel** [comment]
i have removed the two SGD annotations. in noctua, which was not easy to do in any intuitive way. hope i didn't mess it up.
