### ISSUE TITLE
PTN000447133 not all gamma tubulin small complex (family error)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4243]
* **PTHR ID & PTN node:**

GO:0008275 | gamma-tubulin small complex | IBA with S000005070 , PTN000447133 , alp16 , FBgn0001612 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

Pombe alp16

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous propagation

SGD SPC98 and drosophila Grip91 are Alp6 orthologs, not pombe alp16.

There is no identified alp16 in S. cerevisiae. The fly Alp16 ortholog is most likely CG18109
Alp16 is gamma tubulin large complex

more background
https://github.com/pombase/curation/issues/3284

**Comment by marcfeuermann** [comment]
Gamma tubulin small complex and non-gamma tubulin small complex members are mixed within the family, and it is not possible to distinguish who is who (appart from those characterized in literature), so the term is in fact not PAINTable. I've removed its propagation. We have gamma tubulin complex for all.
