### ISSUE TITLE
RNA-directed 5'-3' RNA polymerase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4244]
There are quite a few 
 DNA-dependent RNA polymerases annotated to RNA-directed 5'-3' RNA polymerase activity
which is the term for RdRP activity/RNA-dependent RNA polymerase activity 
For example 12 subunits of S. cerevisiae RNA polymerase @srengel 

and human TERT (which is a  [RNA-directed DNA polymerase activity) @RLovering  
(also complex portal, not sure who to tag).

You can  probably add "never in S. cerevisiae" and "never in human" to this term, I don't think either has RNA-directed 5'-3' RNA polymerase activity (although some transposons might, so this would need to be checked)

**Comment by pgaudet** [comment]
We just looked at the data from the paper annotated https://pubmed.ncbi.nlm.nih.gov/19701182/, and it is 5'-> 3' 

<img width="309" alt="image" src="https://user-images.githubusercontent.com/4782928/180776155-d4360bca-59ed-46eb-89ab-54d9beeb3671.png">

See also abstract 
> Human TERT and RMRP form a distinct ribonucleoprotein complex that has RNA-dependent RNA polymerase (RdRP) 

So, I wont put a taxon constraints on human.

Thanks, Pascale

**Comment by pgaudet** [comment]
For at least one yeast paper, the authors state that polII has RNA-dependent RNA polymerase activity, see
PMID:18004386

Do you think this is not right ?

**Comment by ValWood** [comment]
Well, the HDV  (RNA virus) uses hijacks the host polymerase , as an RdRP. Do we annotate that as normal activity?
There may be further papers showing a role in small RNA generation- not sure ?

**It is possible** that the ancient RdRP activity of
Pol II, which still replicates HDV, **is still used in certain cellular
processes**, because many organisms lack dedicated single-subunit
RdRPs. Given the slow nature and the impaired processivity of the
RdRP activity in vitro, such processes would require stimulating
factors or would be restricted to the generation of smaller RNAs.

**Comment by pgaudet** [comment]
Are all yeast papers describing the same viral phenomenon? 

@srengel are you OK to add that taxon constraint?

**Comment by srengel** [comment]
i don't think we are good with that taxon constraint.  this paper says yeast has RNA-dependent RNA polymerase II activity:
https://www.yeastgenome.org/reference/35175277

**Comment by ValWood** [comment]
Is that the correct paper? this is about vacuolar trafficking?

**Comment by srengel** [comment]
ack sorry this is the right paper, that other one is something else i'm working on

https://www.yeastgenome.org/reference/18004386

**Comment by ValWood** [comment]
So,  this is the one I looked at. It isn't clear that the RdRP has a functional role for S. cerevisiae, just that they can get it to reverse transcribe a virus RNA in vitro?

"Given the slow nature and the impaired processivity of the
RdRP activity in vitro, such processes would require stimulating
factors or would be restricted to the generation of smaller RNAs." 

but they don't present a role in S. c and this was back in 2007. Is there any work since where there is a role in generating  small RNAs (It would be massive if there was)

**Comment by srengel** [comment]
i am not in any way comfortable asserting that i know so much about biology to say that this activity that occurs isn't in any way biologically significant.

**Comment by ValWood** [comment]
OK no worries. can close this.
