### ISSUE TITLE
Creation of GO term for 'inner membrane complex'

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-annotation#4247]
Would it be possible to create a component GO term for 'inner membrane complex'?
This structure is specific to Apicomplexa species and I couldn't find an appropriate GO term to describe it.

Potential definition:
Double membrane structure located directly below the plasma membrane in Apicomplexa. 
PMID: 24612102 

Thank you

Rossana

**Comment by ValWood** [comment]
Hi @rozaru 

Is it this term?
https://www.ebi.ac.uk/QuickGO/term/GO:0070258
