### ISSUE TITLE
not plasma membrane PTN000850943 PTN001566526

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4253]
These might be close to the plasma membrane, but I don't think they are really plasma membrane proteins (cortical)

* **PTHR ID & PTN node:**
https://www.pombase.org/gene/SPAPJ760.02c
abp1 |   | IBA with FBgn0025865 , DDB_G0273447 , Q14247 , Q9UJU6 , MGI:1931838 , PTN000850943 , MGI:99695 , 619839 , 70885 , P14317

https://www.pombase.org/gene/SPAC15A10.08
ain1 |   | IBA with PTN001566526 , MGI:98387 , WBGene00006803 , 1308097 , 2507 , MGI:1313261 , ZDB-GENE-010426-1 , MGI:1890574 , P46939 , MGI:94909 , MGI:104631 , 621714 , O15020 , 70907 , 1305194 , F6W8M4 , MGI:98386 , P05094 , FBgn0250788 , FBgn0260003 , 3751 , P11532 , MGI:98388 , FBgn0250789

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Both families have been updated
