### ISSUE TITLE
not plasma membrane  PTN001217453 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4254]
* **PTHR ID & PTN node:**

not plasma membrane (cortical
https://www.pombase.org/gene/SPBC4F6.06
IBA with kin1 , S000004086 , PTN001217453 , S000002529

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Updated family.
