### ISSUE TITLE
Review annotations to  GO:0016277 [myelin basic protein]-arginine N-methyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4256]
Dear all, 

The proposal has been made to obsolete  GO:0016277 [myelin basic protein]-arginine N-methyltransferase activity, see https://github.com/geneontology/go-ontology/issues/23705

Annotations are here: 
https://docs.google.com/spreadsheets/d/1yPO42RzBGfdUGAtl17pkMih4b0g50Ko1kDYQssFe8W8/edit#gid=0

3 TAIR
1 HGNC

Thanks, Pascale

**Comment by tberardini** [comment]
TAIR done
