### ISSUE TITLE
PTN002926343 NOT a transporter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4257]
SOURCE   ENTITY TYPE      ENTITY ID                        GO ID            EVIDENCE                 REFERENCE        WITH/FROM                                                EXTENSION
REFG     protein          Q6NXT4                           GO:0005385       ECO:0000318 (IBA)        PMID:21873635    MGI:MGI:2386741|PANTHER:PTN002926343                     

Query details:
Hi, according to PubMed=19366695, human SLC30A6 is missing important residues for zinc transport and has no intrinsic activity (also not conserved in orthologs). However, forms a functional transporter with SLC30A5 which has an intrinsic transporter activity. Maybe this MF should not be assigned to SLC30A6 genes.

**Comment by pgaudet** [comment]
Reporter by @lbreuza in P2GO

**Comment by marcfeuermann** [comment]
Indeed, I've removed the MF propagation but kept the BP.
