### ISSUE TITLE
Review annotations to GO:0100002 negative regulation of protein kinase activity by regulation or protein phosphorylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4263]
This term will be obsoleted, see https://github.com/geneontology/go-ontology/issues/12351

1. BHF @RLovering 
[P31749](https://www.uniprot.org/uniprot/P31749) from PMID:21711983 |  

2. SGD @srengel 
[GCN2](http://amigo.geneontology.org/amigo/gene_product/SGD:S00000269 from [PMID:28057755](http://amigo.geneontology.org/amigo/reference/PMID:28057755)

Thanks, Pascale

**Comment by pgaudet** [comment]
Consider annotating to 'GO:0004860 protein kinase inhibitor activity'

**Comment by RLovering** [comment]
UCL annotation updated

**Comment by srengel** [comment]
SGD done.
