### ISSUE TITLE
PTN000756668 not a transporter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4264]
* **PTHR ID & PTN node:**

GO:0015234 | thiamine transmembrane transporter activity | IBA with locus:2154374 , S000003328 , PTN000756668 , A0A1D6N272 , Q8RXZ9 , FBgn0037852 , B4FIJ0

GO:0030974 | thiamine pyrophosphate transmembrane transport | IBA with A0A1D6N272 , PTN000756668 , B4FIJ0 , FBgn0037852 , S000003328 , locus:2154374 , Q8RXZ9

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1B2.02c
https://www.yeastgenome.org/locus/YDR470C

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Possibly a bit of both. SGD text  for Ugo1 says:
Outer membrane component of the mitochondrial fusion machinery; binds to Fzo1p and Mgm1p to link these two GTPases during mitochondrial fusion; involved in fusion of both the outer and inner membranes; facilitates dimerization of Fzo1p during fusion; import into the outer membrane is mediated by Tom70p and Mim1p; has similarity to carrier proteins but likely not a transporter; similar to human SLC25A46 implicated in optic atroprophy spectrum disorder and Leigh syndrome

Note that  UGo1 is SGD:S000002878
S000003328 is a carrier in the same family

**Comment by marcfeuermann** [comment]
Duplication followed by loss of function/neofunctionalization. This big family of transporters needed several updates. Done.
