### ISSUE TITLE
Review annotations to Golgi to plasma membrane CFTR protein transport (and regulation)

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4265]
A proposal has been made to obsolete BP terms Golgi to plasma membrane CFTR protein transport and its regulations because these terms involved a specific gene product.

Of the 5 terms, there are 3 EXP annotations, all from UniProt
GO:0043000 Golgi to plasma membrane CFTR protein transport  2
GO:0043002 negative regulation of Golgi to plasma membrane CFTR protein transport 0
GO:0043003 positive regulation of Golgi to plasma membrane CFTR protein transport 0
GO:0042999 regulation of Golgi to plasma membrane CFTR protein transport 0
GO:0043004 cytoplasmic sequestering of CFTR protein 1

**Comment by raymond91125** [comment]
https://docs.google.com/spreadsheets/d/1t6iOf_qbC4-qVsUr_jcnP14JKFgWBoveGQ2AKlCYciw/edit?usp=sharing
Existing annotations may be
moved to GO:0043001 Golgi to plasma membrane protein transport, add has input CFTR
moved to GO:0051220 cytoplasmic sequestering of protein + has input CFTR

**Comment by raymond91125** [comment]
@pgaudet Who at UniProt should be notified? Thanks.

**Comment by raymond91125** [comment]
There is an InterPro2GO mapping
InterPro:IPR038879 Golgi-associated PDZ and coiled-coil motif-containing protein > GO:cytoplasmic sequestering of CFTR protein ; GO:0043004

**Comment by pgaudet** [comment]
I have changed all UniProt annotations. 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have removed GO:0043004 from IPR038879; this will be visible in the next InterPro release (91.0).
Best regards,
Sara
