### ISSUE TITLE
PTN000989606   Mon1-Czz1 complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4266]
* **PTHR ID & PTN node:**
PTN000989606  

* **Sequences with problematic annotation (ID + gene/protein name):**
<img width="1168" alt="no  identified ccz1" src="https://user-images.githubusercontent.com/7359272/187271599-ea9861a5-85a2-4b1e-bc4b-df1b57bd88b7.png">

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation error, the  other member of the complex appears to be a lineage specific gene loss in Schizos:
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR13056
Despite broad eukaryotic conservation I have been unable to detect in fission yeast

**Comment by marcfeuermann** [comment]
Corrected
