### ISSUE TITLE
 PTN000305308  -	GO:0000153	 cytoplasmic ubiquitin ligase complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4267]
* **PTHR ID & PTN node:**

 PTN000305308 

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC3B9.06c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

atg3 is an  atg8 ligase

**Comment by marcfeuermann** [comment]
Reviewed
