### ISSUE TITLE
 IPR045223 not ribosomal

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4268]
* **InterPro ID / label**

 IPR045223 

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC6B12.15

* **Description of issue**

Is robosome-associated, but isn't actually ribosomal

**Comment by sarach06** [comment]
Hi Val,
Thank you very much, you are right. I added GO:0045182 (translation regulator activity) to this entry, let me know if you agree or if you think a more appropriate one should be added.
Best regards,
Sara

**Comment by ValWood** [comment]
Sounds good.

**Comment by sarach06** [comment]
Thanks, it will be visible in InterPro 91.0. I'll close this one, then.
Best regards,
Sara
