### ISSUE TITLE
, PTN001586581

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4269]
* **PTHR ID & PTN node:**

, [PTN001586581]

* **Sequences with problematic annotation (ID + gene/protein name):**

<img width="1185" alt="no TAFI110 and TAFI48  in fungi" src="https://user-images.githubusercontent.com/7359272/187276813-28087fa7-dc29-43e7-9870-73f9775600f9.png">

* **Type of Issue: Erroneous  propagation, **

As far as I can see. there is no TAF1A or TAF1C in fungi

**Comment by marcfeuermann** [comment]
Good point. I've restricted the use of this term.
