### ISSUE TITLE
 PTN002010747  not in yeast?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4270]
* **PTHR ID & PTN node:**

[PTN002010747]

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC576.12c

<img width="1150" alt="fanconi, missing most members" src="https://user-images.githubusercontent.com/7359272/187277190-c2bc067a-cbb9-4ca4-9a2b-455e69914c19.png">

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Yeast have other fanconi anemia related complexes, but they don't have FANC A,C,E,G or F

**Comment by marcfeuermann** [comment]
This has already been addressed:
https://github.com/geneontology/go-annotation/issues/4211
So should disappear soon.
