### ISSUE TITLE
 IPR003213	 respiratory chain complex IV 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4271]
* **InterPro ID / label**

IPR003213

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC24C6.13

* **Description of issue**

coa6 is mitonodrial intermembrane space, not 

respiratory chain complex IV

**Comment by sarach06** [comment]
Hi Val,
Thank you very much for this. I have removed the term from this entry. The changes will be visible in InterPro 91.0.
Best regards,
Sara
