### ISSUE TITLE
IPR037856 not MLL3/4 complex for pombe (& possibly other yeast )

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4272]
* **InterPro ID / label**

GO:0044666 | MLL3/4 complex | IEA with IPR037856

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

pombe has no KMRC2 (MLL$) or KMTC2 (MLL3)

**Comment by sarach06** [comment]
Hi Val,
Thank you very much for this. I have removed the term from this entry, which will be visible in the next InterPro release (91.0).
Best regards,
Sara
