### ISSUE TITLE
PTN000340056 messenger ribonucleoprotein complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4273]
* **PTHR ID & PTN node:**

sum2 | GO:1990124 | messenger ribonucleoprotein complex | IBA with FBgn0041775 , PTN000340056 , WBGene00012484

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC800.09
I currently annotated to 
GO:0033962 | P-body assembly | ISO with S000006333

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This one might seem a bit picky, but this term seems that it does not refer to an actual complex, it sounds more like a grouping term but it has no descendants.
I only have this single annotation.

This protein might be binding RNAs but I don't see any evidence for a stoichiometric complex, so I am going to filter this single annotation (unless there is more evidence about precise compositions, and other subunits)

Q should the term exist? @pgaudet  lots of things could be described as "messenger ribonucleoprotein complex ", every splicosomal complex for example. if it is kept it needs to be more precise:

<img width="1200" alt="mRNA  complex" src="https://user-images.githubusercontent.com/7359272/187471171-b26effdd-a669-4dee-935f-f5b8d1db8270.png">

**Comment by marcfeuermann** [comment]
"messenger ribonucleoprotein complex" seems indeed not so relevant. I've removed it.
