### ISSUE TITLE
PTN001784663 not mitochondria-associated endoplasmic reticulum membrane (GO:0044233)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4275]
* **PTHR ID & PTN node:**

GO:0044233 | mitochondria-associated endoplasmic reticulum membrane | IBA with PTN001784663 ,

* **Sequences with problematic annotation (ID + gene/protein name):**

atg14 generally

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I would not annotate atg14 to this term, but I can see why it was.

The problem is probably more with the term name:
mitochondria-associated endoplasmic reticulum membrane (GO:0044233)
 the def is 

Definition | Parents
-- | --
A zone of apposition between endoplasmic-reticulum and mitochondrial membranes, structured by bridging complexes. These contact sites are thought to facilitate inter-organelle calcium and phospholipid exchange.

atg14 is not part of this structure.

A better term might be
omegasome (GO:1990462)

Definition | Parents
-- | --
Omega-shaped (as in the Greek capital letter) intracellular membrane-bounded organelle enriched in phosphatidylinositol 3-phosphate and dynamically connected to the endoplasmic reticulum. Omegasomes are the first step of the formation of autophagosomes via the phagophore assembly sites.

which is located at the ER membrane?

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Done
