### ISSUE TITLE
PTN001278732 not nuclear membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4277]
* **PTHR ID & PTN node:**

GO:0005637 | nuclear inner membrane | IBA with PTN001278732 , S000003623 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC17G8.01c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

1987
Yeast tRNA ligase is an enzyme required for tRNA splicing. A study by indirect immune fluorescence shows that this enzyme is localized in the cell nucleus. At higher resolution, studies using indirect immune electron microscopy show this nuclear location to be primarily at the inner membrane of the nuclear envelope, most likely at the nuclear pore. There is a more diffuse, secondary location of ligase in a region of the nucleoplasm within 300 nm of the nuclear envelope.

I would not annotate to "nuclear membrane". Maybe "nuclear periphery"?

GO:0034399 
nuclear periphery
Definition ([GO:0034399 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0034399))
The portion of the nuclear lumen proximal to the inner nuclear membrane.

@srengel

**Comment by ValWood** [comment]
@srengel  this might be ok, some tRNA things do seem to be IM attached....

**Comment by marcfeuermann** [comment]
I do have any better CC primary GO term to PAINT. I've annotated to the parent nucleus.
