### ISSUE TITLE
Adh-related does not have oxidoreductase activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4279]
* **PTHR ID & PTN node:**
PANTHER:PTN000672121
PANTHER:PTN001212167
short-chain dehydrogenase/reductase family 9c PTHR43313

* **Sequences with problematic annotation (ID + gene/protein name):**
Dmel: Adhr; FBgn0000056
http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0000056
Adhr is established as an inactive enzyme: PMID:8170369 ..Gly 14 is known to be essential for both ADH activity and NAD binding, since the EMS-induced AdhN11 mutation of D. melanogaster
is substituted by an aspartic acid residue at this site. ADH from this mutant strain is inactive and has a lower affinity
for S-AMP, a competitive inhibitor of coenzyme binding. ADHR protein lacks Gly 14.

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
*Block propagation of 
steroid dehydrogenase activity
steroid metabolic process
steroid dehydrogenase activity

**Comment by marcfeuermann** [comment]
Thanks for pointing this out. I've blocked annotations for all leaves that miss the important residue. Hope this will clean a lot the tree.

**Comment by sjm41** [comment]
Looks like Adhr is now getting annotated with "oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor" via PTN002449290 (PTHR44229)

**Comment by marcfeuermann** [comment]
Argh....
I suspect that my NOT annotations have been lost during PANTHER library version update. The family looks now very different as well as the annotations. And all my NOT annotations disappeared. I've added them again. Will have to investigate this further with the PAN-GO/PAINT team to avoid this to happen again.
