### ISSUE TITLE
Review annotations to GO:1990356  sumoylated E2 ligase complex

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4281]
The proposal has been made to obsolete GO:1990356 sumoylated E2 ligase complex as it is not a stable complex. 

https://docs.google.com/spreadsheets/d/1gDIIKlPQRiSE4joU0OViypfQj0gC9PFPKMCMliTMHdo/edit#gid=0

There are 2 annotations, by 1 BHF and 1 by CACAO. 

Thanks, Pascale

**Comment by RLovering** [comment]
this ticket can now be closed
