### ISSUE TITLE
PTN000365540, regulation, or not????

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4285]
* **PTHR ID & PTN node:**

GO:0032956 | regulation of actin cytoskeleton organization | IBA with PTN000365540 , Q13576 , DDB_G0288977 , DDB_G0269140

* **Sequences with problematic annotation (ID + gene/protein name):**

rng2 in pombe is a core part of contractile ring assembly, acting as an adaptor for myosin at the cell division site. A researcher  who has worked on rng for many years mentioned that it has no detected GTPase activator  activity (which is I suspect how the regulation annotation arises)

Even is it was a GTPase, should it have a 'regulation' annotation if it is part of the pathway?
This might be a good example for the "regulation discussion" at the upcoming GO meeting. GTPases are particularly problematic
because they are 'part of' process, but they are regulation. I am still struggling how to annotate these, because if they are "regulation of" they will be excluded from enrichment and slims. 

@vanaukenk 
@pgaudet

**Comment by marcfeuermann** [comment]
Indeed, we need clear rules about this. Many gene families are impacted. I'll keep this one open until we have a consensus about how annotating such cases.

**Comment by marcfeuermann** [comment]
So, meeting over, not sure we got a consensus. I've corrected this several weeks ago. Close this for now.

**Comment by ValWood** [comment]
planned for discussion on upcoming curation calls!

**Comment by marcfeuermann** [comment]
Okay thanks. I think your proposal is the good one. Lets see...
