### ISSUE TITLE
Review annotations to GO:0040035 hermaphrodite genitalia development and descendants

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4287]
The proposal has been made to obsolete GO:0040035 hermaphrodite genitalia development and GO:0048815 hermaphrodite genitalia morphogenesis.

There are 34 EXP annotations, 22 from Uniprot, 12 from WB

https://docs.google.com/spreadsheets/d/1NOEvv5x5HA2pMDXbIMWPtDVnlvm0v00XHU_w0u1P8H8/edit?usp=sharing

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-announcements/issues/378

**Comment by Antonialock** [comment]
I think this can close?

**Comment by pgaudet** [comment]
@raymond91125 @vanaukenk have the WB annotations been fixed ?

**Comment by pgaudet** [comment]
All done
