### ISSUE TITLE
Change go-rel to allow SO in Protein2GO

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4289]
Hello, 

From @RLovering 
From our last discussion I think it was agreed that the specific motif binding GO terms would be removed and instead people should use
 
GO:0000978 RNA polymerase II cis-regulatory region sequence-specific DNA binding
And then use the AE field eg.: has_input(SO:0001158)
 
UCL has 36 annotations to GO:0070888 E-box binding which will change to
GO:0000978 RNA polymerase II cis-regulatory region sequence-specific DNA binding
AE has_input(SO:0001158)
 
However, Protein2GO does not allow the inclusion of ANY SO IDs therefore it is not possible for me to make these changes. Also I don’t want to ask Alex to make these changes unless Protein2GO is changed so that it allows SO IDs to be included.
 
Please would you confirm that SO IDs need to be allowed or whether to go back to the previous decision of creating a GO term for each motif.
 
The other problem I have is that SO does not have IDs for at least 3 GO term equivalents eg:
 
·  SO does not have the term: vitamin D response element whereas GO has GO:0070644 vitamin D response element binding
·  SO does not have the term: serum response element whereas GO has GO:0010736 serum response element binding
·  SO does not have the term: carbohydrate response element whereas GO has GO:0035538 carbohydrate response element binding
 
Ideally I would not want these terms removed before the SO IDs were created. Not that I have requested these terms but I will if you confirm that GO is going to delete the terms
 
Thanks
 
Ruth

**Comment by pgaudet** [comment]
Discussing with @alexsign 

Annotations need to be updated from occurs_at to has_input. 
However has_input has the following ranges for SO: 
*  SO:0000704 gene
* SO:0000673 transcript
* SO:0000839 polypeptide_region



Example SO:0001158  E_box_motif is indirectly child of gene so this _should_ work

**Comment by pgaudet** [comment]
Added [SO:0001683 sequence motif](http://www.sequenceontology.org/browser/current_svn/term/SO:0001683) to local_range for  'has input' in gorel-edit.owl 

PR: https://github.com/geneontology/go-ontology/compare/annotation-4289?expand=1

**Comment by pgaudet** [comment]
Added SO:0001683 to [db-xrefs.yaml ](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml)

PR: https://github.com/geneontology/go-site/pull/1919

**Comment by RLovering** [comment]
Hi @alexsign 

SO is still not an option in Protein2GO, any ideas about how to make this available?

Thanks

Ruth

**Comment by pgaudet** [comment]
Now working in P2GO !!!! 

@RLovering
