### ISSUE TITLE
Review annotations to GO:0071921 cohesin loading and GO:0061774 cohesin unloading

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4296]
The proposal has been made to obsolete GO:0071921 cohesin loading and GO:0061774 cohesin unloading

Annotations are here: 
https://docs.google.com/spreadsheets/d/1_nLZwQT3IOOi-MRQEyYxbdHc2Inl5v7FbnhBC5npKck/edit#gid=0

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Contributor   (Assigned by) | Number of annotations
--|--
BHF-UCL | 2
ComplexPortal | 1
FlyBase | 5
PomBase | 33
SGD | 5
UniProt | 13
WB | 1

</body>

</html>

**Comment by srengel** [comment]
SGD done.

**Comment by sandraorchard** [comment]
Complex Portal done (but as usual you will have to wait for it to come through the release cycles)

**Comment by Antonialock** [comment]
uniprot done

**Comment by RLovering** [comment]
UCL done

**Comment by ValWood** [comment]
PomBase has 5 left.
These are to 


GO:1905412 | negative regulation of mitotic cohesin loading
and 
GO:1905406 | positive regulation of mitotic cohesin loading

I think these were going to  be renamed to 
positive/negative regulation of mitotic sister chromatin cohesion (which do not currently exist)



[GO:1905406](https://www.pombase.org/term/GO:1905406)	[positive regulation of mitotic cohesin loading](https://www.pombase.org/term/GO:1905406)

**Comment by pgaudet** [comment]
@ValWood Did we want to obsolete these? This is not yet done, I cannot find any ticket. Would you please create an obsoletion ticket if you want to go ahead with this?

**Comment by ValWood** [comment]
Yes I took the ticket.

**Comment by pgaudet** [comment]
Replaced by https://github.com/geneontology/go-annotation/issues/5501
