### ISSUE TITLE
PTN000281062, not DSB repair?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4302]
* **PTHR ID & PTN node:**

GO:0006302 | double-strand break repair | IBA with Q7Z2E3 , PTN000281062 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC18.09c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I don't see any evidence that apratxin is involved in DSB-repair. When I click on this link I see only the PAINT source (although he UniProt description mentions DSB repair, i am not sure that this is correct.

cc @Antonialock

**Comment by Antonialock** [comment]
I cannot see mention of double-strand break repair in pmid:17519253 - only single strand break repair. I will remove the GO annotation from the PMID (I think that's the only GO DSB reference & review the UniProt function statement (it has a few other pmids associated with the sentence mentioning dsb repair).

**Comment by Antonialock** [comment]
also did some other cleaning of the GO annotation. I think ssDNA repair is sufficient? Iit doesn't need the response to H2O2 / DNA damage blah, it seems superfluous in this context

**Comment by Antonialock** [comment]
hmm. actually DSB repair for aprataxin might be ok from other publications


pmid: 17276982
We suggest that Aprataxin may have a general proofreading function in DNA repair, removing DNA adenylates as they arise during single-strand break repair, double-strand break repair, and in base excision repair

27262532
Several additional DNA end-specific phosphodiesterases, including TDP1, TDP2 and aprataxin are available to resolve various non-nucleotide moieties at DSB ends. This review summarizes the biochemical specificities of these enzymes and the evidence for their participation in the NHEJ pathway. 

 24656613
DNA end processing is required to remove damaged DNA and non-ligatable end groups at the termini of the DSB to facilitate ligation. End processing in response to IR-induced damage may include a variety of enzymes including polynucleotide kinase/phosphatase (PNKP), aprataxin and PNKP related protein (APLF), DNA polymerases and Artemis

**Comment by Antonialock** [comment]
I will leave it in the Uniprot function comment.

**Comment by ValWood** [comment]
Its probably Ok to leave the GO annotation in that case
. It might be better to not to transfer until there is better evidence. 
I will ask around.

24656613 says 'may include'
I also wonder if this is really a part of these pathways, or is a separate pathway to fix toxic intermediates that may arise during the repair processes,rather than being part of these specific pathways?

Anyway it seems unclear....
