### ISSUE TITLE
Fix UniRule mappings

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4310]
Hi @pedruzzi 

[UniRule:UR000865637](https://www.uniprot.org/unirule/UR000865637) and [UniRule:UR000865639](https://www.uniprot.org/unirule/UR000865639) maps to GO:0044662disruption by virus of host cell membrane , which has been obsoleted, see https://github.com/geneontology/go-ontology/issues/24077. 

We (the  multispecies working group) suggest that you reannotate to GO:0051673 disruption of membrane integrity in another organism. 

Thanks, Pascale

**Comment by suzialeksander** [comment]
closing as this should appear in the error reports
