### ISSUE TITLE
26S proteasome regulatory subunit 10B (IPR035263)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4316]
* **InterPro ID / label**
26S proteasome regulatory subunit 10B (IPR035263)

* **Description of issue**
This entry currently has the GO MF "ATP hydrolysis activity (GO:0016887)".
Can you change that to the more informative "proteasome-activating activity (GO:0036402)" to match the GO annotation on its InterPro parent entry (IPR005937) and all its sibling entries?

**Comment by sarach06** [comment]
Dear Steven,
PANTHER subfamily signatures have been deleted in InterPro from PANTHER 17.0, and this will be reflected in our next release, InterPro 91.0. This entry included a subfamily which has been removed, then the mapping for this set of sequences will correspond to the parent entry, IPR005937, as you mentioned. Hope this helps, let me know if you have any questions.
Best regards,
Sara

**Comment by sjm41** [comment]
Sounds good, thanks Sara
