### ISSUE TITLE
ARBA00027282 regulation of DNA metabolic process  (based on legacy annotation)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4317]
* **ARBA rule (ID and label):**

GO:0051052 | regulation of DNA metabolic process | IEA with ARBA00027282

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC6F6.17

* **Description of issue**

regulation. annotation has been removed

**Comment by pgaudet** [comment]
Should go away when ARBA runs again

**Comment by PedroRaposo** [comment]
Hi Val,
When you say the "regulation. annotation has been removed" are you saying that, in this moment the GO:0051052 (regulation of DNA metabolic process) has been removed from Q96UP3?
If I compare the flat files from 20212 to August of 2022 (https://www.uniprot.org/uniprotkb/Q96UP3/history?versions=60,115), before this was reported, I do not see GO:0051052 in either versions.
Was this removal in UniProt, or QuickGO, or PomBase, or in another resource?

**Comment by ValWood** [comment]
It is possible that the "regulation " annotation was on an ortholog. Sorry I should have recorded that. 
But this can close because it's all fixed now.
v
