### ISSUE TITLE
PTN004698611 Tea4 is a pseudokinase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4318]
* **PTHR ID & PTN node:**

GO:0004674 | protein serine/threonine kinase activity | IBA with Q92918 , O95747 , 621643 , FBgn0035001 , Q9Y6E0 , Q9Y4K4 , O94804 , Q9H2G2 , PTN004698611 , MGI:1346882 , DDB_G0286359 , Q12851 , FBgn0263395 , sid1 , MGI:1858416 , WBGene00001526 , Q8IVH8 , FBgn0023083 , WBGene00013355 , MGI:1917378 , Q9UEW8

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC12B10.14c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation 

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprotkb/Q10447/entry
lacks the active site Aspartate.

**Comment by marcfeuermann** [comment]
Indeed key residues are missing. Propagation blocked.
