### ISSUE TITLE
 PTN001427121 protein localization to kinetochore

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4325]
* **PTHR ID & PTN node:**

protein localization to kinetochore
mis12 |   | IBA with CAL0000180490 , PTN001427121 , S000000032 | Gaudet P et al. (2011)
spc7 |   | IBA with PTN002001209 , S000003061 | Gaudet P et al. (2011)

I think we should consider not transferring 'protein localization " annotations. For these am replacing by MF + process.

For example , in this case
"kinetochore adaptor" + substrate part of "kinetochore assembly" (if suitable). 
Also, If I have made 'localization' annotations, I always capture the localized protein, and this gets lost in the annotation transfer so it is not so meaningful.
@pgaudet  what do you think?

**Comment by ValWood** [comment]
Although this is not so important, I like to report everything I am filtering (otherwise it gets confusing)

**Comment by pgaudet** [comment]
Done
