### ISSUE TITLE
Problem with PAINT mapping of GO:0005886

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-annotation#4326]
Hello,

I was surprised to see that my non-membranous two-component system protein SasA has GO Mapping to plasma membranes… See Q55630, this is the DR line:
DR   GO; GO:0005886; C:plasma membrane; IBA:GO_Central.

I only find this GO in one of the SasA proteins, and with this evidence tag in 33 proteins in the file I’m looking at (sensor2.sp). 7 of the 33 do not have the KW membrane, and are not membrane proteins (well, one is a Dicty protein with so many Ns who knows about it…). So while this mapping is usually correct, it is not always correct.

Can you look into this please? Thanks,

Andrea

**Comment by marcfeuermann** [comment]
Hi Andrea,
Thank you for pointing out this Issue. I’ve looked at the PAINT annotation and in our current version, I cannot see any annotation with PAINT for this big family (PTHR43047). It is possible that the annotation with PAINT have been corrected or lost in the latest version of the phylogenetic trees recently implemented (PANTHER 17). This means that the annotation to plasma membrane should disappear in SP entries soon. This family is quite big and only few members have GO annotations, most of them not usable for PAINTing. Anyway, I will work on PTHR43047 as soon as the new version of the PAINT tool will be available, to be sure everything is clean.
Best regards,
Marc.
