### ISSUE TITLE
Tubulin-folding cofactor B, N-terminal ubiquitin-like domain (IPR045172)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4328]
* **InterPro ID / label**
Tubulin-folding cofactor B, N-terminal ubiquitin-like domain (IPR045172)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly TBCB (FBgn0034451/A1ZBM2)
Human TBCB (Q99426)

* **Description of issue**
Please check, but I think we can add the following GO terms to this entry:
alpha-tubulin binding (GO:0043014)
post-chaperonin tubulin folding pathway (GO:0007023)
tubulin complex assembly (GO:0007021)

See PMID: 28137948 as an extra ref.

**Comment by sarach06** [comment]
Hi Steven,
Many thanks. I have added these terms to this entry and the reference you provided. These changes will be visible in the next InterPro release (92.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
