### ISSUE TITLE
IPR030797 is associated with central nervous system development, but is found in fungi

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-annotation#4330]
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR030797/

This results in propagation of CNS development to fungi, e.g

https://www.uniprot.org/uniprotkb/A0A015JUY6/entry#function

Perhaps this could be turned into an ARBA rule, e.g. IF IPR030797 AND bilateria THEN CNS development

or just removed

**Comment by ValWood** [comment]
as far as I understood, the ARBA rules are developed independently of the InterPro mappings

**Comment by esperetta** [comment]
The ARBA rules use the InterPro signatures and taxonomy as conditions to aggregate protein sequences, but the actual annotation is disjoint from the InterPro annotation.  In fact, ARBA only learns from experimental annotations  (so InterPro2 Go mapping is excluded). 

ARBA GO annotations are based on the DR GO annotations in the SwissProt flat files which might (or not) have experimental GO annotations with an overlapping knowledge with InterPro GO annotations. 

I can see that this particular InterPro signature has now been deleted so it should not be available to ARBA.

**Comment by pgaudet** [comment]
Hi @sarach06, indeed this should now be OK.
