### ISSUE TITLE
dribble PMID:16542639 annotation to DNA binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4331]
Hi @federicaquaglia, I am contacting you with regard to a DisProt annotation.

Q9VPU8; dribble dbe PMID:16542639 (FBgn0020305)
https://www.ebi.ac.uk/QuickGO/annotations?reference=PMID:16542639

Has been annotated with 2x DNA binding when the paper shows it to be RNA binding and this has been annotated by the CAFA project.

Could you review this please?

**Comment by ValWood** [comment]
Please close if addressed

**Comment by hattrill** [comment]
It is still an issue:

![Screenshot 2023-08-31 at 09 38 45](https://github.com/geneontology/go-annotation/assets/11865746/58d897d2-944d-4a20-9634-f35b2c1ea912)

 nudging DisProt:

@federicaquaglia
@victorianugnes

**Comment by victorianugnes** [comment]
Hi all. Thank you for noticing and letting us know. The DNA binding function annotation has been removed from that protein entry.
