### ISSUE TITLE
NOT enables peptidase 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4337]
@sjm41 has added NOT peptidase activity GO:0008233 for these entries that have a "positive" IBA for children term. This bunch will be coming down the pipeline for you in the FB2022_06  release - 

**IBAs**

UniProtKB:A1ZBU9		enables	GO:0008234	cysteine-type peptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN001621808
UniProtKB:Q9VRE9		enables	GO:0019784	deNEDDylase activity	PMID:21873635	ECO:0000318	PANTHER:PTN008206918
UniProtKB:Q8IR04		enables	GO:0008239	dipeptidyl-peptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN000198379
UniProtKB:Q0KI25		enables	GO:0070006	metalloaminopeptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN000164250	
UniProtKB:Q7PLV6		enables	GO:0070006	metalloaminopeptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN000164250	
UniProtKB:Q9VTL4		enables	GO:0070006	metalloaminopeptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN000164250	
UniProtKB:Q9W2S7		enables	GO:0070006	metalloaminopeptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN000164250	
UniProtKB:Q9W2S8		enables	GO:0070006	metalloaminopeptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN000164250	
UniProtKB:Q9VC06		enables	GO:0004222	metalloendopeptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN000211184	
UniProtKB:X2JE21		enables	GO:0004222	metalloendopeptidase activity	PMID:21873635	ECO:0000318	PANTHER:PTN002628656	

IKRs from Steven:

UniProtKB:A1ZBU9	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:C01.UNB
UniProtKB:Q0KI25	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:M01.UNW
UniProtKB:Q7PLV6	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:M01.UNW
UniProtKB:Q8IR04	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:S09.UNB
UniProtKB:Q9VC06	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:M03.UNA
UniProtKB:Q9VRE9	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:C48.UNW
UniProtKB:Q9VTL4	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:M01.UNW
UniProtKB:Q9W2S7	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:M01.973
UniProtKB:Q9W2S8	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:M01.UNW
UniProtKB:X2JE21	NOT	RO:0002327	GO:0008233	GO_REF:0000047	ECO:0000320	MEROPS:M12.UNB

Here are the mappings UniProtKB -> FBgns & symbol, if that helps
A1ZBU9	FBgn0034513	CG13423
Q0KI25	FBgn0039064	CG4467
Q7PLV6	FBgn0058470	CG40470
Q8IR04	FBgn0266354	CG45002
Q9VC06	FBgn0039252	CG11771
Q9VRE9	FBgn0031157	CG1503
Q9VTL4	FBgn0036186	CG6071
Q9W2S7	FBgn0030223	CG2111
Q9W2S8	FBgn0030222	CG9806
X2JE21	FBgn0259110	mmd

If you could block propagation of children of peptidase activity for these genes

**Comment by marcfeuermann** [comment]
Hello,
Thanks for pointing out these issues and for your nice way to display the lists. Finally I've blocked all propagation of children of peptidase activity for these genes. Sorry for the delay, I had no stable access to the server these last weeks. We have improved our tool by highlighting key residues in the multi-sequence alignment (when they are known and annotated in UniPprot). This should slightly improve our IKR annotations ;-)
