### ISSUE TITLE
Review annotations to GO:0110148 biomineralization & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4338]
Dear all, 

The proposal has been made to obsolete GO:0110148 biomineralization & regulation children, see https://github.com/geneontology/go-ontology/issues/24213

There are 80 EXP annotations: 

Group | Number of annotations
-- | --
MGI | 66
UniProt | 9 
ZFIN | 5

Annotation review spreadsheet with suggestions for corrections is here: https://docs.google.com/spreadsheets/d/1ygIejQOrONTyuEk4UZyvHF5f3M6jqUnSVje973wPQPw/edit#gid=0

**Comment by pgaudet** [comment]
One possible replacement for some of these annotation could be a new term “inhibition of ectopic tissue mineralization", to annotate genes that increase levels of inorganic pyrophosphate, a mineralization inhibitor that prevents ossification/mineralization of non-bone tissue. This term would not be using the ‘negative regulation’, label, because it does not negatively regulate a normal process, but it would be a process that prevents an aberrant process. 

@hdrabkin @sramachand would that be helpful? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
We (MGI) plan to discuss this at group meeting tomorrow. Most likely YES, the new term might be helpful to rehouse those annotations.

**Comment by hdrabkin** [comment]
Doesn't 'ectopic' imply an 'abnormal' process?

**Comment by hdrabkin** [comment]
This needs to be discussed on ontology call

**Comment by pgaudet** [comment]
> Doesn't 'ectopic' imply an 'abnormal' process?

Yes, the idea of the term is to say that they is a pathway that counteracts the abnormal process.

**Comment by deustp01** [comment]
> Yes, the idea of the term is to say that they is a pathway that counteracts the abnormal process

But the original term encompasses all of normal mineralization, if I read the definition correctly, and the proposed term is confined to inhibition of a specific kind of biomineralization. Is that intended? What new parentage will be available for all the grandchildren that describe various tissue-specific (bone, shell, ...) mineralization processes?

**Comment by pgaudet** [comment]
@deustp01 
The definition is " A homeostatic process involved in the maintenance of non-mineral tissue, by preventing ectopic mineralization of non-bone tissue. " (see https://github.com/geneontology/go-ontology/issues/24228) - I can wider this if you have a better suggestion for wording this. As far as I can tell, this applies to the papers under review here, but maybe there are other cases that should also be covered.

**Comment by deustp01** [comment]
@ukemi @hdrabkin our concern is parentage. Consider [GO:0030282 bone mineralization](https://www.ebi.ac.uk/QuickGO/term/GO:0030282)
bone mineralization is_a biomineral tissue development (GO:0031214) is_a (GO:0110148) biomineralization.
Maybe I'm missing something here, but if GO:0031214 is edited (or replaced by a new term) to cover only prevention of ectopic mineralization, what becomes of the correct mineralization of tissues that are supposed to become bone?

**Comment by pgaudet** [comment]
We are not changing GO:0031214 

The proposal is to obsolete  the parent, GO:0110148 biomineralization, to distinguish between cellular biomineralization (of which so far there is a single example, [magnetosome assembly](https://github.com/geneontology/go-ontology/issues/24211)), and the biomineralization that occur in multicellular organisms. 

The review is about genes directly annotated to GO:0110148 biomineralization, GO:0110150 negative regulation of biomineralization, GO:0110151 positive regulation of biomineralization, to annotate them to something more specific.

**Comment by pgaudet** [comment]
@AndreaAuchincloss replaced the bacterial annotations

**Comment by sramachand** [comment]
ZFIN done
