### ISSUE TITLE
Review annotations to 'GO:1903118 urate homeostasis', 'GO:0097274 urea homeostasis' and 'GO:0097277 cellular urea homeostasis' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4342]
Dear all, 

The proposal has been made to obsolete  'GO:1903118 urate homeostasis', 'GO:0097274 urea homeostasis' and 'GO:0097277 cellular urea homeostasis', see https://github.com/geneontology/go-ontology/issues/24296. 

There are 3 MGI annotations to be reviewed:  
https://docs.google.com/spreadsheets/d/1I14NlniBFddMnXWLQZgAcGBTzA3c5SWtRpDtcKHdshw/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
pining @hdrabkin 
can you update these annotations?

**Comment by hdrabkin** [comment]
MGI done
