### ISSUE TITLE
Review annotations to GO:0033561 regulation of water loss via skin

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4345]
Dear all, 

The proposal has been made to obsolete GO:0033561 regulation of water loss via skin
see https://github.com/geneontology/go-ontology/issues/24298

Please review your annotations: 
https://docs.google.com/spreadsheets/d/1r4TA9SkerbQKUnV1f3Va03fe1uDMj3osPjCp0-EbwRA/edit#gid=0

**Comment by hdrabkin** [comment]
mgi done

**Comment by hdrabkin** [comment]
link to spreadsheet does not work

**Comment by pgaudet** [comment]
Thanks for letting me know, I updated the link.

**Comment by slaulederkind** [comment]
RGD finished.

**Comment by pgaudet** [comment]
Thanks everyone!
