### ISSUE TITLE
Review annotations to GO:0055069 zinc homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4346]
Dear all, 

For the BP refactoring, we are aiming to split organism-level process and cell-level process. We are now looking at 'GO:0055069 zinc homeostasis', this term will be obsoleted, and annotations rehoused under 
"cellular zinc ion homeostasis"
GO:0010312 detoxification of zinc ion

Please review your annotations: 

https://docs.google.com/spreadsheets/d/1smlSDXVM09y_Qa1NHETogQMLYuHOo7ODWonYCnpE0n8/edit#gid=0

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Group | Number of annotations 
-- | --
FlyBase | 7 - DONE
MGI | 1 - DONE
MTBBASE | 1 - DONE
ParkinsonsUK-UCL | 2 - DONE
TAIR | 5 - DONE
UniProt | 3 - DONE
WB | 1 - DONE
ZFIN | 5

Thanks, Pascale

</body>

</html>

**Comment by hdrabkin** [comment]
GO:0055069 is   | zinc ion homeostasis
Can't find any annotations to nickel ion homeostasis.

**Comment by pgaudet** [comment]
Sorry, this is indeed zinc homeostasis. MGI has 1 annotation.

**Comment by hattrill** [comment]
@pgaudet have done FlyBase annotations except one with NTR:https://github.com/geneontology/go-ontology/issues/24307

**Comment by hdrabkin** [comment]
MGI done

**Comment by vanaukenk** [comment]
WB done

**Comment by hattrill** [comment]
FB done

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
Obsoletion ticket: 
https://github.com/geneontology/go-ontology/issues/24464

**Comment by sramachand** [comment]
ZFIN done.
