### ISSUE TITLE
Review annotations to  'GO:0097056 selenocysteinyl-tRNA(Sec) biosynthetic process'.

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4347]
Dear all, 

The proposal has been made to obsolete  'GO:0097056 selenocysteinyl-tRNA(Sec) biosynthetic process'.
see https://github.com/geneontology/go-ontology/issues/24381

Please review your annotations: 
There is are 2 annotations, one by UniProt (changed), one by EcoCyc to  PMID:2007584 @amandamackie 

The annotations can be replaced by GO:0001717 conversion of seryl-tRNAsec to selenocys-tRNAsec. Automatic replacement will be done by the GO pipeline. 

Thanks, Pascale

**Comment by amandamackie** [comment]
The EcoCyc annotation has been changed. 

Amanda

**Comment by pgaudet** [comment]
Thanks
