### ISSUE TITLE
Review annotations to GO:0000453 enzyme-directed rRNA 2'-O-methylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4348]
SUBJECT: Proposal to obsolete GO:0000453 enzyme-directed rRNA 2'-O-methylation

Dear all, 

The proposal has been made to obsolete [GO:0000453] enzyme-directed rRNA 2'-O-methylation
The reason for obsoletion is that this term represents a molecular function.

Please review your annotations: 
https://docs.google.com/spreadsheets/d/1GCutZwmO-ixQcc2nsvUGOJZeisb_qPydShBgqYT_NXs/edit#gid=0

There are 4 experimental annotations to this  by EcoCyc.

There are 2 UniRule mapping, 
https://www.uniprot.org/unirule/UR000086060
https://www.uniprot.org/unirule/UR000166071
suggested replacement is rRNA processing GO:0006364

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/24318

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by pgaudet** [comment]
Term is now obsolete.
Any remaining annotation will appear in error reports.
