### ISSUE TITLE
Review annotations to GO:0046838 phosphorylated carbohydrate dephosphorylation and descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4349]
Dear all, 

The proposal has been made to obsolete GO:0046838 phosphorylated carbohydrate dephosphorylation and descendants

GO:0046838 phosphorylated carbohydrate dephosphorylation
GO:0033518 myo-inositol hexakisphosphate dephosphorylation
GO:0046855 inositol phosphate dephosphorylation

see https://github.com/geneontology/go-ontology/issues/24269
Reason for obsoletion, these terms represent Molecular function terms.

Please review your annotations: 
https://docs.google.com/spreadsheets/d/1xwZBzG67gWflfgmofDPPZeXv4dfzenWapLIRncfmIQI/edit#gid=0

**Comment by ValWood** [comment]
@pgaudet could you tag:
(1) AgBase
(1) CGD
(1) EcoliWiki

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by srengel** [comment]
tagging @marekskrzypek for the CGD annotation

**Comment by ValWood** [comment]
I missed these off:
InterPro:IPR000760
InterPro:IPR033942
InterPro:IPR022337
InterPro:IPR017361
UniRule:UR001029754

**Comment by ValWood** [comment]
@sarach06  not enough room to tag everyone...

**Comment by ValWood** [comment]
I missed these
GO:0046855
InterPro | IPR045849
InterPro | IPR046985
GO:0046838
InterPro | IPR045204

**Comment by marekskrzypek** [comment]
CGD done

**Comment by tberardini** [comment]
TAIR done (there are 3 other Arabidopsis annotations but made by UniProt, that I couldn't update)

**Comment by hattrill** [comment]
FB Done

**Comment by sarach06** [comment]
Dear Val,
Thank you very much. I have reviewed these entries and removed the terms you mentioned. These changes will be visible in the next InterPro release.
Best wishes,
Sara

**Comment by slaulederkind** [comment]
RGD is finished.  Thanks to whoever removed the ISO annotations.

**Comment by srengel** [comment]
SGD done.

**Comment by ukemi** [comment]
MGI done

**Comment by ValWood** [comment]
I am going to go ahead with this one, it seems most are now done

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
