### ISSUE TITLE
Review annotations to of histone amino acid axis of classification (in favour of histone class and residue) 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4350]
Dear all, 

The proposal has been made to obsolete 
GO:0018024    histone lysine N-methyltransferase activity
GO:0008469   histone arginine N-methyltransferase activity
GO:0035184    histone threonine kinase activity
GO:1990259 histone glutamine N-methyltransferase activity
GO:0035174    histone serine kinase activity
 GO:0018110   histone arginine kinase activity
 GO:0035400  histone tyrosine kinase activity
 GO:0140792 histone tyrosine phosphatase activity
 GO:0140790 histone serine/threonine phosphatase activity

GO TERM ID: GO TERM
see https://github.com/geneontology/go-ontology/issues/24397

Please review your annotations:

**Comment by ValWood** [comment]
I need to finish this ticket

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
