### ISSUE TITLE
Review annotations to GO:0048478 replication fork protection

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4352]
Dear all, 

The proposal has been made to obsolete GO:0048478 replication fork protection
see 
https://github.com/geneontology/go-ontology/issues/24151

Please review your annotations: 
https://docs.google.com/spreadsheets/d/1CCaVywVEdnyUE01z7o6HgMvrzAJj3kpYVNql8kYEE9Y/edit#gid=0

30 EXP annotation
PomBase 12
SGD 10
UniProt 3
Complex Portal 1

There are 2 mappings:
InterPro:IPR012923
UniRule:UR001184765

For replacement consider:
GO:0031297 replication fork processing
or some other DNA metabolism  or checkpoint response term.

Note that the term "replication fork protection complex" will remain

**Comment by hattrill** [comment]
FB done

**Comment by sarach06** [comment]
Dear Val, 
Thank you very much. I have replaced this term for GO:0031297. The changes will be available in the next InterPro release.
Best regards,
Sara

**Comment by Antonialock** [comment]
Uniprot done

**Comment by Antonialock** [comment]
(not sure how the count above was done? There were 7 Uniprot annotations)

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by ValWood** [comment]
Everybody says they are done, thanks!
