### ISSUE TITLE
Review annotations to GO:0000737 DNA catabolic process, endonucleolytic GO:0000738 DNA catabolic process, exonucleolytic

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4354]
Dear all, 

The proposal has been made to obsolete 
GO:0000737 DNA catabolic process, endonucleolytic 
GO:0000738 DNA catabolic process, exonucleolytic
see https://github.com/geneontology/go-ontology/issues/24075

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/19OJQYaxbv2PLVrfkWScPAByVDqUIwp1pAwiWIL8MKys/edit#gid=0

Impacted groups: 
   2 ARUK-UCL
   3 EcoCyc
   4 FlyBase
   3 MGI
   2 SGD
   1 TAIR
  13 UniProt
  12 WB

----

Mappings that need to be reviewed:
 InterPro | IPR033309

Thanks.

**Comment by tberardini** [comment]
TAIR done

**Comment by sarach06** [comment]
Dear Val,
Thank you very much for this. I have replaced this term for GO:0006308 (DNA catabolic process) in this entry. This will be visible in the next InterPro release.
Best,
Sara

**Comment by Antonialock** [comment]
uniprot done.

**Comment by RLovering** [comment]
UCL done

**Comment by ValWood** [comment]
I'm not sure if the 4 FlyBase are done @hattrill  but I will go ahead with this one...

**Comment by pgaudet** [comment]
WB are also not marked as done

**Comment by ValWood** [comment]
@vanaukenk  are these done? The first one is flagged as done, and the majority are to the same gene, but there are some additional ones unflagged.

**Comment by vanaukenk** [comment]
@ValWood I will try to finish these today.

**Comment by vanaukenk** [comment]
WB is done.

**Comment by hattrill** [comment]
FB done

**Comment by ValWood** [comment]
@RLovering @hattrill @LiNiMGI  ignore. These are done

**Comment by pgaudet** [comment]
According to the spreadsheet, these are all done.
