### ISSUE TITLE
Review annotations to GO:0035103 SBP sterol regulatory element binding protein cleavage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4355]
Dear all, 

The proposal has been made to obsolete GO TERM ID: GO TERM
see https://github.com/geneontology/go-ontology/issues/24454

Mappings that need to be reviewed: (InterPro2GO, ~UniProt-Keywords, UniRule~) 

InterPro | IPR038967 | DSC E3 ubiquitin ligase complex subunit 4-like

Thanks.

**Comment by pgaudet** [comment]
(This term only has a single UniProt mapping)

**Comment by ValWood** [comment]
InterPro?

**Comment by blazaropinto** [comment]
Hi,

Thanks for that. I replaced this term with GO:0032933. The changes will be available in InterPro 93.0.

Best regards,
Beatriz
