### ISSUE TITLE
InterPro:IPR004712 & InterPro:IPR032516 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4356]
* **InterPro ID / label**

InterPro:IPR004712 & InterPro:IPR032516 

are annotated to GO:0030004 cellular monovalent inorganic cation homeostasis, which will get obsoleted, see https://github.com/geneontology/go-ontology/issues/24455

Based on the InterPro entries, this annotation could perhaps be changed to GO:0042391 regulation of membrane

Thanks, Pascale

**Comment by blazaropinto** [comment]
Dear Pascale,

I agree, I replaced this GO term in both entries. The changes will be available in InterPro 93.0.

Best regards,
Beatriz

**Comment by pgaudet** [comment]
Thanks !
