### ISSUE TITLE
Review annotations to GO:0030004 cellular monovalent inorganic cation homeostasis and GO:0030320 cellular monovalent inorganic anion homeostasis 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4357]
Dear all, 

The proposal has been made to obsolete GO:0030004 cellular monovalent inorganic cation homeostasis and GO:0030320 cellular monovalent inorganic anion homeostasis  (and related terms), see [[Obsoletion notice: unnecessary grouping terms in the chemical homeostasis branch]](https://github.com/geneontology/go-ontology/issues/24455)

* There is one MGI annotation to  GO:0030320 
* 2 InterPro annotations to GO:0030004: InterPro:IPR004712 & InterPro:IPR032516 (Na+/H+ antiporter) >> change to GO:0042391 regulation of membrane potential
* 4 EXP SGD to GO:0030004

The terms will be replaced_by other terms as described in the ontology ticket, so for EXP annotations these should be automatically replaced. 

@sarach06 @blazaropinto : Are InterPro mappings also automatatically updated when a term is obsoleted with a replaced_by tag, or do you need to manually update them? 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
These two InterPro entries have been updated. The mappings are not automatically updated when a term is obsoleted, we have warnings once the term is obsoleted and then we manually change it. Or if we receive this information from you, we updated them before. Makes sense? Let me know if you have any questions,
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks for the info @sarach06 , this is very helpful. 

Pascale

**Comment by hdrabkin** [comment]
checked replacement; done

**Comment by srengel** [comment]
SGD appears to be done as the replacement seems to have already gone through.  however, it looks like there are a couple of new-ish annotations by InterPro:

NHA1	YLR138W	involved in	GO:0030004	cellular monovalent inorganic cation homeostasis	biological process		IEA with IPR004712	computational	InterPro	2022-11-09	DDB, et al. (2001)
NHA1	YLR138W	involved in	GO:0030004	cellular monovalent inorganic cation homeostasis	biological process		IEA with IPR032516	computational	InterPro	2022-11-09	DDB, et al. (2001)

**Comment by pgaudet** [comment]
@sarach06 @blazaropinto 

Can you update the following entries: 
*** IPR004712 and  IPR032516**
* * change [cellular monovalent inorganic cation homeostasis (GO:0030004)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0030004) to GO:0036376 sodium ion export across plasma membrane and GO:0120029 'proton export across plasma membrane'

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much for this. I have added these terms to both entries. These changes will be available in InterPro 93.0.
Best regards,
Sara

**Comment by pgaudet** [comment]
Thanks!
