### ISSUE TITLE
Review annotations to GO:0035784 nickel cation homeostasis

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4358]
Dear all, 

The proposal has been made to obsolete GO:0035784 nickel cation homeostasis
see https://github.com/geneontology/go-ontology/issues/24465

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/148hiLS-U4JuzJH1Bn8upT0Y2tlC6UKGZ2YXdg0r93qc/edit#gid=0

Impacted groups: 
EcoCyc 1 EXP
----

Thanks.

**Comment by pgaudet** [comment]
EcoCyc done , see https://github.com/geneontology/go-ontology/issues/24465#issuecomment-1336539926
