### ISSUE TITLE
bur6 not epsilon DNA polymerase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4360]
Hi,

Can you check up on there for me?
~bur1~ bur6 is a transcription regulator, not epsilon DNA polymerase
I  think maybe  CP meant to annotate cdc20 from this paper?
Val

UniProtKB:Q10315 | bur6 | located_in | GO:0008622    epsilon DNA polymerase complex | ECO:0005547   NAS | PMID:9605404 |   | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | ComplexPortal |  

UniProtKB:Q10315 | bur6 | involved_in | GO:0006261    DNA-templated DNA replication | ECO:0005547   NAS | PMID:9605404 |   | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | ComplexPortal

UniProtKB:Q10315	bur6	located_in	[GO:0008622](https://www.ebi.ac.uk/QuickGO/term/GO:0008622)    epsilon DNA polymerase complex	[ECO:0005547](https://www.ebi.ac.uk/QuickGO/term/ECO:0005547)   NAS	PMID:9605404	
284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843)	ComplexPortal	
UniProtKB:Q10315	bur6	involved_in	[GO:0006261](https://www.ebi.ac.uk/QuickGO/term/GO:0006261)    DNA-templated DNA replication	[ECO:0005547](https://www.ebi.ac.uk/QuickGO/term/ECO:0005547)   NAS	PMID:9605404	
284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843)	ComplexPortal

@kalpanap

**Comment by ValWood** [comment]
Also I'm wondering why NAS was used with a publication?

**Comment by ValWood** [comment]
I'm confused...

**Comment by sandraorchard** [comment]
I think everything that is annotated to "ECO:0005547 ! biological system reconstruction evidence based on inference from background scientific knowledge used in manual assertion" in the COmplex Portal has been mapped to NAS to stop you all getting a plethora of emails to say we weren't supplying all the information required for its previous mapping. We have to use ECO:000547 a lot on entries as you tend not to get a single strong piece of evidence that a complex is involved in a process or function, but more an indication based on KO's/over-expression of individual protein components.

**Comment by pgaudet** [comment]
@ValWood @sandraorchard 
Is this still an issue? 
@ValWood is this about bur1, bur6 or cdc20?

**Comment by ValWood** [comment]
The annotations still exist in the Uniprot entry:
https://www.uniprot.org/uniprotkb/Q10315/entry
complex Portal need to fix. I think it's a case of mistaken identity.

bur6 is a transcription regulator, not epsilon DNA polymerase
I think maybe CP meant to annotate cdc20 but annotated bur6 bymistake?

**Comment by sandraorchard** [comment]
Sorted locally but the COmplex Portal and IntAct have fallen victim of the EBI server migration and not managed a release for some time. Hoping to get on out by next month.

**Comment by ValWood** [comment]
OK will close!
tks
