### ISSUE TITLE
Review annotations to GO:0008022 protein C-terminus binding

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4362]
Dear all, 

The proposal has been made to obsolete GO:0008022 protein C-terminus binding;
see https://github.com/geneontology/go-ontology/issues/24152.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1_wBFkMfYvRG2f6lBZTvuffMHkqpeTKJhvBjqd_Ircyk/edit#gid=0

Impacted groups: 
AgBase 4 @jinhuiz
ARUK-UCL 6 @RLovering
BHF-UCL 9
CACAO 1 @dsiegele
CAFA 12 @Antonialock
HGNC-UCL 3 
MGI 23 @krchristie
RGD 108 @slaulederkind
TAIR 2 @tberardini
UniProt 168 @Antonialock
WB 8 @vanaukenk

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

InterPro | IPR017375 | Peroxisome assembly protein 12 @sarach06

Thanks.

**Comment by tberardini** [comment]
TAIR done

**Comment by Antonialock** [comment]
Uniprot done. Most terms updated, evidence and with/from+ extension fixed where needed.

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
