### ISSUE TITLE
Review annotations to GO:0047485 protein N-terminus binding

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4363]
Dear all, 

The proposal has been made to obsolete GO:0047485 protein N-terminus binding
see https://github.com/geneontology/go-ontology/issues/24486

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1oUZcu9wJu1Pov77Vp3LyVEMhwuNNJNjy76UuSii0Mig/edit#gid=0

Impacted groups:
ARUK-UCL 1@RLovering
BHF-UCL 2 @RLovering
CAFA 8 @Antonialock
HGNC-UCL 1 @RLovering
MGI 10 @krchristie
RGD 48 @slaulederkind
TAIR 1 @tberardini
UniProt 94 @Antonialock
WB 2 @vanaukenk

----

Mappings that need to be reviewed: 
None

Thanks.

**Comment by hdrabkin** [comment]
mgi done

**Comment by tberardini** [comment]
TAIR done

**Comment by Antonialock** [comment]
Uniprot fixed. Most had been changed already, I filled in interaction partner and fixed evidence code where required.
