### ISSUE TITLE
Review annotations to GO:0031997 N-terminal myristoylation domain binding

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4365]
Dear all, 

The proposal has been made to obsolete  GO:0031997 N-terminal myristoylation domain binding
see https://github.com/geneontology/go-ontology/issues/24486

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1bDS--JYapbVWa3cn70QrxXNLdhnU94cc8ZQZetweVT0/edit#gid=0

Impacted groups: 
UniProt 3 

----

Mappings that need to be reviewed: none

Thanks.

**Comment by Antonialock** [comment]
done
