### ISSUE TITLE
Review annotations to GO:0010252 auxin homeostasis 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4366]
Hi @tberardini @lreiser 

For the work on homeostasis, I'd like to know whether GO:0010252 auxin homeostasis has been used to mean 'intracellular auxin homeostasis' or 'multicellular organism-level auxin homeostasis', or both. I would appreciate it if you could look at the annotations and let me know exactly how this term has been used. 

https://docs.google.com/spreadsheets/d/1P5lP-YQyZA-FGxOutxF0lwG9XGNtkdI4GZn1CBhbb_w/edit#gid=0

Thanks, Pascale

**Comment by lreiser** [comment]
1. Looking at the definition of the term
A homeostatic process that maintains an endogenous steady-state concentration of primary auxin, or constant level of auxin in a biological system, by a number of biochemical processes including transport, biosynthesis, catabolism and conjugation. Source: [PMID:22504182](http://www.ncbi.nlm.nih.gov/pubmed/22504182)


2. Quick literature scan shows examples of   'intracellular auxin homeostasis' (https://www.nature.com/articles/nature11001) though the majority of the annotated genes would fall under 'intercellular or organismal /organ level".  For example, in plants auxin gradients provide important positional information for things like epidermal cell type patterning or specifying organizing centers of meristems (stem cell niches.) Some of the annotated genes include auxin influx and efflux carriers that are polarly localized within cells.

I would say that plant exhibit both classes. 
@tberardini ...sound right to you?

**Comment by tberardini** [comment]
> I would say that plant exhibit both classes.

Sounds right to me.

**Comment by pgaudet** [comment]
OK, so I will obsolete the term and create two more specific terms. 

If you can 'easily' tell whether the non TAIR annotations are 'intracellular' or 'organism-level' I would appreciate it if you could put it in the spreadsheet, so I can reannotate. 

Thanks, Pascale

**Comment by lreiser** [comment]
Pascale, I looked at the non TAIR annotations and made comments. 
I will work on the TAIR set....

**Comment by lreiser** [comment]
@pascale- when we have the new terms I can make the changes in TAIR_ I reviewed the set.

**Comment by pgaudet** [comment]
The two terms have been created: 
https://github.com/geneontology/go-ontology/issues/24555

**Comment by lreiser** [comment]
@pgaudet  all of the tair ones are done- the only Arabidopsis annotations left are from other groups

**Comment by tberardini** [comment]
Removing Leonore and myself from this ticket since she has addressed all the TAIR-sourced annotations.
