### ISSUE TITLE
Indigoidine synthase A-like (IPR022830)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4369]
* **InterPro ID / label**
Indigoidine synthase A-like (IPR022830) [homologous superfamily]

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly CG2794 (FBgn0031265/Q9VPR3)

* **Description of issue**
GO term should be removed or changed from "pseudouridylate synthase activity (GO:0004730)" to "pseudouridylate synthase activity (GO:0004730)"
This is same issue as #3608, but we didn't spot that the homologous superfamily record was also affected.

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for pointing that out. I've changed this term. The changes will be available in InterPro 93.0.

Best regards,

Beatriz

**Comment by sjm41** [comment]
Thanks!
