### ISSUE TITLE
Review annotations to  GO:0061088 regulation of sequestering of zinc ion and + and - children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4370]
Dear all, 

The proposal has been made to obsolete GO:0061088 regulation of sequestering of zinc ion and + and - children 
see https://github.com/geneontology/go-ontology/issues/24552

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1VIQFXYiWlayAlddZD9tj1NFb7w9h89wGhuZPhZCsdFs/edit#gid=0

Impacted groups: 
BHF 5 annotations

Thanks, Pascale

**Comment by RLovering** [comment]
UCL done
