### ISSUE TITLE
Review annotations to  GO:0070893 transposon integration & regulation children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4373]
Dear all, 

The proposal has been made to obsolete  GO:0070893 transposon integration & regulation children 
see https://github.com/geneontology/go-ontology/issues/24560

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1s6Y0ojEltq_Rb8rG1Dq0TwSz2HEqtkdm1BIAm_UVbfo/edit#gid=0

**Impacted groups:** 

Group | Number of annotations
-- | --
EcoCyc | 1
FlyBase | 1
SGD | 4
UniProt | 3 (fixed)
WB | 1

----

**Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule)** 
No mappings

Thanks.

**Comment by srengel** [comment]
SGD done.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by vanaukenk** [comment]
WB done

**Comment by pgaudet** [comment]
1 FB left @hattrill

**Comment by hattrill** [comment]
fb done
