### ISSUE TITLE
IPR046374 (Protein disulfide-isomerase A5, TRX (a) domain)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4375]
* **InterPro ID / label**
IPR046374 (Protein disulfide-isomerase A5, TRX (a) domain)

* **Example sequences with problematic annotation (ID + gene/protein name):**
D. melanogaster CG9302 (FBgn0032514/Q9VJZ1) and ERp60 (FBgn0033663/Q3YMU0)

* **Description of issue**
I don't see any evidence from the description or the EC xrefs on this entry for the associated oxidoreductase term (protein-disulfide reductase activity (GO:0015035)).  Can you check?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I removed the term from this entry as I didn't find evidence to support its addition. The changed will be visible in InterPro 93.0.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
