### ISSUE TITLE
Review annotations to GO:ID GO:0055065 metal ion and GO:0055076 transition metal ion homeostasis & cellular children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4379]
Dear all, 

The proposal has been made to obsolete 
* GO:0055065 metal ion 
* GO:0055076 transition metal ion homeostasis
*  GO:0046916 cellular transition metal ion homeostasis 
*  GO:0006875 cellular metal ion homeostasis, 
see https://github.com/geneontology/go-ontology/issues/24570

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1BxrYp45PEyf0m71jxR4n_cQyrUPEkvmkiwcPneCekC8/edit#gid=0

Impacted groups: 

Group | Number of annotations
-- | --
CGD | 3
FlyBase | 8
MGI | 6
PseudoCAP | 2
RGD | 2
SGD | 3
TAIR | 8

----

**Note that in some cases 'GO:0140961 cellular detoxification of metal ion' would be more appropriate than 'homeostasis', in particular for toxic ions. Please dont hesitate to request children of GO:0140961 if needed.**

Thanks, 

Pascale

**Comment by hdrabkin** [comment]
@pgaudet , Why are annotations to GO:0006875 in this sheet if the point is to obsolete GO:0055065 and GO:0055076?
What am I missing here?

**Comment by pgaudet** [comment]
Hi @hdrabkin 

See the initial comment for this ticket - the 4 terms are being obsoleted; I thought 4 terms were too much for the title (I will edit to clarify)

**Comment by hdrabkin** [comment]
@pgaudet : sheet lists 2 GO:0055065. However, in Noctua, I can find no annotations from MGI using this term at all. Was this term in another review by chance?

**Comment by pgaudet** [comment]
sorry, these are ISOs, I dont know what they are there, I'll remove them.

**Comment by hdrabkin** [comment]
MGI done

**Comment by hattrill** [comment]
FB done

**Comment by gthayman** [comment]
Both of RGD's are ISOs.

**Comment by tberardini** [comment]
TAIR done

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
