### ISSUE TITLE
Review annotations to GO:1904008 response to monosodium glutamate & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4382]
Dear all, 

The proposal has been made to obsolete 

* GO:1904008 response to monosodium glutamate
* GO:1904009 cellular response to monosodium glutamate
* GO:1904608 response to monosodium L-glutamate
see https://github.com/geneontology/go-ontology/issues/24592

Experimental annotations that need to be reviewed are here: 
[response to monosodium glutamate](https://docs.google.com/spreadsheets/d/17rMhPEg5X2SY_Ra9VxmidrA9raCI9OHe07I7F7mue3M/edit#gid=0)

Impacted groups: 
RGD 6 EXP 

If necessary monosodium glutamate can be captured as an extension.

Thanks.
Pascale

**Comment by gthayman** [comment]
RGD done.
