### ISSUE TITLE
Review annotations to GO:0050072 m7G(5')pppN diphosphatase activity & regulation children  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4383]
Dear all, 

The proposal has been made to obsolete  GO:0050072 m7G(5')pppN diphosphatase activity & regulation children  
see https://github.com/geneontology/go-ontology/issues/23290

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1vFTXkVPHNC_cSFHYH0KPn4TRMT655FfQ44_Pmmjnzbk/edit#gid=0

Impacted groups: 

Contributor   (Assigned by) | Number of annotations 
-- |  -- 
ComplexPortal | 3
FlyBase | 2
GeneDB | 4
PomBase | 8
SGD | 3
TAIR | 3
UniProt | 28
WB | 8

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by sjm41** [comment]
FlyBase done.

**Comment by Antonialock** [comment]
UniProt done

**Comment by tberardini** [comment]
TAIR done

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by srengel** [comment]
SGD done.

**Comment by sjm41** [comment]
Hi @vanaukenk Can you take a look at the WB annotations here, thanks.

**Comment by pgaudet** [comment]
4 GeneDB annotations also left.

**Comment by pgaudet** [comment]
[InterPro:IPR044099](http://www.ebi.ac.uk/interpro/entry/IPR044099) >> corresponds to new GO term GO:0140933
 5'-(N(7)-methylguanosine 5'-triphospho)-[mRNA] hydrolase activity

@sarach06 @blazaropinto

**Comment by vanaukenk** [comment]
WB done

**Comment by sarach06** [comment]
Hi all,
Thank you very much for this. I have updated the term in IPR044099. This will be visible in the next InterPro release (93.0).
Best regards,
Sara

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
