### ISSUE TITLE
regulation of mitotic metaphase/anaphase transition 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4386]
* **InterPro ID / label**

regulation of mitotic metaphase/anaphase transition 
 IEA with IPR018860
IEA IPR007192
IEA IPR024789
IEA IPR008402

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

Originally I made these annotations, but we discussed this pathway at the last GO meeting and it was decided that the proteasome should not really be annoyed to this term (it isn't doing the  regulating')

Could these mappings be removed?

Thanks
v

**Comment by blazaropinto** [comment]
Hi Val,

Thanks for letting us know. I've removed these terms. The changes will be visible in the next release.

Best,
Beatriz
