### ISSUE TITLE
Review annotations to GO:0055073 cadmium ion homeostasis and GO:0006876 cellular cadmium ion homeostasis 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4389]
Dear all, 

The proposal has been made to obsolete GO:0055073 cadmium ion homeostasis and GO:0006876 cellular cadmium ion homeostasis 
see https://github.com/geneontology/go-ontology/issues/24624

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1apdIPiRTEVSBe93uBK7olzpa-jQCFuflx7GSwmNWbK8/edit#gid=0

Impacted groups: 
2 BHF-UCL
1 EcoCyc
1 SGD
1 TAIR

Suggestions have been made for reannotation. 

Thanks, Pascale

Thanks.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by RLovering** [comment]
UCL done

**Comment by tberardini** [comment]
TAIR done by Leonore

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
All done
