### ISSUE TITLE
Review annotations to GO:0043443 acetone metabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4391]
Dear all, 

The proposal has been made to obsolete GO:0043443 acetone metabolic process
see https://github.com/geneontology/go-ontology/issues/24647

Experimental annotations by UniProt to PMID:9237998 should be moved to the new term GO:0140977 cellular detoxification of acetone 

Thanks, Pascale

**Comment by Antonialock** [comment]
fixed

**Comment by pgaudet** [comment]
thanks
