### ISSUE TITLE
Advice needed: how do you parse your annotation QC reports?

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-annotation#4392]
Please merge with an existing issue if that already exists. I tried to find one but couldn't.

Background: With each set of annotations that we release, we review the http://snapshot.geneontology.org/reports/tair-report.html that runs and reports issues. We then try to address the issues for the TAIR created problems as best we can. In the current format, we manually perform this set of steps for each set of GO-RULE violations. 

Here's a sample set for one rule:

> 
> gorule-0000006
> 
> IEP and HEP usage is restricted to terms from the Biological Process ontology
> 
>     total: 5
> 
> Messages
> 
>     ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- AGI_LocusCode AT2G19390 SCS2A enables GO:0004402 TAIR:Publication:501793578|PMID:33737195 IEP F AT2G19390 AT2G19390|SCS2A|SAGA complex subunit 2A|F27F23.19|F27F23_19 protein taxon:3702 20221108 TAIR TAIR:locus:2047695
>     ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- AGI_LocusCode AT4G29790 SCS2B located_in GO:0070461 TAIR:Publication:501793578|PMID:33737195 IEP C AT4G29790 AT4G29790|SCS2B|SAGA complex subunit 2B|F27B13.30|F27B13_30 protein taxon:3702 20221108 TAIR TAIR:locus:2123879
>     ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- AGI_LocusCode AT5G22450 SCS1 located_in GO:0070461 TAIR:Publication:501793578|PMID:33737195 IEP C AT5G22450 AT5G22450|SCS1|SAGA complex subunit 1|MWD9.25|MWD9_25 protein taxon:3702 20221108 TAIR TAIR:locus:2176347
>     ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- AGI_LocusCode AT3G05655 lncCOBRA5 located_in GO:0005634 TAIR:Publication:501799386|PMID:35693169 IEP C AT3G05655 AT3G05655|lncCOBRA5 lnc_RNA taxon:3702 20220627 TAIR TAIR:locus:6532567487
>     ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- AGI_LocusCode AT2G18790 PHYB located_in GO:0005829 TAIR:Publication:501801269|PMID:36401805 IEP C AT2G18790 AT2G18790|PHYB|HY3|OOP1|phytochrome B|OUT OF PHASE 1|MSF3.17|MSF3_17|PHYTOCHROME B protein taxon:3702 20221130 TAIR TAIR:locus:2005515

Here's our usual workflow for review:

1. copy and paste each set of violations into a new spreadsheet
2. edit out the part of the line before the actual annotation "ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology --" (find and replace with null works)
3. convert the remaining text to columns with 'space' as the delimiter
4.  fix weird splitting that occurs
5. sort according to GO term or gene identifier or submitter so that we can proceed with the fixing

I've only given an example with 5 lines to illustrate. One can imagine how much more tedious this is with many more annotations to review.

Does anyone else have a more efficient way to work through the file? All suggestions welcome.
@cmungall Is there a solution at the report formatting level that could be beneficial to all?

**Comment by tberardini** [comment]
Tagging folks who I think process their MODs annotation QC reports for input.
@pfey03 @hdrabkin @vanaukenk @srengel @lreiser

**Comment by ValWood** [comment]
We don't parse this file. I fix  individual errors and warnings manually to make sure that the annotation is as it should be. But it seems that quite a lot of errors in the TAIR report aren't TAIR errors, they are  IBA and IEA mappings warnings. I filter these and report them on the annotation tracker when I see them.
If there are ever any changes that require  some global change in PomBase I pass them over to Kim.

 I'm never really sure what the "predictions" section doing in this file .

**Comment by pfey03** [comment]
We don't have a GO QC report I always fix reviews right away in P2GO. There I have history of annotations or also deleted are still viewable. I can get excellent stats from P2GO and only write about that in one or two sentences in our yearly grant progress report that I always mainly do.

**Comment by pgaudet** [comment]
Hi @tberardini 

What would you need? If I understand correctly, you copy the error to a spreadsheet to be able to track which error you have corrected? And the main problem is that the copy/paste in the spreadsheet messes up the columns? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@pfey03 There is a Dicty GOC report, see http://snapshot.geneontology.org/reports/dictybase-report.html
However if you correct all errors reported by P2GO, this should not give you any additional errors.

Thanks, Pascale

**Comment by ValWood** [comment]
It would be nice to review the file contents on an annotation call @vanaukenk ?
I still find the contents a bit confusing...

**Comment by vanaukenk** [comment]
This issue is on the agenda for discussion on tomorrow's annotation call.

**Comment by pfey03** [comment]
@pgaudet 
gorule-0000020 The obsolete terms are form IEAs
gorule-0000046 not matching is P2GO we need to annotate to UniProt Ids so as long as this is the case these are not errors as there is a UniProt dicty ID mapping. It will eventually be done when we move to GO-CAM or if we are able to import GO into new database whatever is first. We currently just display GO in our new database.
gorule-0000059 I don't know about these GAFs as far as I know they come from P2GO. 
Also we have too little personell for all to do quickly. Annotations that I can fix I always do them quickly.

**Comment by tberardini** [comment]
@pgaudet What we would find useful is a tab (or comma) delimited file that has the error in one column and the annotation details (the annotation file lines) in the rest of the columns. Others may find such a format useful as well.

**Comment by srengel** [comment]
SGD doesn't routinely do anything with this report because it is just too difficult to deal with.  too hard to read, tons of annotations that are not from us, etc.  so much other stuff for us to do that this rarely gets attention.

**Comment by tberardini** [comment]
Looks like we have a good new solution that's a combo between the .md files and the new snapshot report. Thank you.
