### ISSUE TITLE
Review annotations to GO:2001020 regulation of response to DNA damage stimulus and terms for positive and negative regulation

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4393]
Dear all, 

The proposal has been made to obsolete 
GO:2001020 regulation of response to DNA damage stimulus
GO:2001021 negative regulation of response to DNA damage stimulus
GO:2001022 positive regulation of response to DNA damage stimulus
see https://github.com/geneontology/go-ontology/issues/24632

Experimental annotations that need to be reviewed are here: 
(Annotations are to be replaced by GO:0006974 cellular response to DNA damage stimulus)
https://docs.google.com/spreadsheets/d/1lTmcSTP23DajCadSIDFb54OCDnW63q1Du_szaVuVTrw

Impacted groups: 
CACAO 1 @dsiegele
ComplexPortal 4 @kalpanap
FB 1 @hattrill
MGI 3 @krchristie
ParkinsonsUK-UCL 2 @RLovering
SGD 5 @srengel
TAIR 5 @tberardini
UNIPROT 21 @Antonialock
ZFIN 1 @sramachand

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by hattrill** [comment]
FB done

**Comment by tberardini** [comment]
TAIR done

**Comment by Antonialock** [comment]
uniprot done

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by sandraorchard** [comment]
Can someone remove Kalpana's assignment please - and assign Complex Portal issues to sandraorchard for the time being,

**Comment by srengel** [comment]
SGD done.

**Comment by sramachand** [comment]
ZFIN done

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
