### ISSUE TITLE
Review annotations to GO:0052746 inositol phosphorylation

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4394]
Dear all, 

The proposal has been made to obsolete GO:0052746 inositol phosphorylation,
see https://github.com/geneontology/go-ontology/issues/24634.

The reason for obsoletion is this is a single-step process.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1qOLSbLu-_gOnM7aAi0ZRTRTY1-pkKnFY-ZAi_YeO28A

Impacted groups: 
GeneDB 3 @uliboehme
UniProt 1 @Antonialock
TAIR 1 @tberardini
BHF-UCL 1 @RLovering

----

Mappings that need to be reviewed: None

Thanks.

**Comment by tberardini** [comment]
TAIR done

**Comment by Antonialock** [comment]
uniprot done

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
