### ISSUE TITLE
complex portal: mitochondrial respiratory chain complex II, succinate dehydrogenase complex (ubiquinone)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4396]
re
https://www.pombase.org/reference/GO_REF:0000114

4 members of 

mitochondrial respiratory chain complex II, succinate dehydrogenase complex (ubiquinone)
--

[mitochondrial respiratory chain complex II, succinate dehydrogenase complex (ubiquinone)](https://www.pombase.org/term/GO:0005749)
are annotated to

[proton motive force-driven mitochondrial ATP synthesis](https://www.pombase.org/term/GO:0042776)

but I don't think that this is the correct term.
There are a number of children under "[GO:0022904](https://www.ebi.ac.uk/QuickGO/term/GO:0022904)    respiratory electron transport chain" including:

<img width="718" alt="Screenshot 2023-01-09 at 14 35 59" src="https://user-images.githubusercontent.com/7359272/211333170-989a306a-43c4-4381-9191-af99bb9b2cff.png">

representing the different parts of electron transport (it is possible these terms should not exist, as they likely represent MF's rather than BPs, but the correct term in this schema for this complex is
[GO:0006121](https://www.ebi.ac.uk/QuickGO/term/GO:0006121)    mitochondrial electron transport, succinate to ubiquinone
(under the child GO:0019646   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0019646/complete)
aerobic electron transport chain)
The transfer of electrons from succinate to ubiquinone that occurs during oxidative phosphorylation, mediated by the multisubunit enzyme known as complex II.

the  proton motive force-driven mitochondrial ATP synthesis is for the  
F1-Fo ATP synthase step.

**Comment by ValWood** [comment]
pinging @sandraorchard  pls let me know if I can close, or if I should assign to one of  your team.

**Comment by pgaudet** [comment]
@sandraorchard Did you have a chance to look at this one?

**Comment by sandraorchard** [comment]
Sorry, will take a look over the next few days

**Comment by sandraorchard** [comment]
removed from all relevant entries
