### ISSUE TITLE
Remove PAINT annotation to GO:0043231 	intracellular membrane-bounded organelle 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4400]
GO:0043231 	intracellular membrane-bounded organelle 
(note this one is also used by PAINT), and I can't work out what the membrane-bounded organelle referred to is in all cases (for example one is a plasma membrane protein)

<img width="967" alt="Screenshot 2022-10-24 at 18 12 31" src="https://user-images.githubusercontent.com/7359272/197585702-18d189b4-3d0f-47fa-b6ee-183ce1788398.png">

**Comment by marcfeuermann** [comment]
Removed annotation. Replaced by more precise term when possible,
