### ISSUE TITLE
Review annotations to [ GO:0035103 sterol regulatory element binding protein cleavage]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4401]
Dear all, 

The proposal has been made to obsolete [GO:0035103](https://www.ebi.ac.uk/QuickGO/term/GO:0035103)    sterol regulatory element binding protein cleavage
see [https://github.com/geneontology/go-ontology/issues/24454]

Mappings that need to be reviewed: 
InterPro:IPR038967

Thanks.

**Comment by sarach06** [comment]
Dear Val,
Thank you very much. This term has been removed from this entry, which will be visible in the next InterPro release InterPro 93.0).
Best wishes,
Sara

**Comment by pgaudet** [comment]
Done
