### ISSUE TITLE
Review annotations to GO:0018024  histone lysine N-methyltransferase activity &  GO:0035184    histone threonine kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4402]
Dear all, 

The proposal has been made to obsolete GO:0018024 histone lysine N-methyltransferase activity
and  GO:0035184    histone threonine kinase activity

see https://github.com/geneontology/go-ontology/issues/24397

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1gEvtmRnv8x9V-yCBumrvTWgo4rn85tWjfwrzo2shpXc/edit#gid=0

Impacted groups: 

~(24) | UniProt~
~(6) | MGI~
~(4) | TAIR~
(3) | GeneDB
~(2) | FlyBase~

Mappings that need to be reviewed: 

~[R-HSA-4827383](https://www.reactome.org/content/detail/R-HSA-4827383)
[R-HSA-4827382](https://www.reactome.org/content/detail/R-HSA-4827382)
[R-HSA-3788748](https://www.reactome.org/content/detail/R-HSA-3788748)
[R-HSA-5634802](https://www.reactome.org/content/detail/R-HSA-5634802)
[R-HSA-5651654](https://www.reactome.org/content/detail/R-HSA-5651654)
[R-HSA-5651657](https://www.reactome.org/content/detail/R-HSA-5651657)
[R-HSA-5634729](https://www.reactome.org/content/detail/R-HSA-5634729)
[R-HSA-5637686](https://www.reactome.org/content/detail/R-HSA-5637686)
[R-HSA-5649764](https://www.reactome.org/content/detail/R-HSA-5649764)
[R-HSA-5649799](https://www.reactome.org/content/detail/R-HSA-5649799)
[R-HSA-5634750](https://www.reactome.org/content/detail/R-HSA-5634750)
[R-HSA-5649801](https://www.reactome.org/content/detail/R-HSA-5649801)
[R-HSA-5159245](https://www.reactome.org/content/detail/R-HSA-5159245)
[R-HSA-5649800](https://www.reactome.org/content/detail/R-HSA-5649800)
[R-HSA-5244692](https://www.reactome.org/content/detail/R-HSA-5244692)
[R-HSA-5423038](https://www.reactome.org/content/detail/R-HSA-5423038)
[R-HSA-3788745](https://www.reactome.org/content/detail/R-HSA-3788745)
[R-HSA-5649802](https://www.reactome.org/content/detail/R-HSA-5649802)
[R-HSA-5638141](https://www.reactome.org/content/detail/R-HSA-5638141)
[R-HSA-5638157](https://www.reactome.org/content/detail/R-HSA-5638157)
[R-HSA-5638333](https://www.reactome.org/content/detail/R-HSA-5638333)
[R-HSA-5638332](https://www.reactome.org/content/detail/R-HSA-5638332)~

Thanks.

**Comment by ValWood** [comment]
Note that this obsoletion is because there are multiple axis of classification, grouping term will be histone class (H2A, H3 etc), not amino acid- specific residue modifiers (e.g. histone H3K4 acetyltransferase activity) , will be kept. So you can move your annotations up to the parent, or down to a more specific child.

**Comment by ValWood** [comment]
InterPro mappings 
InterPro:IPR006560
InterPro:IPR007728
InterPro:IPR011381
InterPro:IPR013257
InterPro:IPR016569
InterPro:IPR016858
InterPro:IPR017111
InterPro:IPR017155
InterPro:IPR018848
InterPro:IPR021162
InterPro:IPR021169
InterPro:IPR021654
InterPro:IPR025788
InterPro:IPR025789
InterPro:IPR030445
InterPro:IPR032926
InterPro:IPR037841
InterPro:IPR037842
InterPro:IPR037877
InterPro:IPR037890
InterPro:IPR037927
InterPro:IPR038034
InterPro:IPR038035
InterPro:IPR042294
InterPro:IPR043550
InterPro:IPR044410
InterPro:IPR044411
InterPro:IPR044418
InterPro:IPR044419
InterPro:IPR044422
InterPro:IPR044437
InterPro:IPR044438
InterPro:IPR044439
InterPro:IPR044570
InterPro:IPR045318

**Comment by ValWood** [comment]
UniRule:UR000615760
UniRule:UR000128653

**Comment by Antonialock** [comment]
uniprot done

**Comment by sjm41** [comment]
FlyBase done.

**Comment by hdrabkin** [comment]
mgi done

**Comment by tberardini** [comment]
TAIR done

**Comment by sarach06** [comment]
Dear Val,
Thanks for the reminder, seems like we missed this one, my apologies. I have checked this mapping and removed the term from the entries, adding the parent or a more specific term when suitable. These changes will be available in the next InterPro release (93.0).

Best regards,
Sara

**Comment by pgaudet** [comment]
@uliboehme Can you please fix the GeneDB annotations? 
https://docs.google.com/spreadsheets/d/1gEvtmRnv8x9V-yCBumrvTWgo4rn85tWjfwrzo2shpXc/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
