### ISSUE TITLE
Review annotations to GO:0008469 histone arginine N-methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4403]
Dear all, 

The proposal has been made to obsolete GO:0008469   histone arginine N-methyltransferase activity
see [https://github.com/geneontology/go-ontology/issues/24397]

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1pYNPCqeb7xQgb1P5VWEifjnOsMH57eYS0Skn9YRT4Rs/edit#gid=0

Impacted groups: 

+ | − | (6) | UniProt
+ | − | (4) | MGI
+ | − | (3) | AspGD
+ | − | (3) | TAIR
+ | − | (2) | CACAO
+ | − | (2) | GeneDB
+ | − | (2) | HGNC-UCL
+ | − | (2) | Reactome
+ | − | (1) | WB

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

[R-HSA-8937113](https://www.reactome.org/content/detail/R-HSA-8937113)
[R-HSA-5216234](https://www.reactome.org/content/detail/R-HSA-5216234)
[R-HSA-5205861](https://www.reactome.org/content/detail/R-HSA-5205861)
[R-HSA-5205799](https://www.reactome.org/content/detail/R-HSA-5205799)
[R-HSA-8937022](https://www.reactome.org/content/detail/R-HSA-8937022)
[R-HSA-5661117](https://www.reactome.org/content/detail/R-HSA-5661117)
[R-HSA-8936608](https://www.reactome.org/content/detail/R-HSA-8936608)
[R-HSA-8936584](https://www.reactome.org/content/detail/R-HSA-8936584)

Thanks.

**Comment by ValWood** [comment]
UniRule:UR000615760
UniRule:UR000128653

**Comment by deustp01** [comment]
Reactome is done

**Comment by Antonialock** [comment]
uniprot done

**Comment by vanaukenk** [comment]
WB done

**Comment by LiNiMGI** [comment]
MGI done

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
Hi @LiNiMGI 

MGI has also annotated a Rat paper - PMID:8663146
Did you also fix that? It's not in the spreadsheet. 

For annotation suggestions, I dont think this is showing any BPs, just MFs.

**Comment by pgaudet** [comment]
@RLovering 2 annotations left, easily replaced

**Comment by RLovering** [comment]
UCL done

**Comment by LiNiMGI** [comment]
Rat annotation also fixed, thanks @pgaudet

**Comment by deustp01** [comment]
Now Reactome is done - all usages of GO:0008469 histone arginine N-methyltransferase have been removed, as have all usages of GO:0018024 histone-lysine N-methyltransferase activity. Just missed a release deadline so changes will appear in our June 2023 release.

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
