### ISSUE TITLE
Remove RNA polyII holoenzyme mapping to 27716820

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4405]
* **InterPro ID / label**
IPR026213

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**
We proposed to obsolete  GO:0016591 RNAP II holoenzyme, see https://github.com/geneontology/go-ontology/issues/10556
There is one IPR mapping IPR026213. Newer literature suggests this is an elongation factor, see for eg PMID:27716820

* can possibly add MF: GO:0003711 transcription elongation factor activity and BP: GO:0006368 'transcription elongation by RNA polymerase II'
* We cannot tell whether this really belongs to a complex, although when it is active it is tightly associated with the RNA poly II core. Maybe change CC to nucleus? 

Thanks, Pascale

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I have removed this term, added the MF and BP you suggested, and changed CC to nucleus. Also, I updated the abstract and added more recently references, including the one you mentioned. This will be visible in the next InterPro release (93.0).
Best wishes,
Sara
