### ISSUE TITLE
mad3 not a protein kinase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4406]
* **PTHR ID & PTN node:**

GO:0004672 | protein kinase activity | IBA with S000003420 , PTN000361607 , bub1

* **Sequences with problematic annotation (ID + gene/protein name):**

Pombe mad3 https://www.pombase.org/gene/SPCC1795.01c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This is inferred from bub1, which  IS a protein kinase, but mad3 has no pk domain

<img width="854" alt="Screenshot 2023-01-16 at 17 27 47" src="https://user-images.githubusercontent.com/7359272/212736775-c933d338-c99b-430f-8dc6-c532e98c5bfe.png">

<img width="813" alt="Screenshot 2023-01-16 at 17 31 26" src="https://user-images.githubusercontent.com/7359272/212736957-8cddea04-a134-4b33-b834-1b2c9ff81bef.png">

**Comment by marcfeuermann** [comment]
Indeed, we have the same issue with cerevisiae proteins in the same family. This has been corrected for both.
