### ISSUE TITLE
Review annotations to GO:0030104 water homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4407]
Dear all, 

The proposal has been made to obsolete GO:0030104 water homeostasis
see https://github.com/geneontology/go-ontology/issues/24726 

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1m7KoQfGJ06drHqViHrfJ2P_Y1xIgb44PQysjXAlo86M/edit#gid=0
Impacted groups: 

Group | Number of annotations
-- | --
dictyBase | 1
FlyBase | 5
MGI | 5
TAIR | 3
UniProt | 8
WB | 4
ZFIN | 4
  

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
NA

Thanks.

**Comment by lreiser** [comment]
tair is done

**Comment by LiNiMGI** [comment]
MGI is done

**Comment by sramachand** [comment]
ZFIN done

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-ontology/issues/24726#issuecomment-1387356580

**Comment by hdrabkin** [comment]
mgi done

**Comment by hattrill** [comment]
fb done

**Comment by pgaudet** [comment]
All done
