### ISSUE TITLE
Review annotations to GO:0070816 phosphorylation of RNA polymerase II C-terminal domain & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4408]
Dear all, 

The proposal has been made to obsolete GO:0070816 phosphorylation of RNA polymerase II C-terminal domain and children: 
GO:0071619 phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:0071620 phosphorylation of RNA polymerase II C-terminal domain serine 5 residues  
GO:1901921 phosphorylation of RNA polymerase II C-terminal domain involved in recruitment of 3'-end processing factors to RNA polymerase II holoenzyme complex
GO:1901408 negative regulation of phosphorylation of RNA polymerase II C-terminal domain
GO:1901409 positive regulation of phosphorylation of RNA polymerase II C-terminal domain
GO:1901407 regulation of phosphorylation of RNA polymerase II C-terminal domain 
GO:2001163 regulation of phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:2001164 negative regulation of phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
GO:2001165 positive regulation of phosphorylation of RNA polymerase II C-terminal domain serine 2 residues 

See https://github.com/geneontology/go-ontology/issues/19105

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1XZCfcnBMuLgq5b6_5Lj5FamaJOw4Oczwn0fs4gjSKyg/edit#gid=0

**Impacted groups:** 
There are 68 EXP annotations: 
Group | Number of annotations
-- | --
CACAO | 1
ComplexPortal | 14
FlyBase | 3
SGD | 47
UniProt | 3

Consider changing annotations to 
GO:0140834 RNA polymerase II C-terminal domain S2 kinase activity
GO:0140836 RNA polymerase II C-terminal domain S5 kinase activity
GO:0140837 RNA polymerase II C-terminal domain S7 kinase activity
GO:0140835 RNA polymerase II C-terminal domain T4 kinase activity

Thanks, Pascale

**Comment by hattrill** [comment]
FB done

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
Still missing Complex Portal and CACAO @sandraorchard @dsiegele

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
