### ISSUE TITLE
Review annotations to actin reorganization & related

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4409]
Dear all, 

The proposal has been made to obsolete  (https://github.com/geneontology/go-ontology/issues/14087) 
* GO:0090527 actin filament reorganization 
* GO:0031532 actin cytoskeleton reorganization
*  GO:2000249 regulation of actin cytoskeleton reorganization
*  GO:0030037 actin filament reorganization involved in cell cycle
*  GO:2000250 negative regulation of actin cytoskeleton reorganization
*  GO:2000251 positive regulation of actin cytoskeleton reorganization

Experimental annotations that need to be reviewed are here:
https://docs.google.com/spreadsheets/d/11iY9Rmb3ZbyNSf8ZdI37whYfwz2pmYrCoPVibz2EE4g/edit#gid=0

Impacted groups: 
There are 84 EXP annotations to these terms: 

BHF-UCL and ARUK-UCL	16x28 (12 added) done
CACAO	2
~dictyBase	4~
FlyBase	8
MGI	4
~PomBase	1~ done
RGD	3
SGD	17
~UniProt	28~ 
~WB	1~ done

Thanks.

Pascale

**Comment by hattrill** [comment]
FB done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by LiNiMGI** [comment]
@pgaudet while reviewing, I noticed MGI has more annotations to the actin reorganization & related terms than showed in the excel sheet.

**Comment by srengel** [comment]
SGD done.

**Comment by pfey03** [comment]
dicty done a while ago, forgot to say it here

**Comment by LiNiMGI** [comment]
@pgaudet 
More examples for MGI annotations that are not in the excel sheet.
They are in current version of Amigo.
PMID:17507657 Cdh1 MGI:MGI:88354   GO:0031532 actin cytoskeleton reorganization. IMP. MGI:1857282
PMID:9808630 Plec MGI:1277961 GO:0031532 actin cytoskeleton reorganization. IMP (not in form but in graph)
PMID:17008542  Plek2 MGI:1351466 GO:0031532 actin cytoskeleton reorganization. IDA
PMID:27917469. Pak1 MGI:1339975  GO:0031532 actin cytoskeleton reorganization. ISO Q13153
PMID:27917469 Syde1 MGI:1918959  GO:0031532 actin cytoskeleton reorganization. ISO Q6ZW31
PMID:10809671 Shc1 MGI:98296 GO:0031532 actin cytoskeleton reorganization IMP MGI:2384189
PMID:10438476 Lpin1 MGI:1891340 GO:0031532 actin cytoskeleton reorganization IMP MGI:1856603
PMID:17018287. Eps8 MGI:104684 GO:0031532 actin cytoskeleton reorganization  IMP MGI:3693626
PMID:12529407 S100a9 MGI:1338947 GO:0031532 actin cytoskeleton reorganization  IMP MGI:2450165

There are also one MGI annotation that is in Nocua production, but failed reasoner, so it didn't go to MGI.
PMID:24747950 Plek2 MGI:1351466 GO:0031532 actin cytoskeleton reorganization. RNAi
Maybe we need a Noctua QC for Noctua models that failed reasoner, so curator will be notified to fix it?
thanks,
Li

**Comment by LiNiMGI** [comment]
MGI done with those missing from the annotation review ticket.

**Comment by RLovering** [comment]
ucl done

**Comment by Antonialock** [comment]
uniprot done

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
