### ISSUE TITLE
Review annotations to GO:1904766 negative regulation of macroautophagy by TORC1 signaling

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4411]
Dear all, 

The proposal has been made to obsolete GO:1904766 negative regulation of macroautophagy by TORC1 signaling
see https://github.com/geneontology/go-ontology/issues/22004

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1V7-FvdV8gWYDtg0V2ZdsSBdrxkbedM2QfFdOc8RgI7A

Impacted groups: 
Flybase 2
UniProt 1

Thanks.

**Comment by deustp01** [comment]
> [LINK TO ANNOTATION REVIEW GOOGLE SPREADSHEET from this directory https://drive.google.com/drive/folders/1j8F_RxmD1U1cOGoWTU4S6EivflrYJf9C]

That link appears to point to a directory. Is there is specific folder / file that lists the affected annotations?

**Comment by raymond91125** [comment]
Sorry, was to submit first to get a ticket number and then add the details. Caught me in the act.

**Comment by pgaudet** [comment]
All done
