### ISSUE TITLE
Review annotations to [NON PROGRAMMED cell death terms]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4412]
Dear all, 

The proposal has been made to obsolete 
GO:0008219 cell death
GO:0070265 necrotic cell death
GO:0070267 oncosis
see https://github.com/geneontology/go-ontology/issues/24680

The annotations should be moved to one of the 'programmed  death' children. For example if necrotic cell death is valid for GO it should move to "programmed necrotic  cell death" or one of it's children. Pathogenic mutations should not be annotated to cell death using GO, only programmed death mechanisms should be annotated.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1sPkWZ3rNAFpUQRD0d9n2mzi4j7pd8ztBFb33OblWYWw/edit#gid=0]

Impacted groups: 

cell death 97

~| − | (30) | TAIR~
~| − | (27) | UniProt~
~− | (10) | FlyBase~
~| − | (9) | RGD~
| − | (5) | EcoCyc
~| − | (5) | MGI~
~| − | (4) | Xenbase  @malcolmfisher103~

| − | (2) | CACAO
~| − | (2) | dictyBase~
| − | (1) | AgBase
| − | (1) | GeneDB
| − | (1) | PseudoCAP
consider programmed cell death or descendant

necrotic cell death (12)

~| − | (5) | UniProt~
~| − | (5) | WB~
~| − | (1) | RGD~
~| − | (1) | dictyBase~
consider programmed necrotic cell death or descendant

GO:0070267 oncosis

~| − | (2) | UniProt~

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

InterPro:IPR042377  move to -> programmed cell death?

Thanks.

**Comment by pfey03** [comment]
Phenotypes and GO are related as most phenotypes are based on GO. Why the base term GO:0008219 cell death will be obsoleted I don't understand.

**Comment by ValWood** [comment]
from https://github.com/geneontology/go-announcements/issues/464#issuecomment-1396608685

All programmed cell death terms will stay in GO. If you look at the annotated graph in https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeneontology%2Fgo-ontology%2Fissues%2F24680&data=05%7C01%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C3bff5922f202406b492208daf9f75a70%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638097138010525995%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bc%2BRb%2FlPYlI54UlbNDtsEBfWDgFNieqOR0ZlEcAV9A4%3D&reserved=0
you can see the terms that will be removed.

    necrotic cell death will go because it is a descendent of necrotic cell death and only 'programmed necrotic cell death' terms are required for GO annotation"
    oncosis will go because it is a child of necrotic cell death, but not under programmed cell death.
    cell death will no longer be required as a grouping term because it will be 'single inheritance', (i.e it will have only one child term "programmed cell death"). This is bad practice in ontology development. It is also causing bad annotation practice, all existing annotations should be 'deeper', or if they are not 'intentional cell death, they should be removed.

There is no problem with autophagic cell death, and it is already positioned correctly under programmed cell death. There are no plans to touch any of the terms under 'programmed cell death' which represents the 'evolved/intentional' cell death pathways.

**Comment by hdrabkin** [comment]
Mary Dolan notes that there slims could be impacted affected:
'cell death' is a category in MGI slim/ribbon and Alliance slim/ribbon <== could switch to 'programmed cell death' (shorten to 'cell death'?)
subset: goslim_agr
subset: goslim_chembl
subset: goslim_drosophila
subset: goslim_mouse
subset: goslim_plant

**Comment by hdrabkin** [comment]
Mary Dolan notes multiple slims affected:
cell death' is a category in MGI slim/ribbon and Alliance slim/ribbon <== could switch to 'programmed cell death' (shorten to 'cell death'?)
subset: goslim_agr
subset: goslim_chembl
subset: goslim_drosophila
subset: goslim_mouse
subset: goslim_plant
what about terms in other ontologies (e.g. MP) that use 'cell death' in definition?

**Comment by ValWood** [comment]
I missed the subsets, but that will be done as part of
https://github.com/geneontology/go-ontology/issues/24652
when the term is edited.

> what about terms in other ontologies (e.g. MP) that use 'cell death' in definition?

The obsoletion announcement  for this ticket hasn't gone out yet. Presumably the external ontologies will be monitoring the announcements and will fix as normal ? Many terms are used in external ontologies,  for example I'm fixing GO terms obsoleted from FYPO logical defs all the time....there isn't a mechanism to check which ontologies are using GO terms

**Comment by ValWood** [comment]
'programmed cell death'  would be appropriate for the slims.

**Comment by ValWood** [comment]
Oh the obsoletion notice did go out, I was getting confused.

**Comment by vanaukenk** [comment]
WB done

**Comment by ValWood** [comment]
> what about terms in other ontologies (e.g. MP) that use 'cell death' in definition?

I don't know if this is helpful but for inviable cell in FYPO we have logically defined

'has part' some 
    ('lethal (sensu genetics)'
     and ('characteristic of' some 'fungal cell'))

so no need to use GO for this when describing a phenotype which leads to inviable cells (i.e. cell lethality). For logical defs referring to programmed cell death pathways you would just swap in the appropriate 'programmed' term.

**Comment by Antonialock** [comment]
uniprot done

**Comment by ValWood** [comment]
Pinging
RGD @slaulederkind 
TAIR @tberardini  (are you done, or part done?)
Xenbase @malcolmfisher103
FlyBase @hattrill 

In the first instance I'd like to get all of the annotations to the  non-programmed descendants , and the cell death term itself.
Once the descendants have no annotations I'll go ahead and obsolete those.
I will hold of obsoleting "cell death" until the phenotype ontologies locate the correct logical definition for "any old cell death" and make it "do not annotate" in the meantime with a comment that it is out of scope and will be obsoleted soon. @hattrill  does that work for you?

**Comment by ValWood** [comment]
I will proceed with the obsoletion of 
GO:0070265 necrotic cell death 
GO:0070267 oncosis
because the EXP to these are  reported as done

**Comment by hattrill** [comment]
> 

That's good for me @ValWood, thanks!

**Comment by malcolmfisher103** [comment]
Xenbase should be all done.

Malcolm


-------------------------

Malcolm Fisher, PhD

Xenbase Curator

Cincinnati Children’s Hospital Medical Center

Division of Developmental Biology

3333 Burnet Avenue, Cincinnati,

Ohio 45229-3026

Tel:(513) 803 5379

________________________________

**Comment by hdrabkin** [comment]
MGI done (also found a few more not in spreadsheet and fixed).

**Comment by hattrill** [comment]
FB done

**Comment by ValWood** [comment]
proceed with
GO:0070265 necrotic cell death
GO:0070267 oncosis

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by ValWood** [comment]
Update
PseudoCAP 1 @glwinsor
TriTryp 1 @uliboehme
AgBase 1 @jinhuiz
Cacao 1 @dsiegele

I will proceed with this one.

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
