### ISSUE TITLE
Review annotations to GO:0044026 DNA hypermethylation

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#4413]
Dear all, 

The proposal has been made to obsolete GO:0044026 DNA hypermethylation
see https://github.com/geneontology/go-ontology/issues/24709

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1ttZx5TVZnWa3i2HvbPpHV0p8HRN2VXn_5ilkqeP700c/edit?usp=sharing

Impacted groups: 
MGI 1
RGD 1

----

Thanks.

**Comment by gthayman** [comment]
RGD done.
