### ISSUE TITLE
Review annotations to GO:0010941, GO:0060548, GO:0010942 cell death regulation terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4415]
Dear all, 

The proposal has been made to obsolete GO:0010941, GO:0060548, GO:0010942 cell death regulation terms
see https://github.com/geneontology/go-ontology/issues/24755

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1-NnAiTGTdaRVjMJ7rwtYyMeISicM4upwe9By2sbUIQQ/edit#gid=0

I have spot checked quite a few of these. Most can probably move to a regulation of programmed cell death (or one of the descendants for apoptosis/autophgy etc). However, many of these are clearly phenotypes. I have checked and flagged some of these. Note that cell death terms should only be used for cell death pathways, and not for:
- mutants that are pathological/toxic (even those  which activate damage checkpoint or apoptotic pathways, many mutants cause problems which require checkpoints or cell death pathways to be activated, but are not themselves part of these pathways ). 
- genes which are required for normal growth and viability 

Therefore, it is worth checking these if you are not sure that they operate in a cell death pathway.

Impacted groups: 

positive regulation of cell death
 
-- | --| --
~+ | − | (60) | FlyBase~
+ | − | (35) | RGD
~+ | − | (20) | UniProt~
~+ | − | (14) | ARUK-UCL | done~
~+ | − | (9) | TAIR~
+ | − | (6) | BHF-UCL
+ | − | (4) | ParkinsonsUK-UCL
~+ | − | (3) | ComplexPortal~
+ | − | (2) | AgBase
~+ | − | (2) | MGI~
+ | − | (1) | CACAO
~+ | − | (1) | CAFA~
~+ | − | (1) | dictyBase~

negative regulation of cell death

-- | -- | -- | -- | --
+ | − | (49) | RGD
~+ | − | (45) | UniProt~
~+ | − | (13) | ComplexPortal~
~+ | − | (13) | FlyBase~
~+ | − | (11) | MGI~
+ | − | (7) | ParkinsonsUK-UCL
+ | − | (4) | ARUK-UCL | done
+ | − | (3) | BHF-UCL
~+ | − | (3) | TAIR~
~+ | − | (2) | ZFIN~
+ | − | (1) | AgBase

regulation of cell death

-- | --
~+ | − | (8) | UniProt~
~+ | − | (6) | FlyBase~
~+ | − | (5) | TAIR~
~+ | − | (4) | MGI~
~+ | − | (1) | CAFA~
+ | − | (1) | ParkinsonsUK-UCL
+ | − | (1) | RGD

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by hattrill** [comment]
Hi @gantonazzo I've added you to the list. Can you look at some of them over the next couple of weeks?

**Comment by hdrabkin** [comment]
mgi done

**Comment by gantonazzo** [comment]
FlyBase done

**Comment by Antonialock** [comment]
CAFA and uniprot done

**Comment by ValWood** [comment]
Pinging @slaulederkind @RLovering @tberardini @doughowe @LeylaR

**Comment by LiNiMGI** [comment]
There are annotations to the term but not in the excel sheet, will review the annotations and report back when finish.

**Comment by tberardini** [comment]
I'm working on the list, @ValWood, but I don't have full time to dedicate to it. I'm about a third through the 'cell death' ones and plan to tackle the regulation ones after that.

**Comment by sramachand** [comment]
ZFIN done

**Comment by LiNiMGI** [comment]
MGI done

**Comment by tberardini** [comment]
TAIR finally done

**Comment by pgaudet** [comment]
All fixed
