### ISSUE TITLE
Review annotations to GO:0010216 negative regulation of gene expression via chromosomal DNA cytosine methylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4416]
Dear all, 

The proposal has been made to obsolete GO:0010216 negative regulation of gene expression via chromosomal DNA cytosine methylation
see https://github.com/geneontology/go-ontology/issues/24711

The term will be replaced by 'GO:0044027 negative regulation of gene expression via CpG island methylation'; if your group has an automated replacement mechanism, no action is needed.

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1KRAaKRqtkbMHcVJ31OUSXH8Jycg8d6e1Wt8e08uPO84/edit#gid=0

Impacted groups: 

Contributor   (Assigned by)
--
MGI | 2
RGD | 1
TAIR | 8
UniProt | 14
ZFIN | 1

Thanks, Pascale

**Comment by gthayman** [comment]
RGD done.

**Comment by tberardini** [comment]
TAIR automatically updated.
