### ISSUE TITLE
Q9H211 DNA replication factor Cdt1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4418]
his paper seems over annotated:
http://amigo.geneontology.org/amigo/reference/PMID:22581055

For 

ORC6 | Origin recognition complex subunit 6 |   | negative regulation of cell division |   | CAFA | Homo sapiens | IMP |   | origin recognition complex subunit 6 pthr13394 | protein |   | PMID:22581055
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CDT1 | DNA replication factor Cdt1 |   | positive regulation of protein-containing complex assembly | has input Ndc80 complex | CAFA | Homo sapiens | IMP |   | dna replication factor cdt1 pthr28637 | protein |   | PMID:22581055 | 20160728
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CDT1 | DNA replication factor Cdt1 |   | regulation of chromosome organization |   | CAFA | Homo sapiens | IMP |   | dna replication factor cdt1 pthr28637 | protein |   | PMID:22581055 | 20160725
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | CDT1 | DNA replication factor Cdt1 |   | cell division |   | CAFA | Homo sapiens | IMP |   | dna replication factor cdt1 pthr28637 | protein |   | PMID:22581055 | 2016072
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CDT1 | DNA replication factor Cdt1 |   | kinetochore organization |   | CAFA | Homo sapiens | IMP |   | dna replication factor cdt1 pthr28637 | protein |   | PMID:22581055 | 20160727
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | CDT1 | DNA replication factor Cdt1 |   | deactivation of mitotic spindle assembly checkpoint | has input UniProtKB:Q9Y6D9 | CAFA | Homo sapiens | IMP |   | dna replication factor cdt1 pthr28637 | protein |   | PMID:22581055 | 20160727
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CDT1 | DNA replication factor Cdt1 |   | negative regulation of protein localization to kinetochore | has input UniProtKB:Q9Y6D9part of deactivation of mitotic spindle assembly checkpoint | CAFA | Homo sapiens | IMP |   | dna replication factor cdt1 pthr28637 | protein |   | PMID:22581055 | 20160801
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

[CDT1](http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q9H211)	DNA replication factor Cdt1		[negative regulation of protein localization to kinetochore](http://amigo.geneontology.org/amigo/term/GO:1905341)	[has input](http://purl.obolibrary.org/obo/RO_0002233) [UniProtKB:Q9Y6D9](https://www.uniprot.org/uniprot/Q9Y6D9)
[part of](http://purl.obolibrary.org/obo/BFO_0000050) [deactivation of mitotic spindle assembly checkpoint](http://amigo.geneontology.org/amigo/term/GO:1902426)	CAFA	[Homo sapiens](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9606)	IMP		[dna replication factor cdt1 pthr28637](http://www.pantherdb.org/panther/lookupId.jsp?id=PTHR28637)	protein		[PMID:22581055](http://amigo.geneontology.org/amigo/reference/PMID:22581055)	20160801

attachment of mitotic spindle microtubules to kinetochore seems to be correct. That would make the original chromosome segregation annotation by UniPRot redundant from the same publication, so that could be deleted.

**Comment by ValWood** [comment]
Putting on the tracker because I have no access to protein2GO  A.T.M

**Comment by Antonialock** [comment]
thanks I have tidied up the annotation
