### ISSUE TITLE
Review annotations to GO:1904486 - response to 17alpha-ethynylestradiol

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4419]
Dear all, 

The proposal has been made to obsolete GO:1904486 - response to 17alpha-ethynylestradiol
see https://github.com/geneontology/go-ontology/issues/19002

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1haRDy9ObF4BHiTR_cF0MIRLChJtXpxOyZJD7FBSIuHo

Impacted groups: 
RGD 6
AgBase 1 @jinhuiz

Thanks.

**Comment by gthayman** [comment]
RGD done.

**Comment by pgaudet** [comment]
AgBase done
