### ISSUE TITLE
non-fungal terms used for Candida

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4420]
the annotations  look incorrect for candida:
<img width="854" alt="report_annotation tracker" src="https://user-images.githubusercontent.com/7359272/214123805-9a5d7375-d009-4075-817b-f2ed83987dce.png">

consider
GO:0052553   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0052553/complete)
modulation by symbiont of host immune response

**Comment by marekskrzypek** [comment]
I don't know where these come from. What we have in CGD is GO:0044416 induction by symbiont of host defense response and that seems appropriate.



On Jan 23, 2023, at 1:47 PM, Val Wood ***@***.***> wrote:



the annotations look incorrect for candida:
[report_annotation tracker]<https://user-images.githubusercontent.com/7359272/214123805-9a5d7375-d009-4075-817b-f2ed83987dce.png>

consider
GO:0052553 JSON<https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0052553/complete>
modulation by symbiont of host immune response

**Comment by ValWood** [comment]
maybe this is a synch issue, will close
