### ISSUE TITLE
PTN000129456 not all mitochondrial ribosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4421]
* **PTHR ID & PTN node:**

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC119.11c

GO:0003735 | structural constituent of ribosome | IBA with PTN000129456 , S000004626 | Gaudet P et al. (2011)
-- | -- | -- | --
GO:0070125 | mitochondrial translational elongation | IBA with Q9H9J2 , PTN000129456 | Gaudet P et al. (2011) | 30
-- | -- | -- | -- | --
GO:0005739 | mitochondrion | IBA with S000004626 , Q9H9J2 , PTN000129456
-- | -- | --

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation from shared domain
https://www.pombase.org/gene_subset/interpro:IPR014720

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
There was indeed a problem with this family. The annotation has been reviewed.
