### ISSUE TITLE
PTN000752736 pombe raf1 seems to be in the wrong family

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4423]
* **PTHR ID & PTN node:**

GO:0070840 dynein complex binding
IBA with FBgn0015754 , P43034 , PTN000752736

GO:0051010	
microtubule plus-end binding
IBA with PTN000752736 , S000005795

GO:0000132	
establishment of mitotic spindle orientation
IBA with P43034 , PTN000752736 , WBGene00003047

GO:0031023	
microtubule organizing center organization
IBA with PTN000752736 , WBGene00003047 , P43034 , FBgn0015754	Gaudet P et al. (2011)	15
GO:0007097	
nuclear migration
IBA with PTN000752736 , 620331 , ZDB-GENE-040116-3 , FBgn0015754 , WBGene00003047 , Q00664 , S000005795

GO:0047496	
vesicle transport along microtubule
IBA with MGI:109520 , PTN000752736

GO:0005881	
cytoplasmic microtubule
IBA with P43034 , PTN000752736 , S000005795

GO:0000776	
kinetochore
IBA with PTN000752736 , WBGene00003047 , P43034

GO:0005875	
microtubule associated complex
IBA with PTN000752736 , MGI:109520 , 620331 , FBgn0015754 , WBGene00003047 , P43034

GO:0005635	
nuclear envelope
IBA with 620331 , P43034 , PTN000752736

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC613.12c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation.
I'm going to double check this in a minute but these don't seems to be raf1 orthologs

**Comment by ValWood** [comment]
I double-checked, this seems to be an incorrect family assignment...

**Comment by pgaudet** [comment]
This should be assigned to @huaiyumi or @dustine32 

Huaiyu, Dustin, do you still keep track of these in the Panther tracker: https://github.com/pantherdb/Helpdesk/issues ?

**Comment by dustine32** [comment]
@pgaudet Yep! We still use that issue tracker. So, `PomBase:SPCC613.12c` (raf1) shouldn't be in PTHR44129 (RIK1-ASSOCIATED FACTOR 1). If there's a suggested new family, we can assign it to that for PANTHER 18.0. Otherwise, we'll rescore it and see if it hits a different family.

**Comment by ValWood** [comment]
Sorry for the late follow up. I don't think I could easily classify the pombe family member, it seems to be quite resticted, I don't see clear orthologs in other species.

**Comment by ValWood** [comment]
Note that the current panther family in InterPro appears to be this one
https://www.pantherdb.org/panther/family.do?clsAccession=PTHR44019 
but this  isn't the one from where the annotations in AmiGO are currently derived.

<img width="1184" alt="GO-inference CLRC " src="https://github.com/geneontology/go-annotation/assets/7359272/0ac0b362-0819-4e6f-8273-d3865fe32a24">

**Comment by marcfeuermann** [comment]
S. pombe raf1 is part of a small fungal node (PTN008687784) that rose from an ancient duplication in fungi. These proteins might be related to PTHR44129, but have diverged. Sequences are more different then for the neighboring proteins. I've blocked all annotations for PTN008687784.
