### ISSUE TITLE
Review annotations to GO:1990248 regulation of transcription from RNA polymerase II promoter in response to DNA damage & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4425]
Dear all, 

The proposal has been made to obsolete 
GO:1990248 regulation of transcription from RNA polymerase II promoter in response to DNA damage
GO:0010767 regulation of transcription from RNA polymerase II promoter in response to UV-induced DNA damage
GO:0010768 negative regulation of transcription from RNA polymerase II promoter in response to UV-induced DNA damage

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1XyAo7aF2-pDsATsLCFNjQy4f3ZUjEQCmFZ6WP0yToc8/edit#gid=0

Impacted groups: 

BHF-UCL: 2
CGD: 1
FlyBase: 3
TAIR: 1
UniProt: 1

Thanks, Pascale

**Comment by pgaudet** [comment]
negative regulation of transcription from RNA polymerase II promoter by transcription factor localization involved in response to DNA damage checkpoint signaling 1 pombase @ValWood

**Comment by hattrill** [comment]
FB done

**Comment by lreiser** [comment]
TAIR done

**Comment by jlewsmith** [comment]
CGD done

**Comment by pgaudet** [comment]
Terms are now obsolete, see https://github.com/geneontology/go-ontology/issues/24817
Any remaining annotation will appear in error reports.
