### ISSUE TITLE
Review annotations to GO:0070997 neuron death & children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4426]
Dear all, 

The proposal has been made to obsolete GO:0070997 neuron death & children
see https://github.com/geneontology/go-ontology/issues/24751

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1QxcMlE5FVF9oAlMZmXDUduvu7DNhp7BGHo7K_ITUIf4/edit#gid=0

Impacted groups: 
~MGI (20)~
RGD (9)
~ARUK-UCL (1)~
~BHF-UCL (2)~

----

There are no mappings to these terms.

Thanks.

**Comment by RLovering** [comment]
UCL done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by ValWood** [comment]
GO class direct
GO:0036475
GO:0070997
are the only term in this spreadsheet. The annotations are not all i nthe same spreadsheet as these were added later.

**Comment by RLovering** [comment]
Hi Val

are we removing all annotations to GO:0036475 neuron death in response to oxidative stress and child terms including the regulation children = I have 36 of these

and removing all annotations to GO:0070997 neuron death and child terms including the regulation children = I have 187 of these (including the 36 above)

or are we allowed to keep terms such as GO:0043524 negative regulation of neuron apoptotic process

Thanks

Ruth

**Comment by ValWood** [comment]
Hi Ruth,
everything which mentions apoptotic will stay, so 
GO:0043524 negative regulation of neuron apoptotic process
is fine.

Does that make sense?
v

**Comment by RLovering** [comment]
yes I now have 118 annotations to edit. I have added a QuickGO download of my annotations as a separate tab.

I guess 3 of these I have done already so I will remove these from the tab when I find them and I have removed 'Done' from the table heading

Not sure when these are going to be done. Some might have evidence of apoptosis. Are any other death terms allowed? eg

**Comment by ValWood** [comment]
GO:0012501   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0012501/complete)
programmed cell death
or any of its children.  You can use programmed cell death are sure that it is "controlled" cell death, and not just:
i) removal  or inactivation of a gene essential for cellular processes, 
ii) or a toxic mutation,  or  
iii) something required for metabolite repair which reduces cell viability over time (for example DNA damage response pathway mutants would eventually result in cell lethality ). 

A lot of the existing annotations to the non-programmed cell death terms were these types of annotations which are really phenotypes.

**Comment by ValWood** [comment]
I am just looking at 
https://www.uniprot.org/uniprotkb/P05198/entry
for a different reason and this is a nice example of a gene which shouldn't be annotated to 

"positive regulation of neuron death"
https://pubmed.ncbi.nlm.nih.gov/18508033/
cell death in response to toxin (pathological)
Rotenone-induced cell death preceded intracellular accumulation of reactive oxygen species, and antioxidants failed to protect cells, indicating that oxidative stress was minimally involved in rotenone-induced death of SK-N-MC cells.
An eIF2alpha siRNA significantly reduced rotenone cytotoxicity. 

This is because the general stress response inhibits eIF2alpha, this causes a decrease in translation globally , and an increase in translation of a subset of stress responsive genes, so this seems to be general stress pathway.
you could probably use GO:0036490   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0036490/complete)
regulation of translation in response to endoplasmic reticulum stress
The cell death in this case is not desirable, its cytotoxicity.

**Comment by pgaudet** [comment]
@ValWood You left out all the regulation annotations. I edited the spreadsheet, we have some more corrections to to: 

https://docs.google.com/spreadsheets/d/1QxcMlE5FVF9oAlMZmXDUduvu7DNhp7BGHo7K_ITUIf4/edit#gid=0

UCL | 88 (we have fewer than QuickGO because chains are not being loaded in AmiGO)
CAFA | 4
DFLAT | 3
FlyBase | 21
MGI | 18
RGD | 83
UniProt | 58
ZFIN | 2

**Comment by RLovering** [comment]
Thanks Val
That is a great I agree that many of these may be over annotated - I do try to convince people not to curate potential toxic effects - hopefully not too many are my own - lol

Best

Ruth

**Comment by ValWood** [comment]
Sorry everyone!

**Comment by LiNiMGI** [comment]
MGI done

**Comment by sramachand** [comment]
ZFIN done

**Comment by ValWood** [comment]
It is described as an "active process" in a number of places from Googling, but is it a cell death? it seems like some sort of repair with autophagy of part of the neurone?

**Comment by hattrill** [comment]
yes- it seems to be either retrogrde or anterograde in terms of localization, can also occur trans-synaptically!!! Think that these might be better  under some vague 'response to injury' as looking at the literature, I can't discern a pathway.

**Comment by pgaudet** [comment]
@hattrill is this the right ticket ?

**Comment by hattrill** [comment]
@pgaudet yes - a couple of my neuron death papers are about Wallerian degeneration as a type of death.

**Comment by hattrill** [comment]
FB done. 
for Wallerian degeneration (annotation to +ve reg neuron death) changed to response to axon injury
and for another Wallerian degeneration paper,  annotation to -ve reg neuron death, removed as no evidence that survival of neurones = -ve reg cell death.

**Comment by Antonialock** [comment]
@hattrill I wondered if the Wallerian thing is part of regeneration (need to tear down before rebuilding) but I used "response to axon injury" too.

I agree the mechanism doesn't look very clear (looking at https://en.wikipedia.org/wiki/Wallerian_degeneration). I guess once the pathway is known things can be fitted to a new term...

**Comment by Antonialock** [comment]
CAFA DFLAT and Uniprot done

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
