### ISSUE TITLE
Review annotations to GO:1990259 histone glutamine N-methyltransferase activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4427]
Dear all, 

The proposal has been made to obsolete GO:1990259 histone glutamine N-methyltransferase activity 
see https://github.com/geneontology/go-ontology/issues/24397

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0

Impacted groups: 
UniProt 2 
SGD 1

----

Thanks.

**Comment by srengel** [comment]
this term has been renamed 'histone H2AQ104 methyltransferase activity'.  is it still going to be obsoleted?

**Comment by pgaudet** [comment]
No it should NOT be obsoleted @ValWood
