### ISSUE TITLE
Review annotations to GO:0070940 dephosphorylation of RNA polymerase II C-terminal domain

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4428]
Dear all, 

The proposal has been made to obsolete GO:0070940 dephosphorylation of RNA polymerase II C-terminal domain. The reason for obsoletion is that this represents a molecular function represented as a biological process, see https://github.com/geneontology/go-ontology/issues/24824

Annotations: https://docs.google.com/spreadsheets/d/1oFHaeYE-G8-wPxzJlNSpfAkNmbLgv7VebOm2lLVkjSA/edit#gid=0
There are 15 experimental annotations to this term by 
FlyBase - 2
TAIR - 1
SGD - 12

There are 2 InterPro2GO mappings to this term: InterPro:IPR039189 and InterPro:IPR039693
and 3 UniRules:  UniRule:UR001628777, UniRule:UR001419780 and UniRule:UR001253786

Thanks, Pascale

**Comment by srengel** [comment]
SGD done.

**Comment by hattrill** [comment]
fb done

**Comment by sarach06** [comment]
Dear Pascale,
Thank you very much. Following #24824, I have removed GO:0070940 from both entries.
Best wishes,
Sara

**Comment by tberardini** [comment]
TAIR reviewed and done.

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
