### ISSUE TITLE
Review annotations to piRNA processing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4432]
Dear all, 

We have create new terms, 'primary piRNA processing' and 'secondary piRNA processing, see https://github.com/geneontology/go-ontology/issues/23135

Annotations should be rehoused as suggested here: 
https://docs.google.com/spreadsheets/d/1HY8e48mwjpQRyl37S6pjGsfiGG_PGwV73C2Kosb1iOg/edit#gid=0

(note the 'primary piRNA processing has just been created, it will not be available in annotation tools just yet) 

Thanks, Pascale

**Comment by vanaukenk** [comment]
WB done

**Comment by pgaudet** [comment]
1 remaining ZFIN annotation

**Comment by pgaudet** [comment]
ping @sramachand

**Comment by sramachand** [comment]
ZFIN done.
