### ISSUE TITLE
Review annotations to GO:0036254 cellular response to amiloride, GO:0015898, GO:0036253, GO:0072755

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4433]
Dear all, 

The proposal has been made to obsolete
GO:0036254 cellular response to amiloride
GO:0015898 amiloride transport
GO:0036253 response to amiloride
GO:0072755 cellular response to benomyl
see https://github.com/geneontology/go-ontology/issues/21394

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1vL7oJgZMOhGIiwye7hrRtjLtpgXmalww_tUtHA9G1Lk/edit#gid=0

Impacted groups: 
GO:0015898 amiloride transport | MGI 1
GO:0036253 response to amiloride | RGD 1
GO:0036254 cellular response to amiloride | ComplexPortal 13
GO:0072755 cellular response to benomyl | UniProt 1

----

Thanks.

**Comment by Antonialock** [comment]
uniprot done

**Comment by pgaudet** [comment]
Terms are now obsolete, see https://github.com/geneontology/go-ontology/issues/24817
Any remaining annotation will appear in error reports.
