### ISSUE TITLE
Protein O-mannosyl-transferase TMTC, DUF1736 (IPR013618)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4434]
* **InterPro ID / label**
Protein O-mannosyl-transferase TMTC, DUF1736 (IPR013618)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly genes/proteins as follows (human orthologs in brackets):
FBgn0020312	Tmtc3/Q7K4B6 (TMTC3/Q6ZXV5)
FBgn0028481	CG4341/Q9V3X5 (TMTC2/Q8N394) 
FBgn0038324	CG5038/Q9VF81 (TMTC4/Q5T4D3)
FBgn0051690	CG31690/Q9VQE9 (TMTC2/Q8N394)

* **Description of issue**
I think you can associate "dolichyl-phosphate-mannose-protein mannosyltransferase activity (=EC:2.4.1.109)" with this entry

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you very much for your suggestion. I am not aware of any evidence the region covered by this entry is the catalytic domain of these enzymes. Please let me know if there is something I missed.

Best regards,
Beatriz

**Comment by sjm41** [comment]
Hi Beatriz

Ah, yes. You're right!  Never mind....
Thanks for checking!
