### ISSUE TITLE
Review annotations to GO:0004652 polynucleotide adenylyltransferase activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4435]
Dear all, 

The proposal has been made to obsolete GO:0004652 polynucleotide adenylyltransferase activity, see 
You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24859

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/11KVvu1s9hqsDEVNTgfLB85GYDseA1qiYb2RpVkaIYG4/edit#gid=0

Impacted groups: 
(20) SGD
(16) UniProt
(5)	FlyBase
(5)	PomBase
~(5)	WB~
(2)	GeneDB
(1)	CGD
(1)	ComplexPortal
(1)	EcoliWiki
(1)	MGI

There are 6 InterPro mappings:
InterPro:IPR007012
InterPro:IPR007010
InterPro:IPR014492
InterPro:IPR040136
InterPro:IPR040137
InterPro:IPR045862
 
1 UniRule
UniRule:UR000999770
 
1 EC: will be moved in the ontology
EC:2.7.7.19

1 RHEA: will be moved in the ontology
RHEA:11332

Thanks, Pascale

**Comment by pgaudet** [comment]
There is also one Reactome reaction: 
Reactome:R-HSA-72185

**Comment by sjm41** [comment]
FlyBase done

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. I have checked these entries and updated the term (changed to GO:1990817). IPR040136 and IPR040137 don't exist any more as they included PANTHER subfamilies and were deleted. I found additional entries mapping to GO:0004652 (IPR010206, IPR004976 and IPR037265) which were also updated. These changes will be available in InterPro 93.0.
Best,
Sara

**Comment by pgaudet** [comment]
Thank you. Sorry I missed some entries! Thanks for checking.

**Comment by jlewsmith** [comment]
CGD done

**Comment by deustp01** [comment]
Reactome done - this one is easy

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
