### ISSUE TITLE
PTN001998983 |

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4436]
* **PTHR ID & PTN node:**

GO:0033615 | mitochondrial proton-transporting ATP synthase complex assembly | IBA with S000004704 , PTN001998983 | Gaudet P et al. (2011) | 8

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC31A2.06

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous source. This is indirect phenotype since atp25 is a  mitochondrial polynucleotide adenylyltransferase
required for mRNA stability (so presumably upstream of complex assembly)

**Comment by marcfeuermann** [comment]
Corrected
