### ISSUE TITLE
RNA polymerase, Rpb8  IPR005570

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4438]
* **InterPro ID / label**
RNA polymerase, Rpb8  IPR005570

* **Description of issue**
I think you can add "[DNA-directed 5'-3' RNA polymerase activity (GO:0003899)"  to this entry. (This GO term is already on other similar InterPro terms that relate to RNApol catalytic subunits shared between all 3 RNApols.)

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I added the term to this entry, which will be visible in the next InterPro release (93.0).
Best,
Sara
