### ISSUE TITLE
Review annotations to GO:0003374 dynamin family protein polymerization involved in mitochondrial fission

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4439]
Dear all, 

The proposal has been made to obsolete GO:0003374 dynamin family protein polymerization involved in mitochondrial fission
see https://github.com/geneontology/go-ontology/issues/24439

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/18KIheiy-e_gIK6m7N0Gjz7WBbUVQ73R45yMXtk5FS2Y/edit#gid=0

Impacted groups: 

UniProtKB 3 @Antonialock 

Thanks.

**Comment by ValWood** [comment]
pinging @Antonialock (only 3 annotations)

**Comment by Antonialock** [comment]
uniprot done
