### ISSUE TITLE
Phosphoglycerate mutase 1  IPR005952

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4445]
* **InterPro ID / label**
Phosphoglycerate mutase 1  IPR005952

* **Description of issue**
This entry has both a parent and child MF term associated with it:
[intramolecular transferase activity, phosphotransferases (GO:0016868)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016868)
[phosphoglycerate mutase activity (GO:0004619)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004619)

Given the description says the family applies to 5.4.2.11 & 5.4.2.4, seems like just the parent term (= 5.4.2.-) should be on the entry?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. Yes, I agree with you. I removed GO:0004619 from this entry, leaving the parent term only. This will be visible in the next InterPro release (93.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara
