### ISSUE TITLE
PTN005210253 (MYOSIN HEAVY CHAIN, NON-MUSCLE (PTHR45615))

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4452]
* **PTHR ID & PTN node:**
PTN005210253 (MYOSIN HEAVY CHAIN, NON-MUSCLE (PTHR45615))

* **Sequences with problematic annotation (ID + gene/protein name):**
D. melanogaster c(3)G (FBgn0000246/Q9VF37)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
erroneous propagation

D. melanogaster c(3)G encodes the transverse filament protein of the synaptonemal complex ([11731477](http://www.ncbi.nlm.nih.gov/pubmed/11731477/), [17947423](http://www.ncbi.nlm.nih.gov/pubmed/17947423/) ) - it doesn't have an ATPase domain and there's no evidence it has motor activity.

But PTN005210253/PTHR45615 is annotating it with "microfilament motor activity "

I'm not sure if that family needs splitting or propagation to c(3)G just needs to be blocked?

**Comment by marcfeuermann** [comment]
This is a complicated family that requires a complete reannotation. I've reviewed the motor activity.
