### ISSUE TITLE
Review annotations to GO:0007568 aging and GO:0010259 multicellular organism aging

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4453]
Dear all, 

The proposal has been made to obsolete GO:0007568 GO:0010259
see https://github.com/geneontology/go-ontology/issues/24930

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1rDT6_mTaDLLCs6ksZJybQF_xTBeJaI0ulp1aDQX8Kes/edit#gid=0

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 
   2 ARUK-UCL	GO:0007568	IEP
   1 ARUK-UCL	GO:0007568	IGI
   ~4 FlyBase	GO:0007568	IMP~
   ~4 FlyBase	GO:0010259	IMP~
  ~1 MGI	GO:0007568	IDA~
  ~17 MGI	GO:0007568	IMP~
   ~1 MGI	GO:0010259	IDA~
  ~58 MGI	GO:0010259	IGI~
  ~29 MGI	GO:0010259	IMP~
  ~28 RGD	GO:0007568	IDA~
 ~315 RGD	GO:0007568	IEP~
   ~1 RGD	GO:0007568	IMP~
   ~2 RGD	GO:0007568	IPI~
  ~15 RGD	GO:0010259	IEP~
   ~1 SGD	GO:0007568	IMP~
  ~8 TAIR	GO:0007568	IEP~
   ~6 TAIR	GO:0007568	IMP~
  ~6 TIGR	GO:0007568	IEP~
  ~1 TIGR	GO:0007568	IMP~
  11 UniProt	GO:0007568	IDA
  17 UniProt	GO:0007568	IMP

Many of the annotations are IEP and from a spot check these seem to describe age-related changes in expression of individual genes and are out of scope for GO (possibly you can do this in your expression annotation?).
Other annotations may be moved to other more appropriate terms - for instance plant terms could sometimes be rehoused under terms like "fruit ripening".
Age-related changes in fertility can be annotated to GO:1990636  reproductive senescence. There might be other examples of 'programmed' developmental processes like this where an appropriate term  does not exist, these can be requested.
GO:0090398   cellular senescence might also be appropriate for some annotations.
 Some of the metazoan annotations are related to processes like insulin/TOR or endocrine signalling which, when manipulated, can extend or reduce lifespan, or other aspects of the 'aging phenotype' (functional decline), which are of scope for GO.

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
NONE

Thanks.

**Comment by srengel** [comment]
SGD done.

**Comment by tberardini** [comment]
Note to self:
GO:0007568 aging
GO:0010259 multicellular organism aging

**Comment by tberardini** [comment]
TAIR and TIGR A. thaliana annotations done

**Comment by LiNiMGI** [comment]
MGI done.
spreadsheet above missing MGI annotations of GO:0010259 from PMID:12634787.

**Comment by hattrill** [comment]
FB done

**Comment by slaulederkind** [comment]
Removing all those "aging" annotations makes me feel young again!

**Comment by sramachand** [comment]
ZFIN done.

**Comment by Antonialock** [comment]
uniprot done

**Comment by ValWood** [comment]
Thank you all for your herculean efforts on this ticket especially @slaulederkind who has rejuvenated! this was one of the bigger ones. Hopefully, your old annotations found better homes.

Only
WormBase (4 annotations) @vanaukenk 
@RLovering  (3 annotations)

so I will proceed to obsoletion with these next week,  hopefully these 7 outstanding annotations can be fixed imminently

**Comment by ValWood** [comment]
still 
WormBase (4 annotations) @vanaukenk
@RLovering (3 annotations)

but all of the others are done, so I will go ahead with the obsoletion today.
Thanks
v

**Comment by RLovering** [comment]
UCL DONE

**Comment by RLovering** [comment]
there are around 100 annotations with these terms in the AE field. I have deleted the terms from the UCL AE field annotations. Attached are the downloads that you might want to record/circulated
[QuickGO-annotations-multiagingAE.xlsx](https://github.com/geneontology/go-annotation/files/11040728/QuickGO-annotations-multiagingAE.xlsx)
[QuickGO-annotations-agingAE.xlsx](https://github.com/geneontology/go-annotation/files/11040729/QuickGO-annotations-agingAE.xlsx)
Or use these URLs:
https://www.ebi.ac.uk/QuickGO/annotations?extension=GO:0007568
https://www.ebi.ac.uk/QuickGO/annotations?extension=GO:0010259

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
