### ISSUE TITLE
PTN000337769 (SEC61 SUBUNIT BETA (PTHR13509))

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4454]
* **PTHR ID & PTN node:**
PTN000337769 (SEC61 SUBUNIT BETA (PTHR13509))

* **Sequences with problematic annotation (ID + gene/protein name):**
D.melanogaster Sec61β (FBgn0010638/Q7JZN0)
Human SEC61B (P60468)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Erroneous source

PTN000337769 adds "protein-transporting ATPase activity(CONTRIBUTES_TO)" to SEC61 SUBUNIT BETA proteins based on a single source annotation to S. cerevisiae SBH1 (P52870).
I don't think that's appropriate - the Sec61 beta subunit is one of three subunits comprising the Sec61 translocon complex, none of which have ATPase activity. That's provided by another protein (called BiP/KAR2/HSPA5) - that is an ATPase and provides the driving force for ratcheting proteins through the Sec61 channel.

See PMID:28564553 for review.

**Comment by marcfeuermann** [comment]
I agree... the annotation has been removed.

**Comment by sjm41** [comment]
Thanks Marc

**Comment by marcfeuermann** [comment]
You're welcome Steven. I see there is still a lot of "CONTRIBUTES_TO" stuff to clean. Thanks for your input.
Take care and stay healthy.
Best regards,
Marc.

**Comment by sjm41** [comment]
I think this one (and the other tickets I made on Friday) must be relatively new PAINT annotations - I hadn't seen them before, and I check annotations for the fly enzymes regularly.
Might have some more tickets for you in the next few days....

Cheers.

**Comment by marcfeuermann** [comment]
Strange, I did not use CONTRIBUTES_TO terms for PAINTing since a while. Anyway, yes, let us know if you have more concerns.
The goal is to have the cleanest set of annotations possible.
Cheers,
Marc.
