### ISSUE TITLE
PTN000249148 PTN000399700 PTN000295357 PTN000334172 PTN000310442 PTN000374345 PTN000299878 PTN001398707 PTN000830013

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4460]
* **PTHR ID & PTN node:**
PTN000249148
PTN000399700
PTN000295357
PTN000334172
PTN000310442
PTN000374345
PTN000299878
PTN001398707
PTN000830013

All these add a "contributes_to RNA polymerase X activity" term to RNApol subunits that lie outside the catalytic core (e.g. see PMID: 22365827), all based on single annotations to the yeast proteins.

Can these annotations be removed please.

**Comment by marcfeuermann** [comment]
All have been cleaned.
