### ISSUE TITLE
O-acyltransferase WSD1, C-terminal (IPR009721)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4462]
* **InterPro ID / label**
O-acyltransferase WSD1, C-terminal (IPR009721)

* **Description of issue**
Description of this entry is "This entry represents the C terminus (approximately 170 residues) of a number of hypothetical plant proteins. O-acyltransferase WSD1 is a bifunctional wax ester synthase/diacylglycerol acyltransferase, which is involved in cuticular wax biosynthesis [1]"
Given this is just the C-terminus (not clear this contains the catalytic domain?) of many hypothetical proteins, and the one characterized protein has two activities, it seems a bit odd that the entry is associated with the one specific GO MF term "diacylglycerol O-acyltransferase activity (GO:0004144)".

I see that the related family entry "O-acyltransferase WSD1-like IPR045034" is associated with a higher level GO MF term (O-acyltransferase activity (GO:0008374) that covers both of the specific activities of WSD1.

So maybe remove GO:0004144 from IPR009721, or replace it with GO:0008374? What do you think?

Thanks.

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this! You are right, this is not the catalytic domain, IPR004255 is that one and it has GO:0004144 associated to it. I have removed this term from the C-terminal domain. These changes will be visible in the next InterPro release (94.0).
Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara
