### ISSUE TITLE
Tyrosine-protein kinase, Fes/Fps type (IPR016250)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4465]
* **InterPro ID / label**
Tyrosine-protein kinase, Fes/Fps type (IPR016250)

* **Description of issue**
Entry description says "This entry represents Fes/Fps family of non-receptor tyrosine kinases."
So I think the current MF term "protein tyrosine kinase activity (GO:0004713)" c/should be changed to the child term "non-membrane spanning protein tyrosine kinase activity (GO:0004715)"?

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have updated the term to the child one, as you suggested. This will be available in InterPro 94.0.
Best,
Sara

**Comment by sjm41** [comment]
Thanks!
