### ISSUE TITLE
PTN000274640 (PTHR12411) - NOT problem

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4467]
* **PTHR ID & PTN node:**
PTN000274640 (PTHR12411)

* **Sequences with problematic annotation (ID + gene/protein name):**
Fly CG6337 (FBgn0033873/Q7JYA0)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
erroneous propagation

PTN000274640 adds "cysteine-type endopeptidase activity" to fly CG6337, but this has "NOT enables cysteine-type peptidase activity" and "NOT enables peptidase activity" IKR annotations.

**Comment by marcfeuermann** [comment]
Reviewed the whole family.
