### ISSUE TITLE
PTN001650889 (PTHR43226) - NOT problem

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4468]
* **PTHR ID & PTN node:**
PTN001650889 (PTHR43226)

* **Sequences with problematic annotation (ID + gene/protein name):**
Fly CG32454 (FBgn0260481/Q8IPS7)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
erroneous propagation

PTN001650889 adds "aminopeptidase activity" to fly CG32454, but this has "NOT enables peptidase activity" IKR annotation.

**Comment by marcfeuermann** [comment]
Corrected.
