### ISSUE TITLE
Review annotations to  GO:0035174    histone serine kinase activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4469]
Dear all, 

The proposal has been made to obsolete  GO:0035174    histone serine kinase activity 
see https://github.com/geneontology/go-ontology/issues/24397

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1li9nkga5EE74p_SieWbUIrymKJvS0G9m2FQj4f97h7Q/edit#gid=0

Impacted groups: 
MGI 1 
UniProt 2

Thanks, Pascale

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by pgaudet** [comment]
uniprot done
