### ISSUE TITLE
Review annotations to GO:0000335 negative regulation of transposition, DNA-mediated, and and GO:0010526 negative regulation of transposition, RNA-mediated

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4480]
Dear all, 

The proposal has been made to obsolete GO:0000335 negative regulation of transposition, DNA-mediated, and and GO:0010526 negative regulation of transposition, RNA-mediated

see https://github.com/geneontology/go-ontology/issues/23746

Experimental annotations that need to be reviewed are here: 

DNA mediated: https://docs.google.com/spreadsheets/d/1lJVML5EPKMUt-vJmk_iYGgXVOi3TNXvF-Gzv4D8PXQI/edit#gid=0
Impacted groups: 
FB (3 EXP) 
WormBase (3 EXP)
TAIR (2 EXP)
3 UniProt (new term needed) 

Thanks, Pascale

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
3 WB left @vanaukenk

**Comment by pgaudet** [comment]
Hi Kimberly - Colin and I reviewed this - 3 annotations to a single paper, and proposed a new annotation. Hopefully that helps!

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
