### ISSUE TITLE
pICln-Sm protein complex (GO:0034715)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4481]
https://www.pombase.org/term/GO:0034715

Is
Definition	Parents
A protein complex that contains pICln (CLNS1A) and several Sm proteins, including SmD1, SmD2, SmE, SmF, and SmG. [PMID:11713266]

But we only have 2 subunits PAINTED

SNRPD1 Smd1 (binds saf5). PAINTED
SNRPD3 Smd3  (binds saf5) PAINTED

I wonder if these could be PINTED too?

CLNS1A Saf5 (binds smd1/3). PTN000483770 
SNRPE Sme1  PTN000127555
SNRPF Smf1 PTHR11021
SNRPD2 Smd2 PTHR12777

All of the EXP annotations come from the same paper
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0034715&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

(I try to make sure each subunit of a complex is  conserved and annotated, so I can do this manually, but it makes most sense to PAINT it)

**Comment by marcfeuermann** [comment]
Hi Val, this is a great suggestion. I will look at the families. If we have primary annotations, I will PAINT them. Thanks.

**Comment by marcfeuermann** [comment]
Great ! Done.
