### ISSUE TITLE
 PTN000063908 NOT eukaryotic translation initiation factor 2B complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4482]
* **PTHR ID & PTN node:**

GO:0005851 | eukaryotic translation initiation factor 2B complex | IBA with PTN000063908 , P05198

Definition | Parents
-- | --
A multisubunit guanine nucleotide exchange factor which catalyzes the exchange of GDP bound to initiation factor eIF2 for GTP, generating active eIF2-GTP. In humans, it is composed of five subunits, alpha, beta, delta, gamma and epsilon.

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC3G9.09c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This is  [eukaryotic translation initiation factor 2 complex](https://www.pombase.org/term/GO:0005850)
not 2B

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprotkb/P05198/entry
@Antonialock  could you remove this annotation (I still can't do disputes in Protein2GO)

eukaryotic translation initiation factor 2B complex (https://www.ebi.ac.uk/QuickGO/term/GO:0005851)

This is 

eukaryotic translation initiation factor 2 complex (which is a regulator of  eIF2B, both positive and negative depending on phosphorylation status)

Supplementation of such preparations with recombinant eIF2Balpha markedly enhances activity, indicating that eIF2Balpha is required for full activity of mammalian eIF2B.

**Comment by ValWood** [comment]
Actually this isn't  EIF2A its EIF2S1 - but it must be a paralog because it is mapping pombe EIF2A to the 2B complex term...

**Comment by ValWood** [comment]
I'm really confused by this. 
P05198 has the message
This gene should not be confused with EIF2A, with which it shares the alias EIF2A. Although both of these proteins function in binding initiator tRNA to the 40S ribosomal subunit, the eIF2 complex requires GTP, whereas the EIF2A protein does so in a codon-dependent manner.

but it is EIF2A at least it's conserved 1:1 and this is EIF2A in yeast. Id this warning applied to the correct protein?

**Comment by ValWood** [comment]
Right EIF2A vs EIF2alpha  this is EIF2alpha

**Comment by marcfeuermann** [comment]
Yes it is the alpha subunit of eIF2 complex. I've removed propagation of eIF2B complex. I let this open until the primary GO annotation is corrected.

**Comment by Antonialock** [comment]
Just wanted to clarify I don't need to do anything right?

**Comment by ValWood** [comment]
You will need to double check which way around it should be, but one of these 2 annotation is incorrect:
<img width="844" alt="Screenshot 2023-03-21 at 14 49 44" src="https://user-images.githubusercontent.com/7359272/226644464-1c001684-83f4-49b7-8c2c-95960109bd92.png">

**Comment by marcfeuermann** [comment]
Thanks Antonia. So I think we can close this one.
