### ISSUE TITLE
Review annotations to GO:1905224 clathrin-coated pit assembly (and its regulation terms)

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4483]
Dear all, 

The proposal has been made to obsolete 
GO:1905224 clathrin-coated pit assembly

see https://github.com/geneontology/go-ontology/issues/22873

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1PKgOz3RyUFL7zjJwAQ2w2QclEQm1WnAYdlCRbFulmHc

Impacted groups: 
UCL 2 EXP
UniProt 1 EXP

----

Thanks.

**Comment by pgaudet** [comment]
UniProt done

**Comment by RLovering** [comment]
ucl done
