### ISSUE TITLE
Review annotations to some hydroxyacyl-CoA dehydratase activity terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4488]
Dear all,

The proposal has been made to obsolete
GO:0080023 (3R)-3-hydroxyacyl-CoA dehydratase activity -> 6 EXP
GO:0003859 (3R)-3-hydroxybutyryl-CoA dehydratase activity -> 1 EXP
GO:0102158 very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity -> 0 EXP, all IEAs RHEA/EC
GO:0016508 long-chain-enoyl-CoA hydratase activity -> 7 EXP

see https://github.com/geneontology/go-ontology/issues/24738

**Comment by gthayman** [comment]
RGD done.

**Comment by deustp01** [comment]
Reactome done - fixed the two noted (GO:0016508) in the spreadsheet and two additional ones (GO:0080023, GO:0003859) not noted.

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
