### ISSUE TITLE
O-phosphoseryl-tRNA(Sec) selenium transferase (IPR019872)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4490]
* **InterPro ID / label**
O-phosphoseryl-tRNA(Sec) selenium transferase (IPR019872)

* **Description of issue**
Current entry description: _In the archaea and eukaryotes, the conversion of the mischarged serine to selenocysteine (Sec) on its tRNA is accomplished in two steps. This enzyme, O-phosphoseryl-tRNA(Sec) selenium transferase, acts second, after a phosphophorylation step catalysed by a homologue of the bacterial SelA protein. It converts O-phosphoseryl-tRNA(Sec) to selenocysteinyl-tRNA(Sec), which is required for selenoprotein biosynthesis._

Current GO term is selenotransferase activity (GO:0016785).
Looks like that could be changed to the child term "phosphoseryl-selenocysteinyl-tRNA selenium transferase activity (GO:0098621), which has definition "O-phosphoseryl-tRNA(Sec) + selenophosphoric acid + H2O => L-selenocysteinyl-tRNA(Sec) + 2 phosphoric acid."
(And the EC xref on that GO term (EC:2.9.1.2) is the same as the EC xref on the InterPro page)

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. I have updated the term for the child one as you suggested. This will be available in the next InterPro release (94.0).
Best,
Sara
