### ISSUE TITLE
Simple report systems not working ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4491]
https://github.com/geneontology/go-annotation/actions/runs/4305264641

**Comment by kltm** [comment]
Specifically, reports for #4488 and #4489 not generated; run actions indicate errors.

**Comment by kltm** [comment]
Can reproduce locally:
```python3 ./scripts/annotation-review-report.py geneontology/go-annotation 7 --number 4488 --label direct_ann_to_list_of_terms --field annotation_class --output /tmp/ --verbose
```

**Comment by kltm** [comment]
@pgaudet The issue seems to be that there are no annotations meeting the criteria for a given term. For example, GO:0102158 has no annotations for ECO:0000006.
As a fix, I'll make it more robust to these kinds of errors.

**Comment by kltm** [comment]
@pgaudet I think that's it. If things are working better, go ahead and close.

**Comment by pgaudet** [comment]
I have a longer list of terms here, and no report being generated after 15 minutes
https://github.com/geneontology/go-annotation/issues/4494

**Comment by kltm** [comment]
> I have a longer list of terms here, and no report being generated after 15 minutes #4494

See https://github.com/geneontology/go-annotation/issues/4495 for new issue
