### ISSUE TITLE
Review annotations to GO:2000653 regulation of genetic imprinting

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#4501]
Dear all, 

The proposal has been made to obsolete GO:2000653 regulation of genetic imprinting
see https://github.com/geneontology/go-ontology/issues/25010

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1g7iIQCElmy9rfN554KGKisF-zVWlu9dyQi0NmUtARl0/edit?usp=sharing

Impacted groups: 
MGI: 5
UniProt: 9
BHF-UCL: 1

----

Mappings that need to be reviewed: none

Thanks.

**Comment by pgaudet** [comment]
@Antonialock I'll review these with Colin on Friday

**Comment by RLovering** [comment]
ucl done

**Comment by pgaudet** [comment]
@krchristie Colin and I reviewed the 3 remaining mouse papers and made some suggestions for reaannotation.

**Comment by krchristie** [comment]
> @krchristie Colin and I reviewed the 3 remaining mouse papers and made some suggestions for reaannotation.

@pgaudet - Regarding this comment:
> Colin says that the authors are not using 'genetic imprinting' in the sense of inherited form the parental imprinting, but they refer to ''transcription initiation-coupled chromatin remodeling''; this term would be more accurate.
> 
> krchristie MGI
> MGI:MGI:109345 = Ctr9
> PMID:24036311
> GO:2000653 = regulation of genetic imprinting
> IMP
> 20141105
> NCBITaxon:10090
> PANTHER:PTHR14027

@LiNiMGI  and I disagree that this paper doesn’t specifically talk about imprinted genes. While much of the beginning of the paper is about more general effects of knockdown of Ctr9, on page 19 of the paper, the section header is “Ctr9 deficiency leads to aberrant expression of imprinted genes”. In that section on p 21, they talk about two specific imprinted genes which exhibit loss of imprinting in blastocysts lacking Ctr9. Based on this section, I’ve chosen the term “negative regulation of gene expression, epigenetic” and put the specific genes as input for the regulation.

**Comment by pgaudet** [comment]
OK thanks for the feedback and the review!
