### ISSUE TITLE
Creatinase, N-terminal (IPR000587)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4502]
* **InterPro ID / label**
Creatinase, N-terminal (IPR000587)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly CG6225 (FBgn0038072/Q9VG44) = non-peptidase homolog

* **Description of issue**
This entry is based on [PF01321](https://www.ebi.ac.uk/interpro/entry/pfam/PF01321/), which says "This family includes the N-terminal non-catalytic domains from creatinase and prolidase. The exact function of this domain is uncertain."

But the InterPro entry is associated with "[hydrolase activity (GO:0016787)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016787)".  I think that should be removed

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. I have removed the term from this entry, which will be visible in InterPro 94.0.
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks!
