### ISSUE TITLE
IPR003593 (AAA+ ATPase domain) & IPR003439 (ABC transporter-like, ATP-binding domain)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4506]
* **InterPro ID / label**
IPR003593 (AAA+ ATPase domain) & IPR003439 (ABC transporter-like, ATP-binding domain)

* **Description of issue**
I think "ATP hydrolysis activity" (GO:0016887) can be added to both these entries?  (IPR003439 is a 'child' of 'IPR003593')

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this. I added the GO term to the parent entry, which includes the proteins in the child. The changes will be available in the next InterPro release.

Best regards,

Beatriz

**Comment by sjm41** [comment]
Hi @blazaropinto 
Turns out there are a couple of fly proteins (CG11069/Q8MRJ2, CG31121/Q0KI14) that lack the parent InterPro signature (IPR003593) and only have the child entry (IPR003439).
Is it possible/appropriate to add "ATP hydrolysis activity" (GO:0016887) to IPR003439 too? What do you think?

**Comment by blazaropinto** [comment]
Missed these trEMBL sequences, thank you so much for spotting this Steven, I added the term to IPR003439 too. The changes will be available in the next InterPro release.
Best,
Beatriz
