### ISSUE TITLE
ATPase, V1 complex, subunit A (IPR005725)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4507]
* **InterPro ID / label**
ATPase, V1 complex, subunit A (IPR005725)

* **Description of issue**
I think you can add "ATP hydrolysis activity" (GO:0016887) to this entry.

Entry description ends with "This entry represents subunit A from the V1 complex of V-ATPases. There are three copies each of subunits A and B ([IPR005723]), both of which participate in nucleotide binding. However, only subunit A is catalytic, functioning in ATP hydrolysis to drive the rotation of the D and F subunits of V1, as well as the V0 complex c-ring rotor subunit for proton translocation"

**Comment by blazaropinto** [comment]
Hi Steven,

I agree. Thank you for pointing this out. I added the term. The changes will be available in the next InterPro release.

Best regards,

Beatriz
