### ISSUE TITLE
IPR001753 ('Enoyl-CoA hydratase/isomerase')

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4509]
* **InterPro ID / label**
IPR001753 ('Enoyl-CoA hydratase/isomerase')

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly Srlp (FBgn0038049/Q9VG69)

* **Description of issue**
This entry is associated with the top-level term 'catalytic activity', which is consistent with the description ("This family contains a diverse set of enzymes...) but isn't very informative. Moreover, many of its 'child' terms (listed under 'family relationships') have no GO terms associated (although some have very specific GO terms).

Also, IPR001753 is found in at least one fly protein that is not known to be catalytic:
Srlp (FBgn0038049/Q9VG69) - a regulatory protein characterized in PMID:30931935

So, maybe remove 'catalytic activity' from IPR001753? (Could review the IPR001753 children to see if more of them could have more specific/informative GO terms added?)

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this. I agree, I removed this too general term and added 

- GO:0016829 and GO:0019439 to IPR017602
- GO:0016823 to IPR017613
- GO:0016829 to IPR017633
- GO:0016853 to IPR045002

The changes will be available in the next InterPro release.

Best regards,

Beatriz
