### ISSUE TITLE
PMID:18622392 complex Portal NAS annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4510]
Hello,

Complex Portal have made a number of NAS annotations  from

PMID:18622392

to
double-strand break repair via nonhomologous end joining
	arp42, arp9, rsc1, rsc4, rsc58, rsc7, rsc9, sfh1, snf21, ssr1, ssr2, ssr3, ssr4
	positive regulation of double-strand break repair via homologous recombination
	arp42, arp9, snf22, snf30, snf5, snf59, sol1, ssr1, ssr2, ssr3, ssr4, tfg3

these are incorrect, could they be removed please?

Thanks

Val

**Comment by ValWood** [comment]
Sandra, pls let me know  who I should tag for these.

**Comment by sandraorchard** [comment]
Removed - and I am your only contact at the moment. Henning has recruited a new Complex Portal curator, but she is still on IntAct curation-101 so its going to be a few months before I can dump this on her. We are also well overdue for a release as they have fallen foul of the EBI server migration which caused UniProt to skip releases a few months earlier, but I am (largely) on top of changes and they hopefully will go public next month.
