### ISSUE TITLE
PTN000085952 post-translational protein targeting to endoplasmic reticulum membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4515]
I'm not completely sure about this one:

* **PTHR ID & PTN node:**

- | GO:0006620 | post-translational protein targeting to endoplasmic reticulum membrane | IBA with PTN000085952 , S000002258 , ZDB-GENE-040625-120

defined

from
 [S000002258](https://www.yeastgenome.org/locus/S000002258) , [ZDB-GENE-040625-120](http://zfin.org/ZDB-GENE-040625-120)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1142.06
(get complex subunit)

Get complex is
An endoplasmic reticulum protein-containing complex that is conserved in eukaryotics and that mediates the insertion of tail-anchored proteins into the ER membrane. In yeast, includes Get1p, Get2p and Get3p proteins.

post-translational protein targeting to endoplasmic reticulum membrane
is

Definition | Parents
-- | --
The targeting of proteins to a membrane that occurs after their translation. Some secretory proteins exhibit posttranslational transport into the endoplasmic reticulum (ER) lumen: they are synthesized in their entirety on free cytosolic ribosomes and then released into the cytosol, where they are bound by chaperones which keep them in an unfolded state, and subsequently are translocated across the ER membrane.

so the annotations don't seem to be correct?

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Hi Val,
In my opinion there is a problem with the definition of the term. I would say that annotation is correct when you look at the term itself or the first sentence of the definition. Then the second part of the definition explains something totally different, since it is not targeting to membrane anymore but to the ER lumen to be further secreted. So the term is indeed confusing...

**Comment by ValWood** [comment]
I forgot about this, you are correct!
https://github.com/geneontology/go-ontology/issues/21053
I will add this ticket to my list!

**Comment by marcfeuermann** [comment]
Issue 21053 seems still open. Anyway, at the PAINT level, I've removed the "suspect" term and annotated with the clear term
tail-anchored membrane protein insertion into ER membrane (GO:0071816).
