### ISSUE TITLE
Review annotations to GO:0006379 mRNA cleavage, GO:0031439 positive regulation of mRNA cleavage, GO:0031437 regulation of mRNA cleavage, GO:0031438 negative regulation of mRNA cleavage,

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4517]
Dear all, 

The proposal has been made to obsolete:
GO:0006379 mRNA cleavage, 
GO:0031439 positive regulation of mRNA cleavage, 
GO:0031437 regulation of mRNA cleavage, 
GO:0031438 negative regulation of mRNA cleavage, 

see 
https://github.com/geneontology/go-announcements/issues/508
https://github.com/geneontology/go-ontology/issues/25185

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/15WJP7JS2Ia8vgEbwsDP00bOMfqrk_2XFZEVIuV1atyA/edit#gid=0

Impacted groups: 
2 SGD @srengel 
~1 TAIR @tberardini~
~3 Uniprot @Antonialock~
1 CACAO @dsiegele
1 Ecocyc @amandamackie

Thanks.

**Comment by tberardini** [comment]
TAIR done

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by Antonialock** [comment]
I don't do CACAO @dsiegele
 (maybe you got it mxed up with CAFA)

**Comment by ValWood** [comment]
> (maybe you got it mxed up with CAFA)

always!

**Comment by srengel** [comment]
SGD done.
