### ISSUE TITLE
Review annotations to GO:0098787 mRNA cleavage involved in mRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4518]
Dear all, 

The proposal has been made to obsolete 
GO:0098787 mRNA cleavage involved in mRNA processing

see https://github.com/geneontology/go-ontology/issues/25185#issuecomment-1479899916

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1KnMYeufddThcZD9VY_QXy3Rtt-p_m9_ACGfyK1WER0Q/edit#gid=0

Impacted groups: 
1 ComplexPortal @sandraorchard 
~1 ParkinsonsUK-UCL @RLovering~ 
1 SGD @srengel 
1 UniProt @Antonialock 

Thanks.

**Comment by RLovering** [comment]
ucl done

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by Antonialock** [comment]
uniprot done

**Comment by srengel** [comment]
SGD done.
