### ISSUE TITLE
Peptidase C1B, bleomycin hydrolase (IPR004134)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4520]
* **InterPro ID / label**
Peptidase C1B, bleomycin hydrolase (IPR004134)

* **Description of issue**
Entry currently has "[cysteine-type peptidase activity (GO:0008234)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008234)" but I think this can be changed to the more specific child term 'cysteine-type aminopeptidase activity' (GO:0070005)'

E.g. The interpro description starts with "This group of proteins belong to MEROPS peptidase family C1, subfamily C1B. This family contains prokaryotic and eukaryotic aminopeptidases"

And Merops describes C1B as aminopeptidases: https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=C1B

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this, I agree, the term is now changed. The changes will be visible in the next InterPro release.

Best regards,
Beatriz
