### ISSUE TITLE
Peptidase S28 (IPR008758)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4521]
* **InterPro ID / label**
Peptidase S28 (IPR008758)

* **Description of issue**
MEROPS says S28 is specifically for exopeptidases (https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=S28), so I think you can improve the current '[serine-type peptidase activity (GO:0008236)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008236)' term to ''serine-type exopeptidase activity' (GO:0070008).'

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this, agreed, the term is now changed. The changes will be visible in the next InterPro release.

Best regards,
Beatriz
