### ISSUE TITLE
Presenilin/signal peptide peptidase (IPR006639)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4522]
* **InterPro ID / label**
Presenilin/signal peptide peptidase (IPR006639)

* **Description of issue**
This currently has '[aspartic-type endopeptidase activity (GO:0004190)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004190)'.
I think you can change this to the more specific 'aspartic endopeptidase activity, intramembrane cleaving' (GO:0042500)'.
Same goes for the child terms of IPR006639.

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this, I agree, the term is now changed in all these entries. The changes will be visible in the next InterPro release.

Best regards,
Beatriz
