### ISSUE TITLE
Serine/threonine-protein kinase, active site (IPR008271)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4523]
* **InterPro ID / label**
Serine/threonine-protein kinase, active site (IPR008271)

* **Description of issue**
The entry label here suggests the associated GO term should be changed from the current "protein kinase activity (GO:0004672)" to "protein serine/threonine kinase activity' (GO:0004674)".

I note that @ValWood previously asked (#1233) that the GO term be "protein kinase activity (GO:0004672)" because the InterPro term hits MAP kinases that she said catalyze "the concomitant phosphorylation of threonine (T) and tyrosine (Y) residues in a Thr-Glu-Tyr (TEY) thiolester sequence in a MAP kinase (MAPK) substrate." [ISBN:0198547684]".

Is that really true?  Several reviews I looked at and Wikipedia says MAPKs are serine/threonine kinases (https://en.wikipedia.org/wiki/Mitogen-activated_protein_kinase).  Also GO has 'MAP kinase activity' as a child of 'protein serine/threonine kinase activity'.

**Comment by ValWood** [comment]
Possibly not MAP kinases,
but there is evidence that some  members of the family auto tyrosine phosphorylate

https://www.pombase.org/gene/SPBC1347.06c
https://www.pombase.org/gene/SPBC3H7.15
https://www.pombase.org/gene/SPAC23C4.12
https://www.pombase.org/gene/SPAC1687.15
https://www.pombase.org/gene/SPAC823.03

I'm getting IEA mappings to tyrosine kinase for the MAP kinases, I'm not sure if these are correct, but it might be a similar situation.  I seem to remember that a lot of kinases auto tyrosine phosphorylate to activate?

**Comment by ValWood** [comment]
OK agreed, sorry I misread!

**Comment by tony787** [comment]
Hi Steven,
Amongst this InterPro signature hits are dual specificity protein kinases that can act as both tyrosine kinases and serine/threonine kinases. In this case, I believe, keeping the more generic term would be better. I hope this gives an answer to your question.
Best wishes,
Toni

**Comment by sjm41** [comment]
Thanks Toni.
Understood. Though given all dual-specificity protein kinases have serine/threonine kinase activity, it would still be correct to annotate this entry with "protein serine/threonine kinase activity", no?

**Comment by tony787** [comment]
Hi Steven,
No, because amongst the hits are also WEE/WEE1/WEE2 kinases and these as far as I can see are only tyrosine kinases. In this case, "protein serine/threonine kinase activity" would not apply to all proteins annotated with this signature.

**Comment by sjm41** [comment]
Aha, so bona fide tyrosine kinases also have this signature!  In that case, I agree with leaving the GO term as 'protein kinase activity'.
Can the InterPro entry name be changed to 'protein kinase, active site' to more accurately describe the entry and avoid this confusion in future?

**Comment by tony787** [comment]
This entry is a Prosite pattern and it is designed to match a serine/threonine kinase active site. There is another pattern that is specific for the tyrosine kinase active site (IPR008266). As far as I know from experience, there is no clear cut between serine/threonine and tyrosine kinases, and there are some tyrosine kinases that are more similar in sequence to serine/threonine kinases. We can add in the signature description these tyrosine kinases as an exception but I think it is best to keep the entry name as this is the main group detected.
