### ISSUE TITLE
Dual specificity tyrosine-phosphorylation-regulated kinase (IPR042521)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4524]
* **InterPro ID / label**
Dual specificity tyrosine-phosphorylation-regulated kinase (IPR042521)

* **Description of issue**
I think you can add 'protein serine/threonine/tyrosine kinase activity' (GO:0004712)" to this entry.

**Comment by sarach06** [comment]
Dear Steven,
Thank you very much. I have added to term to this entry, which will be visible in the next InterPro release (94.0).
Best regards,
Sara
