### ISSUE TITLE
Carbohydrate/purine kinase, PfkB, conserved site (IPR002173)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4526]
* **InterPro ID / label**
Carbohydrate/purine kinase, PfkB, conserved site (IPR002173)

* **Description of issue**
This entry currently has the GO-MF term "phosphotransferase activity, alcohol group as acceptor (GO:0016773)".
But from the term name and description, it seems this could be replaced with the child term "kinase activity (GO:0016301)"

What do you think?

**Comment by tony787** [comment]
Hi Steven,
I think it is correct and so I replaced the GO term for this entry. The changes will be available in the next InterPro release.
Best,
Toni
