### ISSUE TITLE
IPR006840 Glutathione-specific gamma-glutamylcyclotransferase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4527]
* **InterPro ID / label**
IPR006840 Glutathione-specific gamma-glutamylcyclotransferase

* **Description of issue**
Current GO is "gamma-glutamylcyclotransferase activity (GO:0003839)" but it should be "GO:0061928 glutathione specific gamma-glutamylcyclotransferase activity"

**Comment by tony787** [comment]
Hi Steven,
I have replaced the Go term for this entry. The changes will be available in the next InterPro release.
Best,
Toni

**Comment by sjm41** [comment]
Thanks Toni!
