### ISSUE TITLE
Review annotations to protein initiator methionine removal (GO:0070084) and protein initiator methionine removal involved in protein maturation (GO:0035551)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4529]
Dear all, 

The proposal has been made to obsolete 
protein initiator methionine removal (GO:0070084)
and
protein initiator methionine removal involved in protein maturation (GO:0035551)

see  https://github.com/geneontology/go-ontology/issues/25210

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/11XegsfMZcdZi9WEsVZA-omiQNokBevoqGO5WMIjll0A/edit#gid=0

2 MTBBASE
2 SGD
5 Uniprot
1 EcoCyc

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

None

Thanks.

**Comment by ValWood** [comment]
@Antonialock
@srengel 
@amandamackie 

Note that here I will do "replaced by, so the annotations will be migrated automagically to the parent. You don't need to fix the BP annotation.
However, to get the specificity that this is  "N-terminal initiation methionine removal", you should 
add the resurrected molecular function term


GO:0004239 | initiator methionyl aminopeptidase activity

(this is part of the work to remove molecular functions, and particularly  modification terms,  from the 
BP ontology)

**Comment by ValWood** [comment]
scrub that.  Both terms don't have the processing parent so to be on the safe side we should  do consider.

The consider term is
GO:0016485   protein processing

**Comment by Antonialock** [comment]
I have fixed the UniProt ones

**Comment by Antonialock** [comment]
and MTB

**Comment by Antonialock** [comment]
2 annotations are from NUNI - I am not responsible for those (NOt sure who is? @pgaudet ? )

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by pgaudet** [comment]
@Antonialock 

NUNI are the  **N**octua **UNI**prot annotations 

2 annotation by @sylvainpoux to 
- P53582 (http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A62900b6400001836)
and 
- http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A62900b6400001815
both should be change to 'protein maturation' 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi
@pgaudet and @Antonialock 

I will modify the GO-CAM models. By the way, I don't think it is a good idea to delete this BP term: many enzymes work in cooperation with regulatory subunits and we dom't always know the Molecular Function of these subunits /they can act as substrate adapter, activators, repressors etc). 

Form that point of view these BP annotations are extremely useful for non-catalytic subunits.

Sylvain

**Comment by ValWood** [comment]
Because initiator methionine removal is a single step you would have

P53582 GO:0004239 | initiator methionyl aminopeptidase activity
part_of protein maturation

Any regulatory subunit and  would be
GO:0061135   endopeptidase regulator activity  or adaptor (or just molecular function if this were not clear) , with input P53582 and part_of protein maturation
so the connection would be made in this way.

If it were a multi-step pathway, we would have a process term. This is part of a general effort to remove the single-step processes from the BP protein modification and RNA modification branches because this results in annotation inconsistency. Historically curators often annotated to the modification BP redundantly with the MF   (i.e. methylation, phosphorylation) and not to the actual biological process i.e chromatin remodelling or signalling).  
Protein maturation steps are a bit of an edge case though, maybe it is desirable to distinguish different maturations in the process ontology but it would be inconsistent with the way that other modifications are now handled.

**Comment by srengel** [comment]
(i fixed the SGD ones some time ago but forgot to post here.)  SGD done.

**Comment by pgaudet** [comment]
All done

**Comment by sylvainpoux** [comment]
Hi @Antonialock 
I changed these two annotations into protein maturation several months ago. In theory, the problem should not be present anymore
Could you let me know which annotation cause problem?
Thanks
Sylvain

**Comment by Antonialock** [comment]
oh apologies, wrong ticket! It's the one about NF-kappaB
