### ISSUE TITLE
Review annotations to GO:0060547 negative regulation of necrotic cell death GO:0010939 regulation of necrotic cell death GO:0010940 positive regulation of necrotic cell death

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4530]
Dear all, 

The proposal has been made to obsolete GO TERM ID: GO TERM
GO:0060547 negative regulation of necrotic cell death
GO:0010939 regulation of necrotic cell death
GO:0010940 positive regulation of necrotic cell death

see https://github.com/geneontology/go-ontology/issues/25218

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1lxhoxJpgiz5jVbSG4KY2l0urpsXocsGyr4hyktUP8Dc/edit#gid=0

Impacted groups: 
   2 ARUK-UCL
   2 AgBase
   2 BHF-UCL
   1 DFLAT
   4 FlyBase
   8 RGD
  10 UniProt
  19 WB
   1 dictyBase

Thanks.

**Comment by pfey03** [comment]
Done with the annotation

**Comment by RLovering** [comment]
UCL annotations done there were 4 mouse RNAs that were missed in the spreadsheet, I have added these IDs to the spreadsheet

**Comment by vanaukenk** [comment]
WB done.

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
