### ISSUE TITLE
IPR018200 NOT GO:0006511 | ubiquitin-dependent protein catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4534]
* **InterPro ID / label**

GO:0006511 | ubiquitin-dependent protein catabolic process | IEA with IPR018200

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

https://www.pombase.org/gene/SPAC13A11.04c
This deubiquitinase activity isn't part of a deradation pathway, it's main target is 
 mono-ubiquitylated H2B and the DUB during chromatin remodelling for transcription.

tks

**Comment by sarach06** [comment]
Hi Val,
Many thanks. I have removed the term from this entry. The changes will be available in InterPro 94.0.
Best wishes,
Sara
