### ISSUE TITLE
PTN002541993 not cysteine-type endopeptidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4535]
* **PTHR ID & PTN node:**

GO:0004197 | cysteine-type endopeptidase activity | IBA with MGI:2182061 , Q70CQ2 , Q86T82 , Q92995 , MGI:1888998 , PTN002541993 , O75317 , Q14694 , Q70CQ3 , MGI:894681 , Q93009

This annotation appears to be incorrect.
https://www.pombase.org/gene/SPAC13A11.04c

Ubp8 is a deubiqitinase.
Deubiquitinases don't cleave the peptide bond so they aren't endo-peptidases.

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

See:
https://github.com/geneontology/go-ontology/issues/25231

could be erroneous annotation, or propagation. I looked at the first one  MGI:2182061  and that appeared to be an annotation issue.
I would challenge them in Protein2GO, but I no longer have access, and I'm not sure if some are genuinely endopeptidases.

**Comment by deustp01** [comment]
Enzymology nomenclature / classification issue: doesn't the bond here involve the main-chain carboxyl group of one moiety and a lysine side chain amino group of the other, so the result is an isopeptide linkage, and its cleavage (probably?) proceeds by the same mechanisms as are used to cleave internal or terminal peptide bonds?

**Comment by deustp01** [comment]
It sounds like two aspects of chemistry collide here. One is how to categorize reactions that cause cleavage of peptide bonds. The other is how to categorize reactions that cause the various covalent modifications of histones. No good ideas from here about how best to referee the conflict between those two classification systems.

**Comment by marcfeuermann** [comment]
I've remove the annotation to  "cysteine-type endopeptidase activity". We have "cysteine-type deubiquitinase activity" annotation, which describes the right MF.
