### ISSUE TITLE
IPR002969 IPR026222 aging

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4536]
* **InterPro ID / label**
 IPR002969 IPR026222

* **Example sequences with problematic annotation (ID + gene/protein name):**

I noticed these mappings for obsolete term aging are still present in AmiGO.
https://www.ebi.ac.uk/QuickGO/term/GO:0007568
THis might be just a synchronization issue, or I could have forgottent to tag you in the original ticket?

**Comment by sarach06** [comment]
Hi Val,
I checked and this term is not linked to these InterPro entries, it may be a synchronization issue.
Best wishes,
Sara
