### ISSUE TITLE
Review annotations to GO:0090501 RNA phosphodiester bond hydrolysis and descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4544]
Dear all, 

The proposal has been made to obsolete GO TERM ID: GO TERM
GO:0090503 RNA phosphodiester bond hydrolysis, exonucleolytic
GO:0090501 RNA phosphodiester bond hydrolysis, endonucleolytic
GO:0098789	pre-mRNA cleavage required for polyadenylation
GO:0090501	RNA phosphodiester bond hydrolysis

see https://github.com/geneontology/go-ontology/issues/25259

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1a3Vl6CARGx7UbFGKneTs2m4XqPRAOS39tAq2X-_Zak8/edit#gid=0

Impacted groups: 
  1 BHF-UCL	GO:0090501	RNA phosphodiester bond hydrolysis
   2 BHF-UCL	GO:0090502	RNA phosphodiester bond hydrolysis, endonucleolytic
   4 BHF-UCL	GO:0090503	RNA phosphodiester bond hydrolysis, exonucleolytic
   7 ComplexPortal	GO:0098789	pre-mRNA cleavage required for polyadenylation
   2 EcoCyc	GO:0090501	RNA phosphodiester bond hydrolysis
   2 EcoCyc	GO:0090502	RNA phosphodiester bond hydrolysis, endonucleolytic
   3 FlyBase	GO:0090502	RNA phosphodiester bond hydrolysis, endonucleolytic
   2 FlyBase	GO:0090503	RNA phosphodiester bond hydrolysis, exonucleolytic
   4 GOC	GO:0090501	RNA phosphodiester bond hydrolysis
   1 GeneDB	GO:0098789	pre-mRNA cleavage required for polyadenylation
   2 HGNC	GO:0090503	RNA phosphodiester bond hydrolysis, exonucleolytic
   2 PseudoCAP	GO:0090503	RNA phosphodiester bond hydrolysis, exonucleolytic
  22 SGD	GO:0098789	pre-mRNA cleavage required for polyadenylation
  12 UniProt	GO:0090501	RNA phosphodiester bond hydrolysis
  13 UniProt	GO:0090502	RNA phosphodiester bond hydrolysis, endonucleolytic
  14 UniProt	GO:0090503	RNA phosphodiester bond hydrolysis, exonucleolytic
   7 UniProt	GO:0098789	pre-mRNA cleavage required for polyadenylation
   6 WB	GO:0090502	RNA phosphodiester bond hydrolysis, endonucleolytic

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

None

Thanks.

**Comment by ValWood** [comment]
@pgaudet

The behaviour of the spreadsheet generation was a bit unexpected (for me).

I have included 2 process terms, and I only expected to get "process" descendants. These terms have MF_BP links, so it also pulls in all of the MF annotations. In general, perhaps we only want to retrieve terms from the same ontology aspect?

**Comment by ValWood** [comment]
@sartweedie for HGNC!

**Comment by ValWood** [comment]
Please note that for these I can't easily suggest a  process term replacement , you will need to check to see which process (if any - this will likely already be annotated). 

Except for 
GO:0098789 pre-mRNA cleavage required for polyadenylation
which  if  co-annotated to
CC mRNA cleavage factor complex (GO:0005849) or one of its descendants, (or  be an associated protein)

can be moved to
GO:0180010   co-transcriptional mRNA 3'-end processing, cleavage and polyadenylation pathway
(this is a relatively new term, created  as part of the work to improve RNA processing and degradation pathways)

**Comment by vanaukenk** [comment]
WB done

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by sartweedie** [comment]
HGNC done

**Comment by srengel** [comment]
i still see annotations to this term in Protein2GO from Complex Portal.  @sandraorchard

**Comment by sandraorchard** [comment]
Waiting for a release for them to update - IntAct and Complex Portal have been victim of the EBI server migration but hopefully release will start next week.

**Comment by pgaudet** [comment]
>The behaviour of the spreadsheet generation was a bit unexpected (for me).

> I have included 2 process terms, and I only expected to get "process" descendants. These terms have MF_BP links, so it also pulls in all of the MF annotations. In general, perhaps we only want to retrieve terms from the same ontology aspect?

Good point, I dont remember running into this. @kltm I think the script is looking for 'part of' and 'regulates', is this right? 

(that being said, I am not sure why you added both labels, can both script run at once? anyway the 'regulates' also inclludes the direct annotations)

**Comment by kltm** [comment]
@pgaudet I'm assuming you're talking about the "regulation" report. That is using the "regulates_closure", as found in the regulates filter in AmiGO. Direct should be /anything/ directly annotated, no closure or relation involved. It seems both reports can be run at the same time, as it is looking at the label, but I guess one of them "wins".

**Comment by amandamackie** [comment]
EcoCyc done.
 
@ValWood, I am not able to open the spreadsheets that you attach listing the experimental annotations without first requesting access. Is there some way to rectify this? I've noticed that it doesn't happen with requests that @pgaudet sends ie. I can always open spreadsheets that Pascale has attached directly.

**Comment by pgaudet** [comment]
@ValWood I think I understand the issue you mentioned

> These terms have MF_BP links, so it also pulls in all of the MF annotations. 

In fact the 'GOC'- created ones are automated generated by F->P interontology links. This is not related to the query.

**Comment by ValWood** [comment]
Maybe we need to remove any F-P links in the ontology before we begin the obsoletion procedure?
 But it would be better if these were ignored (less work)

**Comment by pgaudet** [comment]
You can just ignore source = GOC

**Comment by pgaudet** [comment]
UniProt donce, except for PIR 

@Antonialock Can you fix these ? They only need to be deleted (redundant with MF)

**Comment by pgaudet** [comment]
@RLovering I just checked, all the ones you have are redundant with MFs and can be removed. There are other BPs.

**Comment by RLovering** [comment]
Thanks Pascale, I have deleted all of UCLs
Ruth

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
