### ISSUE TITLE
Make spreadsheets accessible

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4547]
EcoCyc done.
 
@ValWood, I am not able to open the spreadsheets that you attach listing the experimental annotations without first requesting access. Is there some way to rectify this? I've noticed that it doesn't happen with requests that @pgaudet sends ie. I can always open spreadsheets that Pascale has attached directly.

_Originally posted by @amandamackie in https://github.com/geneontology/go-annotation/issues/4544#issuecomment-1512228374_
            

@pgaudet, how do I resolve this?

**Comment by pgaudet** [comment]
Emailed Amanda
