### ISSUE TITLE
Review annotations to GO:0004143 diacylglycerol kinase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4549]
Hi @srengel 

Can you review the 2 EXP to GO:0004143 diacylglycerol kinase activity

https://docs.google.com/spreadsheets/d/1g9V_f-Mh1siAAr03O1C7zmZExQWlkmXhqySVhkdxpmA/edit#gid=0

These should be using the new term GO:0141035  CTP-dependent diacylglycerol kinase activity 
(just created today - you might need to wait a few days to be able to use it) 

Thanks, Pascale

**Comment by pgaudet** [comment]
[pthr31303](http://www.pantherdb.org/panther/lookupId.jsp?id=PTHR31303) also needs to be reviewed

**Comment by srengel** [comment]
SGD done.

**Comment by marcfeuermann** [comment]
Still waiting on the term to appear in PAINT.

**Comment by marcfeuermann** [comment]
Still not available for PAINTing.

**Comment by marcfeuermann** [comment]
Finally available for PAINTing. Done.
