### ISSUE TITLE
Review annotations to GO:0043631 RNA polyadenylation (remaining high level terms)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4553]
Dear all, 

The proposal has been made to obsolete 
GO:0043631   RNA polyadenylation
GO:0006378 mRNA polyadenylation
GO:1900364 negative regulation of mRNA polyadenylation
GO:1900365 positive regulation of mRNA polyadenylation
GO:1900363 regulation of mRNA polyadenylation
GO:0043629 ncRNA polyadenylation
~GO:0071050 sno(s)RNA polyadenylation~ I removed these, we can do a direct relace for this one so no reannotation required

see https://github.com/geneontology/go-ontology/issues/24924

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1Dyb4jkJAqnHonfWw2-9u3zQcpAcVd5cd9p_I7ta2Muc/edit#gid=0

Impacted groups: 
   2 CGD @marekskrzypek
   4 ComplexPortal @sandraorchard 
   2 EcoliWiki @amandamackie 
  29 FlyBase @hattrill  @gantonazzo 
  51 GeneDB @uliboehme
  13 MGI @LiNiMGI 
   3 RGD @slaulederkind 
 120 SGD @srengel 
  12 TAIR @tberardini 
  76 UniProt @Antonialock 
   7 WB @vanaukenk 
   6 ZFIN @sramachand

This is the last big ticket in this branch. 
Usually you will need the equivalent "3'end processing" term (if nuclear) or for mRNA "mRNA destabilization (if cytoplasmic). Sometimes it isn't known what the process is as there is only an MF assay.

Mappings that need to be reviewed: NONE

Thanks.

**Comment by amandamackie** [comment]
EcoCyc (Ecoliwiki) done

**Comment by slaulederkind** [comment]
RGD is finished.

**Comment by srengel** [comment]
SGD done.

**Comment by LiNiMGI** [comment]
@ValWood I only see 7 MGI annotations in the google spreadsheet, will check noctua when reviewing. thanks.

**Comment by LiNiMGI** [comment]
MGI done.
I also added some MGI annotations to the end of the google spreadsheet @ValWood (1 ISS, 1 IDA and 3 TAS) Thanks!

**Comment by pgaudet** [comment]
Terms are now obsolete.
Any remaining annotation will appear in error reports.
