### ISSUE TITLE
IPR036735 not "regulation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4555]
* **InterPro ID / label**

- | GO:0006355 | regulation of DNA-templated transcription | IEA with IPR036735 | GO_REF:0000002

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC23C4.19

* **Description of issue**

A better mapping would be
DNA-templated transcription elongation (GO:0006354)

**Comment by sarach06** [comment]
Hi Val,
Many thanks for this. I have updated the term as you suggested. It will be available in the next InterPro release.
Best wishes,
Sara
