### ISSUE TITLE
GO:0036369  transcription factor catabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4556]
Dear all, 

The proposal has been made to obsolete  GO:0036369 transcription factor catabolic process

This is not a specific pathway, to be replaced by the parent GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process

Ontology ticket: https://github.com/geneontology/go-ontology/issues/25300

Annotations by 	
PomBase, SGD, WB, BHF, CACAO

@ValWood @srengel @vanaukenk @RLovering 
OK with the obsoletion?

**Comment by ValWood** [comment]
Yes, PomBase done

**Comment by RLovering** [comment]
UCL done (found one more to do via QuickGO)

**Comment by pgaudet** [comment]
4 annotations left: 
- 2 WB
- 1 TAIR
- 1 CACAO
