### ISSUE TITLE
GO:0006400 | tRNA modification | IBA with MGI:2384560 , PTN000206950

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4557]
* **PTHR ID & PTN node:**

GO:0006400 | tRNA modification | IBA with MGI:2384560 , PTN000206950 | Gaudet P et al. (2011)

there are 3 MGI annotations to papers describing "editing activity". I don't think tRNA modification is the correct process for this, is it?

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC23C11.09

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous annotation, see above

**Comment by pgaudet** [comment]
Removed 'tRNA modification' and a few other annotations (binding).
