### ISSUE TITLE
Review annotations to GO:0050213 progesterone 5-alpha-reductase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4558]
Dear all, 

The proposal has been made to obsolete GO:0050213 'progesterone 5-alpha-reductase activity' and to replace it with GO:0047751 3-oxo-5alpha-steroid 4-dehydrogenase (NADP(+)) activity
see https://github.com/geneontology/go-ontology/issues/25314

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1NmR5w8GLodHdc_eBmGtNidpk_d6z0Q9SDrxLkCUJhrQ

Impacted groups: 
UniProt 3 EXP

----

Mappings that need to be reviewed: NONE

Thanks.

**Comment by Antonialock** [comment]
the UniProt ones are already updated.Message ID:
***@***.***>

>

**Comment by pgaudet** [comment]
Thanks!
