### ISSUE TITLE
IPR000120	amidase/ too granular

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#456]
i'm not sure that all these are clssed as amidases?

also present in 
glutamyl-tRNA(Gln) amidotransferase activity
which doesn't appear to be an amidase?

val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/456":https://sourceforge.net/p/geneontology/annotation-issues/456

**Comment by sjm41** [comment]
IPR000120 is currently mapped to 'hydrolase activity'.
But as pointed out above, and as mentioned in the IPR000120 description, this signature is also found in Subunit A of Glu-tRNA(Gln) amidotransferase, which equates to a ligase activity (glutaminyl-tRNA synthase (glutamine-hydrolyzing) activity).

So, I think the InterPro2GO mapping here has to go all the way up to 'catalytic activity'.

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have changed the term as you said. The changes will be seen in the next InterPro release (86.0).

Best,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
