### ISSUE TITLE
pombe clr6 not NuRD

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4570]
* **PTHR ID & PTN node:**

clr6 | GO:0016581 | NuRD complex | IBA with Q92769 , WBGene00001834 , Q13547 , PTN000743059 , MGI:108086 , FBgn0015805

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC36.05c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Propagation I suspect. In pombe the NURD-type complexes are SHREC and SHREC2, they contain 
clr3 https://www.pombase.org/gene/SPBC800.03 as their histone deacetylase.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Looks like the fungal complexes do not use the same deacetylase since clr6 is the closest to the "NURD" cluster and clr3 is in another location in the family. I've restricted the annotation.
