### ISSUE TITLE
Review annotations to GO:0016307 phosphatidylinositol phosphate kinase activity, GO:0052813 phosphatidylinositol bisphosphate kinase activity  and GO:0035004 phosphatidylinositol 3-kinase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4571]
Dear all, 

The proposal has been made to obsolete 

GO:0016307 phosphatidylinositol phosphate kinase activity >> 4 EXP (no EC/RHEA)
GO:0052813 phosphatidylinositol bisphosphate kinase activity >> 1 EXP (no EC/RHEA)
GO:0035004 phosphatidylinositol 3-kinase activity >> 5 EXP (no EC/RHEA)

(Unnecessary grouping classes) 

see https://github.com/geneontology/go-ontology/issues/18016

**Comment by pgaudet** [comment]
Review spreadsheet: see
see https://docs.google.com/spreadsheets/d/1r7TotHEmXHQhsHMrZ6w0sjVL1gRQyzJ-G3dFVWr6Jh4/edit#gid=0

REPLACEMENTS: 
* GO:0035004 phosphatidylinositol 3-kinase activity will be replaced by GO:0016303  1-phosphatidylinositol-3-kinase activity (same meaning)l
* GO:0052813 and GO:0016307 will be replaced by the new parent, GO:0052742 phosphatidylinositol kinase activity

Therefore, if your group uses automated replacement of obsolete terms, no action is required. 

Impacted groups: 

Group | Number of annotations 
-- | --
GeneDB | 1
TAIR | 2
dictyBase | 1
BHF-UCL | 1
FlyBase | 2
RGD | 1
SGD | 1
ZFIN | 1


Mappings: 
6 InterPro mappings, 5 Reacome and 1 UniRule

Thanks, Pascale

**Comment by sjm41** [comment]
FlyBase done.

**Comment by deustp01** [comment]
Reactome done (though there may be a delay in propagating changes to public view)

**Comment by sramachand** [comment]
ZFIN done

**Comment by pgaudet** [comment]
Terms are now obsoleted. Remaining annotations appear in error reports.
