### ISSUE TITLE
Review annotations to terms with partial EC:1.1.1.-

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4578]
- [x] 3-ketodihydrosphinganine   (C18) reductase activity GO:0102282
- [x] 3beta-hydroxysteroid   dehydrogenase activity GO:0102727 
- [x] 4-hydroxy-L-isoleucine   dehydrogenase activity GO:0102394
- [x] 4alpha-carboxy,4beta,14alpha-dimethyl-9beta,19-cyclo-5alpha-cholest-24-en-3beta-ol   dehydrogenase/C4-decarboxylase activity GO:0102187
- [x] 4alpha-carboxy-stigmasta-7,24(241)-dien-3beta-ol   dehydrogenase/C4-decarboxylase activity GO:0102182
- [x] L-glyceraldehyde 3-phosphate   reductase activity GO:0103037 
- [x] UDP-3-dehydro-alpha-D-glucose   dehydrogenase activity GO:0102982 
- [x] alpha-ketoglutarate reductase   activity (NADH-dependent) GO:0102909
- [x] avenastenone reductase   activity GO:0102183
- [ ] beta-keto ester reductase   activity GO:0103014
- [x] choline monooxygenase activity   (NADP-dependent) GO:0102280
- [x] dTDP-4-oxo-2,6-dideoxy-D-glucose   4-ketoreductase (dTDP-D-oliose producing) activity GO:0102309
- [x] ethylglyoxal reductase (NADH-dependent,   hydroxyacetone-forming) activity GO:0103030
- [x] gamma-hydroxybutyrate dehydrogenase   activity (NAD(P)-dependent GO:0102722
- [x] hentriaconta-3,6,9,12,19,22,25,28-octaene-16-one-15-oyl-CoA   reductase activity GO:0102329
- [x] isobutyraldehyde reductase activity   GO:0103050
- [x] methylglyoxal reductase (NADPH-dependent,   acetol producing) GO:1990002
- [x] methylthioalkylmalate dehydrogenase   activity GO:0103093
- [x] methylthiobutylmalate dehydrogenase   activity GO:0103084
- [x] methylthiohexylmalate dehydrogenase   activity GO:0103090
- [x] methylthiopentylmalate dehydrogenase   activity GO:0103087
- [x] methylthiopropylmalate dehydrogenase   activity GO:0103081
- [x] mithramycin dehydrogenase activity   GO:0102357
- [x] oryzalexin A synthase activity GO:0102616
- [x] oryzalexin B synthase activity GO:0102618
- [x] oryzalexin C synthase (oryzalexin A   dependent) activity GO:0102619
- [x] oryzalexin C synthase (oryzalexin B   dependent) activity GO:0102617
- [x] phenylacetaldehyde reductase activity   GO:0102386 
- [x] tartronate semialdehyde reductase   activity GO:0103032

(oxidoreductase activity, acting on the   CH-OH group of donors, NAD or NADP as acceptor GO:0016616 >> OK, parent class)

**Comment by deustp01** [comment]
@pgaudet what is the requested action here? E.g., are these potential candidates for obsoletion or merger, or items affected by a possible reorganization of ontology structure? Something else? If the answer is complex, this might be an item for the ontology call today?
Thanks
