### ISSUE TITLE
Review annotations to GO:0043551 regulation of phosphatidylinositol 3-kinase activity  & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4579]
Dear all, 

The proposal has been made to obsolete GO:0043551 regulation of phosphatidylinositol 3-kinase activity
see https://github.com/geneontology/go-ontology/issues/25383

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1-vbq_K-W0YBG_q0lrLKINfDvpcOS5gLKLIq96tttqTo/edit#gid=0

Impacted groups: 

assigned   by |  
-- | --
BHF-UCL | 14
DFLAT | 1
GeneDB | 1
MGI | 7
RGD | 3
UniProt | 38

----

Mappings that need to be reviewed:
 InterPro:IPR039724 WD repeat-containing protein 91 > GO:regulation of phosphatidylinositol 3-kinase activity ; GO:0043551

Thanks.

**Comment by gthayman** [comment]
RGD done.

**Comment by LiNiMGI** [comment]
MGI done

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
I dont think the InterPro was addressed - IPR039724
@blazaropinto @sarach06

**Comment by blazaropinto** [comment]
Thank you for this, I replaced this GO term for [GO:0035014](https://www.ebi.ac.uk/QuickGO/term/GO:0035014). The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by pgaudet** [comment]
@blazaropinto @sarach06 
I suggest you change the annotation of IPR039724 to 
- GO:0141039 phosphatidylinositol 3-kinase inhibitor activity and 
- GO:0051898 'negative regulation of phosphatidylinositol 3-kinase/protein kinase B signal transduction'
Thanks, Pascale

**Comment by sarach06** [comment]
Dear Pascale,
My apologies for not being to this before, we've just missed it. Many thanks for your suggestion, I have changed the annotation of IPR039724 to GO:0141039 phosphatidylinositol 3-kinase inhibitor activity and GO:0051898 'negative regulation of phosphatidylinositol 3-kinase/protein kinase B signal transduction'. These changes will be visible in InterPro 97.0.
Best regards,
Sara
