### ISSUE TITLE
Review annotations to GO:0030579 ubiquitin-dependent SMAD protein catabolic process

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4581]
Dear all, 

The proposal has been made to obsolete GO:0030579 ubiquitin-dependent SMAD protein catabolic process
see https://github.com/geneontology/go-ontology/issues/25299

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1uaSaQEeOQhd-oAbdWp5MHEIo53-28g8haVs64TnG_0Q

Impacted groups: 
MGI 2 EXP
UCL 6 EXP

----

Mappings that need to be reviewed: none

Thanks.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by pgaudet** [comment]
Wonderful !
