### ISSUE TITLE
GO:0046929 in non-eukaryotes

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-annotation#4582]
Hi,
We've received a Report on taxon constraint violations for this term:
Andrea Auchincloss                 GO:0001505 only_in_taxon Eumetazoa                protein     P18640                   GO:0046929 negative regulation of neurotransmitt...ECO:0000314 (IDA) PMID:7901002   12336    Clostridium botulinum C phage
Botox is a protein that can be encoded in a bacterium or virus which affects the eukaryotic host by inhibiting neurotransmitter release. I don't think the constraint on the term is correct.
-Andrea

**Comment by deustp01** [comment]
The definition of BP term GO:0001505 "regulation of neurotransmitter levels" is "Any process that modulates levels of neurotransmitter."  It looks like the process occurs in the organism that makes the neurotransmitter, regardless of the source of the entity that is doing the regulating. So if only eumetazoa have neurotransmitters, the restriction seems right.

An analogous restriction exists for GO:0061772 "xenobiotic transport across blood-nerve barrier", which can only be applied to vetrebrates, the locus of the blood-nerve barrier, reardless of the source of the xenobiotic entity.

**Comment by ValWood** [comment]
closing
