### ISSUE TITLE
Simple reports: please query extensions for obsolete terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4585]
We need to know whether terms to be obsoleted are also present in other column of the GAF file: 
- extensions (col 16 of GAF) 
- With (or) From (col 8 of GAF)
These could be grouped together in a 3rd report called 'extensions_with:GO#####'. 

Thanks, Pascale

**Comment by kltm** [comment]
Fields are indeed in GOlr with `evidence_with` and `annotation_extension_class`.

**Comment by kltm** [comment]
@pgaudet If you don't mind it being split into two files, I have something in place for you. Output here:
https://github.com/geneontology/go-annotation/issues/4589

I'm not 100% the new files are catching; it would be best to test on known examples.

**Comment by pgaudet** [comment]
Yes, it's working, see https://github.com/geneontology/go-annotation/blob/master/reports/4590/extensions_GO_0065003.tsv

 Thanks @kltm !!!

**Comment by kltm** [comment]
Running into issues with new script.
Errors like:
```
Run mkdir -p reports/$NUMBER && python3 ./scripts/annotation-review-report.py geneontology/go-annotation 7 --number $NUMBER --label direct_ann_to_list_of_terms --field evidence_with --output ./reports/$NUMBER --prefix ev_with --verbose
INFO:annotation-review-report:Verbose: on
INFO:annotation-review-report:Will output to: ./reports/4593
INFO:annotation-review-report:Prefix: ev_with_
INFO:annotation-review-report:Will filter for issue: 4593
INFO:annotation-review-report:Will filter for issue label: direct_ann_to_list_of_terms
INFO:annotation-review-report:Will filter for field: evidence_with
ERROR:annotation-review-report:no terms found in 
Error: Process completed with exit code 1.
```
https://github.com/geneontology/go-annotation/actions/runs/5083751583/jobs/9135139528#step:6:14
See
https://github.com/geneontology/go-annotation/issues/4593

**Comment by kltm** [comment]
@pgaudet I believe that this should be working now. It was a typo in the "regulates" version of the query.

**Comment by kltm** [comment]
@pgaudet Apologies for the trouble; you can close your last tickets and retry them.
