### ISSUE TITLE
Review annotations to GO:1901044 protein polyubiquitination involved in nucleus-associated proteasomal ubiquitin-dependent protein catabolic process

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4586]
Dear all, 

The proposal has been made to obsolete GO:1901044 protein polyubiquitination involved in nucleus-associated proteasomal ubiquitin-dependent protein catabolic process
see https://github.com/geneontology/go-ontology/issues/25298

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1ObHRmfLnBZz3nlgYHmEOepQnL0-RecCj2djGgJHDLUE

Impacted groups: 
Flybase 2 IDA

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by hattrill** [comment]
FB has fixed these.
