### ISSUE TITLE
Review annotations to GO:0070928 regulation of mRNA stability, ncRNA-mediated 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4587]
Dear all, 

The proposal has been made to obsolete GO:0070928 regulation of mRNA stability, ncRNA-mediated , see 
https://github.com/geneontology/go-ontology/issues/25425

**Comment by pgaudet** [comment]
1 RFAM mapping to Rfam:RF03533 - suggest to replace by [GO:0035194 ncRNA-mediated post-transcriptional gene silencing](http://amigo.geneontology.org/amigo/term/GO:0035194#display-lineage-tab)

@kalvari
 @AntonPetrov

**Comment by AntonPetrovLTX** [comment]
@pgaudet Thank you for raising this issue! As I am no longer at EBI after completing my 9 years, for cases like this I suggest tagging @blakesweeney, the current @Rfam tzar.

**Comment by AntonPetrov** [comment]
@pgaudet Thank you for raising this issue! As I am no longer at EBI after completing my 9 years, for cases like this I suggest tagging @blakesweeney, the current https://github.com/Rfam tzar.

**Comment by AntonPetrov** [comment]
Yes, that's right

**Comment by blakesweeney** [comment]
Hi, we'll take care of this shortly. Thanks for letting us know!

**Comment by blakesweeney** [comment]
I have made this change on our preview site. It will be public once we release.
