### ISSUE TITLE
Review annotations to GO:0016570 histone modification 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4595]
GO:0016570 histone modification 

rerun for https://github.com/geneontology/go-ontology/issues/24294

**Comment by pgaudet** [comment]
This replaces the other ticket: https://github.com/geneontology/go-annotation/issues/4261


I added a spreadsheet to the annotation report


Here's how many annotations are left by group: 

Group | Count
-- | --
ARUK-UCL+BHF | 72
AgBase | 2
AspGD | 15
BHF-UCL | 71
CACAO | 3
CGD | 7
ComplexPortal | 289 - done, just not updated
DisProt | 1
FlyBase | 2
GOC | 4
GO_Central | 6
GR | 1
GeneDB | 23
HGNC | 3
HGNC-UCL | 2
MGI | 34
RGD | 28
SGD | 1
UniProt | 42
WB | 37
ZFIN | 28

**Comment by pgaudet** [comment]
Mappings to correct: 

InterPro:IPR007133 RNA polymerase II associated factor Paf1 > GO:histone modification ; GO:0016570
InterPro:IPR007149 Leo1-like protein > GO:histone modification ; GO:0016570
InterPro:IPR007852 Cdc73/Parafibromin > GO:histone modification ; GO:0016570
InterPro:IPR031101 RNA polymerase-associated protein Ctr9 > GO:histone modification ; GO:0016570
InterPro:IPR030849 Ubiquitin carboxyl-terminal hydrolase 16 > GO:histone deubiquitination ; GO:0016578
HAMAP:MF_03046 > GO:histone deubiquitination ; GO:0016578
HAMAP:MF_03047 > GO:histone deubiquitination ; GO:0016578
HAMAP:MF_03062 > GO:histone deubiquitination ; GO:0016578
UniRule:UR000112776 > GO:histone deubiquitination ; GO:0016578
UniRule:UR000160894 > GO:histone deubiquitination ; GO:0016578
UniRule:UR000161210 > GO:histone deubiquitination ; GO:0016578

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
UniProt done

**Comment by pgaudet** [comment]
@LiNiMGI @gthayman Do you need more time to fix your annotations?

**Comment by LiNiMGI** [comment]
@pgaudet At MGI, we only got time to review most of the MGI annotations from the “623 enzymes” worksheet, we didn’t get chance to look at this new list you generated 2023-05-26 yet. Yes, MGI will need more time, thanks!

**Comment by gthayman** [comment]
Yes.

**Comment by hattrill** [comment]
fb done

**Comment by pgaudet** [comment]
Here's what's left: https://docs.google.com/spreadsheets/d/1LJTu3sZjwH7u3sD65KXf_e-l3A85cRKpeiYh2DVsRgg/edit#gid=669690606

MGI 33
RGD 25
WB 37

Thanks, Pascale

**Comment by gthayman** [comment]
RGD done.

**Comment by sramachand** [comment]
ZFIN done

**Comment by ValWood** [comment]
AN update
<img width="305" alt="Screenshot 2023-08-29 at 19 01 28" src="https://github.com/geneontology/go-annotation/assets/7359272/c215e225-f908-4f83-bea0-509880b7565c">

**Comment by uliboehme** [comment]
GeneDB (VEuPathDB) is done.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by pgaudet** [comment]
Terms are now obsoleted; any remaining annotations will appear in error reports.
