### ISSUE TITLE
Review plant annotations to GO:0006349 regulation of gene expression by genomic imprinting -in plants

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4596]
See explanation here: https://github.com/geneontology/go-ontology/issues/25455

Annotations are here
https://docs.google.com/spreadsheets/d/1_UNkbERVawN324c8AExXcoCvjP1pkPePmTaV66CLmw8/edit#gid=0

@colinlog and I suggest that these can pretty much all move to the new term  GO:0141044  epigenetic programming in the endosperm

**Comment by lreiser** [comment]
this is finally done!

**Comment by pgaudet** [comment]
Thanks !
