### ISSUE TITLE
Review annotations to GO:0016971 flavin-linked sulfhydryl oxidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4600]
GO:0016971 flavin-linked sulfhydryl oxidase activity
see https://github.com/geneontology/go-ontology/issues/25461

**Comment by suzialeksander** [comment]
Is this ticket still valid @pgaudet? It looks like the term was modified but not obsoleted

**Comment by pgaudet** [comment]
Right, that was just for checking. Thank you!
