### ISSUE TITLE
Blocks to FBgn0038630 CG14305/Tssk

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4602]
FBgn0038630 (CG14305/Tssk) is a testis-specific Ser/Thr kinase, PMID:37149634.

Could you block the progation of these BPs
SERINE/THREONINE KINASE (PTHR24343)
PANTHER:PTN001217363
GO:0032007	
negative regulation of TOR signaling

GO:0042149	
cellular response to glucose starvation

GO:0031588	
nucleotide-activated protein kinase complex

and this CC:
PANTHER:PTN000678822
SERINE/THREONINE KINASE (PTHR24343)
GO:0035556	
intracellular signal transduction

Think these come from the membership to the Calcium/Calmodulin-dependent kinase family (which are not all reg'd by Ca/Calm).

Looking at this paper PMID:37149634, where some human orthologs can functional substitute and looking at some of the mouse orthologs on the Alliance page https://www.alliancegenome.org/gene/FB:FBgn0038630#function---go-annotations perhaps "spermatogenesis" may be a common annotation for some Tssk's.

**Comment by marcfeuermann** [comment]
Huge kinase family. I've restricted the annotation of the corresponding terms.
