### ISSUE TITLE
Change obsolete AE CL ID 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#4603]
Hi Alex

would it be possible to change all the CL:0002609 obsolete neuron of cerebral cortex IDs in over 600 AEs 
https://www.ebi.ac.uk/QuickGO/annotations?extension=CL:0002609

to CL:0010012 cerebral cortex neuron

Very annoying that CL didn't just merge these 2 terms

I am assuming that RGD, UniProt, SynGO, CAFA and SYSCILIA_CCNET will not object to this change

Best

Ruth

**Comment by alexsign** [comment]
@RLovering Hi Ruth, I updated CL:0002609 to CL:0010012 in Protein2GO for "Internal" groups. This change should appear in the QuickGO after next public release in mid July.

**Comment by RLovering** [comment]
wonderful thank you so much
Ruth
