### ISSUE TITLE
gpad/gpi 2.0 specs: Allowed Gene Product to GO Term Relations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4604]
We should reformulate the 'Allowed Gene Product to GO Term Relations' to reference the RO subset 'valid_for_go_gp2term', to make sure the 'source of truth' is not in two places.

**Comment by kltm** [comment]
Spec finalized: moving on. Add to docs, not part of spec.

**Comment by kltm** [comment]
Moved to better home.
