### ISSUE TITLE
Review annotations to GO:0019787 ubiquitin-like protein transferase activity and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4607]
GO:0019787 ubiquitin-like protein transferase activity
GO:0019777 Atg12 transferase activity
GO:0019775 FAT10 transferase activity
GO:0042296 ISG15 transferase activity
GO:0019788 NEDD8 transferase activity
GO:0072496 Pup transferase activity
GO:0019789 SUMO transferase activity
GO:0004842 ubiquitin-protein transferase activity
GO:0071568 UFM1 transferase activity
GO:0042294 URM1 transferase activity

**Comment by ValWood** [comment]
Hi @pgaudet  what is the review for? @ukemi  reviewed this branch in detail a couple of years back, I think it works well. 

I would hate to lose the specificity we have been able to annotate here:
https://www.pombase.org/term/GO:0019787
It's really useful to see at a glance what the ubiquitin-like substrate is, and increasingly  for people who are trying to  identify missing E3 ligases in pathways , users really need to be able to retrieve only ubiquitin transferases, NEDD8 transferases etc

This is a slightly special case because it isn't capturing the substrate but the type of ubiquitin **moiety being transferred** (it's more like a modification)

**Comment by ValWood** [comment]
So for example


rfp1 SUMO-ubiquitin ligase activity  sumoylates top2
dma1 ubiquitin protein ligase activity ubiquitinates sid4

**Comment by ValWood** [comment]
I probably didn't explain that very well, but these terms are capturing the type **ubiquitin-type protein being transferred** (i.e. used as a protein modification), the  actual substrate is captured by a has_input extension.

**Comment by sjm41** [comment]
@ValWood @deustp01 

The proposal here is only to obsolete the 'UBL transferase activity' grouping terms.  All of these grouping terms have specific 'UBL conjugating enzyme activity' (ie. E2) and 'UBL ligase activity (ie. E3) terms, and these are not proposed for deletion.  For example:
```
       |_ubiquitin-like protein transferase activity (GO:0019787)
            |_ubiquitin-protein transferase activity (GO:0004842)
                |_ubiquitin conjugating enzyme activity (GO:0061631)
                |_ubiquitin protein ligase activity (GO:0061630)
            |_SUMO transferase activity (GO:0019789)
                |_SUMO conjugating enzyme activity (GO:0061656)
                |_SUMO ligase activity (GO:0061665)
            |_UFM1 transferase activity (GO:0071568)
                |_UFM1 conjugating enzyme activity (GO:0061657)
                |_UFM1 ligase activity (GO:0061666)
            |_NEDD8 transferase activity (GO:0019788)
                |_NEDD8 conjugating enzyme activity (GO:0061654)
                |_NEDD8 ligase activity (GO:0061663)
            |_Atg12 transferase activity (GO:0019777)
                |_Atg12 conjugating enzyme activity (GO:0061651)
                |_Atg12 ligase activity (GO:0061660)
```

Question is whether any of the current annotations made direct to a 'UBL transferase activity' grouping term cannot be made to a more specific E2/E3 term?

**Comment by ValWood** [comment]
What is the rationale for removing the grouping terms, just so I understand?

**Comment by suzialeksander** [comment]
@pgaudet is this still valid?

**Comment by pgaudet** [comment]
Looks like this was done: 

<img width="319" alt="image" src="https://github.com/user-attachments/assets/b4281c84-fce7-4ac3-9525-86b7da6b0e93">
