### ISSUE TITLE
Review annotations to GO:0070191 methionine-R-sulfoxide reductase activity (merge)

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4608]
Dear all, 

The proposal has been made to obsolete GO:0070191 methionine-R-sulfoxide reductase activity.
see https://github.com/geneontology/go-ontology/issues/25460

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1JiCmj9MbCMnffHxUJcJJx8sd9omvAcYPT_hc1vLBUrY/edit#gid=0

Impacted groups: 
SGD 1
UniProt 1
MGI 1

----

Mappings that need to be reviewed: none

Thanks.

**Comment by Antonialock** [comment]
I'm looking at the UniProt annotation. 

It is suggested the protein is moved to
L-methionine-(R)-S-oxide reductase activity

I see that there is also the GO term
peptide-methionine (R)-S-oxide reductase activity

In the paper the authors say:

"In summary, we demonstrated that (i) MsrB3 expression enhances tolerance to oxidative stress; (ii) MsrB3 expression is induced during the cold acclimation process; (iii) MsrB3 expression during cold acclimation enhances freezing tolerance in plants; (iv) increased MetO and ROS content in response to low temperature is inhibited by expression of MsrB3; (v) MsrB3 is localized at the ER; and (vi) a majority of the proteins that are regulated by low temperature in an MsrB3-dependent manner localize to the chloroplast. These observations suggest that MsrB3 enhances tolerance to cold stress by **repairing oxidized proteins** that accumulate in the presence of the ROS elicited in low temperature conditions"

The suggested GO term does not look correct based on what the authors infer (though it does look somewhat speculative)?
I'm not sure whether to annotate to the sibling term "peptide-methionine (R)-S-oxide reductase activity" based on author "inference"? or remove the anntoation, or up one level?

feedback appreciated

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
@Antonialock I agree, the paper does not assay the enzymatic activity. I deleted the annotation. 

Thanks, Pascale
