### ISSUE TITLE
Check direct annotations to GO:0032989 cellular component morphogenesis & some general children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4609]
GO:0032989 cellular component morphogenesis
GO:0032990 cell part morphogenesis (NOW OBSOLETE)
GO:0010927 cellular component assembly involved in morphogenesis

**Comment by pfey03** [comment]
@pgaudet we have 10 EXP annotations to GO:0042244 spore wall assembly. I guess this stays.

**Comment by pgaudet** [comment]
Sure - this was about **direct** annotations. Also, we're not asking anything from contributing groups (yet ;)

**Comment by suzialeksander** [comment]
@pgaudet any action needed here?

**Comment by pgaudet** [comment]
It was for this ticket: https://github.com/geneontology/go-ontology/issues/25496

No action needed.
