### ISSUE TITLE
Q96JS3 · PGBD1_HUMAN - probably dbTF not scavenger receptor

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-annotation#4610]
* **InterPro ID / label** SRCR domain IPR001190

* **Example sequences with problematic annotation (ID + gene/protein name):**
* Q96JS3 · PGBD1_HUMAN  
* this protein has several domains:
* [IPR029526](https://www.ebi.ac.uk/interpro/entry/IPR029526)
PGBD
[IPR003309](https://www.ebi.ac.uk/interpro/entry/IPR003309)
SCAN_dom
[IPR038269](https://www.ebi.ac.uk/interpro/entry/IPR038269)
SCAN_sf
[IPR001190](https://www.ebi.ac.uk/interpro/entry/IPR001190)
SRCR

* **Description of issue**

The SCAN domain of PGBD1 suggests it maybe a dbTF. In addition an otholog of this protein binds specific DNA sequence and the protein has been identified as binding many other dbTFs. see https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q96JS3
please consider removing this protein from this InterPro record - or editing it so that it does not have the GO scavenger receptor activity term associated with it

Thanks

Ruth

**Comment by sarach06** [comment]
Dear Ruth,
Thank you very much for this. I have removed the term from IPR001190 to stop this wrong propagation. This will be visible in the next InterPro release (95.0).
Best wishes,
Sara

**Comment by RLovering** [comment]
Hi Sara

thank you so much for addressing this so quickly

Nice to finally meet you in April

All the Best

Ruth
