### ISSUE TITLE
Check annotations to GO:0060395 SMAD protein signal transduction & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4611]
GO:0060395 SMAD protein signal transduction

**Comment by pgaudet** [comment]
Hi, 

For the work on signaling cassettes, we'd like to check annotations to the SMAD signaling pathway and its regulation, to make sure annotations are correct

@hattrill is there a document with guidelines already available? 

Annotations are here: 
https://docs.google.com/spreadsheets/d/1lxa0oX-ZKImCa-MeWJxS9nirUxeoFfWPX9XNyFcxrwE/edit#gid=0


Thanks, Pascale

**Comment by pgaudet** [comment]
Contributor | Number of annotations
-- | --
UCL | 50
FlyBase | 10
GO_Central | 1
MGI | 42
UniProt | 30
Xenbase | 1

**Comment by pgaudet** [comment]
To be discussed at an annotation call

**Comment by RLovering** [comment]
UCL annotations checked and changed where required

**Comment by pgaudet** [comment]
Left to check

Assigned_by |Count 
-- | --
FlyBase | 3
GO_Central | 1
MGI | 41
UniProt | 28
Xenbase | 1

**Comment by hattrill** [comment]
FB done

**Comment by hattrill** [comment]
Hi @pgaudet - sorry, I just notice the comment about documentation. I will start one which can accommodate the cassettes as we do them.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by pgaudet** [comment]
@malcolmfisher103 can you please look at the XenBase annotation?

**Comment by malcolmfisher103** [comment]
@pgaudet Hi Pascale, I think this was done some time ago but not marked up in the spreadsheet sorry about that.

**Comment by pgaudet** [comment]
AI Pascale to check the remaining UniProt annotations

**Comment by pgaudet** [comment]
UniProt done. 

thanks for the ping @suzialeksander
