### ISSUE TITLE
Check annotations to SMAD protein phosphorylation terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4612]
GO:0007182 common-partner SMAD protein phosphorylation - 7 EXP
GO:0060389 pathway-restricted SMAD protein phosphorylation  - 43 EXP
GO:0060393 regulation of pathway-restricted SMAD protein phosphorylation - 4 EXP
GO:0060394 negative regulation of pathway-restricted SMAD protein phosphorylation - 20 EXP
GO:0010862 positive regulation of pathway-restricted SMAD protein phosphorylation - 66 EXP

For signaling cassettes work 
@hattrill @RLovering @gantonazzo

**Comment by pgaudet** [comment]
Annotations are here: 

https://docs.google.com/spreadsheets/d/1GVO0oroN6esu1RoNFGqA3j0BwlV3inq9wVDLM-D8dqk/edit#gid=0

**Comment by pgaudet** [comment]
Annotations could perhaps be moved to one of these terms
- GO:0060395 SMAD protein signal transduction
-   [regulates relation] [GO:0060390 regulation of SMAD protein signal transduction](http://amigo.geneontology.org/amigo/term/GO:0060390#display-lineage-tab)
- [negatively_regulates relation] [GO:0060392 negative regulation of SMAD protein signal transduction](http://amigo.geneontology.org/amigo/term/GO:0060392#display-lineage-tab)
-  [positively_regulates relation] [GO:0060391 positive regulation of SMAD protein signal transduction](http://amigo.geneontology.org/amigo/term/GO:0060391#display-lineage-tab)
- GO:0007179 transforming growth factor beta receptor signaling pathway or regulation 
- GO:0032924 activin receptor signaling pathway or regulation 
- GO:0030509 BMP signaling pathway  or regulation 
Thanks, Pascale

**Comment by pgaudet** [comment]
Group | Number of annotations
-- | --
ARUK-UCL | 2
BHF-UCL | 81
ComplexPortal | 6
FlyBase | 3
MGI | 4
RGD | 2
UniProt | 26
Xenbase | 1
ZFIN | 15

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by hattrill** [comment]
FB done

**Comment by sramachand** [comment]
ZFIN done

**Comment by Antonialock** [comment]
Uniprot done

**Comment by gthayman** [comment]
RGD done.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by malcolmfisher103** [comment]
Xenbase done.

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
Thanks everyone!
