### ISSUE TITLE
PTN001000243 not | succinate dehydrogenase (ubiquinone) activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4618]
* **PTHR ID & PTN node:**

GO:0008177 | succinate dehydrogenase (ubiquinone) activity | IBA with PTN001000243 , S000004154 , S000002585

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBP23A10.16

This appears to be a membrane adaptor, not catalytic subunit
In pombe, this particular adaptor is for both 
TIM22 mitochondrial import inner membrane insertion complex](https://www.pombase.org/term/GO:0042721)
and succinate dehydrogenase (S. cerevisiae has 2  paralogs with split function)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation and propagation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Yes indeed. A good thing is that finally adaptor activities get annotated. For non-enzyme MFs we have mostly binding activities. Hope this will change.
