### ISSUE TITLE
Review annotations to transforming growth factor beta receptor signaling pathway involved  in x 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4620]
GO:0003302 transforming growth factor beta receptor signaling pathway involved in heart jogging 0 annotations
GO:0035463 transforming growth factor beta receptor signaling pathway involved in determination of left/right asymmetry
GO:0035464 regulation of transforming growth factor receptor beta signaling pathway involved in determination of left/right asymmetry 0 annotations
GO:0060797 transforming growth factor beta receptor signaling pathway involved in primary germ layer cell fate commitment
GO:0060798 transforming growth factor beta receptor signaling pathway involved in mesodermal cell fate specification
GO:0060799 transforming growth factor beta receptor signaling pathway involved in endodermal cell fate specification
GO:0060822 transforming growth factor beta receptor signaling pathway involved in axial mesodermal cell fate specification
GO:0060826 transforming growth factor beta receptor signaling pathway involved in neural plate anterior/posterior pattern formation
GO:0060835 transforming growth factor receptor beta signaling pathway involved in oral/aboral axis specification
GO:0090010 transforming growth factor beta receptor signaling pathway involved in primitive streak formation
GO:0090012 negative regulation of transforming growth factor beta receptor signaling pathway involved in primitive streak formation 0 annotations
GO:0090013 regulation of transforming growth factor beta receptor signaling pathway involved in primitive streak formation 0 annotations
GO:1901048 transforming growth factor beta receptor signaling pathway involved in regulation of multicellular organism growth
GO:1905313 transforming growth factor beta receptor signaling pathway involved in heart development

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/16ar2ohGBGZDsZ7K0Fg9_EtDsYZ2HL_euzbQEWVJNL8Y/edit#gid=0

There are 26 annotations to these terms:
* BHF: 1
* FlyBase: 4
* MGI: 1
* ZFIN: 20
 
These terms have not been used for annotation extensions.
There are no mappings to these terms; these terms are not present in any subsets.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
Terms are now obsoleted, see https://github.com/geneontology/go-ontology/issues/25534
Remaining annotations appear in error reports.

**Comment by sramachand** [comment]
ZFIN done

**Comment by pgaudet** [comment]
All done
