### ISSUE TITLE
Review annotations to GO:0036363  transforming growth factor beta activation  & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4623]
GO:0036363  transforming growth factor beta activation  & regulation children

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by suzialeksander** [comment]
UniProt and AgBase left. @jinhuiz @Antonialock

**Comment by Antonialock** [comment]
@suzialeksander is there a spreadsheet?
thanks

**Comment by Antonialock** [comment]
And some more background of what needs to happen? cheers

**Comment by pgaudet** [comment]
Out of date, I'll re-run 

@Antonialock we plan to obsolete all regulation of MF terms, and replace them either by 'x regulator activity' or maybe in this case, regulation of the TGF pathway.
