### ISSUE TITLE
Review annotations to activin receptor signaling pathway involved in x

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4624]
GO:0038103 activin receptor antagonist activity involved in negative regulation of nodal signaling pathway
GO:0061372 activin receptor signaling pathway involved in heart jogging'

**Comment by pgaudet** [comment]
Since IC annotation by ZFIN: 
ZFIN:ZDB-GENE-040421-2	DAN domain family, member 5		GO:0061372		ZFIN	NCBITaxon:7955	IC	GO:0032926	PANTHER:PTHR15273		PMID:15084459	20101104

**Comment by sramachand** [comment]
ZFIN done
