### ISSUE TITLE
problem with PAINT family, or annotation transfer or both PANTHER:PTN000331677

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4625]
* **PTHR ID & PTN node:**

see
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P0AEH3

This is transferring

GO:0004343    glucosamine 6-phosphate N-acetyltransferase activity
GO:0006048    UDP-N-acetylglucosamine biosynthetic process
GO:0005793    endoplasmic reticulum-Golgi intermediate compartment

from eukaryotes to bacteria

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
I had a look but I could not immediately find any information about the specificity of this acetyltransferase in bacteria.

CC @sarach06

**Comment by ValWood** [comment]
In case this is helpful, there are two pombe members of this family, one is close to the eukaryotic  
glucosamine 6-phosphate N-acetyltransferase and one is closer to the bacterial enzymes of unknown specificity  and is thought to be possibly a horizontal transfer. 

Perhaps the family needs to be split?

**Comment by marcfeuermann** [comment]
The family tree is quite weird here. bacteria are in the middle of eukaryotes. We have an indication for an horizontal transfer, but from the tree topology it is hard to understand. Anyway, I've updated the annotation.

**Comment by ValWood** [comment]
I couldn't understand it either!
