### ISSUE TITLE
Review annotations to GO:0031975 envelope

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4626]
GO:0031975 envelope

Obsoletion request is here: https://github.com/geneontology/go-ontology/issues/27034

**Comment by suzialeksander** [comment]
@pgaudet any action needed here?

**Comment by pgaudet** [comment]
1 UniProt mapping: UniProtKB-SubCell:SL-0036 Cell envelope
Should be changed to GO:0030313 cell envelope
@Antonialock

**Comment by Antonialock** [comment]
done
