### ISSUE TITLE
Review annotations to GO:1905478 regulation of glutamate-ammonia ligase activity  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4627]
GO:1905479 negative regulation of glutamate-ammonia ligase activity
GO:1905480 positive regulation of glutamate-ammonia ligase activity
GO:1905478 regulation of glutamate-ammonia ligase activity

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1TMwaQpCpgSQsZ0DgbsVvGQm7bYVHbuPKrIYTahscZeQ/edit#gid=0

Single ZFIN annotation. No mappings, not present in any subsets. 

@sramachand Maybe one appropriate process would be 'cellular nitrogen homeostatic process'; let me know if you'd like me to create this term. 

Thanks, Pascale

**Comment by sramachand** [comment]
@pgaudet 

Could you please create the "cellular nitrogen homeostatic process" term? Thanks

Sridhar

**Comment by pgaudet** [comment]
Terms are now obsoleted, see https://github.com/geneontology/go-ontology/issues/25543
Remaining annotations appear in error reports.
