### ISSUE TITLE
Review annotations to GO:0006349 regulation of gene expression by genomic imprinting

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4629]
GO:0006349 regulation of gene expression by genomic imprinting

https://docs.google.com/spreadsheets/d/10yTI_nqzUXZPS2WOjCnrfRCgZb3odVysClOKDp5eDjI/edit#gid=0

**Comment by pgaudet** [comment]
* UniRule:UR000615760 > GO:regulation of gene expression by genomic imprinting ; GO:0006349

BHF-UCL | 4
FlyBase | 1
MGI | 22
UniProt | 6


Many annotations should be moved to the new term, 'GO:0141068 autosomal genomic imprinting' so most edits can not be made immediately.

**Comment by pgaudet** [comment]
Dear all, 

We will proceed with the obsoletion of GO:0006349 regulation of gene expression by genomic imprinting when annotation reviews are completed. Colin made suggestions for reannotation: 
BHF-UCL | 4
FlyBase | 1
MGI | 22

Thanks, 

Pascale

**Comment by hattrill** [comment]
fb done

**Comment by pgaudet** [comment]
Hi @LiNiMGI 
Just to let you know that the terms required for reannotations have nor been created. Let me know if you have any questions.

**Comment by suzialeksander** [comment]
This term was obsoleted; any remaining annotations will appear in GORULES error reports
