### ISSUE TITLE
Review annotations to GO:0043491 pkb signaling 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4633]
GO:0043491  protein kinase B signaling

Annotations + extensions are here: https://docs.google.com/spreadsheets/d/1u9Mo1LQnHVOI88CYNDKhKL2csszugGRLKkZZDicVqWY/edit#gid=653397601

**Comment by pgaudet** [comment]
No mappings, not used in with field
Does have extensions

**Comment by pgaudet** [comment]
Being pre-reviewed by @hattrill @gantonazzo @RLovering 
we'll make recommendations when we have looked at a few more.

**Comment by hattrill** [comment]
Checked FB - most are correct. All in the P13K-Akt signaling module. A few redundant with PI3K signaling.

**Comment by RLovering** [comment]
all checked and revised where needed

**Comment by pgaudet** [comment]
Annotations should be reviewed; some annotations to the pathway are to the upstream proteins (such as receptors) - see guidelines here: 
https://docs.google.com/document/d/1ukxL3vKfLbV4NAiGSeGg3EbpLKijfXXOr0npHeUYLI4/edit#heading=h.ko6f1mhlp57a


assigned_by | count
-- | -- 
dictyBase | 3
FlyBase | 1
MGI | 78
RGD | 3
UniProt | 18
ZFIN | 1






Thanks, Pascale

**Comment by pfey03** [comment]
@pgaudet I don't find any term 'positive regulation of PI3K/PKB signaling ' Is it too new and will there be  a term just 'PI3K/PKB signaling'?

**Comment by pfey03** [comment]
and what is wrong with 'phosphatidylinositol 3-kinase/protein kinase B signal transduction'

**Comment by gthayman** [comment]
RGD done.

**Comment by deustp01** [comment]
Reactome (not on the list above) done as a sanity check: all our annotations are to phosphorylation of other proteins by activated AKT / PKB. If I understand the [guidelines](https://docs.google.com/document/d/1ukxL3vKfLbV4NAiGSeGg3EbpLKijfXXOr0npHeUYLI4/edit#heading=h.ko6f1mhlp57a) correctly, this puts them outside (downstream of) the proposed "pkb signaling" module, as that module end with the activation of AKT, a step before it phosphorylates anything.

**Comment by pgaudet** [comment]
@deustp01 

> Reactome (not on the list above) done as a sanity check: we have 15 annotations to phosphorylation of other proteins by activated AKT / PKB. If I understand the [guidelines](https://docs.google.com/document/d/1ukxL3vKfLbV4NAiGSeGg3EbpLKijfXXOr0npHeUYLI4/edit#heading=h.ko6f1mhlp57a) correctly, this puts them outside (downstream of) the proposed "pkb signaling" module, as that module end with the activation of AKT, a step before it phosphorylates anything.

This is right. We might annotate the larger pathway that includes the PI3K/PKB cascade for the PKB targets, but these targets are not part of the PI3K/PKB cascade. 

Thanks, Pascale

**Comment by hattrill** [comment]
FB done

**Comment by pfey03** [comment]
Dicty is done

**Comment by pgaudet** [comment]
@LiNiMGI Many annotations that I looked at need to be changed, when you have a chance to look into this.

**Comment by LiNiMGI** [comment]
Thanks @pgaudet for those suggestions, `

**Comment by pgaudet** [comment]
Ill reopen - UniProt are not finished

**Comment by LiNiMGI** [comment]
sorry I accidentally closed it. thanks @pgaudet

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by Antonialock** [comment]
UniProt done.

**Comment by suzialeksander** [comment]
Annotation review is done. Is there any further action here?

**Comment by pgaudet** [comment]
Term was renamed https://github.com/geneontology/go-ontology/issues/25656
