### ISSUE TITLE
Review annotations to GO:0014065 'phosphatidylinositol 3-kinase signaling' and regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4638]
GO:0014065 'phosphatidylinositol 3-kinase signaling' and regulation children

Annotations are here: https://docs.google.com/spreadsheets/d/1cryOv5z7cxjbYA0Mt7avXWVxmDMSUGKDiYyRm98NFF4/edit#gid=0

Some extensions (in the spreadsheet) 
Not used for 'with/from'

**Comment by pgaudet** [comment]
Mappings 

- InterPro:IPR026722 Neuronal tyrosine-phosphorylated phosphoinositide-3-kinase adapter 1/2 > GO:phosphatidylinositol 3-kinase signaling ; GO:0014065
- InterPro:IPR037702 PI3Kbeta, catalytic domain > GO:phosphatidylinositol 3-kinase signaling ; GO:0014065
- InterPro:IPR037703 PI3Kdelta, catalytic domain > GO:phosphatidylinositol 3-kinase signaling ; GO:0014065
- InterPro:IPR037704 PI3Kalpha, catalytic domain > GO:phosphatidylinositol 3-kinase signaling ; GO:0014065

**Comment by hattrill** [comment]
All FB removed or replaced with PKb signaling equivalents

**Comment by pgaudet** [comment]
Group | Number of annotations
-- | --
AgBase | 11
ARUK-UCL | 8
BHF-UCL | 46
CACAO | 1
CAFA | 5
dictyBase | 9
FlyBase | 28
GO_Central | 6
MGI | 62
RGD | 9
UniProt | 78
ZFIN | 6

Review is only needed if your group does not have a mechanism for automatic replacement. 
@gthayman Is this the case for RGD?

**Comment by gthayman** [comment]
RGD done.

**Comment by pfey03** [comment]
Why are these obsoleted?

**Comment by pgaudet** [comment]
I forgot to link the ticket: https://github.com/geneontology/go-ontology/issues/25657

This term is being obsoleted because it either represents the PI3K/PKB cascade, or the paper is just assaying the PI3K activity. 

OK ? 

Thanks, Pascale

**Comment by blazaropinto** [comment]
Thanks Pascale, the four InterPro entries are updated. The changes will be available in the next InterPro release.

Best regards,
Beatriz

**Comment by RLovering** [comment]
UCL annotations all checked

**Comment by suzialeksander** [comment]
term has been obsoleted.  remaining unchanged annotations can now be found on the annotation error reports.
