### ISSUE TITLE
GO:0048015 phosphatidylinositol-mediated signaling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4639]
GO:0048015 phosphatidylinositol-mediated signaling
Annotations are here: 
https://docs.google.com/spreadsheets/d/1qQQS35lei6Roy-OtuxWhOx5ZEfLDXCIfaAq4b31SpVk/edit#gid=0

(43 EXP + 5 mappings)

**Comment by pgaudet** [comment]
Check if these can be annotated to the more specific term [GO:0014065 phosphatidylinositol 3-kinase signaling](https://amigo.geneontology.org/amigo/term/GO:0014065#display-lineage-tab)

or if we need new terms

**Comment by deustp01** [comment]
> Annotations are here:

There is also one Reactome annotation, to a pathway R-HSA-198203 "PI3K/AKT activation". It could probably be switched to GO:0014065 phosphatidylinositol 3-kinase signaling if needed.

**Comment by pgaudet** [comment]
Hi @deustp01 

Please move the annotation to GO:0043491 'phosphatidylinositol 3-kinase signaling/protein kinase B signal transduction', which represents this specific signaling cassette. 

Thanks, Pascale

**Comment by deustp01** [comment]
Done. The change will propagate to our public db with our next release, in September

**Comment by pfey03** [comment]
@pgaudet why are the dicty annotation listed that are not this terms but chemotaxis to cAMP and actin polymerisation? I won't change these

**Comment by pgaudet** [comment]
@pfey03 because these use the term in the extension - you have for e. g. chemotaxis to cAMP part of phosphatidylinositol-mediated signaling (which seems the wrong way around ?)

Thanks, Pascale

**Comment by pfey03** [comment]
ok, I see it now. It's often Bob''s annotations, but I change them usually

**Comment by pfey03** [comment]
@pgaudet GO:0014065 that you recommend above is an obsoleted term

**Comment by pfey03** [comment]
GO:0043491 protein kinase B signaling is a valid term

**Comment by pgaudet** [comment]
@pfey03 

> GO:0014065 that you recommend above is an obsoleted term

Apologies.- too many moving parts! 

> GO:0043491 protein kinase B signaling

I thought this one was OK, since the abstract mentions PKB, I thought this might be the pathway they were testing?

**Comment by pfey03** [comment]
I need to read each paper as some annotation were pre P2GO

**Comment by pgaudet** [comment]
There are still about 4 annotations each by MGI and RGD.

**Comment by LiNiMGI** [comment]
MGI done

**Comment by pgaudet** [comment]
@sarach06 @blazaropinto  InterPro has not yet replied to this - were these mappings updated?

**Comment by pgaudet** [comment]
Thanks!
