### ISSUE TITLE
Review annotations to coreceptor activity involved in x

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4643]
GO:0060724 coreceptor activity involved in epidermal growth factor receptor signaling pathway
GO:0071936 coreceptor activity involved in Wnt signaling pathway
GO:1904928 coreceptor activity involved in canonical Wnt signaling pathway
GO:1904929 coreceptor activity involved in Wnt signaling pathway, planar cell polarity pathway    
GO:0060725 regulation of coreceptor activity (no annotations) - MF in BP

**Comment by pgaudet** [comment]
* 2 XenBase
* 2 BHF
* UniRule:UR000484796 > GO:coreceptor activity involved in Wnt signaling pathway ; GO:0071936
Annotations are here: 
https://docs.google.com/spreadsheets/d/1fWb5IUBncq1hcGKOX2QbysKWnj4kLQXmkvhiDRSymPQ/edit#gid=0

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
