### ISSUE TITLE
Review annotations to GO:0048017 inositol lipid-mediated signaling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4645]
GO:0048017 inositol lipid-mediated signaling

**Comment by hattrill** [comment]
Direct EXP annotatations to:
GO:0048017 inositol lipid-mediated signaling - 0
 and for single child term:
GO:0048015 phosphatidylinositol-mediated signaling - 8

**Comment by pgaudet** [comment]
GO:0048017 inositol lipid-mediated signaling - has 8 EXP: 

https://docs.google.com/spreadsheets/d/1rVvaF6iE3mZPdiXz-23e-AASDT5D9NIdTA2JbHqDIqY/edit#gid=0

* 1 UniProt - removed
* 5 SGD
* 1 MGI
* 1 WB
I am surprised we are getting different numbers...

**Comment by pgaudet** [comment]
for GO:0048015 phosphatidylinositol-mediated signaling , see https://github.com/geneontology/go-annotation/issues/4639

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
@vanaukenk There is one WB annotation left to review; can you please check? I dont see a lot of molecular evidence to annotations a precise role in a signaling pathway.

**Comment by pgaudet** [comment]
@sarach06 @blazaropinto 

IPR016555  >> PLD is involved in many signaling pathways, see Fig 3 in PMID:29478139

I suggest you move the annotation to the parent GO:0035556 intracellular signal transduction. 

Thanks, Pascale

**Comment by blazaropinto** [comment]
Thank you for letting us know Pascale. I updated the term in this entry. The changes will be available in the next InterPro release.

Best,
Beatriz

**Comment by pgaudet** [comment]
Thanks everyone!
