### ISSUE TITLE
Review annotations to GO:0031566 actomyosin contractile ring maintenance, and redundant children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4646]
Dear all, 

The proposal has been made to obsolete 
GO:0032189 maintenance of actomyosin contractile ring localization
GO:0032187 actomyosin contractile ring localization
~GO:0031566 actomyosin contractile ring maintenance~
GO:0036212 contractile ring maintenance
see https://github.com/geneontology/go-ontology/issues/25606
and "regulation" terms

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1nKlwFfm8vXAPz5sJyPtGb16YXE70JupOpAMr1Mx2ytc/edit#gid=0

Impacted groups: 

~FlyBase2 @hattrill~
CGD 1 @jlewsmith 
~PomBase 16 @ValWood~ Done
Cacao 1 @dsiegele 

----

Thanks.

**Comment by hattrill** [comment]
FB done

**Comment by ValWood** [comment]
These are done (obsoleted terms).

**Comment by pgaudet** [comment]
1 annotation by CACAO
1 by Japonicaus - @ValWood  do you fix these?

**Comment by ValWood** [comment]
Actually

GO:0031566 was not obsoleted, it was renamed to 
actomyosin contractile ring maturation (GO:0031566)
which is more in line with current science

**Comment by ValWood** [comment]
I do fix the japonicus....
