### ISSUE TITLE
S. pombe IRS4/Tax4  PTN000130974

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4651]
* **PTHR ID & PTN node:**
[PTN000130974](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000130974)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1687.09

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Propagation

GO:0006897 | endocytosis | IBA with S000001445 , 1305550 , S000000143 , Q9H4M9 , FBgn0035060 , Q8IJF4 , MGI:104583 , FBgn0016693 , FBgn0023388 , CAL0000184200 , locus:2135462 , PTN000130974 , P42566 , S000005028 , 628883 , MGI:2154274 , MGI:1341878 , locus:2092419 , CAL0000174035 , MGI:1338069 , WBGene00001224 , Q9NLB8
-- | -- | --

GO:0016197 | endosomal transport | IBA with MGI:1341878 , Q9H4M9 , FBgn0023388 , Q9NZN3 , locus:2092419 , 1305550 , WBGene00004373 , PTN000130974 , Q9NZN4 , Q9H223
-- | -- | --

The yeast orthologs are TAX4 and IRS1. I wasn't sure about the higher eukaryotic orthologs. However, I wonder if, from the pleiotropic nature of the annotations, if the key annotation here is [inositol lipid-mediated signaling](https://www.yeastgenome.org/go/GO:0048017) (It appears to be involved in lots of membrane activities. The S. cerevisiae paralog annotations are focused on autophagy.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
I've restrited the propagation. However, I'm so so happy with the topology of the tree.
