### ISSUE TITLE
Sulfatase, N-terminal (IPR000917)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4652]
* **InterPro ID / label**
Sulfatase, N-terminal (IPR000917)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Human SGSH (P51688)
Fly Sgsh (Q9VE24)

* **Description of issue**
IPR000917 adds "[sulfuric ester hydrolase activity (GO:0008484)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008484)" (which corresponds to EC:3.1.6.-) to the proteins above, but those proteins are annotated to EC:3.10.1.1 in UniProt and/or get N-sulfoglucosamine sulfohydrolase activity (GO:0016250) (corresponding to EC:3.10.1.1) via PAINT annotation.

Other proteins matching IPR000917 do seem to be bona fide sulfuric ester hydrolases, so maybe the only thing to do here is just to remove the GO-MF term from IPR000917?

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for pointing this out. I agree, I removed this term from the entry. The changes will be available in the next InterPro release.

Best,
Beatriz

**Comment by sjm41** [comment]
Thanks!
