### ISSUE TITLE
PTN000022481 (L-ASPARAGINASE (PTHR10188))

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4654]
PTN000022481 adds the following two catalytic activity terms to members of the L-ASPARAGINASE (PTHR10188) family:

asparaginase activity (= EC:3.5.1.1)
PTN000810088 (ECOLI|EnsemblGenome=BAA35516|UniProtKB=P37595)
PTN001303548 (ARATH|TAIR=locus=2093387|UniProtKB=Q8GXG1)
PTN000022633 (ARATH|TAIR=locus=2181509|UniProtKB=P50287)
PTN000022599 (RAT|RGD=708526|UniProtKB=Q8VI04)
PTN002468878 (HUMAN|HGNC=16448|UniProtKB=Q7L266)

beta-aspartyl-peptidase activity (= EC:3.4.19.5)
PTN000810088 (ECOLI|EnsemblGenome=BAA35516|UniProtKB=P37595)
PTN002468878 (HUMAN|HGNC=16448|UniProtKB=Q7L266)

Human ASRGL1 (Q7L266) is a primary source for both activities - these annotations look correct, though this protein is exceptional in having both activities.

However, the other 2 human members of PTHR10188 are not known to have either of those activities, and instead are characterized to have different activities:
- TASP1 (Q9H6P5) threonine-type endopeptidase activity (EC:3.4.25.-)
- AGA (P20933) N4-(beta-N-acetylglucosaminyl)-L-asparaginase activity (EC:3.5.1.26)

So 'asparaginase activity' and 'beta-aspartyl-peptidase activity' are being incorrectly added to human TASP1 and AGA (and the same goes for their orthologs in other species).

I think PTN000022481 /PTHR10188 probably needs splitting out with different activities annotated to different branches?

**Comment by marcfeuermann** [comment]
We have indeed 3 clades with different activities. I've updated the annotation.

**Comment by sjm41** [comment]
Nice, thanks!
