### ISSUE TITLE
Review annotations to GO:0071514 genomic imprinting

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4657]
Dear all, 

For the work in transcription refactoring, we are now looking at epigenetic processes, and have created new terms that are more appropriate for a lot of annotations current to GO:0071514 genomic imprinting. 

We have made suggestions for reannotation here: 
https://docs.google.com/spreadsheets/d/1Tj_OtzIL-kj_1a2XK7fZ-8sozZLpv1HufAskHvXWTrU/edit#gid=0

1 BHF
18 MGI
17 UniProt - DONE
1 GO Central - DONE

Thanks, Pascale

**Comment by LiNiMGI** [comment]
MGI done

**Comment by pgaudet** [comment]
All done
