### ISSUE TITLE
Review annotations to GO:0090172  microtubule cytoskeleton organization involved in homologous chromosome segregation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4658]
Dear all, 

The proposal has been made to obsolete  GO:0090172  microtubule cytoskeleton organization involved in homologous chromosome segregation
see https://github.com/geneontology/go-ontology/issues/25545

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/12wZH2K_31uc6mt6H529E_J5jnzoPftxzvQNBPcTL34s/edit#gid=0

Impacted groups: 
MGI @LiNiMGI  (1 annotation)

Thanks.

**Comment by ValWood** [comment]
Hi @LiNiMGI  is it OK for me to GO ahead with this obsoletion (single MGI annotation)
Thanks
val

**Comment by LiNiMGI** [comment]
MGI done, thanks @ValWood!
