### ISSUE TITLE
Review annotations to GO:0000904 cell morphogenesis involved in differentiation

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4661]
Dear all, 

The proposal has been made to obsolete GO:0000904 cell morphogenesis involved in differentiation and its regulation terms, with direct replacement GO:0000902 cell morphogenesis. And its regulation, positive regulation, and negative regulation.

see https://github.com/geneontology/go-ontology/issues/24299.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1hvYeqnzHsyHq-IMHEAj-qOdipYR8dJocU90LceWwK1o/edit#gid=0

Impacted groups: 

MGI 14
TAIR 2
ZFIN 16
RGD 1
CACAO 1
----

Thanks.

**Comment by raymond91125** [comment]
made by mistake.

**Comment by raymond91125** [comment]
pending discussion https://github.com/geneontology/go-ontology/issues/24299

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
