### ISSUE TITLE
GO:0022848	 acetylcholine-gated monoatomic cation-selective channel activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-annotation#4665]
* **PTHR ID & PTN node:**
MGI:MGI:1202403|MGI:MGI:3609260|PANTHER:PTN004502671|RGD:621534|UniProtKB:Q9UGM1
* **Sequences with problematic annotation (ID + gene/protein name):**
P46098 and other proteins of the 5-hydroxytryptamine receptor (TC 1.A.9.2) subfamily
* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Those are serotonin-gated  cation-selective channels. Not acetylcholine.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by pgaudet** [comment]
Fixed, thanks for reporting this.
