### ISSUE TITLE
IPR028885 Adenylyltransferase and sulfurtransferase MOCS3/Uba4

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4666]
* **InterPro ID / label**
IPR028885 Adenylyltransferase and sulfurtransferase MOCS3/Uba4

* **Example sequences with problematic annotation (ID + gene/protein name):**
MOCS3/Uba4

* **Description of issue**
This entry is currently annotated with the MF "thiosulfate sulfurtransferase activity (GO:0004792)" (= EC: 2.8.1.1).
This specific activity has been shown for human MOCS3/ yeast Uba4 in in vitro assays, but it's not thought to be the physiological reaction catalysed in eukaryotes.

E.g. from the abstract of PMID:17459099: "Our studies revealed that in humans and most eukaryotes thiosulfate is not the physiologic sulfur donor for MOCS3, whereas in bacterial homologs, which have an arginine at the last position of the active site loop, thiosulfate can be used as a sulfur source for molybdenum cofactor biosynthesis."

E.g from the abstract of PMID: 18491921: "We demonstrate that the C-terminal domain of Uba4, like MOCS3, has rhodanese activity and is able to transfer the sulfur from thiosulfate to cyanide in vitro. In addition, we were able to copurify stable heterotetrameric complexes of Uba4 with both human Urm1 and MOCS2A. The N-terminal domain of Uba4 catalyzes the activation of either MOCS2A or Urm1 by formation of an acyl-adenylate bond. After adenylation, persulfurated Uba4 was able to form a thiocarboxylate group at the C-terminal glycine of either Urm1 or MOCS2A."

UniProt annotates these EC terms to human MOCS3:
EC:2.7.7.80 (= GO:0061605 molybdopterin-synthase adenylyltransferase activity)
EC:2.8.1.11 (= GO:0061604 molybdopterin-synthase sulfurtransferase activity)

So you could consider adding those GO terms instead, but I'm not sure they are accurate for all proteins with IPR028885.
So may be better just to remove the "thiosulfate sulfurtransferase activity (GO:0004792)" term??

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this. I think GO:0016783 (the parent of the current GO term and GO:0061604) could be a good replacement. Also I think GO:0016779 seem to apply to all sequences of this family. Please let me know if you agree with this.

Regards,
Beatriz

**Comment by sjm41** [comment]
Hi Beatriz

_I think GO:0016783 (the parent of the current GO term and GO:0061604) could be a good replacement._ 
Yes, I agree.

_Also I think GO:0016779 seem to apply to all sequences of this family._ 
That seems fine.
Though I wonder if the child term of GO:0016779 nucleotidyltransferase activity, adenylyltransferase activity GO:0070566, would also work? (It at least fits with the InterPro term name, though maybe all members are not adenylyltransferases?)

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for your quick reply, I think you are right, almost all members are annotated in Uniprot as adenylyltransferases (except for some trEMBL uncharacterised sequences), so I added those two terms and removed GO:0004792, The changes will be available in the next InterPro release.

Best regards,

Beatriz
