### ISSUE TITLE
Review annotations to GO:0019800 peptide cross-linking via chondroitin 4-sulfate glycosaminoglycan 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4667]
Hi @LiNiMGI 

There are 8 MGI annotations to GO:0019800 peptide cross-linking via chondroitin 4-sulfate glycosaminoglycan 
based on PMID:18757743

However it seems like these are the targets of the glycosaminoglycanination (?), not the mediators. Can you please check ? 

Thanks, Pascale

**Comment by dms321** [comment]
Deleted

**Comment by pgaudet** [comment]
Thanks!
