### ISSUE TITLE
Annotation check  LSM1

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4668]
[LSM1] enables	[RNA cap binding](https://www.yeastgenome.org/go/GO:0000339)		[IMP](http://wiki.geneontology.org/index.php/Inferred_from_Mutant_Phenotype_(IMP))	SGD	2003-04-10

Hi, could you check this one? As far as I'm aware LSM1-7 complex  doesn't bind to the CAP, it binds to the 3'  end or RNAs usually? (I think it is involved int he decapping pathway, but not by binding to the cap) Also, the   IMP  evidence looks odd?

@suzialeksander 
@srengel

**Comment by ValWood** [comment]
Note to self, only evidence for PANTHER:PTN000400406

**Comment by ValWood** [comment]
I might be incorrect here,  but as far as I can see all Lsm complexes bind to the U-rich region at the 3' end of RNA. Although most of the data I see comes from Lsm 2-8 rather than 1-7, I think the specificity is the same?

**Comment by srengel** [comment]
Hi Val, i have removed the annotation in P2GO just now.  thanks for bringing it to our attention.

**Comment by ValWood** [comment]
@marcfeuermann  will this disappear automatically?

**Comment by marcfeuermann** [comment]
Hi Val and Stacia,
It should disappear automatically, but new annotations or changes take a while before being available to PAINT, so I also removed the PAINT propagation. The tool is quite quick and it takes only few seconds to change it.
Thanks.
Marc.
