### ISSUE TITLE
Review annotations to GO:0048016 inositol phosphate-mediated signaling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4669]
The proposal has been made to obsolete GO:0048016 inositol phosphate-mediated signaling, see 
https://github.com/geneontology/go-ontology/issues/25718

The reason for obsoletion is that this term is not clearly defined and represents several pathways, or is sometimes used to annotate experiments in which some inositol phosphate's level changes, but no data is presented on the actual pathway affected.

**Comment by pfey03** [comment]
we had one ISS annotation and I deleted it

**Comment by pgaudet** [comment]
May be useful to look at an example of a generalized pathway (from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3385957/)

<img width="704" alt="image" src="https://github.com/geneontology/go-annotation/assets/4782928/a8fbe1f9-d1bb-4788-99c1-b96f2cc135bd">

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by LiNiMGI** [comment]
MGI done

**Comment by pgaudet** [comment]
BHF done

**Comment by vanaukenk** [comment]
WB done

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports.
