### ISSUE TITLE
Review annotations to GO:0000904 cell morphogenesis involved in differentiation & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4671]
GO:0000904 cell morphogenesis involved in differentiation
GO:0010769 regulation of cell morphogenesis involved in differentiation 
GO:0010771 negative regulation of cell morphogenesis involved in differentiation
GO:0010770 positive regulation of cell morphogenesis involved in differentiation

Were obsoleted or renamed, 
see https://github.com/geneontology/go-ontology/issues/24299

https://docs.google.com/spreadsheets/d/1S9aobGIF03vIYxEWtKmx0e_XBj9w1lKJo4sR7LLVw40/edit

**Comment by ukemi** [comment]
MGI done

**Comment by pgaudet** [comment]
AgBase done

**Comment by pgaudet** [comment]
Annotations should be rehoused with the REPLACED_BY 
If people want to check, there are still: 
1 CACAO 
1 RGD
2 TAIR
16 ZFIN


Please take your name off the list when you are done (or if you dont want to review the annotations).

**Comment by gthayman** [comment]
RGD done.

**Comment by tberardini** [comment]
TAIR annotations have been automatically migrated.

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error report
