### ISSUE TITLE
Lupus La protein

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4672]
https://www.uniprot.org/uniprotkb/P05455/entry

Molecular Function | DNA bindingSource:DisProt1 Publication

Molecular Function	[DNA binding](https://www.ebi.ac.uk/QuickGO/term/GO:0003677)Source:DisProt1 Publication

I don't see any mention of DNA binding in this paper?
PMID: 12842046
https://pubmed.ncbi.nlm.nih.gov/12842046/

**Comment by ValWood** [comment]
tagging @victorianugnes

**Comment by pgaudet** [comment]
@Aspromonte

**Comment by ValWood** [comment]
So just to confirm, is DNA binding annotation removed?  If so I can close this one.

**Comment by victorianugnes** [comment]
Hi, sorry for the late reply. Yes it's removed already. Thanks again
