### ISSUE TITLE
Saccharopine dehydrogenase, NADP binding domain (IPR005097)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4673]
* **InterPro ID / label**
Saccharopine dehydrogenase, NADP binding domain (IPR005097)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly [FBgn0038038](https://flybase.org/reports/FBgn0038038), [FBgn0037298](https://flybase.org/reports/FBgn0037298)
Human SCCPDH https://www.uniprot.org/uniprotkb/Q8NBX0/entry

* **Description of issue**
This entry is currently annotated to the high level term 'oxidoreductase activity'.
But I don't think this represents a catalytic domain, and the InterPro entry indicates the domain is also found in Homospermidine synthase (HSS) (2.5.1.44), a transferase.
So, I think this InterPro2GO should be removed.

(I also see that a couple of sentences are repeated in the first and second paragraphs of the InterPro description)

**Comment by sarach06** [comment]
Hi Steven, 
Thank you very much for this. Yes, I agree. I have removed the term from this entry and updated the description. This will be visible in the next interPro release (96.0).
Best,
Sara
