### ISSUE TITLE
Review annotations to  GO:0045213 neurotransmitter receptor metabolic process - full list 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4675]
GO:0001505 regulation of neurotransmitter levels
GO:0042133 neurotransmitter metabolic process
GO:0042136 neurotransmitter biosynthetic process
GO:0042135 neurotransmitter catabolic process
GO:0045213 neurotransmitter receptor metabolic process
GO:0097019 neurotransmitter receptor catabolic process
GO:0042165 neurotransmitter binding

**Comment by pgaudet** [comment]
53 EXP 

https://docs.google.com/spreadsheets/d/1xOStk5iOhXvf6AVSKlBmSESrpnpFHa8F_S5Atns4SP4/edit#gid=0

**Comment by pgaudet** [comment]
2 InterPro

* interpro2go	InterPro:IPR003980 Histamine H3 receptor > GO:regulation of neurotransmitter levels ; GO:0001505
* interpro2go	InterPro:IPR017128 Catechol O-methyltransferase, eukaryotic > GO:neurotransmitter catabolic process ; GO:0042135

**Comment by pgaudet** [comment]
2 KW2GO 
@Antonialock 
* uniprotkb_kw2go	UniProtKB-KW:KW-0531 Neurotransmitter degradation > GO:neurotransmitter catabolic process ; GO:0042135
* uniprotkb_kw2go	UniProtKB-KW:KW-0530 Neurotransmitter biosynthesis > GO:neurotransmitter biosynthetic process ; GO:0042136

**Comment by pgaudet** [comment]
1 UniRule @pedruzzi 
unirule2go	UniRule:UR000639763 > GO:neurotransmitter catabolic process ; GO:0042135

**Comment by RLovering** [comment]
Hi
I found 4 annotations that were either TAS/NAS/ISS which I have removed. But I only checked for annotations directly to the terms listed above. UCL has 160 annotations if all child terms are included. https://www.ebi.ac.uk/QuickGO/annotations?assignedBy=ARUK-UCL,Alzheimers_University_of_Toronto,BHF-UCL,HGNC-UCL,ParkinsonsUK-UCL,SynGO-UCL&goId=GO:0042165,GO:0097019,GO:0045213,GO:0042135,GO:0042136,GO:0042133,GO:0001505&goUsageRelationships=is_a,part_of,occurs_in,regulates&goUsage=descendants

Please confirm that only direct annotations to the 7 terms above are to be reviewed. If child terms are to be edited then the spreadsheet needs to be updated

Thanks

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 

Yes, only direct annotations to these terms are concerned.

**Comment by Antonialock** [comment]
uniprot done

**Comment by ukemi** [comment]
MGI done

**Comment by gthayman** [comment]
RGD done.

**Comment by sramachand** [comment]
ZFIN done

**Comment by vanaukenk** [comment]
WB done

**Comment by hattrill** [comment]
FB done

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error reports
