### ISSUE TITLE
Review annotations to evasion of host immune response via modulation of xx

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4676]
GO:0042786 evasion of host immune response via modulation of host antigen processing and presentation
GO:0042784 evasion of host immune response via modulation of host complement system
GO:0042785 evasion of host immune response via modulation of host cytokine network

**Comment by suzialeksander** [comment]
[GO:0042784](https://www.ebi.ac.uk/QuickGO/term/GO:0042784) 	symbiont-mediated suppression of host complement activation 	
[GO:0042785](https://www.ebi.ac.uk/QuickGO/term/GO:0042785) 	obsolete evasion of host immune response via modulation of host cytokine network 	
[GO:0042786](https://www.ebi.ac.uk/QuickGO/term/GO:0042786) 	obsolete evasion of host immune response via modulation of host antigen processing and presentation


One of these is still active. Is there any action here @pgaudet
