### ISSUE TITLE
Review annotations to GO:0016580 Sin3 complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4680]
Dear all, 

The proposal has been made to obsolete GO:0016580 Sin3 complex
see https://github.com/geneontology/go-ontology/issues/25357

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1ET5wOaarn-cTyXfonmu_YMWSA-Cf0fiR2YHf9J1nEJk/edit#gid=0

Impacted groups: 
BHF-UCL 4
MGI 1
TAIR 7
UniProt 6

Thanks.

**Comment by ValWood** [comment]
Hi @tberardini @LiNiMGI @Antonialock @RLovering 

The action is to either 
1) move up to SIN-3 type complex
Or 
2) annotate more precisely to One of the Rpd3* complexes

I will merge into Sin-3 type do if you do no action the annotations will move there.
v

**Comment by tberardini** [comment]
We'd move up to SIN-3 type complex so no action needed on our part. Thanks for the heads up, @ValWood.

**Comment by RLovering** [comment]
UCL done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by pgaudet** [comment]
Moving up is also OK for UniProt
