### ISSUE TITLE
Review annotations to NF-kappaB signaling pathway (canonical and non-canonical)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4682]
It seems like some annotations contain upstream proteins that should be annotated to 'regulation of NF-kappaB signal transduction' and/or using the relation 'acts upstream of or within' for the NF-kappaB terms: 

GO:0038061 'non-canonical NF-kappaB signal transduction'
GO:0007249 'canonical NF-kappaB signal transduction'

Background: see images here: https://docs.google.com/document/d/1ukxL3vKfLbV4NAiGSeGg3EbpLKijfXXOr0npHeUYLI4/edit#heading=h.lkbwi265yjnj

GO:0038061
non-canonical NF-kappaB signal transduction (was: NIK/NF-kappaB signaling)  
The process in which a signal is passed on to downstream components within the cell through the NIK-dependent processing and activation of NF-kappaB. Begins with activation of the NF-kappaB-inducing kinase (NIK), which in turn phosphorylates and activates IkappaB kinase alpha (IKKalpha). IKKalpha phosphorylates the NF-kappa B2 protein (p100) leading to p100 processing and release of an active NF-kappaB (p52). The non-canonical NF-kappaB signaling pathway is generally activated by ligands of the TNF receptor superfamily, including lymphotoxin beta (LTB), CD40, OX40, RANK, TWEAK and B cell-activating factor (BAFF). PMID:11239468 PMID:15140882 PMID:34659217

GO:0007249
canonical NF-kappaB signal transduction (was: I-kappaB kinase/NF-kappaB signaling)
The process in which a signal is passed on to downstream components within the cell through the I-kappaB-kinase (IKK)-dependent activation of NF-kappaB, also known as the canonical NF-kappaB signaling cascade. The cascade begins with activation of a trimeric IKK complex (consisting of catalytic kinase subunits IKKalpha and/or IKKbeta, and the regulatory scaffold protein NEMO) and ends with the regulation of transcription of target genes by NF-kappaB. In a resting state, NF-kappaB dimers are bound to I-kappaB proteins, sequestering NF-kappaB in the cytoplasm. Phosphorylation of I-kappaB targets I-kappaB for ubiquitination and proteasomal degradation, thus releasing the NF-kappaB dimers, which can translocate to the nucleus to bind DNA and regulate transcription. The canonical NF-kappaB pathway is mainly stimulated by proinflammatory cytokines such as IL-1beta, tumor necrosis factor (TNF)-alpha, antigen ligands, and toll-like receptors (TLRs). PMID:12773372 PMID:34659217

**Comment by pgaudet** [comment]
* InterPro:IPR030312 Interleukin-1 receptor-associated kinase 1-binding protein 1 > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249
* InterPro:IPR033621 TRAF-interacting protein with FHA domain-containing protein > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249
* InterPro:IPR038753 NF-kappa-B inhibitor-like protein 1 > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249
* InterPro:IPR039669 TRAF family member-associated NF-kappa-B activator > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249
* InterPro:IPR042227 NF-kappa-B inhibitor-interacting Ras-like protein > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1xDQq-ccCfAYv-lQ_T1_S_dWQWCxf3jYhejhTPW6AAGA/edit#gid=0

**Comment by pgaudet** [comment]
assigned_by
--
AgBase | 5
ARUK-UCL | 20
BHF-UCL | 3
CAFA | 6
MGI | 103
RGD | 3
UniProt | 69
ZFIN | 13

**Comment by sramachand** [comment]
ZFIN done

**Comment by RLovering** [comment]
UCL done

**Comment by sarach06** [comment]
Dear Pascale,
Thank you very much. I have checked these InterPro entries, they have the GO:0007249 term associated.
Best regards,
Sara

**Comment by pgaudet** [comment]
@gthayman single RDG annotation left, I made a suggestion in the spreadsheet https://docs.google.com/spreadsheets/d/1xDQq-ccCfAYv-lQ_T1_S_dWQWCxf3jYhejhTPW6AAGA/edit#gid=0

**Comment by gthayman** [comment]
Changed.

**Comment by ukemi** [comment]
MGI done

**Comment by hattrill** [comment]
@pgaudet I had a look at the InterPro2GO associations - I think that these would be better as regulatory terms:

> * InterPro:IPR030312 Interleukin-1 receptor-associated kinase 1-binding protein 1 > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249

**Update InterPro:IPR030312 to GO:0043123 positive regulation of canonical NF-kappaB signal transduction**

>     * InterPro:IPR033621 TRAF-interacting protein with FHA domain-containing protein > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249

From https://www.embopress.org/doi/full/10.15252/embr.202152878 Looks like it could be associated with both:
GO:0043123 positive regulation of canonical NF-kappaB signal transduction and GO:1901224 positive regulation of non-canonical NF-kappaB signal transduction, but it is best characterised for its interaction with the canonical pathway there I would suggest:

**Update InterPro:IPR033621 to GO:0043123 positive regulation of canonical NF-kappaB signal transduction**

>     * InterPro:IPR038753 NF-kappa-B inhibitor-like protein 1 > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249

**Update InterPro:IPR038753 to GO:0043124 negative regulation of canonical NF-kappaB signal transduction**

>     * InterPro:IPR039669 TRAF family member-associated NF-kappa-B activator > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249

Based on https://www.uniprot.org/uniprotkb/Q92844/entry:
**Update InterPro:IPR039669 to GO:0043124 negative regulation of canonical NF-kappaB signal transduction**

>     * InterPro:IPR042227 NF-kappa-B inhibitor-interacting Ras-like protein > GO:I-kappaB kinase/NF-kappaB signaling ; GO:0007249

 **Update InterPro:IPR042227 to GO:0043124 negative regulation of canonical NF-kappaB signal transduction**

**Comment by suzialeksander** [comment]
@Antonialock can you just check if the UniProt and CAFA are done?

**Comment by pgaudet** [comment]
@sarach06 @blazaropinto Would you please review the InterPro annotations based on Helen's suggestions above?
https://github.com/geneontology/go-annotation/issues/4682#issuecomment-1759617557

**Comment by blazaropinto** [comment]
Hi Pascale and Helen,

Thank you so much for that. I updated these 5 terms. The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by suzialeksander** [comment]
@pgaudet there are still holes in the spreadsheet but comments indicate this review is done, or as done as it will get. Is there any further action?

**Comment by pgaudet** [comment]
Let's close, thanks.
