### ISSUE TITLE
GPAD/GPI 2.0 Specifications - Request for comments on new draft

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-annotation#4684]
Starting on Tuesday, July 18th, we are requesting review and comments on the proposed GPAD/GPI 2.0 file format specifications. The spec has been revised since the [last round of comments](https://github.com/geneontology/go-annotation/issues/2864).

https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md

Please add any comments or questions you have about the specs to this ticket by Friday, August 18th, 2023.

Thank you.

**Comment by ukemi** [comment]
I sent these to Lori and looked them over as well. You did a nice job @balhoff. But as Lori said, we will see what happens when we start doing the new loads.  :)

**Comment by kltm** [comment]
Some initial comments:

* `'!gpa-version: 2.0' ` seems a little quirky; should this not be `gpad-version`? I know at one point an allowed file extension was `.gpa`, but that is no longer allowed. Does the history justify the inconsistency?
* There is the BNF comment that `complementation is written using minus symbol`; do we have complements anywhere? I'm not sure I ran into that.
* Date is a little funny for us. We want YYYY-MM-DD; time may be included as YYYY-MM-DDTHH:MM:SS, so ISO-8601 parsers will work, but we are not wanting to accept all ISO-8601 \(i.e. YYYYMMDD would be verboten). This is to preserve trivial parsing without worrying and the entire spec and necessitating a library.

**Comment by kltm** [comment]
Tagging @alexsign just to make sure this is on your radar. We're not switching to this immediately, but we are trying to firm up the spec for future conversation.

**Comment by kltm** [comment]
@balhoff 

* Okay, so if there are no complaints `gpa-version` to `gpad-version`.
* Ah, I missed it there. I just wanted to make sure it was used if mentioned. Either way.
* I'm a little worried that xsd:date is a bit...marginal? Maybe that's just me. How about noting that it's a subset of ISO 8601 as defined by xsd:date (https://books.xmlschemata.org/relaxng/ch19-77041.html, not sure what the best link is for an official ref)? I suspect that most people outside reading this would be more familiar/comfortable with ISO 8601 vs xsd:date.

**Comment by sierra-moxon** [comment]
Very clear - thank you!  One trivial comment - `DB_Object_Synonyms` uses the value in the example for `DB_Object_Symbol`.  Should all symbols be synonyms as well?

**Comment by balhoff** [comment]
@sierra-moxon I don't know the answer to your question. Maybe @vanaukenk or @ukemi could comment? The issue is that the example values have `AMOT` for `DB_Object_Symbol`, and `AMOT|KIAA1071` for `DB_Object_Synonyms`. I agree that does kind of lead you to a conclusion that might not be intended.

**Comment by pgaudet** [comment]
RIght, I dont think symbols should be synonyms. In some cases maybe people want to capture at least different casing? But I suggest we remove AMOT form synonyms in the examples. 

Thanks, 

Pascale

**Comment by balhoff** [comment]
Thanks @pgaudet, I changed the example: https://github.com/geneontology/go-annotation/pull/4724

**Comment by kltm** [comment]
@pgaudet Not sure how/why this is in the "Misc" project and not the "GPAD/GPI 2.0" project...
Unless you can rememeber why, I would suggest switching it over to there and probably closing.

**Comment by pgaudet** [comment]
Right. This is anyways done.
