### ISSUE TITLE
Review annotations to GO:0090650 cellular response to oxygen-glucose deprivation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4686]
Dear all, 

The proposal has been made to obsoleteGO:0090650 cellular response to oxygen-glucose deprivation
see https://github.com/geneontology/go-ontology/issues/21284

Annotations are here: https://docs.google.com/spreadsheets/d/1OMIoRgog1oVKfL6oCV4qkoommWgVrxP0xTXxsSaQWVA/edit#gid=0

2 MGI
20 RGD

This is not a normal process. 

Thanks, Pascale

**Comment by LiNiMGI** [comment]
MGI done

**Comment by suzialeksander** [comment]
All annotations have been fixed
