### ISSUE TITLE
Review annotations to  signaling via intracellular signaling cascade

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4690]
GO:0038030 non-canonical Wnt signaling pathway via MAPK cascade
GO:0038168 epidermal growth factor receptor signaling pathway via I-kappaB kinase/NF-kappaB cascade
GO:0038029 epidermal growth factor receptor signaling pathway via MAPK cascade
GO:0038167 epidermal growth factor receptor signaling pathway via positive regulation of NF-kappaB transcription factor activity

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1xKnZjV6ORptAjqGTs6smWinA6PBDriB1FjFoMmF9fgY/edit#gid=0

1 BHF 
1 MGI

**Comment by RLovering** [comment]
UCL-done

**Comment by LiNiMGI** [comment]
MGI done
