### ISSUE TITLE
Review annotations to GO:0004704 NF-kappaB-inducing kinase activity and its child GO:0007250 activation of NF-kappaB-inducing kinase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4692]
Dear all, 

The proposal has been made to obsolete 
GO:0004704 NF-kappaB-inducing kinase activity
and its child 
GO:0007250 activation of NF-kappaB-inducing kinase activity, 

see https://github.com/geneontology/go-ontology/issues/24418

Annotations are here: https://docs.google.com/spreadsheets/d/1OE3wUtf9dpnH4SwS-c-fg9a7okQPEIWoUwvSPlQQ05s/edit#gid=0

**Comment by pgaudet** [comment]
Group | Number of annotations
-- | --
AgBase | 1
MGI | 7 (including 1 extension)
UniProt | 16

**Comment by LiNiMGI** [comment]
mgi done.

**Comment by suzialeksander** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0007250 is still an active term. Is there any action required for GO:0007250? @pgaudet

**Comment by pgaudet** [comment]
Out of date. 

GO:0004704 NF-kappaB-inducing kinase activity is obsolete but not its child GO:0007250 activation of NF-kappaB-inducing kinase activit
