### ISSUE TITLE
Review annotations to GO:0044416 induction by symbiont of host defense response & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4693]
GO:0044416 induction by symbiont of host defense response
GO:0052391 induction by symbiont of defense-related host calcium ion flux
GO:0052075 positive regulation by symbiont of host jasmonic acid-mediated defense response
GO:0052104 induction by symbiont of host systemic acquired resistance
GO:0044832 induction by virus of host cytokine production
GO:0052102 positive regulation by symbiont of defense-related host calcium-dependent protein kinase pathway'
GO:0052074 positive regulation by symbiont of host salicylic acid-mediated defense response 
GO:0052035 positive regulation by symbiont of host inflammatory response

See https://github.com/geneontology/go-ontology/issues/21260

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1rOIpXSf23DrRB6gOp-CWAMST1qXyLa6e2rd229IgHG8/edit#gid=0

**Comment by suzialeksander** [comment]
@pgaudet I think this ticket is too broad; the spreadsheet wasn't touched but it looks like it contains terms not in the above ticket. Is there still any action needed?

**Comment by pgaudet** [comment]
Terms were obsoleted.
