### ISSUE TITLE
Review annotations to regulation of transcription involved in x

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4694]
There are very few annotations remaining to close  https://github.com/geneontology/go-ontology/issues/12739

assigned_by
--
BHF-UCL | 13
BHF-UCL-   ParkinsonsUK-UCL | 6
CGD | 9
FlyBase | 2
MGI | 7
SGD | 1
TAIR | 2
UniProt | 8
WB | 22

* GO:2000820 | 'negative regulation of transcription from   RNA polymerase II promoter involved in smooth muscle cell   differentiation'
* GO:1901522 | 'positive regulation of transcription from RNA polymerase II   promoter involved in cellular response to chemical stimulus'
* GO:1902097 | 'positive regulation of transcription from RNA polymerase II   promoter involved in defense response to Gram-negative bacterium'
* GO:1904081 | 'positive regulation of transcription from RNA polymerase II   promoter involved in neuron differentiation'
* GO:2000763 | 'positive regulation of transcription from RNA polymerase II   promoter involved in norepinephrine biosynthetic process'
* GO:0006990 | 'positive regulation of transcription from RNA polymerase II   promoter involved in unfolded protein response'

I'd like to go ahead with the obsoletion by the end of August, unless there are objections.

**Comment by RLovering** [comment]
created spreadsheet for UCL annotations here https://docs.google.com/spreadsheets/d/1bukxejuINOZg7e0C5Q8atzFLWV3fO-xSFpChArowaEY/edit?usp=sharing

**Comment by jlewsmith** [comment]
Hi Pascale,

I'm not finding CGD assignments on the spreadsheet - what am I missing?

Best,
Jodi


Jodi Lew-Smith Ph.D.
Senior Biocuration Scientist  |  Candida Genome Database
Department of Genetics
Stanford University School of Medicine
Stanford, CA 94305
***@***.***
________________________________

**Comment by srengel** [comment]
looks like the SGD one has already been addressed.

**Comment by Antonialock** [comment]
I got 23 annotations for UniProt.  They should all be fixed now.

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
Apologies, here's the spreadsheet
https://docs.google.com/spreadsheets/d/1FjL3O0ylo9UIm_jp9-Y21zfXOQDdV9T06JTjcKp73Wc/edit#gid=0

**Comment by RLovering** [comment]
UCL done

**Comment by pgaudet** [comment]
@jlewsmith Did you find your annotations with the spreadsheet? https://docs.google.com/spreadsheets/d/1FjL3O0ylo9UIm_jp9-Y21zfXOQDdV9T06JTjcKp73Wc/edit#gid=0

**Comment by jlewsmith** [comment]
Yes - they're done now.
