### ISSUE TITLE
Review annotations to GO:0050886 endocrine process and other endocrine terms

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4701]
Dear all, 

The proposal has been made to obsolete
GO:0050886 endocrine process
GO:0060986 endocrine hormone secretion
GO:0044060 regulation of endocrine process
GO:0038002 endocrine signaling

see https://github.com/geneontology/go-ontology/issues/17084

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1bn1AvN8Z0gbo0IuQfxO1EgMhHUC27XHO03hzcSA4qsk

Impacted groups: 
Flybase 3
CACAO 1

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
none

Thanks.

**Comment by hattrill** [comment]
FB done

**Comment by raymond91125** [comment]
Thanks.
