### ISSUE TITLE
Review annotations to GO:0048569 post-embryonic animal organ development / GO:0048563 morphogenesis

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4706]
Dear all, 

The proposal has been made to obsolete GO:0048569 post-embryonic animal organ development / GO:0048563 morphogenesis
see https://github.com/geneontology/go-ontology/issues/20469

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/17pXwtERUNZ130GkxAzyqwSOP0sHgDu4SXzB6beqOX10/edit#gid=0

Impacted groups: 
WB 2
RGD 1
MGI 7

----

Mappings that need to be reviewed: None

Thanks.

**Comment by gthayman** [comment]
RGD done.

**Comment by raymond91125** [comment]
These terms do have replaced_by so may not need manual re-annotations.

**Comment by LiNiMGI** [comment]
where I can I find the "replaced_by" information? Thanks, Li

**Comment by pgaudet** [comment]
Hi @LiNiMGI 
You can see them in Quick GO and AmiGO, for example: 
https://amigo.geneontology.org/amigo/term/GO:0003124

Note that this information is not yet available for this term since there has not been a release since the obsoletion.

**Comment by vanaukenk** [comment]
WB done

**Comment by LiNiMGI** [comment]
> These terms do have replaced_by so may not need manual re-annotations.

@raymond91125 what is the proposed "replace_by" term in this case? Thanks.

**Comment by raymond91125** [comment]
thanks all.
