### ISSUE TITLE
Review annotations to [INSERT GO TERM]

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4708]
GO:0043841 | (S)-lactate 2-kinase activity | 1 NOT annotation
GO:0080049 | L-gulono-1,4-lactone dehydrogenase activity | 2 EXP annotations
GO:0102053 | (-)-jasmonoyl-isoleucine synthetase activity | 4 EXP annotations

**Comment by pgaudet** [comment]
Not working 

@kltm any idea what's happening ?

**Comment by kltm** [comment]
@pgaudet see #4710
