### ISSUE TITLE
Review annotations to GO:1900095 regulation of dosage compensation by inactivation of X chromosome  & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4713]
GO:1900095 regulation of dosage compensation by inactivation of X chromosome will be obsoleted, see https://github.com/geneontology/go-ontology/issues/25956

Annotations are here: 
https://docs.google.com/spreadsheets/d/1qgrMv-MlrYg5fFjHg8kveADjxvXaB43rFrDuX_tahoA/edit#gid=0

- 12 Complex Portal (to a single paper)
- 3 MGI 
- 
Thanks, Pascale

**Comment by LiNiMGI** [comment]
Checked in Noctua today, MGI does not have any annotation to the term GO:1900095 regulation of dosage compensation by inactivation of X chromosome. Maybe it's already been changed during some other annotation reviews?

**Comment by sandraorchard** [comment]
Complex Portal done
