### ISSUE TITLE
check annotations to GO:0060819 inactivation of X chromosome by genomic imprinting and GO:0060820 inactivation of X chromosome by heterochromatin formation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4714]
GO:0060819 inactivation of X chromosome by genomic imprinting
GO:0060820 inactivation of X chromosome by heterochromatin formation

**Comment by pgaudet** [comment]
5 annotations, 
https://docs.google.com/spreadsheets/d/1XfxBZUcyvNKpPMJ8hs2rnEeA4H0csQDOMyfGDhDDy1Y/edit#gid=0
no mappings, no extensions, no 'with'

**Comment by pgaudet** [comment]
@krchristie Would you please close the dispute for Q3UK78?

**Comment by pgaudet** [comment]
@ARUK-UCL - should be "random X chromosome inactivation"

**Comment by RLovering** [comment]
UCL done

**Comment by krchristie** [comment]
> @krchristie Would you please close the dispute for Q3UK78 and Q8BTQ0 in PMID:28596365?

done
