### ISSUE TITLE
Review annotations to GO:0060465 pharynx development & GO:0043282 pharyngeal muscle development

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4715]
Dear all, 

The proposal has been made to obsolete GO:0060465 pharynx development and rename GO:0043282 pharyngeal muscle development to chordate pharyngeal muscle development.
see https://github.com/geneontology/go-ontology/issues/18285

Existing annotations should be moved to a new term specific to chordate, insect, or nematode, respectively.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1guIRjix5b112laNkElUgKnFeQc6231XQGtNA-_w3lPo/edit#gid=0

Impacted groups: 
UNIPROT 20
WB 43
MGI 2 
FB 1
UCL 1

Thanks.

**Comment by LiNiMGI** [comment]
waiting for the new term "GO:0160093 chordate pharynx development" to be available in noctua.

**Comment by Antonialock** [comment]
uniprot done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by suzialeksander** [comment]
@raymond91125 what is the current status of this ticket?

**Comment by raymond91125** [comment]
Ontology changes have been made. Annotation review may be kept for tracking workflow. But I don't know that for sure.

**Comment by pgaudet** [comment]
@raymond91125 it looks lke GO:0060465 pharynx development is not obsolete; should it not be?

**Comment by vanaukenk** [comment]
All the WB annotations have been updated to the nematode-specific terms.

@raymond91125

**Comment by suzialeksander** [comment]
@sandraorchard the only remaining annotations are to [GO:0060465](https://www.ebi.ac.uk/QuickGO/term/GO:0060465) from ComplexPortal, please check if these are still valid or if "GO:0160094 nematode pharynx development" should be used.

**Comment by sandraorchard** [comment]
Replaced in the Complex Portal

**Comment by hattrill** [comment]
FB done
