### ISSUE TITLE
InterPro:IPR017072 not 'regulation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4717]
* **InterPro ID / label**

InterPro:IPR017072

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.uniprot.org/uniprotkb/Q09915/entry

Biological Process | positive regulation of transcription elongation by RNA polymerase IISource:InterPro

* **Description of issue**
Follow up from
https://github.com/geneontology/go-annotation/issues/1737

This shouldn't be 'regulation'
It could be
"transcription elongation by RNA polymerase II"
or
even better
[GO:0140673](https://www.ebi.ac.uk/QuickGO/term/GO:0140673)    transcription elongation-coupled chromatin remodeling

**Comment by tony787** [comment]
Dear Val,
Thank you for the suggestion. It aligns well with the findings here PMID: 24100010. 
I have replaced the term in IPR017072.
This will be visible in the next InterPro release.
Best wishes,
Toni
