### ISSUE TITLE
RGD annotations to alternative splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4718]
These 2 annotation to alternative splicing are describing a target of alternative splicing, not  a gene product involved _in alternative splicing:

UniProtKB:A0A0G2K736 | Kdm1a | involved_in | GO:0000380    alternative mRNA splicing, via spliceosome | ECO:0000270   IEP | PMID:20164337 |   | 10116 Rattus norvegicus | RGD |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB:A0A8I6G2K8 | Kdm1a | involved_in | GO:0000380    alternative mRNA splicing, via spliceosome | ECO:0000270   IEP | PMID:20164337 |   | 10116 Rattus norvegicus | RGD

UniProtKB:A0A0G2K736	Kdm1a	involved_in	[GO:0000380](https://www.ebi.ac.uk/QuickGO/term/GO:0000380)    alternative mRNA splicing, via spliceosome	[ECO:0000270](https://www.ebi.ac.uk/QuickGO/term/ECO:0000270)   IEP	PMID:20164337	
10116 Rattus norvegicus	RGD	
UniProtKB:A0A8I6G2K8	Kdm1a	involved_in	[GO:0000380](https://www.ebi.ac.uk/QuickGO/term/GO:0000380)    alternative mRNA splicing, via spliceosome	[ECO:0000270](https://www.ebi.ac.uk/QuickGO/term/ECO:0000270)   IEP	PMID:20164337	
10116 Rattus norvegicus	RGD

**Comment by ValWood** [comment]
oddly there are 2 sources:

UniProtKB:B3STT9 | Kdm1a | involved_in | GO:0000380    alternative mRNA splicing, via spliceosome | ECO:0000270   IEP | PMID:20164337 |   | 10116 Rattus norvegicus | RGD
-- | -- | -- | -- | -- | -- | -- | -- | --


UniProtKB:B3STT9	Kdm1a	involved_in	[GO:0000380](https://www.ebi.ac.uk/QuickGO/term/GO:0000380)    alternative mRNA splicing, via spliceosome	[ECO:0000270](https://www.ebi.ac.uk/QuickGO/term/ECO:0000270)   IEP	PMID:20164337	
10116 Rattus norvegicus	RGD

**Comment by ValWood** [comment]
Another:


UniProtKB:P15127 | Insr | involved_in | GO:0000380    alternative mRNA splicing, via spliceosome | ECO:0000270   IEP | PMID:23633480 |   | 10116 Rattus norvegicus | RGD
-- | -- | -- | -- | -- | -- | -- | -- | --


UniProtKB:P15127	Insr	involved_in	[GO:0000380](https://www.ebi.ac.uk/QuickGO/term/GO:0000380)    alternative mRNA splicing, via spliceosome	[ECO:0000270](https://www.ebi.ac.uk/QuickGO/term/ECO:0000270)   IEP	PMID:23633480	
10116 Rattus norvegicus	RGD

**Comment by gthayman** [comment]
Fixed.

**Comment by ValWood** [comment]
speedy! thanks.
