### ISSUE TITLE
Review annotations to GO:0050155 ornithine(lysine) transaminase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4719]
Dear all, 

The proposal has been made to obsolete GO:0050155 ornithine(lysine) transaminase activity
see https://github.com/geneontology/go-ontology/issues/25975. It will be replaced by GO:0004587 ornithine-oxo-acid transaminase activity as both XREF to EC:2.6.1.13. GO:0004587 will be renamed to ornithine aminotransferase activity.

Experimental annotations that need to be reviewed are here: (automatic replacement may be applied)
https://docs.google.com/spreadsheets/d/1Ntdn6DlyF6r4vuCk_gpvWIqkXG830w_iJVAKU1etmCc/edit#gid=0

Impacted groups: 
UniProt 2

----

Thanks.

**Comment by pgaudet** [comment]
Right - terms with REPLACED BY dont need to be updated for groups using Noctua and P2GO
