### ISSUE TITLE
Review annotations to regulation of transcription from RNA polymerase x promoter involved in cell cycle

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4720]
Ontology ticket: https://github.com/geneontology/go-ontology/issues/26002

GO:0010674 | negative regulation of transcription from RNA   polymerase II promoter involved in meiotic cell cycle
GO:0071930 | negative regulation of transcription involved in G1/S transition of   mitotic cell cycle
GO:0090419 | negative regulation of transcription involved in G2/M transition of   mitotic cell cycle
GO:0051038 | negative regulation of transcription involved in meiotic cell cycle
GO:0010673 | positive regulation of transcription from RNA polymerase II promoter   involved in meiotic cell cycle
GO:0007072 | positive regulation of transcription involved in exit from mitosis
GO:0007073 | positive regulation of transcription involved in exit from mitosis, from   RNA polymerase I promoter
GO:0007074 | positive regulation of transcription involved in exit from mitosis, from   RNA polymerase II promoter
GO:0007075 | positive regulation of transcription involved in exit from mitosis, from   RNA polymerase III promoter
GO:0071931 | positive regulation of transcription involved in G1/S transition of   mitotic cell cycle
GO:0090282 | positive regulation of transcription involved in G2/M transition of   mitotic cell cycle
GO:0051039 | positive regulation of transcription involved in meiotic cell cycle
GO:0010672 | regulation of transcription from RNA polymerase II promoter involved in   meiotic cell cycle
GO:0000083 | regulation of transcription involved in G1/S transition of mitotic cell   cycle
GO:0000117 | regulation of transcription involved in G2/M transition of mitotic cell   cycle
GO:0051037 | regulation of transcription involved in meiotic cell cycle

Annotations are here: https://docs.google.com/spreadsheets/d/1ctk_ArpXgEJQboPxn_uK74VOWxjepCodmzCfhF_otuQ/edit#gid=0

- 145 annotations + 3 extensions]
- 1 InterPro mapping

assigned_by
--
BHF-UCL | 3
CGD | 6
ComplexPortal | 6
FlyBase | 4
MGI | 4
PomBase | 20
RGD | 1
SGD | 92 - DONE
UniProt | 11 - DONE

**Comment by pgaudet** [comment]
@srengel Can these be captured as extensions, or do we need new terms, or modify the current ones? 

Thanks, Pascale

**Comment by srengel** [comment]
hi @pgaudet yes we'll try to clean these up with curation (ex. extensions, etc.) instead of requesting new terms or modifications.

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
InterPro:IPR039198

How about changing mappings to 
GO:0001227 'DNA-binding transcription repressor activity, RNA polymerase II-specific'
and GO:0000082  G1/S transition of mitotic cell cycle

@blazaropinto @sarach06

**Comment by hattrill** [comment]
FB done

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much. Yes, I agree. I replaced the term and added the two you suggested. These changes will be visible in InterPro 97.0.
Best wishes,
Sara

**Comment by ValWood** [comment]
Pombase done

**Comment by jlewsmith** [comment]
CGD done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by gthayman** [comment]
RGD done.

**Comment by RLovering** [comment]
UCL done

**Comment by sandraorchard** [comment]
Complex Portal done
