### ISSUE TITLE
Review annotations to regulation of transcription from RNA polymerase II promoter in response  to stress 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4722]
Ontology ticket: https://github.com/geneontology/go-ontology/issues/26004

GO:0043620 | regulation of DNA-templated transcription in response to stress
GO:0010689 | negative regulation of ribosomal protein gene transcription from RNA polymerase II promoter in response to chemical stimulus
GO:0010690 | negative regulation of ribosomal protein gene transcription from RNA polymerase II promoter in response to stress
GO:0010691 | negative regulation of ribosomal protein gene transcription from RNA polymerase II promoter in response to nutrient levels
GO:0010723 | positive regulation of transcription from RNA polymerase II promoter in response to iron
GO:0033217 | regulation of transcription from RNA polymerase II promoter in response to iron ion starvation
GO:0034395 | regulation of transcription from RNA polymerase II promoter in response to iron
GO:0034396 | negative regulation of transcription from RNA polymerase II promoter in response to iron
GO:0036003 | positive regulation of transcription from RNA polymerase II promoter in response to stress
GO:0036086 | positive regulation of transcription from RNA polymerase II promoter in response to iron ion starvation
GO:0036091 | positive regulation of transcription from RNA polymerase II promoter in response to oxidative stress
GO:0043618 | regulation of transcription from RNA polymerase II promoter in response to stress
GO:0043619 | regulation of transcription from RNA polymerase II promoter in response to oxidative stress
GO:0061402 | positive regulation of transcription from RNA polymerase II promoter in response to acidic pH
GO:0061406 | positive regulation of transcription from RNA polymerase II promoter in response to glucose starvation
GO:0061407 | positive regulation of transcription from RNA polymerase II promoter in response to hydrogen peroxide
GO:0061408 | positive regulation of transcription from RNA polymerase II promoter in response to heat stress
GO:0061411 | positive regulation of transcription from RNA polymerase II promoter in response to cold
GO:0061417 | negative regulation of transcription from RNA polymerase II promoter in response to oxidative stress
GO:0061418 | regulation of transcription from RNA polymerase II promoter in response to hypoxia
GO:0061419 | positive regulation of transcription from RNA polymerase II promoter in response to hypoxia
GO:0061428 | negative regulation of transcription from RNA polymerase II promoter in response to hypoxia
GO:0090375 | negative regulation of transcription from RNA polymerase II promoter in response to iron ion starvation
GO:0097201 | negative regulation of transcription from RNA polymerase II promoter in response to stress
GO:1990440 | positive regulation of transcription from RNA polymerase II promoter in response to endoplasmic reticulum stress
GO:1990441 | negative regulation of transcription from RNA polymerase II promoter in response to endoplasmic reticulum stress

**Comment by RLovering** [comment]
Hi Pascale

please would you create the annotation revision table as the github link doesn't seem to be helpful

BTW I have edited 4 UCL annotations associated with the GO term GO:0006978

Thanks

Ruth

**Comment by pgaudet** [comment]
- [ ] InterPro:IPR014842 Iron-regulated transcriptional activator AFT > GO:positive regulation of transcription from RNA polymerase II promoter in response to iron ion starvation ; GO:0036086
- [ ] InterPro:IPR016849 Histone acetyltransferase Rtt109 > GO:regulation of transcription from RNA polymerase II promoter in response to stress ; GO:0043618

**Comment by pgaudet** [comment]
Annotations are here: 
https://docs.google.com/spreadsheets/d/1_sVMhCftgt3C7mQB-PN5zLSEtnL8hFr75EYqGJ05LwQ/edit#gid=0


Group | Number of annotations
-- | --
BHF-UCL | 55
CACAO | 1
CAFA | 2
CGD | 23
ComplexPortal | 1
FlyBase | 2
MGI | 17
MTBBASE | 1
PomBase | 1
RGD | 3
SGD | 8
TAIR | 2
UniProt | 17
WB | 2
ZFIN | 1

**Comment by pgaudet** [comment]
@ValWood @gthayman 
@sarach06 @blazaropinto

**Comment by srengel** [comment]
@jlewsmith  the idea is to change these to "regulation of transcription from RNA polymerase II promoter" and then put "response to stress" in the Annotation Extension.

**Comment by RLovering** [comment]
thanks for the link to google doc

**Comment by srengel** [comment]
SGD done.

**Comment by jlewsmith** [comment]
CGD done
________________________________

**Comment by pgaudet** [comment]
Apologies @jlewsmith 

Looks like you were able to change the annotations; normally we would recommend to use an annotation extension to capture the 'response to stress', if appropriate.

**Comment by sarach06** [comment]
Hi Pascale,
So, for the two InterPro entries, I will remove the terms for now until these ones are fixes, if that's make sense? or is there any other suggestion to map?
Thanks
Sara

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by gthayman** [comment]
RGD done.

**Comment by pgaudet** [comment]
@sarach06 
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR016849
Reading on H3K56, I think this is involved in GO:0140889 DNA replication-dependent chromatin disassembly


https://www.ebi.ac.uk/interpro/entry/InterPro/IPR014842/
I suggest you annotate [positive regulation of transcription by RNA polymerase II](http://purl.obolibrary.org/obo/GO_0045944) and [cellular response to iron ion starvation](http://purl.obolibrary.org/obo/GO_0010106)


Does that work? 

Thanks, Pascale

**Comment by sramachand** [comment]
ZFIN done.

**Comment by pgaudet** [comment]
Remaining annotations: 

Group |  Number of annotations
-- | --
CACAO | 1
ComplexPortal | 1
FlyBase | 2
PomBase | 1
TAIR | 2
UniProt | 16
WB | 2

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
@sarach06 
In fact the term I suggested for https://www.ebi.ac.uk/interpro/entry/InterPro/IPR016849 is too specific, please use the more general [chromatin organization](http://purl.obolibrary.org/obo/GO_0006325)

Thanks, Pascale

**Comment by vanaukenk** [comment]
WB done

**Comment by lreiser** [comment]
TAIR is done

**Comment by pgaudet** [comment]
Terms are obsoleted. Any remaining annotation will appear in GO-RULE reports.
