### ISSUE TITLE
Replace/remove metazoan annotations to GO:0080188 gene silencing by RNA-directed DNA methylation 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4723]
GO:0080188 gene silencing by RNA-directed DNA methylation https://www.ebi.ac.uk/QuickGO/term/GO:0080188

This process has only been shown to occur in plants.

MGI and FlyBase have exp evidenced annotations to mouse and fly genes to this term.

Should be revised -
consider terms under 
regulatory ncRNA-mediated heterochromatin formation GO:0031048
facultative heterochromatin formation GO:0140718

2 annotations for MGI:
Kcnq1ot1 MGI:1926855
PMID:20573698
PMID:15340049

FlyBase:
FBgn0086908	egg	FB:FBrf0230020|PMID:26494711
FBgn0034246	Dcr-2	FB:FBrf0209635|PMID:19948966
FBgn0034617	Panx	FB:FBrf0230020|PMID:26494711
FBgn0004872	piwi	FB:FBrf0230020|PMID:26494711
FBgn0087035	AGO2	FB:FBrf0209635|PMID:19948966
FBgn0263755	Su(var)3-9	FB:FBrf0209635|PMID:19948966
FBgn0031951	r2d2	FB:FBrf0209635|PMID:19948966

**Comment by hattrill** [comment]
All FB revised.

**Comment by krchristie** [comment]
MGI done

**Comment by krchristie** [comment]
@hattrill - Since I'm the last, I'm going to mark this as closed.
