### ISSUE TITLE
PANTHER:PTN007449682  not in yeast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4725]
* **PTHR ID & PTN node:**

* **Sequences with problematic annotation (ID + gene/protein name):**

UniProtKB:O94446 | mst1 | part_of | GO:0072487    MSL complex | ECO:0000318   IBA | PMID:21873635 | FB:FBgn0014340 more... | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | GO_Central

any other fungal annotatiosn to this complex

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation

Reason
MSL complex
Cellular Component
Definition (GO:0072487 GONUTS page)
A histone acetyltransferase complex that catalyzes the acetylation of a histone H4 lysine residue at position 16. In human, it contains the catalytic subunit MOF, and MSL1, MSL2 and MSL3. PMID:16227571 PMID:20018852

MOF= KAT8 (not in yeast)
MSL1,2,3 appear to be metazoan specific

I'll request a taxon restriction

**Comment by marcfeuermann** [comment]
Annotation has been restricted.
