### ISSUE TITLE
Decide where final specs will live, how users should view them, and make sure we clearly deprecate older versions, documentation

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#4727]
Now that the spec for GPAD/GPI 2.0 has been finalized, we need to decide what to do with them for public presentation.

Proposal:

- [x] End-user documentation is added at https://geneontology.org/docs/gene-product-association-data-gpad-format-2_0/, which includes:
- [x]  end-user oriented details, 
- [x] a friendly diff with the current spec(s), 
- [x] and a link to the "real" spec
- [ ] The new spec is linked to the item above in the GO website at https://geneontology.org/docs/go-annotations/, 
- [x] has a note that it is the "upcoming" format

**Comment by suzialeksander** [comment]
Updating this issue as https://geneontology.org/docs/gene-product-association-data-gpad-format-2.0/ is live and presentable, just intentionally not linked anywhere yet

**Comment by pgaudet** [comment]
- [ ] Add a note to refer to go-rules

**Comment by pgaudet** [comment]
Done, see 
https://geneontology.org/docs/go-annotations/
