### ISSUE TITLE
Review annotations to GO:0052590 sn-glycerol-3-phosphate:ubiquinone oxidoreductase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4731]
Hello, 

GO:0052590 sn-glycerol-3-phosphate:ubiquinone oxidoreductase activity will be obsoleted, see https://github.com/geneontology/go-ontology/issues/25984, and replaced by its parent GO:0004368 glycerol-3-phosphate dehydrogenase (quinone) activity. 

There are 2 annotations by Ecocyc to glpD [P13035](https://www.uniprot.org/uniprot/P13035). Please review @amandamackie 

Thanks, Pascale

**Comment by amandamackie** [comment]
I've replaced the EcoCyc annotations with the parent term.

Amanda

**Comment by pgaudet** [comment]
Thanks!
