### ISSUE TITLE
ARBA00035048 ARBA mappings from DEAD box helicases to splicosomal complexes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4733]
* **ARBA rule (ID and label):**
ARBA00035048

* **Sequences with problematic annotation (ID + gene/protein name):**

Pombe genes (and all orthologs in other species)
dhx37 / SPAPB1A10.06c
GO:0005681 spliceosomal complex IEA with ARBA00035048
(Is small subunit processome)

prh1 / SPAC2G11.11c
GO:0005681 spliceosomal complex IEA with ARBA00035048
Definitely not splicing because it's nucleolar

ucp12 / SPCC895.09c
GO:0005681 spliceosomal complex IEA with ARBA00035048
Unknown location but unlikely splicing, more likely other processing

* **Description of issue**
* 
A lot of DEAH box helicases are mapped to spliceosomes. This is because DEAH box helicases are highly similar to each other, but they are involved in different processes.

The spliceosome is very well characterised in many species and it is highly unlikely that this large proteins would be missed.

The S. cerevisiae spliceosome has 4 DEAH box helicases

See
Structure and function of spliceosomal DEAH-box ATPases
PMID: 37441768 
Abstract
Splicing of precursor mRNAs is a hallmark of eukaryotic cells, performed by a huge macromolecular machine, the spliceosome. Four DEAH-box ATPases are essential components of the spliceosome, which play an important role in the spliceosome activation, the splicing reaction, the release of the spliced mRNA and intron lariat, and the disassembly of the spliceosome.

Pombe and human have 5. 

I would be skeptical to any spliceosome predictions for unannotated cerevisiae, pombe or human genes...

cheers,
v

**Comment by PedroRaposo** [comment]
Hi Val,
If I understand the issue, effectively what we want is to do, is to stop the propagation of GO:0005681 (spliceosomal complex) from ARBA00035048 into TrEMBL entries from S. cerevisiae, S. pombe and Human?

**Comment by ValWood** [comment]
Yes, some of these helicases are spliceosomal complex, but many are not.

**Comment by PedroRaposo** [comment]
This has been updated.
