### ISSUE TITLE
Review annotations to GO:0004704 NF-kappaB-inducing kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4736]
Dear all, 

The proposal has been made to obsolete GO:0004704 NF-kappaB-inducing kinase activity
see  https://github.com/geneontology/go-ontology/issues/24418

Experimental annotations that need to be reviewed are here:https://docs.google.com/spreadsheets/d/1LhgdpBmlxQTxuX-XzrvEa5NMkJh5Oyp5Df7k_5LcLEc/edit#gid=0

Impacted groups: 
UniProt : 2

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
No mappings

Thanks.

**Comment by pgaudet** [comment]
Duplicate of https://github.com/geneontology/go-annotation/issues/4692
