### ISSUE TITLE
IPR005517 family  not always  GO:0003746 | translation elongation factor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4738]
* **InterPro ID / label**

IPR005517 

* **Example sequences with problematic annotation (ID + gene/protein name):**

cwf10 | GO:0003746 | translation elongation factor activity | IEA with IPR005517

* **Description of issue**

cwf10 is
U5 snRNP GTPase subunit Cwf10
see https://www.pombase.org/gene_subset/interpro:IPR005517

**Comment by tony787** [comment]
Dear Val, thank you for pointing this. 
It is indeed problematic. Cwf10 structure was determined as a part of the yeast spliceosome https://doi.org/10.1126/science.aac7629 and it is the only GTPase in the spliceosomal complex. Cwf10 is homologous to elongation factors EFG/EF2 but functionally diverged. 
I have removed the associated problematic GO term. This change will appear in the next InterPro release.
Best wishes,
Toni
