### ISSUE TITLE
Review annotations to GO:0044081 symbiont-mediated suppression of host nitric oxide-mediated signaling 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4741]
Dear all, 
GO:0044081 symbiont-mediated suppression of host nitric oxide-mediated signaling 

see https://github.com/geneontology/go-ontology/issues/25988

Thanks.

**Comment by pgaudet** [comment]
4 annotations by GeneDB from the same paper, PMID:19797268. 

The effect on NO seems to be a downstream effect of the perturbation by Leishmania of host PTP1B signaling  , which is already captured by the annotation to [perturbation of host signal transduction pathway](https://amigo.geneontology.org/amigo/term/GO:0052027). I suggest removing these annotations. 

Thanks, Pascale

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
