### ISSUE TITLE
Review annotations to GO:0052163 'symbiont defense to host-produced nitric oxide'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4742]
Dear all, 

We propose to obsolete 
GO:0052163 'symbiont defense to host-produced nitric oxide'

see https://github.com/geneontology/go-ontology/issues/25988

**Comment by pgaudet** [comment]
2 CGD annotations and 1 Reactome model need to be reviewed, see 
https://docs.google.com/spreadsheets/d/1yAL2TcRAm4mRhM5hpRggxEBM_XRrU6fadyQ8MnlfOz8/edit#gid=0

**Comment by pgaudet** [comment]
Hi @deustp01 

In the [spreadsheet](https://docs.google.com/spreadsheets/d/1yAL2TcRAm4mRhM5hpRggxEBM_XRrU6fadyQ8MnlfOz8/edit#gid=0) I suggest replacement by [cellular detoxification of nitrogen compound](https://amigo.geneontology.org/amigo/term/GO:0070458) but looking more closely, you probably want 'symbiont-mediated detoxification of host-generated reactive oxygen species'?

**Comment by deustp01** [comment]
Reactome fixed - change will become visible with December 2023 release

**Comment by jlewsmith** [comment]
CGD done
________________________________

**Comment by jlewsmith** [comment]
CGD done
