### ISSUE TITLE
Review annotations to GO:0004809 tRNA (guanine-N2-)-methyltransferase activity & GO:0016429 tRNA (adenine-N1-)-methyltransferase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4743]
Dear all, 

The proposal has been made to obsolete 
GO:0004809 tRNA (guanine-N2-)-methyltransferase activity
GO:0016429 tRNA (adenine-N1-)-methyltransferase activity
see https://github.com/geneontology/go-ontology/issues/26104
For the corresponding EC terms have been replaced by new ones.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1XsyLzvH5MRd1LqUQRLw1J_7dpgtlpYQs4zov0nyCVcA/edit#gid=0

Impacted groups: 
FlyBase 1
Reactome 1
PomBase 2
MTBBASE 1
CAFA 1
ComplexPortal 3
SGD 9
UniProt 7

[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

----

Mappings that need to be reviewed: none

Thanks.

**Comment by hattrill** [comment]
@sjm41 tagging you and thought you'd be best placed to do this. Terms not available in P2GO yet, so have to wait for a bit.

**Comment by ValWood** [comment]
PomBase done, the terms are now available in Canto, so presumably in Protein2GO too.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by pgaudet** [comment]
Hi, 

Some annotations from InterProt, UniRules/HAMAP, Reactome and SGD remain, see https://docs.google.com/spreadsheets/d/1XsyLzvH5MRd1LqUQRLw1J_7dpgtlpYQs4zov0nyCVcA/edit#gid=0

I've added suggestions. 
Thanks

@pedruzzi @srengel @sarach06 @blazaropinto @deustp01

**Comment by deustp01** [comment]
Reactome done

**Comment by srengel** [comment]
SGD done.

**Comment by blazaropinto** [comment]
Thank you Pascale, these GO terms are updated in the mentioned InterPro entries.
Best,
Beatriz

**Comment by pgaudet** [comment]
Terms have been obsoleted, the annotations will show up in GO rules error reports.
