### ISSUE TITLE
IPR019807 Hexokinase, binding site

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4747]
* **InterPro ID / label**
IPR019807 Hexokinase, binding site

* **Description of issue**
This is described as a substrate-binding site rather than a catalytic site, so remove "hexokinase activity (GO:0004396)"?

**Comment by sarach06** [comment]
Hi Steven,
Yes you are right. I removed the term from this entry; it will be visible in InterPro 97.0.
Best,
Sara
