### ISSUE TITLE
Annotations should be deleted since new evidences show a different catalytic activity for Q8TCG5  and orthologs.

### ISSUE THREAD

**Issue by ccasalsc** [geneontology/go-annotation#4748]
PANTHER:PTN001097100|RGD:2396|UniProtKB:P50416

Q8TCG5 and orthologs

erroneous propagation: 
It seems that this paralog doesn't have this activity and neither is located in the mitochondrion but in the endoplasmic reticulum where it has a GO:0008474 palmitoyl-(protein) hydrolase activity
PubMed=12376098
PubMed=24222496
PubMed=30135643
even if in the paper: 18192268, the authors see some activity when overexpressed but
the some of the authors wrote later in a review: PubMed=26708865
'CPT1C binds to palmitoyl-CoA as CPT1A and CPT1B, its CPT1 catalytic activity is 100-fold lower than other CPT1s. it is specifically expressed in neurons (a cell-type that does not use fatty acids as fuel to any major extent), it is localized in the endoplasmic reticulum of cells, and it has minimal CPT1 catalytic activity with l-carnitine and acyl-CoA esters.'
Thank you to have a look and correct the annotations if you agree.

**Comment by marcfeuermann** [comment]
Thanks for the detailed information. Corrected.
