### ISSUE TITLE
IPR000387, IPR020422, IPR000340, IPR016130

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4749]
* **InterPro ID / label**
Domains:
Tyrosine-specific protein phosphatases domain (IPR000387)
|_Dual specificity protein phosphatase domain (IPR020422)
|_Dual specificity phosphatase, catalytic domain (IPR000340)

Site:
Protein-tyrosine phosphatase, active site (IPR016130)

* **Example sequences with problematic annotation (ID + gene/protein name):**
D. melanogaster mRNA-cap (mRNA-capping-enzyme) = Q9VY44
Human MCE1 (mRNA-capping enzyme) aka RNGTT = O60942

* **Description of issue**
The 4 InterPro entries above are all associated with "phosphatase activity (GO:0016791)" (=EC:3.1.3.-) or it's child term "protein tyrosine/serine/threonine phosphatase activity (GO:0008138)"
However, all these signatures are found in the mRNA-capping-enzyme (e.g. Q9VY44, O60942), which is characterized as having "mRNA 5'-phosphatase activity (GO:0140818) (=EC:3.6.1.74)", which is a "pyrophosphatase activity" (i.e. cleaves the bond between two phosphates) and is classified under a different branch of GO/EC. (See the InterPro family entry IPR017074.)

So, I think the GO annotations on these 4 InterPro entries either need moving up to the common parent (hydrolase activity) or, given that annotation with that high-level GO term isn't very useful, maybe just removing?

**Comment by sarach06** [comment]
Hi Steven,
Thanks a lot for this, I agree with you. I have removed the term from these entries. These changes will be included in InterPro 97.0.
Best regards,
Sara
