### ISSUE TITLE
IPR023267 RNA (C5-cytosine) methyltransferase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4751]
* **InterPro ID / label**
IPR023267 RNA (C5-cytosine) methyltransferase

* **Description of issue**
I think you can add "GO:0008173 RNA methyltransferase activity" to this entry. What do you think?

**Comment by sarach06** [comment]
Hi Steven,
Many thanks for this; yes I agree. I added the term to this entry, which will be available in InterPro 97.0.
Best regards,
Sara
