### ISSUE TITLE
Review annotations to GO:0030242 autophagy of peroxisome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4753]
Dear all, 

The proposal has been made to obsolete GO:0030242 autophagy of peroxisome

see https://github.com/geneontology/go-ontology/issues/25541

Experimental annotations that need to be reviewed are here: 

https://docs.google.com/spreadsheets/d/1-A9RBBAaYI2IOeZ6YIMmKnJqu64KNFHNGTkWzxVnwpA/edit#gid=0 

Impacted groups: 

26 SGD
2 UniProt

----

Mappings that need to be reviewed: 

GO:0030242 | interpro2go | InterPro:IPR016347 Acyl-CoA-binding domain-containing protein 5 > GO:autophagy of peroxisome 

GO:0030242 | pirsf2go | PIRSF:PIRSF002412 MA_DBI 

Thanks.

**Comment by sarach06** [comment]
Hi Val,
Thank you for this. I have changed the term in IPR016347 to GO:0000425 - pexophagy, let me know if you agree. This will be available in InterPro 97.0.

Best regards,
Sara

**Comment by ValWood** [comment]
That seems correct based on "peroxisome receptor for pexophagy but is dispensable for aggrephagy and nonselective autophagy." part of this entry.
In GO pexophagy is defined
"The selective autophagy process in which a peroxisome is degraded by macroautophagy"

so I think that's all good
v

**Comment by srengel** [comment]
trying to fix these SGD ones from autophagy of peroxisome to pexophagy, but P2GO is throwing an erroneous error:
"Annotation failed taxon constraint GO:0006914 (autophagy) and its descendants should ONLY be used with gene products from the taxonomic group Eukaryota"

**Comment by Antonialock** [comment]
uniprot fixed

**Comment by srengel** [comment]
Hi @pgaudet great, thanks!  can you please remove yours for Q12527 so that i can fix the SGD one? because now i'm getting a unique constraint error ("this annotation already exists from 1 source").

**Comment by pgaudet** [comment]
Done @srengel

**Comment by srengel** [comment]
SGD done.

**Comment by suzialeksander** [comment]
The corresponding ontology ticket has been closed and all requested annotations have been reviewed, however the term is not obsolete.  @ValWood is there anything else needed on this ticket

**Comment by ValWood** [comment]
For some reason I missed that one.
Will do next week
https://github.com/geneontology/go-ontology/issues/28542
