### ISSUE TITLE
Review annotations to GO:0061726 mitochondrion disassembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4755]
Dear all, 

The proposal has been made to obsolete GO:0061726 mitochondrion disassembly
see [https://github.com/geneontology/go-ontology/issues/25541

There are no experimental annotations

Thre are no mappings

Thanks.

**Comment by ValWood** [comment]
Hi, Ruth, no there is a slight change of plan. I was concerned not to have a parentage to  group under "mitochondrial processes" and so, I will keep 
"autophagy of the mitochondrion", with the "mitochondrion organization" parent
even though "mitochondrial organization is slightly incorrect (this is degradation, not disassembly, and so it isn't really 'organization'.

If we remove this it will need to be replaced by something which groups all the aspects of mitochondrial "homeostasis" .
Was that your concern ?

(I will make "mitochondrial disassembly" and it's current exact  "mitochondrial degradation" synonym 
and add a "do not annotate" flag , as all annotation should go to one of the "autophagy" terms. Do you agree?)

**Comment by RLovering** [comment]
Hi Val

that sounds good to me. btw mitochondrial homeostasis sounds good

Ruth
