### ISSUE TITLE
 Piccolo NuA4 histone acetyltransferase complex | IEA with IPR024943

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4757]
* **InterPro ID / label**

GO:0032777 | Piccolo NuA4 histone acetyltransferase complex | IEA with IPR024943

* **Example sequences with problematic annotation (ID + gene/protein name):**

epl1 
https://www.pombase.org/gene/SPCC830.05c

* **Description of issue**

pombe (and likely other test) do not have Piccolo complex which is a  submodule of NuA4 histone acetyltransferase complex  that can function independently in S. cereviaie.

You can re-map to GO:0035267 | NuA4 histone acetyltransferase complex

see
https://github.com/geneontology/go-ontology/issues/26138

**Comment by blazaropinto** [comment]
Hi Val,

Many thanks for that. I removed GO:0032777 from the entry. The changes will be available in the next InterPro release.

Best,
Beatriz
