### ISSUE TITLE
Review annotations to GO:0090305 nucleic acid phosphodiester bond hydrolysis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4765]
Dear all,

The proposal has been made to obsolete GO:0090305 nucleic acid phosphodiester bond hydrolysis
see https://github.com/geneontology/go-ontology/issues/26133

Impacted groups:
   ~1 BHF-UCL auto~
   ~3 CAFA auto~
   ~EcoCyc~ DONE
   ~1 FlyBase auto~
   ~6 GOC~
   ~1 MGI auto~
   ~1 MTBBASE auto~
   1 TAIR 
  ~10 UniProt auto~
   ~1 ZFIN auto~
Annotation will migrate to the parent 
GO:0090304   nucleic acid metabolic process
but you could check if an appropriate MF term is present.

**Annotations are here https://docs.google.com/spreadsheets/d/1KQ7FWrT933EIoPbz3_jiOS0r5DNBGj-J_HP0H4oWG0w/edit#gid=0**

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule)

| GO:0090305 | hamap2go | HAMAP:MF_04009 
| GO:0090305 | interpro2go | InterPro:IPR010584 
| GO:0090305 | interpro2go | InterPro:IPR016368 
| GO:0090305 | interpro2go | InterPro:IPR018669 
| GO:0090305 | interpro2go | InterPro:IPR019064 
| GO:0090305 | interpro2go | InterPro:IPR026770 
| GO:0090305 | interpro2go | InterPro:IPR046390 
| GO:0090305 | pirsf2go | PIRSF:PIRSF002882 
| GO:0090305 | unirule2go | UniRule:UR000100329 
| GO:0090305 | unirule2go | UniRule:UR000281433 
| GO:0090305 | pfam2go | Pfam:PF06630 
| GO:0090305 | pfam2go | Pfam:PF09564 
| GO:0090305 | pfam2go | Pfam:PF09907 

Thanks.

**Comment by ValWood** [comment]
@pgaudet
  I don't know if I need to tag MTBBASE or if they will automigrate
 I don't know who to tag for PIRSF or HAMAP, I could not find them here: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by pgaudet** [comment]
@ValWood MTBBASE is updated automatically, as it is now an internal P2GO source.

 you can check here: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
Would it be helpful if we added which curation tool each group uses?

**Comment by pgaudet** [comment]
PRISF are automatically generated from InterPro, see file header: 
http://snapshot.geneontology.org/ontology/external2go/pirsf2go

I made a note to myself to improve the documentation
Maybe we can also exclude these from the reports.

**Comment by ValWood** [comment]
Hi @tberardini @blazaropinto  I will go ahead an obsolete this today if that is OK.
You only need to migrate to the parent.
v

**Comment by tberardini** [comment]
Finally got to this. TAIR done.

**Comment by pgaudet** [comment]
Obsoletion done. 

Errors will appear in reports.
