### ISSUE TITLE
Review annotations to GO:0022889 serine transmembrane transporter activity

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#4767]
Dear all, 

The proposal has been made to obsolete GO:0022889 serine transmembrane transporter activity see https://github.com/geneontology/go-ontology/issues/26052

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1aA9E4XeJRGI7GYYj4Cqx-ikM5gZV070pw5y-c5D3D1g/edit?usp=sharing

Impacted groups:  
1 ARK-UCL
3 UniProt

----

Mappings that need to be reviewed: 
term	file	line
GO:0022889	rhea2go	RHEA:35031 > GO:serine transmembrane transporter activity ; GO:0022889
GO:0022889	interpro2go	InterPro:IPR023726 Threonine/serine transporter TdcC > GO:serine transmembrane transporter activity ; GO:0022889

GO:0022889 should be replaced directly with GO:0015194.

Thanks.

**Comment by RLovering** [comment]
UCL done

**Comment by blazaropinto** [comment]
Thank you for that, the term is updated in InterPro as well.
Best,

**Comment by pgaudet** [comment]
All done
