### ISSUE TITLE
CC2D1B annotation review (not a transcription factor/transcription regulator)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4768]
CC2D1B is an accessory factor for NE localized ESCRT III

Old annotations for this publication  (Freud-2)
https://pubmed.ncbi.nlm.nih.gov/12917378/ (only cited twice)
should probably be reviewed and removed (and flagged as not for GO annotation)

(or minimally should not be PAINT propagated)

See
https://pubmed.ncbi.nlm.nih.gov/33349255/
Lethal (2) giant discs (Lgd)/CC2D1 is required for the full activity of the ESCRT machinery

and
https://pubmed.ncbi.nlm.nih.gov/30513301/
CC2D1B Coordinates ESCRT-III Activity during the Mitotic Reformation of the Nuclear Envelope

Tagging @LiNiMGI  since the original annotation comes from mouse for feedback.

I came across  it whilst checking
https://www.pombase.org/reference/PMID:37783794 submission

**Comment by ValWood** [comment]
Unirpot KW annotation also need reviewing.
Tip: Follow the Reactome annotation
@Antonialock

**Comment by LiNiMGI** [comment]
Karen, would you please help with this? thanks! @krchristie

**Comment by Antonialock** [comment]
On a quick look I'm not sure the transcriptional function should be removed, there is a later and more highly cited paper for that function, and perhaps the protein has different functions (it is alternatively spliced too). 

But yes at the minimum the ESCRT related function should be annotated...
I passed the request on to David Carpentier (new starter at UniProt). Vesicle transport is his area.

**Comment by ValWood** [comment]
OK, I flagged this because it's a C2 domain protein, and I don't know of any case where C2  domain is a transcription factor (it's usually membrane targeting), and I don't see a recognisable DNA binding domain. Although it is possible there is  a DNA binding domain  in there somewhere, and that C2 has other roles so you can ignore this one if there is additional support.

**Comment by ValWood** [comment]
Can you pop the paper in here for future reference, all of the papers I see in the last few years are about membrane sealing after mitosis, and its role in the ESCRTIII machinery.

**Comment by Antonialock** [comment]
PMID: 19423080
Conclusions: Human Freud-2 binds to the 5-HT1A DRE and represses the human 5-HT1A receptor gene to regulate its expression in non-serotonergic cells and neurons.

**Comment by Antonialock** [comment]
and
PMID: 21155902
aken together, these data show that Freud-2 is the second component that, with Freud-1, mediates dual repression of the 5-HT1A receptor gene at the DRE.

**Comment by ValWood** [comment]
hmmmm. OK. I'm getting tonnes of red flags from these abstracts and the papers but then  I'm not a neuroscientist so I might be missing something. These wouldn't pass the bar for a yeast paper that's for sure.
I have asked an ESCRT II expert, and I'll delete this comment but provide feedback if I get any further info.

**Comment by krchristie** [comment]
It is clear that Cc2d1b DOES have a role in the endocytic pathway and I will make annotations for mouse from this paper: 

> Drusenheimer N, et al. **The Mammalian Orthologs of Drosophila Lgd, CC2D1A and CC2D1B, Function in the Endocytic Pathway, but Their Individual Loss of Function Does Not Affect Notch Signalling.** PLoS Genet. 2015 Dec 31; 11(12) PMID:26720614

However, I agree with @Antonialock that it does not appear appropriate to remove transcription annotations at this point in time. There are several papers on the transcriptional repressor role of Freud2 (aka Cc2d1b) and numerous papers on a similar role for the related protein Freud1 (aka Cc2d1ba) in the mammalian species humans, rats, and mice.  Here are results from searches for Freud2 (aka Cc2d1b) and Freud1 (aka Cc2d1ba) in PubMed:

**"Freud2" (aka Cc2d1b) search:**

> 1: Kondaurova EM, et al.  5-HT1A receptor gene silencers Freud-1 and Freud-2 are differently expressed in the brain of rats with genetically determined high level of fear-induced aggression or its absence. Behav Brain Res. 2016 Sep 1 310:20-5. PMID:27150226
> 
> 2: Hadjighassem MR, Galaraga K, Albert PR. Freud-2/CC2D1B mediates dual repression of the serotonin-1A receptor gene. Eur J Neurosci. 2011 Jan 33(2):214-23. PMID:21155902
> 
> 3: Hadjighassem MR, et al.  Human Freud-2/CC2D1B: a novel repressor of postsynaptic serotonin-1A receptor expression. Biol Psychiatry. 2009 Aug 1 66(3):214-22. PMID:19423080
> 
> 4: Rogaeva A, Galaraga K, Albert PR. The Freud-1/CC2D1A family: transcriptional regulators implicated in mental retardation. J Neurosci Res. 2007 Oct 85(13):2833-8. PMID:17394259


**"Freud1" (aka Cc2d1a) search:**

> 1: Belokopytova II, et al. Effects of the Cc2d1a/Freud-1 Knockdown in the Hippocampus of BTBR Mice on the Autistic-Like Behavior, Expression of Serotonin 5-HT<sub>1A</sub> and D2 Dopamine Receptors, and CREB and NF-kB Intracellular Signaling. Biochemistry (Mosc). 2022 Oct;87(10):1206-1218. PMID:36273889
> 
> 2: Miyagishi H, et al. Possible role of transcriptional regulation of 5-HT<sub>1A</sub> receptor in the midbrain on unadaptation to stress in mice. Brain Res. 2022 May 15;1783:147859. PMID:35245487
> 
> 3: Kondaurova EM, et al. Effects of a <i>Cc2d1a/Freud-1 Knockdown</i> in the Hippocampus on Behavior, the Serotonin System, and BDNF. Int J Mol Sci. 2021 Dec 11;22(24):13319. PMID:34948116
> 
> 4: Kondaurova EM, et al. Genetic Background Underlying 5-HT<sub>1A</sub> Receptor Functioning Affects the Response to Fluoxetine. Int J Mol Sci. 2020 Nov 20;21(22):8784. PMID:33233644
> 
> 5: Kumar S, et al. Coiled-Coil and C2 Domain-Containing Protein 1A (CC2D1A) Promotes Chemotherapy Resistance in Ovarian Cancer. Front Oncol. 2019 Oct 1;9:986. PMID:31632917
> 
> 6: Vahid-Ansari F, et al. Abrogated Freud-1/Cc2d1a Repression of 5-HT1A Autoreceptors Induces Fluoxetine-Resistant Anxiety/Depression-Like Behavior. J Neurosci. 2017 Dec 6;37(49):11967-11978. PMID:29101244
> 
> 7: Souslova T, et al. Recruitment by the Repressor Freud-1 of Histone Deacetylase-Brg1 Chromatin Remodeling Complexes to Strengthen HTR1A Gene Repression. Mol Neurobiol. 2017 Dec;54(10):8263-8277. PMID:27914010
> 
> 8: Kondaurova EM, et al. 5-HT1A receptor gene silencers Freud-1 and Freud-2 are differently expressed in the brain of rats with genetically determined high level of fear-induced aggression or its absence. Behav Brain Res. 2016 Sep 1;310:20-5. PMID:27150226
> 
> 9: Szewczyk B, et al. Stress-induced alterations in 5-HT1A receptor transcriptional modulators NUDR and Freud-1. Int J Neuropsychopharmacol. 2014 Nov;17(11):1763-75. PMID:24946016
> 
> 10: Adeosun SO, et al. 17β-estradiol-induced regulation of the novel 5-HT1A-related transcription factors NUDR and Freud-1 in SH SY5Y cells. Cell Mol Neurobiol. 2012 May;32(4):517-21. PMID:22328058
> 
> 11: Hadjighassem MR, et al. Freud-2/CC2D1B mediates dual repression of the serotonin-1A receptor gene. Eur J Neurosci. 2011 Jan;33(2):214-23. PMID:21155902
> 
> 12: Naumenko VS, et al. [On the role of selective silencer Freud-1 in the regulation of the brain 5-HT(1A) receptor gene expression]. Mol Biol (Mosk). 2010 Sep-Oct;44(5):898-903. Russian. PMID:21090244
> 
> 13: Szewczyk B, et al. Decreased expression of Freud-1/CC2D1A, a transcriptional repressor of the 5-HT1A receptor, in the prefrontal cortex of subjects with major depression. Int J Neuropsychopharmacol. 2010 Sep;13(8):1089-101. PMID:20392296
> 
> 14: Kieran N, et al. Chronic social defeat downregulates the 5-HT1A receptor but not Freud-1 or NUDR in the rat prefrontal cortex. Neurosci Lett. 2010 Jan 29;469(3):380-4. PMID:20026183
> 
> 15: Iyo AH, et al. Differential regulation of the serotonin 1 A transcriptional modulators five prime repressor element under dual repression-1 and nuclear-deformed epidermal autoregulatory factor by chronic stress. Neuroscience. 2009 Nov 10;163(4):1119-27. PMID:19647046
> 
> 16: Hadjighassem MR, et al. Human Freud-2/CC2D1B: a novel repressor of postsynaptic serotonin-1A receptor expression. Biol Psychiatry. 2009 Aug 1;66(3):214-22. PMID:19423080
> 
> 17: Rogaeva A, et al. The Freud-1/CC2D1A family: transcriptional regulators implicated in mental retardation. J Neurosci Res. 2007 Oct;85(13):2833-8. PMID:17394259
> 
> 18: Rogaeva A, Albert PR. The mental retardation gene CC2D1A/Freud-1 encodes a long isoform that binds conserved DNA elements to repress gene transcription. Eur J Neurosci. 2007 Aug;26(4):965-74. PMID:17714190
> 
> 19: Rogaeva A, et al. Differential repression by freud-1/CC2D1A at a polymorphic site in the dopamine-D2 receptor gene. J Biol Chem. 2007 Jul 20;282(29):20897-905. PMID:17535813
> 
> 20: Albert PR, Lemonde S. 5-HT1A receptors, gene repression, and depression: guilt by association. Neuroscientist. 2004 Dec;10(6):575-93. PMID:15534042
> 
> 21: Lemonde S, et al. Cell type-dependent recruitment of trichostatin A-sensitive repression of the human 5-HT1A receptor gene. J Neurochem. 2004 Feb;88(4):857-68. PMID:14756806
> 
> 22: Ou XM, et al. Freud-1: A neuronal calcium-regulated repressor of the 5-HT1A receptor gene. J Neurosci. 2003 Aug 13;23(19):7415-25. PMID:12917378

**Comment by ValWood** [comment]
It seems too early to rule anything out.

This protein has multiple seemingly conflicting roles, here is a useful review:
https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3

So far, the information about the function of Lgd in mammals is confusing and points to a variety of functions.

"The most surprising function of LGD1/CC2D1A and LGD2/CC2D1B is the one as a transcriptional repressor that represses the expression of serotonin-1A auto-receptors. This finding provides a molecular link of both genes to depression and anxiety (Ou et al. [2003](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR46); Rogaeva et al. [2007](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR48); Hadjighassem et al. [2009](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR25); Vahid-Ansari et al. [2017](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR67)). The DNA-binding activity of LGD2/CC2D1a has not been determined, but the linker region that connects DM14–4 with the C2 domain was predicted to fold in a HLH conformation typical for bHLH transcription factors (Ou et al. [2003](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR46))."

(All seem to be from a single lab so far)

So, if these are good DNA binding TF experiments, all is OK for now (I wasn't sure about this because they seem to use the promoter fragments from the genes of interest, but no control?).

**Comment by krchristie** [comment]
> It seems too early to rule anything out.

Agreed!!
 
> This protein has multiple seemingly conflicting roles, here is a useful review: https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3
> 
> So far, the information about the function of Lgd in mammals is confusing and points to a variety of functions.
> 
> "The most surprising function of LGD1/CC2D1A and LGD2/CC2D1B is the one as a transcriptional repressor that represses the expression of serotonin-1A auto-receptors. This finding provides a molecular link of both genes to depression and anxiety (Ou et al. [2003](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR46); Rogaeva et al. [2007](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR48); Hadjighassem et al. [2009](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR25); Vahid-Ansari et al. [2017](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR67)). The DNA-binding activity of LGD2/CC2D1a has not been determined, but the linker region that connects DM14–4 with the C2 domain was predicted to fold in a HLH conformation typical for bHLH transcription factors (Ou et al. [2003](https://link.springer.com/chapter/10.1007/978-3-030-55031-8_3#ref-CR46))."

Some of the conflicts appear to be differences between taxa. The role of Lgd in Drosophila with respect to Notch signaling does not appear to be conserved in mammals based on work in mice, rats, and humans. There is a discrepancy between humans and mice regarding whether CC2D1A is involved in the centrosome cycle, though the experiment suggesting that it is involved was done by overexpression in HeLa cells.


> 
> (All seem to be from a single lab so far)
> 
> So, if these are good DNA binding TF experiments, all is OK for now (I wasn't sure about this because they seem to use the promoter fragments from the genes of interest, but no control?).

There are certainly a number of papers from  the same lab, but I didn't look at all 22 of the papers that came up in the search for "Freud1" to see if they are all from the same lab. Regarding the quality of the DNA binding experiments, I thought the ones in one of the previously annotated papers I read (Hadjighassem et al. 2011) seemed fine. In any case, with the number of published papers on the transcriptional role  of Freud1 (aka Cc2d1a), I will not be removing annotations to a transcriptional regulatory role for either Cc2d1a or Cc2d1b at this time.

I have annotated the Drusenheimer paper with annotations about the role of Cc2d1a and Cc2d1b in the endocytic pathway, as well as with some NOT annotations to help prevent inappropriate propagations.

> Hadjighassem MR, Galaraga K, Albert PR. Freud-2/CC2D1B mediates dual repression of the serotonin-1A receptor gene. Eur J Neurosci. 2011 Jan 33(2):214-23. PMID:21155902
> 
> Drusenheimer N, et al. The Mammalian Orthologs of Drosophila Lgd, CC2D1A and CC2D1B, Function in the Endocytic Pathway, but Their Individual Loss of Function Does Not Affect Notch Signalling. PLoS Genet. 2015 Dec 31; 11(12) PMID:26720614

**Comment by ValWood** [comment]
Great, thanks Karen. We can close this one! It might be useful, based on Karen's last comment to flag this family as "NOT for PAINT ing" for the time being @marcfeuermann @pgaudet  is that possible?

**Comment by krchristie** [comment]
> Great, thanks Karen. We can close this one! It might be useful, based on Karen's last comment to flag this family as "NOT for PAINT ing" for the time being @marcfeuermann @pgaudet is that possible?

@ValWood - I don't know that I would flag this family as not for PAINT. Based on what I've read, I think I would want to annotate the family, or relevant branch depending on the structure, with the endosome related terms as that seems to be found in all the studied members, so is likely the ancestral function. Some other terms may still be worth propagation within more limited taxonomic ranges even though they are not appropriate for propagation across the entire range that the endosome terms should be propagated across.
