### ISSUE TITLE
Review annotations to GO:0070584 mitochondrion morphogenesis 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4775]
Dear all, 

The proposal has been made to obsolete GO:0070584 mitochondrion morphogenesis 
see https://github.com/geneontology/go-ontology/issues/26187

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1KK7eS21Ums_UDvF5OAz5Gx1_81unYhgozJ39_RmcnqI/edit#gid=0

Other annotations will be auto-migrated

Impacted groups: 
CGD 3
GeneDB 2
TAIR 1
MGI 2 (extensions)

Thanks.

**Comment by ValWood** [comment]
Ignore if I assigned you and your annotations are automigrated

**Comment by LiNiMGI** [comment]
MGI done

**Comment by jlewsmith** [comment]
CGD done
________________________________

**Comment by tberardini** [comment]
TAIR done

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
