### ISSUE TITLE
 PTN001127687 not all central plaque of spindle pole body

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4781]
* **PTHR ID & PTN node:**

GO:0005823	
central plaque of spindle pole body
IBA with cam1 , PTN001127687 , S000000313

* **Sequences with problematic annotation (ID + gene/protein name):**
https://www.pombase.org/gene/SPAC29A4.05

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous propagation

When Pik1-D450-mNG was co-imaged with Cam2-mCherry, no co-localization was detected, consistent with Cam2 localizing exclusively to endocytic actin patches in wildtype cells (Fig. S3A) (Sammons et al., 2011).
and PMID:37815455

**Comment by marcfeuermann** [comment]
Very complex family. Corrected.
