### ISSUE TITLE
Review annotations to GO:0038031 non-canonical Wnt signaling pathway via JNK cascade

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4789]
GO:0038031 non-canonical Wnt signaling pathway via JNK cascade

**Comment by pgaudet** [comment]
Annotations are here: 
https://docs.google.com/spreadsheets/d/1fV0DIFbc9FY4tL_5RtvH6G9VtvSJeikCmbfB-mnHi4E/edit

**Comment by pgaudet** [comment]
UniProt done

**Comment by pgaudet** [comment]
@malcolmfisher103 can you please look at the XenBase annotations?

**Comment by malcolmfisher103** [comment]
Xenbase done.
