### ISSUE TITLE
PTN000327581 not regulation of transcription elongation in the GO sense (just major problems with transciption elongation)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4791]
* **PTHR ID & PTN node:**

GO:0032784 | regulation of DNA-templated transcription elongation | IBA with Q96FV9 , PTN000327581

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCP25A2.03

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This is a phenotype.
It *might*  be involved in termination, but likely not.
It is *required* for normal elongation because when mutated mRNA can no longer be exported and everything upstream get compromised.

I have raised Uniprot issues for the primary annotations (including a 1999 annotation to apoptosis, which I'll bet is a readout of some sort because it precedes knowledge of the real role).
(it might be worth checking the other THO/Trex complex subunits aren't annotated to regulation of the upstream processes)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation removed.
