### ISSUE TITLE
PTN000517042  , regulation of transcrption

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4794]
* **PTHR ID & PTN node:**

I wouldn't annotate RITs complex to 

GO:0000122 negative regulation of transcription by RNA polymerase II
IBA with PTN000517042 , P45973 , FBgn0030082

It is part of heterochromatin formation, but heterochromatin is the default, and the transcription would need to be positively activated?

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC18G6.02c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation reviewed,
