### ISSUE TITLE
Annotation review MGI:1914778  Nudt7

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4796]
Hello, 

Working on https://github.com/geneontology/go-ontology/issues/24569, I noticed that some MGI:1914778 annotations to GO:0010945 CoA pyrophosphatase activity should in fact be to GO:0106399 acyl-coenzyme A diphosphatase activity: 

- [ ] [MGI:1914778](http://www.informatics.jax.org/marker/MGI:1914778) - PMID:11415433

Thanks, Pascale

**Comment by ukemi** [comment]
Please see PMID:11415433. The section 'Properties of the enzymatic activity', sentence #3.

CoA pyrophosphatase activity in GO is defined as: Catalysis of the reaction: coenzyme A or its derivatives + H2O = 3',5'-ADP + 4'-phosphopantetheine.

This is what they see in their HPLC analysis of the reaction.

**Comment by deustp01** [comment]
I think that the two GO terms in fact describe the identical molecular function.

[GO:0106399](https://www.ebi.ac.uk/QuickGO/term/GO:0106399)
acyl-coenzyme A diphosphatase activity "an acyl-CoA + H2O = adenosine 3',5'-bisphosphate + an acyl-4'-phosphopantetheine + 2 H+"

[GO:0010945](https://www.ebi.ac.uk/QuickGO/term/GO:0010945)
CoA pyrophosphatase activity "Catalysis of the reaction: coenzyme A or its derivatives + H2O = 3',5'-ADP + 4'-phosphopantetheine."

"Coenzyme A or its derivatives" (GO:0010945) looks to me to be a synonym for "an acyl-CoA" (GO:0106399). And if a a CoA derivative, i.e., an acyl-CoA is hydrolyzed, the acyl moiety it should emerge as acyl-4'-panotheine, I think, so the outputs in the definition of GO:0010945 are too narrow, fitting only the CoA input and not the "or its derivatives" input.

The definition of GO:0010945 is missing the two H+ outputs of GO:0106399 but I think that is an annotation mistake in GO:0010945 - see [RHEA:50044](https://www.rhea-db.org/rhea/50044)

**Comment by kaxelsen** [comment]
The evidence for the two terms is overlapping.

[GO:0106399](https://www.ebi.ac.uk/QuickGO/term/GO:0106399) is based on [PMID:32915949](https://pubmed.ncbi.nlm.nih.gov/32915949/) describing FITM2_HUMAN as acyl-CoA hydrolase ([RHEA:50044](https://www.rhea-db.org/rhea/50044) and children)

[GO:00010945](https://www.ebi.ac.uk/QuickGO/term/GO:00010945) is based on [PMID:16185196](https://pubmed.ncbi.nlm.nih.gov/16185196/) describing NUD19_MOUSE also as acyl-CoA hydrolase ([RHEA:50044](https://www.rhea-db.org/rhea/50044) and children)
It is also based on [PMID:10922370](https://pubmed.ncbi.nlm.nih.gov/10922370/) describing PCD1_YEAST a CoA hydrolase ([RHEA:75715](https://www.rhea-db.org/rhea/75715)) with even higher activity toward CoA disulfide ([RHEA:75719](https://www.rhea-db.org/rhea/75719)).

So, if you want to keep the two GO terms some tidying up of the evidence is needed.

**Comment by pgaudet** [comment]
I created a proper review ticket https://github.com/geneontology/go-annotation/issues/4816
Looking at some papers a bit randomly, it seems like we need to look carefully at Kds/Mms to make sure we get a good picture  of the specificity

**Comment by pgaudet** [comment]
OK, looking at the annotations and the RHEA reactions, I think the merge was the better option.
