### ISSUE TITLE
Review annotations to Wnt pathway involved in x

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4800]
Hi everyone,

Many annotations for Wnt signaling involved in x were fixed in #4681, but a number of terms that the Signaling Working group proposes to obsolete are not in the review: 

GO:1904886 | beta-catenin destruction complex disassembly
GO:0022002 | negative regulation of anterior neural cell fate commitment of the neural plate by Wnt signaling pathway
GO:2000041 | negative regulation of planar cell polarity pathway involved in axis elongation
GO:2000151 | negative regulation of planar cell polarity pathway involved in cardiac muscle tissue morphogenesis
GO:2000162 | negative regulation of planar cell polarity pathway involved in cardiac right atrium morphogenesis
GO:2000168 | negative regulation of planar cell polarity pathway involved in neural tube closure
GO:2000164 | negative regulation of planar cell polarity pathway involved in outflow tract morphogenesis
GO:2000166 | negative regulation of planar cell polarity pathway involved in pericardium morphogenesis
GO:2000149 | negative regulation of planar cell polarity pathway involved in ventricular septum morphogenesis
GO:0003402 | planar cell polarity pathway involved in axis elongation
GO:1904938 | planar cell polarity pathway involved in axon guidance
GO:0061350 | planar cell polarity pathway involved in cardiac muscle tissue morphogenesis
GO:0061349 | planar cell polarity pathway involved in cardiac right atrium morphogenesis
GO:0060775 | planar cell polarity pathway involved in gastrula mediolateral intercalation
GO:0061346 | planar cell polarity pathway involved in heart morphogenesis
GO:0090179 | planar cell polarity pathway involved in neural tube closure
GO:0061347 | planar cell polarity pathway involved in outflow tract morphogenesis
GO:0061354 | planar cell polarity pathway involved in pericardium morphogenesis
GO:0061348 | planar cell polarity pathway involved in ventricular septum morphogenesis
GO:0090082 | positive regulation of heart induction by negative regulation of canonical Wnt signaling pathway
GO:1902844 | positive regulation of spinal cord association neuron differentiation by negative regulation of canonical Wnt signaling pathway
GO:0035593 | positive regulation of Wnt signaling pathway by establishment of Wnt protein localization to extracellular region
GO:2000286 | receptor internalization involved in canonical Wnt signaling pathway
GO:0060901 | regulation of hair cycle by canonical Wnt signaling pathway
GO:2000040 | regulation of planar cell polarity pathway involved in axis elongation
GO:0022002 | negative regulation of anterior neural cell fate commitment of the neural plate by Wnt signaling pathway

**Comment by pgaudet** [comment]
assigned_by | count
-- | -- 
AgBase | 1
BHF-UCL | 37
CACAO | 2
ComplexPortal | 3
FlyBase | 3
MGI | 122
RGD | 1
UniProt | 13
ZFIN | 45
Xenbase | 1


Spreadsheet is here: https://docs.google.com/spreadsheets/d/1q7knmSxkaxX8GSEyx-Z3eH0TVDSjyG0HQQy4HM2F6mE/edit#gid=0

**Comment by deustp01** [comment]
The list is missing at least one Reactome annotation, linking proteins involved in our pathway [R-HSA-4641262](https://reactome.org/content/detail/R-HSA-4641262) "Disassembly of the destruction complex and recruitment of AXIN to the membrane" to GO:1904886 | beta-catenin destruction complex disassembly.

**Comment by pgaudet** [comment]
Are they TASs? Typically we only query EXP.

**Comment by pgaudet** [comment]
@malcolmfisher103

**Comment by slaulederkind** [comment]
RGD annotation fixed.

**Comment by RLovering** [comment]
UCL done

**Comment by hattrill** [comment]
FB done

**Comment by LiNiMGI** [comment]
@pgaudet @hattrill what is recommend term for "planar cell polarity pathway"? any other tickets/links that I can read to get more information? thank you!

**Comment by hattrill** [comment]
Hi @LiNiMGI there are some papers on https://github.com/geneontology/go-ontology/issues/26335 that might be useful. 
 
For the term GO:0060071 Wnt signaling pathway, planar cell polarity pathway the requirement is that it is signaling via the JNK pathway. It may not necessarily be associated with the 'establishment of planar polarity' GO:0001736 which is the term used for cell-cell interactions from transmembrane proteins see https://www.nature.com/articles/nrm.2017.11, so might be good to check that when the annotation was made the curator was not confusing the non-canonical wnt signaling pathway with the establishment of planar polarity by asymmetric localization of membrane proteins that is propagated through a tissue.

**Comment by krchristie** [comment]
> Hi @LiNiMGI there are some papers on [geneontology/go-ontology#26335](https://github.com/geneontology/go-ontology/issues/26335) that might be useful.
> 
> For the term GO:0060071 Wnt signaling pathway, planar cell polarity pathway the requirement is that it is signaling via the JNK pathway. 

@hattrill - I am wondering if it is really true that all planar cell polarity pathway signaling requires the JNK pathway. 
* In the diagram that is included in the ontology ticket you referred to above, the brown box labeled as the Wnt/PCP pathway encloses two pathways, one of which regulates transcription via JUN and the other which regulates the cytoskeleton without the involvement of JUN.
* Also, to me the existing definition's reference doesn't seem to indicate that JNK MUST be involved, only that it is one of the possibilities. 

**Definition:** The series of molecular signals initiated by binding of a Wnt protein to a receptor on the surface of the target cell where activated receptors signal via downstream effectors including C-Jun N-terminal kinase (JNK). In some instances, may be involved in reorganize the cytoskeleton organization and/or in the establishment of planar cell polarity pattern orientation.

> It may not necessarily be associated with the 'establishment of planar polarity' GO:0001736 which is the term used for cell-cell interactions from transmembrane proteins see https://www.nature.com/articles/nrm.2017.11, so might be good to check that when the annotation was made the curator was not confusing the non-canonical wnt signaling pathway with the establishment of planar polarity by asymmetric localization of membrane proteins that is propagated through a tissue.

**Comment by hattrill** [comment]
Hi @krchristie yes, you are correct. Perhaps it is better to focus on the activation of the small G proteins, as that is more the central factor. How about this for the definition?

Definition: The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell resulting in the activation small G proteins such as Rho, Rac, and Cdc42 which, in turn activate effectors including C-Jun N-terminal kinase (JNK) and Rho kinase (Rok) and ending in a change in the transcription of target genes and/or reorganisation of the cytoskeleton. PMID: 23140633.

**Comment by krchristie** [comment]
> Hi @krchristie yes, you are correct. Perhaps it is better to focus on the activation of the small G proteins, as that is more the central factor. How about this for the definition?
> 
> Definition: The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell resulting in the activation small G proteins such as Rho, Rac, and Cdc42 which, in turn activate effectors including C-Jun N-terminal kinase (JNK) and Rho kinase (Rok) and ending in a change in the transcription of target genes and/or reorganisation of the cytoskeleton. PMID: 23140633.

@hattrill  - I'm not as well read on this signaling pathway as you are, but based on the review you took the summary diagram from, I like your proposed definition and think it is a great improvement.

**Comment by hattrill** [comment]
Thanks @krchristie I will add it to the ontology ticket for @pgaudet to update.

**Comment by pgaudet** [comment]
Status Nov 10, 2023

- [ ] CACAO	2
- [ ] ComplexPortal	3
- [ ] MGI	105
- [ ] UniProt	11
- [ ] ZFIN	6

**Comment by pgaudet** [comment]
Let's re-run the query after the next release

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by suzialeksander** [comment]
@pgaudet do want to re-run this spreadsheet?

**Comment by pgaudet** [comment]
replaced by https://github.com/geneontology/go-annotation/issues/5371
