### ISSUE TITLE
PTN008604681 not all signal transduction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4802]
* **PTHR ID & PTN node:**

GO:0007165 | signal transduction | IBA with S000006369 , ZDB-GENE-030131-8783 , MGI:1916831 , 71043 , MGI:97846 , locus:2827916 , DDB_G0269178 , P63000 , 619755 , DDB_G0268622 , I3LVS7 , P60763 , P84095 , MGI:1096342 , DDB_G0280975 , CAL0000192659 , Q8IXI1 , MGI:106211 , FBgn0039532 , FBgn0010341 , WBGene00003239 , P61586 , DDB_G0277869 , P17081 , PTN008604681 , Q8IXI2 , MGI:1931551 , 619921 , P60953 , S000004219 , ZDB-GENE-040322-2 , MGI:97845 , DDB_G0293526 , FBgn0010333 , WBGene00000424 , FBgn0014011

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC320.04c
(ERMES complex subunit)

The S. cerevisiae ortholog of pombe gem1 is SGD:S000000046 which isn't involved in signalling and isn't in the list.
(Quote a fe w GTPases aren't signalling)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
gem1 | ERMES complex GTPase subunit Gem1 |   | actin filament organization |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN008604681UniProtKB:Q9HBH0


also doesn't apply to ERMES

**Comment by marcfeuermann** [comment]
ERMES node reviewed.
