### ISSUE TITLE
 IPR044996 cellular respiration

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4803]
* **InterPro ID / label**

 IPR044996 
* **Example sequences with problematic annotation (ID + gene/protein name):**

coq10 https://www.pombase.org/gene/SPCC16A11.07

* **Description of issue**

Although ubiquinone is 'required'  for cellular respiration, **ubiquinone biosynthesis** isn't  part of respiration  (causally upstream)

**Comment by blazaropinto** [comment]
Thank you so much for this Val. I agree, the term is now removed and the changes will be visible in InterPro 98.0.
Best,
Beatriz
