### ISSUE TITLE
InterPro: IPR002020 &  IPR005809 NOT TCA cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4804]
* **InterPro ID / label**

IPR005809 NOt TCA cycle

* **Example sequences with problematic annotation (ID + gene/protein name):**

acl2
<img width="1052" alt="_______ticket interpro acl2" src="https://github.com/geneontology/go-annotation/assets/7359272/2ae3c4c1-26ef-43b1-b569-2b3ef1758932">

* **Description of issue**

acl2 (not to be confused with the TCA ctrate synthase) 
ACLYis a key enzyme of de novo fatty acid synthesis responsible for generating **cytosolic** acetyl-CoA and oxaloacetate.

The same applies to the TCA cycle mapping  for  IPR005809 for acl1

**Comment by blazaropinto** [comment]
Hi Val,

Thank you very much for this.

I see the first sequence SPAC22A12.16 acts in the cytosol, but I see in [GO:0006099 — tricarboxylic acid cycle](http://www.ebi.ac.uk/QuickGo/GTerm?id=GO:0006099) "In eukaryotes the tricarboxylic acid is confined to the mitochondria." Same happens with human P53396, arabidopsis O80526 and other eukaryotic sequences in this IP entry. So I agree this GO term shouldn't be propagated to these proteins. I'll remove this term, the changes will be visible in InterPro 98.0.

With regard to the second sequence https://www.pombase.org/gene/SPCC1620.08 (O94415), according to Pombase, the homologues are [Saccharomyces](https://www.yeastgenome.org/locus/YGR244C#overview) and [human](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11448) beta subunit of succinyl-CoA ligase, is this right? and Uniprot also says it functions in the citric acid cycle (TCA), locating it in the mitochondria. I'm confused here..

Best regards,

Beatriz

**Comment by ValWood** [comment]
Hi @blazaropinto   it is correct that the TCA cycle occurs in the mitochondria in eukaryotes. The problem is that 
SPAC22A12.16 ATP-citrate synthase subunit 2 is not a TCA cycle gene.
The TCA cycle gene is just "citrate synthase". In pombe this is cit1 https://www.pombase.org/gene/SPAC6C3.04 and this is in the mitochondria as expected.
The family contains 2 members , the ATP citrate synthase (involved in lipid metabolism in the. cytosol) a nd the TCA citrate synthase. See:
https://www.pombase.org/gene_subset/interpro:IPR002020

It is the same situation for 
https://www.pombase.org/gene_subset/interpro:IPR005809
The family encodes 2 members, the TCA cycle component is
https://www.pombase.org/gene/SPCC1620.08

and the other member (acl2)
https://www.pombase.org/gene/SPAC22A12.16
functional with acl1 in the cytoplasm

This is the human acl2
https://www.uniprot.org/uniprotkb/P53396/entry (ACLY)

It seems a shame to lose the mappings on these 2 families. Perhaps they can be rebuilt to split the 2  subfamilies.
This should be possible because in the first case, CDD manages to split them, and in the second case, Gene3D manages to split them.

**Comment by blazaropinto** [comment]
About IPR002020, indeed I had a note to look at the contributing signature PF00285 in Pfam when possible to see how can we fix this for citrate synthases. For now I removed the term [GO:0006099](https://www.ebi.ac.uk/QuickGO/term/GO:0006099) from this big entry and assigned it to its children IPR010109 and IPR024176 (but not to IPR014608). I know this is not perfect but I will try to improve these groupings in the future. 

SPAC22A12.16 (O13907) used to be in IPR005809 (in PANTHER 17.0, the version used in InterPro 96.0 -publicly available now), but the update to PANTHER 18.0 (the version used in InterPro 97.0 -publicly available shortly) means this protein is now predicted to be part of IPR002020. Sorry for the confusion, I should have realised earlier of the mismatch 😅 .

The changes in the GO terms explained above will be visible in InterPro 98.0.

I hope this makes sense, my apologies again.

Best,
Beatriz

**Comment by ValWood** [comment]
Not your fault, I only just noticed these weren't TCA when doing some QC and it took me ages to figure it out-  they have probably been like this for years!

**Comment by blazaropinto** [comment]
Thanks a lot for reporting this Val!
