### ISSUE TITLE
Review annotations to GO:0006378  mRNA polyadenylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4805]
This is a follow-up / reminder from
https://github.com/geneontology/go-annotation/issues/4553
some annotations remain to "mRNA polyadenylation".
I'm creating a new annotation ticket in case there are new  annotations since  the first ticket was way back in April.

Dear all, 

The proposal has been made to obsolete GO:0006378 mRNA polyadenylation
see https://github.com/geneontology/go-ontology/issues/24924

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1SgxLisALlzcXk6GKaIukJ7V-XEKFBcLRIYip0fUmW9s/edit#gid=0
Impacted groups: 
   1 CGD
   2 ComplexPortal
   1 EcoliWiki
   8 FlyBase
  16 GeneDB
   3 SGD
  ~3 TAIR~
  ~17 UniProt~
   1 WB

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

UniRule:UR001229751 > GO:mRNA polyadenylation ; GO:0006378
UniRule:UR001629771 > GO:mRNA polyadenylation ; GO:0006378
InterPro:IPR010206 Poly(A) polymerase I > GO:mRNA polyadenylation ; GO:0006378
InterPro:IPR016706 Cleavage/polyadenylation specificity factor subunit 5 > GO:mRNA polyadenylation ; GO:0006378
InterPro:IPR021605 Pcf11, Clp1-ID > GO:mRNA polyadenylation ; GO:0006378
InterPro:IPR027075 Cleavage and polyadenylation specificity factor subunit 2 > GO:mRNA polyadenylation ; GO:0006378
InterPro:IPR045154 Protein PCF11-like > GO:mRNA polyadenylation ; GO:0006378

Thanks.

**Comment by ValWood** [comment]
Hi everyone, this is the final term for obsoletion in the polyadenylation branch (I hope). It was included in an older obsoletion notice, but it seems that I didn't include the annotations to this term in the spreadsheets.

1 CGD
2 ComplexPortal
1 EcoliWiki
8 FlyBase
16 GeneDB
3 SGD
3 TAIR
17 UniProt
1 WB

and some InterPro and UniRule mappings

**Comment by srengel** [comment]
SGD done.

**Comment by blazaropinto** [comment]
Thanks for this. I updated IPR027075, IPR016706, IPR045154, IPR021605. The changes will be visible in InterPro 98.0.
Best,
Beatriz

**Comment by Antonialock** [comment]
Uniprot done

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by tberardini** [comment]
TAIR done

**Comment by vanaukenk** [comment]
WB done - sorry this one has been done for a while but I forgot to update the spreadsheet and ticket.

**Comment by suzialeksander** [comment]
The related ontology ticket has been closed.  Please check your error reports to find & correct the remaining issues @dsiegele @uliboehme
