### ISSUE TITLE
report-direct-ann-term.yml 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4808]
## Describe the issue/bug

The Github workflow workflows/report-direct-ann-term.yml 
https://github.com/geneontology/go-annotation/actions/runs/6710492686

has failed

**Comment by ValWood** [comment]
I'm not sure, I received a Github workflow message saying 
".github/workflows/report-direct-ann-term.yml: All jobs have failed"
maybe that is normal?

**Comment by kltm** [comment]
I suspect that if you give it no input it likely is.

**Comment by ValWood** [comment]
Ha, I only saw the failed workflow message and didn't link back to the fact that there was no ID in the ticket. Sorry about that!
