### ISSUE TITLE
PTN001906771 not regulation of cell shape

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4810]
* **PTHR ID & PTN node:**

tea1
GO:0008360 | regulation of cell shape | IBA with G5EAY1 , S000001201 , PTN001906771

I can see how the cell end marker tea1 becomes annotated to "regulation of cell shape" because it is 
establishment or maintenance of bipolar cell polarity

but, it isn't really regulating cell shape. In fact, in pombe I'm not even sure cell shape is affected,  cells grow to the same shape and size, but monopolarly rather than bipolarly.

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

**Comment by marcfeuermann** [comment]
Corrected
