### ISSUE TITLE
Issue in PomBase GPI causes issues with NEO pipeline 

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#4811]
In the file https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi.gz, lines like

`PR:000060241	akr1	palmitoyltransferase Akr1		SO:0001217	NCBITaxon:4896	PomBase:SPAC2F7.10	PomBase:SPAC2F7.10.1:pep		UniProtKB:Q09701	go-annotation-summary=palmitoyltransferase Akr1`

generate obo like

```
[Term]
id: PR:000060241
name: akr1 Spom
synonym: "akr1" BROAD []
synonym: "000060241" RELATED []
synonym: "SPAC2F7.10.1:pep" RELATED []
xref: PomBase:SPAC2F7.10.1:pep
is_a: CHEBI:33695 ! information biomacromolecule
relationship: in_taxon NCBITaxon:4896
property_value: https://w3id.org/biolink/vocab/category https://w3id.org/biolink/vocab/MacromolecularMachine
property_value: https://w3id.org/biolink/vocab/category https://w3id.org/biolink/vocab/GeneProduct
relationship: has_gene_template PomBase:SPAC2F7.10
```

Naturally, `xref: PomBase:SPAC2F7.10.1:pep` is not a correctly structured CURIE and fails.

This `:pep` thing occurs nearly 100 times:

```
sjcarbon@moiraine:~/local/src/git/neo[master]$:) zcat mirror/pombase.gpi.gz | grep ":pep" | wc -l
93
```

Tagging @ValWood @kimrutherford @pgaudet @vanaukenk

**Comment by kltm** [comment]
Noting that this will block the NEO pipeline until we have a fixed upstream version or clean a version and point to that in the metadata instead.

**Comment by kimrutherford** [comment]
Sorry about that.

I've made a quick fix to change ":pep" to ".pep" in: https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi.gz

**Comment by kltm** [comment]
Confirming it's gone at our end now too. Thank you!
