### ISSUE TITLE
PTN008735182 regulation or not

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4814]
* **PTHR ID & PTN node:**

GO:0000122 | negative regulation of transcription by RNA polymerase II | IBA with S000004966 , Q969S8 , PTN008735182

* **Sequences with problematic annotation (ID + gene/protein name):**
https://www.pombase.org/gene/SPBC800.03

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This is nucleosome positioning for heterochromatin assembly.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Focused on core function.
