### ISSUE TITLE
Review annotations to GO:0010533 regulation of activation of Janus kinase activity & + and - children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4818]
GO:0010533 regulation of activation of Janus kinase activity
GO:1902569 negative regulation of activation of Janus kinase activity
GO:0010536 positive regulation of activation of Janus kinase activity

7 annotations https://docs.google.com/spreadsheets/d/1XZeBEiXXggw3qkRvFlBgL1DZe_fwgHEbOHsc5S_PEkI/edit#gid=0

**Comment by suzialeksander** [comment]
@pgaudet no clear request here, is this still a valid ticket?

**Comment by pgaudet** [comment]
Yes - this will be obsoleted 

@LiNiMGI Can you please fix the single MGI annotation? [Socs1](https://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1354910)  & PMID:21606371

**Comment by LiNiMGI** [comment]
MGI done.
