### ISSUE TITLE
Review annotations to GO:0018545 NAD(P)H nitroreductase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4819]
Dear all, 

The proposal has been made to obsolete GO:0018545 NAD(P)H nitroreductase activity
see https://github.com/geneontology/go-ontology/issues/23357

This term is being replaced by GO:0046857 oxidoreductase activity, acting on other nitrogenous compounds as donors, with NAD or NADP as acceptor

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1aNk8Q86RJIqPjuZOBYoAgqhR9Gekesk-YzH9ScbSpqk/edit#gid=0

Impacted groups: 
EcoCyc 4

Thanks.

**Comment by amandamackie** [comment]
Reviewed and corrected

**Comment by pgaudet** [comment]
Thanks @amandamackie `
