### ISSUE TITLE
triose phosphate isomerase annotations to GO:0006633

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#482]
I noticed that triose phosphate isomerase, which works at a nexus of biosynthetic pathways including glycolysis and gluconeogenesis, has been assigned to GO:0006633; fatty acid biosynthetic process on the basis of it serving on the path between glycolysis and phosphoglycerol and glycerol biosynthesis and those might lead, in some organisms, not to fatty acid biosynthesis but to acylglycerol \(an ester\) biosynthesis.
The assignment of TPI to GO:0006633 is certainly a step too far in organisms, like archaea, that lack fatty acid biosynthesis.  The term GO:0045017, glycerolipid biosynthetic process, with the two children, GO:0046463,  acylglycerol biosynthetic process, and GO:0006633; fatty acid biosynthetic process would serve better, but might still be too far a metabolic reach in some cases.
The definition of GO:0008611, ether lipid biosynthetic process, would still need a tweek for this to work.
"The chemical reactions and pathways resulting in the formation of ether lipids, lipids that contain \(normally\) one fatty alcohol in ether linkage to one of the carbon atoms \(normally C-1\) of glycerol." needs to be
"The chemical reactions and pathways resulting in the formation of ether lipids, lipids that contain \(normally\) one lipid alcohol in ether linkage to one of the carbon atoms \(normally C-1\) of glycerol."  Instead of "lipid alcohol" a list of terms "fatty or isoprenyl alcohols" might be used.

Reported by: jsgaravelli

Original Ticket: "geneontology/annotation-issues/482":https://sourceforge.net/p/geneontology/annotation-issues/482

**Comment by mcourtot** [comment]
@ValWood this is a very old ticket - ok to close?

**Comment by ValWood** [comment]
yep
