### ISSUE TITLE
Review annotations to GO:0016657 oxidoreductase activity, acting on NAD(P)H, nitrogenous group as acceptor

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4821]
Dear all, 

The proposal has been made to obsolete GO:0016657 oxidoreductase activity, acting on NAD(P)H, nitrogenous group as acceptor
see https://github.com/geneontology/go-ontology/issues/23357

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1moDLKPdX5b_GfPfpwNq5ZRl7a0WqLkgh9dCKFqBsrPQ/edit#gid=0

Impacted groups: 
EcoCyc 1
MGI 1
SGD 1
UniProt 1

Thanks.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by srengel** [comment]
SGD done
