### ISSUE TITLE
 PTN004187732  H3K9me/H3K9me2 demethylase activity to =/- reg of transcription.  AND PTN000290238

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4822]
* **PTHR ID & PTN node:**

* **Sequences with problematic annotation (ID + gene/protein name):**

PomBase Lsd1 
GO:0140683 | histone H3K9me/H3K9me2 demethylase activity
is annotated to

GO:0000122 | negative regulation of transcription by RNA polymerase II | IBA with PTN004187732 , MGI:1196256 , O60341 | Gaudet P et al. (2011) | 52
-- | -- | -- | -- | --
- | GO:0045944 | positive regulation of transcription by RNA polymerase II | IBA with MGI:1196256 , PTN004187732 , 1562975 , O60341 | Gaudet P et al. (2011) | 99

I'm not sure that either of these annotations are correct t (at least for yeast).
Mutation will affect transcription, but this seems to be more heterochromatin assembly and boundr formation?

@colinlog 
@pgaudet 
do you agree?

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
As we try to focus on the core functions of the families, I removed all downstream transcription regulation propagation.
