### ISSUE TITLE
IPR003150 regulation of transcription

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4823]
* **InterPro ID / label**

[IPR003150](http://www.ebi.ac.uk/interpro/entry/IPR003150)

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC1703.02

* **Description of issue**

I'm not 100% about this one, but I have annotated RSC complex to

GO:0045815 | transcription initiation-coupled chromatin remodeling

should  it also be annotated to
regulation of DNA-templated transcription GO:0006355

@pgaudet 
@colinlog

**Comment by tony787** [comment]
Dear Val,

This InterPro (IPR003150) entry includes a number of mammalian transcription factors such as RFX1/2/3/4/5/6/7/8 for which, as far as I'm aware, the transcription initiation-coupled chromatin remodelling doesn't apply. The RSC complex, on other side, remodels chromatin structure and regulates gene transcription so I believe the term 'regulation of DNA-templated transcription' is applicable to it.

Best wishes,
Toni

**Comment by colinlog** [comment]
Because it is recruited by a dbTF it has a MF function as a co-repressor or co-activator and is thus part_of BP transcription regulation.

RSC has a role in generating the dimensions of the nucleosome depleted region of gene promoters (positioning the -1 and + nucleosomes.

Definitely also BP: transcription intitiation-coupled chromatin remodelling.

@pgaudet I notice we deleted the nucleosome sliding/mobilisation BP, but we did not resurect it as a MF...  This is certainly what these enzymes do for transcription regulation, more often than not by virtue of being recruited by dbTFs, although they also read the histone modification code.

**Comment by ValWood** [comment]
This causes a curation logic issue for me. 

We are describing the same process in these 2 ways:

<img width="757" alt="Screenshot 2023-11-15 at 09 21 15" src="https://github.com/geneontology/go-annotation/assets/7359272/1118c5ac-c47b-4c07-a015-d96c69c25b33">

if both, this implies that 
BP: transcription intitiation-coupled chromatin remodelling.
should be part of  regulation of DNA-templated transcription GO:0006355

or are these two annotations describing the role of RSC in 2 different processes,  first  the regulation, and then the initiation?

**Comment by pgaudet** [comment]
Looking at this with @colinlog 

It looks like you get the hit to [IPR003150](http://www.ebi.ac.uk/interpro/entry/IPR003150) based on the PROSITE winged helix domain, which has the annotation to regulation of transcription. This is a bit odd, there is no human ortholog, so it's a bit unusual. Could the winged helix domain be a false positive or a low match? 

Colin says RSC is not  know to be a sequence-specific dbTF.

**Comment by ValWood** [comment]
RSC9 seems to have a known DNA binding domain https://www.yeastgenome.org/locus/S000004596/go
in S. cerevisiae (although I don't immediately see DNA binding assay in this paper, used for the IDA annotation).

However Rsc9 pombe and S. cerevisiae appear to have an ARID DNA binding domain based on most protein family methods (Pfam, SMART, CDD) I don't think this is a FP for the family.

My main issue is that we are describing the same process with 3 different terms in 2 different parts of the graph.
In the GO context it doesn't seem that the remodelled is doing the regulating? The transcription factor is doing this?)
Presumably the initiation-associated remodelling is required for the transcription to occur as much as the polymerase?
I can join next Friday.

**Comment by ValWood** [comment]
I forgot to respond to this.

The outcome is that RSC is a co-regulator and so it has 2 roles,
i) as a coregulator for regulation of initiation and  ii) as part of transcription initiation-coupled chromatin remodeling

SO the mappings are OK.
