### ISSUE TITLE
IPR027093 not reguation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4824]
* **InterPro ID / label**

GO:0006355 | regulation of DNA-templated transcription

* **Example sequences with problematic annotation (ID + gene/protein name):**
RNA polymerase II transcription elongation factor Eaf1
https://www.pombase.org/gene/SPCC1223.10c

* **Description of issue**

Is part_of, should be
GO:0006368 | transcription elongation by RNA polymerase II

**Comment by tony787** [comment]
Dear Val,
Thank you for pointing this. 
I have replaced the term and this change will be visible in the next InterPro release.
Best wishes,
Toni
