### ISSUE TITLE
IPR012259 glycine metabolism?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4827]
* **InterPro ID / label**

[IPR012259](http://www.ebi.ac.uk/interpro/entry/IPR012259)

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1223.08c

* **Description of issue**

Glycine biosynthetic process seems to be too indirect.
DHFR itself doesn't directly participate in glycine metabolism, the overall folate cycle, in which DHFR is a key enzyme, is interconnected with glycine metabolism through the transfer of one-carbon units

**Comment by deustp01** [comment]
> Glycine biosynthetic process seems to be too indirect.

[MetaCyc](https://biocyc.org/META/new-image?object=GLYSYN-PWY) disagrees - this reaction sequence shows up in a variety of pathways (depending how one draws pathway boundaries) but is a major source of glycine: 

> General Background
> 
> The proteinogenic amino acid [glycine](https://biocyc.org/compound?orgid=META&id=GLY) can biosynthesized via several different pathways. The main pathway in most organisms is the production of glycine from [L-serine](https://biocyc.org/compound?orgid=META&id=SER) via [EC 2.1.2.1, glycine hydroxymethyltransferase](https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-2.1.2.1). Eukaryotic organisms have both a cytosolic enzyme (SHMT2) and a mitochondrial enzyme (SHMT1) (see [glycine biosynthesis I](javascript:void(0);)). The two isoforms were reported to work in opposite directions depending on the culture conditions [[Kastanos97](http://www.ncbi.nlm.nih.gov/pubmed/9398220)].
> 
>

**Comment by ValWood** [comment]
OK I assumed that since DHFR generates THF, and THF is a contactor in the interconversion, this would make DHFR indirect (causally upstream).

I'm never sure how the boundaries should be drawn.

**Comment by pgaudet** [comment]
The InterPro entry seems clear that this is _part of_ glycine synthesis, but in individual entries there seems to be reactions in other pathways: 
https://www.uniprot.org/uniprotkb/Q86XF0/entry
https://www.uniprot.org/uniprotkb/P0ABQ4/entry


So I agree it's safer not to have it as an InterPro mapping.

**Comment by pgaudet** [comment]
@blazaropinto @sarach06 @tony787 

What do you think, should these mappings be removed?

**Comment by blazaropinto** [comment]
Thanks for pointing this out. I agree. I removed the term. The changes will be visible in the next release.

Best,
Beatriz
