### ISSUE TITLE
GO:0009452	 7-methylguanosine RNA capping IEA with IPR019012	GO_REF:0000002

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4828]
* **InterPro ID / label**

GO:0009452 | 7-methylguanosine RNA capping | IEA with IPR019012 | GO_REF:0000002

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC2G11.15c

* **Description of issue**

I think this should be
https://www.pombase.org/term/GO:0036261 ?

https://www.pombase.org/term/GO:0009452 7-methylguanosine RNA capping
is  not a parent of  GO:0036261

They are in different ontology branches.

@pgaudet  probably it should be clearer that  GO:0009452 refers to monomethylation?

**Comment by tony787** [comment]
Dear Val,
I agree and I have changed the term to GO:0036261.
This change will appear in the next InterPro release.
Best wishes,
Toni
