### ISSUE TITLE
Review annotations to GO:0005845 mRNA cap binding complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4832]
Dear all, 

The proposal has been made to obsolete GO:0005845 mRNA cap binding complex
see https://github.com/geneontology/go-ontology/issues/26347

Annotation will be remapped

Impacted groups: 
   4 ComplexPortal
   2 PomBase
   1 TAIR
  14 UniProt

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

term	file	line
interpro2go	InterPro:IPR028271 RNA guanine-N7 methyltransferase activating subunit > GO:mRNA cap binding complex ; GO:0005845
interpro2go	InterPro:IPR031456 Cap-associated protein Caf20 > GO:mRNA cap binding complex ; GO:0005845
unirule2go	UniRule:UR000107560 > GO:mRNA cap binding complex ; GO:0005845
hamap2go	HAMAP:MF_03031 > GO:mRNA cap binding complex ; GO:0005845

Thanks.

**Comment by ValWood** [comment]
term | file | line
-- | -- | --
2 | GO:0005845 | interpro2go | InterPro:IPR028271 RNA guanine-N7 methyltransferase activating subunit > GO:mRNA cap binding complex ; GO:0005845
3 | GO:0005845 | interpro2go | InterPro:IPR031456 Cap-associated protein Caf20 > GO:mRNA cap binding complex ; GO:0005845
4 | GO:0005845 | unirule2go | UniRule:UR000107560 > GO:mRNA cap binding complex ; GO:0005845
5 | GO:0005845 | hamap2go | HAMAP:MF_03031 > GO:mRNA cap binding complex ; GO:0005845

**Comment by pgaudet** [comment]
@ValWood Can you make a spreadsheet for these? 

HAMAP is @pedruzzi

**Comment by ValWood** [comment]
@blazaropinto 
@esperetta

**Comment by esperetta** [comment]
The UniRule UR000107560 is another name for [MF_03031](https://hamap.expasy.org/signature/MF_03031). @pedruzzi, could you please have a look? Thanks.
@ValWood I also checked and this is the only rule using this GO term. Thanks.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by Antonialock** [comment]
Uniprot reviewed

**Comment by blazaropinto** [comment]
InterPro:IPR028271 RNA guanine-N7 methyltransferase activating subunit > GO:mRNA cap binding complex ; GO:0005845 --> I changed this term for [GO:0031533: mRNA cap methyltransferase complex](https://www.ebi.ac.uk/QuickGO/term/GO:0031533)

InterPro:IPR031456 Cap-associated protein Caf20 > GO:mRNA cap binding complex ; GO:0005845  --> I deleted this term and added the MF [GO:0008190 — eukaryotic initiation factor 4E binding](http://www.ebi.ac.uk/QuickGo/GTerm?id=GO:0008190)

The changes will be available in the next InterPro release.

Best,
Beatriz

**Comment by tberardini** [comment]
TAIR done

**Comment by suzialeksander** [comment]
@pedruzzi please clean up the remaining annotations, we are closing this ticket and the remaining problematic mappings will now be available on the error report: http://release.geneontology.org/2023-11-15/reports/assigned-by-UniProt-report.html#gorule-0000020

**Comment by pedruzzi** [comment]
Done that now. Thanks a lot. Will take some time until the mappings disappear though.
-ivo
