### ISSUE TITLE
Review annotations to GO:0071712   ER-associated misfolded protein catabolic process  & regulation children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4833]
Dear all, 

The proposal has been made to obsolete GO:0071712  
ER-associated misfolded protein catabolic process , 
and its regulation children, 
see https://github.com/geneontology/go-ontology/issues/23092

Annotations will be remapped to the parent
GO:0036503   ERAD pathway
Definition ([GO:0036503 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0036503))
The protein catabolic pathway which targets endoplasmic reticulum (ER)-resident proteins for degradation by the cytoplasmic proteasome. It begins with recognition of the ER-resident protein, includes retrotranslocation (dislocation) of the protein from the ER to the cytosol, protein modifications necessary for correct substrate transfer (e.g. ubiquitination), transport of the protein to the proteasome, and ends with degradation of the protein by the cytoplasmic proteasome.

there is no difference. See the ontology ticket for more detail.

Impacted groups: 
  2 AspGD
   ~3 CGD~
   ~1 ComplexPortal~ DONE
   ~3 ParkinsonsUK-UCL~ DONE
   ~2 PomBase~ DONE

Will migrate automatically
   1 RGD
  15 SGD
   5 UniProt
   4 WB
   1 MGI

----

Thanks.

**Comment by ValWood** [comment]
@pgaudet  are there any groups listed here for which the remapping won't work?

**Comment by RLovering** [comment]
UCL annotations revised, the spreadsheet was empty so I found these myself

**Comment by ValWood** [comment]
HI Ruth, I didn't make a spreadsheet because the annotations will be remapped to
Annotations will be remapped to the parent
GO:0036503 ERAD pathway (which is not different from the 2 children)

We only make a ticket because some groups need to remap manually.

**Comment by pgaudet** [comment]
I think CGD and Complex Portal need to be manually updated.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by jlewsmith** [comment]
CGD done

**Comment by ValWood** [comment]
@pgaudet  who does AspGD?
Otherwise this one can close

**Comment by pgaudet** [comment]
I do ;)

**Comment by pgaudet** [comment]
seems like there is a replaced_by, so this is all good
