### ISSUE TITLE
Review annotations to GO:0030433    ubiquitin-dependent ERAD pathway  & regulation children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4834]
Dear all, 

The proposal has been made to obsolete [GO:0030433](https://www.ebi.ac.uk/QuickGO/term/GO:0030433)    ubiquitin-dependent ERAD pathway and its regulation children, 
see https://github.com/geneontology/go-ontology/issues/23092

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1SRBcUABAQwRuTgMlCQ5l_Ffp5GBEDQL_t8aaomWhvvQ/edit#gid=0

Annotation will be automatically remapped to GO:0036503   ERAD pathway

Impacted groups: 
   1 CGD
  11 ComplexPortal
   5 GeneDB
  12 TAIR

Will be automatically remapped
 4 FlyBase
   9 MGI
   4 PomBase
  97 SGD
  60 UniProt
   2 WB
   1 ZFIN

Fixed
  28 ParkinsonsUK-UCL FIXED

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
term	file	line
GO:0030433	interpro2go	InterPro:IPR017247 UBX domain-containing protein 8 > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	interpro2go	InterPro:IPR040352 Transmembrane and ubiquitin-like domain-containing protein 1/2 > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	interpro2go	InterPro:IPR044623 ERAD-associated E3 ubiquitin-protein ligase component HRD3 > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	interpro2go	InterPro:IPR045132 Ubiquitin conjugation factor E4 > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	interpro2go	InterPro:IPR045149 Protein OS-9-like > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	interpro2go	InterPro:IPR048056 AUP1, CUE domain > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	unirule2go	UniRule:UR000138768 > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	unirule2go	UniRule:UR001426776 > GO:ubiquitin-dependent ERAD pathway ; GO:0030433
GO:0030433	unirule2go	UniRule:UR001695774 > GO:ubiquitin-dependent ERAD pathway ; GO:0030433

No action required. Annotations will be remapped to ERAD pathway

Thanks.

**Comment by ValWood** [comment]
@pgaudet  same again , do I need to do a spreadsheet here? or will they all remap automatically?

**Comment by RLovering** [comment]
UCL annotations done, added a tab with just UCL annotations so that I could keep track of the annotations checked and changed

**Comment by ValWood** [comment]
Is this retirement? Can't wait ;(

**Comment by pgaudet** [comment]
Many annotations there do not updated automatically:

- CGD
- ComplexPortal
- GeneDB
- TAIR ?? 
- InterPro


Thanks, Pascale

**Comment by ValWood** [comment]
Stil needs spreadsheet

**Comment by ValWood** [comment]
Apologies

1 CGD @jlewsmith
11 ComplexPortal @sandraorchard
5 GeneDB @uliboehme
12 TAIR @tberardini / @lreiser

I obsoleted this term today as part of a larger ticket, but you can fix these in the logs if you don't get to it before.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by blazaropinto** [comment]
GO:0030433 changed to GO:0036503 ERAD pathway in the 6 entries mentioned. The changes will be available in the next InterPro release.

Best,
Beatriz

**Comment by lreiser** [comment]
TAIR tidied up

**Comment by jlewsmith** [comment]
CGD done

**Comment by suzialeksander** [comment]
This term has been obsoleted, remaining annotations will appear in GORULES error reports
