### ISSUE TITLE
Review annotations to GO:1904379    protein localization to cytosolic proteasome complex involved in ERAD pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4835]
Dear all, 

The proposal has been made to obsolete GO:1904379    protein localization to cytosolic proteasome complex involved in ERAD pathway
see https://github.com/geneontology/go-ontology/issues/23092

Experimental annotations that need to be reviewed are here: 

ParkinsonsUK-UCL | UniProtKB:P54252 | ATXN3 | PMID:17000876 |   | GO:1904379 | protein localization to cytosolic proteasome complex involved in ERAD pathway | IMP |   |   | PANTHER:PTHR14159 | 20150623 |   | NCBITaxon:9606

will be remapped to GO:0036503   (https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0036503/complete)
ERAD pathway

----

Thanks.

**Comment by RLovering** [comment]
UCL annotations revised
