### ISSUE TITLE
Review annotations to GO:0007303 cytoplasmic transport, nurse cell to oocyte

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4842]
Dear all, 

The proposal has been made to obsolete GO:0007303 cytoplasmic transport, nurse cell to oocyte
see https://github.com/geneontology/go-ontology/issues/26386

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1g-1-UYMz_SQh5emyGuhNauMdTG1JOP9XpOx8pSJ-D9g/edit#gid=0

Impacted groups: 
FB 

Thanks.

**Comment by hattrill** [comment]
FB done
