### ISSUE TITLE
Block to propagation to from PTN000643123 to FBgn0266432/CG45062

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4843]
* **PTHR ID & PTN node:** SODIUM/POTASSIUM-TRANSPORTING ATPASE SUBUNIT ALPHA (PTHR43294) ; PTN000643123

* **Sequences with problematic annotation (ID + gene/protein name):** FBgn0266432/CG45062

* **Type of Issue: Erroneous source or erroneous propagation, or other issue:** This gene has lost the N-terminal domain and so most probably cannot act as a K+ transporter. So please block PAINT annotations to this gene as we don't really know what it does.

**Comment by marcfeuermann** [comment]
This has already been addressed and solved
see: https://github.com/geneontology/go-annotation/issues/4640
Sorry for the time lag.
