### ISSUE TITLE
Review annotations to GO:0044736 acid-sensing ion channel activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4849]
Dear all, 

The proposal has been made to obsolete GO:0044736 acid-sensing ion channel activity, and its regulation children, 
see [LINK TO GO-ONTOLOGY TICKET]

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1n7pDCBRcgc513_RMm1ojJA4VdRfR0y1uxjGiP0U04Dk/edit#gid=0

Impacted groups: 
FlyBase: 3
MGI: 3
UniProt: 3

Mappings that need to be reviewed: 

Reactome:R-HSA-2671885 > GO:acid-sensing ion channel activity ; GO:0044736 

Thanks.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by hattrill** [comment]
Just waiting for terms to be available in P2GO

**Comment by deustp01** [comment]
The recommended replacement is:
Replacements:
GO:0044736 acid-sensing ion channel activity >> GO:0160128 pH-gated channel activity
Right? If so, R-HSA-2671885 already fixed in local database and the fix will become visible with a=our March 2024 release.
So, done?

**Comment by pgaudet** [comment]
@hattrill 

Unfortunately we haven't had a snapshot in several weeks. Hopefully the pipeline problems will get resolved soon and the term will be available. 

However this is a term replacement, this will be done automatically in P2GO. Should we close this?

**Comment by hattrill** [comment]
@pgaudet then that's fine with me.
