### ISSUE TITLE
Review annotations to     GO:0003953 NAD+ nucleosidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4850]
Dear all, 

The proposal has been made to obsolete 
GO:0061810 NAD glycohydrolase activity
GO:0061811 ADP-ribosyl cyclase activity and 
GO:0061812 cyclic ADP-ribose hydrolase

see https://github.com/geneontology/go-ontology/issues/26011 

Experimental annotations that need to be reviewed are here: 

https://docs.google.com/spreadsheets/d/1LpNkGGknV7rM0b9lgdd3bNKGyXRueOzpmPE21lC1Hao/edit#gid=0

Impacted groups:  To correct: (highlighted in orange in the spreadsheet): 
1 FlyBase
2 MGI 
1 RGD 
1 InterPro
2 Reactome

 Others will be correctly re-mapped. 

----

Thanks.

**Comment by deustp01** [comment]
Done, as noted above. Does this fully resolve my "confusion" comment on #26011 ?

**Comment by pgaudet** [comment]
I think so - is it OK for you ?

**Comment by sjm41** [comment]
@pgaudet Annotation spreadsheet suggests the FB annotation should change from 'GO:0003953 | NAD+ nucleosidase activity' to 'GO:0061810 | NAD glycohydrolase activity'.

But https://github.com/geneontology/go-ontology/issues/26011#issuecomment-1833656046 says you'll obsolete 'NAD glycohydrolase activity' and replace by its parent 'NAD+ nucleosidase activity'.

So I don't think I need to do anything here, right?

**Comment by pgaudet** [comment]
Thanks for pointing this out @sjm41 
I had forgot to update the spreadsheet. No changed are needed from FB.

**Comment by LiNiMGI** [comment]
MGI done

**Comment by blazaropinto** [comment]
The term is updated in IPR003193, the changes will be available in the next InterPro release.
Best,
Beatriz
