### ISSUE TITLE
Review annotations to GO:0006407 rRNA export from nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4851]
Dear all, 

The proposal has been made to obsolete GO:0006407 rRNA export from nucleus
see  https://github.com/geneontology/go-ontology/issues/25263

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1VvCTAb3u72hm4OztGkRVZjlGTtvemYqorWNu41oRB50/edit#gid=0

Impacted groups: 
   2 MGI @LiNiMGI 
  23 SGD @srengel 
   1 UniProt @Antonialock 
No action is necessary  as this term will be replaced by
ribosomal subunit export from nucleus - GO:0000054

Thanks.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
