### ISSUE TITLE
Block propagation to FBgn0263026 (CG43321); M9NEV9 of mitochondrial related terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4852]
PANTHER:PTN002141638 
Family 	ESSENTIAL MCU REGULATOR, MITOCHONDRIAL (PTHR33904)
Subfamily 	ESSENTIAL MCU REGULATOR, MITOCHONDRIAL (PTHR33904:SF1)

* **Sequences with problematic annotation **

FBgn0263026 (CG43321); UniProtKB:M9NEV9)

* **Type of Issue:**

The insect orthologs of this protein have lost the N-terminal portion that contains the mitochondrial targetting sequence (65aa protein vs 106aa vertebrate version), so seems unlikely that this is mitochondrial. I've put NOT annotations on these terms using the ISM.

Tagging @gantonazzo

**Comment by marcfeuermann** [comment]
Thanks for reporting this. I've blocked the annotations.
