### ISSUE TITLE
Review annotations to some intracellular signaling pathways

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4853]
Dear all, 

The proposal has been made to obsolete 

GO:0038008 TRAF-mediated signal transduction (https://github.com/geneontology/go-ontology/issues/26498)
GO:0019932 second-messenger-mediated signaling (https://github.com/geneontology/go-ontology/issues/26503)
GO:0071848 positive regulation of ERK1 and ERK2 cascade via TNFSF11-mediated signaling and GO:0071847 TNFSF11-mediated signaling pathway (https://github.com/geneontology/go-ontology/issues/26499)
GO:0061359 regulation of Wnt signaling pathway by Wnt protein secretion  (https://github.com/geneontology/go-ontology/issues/26404)
GO:0007227 signal transduction downstream of smoothened (https://github.com/geneontology/go-ontology/issues/26496)

**Comment by RLovering** [comment]
I assume that the child terms for these terms are not included in the obsoletion? As UCL has lots of annotations to review if the child terms are included

**Comment by pgaudet** [comment]
Which child terms are you referring to? 
- children of  GO:0019932 second-messenger-mediated signaling are not being obsoleted
- I dont think other terms have children?

**Comment by RLovering** [comment]
Phew ;)

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by vanaukenk** [comment]
WB done

**Comment by sramachand** [comment]
ZFIN done

**Comment by suzialeksander** [comment]
Associated terms were obsoleted, any remaining annotations will appear in GORULES error reports
