### ISSUE TITLE
Review annotations to GO:0018142 protein-DNA covalent cross-linking and descendents

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4855]
Dear all, 

The proposal has been made to obsolete
GO:0018142 protein-DNA covalent cross-linking 
This term appears to represent a single-step MF, newly created GO:0160129 protein-DNA covalent cross-linking activity
GO:0018145 protein-DNA covalent cross-linking via peptidyl-serine (no annotation)
GO:0018164 protein-DNA covalent cross-linking via peptidyl-threonine (no annotation)
GO:0045327 protein-DNA covalent cross-linking via peptidyl-tyrosine (no annotation)
GO:0045326 protein-DNA covalent cross-linking via the 3'-end to peptidyl-tyrosine (no annotation)
GO:0018163 protein-DNA covalent cross-linking via the 5'-end to peptidyl-tyrosine (no annotation)

see https://github.com/geneontology/go-ontology/issues/26415

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1qqqa7Dc_v4OVWnJZOp-PqsPvDCH4qi-0hkxv0B0kjWU

Impacted groups: 
MGI 1
UniProt 5

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
GO:0018142	interpro2go	InterPro:IPR003365 Viral replication-associated protein, N-terminal > GO:protein-DNA covalent cross-linking ; GO:0018142
GO:0018142	interpro2go	InterPro:IPR003738 SOS response associated peptidase (SRAP) > GO:protein-DNA covalent cross-linking ; GO:0018142
GO:0018142	interpro2go	InterPro:IPR008770 DNA terminal protein Gp3 > GO:protein-DNA covalent cross-linking ; GO:0018142
GO:0018145	resid2go	RESID:AA0246 > GO:protein-DNA covalent cross-linking via peptidyl-serine ; GO:0018145
GO:0018163	resid2go	RESID:AA0254 > GO:protein-DNA covalent cross-linking via the 5'-end to peptidyl-tyrosine ; GO:0018163
GO:0018164	resid2go	RESID:AA0255 > GO:protein-DNA covalent cross-linking via peptidyl-threonine ; GO:0018164
GO:0045326	resid2go	RESID:AA0323 > GO:protein-DNA covalent cross-linking via the 3'-end to peptidyl-tyrosine ; GO:0045326

Thanks.

**Comment by raymond91125** [comment]
@pgaudet Whom should be assigned for resid2go? Thanks.

**Comment by pgaudet** [comment]
RESID2GO mappings are maintained in the ontology, GO editors manage them. You can just delete them.

**Comment by blazaropinto** [comment]
Hi,
I deleted this term from all mentioned entries and added [GO:0106300](https://www.ebi.ac.uk/QuickGO/term/GO:0106300) to IPR003738.
I'm afraid I can't add the newly created term yet.
The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by raymond91125** [comment]
> Hi,
> 
> All UniProt annotations were made by @sylvainpoux , so I am reassigning the UniProt reviews to him.

Should the following file be updated then?
metadata/group-contacts.csv

**Comment by pgaudet** [comment]
Hi Raymond, no I dont think we need to update the file, usually we have 1-2 contact persons by group but reviews do get reassigned when appropriate.

**Comment by suzialeksander** [comment]
These terms were obsoleted, any remaining annotations will appear in GORULES error reports
