### ISSUE TITLE
Review annotations to GO:0019419 sulfate reduction 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4856]
Dear all, 

The proposal has been made to obsolete GO:0019419 sulfate reduction  & replaced by GO:0000103 sulfate assimilation

see https://github.com/geneontology/go-ontology/issues/26582

Experimental annotations that need to be reviewed are here: 

https://docs.google.com/spreadsheets/d/1GBsELqUPDqTyNkI1bkfa2CVyUP4kPIcZ0HzDObOOkmA/edit#gid=0

Impacted groups: 
2 ComplexPortal
1 TAIR
2 InterPro

Thanks.

**Comment by tberardini** [comment]
TAIR done

**Comment by blazaropinto** [comment]
Hi Pascale,

Thank you for this. These terms are updated now. The changes will be available in the next InterPro release.

Best,

Beatriz

**Comment by sandraorchard** [comment]
Done
