### ISSUE TITLE
Review annotations to GO:0016290 palmitoyl-CoA hydrolase activity and GO:0102991 myristoyl-CoA hydrolase activity  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4859]
Dear all, 

The proposal has been made to obsolete 
GO:0016290 palmitoyl-CoA hydrolase activity 
GO:0102991 myristoyl-CoA hydrolase activity 

Annotations are here: https://docs.google.com/spreadsheets/d/18hq_XWeSvYtNcuTlItRwWP9QZZ9R7xFLp5MVyMQZutU/edit#gid=0

Group | Number of EXP annotations 
-- | --
BHF-UCL | 1
EcoCyc | 2
MGI | 1
RGD | 3
UniProt | 14
ZFIN | 1

The terms will be replaced by the parent GO:0052816 long-chain fatty acyl-CoA hydrolase activity. 

Thanks, Pascale

**Comment by pgaudet** [comment]
GO:0102991 myristoyl-CoA hydrolase activity has no manual annotations

**Comment by suzialeksander** [comment]
These terms were obsoleted, any remaining annotations will appear in GORULES error reports
