### ISSUE TITLE
Review annotations to GO:0009927 histidine phosphotransfer kinase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4861]
Checking annotations to 

GO:0009927 histidine phosphotransfer kinase activity

**Comment by pfey03** [comment]
@pgaudet Is there a replacement term for this? we only have 1 IDA and 1 ISS. Why is the MF being obsoleted?


Thanks,
Petra

**Comment by pgaudet** [comment]
Hi @pfey03 

This was not for obsoletion, I was just checking annotations. 

Thanks, Pascale

**Comment by pfey03** [comment]
@pgaudet Ah ok thanks Pascale
