### ISSUE TITLE
Review annotations to GO:0007263 nitric oxide mediated signal transduction & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4863]
GO:0007263 nitric oxide mediated signal transduction
GO:0010749 regulation of nitric oxide mediated signal transduction 
GO:0010751 negative regulation of nitric oxide mediated signal transduction
GO:0010750 positive regulation of nitric oxide mediated signal transduction

Ontology ticket: https://github.com/geneontology/go-ontology/issues/26613

Annotations are here: https://docs.google.com/spreadsheets/d/1q0UmVT5dG95-sJ2D4uLc5c1Evge9zEGcD_kZJhcD7tc/edit#gid=0

assigned_by | Number of EXP
-- | --
CAFA | 1
CGD | 3
dictyBase | 1
FlyBase | 4
MGI | 5
PomBase | 1
RGD | 2
UniProt | 18
UCL  | 9 (done)

**Comment by suzialeksander** [comment]
Annotation Review is out-of-date and was closed
