### ISSUE TITLE
Review annotations to GO:0030580 quinone cofactor methyltransferase activity' & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4866]
Dear all, 

The proposal has been made to obsolete 
GO:0030580 quinone cofactor methyltransferase activity'
GO:0043429 2-nonaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043428 2-heptaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043430 2-decaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043334 2-hexaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043333 2-octaprenyl-6-methoxy-1,4-benzoquinone methylase activity

see
https://github.com/geneontology/go-ontology/issues/25682

Annotations are here: https://docs.google.com/spreadsheets/d/1JHKU8bl1juF8HCLZrhlOUWVUPHf_7E1592V4TvWbCNc/edit#gid=0

- 2 EcoCyc
- 1 UniProt (will be automatically replaced) 
- 1 SGD  (will be automatically replaced) 
- 3 HAMAP/UniRule

Thanks, Pascale

**Comment by deustp01** [comment]
The search missed a Reactome instance, R-HSA-2162188. Now fixed.

**Comment by pgaudet** [comment]
thanks @deustp01

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by suzialeksander** [comment]
Terms were obsoleted, any remaining annotations will appear in the GORULES error reports.
