### ISSUE TITLE
Review annotations to GO:0044595 decaprenyldihydroxybenzoate methyltransferase activity, GO:0004395 hexaprenyldihydroxybenzoate methyltransferase activity, and GO:1990887 2-polyprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinol O-methyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4867]
Dear all, 

The proposal has been made to obsolete 

GO:0044595 decaprenyldihydroxybenzoate methyltransferase activity
GO:0004395 hexaprenyldihydroxybenzoate methyltransferase activity, and 
GO:1990887 2-polyprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinol O-methyltransferase activity
**& replace by GO:0010420 3,4-dihydroxy-5-polyprenylbenzoic acid O-methyltransferase activity**

see https://github.com/geneontology/go-ontology/issues/26632 

Experimental annotations that need to be reviewed are here: 

https://docs.google.com/spreadsheets/d/1W4EK61mOfLyAcL32Zex1TwG7e5CMBLhzCeForlysTzY/edit#gid=0

Impacted groups: 

1 RGD
1 SGD
1 TAIR
1 Reactome
2 HAMAP/UniRule

Thanks.

**Comment by deustp01** [comment]
Reactome done

**Comment by tberardini** [comment]
TAIR done

**Comment by suzialeksander** [comment]
remaining annotations should be picked up in the Reports.
