### ISSUE TITLE
Review annotations to children of GO:0061542 3-demethylubiquinol-n 3-O-methyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4868]
Dear all, 

The proposal has been made to obsolete 

GO:0008689 3-demethylubiquinone-9 3-O-methyltransferase activity
GO:0044596 3-demethylubiquinol-10 3-O-methyltransferase activity 
GO:0061543 3-demethylubiquinol-6 3-O-methyltransferase activity 
GO:0099119 3-demethylubiquinol-8 3-O-methyltransferase activity

see https://github.com/geneontology/go-ontology/issues/25680 

& replace by parent GO:0061542 3-demethylubiquinol-n 3-O-methyltransferase activity

Experimental annotations that need to be reviewed are here:  https://docs.google.com/spreadsheets/d/1Q6k_dM8K5QTE4k01qOEuODXXikIfpwir0Nf7Y5S8J_Y/edit#gid=0

Impacted groups: 
1 SGD
1 EcoCyc
1 Reactome
3 UniRule/HAMAP

Thanks.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by suzialeksander** [comment]
Terms were obsoleted, remaining annotations will appear in GORULES error reports
