### ISSUE TITLE
Review annotations to GO:0019054 modulation by virus of host process  - immune sytem perturbation terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4869]
GO:0039699 | viral mRNA cap methylation
GO:0099016 | evasion by virus of DNA end degradation
GO:0019049 | virus-mediated perturbation of host defense response
GO:0075528 | perturbation by virus of host immune response
GO:0039503 | suppression by virus of host innate immune response
GO:0039504 | suppression by virus of host adaptive immune response
GO:0039573 | suppression by virus of host complement activation
GO:0039673 | evasion by virus of host dendritic cell activity
GO:0039671 | evasion by virus of host natural killer cell activity
GO:0099018 | evasion by virus of host restriction-modification system
GO:0098672 | inhibition of host CRISPR-cas system by virus

Annotations are here: 
https://docs.google.com/spreadsheets/d/1bdHnQ-00fhRVZIThWdhSUYYxbxgYAF_WYyx1eGmeDgI/edit#gid=0
* 10 CACAO
* 35 UniProt
* 4 HAMAP
* 5 UniRules
* 12 InterPro

**Comment by RLovering** [comment]
Hi Pascale

UCL has 11 annotations to child terms https://www.ebi.ac.uk/QuickGO/annotations?assignedBy=ARUK-UCL,Alzheimers_University_of_Toronto,BHF-UCL,HGNC-UCL,ParkinsonsUK-UCL,SynGO-UCL&goId=GO:0071507,GO:0030580,GO:1990887,GO:0004395,GO:0044595,GO:0019054,GO:0052559,GO:1990216,GO:0061542&goUsageRelationships=is_a,part_of,occurs_in,regulates&goUsage=descendants

<div class="column small-12 overflow-pane">
Term ID | Term name | Remove
-- | -- | --
GO:0039656 | modulation by virus of host gene expression |  
GO:1904188 | negative regulation of transformation of host cell by virus |  
GO:1904187 | regulation of transformation of host cell by virus |  
GO:1904189 | positive regulation of transformation of host cell by virus |  
GO:0019050 | suppression by virus of host apoptotic process |  
GO:0019056 | modulation by virus of host transcription |  
GO:0046775 | suppression by virus of host cytokine production |  


        </div>
        <div class="row column small-12">
          <div class="float-right">
            <chart-icon ids="GO:0039656,GO:1904188,GO:1904187,GO:1904189,GO:0019050,GO:0019056,GO:0046775" class="ng-isolate-scope"><span ng-click="showChart()" class="chart-btn selectable" data-icon="h"></span></chart-icon>
            </div></div>
            <a class="button icon-generic" ng-href="https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0039656,GO:1904188,GO:1904187,GO:1904189,GO:0019050,GO:0019056,GO:0046775/complete" data-icon="L" target="_blank" href="https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0039656,GO:1904188,GO:1904187,GO:1904189,GO:0019050,GO:0019056,GO:0046775/complete"> JSON</a>
            
Term ID 	Term name 
GO:0039656 modulation by virus of host gene expression 	
GO:1904188 negative regulation of transformation of host cell by virus 	
GO:1904187 regulation of transformation of host cell by virus 	
GO:1904189 positive regulation of transformation of host cell by virus 	
GO:0019050 suppression by virus of host apoptotic process 	
GO:0019056 modulation by virus of host transcription 	
GO:0046775 suppression by virus of host cytokine production 	

Will these child terms be obsoleted too?
Thanks
Ruth

**Comment by pgaudet** [comment]
Hi Ruth, 

Here you go: 

Term ID | Term name | To be merged into the more general 'symbiont' term
-- | -- | --
GO:0039656 | modulation by virus of host gene expression |  yes
GO:1904188 | negative regulation of transformation of host cell by virus |  no, will remain
GO:1904187 | regulation of transformation of host cell by virus |  no, will remain
GO:1904189 | positive regulation of transformation of host cell by virus |  no, will remain
GO:0019050 | suppression by virus of host apoptotic process |  yes
GO:0019056 | modulation by virus of host transcription |  yes
GO:0046775 | suppression by virus of host cytokine production |   yes



Note that only viral genes should be annotated to these processes. 

Thanks, Pascale

**Comment by RLovering** [comment]
great, I think I have revised the UCL ones and these are all to viruses
