### ISSUE TITLE
IPR020598 & IPR020596 have redundant GO annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4870]
Both these entries:
IPR020598 Ribosomal RNA adenine methylase transferase, N-terminal
IPR020596 Ribosomal RNA adenine methylase transferase, conserved site

Have both these GO-MF terms:
rRNA (adenine-N6,N6-)-dimethyltransferase activity (GO:0000179)
rRNA methyltransferase activity (GO:0008649)

Can you remove GO:0008649, since it's a parent of  GO:0000179?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this. The term has been removed from both entries. This will be visible in the next InterPro release (78.0).
Best wishes,
Sara
