### ISSUE TITLE
Review annotations to GO:1990216 positive regulation by symbiont of host transcription

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4873]
Dear all, 

The proposal has been made to obsolete GO:1990216 positive regulation by symbiont of host transcription

Annotations are here: https://docs.google.com/spreadsheets/d/1LQ3ooL10wM_W04XfriJ4T_nK5Wq3HTeQP1bZq4I6K20/edit#gid=0

**Comment by suzialeksander** [comment]
The corresponding go-ontology ticket does not exist
