### ISSUE TITLE
Review annotations to  GO:0052559 induction by symbiont of host immune response

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4874]
Dear all, 

The proposal has been made to obsolete GO:0052559 induction by symbiont of host immune response

Annotations are here: https://docs.google.com/spreadsheets/d/1R_Ar8pSI-RYNhmKbAvmzxI7kP0JUZuHvwtFcVVzQRfE/edit#gid=0

**Comment by jlewsmith** [comment]
CGD done
