### ISSUE TITLE
IPR013328 6-phosphogluconate dehydrogenase, domain 2

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4875]
* **InterPro ID / label**
IPR013328 6-phosphogluconate dehydrogenase, domain 2

* **Example sequences with problematic annotation (ID + gene/protein name):**
Dmel Ndf (Q8T079)
Human GLYR1 (Q49A26)

* **Description of issue**
This homologous superfamily entry is annotated with the high-level MF term 'oxidoreductase activity', but the signature is found in Ndf/GLYR1, which is not characterised to be an enzyme.
Suggest removing this association.

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you so much for this. This entry also represents a domain with NADP/binding activity in many proteins. This term is removed now. The changes will be available in the next InterPro release.

Best,

Beatriz
