### ISSUE TITLE
FAD dependent oxidoreductase IPR006076

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4877]
* **InterPro ID / label**
FAD dependent oxidoreductase IPR006076

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly CG3626 (Q9W4K8), human PDPR (Q8NCN5)

* **Description of issue**
This has GO annotation to the high-level MF term 'oxidoreductase activity', but the signature is found in PDPR (pyruvate dehydrogenase phosphatase regulatory subunit), which isn't a catalytic subunit.
Can you remove this mapping?

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this. This term is removed now. The changes will be available in the next InterPro release.

Best,

Beatriz
