### ISSUE TITLE
Review annotations to GO:0043734 DNA-N1-methyladenine dioxygenase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4880]
Dear all, 

The proposal has been made to obsolete GO:0043734 DNA-N1-methyladenine dioxygenase activity
see https://github.com/geneontology/go-ontology/issues/26656
and will be replaced by GO:0035516 'oxidative DNA demethylase activity. 

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1SP4xShMGjEhZ6oMEB69bJEIHdGY2q3cKKI2Fpq2SJNA/edit#gid=0

Impacted groups: 
8 UniProt
1 EcoCyc
2 Reactome 

Thanks.

**Comment by deustp01** [comment]
Reactome is done

**Comment by amandamackie** [comment]
EcoCyc done
