### ISSUE TITLE
Review annotations to some 'entry into host' terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4882]
Dear all, 

The proposal has been made to obsolete 
GO:0039667 viral entry into host cell via pilus retraction
GO:0039668 viral entry into host cell via pilus basal pore 
GO:0039669 viral entry into host cell via pilus retraction and membrane fusion 
GO:0035635 entry of bacterium into host cell 
GO:0039707 virus-mediated pore formation in host cell membrane 

See https://github.com/geneontology/go-ontology/issues/26669

Annotations are here: https://docs.google.com/spreadsheets/d/1xxoNItZwF1bKUQe0q1DgkshH07J2es8FdBcduG9ezYY/edit#gid=0

Impacted groups: 
| Database    | Count |
|-------------|-------|
| AgBase      |   4   |
| CACAO       |   1   |
| GO_Central  |   1   |
| MGI         |   2   |
| CAFA        |   4   |
| UniProt     |   2   |
| Reactome    |   2   |
| InterPro   |   6   |
| HAMAP    |   1   |

**Comment by deustp01** [comment]
Reactome done. All uses of GO:0035635 entry of bacterium into host cell have been switched to GO:0046718 (which right now is still named "caterial entry" but will become taxon-agnostic shortly). The changes will become visible, with the updated name, in our March 2024 release.

**Comment by suzialeksander** [comment]
[GO:0035635](https://www.ebi.ac.uk/QuickGO/term/GO:0035635) 	entry of bacterium into host cell is still a valid term. 

The other terms were obsoleted; remaining annotations will appear in GORULES error reports
[GO:0039707](https://www.ebi.ac.uk/QuickGO/term/GO:0039707) 	obsolete virus-mediated pore formation in host cell membrane 	
[GO:0039669](https://www.ebi.ac.uk/QuickGO/term/GO:0039669) 	obsolete viral entry into host cell via pilus retraction and membrane fusion 	
[GO:0039668](https://www.ebi.ac.uk/QuickGO/term/GO:0039668) 	obsolete viral entry into host cell via pilus basal pore 	
[GO:0039667](https://www.ebi.ac.uk/QuickGO/term/GO:0039667) 	obsolete viral entry into host cell via pilus retraction

**Comment by suzialeksander** [comment]
The remaining annotations to [GO:0035635](https://www.ebi.ac.uk/QuickGO/term/GO:0035635) entry of bacterium into host cell are from AgBase and GOCentral

@pgaudet as noted on the ontology ticket, [GO:0035635](https://www.ebi.ac.uk/QuickGO/term/GO:0035635)
entry of bacterium into host cell is not obsoleted but that ticket is closed, can you make a new ticket if this term is still about to be obsoleted?
