### ISSUE TITLE
Review annotations to     GO:0004164  diphthine synthase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4886]
GO:0004164 diphthine synthase activity

is only present in Archae. For eukaroytic enzymes, please use the new term GO:0141133  diphthine methyl ester synthase activity (created today, it will take a few days to become available)

**Comment by pgaudet** [comment]
Dear all, 

We now have two activities describing archeal GO:0004164 diphthine synthase activity and eukaryotic GO:0141133 diphthine methyl ester synthase activity, which catalyze slightly different reactions (see https://github.com/geneontology/go-ontology/issues/25281 for more details). So, all eukaryotic annotations to  GO:0004164  will need to be moved to GO:0141133 

Annotations are here: https://docs.google.com/spreadsheets/d/1Rm6KG8bvoo86lplWHgOewF1UWHnd6GsCWxHqb6L5Roo/edit#gid=0

There is 1 Reactome EXP and one mapping
2 SGD annotations
1 InterPro
1 HAMAP

Thanks, Pascale

**Comment by deustp01** [comment]
Reactome done

**Comment by suzialeksander** [comment]
@uliboehme there's a GeneDB annotation to [GO:0004164](https://www.ebi.ac.uk/QuickGO/term/GO:0004164)
diphthine synthase activity, please consider GO:0141133 diphthine methyl ester synthase activity. This is currently in the  error report http://snapshot.geneontology.org/reports/assigned-by-GeneDB-report.html
