### ISSUE TITLE
IPR046792 Peptidase C54, catalytic domain / IPR005078 Peptidase C54

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4888]
* **InterPro ID / label**
IPR046792 Peptidase C54, catalytic domain
IPR005078 Peptidase C54

* **Description of issue**
Can you add "GO:0008234 cysteine-type peptidase activity" to one/both of these entries?

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this. The term is added to both entries now. The changes will be available in the next InterPro release.

Best,

Beatriz
