### ISSUE TITLE
Review annotations to     GO:0042785  evasion of host immune response via modulation of host cytokine network

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4889]
Dear all, 

The proposal has been made to obsolete  GO:0042785  evasion of host immune response via modulation of host cytokine network

**Comment by pgaudet** [comment]
Please review, and if appropriate move to  GO:0141135 symbiont-mediated suppression of host chemokine signal transduction pathway

**Comment by Antonialock** [comment]
There is no speadsheet but I guess it will be in the logs.

**Comment by pgaudet** [comment]
Thanks for checking @Antonialock 


These were all fixed or deleted.
