### ISSUE TITLE
Review annotations to GO:0061765 perturbation by virus of host non-canonical NF-kappaB signal transduction & related

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4891]
GO:0039644 suppression by virus of host NF-kappaB cascade
GO:0039652 induction by virus of host NF-kappaB cascade
GO:0061765 perturbation by virus of host non-canonical NF-kappaB signal transduction

**Comment by suzialeksander** [comment]
All terms have been obsoleted.
