### ISSUE TITLE
Review annotations to  GO:0044071  perturbation of host cell cycle progression

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4892]
GO:0044071  perturbation of host cell cycle progression & children

**Comment by pgaudet** [comment]
Obsolete  GO:0060153 | perturbation by virus of host cell cycle progression 
& replace by parent [symbiont-mediated perturbation of host cell cycle progression](http://purl.obolibrary.org/obo/GO_0044071) 
1 DisProt annotation; 2 Uniprot

**Comment by suzialeksander** [comment]
These terms were obsoleted; any remaining annotations will be on the GORules reports
