### ISSUE TITLE
Review annotations to GO:0090308 regulation of DNA methylation-dependent heterochromatin formation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4893]
GO:0090308 regulation of DNA methylation-dependent heterochromatin formation
GO:0090310 negative regulation of DNA methylation-dependent heterochromatin formation
GO:0090309 positive regulation of DNA methylation-dependent heterochromatin formation 

Misleading and incorrectly annotated

See https://docs.google.com/spreadsheets/d/1b7l-q0PIggn2croU9GLQjYpj8MSmuc1IzX0TcA_Bedc/edit?gid=0#gid=0

**Comment by suzialeksander** [comment]
no ontology ticket

**Comment by pgaudet** [comment]
@hattrill Can you please review the FB annotations and let us know if you agree? 

https://docs.google.com/spreadsheets/d/1b7l-q0PIggn2croU9GLQjYpj8MSmuc1IzX0TcA_Bedc/edit?gid=0#gid=0

**Comment by hattrill** [comment]
FB done - changed as per sheet suggestions

**Comment by pgaudet** [comment]
Thanks!
