### ISSUE TITLE
IPR009349 regulation of DNA-templated transcription

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4895]
* **InterPro ID / label**

IPR009349 

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1A6.01c  O13855
https://www.yeastgenome.org/locus/S000001731/go#comp 

[O13855](https://www.uniprot.org/uniprot/O13855)

* **Description of issue**

not
GO:0006355	regulation of DNA-templated transcription

These transcription related annotation comes from human.

More recently this has been shown clearly to be part of the ribosome quality control pathway 
https://www.yeastgenome.org/locus/S000003503#go
https://www.yeastgenome.org/locus/S000001731#go
https://www.yeastgenome.org/locus/S000003078#go

there are detailed papers on the mechanism
https://pubmed.ncbi.nlm.nih.gov/28757607/
https://pubmed.ncbi.nlm.nih.gov/32099016/
https://pubmed.ncbi.nlm.nih.gov/36627279/

It is possible there may also be a QC role in transcription, but for now this should be the major annotation, because only detected in the cytoplasm in yeast. There is no transcription, or nuclear EXP annotation at SGD

consider:

GO:0072344  rescue of stalled ribosome
GO:0180022 RQC-trigger complex
@marcfeuermann  you could also do PAINT mappings  yeast-> human for these

**Comment by sarach06** [comment]
Dear Val,
Thank you very much for this. I have replaced GO:0006355 regulation of DNA-templated transcription for the terms you suggested. I also updated the name and abstract for this entry. These changes will be visible in InterPro 98.0.

Best wishes,
Sara
