### ISSUE TITLE
 PTN008344380 not GO:0003713	transcription coactivator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4896]
* **PTHR ID & PTN node:**

PTN008344380

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1A6.01c  and orthologs

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation

Issue described here:
https://github.com/geneontology/go-annotation/issues/4895

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed.

**Comment by ValWood** [comment]
Annotation still present in Quickgo

**Comment by pgaudet** [comment]
@ValWood anything resolved after this date is not yet on P2GO. I am not sure it makes sense to reopen all these tickets, unless you want. to assign them to yourself to review? 

If you want to check the annotations in the PAINT database, please download the most up-to-date paint-pombase file: http://release.geneontology.org/2024-04-18/products/upstream_and_raw_data/paint_pombase-src.gaf.gz

**Comment by ValWood** [comment]
It's OK, can be closed. I'd assumed that the PAINT annotations would be updated in GO within a few months, but  if it's a time lag issue I'll just keep the filters for a while longer.
v

**Comment by pgaudet** [comment]
Sounds good.

**Comment by marcfeuermann** [comment]
I've completely updated the annotation. I'll try to close this one again ;-)
