### ISSUE TITLE
GO:0000280	 nuclear division IBA with PTN000835966 , S000003616

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4898]
* **PTHR ID & PTN node:**

 PTN000835966 , 

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC550.14

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous annotation,  mitosis seems to be indirect (available evidence indicates role in the regulation if RNA stability)

the existing SGD annotation are a broad range of phenotypes (so clearly  pleiotropic )
https://www.yeastgenome.org/locus/S000003616#go
I would not transfer anything for this for now unless there is other evidence.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed.

**Comment by ValWood** [comment]
Annotation still present in QuickGO, should it have disappeared by now? in fact the annotation at SGD is no longer present

**Comment by pgaudet** [comment]
Hi @ValWood 
I confirm that these are gone from the PAINT source annotations, as of the last release 

> !gaf-version: 2.2
!Created on Tue Apr  9 08:34:36 2024.
!generated-by: PANTHER
!date-generated: 2024-04-09
!PANTHER version: v.17.0.
!GO version: 2024-01-17.

Looks like there is a lag in QuickGO.
