### ISSUE TITLE
IPR040240 GO:0001091	 RNA polymerase II general transcription initiation factor binding IEA with 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4899]
* **InterPro ID / label**

IPR040240

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC2G11.14 (taf1)

* **Description of issue**

Taf1 is part_of TFIID, so it IS_A  RNA polymerase II general transcription initiation factor

you could change this mapping to

GO:0016251 | RNA polymerase II general transcription initiation factor activity

**Comment by sarach06** [comment]
Hi Val,
Thank you very much for this. I changed the mapping to GO:0016251, as you suggested. It will be available in InterPro 98.0.

Best,
Sara
