### ISSUE TITLE
PTN000553037 not GO:1901800 | positive regulation of proteasomal protein catabolic process | 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4900]
* **PTHR ID & PTN node:**

PTN000553037

GO:1901800 | positive regulation of proteasomal protein catabolic process | IBA with  , P35998 , S000002165

* **Sequences with problematic annotation (ID + gene/protein name):**

proteasome regulatory subunits:

rpt1 https://www.pombase.org/gene/SPBC16C6.07c
also has part_of
GO:0043161 | proteasome-mediated ubiquitin-dependent protein catabolic process

rpt3 https://www.pombase.org/gene/SPCC576.10c
GO:1901800 | positive regulation of proteasomal protein catabolic process | IBA with P35998 , PTN000553037 , S000002165

(this is *within pathway* regulation (i.e part_of for GO)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

annotation 
@edwong57 

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
The annotation seems not to exist anymore.
