### ISSUE TITLE
IEA with IPR039198 GO:0001227	 DNA-binding transcription repressor activity, RNA polymerase II-specific 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4903]
* **InterPro ID / label**

IEA with IPR039198

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC800.02 (mapping filtered, see. 

SGD https://www.yeastgenome.org/locus/S000005609/go#comp
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q9HGL9

* **Description of issue**
* 
Not DNA binding

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. I removed the term from this entry, which will be visible in the next InterPro release.
Best wishes,
Sara
