### ISSUE TITLE
 IEA with IPR045148 GO:0003712	 transcription coregulator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4904]
* **InterPro ID / label**

 IEA with IPR045148

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC13C5.02

* **Description of issue**

I don't see any evidence for  
GO:0003712 | transcription coregulator activity

note that the human orthologs are 
PRPF40A &B, these are involved in pre-mRNA processing.

These do bind to RNA pol II CTD post transcriptionally, are most likely some surveillance role.

**Comment by tony787** [comment]
Dear Val,
Happy New Year!
Thank you for this information. I have removed the GO:0003712 term from this entry.
The change will appear in the next InterPro release.
Wish you a good start of 2024!
Best wishes,
Toni
