### ISSUE TITLE
sro7. PTN000028271, PTN000028273 regulation vs. non regulation terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4906]
* **PTHR ID & PTN node:**

PTN000028271, PTN000028273

* **Sequences with problematic annotation (ID + gene/protein name):**

PomBase https://www.pombase.org/gene/SPAC1F3.03
SGD  https://www.yeastgenome.org/locus/S000006236
others

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

The yeast annotations are to part_or exocytosis and Golgi to plasma membrane transport, the  annotations  from metazoa seem to be to "regulation of" terms

<img width="1491" alt="GO PAINT-query-sro7" src="https://github.com/geneontology/go-annotation/assets/7359272/1b727bbc-37c9-40ea-9687-b6ef92abfbb3">

These seem to be part of the pathway in the GO sense, and not "regulation"
@pgaudet can you confirm that we would not annotate these to "regulation of"

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
I'm also not sure that the establishment polarity annotation is transferrable.   Determination of cell polarity occurs upstream of exocytosis. This is the only exoxytotic protein annotated to this term. I blocked this one.

**Comment by marcfeuermann** [comment]
Reviewed the regulation stuff and removed the  establishment polarity annotation.
