### ISSUE TITLE
PTN000270645  Tim54 not lipid kinase in fungi

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4907]
* **PTHR ID & PTN node:**

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

FThe lipid kinase activities described for meatazoa seem to be unlikely to be conserved in yeast

GO:0017050 | D-erythro-sphingosine kinase activity | IBA with MGI:1316649 , Q9NRA0 , MGI:1861380 , S000004250 , S000005697 , FBgn0030300 , DDB_G0272522 , FBgn0052484 , 620048 , PTN000270645 , DDB_G0284545 , Q9NYA1

This is all I found:
Tim54
https://f1000research.s3.amazonaws.com/manuscripts/28588/b9cfdbd7-e8a7-4346-ba92-e08242bc16be_25904_-_jeremy_g_wideman.pdf?doi=10.12688/f1000research.25904.1&numberOfBrowsableCollections=92&numberOfBrowsableInstitutionalCollections=5&numberOfBrowsableGateways=54

These results indicate that Tim54 and AGK likely share a common ancestor; however, the diacylglycerol kinase (DAGK) domain is now virtually undetectable in fungal sequences.
Tim54 is likely a divergent fungal AGK which lost the DAGK domain after the divergence of holomycota from holozoa (Figure 4).

 
Also
https://www.yeastgenome.org/locus/S000003590/go

**Comment by ValWood** [comment]
This one appears just to be propagated too broadly, its OK for
lcb4 https://www.pombase.org/gene/SPAC4A8.07c

**Comment by marcfeuermann** [comment]
Annotation has been blocked for the Tim54 node.
