### ISSUE TITLE
arg82 PTN000274018  not hexakisphosphate kinase activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4908]
* **PTHR ID & PTN node:**

arg82 | GO:0000828 | inositol hexakisphosphate kinase activity | IBA with Q96PC2 , MGI:1923750 , PTN000274018 , S000002424 , Q9UHH9 , Q92551 , Q57X56

I don't think inositol hexakisphosphate kinase activity can be transferred to arg82.
S000002424 is kcs1 which has a different specificity  to arg82
https://www.yeastgenome.org/locus/S000002580#go

arg82 does 2 steps, but they are different from  ksc1:
<img width="492" alt="inositol" src="https://github.com/geneontology/go-annotation/assets/7359272/6693d75d-416c-45fd-9c10-d7c52dd64ee5">

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation has been blocked for the arg82 node.
