### ISSUE TITLE
protein maturation by [4Fe-4S] cluster transfer (GO:0106035) vs GO:0016226 | iron-sulfur cluster assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4909]
This may be an ontology issue, or an annotation issue.

I have a number of protein that I have annotated to 
protein maturation by [4Fe-4S] cluster transfer (GO:0106035)
because they 
Definition 
The transfer of an assembled 4Fe-4S] cluster from a scaffold protein to an acceptor protein that contributes to the attainment of the full functional capacity of a protein.

For these I often get an annotation by PAINT to GO:0016226 | iron-sulfur cluster assembly
(but this pathway seems to proceed protein maturation by [4Fe-4S] cluster transfer (GO:0106035)

e.g.
nar1
GO:0016226 | iron-sulfur cluster assembly | IBA with Q9H6Q4 , MGI:1914813 , PTN000177496 , S000005184

cia2
GO:0016226 | iron-sulfur cluster assembly | IBA with Q9Y3D0 , locus:2199362 , PTN000272123 , S000001164

nfu2
GO:0016226 | iron-sulfur cluster assembly | IBA with locus:2088781 , locus:2120745 , locus:2008311 , S000001523 , Q9UMS0 , locus:2141400 , PTN004238686 , locus:2158849

* **Sequences with problematic annotation (ID + gene/protein name):**

see above

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I'm not sure. To me this seems like the annotation is not quite correct.
If  GO:0016226 | iron-sulfur cluster assembly
is acceptable then it should probably be an ancestor of 
protein maturation by [4Fe-4S] cluster transfer (GO:0106035)
but that doesn't seen quite right?

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
This is a useful ticket showing the pathway:
https://github.com/geneontology/go-annotation/issues/2217
Maybe the first step is to figure out  what should be included in the pathway, what is a MF and whats a BP

**Comment by ValWood** [comment]
more history
https://github.com/pombase/curation/issues/2167

**Comment by marcfeuermann** [comment]
I've removed PAINT annotation to assembly term and replaced by protein maturation by [4Fe-4S] cluster transfer (GO:0106035) when available.
