### ISSUE TITLE
Review annotations to GO:0003933  GTP cyclohydrolase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4913]
GO:0003933 GTP cyclohydrolase activity

**Comment by pgaudet** [comment]
- [ ] **InterPro:IPR003801 GTP cyclohydrolase FolE2/MptA > GO:GTP cyclohydrolase activity ; GO:0003933** >> change mapping to [GO:0003934 GTP cyclohydrolase I activity](https://amigo.geneontology.org/amigo/term/GO:0003934#display-lineage-tab)
- [ ] **InterPro:IPR007839 GTP cyclohydrolase III > GO:GTP cyclohydrolase activity ; GO:0003933**  >> change mapping to GO:0043740 GTP cyclohydrolase IIa activity
- [ ] **InterPro:IPR022840 GTP cyclohydrolase MptA > GO:GTP cyclohydrolase activity ; GO:0003933** >> change mapping to [GO:0044682 archaeal-specific GTP cyclohydrolase activity](https://amigo.geneontology.org/amigo/term/GO:0044682#display-lineage-tab)
- [ ] HAMAP:MF_01527 > GO:GTP cyclohydrolase activity ; GO:0003933
- [ ] UniRule:UR000078507 > GO:GTP cyclohydrolase activity ; GO:0003933

**Comment by sarach06** [comment]
Hi Pascale,
Thank you very much for this. I have changed the terms in IPR003801 and IPR007839 but not in IPR022840 as it includes some bacterial matches (they are TrEMBL sequences, 16% of the total sequences included in the model) so I would leave the current term due to taxon constraints. Let me know if you agree with this.
Best wishes,
Sara

**Comment by pgaudet** [comment]
Thanks @sarach06, this look fine to me. The description of the entry specifically mentioned archae, this is why I suggested this. Thanks for checking.

**Comment by suzialeksander** [comment]
@pedruzzi has this UniRule change been made?

**Comment by pedruzzi** [comment]
@suzialeksander  now yes :innocent:. I replaced GO:0003933 with GO:0044682 GTP cyclohydrolase IV activity (the archaeal-specific activity). Although the rule touches both archaea and bacteria, there is a condition in the rule that annotates bacteria with GO:0003934 and archaea with GO:0044682.
Thanks

**Comment by suzialeksander** [comment]
done.
