### ISSUE TITLE
Review annotations to GO:1990274 mitotic actomyosin contractile ring disassembly  & regulation children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4915]
Dear all, 

The proposal has been made to obsolete 
GO:1990274 mitotic actomyosin contractile ring disassembly, and its regulation children, 
see https://github.com/geneontology/go-ontology/issues/26711

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1b4N0XSS2_bFRvnMRLwYr23QhQpXV8eID0ukKmhrm-oM/edit#gid=0

Impacted groups: 
SGD 6
PomBse 4

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by ValWood** [comment]
Actually, no need to review, these will have direct replacement, no action necessary.

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
