### ISSUE TITLE
Review annotations to GO:0009917 sterol 5-alpha reductase activity & GO:0009918 sterol delta7 reductase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4918]
Dear all, 

The proposal has been made to obsolete 
GO:0009917 sterol 5-alpha reductase activity 
GO:0009918 sterol delta7 reductase activity

see https://github.com/geneontology/go-ontology/issues/26736

Experimental annotations that need to be reviewed are here: 

https://docs.google.com/spreadsheets/d/1XwCvZjbpv2K-SmyjrveUReb-tPZ6yLhB1G5wnAUr3mM/edit#gid=0

Impacted groups: 
TAIR
UniProt

Note that the annotations will be automatically replaced.

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by tberardini** [comment]
TAIR annotations have been automatically updated.

**Comment by tberardini** [comment]
UniProt annotation remains. @pgaudet please go ahead and close if appropriate.
