### ISSUE TITLE
Review annotations to GO:0039526 perturbation by virus of host apoptosis - to be merged with 'symbiont' equivalents

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4919]
- [ ] GO:0019051 induction by virus of host apoptotic process >> replace by GO:0052151 symbiont-mediated activation of host apoptosis
- [ ] GO:0019050 suppression by virus of host apoptotic process  >> replace by GO:0033668 symbiont-mediated suppression of host apoptosis
- [ ] GO:0039526 perturbation by virus of host apoptosis  >> replace by  GO:0052150 symbiont-mediated perturbation of host apoptosis

Annotations are here: https://docs.google.com/spreadsheets/d/1olgiDggXYbI5bxS7hn9DfowwiuvrbHzEUqfzopP_xiM/edit#gid=0

All annotations will be replaced automatically except for CACAO. 

Other groups with annotations (in case you want to check):

- MGI
- ParkinsonsUK-UCL
- UniProt
- ZFIN

There are also 6 InterPro mappings, 
5 keywords and 3 UniRule/HAMAP mappings. 

Thanks, Pascale

**Comment by pgaudet** [comment]
https://docs.google.com/spreadsheets/d/1olgiDggXYbI5bxS7hn9DfowwiuvrbHzEUqfzopP_xiM/edit#gid=0

**Comment by Antonialock** [comment]
keywords done
