### ISSUE TITLE
Review annotations to GO:1990124 messenger ribonucleoprotein complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4920]
Dear all, 

The proposal has been made to obsolete GO:1990124 messenger ribonucleoprotein complex
see https://github.com/geneontology/go-ontology/issues/26431

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/15C4GnPdjEgfux9fr8pY9VyNsYlx996UltFzLmGykC6s/edit#gid=0

Impacted groups: 
   ~4 CAFA~
   ~5 FlyBase~
   7 RGD
  ~22 UniProt~

Thanks.

**Comment by hattrill** [comment]
FB done

**Comment by Antonialock** [comment]
Uniprot done. I wasn't sure if I can replace "ARVCF occurs in large RNA-containing complexes that contain both spliced and unspliced mRNAs of housekeeping genes." with an existing term? Is it known what this is?

**Comment by Antonialock** [comment]
@ValWood it's from PMID:24644279

**Comment by ValWood** [comment]
It looks quite poorly characterised with conflicting annotations. I would probably lose that annotation. It sounds more like it is describing a  nuclear  body  (which have lots of RNAs in none stoichiometric amounts) than a complex per se.

**Comment by Antonialock** [comment]
thanks, all done then

**Comment by slaulederkind** [comment]
RGD finished.

**Comment by vanaukenk** [comment]
@ValWood 

WormBase annotations done
