### ISSUE TITLE
Review annotations to GO:0035071 salivary gland cell autophagic cell death /GO:0035072 ecdysone-mediated induction of salivary gland cell autophagic cell death

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4921]
Dear all, 

The proposal has been made to obsolete 
GO:0035071 salivary gland cell autophagic cell death
GO:0035072 ecdysone-mediated induction of salivary gland cell autophagic cell death
see https://github.com/geneontology/go-ontology/issues/25605

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1ydWxyImxKUIPhg-syJT-o0lsBGWRzlGhKvvnNBRav8Q/edit#gid=0

Impacted groups: 
 34 FlyBase

Thanks.

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
