### ISSUE TITLE
Review annotations to GO:0019907 cyclin-dependent protein kinase activating kinase holoenzyme complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4922]
Dear all, 

The proposal has been made to obsolete 
GO:0019907 cyclin-dependent protein kinase activating kinase holoenzyme complex
see https://github.com/geneontology/go-ontology/issues/26676

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/17KQqyBbMK-_gh3TygKZrwm4hChlCUn6NhdEw6DHGy-Y/edit#gid=0

Impacted groups: 
   ~2 CAFA~
   3 ComplexPortal
   ~1 PomBase~ DONE
  ~5 UniProt~

Thanks.

**Comment by Antonialock** [comment]
Uniprot done

**Comment by Antonialock** [comment]
and CAFA

**Comment by suzialeksander** [comment]
just waiting on ComplexPortal looks like.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by ValWood** [comment]
OK all done

@suzialeksander  note that this was only open 3 days,  groups have longer to fix
