### ISSUE TITLE
Review annotations to GO:1901998 toxin transport and GO:1902007 regulation of toxin transport

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4923]
Dear all, 

The proposal has been made to obsolete 
GO:1901998 toxin transport
GO:1902007 regulation of toxin transport
see https://github.com/geneontology/go-ontology/issues/26720

The reason for obsoletion is that the term toxin transport is vague. May consider transfer annotations to GO:1990748 cellular detoxification.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1LJ_mpC4hwCK2LoHXXKjm_3ZA1UVjEFV4ZuZTpBdSFoc/edit#gid=0

Impacted groups: 
UCL 18
CAFA 4
EcoCyc 3
UniProt 2
CACAO 1

----

Mappings that need to be reviewed:
InterPro:IPR041408 Hemolysin coregulated protein (Hcp) TssD > GO:toxin transport ; GO:1901998

Thanks.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by RLovering** [comment]
UCL done

**Comment by Antonialock** [comment]
CAFA and uniprot fixed
