### ISSUE TITLE
Review annotations to GO:0019933 cAMP-mediated signaling  & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4925]
GO:0019933 cAMP-mediated signaling represents the same pathway as adenylate cyclase-activating G protein-coupled signaling pathway, see https://github.com/geneontology/go-ontology/issues/20712

Annotations are here: https://docs.google.com/spreadsheets/d/17fLb5JVbiTTgpsWmXKdzWSkp1rRd_cic2XO1azel6Gg/edit#gid=0

**Comment by RLovering** [comment]
UCL done, note I found a few more annotations to revise in QuickGO, the majority were NAS/TAS

**Comment by suzialeksander** [comment]
Annotation Review is out-of-date and was closed
