### ISSUE TITLE
Review annotations to GO:0007231 osmosensory signaling pathway & some children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4928]
GO:0000161  osmosensory signaling MAPK cascade
~GO:0007231 osmosensory signaling pathway~
GO:0140531 regulation of osmosensory signaling MAPK cascade
GO:0140532 negative regulation of osmosensory signaling MAPK cascade

**Comment by pgaudet** [comment]
@srengel FYI
No action needed, all annotations will be remapped

**Comment by RLovering** [comment]
Hi Pascale

why is GO:0007231 osmosensory signaling pathway being removed? UCL has 3 exit annotations to this term.  Sorry I couldn't find any other information about this

Best

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 

Sorry, GO:0007231 osmosensory signaling pathway is **not** being obsoleted, only these: 

GO:0000161 osmosensory signaling MAPK cascade > GO:0038066 'p38MAPK cascade'
GO:0140531 regulation of osmosensory signaling MAPK cascade > GO:1900744 regulation of p38MAPK cascade
GO:0140532 negative regulation of osmosensory signaling MAPK cascade > GO:1903753 negative regulation of p38MAPK cascade

**Comment by RLovering** [comment]
thanks ;)

**Comment by robnash** [comment]
Just saw the proposal re the obsoletion notice. Can there at least be some synonyms added to the p38MAPK terms as yeast researchers usually do not refer to this as a p38MAPK cascade?
