### ISSUE TITLE
Review annotations to  GO:0031098 stress-activated protein kinase signaling cascade and GO:0051403 'stress-activated MAPK cascade and regulation children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4930]
GO:0031098 stress-activated protein kinase signaling cascade
GO:0051403 'stress-activated MAPK cascade
GO:0032872 regulation of stress-activated MAPK cascade
GO:0070302 regulation of stress-activated protein kinase signaling cascade
GO:0032873 negative regulation of stress-activated MAPK cascade
GO:0070303 negative regulation of stress-activated protein kinase signaling cascade
GO:0032874 positive regulation of stress-activated MAPK cascade
GO:0070304 positive regulation of stress-activated protein kinase signaling cascade

**Comment by deustp01** [comment]
we have used GO:0051403 ([R-HSA-450294](https://reactome.org/content/detail/R-HSA-450294))

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1-qbatxU2Ppgrbzjmc_5-2xBGSLioKtAE1ibEQ5Rv4I4/edit#gid=0

**Comment by suzialeksander** [comment]
Annotation Review is out-of-date and was closed
