### ISSUE TITLE
PTN000527275   PTN000383725 not all "RISC complex" (GO:0016442)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4932]
* **PTHR ID & PTN node:**

[PTN000527275](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000527275)

[PTN000383725](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000383725)

* **Sequences with problematic annotation (ID + gene/protein name):**

ago1 https://www.pombase.org/gene/SPCC736.11
[O74957](https://www.uniprot.org/uniprot/O74957)

and

dcr1 https://www.pombase.org/gene/SPCC188.13c
* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Propagation.

RISC is RISC complex is involved in posttranscriptional repression of gene expression through downregulation of translation or induction of mRNA degradation.

fission yeast doesn't do  posttranscriptional repression (It has RITS which is a different composition)

**Comment by marcfeuermann** [comment]
Both families have been updated.
