### ISSUE TITLE
 IPR016685 not all RISC

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4933]
* **InterPro ID / label**

 IPR016685 

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC645.08c

* **Description of issue**

See
https://github.com/geneontology/go-annotation/issues/4932

**Comment by blazaropinto** [comment]
Thank you for this Val, I changed RISC complex for the parent GO:0031332, which includes RITS complex. The changes will be visible in the next release.

Best, 
Beatriz
