### ISSUE TITLE
Review annotations to some transcription/translation virus/symbiont terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4934]
See https://github.com/geneontology/go-ontology/issues/26747

- GO:0046778 modification by virus of host mRNA processing': no annotations, no mappings. Unnecessary grouping class.
- GO:0046783 modification by virus of host polysomes
- GO:0019056 modulation by virus of host transcription
-  GO:0044073 modulation by symbiont of host translation
- GO:0044074 negative regulation by symbiont of host translation
- GO:0042786 evasion of host immune response via modulation of host antigen processing and presentation
- GO:0052064 symbiont-mediated activation of reactive oxygen species production in host cell

**Comment by pgaudet** [comment]
3 CACAO annotations need to be replaced, see https://docs.google.com/spreadsheets/d/1Dezwb_YDN0ICsS-y7ne-lXEUiNnU1rD-DzGUHQpLELc/edit#gid=0

Others will be automatically remapped.

**Comment by genegodbold** [comment]
Hey @pgaudet, you're cranking through these! :-)

**Comment by dsiegele** [comment]
@pgaudet  I fixed the CACAO annotations.
