### ISSUE TITLE
Review annotations to GO:1905538 polysome binding  & regulation children

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4935]
Dear all, 

The proposal has been made to obsolete GO:1905538 polysome binding, and its regulation children, 
see https://github.com/geneontology/go-ontology/issues/26170

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1ETWpaqztdAmlvRhUOv-MqUsK0bGMkVYAKQT3VkEtols/edit#gid=0

Impacted groups: 
UniProt 11
MGI 4
TAIR 2
SGD 1
UCL 1

----

Mappings that need to be reviewed: None.

Thanks.

**Comment by srengel** [comment]
SGD done.

**Comment by RLovering** [comment]
UCL done - thanks

**Comment by LiNiMGI** [comment]
MGI done, thanks!

**Comment by Antonialock** [comment]
Uniprot done
