### ISSUE TITLE
PTN000558564 O74518 not TRAMP

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4938]
* **PTHR ID & PTN node:**

GO:0031499 | TRAMP complex | IBA with S000005475 , Q8NDF8 , cid14 , PTN000558564 , S000005243 | GOREF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC663.12 
O74518

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Proapagation.This is likely to be a tricky on.
Pombe Cid14 (which is Tram) is in the inferred from list)

Cid 12 is part of RNA-directed RNA polymerase complex (RNAi oathwya, which is absent from S. cerevisiae)

**Comment by marcfeuermann** [comment]
Corrected.
