### ISSUE TITLE
Review annotations to GO:0010823 negative regulation of mitochondrion organization and GO:0010822 positive regulation of mitochondrion organization

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#4942]
Dear all, 

The proposal has been made to obsolete GO:0010823 negative regulation of mitochondrion organization and GO:0010822 positive regulation of mitochondrion organization:
https://github.com/geneontology/go-ontology/issues/26782

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1h46Ns8_NjMbJRa8ubXgYag_J4wPvBql7OPvnrztRhwQ/edit?usp=sharing

Impacted groups: 
ARUK-UCL 2 -done
ParkinsonsUK-UCL 4 - done
UniProt 5
BHF-UCL 1 - done

Thanks.

**Comment by pgaudet** [comment]
UniProt annotations fixed

**Comment by RLovering** [comment]
UCL annotations fixed

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error report
