### ISSUE TITLE
Review annotations to GO:0019071 viral DNA cleavage involved in viral genome maturation

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4943]
Dear all, 

The proposal has been made to obsolete GO:0019071 viral DNA cleavage involved in viral genome maturation
see https://github.com/geneontology/go-ontology/issues/26134

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1_GlqvjiwwgvatZ_VG-44yoVGMeW2i8VPKWeJ9P0-RsE/edit#gid=0

Impacted groups: 
CACAO 1

----

Mappings that need to be reviewed: none

Thanks.

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error report
