### ISSUE TITLE
Review annotations to GO:0044030 regulation of DNA methylation & positive and negative children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4945]
GO:0044030 regulation of DNA methylation
GO:1905642 negative regulation of DNA methylation
GO:1905643 positive regulation of DNA methylation

Annotations are here: https://docs.google.com/spreadsheets/d/1xojPzweyOAJiOZqyuwH3M75q5fL3g0oPIwEfUji8L6s/edit#gid=0

Impacted groups: 
- 3 BHF
- 2 Complex Portal
- 7 MGI
- 18 TAIR

InterPro:IPR015270 Protein RDM1, plant > GO:regulation of DNA methylation ; GO:0044030: change to [gene silencing by RNA-directed DNA methylation](http://purl.obolibrary.org/obo/GO_0080188)

Thanks, Pascale

**Comment by LiNiMGI** [comment]
MGI annotations were already fixed under ticket 4729.

**Comment by pgaudet** [comment]
Thanks Li!

**Comment by blazaropinto** [comment]
Thanks Pascale, I updated this term, the changes will be visible in the next release.

Best,
Beatriz

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error report
