### ISSUE TITLE
PTN000124276 , DNA repair

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4950]
* **PTHR ID & PTN node:**

GO:0006281 | DNA repair | IBA with PTN000124276 , S000001141

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1F5.11c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation, should now be

GO:0140861 | DNA repair-dependent chromatin remodeling

@edwong57 

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by pgaudet** [comment]
I dont see the primary annotation in PAINT - did you just add that ?

**Comment by ValWood** [comment]
The annotation is not present yet, the existing EXP annotation would need revising at SGD
I made the annotation at PomBase by IC from NuA4 histone acetyltransferase complex (GO:0035267)

I was looking at the intersection between DNA repair and GO:0140861 | DNA repair-dependent chromatin remodeling
https://www.pombase.org/results/from/id/73947c3f-19dd-4dd4-880d-fc1e405e75b4
to check the annotations on the chromatin remodelling complexes. This was the only one remaining.

**Comment by marcfeuermann** [comment]
I removed DNA-repair. We will have to wait right terms to be available.

**Comment by marcfeuermann** [comment]
The term is now available from a Flybase annotation. Done.
