### ISSUE TITLE
Review annotations to GO:0039503 suppression by virus of host innate immune response

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4951]
Dear all, 

The proposal has been made to obsolete GO:0039503 suppression by virus of host innate immune response, see
https://github.com/geneontology/go-ontology/issues/26859

2 CACAO
23 UniProt (will be automatically replaced)

**Comment by pgaudet** [comment]
- [ ] InterPro:IPR009179 Protein E3 > GO:suppression by virus of host innate immune response ; GO:0039503
- [ ] HAMAP:MF_04073 > GO:suppression by virus of host innate immune response ; GO:0039503
- [ ] HAMAP:MF_04143 > GO:suppression by virus of host innate immune response ; GO:0039503
- [ ] UniRule:UR000584809 > GO:suppression by virus of host innate immune response ; GO:0039503
- [ ] UniRule:UR001372527 > GO:suppression by virus of host innate immune response ; GO:0039503
- [ ] UniProtKB-KW:KW-1090 Inhibition of host innate immune response by virus > GO:suppression by virus of host innate immune response ; GO:0039503


These should be replaced by GO:0052170 symbiont-mediated suppression of host innate immune response.

**Comment by blazaropinto** [comment]
Thanks Pascale, I think this term is a perfect replacement. The changes will be visible in the next release.

Best,
Beatriz

**Comment by Antonialock** [comment]
KW fixed

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
