### ISSUE TITLE
IPR006168 Glycerol-3-phosphate dehydrogenase, NAD-dependent

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4952]
* **InterPro ID / label**
IPR006168 Glycerol-3-phosphate dehydrogenase, NAD-dependent

* **Description of issue**
This entry says "NAD-dependent glycerol-3-phosphate dehydrogenase (1.1.1.8) (GPD) catalyzes the reversible reduction of dihydroxyacetone phosphate to glycerol-3-phosphate. It is a cytoplasmic protein, active as a homodimer"

It has a GO-CC annotation of glycerol-3-phosphate dehydrogenase complex (GO:0009331).

But GO:0009331 is for a different (but related!) glycerol-3-phosphate dehydrogenase complex - the current GO:0009331 def ("An enzyme complex that catalyzes the dehydrogenation of sn-glycerol 3-phosphate to form glycerone phosphate.") needs improvement to make this clearer, but it has a reference of PMID:7576488 and a relation of 'capable of GO:0004368 glycerol-3-phosphate dehydrogenase (quinone) activity' = Catalysis of the reaction: sn-glycerol 3-phosphate + a quinone = glycerone phosphate + a quinol. (EC:1.1.5.3).

So, please remove GO:0009331 from IPR006168.

GO:0009331 is correctly on this other InterPro entry: IPR000447 FAD-dependent glycerol-3-phosphate dehydrogenase
Should GO:0009331 also be on the child entry for the GlpA subunit - Glycerol-3-phosphate dehydrogenase, GlpA subunit (IPR017752) ?
And maybe also this other entry for the GlpB subunit - Glycerol-3-phosphate dehydrogenase, GlpB subunit (IPR009158)?
And the GlpC subunit - Glycerol-3-phosphate dehydrogenase, GlpC subunit (IPR017753)

**Comment by sjm41** [comment]
Actually, I don't think GO:0009331 should be on "IPR000447 FAD-dependent glycerol-3-phosphate dehydrogenase" either  since IPR000447 appears to be for both eukaryotic and bacterial EC:1.1.5.3 enzymes, and only the bacterial enzyme is described as a complex, as far as I can tell.
So I think GO:0009331 should only be on the entries for the individual bacterial subunits, IPR017752, IPR009158 and IPR017753.

**Comment by blazaropinto** [comment]
Thank you Steven, the term GO:0009331 is now in IPR017752, IPR009158 and IPR017753 but not in IPR006168. The changes will be visible in the next release.

Best,
Beatriz
