### ISSUE TITLE
Review annotations to GO:0009331 glycerol-3-phosphate dehydrogenase complex

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4953]
This term may have been applied to the wrong species, see https://github.com/geneontology/go-ontology/issues/26862

GO:0009331 glycerol-3-phosphate dehydrogenase complex

**Comment by pgaudet** [comment]
@sarach06 @blazaropinto @tony787 
Can you please review IPR006168 and IPR000447? 

@pedruzzi 
Can you please review UniRule:UR000067708 and 	UniRule:UR000080073? 

Are these always 'complexes'? According to @sjm41 , in eukaryotes this is a monomer

**Comment by pgaudet** [comment]
Please wait before implementing this, it seems this may be a complex after all... 
https://github.com/geneontology/go-ontology/issues/26862#issuecomment-1909556056

**Comment by sjm41** [comment]
I already made an InterPro2GO ticket for this here: https://github.com/geneontology/go-annotation/issues/4952

**Comment by blazaropinto** [comment]
Thank you Pascale, I just worked on the ticket mentioned above by Steven, so those entries are checked for this term now :)
Best,
Beatriz
