### ISSUE TITLE
4 The mouse annotations seem to be for 2 lncRNA (Although they all appear to be for the same locus)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4954]
The mouse annotations seem to be for 2 lncRNA (although they all appear to be 
for the same locs using different identifiers. I think some of these correspond to degradation products?

<img width="1352" alt="Screenshot 2024-01-23 at 10 03 03" src="https://github.com/geneontology/go-ontology/assets/7359272/06c34494-c14d-47a2-b31f-c229f045ecc1">

<img width="899" alt="Screenshot 2024-01-23 at 09 56 35" src="https://github.com/geneontology/go-ontology/assets/7359272/2aa5c614-ad4f-4fc8-983a-1946e8f75ce8">

- [ ] If this *is* the case, before this becomes a larger issue,  perhaps we need to mandate curators to ONLY use the primary Identifiers for a non-coding RNA unless a specific variant is required?

_Originally posted by @ValWood in https://github.com/geneontology/go-ontology/issues/26471#issuecomment-1906059093_

**Comment by ValWood** [comment]
@LiNiMGI  comment transferred from
https://github.com/geneontology/go-ontology/issues/26471

I am not sure why you got: MGI 6 annotations for 2 genes

**Comment by ValWood** [comment]
@ValWood  comment transferred from
comment transferred from
https://github.com/geneontology/go-ontology/issues/26471

This propagation may be performed by RNACentral.  They may propagate the GO annotations to all of the versions of the RNA at a specific locus. This would often not be appropriate (especially for the degradation fragments as these aren't functional entities). I will find out.... @blakesweeney

**Comment by ValWood** [comment]
@blakesweeney 
comment transferred from
https://github.com/geneontology/go-ontology/issues/26471

Hi, RNAcentral doesn't propogate terms between overlapping transcripts. The only propogation we do is from Rfam families to sequences matching the families. I'm not sure where the terms come from as what we show is meant to be a reflection of QuickGO. Is there a case I should look into to see what is happening?

**Comment by ValWood** [comment]
(I put the comment in the wrong ticket)

Hi @alexsign 

MGI annotated a lncRNA MGI:1916420
but the GO annotation is propagated onto degradation fragments.

Do you know where/how this happens? It makes it appear that there are numerous annotated entities, but the annotation should only be on the full length transcript as that is the only version which has the regulatory activity.

**Comment by ValWood** [comment]
@alexsign response


@ValWood based on previous cases I assume it's because of MGI to RNAcental mapping:

MGI:MGI:1916420 RNAcentral:URS00009ADEA8_10090
MGI:MGI:1916420 RNAcentral:URS00009B7330_10090
MGI:MGI:1916420 RNAcentral:URS00009BC4F4_10090
MGI:MGI:1916420 RNAcentral:URS00009BE664_10090
MGI:MGI:1916420 RNAcentral:URS0000A8D3FF_10090
MGI:MGI:1916420 RNAcentral:URS0000A9FC7D_10090

which I get from
[https://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fftp.ebi.ac.uk%2Fpub%2Fdatabases%2FRNAcentral%2Fcurrent_release%2Fid_mapping%2Fdatabase_mappings&data=05%7C02%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C4ee59f068f014d2e3c6608dc1da38131%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638417835279682930%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eC8eLgv%2FVwbtF2rPudtl3bbjutrUVOe%2BtWgTXt4bV5Q%3D&reserved=0)
Most likely you need to contact RNAcentral to fix it

**Comment by blakesweeney** [comment]
I'm happy to correct incorrectly assigned mappings, but I'm not clear on which ones we are providing that are wrong.

**Comment by ValWood** [comment]
Hi Blake,

So here are some mapped examples with their coordinates
https://rnacentral.org/rna/URS00009ADEA8/10090
73,194,054	73,207,996

https://rnacentral.org/rna/URS00009B7330/10090 
73,193,785 .. 73,207,895

https://rnacentral.org/rna/URS00009BC4F4/10090
73,193,991	73,205,668

https://rnacentral.org/rna/URS00009BE664/10090
73,193,784	73,207,992

https://rnacentral.org/rna/URS0000A8D3FF/10090
73,188,951	73,208,143

These are all slightly different versions of the same entity, but for GO only a single entity should be mapped, the one which corresponds to the annotated object at MGI
which is Chr7:73189549-73208143
https://www.informatics.jax.org/marker/MGI:1916420

Other versions appear to be derived from the same locus, they include cDNAs from various sources and degradation products.  I'm finding it quite difficult to figure out if there is a "gene ID " for the entire locus that corresponds to the annotated version at MGI.

I tried to trouble shoot further by tracing the source of these other variants in the  RNA central browseable view on the gene pages, but there seems to be a bug which makes it difficult to scroll and then click on a specific identifier. So I can't describe exactly what causes the problem. From a GO perspective the problem is that this will over-inflate the numbers of RNAs with specific GO functions and activities, which means that when users perform enrichment analyses thay may miss statistically significant enrichments. This is probably not an immediate problem because most users are unlikely to perform enrichment on RNA datasets, but it is still somewhat confusing to see a single biological entity represented multiple times in QuickGO with different identifiers.

I should note that this isn't a problem in AmiGO which uses the MGI Identifier
https://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1916420

So I guess the solution is only to map the GO data to a single ID which describes the annotated object/locus, but in this case, I can't work out which ID this would be?

**Comment by ValWood** [comment]
Here is an example in AmiGO

Homo sapiens (human) CDKN2B antisense RNA 1 (CDKN2B-AS1)

https://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS0000732D5D_9606 Homo sapiens (human) CDKN2B antisense RNA 1 (CDKN2B-AS1)
https://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS0000E7A1EE_9606 Homo sapiens (human) CDKN2B antisense RNA 1
https://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS000048C294_9606 Homo sapiens (human) CDKN2B antisense RNA 1
https://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS00000A3606_9606 Homo sapiens (human) CDKN2B antisense RNA 1
https://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS0000D62B72_9606 Homo sapiens (human) CDKN2B antisense RNA 1
plus others

These are all the same entity, most are mapped to "heterochromatin formation" which will o overinflate the  annotation numbers to this term.

**Comment by blakesweeney** [comment]
The MGI data was imported once a while ago. I don't actually recall how it works, so it is very possible we are messy in mapping ids internally. This could lead to automated tools which map to the URS_taxids getting very vague mappings. I can look into this at some point.

**Comment by blakesweeney** [comment]
I'm looking into this a bit and I'm confused about what the correct thing would be to do here. As far as I can tell MGI puts 12 transcripts in their gff3 files for `MGI:1916420`. To me it seems reasonable to try and import them all and so they are all marked as being transcripts for gene `MGI:1916420` in RNAcentral. I dont' think trying to skip transcripts would be a good idea here. If there is an easy way to get what MGI considers the primary transcript we can import that as well. Not sure how we will indicate it but I can think about something.

As far as I know we don't do any mapping for GO annotations, so I don't think we create the overly broad annotation. It is possible we did and I just don't see where it happened though. Is it possible that someone wanted to annotate that transcript with a GO term and just mapped from `MGI:1916420` to all RNAcentral sequences from that gene? If so that is always going to lead to annotating all transcripts in the gene.

I think the best thing we could do in this case would be to write other more precise ids into our ID mapping file if desired. It seems like there are ensembl transcript ids and NCBI ids that are avaiable, so adding those should be easy. I'll be happy to do that if someone let's me know what would be more helpful or if I am misunderstanding something.

**Comment by ValWood** [comment]
I was going to raise the issue at the upcoming GO consortium meeting, but it isn't really a GO issue, it only affects the data in GOA (the MGI annotation is correctly represented in the GO database). 
Since I can't work out the problem either, I don't know what the solution would be.
 I'll assign the ticket to @alexsign  but it probably isn't a big issue unless the numbers of propagations become large. Maybe wait and see if other examples come along?

**Comment by alexsign** [comment]
@ValWood Hi Val, I'm not sure why you assigned this to me. I'm getting data from MGI and RNAcentral. As @blakesweeney stated above "As far as I can tell MGI puts 12 transcripts in their gff3 files for MGI:1916420. To me it seems reasonable to try and import them all and so they are all marked as being transcripts for gene MGI:1916420 in RNAcentral.", which means it's originated at MGI, right?
In the QuickGO we using RNAcentral identifiers and if mapping from MGI is correct then our annotations data is correct as well.

**Comment by ValWood** [comment]
OK, I remove you and assigned to @LiNiMGI

**Comment by LiNiMGI** [comment]
@ValWood 
Hi Val,
I talked with MGI sequence group, and was told: 
MGI doesn’t make mapping of MGI genes to RNAcentral. 
MGI doesn’t map GO annotations to all the associated sequences of that gene.
As for represented sequences for non-coding RNA genes, MGI is not aware of anything similar to reference proteome for proteins. 

By looking at the mouse isoform file we get from GOA, I also see many gene level GO annotations were propagated to the isoforms/fragments of the genes.  
So I suspect this is not a lncRNA only issue?

Yes, maybe we should discuss further in the upcoming GOC meeting.
Thanks,
Li

**Comment by ValWood** [comment]
OK, I guess this is just a "feature" of GOA that I hadn't considered before, because all of the pombe genes are in UniProt non-redundantly. It's probably not a huge issue (well it isn't directly a GO issue) so  I don't know if we want to bring it to the consortium meeting. I'll leave that to @pgauget @cmungall  to decide.

It's mainly an issue for consumers of GO data from GOA, and if lots of RNA fragments get annotated with GO terms it could have the potential to distort enrichment results (and probably a bigger issue for ncRNAs because  they are likely to have many more 'fragment' entries.

It seems though that we would need to call it a feature, and if users want non-redundant datasets they should be using GO not GOA?

Anyway for now I'll close this ticket as it isn't something the consortium can easily address.
