### ISSUE TITLE
Review annotations to GO:0035179 larval turning behavior

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#4956]
Dear all, 

The proposal has been made to obsolete GO:0035179 larval turning behavior
see https://github.com/geneontology/go-ontology/issues/26850

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1kIIavxYOLWCe5JZrYxwn8iwS8kvd1WjCj3GATd1Tunc/edit?usp=sharing

Impacted groups: 
Flybase 3

Thanks.

**Comment by hattrill** [comment]
FB ones all done.
