### ISSUE TITLE
Add report in 'direct_annot_to_list_of_terms' and 'reg_ann_to_list_of_terms' to include a group with ECO_0000204

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4963]
We would like to add another report in the GH actions triggered by the labels 
`direct_ann_to_list_of_terms` and `reg_ann_to_list_of_terms`

to also include TAS and NAS? We end up missing Reactome (TAS) annotations. (and we might was well fix NAS annotations.)

Thanks, Pascale

@deustp01

**Comment by kltm** [comment]
[@pgaudet I directly edited yours above to clarify]

**Comment by kltm** [comment]
Let me clarify this a little. Currently, the GOlr query uses `evidence_subset_closure:ECO:0000006` directly--there is no "evidence list" being used. Is there another term that you wish to be used instead of `ECO:0000006` ("experimental evidence) as the single ECO term closure used? Otherwise, it would require some rewriting, and I'd want to ticket it as a separate project (i.e. not a trivial change).

**Comment by pgaudet** [comment]
Ha ! Makes sense. Could we have another report in the list of reports, to children of author statement http://purl.obolibrary.org/obo/ECO_0000204?

**Comment by kltm** [comment]
@mugitty I think this may be what @pgaudet was outlining?

**Comment by mugitty** [comment]
@kltm,
@pgaudet confirmed that this was the feature request

**Comment by pgaudet** [comment]
@kltm can this be implemented?

**Comment by pgaudet** [comment]
@cmungall

**Comment by pgaudet** [comment]
Please include this in the 'normal' EXP report if possible, or generate another report 'GOIDs__author-statement'

**Comment by kltm** [comment]
Clarifying for my own use, we want to have a union of results with (new) ECO:0000204 and (current) ECO:0000006.

**Comment by kltm** [comment]
@pgaudet PR at https://github.com/geneontology/go-annotation/pull/5290 . I think it's good to merge; if you have a moment for testing, could you merge it in and give it a spin?

**Comment by pgaudet** [comment]
This seems to be working correctly. Thanks @kltm !
