### ISSUE TITLE
Review annotations to GO:0047952 glycerol-3-phosphate dehydrogenase [NAD(P)+] activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4964]
NAD- and NADP-specific glycerol-3-phosphate dehydrogenase activity have been incorrectly obsoleted, see #21790. All 3 terms have now been restored, with the following taxon-specific distribution: 

- [glycerol-3-phosphate dehydrogenase (NAD+) activity](http://purl.obolibrary.org/obo/GO_0141152): only in eukaryotes
-  [glycerol-3-phosphate dehydrogenase [NAD(P)+] activity](http://purl.obolibrary.org/obo/GO_0047952): only in bacteria (see PMID:28326)
-  [glycerol-3-phosphate dehydrogenase (NADP+) activity](http://purl.obolibrary.org/obo/GO_0141153): only in archae (see PMID:15557260)

Annotations are here: https://docs.google.com/spreadsheets/d/1ZVgsKa7-DLxcfLyCb-D5t9FUGH25r-TwdazerNtdSok/edit#gid=0

The new terms should be available by next week (hopefully by Monday 2024-02-12). 

- AspGD   2
- FlyBase 1
- MGI 6
- PomBase 1
- RGD 3
- SGD 2
- DONE EcoCyc  2: checked, and unchanged
- DONE EcoliWiki   1: checked, and unchanged
-  DONE UniProt 1 : checked, and unchanged

Thanks, Pascale

**Comment by sjm41** [comment]
@blazaropinto @sarach06 I think there are also some InterPro2GO annotations to review here (apologies if you've already addressed these and I missed it):
IPR006109 Glycerol-3-phosphate dehydrogenase, NAD-dependent, C-terminal
IPR006168 Glycerol-3-phosphate dehydrogenase, NAD-dependent
IPR017751 Glycerol-3-phosphate dehydrogenase, NAD-dependent, eukaryotic
