### ISSUE TITLE
Review annotations to GO:0044876 'hercynylselenocysteine synthase'  and GO:1990412 'hercynylselenocysteine lyase activity (selenoneine-forming)' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4965]
- GO:0044876 'hercynylselenocysteine synthase' Obsolete Rhea ID used in xref: RHEA:42680: comment from RHEA: PMID:36071162 has demonstrated that this reaction does not take place
- GO:1990412 'hercynylselenocysteine lyase activity (selenoneine-forming)' Obsolete Rhea ID used in xref: RHEA:42696 comment from RHEA: PMID:36071162 has demonstrated that this reaction does not take place

**Comment by pgaudet** [comment]
@ValWood you have annotations to both these terms from PMID:24828577

Are you OK with the obsoletion? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes sure, go ahead.
