### ISSUE TITLE
Review annotations to GO:0000291 nuclear-transcribed mRNA catabolic process, exonucleolytic (and some descendants)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4966]
Dear all, 

The proposal has been made to obsolete:

GO:0000291 nuclear-transcribed mRNA catabolic process, exonucleolytic
GO:0043928. exonucleolytic catabolism of deadenylated mRNA
GO:0034428. nuclear-transcribed mRNA catabolic process, exonucleolytic, 5'-3'
GO:0070480 exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-independent decay

see 
https://github.com/geneontology/go-ontology/issues/26796

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1ncJtjqgpOCEaCckDA_1Olho5FfviJQ_j08TmW0ZQRUk/edit#gid=0

Impacted groups: 

 ~1 FlyBase~
   2 GeneDB
   1 PomBase
   1 SGD
   1 TAIR
 ~9 UniProt~

(I will add recommendations to the spreadsheet)
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

GO:0000291 | hamap2go | HAMAP:MF_03045 > GO:nuclear-transcribed mRNA catabolic process, 
GO:0000291 | unirule2go | UniRule:UR000187751 > GO:nuclear-transcribed mRNA catabolic process, exonucleolytic 

Thanks.

**Comment by deustp01** [comment]
Is there a suggested replacement for GO:0043928, which we have used for our pathway "[mRNA decay by 5' to 3' exoribonuclease](https://reactome.org/content/detail/R-HSA-430039
)"
Thanks

**Comment by ValWood** [comment]
Hi @deustp01 

The problem with the existing terms is that they combine a MF (exonuclease) and BP  (catabolism- which will be most likely be renamed 'decay'  to align with community language)

The endonuclease terms are not  specific for any pathway,  but  mix different nuclear surveillance pathways and cytoplasmic pathways together.

exonucleolytic catabolism of deadenylated mRNA (GO:0043928)
is not well defined  and it does not specify 5'-3'  (in fact most deadenylated decay will be 3'-5'? i.e. via TRAMP or the MTREC/exosome), so this might not be the term you needed.

Are you using this term in the context of NMD ( which is, or at least can be 5'-3')?
There is a term for this:
GO:0070478   nuclear-transcribed mRNA catabolic process, 3'-5' exonucleolytic nonsense-mediated decay
which I will likely relabel but the current meaning will be retained. Is this more suitable?

If this doesn't work, and you can tell me the specific pathways, I can let you know which terms appear to be the correct ones for those specific pathways.

My aim is to deal with the nuclear pathways first, but  while obsoleting unnecessary function focussed grouping terms I will ensure that people have the correct cytosolic pathway terms to migrate to.  I already have 56 terms in my basket and I'm sure we only need half of these!

**Comment by ValWood** [comment]
@pgaudet 

GO:0034427 | nuclear-transcribed mRNA catabolic process, exonucleolytic, 3'-5' | 
has an IEA mapping that did not get recognized by the script?
IEA with IPR028591

**Comment by deustp01** [comment]
Val,
This is the specific pathway - [](https://reactome.org/content/detail/R-HSA-430039). I know almost nothing about the biology here, so any suggestions would be really helpful!

**Comment by ValWood** [comment]
OK that's useful! I can use this as a reference. This seems to correspond to
"nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay (GO:0000288)"
but the GO term label and def is a bit unclear (but most of the children and annotations correspond to this).

I  was thinking of labelling this as 
"translation-associated, deadenylation-dependent mRNA decay"
to group  the cytosolic pathways associated with translation
i.e.
General mRNA decay (CCR4 -NOT), 
NO-GO and 
Non-stop decay.
because the pathways are interconnected. I had not thought beyond that because I'm concentrating on nuclear pathways first  but I think you can use

"nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay (GO:0000288)"
and eventually I will provide a list of complex-pathway mappings for the correct pathway terms (eventually).

**Comment by pgaudet** [comment]
@ValWood 

IPR028591 maps to GO:0034427, which is not listed in the original comment of the ticket. The script strictly takes these IDs into account.

**Comment by ValWood** [comment]
right, there is another ticket for 
https://github.com/geneontology/go-ontology/issues/24918
I  was going to repurpose, but the final decision was that there is conflation of multiple pathways so I will probably obsolete that too. I will look into that one further once I get to cytoplasmic (there are definitely multiple terms for the same process)

**Comment by ValWood** [comment]
comment from  @pgaudet  Can these terms be replaced by the parent GO:0006402 mRNA catabolic process ?

I will do a "replace by" but mostly but mostly people want to use a more specific pathway
(i.e NMD, non stop decay, nuclear surveillance etc etc), these terms group so many  different things.

I think in a  ideal world " mRNA catabolic process" will be a do not annotate term.

**Comment by tberardini** [comment]
TAIR done

**Comment by Antonialock** [comment]
uniprot done

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
