### ISSUE TITLE
Review annotations to GO:0044416 induction by symbiont of host defense response  & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4967]
Dear all, 

The proposal has been made to obsolete GO:0044416 induction by symbiont of host defense response and child
GO:0052391 induction by symbiont of defense-related host calcium ion flux

Ontology ticket: https://github.com/geneontology/go-ontology/issues/21260

Annotations are here: https://docs.google.com/spreadsheets/d/1Pw-qGx_hsmkesFotWq4iDr0otm0sDv0z5EprtQitGz8/edit#gid=0

There are 29 CGD annotations and 1 CAFA. 

Please remove/fix your annotations. 

Thanks, Pascale

**Comment by Antonialock** [comment]
uniprot fixed

**Comment by jlewsmith** [comment]
CGD done

**Comment by pgaudet** [comment]
Thanks!
