### ISSUE TITLE
PTN002599563 not all tryptophan biosynthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4968]
* **PTHR ID & PTN node:**

PTN002599563

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBP8B7.29

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation I think. This family also contains trp3 which is correctly annotated
i.e https://www.pombase.org/gene_subset/interpro:IPR019999 (corresponding InterPro)

You could probably also remove 
GO:0008153 para-aminobenzoic acid biosynthetic process 
https://github.com/geneontology/go-ontology/issues/26927
* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation reviewed.
