### ISSUE TITLE
Review annotations to dehydrogenase complexes

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4969]
Dear all, 

The proposal has been made to obsolete (all with replaced_by)
GO:0005967 mitochondrial pyruvate dehydrogenase complex
GO:0009353 mitochondrial oxoglutarate dehydrogenase complex
GO:0010240 plastid pyruvate dehydrogenase complex
GO:0045248 cytosolic oxoglutarate dehydrogenase complex
GO:0045250 cytosolic pyruvate dehydrogenase complex
GO:0160120 mitochondrial branched-chain alpha-keto acid dehydrogenase complex
GO:0017086 3-methyl-2-oxobutanoate dehydrogenase (lipoamide) complex

see https://github.com/geneontology/go-ontology/issues/26881

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1gDmxRwzszstV9TPbRXR5KiSm4SHe42foCgHqETAfHQo/edit#gid=0

Impacted groups: 
SGD 12
ComplexPortal 5
UniProt 5
EcoCyc 3
MGI 1
GeneDB 1

----

Mappings that need to be reviewed: 
GO:0009353	interpro2go	InterPro:IPR020373 Alpha-ketoglutarate dehydrogenase component 4/YMR-31 > GO:mitochondrial oxoglutarate dehydrogenase complex ; GO:0009353

Thanks.

**Comment by raymond91125** [comment]
There is an SGD annotation that uses GO:0005967 in annotation_extension_class. How should this be dealt with? @pgaudet

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by Antonialock** [comment]
uniprot done

**Comment by Antonialock** [comment]
CAFA and uniprot fixed

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
