### ISSUE TITLE
Review annotations to GO:0035553 'oxidative single-stranded RNA demethylation' and GO:0035552 'oxidative single-stranded DNA demethylation'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4970]
GO:0035553 'oxidative single-stranded RNA demethylation'
GO:0035552 'oxidative single-stranded DNA demethylation'

see https://github.com/geneontology/go-ontology/issues/26935

**Comment by pgaudet** [comment]
@RLovering Hello ! 

@colinlog and I have reviewed all annotations for these 2 terms. In fact they are redundant with MF, in all cases

https://docs.google.com/spreadsheets/d/1tNAH3cxIwN9uoOgSE-AiaY7eZsiqFDDkWC6JICMV3kc/edit#gid=0

So, these annotations can be safely removed. 

Thanks, Pascale

**Comment by RLovering** [comment]
ok I think I have deleted the 4 annotations as requested although one of the IDs had already been removed so I removed GO:0035513 oxidative RNA demethylation not GO:0035553
Hope that is OK
Ruth

**Comment by pgaudet** [comment]
GO:0035553 is also obsoleted - are the suggestions we made not working ?

**Comment by suzialeksander** [comment]
These terms were obsoleted, remaining annotations will be in the GORULES error reports
