### ISSUE TITLE
PTN001410513 not termination of RNA polymerase II transcription 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4974]
* **PTHR ID & PTN node:**

GO:0006369 | termination of RNA polymerase II transcription | IBA with S000003336 , PTN001410513

* **Sequences with problematic annotation (ID + gene/protein name):**

All

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Evidence not strong enough to propagate, single publication, quite old, checked with expertss

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation reviewed.
