### ISSUE TITLE
Review annotations to GO:0061778 intracellular chloride channel activity (with replacement)

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4976]
Dear all, 

The proposal has been made to obsolete GO:0061778 intracellular chloride channel activity,
see https://github.com/geneontology/go-ontology/issues/26874.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1U353V5oKvvIySGT2WBdYm4uK_ek11TQZptMygbisqyQ/edit#gid=0

Impacted groups: 
UniProt 2

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by Antonialock** [comment]
fixed

**Comment by RLovering** [comment]
Hi sorry to be late with this query, are the regulation terms going to be kept? UCL has 3 of these thanks Ruth

**Comment by pgaudet** [comment]
Hi @RLovering thanks for pointing that out. Regulation should also go - if we think the term should be obsoleted, its regulation should as well.

**Comment by RLovering** [comment]
Great, I probably should have checked the paper before asking ;) 3 UCL annotations deleted.
One other which is UniProt:
Qualifier	GO Term	Evidence	Reference	With / From	Taxon	Assigned By	Annotation Extension
UniProtKB:A1A5B4 	ANO9 	involved_in 	GO:1902939
negative regulation of intracellular calcium activated chloride channel activity
IDA
PMID:22946059 	
UniProt

Best
Ruth

**Comment by pgaudet** [comment]
Thanks, changed annotation.
