### ISSUE TITLE
Review annotations to 'recruitement' BPs 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4978]
GO:0034402 recruitment of 3\'-end processing factors to RNA polymerase II holoenzyme complex
GO:0046799 recruitment of helicase-primase complex to DNA lesions
GO:0036031 recruitment of mRNA capping enzyme to RNA polymerase II holoenzyme complex

Annotations are here: 
https://docs.google.com/spreadsheets/d/1Wzwkd-zOeNlj75lzvPt-Hb9JnWKV4J8uV9DD6VK0LM8/edit#gid=0

- [x] 8 SGD
- [x] DONE 1 UniProt

**Comment by srengel** [comment]
SGD done.
