### ISSUE TITLE
PTN000433761 not all necessarily 	 spliceosomal complex disassembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4979]
* **PTHR ID & PTN node:**

GO:0000390 | spliceosomal complex disassembly | IBA with PTN000433761 , S000000815 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC20H4.09

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation

pombe GIh35 is the ortholog of human  DHX35 https://www.uniprot.org/uniprotkb/Q9H5Z1/entry

and is partly characterised in fission yeast, as part of a 3 member complex
Gpl1-Gih35-Wdr83 complex  which is conserved from fission yeast to human, **but absent from budding yeast**
https://www.pombase.org/reference/PMID:36361590
so it seems strange to have inferences from budding yeast.

I think it's probably splicing surveillance, but there isn't too much detail at the moment.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation reviewed.
