### ISSUE TITLE
Review annotations to GO:0036451 cap mRNA methylation GO:0097309 cap1 mRNA methylation GO:0097310 cap2 mRNA methylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4980]
Dear all, 

The proposal has been made to obsolete 
GO:0036451 cap mRNA methylation
GO:0097309 cap1 mRNA methylation
GO:0097310 cap2 mRNA methylation
see https://github.com/geneontology/go-ontology/issues/26942

Experimental annotations that need to be reviewed are here: 

https://docs.google.com/spreadsheets/d/1D03tT6ga0ta-L47ATnY3F3X436xw1RRzaawEqi2E69o/edit#gid=0

Impacted groups: 
Uniprot 2
FlyBase 3

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

GO:0097309 | unirule2go | UniRule:UR001478754 > GO:cap1 mRNA methylation ; GO:0097309

Thanks.

**Comment by sjm41** [comment]
FB done.

**Comment by Antonialock** [comment]
Uniprot done

**Comment by ValWood** [comment]
I will proceed with obsoletion since there is a direct replacement
