### ISSUE TITLE
Review annotations to GO:0006378 mRNA polyadenylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4983]
Dear all, 

The proposal has been made to obsolete GO:0006378 mRNA polyadenylation
see https://github.com/geneontology/go-ontology/issues/26944

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1m8JQ7T47U3dBfQ56GBchqvytIaE-7QiOOa4MDm1VhiQ/edit#gid=0

Impacted groups: 
  ~2 ComplexPortal~
   1 EcoliWiki
   ~8 FlyBase~
  16 GeneDB
  ~1 WB~

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

GO:0006378 | interpro2go | InterPro:IPR016706 Cleavage/polyadenylation specificity factor subunit 5 > GO:mRNA polyadenylation ; GO:0006378
GO:0006378 | interpro2go | InterPro:IPR021605 Pcf11, Clp1-ID > GO:mRNA polyadenylation ; GO:0006378
GO:0006378 | interpro2go | InterPro:IPR027075 Cleavage and polyadenylation specificity factor subunit 2 > GO:mRNA polyadenylation ; GO:0006378
GO:0006378 | interpro2go | InterPro:IPR045154 Protein PCF11-like > GO:mRNA polyadenylation ; GO:0006378

GO:0006378 | unirule2go | UniRule:UR001229751 > GO:mRNA polyadenylation ; GO:0006378
GO:0006378 | unirule2go | UniRule:UR001629771 > GO:mRNA polyadenylation ; GO:0006378

Thanks.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by hattrill** [comment]
FB done

**Comment by vanaukenk** [comment]
WB has been done for a while, but the corrected annotation hasn't made it through the system yet.

**Comment by pgaudet** [comment]
@blazaropinto @sarach06 @tony787 Can you look at these ?

**Comment by ValWood** [comment]
@dsiegele there is one Ecowiki annotation, sorry I don't think I tagged you?
Val

**Comment by ValWood** [comment]
Thanks, it is possible they were removed on one of the earlier tickets!
