### ISSUE TITLE
Review annotations to GO:0036363 transforming growth factor beta activation & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4984]
Dear all, 

The proposal has been made to obsolete the following terms, and replace them either by 'x regulator activity' or maybe in this case, regulation of the TGF pathway.

GO:0036363 transforming growth factor beta activation
GO:1901389 negative regulation of transforming growth factor beta activation
GO:1901390 positive regulation of transforming growth factor beta activation
GO:1901388 regulation of transforming growth factor beta activation
GO:0036364 transforming growth factor beta1 activation
GO:0036365 transforming growth factor beta2 activation
GO:0036366 transforming growth factor beta3 activation 
GO:1901393 negative regulation of transforming growth factor beta1 activation
GO:1901394 positive regulation of transforming growth factor beta1 activation
GO:1901392 regulation of transforming growth factor beta1 activation 
GO:1901396 negative regulation of transforming growth factor beta2 activation
GO:1901397 positive regulation of transforming growth factor beta2 activation
GO:1901395 regulation of transforming growth factor beta2 activation 
GO:1901399 negative regulation of transforming growth factor beta3 activation
GO:1901400 positive regulation of transforming growth factor beta3 activation
GO:1901398 regulation of transforming growth factor beta3 activation 

Experimental annotations that need to be reviewed are here:   https://docs.google.com/spreadsheets/d/1PDVbe6562nW1iVbqUEVBBuJC0bSCJ7p-l8LzuL_aE3s/edit#gid=0

**Impacted groups:** 
1 ComplexPortal
4 AgBase
17 UniProt

@Antonialock Can you have a look to the UniProt and AgBase, and let me know if you need help with any of them? 

Thanks, Pascale

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by Antonialock** [comment]
@pgaudet I annotated e.g. Nrros/LRRC33 to receptor ligand inhibitor activity......but in uniprot it is described as "Transforming growth factor beta activator LRRC33" 
e.g. 29909984

I think it looks like it is required to position tgfb on the surface of the cell, and keep it in an inactive state, until an integrin comes along? (multicellular organism, not my area....so maybe I have this wrong). if inhibitor doesnt fit then perhaps a chaperoning role? Just seems strange to associate an "inhibitor" term with something that is named an activator....

**Comment by Antonialock** [comment]
I annotated "Lrrc32 and ltbp1 to establishment of protein localization to extracellular region"
it might be more like a chaperone than inhibitor? e.g. 28912269 &  2022183

**Comment by Antonialock** [comment]
and maybe I should request "establishment of protein localization to extracellular matrix?"

**Comment by Antonialock** [comment]
aside from the ones with questions and requests I've done the rest to the best of my ability..

**Comment by pgaudet** [comment]
Thanks @Antonialock !
