### ISSUE TITLE
Review annotations to GO:0045204 MAPK export from nucleus & related

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4985]
Dear all, 

The proposal has been made to obsolete
GO:0045204 MAPK export from nucleus
GO:0045208 MAPK phosphatase export from nucleus
GO:0045209 MAPK phosphatase export from nucleus, leptomycin B sensitive
GO:0071701 regulation of MAPK export from nucleus
see https://github.com/geneontology/go-ontology/issues/26971.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1ddUxc-QYJFyYWdzgr3mhgcnidcuLDafmVGEAjehPQjM/edit#gid=0

Impacted groups: 
UniProt 3
SGD 3

Thanks.

**Comment by pgaudet** [comment]
UniProt done.

**Comment by srengel** [comment]
SGD done,
