### ISSUE TITLE
InterPro:IPR005677 Fumarate hydratase, class II

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#4986]
* **InterPro ID / label**
InterPro:IPR005677 Fumarate hydratase, class II

* **Description of issue**
This entry is for fumarate hydratase, which is characterised to be a homotetramer. However, it has an InterPro2GO annotation to [tricarboxylic acid cycle enzyme complex (GO:0045239)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0045239), which is a grouping term for **heteromeric** TCA complexes. (Like many/most homo-oligomers, there is no GO complex term for fumarate hydratase, and I don't see any other InterPro entries for TCA cycle homo-oligomers (citrate synthase dimer, malate dehydrogenase dimer) with an association to GO:0045239.

So I think GO:0045239 should be removed from IPR005677.

Also see https://github.com/geneontology/go-ontology/issues/26882

**Comment by blazaropinto** [comment]
Hi Steven, 
Thank you so much for spotting that, the term is removed now and the changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by sjm41** [comment]
Thanks Beatriz!
