### ISSUE TITLE
Complex Portal decapping complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4987]
<img width="1395" alt="report- complex portal" src="https://github.com/geneontology/go-annotation/assets/7359272/8d3735fe-138d-4487-8c05-572a16b49f5e">

mRNA 5' phosphatase is actually 
-- | --
A 5'-end triphospho-[mRNA] + H2O = a 5'-end diphospho-[mRNA] + H+ + phosphate

and  decapping enzyme is 

GO:0140932 | 5'-(N(7)-methyl 5'-triphosphoguanosine)-[mRNA] diphosphatase activity

@pgaudet should we change the label for "mRNA 5' phosphatase activity", people do call it that, but its ambiguous

**Comment by sandraorchard** [comment]
removed and replaced.
