### ISSUE TITLE
Review annotations to ncRNA metabolic process and children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4988]
Dear all, 

The proposal has been made to obsolete 
GO:0034471 ncRNA 5'-end processing
GO:0034661 ncRNA catabolic process
GO:0110008 ncRNA deadenylation
GO:0097064 ncRNA export from nucleus
GO:0034660 ncRNA metabolic process
GO:0034470 ncRNA processing
GO:0098790 ncRNA transcription associated with protein coding gene TSS/TES
GO:0098781 ncRNA transcription
GO:0071029 nuclear ncRNA surveillance

see https://github.com/geneontology/go-ontology/issues/26761

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1vmYvdm0xxo7mI7CePQACj4SGAEMgsZfi7yVaE6Xb6TM/edit#gid=0

Impacted groups: 
  4 EcoCyc may need new terms
   3 PomBase
   2 TAIR
   2 UniProt
   3 WB
   4 SGD
   3 MGI
   2 BHF-UCL

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by RLovering** [comment]
Hi Val

let me know when terms available to update the UCL annotations

Thanks

Ruth

**Comment by vanaukenk** [comment]
WB done

**Comment by LiNiMGI** [comment]
MGI done

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error reports
