### ISSUE TITLE
UniProtKB:P0ADZ4 rpsO annotation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#4989]
Hi @amandamackie, 
I came across this annotation to a 
UniProtKB:P0ADZ4 rpsO mRNA base-pairing translational repressor activity 	PMID:2407855

This term should only be used to annotate RNA-species. 

This term was formally labelled "mRNA binding involved in post-transcriptional gene silencing", so probably a hangover from the change in the ontology.

**Comment by amandamackie** [comment]
Hi @hattrill,
I've removed the incorrect annotation and thanks for the feedback
Amanda
