### ISSUE TITLE
Review annotations to GO:0045239 tricarboxylic acid cycle enzyme complex

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4990]
Dear all, 

The proposal has been made to make do_not_annotate GO:0045239 tricarboxylic acid cycle enzyme complex
see https://github.com/geneontology/go-ontology/issues/26882.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/163P4kurlInpgnC7q_hbmYUTzzdOWzotCu9b7L-Zvdsc/edit#gid=0

Impacted groups: 
PseudoCAP 2

----

Mappings that need to be reviewed: 
InterPro:IPR005677 Fumarate hydratase, class II > GO:tricarboxylic acid cycle enzyme complex ; GO:0045239
Already announced https://github.com/geneontology/go-annotation/issues/4986.

Thanks.

**Comment by suzialeksander** [comment]
This term has been made `gocheck_do_not_annotate`. Any remaining annotations will be caught in the GORules reports
