### ISSUE TITLE
GO:0004577	 N-acetylglucosaminyldiphosphodolichol N-acetylglucosaminyltransferase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-annotation#4992]
* **PTHR ID & PTN node:**
PANTHER:PTN001741631

* **Sequences with problematic annotation (ID + gene/protein name):**
ALG14

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

It does not have the activity per se as it is not the catalytic subunit. This should be kept for ALG13 the catalytic subunit of the complex

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Was an old 'contributes_to' annotation. removed.
