### ISSUE TITLE
Review annotations to GO:0198738 cell-cell signaling by wnt

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4993]
Dear all, 

The proposal has been made to obsolete GO:0198738 cell-cell signaling by wnt 
see https://github.com/geneontology/go-ontology/issues/26960

3 annotations left by complex portal to PMID:27214281

Suggest to replace by  GO:0007166 cell surface receptor signaling pathway

Thanks, Pascale

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
