### ISSUE TITLE
Review annotations to GO:0007280 pole cell migration

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#4994]
Dear all, 

The proposal has been made to obsolete GO:0007280 pole cell migration (with replaced_by).
see https://github.com/geneontology/go-ontology/issues/25689.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1AHJs0-gdSSt7Y-BVPmKtQa5KN8kNIupo1Ib-5Z2PaDY/edit#gid=0

Impacted groups: 
FlyBase 16
UniProt 2

Thanks.

**Comment by pgaudet** [comment]
Will be automatically replaced. No action needed.
