### ISSUE TITLE
Incorrect UniProt KW mapping:  KW:KW-0239 for TENT4B

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4997]
<img width="966" alt="Screenshot 2024-02-15 at 10 06 47" src="https://github.com/geneontology/go-annotation/assets/7359272/2ef03160-e70d-4518-a796-898cdbbf4e0f">

* **UniProt KeyWord (ID and label):**

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

This is and RNA polymerase (and also  RNA binding not DNA binding (another false +ve KW)

**Comment by Antonialock** [comment]
thanks Val, I've looksed at this family of proteins and reviewed keywords along with some other tidying of sequences and residues involved in binding. It will take "a while" to filter through ( I don't have an estimate).
