### ISSUE TITLE
interconversion or synthesis?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#5]
Hello,

Lauren Brinkac, a TIGR microbial annotator, has raised
an annotation question that I would like to get some
clarification on.

There is a set of proteins involved in the conversion
of the various nucleotides between their mono-, di-,
and tri-phosphate forms.  (Ex. adenylate kinase,
thymidylate kinase).

At TIGR we annotate these to "nucleobase\, nucleoside
and nucleotide interconversion"  GO:0015949 and its
children.
However, when I look at other group's annotation, I
find that no one else (wth the exception of one FlyBase
gene which is not one of these kinases) is using these
terms.

I have seen other groups use the process term "ATP
biosynthesis" or "dTTP biosynthesis" (as appropriate
for the above proteins).  I can see the logic behind
this assignment but it seems like the interconversion
terms are more precise.
In my Stryer text these reactions are described as
interconversions between the forms, so even though the
terms in GO don't have definitions, it seems clear that
is what they were intended to be.

Should both the biosynthesis and interconversion terms
be assigned?  Is there a reason other groups are
avoiding the interconversion terms?

Thanks for your time,
Michelle

Reported by: mlgwinn

Original Ticket: "geneontology/annotation-issues/5":https://sourceforge.net/p/geneontology/annotation-issues/5

**Comment by linuxlovell** [comment]
thanks www.movied.org
