### ISSUE TITLE
Complex Portal sdh1 not  | GO:0042776    proton motive force-driven mitochondrial ATP synthesis 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5025]
UniProtKB:Q9UTJ7 | sdh1 | involved_in | GO:0042776    proton motive force-driven mitochondrial ATP synthesis | ECO:0005544   ISO | GO_REF:0000114 | ComplexPortal:CPX-565 | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | ComplexPortal

**Comment by sandraorchard** [comment]
Removed from entry - release due soon and will work its way through the system.
