### ISSUE TITLE
PTN000502669  not cytosolic for f.y.

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5056]
* **PTHR ID & PTN node:**

GO:0005829 | cytosol | IBA with PTN000502669 , P0A8N3 , Q15046 , P0A8N7 , P0A8N5

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC18.08
mitochondrial lysine-tRNA ligase Msk1

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation reviewed
