### ISSUE TITLE
Review annotations to GO:0005315 inorganic phosphate transmembrane transporter activity and GO:0015114 phosphate ion transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5071]
GO:0005315 inorganic phosphate transmembrane transporter activity
GO:0015114 phosphate ion transmembrane transporter activity

These two terms represent the same activity (phosphate ion == inorganic phosphate)

Obsoletion request is here: https://github.com/geneontology/go-ontology/issues/27121

**Comment by blazaropinto** [comment]
Hi Pascale,

Thank you very much for that. I updated these 2 terms. The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
