### ISSUE TITLE
Review annotations to GO:0044079  modulation by symbiont of host neurotransmitter secretion

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5074]
Hi @dsiegele 

CACAO has an annotation to 'GO:0044079  modulation by symbiont of host neurotransmitter secretion' based on [PMID:1328520](https://amigo.geneontology.org/amigo/reference/PMID:1328520); I think this is suppression, do you agree? (ie this would be better under [negative regulation by symbiont of host neurotransmitter secretion](https://amigo.geneontology.org/amigo/term/GO:0044762) - which is being relabeled as 'symbiont-mediated suppression of host neurotransmitter secretion', see https://github.com/geneontology/go-ontology/issues/27128

Thanks, Pascale

**Comment by suzialeksander** [comment]
@dsiegele can you check this, just one annotation in question. The terms have already been renamed

**Comment by pgaudet** [comment]
Term label was changed. @dsiegele please let us know if you'd like to revert this change.
