### ISSUE TITLE
 PTN000002587 not mediator

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5076]
Following on from 

https://github.com/geneontology/go-annotation/issues/5075

* **PTHR ID & PTN node:**

GO:0016592 | mediator complex | IBA with PTN000002587 , FBgn0004597 , MGI:1858199 , S000004970 , srb11

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1296.05c
This is cyclin L family, conserve to human but absent from S. cerevisiae.
Human counterparts are CCNL1 CCNL2 (so this applies also to these, they should be in the same clade independent of srb11)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

This is the model: This refers to Lcp1 and the previous ticket to Cdk11
<img width="993" alt="Screenshot 2024-02-22 at 15 22 24" src="https://github.com/geneontology/go-annotation/assets/7359272/5f067020-2ddd-4b83-832f-10463afb8175">

**Comment by marcfeuermann** [comment]
Annotation reviewed.
