### ISSUE TITLE
SNF2, N-terminal (IPR000330)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5078]
* **InterPro ID / label**
SNF2, N-terminal (IPR000330)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Dmel SuUR (FBgn0025355, Q9VTE2)

* **Description of issue**
This entry is associated with "ATP-dependent chromatin remodeler activity (GO:0140658)"

But IPR000330 has 5 child terms, only one of which is annotated "ATP-dependent chromatin remodeler activity (GO:0140658)", suggesting this function isn't a feature of all proteins with IPR000330?
E.g. Dmel SuUR hasn't been characterized to have this activity.

What do you think?

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much. I agree with you, the term doesn't apply to all of the proteins in this entry, so I removed from it. This will be available in the next InterPro release (99.0).
Best regards,
Sara

**Comment by sjm41** [comment]
Thanks Sara

**Comment by sarach06** [comment]
Hi Steven,
You're right, sorry about that! It's removed; will be visible in InterPro 102.0.

Best regards,
Sara
