### ISSUE TITLE
PTN008697341 (LEUCINE-RICH REPEAT-CONTAINING (PTHR45752))

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5080]
* **PTHR ID & PTN node:**
PTN008697341 (LEUCINE-RICH REPEAT-CONTAINING (PTHR45752))

* **Sequences with problematic annotation (ID + gene/protein name):**
Dmel Lrr47 (FBgn0010398/Q9VKU0)
Dmel CG3494 (FBgn0035008/Q0E8W8)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
erroneous propagation

This node adds "protein serine/threonine phosphatase activity" based on 3 source annotations:
(RAT|RGD=621308|UniProtKB=Q9WTR8)
(RAT|RGD=1562857|UniProtKB=D4A254)
(DROME|FlyBase=FBgn0032749|UniProtKB=Q9VJ07)

Source annotations look good, but the node then adds that phosphatase MF to Lrr47 and CG3494 - the encoded proeteins have LRR domains but no phosphatase domain.

So I think propagation of "protein serine/threonine phosphatase activity" should be blocked to Lrr47 and CG3494?

**Comment by marcfeuermann** [comment]
Annotation reviewed.
