### ISSUE TITLE
PROTEIN DISPATCHED-RELATED (PTHR45951) PTN002244707

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5081]
* ** PTHR ID:PTN002244707 PTN node:PTN002244707**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
IBA to MF: transmembrane transporter activity GO:0022857
Current thinking about the molecular function Dispatched proteins is that they do not transport proteins across a membrane, they seem to act more like carrier (PMID:32494603, PMID:30852081). Dispite recent structural info, the mechanism poorly defined.

Looks like this could be fixed by updating mouse Disp1 (Q3TDN0) PMID:12372301 from transmembrane transporter activity -> molecular carrier activity at MGI end @LiNiMGI

**Comment by LiNiMGI** [comment]
Thanks Helen, the review article is very helpful! @hattrill 
Mouse Disp1 (Q3TDN0) PMID:12372301 changed from transmembrane transporter activity -> molecular carrier activity in Noctua.

**Comment by hattrill** [comment]
Thanks @LiNiMGI
