### ISSUE TITLE
IPR047115 Arylsulfatase B

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5082]
* **InterPro ID / label**
IPR047115 Arylsulfatase B

* **Description of issue**
From the entry description, associated ECs, and matching proteins (at least in Dmel), I think it would be appropriate to add 'sulfuric ester hydrolase activity (GO:0008484)' (=EC:3.1.6.-) to this InterPro entry. What do you think?

**Comment by blazaropinto** [comment]
Hi Steven,
Thank you for this. I agree, so I added the term. The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by sjm41** [comment]
Great, thanks!
