### ISSUE TITLE
PTN002281442 for GO:0000460 | maturation of 5.8S rRNA

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5083]
* **PTHR ID & PTN node:**

GO:0000460 | maturation of 5.8S rRNA | IBA with PTN002281442 , P42285 , S000003586

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC17H9.02

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation. This is MTREC subunit (human equivalent PAXT complex).
There isn't a functional equivalent in S. cerevisiae.  MTR4 has an independent ortholog SGD:S000003586 in pombe and human which is part of TRAMP complex).

MTREC and TRAMP have quite a different range of substrates.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation reviewed
