### ISSUE TITLE
Review annotations to GO:1990120 messenger ribonucleoprotein complex assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5084]
Dear all, 

The proposal has been made to obsolete GO TERM ID: GO TERM
see GO:1990120 messenger ribonucleoprotein complex assembly

Experimental annotations that need to be reviewed are here: 
[https://docs.google.com/spreadsheets/d/1JASJKgE6MN46e52ncY4QRWz1s3Z3NLjTWdukH4q8bEo/edit#gid=0]

Impacted groups: 
SGD 1 annotation
~UniProt 4 annotations~

Thanks.

**Comment by Antonialock** [comment]
Uniprot done. 
Val just for future tickets -  it is very useful to see the motivation behind the obsoletion & I assume there's no proposed replacement in this case.

**Comment by ValWood** [comment]
Sorry its in the ontology ticket:
https://github.com/geneontology/go-ontology/issues/27077
-- links to  https://github.com/geneontology/go-ontology/issues/26431
which describes why the complex was obsoleted.

Basically  it isn't really describing a single complex but everything that occurs associated with any mRNA molecule (and essentially 100's of proteins'. It isn't really possible to describe this complexity as a single term in GO.

Its more of a "composite" concept for everything happening to the transcriptional and translations unit.
synonymous with
https://en.wikipedia.org/wiki/Messenger_RNP

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
