### ISSUE TITLE
Review annotations to GO:0031668 cellular response to extracellular stimulus

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5085]
Dear all, 

The proposal has been made to obsolete GO:0031668 cellular response to extracellular stimulus.
see https://github.com/geneontology/go-ontology/issues/27020

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1vHAnq7fPYVLYJCWXGdNF-7gcrWPBj-Vkx9NqrzFzVTs/edit?usp=sharing

Impacted groups: 
ARUK-UCL 1 - done
BHF-UCL 2 - done
MGI 15
RGD 4
UniProt 2

Thanks.

**Comment by slaulederkind** [comment]
RGD annotations finished.

**Comment by edwong57** [comment]
looks like it is all done. closing
