### ISSUE TITLE
Review annotations to GO:0110046 signal transduction involved in cell cycle switching, mitotic to meiotic cell cycle

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5086]
Dear all, 

The proposal has been made to obsolete GO:0110046 signal transduction involved in cell cycle switching, mitotic to meiotic cell cycle
see https://github.com/geneontology/go-ontology/issues/27022

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1StXhM_zSKlKINFIsuM5rRf6KKEn7qYe1osw487pnuR8/edit?usp=sharing

Impacted groups:
PomBase 13

Thanks.

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
