### ISSUE TITLE
Review annotations to GO:0000003 reproduction terms (with replacements)

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5090]
Dear all, 

The proposal has been made to obsolete
GO:0000003 reproduction
GO:0032504 multicellular organism reproduction
GO:0032505 reproduction of a single-celled organism

see https://github.com/geneontology/go-ontology/issues/27054.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1b5iLd_8l4yopf_Sb1hkhuQPvwGGiGTH0sOMVbCciuOM/edit#gid=0

Impacted groups: 
WB 128
TAIR 9
~UniProt 7~
MGI 3
ZFIN 3
TIGR 1
~Roslin_Institute 1~

----

Mappings that need to be reviewed: 
Wikipedia:Reproduction > GO:reproduction ; GO:0000003

Thanks.

**Comment by Antonialock** [comment]
Uniprot and roslin insttute done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by lreiser** [comment]
TAIR- accepted changes to reproductive process....

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error reports
