### ISSUE TITLE
PTN000387181 not all poly A tail shortening

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5093]
* **PTHR ID & PTN node:**

GO:0000289 | nuclear-transcribed mRNA poly(A) tail shortening | IBA with Q8NA58 , MGI:2685159 , MGI:1921358 , PTN000387181

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC29A10.09c ([O94386](https://www.uniprot.org/uniprot/O94386))

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation PNLDC1 does not seem to be ortholog.
In fission yeast this is involved in  siRNA 3' end processing, but does not appear to have a role in mRNA degradation (i.e appears to localize only to constitutive heterochromatin)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation reviewed
