### ISSUE TITLE
IPR011147 not all aspartate kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5094]
* **InterPro ID / label**

GO:0004072 | aspartate kinase activity | IEA with IPR011147

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC776.03

O94671

* **Description of issue**

Is  homoserine dehydrogenase (they are similar)

**Comment by sarach06** [comment]
Hi Val
Thank you very much for this, I have removed GO:0004072 from this entry. This will be visible in the next InterPro release (99.0).
Best regards,
Sara
