### ISSUE TITLE
Incorrect UniProt KW mapping: GO:0009082 | branched-chain amino acid biosynthetic process | IEA with KW-0100

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5095]
* **UniProt KeyWord (ID and label):**

GO:0009082 | branched-chain amino acid biosynthetic process | IEA with KW-0100

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC776.03

* **Description of issue**

Homoserine dehydrogenase (L-homoserine:NADP oxidoreductase); dimeric enzyme that catalyzes the third step in the common pathway for methionine and threonine biosynthesis

**Comment by Antonialock** [comment]
I agree it looks upstream

Homoserine dehydrogenase 
![image](https://github.com/geneontology/go-annotation/assets/12727506/4e40bd87-d49f-4b6b-bda6-4f6938d2e023)

i.e. it provides an input for isoleucine biosynthesis. 

The term isoleucine biosynthesis does not have a defined start which would seem useful to provide clarification on what should be annotated to this? from this paper it looks like it starts with condensation of pyruvate with 2-ketobutyrate (2KB in most, but not all, organisms is produced from threonine)

"in isoleucine biosynthesis, pyruvate is condensed with 2-ketobutyrate (2 KB). In most organisms, 2 KB is produced from threonine cleavage. Despite this, different biosynthetic routes, which mirror other metabolic pathways, are known to support the production of 2 KB in specific lineage"

https://elifesciences.org/articles/54207

**Comment by Antonialock** [comment]
I've given this family of proteins an overhaul.
