### ISSUE TITLE
Incorrect UniProt KW mapping: GO:0007186 | G protein-coupled receptor signaling pathway | IEA with KW-0297

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5097]
* **UniProt KeyWord (ID and label):**

GO:0007186 | G protein-coupled receptor signaling pathway | IEA with KW-0297

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC11H11.04 mam2

* **Description of issue**

@Antonialock  this isn't G-protein mediated is it?

**Comment by Antonialock** [comment]
yes I think it is believed gpa1 mediates signaling to byr2?

**Comment by ValWood** [comment]
of course it's map3 +gpa1 tks
