### ISSUE TITLE
Review annotations to synthesis of RNA primer involved in x & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5099]
Dear all, 

The proposal has been made to obsolete 

- GO:1902295 synthesis of RNA primer involved in cell cycle DNA replication
- GO:1902330 synthesis of RNA primer involved in bacterial-type DNA replication
- GO:1902318 synthesis of RNA primer involved in nuclear cell cycle DNA replication
- GO:1902981 synthesis of RNA primer involved in mitotic DNA replication
- GO:1902980 synthesis of RNA primer involved in premeiotic DNA replication

see [LINK TO GO-ONTOLOGY TICKET]

Experimental annotations that need to be reviewed are here: 
[LINK TO ANNOTATION REVIEW GOOGLE SPREADSHEET https://docs.google.com/spreadsheets/d/13oNsCNrIDGH26TAKCvpDW2QJXT_0vsR0g4qMKygR_b4]

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error reports
