### ISSUE TITLE
Review annotations to GO:0141005 retrotransposon silencing by heterochromatin formation & children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5100]
For the ncRNA refactor work, @hattrill will review annotations to these terms 

GO:0141005 retrotransposon silencing by heterochromatin formation
- GO:0141006 piRNA-mediated retrotransposon silencing by heterochromatin formation
- GO:0141095 retrotransposon silencing by DNA methylation-dependent heterochromatin formation
- GO:0141010 retrotransposon silencing by RNA-directed DNA methylation
- GO:0141007 siRNA-mediated retrotransposon silencing by heterochromatin formation

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1EbEzwQBRUNhicogWB245uu96pLc-wVK07SC7IpWt8rs/edit#gid=0

**Comment by hattrill** [comment]
@pgaudet have reviewed the annotations. A lot are ok, as were reviewed previously. 
There are quite a few mouse ones that are best described by 'retrotransposon silencing by piRNA-directed DNA methylation' and/or need siRNA-mediated retrotransposon silencing by heterochromatin formation to be removed.

**Comment by pgaudet** [comment]
@LiNiMGI See comment above: https://github.com/geneontology/go-annotation/issues/5100#issuecomment-1994938861

Can you please look into these? 

Thanks, Pascale

**Comment by LiNiMGI** [comment]
@pgaudet 
Seems to me there will be a new term 'retrotransposon silencing by piRNA-directed DNA methylation'. It is not available in Noctua yet, I will update annotations when new term become available in Noctua, thanks, Li

**Comment by pgaudet** [comment]
Hi @LiNiMGI 
FYI - It looks like the term is now available.

**Comment by hattrill** [comment]
@LiNiMGI talking with @pgaudet yesterday, we won't add retrotransposon silencing by piRNA-directed DNA methylation, as this looks too much like a compound term. 
Instead, these ones can be co-annotated with GO:0141176 gene silencing by piRNA-directed DNA methylation and GO:0010526 retrotransposon silencing.
Planning to make this the same for the other terms where we have a "retrotransposon silencing by" pattern - I will look at the sheet and update the ones affected.

**Comment by LiNiMGI** [comment]
Thanks @hattrill @pgaudet 
MGI done.
Li

**Comment by pgaudet** [comment]
@hattrill can this be closed?

**Comment by hattrill** [comment]
Yes, looks like it.
