### ISSUE TITLE
PAINT  PTN000360953 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5103]
* **PTHR ID & PTN node:**

GO:0030003 | intracellular monoatomic cation homeostasis | IBA with O95202 , MGI:1932557 , S000005387 , PTN000360953

* **Sequences with problematic annotation (ID + gene/protein name):**
https://www.pombase.org/gene/SPAC23C11.17 (mdm38, currently misnamed)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This is a ribosome receptor, and helps the mitochondrial encoded protein into the inner membrane.
GO:0030003 | intracellular monoatomic cation homeostasis 
seems like a phenotype?
. 
* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Weird, has been shown to be a potassium transporter in Human, Drosophila and S. cerevisiae. For the moment I removed the annotation.

**Comment by ValWood** [comment]
Hmm, I read the first SGD description  which focusses on the newer role:

Membrane-associated mitochondrial ribosome receptor; forms a complex with Mba1p to facilitate recruitment of mRNA-specific translational activators to ribosomes; ribosome-associated protein involved in the insertion of newly synthesized proteins into the mitochondrial inner membrane; role in protein export and K+/H+ exchange; localizes to the inner mitochondrial membrane; human ortholog Letm1 implicated in Wolf-Hirschhorn syndrome [1](https://www.yeastgenome.org/locus/S000005387#reference) [2](https://www.yeastgenome.org/locus/S000005387#reference) [3](https://www.yeastgenome.org/locus/S000005387#reference) [4](https://www.yeastgenome.org/locus/S000005387#reference) [5](https://www.yeastgenome.org/locus/S000005387#reference)

....as a ribosome receptor with a role in inserting into the IMM.  I assumed the abnormal transport in the older papers was an indirect phenotype but this isn't easily explained because I'm not aware of any mitochondrial encoded proteins that would affect potassium transport.

SGD also have a summary
Ribosome binding protein that positively regulates mitochondrial translation with Mba1p; involved in cellular potassium ion homeostasis by transporting potassium ions with Rbk1p and YDL183Cp; plays a role in biogenesis of both cytochrome bc(1) and cytochrome c oxidase complexes; localized to mitochondrial inner membrane

which mentioned the transport role again. It's difficult to reconcile these 2 different processes, so I will dig a little deeper and see how the more recent publications explain the transport phenotypes.
