### ISSUE TITLE
IPR022801  not ribosome subunit

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5105]
* **InterPro ID / label**

GO:0015935 | small ribosomal subunit | IEA with IPR022801 | GO_REF:0000002

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC19D5.05c

* **Description of issue**

Imp3 isn't part of the final ribosome, it's only part of assembly.

GO:0034457 | Mpp10 complex
would be a better mapping

**Comment by ValWood** [comment]
I see the family does also contain ribosome subunits, so you probably won't be able to create a mapping for this.

**Comment by ValWood** [comment]
GO:0003735 | structural constituent of ribosome
will also need to go....

**Comment by sarach06** [comment]
Hi Val,
Thank you very much for this. Yes, I agree, both terms have been removed from this entry. This will be visible in the next InterPro release (99.0).
Best wishes,
Sara
