### ISSUE TITLE
IPR011603 2-oxoglutarate dehydrogenase E1 component

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5107]
* **InterPro ID / label**
IPR011603 2-oxoglutarate dehydrogenase E1 component

* **Example sequences with problematic annotation (ID + gene/protein name):**
Dmel Q9VA02
human [Q96HY7](http://www.uniprot.org/uniprot/Q96HY7)

* **Description of issue**
Q9VA02/Q96HY7 has the IPR011603 signature and  is related to OGDH, which has [oxoglutarate dehydrogenase (succinyl-transferring) activity (GO:0004591)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004591) and is the E1 component of the OGDH complex acting in the [tricarboxylic acid cycle (GO:0006099)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006099).
But Q9VA02/Q96HY7 has been characterized to have a different activity and act in a different process - see UniProt report (https://www.uniprot.org/uniprotkb/Q96HY7/entry) and PMID:33045952.

So I think the '[oxoglutarate dehydrogenase (succinyl-transferring) activity (GO:0004591)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004591)' annotation needs changing to the parent term '
oxidoreductase activity, acting on the aldehyde or oxo group of donors, disulfide as acceptor | GO:0016624', while the [tricarboxylic acid cycle (GO:0006099)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006099) annotation should be removed (or changed to a high-level metabolic process term.)

**Comment by blazaropinto** [comment]
Hi Steven,

Thanks very much for that. I updated to GO:0016624 and removed GO:0006099. The changes will be available in the next InterPro release.

Best,
Beatriz
