### ISSUE TITLE
PTN000229249 (GUANYLYL CYCLASE (PTHR11920))

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5108]
* **PTHR ID & PTN node:**
PTN000229249 (GUANYLYL CYCLASE (PTHR11920))

This node is annotated with both [adenylate cyclase activity](http://amigo.geneontology.org/amigo/term/GO%3A0004016) and [guanylate cyclase activity](http://amigo.geneontology.org/amigo/term/GO%3A0004383).

I think it should just have guanylate cyclase activity - that would fit the fly proteins at least, and there's a more source annotations for that activity compared to the adenylate cyclase activity.  But it might not be as simple as that....

**Comment by marcfeuermann** [comment]
Indeed, adenylate cyclase acrtvity has been removed. Annotation comes from a possible horizontal gene transfer by MYCTU and an ancestral duplication in DICDI/DICPU.
