### ISSUE TITLE
IPR024371 acetyl-CoA transmembrane transport

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5109]
* **InterPro ID / label**
* IPR024371 Acetyl-coenzyme A transporter 1-like

* **Description of issue**
Already has acetyl-CoA transmembrane transporter activity (GO:0008521). Could you add GO:0035348 acetyl-CoA transmembrane transport

**Comment by blazaropinto** [comment]
Hi Helen,

Thanks for that. I added the term. The changes will be available in the next InterPro release.

Best,
Beatriz
