### ISSUE TITLE
GO:0044233 | mitochondria-associated endoplasmic reticulum membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5110]
* **PTHR ID & PTN node:**

GO:0044233 | mitochondria-associated endoplasmic reticulum membrane | IBA with MGI:1277186 , PTN000315667 | GO_REF:0000033 | 8

* **Sequences with problematic annotation (ID + gene/protein name):**
https://www.pombase.org/gene/SPBC4B4.10c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I wouldn't annotate atg5 to this term, maybe 

GO:0000407 | phagophore assembly site

Punctate structures proximal to the endoplasmic reticulum which are the sites where the Atg machinery assembles upon autophagy induction.

was intended?

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
In  fact the annotation is right since the phagophore asembly site is localized at the mitochondria-associated endoplasmic reticulum membrane. However, as we have already the annotation to phagophore assembly site, it is not necessary to have all annotations. may be this is more a hierarchy problem.

**Comment by ValWood** [comment]
OK, yesterday I relabelled  "mitochondria-associated endoplasmic reticulum membrane" to
"mitochondria-associated endoplasmic reticulum membrane contact site" based on the other terms.

So is " phagophore asembly site" and ""mitochondria-associated endoplasmic reticulum membrane contact site" equivalent?
