### ISSUE TITLE
Review annotations to GO:0043045 ! post-fertilization epigenetic regulation of gene expression

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5112]
For 
https://github.com/geneontology/go-ontology/issues/26951

**Comment by pgaudet** [comment]
@colinlog reviewed the genes annotated. All seem, except for 2 MGI annotations to 
MGI:MGI:2685210 and MGI:MGI:99204

@LiNiMGI Can you please review then annotations and see if we agree with the proposal in the spreadsheet 
https://docs.google.com/spreadsheets/d/1wKPs0cp8tz1cpilp1XFkFPmrR_rxw62fNKvofCyzAw4/edit#gid=0

**Comment by LiNiMGI** [comment]
MGI done.
