### ISSUE TITLE
GH actions don't work ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5113]
Hi @kltm 
See https://github.com/geneontology/go-annotation/issues/5112

The GH actions didn't seem to work? This is not the first time I notice. 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet You can see why actions failed here: https://github.com/geneontology/go-annotation/actions

**Comment by kltm** [comment]
But, more to the point, you seem to be forgetting to add the ontology terms you want to the body during creation? The title, IIRC, is irrelevant. https://github.com/geneontology/go-annotation?tab=readme-ov-file#overview

**Comment by pgaudet** [comment]
Ah ok thanks !!
