### ISSUE TITLE
Review annotations to GO:0048213 Golgi vesicle prefusion complex stabilization

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5115]
Dear all, 

The proposal has been made to obsolete GO:0048213 Golgi vesicle prefusion complex stabilization
see https://github.com/geneontology/go-ontology/issues/27100

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/1UKdu-quZ8UiwBujaBKpPsfkh8eG-hhtvrAwOVVww94s/edit?usp=sharing

Impacted groups: 
UniProt 1
----

Thanks.

**Comment by pgaudet** [comment]
Removed, was already annotated to retrograde vesicle-mediated transport, Golgi to endoplasmic reticulum
