### ISSUE TITLE
Review annotations to GO:0043621 protein self-association and  GO:0032840 intramolecular proline-rich ligand binding

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5116]
Dear all, 

The proposal has been made to obsolete GO:0043621 protein self-association and  GO:0032840 intramolecular proline-rich ligand binding
see https://github.com/geneontology/go-ontology/issues/27101

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/14eHLs7s81y_pUziDB58dtUfv244dNd2lZodeJAJ0OZs/edit?usp=sharing

Impacted groups: 

AgBase  14
BHF-UCL  7 - UCL done
~CAFA  9~ done
FlyBase  3
MGI  22
RGD 11
TAIR  55
~UniProt  153~ done
~WB  14~ done
ZFIN  1
dictyBase  3

Thanks.

**Comment by hattrill** [comment]
FB done

**Comment by gthayman** [comment]
RGD done

**Comment by pgaudet** [comment]
I'm interested to know what different groups are doing; I was assuming these were being moved to 'protein binding'.

**Comment by hattrill** [comment]
@tberardini @pgaudet 
I've deleted them. We've made a decision that we should stop capturing terms that describe self-association and terms like this that describe homomultimerization/stoichiometry - we already have a curator working on capturing pair-wise physical interactions (and complex portal and IntAct are also doing similar). Plus, in the MF domain, it doesn't say much about what the protein does.

**Comment by Antonialock** [comment]
protein self-association sounds like a very strange term
"Binding to a domain within the same polypeptide"
...isn't that just forming the protein tertiary structure?

**Comment by Antonialock** [comment]
uniprot and cafa done. It seemed to be a grab bag of intra and inter self-association, some redundant with intact. It didn't seem like we'd lose much from letting go of them.

**Comment by sramachand** [comment]
ZFIN done

**Comment by lreiser** [comment]
@tberardini  if we don't do anything when the term is obsoleted the annotations would be obsoleted Since there is nothing to replace this with I am inclined to not do anything and let the terms and annotations expire.

**Comment by tberardini** [comment]
@lreiser I'm ok with having the annotations expire. RIP annotations.

**Comment by LiNiMGI** [comment]
MGI done

**Comment by vanaukenk** [comment]
WB done

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error reports
