### ISSUE TITLE
 PTN001053248 GO:0005788 | endoplasmic reticulum lumen

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5119]
* **PTHR ID & PTN node:**

GO:0005788 | endoplasmic reticulum lumen | IBA with PTN001053248 , Q67UF5 , 628688 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC959.05c
https://www.yeastgenome.org/locus/S000001267

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Although involved in the retention of luminal proteins it is an ER membrane protein

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed.
