### ISSUE TITLE
Replace GO term glycogen biosynthetic process with glycogen metabolic process for IPR002291

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-annotation#5120]
* *IPR002291*

* **Example sequences with problematic annotation (ID + gene/protein name): Drosophila PhKy (CG1830) phosphorylase kinase gamma**

* **Description of issue**
Would it be possible to replace the current GO term "glycogen biosynthetic process (GO:0005978)" with the parent term "glycogen metabolic process (GO:0005977)"?

This would make the GO annotation between the catalytic subunit (IPR002291) and the regulatory subunit (IPR008734) consistent.

It would also represent better the role of the catalytic subunit as based on the literature the annotation would be:
positive regulation of glycogen catabolic process (based on the phosphorylation-mediated activation of glycogen phosphorylase)
negative regulation of glycogen biosynthetic process (based on the phosphorylation-mediated inhibition of glycogen synthase, although it's not clear if this is physiologically relevant).
Both would be covered by the glycogen metabolic process GO term.

Thank you

Rossana

**Comment by blazaropinto** [comment]
Hello,

Thank you very much for this. I've updated this term. The changes will be available in InterPro 100.0.

Best,

Beatriz

**Comment by rozaru** [comment]
Thank you Beatriz for updating the term.
Rossana
