### ISSUE TITLE
Review annotations to terms using leucine

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5122]
This is to check annotations to confirm that we can rename terms to L-leucine xx. 

GO:0071233 | cellular response to leucine
GO:0070728 | leucine binding
GO:0009098 | leucine biosynthetic process
GO:0006552 | leucine catabolic process
GO:0098713 | leucine import across plasma membrane
GO:0006551 | leucine metabolic process
GO:0015820 | leucine transport
GO:0043201 | response to leucine

**Comment by suzialeksander** [comment]
GO:0098713 obsolete leucine import across plasma membrane is the only term that's been obsoleted, but I don't see an ontology ticket for that.  No other ontology tickets.

**Comment by pgaudet** [comment]
D- and L- amino acid issue - will do later.
