### ISSUE TITLE
Review annotations to GO:0140035 ubiquitination-like modification-dependent protein binding & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5126]
GO:0140035 ubiquitination-like modification-dependent protein binding
GO:0140037 sumo-dependent protein binding
GO:0140036 ubiquitin-dependent protein binding 

Annotations are here: https://docs.google.com/spreadsheets/d/18dk19bOMaRqBYBmsAde6_mWQCPxA4Y39RVgwbHlO57Q/edit#gid=0

**Comment by pgaudet** [comment]
We'd like to rename these terms 'reader activity', see 
https://github.com/geneontology/go-ontology/issues/27325

@sylvainpoux to review UniProt and I will look at the others.

**Comment by sylvainpoux** [comment]
Hi Pascale,
I will check if the uniProt annotations are correct
Thanks
Sylvain

**Comment by sylvainpoux** [comment]
Done, most of them were correct (but I also have to admit that most annotations were from me, meaning that I was least consistent in the way of curating these papers)
S,

**Comment by pgaudet** [comment]
Great, thanks ! I'll have a look at the others.

**Comment by RLovering** [comment]
UCL checked - 1 annotation would ideally be ubiquitin reader activity

**Comment by pgaudet** [comment]
Thanks @RLovering ! 

@hattrill There is a single FlyBase annotation, to the Rho GTPase-activating protein Graf; do you think it's OK calling this a ubiquititin reader?

**Comment by hattrill** [comment]
@pgaudet this seems ok to me, from the definition.

I couldn't work it out from the ticket, but will this be classed as a  molecular adaptor activity?

**Comment by pgaudet** [comment]
Yes, so far readers are adaptors. Is this consistent with this annotation?

**Comment by hattrill** [comment]
Yes, that's fine

**Comment by suzialeksander** [comment]
Change has been made in the ontology
