### ISSUE TITLE
Review annotations to GO:000991 - response to extracellular stimulus

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5130]
Dear all, 

The proposal has been made to obsolete GO:0009991 - response to extracellular stimulus
see https://github.com/geneontology/go-ontology/issues/27020

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/16V38dwLL3ofgw_MWuxUCHyGYZ24Ji_pySil4UtAMA3I/edit?usp=sharing

Impacted groups: 
RGD 1
TAIR 1
MGI 1
UniProt 2 - done
dictyBase 1 - DONE

----

Thanks.

**Comment by pfey03** [comment]
Dicty done, Petra

**Comment by tberardini** [comment]
TAIR done

**Comment by RLovering** [comment]
UCL done and 2 UCL annotations  to GO:0140039 cell-cell adhesion in response to extracellular stimulus - 1 deleted one changed

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by suzialeksander** [comment]
This term was obsoleted; remaining annotations will appear in GORULES error reports
