### ISSUE TITLE
Review annotations to GO:0006069 ethanol oxidation

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5131]
Dear all, 

The proposal has been made to obsolete GO:0006069 ethanol oxidation
see https://github.com/geneontology/go-ontology/issues/27260

Experimental annotations that need to be reviewed are here:
https://docs.google.com/spreadsheets/d/1DY1OvsVTk0DMg5p7P2SQDLV50IM4u3G6OMJ1jACeKBA/edit?usp=sharing

Impacted groups:
UniProt 6
RGD 3
FlyBase 1

----

Thanks.

**Comment by slaulederkind** [comment]
RGD finished.

**Comment by hattrill** [comment]
FB done
