### ISSUE TITLE
Review annotations to  GO:0035584 calcium-mediated signaling using intracellular calcium source and  GO:0035585 calcium-mediated signaling using extracellular calcium source

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5132]
GO:0035584 calcium-mediated signaling using intracellular calcium source
 GO:0035585 calcium-mediated signaling using extracellular calcium source

See obsoletion ticket: https://github.com/geneontology/go-ontology/issues/27412
for details

Group | Number of annotations 
-- | --
MGI | 1
ZFIN | 1
PomBase | 2 DONE
ARUK-UCL | 14 DONE
UniProt | 16 DONE

Annotations are here: https://docs.google.com/spreadsheets/d/1al0kZJQRQNyEGFm-rQOHSTk0dB_We_qRM1rKilRRVZY/edit#gid=0

**Comment by Antonialock** [comment]
uniprot done

**Comment by LiNiMGI** [comment]
MGI done.
