### ISSUE TITLE
Review annotations to GO:0055056 D-glucose transmembrane transporter activity and GO:0005355 glucose transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5143]
Dear all, 

These two terms seem equivalent: 

GO:0055056 D-glucose transmembrane transporter activity will be obsoleted and replaced by GO:0005355 glucose transmembrane transporter activity

see https://github.com/geneontology/go-ontology/issues/27326

Experimental annotations that need to be reviewed are here: 
[LINK TO ANNOTATION REVIEW GOOGLE SPREADSHEET https://docs.google.com/spreadsheets/d/13oNsCNrIDGH26TAKCvpDW2QJXT_0vsR0g4qMKygR_b4]

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by suzialeksander** [comment]
incomplete request @pgaudet

**Comment by jlewsmith** [comment]
Hi Pascale,

Can you update the link to the spreadsheet on #5143<https://github.com/geneontology/go-annotation/issues/5143>  - it's not functional yet.

Thanks,
Jodi
________________________________

**Comment by pgaudet** [comment]
@jlewsmith Is this not working ? 
https://docs.google.com/spreadsheets/d/1Tc-2bSKBmnqvmEAD1PPVYSRLYP3EP_DI0-TL2noilfs/edit?gid=0#gid=0

**Comment by jlewsmith** [comment]
Hi Pascale,

That link works fine - thanks.

Jodi
________________________________

**Comment by jlewsmith** [comment]
CGD done (although it appears they were automatically fixed as I didn't find the obsoleted term, only the new term)
________________________________

**Comment by pgaudet** [comment]
Terms have been obsoleted. Remaining annotations will appear in GORULES reports.
