### ISSUE TITLE
Review annotations to GO:0000971 tRNA exon ligation utilizing 2',3' cyclic phosphate of 5'-exon as source of linkage phosphate

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5151]
Dear all, 

The proposal has been made to obsolete GO:0000971 tRNA exon ligation utilizing 2',3' cyclic phosphate of 5'-exon as source of linkage phosphate

see https://github.com/geneontology/go-ontology/issues/27438

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1_YNIRlWzy_ujW5sZg5HbygC66vacKQcAijcXBGd4U1s/edit?usp=sharing

Impacted groups: 
WB 1

Thanks.

**Comment by vanaukenk** [comment]
I've fixed the WB annotation in Protein2GO
