### ISSUE TITLE
IPR027513 RNA-splicing ligase RtcB homologue, eukaryotic

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5152]
* **InterPro ID / label**
IPR027513 RNA-splicing ligase RtcB homologue, eukaryotic

* **Example sequences with problematic annotation (ID + gene/protein name):**
Dmel RtcB/FBgn0032781/Q9VIW7 (and orthologs)

* **Description of issue**
IPR027513 has associated EC of EC:6.5.1.8 but is annotated with 'RNA ligase (ATP) activity (GO:0003972)' (=EC:6.5.1.3)'
Consistent with that, Q9VIW7 is annotated to EC:6.5.1.8 in UP.

So I think IPR027513 should be annotated with the new term 'RNA ligase (GTP) activity' (GO:0170057) requested in https://github.com/geneontology/go-ontology/issues/27418 (when it's available).

**Comment by blazaropinto** [comment]
Hi Steve,

Thank you so much for that. I updated the term. The changes will be available in the next InterPro release.

Best,

Beatriz
