### ISSUE TITLE
Final tasks for migration to GPAD/GPI 2.0 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5153]
Hi everyone, 

These are the tasks needed to finalize the switch to emitting GPAD/GAF2.0. 
(I tentatively assigned people but not 100% about the assignments):  

- [x] @LiNiMGI  to add an example GPAD with all types of examples (with extensions, with isoforms, etc) here: 
https://drive.google.com/drive/folders/1apwGcSv_VBcat816YM5gRDUB-FkmCebE
- [x] @sierra-moxon to produce a corresponding GPI file  – this can be the ‘normal’ MGI GPI2.0, (minus any errors?), save in the same folder https://drive.google.com/drive/folders/1apwGcSv_VBcat816YM5gRDUB-FkmCebE
- [x]  @sierra-moxon to check that our parsers don’t get errors for these files before publicizing
- [ ] @kltm to generate links to these files
- [x] @suzialeksander to fix the GO website to refer to the GPAD/GPI2.0 documentation as the main file format, and more previous documentation 
- [ ] @suzialeksander to announce to go-consortium and GH go-annoucement repo (+ Alliance forum? other places) under deprecated formats (https://geneontology.org/docs/deprecated-products-and-formats/) 

I think we can aim for the May 2024 GO release, if this announcement can be sent in the ext week. 

Thanks, Pascale

**Comment by sierra-moxon** [comment]
Hi @pgaudet - w/re to GPI, as I understand it (which may be wrong) the regular GO pipeline produces the GPI for us by default (and it is being produced in my pipeline now: http://skyhook.berkeleybop.org/full-issue-325-gopreprocess/annotations/mgi.gpi.gz).  Is this correct?

**Comment by pgaudet** [comment]
This issue is GPI2.0 merges columns 1 and 2, compared with GPI1.2, see
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md

so, as far I can tell, it seems this is a different format, we cannot use the GPI that used to be produced. 

Right? 

Thanks, Pascale

**Comment by sierra-moxon** [comment]
I believe the tasks here are complete w/re to development
