### ISSUE TITLE
Review annotations to unnecessary grouping terms 

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5154]
Dear all, 

The proposal has been made to obsolete
'organic substance biosynthetic process' GO:1901576
'organic substance catabolic process' GO:1901575
'organic substance metabolic process' GO:0071704
'organic substance transport' GO:0071702
'response to organic substance' GO:0010033
'detection of organic substance' GO0071703
'response to inorganic substance' GO0010035
'cellular response to organic substance' GO:0071310
'cellular response to inorganic substance' GO:0071241
organic cyclic compound catabolic process GO:1901362 
organic cyclic compound biosynthetic process GO:1901362 
organic cyclic compound metabolic process GO:1901360 

see https://github.com/geneontology/go-ontology/issues/27386

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1HzTyTZM3vq1182I2yAphuRbZpboEI58oouhHwZaBZ5Y/edit#gid=0

Impacted groups: 

- [x] CGD 1
- [x] Complex Portal 1
- [x] EcoCyc 2
- [x] FlyBase 9
- [ ] MGI 157
- [x] MTBBASE 8
- [ ] PseudoCAP 1
- [x] RGD 157
- [x] TAIR 2
- [x] UniProt 20

----

Mappings that need to be reviewed:
InterPro:IPR007543 LptD, C-terminal > GO:response to organic substance ; GO:0010033
InterPro:IPR020889 LPS-assembly protein LptD > GO:response to organic substance ; GO:0010033
Rfam:RF00760 mir-342 > GO:cellular response to inorganic substance ; GO:0071241
Rfam:RF04052 mir-466 > GO:cellular response to inorganic substance ; GO:0071241
UniProtKB-KW:KW-0762 Sugar transport > GO:organic substance transport ; GO:0071702
InterPro:IPR001547 Glycoside hydrolase, family 5 > GO:organic substance metabolic process ; GO:0071704
InterPro:IPR005843 Alpha-D-phosphohexomutase, C-terminal > GO:organic substance metabolic process ; GO:0071704
InterPro:IPR036900 Alpha-D-phosphohexomutase, C-terminal domain superfamily > GO:organic substance metabolic process ; GO:0071704

Thanks.

**Comment by hattrill** [comment]
FB done

**Comment by tberardini** [comment]
TAIR done

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by Antonialock** [comment]
uniprot done

**Comment by slaulederkind** [comment]
RGD finished.

**Comment by blazaropinto** [comment]
Hi Pascale,

Thanks for that. I removed the mentioned terms and added GO:0000272 to IPR001547. The changes will be available in InterPro 100.0.

Best,
Beatriz

**Comment by pgaudet** [comment]
MGI @LiNiMGI 
ComplexProtal @sandraorchard 
PseudoCap @glwinsor 

Still need to review their annotations.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by raymond91125** [comment]
@pgaudet Should I wait more or go ahead with obsoleting these terms? Thanks.

**Comment by pgaudet** [comment]
@LiNiMGI Do you want to have a look at the MGI annotations before we go ahead with the obsoletion?

**Comment by LiNiMGI** [comment]
Thanks@pgaudet, I plan to start the review next week (was waiting and trying to get some help), it might take me a while to finish this one; obsolete now will make the review  process even hard since I have to switch to graph editor to make all the changes...

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error reports

**Comment by krchristie** [comment]
Presumably inclusion of the three annotations to "intracellular calcium ion homeostasis" in the annotations to review spreadsheet was an error since this GO term in not included in the list of terms to be obsoleted. I do not plan to delete these annotations.

![20241126-nonOrganicInorganicTerms](https://github.com/user-attachments/assets/0d132b79-b585-4932-b4fe-5c6cd296883b)

**Comment by pgaudet** [comment]
Hi @krchristie 

In fact these annotations have extensions with the terms mentioned above. 
It looks like some other extensions were missing; I've added them, with 'EXTENSION' in the first column so it's more obvious. 

Thanks, Pascale
