### ISSUE TITLE
Review annotations to GO:0047263 N-acylsphingosine galactosyltransferase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5155]
Dear all, 

The proposal has been made to obsolete GO:0047263 N-acylsphingosine galactosyltransferase activity;
see https://github.com/geneontology/go-ontology/issues/27410.

This term is to be replaced by GO:0003851 2-hydroxyacylsphingosine 1-beta-galactosyltransferase activity.
EC:2.4.1.47, MetaCyc:2.4.1.47-RXN, and RHEA:13093 will also be transferred to GO:000385.

There are 0 Experimental annotations that need to be reviewed.

----

Mappings that need to be reviewed:
GO:0047263	ec2go	EC:2.4.1.47 > GO:N-acylsphingosine galactosyltransferase activity ; GO:0047263
GO:0047263	metacyc2go	MetaCyc:2.4.1.47-RXN > GO:N-acylsphingosine galactosyltransferase activity ; GO:0047263
GO:0047263	rhea2go	RHEA:13093 > GO:N-acylsphingosine galactosyltransferase activity ; GO:0047263
GO:0047263	reactome2go	Reactome:R-HSA-6785933 > GO:N-acylsphingosine galactosyltransferase activity ; GO:0047263

Thanks.

**Comment by deustp01** [comment]
Reactome fixed. Change will appear in June 2024 release.
