### ISSUE TITLE
Reannotate nodulin 26-like intrinsic proteins (NIPs) 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5156]
When this term 'borate channel activity' is available:
https://github.com/geneontology/go-ontology/issues/27487

The TAIR annotations to GO:0046715	active borate transmembrane transporter activity for
UniProtKB:Q8LAI1 ; NIP7-1 PMID:21710975
UniProtKB:Q9SAI4 ; NIP6-1 PMID:18952773
UniProtKB: Q9SV84 ; NIP5-1 PMID:16679457
should be replaced with 'borate channel activity'

See https://tcdb.org/search/result.php?tc=1.A.8.12#1.A.8.12 for classification and Structural and functional insights into the mechanism of action of plant borate transporters PMID:34112901

Assigning this to @lreiser (feel free to change)

**Comment by lreiser** [comment]
done
