### ISSUE TITLE
Review annotations to GO:0004121 cystathionine beta-lyase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5157]
Dear all, 

The proposal has been made to obsolete (with replaced_by)
GO:0004121 cystathionine beta-lyase activity
GO:0050271 S-alkylcysteine lyase activity
see https://github.com/geneontology/go-ontology/issues/27410

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1u6gFHAxy44ZvNJNibIWX3KVrPO77skSALJT9BUGFyAo/edit#gid=0

Impacted groups: 
AspGD 3
EcoCyc 2
SGD 2
TAIR 3

----

Mappings that need to be reviewed:
interpro2go	InterPro:IPR006233 Cystathionine beta-lyase, bacterial > GO:cystathionine beta-lyase activity ; GO:0004121
interpro2go	InterPro:IPR006238 Cystathionine beta-lyase, eukaryotic > GO:cystathionine beta-lyase activity ; GO:0004121

Thanks.

**Comment by Antonialock** [comment]
the AspGD ones were updated automatically so I will remove my assignment

**Comment by pgaudet** [comment]
SGD and TAIR will also be updated automatically.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have replaced GO:0004121 with GO:0047804 in the two entries you mentioned. This will be visible in the next InterPro release (100.0).
Best wishes,
Sara

**Comment by suzialeksander** [comment]
These terms were obsoleted; remaining annotations will appear in GORULES error reports
