### ISSUE TITLE
Rhea mappings for  pombe ura1/ SGD URA2

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5159]
Rhea is mapping pombe 
ura1 https://www.pombase.org/gene/SPAC22G7.06c to 
https://www.rhea-db.org/rhea/15889 GO:0004359	glutaminase activity IEA with 15889	GO_REF:0000116
and 
https://www.rhea-db.org/rhea/18029 GO:0004087	carbamoyl-phosphate synthase (ammonia) activity IEA with 18029	GO_REF:0000116

but it seems to be
GLNase (glutamine amidotransferase), GO:0003922
CPSase (carbamoylphosphate synthetase)  GO:0004088
ATCase (aspartate transcarbamoylase)  GO:0004070

also applies to S.  cerevisiae ortholog URA2
https://www.yeastgenome.org/locus/S000003666

papers
https://www.yeastgenome.org/reference/S000050154
https://www.pombase.org/reference/PMID:8590465

**Comment by ValWood** [comment]
@kaxelsen

**Comment by kaxelsen** [comment]
I'm not sure what the problem is. If it is that we have added a 'glutaminase' reaction (RHEA:15889) instead of a 'glutamine amidotransferase' reaction, then I'm sorry that I will not be able to help you because the error is in the name.

The so-called 'glutamine amidotransferase' domains are part of two-domain or two-subunit systems where the 'glutamine amidotransferase' domain/subunit hydrolyses glutamine to produce ammonia (NH3) that is then channeled to the second domain/subunit to be used as a substrate in a second reaction. So, in short, there is no amido group transferred. There is an ammonia molecule produced and channeled between two active sites. This means the name 'glutasmine amidotransferase' is completely wrong, and I would be very happy if it were possible to stop the usage of the term for these proteins/domains.

**Comment by ValWood** [comment]
so we should obsolete "GLNase (glutamine amidotransferase), GO:0003922"?

It is also weird that in GO
GMP synthase activity
Catalysis of the reaction: ATP + XMP + NH4(+) = AMP + diphosphate + GMP + 2H+.

is a descendant  of
GO:0003922   GMP synthase (glutamine-hydrolyzing) activity
Catalysis of the reaction: ATP + XMP + L-glutamine + H2O = AMP + diphosphate + GMP + L-glutamate + 2H+.
?

**Comment by kaxelsen** [comment]
> so we should obsolete "GLNase (glutamine amidotransferase), GO:0003922"?

I don't think you can. GLNase or GATase is very widely used, so you would probably receive questions about where the term had gone if you tried.

GMP synthase (glutamine-hydrolyzing) is EC 6.3.5.2. 
If you look at the RHEA reaction linked to this EC you will find:
RHEA:11680 ATP + H2O + L-glutamine + XMP = AMP + diphosphate + GMP + 2 H+ + L-glutamate 
This is a Multi-step reaction consisting of RHEA:15889 and RHEA:18301
RHEA:15889 H2O + L-glutamine = L-glutamate + NH4+
RHEA:18301 ATP + NH4+ + XMP = AMP + diphosphate + GMP + 2 H+

In Rhea RHEA18301 is part-of RHEA:11680

**Comment by ValWood** [comment]
Right, got it. I understand the glutaminase annotation.

I still don't understand the
https://www.rhea-db.org/rhea/18029 GO:0004087 carbamoyl-phosphate synthase (ammonia) activity IEA with 18029
is that also correct for  a trifunctional
GLNase / CPSase /ATCase  ?

**Comment by deustp01** [comment]
I'm missing something here - isn't this the homolog of a multidomain protein each of whose domains enables a different step in a multistep process, so the whole protein should pick up as many different GO MF catalysis terms and RHEA reactions as it has distinct catalytic domains? Or have I missed the point of the query?

**Comment by ValWood** [comment]
So, I thought the protein  (pombe ura1) https://www.pombase.org/gene/SPAC22G7.06c
was tri-functional,  according to
https://www.pombase.org/reference/PMID:8590465

and I have 6 independent MF terms which are not parent/child, they are in different parts of the graph

<img width="637" alt="Screenshot 2024-04-04 at 20 12 17" src="https://github.com/geneontology/go-annotation/assets/7359272/274963a4-2faf-4d31-863c-47b3b3cfb166">

so I was trying to narrow down to the 3 activities, until @kaxelsen  pointed ot my error of my ways.

So I am trying to figure out if all 6  **unique activities** are correct, and if so, how they relate to each other so that we can link up the pathway. If anyone has done this already please point me that way...

**Comment by deustp01** [comment]
Aha! Got it. No, sorry, no clue.

**Comment by kaxelsen** [comment]
> I still don't understand the
> https://www.rhea-db.org/rhea/18029 GO:0004087 carbamoyl-phosphate synthase (ammonia) activity IEA with 18029
> is that also correct for a trifunctional
> GLNase / CPSase /ATCase ?

Yes,  it is. The GLNase / CPSase are coupled like for EC 6.3.5.2 and forms EC 6.3.5.5. The ATCase activity is just an extra domain that has been 'added' that catalyses an additional reaction using the product carbamoyl phosphate from EC 6.3.5.5 as substrate in RHEA:20013 (EC 2.1.3.2)

**Comment by ValWood** [comment]
Thanks, @kaxelsen  I will close this. I have enough information to proceed to find out what GO best practice would be in this situation.
