### ISSUE TITLE
 PANTHER:PTN000384994 not preribosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5161]
* **PTHR ID & PTN node:**

UniProtKB:O42936	las1	part_of	[GO:0030687](https://www.ebi.ac.uk/QuickGO/term/GO:0030687)    preribosome, large subunit precursor	[ECO:0000318](https://www.ebi.ac.uk/QuickGO/term/ECO:0000318)   IBA	GO_REF:0000033	
PANTHER:PTN000384994 more...
284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843)	GO_Central

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC16C6.12c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

annotation,
Las1 is part of the rixosome complex and the las1 complex
It associates with the pre-ribosome but isn't part of it

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation removed.
