### ISSUE TITLE
Review annotations to GO:0009991 response to extracellular stimulus & children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5162]
GO:0009991 response to extracellular stimulus
GO:0031668 cellular response to extracellular stimulus
GO:0032104 regulation of response to extracellular stimulus
GO:0032105 negative regulation of response to extracellular stimulus
GO:0032106 positive regulation of response to extracellular stimulus

**Comment by suzialeksander** [comment]
All terms have been obsoleted.
