### ISSUE TITLE
Review annotations to GO:0030792 methylarsonite methyltransferase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5165]
Dear all, 

The proposal has been made to obsolete GO:0030792 methylarsonite methyltransferase activity (with replacement)
see https://github.com/geneontology/go-ontology/issues/27410.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1pPYyt8V620yPAv6lsfwq9nd-Z0LqSHf3UaMj_Ks7X9E/edit#gid=0

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by suzialeksander** [comment]
This term has been obsoleted.
