### ISSUE TITLE
REFG     protein          Q9UBM7                           GO:0016132       ECO:0000318 (IBA)        GO_REF:0000033  

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-annotation#5168]
Hi Lionel, 

It looks like the AC of the protein disputed is missing? 

It would be more convenient if you could dispute these in the go-annotation tracker. 

https://github.com/geneontology/go-annotation/issues/new?assignees=marcfeuermann%2C+pgaudet&labels=PAINT+annotation&projects=&template=paint-issue.md&title=

Pascale

From: [Lionel.Breuza@sib.swiss](mailto:Lionel.Breuza@sib.swiss) <[Lionel.Breuza@sib.swiss](mailto:Lionel.Breuza@sib.swiss)>
Date: Friday, April 12, 2024 at 9:47 AM
To: Pascale Gaudet <[Pascale.Gaudet@sib.swiss](mailto:Pascale.Gaudet@sib.swiss)>
Cc: Lionel Breuza <[Lionel.Breuza@sib.swiss](mailto:Lionel.Breuza@sib.swiss)>
Subject: [Protein2GO] Query concerning annotation to protein Q9UBM7
A query has been raised over a GO annotation coming from your group. The details are given below.

You may contact the curator who raised the query directly by replying to this email.
SOURCE   ENTITY TYPE      ENTITY ID                        GO ID            EVIDENCE                 REFERENCE        WITH/FROM                                                EXTENSION
REFG     protein          Q9UBM7                           GO:0016132       ECO:0000318 (IBA)        GO_REF:0000033   PANTHER:PTN001847198|TAIR:locus:2008071                  

Query details:
This is a process specific to plants should not be applied to mammals. "The chemical reactions and pathways resulting in the formation of brassinosteroids, any of a group of steroid derivatives that occur at very low concentrations in plant tissues and may have hormone-like effects."

Sent by Protein2GO on behalf of Lionel Breuza ([Lionel.Breuza@sib.swiss](mailto:Lionel.Breuza@sib.swiss))

**Comment by pgaudet** [comment]
Thanks, fixed.
