### ISSUE TITLE
ERD2 HDEL receptor

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5169]
* **PTHR ID & PTN node:**

GO:0006888	endoplasmic reticulum to Golgi vesicle-mediated transport
IBA with S000000136 , PTN000062353

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBP8B7.22 Pombase
https://www.yeastgenome.org/locus/S000000136

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous annotation. The H/KDEL receptor :

https://www.nature.com/articles/s41467-023-37056-0
 We propose that ERD2 remains fixed as a Golgi gatekeeper, capturing K/HDEL proteins when they arrive and releasing them again into a subdomain for retrograde transport back to the ER.

(but also  many others)

so, shouldn't  it be "GO:0006890  retrograde vesicle-mediated transport, Golgi to endoplasmic reticulum"
rather than GO:0006888	endoplasmic reticulum to Golgi vesicle-mediated transport
@srengel 
@edwong57 

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by edwong57** [comment]
@ValWood, I took a look. Yeah, I think you're right. I fixed our annotation for ERD2 and changed it to GO:0006890 in Noctua. Not sure how long it will take to propogate over.

**Comment by ValWood** [comment]
Thanks!
