### ISSUE TITLE
Review annotations to  GO:1901576 organic substance biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5170]
Dear all, 

The proposal has been made to obsolete GO:1901576 organic substance biosynthetic process
see 
https://github.com/geneontology/go-ontology/issues/27194

There are no annotations or mappings to this term.

Thanks.

**Comment by pgaudet** [comment]
Bad results, AmiGO evidence not available. This will need to b re-ran after the next GO release.
