### ISSUE TITLE
Review annotations to GO:0071703 detection of organic substance

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5175]
Dear all, 

The proposal has been made to obsolete GO:0071703 detection of organic substance
see https://github.com/geneontology/go-ontology/issues/27194

Experimental annotations that need to be reviewed are here: 
[LINK TO ANNOTATION REVIEW GOOGLE SPREADSHEET https://docs.google.com/spreadsheets/d/13oNsCNrIDGH26TAKCvpDW2QJXT_0vsR0g4qMKygR_b4]

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by pgaudet** [comment]
Bad results, AmiGO evidence not available. This will need to b re-ran after the next GO release.
