### ISSUE TITLE
Review annotations to  GO:0010035 response to inorganic substance GO:0010035

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5176]
Dear all, 

The proposal has been made to obsolete GO:0010035 response to inorganic substance GO:0010035
see https://github.com/geneontology/go-ontology/issues/27194

Experimental annotations that need to be reviewed are here: 
[LINK TO ANNOTATION REVIEW GOOGLE SPREADSHEET https://docs.google.com/spreadsheets/d/13oNsCNrIDGH26TAKCvpDW2QJXT_0vsR0g4qMKygR_b4]

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by pgaudet** [comment]
Bad results, AmiGO evidence not available. This will need to b re-ran after the next GO release.

**Comment by RLovering** [comment]
Hi Both

UCL had 2 annotations with this ID based on PMID:10973981, I have deleted both annotations.

UniProtKB:P13866 	SLC5A1 	involved_in 	[GO:0010035](https://www.ebi.ac.uk/QuickGO/term/GO:0010035)
response to inorganic substance
	[ECO:0000314](https://www.ebi.ac.uk/QuickGO/term/ECO:0000314)
IDA
	PMID:10973981 	
	9606 Homo sapiens 	ARUK-UCL 	has_input (CHEBI:17996)
UniProtKB:P30531 	SLC6A1 	involved_in 	[GO:0010035](https://www.ebi.ac.uk/QuickGO/term/GO:0010035)
response to inorganic substance
	[ECO:0000314](https://www.ebi.ac.uk/QuickGO/term/ECO:0000314)
IDA
	PMID:10973981 	
	9606 Homo sapiens 	ARUK-UCL 	has_input (CHEBI:17996)

Also please note that you keep using a google doc template that has a UCL tab which has completely unrelated annotations on it. Please delete the UCL tab from the template you are using 

Hope you both had a great easter, I met up with the family on a safari in South Africa - what an amazing experience.

Ruth

**Comment by pgaudet** [comment]
replaced by https://github.com/geneontology/go-annotation/issues/5187
