### ISSUE TITLE
IPR006223 Glycine cleavage system T protein

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5180]
* **InterPro ID / label**
IPR006223 Glycine cleavage system T protein

* **Example sequences with problematic annotation (ID + gene/protein name):**
Dmel Q9VKR4

* **Description of issue**
I think you can add 'glycine cleavage complex ; GO:0005960' to this entry.

**Comment by blazaropinto** [comment]
Thank you Steven,
I agree, I added this term. The changes will be available in InterPro 100.0.
Best,
Beatriz
