### ISSUE TITLE
Ribose-phosphate pyrophosphokinase (IPR005946)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5185]
* **InterPro ID / label**
Ribose-phosphate pyrophosphokinase (IPR005946)

* **Example sequences with problematic annotation (ID + gene/protein name):**
Regulatory subunits of the complex, e.g.
Dmel FBgn0039790 | CG2246
Human PRPSAP1/PRPSAP2

* **Description of issue**
IPR005946 seems to be present in both the catalytic and regulatory subunits of the heteromeric enzyme complex, so I think the current annotation to "ribose phosphate diphosphokinase activity (GO:0004749)" will have to be removed.

See PMID: 9348095.

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you very much for that. I agree, I removed this term. The changes will be available in InterPro 100.0

Best,
Beatriz
