### ISSUE TITLE
PTN008604283  UBIQUITIN-CONJUGATING ENZYME E2 (PTHR24068)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5186]
* **PTHR ID & PTN node:**
PTN008604283 
UBIQUITIN-CONJUGATING ENZYME E2 (PTHR24068)

* **Sequences with problematic annotation (ID + gene/protein name):**
FBgn0026316 | Ubc10
FBgn0017456 | Ubc84D
FBgn0011217 | eff
FBgn0035584 | CG17030
& orthologs

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Erroneous source 

Currently, this node (which comprises E2 enzymes) is annotated with "ubiquitin ligase complex" (i.e. the E3) based on these three annotations:
(SCHPO|PomBase=SPBC119.02|UniProtKB=P46595) = Ubiquitin-conjugating enzyme E2 4
(HUMAN|HGNC=12474|UniProtKB=P51668) = Ubiquitin-conjugating enzyme E2 D1
(HUMAN|HGNC=12475|UniProtKB=P62837) = Ubiquitin-conjugating enzyme E2 D2

I think "ubiquitin ligase complex" annotation on these 3 proteins should be removed.

I've disputed the two human annotations with Ruth via P2GO.
@ValWood Could you check the pombe annotation?

**Comment by ValWood** [comment]
I'd assumed we would include the E2 subunit because its presence is critical for the function of the complex?- there is no ubiquitin, or ligase without it?

https://en.wikipedia.org/wiki/SCF_complex
(even though the SCF part is the core it isn't a functional unit on its own)

There is no  separate "ubiquitin conjugating complex".

**Comment by ValWood** [comment]
The  ubiquitin conjugating complex annotations I have are for "HULC complex"
and this is because of the dual ligase/conjugating complex parentage (which is a bit weird)

**Comment by sjm41** [comment]
I believe E1, E2 and E3 are generally seen and described as distinct complexes - GO certainly has them as 3 discrete terms. (copied below)

I think the HULC complex is an outlier - seems this is an unusual case where the stable complex does combine and E2 and E3?

SCF is a stand-alone (albeit multi-subunit) E3 complex - no E2 involved.

id: GO:0120123
name: ubiquitin activating enzyme complex
def: "A protein complex responsible for the catalysis of the reaction: E1 + ubiquitin + ATP--> E1-ubiquitin + AMP + PPi, where the E1-ubiquitin linkage is a thioester bond between the C-terminal glycine of Ub and a sulfhydryl side group of an E1 cysteine residue. This is the first step in a cascade of reactions in which ubiquitin is ultimately added to a protein substrate." [GOC:lnp, PMID:9545234]
synonym: "E1 complex" EXACT [GOC:lnp]
synonym: "E1 ubiquitin-activating enzyme" RELATED [GOC:lnp]
intersection_of: GO:0140535 ! intracellular protein-containing complex
intersection_of: capable_of GO:0004839 ! ubiquitin activating enzyme activity


id: GO:0031371
name: ubiquitin conjugating enzyme complex
def: "Any complex that possesses ubiquitin conjugating enzyme activity." [GOC:mah]
subset: goslim_pir
synonym: "E2 complex" RELATED []
intersection_of: GO:0140535 ! intracellular protein-containing complex
intersection_of: capable_of GO:0061631 ! ubiquitin conjugating enzyme activity


id: GO:0000151
name: ubiquitin ligase complex
def: "A protein complex that includes a ubiquitin-protein ligase and enables ubiquitin protein ligase activity. The complex also contains other proteins that may confer substrate specificity on the complex." [GOC:jh2, PMID:9529603]
subset: goslim_pir
intersection_of: GO:0140535 ! intracellular protein-containing complex
intersection_of: capable_of GO:0061630 ! ubiquitin protein ligase activity


===


id: GO:0033503
name: HULC complex
def: "A ubiquitin ligase complex that contains two RING finger proteins, which have ubiquitin ligase activity, in addition to a protein with ubiquitin-conjugating enzyme activity; catalyzes the ubiquitination of histone H2B at lysine 119 (or the equivalent residue). In Schizosaccharomyces the subunits are Rhp6, Shf1, Brl2/Rfp1 and Brl1/Rfp2." [GOC:mah, PMID:17363370, PMID:17374714]
is_a: GO:0000151 ! ubiquitin ligase complex
is_a: GO:0031371 ! ubiquitin conjugating enzyme complex
relationship: part_of GO:0000785 ! chromatin

**Comment by ValWood** [comment]
I'm still not sure. This seems to be an accurate representation of a functional SCF complex:

<img width="263" alt="Screenshot 2024-04-23 at 08 52 36" src="https://github.com/geneontology/go-annotation/assets/7359272/4df7e66e-a437-451d-bb3e-8e1f93107982">

there is no ligase without the E2.  So although the conjugating enzyme my exist independently, I wouldn't annotate that ?
(in GO because the GO rules state:

https://wiki.geneontology.org/Protein_complexes
A cellular component should be composed of more than one subunit (protein and another protein or a RNA), forming a stable interaction that exists as a **functional unit** in vivo.

This is a classical ligase complex, like APC which also includes the E2 subunit:

<img width="253" alt="Screenshot 2024-04-23 at 08 57 56" src="https://github.com/geneontology/go-annotation/assets/7359272/75dfb016-df5b-473c-8dd0-7cfe861f4a69">

**Comment by sjm41** [comment]
Hi Val

I realise now that "E2 complexes" (ubiquitin conjugating enzyme complexes) are extremely rare.  Most E2s are single-subunit enzymes, and there are only 3 examples of "E2 complexes" described in the GO:
```
ubiquitin conjugating enzyme complex (GO:0031371)
    |_UBC13-UEV1A complex (GO:0035370) = UBC13-MMS2 complex (GO:0031372) [see #27697]
    |_HULC complex (GO:0033503)
    |_CUE1-UBC7 ubiquitin-conjugating enzyme complex (GO:1990389)
```

So, I detract my suggestion that "ubiquitin ligase complex" should be changed to "ubiquitin conjugating enzyme complex" for these three proteins!:
(SCHPO|PomBase=SPBC119.02|UniProtKB=P46595) = Ubiquitin-conjugating enzyme E2 4
(HUMAN|HGNC=12474|UniProtKB=P51668) = Ubiquitin-conjugating enzyme E2 D1
(HUMAN|HGNC=12475|UniProtKB=P62837) = Ubiquitin-conjugating enzyme E2 D2


Instead, I would suggest that the "ubiquitin ligase complex" annotation should just be removed for those E2 proteins.
Yes, the E2 binds to the E3 during ubiquitin transfer, but I don't think these are 'stable interactions'.  If that was the case, then all E2 enzymes would have to be annotated to "ubiquitin ligase (E3)complex".


The wikipedia pages referred to above say:
1. "The SCF complex contains a variable F-box protein and three core subunits: F-box protein, Skp1, Collin, RBX1" and "Rbx1 binds the E2–ubiquitin conjugate."
2. "The APC/C is a large complex of 11–13 subunit proteins, including a cullin (Apc2) and RING (Apc11) subunit much like SCF." and "RING/APc11 binds to the E2-ubiquitin conjugate that catalyzes the transfer of ubiquitin to an active site in E2" and "APC/C brings together an E2 ubiquitin-conjugating enzyme and the D-box".

Also, the pombe paper that's the source for the SPBC119.02|UniProtKB=P46595 annotation mentioned above says:
_To obtain the SpSCF[Fbh1] complex, we separately purified Fbh1-Skp1 and Pcu1 (fission yeast Cullin1)-Rbx1 complexes, mixed them to form the SpSCF[Fbh1] complex, and used these recombinant proteins in an in vitro ubiquitination assay. Several SCF complexes have ubiquitin E3 ligase activity that requires either Ubc4 or Cdc34 as the E2 enzyme [47]. In fission yeast, Ubc15 is a candidate functional homolog of Ccd34. Thus, we tested both Ubc4 and Ubc15 as candidate E2 enzymes in a ubiquitination assay with the SCF[Fbh1] complex_
i.e. the authors also talk about their 'SCF' complex as a separate entity from the E2 enzyme.

So, yes, the E3 complex (e.g. SCF or APC/C) definitely binds to an E2 during ubiquitin transfer, but I wouldn't say that an E2 is "part of an E3 complex" (except perhaps for that unusual case of the HULC complex).

**Comment by ValWood** [comment]
OK, sounds good. I'll edit  the annotation to fit this!

**Comment by ValWood** [comment]
PomBase fixed

**Comment by ValWood** [comment]
Also
[GO:0000836](https://www.pombase.org/term/GO:0000836)	
[Hrd1p ubiquitin ligase complex](https://www.pombase.org/term/GO:0000836)
[ISO](http://wiki.geneontology.org/index.php/Inferred_from_Sequence_Orthology_(ISO)) with [S000004624](https://www.yeastgenome.org/search?q=S000004624&is_quick=true)	[GO_REF:0000024](https://www.pombase.org/reference/GO_REF:0000024)

**Comment by marcfeuermann** [comment]
Annotation removed
