### ISSUE TITLE
Block annotation propagation to fly Bursicon from GREMLIN 1 (PTHR15283)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5188]
* **PTHR ID & PTN node:**
* PTN002309998
* [GREMLIN 1 (PTHR15283)](http://www.pantherdb.org/panther/family.do?clsAccession=PTHR15283)

* **Sequences with problematic annotation (ID + gene/protein name):**
* FB:FBgn0038901 , Burs

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
* Burs has no role in BMP signaling, in fly it is a neuropeptide hormone, so these terms are incorrect:
-sequestering of BMP from receptor via BMP binding
-animal organ morphogenesis
-BMP binding
* Please block annotations from this node

**Comment by marcfeuermann** [comment]
Annotated change of function (loss and gain) for the corresponding node.
