### ISSUE TITLE
Review annotations to GO:0019145 aminobutyraldehyde dehydrogenase activity GO:0033737 1-pyrroline dehydrogenase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5189]
These two terms represent the same reaction: 

GO:0019145 aminobutyraldehyde dehydrogenase activity >> keep
GO:0033737 1-pyrroline dehydrogenase activity >> obsolete

(https://github.com/geneontology/go-ontology/issues/27695)

**Comment by amandamackie** [comment]
Done

**Comment by pgaudet** [comment]
Thanks!
