### ISSUE TITLE
Review annotations to GO:0047760  butyrate-CoA ligase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5190]
Dear all, 

The proposal has been made to obsolete GO:0047760  butyrate-CoA ligase activity 
and replace it by  GO:0031956 medium-chain fatty acid-CoA ligase activity

see https://github.com/geneontology/go-ontology/issues/25800

**Comment by suzialeksander** [comment]
This term was obsoleted because it represents a specific substrate of medium-chain fatty acid-CoA ligase activity ; GO:0031956.
