### ISSUE TITLE
IPR036549 Cytochrome c oxidase, subunit VIb superfamily

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5193]
IPR036549
Cytochrome c oxidase, subunit VIb superfamily

This is a homologous superfamily entry.
It is annotated with "[respiratory chain complex IV (GO:0045277)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0045277)", but I don't see that annotation on any of the more specific 'child' InterPro entries, maybe because some of them are described as 'assembly factors' rather than a real complex IV subunit?

So I think this GO term should be removed from this entry.

**Comment by blazaropinto** [comment]
Hi Steven,

Thank you for this. I see, I suppose you mean the overlapping entries. I removed this CC term as it is indeed problematic in such a big family. The changes will be available in InterPro 100.0

Best,
Beatriz

**Comment by sjm41** [comment]
Right, proteins classed as complex IV assembly factors were incorrectly getting 'part of complex IV' annotations.
Thanks!
