### ISSUE TITLE
Review annotations to GO:0008532 'N-acetyllactosaminide beta-1,3-N-acetylglucosaminyltransferase activity and GO:0008457 beta-galactosyl-N-acetylglucosaminylgalactosylglucosyl-ceramide ...

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5194]
GO:0008532 'N-acetyllactosaminide beta-1,3-N-acetylglucosaminyltransferase activity
GO:0008457 beta-galactosyl-N-acetylglucosaminylgalactosylglucosyl-ceramide beta-1,3-acetylglucosaminyltransferase activity

Based on xrefs, these represent the same activity

**Comment by deustp01** [comment]
For what it's worth, Reactome has not used GO:0008457 at all, but has used GO:0008532 to annotate the activity of human [B3GNT1,2,3,4,7](https://reactome.org/content/detail/R-HSA-2046221) proteins in [R-HSA-2025724](https://reactome.org/content/detail/R-HSA-2025724) "B3GNT1,2,3,4,7 add GlcNAc to form Keratan-PG" with PMID:15620693 and PMID:11821425 as evidence. (But i have no expertise in this area, so this is all I know - no insight into the relative appropriateness of the tow GO terms.)

**Comment by pgaudet** [comment]
Thanks @deustp01 ! 

Actually GO:0008457 is only used once by UniProt to annotate Q9BYG0 (annotation is from 2003), which is annotated by the same paper by RHEA to https://www.rhea-db.org/rhea/13905, which corresponds to GO [lactosylceramide 1,3-N-acetyl-beta-D-glucosaminyltransferase activity](http://purl.obolibrary.org/obo/GO_0047256)

So I will move the annotation and obsolete the term GO:0008457. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsoletion ticket is here: https://github.com/geneontology/go-ontology/issues/27713
