### ISSUE TITLE
Review annotations to GO:0030792 methylarsonite methyltransferase activity (with replacement)

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5195]
Dear all, 

The proposal has been made to obsolete GO:0030792 methylarsonite methyltransferase activity.
see https://github.com/geneontology/go-ontology/issues/27410.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1hJC98ciRlpQFE23z-PsFjlmMeAshIA1jybr2SuJJin8/edit#gid=0

Impacted groups: 
UniProt 3

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
MetaCyc:2.1.1.138-RXN > GO:methylarsonite methyltransferase activity ; GO:0030792

Thanks.

**Comment by raymond91125** [comment]
Is there a standard URL construct for MetaCyc XREFs? e.g. http://XXX/XXX/2.1.1.138-RXN? They are not always easy to find.

**Comment by pgaudet** [comment]
It should be MetaCyc:XXXX (for example MetaCyc:2ASDEG-PWY; see https://wiki.geneontology.org/RHEA_and_EC_mappings --- I know this page needs a lift!) 

I usually look at other xrefs and build them the same way.

**Comment by raymond91125** [comment]
What I meant was: Is there a standard way to see if a MetaCyc ref is still valid. I usually had to Google and that seems haphazard.

**Comment by pgaudet** [comment]
Can you not click on the link from AmiGO ?

**Comment by raymond91125** [comment]
I just realized you've already obsoleted GO:0030792 https://github.com/geneontology/go-ontology/issues/27695

**Comment by pgaudet** [comment]
Sorry! I thought I only did the ones with problems in synonym xrefs. I didn't want to duplicate the work!

**Comment by raymond91125** [comment]
Just for reference:
From AmiGO https://amigo.geneontology.org/amigo/term/GO:0050303, I see this URL: <https://biocyc.org/META/NEW-IMAGE?type=NIL&object=LYSINE-6-DEHYDROGENASE-RXN>. Replacing the object, URL <https://biocyc.org/META/NEW-IMAGE?type=NIL&object=2.1.1.138-RXN> is redirected to <https://biocyc.org/reaction?orgid=META&id=2.1.1.138-RXN>. But it is not the same reaction as that of GO:0030792. Plus it says: "This reaction can occur spontaneously. No enzyme is required or has been identified." I'm confused.

**Comment by pgaudet** [comment]
Hi @raymond91125 

1. I am not clear how you landed on [GO:0050303](https://amigo.geneontology.org/amigo/term/GO:0050303), lysine 6-dehydrogenase activity from GO:0030792 methylarsonite methyltransferase activity
2. From MetaCyc [LYSINE-6-DEHYDROGENASE-RXN](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=LYSINE-6-DEHYDROGENASE-RXN), how did you get to MetaCyc [2.1.1.138-RXN](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=2.1.1.138-RXN) ?
