### ISSUE TITLE
Review annotations to GO:0047844 deoxycytidine deaminase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5196]
Dear all, 

The proposal has been made to obsolete GO:0047844 deoxycytidine deaminase activity.
see https://github.com/geneontology/go-ontology/issues/27410.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1PO77zYKLP6nsPHPuag7bEeuF5t56VFfmTPFIAnGfQfc/edit#gid=0

Impacted groups: 
EcoCyc 1
GeneDB 1
MTBBASE 1
TAIR 1
UniProt 4
WB 2

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
UniRule:UR001376779 > GO:deoxycytidine deaminase activity ; GO:0047844

Thanks.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by pgaudet** [comment]
@raymond91125 please confirm that the term has been replaced by GO:0004126 cytidine deaminase activity.

For most groups that would mean that no re-annotation is needed. 

Thanks, Pascale

**Comment by deustp01** [comment]
and one Reactome reaction / catalystActivity fixed.

**Comment by PedroRaposo** [comment]
GO:0047844 (deoxycytidine deaminase activity) has now been removed from UniRule UR001376779. This rule has the molecular function GO:0004126 (cytidine deaminase activity) so the rule still contains this information.

**Comment by pgaudet** [comment]
The term was obsoleted. Remaining annotations will appear in error reports.
