### ISSUE TITLE
PTN000326738  not autophagy

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5197]
* **PTHR ID & PTN node:**

GO:0000422	
[autophagy of mitochondrion](https://www.pombase.org/term/GO:0000422)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [Q9Y3D6](https://www.uniprot.org/uniprot/Q9Y3D6) , [PTN000326738](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000326738)	[GO_REF:0000033](https://www.pombase.org/reference/GO_REF:0000033)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC11G11.01

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

Note, I queried the annotation in protein2GO but there are also lots of annotation to apoptosis for this protein. These also look like phenotypes. I only checked one (IDA) and it looked to be a consequence of deleting Fis1 (but I did not flag this one)
@pgaudet  @Antonialock  If you look at these (expired accounts) could you review/remove the apoptosis annotations too if appropriate? @marcfeuermann  may know if this is really involved in apoptosis pathway but it looks like a readout to me.

**Comment by ValWood** [comment]
Has anybody noticed that when you dispute annotation in protein2GO, they are no longer flagged? The disputes appear to have worked because I got an e-mail notification....

**Comment by ValWood** [comment]
@Antonialock has fixed the uniprot entry

**Comment by marcfeuermann** [comment]
Annotations removed from PAINT.
