### ISSUE TITLE
PTN000797965 indirect for purine nucleobase biosynthetic process/ methylenetetrahydrofolate reductase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5201]
* **PTHR ID & PTN node:**
GO:0009113	
purine nucleobase biosynthetic process
IBA with PTN000797965 , S000001788

GO:0006164	
purine nucleotide biosynthetic process
IEA with KW-0658

this is the last step in folate synthesis.
Folate is co-factor for nucleotide metabolism (and lots of other compoundes)

this seems indirect

cc @Antonialock for KW
cc @edwong57 for source

* **Sequences with problematic annotation (ID + gene/protein name):**

e.g  S. pombe https://www.pombase.org/gene/SPBC1711.04

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Corrected.
