### ISSUE TITLE
Review annotations to GO:0035370 UBC13-UEV1A complex

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5202]
Dear all, 

The proposal has been made to obsolete UBC13-UEV1A complex GO:0035370

see https://github.com/geneontology/go-ontology/issues/27697

**Comment by pgaudet** [comment]
2 ComplexPortal
2 FlyBase (will be automatically replaced)
2 UniProt (will be automatically replaced)
1 ZFIN (will be automatically replaced)

**Comment by sandraorchard** [comment]
Complex Portal done
