### ISSUE TITLE
 IPR033904 farnesyltranstransferase activity (GO:0004311)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5207]
* **InterPro ID / label**

[IPR033904](http://www.ebi.ac.uk/interpro/entry/IPR033904)

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC646.05c erg9

* **Description of issue**

erg9 is
farnesyl-diphosphate farnesyltransferase activity (GO:0004310)

farnesyltranstransferase activity (GO:0004311)  is
https://www.pombase.org/gene/SPBC36.06c

**Comment by blazaropinto** [comment]
Hi Val,

Thank you very much for that. I agree, I updated this term. I also added the more general [GO:0004659](https://www.ebi.ac.uk/QuickGO/term/GO:0004659) to IPR000092, where O59703 is included. The changes will be available in InterPro 100.0.

Best,
Beatriz
