### ISSUE TITLE
Review annotations to children of GO:0015291 secondary active transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5209]
- [x] GO:0015541 secondary active cyanate transmembrane transporter activity
- [ ] GO:0015355 secondary active monocarboxylate transmembrane transporter activity
- [x] GO:0015322 secondary active oligopeptide transmembrane transporter activity
- [ ] GO:0008513 secondary active organic cation transmembrane transporter activity
- [ ] GO:0015558 secondary active p-aminobenzoyl-glutamate transmembrane transporter activity
- [ ] GO:0008271 secondary active sulfate transmembrane transporter activity
- [ ] GO:0015291 secondary active transmembrane transporter activity
- [ ] GO:0071913 citrate secondary active transmembrane transporter activity
- [x] GO:0015328 cystine secondary active transmembrane transporter activity
- [ ] GO:0008490 arsenite secondary active transmembrane transporter activity
- [ ] GO:0005477 pyruvate secondary active transmembrane transporter activity
- [x] GO:0015351 bilirubin secondary active transmembrane transporter activity
- [ ] GO:0042960 antimonite secondary active transmembrane transporter activity
- [ ] GO:0000102 L-methionine secondary active transmembrane transporter activity
- [x] GO:0015400 low-affinity secondary active ammonium transmembrane transporter activity
- [x] GO:0000227 oxaloacetate secondary active transmembrane transporter activity
- [ ] GO:0015398 high-affinity secondary active ammonium transmembrane transporter activity
- [ ] GO:0015513 high-affinity secondary active nitrite transmembrane transporter activity
- [ ] GO:0005371 tricarboxylate secondary active transmembrane transporter activity
- [x] GO:0015324 peptide-acetyl-CoA secondary active transmembrane transporter activity
- [ ] GO:0005294 neutral L-amino acid secondary active transmembrane transporter activity
- [x] GO:0022897 proton-dependent peptide secondary active transmembrane transporter activity
- [x] GO:1901680 sulfur-containing amino acid secondary active transmembrane transporter activity
- [ ] GO:0005427 proton-dependent oligopeptide secondary active transmembrane transporter activity

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/10vccQ5GzJqiXPw4aeuHfAZ0jWO4xebGLqz3xRyvq_hs/edit#gid=0

**Comment by suzialeksander** [comment]
Current status of terms in this ticket:

[GO:0000227](https://www.ebi.ac.uk/QuickGO/term/GO:0000227) 	obsolete oxaloacetate secondary active transmembrane transporter activity 	
[GO:0008513](https://www.ebi.ac.uk/QuickGO/term/GO:0008513) 	secondary active organic cation transmembrane transporter activity 	
[GO:1901680](https://www.ebi.ac.uk/QuickGO/term/GO:1901680) 	obsolete sulfur-containing amino acid secondary active transmembrane transporter activity 	
[GO:0008271](https://www.ebi.ac.uk/QuickGO/term/GO:0008271) 	secondary active sulfate transmembrane transporter activity 	
[GO:0008490](https://www.ebi.ac.uk/QuickGO/term/GO:0008490) 	arsenite secondary active transmembrane transporter activity 	
[GO:0000102](https://www.ebi.ac.uk/QuickGO/term/GO:0000102) 	L-methionine secondary active transmembrane transporter activity 	
[GO:0015513](https://www.ebi.ac.uk/QuickGO/term/GO:0015513) 	high-affinity secondary active nitrite transmembrane transporter activity 	
[GO:0015324](https://www.ebi.ac.uk/QuickGO/term/GO:0015324) 	obsolete peptide-acetyl-CoA secondary active transmembrane transporter activity 	
[GO:0015322](https://www.ebi.ac.uk/QuickGO/term/GO:0015322) 	obsolete secondary active oligopeptide transmembrane transporter activity 	
[GO:0015558](https://www.ebi.ac.uk/QuickGO/term/GO:0015558) 	secondary active p-aminobenzoyl-glutamate transmembrane transporter activity 	
[GO:0015541](https://www.ebi.ac.uk/QuickGO/term/GO:0015541) 	secondary active cyanate transmembrane transporter activity 	
[GO:0015291](https://www.ebi.ac.uk/QuickGO/term/GO:0015291) 	secondary active transmembrane transporter activity 	
[GO:0005371](https://www.ebi.ac.uk/QuickGO/term/GO:0005371) 	tricarboxylate secondary active transmembrane transporter activity 	
[GO:0005294](https://www.ebi.ac.uk/QuickGO/term/GO:0005294) 	neutral L-amino acid secondary active transmembrane transporter activity 	
[GO:0005427](https://www.ebi.ac.uk/QuickGO/term/GO:0005427) 	proton-dependent oligopeptide secondary active transmembrane transporter activity 	
[GO:0005477](https://www.ebi.ac.uk/QuickGO/term/GO:0005477) 	pyruvate secondary active transmembrane transporter activity 	
[GO:0042960](https://www.ebi.ac.uk/QuickGO/term/GO:0042960) 	antimonite secondary active transmembrane transporter activity 	
[GO:0015355](https://www.ebi.ac.uk/QuickGO/term/GO:0015355) 	secondary active monocarboxylate transmembrane transporter activity 	
[GO:0015351](https://www.ebi.ac.uk/QuickGO/term/GO:0015351) 	obsolete bilirubin secondary active transmembrane transporter activity 	
[GO:0015328](https://www.ebi.ac.uk/QuickGO/term/GO:0015328) 	obsolete cystine secondary active transmembrane transporter activity 	
[GO:0015398](https://www.ebi.ac.uk/QuickGO/term/GO:0015398) 	obsolete high-affinity secondary active ammonium transmembrane transporter activity 	
[GO:0015400](https://www.ebi.ac.uk/QuickGO/term/GO:0015400) 	obsolete low-affinity secondary active ammonium transmembrane transporter activity 	
[GO:0022897](https://www.ebi.ac.uk/QuickGO/term/GO:0022897) 	obsolete proton-dependent peptide secondary active transmembrane transporter activity 	
[GO:0071913](https://www.ebi.ac.uk/QuickGO/term/GO:0071913) 	citrate secondary active transmembrane transporter activity

**Comment by suzialeksander** [comment]
@pgaudet no clear request, is there a suggested action/alt term or are these terms being obsoleted?
