### ISSUE TITLE
PTN005164964 not all ubiquinone biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5212]
* **PTHR ID & PTN node:**

PTN005164964 
ubiquinone biosynthetic process
IBA with WBGene00000763 , coq3 , Q9NZJ6 , locus:2052761 , S000005456 , P17993 , 2380 , PTN005164964

* **Sequences with problematic annotation (ID + gene/protein name):**

A bunch of fission yeast methyltransferases  
SPAC750.03c
SPAC977.03
SPACUNK4.09
SPBC1348.04
with some similarity to coq3 have been annotated to GO:0006744 

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
Note that these particular methyltransferases are likely to be horizontal transfer because they are more closely related to prokaryotic methyltransferases even than other Schizos...

**Comment by marcfeuermann** [comment]
Family reviewed.
