### ISSUE TITLE
Review annotations to GO:0008519 ammonium transmembrane transporter activity & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5213]
GO:0008519 ammonium transmembrane transporter activity
GO:0015398 high-affinity secondary active ammonium transmembrane transporter activity
GO:0015400 low-affinity secondary active ammonium transmembrane transporter activity

According to the TCDB cross reference, GO:0008519 ammonium transmembrane transporter activity is a channel, so the two children GO:0015398 high-affinity secondary active ammonium transmembrane transporter activity and
GO:0015400 low-affinity secondary active ammonium transmembrane transporter activity are incorrectly placed. 

Annotations are here: https://docs.google.com/spreadsheets/d/1tykMgU5ypmCJuhWuhlmIrHIXYtm50M2lZXhEG_yAGXE/edit#gid=0

**Comment by pfey03** [comment]
I changed the annotations it was only one gene

**Comment by suzialeksander** [comment]
The terms  GO:0015398 high-affinity secondary active ammonium transmembrane transporter activity and GO:0015400 low-affinity secondary active ammonium transmembrane transporter activity have been obsoleted and and replaced by the parent GO:0008519
