### ISSUE TITLE
PTN000432120  fatty acid beta-oxidation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5214]
* **PTHR ID & PTN node:**

 erg10  is annotated to beta-oxidation
 
[GO:0006635](https://www.pombase.org/term/GO:0006635)	
[fatty acid beta-oxidation](https://www.pombase.org/term/GO:0006635)
[IBA](http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)) with [FBgn0025352](http://flybase.org/reports/FBgn0025352.html) , [P55084](https://www.uniprot.org/uniprot/P55084) , [620513](https://rgd.mcw.edu/rgdweb/search/search.html?term=620513) , [PTN000432120](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000432120) , [620482](https://rgd.mcw.edu/rgdweb/search/search.html?term=620482)

* **Sequences with problematic annotation (ID + gene/protein name):**

erg10

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I think this one might be propagation

* Add the label 'high priority' if needed. Generally high high-priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
I meant to add I wasn't sure about this but the definition is 

A fatty acid oxidation process that results in the complete oxidation of a long-chain fatty acid.......

**Comment by marcfeuermann** [comment]
Family has been re-annotated.
