### ISSUE TITLE
IPR002225 3-beta-hydroxy-delta5-steroid dehydrogenase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5215]
* **InterPro ID / label**

HI,
could you have a look at this mapping and see where it comes from? I could not detect a source annotation (at least in eukaryotes), and it isn't a parent of any of the more specific annotations
[GO:0003854](https://www.pombase.org/term/GO:0003854)	
[3-beta-hydroxy-delta5-steroid dehydrogenase activity](https://www.pombase.org/term/GO:0003854)
(http://www.ebi.ac.uk/interpro/entry/IPR002225)

https://www.pombase.org/gene/SPBC3F6.02c

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

**Comment by blazaropinto** [comment]
Hi Val,

Thank you very much for that. This term is mapped to human P14060 (PMID:1401999) or C.elegans Q9XWF0 (PMID:18495818), but shouldn't propagate to all proteins in this entry. This entry already has the more general MF [GO:0016616](https://www.ebi.ac.uk/QuickGO/term/GO:0016616), so I'll just remove [GO:0003854](https://www.pombase.org/term/GO:0003854). The changes will be available in InterPro 100.0.

Best,
Beatriz
