### ISSUE TITLE
Review annotations to GO:0019008 molybdopterin synthase complex

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5216]
Dear all, 

The proposal has been made to obsolete GO:0019008 molybdopterin synthase complex (replaced by GO:1990140).
see https://github.com/geneontology/go-ontology/issues/27655

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1huQfgPF9LyE-IsRUnITuhYJsu2Mn5S4DyLcfFIjPpA8/edit#gid=0

Impacted groups: 
ComplexPortal 1
FlyBase 3
UniProt 1

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

UniRule:UR000160817 > GO:molybdopterin synthase complex ; GO:0019008
UniRule:UR000161417 > GO:molybdopterin synthase complex ; GO:0019008
HAMAP:MF_03051 > GO:molybdopterin synthase complex ; GO:0019008
HAMAP:MF_03052 > GO:molybdopterin synthase complex ; GO:0019008
InterPro:IPR010505 Molybdenum cofactor biosynthesis protein A-like, twitch domain > GO:molybdopterin synthase complex ; GO:0019008
InterPro:IPR028888 Molybdopterin synthase catalytic subunit, eukaryotes > GO:molybdopterin synthase complex ; GO:0019008

Thanks.

**Comment by sjm41** [comment]
Thanks @raymond91125 
Won't these annotations get automatically transferred given it's effectively a merge (obsoletion and replace by)?

**Comment by pgaudet** [comment]
@sjm41 

ComplexPortal, InterPro and UniRule need to be manually updated.

**Comment by raymond91125** [comment]
Is there a table showing what annotation types would be automatically replaced, thus not need assignment?

**Comment by sjm41** [comment]
The FlyBase annotation will get automatically updated, right?

**Comment by pgaudet** [comment]
@sjm41 

Yes

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by PedroRaposo** [comment]
@pedruzzi, could the GO term GO:0019008 (molybdopterin synthase complex) be changed accordingly on rules UR000160817 and UR000161417, since these are HAMAP rules, please?

**Comment by pedruzzi** [comment]
HAMAP rules fixed

**Comment by suzialeksander** [comment]
@blazaropinto can you check if InterPro:IPR010505 needs to be changed? IPR028888 looks to be corrected.

**Comment by sarach06** [comment]
Hi Suzie,
Beatriz is on holiday at the moment. I had a look and GO:0019008 is not in IPR010505 (here is the public version in InterPro 101.0 [https://www.ebi.ac.uk/interpro/entry/InterPro/IPR010505/](url)). Please let me know if you have any questions.

Best regards,
Sara
