### ISSUE TITLE
Review annotations to GO:0008043 intracellular ferritin complex

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5217]
Dear all, 

The proposal has been made to obsolete GO:0008043 intracellular ferritin complex
see https://github.com/geneontology/go-ontology/issues/27758.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1xbExal30HXi9mNe2iRJ4x9Fkwv0BahAqYHnEL7lR2LE/edit#gid=0

Impacted groups: 
FlyBase 2
UniProt 2

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by pgaudet** [comment]
Replaced by GO:0070288

Annotations will be replaced.
