### ISSUE TITLE
Review annotations to GO:0008746 NAD(P)+ transhydrogenase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5218]
Dear all, 

The proposal has been made to obsolete GO:0008746 NAD(P)+ transhydrogenase activity.
see [https://github.com/geneontology/go-ontology/issues/27814.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1K3WD0kGOAJgK_ypNR-aevrFN0oiDPrOxuaoe6K0_820/edit#gid=0

Impacted groups: 
EcoCyc 4
TAIR 2

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
interpro2go	InterPro:IPR026255 NAD(P) transhydrogenase, alpha subunit > GO:NAD(P)+ transhydrogenase activity ; GO:0008746
reactome2go	Reactome:R-HSA-450971 > GO:NAD(P)+ transhydrogenase activity ; GO:0008746

Thanks.

**Comment by deustp01** [comment]
Do I understand correctly, the recommendation is to replace annotations to GO:0008746 NAD(P)+ transhydrogenase activity with ones to  GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity? if so, that's fine - will do; if not, what is the recommendation?

**Comment by amandamackie** [comment]
I'm also confused. GO:0003957 is currently a child of  GO:0015078 proton transmembrane transporter activity. Will that change?
The main distinction I need is between an enzyme that moves protons across a membrane (EC7.1.1.1 proton-translocating NAD(P)+ transhydrogenase) and one that doesn't (EC6.1.1.1/EC6.1.1.3 NAD(P)+ transhydrogenase)

**Comment by pgaudet** [comment]
Hi @amandamackie 
I think the proposal is to move the annotations of pntA and pntB from GO:0008746 NAD(P)+ transhydrogenase activity **to GO:0008750 proton-translocating NAD(P)+ transhydrogenase activity**

and for sthA, move from GO:0008746 NAD(P)+ transhydrogenase activity to **GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity**. This would match the EC mappings in UniProt. 

Does this sound correct? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@deustp01 
I cannot find any Reactome annotations - the request is to reannotate to either GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity or GO:0008750 proton-translocating NAD(P)+ transhydrogenase activity. 

Thanks, Pascale

**Comment by deustp01** [comment]
From the top of the ticket,

> reactome2go Reactome:R-HSA-450971 > GO:NAD(P)+ transhydrogenase activity ; GO:0008746

and GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity will work. Thanks

**Comment by amandamackie** [comment]
@pgaudet 
That makes sense. My only concern is that in the ontology GO:0003957 NAD(P)+ transhydrogenase is currently a child of GO:0015078 proton transmembrane transporter activity and sthA is not the proton-translocating enzyme (PntAB is).

**Comment by pgaudet** [comment]
Good point! I'll add comments on the ontology ticket https://github.com/geneontology/go-ontology/issues/27814

**Comment by amandamackie** [comment]
Now changed in EcoCyc

**Comment by pgaudet** [comment]
Obsoletion is done. Errors will appear in rules reports.
