### ISSUE TITLE
Review annotations to GO:1900274 regulation of phospholipase C activity & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5219]
The proposal has been made to obsolete

GO:1900274 regulation of phospholipase C activity
GO:1900275 negative regulation of phospholipase C activity
GO:0010863 positive regulation of phospholipase C activity
GO:0007202 activation of phospholipase C activity

see https://github.com/geneontology/go-ontology/issues/27854

Annotations are here: https://docs.google.com/spreadsheets/d/1z9gn6boDvyURD5fE9CQoW44q25v9alkzIqVRRvYZ8y8/edit#gid=0

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<meta charset=utf-8>
<meta charset=utf-8>

<body link="#467886" vlink="#96607D">

Group | Number of annotations
-- | --
AgBase | 3
ARUK-UCL | 1
BHF-UCL | 2
CAFA | 1
MGI | 2
PseudoCAP | 1
UniProt | 22
ZFIN | 1
  |  

</body>

</html>

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by sramachand** [comment]
ZFIN done

**Comment by Antonialock** [comment]
CAFA and uniprot done

**Comment by suzialeksander** [comment]
These terms have been obsoleted; remaining annotations will appear in GORULES error reports.
