### ISSUE TITLE
IPR018168 not GO:0016709

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5225]
* **InterPro ID / label**

GO:0016709 | oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen | IEA with IPR018168

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC146.12

* **Description of issue**

Maybe this is a bacterial/eukaryotic difference, because the PROSIT family covers bacterial members but as far as I can tell, the reactions performed by coq6 don't involve NAD(P)H

**Comment by blazaropinto** [comment]
Hi Val,

Thank you very much for this. I removed the term. The change will be visible in InterPro 100.0.

Best,

Beatriz
