### ISSUE TITLE
PTN000252522  not always GO:1901006 | ubiquinone-6 biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5226]
* **PTHR ID & PTN node:**

coq11 | ↑is_a GO:1901006 | ubiquinone-6 biosynthetic process | IBA with PTN000252522 , S000004281

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1840.09

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous propagation.
S. pombe produces ubiquinone-10 (Coenzyme Q10) instead of ubiquinone-6

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
see
https://www.pombase.org/reference/PMID:24911838
Functional conservation of coenzyme Q biosynthetic genes among yeasts, plants, and humans.
In living organisms, CoQ exists in a number of different forms with differing isoprenoid side chain lengths. For example, in humans and the fission yeast Schizosaccharomyces pombe, the CoQ side chain comprises ten isoprene units (CoQ10), whereas those in Arabidopsis thaliana and Saccharomyces cerevisiae are composed of nine (CoQ9) and six (CoQ6) units, respectively [[1]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0099038#pone.0099038-Kawamukai1).

**Comment by marcfeuermann** [comment]
Moved annotation to parent term: ubiquinon-6 biosynthetic process

**Comment by ValWood** [comment]
I was just about to correct  you ;)

**Comment by marcfeuermann** [comment]
Yes sorry, I've sent the message too quickly.
Copy/paste is dangerous sometimes ;-)
