### ISSUE TITLE
 IPR010233 not GO:0008425 | 2-polyprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5227]
* **InterPro ID / label**

hi, 
GO:0008425 | 2-polyprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity

* **Example sequences with problematic annotation (ID + gene/protein name):**

I have

3,4-dihydroxy-5-polyprenylbenzoic acid O-methyltransferase activity
and
3-demethylubiquinol-n 3-O-methyltransferase activity

from Rhea and these appear to be correct for the 2 steps catalysed by coq3

* **Description of issue**

**Comment by ValWood** [comment]
I see 
GO:0008425 | 2-polyprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity == coq5 a different methyltransferase.

**Comment by blazaropinto** [comment]
Thank you very much for this Val. I removed this term and updated with both given by UniProt and Rhea to these enzymes. The changes will be visible in InterPro 100.0.

Best,

Beatriz
