### ISSUE TITLE
IPR046962 Autophagy-related protein 3

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5228]
* **InterPro ID / label**
IPR046962 Autophagy-related protein 3

* **Example sequences with problematic annotation (ID + gene/protein name):**
Human ATG3 and orthologs

* **Description of issue**
I think you can change the current [Atg8-family ligase activity (GO:0019776)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0019776) annotation to GO:0141046 Atg8-family conjugating enzyme activity

**Comment by sarach06** [comment]
Dear Val,
Thank you very much. Yes, I agree, I have updated the term in this entry, which will be visible in InterPro 100.0.
Best wishes,
Sara

**Comment by sjm41** [comment]
Thanks Sara!
From Steven (aka Val!)
