### ISSUE TITLE
Review annotations to GO:0140080 class III/IV DNA-(apurinic or apyrimidinic site) endonuclease activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5230]
Dear all, 

The proposal has been made to obsolete GO:0140080 class III/IV DNA-(apurinic or apyrimidinic site) endonuclease activity
see https://github.com/geneontology/go-ontology/issues/27071.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1RP_-GtuL4sdjctOw5w2UR1br80EZGNj0pOEdvu6IMM0/edit#gid=0

Impacted groups: 
FlyBase 1

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None.

Thanks.

**Comment by sjm41** [comment]
I've removed the FB annotation (though it will take a while for this change to show in AmiGO).
