### ISSUE TITLE
PTN002705826 (PTHR18861)

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-annotation#5231]
* **PTHR ID & PTN node:**
* PTHR18861
* PTN002705826

* **Sequences with problematic annotation (ID + gene/protein name):**
* spd-5 (WBGene00004955)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
* spd-5 has inherited some synapse-related BP, MF, and CC terms, but all evidence in C. elegans indicates that this protein is a scaffold protein for the pericentriolar material (see, for example, https://pubmed.ncbi.nlm.nih.gov/28575670/).
* Suggested GO terms to remove: GO:0007274, GO:0048167, GO:0048790, GO:0098882, GO:0048788	

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

Thanks and please let me know if you need any more information.

**Comment by marcfeuermann** [comment]
Annotated loss and gain of function fort he small spt5 node.
