### ISSUE TITLE
PTN001115588

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-annotation#5232]
* **PTHR ID & PTN node:**
PTN001115588
* **Sequences with problematic annotation (ID + gene/protein name):**
D. melanogaster 
Chs2 (Q9VNW7)
kkv (Q8IPN4)
* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
erroneous propagation

In D. melanogaster and likely in other insects, chitin (the product of chitin synthase) is find in the cuticle and peritrophic matrice and is not part of cell wall.
According to the GO definition, cell wall is mainly found in yeast and plants.
_The rigid or semi-rigid envelope lying outside the cell membrane of plant, fungal, most prokaryotic cells and some protozoan parasites, maintaining their shape and protecting them from osmotic lysis. In plants it is made of cellulose and, often, lignin; in fungi it is composed largely of polysaccharides; in bacteria it is composed of peptidoglycan; in protozoan parasites such as Giardia species, it's made of carbohydrates and proteins._

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
BPs were well annotated but I indeed had to corrects CCs,

**Comment by rozaru** [comment]
@marcfeuermann 
Could also the [cell septum](http://amigo.geneontology.org/amigo/term/GO%3A0030428) term be removed for D. melanogaster Chs2 (Q9VNW7) and kkv (Q8IPN4) and arthropods in general as this term described a structure that is likely found only in Bacteria and Fungi. 
I wasn't sure if this was included in the "had to corrects CCs" in your comment.
Thanks

**Comment by marcfeuermann** [comment]
This has of copurse also been corrected.
