### ISSUE TITLE
IPR027109 SWR1-complex protein 4/DNA methyltransferase 1-associated protein 1

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5235]
* **InterPro ID / label**
IPR027109 SWR1-complex protein 4/DNA methyltransferase 1-associated protein 1

* **Example sequences with problematic annotation (ID + gene/protein name):**
FLy DMAP1 (Q7K3D8)

* **Description of issue**
This entry is for a methylase/acetyltransferase-**associated** protein, so shouldn't be annotated with [histone acetyltransferase activity (GO:0004402)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004402).
Can you remove that?
Thanks.

**Comment by sarach06** [comment]
Hi Steven,
Thank you very much for this, I have removed the term from this entry. This will be visible in InterPro 100.0.

Cheers,
Sara
