### ISSUE TITLE
 GO:0015990	 electron transport coupled proton transport IBA with PTN000046094 , P0ABI8

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5237]
* **PTHR ID & PTN node:**

- | GO:0015990 | electron transport coupled proton transport | IBA with PTN000046094 , P0ABI8

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPMIT.01
(and other eukaryotic)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

it could be an erroneous annotation but it's E coli so I'm not sure 

but for higher eukaryotes the correct term is
mitochondrial electron transport, cytochrome c to oxygen (GO:0006123)

in fact, I wonder if we even need this term?
Only 16 EXP annotations  e. coli, complex Portal and SGD (1)

The SGD one looks like an annotation error :
https://www.yeastgenome.org/locus/S000004126
"Cth2 deficiency relieves Cth2-mediated post-transcriptional repression of nuclear-encoded components of the electron transport chain. "

 The only thing I would annotate to this ter is the proton transporting ATPase and that has
proton motive force-driven mitochondrial ATP synthesis (GO:0042776)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Updated.
