### ISSUE TITLE
PTN002690736  not regulation of splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5238]
* **PTHR ID & PTN node:**

GO:0048026 | positive regulation of mRNA splicing, via spliceosome | IBA with PTN002690736 , MGI:109580 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC31G5.01
human https://www.uniprot.org/uniprotkb/Q15427/entry

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Seems to be erroneous annotation MGI @LiNiMGI 
U2 snRNP-associated RNA-binding protein Sap49
is part_of splicing, not regulation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Corrected.

**Comment by LiNiMGI** [comment]
MGI corrected.
