### ISSUE TITLE
IPR049627 E3 ubiquitin-protein ligase complex SLX5-SLX8 subunit SLX8

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5239]
* **InterPro ID / label**
IPR049627 E3 ubiquitin-protein ligase complex SLX5-SLX8 subunit SLX8

* **Description of issue**
Entry says: 
This entry includes E3 ubiquitin-protein ligase complex SLX5-SLX8 subunit SLX8 from budding yeast, which mediates ubiquitination and subsequent desumoylation/degradation of sumoylated proteins and proteins containing SUMO-like domains

That is, SLX8 is part of an E3 ubiquitin-protein ligase, that transfers ubiquitin to sumoylated proteins.

But it's annotated with [SUMO-ubiquitin ligase activity (GO:0140082)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0140082), that has def:
Isoenergetic transfer of SUMO from one protein to an existing ubiquitin chain via the reaction X-ubiquitin + Y-ubiquitin = Y-ubiquitin-ubiquitin + X

I don't think SLX8 is a SUMO transferase.
It seems IPR049627 would be better annotated with 'ubiquitin protein ligase activity (GO:0061630)'

But I see @ValWood has also annotated S. pombe slx8 with 'SUMO-ubiquitin ligase activity' from PMID: 28552615 (and that's also the source for a PAINT annotation - [PTN002931943](https://www.pantree.org/node/annotationNode.jsp?id=PTN002931943). Again, I don't easily see the evidence for slx8 having a SUMO transferase activity from that paper, but maybe I'm missing it??

**Comment by ValWood** [comment]
I agree this isn't a 'SUMO-ubiquitin ligase activity' (I don't know what this is?).

The term was requested for PMID: 28552615
https://github.com/geneontology/go-ontology/issues/13992
maybe it should be obsoleted.

(I think it is a conflation  with SUMO-targeted ubiquitin ligase?)

**Comment by sjm41** [comment]
Hi @blazaropinto Just checking this one hasn't fell off your radar. Thanks.

**Comment by blazaropinto** [comment]
Thanks both,

[GO:0033768: SUMO-targeted ubiquitin ligase complex](https://www.ebi.ac.uk/QuickGO/term/GO:0033768) is a CC term, but I agree ubiquitin protein ligase activity (GO:0061630) is the MF that represent this group best. I updated this. The changes will be available in InterPro 101.0.

Best,
Beatriz
