### ISSUE TITLE
PTN000604564  nucleosomal DNA binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5242]
* **PTHR ID & PTN node:**

hta1 | GO:0031492 | nucleosomal DNA binding | IBA with PTN000604564 , O75367 , P0C0S5 , MGI:1349392 | GO_REF:0000033 
hta2 |   | IBA with P0C0S5 , MGI:1349392 , PTN000604564 , O75367

I'm blocking the term "nucleosome DNA binding"  

it's odd to annotate histones to this term,  the annotations don't really make any sense.....
histones bind to DNA  which contains nucleosomes (which histone is a part_of???)

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed
