### ISSUE TITLE
Review annotations to GO:0038181 bile acid receptor activity & GO:0038183 bile acid signaling pathway

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5246]
Dear all, 

The proposal has been made to obsolete
GO:0038181 bile acid receptor activity -> consider GO:0038186 bile acid nuclear receptor activity, GO:0038182 G protein-coupled bile acid receptor activity 
GO:0038183 bile acid signaling pathway -> consider GO:0038184 cell surface bile acid receptor signaling pathway, GO:0038185 intracellular bile acid receptor signaling pathway

see https://github.com/geneontology/go-ontology/issues/26958

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1vV-n8rJfAhZqWlNyz0bU34jx_m5Tk_GF3cabXgkD080/edit#gid=0

Impacted groups: 
UniProt 5
BHF-UCL 1
ParkinsonsUK-UCL 2
RGD 24

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
interpro2go	InterPro:IPR044114 Bile acid receptor, ligand binding domain > GO:bile acid signaling pathway ; GO:0038183
(maps to GO:0038185 intracellular bile acid receptor signaling pathway)

Thanks.

**Comment by slaulederkind** [comment]
RGD corrections are finished.

**Comment by pgaudet** [comment]
@RLovering Can you please change your annotation to  RGD:628831 | Nr1h4 | PMID:12718893\|RGD:1625198 ? 

Thanks, Pascale

**Comment by RLovering** [comment]
UCL annotations done - not sure what you wanted me to do wrt PMID:12718893 - these aren't UCLs

**Comment by pgaudet** [comment]
These are all done.
