### ISSUE TITLE
 iron incorporation into metallo-sulfur cluster | IBA with Q16595 , PTN000423706

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5248]
* **PTHR ID & PTN node:**

GO:0018283 | iron incorporation into metallo-sulfur cluster | IBA with Q16595 , PTN000423706

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1183.03c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

not a major issue, I just wanted to report that I was blocking it because it seems to be describing a MF (chaperone)
(but it has "do not annotate" anyways)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
We are currently cleaning the annotations to remove the pseudo-BP terms that describe a MF and check if we can replace them by more relevant annotations.. So I removed the PAINT annotation. They should anyway disappear if the terms are once obsoleted.
