### ISSUE TITLE
IPR002905 tRNA methyltransferase, Trm1

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5250]
* **InterPro ID / label**
IPR002905 tRNA methyltransferase, Trm1

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly Trm1 (Q9VK89)

* **Description of issue**
Entry says "Trm1 ([2.1.1.216](https://enzyme.expasy.org/EC/2.1.1.216)) dimethylates a single guanine residue at position 26 of a number of tRNAs using S-adenosyl-L-methionine as donor of the methyl groups"

But it has GO annotation to tRNA (guanine(10)-N2)-methyltransferase activity (GO:0160102) = EC:2.1.1.214

I think that needs changing to tRNA (guanine(26)-N2)-dimethyltransferase activity (GO:0160104) = EC:2.1.1.216
(which is what the 'child' IPR022923 entry already has.)

**Comment by sjm41** [comment]
> so I'm thinking the parent GO term GO:0016423 could be better for this parent entry

Sounds fine to me, thanks. Though if the parent GO term GO:0016423 is more appropriate for IPR002905, then the entry description should probably also be more generalised?

**Comment by blazaropinto** [comment]
Thanks, I updated both the GO term and the description, adding pmid:17198746. The changes will be available in InterPro 101.0.
Best,
Beatriz
