### ISSUE TITLE
IPR010233 Ubiquinone biosynthesis O-methyltransferase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5251]
* **InterPro ID / label**
IPR010233 Ubiquinone biosynthesis O-methyltransferase

* **Example sequences with problematic annotation (ID + gene/protein name):**
Fly Coq3, Human COQ3

* **Description of issue**
Entry says "This entry represents an O-methyltransferase, which is believed to act at two points in the ubiquinone biosynthetic pathway in bacteria (UbiG) and mitochondria (COQ3)"

It's annotated with 2-polyprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity (GO:0008425), which maps to EC:2.1.1.201.

But the EC associations on the entry are to 2.1.1.114, 2.1.1.222, 2.1.1.64.
Moreover, human COQ3 (Q9NZJ6) (as mentioned on the entry) is annotated with EC:2.1.1.114 and EC:2.1.1.64 in UniProt.

So I think GO:0008425 should be removed from the entry. I'm not sure if it can be replaced with one/more of the GO terms mapping to EC:2.1.1.114 or EC:2.1.1.64, or else a higher level term like 'methyltransferase activity'.

**Comment by ValWood** [comment]
yep, was done recently
https://github.com/geneontology/go-annotation/issues/5227

**Comment by sjm41** [comment]
Oops, sorry. I normally check if something has already been reported before making a ticket, but must have forgot this time. Thanks both!
