### ISSUE TITLE
Remove cytoplasm propagation from PTN000230217

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5253]
* **PTHR ID & PTN node:**
* SCAVENGER RECEPTOR CLASS B TYPE-1 SR-B1 (PTHR11923)  PTN000230217 

* **Sequences with problematic annotation (ID + gene/protein name):**
* e.g. FBgn0035091 CG3829 is localized to the plasma membrane (PMID:38713014)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
* Cytoplasm seems incorrect, DOI: 10.1016/j.ibmb.2007.11.003, doi: [10.1016/j.metabol.2014.03.011](https://doi.org/10.1016%2Fj.metabol.2014.03.011), doi: [10.1146/annurev-physiol-021317-121550](https://doi.org/10.1146%2Fannurev-physiol-021317-121550) describe this class as having two TM domains.
IPR002159 CD36 family are decribed as membrane

**Comment by marcfeuermann** [comment]
Almost all annotated proteins are located within intracellular organelle membranes (vesicles, lysosomes...), so membrane does not exclude cytoplasm. Cytoplasm is distinct from cytosol. However, I've removed direct annotation since it will be anyway associated by parentage for most of the members.
