### ISSUE TITLE
Should contributes_to be  included with PAINT annotations?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5254]
I thought is was, but it seems not:

<img width="1033" alt="Screenshot 2024-05-24 at 18 38 24" src="https://github.com/geneontology/go-annotation/assets/7359272/95b0e2c6-41a0-48a2-8e67-f9aaa46997ea">

CC @krchristie

**Comment by marcfeuermann** [comment]
After reviewing the annotations, they all seem to be annotated with contributes_to, which seems to me to be the rule in this case. In any case, with PAINT we can only use the primary annotations as they were made. We can neither add nor remove a tag such as contributes_to. Have I misunderstood something? 
If the question is whether to propagate contributes_to in PAINT, I'd say yes in this case.
Best regards,
Marc.

**Comment by ValWood** [comment]
I think contributes_to should propagate...I thought it did ? @pgaudet

**Comment by pgaudet** [comment]
The annotation that PAINT propagates depends on whether the original annotation had a contributes_to or not. 

If there are annotations with and without 'contributes_to', then the PAINT curator picks which to propagate. 

Where is the screenshot from ? In AmiGO I see contributes_to for all rpb10 RNA polymerase annotations: 

<img width="1079" alt="image" src="https://github.com/geneontology/go-annotation/assets/4782928/f2b45d5d-44b4-4b1b-b5f3-9da45a93ce6e">

but not on the pombase page: 
<img width="1171" alt="image" src="https://github.com/geneontology/go-annotation/assets/4782928/7edf8d54-0a6e-4a6d-831c-60c355d0f457">

Do you display this information? Looks like something may have gotten lost.

**Comment by ValWood** [comment]
May be a PomBase bug, tagging @kimrutherford

**Comment by kimrutherford** [comment]
We don't load qualifiers from the GOA GAF file at the moment, except for NOT.  Should we load all of these?:

 - colocalizes_with
 - contributes_to
 - enables
 - involved_in
 - is_active_in
 - located_in
 - part_of

**Comment by ValWood** [comment]
I'm confused,  I thought the only annotation qualifiers were 
colocalizes_with
contributes_to
NOT

We should load contributes to from PAINT 
We don't use colocalized_with (are there any external annotations that use it?)

**Comment by kimrutherford** [comment]
> I'm confused, I thought the only annotation qualifiers were

You're right: https://geneontology.org/docs/go-annotations/#annotation-qualifiers

It's probably something to do with GPAD/GPI:
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#allowed-gene-product-to-go-term-relations

> We should load contributes to from PAINT

It looks like all the contributes_to qualifiers come from PAINT.  I'll make sure they're loaded for tomorrow's update.

> We don't use colocalized_with (are there any external annotations that use it?)

There are 4 colocalizes_with annotations from http://snapshot.geneontology.org/annotations/pombase.gaf.gz:
```
PomBase SPCC736.14      dis1    colocalizes_with        GO:0035371      GO_REF:0000033  IBA     PANTHER:PTN000288762|UniProtKB:Q14008   C       TOG/XMAP215 microtubule plus end tracking polymerase Dis1              protein_coding_gene     taxon:4896      20170228        GO_Central
PomBase SPCC895.07      alp14   colocalizes_with        GO:0035371      GO_REF:0000033  IBA     PANTHER:PTN000288762|UniProtKB:Q14008   C       TOG/XMAP215 microtubule plus end tracking polymerase Alp14     mtc1    protein_coding_gene     taxon:4896      20170228        GO_Central
PomBase SPAC17C9.13c    cut8    colocalizes_with        GO:0031965      GO_REF:0000033  IBA     PANTHER:PTN008622754|FB:FBgn0036994     C       tethering factor for nuclear proteasome Cut8           protein_coding_gene     taxon:4896      20221209        GO_Central
PomBase SPAPJ760.02c    abp1    colocalizes_with        GO:0005884      GO_REF:0000033  IBA     PANTHER:PTN000850943|FB:FBgn0036372|RGD:70885|RGD:619839        C     cofilin/tropomyosin family, drebrin ortholog Abp1                protein_coding_gene     taxon:4896      20190524        GO_Central
```

**Comment by ValWood** [comment]
those are OK, I'm not sure they need cplicaizes_with but I can look at those later. 
We can close this on the GO tracker and move to PomBase.
