### ISSUE TITLE
GO:0048029 monosaccharide binding )  PTN000344216,

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5256]
* **PTHR ID & PTN node:**
<img width="1043" alt="Screenshot 2024-05-25 at 12 42 26" src="https://github.com/geneontology/go-annotation/assets/7359272/f861a571-a48c-4ab7-bbc9-1bb0ad2ee476">

* **Sequences with problematic annotation (ID + gene/protein name):**

pfk1

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

strictly pfk1 does not bind to monosaccharide, it binds  to F-6_P which is a monosaccharide derivative
(there is no monosaccharide derivative binding in GO)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This family has probably been annotated a while ago and there were many binding annotations that we are not using anymore. The annotation has been completely updated.
