### ISSUE TITLE
GO:0005986	 sucrose biosynthetic process IBA with PTN000168022 , locus:2078941 , locus:2031103

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5257]
* **PTHR ID & PTN node:**

GO:0005986 | sucrose biosynthetic process | IBA with PTN000168022 , locus:2078941 , locus:2031103

* **Sequences with problematic annotation (ID + gene/protein name):**

odd for fbp1?

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation removed.
