### ISSUE TITLE
Review annotations to GO:0106054 tRNA-uracil-34 sulfurtransferase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5259]
Dear all, 

The proposal has been made to obsolete GO:0106054 tRNA-uracil-34 sulfurtransferase activity
see https://github.com/geneontology/go-ontology/issues/27928

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1pJ9AH3gMP7pEqj0cuwXuc8w7CjeRD4xkIjtKh0Dz4S0/edit#gid=0

Impacted groups: 
PomBase 4

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None.

Thanks.

**Comment by raymond91125** [comment]
Annotations may be moved to GO:0103016 tRNA-uridine 2-sulfurtransferase activity (revised label).

**Comment by ValWood** [comment]
PomBase done
