### ISSUE TITLE
PTN000216787 not all  GO:0006099 | tricarboxylic acid cycle | 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5262]
* **PTHR ID & PTN node:**

GO:0006099 | tricarboxylic acid cycle | IBA with 70889 , 621881 , idh1 , idh2 , P51553 , P50213 , PTN000216787 , FBgn0038922 , 2863 , O43837

* **Sequences with problematic annotation (ID + gene/protein name):**

lys12 https://www.pombase.org/gene/SPAC31G5.04

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Corrected.
