### ISSUE TITLE
PTN000950416  CARBON CATABOLITE REPRESSOR PROTEIN 4 (PTHR12121)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5263]
* **PTHR ID & PTN node:**
PTN000950416  CARBON CATABOLITE REPRESSOR PROTEIN 4 (PTHR12121)
* **Sequences with problematic annotation (ID + gene/protein name):**
ANGEL2 (UniProtKB:Q5VTE6)
angel (FB:FBgn0016762/UniProtKB:Q24239)
do not have GO:0000175 3'-5'-RNA exonuclease activity

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

This particular family/node might be too broad (perhaps corresponds to endonuclease/exonuclease/phosphatase domain (PFAM: PF03372) this signiture)

The "angel" proteins e.g.  (PMID:36180430, PMID:32732418) are 3' RNA phosophatases (made NTRs https://github.com/geneontology/go-ontology/issues/28001 and https://github.com/geneontology/go-ontology/issues/28002)

**Comment by marcfeuermann** [comment]
Annotation has been removed. Will add the correct function once available.
