### ISSUE TITLE
IPR045114 not all poly(A)+ mRNA export from nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5264]
* **InterPro ID / label**

GO:0016973 | poly(A)+ mRNA export from nucleus | IEA with IPR045114

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.yeastgenome.org/locus/S000003844#go
https://www.pombase.org/gene/SPAC1B3.08

* **Description of issue**

I don't think we can map to poly A export, because CSN12 is "unknown" but likely to be splicing or elongation (which could cause export defects)

**Comment by blazaropinto** [comment]
Thanks Val,
I see this term is also assigned to both budding and fission yeast proteins by GO central, and this annotation is coming from the PANTHER database itself https://www.pantherdb.org/panther/family.do?clsAccession=PTHR12732. Do you think the parent term GO:0006406 would be ok? (PMID:12411502)
Best,
Beatriz

**Comment by ValWood** [comment]
I don't see the annotation here:
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=O13873&aspect=biological_process

or here:
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P47130&aspect=biological_process

so maybe e you are looking at the other family member?

**Comment by blazaropinto** [comment]
Oh sure, you are right, just looked at the ones that had the term (Q08231 and Q9Y820), indeed there is nothing speaking about mRNA export in those. Neither in several other SwissProt, looking more carefully (Q5FWP8, Q6C1L4, Q6BGR7...), so I'll remove the term and add [GO:0003690](https://www.ebi.ac.uk/QuickGO/term/GO:0003690) and [GO:0003723](https://www.ebi.ac.uk/QuickGO/term/GO:0003723). The changes will be available in InterPro 101.0.
Best,
Beatriz
