### ISSUE TITLE
Review annotations to GO:0097224 sperm connecting piece (with replacement)

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5269]
Dear all, 

The proposal has been made to obsolete GO:0097224 sperm connecting piece
see https://github.com/geneontology/go-ontology/issues/28003

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1DPf99uAxMhMDrX254b3YMvNigqhF0BPqx3g3jOurQ3w/edit#gid=0

Impacted groups: 
MGI 4
UniProt 14

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
InterPro:IPR042769 SPATA6 family > GO:sperm connecting piece ; GO:0097224

Thanks.

**Comment by Antonialock** [comment]
@raymond91125 Isgoing to happen automatically or do they need to be reviewed? I am not sure what the reason is to obsolete rather than merge?

**Comment by Antonialock** [comment]
looks like these were done automatically

**Comment by blazaropinto** [comment]
Good afternoon,
Thank you for tagging us. I replaced the term with [GO:0120212](https://www.ebi.ac.uk/QuickGO/term/GO:0120212). The changes will be available inn InterPro 101.0.
Best,
Beatriz

**Comment by suzialeksander** [comment]
This term was obsoleted
