### ISSUE TITLE
Review annotations to children of GO:0048384 retinoic acid receptor signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5271]
GO:0060498 retinoic acid receptor signaling pathway involved in lung bud formation
GO:0060824 retinoic acid receptor signaling pathway involved in neural plate anterior/posterior pattern formation
GO:0035576 retinoic acid receptor signaling pathway involved in pronephric field specification
GO:0034671 retinoic acid receptor signaling pathway involved in pronephros anterior/posterior pattern specification
GO:0090242 retinoic acid receptor signaling pathway involved in somitogenesis
GO:0021908 retinoic acid receptor signaling pathway involved in spinal cord anterior/posterior pattern formation
GO:0060895 retinoic acid receptor signaling pathway involved in spinal cord dorsal/ventral patterning

**Comment by pgaudet** [comment]
Only GO:0090242 retinoic acid receptor signaling pathway involved in somitogenesis has annotations

**Comment by pgaudet** [comment]
@LiNiMGI @sramachand 
Would you please review your annotations to GO:0090242 retinoic acid receptor signaling pathway involved in somitogenesis? 
2 MGI, 4 ZFIN 

https://docs.google.com/spreadsheets/d/1cAyyDB3cY85owfJpRv4rI5PN1Aqrwd3Msjq8NRMfxmU/edit#gid=0


It seems like annotations should be moved to either
GO:0048385 regulation of retinoic acid receptor signaling pathway
GO:0048387 negative regulation of retinoic acid receptor signaling pathway
GO:0048386 positive regulation of retinoic acid receptor signaling pathway

plus part_of  GO:0001756 somitogenesis

**Comment by LiNiMGI** [comment]
The two MGI annotations to GO:0090242 retinoic acid receptor signaling pathway involved in somitogenesis were generated through "folding" the annotation and extension by the reasoner.  So no changes need to be made in Noctua. Thanks!

**Comment by sramachand** [comment]
No changes need to be made for the ZFIN annotations as the extension part_of GO:0001756 somitogenesis has already been added
