### ISSUE TITLE
GO:0005886 | plasma membrane |  PTN001578037 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5276]
* **PTHR ID & PTN node:**

GO:0005886 | plasma membrane | IBA with S000000282 , CAL0000178111 , PTN001578037 , S000002462 , CAL0000191729 , Q4WNS8

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1223.12c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous transfer. Meu10 is only expressed in fission yeast meiosis II, and localizes to the spore  wall, not plasma membrane
I'm surprised that it is different for other yeast...

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
_S. cerevisae_ has multiple paralogs and some are spore-specific, so it might not be a safe propagation for  the family

**Comment by marcfeuermann** [comment]
There are indeed many paralogs, so I removed PAINT annotations.
