### ISSUE TITLE
Review annotations to children and regulation terms of (subtype) chitin metabolic process

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5277]
Dear all, 

The proposal has been made to obsolete
GO:0006037 cell wall chitin metabolic process
GO:0006034 cuticle chitin metabolic process
GO:0006035 cuticle chitin biosynthetic process
GO:0006036 cuticle chitin catabolic process
GO:0034217 ascospore wall chitin biosynthetic process
GO:0034218 ascospore wall chitin metabolic process
GO:0006038 cell wall chitin biosynthetic process
GO:0006039 cell wall chitin catabolic process
GO:0034221 fungal-type cell wall chitin biosynthetic process
GO:0034222 regulation of cell wall chitin metabolic process
GO:0034232 ascospore wall chitin catabolic process
GO:0034223 regulation of ascospore wall chitin biosynthetic process
GO:0034233 regulation of cell wall chitin catabolic process
GO:0034234 regulation of ascospore wall chitin catabolic process
GO:0032884 regulation of cell wall chitin biosynthetic process

see https://github.com/geneontology/go-ontology/issues/27960.

The obsoleted terms will be merged to respective parent terms.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1hywV4yvou3T8huLC8J60IzH8l8xHk2T-hQ8KzR81q5Q/edit?gid=0#gid=0

Impacted groups: 
FlyBase	9 (automatic transfer)
SGD	19 (automatic transfer)
AspGD	2 (automatic transfer)
CGD	15 
UniProt	8 (automatic transfer)
~PomBase	3~ DONE
ComplexPortal	1 

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by ValWood** [comment]
Note that for the automatic transfer, there is a loss of information because these genes will no longer be annotated to the old parent "ascospore wall biogenesis" etc

**Comment by pgaudet** [comment]
Right, adding an annotation to the proper BP would be very useful 

@rozaru 
@srengel 
@Antonialock

**Comment by rozaru** [comment]
I checked and updated the annotation for the FlyBase entries affected.
I wasn't sure where these two entities comes from in the spreadsheet:
FBgn0004610	NaDh
FBgn0004609	NaDg
They are not in FlyBase and they seem to correspond to:
FBgn0041630	Hexo1
FBgn0041629	Hexo2

**Comment by suzialeksander** [comment]
All terms were obsoleted and will be merged to parent terms automatically.
