### ISSUE TITLE
Review annotations to GO:0032450 maltose alpha-glucosidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5278]
Dear all, 

The proposal has been made to obsolete GO:0032450 maltose alpha-glucosidase activity 
see https://github.com/geneontology/go-ontology/issues/28110

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1FULCr1hvgQG0NwxvD0_MKn7Tn5_l4HeD0yl9SSzzfyQ/edit?gid=0#gid=0

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by jlewsmith** [comment]
Hi Pascale,

There doesn't appear to be anything in the spreadsheet - what am I missing?

Jodi
________________________________

**Comment by pgaudet** [comment]
Sorry @jlewsmith - I had forgotten to link the spreadsheet. Here it is: https://docs.google.com/spreadsheets/d/1FULCr1hvgQG0NwxvD0_MKn7Tn5_l4HeD0yl9SSzzfyQ/edit?gid=0#gid=0

Pascale

**Comment by jlewsmith** [comment]
Thanks Pascale!
________________________________

**Comment by srengel** [comment]
SGD done.

**Comment by pgaudet** [comment]
Terms were obsoleted. Remaining annotations will appear in reports.
