### ISSUE TITLE
Review annotations to GO:0036531 glutathione deglycation

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5279]
Dear all, 

The proposal has been made to obsolete GO:0036531 glutathione deglycation
see https://github.com/geneontology/go-ontology/issues/28116

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1ZMkJTkcWSJjpReOF66DKfbX5l93LLvwWL7IxVoQWu_g/edit?gid=0#gid=0

Impacted groups: 
ParkinsonsUK-UCL 1

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
none

Thanks.

**Comment by suzialeksander** [comment]
This term was obsoleted
