### ISSUE TITLE
Review annotations to GO:0051065 CTP reductase activity 

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5280]
Dear all, 

The proposal has been made to obsolete GO:0051065 CTP reductase activity 
see https://github.com/geneontology/go-ontology/issues/28055

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1SP5n7COOtdPjCJWorPSAO8WfFTdWUPcT7EGmqttYWQo/edit?gid=0#gid=0

Impacted groups: 
EcoCyc 1

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

Thanks.

**Comment by amandamackie** [comment]
Reviewed and changed in EcoCyc
