### ISSUE TITLE
Review annotations to children of GO:0016906 sterol 3-beta-glucosyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5281]
Dear all, 

The proposal has been made to obsolete

GO:0051507 beta-sitosterol UDP-glucosyltransferase activity
GO:0051506 ergosterol UDP-glucosyltransferase activity
GO:0051508 stigmasterol UDP-glucosyltransferase activity
GO:0051509 tomatidine UDP-glucosyltransferase activity

since these represent specific substrates of GO:0016906 sterol 3-beta-glucosyltransferase activity, see https://github.com/geneontology/go-ontology/issues/25771

These terms will be replaced by the parent GO:0016906 sterol 3-beta-glucosyltransferase activity.

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1EsfAMFq4u1Vkk3mYtFiRnqPMy77wHTp1cxtzzbHmORM/edit?gid=0#gid=0

dictyBase : 4
TAIR: 1

**Comment by suzialeksander** [comment]
These terms were obsoleted, no further action required.
