### ISSUE TITLE
Review annotations to GO:0102202 soladodine glucosyltransferase activity, GO:0102203 brassicasterol glucosyltransferase activity, GO:0102205 cholesterol alpha-glucosyltransferase activityand 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5282]
GO:0102203 brassicasterol glucosyltransferase activity
GO:0102205 cholesterol alpha-glucosyltransferase activity
GO:0102202 soladodine glucosyltransferase activity

**Comment by pgaudet** [comment]
share same EC, see https://github.com/geneontology/go-ontology/issues/25771

**Comment by pgaudet** [comment]
Single dicty annotation: 
dictyBase | dictyBase:DDB_G0288655 | ugt52 | PMID:10224056

Will be replaced by GO:0016906 sterol 3-beta-glucosyltransferase activity

**Comment by suzialeksander** [comment]
These terms have all been obsoleted
