### ISSUE TITLE
Review annotations to GO:0043719 2-octaprenyl-3-methyl-6-methoxy-1,4-benzoquinol hydroxylase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5284]
Dear all, 

The proposal has been made to obsolete GO:0043719 2-octaprenyl-3-methyl-6-methoxy-1,4-benzoquinol hydroxylase activity
see https://github.com/geneontology/go-ontology/issues/28053

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1DEPs9j_UqB4I5DQ1L5k0w4az3I79Q8XHQeeTX0cS7z4/edit?gid=0#gid=0

Impacted groups: 
TAIR 1

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
none

Thanks.

**Comment by suzialeksander** [comment]
This term has been obsoleted, only annotation was fixed.
