### ISSUE TITLE
 PTN001904567 not all capping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5285]
* **PTHR ID & PTN node:**

for3 |   | IBA with PTN001904567 , cdc12 , S000001421 , S000005215 | GO_REF:0000033
fus1 |   | IBA with cdc12 , PTN001904567 , S000001421 , S000005215 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

formins don't fit the definition of "actin capping" even though they bind to the ends of actin filaments.

"capping" is defined

The binding of a protein or protein complex to the end of an actin filament, thus preventing the addition, exchange or removal of further actin subunits. [[ISBN:071673706X](https://www.worldcat.org/search?q=bn%3A071673706X)]

while formins are functioning as "actin polymerases"

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

Not high priority as the "capping" terms will likely be obsoleted.
I just wanted to not as I will be filtering.

**Comment by marcfeuermann** [comment]
I've removed anyway the propagation of this term.
