### ISSUE TITLE
succinate dehydrogenase (ubiquinone) cytochrome b subunit not TCA cycle

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5288]
GO:0006099 | tricarboxylic acid cycle | ISO with CPX-565

https://www.pombase.org/gene/SPCC330.12c 
O74882

(possibly other species)

The SDHA and SDHB subunits are directly involved in the TCA cycle by catalyzing the conversion of succinate to fumarate. In contrast, SDHC (along with SDHD) is specifically involved in the electron transport aspect, helping transfer the electrons generated in the TCA cycle to the ETC.

**Comment by ValWood** [comment]
Also
https://www.pombase.org/gene/SPAC140.01 P21911

**Comment by ValWood** [comment]
>Also
https://www.pombase.org/gene/SPAC140.01 P21911

Actually I am not sure about this one, I'll look in more detail tomorrow

**Comment by ValWood** [comment]
OK!
Sdh1 (SDHA) is TCA and electron transport
Sdh2 (SDHB), sdh3 (SDHC) and sdh4 (SDHD)  are electron transport only

**Comment by deustp01** [comment]
In humans, all of SDHA, B, C, and D are components of the succinate dehydrogenase complex, which mediates the conversion of succinate to fumarate, a step in the TCA cycle, with transfer of electrons to bound Coenzyme Q which then passes the electrons on to the electron transport chain ([R-HSA-70994](https://reactome.org/PathwayBrowser/#/R-HSA-71403&SEL=R-HSA-70994&PATH=R-HSA-1430728,R-HSA-1428517)). See also [RHEA:40523](https://www.rhea-db.org/rhea/40523) and the Complex Portal entry [CPX-561](https://www.ebi.ac.uk/complexportal/complex/CPX-561) for the SDH complex.

As far as I can tell the point of all of this is that at this step the TCA cycle and the electron transport chain merge, so all the parts of the complex contribute to both processes.

**Comment by ValWood** [comment]
OK I will put them in the TCA model. I guess they are required for localization anyway although not directly involved in the conversion of succinate to fumarate.

https://pubmed.ncbi.nlm.nih.gov/19739941/
<img width="374" alt="Screenshot 2024-06-18 at 19 11 46" src="https://github.com/geneontology/go-annotation/assets/7359272/90d5afec-a224-4767-8afe-941dde6f1ec7">

I didn't put them all in TCA cycle previously although all are in 
"mitochondrial electron transport, succinate to ubiquinone (GO:0006121)"

I have asked an expert who would err on the side of keeping them in,  but she  is asking a carbon metabolism guru!
I will close this unless there is further feedback.

**Comment by ValWood** [comment]
My issue is that I don't know which MF to attach to these 3 subunits in their TCA cycle role in the model.

Would
[GO:0008177] succinate dehydrogenase (quinone) activity
part_of TCA cycle be correct ?

**Comment by deustp01** [comment]
> Would
> [GO:0008177] succinate dehydrogenase (quinone) activity
> part_of TCA cycle be correct ?

Or is this an argument for multiple parentage, so [GO:0008177] succinate dehydrogenase (quinone) activity is also part_of electron transport?

**Comment by ValWood** [comment]
I'm strugging how to complete this part of the model. It might be useful to discuss on a future annotation or Noctua call. At the moment I am waiting for dome annotations to work through to Noctua, then I will share the final version for input.
I'm surprised that I could not find an existing GO-CAM model for TCA cycle?

**Comment by pgaudet** [comment]
Hi @ValWood 

What did you use as a search keyword? I find 7 models search titles with 'TCA': 

http://noctua.geneontology.org/workbench/noctua-landing-page/?offset=0&limit=50&title=TCA&expand&debug

**Comment by ValWood** [comment]
I used the GO ID, but perhaps I had another filter on. I now see the mouse model:
http://noctua.geneontology.org/workbench/noctua-alliance-pathway-preview/?model_id=gomodel%3A633b013300000306

In this model David has modelled succinate dehydrogenase as a complex.
but I want to put the individual gene products in (I would really like to do both, i.e model as a complex but be able to 'uncollepse' to show the subunits. I haven't figured out a way to do this....
