### ISSUE TITLE
GO:0000030 | mannosyltransferase activity | IBA with PTN001997630 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5292]
* **PTHR ID & PTN node:**

GO:0000030 | mannosyltransferase activity | IBA with PTN001997630 , S000005102 | contributes_to | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC167.09 pga1

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Incorrect annotation.
pga1 is a subunit of
GO:0120097 | glycosylphosphatidylinositol-mannosyltransferase II complex

GPI18 appears to be the mannosyltransferase subunit
pga1 appears to be essential  regulatory subunit

@edwong57 

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by edwong57** [comment]
@ValWood Is there anything that I need to do?

**Comment by ValWood** [comment]
Hi Sorry yes, the annotation is to mannosyltransferase, but this is the regulatory subunit, not the catalytic subunit.
v

**Comment by marcfeuermann** [comment]
This one was annotated as contributes-to. Annotation remove. I close this one as discussion is redundant to 
https://github.com/geneontology/go-annotation/issues/5293
