### ISSUE TITLE
IPR044844 NOT farnesyltranstransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5294]
* **InterPro ID / label**

IPR044844

* **Example sequences with problematic annotation (ID + gene/protein name):**

erg9 https://www.pombase.org/gene/SPBC646.05c

* **Description of issue**

This is 

farnesyl-diphosphate farnesyltransferase activity
squalene synthase activity

but not
farnesyltranstransferase activity

which is
https://www.pombase.org/gene/SPBC36.06c

thanks
v

**Comment by blazaropinto** [comment]
Hi Val, 
Thank you very much for that. I updated the terms and also added [GO:0045338](https://www.ebi.ac.uk/QuickGO/term/GO:0045338). The changes will be available in InterPro 101.0.
Best, 
Beatriz
