### ISSUE TITLE
GO:0072659 | protein localization to plasma membrane |PTN000464299 |

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5295]
* **PTHR ID & PTN node:**

GO:0072659 | protein localization to plasma membrane | IBA with Q7Z7B1 , PTN000464299 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

gwt1/PIG-W (all species)
e.g
https://www.pombase.org/gene/SPAC144.10c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous source.
The GPI pathway  mutants  causes mislocalization of plasma me brane destined proteins, but this seems indirect.
None of the other (linear) pathway components are annotated to GO:0072659 | protein localization to plasma membrane

@Antonialock  do you think the annotation should be removed?

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation remove at the PAINT level.
