### ISSUE TITLE
GO:0006888 | endoplasmic reticulum to Golgi vesicle-mediated transport | IBA with S000001869 , PTN000398233

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5296]
* **PTHR ID & PTN node:**

GO:0006888 | endoplasmic reticulum to Golgi vesicle-mediated transport | IBA with S000001869 , PTN000398233

This is a phenotype from an early paper 1996   before the role in GPI biosynthesis was unravelled
It seems to be because this step  required for their efficient incorporation into [COPII transport vesicles](https://www.yeastgenome.org/go/30134) through association with cargo receptors
but  transport seems to be indirect. There is only a problem in the mutant because its  required upstream

The later 2004 paper showing the role in GPI metabolism says
The mutant cells showed a clear delay in the maturation of GPI-APs in the Golgi and accumulation of GPI-APs in the ER. Thus, the GPI inositol deacylation is important for efficient transport of GPI-APs from the ER to the Golgi.

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC824.02 bst1

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This is again a duplicated ticket that has been recently addressed.
https://github.com/geneontology/go-annotation/issues/5255
Please check before submitting new issues. 
Thanks,
Marc.

**Comment by ValWood** [comment]
Sorry, I usually search, I must have done something wrong here.
v
