### ISSUE TITLE
Review annotations to biotin-protein ligase activity terms

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5297]
Dear all, 

The proposal has been made to obsolete (with replacement)
GO:0018271 biotin-protein ligase activity
GO:0004078 biotin-[methylcrotonoyl-CoA-carboxylase] ligase activity
GO:0004079 biotin-[methylmalonyl-CoA-carboxytransferase] ligase activity
GO:0004080 biotin-[propionyl-CoA-carboxylase (ATP-hydrolyzing)] ligase activity
GO:0071734 biotin-[pyruvate-carboxylase] ligase activity 

see https://github.com/geneontology/go-ontology/issues/28107

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1Zc-A6DUSxBtNtAU-vjx14TvG-EHM3fPd4rzDqSGEJ2o/edit?gid=0#gid=0

Impacted groups: 
TAIR 2
RGD 1
UniProt 4
CGD 1
FlyBase 1
GO_Central 1
MGI 1
SGD 1

----

Thanks.

**Comment by jlewsmith** [comment]
CGD done
________________________________

**Comment by slaulederkind** [comment]
RGD finished

**Comment by suzialeksander** [comment]
All terms have been obsoleted.
