### ISSUE TITLE
Review annotations to  GO:0019516 lactate oxidation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5299]
Dear all, 

The proposal has been made to obsolete GO:0019516 lactate oxidation
see https://github.com/geneontology/go-ontology/issues/27096

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1i2WesPAaKjdbMnflTsjc1zh2dFR6a2Ti6jE2gP_ul2s/edit?gid=0#gid=0

Impacted groups: 
UniProt  1
MGI 1
EcoCyc 3

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 

GO:0019516 | unirule2go | UniRule:UR000079107 > GO:lactate oxidation ; GO:0019516
GO:0019516 | unirule2go | UniRule:UR000160008 > GO:lactate oxidation ; GO:0019516
GO:0019516 | unirule2go | UniRule:UR000635130 > GO:lactate oxidation ; GO:0019516
GO:0019516 | interpro2go | InterPro:IPR004452 4Fe-4S binding protein > GO:lactate oxidation ; GO:0019516
GO:0019516 | interpro2go | InterPro:IPR012256 D-lactate dehydrogenase > GO:lactate oxidation ; GO:0019516
GO:0019516 | hamap2go | HAMAP:MF_01559 > GO:lactate oxidation ; GO:0019516
GO:0019516 | hamap2go | HAMAP:MF_02092 > GO:lactate oxidation ; GO:0019516
GO:0019516 | hamap2go | HAMAP:MF_02103 > GO:lactate oxidation ; GO:0019516

Thanks.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by blazaropinto** [comment]
Thanks Val,
I replaced the term with GO:0006089 in both entries. The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by Antonialock** [comment]
uniprot done
