### ISSUE TITLE
Review annotations to GO:1901564 organonitrogen compound metabolic process; GO:1901566 organonitrogen compound biosynthetic process; GO:1901565 organonitrogen compound catabolic process; GO:0010243 response to organonitrogen compound; GO:0010243 cellular response to organonitrogen compound

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5300]
Dear all, 

The proposal has been made to obsolete 

GO:1901564 organonitrogen compound metabolic process
GO:1901566  organonitrogen compound biosynthetic process
GO:1901565 organonitrogen compound catabolic process
GO:0010243 response to organonitrogen compound
GO:0010243 cellular response to organonitrogen compound

see  https://github.com/geneontology/go-ontology/issues/27194

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1To7vaLVHu2oLD2BrwuGkRQvjLnv4Bqh18IX_VuDVLDE/edit?gid=0#gid=0

Impacted groups: 

AgBase 4
MGI 1
~TAIR 2~
DictyBase  1
~UniProt 2~

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
NONE

Thanks.

**Comment by pfey03** [comment]
This annotation is from Bob I told im in Slack to fix it

**Comment by Antonialock** [comment]
uniprot done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
All done
