### ISSUE TITLE
Review annotations to GO:0008785 alkyl hydroperoxide reductase activity and GO:0009389 dimethyl sulfoxide reductase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5302]
Dear all, 

The proposal has been made to obsolete GO:0008785 alkyl hydroperoxide reductase activity and GO:0009389 dimethyl sulfoxide reductase activity

See ~#28261~ 

https://github.com/geneontology/go-ontology/issues/28287

**Comment by pgaudet** [comment]
1) GO:0008785 alkyl hydroperoxide reductase activity maps to https://enzyme.expasy.org/EC/1.11.1.15, which has been transferred to 6 ECs
2) GO:0009389 dimethyl sulfoxide reductase activity

**Comment by suzialeksander** [comment]
@pgaudet is this ticket valid? The ontology ticket associated is closed
