### ISSUE TITLE
Review annotations to GO:0008997 ribonuclease R activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5304]
Dear all, 

The proposal has been made to obsolete GO:0008997 ribonuclease R activity

see https://github.com/geneontology/go-ontology/issues/28072

**Comment by pgaudet** [comment]
Single EcoCyc annotation to 
UniProtKB:P21499 | rnr


Suggest to re-annotate to exoribonuclease II activity ; GO:0008859

Thanks, Pascale

**Comment by amandamackie** [comment]
Removed and replaced by GO:0000175 (3'-5- RNA exonuclease activity). We annotate a separate E. coli enzyme (RNase II encoded by rnb) with GO:0008859.

Amanda
