### ISSUE TITLE
Review annotations to Children of GO:0019171 (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5307]
Dear all, 

The proposal has been made to obsolete : 

GO:0047450 (3R)-3-hydroxybutanoyl-[acyl-carrier-protein] hydratase activity >> 1 EXP
GO:0008693 (3R)-3-hydroxydecanoyl-[acyl-carrier-protein] dehydratase activity >> 2 EXP
GO:0008659 (3R)-3-hydroxymyristoyl-[acyl-carrier-protein] dehydratase activity >> 0 EXP
GO:0047451 (3R)-3-hydroxyoctanoyl-[acyl-carrier-protein] dehydratase activity >> 2 EXP
GO:0004317 (3R)-3-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity >> 0 EXP

see https://github.com/geneontology/go-ontology/issues/28163

4 EcoCyc
~1 TAIR~

See https://docs.google.com/spreadsheets/d/10ZZENRr4vHHlycpj9S3gBkq4Se-nzcIygM_5KHlT9Fk/edit?gid=0#gid=0

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by tberardini** [comment]
TAIR automatically updated to replacement term
