### ISSUE TITLE
Review annotations to GO:0046566 DOPA dioxygenase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5308]
Dear all, 

The proposal has been made to obsolete GO:0046566  DOPA dioxygenase activity because it represents the same reaction as GO:0050297 stizolobate synthase activity. Annotations should be moved to GO:0050297. 

Thanks, Pascale

**Comment by pgaudet** [comment]
- 1 EcoCyc:  UniProtKB:P24197 | ygiD | PMID:23666480
- 2 UniProt (will get automatically remapped)

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by pgaudet** [comment]
Thanks !
