### ISSUE TITLE
Review annotations to GO:0071633 dihydroceramidase activity GO:0070774 phytoceramidase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5313]
Dear all, 

The proposal has been made to obsolete
GO:0071633 dihydroceramidase activity
GO:0070774 phytoceramidase activity
and migrate annotations to GO:0017040 N-acylsphingosine amidohydrolase activity.
See https://github.com/geneontology/go-ontology/issues/28294.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1brAft9MShA9pRwuFTUHnsDepSXyev5wf04t6WmLXtGk/edit?gid=0#gid=0

Impacted groups:
11 UniProt (automatic)
3 SGD (automatic)
2 BHF-UCL (automatic)
1 TAIR

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
none

Thanks.

**Comment by suzialeksander** [comment]
These terms were obsoleted.
