### ISSUE TITLE
polyprenol catabolic process | IBA with Q9H8P0 , PTN000379006 MGI:1930252 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5314]
* **PTHR ID & PTN node:**

GO:0016095 | polyprenol catabolic process | IBA with Q9H8P0 , PTN000379006 , MGI:1930252 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC7D4.09c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation,
dfg10 is involved in the conversion of polyprenol (isopreniod) into dolichol.

It isn't catabolising the isoprenoid?

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
I agree. I've removed the propagation.
