### ISSUE TITLE
GO:0003865 | 3-oxo-5-alpha-steroid 4-dehydrogenase activity | IBA with Q9H8P0 , locus:2030235 , PTN000379006

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5315]
* **PTHR ID & PTN node:**

GO:0003865 | 3-oxo-5-alpha-steroid 4-dehydrogenase activity | IBA with Q9H8P0 , locus:2030235 , PTN000379006

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC7D4.09c

possibly most other annotated proteins

There seems to be only one paper supporting 
GO:0003865 | 3-oxo-5-alpha-steroid 4-dehydrogenase activity | 

This is likely not true in yeast. 
The conserved role for this protein is polyprenol reductase 
see the  Cell paper
https://linkinghub.elsevier.com/retrieve/pii/S0092867410006197
(part of dolichol synthesis pathway)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Same family as https://github.com/geneontology/go-annotation/issues/5314
But another issue. I've corrected this one too.
