### ISSUE TITLE
GO:0009063 | amino acid catabolic process | IBA with PTN000480319 , locus:2176446 , P38117

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5320]
* **PTHR ID & PTN node:**

GO:0009063 | amino acid catabolic process | IBA with PTN000480319 , locus:2176446 , P38117

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC1805.02c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

source, this is the source of the human annotation, I don't get amino acid catabolic process from this?
https://pubmed.ncbi.nlm.nih.gov/25416781/
" Because Lys200 and Lys203 are located adjacent to this ETFβ recognition loop, one may speculate that ETFβ methylation may differentially affect its interaction with the various mitochondrial dehydrogenases, thus providing a regulatory mechanism for modulating the metabolism of fatty acids, certain amino acids, and choline."
(The useful thing to capture from this paper is that Recombinant METTL20 Catalyzes Methylation of Lys200 and Lys203 in ETFβ in Vitro)

is the closest
I could not access the TAIR source

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
We have also the TAIR annotation from https://pubmed.ncbi.nlm.nih.gov/16923016/
It seems to be a phenotype, so I removed this annotation. We have some more relevant ones anyway.
