### ISSUE TITLE
Erroneous mappings to "respiratory chain complex I" PTN000042666 and PTN000207233

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5321]
* **PTHR ID & PTN node:**

GO:0045271	
respiratory chain complex I
IBA with PTN000042666 , MGI:1920150 , P04394 , P19404 , locus:2132387 , FBgn0030853

IBA with locus:2159522 , P25708 , P49821 , FBgn0031771 , MGI:107851 , PTN000207233

* **Sequences with problematic annotation (ID + gene/protein name):**

pombe SPBC18E5.10 and SPAC11E3.12 plus S. cerevisiae orthologs

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Erroneous propagation

(this one is odd; it's a new propagation, and it is to a term that is taxon restricted for Pombe and cerevisiae.)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This has been recently corrected during the PAN-GO taxon constraints "jamboree" (earlier this year). The updates should be available soon.
