### ISSUE TITLE
FBgn0040212 block propagation from PANTHER:PTN000285763

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5329]
* **PTHR ID & PTN node:**
* PANTHER:PTN000285763
* GLYCEROL-3-PHOSPHATE ACYLTRANSFERASE (PTHR12563)

* **Sequences with problematic annotation (ID + gene/protein name):**
FBgn0040212, Glyceronephosphate O-acyltransferase, Gnpat

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
This gene is most likely the ortholog Hsap\GNPAT over Hsap\GPAT2 so annotations from PANTHER:PTN002488810 are good, but from PANTHER:PTN000285763 are less likely.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Indeed, there is a clear ancient duplication making distinction between nodes PTNPTN002488810 and PTN000970957. I've corrected the annotation.
