### ISSUE TITLE
IGNORE Review annotations to GO:0003964 RNA-directed DNA polymerase activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5334]
Dear all, 

The proposal has been made to obsolete GO:0003964 RNA-directed DNA polymerase activity  & replace it by its parent 

GO:0003720 telomerase activity 
see  https://github.com/geneontology/go-ontology/issues/28394

Annotations and mappings are here: https://docs.google.com/spreadsheets/d/1gNyw7L9MoHdaNR5TrUSemkh730D9C0Ln_z-_8i1mGZg/edit?gid=0#gid=0

**Comment by pgaudet** [comment]
**Annotations:** 
BHF-UCL 4
CACAO   1
PomBase 1
SGD 2
UniProt 5

 will be replaced automatically

**Extensions:** 
all BHF: will be replaced automatically

**Comment by pgaudet** [comment]
Mappings that need editing: 

- [ ] unirule2go  UniRule:UR000584809 > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] reactome2go Reactome:R-HSA-164504 > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] reactome2go Reactome:R-HSA-164520 > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] hamap2go    HAMAP:MF_04073 > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] interpro2go InterPro:IPR000123 RNA-directed DNA polymerase (reverse transcriptase), msDNA > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] interpro2go InterPro:IPR010659 Reverse transcriptase connection > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] interpro2go InterPro:IPR010661 Reverse transcriptase thumb > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] interpro2go InterPro:IPR021891 Telomerase ribonucleoprotein complex - RNA-binding domain > GO:RNA-directed DNA polymerase activity ; GO:0003964
- [ ] uniprotkb_kw2go UniProtKB-KW:KW-0695 RNA-directed DNA polymerase > GO:RNA-directed DNA polymerase activity ; GO:0003964

**Comment by ValWood** [comment]
What about reverse trancriptases (for example viral, or as part of transposons? ( have used for transposons)

**Comment by ValWood** [comment]
But the term 
GO:0003964 RNA-directed DNA polymerase activity
was agnostic for primer source?

In fact the term has 2 synonyms

RNA-directed DNA polymerase, group II intron encoded | narrow
RNA-directed DNA polymerase, transposon encoded | narrow

**Comment by deustp01** [comment]
Indeed. Should be GO:0003964 RNA-directed DNA polymerase activity be retired, or should terms like telomerase activity (and others that differ by the RNA template used in the activity) be made children of it?
For aspects of DNA synthesis enabled by viral reverse transcriptase, I don't see how to avoid use of GO:0003964 RNA-directed DNA polymerase activity. GO:0003964 is an is_a child of  GO:0034061 DNA polymerase activity - there are no terms of intermediate granularity. Do we indeed want to lump everything that uses any sort of RNA template into one term?

**Comment by pgaudet** [comment]
Apologies - this was NOT the right term. The term to be obsoleted is 
GO:0003721 telomerase RNA reverse transcriptase activity

I will open a new ticket.
