### ISSUE TITLE
PTN000567445  not all splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5335]
* **PTHR ID & PTN node:**

[PTN000567445](http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000567445)

* **Sequences with problematic annotation (ID + gene/protein name):**

Pombe Mrd1 https://www.pombase.org/gene/SPBP22H7.02c 
human RBM19 https://www.uniprot.org/uniprotkb/Q9Y4C8/entry 
cerevisiae https://www.yeastgenome.org/locus/S000006316
(these  are rRNA processing)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**propagation I think. This Panther family 

conflates multiple RNA binding domain proteins which look very similar.
For example,  splicing is correct for huamnSRSF10 https://www.uniprot.org/uniprotkb/O75494/entry

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
reviewed
