### ISSUE TITLE
Review annotations to GO:0003721 telomerase RNA reverse transcriptase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5337]
Dear all, 

The proposal has been made to obsolete **GO:0003721 telomerase RNA reverse transcriptase activity** 
see https://github.com/geneontology/go-ontology/issues/28394

Annotations will be automatically replaced by its parent **GO:0003720 telomerase activity**
Annotations are here: 
https://docs.google.com/spreadsheets/d/1m3u_je5vlcJ6zbv_WYDvctjvdmV77h4m2SJx0hi7rV0/edit?gid=0#gid=0

BHF-UCL	14
CGD	1
ComplexPortal	1
GeneDB	1
PomBase	3
RGD	1
SGD	1
UniProt	9

**Comment by pgaudet** [comment]
@sarach06 @blazaropinto @tony787 

Can you also update the InterPro:IPR003545 mapping to  GO:0003720 telomerase activity? 
(maybe you can also add a BP, for eg [telomere maintenance](http://purl.obolibrary.org/obo/GO_0000723)) 

Thanks, Pascale

**Comment by tony787** [comment]
Dear Pascale,
I have updated the term. I have also added GO:0000723 as BP. Changes will be visible in the InterPro release 102.0.
Best wishes,
Toni

**Comment by pgaudet** [comment]
Term is obsoleted - annotations will be in error reports.
