### ISSUE TITLE
Review annotations to GO:0036137 kynurenine aminotransferase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5339]
Dear all, 

The proposal has been made to obsolete GO TERM ID: GO:0036137 kynurenine aminotransferase activity
see https://github.com/geneontology/go-ontology/issues/28461.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1GhS1Mp_xZNMKYE000K70BxX5PukmJSvItJ9nItd-780/edit?gid=0#gid=0

Impacted groups: 
SGD 1
UniProt 3

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
none

Thanks.

**Comment by Antonialock** [comment]
Uniprot done

**Comment by srengel** [comment]
SGD done.
