### ISSUE TITLE
Review annotations to   GO:1903562  microtubule bundle formation involved in mitotic spindle midzone assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5346]
Dear all, 

The proposal has been made to obsolete  GO:1903562  microtubule bundle formation involved in mitotic spindle midzone assembly

see  https://github.com/geneontology/go-ontology/issues/24046

Impacted groups: 
PomBase 2 (done)
WB 1 (done)
FlyBase  4 @hattrill, these all appear to be the same annotation in QuickGO; there is only a single annotation in AmiGO.
UniProt 2 @Antonialock 
ComplexPortal  3 @sandraorchard 

Thanks.

**Comment by ValWood** [comment]
Weirdly, the script gives me only 2 annotations but QuickGO has 12
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:1903562&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

check this has not been actioned in another ticket

**Comment by pgaudet** [comment]
Yeah sometimes I wonder if AmiGO has everything, but I haven't been able to find a way to troubleshoot this systematically. 

In this case it does look like AmiGO is missing some annotations. 

Can you make sure that the pombase annotations that we see in QuickGO are in the Pombase GAF file ? We should open a ticket in go-site to ask @kltm

**Comment by ValWood** [comment]
The PomBAse annotations are already removed.
The Fly  and worm annotation is reported (there are 4  identical Fly annotations in QuickGO).

The missing annotations are Uniprot

UniProtKB:P17119 | KAR3 | involved_in | GO:1903562    microtubule bundle formation involved in mitotic spindle midzone assembly | ECO:0000314   IDA | PMID:25313961 |   | 559292 Saccharomyces cerevisiae (strain ATCC 204508 / S288c) | UniProt |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB:Q01649 | CIK1 | involved_in | GO:1903562    microtubule bundle formation involved in mitotic spindle midzone assembly | ECO:0000315   IMP | PMID:25313961 |   | 559292 Saccharomyces cerevisiae (strain ATCC 204508 / S288c) | UniProt

I checked QuickGO and Protein2GO and was unable to see any 'date added', so I'm not sure whether they should be in the GO database are not.
The Complex Portal annotations are also absent which aligns with missing data from EBI.

**Comment by vanaukenk** [comment]
I've updated the C. elegans annotation.

**Comment by ValWood** [comment]
I'll use QuickGO as the  reference here but I  won't make a spreadsheet (there  are not many annotations)

**Comment by kltm** [comment]
@pgaudet AmiGO should have pretty much exactly what is in the final local qc'ed GAFs, as supplied by the pipeline and listed in the build here https://github.com/geneontology/pipeline/blob/snapshot-post-fail/Jenkinsfile#L107-L131 .

**Comment by vanaukenk** [comment]
I'll check about the C. elegans annotations from ComplexPortal.  I know we can't pass the protein-containing complex annotations through WB, but we should be able to get the gene-centric annotations from ComplexPortal.

**Comment by hattrill** [comment]
FB done
