### ISSUE TITLE
Remove snapshot.geneontology.org path from script (accident) and repo

### ISSUE THREAD

**Issue by kltm** [geneontology/go-annotation#5348]
Currently, there is the very odd top-level directory in this repo:

snapshot.geneontology.org

This was accidentally added as part of a workflow adjustment a few months ago when adding a mappings report.

To close this, two steps:

- [x] prevent further additions/changes to this path in the workflow
- [x] manually remove it from the repo

**Comment by kltm** [comment]
Tagging @pgaudet

**Comment by kltm** [comment]
I believe I got the first part done.

**Comment by kltm** [comment]
(A little surprised, but) it looks like the script itself managed to clean and self-commit, removing the problematic directory.

@pgaudet If things are looking okay at your end, please close.

**Comment by pgaudet** [comment]
Great !
