### ISSUE TITLE
Review annotations to GO:0042652 mitochondrial respiratory chain complex I, peripheral segment

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5352]
Dear all, 

The proposal has been made to obsolete GO:0042652 mitochondrial respiratory chain complex I, peripheral segment
see https://github.com/geneontology/go-ontology/issues/27253#issuecomment-2230151385

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1Z__c_BSSjvT56jzGMq98pXD_qsPH_4Pls8xsU7iJJ-8/edit?gid=0#gid=0

Impacted groups: 
AspGD 1

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by pgaudet** [comment]
Antonia fixed this in June.
