### ISSUE TITLE
IPR039698  not always GO:0003865 3-oxo-5-alpha-steroid 4-dehydrogenase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5353]
* **InterPro ID / label**

https://www.ebi.ac.uk/interpro/entry/InterPro/IPR039698/
is mapping to 
GO:0003865	3-oxo-5-alpha-steroid 4-dehydrogenase activity 

but  it should be
polyprenol reductase activity (GO:0102389)
or a common parent?

* **Example sequences with problematic annotation (ID + gene/protein name):**

dfg10
https://www.pombase.org/gene/SPAC7D4.09c

* **Description of issue**

see also
https://github.com/geneontology/go-annotation/issues/5315

**Comment by blazaropinto** [comment]
Hi Val,
Thank you for that. I remove this term and added the common parent GO:0016627. The changes will be available in InterPro 102.0.
Best,
Beatriz
