### ISSUE TITLE
Review annotations to specific children of  alcohol dehydrogenase

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5358]
The proposal has been made to obsolete: 

- GO:0004023  alcohol dehydrogenase (NAD+) activity, metal ion-independent
- GO:0004025 alcohol dehydrogenase (NAD+) activity, iron-dependent
- GO:0004024 alcohol dehydrogenase (NAD+) activity, zinc-dependent
see https://github.com/geneontology/go-ontology/issues/28393

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/12gCLI9g0Y832JMzw1cUNZ15y5CYbBR0Vim1IPdnwObo/edit?gid=0#gid=0
- 1 EcoCyc
- 1 EcoWiki
- 1 MGI >> will be automatically replaced
- 5 UniProt >> will be automatically replaced
-  Reactome:R-HSA-71707 > GO:alcohol dehydrogenase (NAD+) activity, zinc-dependent ; GO:0004024


Please replace by the parent GO:0004022 alcohol dehydrogenase (NAD+) activity, since the specific co-factor is outside the scope of GO. Note that this is also outside the scope of EC and RHEA. 

 
Thanks, Pascale

**Comment by deustp01** [comment]
Reactome is fixed.

**Comment by amandamackie** [comment]
EcoCyc also fixed

**Comment by pgaudet** [comment]
Terms have been obsoleted. Remaining annotations will show up in reports.
