### ISSUE TITLE
PTN000487132 not all GO:0009089 | lysine biosynthetic process via diaminopimelate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5359]
* **PTHR ID & PTN node:**

PTN00048713

GO:0009089 | lysine biosynthetic process via diaminopimelate

hom3 |   | IBA with P00562 , PTN000487132 , P9WPX3 , P08660

* **Sequences with problematic annotation (ID + gene/protein name):**

hom3  https://www.pombase.org/gene/SPBC19F5.04  (PAINT)
hom2 https://www.pombase.org/gene/SPCC1827.06c (Unipathway only)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Propagation.
 S. cerevisiae and S. pombe don't operate the diaminopimelate for lysine biosynthesis (although apparently some fungi do)
I will add a taxon black for budding/fission yeast)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
PAINT has been reviewed.
