### ISSUE TITLE
GO:0000064	 L-ornithine transmembrane transporter activity IBA with PTN000641358 ,

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5361]
* **PTHR ID & PTN node:**

GO:0000064 | L-ornithine transmembrane transporter activity | IBA with S000005656 , PTN000641358 , Q9BXI2 , Q9Y619 , 1311488 , locus:2057671 | GO_REF:0000033 | 2

* **Sequences with problematic annotation (ID + gene/protein name):**

Minimally 
https://www.pombase.org/gene/SPAC4G9.20c (ymc1)
Ymc1 is glycine glutamate carrier.

The L-ornithine carrier is https://www.pombase.org/gene/SPBC29A3.11c
(this is the ortholog of S000005656 ORT1 / YOR130C used above)

thanks

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propagation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed.
