### ISSUE TITLE
GO:0004070 | aspartate carbamoyltransferase activity | IBA with ura1 , PTN000150227

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5364]
* **PTHR ID & PTN node:**

GO:0004070 | aspartate carbamoyltransferase activity | IBA with ura1 , S000003666 , FBgn0003189 , 1588606 , PTN000150227 , MGI:1916969

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC215.08c (arg4)

GO:0004088 | carbamoyl-phosphate synthase (glutamine-hydrolyzing) activity

(SGD ortholog  of arg4 - CPA2 does not have this annotation except via IBA

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

propgation

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Done.
