### ISSUE TITLE
Review annotations to cGMP-stimulated/cGMP-inhibited cyclic-nucleotide phosphodiesterase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5367]
Dear all, 

The proposal has been made to obsolete
GO:0004118 cGMP-stimulated cyclic-nucleotide phosphodiesterase activity
GO:0004119 cGMP-inhibited cyclic-nucleotide phosphodiesterase activity

see https://github.com/geneontology/go-ontology/issues/20117.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1nGg6DALnvUgfCnZ5kc6D2xvPZeEKXcES-mpU0JOlhHQ/edit?gid=0#gid=0

Impacted groups: 
[LIST GROUPS + NUMBER OF ANNOTATIONS + ADD ASSIGNEES] 

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
[LIST IDs + ADD ASSIGNEES] 

Thanks.

**Comment by pgaudet** [comment]
OK we will keep the terms.
