### ISSUE TITLE
GO:0005085	 guanyl-nucleotide exchange factor activity IBA with S000003065 , pim1 , P18754 , MGI:1913989 , PTN002338189

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5368]
* **PTHR ID & PTN node:**

GO:0005085 | guanyl-nucleotide exchange factor activity | IBA with S000003065 , pim1 , P18754 , MGI:1913989 , PTN002338189

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC3H7.06c
https://www.yeastgenome.org/locus/S000000484#go

We can't rule it out, but it is transferred  from S000003065 , pim1  which aren't orthoogs and all are part of the same WD repeat subfamily  (this one, pof 9 is an F-box/ubiquiting ligase subunit)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
propagation via
https://pantherdb.org/panther/family.do?clsAccession=PTHR45982

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed.
