### ISSUE TITLE
Annotation review for obsoletion GO:0035304 regulation of protein dephosphorylation, and its descendants

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5374]
Dear all, 

The proposal has been made to obsolete GO:0035304 regulation of protein dephosphorylation, and its descendants.
see https://github.com/geneontology/go-ontology/issues/28499.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1-lvQpg4Jgz0GF7GggnlUsNgJMALXmHwPuF-VNs4n2rY/edit?gid=0#gid=0

Impacted groups: 
ARUK-UCL	8 - done
BHF-UCL	17 - done
CACAO	2  - done
~CAFA	6~
ComplexPortal	1
FlyBase	6
GO_Central	3
GeneDB	2
HGNC-UCL	5 - done
MGI	15
ParkinsonsUK-UCL	14 - done
RGD	5
SGD	13
~TAIR	3~
~UniProt	49~
dictyBase	2

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by sandraorchard** [comment]
Complex Portal done

**Comment by hattrill** [comment]
FB done

**Comment by srengel** [comment]
SGD done.

**Comment by tberardini** [comment]
TAIR done

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by Antonialock** [comment]
CAFA and uniprot done

**Comment by pgaudet** [comment]
Terms have been obsoleted. Remaining annotations by GeneDB will appear in reports.
