### ISSUE TITLE
PTN008505894  alpha,alpha-trehalose-phosphate synthase (UDP-forming) activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5376]
* **PTHR ID & PTN node:**

GO:0003825 | alpha,alpha-trehalose-phosphate synthase (UDP-forming) activity | IBA with tps1 , FBgn0027560 , locus:2202990 , O59921 , PTN008505894 , CAL0000182821

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC19G12.15c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Propagation, tpp1 is the phosphatase. Mutant accumulates alpha,alpha-trehalose 6-phosphate

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed,
