### ISSUE TITLE
PTN002001455 cell wall indirect (appears to be an ER chaperone)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5377]
* **PTHR ID & PTN node:**

GO:0006078 | (1->6)-beta-D-glucan biosynthetic process | IBA with PTN002001455 , CAL0000189708 | GO_REF:0000033 | 4

GO:0009272 | fungal-type cell wall biogenesis | IBA with CAL0000189708 , PTN002001455 , S000001143

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC306.06c
(VAO1 is  related to BIG1, and the human counterpart is ATP6AP1)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Annotation, this seems to be an indirect phenotype.

i.e.  from abstract "  Residual beta-l,6-glucan levels in the big1Deltakre5Delta double mutant indicate that these gene products are unlikely to be beta-l,6-glucan synthase subunits, but rather may play some ancillary roles in beta-l,6-glucan synthase assembly or function, **or in modifying proteins for attachment of beta-l,6-glucan.**"

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
All BP annotations removed. many indirect primary annotations.
