### ISSUE TITLE
 microautophagy , PTN002244143

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5378]
* **PTHR ID & PTN node:**

GO:0016237 | microautophagy | IBA with S000003549 , PTN002244143
GO:0042144 | vacuole fusion, non-autophagic | IBA with PTN002244143 , S000003549

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1322.14c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I spoke with an expert on autophagy and it is not known if the role of VTC complex on autophage i direct or indirect.

Now that we know that its primary role is in the synthesis and import of polyphosphate, it would seem that these might not be the most appropriate annotations to transfer.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
The PAINT annotation has seemingly been corrected. Only the primary annotation of yeast still requires review.
@srengel, could someone at SGD have a look ? Thanks.

**Comment by srengel** [comment]
Hi @marcfeuermann i have removed the following annotation just now from Noctua.  

GO:0042144 | vacuole fusion, non-autophagic | S000003549
