### ISSUE TITLE
Review annotations to GO:1905182  positive regulation of urease activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5379]
Hi @tberardini 
Would you please change the 3 TAIR annotations to GO:1905182  positive regulation of urease activity ? 

See obsoletion notice here: https://github.com/geneontology/go-ontology/issues/28482
(not sure what happened that TAIR annotations were missed, looks like there were changes between the different releases)

- AGI_LocusCode	AT1G21840	UREF	acts_upstream_of_or_within	GO:1905182	TAIR:Publication:501717862|PMID:16244137	IMP		P	AT1G21840	AT1G21840|UREF|urease accessory protein F|T26F17.5	protein	taxon:3702	20240327	TAIR		TAIR:locus:2036997
- AGI_LocusCode	AT2G34470	UREG	acts_upstream_of_or_within	GO:1905182	TAIR:Publication:501717862|PMID:16244137	IMP		P	AT2G34470	AT2G34470|UREG|PSKF109|urease accessory protein G|T31E10.19|T31E10_19|UREASE ACCESSORY PROTEIN UREG	protein	taxon:3702	20240327	TAIR		TAIR:locus:2040894
- AGI_LocusCode	AT2G35035	URED	acts_upstream_of_or_within	GO:1905182	TAIR:Publication:501717862|PMID:16244137	IMP		P	AT2G35035	AT2G35035|URED|urease accessory protein D	protein	taxon:3702	20240327	TAIR		TAIR:locus:504956057

Ideally these could be annotated to GO:0030234 enzyme regulator activity or a child. Please create an ontology ticket if you need a more specific term. 

Thanks, Pascale

**Comment by tberardini** [comment]
I've removed all the BP annotations, there were MF annotations already in place for 'urease activator activity.'

**Comment by pgaudet** [comment]
Great! Thanks @tberardini
