### ISSUE TITLE
PTN000846179 GO:0004805 | trehalose-phosphatase activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5382]
* **PTHR ID & PTN node:**

reciprocal of https://github.com/geneontology/go-annotation/issues/5376

GO:0004805 | trehalose-phosphatase activity | IBA with S000004566 , PTN000846179 , S000004874 | contributes_to

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC328.03 tps1

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

annotation
The ortholog TPS1 is described as both
https://www.yeastgenome.org/locus/S000000330
but the description says Synthase subunit of trehalose-6-P synthase/phosphatase complex;
which aligns with pombe data

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Reviewed.
