### ISSUE TITLE
PTN001908418 | protein serine/threonine kinase activity

### ISSUE THREAD

**Issue by magrane** [geneontology/go-annotation#5384]
* **PTHR ID & PTN node:** PTN001908418

* **Sequences with problematic annotation (ID + gene/protein name):** UniProt entry Q13418 (human ILK) and orthologs

* **Type of Issue: Erroneous GO term:** Recent evidence shows that ILK does not have protein kinase activity and is likely to act as a scaffold protein. See PMID:20005845 & PMID:21524996 which show lack of kinase activity as well as PMID:30367047 which describes a non-catalytic role for ILK and a recent review, PMID:35089438.

**Comment by marcfeuermann** [comment]
Kinase families are huge and very complex families. Thanks for pointing this out. The annotation has been reviewed accordingly.

**Comment by marcfeuermann** [comment]
I think it would be worth to update Swiss-Prot annotation and primary GO annotation for human ILK (Q13418 ) and othologs.
Thanks
@lbreuza, ?

**Comment by magrane** [comment]
@lbreuza I have already updated Swiss-Prot annotation and GO annotations for ILK_HUMAN & orthologs
