### ISSUE TITLE
PTN001441502 pombe probably false positive for this family

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5385]
* **PTHR ID & PTN node:**

GO:0003682 | chromatin binding | IBA with PTN001441502 , Q96DN6 , Q9P267
GO:0005634 | nucleus | IBA with Q9P267 , Q96DN6 , PTN001441502

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC21C3.14c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I used this to annotate the human ortholog, but now I believe it to be a PANTEHR false positive.
This really looks like a cell surface protein (receptor or some cell surface molecule).
It has a clear signal poptide prediction and what appears to be aa glycosylated repeat egion.

 Its also quite different in length, and the AlphaFold structures appear to be very different. Could you take a look at the aligned region and see what you think.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This tree is indeed weird. Annotation reviewed and I sent a request to Panther to review the tree topology.
