### ISSUE TITLE
GO:0003941	 L-serine ammonia-lyase activity IBA with PTN002459384 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5386]
* **PTHR ID & PTN node:**

GO:0003941 | L-serine ammonia-lyase activity | IBA with PTN002459384 , S000000569 , P20132 , P0AGF6

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC1677.03c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

In fission yeast tda1 is  the threonine deaminase and sry1 is the L-serine ammonia-lyase

Fission yeast doesn't have  S000000569 (CHA1) which performs both threonine deaminase and sry1 is the L-serine ammonia-lyase it only has the ILV1 ortholog (tda1)

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation has been updated.
