### ISSUE TITLE
isoleucine biosynthetic process | IEA with IPR012080

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5387]
* **InterPro ID / label**

GO:0009097 | isoleucine biosynthetic process | IEA with IPR012080

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

Hi , this seems a bit indirect,

aspartate-semialdehyde dehydrogenase is involved in the comment pathways of   methionine and threonine biosynthesis.
isoleucine and other branched chain amino acids are synthesised from  threonine, but  this seems quite indirect (as does [lysine biosynthetic process via diaminopimelate (GO:0009089)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009089))

**Comment by blazaropinto** [comment]
Hi Val,

I agree, I removed the terms. The changes will be visible in the next InterPro release.

Best,
Beatriz
