### ISSUE TITLE
Incorrect UniProt KW mapping: IEA with KW-0457

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5388]
* **UniProt KeyWord (ID and label):**

GO:0009085 | lysine biosynthetic process | IEA with KW-0457

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1827.06c

GO:0004073 | aspartate-semialdehyde dehydrogenase activity

* **Description of issue**

aspartate-semialdehyde dehydrogenase is involved in the common pathways of methionine and threonine biosynthesis.
isoleucine and other branched-chain amino acids are synthesised from threonine, but this seems quite indirect

**Comment by Antonialock** [comment]
it looks fine?

![3-s2 0-B9780080885049002208-f00220-02-9780080885049](https://github.com/user-attachments/assets/52798ea1-2ee1-451a-bc93-138303e8168e)
Figure 2. The aspartate pathway. l-Lysine belongs to the aspartate pathway of amino acids and four different variants of the l-lysine biosynthetic pathway are indicated.

**Comment by Antonialock** [comment]
https://www.sciencedirect.com/topics/neuroscience/aspartate-semialdehyde-dehydrogenase

The first two steps of the [biosynthetic pathway](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/anabolism) of the aspartate pathway are phosphorylation of l-aspartate into l-aspartate-4-phosphate and further conversion into l-aspartate semialdehyde, catalyzed by [AK](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/aspartokinase) and aspartate semialdehyde [dehydrogenase](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/dehydrogenase) (Asd), respectively. l-Aspartate semialdehyde represents an important branch point in the aspartate pathway; either it is converted into l-homoserine by [HD](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/homoserine-dehydrogenase) for synthesis of l-threonine, l-methionine, and l-isolecucine, or it is converted into 2,3-dihydrodipicolinate by DapA and enters the l-lysine biosynthetic pathway (Figure 2).

**Comment by Antonialock** [comment]
that example is bacteria.....i'll have a look for fungi

**Comment by Antonialock** [comment]
ah

L-lysine is the only one known to have two distinct biosynthetic pathways: the diaminopimelate (DAP) pathway in plants, bacteria, and lower fungi, and the α-aminoadipate (AAA) pathway in euglenoids and higher fungi

The presence of the AAA pathway for lysine biosynthesis has been demonstrated in several yeasts and molds, including Saccharomyces cerevisiae (4,7), Yarrowia lipolytica (8), Schizosaccharomyces pombe (9), Rhodotorula
glutinis (10), Candida maltosa (11), Neurospora crassa (12), and Penicillium chrysogenum (13); human pathogenic fungi, such as Candida albicans (14), and Cryptococcus neoformans (15), and Aspergillus fumigatus (15); and plant pathogens, including Magnaporthe grisea .....

![image](https://github.com/user-attachments/assets/dc0d6ee6-0726-49f1-baf0-fea5a84043cb)

![image](https://github.com/user-attachments/assets/316d052b-c70f-4c86-b81b-8ed3d39e8e58)

**Comment by Antonialock** [comment]
I'll have a look at these to remove...

**Comment by ValWood** [comment]
I don't know what lower and higher fungi are either ;)

**Comment by Antonialock** [comment]
this has been fixed under the hood.
