### ISSUE TITLE
GO:0032865 | ERMES complex | IBA with S000003929 , PTN001412650

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5392]
* **PTHR ID & PTN node:**

GO:1990456 | mitochondrion-endoplasmic reticulum membrane tethering | IBA with S000003929 , PTN001412650 

GO:0015914 | phospholipid transport | IBA with S000003929 , PTN001412650

GO:0032865 | ERMES complex | IBA with S000003929 , PTN001412650 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC23G7.06c
possibly others

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Propagation
SPBC23G7.06c is nvj2 and the budding yeast ortholog is NVJ2 SGD:S000006295

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation has been updated.
