### ISSUE TITLE
GO:0016833 oxo-acid-lyase activity IEA with IPR014640

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5394]
* **InterPro ID / label**

GO:0016833 oxo-acid-lyase activity
IEA with IPR014640

* **Example sequences with problematic annotation (ID + gene/protein name):**

his4 https://www.pombase.org/gene/SPBC418.01c

<img width="1202" alt="report @ remove IEA" src="https://github.com/user-attachments/assets/18b36d27-d4e6-4beb-b6cb-fd5efe18d3ec">

* **Description of issue**

As far as I can see his4 has 2 activities
glutaminase activity
imidazoleglycerol-phosphate synthase activity

and 

GO:0016833 | oxo-acid-lyase activity

isn't a parent for either:
<img width="820" alt="Screenshot 2024-07-29 at 15 17 23" src="https://github.com/user-attachments/assets/7f592e70-2d5b-4fe7-9257-6e79cb81e364">

I think you can remove
GO:0016833   oxo-acid-lyase activity (but double check this in case i missed some other activity)

add
glutaminase activity (instead)

and remove 
[pentosyltransferase activity (GO:0016763)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016763)

(redundant with imidazoleglycerol-phosphate synthase activity)

**Comment by sarach06** [comment]
Hi Val,
Thank you for highlighting this. I agree, oxo-acid-lyase activity had to be removed, I added glutaminase activity and also removed pentosyltransferase activity. These changes will be visible in InterPro release 102.0.
Best wishes,
Sara
