### ISSUE TITLE
GO:0005739	 mitochondrion IBA with PTN000073792

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5395]
* **PTHR ID & PTN node:**

GO:0005739 | mitochondrion | IBA with S000000160 , PTN000073792

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC21.05c

P15258

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Propagation, I think, maybe from kelch repeats.

S000000160 isn't the SGD ortholog of SPBC21.05c (ral2),  MDS3 is

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This has been previously corrected following a ticket by flybase: https://github.com/geneontology/go-annotation/issues/5322

**Comment by ValWood** [comment]
oops, sorry, forgot to check!

**Comment by marcfeuermann** [comment]
No worries, it is okay. It was not exactly the same request ;-)
