### ISSUE TITLE
Review annotations to GO:1904923 regulation of autophagy of mitochondrion in response to mitochondrial depolarization plus +/-

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5403]
Dear all, 

The proposal has been made to obsolete 

GO:1904923 regulation of autophagy of mitochondrion in response to mitochondrial depolarization
GO:0098779 positive regulation of mitophagy in response to mitochondrial depolarization
GO:1904924 negative regulation of mitophagy in response to mitochondrial depolarization

see https://github.com/geneontology/go-ontology/issues/26202

Impacted groups: 
9 Parkinsons UK
1 CACAO
will be automatically migrated  to the "regulation of type 2 mitophagy" terms

There are also 5 extensions are these also automatically migrated?

Thanks.

**Comment by RLovering** [comment]
Hi Val
this term is already obsolete and UCL - it looks like this change has already been done so I am not sure what I need to do here. Please confirm what you would like me to do, 
Thanks
Ruth

**Comment by ValWood** [comment]
Hi Ruth!

ignore. I thought these were additional terms that I had missed.
Do you know if extensions are automatically  replaced?

**Comment by RLovering** [comment]
Hi Val
yes I think they were. I looked at the protein retrived with this search. https://www.ebi.ac.uk/QuickGO/annotations?extension=part_of(GO:1904924
And the AE field was updated on 6th August see screenshots

<img width="1128" alt="Screenshot 2024-08-07 at 11 25 29" src="https://github.com/user-attachments/assets/ff76b962-4892-4341-8868-2a9190aa381e">
<img width="984" alt="Screenshot 2024-08-07 at 11 25 11" src="https://github.com/user-attachments/assets/a8cfae84-f29e-4eb8-8b0a-3ddf19f94b71">
<img width="967" alt="Screenshot 2024-08-07 at 11 24 56" src="https://github.com/user-attachments/assets/231aa35e-5f74-416b-a11a-68ad6cf72ee6">
Hope these make sense to you
Ruth

**Comment by ValWood** [comment]
Thanks!
