### ISSUE TITLE
PTN000048763  DNA LIGASE 1/3 FAMILY MEMBER (PTHR45674)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5406]
* **PTHR ID & PTN node:**
PTN000048763 
DNA LIGASE 1/3 FAMILY MEMBER PTHR45674

* **Sequences with problematic annotation (ID + gene/protein name):**
For FlyBase: FBgn0262619, DNAlig1
mitochondrion GO:0005739
* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Could you block the mitochondrion term to FBgn0262619, DNAlig1 as this is just found in the nucleus.

I think that this branch be reviewed at for all the DNA ligases, as for the mammalian and fly DNA ligases, at least, only DNA ligase 3 is mitochondrial (and nuclear) and have a targeting sequence. The other DNA ligases, including DNA ligase 1 are nuclear. 

PMC10371073

**Comment by marcfeuermann** [comment]
Annotation has been updated.
