### ISSUE TITLE
CPX-1097  move to GO:0004126  cytidine deaminase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5412]
ComplexPortal:CPX-1097 | c2u-editosome_human | enables | GO:0004131    cytosine deaminase activity | ECO:0000314   IDA | PMID:11134005 |   | 9606 Homo sapiens | ComplexPortal

Hi @sandraorchard 
I think this one should be
GO:0004126  cytidine deaminase activity
Molecular Function
Definition ([GO:0004126 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0004126))
Catalysis of the reaction: cytidine + H+ + H2O = uridine + NH4 and deoxycytidine + H+ + H2O = deoxyuridine + NH4+.

rather than cytosine deaminase
Catalysis of the reaction: cytosine + H2O = uracil + NH3.

	1	RNA-specific cytidine deaminase (Apobec family):
	◦	These enzymes specifically deaminate cytidine residues in RNA molecules.
	◦	They are involved in RNA editing processes, such as the conversion of cytidine (C) to uridine (U) in RNA.
	◦	An example of this family is APOBEC1, which edits apolipoprotein B mRNA.
	2	Cytosine deaminase:
	◦	This enzyme deaminates cytosine to uracil.
	◦	It acts on free cytosine (not part of RNA or DNA) or cytosine nucleotides.
	◦	Cytosine deaminase is commonly found in certain bacteria and fungi and is involved in pyrimidine metabolism.

I will going to propose taxon restrictions   which might help a little but let me know if any other improvements can be made.
v

**Comment by sandraorchard** [comment]
Corrected - thank you
