### ISSUE TITLE
GO:0000030	 mannosyltransferase activity IEA with IPR042322	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5417]
* **InterPro ID / label**

IPR042322	

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1919.02,   pbn1 (but all)

* **Description of issue**

This is a mannosyltransferase complex subunit , but it isn't the mannosyltransferase. That's 
https://www.ebi.ac.uk/interpro/entry/InterPro/IPR007704/ (PIG-M)

pbn1 is the regulatory subunit

**Comment by blazaropinto** [comment]
Thank you Val,
I agree, I removed this term and updated the description make its role a bit clearer. The changes will be available in the next InterPro release.
Best,
Beatriz
