### ISSUE TITLE
IPR010482 not all peroxins

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5421]
* **InterPro ID / label**

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene_subset/interpro:IPR010482
mug65 https://www.pombase.org/gene/SPAC1296.04
and orthologs
human TECPR1  https://www.uniprot.org/uniprotkb/Q7Z6L1/entry
S. cerevisiae https://www.yeastgenome.org/locus/S000000848
aren't peroxins

The hit is a fragment of a WD  propellor so perhaps a common binding site for something.

* **Description of issue**

resulted in incorrect ARBA mappings

**Comment by blazaropinto** [comment]
Hi Val,

Thank you for pointing this out. I used a recent resolved structure (PMID:37409490) to rename and update the description of this domain (seems to be an insertion in the beta propellers). For now, I've named it 'TECPR1-like, DysF domain'. The changes will be available in the next InterPro release.
Best,
Beatriz

P.S. As this entry is based on a Pfam family, I'll try and improve the model when/if possible.
