### ISSUE TITLE
Review annotations to GO:0019857 5-methylcytosine metabolic process & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5423]
GO:0019857 5-methylcytosine metabolic process
GO:0046082 5-methylcytosine biosynthetic process
GO:0006211 5-methylcytosine catabolic process

Ontology ticket: https://github.com/geneontology/go-ontology/issues/28732

Annotations are here: https://docs.google.com/spreadsheets/d/1bXkUTTCOi2g9N79C-KaDjT7t-6h3tYhzeku2xHsfOCk/edit?gid=0#gid=0

**Comment by pgaudet** [comment]
1 UniProt - fixed
2 MGI 
1 UniRule
1 InterPro. 

Suggestions are here: https://docs.google.com/spreadsheets/d/1bXkUTTCOi2g9N79C-KaDjT7t-6h3tYhzeku2xHsfOCk/edit?gid=0#gid=0

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have replaced GO:0006211 with GO:0141167. This changes will be visible in InterPro 102.0.
Best,
Sara

**Comment by LiNiMGI** [comment]
MGI done.
