### ISSUE TITLE
GO:0004069 | L-aspartate:2-oxoglutarate aminotransferase activity | IEA with IPR016210

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5433]
* **InterPro ID / label**

GO:0004069 | L-aspartate:2-oxoglutarate aminotransferase activity | IEA with IPR016210

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC132.04c

* **Description of issue**

https://www.pombase.org/gene/SPCC132.04c
is GO:0004352 | glutamate dehydrogenase (NAD+) activity
(doesn't appear to be multifunctional)

**Comment by blazaropinto** [comment]
Hi Val,
Thank you for this. I agree, I removed the term. The change will be available in the next InterPro release.
Best,
Beatriz
