### ISSUE TITLE
Review annotations to GO:0019551 glutamate catabolic process to 2-oxoglutarate

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5435]
Dear all, 

The proposal has been made to obsolete GO:0019551 glutamate catabolic process to 2-oxoglutarate
see https://github.com/geneontology/go-ontology/issues/28800
* This is a single-step molecular function.

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1EaA7-1bqWRmVfNfpOHF6RqHdmUGunrZ2GJTsDdt3ihQ/edit?gid=0#gid=0

Impacted groups: 
CGD	1
MGI	2
~PomBase	1~ fixed
RGD	2

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
InterPro:IPR007780 NAD-glutamate dehydrogenase, bacteria > GO:glutamate catabolic process to 2-oxoglutarate ; GO:0019551
InterPro:IPR016210 NAD-dependent glutamate dehydrogenase, eukaryotes > GO:glutamate catabolic process to 2-oxoglutarate ; GO:0019551
InterPro:IPR028971 NAD-glutamate dehydrogenase, catalytic domain > GO:glutamate catabolic process to 2-oxoglutarate ; GO:0019551
UniRule:UR000380776 > GO:glutamate catabolic process to 2-oxoglutarate ; GO:0019551

Thanks.

**Comment by jlewsmith** [comment]
CGD done

**Comment by sarach06** [comment]
Hi Raymond,
Thank you very much. The InterPro entries you mentioned above are not mapped to GO:0019551, also I checked and we don't have any entries with this GO term. 

Best regards,
Sara

**Comment by LiNiMGI** [comment]
I didn't find the two annotations on the spreadsheet in MGI (Noctua).
So I will say MGI done. Thanks!

**Comment by pgaudet** [comment]
@LiNiMGI Are you sure? 

http://noctua.geneontology.org/workbench/noctua-landing-page/?offset=0&limit=50&term=GO:0006107&expand&debug

**Comment by LiNiMGI** [comment]
@pgaudet i don't see any MGI annotation to GO:0019551, the link you provide shows annotation to GO:0006107, did I misunderstand anything here? I thought this ticket is to review two MGI annotations to GO:0019551...Thanks.

**Comment by pgaudet** [comment]
@LiNiMGI OK never mind! Not sure what I was looking at!

**Comment by pgaudet** [comment]
The term has been obsoleted. Remaining annotations will appear in error reports.
