### ISSUE TITLE
Review annotations to GO:0016415 'octanoyltransferase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5436]
Dear all, 

The proposal has been made to obsolete GO:0016415 'octanoyltransferase activity'

Please re-annotate to GO:0033819 lipoyl(octanoyl) transferase activity if appropriate.

Thanks.

**Comment by pgaudet** [comment]
- [ ] EcoCyc: P60720 (lipB)
- [ ] UniProt: P60720 (lipM); fixed
- [ ] UniProt: P39648 (lipL); fixed

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by pgaudet** [comment]
Thanks!
