### ISSUE TITLE
PTN000186700/ PTN000186702 cytosolic forms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5437]
* **PTHR ID & PTN node:**
* PTN000186700 - PTN000186702
* ACONITASE/IRON-RESPONSIVE ELEMENT FAMILY MEMBER (PTHR11670) - ACONITASE/IRON-RESPONSIVE ELEMENT FAMILY MEMBER (PTHR11670)

* **Sequences with problematic annotation (ID + gene/protein name):**
FBgn0024958, Irp-1A (Iron regulatory protein 1A)
FBgn0024957, Irp-1B (Iron regulatory protein 1B)
should not have tricarboxylic acid cycle and mitochondrion annotations

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
* The aconitases should be split into the mitochondrial and cytosolic forms if possible. In D.mel there are 2 mitochondrial aconitases that function in the TCA cycle: FBgn0010100, mAcon1 and FBgn0037862, mAcon2
and 2 cytosolic aconitases that also function as iron-regulatory proteins
FBgn0024958	Iron regulatory protein 1A	Irp-1A
FBgn0024957	Iron regulatory protein 1B	Irp-1B

**Comment by marcfeuermann** [comment]
From the topology of the tree and the primary annotations, it is not obvious to distinguish between the 2 forms. I've deleted all annotations and tried to make a new evolutionary model (with loss and gain of function) that fits better to the data.
Irp-1A  and Irp-1B do not have the wrong annotations anymore.
