### ISSUE TITLE
Review annotations to GO:0004310 farnesyl-diphosphate farnesyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5438]
Dear all, 

The proposal has been made to obsolete  GO:0004310 farnesyl-diphosphate farnesyltransferase activity & replace by  GO:0051996 squalene synthase activity, see 
https://github.com/geneontology/go-ontology/issues/28819

Annotations are here: 
https://docs.google.com/spreadsheets/d/1T_P6vig1n_FDMbYKAhks6Oa0oB37QeXWbsvpr6v6gJk/edit?gid=0#gid=0

- 1 CGD
- 1 pombase
- 2 RGD
- 2 SGD
- 2 TAIR 
- 2 TIGR 

I think other than CGD annotations will be automatically replaced.

**Comment by jlewsmith** [comment]
CGD done

**Comment by jlewsmith** [comment]
Hi Pascale,

I just realized I forgot to attend the monthly annotation meeting - I was on vacation last week and still not back on top of the schedule.

Sorry about that!

Jodi
________________________________

**Comment by pgaudet** [comment]
No worries, have a look at the minutes and let Kimberly or I know if you have any questions.

**Comment by jlewsmith** [comment]
OK - thank you!
________________________________

**Comment by ValWood** [comment]
- Pombase does not have automatic replacement (we will probably implement, but I like to check),

**Comment by pgaudet** [comment]
Oh sorry about that !!! I'll make sure to notify you.
