### ISSUE TITLE
Review annotations to GO:0050048 L-leucine:2-oxoglutarate aminotransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5439]
Dear all, 

The proposal has been made to obsolete GO:0050048 L-leucine:2-oxoglutarate aminotransferase activity  & replace by GO:0052654 L-leucine transaminase activity, as these two terms represent the same reaction.

see 
https://github.com/geneontology/go-ontology/issues/28817

Annotations are here: https://docs.google.com/spreadsheets/d/1BtC6WbsTDmUr5p5XGBJzCskM1iOqj-BvirTRc4YQPsk/edit?gid=0#gid=0

1 EcoCyc
1 TAIR

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by tberardini** [comment]
TAIR done.
