### ISSUE TITLE
Review annotations to GO:0006507 GPI anchor release

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5441]
Dear all, 

The proposal has been made to obsolete GO:0006507 GPI anchor release
see https://github.com/geneontology/go-ontology/issues/28868
(Single-step process that should be an MF, e.g. GO:0004621 glycosylphosphatidylinositol phospholipase D activity)

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1tI7nGttTmoRhK7FGP5ebkTOaocJtpTccbAGrti151lc/edit?gid=0#gid=0

Impacted groups: 
FlyBase	1 DONE
GeneDB	2
MGI	1 DONE
UniProt	12
ZFIN	1 DONE

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None.

Thanks.

**Comment by doughowe** [comment]
ZFIN annotation updated.

**Comment by LiNiMGI** [comment]
MGI done.

**Comment by hattrill** [comment]
FB done

**Comment by pgaudet** [comment]
UniProt annotations fixed. 

Term has been obsoleted, remaining annotations will appear in error reports.
