### ISSUE TITLE
IPR012080 UniPathway:UPA00034 GO:0009089	lysine biosynthetic process via diaminopimelate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5442]
* **InterPro ID / label**

IPR012080

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P78780&aspect=biological_process
and S. cerevisiae ortholog

* **Description of issue**

is via
lysine biosynthetic process via aminoadipic acid

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. I added the term to this entry, which will be available in the next InterPro release (102.0).

Best wishes,
Sara
