### ISSUE TITLE
AQP6 contrary to classical aquaporins is not active at plasma membrane and it has very low water permeability

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-annotation#5446]
* **PTHR ID & PTN node:**
DR PANTHER=PTHR19139:SF113; AQUAPORIN-6; 1

* **Sequences with problematic annotation (ID + gene/protein name):**
UniProtKB:Q13520

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
I've removed annotations to water transport for AQP6. I kept the specific function of nitrate transport for AQP6 from PMID:1217700.
