### ISSUE TITLE
Block apoptosis annotations for Debcl and Buffy

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5449]
* **PTHR ID & PTN node:**
 PTN000135648 
BCL-2 RELATED (PTHR11256)
* **Sequences with problematic annotation (ID + gene/protein name):**
FBgn0040491 Buffy
FBgn0029131 Debcl
* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Block the apoptopic terms 
extrinsic apoptotic signaling pathway in absence of ligand
intrinsic apoptotic signaling pathway in response to DNA damage
involved_in release of cytochrome c from mitochondria
as these proteins are anti-apoptotic in flies 
(PMC165625)
CC and MF annotations are fine.

**Comment by marcfeuermann** [comment]
Done.
