### ISSUE TITLE
Block propagation of enzyme terms from PANTHER:PTN000126545 to Cht12

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5451]
* **PTHR ID & PTN node:**
PANTHER:PTN000126545
CHITINASE (PTHR11177)
* **Sequences with problematic annotation (ID + gene/protein name):**
* Cht12 FBgn0050293 lacks catalytic residues (PMID: 38184175)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
Block propagation of
chitinase activity
chitin catabolic process

**Comment by marcfeuermann** [comment]
WE already blocked many annotations due to the lack of catalytic residues, we missed this one. Corrected.
