### ISSUE TITLE
chloride channel, voltage gated (IPR001807)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5455]
* **InterPro ID / label**
chloride channel, voltage gated (IPR001807)

* **Example sequences with problematic annotation & Description of issue:**

The ClC family are split into two distinct mechanistic groups
From PMID:29845874:
In mammals, ClC-1, -2, -Ka/-Kb are plasma membrane Cl- channels, whereas ClC-3 through ClC-7 are 2Cl-/H+-exchangers in endolysosomal membranes. 

D.mel -> human orthologs - mech
FBgn0051116 ClC-a  - CLCN2  - voltage-gated Cl- channel
FBgn0033755 ClC-b  CLCN7 - Cl-/H+ antiporter
FBgn0036566 ClC-c  CLCN3  - Cl-/H+ antiporter

but all are getting voltage-gated chloride channel activity from IPR001807

IPR001807 has all the subfamilies, so this could be fixed by associating the children with either chloride:proton antiporter activity (GO:0062158) or voltage-gated chloride channel activity (GO:0005247) and renaming IPR001807 and changing the associated term to chloride transmembrane transporter activity (GO:0015108).

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have updated these entries and changed the terms on the parent and children, accordingly. These changes will be visible in InterPro 103.0.

Best regards,
Sara

**Comment by hattrill** [comment]
Thanks. I will close this.
