### ISSUE TITLE
PTN000123147

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-annotation#5458]
* **PTHR ID & PTN node:**
PTN000123147
* **Sequences with problematic annotation (ID + gene/protein name):**

This GO term protein O-linked fucosylation (GO:0036066)is added as part of the node annotation. Would it be possible to remove it as it is inappropriate based on the definition of the term.
I deleted the Drosophila annotation that was behind this annotation (IBD|PTN000123188(DROME\|FlyBase=FBgn0265351\|UniProtKB=Q9VHT4)

Thanks

**Comment by marcfeuermann** [comment]
PAINT annotation has been removed.
