### ISSUE TITLE
GO:0016701	 oxidoreductase activity, acting on single donors with incorporation of molecular oxygen IEA with IPR014436

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5462]
* **InterPro ID / label**

GO:0016701	 oxidoreductase activity, acting on single donors with incorporation of molecular oxygen IEA with IPR014436

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC1709.16c

* **Description of issue**

The description of those family is

Extradiol aromatic ring-opening dioxygenase, DODA-type

which implies it's a dioxygenase. 
dioxygenase activity (GO:0051213)
Catalysis of an oxidation-reduction (redox) reaction in **which both atoms of oxygen from one molecule of O2** are incorporated into the (reduced) product(s) of the reaction.

not 
GO:0016701	 oxidoreductase activity, **acting on single donors** with incorporation of molecular oxygen IEA with IPR014436

**Comment by sarach06** [comment]
Hi Val,
Thank you very much for this, I have replaced the term for dioxygenase activity. This will be visible in InterPro 103.0.
Best wishes,
Sara
