### ISSUE TITLE
Review annotations to GO:0072000 extracellular polysaccharide catabolic process involved in ascospore release from ascus & GO:0072316 alpha-glucan catabolic process involved in ascospore release from ascus

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5467]
Dear all, 

The proposal has been made to obsolete GO:0072000 extracellular polysaccharide catabolic process involved in ascospore release from ascus & GO:0072316 alpha-glucan catabolic process involved in ascospore release from ascus
see https://github.com/geneontology/go-ontology/issues/29019

Experimental annotations that need to be reviewed are here: https://docs.google.com/spreadsheets/d/12JUElBa_BZDOZhRxcozN3LI3plC33DFgG5BwLkMHD_w/edit?usp=sharing

Impacted Groups:

PomBase 3
----
No mappings

Thanks.

**Comment by ValWood** [comment]
fixed, thanks!
