### ISSUE TITLE
Review annotations to GO:2000777 positive regulation of proteasomal ubiquitin-dependent protein catabolic process involved in cellular response to hypoxia

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5468]
Dear all, 

The proposal has been made to obsolete GO:2000777 positive regulation of proteasomal ubiquitin-dependent protein catabolic process involved in cellular response to hypoxia

see https://github.com/geneontology/go-ontology/issues/29020

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1iLYvkojsCzw9a4REIPtBFiLlFNLYXB66idrMYAF4xUg/edit?usp=sharing

Impacted groups: 
UniProt 1

----

No mappings to review

Thanks.

**Comment by pgaudet** [comment]
Fixed annotation.
