### ISSUE TITLE
Review annotations to GO:0044149 cellular biosynthetic process, GO:0045226 extracellular polysaccharide biosynthetic process, GO:0031327 negative regulation of cellular biosynthetic process, GO:0031328 positive regulation of cellular biosynthetic process

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-annotation#5469]
Dear all, 

The proposal has been made to obsolete:
GO:0044149 cellular biosynthetic process
GO:0045226 extracellular polysaccharide biosynthetic process
GO:0031327 negative regulation of cellular biosynthetic process
GO:0031328 positive regulation of cellular biosynthetic process

see https://github.com/geneontology/go-ontology/issues/29022

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/17tUwi6TZfmk1THO_IZ5deayg_YGhCj_Bd9OHctvE0YE/edit?usp=sharing

Impacted groups: 
ARUK-UCL 5
BHF-UCL 1
MGI 3
PseudoCAP 42
EcoCyc 6
UniProt 21

----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
GO:0044249 | cellular biosynthetic process: 2 InterPro
GO:0045226 | extracellular polysaccharide biosynthetic process: 3 InterPro

Thanks.

**Comment by sarach06** [comment]
Hi,
Thank you very much. I have removed the terms from the InterPro entries. These changes will be visible in the next InterPro release (103.0).
Best,
Sara

**Comment by RLovering** [comment]
UCL done
