### ISSUE TITLE
IPR009014 Transketolase C-terminal/Pyruvate-ferredoxin oxidoreductase domain II

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5471]
* **InterPro ID / label**
IPR009014 Transketolase C-terminal/Pyruvate-ferredoxin oxidoreductase domain II

* **Example sequences with problematic annotation (ID + gene/protein name):**
Drosophila FBgn0036784 | CG5103

* **Description of issue**
This homologous superfamily entry is annotated with the high level GO term 'catalytic activity'. This isn't very informative, and flies (at least) have pseudo enzymes that match this motif.
Maybe remove the annotation?

**Comment by blazaropinto** [comment]
Thank you for this Steven. I agree, this term should be removed. The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by sjm41** [comment]
Thanks Beatriz!
