### ISSUE TITLE
Review annotations to GO:0051767 nitric-oxide synthase biosynthetic process and regulation

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5473]
Dear all, 

The proposal has been made to obsolete 
GO:0051767 nitric-oxide synthase biosynthetic proces
GO:0051771 negative regulation of nitric-oxide synthase biosynthetic process
GO:0051770 positive regulation of nitric-oxide synthase biosynthetic process
GO:0051769 regulation of nitric-oxide synthase biosynthetic process 

see https://github.com/geneontology/go-ontology/issues/28860.

"The annotations to the regulation of NO synthase biosynthesis are to signaling molecules, indicating that they should instead be annotated to the appropriate signaling pathway, + 'acts upstream of, positive effect' (positive) GO:0141149 regulation of nitric oxide-cGMP mediated signal transduction"

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/153K3OPgtJPq6Y7LuPMHq7kSt2HHUaIM0FOnmhb_IaZs/edit?gid=0#gid=0

Impacted groups: 
ARUK-UCL	8 - done
BHF-UCL	14 - done
RGD	15
UniProt	2

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None.

Thanks.

**Comment by slaulederkind** [comment]
Why does "nitric-oxide synthase biosynthetic process and regulation" get singled out for ontological treatment away from "translation".  It's not part of a group of proteins like the MHC.  There are also a handful of other individual proteins listed under "macromolecule biosynthetic process" (GO:0009059).  Why?

**Comment by deustp01** [comment]
> Why does "nitric-oxide synthase biosynthetic process and regulation" get singled out for ontological treatment

Because of its uniquely central role in mediating / regulating a number of other processes in mammals, maybe a larger range of multicellular animals, was the answer given in an earlier ontology discussion. And that answer was deemed insufficient to justify singling it out, hence the current obsoletion proposal.

**Comment by slaulederkind** [comment]
RGD finished.

**Comment by slaulederkind** [comment]
Thank you @deustp01.

**Comment by RLovering** [comment]
Note that NO has important for antibacterial etc properties and therefore its synthesis is not necessarily relevant to nitric oxide-cGMP mediated signal transduction and also NO is necessary for peptidyl-cysteine S-nitrosylation therefore regulation of NO levels is not just about regulation of nitric oxide-cGMP mediated signal transduction. Although I am sure that changing these annotations will encourage the annotation to these other processes which will be a good thing but unfortunately it is not simply a case of changing the existing annotations to the signaling term
Ruth

**Comment by Antonialock** [comment]
uniprot updated

**Comment by pgaudet** [comment]
Thanks @RLovering 

We should definitely look at these examples.

**Comment by RLovering** [comment]
> Thanks @RLovering
> 
> We should definitely look at these examples.

I have made sure that the term inflammatory response is included where appropriate and changed term to regulation of gene expression has input NOS1/2/3 as required if appropriate

**Comment by pgaudet** [comment]
Great !
