### ISSUE TITLE
PANTHER:PTN008535681 mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5480]
* **PTHR ID & PTN node:**

PANTHER:PTN008535681
is mapped to cytoplasm

* **Sequences with problematic annotation (ID + gene/protein name):**

All

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Is there any way this can be moved down  to mitochondria?

It already has an IBA to SAM complex which is mitochondrial

UniProtKB:Q9UUA5 | SPBC409.19c | part_of | GO:0001401    SAM complex | ECO:0000318   IBA | GO_REF:0000033

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Mitochondrial outer membane and mitochiondria are parents of SAM complex, so the annotation to mitochondria is automatic.
What I could do was to remove the annotation of cytoplasm to the root and restrict it to the non-mitochondrial branch of the family.
