### ISSUE TITLE
PTN000320077. not succinate metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5483]
* **PTHR ID & PTN node:**

GO:0006105 | succinate metabolic process | IBA with FBgn0038437 , PTN000320077

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBP23A10.03c (sdh7) but also human and S. cerevisiae orthologs

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

source, this is a LYR protein this one specific for  
GO:0034553 | mitochondrial respiratory chain complex II assembly
(succinate dehydrogenase)

@hattrill 

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by hattrill** [comment]
@ValWood removed annotation - will take a while to filter through as missed the window for the FB release.

**Comment by marcfeuermann** [comment]
Also removed at the PAINT level, so IBAs should disappear soon.
