### ISSUE TITLE
SPAC6G10.03c NOT PTN000862575 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5486]
* **PTHR ID & PTN node:**

GO:0035965 | cardiolipin acyl-chain remodeling | IBA with PTN000862575 , S000003342 | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC6G10.03c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Pombe doesn't remodel its cardiolipin, apparently.
I have added a NOT to the parent term  [cardiolipin metabolic process](https://www.pombase.org/term/GO:0032048) for this gene.

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
The annotation has been updated.
