### ISSUE TITLE
GO:0016485 | protein processing | IBA with PTN002503342

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5487]
* **PTHR ID & PTN node:**

GO:0016485 | protein processing | IBA with PTN002503342 , WBGene00013595

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC19B12.08 (atg8)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Looks like an annotation issue because this is autophagy, not maturation (protein processing is a subclass of maturation)
@vanaukenk  could you take a look?

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
This is atg4, not atg8, and its protease activity is required for proteolytic activation of atg8 since it cleaves the C-terminal amino acid of atg8 to reveal a C-terminal glycine
Looks to be protein maturation...

**Comment by ValWood** [comment]
got it. reinstating.

**Comment by ValWood** [comment]
I didn't think of this as processing because it's

Catalysis of the reaction: [protein]-C-terminal L-amino acid-glycyl-phosphatidylethanolamide + H2O = [protein]-C-terminal L-amino acid-glycine + a 1,2-diacyl-sn-glycero-3-phosphoethanolamine. An example of this reaction is the removal of ATG8 from membranes to which it is covalently linked to a phosphatidylethanolamid via its terminal glycine residue.

so seems to be removing a conjugation. Not sure where processing begins and ends here!

**Comment by marcfeuermann** [comment]
In fact atg4 has a dual function. In addition to catalyze the deconjugation of phosphatidylethanolamine, it also  removes the terminal amino acid to maturate atg8 (PMID:11100732, 11149920, 18701704, 18725539, ...)

**Comment by ValWood** [comment]
thanks!
