### ISSUE TITLE
IPR018119 Strictosidine synthase, conserved region

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5495]
* **InterPro ID / label**
IPR018119 Strictosidine synthase, conserved region

* **Example sequences with problematic annotation (ID + gene/protein name):**
Dmel FBgn0015737/Q9VB46
Dmel FBgn0041780/Q9VAQ9

* **Description of issue**
1. IPR018119 is currently associated with "[strictosidine synthase activity (GO:0016844)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016844)", but there are a couple of issues with this:
a. I don't think there's any evidence this entry represents the catalytic domain
b. This domain is found in animals, including two fly proteins (listed above) - the primary paper describing the animal members (PMID: 10777701) says that while they have sequence similarity to Alkaloid-Synthesizing Enzymes (e.g. Strictosidine synthase) of plants, they the animal proteins likely have a different function than Strictosidine synthase.
So I think GO:0016844 should be removed.

2. This entry is also annotated to the BP [biosynthetic process (GO:0009058)](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009058) - I'm not sure that's justified either, but it's probably too high level to be useful anyway. Also remove?

3. The EC entry in the description should be updated to [3.5.99.13](https://enzyme.expasy.org/EC/3.5.99.13)

**Comment by blazaropinto** [comment]
Hi Steven,
Thank you very much for this information. I updated the description of this entry, fixing EC number and talking about non-plant members as well. I also removed both GO terms. The changes will be available in the next InterPro release.
Best,
Beatriz

**Comment by sjm41** [comment]
excellent, thanks!
