### ISSUE TITLE
Incorrect UniProt KW mapping: UniProtKB:Q9BQ70 KW:KW-0238

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5500]
* **UniProt KeyWord (ID and label):**

please remove

UniProtKB:Q9BQ70 | TCF25 | enables | GO:0003677    DNA binding | ECO:0007322   IEA | GO_REF:0000043 | UniProtKB-KW:KW-0238 | 9606 Homo sapiens | UniProt

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.uniprot.org/uniprotkb/Q9BQ70/entry

* **Description of issue**

NO evidence this binds DNA unless tagged with GAL4 DNA binding domain

**Comment by Antonialock** [comment]
yes GAL4 fused, I will remove DNA binding and the function comment in uniprot relating to this.
