### ISSUE TITLE
Review annotations to GO:0046538 2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity and  GO:0046537 2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5503]
Dear all, 

The proposal has been made to obsolete GO:0046538 2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity and 
GO:0046537 2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity

and replace by parent [phosphoglycerate mutase activity](http://purl.obolibrary.org/obo/GO_0004619)

Group | Number of annotations
-- | --
EcoCyc | 3 DONE
GeneDB | 2
PomBase | 1 DONE
RGD | 1
TAIR | 2
UniProt | 8
WB | 2

Mappings 

- HAMAP:MF_01038 > GO:2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity ; GO:0046537
- HAMAP:MF_01039 > GO:2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity ; GO:0046538
- HAMAP:MF_01402 > GO:2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity ; GO:0046537
- InterPro:IPR004456 2,3-bisphosphoglycerate-independent phosphoglycerate mutase > GO:2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity ; GO:0046537
- InterPro:IPR023665 2,3-bisphosphoglycerate-independent phosphoglycerate mutase, prokaryotes > GO:2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity ; GO:0046537
- UniRule:UR000009933 > GO:2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity ; GO:0046537
- UniRule:UR000100531 > GO:2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity ; GO:0046537
- UniRule:UR000100537 > GO:2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity ; GO:0046538
-

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by sarach06** [comment]
Hi,
Thank you very much for this. I have replaced the term in IPR004456 with the parent term and removed it from its children IPR023665 ( we don't have to add it in both as it will be transferred from the parent InterPro entry). These changes will be available in InterPro 103.0.
Best regards,
Sara

**Comment by pgaudet** [comment]
Terms have been obsoleted. Errors will appear in reports.
