### ISSUE TITLE
PTN002461317 APOPTOSIS-INDUCING FACTOR 1 (PTHR43557) 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5505]
* **PTHR ID & PTN node:**
* PTN002461317 APOPTOSIS-INDUCING FACTOR 1 (PTHR43557)

* **Sequences with problematic annotation (ID + gene/protein name):**
* FBgn0031392 AIF

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
* mitochondrial respiratory chain complex assembly GO:0033108
* In flies this is part of the mitochondrial disulfide relay system rather than being an classical assmebly factor. From PMID: 37159021 it acts upstream of complex I assembly:

* I think that 'mitochondrial disulfide relay system GO:0160203' would be a better term to propagate, but could you at least block the proagation of GO:0033108 to the fly protein?
*
![Screenshot 2024-11-06 at 10 32 00](https://github.com/user-attachments/assets/ff5ff87f-dd02-4148-b2bc-2e32dc3c32b1)

**Comment by marcfeuermann** [comment]
Thanks,  makes sense and I made the proposed changes.
