### ISSUE TITLE
GO:0036503 | ERAD                     pathway | IBA with gpt1 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5511]
* **PTHR ID & PTN node:**

the supporting annotation on gpt1 is removed. Will this disappear automatically?
GO:0036503 | ERAD                     pathway | IBA with gpt1 , PTN000132051

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
It is not present anymore. Removing a primary annotation leads to the automatic removal of its propagation. But I always prefer checking if there is no other impact on the annotation.
