### ISSUE TITLE
 InterPro:IPR039205 &  InterPro:IPR007763 - remove mitochondrial respiratory chain complex I assembly

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5514]
Remove association between InterPro:IPR039205 NADH dehydrogenase [ubiquinone] 1 alpha subcomplex subunit 11
and IPR007763 NADH dehydrogenase [ubiquinone] 1 alpha subcomplex subunit 12

with mitochondrial respiratory chain complex I assembly GO:0032981

as they are not assembly factors, which are transiently associated and leave after assembly.

And add
respiratory chain complex I GO:0045271

For InterPro:IPR039205 I think, as it is just found in eukaryotes, should be ok to add mitochondrial-specific term:
mitochondrial electron transport, NADH to ubiquinone  GO:0006120 
mitochondrial inner membrane GO:0005743

**Comment by sarach06** [comment]
Hi Helen,
Many thanks for this. I have updated the GO terms in these entries and updated the descriptions, accordingly. This will be visible in InterPro 103.0.
Best regards,
Sara
