### ISSUE TITLE
IPR000104 Antifreeze protein, type I -> GO:0016172 antifreeze activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5520]
* InterPro ID / label
IPR000104

* **Example sequences with problematic annotation (ID + gene/protein name):**

* IPR000104
Antifreeze protein, type I may be connected to MF GO:0016172 antifreeze activity (reinstated a previously obsoleted term).

https://github.com/geneontology/go-ontology/issues/29149

**Comment by sarach06** [comment]
Hi!
Many thanks for this. For us the term still is obsolete so I can't add it right now to the entry. When it is available we can add it to the entry. May I ask you to keep us in the loop and let us know when is available back?

Thanks!
Sara

**Comment by pgaudet** [comment]
Hi @sarach06 

What is the InterPro process for loading GO terms? 
The term has been restored in the very last build - https://ontology-build.geneontology.org/go-basic.obo
but I am not sure it's in the InterPro system yet. 

Pascale

**Comment by sarach06** [comment]
Hi Pascale,
I can see that it has been recently released. Once UniProt updates the GO terms with the latest release (not sure when that is but I'm trying to get that information), and we do a UniProt update in InterPro, we then are available to get the latest GO terms additions/changes (can be in the coming months). Does this make sense? I will be back to you when I can get more details.
Best wishes,
Sara
