### ISSUE TITLE
CYTOCHROME C OXIDASE POLYPEPTIDE 7A (PTHR10510) Respirasome assembly

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5524]
* **PTHR ID & PTN node:**
PANTHER:PTN000828143
CYTOCHROME C OXIDASE POLYPEPTIDE 7A (PTHR10510)
* **Sequences with problematic annotation (ID + gene/protein name):**
COX7A FBgn0040529
COX7AL FBgn0037579
COX7AL2 FBgn0085201
* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
mitochondrial respirasome assembly GO:0097250

In humans and mice, COX7A2L/Cox7a2l is annotated with mitochondrial respirasome assembly GO:0097250. This point is debated somewhat in the literature (PMID: 27545886,PMID:30428348), but the major issue here is that COX7A2L is very similar to COX7A1. COX7A1 has not been characterised as a respirasome assmebly factor but is a component of complex IV. 

In flies, 
COX7A FBgn0040529
COX7AL FBgn0037579
COX7AL2 FBgn0085201
are all more similar to human COX7A1 than COX7A2L.
 
Therefore block the propagation of terms from PANTHER:PTN000828143 to these genes.

This branch should be reviewed to try to separate the COX7A2L from the COX7A1 sequences.

**Comment by marcfeuermann** [comment]
This was annotated to the root of the family. In fact we have some contradictory primary annotations for this term and very few evidence. So I removed PAINTing for GO:0097250. 
COX7A2L and COX7A1 are on distinct branches, not sure it is possibkle to create separate families. I will investigate...
