### ISSUE TITLE
IPR009914 improve mapping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5527]
* **InterPro ID / label**

current

GO:0019348 | dolichol metabolic process

but this is  downstream of dolichol metabolic process.

A better mapping would be

GO:0180047 | dolichol phosphate mannose biosynthetic process
because this is the module output

* **Example sequences with problematic annotation (ID + gene/protein name):**

dpm2

**Comment by blazaropinto** [comment]
Hi Val,
Thank you for this. I can see this change has already been done so will be publicly available in the next IntePro release.
Best,
Beatriz

**Comment by blazaropinto** [comment]
No worries :)
