### ISSUE TITLE
GO:0012505 | endomembrane system | IEA with SL-0147 | GO_REF:0000044

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5534]
https://www.pombase.org/gene/SPAC343.05
GO:0012505 | endomembrane system | IEA with SL-0147 | GO_REF:0000044

The location of activity isn't endomembrane system (this is part of the vacuolar ATPase)

@pgaudet  who do I assign to?

**Comment by pgaudet** [comment]
This is the same as Keywords.

**Comment by Antonialock** [comment]
Removed for all fungi, thanks.
