### ISSUE TITLE
replication-born double-strand break repair via sister chromatid exchange IBA with S000002599 , PTN000872167

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5536]
* **PTHR ID & PTN node:**

GO:1990414	
replication-born double-strand break repair via sister chromatid exchange
IBA with S000002599 , PTN000872167	GO_REF:0000033

should be

GO:0140861	
DNA repair-dependent chromatin remodeling?
@pgaudet  do you agree ?

* **Sequences with problematic annotation (ID + gene/protein name):**

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Complex family with several hundreds of primary BP annotations. I've reviewed the whole annotation. The annotation to GO:1990414 is not really necessary. I've added GO:0140861.
