### ISSUE TITLE
Review annotations to GO:0044349 DNA excision and child

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5539]
Dear all, 

The proposal has been made to obsolete
GO:0044349 DNA excision
GO:0000718 nucleotide-excision repair, DNA damage removal
see https://github.com/geneontology/go-ontology/issues/29220

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1LGmLqzeBemDZK5EmCa3utgdTV-yK9xDhgHJDM4RzDVs/edit?gid=0#gid=0

Impacted groups: 
EcoCyc 1

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
None

Thanks.

**Comment by amandamackie** [comment]
I've removed this annotation from EcoCyc
