### ISSUE TITLE
Review annotations to GO:0140133 symbiont-mediated suppression of host cytokine production

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5541]
Dear all, 

The proposal has been made to obsolete GO:0140133 symbiont-mediated suppression of host cytokine production

**Comment by pgaudet** [comment]
1 BHF
1 DisProt

see https://docs.google.com/spreadsheets/d/1JJtG2BmFfITflSTu0nEpDJlLE0MZT-RkNzc5KZSNy7M/edit?gid=0#gid=0

Annotations can be removed; more specific annotations already exist. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

the alternative annotation you have suggested is equivalent to this term is GO:0039540   symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of RIG-I activity. However this term does not imply a regulation of cytokine production. I would have thought that an effect on cytokine production by a symbiont is very important to capture. Overproduction of cytokines is now known to be a potentially lethal disease - cytokine storm - associated with some symbionts, in contrast reduction in cytokine production is likely to give the symbiont a growth advantage as it may reduce the immune response to the symbiont.

The parent term GO:0052170 symbiont-mediated suppression of host innate immune response provides a much better alternative if the plan is to remove GO:0140133 symbiont-mediated suppression of host cytokine production. 

Best

Ruth

**Comment by pgaudet** [comment]
Sounds good! Thanks @RLovering :)

**Comment by victorianugnes** [comment]
DisProt done, apologies for the delay!
