### ISSUE TITLE
ALANYL-TRNA SYNTHETASE (PTHR11777)-FBgn0027094

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5546]
* **PTHR ID & PTN node:**
ALANYL-TRNA SYNTHETASE (PTHR11777) 
PTN000206953
* **Sequences with problematic annotation (ID + gene/protein name):**
FBgn0027094 AlaRS
* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
* Block propagation of mitochondrion GO:0005739 to FBgn0027094 as this is the cytoplasmic version of this enzyme

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by ValWood** [comment]
These will be tricky to propagate correctly. The localizations don't always align well with the ortholog. For example, the family member  is the only alanyl-tRNA synthase in pombe, and is both mitochondrial and cytosolic

**Comment by hattrill** [comment]
I think that in these cases, not propagating a CC is the correct choice. As Ronan Keating once said, "you say it best when you say nothing at all"
