### ISSUE TITLE
MTG2 not involved in cytoplasmic translation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5548]
SGD:S000001211 MTG2 is annotated with cytoplasmic translation from PMID:15591131

Think that this is a mistake as it is mitochondrial. Abstract says "We propose that Mtg2p is involved in mitochondrial ribosome biogenesis." which is consistent with the current model of action proposed for the human enzyme in PMID:33283228. 

Suggested replacement term:
mitochondrial large ribosomal subunit assembly GO:1902775

**Comment by srengel** [comment]
Hi @hattrill replaced as requested. just now in Noctua.  thank you again for bringing this improvement opportunity to our attention.
