### ISSUE TITLE
GO:1990050 | phosphatidic acid transfer activity | IBA with O43715 , PTN005302567 | contributes_to 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5549]
* **PTHR ID & PTN node:**

GO:1990050 | phosphatidic acid transfer activity | IBA with O43715 , PTN005302567 | contributes_to | GO_REF:0000033

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC119.18 (mdm35)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

annotation, but the original annotation doesn't exist. Will this disappear automatically if the supporting annotation disappears?
I have never been sure about this...

**Comment by pgaudet** [comment]
Hi @ValWood 
If the original annotation is removed, the PAINT annotated will get removed as well in the next release.
