### ISSUE TITLE
PEROXISOMAL MEMBRANE PROTEIN 2, PXMP2 MPV17 (PTHR11266)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-annotation#5552]
* **PTHR ID & PTN node:**
* PTN000137585
* [PEROXISOMAL MEMBRANE PROTEIN 2, PXMP2 MPV17 (PTHR11266)](http://www.pantherdb.org/panther/family.do?clsAccession=PTHR11266)

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**
*'mitochondrial ribosome assembly' should not be propagated from this node. Some members of this family have been shown to have ion channel activity. Q567V2 is the only example where ribosome biogenesis has been shown to be defective in mutants and the mechanism is unknown - it might be via stabilization rather than assembly.

Might be possible to add mitochondrion/mitochondrial inner membrane if you can distinguish the PXMP2 branch which is peroxisomal.

**Comment by marcfeuermann** [comment]
The annotatio is indeed not very relevant. I've removed the PAINTing of this term.
