### ISSUE TITLE
Review annotations to GO:0072555 17-beta-ketosteroid reductase (NADPH) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#5555]
Dear all, 

The proposal has been made to obsolete GO:0072555 17-beta-ketosteroid reductase (NADPH) activity

**Comment by pgaudet** [comment]
1 UniProt >> removed
1 TAIR
1 CAFA 

Consider removing annotations, already annotated to GO:0072582 17-beta-hydroxysteroid dehydrogenase (NADP+) activity

Thanks, Pascale

**Comment by Antonialock** [comment]
I removed the CAFA annotation
