### ISSUE TITLE
GO:0000055 | ribosomal large subunit export from nucleus | IBA with PTN000529705 , locus:2033661

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5558]
* **PTHR ID & PTN node:**

GO:0000055 | ribosomal large subunit export from nucleus | IBA with PTN000529705 , locus:2033661

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC737.08 and all others

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

Midasin's primary function is in pre-60S Assembly: to remove specific assembly factors from the pre-60S ribosomal subunit. 
Proper maturation is a prerequisite for the subsequent recruitment of export factors but midasin doesn't seem to have a direct role in transport.

In fact the TAIR description  (i.e annotation source) is

Represents a homolog of the yeast MDN gene, which encodes a non-ribosomal protein involved in the maturation and assembly of the 60S ribosomal subunit. In Arabidopsis, it is essential for female gametogenesis progression.

**Comment by lreiser** [comment]
ticket is closed but I also removed this from TAIR annotation so it won't
come back...
Leonore Reiser, Ph.D.

***@***.***
www.arabidopsis.org
www.agbiodata.org
www.phoenixbioinformatics.org
