### ISSUE TITLE
GO:0006397 | mRNA processing | IEA with IPR030843  IPR030844 IPR030844

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5559]
* **InterPro ID / label**

GO:0006397 | mRNA processing | IEA with IPR030843

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

this seems incorrect at least for pan2
https://www.pombase.org/gene/SPAC22G7.04

pan2 is  a P-body protein involved in "
GO:0000289 | nuclear-transcribed mRNA poly(A) tail shortening
which makes it catabolism rather than processing (which is maturation)

**Comment by ValWood** [comment]
same for  GO:0006397 | mRNA processing | IEA with IPR030844

**Comment by ValWood** [comment]
and
https://www.pombase.org/gene/SPBC336.14c

GO:0006397 | mRNA processing | IEA with IPR030844
-- | -- | --


[GO:0006397](https://www.pombase.org/term/GO:0006397)	
[mRNA processing](https://www.pombase.org/term/GO:0006397)
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with [IPR030844](http://www.ebi.ac.uk/interpro/entry/IPR030844)

**Comment by blazaropinto** [comment]
Hi Val,
Thank you for this. I agree, so I remove the term from those entries. The changes will be available in the next InterPro release.
Best,
Beatriz
