### ISSUE TITLE
 GO:0006397	 mRNA processing IEA with IPR039727

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5560]
* **InterPro ID / label**

- | GO:0006397 | mRNA processing | IEA with IPR039727

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC725.08

* **Description of issue**

Pir2 is involved in surveillance (where inappropriately expressed or malformed RNAs are degraded)

rather than processing which is "maturation"

**Comment by ValWood** [comment]
Just to add if these InterPRo top GO mappings are made from existing annotations could you note them in the tickets? They need to be removed at source.

**Comment by blazaropinto** [comment]
Hi Val,
Thank you for this. I agree, the term doesn't look correct for quite a few members of the family, so I removed it. The changes will be available in the next InterPro release.
Best,
Beatriz
