### ISSUE TITLE
GO:0000387	 spliceosomal snRNP assembly IEA with IPR034100, IPR034098, IPR017340

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5561]
* **InterPro ID / label**

GO:0000387 | spliceosomal snRNP assembly | IEA with IPR034100

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPBC3E7.14 smf1

* **Description of issue**

smf1 is a core member of the spliceosomal snPRNP, rather than an assembly factor

**Comment by ValWood** [comment]
ditto

GO:0000387 | spliceosomal snRNP assembly | IEA with IPR034098
e.g. https://www.pombase.org/gene/SPBC4B4.05 smg1

**Comment by ValWood** [comment]
and

GO:0000387 | spliceosomal snRNP assembly | IEA with IPR017340

**Comment by blazaropinto** [comment]
Hi Val,
Thank you for this. I agree, so I removed the term from those entries and added [GO:0000398](http://www.ebi.ac.uk/QuickGo/GTerm?id=GO:0000398) to IPR034100, IPR034098 and [GO:0000395](https://www.ebi.ac.uk/QuickGO/term/GO:0000395) and [GO:0030627](https://www.ebi.ac.uk/QuickGO/term/GO:0030627) to IPR017340.
The changes will be available in the next InterPro release.
Best,
Beatriz
