### ISSUE TITLE
GO:0006281	 DNA repair IEA with IPR038959	GO_REF:0000002

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5562]
* **InterPro ID / label**

GO:0006281 | DNA repair | IEA with IPR038959 | GO_REF:0000002

* **Example sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC29A4.08c prp19

* **Description of issue**

prp19

PTHR43995 | PANTHER | Pre-mRNA-processing factor 19 | IPR038959

is a uB ligase involved in splicing. I'm fairly confident it doesn't have a role in DNA repair (although closely related family members do) but we have a lot of interaction data which places it in multiple splicing associated complexes, but no DNA repair complexes

**Comment by blazaropinto** [comment]
Hi Val,
Thank you for this. I agree, I see there is no direct evidence for a role in this process of the homologue from A.thaliana either, so I removed the term. The changes will be available in the next InterPro release.
Best,
Beatriz
