### ISSUE TITLE
Review annotations to GO:0052739 phosphatidylserine 1-acylhydrolase activity and GO:0080076 caffeoyl CoA:S-adenosyl-L-methionine O-methyltransferase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-annotation#5566]
Dear all, 

The proposal has been made to obsolete (with replacements)
GO:0052739 phosphatidylserine 1-acylhydrolase activity  -> GO:0008970 phospholipase A1 activity
GO:0080076 caffeoyl CoA:S-adenosyl-L-methionine O-methyltransferase activity  ->  GO:0042409 caffeoyl-CoA O-methyltransferase activity

see https://github.com/geneontology/go-ontology/issues/28816

Experimental annotations that need to be reviewed are here: 
https://docs.google.com/spreadsheets/d/1XDf7Jtv_ctlYGKMER5hH7oI7pI3oO9yjIZ-ccwGzFNY/edit?gid=0#gid=0

Impacted groups: 
Reactome 1
TAIR 2
UniProt 1 (to be automatically moved)

** Group contacts: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
----

Mappings that need to be reviewed: (InterPro2GO, UniProt-Keywords, UniRule) 
reactome2go	Reactome:R-HSA-8869425 > GO:phosphatidylserine 1-acylhydrolase activity ; GO:0052739

Thanks.

**Comment by deustp01** [comment]
One Reactome instance involving GO:0052739 has been patched as suggested. Correction will become visible with our March 2025 release.

**Comment by lreiser** [comment]
tair done....
