### ISSUE TITLE
GO:0007059 | chromosome segregation | IBA with S000000935 , P20654 , PTN000911504

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5570]
* **PTHR ID & PTN node:**

GO:0007059 | chromosome segregation | IBA with S000000935 , P20654 , PTN000911504

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC31H12.05c
sds21 is a paralog of dis1 which is involved in chromosome segregation, but there appears to be separation of. function in fission yeast. There does not seem to be a chromosome segregation =rol for sds21 and it doesn't localize to the kinetochore

Dis2, but not Sds21, binds the kinetochore and is required for correct chromosome segregation and spindle checkpoint silencing (Ohkura et al., 1989; Vanoosthuyse and Hardwick, 2009).

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

* Add the label 'high priority' if needed. Generally high priority issues affect a lot of proteins, and annotations are incorrect (as opposed to just imprecise).

**Comment by marcfeuermann** [comment]
Annotation has been reviewed
