### ISSUE TITLE
IPR004567 Type II pantothenate kinase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-annotation#5592]
* **InterPro ID / label**
IPR004567 Type II pantothenate kinase

* **Example sequences with problematic annotation (ID + gene/protein name):**
fly CG5828 (FBgn0031682/Q9VMU2)

* **Description of issue**
This is a family entry with a GO annotation to [pantothenate kinase activity (GO:0004594](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004594).
But while fly CG5828 (FBgn0031682/Q9VMU2) is a member of this family, it lacks the N-terminal kinase domain. (It does have a  phosphatase domain, so is thought to function as a phosphatase, like human PANK4 (Q9NVE7)).

So would it be possible to remove GO:0004594 from  IPR004567?

**Comment by blazaropinto** [comment]
Hi Steven,
Thank you for this. I agree, so I removed the term from this entry. The changes will be available in InterPro 104.0.
Best,
Beatriz
