### ISSUE TITLE
P38086/RDH54/ incorrect mappings to topoisomerase

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#566]
isomerase/toposimerase KW need removing, see thread below
thanks
Val

Rad54 and Rdh54 activities would fall under the purview of how  helicase terms (child terms of GO:0004386).  But the distinction  between Rad54 and Rdh54 compared to say, Pif1 or Srs2 is that they  don't separate the dsDNA into independent ssDNA strands, have  directionality, or processivity.

Maybe we do need a new term that makes that distinction?

On Feb 7, 2008, at 12:55 PM, Julie Park wrote:

&gt; Hi Val and Midori,
&gt;
&gt; The authors clearly assert in the paper that Rad54p is NOT a  helicase (because there is no processivity) and so I would rather  not make the annotation to helicase.  Perhaps this function needs a  new term for what would equate to "DNA opening" activity?  I'm also  going to pull Eurie into this to see if you have any additional  thoughts?
&gt;
&gt; I'll also look in to RDH54.
&gt;
&gt; Thanks,
&gt; Julie
&gt;
&gt; On Feb 7, 2008, at 10:41 AM, Valerie Wood wrote:
&gt;
&gt;&gt;
&gt;&gt; The same is also true for RDH54, (cereivisae only has 3  topoisomerases, top1,2 and 3)
&gt;&gt;
&gt;&gt; There are computational mappings to topoisomerase for this entry  from a SPKW  which might of been made due to these IDA  annotations.  I will report this tomorrow.
&gt;&gt;
&gt;&gt;
&gt;&gt; Val
&gt;&gt;
&gt;&gt;
&gt;&gt; Midori Harris &lt;midori@ebi.ac.uk&gt; wrote:
&gt;&gt;
&gt;&gt;&gt; I think the synonym should stay, but its scope should be 'related'  instead
&gt;&gt;&gt; of 'exact'. If I remember rightly, all topoisomerases can remove
&gt;&gt;&gt; supercoils, and some can introduce supercoils. But since  supercoils can
&gt;&gt;&gt; also be formed in other ways (e.g. ahead of and behind helicases  and RNA
&gt;&gt;&gt; polymerases) the synonym shouldn't be exact. I'll fix that.
&gt;&gt;&gt;
&gt;&gt;&gt;&gt; From the experiments, I think I agree with Val -- they seem to  show that
&gt;&gt;&gt;
&gt;&gt;&gt; Rad54p has helicase activity.
&gt;&gt;&gt;
&gt;&gt;&gt; m
&gt;&gt;&gt;
&gt;&gt;&gt; On Thu, 7 Feb 2008, Valerie Wood wrote:
&gt;&gt;&gt;
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; Hmm, I think I will ask Midori about this one. The synonym looks  like it
&gt;&gt;&gt;&gt; could be a bit misleading. Supercoiling can occur via helicases  (for
&gt;&gt;&gt;&gt; example during the DNA or RNA polymerase reaction) and is  releived by
&gt;&gt;&gt;&gt; topoisomerases. The topisomease reaction is some sort of isomerase
&gt;&gt;&gt;&gt; reaction which involved cutting a strand, decreasing the linking  number
&gt;&gt;&gt;&gt; and joining the strand back together. This isn't what the  helicase does.
&gt;&gt;&gt;&gt; The helicase unwinds but the supercoiling (elsewhere) is a  byproduct of
&gt;&gt;&gt;&gt; the unwinding.
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; Val
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; Julie Park &lt;juliep@genome.stanford.edu&gt; wrote:
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt; Hi Val,
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt; The synonym for DNA topoisomerase activity is "DNA supercoiling
&gt;&gt;&gt;&gt;&gt; activity" and the assay described in this paper seems to address  that
&gt;&gt;&gt;&gt;&gt; activity and the topoisomerase used is to relax the DNA so the
&gt;&gt;&gt;&gt;&gt; different physical forms can be distinguished by gel.  So in that
&gt;&gt;&gt;&gt;&gt; sense the annotation seems alright.  If you think that these  should
&gt;&gt;&gt;&gt;&gt; be two separate terms, perhaps it merits opening a SourceForge  item?
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt; Regards,
&gt;&gt;&gt;&gt;&gt; Julie
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt; ****************************************************************
&gt;&gt;&gt;&gt;&gt; Julie Park, Ph.D., Scientific Curator
&gt;&gt;&gt;&gt;&gt;  Saccharomyces Genome Database
&gt;&gt;&gt;&gt;&gt;  Department of Genetics
&gt;&gt;&gt;&gt;&gt;  Stanford University School of Medicine
&gt;&gt;&gt;&gt;&gt;  Stanford, CA 94305-5120 USA
&gt;&gt;&gt;&gt;&gt;  phone: (650)724-9959  fax: (650)725-1534
&gt;&gt;&gt;&gt;&gt;  http://www.yeastgenome.org
&gt;&gt;&gt;&gt;&gt; *****************************************************************
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt; On Feb 6, 2008, at 1:45 AM, &lt;yeast-curator@genome.stanford.edu&gt;  wrote:
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt;&gt; Form_Name "Suggestion"
&gt;&gt;&gt;&gt;&gt;&gt; URL "http://db.yeastgenome.org/cgi-bin/GO/goAnnotation.pl?
&gt;&gt;&gt;&gt;&gt;&gt; dbid=S000003131"
&gt;&gt;&gt;&gt;&gt;&gt; Name "val"
&gt;&gt;&gt;&gt;&gt;&gt; Address "val@sanger.ac.uk"
&gt;&gt;&gt;&gt;&gt;&gt; Remote Address "193.62.203.214"
&gt;&gt;&gt;&gt;&gt;&gt; Referer "http://db.yeastgenome.org/cgi-bin/suggestion"
&gt;&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt;&gt; Text "I'm not sure that topoisomerase is correct here: Isn't the
&gt;&gt;&gt;&gt;&gt;&gt; topoisomerase used in the assay to confirm the specific type of
&gt;&gt;&gt;&gt;&gt;&gt; unwinding reaction? Val Unwinding of the relaxed duplex by Rad54
&gt;&gt;&gt;&gt;&gt;&gt; was expected to result in the formation of positively supercoiled
&gt;&gt;&gt;&gt;&gt;&gt; domains in the adjacent regions of the duplex, which would be
&gt;&gt;&gt;&gt;&gt;&gt; removed by the topoisomerase I present in the reaction"
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/566":https://sourceforge.net/p/geneontology/annotation-issues/566

**Comment by mcourtot** [comment]
Hi Val: did this get fixed?

**Comment by ValWood** [comment]
nope
http://www.uniprot.org/uniprot/P38086

**Comment by mcourtot** [comment]
Action: remove KW-0799 from P38086
