### ISSUE TITLE
Hsp 27 binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#6]
Hello, 

I have a gene product that specifically interacts with 
the heat shock protein 27 - hsp 27 - and exerts an 
inhibitory effect upon its functioning. 
PMID: 11546764 and references therein
Heat shock protein 27 participates in an number of 
processes; its activity is mudlated via interactions with 
a range of proteins

Proposed terms
GO:0005515 - protein binding 
GO:new -  Hsp 27 binding
Def: Interacting selectively with Hsp 27, a member of 
the light weight heat shock proteins.

GO:0030188 - chaperone regulator activity
GO:new - Hsp 27 regulator acitivty
Def: Modulates the activity of light weight chaperone 
proteins. 

GO:0030190 - chaperone inhibitor activity
GO_new  - Hsp 27 inhibitor acitrivy
Def: Stops, prevents or reduces the activity of light 
weight chaperone proteins. 

Thank you, 

Victoria

Reported by: vpetri

Original Ticket: "geneontology/annotation-issues/6":https://sourceforge.net/p/geneontology/annotation-issues/6

**Comment by linuxlovell** [comment]
thanks www.movied.org
