### ISSUE TITLE
query KW mapping to membrane

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#622]
P32747 SPAC57A10.12c ura3 
has a keyword mapping to membrane

this seems like it should be removed,

derived from
Subcellular Location    Mitochondrion inner membrane.

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/622":https://sourceforge.net/p/geneontology/annotation-issues/622

**Comment by mcourtot** [comment]
HI Val, did this get fixed?

**Comment by ValWood** [comment]
Still there
http://www.ebi.ac.uk/QuickGO/GProtein?ac=P32747
