### ISSUE TITLE
Antibiotic resistance

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#629]
A number of pombe genes have a SP keyword
antibiotic resistance

mapped to GO term
response to antibiotic

cycloheximide
and response to cycloheximide

these include

19S proteasome regulatory subunit Rpn11  P41878  
ubiquitinated histone-like protein Uhp1 P30821
tubulin beta    P05219
Ran GTPase binding protein Hba1 Q09146

this isn't an approprite mapping as these are mutant phenotypes and do not represent normal processes for these gene products.

can these mappings be removed.

thanks

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/629":https://sourceforge.net/p/geneontology/annotation-issues/629

**Comment by mcourtot** [comment]
Hi Val - going through old tickets in hopes of cleaning up the tracker. It seems a lot of those were submitted/commented on by you, so apologies in advance but I'll be bouncing them back trying to see if they should remain open or can be closed.

**Comment by ValWood** [comment]
Still there...
http://www.uniprot.org/uniprot/P41878

**Comment by mcourtot** [comment]
Action: remove KW-0046 from P41878, P30821, P05219, Q09146

**Comment by ValWood** [comment]
transferred to the master ticket for rogue KW mappings
https://github.com/geneontology/go-annotation/issues/1503
