### ISSUE TITLE
presumed potassium channel subunit

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#635]
voltage-gated ion channel activity       SP_KW:KW-0851
ion channel activity        SP_KW:KW-0407
potassium ion binding       SP_KW:KW-0630

these mappings seem too specific (certainly the channel activity, it is likely to be an oxidoreductase)

pombe O59826 on
InterPro:IPR005399 for more details

(see previous SF item 

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/635":https://sourceforge.net/p/geneontology/annotation-issues/635

**Comment by mcourtot** [comment]
Hi Val: can you update status, and whether this can be closed?

**Comment by ValWood** [comment]
Nope, still has "voltage-gated ion channel'
http://www.uniprot.org/uniprot/O59826
Although this is a subunit of a transporter complex it isn't a transporter itself.

**Comment by mcourtot** [comment]
Thanks for checking - tagging for bulk submission to UniProt.

**Comment by ValWood** [comment]
The mapping is still present.

**Comment by Antonialock** [comment]
Removed, I'm note sure if KW mappings only filter through next uniprot update or sooner.

**Comment by Antonialock** [comment]
(kw removed from:
Q13303 Q14722 P62482 Q27955 P63143 P63144 P62483 Q9XT31 Q9PTM5 Q4PJK1 Q28528 Q9PWR1 O43448 Q63494 P97382 Q9PTM4 O23016 Q40648 O59826
)

**Comment by Antonialock** [comment]
I can't remove the KW because although the KW is in the "molecular function" branch of KWs, it is defined more like a complex in terms of mapping across to GO e.g.  
Ion channel (KW-0407): "Protein which is part of a transmembrane protein complex that forms a hydrophilic channel"

I will remove the MF from the mapping.

**Comment by Antonialock** [comment]
voltage-gated ion channel activity SP_KW:KW-0851
monoatomic ion transmembrane transport
monoatomic ion channel complex

ion channel activity SP_KW:KW-0407
monoatomic ion transmembrane transport
monoatomic ion channel complex

potassium ion binding SP_KW:KW-0630
mapping had already been deleted
