### ISSUE TITLE
SPKW transport incorrect mappings

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#673]
This comes up regularly....

Here is another example

S. pombe    Q7Z991   and S. cerevisiae  P43569 CCR4 NOT complex have a kw mapping to transport. They are not involved in transport...

I think the mapping comes from the fact that these have an ABC transporter domain.

ABC transporters domains on their own do not mean that the protein is a tm transporter, this domain is actually an ATPase region (it is inappropriately named). 
These proteins can only unambiguously be annotated as  transporters  IF they are accompanied by  the tmm domains (this may not be the case in bacteria but In eukaryotes this domain is present in a number of non transporter proteins including transcription and translation factors).

The incorrect mappings have been removed from iInterpro, but the Uniprot ones still remain.

Val

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/673":https://sourceforge.net/p/geneontology/annotation-issues/673

**Comment by mcourtot** [comment]
Hi Val: can you update status, and whether this can be closed?

**Comment by ValWood** [comment]
No, still has a transport mapping
http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q7Z991

**Comment by pgaudet** [comment]
KW removed from  Q7Z991
