### ISSUE TITLE
check keywords for Sc URN1

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#679]
Hi,

I have just removed information from our description line for S. cerevisiae URN1 that stated it was an mRNA splicing factor. This was derived from unpublished info submitted with the gene name reservation, but as of 12/10/2008, I do not see any published information supporting the involvement of this gene in splicing. 

I see these IEA annotations from the GOA project:
"mRNA processing" with EBI:KW-0507
"RNA splicing" with EBI:KW-0508
"spliceosome" with EBI:KW-0747

Please check these keywords associated with URN1 to see if there is any published information to support these keywords. If there is, I'll be happy to update the info in SGD. Otherwise, they should probably be removed.

thanks,

-Karen

Reported by: krchristie

Original Ticket: "geneontology/annotation-issues/679":https://sourceforge.net/p/geneontology/annotation-issues/679

**Comment by suzialeksander** [comment]
Looking at this today, these IEAs are still being made (last one in September, and now to "spliceosomal complex").  I think there is some evidence in the literature to support- especially for the pombe homolog.  Closing.
