### ISSUE TITLE
KW mappings to motor activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#694]
a number of pombe proteins are mapped to motor activity based on a KW mapping 
but these are not the motor proteins

SPBC56F2.03 actin-like protein Arp10 (predicted)
SPAC1805.08 dlc1, dynein light chain Dlc1
SPAC926.07c dlc2, dynein light chain Dlc2
SPAC926.03  rlc1, myosin II regulatory light chain Rlc1
SPAP8A3.08  cdc4, myosin II light chain

Reported by: ValWood

Original Ticket: "geneontology/annotation-issues/694":https://sourceforge.net/p/geneontology/annotation-issues/694

**Comment by mcourtot** [comment]
Hi Val - can you confirm status? I'm adding the correct label so hopefully once those tickets are sorted out we can address them all at once.

**Comment by ValWood** [comment]
First one fixed, second one not. I won't check the rest
http://www.uniprot.org/uniprot/Q9UTS6

**Comment by mcourtot** [comment]
Thanks Val - there seems to be quite a bit of outstanding tickets on those. Would it be easier to sit together when you're next here and prepare the submission together?

**Comment by ValWood** [comment]
I would just put this one throught to. These are the outstanding ones (for pombe, but other organimss will need checking too).
Others are fixed.

SPAC1805.08	dlc1, dynein light chain Dlc1  
	Q9UTS6 http://www.uniprot.org/uniprot/Q9UTS6

SPAC926.07c	dlc2, dynein light chain Dlc2
Q9UR05 http://www.uniprot.org/uniprot/Q9UR05

**Comment by ValWood** [comment]
Yay, this one is done
