### ISSUE TITLE
nitric oxide binding, regulator activity, regulation of NOS 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#7]
Hello,

I have a gene product that interacts with and inhibits 
the activity of nitric oxide synthase. 
PMID: 8864115  and references therein

GO has only nitric oxide regulator acrivity, regulation of 
nitric-oxide biosynthesis, positive and negative.

I'm interested in having terms for NOS binding and 
inhibition. For consistency reasons the following terms 
are proposed:

GO:0030235 - nitric-oxide synthase regulator activity
GO:new - nitric-oxide activator activity
Synonym: nitric oxide activator activity
Def: Increases the activity of a nitric-oxide synthase
GO:new - nitric-oxide inhibitor activity
Synonym: nitric oxide inhibitor activity
Def: Stops, prevents or reduces the activity of a nitric-
oxide synthase.

GO:0019899 - enzyme binding
GO:new - nitric-oxide binding
Synonym: nitric oxide binding
Def. Interacting selectively with a nitric-oxide synthase

GO:0050790 - regulation of enzyme activity
GO:new - regulation of nitric-oxide synthase 
activity
Synonym: regulation of nitric oxide synthase
Def:Any process that modulates the activity of a nitric-
oxide synthase
GO:new - negative regulation of nitric-
oxide synthase activity
Synonym: negative regulation of nitric synthase activity
Def: Any process that stops, prevents or reduces the 
activity of a nitric-oxide synthase
GO:new - positive regulation of nitric-
oxide synthase activity
Synonym: positive regulation of nitric oxide activity
Def: Any process that activates or increases the 
activity of a nitric-oxide synthase 

Reported by: vpetri

Original Ticket: "geneontology/annotation-issues/7":https://sourceforge.net/p/geneontology/annotation-issues/7

**Comment by linuxlovell** [comment]
thanks www.movied.org
