### ISSUE TITLE
genes associated with GO:0006488 (LLO synthesis)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#786]
This report is similar to https://sourceforge.net/tracker/index.php?func=detail&aid=2945847&group\_id=36855&atid=605890 , but here I will list all the genes belonging to "Dolichol-linked oligosaccharide biosynthetic process ; GO:0006488 and children" which are not currently annotated as such in GO

For a review on this process and the genes involved, I recommend you:
PMID: 19862844 and 11805072

DPAGT1
ALG1
ALG11
RFT1
ALG3
ALG9
ALG10A/B
ALG5
DPM1
DPM2
DPM3
PMM1
PMM2
GMPPA
GMPPB
PGM3
UAP1
DOLK1

genes already annotated in GO:
ALG12
ALG2
DPAGT1
MPDU1

Reported by: dalloliogm

Original Ticket: [geneontology/annotation-issues/786](https://sourceforge.net/p/geneontology/annotation-issues/786)

**Comment by pgaudet** [comment]
Hi @ggeorghiou - can you please annotate this ? Or pass it on... 

Thanks, Pascale
