### ISSUE TITLE
KW-0617   , 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#787]
Hi 
this is mapping GO:0004252 serine-type endopeptidase activity to SERINE1.  SERINE1 is an inhibitor of this activity, and does have the correct KW-0722 GO:0004867   serine-type endopeptidase inhibitor activity

KW-0617 needs to be removed from SERINE1 P05121, and maybe worth checking that there are no other records with KW-0617 and  KW-0722 

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/annotation-issues/787](https://sourceforge.net/p/geneontology/annotation-issues/787)

**Comment by mcourtot** [comment]
@rachhuntley: can you confirm status?

**Comment by rachhuntley** [comment]
It looks like KW-0617 plasminogen activation is no longer mapped to GO:0004252 serine-type endopeptidase activity. I'm not sure if the keyword has changed name or just the mapping has been removed, but the three proteins mentioned above still have both KW-0617 and KW-O722, but only the latter is producing a GO annotation. There is no longer any annotation for GO:0004252 serine-type endopeptidase activity for any of these proteins.

Is it OK for a plasminogen activator inhibitor to have the keyword plasminogen activation?
(Although, as mentioned, this is not a problem for the GO annotation only the UniProt keywords).

**Comment by ValWood** [comment]
Looks OK
