### ISSUE TITLE
Human Calreticulin Annotations

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#8]
[This item has been transferred from the curator
requests tracker (905470) and was submitted by Pascale
Gaudet (pgaudet)].

Hello all,

The calreticulin gene of human (CRTC_HUMAN),
SwissProt ID P27797, is annotated with regulation of
transcription, DNA dependent, and transcription
corepressor activity. Is this correct? 

Pascale

Reported by: jl242

Original Ticket: "geneontology/annotation-issues/8":https://sourceforge.net/p/geneontology/annotation-issues/8

**Comment by linuxlovell** [comment]
thanks www.movied.org
