### ISSUE TITLE
Genes associated with GO:004432

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#815]
The following genes can be associated with the term GO:004432, 'ER Quality Control Compartment':
- ER Mannosidase I (uniprot id: Q9UKM7, MA1B1_HUMAN) 
- EDEM1 (Q9261, (EDEM1_HUMAN)
- EDEM2 (Q9BV94 EDEM2_HUMAN)
- EDEM3 (Q9BZQ6 EDEM3_HUMAN)

The following Pubmed IDs validate the association:
- 18003979 (Endoplasmic reticulum (ER) mannosidase I is compartmentalized and required for N-glycan trimming to Man5-6GlcNAc2 in glycoprotein ER-associated degradation. Avezov E, Frenkel Z, Ehrlich M, Herscovics A, Lederkremer GZ. Mol Biol Cell. 2008 Jan;19(1):216-25. Epub 2007 Nov 14.)
- 11408579 (A novel quality control compartment derived from the endoplasmic reticulum. Kamhi-Nesher S, Shenkman M, Tolchinsky S, Fromm SV, Ehrlich R, Lederkremer GZ. Mol Biol Cell. 2001 Jun;12(6):1711-23)

Reported by: dalloliogm

Original Ticket: [geneontology/annotation-issues/815](https://sourceforge.net/p/geneontology/annotation-issues/815)

**Comment by pgaudet** [comment]
@ggeorghiou Can you please have a look and see if you can annotate PMID:11408579? The otehr paper is annotated. 

Thanks, Pascale

**Comment by pgarmiri** [comment]
Hi @pgaudet ,
I just curated the suggested paper. The term could be used but none of the entities mentioned above were in the paper.
Regards,
Penelope

**Comment by pgaudet** [comment]
We can close, thanks !
