### ISSUE TITLE
PANTHER:PTHR11829_AN0 incorrect annotation (forkhead)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#816]
There are a number of annotations for some fission yeast transcription factors  with this reference which are incorrect:

RNA polymerase II transcription factor activity, enhancer binding ( yeast don't have "enhancers" as such

promoter binding (incorrect as promoter is defined)

specific transcriptional repressor activity (no evidence that these transcription factors also function as repressors)

double-stranded DNA binding (if all tracription factors bind double strnded DNA, this should be a parent of
RNA polymerase II regulatory transcription factor site sequence-specific DNA binding)

These annotation issues  might be moot becuase many of these terms will probably disappea in the overhaul.

Cheers

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/816](https://sourceforge.net/p/geneontology/annotation-issues/816)

**Comment by mcourtot** [comment]
@thomaspd: you seem to be the last one referenced on this (old) ticket - can you follow up?

**Comment by pgaudet** [comment]
Current annotations are: 

* regulation of transcription by RNA polymerase II          
* RNA polymerase II transcription factor activity, sequence-specific DNA binding                              
* nucleus                                 
* cell differentiation                        
* anatomical structure morphogenesis 

May be worth revisiting for the last two terms

**Comment by pgaudet** [comment]
Removed anatomical structure development and cell differentiation from the fungi clade.
