### ISSUE TITLE
PANTHER:PTHR22573_AN318 incorrect annotations 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#817]
fission yeast SPAC1296.01c

has mappings to
chitin biosynthetic process         ISS (PAINT_REF:0022573) with PANTHER:PTHR22573_AN318
fission yeast has no chitin in vegetaive cell walls

These also look wrong
photoreactive repair        ISS (PAINT_REF:0022573) with PANTHER:PTHR22573_AN318    1 other
response to UV      ISS (PAINT_REF:0022573) with PANTHER:PTHR22573_AN318  
(I don't actually see any orthologs with this annotation and it doesn't make biological sense, so it might be a PAINT bug?)

val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/817](https://sourceforge.net/p/geneontology/annotation-issues/817)

**Comment by mcourtot** [comment]
@pgaudet: trying to go through old tickets on tracker and do some cleanup. I'm assigning Panther tickets to you, but please reassign if this should go to someone else.

**Comment by pgaudet** [comment]
The tree is now annotated to 'glycogen biosynthetic process'; is this OK ? 
photoreactive repair and response to UV are gone. 

@ValWood if that's OK please close. 

Pascale

**Comment by ValWood** [comment]
no ;)

where does that come from?

The gene I was looking at is:
SPAC1296.01c
https://www.pombase.org/gene/SPAC1296.01c ?

**Comment by pgaudet** [comment]
SPAC1296.01c is now in PTHR45955; @ValWood says annotations are OK now. 

Pascale
