### ISSUE TITLE
PANTHER problem annotation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#820]
DNA damage response, signal transduction resulting in induction of apoptosis        ISS (PAINT_REF:0011361) with PANTHER:PTHR11361_AN79
(msh2 and 6)

pathway absent from pombe (not present in yeast)?

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/820](https://sourceforge.net/p/geneontology/annotation-issues/820)

**Comment by marcfeuermann** [comment]
Has probably been fixed a while ago since no mention to apoptosis can been found anymore.
