### ISSUE TITLE
PTHR43718 (was:PANTHER:PTHR10046_AN2) problems

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#822]
SPAC22F3.06c
I am concerned about most of the annotations to Lon protease homolog Lon1 (predicted)  
as these do not appear to be annotated to any of the orthologs.

Lon is a mitochondrial protease involved in protein degradation. I can't trace annotations to

single-stranded RNA binding
single-stranded DNA binding
mitochondrial light strand promoter anti-sense binding
mitochondrial nucleoid

response to hypoxia (see response to discussion)
oxidation-dependent protein catabolic process
cellular response to oxidative stress

(these may be OK, it could have dual functionality but i can't trace the source organism)

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/822](https://sourceforge.net/p/geneontology/annotation-issues/822)

**Comment by pgaudet** [comment]
@ValWood 
Current annotations to this family are: 
protein targeting to peroxisome
protein processing
peroxisomal matrix

If that's OK please close. 

Thanks, Pascale

**Comment by ValWood** [comment]
nope  sorry ;(

In  pombe/cerevisiae  this is in the mitochondrial matrix.....
and we don't know it's targets.... but it seems to be quality control not processing (where does the peroxisome stuff come from?)

**Comment by ValWood** [comment]
this is 1:1 to human and the human ortholog is also mitochondrial /Qc
http://www.uniprot.org/uniprot/P36776

**Comment by ValWood** [comment]
was this the right ticket?

**Comment by pgaudet** [comment]
@dustine32
Can you please look at this one ? 
In the file in the current ftp ()

http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC22F3.06c

**Comment by dustine32** [comment]
@pgaudet So far as I can see the PomBase:SPAC22F3.06c to GO:0005759 IBA is in the paint_pombase.gaf submitted by us so it's likely coming out of the PAINT DB and not related to the GO pipeline. I'll double-check the ftp.pombase file but this looks like a normal IBA. Does it look odd in PAINT?

**Comment by dougli1sqrd** [comment]
Yes, I find `PomBase	SPAC22F3.06c	lon1		GO:0001018	PMID:21873635	IBA	PANTHER:PTN000005479|MGI:MGI:1921392|UniProtKB:P36776	F	mitochondrial matrix Lon protease	UniProtKB:Q09769|PTN000005530	protein	taxon:284812	20170228	GO_Central` in the paint_pombase source file on our end. 

I also see it after paint_pombase is validated.

**Comment by cmungall** [comment]
Thanks for the double-validation Eric. @pgaudet should we assign this ticket to @dustine32 now? (I think we need to add him to this tracker)

**Comment by pgaudet** [comment]
@cmungall I dont know how to assign people to individual trackers or to multiple teams.

**Comment by pgaudet** [comment]
@dustine32 
I dont see the annotation in PAINT. I do see this message: 

>2018-06-27: PAINT_EXP annotation to node PTN000005479 with GO:0001018 was un-obsoleted because there now exists new supporting leaf node experimental go annotation after PANTHER library version update.

However there are only two NOT annotations t human and mouse LONP1 (see screenshot). 

<img width="966" alt="image" src="https://user-images.githubusercontent.com/4782928/45051018-cabc2400-b050-11e8-8886-333c15eb61c2.png">


@dustine32 will you troubleshoot this with Anushya ?

**Comment by ValWood** [comment]
Are we looking at the right GO terms
Lon1 is a mitochondrial matrix protein so  GO:0005759 is fine...

**Comment by ValWood** [comment]
I was questioning
"mitochondrial light strand promoter anti-sense binding" , mainly....
I think we established last night that the proetase does bind to mitochondrial DNA but promoter binding still seemed strange, so was this the annotation that you could not locate for pombe @pgaudet ?

**Comment by ValWood** [comment]
ignore, that is the term  you were looking at.

**Comment by pgaudet** [comment]
Waiting for response from @dustine32

**Comment by dustine32** [comment]
@pgaudet Focusing on the PomBase:SPAC22F3.06c to GO:0001018 IBA that's getting spit out of PAINT, you may have fixed it on the PAINT side by obsoleting the GO:0001018 to PTN000005479 annotation a few days ago. This should be reflected by the next export of PAINT IBA GAFs, which I'm doing a test run right now to confirm.

**Comment by dustine32** [comment]
@pgaudet Returning back to this one now because I can finally see the results of the GAF test run (the USC HPC server cluster was down all last week). I confirmed that the PomBase:SPAC22F3.06c to GO:0001018 IBA annotation did not get generated. This means it shouldn't be included in next month's PAINT GAF submission. For comparison, the 8/23/18 PAINT GAFs did contain this line.

I'm pretty sure this annotation isn't being generated because its IBD to PTN000005479 was recently obsoleted on 9/3/18.

**Comment by thomaspd** [comment]
All of the questionable annotations have been corrected (see http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC22F3.06c), except for the ss DNA binding annotation, but we feel this is adequately supported in the literature for the mouse protein with the experimental annotation that was used https://www.ncbi.nlm.nih.gov/pubmed/?term=12657466

**Comment by ValWood** [comment]
Yep OK agreed, the DNA binding activity appears to be highly conserved.
v
