### ISSUE TITLE
GO:0000718 nucleotide-excision repair, DNA damage removal

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#824]
just annotated proteins of the XPC complex \(including Q01831 human XPC and P54727 human RAD23B\)  and wondered why these  have been annotated to GO:0000718 nucleotide-excision repair, DNA damage removal by REACTOME. Should rather go to GO:0000715 nucleotide-excision repair, DNA damage recognition \(which is the function of the complex\).
Moreover, the pmid used by REACTOME PMID:10583946 is a review paper, means it does not contain any experimental data \(which is somehow expected seeing the used evidence code 'EXP'.\) Might also apply for other proteins that have been annotated b REACTOME using this pmid.

Reported by: broechert

Original Ticket: [geneontology/annotation-issues/824](https://sourceforge.net/p/geneontology/annotation-issues/824)

**Comment by mcourtot** [comment]
@rachhuntley: can this be closed or is it still active?

**Comment by rachhuntley** [comment]
Well, the two proteins mentioned at the beginning no longer have annotation to GO:0000718 nucleotide-excision repair, DNA damage removal, so this appears to have been resolved (in only 5.5 years - woo-hoo!)

**Comment by mcourtot** [comment]
Yes - I was trying to clean up the backlog at least a little bit... on the bright side, 5.5 years is better than never ;)
