### ISSUE TITLE
PANTHER:PTHR10871_AN0 (ribosomal protein)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#860]
One member of this family is a ribosomal protein, and although the cytoplasmic member is implicated also in riobosome biogenesis, this should not be transferred across to the mitochondrial member (this is analogous to the GTPAse example we discussed recently on the mailing list...)

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/860](https://sourceforge.net/p/geneontology/annotation-issues/860)

**Comment by thomaspd** [comment]
ribosome biogenesis was removed before the paint data was loaded to the paint database in Feb. 2017.
