### ISSUE TITLE
PAINT_REF:0011409) with PANTHER:PTHR11409_AN0 	4 others

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#862]
dea2 SPBC1198.02 in fission yeast is adenine deaminase (not adenosine)

(it is possible that the adenosine annotation originates from some UniPRot entries which have all recently been fixed across organisms so this one will need revisiting)

Out of curiosity, how do PAINT annotations get updated when the supporting annotations are removed?

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/862](https://sourceforge.net/p/geneontology/annotation-issues/862)

**Comment by ValWood** [comment]
fixed in AmiGO
