### ISSUE TITLE
muscle atrophy ; GO:0014889

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#877]
Relating to a GO SF item, there are annotations to 'muscle atrophy GO:0014889' which are suspicious. The term should only be used when muscle atrophy is a 'normal' physiological process and not a disease process.

We will add a comment to GO:0014889 to this effect.

https://sourceforge.net/tracker/?func=detail&aid=2193207&group\_id=36855&atid=440764

There are 30 annotations to this term or its children \(14 manual- UniProt, RGD and MGI\).

Thanks,
GO.

Reported by: rebeccafoulger

Original Ticket: [geneontology/annotation-issues/877](https://sourceforge.net/p/geneontology/annotation-issues/877)

**Comment by mcourtot** [comment]
Seems addressed by @rachhuntley - please reopen if not.
