### ISSUE TITLE
question on GO:0030254

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#9]
Hello  this is Candace Collmer (email: 
ccollmer@wells.edu) from the PAMGO (Plant-Associated 
Microbe Gene Ontology) interest group.  We are 
beginning the work of developing suggested GO terms 
for the Biological Process ontology that could be used to 
annotate gene products of different plant pathogens  
bacteria, fungi, oomycetes, nematodes, etc.  We are 
currently working on an outline of higher order terms 
(and definitions) that we hope will be applicable to both 
plant and animal pathogens as well as to microbes that 
enter into various types of symbiotic relationships with 
hosts.  We are also trying to find a way to integrate 
these suggested new terms into existing categories in 
the GO Biological Process ontology (e.g. host-pathogen 
interactions, pathogenesis, etc.), and will soon send a 
proposed scheme for your evaluation. 
In the meantime, as we are working on this project, 
we have a question about what gene products are 
appropriate to annotate to an existing term in the GO 
biological process ontology,  GO:0030254 = type III 
protein secretion system (definition: a bacterial 
secretion system in which secretion occurs in a 
continuous process without the distinct presence of 
periplasmic intermediates; does not involve proteolytic 
processing of secreted proteins).  Given this is a 
biological process term, can we annotate gene products 
to it that are transported via the type III system as well 
as those gene products that make up the injection 
apparatus itself?

Reported by: ccollmer

Original Ticket: "geneontology/annotation-issues/9":https://sourceforge.net/p/geneontology/annotation-issues/9

**Comment by linuxlovell** [comment]
thanks www.movied.org
