### ISSUE TITLE
some mappings to "transport" should be to "localization"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#916]
HI,

S. pombe cut8   P38937 has keyword mappings to transport and protein transport.

Cut* is involved in tethering of the proteasome to the nuclear envelope, so its role is in "localization" which is broader then transport, so these KW need to be removed.

It could be mapped to
"proteasome localization"

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/916](https://sourceforge.net/p/geneontology/annotation-issues/916)

**Comment by mcourtot** [comment]
@rachhuntley: can this be closed?

**Comment by ValWood** [comment]
Nope mapping it still applied to this (and probably to other related proteins)
http://www.uniprot.org/uniprot/P38937

**Comment by mcourtot** [comment]
Thanks Val - I am applying the label "UniProt KW' to those, so I can submit a bulk update to the UniProt curators. I also added a link in the contributing guidelines for the tracker towards the UniProt update submission form as those are dealt with by someone in the UniProt team at SIB, so in future it is probably best to submit directly there to make sure they don't fall through the cracks.

**Comment by ValWood** [comment]
In addition, most of these have already been submitted to the UnIProt helpdesk a number of times, so I don't think anyone monitors this either!

**Comment by ValWood** [comment]
I should add that one problem with using the helpdesk is that  if I submit these from fission yeast acc numbers they will be assigned to the yeast UniProt curator, because they come from pombe. However, these are NOT fission yeast specific mapping issues, they affect all species to which the mapping is applied, so the mapping needs to be looked at critically.

**Comment by rachhuntley** [comment]
The process that we agreed on when I was at EBI was that I would forward these requests onto the UniProt helpdesk because UniProt don't monitor this tracker. They did receive them but had such a huge backlog that some just got missed. I don't know if this is still the procedure?

**Comment by mcourtot** [comment]
Hi all - seeing Val at the office reminded me of this :)

We talked about this in a GOA meeting. The go-annotation tracker was never a UniProt activity, rather Rachael was forwarding the requests to the helpdesk, and we would like to cut down on this redundant activity. The keyword mapping is maintained by our SIB colleagues and so the help@uniprot.org is the appropriate mailing list to use for those.
This was brought up with SIB recently and they are in the process of restarting monitoring emails about this mapping and so this should help resolve problems there.

Hope this helps,
Melanie

**Comment by ValWood** [comment]
I have agreed to go through the tickets and resubmit to the helpdesk, and then close the git hub ticket when completed. This way we maintain a record for the GO archive which isn't just in my mailbox.

**Comment by ValWood** [comment]
transferred to
https://github.com/geneontology/go-annotation/issues/1503
