### ISSUE TITLE
SP_KW:KW-0805 KW mapping

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#956]
RNA polymerase I upstream activation factor complex subunit Rrn10
is mapping to 
regulation of transcription, DNA-dependent  
but this is directly involved in
transcription from RNA polymerase I promoter
so this would be a more appropriate mapping

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/957](https://sourceforge.net/p/geneontology/annotation-issues/957)

**Comment by mcourtot** [comment]
@rachhuntley: can this be closed?

**Comment by ValWood** [comment]
nope still present:

http://www.ebi.ac.uk/QuickGO/GProtein?ac=Q10360	
Q10360 rrn10
GO:0006355 regulation of transcription, DNA-templated
P
IEA
UniProt Keywords2GO (UniProtKB/Swiss-Prot entries)
UniProtKB-KW:KW-0805

**Comment by ValWood** [comment]
This one is hardly surprising as we had an experiemental annotation to a regulation term, now fixed

**Comment by mcourtot** [comment]
Thanks - assigning myself and tagging for bulk submit to UniProt curators later.

**Comment by sylvainpoux** [comment]
Hi, I see more a problem of ontology here: the KW maps to regulation of GO:0006355; regulation of transcription, DNA-templated, which is imprecise, but not incorrect.

GO:0006361 transcription initiation from RNA polymerase I promoter would be of course better and ideally GO:0006361 and GO:0006355 should be directly linked.

Unfortunately,  GO:0006361 and GO:0006355 are related by the parent 'GO:0006351 transcription, DNA-templated'

I don't think we can do something for this

Sylvain

**Comment by ValWood** [comment]
Hi Sylvain,

I'm confused
why not map to
GO:0006361 transcription initiation from RNA polymerase I promoter 
instead?
since it is directly involved, not regulating?

val
