### ISSUE TITLE
incorrect mapping SP_KW:KW-0240

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#974]
SP\_KW:KW-0240

is mapping S. pombe spp1 and 2 \(DNA primase\)
http://www.uniprot.org/uniprot/O14215
http://www.uniprot.org/uniprot/O74761

to transcription

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/975](https://sourceforge.net/p/geneontology/annotation-issues/975)

**Comment by mcourtot** [comment]
@ValWood: can you check status?

**Comment by ValWood** [comment]
This one is fixed
