### ISSUE TITLE
SP_KW:KW-0313 glucose metabolism

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-annotation#980]
Q9P6P9  pyruvate dehydrogenase (acetyl-transferring) kinase activity has a maapping to

GO:0006006  glucose metabolic process

but pyruvate can come from other places 

Thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/annotation-issues/981](https://sourceforge.net/p/geneontology/annotation-issues/981)

**Comment by Antonialock** [comment]
val I see in PomBase

Gene: pkp1 / SPAC644.11c
aerobic respiration
acetyl-CoA biosynthesis from pyruvate

re you changing these to regulation?

**Comment by Antonialock** [comment]
Should the kinase and the phosphatase have a "direct" GO term to signaling?

![image](https://github.com/geneontology/go-annotation/assets/12727506/6d96a7cc-03b9-45b7-9608-af7fdee9746a)



![image](https://github.com/geneontology/go-annotation/assets/12727506/71f7188e-b578-4b9c-a8c7-ecc01bd6bf6c)

**Comment by Antonialock** [comment]
these have been removed behind the scenes.
